### ISSUE TITLE
display warning on power tag deletion with a "confirm" dialog box

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#100]
Hi, this is a `first-timers-only issue`. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!
## The problem

Some tags on PublicLab.org pages ([like this one](https://publiclab.org/wiki/aerial-photography)) trigger specific features -- we call these [power tags](https://publiclab.org/wiki/power-tags), and they always have a `key:value` format with a colon in them. See this screenshot:

![screen shot 2016-10-25 at 1 40 04 pm](https://cloud.githubusercontent.com/assets/24359/19697289/c3ce9eca-9ab8-11e6-9310-747edb7708f8.png)

When power tags are deleted, some page functions may be broken, so we should warn people before they do so. 
## Solution

Use a confirm dialog box to alert people that they are deleting power tags, which may break something:

> This is a power tag (see https://publiclab.org/wiki/power-tags) -- and may drive a specific function on this page. Are you sure you want to delete it?

A confirm dialog box looks like this:

![screen shot 2016-10-25 at 1 42 35 pm](https://cloud.githubusercontent.com/assets/24359/19697586/ecf96a36-9ab9-11e6-987f-db7ed0d2adf8.png)

This can be added using a `data-confirm='Message text goes here'` attribute on the `<a>` link tag, like this:

``` ruby
<a data-confirm="This is a power tag (see https://publiclab.org/wiki/power-tags) -- and may drive a specific function on this page. Are you sure you want to delete it?" class="tag-delete" data-remote="true" href="/tag/delete/<%= @node.id %>/<%= tag.tid %>" data-tag-id="<%= tag.tid %>">x</a>
```

The template for that `<a>` tag is on this line: https://github.com/publiclab/plots2/blob/master/app/views/tag/_tagging.html.erb#L9
## Steps to Fix
- [ ] claim this issue with a comment here, below
- [ ] set up a repository locally and make sure that all tests pass
- [ ] start a pull request (see contributing to Public Lab software) but mark it as "in progress"
- [ ] fix the issue following the steps above
- [ ] make sure all tests pass with `rake test`
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by jywarren** [comment]
Reforming this as a `first-timers-only` issue! ([see here](https://publiclab.org/wiki/developers#Preparing+issues+for+newcomers))

**Comment by jywarren** [comment]
Hi, Bryan -- mind if I delete our comments to make this look a little less intense to a first-timer?

**Comment by ZettStai** [comment]
Hi, I'd like to try this one. Let me set up the repo locally and test and I can start working on it.

**Comment by jywarren** [comment]
That would be great, thanks and please ask if you run into trouble!

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by ZettStai** [comment]
I'm still trying to set this up locally on my Mac, but I'm running into issues with Solr. Since this is my first issue, would it be better to use a Cloud9 environment instead?

**Comment by jywarren** [comment]
That could work -- but in the latest version solr is no longer required for
development or testing... Do you have the latest version?

Thanks!!!

**Comment by darshan934** [comment]
Hi, I'd like to work on this. All i need is to make a pull request and change/add/delete code to fix the issue right? 
This is my first time contributing to OpenSource, hence i apologize if my questions sound stupid. 
Thanks :)

**Comment by ryzokuken** [comment]
@darshan934 I guess @ZettStai is working on this. Take a look at [other first timer issues](https://github.com/publiclab/plots2/issues?q=is%3Aopen+is%3Aissue+label%3Afirst-timers-only) to find one that suits you.

**Comment by darshan934** [comment]
@ryzokuken alright, thank you for your quick response :)

**Comment by ebarry** [comment]
Hi @ZettStai ! Thank you for reaching out to Public Lab! I would like to invite you to join us in a video conference to say a few words about what you found engaging about the Public Lab community and/or this particular github issue. The event is https://publiclab.org/openhour, and it’s coming right up on November 7th, at 1pm EDT which is UTC/GMT -4. 

Please feel free to respond here, or else email liz@publiclab.org, stevie@publiclab.org, jeff@publiclab.org.

**Comment by ZettStai** [comment]
@jywarren I tried reinstalling without Solr, but I'm still having issues on my mac. I was able to successfully deploy on cloud9 though after running the script a couple of times (the database didn't fully set up the first time for some reason). The tests complete now, but it says 0% passed. If that's expected, I'll go ahead and start working on this tomorrow. Sorry for the delay.

**Comment by jywarren** [comment]
Hi, ZettStai - if you paste the test output into a Gist at gist.github.com,
I can take a look; or, you can give me access to your cloud9 server to take
a look there. Thanks for your work to get this up and running!

**Comment by Jefferson-Faseler** [comment]
I have my environment running, I think I will try to tackle it.

**Comment by ZettStai** [comment]
@jywarren Here's the test output: https://gist.github.com/ZettStai/5675160a5b0e28d36d112eef1cc9b40c

**Comment by jywarren** [comment]
Hi, @Jefferson-Faseler -- it looks like @ZettStai got this one and finished it up in #951 -- but if you're looking for another challenge, we'd love to have your involvement in another `first-timers-only` issue here:

https://github.com/publiclab/plots2/labels/first-timers-only

Or a more general help-wanted issue: https://github.com/publiclab/plots2/labels/help-wanted

We may not have a huge # of remaining `first-timers-only` issues left, with the extra steps and helpful notes, as they're a lot of work to make. But if you look at `fto-candidate` issues, those are ones we haven't yet had time to format as nicely, but should be relatively easier, stand-alone issues you could tackle -- and of course we're happy to help you out on any of them:

https://github.com/publiclab/plots2/labels/fto-candidate

@ZettStai -- thanks a lot, and the same goes for you! Curious, how did you each find us? We're trying to get better at new contributor outreach.

**Comment by ZettStai** [comment]
@jywarren I saw one of your first-timers-only issues on Twitter @first_tmrs_only

@ebarry Thank you for inviting me. Unfortunately I won't be able to make attend, but I appreciate being invited

Thank you both for the opportunity. The instructions were very clear and I was almost overthinking it. Hope to contribute more in the future!
