### ISSUE TITLE
Increase width of drop down menu so title is readable

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#10013]
**Please describe the desired behavior.**

I am looking for this button to be wide enough to see the words "Filter period:" without the words being cut off and appearing as "Filter pei" which is making this menu needlessly cryptic: 
<img width="549" alt="Screen Shot 2021-08-10 at 10 05 36 AM" src="https://user-images.githubusercontent.com/161439/128881581-72990faf-4845-4c7d-aec5-a6a9cd7155e9.png">

See in the below screenshot, the first line in the drop down menu: 
<img width="742" alt="Screen Shot 2021-08-10 at 10 05 46 AM" src="https://user-images.githubusercontent.com/161439/128881640-f37e9c3b-4802-437d-97b4-65e03a045050.png">

**Additional context (optional)**

This is occurring on https://publiclab.org/stats?start=01-01-2020&end=20-08-2021
https://publiclab.org/stats

**Comment by ebarry** [comment]
this too narrow menu is only visible at narrow browser widths, but not so narrow that it loads in "mobile" view

**Comment by noi5e** [comment]
Replicating this issue (except with sliiightly wider width) on Firefox with MacOS Catalina:
<img width="505" alt="Screen Shot 2021-08-16 at 3 06 14 PM" src="https://user-images.githubusercontent.com/4361605/129635505-158fd0b6-4d36-4232-83fa-0de3da077cf7.png">

Here's where the changes need to be made:
https://github.com/publiclab/plots2/blob/2bb0cdd28c8d1a513b0161c402062f4edee4624d/app/views/stats/index.html.erb#L15-L20

The parent element has a Bootstrap class of `col-lg-2` which has a fixed width:
<img width="314" alt="Screen Shot 2021-08-16 at 3 11 47 PM" src="https://user-images.githubusercontent.com/4361605/129635769-0140b515-c6b3-47da-8dec-b43fd2b636c8.png">
