### ISSUE TITLE
Weekly Community Check-In #113 - The World Runs on Open Source

### ISSUE THREAD

**Issue by anirudhprabhakaran3** [publiclab/plots2#10010]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## The World Runs on Open Source

PublicLab is an open-source project and runs on a lot of open-source technologies. In fact, a lot of the world's most critical infrastructure works on open-source software. Even NASA's rovers use open-source technologies (you can see the rover badge on people's profiles who contributed to projects that were used by NASA).

It's kind of mind-blowing to me that there are hundreds of thousands of people, just like you and me, who make PRs and file issues and contribute to open source projects without any pay, for no other reason than genuine interest in the project and the code. These contributors help power the world's servers, computers, TVs, phones, satellites and even the rovers on other planets! What do you think?

## This week's focus Issues

These are issues that are of high priority and requests from our large community that use the software. 

https://github.com/publiclab/plots2/labels/high-priority

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note to focus issues contributors

Thanks so much @Ash-KODES, @luckych8080, @DalilaBA, @jywarren, @imajit, @Manasa2850, @hrishikeshnikam2000 for working on issues this week 🥇

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time!

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by unnati914** [comment]
Nice topic @anirudhprabhakaran3 💯

**Comment by unnati914** [comment]
What I believe is.. open source is for everyone :) and the feeling of doing a small tinch for the community and humanity gives me immense pleasure. The sense of happiness after doing something for someone is great 💯

**Comment by govindgoel** [comment]
Yeah totally agreed @unnati914, you feel awesome and connection with the community is also one thing I admire.

**Comment by ebarry** [comment]
Great topic @anirudhprabhakaran3 ! I love this. To me, open source is one of the brights spots in all of human endeavor. That sounds like an overstatement but people supporting each other to make something of use to even more people ... with equity providing continual course correction is rad!

**Comment by noi5e** [comment]
> Even NASA's rovers use open-source technologies (you can see the rover badge on people's profiles who contributed to projects that were used by NASA).

That is truly mind-blowing to me!!! Love this check-in @anirudhprabhakaran3.

The whole idea of open-source is really inspiring to me too.

**Comment by jywarren** [comment]
> Even NASA's rovers use open-source technologies (you can see the rover badge on people's profiles who contributed to projects that were used by NASA).

Wow! I wonder, should we get the badge for https://github.com/publiclab/infragram, which was built in part for/with NASA?

**Comment by unnati914** [comment]
moved to  #10045 💯
