### ISSUE TITLE
Separate map template out into a unique partial

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1001]
Small Leaflet maps are currently shown in sidebars here (scroll to bottom, look at left side):

https://publiclab.org/search/lima

The code driving that is here:

https://github.com/publiclab/plots2/blob/master/app/views/sidebar/_related.html.erb#L80-L108

We should make a template helper like`render_map(lat, lon, items)` which accepts an array of items that have `.lat` and `.lon` methods, so we can use maps in more places. 

The helper could go in: https://github.com/publiclab/plots2/blob/master/app/helpers/application_helper.rb

Eventually we could use this to generate an inline tag that shows a map, just like they currently show a table of results: https://publiclab.org/wiki/power-tags#Inline+power+tags

**Comment by mridulnagpal** [comment]
I would like to work on this issue

**Comment by jywarren** [comment]
Great, we'd love to have your help on this!
