### ISSUE TITLE
anniversary block's down margin is not aligned properly

### ISSUE THREAD

**Issue by max-keviv** [publiclab/plots2#10018]
**Please describe the desired behavior.**

this block of id "anniversary" in header, it's down margin is not properly aligned in phone resolution
> <div id="anniversary"><p>
<b>Want to talk about wastewater?</b> Join us for <b>Open Call</b> on this topic every Tuesday through September.
</p></div>

![Screenshot (229)](https://user-images.githubusercontent.com/59287619/128964454-d44e6062-0e08-40e9-8ad0-2f10dc2b40c3.png)

**Describe the solution you'd like.**

down margin should be of block should be increased 

![Screenshot (230)](https://user-images.githubusercontent.com/59287619/128964627-51057c8f-f79e-463a-a2d6-7f063b12945b.png)

what you think @ebarry

**Comment by ebarry** [comment]
Yes you're right! the banner should be as you illustrate. Perhaps this is a good candidate for a first-timers-only issue? I'll add a label to that effect. thank you!

**Comment by Tlazypanda** [comment]
Hey @max-keviv thanks for tracking down this issue :100: The anniversary element is not accessible on the dev codebase but is maintained at the production level but in this case the issue might be to change the `#header margin-top` in case of pages with pixels less than `768p` I think it's taking `68p` now so updating that to `75p` should work :)

**Comment by ebarry** [comment]
As site admin, i have access to this code in production via https://publiclab.org/features/11796/edit
@bhamster is currently maintaining this block. Does @max-keviv have recommendations for how we might better write the following HTML? 

****




 
<div id="anniversary"><p>
<b>Want to talk about wastewater?</b> Join us for <b>Open Call</b> on this topic every Tuesday through September. <a href="https://publiclab.org/wiki/open-call">Click here for call-in details!</a>
</p></div>






 
<style>
#anniversary {
  background:#eef; 
  padding:8px 10px;
  position:fixed;
  top:0; left:0;
  z-index:999;
  width:100%;
  font-size: 13px;
}

#anniversary b {
  color:#335;
}

#anniversary a {
  color:#339;
  text-decoration: underline;
}

#anniversary p {
  color:#115;
  margin:6px;
  padding-right:10px;
}

#anniversary .btn {
  float:right;
}

.body-container {
  margin-top:48px;
}
#header {
  margin-top:48px;
}

@media (max-width: 768px) {
  
  .body-container {
    margin-top:68px;
  }
  #header {
    margin-top:68px;
  }
}

</style>

**Comment by max-keviv** [comment]
@ebarry  thanks for asking 😊 @Tlazypanda is absolutely right 👍, we should implement this 

> the `#header margin-top` in case of pages with pixels less than `768p` I think it's taking `68p` now so updating that to `75p` should work :)
