### ISSUE TITLE
Move /blog links into the same <p> tag so they appear on a single line

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1007]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

On our Blog page, there are now three links below the header:

https://publiclab.org/blog

`About the blog`

`Research`

`Methods`

Let's move those to the same line, separated by a ` | ` -- on this line of code:

https://github.com/publiclab/plots2/blob/master/app/views/tag/blog.html.erb#L10-L12

Just move them into the same `<p></p>` tag, and that's it!

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by Kashyap12** [comment]
Hi can I take this up?

**Comment by jywarren** [comment]
We'd love your help on this and are happy to offer any assistance you might need. Thanks a lot!

Just curious -- we're trying to improve our outreach to new contributors -- how did you happen to hear about us?

**Comment by Kashyap12** [comment]
via Twitter handle @first_tmrs_only

**Comment by Kashyap12** [comment]
Hi @jywarren , I have made a pull request on the above issue, but I guess I ve messed up in creating a branch , I submitted the PR from my master, please let me know if you can merge the PR. Thanks :)

**Comment by jywarren** [comment]
Super -- i see that in #1010 -- thanks. Looking there.

**Comment by Kashyap12** [comment]
So can it be merged, or did I mess up somewhere ? @jywarren

**Comment by jywarren** [comment]
It can be merged -- it's your choice at this point. I made a request for a slight reformatting, but it's a stylistic change, not a functional one. Shall I merge, or would you like to tweak the indentations? 

Thanks!

**Comment by Kashyap12** [comment]
I would love to see it get merged :) @jywarren

**Comment by jywarren** [comment]
Great, i'll do it now. Thanks!
