### ISSUE TITLE
website tag pages are broken

### ISSUE THREAD

**Issue by dlebauer** [publiclab/plots2#10084]
### Please describe the problem (or idea)

Navigating the site, whenever I click a topic or tag, it directs me to `https://publiclab.org/tag/<tagname>` e.g. https://publiclab.org/tag/water-quality. All of these pages return an error e.g. 

![image](https://user-images.githubusercontent.com/464871/130538134-8ad4fe8d-f39b-4eb0-b030-a3b70c4ebe7c.png)

### Please show us where to look

Any of the topics on https://publiclab.org/wiki/topics

### What's your PublicLab.org username?

dlebauer

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

Windows 10 + edge v 92.0.902.67

**Comment by ebarry** [comment]
Hi @dlebauer  , 
Thank you for reporting this!
it may be possible that you were browsing the site when we were re-launching some new code or doing some other maintenance that affected this pages. I just tried to reproduce this, and am not currently seeing any problem with tag pages. Could you let us know what you're experiencing now? Thank you!

**Comment by dlebauer** [comment]
its working now, thanks!
