### ISSUE TITLE
Weekly Community Check-In #115 - Outreachy Summer '21 comes to an end 

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#10085]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Outreachy Summer '21 comes to an end 

We are finally at the end of the road with Outreachy Summer '21 cohort and just a week away from the end of Gsoc. Let's celebrate this time with the amazing contributions from our Outreachy Interns. We had some amazing work done from all the Summer of Code participants. 

On this occasion I invite all our interns to share their experiences of working with Publiclab :heart: 

If you are planning to write a final Blog :writing_hand:  sharing your experiences do share the link here for us to read :eye: 

And finally congratulations to all!!! :100:  We had a great time working with you and having you hear with us!!

### Thank you note to focus issues contributors

All our SoC interns - @Manasa2850 @TildaDares @17sushmita @daemon1024 @waridrox @imajit 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by Tlazypanda** [comment]
@jywarren, @anirudhprabhakaran3, @TildaDares, @daemon1024, @om2137, @arnab-2001, @Quado1, @daksh10110, @dependabot[bot], @DinSanGun, @micahweston, @17sushmita, @imajit, @aummishra, @Manasa2850, @vacom13, @sorutifokkusu, @Ash-KODES, @luckych8080, @DalilaBA, @hrishikeshnikam2000, @noi5e, @atayl16, @roshni-patel, @saraswathy-krish, @adrnna, @Pandademic, @DmitriiOxen, @jayeritz

**Comment by Arnabbibhuti01** [comment]
It's my first time here as well as in open source and I would be glad to be a part of this community.

**Comment by arnab-2001** [comment]
It's my first time here as well as in open source. I would be really glad to be a part of this community looking forward to working ahead.

**Comment by cesswairimu** [comment]
Congrats @TildaDares @Manasa2850 @17sushmita @daemon1024 @waridrox  @imajit :rocket: :rocket:

**Comment by waridrox** [comment]
Sorry that I almost forget...been busy with my exams lately 😅, Here's my experience with PL - https://publiclab.org/notes/waridrox/08-28-2021/gsoc-2021-experience-with-public-lab?_=1630156977

Would be eager to continue with contributions wherever possible 🎈🚀

**Comment by 17sushmita** [comment]
Hi all, Sorry for the delayed response. I had a really bad week as my laptop got some issues ☹️  so couldn't be active here. 
Talking about my experience with PublicLab, It has been amazing and full of new learnings. In whole, my GSoC period has helped me explore more about my specific interests such as I really enjoyed playing with Database queries and optimising it. I'm trying to focus more on learning Databases. Apart from the learning, I believe, not only GSoC but open source has helped me grow as a person to be more collaborative and good towards the community and I really admire the mentors here in PublicLab, they are so welcoming and appreciative. I'm looking forward to contribute more and help new contributors wherever possible 😃 

And here is the link to my GSoC final blog - https://publiclab.org/notes/17sushmita/08-23-2021/gsoc-report-tag-topic-system-refinements?_=1630232680

**Comment by jywarren** [comment]
Hi and congratulations @TildaDares @Manasa2850 @17sushmita @daemon1024 @waridrox @imajit !!! 🎉 🎉 🎉 

I've just submitted the last of our evaluations and it was our pleasure to pass all 6 of you. You've all done a tremendous job this summer and I plan to give more specific feedback and to celebrate your projects in the days and weeks to come. Please know that it's been an honor to work with you all, and many thanks as well to our code coordinators past and present @Tlazypanda @noi5e @RuthNjeri @cesswairimu and all of our mentors @publiclab/mentors @publiclab/soc who helped to make this process smooth and to support our excellent team. 👏 👏 👏

**Comment by jywarren** [comment]
And for reference, here are folks final posts!

* https://publiclab.org/notes/17sushmita/08-23-2021/gsoc-report-tag-topic-system-refinements
* https://medium.com/@waridrox/gsoc-2021-at-public-lab-final-report-7347b7edf466
* https://publiclab.org/notes/ajitmujumdar25999/08-21-2021/gsoc-2021-translation-system-refinement
* https://publiclab.org/notes/barun1024/08-22-2021/gsoc-2021-geographic-features-refinement-final-report

**Comment by Manasa2850** [comment]
I had a wonderful time working with Public Lab! I really learnt a lot this summer, both in terms of coding as well as in terms of being a part of the community. My heartfelt thanks to @jywarren and all other mentors for helping me throughout. Looking forward to continue contributing and help others contribute as well! :smiley:

**Comment by Pandademic** [comment]
Congrats to @TildaDares @Manasa2850 @17sushmita @daemon1024 @waridrox @imajit !

**Comment by TildaDares** [comment]
I'm beyond grateful to everyone at Public Lab for the opportunity to be your intern. Your constant feedback and guidance have helped me grow and learn so much for the past three months. I'd love to contribute more and help other contributors as well. Thank you!

**Comment by Tlazypanda** [comment]
Hey everyone! I am having such a blast reading all of your posts and all the skills both technical and non-technical you learnt in the process - 
- @17sushmita loved how you highlighted with every paragraph the exact skills you learnt 
- @waridrox loved how you kept going in the face of adversity and so many challenges
- @daemon1024 loved how you have highlighted collaboration and the breaking down of tasks into smaller ones
- @imajit loved how you approached the problem in a structural manner with an effort to onboard first-timers through future scope on your project 

Y'all are all amazing wishing you all the best for your upcoming years :100:

**Comment by aliciapaz** [comment]
Hi everyone!! 
I've been away from plots2 lately but I'm very happy to see such a successful end of summer internships 🎉 ❤️ 
Congratulations @TildaDares @waridrox @17sushmita @daemon1024 @imajit

Wishing you the best for your next challenges, journeys, kite flights!! 🐒 🪁🎈

**Comment by Tlazypanda** [comment]
New weekly check in open at #10126 leaving this open for an extra week to let folks chime in

**Comment by noi5e** [comment]
A belated congrats to all the interns this summer! @TildaDares @waridrox @17sushmita @daemon1024 @imajit. And thanks for making this check-in @Tlazypanda!

Closing this check-in now.

**Comment by ebarry** [comment]
What a great summer of contributions! Wow, your work has made / is making a huge impact for the Public Lab community. I made a sum-up tweet -- any corrections or additions of twitter handles? https://twitter.com/PublicLab/status/1435613144269922317

**Comment by RuthNjeri** [comment]
Congratulations everyone. You did it! @TildaDares @Manasa2850 @17sushmita @daemon1024 @waridrox @imajit ! :tada
