### ISSUE TITLE
Add Strings to Translation Function Call in _activity.html.erb

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#10102]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [_acitivity.html.erb](https://github.com/publiclab/plots2/blob/main/app/views/dashboard/_activity.html.erb) and  [_en.yml](https://github.com/publiclab/plots2/config/locales/en.yml) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

 [_acitivity.html.erb](https://github.com/publiclab/plots2/blob/main/app/views/dashboard/_activity.html.erb)
```diff
- 70     <li><a href="#"><a href="#">Post date</a></li>
- 71    <li><a href="#"><a href="#">Recent activity</a></li>
+ 70      <li><a href="#"><a href="#"><%= translation('dashboard._activity.post_date') %></a></li>
+ 71     <li><a href="#"><a href="#"><%= translation('dashboard._activity.recent_activity') %></a></li>
```
 [_en.yml](https://github.com/publiclab/plots2/config/locales/en.yml)
```diff
+ 313      recent_activity: "Recent activity"
+ 314      post_date: "Post date"
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by juank1809** [comment]
Hey! I'd like to work on this issue :)!

**Comment by Tlazypanda** [comment]
Hey @juank1809 go ahead :)

**Comment by TemitopeAgbaje** [comment]
Hello @Tlazypanda can i get a first timer issue

**Comment by noi5e** [comment]
I have reopened this FTO issue for anyone who wants it. @TemitopeAgbaje

**Comment by noi5e** [comment]
Reserving this issue for @Axuby, please claim it in the next 24 hours!

**Comment by RReiso** [comment]
Hi.Could I work on this issue?

**Comment by noi5e** [comment]
@RReiso, I've reserved this issue for @Axuby, they can claim it in the next day or two.

Meanwhile, I've added you to the list at #10153, if another issue comes up, I'll do my best to tag you there!

**Comment by RReiso** [comment]
Thanks!

**Comment by Axuby** [comment]
Ok thank you @noi5e 
Issue accepted.

**Comment by noi5e** [comment]
Great, thanks @Axuby!
