### ISSUE TITLE
'Help wanted' link in 'first time only' issue template.

### ISSUE THREAD

**Issue by chicken-biryani** [publiclab/plots2#10112]
**The Issue**

**The link 'help wanted' in the 'first-timers only issue template isn't linked correctly.**

The link is over here:

![image](https://user-images.githubusercontent.com/41121520/131218682-3a63ed7a-1db7-42ac-b9c0-e613ce553e44.png)

**How is it functioning:**

It takes the user over here 

![image](https://user-images.githubusercontent.com/41121520/131218145-139e43d7-b389-4c91-8169-9d538763877d.png)

**How it should function:**

It should ideally be taking a user over here - 

![image](https://user-images.githubusercontent.com/41121520/131218164-0a515525-e61f-4e1e-9baa-b26580299310.png)

**Proposed solution:**

Modify line 17 [over here.](https://github.com/publiclab/plots2/blob/main/.github/ISSUE_TEMPLATE/--first-timers-only.md)

Modify line 17:

`If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!`

To:

`If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues. Thanks!`

**Comment by chicken-biryani** [comment]
Hey, @Tlazypanda / @daemon1024 
Can I work on this?

**Comment by daemon1024** [comment]
Thanks for digging this out. ☺️

> Can I work on this?

Sure. Thanks a lot ✌️🙌
