### ISSUE TITLE
Issue with the Hyper-link in FTO template

### ISSUE THREAD

**Issue by Vishal01-git** [publiclab/plots2#10117]
Here the hyper-link that is attached with **_here is a great tutorial_** is not available now.

<img width="624" alt="issue1" src="https://user-images.githubusercontent.com/52890952/131453044-2845c361-b75e-4b53-b2ed-a3907bc4550e.png">

**First the link is this--**

>https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github

**Now it it this--**

>https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github

Have a look into this @jywarren @jywarren @Tlazypanda

**Comment by StephNathai** [comment]
Hi @noi5e, I can update this link if this issue is available, thanks.

**Comment by noi5e** [comment]
Thanks @StephNathai! Would you mind making a first-timer-only issue out of it, for a new contributor to solve?

**Comment by StephNathai** [comment]
@noi5e yea absolutely, will do!

**Comment by noi5e** [comment]
Great @StephNathai! We have a FTO template already set up when you click on `New Issue`.

When it's done you can tag the next person on the list at #10153!

**Comment by StephNathai** [comment]
Thanks @noi5e! Just created the FTO issue and tagged the next person in line (https://github.com/publiclab/plots2/issues/10188)

**Comment by noi5e** [comment]
Awesome @StephNathai, thanks! Closing this issue now.
