### ISSUE TITLE
overflow issue on (?) help icon and long powertag names

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#10124]
There's an overflow/overlap issue on the (?) help icon and long powertag names:

![image](https://user-images.githubusercontent.com/24359/131545386-12878abc-c301-445a-8810-5decdd95831d.png)

I'm not sure what to do about this visually! Can we force a wrap?

_Originally posted by @jywarren in https://github.com/publiclab/plots2/issues/9987#issuecomment-909421149_

**Comment by jywarren** [comment]
Yes, we should be able to. We can test this in the Chrome dev console too:

```css

    white-space: pre-wrap; /* css-3 */
    white-space: -moz-pre-wrap; /* Mozilla, since 1999 */
    white-space: -pre-wrap; /* Opera 4-6 */
    white-space: -o-pre-wrap; /* Opera 7 */
    word-wrap: break-word; /* Internet Explorer 5.5+ */
```

https://stackoverflow.com/questions/18891755/force-word-wrap-through-css

https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

Test this out on this page!:


https://publiclab.org/notes/bhamster/08-06-2021/building-a-coqui-water-conductivity-sensor-and-analyzing-its-sound

**Comment by StephNathai** [comment]
Hi, can I fix this?

**Comment by jywarren** [comment]
We'd love your help, yes! Do you think you could try opening a pull request? We're happy to help, here, in the weekly check-in at #10126, or in the chatroom at https://gitter.im/publiclab/publiclab ! 🎉

**Comment by StephNathai** [comment]
@jywarren Yep I'll open one. Lemme figure out the best fix and then it just needs a quick review from my employer and I'll push up the PR here.

**Comment by jywarren** [comment]
awesome!

**Comment by StephNathai** [comment]
@jywarren PR is up and ready for your review. Pease let me know if anything needs to be changed, thanks!
