### ISSUE TITLE
Non-image upload (PDF) to Google Cloud Storage not working (from wiki pages)

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#10120]
Dragging in a PDF to this page: https://publiclab.org/wiki/edit/frac-sand-mining-pollution-incident-report-form-and-guide

correctly processed and then generated and inserted this markup:

```html
<a href="/i/44764"><i class="fa fa-file"></i> via_main_menu_July_2021.pdf</a>
```

That link redirects to:

https://storage.googleapis.com/publiclab-production/public/system/images/photos/000/044/764/large/via_main_menu_July_2021.pdf

However that URL shows:

```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: publiclab-production/public/system/images/photos/000/044/764/large/via_main_menu_July_2021.pdf</Details>
</Error>
```

Could we be seeing a redirect issue affecting non-image files?

**Comment by icarito** [comment]
The PDF in question is uploaded to the `/original/` path, not `/large/` path!

**Comment by jywarren** [comment]
great. OK, so we need to change the display logic to return original if it doesn't match gif/png/jpg/jpeg. Thanks for catching that!!!

**Comment by jywarren** [comment]
This is probably due to https://github.com/publiclab/plots2/pull/9900

https://github.com/publiclab/plots2/blob/4ca8ad36ca1e8a23eeae18be5c03ab462474edaf/app/controllers/images_controller.rb#L7-L17

but we can modify the logic with `image.is_image?`
