### ISSUE TITLE
Gitpod startup issue - passenger taking too long?

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#10134]
Thanks to @DalilaBA for finding this issue, let's figure it out!

> Hi everyone, I don't know where to reach out really for help, I've had this error while executing "passenger start", everything went well during the installation I think, so can anyone help me on this ?
![image](https://user-images.githubusercontent.com/10799976/132101844-63b8502f-7c96-4335-ae93-481fe48b717a.png)

_Originally posted by @DalilaBA in https://github.com/publiclab/plots2/issues/10126#issuecomment-913001871_

**Comment by jywarren** [comment]
I had asked:

> Could you try pressing the refresh button on the preview window? I wonder
if it just got stuck the very first time when passenger was taking a long
time to load.

@DalilaBA commented 2 hours ago
> I did many times, but it is the same error

Hi @DalilaBA i'm not sure what the issue is, and I'm sorry it's causing trouble. Have you tried closing GitPod and starting it up fresh? I just opened it and it seems to be working on a fresh open. I think i've noticed GitPod isn't completely consistent, i think it may have to do with shifting dependencies, or upstream services and their response time... it's a little disconcerting but I can't see a reason it'd work for me but not you, apart from just random luck if it's an intermittent issue.

**Comment by jywarren** [comment]
If you see it again, could you paste in here the contents of the `Detailed diagnostics` tab? 
![132101844-63b8502f-7c96-4335-ae93-481fe48b717a](https://user-images.githubusercontent.com/24359/132135336-64d93349-d934-4afb-9b78-9feefd0c2938.png)

**Comment by DalilaBA** [comment]
Hi @jywarren thank you very much for your help, you don't have to be sorry, I'm happy to learn.
I don't really understand what you mean by refreshing the GitPod, I cloned and installed the project locally following the steps wrot in the README file.
and here is the detailed diagnostics : 
![image](https://user-images.githubusercontent.com/10799976/132136910-4aa3c8fc-153a-4a86-bcfe-89aa541b8e2d.png)

**Comment by DalilaBA** [comment]
Hey @noi5e can you please help me on this issue ??

**Comment by DalilaBA** [comment]
hi @noi5e , here is the rest of the error : 
![image](https://user-images.githubusercontent.com/10799976/133142023-af6dcf85-5e1a-4c16-8abd-7e48e4b7fbfc.png)


and yu know it got me thinking maybe it is a permission problem with the WSL ubuntu and the C:/ directory of Windows...

**Comment by noi5e** [comment]
> and yu know it got me thinking maybe it is a permission problem with the WSL ubuntu and the C:\ directory of Windows...

Sounds like it could be something like that. Here's what you get when you query the error message:
https://www.google.com/search?client=firefox-b-1-d&q=insecure+world+writable+dir+%2Fmnt%2Fc+in+path

**Comment by DalilaBA** [comment]
yes, look what I found : "  ....I'm sure the devs are aware of this, and that's why they definitely do not recommend running WSL as a server platform (also the disk i/o performance would be pretty atrocious for such a purpose). This will likely change in the future...."
so I'm gona try and install it via windows directly

**Comment by jywarren** [comment]
My apologies @DalilaBA i thought you were using our GitPod system to get it running. If you haven't tried, and are still stuck on this step, it's a very fast way to get the system running in just a few clicks, in a standard virtual environment online!

You could start it up by clicking the GitPod button at the top of the Readme on this page: https://github.com/publiclab/plots2/

or with the URL: https://gitpod.io/#https://github.com/publiclab/plots2

Just in case you can't get it running locally!

**Comment by DalilaBA** [comment]
Alright thank you @jywarren 😁

**Comment by DalilaBA** [comment]
@jywarren @noi5e it is working perfectly fine on the gitpod, thank you very much for you're help

**Comment by noi5e** [comment]
Thanks everyone, closing this issue!

**Comment by jywarren** [comment]
OK, that sounds great @DalilaBA. Tell us how it goes!

**Comment by jywarren** [comment]
Oops, this was a stray tab that hadn't updated and now i see the updates. Never mind! Thanks! Retitled it for clarity too. :-)

**Comment by DalilaBA** [comment]
No problemo 👍
