### ISSUE TITLE
Weekly Community Check-In #117 - We Love 🌍 

### ISSUE THREAD

**Issue by noi5e** [publiclab/plots2#10141]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

## We Love 🌎 !

Something different this week! I think most of us know about [Public Lab's mission](https://publiclab.org/about): 

> Pursuing Environmental Justice through Community Science and Open Technology

Revisiting this mission got me thinking... Everything small code change we make in this repository supports people's access to clean water, clean air, and clean nature. 

**Is there a beautiful place on Earth that you love? Even somewhere you haven't been yet but would like to go? Post about it in the comments for this week's check-in!**

## Welcome Outreachy Winter Applicants! ❤️ 

This week, we also continue to welcome folks who want to apply for the Outreachy Internship Winter 2021 cycle. Feel free to introduce yourself in the comments as well, ask for help, or ask questions about our community!

The contribution period for the Outreachy Internship application opens on **October 1st**, but it's never too early to get familiar with our codebase and prepare to make contributions.

Things you can do include:
- Introduce yourself on our Gitter chatroom
- Complete a first-timer-only issue, if you haven't done one yet
- If you have completed an FTO, we encourage you to make your own FTO issue to help introduce more first-timers to our community. You can follow the guide that @imajit made here: #9945
- Help someone make a pull request for the first time, or get their local environment set up.
- Open a weekly check-in like this one!

## Key Issues

For Outreachy applicants who are looking for some issues to take on after completing a first-timer-only issue, I suggest taking a look at these issues. 

Some of them seem a little easy, others are more challenging, but either way you will develop the skills you need to research our codebase and solve problems! 💯 

- #10140
- #10118
- #10117
- #10112
- #10088
- #10084

It can be challenging making the leap into researching complex problems like this, but that's what we're all here for! Leave a comment if you need help and we'll do our best to help 🤗 

### Thank You to Our Contributors This Week 🥇 

Thank you to everyone who made a commit to the codebase, made an issue, or code reviewed this week:
@chicken-biryani @sandipanpanda @Ishan2077 @suryablaster @noi5e @jywarren @Ash-KODES @RazaKhanGit @17sushmita @Onyinye91-ctrl @imajit @Manasa2850 @Vishal01-git @Tlazypanda ... and everyone else I missed!

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by noi5e** [comment]
Here's a photo of a place on Earth I discovered last week! Montecito Hot Springs near Santa Barbara: 
![1-hot-springs-canyon-montecito-santa-barbara](https://user-images.githubusercontent.com/4361605/132441248-d038a8ae-55c3-47d0-bd00-b1892e23beb4.jpg)

**Comment by Vishal01-git** [comment]
Thanks @noi5e , I'm always ready to contribute to open source , Please if you have any FTO issues assign me , i'm open to take that.

**Comment by ebarry** [comment]
gorgeous place @noi5e ! I love hot springs.

**Comment by Tlazypanda** [comment]
Great check-in @noi5e Welcoming all Outreachy aspirants :heart:

**Comment by noi5e** [comment]
> Thanks @noi5e , I'm always ready to contribute to open source , Please if you have any FTO issues assign me , i'm open to take that.

Great @Vishal01-git! I'm planning on making some more later this week, so keep your eyes peeled!

**Comment by RuthNjeri** [comment]
Hi everyone!! This is a lovely check-in @noi5e.

I mostly want to visit New England one day because of Mark Weins https://www.youtube.com/watch?v=ZTHGIifvqf4 
![image](https://user-images.githubusercontent.com/7622875/132727281-f17268fc-9bd1-4134-a467-07cb2c195116.png)

**Comment by Jon-Jos** [comment]
Hi everyone! 😄
I'm John, you can call me Jon. I have free time to hit the keys, fond of nature and I like Public Lab's karma! I'm pursuing b.tech cse.  I ❤️ to contribute to Public Lab 🎈 and I'm happy to be assigned with a first-timers-only issue.  
Thankyou for your reply @Tlazypanda

**Comment by unnati914** [comment]
nice check-in @noi5e 💯

**Comment by ishitakeshawani** [comment]
Hello, I am Ishita Keshawani. Looking forward to learning from the community and contribute to projects :sparkles:

**Comment by Hina-softwareEngineer** [comment]
Hello everyone, 
I'm Hina. I am starting my open-source journey and I like to contribute to open-source, learn and grow with all of you here. ✨✨
Thanks

**Comment by noi5e** [comment]
Wow those are a lot of clams @RuthNjeri, nice to hear from you!

Welcome to Public Lab, @ishitakeshawani @Hina-softwareEngineer @Jon-Jos!!!

**Comment by Tlazypanda** [comment]
Closing this new check in at #10154 Thanks everyone :v:

**Comment by jywarren** [comment]
Hi all! I missed this one, my apologies, but i love the photos! Thanks @noi5e for the check-in. I'll say I love the beach, especially in New England, which is why i was away last week -- here's a picture of a horseshoe crab I found! 

![image](https://user-images.githubusercontent.com/24359/133684872-a920d59f-64e1-4a02-af1e-49d80c5e4fff.png)

❤️ 🌎
