### ISSUE TITLE
Hidden menu button in navigation bar.

### ISSUE THREAD

**Issue by Jon-Jos** [publiclab/plots2#10144]
### Please describe the problem (or idea)

Hidden menu button in navigation bar when browser in half window and in android when the orientation is changed to landscape.

https://user-images.githubusercontent.com/71092045/132849662-03734c9d-0053-4faa-8fea-d84a8b8adcb8.mp4

### Please show us where to look

https://publiclab.org

### What's your PublicLab.org username?

username : jonjos

### Browser, version, and operating system

Windows, Android 
Google Chrome : Version 93.0.4577.63 (Official Build) (64-bit)

**Comment by Jon-Jos** [comment]
repo ???
Please share the repository of the code, 
I couldn't find it.

**Comment by Tlazypanda** [comment]
Hey @Jon-Jos I think this is where you should look into. Thank you! 

publiclab/plots2/app/views/layouts/_header.html.erb Line 202
```
        <li id="md-ham" class="d-lg-none dropdown">
          <a href="#" class="btn btn-dark" data-toggle="dropdown"><span class="fa fa-white" style="vertical-align: middle;"></span></a>
          <div class="dropdown-menu dropdown-menu-right">
            <a class="dropdown-item d-lg-none" href="//store.publiclab.org"><%= translation('layout._header.store') %></a>
            <a class="dropdown-item d-lg-none"  href="/donate"><%= translation('layout._header.donate') %></a>
            <!--These menu items will only appear in the "More" dropdown menu. -->
            <% if current_user %>
              <a class="dropdown-item d-xl-none" rel="tooltip" title="<%= translation('layout._header.your_dashboard',{},false) %>" data-placement="bottom" href="/dashboard"><%= translation('layout._header.dashboard') %></a>
            <% else %>
              <a class="dropdown-item d-xl-none" rel="tooltip" title="<%= translation('layout._header.become_part_community',{},false) %>" href="/signup"><%= translation('layout._header.join') %></a>
            <% end %>
          </div>
        </li>
```

**Comment by Jon-Jos** [comment]
Hi 😄
Made the Drop Down Menu Button appear! properly.
Should I make a pull request @Tlazypanda @aliciapaz ??
![gif1](https://user-images.githubusercontent.com/71092045/133503100-dc474903-b6be-462a-9dc4-d317d09fb539.gif)

**Comment by aliciapaz** [comment]
Sure @Jon-Jos! 
Thank you!!
