### ISSUE TITLE
Redirect /post to /editor unless it's an event post

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1014]
We're pretty much ready with our new rich editor (at https://publiclab.org/editor) except for event posting, so we should set a redirect now in the editor_controller, unless someone specifically wants the old one. So let's rename the `post` action to `legacy`:

Then, make a new `post` method which checks if we definitely want the legacy version, and if not, redirects to the new editor. 

But since we don't yet have the events widget working in the new editor, we should also go to the legacy editor if it's going to be an event:

```ruby
def post
  if params[:legacy] || params[:template] == "event"
    flash.now[:notice] = "This is the legacy editor. For the new rich editor, <a href='/editor?#{request.env['QUERY_STRING']}'>click here</a>."
    legacy
  else
    flash.now[:notice] = "This is the new rich editor. For the legacy editor, <a href='/post?#{request.env['QUERY_STRING']}&legacy=true'>click here</a>."
    rich
  end
end
```

I think that'll work, though it'll likely cause some test errors which will have to be adjusted for the new rich editor page.

**Comment by mridulnagpal** [comment]
I would like to work on this issue

**Comment by jywarren** [comment]
We'd love your help on this and are happy to offer any assistance you might need. Thanks a lot!

Just curious -- we're trying to improve our outreach to new contributors -- how did you happen to hear about us?

**Comment by mridulnagpal** [comment]
I heard about it from a friend of mine

**Comment by mridulnagpal** [comment]
In which file do I change the following ?

**Comment by jywarren** [comment]
Hi, responded in your pull request. Thanks!!!

**Comment by ykl7** [comment]
@jywarren @mridulnagpal If this is still open, would you mind if i had a look at it?

**Comment by jywarren** [comment]
I believe there's an open PR in #1021 -- I think it's still in progress, but with @mridulnagpal's permission you could build on the commits there?

**Comment by ykl7** [comment]
Hi! I'm unable to get work done on this issue. If anyone else wants to, please go ahead and claim this to start with

**Comment by mridulnagpal** [comment]
@jywarren M back on it

**Comment by ykl7** [comment]
Thanks @mridulnagpal

**Comment by jywarren** [comment]
Great, left a comment over on the PR at #1021 -- thanks!

**Comment by mridulnagpal** [comment]
@jywarren I think this issue is resolved

**Comment by jywarren** [comment]
True!
