### ISSUE TITLE
Weekly Community Check-In #118 - Music to code 🎹 🎵 

### ISSUE THREAD

**Issue by aliciapaz** [publiclab/plots2#10154]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Music to code 🎶 🎧 

Life wouldn't be the same without music! It helps us to relax, focus and connect with deep mental and emotional states. Coding with the right beat can make you feel like a real hacker! 👩🏽‍💻 
This week let's share our favorite playlists/albums/songs to code to! 

## Welcome Outreachy Winter Applicants! 🗺️ 

This week we continue to welcome folks who want to apply for the Outreachy Internship Winter 2021 cycle 🪁 

The contribution period for the Outreachy Internship application begins on October 1st, but you can start getting familiar with the codebase and prepare to make contributions. 

These are some ideas to get you on board:

- Introduce yourself in the comments below
- Introduce yourself on our [Gitter](https://gitter.im/publiclab/publiclab) chatroom
- Complete a first-timer-only (FTO) issue, if you haven't done one yet
- If you already completed an FTO, you can create your own FTO issue to help introduce more first-timers to our community. You can follow this guide on how to do so: https://github.com/publiclab/plots2/issues/9945
- Help someone make a pull request for the first time, or get their local environment set up.
- Open a weekly check-in like this one!

## Key Issues

The following issues are great candidates for Outreachy applicants who are looking for an issue to work on after completing a first-timer-only. 
- https://github.com/publiclab/plots2/issues/10144
- https://github.com/publiclab/plots2/issues/10140
- https://github.com/publiclab/plots2/issues/10118

We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by aliciapaz** [comment]
Here is one of my favorite OSTs to code to. Four hours of awesome music, with a wide range of styles and moods 🤸🏽‍♀️ 

https://www.youtube.com/watch?v=QOWepkAK5FA

I hope you enjoy it!

**Comment by Tlazypanda** [comment]
@arnab-2001, @StephNathai, @jywarren, @dependabot[bot], @DalilaBA, @chicken-biryani, @sandipanpanda, @Ishan2077, @suryablaster, @noi5e, @Ash-KODES, @RazaKhanGit, @17sushmita, @Onyinye91-ctrl, @imajit, @sorutifokkusu, @poojap10, @TildaDares, @anirudhprabhakaran3, @daemon1024, @om2137, @Quado1, @daksh10110, @DinSanGun, @micahweston

**Comment by Tlazypanda** [comment]
Aah I love this check-in idea :heart: Will definitely check out the link you shared @aliciapaz!
I just like to listen to piano soundtracks from movies/series - Your lie in april soundtracks, Anything with Hans Zimmer and since I am trying (emphasis here on trying :p) to learn Spanish lots of Spanish tracks that well kinda distract me from coding and make me wanna dance :D 

Would love to hear from @jywarren, @noi5e on this prompt :v:

**Comment by anirudhprabhakaran3** [comment]
Great idea @aliciapaz ! Most of the time when I'm coding, I just let Spotify go on shuffle XD. The few times that I actually put something specific is usually songs by FINNEAS (he's my favourite artist), some cinematic themes and a little bit of hip hop. It feels great to be coding while there are great hihats playing on your headphones 🎵

**Comment by daemon1024** [comment]
Same as @anirudhprabhakaran3 mentioned, I usually have Spotify on shuffle 🎧🎶

I have been recently listening to https://youtube.com/c/MyAnalogJournal which @noi5e shared in one of weekly SoC calls 🙌

Coincidentally GitHub asked about something similar today https://twitter.com/github/status/1438239431874338817?s=19 🎵

**Comment by DalilaBA** [comment]
Ahh I'm a music lover, music is really good for the brain, as said in the "Hardvard health publishing" : << music can activate almost all brain regions and networks, it can help to keep a myriad of brain pathways and networks strong, including those networks that are involved in well-being, learning, cognitive function, quality of life, and happiness. >>

Same as @Tlazypanda i like classic music especially Ludovico Enaudi's songs, he is realy great Artist, and adding the rain sound in the background is just perfect...

But ther is something that I wanted to share with you guys, "Purple noise" (music frequencies), one of the best DJ is [Boris Brejcha](https://borisbrejcha.com/home) I dnt know if you heard about it, here some quotes wrote on his website  : "While on the darknest night you will lose your biggest fear and feel the awakenings of your true inner being, the melodies will unbelieveable originate a feel of freedoom, like standing on zero gravity, giving you an illusion of being able to swim to the moon and back.", try it your self, I like this compilation : 
 - https://www.youtube.com/watch?v=Pz29ToCtd1U&ab_channel=D1gitalSound
 - https://www.youtube.com/watch?v=fO-aXupndhM&ab_channel=Ztsky

I have a really large taste when it comes to music, POP an R&B are included, but I wanted to share with you another kind of music, the arabic one's, I'll not say much just try it and enjoy 😄 : 
- https://www.youtube.com/watch?v=FC6cJOwS018&ab_channel=Aleph
- https://www.youtube.com/watch?v=G27os9WrXgk&ab_channel=D33pSoul-Topic
- https://www.youtube.com/watch?v=azcGdik3T7I&ab_channel=D33pSoul-Topic
- https://www.youtube.com/watch?v=ddoUBC1qrgg&t=865s&ab_channel=CafeDeAnatoliaETHNOWORLD

**Comment by noi5e** [comment]
Wow yeah, thanks for this check-in @aliciapaz! Great topic.

Like Barun mentioned, one of my go-tos recently has been My Analog Journal, where you get to see DJs spinning vinyl from all around the world:
[Psychedelic Cumbia](https://www.youtube.com/watch?v=k8OwzWNZEUI)
[Peruvian Chicha](https://www.youtube.com/watch?v=6GwdWSx8v0c)
[Arabic Tapes & Records](https://www.youtube.com/watch?v=HxaM6UJpAyg)

I know that @jywarren listens to Brazilian music sometimes when coding:
[IT'S BRAZIL BABEEEE](https://www.youtube.com/watch?v=VbA4V5KYdqY)

I spent a lot of the Outreachy internship listening to Justice Der on repeat. He's a really talented guitarist!
[Justice Der - Covers](https://www.youtube.com/watch?v=mPymRFeTJa4)

**Comment by chicken-biryani** [comment]
I've been looking for new music to listen to for a change.

I feel that sharing music is similar to saying "Hey, here's a piece of my soul".

So, thank you to for sharing.❤️

Here's a fraction of my soul 😅 -

[Pink Floyd - Slippery Guitar](https://open.spotify.com/track/4BTEQr44jGASYX7VG21i3d?si=t-l0HYMSRHqfeH8aAiZXPQ&utm_source=copy-link&dl_branch=1)

**Comment by jywarren** [comment]
Ooh!! I've also been using MyAnalogJournal, thanks @noi5e for the tip! I like all those lofi-hiphop youtube channels, esp. Brazilian Lofi Hiphop, and I also sometimes code to really loud Mozart's Requiem, lol 😂 

But honestly i haven't been listening to music as much while coding recently, so i bet my coding has been suffering!!! 😅

**Comment by jywarren** [comment]
OMG someone should make a playlist of all the great suggestions here! 🤯 💥 ❤️

**Comment by DalilaBA** [comment]
Oh @jywarren speaking of Lofi music, I've made one a long time ago 😅 
https://youtu.be/YkHh53S6hKU
I would love to have some feedbacks 😁

**Comment by TildaDares** [comment]
Thank you @aliciapaz This check-in topic is a wonderful idea. I don’t really have something specific I listen to when I code, I just press the shuffle button and code away. 

There are so many new things to try in this thread. 

@DalilaBA I listened to the Lofi music you uploaded on YouTube and I loved it. It’s very calming and I’m going to listen to it while I code now.

**Comment by DalilaBA** [comment]
@TildaDares I'm happy that you like it 😊

**Comment by jywarren** [comment]
> Oh @jywarren speaking of Lofi music, I've made one a long time ago 😅
> https://youtu.be/YkHh53S6hKU
> I would love to have some feedbacks 😁

Oh wow I'll give this a listen today!!! ✨✨

**Comment by aliciapaz** [comment]
Wow!! Thank you all for your responses and shares 🎉 
I'm a little crazy about music myself so I love having all this new music to listen to 🙈  

I've been listening to MyAnalogJournal and Justice Der, great music there! Thank you @noi5e.

@Tlazypanda I love Hans Zimmer and Your lie in April soundtracks as well 😻 I loved that anime... it made me cry lol
If you like jazz, Kids on the slope has great music and a beautiful story as well (I'm a big fan of Watanabe's anime as you can see, but that's a whole different topic!).

Thanks again to y'all for making this weekly check-in awesome ❤️ 🎸 🎷

**Comment by jywarren** [comment]
OMG @DalilaBA you made this? it's incredible!! 🌠 I loved the raindrops syncing with the beat, especially!

**Comment by 17sushmita** [comment]
Woww! Really great topic @aliciapaz. What a wonderful conversation going on😍
I too love to listen music(and sing crazily🤣) while coding. My favorites are all kinds of Indian music. I usually like to listen in group with my friends on discord and code at the same time. If someone uses discord here, you must be familiar with Rythm bot that we use to play music. But recently YouTube changed few guidelines so Rythm has stopped its services😕 on 15th September I guess. So now we've moved on to Mee6 bot😀

**Comment by imajit** [comment]
Love the topic for this weekly :100: 
When I code, I don't listen to music since I get distracted by it and forget about the code :rofl:, but in my spare time, I enjoy listening to raps.

**Comment by Goodiec** [comment]
Hi everyone, I'm Goodness, an Outreachy applicant interested in the "Refine the Public Lab Rich Editor" project. I am looking forward to contributing to this community! I would love to open the next check-in, it's my first time, and would appreciate any help I can get. Thank you.

**Comment by TildaDares** [comment]
Thanks, everyone. Closing this and moving the next check-in to #10305
