### ISSUE TITLE
wrong link after loging in

### ISSUE THREAD

**Issue by DalilaBA** [publiclab/plots2#10155]
### Please describe the problem (or idea)

after login in for the first time, I was redirected to localhost/home
I logged in from this page : 
![image](https://user-images.githubusercontent.com/10799976/133451305-7fe86b7c-7fdd-4f32-be52-f2895d7706e7.png)

> What did you expect to see that you didn't?

beeing redirected to the dashboard

### Please show us where to look

https://3000-aquamarine-stork-lqza3xwy.ws-eu16.gitpod.io/login

### What's your PublicLab.org username?

> This can help us diagnose the issue: I used the admin id

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!
last version of Opera

****

**Comment by noi5e** [comment]
@DalilaBA, thanks for opening this issue!

This issue needs more detail, maybe screenshots, GIFs or videos?

The following link you posted leads me to a blank white page: https://3000-aquamarine-stork-lqza3xwy.ws-eu16.gitpod.io/login

I just tried logging in with GitPod on the `main` branch of `plots2` which you can access on the [repo's homepage](https://github.com/publiclab/plots2)

Here's a video of what happened when I login with GitPod, everything seems to work fine:
https://user-images.githubusercontent.com/4361605/133679166-a0f4b8af-cc96-4888-ac9b-e747d867a736.mov

**Comment by DalilaBA** [comment]
@noi5e haha, when I user the gif recorder it worked just fine too, well it is fixed 😄
