### ISSUE TITLE
Hacktoberfest Contributing Discussion :fire: How can you help?

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#10186]
Hey Everyone! :wave: 

We are thinking of participating in Hacktoberfest and for that we need to lay down some community rules and share some ideas to get the momentum going for Hacktoberfest :tada: 

Please feel free to share your ideas on what we should do. You can help out by -
- Creating ftos using #9945 or for normal bug fixes which we will be tagging as hacktoberfest issues later
- Creating markdown documentation for the participants (hacktoberfest specific contributing guidelines)
- Sharing any resources for us to look into and follow
- Sharing about this on social platforms to engage more participants

Hoping for the community members to join hands & celebrate the spirit of Hacktoberfest :100:

**Comment by Tlazypanda** [comment]
@ZacharyGillmore, @noi5e, @jywarren, @Jon-Jos, @chicken-biryani, @comic-dev, @Vishal01-git, @Hina-softwareEngineer, @arnab-2001, @StephNathai, @dependabot[bot], @DalilaBA, @sandipanpanda, @Ishan2077, @suryablaster, @Ash-KODES, @RazaKhanGit, @17sushmita, @Onyinye91-ctrl, @imajit, @sorutifokkusu, @poojap10, @TildaDares, @anirudhprabhakaran3, @daemon1024, @om2137, @Quado1, @daksh10110, @DinSanGun, @micahweston, @aummishra, @Manasa2850, @vacom13, @luckych8080, @hrishikeshnikam2000, @atayl16, @roshni-patel, @saraswathy-krish, @adrnna

**Comment by chicken-biryani** [comment]
Hey,

I would love to help out.

Just a question...

Can we clarify our ideas under this issue itself that, "Hey I think this can be a first good issue."... or over Gitter... or... Just create the issue, and if it's relevant it would be good to go else it'd just get closed?

You know till we get a hang of creating a good fto issue.

**Comment by Jon-Jos** [comment]
Wow great!  @Tlazypanda 😁

Can someone shed  light 💡 on these queries...

(1/2) 
Which are the

1. languages 
2. tools
3. frameworks 
4. libraries 
5. toolkits 
6 ... 
7 ... 

 a contributor must learn! in Public Lab?

(2/2)
Which are the areas  Public Lab currently need code development (bug fixes, improvement)?
 
and which are the technologies used in that specific area ?

🚀 Hacktoberfest 2021  🌳🌳🌳

♥️

**Comment by noi5e** [comment]
Yay, this is exciting @Tlazypanda, thanks for opening!

> Can we clarify our ideas under this issue itself that, "Hey I think this can be a first good issue."... or over Gitter... or... Just create the issue, and if it's relevant it would be good to go else it'd just get closed?

@chicken-biryani Either one is fine!

@Jon-Jos, definitely Rails and JavaScript! We have almost 600 issues open, so plenty of places to start 😅

**Comment by jywarren** [comment]
@Tlazypanda ty so much for getting this going! Let's think about marking FTOs without using the `first-timers-only` label /yet/ so they don't get snapped up? We could also leave a comment that could later be deleted maybe...

@chicken-biryani we do have a `fto-candidate` label which we use to mark "almost done" FTOs before they get the official label. They they could get reviewed by @noi5e @Tlazypanda or myself (or other past code community coordinators if they're around) before getting the final label? If that sounds good to you? Once you've written/prepared one all the way through, you're probably good to make others on your own though.

@Jon-Jos great questions. We have some pretty thorough introductions up at https://code.publiclab.org, our welcome page. You actually don't have to know any of those things to participate in a first-timers-only issue, although as @noi5e says, JavaScript or Ruby could help. We try our best to offer a very low-barrier starting point for newcomers!

**Comment by anirudhprabhakaran3** [comment]
Hello! This is great.

I think we can expand on the present CONTRIBUTING.md to make a better document for anyone who is actually interested in Hacktoverfest. That way we can get higher quality PRs and issues can be solved better.

**Comment by unnati914** [comment]
Hello! 
Thanks for opening this, really excited for this. We can actually have a blog stating what publiclab does(I know we already have it on the website) but this can be a good fto for new comers, these can help them in their technical skills as well. And we can actually share this on socials too and ways to contribute ofcourse!
Let me know any suggestions or improvements if any :)

**Comment by DalilaBA** [comment]
Awsome thank you @Tlazypanda, there is so many good ideas over here, I'm happy to help, there is a lot of work on the translation files that can be used as FTOs
But I do have some questions about the translations, how can we change the language on the Dev side since we don't have the functionality on the footer ?

**Comment by Vishal01-git** [comment]
Great decision @Tlazypanda of participating in Hacktoberfest , this will help many open source enthusiast to know about publiclab.
And i can help you by spreading about this in my community.

**Comment by DalilaBA** [comment]
@Tlazypanda got it, I'll get into it as soon as I get home 😁

**Comment by om2137** [comment]
Hey, 
I did FTO and had my first PR merged here at Public lab, very new to contributing to open source. But would love to help out, if there is anything to be get done.

**Comment by atayl16** [comment]
This is me as well. I did one and would love to help, but really have no
idea where to start. Is there a guide somewhere for those of us that are
excited, did our FTO and want to do more?

**Comment by anirudhprabhakaran3** [comment]
@Tlazypanda working on the doc

**Comment by jywarren** [comment]
Yay and welcome folks! One thing that really helps is if we can encourage newcomers to help other newcomers. If there are open FTOs and people seem a bit stuck, or just need encouragement, that's really helpful! 

I don't know if we can make Hacktoberfest issues which encourage this, but even outside of Hacktoberfest, this is a really critical area of support which newcomers are really good at -- because they know what it's like! And have the most recent experience of overcoming the challenges of contributing!

**Comment by anirudhprabhakaran3** [comment]
Hello everyone!

I have prepared a document for guidelines for Hacktoberfest. It would be great if y'all could go through it, and provide feedback - anything that I missed out on or should add!

https://docs.google.com/document/d/1w3Y_Xy4MJEeV6rxK9qorsMcFLYj2lVY785hMUYtvHJo/edit?usp=sharing

I'll be making this into an MD file so that it can be merged into the codebase.

**Comment by ebarry** [comment]
Thank you! Looks great as far as i can tell! I added a line near the top to link to code.publiclab.org

**Comment by chicken-biryani** [comment]
Hey,
@Tlazypanda and @noi5e ,
I hope you're doing well.

Are there any particular guidelines/posters I could circulate around for hacktoberfest or in general?

I am sure there are people in our universities who are looking to contribute and start their journey with open source but aren't as aware.

**Comment by Tlazypanda** [comment]
Hey @chicken-biryani yeah here's the link - https://github.com/publiclab/plots2/blob/main/HACKTOBERFEST.md

Also since we T-2 hrs from Hacktoberfest hoping for all the contributors in this thread to help out with opening issue, reviewing prs or in any capacity they can :tada:

**Comment by chicken-biryani** [comment]
Hia!
Created an issue that maybe can be broken down into 3-4 first-timer issues.
https://github.com/publiclab/community-toolbox/issues/502

Create the folder and then an issue each to create a sub-template.

**Comment by jywarren** [comment]
Hi all! Just closing this up for the year! Thank you!!!!!
