### ISSUE TITLE
CodeClimate issues reported on models/user.rb

### ISSUE THREAD

**Issue by brunoocasali** [publiclab/plots2#10218]
### Please describe the problem (or idea)

This is not a bug, but a wip-tracking issue about the `user.rb` file.
Accordingly to codeclimate we have multiple issues there that could be addressed one by one.

### Please show us where to look

https://codeclimate.com/github/publiclab/plots2/app/models/user.rb/source#issue-f685bcbb6f822884dec234767db1861a

**Comment by KarishmaVanwari** [comment]
Can I work on this? @brunoocasali

**Comment by brunoocasali** [comment]
Yes @KarishmaVanwari, please!

**Comment by KarishmaVanwari** [comment]
Could you please assign me this issue? @brunoocasali

**Comment by brunoocasali** [comment]
No actually, because I'm not a member of publiclab 😅

**Comment by jywarren** [comment]
Sorry folks just to clarify here, it's OK to begin working without formally assigning, because we often get contributions from folks not listed part of the org (because they're new) and so we usually skip assigning to smooth the process. Sorry for the ambiguity!

**Comment by KarishmaVanwari** [comment]
Hey @jywarren @brunoocasali I've opened a PR #10779. Please have a look. Thanks!

**Comment by KarishmaVanwari** [comment]
Hey @jywarren @brunoocasali I've opened another PR #10793. Please review. Thanks!
