### ISSUE TITLE
more pagination in research notes 

### ISSUE THREAD

**Issue by max-keviv** [publiclab/plots2#10219]
when In research notes of few topics the last few pages in pagination don't contain the research notes

there may be extra pagination 

here you can see
https://publiclab.org/tag/climate-change?page=2
or
https://publiclab.org/tag/indoor-air-quality?page=3

https://user-images.githubusercontent.com/59287619/135364762-b6b9ecb5-0aaf-4b3f-9c5a-796d393c6e1e.mp4

**Comment by ebarry** [comment]
Confirming that I am also experiencing this pagination bug. Thanks for reporting @max-keviv !

**Comment by jywarren** [comment]
Hi all, the issue is here: we're paginating before we filter out questions:

https://github.com/publiclab/plots2/blob/883e081e0bbbd7cd25332798a4b27404f67f1035/app/controllers/tag_controller.rb#L132-L143

@max-keviv, would you like to try to fix this bug? It might be as simple as moving the pagination lines down below, but there could also be unexpected complications. Happy to help in either case!

**Comment by max-keviv** [comment]
@jywarren thank you, 
yes I would like to fix this bug 
so if I am right then, we need to move the line 132-133 after 143
please correct me if I'm missing something

**Comment by KarishmaVanwari** [comment]
Can I take up this issue? @jywarren

**Comment by TildaDares** [comment]
Hi @max-keviv, you can go ahead and move those lines. You can also check for unexpected complications as @jywarren said.

**Comment by jywarren** [comment]
Yes @max-keviv thank you - hopefully we just pass all tests no problem. But if a test fails, let's try to see why!

@KarishmaVanwari i think we have one open here if you'd like to leave a comment claiming it: https://github.com/publiclab/plots2/issues/10368 

Thank you everyone!

**Comment by tichnas** [comment]
Hi @TildaDares @jywarren

Is this issue still open? If yes, I'd love to work on it :)

Thanks

**Comment by jywarren** [comment]
Hi @tichnas i believe @max-keviv is working on it in https://github.com/publiclab/plots2/pull/10569 now. If you'd like another issue to work on, have you completed one at https://code.publiclab.org yet? Thank you!
