### ISSUE TITLE
Change link in community-toolbox/index.html

### ISSUE THREAD

**Issue by chicken-biryani** [publiclab/plots2#10229]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

*Change the line number 218 over [here.](https://github.com/publiclab/community-toolbox/blob/main/index.html)*

```diff 
-  218   <p>Once you've completed a <b><span  id="issue-label-for-newcomer">first-timers-only</span></b> issue, there are <a  id="help-wanted-issues" href="https://github.com/publiclab/plots2/labels/help-wanted">plenty of other challenges</a> we'd love to have your help on.</p>

+ 218 <p>Once you've completed a <b><span  id="issue-label-for-newcomer">first-timers-only</span></b> issue, there are <a  id="help-wanted-issues" href="https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22">plenty of other challenges</a> we'd love to have your help on.</p>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by Tarcisio-Menezes** [comment]
This is my first contribution, thanks for opportunity! I think I can solve this!

**Comment by AshishisLiquid** [comment]
Can i contribute in this issue. I am first timer in open source.

**Comment by chicken-biryani** [comment]
Hia, @Tarcisio-Menezes!
Definitely go ahead.
Happy contributing! 🎉

**Comment by chicken-biryani** [comment]
Hey @AshishisLiquid ,
Hope you're doing well!

Claiming issues works on a first come first serve basis.

But you can always keep your eyes open for new issues or even create an issue of  your own. 😉

**Comment by AshishisLiquid** [comment]
@chicken-biryani If it does not resolved by @Tarcisio-Menezes can i contribute ?

**Comment by chicken-biryani** [comment]
@AshishisLiquid definitely!

**Comment by Evensusu** [comment]
Hi can I contribute?

**Comment by Tarcisio-Menezes** [comment]
Thanks for the welcome @chicken-biryani  !
I've already opened the PR regarding the link change, I hope everything went well!

https://github.com/publiclab/community-toolbox/pull/500

**Comment by chicken-biryani** [comment]
Hey, @Evensusu!
Hope you're doing well.

Claiming issues works on a first come first serve basis.

The person who comments first 'Hey can I work on this' (Or something like that) gets to work on the issue.

For example over here: @Tarcisio-Menezes was the first person to suggest that he'd like to work on it, so they get to work on the issue.

But, I am glad to see your enthusiasm, keep your eyes open, for new issues. 😉

**Comment by Sshashank5690** [comment]
hey Can I contribute in this?
This is my first time.

**Comment by Rishi22-Coding** [comment]
I just Updated https://github.com/publiclab/community-toolbox/pull/503#issue-748137096

**Comment by chicken-biryani** [comment]
Hia, @Sshashank5690!

Hope you're doing well.

Well, as stated above, claiming issues works on a first come first serve basis. So over here, someone has already worked on it.

But you can always keep your eyes open for new, upcoming issues.

**Comment by chicken-biryani** [comment]
Heyy @Rishi22-Coding!

Thank you for making the changes but:
- That PR won't be accepted as someone has claimed it and worked on it before you did.

Also,  try not to work on an issue that has not been assigned to you because:

- It may be possible that someone else has already claimed it the issue and is already working on it, so you working on it would be just a waste of your time and energy.

So to work on an issue always check:
1) Whether it has been claimed by someone else and assigned to them or not.
2) If you would like to work on it Comment "Hey could I work on this issue?"... Have a little patience and only when it has been assigned to you start working on it.

**Comment by Mayank-Creater** [comment]
This is my first time contribution to open source.

**Comment by evansusu** [comment]
hi can I work on this?

**Comment by TildaDares** [comment]
Thanks @chicken-biryani

**Comment by pulkit-30** [comment]
Hey @TildaDares,
Is anyone working on this issue?
If not, I would love to start my contribution to this organization with this issue. May you please assign me this issue.

**Comment by TildaDares** [comment]
Hi @pulkit-30, this issue has been resolved.
