### ISSUE TITLE
Inconsistency in availability of "delete" button visible to author of note

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#10255]
This bug is going to be hard to reproduce because I've just banned the author in order to meet their request of removing their content, hopefully temporarily.  

### Please describe the problem

> What happened just before the problem occurred? Or what problem could this idea solve?

This user: https://publiclab.org/notes/author/jrmc502 wishes to delete their notes. 

> What did you expect to see that you didn't?

Of their two notes, this note shows the "delete" button: https://publiclab.org/notes/jrmc502/10-07-2020/towards-ai-assisted-water-testing-instructions

This post does not show the delete button: https://publiclab.org/notes/jrmc502/10-07-2020/towards-ai-assisted-water-testing

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

liz

**Comment by bhamster07** [comment]
Following up on a conversation with @jywarren about this issue, sharing full page screenshots that seem related to this: inconsistencies in sidebar menu options when viewing research notes authored by other users, from a non-admin/non-mod account. These screenshots are two different research notes from one author.

<img width="1746" alt="Full screen 2 item menu" src="https://user-images.githubusercontent.com/68756159/136102128-1d8fe372-1cbe-4b73-b5a3-7550e944d3d8.png">
<img width="1752" alt="Full screen 3 item menu" src="https://user-images.githubusercontent.com/68756159/136102172-5b9df862-b8b0-41ba-81d2-7ad68ba2963b.png">

**Comment by anirudhprabhakaran3** [comment]
Is this happening for all authors? Or like some specific authors have some inconsistency?

**Comment by jywarren** [comment]
Hi @wajeehamushtaq I believe @Goodiec is working on this! @TildaDares that's an AMAZING catch there. I believe it's already fixed now in https://github.com/publiclab/plots2/pull/10311 and so this should resolve once it publishes to the live site. Maybe later today!

**Comment by bhamster07** [comment]
🔍 Super sleuthing @TildaDares and @Goodiec, thank you!!
