### ISSUE TITLE
Map page breaks with no @node.map.tms check

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1026]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

The map page at http://publiclab.org/map/northern-virginia-community-college-sterling-virginia/03-07-2014 shows an error, with a server log output of the following:

```ruby
Completed 500 Internal Server Error in 258ms

ActionView::Template::Error (undefined method `tms' for nil:NilClass):
2: <iframe style="width:100%;border:none;background:#ddd;margin-bottom:8px;" height="375" src="http://archive.publiclaboratory.org/leaflet/?tms=<%= @node.map.tms %>&lon=<%= @node.lon %>&lat=<%= @node.lat %>&zoom=<%= @node.map.min_zoom+1 %>"></iframe>
app/views/map/show.html.erb:2:in `_app_views_map_show_html_erb___64319787606996866_46932220'
```

It's supposed to show a map similar to this page: https://publiclab.org/map/barataria-site-abh1-barataria-bay-louisiana/07-25-2014

This issue reformats and replaces #131.

## Solution

The error is on line 2 of:

https://github.com/publiclab/plots2/tree/master/app/views/map/show.html.erb:L2

The error could be solved by adding a `if @node.map` conditional around the line that uses `@node.map.tms`:

```ruby
<% if @node.map %>
  <iframe style="width:100%;border:none;background:#ddd;margin-bottom:8px;" height="375" src="//archive.publiclab.org/leaflet/?tms=<%= @node.map.tms %>&lon=<%= @node.lon %>&lat=<%= @node.lat %>&zoom=<%= @node.map.min_zoom+1 %>"></iframe>
<% end %>
```

## Steps to Fix

- [x] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by wvward** [comment]
I'd like to contribute to this issue.  I've read through the README & requested an invite to C9.io.

**Comment by jywarren** [comment]
Oh that would be so super, thank you will! Don't hesitate to ask if you
need any help.

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by wvward** [comment]
Hi, Jeff-
I haven't been able to work on it as much this last week.  I have been
following the 15 minutes/week commitment too closely.  I'll check in soon &
update.

Thanks for checking on me,
Will

On Dec 7, 2016 3:08 PM, "Jeffrey Warren" <notifications@github.com> wrote:

Hi, just checking if you've gotten stuck on this at all, or if I could help
in any way? Thanks!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/1026#issuecomment-265573976>,
or mute the thread

**Comment by jywarren** [comment]
No problem at all -- and no need to increase time commitment -- just wanted
to check in! Thanks, Will

**Comment by Connerh92** [comment]
Hello, I noticed this was still open and it has been over a month since the last person had messaged, so I was wondering if I could have a go at this issue and fix it. Thanks!

**Comment by ananyo2012** [comment]
@Connerh92 Sure you can take this up

**Comment by jywarren** [comment]
Yes, and happy to help if you need any input! Thanks!

**Comment by VishalRocks** [comment]
Hi I saw this issue open, can I solve this?

**Comment by jywarren** [comment]
Perhaps @Connerh92 is still working on it? If not, you can find more problems to solve here:

https://github.com/publiclab/plots2/projects/2?fullscreen=true

thank you!!!

**Comment by jywarren** [comment]
@Connerh92, are you still working on this? If not, @VishalRocks,  you can probably give it a try!

**Comment by VishalRocks** [comment]
I have done it..but how to test it in local? I tried url localhost:3000/map/northern-virginia-community-college-sterling-virginia/03-07-2014

**Comment by wvward** [comment]
And glad others picked up where I left off (the beginning)! :)

**Comment by jywarren** [comment]
Hi all!

To test, start by opening a pull request and we can add a test then. Sound
good?

**Comment by VishalRocks** [comment]
Sure..this is the pull request https://github.com/publiclab/plots2/pull/1285

**Comment by jywarren** [comment]
Great, solved over there!
