### ISSUE TITLE
"make a lead page for this topic" button on tag pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1027]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

The new tag pages have a great "intro" section sourced from the first paragraph of the corresponding wiki page, as of #985: 

https://publiclab.org/tag/visual-pm

![screen shot 2016-11-28 at 3 12 27 pm](https://cloud.githubusercontent.com/assets/24359/20684262/2291cdfe-b57d-11e6-8a52-5a81e5b8410f.png)

But if no corresponding page exists, they do not.

## Solution

The code for the check is here: https://github.com/publiclab/plots2/blob/master/app/views/tag/show.html.erb#L4

we should add an `else` block which shows a message like: 

> This topic has no lead wiki page. `Add one now +`

which leads to `/wiki/<page-name>` -- that way people are prompted to make one.

**Comment by manish310794** [comment]
@jywarren I have made the required changes in my local. Can you help me with creating a pull request. I have created a new branch in my local for this issue. When I am trying to push that branch to your repository, it return 403 (Unauthorized) error.

**Comment by jywarren** [comment]
Hmm, can you tell me the exact steps you take? Do you have your own fork?

Perhaps you have to push to: `git push https://github.com/manish310794/plots2.git feature-branch-name`

If you can share your exact console steps I can help out, thanks!

**Comment by jywarren** [comment]
Great? Closed in https://github.com/publiclab/plots2/pull/1029
