### ISSUE TITLE
Add contributors count to tag pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1028]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

The new tag pages have a great "intro" section sourced from the first paragraph of the corresponding wiki page, as of #985: 

https://publiclab.org/tag/dustduino

But if no corresponding page exists, they do not.

You can see the contributor count for that topic here:

https://publiclab.org/contributors/dustduino

![screen shot 2016-11-28 at 3 19 43 pm](https://cloud.githubusercontent.com/assets/24359/20684623/c46c4e78-b57e-11e6-9f7c-a103c869bd3c.png)

We should show how many people contributed to that topic on the tag page itself, just below the title, in smaller grey text just below this line: https://github.com/publiclab/plots2/blob/master/app/views/tag/show.html.erb#L12

See how we calculate that in the `contributors` action in the tag_controller: https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L217

```ruby
    @users = @notes.collect(&:author).uniq
```

However, that `@notes` is *all* notes, not just those on this page (since /tag/dustuino is paginated). So see the tag_controller to see how that's calculated. We'll likely have to add that code as well to be able to display this on the main tag page under `def show` in the same controller.

**Update:** We may just want to display the number in the tab for Contributors, just before the word, like: `14 Contributors`. That would go on this line:

https://github.com/publiclab/plots2/blob/master/app/views/tag/show.html.erb#L61 And could look like this:

```ruby
     <li<% if @node_type == "contributors" %> class="active"<% end %>><a href="/contributors/<%= params[:id] %>"><i class="fa fa-user"></i> <%= @notes.collect(&:author).uniq.length %> <%= raw t('tag.show.contributors') %></a></li>
```

However, we still want to be sure we're counting **all** contributors, and not just the ones for content shown on this page. We may want to add a followup issue to convert this count to a generalized tag-based method for counting contributors. OK -- did that in #1419

**Comment by manish310794** [comment]
@jywarren I am interested to take this up.
I need some context here though.

- We need to show the contributors count for the tag or the wiki page?
- If there is no wiki page for that tag, where will the count be shown?
- Is contributor count dependent on the notes displayed? If so, then how?

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L217 shows all contributors for that tag, and we can use a phrase like:

> # people have contributed to this topic. 

For now, let's just keep this inside the wiki block, and only show it if there's a corresponding wiki page. 

Contributor count will probably need to be calculated separately from how `@notes` is already generated, since `@notes` will be paginated, so you'd only see results from currently shown notes.

You could do this, even though it's going to be a lot of processing:

```ruby
    all_notes = DrupalNode.where(:status => 1, :type => 'note')
                       .includes(:drupal_node_revision,:drupal_tag)
                       .where('term_data.name = ?', params[:id])
                       .order("node_revisions.timestamp DESC")
    @contributors = all_notes.collect(&:author).uniq
```

If we'd like to be more efficient, we could use `.select()` to narrow and not return any database columns we don't explicitly need: http://guides.rubyonrails.org/active_record_querying.html#selecting-specific-fields

But you have to be careful -- every single field you need to make the relationships is required... so it's a little delicate to do properly. 

Thanks!

**Comment by mridulnagpal** [comment]
@manish310794 If you are not working on it anymore, I would like to give it a try.

**Comment by jywarren** [comment]
Hi all -- @manish310794 or @mridulnagpal - are folks stuck on this one or want to give it another try? We're happy to help!

**Comment by ryzokuken** [comment]
@manish310794, @mridulnagpal Any of you guys working on this issue?

**Comment by jywarren** [comment]
@ryzokuken i think perhaps we should tidy this one up and clear the comments so it can be taken on by someone new, if we don't hear from them.

**Comment by mridulnagpal** [comment]
I am a liitle tied up right now. You can surely work on this

**Comment by arkokoley** [comment]
Is this issue still open? I'd like to help out.

**Comment by ryzokuken** [comment]
@arkokoley It is, I suppose. Feel free to come back here or on our Gitter should you need any help. Thanks.

**Comment by jywarren** [comment]
Hi, @arkokoley, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by ryzokuken** [comment]
Hey, @arkokoley! What's the status on this? If you require any assistance from our side, feel free to ask for help or hop on to one of the chatrooms.

**Comment by jywarren** [comment]
Just a note to folks - as we haven't heard back from people, this is up for grabs!

**Comment by austindenny** [comment]
@jywarren I can take a stab at this if still open

**Comment by jywarren** [comment]
Super, please do, esp. as I don't think there's been activity on it
recently. We're happy to help!

**Comment by kingofpirate** [comment]
@jywarren I like to contribute on this issue!! Can I?

**Comment by jywarren** [comment]
Yes please!

**Comment by kingofpirate** [comment]
I am using    
```
 notes = Node.where(status: 1, type: 'note')
                 .includes(:revision, :tag)
                 .where('term_data.name = ?', params[:id])
    users = notes.collect(&:author).uniq
    if !users.nil?
      @length=users.length
    end
```
to count users.
And Badge to show number contributor.If contributors are zero then show no badge

**Comment by jywarren** [comment]
Hmm, do you think you could open a pull request so we can look at your
changes in context? Thanks!

**Comment by kingofpirate** [comment]
My rake test queries are giving errors and I am not able to remove the errors.I have tried googling it and many more things but it still giving error..My output to `bundle exec rake test:all --trace` is : 
https://gist.github.com/kingofpirate/ad0585e5d8ea49d61533dc256c2f7be4

**Comment by devaman** [comment]
@jywarren I have submitted a pull request on this issue.Can you review it...

**Comment by jywarren** [comment]
Thanks to @devaman for this fix!!!
