### ISSUE TITLE
Add self-introduction prompts upon subscribing to googlegroups

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#103]
This is a mailing list issue. 

Upon subscription, set up the google group to send self-introduction prompts. We could ask about the interests that brought them here, what skills they have to offer, and their general location. If we decide that these prompts should include a geographic survey, we should think about if there's a way to connect what's sent to a googlegroup with someone's profile pages on the website. 
# 

Example format from a group that Shannon is on: 

Welcome to the xxx.

First thing's first -- introduce yourself! Share your bio with the group.

Why.
We want to know who you are, what you're into, and what job/panel/advice/expertise you can offer.

I hate my bio.
If you don't love it, note that you'd like suggestions for improvement. Everyone here has had to write one, knows how annoying it is, and knows theirs could be better. You're in a safe bio-improving space, my friend.
#

**Comment by steviepubliclab** [comment]
Think this is done right?

**Comment by ananyo2012** [comment]
Closing this one as this is not relevant here. Reopen if needed
