### ISSUE TITLE
‘Preview and Publish’ buttons misplaced at certain screen width - UI Bug (3/3) 

### ISSUE THREAD

**Issue by Jon-Jos** [publiclab/plots2#10308]
![buttons in footer](https://user-images.githubusercontent.com/71092045/136822610-3bee5ea3-cd05-46af-be58-12c7e77b41a2.png)
look here-> https://publiclab.org/post

Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by Raioite** [comment]
Working on this!

**Comment by Jon-Jos** [comment]
go ahead! 🚀 @harsh-the-innovator

**Comment by jywarren** [comment]
Hi @Jon-Jos thanks for helping to find this bug - and for documenting it! (sorry to repeat myself as I left a similar comment but just in case, continuing below)

I do want to note that our "first-timers-only" issues have a very specific format which include the specific changes to be made. So this is more like a "fto-candidate" -- which might be converted into a full "first-timers-only" once a solution is included, if it's simple enough and easy to confirm when completed! I'll adjust the labeling accordingly. Thanks a lot!!!

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by harsh-the-innovator** [comment]
Error is coming while installing ruby in ubuntu. I have followed instructions given on repo.

harsh@harsh-ubuntu:~$ curl -L https://get.rvm.io | bash -s stable
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   194  100   194    0     0    105      0  0:00:01  0:00:01 --:--:--   105
100 24535  100 24535    0     0  10287      0  0:00:02  0:00:02 --:--:-- 10287
Downloading https://github.com/rvm/rvm/archive/1.29.12.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.12/1.29.12.tar.gz.asc
gpg: Signature made Saturday 16 January 2021 12:16:22 AM IST
gpg:                using RSA key some_rsa_key
gpg: Can't check signature: No public key
GPG signature verification failed for '/home/harsh/.rvm/archives/rvm-1.29.12.tgz' - 'https://github.com/rvm/rvm/releases/download/1.29.12/1.29.12.tar.gz.asc'! Try to install GPG v2 and then fetch the public key:

    gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys some_key

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
    command curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -

In case of further problems with validation please refer to https://rvm.io/rvm/security

**Comment by harsh-the-innovator** [comment]
Footer is not showing in development mode.
This below line is coming.Then how can i show it because i have to make the button show.
_The footer is empty during local development_

**Comment by harsh-the-innovator** [comment]
Please someone help!

**Comment by harsh-the-innovator** [comment]
Please anyone reply atleast.

**Comment by KarishmaVanwari** [comment]
Can I take up this issue, if it's still open? @TildaDares @Jon-Jos

**Comment by mittal-parth** [comment]
Can I work on this? @TildaDares @Jon-Jos

**Comment by Tahree22** [comment]
Hello, can I work on this issue?

**Comment by TildaDares** [comment]
Hi @mittal-parth, you can work on this. But, before you open a PR, can you add a screenshot of the UI changes you made after correcting the problem in this issue? Thanks!

**Comment by mittal-parth** [comment]
Sure @TildaDares!
How does this look?

https://user-images.githubusercontent.com/76661350/148769265-e637d03e-4c3e-45b2-85c5-758dc1714d59.mp4

**Comment by TildaDares** [comment]
Looks good @mittal-parth. You can open a PR.
