### ISSUE TITLE
Weekly Community Check-In #119 - Learning to take breaks 🧘

### ISSUE THREAD

**Issue by Goodiec** [publiclab/plots2#10305]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Learning to take breaks
Sometimes activities around us overwhelm us and we feel like we don't have enough time in a day but it is always advisable to press pause for a while, take an effective break (call someone, do a quick workout, take a walk, read a book, take a nap, etc) and see what impact it has on your productivity. Taking breaks helps to improve focus and concentration, getting you back to work with more energy and motivation 💪.
This week let's share how we take breaks and they help us.

## Welcome Outreachy Winter Applicants! ❤️
This week, we welcome Outreachy Internship Winter 2021 cycle applicants. Feel free to introduce yourself in the comments as well, ask for help, or ask questions about our community!

The contribution period for the Outreachy Internship application started on October 8th. To get familiar with the codebase and make contributions, these are some ideas to get you on board:

Introduce yourself in the comments below
Introduce yourself on our Gitter chatroom
Complete a first-timer-only (FTO) issue, if you haven't done one yet
If you already completed an FTO, you can create your own FTO issue to help introduce more first-timers to our community. You can follow this guide on how to do so: [Adding new strings for Translation #9945](https://github.com/publiclab/plots2/issues/9945)
Help someone make a pull request for the first time, or get their local environment set up.
Open a weekly check-in like this one!

## Key Issues
The following issues are great candidates for Outreachy applicants who are looking for an issue to work on after completing a first-timer-only.
- [Inconsistency in availability of "delete" button visible to author of note #10255](https://github.com/publiclab/plots2/issues/10255)
- [Advanced tagging menu not working #10118](https://github.com/publiclab/plots2/issues/10118)

We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note to focus issues contributors
Many thanks to everyone who contributed in one way or another either by committing to the codebase, opening an issue, or reviewing a PR: 
🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇
@Jon-Jos @jywarren @TildaDares @AnirbanBall @Manasa2850 @ShivamJhaa @rigved-telang @fuadnafiz98 @Axuby
🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇

## Next Check-in
If you would like to open the next check-in...Leave a comment below. We are happy to help if it's your first time

**Thanks to everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by ebarry** [comment]
I like to choose a workout from the Nike Training Center app for a break :)

**Comment by Georjane** [comment]
Hi everyone, I'm Jane. It's nice to be working with such a warm and welcoming community. I have just been a little overwhelmed with all the materials to read to get started and familiarise myself with open source contributions. So I didn't do much this week. But my goal is to complete an FTO issue this weekend so I can start contributing to the issues next week.

Nice to meet you all again 😃 
[Jane](https://witahgeorjane.tech/) 👧🏽

**Comment by TildaDares** [comment]
Thanks, everyone. Closing this and moving the next check-in to #10356
