### ISSUE TITLE
Move question card template back to questions/_questions.html.erb

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#10325]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/notes/_card.html.erb](https://github.com/publiclab/plots2/blob/main/app/views/notes/_card.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -45,16 +45,6 @@
             </span>
           <% elsif node.type == 'page' %>
             Wiki page by <%= node.revisions.collect(&:uid).uniq.length %> people
-          <% elsif node.type == 'question' %>
-            <div class="card bg-white rounded<% if node.status == 4 %> moderated<% end %>">
-              <div class="card-header">
-                <%= render partial: 'dashboard/node_moderate', locals: { node: node } %>
-                <h4><a <% if @widget %>target="_blank"<% end %> href="<%= node.path(:question) %>"><%= node.title %></a></h4>
-              </div>
-              <div class="card-footer">
-                <p class="meta"><%= render partial: "dashboard/node_meta", locals: { node: node } %></p>
-              </div>
-            </div>
           <% end %>
         </p>
       </div>
```

- [ ] 📝 **Update** the file [app/views/questions/_questions.html.erb](https://github.com/publiclab/plots2/blob/main/app/views/questions/_questions.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -2,7 +2,15 @@
 <div class="card-view questions-page row">
   <% questions.each_with_index do |node,i| %>
     <div class="<% if @widget %>col-xs-4 col-sm-4 col-md-4 <% end %>col-lg-4" style="margin-top:20px;">
-      <%= render partial: 'notes/card', locals: { node: node, i: i, tagname: @tagname } %>
+      <div class="card bg-white rounded<% if node.status == 4 %> moderated<% end %>">
+        <div class="card-header">
+          <%= render partial: 'dashboard/node_moderate', locals: { node: node } %>
+          <h4><a <% if @widget %>target="_blank"<% end %> href="<%= node.path(:question) %>"><%= node.title %></a></h4>
+        </div>
+        <div class="card-footer">
+          <p class="meta"><%= render partial: "dashboard/node_meta", locals: { node: node } %></p>
+        </div>
+      </div>
     </div>
 
     <% unless @widget %><hr class="d-lg-none" /><% end %>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by wajeehamushtaq** [comment]
Thanks, @TildaDares !!

**Comment by TildaDares** [comment]
@wajeehamushtaq Yes you can make another PR to fix this issue.

**Comment by sr-utkarsh** [comment]
I am new to open source contribution. Is this issue open?

**Comment by IshaNadkar** [comment]
I am new to open source contribution. Is this issue open?

**Comment by anayo-hub** [comment]
please i would like to make a contribution
