### ISSUE TITLE
Hide comment toolbar when viewing comment preview

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#10330]
Since a normal comment doesn't have a toolbar, it's best to hide it when previewing a comment.

<img width="711" alt="Screenshot 2021-10-14 at 22 13 50" src="https://user-images.githubusercontent.com/63427719/137396415-23d4c012-c231-4e02-aead-4afc11531de5.png">

The relevant code needed for this is in https://github.com/publiclab/plots2/blob/main/app/views/comments/_form.html.erb and
https://github.com/publiclab/plots2/blob/7836a0fecd1e68a433fb1415acc8f5e14c37f686/app/assets/javascripts/editor.js#L171-L183

****

This has been marked as a good candidate for becoming a [first-timers-only issue](https://code.publiclab.org/#r=all) like these, meaning that it's **simple, self-contained**, and with some extra formatting✍️, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider **reformatting it as a first-timers-only issue**, and then ping @publiclab/reviewers to get it labelled🏷. Or, if this is not your first time, **try to solve it yourself**🧑‍💻!

**Comment by leau-void** [comment]
Hi, I would like to be assigned this issue.
Thank you.

**Comment by KarishmaVanwari** [comment]
Is the issue open? I am willing to work on this. @TildaDares

**Comment by TildaDares** [comment]
Hi @cillacode, just checking in to know if you’re still interested in working on this? 

Hi @KarishmaVanwari, let’s give @cillacode some time to reply. In the meantime, you can request to be assigned to a `first-timers-issue` by leaving a comment here #10153. You can also work on other issues labeled `bug`, `first-timers-issue` or the general `help wanted `label. Thank you!

**Comment by KarishmaVanwari** [comment]
> Hi @cillacode, just checking in to know if you’re still interested in working on this?
> 
> Hi @KarishmaVanwari, let’s give @cillacode some time to reply. In the meantime, you can request to be assigned to a `first-timers-issue` by leaving a comment here #10153. You can also work on other issues labeled `bug`, `first-timers-issue` or the general `help wanted `label. Thank you!

Sure, I'll leave at comment over there 
Also, do let me know if this issue is open.
Thanks @TildaDares

**Comment by TildaDares** [comment]
Reassigning this since @cillacode has been inactive.

@KarishmaVanwari if you're still interested in working on this I can assign it to you.

**Comment by KarishmaVanwari** [comment]
> Reassigning this since @cillacode has been inactive.
> 
> @KarishmaVanwari if you're still interested in working on this I can assign it to you.

Yes, I'll work on this. Thanks @TildaDares

**Comment by KarishmaVanwari** [comment]
Hey @TildaDares can you please tell me where can I find the concerned ui as in on which route? Since I am unable to see comment option or topics on the localhost (as it is visible on the publiclab website).

**Comment by TildaDares** [comment]
Hi @KarishmaVanwari, you can visit any note in your local environment, scroll to the bottom of the page and you should see a comment box.

**Comment by KarishmaVanwari** [comment]
I've created the pull request, please have a look @TildaDares

**Comment by KarishmaVanwari** [comment]
@TildaDares I have opened another pull request, please have a look
