### ISSUE TITLE
Show notification message when bell icon is clicked

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#10331]
When the bell icon is clicked, a message like the one below is supposed to display but it doesn't.

<img width="711" alt="Screenshot 2021-10-14 at 22 26 18" src="https://user-images.githubusercontent.com/63427719/137397919-016f2f6f-2be0-4072-b12c-383d991a69f5.png">

The relevant code needed for this change is in 
https://github.com/publiclab/plots2/blob/7836a0fecd1e68a433fb1415acc8f5e14c37f686/app/views/comments/_form.html.erb#L212-L217

https://github.com/publiclab/plots2/blob/7836a0fecd1e68a433fb1415acc8f5e14c37f686/app/assets/javascripts/comment.js#L73-L76

****

This has been marked as a good candidate for becoming a [first-timers-only issue](https://code.publiclab.org/#r=all) like these, meaning that it's **simple, self-contained**, and with some extra formatting✍️, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider **reformatting it as a first-timers-only issue**, and then ping @publiclab/reviewers to get it labelled🏷. Or, if this is not your first time, **try to solve it yourself**🧑‍💻!

**Comment by leau-void** [comment]
I would like to take on this issue if possible.
Thanks :)
