### ISSUE TITLE
Intermittent test failures due to new timeframe code

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#10341]
#10318 caused some intermittent test issues -- for example:

```
Progress: |======================= FAIL TagTest#test_contributors_with_timeframe (3.13s)
        Expected: [1, 2, 5, 6]
          Actual: [1, 2]
        test/unit/tag_test.rb:193:in `block in <class:TagTest>'
```

https://github.com/publiclab/plots2/blob/9682cb895fae5fe2e2251eb6b87c2a01d74084f2/test/unit/tag_test.rb#L189-L200

**Comment by subhangi2731** [comment]
@jywarren I  want to work on the issue can u please assign me this

**Comment by jywarren** [comment]
OK! Tried freezing time in #10365, let's monitor the situation!

**Comment by jywarren** [comment]
Hmm, looks like it failed again in:

https://github.com/publiclab/plots2/pull/10366

```
Progress: |==================================================== FAIL TagTest#test_contributors_with_timeframe (17.99s)
        Expected: [1, 2]
          Actual: [1, 2, 5, 6, 12]
        test/unit/tag_test.rb:195:in `block in <class:TagTest>'
```

**Comment by jywarren** [comment]
```
Progress: |==================================================== FAIL TagTest#test_contributors_with_timeframe (17.99s)
        Expected: [1, 2]
          Actual: [1, 2, 5, 6, 12]
        test/unit/tag_test.rb:195:in `block in <class:TagTest>'
```

**Comment by jywarren** [comment]
Looking more closely at the tag.rb section now:

https://github.com/publiclab/plots2/blob/cd11fdca637b5a4dad21968bf448adb7102c3e8c/app/models/tag.rb#L64-L77

**Comment by jywarren** [comment]
OK, hoping this is a fix! I focused on the line:

```
   contributors = Tag.contributors(tag.name, start: Time.now-1.month, finish: Time.now) 
```

And I changed `Time.now` to `Time.now+1.day` so it doesn't sometimes fall before the timestamp of fixture data which can be created all at once.
