### ISSUE TITLE
Add "This is part of a series about X" message to notes, via tagging

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1036]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

Increasingly on our site, notes are becoming parts of sequences or collections -- for example:

https://publiclab.org/tag/research-culture

![screen shot 2016-11-30 at 1 56 17 pm](https://cloud.githubusercontent.com/assets/24359/20766783/c557fac0-b705-11e6-83f7-ca08ab9daea4.png)

## Solution

It'd be helpful if people could more easily find their way back to that whole collection while reading an individual note!

We should display a message at the top of the note body that says:

> This is part of a series on [formaldehyde](/tag/formaldehyde).

This message would be triggered by using the [power tag](https://publiclab.org/wiki/power-tags) `series:tagname` and would link to (in this example):

https://publiclab.org/tag/formaldehyde

The message would use this markup, fetching the `value` of the power tag with `@node.power_tag('series')`:

```ruby
  <% if @node.has_power_tag('series') %><div class="alert alert-info"><%= raw t('notes.show.series') %> <a href="/tag/<%= @node.power_tag('series') %>"><%= @node.power_tag('series') %></a>.</div><% end %>
```

And we'd want to put that code just after this line: https://github.com/publiclab/plots2/blob/master/app/views/notes/show.html.erb#L6

It'd also need a translation entry here: https://github.com/publiclab/plots2/blob/master/config/locales/views/notes/show/en.yml#L7 which would be inserted where it says `<%= raw t('notes.show.series') %>`

That would contain the text of the message up until the link begins.

## Steps to Fix

- [x] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by shaduk** [comment]
Hi. I would like to work on this one. This would be my first PR. Thanks for making it easy for first timers. I will setup the codebase on my laptop and let you know for any issues. Thanks again.

**Comment by jywarren** [comment]
We'd love your help on this and are happy to offer any assistance you might need. Thanks a lot!

Just curious -- we're trying to improve our outreach to new contributors -- how did you happen to hear about us?

**Comment by shaduk** [comment]
I received the link via @YourFirstPR on Twitter (https://twitter.com/yourfirstpr). I appreciate your help. Thank you.

**Comment by shaduk** [comment]
Hello jywarren. I am sorry, I have been busy with End Semester exams and Presentations. I can assure you that I will start working on it asap when I am done with everything next week. In the meantime if anyone wants to work on this issue please go ahead. 
Thanks
Shad

**Comment by jywarren** [comment]
Oh, no worries, and thank you for checking in!

**Comment by ebarry** [comment]
Hi @shaduk , hope your semester has wrapped up in good order! Winter holidays are starting, so please pardon any delays from our end if you re-start work on this.

**Comment by Pk13055** [comment]
@shaduk Are you still working on this? Do you need help?

**Comment by tgisg** [comment]
Hello, my friend @calaway and I are interested in working on this issue. We would like to claim it and we can start working on it now. We're students at Turing School of Software and Design and this is our first open source contribution.

**Comment by jywarren** [comment]
Please, we'd love your contribution -- and do ask if you need any help or pointers!

**Comment by tgisg** [comment]
Please review the contribution made by @calaway and myself. Thanks! https://github.com/publiclab/plots2/pull/1179
