### ISSUE TITLE
Need to edit the Getting Started page

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1037]
### What happened just before the problem occurred

I tried to edit The Getting Started page that is linked to from our dropdown menu but couldn't find the edit button. I am trying to remove mention of "chapters"

### Relevant URLs

https://publiclab.org/getting-started

### PublicLab.org username

liz

**Comment by jywarren** [comment]
Hi, Liz - that page has the `style:fancy` [power tag](https://publiclab.org/wiki/power-tags) which hides the edit button under the `v` chevron toggle. Thanks!

![image](https://cloud.githubusercontent.com/assets/24359/20769697/ff9abc94-b710-11e6-89dd-19c376fe9829.png)
