### ISSUE TITLE
URL for in text headers drops too low

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#1038]
### What happened just before the problem occurred
When I use a URL to tag a place within a page for example, https://publiclab.org/wiki/frac-sand#Outline+of+Wiki+Documents  where the # brings me to a spot on the page I wanted to call out, the link brings my page to a place below the header, so you can't see the title. Is there anyway to make it scroll to the top of the header? 

### Relevant URLs

https://

### PublicLab.org username stevie

(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
I believe we've seen this before and it may be screen size and/or browser dependent. Can you upload full-window screenshots to show what you're seeing? I see:

![screen shot 2016-11-30 at 3 24 55 pm](https://cloud.githubusercontent.com/assets/24359/20769773/451a57b6-b711-11e6-88b4-172df924ad39.png)
![screen shot 2016-11-30 at 3 25 00 pm](https://cloud.githubusercontent.com/assets/24359/20769774/451b0080-b711-11e6-8b72-7218a1f8dfa0.png)

**Comment by steviepubliclab** [comment]
Sure, I'm using google chrome and I see this: 
![screen shot 2016-11-30 at 2 26 29 pm](https://cloud.githubusercontent.com/assets/7490478/20769832/1ef781ce-b709-11e6-9e5c-ccc3d12ddb40.png)

**Comment by jywarren** [comment]
did you enter the URL with the deep link initially, or did you press a link
higher on the same page?

**Comment by steviepubliclab** [comment]
I grabbed the URL from the link button on the header and used it to reference a place. This time it was for an email. 
-Stevie

**Comment by jywarren** [comment]
Yes, but was your screenshot from after using a link within the same page, or freshly pasting https://publiclab.org/wiki/frac-sand#Outline+of+Wiki+Documents into a new tab? Thank you!

**Comment by jywarren** [comment]
(I believe this is related to #156, which we believed was fixed in #367)

**Comment by steviepubliclab** [comment]
Oh I see what you're saying. Yep, looks like it works. Thanks!
Closing now
