### ISSUE TITLE
incorrectly redirected to successful posting in new rich editor

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1040]
### What happened just before the problem occurred

I posted a new note at

https://publiclab.org/editor

It published fine: https://publiclab.org/notes/warren/11-30-2016/how-many-people-to-do-an-activity

However, I saw this:

![screenshot 2016-11-30 at 4 56 16 pm](https://cloud.githubusercontent.com/assets/24359/20773080/24b60184-b71e-11e6-9532-bb100441758f.png)

I believe this is because it didn't recognize a successful response from this line: 

https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb#L181

On this line, we should better recognize a response with zero errors, and go to the post:

https://github.com/publiclab/plots2/blob/master/app/views/editor/rich.html.erb#L213

Next step: go through this in development mode and find what a successful response looks like, and then test that the JavaScript code on line 213 above correctly identifies it as successful.

**Comment by jywarren** [comment]
@ashleypt - curious if you're interested in this one -- it's at the intersection of the JavaScript editor library and the main Rails application, and shows some of the challenges of interfacing complex projects. Give a shout if you want to take a crack at it!

**Comment by ashleypt** [comment]
@jywarren @ashleypt sure, I can take a look at it :)

**Comment by ashleypt** [comment]
oops I accidentally hit close and comment D:

**Comment by ashleypt** [comment]
I'll start off by console.logging the response object and the results of the condition in the erb. then I'll try passing in different json objects to see if I can replicate those errors

**Comment by jywarren** [comment]
great!

**Comment by jywarren** [comment]
Hi, @ashleypt - just checking if you've gotten stuck on this or needed any help. #1091 will make the new editor default, so I want to be sure we resolve this too before publishing that one. Thanks!

**Comment by jywarren** [comment]
And if you don't think you'll be able to work on it soon, I'm happy to take this one and help you find another that'll be interesting. Thanks!

**Comment by jywarren** [comment]
I went ahead and resolved this last night since we had a switchover to the rich editor in #1091 -- but I'm happy to help you find another issue, and there are a few in https://github.com/publiclab/PublicLab.Editor/ as well. Thanks!
