### ISSUE TITLE
Hide sidebar on small screens when button is clicked

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#10409]
When the `chevron-down` icon is clicked, the `#sidebar` section is supposed to be hidden but currently it doesn't work. This only applies to `sm` and `md` screens.

<img width="535" alt="Screenshot 2021-10-23 at 09 02 17" src="https://user-images.githubusercontent.com/63427719/138548196-c853c8d3-117d-48bf-ae23-6d367b894bf4.png">

You can see a demonstration of this in https://publiclab.org/questions/warren/01-04-2018/how-good-is-the-purpleair-sensor-and-what-does-it-detect

The relevant code needed for this change can be found in
https://github.com/publiclab/plots2/blob/99f3520499a96fa7b93ecc099cdde6bbd6fb67eb/app/assets/javascripts/sidebar.js#L1-L9
 
https://github.com/publiclab/plots2/blob/99f3520499a96fa7b93ecc099cdde6bbd6fb67eb/app/views/sidebar/_question.html.erb#L5-L7

**Comment by ShivamJhaa** [comment]
Hello @TildaDares , I have a small doubt
" #sidebar .hidden-sm,
#sidebar .hidden-md {
  display: block !important;
} "
I only need to add this in style.css, or something else?

**Comment by TildaDares** [comment]
Hi @ShivamJhaa, have you tried using that style and it worked?

**Comment by TildaDares** [comment]
@ShivamJhaa I think the reason why the `.hidden-sm, .hidden-md` classes don't work is because bootstrap removed them https://getbootstrap.com/docs/4.1/migration/#responsive-utilities

**Comment by ShivamJhaa** [comment]
> Hi @ShivamJhaa, have you tried using that style and it worked?

I am using gitpod so I am not able to test this.

**Comment by ShivamJhaa** [comment]
> @ShivamJhaa I think the reason why the `.hidden-sm, .hidden-md` classes don't work is because bootstrap removed them https://getbootstrap.com/docs/4.1/migration/#responsive-utilities

So do I have to replace them with "d-sm-block, d-md-block"?

**Comment by TildaDares** [comment]
@ShivamJhaa I'm not familiar with gitpod but there should be a way to view your changes on the browser or you can just tweak the CSS with Chrome dev tools.

**Comment by ShivamJhaa** [comment]
@TildaDares  PTAL

**Comment by TildaDares** [comment]
Thank you for teaching me something new @ShivamJhaa. I didn't know that PTAL means Please Take Another Look 😅

**Comment by ShivamJhaa** [comment]
> Thank you for teaching me something new @ShivamJhaa. I didn't know PTAL means Please Take Another Look sweat_smile

Your welcome.

**Comment by KarishmaVanwari** [comment]
Can I take up this issue, if it is still open? @TildaDares

**Comment by TildaDares** [comment]
Hi @KarishmaVanwari, there’s a PR open for this already. Thanks!

**Comment by KarishmaVanwari** [comment]
> Hi @KarishmaVanwari, there’s a PR open for this already. Thanks!

Okay
