### ISSUE TITLE
Weekly Community Check-In #121 - Gaming 👾 

### ISSUE THREAD

**Issue by DalilaBA** [publiclab/plots2#10436]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Video games 
Many theories and research have been made about the effect of video games in the brain, some says that it increase productivity and reflection, and other says that it make the person more agile and speed up his reflexes... but I like to think that it is the best way to destress, and spend a good time with friends and make a lot of new ones.
So what is your favorite video game, that you can spend hours on it ? or what is the actual one that you just discovered and that you like so much ?
Old and new ones are welcome, cause every game has his story, and every memory count 😄 

For me is **League of Legends** wild rift, the mobile version of League of Legends, I like playing with friends and it is fun 🎊 

## This week's focus Issues

These are issues that are of high priority and requests from our
large community that use the software. 

https://github.com/publiclab/plots2/labels/bug

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note to focus issues contributors

Big thank you for all the contributors, the Outrachy and the reviewrs 🥇  and good luck for the proposals, remember that  most importantly is to participate and try, and it is okey to fail, just keep tryin  😃 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by TildaDares** [comment]
Moved to #10475. Thanks everyone!
