### ISSUE TITLE
"sort by topic" for https://publiclab.org/tools

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1047]
This is a design issue -- we need some interface design thinking -- using the UI components available in https://getbootstrap.com/ (which we use) for sorting the methods/tools we show at 

https://publiclab.org/tools

As more tools are added, we'll need to be able to sort them by, for example:

* water
* air
* soil
* ...

what other categories, and how might this page organization work while still preserving the "most recently updated at top" convention?

**Comment by ebarry** [comment]
thinking about how this categorization can converge with what environmental issues people are asking about in Q&A...

**Comment by jywarren** [comment]
Thanks -- I can see two ways:

1. compiling a list of topics (tagnames) that collect those kinds of issues, and/or a metric (e.g. # of questions) for collecting and displaying such a list
2. displaying question count alongside upgrade and activity count on a per-method basis, as shown in this screenshot:

![screen shot 2016-12-02 at 1 51 39 pm](https://cloud.githubusercontent.com/assets/24359/20846193/826eefa6-b896-11e6-8279-2680b990068c.png)

**Comment by jywarren** [comment]
Hi, @steviepubliclab -- is compiling a list of topics or categories which we could use to sort this page something you could help with, perhaps in conjunction with your interviewing offline folks? Or that you already have some data for? I think we could do between 3-8 categories.

**Comment by steviepubliclab** [comment]
Hi, 
Sure, love to help think through this. Not sure it's something we can ask in the interviewing process that's going on, that one is pretty specific and is already getting long, but input from others would be really helpful! Maybe we could come up with a few options, post it and ask for input from others?

**Comment by jywarren** [comment]
That'd be great, thank you!

**Comment by jywarren** [comment]
Hope it's all right - i assigned this one to you but can collab of course.

**Comment by steviepubliclab** [comment]
I was just wondering if we could we sort these by environmental tags that someone would pick when they came to the page. a number of these methods could fall under different categories (land, air, water etc.)

**Comment by jywarren** [comment]
That's just what I was thinking, yeah! So I suggested:

* water
* air
* soil

Do you prefer "land", or have other suggestions to add, or are these three sufficient to start with?

**Comment by steviepubliclab** [comment]
sorry, I don't think I was clear enough. I meant more specific tags, as in people would pick their own tag of interest and methods with those tags would show up on the page. For example they could choose:
- a pollutant  ("pesticides," "H2S," "lead") or 
- environmental issue ("fracking," "mining," "landfill") or 
- a larger category ("water" or "air")

I just feel like this is actually really complicated and if we categorize these into just the big groups we'll be missing a good bit of crossover and detail. But perhaps this is all covered under the new search? I'm probably just thinking of a methods specific search feature.

**Comment by jywarren** [comment]
Great, the specifics are very helpful, thank you. I'd hoped for more specific categories, so I'm glad you're thinking along similar lines.

How might people pick a tag, though, specifically? Would they type it in themselves, or select tags from a list of content that already exists and is tagged, or would we offer a set of tag names we imagine might be comprehensive enough but not overwhelming?

I do think search is a separate discussion, but we might face a similar issue there with "suggested search terms" and need a similar list of options. Can you propose a # of tag names you imagine would be the right #, and take a stab at what they would actually be? That's what we need to move forward here. 

Thanks!

**Comment by steviepubliclab** [comment]
Hi
Ok just did some brainstorming with @gretchengehrke. We thought it would be neat if people could pick environmental issues or/(and?) finding monitoring methods for specific things. See list:: 

**Environmental Issue:** 
- Agriculture, 
- Drinking Water,
- Fracking, 
- Indoor Air, 
- Industry (chemical processing),
- Land Use / Change, 
- Mining, 
- Oil / Gas, 
- Transportation, 
- Urban Planning, 

**Find Monitoring Methods for ____**
- Conductivity / Salinity
- Depth
- Formaldehyde 
- Heavy Metals
- Hydrogen Sulfide
- Land change
- Petroleum Products
- pH
- Photosynthesis 
- PM 
- Temperature
- Turbidity / Suspended Solids

This second list would be things we could add to as new tools come on PL. It might be nice if the methods template allowed people to choose the Environmental Issue tag(s) and also tags for the second category @ebarry what do you think?

**Comment by jywarren** [comment]
Great -- the first list is already a good number of them -- would we show them all? And in what kind of display -- something like this:

![screen shot 2016-12-15 at 5 18 26 pm](https://cloud.githubusercontent.com/assets/24359/21244212/8c9110aa-c2ea-11e6-95c4-75e31fb00cc9.png)

I think it could be important to show methods that are associated with a few of the "key" ones as examples, so the page isn't empty until you begin choosing, you know? What do you think about that?

**Comment by steviepubliclab** [comment]
Hi!
Can we do these as a dropdown for people to choose from? +1 to having key
methods on the page when it's first loaded. Not sure how to pick these,
maybe the most recently updated works for this as well?

**Comment by gretchengehrke** [comment]
I agree w/ having a dropdown menu would be more visually appealing (and perhaps easier to discern that you are supposed to select one). For the key methods, perhaps we could go by the methods that have the most views? Or, if they are activities, the most replications?

**Comment by jywarren** [comment]
I think the question of what the best interface design for the display is a separate question, and one we can revisit and also test out. But thank you -- this is the key info we need to go forward:

> the methods that have the most views
> the most recently updated

So, we actually already sort methods by `most-recently-updated`, which we chose as better to the previous `most-viewed` -- the question is how to select the **topics/tagnames** we should display by default, and how many. 

I think 3-4 distinct listings, or 6 at maximum, on the page, is probably the most we can reasonably fit. So, would you want to show:

1. the 3-6 topics/tags in which contain the most recently updated content
2. the most commonly-used 3-6 topics/tags (with the most recently updated methods for each)

(Also, I'd guess that those we choose to show by default wouldn't be from just any tag on the site, but from this curated list Stevie's started on.)

**Comment by jywarren** [comment]
And sorry, i know I asked for input on type of display, but unfortunately dropdowns present some pretty serious [known UI problems](https://www.nngroup.com/articles/drop-down-menus-use-sparingly/) -- I figure once we can identify our topics and how many we want to show, and in what order, we can circle back to the interface design questions.

**Comment by steviepubliclab** [comment]
Ok I hear you on the UI problems of dropdown menus, but as a theme, I have
concerns about too much text /too many options on the page when someone
doesn't ask for it (ie click on it). I'm also unclear if you're asking me
any further questions from your previous post. Can you clarify?

**Comment by jywarren** [comment]
Yes, I'm also concerned about that -- my question is to try to prioritize what we do show, specifically so there's not too much: 

> So, would you want to show:
> * the 3-6 topics/tags in which contain the most recently updated content
> * the most commonly-used 3-6 topics/tags (with the most recently updated methods for each)

And I'll add one other option: a fixed list of 3-6 tags. This could be similar to the original suggestion. 

Thanks!

**Comment by jywarren** [comment]
OK - I caught up with Stevie on this and proposed some rough mockups of different possibilities as a next step. Thank you for pointing out that one option is to not show any methods on initial page load, that hadn't occurred to me. Here are two scenarios to explore and discuss. Love to hear your thoughts, @gretchengehrke, @steviepubliclab, @ebarry !

Note that these are intended to be rough; not final decisions on things like how to list out suggested topics, how to group or order listed methods, etc. -- just to give a general impression of how someone would initially see and interact with this page:

### Direction 1: show just a prompt until topic is input

![public lab tool 2ftechnique page rev](https://cloud.githubusercontent.com/assets/24359/21279325/aa7710c4-c3ad-11e6-98df-5a9614d38606.jpg)

After inputting a term, matching methods would appear:

![public lab tool 2ftechnique page rev 1](https://cloud.githubusercontent.com/assets/24359/21279338/ba2f25d8-c3ad-11e6-82e5-e8bfa7ba7d5d.jpg)

****

### Direction 2: Show some methods by default

This could show some topic names that were recently updated, or that widely used: 

![public lab tool 2ftechnique page rev 2](https://cloud.githubusercontent.com/assets/24359/21279362/d6f5139e-c3ad-11e6-9a03-6cbf53b60dfb.jpg)

**Comment by jywarren** [comment]
Oh, and one thing that I forgot to mention or include-- I think it would be great to have a prompt to [Add your own]() along with a link to [Why and how to share]() -- the first could go to Liz's recent "method template" activity

**Comment by steviepubliclab** [comment]
Hi Jeff,
Thanks for these. The visuals are really helpful. I think I prefer option
2. I was worried it would be busy, but I think this looks good, and I like
the size of the text buttons below.

A couple other thoughts:
- What do you think of moving the text that is below the text (search) box
to above it? Following down the page, it seems like you need to have text
in the box until you read further that the buttons are an alternative.
- Do you have ideas about the sidebar? I know it's not on the current page,
and I think that's a good thing. If we break out into these new sections, I
really think we should keep it off.
- On the current "recently updated/most popular categories" text, can we
pick one of these statements? which ever seems most important to know,
maybe "recently updated"
- On option 2, when someone clicks "view all" will the page show up like
the option 1 pg 2? that makes sense to me.


One thing I'm thinking about is, while this page is good for sorting out
categories of methods, I don't think it's going to help people in choosing
the "right method" for their question. I feel like the categories on the
new methods page header are the real crux of the info that people will need
to know. Searching by these might eventually become really valuable, not
now, but something we should maybe keep thinking about.

Thanks!

**Comment by jywarren** [comment]
> What do you think of moving the text that is below the text (search) box
to above it? Following down the page, it seems like you need to have text
in the box until you read further that the buttons are an alternative.

Sure, i can try a mockup of that too

> Do you have ideas about the sidebar? I know it's not on the current page,
and I think that's a good thing. If we break out into these new sections, I
really think we should keep it off.

agreed!

> On the current "recently updated/most popular categories" text, can we
pick one of these statements? which ever seems most important to know,
maybe "recently updated"

yes, i put both because i wasn't sure which we should show, but I strongly lean towards recently updated, agreed

> On option 2, when someone clicks "view all" will the page show up like
the option 1 pg 2? that makes sense to me.

Yep!

**Comment by jywarren** [comment]
![screen shot 2017-01-06 at 12 01 05 pm](https://cloud.githubusercontent.com/assets/24359/21725801/e20233ba-d407-11e6-92f0-c7cd2437217d.png)

**Comment by Pk13055** [comment]
@jywarren If you've decided which way to go, I could try incorporating the required mockup?

**Comment by jywarren** [comment]
Yes, why don't you go ahead, thanks! 

@steviepubliclab and @gretchengehrke, can we find a time to:

1. Make formatted tagnames for each of the topics we've listed here, I.e. with dashes and no spaces
2. Go and actually tag all the methods accordingly?

@Pk13055, I believe each topic "row" will be wiki pages matching the topic tag AND the tag "tool".

**Comment by Pk13055** [comment]
@jywarren Sorry, I was caught up with other stuff; I'll get working on this right away. I'll have a PR within a few days. I hope this isn't an urgent issue?

**Comment by jywarren** [comment]
No problem, we're grateful for your help!

**Comment by Pk13055** [comment]
@jywarren I'm caught up with some other work and don't think I'll be able to help out this time. Sorry!

**Comment by steviepubliclab** [comment]
hi @jywarren 

For the tags, a lot of them should work as is- but for those that are different can we do: 
- IndoorAir, 
- Chemical, 
- LandUse (and/or LandChange but have them search both?)
- Oil (and or Gas, but have them search both?) alt: OilandGas
- UrbanPlanning

originally on this post this was for tool page right? which is now methods  - but still question on activities/methods. We could just do both with these tags though I think, just curious which would show up on the page?

**Comment by jywarren** [comment]
Great, what about the ones that are `/` -- like Turbidity / Suspended Solids ? Two separate tags?

Yes, this is /methods -- so each method would show, and each one could say how many activities are available for it. So, for (totally made up examples):

**Aerial Mapping**
4 methods (Map with a pole, Stitch a map, Map with a kite)

**Timelapse**
3 methods (Set up a timelapse camera, Make a video from your timelapse, Build a DIY timelapse camera) 

We wouldn't need to actually list the activities by name, but just how many there are. 

I just checked and this was showing already but broke; i just submitted a fix.

**Comment by steviepubliclab** [comment]
Seems like the ones that would show up on the page are the first category? 
For the second category, I think a lot of the other tags are in use on those methods mostly. GG and I were just thinking about things that already existed. This second category being "things we could add to as new tools come on PL".

**Comment by jywarren** [comment]
Oh, ok, so we mostly (right now) need to think about displaying:

`agriculture`,
`drinking-water`,
`fracking`,
`indoor-air`,
`chemicals`,
`industry`,
`land-use`,
`land-change`,
`mining`,
`oil-and-gas`,
`transportation`,
`urban-planning`

Does that work for reformatting too? We have to use dashes since tags have no capital letters. 

`land-change` might be a little too ambiguous vs. `land-use` -- but let's see how it goes.

**Comment by steviepubliclab** [comment]
yeah I think that works. in your mind do these cover what exists? I guess I'm wondering if it would be easy to add/change them as PL grows?

**Comment by jywarren** [comment]
Also, for the default display, should we just show everything, organized by topic, and then narrow it down as people search? I ask because people may not use the search box, and by default then they'd see a full listing, and also because it could simplify the coding -- it'd mainly just be hiding/showing groups then. Easier to implement.

**Comment by jywarren** [comment]
Yes, we'd be able to expand them pretty easily. Thanks!

**Comment by steviepubliclab** [comment]
ehh I'm confused about the choice

**Comment by jywarren** [comment]
ok cool synced by phone. And we'll grey out the topics for which there are no methods, in the list.

**Comment by jywarren** [comment]
Progress in #1235, should be published this week for trying it out...

**Comment by steviepubliclab** [comment]
Great news!

**Comment by jywarren** [comment]
http://testing.laboratoriopublico.org/methods/mining shows initial styling work, though the actual results aren't complete.

**Comment by ebarry** [comment]
Wow looking amazing!

Quick thoughts on the wording:
- can we choose either techniques or methods for the sentence? gives us
more characters to add in "and advocacy" at the end of the sentence.
- "browse many of them" -- why not just "browse them"

*Public Lab's community collaboratively develops many different techniques
and methods for DIY environmental monitoring.*

*Browse many of them here and learn how to get involved.*

--

+1 336-269-1539
@lizbarry <http://twitter.com/lizbarry>

**Comment by jywarren** [comment]
Thanks, I just made up text so feel free to propose more thorough rewrites as well! Help with text is ALWAYS welcome!

I have to say, i'm thinking hard about how "methods" sounds a bit intimidating, which is why i mixed in other usages. If you can help make "methods" sound like something anyone can post or share, and not a SCIENTIFIC TERM (per se), I'd love to integrate new text.

**Comment by steviepubliclab** [comment]
Can we add the category "community-organizing" Will capture methods like "working with the media" and "public comment"

**Comment by jywarren** [comment]
Rad stevie's PR to do this is at #1312. Merging in a moment.

**Comment by steviepubliclab** [comment]
Woot! -- Merge Pull Request! 🎉

**Comment by steviepubliclab** [comment]
Hi again on this issue. I was looking at the page and wondering if there's
another category we're missing related to conducting research. Some of the
methods I think would fall under it are:
- https://publiclab.org/wiki/literature-review
- https://publiclab.org/wiki/health-effects-lit-review
- https://publiclab.org/wiki/start-enviro-monitor-study

I don't think these are captured in the other categories. Maybe this tag
could just be "research" ? A bit vague, open to suggestions.

-Stevie
