### ISSUE TITLE
Weekly Community Check-In #122 - Take Care of YOU!💅🏽 

### ISSUE THREAD

**Issue by Georjane** [publiclab/plots2#10475]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform that helps a newcomer to become a leader of tomorrow. 💯

## Take Care of YOU!💅🏽 
When working from home, it can be easy to let our professional and personal lives blend together. But without a clear boundary between being “at work” and being “at home” when working from home, our mental health may suffer. 🤕 

While many remote workers feel more productive and happier when working from home, that doesn’t mean that it’s all sunshine and roses. 91% of remote workers say that unmanageable stress or frustration impacts the quality of their work and 83% say burnout can negatively impact their personal relationships. For example, as a single mom, I get so frustrated when my 4 months old boy can't stop crying when I do everything humanly possible so I could get some work done.

Those who have been working remotely for years, they’ve worked hard to: Establish a routine that works for them, Set boundaries for their personal and professional lives, and Create a dedicated work area to distinguish work time from personal time. But for some of us who had to adjust overnight, it can be exhausting and overwhelming without having the right tools in our toolbelt. Hence the burnout..😄

This week share a self-care routine you practice in order to stay happy and healthy whether you are working or relaxing

Stretching and exercise especially dancing 💃🏽 do the trick for me!

## This week's focus Issues

These are issues that are of high priority and requests from our large community that uses the software. 

https://github.com/publiclab/plots2/labels/high-priority

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note to focus issues contributors

We say a huge thank you to everyone who completed/opened an FTO, reviewed PRs, welcomed newcomers to the community, and provided support to each other. Thanks so much, @Angelvicks 🥇, @Kabere34 🥇, @leau-void 🥇, @DalilaBA 🥇, @PaulinaGadea 🥇, @Goodiec 🥇, @wajeehamushtaq 🥇, @NARUDESIGNS 🥇, @subhangi2731 🥇, @Georjane 🥇, @Tlazypanda 🥇, @jywarren🥇, @TildaDares 🥇 

## Next Check-in
If you would like to open the next check-in. Leave a comment below. We are happy to help if it's your first time

**Thanks to everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by DalilaBA** [comment]
hey @Georjane thank you very much for this check-in 🎊 , I like to dance too haha, and I recently joined a gym club and it is very good so far, nothing more good then shacking up 😄

**Comment by Georjane** [comment]
> hey @Georjane thank you very much for this check-in 🎊 , I like to dance too haha, and I recently joined a gym club and it is very good so far, nothing more good then shacking up 😄

😄 😄 😄 I totally agree with you @DalilaBA !

**Comment by ebarry** [comment]
Anyone interested in opening the next check-in?

**Comment by jywarren** [comment]
Thanks @Georjane for this check-in! It's so true how important this is. I wish coding were more of a outdoors and sunshine, moving your body kind of activity, but it isn't! And your point on boundaries is right on. 🌟 

Thanks for looking after the health of our community!!!

**Comment by TildaDares** [comment]
Thanks everyone. Moving to #10489.

**Comment by beinjamin** [comment]
bonjour
