### ISSUE TITLE
Profile picture doesn't display on some pages after login such as publiclab.org/dashboard and publiclab.org/post

### ISSUE THREAD

**Issue by NARUDESIGNS** [publiclab/plots2#10481]
After logging in, you will find that the avatar (profile) image isn't displayed for some pages such as https://publiclab.org/dashboard and https://publiclab.org/post, however, for pages like https://publiclab.org/people, you can see the profile images.
Here are sample images to describe the situation better:
![Screenshot 2021-11-03 at 17 27 14](https://user-images.githubusercontent.com/49737323/140103813-f5afc292-e36b-48bc-b9d7-11cd7b7a9037.png)
![Screenshot 2021-11-03 at 17 36 33](https://user-images.githubusercontent.com/49737323/140103907-1f6cefe3-45cc-4bff-8a8c-688af5b22b2c.png)

**Comment by TildaDares** [comment]
I think this is a duplicate of #9450

**Comment by NARUDESIGNS** [comment]
Ok, thank you @TildaDares I will close this issue now. Please going forward, is there a way I can check if an issue has been open for a particular problem to avoid duplicates like this?

**Comment by TildaDares** [comment]
Hi @NARUDESIGNS, you can search for a keyword related to the bug you want to open an issue for.
