### ISSUE TITLE
Weekly Community Check-In #123 - Icebreaker Game🥶

### ISSUE THREAD

**Issue by wajeehamushtaq** [publiclab/plots2#10489]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Icebreaker Game 🌀

Icebreakers are commonly presented as a game to "warm-up" the group by helping the members to get to know each other. Being a part of the Public Lab community we are just like family. So we should know each other especially the fun fact about each other. So I have created some fun questions for our community members to get to know their personalities. It's not personal just as a fun side. 😁

1. If you are not a developer what would you be? 🤔
2. If you are invisible to everyone what would you like to do? 👻
3. Something funny you did in childhood? 🤩
4. Who is your favorite cartoon character?🧙‍♂️
5. What is the song you listen to when you feel down or when you are happy? 🎶

For me:
1. I will be an Arabic or western calligrapher
2. I will steal my sister's jewelry and make-up as she does not share them with me 😅
3. I used to wear my brother's clothes as I was a tomboy
4. Winnie-the-pooh 🤩
5. The Food and Star-up by Barbra Lica 

## This week's focus Issues

These are issues that are of high priority and requests from our
large community that use the software. 

https://github.com/publiclab/plots2/labels/high-priority

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note to focus issues contributors
I would like to thank each and every person who contributes to open-source projects and help others to learn something. All you guys deserve a trophy 🏆 because you are awesome.

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by Georjane** [comment]
Thank you @wajeehamushtaq for the weekly check-in😊🙏 
Very interesting topic, I love it.

- If I were not a developer I would be a civil engineer👷‍♀️
- if I were invisible I would watch movies all day while eating biscuits 😅
- i would carve out my play toys using papers I took my school books and hide the pieces of papers generated from doing this under my bed so my mom won't notice🤭
- Moana❤
- Try Everything by Shakira💯

**Comment by NARUDESIGNS** [comment]
Thank you @wajeehamushtaq 

If you are not a developer what would you be? 🤔
ans - I'd be a designer

If you are invisible to everyone what would you like to do? 👻
ans - go to silicon valley and present alongside Tim Cook lol

Something funny you did in childhood? 🤩
ans - tried to force a nail through a socket on the wall and got shocked.

Who is your favourite cartoon character?🧙‍♂️
ans - don't really have one, but batman or spiderman

What is the song you listen to when you feel down or when you are happy? 🎶
ans - everything I wanted by Billie Eilish or read all about it by Emily Sande

**Comment by wajeehamushtaq** [comment]
Thank you @Georjane and @NARUDESIGNS for your awesome answers. This shows how mischievous we are 🤣🤣

**Comment by ebarry** [comment]
1. I might be an environmental lawyer (phew what a good thing it is that i work in tech 😅 )
2. I would go eavesdrop in boardrooms and governmental suites to hear what the powerful say when they think no one is listening
3. Apparently I didn't speak in my early years, just read books
4. the Pink Panther
5. If i need a guaranteed pick-me-up: George Michaels "Faith"

**Comment by TildaDares** [comment]
Moved to #10514. Thanks everyone!
