### ISSUE TITLE
Assorted help-file and template changes

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1048]
This is a collection (please add if you have more!) of small changes to various templates. This is a good candidate for several distinct first-timers-only issues. 

@publiclab/reviewers -- input appreciated!

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

https://github.com/publiclab/plots2/blob/master/CONTRIBUTING.md

Add a First-Timers-Only section using text from README (https://github.com/publiclab/plots2/#first-time) with link to https://github.com/publiclab/plots2/projects/2

https://github.com/publiclab/plots2/blob/master/ISSUE_TEMPLATE.md

Add: "Suggested steps to resolve"

https://github.com/publiclab/plots2/blob/master/PULL_REQUEST_TEMPLATE.md

Add: "fixes `#number`" to show how you can auto-close issues

**Comment by Pk13055** [comment]
I have submitted a PR regarding this issue.
