### ISSUE TITLE
add community survey to website

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#105]
NB: This is not related to coding at this time. 

The need: 
- be able to identify regional trends or hot spots of people who want to get involved and be contacted. Relevant where there are not yet regional lists.

Proposal: 
- well-explained survey linked on front page of website with publicly available results

**Comment by jywarren** [comment]
Hi, Liz - could we close this due to the Eval project, at least for now?

**Comment by ananyo2012** [comment]
@jywarren Perhaps I can add this as an Google Code-in task as an outreach Activity if you would recommend. Though I am unaware of the Eval Project.

**Comment by jywarren** [comment]
I think this is one for @ebarry, but if she feels there's a way to break it
up, that's possible. We've just finished the Barnraising though, so perhaps
we need to circle back on this one when we're less behind on things.

**Comment by ebarry** [comment]
Closing this in favor of the Geographic Milestones project https://github.com/publiclab/plots2/milestone/7

**Comment by ananyo2012** [comment]
Oh great work Liz! Creating the milestone will help organize things.
ᐧ
