### ISSUE TITLE
Lead images on notes not displayed for non-logged in users

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#10513]
### Please describe the problem (or idea)

Reported from one of our fellows: lead images on research notes are not showing up unless he's logged in. Jeanette is seeing the same issue. She writes: 

> Curiously, there is some invisible element representing the lead image on the page when not logged in. If I hover in the white space above the title, I can see my cursor indicate a link (see bottom left URL on the "image_absent" screenshot) and if I click on it, I'm led to the image file. 

Here is a screenshot of a note not logged in: 
<img width="1580" alt="image_absent" src="https://user-images.githubusercontent.com/161439/142931792-c26c10df-a313-4708-add5-a19b4e927dfd.png">

Same note when logged in: 
<img width="1698" alt="image_present" src="https://user-images.githubusercontent.com/161439/142931821-5aa08081-85b8-403a-84cb-8f2b96441f55.png">

> What did you expect to see that you didn't?

I expected for notes to appear the same to logged-in AND non-logged-in users. 

### Please show us where to look

https://publiclab.org/notes/alejobonifacio/11-19-2021/aguas-cloacales-en-la-cuenca-del-rio-suquia

### What's your PublicLab.org username?

alejobonifacio
bhamster

**Comment by jywarren** [comment]
Hi, thanks, great documentation too. I see this error on incognito mode (not logged in):

```
Uncaught ReferenceError: $D is not defined
    at HTMLDocument.<anonymous> (editorToolbar-d4ea1f099e2c7f4d56fe865db604f40e3442fe08cfc763c9b610a1d023b4e5f1.js:1)
    at u (application-71ef264561fb4f8f6d91be6a202f54e213f5c0100c35ce925df4a2f577bbd0aa.js:30)
    at Object.fireWith [as resolveWith] (application-71ef264561fb4f8f6d91be6a202f54e213f5c0100c35ce925df4a2f577bbd0aa.js:30)
    at Function.ready (application-71ef264561fb4f8f6d91be6a202f54e213f5c0100c35ce925df4a2f577bbd0aa.js:30)
    at HTMLDocument.s (application-71ef264561fb4f8f6d91be6a202f54e213f5c0100c35ce925df4a2f577bbd0aa.js:19)
(anonymous) @ editorToolbar-d4ea1f099e2c7f4d56fe865db604f40e3442fe08cfc763c9b610a1d023b4e5f1.js:1
u @ application-71ef264561fb4f8f6d91be6a202f54e213f5c0100c35ce925df4a2f577bbd0aa.js:30
fireWith @ application-71ef264561fb4f8f6d91be6a202f54e213f5c0100c35ce925df4a2f577bbd0aa.js:30
ready @ application-71ef264561fb4f8f6d91be6a202f54e213f5c0100c35ce925df4a2f577bbd0aa.js:30
s @ application-71ef264561fb4f8f6d91be6a202f54e213f5c0100c35ce925df4a2f577bbd0aa.js:19
```

It corresponds to:

```js
dropZone:$("#side-dropzone"),dataType:"json",formData:{uid:$D.uid,nid:$D.nid}
```

which is where the comment editor is depending on variable `$D`, which is only present if you're logged in. 

So tracing this, it could be solved in 2 ways:

1. add a conditional before running the code in [editorToolbar.js](https://github.com/publiclab/plots2/blob/main/app/assets/javascripts/editorToolbar.js)
2. don't include `editorToolbar.js` when not logged in, but it seems maybe that include is made in [many places](https://github.com/publiclab/plots2/search?q=legacy-editor-container)

Either way, we should set up a test to confirm a main image loads, which would be at maybe:

1. https://github.com/publiclab/plots2/blob/4d662445527e5f0a9c070e684ad9a874ea99d955/test/system/post_test.rb#L123-L124
2. attach a main image with `main_image_id = ` to a node in fixtures and add a system test for it... but this is a lot of extra steps. Maybe better log out in the above system test and just check there?

**Comment by jywarren** [comment]
OK, starting with the test here, though it may need some tweaking for syntax: https://github.com/publiclab/plots2/pull/10517
