### ISSUE TITLE
Weekly Community Check-In #124 - Outreachy Winter'21 Interns announced!!

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#10514]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Outreachy Winter'21 Interns announced!!

Congratulations to @Georjane and @NARUDESIGNS  for being accepted into Outreachy Winter'21 cohort :heart: 

We hope you make out of your internship here at Publiclab. We are so excited to have you folks onboard :tada: We encourage you to share with us your experience of being accepted for Outreachy through a message or even a blog post (we love to read one of those). We also would like to highlight that during this internship tasks might be challenging at time but feel free to reach out to the mentors and seek help if you are stuck at any point of time. 

We would also like to thank all the amazing contributors @wajeehamushtaq, @jet2018 for their contributions during this period :100: who we were not able to accept due to limited slots. 

Looking forward to an amazing winter :snowflake: with you folks!!

### Thank you note to focus issues contributors

@cesswairimu for her absolutely amazing feat of reviewing over 25 Pull Requests :100: 
@DalilaBA for opening so many FTOs and welcoming new contributors :fire: 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by Georjane** [comment]
🥳🥳🥳💃💃💃

Thank you very much @Tlazypanda 💯
I am so honored to have been accepted as an Outreachy Intern to this amazing Public Lab community 💖 

I am so excited right now and I look forward to making a positive impact by contributing as much as I can to the community. I also look forward to outlining my whole experience in my blog so I could share with everybody and hope it inspires someone to join our open source community 🙏❤

**Comment by DalilaBA** [comment]
@Tlazypanda it is a big pleasure to be part of this community, I hope that Ill be able to help much more 😄

**Comment by NARUDESIGNS** [comment]
Thank you very much @Tlazypanda I'm both excited and nervous and I hope that I get to make those meaningful contributions that I have proposed.
I also will like to open the next check-in and yes, it is my first time so I need you to help guide me 
Thank you!

**Comment by TildaDares** [comment]
Congratulations @NARUDESIGNS and @Georjane 🎉🎉

**Comment by jywarren** [comment]
Congrats @Georjane and @NARUDESIGNS!

I'm so very thankful to everyone who applied to work with us. Every one of your contributions means a lot to us and we're grateful for your time and efforts.  🌟 🎉 ❤️ 

I know you all put in a huge amount of work and we're only able to work with a few of you. Know that you're always welcome here and that we wish we could work with more of you!

**Comment by Tlazypanda** [comment]
Congratulations @Georjane and @NARUDESIGNS :heart: 

And yes definitely feel free to reach out @NARUDESIGNS for any questions you may have for the weekly check-in!!

As @jywarren mentioned all the applicants are welcome here and we appreciate all your contributions as always :blue_heart:

**Comment by NARUDESIGNS** [comment]
> Congratulations @Georjane and @NARUDESIGNS ❤️
> 
> And yes definitely feel free to reach out @NARUDESIGNS for any questions you may have for the weekly check-in!!
> 
> As @jywarren mentioned all the applicants are welcome here and we appreciate all your contributions as always 💙

Hi, @Tlazypanda thank you very much. I sent you a message on Gitter chat with some of my questions.

**Comment by TildaDares** [comment]
Moved to #10531. Thanks everyone!
