### ISSUE TITLE
GCI16 Task Modularising Readme

### ISSUE THREAD

**Issue by pipix51** [publiclab/plots2#1052]
I would like to change the readme of the plots2 repository by modularising it. I have broken up the current readme into several sections, such as API, Bugs and Support, and Installation. The wiki repository that I have changed is at https://github.com/pipix51/plots2/wiki. Please review the modularised readme.

**Comment by ananyo2012** [comment]
Oh sorry @pipix51 but @EmilyOng has already claimed this task. Please claim the task first before you start working on it. Some tasks only have 1 instance count like this one. So it can be done by only one person at a time. You look at our other tasks labelled `publiclab` in the FOSSASIA task page. Be sure to claim the task first.

**Comment by jywarren** [comment]
This is complete in #1056 -- thanks to @EmilyOng !
