### ISSUE TITLE
Weekly Community Check-In #125 - STAY HEALTHY

### ISSUE THREAD

**Issue by NARUDESIGNS** [publiclab/plots2#10531]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## STAY HEALTHY

Our health is one of the most important aspects of our lives. As software engineers, designers, writers, maintainers and whatever roles we tend to find ourselves playing, it is paramount that we pay attention to our health and how we can improve them. Most of us spend hours on our computer or on a project, a study, a research or a survey as our job requires. We get too engrossed in it that we unconsciously build up habits that are physically and mentally unhealthy. Being productive may be a problem if we don’t first take care of our health. And so I have decided to share a few tips to help us work in a more balanced and healthy manner. Here are a few tips to help us work better.
- **Stand up and take a walk** - we sit a lot or stay stationary at some position for long and often. It is beneficial for us to pause and take a little walk to stretch our bodies and air our minds before coming back to continue from where we left off.
-  **Protect your eyes** - if you are like me and spend at least 7hours on your computer daily, then you should try placing your computer about 12inches back and use a blue light filter or anti-glare glasses if you got one.
- **Drink water, drink more water** - we love coffee which is okay but we should make sure to drink about 7-8 glasses of water daily to stay hydrated.
- **Exercise** - you may be too busy but twice or once a week is a good start for you to workout. Jog, run, swim, go to the gym, bike or do whatever it is you enjoy and in turn exercise your body.
- **Sleep well** - I have trouble sleeping sometimes as this is a habit I have built over time and so I’m learning to sleep for 7hrs every day. You should also find time to rest your body for a good amount of time.
- **Diet properly** - I’m no meal planner but take good food, fruits, vegetables, nuts in the right proportion.
- Lastly, **take vacations or some period off work**. Be with family, reach out to friends and visit places if you love to. Give yourself some time and come back fresh.

I wish I could share more, but I hope that this helps us get started with paying attention to our health. We only got one life, each of us and we have to live it right. Please share some of your tips that could help us stay healthy and productive.

### Thank you note to focus issues contributors

🥇 🥇 🥇 🥇 🥇 🥇 🥇
Thank you @najmieh for making your first contribution already! 🎈 
Also, thank you @DalilaBA @wajeehamushtaq @Georjane @cesswairimu @wajeehamushtaq @jet2018
Our mentors and maintainers as well, we want to thank you for your time and efforts @jywarren @TildaDares @Tlazypanda
🥇 🥇 🥇 🥇 🥇 🥇 🥇

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks to everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by jywarren** [comment]
Thank you so much for this thoughtful weekly check-in topic! It's so cold here right now (getting to be winter) that I am tempted to stay in all day. But today I rode my bike mid-day and indeed I feel so much better! 🚲 🚲

**Comment by TildaDares** [comment]
Moving to #10555. Thanks everyone!
