### ISSUE TITLE
Please invite me to the GitHub Organization

### ISSUE THREAD

**Issue by Jyoti-prakash-rout** [publiclab/plots2#10550]
I'm a Web Dev enthusiast & a junior pursuing my Bachelors in Computer Science & Engineering. I'm interested in Web Devlopment, Machine Learning & DevOps & I enjoy learning new things & stuff as well as I'm a Frontend Devloper with experience building Dynamic & Static Web pages. I am always interested in learning the answers to how, why, and what relates to the Technologies around me.

I would like to grow my programming skills by doing lots of Open Source contributions. Looking forward to learning, collaborating, and growing as a community.

**Comment by anirudhprabhakaran3** [comment]
Hello!
I would suggest you check out code.publiclab.org to get an idea of how to start contributing. You can join our Gitter channel for more. 
As a beginner, you can either try to setup the project on your local system, or use GitPod. To start contributing, you can check the first time issues.

Thank you!

**Comment by TildaDares** [comment]
Hi @Jyoti-prakash-rout, welcome to Public Lab🎈. There's an open issue you can work on in #10207.
If you have any questions/issues or feel like introducing yourself to the community, you can join the [Gitter channel](https://gitter.im/publiclab/publiclab). We also look forward to working with you😃.
