### ISSUE TITLE
Weekly Community Check-In #126 - Something New That You've Learned

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#10555]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform that helps a newcomer to become the leader of tomorrow. 💯

## Something New That You've Learnt 

Every time I work with a contributor to resolve their issues/PRs I learn something new. I learn new acronyms, new ways of doing things that I've never would have thought of doing before. This is one of the reasons why I love contributing to Open Source. Collaborating with people teaches you things that you probably wouldn't know about working alone. 

I'll be sharing two things I've learned recently from working with the Public Lab community.

- I learned that PTAL means [Please Take a Look](https://github.com/publiclab/plots2/issues/10409#issuecomment-960908254) from @ShivamJhaa 😅
- This morning I also learned that Github has a feature that converts a task list to an issue while going through @NARUDESIGNS [planning issue](https://github.com/publiclab/PublicLab.Editor/issues/760#issuecomment-987781288)

For this week's check-in, I'd love to hear about new things that you've learned. It doesn't have to be something you learned from someone else.
## This week's focus Issues

These are issues that are of high priority and requests from our
large community that use the software. 

https://github.com/publiclab/plots2/labels/high-priority

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note to focus issues contributors

🥇 🥇 🥇 🥇 🥇 🥇 🥇 Thank you @najmieh, @KarishmaVanwari, @madhhuurrii, @Prerna-0202, @Georjane, @NARUDESIGNS, @jywarren, @Tlazypanda and everyone else who has made a contribution. 🥇 🥇 🥇 🥇 🥇 🥇 🥇

Also, I'd like to wish the Outreachy interns @Georjane and @NARUDESIGNS  an amazing first week. 

## Next Check-in
If you would like to open the next check-in. Leave a comment below. We are happy to help if it's your first time

**Thanks to everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by NARUDESIGNS** [comment]
Thank you @TildaDares 
I learnt from you that LGTM means Looks Good To Me lol.

**Comment by Georjane** [comment]
> Thank you @TildaDares I learned from you that LGTM means Looks Good To Me lol.

oh wow, I just learned this too now! 😄 thanks for this amazing topic for this week's check-in.
Also, I was wondering what **plots** stand for? @TildaDares. I guessed Public Lab Outreachy Software... 🤔 😃

**Comment by ebarry** [comment]
Happy first week of December to all!
Something I learned about recently was this open data model for sharing hardware designs: https://www.internetofproduction.org/open-know-how

**Comment by madhhuurrii** [comment]
Thank you for tagging me, I would love to contribute more in coming days! 
Recently I bought a ukelele and have started learning it (as a complete beginner).

**Comment by ShivamJhaa** [comment]
This week I learned about testing with karma and jasmine and also came to know about gitpod, how awesome this tool is for contribution.

**Comment by NARUDESIGNS** [comment]
Oh, I also learnt the basics of Jasmine and Jest test syntax (most of which are similar) and then I learnt about BDD (behaviour-driven development) and TDD (test-driven development). I started to learn this because I've been asking @jywarren too many questions about tests the past few days lol.
At first, I was too worried about it (I still am a little tbh) but I believe I'd get comfortable with it soon.

**Comment by jywarren** [comment]
> Thank you for tagging me, I would love to contribute more in coming days! Recently I bought a ukelele and have started learning it (as a complete beginner).

I love this! 🎸 

@NARUDESIGNS never too many questions 🎉 

@ShivamJhaa yeahhhhhh gitpod has really been a revolution!

I've been learning a lot recently - i enrolled in Korean language school. I know a lot of Korean words from my family but it feels great to be learning whole sentence structures and more!

**Comment by TildaDares** [comment]
Thanks everyone! Moved to #10631
