### ISSUE TITLE
Add remove profile photo button

### ISSUE THREAD

**Issue by sakshi-2412** [publiclab/plots2#10566]
Right now, if a user has uploaded a profile photo, there is no way to remove it ( set it back to default ). 

**Please describe the desired behavior.**
There should be delete button to remove user's profile photo in the edit profile form.

Also, if a user uploads a photo, the same is not shown in the edit profile form till the window is reloaded.

https://user-images.githubusercontent.com/85152262/145716315-5b37bc27-03a0-420c-af2d-1385b40c94e9.mp4

A quick fix would be to reload the page after photo is updated. I have used this fix for the time being :sweat_smile:

**Additional context (optional)**
I tried to do some changes, (if they look good I can open a PR) 

https://user-images.githubusercontent.com/85152262/145716072-7e0c9103-866e-4adc-a455-69697c2be5a8.mp4

**Comment by TildaDares** [comment]
@sakshi-2412 Brilliant observation! You are free to open a PR. Thanks!
