### ISSUE TITLE
invite involvement in updating wiki pages via notices

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#106]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem
Give a bootstrap alert on top of wiki pages that haven't been edited for the past 6 months prompting users to contribute to it.

## Solution
Go to the [wiki/show](https://github.com/publiclab/plots2/blob/master/app/views/wiki/show.html.erb) template and add an alert with `.alert-info` bootstrap class with some text like "This wiki page hasn't been edited for quite long. Consider updating it if you are acquainted with it."

This should be shown for wiki pages that haven't been edited for past 6 months. So the code should be like
```ruby
<% if @node.latest.created_at < Time.now - 6.months %>
  <div class="alert alert-info" role="alert">...</div>
<% end %>
```

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by ananyo2012** [comment]
@jywarren Some idea on this?

**Comment by jywarren** [comment]
We could display a notice if a wiki page hasn't been edited in more than 6
months, and say "wiki pages need help from contributors like you" or
something...

**Comment by ananyo2012** [comment]
@jywarren Does this look ok now? I was thinking of adding this as a Google Code-in task.

**Comment by jywarren** [comment]
I think this would make a good GCI task, yes!

**Comment by fankee** [comment]
I would like to take this up if no one is working on it.

**Comment by ananyo2012** [comment]
@fankee This is actually reserved as a Google Code-in task. Can you take up other issues that aren't labelled with `gcin` label? You can look at [fto-candidate](https://github.com/publiclab/plots2/labels/fto-candidate) issues. They are close to becoming first-timer issues.

**Comment by MayankKashyap** [comment]
@jywarren u would like to take this issue , because I think no one work on it

**Comment by MayankKashyap** [comment]
I*

**Comment by MayankKashyap** [comment]
I mean to say that , I would like to work on this issue

**Comment by MayankKashyap** [comment]
@jywarren can i work on this issue.?

**Comment by jywarren** [comment]
Yes I think you're right, and GCI is now over for a few months. Please go ahead, and thanks!

**Comment by MayankKashyap** [comment]
OK @jwarren , I am working on it

**Comment by MayankKashyap** [comment]
Hey, anyone tell me how I can check whether the wikipage is updating or not.?

**Comment by aspriya** [comment]
@MayankKashyap , are you still working on this one. As I'm hoping to contribute for Wiki Discussion idea in GSoC, I'm just fixing issues related to it.

**Comment by jywarren** [comment]
Hi, yes apologies for my slow reply. What exactly do you want to check?
