### ISSUE TITLE
Weekly Community Check-In #127 - Productivity

### ISSUE THREAD

**Issue by NARUDESIGNS** [publiclab/plots2#10631]
# OUTREACHY WEEKLY CHECK-IN
### Hi everybody!** 👏
We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.
We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

### PRODUCTIVITY
Staying productive throughout the day or throughout our course of work can be difficult. We are often distracted by other things that seem (or even most likely are) interesting than work itself and so we tend to procrastinate a lot or manage our time poorly. For this week’s checkin, I wanted to share some tips I use to combat procrastination and get work done as much as I can. I’m not perfect at this myself yet but I’m working on it and I hope it helps you.
I came across the Pomodoro Technique developed by Francesco Cirillo, which helps us manage our time with work.

### The Pomodoro Technique
The Pomodoro Technique is pretty simple, you set a focus time of 25mins for work (or study, whichever stuff you need to focus on), then you take 5mins break afterwards and after 4 rounds, you take a longer break of 25mins.
To practice this, I advise that you make use of a timer. You can follow these rules to practice it:
1. **Set 25mins timer**:  Make sure you don’t do anything else asides from work within this period of time. Once the timer is started, you have to complete it.
2. **Take a 5mins break:** After the 25mins elapses, you have to take a 5mins break. You can take a walk around your office or room, reply to friends or mails or checkout Instagram but this time is meant to relax your brain and mind for the next round. 
3. **Repeat**: After the break is over, you have to start another round and keep the intervals going.
4. **Take a 25mins break:** After 4 rounds, you have to take a much longer break of 25mins and this time you could go play some PlayStation, read some article or whatsoever but again remember that this is time to relax your brain so do not do some other form of work that requires more brainwork.

### Break Down Tasks Into Chunks
Sometimes, the tasks for the day gets so overwhelming that we do little to nothing for the day. A good way is to break down tasks into little chunks. For this, I make use of a hard copy of sticky notes. First, I break down my tasks for the day into several chunks and then I take a look at them to decide which major 3 of them I’d like to complete for the day. I pen this into the sticky note and place it in front of my desk where I can look at it most of the time.
Some tasks take a long time or need more resources, so it's ok to jump onto another task and keep going.

### Have a daily routine
Having a daily routine isn’t easy and requires discipline but if you have a pretty good idea of how your day should go (even though it doesn’t always go that way) then you are more likely to achieve some of your set goals for the day than going through your day without a routine. 

There you go guys, these are my tips for staying productive but please remember to have fun and take breaks rather than work all through to avoid burnouts. If you’d like to share more tips on how we can stay productive, I’d be more than happy to hear your tips. 
Thank you for reading!

## Thank you note to contributors
Many thanks to the contributors of last week 🥇 🥇 🥇 🥇 🥇 🥇 🥇  @RaviAnand111 @TildaDares @jywarren @billymoroney1 @Georjane @Tlazypanda @jywarren @NARUDESIGNS  🥇 🥇 🥇 🥇 🥇 🥇 🥇

**Next Check-in**
If you would like to open the next check-in. Leave a comment below. We are happy to help if it's your first time.
Thanks, everyone for making Public Lab awesome ❤️
Have a great week ahead all 🎈

**Comment by Georjane** [comment]
Thank you very much @NARUDESIGNS for these productivity tips. 🙏🏽  I would definitely try it out this week.

Personally what I do to be productive is to write down my tasks and goals for the day at the start of the day then I can track my progress and measure my productivity at the end of each day.
Also, I love working in the early hours of the day say 3 am...I tend to be more productive at that time, 😄 

thanks again @NARUDESIGNS  I will try out some of your tips. This is my first time learning about the Pomodoro Technique

**Comment by jywarren** [comment]
Hi @NARUDESIGNS - thanks for a great topic! I'm not a Pomodoro practitioner myself but I love the idea, and how it emphasizes the importance of rest. Sometimes we feel like we need to be pushing all the time, but that's not actually the way to be our best. Also, from my experience, folks who use Pomodoro are just nice people. Not scientific data, but my experience. 😄 🍅  I wonder if it is causative - i.e. well rested people are nicer, or if it's the other way around, nice people take good care of themselves? Either way I support!

@Georjane i'm a list maker too. It feels great crossing them off. And I also appreciate the idea of finding the "best time" as we're all quite different at different times of the daily cycle -- even irrespective of our outside-of-work obligations, I think! I'm very positive in the morning, but also more introverted. I think it's my most productive time of day. But sometimes I also get a late night urge to crack a problem, and it can be super productive. 💪

**Comment by TildaDares** [comment]
Moved to #10668. Thanks everyone!
