### ISSUE TITLE
add a powertag to write more explanatory titles for display in grids?

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1063]
## Problem

I am working on making a great method page (https://publiclab.org/tools) that i can show people as an example. For simplicity, i've been working on https://publiclab.org/wiki/coqui. 

On that page, the activity grid (https://publiclab.org/notes/liz/08-30-2016/check-out-these-activity-grids) is working well: 

![screen shot 2016-12-05 at 3 57 12 pm](https://cloud.githubusercontent.com/assets/161439/20902462/4aeb0792-bb05-11e6-9198-12bfc8cccacf.png)

but i notice that directly below the grid all there's a lot of repeat links, basically it's what was on this page before there was an activity grid: 
  
![screen shot 2016-12-05 at 4 08 31 pm](https://cloud.githubusercontent.com/assets/161439/20902453/3e095d44-bb05-11e6-82e4-8e524b1582bd.png)

![screen shot 2016-12-05 at 3 57 25 pm](https://cloud.githubusercontent.com/assets/161439/20902456/41e22e50-bb05-11e6-9f02-5062f9551c04.png)

Actually, as I look at it, i think that the old way is easier to understand because the activities are introduced in a particular order, and with explanatory text that is more helpful than the actual title of any given post. 

> Part of the problem may be that the title of any particular post might not be understandable to someone new reading it and getting started, but only the author can edit them. 

## Proposed solution

But using Power Tags (https://publiclab.org/wiki/power-tags) we could add an "additional attribute" to this pre-existing content. 

In this issue I am suggesting that we should create a powertag to add an additional field to activity grids offering an additional, a more explanatory title for each linked note.

### Walkthrough

So someone who's not the original author but who is working on organizing this research area might:

1. see that the title isn't optimal for the grid display
2. go to that post (link to post) and think of a new title that would work better
3. add that via a power tag like `grid-title:<lalala>`
4. the grid would show the powertag-based title instead of the original

Another part of the solution is ordering the activities with a powertag, (like in #766).

## Code links

Help me find where the relevant code is, @jywarren (or @publiclab/reviewers)

**Comment by Pk13055** [comment]
@ebarry Has this issue/feature been resolved yet? I would like to help out if required.

**Comment by arkokoley** [comment]
@ebarry Has this issue been resolved yet? I would like to take on this, if its still open.

**Comment by ebarry** [comment]
@jywarren is there anything else going on that affects our ability to move on this?

**Comment by jywarren** [comment]
So, we have a "suggested title" feature in comments, although I worry it is fragile and maybe broken? I wonder if we should close this and open an issue for fixing the suggested title comment feature and protecting it with a system test! I'm going to close this and if you're interested, please do this!

![image](https://user-images.githubusercontent.com/24359/58596677-003e1880-8243-11e9-9d99-9353dd5755c4.png)
