### ISSUE TITLE
Weekly Community Check-In #128 - There is always a first time, for everything

### ISSUE THREAD

**Issue by mittal-parth** [publiclab/plots2#10668]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## There is always a first time, for everything
Exploring or experiencing the unknown can be intimidating and challenging. However, there is always a start. From the first line of code, the first commit, the first PR, the first self-cooked dish to your first income - there is always a start, often forgetting the importance of acknowledging the same. 😌
Each start adds to your personality and leads to actions that could eventually even define your identity! ✨ 
These were some of my firsts in the past week or two:

☑️ Made my first [PR](https://github.com/publiclab/plots2/pull/10634) to PublicLabs 
☑️ Taught the basics of Ruby to 60+ students as part of a Web Development Bootcamp at our college 
☑️ Drove a car independently 
☑️ (And now I have written my first community check-in!)

The result is immense happiness and satisfaction. I would love it if you could reflect and share some of your firsts over the last couple of weeks! 🎉 
Cheers to more firsts! 🥂 

## Thank you note to the recent contributors
Many thanks to the active contributors of last week 🥇 🥇 🥇 🥇 🥇 🥇 🥇  @DhruvGala, @sakshi-2412, @AshSmah, @dependabot[bot], @anirudhprabhakaran3, @jywarren  🥇 🥇 🥇 🥇 🥇 🥇 🥇

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by ebarry** [comment]
I had a first this week, switching off Google Chrome to the Brave browser! Very happy so far with the additional privacy features.

**Comment by jywarren** [comment]
Hi @mittal-parth thank you so much, and what a nice topic for the week! My first was making lasagna from freshly made pasta. It was delicious! 🍝 

I hope to have a first of building a small shed in my mom's backyard - so that's my aspirational first! 🪚 🛠️ 😅

**Comment by mittal-parth** [comment]
Nice to hear that @ebarry ! I should also give it a try I think!

**Comment by mittal-parth** [comment]
Thank you @jywarren !! 💙 
That sounds mouth watering! 😋 
My aspirational first would be to participate in my first hackathon. I wish you luck with building the small shed! 
Oh I see you were talking about creating different releases - must have been helpful there.

**Comment by Georjane** [comment]
Hahaha 😄 my first for this week was giving my baby solids. I tried giving him cereals for the first time which he kind of resisted but I guess he will get use to it with time.

And a first for me on PublicLab for this week was contributing to an npm package, spectral-workbench.js 🚀

**Comment by sakshi-2412** [comment]
I learned about docker this week, how awesome it is!🥺
( Also, thanks to Public Lab, I love the idea of weekly community check-ins - they are encouraging and thoughtful✨)

**Comment by RaviAnand111** [comment]
This week was so much fun, I learned alot of things, jquery, javascript and much more. 
First for me was : 
1. I learned to use `git restore` and `git revert` for first time. 
2. I also have started to learn "how to play chess" in this week. 

Thanks to @NARUDESIGNS  and @TildaDares for teaching me. 
Being part of this community is awesome.

**Comment by NARUDESIGNS** [comment]
Thank you very much @mittal-parth 
My first with Public Lab was actually a lot of things so I'd just skip those and talk about stuff I used for the first time this week. 
For this week, it was my first time using git suggestion, thanks to @TildaDares. It was also my first time running the codebase on Gitpod environment. Public Lab is a beautiful community, I've been learning ever since I got here!

**Comment by jywarren** [comment]
> For this week, it was my first time using git suggestion, thanks to @TildaDares.

Interesting, actually what is git suggestion, I'm not familiar with that!

**Comment by anirudhprabhakaran3** [comment]
So interesting to read about everyone's new experiences! My college semester started this week, and i'm ambivalent about what I think of it 😅 . I started learning a new web framework, Phoenix (based on Elixir) and started learning React! In the non-tech world, I have started reading Anna Karenina. Looking forward for a great time 😄

**Comment by mittal-parth** [comment]
So cool to hear everyone's experiences! 🥺 
As @sakshi-2412 mentioned, I also like this idea of community check-ins. its a great way to bond! ✨

**Comment by govindgoel** [comment]
I learned this week about the Turing awards and went through the contributions of the 2009 winner. 
To know more: https://amturing.acm.org/award_winners/thacker_1336106.cfm

**Comment by TildaDares** [comment]
Moved to #10682. Thanks everyone!
