### ISSUE TITLE
Profile pictures on profile pages aren't loading

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#10677]
Reported by @ebarry  - pages like https://publiclab.org/profile/warren aren't loading their profile images - they're stuck pre-lazyload (https://github.com/tuupola/lazyload)

Running `$("img").lazyload();` doesn't work (it does for other lazyload images)

`$("img.rounded-circle").lazyload();` also doesn't, although for both of these `$("img.rounded-circle")` and `$("img").lazyload();` the element is actually returned.

`$(".order-md-last img").lazyload();` works. Huh?

We need to search https://github.com/tuupola/lazyload/ to see what's up! An easy fix would be to explicitly add the last line above but that's messy. Let's try to figure out what's actually going wrong!

**Comment by Ash-KODES** [comment]
hey,can i work on this?

**Comment by govindgoel** [comment]
@jywarren I checked this and seems to be similar to https://github.com/publiclab/plots2/pull/10645.
In `profile.html.erb` we have image_tag here also, in local it is working fine but not in production as I can check.
 ```<%= image_tag(@profile_user.profile_image(:medium), class:'rounded-circle', id:'profile-photo', style:"width:50%;margin-bottom:20px;") %>```

**Comment by KarishmaVanwari** [comment]
Hey @jywarren @govindgoel, can I take up this issue?

**Comment by Forchapeatl** [comment]
Please May I take this issue?

**Comment by KarishmaVanwari** [comment]
@jywarren @govindgoel @TildaDares I've opened a PR #10802. Please have a look. Thanks!
