### ISSUE TITLE
Bring "embed button" function from notes grids to thumbnail grids

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#10686]
Grids (as in ) have a small "embed" button in the bottom right corner - almost invisible! But a small grey `</>` icon or something similar:

![image](https://user-images.githubusercontent.com/24359/152025208-d52d226c-4879-48b8-b867-c127fe89a2fe.png)

Let's port that function over to the "thumbnail image grids" as shown in https://publiclab.org/wiki/coqui (this page has both types actually):

![image](https://user-images.githubusercontent.com/24359/152025462-2b187b69-1555-4f36-9aff-9bf690406197.png)

Actually the code for embed grids is a bit duplicated - it appears in both 

https://github.com/publiclab/plots2/blob/b11aa99180db020562a9e379e63081f4e31995f3/app/views/grids/_notes.html.erb#L106-L125

and 

https://github.com/publiclab/plots2/blob/b11aa99180db020562a9e379e63081f4e31995f3/app/views/grids/_wikis.html.erb#L36-L56

We should move it into a re-usable partial template and then install it in the thumbnails grid template here: https://github.com/publiclab/plots2/blob/main/app/views/grids/_thumbnail.html.erb

Don't forget we need the actual icon itself too: 

https://github.com/publiclab/plots2/blob/b11aa99180db020562a9e379e63081f4e31995f3/app/views/grids/_wikis.html.erb#L29

The new partial can be in the same folder, and called: `_embedButton.html.erb`. We will have to pass in the 2 variables `className` and `randomSeed`, so that the code inside the partial template can still access those variables:

```rails
<%= render partial: "grids/embedButton" , locals: {className: className, randomSeed: randomSeed} %>
```

This isn't too hard but has many parts, and will require creating test grids using the syntax on the example wiki page https://publiclab.org/wiki/coqui in your local copy of the code. I'm happy to help people work through this!

**Comment by sakshi-2412** [comment]
@jywarren I would like to work on this

**Comment by jywarren** [comment]
We'd love your help! Have you completed a first-timers-only issue from https://github.com/publiclab/plots2/issues/10153 or https://code.publiclab.org? Thank you!

**Comment by sakshi-2412** [comment]
Yes I have completed my first-timers issue. I'll start working on this one. Thanks 😄

**Comment by jywarren** [comment]
Hi @sakshi-2412 would you like some support on this? I'm happy to and please reach out in the chatroom at https://gitter.im/publiclab/publiclab as well if you'd like some help!

**Comment by sakshi-2412** [comment]
Hello @jywarren sorry for the delay caused. I had some family emergency. I will surely reach out to you if I want some help, I will be updating you soon with my work. Thanks! 😄

**Comment by sakshi-2412** [comment]
@jywarren I did the following things - added the embed button to thumbnail grids using partial template and removed it from notes and wikis list. 

https://user-images.githubusercontent.com/85152262/154328227-7a55c80e-597a-4636-a5c5-38c8db8190b3.mp4

I couldn't understand the usage of passing className variable in the template. It is used in this line 
`setupGridSorters(".<%= className %>-<%= randomSeed %>"); `
I think this code is related to grid sorting and not the embed button, and thus should not be included in the partial template. Am I correct?

Rather than className, I had to pass type and tagname variables to the partial template.

**Comment by jywarren** [comment]
Hi, I believe we use className to provide unique identifiers for both css and JavaScript functions, so I would pass it in just in case. But if that doesn't make sense I'm happy to review more closely! 

I'm sorry to hear of your emergency and please take as much time as you need, no worries.

**Comment by sakshi-2412** [comment]
Oh okay I understand it now. Thanks for your help. I will open a PR soon :sparkles:
