### ISSUE TITLE
JSON API for wiki pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1069]
Heard a request from @devinbalkind -- to access wiki pages.

I think we could start by modifying this `show` method in the tag
controller:

https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L16-L51

This ought to be in a new issue, but please feel free to copy over, or ask
me and I can create one!

We could break out the response by format type, as is done on this line of
Spectral Workbench:

https://github.com/publiclab/spectral-workbench/blob/master/app/controllers/spectrums_controller.rb#L72-L76

So, like:

```ruby
    respond_with(@nodes) do |format|
      format.html { render 'tag/show' }
      format.xml  { render :xml => @nodes }
      format.json  { render :json => @nodes }
    end
```

That'd make it possible to send a request similar to the usual one for wiki
pages, for example:

https://publiclab.org/wiki/tag/tool (for the tag `tool` -- all tool pages, as Devin's expressed interest in)

But add a format to the request, like:

https://publiclab.org/wiki/tag/pm.json

And you'd receive `@nodes` in JSON format as a result.

We'd want to write a functional test for it too, and an API page entry, but
that should be pretty easy.

A test could be added to:

https://github.com/publiclab/plots2/blob/master/test/functional/tag_controller_test.rb

and look like:

```ruby
  test "tag show JSON" do

    get :show, id: tags(:spectrometer), format: 'json'

    assert :success
    assert_not_nil :tags

    json = ActiveSupport::JSON.decode(@response)

    assert_not_nil json
    # assert more things to check this
  end
```

Thanks!!

**Comment by 500swapnil** [comment]
Hi I would like to help with this one. How do I proceed?

**Comment by jywarren** [comment]
I think we can just add the `respond_with` block I suggested, below. Make sense? Thanks!

**Comment by 500swapnil** [comment]
#1071

**Comment by jywarren** [comment]
wow, that was fast!

**Comment by jywarren** [comment]
This is now complete and merged in #1071 -- thank you very much, @devinbalkind and @500swapnil !

**Comment by jywarren** [comment]
We may publish tonight or tomorrow.

**Comment by jywarren** [comment]
Online! I dropped some quick documentation onto this page: https://github.com/publiclab/plots2/wiki/API

**Comment by devinbalkind** [comment]
Cool!

How do I get a feed of tools?

I tried https://publiclab.org/tag/tool:*.json but that didn't work for me.

Thanks.

**Comment by jywarren** [comment]
I believe it's working at https://publiclab.org/tag/tool.json -- and please open a new issue if you have specific metadata or fields requests. Thanks!

**Comment by devinbalkind** [comment]
Nice.

Can I get:
* thumbnail image link
* full path (i.e. hyperlinkable)
* first 100 character description
* tags

THANK YOU!!!!
