### ISSUE TITLE
Make scrollbars optional, or add custom scrollbars

### ISSUE THREAD

**Issue by anirudhprabhakaran3** [publiclab/plots2#10720]
### Please describe the problem (or idea)
In the wiki pages, the tables have scrollbars attached at both horizontal and vertical axes, even though they perform no function in this case. 
<img width="615" alt="image" src="https://user-images.githubusercontent.com/76864239/153695955-95f0712f-1d6f-4a90-80bd-057aaf4f0c04.png">

> What happened just before the problem occurred? Or what problem could this idea solve?
By making the scrollbars either optional based on the content, or making some sort of custom scrollbar, we can make the UI look better.

> What did you expect to see that you didn't?

A non functioning scrollbar.

### Please show us where to look

https://publiclab.org/wiki/micro

### What's your PublicLab.org username?
> This can help us diagnose the issue: 

anirudhprabhakaran3

### Browser, version, and operating system
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

Google Chrome - 98.0.4758.82 (Official Build) (64-bit) (cohort: Stable) 
OS - Windows 11 Version 21H2 (Build 22000.493)

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by KarishmaVanwari** [comment]
Hey @anirudhprabhakaran3 can you please assign me this issue ?

**Comment by anirudhprabhakaran3** [comment]
Hmm, I don't think I can assign this issue, but I think @KarishmaVanwari can work on it since she brought it to our attention. @adi611 you can look into other issues available!

**Comment by KarishmaVanwari** [comment]
Yes, I'm on it. Thanks @anirudhprabhakaran3 !!

**Comment by cesswairimu** [comment]
Great collaboration here :tada:   @KarishmaVanwari  I have assigned you the issue. @adi611 please do let me know if you can't find another issue one and I can help find you one. Thanks all

**Comment by KarishmaVanwari** [comment]
Thank you @cesswairimu!!

**Comment by cesswairimu** [comment]
more info:  These lists are  generated using in-line power tags that can be added by an author when making a wiki, research notes etc more info on these and how they are used can be found [here](https://publiclab.org/wiki/power-tags#Inline+power+tags)

**Comment by KarishmaVanwari** [comment]
@cesswairimu @anirudhprabhakaran3 
I've created a PR #10756 , please have a look. Apologies for the delay.

**Comment by cesswairimu** [comment]
No worries @KarishmaVanwari and no apologies needed we encourage contributors to contribute when they can and most of our contributors come and go as they wish or based on how their schedules are, so please no need to apologize :slightly_smiling_face: taking a look now and thanks for working on this :heart:

**Comment by KarishmaVanwari** [comment]
Thank you so much @cesswairimu!! ❤
