### ISSUE TITLE
Call for Summer of Code mentors 2022!

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#10728]
Hi all :wave:
We have applied to [GSoC](https://summerofcode.withgoogle.com/) and we have been accepted to [Outreachy](https://www.outreachy.org/) :tada: .   We are hereby looking for folks interested in mentoring both or either of these programs, this coming summer. We have been participating in both programs  for  a several years now.

Outreachy internship period this year is 30th May - 26th Aug-- [full timeline](https://www.outreachy.org/apply/project-selection/)
GSoC internship period is  20th May - 12th Sept-- [full timeline](https://developers.google.com/open-source/gsoc/timeline)
*N/B:*  both programs are allowing for an extension of the internship period this round

Last year's proposals for Outreachy are [here](https://publiclab.org/notes/cess/04-04-2021/call-for-proposals-outreachy-summer-2021) and  for GSoC [here](https://publiclab.org/notes/cess/03-24-2021/call-for-2021-gsoc-proposals)

**We especially welcome people from groups underrepresented in free and open source software!**

It's very important to us to have diverse representation in our mentor group just as in our participant group. And remember -- our community aspires to be a respectful place. Please read and abide by our [Code of Conduct](https://publiclab.org/conduct)
We are calling for individuals who would like to be mentors for this round.

### Projects:
**[Here](https://publiclab.org/wiki/gsoc-ideas#2022+Ideas) is the list of potential projects for the summer round(_additions are ongoing_)**
**[And here](https://github.com/publiclab/plots2/issues/10754) is the discussion issue for this summer's projects**
 

### To participate as a mentor:
We're asking for mentors that have taken some of the following steps to be part of our community:

1. Solve a [first-timers issue](https://code.publiclab.org/#r=all). Provide the link to the first timer issue's pull request (PR) once it's merged. In case, you are not able to find any first-timer issue, solve issue marked as `fto-candidate` or `support`, these issues may require little more work, but we'll try to help.
2. Solve a [help-wanted issue](https://github.com/publiclab/plots2/labels/help-wanted). Help wanted issues are issues which are neither labelled  as `fto-candidate` nor as `first-timer-only`. Provide link to such issues' merged PR.(Make sure you claim the issue first by commenting on issue you are planning to solve)
3. Make a first-timers issue. [Use the extra friendly template](https://github.com/publiclab/plots2/issues/new?assignees=&labels=fto-candidate&template=--first-timers-only.md&title=) which we generally use for creating our first timer issues. Provide the link to the first timer issue which is created by you.

### What do mentors do:
Mentors check in with a student at least once per week roughly from May-Sept(_refer to exact timeline above_), and offer some project management guidance and encouragement... while relying on the [chatroom](https://publiclab.org/chat) and the 
[reviewers group](https://github.com/orgs/publiclab/teams/reviewers) to provide code-specific input, so that we share the burden of specific technical support. We have weekly Check-Ins on GitHub (https://github.com/publiclab/plots2/issues/9600) as well, and mentors are expected (along with students!) to be in the rotation to post these occasionally.

Remember that to be a mentor you don't necessarily need to know how to code -- we also need mentors who know Public Lab's community and practices well, and who can encourage students to speak up when they get stuck, and to ask the community for input and testing of their work. Students often get stuck when they don't know how something should look, or how a feature might be used by the community -- contextual info!

If you're interested in being a mentor, please leave a comment here, fill in [this form](https://docs.google.com/forms/d/1Dd6yplcKAuBHyXga9u2ME-lEv4SnLKFmYzglkd_1qQM/) and read over our [software outreach resources](https://publiclab.org/software-outreach) to get an idea of how we work!

### Helpful resources on mentoring:
-  [Summer of Code workflow](https://publiclab.org/wiki/gsoc#How+we+work)
-  [Extra notes on our approach](https://opensource.googleblog.com/2016/12/google-summer-of-code-2016-wrap-up_21.html)
-  [Different ways to mentor](https://publiclab.org/notes/warren/11-08-2016/help-public-lab-s-software-grow-by-joining-a-supportive-team) -- we need various types!
-  [Outreachy Mentor guide](https://www.outreachy.org/mentor/#mentor)
-  [What reviewers do day-to-day on Public Lab code projects](https://publiclab.org/wiki/developers#Reviewers)
-  [Our commitment to modularity](https://publiclab.org/notes/warren/01-18-2018/software-outreach-modularity-is-great-for-collaboration), *very important in how we ask contributors to work*
- Check out our growing list of [software outreach strategies](https://publiclab.org/software-outreach)

cc: @publiclab/mentors @publiclab/reviewers 

Many thanks and appreciation to mentors of the past year 
:star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: 
 @RuthNjeri @jywarren @pydevsg  @divyabaid16  @noi5e  @SidharthBansal  @gautamig54  @TildaDares  @Tlazypanda @coderjolly  @namangupta01  @keshavsethi @grvsachdeva 
:star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: 
 

We are happy to answer questions, please leave a comment below if any!

**Comment by debck** [comment]
Hi All, I would love to be a mentor this time and help with the projects, :tada:
Thanks 💯

**Comment by Manasa2850** [comment]
Hello everyone, 
I would like to be a GSoC / Outreachy mentor this time! Thank you :smiley:

**Comment by jywarren** [comment]
Thanks all, we SO appreciate the support!!!

**Comment by pydevsg** [comment]
Hello all,
Hope everyone is doing good.
I would love to continue mentoring students in GSoC this year as well :)

**Comment by cesswairimu** [comment]
Thanks @Manasa2850 @debck  and @pydevsg  and everyone planning to mentor :tada: :tada: 
The discussion issue for this year's project has been opened [here](https://github.com/publiclab/plots2/issues/10754) thanks @TildaDares  :heart:

**Comment by cesswairimu** [comment]
Closing this, thanks all

**Comment by pydevsg** [comment]
Hey I did filled the form maybe you missed it somehow.
I have filled it and am interested in mentoring folks this year as well.
Thanks
