### ISSUE TITLE
Profile's  followers/following  improvements

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#10730]
This a follow up to  https://github.com/publiclab/plots2/issues/10695 . Which added these links for followers and following links like so
![Screenshot from 2022-02-18 13-42-25](https://user-images.githubusercontent.com/17081074/154667960-8b1eeee0-fce4-4f0a-922d-5a178e90aab3.png)

on this page https://stable.publiclab.org/profile/liz

some improvements suggested here are: 
-  Deactivate the link to the followers/following page if zero. 
- The pagination is odd on the page followers/following page.  Maybe remove the pagination if less than 10?

**Comment by cesswairimu** [comment]
Hi @kirti1211c, feel free to claim this if interested. Thanks

**Comment by shubhangi013** [comment]
I'd like to work on this issue!

**Comment by cesswairimu** [comment]
Hello @shubhangi013, we would love your help!
Please go ahead. Thanks

**Comment by shubhangi013** [comment]
> Hello @shubhangi013, we would love your help!
> Please go ahead. Thanks

Yeah.. trying to set plots2 on my local system but I'm facing some errors. They're being discussed in the Gitter.

**Comment by cesswairimu** [comment]
Cool :+1: left a comment, please let us know if it helps or any further errors you face, thanks

**Comment by shubhangi013** [comment]
I've successfully set up the project and can now work on this issue. Thanks for guidance

**Comment by TildaDares** [comment]
@Forchapeatl if you’re interested the last item on the enhancements list has not been completed

> The pagination is odd on the page followers/following page. Maybe remove the pagination if less than 10?

**Comment by KarishmaVanwari** [comment]
Hey @TildaDares, can I work on this issue?

**Comment by KarishmaVanwari** [comment]
@TildaDares @cesswairimu I've opened a PR to fix the odd pagination issue at #10806. Please have a look. Thanks!
