### ISSUE TITLE
Weekly Community Check-In #131 - Health

### ISSUE THREAD

**Issue by RaviAnand111** [publiclab/plots2#10734]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Health

We programmers, coders, software engineers are required to work while sitting on our chair the whole time, this sedentary lifestyle is not good for health. So we need to take extra steps to be healthy. So this week lets talk about our physical and mental health which is as important as being successful in life. 

I want everyone to share what they do daily to stay healthy and in shape or if planning what are you planning to do to stay healthy?

### Thank you note

Many thanks to the contributors of the past weeks 🏅 🏅 🏅 [@KarishmaVanwari](https://github.com/KarishmaVanwari), [@TildaDares](https://github.com/TildaDares), [@Georjane](https://github.com/Georjane), [@NARUDESIGNS](https://github.com/NARUDESIGNS), [@elliefoote](https://github.com/elliefoote)

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by RaviAnand111** [comment]
I myself go on run every morning and try to do exercise after that, but as now colleges are open it is hard to do that. I like to do meditation and read books to exercise my mind. I also go for walk in the evening sometimes, usually I get lazy and skip it 😝 . 

Can you guys please share your stories too if possible ?
@TildaDares @jywarren @cesswairimu 

Thank You

**Comment by TildaDares** [comment]
Thank you for this wonderful check-in topic @RaviAnand111. I like to read books or listen to music and if I'm feeling really good, I take walks. I also got a bicycle recently so I ride when I have the chance.

**Comment by mittal-parth** [comment]
Very true @RaviAnand111!
I dance for keeping myself fit as it exercises the entire body! 🕺🏼 I meditate so as to maintain my mental health; *try* to take breaks and walk a little to avoid long durations of sitting; do some exercises for the eyes because we tend to abuse them a lot 😓

**Comment by sakshi-2412** [comment]
Such a nice topic @RaviAnand111✨ I do meditation or listen to music to keep my mind fresh. More than anything else, I am a bit concerned about my eyes, so I have started doing eye exercises recently just as @mittal-parth said. Don't want to have specs🤷‍♀️

**Comment by jywarren** [comment]
Thank you for this check-in and for this excellent topic. I love hearing how you all tend to your health! I usually bicycle but not in the ❄️ ❄️ ❄️  so i am feeling the need to do more to move my body these days. I also practice meditation and want to make more regular time for it! I often listen to ["singing bowl" audio recordings](https://soundcloud.com/massageasmr/tibetan-singing-bowl-studio-session-2-deep-sleep-meditation) and do simple breathing exercises.

**Comment by cesswairimu** [comment]
Thanks again @RaviAnand111 for the check-in. Great theme :heart: 

I do simple small stretch and full body exercises from chloe ting's channel, I also journal,  read fiction and history materials.
I also love dancing alone in the house :smile:

**Comment by cesswairimu** [comment]
Would anyone like to open next week's check-in?

**Comment by sakshi-2412** [comment]
Hey @cesswairimu I would love to open this week's check-in

**Comment by cesswairimu** [comment]
Awesome,🎉🎉 thanks @sakshi-2412
