### ISSUE TITLE
Images on /wiki are not center aligned

### ISSUE THREAD

**Issue by mittal-parth** [publiclab/plots2#10755]
### Please describe the problem (or idea)
After the recent change in the look of the `/wiki` page via #10731, the images in the _Image_ column are not center aligned. 

![image](https://user-images.githubusercontent.com/76661350/156764957-572fce90-4eba-44dc-98b7-f812a90cec91.png)

The relevant code can can be found in [this file](https://github.com/publiclab/plots2/blob/main/app/views/wiki/_wikis.html.erb)

### Please show us where to look

https://publiclab.org/wiki

### Browser, version, and operating system
Browser: Chrome
Version 98.0.4758.102
OS: Ubuntu 20.04.3 LTS via WSL 2 on Windows 11

****

**Comment by AbihaFatima** [comment]
@TildaDares I would like to work on this. Thanks!

**Comment by TildaDares** [comment]
Go ahead @AbihaFatima
