### ISSUE TITLE
Make the little `v` button a little larger on question page 

### ISSUE THREAD

**Issue by KarishmaVanwari** [publiclab/plots2#10757]
### 💡Format this Issue Into a First Timers Issue
This has been marked as a good candidate for becoming a [first-timers-only issue](https://code.publiclab.org/#r=all) like these, meaning that it's **simple, self-contained**, and with some extra formatting✍️, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider **reformatting it as a first-timers-only issue**, and then ping @publiclab/reviewers to get it labelled🏷. Or, if this is not your first time, **try to solve it yourself**🧑‍💻!

****

### 🤔 What you will need to know.

Make the little `v` button a little larger on a question page like [this one](https://publiclab.org/questions/Softconcept_Africa/09-29-2016/question-put-some-dustduino-in-africa) which is visible on lower screen sizes (mobile, tab).
The relevant code can be found [here](https://github.com/publiclab/plots2/blob/4d31f1d8e4e821d9f148142a50e6e0c105fe174f/app/views/sidebar/_question.html.erb#L5).

https://user-images.githubusercontent.com/78212650/155412993-b4feca44-a594-428a-8029-4cacadef3879.mp4

**Comment by AbihaFatima** [comment]
Hello👋, I was wondering if I could work on this issue if it hasn't been been reserved for anybody else. Thanks! :)

**Comment by TildaDares** [comment]
Sure @AbihaFatima

**Comment by mehul89** [comment]
hello @TildaDares I was like to work on this issue pls assigned me
this is my first contribution

**Comment by TildaDares** [comment]
Hi @mehul89, someone is already working on it. I can see you’ve left your name in the first-timers list so as soon there’s an issue for you I’ll ping you.

**Comment by Nishmaxcoder** [comment]
Hello @TildaDares 
I was wondering if I could work on this issue if it hasn't been reserved for anybody else. Thanks! :)

**Comment by TildaDares** [comment]
Hi @Nishmaxcoder, this issue has been reserved. You can leave a comment in #10153 and we’ll assign you to an issue when one is available.

**Comment by mehul89** [comment]
> <img alt="@Nishmaxcoder" width="40" height="40" src="https://avatars.githubusercontent.com/u/101393352?s=88&amp;v=4">

so mam tell me  what can I do now

**Comment by mehul89** [comment]
> Hello @TildaDares I was wondering if I could work on this issue if it hasn't been reserved for anybody else. Thanks! :)

so pls tell me what can I do now
