### ISSUE TITLE
Sign up modal goes down

### ISSUE THREAD

**Issue by janvi01** [publiclab/plots2#10759]
### Please describe the problem (or idea)
Sign up modal goes down for screen size (width ~ 350 - 600)

https://user-images.githubusercontent.com/34344234/156975889-75ecb340-8afd-4bff-a93c-20af4c0d19cd.mov

### Please show us where to look

https://publiclab.org
dropdown -> sign up option

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by Forchapeatl** [comment]
I would love to work on this issue

**Comment by janvi01** [comment]
Hey, @TildaDares if you can assign this to @Forchapeatl.
Thanks!

**Comment by TildaDares** [comment]
Hi @Forchapeatl, sure go ahead.
