### ISSUE TITLE
Weekly Community Check-In #133 - Congratulations Outreachy Interns Winter 2021 :tada: :tada: 

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#10764]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## :confetti_ball: Congratulations Outreachy Interns Winter 2021  :confetti_ball:  
 Congratulations @Georjane and @NARUDESIGNS :raised_hands: :raised_hands: and many many thanks for your amazing work. If you would like to share any links of your work or the program feel free to leave a comment below or on chat :100: :100: 
If you would like to see Jane's proposal its [here](https://publiclab.org/notes/pzgeorjane/11-02-2021/outreachy-proposal-rebuilding-spectral-workbench-capture-and-analysis-interface) and Paul's can be found [here](https://publiclab.org/notes/NaruDesigns/11-05-2021/outreachy-proposal-refine-the-public-lab-rich-editor)
And their projects breakdown are [here](https://github.com/publiclab/spectral-workbench/issues/801) and [here](https://github.com/publiclab/PublicLab.Editor/issues/760) respectively. 

All the best as you wrap up your projects :tada: :tada: 

### Summer of Code preparations
We are participating in Outreachy and GSoC programs this coming summer. The [*call for Summer of Code mentors is still ongoing :-  more details here*](https://github.com/publiclab/plots2/issues/10728). The discussion of [*the summer projects is also ongoing here*](https://github.com/publiclab/plots2/issues/10754). We appreciate all the folks who have offered to mentor and we are welcoming anyone else who is interested in mentoring to check the two out. Thanks

#### How you can help as a contributor.

- Please be welcoming to aspirants who will be reaching out in the coming weeks.
-  If you create an issue or encounter an issue that could be left out for a first-timer kindly consider leaving it  for a new contributor and labeling it as `fto-candidate` _or you could ping me to label it if you cannot_
- Help add more information or update outdated info on `fto-candidate` issues,  on any of our projects.

### Thank you notes: 

Many thanks to the contributors for the past few weeks
🥇🥇🥇🥇 [@adi611](https://github.com/adi611), [@janvi01](https://github.com/janvi01), [@mittal-parth](https://github.com/mittal-parth), [@elliefoote](https://github.com/elliefoote), [@Mik-27](https://github.com/Mik-27), [@Alvinkariuki](https://github.com/Alvinkariuki), [@kirti1211c](https://github.com/kirti1211c), [@lokcito](https://github.com/lokcito)🥇🥇🥇🥇 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time :)

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by NARUDESIGNS** [comment]
Thank you!
Big thanks to @jywarren @TildaDares for your support and lessons and time. I appreciate you.
Thanks to @Georjane and @RaviAnand111 as well

I still plan to be a contributor to PublicLab and I'd try to keep at it.
I'm glad PublicLab was a major part of my Outreachy experience!

**Comment by Georjane** [comment]
Thank you very much @cesswairimu 🥳 
I appreciate my incredible mentors @jywarren @TildaDares @Tlazypanda for all the support and patience ❤️ 
This is just the beginning of my coding journey with PublicLab

**Comment by jywarren** [comment]
Thank you @Georjane @NARUDESIGNS so much, we are so happy you chose to work with us! And thanks to my co-mentors @Tlazypanda @TildaDares @cesswairimu !!!

**Comment by cesswairimu** [comment]
Hi all, lets keep this for another week. Thanks all

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/mapknitter/issues/1615. Thanks all
