### ISSUE TITLE
Follow and New Post buttons are stacked on each other when there's a lot of text

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#10772]
On the user's profile page, the `New Post` and `Follow` buttons are stacked on top of each other when there's a lot of text. It would be nice if the buttons could go below the text when there's an overflow.

<img width="659" alt="Screenshot 2022-03-10 at 09 39 53" src="https://user-images.githubusercontent.com/63427719/157621888-865fb5d3-1ac3-49f6-aaf4-6ba5c9b07e04.png">

You can see this demonstrated in 
https://publiclab.org/profile/mathildaudufo

Relevant code is in:
https://github.com/publiclab/plots2/blob/cc104ae472ddbb18aa94cc7f0ade0fa455c23cff/app/views/tag/_topicCard.html.erb#L44-L56

**Comment by Varshini-k-02** [comment]
Hi @TildaDares, Can I work on this issue? I have my name tagged in this list in #10153, so am I eligible to solve this?

**Comment by TildaDares** [comment]
Hi @Varshini-k-02, go ahead. Thanks!

**Comment by Varshini-k-02** [comment]
Hi @TildaDares. Actually I need help with erb file. I'm having trouble in making changes in the actual file while I can make changes when I inspect the card in the browser. Basically how can I make changes in the actual erb file? Please help out with some resources. I'm new to Ruby on rails.

**Comment by TildaDares** [comment]
@Varshini-k-02 If you want to a new class, you can just add in the style tag here:
https://github.com/publiclab/plots2/blob/cc104ae472ddbb18aa94cc7f0ade0fa455c23cff/app/views/tag/_topicCard.html.erb#L63-L73

If you want to change the styling of the container div, you'll find it here:
https://github.com/publiclab/plots2/blob/cc104ae472ddbb18aa94cc7f0ade0fa455c23cff/app/views/tag/_topicCard.html.erb#L38-L57

Classes are added to elements like normal HTML elements.

I hope that helps.

**Comment by Ash-KODES** [comment]
Can I work on it?
@TildaDares

**Comment by TildaDares** [comment]
Sure @Ash-KODES, go ahead!

**Comment by TildaDares** [comment]
Hi @Ash-KODES, any updates on this? Feel free to ask for help if you need it.

**Comment by divyangana009** [comment]
Hi, @TildaDares  Can I work on it? Complete newbie(Outreachy applicant)

**Comment by TildaDares** [comment]
Hi @divyangana009, I’m waiting on @Ash-KODES reply but in the meantime you can leave a comment in #10153 and we’ll ping you when there’s an issue available. Thanks!

**Comment by Ash-KODES** [comment]
@divyangana009 please go ahead:)
actually I am little busy...apologies

**Comment by divyangana009** [comment]
@TildaDares  ok! Thanks ma'am

**Comment by Prachi-22-81** [comment]
Hi @TildaDares, Can I work on this issue?

**Comment by SAKSHI993** [comment]
Hi @TildaDares Can I work on it? (outreachy applicant and first issue)

**Comment by VictoriaAjala** [comment]
Hello @TildaDares , It seems no one is working on this, I would love to solve this issue?

**Comment by VictoriaAjala** [comment]
Hello @TildaDares I'm having issues setting up this project on my PC.

I keep getting the errors in the images below anytime I run `Run rake db:setup`

![image](https://user-images.githubusercontent.com/102407780/174617863-cbd7d9e4-e76e-4fc1-84bb-46c806c6c381.png)

![image](https://user-images.githubusercontent.com/102407780/174617941-4fb56a2c-8ba3-4159-be66-f27c7fc3ab62.png)

![image](https://user-images.githubusercontent.com/102407780/174618008-8970703b-ae8a-4395-b7eb-7f7e9080e4d3.png)

**Comment by gunesnt** [comment]
Hi @TildaDares, can I work on this issue?

**Comment by VictoriaAjala** [comment]
Thank you @TildaDares I'd setup sqlite3 instead.

**Comment by gunesnt** [comment]
> Hi @gunesnt, @VictoriaAjala is currently working on this. If you're interested, you could work on #11101.

thank you, I am looking at issue  #11101.

**Comment by VictoriaAjala** [comment]
![image](https://user-images.githubusercontent.com/102407780/175110481-e8a85f00-12a9-4fd6-8c92-7def6677bd78.png)

I get `unable to connect to github` whenever I run: `rails webpacker:install && rails webpacker:install:react && rails generate react:install`

**Comment by TildaDares** [comment]
Closed in #11260
