### ISSUE TITLE
User social media links deletion is hard to find

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#10773]
A contributor is unable to delete or remove their social media links from their profile after it has been added. You can only reset to an empty profile/link but the icons will still be displayed on the profile page. An improvement/solution would be to add cancel icons to each social media icon so that profile users can unlink their social media.

<img width="1201" alt="Screenshot 2022-03-10 at 09 48 37" src="https://user-images.githubusercontent.com/63427719/157625124-6a3ba49f-678d-4d32-9256-5484be4d9c00.png">

UPDATE: You can delete the social media links be deleting from the list of user tags but it's not really easy for a first-timer to figure out on their own.

<img width="194" alt="Screenshot 2022-03-10 at 11 50 07" src="https://user-images.githubusercontent.com/63427719/157646692-f6de96ed-4841-415a-a07c-27b40c598b63.png">

**Comment by Forchapeatl** [comment]
Please May I work on this Issue ?

**Comment by TildaDares** [comment]
Hi @Forchapeatl, sure you work on this.

**Comment by TildaDares** [comment]
This task involves:

- [ ] Add the cancel icon to the social media icons (the cancel button should only be shown to admins/moderators and the profile users.
https://github.com/publiclab/plots2/blob/cc104ae472ddbb18aa94cc7f0ade0fa455c23cff/app/views/users/profile.html.erb#L100-L121

- [ ] Delete the user_tag by doing something like this with the cancel icon
https://github.com/publiclab/plots2/blob/cc104ae472ddbb18aa94cc7f0ade0fa455c23cff/app/views/tag/_tags.html.erb#L44

The final UI look should look like this:
<img width="225" alt="Screenshot 2022-03-10 at 11 52 29" src="https://user-images.githubusercontent.com/63427719/157647119-5f1a41b8-51c5-4f5b-9d52-fa539b700660.png">

**Comment by TildaDares** [comment]
The tasks look like a lot so if you need assistance, please feel free to reach out.

**Comment by Forchapeatl** [comment]
Okay, thank you

**Comment by Forchapeatl** [comment]
@TildaDares , please I need some help.   I followed the instructions on the [https://github.com/publiclab/plots2/#installation](https://github.com/publiclab/plots2/#installation) at the final stage of running the server I my terminal has been on this stagefor a while , Please is this the required display ? Because localhost:3000 doesn't  respond .
![image](https://user-images.githubusercontent.com/24577149/158000654-353ab43e-e506-4fd7-8cc8-71be4768aa9f.png)

**Comment by TildaDares** [comment]
Have you tried restarting the server?

**Comment by Forchapeatl** [comment]
> Have you tried restarting the server?

I restarted and it works fine now. Thank you

**Comment by Forchapeatl** [comment]
> 



> This task involves:
> 
> * [ ]  Add the cancel icon to the social media icons (the cancel button should only be shown to admins/moderators and the profile users.
>   https://github.com/publiclab/plots2/blob/cc104ae472ddbb18aa94cc7f0ade0fa455c23cff/app/views/users/profile.html.erb#L100-L121
> * [ ]  Delete the user_tag by doing something like this with the cancel icon
>   https://github.com/publiclab/plots2/blob/cc104ae472ddbb18aa94cc7f0ade0fa455c23cff/app/views/tag/_tags.html.erb#L44
> 
> The final UI look should look like this: <img alt="Screenshot 2022-03-10 at 11 52 29" width="225" src="https://user-images.githubusercontent.com/63427719/157647119-5f1a41b8-51c5-4f5b-9d52-fa539b700660.png">

Please for your review on this UI below. 
![image](https://user-images.githubusercontent.com/24577149/158052177-469e25fa-c5e7-416c-a1ac-b6d7bf516616.png)
The Problem is the delete bage doen't make the delete request properly as  I don't know how to extract the tag value. I have highlighted the in the image above
my code 
` <a href="/profile/tags/delete/3?name=<%=tag.name%>"><span style=" color: white; position: absolute; display: block; " class="badge badge-primary mb-1">x</span></a>`

the `<%=tag.name%>` of my code returns an empty value.  Please how may I call the tag name?

**Comment by TildaDares** [comment]
@Forchapeatl The first thing you should is to change the `social_link` method here to `get_last_value_of_power_tag`
https://github.com/publiclab/plots2/blob/cc104ae472ddbb18aa94cc7f0ade0fa455c23cff/app/controllers/users_controller.rb#L167-L170 and change the variables to something like `@twitter_username`

**Comment by TildaDares** [comment]
Then in your view file, all you need to do is add
`<a href="/profile/tags/delete/3?name=<%= @twitter_username %>"><span style=" color: white; position: absolute; display: block; " class="badge badge-primary mb-1">x</span></a>`

**Comment by Forchapeatl** [comment]
Noted, Thank you.

**Comment by Forchapeatl** [comment]
Someone please help me I can't get the value of `user.id`
![image](https://user-images.githubusercontent.com/24577149/158180707-27ccb96f-e8e7-4092-9cc4-21601af52d33.png)

**Comment by Forchapeatl** [comment]
> Use @profile_user.id

Noted, thank you

**Comment by Forchapeatl** [comment]
The front end works fine 
Problem is The "delete method" is not functioning as expected please have a look at the deployed demo [http://194.163.138.111/profile/user](http://194.163.138.111/profile/user)
 Please this is the fontend code snippet
`      <% if @twitter.nil? == false %>
      <span>
       <a aria-label="Delete tag" data-confirm="Are you sure you want to delete it?" class="tag-delete" data-remote="true" href="/profile/tags/delete/<%= @profile_user.id %>?name=<%= @twitter_user %>" data-method="delete"><span style=" color: white; position: absolute; display: block; " class="badge badge-primary mb-1">x</span></a>         
        <a href="<%= @twitter %>" >
          <i class="fa fa-twitter fa-3x" ></i>
        </a>
</span>         
      <% end %>
`

**Comment by Forchapeatl** [comment]
> The front end works fine Problem is The "delete method" is not functioning as expected please have a look at the deployed demo http://194.163.138.111/profile/user Please this is the fontend code snippet ` <% if @twitter.nil? == false %> <span> <a aria-label="Delete tag" data-confirm="Are you sure you want to delete it?" class="tag-delete" data-remote="true" href="/profile/tags/delete/<%= @profile_user.id %>?name=<%= @twitter_user %>" data-method="delete"><span style=" color: white; position: absolute; display: block; " class="badge badge-primary mb-1">x</span></a> <a href="<%= @twitter %>" > <i class="fa fa-twitter fa-3x" ></i> </a> </span> <% end %>`

@TildaDares  Please  help me , Please have a look at the demo this demo  [http://194.163.138.111/profile/user](http://194.163.138.111/profile/user).The tag delete controller is not responding, The tag seems to reapear after deleting.

**Comment by Forchapeatl** [comment]
@TildaDares  Noted thank you

> @Forchapeatl I think you need to prefix the site name with username. Something like this `twitter:username`

**Comment by Forchapeatl** [comment]
How may I refresh  div without reloading the webpage. 
Tag is deleted succefully but the social icon disappears only after the entire page is reloaded. 

https://user-images.githubusercontent.com/24577149/158548807-a92833c5-7735-4d92-8e24-719b5d4a27fa.mp4

**Comment by TildaDares** [comment]
Hi @Forchapeatl, can you open a PR and then we'll go from there?

**Comment by Forchapeatl** [comment]
> Hi @Forchapeatl, can you open a PR and then we'll go from there?
Okay

**Comment by Forchapeatl** [comment]
@TildaDares I'm sorry it took so long to open the PR . I was trying to record my screen to make the PR more comprehensive. But my screen recorder had some malfuctions. I'm sorry it took so long.

**Comment by TildaDares** [comment]
A good follow-up would be to show the cancel button only to logged in users, admins/moderators and profile users. You could even create an FTO for it.
> * (the cancel button should only be shown to admins/moderators and the profile users.

All you have to do is insert the code for the cancel button in an if statement:

```
<% if logged_in_as(['admin', 'moderator']) || (current_user && current_user.uid == @profile_user.uid) %>
<!-- Code for cancel button -->
<% end %>
```

**Comment by Forchapeatl** [comment]
> A good follow-up would be to show the cancel button only to logged in users, admins/moderators and profile users. You could even create an FTO for it.
> 
> > * (the cancel button should only be shown to admins/moderators and the profile users.
> 
> All you have to do is insert the code for the cancel button in an if statement:
> 
> ```
> <% if logged_in_as(['admin', 'moderator']) || (current_user && current_user.uid == @profile_user.uid) %>
> 
> <% end %>
> ```

Thank you . For this wonderful idea.
