### ISSUE TITLE
Change User Unfollow Button to Neutral Color

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#10774]
The user `Follow` and `Unfollow` buttons have the same color and this can be confusing for contributors. 

<img width="324" alt="Screenshot 2022-03-10 at 09 59 57" src="https://user-images.githubusercontent.com/63427719/157627069-850f0a9a-5ed1-4a6d-b069-163e895acafb.png">

A grey color like this would show the difference between the two buttons.

<img width="125" alt="Screenshot 2022-03-10 at 10 01 40" src="https://user-images.githubusercontent.com/63427719/157627401-429bfeb8-a350-4361-b3d4-89801c20f3d2.png">

Relevant code for this is in:
https://github.com/publiclab/plots2/blob/cc104ae472ddbb18aa94cc7f0ade0fa455c23cff/app/views/users/profile.html.erb#L127-L131

**Comment by garimavs** [comment]
I would like to work on this @TildaDares. Thank you!

**Comment by TildaDares** [comment]
Go ahead @garimavs

**Comment by garimavs** [comment]
Hello @TildaDares, I'm facing some installation issues. I have mentioned the same in our Gitter community, will it be possible for someone from the organization to have a look at it?

**Comment by garimavs** [comment]
> Hello @TildaDares, I'm facing some installation issues. I have mentioned the same in our Gitter community, will it be possible for someone from the organization to have a look at it?

Kindly ignore the mentioned comment, but can you help me with the screenshot, because I'm unable to get to that page.
