### ISSUE TITLE
change store link to view on compact displays

### ISSUE THREAD

**Issue by Nataliegurl** [publiclab/plots2#108]
Kit  and Outreach met today and together we thought a it might be helpful to have a standardized approach to connecting directly to the store from all our various site. i.e specrtalworkbench.org, infragram.org, and mapknitter. So, it is clear to  folks, maybe a button at the top that says buy a kit. I think this is helpful to direct traffic to the store, but want to emphasize that this doesn't mean eliminating other routes, such in text links, citations and other ways that provide individual personality and additional ways for folks to find their way to the store.

**Comment by jywarren** [comment]
Bumping this to @ebarry @steviepubliclab @BeckiC not sure Tony's github handle.

**Comment by tonypubliclab** [comment]
I think it makes sense to have a Store button on top level navigation. I don't think this is an issue of being too commercial. It's just a matter of basic usability and making it easy for people to find what they are looking for. And as a separate issue, we can make a point to include language and links on the store pages to inform people about the open hardware nature, including links to the DIY pages. We could eventually include PDFs of designs as free items in the store, or whatever we think best uses the store to both raise funds and fulfill the mission. But I think it's an important enough program, and a popular enough destination to get a direct link from the main menu. Just "store." not buy or kits or shop or anything like that.

**Comment by jywarren** [comment]
All designs already have to be published on the PL website in order to be open source, so we just need to be consistent about linking to the designs and design files. 

"Store" could probably fit in our new, shorter menu bar. @sdosemagen led that design effort, so i guess we should get her +1 too.

**Comment by jywarren** [comment]
So at this point, it sounds like there's a clear proposal to include "Store" as a top level link. I think you may now want to email all staff:

* asking specifically for +1s from Shannon, Becki, Liz, Stevie
* linking to this issue, and 
* suggesting a specific placement, like "left of Donate" for example

If it doesn't meet with objection, I can make the change within a day.

**Comment by tonypubliclab** [comment]
Done. And as far as specific placement, I'd say below, or to the right of Donate (depending on what device you are on!).
so: 
Projects/About/Get Involved/Data/Donate/Store
If we felt it would be better to reverse the positions to Store/Donate, I'd support that too.

**Comment by ebarry** [comment]
+1 Store listed on top level navigation

Now, are you ready for my suggestions on your page, http://store.publiclab.org/ ? ;)

**Comment by steviepubliclab** [comment]
I think it's ok, but I might lean slightly in favor of "kits" instead.

**Comment by tonypubliclab** [comment]
yeah, always open to suggestions!

On Tue, Sep 1, 2015 at 10:19 AM, Liz Barry <notifications@github.com> wrote:

> +1 Store listed on top level navigation
>
> Now, are you ready for my suggestions on your page,
> http://store.publiclab.org/ ? ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/publiclab/plots2/issues/108#issuecomment-136801499>.
>



-- 
Tony Chiotti
Public Labs Kits Program
http://store.publiclab.org
tony@publiclab.org

**Comment by tonypubliclab** [comment]
I'm a believer in the "give them the page they requested" philosophy, and since it takes them directly to store.publiclab.org with the Title "Public Lab Store" I think "Kits" or "Shop" etc would cause a bit of a "Baroo?" face.

With the future library project, it's possible we'd want to rebrand kits program in general away from calling it a store, but I'd want to implement it across the pages and urls to keep it consistent. I like the idea of building connections between the shopify pages and the wiki pages to point more to the DIY options.

For now, can we go wtih Store and make the link happen? Any objections?

**Comment by jywarren** [comment]
+1. Any thoughts on "a very clear and highly visible (front page) explanation of how the Kits Initiative is still a non-profit, and/or supports PL's non-profit programs"?

I can make this change today or tomorrow.

**Comment by tonypubliclab** [comment]
Different than the language currently on the Kits main page?

I mean, I might make it less dense as far as style goes, but that does
capture the idea.

"The Kits Initiative creates, assembles, and distributes kits from the open
research designs of the Public Lab community to foster and develop the
reach of open, accessible science, by placing tools in the hands of those
that need them. Revenue from the kits program directly supports the Public
Lab nonprofit."

My stab at an edit:
The Kits Initiative designs, builds and distributes kits based on the work
of the Public Lab community. We make research and learning tools available
by ordering parts in bulk and then assembling kits to sell at low cost. All
revenue from this program directly supports the work of the nonprofit
Public Lab.

Where would this go? I was just envisioning a one word link, but happy to
see reference to the program wherever.

On Thu, Sep 3, 2015 at 11:37 AM, Jeffrey Warren <notifications@github.com>
wrote:

> +1. Any thoughts on "a very clear and highly visible (front page)
> explanation of how the Kits Initiative is still a non-profit, and/or
> supports PL's non-profit programs"?
>
> I can make this change today or tomorrow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/publiclab/plots2/issues/108#issuecomment-137537508>.
>



-- 
Tony Chiotti
Public Labs Kits Program
http://store.publiclab.org
tony@publiclab.org

**Comment by steviepubliclab** [comment]
Nice Tony! I like it.

**Comment by jywarren** [comment]
I think that could go in the sidebar, or maybe preferably, there could be a shorter sentence like "[Supporting the Public Lab non-profit's programs](/wiki/kits) through the sale of open source kits." which is an oversimplification, but answers the immediate question of "why does a non-profit have a store" and/or catches people who simply assume that we are just a store. 

I'm adding this menu item now to the plots2 site.

**Comment by jywarren** [comment]
Change is ready to be merged and deployed - i'll wait til tomorrow to do so so people can see the pull request.

**Comment by jywarren** [comment]
There is a slight issue at some sizes, but I could modify this change to hide the link when the window gets that small. This does occur on iPads:

![screenshot 2015-09-03 at 4 37 21 pm](https://cloud.githubusercontent.com/assets/24359/9670370/28f6cf6e-525a-11e5-8018-3db6f34328aa.png)

**Comment by tonypubliclab** [comment]
looks great. Thanks Jeff!
t

On Thu, Sep 3, 2015 at 1:38 PM, Jeffrey Warren <notifications@github.com>
wrote:

> There is a slight issue at some sizes, but I could modify this change to
> hide the link when the window gets that small. This does occur on iPads:
>
> [image: screenshot 2015-09-03 at 4 37 21 pm]
> <https://cloud.githubusercontent.com/assets/24359/9670370/28f6cf6e-525a-11e5-8018-3db6f34328aa.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/publiclab/plots2/issues/108#issuecomment-137567949>.
>



-- 
Tony Chiotti
Public Labs Kits Program
http://store.publiclab.org
tony@publiclab.org

**Comment by jywarren** [comment]
OK, i adjusted it so it is hidden on smaller screens, including the iPad. I know this isn't ideal but until we make more space or come up with another solution, this is the easier fix:

![screenshot 2015-09-04 at 8 07 49 pm](https://cloud.githubusercontent.com/assets/24359/9697566/479d2070-535f-11e5-8a91-800dcc6c1b9a.png)

**Comment by jywarren** [comment]
Hi, @tonypubliclab -- this is now live; if you'd like, please change the title to "show store link in compact displays" and we'll do one more design revision to ensure this happens.

**Comment by tonypubliclab** [comment]
Thanks Jeff! Looks great.

**Comment by jywarren** [comment]
Thanks. Is this as urgent, or can we hold off for a few weeks?
