### ISSUE TITLE
"Show more" button on tables of notes not useful any more; adapt or remove

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#10817]
We have a button/link to "show more" after a certain number of entries in a table, as shown in pages like https://publiclab.org/embed/grid/question:infragram

<img width="725" alt="image" src="https://user-images.githubusercontent.com/24359/159573223-ac8b7b36-3f2f-4520-953d-70b42aa88c4d.png">

This is only after scrolling all the way to the bottom. But now that we have scrolling of this type, we don't need that link any more. It used to show more than 10 if you clicked it but now we just show them all.

We could either just remove it (and the javascript code that made it work) or we could remove the javascript, but make the link lead back to the main page for this table's content:

So for https://publiclab.org/embed/grid/question:infragram, that would be:

https://publiclab.org/tag/question:infragram

Then people can just go through the full paginated list. 

The code for this is in this section of the template for the table:

https://github.com/publiclab/plots2/blob/5a0cd7384055f62cdc009b527549761ebccd446b/app/views/grids/_notes.html.erb#L72-L109

****
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by adriancf-br** [comment]
May I work on this Issue?

**Comment by TildaDares** [comment]
Hi @stephaniequintana, I know you’re looking for another FTO to work on. This could be a good place to start.

**Comment by stephaniequintana** [comment]
@TildaDares THANK YOU! @jywarren has assigned one to me. After working on that one I will definitely come back here to see what I can do to help.

**Comment by Yavnikaa** [comment]
@TildaDares @jywarren can I take this up?

**Comment by TildaDares** [comment]
Hi @Yavnikaa, go ahead!

**Comment by Yavnikaa** [comment]
I think it's a better idea to altogether remove the button since there are pages like https://mapknitter.org/#3/19.13/-80.59/ , where we need to figure out where should we redirect the user to. So shall I proceed by removing this button and the associated javascript completely?

**Comment by TildaDares** [comment]
Hi @Yavnikaa, that sounds good. Go ahead!

**Comment by Yavnikaa** [comment]
I have made the PR. Could you please review it? @jywarren @TildaDares
