### ISSUE TITLE
"Notes" tab missing from question page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#10824]
Our topic pages have tabs for "notes" and "questions":

https://publiclab.org/tag/infragram

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/24359/159574042-7312b33e-8a79-4858-9271-b05a00dfddee.png">

When the questions tab is open, you can get back to notes with the notes tab:

https://publiclab.org/questions/tag/infragram

<img width="874" alt="image" src="https://user-images.githubusercontent.com/24359/159591155-a775c01e-8707-4c6f-9e75-1da11cfe4060.png">

However, questions are actually just notes tagged with a special tag, `question:TOPICNAME` -- for example, for topic infragram, above, the tag is `question:infragram`.

Unfortunately, there's a bug with the tab display where if you accidentally go to this address, you see no "notes" tab at all:

https://publiclab.org/tag/question:infragram

<img width="925" alt="image" src="https://user-images.githubusercontent.com/24359/159574026-63565584-4004-4d8a-bb1c-fe89402c1b69.png">
 
Shouldn't we just remove this conditional wrapping that first tab?

https://github.com/publiclab/plots2/blob/f9799801531bc03fb451760df7dfe1f95554e85b/app/views/tag/show/_nav_tabs.html.erb#L5-L15

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by pydevsg** [comment]
Nice catch @jywarren 😃 
I agree with the same, we should remove the conditional wrapping .

**Comment by TildaDares** [comment]
Hi @pydevsg, this issue doesn’t really follow the formatting that FTOs usually have. I think it would be best to leave it as an `fto-candidate` instead.

**Comment by ishikajn8126** [comment]
Hey @jywarren!
I would like to work on this!

**Comment by TildaDares** [comment]
Hi @ishikajn8126, please go ahead. If you need any assistance, feel free to reach out.

**Comment by ishikajn8126** [comment]
> Hi @ishikajn8126, please go ahead. If you need any assistance, feel free to reach out.

Sure, thanks.

**Comment by EECvision** [comment]
Hi @TildaDares, I am an outreachy applicant. Please can I work on this issue if it is still open?

**Comment by stephaniequintana** [comment]
Hi, @ishikajn8126 - I'm just dropping a quick line to see if you would like any help on this issue. If so,  @EECvision just commented that he would like to work on it, too. I can also help if you would like. Please feel free to reach out to either of us.

For me, the biggest hurdle was getting my environment setup. I see [here](https://github.com/publiclab/plots2/issues/10844#issuecomment-1080715213) that you may have the same problem I ran into. Please see [my reply](https://github.com/publiclab/plots2/issues/10844#issuecomment-1081581705) and reach out if that is the case.

Happy coding!

**Comment by jywarren** [comment]
@ishikajn8126 have you completed a first-timers-only issue already? If you have, perhaps you'd like to try reposting this issue as a first-timers-only issue for someone else? 

However, otherwise please go ahead and thanks everyone for offering support! 🎉

**Comment by ishikajn8126** [comment]
Hey @stephaniequintana @jywarren!! I'm facing some issue in my environment setup, I'm working on it, will open a PR as soon as I get it ready..

**Comment by Forchapeatl** [comment]
> Hey @stephaniequintana @jywarren!! I'm facing some issue in my environment setup, I'm working on it, will open a PR as soon as I get it ready..

@ishikajn8126 some screenshots of the issue would be helpful. Can you share the issue with us.

**Comment by ishikajn8126** [comment]
> > Hey @stephaniequintana @jywarren!! I'm facing some issue in my environment setup, I'm working on it, will open a PR as soon as I get it ready..
> 
> @ishikajn8126 some screenshots of the issue would be helpful. Can you share the issue with us.

Hey @Forchapeatl, [here](https://github.com/publiclab/plots2/issues/10844#issuecomment-1080715213) is the ss of the issue that I was facing...
I've got it resolved now!
Thanks a lot for concern!!
