### ISSUE TITLE
Legacy /map/ nodes on publiclab.org need updating

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#10830]
I ran into this old content type when speaking with one of the earliest contributors to Public Lab. Map content in URLs formatted like `/map/`

- They display, but can't be edited
- They have authors, but this is hardcoded and not linked to publiclab.org author profiles 
- They can be "liked" but the icon for liking is duplicated on the other side of the content, and only the "wrong" one works. 
- Tags can be added to them so that they show up in search results, but without tagging them The Google search does not search their title or body content 

#### More detail

Check out this gif where the "star" icon in the right sidebar does not work, while an unexpected star icon on the left does work: 
![liking-map-nodes](https://user-images.githubusercontent.com/161439/159762248-924aacaf-603c-46e3-a883-8aab74c49416.gif)

Seen on: https://publiclab.org/map/tlc-youth-center-nsambya-rd-kampala-uganda/2012-11-09

Ideally, their would only be one star icon, it would be in the right sidebar, and it would function. :)

**Comment by ebarry** [comment]
More on map nodes:
Here's what happens when i try to edit the content to update it to correct inaccuracies that the original author told me about. 

![editing-map notes](https://user-images.githubusercontent.com/161439/159763405-7511a871-7ac7-4216-a8f8-83560f31bf99.gif)

What i would change if i could : 
- add two authors 
- edit title for accuracy

**Comment by ebarry** [comment]
Crossposting a comment i left in the chat, /map/ type nodes aren't covered by the google search. 
If they do not have tags (and most don't as they pre-date our extensive use of taging), the Google search seems to not search their title or body content.

**Comment by Forchapeatl** [comment]
I would love to work on this issue, may I ?

**Comment by jywarren** [comment]
Hi all! This is part of our giant "Deprecate legacy systems" project, and we have a plan to port all of this type over to be notes, at https://github.com/publiclab/plots2/issues/4072, as a part of #956. 

I saw that Google searching on PublicLab.org does seem to work for me: https://publiclab.org/search/kamwokya shows:

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/24359/161789645-6bf39219-dd92-4de7-ad36-54313b5a0fb9.png">

https://publiclab.org/search?q=csikszentmihalyi also shows this page as a result, so it is searching the whole page -- Google search doesn't actually distinguish fields, it just searches all page text. 

@ebarry if you're not seeing this, can you show us what you see when you search? 

I'm closing this in favor of #4072 and will add more detail there - @Forchapeatl we would love your help with it!
