### ISSUE TITLE
Change translation key for distance_of_time_on_words

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#10850]
Hi everyone, we are having translation errors with our user profile page on publiclab.org. This issue and #10849 are meant to resolve part of the issue in #10765. There are a series of translation files that their translation keys that need to be changed. I would have created separate FTOs for them but the changes are the same and would seem repetitive. I'll list the files that need changes and the lines that need to be changed.

- [ar.yml](https://github.com/publiclab/plots2/blob/main/config/locales/ar.yml) (Line 64) - Reserved for @akanbifatimah https://github.com/publiclab/plots2/pull/10857
- [de.yml](https://github.com/publiclab/plots2/blob/main/config/locales/de.yml) (Line 65) - Reserved for @BRB3D https://github.com/publiclab/plots2/pull/10864
- [es.yml](https://github.com/publiclab/plots2/blob/main/config/locales/es.yml) (Line 64) - Reserved for @siddhi-244 https://github.com/publiclab/plots2/pull/10903
- [gr.yml](https://github.com/publiclab/plots2/blob/main/config/locales/gr.yml) (Line 65) - Reserved for @marshatiisa https://github.com/publiclab/plots2/pull/10929
- [hi-IN.yml](https://github.com/publiclab/plots2/blob/main/config/locales/hi-IN.yml) (Line 61) - Reserved for @barcha47 https://github.com/publiclab/plots2/pull/10852
- [it.yml](https://github.com/publiclab/plots2/blob/main/config/locales/it.yml) (Line 66) - Reserved for @Ms-Error https://github.com/publiclab/plots2/pull/10851
- [ko.yml](https://github.com/publiclab/plots2/blob/main/config/locales/ko.yml) (Line 64) - Reserved for @pranayrauni https://github.com/publiclab/plots2/pull/10856
- [pt-BR.yml](https://github.com/publiclab/plots2/blob/main/config/locales/pt-BR.yml) (Line 64) - Reserved for @kachifako https://github.com/publiclab/plots2/pull/10861
- [ru.yml](https://github.com/publiclab/plots2/blob/main/config/locales/ru.yml) (Line 64) - Reserved for @nuilewis https://github.com/publiclab/plots2/pull/10906
- [zh-CN.yml](https://github.com/publiclab/plots2/blob/main/config/locales/zh-CN.yml) (Line 64) - Reserved for @anushkachauhxn https://github.com/publiclab/plots2/pull/10858

Required Change:
```diff
-    distance_in_words:
+    time_ago_in_words:
```

**Comment by TildaDares** [comment]
We usually reserve issues for 24 hours but since I didn't mention this before, I'll still leave them assigned to you for another 24 hours. So if you haven't claimed the issue assigned to you, I'll have to reassign it. Thanks!

**Comment by BRB3D** [comment]
Hi thanks tilda, I’m working on it today.
Regards José Islas

Sent from my iPhone

On Mar 28, 2022, at 3:00 PM, Tilda Udufo ***@***.***> wrote:

﻿

We usually reserve issues for 24 hours but since I didn't mention this before, I'll still leave them assigned to you for another 24 hours. So if you haven't claimed the issue assigned to you, I'll have to reassign it. Thanks!

**Comment by TildaDares** [comment]
Hi @HilaryDev, @LontchiFrank, @divyangana009 are you interested in working on this?

**Comment by TildaDares** [comment]
Reassigning

**Comment by TildaDares** [comment]
Hi @smyww4, @BlueDragn, @arpit-maurya I have reserved issues for you.

**Comment by barcha47** [comment]
hey @TildaDares i have completed my this task, am i now eligble to apply for other issues? I am newbie therefore bit confused. thanks

**Comment by TildaDares** [comment]
Hi @barcha47, yes you are.

**Comment by TildaDares** [comment]
Reassigning

**Comment by TildaDares** [comment]
@nuilewis, @siddhi-244, @Albert-Debbarma there are issues reserved for you.

**Comment by siddhi-244** [comment]
> @nuilewis, @siddhi-244, @Albert-Debbarma there are issues reserved for you.

Will do it. Thanks

**Comment by nuilewis** [comment]
> @nuilewis, @siddhi-244, @Albert-Debbarma there are issues reserved for you.

Thank you @TildaDares , I'll get started right away.

**Comment by nuilewis** [comment]
Hello, I've done the changes to the file I was assigned to, I'm about to create a PR, and there are no conflicts, but I'm a bit confused on what issue number I'm supposed to use for my PR, can somebody please clarify me on this?

**Comment by TildaDares** [comment]
@nuilewis The issue number is the number at the top of this issue. It usually starts with a #

**Comment by nuilewis** [comment]
Okay, thank you. I got confused because I saw the same issue with a different issue number, but I was able to get the right one. I made a PR, please review my changes if it's okay.

**Comment by TildaDares** [comment]
Reassigning

**Comment by TildaDares** [comment]
Hi @Linjelium11, there's an issue reserved for you. Reserved for 24 hours.

**Comment by TildaDares** [comment]
Reserved for @marshatiisa for 24 hours!

**Comment by marshatiisa** [comment]
I have updated this in: e0c595d832d9c1c03c79f7e2e8a7aca187254e5d 
@TildaDares

**Comment by TildaDares** [comment]
Hi @marshatiisa, I don’t think you’ve created a PR.

**Comment by marshatiisa** [comment]
I have now created a PR. @TildaDares
