### ISSUE TITLE
obsolete configuration found in the rubocop style guide

### ISSUE THREAD

**Issue by kunmi02** [publiclab/plots2#10868]
### Please describe the problem (or idea)
 Rubocop commands does not work on the project which can lead to writing codes with an obsolete style guide.
running a `rubocop` commands leads to errors

> What happened just before the problem occurred? Or what problem could this idea solve?
 Runing `rubocop .` on the root folder throws an error complaining about obselete commands in the .rubocop_shopify_styleguide.ym` file, .rubocop.yml file and in rubocop_todo.yml.

> What did you expect to see that you didn't?

I expect the rubocop files for the styling guide to be updated.

### Please show us where to look
- .rubocop_shopify_styleguide.yml
-  .rubocop_todo.yml
-  .rubocop.yml
https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by kunmi02** [comment]
if issue is approved I will like to work on it

**Comment by TildaDares** [comment]
Hi @kunmi02, thanks for spotting this. We have a similar issue in #8646.
 
This will probably take some time to correct all of the incorrect commands. You're free to take this up.

**Comment by kunmi02** [comment]
@TildaDares I have a pr for this. mentioned you on the pr.  please respond
