### ISSUE TITLE
Enhance the Lock icon with tooltip support on /events page

### ISSUE THREAD

**Issue by AbihaFatima** [publiclab/plots2#10862]
Currently the locked icon on [events](https://publiclab.org/events) page doesn’t support tooltip while hovering over, like all other icons.

![plots2-events](https://user-images.githubusercontent.com/70844041/160466553-1c794168-b183-4336-b2eb-c46d27f172d5.png)

**Comment by AbihaFatima** [comment]
@TildaDares 
May I start working on this?

**Comment by TildaDares** [comment]
Hi @AbihaFatima, yeah go ahead. Thanks!

**Comment by AbihaFatima** [comment]
@TildaDares 
while running it on localhost (logged in as user) I can see the tooltip on the locked icon saying:
![capture-1](https://user-images.githubusercontent.com/70844041/160838170-64bb0528-8918-4263-85af-1c76e4ee26b8.png)
which is for the first timer posters and it redirects [here](https://publiclab.org/notes/tester/04-23-2016/new-moderation-system-for-first-time-posters). 
How do I test it for non-first-time posters?

**Comment by TildaDares** [comment]
@AbihaFatima You can do that by logging in as `admin`. The password is `password`.
