### ISSUE TITLE
Weekly Community Check-In #135 - Love Yourself ❤️

### ISSUE THREAD

**Issue by RaviAnand111** [publiclab/plots2#10871]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Love Yourself

We have to do a lot of things in life, and sometimes we might forget to care for ourselves. Being happy with ourselves is very important and it's a quality that radiates. I just wanted to remind everyone to take care of themselves. Then only then can we can love and care about others.

## Outreachy

Congratulations ✨ ✨ to all the Outreachy applicants whose initial applications have been accepted. Since we're in the Outreachy contribution stage, we've had a lot of applicants join the community. A lot of the applicants have really supported other applicants and answered questions that they have. Some have gone ahead to create FTOs for first-timers.

We are a community that values cooperation and mutual support very highly, so please try to be helpful and friendly to members of the community. So I want to ask the contributors how someone from the community has helped them recently. 

### Thank you note to focus issues contributors

Many thanks to all the folks who have been helping summer of code aspirants across all our channels

⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ 
Thanks so much [@jywarren](https://github.com/jywarren), [@sakshi-2412](https://github.com/sakshi-2412), [@BRB3D](https://github.com/BRB3D), [@KarishmaVanwari](https://github.com/KarishmaVanwari), [@Forchapeatl](https://github.com/Forchapeatl), [@dependabot[bot]](https://github.com/apps/dependabot), [@Sakshamgupta90](https://github.com/Sakshamgupta90), [@kachifako](https://github.com/kachifako), [@barcha47](https://github.com/barcha47), [@moazzammoriani](https://github.com/moazzammoriani), [@girija0707](https://github.com/girija0707), [@anushkachauhxn](https://github.com/anushkachauhxn), [@pranayrauni](https://github.com/pranayrauni), [@akanbifatimah](https://github.com/akanbifatimah), [@Ms-Error](https://github.com/Ms-Error), [@padmajabhol](https://github.com/padmajabhol), [@sarxxt](https://github.com/sarxxt), [@reeshi-18](https://github.com/reeshi-18), [@adriancf-br](https://github.com/adriancf-br), [@BeeBombshell](https://github.com/BeeBombshell), [@BhavyaT-135](https://github.com/BhavyaT-135)🥇
⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by RaviAnand111** [comment]
When I joined publiclab community, I didn't knew anything, but I learnt from git to making PRs and then helping others. Everything I learned in this community. Everyone I know in the community helped me one way or other, but I would like to name a few who replied to my wierd and silly questions despite being stuck, confused and facing problems themselves.
 
Thank You @NARUDESIGNS @TildaDares @cesswairimu @jywarren and all the members of the publiclab community for taking time from your schedule to help us beginners.

**Comment by akanbifatimah** [comment]
Thank you @RaviAnand111 , so glad to help.

**Comment by on2onyekachi** [comment]
Thank you @RaviAnand111. I do hope to learn from you.

**Comment by girija0707** [comment]
Thank you @RaviAnand111 , this is an amazing community happy to help and learn along the way ☺️

**Comment by mittal-parth** [comment]
Would just like to appreciate how the community has been very helpful and supportive with quick reviews and feedback from the start! ❤️

**Comment by PeculiarE** [comment]
Good points @RaviAnand111 about taking time to care for yourself. it's something I'm sometimes very careless about. Could be so focused on solving a problem to the detriment of my health and fitness. But I'm gradually learning to find a balance. Thanks for sharing ❤️ .

And it's nice and encouraging to see you paying the help forward by helping other contributors having issues in the chatroom. Much appreciated 😄 👍

**Comment by shefali12-ab** [comment]
@PeculiarE  I would like to open next check-in.

**Comment by RaviAnand111** [comment]
Great @shefali12-ab ❤️, go for it , You can ask @cesswairimu @TildaDares or even me for any doubts you have.

**Comment by shefali12-ab** [comment]
sure @RaviAnand111 . Thank you :)

**Comment by cesswairimu** [comment]
Hi all, a little late to ask but would anyone like to open this week's check-in?  I will open in the next few hrs if no one is up for it.
Thanks all

**Comment by RaviAnand111** [comment]
Hi @cesswairimu I think @shefali12-ab was going to do it. I am also happy to create one If no one is creating it.

**Comment by cesswairimu** [comment]
Hi @RaviAnand111  my bad, missed that, thanks :heart:. 
Hi @shefali12-ab, kindly feel free to open anytime today and do reach out in case of anything. We have a template we use [here](https://github.com/publiclab/plots2/issues/new?assignees=&labels=community+check-in&template=--weekly-check-in.md&title=Weekly+Community+Check-In+%23+-+Topic)  I was thinking we could do it on the Infragram project this week(_not required, you can open on plots2 too no prob_) Thanks

**Comment by shefali12-ab** [comment]
Hey @cesswairimu i will do it by today. Thank you :)

**Comment by shefali12-ab** [comment]
Hey @RaviAnand111 @cesswairimu  i have created a new check-in 
https://github.com/publiclab/plots2/issues/10948 do check it out and tell me the changes that I need to do in it if required.

**Comment by jywarren** [comment]
Hi @RaviAnand111 such a powerful message, I deeply appreciate it! Thank you and it's such a pleasure to see everyone joining in the community.

@shefali12-ab thank you, yours looks amazing! I will close this up and we'll move over there.
