### ISSUE TITLE
Remove Duplicate Code in Spam2

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#10897]
Hi everyone, I created an FTO in #10893 to keep the code for `batch select` DRY. This issue(s) will remove the duplicate code. I would have created FTOs for each one but the changes are similar so I decided to create one issue for it. These are the files that need changes:

- [app/views/spam2/_comments.html.erb](https://github.com/publiclab/plots2/blob/main/app/views/spam2/_comments.html.erb) Reserved for @falyne
- [app/views/spam2/_flags.html.erb](https://github.com/publiclab/plots2/blob/main/app/views/spam2/_flags.html.erb) - Reserved for @Tanushka11 https://github.com/publiclab/plots2/pull/10926
- [app/views/spam2/_nodes.html.erb](https://github.com/publiclab/plots2/blob/main/app/views/spam2/_nodes.html.erb) - Reserved for @rohaid-bakh https://github.com/publiclab/plots2/pull/10969
- [app/views/spam2/_queue.html.erb](https://github.com/publiclab/plots2/blob/main/app/views/spam2/_queue.html.erb) - Reserved for @AmenuveveDordor https://github.com/publiclab/plots2/pull/10902
- [app/views/spam2/_users.html.erb](https://github.com/publiclab/plots2/blob/main/app/views/spam2/_users.html.erb) - Reserved for @Morai-C https://github.com/publiclab/plots2/pull/10951 

Required Change:
```diff
@@ -2,11 +2,7 @@
        $("#all").click(function () { //select all button
-               $('.selectedId').prop('checked', !$('.selectedId').prop('checked'));
-               var check = ($('.selectedId').filter(":checked").length == $('.selectedId').length);
-               $('#select-count').text($('.selectedId').filter(":checked").length);
-               $('#selectall').prop("checked", check);
-               disable_buttons('#selectall');
+               select_all();
   });
   var pageselect_val = localStorage.getItem('page-select') || '';
   $("#pageselect").val(pageselect_val);
```

**Comment by Morai-C** [comment]
thanks for the issue.. on it

**Comment by Morai-C** [comment]
Hey @TildaDares, I've raised a PR https://github.com/publiclab/plots2/pull/10899  Please have a look. Thanks!

**Comment by P3lumi** [comment]
Thank you, I will get to it immediately

**Comment by AmenuveveDordor** [comment]
Hey @TildaDares thank you, I’ll start working on it immediately

**Comment by rohaid-bakh** [comment]
Thank you! I'll get started on it immediately.

**Comment by TildaDares** [comment]
Reassigning

**Comment by TildaDares** [comment]
Hi @RuthAtem, there's an issue reserved for you. It's reserved for 24 hours.

**Comment by TildaDares** [comment]
Reassigning!

**Comment by TildaDares** [comment]
Hi @Tanushka11, there's an issue reserved for you for 24 hours!

**Comment by Tanushka11** [comment]
Hii @TildaDares thank you, I will start working on it immediately.

**Comment by Tanushka11** [comment]
#10926

**Comment by Tanushka11** [comment]
Hey @TildaDares  Please Review #10926

**Comment by RuthAtem** [comment]
Hi @TildaDares Thanks for assigning me, Please can I still work on  it

**Comment by TildaDares** [comment]
Hi @RuthAtem, it has already been reassigned but I’ll put your name back on the list.

**Comment by RuthAtem** [comment]
Okay thank you

**Comment by YUVRAJ06singh08deora** [comment]
Hey @TildaDares I would also like to try out this issue

**Comment by TildaDares** [comment]
Thank you @YUVRAJ06singh08deora but all of the issues have been claimed.

**Comment by TildaDares** [comment]
Hi @P3lumi, do you need any help with this?

**Comment by falyne** [comment]
hi @TildaDares thanks for assigning this issue. i'm on it

**Comment by falyne** [comment]
Hi @TildaDares kindly review the PR i created thanks
