### ISSUE TITLE
SSL site blocks older youtube embeds

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/plots2#109]
I'm not seeing youtube embeds in older notes in either firefox or chrome:
![screen shot 2014-06-25 at 2 55 54 pm](https://cloud.githubusercontent.com/assets/1203280/3392353/84087392-fcb3-11e3-9c78-3bd4e8d4cc30.png)
two notes:
https://publiclab.org/notes/mathew/2-1-2013/american-kite-fishing-low-tech-kite-balloon-hybrid
and 
https://publiclab.org/notes/mathew/2-1-2013/how-pauls-fishing-kites-flys-wind

**Comment by jywarren** [comment]
Merging into #110.
