### ISSUE TITLE
Extra space in the author popover

### ISSUE THREAD

**Issue by RaviAnand111** [publiclab/plots2#10911]
### Please describe the problem (or idea)
There is too much space before the name of authors which makes the popover wierd looking.

### Please show us where to look
https://publiclab.org/events
![new_issue_publiclab](https://user-images.githubusercontent.com/59113935/161433924-b9eab9aa-94b5-4fc0-a902-1c4122c52dea.png)

****
Hey @TildaDares @jywarren @cesswairimu, Do you think it is intentional ? 
If it is not I am thinking of creating a FTO issue for it.

**Comment by TildaDares** [comment]
@RaviAnand111 You're right about the extra space. You can create an FTO.

**Comment by saikmusunuri** [comment]
Hey @TildaDares, can I please work on this issue?

**Comment by jywarren** [comment]
Hi @saikmusunuri if @RaviAnand111 or someone else creates a first-timers-only issue, we will add it to the queue in https://github.com/publiclab/plots2/issues/10153 - have you signed up for one there? Thank you!

****
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by jywarren** [comment]
The code for this element can be found here!

https://github.com/publiclab/plots2/blob/cf10caaefb78b631c15a54f44ec35e9a77d2bbdb/app/views/wiki/_header.html.erb#L35-L41

**Comment by TildaDares** [comment]
FTO opened in #10917
