### ISSUE TITLE
Extra right and bottom margin and unequal size of cards(people active on public lab).

### ISSUE THREAD

**Issue by shefali12-ab** [publiclab/plots2#10914]
### Please describe the problem (or idea)
 extra right and bottom margin at the place where map is present , also size of cards (people active on public lab)are not equal it can be improved so that UI looks good.
also one thing that can be done is ,placing the cards first and at the bottom of cards we can place map.

![Screenshot from 2022-04-04 08-56-04](https://user-images.githubusercontent.com/56781823/161469490-95b6b16b-e85c-4016-83fa-f9a00530fdb3.png)

### Please show us where to look

https://publiclab.org/people

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by shefali12-ab** [comment]
Hii, @TildaDares @cesswairimu i just encounter this issue. do let me know your views about this issue.

**Comment by TildaDares** [comment]
@shefali12-ab About the extra right margin, it's not the same on my screen
<img width="1280" alt="Screenshot 2022-04-04 at 09 34 56" src="https://user-images.githubusercontent.com/63427719/161505891-d72a8f95-c215-4c6d-886e-07e98a03d394.png">

Also, the reason why the cards aren't equal is that some users have tags on their cards and others don't. Some tag texts are also longer than others. Do you know of a way we can make the card size equal and still have the same content as we have now?

Public Lab has a lot of users so it might take a while for a user to see the map if you place it at the bottom.

**Comment by shefali12-ab** [comment]
okay @TildaDares i understand it, i will try if we can make the size of cards equal and will let you know. 
Moreover I have two more suggestions:-
1. The first time i have opened this public.org/people page i didn't understand what this map is about . so, we can add a little description about this map. under the map.
2.  We can create a issue that basically contains all the queries and their solution  that one can encounter while setting up the project. so that it will become easy to help new contributors by refering them to that particular issue just like check-in ideas.

**Comment by TildaDares** [comment]
@shefali12-ab There’s a text underneath the map that tells you why the map is there. Do you think that isn’t helpful enough or we could place it in a location that’s more visible?

> The first time i have opened this public.org/people page i didn't understand what this map is about . so, we can add a little description about this map. under the map.


We have a setup issue in #10844

> We can create a issue that basically contains all the queries and their solution that one can encounter while setting up the project. so that it will become easy to help new contributors by refering them to that particular issue just like check-in ideas.

**Comment by shefali12-ab** [comment]
@TildaDares yes we can make it more visible. also text present underneath the map is just asking about (sharing your own location on profile) so, can't it be more descriptive like why should people share there profile. or something about this map.

**Comment by TildaDares** [comment]
@shefali12-ab Actually the text is telling you why the map is there. This is the text:
`Current view based on your shared location. Click [here](https://publiclab.org/profile) to adjust.`

**Comment by Hydriah** [comment]
@TildaDares  i am thinking the differ in sizes is from its screen responsiveness

**Comment by shefali12-ab** [comment]
> Hi @shefali12-ab! Thanks for opening the issue! I think we can make the size of the cards equal by enforcing a fixed size for all the cards. This size would naturally be the maximum possible size which fits all the content. Moreover, since we have only 3 tags being shown at max, we can make each user's card something like this
> 
> <img alt="image" width="201" src="https://user-images.githubusercontent.com/76661350/161603761-d5bdae87-dfad-4562-9463-57580f622440.png">
> 
> (All tags appear one below the other, _regardless of the length of the tag_)
> 
> cc: @TildaDares

sure @mittal-parth we can do like this also. @TildaDares can we do it like this as parth has shown in above image.

**Comment by TildaDares** [comment]
If it’s fine with you I’d like to see a screenshot of what a profile without tags would like beside one with tags using a fixed width. I want to know if the profile would look empty when it doesn’t have tags.

**Comment by mittal-parth** [comment]
@shefali12-ab Would you like to try?

**Comment by shefali12-ab** [comment]
Hey @TildaDares @mittal-parth. Card without tags having fixed width looks like this 
![_ Public Lab_ List](https://user-images.githubusercontent.com/56781823/161965488-53a8ef90-ddce-47b3-bb75-31bb77c2141b.png)

**Comment by TildaDares** [comment]
Hi @shefali12-ab, this looks great but I'd like to see a card with tags and one without side by side.

**Comment by shefali12-ab** [comment]
sure @TildaDares I will share it ,here soon.

**Comment by shefali12-ab** [comment]
Hii @TildaDares see these two
1.
![_ Public Lab_ List (2)](https://user-images.githubusercontent.com/56781823/162045426-1946e47c-519a-4914-8a92-7a39ffb9b59a.png)
2.
![_ Public Lab_ List (1)](https://user-images.githubusercontent.com/56781823/162045451-18140095-1a98-4b97-80ee-5ea21ddf2be9.png)

**Comment by TildaDares** [comment]
@shefali12-ab I’m not sure about the width of the tags. They are too wide.

Also, you still haven’t shown how the page would look if we had cards with tags and cards without tags side by side.

**Comment by shefali12-ab** [comment]
@TildaDares see this one, I have placed cards with and without tags side by side also  changed the widths of tags. 
![_ Public Lab_ List (3)](https://user-images.githubusercontent.com/56781823/162051286-fdc2cac5-77cd-42de-acfa-8b3c99e155c1.png)
The cards without tags are looking empty, but they all have same size . what do you say about this ?

**Comment by TildaDares** [comment]
@shefali12-ab I agree with you, they look empty.

**Comment by shefali12-ab** [comment]
@TildaDares okay i will close this issue and look for other issues to work upon. Thank you so much  for discussion :)

**Comment by shefali12-ab** [comment]
@TildaDares I have founded some of more things that can be improved in https://publiclab.org/blog
1. There is  extra left margin at the place where youtube video is placed.
2. The font size are too small, it can be improved.
3. After clicking on the follow button it is not performing any action,
you can check these things and let me know so that FTO issues can be created from these.
Thank you!
![_ Public Lab_ Blog (1)](https://user-images.githubusercontent.com/56781823/162136664-466bdd10-b5fe-4935-9b99-042fa3229d7e.png)

**Comment by TildaDares** [comment]
@shefali12-ab You can go ahead to open issues for them.

**Comment by shefali12-ab** [comment]
sure @TildaDares I need to know that after clicking on Follow button what action it needs to perform, I will mention this in issue.
