### ISSUE TITLE
🎉 Welcome GSoC 2022 applicants and call for proposals 🎉 🙋‍♀️🙋🙋‍♂️

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#10915]
Hello :wave: and welcome to PublicLab :balloon: 
We are glad to have you here. We are participating in Google Summer of Code(GSoc) this summer. 
This is a discussion issue for all of you. If you would like to checkout our large community you can find us on [chat channels](https://publiclab.org/chat) and also we do weekly check-ins where folks say what they are working on and ask for help if blocked. You can find the link to the latest check-in here #9600 

### Projects
Idea list/ potential projects: https://publiclab.org/wiki/gsoc-ideas#2022+Ideas
Github discussion: https://github.com/publiclab/plots2/issues/10754

### DeadLine
 April 19,  18:00 UTC   is the contributor application deadline

Here are a few todos :

### Introduce yourself 
Please say hello in a comment below, so we get to know you(optional).

###  First contribution :man_technologist: :woman_technologist: 
We suggest you make a first contribution. We have issues with the first-timer-only label which are specifically tailored for a first time contributor. You can find them here https://code.publiclab.org/ along with the guidelines on how to start contributing. Please be sure to check if someone is already working on an issue before you take it up. Kindly leave a comment on the issue to let other people know you are working on an issue. If you can't find any issues that are available, please feel free to leave a comment below and we will find you one asap.

## Second issue
After you solve the first issue you can browse through our  "help-wanted" , "bug" or other non first-timer  issues and leave a comment on any you would like to work on. Feel free to ask if you need more context for you to solve an issue, the community is always ready to help.We also encourage contributors to hep each other where they can.

### Call for GSoC proposals

We request applicants to post their proposals on the PublicLab website too. Here are [2021 proposals](https://publiclab.org/notes/cess/03-24-2021/call-for-2021-gsoc-proposals) you could look at 

[Here](https://publiclab.org/notes/cess/04-11-2022/call-for-proposals-google-summer-of-code-2022) is a link to call of proposals to the PL website, which also has a template for drafting the template, sample proposals for past interns and helpful pointers while drafting the proposals.
 Kindly submit early and post a link on gitter so that contributors and mentors can give feedback and help you improve on your proposal.  

### Questions :thinking: 

 If you have any questions please leave a comment below and we will get back to you.

#### A few tips for making awesome proposals:
* Please [submit the proposals at publiclab.org]  first. After all the reviews you can submit it on the official website.
* Your information so that we can know you better (not mandatory !).
* Include weekly timeline: Explain what you will be doing in which week. Divide the period into months in bigger tasks. Then into weeks into smaller tasks.
* Include demos/images/gifs to demonstrate your idea
* Include Mock-Ups, Flow Charts, Data Flow Diagrams, etc to explain the workflow in simple language. So that people in the logistics department can review your work and suggest changes.
* PRs merged & Issues reported: This is the most crucial aspect of any application. We want people to be well versed with our system. Please mention all the issues reported, PR merged, suggestions etc in the proposal.
* Start early and have many revisions of the proposal to increase your chances.

These tips are general tips.
Are you tensed? overwhelmed?  No need to worry!!! : We all are there to help you at each stage of the way. Feel free to reach out in case of anything.

**Comment by samiali12** [comment]
Hello,

**Comment by keshavgbpecdelhi** [comment]
Hi, I am Keshav, new to publiclab, a potential GSOC applicant. I found publiclab an awesome community, Happy to be the part of this amazing supportive environment. I will give my fullest. 🐱‍🏍🧡

**Comment by Sakshamgupta90** [comment]
Hi @cesswairimu, since there are two project sizes, it's our choice which project size we should consider? or do we have to consider for 350hr only?
2.)And If suppose I choose 175 hr project size, then is it our choice that, what we can do during that timeline according to a project? 
3.) which is good?175 hr or 350hr.
Thank you!

**Comment by Tanish2000** [comment]
Hi, I am Tanish, a potential GSoC applicant. I am looking for an FTO issue. Please help to get one.

**Comment by cesswairimu** [comment]
Hi @Sakshamgupta90, Jeff replied to this question best [here](https://github.com/publiclab/plots2/issues/10754#issuecomment-1082331256). Please let us know if you have any further questions. Thanks

**Comment by cesswairimu** [comment]
Hi @Tanish2000,  I have reserved  this one [here](https://github.com/publiclab/plots2/issues/10937)  for you. Thanks

**Comment by siddhi-244** [comment]
Hiii, this is Siddhi Bhanushali.  Where do we have to submit the proposal for review (before the final submission) and is there any structure?

**Comment by Forchapeatl** [comment]
> Hiii, this is Siddhi Bhanushali. Where do we have to submit the proposal for review (before the final submission) and is there any structure?

Please checkout this reply [https://github.com/publiclab/plots2/issues/10754#issuecomment-1082331256](https://github.com/publiclab/plots2/issues/10754#issuecomment-1082331256)

**Comment by cesswairimu** [comment]
Hi all, [Here is the call for proposals](https://publiclab.org/notes/cess/04-11-2022/call-for-proposals-google-summer-of-code-2022) feel free to post  the linkhere once you have posted. Thanks all

**Comment by cesswairimu** [comment]
hi @siddhi-244 [here](https://publiclab.org/notes/cess/04-11-2022/call-for-proposals-google-summer-of-code-2022)

**Comment by Forchapeatl** [comment]
> Hi @Forchapeatl , I saw you proposal, I will check it out by latest tomorrow, thanks

thank you

**Comment by void-ness** [comment]
Hello Community Members! Lakshya This side. I am a sophomore currently pursuing undergraduates in Computer Sciences. I am inspired by the motive behind public lab. The idea of helping in some way to reduce pollution excites me. I am versed with Web Development and has expertise in JavaScript and React. I love spending hours with HTML and CSS by side. 

I am still exploring the community. I had a small doubt, I was checking your community on Gitter. I wanted to ask are their subchannels in Gitter for specific discussions or only 1 general channel is present for all type of discussions. I am trying to learn things and better equip myself. Looking forward to contribute 😄

**Comment by cesswairimu** [comment]
Hi @void-ness and welcome :tada: It is the one channel for the gitter channel for now. We are open to discussing a creation of  a channel for gsoc applicants in future if that would be a better way to interact.. what do you think? I would like to hear what other applicants think too . Thanks all

**Comment by anantraghuvanshi** [comment]
Hey there, @TildaDares @cesswairimu @jywarren Kindly review my proposal. The link is attached [here](https://docs.google.com/document/d/1OQ-Ds3NZM-5yYlVXnM7lDp8d4mQbKhiLn3CftYXnhBY/edit).

Thanks!!

**Comment by mittal-parth** [comment]
Hi @jywarren, @cesswairimu and @TildaDares!! Please find my proposal [here](https://publiclab.org/notes/mittalparth22/04-12-2022/gsoc-2022-proposal-refine-user-interfaces-across-publiclab-org) for the project idea _Refine User Interfaces across PublicLab.org_. I would highly appreciate any feedback on the same!

Thank you!

**Comment by void-ness** [comment]
> Hi @void-ness and welcome 🎉 It is the one channel for the gitter channel for now. We are open to discussing a creation of a channel for gsoc applicants in future if that would be a better way to interact.. what do you think? I would like to hear what other applicants think too . Thanks all

I personally believe that can be a wonderful option that can be explored in future for dealing with naive and lost GSOC applicants like me :) However the community is so helpful I never felt alone. Thank you for being so helpful with my queries on gitter as well as on github 😊

**Comment by keshavgbpecdelhi** [comment]
Hi @jywarren, I want to be gsoc contributor for public lab for [Refine User Interfaces across PublicLab.org](https://publiclab.org/wiki/gsoc-ideas#Refine+User+Interfaces+across+PublicLab.org). I am unable to understand this statement `Brainstorm better interlinked navigation between https://publiclab.org/wiki pages <> https://store.publiclab.org/ <> individual tag pages (like https://publiclab.org/tag/water-quality).`. What linking are we talking about ? 

I have seen the [Store](https://store.publiclab.org) is accessible from [Wiki](https://publiclab.org/wiki), while tags are not. Is that means we have to access Tags through Wiki and Store though navbar button or is there something which I misunderstood. Please Clarify.

Thankyou.

**Comment by TildaDares** [comment]
Hi @keshavgbpecdelhi, this comment might help https://github.com/publiclab/plots2/issues/10754#issuecomment-1068086159

**Comment by fetian-debug** [comment]
Hello, I am Fetian, a potential GSoC applicant. I am looking for an FTO issue. Please help to get one.

**Comment by Forchapeatl** [comment]
> Hello, I am Fetian, a potential GSoC applicant. I am looking for an FTO issue. Please help to get one.

[here](https://github.com/publiclab/plots2/issues/11061) is an FTO for you
