### ISSUE TITLE
Weekly Community Check-In #136 - Kindness Always Wins 

### ISSUE THREAD

**Issue by shefali12-ab** [publiclab/plots2#10948]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Kindness always wins

This is a quote by Selena Gomez, a famous pop singer, this quote always has my heart and I believe that if more humans are kind to others then it's a blessing to humanity.
If you are reading this I just wanna say, at any point in your life if you got a chance to help people in any way help them because you will never know what it brings to a person who was really in need.
During my open source journey, I have met many peoples who have helped me in my learnings and I remember a project named Git internals to which I have contributed, that uses asscidoctor for documentation. I was not familiar with it, but the mentors of that project guided me whenever I needed help and it took me one month to create PR for that project but the learning and feeling of appreciation that I got from there, have always pushed me to contribute  in opensource projects and continue my journey.

### Thank you note to focus issues contributors

Thanks so much @cesswairimu @RaviAnand111 @mittal-parth @jywarren @sakshi-2412 @Tlazypanda @noi5e @unnati914 @Manasa2850 @17sushmita @Georjane @waridrox for your past contributions.

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by akanbifatimah** [comment]
@shefali12-ab , I totally agree with you," if more humans are kind to others then it's a blessing to humanity". Kindness always wins. 
Thank you @shefali12-ab for this.
@cesswairimu @RaviAnand111 @mittal-parth @jywarren @sakshi-2412 @Tlazypanda @noi5e @unnati914 @Manasa2850 @17sushmita @Georjane @waridrox thank you for your past contributions.

**Comment by jywarren** [comment]
Hi @shefali12-ab thank you so much for this check-in and your message! We're grateful for your kindness! 

If folks would like to share things they worked on this week, either things you feel good about or got stuck on or whatever, please feel welcome to share here each week!

I took 3 whole days off 😲  this weekend to rest after one of the busiest months i remember recently. It felt so great, and I'm grateful to return to see you all thriving! A wonderful way to return.

**Comment by AbihaFatima** [comment]
Couldn't have agreed more 💯@shefali12-ab! One act of kindness ingnites another. Being kind, practicing gratitude, and showing compassion are not only good traits, they are essential to manifesting a better world for all of us. Thankful to all the contributors of this community!🥂

**Comment by illyShelly** [comment]
Hi Shefali, @shefali12-ab very nice words. I am happy I can be part of this community 💯 . It is good escape from bad news coming these days. 
Okay, fun facts and a bit sweat 😅: My first ever PR onto Open Source Project (here) I ended up with  diverged local and remote branch. Meaning, they differed by a few commits and didn't flow the right way. So the learning here: think about it before you do some stuff directly in GitHub and run git commands in your terminal (merge, pull, fetch...) 😄 
My goal: 
- I would like to do a more challenging issue in this or mapknitter repo. 
- As well as I like to suggest/prepare some ideas related to UI especially cards. To make the card's layout of each part separate <div> and make the font more relevant to the size of the card? As well as some fixed max number of chars for each title <a>. 
Do you think @jywarren could be this work part of contribution period or should I take it as part of the proposal for the internship? Thank you.

<img width="1022" alt="Screenshot 2022-04-06 at 12 09 29" src="https://user-images.githubusercontent.com/26350915/161952112-2e31ecff-3e41-4806-bd3c-9a92adf5bee8.png">

**Comment by on2onyekachi** [comment]
Hi @shefali12-ab Thank you for this piece!. As humans, what do we live for, if not to make life less difficult for others.  Kindness is truly the nature of humanity. 

Just as @jywarren said, I had a whole lot of rest also during the weekend which was so great! And it surly helps being productive during the week.

**Comment by mittal-parth** [comment]
Well said @shefali12-ab! 
Apart from making the world a better place, it also gives a great sense of satisfaction after having helped someone selflessly. I think it also one of the core values of Open Source! 🎉

**Comment by shefali12-ab** [comment]
> @shefali12-ab , I totally agree with you," if more humans are kind to others then it's a blessing to humanity". Kindness always wins. Thank you @shefali12-ab for this. @cesswairimu @RaviAnand111 @mittal-parth @jywarren @sakshi-2412 @Tlazypanda @noi5e @unnati914 @Manasa2850 @17sushmita @Georjane @waridrox thank you for your past contributions.

Thanks to you too @jywarren, I really appreciate the people in the community for helping new members and answering each query.

**Comment by shefali12-ab** [comment]
> Hi @shefali12-ab thank you so much for this check-in and your message! We're grateful for your kindness!
> 
> If folks would like to share things they worked on this week, either things you feel good about or got stuck on or whatever, please feel welcome to share here each week!
> 
> I took 3 whole days off astonished this weekend to rest after one of the busiest months i remember recently. It felt so great, and I'm grateful to return to see you all thriving! A wonderful way to return.

that's great @jywarren after all we are humans and we all need a break from work :)

**Comment by shefali12-ab** [comment]
> Couldn't have agreed more 100@shefali12-ab! One act of kindness ingnites another. Being kind, practicing gratitude, and showing compassion are not only good traits, they are essential to manifesting a better world for all of us. Thankful to all the contributors of this community!clinking_glasses

Thank you :)) @AbihaFatima

**Comment by shefali12-ab** [comment]
> Hi Shefali, @shefali12-ab very nice words. I am happy I can be part of this community 100 . It is good escape from bad news coming these days. Okay, fun facts and a bit sweat sweat_smile:
> 
> * My first ever PR onto Open Source Project (here) I ended up with  diverged local and remote branch. Meaning, they differed by a few commits and didn't flow the right way. So the learning here: think about it before you do some stuff directly in GitHub and run git commands in your terminal (merge, pull, fetch...) smile
> * As well as I started translation .yml file into Czech, but I had to use google translator few times because I couldn't remember how to say some words in my own language  rofl
> 
> Enjoy coding partying_face
> 
> My goal:
> 
> * I would like to do a more challenging issue in this or mapknitter repo, especially ruby code/RoR related.
> * As well as I like to suggest/prepare some ideas related to UI especially cards. To make the card's layout of each part separate `<div>` and make the font more relevant to the size of the card? As well as some fixed max number of chars for each title `<a>`.
>   Do you think @jywarren could be this work part of contribution period or should I take it as part of the proposal for the internship? Thank you.
> 
> <img alt="Screenshot 2022-04-06 at 12 09 29" width="1022" src="https://user-images.githubusercontent.com/26350915/161952112-2e31ecff-3e41-4806-bd3c-9a92adf5bee8.png">

Thank you and Alll the best @illyShelly

**Comment by PeculiarE** [comment]
@shefali12-ab....thank you for your wise words.

I've spent the past week looking at the work already done on the project I am interested in; trying to understand the logic and implementation and familiarise myself with the codebase. And while it has been a bit challenging, I've been fortunate to receive helpful explanations from fellow contributors in the community and that really enforced your message on kindness.

I believe kindness is a cycle. The more you give it, the more others are encouraged to pay it forward ❤️

**Comment by shefali12-ab** [comment]
Thank you :)) and all the best @PeculiarE

**Comment by cesswairimu** [comment]
Hi all, thanks again @shefali12-ab for the check-in, great theme :tada, and thanks everyone for your kindness :heart: :heart: 

We have posted a call for Google Summer of Code proposals on the PublicLab website [here](https://publiclab.org/notes/cess/04-11-2022/call-for-proposals-google-summer-of-code-2022) 
I am catching up on a few things then I will post this week's check-in in the next few hours -  if anyone is up for it : _opening this week's check-in_ please leave a comment and go ahead_ Thanks all

**Comment by illyShelly** [comment]
@cesswairimu 😉 thank you very much. I'll check your suggestion!

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/infragram/issues/354. Thanks all
