### ISSUE TITLE
Bullet points are starting with small letters

### ISSUE THREAD

**Issue by RaviAnand111** [publiclab/plots2#10958]
### Please describe the problem (or idea)

I think the bullet points' first letter should be Capital, it makes it look good, indented and professional.

### Please show us where to look

https://publiclab.org/wiki/projects

![image](https://user-images.githubusercontent.com/59113935/161997740-280725b4-f019-4306-a3a3-df0b65c716e9.png)

Hey @TildaDares @jywarren @cesswairimu, what do you guys think, Can we create a FTO for this or leave it as it is for now ?

**Comment by TildaDares** [comment]
Hi @RaviAnand111, this page in the Public Lab site directly. It can only be edited in the PL site.

**Comment by RaviAnand111** [comment]
oh, ok, so there is no need of FTO for it. 
Then I should close this issue ?

**Comment by RaviAnand111** [comment]
Thank You @TildaDares ❤️
