### ISSUE TITLE
Change Tab indents of the script tag in insights.html.erb file to double-space indentations lines 66-75

### ISSUE THREAD

**Issue by akanbifatimah** [publiclab/plots2#10968]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Claim the issue by commenting. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
<details>
  <summary>💡 <i>Learn how to claim</i> 🙋</summary>
  <h3>Claiming an issue</h3>
  <p>Unless the issue is marked as reserved for someone, you can just say "I'd like to try this!" and then you've claimed it - no need to wait for someone to assign it to you. Just be sure you link your pull request (PR) to this issue so we can see where your solution is.</p>
  <p>And open one early if possible - even before you've completed it with additional commits - and others can help you figure out any issues you may face.</p>
</details>

- [ ] 📝 **Update** the file [_insights.html.erb](https://github.com/publiclab/plots2/blob/main/app/views/spam2/_insights.html.erb) in the `https://github.com/publiclab/plots2/blob/main/app/views/spam2/_insights.html.erb` repository (press the little pen Icon) and edit the line as shown below.

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$diff --git a/app/views/spam2/_insights.html.erb b/app/views/spam2/_insights.html.erb
index 71de6ff1..f45db781 100644
--- a/app/views/spam2/_insights.html.erb
+++ b/app/views/spam2/_insights.html.erb
@@ -63,16 +63,16 @@
 <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
 <script>
 var options = {
-       chart: {
-               type: "line",
-               height: 300,
-               foreColor: "#999",
-               scroller: {
-                       enabled: true,
-                       track: {
-                               height: 7,
-                               background: '#e0e0e0'
-                       },
+  chart: {
+    type: "line",
+    height: 300,
+    foreColor: "#999",
+    scroller: {
+      enabled: true,
+      track: {
+        height: 7,
+        background: '#e0e0e0'
+      },
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below, and [reach out in our chatroom](https://publiclab.org/chat)!

**Comment by TildaDares** [comment]
@akanbifatimah This looks good but the JavaScript is the one that needs changing.

**Comment by akanbifatimah** [comment]
> @akanbifatimah This looks good but the JavaScript is the one that needs changing.

Thank you for calling my attention to that @TildaDares , I will close this FTO and raise another one with changes in just the JavaScript part , should I go ahead?

**Comment by akanbifatimah** [comment]
Hi @TildaDares , I have updated the changes in the Javascript Part, Kindly Review.Thank you

**Comment by TildaDares** [comment]
@akanbifatimah Some of the code is more than two spaces deep.

**Comment by akanbifatimah** [comment]
> @akanbifatimah Some of the code is more than two spaces deep.

ok, I will check and effect the necessary changes, thank you.

**Comment by akanbifatimah** [comment]
Hi @TildaDares , I figured out rendering all of those changes on the file might not be easy for a first timer, I resulted to breaking it down so its easy for a first Timer to understand and figured out it would help in creating more FTO's for others who might have not been assigned one yet, is this ok?

**Comment by TildaDares** [comment]
Hi @akanbifatimah, this looks really great. I’m a bit worried about git conflicts though.

**Comment by akanbifatimah** [comment]
I totally understand @TildaDares ,I will try my best to make it easier for a biginner while effecting all the changes.

**Comment by TildaDares** [comment]
On second thought @akanbifatimah I think it might be better for you to open a PR for this issue since it involves a lot of changes. That's if you're interested.

**Comment by akanbifatimah** [comment]
I will do that..thank you for the suggestion @TildaDares

**Comment by akanbifatimah** [comment]
Hi @TildaDares , I have opened a PR for this issue at #11020
