### ISSUE TITLE
Increase the text fontsize.

### ISSUE THREAD

**Issue by shefali12-ab** [publiclab/plots2#10978]
### 💡Format this Issue Into a First Timers Issue
This has been marked as a good candidate for becoming a [first-timers-only issue](https://code.publiclab.org/#r=all) like these, meaning that it's **simple, self-contained**, and with some extra formatting✍️, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider **reformatting it as a first-timers-only issue**, and then ping @publiclab/reviewers to get it labelled🏷. Or, if this is not your first time, **try to solve it yourself**🧑‍💻!

****

Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Claim the issue by commenting. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
<details>
  <summary>💡 <i>Learn how to claim</i> 🙋</summary>
  <h3>Claiming an issue</h3>
  <p>Unless the issue is marked as reserved for someone, you can just say "I'd like to try this!" and then you've claimed it - no need to wait for someone to assign it to you. Just be sure you link your pull request (PR) to this issue so we can see where your solution is.</p>
  <p>And open one early if possible - even before you've completed it with additional commits - and others can help you figure out any issues you may face.</p>
</details>

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below.

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

At the https://publiclab.org/blog page fontsize of texts present are too small, that can be increased according to UI of this page.

![_ Public Lab_ Blog (2)](https://user-images.githubusercontent.com/56781823/162266735-24150983-3498-49d0-86bc-788fefe4b0cf.png)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below, and [reach out in our chatroom](https://publiclab.org/chat)!

**Comment by TildaDares** [comment]
Hi @shefali12-ab, do you intend to work on this?

**Comment by shefali12-ab** [comment]
@TildaDares sure I can work on it.

**Comment by TildaDares** [comment]
@shefali12-ab We can use the font-size of a normal note like this https://publiclab.org/notes/cess/04-04-2022/call-for-proposals-outreachy-summer-2022

**Comment by shefali12-ab** [comment]
okay @TildaDares 
here in the link given, the following font size, weight and style are used
```
 font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";
font-size: 1rem;
font-weight: 400
```
and at the blog page also the same font size, weight, and style are used, but here on the blog page the font size is looking too small, so can I increase it ?, or apply some changes, I will let you know if it looks better than before.

**Comment by TildaDares** [comment]
@shefali12-ab Actually the font-size for the blog is `15px`
https://github.com/publiclab/plots2/blob/9eb56bc4113c1f823d1b3c6cc1910554dc08c5fb/app/assets/stylesheets/blog.css#L48-L50

**Comment by TildaDares** [comment]
@shefali12-ab I think the reason why the font-size is that small is because the page is meant to be a kind of preview to the actual blog content.

**Comment by shefali12-ab** [comment]
okay, @TildaDares so, do I need to increase the font size or not. 
one more thing I have encountered while running the project locally, right now I am facing a problem in opening my Ubuntu OS, I will share that issue as soon as I will get back to my ubuntu OS.
Thank you

**Comment by TildaDares** [comment]
@shefali12-ab I don't think we need to increase the font size anymore.

**Comment by shefali12-ab** [comment]
Hii @TildaDares @jywarren see this screen recording,
https://www.awesomescreenshot.com/video/8322334?key=d3569c1bea44369804e2aa55527e7331
When i have opened this bolg page locally using gitpod , I have found that some of the contents like youtube video iframe and the paragraphs are missing from there. Also that follow button is clickable.
But at  https://publiclab.org/blog link mentioned in publiclab repositry, the follow button is not clickable, also youtube iframe and paragraphs contents are present there.
I just want to know is this happening with me only, when i am running this project locally. or is it actually a issue.

**Comment by shefali12-ab** [comment]
> @shefali12-ab I don't think we need to increase the font size anymore.

sure i will close this issue.

**Comment by TildaDares** [comment]
@shefali12-ab The contents of the blog are user generated. So a user can decide whether or not they want to include a YouTube iframe or a paragraph. If you want to work on the iframe, all you have to do is create a post and then add the `blog` tag.

**Comment by TildaDares** [comment]
I’m not sure about the follow button though.

**Comment by shefali12-ab** [comment]
sure @TildaDares , I can create a blog but on which topic, do i need to create a blog, i didn't have any idea about it. 
I thought that it was a issue that need to be fixed when i was going through the blog page.

**Comment by shefali12-ab** [comment]
Hey @TildaDares I'm waiting for your reply, also I have sucessfully completed my FTO issue, Now i am looking for some more challenging issue, I have serched for issue with tag Help wanted, but didn't get any. please guide me with this.

**Comment by TildaDares** [comment]
@shefali12-ab What is the question again?

> Hey @TildaDares I'm waiting for your reply

**Comment by shefali12-ab** [comment]
@TildaDares I need to know that for blog page to fix the issue of iframe, i need to create a post. please suggest me some topics so that i could create a post.
I have sloved the FTO issue now  am looking for some challenging issue,  please guide me and help me with this.

**Comment by TildaDares** [comment]
@shefali12-ab If you want to create a blog post on your local env, all you have to do is navigate to `https://localhost:3000/post` and fill in the necessary form inputs. After doing that, make sure you add the tag `blog` to it and then press publish.

**Comment by shefali12-ab** [comment]
okay sure @TildaDares I will let you know before publishing it. Thank You

**Comment by shubhi-arora** [comment]
Hi @TildaDares if this issue is still open then please assign me this!
