### ISSUE TITLE
Fix left margin on blog page

### ISSUE THREAD

**Issue by shefali12-ab** [publiclab/plots2#10977]
### 💡Format this Issue Into a First Timers Issue
This has been marked as a good candidate for becoming a [first-timers-only issue](https://code.publiclab.org/#r=all) like these, meaning that it's **simple, self-contained**, and with some extra formatting✍️, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider **reformatting it as a first-timers-only issue**, and then ping @publiclab/reviewers to get it labelled🏷. Or, if this is not your first time, **try to solve it yourself**🧑‍💻!

****

Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Claim the issue by commenting. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
<details>
  <summary>💡 <i>Learn how to claim</i> 🙋</summary>
  <h3>Claiming an issue</h3>
  <p>Unless the issue is marked as reserved for someone, you can just say "I'd like to try this!" and then you've claimed it - no need to wait for someone to assign it to you. Just be sure you link your pull request (PR) to this issue so we can see where your solution is.</p>
  <p>And open one early if possible - even before you've completed it with additional commits - and others can help you figure out any issues you may face.</p>
</details>

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below.

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

There is a more left margin on https://publiclab.org/blog due to which youtube video iframe was shifted to right.
It can be fixed by giving proper margin.
![🎈-Public-Lab-Blog (1)](https://user-images.githubusercontent.com/56781823/162263709-be4b0351-aca5-4ceb-8e5b-d1d55d79a9bb.png)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below, and [reach out in our chatroom](https://publiclab.org/chat)!

**Comment by TildaDares** [comment]
Hi @shefali12-ab, do you intend to work on this yourself?

**Comment by shefali12-ab** [comment]
Hii @TildaDares yeah sure I can work on it or if you want to assign it to a new member I am okay with that too.

**Comment by TildaDares** [comment]
FTOs have a specific format. If you want someone else to work on this as a first-timers only issue, it needs to look like this https://github.com/publiclab/plots2/issues/10959. We only use this template for FTOs.

**Comment by TildaDares** [comment]
Also, it’s a bit tricky to adjust the size of a YouTube Iframe so I’m not sure this can be considered an FTO-candidate.

**Comment by shefali12-ab** [comment]
Sure @TildaDares I can work on it. Thank you :)

**Comment by shubhi-arora** [comment]
Hi @TildaDares please assign me this issue. I am an outreachy applicant.

**Comment by ebarry** [comment]
Hi there, 
I'm wondering if this is in fact a Left margin issue, i have some doubt about the diagnosis of the unexpected appearance showing at the top of the blog. . 
When scrolling through the blog, i see that it is intentionally designed with wide left and wide right margins. 
Can you also scroll down through the blog to take a look for yourself? 

This unexpected appearance seems to be caused by a video embed that is overflowing the right margin. 
Please take a look.

**Comment by ebarry** [comment]
i think it's related to https://github.com/publiclab/plots2/issues/11073
