### ISSUE TITLE
Improve User Experience for questions part

### ISSUE THREAD

**Issue by illyShelly** [publiclab/plots2#10983]
Hi 👋 
I have a suggestion to change the PublicLab.org page on the alert part with questions and `Follow this topic` button.
1. Wouldn't be nice to make **space between text and the follow-up button**? (viz. example pic)
2. What about to have **nickname capitalise** to emphasise the person?
3. There is small 'typo' **one more empty character** before 'nickname' - ease to change as some FTO. 
4. I would have also question related to **size of the question** (font-size) - in comparison with rest of the text, what about to make it smaller. Let's say 28-30px or better to use `<h2>` tag.
The space between `Question:` and text of the question I already created FTO waiting for your confirmation.

Thanks for your opinion 🙂 

The code to the actual webpage is here:
[Link to click:](https://publiclab.org/questions/laurel_mire/09-20-2021/what-can-you-do-about-oil-in-your-ditch-following-a-natural-disaster-when-traditional-resources-normal-pathways-are-not-available)

**The current state:**

<img width="888" alt="Screenshot 2022-04-08 at 11 43 23" src="https://user-images.githubusercontent.com/26350915/162411525-04d257b7-4c0c-4e73-8c9b-2c50b9aaf08f.png">

**Please describe the desired behavior.**
Describe the solution you'd like.
- Add separate div's and use flexbox properties for CSS.

**Additional context (optional)**
Feel free to include any applicable: code, screenshots, or gifs.

**Possible change 1 (just alert part):**

<img width="811" alt="Screenshot 2022-04-07 at 23 39 49" src="https://user-images.githubusercontent.com/26350915/162326197-03e5ab85-cdea-4946-beef-fc86bc4150b4.png">

**Possibly change 2 ( with smaller font-size as well):**

<img width="738" alt="Screenshot 2022-04-08 at 00 03 03" src="https://user-images.githubusercontent.com/26350915/162327446-0b8dbf75-bb00-459a-8bb6-01dfe745d88b.png">

**Comment by illyShelly** [comment]
@jywarren @TildaDares I'd like to ask you for your opinion 👍 Thank you.

**Comment by TildaDares** [comment]
@illyShelly The images you added are before pics right?

**Comment by illyShelly** [comment]
@TildaDares Hi, sorry for the confusion. Actually, the pics are the version how they could look like if we make any changes. So, when you open the link (above) it looks like this at the moment (fresh printscreen bellow):

<img width="1161" alt="Screenshot 2022-04-08 at 11 46 14" src="https://user-images.githubusercontent.com/26350915/162410990-716e292f-80a2-41f4-98a2-ec7ca2277424.png">

**Comment by TildaDares** [comment]
I really like this. I think we could also do without the colon.
> 1. Wouldn't be nice to make **space between text and the follow-up button**? (viz. example pic)

I'm not so sure about this. I think it's best to leave the username as it is so that there's no confusion and we can maintain consistency.
> 2\. What about to have **nickname capitalise** to emphasise the person?

Go for it!
> 3\. There is small 'typo' **one more empty character** before 'nickname' - ease to change as some FTO.

You're right, the heading will look better with a smaller font-size. Maybe we could use 2rem since the current one is 2.75rem.
> 4\. I would have also question related to **size of the question** (font-size) - in comparison with rest of the text, what about to make it smaller. Let's say 28-30px or better to use `<h2>` tag.

**Comment by illyShelly** [comment]
@TildaDares Ok, thank you very much for your input 😉 I'll start to work on it and make some FTO 👩‍💻 👨‍💻 for others.
