### ISSUE TITLE
auto-generate "new activity" and "new upgrade" buttons for activity grids

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1098]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

Our great [new activity grids](https://publiclab.org/notes/liz/08-30-2016/check-out-these-activity-grids) display lists of activities based on tag name, and are often accompanied by buttons that say `Add an activity` and `Request an activity`. These are currently manually added, for example on this page:

https://publiclab.org/wiki/kite-making

Along with a helpful notice below, using this mix of HTML and markdown:

```
## Activities

[activities:kite-making]

<a href="/post?tags=activity:kite-making,kite-making,seeks:replications&title=How%20to%20do%20X" class="btn btn-primary">Add an activity</a> <a href="/post?tags=question:kite-making,request:activity&template=question&title=How%20do%20I...&redirect=question" class="btn btn-primary">Request an activity guide</a>

_Guides should include a materials list and a step-by-step construction guide with photo documentation. Learn what [makes a good activity here](https://publiclab.org/notes/warren/09-17-2016/what-makes-a-good-activity)._
```

(screenshot would be helpful here)

That's long and we could automate it by adding a new line to the template generator in this file, just after this line:

https://github.com/publiclab/plots2/blob/master/app/helpers/application_helper.rb#L55

It could just be the HTML from above, so, substituting in the `tagname`:

```ruby
      output += '<a href="/post?tags=activity:#{tagname},#{tagname},seeks:replications&title=How%20to%20do%20X" class="btn btn-primary add-activity">Add an activity</a> <a href="/post?tags=#{tagname},question:#{tagname},request:activity&template=question&title=How%20do%20I...&redirect=question" class="btn btn-primary request-activity">Request an activity guide</a>'
      output += '_Activities should include a materials list, costs and a step-by-step guide to construction with photos. Learn what [makes a good activity here](/notes/warren/09-17-2016/what-makes-a-good-activity)._'
```

**Comment by mridulnagpal** [comment]
@jywarren I'd like to give it a shot

**Comment by jywarren** [comment]
Once #1091 is complete, that'd be great, thanks!

**Comment by mridulnagpal** [comment]
@jywarren Where is the file with html redundant code because once we automate it we would have to delete it from there as well.

**Comment by jywarren** [comment]
It's actually in wiki page content, not in the codebase, and @ebarry has
agreed to chase it down and delete it once the new buttons are live. Thanks!
