### ISSUE TITLE
Correct code and add new class using flexbox property for better UI

### ISSUE THREAD

**Issue by illyShelly** [publiclab/plots2#11001]
### 💡Improved UI in question part of the page

- [ ] 📝 **Update** the file [$app/views/questions/show.html.erb](https://github.com/publiclab/plots2/blob/main/app/views/questions/show.html.erb#L28) in the `plots2` repository 

Link to the page on Publiclab.org [the web](https://publiclab.org/questions/laurel_mire/09-20-2021/what-can-you-do-about-oil-in-your-ditch-following-a-natural-disaster-when-traditional-resources-normal-pathways-are-not-available)

## What need to be changed:
Firstly, the code in the `show.html.erb` starting in the line **28** (as mentioned above)
- this will correct typo by deleting the **extra space** in front of generated nickname,
- 1 **extra sign** `:`,
- add 2 div tags `<div>` with a new classes to use `flexbox` to make visible change between text and the button "Follow this topic" `d-flex align-items-center justify-content-between`
- decrease size for `<h1>` and add `media query` for small devices
- correct indentation

## Printscreens:

**Current state on the page:**

<img width="772" alt="Screenshot 2022-04-09 at 00 12 28" src="https://user-images.githubusercontent.com/26350915/162541643-8912b076-bafe-4f5d-b252-94116e77b52c.png">

**After change:**

<img width="798" alt="Screenshot 2022-04-09 at 17 09 03" src="https://user-images.githubusercontent.com/26350915/162579895-e4c94458-7ef8-4fee-b856-7ae7baaee318.png">

### 🤔❓ Questions?

Leave a comment below, and [reach out in our chatroom](https://publiclab.org/chat)!

**Comment by TildaDares** [comment]
Thanks for working on this @illyShelly. It looks great.

Can you also move the `follow this topic` button to the end of the div as shown in your screenshot in this FTO? Thanks!

**Comment by illyShelly** [comment]
@TildaDares hi 🙂 sure I'll do it. Just messed up my local git when trying to be sure, it works 😄

**Comment by illyShelly** [comment]
@TildaDares Hi again :) Prepared as discussed in this issue [#10983](https://github.com/publiclab/plots2/issues/10983)
ℹ️ I just didn't add or change size of `h1`, because I suppose it's in general css style file `style.css`, which will affect **all h1 heading** tags. Am I right?
I think in general we should avoid to use in-style css to change directly some code. If we decide to change `<h1>` we can create another FTO. What do you think? 🙂

**Comment by TildaDares** [comment]
@illyShelly You can use Bootstrap to add the styles. The classes to add will be `d-flex align-items-center justify-content-center`.
> In `app/assets/stylesheets/questions.css` write these few lines to add a new class to actually see the change (space between text and the button) :
> 
> <img alt="Screenshot 2022-04-09 at 16 47 42" width="325" src="https://user-images.githubusercontent.com/26350915/162579185-f8a98c53-4bcd-499b-a6c7-132964088fec.png">
> 
> *

**Comment by illyShelly** [comment]
@TildaDares , Okay I change it but it is `d-flex align-items-center justify-content-between` for making the space otherwise it's smashed together.

**Comment by TildaDares** [comment]
Okay @illyShelly

**Comment by illyShelly** [comment]
@TildaDares , thank you. I guess it's done 🙂 and much shorter now.

**Comment by illyShelly** [comment]
I one more thing sorry, the other FTO could be to `improve and sync indentation`. It's a bit unorganised.

**Comment by TildaDares** [comment]
@illyShelly I added a few styles to make it more responsive on smaller screens. What do you think?

https://user-images.githubusercontent.com/63427719/162632233-24dab211-12b2-4f00-9641-df815f48f558.mov

**Comment by illyShelly** [comment]
Hi @TildaDares 👋  OK. 
Now the only thing which needs our care 😃 is responsiveness of the <h1>. What about to add some media query (or update them) something like this (it's also for old iPhone 5 for instance). What do you think?

`
h1 {
    font-size: 1rem;
}

@media (min-width: 320px) {
    h1 {
        font-size: 1.5rem;
    }
}

@media (min-width: 600px) {
    h1 {
        font-size: 1.7rem;
    }
}

@media (min-width: 800px) {
    h1 {
        font-size: 1.9rem;
    }
}

@media (min-width: 1000px) {
    h1 {
        font-size: 2.05rem;
    }
}
`

**Comment by TildaDares** [comment]
@illyShelly Sounds interesting. Can I see a screen recording of how it looks on different screen sizes?

**Comment by illyShelly** [comment]
@TildaDares 👋 

In recording is the difference between local:3000 and current Publiclab.org page. 
So, I implement the **media query** with some corrections for **other headings as well** (h2 - h5). Of course now it's without your suggestion - please send it to me.

Why all?
1. because so many `<a> tags ` /links and various buttons is used as **anchor tag** with **heading** , so without change of all would stay the text big even on smaller devices - as default size for h2-h5. Until someone change them and apply some classes f.e. for cards: (.card-pic, .card-body, .card-links etc.).
2. You can see in the gif it makes problem in **cards and some buttons** - anchor tags are just in div, or within `<h3>` etc. so it overlaps.
3. In general, it is problem especially for users with disability using screen readers - but it's another topic 'accessibility' and rules.

So, the css file will look like this (+/- some smaller change as you like):

```
/*For the smallest devices (< iPhone 5)*/
@media (max-width: 319px) {
    h1 {
      font-size: 1.2rem;
    }
    h2 {
      font-size: 1.1rem;
    }
    h3 {
      font-size: 1rem;
    }
    h4 {
      font-size: 0.95rem;
    }
    h5 {
      font-size: 0.9rem;
    }
    /*For text*/
    p {
      font-size: 12px;
    }
}

@media (min-width: 320px) {
    h1 {
      font-size: 1.5rem;
    }
    h2 {
      font-size: 1.4rem;
    }
    h3 {
      font-size: 1.3rem;
    }
    h4 {
      font-size: 1.25rem;
    }
    h5 {
      font-size: 1.2rem;
    }
}

@media (min-width: 600px) {
    h1 {
      font-size: 1.7rem;
    }
    h2 {
      font-size: 1.6rem;
    }
    h3 {
      font-size: 1.5rem;
    }
    h4 {
      font-size: 1.4rem;
    }
    /*Some cards and links <a> use headings instead of class*/
    h5 {
      font-size: 1.25rem;
    }
}

@media (min-width: 800px) {
    h1 {
      font-size: 1.9rem;
    }
    h2 {
      font-size: 1.8rem;
    }
    h3 {
      font-size: 1.7rem;
    }
    h4 {
      font-size: 1.45rem;
    }
    h5 {
      font-size: 1.25rem;
    }
}

@media (min-width: 1000px) {
    h1 {
      font-size: 2.0rem;
    }
    h2 {
      font-size: 1.85rem;
    }
    h3 {
      font-size: 1.75rem;
    }
    h4 {
      font-size: 1.55rem;
    }
    h5 {
      font-size: 1.25rem;
    }
}

```
To make gif  small is complicated 😄 

![sending-headings](https://user-images.githubusercontent.com/26350915/162785716-78c66557-da8e-4bed-8752-5d25a131ac25.gif)

**Comment by TildaDares** [comment]
@illyShelly I use mac’s inbuilt screenshot app.

**Comment by TildaDares** [comment]
@illyShelly Hmmm I don’t think we need different font-size on different screen sizes since rem already does that. I think if we just reduce the size of the question header, we’ll be fine.

**Comment by TildaDares** [comment]
Also I was reading about rems just now and I learnt that instead of changing the value of the tags directly, we do only do that for the html tag https://dev.to/vetswhocode/responsive-sizing-with-rem-css-units-2m27

**Comment by illyShelly** [comment]
> @illyShelly Hmmm I don’t think we need different font-size on different screen sizes since rem already does that. I think if we just reduce the size of the question header, we’ll be fine.

@TildaDares,
My internet and computer is sooooo slow today. Sorry.

OK, I have experience with EM - relative sizing to parent element, not REM. I agree, we do not need so many queries -> points where it will change the size of headings. And thank you for the recording info - it saves my nerves 😉 

But as I can read here [and](https://elementor.com/help/whats-the-difference-between-px-em-rem-vw-and-vh/) and tried it in browser I understand as: REM resize tags based on default html which is **16px** or if we change the html for another value (as is example 18px).
Then, 1REM = 1*16px=16px; 2REM = 2*16px = 32px -> when changing base to 18px -> 1REM = 1*18=18px; 2REM = 2*18px etc.
But it doesn't mean the elements will change their value **H1, p, .. tag** when we resize the page. No change there.

I will suggest then: 
1. Set size of h1 - to be smaller.
2. Have at least 1 media query for small devices (smartphones) upto 400px for all headings, otherwise the text (Question, Comment) will be still 2.0rem (32px) even on small screens.

```
h1 {
  font-size: 1.95rem;
}

@media only screen and (max-width: 400px) {
    h1 {
      font-size: 1.6rem;
    }
    h2 {
      font-size: 1.4rem;
    }
    h3 {
      font-size: 1.3rem;
    }
    h4 {
      font-size: 1.25rem;
    }
    h5 {
      font-size: 1.2rem;
    }
}
```

Uploading Tilda_result1.mov…

**Comment by illyShelly** [comment]
https://user-images.githubusercontent.com/26350915/162825474-5e1f4a02-249b-4ff3-bbed-1a58225aa329.mov

**Comment by illyShelly** [comment]
https://user-images.githubusercontent.com/26350915/162827422-5b964331-dc9d-422e-a24d-6c5ff4a0e107.mov

**Comment by TildaDares** [comment]
@illyShelly This looks good. Do you think you could take this up yourself? It's possible we might have further discussion after opening a PR.

**Comment by illyShelly** [comment]
@TildaDares hi, sure it'll be easier. I'll correct also indentation in the file. It's mishmash. Thank you for your time :)
