### ISSUE TITLE
Fix typo in html tag (part of #10989)

### ISSUE THREAD

**Issue by kachifako** [publiclab/plots2#11002]
### 💡Format this Issue Into a First Timers Issue
This has been marked as a good candidate for becoming a [first-timers-only issue](https://code.publiclab.org/#r=all) like these, meaning that it's **simple, self-contained**, and with some extra formatting✍️, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider **reformatting it as a first-timers-only issue**, and then ping @publiclab/reviewers to get it labelled🏷. Or, if this is not your first time, **try to solve it yourself**🧑‍💻!

****

Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Claim the issue by commenting. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
<details>
  <summary>💡 <i>Learn how to claim</i> 🙋</summary>
  <h3>Claiming an issue</h3>
  <p>Unless the issue is marked as reserved for someone, you can just say "I'd like to try this!" and then you've claimed it - no need to wait for someone to assign it to you. Just be sure you link your pull request (PR) to this issue so we can see where your solution is.</p>
  <p>And open one early if possible - even before you've completed it with additional commits - and others can help you figure out any issues you may face.</p>
</details>

- [ ] 📝 **Update** these files in the `plots2` repository (press the little pen Icon) and edit the lines as shown below:
- [404.html](https://github.com/publiclab/plots2/blob/c7d95b1c2377eadb50d900a43e636284dca2c66a/public/404.html) (Line 62)

- [422.html](https://github.com/publiclab/plots2/blob/c7d95b1c2377eadb50d900a43e636284dca2c66a/public/422.html) (Lines 45 and 63)

- [500.html](https://github.com/publiclab/plots2/blob/c7d95b1c2377eadb50d900a43e636284dca2c66a/public/500.html) (Lines 43, 47, 65)

- [502.html](https://github.com/publiclab/plots2/blob/c7d95b1c2377eadb50d900a43e636284dca2c66a/public/502.html) (Lines 46, 62)

 - [503.html](https://github.com/publiclab/plots2/blob/c7d95b1c2377eadb50d900a43e636284dca2c66a/public/503.html) (Lines 46, 62)

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
  -    <hr  />
  +     <hr>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below, and [reach out in our chatroom](https://publiclab.org/chat)!

**Comment by kachifako** [comment]
I hope this is okay @TildaDares

**Comment by TildaDares** [comment]
Looks good @kachifako. Thank you!!

**Comment by kachifako** [comment]
Happy to be of help @TildaDares .

Should I assign the individual issues to first timers ?

**Comment by TildaDares** [comment]
Reserved for @Crisoal for 24 hours!

**Comment by Crisoal** [comment]
thank you


> Reserved for @Crisoal for 24 hours!

thank you

**Comment by Crisoal** [comment]
@TildaDares how do I make changes to the file?

**Comment by TildaDares** [comment]
@Crisoal Have you gone through this issue's description?

**Comment by Crisoal** [comment]
> @Crisoal Have you gone through this issue's description?

yes but should I add a my own words to the file?

**Comment by TildaDares** [comment]
@Crisoal You are supposed to remove the lines that start with `-` and then replace it with the line that starts with `+`.
> Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:
> 
> ```diff
>   -    <hr  />
>   +     <hr>
> ```
> 
> *

**Comment by Crisoal** [comment]
> @Crisoal You are supposed to remove the lines that start with `-` and then replace it with the line that starts with `+`.
> 
> > Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:
> > ```diff
> >   -    <hr  />
> >   +     <hr>
> > ```

Yes, thank you. I got the hang of it and I have done the tasks

**Comment by kachifako** [comment]
> > @Crisoal You are supposed to remove the lines that start with `-` and then replace it with the line that starts with `+`.
> > > Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:
> > > ```diff
> > >   -    <hr  />
> > >   +     <hr>
> > > ```
> 
> Yes, thank you. I got the hang of it and I have done the tasks

did you create a pull request to merge the changes  @Crisoal ?

**Comment by guyinmanhattan2021** [comment]
Hi @kachifako can I contribute to this?

**Comment by TildaDares** [comment]
Hi @Crisoal, do you need help with this?

**Comment by haydenmlh** [comment]
Hi, I'd like to try this!

**Comment by Crisoal** [comment]
> Hi @Crisoal, do you need help with this?

i have done the first task but I am not sure of how to go about the second task

**Comment by Crisoal** [comment]
> @Crisoal What is the second task?

it is to pull request

**Comment by TildaDares** [comment]
@Crisoal You can follow this guide https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github. Skip the steps you’ve already done.

**Comment by Crisoal** [comment]
> @Crisoal You can follow this guide https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github. Skip the steps you’ve already done.

ok, thanks

**Comment by Crisoal** [comment]
I have been able to pull a request. Can you pls review it?

**Comment by Crisoal** [comment]
> I have been able to pull a request. Can you pls review it?

https://github.com/Crisoal/plots2
