### ISSUE TITLE
Positioning of Lock Icon is not in center of circle.

### ISSUE THREAD

**Issue by Radhika-Saini** [publiclab/plots2#11014]
The Lock icon is found on the site by the following steps-
1. Login
2. In the community Dropdown, Click on Get Started. 

![2022-04-10 (3)](https://user-images.githubusercontent.com/59209590/162589351-a4015bb9-3d10-40a7-b2ff-08456751e536.png)

**Comment by Radhika-Saini** [comment]
@TildaDares  I found a bug, Kindly review.

**Comment by TildaDares** [comment]
Hi @Radhika-Saini, go ahead. Thanks!

**Comment by Radhika-Saini** [comment]
@Tilda I am an outreachy applicant, Finding bugs and Suggesting Feature PR are enough for contribution or need more to get selected.

**Comment by TildaDares** [comment]
Hi @Radhika-Saini, you need to make at least one contribution(PR).

**Comment by Radhika-Saini** [comment]
Ok, @TildaDares  Thanks.

**Comment by romasinha** [comment]
If this issue is not resolved yet, can I take it up @TildaDares?

**Comment by Ifetakuro** [comment]
@Radhika-Saini have you been able to fix the bug? do you mind me helping if you havent?

**Comment by rajvidg** [comment]
@Radhika-Saini is this issue still open? If yes, can I help to resolve it.

**Comment by Radhika-Saini** [comment]
Yeah @Ifetakuro, @rajvidg we all can do this together.

**Comment by rajvidg** [comment]
> Yeah @Ifetakuro, @rajvidg we all can do this together.

Oh great :) , so, should we ask the mentors first or proceed?

**Comment by Ifetakuro** [comment]
@Radhika-Saini @rajvidg once we get a go ahead from @TildaDares we should be able to work on it together :)

**Comment by rajvidg** [comment]
> @Radhika-Saini @rajvidg once we get a go ahead from @TildaDares we should be able to work on it together :)

Yes, I was also thinking the same. :)

**Comment by Sushil333** [comment]
Hi @TildaDares, 
I have fixed this issue in pr https://github.com/publiclab/plots2/pull/11087/commits/050da3cb47e2aca7848a5b570511be6d23ef8b12 . Please review it.
Thanks.

**Comment by TildaDares** [comment]
Hi @Sushil333, you haven't pushed to `publiclab/plots2`.

**Comment by Sushil333** [comment]
> Hi @Sushil333, you haven't pushed to `publiclab/plots2`.

Thank you for the reply. I already made a pull request https://github.com/publiclab/plots2/pull/11087 and this is another one. I think both are in same pr.

**Comment by TildaDares** [comment]
Closed in #11368
