### ISSUE TITLE
Fix warnings in style.css

### ISSUE THREAD

**Issue by Somya-Singhal** [publiclab/plots2#11029]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

<img width="427" alt="pl-21" src="https://user-images.githubusercontent.com/88088520/162729915-91d2cd37-2ef0-4bf9-a348-76640a95c801.PNG">

> What did you expect to see that you didn't?

<img width="457" alt="pl-22" src="https://user-images.githubusercontent.com/88088520/162730094-4659c9c1-09dd-4921-a546-24ba7b60e265.PNG">

Hello @TildaDares, I noticed there were some warnings in style.css which would be resolved if we add the standard style rule in addition to the vendor prefixed version. Above I have attached the screenshot of the solution also.

### Please show us where to look

https://github.com/publiclab/plots2/blob/main/static/style.css

**Comment by Somya-Singhal** [comment]
Hello @TildaDares, Can I work on resolving this issue?

**Comment by TildaDares** [comment]
Yeah go ahead @Somya-Singhal. Thanks!!

**Comment by Somya-Singhal** [comment]
Thanks @TildaDares, I linked a pull request. Can you please review it and suggest the changes if any needed?

**Comment by Somya-Singhal** [comment]
<img width="288" alt="image" src="https://user-images.githubusercontent.com/88088520/162948471-e9112bdd-72dc-40ea-b9d9-1d62f346e623.png">

Hello @TildaDares, I noticed that in this block of code, `sidebar` is used as id and `box` is used as class. But in style.css this id and class has not been implemented, so is this intentionally kept or we can remove it?

**Comment by TildaDares** [comment]
@Somya-Singhal `sidebar` and `box`  might be used for JavaScript.
