### ISSUE TITLE
Upgrade to Rails 4.2

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1102]
We're starting to get warnings for the `paperclip` gem:

```
DEPRECATION WARNING: [paperclip] [deprecation] Rails 3.2 and 4.1 are unsupported as of Rails 5 release. Please upgrade to Rails 4.2 before upgrading paperclip. (calle
d from <class:Image> at /home/warren/sites/plots2/app/models/image.rb:12)
DEPRECATION WARNING: [paperclip] [deprecation] Rails 3.2 and 4.1 are unsupported as of Rails 5 release. Please upgrade to Rails 4.2 before upgrading paperclip. (calle
d from <class:User> at /home/warren/sites/plots2/app/models/user.rb:21)
```

Worth trying it out  in the Gemfile and Gemfile.lock and seeing how the tests do?

**Comment by mridulnagpal** [comment]
@jywarren I'd like to try it out

**Comment by jywarren** [comment]
I believe we've left some comments in the codebase as well, whenever we did
a rails 4 or 3 specific fix so it may be worth searching for 'Rails 3' or
'Rails 4'!

**Comment by mridulnagpal** [comment]
@jywarren So what all things will I have to do? I don't know where to start

**Comment by jywarren** [comment]
Yeah it's a tough one. I think for starters, change the gemfile and run 'bundle install' and then add the Gemfile.lock -- then create a PR. We'll see what happens. 

I ran a search for "Rails 3" and "Rails 4" and didn't find anything. So I guess we see what happens?

It looks like the big one is from Rails 3-4, here: http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-3-2-to-rails-4-0

And then from 4.0-4.1 is not as bad, as can be expected. I'm not sure, but it looks like we'll want to go to 4.2!

**Comment by pyluftig** [comment]
@jywarren and @mridulnagpal I would like to help with this one. I've done an upgrade in the past so let me know if you want my help.

**Comment by mridulnagpal** [comment]
Yeah please do :)

**Comment by jywarren** [comment]
Merge into #1318 --
