### ISSUE TITLE
Unnecessary forward slash in many html files

### ISSUE THREAD

**Issue by Ishhha** [publiclab/plots2#11035]
Many unnecessary forward slashes are there in hr and br tags in 404.html, 422.html, 500.html, 502.html, and 503.html.

### Please show us where to look

https://publiclab.org/plots2/public/404.html
https://publiclab.org/plots2/public/422.html
https://publiclab.org/plots2/public/500.html
https://publiclab.org/plots2/public/502.html
https://publiclab.org/plots2/public/503.html

**Comment by Ishhha** [comment]
@TildaDares Can I work on this issue?

**Comment by TildaDares** [comment]
Hi @Ishhha, an issue has already been opened for hr tags in #11002.

**Comment by Ishhha** [comment]
Okay @TildaDares.
