### ISSUE TITLE
Improve the alignment of the navigation bar links 

### ISSUE THREAD

**Issue by simransia** [publiclab/plots2#11049]
The "store" and the "donate" buttons on the navbar are not looking good as they are having unequal widths and are not aligned well on the navbar. 
Along with that, the "About us" link on the navigation bar is aligned more towards the right which is also not looking good. Secondly, it should be changed from "About us" to "About Us"

So, I want to make the store and donate buttons align to the right and also want to make their widths equal. And I also want to make the margin-left of the "About us" link equal to the margin-left of other navigation links.

### BEFORE:
![Screenshot (122)](https://user-images.githubusercontent.com/88017902/163147854-7a5bd1b1-35af-41ef-9b18-e6ad93b74a1c.png)

### AFTER:
![Screenshot (124)](https://user-images.githubusercontent.com/88017902/163147944-43254a0e-0a4e-4385-ba30-4225b99d7c37.png)

### Video for showing responsiveness:

https://user-images.githubusercontent.com/88017902/163152820-f6f36645-8038-475f-b98c-714c0bc623ff.mp4

**Comment by simransia** [comment]
Hello @TildaDares , should I work on this issue and make a pull request?

Please let me know. Thank You!

**Comment by TildaDares** [comment]
Hmmm I’m not sure 🤔. I like the way all of the nav links related to the public Lab community and the content related to the user are separate.

**Comment by TildaDares** [comment]
@simransia I’m not worried about code breaking. I just don’t see how Store and Donate relate to Dashboard.

**Comment by simransia** [comment]
Ok @TildaDares , I got it. 
Then I will not align the Store and donate buttons to the right, which will keep the public lab's community links and the content related to the user separated.
I will only make the width of both the buttons equal and modify the "About us" link's margin-left and spelling.

**Then the navigation bar will look like this:**
![Screenshot (127)](https://user-images.githubusercontent.com/88017902/163201363-e9663c81-8ec4-475b-bf8a-ba2ff1a7627f.png)

Can I now create a pull request after applying the mentioned changes?

**Comment by TildaDares** [comment]
Sounds like a great idea @simransia. Thanks!

**Comment by cesswairimu** [comment]
solved  in https://github.com/publiclab/plots2/pull/11053. Closing this
