### ISSUE TITLE
Add margin to “welcome to new dashboard”

### ISSUE THREAD

**Issue by Ifetakuro** [publiclab/plots2#11059]
![6264171A-9465-4A0F-8611-F0662C04B977](https://user-images.githubusercontent.com/93978195/163588173-cd189ca3-a6f0-4323-a5ef-3b391c6234e5.jpeg)

### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

When on small screen the “new dashboard” div is too close to the last grid element. Thereby looking like a single element.

> What did you expect to see that you didn't?

I expect to see a gap between the grid elements and the welcome to new dash board. Thereby showing they’re not together.
I suggest we add a margin top to the element.

@jywarren @TildaDares please can I work on this or can it be a FTO?

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by TildaDares** [comment]
Hi @Ifetakuro, go ahead!!

**Comment by Ifetakuro** [comment]
@TildaDares thank you
