### ISSUE TITLE
Unchecking the select-all checkbox does not disable spam2 buttons

### ISSUE THREAD

**Issue by PeculiarE** [publiclab/plots2#11065]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I clicked and unclicked on the select button on the mini-navbar on spam2 dashboard and the spam2 buttons (spam, publish, delete etc) were enabled and disabled respectively.

However, once I tried to replicate same with the select-all checkbox on the table, I did not get the same result.

> What did you expect to see that you didn't?

i expected that once I unchecked the select-all checkbox, the spam2 buttons will be automatically disabled. But they weren't. So a moderator can click on any of the buttons (e.g. ban) without any node being selected for banning, and this throws an uncaught exception.

Please see the demo below:

https://user-images.githubusercontent.com/75625011/163829254-29b9affa-2515-48c7-a4cb-9d4902f2900a.mp4

### Please show us where to look

https://publiclab.org/spam2

### What's your PublicLab.org username?

perhisohwode (However, I'm neither a mod nor an admin, so I was only able to observe this in my local environment)

### Browser, version, and operating system

Google Chrome Version 100.0.4896.60 (Official Build) (arm64), MacOS Big Sur version 11.4

**Comment by PeculiarE** [comment]
Hi @cesswairimu, @TildaDares, @jywarren....can I work on this, please?

**Comment by TildaDares** [comment]
Hi @PeculiarE, great catch. Go ahead!

**Comment by PeculiarE** [comment]
Alright @TildaDares. Thank you
