### ISSUE TITLE
Fix indentation in new.html.erb

### ISSUE THREAD

**Issue by abhishekchauhan15** [publiclab/plots2#11077]
### 💡Format this Issue Into a First Timers Issue
This has been marked as a good candidate for becoming a [first-timers-only issue](https://code.publiclab.org/#r=all) like these, meaning that it's **simple, self-contained**, and with some extra formatting✍️, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider **reformatting it as a first-timers-only issue**, and then ping @publiclab/reviewers to get it labelled🏷. Or, if this is not your first time, **try to solve it yourself**🧑‍💻!

****
### todo:
Fix indentation  of this file [new.html.erb](https://github.com/publiclab/plots2/edit/main/app/views/csvfiles/new.html.erb) in the `plots2` repository (press the little pen Icon). Indentation should be 2 spaces deep.

**Comment by abhishekchauhan15** [comment]
Hey @TildaDares Kindly review my FTO issue!

**Comment by TildaDares** [comment]
Hi @abhishekchauhan15, indentation should be two spaces deep. Thanks!!

**Comment by ryuusama09** [comment]
Hi ,can I claim this issue ?

**Comment by TildaDares** [comment]
Hi @ryuusama09, this issue is not formatted properly. You can request for an issue in #11105. Thank you!

**Comment by Sayak-singha** [comment]
hi, can I fix this issue

**Comment by lanefoxwood** [comment]
Hey, just wanted to say I'm sorry if this issue isn't ready to be worked on yet. I attempted to work on what the original todo requested. If I am in the wrong place, again, sorry!

**Comment by cesswairimu** [comment]
Hey @lanefoxwood, its okay,  we normally leave a comment on an issue before starting working on an issue for better planning. But no worries, @Sayak-singha please let me know if me know if you are still looking for an issue, Thanks you both

**Comment by Sayak-singha** [comment]
> Hey @lanefoxwood, its okay,  we normally leave a comment on an issue before starting working on an issue for better planning. But no worries, @Sayak-singha please let me know if me know if you are still looking for an issue, Thanks you both 

I have commented on the First-timer-only repo and my name was added to the list hope I will get an issue within some days

**Comment by 7malikk** [comment]
@TildaDares Hello, does this issue still need formatting, i would like to give it a go, my name has not been added to the list for those requesting for an issue

**Comment by TildaDares** [comment]
Hi @7malikk, yes go ahead. Thank you!

**Comment by 7malikk** [comment]
> Hi @7malikk, yes go ahead. Thank you!

Alright @TildaDares , I'll get on it and ping you. Thank you!

**Comment by TildaDares** [comment]
You’re right @7malikk. I’ll close this now. Thank you!!

**Comment by TildaDares** [comment]
Resolved in #11133
