### ISSUE TITLE
Pagination and results mismatched on questions tab of some tag pages

### ISSUE THREAD

**Issue by bhamster07** [publiclab/plots2#11076]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I've encountered a bug on some tag pages when viewing the questions tab. For example, on https://publiclab.org/questions/tag/community, the tab icon shows 13 posts and there are 13 cards displayed below, but at the bottom there's a pagination menu that suggests 5 pages of results. When I click on any subsequent page, the page just displays the same 13 results first seen on pg. 1.

<img width="407" alt="Screen Shot 2022-04-19 at 12 43 47 PM" src="https://user-images.githubusercontent.com/68756159/164083601-52982daa-0060-44ca-bc5e-e35a5983a59e.png">

> What did you expect to see that you didn't?

With all 13 results visible on the first page, I expected to see only 1 page available in the pagination menu instead of 5.

### Please show us where to look

https://publiclab.org/questions/tag/community

Something similar happens at https://publiclab.org/questions/tag/stormwater. 16 posts visible, pagination menu suggests 4 pages of results.

But this doesn't seem to happen on some other tag pages! E.g., https://publiclab.org/questions/tag/mine-reclamation, no visible mismatch here.

### What's your PublicLab.org username?

bhamster

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

Chrome 100.0.4896.88, MacOS Monterey 12.3.1

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by Deepthi562** [comment]
@TildaDares can i work on this?

**Comment by ebarry** [comment]
Thanks for reporting this bug @bhamster07 !
What you describe sounds so tricky! A real mystery: 

> Something similar happens at https://publiclab.org/questions/tag/stormwater. 16 posts visible, pagination menu suggests 4 pages of results.

> But this doesn't seem to happen on some other tag pages! E.g., https://publiclab.org/questions/tag/mine-reclamation, no visible mismatch here.

**Comment by jywarren** [comment]
Hi! Confirming that this happens on stable too; hopefully we see it get fixed in https://github.com/publiclab/plots2/pull/11134 and we can confirm in stable!

<img width="437" alt="image" src="https://user-images.githubusercontent.com/24359/170139425-62e1ee66-ddfd-44e8-bf1a-9e24212fb61a.png">


@Deepthi562 sorry for the slow response, this one was pretty obscure. Can we help you find another? Please say hello in our chatroom at https://matrix.to/#/#publiclab:matrix.org and we can help find you one!

**Comment by jywarren** [comment]
Confirmed on https://stable.publiclab.org/questions/tag/community !
