### ISSUE TITLE
Improve Card heights

### ISSUE THREAD

**Issue by rajvidg** [publiclab/plots2#11079]
In the Infagram.org site, I came with the following bug of unequal card heights in the case of long text titles, so it can be improved by increasing the height of the shorter text cards accordingly.
I have attached the following screenshot for the context:
<img width="619" alt="plots2_Issue2" src="https://user-images.githubusercontent.com/78178838/164268099-83f9be05-dd4f-44b0-9656-adb25ab83d10.png">
@TildaDares please suggest what can be done in this ? :)

**Comment by TildaDares** [comment]
Hi @rajvidg, we're a bit skeptical about using a fixed height for cards because some of them would look empty compared with cards that have long titles. Do you have any solution in mind that removes this problem?

**Comment by rajvidg** [comment]
> Hi @rajvidg, we're a bit skeptical about using a fixed height for cards because some of them would look empty compared with cards that have long titles. Do you have any solution in mind that removes this problem?

Oh yes, it can be a thing, so okay, let me think some other approach then!

**Comment by cesswairimu** [comment]
The current design seems better as , closing this for now  and please feel free to reopen and update if you have a better design. Thanks all
