### ISSUE TITLE
Fill out new HTML form for location entry

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1107]
Followup to #1035, @mridulnagpal asked for next steps. We now have a blank HTML template:

https://github.com/publiclab/plots2/blob/master/app/views/locations/form.html.erb

Now we need to add HTML markup for the location form itself, building from this image:

![gif](https://cloud.githubusercontent.com/assets/161439/17665075/8f4b041a-62c6-11e6-9fdf-0bf5b4a71e80.gif)

And using elements from https://getbootstrap.com/components/ 

We can leave the map as a grey square at the top, for now!

**Comment by mridulnagpal** [comment]
@jywarren I did not get the exact template could you tell me more about it?

**Comment by jywarren** [comment]
I think we're hoping to get a set of text and inputs to simply display as best as you can what's shown in the gif (by @ebarry) but that don't need to function just yet. Then we'll do a followup task of starting to plug in functions. Make sense?
