### ISSUE TITLE
Add padding

### ISSUE THREAD

**Issue by rajvidg** [publiclab/plots2#11078]
I saw this in the bottom of Infagram.org site's Q&A section where the "ask a question" call to action button was placed right below the scroll bar of Q&A section, I think there should be some gap between them for a better distinction.
I have attached a screenshot of the above bug:
<img width="909" alt="plots2_Issue1" src="https://user-images.githubusercontent.com/78178838/164265716-12588041-244e-4a11-acca-55d9364efdf2.png">
@TildaDares can I work on this? Please review. :)

**Comment by TildaDares** [comment]
Hi @rajvidg, this has been resolved in https://github.com/publiclab/plots2/pull/10912. We're just waiting for the changes to be published on the main site. Thanks!

**Comment by rajvidg** [comment]
> Hi @rajvidg, this has been resolved in #10912. We're just waiting for the changes to be published on the main site. Thanks!

Oh, okay, thanks for your time :)
