### ISSUE TITLE
Revisit reverse chronological sorting in inline grids

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#11103]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I asked "Has the default sorting in inline grids changed? I'm surprised to see the reverse chron order on this page which makes everything look really old https://publiclab.org/locations"

and Jeff replied: 

> it looks like sorting reversed in the past year https://web.archive.org/web/20210417150950/https://publiclab.org/locations
> Here is the change: /plots2/commit/fa4434b50977218575a2dc2e9b422ac88cdcb007#diff-9486c6225f3ecf92b3e2a8745a67090f2ab6ad033c5504c6a096902fe4dc02ceL399-R401
> It was in relation to a fix for this issue: https://github.com/publiclab/plots2/issues/10507
> It's pretty subtle and I'm not quite sure the relationship between the ordering and this bug, but it seems on first glance to be significant. 

> What did you expect to see that you didn't?

I would expect to see most recent posts at the top, with chronological sorting where oldest is lowest. 

### Please show us where to look

https://publiclab.org/locations
and the many, many other pages that use inline grids

### What's your PublicLab.org username?

Liz

**Comment by jywarren** [comment]
Just noting that this one could cause a test failure if we just re-add the DESC to the order clause. But it could be worth an attempt:

https://github.com/publiclab/plots2/blob/e211e63cf709141e1de86d996ad073f362e7ef68/app/models/concerns/node_shared.rb#L401

Note that DESC exists on the alternative version of this method a few lines down!

**Comment by mittal-parth** [comment]
@ebarry @jywarren 
The problem seems to be with embeds that include both _notes_ and _pages_. Whenever the `nodes_by_tagname` receives an array of different types of content, that block doesnt contain the DESC. 
I can try this but I cant seem to find the way to embed a grid inside a wiki. 
Also, upon visiting /embed/grid/<tagname> on localhost, only notes associated to the tag are visible (even though wikis exist). Am I missing something?

**Comment by Forchapeatl** [comment]
> @ebarry @jywarren The problem seems to be with embeds that include both _notes_ and _pages_. Whenever the `nodes_by_tagname` receives an array of different types of content, that block doesn't contain the `DESC`. I can try this but I can't seem to find the way to embed a grid inside a wiki. Also, upon visiting` /embed/grid/<tagname>` on localhost, only notes associated to the tag are visible (even though wikis exist). Am I missing something?

Please could you share some screenshots or codes?

**Comment by mittal-parth** [comment]
Thank you! @ebarry 

I have created a [PR](https://github.com/publiclab/plots2/pull/11114) for this. Adding the `DESC` worked. No tests failed either!
cc: @jywarren
