### ISSUE TITLE
Missing translations on layouts/_header.html.erb

### ISSUE THREAD

**Issue by mittal-parth** [publiclab/plots2#11115]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Claim the issue by commenting. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
<details>
  <summary>💡 <i>Learn how to claim</i> 🙋</summary>
  <h3>Claiming an issue</h3>
  <p>Unless the issue is marked as reserved for someone, you can just say "I'd like to try this!" and then you've claimed it - no need to wait for someone to assign it to you. Just be sure you link your pull request (PR) to this issue so we can see where your solution is.</p>
  <p>And open one early if possible - even before you've completed it with additional commits - and others can help you figure out any issues you may face.</p>
</details>

- [ ] 📝 **Update** the following files in the `plots2` repository (press the little pen Icon) and edit the line as shown below.

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

- [ ] 1. [/app/views/layouts/_header.html.erb](https://github.com/publiclab/plots2/blob/main/app/views/layouts/_header.html.erb#L71)

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

 ## `How to Access`
```diff
70:  <div class="dropdown-divider"></div>
- 71:  <h6 class="dropdown-header">Kits</h6>
+ 71:  <h6 class="dropdown-header"><%= translation('layout._header.tools.kits') %></h6>
72:  <%= create_nav_dropdown_item("/kits","layout._header.tools.kits_initiative") %>
73:  <%= create_nav_dropdown_item("//store.publiclab.org","layout._header.tools.store") %>
- 74:  <h6 class="dropdown-header">Software</h6>
+ 74:  <h6 class="dropdown-header"><%= translation('layout._header.tools.software') %></h6>
75:  <%= create_nav_dropdown_item("//mapknitter.org","layout._header.tools.map_knitter") %>
```

```diff
88:  <div class="dropdown-menu">
89:    <%= create_nav_dropdown_item("/about","layout._header.about.about_public_lab") %>
90:    <%= create_nav_dropdown_item("/blog","layout._header.about.blog") %>
- 91:    <%= create_nav_dropdown_item("/newsletter","Newsletter") %>
+ 91:    <%= create_nav_dropdown_item("/newsletter","layout._header.about.newsletter") %>
- 92:    <%= create_nav_dropdown_item("/public-lab-careers","Careers") %>
+ 92:    <%= create_nav_dropdown_item("/public-lab-careers","layout._header.about.careers") %>
93:    <%= create_nav_dropdown_item("/wiki/contact","layout._header.about.contact") %>
94:  </div>
```
- [ ] 2. [/config/locales/en.yml](https://github.com/publiclab/plots2/blob/main/config/locales/en.yml#L728)

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

 ## `How to Access`
```diff
728:        code_community: "Code Community"
+ 729:      kits: "Kits"
+ 730:      software: "Software"
731:      about:
732:        about_title: "About us"
733:        stories: "Stories"
734:        blog: "Blog"
735:        about_public_lab: "About Public Lab"
736:        team: "Non-profit team"
737:        organizers: "Organizers"
738:        board: "Non-profit board"
739:        fund: "How we're funded"
740:        press_and_media: "Press and Media"
741:        contact: "Contact"
+ 742:      newsletter: "Newsletter"
+ 743:      careers: "Careers"
```

- [ ] 3. [/config/locales/fr.yml](https://github.com/publiclab/plots2/blob/main/config/locales/fr.yml#L509)

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

 ## `How to Access`
```diff
509:      search: "Rechercher dans Public Lab"
+ 510:    tools:
+ 511:      tools_title: "Outils"
+ 512:      methods: "Méthodes"
+ 513:      kits_initiative: "Initiative des trousses"
+ 514:      store: "Magasin"
+ 515:      map_knitter: "Map Knitter"
+ 516:      spectral_workbench: "Spectral Workbench"
+ 517:      code_community: "Communauté de codes"
+ 518:      kits: "Trousses"
+ 519:      software: "Logiciel"
520:      about:
521:        about_title: "À propos de nous"
522:        stories: "Récits"
523:        blog: "Blog"
524:        about_public_lab: "À propos de Public Lab"
525:        team: "Équipe à but non-lucratif"
526:        organizers: "Organisateurs⋅rices"
527:        board: "Comité administrateur à but non lucratif"
528:        fund: "Comment nous sommes financés"
529:        press_and_media: "Presse et Média"
530:        contact: "Contact"
+ 531:      newsletter: "Bulletin"
+ 532:      careers: "Carrières"
533:      get_involved:
```
- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by TildaDares** [comment]
Thanks for opening this @mittal-parth. There are a few changes needed.

`kits` and `software` should be aligned with `code_community`.
> ```diff
> 728:        code_community: "Code Community"
> + 729:        kits: "Kits"
> + 730:        software: "Software"
> ```

`newsletter` and `careers` should be aligned with `contact`
> ```diff
> 741:        contact: "Contact"
> + 742:        newsletter: "Newsletter"
> + 743:        careers: "Careers"
> ```

`tools` should be aligned with `search`. `kits` should be aligned with `code_community`
> ```diff
> 509:      search: "Rechercher dans Public Lab"
> + 510:      tools:
> + 511:        tools_title: "Outils"
> + 512:        methods: "Méthodes"
> + 513:        kits_initiative: "Initiative des trousses"
> + 514:        store: "Magasin"
> + 515:        map_knitter: "Map Knitter"
> + 516:        spectral_workbench: "Spectral Workbench"
> + 517:        code_community: "Communauté de codes"
> + 518:       kits: "Trousses"
> + 519:        software: "Logiciel"
> ```

`newsletter` and `careers` should be aligned with `contact`
> ```diff
> 530:        contact: "Contact"
> + 531:        newsletter: "Bulletin"
> + 532:        careers: "Carrières"
> ```

Thanks!

**Comment by TildaDares** [comment]
Also, do you speak/understand French?

**Comment by mittal-parth** [comment]
No no I dont understand French. I use Google Translate itself 😅. I pick that file because its the most updated 😛

**Comment by mittal-parth** [comment]
@TildaDares Pls check if I have made the required changes correctly. Sorry for the trouble!

**Comment by TildaDares** [comment]
Hi @mittal-parth, the issue hasn't been resolved.
> @TildaDares Pls check if I have made the required changes correctly. Sorry for the trouble!

**Comment by mittal-parth** [comment]
@TildaDares 
Interesting 🤔 

https://user-images.githubusercontent.com/76661350/166853846-87f6fd0b-cfd7-4608-b768-ddb8bab5fe04.mp4

Updated the rest. Looks like I didnt press the 'Update Comment' button last time 🥲

**Comment by TildaDares** [comment]
@mittal-parth Your translation still works so I think we can leave it as it is. Thanks for working on this!!

**Comment by TildaDares** [comment]
Reserved for @Dustpie for 24 hours!!

**Comment by Dustpie** [comment]
Thank you for reserving the issue for me Tilda, I will try it.

**Comment by TildaDares** [comment]
Hi @Dustpie, do you need help with this? Please feel free to reach out if you do.

**Comment by christinecannon** [comment]
Hello! Would it be okay for me to try this if @Dustpie is no longer working on it? I'd like to try this but don't want to take the opportunity away from anyone else of course!

**Comment by Dustpie** [comment]
I'm still working on it I just had to jump ik for shifts a lot so I'm a bit tired.
I will work on it tonight

**Comment by TildaDares** [comment]
Hi @christinecannon, you can leave a comment in #11105 and we’ll help you look for an issue. Thank you!

**Comment by Dustpie** [comment]
Yes you can have the issue
