### ISSUE TITLE
Add function to "post type" dropdown in new Rich editor

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1111]
This requires some UI/UX design thinking before we're ready to start coding.

We have a new rich editor! But it has this nice dropdown for "types" that doesn't do anything (although it also doesn't break anything) -- here, you can see the default `a research note`:

![screen shot 2016-12-15 at 5 37 04 pm](https://cloud.githubusercontent.com/assets/24359/21271220/1737a5be-c388-11e6-95bb-a3413e58ed1a.png)

https://publiclab.org/post (login required)

We should make it insert a template -- perhaps making a JavaScript jQuery `ajax` call to a template, like:

https://publiclab.org/notes/raw/13732

And inserting that before the post body, or at the insertion point. 

What should happen if you've already chosen one? Replace it?

Or if you've entered content; append instead of replace? Or just assume the user can hit `undo`?

**Comment by ryzokuken** [comment]
What if the template for the corresponding type is not used as `$('your-input').value` but as the placeholder text instead? I'm sure there must be a jQuery binding for that, and if not, we can manually set the attribute. The placeholder would only show up if there is no text in the input and otherwise won't affect the text in any way.

@jywarren what do you think?

**Comment by jywarren** [comment]
Oh I like this idea -- but the placeholder text won't appear in rich text
mode as it's not a textarea then.

**Comment by ryzokuken** [comment]
@jywarren What exactly did we decide on, then?
Perhaps we could insert the data into the fields empty and skip the fields that already have some data inside them. This would push actual data (not placeholder text) inside the fields but at the same time, not write over the existing data.

**Comment by jywarren** [comment]
I agree with this -- and additionally that we could insert the appropriate
template text at the bottom of the post, as GitHub Saved Replies does?

**Comment by ryzokuken** [comment]
@jywarren Just checked it out. Github's saved replies adds a newline and appends the new message at the end of the current buffer. I guess this would be best for us as well. However, if the user repeatedly changes the value on the dropdown, the sample text will keep on adding. Is this desirable?

**Comment by jywarren** [comment]
Hmm... It's a bit of an odd interface. Maybe we need to rethink how it
should work more broadly, but one difference might be that if all that's in
the textarea is another template, it might replace the template instead of
adding to it?

What if, once you choose one and begin typing into the textarea, this menu
were disabled? Since it's more of a starting point rather than a useful way
to add content -- in this, it's less like saved replies. Or, perhaps it's
OK that the behavior be different before and after you actually begin
typing text in.

Not 100% sure on this, happy to hear your opinions.

**Comment by ryzokuken** [comment]
Totally a stupid thought, but we could make an "Insert Template" button with the same functionality. Just like Github calls it "Insert a saved reply". This way, merely switching between modes won't make much of a difference, but rather they'd have control over when to insert the corresponding reply to the textarea. This way, they could swap the different options without worrying about having to clean up the mess inside the body text. What do you say?

**Comment by jywarren** [comment]
Hmm, sorry but what exactly would it do? Just the same as saved replies,
and we add a button instead of switching immediately when another option is
selected in the menu?

Would we move the menu?

**Comment by ryzokuken** [comment]
Yes. It'd insert an appropriate template corresponding to the selected value from the dropdown.

**Comment by jywarren** [comment]
What if as soon as you interact with the textarea it begins the "insert"
behavior but before then it just changes on selecting, with no button shown
yet? Is that too hybrid?

**Comment by ryzokuken** [comment]
If I interpreted what you said correctly, we could check if the user has interacted with the textarea since the last update/append. If no interaction has taken place, then swap the templates, otherwise append. How does this sound?

**Comment by jywarren** [comment]
Or even use a listener to check if they've clicked or typed into the
textarea, and change the interface based on that. Yes! Let's try this and
see how people like it.

**Comment by ryzokuken** [comment]
Let's decide on the exact functionality and then I'd try my best convert it into code. We could always change it later to better suit people's needs.

**Comment by jywarren** [comment]
Let's start with a simple case and just replace the content until someone
interacts with the text area, then append it. How's that sound?

Thanks!

**Comment by ryzokuken** [comment]
Yes, that sounds pretty do-able (if that's a word). I'd look into the Javascript side of things (because we're using Bootstrap, I assume we're also using JQuery, right?) and come back to you.

**Comment by jywarren** [comment]
Yep, that sounds great!

**Comment by ryzokuken** [comment]
There seems to be something trickier going on in the rich text editor though. The typed text appears to be not inside the textarea but inside a div.

Also, some script is seemingly blocking the event handlers from being called. (I guess some `event.preventDefault()`?)

**Comment by jywarren** [comment]
Ah yes, apologies -- to update its content (esp. since the user may be in either rich or markdown modes), you should use:

```js
editor.richTextModule.value('hello there');
```

And apologies for a slow start this week -- a lot to get done! I'll update the docs accordingly:

https://github.com/publiclab/PublicLab.Editor/blob/master/README.md

**Comment by jywarren** [comment]
changes made here: https://github.com/publiclab/PublicLab.Editor/pull/87

**Comment by ryzokuken** [comment]
Did look into the documentation of the Editor library. Would still need your help in order to add event listeners and we're using a bower library to do it.

**Comment by jywarren** [comment]
So, you could try to trigger this code on `change` event of the `<select>` - using jQuery. You could then write a JavaScript method to insert appropriate content into the textarea using:

```js
editor.richTextModule.value('hello there');
```

Does this make sense? Give it a try and I'm happy to leave more specific comments! Thanks!

**Comment by jywarren** [comment]
I've been thinking on this and maybe we should just remove that menu for now! Is it really that important?

**Comment by cesswairimu** [comment]
the dropdown  has been removed. Closing this
