### ISSUE TITLE
Get Solr to (testably) reindex in a Jenkins container running in production mode

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1112]
@icarito has set up a Jenkins system to boot containers for testing and staging. We're going to set up a branch in this repository called `solr` and get a Jenkins container to build on any push to that branch. 

I'll take on the next steps:

## THE PLAN

* [x] create "solr" branch which Jenkins will build - http://staging.laboratoriopublico.org/job/Plots-Solr/
* [ ] establish some test for whether Solr is working & reindexing goes well
  * [x] check logs - reindex would be added (in the branch, or in Jenkins web config) to the Jenkins setup process? each log is saved as a build # here: http://staging.laboratoriopublico.org/job/Plots-Solr/
    * currently show a fail when reindexing errors out
    * code being worked on in this branch: https://github.com/publiclab/plots2/tree/fix_solr and in #1176
  * [ ] check http interface for actual searches on this controller: https://github.com/publiclab/plots2/blob/master/app/controllers/searches_controller.rb#L48
    * `@solr_nodes = @ssearch.notes(params[:month])` uses Solr in the searches#show action (I checked in [the model code](https://github.com/publiclab/plots2/blob/master/app/models/search_record.rb#L32))
    * (`redirect_to search_url(@search)` leads to the "show" method from CREATE or UPDATE)
    * When you POST to /searches with params: search_record[key_words]=balloon, you should get redirected to show, and then show should display correctly. But not sure this means success
  * [ ]  direct test of `/searches/test` (new controller funciton `test` added which makes a Solr call)
  * [ ] `/test/solr/...` test of `/searches/test` as well
* [ ] use resources below to get this new branch to correctly install and reindex Solr in production mode in Jenkins
  * disable some fields to get reindex to run, then figure out how to re-enable them: https://github.com/publiclab/plots2/issues/1053

## Followup

* [ ] [searches_controller_test.rb](https://github.com/publiclab/plots2/blob/master/test/solr/searches_controller_test.rb) - figure this out later:
  * [ ] don't cause Travis to fail
  * [ ] are using embedded solr, we'll want to switch to container solr
* [ ] remove `gem 'sunspot_solr'` from Gemfile and ? Gemfile.lock
* [x] re-enable solr tests in #1203

## Resources

> "gem 'sunspot_solr' # optional pre-packaged Solr distribution for use in development" -- https://github.com/outoftime/sunspot (can remove this once we solve our problems, including getting [current solr tests](https://github.com/publiclab/plots2/tree/master/test/solr/searches_controller_test.rb) to run on the containerized solr)

https://wiki.apache.org/solr/SchemaXml
https://cwiki.apache.org/confluence/display/solr/Apache+Solr+Reference+Guide

https://github.com/sunspot/sunspot/issues/711
* fix `sunspot_rails` to v2.2.7

Two version of Solr: gem and container
Reindexing works on gem solr (version 5.x?) -- x% at least
Solr in container worked to ~38% (using core setup by gem solr?)

**Hypothesis:** core built by gem solr was reindexing in container solr, but a core created by the container solr seems to have trouble with "types" -- perhaps lacking a schema.

HOW TO generate an accurate scheme.xml AND where is it stored?

Preferred Solr version: v5.3.1 (slight update from most recent in the gem, available as pre-build container)? most recent Solr is v6.5

**Comment by icarito** [comment]
The route for a test of advanced seach is a POST from the form at https://publiclab.org/searches/new

**Comment by icarito** [comment]
There is a trail of 3 issues solved in the buld history at: http://staging.laboratoriopublico.org/job/Plots-Solr/

**Comment by icarito** [comment]
![image](https://cloud.githubusercontent.com/assets/199755/21733644/96aa5e26-d42d-11e6-94b7-f825064a4054.png)

**Comment by jywarren** [comment]
oh wow -- the error generated is automatically shown? Great work!

**Comment by icarito** [comment]
'_' 

actually, I copied those manually for quick reference - but yeah it'd be cool if it did that automatically

**Comment by icarito** [comment]
This is the latest attempt, I got up to 39.14%.
```
solr_1 | 7635792 ERROR (qtp1112280004-13) [   x:default] o.a.s.c.SolrCore org.apache.solr.common.SolrException: ERROR: [doc=DrupalNodeRevision 1] cannot set an index-time boost, unindexed or norms are omitted for field title_text: The Public Laboratory 

[################################                                                    ] [333266/851416] [ 39.14%] [03:37] [05:37] [  1533.30/s]
rake aborted! 
RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request 
Error: 'ERROR: [doc=DrupalNodeRevision 1] cannot set an index-time boost, unindexed or norms are omitted for field title_text: The Public Labo
ratory','code'=>400}} 
```

**Comment by icarito** [comment]
Trick learned, to avoid to reindex the entire database while debugging the solr schema (that is, the `searchable` block in the model):
```
RAILS_ENV=production docker-compose run web bundle exec  rake sunspot:reindex[500,DrupalNode]
```
It is possible to limit to indexing a single model. First argument is the batch size.

**Comment by jywarren** [comment]
Was it possible to disable boost for the revisions table? I could submit a
commit if that'd help.

**Comment by icarito** [comment]
Yes but now I'm looking at a different error on the same table:

```

solr_1 | Caused by: java.lang.IllegalArgumentException: Document
contains at least one immense term in field="body_text" (whose UTF8
e[0/1970]is longer than the max length 32766), all of which were
skipped.  Please correct the analyzer to not produce such terms.  The
prefix of the first immense term is: '[-27, -121, -70, -28, -70, -114,
-28, -72, -115, -27, -112, -116, -25, -102, -124, -27, -114, -97, -27,
-101, -96, -17, -68, -116, -26, -120, -111, -28, -69, -84]...', original
message: bytes can be at most 32766 in length; got 34363

```

I'm trying to slice the body_text as I did with DrupalNode, but I'm
still getting the same error.

```                                                                                                                           
body.to_s.gsub!(/[[:cntrl:]]/,'').to_s.slice(0..32500)
```

My working changes are in /srv/plots_branch1, I've not committed yet.
I posted some notes as I went along at http://pad.publiclab.org/p/wwg

**Comment by icarito** [comment]
It worked with:
`body.to_s.gsub!(/[[:cntrl:]]/,'').to_s.slice(0..2500)`
But that only indexes the beginning. In theory 32766 characters are possible but I'm not sure how it's counting (some articles have japanese or chinese which is longer than UTF8).

**Comment by jywarren** [comment]
Hmm, well let's leave a good note and we can circle back later and narrow
it down to improve the percentage of text were indexing. For now truncating
seems like a good stopgap until we get the index to complete. Thanks!

**Comment by icarito** [comment]
Agreed, I'm going to push to the fix_solr branch. I got it to index
truncated to the 10000th character.

I'm not sure if this is a design limit of Solr.

:-/

**Comment by icarito** [comment]
Solr was able to reindex as per the changes in `fix_solr` branch. Not sure what we can consider a good note, I guess we can document it? Closing this one.
