### ISSUE TITLE
Weekly Community Check-In #141 - The Domino Effect

### ISSUE THREAD

**Issue by shefali12-ab** [publiclab/plots2#11122]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## The Domino Effect

Have you ever thought of learning something new and at the very beginning you thought it would be too lengthy and time taking to complete that thing? This happens to many of us , for me it happens when I started learning the C language. In the beginning, I found it difficult to understand as I didn't read these subjects in my intermediate. But the curiosity to learn something new has pushed me to learn it and I continued practicing it daily even if someday I didn't learn anything new, I just revise the previous topics. 

Recently I read an article about The Domino effect and I just loved it, Let's now talk about the domino effect.
Domino basically refers to a small rectangular box-type object in a game. In the game, we place these dominos one after the other. and if we slightly push the first block then the first block will hit the second and second block will hit third and so on.
This same thing applies to any task that we earlier thought would be difficult to complete. If we divide our task into the smaller task and try to complete that subtask then at the end we have actually completed the task that we earlier thought to be difficult . 

### Thank you note to focus issues contributors
A big thankyou to all the contributors who have contributed to publiclab and the mentors for there constant support and guidance @Somya-Singhal @on2onyekachi @mittal-parth @PeculiarE @jywarren @TildaDares @cesswairimu .

 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

### Check-in Ideas
We are collecting a list of check-in ideas [here](https://github.com/publiclab/plots2/issues/9480). If you have any ideas please leave a comment there or if you are looking for next check-in ideas you could also browse there too.
 

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by girija0707** [comment]
Well said, dividing a huge chunk into smaller ones helps in the long run, and this applies not only for work but for pizzas too 🍕😉

**Comment by PeculiarE** [comment]
🤣 🤣 .....you made my day @girija0707 with your pizza comment. You're sooo right!

Thank you @shefali12-ab for sharing and for the mention as well. And I definitely agree with you on the importance of daily practice. Consistency is everything 🚀

**Comment by on2onyekachi** [comment]
Wow! @shefali12-ab thanks for this!

Recently, I've been working more on my infragram design improving some details and the UI from my end, fixing some bugs found in the community-toolbox repo and also helping first-timers to get started with open source. Outside the community, I'm improving my skill on codewars, and it has been going so well. codewars if actually fun when you don't get stuck!. 😀😬

**Comment by shefali12-ab** [comment]
> Wow! @shefali12-ab thanks for this!
> 
> Recently, I've been working more on my infragram design improving some details and the UI from my end, fixing some bugs found in the community-toolbox repo and also helping first-timers to get started with open source. Outside the community, I'm improving my skill on codewars, and it has been going so well. codewars if actually fun when you don't get stuck!. 😀😬

Great to hear that @on2onyekachi

**Comment by shefali12-ab** [comment]
> Well said, dividing a huge chunk into smaller ones helps in the long run, and this applies not only for work but for pizzas too 🍕😉

yup of course it applies to anything we thought to be huge like pizza 😉@girija0707

**Comment by shefali12-ab** [comment]
> 🤣 🤣 .....you made my day @girija0707 with your pizza comment. You're sooo right!
> 
> Thank you @shefali12-ab for sharing and for the mention as well. And I definitely agree with you on the importance of daily practice. Consistency is everything 🚀

yup , thank you 😀 @PeculiarE

**Comment by girija0707** [comment]
> 🤣 🤣 .....you made my day @girija0707 with your pizza comment. You're sooo right!
> 
> Thank you @shefali12-ab for sharing and for the mention as well. And I definitely agree with you on the importance of daily practice. Consistency is everything 🚀

Glad to hear that 😁🤗

**Comment by girija0707** [comment]
> > Well said, dividing a huge chunk into smaller ones helps in the long run, and this applies not only for work but for pizzas too 🍕😉
> 
> yup of course it applies to anything we thought to be huge like pizza 😉@girija0707

Indeed ☺️

**Comment by SHIVANGISINGH1** [comment]
Amazing thought @shefali12-ab 👌❤️, I myself get stuck whenever I am starting a new project, looking through all the work it just gets very overwhelming, the same happened with me at outreachy in the beginning. But I did some work regularly to complete my targets and I try to follow this strategy every time I am preparing for something. 

Thank you so much for sharing ☺️☺️❤️

**Comment by ebarry** [comment]
Love this theme! I've also heard a phrase "the first step's a doozy" about how while it can seem very hard to take a first step on something now, after that it's just one step at a time.

**Comment by shefali12-ab** [comment]
> Love this theme! I've also heard a phrase "the first step's a doozy" about how while it can seem very hard to take a first step on something now, after that it's just one step at a time.

Thank you ☺️❤️, I totally agree with you we just need to take the first step to start something new  @ebarry

**Comment by TildaDares** [comment]
Great topic @shefali12-ab. I've found out that if I think too much about how much I need to learn, I get too scared to start. Now, I try to focus on taking things one step at a time.

**Comment by shefali12-ab** [comment]
> Great topic @shefali12-ab. I've found out that if I think too much about how much I need to learn, I get too scared to start. Now, I try to focus on taking things one step at a time.

Thank you @TildaDares I'm glad to know that it inspires you :)

**Comment by shefali12-ab** [comment]
> Very well said @shefali12-ab, if we break the tasks into small chunks, it seems less difficult to complete the task and even we can properly learn each and every concept systematically. Thank you, so much for sharing!!

Thank you :)) @Somya-Singhal

**Comment by simransia** [comment]
Well written @shefali12-ab! 👌💥💛
Breaking complex overwhelming tasks into small manageable tasks and then being consistence with doing the small task is the key for doing great things with ease! And this principle applies not only to programming but to everything in life. It also reminds me of an article saying:  ⭐️ **"Reading 20 pages per day is 30 books per year. Saving $10 per day is $3,650 per year. Running 1 mile per day is 365 miles per year Becoming 1% better per day is 37% better per year!!"**. ⭐️

Hii @cesswairimu. I would love to create the next check-in . Please tell me when can I create the next one. Thank you😊

**Comment by cesswairimu** [comment]
Awesome :tada: @simransia you can open on Sunday evening or on Monday. Thanks

**Comment by illyShelly** [comment]
When the solution is so simple 🦶by 🦶by🦶  , I wonder 👀 why it is so difficult than?? We could succeed much more.

**Comment by simransia** [comment]
> Awesome 🎉 @simransia you can create on Sunday evening or on Monday. Thanks

Great to know that @cesswairimu . Thank you for informing! 👍

**Comment by cesswairimu** [comment]
Hi @simransia, feel free to open the check-in anytime today. thanks

**Comment by simransia** [comment]
> Hi @simransia, feel free to open the check-in anytime today. thanks

I have opened it @cesswairimu . Kindly go through it [here](https://github.com/publiclab/infragram/issues/412)  😊

**Comment by jywarren** [comment]
Thank you @shefali12-ab for a great check-in theme!!!

**Comment by cesswairimu** [comment]
Thanks all, closing this.
