### ISSUE TITLE
Insert link and notice of Code of Conduct into signup page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1117]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

(breaking this out from #899) 

We have a code of conduct here: https://publiclab.org/conduct which we're very proud of!

And we ought to ask people to abide by it when they sign up at: 

https://publiclab.org/signup

## Solution

We could show this text:

> By signing up, you agree to the [code of conduct](), which applies to all online and in-person spaces managed by the Public Lab community and non-profit.

The link should open in a new tab or window -- so include (`target="_blank"`) in the `<a>` tag! 

It could look like this:

![image](https://cloud.githubusercontent.com/assets/24359/21281352/ebf362d0-c3b9-11e6-9bb5-2104610abd8e.png)

The template for the "licensing agreement" is here, on these lines:

https://github.com/publiclab/plots2/blob/master/app/views/users/new.html.erb#L27-L29

The new text could go just above those, in a `<div>` of its own, copied from the existing notice. 

## Steps to Fix

- [x] claim this issue with a comment here, below, and ask any clarifying questions you need
- [x] set up a repository locally following the README instructions, and make sure that all tests pass
- [x] try to fix the issue following the steps above, but even before you're done, you can:
- [x] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [x] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by whoisjstn** [comment]
I'll take a shot at this!

**Comment by jywarren** [comment]
Great! Thank you and we're happy to help if you need it.

On Dec 16, 2016 6:59 PM, "Justin Postlewaite" <notifications@github.com>
wrote:

I'll take a shot at this!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/1117#issuecomment-267725029>,
or mute the thread

**Comment by Pk13055** [comment]
@whoisjstn Are you still working on this?

**Comment by ananyo2012** [comment]
Yeah here is the PR regarding this https://github.com/publiclab/plots2/pull/1122

**Comment by jywarren** [comment]
Accepted and complete!
