### ISSUE TITLE
add nofollow to auth links

### ISSUE THREAD

**Issue by icarito** [publiclab/plots2#11183]
![imagen](https://user-images.githubusercontent.com/199755/173498169-3e7766d9-ee5b-401b-b557-8c74468b74cf.png)
Crawlers seem to be hitting our twitter auth endpoint - lets try to find out where they are finding this link within our site and set it to _nofollow_

**Comment by jywarren** [comment]
I can take this one! https://en.wikipedia.org/wiki/Nofollow
