### ISSUE TITLE
Weekly Community Check-In #145 

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#11200]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Check-in 145:
Hi all, I am out of check-in ideas - if you have any theme we could use this week, feel free to edit and put a theme :)...otherwise we can check in with everyone. How is everyone doing?.
It is also a good time to highlight that we do collect check-in ideas [here](https://github.com/publiclab/plots2/issues/9480). If you have any ideas please leave a comment there :). Thanks all

### SoC interns:
Hi all, its great to see you get start with your projects :tada: :tada:. Rem the first few weeks can be overwhelming as you try to gather all the info and iron out your proposals so remember to be kind and patient with yourself.  Also the check-in is a good place to ask any questions you may have for the larger coding community. 

### Thank you note to contributors of the first few weeks

🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇
Thanks so much  @jywarren, @TildaDares, @PeculiarE,  @KarishmaVanwari, @anirudhprabhakaran3, @Forchapeatl, @stephaniequintana, @htinz, @nikhilnarla, @vedant-z, @stirlhoss, @christinecannon, @gunesnt, @VictoriaAjala, @z-prince, @rajvidg 
🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇
## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by jywarren** [comment]
After doing 145 of these, even though many themes are suggested by newcomers, I can't fault Cess for not having an idea for a theme! I'd love to hear how people are doing. 

I'm in Kazakhstan and Kyrgystan for a month with my partner -- visiting her family -- so I am doing really well! Eating a lot of Kazakh and Kyrgyz food, spending time with family, spending time outdoors. A much needed "retreat" and my first time traveling since the start of the pandemic. It makes me think I should schedule more such time even if not so far away, like, just spending a week in a cabin more often. ❤️

**Comment by anirudhprabhakaran3** [comment]
Hello everyone! This week, I've actually been on a trip with my friends, so I haven't been able to do much work 😬. However, it has been quite refreshing to travel in nature after such a long time. I'll share pictures on the Element chat of the scenery!

**Comment by cesswairimu** [comment]
I have been anxious lately, but I am finding ways to manage it better.. Its cold in Nairobi and we are experiencing the 6th wave, so keeping warm :coffee:  and staying indoors mostly.
Would anyone like to open like to open next week's check-in?

**Comment by stephaniequintana** [comment]
Hi, all - I know it's the end of the week, but I wanted to drop a line...
I, too, have been traveling this week. I've driven my parents to Louisiana for a Celebration of Life. It's bittersweet in that we lost someone dear to us, but we are able to see so very many that we don't get to often. It's absolutely breathtaking here. The pic doesn't do it justice, but it seems like the trees are 10 stories tall:

![IMG_3084](https://user-images.githubusercontent.com/81270711/175557227-53c1b3b3-fdb7-447b-af85-8935eb66b300.jpg)

I haven't done as much work as I would like to have, but I have a stable connection today and will make some good headway. Hope everyone has a great weekend.

**Comment by Forchapeatl** [comment]
@cesswairimu  sure , no problem.

**Comment by Forchapeatl** [comment]
sorry for your loss @stephaniequintana

**Comment by cesswairimu** [comment]
hi @Forchapeatl, please feel free to open anytime today or tomorrow. Thanks :heart:

**Comment by Forchapeatl** [comment]
Thank you @cesswairimu , here is the checkin for this [week](https://github.com/publiclab/plots2/issues/11228). Should  do I close this one?

**Comment by cesswairimu** [comment]
Yes please, thanks again
