### ISSUE TITLE
Add gitter chat button in Readme

### ISSUE THREAD

**Issue by ananyo2012** [publiclab/plots2#1121]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem
Now that publiclab has its gitter channel at https://gitter.im/publiclab/publiclab we would love to have a gitter chat button in readme.

## Solution

Add this line to add the gitter chat button in readme
```
[![Join the chat at https://gitter.im/publiclab/publiclab](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/publiclab/publiclab)
```

## Steps to Fix

- [x] claim this issue with a comment here, below, and ask any clarifying questions you need
- [x] set up a repository locally following the README instructions, and make sure that all tests pass
- [x] try to fix the issue following the steps above, but even before you're done, you can:
- [x] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [x] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by adarsh-ideal** [comment]
I want to work on this.

**Comment by jywarren** [comment]
Complete!
