### ISSUE TITLE
Weekly Community Check-In #146 - Exciting moments

### ISSUE THREAD

**Issue by Forchapeatl** [publiclab/plots2#11228]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Check-in 146:

This week share an exciting moment you have had on PublicLab. Could be a feature that you worked on that got you super excited, an Interaction you had with another collaborator, an open call that was very exciting for you, an issue that you raised that got you excited, an eureka moment you had when working on an issue, anything really.

## This week's focus Issues

These are issues that are of high priority and requests from our
large community that use the software. 

https://github.com/publiclab/plots2/labels/high-priority

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note to focus issues contributors

Thanks so muchThanks so much @jywarren, @TildaDares, @PeculiarE, @KarishmaVanwari, @anirudhprabhakaran3, @Forchapeatl, @stephaniequintana, @htinz, @nikhilnarla, @vedant-z, @stirlhoss, @christinecannon, @gunesnt, @VictoriaAjala, @z-prince, @rajvidg 🥇

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

### Check-in Ideas
We are collecting a list of check-in ideas [here](https://github.com/publiclab/plots2/issues/9480). If you have any ideas please leave a comment there or if you are looking for next check-in ideas you could also browse there too.
 

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by Forchapeatl** [comment]
you 're welcome @cesswairimu

**Comment by NARUDESIGNS** [comment]
> Thanks for the check-in @Forchapeatl. I also met @NARUDESIGNS at OSCAFEST a few months ago. It was really exciting to meet in person.

Was really nice to meet you too @TildaDares I was surprised you recognized me even though you were behind me 😊

**Comment by PeculiarE** [comment]
Thank you for the check-in @Forchapeatl!

My first ever PR on a Ruby project (both open and closed source) was right here on Public Lab. Can clearly remember how excited I was when it was approved and merged. Was walking on clouds for the rest of the day 🤣 😆

**Comment by cesswairimu** [comment]
Meeting Jeff and stekching some PL ideas and processes on a piece of paper remains one of those surreal moments for me too too hear  :smiley:   here. I missed OSCA this year, maybe I can catch you both on the next one :wink:

**Comment by NARUDESIGNS** [comment]
It's my birthday tomorrow 🎉 
I'm grateful for how far I've come and I thank you guys for being a part of my journey 🥳

**Comment by Forchapeatl** [comment]
Happy Birthday in advance @NARUDESIGNS

**Comment by jywarren** [comment]
Happy birthday Paul!!!!

**Comment by NARUDESIGNS** [comment]
> Happy Birthday in advance @NARUDESIGNS 

Thank you ❤️

**Comment by stephaniequintana** [comment]
Thanks for this check-in @Forchapeatl - even though I'm just now checking-in, I've been thinking on my exciting moments w/PL since you first posted this. It's nice reading about all the others. I especially like that so many of you got to meet in person, in many cases after working together remotely for a time - how neat that must've been!

Mine is not one specific moment, but more of a conglomeration of my excitement growing as I interacted with the community. From the responses to my very first "Hi,everyone!" in the chat room to experiencing the whirlwind and multitude of applicants and then joining a couple of the open calls where I could  actually feel the care and interest of the community...it's all been exciting and I'm glad to be a part of it :heart:

Happy Birthday, @NARUDESIGNS!!

**Comment by KarishmaVanwari** [comment]
Happy Birthday @NARUDESIGNS!! Wishing you the best!! 🎉

**Comment by cesswairimu** [comment]
Happy birthday @NARUDESIGNS :tada: :tada:

**Comment by PeculiarE** [comment]
Happy birthday, Paul!!!!! 🎉 🎉 🥳 🥳

**Comment by anirudhprabhakaran3** [comment]
Happy birthday @NARUDESIGNS !!!! 🥳 🎉

**Comment by vedant-z** [comment]
Happy Birthday @NARUDESIGNS 🎉🎉

**Comment by cesswairimu** [comment]
Would anyone like to open next week's check-in?

**Comment by NARUDESIGNS** [comment]
Thank you everyone for your wishes and I'm sorry this check-in was kinda distracted by my birthday.
❤️

**Comment by anirudhprabhakaran3** [comment]
Hi @cesswairimu , can I open this week's check-in?

**Comment by cesswairimu** [comment]
Hi @anirudhprabhakaran3, yes you can. thanks

**Comment by cesswairimu** [comment]
hi @anirudhprabhakaran3, I bet you forgot you to open the check-in and it skipped my mind. Would you like to open this coming week one?

**Comment by anirudhprabhakaran3** [comment]
Right, yes. So sorry! I'll open one right now

**Comment by anirudhprabhakaran3** [comment]
New check-in at https://github.com/publiclab/plots2/issues/11266. Thanks everyone!
