### ISSUE TITLE
Follow button on blog page only works for the first post

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#11246]
The follow button on the blog posts page only works for the first post.

You can test this by navigating to the blog page https://publiclab.org/blog and clicking the follow button.

The relevant code for this functionality:

https://github.com/publiclab/plots2/blob/bf8b4aba318a8b9c2421271ae44cc733055e1a33/app/views/tag/_subscribe_button.html.erb#L4-L21

https://github.com/publiclab/plots2/blob/bf8b4aba318a8b9c2421271ae44cc733055e1a33/app/views/tag/blog.html.erb#L67

I think the reason it only works for the first post is because the popover id is not unique for each post.

**Comment by udyanojha** [comment]
Hi @TildaDares 
May I work on this? I just finished my first Contribution here. 
Also, I think we should use **class** instead of **id** for identifying more than one element. The id attribute is intended to be used for a single element and if more than one has the same id, only 1 will be selected.
Hence, the first button responds. 
Or we can use different unique ids but it will be difficult to work with. I'm new please correct me where needed.

**Comment by udyanojha** [comment]
> Hi @TildaDares May I work on this? I just finished my first Contribution here. Also, I think we should use **class** instead of **id** for identifying more than one element. The id attribute is intended to be used for a single element and if more than one has the same id, only 1 will be selected. Hence, the first button responds. Or we can use different unique ids but it will be difficult to work with. I'm new please correct me where needed.

I'll try to reproduce this on my device and then get back!

**Comment by udyanojha** [comment]
Hi! @TildaDares ,
I hope you are doing good. 
Please refer to the above comments. 
Thanks

**Comment by Harsh3363** [comment]
Hii @TildaDares can I to fix this issue

**Comment by hsadia538** [comment]
@Harsh3363  are you still working on this?

**Comment by Harsh3363** [comment]
> @Harsh3363  are you still working on this?

Yeah

**Comment by Harsh3363** [comment]
> Hi @Harsh3363, do you need help with this?

Hey @TildaDares 
Actually my exams are going on and that's why I'm not able to finish this
Sorry for the delay

**Comment by TildaDares** [comment]
Completed in #11378
