### ISSUE TITLE
Update alert message on wiki creation/edit

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#11244]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Claim the issue by commenting. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
<details>
  <summary>💡 <i>Learn how to claim</i> 🙋</summary>
  <h3>Claiming an issue</h3>
  <p>Unless the issue is marked as reserved for someone, you can just say "I'd like to try this!" and then you've claimed it - no need to wait for someone to assign it to you. Just be sure you link your pull request (PR) to this issue so we can see where your solution is.</p>
  <p>And open one early if possible - even before you've completed it with additional commits - and others can help you figure out any issues you may face.</p>
</details>

- [ ] 📝 **Update** the file [app/controllers/wiki_controller.rb](https://github.com/publiclab/plots2/tree/main/app/controllers/wiki_controller.rb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below.

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -117,7 +117,7 @@ class WikiController < ApplicationController
       flash[:warning] = "This page is <a href='/wiki/power-tags#Locking'>locked</a>, and only <a href='/wiki/moderators'>moderators</a> can edit it."
       redirect_to @node.path
     elsif current_user &.first_time_poster
-      flash[:notice] = "You can create the wiki once your research note/question is approved by moderators. Click <a href='https://publiclab.org/notes/tester/04-23-2016/new-moderation-system-for-first-time-posters'>here</a> to learn why."
+      flash[:notice] = "You can edit this wiki once your research note/question has been approved by moderators. Click <a href='https://publiclab.org/notes/tester/04-23-2016/new-moderation-system-for-first-time-posters'>here</a> to learn why."
       redirect_to Node.find_wiki(params[:id]).path
       return
     end
@@ -135,7 +135,7 @@ class WikiController < ApplicationController
   def new
     @revision = Revision.new
     if current_user &.first_time_poster
-      flash[:notice] = "You can create the wiki once your research note/question is approved by moderators. Click <a href='https://publiclab.org/notes/tester/04-23-2016/new-moderation-system-for-first-time-posters'>here</a> to learn why."
+      flash[:notice] = "You can create a wiki once your research note/question has been approved by moderators. Click <a href='https://publiclab.org/notes/tester/04-23-2016/new-moderation-system-for-first-time-posters'>here</a> to learn why."
       redirect_to '/'
       return
     end
```

- [ ] 📝 **Update** the file [app/views/like/_like.html.erb](https://github.com/publiclab/plots2/tree/main/app/views/like/_like.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below.

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -15,7 +15,7 @@
           <i class="ml-1 ff fa fa-lock"></i>
         </a>
       <% elsif current_user && current_user.first_time_poster %>
-        <a class='btn btn-outline-secondary btn-circle btn-sm' rel="tooltip" title="You can create the wiki once your research note/question is approved by moderators. Click to learn why." data-placement="top" href="https://publiclab.org/notes/tester/04-23-2016/new-moderation-system-for-first-time-posters">
+        <a class='btn btn-outline-secondary btn-circle btn-sm' rel="tooltip" title="You can edit this wiki once your research note/question has been approved by moderators. Click to learn why." data-placement="top" href="https://publiclab.org/notes/tester/04-23-2016/new-moderation-system-for-first-time-posters">
           <i class="ml-1 ff fa fa-lock"></i>
         </a>
       <% else %>
```

- [ ] 📝 **Update** the file [test/functional/wiki_controller_test.rb](https://github.com/publiclab/plots2/tree/main/test/functional/wiki_controller_test.rb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below.

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -200,7 +200,7 @@ class WikiControllerTest < ActionController::TestCase
         id: 'chicago'
         }

-    assert_equal flash[:notice], "You can create the wiki once your research note/question is approved by moderators. Click <a href='https://publiclab.org/notes/tester/04-23-2016/new-moderation-system-for-first-time-posters'>here</a> to learn why."
+    assert_equal flash[:notice], "You can edit this wiki once your research note/question has been approved by moderators. Click <a href='https://publiclab.org/notes/tester/04-23-2016/new-moderation-system-for-first-time-posters'>here</a> to learn why."
     assert_redirected_to nodes(:place).path
   end
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below, and [reach out in our chatroom](https://publiclab.org/chat)!

**Comment by joshhayles** [comment]
@TildaDares I've read through this, but I don't see any instructions on what the issue is that I'm supposed to fix? Can you clarify what I need to do?

**Comment by XD69Z** [comment]
Hey, is the bug fixed, I am first timer and I am looking for my first contribution, and this seems like something that I can contribute towards.

**Comment by XD69Z** [comment]
Hey @TildaDares if this issue remains unresolved, can I take it up ?

**Comment by ritikadhamija** [comment]
Hi @TildaDares I would love to contribute. Let me know if this issue is still unresolved.

**Comment by rit-clone** [comment]
Hi @TildaDares I've raised this [PR](https://github.com/publiclab/plots2/pull/11292). Please let me know what further steps are required from my side. 
(P.S. sorry for the mismatch, `ritikadhamija` was my old username)
