### ISSUE TITLE
Refine Display of Email Notifications Page

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#11252]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Claim the issue by commenting. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
<details>
  <summary>💡 <i>Learn how to claim</i> 🙋</summary>
  <h3>Claiming an issue</h3>
  <p>Unless the issue is marked as reserved for someone, you can just say "I'd like to try this!" and then you've claimed it - no need to wait for someone to assign it to you. Just be sure you link your pull request (PR) to this issue so we can see where your solution is.</p>
  <p>And open one early if possible - even before you've completed it with additional commits - and others can help you figure out any issues you may face.</p>
</details>

- [ ] 📝 **Update** the file [app/views/users/settings.html.erb](https://github.com/publiclab/plots2/tree/main/app/views/users/settings.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below.

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -1,9 +1,9 @@
 <form name="settingsForm" action="/save_settings" method='post' data-remote="true" class="mx-3">
 <div class="emailSettings">
-  <h4><b><%=translation('user.settings.email_notifications_title')%></b></h4>
+  <h4><b><%=translation('users.settings.email_notifications_title')%></b></h4>
   <hr style="width: 35%;  margin-left: 0;" />

-  <h4><b><%=translation('users.settings.notified_by_email')%></b></h4>
+  <p class="notif-desc"><b><%=translation('users.settings.notified_by_email')%></b></p>

   <div style="display: inline-flex; justify-content: space-between; width: 90%;">
     <span><%=translation('users.settings.direct_comment')%> </span>
@@ -64,7 +64,8 @@
   <% end %>

   <br />
-  <h4><b><%= translation('users.settings.email_notifications')%> </b></h4>
+  <h5><b><%= translation('users.settings.email_digests')%> </b></h5>
+  <p class="notif-desc"><b><%= translation('users.settings.email_notifications')%> </b></p>

   <div style="display: inline-flex; justify-content: space-between; width: 90%;">
     <span><%=translation('users.settings.weekly_digest')%> </span>
@@ -129,7 +130,7 @@
   <h4><b>Browser Notifications</b></h4>
   <hr style="width: 35%;  margin-left: 0;" />

-  <h4><b><%=translation('users.settings.browser_notifications')%> </b></h4>
+  <p class="notif-desc"><b><%=translation('users.settings.browser_notifications')%> </b></p>

   <div style="display: inline-flex; justify-content: space-between; width: 90%;">
     <span><%=translation('users.settings.mentioned')%></span>
@@ -286,6 +287,10 @@
   .slider.round:before {
     border-radius: 50%;
   }
+
+  .notif-desc {
+    font-size: 1.1rem;
+  }
 </style>

 <script>
```

- [ ] 📝 **Update** the file [config/locales/en.yml](https://github.com/publiclab/plots2/tree/main/config/locales/en.yml) in the `plots2` repository (press the little pen Icon) and edit the line as shown below.

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -176,6 +176,7 @@ en:
       moderation_email: "Moderation emails"
       email_notifications: "Email notifications are sent for each post in topics you follow. If you prefer to receive a digest, choose one of these options:"
       email_notifications_title: "Email Notifications"
+      email_digests: "Email Digests"
       weekly_digest: "In a weekly digest"
       daily_digest: "In a daily digest"
       spam_weekly_digest: "In a weekly digest for unmoderated posts"
```

### Before & After

![screencapture-publiclab-org-settings-2022-07-06-16_37_42](https://user-images.githubusercontent.com/63427719/177590066-c5593f61-8413-4c3f-9ee2-e1439d790d98.png)

![screencapture-localhost-3000-settings-2022-07-06-16_42_52](https://user-images.githubusercontent.com/63427719/177590529-3b21787b-1732-4b1f-b6f4-945fc5de4469.png)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below, and [reach out in our chatroom](https://publiclab.org/chat)!

**Comment by oba2311** [comment]
Hey @TildaDares  - is it up for grabs now? thanks!

**Comment by aakash-kumar-gorai** [comment]
hey @TildaDares can you tell that have followed the steps correctly to create a pull request ?
