### ISSUE TITLE
Weekly Community Check-In #147 - New Technologies

### ISSUE THREAD

**Issue by anirudhprabhakaran3** [publiclab/plots2#11266]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, and contribute together so why not share our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , and your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## New Technologies.

This week, share a new technology that you came across and found really interesting. By technology, it could be anything - a framework, a language, a tool, anything!

I came across two new technologies this week, which I found very interesting. One is [Pocketbase](https://pocketbase.io/), a very lightweight, but batteries-included backend framework written for mobile and web apps. It is written in Go and has API wrappers in Javascript (a Dart one is coming soon). I'm excited to look into it!

Another technology that I came across was [Bun](https://bun.sh/). It is a new, and faster runtime for Javascript runtime, that claims to reduce serve and load times drastically and claims to be faster. Want to try it out too soon!

## This week's focus Issues

These are issues that are of high priority and requests from our large community that use the software. 

https://github.com/publiclab/plots2/labels/high-priority

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note to focus issues contributors

Thanks so much, @leighbriody @XD69Z @udyanojha @gunesnt @KarishmaVanwari @gitofbabai @anirudhprabhakaran3!

## Next Check-in
If you would like to open the next check-in, leave a comment below. We are happy to help if it's your first time

### Check-in Ideas
We are collecting a list of check-in ideas [here](https://github.com/publiclab/plots2/issues/9480). If you have any ideas please leave a comment there or if you are looking for next check-in ideas you could also browse there too.
 

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by udyanojha** [comment]
Hi everybody! 👏
First of all, I would like to thank the Public Lab community to be so welcoming and providing a seamless opportunity to get started with open source and learning in public. 😄
I got my first PR merged this week. @TildaDares thank you for actively helping us first-timers. ❤️
I learned many things about open source from Public Lab community resources. 🎯
Although I'm new in tech, I like to keep myself updated with new tech to keep the journey exciting, e.g. Bun seems really promising. Those stats ⚡
The current week's goals are: 
- To make another contribution in public.
- Setting up Public Labs by following readme (having lots of issues rvm etc 😄 I'm new)
- To keep updating my DSA / Learning journey in my repo.
- Just being a better person than what I am currently. 

I wish you all the very best! Happy Coding!

**Comment by NARUDESIGNS** [comment]
Yea I heard about this bun too but haven't looked into it yet.
Well for me I got to learn so much about Vue3 Composition API and use it at work.
Alongside I found:
- **Mockapi** which helps you create mock api endpoints with mock data.
- **Swagger UI** and **Readme**, these ones are very helpful for documenting your API.
- Lastly **Thunder Client**, this is like postman but is a VSCode extension. So you can test api endpoints without leaving your editor.

It's been fun all the way, thank you for this check-in 🚀@anirudhprabhakaran3

**Comment by rangav** [comment]
Thank you for mentioning about [Thunder Client](https://www.thunderclient.com), let me know if you have any feedback or questions on our Github page

https://github.com/rangav/thunder-client-support

**Comment by PeculiarE** [comment]
Thank you everyone for sharing these awesome technologies. Looking forward to using them in a couple of projects.

Recently, I got introduced to Metabase. It's an open-source BI (Business Intelligence) tool that serves as a viable alternative to Tableau and PowerBI. One of its exciting features is its ability to deliver automated reports to your email or a Slack channel at prescribed time intervals.

**Comment by udyanojha** [comment]
@PeculiarE I'll definitely check this. I have past experience with teaching EDA, BI practices etc using R, Python, Google Data Studio etc. Thank you for sharing.

**Comment by cesswairimu** [comment]
Thanks all for sharing;  
Not a new tool, but an extension I often use is [octotree](https://github.com/ovity/octotree) extension, comes in handy when checking out github projects and navigate between the files.

Would anyone like to open this week's check-in?

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/infragram/issues/433. Thanks all.
