### ISSUE TITLE
Weekly Community Check-In #149 - Helpful learning channels

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#11315]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

##  Helpful learning channels 

I have found myself consuming a lot of tech resources from youtube  which is funny because I wouldn't really consume any tech detailed resources from there; anyways my two favorite for conferences are  [CodeSync](https://www.youtube.com/c/CodeSync) and[ Goto conferences](https://www.youtube.com/c/GotoConferences) and for checking out a language or a framework - [Free Code Camp](https://www.youtube.com/c/Freecodecamp).  This week lets share any free tech-related channels you have found useful(doesn't have from youtube). 
Thanks all and great week ahead :rocket:  

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

### Check-in Ideas
We are collecting a list of check-in ideas [here](https://github.com/publiclab/plots2/issues/9480). If you have any ideas please leave a comment there or if you are looking for next check-in ideas you could also browse there too.
 

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by jywarren** [comment]
Hi Cess - thank you, great topic. I find that I have a lot of trouble using different libraries, as many are not well documented. I like the ability to go look at other projects and how they've used a library, as a hint to how we should do it. So I often go into other projects' issues and look around, or use the "blame" view (aka "appreciation" view haha) to see how things were done so I can see.

I also love watching people do things in video, because you can't accidentally skip a step when explaining!

**Comment by cesswairimu** [comment]
Hi all, lets leave this for another week. If anyone would like to open next week's check-in kindly comment below. Thanks all

**Comment by PeculiarE** [comment]
Thank you for sharing, Cess!

I don't have any specific youtube channels I use. And I prefer reading to watching 😀

So, most times, I first head over to read the documentation for the library, plugin, or package I want to include in the project I'm working on. Then I read Medium or Dev.to articles/tutorials to see how fellow developers have used them in their own projects. If it's looking too complicated or difficult to understand, then and only then do I switch to video explanations on Youtube 😓
