### ISSUE TITLE
Unable to Publish if note contains <form>

### ISSUE THREAD

**Issue by klie1** [publiclab/plots2#1133]
### What happened just before the problem occurred
I wrote a research note in what is now considered the legacy editor.  When I clicked "Publish", the button lights up, but it never processes to the next page:
![screen shot 2016-12-20 at 3 22 21 pm](https://cloud.githubusercontent.com/assets/20325934/21368497/6c49fbc2-c6c8-11e6-8afe-7f708f216d76.png)

### Relevant URLs

https://publiclab.org/post?&legacy=true

### PublicLab.org username

klie

### Browser, version, and operating system
Chrome Version 54.0.2840.98 (64-bit)
Mac OS El Capitan 10.11.6

**Comment by ananyo2012** [comment]
@klie1 Can you check this once more? I wasn't able to reproduce it. I was using Chrome too.

**Comment by ananyo2012** [comment]
Just to remind if you don't put a feature image an alert shows up first and you have to press the publish button again. Did the same thing happen?

**Comment by klie1** [comment]
Hi @ananyo2012 thanks for helping out :)  So, the problem wasn't actually the problem, ha.  
I isolated the issue to specific form code that I was attempting to use:

```
<form action="http://publiclab.createsend.com/t/d/s/ntigi/" method="post" id="subForm">
    <p>
        <label for="fieldName">Name (Optional):</label><br />
        <input id="fieldName" name="cm-name" type="text" />
    </p>
    <p>
        <label for="fieldEmail">Email:</label><br />
        <input id="fieldEmail" name="cm-ntigi-ntigi" type="email" required />
    </p>
    <p>
        <button type="submit">Subscribe</button>
    </p>
</form>
```

I deleted the form code and was able to post the note, so this is no longer urgent.  I'll update the title of the issue.

**Comment by jywarren** [comment]
Should we be able to include forms in posted content? If so, we can write a test for this and reproduce the error, then fix it. Also, it may be worth testing in the "Markdown mode" of the new rich editor, to try to see what error actually occurs.

**Comment by jywarren** [comment]
I think I'm going to close this, although thank you for submitting it, because typically forms are considered a security risk to allow in content posting. Thanks!!!
