### ISSUE TITLE
The "$" character causes a (Markdown?) formating error in research notes and wikis.

### ISSUE THREAD

**Issue by Fastie** [publiclab/plots2#1134]
The $ character in research notes or wiki pages is apparently being parsed as a formating code. The text immediately following the $ is displayed in a bold, italic, fancy typeface. Not all instances of the $ character cause the unwanted formating. 

Example URLs
https://publiclab.org/questions/jfd/12-14-2016/video-infragram
https://publiclab.org/wiki/replacement-parts-for-the-makerbot-replicator-1-dual

PublicLab.org username
cfastie

Browser, version, and operating system
Chrome or IE with Windows

**Comment by jywarren** [comment]
Hi Chris, thanks for reporting - theses already a fix made for this, it's just pending publication -- happy holidays! Should go up in coming days.

**Comment by jywarren** [comment]
Fixed and published now!
