### ISSUE TITLE
Notes and Questions Pages Returning Error Pages

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#11355]
Existing notes/questions and newly created notes/questions display an error page when you try to access them.

The console returns this error
`Psych::DisallowedClass (Tried to load unspecified class: ActiveSupport::HashWithIndifferentAccess):`

I get the same error on the stable server.

Cc @jywarren @cess

https://user-images.githubusercontent.com/63427719/184550306-f8485e24-cd17-428b-b517-8e8d223194d3.mov

**Comment by jywarren** [comment]
Thank you, noticed this on stable as well: https://stable.publiclab.org/notes/juan/6-5-2012/fabaoutfit-vertical-kap-and-bap

**Comment by jywarren** [comment]
I believe this relates to YAML access security rules which have broken lots of things in Rails recently: https://github.com/publiclab/plots2/pull/11274

**Comment by jywarren** [comment]
I'll try adding `ActiveSupport::HashWithIndifferentAccess` to the allowed list

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/blob/6c27608354b632772149e2fb995e68da1deec7b3/config/environments/test.rb#L47-L60

It's there - i'll copy it into production. Unfortunately we use lots of classes in YAML as part of config.

**Comment by jywarren** [comment]
Made the change here: https://github.com/publiclab/plots2/commit/befb024d8f501e0667cd718e2c09cac5fa7ef63e

We'll monitor the URL at https://stable.publiclab.org/notes/juan/6-5-2012/fabaoutfit-vertical-kap-and-bap

**Comment by jywarren** [comment]
I believe this is resolved now!

**Comment by cesswairimu** [comment]
I got this locally, adding Jeff's change on the dev config fixed it. I will make an fto for it

**Comment by cesswairimu** [comment]
fto compeleted in https://github.com/publiclab/plots2/pull/11453. closing this, thanks all
