### ISSUE TITLE
Weekly Community Check-In #150 - Congratulations Summer 2022 Outreachy Interns :tada: :confetti_ball: :tada:

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#11373]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Congratulations Summer 2022 Outreachy Interns :tada: :tada:  

Last week  was officially the last week of Outreachy this summer. This week lets celebrate the two: @PeculiarE and @stephaniequintana for the great work they have done in their projects and also within the community :tada: :tada:.  Here is[ Peculiar's initial proposal](https://publiclab.org/notes/perhisohwode/04-16-2022/outreachy-proposal-mapknitter-org-spam-management-system) and [Stephanie's](https://publiclab.org/notes/stefq1111/04-08-2022/outreachy-proposal); and here are their project planning issues https://github.com/publiclab/mapknitter/issues/1744 and https://github.com/publiclab/infragram/issues/415 respectively.  Thanks also for the ftos, the reviews and all the help you have provided around the community.
If you have any blogs or other links to your work you would like to share feel free to share below. Thanks for the great work :rocket: :rocket: and congratulations :tada: :tada: 

### Thank you note to contributors of the past few weeks

:1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal:

@KarishmaVanwari, @jywarren,  @zadilkhwaja, @iem-saad, @zexinbeh,  @opelolo, @prak30, @april-EXO @xinzhe822, @vaishnavi4444, @Manaswee03, @Harsh3363, @hyy170190, @slayeh17, @kunmi02, @hsadia538, @Forchapeatl  

:1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal:

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

### Check-in Ideas
We are collecting a list of check-in ideas [here](https://github.com/publiclab/plots2/issues/9480). If you have any ideas please leave a comment there or if you are looking for next check-in ideas you could also browse there too.
 

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by TildaDares** [comment]
Congratulations @PeculiarE & @stephaniequintana 🎉 🎉

**Comment by PeculiarE** [comment]
Thank you so much @cesswairimu, @TildaDares, @jywarren! ❤️ ❤️ ❤️ 

I've totally enjoyed working with every single one of you and collaborating with the entire community at large. it's been a rollercoaster of a ride (lots of ups, downs, and thousands of learning opportunities). I can definitely say my coding and communication skills have become way better compared to when I initially joined the community roughly 6 months ago. Once again, I'm super glad I'm part of the community and also super grateful for your mentorship, support, and friendliness....You guys are simply the best!

Hmmmm...blogs and other works? Well, I've been a bit lax with my blog  🤦‍♀️ but when I do get around to detailing my experience during these past few months, I'd definitely share it on the chat forum. Right now, Jeff and I are working on a lite version of MapKnitter at https://github.com/publiclab/Leaflet.DistortableImage/issues/998. It's kinda daunting but it is crazy fun seeing our ideas become reality 😄 😄

**Comment by cesswairimu** [comment]
Congratulations again you both. Thanks all
