### ISSUE TITLE
Display rich editor when editing a research note

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1141]
We now default to the rich editor on https://publiclab.org/post (needs login), but not when editing a note. 

We have a switch in the controller to use the rich editor:

https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb#L154

We should now reverse this, so that the rich editor is default, and the legacy editor is only used if the URL includes `params[:legacy]` -- as we've done here:

https://github.com/publiclab/plots2/blob/master/app/controllers/editor_controller.rb#L34

We should display a notice on the edit page inviting authors to use the legacy editor, too, placing this line just before the `render` line in the controller:

```ruby
    flash.now[:notice] = "This is the new rich editor. For the legacy editor, <a href='/notes/edit/#{@node.id}?#{request.env['QUERY_STRING']}&legacy=true'>click here</a>."
```

These changes will break some tests, most likely, but that's a good thing -- it'll confirm that we've made the changes. When submitting a pull request for this, observe the tests fail, then I'm happy to help you adjust the tests to the new behavior. 

Thanks!

**Comment by ryzokuken** [comment]
@jywarren perhaps I could pick this one up?

**Comment by jywarren** [comment]
Super!

**Comment by ryzokuken** [comment]
@jywarren should i wrap the code for the rich text editor in a `rich` method as the sample you provided does?

**Comment by jywarren** [comment]
No, now that it's a default, I think just the conditional switch that already exists should be fine. Thanks!
