### ISSUE TITLE
Solr tests failing as of recent Solr containerization changes

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1142]
A recent set of changes by @icarito to move solr testing into an independent container (#1109) causes this in the TravisCI tests:

`Sunspot::Solr::Server::JavaMissing: You need a Java Runtime Environment to run the Solr server`

I see this was happening in the original merge here: 

https://travis-ci.org/publiclab/plots2/builds/184358852

These two dependencies were removed:

`openjdk-7-jre openjdk-7-jdk`

I'll move them back in, momentarily!

**Comment by jywarren** [comment]
If #1143 passes, I'll merge it and we'll figure out how to separate out Java later, once we can get it to not fail TravisCI tests. No big rush on this, though, @icarito, don't let me interrupt any holidays you may be taking!

**Comment by icarito** [comment]
Thanks Jeff,

I'll take this up again this week possibly today.

Regards,

Sebastian
