### ISSUE TITLE
Rubocop - Use string interpolation

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#11429]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from underrepresented groups in free and open-source software!

We know that the process of creating a pull request is one of the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Claim the issue by commenting. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
<details>
  <summary>💡 <i>Learn how to claim</i> 🙋</summary>
  <h3>Claiming an issue</h3>
  <p>Unless the issue is marked as reserved for someone, you can just say "I'd like to try this!" and then you've claimed it - no need to wait for someone to assign it to you. Just be sure you link your pull request (PR) to this issue so we can see where your solution is.</p>
  <p>And open one early if possible - even before you've completed it with additional commits - and others can help you figure out any issues you may face.</p>
</details>

- [ ] 📝 **Update** the file [app/controllers/admin_controller.rb](https://github.com/publiclab/plots2/blob/main/app/controllers/admin_controller.rb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below.

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -15,7 +15,7 @@ class AdminController < ApplicationController
         flash[:error] = 'Only admins can promote other users to admins.'
       end
     end
-    redirect_to '/profile/' + @user.username + '?_=' + Time.now.to_i.to_s
+    redirect_to "/profile/#{@user.username}?_=#{Time.now.to_i}"
   end

   def promote_moderator
@@ -29,7 +29,7 @@ class AdminController < ApplicationController
         flash[:error] = 'Only moderators can promote other users.'
       end
     end
-    redirect_to '/profile/' + @user.username + '?_=' + Time.now.to_i.to_s
+    redirect_to "/profile/#{@user.username}?_=#{Time.now.to_i}"
   end

   def demote_basic
@@ -43,7 +43,7 @@ class AdminController < ApplicationController
         flash[:error] = 'Only admins and moderators can demote other users.'
       end
     end
-    redirect_to '/profile/' + @user.username + '?_=' + Time.now.to_i.to_s
+    redirect_to "/profile/#{@user.username}?_=#{Time.now.to_i}"
   end

   def reset_user_password
@@ -280,7 +280,7 @@ class AdminController < ApplicationController
     else
       flash[:error] = 'Only moderators can moderate other users.'
     end
-    redirect_to '/profile/' + user.name + '?_=' + Time.now.to_i.to_s
+    redirect_to "/profile/#{user.name}?_=#{Time.now.to_i}"
   end

   def unmoderate
@@ -291,7 +291,7 @@ class AdminController < ApplicationController
     else
       flash[:error] = 'Only moderators can unmoderate other users.'
     end
-    redirect_to '/profile/' + user.name + '?_=' + Time.now.to_i.to_s
+    redirect_to "/profile/#{user.name}?_=#{Time.now.to_i}"
   end

   def ban
@@ -301,7 +301,7 @@ class AdminController < ApplicationController
     else
       flash[:error] = 'Only moderators can ban other users.'
     end
-    redirect_to '/profile/' + user.name + '?_=' + Time.now.to_i.to_s
+    redirect_to "/profile/#{user.name}?_=#{Time.now.to_i}"
   end

   def unban
@@ -312,7 +312,7 @@ class AdminController < ApplicationController
     else
       flash[:error] = 'Only moderators can unban other users.'
     end
-    redirect_to '/profile/' + user.name + '?_=' + Time.now.to_i.to_s
+    redirect_to "/profile/#{user.name}?_=#{Time.now.to_i}"
   end

   def users
@@ -359,7 +359,7 @@ class AdminController < ApplicationController
     else
       flash[:error] = 'Only admins can migrate users.'
     end
-    redirect_to '/profile/' + du.name
+    redirect_to "/profile/#{du.name}"
   end

   def queue
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in the comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming the `first-timers-only` issue. We're happy to keep it assigned to you as long as you need it if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below, and [reach out in our chatroom](https://publiclab.org/chat)!

**Comment by TildaDares** [comment]
Reserved for @abhishek0chauhan for 24 hours!

**Comment by yuhwaa** [comment]
Hi! I'd like to work on this when it gets to be re-assigned!

**Comment by TildaDares** [comment]
Hi @yuhwaa, please leave a comment in #11105 and we’ll look for an issue for you to work on. Thank you!

**Comment by yaegareren** [comment]
I have created a pull request for this task. Kindly review it.

**Comment by NPDebs** [comment]
Hi @TildaDares .
Can I please be assigned to this issue? Thanks!

**Comment by TildaDares** [comment]
Hi @NPDebs, please leave a comment in https://github.com/publiclab/plots2/issues/11105 and we’ll look for an issue for you to work on. Thank you!

**Comment by TildaDares** [comment]
Reserved for @Ceejaycodez for 24 hours!

**Comment by Ceejaycodez** [comment]
> ###

HI @TildaDares, I would like to claim my FTO

**Comment by Ceejaycodez** [comment]
> Reserved for @Ceejaycodez for 24 hours!

Hi @TildaDares. I have submitted a pull request @ https://github.com/publiclab/plots2/pull/11531
