### ISSUE TITLE
add additional fields to JSON API calls for wiki pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1144]
@devinbalkind requested as a followup to #1069, the following fields for wiki pages:

* thumbnail image link
* full path (i.e. hyperlinkable)
* first 100 character description
* tags

These should be pretty easy; the JSON is rendered here:

https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L54

We could break that up into multiple lines, something like this:

```ruby
      format.json  {
        nodes.each do |node|
          node.path = "https://" + request.host.to_s + node.path
          node['preview'] = node.body_preview
          node['image'] = node.main_image_url if node.main_image
          node['tags'] = node.tags.collect(&:name) if node.tags
        end
        render json: nodes
      }
```

This may need to be tested, with an expansion of this test: 

https://github.com/publiclab/plots2/blob/master/test/functional/tag_controller_test.rb#L150

**Comment by Pk13055** [comment]
I would like to work on this issue; though I don't know how to test this.

**Comment by jywarren** [comment]
Hi, @Pk13055 -- i think that in the linked-to test above, you could add additional assertions of the contents of the JSON resposne -- see how the test decodes the JSON it receives back, and then checks what's inside the response? We'd want to look for each of the new fields we're appending, like `['tags']` -- make sense?

**Comment by Pk13055** [comment]
How does this look:
`
 test "tag show JSON" do

    get :show, id: tags(:spectrometer), format: 'json'

    assert :success
    assert_not_nil :tags

    json = ActiveSupport::JSON.decode(@response.body)

    assert_not_nil json
    assert :preview
    assert :image
      assert :tags
  end
'

**Comment by jywarren** [comment]
Let's just start with testing the first returned item, which will make
future code changes easier without changing what this test expects. I think
your code looks good but you should try running it to see what you get!
And/or upload a new commit and let TravisCI run tests for you.

I'm happy to help (though I'm traveling at the moment so can't always reply
immediately) and trial and error with tests is a good way to begin.  Thanks!

On Dec 28, 2016 4:07 PM, "Pratik Kamble" <notifications@github.com> wrote:

How would I iterate over the returned object?
Would it be the same format for all the assertions?

assert_equal tags(:spectrometer).notes.first.body_preview,
json.first[:preview]
assert_equal tags(:spectrometer).notes.first.main_image_url,
json.first[:image]
assert_equal tags(:spectrometer).notes.first.tags, json.first[:tags]
I think maybe the tags part might have to be handled differently? (I'm new
to tests, so any and all guidance is greatly appreciated. Also, do excuse
any redundant/trivial doubts)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/1144#issuecomment-269540951>,
or mute the thread

**Comment by devinbalkind** [comment]
What's the right URL to get this feed? I tried https://publiclab.org/tag/tool.json and the results aren't a list of tools.

**Comment by jywarren** [comment]
Tools are wiki pages, so: https://publiclab.org/wiki/tag/tool.json

It looks like we're supplying the image record, not the image URL; will file a followup issue.

**Comment by jywarren** [comment]
Here's one tool:

```
{"cached_likes":2,"changed":[],"comment":0,"comments_count":0,"created":1473964982,"drupal_node_revisions_count":12,"language":"","main_image_id":18073,"moderate":0,"nid":13450,"promote":0,"slug":"photo-monitoring","status":1,"sticky":0,"title":"Photo Monitoring","tnid":0,"translate":0,"type":"page","uid":1,"vid":28507,"path":"https://publiclab.org/wiki/photo-monitoring","preview":"Photography is a powerful and affordable way to document all kinds of environmental issues. We'll...","image":{"created_at":"2016-09-19T18:35:19Z","id":18073,"nid":13450,"notes":null,"photo_content_type":"image/png","photo_file_name":"Screenshot_2016-09-19_at_2.32.15_PM.png","photo_file_size":"2429535","remote_url":null,"title":null,"uid":1,"updated_at":"2016-09-19T18:35:21Z","version":0,"vid":0},"tags":["photo-monitoring","timelapse","tool","trapcam","trap-cam","trail-cam","activities:timelapse","upgrades:timelapse"]}
```

**Comment by devinbalkind** [comment]
Ahhh yes. Splendid! Thanks.

**Comment by jywarren** [comment]
Submitted a fix here, waiting for tests to run: https://github.com/publiclab/plots2/pull/1164/files#diff-a8eb2425ebeb0814d010864bb014e815

**Comment by jywarren** [comment]
Complete -- should go out with new code later this week. https://github.com/publiclab/plots2/pull/1164

**Comment by devinbalkind** [comment]
Can we get more characters in the "preview" field - which is the tool's description? Looks like the current count is around 100 characters. 500 would be good. Thanks.

**Comment by jywarren** [comment]
Hi, @devinbalkind - would you be willing to add a parameter to the `body_preview` method here, to make that possible? 

https://github.com/publiclab/plots2/blob/master/app/models/drupal_node_revision.rb#L127

**Comment by devinbalkind** [comment]
Tried. Let me know if that works. 

Thanks.

**Comment by jywarren** [comment]
yeah, let's discuss at the event!

**Comment by devinbalkind** [comment]
Looks like the most useful data ya'll have from a recola.org perspective is the /wiki/tag/method records. We could pull those in, display the name, image, description (character limited) and a link to your website's record. Will look more into this at some point.

**Comment by ebarry** [comment]
hey @devinbalkind http://recola.org/knowledge-api/ is down

**Comment by devinbalkind** [comment]
It's abandoned. If someone wants to use it or do something related to it let me know.

**Comment by ebarry** [comment]
ok thanks Devin.
--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net
