### ISSUE TITLE
Update ReadMe.md file to include a missing installation step

### ISSUE THREAD

**Issue by segun-codes** [publiclab/plots2#11466]
As observed by the contributor iIlyShelly (https://github.com/publiclab/plots2/issues/10844#issuecomment-1083480321) and also confirmed by me during setup, step 10 in the ReadME.md file should be preceded by running the command "bundle exec rake webpacker:install" (or alternative with similar effect) otherwise errors related to _webpack_ and _manifest.json_ are returned. To avoid wasting time trying to fix this error especially for first timers, the ReadMe.md could be updated to include the missing step.

**Comment by ayeolakenny** [comment]
can this issue be assigned to me pls?

**Comment by xiaodaiweiwei** [comment]
I can have a try on this issue.

**Comment by TildaDares** [comment]
Hi @segun-codes, that is a brilliant observation. I don’t think everyone encounters that error so what you should do is instead of adding it as a step, we can say something along the lines of 

“If you have the following error, then do this.”

That wording can be better refined though.

Thank you!

**Comment by segun-codes** [comment]
Hi @TildaDares, I observed that in a later version of the ReadMe.md file someone else had already implemented a pull request to address the issue I raised. It appears it was an older version of the README.md file that I was looking at when I generated the issue otherwise, I wouldn't have need to raise the issue in the first place.

**Comment by TildaDares** [comment]
It’s good you caught that @segun-codes. I think you can close this issue now.

Thank you!

**Comment by segun-codes** [comment]
Okay
