### ISSUE TITLE
refine gnupg2 install step

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#11478]
Follow up for: https://github.com/publiclab/plots2/pull/11465

## todo: 
 Update https://github.com/publiclab/plots2/blob/main/README.md#windows-installation where we have `sudo apt install gnupg2` to  :

"Install gnupg2 if you haven't already with:  `sudo apt install gnupg2`"

**Comment by 7malikk** [comment]
@cesswairimu i'd like to claim this task

**Comment by cesswairimu** [comment]
great, go ahead

**Comment by 7malikk** [comment]
@cesswairimu Alright, thank you, can I convert it to an FTO and take up the task?

**Comment by 7malikk** [comment]
Oh, i think @RealRichi3  already has, i'll take up the task then. Thank you
