### ISSUE TITLE
[Help wanted] Navigating to localhost:3000 after setting up server throws an error

### ISSUE THREAD

**Issue by RealRichi3** [publiclab/plots2#11471]
### Navigating to localhost:3000 after setting up server throws an error
For the standard installation, I started the server using `passenger start`, but when i navigate to http://localhost:3000 it shows an error

![image](https://user-images.githubusercontent.com/76791916/195228860-b6355db3-75ca-41d0-85ea-e7b2cabfec07.png)

I already tried `yarn install` inside the project directory but it still shows the same thing
I also tried using gitpod, the same thing happens

I expected it to show a prompt to login

### Browser, version, and operating system
Windows Subsystem for Linux  (Ubuntu - 18.04)

**Comment by xiaodaiweiwei** [comment]
Can I try on this issue? Thank you.

**Comment by RealRichi3** [comment]
No problem, i need help solving the issue

**Comment by xiaodaiweiwei** [comment]
Yes, I would try my best to solve that. Do I need to be assigned to this issue? Where could I find the exact place for the problem?

**Comment by AndroGenius-codes** [comment]
this happened to me previously because i missed a step. try opening a new work space and follow the steps one by one. in my case i think i didn't do the rake db:setup step after migrating the database. also pay close attention to the warnings you get during installation process.

**Comment by RealRichi3** [comment]
Alright, thanks

**Comment by cesswairimu** [comment]
hi @RealRichi3,  which error is being displayed on the terminal? Please share. Also I saw another issue on setup, please raise  any further installations  issues in [this installation discussion issue]( https://github.com/publiclab/plots2/issues/10844) also you might find the solutions to most of the issues there.  Thanks
