### ISSUE TITLE
Reset background image to fit container

### ISSUE THREAD

**Issue by THEDARKMAN007** [publiclab/plots2#11485]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from underrepresented groups in free and open-source software!

We know that the process of creating a pull request is one of the biggest barriers for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and look through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

 ### 🤔 What you will need to know.
 Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step
* [ ]  🙋 **Claim this issue**: Claim the issue by commenting. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

* [ ]  📝 **Update** the file [/workspace/plots2/app/assets/stylesheets/dashboard.css](https://github.com/publiclab/plots2/blob/main/app/assets/stylesheets/dashboard.css) in the `plots2` repository (press the little pen Icon) and edit the line as shown below.

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

https://github.com/publiclab/plots2/blob/a5d24839bdd1987a6a3dd2c703701d96c897b58a/app/assets/stylesheets/dashboard.css#L126-L128
Below is a "diff" showing in red (and a `-`) which code(s) to remove, and in green (and a `+`) which code(s) to add:

 ```diff
 -  background-size: cover;
 +  background-size: contain;
 +  background-repeat: no-repeat;
 +  background-position: center;
 ```
 
 * [ ]  💾 **Commit** your changes
 * [ ]  🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

 1. If you are not familiar with GitHub or the pull request model, [here is a guide you can follow](https://guides.github.com/activities/hello-world/) on how GitHub works.
 2. If you are familiar with the terminal or would like to learn to use it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
 3. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.
 
 * [ ]  🏁 **Done** Ask in the comments for a review :)
 
 ### Please keep us updated
 💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming  first-timers-only issue. We're happy to keep it assigned to you as long as you need it if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!
 
 If this happens to you, don't sweat it! Grab another open issue.
 
 ### Is someone else already working on this?
 🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.
 
 👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

 ### 🤔❓ Questions?
 Leave a comment below, and [reach out in our chatroom](https://publiclab.org/chat)!

**Comment by THEDARKMAN007** [comment]
Hello @jywarren @TildaDares @cesswairimu. this seems like a good first issue for new contributors. it's simply a CSS change to make the image fit its container and I have also hinted at what code would carry out the desired change. i would love to get your review on it. thank you very much

**Comment by TildaDares** [comment]
Hi @THEDARKMAN007, thank you for opening this issue. The image looks stretched in the image above after correction. Can you try this CSS on the background-image and let's compare?
```
background-size: contain;
background-repeat: no-repeat;
background-position: center;
```

Thank you!

**Comment by THEDARKMAN007** [comment]
okay @TildaDares

**Comment by THEDARKMAN007** [comment]
@TildaDares  pls i need your help, am having problems setting up the plot2 website. the contents of the website is incomplete with the image missing. i did this change using developer tools but on the actual website. thanks

**Comment by THEDARKMAN007** [comment]
i run it on gitpod, i follow the installation instructions and after that i log in usinng the provided username and password, but there is still no effect, most of the HTML contenets are missing including the picture corrected

**Comment by THEDARKMAN007** [comment]
hi @TildaDares, after running the plot2 project on gitpod and logging in. the image of the website is absent.

**Comment by Chelsofia** [comment]
Hi @TildaDares I would like to work on this issue.

**Comment by TildaDares** [comment]
Hi @THEDARKMAN007, you have to create a blog post with an image to test this. All you have to do is create a note with a `blog` tag.

**Comment by THEDARKMAN007** [comment]
@TildaDares, THANK YOU. that CSS code is a much better fix. I referenced it in the issue.
pls, could you review it.

**Comment by TildaDares** [comment]
Hi @THEDARKMAN007, please take a look at this issue https://github.com/publiclab/plots2/issues/11497 to know the expected format of an FTO. Thank you!

**Comment by THEDARKMAN007** [comment]
hi @TildaDares  @jywarren  my apologies, misunderstood what u said. I used the template as referenced. pls, could you review it and let me know if it's alright.

**Comment by TildaDares** [comment]
Hi @THEDARKMAN007, this looks good. Can you also the line numbers like in this issue #11481? Thank you!

**Comment by TildaDares** [comment]
Hi @Chelsofia, please go ahead. Thank you!!

**Comment by Chelsofia** [comment]
Ok @TildaDares . Thank you

**Comment by TildaDares** [comment]
Reserved for @victoria-parker

**Comment by victoria-parker** [comment]
> Reserved for @victoria-parker

Thank you @TildaDares :)
