### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by Natacha-Danbadan** [publiclab/plots2#11494]
This issue aims to improve the accessibility of the html pages (Semantic HTML) and fix the position of the scripts to Keep up with best practices. This to enable web crawlers and users in general to be able to access the site's content regardless of a user's impairment. For example  replace the nav tag with the header tag, have a main tag in all  html  files, position the script tag inside of the body as some are positioned out of the body. This would be done to all html files contained in the repo below. 

https://github.com/publiclab/plots2/tree/main/public

![screencapture-github-publiclab-plots2-blob-master-public-404-html-2022-10-16-20_58_31](https://user-images.githubusercontent.com/102672669/196055490-8f75a53f-0354-4387-bc8d-0d7aab8515bc.jpg)

**Comment by liliyao2022** [comment]
Hi, I'd like to try.

**Comment by liliyao2022** [comment]
[Replaced the nav tag with the header tag.](https://github.com/publiclab/plots2/pull/11495)

**Comment by vareenrose** [comment]
I'd like to do this for the rest of the html files

**Comment by Natacha-Danbadan** [comment]
Hi, the issue has'nt been approved yet.

**Comment by TildaDares** [comment]
Hi @Natacha-Danbadan, thank you for opening this issue. Your suggestion is very good and will help improve the accessibility of the site. Can you make a list of all the files that need this change? Thank you!

**Comment by Natacha-Danbadan** [comment]
The first set of HTML files can be found in the plots2 repo

**Comment by Natacha-Danbadan** [comment]
Yes @TildaDares I have just done that. I'm still expecting an FTO issue. Thank you ma'am.

**Comment by TildaDares** [comment]
Hi @Natacha-Danbadan, the other HTML files in here https://github.com/publiclab/plots2/tree/main/public apart from `404.html` also need this change. Maybe you could work on that. Thanks!

**Comment by Natacha-Danbadan** [comment]
Yes ma'am, I also stated the other HTML files that need to be worked on in my previous message. I'll get started on that ASAP. Thanks ma'am.

**Comment by TildaDares** [comment]
Hi @Natacha-Danbadan, setting a base tag now would mean having to change all the internal links in the project. That would be too big a task to complete before the contribution period ends. Thank you!

**Comment by Natacha-Danbadan** [comment]
Okay ma'am, duly noted.

**Comment by Natacha-Danbadan** [comment]
@TildaDares @cesswairimu @jywarren kindly help review my PR. https://github.com/publiclab/plots2/pull/11539

**Comment by Natacha-Danbadan** [comment]
@TildaDares @cesswairimu @jywarren kindly help review my PR for the Leaflet.DistortableImage Repo
https://github.com/publiclab/Leaflet.DistortableImage/pull/1234/

**Comment by amarachi-nwokocha** [comment]
Hi @Natacha-Danbadan is this issue taken id love to work on it
