### ISSUE TITLE
Styling of the footer to increase the UX 

### ISSUE THREAD

**Issue by JeffyDave** [publiclab/plots2#11522]
I feel the footer of the publiclab.org website is a little bit out of style
We could add a background colour to it and maybe style the fonts  

![Screen Shot 2022-10-20 at 4 19 25 PM](https://user-images.githubusercontent.com/106249556/196997191-fda21483-9c0d-47e5-8436-d21defa77946.png)

**Comment by 7malikk** [comment]
@TildaDares @jywarren I'd love to work on this if approved

**Comment by TildaDares** [comment]
Hi @JeffyDave, thank you for opening this issue. The code for the footer is not in this project repo so you wouldn’t be able to change it. The code is added directly to the public lab website. Thank you!

**Comment by TildaDares** [comment]
You can look at the repo for issues simple enough for first-timers to work on.

**Comment by TildaDares** [comment]
I’ll be closing this issue now. Thanks all!
