### ISSUE TITLE
Fix "pry" warning

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#11529]
Pry hasn't been updated for a while as its in dev/test env . ruby-2.7.3 is giving this  warning  for it: ` warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead`

Fix: 
- On the projects terminal run ` bundle update pry-rails`
- Commit Gemfile.lock and PR

**Comment by 7malikk** [comment]
@cesswairimu Can i give it a try?
