### ISSUE TITLE
Fix nokogumbo gem warning

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#11528]
Logs are showing this warning 
```
Fix `.rvm/gems/ruby-2.7.3/gems/nokogumbo-2.0.4/lib/nokogumbo/html5.rb:13: warning: already initialized constant Nokogiri::HTML5::HTML_NAMESPACE`
```

Could be fixed by these steps:
- run `bundle update nokogumbo`  - this will update nokogumbo to v 1.2.5 and  maybe also update nokogiri in `Gemfile.lock`
-  Remove older versions of nokogumbo and nokogiri from Gemfile.lock(optional)
-  Check if app  running okay 
- Commit and make PR to see if tests are passing

Refer to: https://github.com/sparklemotion/nokogiri/issues/2205

**Comment by 7malikk** [comment]
@cesswairimu can i give this a go?

**Comment by cesswairimu** [comment]
Go ahead @7malikk, lets leave #11529 for another contributor. thanks

**Comment by 7malikk** [comment]
> Go ahead @7malikk, let's leave #11529 for another contributor. thanks

@cesswairimu I just completed #11529 I can leave this one for another contributor

**Comment by cesswairimu** [comment]
cool :+1: thanks

**Comment by Ibom99** [comment]
@cesswairimu Can I work on this fix?

**Comment by victory-lydia** [comment]
@cesswairimu Please can I work on this issue

**Comment by cesswairimu** [comment]
@Ibom99 , you can go ahead, @victory-lydia I am still working on the warnings, I will ping you if I create a similar one. thanks

**Comment by Ibom99** [comment]
Thank you @cesswairimu i’ll get on it!

**Comment by victory-lydia** [comment]
Thanks @cesswairimu will be waiting

**Comment by Jennifer-tech** [comment]
Hi @cesswairimu please can I get an issue to work on too
