### ISSUE TITLE
Weekly Community Check-In #151 - Don’t give up ❤️

### ISSUE THREAD

**Issue by JeffyDave** [publiclab/plots2#11547]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Don’t give up ❤️ 

People from different backgrounds tend to fight a lot of personal battles while trying to grow in the tech industry. Things may be getting tougher but please don’t give up. 

Some tips to help you stay motivated
1. Remember where you came from and where you’re going. We need to remember why we have to wake up and push ourselves daily, it helps us to keep going.
2. Talk to a friend. Talking to a close friend helps lighten up the mind from these personal struggles we tend to face. If you feel you have no one to speak to please speak to me. I’ll always be here to listen. 
3. Go out a little. A lot of us are introverted because of the nature of what we do. Take some time outside the house and go for those short walks, get a drink a with a friend or play a sport from time to time.

Please take care of your mental health, it’s one of the most important factors that affect our positive output both in the work of technology and our day to day lives. Don’t ever give up on your dreams, you’ve got this!!!!

If you have any tip to help us stay motivated, you could also leave a comment on that. 

### Thank you note to focus issues contributors

Thanks so much @TildaDares @jywarren @cesswairimu for creating FTO's   🥇

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

### Check-in Ideas
We are collecting a list of check-in ideas [here](https://github.com/publiclab/plots2/issues/9480). If you have any ideas please leave a comment there or if you are looking for next check-in ideas you could also browse there too.
 

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by cesswairimu** [comment]
Lovely @JeffyDave :tada: :tada: and great theme :heart:, thanks!

**Comment by segun-codes** [comment]
Refreshing... thanks! @JeffyDave

**Comment by JeffyDave** [comment]
@TildaDares @jywarren Could you read this and tell me what you think
?

**Comment by JeffyDave** [comment]
> Lovely @JeffyDave 🎉 🎉 and great theme ❤️, thanks!

You're welcome😊😊

**Comment by TildaDares** [comment]
This is a very helpful topic @JeffyDave. I especially relate to point 3.

Thank you!

**Comment by JeffyDave** [comment]
Thank you very much everyone. You could also add something you think would give someone out here some motivation

**Comment by TildaDares** [comment]
Hi @JeffyDave, we usually leave this open until another check in issue is opened. Thank you!

**Comment by JeffyDave** [comment]
Okay

**Comment by JeffyDave** [comment]
Okay

**Comment by Josephsanya** [comment]
Thanks soooo much 
Really need this, especially to talk to someone, cos I'm struggling here. 😔

**Comment by obueto** [comment]
Thank you so much..number 1 is the goal..i really appreciate

**Comment by JeffyDave** [comment]
> Thanks soooo much Really need this, especially to talk to someone, cos I'm struggling here. 😔

I'm here, what's your twitter?

**Comment by JeffyDave** [comment]
> Thank you so much..number 1 is the goal..i really appreciate

You're Welcome.😊

**Comment by FrancoFrancis** [comment]
awesome

**Comment by jywarren** [comment]
Hi! I just wanted to say I really appreciate the theme of this post. It's such an important thing to remember! Thank you @JeffyDave!!! ❤️

**Comment by cesswairimu** [comment]
Thanks again all, closing this now
