### ISSUE TITLE
The dropdown modal window should close when the user clicks outside the modal

### ISSUE THREAD

**Issue by prius2055** [publiclab/plots2#11554]
![modal should close](https://user-images.githubusercontent.com/63577080/198907001-03587ea7-18ce-475a-9acb-0a6e624aca5c.png)

**Please describe the desired behavior.**
Describe the solution you'd like.

**Additional context (optional)**
Feel free to include any applicable: code, screenshots, or gifs.

**Comment by prius2055** [comment]
Hi @TildaDares I also think this will help improve the site. The user should be able to close the modal dropdown whenever outside of the modal window is closed.

**Comment by prius2055** [comment]
@jywarren please review @cesswairimu please review

**Comment by TildaDares** [comment]
Hi @prius2055, the code for the footer is not in the project repo. It's hardcoded into the website itself so you wouldn't be able to count it as a contribution.  We'll note this down and see what we can do about it. Thanks @prius2055!
