### ISSUE TITLE
Avoid to convert huge animations

### ISSUE THREAD

**Issue by icarito** [publiclab/plots2#1159]
![oglwmu](https://cloud.githubusercontent.com/assets/199755/21615981/ce5babea-d1ad-11e6-9999-e142e93f53f2.gif)
### What happened just before the problem occurred
Big gif animation was uploaded.

### Relevant URLs
(I've attached the culprit image)

### PublicLab.org username
icarito

(to help reproduce the issue)

### Browser, version, and operating system
Any

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by icarito** [comment]
Note this is a Denial of Service for Publiclab.Org @jywarren @ebarry

**Comment by ananyo2012** [comment]
Hmm a Google Code-in student just asked me whether he could upload a gif. It might be this one. Is the research note published yet?

**Comment by icarito** [comment]
@ananyo2012 yes please make him stop it's bringing the server down :-)

**Comment by icarito** [comment]
@jywarren can we accomodate these animations perhaps by uploading manually for now until we can fix this issue?

**Comment by icarito** [comment]
@jywarren last time something like this happened with **Mapknitter** I had a loop renicing every `convert` process but that was an ugly hack. I can look it up again.

**Comment by icarito** [comment]
The following is currently running in the server, need to restart nginx to reset process queues:

```
watch 'sudo renice -n +19 `pgrep "convert"\|"identify"`'
```

**Comment by ananyo2012** [comment]
@icarito Uh so I think it's already uploaded. So you have to tackle it this time. In case the gif doesn't show up I can ask the student to upload it somewhere else and include the link in the research note.

**Comment by icarito** [comment]
Thanks @ananyo2012  I think it's over for now. @jywarren - Since `convert` takes a long time, it's taking up the request queue so I've gone ahead and doubled its size to 200 (passenger_max_request_queue_size 200;) - it should avoid this particular queue exhaution - I could disable the queue entirely setting it to 0 but then we run the risk of exhausting memory.

**Comment by icarito** [comment]
I'll leave the renicing loop running preemptively until we have a fix for it.
Thanks everyone!

**Comment by icarito** [comment]
@ananyo2012 in any case it looks like he's still uploading images or they are queued for converting to numerous sizes.

**Comment by jywarren** [comment]
Hi, all, thanks for the quick responses. 

@icarito - what are the limits we particularly want to impose -- file size for `convert`able images? i.e.:

1. if file is an image
2. if file is > x MB

and should we:

A. reject such large files
B. accept them but not resize them (with some switching logic)
C. reject such files if they are images

Our image model is here: https://github.com/publiclab/plots2/blob/master/app/models/image.rb

Validations can be done on size: https://github.com/thoughtbot/paperclip#validations

Possibly we could skip post-processing based on file size: https://github.com/thoughtbot/paperclip#events

But it would be easier to simply forbid such large uploads; still, seeking some granularity in what we forbid. 

Thanks!

**Comment by icarito** [comment]
A priori I would not reject images, but would try to convert them in a less expensive way - like we do on MapKnitter.
It would be a good opportunity to look for alternative ways to do this?

**Comment by jywarren** [comment]
Hmm, on MapKnitter, do we cage the processes in an ionice when they're triggered? Is it possible to... somehow intercept or alias `convert` on the machine to accomplish this? I think we're much more directly calling `convert` on MapKnitter than here, where the `paperclip` library manages it.

**Comment by icarito** [comment]
By the way I found the queue full again, so passenger_max_request_queue_size to 0. And yes, it's possible to wrap `convert` - perhaps even make it into a process queue? I'll look at it.

**Comment by icarito** [comment]
By the way I wrote to the uploader at https://publiclab.org/notes/sanchittechnogeek/01-03-2017/translating-project-files-using-transifex

**Comment by jywarren** [comment]
Tried an implementation here: https://github.com/publiclab/plots2/pull/5411 but we should test it out...

**Comment by jywarren** [comment]
Filed a follow-up to try to ensure the returned URL is the original size if it's a big gif, also broke out `is_big_gif` as a method: https://github.com/publiclab/plots2/commit/76ee978074d3f03b708dd2498bc1ce5ea13aa120
