### ISSUE TITLE
Shade or highlight the grid square the center dot is inside of #1070

### ISSUE THREAD

**Issue by mridulnagpal** [publiclab/plots2#1182]
### Relevant URLs

https://

### PublicLab.org username

(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by mridulnagpal** [comment]
@jywarren  #1070 I am stuck on this one can you help please...

**Comment by mridulnagpal** [comment]
@jywarren Any updates?

**Comment by jywarren** [comment]
I'm so sorry- I missed your previous comment. I'll look over this now.

**Comment by jywarren** [comment]
Ah, so I think you could add a check for each cell at this line, which would run whenever the map is moving:

https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/locationForm.js#L48

We could compare the cell to map.getCenter(), and change the cell style if it's inside the bounds.

**Comment by mridulnagpal** [comment]
@jywarren  I didn't get it could you frame an example for the same?

**Comment by jywarren** [comment]
Sure, so why don't you start by putting some lines just after line 48 of this file:

https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/locationForm.js#L48

Leave a comment if you're not sure what goes there, but you should need to:

1. find where the center point is with something like `var center = bounds.getCenter();`
2. iterate over each cell with a `this._cells.forEach(function(cell) { ... });` function
3. for each cell, test if the center point is inside the cell, using the cell's properties, similarly to the code in this section: https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/locationForm.js#L94

Give it a try!

**Comment by jywarren** [comment]
In progress here: https://github.com/publiclab/plots2/pull/1202
