### ISSUE TITLE
Implementing mailing option for comments 

### ISSUE THREAD

**Issue by mridulnagpal** [publiclab/plots2#1183]
### Relevant URLs

https://

### PublicLab.org username

(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hi, Mridul! Was this for expanding out ideas for reply-by-email? I was thinking of:

ActionMailer
ActionJob for scheduling tasks like checking the mail.

**Comment by mridulnagpal** [comment]
@jywarren Sounds good to me. Did you checkout the bunny gem by RabbitMQ?

**Comment by jywarren** [comment]
Hm, it's interesting -- I think though for this kind of stuff, we'd only (as a starting point) need ActionMailer and ActionJob. At most basic, this could just be using ActionMailer to receive and parse incoming messages. 

We should plan out a set of tests to ensure we can actually receive emails, and then send a set of test emails through the system to prove that it's receiving and parsing through them properly. This'd be a great GSoC idea -- want to add it to https://publiclab.org/wiki/gsoc-ideas ?

**Comment by mridulnagpal** [comment]
@jywarren Yeah seems legit.

**Comment by jywarren** [comment]
Closing for now -- see https://github.com/publiclab/plots2/milestone/9 for more!
