### ISSUE TITLE
Dropdown on /post not working

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#1189]
### What happened just before the problem occurred
Hello! I went to publiclab.org/post and found the top menu bar drop downs aren't working. Any ideas?

Username: stevie

**Comment by jywarren** [comment]
Hi, this is being addressed in #1111, thanks!

**Comment by steviepubliclab** [comment]
oops sorry!

**Comment by jywarren** [comment]
no, thank you for reporting! v helpful to know things will be reported if
we haven't caught them :-)
