### ISSUE TITLE
"This is an event" checkbox value does not persist when editing already-published research note

### ISSUE THREAD

**Issue by dwblair** [publiclab/plots2#119]
After creating a research note, checking off "This is an event", and publishing it, I returned to make minor edits the note, and had to re-check that checkbox.  Not a big deal, but some folks might assume that the value would persist, and not re-check it.

**Comment by ananyo2012** [comment]
Also it would be good if the event could be directly modified using the calender. Presently if we want to change the event date we have to edit the date in the power tag itself.

**Comment by jywarren** [comment]
Closing in favor of https://github.com/publiclab/PublicLab.Editor/issues/70, thanks!
