### ISSUE TITLE
Test email notifications to author on question answers

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#1190]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

### What happened just before the problem occurred

I had posted a few questions back in December and just now went back to them and saw a few people had written in on both comments and proposed answers. I didn't get any email notifications for these and was wondering if that is a feature we have that's not working, just not working for me, or perhaps not written? 

### Relevant URLs

https://publiclab.org/questions

**Comment by jywarren** [comment]
Hi, Stevie, are you subscribed to the questions you're referring to? Thanks!

On Jan 18, 2017 10:38 AM, "steviepubliclab" <notifications@github.com>
wrote:

What happened just before the problem occurred

I had posted a few questions back in December and just now went back to
them and saw a few people had written in on both comments and proposed
answers. I didn't get any email notifications for these and was wondering
if that is a feature we have that's not working, just not working for me,
or perhaps not written?
Relevant URLs

https://publiclab.org/questions
PublicLab.org username: Stevie

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/1190>, or mute the thread

**Comment by steviepubliclab** [comment]
Oh hi again,
I had written them, do I also need to subscribe to it? Klie just tested this out for me, I did just get a notification when they tested the "comment" part of it, but not when they tested the "answers" one

**Comment by jywarren** [comment]
ah ok, you were original author. Let's write a test for this -- it'll make
a good first-timers-only issue; i'll mark this as a candidate and circle
back. Thanks!

**Comment by jywarren** [comment]
We already test that authors **can be notified** in unit tests:

https://github.com/publiclab/plots2/blob/master/test/unit/answer_mailer_test.rb#L4

But I wasn't able to find a test for whether notifications are sent on answer posting, which would be a functional test of answers controller:

https://github.com/publiclab/plots2/blob/master/test/functional/answers_controller_test.rb

On these lines, we could add a check for if a notification was sent:

https://github.com/publiclab/plots2/blob/master/test/functional/answers_controller_test.rb#L12-L16

To do that, those lines could be wrapped in this check:

```ruby
    assert_difference 'ActionMailer::Base.deliveries.size', 1 do
       # create the answer here
    end
```

This would ensure that **some** notification is sent. But is it sent to the author? 

We'd want to do:

```ruby
assert_equal node(:question).author.email, ActionMailer::Base.deliveries.last.to
```

Just after the other check. 

Once the test is added, if Stevie's observations hold up, it should fail, confirming the problem. Then we can add the appropriate code to ensure the notification is sent, which will make the test pass.

Happy to help reformat this and support anyone seeking to fix it!

**Comment by ryzokuken** [comment]
@jywarren This looks pretty doable. Would you rather have me reformat it, or should I fix this right away? I'd prefer reformatting this into a first-timers-only. Also, as I said, we could avoid having fto-candidates being solved by contributors, and rather encourage them to reformat those. This would directly affect the amount of first-timers-only issues (or so I think). What do you say?

**Comment by jywarren** [comment]
I think either way would be fine! If you prefer re-formatting, that sounds
wonderful.

**Comment by ryzokuken** [comment]
Yeah, reformatting it is, then. What are your thoughts about keeping fto-candidates open for reformatting only (atleast for existing contributors) though?

**Comment by ryzokuken** [comment]
Requesting them to reformat instead would be a pretty nice way to begin.

**Comment by jywarren** [comment]
yes, let's think of a line that makes that request that we can put as the
"preamble" for fto-candidates, but is mostly encouraging, not requiring.
Thanks, good idea!

**Comment by ryzokuken** [comment]
@jywarren Here's the reformatted counterpart: https://github.com/publiclab/plots2/issues/1198
Feel free to close this issue.
