### ISSUE TITLE
Fix build failures in CI due to package installations

### ISSUE THREAD

**Issue by ananyo2012** [publiclab/plots2#1194]
Now this is really an issue to be taken care off. Its annoying to see failing builds due to package installations. The main problem is taking place here
```
ERROR: Service 'web' failed to build: The command '/bin/sh -c apt-get update -qq && apt-get install -y bundler libmysqlclient-dev ruby-rmagick libfreeimage3 nodejs-legacy npm wget openjdk-7-jre openjdk-7-jdk' returned a non-zero code: 100
```

Need to check what is happening in Docker and why this step is failing every time.

**Comment by jywarren** [comment]
I agree, this is troubling. I had thought it was that to some degree, there may always be occasional failures when making requests to remote dependencies. So we could either:

1. cache them unless they change
2. depend on a more reliable source

Not sure to what degree either of these is possible.

**Comment by jywarren** [comment]
Some resources:

https://github.com/docker/docker/issues/3313

http://stackoverflow.com/questions/24832972/docker-apt-get-update-fails

**Comment by jywarren** [comment]
and https://docs.travis-ci.com/user/caching/

**Comment by jywarren** [comment]
that last one seems to indicate we shouldn't cache compiled binaries :-(

**Comment by jywarren** [comment]
There had been some mention of an apt cache that Travis set up, in some of the older github threads, but that seems to be missing from the latest docs. 

This will improve somewhat once we get the Solr container working, as we will no longer need to install Java. (caching our gems may also speed things up)

OK, looking at a failed build, the exact error was (for this one):

```
E: Failed to fetch http://http.debian.net/debian/pool/main/n/node-fstream/node-fstream_0.1.24-1_all.deb  Error reading from server. Remote end closed connection [IP: 5.153.231.35 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

However this looks like precisely our problem: https://github.com/docker-library/buildpack-deps/issues/40

**Comment by jywarren** [comment]
Attempting to apply final suggestions from that last `docker-library` comment in #1195. We should open/close over and over to see.

**Comment by jywarren** [comment]
OK - https://github.com/publiclab/plots2/pull/1195 seemed to work; let's see!
