### ISSUE TITLE
Impressionist counter_cache not working

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1196]
### What happened just before the problem occurred

We've installed the [impressionist gem](https://github.com/charlotte-ruby/impressionist) and are successfully counting unique impressions on pages now. But the "counter cache" setup (which would keep a column on the `node` table updated with a calculated tally of views) is not working, though that's in the code:

https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L181

We've temporarily based `node.totalcount` on the sum of `node.legacy_views + node.impressions_count`:

https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L183-L187

However, if we can get this line of the tests passing, we can re-institute the cached value, which will improve performance for node page views (notes and wikis):

https://github.com/publiclab/plots2/blob/master/test/functional/notes_controller_test.rb#L74

**Comment by imsarath** [comment]
@jywarren , Is this issue fixed ? If not, can i pick it up ?

**Comment by jywarren** [comment]
It is not fixed yet -- yes, that'd be great. Tell me if you need help diving in!

**Comment by ryzokuken** [comment]
@imsarath Are you currently working on this?
