### ISSUE TITLE
comment form breaks if you publish while previewing

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#120]
![screen shot 2014-07-21 at 9 45 56 am](https://cloud.githubusercontent.com/assets/24359/3644164/6ae0412c-10dd-11e4-8bd4-424855890c1d.png)

Then:

![screen shot 2014-07-21 at 9 46 32 am](https://cloud.githubusercontent.com/assets/24359/3644170/73a7d1da-10dd-11e4-9096-9269e5a8f4cf.png)

**Comment by ananyo2012** [comment]
Closing this as it is no longer happening.
