### ISSUE TITLE
BUG: link to "read more" reloads page

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1208]
### What happened just before the problem occurred

I was composing a post in publiclab.org/post and when adding tags in step 4, accidentally clicked the "read more" link. This should have been fine and just opened another tab, but instead it reloaded the page and i lost my work. 

![screen shot 2017-01-20 at 5 15 18 pm](https://cloud.githubusercontent.com/assets/161439/22167410/2469198a-df34-11e6-939c-31ec1b351219.png)

### Relevant URLs

https://publiclab.org/post

### PublicLab.org username

liz
(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by ryzokuken** [comment]
@ebarry Would slightly changing the link's behaviour to open the corresponding page in another tab work for us? That'll be an easy fix. Other solutions would either cut down on the functionality of the link or seriously complicate the workflow. I'm not sure we'd need either of those.

**Comment by ryzokuken** [comment]
@jywarren It's strange that in my local instance, the link is dead. It unnecessarily reloads the page while not performing any functionality at all. `<a href="">Read more »</a>`

**Comment by ebarry** [comment]
Yes Ujjwal that would work perfectly.

On Jan 21, 2017 2:22 AM, "Ujjwal Sharma" <notifications@github.com> wrote:

@jywarren <https://github.com/jywarren> It's strange that in my local
instance, the link is dead. It unnecessarily reloads the page while not
performing any functionality at all. <a href="">Read more »</a>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/1208#issuecomment-274245862>,
or mute the thread

**Comment by ryzokuken** [comment]
@ebarry Why not remove the link altogether? (atleast for now) Now that we know it doesn't really perform any function and just ends up reloading the page. Dunno, maybe I'm missing something here.

**Comment by ebarry** [comment]
the link could be removed or set to point to https://publiclab.org/tags

--

+1 336-269-1539
@lizbarry <http://twitter.com/lizbarry>

**Comment by ryzokuken** [comment]
@jywarren @ebarry maybe this will do? https://github.com/publiclab/PublicLab.Editor/pull/89

**Comment by ebarry** [comment]
Oooo looks great as far as I can tell from just reading it!
