### ISSUE TITLE
BUG: "event" posts don't generate correct power tags

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1209]
### What happened just before the problem occurred

I posted an event https://publiclab.org/notes/liz/01-20-2017/edgi-foia-event-at-cuny-in-new-york-city-online#comments but it showed up as a regular post, not as an event with the RSVP feature. 

While composing this post, i choose "post an event" from the dropdown, however, the published event did not include the powertags "event:rsvp" and "date:YYYY-MM-DD". I had to look up what those tags were on https://publiclab.org/wiki/power-tags#Automated+power+tags,+not+for+manual+adding and add them myself with the actual date.

### Relevant URLs

See above! Thanks :)

### PublicLab.org username

liz
(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hi, Liz - you found a bug, thank you -- however please don't re-add the events tag until we figure this out; i found that it broke both the new-york-city and gulf-coast wiki pages (strangely). I removed it and they work now; i'll write a test to isolate this problem and fix it over the weekend. 

Thanks! The error was:

```
Completed 500 Internal Server Error in 4716.8ms

ActionView::Template::Error (invalid date):
    5:       <% events = @node.power_tags('events') %>
    6:       <% events.each do |power_tag| %>
    7:         <% Tag.find_nodes_by_type_with_all_tags(["event",power_tag]).sort_by{|a| a.changed}.each do |node| %>
    8:           <li><a href="<%= node.path %>"><i class="fa fa-calendar"></i><% if node.has_power_tag('date') %> <b><%= DateTime.strptime(node.power_tag('date'),'%m-
%d-%Y').to_date.to_s(:long) %></b><% end %> <%= node.title %></a></li>
    9:         <% end %>
    10:       <% end %>
    11:       <% if events.length == 0 %><li><%= t('sidebar._events.no_events') %></li><% end %>
  app/views/sidebar/_events.html.erb:8:in `strptime'
```

**Comment by ryzokuken** [comment]
@jywarren Any idea what would be causing this to happen? I'd look more into this as well.

**Comment by jywarren** [comment]
I think we should try adding tags to a page with invalid date formatting, like `date:bad` and rendering the page in a functional test, and then writing some way to catch the bad date. This should solve it in a testable way.

**Comment by ryzokuken** [comment]
`DateTime.strptime(node.power_tag('date')`
@jywarren Is this piece of code raising the error? 

If so, then perhaps we could add another condition to `<% if node.has_power_tag('date') %>` to render it only if it's a valid date. Would a simple regex suffice? Something like `utils.isValidDate()`? Sorry if utility functions don't work that way in Rails, but I'm sure you got the point.

**Comment by jywarren** [comment]
Yes, that's it. I think it would be really valuable to try, in a test for that page:

```ruby
@node.add_tag('date:bad')

get :show, id: @node.slug

assert_response :success
```

That would go in this file: 

https://github.com/publiclab/plots2/blob/master/test/functional/wiki_controller_test.rb

**Comment by ryzokuken** [comment]
@jywarren First, I create a wiki page with invalid date formatting and have this code go thereafter? Sorry, I might be missing something here.

**Comment by ryzokuken** [comment]
@jywarren Coming back to this issue. Sorry for the delay.

**Comment by ryzokuken** [comment]
@jywarren Thanks our last little endeavour, all the tests passed. I added the test for bad formatted dates, and it fails as expected. 

```
Error: test_Pages_with_invalid_date_formatting_still_render(WikiControllerTest): ArgumentError: invalid date
test/functional/wiki_controller_test.rb:562:in `strptime'
test/functional/wiki_controller_test.rb:562:in `block in <class:WikiControllerTest>'
```

should we now try to handle this invalid date exception inside the function that calls `strptime` or inside `node.add_tag` itself? The second one sounds much better as users won't be able to add invalid dates in the first place, thus freeing us from the hassle of conditional rendering. I'm going to bed now but will do whatever you feel would be better tomorrow morning.

**Comment by jywarren** [comment]
Let's do it on tag creation. But we should manually check that when you create a note with a bad tag, you get some kind of notification. 

Let's add a validation to the tag.rb model, which should fail this line in `node.add_tag`:

https://github.com/publiclab/plots2/blob/master/app/models/drupal_node.rb#L666

**Comment by ryzokuken** [comment]
Line number 666? :stuck_out_tongue: Will look into it now.
