### ISSUE TITLE
BUG: Header dropdown menus are broken on 404 error page

### ISSUE THREAD

**Issue by sjones88** [publiclab/plots2#1211]
Visit any invalid route (e.g. https://publiclab.org/invalidroute). The 404 "That page does not exist" partial loads and the dropdown menus and search form break in Chrome 54.0 on macOS Sierra. I haven't tried this with another browser or OS.

**Comment by jywarren** [comment]
Good catch! I think these are sourced from the static `/public/404.html` and similar templates, which probably have to be updated to reflect the most recent dynamically generated headers. A pain, but as headers change we do have to update the static versions (important bc the static ones are loaded without having to run Rails, so if something's broken, they are still loaded with no dynamic code having to run)

**Comment by ryzokuken** [comment]
@jywarren What exactly would need to be done in order to fix this?

**Comment by jywarren** [comment]
I believe just updating the header sections from the 500.html, 502.html,
and 404.html pages to reflect the most recent headers (as a non-logged-in
user would see them). I had simplified them somewhat as well, so it's not a
direct copy. But it should be only the header navbar sections themselves.

**Comment by jywarren** [comment]
for example:
https://github.com/publiclab/plots2/blob/master/public/404.html#L26-L166

**Comment by ryzokuken** [comment]
@jywarren Why is the 404 page not rendering the normal navbar though? The normal navbar should be put up in a partial IMO and then included in all these pages. What do you think?

**Comment by jywarren** [comment]
That'd be nice, but that would require Ruby to assemble the page instead of
just passing a static page. I don't know of workarounds, but it could bear
some research.

OK, some ideas:

https://medium.com/@tair/custom-error-pages-in-rails-you-re-doing-it-wrong-ba1d20ec31c0

this is for dynamic error pages, but for reasons in the above post, i
disagree with that approach:
https://mattbrictson.com/dynamic-rails-error-pages

The third thought it that we could dramatically simplify the headers on
error pages, and simply show the error and have a single link back to the
PL home `/` instead of trying to keep each of these pages in sync with the
dynamic header.

I guess I prefer this last solution!

**Comment by ryzokuken** [comment]
@jywarren I would look into the post and try to do what's best to solve this issue. (Hopefully, permanently)

**Comment by ryzokuken** [comment]
@jywarren I guess I should start working on simplifying the static pages, then?

**Comment by jywarren** [comment]
I think that's a good idea! Perhaps we could simply remove all of the items besides the words `Public Lab` -- people can get back to the front page and just navigate from there. 

This could also be a good FTO?

**Comment by ryzokuken** [comment]
@jywarren yes. Would it be okay if I made an FTO tomorrow morning?

**Comment by jywarren** [comment]
oh of course, just suggesting. Many thanks!

**Comment by meganft** [comment]
Hi @jywarren is this still a pending issue?

**Comment by jywarren** [comment]
Hi, this is, but I think we need to more clearly specify what we want to do -- 

> strip almost all links out of the navbar except the **Public Lab**

This could be a good first step, though, and if you can upload a screenshot with your pull request, that would be great!

On the other hand, there are also lots of great issues to be tackled that are a little more organized, at:

https://github.com/publiclab/plots2/labels/first-timers-only

https://github.com/publiclab/plots2/labels/fto-candidates

Thanks!

**Comment by meganft** [comment]
Thanks! I went ahead and did some work on it so I will screenshot my PR to see if it's in the direction you were thinking.

**Comment by jywarren** [comment]
Thanks, @meganft!
