### ISSUE TITLE
missing historical revisions in the wiki?

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/plots2#1212]
I'm looking for older revisions to the DSK wiki page, but a revision from "February 2015" contains activity grids that clearly make it a late-2016 page:
https://publiclab.org/wiki/revisions/desktop-spectrometry-kit-3-0/21838

I can't seem to find the older historic revisions, at least on this page.

**Comment by jywarren** [comment]
thanks, we'll look into it!

On Mon, Jan 23, 2017 at 3:32 PM, mathew lippincott <notifications@github.com

**Comment by jywarren** [comment]
I'd like to create a test that checks revision pages against the timestamp
of their db record.

This may involve creation of more/better fixture data of "old" revisions
for the tests to run upon.

**Comment by jywarren** [comment]
noting hat the "raw" templates also seem to be returning old material

**Comment by jywarren** [comment]
Fix is in testing now, in #1216!
