### ISSUE TITLE
Switch from Bower to Yarn

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plots2#1215]
**NOTE: Quite a bit of the content in here is directly taken from different pages on the internet, but it's done just to make this proposal as self-contained as possible**

[Rails 5.1 ships with yarn](https://twitter.com/dhh/status/808348184481124352) also, it's now possible to use webpack on Rails using yarn, using which we could use newer JS features like classes, modules and the overall cleaner and concise syntax of ES2015. 

# Why would Yarn work for us?

1. Firstly, yarn does not use an independent package index. Rather, it fetches packages from both the `npm` and `bower` registries, thus making sure all our current packages will work just fine. 

2. Because it supports the npm registry in addition to the normal bower registry we've been utilizing, it certainly increases the amount of packages we have available to us for a certain task.

3. By making use of certain network and package hacks (like local caching of packages), yarn speeds up the downloading, installation and in general the workflow.

4. As @ananyo2012 suggested, lockfiles are helpful in projects as significant as ours, literally keeping all the developers as well as the CI and production "on the same page".

5. Because installing packages is faster with yarn, it will speed up the testing process, making the CI take significantly less time.

6. Numerous tutorials and articles on the internet regarding usage of yarn as a replacement for bower and the asset pipeline make it evident that not only is it more efficient, but also that we're not the only ones considering to use it in a rails environment.

7. Yarn was created by Facebook in a collaboration with Exponent, Google, and Tilde. It is maintained and supported by all these giants and the Javascript community in general. This was done keeping in mind that none of the present package managers were equally effective.

*I would try to keep adding more stuff here as and when they come to my mind*

# What makes Yarn cool?

## Ultra Fast

Yarn caches every package it downloads so it never needs to download it again. It also parallelizes operations to maximize resource utilization so install times are faster than ever.

## Mega Secure

Yarn uses checksums to verify the integrity of every installed package before its code is executed.

## Super Reliable

Using a detailed, but concise, lockfile format, and a deterministic algorithm for installs, Yarn is able to guarantee that an install that worked on one system will work exactly the same way on any other system.

## Offline Mode

If you've installed a package before, you can install it again without any internet connection.

## Deterministic

The same dependencies will be installed the same exact way across every machine regardless of install order.

## Network Performance

Yarn efficiently queues up requests and avoids request waterfalls in order to maximize network utilization.

## Same Packages

Install any package from npm and keep your package workflow the same.

## Network Resilience

A single request failing won't cause an install to fail. Requests are retried upon failure.

## Flat Mode

Resolve mismatching versions of dependencies to a single version to avoid creating duplicates.

**Comment by jywarren** [comment]
Hi, what would the steps for installing Yarn look like? Would it be a
simple replacement of `bower.json` plus a `yarn install` instead of `bower
install`?

**Comment by ryzokuken** [comment]
Installing yarn could be different for different distributions. As of lately, they have been working on native solutions apart from the regular `npm install -g yarn` just like one would do `npm install -g bower`.

In order to use yarn to install the dependencies, one would do `yarn` or `yarn install` instead of the regular `bower install`

**Comment by jywarren** [comment]
would changes to the bower.json file be extensive, or is it fairly similar?

**Comment by ryzokuken** [comment]
It fetches packages from the same source, so the packages would def. remain the same. 

Regarding the structure of the files, yarn uses the standard `package.json` format, because the entire Javascript community had been using npm (most people phased out bower earlier in favor of npm) so the package file is `package.json` and the modules are installed in `node_modules/` primarily to maintain npm compatibility (any npm project can use yarn out of the box). That said, the structure of both the `bower.json` and `package.json` files are quite similar. 

Example: 

1) The `bower.json` currently in use in plots2

```
{
  "name": "plots2",
  "version": "2.1",
  "dependencies": {
    "fontawesome": "~4.5.0",
    "bootstrap": "~3.2.0",
    "bootstrap-lightbox": "jbutz/bootstrap-lightbox#~0.7.0",
    "bootstrap-typeahead": "bassjobsen/Bootstrap-3-Typeahead#~4.0.0",
    "bootstrap-datepicker": "~1.6.0",
    "bootstrap-tokenfield": "~0.12.0",
    "jquery": "~1.11",
    "jquery-file-upload": "~8.1.0",
    "marked": "0.3.2",
    "ics": "nwcell/ics.js#0.1.3",
    "jsdiff": "~1.2.2",
    "flot": "~0.7",
    "leaflet": "0.7.3",
    "moment": "~2.10.6",
    "junction": "theleagueof/junction",
    "publiclab-editor": "~0.2.0",
    "leaflet-d3": "^0.3.8",
    "woofmark": "~4.2.0",
    "horsey": "3.0.0",
    "i18n-js": "^2.1.2"
  },
  "resolutions": {
    "jquery": "~2.1.0",
    "bootstrap": "~3.2.0"
  }
}
```

2) The `package.json` from one of the random projects I have been working on

```
{
  "name": "hermes",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "",
    "start": "node server",
    "build": "rimraf dist && node_modules/.bin/webpack --progress --profile --colors",
    "eslint": "eslint ."
  },
  "author": "osdc",
  "license": "GPL-3.0",
  "dependencies": {
    "moment": "^2.17.1",
    "react": "^15.0.2",
    "react-datepicker": "^0.39.0",
    "react-dom": "^15.0.2",
    "react-hot-loader": "^3.0.0-beta.2",
    "react-redux": "^4.4.5",
    "react-router": "^2.4.0",
    "react-router-redux": "^4.0.4",
    "redux": "^3.5.2",
    "svg-react-loader": "^0.3.7",
    "yarn": "^0.15.1"
  },
  "devDependencies": {
    "autoprefixer": "^6.3.6",
    "babel-core": "^6.8.0",
    "babel-eslint": "^6.0.4",
    "babel-loader": "^6.2.4",
    "babel-polyfill": "^6.8.0",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-0": "^6.5.0",
    "css-loader": "^0.23.1",
    "eslint": "^2.9.0",
    "eslint-loader": "^1.5.0",
    "eslint-plugin-react": "^5.0.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "html-webpack-plugin": "^2.16.1",
    "json-loader": "^0.5.4",
    "node-sass": "^3.4.0",
    "postcss-loader": "^0.9.1",
    "react-addons-test-utils": "^15.0.2",
    "rimraf": "^2.5.2",
    "sass-loader": "^3.2.0",
    "stats-webpack-plugin": "^0.3.1",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "webpack": "^1.13.0",
    "webpack-dev-server": "^1.14.1"
  }
}
```

**Comment by jywarren** [comment]
OK - so, we store our packages in /public/lib/, since some assets
(referenced in css files) must be directly referenced. If you can configure
yarn to store packages there, then I think you could open a PR that'd pass
pretty easily once a package.json file is prepared.

**Comment by ryzokuken** [comment]
@jywarren If we use webpack along with it, we wouldn't need to install them at a custom location as webpack resolves all the local `import`s and `include`s to the corresponding package.

**Comment by jywarren** [comment]
I really think it's important to do one step at a time - even if we combine
both into a single PR. webpack is nice, but it does add complexity.

Think about how existing contributors may have to retool if they already
have bower, if they don't have webpack, etc -- and if each step adds extra
burden or complexity to the process of contributing (have to run a webpack
command? troubleshoot it if it doesn't work out of the box?)

Also we should consider if there is a great deal of documentation and
familiarity and community around each tool. Will people be able to find
documentation and support for Yarn, webpack, as easily as they do for our
current tool choices? This is the kind of thing I want to consider at each
point.

Thank you for your research!

**Comment by ryzokuken** [comment]
@jywarren Yeah, we need to keep everything in mind while considering to make such changes. I will do some more research into the projects and look around a bit more. As the community has been actively working on these projects, however, something there proves to be better support regarding such tools.

**Comment by ryzokuken** [comment]
@jywarren Closing this for now, as we have no immediate plans for making the switch.

**Comment by ryzokuken** [comment]
@jywarren I recently noticed that the bower package now throws a warning:

```
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467
```

Also, there's a big banner on bower's website that says the same. Maybe now would be a good time to start thinking about a possible upgrade path to yarn? Even npm5 is good enough, I feel.

**Comment by jywarren** [comment]
agreed!

**Comment by jywarren** [comment]
https://bower.io/blog/2017/how-to-migrate-away-from-bower/ - let's start thinking about how to break this down - what can we do to prepare, or can we make a checklist?

**Comment by ryzokuken** [comment]
One problem we noticed was that there's no way to configure npm or yarn to install modules in a custom location like we've configured bower to, and that's expected behavior for JavaScript files. Rather, we could use something like Webpack or Poi to compile all the files from `node_modules` and place the compiled minified file someplace we want.

**Comment by ryzokuken** [comment]
@jywarren Oh, I just noticed that we don't have to -- just use `Rails.application.config.assets.paths << Rails.root.join('node_modules')` in the initializers

**Comment by ryzokuken** [comment]
## List of Resources:

* https://github.com/rails/webpacker
* http://nithinbekal.com/posts/yarn-rails/
* https://sheerdevelopment.com/posts/using-yarn-with-rails
* http://samuelmullen.com/articles/replacing-the-rails-asset-pipeline-with-webpack-and-yarn/

**Comment by jywarren** [comment]
So what's a checklist here?

* [ ] install yarn in container configs (docker-compose.yml?)
* [ ] run [bower-away](https://github.com/sheerun/bower-away) to make a flat bower file
* [ ] check in new `package.json` file that's generated
* [ ] run tests

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/pull/2659

**Comment by jywarren** [comment]
OK, it's running tests...  -- any help with this appreciated!

**Comment by jywarren** [comment]
This was completed!!! Closing - thanks!
