### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by matyushkin** [publiclab/plots2#1218]
I can not log into my profile as in [this question](https://github.com/publiclab/spectral-workbench/issues/232).

I enter the password, I see window 1 (in the screenshot), click YES, but after the transition to following page, I am not in the system. (screenshot 2) I see again "login" (not my nickname)

PublicLab.org username: levamatyushkin
Browser, version, and operating system: Chrome 55.0.2883.87 on Windows 10

![2017-01-25_23-18-00](https://cloud.githubusercontent.com/assets/4839771/22307686/16f9f8e4-e355-11e6-9e10-47184919556f.png)
![2017-01-25_23-18-29](https://cloud.githubusercontent.com/assets/4839771/22307688/19985834-e355-11e6-8ee0-581f58103088.png)

**Comment by jywarren** [comment]
Hmm, can you give it a try in an Incognito window, to see if there are
caching issues at play here?

I believe the cause is different than in the referenced issue, since we
resolved that particular bug. Hopefully once we check out the cache, I can
go into the logs to track what's happening. Sorry for the trouble and thank
you for reporting it!

**Comment by matyushkin** [comment]
I just tried it in incognito mode, but the situation is persistent (earlier I tryied to clear the cache and use other browsers (Firefox, Edge, etc.), but saw the same). Thank you for you attention!

**Comment by jywarren** [comment]
OK! I'll have a moment to dig through the logs tonight or mid-day tomorrow.
Thank you for your patience.

**Comment by jywarren** [comment]
Hi, I belive I found the issue -- your account was still pointed at
http://publiclab.org, not https:// -- i fixed that -- can you try again?

**Comment by matyushkin** [comment]
Oh yes, great! Thank you very much.

**Comment by jywarren** [comment]
awesome - thank you too!
