### ISSUE TITLE
drag and drop prompt in the edittor going down behind publish button in mobile view

### ISSUE THREAD

**Issue by djmgit** [publiclab/plots2#1239]
When viewing the mobile version of the site, the drag and drop prompt is going behind the publish button. As a result of which the entire label 'Drag & drop to add an image or file, or choose one' cannot be viewed properly. The container should be made responsive, that is the height of the container should increase when the screen width reduces

**Comment by djmgit** [comment]
A screen shot of the problem : 
![screenshot from 2017-02-07 01-43-45](https://cloud.githubusercontent.com/assets/16368427/22664493/f107908e-ecd6-11e6-9bc6-1d79ba432bf9.png)

**Comment by jywarren** [comment]
great catch! reading your PR now. Thank you!
