### ISSUE TITLE
Dropdown menu not dropping, chrom & firefox on mac

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/plots2#1250]
I'm trying to access the dropdown menu for print/code/etc. options, but it won't open up. Same problem in Chrome and Firefox

Chrome: Version 55.0.2883.95 
Firefox: 51.0.1

![screen_shot_2017-02-07_at_3_29_34_pm](https://cloud.githubusercontent.com/assets/1203280/22716408/ceb99d46-ed4a-11e6-8110-7260dd83f060.png)

![screen shot 2017-02-07 at 3 30 07 pm](https://cloud.githubusercontent.com/assets/1203280/22716436/e6346532-ed4a-11e6-9556-e9e9cb5ec4a5.png)

**Comment by jywarren** [comment]
Hi, could you open your javascript console and paste in any errors you see here? Thank you!

**Comment by jywarren** [comment]
I believe this may be resolved now in any case!

**Comment by jywarren** [comment]
Pls reopen if you see it persisting. Thanks!

**Comment by mathewlippincott** [comment]
Yes, it appeared to be fixed as of yesterday afternoon, thanks!
