### ISSUE TITLE
suspect that usernames with dashes do not get identified by @mentions code

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#126]
such as this comment:

> looping in @Adam-Griffith for his wetland plant ID skillz

http://publiclab.org/notes/nicholas/07-19-2014/phragmites-landfill-invasion#c9597

**Comment by btbonval** [comment]
seems covered in the above reference for #116

https://github.com/publiclab/plots2/issues/116#issuecomment-68069203

Renaming that ticket to be more general and closing this ticket as it adds nothing new.
