### ISSUE TITLE
Integrate Rich Editor into "edit subsections" code

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1265]
We now have early prototype editable subsections:

https://publiclab.org/wiki/sandbox?raw=true

(testing being added in #1263)

We should be able to edit the subsections using the rich editor:

https://github.com/publiclab/PublicLab.Editor/

Similarly to how we use it here:

https://github.com/publiclab/plots2/tree/master/app/views/editor/rich.html.erb

Since it takes a lot of resources to boot up the editor, we should do it when people click the "edit" button, instead of pre-generating all the forms. 

## Code links

Right now, a set of different functions are used to break a page up into sections:

https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/wikis.js#L20

and https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/wikis/processSections.js

pre-build a form for each: https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/wikis/processSections.js

and hide all the forms until someone clicks the edit button:

https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/wikis/processSections.js#L76

**Comment by jywarren** [comment]
done in #1282

**Comment by icarito** [comment]
Wow, this looks nice. I tried it in the sandbox.
I see two issues:
 - "Expanding sections" headers don't appear to be editable.
 - "Expanding sections" are not expanding anymore. Instead they are expanded by default and clicking the expansion widget "triangle" does nothing.
 - While probably useful, it may be confusing to have more than one or two rich editor subsections open at once.
Let me know how
