### ISSUE TITLE
lose place on website after login

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/plots2#127]
sometimes i'm not logged in, click an e-mail link to a comment on a research note, and then to comment I have to log in.  after login I'd like to be taken back to the page I was viewing.

**Comment by ebarry** [comment]
This still happens sometimes. Is it a problem in individual's browsers or is there a setting for this on the website?

**Comment by jywarren** [comment]
Which login form or link do you use when logging in?

**Comment by ebarry** [comment]
it happens most to me when i begin to edit a page and discover i'm not
actually logged in

--

@lizbarry <http://twitter.com/lizbarry>

**Comment by jywarren** [comment]
But where on the page itself do you log in? Do you click on a button that
says "log in" and where do you find that button?

**Comment by ebarry** [comment]
Ah, when i click "Edit" it automatically redirects me to [image: Inline
image 1]

--

@lizbarry <http://twitter.com/lizbarry>

**Comment by jywarren** [comment]
OK, cool, thanks. Note to self and/or developers: we need more
?return_to=foo parameters in login prompts and redirects.

**Comment by jywarren** [comment]
I believe this is complete now, but if you encounter it again, pls reopen.
