### ISSUE TITLE
I am not able to chat with the community 

### ISSUE THREAD

**Issue by JayTanna** [publiclab/plots2#1281]
### Relevant URLs

https://

### PublicLab.org username

(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by ryzokuken** [comment]
Could you provide any additional information regarding this issue?

**Comment by jywarren** [comment]
Hi, I think we saw your message but you were gone by the time we replied; sorry! I'm closing this now but if you have a specific question, please ask!
