### ISSUE TITLE
icon drop down not working on wiki pages

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#1289]
### What happened just before the problem occurred
Seems like the man icon on the right side of the page does not have the drop down function working on wiki pages. 

For example: 
- https://publiclab.org/wiki/barnraising-2015
- https://publiclab.org/wiki/frac-sand

### PublicLab.org username
stevie

**Comment by jywarren** [comment]
Fixed in https://github.com/publiclab/plots2/pull/1288, thank you for reporting!

**Comment by steviepubliclab** [comment]
Fixed? or something people are looking at somewhere else? Looks like all the dropdowns on the wiki pages aren't working right now.

**Comment by jywarren** [comment]
Fixed, at least it works for me... I just tested. Can you try in an
incognito window? Maybe you need to clear your cache?

**Comment by steviepubliclab** [comment]
Seems to be working now. Thanks!
-Stevie
