### ISSUE TITLE
Option: unpublished draft URL of research note, for initial review by participants

### ISSUE THREAD

**Issue by dwblair** [publiclab/plots2#129]
I've had some outings in which I've taken photos of participants in a meeting, and I've written up some description of the event -- and I'd like to be able to send them a link to the research note before it has been published on publiclab.org, for them to review re: privacy concerns or material content ...

**Comment by mathewlippincott** [comment]
I want to second this, and add I got the feedback from CSU students that not being able to save a draft in the Research Note UI was confusing.  A "save as draft" that saves to dashboard and allows for multiple in-progress notes was Damarquis and Paul's suggestion.

I personally copy the text of partially finished reserach notes and save in text files, but that Markdown flexibility isn't immediately obvious.

**Comment by jywarren** [comment]
I think we could do this as part of the Rich Editor project, but it depends
also on how much time we spec for that in the Dec/Jan cycle. Currently,
also, the Dashboard revision is slated first. I'll move all issues into a
set of milestones soon as well, with dates, so we can prioritize. Thanks!

On Fri, Oct 23, 2015 at 6:47 PM, mathew lippincott <notifications@github.com

**Comment by steviepubliclab** [comment]
Hi there, I'm up for bumping this up as well. I'd like to be able to "save" as to continue drafting later myself, and secondly the function of having others "edit" on the post before it goes live as well. Maybe this seems like two features?

**Comment by jywarren** [comment]
Great -- steps I can think of for starters are:

* [ ] making a `draft` status (maybe status = 3?) for nodes (not wiki pages), which makes it not visible to anyone but the author. 
* [ ] a POST parameter like `draft=true` to bypass most of [the "create" method in the notes_controller](https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb#L92) and which adds the `status = 3` when you publish
* [ ] a button to post the form with the `draft` parameter set to `true` [in the Rich Editor](https://github.com/publiclab/plots2/blob/master/app/views/editor/rich.html.erb) template
* [ ] a modification of the `with:____` coauthor tag (see [this post](https://publiclab.org/notes/partsandcrafts/12-02-2017/quick-build-raspberry-pi-microscope) which allows co-authors to see the post
* [ ] an alert at the top of a draft page that offers a shareable link to the post for sending around
* [ ] maybe a secret URL token that allows access to the post even if someone doesn't have an account?

... lots and lots of possible steps here. Stevie, any input on some of the ideas above, or want to choose a subset we could get started on?

Thanks!

**Comment by steviepubliclab** [comment]
Oh wow. This looks great. I would be excited to see any of it!
-Stevie

**Comment by Gauravano** [comment]
Hi @jywarren @steviepubliclab Can I work on this?

**Comment by steviepubliclab** [comment]
Absolutely! I'm not going to be able to offer any coding support on this
(non-coder) and jywarren is away for the week- but if you have some ideas
on moving forward please!

-Stevie

**Comment by Gauravano** [comment]
Opened in #2304
