### ISSUE TITLE
Redirects to non-existent pages should fail gracefully

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1298]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

### Problem

Currently, adding a tag like `redirect:pagename` redirects to https://publiclab.org/wiki/pagename (as a  pattern, using [power tags](https://publiclab.org/wiki/power-tags))

However, if a page with the url `pagename` doesn't exist, it crashes. I've capture this issue in a test here, in a separate branch:

https://github.com/publiclab/plots2/pull/1294/files

### Solution

To resolve this bug, edit the controller on these lines to check if the page exists first, using the conditional `DrupalNode.where(slug: @node.power_tag('redirect').length > 0`: 

https://github.com/publiclab/plots2/blob/master/app/controllers/wiki_controller.rb#L29-L37

This should resolve the test linked to above. Please submit a PR using the relevant linked-to test and the solution together. I'm happy to help you get started!

**Comment by ryzokuken** [comment]
@jywarren There's nothing extra I think this issue needs in order to be a good FTO issue (I mean, that one single line of code is enough to catch the exception) if you're okay with it, I would suggest adding FTO specific stuff to this issue itself as it doesn't need any restructuring or extra specifics that are required to solve it.
