### ISSUE TITLE
Redesign "related notes" queries to be smarter

### ISSUE THREAD

**Issue by Fastie** [publiclab/plots2#13]
On place pages (wikis) with "tabbed:notes" the "research" tab displays related research notes. These are not just notes that are tagged with that place name, and sometimes seemingly unrelated notes are included. For example, notes tagged with "chapter" always seem to be included for every place. The [Jerusalem page](http://publiclab.org/wiki/jerusalem) includes notes from lots of places.

Just curious.

**Comment by ryzokuken** [comment]
@jywarren Let's round up all these older issues and check if they're still relevant considering the various upgrades and design changes plots2 has received over the years. (Nov 2013 :P)

**Comment by ryzokuken** [comment]
@jywarren PING

**Comment by jywarren** [comment]
Oops, sorry, missed this ping! I think we could propose:

* merging https://github.com/publiclab/plots2/blob/master/app/services/typeahead_service.rb and https://github.com/publiclab/plots2/blob/master/app/services/search_service.rb
* using `SearchService.notes(input)` to find related content

However, https://github.com/publiclab/plots2/issues/1706 means we may clean out the sidebars anyways. Will ask @ebarry what to do.

**Comment by jywarren** [comment]
This merging was completed by @milaaraujo and @stefannibrasil in #3107 and related issues in #1449 -- but we are removing the sidebar content in #2493 (or potentially making them default hidden, if someone is passionate about those -- we're hoping the new tag interface can help to perform this function)

However, we are looking for ways to find tags related to any given tag, so I'm going to close this and relate it to https://github.com/publiclab/plots2/issues/3143 which has next steps and code hints. Thanks!!! (wow, closing #13... yipeee!)
