### ISSUE TITLE
Bot for Publiclab

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plots2#1303]
# Bot for Publiclab

## Why

Being an active and welcoming open source community, Publiclab requires a chatbot for a variety of purposes, including the automation of some critical but uninteresting jobs.

Some examples include:

- Normal chatbot functionality (greeting new users, fetching some important data real quick, etc) (can be expanded to add features as and when required)
  - We could add a cool karma system (freeCodeCamp's bot uses brownie points) that rewards members for helping others out by awarding them points and taking away for unhelpful behavior.
- Gitter-IRC sync (currently being handled by matrixbot)
- Automated PR reviews (currently being handled by dangerbot) (let's keep in mind that our solution would be very specific to our needs and highly extensible. Also, as it comes as a 'service' among many handled by the bot, it would fit in perfectly with all our other features)
- Automated reviews for critical documents on the Publiclab website (would need more information for this)
- Keeping track of open issues/assigned issues etc. (this would allow a user to say, print out all the current fto issues right in the chatroom, or maybe print out all the issues some other user is assigned to) (all these can be ideally done using Github's interface, but sometimes you need to demonstrate something and this may come in handy in such situations)

## How

We would most probably built such a bot (only if we choose to do so) on Node. Not only does Node sound quite natural for such an application, but it also works quite well when interacting with multiple APIs. We could host the bot on heroku or somewhere similar for a start and perhaps move to our own servers somewhere down the line (if feasible). We could sprinkle NLP at places because (I feel) it is not very important in our context. I have had experience using NLTK in Python and using it in conjunction with a chatbot running Node, but the NodeJS packages are getting better, and we could try a more native solution if we're feeling adventurous.

## Case 1: Very Simple Bot

A very simple bot would help guide users on the site and mainly automate generic community interaction.  
**Working Example:** FreeCodeCamp's famous CamperBot would (when someone would say "Hello, World!" in the chat) greet them and welcome them to their community (It was recently brought to my notice that this functionality has been removed from CamperBot). However, what we are seeking to achieve here is not as aesthetic or cosmetic as CamperBot (I mean, don't take me wrong, but just greeting newbies wouldn't really get work done. We need to actually help them get started. I realize it always depends on the person as well as their motivations, but there are certainly a few generic suggestions that apply to everyone, right?)

**Example Interactions:**  
- Person: `Hey everyone!`  
Bot: (maybe make it check a database to confirm if the person is indeed a new member in order to avoid spamming the chat channel)  
`Hey, #{Person}! Welcome to Publiclab. Click (here)[...wiki...] to access our wiki. Here's a list of few wiki articles to get you started. Feel free to contact @liz or @stevie on this chat if you have any issues.`
- Person: `Hello, World!`  
Bot: (same old drill)  
`Hello, #{Person}! Welcome to Publiclab. Please go through our (Contribution Guidelines)[...guidelines...] and (Code of Conduct)[...] in order to start contributing. If you are new to open source software, take a look at our (first-timers-only)[...] issues. Check out our (README)[...] in order to setup the project locally or if you're unable to do so, feel free to ask @jywarren to grant you free access to Cloud9. If you are still facing any problems, feel free to ask.`

## Case 2: A Slightly Advanced Bot
This slightly advanced bot would do little more than the simpler version than to provide help regarding help on very specific issues. In other words, this is just a version of the simpler bot with a lot more help cases than the utterly generic. 

**Example Interactions:**
- Person: `@bot help spectrometry`  
Bot: `Hey, #{Person}! I see you needed help with spectrometry. We have a (wiki entry for spectrometry)[...], make sure to check it out. Also, you can refer to the (Wikipedia entry for spectrometry)[...] for additional information.`
- Person: `@bot help bower`  
Bot: `Hey, #{Person}! I see you needed help with bower. Take a look into bower's (official documentation)[...]. Also there are Github wiki entries regarding setting up bower on the following of our projects:`
  - `(plots2)[...]`
  - `(PublicLab.Editor)[...]`
- Person: `@bot help bower installation`  
Bot: `Hey, #{Person}! Bower's official documentation has an (installation section)[...].`

## Case 3: A full-fledged useful bot

This is a bot that builds on top of the other two but rather than just helping members, it actually performs real functionality as it interacts with APIs (Github and plots2 API seems okay for now). What this does is add unlimited possible "features" that can be added to the bot that involve calling these APIs.

**Example Interactions:**  
- Person: `Hey, @jywarren.`  
Jeff: `Welcome to Publiclab, #{Person}. Take a look at our first-timers-only issues in order to begin contributing.`  
Jeff: `@bot issues first-timers`  
Bot: `We currently have the following first-timers-only issues:`
  - `publiclab/plots2#1301`
  - `publiclab/plots2#1198`
  - `...`
- Ujjwal: `@bot issues unassigned`  
Bot: `The following issues are currently open and unassigned: `
  - `publiclab/plots2#1340`
  - `publiclab/plots2#1339`
  - ...
- Person: `@bot pull-request add-for-review 1338`  
Bot: `Pull request publiclab/plots2#1338 has been marked as finished, and has been added for reviewal. Our reviewers team will look into it shortly. Thank you for your contribution.`
- Person: `@bot pull-request add-for-review 1338`  
Bot: `Pull request publiclab/plots2#1338 could not be added for reviewal as Danger reported the following problems with your pull request:`
  - `This pull request doesn’t link to a issue number. Please refer to the issue it fixes (if any) in the format: Fixes #123.`
  - `You have added multiple commits. It’s helpful to squash them if the individual changes are small.`
  - ...
- Liz: `@bot notes awaiting-moderation`  
Bot: `The following notes are awaiting moderation:`
  - `<title of a note linking to it... I hope you got the point>`
  - `...`

Now, before you say anything, I realize that this solution *just works*. In other words, it's almost outright hideous, but it might be the farthest we can reach without running into NLP. Therefore, the next mention has to be...

## Case 4: The bot Publiclab deserves but might not need *right now*

This is just the last bot without any features, but one minor addition that takes it to a whole new level of coolness (did I forget to mention complexity?) -- Natural Language Processing and/or Machine Learning.

**Example Interactions:**
*A sample use of NLP*  
Person: `@bot please put up 1338 for reviewal.`  
OR  
Person: `@bot, I am done working on 1338.`  
OR  
Person: `@bot, 1338 seems good to go.`  
Bot: `Pull request publiclab/plots2#1338 has been marked as finished, and has been added for reviewal. Our reviewers team will look into it shortly. Thank you for your contribution.`

*A sample use of ML (and also NLP)*    
Ujjwal: `@bot, Which issues are currently unassigned?`  
Bot: `Ujjwal, the currently unassigned issues, sorted by your preference for the tags are:`
  - `publiclab/plots2#1340`
  - `...`

I hope I was able to make my ideas clearer and make the abilities of the different types of bots concrete, hopefully making it easier for everyone to decided which one will suit our needs while still being simple enough to be worked on by a group of people as large as possible (we have worked so hard to make plots2's codebase approachable and simple, it'd be a shame if a lot of people feel alienated by the codebase of the chatbot instead. Please feel free to comment on this post for suggestions and clarifications and add any feedback and suggestions in http://pad.publiclab.org/p/bot. Thank you.

## Architecture (suggested):
- Hosting: heroku  
We will probably try to make the bot work in all environments (development, production and staging) on a container so that we don't have to make a switch later when we have expectations to fulfill.  
- Scripting Language: 
  - Node JS (because of obvious reasons)
  - Python is a solid contender (because it is one of the most popular scripting languages, also it is the only language apart from Node JS to have a Gitter module, but mainly because it has the NLTK [highly situational])
  - Ruby follows closely (because plots2 works on Ruby and I think Ruby has the best support for the Github module [somewhat situational])
- If you require any other specifications, please let me know.
---

Will keep updating this thread as and when things get clearer. Please feel free to provide feedback and suggestions.

**Comment by ryzokuken** [comment]
@jywarren Please look into this. I didn't know where else to put this up :stuck_out_tongue: I will keep adding stuff as and when it comes up.

**Comment by jywarren** [comment]
Hi, Ujjwal - I think you could share this just as it is as a research note
-- i think lots of people will have ideas and input over there, and I
certainly do!

**Comment by ryzokuken** [comment]
Could you please talk with the other maintainers and other concerned individuals and tell me if I could pick up the bot as a GSoC project? Are they even willing to give it a shot? (with or without the GSoC tag)

If they agree, then I suppose we should make a formal design document for the project and finalize a few specifics before we narrow down the choices and choose the features we'd focus on.

It would have to be a collaborative effort and you guys might need to involve the community (not the open source community but the publiclab.org community) to make some important decisions (that obviously affects them)

**Comment by jywarren** [comment]
Hi Ujjwal, I pinged some of our community development team and will put out
an email to organizers too.

**Comment by ryzokuken** [comment]
@jywarren Thanks :)

**Comment by ryzokuken** [comment]
@jywarren What's the status on this? I am sorry if I'm insisting way too much, it's just because the more I research about it, the more I want to work on it already. I wonder if I can even wait till 30th of May :stuck_out_tongue: 

But anyway, we would have to do quite a lot of work (including making a complete detailed design document) depending the outcome of this proposal.

**Comment by jywarren** [comment]
Hi, Ujjwal - i think if you could describe in detail one or two small
instances of bots in the research note with stevie and liz, like scripts,
as I had asked, I think that's a good next step. Thanks!

**Comment by ryzokuken** [comment]
I guess you mentioned scripts before. From script, do you mean like... A Python or Ruby script? Or a set of sample interactions between the bot and a user?

**Comment by jywarren** [comment]
Sorry, ambiguous vocabulary! I meant a script like in theater, and had left
an example on your research note. Can we shift the discussion over there
please? Thank you!

**Comment by ryzokuken** [comment]
@jywarren @steviepubliclab @ebarry Put this up here as well, our own Markdown renderer has not been working properly.

**Comment by jywarren** [comment]
Hi, @ryzokuken - did you want to close this and redirect it to https://github.com/publiclab/plotsbot/ ?

**Comment by ryzokuken** [comment]
Yes, definitely.

**Comment by ryzokuken** [comment]
This has been resolved. A new repository has been created for the bot at https://github.com/publiclab/plotsbot/

The bot currently lives in #publiclab-testing in OFTC IRC network

**Comment by ryzokuken** [comment]
This has been resolved. A new repository has been created for the bot at https://github.com/publiclab/plotsbot/

The bot currently lives in #publiclab-testing in OFTC IRC network
