### ISSUE TITLE
/questions page does not show any questions

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1304]
### What happened just before the problem occurred

I visited https://publiclab.org/questions/ and no questions are shown. 
Seems like when i click back and forth between "Recently asked" and "Recently answered", the yellow question blocks flicker for an instant before the page is just blank again. I wonder if this is happening for anyone else?

### Relevant URLs

https://publiclab.org/questions/

### PublicLab.org username

liz

### Browser, version, and operating system

Chrome

**Comment by ebarry** [comment]
Thanks @ryzokuken upon your encouragement i tried all the tabs again, and then restarted my computer in case the problem was somehow in me running out of memory (i really have excessive #s of tabs going right now). 

Unfortunately, the problem is persisting! 
Each tab does somewhat helpfully still seem to show the results pagination navigation.

**Comment by ryzokuken** [comment]
@ebarry Did you switch browser tabs? There are quite a few tabs (five, to be precise) in the questions list itself. Try switching them. Maybe the recently asked questions don't show up but the recently answered ones do?

**Comment by jywarren** [comment]
This is a known issue related to how the questions page uses session
storage; related:

https://github.com/publiclab/plots2/issues/897
https://github.com/publiclab/plots2/pull/929

I think we need to reorganize and break up some of these issues so this
gets solved!

**Comment by ryzokuken** [comment]
@jywarren Let's talk this over and try to fix this in parts. Maybe we could get a few FTOs out of this?

**Comment by jywarren** [comment]
Agreed. I would super love to start by creating a parallel URL based system for searching/sorting questions, so that when entering tags, instead of in the session, it's represented in the URL. 

Once we build and test that (which should be pretty simple) we can then just strip out the session stuff and default to that.

But is there a reason not to use the existing questions-by-tags listings at, for example, https://publiclab.org/questions/tag/spectrometry ?

Could we simply remove session code for initial pageview and then have the form go to these pages?

**Comment by ryzokuken** [comment]
Yeah, I mean, not storing data in the session but rather rendering the questions on-the-fly using data in the URL (sorry if I'm misunderstanding you) seems not only the easier task, but quite natural. Let's work on this.

Regarding the older listings, we would need to make a newer way of listing questions anyway, but maybe we could keep this one as well (for now, atleast). It would not be a nice thing to remove that route without notifying users of this decision and giving them a change to update all instances of such a URL. 

What do you say?

**Comment by jywarren** [comment]
Well, currently since it uses sessions, the /questions page doesn't go to a unique url, so we could just direct folks to `/questions/tag/<tagname>` using the form, right? Or do I misunderstand you?

**Comment by ryzokuken** [comment]
Okay, I got you. Also, don't know if it's happening to anyone else, but I was unable to remove the selected tags in the session by clicking on the cross. The page just re-rendered without the tag actually being removed. All these problems would be solved and searching would be further simplified should we choose to use the redirection method instead.

**Comment by ryzokuken** [comment]
@jywarren I narrowed down https://github.com/publiclab/plots2/blob/master/app/views/tag/_sorting.html.erb#L17-L48 as the part where the session-based tag selection happens. Is that it? If that's the case, maybe we could remove all the session management code and replace it with a simple redirect to `/questions/tag/#{query}` instead?

**Comment by jywarren** [comment]
Sure, that sounds great. Thanks!!!
