### ISSUE TITLE
[request] Add post tags (and other info) to mod mail

### ISSUE THREAD

**Issue by pdhixenbaugh** [publiclab/plots2#1307]
### Relevant URL
[app/mailers/admin_mailer.rb ](https://github.com/publiclab/plots2/blob/fd0b8d65c3005e082115271aa0d666a78708fd0d/app/mailers/admin_mailer.rb)

### Description
Two independent suggestions for improving mod mail:
1. Include post's tags
2. Include newly created account content

When moderators get an email notifying them of a new poster, or a post reported as spam, this email does not contain the tags attached to that post. It also doesn't contain the description or other information the user added to their profile. Tags and account descriptions can give clues about whether a post is legitimate, or spammy.

When I moderate a post, I typically visit the post to see the tags, and the account to see the description. It would save time and page loads if this information were conveyed in the email.

Feel free to consider the requests independent of each other. Thanks!

**Comment by ryzokuken** [comment]
We could make these additions to the mails being sent. Does the post contain details about (or a reference) to the user, though?

**Comment by pdhixenbaugh** [comment]
Curious about what @jywarren will say. In the meantime, you can see from this example email below that there is a reference to the user in the email, but perhaps not in the content of the post? Not sure if that helps. 

The example (redacted so the spammers won't win):
~~~

First-time poster [Bl****Cleaning](https://publiclab.org/profile/BlueSkyCarpetCleaning) has submitted their first research note!

Please help to approve it or mark it as spam: https://publiclab.org/notes/BlueSkyCarpetCleaning/03-02-2017/blue-sky-carpet-cleaning

[Approve](/foo/bar/approve-link) or [Spam](/foo/bar/spam-link)

[horizontal line]
[image, not loaded by email client]

We are ***lorem ipsem, etc*** carpets! [blob](https://publiclab.org/system/images/photos/000/019/713/original/blob)
[Approve](links) or [Spam
](links)
You received this email because you are a Public Lab community moderator

To discuss spam/abuse, forward this to moderators@publiclab.org
Check out the blog at https://publiclab.org/blog | Love our work? Become a Public Lab Sustaining Member today at https://publiclab.org/donate

~~~
(end of mod email)

**Comment by ryzokuken** [comment]
@pdhixenbaugh Thanks for the reply. I got an excellent overview of what the current layout of the mail is. I would look into the mailer's code to see what we can do.

**Comment by ryzokuken** [comment]
@pdhixenbaugh https://github.com/publiclab/plots2/blob/master/app/mailers/admin_mailer.rb#L48-L60 is the part when mail for spam posters is composed. However, it doesn't seem evident how the content is being generated. Will look more into this.

**Comment by ryzokuken** [comment]
Okay, I admit I had no idea that mailers in RoR worked exactly the same way as controllers do. Found the corresponding view (https://github.com/publiclab/plots2/blob/master/app/views/admin_mailer/notify_node_moderators.html.erb). @pdhixenbaugh please tell me what other details would be helpful in the mail. I would try make a PR right away. Thanks.

**Comment by ryzokuken** [comment]
@pdhixenbaugh I'm working on this as we speak. Meanwhile, could you please send me a screenshot of one sample mail so that I can understand exactly how it's rendering? I can see the raw HTML code but it's pretty nondescript.

**Comment by ryzokuken** [comment]
@pdhixenbaugh @jywarren Made a PR. Please look into it and give feedback if possible.

**Comment by jywarren** [comment]
Wow @ryzokuken you work fast! This looks perfect and your PR passes all tests: #1308. I'm merging it now and closing this. Thanks @pdhixenbaugh for filing it and @ryzokuken for solving it, all in one day!

**Comment by ebarry** [comment]
Awesome!

**Comment by ryzokuken** [comment]
As the PR was merged, closing this one.
@pdhixenbaugh If you require any changes or additions, please feel free to open another issue or reopen this one.
