### ISSUE TITLE
page broken at /map/northern-virginia-community-college-sterling-virginia/03-07-2014

### ISSUE THREAD

**Issue by adamdgriffith** [publiclab/plots2#131]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled.

****

http://publiclab.org/map/northern-virginia-community-college-sterling-virginia/03-07-2014

**Comment by ananyo2012** [comment]
@jywarren Can you check this once more? I think this is the reason causing #981

**Comment by jywarren** [comment]
This is probably independent -- the error could be solved by adding a `if @node.map` conditional before calling `@node.map.tms`.

Good first-timers issue!

**Comment by jywarren** [comment]
Reformatted this issue into #1026, closing this one now!
