### ISSUE TITLE
Update to Rails 4

### ISSUE THREAD

**Issue by lalithr95** [publiclab/plots2#1318]
We need to update to rails 4, as current version we use is rails 3 and doesn't have any official support from rails.

Current rails version is rails 5 and has support for 5 and 4. This can be one of the medium size projects in migration all the gems and conventions to rails 4.2 .

cc: @jywarren 

****

See http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-3-2-to-rails-4-0

## Checklist we can do already in Rails 3

- [x] change all instances of ActiveRecord `Model.find_all_by_name()` and similar to `Model.where()` 
- [x] change `assert_false` to `assert_not` in tests (we think!)

## Checklist for breaking changes

Looking through here: https://github.com/publiclab/plots2/pull/1160/files (not comprehensive):

- [x] update gems
- [x] switch all `form_for @____` to `form_for :____`
- [x] change `link_to` `confirm: ___` to `data: { confirm: ____ }`
- [x] change `.includes(:model_name)` to `.references(:table_name)` in ActiveRecord queries (see here: http://brettu.com/rails-daily-ruby-tips-117-activerecord-references-in-rails-4/)
- [x] maybe add `, multiline: true` to some validations (see above)
- [x] maybe change hash accessors from `assigns['output']` to `assigns[:output]`

**Comment by ryzokuken** [comment]
@lalithr95 This one has been in the talks for quite some time. If you are willing to work on this, please coordinate with @jywarren. We decided that the exam period (just before GSoC) would be an appropriate time to do this.

**Comment by jywarren** [comment]
In addition there is a pull request open already; perhaps that's a good
place to start but it must be rebased due to more recent changes in the
master branch.

**Comment by lalithr95** [comment]
Reference: https://github.com/publiclab/plots2/pull/1160

**Comment by ryzokuken** [comment]
@jywarren found this. Let's flesh this issue out a little by make a checklist of stuff we need? Also, let's make a `rails-4` branch and ask people to make the PRs taking that branch as base and not `master`.

**Comment by jywarren** [comment]
Again, here, we should perhaps make a checklist of things we can do before the upgrade, that are compatible with Rails 3 AND Rails 4. And then a checklist of what has to happen all at once. Make sense?

**Comment by jywarren** [comment]
OK, i made a checklist. Some of these may be possible in Rails 3... not sure which. We could get them out of the way on the `master` branch to keep a rails-4 branch smaller.

**Comment by jywarren** [comment]
This is almost complete in #1799

**Comment by jywarren** [comment]
Solved!
