### ISSUE TITLE
Add loading spinners to like btn, post btn, comment btn, etc

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#132]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

Take a look at the comment section in any of the research notes in publiclab.org. The Publish button shows a `loading...` text after you press the publish button until it gets posted. We need similar behavior for Answer comments and Like buttons in Answers as well. We want to use font awesome spinners like [this](http://fontawesome.io/icon/spinner/)

Start by inspecting the code for the Publish button for comments. Here is javascript code shows the loading text: https://github.com/publiclab/plots2/blob/master/app/views/comments/_form.html.erb#L70

You need to use html code for including the spinners and then use appropriate javascript code to make them show up during ajax load and hide it on completion like it is done here using the `beforeSend` block: https://github.com/publiclab/plots2/blob/master/app/views/comments/_form.html.erb#L68-L71

You need to similar thing for [Answer like button](https://github.com/publiclab/plots2/blob/master/app/views/questions/_answer.html.erb#L46) and [Answer Comment button](https://github.com/publiclab/plots2/blob/master/app/views/questions/_form.html.erb#L11) as well.

**Comment by ananyo2012** [comment]
testing a comment

**Comment by ananyo2012** [comment]
Reopening this one as it is still valid. I have also added this as an google code-in Task.
