### ISSUE TITLE
Problem for first timers to manage coordination between Ruby version and Gemfile Specified

### ISSUE THREAD

**Issue by MayankKashyap** [publiclab/plots2#1323]
### What happened just before the problem occurred
Since the version of Gemfile Specified is 2.1.2 and first timer's Ruby version may be different. So when we run the server it always show error **Your Ruby version is 2.3.1, but your Gemfile specified 2.1.2**
(2.3.1 is my Ruby version). And server doesn't work.

### How it can be solved.
It can be solved by removing ruby version lines from gemfile & gemfile.lock

**Comment by mridulnagpal** [comment]
@MayankKashyap Just install rvm to manage ruby versions
https://rvm.io/rvm/install

**Comment by MayankKashyap** [comment]
@mridulnagpal , I have a solution in which we don't need to install rvm, I talked with Warren and he told me that send a pull request by solving this problem

**Comment by MayankKashyap** [comment]
And today I sent an PR for that

**Comment by mridulnagpal** [comment]
Sounds cool. 👍

**Comment by ananyo2012** [comment]
Thanks for reporting this. Solution in #1324
