### ISSUE TITLE
Regex for hashtags does not detect :

### ISSUE THREAD

**Issue by Khamba** [publiclab/plots2#1331]
Hi,

The current regex for hashtags is `/(\s)\#([a-zA-Z0-9_-]+)/` which fails on tags such as question:spectrometer ([like here](https://github.com/publiclab/plots2/blob/master/test/fixtures/tags.yml#L23)).

If the core contributors think this should be changed, I want to submit a fix for this.

Thanks.

**Comment by jywarren** [comment]
Yes please! Great catch. Would it be possible to write a test for this as
well?

**Comment by Khamba** [comment]
I am on it.

**Comment by Khamba** [comment]
@jywarren Where should the tests for this go?

**Comment by jywarren** [comment]
I think we have a new test suite for constants -- and unit tests are faster
to run anyways:
https://github.com/publiclab/plots2/blob/master/test/unit/constants_test.rb

you can run just unit tests, quickly, with `rake test:units` -- does this
make sense? Thanks!

**Comment by Khamba** [comment]
Makes complete sense. Thank you very much.
