### ISSUE TITLE
API calls for tags returning "null" -- need better test to diagnose

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1332]
### What happened just before the problem occurred

https://publiclab.org/api/srch/tags?srchString=ball returned:

```
{"srchParams":{"srchString":"ball","seq":null,"showCount":null,"pageNum":null}}
```

https://github.com/publiclab/plots2/wiki/API covers this usage, as does https://publiclab.org/api/swagger_doc.json

I'm not sure what's going on here, but we do test this out here:

https://github.com/publiclab/plots2/blob/master/test/functional/restful_search_test.rb#L89

We should tighten up this test to actually check that the returned JSON contains a valid tagname, so for example `spec` as a search term should return several tagnames from our fixtures: https://github.com/publiclab/plots2/blob/master/test/fixtures/tags.yml

Once this test is created and failing (capturing the bug), we can investigate why, and fix it! 

Later, this could be adapted into https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/tagging.js#L67 and the older suggested tags query format can be deprecated.

**Comment by jywarren** [comment]
This may also, later, allow this to be updated and completed: https://github.com/publiclab/plots2/pull/595

**Comment by ffiebig** [comment]
I would like to tackle this, but I feel like I feel some guidance.

**Comment by jywarren** [comment]
Hi, @ffiebig -- thanks, we'd love your help and are happy to support you in digging into this bug. I think the first step would be to clone and boot up the project on your own system -- have you tried that yet? The README is a great place to begin there. 

Thanks!

**Comment by ffiebig** [comment]
Hey @jywarren, yes, as a matter of fact I do, in a Cloud9 workspace. 

I tried digging into it, started by trying to write a test that expects search results to be returned in the response. My test-fu is not good and I got lost when I tried to decide on how to check for the presence of the results in the response.

**Comment by jywarren** [comment]
OK - can you try adding and committing your attempted test, and I can take
a look and provide feedback? If you open a pull request I can comment
inline on your code. Thanks!
