### ISSUE TITLE
Have Dangerbot help people narrow down the output of TravisCI failures

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1336]
We have a Dangerbot script here: https://github.com/publiclab/plots2/blob/master/Dangerfile

It looks for certain content in pull requests and provides feedback -- like this:

https://github.com/publiclab/plots2/pull/1335#issuecomment-286455837

![image](https://cloud.githubusercontent.com/assets/24359/23911897/8f1e40d0-08b4-11e7-8118-0625dab211b2.png)

(http://danger.systems/)

We should see if we can get it to detect TravisCI errors, and find the error output, since it can be hard to scan through the (very long) output to find what actually happened:

Example log: https://travis-ci.org/publiclab/plots2/builds/160917149

There may already be an example script for this. But in theory, we could try to search for lines that say "Failure:" like this: https://travis-ci.org/publiclab/plots2/builds/160917149#L2067

Others may say:

```
Error: test_should_choose_i18n_for_layout/alerts(HomeControllerTest): ActionView::Template::Error: undefined method `totalcount' for nil:NilClass
app/models/drupal_node.rb:436:in `totalcount'
```

which includes more context. We could scan for those. 

It looks like the log URLs are easy to construct from the build # -- this one is, for example:

https://s3.amazonaws.com/archive.travis-ci.org/jobs/160917150/log.txt

**Comment by ananyo2012** [comment]
I can take this up. [danjer-junit](https://github.com/orta/danger-junit) enables to post failed tests in danger. It also reports jasmine test failures. Investigating how to  implement it.

**Comment by jywarren** [comment]
:-) awesome!

**Comment by geekychaser** [comment]
Hi can I work on this?

**Comment by cesswairimu** [comment]
We are using github actions now and it outputs the failures at the end of the test...easy to track now....Closing this, thanks all
