### ISSUE TITLE
comments say "error:there was a problem" but work anyways

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/plots2#134]
this happened yesterday to me as well.  Firefox 30.  it says "error:there was a problem" after I post a comment, as if it is still waiting to post.  if i reload the page my comment is there:
http://publiclab.org/notes/mathew/5-29-2012/solar-hot-air-balloons#c9732

**Comment by jywarren** [comment]
I believe this is resolved; pls reopen if not!
