### ISSUE TITLE
ability to exclude tags from an inline grid with new syntax

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1340]
## Problem

Using [inline power tags](https://publiclab.org/wiki/power-tags#Inline+power+tags), you can insert a table of content based on tags into a wiki page (see [these examples](https://publiclab.org/wiki/photo-monitoring)), with the synatx:

`[notes:balloon-mapping]`

But sometimes you want to show something with one tag, but excluding another tag, like "displaying questions about balloon mapping, but not ones that have been answered". 

## Proposed solution

We could make a new syntax, like using the `!` operator to indicate **exceptions**. That could look like this:

`[notes:question:balloon-mapping!answered]`

In this example, we'd see a list of questions on balloon mapping, but not ones that have been answered.

To do this, we'd need to look at the constructor methods for the inline grids themselves, here:

https://github.com/publiclab/plots2/blob/master/app/models/concerns/node_shared.rb#L13-L48

We could add a line after this section: https://github.com/publiclab/plots2/blob/master/app/models/concerns/node_shared.rb#L26-L29

We'd want to be sure an exclamation point would still be recognized by the regex expression here: https://github.com/publiclab/plots2/blob/master/app/models/concerns/node_shared.rb#L14

Then we could either rework the regex to separate out `$2` (the tagname) or split it with:

```ruby
if $2.includes?('!')
  tagname = $2.split('!').first
  exclude = $2.split('!').last
else
  tagname = $2
end
```

Before it gets used to form the query here:

https://github.com/publiclab/plots2/blob/master/app/models/concerns/node_shared.rb#L28

Then, if we found that there was an exclusion, we'd add an additional filter to that query, so we'd get only those which had the tag, but no answered ones, perhaps using code like this:

http://stackoverflow.com/a/42460499

For testing out Regex, please check out http://rubular.com -- very helpful!

This is quite a project, but would be really great - i'm happy to help some folks take this on!

**Comment by ryzokuken** [comment]
@jywarren: The regexp pattern works: http://regexr.com/3fiva. Will work on this.

**Comment by jywarren** [comment]
Hi, @ryzokuken -- awesome, thanks! Are you still working on this one? I know you had exams :-)

**Comment by ryzokuken** [comment]
Oh, I had totally forgotten this one. Will look into this ASAP.

**Comment by jywarren** [comment]
oh, awesome! I'm catching up on PRs and merging a bunch, checking in on issues, and just came across this. Thanks!

**Comment by jywarren** [comment]
For folks wondering, i believe this is available!

**Comment by ViditChitkara** [comment]
@jywarren May I have a go at it?

**Comment by jywarren** [comment]
Yes please! We'd really appreciate it.

On Jan 10, 2018 2:18 PM, "Vidit" <notifications@github.com> wrote:

@jywarren <https://github.com/jywarren> May I have a go at it?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/1340#issuecomment-356706842>,
or mute the thread
