### ISSUE TITLE
Error Occur "rake db:setup " Installation Guideline

### ISSUE THREAD

**Issue by niroshannrsh** [publiclab/plots2#1344]
I have followed installation guide line for setup plot2 on my local machine.
When executing `rake db:setup
`
Shows following error 

> rake aborted!
> Gem::LoadError: You have already activated rake 11.2.2, but your Gemfile requires rake 10.5.0. Prepending `bundle exec` to your command may solve this.

Then i have tried with

`bundle exec rake db:setup`

Shows following error

> /usr/local/bin/rake:23:in `load': cannot load such file -- /usr/share/rubygems-integration/all/specifications/bin/rake (LoadError)
> 	from /usr/local/bin/rake:23:in `<main>'

My operating system is Ubuntu 16.04

Any one can help me for overcome this problem .?

**Comment by Khamba** [comment]
Hi,

Have you done a bundle install in the directory?

**Comment by MayankKashyap** [comment]
Hi, please run *gem install rails*  before bundle install

**Comment by siaw23** [comment]
@niroshannrsh have you been able to fix this?

**Comment by jywarren** [comment]
Hi, all - I'm going to close this but if @niroshannrsh continues to have trouble we can re-open. Thanks!
