### ISSUE TITLE
Allow login from username or email

### ISSUE THREAD

**Issue by vaibhavgeek** [publiclab/plots2#1347]
Currently, the user can login from only his username. Email address and Username both are unique entities. I think it would be better for users if they can login from their email as well.

**Comment by siaw23** [comment]
are you planning to work on this or i should take it?

**Comment by vaibhavgeek** [comment]
I am done with the code. I will create a pull request soon enough.

**Comment by siaw23** [comment]
ok then :)

**Comment by vaibhavgeek** [comment]
@steviepubliclab Awaiting your comments.

**Comment by steviepubliclab** [comment]
Hi there,
Wow this is great. I know those who review code aren't available right now, so maybe hold tight for a bit. Really exciting though, thanks for working on this!

Best

**Comment by jywarren** [comment]
Merged, thanks!
