### ISSUE TITLE
Ruby style guide

### ISSUE THREAD

**Issue by siaw23** [publiclab/plots2#1348]
There are many violations against the Ruby style guide. Is it OK to fix these violations using tools such as Rubocop? I can slowly complete this because there are over 10K violations.

**Comment by jywarren** [comment]
Hi! Perhaps you could start with just a smaller section of code so we can
see how in depth the changes are, then gradually work up to a more
comprehensive change? Thank you!

**Comment by siaw23** [comment]
yes of course. i'm working on it. will make a PR in a couple in few hours. @jywarren

**Comment by siaw23** [comment]
This is just a small set of fixed violations. Please let me know if it can be merged or if there's that needs fixing... @jywarren

**Comment by siaw23** [comment]
@jywarren please check my latest PR. it works on just one controller file with the changes. any thoughts? before i get to work on the whole code base it'll be nice to have such things put in place. make room for clean and more understandable code. can i go ahead? also please give me your thoughts on me doing the upgrade to Rails 4 AND the implementation of Twitter/Facebook login so I can submit the proposal later today.
