### ISSUE TITLE
Logout remotely 

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#1351]
Hi there,
I'm putting in a low priority feature request for the ability to manage log-ins from the dashboard. I've had a situation recently where I was logged in on a different computer at a conference and accidently forgot to logout. I think this means that computer keeps my log in. I'm interested in being able to manage/logout from other computers from my profile or the dashboard! 

### PublicLab.org username
Stevie

**Comment by siaw23** [comment]
something like an option to "Logout from all other devices"?

**Comment by steviepubliclab** [comment]
yeah that would do the trick!
-Stevie

**Comment by siaw23** [comment]
@steviepubliclab i can implement this but my priority now would be first completing my GSoC goals if i'm selected. so let's see. if after that no one has written code for it. i'll do it.

**Comment by steviepubliclab** [comment]
Sounds great! Thanks for looking into it.

**Comment by Diksha2008** [comment]
I would like to work on this if no one else is ?

**Comment by jywarren** [comment]
Yes please!
