### ISSUE TITLE
Code Tag Not Working as Expected

### ISSUE THREAD

**Issue by RainmanJS** [publiclab/plots2#1374]
### What happened just before the problem occurred

Page does not display code correctly.

### Relevant URLs

https://publiclab.org/n/14103

### PublicLab.org username

jesseslone

(to help reproduce the issue)

### Browser, version, and operating system

Safari, latest beta of macOS

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by ffiebig** [comment]
This might be related to #1358, the fix came with #1377

**Comment by jywarren** [comment]
Thanks @ffiebig -- it's possible. I looked at the page and it seems OK now -- I'm going to close this since it probably happened before #1377 was published? But @RainmanJS if you see something wrong that I missed, please re-open and help us pin it down. Thanks for reporting!!

**Comment by RainmanJS** [comment]
Thanks, looks good.  I'll have to get my next version up now.
