### ISSUE TITLE
Remove dead link from dropdown menu

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1379]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

On the top menu bar of https://publiclab.org, there's a Data dropdown menu, and it has a link we no longer need: [Open Water](openwaterproject.io). Further, the link is dead, and I circled with @kanarinka, @dwblair, and @steviepubliclab to confirm that we don't need it. 

![screen shot 2017-04-21 at 11 17 14 am](https://cloud.githubusercontent.com/assets/161439/25284140/1b809d4c-2684-11e7-9187-4f36756a8267.png)

## Solution

Please remove Open Water link from the "Data" dropdown menu on the top menu bar of https://publiclab.org

Where to find the relevant lines of code: https://github.com/publiclab/plots2/tree/master/app/...

What to change them to:

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by jywarren** [comment]
Hi, Liz - can you add (and I can help) things as per this? https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors

**Comment by ebarry** [comment]
alright, i think i fixed it, let me know.

**Comment by jywarren** [comment]
perfect!!!

**Comment by morrme** [comment]
🙋🏾 I'd like to help . Thanks for making these available!

**Comment by jcotillo** [comment]
@morrme are you claiming this issue?

**Comment by morrme** [comment]
@jcotillo yes,
