### ISSUE TITLE
#tag hashtag links

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#138]
### The proposal

When people post research notes (https://publiclab.org/research/), wiki pages (https://publiclab.org/wiki/), or comments ([example](https://publiclab.org/notes/cbreuer/02-06-2016/oil-testing-kit-initial-electronics#comments)), we'd like it if links were auto-added to any word preceded by a hash mark, just like on Twitter -- but that a tag like `#hashtag` would go to https://publiclab.org/tag/hashtag. 

### Proposed implementation

This would be structured very similarly to the Callouts system, using a pattern as it does here: https://github.com/publiclab/plots2/tree/master/config/initializers/constants.rb but with the `#` symbol instead of the `@` symbol.

Watch out, though, because it would have to exclude hashtags that begin a line, as those may be `h1`-level headers in Markdown, which can be indicated without a space, like:

`#My header`

The regular expression would have to exclude that case, and an automated test for that case would be a good idea.

The current Callouts code is implemented for:

* research notes and wiki pages: https://github.com/publiclab/plots2/blob/c2dda7dece061dd0a73efefc34e61dc881b2e4f2/app/models/drupal_node_revision.rb#L43
* comments: https://github.com/publiclab/plots2/blob/8dc3193954beacea8be25af46853f8a978c058b2/app/models/drupal_comment.rb#L26

Adding tags would insert an extra filtering step in both places. 

****

Advanced extras (let's create new issues of these once this one is closed):

Plus #double#hashtags for notes with both and @username#hashtags for notes of that tag for that user. Via @mathewlippincott

**Comment by ananyo2012** [comment]
@ananyo

**Comment by ananyo2012** [comment]
@a123

**Comment by ananyo2012** [comment]
@jywarren I am currently working on this. I am able to fetch the hashtags and link them to an url. I need some directions on it. 

- Shouldall hashtags point to the link https://publiclab.org/tag/hashtag as mentioned above? I think url doesn't matter at this moment as url can be changed depending on future usage.
- ShouldI focus on Callouts and writing test on them for time being? 
- Are we keeping hashtags associated to tags and display them with other tags? Or Should we make new controller and models for hashtags? We can keep hashtags associated with tags and think of a functionality that adds a hashtag tag label as soon as note is posted. But things can get complicated. I think moving to a independent hashtag system would be more efficient.

**Comment by jywarren** [comment]
Cool! To your first two questions, yes and yes!

About a controller, let's use the Tags controller. Hashtags should just be
thought of as an interface to tags. I don't think we need to actually tag a
post if its content includes hashtags.

For example, you might say in a post that "this is different from the work
on #balloon-mapping" - and the post itself wouldn't be a balloon-mapping
post. But we might eventually scan for common words or hashtags in a post
to *suggest* tags.

**Comment by jywarren** [comment]
Uh oh, I shouldn't have merged this so fast. There are a few issues. 

* [ ] One is that all the links to to `/tag/hashtags` instead of a link like `#foo` going to `/tag/foo`
* [ ] another is that there are a variety of edge cases that we should test for -- I tried a few here:

````
#Tagnames! Testing #tagnames with #commas, #exclamations! and #periods. 

#Titles and #tagnames

##Titles

##Titles with multiple words

## Titles

# Tagnames

[#tags in links](/)

[tags in URLs](/mypage#tags)
````

Line 1 shows the first issue I mentioned above.

Line 2 is OK

Line 3-4 -- there's a debate about whether a `#Markdown title` should `# Require a space`  before the hash. Can we craft a regex expression that will **not** match if there is more than one `#` hash mark, like `##` or `###`? That'd solve this for almost all instances, because top-level (single hash) headings are almost never used. 

Line 5 and 6 are fine.

I think line 7 is fine too -- the markdown doesn't nest. 

The last line worked perfectly.

**Comment by jywarren** [comment]
Try it out on Rubular! http://rubular.com/r/RV7tmtiIht

**Comment by ananyo2012** [comment]
@jywarren Trying to solve this issue soon.

**Comment by jywarren** [comment]
Great, thanks. I hope Rubular was helpful, it's an essential tool for me!

**Comment by ananyo2012** [comment]
@jywarren Yeah Rubular is great! I have been using it for quite a while. Please refer to this link http://rubular.com/r/XTCQpZfaKi. I think this covers all the test cases ruling out double hashtags and removes the chances of nested markdown.

**Comment by ananyo2012** [comment]
@jywarren Referring to the very fast issue I have a doubt. Are hashtags and normal tags treated in the same way? Considering `#foo` if we link it to `/tag/foo` there can can be cases where there are tags on `foo`. So shall we list notes on `#foo` and tag `foo` in the same place? A better alternative would be to use an url `/tag?hashtag=foo`

**Comment by jywarren** [comment]
Ah, maybe I didn't explain enough -- hashtags /are/ tags -- we want any
instance of `#foo` to lead to /tag/foo, so that people can say things like:

    For more on spectrometers, check out the _#spectrometer_ tag.

And it'd auto-generate a link to /tag/spectrometer

Make sense?

**Comment by ananyo2012** [comment]
@jywarren Ok that makes it clearer.
