### ISSUE TITLE
Add "This has been merged!" alert to chatbot

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1381]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

(not yet, but once we finish formatting this:) Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

Our baby chatbot needs to be able to respond to another event: when a PR gets merged. We'd like it to ask first timers what their Twitter handle is, so we can thank them!

## Solution

Here's the script for the cute chatbot where we can add the new text: https://github.com/publiclab/plots2/blob/master/Dangerfile

But we don't yet have a trigger for "when a PR is merged". Here's the reference for Dangerbot itself: http://danger.systems/reference.html

We need to find the trigger for "when a PR is merged" by reading through the Danger docs, and when that happens, send a message like:

`Hi, thanks so much; your code will likely be published to PublicLab.org in the next few days. In the meantime, can you tell us your Twitter handle so we can thank you properly?`

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by ryzokuken** [comment]
Hey, @ebarry! I read the word "chatbot" and jumped on it :P Will try to reformat this one.

**Comment by jywarren** [comment]
Hi, Liz - just a note - I just added a prefix to the intro so that people wandering across this before it's ready don't YET think that it's a first-timers-only issue. This can be removed once it's ready.

**Comment by jywarren** [comment]
And i added my standard "help make this an FTO issue" preamble

**Comment by jywarren** [comment]
And added a suggested text for requesting a Twitter handle

**Comment by kirangp** [comment]
Hi @ebarry @jywarren Can I work on this?

**Comment by ryzokuken** [comment]
Sure, @kirangp. Feel free to ask for help in case you get stuck anywhere.

**Comment by kirangp** [comment]
Thanks @ryzokuken So as per my understanding I need to update the Dangerfile so that chatbot . Can you tell me how can I test this chatbot locally?

**Comment by jywarren** [comment]
Hmm, i'm not sure how to test it locally, but it may be that if you open a
pull request with the new changes, it will run the new (proposed) version
of the chatbot on the PR itself -- i know it does this for changes to the
tests in Travis. It's worth a try!

**Comment by jywarren** [comment]
I've moved this to a new `first-timers-only` issue here, because we can rely on Welcomebot to do this: 

https://github.com/publiclab/plots2/issues/3342

Thanks!
