### ISSUE TITLE
 link to Public Lab's chat doesn't work (on 404, not logged in)

### ISSUE THREAD

**Issue by kaametza** [publiclab/plots2#1382]
### What happened just before the problem occurred
Looking for a pad page I made a mistake and got to a page that doesn't exist. I tried to access the chat link and I didn't get any response from the website. I do have Ublock installed and active.

### Relevant URLs

https://publiclab.org/SLMission

### PublicLab.org username

(to help reproduce the issue)

### Browser, version, and operating system

Version 57.0.2987.98 built on Debian 9.0, running on Debian 9.0 (64-bit)

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
I'm sorry to hear this -- which chat link did you mean, and on what page? https://publiclab.org/SLMission is not a valid URL -- did you mean https://publiclab.org/wiki/SLMission? Hmm, but that also doesn't exist. Hope we can help!

**Comment by jywarren** [comment]
Hi, I believe it is working now, see attached screenshot. But if you can share a link to a page where it isn't, please re-open, and thanks!

BTW, there is also chat available at http://publiclab.org/chat.

![screenshot 2017-05-09 at 4 06 59 pm](https://cloud.githubusercontent.com/assets/24359/25870311/ac71bd1c-34d1-11e7-85fd-31a03337b30f.png)

**Comment by icarito** [comment]
Hi,

I tested it and still the "Open Chatroom" button doesn't change the page
(it does start loading and finishes, but doesn't display anything).

Here's a link to reproduce:
https://publiclab.org/not_working_open_chatroom_button

**Comment by jywarren** [comment]
Ah, i see! the button on the 404 page itself! at /public/404.html.

Fixing this now, then.

**Comment by jywarren** [comment]
OK, this'll be much better:

![image](https://cloud.githubusercontent.com/assets/24359/25871565/f94dd6d0-34d5-11e7-888f-070936443808.png)
