### ISSUE TITLE
single typo in a link to the Advanced Search url

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1385]
### What happened just before the problem occurred

So, i've landed on this wrong link many times over the past 6 months, probably because i'm always searching for weird stuff on publiclab.org. Finally, i sorted out how to reproduce this bug: 

- go to publiclab.org
- type an unlikely search term into the search text box, click enter
![screen shot 2017-04-27 at 8 20 20 am](https://cloud.githubusercontent.com/assets/161439/25483093/680b51be-2b22-11e7-865c-3ccaa15e597f.png)

- for search terms where no results are returned on the first pass, for instance i tried "open open hardware revision cycle", which created a URL of https://publiclab.org/search/open%20open%20hardware%20revision%20cycle , it goes to a no search results returned. 
![screen shot 2017-04-27 at 8 19 40 am](https://cloud.githubusercontent.com/assets/161439/25483099/6d90d000-2b22-11e7-838b-08f02ea8f823.png)

- on this screen, click "Advanced Search" 
- It goes to a "page does not exist" because of a misplaced "e" in the URL so "search" is wrongly "searche" -- https://publiclab.org/searche/advanced/ should be https://publiclab.org/search/advanced/
![screen shot 2017-04-27 at 8 19 55 am](https://cloud.githubusercontent.com/assets/161439/25483148/a3aeded4-2b22-11e7-8872-57a57b50a577.png)

### Relevant URLs

a test search term that will return no results on the first pass, for instance https://publiclab.org/search/weirdstuff , so that the link "Advanced search" will be offered, which goes to the wrong URL: https://publiclab.org/searche/advanced/

### PublicLab.org username

liz

**Comment by itroman** [comment]
Happy to fix this if it's open.

**Comment by jywarren** [comment]
Yes please! We are happy to help if you run into trouble.
