### ISSUE TITLE
comments on dashboard "activity" section not paginating

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#1391]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### The problem

I was on [the dashboard](https://publiclab.org/dashboard), and selected only the "comments" under activity to scroll through and view those that have been made recently. 

Clicking the pagination bar on the bottom didn't work and each page of comments ("1-2-3-4") loaded the same comments responses, not going back in the history. 

(additions by @jywarren follow)

### Proposed solution

We need to make the page respond to the "page=2" style changes in the URL when people click the page number buttons. 

So to start with, comments are fetched on this line of the `home_controller.rb`:

https://github.com/publiclab/plots2/blob/master/app/controllers/home_controller.rb#L88

See how `.limit(20)` appears below, limiting the returned comments to 20? We should change that to respond to the "page number" which gets added into the URL, just like is done on this line:

https://github.com/publiclab/plots2/blob/master/app/controllers/home_controller.rb#L61

Changing the `.limit(20)` to: `.page(params[:page])` should get the comments paginating as well. 

## Steps to Fix

- [x] claim this issue with a comment here, below, and ask any clarifying questions you need
- [x] set up a repository locally following the README instructions, and make sure that all tests pass
- [x] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by SwordShieldMouse** [comment]
I'd like to try to work on this!

**Comment by ananyo2012** [comment]
Sure go on ahead! If you want any help you can comment here or ask us in [our chatroom](https://chat.publiclab.org/)
