### ISSUE TITLE
Code of Conduct on bottom bar

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#1393]
I was wondering if someone could add a link to the Public Lab Code of Conduct on the bottom bar of the Public Lab pages? 

Here's a link to the Code of Conduct: https://publiclab.org/conduct

Maybe it would fit best under the links list? Or maybe the Creative Commons piece. 

@ebarry do you think it needs supporting text? For example: "The code of conduct applies to all spaces managed by the Public Lab community and non-profit, both online and in person."

**Comment by jywarren** [comment]
Thanks, this is very quick to do bc of our features work (a first-timer
added a feature to the footer a while back, I believe). Once you have final
text, ping me and I'll add it!

**Comment by jywarren** [comment]
Done, using the text you provided, thanks!

![image](https://cloud.githubusercontent.com/assets/24359/25862865/85a07ae4-34b7-11e7-85e0-4a6f4d08e978.png)
