### ISSUE TITLE
Add new functional tests to each method in Search API

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1395]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

> Tests help us ensure that the site behaves as we expect it to -- and that as new features are added, they don't break existing functions. We're working to get to near 100% "coverage" -- which would mean all our code is covered by tests.

We have good tests written for the typeahead API, here: https://github.com/publiclab/plots2/blob/master/test/functional/typeahead_api_test.rb

This tests each method in: https://github.com/publiclab/plots2/blob/master/app/services/typeahead_service.rb

But we should have similar ones for the search API, for the methods in: https://github.com/publiclab/plots2/blob/master/app/services/search_service.rb

## Solution

Let's create a new file at:

`test/functional/search_api_test.rb` -- containing, as a start:

```js
require 'test_helper'

class SearchApiTest < ActiveSupport::TestCase
  include Rack::Test::Methods

  def app
    Rails.application
  end

  test 'search notes functionality' do
    get '/api/srch/notes?srchString=Blog'
    assert last_response.ok?

    # Expected search pattern
    pattern = {
      srchParams: {
        srchString: 'Blog',
        seq: false,
      }.ignore_extra_keys!
    }.ignore_extra_keys!

    matcher = JsonExpressions::Matcher.new(pattern)

    assert matcher =~ JSON.parse(last_response.body)

    # check for actual Blog note, too
    # assert_equal ___, node(:blog)

  end

end
```

You can try running this with `rake test` or (just to run the functional tests only) `rake test:functionals` -- hopefully it will pass! But you can also just open a pull request (see below) and our automated test system will run it, and you'll be able to see the output there. 

If you can help with this, please open a pull request with this test added, and let's see how it goes. We may need to tweak the `srchString` parameter, and (as noted in the snippet above) add an extra assertion to ensure the results are right. 

After this, we can move on to adding additional tests for the other methods in the API.

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by morrme** [comment]
aww, I think I've contributed already 😭  but this would be awesome to learn more about. If no other first timers come after a certain amount of time, do issues like these open up to others?

**Comment by orcutt989** [comment]
I'd like to contribute, but I am struggling to get plots2 set up on a fresh Ubuntu 12.04 LTS box. I am going to try again and report back with where its failing.

**Comment by jywarren** [comment]
Hi, @morrme -- there are a number of "almost ready for first-timers" issues at https://github.com/publiclab/plots2/labels/fto-candidates -- ones we haven't yet done a final formatting on. Please grab one there! There's also some guidance at https://github.com/publiclab/plots2/projects/2. Thanks!!!

@orcutt989 -- there was a fix submitted for a common `mysql` error this morning -- try refetching the repo and try it again -- hopefully it's resolved! Apologies!

**Comment by orcutt989** [comment]
Stuck at rake db:setup
```
Mysql2::Error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

**Comment by morrme** [comment]
@jywarren they're all claimed at the moment but thanks anyway!

**Comment by jywarren** [comment]
Oh really? Wow, that's kind of great to hear, i guess -- but you can also
sort by "last updated" and find those that haven't been touched for months.
There are several -- and in general, if nobody's responding, you might as
well take it up!

https://github.com/publiclab/plots2/issues?q=is%3Aopen+label%3Afto-candidate+sort%3Aupdated-asc

Also, if you like, tell me what kinds of things you'd like to work on and
we can prep some additional issues!

**Comment by orcutt989** [comment]
@jywarren I don't know if this is possible, but I know feature extensions are a valuable skill to have.

**Comment by jywarren** [comment]
Also, there are a few issues that could be broken off of these:

https://github.com/publiclab/plots2/issues/761
https://github.com/publiclab/plots2/issues/956

On the last one, perhaps the `DrupalNodeRevision => Revision` is a good project? I don't think it'd be too hard, though it does take some use of the `grep` command to find and then replace across lots of files. 

@orcutt989 -- not sure what feature extensions are, can you elaborate? Thanks!! Also, i think you got the mysql issue resolved in the chatroom, right?

**Comment by orcutt989** [comment]
@jywarren Yes! Issue was resolved, just getting it set up now.

Feature extensions - meaning new things that you want to implement or improve.
