### ISSUE TITLE
signup biography does not get added to user profile

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#14]
Steps to reproduce (sufficient but perhaps more than necessary):

1. go to /signup
2. type in some junk that will cause errors and click sign up
3. when forwarded to /register, type in some more junk that will cause errors and click sign up
4. properly fill out the registry and type in something for the bio
5. once logged in as new user, look at profile and see lack of bio

That signup bio is not put in the database anywhere so far as I can tell.

just for fun, I did this again very simply and still see the problem:

1. go to /signup
2. type in valid information and something good in the bio, click sign up
3. once logged in as new user, look at profile and see lack of something good in bio
4. edit profile, change bio, see that it sticks

**Comment by ebarry** [comment]
My single test did not replicate this bug: 
![screen shot 2016-02-16 at 8 06 32 pm](https://cloud.githubusercontent.com/assets/161439/13096628/ce52696c-d4e8-11e5-995c-dbb50d22cf7c.png)

**Comment by ananyo2012** [comment]
I also tested this and it didn't replicate the bug. @jywarren Can this be closed now?
