### ISSUE TITLE
Fix "like" list URL on notes and wiki pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1405]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

What's supposed to happen: 

When you click the "like" menu, you see folks who've "liked" a note, like on this page: https://publiclab.org/wiki/hydrogen-sulfide-sensor

![screenshot 2017-05-09 at 5 03 47 pm](https://cloud.githubusercontent.com/assets/24359/25872633/80a6c5a8-34d9-11e7-99d0-347330ae4877.png)

When you click on their names, you should go to their profiles. 

What actually does happen (screenshot if helpful!): 

Unfortunately you go to a page showing their likes -- this isn't right -- at the URL (for example) https://publiclab.org/profile/warren/likes

## Solution

We should remove the trailing `/likes` from the end of that URL in this file:

https://github.com/publiclab/plots2/blob/master/app/views/like/_like.html.erb#L17

```ruby
  <i class='fa fa-star-o'></i> <a href='/profile/<%= user.username %>/likes'><%= user.username %></a><br />
```

What to change them to:

```ruby
  <i class='fa fa-star-o'></i> <a href='/profile/<%= user.username %>'><%= user.username %></a><br />
```

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by kristapuciitis** [comment]
Hello, I would like to take this issue. First timer, never contributed to any github project.

**Comment by orcutt989** [comment]
@jywarren I can close my pull request if @kristapuciitis wants to take a whack at it.

**Comment by jywarren** [comment]
Yes, @orcutt989 that would be great, thank you. There are a number of https://github.com/publiclab/plots2/labels/fto-candidate issues available that we'd love you try. The `first-timers-only` issues take a while to create, so we'd love to preserve them. Thank you!

@kristapuciitis  we'd love to have a contribution from you!

**Comment by anniemiko** [comment]
Hi @jywarren I've never submitted a pull request and would love to try this one out if it's still open/available. Thanks!

**Comment by jywarren** [comment]
Yes please! We'd love to have your contribution and are happy to help.

**Comment by jywarren** [comment]
Ah, I see there are a couple people interested. Happy to accept changes from both but there are also others available. I'll make one more now.

**Comment by jywarren** [comment]
Just posted this one as a first-timers-only issue too; plenty of work to go around :-)

https://github.com/publiclab/plots2/issues/1406

**Comment by anniemiko** [comment]
Thank you @jywarren - I will start on #1406 then!

**Comment by orcutt989** [comment]
I'll grab this again.

**Comment by kristapuciitis** [comment]
You can take it, I won't solve this issue. Sorry for inconvenience.

**Comment by alanunruh** [comment]
Hi @jywarren :wave: - Wondering if this is still open? If so, I'd love to implement the solution to this issue. (Noob/first time contributor here....)

**Comment by jywarren** [comment]
Yes it is! We'd be very happy to have your contribution.

**Comment by alanunruh** [comment]
Great, I'll take it!

**Comment by shelbyfirebaugh** [comment]
hello @jywarren ! if this issue is still unresolved i would be interested in taking it on so that i can get to know your github workflow

**Comment by ryzokuken** [comment]
Hi @shelbyfirebaugh!  
It has been 20 days since @alanunruh took this up, so it would be safe to for you to pick this up as we haven't really heard from him since then. If it turns out that @alanunruh is infact working on it, we could help you look for another simple issue to get your hands on.

Needless to say, if you face any problems with solving it, please feel free to ask here, on the PR thread or on our chatroom.

**Comment by alanunruh** [comment]
Hi @shelbyfirebaugh, @ryzokuken & @jywarren!

I've completed this issue and it has already been merged https://github.com/publiclab/plots2/pull/1468.

**Comment by ryzokuken** [comment]
Thanks looks awesome, @alanunruh!

@shelbyfirebaugh it seems there was an oversight on our part and this issue was not closed. I am closing this now. Try looking for another first-timers-only issue at https://github.com/publiclab/plots2/issues?q=is%3Aopen+is%3Aissue+label%3Afirst-timers-only

**Comment by shelbyfirebaugh** [comment]
no problem, i'll check out more issues soon.

thank you!
shelby

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
