### ISSUE TITLE
Display a description field for tags, if it exists

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1406]
****

Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

We're going to start using tag descriptions, but there's nowhere to display them for now. Tags appear on most pages, like: https://publiclab.org/wiki/hydrogen-sulfide

What actually does happen (screenshot if helpful!): 

When you hover over a tag now, you can see the time it was created, and the author, in a Bootstrap "tooltip":

![screenshot 2017-05-09 at 5 48 07 pm](https://cloud.githubusercontent.com/assets/24359/25874259/b88eb65a-34df-11e7-926d-61aef9f759e6.png)

## Solution

We should check if there is a description, and show it in the tooltip just before the other info. 

The popover code is here: https://github.com/publiclab/plots2/blob/master/app/views/tag/_tags.html.erb#L4

```ruby
      <span id="tag_<%= tag.tid %>" class="label <%= label_name %>" data-toggle="tooltip" data-html="true" title="created by <strong><%= tag.try(:author).try(:username) %></strong> <%= time_ago_in_words(Time.at(tag.date)) %> ago">
```

For one, it's a bit messy. Try putting each thing on its own line and doing nice two-space indents to make it more readable.

Then, add:

```ruby
<% unless tag.description.empty? %><%= tag.description %> |<% end %>
```

Then open a pull request so we can try it out!

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by anniemiko** [comment]
I'd like to claim this as my first open source PR. Thanks for the opportunity!

**Comment by jywarren** [comment]
Super, and thanks!

**Comment by snhardin** [comment]
Hi! I've never contributed to an open source project before. May I work on this issue?

**Comment by jywarren** [comment]
If nobody's responded for a while then you're welcome to!

**Comment by snhardin** [comment]
Cool! I think my solution works. I just submitted a pull request for this issue.
