### ISSUE TITLE
Dashboard post a question link character limit

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#1413]
### What happened just before the problem occurred
I noticed that when I select "share your work" ->"ask a question" on the dashboard (https://publiclab.org/dashboard) there is a stricter character limit on the question than if I post on /questions. It's hard to post a question under the shorter character limit.

**Comment by jywarren** [comment]
whoa, really?

The dash sends you to
https://publiclab.org/questions/new?tags=question:question&template=question&redirect=question

/questions sends you to:
https://publiclab.org/questions/new?title=&tags=question%3Ageneral&template=question&redirect=question

they're very similar... can you explain how it enforces the limit? Do you
see an error, does it not let you type, what happens?

Thanks!

**Comment by steviepubliclab** [comment]
Hi,
It won't let you publish it when you hit publish and you get this bar: [image:
Inline image 1]

**Comment by jywarren** [comment]
@ananyo2012, I wonder if this is touching your validation code on question length. Is it a requirement we could remove easily?

**Comment by ananyo2012** [comment]
Checking it now

**Comment by steviepubliclab** [comment]
I just posted a longer question in this way, and was not limited by the word count. Think it's fixed?

**Comment by jywarren** [comment]
👍

**Comment by ebarry** [comment]
I think it's a feature not a bug that /questions has a character limit and i propose that we use the opportunity to simplify the /question page and leave the /post template option to write a question fully featured. I wrote out some ideas here: http://pad.publiclab.org/p/ui
