### ISSUE TITLE
add Tag.contributor_count method

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1419]
We need a generalized tag-based method, like `Tag.contributor_count(tagname)` for counting contributors. It'd also be great to count commenters, answerers, etc! It could start with this code: https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L216-L219

It could go in the Tag model: https://github.com/publiclab/plots2/blob/master/app/models/tag.rb

```ruby
def contributor_count(tagname)
  # code here
end
```

We'd of course want to unit test it! It could then be used to replace parts of #1028 and the code in https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L216-L219

**Comment by david-days** [comment]
I think a quick-and-dirty version would be the results of a query like:

`
select count(du.userid)
  from DrupalTag dt
  inner join DrupalCommunityTag dct on dt.tagid = dct.tagid
  inner join DrupalUser du on dct.userid = du.userid
  where dt.tag_name = :tagname

`

OTOH, going through the DrupalNode table would be more likely to ensure that there was a definite link to authors, as opposed to any other mechanism (or it might give the same answer, which would be a way to make sure that the tie-ins would make sense.  Not sure...).

**Comment by david-days** [comment]
meh...probably have that backwards, and need to start from the DrupalUser table.  Still, I think it's the route to go.  Will see what I can come up with tonight.

**Comment by jywarren** [comment]
I think we could do a few chained queries, and combine and `.uniq` the results. Like:

```ruby
uids = Node.where(...).collect(&:uid)
uids += Comment.where(...).collect(&:uid)
uids += Answer.where(...).collect(&:uid)
uids = uids.uniq
uids.length
```

We should write the test first, though!

**Comment by david-days** [comment]
Agree.  I can work the code and the tests.  The finicky issue is getting a "true" answer and/or adjusting the test data set so that it will work.

**Comment by ananyo2012** [comment]
It will be good if we can list out the things that we want to display in contribution count. Here are the things I thought of
- Total no of research notes, wiki pages and questions with that tag
- No of followers of that tag
- Top 5 contributors on that topic. Here is a sample screenshot of how it is done in stackoverflow
![screencapture-stackoverflow-tags-javascript-info-1494863078487](https://cloud.githubusercontent.com/assets/10486343/26066472/9aa91e08-39b4-11e7-8514-972c29484235.png)

**Comment by ebarry** [comment]
This is a really great project that I really want to be able to use -- is there anything needed from me to be able to move this forward?

**Comment by jywarren** [comment]
If combining answers, comments and notes is a good starting point, we can bump this up and ask a new contributor to take it up.

**Comment by jywarren** [comment]
I think we can combine the original issue and my comment here: https://github.com/publiclab/plots2/issues/1419#issuecomment-301337333 and repost it as a first timer issue ! I'll mark it as a candidate

**Comment by jywarren** [comment]
Moving a cleaned-up version into a first-timers issue here: #1774

@ebarry - any outreach help with this appreciated! Thanks!
