### ISSUE TITLE
List of pages/notes sortable by tags of equipment and use case

### ISSUE THREAD

**Issue by skilfullycurled** [publiclab/plots2#142]
Since getting involved in PL, people will send me articles from time to time about environmental issues in Chicago.  My first thought is always (paraphrased), "Awesome! I'm empowered to do something about that!".  My second thought is always, "Which tool(s) should I be using to do something about that?".  So, I've learned how to hammer nails into pieces of wood, but I don't really have a sense about the ways in which I can combine nails and multiple pieces of wood into a structure.  It would be great to be able to go to a list and see all of the situations that people have used the tools in, which tools they used in a given situation, and the location of the site.

**Comment by ebarry** [comment]
Benjamin, as we are getting closer to an overall reorganization around "AIR" "WATER" "LAND" as entry points from the front page, the tagging around what environmental concern is present should get easier. In terms of tools, my perception is that that is part of the culture -- most notes and wikis are getting tagged with the tools mentioned in them.

**Comment by skilfullycurled** [comment]
From the bottom of my August 2014 heart, I thank you!

**Comment by jywarren** [comment]
I believe we can now do this with inline tags: https://publiclab.org/wiki/power-tags#Inline+power+tags
