### ISSUE TITLE
When accessing a page that doesn't exist, the page that shows has two footers?

### ISSUE THREAD

**Issue by tz-hmc** [publiclab/plots2#1426]
### What happened just before the problem occurred

Playing around with cloned copy of PublicLab, realized the double footer bug I found was also on the actual PublicLab website. There's also two navbars, one that covers the other one? But it doesn't show, so I guess it's not really something that needs fixing. But the two footers appear one after another.

![screen shot 2017-05-19 at 8 10 05 pm](https://cloud.githubusercontent.com/assets/21372809/26272582/a7f1c4ce-3cd0-11e7-9069-d13a4f67617b.png)

How are _headers and _footers attached in plots2? I assumed it would be something like <%=render layouts/header> and <%= render layouts/footer>, but that doesn't seem to be the case. On my local copy I just deleted the 404.html header and footer to avoid replicating them.

### Relevant URLs
(any URL that doesn't resolve to a page)
https://publiclab.org/methodssdf

### PublicLab.org username
doesn't matter

### Browser, version, and operating system
doesn't matter

**Comment by ananyo2012** [comment]
Thanks for reporting. We will fix it soon
