### ISSUE TITLE
Multiple chatroom windows show, after chatroom icon is opened, closed, then opened again

### ISSUE THREAD

**Issue by tz-hmc** [publiclab/plots2#1427]
### What happened just before the problem occurred
Chatroom icon was clicked once to open, clicked again to close, and clicked one more time. 
![screen shot 2017-05-19 at 10 00 49 pm](https://cloud.githubusercontent.com/assets/21372809/26273177/25e9d584-3cdf-11e7-8733-fce9cd00d959.png)
^ You can see the second box here.

### Relevant URLs
https://publiclab.org/

### PublicLab.org username
n/a

### Browser, version, and operating system
n/a

**Comment by ananyo2012** [comment]
Thanks for reporting. I am on it
