### ISSUE TITLE
Implement form fields for highly reccomended tags

### ISSUE THREAD

**Issue by skilfullycurled** [publiclab/plots2#143]
There are probably some tags that are enormously helpful as a bare minimum and at the same time easy for anyone to figure out.  As a start, I think it would be good to make type of tool(s) used (balloon mapping), situation (petcoke piles), and location (Chicago, IL).

**Comment by jywarren** [comment]
I'm going to adapt this into one where we display the most recently used tags by someone as options on the tags "cog" menu -- we can expand this out to suggested/related tags once we have the interface in place, as I think related tags may be something we can try via Solr?

Closing and opening #1779.
