### ISSUE TITLE
universityresultonline

### ISSUE THREAD

**Issue by checkresultsonline** [publiclab/plots2#1436]
### Relevant URLs

https://

### PublicLab.org username

(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

http://www.universityresultonline.in/

**Comment by ananyo2012** [comment]
Gosh isn't spamming obvious in github issues these days! Closing this one.
