### ISSUE TITLE
missing page?

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#144]
I was just clicking through some pages, notably
http://publiclab.org/wiki/mapping-curriculum
(seeking out one page with an introduction to balloon, kite, plane, and drone mapping ... and pics)

came across this link:
http://publiclab.org/wiki/mapping-curriculum-platform

says it doesn't exist. I get the feeling everything linked off mapping-curriculum existed at one point, right? So this page is probably lost in the great routing change up of 2014 maybe?

**Comment by jywarren** [comment]
The slideshow page exists -- I'm not convinced the curriculum page did however. Sometimes it's a convention to create a link to a non-existent wiki page to encourage "someone" to make that page. I'm going to close this for now, but if you find evidence (say, internet archive or something, or a ref from the mailing lists) we can re-open. Thanks!
