### ISSUE TITLE
Add tests to check commeting functionality of wiki pages

### ISSUE THREAD

**Issue by aspriya** [publiclab/plots2#1443]
### Feature

This is regarding the Long term project __Wiki Discussion__. A wiki page can broken down into subsections and can be edit per subsection basis. As the project describes, a wiki should be more interactive. Users having the ability to comment on section basis of is one step for acheiving that. It is good to follow TDD approach, so writing test is a good start. 

### Relevant URLs

A detailed description of the project can be found in following links
#1438
https://publiclab.org/notes/Ashan/03-13-2017/wiki-discussion

### Implementation

Currently there are no tests to test the commenting ability of wiki pages. So with this issue I will be adding two test cases to check if a wiki is commentable and to check if a comment is not saved, does it give a error message.

**Comment by jywarren** [comment]
Complete in #1444 🎉
