### ISSUE TITLE
site hangs on /search/mapknitter; optimize

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/plots2#145]
I'm getting an error when conducting searches for 'mapknitter', even though I know its a tag. not sure what's up.  it shows up when I type in http://publiclab.org/tag/mapknitter

![screen shot 2014-08-13 at 4 51 08 pm](https://cloud.githubusercontent.com/assets/1203280/3914352/ca19e782-2344-11e4-927e-faa127f1bebe.png)

**Comment by jywarren** [comment]
Yikes. I think this may be because for a long time we imported all mapknitter maps. Maybe there's like a huge cache of mapknitter notes -- even that aren't published or something? It eventually loaded for me but took a hella long time.

**Comment by jywarren** [comment]
I believe this is resolved -- at least I do not see it happening any longer and perhaps it was dealt with in the big tag optimization rolled out recently.
