### ISSUE TITLE
Adjust subscription_mailer to use rusers table

### ISSUE THREAD

**Issue by StlMaris123** [publiclab/plots2#1451]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who **either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.**

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

### The Problem
We have two users table `users` and `rusers` . We are migrating to the `rusers` table but our mailers are still using the `users` table. This is captured here: 

https://github.com/publiclab/plots2/blob/master/app/mailers/subscription_mailer.rb#L10

### Solution

1. Covert all `user.name` to `user.username` in:
https://github.com/publiclab/plots2/blob/master/app/views/subscription_mailer/notify_node_creation.html.erb#L1

2. add a `def name` method to alias /app/models/user.rb

Our mailers will now be using `rusers` table.

### Steps to Fix

- [ ]  claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see contributing to [Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to the [chatroom](https://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information!](https://github.com/publiclab/plots2/projects/2)

**Comment by jywarren** [comment]
Oh, this is fantastic. Thank you, @StlMaris123 !! Labeling now.

**Comment by cmacaulay** [comment]
@jywarren have you claimed this issue? 😄

**Comment by jywarren** [comment]
Nope, please go for it, we're happy to help you with it! I was just
expressing enthusiasm :-)

**Comment by cmacaulay** [comment]
wonderful, I'll get started!

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by shubham7saxena** [comment]
has the issue been taken? If not, I'd love to get started.

**Comment by jywarren** [comment]
Not sure -- @cmacaulay are you still working on this one? Take your time -- and @shubham7saxena if you're looking for a project, please check out https://github.com/publiclab/plots2/labels/fto-candidate for some that are close but not quite at a level for first-time contribution, and we're happy to help you get into one.

**Comment by DrynnBavis** [comment]
Hey, have any other tasks available?

**Comment by jywarren** [comment]
It sounds like this one is not being actively worked on, so please take it up! Thanks!

**Comment by vishaldeepak** [comment]
Hi, I would like to contribute if its not being done by anyone else

**Comment by jywarren** [comment]
Hi, i haven't seen a pull request from anyone yet, so I think it is
available! Happy to help anyone who's stuck on this!

**Comment by vishaldeepak** [comment]
sure, i'l get at it right away

**Comment by vishaldeepak** [comment]
@jywarren Hi, I am a bit confused in what needs to be done. 

_1.-Covert all user.name to user.username_
So basically just change to `user.username` in that file where it says `user.name`
_2.-add a def name method to alias /app/models/user.rb_
Are we looking to create a method `name` in `user.rb` that acts as alias to `attr_accessible :username`. In that case the solution would be a one liner `alias_attribute :name, :username`

**Comment by jywarren** [comment]
Hi, @vishaldeepak -- i'm hoping some @publiclab/soc folks can help you as well, as I'm about to be traveling!

But but yes, you are correct. I haven't used `alias_attribute` but if that works, that's great!

**Comment by lilliankorinek** [comment]
@vishaldeepak How is the solution going?

**Comment by vishaldeepak** [comment]
il send it in a few hours

**Comment by jywarren** [comment]
This just got fied by @vishaldeepak -- great!!!
