### ISSUE TITLE
Inline question button which opens a form to post a question in a wiki

### ISSUE THREAD

**Issue by aspriya** [publiclab/plots2#1453]
### Feature

This is regarding the Long term project Wiki Discussion. A wiki page can broken down into subsections and can be edit per subsection basis. As the project describes, a wiki should be more interactive. One step for acheving interactivity is letting readers to ask questions. It's more meaningful if a reader can ask questions per section of a wiki page.

### Relevant URLs

A detailed description of the project can be found in following links
#1438
[Project proposal](https://publiclab.org/notes/Ashan/03-13-2017/wiki-discussion)

### Implementation

As publiclab is on it's way of integrating [inline-markdown-editor](https://github.com/publiclab/inline-markdown-editor) library, it's good solving this issue with `inline-markdown-editor`. Calling and passing required arguments to `inline-markdown-editor` function can be found [here](https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/wikis.js#L6-L12). With the `raw=true` query string parameter, a wiki page is already broken down into subsections. To add a question button [extraButtons](https://github.com/publiclab/inline-markdown-editor/blob/master/src/insertEditLink.js#L5-L16) proerty should be passed to inline-markdown-editor with an appropriate function. And clicking this button will display a form in a new window to create a question.

**Comment by jywarren** [comment]
😄 🎈 🎉  Want to assign this to yourself? And you can make a Milestone to collect all your sub-issues if you want. Ask me if you don't have access.

**Comment by jywarren** [comment]
Complete!
