### ISSUE TITLE
small discussion list feed error on /dashboard 

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1454]
### What happened just before the problem occurred

I checked the dashboard, and clicked the tab for "Discussion Lists" and saw an error message: 
![screen shot 2017-06-06 at 11 15 03 am](https://user-images.githubusercontent.com/161439/26839760-a0fb372c-4aa9-11e7-91be-e383465bc3a2.png)

### Relevant URLs

https://publiclab.org/dashboard

### PublicLab.org username

(to help reproduce the issue) liz

**Comment by jywarren** [comment]
Fixed! https://publiclab.org/dashboard
