### ISSUE TITLE
Problem with new research note form "Steps left"

### ISSUE THREAD

**Issue by StlMaris123** [publiclab/plots2#1456]
### FEATURE
When creating a new research note, the publish button is not activated unless you upload image as the last object.

### Relevant URLS

https://publiclab.org/post

### Implementation
Le the user fill in the fields as they appear.  Not fill in the fields and the have to re-upload the image for the publish button to be activated.

**Comment by jywarren** [comment]
Do you think we could have it display some kind of tip or notice like `Please add an image to illustrate your post!` ?

**Comment by jywarren** [comment]
Hmm, i just tested this and realized there may be a bug, not related to the image -- the first time I tried, i saw `1 of 2 steps` left, but then i typed more in the title field and got to `0 of 2 steps left` -- without uploading an image. Maybe the triggering is a bit off? 

Do you think you could add an issue to the editor repository, at https://github.com/publiclab/PublicLab.Editor?

Screenshot for proof:

![screenshot 2017-06-12 at 6 58 59 pm](https://user-images.githubusercontent.com/24359/27058805-6cca9e3c-4fa1-11e7-94eb-e4591c8ce165.png)

**Comment by jywarren** [comment]
Thanks for posting this, @StlMaris123 !!!

**Comment by jywarren** [comment]
Recently fixed!
