### ISSUE TITLE
Make Bootstrap "Pop-over" area close when clicking outside

### ISSUE THREAD

**Issue by StlMaris123** [publiclab/plots2#1457]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

### Feature
![tag](https://user-images.githubusercontent.com/13062617/26973243-21d34238-4d1e-11e7-82c7-dd4fd71d38ce.png)

When a user clicks on follow button to add a new tag, clicking outside the the pop up button shown above does not hide it. You have to re-click on the button for the pop up to disappear.

### Relevant URLS
This is an example of a page where you can follow tags:
https://publiclab.org/wiki/openhour

### FIX
Make the button responsive so that it hides the pop up contents on clicking outside it.

**Comment by jywarren** [comment]
Do you know how this might be done, or could you add a few more hints? It's a Bootstrap element: https://getbootstrap.com/

The "popover" code is actually on this line: https://github.com/publiclab/plots2/blob/master/app/views/like/_like.html.erb#L10

**Comment by StlMaris123** [comment]
I think it can be tackled used `popover` js function

**Comment by jywarren** [comment]
This is great -- i've marked it as `help-wanted` and if you'd like to upgrade it by adding the checklist and other helpful notes, we can make it a `first-timers-only` at some point.

**Comment by jywarren** [comment]
I did also change the title to try to make it a bit more descriptive to a newcomer, and added a section to the top mentioning how it could be "upgraded". Thanks!

**Comment by StlMaris123** [comment]
I also feel it cab be a nice first timer's issue.

**Comment by bassdeveloper** [comment]
Can I contribute?

**Comment by jywarren** [comment]
Yes please!

**Comment by jywarren** [comment]
Oh, sorry! yes, closing now.

**Comment by jywarren** [comment]
Thanks!
