### ISSUE TITLE
Autosave on rich wiki

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#1475]
I've lost a lot of work from unpublished wiki pages that have crashed when my computer closed or otherwise gone missing. I'm interested in having an autosave feature on the rich wiki project.

**Comment by jywarren** [comment]
Sorry, I think the feature is actually to add the rich editor to the
/wiki/new page -- the rich editor already has autosave!

**Comment by jywarren** [comment]
Great, opened an issue for this here: https://github.com/publiclab/plots2/issues/2083

and closing this one.
