### ISSUE TITLE
What's the status on the API

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plots2#1480]
I looked around in the current set of issues but couldn't find one with the roadmap for the plots2 API. What's the current status on the API? Can one register for an API key?

Specifically, I was concerned about the functionality of commenting on a research note.

**Comment by jywarren** [comment]
I believe there's some notes about making API tokens ... Could be on one of
your planning issues from a while ago.

But basically we need to create a new db field for storing token strings.
These can be randomly generated alphanumeric, and stored in rusers.

But how would we store it on the bot side? Do we need some storage?

**Comment by ananyo2012** [comment]
As per https://github.com/publiclab/plots2/wiki/API we don't need an API key as of now. Do we need to have a API token?

**Comment by ryzokuken** [comment]
@jywarren the bot's personal API key will be stored as an environment variable.

@ananyo2012 all users need to have a unique key using which they can make comments etc in their own name.

**Comment by jywarren** [comment]
+1

**Comment by jywarren** [comment]
I'm not at all familiar with how to provide a wrote API  using the grape swagger libraries.  our API is read only at the moment. Can one of you look up and link to some docs on write apis, and change the title of this post to reflect a need for a write API?

**Comment by ryzokuken** [comment]
Sure, will do. Also, I was thinking that if we haven't completed the API,
we could try and use GraphQL in order to get webhooks for posts and comments

**Comment by jywarren** [comment]
I'm interested but one thing at a time! I'm really eager to get the bot
integration with the existing API, and in unit and functional testing our
API. We should also build it out with more - many things could be routed
through the API to reduce complexity of code.

**Comment by jywarren** [comment]
I think #1449 is the best place to start!
