### ISSUE TITLE
Need Flag Option for Spam: Research Notes, comments, wiki pages

### ISSUE THREAD

**Issue by Zengirl2** [publiclab/plots2#1487]
I recently spotted a spam research note for an escort service. I didn't have the admin to delete it, but it would be great if there was a flag option. That way a reader could flag it so a moderator could take it down.

**Comment by jywarren** [comment]
Thanks, Leslie! I was hoping we coudl do this pretty easily just by having
the flag icon button go to:

> mailto:moderators@publiclab.org

We can reform this into a First-Timers-Only issue!

**Comment by ebarry** [comment]
Can we expand this to a "flag as spam" button on all content?

**Comment by jywarren** [comment]
let's add one-by-one follow-up tasks rather than expand this one, but yes!

**Comment by jywarren** [comment]
This could be done in multiple places, but to copy in code I prepared for a MapKnitter version of this:

```ruby
<a rel="tooltip" title="Flag as spam." class="btn btn-sm btn-default" href="mailto:moderators@publiclab.org?subject=Reporting+spam+on+MapKnitter&body=Hi,+I+found+this+map+that+looks+like+spam+or+needs+to+be+moderated:++http://mapknitter.org/maps/<%= map.slug %>+by+http://mapknitter.org/profile/<%= map.user.login %>+Thanks!">
  <i class="far fa-flag"></i>
</a>
```

**Comment by jywarren** [comment]
Awesome, opened the first one for comments here: #2412

**Comment by ebarry** [comment]
Yes, these do look great on the dashboard -- thanks all! It would be great to break the rest of these issues out as described above ^^

**Comment by jywarren** [comment]
#2657 completed in https://github.com/publiclab/plots2/pull/2674 -- great! Let's repeat for the above. 

@publiclab/soc would anyone like to take a look at #2657 as an example and build an almost identical one for flagging Answers or flagging Comments upon answers, as outlined above? 

If you haven't created a `first-timers-only` issue yet, or would like a chance to create another, this is a good example, and you can see how a very similar one was created, claimed, and solved. 🎉 😄 🥇 

I and the rest of @publiclab/reviewers would be happy to help you create a FTO issue and ensure it's well formatted. See these resources:

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://publiclab.github.io/community-toolbox/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by stefannibrasil** [comment]
Hello, @jywarren I can help, but I am finishing some things this week, so I can commit to it only next week.

If someone else can work on this right away, go ahead, otherwise, I'll mark it to start next week. Is that okay? :)

**Comment by jywarren** [comment]
of course! Thank you!

**Comment by stefannibrasil** [comment]
Hi, @jywarren I created two new issues #2731 and #2732. What do you think? Also, I wans't able to add the labels to them, could you help me? :)

**Comment by jywarren** [comment]
Wow! Sorry, little late on this but looking now. Tremendous!

**Comment by jywarren** [comment]
OK I invited you as a reviewer!!!

@Zengirl2 look at the great team pitching in to solve this! Thanks everybody!!!

**Comment by stefannibrasil** [comment]
Awesome, thanks! :tada:

**Comment by Zengirl2** [comment]
Thanks everyone! Looking forward to a spam-free zone.

**Comment by jywarren** [comment]
I'm marking this as a good candidate because folks looking to get involved can read over the original solution in #2657 which was completed in #2674, and reapply this to other places where we could use a flag button. 

Can folks identify places where this is still needed? We can start linking to the corresponding templates and get this completely wrapped up!

**Comment by oorjitchowdhary** [comment]
Hi all, I think the `flag as spam` button is active everywhere now.. wikis, questions, notes, comments, answers, and comments on answers

So I think we can close this 
Thanks

**Comment by jywarren** [comment]
Indeed, thank you!!
