### ISSUE TITLE
Emails about new research notes lack body text

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1490]
### What happened just before the problem occurred

A new note was posted, but it only included the lead image, and nothing else from the post:

```
Dear warren,

Public Lab contributor cfastie just posted a new research note entitled 'Mini Pearl Jam':

Read and respond to the post here: https://publiclab.org/notes/cfastie/07-01-2017/mini-pearl-jam

[IMAGE HERE]

Does this look like spam? Spam
You received this email because you are subscribed to the following tags: everything.

To change your preferences, please visit https://publiclab.org/subscriptions.

Report spam and abuse to: moderators@publiclab.org

Check out the blog at https://publiclab.org/blog | Love our work? Become a Public Lab Sustaining Member today at https://publiclab.org/donate
```

This template is here: https://github.com/publiclab/plots2/blob/master/app/views/subscription_mailer/notify_node_creation.html.erb

This line is supposed to print the body text:

```ruby
<%= raw auto_link(@node.latest.render_body_email(ActionMailer::Base.default_url_options[:host]), :sanitize => false) %>
```

Compare to how it's printed out in a note on the site:

```ruby
  <%= raw auto_link(insert_extras(@node.latest.render_body), :sanitize => false) %>
```

`render_body_email` adds absolute full URLs instead of ones starting with `/` -- https://github.com/publiclab/plots2/blob/master/app/models/drupal_node_revision.rb#L112

**Comment by viren140290** [comment]
@jywarren If I may, I would like to work on this issue.

**Comment by Kevin-Kawai** [comment]
@viren140290 hey are you still working on this? I would like to help if you would be down.

**Comment by Kevin-Kawai** [comment]
@jywarren Hi, I was checking out this issue and I think I'm a little confused as to the details. Is this more of a "look into" type of issue at the current state?

**Comment by jywarren** [comment]
I think so. I was receiving some emails from the site that were just an
image with no body text. I think we can assess this via testing, but it may
take some more looking into... thanks!

**Comment by Kevin-Kawai** [comment]
@jywarren alrighty great, I was just wondering because I was able to reproduce it immediately. I'll try a hand full of things to see if I can figure it out. I'll let you know if anything comes to light.

**Comment by jywarren** [comment]
Ah, you were able to reproduce the error or the successful full email? If
the error, might you try writing a test for it? Thanks!!!

**Comment by Kevin-Kawai** [comment]
@jywarren Sorry I meant I wasn't able to recreate the error. But I was only able to spend a little time on it so I'll try some thing and get back to you if the email is an error.

**Comment by jywarren** [comment]
That sounds great -- many thanks.
