### ISSUE TITLE
Merge tag_test.rb into /test/unit/tag_test.rb and ensure following == true

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1507]
This is a followup issue for @StlMaris123 -- 

I noticed that the unit test you created at 

https://github.com/publiclab/plots2/blob/master/test/models/tag_test.rb

really should be copied into the existing unit test file:

https://github.com/publiclab/plots2/blob/master/test/unit/tag_test.rb

This should be pretty easy, since they're the same format, you can just move the tests into the end of the other file.

Second, @ujithaperera noticed that the `followers_who_dont_follow_tags` method does not check if the value of `tag_selection` is true -- @ujithaperera can you add to the unit test to ensure that the value is true? Then the test will fail (test-driven-development!) and then @StlMaris123 can add the extra condition. 

There actually may not already be any `tag_selection` data in the test fixtures where `following == false` but we can add that in to ensure a good test; add it to this file:

https://github.com/publiclab/plots2/blob/master/test/fixtures/tag_selection.yml

Thank you both!

**Comment by StlMaris123** [comment]
Are two fixtures okay for the test?

**Comment by jywarren** [comment]
Sure!

**Comment by jywarren** [comment]
Complete!
