### ISSUE TITLE
[priority] Non-latin characters blocking latest database migration

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1515]
This is being actively worked on by @jywarren and @icarito --

The latest database migration causes this error on the staging server:

```

Mysql2::Error: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=': SELECT  `rusers`.* FROM `rusers`  WHERE `rusers`.`username` = 'トリーバーチ クラッチ' LIMIT 1/app/app/models/drupal_users.rb:32:in `user'
/app/db/migrate/20170704165711_add_user_bio_and_token.rb:11:in `block in up'
/app/db/migrate/20170704165711_add_user_bio_and_token.rb:9:in `up'
ActiveRecord::StatementInvalid: Mysql2::Error: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=': SELECT  `rusers`.* FROM `rusers`  WHERE `rusers`.`username` = 'トリーバーチ クラッチ' LIMIT 1
/app/app/models/drupal_users.rb:32:in `user'
```

See log here: http://jenkins.laboratoriopublico.org/job/Plots-Staging/lastFailedBuild/console

Attempted fix in https://github.com/publiclab/plots2/pull/1514 didn't work; that skipped records for which:

```ruby
if u.name == u.name.encode('UTF-8') # exclude non-UTF-8 names
```

What else can we do to screen usernames like `'トリーバーチ クラッチ'`?

**Comment by jywarren** [comment]
Actually pasting that string into my console freezes my console... so it's hard to test out manually...

**Comment by jywarren** [comment]
We could try:

```ruby
!u.name.match(/([\p{Hiragana}\p{Katakana}\p{Han}]+)/)
```

http://rubular.com/r/mnDI7lS96P

That seems a bit weird but would probably work? (https://stackoverflow.com/questions/21272853/regex-detecting-all-japanese-characters-in-a-string-and-wrapping-the-substrings)

Or maybe: 

```ruby
!u.name.multibyte?
```

via https://stackoverflow.com/questions/7200321/rails-detect-foreign-characters#7201988

**Comment by jywarren** [comment]
Yeah to revert back the db I did:

```
mysql> use plots
mysql> ALTER TABLE rusers DROP COLUMN bio;
mysql> ALTER TABLE rusers DROP COLUMN token;
mysql> ALTER TABLE rusers DROP COLUMN status;
mysql> ALTER TABLE rusers ADD COLUMN location_privacy BOOLEAN;
```

**Comment by jywarren** [comment]
Trying again in #1517

**Comment by jywarren** [comment]
and again in #1518. What misery!

**Comment by jywarren** [comment]
Hooray! Fixed in #1518!
http://tycho.media.mit.edu:8080/job/Plots-Staging/150/

Whew!

**Comment by icarito** [comment]
@jywarren - I wasn't at the monitor as this evolved. Encoding issues are **hard**! So glad this was caught in staging and not in production!

**Comment by icarito** [comment]
And congratulations on solving it!

**Comment by jywarren** [comment]
:-)
