### ISSUE TITLE
increase visual/design difference between wikis and research notes

### ISSUE THREAD

**Issue by dbeavers** [publiclab/plots2#152]
Consider contrasting the difference between a wiki and a research note.  Currently the way I tell them apart mainly is by looking at the URL.  I would suggest something like changing the background color or pattern to differentiate between the two.

**Comment by CleverFool77** [comment]
@jywarren Is this issue available? I would like to work on this :)

**Comment by gauravano** [comment]
Yes @CleverFool77,  it's available. We would love to have your help with this. 

As you can see there is no clear checklist available so let's ask @jywarren and @btbonval if they have anything in mind regarding the change in design of wiki or note? 

Thanks!

**Comment by jywarren** [comment]
Hi! I think we need to brainstorm a bit on this! What ideas do you have
that could help to distinguish these pages? I had one - that the wiki page
titles could be centered, and have a different header and tabs maybe?

Anyone want to do some sketches to explore ideas?

**Comment by gauravano** [comment]
@CleverFool77 are you trying the changes as suggested by @jywarren?

**Comment by CleverFool77** [comment]
I'm considering about the sketches @gauravano  @jywarren. I'll post the idea here soon.

**Comment by gauravano** [comment]
Great!

**Comment by CleverFool77** [comment]
@jywarren @gauravano I had a question.
Isn't the difference between notes and wiki already specified as the notes are specified in one place whereas wikis have different column given to them. 
Or is there any other page which I might be unaware of or I'm not looking at, where there is no distinction ?

**Comment by CleverFool77** [comment]
https://publiclab.org/notes/lekhidugtal/03-12-2019/create-a-visual-difference-in-wikis-and-notes?_=1552414881

In this, How about making the wikis more centered , like in Medium. And taking  the explore tags beneath. So that User can focus on the information provided in the article. 
@jywarren @gauravano

**Comment by gauravano** [comment]
We can try that @CleverFool77

**Comment by jywarren** [comment]
Hm, interesting, i like the centered idea!

**Comment by jywarren** [comment]
I made some changes along the lines @CleverFool77 suggested and this looks complete now!!! Thank you!!!
