### ISSUE TITLE
Add bio and token to seed data

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plots2#1521]
Currently, the bio for the seed data is set to `nil` instead of `''`.

@jywarren what went wrong?

![screenshot-2017-7-11 action controller_ exception caught](https://user-images.githubusercontent.com/13121330/28084975-fb694c80-6697-11e7-8e0f-6ff0eb6043d8.png)

**Comment by jywarren** [comment]
Hi, @ryzokuken - we had quite a bit of trouble with this one over the
weekend, and found that mysql did not like default values on blob/text
columns. I think that the easiest way to address this may be to replace
`@profile_user.bio` with `@profile_user.bio || ''`, unfortunately? Do you
have another suggestion?

**Comment by ryzokuken** [comment]
@jywarren yes, that sounds pretty good, tbh. I will submit a PR with the change soon.
