### ISSUE TITLE
/stats/subscription page is broken

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1525]
#There is an incorrect link at the top of https://publiclab.org/stats that needs updating. 
The text "subscription stats" goes to a non-existent page (https://publiclab.org/stats/subscriptions) ~but it should link to https://publiclab.org/subscriptions~

![screen shot 2017-07-12 at 10 26 40 am](https://user-images.githubusercontent.com/161439/28122608-ad531e4a-66ec-11e7-91a3-8ad877182d5a.png)

Thank you!

**Comment by ebarry** [comment]
Update: now i'm not sure. /subscriptions only shows personal subscriptions attached to the user account that's logged in. The page is not publicly visible, and it's not comprehensive for subscriptions across the entire site.

**Comment by jywarren** [comment]
I think the page for https://publiclab.org/stats/subscriptions is not supposed to be the same as https://publiclab.org/subscriptions -- so https://publiclab.org/stats/subscriptions is broken, not leading to the wrong place. 

Yes, i checked our "routes" file and /stats/subscriptions is its own page, which seems broken -- I'll update the title.

We should write a functional test for this page, then also check what the failure is. There may already be a test in `/tests/functional/stats_controller_test.rb` but that's where to start. Thanks!

**Comment by ebarry** [comment]
Wow great catch!

**Comment by jywarren** [comment]
@sagarpreet-chadha offered a solution in #1717; it's been made into a `fto-candidate`. Thanks!
