### ISSUE TITLE
add ability to subscribe to tags from publiclab.org/tags

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1526]
Currently, publiclab.org/tags shows number times a tag is in use. 

![screen shot 2017-07-12 at 10 36 03 am](https://user-images.githubusercontent.com/161439/28123048-f3f8b4bc-66ed-11e7-9928-e2cae3e7bd5d.png)

Let's add two columns: 
1.) for subscribing to a tag, 
2.) for subscribing to answer questions about this tag. Code for this already exists on question pages, see: https://publiclab.org/questions/ccpandhare/07-08-2017/how-to-verify-if-my-programmatically-generated-ndvi-version-of-an-image-is-correct

![screen shot 2017-07-12 at 10 53 08 am](https://user-images.githubusercontent.com/161439/28123981-5e89ce68-66f0-11e7-981c-5677ae056f0e.png)

Let's also provide a link on publiclab.org/tags to publiclab.org/subscriptions so that someone to easily see all their subscriptions: 
![screen shot 2017-07-12 at 10 37 08 am](https://user-images.githubusercontent.com/161439/28123105-17f67318-66ee-11e7-86fb-20d5674ecc95.png)

**Comment by jywarren** [comment]
The code for the "subscribe" button is here:

https://github.com/publiclab/plots2/blob/master/app/views/tag/show.html.erb#L42-L47

```ruby
      <% if current_user.following(params[:id]) %>
      <a rel="tooltip" title="<%= t('tag.show.unfollow') %>" class="btn btn-default btn-sm active" href="/unsubscribe/tag/<%= params[:id] %>"><i class="fa fa-eye"></i> <%= t('tag.show.following') %> <b><%= params[:id] %></b></a>
      <% else %>
      <a class="btn btn-default btn-sm" href="/subscribe/tag/<%= params[:id] %>"><i class="fa fa-eye"></i> <%= t('tag.show.follow') %> <b><%= params[:id] %></b></a>
      <% end %>
      <a class="btn btn-default btn-sm" rel="popover" data-placement="bottom" data-html="true" data-title="<%= t('tag.show.users_following_tag') %>" data-content="<% Tag.followers(params[:id]).each do |user| %><i class='fa fa-star-o'></i> <a href='/profile/<%= user.username %>'><%= user.username %></a><br /><% end %><% if Tag.follower_count(params[:id]) == 0 %><i><%= t('tag.show.none') %></i><% end %>"><%= Tag.follower_count(params[:id]) %> <i class="fa fa-user"></i> <span class="caret"></span></a>
```

This could be copied into the tag index page that Liz screenshotted above:

https://github.com/publiclab/plots2/blob/master/app/views/tag/index.html.erb#L16

A possibly simpler implementation is here on the Subscriptions page, that could also be copied in instead:

https://github.com/publiclab/plots2/blob/master/app/views/home/subscriptions.html.erb#L8-L12

```ruby
    <% if current_user.following("everything") %>
      <a rel="tooltip" title="<%= t('home.subscriptions.click_unfollow') %>" class="btn btn-default active" href="/unsubscribe/tag/everything"><i class="fa fa-eye"></i> <%= t('home.subscriptions.following') %> <b><%= t('home.subscriptions.research_notes') %></b></a>
    <% else %>
      <a href="/subscribe/tag/everything" class="btn btn-default"><i class="fa fa-tag"></i> <%= t('home.subscriptions.subscribe_to') %> <b><%= t('home.subscriptions.all') %></b> <%= t('home.subscriptions.notes') %></a>
    <% end %>
```

**Comment by amitsin6h** [comment]
@jywarren can I work on this issue as my first contribution.

**Comment by jywarren** [comment]
Sure, yes please! Happy to help, too.

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by Diksha2008** [comment]
@jywarren I would like to work on this issue!

**Comment by jywarren** [comment]
Yes please! That would be great!

**Comment by Diksha2008** [comment]
@jywarren Adding the following code for subscribe button redirects the page to `/subscriptions` when clicked. How could I avoid that? Using AJAX or some unobtrusive js request? How could I implement toggling?Please help!
```
      <% if current_user.following(params[:id]) %>
      <a rel="tooltip" title="<%= t('tag.show.unfollow') %>" class="btn btn-default btn-sm active" href="/unsubscribe/tag/<%= params[:id] %>"><i class="fa fa-eye"></i> <%= t('tag.show.following') %> <b><%= params[:id] %></b></a>
      <% else %>
      <a class="btn btn-default btn-sm" href="/subscribe/tag/<%= params[:id] %>"><i class="fa fa-eye"></i> <%= t('tag.show.follow') %> <b><%= params[:id] %></b></a>
      <% end %>
      <a class="btn btn-default btn-sm" rel="popover" data-placement="bottom" data-html="true" data-title="<%= t('tag.show.users_following_tag') %>" data-content="<% Tag.followers(params[:id]).each do |user| %><i class='fa fa-star-o'></i> <a href='/profile/<%= user.username %>'><%= user.username %></a><br /><% end %><% if Tag.follower_count(params[:id]) == 0 %><i><%= t('tag.show.none') %></i><% end %>"><%= Tag.follower_count(params[:id]) %> <i class="fa fa-user"></i> <span class="caret"></span></a>
```

**Comment by jywarren** [comment]
I think that for now it's all right if it redirects there. We can think about this interaction and do a follow-up issue if it doesn't seem to work for people. Thanks for your attention to detail though!

**Comment by jywarren** [comment]
Could you also add a column for "# of people subscribed"? That's generated here on this template:

https://github.com/publiclab/plots2/blob/master/app/views/home/subscriptions.html.erb#L35

The code is:

```ruby
<%= Tag.follower_count(subscription.tagname).to_i-1 %>
```
