### ISSUE TITLE
delete search form from sidebar on publiclab.org/questions

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1527]
There seems to be a redundant text entry box in the sidebar of /questions. 
Depending on what we figure out about this, i propose removing it. 

See this video showing how I try to type water into both text boxes and am offered too many options: 
<a href="https://publiclab.org/system/images/photos/000/021/102/original/Q_A-interface.mov"><i class="fa fa-file"></i> Q_A-interface.mov</a>

**Comment by jywarren** [comment]
Just a note that the sidebar form does a distinct thing from the main
input, which is to display listings of questions by tag, rather than search
for individual questions matching the search term.

Not saying it's not reasonable to rework this interface, just clarifying
the current design.

Thanks!

**Comment by jywarren** [comment]
Hi, Liz, I'm closing this until it can be reconciled with the UI design work at https://publiclab.org/notes/siyuan/06-12-2017/a-questions-page-to-encourage-discussions-through-better-ux

Thanks!
