### ISSUE TITLE
Research note as event on calendar

### ISSUE THREAD

**Issue by dbeavers** [publiclab/plots2#153]
Would it be a good idea to have events placed on the PL calendar automatically?  There could be a check box to enable it and perhaps it would be restricted to organizers.  This probably needs a fair amount of discussion.

**Comment by ebarry** [comment]
are any of the new awesome developments on the site lending themselves to revisiting this functionality?

**Comment by jywarren** [comment]
Not really -- but if someone could look into ways to
automatically/programmatically add events to a Google Calendar, we could
try. Maybe with IFTTT.com?

**Comment by jywarren** [comment]
I think this may be possible in Google Calendar with the following format:

`http://www.google.com/calendar/event?action=TEMPLATE&text=Public Lab Event&details=&location=&trp=false&sprop=website:http://publiclab.org&ctz=America/Chicago`

A simpler version works as follows: http://www.google.com/calendar/event?action=TEMPLATE&text=Public Lab Event&details=Details of the event&sprop=website:http://publiclab.org

This should be pretty straightforward to implement using this URL scheme. 

I recommend we also make the calendar buttons larger so people use them. 

We could also show a "subscribe to the PL Events calendar" general link at this point.

**Comment by jywarren** [comment]
Tips on making Google Calendar URLs:

* https://stackoverflow.com/questions/22757908/google-calendar-render-action-template-parameter-documentation

**Comment by jywarren** [comment]
I have an IFTTT recipe in testing right now -- it works, but who is owner for the PL events calendar? I need to enter that account's info in so events get posted on the correct calendar.

**Comment by steviepubliclab** [comment]
I can't tell who owns it. It doesn't say in the settings as far as I can
tell. Seems like the highest level of access are people who have the status
"*Make changes AND manage sharing" *
-Stevie

**Comment by ebarry** [comment]
It might be my "ebarry" gmail account that's the owner, because at the very bottom of the settings and sharing page i have the option to "DELETE" it permanently.

**Comment by jywarren** [comment]
I think I've hooked this up now via IFTTT -- 

https://publiclab.org/notes/imvec/02-04-2018/hack-the-earth-6th-edition-open-call generated an event although it seemed to be one day early...

We should be able to just add an `event:rsvp` and `date:02-06-2018` to any note and wait a bit, then look on http://publiclab.org/events to see it appear.

**Comment by jywarren** [comment]
This is complete!
