### ISSUE TITLE
add two new queries to publiclab.org/stats

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1530]
Add new query types to https://publiclab.org/stats

* comments
* answers
* questions

Keep in mind that the date range of these queries has to be adjustable by URL, for instance see https://publiclab.org/stats/range/10-05-2015/10-05-2016/

Solving this will require customizing the mysql queries. 

Here's what @icarito has already written towards this: 
* for comments: mysql> select count(*) from comments where timestamp>1451606400 and timestamp<1483228800;
* for answers (required additional timestamp conversion): mysql> select count(*) from answers where created_at>FROM_UNIXTIME(1451606400) and created_at<FROM_UNIXTIME(1483228800);    

Solving this also requires figuring out how to print out the answers on publiclab.org/stats

**Comment by jywarren** [comment]
Template is: https://github.com/publiclab/plots2/blob/ea5aa0f2ec08849107afec0fa546a270ae3d968d/app/views/stats/index.html.erb

Controller where queries can be added: https://github.com/publiclab/plots2/blob/ea5aa0f2ec08849107afec0fa546a270ae3d968d/app/controllers/stats_controller.rb#L26

Should be something like:

```ruby
@comments = Comment.where(created_at: @time - 1.weeks..@time).count
```

**Comment by ebarry** [comment]
More info from the evaluation team, we'll be needing to answer these at the end of the year (every year): 
* how many activities were replicated how many times? how many unique people replicated something?
* how many questions, how many answers, AND **how many unanswered questions (if any?)**

### Full text from the evaluation team: 

Metric 2:  Increase in collaboration, novel engagement, and community self-sufficiency as indicated by the number of questions and answers posted to the Public Lab website using the “Q/A” feature, launched in late summer 2016. We aim to achieve a 100% answer rate. 

Metric 3:  Number of instances of replication of a Public Lab method or assay, as measured by participation in new “activity grid” feature (rolled out in late fall 2016).

**Comment by jywarren** [comment]
OK, i've broken this into 3-6 pieces and reposted as a first-timers issue: https://github.com/publiclab/plots2/issues/1667

Thanks!
