### ISSUE TITLE
Figure out why "map of maps" link stopped working

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1531]
Seems like https://mapknitter.org/map/map has stopped working. 
It should generate a point map of all the maps in mapknitter.org
This display is known to be heavy, perhaps my computer cannot render it. 

![mapofmaps](https://user-images.githubusercontent.com/161439/28127299-0610e1fe-66fa-11e7-8afa-551ac51cd3c8.png)

**Comment by jywarren** [comment]
Ah, sorry, but this is for the MapKnitter repository - can you move it over there? Thanks!

**Comment by jywarren** [comment]
Closing, please open this on the MapKnitter repository, thanks!
