### ISSUE TITLE
/questions page not showing any questions when logged in

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1532]
I have this problem most of the time -- but not all the time -- when trying to use the publiclab.org/questions interface. Does this happen to anyone else?

<a href="https://publiclab.org/system/images/photos/000/021/103/original/Q_A_bug.mov"><i class="fa fa-file"></i> Q_A_bug.mov</a>

**Comment by ebarry** [comment]
i'm not seeing this on my new(er) computer, so will close this (for now at least)

**Comment by ebarry** [comment]
I just opened /questions on my new(er) computer and again, the questions do not appear: 
<img width="1006" alt="screen shot 2017-09-04 at 3 33 01 pm" src="https://user-images.githubusercontent.com/161439/30037061-5ae56e82-9186-11e7-868d-fbe5d59a8895.png">

**Comment by jywarren** [comment]
that is really weird Liz. Can you confirm this does not occur when you're not logged in (i.e. incognito mode)? 

Can you also check on your phone? 

I'm changing the title of this issue, as well. This can help make it more readable, especially in list form. 

Thanks for reporting!

**Comment by jywarren** [comment]
And if you find this is only on laptop or only when logged in, you can refine the title & description accordingly, like `...when logged in` for example.

**Comment by jywarren** [comment]
Also created a label called `more-detail-please` for this kind of thing. Thanks!

**Comment by ebarry** [comment]
When i use an incognito window where I am not logged in, I SEE THE QUESTIONS!
Perhaps relevant is that I use ad-blockers in Chrome?

**Comment by jywarren** [comment]
Can you turn off your ad blocker to test that theory?

Alternatively if you use your phone or Firefox to view the page while logged in, can you check that too?

**Comment by ebarry** [comment]
* i can see it on my phone (android, chrome) while logged in. 
* i can see it in Safari whether logged in or not logged in
* (seems like) i do not actually have any adblockers in chrome on this new computer

**Comment by jywarren** [comment]
Great, VERY helpful, thanks liz. Can you now try to clear your cache and cookies in Chrome and look again while logged in?

https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en

We'll get there!

**Comment by ebarry** [comment]
No problems lately! 
Is it really gone? i don't know. Willing to close for now.

**Comment by jywarren** [comment]
:-) feel free to re-open if you see it again!!!
