### ISSUE TITLE
user lookup by email doesn't check the old user table

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#154]
We should add a lookup against the old user table as well.

Migrating users is challenging if they don't recall their usernames. Being able to look up a username by email address for migration can also save a back-and-forth email volley.

**Comment by jywarren** [comment]
I'd like to change this to: `Generate User records for any solo DrupalUsers records in a migration` if this doesn't exist already -- otherwise, we can assume User records are up to date and DrupalUsers email records are out of date. Sound good?

**Comment by gauravano** [comment]
Hi everyone, as we have deprecated DrupalUser -https://github.com/publiclab/plots2/pull/2857. I think this can be closed? Feel free to re-open the issue, if required.

Thanks!

cc @jywarren
