### ISSUE TITLE
rvm install 2.1.2 fails with error 2

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plots2#1540]
Whenever I try to install ruby 2.1.2 on my Antergos installation, `rvm install 2.1.2` fails with the following error:

```
Error running '__rvm_make -j4',
showing last 15 lines of /home/ryzokuken/.rvm/log/1500125001_ruby-2.1.2/make.log
make[2]: *** [Makefile:280: ossl_engine.o] Error 1
make[2]: *** [Makefile:280: ossl_cipher.o] Error 1
make[2]: Leaving directory '/home/ryzokuken/.rvm/src/ruby-2.1.2/ext/openssl'
make[1]: *** [exts.mk:187: ext/openssl/all] Error 2
make[1]: *** Waiting for unfinished jobs....
installing default callback libraries
linking shared-object pathname.so
make[2]: Leaving directory '/home/ryzokuken/.rvm/src/ruby-2.1.2/ext/pathname'
linking shared-object nkf.so
make[2]: Leaving directory '/home/ryzokuken/.rvm/src/ruby-2.1.2/ext/nkf'
linking shared-object dl/callback.so
make[2]: Leaving directory '/home/ryzokuken/.rvm/src/ruby-2.1.2/ext/dl/callback'
make[1]: Leaving directory '/home/ryzokuken/.rvm/src/ruby-2.1.2'
make: *** [uncommon.mk:180: build-ext] Error 2
++ return 2
There has been an error while running make. Halting the installation.
```

**Comment by ryzokuken** [comment]
@jywarren 
```
WARNING: ruby-2.1.2 is past its end of life and is now unsupported.
It no longer receives bug fixes or critical security updates.
```

I think this is now high time we migrated to something new.
This version fails to build on my system with an updated version of openssl anyway.

**Comment by ananyo2012** [comment]
I guess the Ruby version should not be relevant with installation. We even removed the Ruby version line from Gemfile for this reason as per I remember.

**Comment by jywarren** [comment]
Yes, agreed; what version should we switch to, and also where is the reference to 2.1.2 in the codebase? Thanks!

**Comment by ryzokuken** [comment]
I don't really think there's an explicit reference to version 2.1.2 inside the codebase, however, we ask contributors on the README to install version 2.1.2 and this version is known to work perfectly for our use case. Maybe we're also using the same version in production?

Re:Migration, I think strongly that we should migrate to Rails 5 because it will be supported for a longer time and I think will take similar amount of time and hardwork compared to any other version (eg: 4.2)

**Comment by ryzokuken** [comment]
That said, I did figure out a way to solve this and successfully installed Ruby 2.1.2 on my machine. The steps I used were:

```
rvm pkg install openssl
rvm install 2.1.2 --with-openssl-dir=$HOME/.rvm/usr
```

closing this as the issue is finally solved.

@jywarren should I document this somewhere for people who face similar issues until we complete the migration?
