### ISSUE TITLE
New user creation on staging

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1543]
### What happened just before the problem occurred

I went to http://staging.laboratoriopublico.org/signup and tried to create a new account.

I got an error, and the logs showed:

```
Processing by UsersController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"jAuewf43tbci+bgJC+dgxsL72She+0hUuXdleQQhLMM=", "user"=>{"username"=>"warren11", "email"=>"jywarre.n@gmail.com", "pa
ssword"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "drupal_user"=>{"bio"=>""}, "g-recaptcha-response"=>"03AEHxwuzHbMhtb7TIYRu1ooqch9bhttiOllSSSg3wh6wYxNxo
iOzkRSpWu6OxGsAGg85L48B3_kJECR56_3LdmkWkN_6JncTqOxeBc_fizRxn3cZHo0pb_u52ffnJcZD3BIfPY9Lj8zSNNzIOLJxEaeVW3LIhk9VLIU3gb-DGhbh-6wYy21DpeNxrBQIMUu5sj5I19pDouqPhU9ZO6BJ8jj
J3g8kSHqcUoxthRHXPpuWGgZOjMASKveP3-e1Piuve_FI1vXCqLqGEISokf-pBHw3b6ps83e7ruRM8RSvFBX66eTXIy3E0YCr_pQRVtRsbIQyYNbrgl9ZD"}
  Rendered welcome_mailer/add_to_list.text.erb (0.3ms)

Sent mail to publiclaboratory+subscribe@googlegroups.com (10.5ms)
Completed 500 Internal Server Error in 1806.7ms

Errno::ENETUNREACH (Network is unreachable - connect(2) for "localhost" port 25):
  app/mailers/welcome_mailer.rb:11:in `add_to_list'
  app/models/user.rb:134:in `block in add_to_lists'
  app/models/user.rb:133:in `each'
  app/models/user.rb:133:in `add_to_lists'
  app/controllers/users_controller.rb:23:in `create'
```

That's on this line:

`        @user.add_to_lists(['publiclaboratory'])`

So, i think it's just because it doesn't have a mailer set up. It goes to this line:

https://github.com/publiclab/plots2/blob/master/app/mailers/welcome_mailer.rb#L11

`    mail(to: list + '+subscribe@googlegroups.com', subject: subject, from: user.email).deliver`

Since this is running in production mode, I don't know of an easy way to deactivate this line for staging. I'm not totally sure why it doesn't seem to cause trouble on commenting, for example, which would also show an error.

It may also be related to #1541? @ryzokuken @icarito 

I'm going to deploy this to master because i think this is an isolated issue that's not going to affect a system with a mailer properly set up.

**Comment by ryzokuken** [comment]
@jywarren I think it's the same issue, we will probably need to look into it though. Mine showed some problem with the User model.

**Comment by jywarren** [comment]
I'm not convinced it is -- I just deployed to production, and made a new
user successfully! https://publiclab.org/profile/warren111

The bio saved properly. So I think we can close that PR.

But the token did not -- can you open a new issue? It just shows blank for
some reason, not sure why.

**Comment by ryzokuken** [comment]
Okay, I will. Will also try making a user for plotsbot again on staging.

**Comment by jywarren** [comment]
I actually think you won't be able to -- due to the email not being
connected up. But you can try on an old note on PublicLab.org where only
you and I are following -- look at the oldest notes in my history!

**Comment by ryzokuken** [comment]
Okay.

**Comment by ryzokuken** [comment]
@jywarren One note though: I see this on staging while making a new user.

https://screenshots.firefox.com/YgXRFqn89tMF2k8r/staging.laboratoriopublico.org

**Comment by ryzokuken** [comment]
Meanwhile: making a user on the production website, will only post comments to super old thread after you agree to it.

**Comment by jywarren** [comment]
Great. Yes on staging we used the ReCaptcha test string. It still works but
it doesn't stop any bots.

**Comment by icarito** [comment]
This, combined with #1549, makes me think that we made a wrong migration. Note that there was a change to the model to accomodate the migration https://github.com/publiclab/plots2/commit/fdf19ec637db27f8e6b76049e90ab15f59770e54 I'm not experienced with rails, but sounds to me like we need to recover data from backups from 16 days ago?

**Comment by jywarren** [comment]
I think so. Can we have that data ready to re-insert the bio fields we may have overwritten, and in the meantime fully investigate both the errors that occurred using staging, and implement a fix? We can probably re-import the bio fields at whatever time we like, however -- doesn't have to wait for the fix.

Also most likely we don't want to change the migration but rather add a new one if needed.

**Comment by icarito** [comment]
Okay I'll proceed with reloading the missing data, fields `bio`, `token`
and `status`. I'll run it thru staging first.

**Comment by icarito** [comment]
The process involves restoring the table into a new table with a different name, then performing an `UPDATE` and droping the temporary table.

**Comment by icarito** [comment]
Looking it over the data is actually not lost just not migrated either. So I guess crafting a new version of the failed migration https://github.com/publiclab/plots2/commit/fdf19ec637db27f8e6b76049e90ab15f59770e54 would make the missing data appear.

**Comment by icarito** [comment]
I was just about to go `UPDATE  rusers,profile_values set rusers.bio=profile_values.value where rusers.id=profile_values.uid` but since this needs a migration in ruby, I kindly request your help in debugging https://github.com/publiclab/plots2/commit/fdf19ec637db27f8e6b76049e90ab15f59770e54 ? I can facilitate or automate any test on staging ;-)

**Comment by ryzokuken** [comment]
@icarito I'll see what I can do, but honestly, I'm not that good with debugging database stuff.

@jywarren please help.

**Comment by icarito** [comment]
Okay with a fresher mind I think we can use my good old SQL here; https://stackoverflow.com/questions/14856856/how-to-write-sql-in-a-migration-in-rails
just need to create a new migration...

**Comment by icarito** [comment]
Okay I'm looking at the `rusers` table:
```
mysql> select distinct status from rusers ;                                                                                                  +--------+
| status |
+--------+
|      0 |
+--------+
1 row in set (0.31 sec)
```
but the migration said:
```
# copy bios into new fields for non-spam users
    DrupalUsers.where('status != 0').each do |u|
      user = u.user
      if user and defined? :u.status then
        user.status = u.status
        user.bio = DrupalProfileValue.find_by_uid(user.id, conditions: { fid: 7 }) || ''
        user.token = SecureRandom.uuid
        user.save({})
      end
    end
```
So the action wasn't taken for any users, because `status` is never `!=0`

**Comment by icarito** [comment]
I'm trying this:
```
class RecoverBiosTokensStatuses < ActiveRecord::Migration                                                                                    
  def up                                                                                                                                     
      DrupalUsers.find(:all).each do |u|                                                                                                     
        user = u.user                                                                                                                        
        if user                                                                                                                              
            user.status = u.status unless u.nil?                                                                                             
            user.bio = DrupalProfileValue.find_by_uid(user.id, conditions: { fid: 7 }) || ''                                                 
            user.token = SecureRandom.uuid                                                                                                   
            user.save({})                                                                                                                    
        end                                                                                                                                  
      end                                                                                                                                    
  end                                                                                                                                        
                                                                                                                                             
  def down                                                                                                                                   
      raise ActiveRecord::IrreversibleMigration                                                                                              
  end                                                                                                                                        
end
```
and getting this now:
```
==  RecoverBiosTokensStatuses: migrating ======================================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=': SELECT  `rusers`.* FROM `rusers`  WHERE `rusers`.`username` = 'トリーバーチ クラッチ' LIMIT 1/app/app/models/drupal_users.rb:32:in `user'
/app/db/migrate/20170726174757_recover_bios_tokens_statuses.rb:4:in `block in up'
/app/db/migrate/20170726174757_recover_bios_tokens_statuses.rb:3:in `each'
/app/db/migrate/20170726174757_recover_bios_tokens_statuses.rb:3:in `up'
ActiveRecord::StatementInvalid: Mysql2::Error: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=': SELECT  `rusers`.* FROM `rusers`  WHERE `rusers`.`username` = 'トリーバーチ クラッチ' LIMIT 1
/app/app/models/drupal_users.rb:32:in `user'
/app/db/migrate/20170726174757_recover_bios_tokens_statuses.rb:4:in `block in up'
/app/db/migrate/20170726174757_recover_bios_tokens_statuses.rb:3:in `each'
/app/db/migrate/20170726174757_recover_bios_tokens_statuses.rb:3:in `up'
Mysql2::Error: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='
/app/app/models/drupal_users.rb:32:in `user'
/app/db/migrate/20170726174757_recover_bios_tokens_statuses.rb:4:in `block in up'
/app/db/migrate/20170726174757_recover_bios_tokens_statuses.rb:3:in `each'
/app/db/migrate/20170726174757_recover_bios_tokens_statuses.rb:3:in `up'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by icarito** [comment]
Just a note that I implemented the solution in https://github.com/publiclab/plots2/blob/c00234b6357cc6e8d4d52e402955081d9ff55b25/db/migrate/20170704165711_add_user_bio_and_token.rb and it's ongoing in staging, about an hour now...

**Comment by jywarren** [comment]
oh, i didn't see this or a closely related issue was documented separately in #1549, and I posted notes there plus a fix in #1541 -- the stuff in the previous migration to filter out non-latin characters. But also note that the `find_by_` syntax returns just the whole record, not the `value` column, #1541 fixes that at least but may fail on the non-latin characters.

**Comment by jywarren** [comment]
Just to sum up here, we need to skip the `mail(...)` command if we're on staging if we want to solve this. Reposting the issue to reflect this. The rest of the comments are to an unrelated issue, so i'll make a new one and close this. 

Moving to #1570.

**Comment by icarito** [comment]
Another option which I think would be even better is that, since staging
needs to reflect production, we should set up the environment in such a
way that `mail()` doesn't do anything but also doesn't error out.

**Comment by jywarren** [comment]
+1!
