### ISSUE TITLE
Power tag change from "tool" to "method"

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#1545]
I was wondering if we could switch the tag that compiles materials on the /methods page to "method" instead of "tool" 

www.publiclab.org/methods

**Comment by jywarren** [comment]
Can help more soon but the line of code the change is needed on is here!

https://github.com/publiclab/plots2/blob/master/app/controllers/wiki_controller.rb#L355

**Comment by devaman** [comment]
I want to help on this but cannot understand the issue!!

**Comment by steviepubliclab** [comment]
Hi!
I can't help with the coding aspect of it (non-coder) but I can try to explain the issue as I meant when I posted it in non-coding terms.  

Currently, when someone adds the tag "tool" on to any wiki page right now, the page also becomes represented on this page:
- www.publiclab.org/methods 

For example [here's a page](https://publiclab.org/wiki/photo-sharing) with the tag "tool" and you can see it on the Methods wiki page now.

I'm hoping to get the power tag function switched so that what "tool" currently does, the tag "method" would do. I've gone and tagged all the pages with both, so everything should still show show up when this switch happens.

For back story:: For a while we were trying to decide whether to call these compiled materials pages "tools" or "methods." The power tag function was created for the word "tool" but we ultimately decided that we prefer the term "method." So hoping to get that power tag switched! 

Hope that makes sense! 
-Stevie

**Comment by devaman** [comment]
Thanks! It really helped me a lot.

**Comment by devaman** [comment]
I'll change the power tag but then we have to alter all tools tag to methods tag.Should I change the line mentioned by @jywarren?

**Comment by jywarren** [comment]
I *believe* the change would just be to change "tool" to "method" on this line, as referenced above:

```ruby
                 .where('term_data.name = ?', 'tool')
```

**Comment by jywarren** [comment]
Thanks!!
