### ISSUE TITLE
spectra won't embed in comments

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/plots2#155]
I can't seem to get spectra to show up when I embed them in comments.
![screen shot 2014-09-22 at 12 24 46 am](https://cloud.githubusercontent.com/assets/1203280/4352739/b294754c-4229-11e4-8126-656b657bf4aa.png)
 
![screen shot 2014-09-22 at 12 26 28 am](https://cloud.githubusercontent.com/assets/1203280/4352746/cafc61b2-4229-11e4-8aad-07dcf6b403ca.png)

**Comment by jywarren** [comment]
Fixed in swb 2.0
