### ISSUE TITLE
"Switch to legacy editor" should preserve content of page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1563]
This can be achieved with some JavaScript. The notice is here:

https://github.com/publiclab/plots2/blob/master/app/controllers/editor_controller.rb#L40

But we should probably move it into the HTML template here:

https://github.com/publiclab/plots2/blob/master/app/views/editor/rich.html.erb

Once we do that, we can use `editor.richTextModule.value();` from the [PublicLab.Editor project](https://github.com/publiclab/PublicLab.Editor) to fetch the markdown of the post and add it to the URL of the legacy editor with `?body=______` syntax. Same for the title and tags (although we won't be able to grab the lead image as easily)

**Comment by Pk13055** [comment]
Can I pick this up?

**Comment by jywarren** [comment]
Yes please!!! That would be great. I'm happy to add any info necessary!

**Comment by jywarren** [comment]
Did you need some help getting started with this? Thanks!

**Comment by Pk13055** [comment]
@jywarren  Sorry, I got caught up with something else, I'll get started on this, and get back to you if I need some help! Thanks

**Comment by Pk13055** [comment]
> ...Once we do that..

What is it exactly? From what I understood, I have to use JS to get the body markdown and add it [here](https://github.com/publiclab/plots2/blob/master/app/controllers/editor_controller.rb#L40). However, I do not see said line on the [html](https://github.com/publiclab/plots2/blob/master/app/views/editor/rich.html.erb), so where am I supposed to append it?

**Comment by jywarren** [comment]
Hi, so, I believe we have to set up an onClick listener, since we'll have to get the *latest* body text. So something like:

```js
$('.legacy-button').click(function onLegacyClick() {
  window.location = "/post?legacy=true&body=" + editor.richTextModule.value();
});
```

But, sometimes people arrive at the /post page with URL get parameters already set. So we may need to think about getting those too:

https://publiclab.org/post?tags=community,web-development,software,plots2,outreach

We can get those using `editor.tagsModule.value()` -- so let's append those to the end as well. The final URL in this case would be:

https://publiclab.org/post?legacy=true&tags=community,web-development,software,plots2,outreach&body=____

For title, `editor.titleModule.value()`. So I think we can assemble all three and add them to the URL. Make sense?

**Comment by jywarren** [comment]
Also, just mentioning @Fastie who originally requested this feature so he knows when it's complete. Hi, Chris!

**Comment by Diksha2008** [comment]
@jywarren If this issue is still available, can I work on it?

**Comment by jywarren** [comment]
Yes please! Thank you!

**Comment by jywarren** [comment]
I believe this has been solved, although I'm not sure it'll work for very complex existing body text. If we have trouble with that, we may want to look into submitting a synchronous POST request with the body text instead of trying to include it in the URL GET parameters.

**Comment by jywarren** [comment]
And thanks, @Dishka2008! We'll get this published in the next few days!

@icarito if you're comfortable publishing to production please go ahead!
