### ISSUE TITLE
Deep permalinks not working 

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#1564]
### What happened just before the problem occurred
It looks like the links that are embedded in pages (such as the table of contexts type links) aren't working. These are links that jump the reader to another spot in a page. Here are some examples: 

- https://publiclab.org/wiki/organizers-handbook  (with the embedded links such as https://publiclab.org/wiki/organizers-handbook#Getting+started, and https://publiclab.org/wiki/organizers-handbook#Resources+for+organizers)
- https://publiclab.org/wiki/frac-sand-action-oriented-resources (with the embedded links such as: https://publiclab.org/wiki/frac-sand-action-oriented-resources#Reporting and https://publiclab.org/wiki/frac-sand-action-oriented-resources#Monitoring)

**Comment by jywarren** [comment]
Ah, great catch. These are very hard to test for, so we don't automatically
catch it when a new change to the site breaks this.

These are called deep links -- can you change the title? Thanks!!!

**Comment by jywarren** [comment]
Think I've got this one. #1568.

**Comment by jywarren** [comment]
Thank you! Solved, will publish in next day or two.
