### ISSUE TITLE
Fails to precompile assets in production

### ISSUE THREAD

**Issue by icarito** [publiclab/plots2#1575]
### What happened just before the problem occurred
git pull

### Result:
```
plots@rs-plots2:~/production$ bundle exec rake -v -t assets:precompile
** Invoke assets:precompile (first_time)
** Execute assets:precompile
/srv/plots/.rvm/rubies/ruby-2.1.2/bin/ruby /srv/plots/.rvm/gems/ruby-2.1.2/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets --trace
** Invoke assets:precompile:all (first_time)
** Execute assets:precompile:all
** Invoke assets:precompile:primary (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Invoke tmp:cache:clear (first_time)
** Execute tmp:cache:clear
** Execute assets:precompile:primary
** Invoke assets:precompile:nondigest (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Invoke tmp:cache:clear (first_time)
** Execute tmp:cache:clear
** Execute assets:precompile:nondigest
/srv/plots/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/test/unit.rb:199:in `block in non_options': file not found: assets:precompile (ArgumentError)
        from /srv/plots/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/test/unit.rb:178:in `map!'
        from /srv/plots/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/test/unit.rb:178:in `non_options'
        from /srv/plots/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/test/unit.rb:237:in `non_options'
        from /srv/plots/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/test/unit.rb:58:in `process_args'
        from /srv/plots/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/minitest/unit.rb:1073:in `_run'
        from /srv/plots/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/minitest/unit.rb:1066:in `run'
        from /srv/plots/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/test/unit.rb:27:in `run'
        from /srv/plots/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/test/unit.rb:780:in `run'
        from /srv/plots/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/test/unit.rb:372:in `block (2 levels) in autorun'
        from /srv/plots/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/test/unit.rb:33:in `run_once'
        from /srv/plots/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/test/unit.rb:371:in `block in autorun'
```

**Comment by icarito** [comment]
This looks related:
https://stackoverflow.com/questions/18929452/block-in-non-options-file-not-found-argumenterror

**Comment by icarito** [comment]
If I can't find a simple solution here I'm considering moving forward with containers in production app.

**Comment by icarito** [comment]
Even if I can find a solution, I can't prevent this from happening again. That justifies the effort to tie the last loose ends to put plots2 in a Docker container in production: logging, lifecycle management, monitoring. @jywarren @ryzokuken nice tie with `plotsbot` chatops :-) @publiclab/soc

**Comment by icarito** [comment]
Here are the gem lists for both production and staging. @jywarren maybe you can figure out why the difference? Thanks!
[gem_list_20170809_staging.txt](https://github.com/publiclab/plots2/files/1212503/gem_list_20170809_staging.txt)
[gem_list_20170809_prod.txt](https://github.com/publiclab/plots2/files/1212506/gem_list_20170809_prod.txt)

**Comment by jywarren** [comment]
In meetings today but will try... Gemfile.lock should deal with this
though, no?

**Comment by icarito** [comment]
I don't know what the specific issue with Gem is.

Still, aparently compiling assets is a heavy process, it would be better
to "precompile" them off production.

**Comment by jywarren** [comment]
I think it's possible to do that but I'm not sure how to get the unique
hash to match.

**Comment by icarito** [comment]
@jywarren okay before I built a whole new edifice to fix this one, I was able to compile assets by reverting to a prior Gemfile / Gemfile.lock:
```
git checkout 7c28ec491965b34fa1348dae1098976db58ceb5c Gemfile
git checkout 7c28ec491965b34fa1348dae1098976db58ceb5c Gemfile.lock
```
Now the server is capable of compiling assets and restarting nginx, and I am much more tranquil. :-)

**Comment by jywarren** [comment]
Hmm what was the gemfile.lock change that caused this? Do we need to check
in a new one?

**Comment by icarito** [comment]
Last night, when I was trying this out, I started going back in history
for both Gemfile and Gemfile.lock.

Turns out that Gemfile was just the same and Gemfile.lock has only

```

-
-BUNDLED WITH
-   1.14.6
```

removed (could that make a difference?).

Otherwise, your changes working changes to `test/` was reverted and I
was able to precompile assets.
