### ISSUE TITLE
"Publish" button inactive on Rich Editor until the markdown button was clicked

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1587]
### What happened just before the problem occurred

I was posting a research note, and had added a title, a lead image, body text, and a tag, when i discovered that the "Publish" button was inactive. 

I looked over the note, and tried re-doing a couple little things, and noticed that when i clicked the "rich" button back to its state of "markdown" the Publish button reactivated. 

However, i just tried to re-create this sequence, and clicking that button was NOT the determining factor in getting that Publish button to be active. So this is still a bit of an open question. 

My question is how many requirements are there for that Publish button to become active?

### Relevant URLs

https://publiclab.org/post

### PublicLab.org username

liz

### Browser, version, and operating system

Chrome on OSX

**Comment by jywarren** [comment]
Hi, liz - I believe this is an incidence of https://github.com/publiclab/PublicLab.Editor/issues/101, which also shows we need more testing. Can you copy this very helpful info over there and close this? Thank you!

**Comment by jywarren** [comment]
Addressing this (or attempting) in #1612 and https://github.com/publiclab/PublicLab.Editor/issues/101
