### ISSUE TITLE
Notifications for comments on wiki pages - do they go to the right people?

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1589]
Looking at @aspriya's new interface for making comments on wiki pages, it's not clear who comments notify. I guess they should notify all authors for that page, and all commenters, no?

https://publiclab.org/wiki/new-concepts-for-oshw-in-indoor-gardening/comments

![screen shot 2017-08-25 at 11 22 14 am](https://user-images.githubusercontent.com/24359/29720345-b0dea6a2-8987-11e7-9672-c54daa07abf9.png)

Let's **add an italic line above the form indicating who will receive it**:

`Comments will notify all authors of this page, and all commenters, by email.`

## Code

The controller code for that is here:

https://github.com/publiclab/plots2/blob/master/app/controllers/comment_controller.rb#L21

Then it uses `create_comment` here: https://github.com/publiclab/plots2/blob/master/app/helpers/comment_helper.rb

Then `comment.notify` here: https://github.com/publiclab/plots2/blob/master/app/models/comment.rb#L106

It looks like it only notifies the page's original author, and all commenters. 

## Solution

We need to modify this so that if there are any /additional authors/ -- that is, authors of revisions attached to this node -- they get notified too. The change should go inside the `  def notify(current_user)` block in comment.rb -- and be sure we're not notifying revision authors twice in the extra checks below. 

Finally, we should write some tests to ensure this all works. That probably means making sure we have fixture data for a wiki page with revisions by two different authors:

https://github.com/publiclab/plots2/blob/master/test/fixtures/node_revisions.yml

And could be modeled on some of the test in this file: https://github.com/publiclab/plots2/blob/master/test/unit/comment_mailer_test.rb

**Comment by maxtedford** [comment]
Do you still want help with this? If so, I'd be happy to take a stab.

**Comment by jywarren** [comment]
Yes please! We'd love your help and happy to offer tips or support.

**Comment by maxtedford** [comment]
Fantastic! I'll dive in here in the coming days and let you know if any questions crop up 👍

**Comment by jywarren** [comment]
many thanks!

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by maxtedford** [comment]
Hi @jywarren, so sorry this is dragging a bit. I've started on it, and I think I've got a clear grasp on the problem, but I've had a few things come up recently that have diverted my attention temporarily. I should be able to get you a PR by this weekend. Would that work?

**Comment by jywarren** [comment]
Absolutely, and thanks for writing back!

**Comment by maxtedford** [comment]
Hi @jywarren, I've wrapped up this feature branch, but I've got a quick question about the tests. When I run the full suite I have a ton errors due no connection to the solr engine (this has been the case the whole time, but I'm just bringing it up now to make sure I'm not PR'ing a failing branch). The setup guides in the README seem to indicate that setting up solr is an optional step and is not recommended, so I'm a bit confused. Should I need to set that up to have my suite run? Thanks so much! Once I get that resolved I'll be ready to PR this.

**Comment by jywarren** [comment]
Ah, no - solr tests and solr itself is actually not recommended for most
contributors! You can run tests without it with just "rake test" -- and in
fact submitting a pull request will run tests automatically on our testing
server so we'd love to see it even if you're not quite done. Early PRs are
really helpful!

Thanks! Exciting!

**Comment by maxtedford** [comment]
Sounds good, I'll go ahead and push my changes regardless and will let the CI tests do their thing. I've actually been trying to run the suite locally with `rake test`, but for some reason it seems the test environment is trying connect to a solr server and I'm getting a ton of these errors in succession:

<img width="1679" alt="screenshot 2017-10-02 14 42 47" src="https://user-images.githubusercontent.com/9435299/31093658-6860cb28-a780-11e7-9d6d-39b4cd0efbcc.png">

In total it's something like a third of the tests that end up returning those errors. I suspect I may have created some failures here and there just by virtue of poking at the fixtures, and that they may be hiding behind the solr errors, but until I can figure out a way around them it might be tough for me to really get a sense for what I may have corrupted.

I'd love to hear if you have any ideas or if any of the above errors look familiar to you. Thanks so much!

**Comment by jywarren** [comment]
hmm, @icarito is managing some server load issues right now but i wonder if
we need to turn "disabled: true" in /config/sunspot.yml -- thanks for
posting this though!!!

**Comment by maxtedford** [comment]
Anytime! Would you like me to notify the Google group about my PR, or is simply submitting it adequate?

**Comment by maxtedford** [comment]
Also, switching to `disabled: true` in the `sunspot.yml` seems to have done the trick!

**Comment by jywarren** [comment]
Oh cool. I saw the PR and will take a look later today! Thanks!

On Oct 2, 2017 3:22 PM, "Max Tedford" <notifications@github.com> wrote:

Also, switching to disabled: true in the sunspot.yml seems to have done the
trick!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/1589#issuecomment-333637616>,
or mute the thread
