### ISSUE TITLE
multilingual features in posting form, multilingual features

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#159]
this ticket was originally filed in the old repo:
https://github.com/jywarren/plots2/issues/200

summary:
Need to add support for i18n in notes, wikis, and on the menu.

I'm fairly sure we already have i18n for research note content and wiki content, but there is no interface.

As an addendum, we have this concept of using subdomains for language filtering: en.publiclab.org, jp.publiclab.org, etc. @jywarren said this has been started but does not functionally do anything?

**Comment by jywarren** [comment]
I believe this is largely complete now via @jiteshjha's work; I'm going to close it here, although there are ongoing issues related to adding additional languages, coordinating translation, and completing translation integration. Thanks!!!
