### ISSUE TITLE
Prompt for Powertag Input

### ISSUE THREAD

**Issue by shelbyfirebaugh** [publiclab/plots2#1591]
In reference to project 2 described in #1560 

### What We Did

This project was to implement a popup via the javascript prompt() function to request user input for certain powertags. 

To test the functionality we used the `style:fancy` powertag (even though it usually does not require user input) and asked the user to supply the type of style desired (in this case fancy is the only option).

<img width="1220" alt="screen shot 2017-08-26 at 14 39 18" src="https://user-images.githubusercontent.com/14167695/29744201-26378f0e-8a6e-11e7-8ef5-7ee53a6b66d7.png">

After supplying input, the user hits enter or clicks "OK" and the powertag is added.

<img width="1188" alt="screen shot 2017-08-26 at 14 53 25" src="https://user-images.githubusercontent.com/14167695/29744210-5b2639b8-8a6e-11e7-9023-fc05a0631007.png">

We also moved the position of the dropdown to be on the right side of the tag input, and added a link to the powertag documentation at the bottom of the dropdown.

### Issues

Originally we wanted to use the `with:username` powertag as an example of a powertag which would require user input, but we got some errors when attempting to add a username.

<img width="877" alt="screen shot 2017-08-26 at 14 13 30" src="https://user-images.githubusercontent.com/14167695/29744258-4376914a-8a6f-11e7-9a7a-d5fcfdd9fa41.png">

We aren't sure if the errors are because we aren't actually running the database locally, or if we are doing something wrong code-wise.

### PublicLab.org username

shelbyfire and lilliankorinek

### Browser, version, and operating system

Google Chrome, OS X Yosemite

**Comment by shelbyfirebaugh** [comment]
@jywarren here's where we are so far, let us know if we should add/change anything before we push our code

**Comment by jywarren** [comment]
Hmm, on your "downcase" error -- look at the request parameters in the error; it looks like for some reason it wasn't actually submitting a username? It just says `with:` -- is that a clue?

**Comment by jywarren** [comment]
And my apologies for replying slowly!

**Comment by shelbyfirebaugh** [comment]
hey @jywarren ! here's some updates. i changed the wording on the style popup:

<img width="1217" alt="screen shot 2017-08-31 at 13 54 46" src="https://user-images.githubusercontent.com/14167695/29937636-349bbb8a-8e54-11e7-8942-cf41e95c35c7.png">

i believe that the `with:username` tag works now. it says that the username doesn't exist, but it's not a big error so i think it really is just because i can't check the database this time:

<img width="1155" alt="screen shot 2017-08-31 at 13 55 14" src="https://user-images.githubusercontent.com/14167695/29937686-6810d306-8e54-11e7-98a5-8c745b900260.png">
<img width="1201" alt="screen shot 2017-08-31 at 13 55 24" src="https://user-images.githubusercontent.com/14167695/29937692-6f9c03fc-8e54-11e7-885c-2321de2f39b0.png">

also at some point @lilliankorinek and i would like to talk to you about how the powertags should be organized within the dropdown so that we can add the rest of the tags in and push the code

let me know what you think and if there's anything else you want changed!

**Comment by jywarren** [comment]
This looks fantastic. Do you think it's ready to merge in? We can tackle
organization as a next step.

Couple small things:

can you put a space between "Power Tags" and the caret?

I wonder if just calling that menu "Extras" might be even better? Or one of
the icons from Font Awesome (always fun to pick one: http://fontawesome.io/)

**Comment by jywarren** [comment]
Things going well here? Thanks, and happy to help!

**Comment by jywarren** [comment]
Solved in #1605 -- :-)

**Comment by jywarren** [comment]
We'll try to roll this out in the next 2-3 days. Keep an eye out!

**Comment by jywarren** [comment]
actually @icarito if you're not super busy, could you roll this and other changes out? Do you know the sequence to merge to stable manually?

**Comment by icarito** [comment]
Hi Jeff, sorry for the delay. I've been dealing with [slowness in our staging server](https://github.com/publiclab/plots2/issues/1604) but am ready to deploy now. Just looking for the PR and exact commit I should deploy.

**Comment by jywarren** [comment]
It's live, thanks!
