### ISSUE TITLE
Edit history missing on wiki revisions page

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#1594]
### What happened just before the problem occurred
I was working on editing the Barnraising page and wanted to grab text from an edit we had on the page in 2016, but it looks like all the revision history from 2016 is missing. 

### Relevant URLs
www.publiclab.org/barnraising
https://publiclab.org/wiki/revisions/barnraising

### PublicLab.org username
Stevie

**Comment by jywarren** [comment]
Compare this to a "working" wiki page like:

https://publiclab.org/wiki/revisions/opencall

to see what it's supposed to look like! I suspect there's some content on the page which is making it difficult for the revisions template to display, but this bears some looking into... there are just a LOT of revisions. Is this urgent, @steviepubliclab?

**Comment by steviepubliclab** [comment]
I don't think it's urgent (unless it does something to our licensing to not
have people's edits/additions?) . I couldn't get that link you sent to open
though.
-Stevie

**Comment by jywarren** [comment]
Solved in #2707 I believe! We'll double check and i also think the "navigating through revisions" may be slightly broken by this fix but we'll see.
