### ISSUE TITLE
Map details categories visible when empty

### ISSUE THREAD

**Issue by gonzoearth** [publiclab/plots2#16]
This may be more of a personal preference. The ancillary info for each map page should only show up when those fields are used. Categories such as "cartographer's notes" are showing up when empty. I think it would look better/cleaner if those categories are only visible when they contain entries.

**Comment by ananyo2012** [comment]
@jywarren Can this be closed now?

**Comment by jywarren** [comment]
Can you confirm that it's no longer occurring?

**Comment by ananyo2012** [comment]
@jywarren Should I remove the Delete and Raw links in the popover toolbar in the maps show page? as there are already Edit and raw links outside the toolbar.

**Comment by jywarren** [comment]
I think it's fine without. At some point we may launch a larger project
around these pages and can address such issues then. I guess we can close?

**Comment by ananyo2012** [comment]
@jywarren Ok then this can be closed now with the merge.

**Comment by jywarren** [comment]
I'll just close it now, since it's pretty old anyhow. Someone can re-open if it causes more trouble! Thanks!
