### ISSUE TITLE
Request for help updating the dropdown menus on publiclab.org

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1600]
There are a few changes to make on the dropdown menus of publiclab.org. I think i could make these myself if someone could show me which files i need. Your assistance requested @publiclab/soc ! 

First change: 
- from the Project menu: remove initiative areas Open Air, Open Land, Open Water

<img width="159" alt="screen shot 2017-09-04 at 3 41 48 pm" src="https://user-images.githubusercontent.com/161439/30037301-9830bc28-9187-11e7-9a36-1034f9e876cc.png">

**Comment by jywarren** [comment]
Cool, Liz! also ask on plots-dev!

Specifically, you're asking for which files and line numbers actually set
the content of these menus, right?

**Comment by ebarry** [comment]
yes, exactly! Thank you.

**Comment by jywarren** [comment]
Starting to address this in #1620, and so:

Merging into #1621
