### ISSUE TITLE
Task: Add email solution to container

### ISSUE THREAD

**Issue by icarito** [publiclab/plots2#1606]
It dawned on me that we'll need plots2 to send email and our current Dockerfile doesn't provide a solution for this. In order to deploy we'll need to make sure we can send emails from the container reliably.

**Comment by jywarren** [comment]
ahhhhh yeah

**Comment by icarito** [comment]
Actually, we can reuse the host Exim configuration which is already listening locally:
```
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      24310/exim4
```
So the question is how do we tell the ruby app to use SMTP localhost port ? Doing my research...

**Comment by icarito** [comment]
From looking at headers from a recent message from plots I see:
```
X-Received: by 10.200.53.67 with SMTP id z3mr3866012qtb.145.1504872629556;
        Fri, 08 Sep 2017 05:10:29 -0700 (PDT)
Return-Path: <do-not-reply@publiclab.org>
Received: from rs-plots2 ([162.209.105.67])
        by smtp-relay.gmail.com with ESMTPS id a125sm277788qkg.3.2017.09.08.05.10.29
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 08 Sep 2017 05:10:29 -0700 (PDT)
X-Relaying-Domain: publiclab.org
Received: from localhost ([127.0.0.1] helo=localhost.localdomain)
	by rs-plots2 with esmtp (Exim 4.84_2)
	(envelope-from <do-not-reply@publiclab.org>)
	id 1dqI8p-00009e-41; Fri, 08 Sep 2017 12:12:11 +0000
```
Suggesting we already use SMTP. So it will be a question of giving access to `localhost:25` to the docker container. Reading up....

**Comment by icarito** [comment]
It will come down to convince rails to use docker host (IP 172.17.0.1) instead of `localhost` that we use currently. Also possibly setup Exim to listen on `docker0` network interface.
