### ISSUE TITLE
Trouble with question "Ask" button

### ISSUE THREAD

**Issue by GraySkull** [publiclab/plots2#1612]

**Comment by jywarren** [comment]
Thanks on both suggestions -- and saw you just closed it -- did it start
working? I have seen the "disabled" issue and we are trying to resolve that
- hopefully today. Thanks and please re-open if you still see the issue!

**Comment by GraySkull** [comment]
Well, actually I didnt close it. I could get it to work, randomly it seemed, by opening and closing until it finally let me submit. Sorry, but I couldn't find a pattern. 

I thought it was related to tags, since leaving them off seem to work the first time (thanks for adding them to the temp sensor question) . 

Dave

Mobile...

**Comment by jywarren** [comment]
I'm going to re-open the issue and connect to the almost identical one over in https://github.com/publiclab/PublicLab.Editor/issues/101 -- thank you for reporting!

**Comment by jywarren** [comment]
Attempted fix in publiclab/PublicLab.Editor#104 -- fingers crossed, and we'll hopefully ask folks to give this a try when it publishes.

**Comment by jywarren** [comment]
This attempted fix is now live on publiclab.org, both for the question form at publiclab.org/questions/new and for publiclab.org/post. Can folks give it a try and see if the problem is still there? 

Thanks all - @Fastie @steviepubliclab @ebarry as well for previously reporting variations of this bug.

**Comment by jywarren** [comment]
I'm still seeing hte issue but will empty my browser cache to double check.

**Comment by jywarren** [comment]
I believe I've found the issue; testing one more time before rolling out a new fix.

**Comment by jywarren** [comment]
@GraySkull @Fastie @steviepubliclab @ebarry I believe this is now fixed. Closing - and please give it a try and report back please!

Thanks all!
