### ISSUE TITLE
3-column "trifold booklet" layout option for printing notes + wiki pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1622]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

We'd love to make wiki pages more printable and formatted nicely to print compactly on fewer pages. Images can take up a lot of space when they print full-width.

## Solution

There's a neat way to reformat notes and wiki pages for printing as 2-sided trifold brochues; you really only have to run this JS, and it'll print! These styles would persist until page reload. 

```js
$('body').css('column-count', 3).css('column-gap', '50px'); window.print();
```

We should make a button for this, at the bottom of this popup menu:

![screen shot 2017-09-18 at 3 33 57 pm](https://user-images.githubusercontent.com/24359/30560761-df7877ba-9c86-11e7-8a5a-5f90719bffa1.png)

Code for that menu is here: 

https://github.com/publiclab/plots2/blob/master/app/views/like/_like.html.erb#L62

We can just add a new line below that one, with the following code:

```html
<a onClick='$('body').css('column-count', 3).css('column-gap', '50px'); window.print();'><i class='fa fa-print'></i> Print in 3-column layout</a>
```

I tried printing this as a test, and it looks great!

![img_20170605_222936_167](https://user-images.githubusercontent.com/24359/30558809-af9d386a-9c80-11e7-8bed-9e9a29809124.jpg)

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by priyansh1161** [comment]
Hey, I'd like to work on this.

**Comment by jywarren** [comment]
That'd be great! Please tell us if you have any questions! Thanks!

**Comment by jywarren** [comment]
Completed in  https://github.com/publiclab/plots2/pull/1636 thanks!!
