### ISSUE TITLE
Add checkmark icon instead of (Answered) to questions display in pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1624]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

Questions grids, generated by the inline shortcode `[questions:TAGNAME]` ([documented here](https://publiclab.org/wiki/power-tags)) now show questions that have been answered with a nice prefix, `(Answered)` -- which is helpful to tell which have been answered! But it takes up a lot of space:

https://publiclab.org/wiki/harvey#Questions

![screenshot 2017-09-19 at 12 13 57 pm](https://user-images.githubusercontent.com/24359/30603023-5073d18c-9d34-11e7-8f4b-563644ded927.png)

### Solution

This display is set on these lines of code in the grids templates: https://github.com/jywarren/plots2/blob/double-inline-shortcodes/app/views/grids/_notes.html.erb#L37

What we should do is change this:

```html
      <td class="title"><% if node.answered %><b>(Answered)</b> <% end %><a href="<%= node.path %>"><%= node.title %></a></td>
```
so that instead of `<b>(Answered)</b>` it says `<i class="fa fa-"></i> ` (note the trailing space!) 

### Extra credit!

I found the checkbox icon (http://fontawesome.io/icon/check-square/) from http://fontawesome.io/icons/, which accounts for the `fa fa-___` classes. We have FontAwesome installed, so that makes this easier!

There are other checkbox icons there, so if you're opinionated about it, you could try another. Or turn it green with `<i style="color:#0c8;" ...`.

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by haleymnatz** [comment]
Hey @jywarren, can I take this issue?

**Comment by jywarren** [comment]
Yes please! And we'd be happy to help if you need anything.

**Comment by haleymnatz** [comment]
So I've been trying to run the test suite before making the change, but the suite takes almost an hour and has failed (I stepped away and my computer fell asleep). I didn't add solr as this is said to be optional and not recommended, but I see there are a lot of errors (not failures) in the tests with solr. Does this sound correct or did I do something wrong in the installation?

**Comment by jywarren** [comment]
Hmm, try opening a pull request and we can take a look at your code
changes! Thisll also run tests for you on the testing server which could be
faster. Thanks!
