### ISSUE TITLE
Posting a comment on event showed an error

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1627]
### What happened just before the problem occurred

I posted a comment but saw an error message, and it didn't save. My message was:

`Also wanted to point out the growing set of resources on hosting events of different kinds at https://publiclab.org/wiki/host-an-event !!`

The server shows this error:

```
NoMethodError (undefined method `next_thread' for nil:NilClass):
  app/models/node.rb:514:in `add_comment'
  app/helpers/comment_helper.rb:6:in `create_comment'
  app/controllers/comment_controller.rb:21:in `create'
```

https://github.com/publiclab/plots2/blob/master/app/controllers/comment_controller.rb#L21

https://github.com/publiclab/plots2/blob/master/app/helpers/comment_helper.rb#L6

https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L514

### Relevant URLs

https://publiclab.org/notes/liz/03-15-2017/host-a-balloon-mapping-workshop

**Comment by jywarren** [comment]
Also affected this page! https://publiclab.org/notes/mathew/5-29-2012/solar-hot-air-balloons#c17374

**Comment by jywarren** [comment]
A quick fix would be to just check if `comments.last.nil?` on one of these lines in `node.rb`:

```ruby
  def add_comment(params = {})
    thread = if !comments.empty?
               comments.last.next_thread
             else
               '01/'
             end
```

**Comment by jywarren** [comment]
Attempting a fix in https://github.com/publiclab/plots2/pull/1632

**Comment by jywarren** [comment]
Interesting to note - the comments seem to actually post, just the UI reports an error.

**Comment by jywarren** [comment]
#1632 did not resolve it, :-(

**Comment by jywarren** [comment]
Huh, different error now!

```
Started GET "/comment/create/2245?body=Hi%2C+%40suman+-+this+is+a+great+question+and+I%27ve+had+some+not+great+experience+using+coarse+charcoal+briquettes+(the+balloon+di
d+not+fly+very+strongly).+But+maybe+vine+charcoal+or+art+charcoal+would+be+better.+%0D%0A%0D%0AIf+you%27d+like+to+post+this+question+to+the+whole+community%2C+try+https%3
A%2F%2Fpubliclab.org%2Fquestions&_=1505926315314" for 184.179.58.42 at 2017-09-20 16:54:56 +0000
Processing by CommentController#create as JS
  Parameters: {"body"=>"Hi, @suman - this is a great question and I've had some not great experience using coarse charcoal briquettes (the balloon did not fly very strong
ly). But maybe vine charcoal or art charcoal would be better. \r\n\r\nIf you'd like to post this question to the whole community, try https://publiclab.org/questions", "_
"=>"1505926315314", "id"=>"2245"}
  Rendered comment_mailer/notify_note_author.html.erb (11.1ms)

Sent mail to xxxxx@gmail.com (149.1ms)
  Rendered comment_mailer/notify_callout.html.erb (10.1ms)

Sent mail to xxxxx@gmail.com (53.6ms)
  Rendered comment_mailer/notify.html.erb (27.0ms)

Sent mail to  (5.3ms)
Completed 500 Internal Server Error in 544.7ms

ArgumentError (An SMTP To address is required to send a message. Set the message smtp_envelope_to, to, cc, or bcc address.):
  app/models/comment.rb:99:in `block in notify_users'
  app/models/comment.rb:97:in `each'
  app/models/comment.rb:97:in `notify_users'
  app/models/comment.rb:120:in `notify'
  app/helpers/comment_helper.rb:8:in `create_comment'
  app/controllers/comment_controller.rb:21:in `create'
```

**Comment by Gauravano** [comment]
@jywarren is this issue resolved? According to me, above error is due to invalid email id  or due to id with different settings

**Comment by jywarren** [comment]
Hi, I wonder if it was related at all to https://github.com/publiclab/plots2/pull/1771 -- i'd like to try to reproduce this with a test, perhaps? We could deliberately introduce a bad email into a user account and try sending a notification to it...
