### ISSUE TITLE
Not able to post research note in Rich editor mode, must switch to Legacy editor to publish

### ISSUE THREAD

**Issue by gretchengehrke** [publiclab/plots2#1629]
### What happened just before the problem occurred
I have been able to write research notes and get them ready for publication (including adding tags, etc), but when I click on the "Publish" button, nothing happens. I do not receive an error code, and it also does not progress to posting my research note. Instead, nothing happens. If I copy my text and paste it into a new form in the legacy editor mode, add the appropriate tags etc, and click "Publish," then it proceeds as expected to publishing my note. 

### Relevant URLs

https://publiclab.org/post

### PublicLab.org username

@gretchengehrke 

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hi, Gretchen - can you go through these steps right now and take a screenshot of the moment when nothing happens? This will help us narrow things down. Thank you!

**Comment by gretchengehrke** [comment]
Hi Jeff,
It worked with a test post. It's not worked the past several times I tried
it, but maybe that means the bug has already been fixed.
Thanks,
Gretchen

**Comment by jywarren** [comment]
Super, very good to hear. Closing this then; pls reopen if it happens again; it could be a nasty bug that only happens sometimes.

**Comment by jywarren** [comment]
and thanks!
