### ISSUE TITLE
Unexpected email is sent when someone adds a tag to content on publiclab.org

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1630]
hi! :D :keyboard: 

### What happened just before the problem occurred

Gretchen and I just compared notes and realized we are both getting emails every time anyone (?) adds a tag on any (?) content on publiclab.org

Here's a screenshot of one of the emails i get on this: 
<img width="674" alt="screen shot 2017-09-19 at 4 54 31 pm" src="https://user-images.githubusercontent.com/161439/30614974-45b47338-9d5b-11e7-8122-e3db49a56dc9.png">

Because the email links to the /subscriptions page, here are my subscriptions: 
<img width="889" alt="screen shot 2017-09-19 at 4 51 35 pm" src="https://user-images.githubusercontent.com/161439/30614849-e184f04a-9d5a-11e7-97a6-b7c2fac3dbd4.png">

Here are Gretchen's subscriptions: 
<img width="1167" alt="screen shot 2017-09-19 at 4 50 47 pm" src="https://user-images.githubusercontent.com/161439/30614989-55648778-9d5b-11e7-9b1b-6c564e226e70.png">

### Relevant URLs

https://publiclab.org/subscriptions

### PublicLab.org username

liz

**Comment by jywarren** [comment]
Hi, thanks for filing this! But according to your screenshots, you're both following the tag `question:question` -- Gretchen directly and you via the `everything` tag. So it seems you should actually be getting these notifications, based on that information, no?

**Comment by ebarry** [comment]
I'm wondering about this, because i do want notifications for every piece of new content, as in a post or comment. At some point a few weeks ago, Gretchen and I both started to get notifications every time someone added a _tag_ on content that already existed from before (and that we already got notifications about).

**Comment by jywarren** [comment]
StellaMaris worked on this feature and it's possible that for a few days it was sending twice to the same person, but I believe it's working properly now. Can you carefully document a case where it's not -- i.e. that **someone who is not subscribed to "everything" gets a tag notification for a note they've already been notified of**?

Thanks, that would be very helpful to clarify if there is indeed a bug!

**Comment by ebarry** [comment]
Hi Jeff, thanks for helping with this little issue! 

Perhaps i am not familiar with the feature as it is intended to work. 

For people subscribed to everything, or even to all questions, we never need a notification when a tag is added to content, because we already know about that content courtesy of already being subscribed to "everything" and "all questions".  Can tag notifications be turned off for people with these universal subscription settings?

**Comment by jywarren** [comment]
Yes, we can do that -- can you open a new issue with the title "add an
exception to list of users to be notified upon new tag addition, for those
subscribed to 'everything'" and i can help find that line of code and
propose a change. Thanks!

**Comment by sagarpreet-chadha** [comment]
Hey @jywarren sir...can i work on this ? should i open a new issue for this ?

**Comment by jywarren** [comment]
Yes please! That would be great. Thanks!

**Comment by jywarren** [comment]
Solved in #1692, as far as we can tell! Please report back if that seems not to work, and thanks all!

**Comment by ebarry** [comment]
Thank you!!!!!!!!!!!! @gretchengehrke , check it out -- our issue with receiving extra emails each time someone adds a new tag (considering that we were already getting all notifications anyways) has been solved! Please report back if that seems not to work! thanks everyone.
