### ISSUE TITLE
Display "Is this a question? Click here to post it to our new Questions page" below comments if they include a question mark (?)

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1631]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

Often, comments pose a good question, and we might smooth the transition between if we prompted people to post their comment as a question.

## Solution

We could check if `comment.body.include?('?')` (i think that's correct Ruby...) and if so, display a message like:

`Is this a question? Click here to post it to our new Questions page`

Where `Questions page` links to publiclab.org/questions, and `Click here` links to the questions form:

```html
<a href="/questions?title=<%= comment.body %>>Click here</a> to post it to the <a href="/questions">Questions page</a>.
```

The template for individual comment display is here:

https://github.com/publiclab/plots2/blob/master/app/views/notes/_comment.html.erb#L67

We should add the notice below line 67, perhaps in an alert box so it appears in a blue box.

The conditional around the message could be:

```ruby
<% if comment.body.include?('?') %>
  <p class="alert alert-info">Message here...</p>
<% end %>
```

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by fuentesj** [comment]
Hi Jeff, I'd like to take on this issue if it's still available. I've followed the instructions to get a local copy of the repo on my laptop, and I'm hoping to work on this issue during the following week. 

I do have one question at the moment though: Would `comment_controller_test.rb` be the appropriate place to add a test for this issue?

Thank you!

**Comment by jywarren** [comment]
Hi, thanks! On this, I think you could, in the functional tests, by
modifying the text of a comment and then scanning the resulting page with
`assert_select` to see if you see your prompt text. Great idea!

On Fri, Sep 22, 2017 at 10:45 AM, Jonathan Fuentes <notifications@github.com
