### ISSUE TITLE
Add "coauthorship" credit line to list view of recent activity

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1634]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### What happened just before the problem occurred

Some notes are marked as having multiple coauthors, like this one:

https://publiclab.org/notes/liz/06-21-2017/re-posting-2016-dustduino-report

See how it says `by liz with willie` below the title:

![screenshot 2017-09-20 at 11 58 16 am](https://user-images.githubusercontent.com/24359/30654210-40b0b126-9dfb-11e7-8b60-7909eb83239d.png)

But in the list view, at https://publiclab.org/research or https://publiclab.org/questions, the coauthor line is not shown.

https://

### PublicLab.org username

(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

## Solution

We can use the code for the main notes page and copy it into the template for the list view.

Find the coauthorship credit line here: 

https://github.com/publiclab/plots2/blob/master/app/views/notes/show.html.erb#L32-L35

And integrate that into the credit line for the list view, here:

https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_node_meta.html.erb#L2

Should be pretty straightforward! Do note that the original uses `@node` while the list view template uses simply `node` -- and adjust the copied code accordingly.

Thanks and good luck!

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by Arimao** [comment]
I have tried to fix this issue, but I might have failed since I don't have any prior Ruby experience. Here it is.

https://github.com/Arimao/plots2/blob/1634/app/views/dashboard/_node_meta.html.erb

**Comment by jywarren** [comment]
Ah, looks like the wrong URL but your pull request is here: https://github.com/publiclab/plots2/pull/1638#issuecomment-331726123

Thanks, we're very happy to help! I should be able to take a look over this soon, and if @publiclab/reviewers can get to it first that's great too.

**Comment by amitsin6h** [comment]
@jywarren can I work on this issue for my first time fix

**Comment by makeupsomething** [comment]
@jywarren @amitsin6h 
I will take this if still available
