### ISSUE TITLE
questions not showing up

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#1637]
I went to the questions page and it looks the material (questions) on that page aren't showing up right now under any of the tabs: https://publiclab.org/questions/

**Comment by jywarren** [comment]
Hi, Stevie - can you try this using an incognito tab, and on a different
browser (either your phone or, say, Firefox)? You're on Chrome now, right?

This looks like the issue @ebarry has been tracking down. Mysterious but
we'll get it.

**Comment by jywarren** [comment]
Merging into #1532. Thanks!
