### ISSUE TITLE
make search function return tagged posts

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/plots2#164]
I just did a search for silica, and results that show up in /tag/silica don't show up in /search/silica
![screen shot 2014-10-06 at 8 04 15 am](https://cloud.githubusercontent.com/assets/1203280/4528100/75e0f9a6-4d6c-11e4-9150-0aa753f0d26f.png)

this note is the most recent one, and it doesn't show up despite its tag.
![screen shot 2014-10-06 at 8 04 08 am](https://cloud.githubusercontent.com/assets/1203280/4528102/783273ce-4d6c-11e4-9d5b-27d8f063867f.png)

**Comment by jywarren** [comment]
This'll work in the new dynamic search page, which we're in final refinements of now in #987, thanks!
