### ISSUE TITLE
Add right to edit a co-authored note if username is tagged using "with:USERNAME"

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1640]
### What happened just before the problem occurred
I'm posting this on behalf of Mimibell who is co-author on a note, and wished to edit it, but the system did not give the account access, although the friendly green announcement said that it did:
![unnamed](https://user-images.githubusercontent.com/161439/30817357-a58915ea-a1e6-11e7-8f43-4603bed2031e.png)
 
### Relevant URLs

Research Note: https://publiclab.org/notes/stevie/09-20-2017/notes-and-reflections-from-hurricane-preparedness-discussion-dinner

### PublicLab.org username

Individual account: https://publiclab.org/profile/mimibell

**Comment by jywarren** [comment]
Thanks, @ebarry ! This is great; it's part of this issue which needed to be broken up into individual issues, so I'll link it: https://github.com/publiclab/plots2/issues/761

I'll also copy in the notes for how to solve this, and if you'd like help reformatting this issue I think we could get it in the queue pretty easily:


### Steps to fix

give co-authors (as denoted by `with:<username>`, [see code here](https://github.com/publiclab/plots2/blob/master/app/views/notes/show.html.erb#L35-L38)) right to edit (as in now-closed #606), meaning a `node.has_power_tag('with')`-based check on `edit` and `update` actions on `app/controllers/notes_controller.rb`

The check happens in `edit` on this line: https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb#L152

And in the `update` action  on this line: https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb#L178

In each case, we can change:

```ruby
    if current_user.uid == @node.uid || current_user.role == 'admin'
````

into:

```ruby
    if current_user.uid == @node.uid || current_user.role == 'admin' || @node.has_tag("with:%{current_user.username}")
```

That way we allow coauthors to edit the page as well.

**Comment by ViditChitkara** [comment]
Can I work on it??I am a first timer??

**Comment by Diksha2008** [comment]
@jywarren Can I work on this issue ?

**Comment by jywarren** [comment]
Sure, either of you is welcome to do so -- please open a pull request with your changes even before you're done so that you don't overlap work. And I'm happy to help out!
