### ISSUE TITLE
Performance issue optimize query

### ISSUE THREAD

**Issue by icarito** [publiclab/plots2#1641]
On 25/09/17 11:38, Jeffrey Warren wrote:
> Hi! I believe this has to do with this query:
>
> https://github.com/publiclab/plots2/blob/master/app/controllers/admin_controller.rb#L51
>
> And could be solved by refactoring and removing status != 1 users. 

So two actions required (or one of either?):
  - [ ] refactoring (adding index to model?)
  - [x] remove users with status not 1 (confirm?)

**Comment by icarito** [comment]
> removing status != 1 users

You mean doing something like DROP FROM rusers WHERE status!=1 ?
Or would a migration be preferable?

**Comment by jywarren** [comment]
nono, i just mean adding a filter like `.where(status: [1,4])` -- though this would limit the search (used by admins) to verified accounts. But that should be OK. 

### Steps to resolve:

```ruby
        @users = User.where(email: params[:address])
                 .where(status: [1,4])
```

**Comment by jywarren** [comment]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by icarito** [comment]
Here's the top queries for Monday

QUERY TIME - BY MEAN | HITS | SUM | MEAN | STDDEV | MIN | MAX | 95 %TILE
-- | -- | -- | -- | -- | -- | -- | --
publiclab@172.18.0.1: SELECT term_data.* FROM term_data INNER JOIN community_tags ON community_tags.tid = term_data.tid INNER JOIN community_tags node_tags_term_data_join ON node_tags_term_data_join.tid = term_data.tid INNER JOIN node ON node.nid = node_tags_term_data_join.nid WHERE (node.status = :int) GROUP BY name ORDER BY count DESC LIMIT :int OFFSET :int | 26 | 14m46s | 34.07s | 7.69s | 25.83s | 1m01s | 25.76s-1m02s
publiclab@172.18.0.1: SELECT :int AS one FROM rusers WHERE rusers.persistence_token = BINARY :string LIMIT :int | 1 | 22.32s | 22.32s | 0ms | 22.32s | 22.32s | 22.28s-23.01s
publiclab@172.18.0.1: SELECT COUNT(*) FROM rusers WHERE rusers.email = :string | 3 | 34.26s | 11.42s | 3.56s | 8.91s | 15.50s | 8.89s-15.63s
publiclab@172.18.0.1: SELECT DISTINCT node.nid FROM node LEFT OUTER JOIN node_revisions ON node_revisions.nid = node.nid WHERE (node_revisions.status = :int AND node.status = :int AND (type = :string OR type = :string OR type = :string)) GROUP BY node_revisions.nid ORDER BY node_revisions.timestamp DESC LIMIT :int OFFSET :int | 1 | 11.11s | 11.11s | 0ms | 11.11s | 11.11s | 10.96s-11.32s
publiclab@172.18.0.1: SELECT :int AS one FROM rusers WHERE rusers.email = :string LIMIT :int | 6 | 1m06s | 11.02s | 4.76s | 5.54s | 19.71s | 5.48s-19.91s
publiclab@172.18.0.1: SELECT node_revisions.* FROM node_revisions INNER JOIN node ON node.nid = node_revisions.nid WHERE (type = (:string)) AND (node.status = :int) AND (node_revisions.status = :int) AND (timestamp - node.created > :int) GROUP BY node.title, DATE(FROM_UNIXTIME(timestamp)) ORDER BY timestamp DESC LIMIT :int | 5 | 39.21s | 7.84s | 1.66s | 5.11s | 9.59s | 5.06s-9.64s
publiclab@172.18.0.1: SELECT COUNT(*) AS count_all, name AS name FROM term_data INNER JOIN community_tags ON community_tags.tid = term_data.tid INNER JOIN community_tags node_tags_term_data_join ON node_tags_term_data_join.tid = term_data.tid INNER JOIN node ON node.nid = node_tags_term_data_join.nid WHERE (node.status = :int) GROUP BY name | 26 | 3m04s | 7.07s | 1.91s | 5.12s | 13.10s | 5.06s-13.30s

**Comment by icarito** [comment]
Here's a random process list (it varies a lot)
```
mysql> show processlist;
+----+-----------+------------------+----------------------+---------+------+--------------+------------------------------------------------------------------------------------------------------+
| Id | User      | Host             | db                   | Command | Time | State        | Info                                                                                                 |
+----+-----------+------------------+----------------------+---------+------+--------------+------------------------------------------------------------------------------------------------------+
|  8 | publiclab | 172.18.0.1:45981 | publiclab_production | Sleep   |    0 |              | NULL                                                                                                 |
|  9 | publiclab | 172.18.0.1:45983 | publiclab_production | Query   |    0 | Sending data | SELECT  `node`.* FROM `node`  WHERE `node`.`path` = '/wiki/question:civicscience' LIMIT 1            |
| 10 | publiclab | 172.18.0.1:45986 | publiclab_production | Query   |    1 | Sending data | SELECT `node`.* FROM `node`  WHERE `node`.`type` = 'note' AND `node`.`status` = 1                    |
| 11 | publiclab | 172.18.0.1:45988 | publiclab_production | Query   |    0 | Sending data | SELECT `node`.* FROM `node` INNER JOIN `community_tags` ON `community_tags`.`nid` = `node`.`nid` INN |
| 12 | publiclab | 172.18.0.1:45990 | publiclab_production | Query   |    1 | Sending data | SELECT  `node`.* FROM `node`  WHERE `node`.`path` = '/question:civicscience' LIMIT 1                 |
| 13 | publiclab | 172.18.0.1:45993 | publiclab_production | Sleep   |    0 |              | NULL                                                                                                 |
| 15 | root      | 127.0.0.1:35960  | NULL                 | Query   |    0 | init         | show processlist                                                                                     |
+----+-----------+------------------+----------------------+---------+------+--------------+------------------------------------------------------------------------------------------------------+
7 rows in set (0.00 sec)
```

**Comment by icarito** [comment]
Here's more info for Tuesday early morning, for 8 hours with repeated micro-outages:

REQUEST DURATION - BY MEAN | HITS | SUM | MEAN | STDDEV | MIN | MAX | 95 %TILE
-- | -- | -- | -- | -- | -- | -- | --
WikiController#comments.*/* | 45 | 3m12s | 4.26s | 16.83s | 33ms | 1m53s | 82ms-1m54s
WikiController#popular.*/* | 2 | 7.43s | 3.72s | 3.68s | 1.11s | 6.32s | 1.11s-6.34s
WikiController#liked.*/* | 1 | 3.46s | 3.46s | 0ms | 3.46s | 3.46s | 3.44s-3.55s
UserSessionsController#create.HTML | 2 | 6.44s | 3.22s | 3.82s | 518ms | 5.92s | 512ms-5.94s
MapController#show.HTML | 70 | 3m40s | 3.15s | 13.92s | 1ms | 1m57s | 17ms-5.94s
HomeController#dashboard.HTML | 53 | 2m46s | 3.13s | 5.99s | 1ms | 32.99s | 22ms-24.15s
HomeController#front.*/* | 6 | 17.51s | 2.92s | 1.90s | 1.18s | 6.34s | 1.17s-6.44s
TagController#index.*/* | 3 | 8.70s | 2.90s | 2.58s | 416ms | 5.57s | 415ms-5.57s
WikiController#index.HTML | 20 | 57.41s | 2.87s | 2.59s | 816ms | 11.53s | 805ms-11.69s
TagController#show.JSON | 39 | 1m50s | 2.82s | 6.00s | 181ms | 37.03s | 287ms-37.33s
WikiController#methods.*/* | 3 | 8.10s | 2.70s | 2.11s | 1.23s | 5.12s | 1.22s-5.14s
QuestionsController#unanswered.*/* | 1 | 2.49s | 2.49s | 0ms | 2.49s | 2.49s | 2.45s-2.53s
WikiController#revision.HTML | 486 | 18m43s | 2.31s | 2.38s | 1ms | 25.68s | 5ms-7.94s
UsersController#edit.HTML | 19 | 43.54s | 2.29s | 1.98s | 116ms | 6.78s | 116ms-6.87s
HomeController#dashboard.*/* | 24 | 54.35s | 2.26s | 1.77s | 0ms | 6.27s | 0ms-6.34s
UsersController#profile.*/* | 664 | 24m49s | 2.24s | 6.27s | 1ms | 1m56s | 16ms-9.48s
UsersController#create.HTML | 32 | 1m11s | 2.23s | 6.27s | 11ms | 35.83s | 11ms-36.14s
UsersController#profile.HTML | 1704 | 1h02m35s | 2.20s | 4.85s | 1ms | 1m44s | 17ms-9.95s
HomeController#front.HTML | 134 | 4m55s | 2.20s | 2.10s | 13ms | 15.02s | 39ms-8.07s
NotesController#show.*/* | 824 | 29m34s | 2.15s | 8.21s | 0ms | 1m59s | 19ms-8.75s

**Comment by icarito** [comment]
REQUEST DURATION - BY SUM | HITS | SUM | MEAN | STDDEV | MIN | MAX | 95 %TILE
-- | -- | -- | -- | -- | -- | -- | --
TagController#show.HTML | 7390 | 2h21m30s | 1.15s | 1.88s | 0ms | 54.86s | 18ms-5.48s
NotesController#show.HTML | 1856 | 1h04m48s | 2.10s | 3.07s | 0ms | 56.91s | 22ms-8.75s
UsersController#profile.HTML | 1704 | 1h02m35s | 2.20s | 4.85s | 1ms | 1m44s | 17ms-9.95s
StatsController#index.*/* | 1504 | 36m35s | 1.46s | 3.78s | 1ms | 1m58s | 174ms-6.04s
TagController#contributors.HTML | 2043 | 34m39s | 1.02s | 1.83s | 0ms | 29.23s | 32ms-5.48s
NotesController#author_topic.HTML | 1871 | 33m26s | 1.07s | 3.09s | 1ms | 1m56s | 7ms-5.57s
TagController#show.*/* | 1848 | 32m17s | 1.05s | 3.47s | 0ms | 1m54s | 114ms-6.55s
WikiController#show.HTML | 1747 | 31m43s | 1.09s | 7.33s | 0ms | 3m33s | 3ms-5.06s
NotesController#show.*/* | 824 | 29m34s | 2.15s | 8.21s | 0ms | 1m59s | 19ms-8.75s
#. | 1264 | 26m14s | 1.25s | 4.99s | 1ms | 2m04s | 5ms-6.24s

**Comment by jywarren** [comment]
Hmm, this line from top of Monday's list looks like a potential candidate:

```sql
SELECT term_data.* FROM term_data INNER JOIN community_tags ON community_tags.tid = term_data.tid INNER JOIN community_tags node_tags_term_data_join ON node_tags_term_data_join.tid = term_data.tid INNER JOIN node ON node.nid = node_tags_term_data_join.nid WHERE (node.status = :int) GROUP BY name ORDER BY count DESC LIMIT :int OFFSET :int
```
 at 34.07s average and 26 hits. That might jive with your just-posted list's top culprit, `TagController#show.HTML`, but that only shows 1s average. Still, it's something to do with tags, as per 
the query.

It looks like an attempt to get all the tags which are used on any node. This could be the publiclab.org/tags page, which I think we've identified as a potential issue before.

**Comment by jywarren** [comment]
Yes, it's this query: https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L8-L12

**Comment by jywarren** [comment]
Let's fix this.

**Comment by jywarren** [comment]
Gosh, that's a huge query. It must return all nodes, which is about 5400 as per publiclab.org/stats.

Let me see...

**Comment by jywarren** [comment]
OK, making a pull request. Starting with `.select('node.id, node.status, term_data.*, community_tags.*')` to not get the whole node record. Then I'm going to limit this to usages in the past month.

**Comment by jywarren** [comment]
OK, adding this too:

`               .where('community_tags.date > ?', (DateTime.now - 1.month).to_i)`

**Comment by jywarren** [comment]
If this passes, go ahead and merge, @icarito !

**Comment by icarito** [comment]
Okay today we're experiencing the same issue. I've taken a number of measures but can't seem to bring back to normal.
 - I've restarted nginx and mysql
 - I've changed vm.swappiness from 10 to 5
 - I've limited rails passenger_max_pool_size to 4 (reducing memory consumption)
 - I've disabled swap on /dev/xvdc drive only leaving /swapfile

**Comment by icarito** [comment]
I'm running analyzers again for today's timeslice, those are from last night until 11:40 AM

**Comment by icarito** [comment]
Also tried disabling solr, didn't seem to help.

**Comment by icarito** [comment]
Actually, it did help, quite a lot. 
![image](https://user-images.githubusercontent.com/199755/31039000-ae97217a-a53f-11e7-83c5-5c3b576a8441.png)
Perhaps it's related to #1604

**Comment by icarito** [comment]
After having resorted to disabling Solr yesterday, things went for the most part back to normal. At 21:31 pm EST there was another peak, which I've marked in the following graph.

I purposefully used this one short event to do a detailed log analysis for only a 10 minute timeslice.
Pasting the log analysis on matrix.

![image](https://user-images.githubusercontent.com/199755/31046462-63b3e542-a5be-11e7-994f-9a9873d544c0.png)

**Comment by icarito** [comment]
Here's MySQL-slow log for the 10 min timeslice above:
https://matrix.org/_matrix/media/v1/download/matrix.org/ZJrqIMZLFhZNsfrZGfZiSquP

And production log analysis:
https://matrix.org/_matrix/media/v1/download/matrix.org/INVaStNeQKpqjirimHorKHzf

**Comment by icarito** [comment]
Here's a reference to a good resource to debug model: https://www.schneems.com/2017/07/18/how-i-reduced-my-db-server-load-by-80/ looks strangely familiar...

**Comment by icarito** [comment]
@steviepubliclab reported on #publiclab that we're still showing slowness. I'll run the log analyzer for the past couple of days to see where we could optimize again.

**Comment by jywarren** [comment]
Ok, thanks!

**Comment by jywarren** [comment]
Just a few more graphs to look at here:

![screenshot 2017-10-14 at 9 00 40 pm](https://user-images.githubusercontent.com/24359/31581525-0e92eb88-b123-11e7-85c7-36fa74fa4d91.png)

![screenshot 2017-10-14 at 9 01 06 pm](https://user-images.githubusercontent.com/24359/31581526-10313472-b123-11e7-99f3-016c4420a024.png)

**Comment by jywarren** [comment]
I'm thinking about whether simply showing more images on the front page may actually be slowing things down. Think about how many of these are due to the new section at the bottom of the home page:

```
fanboat-narrow-2.jpg | 200 | jpeg | (index) | 296 KB | 376 ms
oil-testing-matej.JPG | 200 | jpeg | (index) | 305 KB | 220 ms
IMG_20160709_181427.jpg | 200 | jpeg | (index) | 394 KB | 766 ms
beach.jpg | 200 | jpeg | (index) | 768 KB | 2.23 s
gowanus.jpg | 200 | jpeg | (index) | 700 KB | 2.05 s
canoe.jpg | 200 | jpeg | (index) | 227 KB | 757 ms
regional-br.jpg | 200 | jpeg | (index) | 84.3 KB | 710 ms
LizBklnNRG.jpg | 200 | jpeg | (index) | 134 KB | 757 ms
1012172009b.jpg | 200 | jpeg | (index) | 102 KB | 719 ms
hog_bayou_africatown_satellite.png | 200 | png | (index) | 242 KB | 723 ms
Screen_Shot_2017-10-09_at_10.12.48_PM.png | 200 | png | (index) | 231 KB | 724 ms
Screenshot_2017-09-20_at_10.37.43_AM.png | 200 | png | (index) | 239 KB | 709 ms
squid-kite.jpg | 200 | jpeg | (index) | 49.2 KB | 754 ms
leaf2017_20171001-1188.JPG | 200 | jpeg | (index) | 129 KB | 366 ms
LAB.JPG | 200 | jpeg | (index) | 46.9 KB | 364 ms
IMG_20161112_142853.jpg | 200 | jpeg | (index) | 54.1 KB | 272 ms
16x9-boat.jpg | 200 | jpeg | (index) | 35.1 KB | 264 ms
Screen_Shot_2017-04-04_at_12.59.11_PM.png | 200 | png | (index) | 166 KB | 230 ms
harvey-5-gty-er-170825_16x9_992.jpg | 200 | jpeg | (index) | 85.5 KB | 213 ms
```

**Comment by jywarren** [comment]
We could test this simply by disabling that bottom section. If this turns out to be the issue, we could:

* enable gzip
* hide this section until you scroll down, and only if you have javascript?

**Comment by jywarren** [comment]
As of #1697 and #1718, the front page activity feed seems **not to be the issue**. Huh. 

Now looking around http://jenkins.laboratoriopublico.org/job/Plots-Stable/200/ -- maybe item #4 on http://jenkins.laboratoriopublico.org/job/Plots-Stable/198/ ?

This is kind of a heavy query: 

https://github.com/publiclab/plots2/pull/1608/files#diff-a8eb2425ebeb0814d010864bb014e815R58

We could try disabling that as a test? Or we could just optimize it. I think I can make it dramatically simpler... will post a PR.

**Comment by jywarren** [comment]
Merging in #1719 when ready.

**Comment by icarito** [comment]
So in order to continue diagnosing this:
 - We have a number of log analysis on `tycho:/srv/analyzer/`
 - I'm going to track down logs for the week Sept 11th - 18th which is _before_ the performance regression to compare.

**Comment by jywarren** [comment]
Cached the activity feed query here: https://github.com/publiclab/plots2/pull/1738

**Comment by icarito** [comment]
This is a short summary of our current performance story and how it has evolved over time. All graphs show request duration for a complete week.

In September we were in a very good position. Average response times were under 100ms with small peaks during nightly backups:

![image](https://user-images.githubusercontent.com/199755/32244042-4dad4316-be45-11e7-8890-d30b81ddc472.png)

Starting Sept. 19th, things changed quite a lot. The most significant change appears to have been the homepage activity feed.

Minimum duration rose to 3s, and we found long peaks and some downtime.

![image](https://user-images.githubusercontent.com/199755/32244036-4744da70-be45-11e7-8eec-ac6eb5cf09d0.png)

A number of optimizations were taken in order to mitigate the problem, including caching the homepage activity view section. This reduced peaks but didn't improve baseline performance.

![image](https://user-images.githubusercontent.com/199755/32244020-3f66af9a-be45-11e7-9f2c-6716754c5a09.png)

Last week  (Oct 28th), Jeff and I continued to diagnose and found that the actual database query could be cached, resulting in finally recovering our baseline performance.

The peaks, however, haven't stopped occurring, if anything, they appear worse. Note the y-scale of the graph is different for each graph.

![image](https://user-images.githubusercontent.com/199755/32244003-2fd62100-be45-11e7-9d9a-e8e911b3dfad.png)

I've not actually found that these peaks cause downtime and log analysis suggest few users get errors, however it would be good to dig deeper and recover our neat flat graph.

**Comment by icarito** [comment]
[2017-10_analysis.zip](https://github.com/publiclab/plots2/files/1431972/2017-10_analysis.zip)
Here's the log analysis files for past days. I wasn't able to identify an obviously heavy query.

**Comment by jywarren** [comment]
I wonder if these peaks are the queries actually running to generate the
cache, which could happen every 10m. We could slow that down to 20 or 30
minutes to test this?

**Comment by icarito** [comment]
I think it would be worth it to try!

**Comment by jywarren** [comment]
Can you file a PR based on this?

https://github.com/publiclab/plots2/blob/master/app/controllers/home_controller.rb#L12

https://github.com/publiclab/plots2/blob/master/app/controllers/home_controller.rb#L40

These two lines can be tweaked for timing. Thanks!

Also - i'll be offline due to the Barnraising this friday, so if we could
skip this week's meeting that'd be great, sorry!

**Comment by icarito** [comment]
I will! Have a great Barnraising!

**Comment by icarito** [comment]
I've merged https://github.com/publiclab/plots2/pull/1755 and deployed it. Set chache timeout to 30m. Let's hope this reduces the load!

**Comment by icarito** [comment]
Here's the top query by sum, from the period affected by Monday's peak reported at #1686.

Query time - by sum | Hits | Sum | Mean | StdDev | Min | Max | 95 %tile
-- | -- | -- | -- | -- | -- | -- | --
publiclab@172.18.0.1: SELECT rusers.* FROM rusers WHERE rusers.persistence_token = :string LIMIT :int | 126 | 12m59s | 6.18s | 1.53s | 5.01s | 17.21s | 5.06s-11.14s
publiclab@172.18.0.1: SELECT users.* FROM users WHERE (name LIKE :string AND access != :int) ORDER BY uid DESC LIMIT :int | 118 | 11m33s | 5.87s | 1.11s | 5.02s | 12.13s | 4.98s-9.79s
publiclab@172.18.0.1: SELECT :int AS one FROM rusers WHERE rusers.persistence_token = BINARY :string LIMIT :int | 14 | 3m19s | 14.22s | 6.26s | 5.54s | 21.77s | 5.48s-21.93s
publiclab@172.18.0.1:  SELECT node.nid, node.status, term_data.*, community_tags.* FROM  term_data INNER JOIN community_tags ON community_tags.tid =  term_data.tid INNER JOIN community_tags node_tags_term_data_join ON  node_tags_term_data_join.tid = term_data.tid INNER JOIN node ON node.nid  = node_tags_term_data_join.nid WHERE (node.status = :int) AND  (community_tags.date > :int) GROUP BY name ORDER BY count DESC LIMIT  :int OFFSET :int | 25 | 3m03s | 7.31s | 1.85s | 5.04s | 12.10s | 4.98s-12.27s
publiclab@172.18.0.1:  SELECT node_revisions.* FROM node_revisions INNER JOIN node ON node.nid =  node_revisions.nid WHERE (type = (:string)) AND (node.status = :int)  AND (node_revisions.status = :int) AND (timestamp - node.created >  :int) GROUP BY node.title, DATE(FROM_UNIXTIME(timestamp)) ORDER BY  timestamp DESC LIMIT :int | 21 | 2m58s | 8.47s | 2.99s | 5.10s | 15.99s | 5.06s-16.14s

**Comment by icarito** [comment]
[Nov06.zip](https://github.com/publiclab/plots2/files/1452831/Nov06.zip)

Here's the analysis for rails logs and full mysql-slow logs analysis if they shed some more light.

**Comment by icarito** [comment]
Adding an index to `persistence_token` will help.

**Comment by icarito** [comment]
I think users are having performance issues. We have two options to restore performance. Either:
  1.  We roll back to plots2 version 2017-09-18, before the performance issues began.
  2.  We migrate to a larger server.

I can do (2) as early as tonight or schedule it for the weekend during lower traffic hours. 
@jywarren I think doing it would be a good idea. I think we can consolidate a couple of smaller servers into one and remain within our hosting constraints.

**Comment by icarito** [comment]
This week's response times:
![image](https://user-images.githubusercontent.com/199755/32608970-0798e4b4-c52c-11e7-83e1-e05ed4f65427.png)
While baseline is better, peaks seem worse, subjectively.

**Comment by jywarren** [comment]
I think there's a way to "flex" the server to higher capacity in Rackspaces
control panel but it says it may incur downtime. We could try overnight?

**Comment by icarito** [comment]
Thanks, I did see that option that comes with the warning: **"Warning: Resizing will take the server offline for minutes or hours depending on server size. Afterwards, you'll have 24 hours to revert the resize if there are problems."**. This did sound a little bit opaque, and the next option to "resize" is actually doubling the cost (but it should fall within range of sponsored hosting).
Thinking it over, it does sound like the least trouble. We could fold archive.publiclab.org into our main server if it turns out we need the hosting credit.

**Comment by icarito** [comment]
For reliability and user experience I think we should do the server upgrade. I'm up for the task tonight, I can give notice to the mailing lists in advance. I don't like the "minutes or hours" approach to systems upgrade nor having any downtime at all, but if midnight unscheduled maintenance in that time range is fine, then the direct Rackspace upgrade is the simplest as there would be no messing with DNS. @jywarren do confirm if you can.

**Comment by icarito** [comment]
@jywarren clarifying, I can do the upgrade completely without your assistance, if doing the Rackspace resize route. A new server would have a different IP and we would need to change DNS records.

**Comment by jywarren** [comment]
Yes let's do this. Thank you Sebastian and do please send out a warning,
including to staff@.  Thanks!

**Comment by icarito** [comment]
Confirmed then. I'll post announcement with a couple of hours advance warning.

**Comment by icarito** [comment]
Resize in progress. Documentation doesn't give details: https://support.rackspace.com/how-to/managing-your-server-resizing-standard-and-general-purpose-servers/

I'll wait it out and confirm. Hopefully this will give us some room to breathe.

**Comment by jywarren** [comment]
Cool, are we still on for our meeting today? If you were up very late, I'm
sure you're exhausted. Any initial improvements noticeable?

**Comment by jywarren** [comment]
Let's also add the persistence token index. Good idea.

**Comment by icarito** [comment]
Sure, I'm up for the meeting! I'll check graphs, only subjectively it
does feel snappier.

**Comment by jywarren** [comment]
Yes perhaps we should look at it if fills up again given time.

**Comment by jywarren** [comment]
Overall progress on CPU load for past few months -- pretty interesting:

![screen shot 2017-11-10 at 11 54 32 am](https://user-images.githubusercontent.com/24359/32669504-c659ab94-c60e-11e7-8a2a-64101ef5a8ed.png)

The big change on ~ Aug 28 was an index on `rusers.status` -- huuuuuge boost. 

Just made optimization for `persistence_token` (added index) - #1767.

**Comment by jywarren** [comment]
Closing!
