### ISSUE TITLE
No notification for disallowed filetype uploads

### ISSUE THREAD

**Issue by skilfullycurled** [publiclab/plots2#165]
I created a research note and the drag and drop uploading for images uploaded without issue.  However, when I drag over an STL file, or choose it, the uploading progress bar does it's animation, but then it hangs at the end and never completes.  I've tried this multiple times, as well as after publishing it, and refreshing, etc.  I'm using Firefox 32.0.3.  Here's the link to the note:

http://publiclab.org/notes/bsugar/10-08-2014/pvc-pipe-fitting-modification-to-3d-printed-body

Since I can't attach the file here, I'll email it to web@publiclab.org.

**Comment by gauravano** [comment]
Hi everyone! Closing this as I have re-opened it at https://github.com/publiclab/plots2/issues/5039. Thanks!
