### ISSUE TITLE
Automated tests fail due to Solr being enabled in test mode -- should disable it

### ISSUE THREAD

**Issue by fuentesj** [publiclab/plots2#1654]
### What happened just before the problem occurred
Unfortunately, this issue has always occurred for me on my machine. While some tests do successfully run & pass, many others simply timeout. 

### What's the problem?
Oftentimes, I see `Net::OpenTimeout: execution expired` come up in the test output. Based on my understanding, something is trying to open up a HTTP connection when I run the tests locally, but cannot appear to do so.

### Relevant URLs
1. When I run `rake test TEST=test/functional/comment_controller_test.rb`, I get the following [output for comment_controller_test.rb](https://gist.github.com/fuentesj/cf0d3075198705989961fc9af9249457)

2. When I run `rake test:functionals`, I get the following [output for functional tests](https://gist.github.com/fuentesj/3de86190b1e1d1e5286c26338e8a9a78): Note how in some cases you'll see the following: 
```
SocketError: Failed to open TCP connection to solr:8983 (getaddrinfo: nodename nor servname provided, or not known)
```
According to `config/sunspot.yml`, I believe solr should only listen on port `8983` in a production environment, and solr should listen only on port `8981` in a test environment. Could some tests be misconfigured? I might have messed up while setting up my local dev environment.

### Additional Information
1. I've noticed that many tests appear to fail at `lib/authlogic_openid/authlogic_openid/acts_as_authentic.rb:74`. Here's an excerpt containing that bit of code: 
```
def save(perform_validation = true, &block)
  return false if perform_validation && block_given? && authenticate_with_openid? && !authenticate_with_openid
  result = super
  yield(result) if block_given?
  result
end
```

### Browser, version, and operating system
OS: MacOS Sierra 10.12.5
Ruby: ruby 2.3.5p376 (2017-09-14 revision 59905) [x86_64-darwin16]
Rails: Rails 3.2.22.4

**Comment by jywarren** [comment]
@maxtedford, is this what you're seeing?

**Comment by maxtedford** [comment]
@jywarren, yes that's what I was experiencing as well.

I've included the `disable: true` flag inside the `sunspot.yml` in #1660, which I believe should fix the problem once it's merged (at least it did for me locally).

@fuentesj, you might try that as well in your local `sunspot.yml` to see if that helps:

![screenshot 2017-10-02 15 44 17](https://user-images.githubusercontent.com/9435299/31095957-8f6d4324-a788-11e7-8c90-532ccc053e6c.png)

**Comment by fuentesj** [comment]
@maxtedford, that worked for me as well! Thank you! I'll close this issue now.

**Comment by jywarren** [comment]
Hi, all -i'm going to re-open so that we figure out if we ought to disable this by default to make running tests easier for everyone -- we could switch it back for Travis tests, for example. 

Thanks!

**Comment by jywarren** [comment]
Trying to address in #1537.
