### ISSUE TITLE
add a one sentence explanation at the top of /research like we have at the top of /wiki

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#166]
Currently /research says 
*Research notes ideas & documentation from contributors like you*

/wiki is rather more helpful, as it also includes an explanatory sentence.  
*The Public Lab Wiki collaborative open documentation by contributors like you*
"At Public Lab, we all collaborate to invent and improve open source environmental science tools. Wiki pages are web pages that anyone can create or edit -- we use them to collect information, documentation, and instructions on projects."

**Comment by jywarren** [comment]
fixed in new dashboard!
