### ISSUE TITLE
IFTTT integration with twitter.com/mapknitter to post images is broken

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1662]
### What happened just before the problem occurred

checked twitter, saw mapknitter tweeting broken images

<img width="507" alt="screen shot 2017-10-03 at 5 03 53 pm" src="https://user-images.githubusercontent.com/161439/31151401-e4c37288-a85c-11e7-839b-7fb1cc2005d8.png">

### Relevant URLs

https://twitter.com/mapknitter

**Comment by jywarren** [comment]
Moved this to MapKnitter repository at https://github.com/publiclab/mapknitter/issues/248
