### ISSUE TITLE
auto-listing of barnstars on /barnstars & compact display on /profile/

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#167]
Two design issues brought up by Chris Fastie: 

1. how will the new barnstar system be displayed on /barnstars? How will legacy barnstars be displayed?
2. can barnstars be displayed more compactly on profile pages, and include custom graphics (if extant)?

Additional: how can offline stuff like "feeding the barnraisers" be captured in the new system which currently requires a research note to be posted before a barnstar can be awarded?

**Comment by jywarren** [comment]
I'd like to break custom graphics off into a new issue: #265

**Comment by jywarren** [comment]
Closing this for better-formatted/documented #705 for the remaining issue.
