### ISSUE TITLE
Search Query Out of Range Error

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#1678]
### What happened just before the problem occurred
On clicking this link : 
<img width="1399" alt="screen shot 2017-10-12 at 7 13 09 pm" src="https://user-images.githubusercontent.com/14952645/31499174-aece084c-af81-11e7-8e08-af5b79d72382.png">

Takes time for loading the page and then (see image):
<img width="1281" alt="screen shot 2017-10-12 at 7 09 12 pm" src="https://user-images.githubusercontent.com/14952645/31498922-e46e43d2-af80-11e7-95a7-14048eb5e66a.png">
  

<img width="629" alt="screen shot 2017-10-12 at 7 06 35 pm" src="https://user-images.githubusercontent.com/14952645/31498807-9cbc6f3c-af80-11e7-8dc0-70c64029d0cc.png">

### Relevant URLs

https://publiclab.org/stats
https://publiclab.org/stats/range/1-1-2010/12-31-2016/

### Browser, version, and operating system
Browser : Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
Operating system : macOS

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hi, thanks for reporting this! I see that line is:

`@end = params[:end] ? Time.parse(params[:end]) : Time.now`

Do you know what happens when you run `Time.parse('12-31-2016')? Maybe
we're ordering the month/day incorrectly?


On Thu, Oct 12, 2017 at 9:46 AM, Sagarpreet Chadha <notifications@github.com

**Comment by jywarren** [comment]
Yes! Look, this works:
https://publiclab.org/stats/range/01-01-2016/31-12-2016/

Can you submit a fix for that page here?
https://github.com/publiclab/plots2/blob/master/app/views/stats/index.html.erb#L15
