### ISSUE TITLE
Improve overall load time for front page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1686]
Server response time is 2.1, but full page load takes 9 seconds for the front page -- https://publiclab.org/ or if you're logged in, https://publiclab.org/home.

This is according to this nice tool by Google: https://developers.google.com/speed/pagespeed/insights/?utm_source=analytics&tab=desktop&url=http%3A%2F%2Fpubliclab.org%2F

That page suggests a number of improvements, which we could go through one by one, including:

* image compression
* asset (JS, CSS) compression
* Eliminate render-blocking JavaScript and CSS in above-the-fold content

The page even provides optimized images and assets we can use.

**Comment by Arvisix** [comment]
Can I assign this issue to myself?

**Comment by jywarren** [comment]
Sure, I think so! Some of these are in content (not in the codebase itself, so, like images), so if you could simply upload an optimized image in this thread, we can add it. I think we are doing JS/CSS compression... would that be gzip based, @icarito ? And the render-blocking stuff, yes, we should address that. 

Thank you!

**Comment by skilfullycurled** [comment]
In relaying (what I thought was) a funny story to @ebarry regarding the site, I happened to mention that the site took a *very* long time to load (front page, not logged in).  She pointed me to this issue and thought it might be helpful if I mention the specifics:  it was with Safari (I can find out the version if that would be useful) and we were trying to access the site around 4:00pm.  If it would make a remarkable difference, I could find out the exact time (it wasn't my computer).

Well.  I hope that helps.  And if it doesn't, please forward any complaints to my office c/o @ebarry.

**Comment by jywarren** [comment]
Thanks, 4pm Eastern, and can you tell us what day? Is a long time more than
10 seconds, or more like 30 seconds? Thanks for your work to move this
forward, @skilfullycurled!

On Nov 6, 2017 7:57 PM, "skilfullycurled" <notifications@github.com> wrote:

In relaying (what I thought was) a funny story to @ebarry
<https://github.com/ebarry> regarding the site, I happened to mention that
the site took a *very* long time to load (front page, not logged in). She
pointed me to this issue and thought it might be helpful if I mention the
specifics: it was with Safari (I can find out the version if that would be
useful) and we were trying to access the site around 4:00pm. If it would
make a remarkable difference, I could find out the exact time (it wasn't my
computer).

Well. I hope that helps. And if it doesn't, please forward any complaints
to my office c/o @ebarry <https://github.com/ebarry>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/1686#issuecomment-342350613>,
or mute the thread

**Comment by skilfullycurled** [comment]
> can you tell us what day? 

OMG.  Duh.  Sorry.  It was today (Monday, Nov. 6, 2017).

> Is a long time more than 10 seconds, or more like 30 seconds?

Browser load times have a way of making it seem as though a second is a year.  While I do not recall the exact amount of time, it was long enough that we thought to interrupt the loading process (e.g. click "x" in the URL bar), tried reloading the page, and even toggled the wifi on and off.  When we interrupted the process, the page displayed but only with a default font (not Junction) and I don't think the "Recent community activity" had loaded either.

Let me know if I can provide any other info.  Happy to help!

**Comment by icarito** [comment]
![image](https://user-images.githubusercontent.com/199755/32533564-5700c264-c41f-11e7-9836-b999c95f1dc4.png)

Hi, I think your experience aligns with one of those moments of peak load that the site has been experiencing for the past month and a half (since Sept 19th). For the long, detailed story, there's lots of info at #1641.

This is telling us that the performance degradation is affecting users.
We have two options to restore performance quick:
  1. We roll back to `plots2` version 2017-09-18, before the performance issues began.
  2. We migrate to a larger server.

The system load monitors seem to indicate that the load is at the database level. I'll try analyzing the timeslice of Nov.6 and see if a particular query can be discerned to be optimized.

![image](https://user-images.githubusercontent.com/199755/32534024-bf23795c-c421-11e7-85c8-9f63f0f76a17.png)

Starting Oct 28th we got a lower base time-to-first-byte but with very high peaks (in particular yesterday's).

![image](https://user-images.githubusercontent.com/199755/32534114-1b84d39e-c422-11e7-9876-ce4cbf79aa5d.png)

@jywarren it is also relevant that since Oct 28th, the CPU has been very busy.

**Comment by ebarry** [comment]
Excited that people are working on this! @jywarren and I checked load time on the front page earlier this week and got the result of 6.4 seconds of waiting: 

<img width="1275" alt="screen shot 2017-11-09 at 11 43 07 am" src="https://user-images.githubusercontent.com/161439/32617641-7abbb4c8-c543-11e7-8849-ed342b9176d7.png">

**Comment by icarito** [comment]
Thanks for the info @ebarry! A quick website is key to user engagement.

**Comment by jywarren** [comment]
We are now getting (in Providence, whereas @ebarry's screenshot is from New Orleans) ~3s time to first byte, rather than 6. 

![screen shot 2017-11-10 at 11 42 38 am](https://user-images.githubusercontent.com/24359/32668697-4d17baf2-c60c-11e7-9876-90d37e9c3eaa.png)

**Comment by jywarren** [comment]
On the front page, which is the original question here (not the dashboard) -- there are 2-3 images that are 700kb+ that we should probably figure out how to load slower. We currently use a carousel that loads them all at once. 

Could we not pre-load them all? Could we just show one and not rotate? Opinions?

**Comment by jywarren** [comment]
@Arvisix any interest in tackling parts of this still? Just checking, no pressure!

**Comment by jywarren** [comment]
Closing as we do well on this now plus have great monitoring via Skylight and Sentry.
