### ISSUE TITLE
Dropdown menus: remove "Connect", update "Get Involved"

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1701]
Hello! This is the latest iteration of the dropdown menus based on conversations with Stevie and Margie. Part of https://github.com/publiclab/plots2/issues/1621

1. Remove `Connect` menu entirely. 
2. Update `Take Action` menu name to `Get Involved`
3. Adjust the dropdown links under `Get Involved` to:

LINKNAME | LINK
Meet people | /events
Join the discussions | /lists
Chat online | /chat
Browse requests | /wiki/requests
See the latest research | /dashboard
Discover methods | /methods
Create an account | /signup
Ask a question | /questions
Post your work | /post

Thank you!!!!

**Comment by sagarpreet-chadha** [comment]
Sir can i try this ?

**Comment by jywarren** [comment]
That'd be great, thank you!!!!

Please mention @ebarry in your PR, when you open one, and if you could make
a screenshot that'd be great too. Thank you!

**Comment by ebarry** [comment]
WOW i'm so excited about this! Dear @sagarpreet-chadha, on behalf of the many people trying to make Public Lab a place where people can easily get involved, thank you so much for helping with our menus!
