### ISSUE TITLE
Publiclab.org top menu bar: change "Store" and "Donate" to buttons

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1702]
Hello! This is the latest update to the top menu bar. Part of https://github.com/publiclab/plots2/issues/1621

Margie (Fundraising Working Group) requested that Donate and Store appear differently from the dropdown menus, specifically as warm-colored buttons. 
We should think about how to approach this. Some points: 

* Donate and Store links in top menu bar are not dropdown menu items, instead, they both leave the publiclab.org website and go to monetary transaction areas. 
* Margie requests that Donate in particular be a warm color like orange. Maybe not red because too alarming. 
* Suggested that Donate and Store buttons should have a complementary color scheme. Perhaps a terracotta and sunflower. 
* Margie provided "Some examples of DONATE buttons from nonprofits kind of like us or with similar funders (#1 would be very nonintrusive). 1. https://www.techandciviclife.org/ 2. https://www.revealnews.org/ 3. https://ecodistricts.org/ 4. http://www.carpediemwest.org/"

**Comment by ianroberts131** [comment]
If this is still available, I can take a look over the weekend.

**Comment by jywarren** [comment]
Hi, I appreciate the offer of help but we need a little more time to think
through the color scheme before we're ready. If you'd like to submit a pull
request for the buttons themselves, and we can tweak the colors before
merging it, that would be helpful, but I want to be clear this may get
delayed a bit more than the usual issue due to the undecided colors. Thanks
so much though!

**Comment by ianroberts131** [comment]
Yep that's fine. I can submit a pull request, and then we can iterate on the color scheme until it's final.

**Comment by ryzokuken** [comment]
@jywarren I think we're using the standard color scheme that comes with bootstrap v3. If that's the case, we would just use something like the `danger` scheme to convey the idea.

Also, now that we're on this, I would also suggest to switch to bootstrap v4. It's out of alpha and looks very promising, plus it will improve the look and feel of the website quite a bit. We also won't have to take too many design decision for the same as the look of the components currently being used (eg: `navbar`) has been improved quite a bit as well.

**Comment by jywarren** [comment]
@ryzokuken - what would it take to switch to Bootstrap 4? could you make an
issue with a checklist so we can start preparing for it and possibly
breaking it up into smaller pieces? Would anything immediately break, or is
there a guidance doc with a provided upgrade checklist as some projects
provide?

Thanks!

**Comment by ryzokuken** [comment]
@jywarren I would definitely look more into it and let you know. The checklist idea sounds awesome! Could you make two checklist-based issues (one for Rails 5 and one for Bootstrap 4)?

I would try giving as much feedback and we can, and we would definitely break those changes into a ton of smaller tasks, possibly even FTOs. Let's make these changes gradually into other branches and merge into stable only when we're confident (the way we discussed regarding multibot).

Thanks

**Comment by jywarren** [comment]
There is already a checklist for Rails 4, which I think may be the first
step. There have been a couple attempts to do it. I think perhaps we have
to power through it in a weekend or something but if you can help
consolidate the currently open issues and PRs around this, that'd be super
helpful!

**Comment by ebarry** [comment]
Thanks for everyone's contributions on this, it's given us a lot to think about! Really impressed at how fast you created the buttons, @ianroberts131 and how thoughtfully you designed them after the references that Margie provided of outlined buttons! As Jeff said, we are circling up over here on some design issues. Perhaps we only add emphasis to the Donate button, and leave the Store link as is. Not sure yet, but thanks to your work this issue has already made a lot of progress and improvement! :D
