### ISSUE TITLE
Reveal tag subscribers

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1703]
Hello!
This issue is broken out from https://github.com/publiclab/plots2/issues/179

Relevant URL: https://publiclab.org/tags

Thanks to the amazing contributor community, publiclab.org/tags has recently received some upgrades, including the addition of a "Follow" button for each listed tag -- this is great!

As part of the community development team, i would like to be able to reach out to these groups of folks. 

How can we reveal all the people who are following each tag?

<img width="1101" alt="screen shot 2017-10-19 at 4 23 59 pm" src="https://user-images.githubusercontent.com/161439/31792427-fff30c28-b4e9-11e7-8f25-191c3f0259e6.png">

**Comment by Diksha2008** [comment]
I would like to work on this!

**Comment by ebarry** [comment]
This is so great that this exists -- thank you so much! 
Here's what the popup menu looks like for the largest tag `spectrometer` with 84 subscribers -- note that you have to scroll the entire page to see the full length of the pop-up window. 
![subscribers-popup](https://user-images.githubusercontent.com/161439/35392064-977cad68-01ae-11e8-9ceb-200bb0011729.gif)

What will happen to this window when we have have a pop-up window with a list of subscribers that is taller than the full height of the header and the footer? Keep in mind there are over 1000 people on our GoogleGroup and we are hoping by the end of this year to be migrating as many of these people as possible over here to subscriptions on the website. 

What do you think?

**Comment by jywarren** [comment]
What about showing 10 and having a link that says "see all 100" which leads
to a new page like `/tag/followers/_tagname_`?
