### ISSUE TITLE
Ability to sort tags alphabetically

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1704]
Hello! This issue is broken out from https://github.com/publiclab/plots2/issues/179

There is an ongoing effort to add functionality to https://publiclab.org/tags

Currently, tags are displayed by frequency of use. It would be great to have other ways to sort, most importantly by alphabetical order. 

Benefits: 
- people interested in air quality could browse all tags beginning with `air-` arguably a critical feature for any site depending on tags to organize collaborative work. 

Bonus: 
navigation by clickable letter `A` `B` etc

**Comment by sagarpreet-chadha** [comment]
Sir...can i take this one ?

**Comment by jywarren** [comment]
Yes please, that would be fantastic. Thank you so much!

On Sat, Oct 21, 2017 at 1:20 PM, Sagarpreet Chadha <notifications@github.com

**Comment by ebarry** [comment]
Wow!!!! WOW!!!!!

**Comment by jywarren** [comment]
Solved in #1714!

**Comment by ebarry** [comment]
Thank you again for this great contribution @sagarpreet-chadha ! I'm explaining this feature to new people joining Public Lab and feeling appreciative that it exists!

**Comment by sagarpreet-chadha** [comment]
Welcome mam...happy to contribute :)
