### ISSUE TITLE
Create new style:XXXXX powertag for Donate page

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1705]
I am posting this on behalf of Margie and the Fundraising Working Group

Margie is looking to change the style of https://publiclab.org/donate in several ways by using a powertag, similar to style:presentation which changes the lead image to full bleed and pushes down the left sidebar, but also including:

- remove left sidebar entirely (like style:blog)
- remove editing bar (like style:fancy)
- centers the text (like style:blog)

This style might be called `style:centered`

Thank you!!!!

**Comment by ebarry** [comment]
Here are all our powertags: https://publiclab.org/wiki/power-tags#General+power+tags

`style:blog` doesn't seem to have an effect on the page styling, mysterious.

**Comment by sagarpreet-chadha** [comment]
@jywarren sir...can i try this ?

**Comment by jywarren** [comment]
Thanks @sagarpreet-chadha but I think this needs a bit more information first. @ebarry have you found that you can't achieve this effect by adding both `style:presentation` and `style:fancy` at the same time? 

And If that gets partway there but still lacks something, can you narrow down this issue to just what's missing? Thanks!!!

**Comment by jywarren** [comment]
I believe this is complete!
