### ISSUE TITLE
Disable front page feed, observe performance, then decide what to do next

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1707]
@icarito and I are trying to determine the source of some performance issues, so we're disabling the front-page activity feed for a couple days. 

https://github.com/publiclab/plots2/pull/1697

Followup: look at graphs, logs, and consider turning it back on, or further optimizing it!

**Comment by icarito** [comment]
Just deployed this. I had just run a reload of the page with network pane developer tools open on my Chromium, and repeated it after deploying. Delay in first request for homepage dropped from 7s to 2.5s on my connection. Will be monitoring graphs over the weekend.

**Comment by jywarren** [comment]
Cool, how did this turn out? If you can post a graph that'd be super.
Thanks!

**Comment by icarito** [comment]
I did check the graphs and they indicate there was no significant improvement. We can re-deploy this then and start looking elsewhere!
![image](https://user-images.githubusercontent.com/199755/31910707-f8634ba4-b803-11e7-871c-95704e6a3a29.png)
