### ISSUE TITLE
rss feeds empty for banned users

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#171]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem
The code for RSS exposes banned users, but blocks their research notes from the RSS feed. See these lines: 
https://github.com/publiclab/plots2/blob/master/app/controllers/users_controller.rb#L154-L163

It'd be better if the banned user was treated as non-existent, as is done with the profile.

## Solution
Modify `@author = DrupalUsers.find_by_name params[:author]` to include status. This can be done using this query 
```ruby
@author = DrupalUsers.find_by_name_and_status( params[:author], 1 )
```

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by jywarren** [comment]
I think it'd be using a `User.where(status: 1, username: params[:author])` call!

**Comment by FlameFractal** [comment]
I'd like to work on this!

**Comment by jywarren** [comment]
That'd be great -- thank you and we're happy to help.

**Comment by ananyo2012** [comment]
@FlameFractal If you don't mind can look at other first-timer issues not labelled with the `gcin` label. This will be made as an Google Code-in Task.

**Comment by FlameFractal** [comment]
Sorry, didn't know that. It's just that all of the 9 issues currently in [first-timers-only](https://github.com/publiclab/plots2/labels/first-timers-only) appeared to be claimed, albeit not updated in a while, I didn't wanna barge in their progress!

**Comment by jywarren** [comment]
Not a problem! Perhaps there's a first timers issue someone's been stuck on
to a while and could use another set of eyes on it?

**Comment by ananyo2012** [comment]
Uh there are some [fto-candidate](https://github.com/publiclab/plots2/labels/fto-candidate) issues that you can see in the mean time. They are close to becoming first-timer issues. In fact they will be made first-timer issues soon.

**Comment by jywarren** [comment]
Hi, @FlameFractal -- GCI has wrapped up and this one is still up for grabs -- we'd love to have your contribution here if you're still interested!

**Comment by jbkimble** [comment]
@jywarren Does this issue still need someone to look at it?  I'd be happy to work on this over the next several days.  Thanks!

**Comment by jywarren** [comment]
It seems to still be open, please take a try!

**Comment by jbkimble** [comment]
@jywarren Awesome, I'm on it!

**Comment by Sh1pley** [comment]
@jywarren Hi there,  would be interested in taking this on. If it isn't otherwise claimed as in progress.  Didn't see a PR up that matched. Thought I'd ask.

**Comment by jywarren** [comment]
Yes please! Thank you!

**Comment by Sh1pley** [comment]
@jywarren got it all installed locally and ran tests, got one failure: 
<img width="1518" alt="screen shot 2017-03-29 at 11 19 26 am" src="https://cloud.githubusercontent.com/assets/12022194/24467441/ae1b9c94-1471-11e7-81eb-8be5574bf834.png">

Is this something I should just press on from (known issue) or something that is broken on my side?
seems from the error message that its a fail based on expected order? Not 100% sure as I haven't completely dove in to the code base around it yet.

**Comment by aki94** [comment]
hi sorry for being late i want to apply for gsoc and looking for first time bug is there any ?  which i can take?

**Comment by Sh1pley** [comment]
Hey, thank you for the email. I am excited to get started with Open Source. I am a student at the Turing School of Software & Design, and have been learning back end Rails apps for the last 6 months. I dove into the code base and see how the author .find_by_id and status is used in the users controller. I see that rss is a separate route, but a little foggy on implementing the rss to ignore a banned user, as the users controller already doesn’t parse their notes. Is this a change that should live in the users controller, users model, or somewhere in the rss service?

Haha, sorry for all of my questions out of the gate, pretty excited to get started on a preexisting app.

Thanks,

Jesse

**Comment by jywarren** [comment]
Hi, Jesse, it does look like an ordering issue. I wonder if it's related to
timestamps, perhaps? Does it happen every time you run tests?

We may be able to ignore it if it does not happen on tests on our TravisCI
testing service once you submit a commit, but we should probably pin down
the problem anyways.

As to where to screen for banned users, I believe RSS feeds are assembled
in the feeds controller. We can likely add a filter for user status to the
activerecord queries there. I'm happy to offer more help if you need!

Ankit, please check out our welcome page at
http://github.com/publiclab/plots2/projects/2, we're happy to have you help!

**Comment by Sh1pley** [comment]
@jywarren Yeah same fail on each run. I will look past it and work on the RSS card, and like you said let Travis and his all seeing-ness catch it, if its actually an issue.

**Comment by Sh1pley** [comment]
@jywarren Also one more question. Is there a possible banned user that I can try and send a request to /feed/:author to see what the current response is. And I am assuming that the desired response is just 404 if specified author has been banned? like it/they never existed? 

thanks again.

**Comment by jywarren** [comment]
Hi, thanks -- looks like Travis doesn't care, so maybe we should open a separate issue. It is odd though! The test is here: https://github.com/publiclab/plots2/blob/master/test/functional/tag_controller_test.rb#L117 and maybe there's something to do with sqlite ordering... sometimes these kinds of failures can be quite subtle. 

Anyhow I see your changes at #1361 -- thanks! I think a 404 would be perfect. Do you think this behavior merits a test, perhaps in https://github.com/publiclab/plots2/blob/master/test/functional/users_controller_test.rb ? Note that we haven't been testing for user rss feeds, but it'd be pretty easy to write one for the basic feed and then one for a banned user (see the fixtures -- we have one, I'm sure). Would you mind giving that a try? 

Thanks so much for your PR!

**Comment by jywarren** [comment]
And if you haven't written tests before, i'm happy to help you out with that too!

**Comment by Sh1pley** [comment]
Yeah, of course I'll write a couple tests. Better late than never!

**Comment by Sh1pley** [comment]
@jywarren Hey sorry for the lack of progress. Jumping into those tests now, had a chance to look into the fixtures files.. don't see any reason I can't write a few tests for this specific thing.

**Comment by jywarren** [comment]
OK, no problem, i just left some comments on your pull request!

**Comment by DoReMiFaSoLaTiDo** [comment]
@jywarren, please may I know if this is still open or @Sh1pley has delivered on the test and implementation?

**Comment by jywarren** [comment]
Hi, @Sh1pley - what do you think? good start over at https://github.com/publiclab/plots2/pull/1361 -- any chance to wrap it up, and can we help you out? Or could @DoReMiFaSoLaTiDo pick up where you left off?

Thanks!

**Comment by wizofe** [comment]
@jywarren I can also jump in, if you need me! ta

**Comment by jywarren** [comment]
Yes, thanks -- really, at this point anyone who wants may give it a try -- but please try to use #1361 as a starting-off point! Much appreciated!

**Comment by jywarren** [comment]
Hi, folks - has anyone made some more progress on this one? I'd be happy to help out.

**Comment by jywarren** [comment]
Also we just posted a new first-timers-only issue -- will start posting new ones regularly now: https://github.com/publiclab/plots2/projects/2
