### ISSUE TITLE
Minor issue with Cloud9 setup instructions

### ISSUE THREAD

**Issue by ianroberts131** [publiclab/plots2#1711]
I recently setup this project on Cloud9, and noticed a small issue with the instructions at https://github.com/publiclab/plots2/wiki/Simple-Installation-for-Cloud9

For item 3, the instructions state to enter `https://github.com/<your-github-username>/plots2.git` before creating the workspace. However, I believe this should be `git@github.com:<your-github-username>/plots2.git`. When I tried the former, it did not clone the repository properly.

I'm happy to submit a pull request to update if you agree.

**Comment by ryzokuken** [comment]
I think this is because the former uses HTTPS while the one you mentioned uses SSH. Technically, both should work.

**Comment by ianroberts131** [comment]
Interesting, when I tried using HTTPS the first time it didn't work, just tested again and it worked just fine. Nevermind then!

**Comment by jywarren** [comment]
Thanks for filing though -- we're definitely interested in catching any
rough spots in the install process!
