### ISSUE TITLE
Email notifications for questions, etc., Could be better for UX

### ISSUE THREAD

**Issue by pdhixenbaugh** [publiclab/plots2#1713]
The template for alerting users about new answers makes it difficult for the user to see at a glance if the information is relevant.

Improving this would help users return to the PL website after seeing the emails with relevant information at a glance in their inbox.

It might be useful to look at all the email templates and compare them to examples from other way platforms to see if they can be improved to provide a better experience for users.

A better template might be something like,

~~~
"[PL]Q: What are some lessons learned...? An answer has been posted on Public Lab"

Hi! <User> responded: <first few words of answer>. Do NOT reply to this email; click this link to see the answer:
https://publiclab.org/questions/pdhixenbaugh/03-14-2017/what-are-some-lessons-learned-using-the-riffle-especially-underwater#a497
~~~

Compared to the older version:
~~~
"[PublicLab] New answer to Question: What are some lessons learned using the Riffle? (Especially Underwater)

Hi! A new answer has been posted for your question 'What are some lessons learned using the Riffle? (Especially Underwater)'. Do NOT reply to this email; click this link to see the answer:
https://publiclab.org/questions/pdhixenbaugh/03-14-2017/what-are-some-lessons-learned-using-the-riffle-especially-underwater#a497

Here is the answer that anuj2017 wrote:

(First few words of answer)..... Lorem ipsem"
~~~

The only problem I can foresee with this is spammers taking advantage of this vector to get eyeballs on their message. To minimize that problem it might be prudent to hold answers in moderation for new users.

What do you all think?

**Comment by pdhixenbaugh** [comment]
![screenshot_20171022-110743](https://user-images.githubusercontent.com/16969821/31864992-226b3026-b71c-11e7-897b-77fe38149107.png)

Here is the information-poor current version, and how it shows up in the inbox

**Comment by jywarren** [comment]
I like this -- the templates are available in this folder: https://github.com/publiclab/plots2/tree/master/app/views/answer_mailer

There are a few of them, but perhaps we can start with the one to the original author, and work from there: 

https://github.com/publiclab/plots2/blob/master/app/views/answer_mailer/notify_question_author.html.erb

This may disrupt peoples' filters a little bit but I think it's worth it for the easier readability. Thanks for the great suggestion -- i'm marking this as a first-timers-only candidate, and hopefully someone will submit a fix based on your before/after changes above!

**Comment by Gauravano** [comment]
@jywarren I would like to take this issue 

A few doubts:-
-  The subject needs to be changed or not?
- I guess report to moderators option has to be removed as we are not showing the complete answer to 
  the user in the mail and giving him redirect link to the answer of his question. 
Please, @jywarren @pdhixenbaugh mention more ideas. Thank You.

**Comment by jywarren** [comment]
Hi, I believe @pdhixenbaugh suggested a shorter title so it shows up more readably on small screens, so yes please! 

I think we can leave the line about moderators in there for now. 

@pdhixenbaugh -- i think we will start to have to moderate answers soon, but perhaps we should open a separate issue up for that, if that's OK?

Thanks!

**Comment by pdhixenbaugh** [comment]
That all sounds like a great way of doing things!

**Comment by Gauravano** [comment]
hi @jywarren, please comment on modified template
![issue2_prop1](https://user-images.githubusercontent.com/20878070/32248419-a7b64fcc-beab-11e7-9646-5b2528aa5f87.png)

**Comment by pdhixenbaugh** [comment]
Hey! Are you able to take a screenshot of what that would look on a phone?
(Maybe forward it to your phone)

**Comment by namangupta01** [comment]
@Gauravano Already done in pr #1747 and open in issue #1746

**Comment by namangupta01** [comment]
@pdhixenbaugh As far as i know this is only for the development mode, so no point to open this on mobile.

**Comment by Gauravano** [comment]
Hey, @namangupta01 I think you are confusing this issue #1713  with other issue #1747 .This issue is about enhancing template of email sent to the user when someone answers his asked question and it has nothing to do with letter opener gem.I have used letter_opener gem just to show @pdhixenbaugh and @jywarren how new template will look and will remove it once we'll finalize a template.

**Comment by Gauravano** [comment]
@pdhixenbaugh as you asked for mobile view here it is 

![screenshot_20171101-173145](https://user-images.githubusercontent.com/20878070/32274210-c1efd9fa-bf2b-11e7-92ff-0d23272852aa.png)

![screenshot_20171101-173220](https://user-images.githubusercontent.com/20878070/32274208-c17e825a-bf2b-11e7-8471-d640e808b6bc.png)

![screenshot_20171101-173225](https://user-images.githubusercontent.com/20878070/32274209-c1b8ca78-bf2b-11e7-9d15-d33d1c19a430.png)

**Comment by jywarren** [comment]
Hi! Responding in the PR. Thanks everybody!!!

**Comment by pdhixenbaugh** [comment]
This looks awesome! The only other thought I have is - could the bracket
prefix be shortened to [PLab] to allow more characters in the preview, but
maybe not :)

**Comment by jywarren** [comment]
Closing this as we solved the major issue! Thanks, and let's open a new one for any follow-ups you'd like to pursue. :-)
