### ISSUE TITLE
Upgrade to Bootstrap 4

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plots2#1716]
We need to upgrade to Bootstrap 4, and this issue will hold a checklist for the same in the future. For now, we need to consolidate all the tasks we need to perform the migration and make a list of them in here, then break them into small self-contained and easy to solve issues.

Reference:
1. http://getbootstrap.com/docs/4.0/migration/
2. http://www.dotnetcurry.com/javascript/1334/migrating-bootstrap-3-to-bootstrap-4
3. http://upgrade-bootstrap.bootply.com (you can put HTML in here and it'll help you convert it!) 

/cc @jywarren 

# Checklist

## General Recommendations / Miscellaneous

- [x] Make a branch called something along the lines of `bootstrap-4` in the `publiclab/plots2` repository. All PRs made for this issue and all related ones need to use that branch as a base and not `master`. That branch would be merged into `master` only when the migration would be complete, we would verify the results and optionally, bootstrap 4 comes out of beta.
- [ ] Fixing pagination
- [x] Fixing the navigation bar

## Deprecated --- Replace with modern alternatives

- [x] Refactor all existing `well`s into `card`s.
- [ ] Refactor all existing `panel`s into `card`s.
- [ ] Refactor all existing `thumbnail`s into `card`s.
- [x] Glyphicons, if any, should be replaced by other icons. Let's use only font-awesome for all our icons, they are good enough for most of our use cases.

## Grid System

- [ ] Bump all grid sizes by one. (eg: `sm` becomes `md`, `md` becomes `lg` and so on).
- [ ] Add support for new `xs` tier for improving support at smaller mobile/IoT devices.

**Comment by jywarren** [comment]
Let's pull out anything from these checklists into our own checklist -- and let's split our checklist into 

1. things we can do on the master branch (i.e. that are viable for both Bootstrap 3 and 4, if any) 
2. things that we must do all at once

Thanks for getting this started!

**Comment by jywarren** [comment]
I added a few items to the checklist.

**Comment by ryzokuken** [comment]
@jywarren Added a few things to the checklist. Let's decide over chat what to refactor `panel`s, `thumbnail`s and `well`s into.

**Comment by jywarren** [comment]
I think the converter above has recommendations on that! wells become
cards, panels too, and thumbnails, they may convert to the new media type,
for < 480px screens?

**Comment by sagarpreet-chadha** [comment]
@jywarren sir can i start working on this ?
 Also is there any existing branch or should i make a new one ?
Thank You .

**Comment by ryzokuken** [comment]
@sagarpreet-chadha sure! If there isn't a branch yet, let me know. I'll have one made.

**Comment by ViditChitkara** [comment]
@ryzokuken I guess there are so many check boxes which indeed needs a lot of refractoring so can I also contribute to it? @sagarpreet-chadha if you are fine with it?

**Comment by ViditChitkara** [comment]
@ryzokuken there isn't any branch named bootstrap-4. If you have made some changes related to this, could you please push them ?

**Comment by ryzokuken** [comment]
Sure. This will need a lot of people's efforts.

**Comment by jywarren** [comment]
Complete!!! Now to 4.2...

**Comment by jywarren** [comment]
Oops! Wrong one! I meant rails 4!

**Comment by ryzokuken** [comment]
@SidharthBansal I'd honestly recommend that you go with whatever you're more comfortable with, but yeah, completing your current project before jumping onto this sounds good. This is probably going to be a sizable task in itself.

Feel free to ping me whenever you need help with this even if I phase out a bit, I'd love to help out as much as I can.

**Comment by SidharthBansal** [comment]
OK great. Most probably this project will not end in Gsoc period. I will be happy to continue this project even after Gsoc period. :-)

**Comment by ryzokuken** [comment]
@SidharthBansal let's try our best and if we still cannot manage to squeeze this in, then so be it.

As I said, if you face any issues or need help with long tasks, feel free to hit me up and I'd jump in. Ideally, we could also do the important parts and decompose the rest as a series of "first timer only" issues.

**Comment by SidharthBansal** [comment]
Yeah, I want to finish this up early too as I want to work on other repos of public lab too.

**Comment by ryzokuken** [comment]
Feel free to help us maintain plotsbot when you're done!

**Comment by SidharthBansal** [comment]
@ryzokuken when are you free to discuss about this project?

**Comment by SidharthBansal** [comment]
@jywarren @ryzokuken shall I create first timers for conversion of glyphicons to font-awesome?

**Comment by jywarren** [comment]
ooh, that sounds great!

**Comment by SidharthBansal** [comment]
I have created the bootstrap-4 branch

**Comment by jywarren** [comment]
cool!

**Comment by SidharthBansal** [comment]
I searched the whole app directory. There are no glyphicons. We have font-awesome icons everywhere.
There are many glyphicons in public directory that needs to be changed, namely in public/lib/bootstrap, public/lib/bootstrap-datepicker, public/lib/bootstrao-token.....

**Comment by jywarren** [comment]
Ah, but those are installed via Bower, so they're external - not tracked in
our repository. So that part seems done!

**Comment by SidharthBansal** [comment]
So, we are done with glyphicons.
I will be installing the bootstrap gem then

**Comment by SidharthBansal** [comment]
I will be working on the remaining stuff of OAuth Login first.

**Comment by jywarren** [comment]
Hi, Sidharth - what did you think, did you make up your mind about what to spend the remainder of the summer working on?

**Comment by SidharthBansal** [comment]
I will be working on the spam moderation system.

**Comment by jywarren** [comment]
ok, awesome, thanks!

**Comment by jywarren** [comment]
Wow, i'm looking at this again... i wonder how hard it will be. It will require a lot of visual inspection to confirm things are working properly. We can use the unstable branch to do this, i think...

**Comment by SidharthBansal** [comment]
We need someone who has a lot of front end experience. When I tried this, each and every CSS and jss element was disturbed. Header, footer, main content, all the divs etc. This project needs to be done by someone who is a front end designer. We can't even break this up into smaller pieces as we need to change the gem first. As soon as we upgrade the bootstrap gems, changes gets reflected in the whole website.

**Comment by jywarren** [comment]
I think that's pretty true, although we could potentially make some GCI
tasks around finding broken things on the unstable test server, or even
local copy, to help catch everything... not sure. Just thinking ahead.
Thanks for your input!
