### ISSUE TITLE
Add an indicator for red colored banned users and a hover over the username to check for spammers quickly 

### ISSUE THREAD

**Issue by Diksha2008** [publiclab/plots2#1721]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem
When you go to page:

[http://localhost:3000/likes](url)

You see something like this: 

![image](https://user-images.githubusercontent.com/19832744/31958293-dcf7edaa-b90e-11e7-94f8-6756a7d3c345.png)

Here, The recent likes are listed with banned users depicted in red colour and black otherwise. There should be an indicator as to what red indicates. Secondly,  a hover for admin and moderators is required over the username  so that they can read peoples' bio quickly to check if they're spammers.

## Solution

The changes are required to be made in the following template:

[https://github.com/publiclab/plots2/blob/master/app/views/like/index.html.erb](url)

Add the indicator for red coloured banned user in `<p>` tags below the heading **Recent Likes** in this template something like this:

```HTML
<p>Username in red indicates <b><i>banned user</i></b>.</p><br>
```
Secondly, a hover over the username for moderators and admin only could be implemented by adding an if else condition to check for admin and moderators like this:
````ruby
<% if current_user && (current_user.role == "admin" || current_user.role == "moderator") %>

<a rel="tooltip" title="<%= like.user.bio %>" class="user" href="/profile/<%= like.user.name %>" style = "color: <%= like.drupal_users.status.zero? ? 'red' : 'black' %>"" > <i class="fa fa-user" aria-hidden="true"></i> <%= like.user.name %></a>

<% else %>

<a href="/profile/<%= like.user.name %>" style = "color: <%= like.drupal_users.status.zero? ? 'red' : 'black' %>"><i class="fa fa-user" aria-hidden="true"></i> <%= like.user.name %></a>

<% end %>
````
replacing this line of code https://github.com/publiclab/plots2/blob/3955e17ad30eda37854d97d7813a862060d2bbfd/app/views/like/index.html.erb#L16

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by jywarren** [comment]
This looks great, thanks so much!!! 🎉

**Comment by jywarren** [comment]
@sagarpreet-chadha - if you're interested in doing one of these as well, take a look here, it's worthwhile and very exciting when someone shows up to try to solve the issue :-)

**Comment by ebarry** [comment]
Wow @Diksha2008 this is a really super first-timers-only issue -- i wish i could write these as well as you can!!!!!

**Comment by sagarpreet-chadha** [comment]
@jywarren sir...Yes sir , I would love to ! Thanks !

**Comment by ViditChitkara** [comment]
@jywarren if this is open could I work on it?

**Comment by Diksha2008** [comment]
@ViditChitkara No, I am not working on it! you can go ahead with it!
