### ISSUE TITLE
create media@publiclab.org email address

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1728]
Dear @icarito and @jywarren 
for the purposes of attaching publiclab media accounts to an organization email that it is easy to rotate membership on, please create media@publiclab.org and send it to publiclab-media@googlegroups.com

**Comment by jywarren** [comment]
Hi, Liz - unfortunately, addresses like this aren't managed through the website, but through the non-profit's Google Apps account, I'll ping you offline to help get this set up. Thanks!
