### ISSUE TITLE
apply same button treatment to all tabs on tag pages

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1736]
hello everyone!

I noticed that this page https://publiclab.org/tag/pesticides has a very nice display of buttons for "Follow [topic]" "Ask a question about [topic]" and "Subscribe to answer questions on [topic]" that is consistent across most tabs (`Research Notes`, `Questions`, `Wiki pages`, `Maps` ):

<img width="636" alt="screen shot 2017-10-27 at 8 59 37 am" src="https://user-images.githubusercontent.com/161439/32105091-383bfb74-baf5-11e7-8990-f20a16e9feef.png">

....but not all tabs -- `Contributors` is very different, and I believe this may be an oversight:

<img width="577" alt="screen shot 2017-10-27 at 8 59 20 am" src="https://user-images.githubusercontent.com/161439/32105104-46b8aa62-baf5-11e7-94aa-a1f7ce0a7fd7.png">

Do we think this is fixable? Thanks!

**Comment by jywarren** [comment]
Hi, liz - I'm not sure exactly what it is you're seeing differently -- is
it the styling of the `RSS` & `Follow pesticides` buttons on the page:
https://publiclab.org/contributors/pesticides ?

Or do you mean that the tab leading to a separate page is unexpected,
versus the expectation of seeing a tab open in the same tab pane without
reloading the page?

Sorry to not immediately get what you're referring to! It's really helpful
to describe what you expected to see, so we can see what's wrong by
contrast. In fact, I'll add that to our Issue template! (
https://github.com/publiclab/plots2/blob/master/.github/ISSUE_TEMPLATE.md)

Thank you!!

**Comment by ebarry** [comment]
Hi Jeff, it's the second condition you describe: 

>the tab leading to a separate page is unexpected,
versus the expectation of seeing a tab open in the same tab pane without
reloading the page? 

and i would add, loading in the same tab pane including the same header. Having the header change is visually confusing when navigating by tabs.

**Comment by Gauravano** [comment]
Hi @jywarren @ebarry actually while going through this issue I observed there can be many changes possible to https://publiclab.org/contributors/pesticides page like we can remove the text part and 
![screenshot from 2018-01-17 01-26-26](https://user-images.githubusercontent.com/20878070/35009421-7b0cc8dc-fb25-11e7-889a-fb059bfbee5b.png)

can add something like this 
![insert2](https://user-images.githubusercontent.com/20878070/35009452-9958b774-fb25-11e7-8ef3-a51267f432df.png)
also, the icons can be changed to  
![insert1](https://user-images.githubusercontent.com/20878070/35009527-d1cb7718-fb25-11e7-9f9f-90bee3803f92.png)

What're your views about these changes?

**Comment by jywarren** [comment]
That sounds great!

**Comment by Gauravano** [comment]
Ok, I understood @ebarry what you are trying to say, we have to place a navbar at contributor page at the same position as its present on others pages.I will share a template to replicate same design on contributor page as others pages have.Thanks.

**Comment by Gauravano** [comment]
Also, If you want I can reverse the changes on done on this line syntax "180 people have contributed 651 research notes and 10 wiki pages tagged with "spectrometer" in the new template.What you say?

**Comment by ebarry** [comment]
I'm not sure! I did appreciate the sentence construction, but perhaps we
could better make a decision after we standardize the header and see what
everything looks like?
thank you sooooo much

--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net
