### ISSUE TITLE
add 'cancel' button to lead photo and comment image uploads

### ISSUE THREAD

**Issue by amysoyka** [publiclab/plots2#174]
Hey Jeff,

I posted in reply to this post (https://github.com/publiclab/plots2/issues/172), but no action as of yet.

The main article image photo upload box and the comments images upload box still don't have cancel buttons...just letting you know. I am guessing there could be other image upload boxes across the site without the 'cancel' ability still?

**Comment by jywarren** [comment]
Solving this in Rich Editor project, thanks! https://github.com/publiclab/PublicLab.Editor/
