### ISSUE TITLE
Donate Button

### ISSUE THREAD

**Issue by margiecohen** [publiclab/plots2#1749]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

The new Donate and Store buttons are a great modification but the blue/purple tone of word Donate is hard to discern. A lighter and more contrasting color (for example, yellow) would make the word Donate stand out better.

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hi Margie and thanks. I think a different shade of purple/blue could also
work. Perhaps the default Bootstrap blue shade, which we can look up.
This'll take some tests and we can upload some screenshots to discuss a new
color choice.

**Comment by ianroberts131** [comment]
@jywarren I'm happy to take this on once we wrap up #1748

**Comment by jywarren** [comment]
Solved!
