### ISSUE TITLE
add Public Lab specific welcome text to talk pages (etherpad)

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#175]
like, 
"Cool, here's a pad we can use to collaboratively write, and then copy into the main wiki page--YAY!"

**Comment by ebarry** [comment]
Can we install a WelcomeBot like OpenHatch created? https://github.com/shaunagm/welcomebot

example from me visiting #openhatch

welcomebot:

Welcome lizbarry!  The channel is pretty quiet right now, so I thought I'd say hello, and ping some people (like shauna, paulproteus, and marktraceur) that you're here.  If no one responds for a while, try emailing us at hello@openhatch.org or just try coming back later.  FYI, you're now on my list of known nicknames, so I won't bother you again.

**Comment by jywarren** [comment]
This should be a new issue, thanks Liz!

**Comment by btbonval** [comment]
I agree with @jywarren . This ticket is about the Etherpad pages, while the bot suggestion is for the chat program.

**Comment by ananyo2012** [comment]
@jywarren iframes do not render correctly. I am getting this error.
`Multiple 'X-Frame-Options' headers with conflicting values ('DENY, SAMEORIGIN') encountered when loading 'https://pad.publiclab.org/p/donate'. Falling back to 'DENY'.`
I have tried solutions in http://stackoverflow.com/questions/16561066/ruby-on-rails-4-app-not-works-in-iframe but it didn't help. Do you think same thing is to be done for https://pad.publiclab.org/ ?

**Comment by jywarren** [comment]
I don't think so -- if you can share your code, I can take a look, but
chat-in-iframes already works here: https://publiclab.org/chat

Hope that helps!

**Comment by ananyo2012** [comment]
@jywarren Ok I will be sharing the code soon. Other urls are working fine but https://pad.publiclab.org/ is throwing error.

**Comment by jywarren** [comment]
I wonder if it's a cross-domain issue with running on localhost, and/or
running http/https?

**Comment by ananyo2012** [comment]
@jywarren I have tested it out on the publiclab sandbox. You can see it here: https://publiclab.org/wiki/sandbox#Testing+iframe
The iframe on https://mapknitter.org/embed/sattelite-imagery works fine but not on https://pad.publiclab.org/p/test

**Comment by jywarren** [comment]
Ah, perhaps @icarito can shed some light on this - now that I think of it,
there's also often the need to enable a cross origin request header, and
Sebastian just did so for another site.

And, I'm sorry, I mixed up the chat and the etherpad -- the page I linked
to was a chat page, and not helpful.

**Comment by ananyo2012** [comment]
@jywarren You can see the code in #538

**Comment by icarito** [comment]
Yes rather than multiple headers, it appears there is no perfectly standard way to restrict iframes. 
I disabled the Xframe limitation and it works. Conceivably we could write a conditional Xframe header (on the referrer) but the referrer can be spoofed. Works now, let me know if I can help further.

**Comment by ananyo2012** [comment]
@jywarren This can be closed now

**Comment by jywarren** [comment]
If @ebarry has additional input on the wording of the header, perhaps we need one more tweak?

**Comment by ananyo2012** [comment]
@ebarry Please have a look at this so that it can e closed.

**Comment by ananyo2012** [comment]
@jywarren Can this be closed now? I see the Talk page being remodeled now with specific text.

**Comment by ebarry** [comment]
HI folks! re-opening this issue in case it helps people find the relevant code. 

Because people come in to etherpads and leave messages that no one ever reads (see example below, messages from February 2017 and May 2017), we need to update this message to say something like "these pads are here for people to collaborate on but FYI if you are trying to get in touch with public lab, please email publiclaboratory@googlegroups.com or call on in Tuesdays [details]"

<img width="1146" alt="screen shot 2017-12-18 at 12 49 25 pm" src="https://user-images.githubusercontent.com/161439/34120147-9f6b2664-e3f2-11e7-86b9-6e40da87164c.png">

cc @steviepubliclab

**Comment by ebarry** [comment]
To the existing header on etherpad:: 
>Talk page for [wiki page name] | This page allows for synchronized editing by multiple people as you type. [Learn more](https://publiclab.org/wiki/talk-pages)

I propose adding a link directly to chat so that we don't have the problem shown above for /lists

Talk page for [wiki page name] | This page allows for synchronized editing by multiple people. [Learn more](https://publiclab.org/wiki/talk-pages). If you are trying to reach someone right now, please visit [publiclab.org/chat](/chat), or call in on any Tuesday at 2pm CT / 3pm ET at +1 408 638 0968, then 415 220 636 [Learn more](https://publiclab.org/events).

@steviepubliclab @jywarren check out this wording

**Comment by jywarren** [comment]
I'd be careful w text that you may ever want to change, but we could put a
feature there so you could change it anytime w the features system?

**Comment by ebarry** [comment]
it would be great to handle this through a feature

--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net

**Comment by jywarren** [comment]
Features are implemented like this: 

https://github.com/publiclab/plots2/blob/95e517f19881d9f3d2f7101cb60494b60bee9610/app/views/sidebar/_featured.html.erb#L7-L9

We could add one to the end of this line:

https://github.com/publiclab/plots2/blob/95e517f19881d9f3d2f7101cb60494b60bee9610/app/views/talk/show.html.erb#L1

This could use reposting as a clean issue with these links and steps, and would make a good first-timers-only issue!

**Comment by gauravano** [comment]
Hey @jywarren @ebarry, do you think this one is required? If yes, I think, making new issue from it will be good. Thanks!

**Comment by jywarren** [comment]
I think we're all good here too!
