### ISSUE TITLE
@usernames are not linked when they begin a bulleted line

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1751]
### Please describe the problem

In a research note, i noticed two usernames were not linked, and so i checked and indeed they are still active accounts

### Please show us where to look

https://publiclab.org/notes/Shannon/07-06-2016/public-lab-code-of-conduct
-- scroll down into the Refinements section, where neither /@klie/ nor /@kanarinka/ are linked

### What's your PublicLab.org username?

liz

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Great catch! Can you add a sample text that's not working and someone
hopefully can write a test for it, and develop a fix?

Here's the line of code we use to find usernames starting with a @ -

https://github.com/publiclab/plots2/blob/master/config/initializers/constants.rb#L2

http://rubular.com is a great site for debugging regular expressions like
this.

**Comment by ebarry** [comment]
Ah -- left out the important observation, that this is happening after an `asterisk space` combo to make a bullet:

Sample text: 

* @kanarinka
* @klie

**Comment by SidharthBansal** [comment]
I think FINDER = /(^|\s)\@([\w-]+)/ should be replaced by FINDER = /[\u2022,\u2023,\u25E6,\u2043,\u2219]?(^|\s)\@([\w-]+)/  as bullet can be of five types 
    Bullet (•)
    Triangular Bullet (‣)
    White Bullet (◦)
    Hyphen Bullet (⁃)
    Bullet Operator (∙)
So, I have used 5 regex coding with it. 
I have made a pull request #1764

**Comment by SidharthBansal** [comment]
Sorry, I checked it but it should be /(^|\s)?@([\w-]+)/ 
This is my first time.
It is working 
![image](https://user-images.githubusercontent.com/20972099/32632938-8642e400-c5cb-11e7-9001-f870fde3a927.png)
I have made a pull request #1765. Tell me if I am wrong anywhere.

**Comment by jywarren** [comment]
Awesome! I'll be going through new submissions tomorrow morning; sorry have
been a bit behind with an event we were running! Thanks so much for your
contribution!
