### ISSUE TITLE
Chatbox should be closed when clicking outside

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plots2#1760]
When you open a chat window, you can dismiss the window by re-clicking on the button. The user should be able to dismiss the window by clicking anywhere else on the screen.

**Comment by sagarpreet-chadha** [comment]
@ryzokuken...can i work on it ?

**Comment by Gauravano** [comment]
hey @ryzokuken I like to work on this issue

**Comment by jywarren** [comment]
Hi! We'd love if either of you could jump in on this. Thanks!

**Comment by jywarren** [comment]
Solved! Thanks!!!!
