### ISSUE TITLE
subscription to tag=everything should also include Answers

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1761]
Hi everyone!
### Please describe the problem (or idea)
> What did you expect to see that you didn't?

I am subscribed to "everything" on the Public Lab website, and i've just noticed that i do not get notifications when "answers" are submitted. Can this be added to subscriptions? 

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

**Comment by sagarpreet-chadha** [comment]
@jywarren sir...can i work on it ?

**Comment by jywarren** [comment]
Yes please!!

Here's the code for notifying for new answers.

https://github.com/publiclab/plots2/blob/master/app/models/answer.rb#L36

Compare to similar code for notes in models/node.rb

In that one, "everything' followers are notified.

Thanks!!
