### ISSUE TITLE
Email address not recognised when registering 

### ISSUE THREAD

**Issue by Gabi-Enterprises** [publiclab/plots2#1770]
Hi - I'm having a problem registering my email address for a new account. 

I went to the register page - https://publiclab.org/register, filled in the information and received this error message "Email should look like an email address." I am using a .today domain name for my email address which I believe might be the problem. 

Chrome, Version 61.0.3163.100, Mac OS. Also the same result on Chromium on Ubuntu. 

Thank you! 
~Gabi

**Comment by jywarren** [comment]
Hi, Gabi! Thanks, this is really helpful. We should add a test for this and see if we can reproduce it. I'm actually having some trouble finding where we check email format, but don't worry, we'll get to the bottom of this!

**Comment by jywarren** [comment]
working on this in https://github.com/publiclab/plots2/pull/1771 !!!
