### ISSUE TITLE
Display redirected wiki page at top of /tag/____ pages if redirect exists

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1773]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### Problem

Tag pages, like https://publiclab.org/tag/h2s-copper-pipe where the tag doesn't have a corresponding wiki page prompt you to make a new page. 

But some pages just have a non-matching wiki page -- this one has for example, the matching:

https://publiclab.org/wiki/hydrogen-sulfide-copper-pipe

### Solution

So we should detect if there's a redirect tag on https://publiclab.org/wiki/h2s-copper-pipe leading to another page, and display /that/ page's lead image and first paragraph, instead of the original (which is empty). 

We can do this in the controller here:

https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L45

Basically after this line, we can see if @wiki exists, and if not, check if it has a redirect, so:

```ruby
@wiki = Node.find(@wiki.power_tag('redirect'))  if @wiki.has_powertag('redirect') # use a redirected wiki page if it exists
```

That'll check if there's a redirect tag, then if there is one, it'll assign the Node with the correct new node id to `@wiki`. Make sense? I'm happy to help here!

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by namangupta01** [comment]
can i work on it?

**Comment by jywarren** [comment]
That'd be great! Much appreciated!

**Comment by Gauravano** [comment]
Hey, @namangupta01  are you working on this issue, otherwise, I would love to take a try on this.

**Comment by jywarren** [comment]
@namangupta01 - if you have any code to start with, we're happy to take a look even if it's not done -- please open a PR and we can help troubleshoot!

**Comment by namangupta01** [comment]
@Gauravano Yes i am working on this issue! @jywarren I will open the pr soon!
