### ISSUE TITLE
add contributor_count method to Tag model

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1774]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

We need a generalized tag-based method, like `Tag.contributor_count(tagname)` for counting contributors. It'd also be great to count commenters, answerers, etc! 

### Solution

It could start with this code: https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L216-L219

It could go in the Tag model: https://github.com/publiclab/plots2/blob/master/app/models/tag.rb

Here's some code to start, but we'd want to narrow these to collect only those tagged with `tagname` -- similar to this code: https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L70-L74

But the general method would look like this: 

```ruby
def contributor_count(tagname)
  uids = Node.where(...).collect(&:uid)
  uids += Comment.where(...).collect(&:uid)
  uids += Answer.where(...).collect(&:uid)
  uids = uids.uniq
  uids.length
end
```

We'd of course want to unit test it! Unit tests for the Tag model live here: https://github.com/publiclab/plots2/tree/master/test/unit/tag_test.rb

(Follow-up issue: it could then be used to replace parts of #1028 and the code in https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L216-L219)

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by ViditChitkara** [comment]
Can I give it a go?

**Comment by jywarren** [comment]
Yes please! Thank you!

**Comment by ebarry** [comment]
Thanks @ViditChitkara ! Happy to give any support we can, we really appreciate your time thinking about this!

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by ViditChitkara** [comment]
Hi, actually I am a bit busy with my exams. I'll open a PR ASAP. Applologies for the delay!!

**Comment by jywarren** [comment]
no problem and good luck with your exams!

**Comment by ViditChitkara** [comment]
Thanks jeff, will surely do it ASAP.

**Comment by jywarren** [comment]
Solved by @ViditChitkara !!! Fantastic.

As a follow-up, do you think it's possible to write a `Tag.contributors` which would collect all the users in an array? If you're interested, we'd LOVE to see this! I think it'd be pretty similar.

**Comment by jywarren** [comment]
If we did a `Tag.contributors` we could then use it in this controller method, and show a wider range of people on that page:

https://github.com/publiclab/plots2/blob/f6fe2ea6273e30444bb2ccde131c0ae1bf6c8ea6/app/controllers/tag_controller.rb#L262-L272

**Comment by ViditChitkara** [comment]
Thanks @jywarren!! I am happy to do this but could you tell me on what basis should I select the contributors, like there are many possible ways in which a user could contribute. It would be great help if you give a little more details!Thanks😄😄

**Comment by jywarren** [comment]
Hi, I think the way you implemented the count works well here too - people who've posted nodes, comments or answers on content with the given tag. Does that make sense? 😁👍

**Comment by ViditChitkara** [comment]
Yes, it makes sense. However, I'll see if there are more ways of getting contributors which are associated with particular tag, else we could use this only!!!!😃😃

**Comment by jywarren** [comment]
Good idea... Maybe wiki page revisions by an author? Under Revision model.

**Comment by ViditChitkara** [comment]
Cool! So I'll make changes in this method only so that wiki page members are also there along with answerers, etc.!!!!😉😉

**Comment by jywarren** [comment]
Super.

**Comment by ebarry** [comment]
this is a really exciting project -- thank you for helping!

--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net

**Comment by ViditChitkara** [comment]
@ebarry surely this is exciting and I'm really happy to contribute to this. I have learnt a lot here and would keep contributing to this. Thank you and @jywarren for helping me out.
