### ISSUE TITLE
Create a Node.tagged_nodes_by_author method

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1776]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting and code pointers, could be a great entry point for a new contributor. 

If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Template draft:** (please leave additions in the comments to get this closer to a full first-timers-only issue)

Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## Problem

We need a way to select all nodes which:

1. are authored or coauthored by a given user
2. are tagged with a given string like `tagname` (for example `replication:1234`)

This can be used, for example, to list activities completed by a given user (to help in completing #928).

## Solution

The format for calling it could be, perhaps:

`Node.tagged_nodes_by_author(tagname, user_id) # nodes by user with given tag`

This method could go in the Tag model, here:

https://github.com/publiclab/plots2/blob/master/app/models/tag.rb

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by SidharthBansal** [comment]
May I take this issue?

**Comment by jywarren** [comment]
Yes please! That would be great, thank you!

**Comment by SidharthBansal** [comment]
Should the function be - 
def self.tagged_nodes_by_author(tagname, user_id)
	Node.where('term_data.name = ?', tagname)
	    .collect(&:user_id)
end
May I make a pull request?
Thanks

**Comment by jywarren** [comment]
I think you'll need: `.includes(:node_tag, :tag)` to be able to specify any attributes from the `term_data` table (which is accessed through the `tag` model in our app)

but also remember the method is named in a way that it should be expected to return nodes -- so, no need for `collect`ing the user_ids. Rather, we will need to specify another `where` filter to ensure the `node` has the specified author. So, like `.where('node.uid = ?', user_id)` -- see?

Then, all together, try:

```ruby

def self.tagged_nodes_by_author(tagname, user_id)
	Node.where('term_data.name = ?', tagname)
                .includes(:node_tag, :tag)
	        .where('node.uid = ?', user_id)
end
```

Does that make sense? Thank you for your contribution here!

**Comment by SidharthBansal** [comment]
Thanks for the advice. I  have made a pull request.
I hope this works
Thanks
