### ISSUE TITLE
Add recently used tags (by current user) to the tagging menu

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1779]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

We've wanted (in #143) to show "suggested tags" on [pages like this one](https://publiclab.org/wiki/microscope) -- in the tags input area (you have to be logged in to see it!) with a more helpful interface, and we now have a tag menu (shown below) where we could put those options:

![screenshot 2017-11-15 at 4 01 57 pm](https://user-images.githubusercontent.com/24359/32866834-7e8aaef8-ca1e-11e7-9181-f5d1ab155660.png)

## Solution

Let's add the most recently used 5 tags by the current user to the menu as suggestions.

The code for the menu items shown above is here:

https://github.com/publiclab/plots2/blob/master/app/views/tag/_advanced_tagging.html.erb#L3-L6

I think we could use a "header" `<li>` as in the [Bootstrap UI](https://getbootstrap.com/docs/3.3/components/#dropdowns) library to say `Recently used tags`:

```html
  <li class="dropdown-header">Recently used tags</li>
```

Then below that, use a query to fetch the past 5 tags by the current user, so:

```ruby
<% Tag.joins(:node_tag).where(uid: current_user.id).order('date DESC').limit(5).each do |tag| %>
  <li onClick="addTag('<%= tag.name %>')"><i><%= tag.name %></i></li>
<% end %>
```

(I *think* that'll work!!) 

You may have to check that `<% if current_user %>` to ensure it only runs for logged-in users!

Hopefully this is pretty straightforward! We're happy to help if you have trouble. Thanks!

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by bentonwong** [comment]
Hi, is this issue still open to be claimed? If so, I would like to claim it and work on it.

**Comment by jywarren** [comment]
Oh, yes please, that would be great and we're happy to help!

**Comment by bentonwong** [comment]
Awesome. I will take a crack at it!

**Comment by bentonwong** [comment]
Using the suggested query above as is throws an error: "ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: term_data.uid". 

I tried querying NodeTags and it produced some better results:
```
<% NodeTag.where(uid: current_user.id).order('date DESC').limit(5).each do |tag| %>
      <li onClick="addTag('<%= tag.name %>')"><i><%= tag.name %></i></li>
    <% end %>
```

Would this be a correct application or does the query still need to be joined with the Tag table?

**Comment by jywarren** [comment]
Aha, cool! Very nicely done. NodeTag actually has a helper for `.name` which makes this work, so and your code is much cleaner as a result! Great work! The join is then unnecessary!

**Comment by bentonwong** [comment]
Thanks. I implemented the changes.  However, when doing the final rake test:all, I am getting a bunch of errors, such as:

Error: test_should_get_dynamic(SearchesControllerTest): RSolr::Error::ConnectionRefused: Connection refused - {:da
ta=>"{\"delete\":[\"User 7\"]}", :headers=>{"Content-Type"=>"application/json"}, :method=>:post, :params=>{:wt=>:j
son}, :query=>"wt=json", :path=>"update", :uri=>#<URI::HTTP http://solr:8983/solr/default/update?wt=json>}
lib/authlogic_openid/authlogic_openid/acts_as_authentic.rb:74:in `save'
lib/authlogic_openid/authlogic_openid/session.rb:73:in `save'
test/solr/searches_controller_test.rb:9:in `setup'

Error: test_should_get_dynamic(SearchesControllerTest): RSolr::Error::ConnectionRefused: Connection refused - {:da
ta=>"{\"delete\":[\"User 7\"]}", :headers=>{"Content-Type"=>"application/json"}, :method=>:post, :params=>{:wt=>:j
son}, :query=>"wt=json", :path=>"update", :uri=>#<URI::HTTP http://solr:8983/solr/default/update?wt=json>}
lib/authlogic_openid/authlogic_openid/acts_as_authentic.rb:74:in `save'
test/solr/searches_controller_test.rb:13:in `teardown'

Error: test_should_get_results(SearchesControllerTest): ActiveRecord::StatementInvalid: SQLite3::SQLException: can
not start a transaction within a transaction: begin transaction

Error: test_should_get_results(SearchesControllerTest): RSolr::Error::ConnectionRefused: Connection refused - {:da
ta=>"{\"delete\":[\"User 7\"]}", :headers=>{"Content-Type"=>"application/json"}, :method=>:post, :params=>{:wt=>:j
son}, :query=>"wt=json", :path=>"update", :uri=>#<URI::HTTP http://solr:8983/solr/default/update?wt=json>}
lib/authlogic_openid/authlogic_openid/acts_as_authentic.rb:74:in `save'
test/solr/searches_controller_test.rb:13:in `teardown'

Failure:
  <true> expected but was
  <false>
test_running_TypeaheadService.notes(TypeaheadServiceTest)
test/solr/typeahead_service_test.rb:18:in `block in <class:TypeaheadServiceTest>'
==================================================================================================================
F
==================================================================================================================

Failure:
  <true> expected but was
  <false>
test_running_TypeaheadService.search_all(TypeaheadServiceTest)
test/solr/typeahead_service_test.rb:8:in `block in <class:TypeaheadServiceTest>'
==================================================================================================================


Finished in 0.844775 seconds.
------------------------------------------------------------------------------------------------------------------
7 tests, 2 assertions, 2 failures, 8 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
------------------------------------------------------------------------------------------------------------------
8.29 tests/s, 2.37 assertions/s
rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/Users/bentonwong/.rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib"
 "/Users/bentonwong/.rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/solr/*_test.rb" ]
/Users/bentonwong/Development/open-source/plots2/lib/tasks/test.rake:39:in `block (2 levels) in <top (required)>'
/Users/bentonwong/Development/open-source/plots2/lib/tasks/test.rake:14:in `block (2 levels) in <top (required)>'
/Users/bentonwong/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/bentonwong/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test:solr_tests
(See full trace by running task with --trace)

Many of the errors appear unrelated to the code I just implemented.

Do you have any thoughts on addressing these issues or should I just ignore them and continue with a pull request?

**Comment by jywarren** [comment]
Hi, no worries, please open a pull request and we can take a look! To get
past these errors you can set disabled = true in config/sunspot.yml, which
we fixed in a recent change. Sorry it gave you trouble!

On Nov 20, 2017 8:16 PM, "Benton Wong" <notifications@github.com> wrote:

Thanks. I implemented the changes. However, when doing the final rake
test:all, I am getting a bunch of errors, such as:

Error: test_should_get_dynamic(SearchesControllerTest):
RSolr::Error::ConnectionRefused:
Connection refused - {:da
ta=>"{"delete":["User 7"]}", :headers=>{"Content-Type"=>"application/json"},
:method=>:post, :params=>{:wt=>:j
son}, :query=>"wt=json", :path=>"update", :uri=>#<URI::HTTP
http://solr:8983/solr/default/update?wt=json>}
lib/authlogic_openid/authlogic_openid/acts_as_authentic.rb:74:in save'
lib/authlogic_openid/authlogic_openid/session.rb:73:insave'
test/solr/searches_controller_test.rb:9:in `setup'

Error: test_should_get_dynamic(SearchesControllerTest):
RSolr::Error::ConnectionRefused:
Connection refused - {:da
ta=>"{"delete":["User 7"]}", :headers=>{"Content-Type"=>"application/json"},
:method=>:post, :params=>{:wt=>:j
son}, :query=>"wt=json", :path=>"update", :uri=>#<URI::HTTP
http://solr:8983/solr/default/update?wt=json>}
lib/authlogic_openid/authlogic_openid/acts_as_authentic.rb:74:in save'
test/solr/searches_controller_test.rb:13:inteardown'

Error: test_should_get_results(SearchesControllerTest):
ActiveRecord::StatementInvalid:
SQLite3::SQLException: can
not start a transaction within a transaction: begin transaction

Error: test_should_get_results(SearchesControllerTest):
RSolr::Error::ConnectionRefused:
Connection refused - {:da
ta=>"{"delete":["User 7"]}", :headers=>{"Content-Type"=>"application/json"},
:method=>:post, :params=>{:wt=>:j
son}, :query=>"wt=json", :path=>"update", :uri=>#<URI::HTTP
http://solr:8983/solr/default/update?wt=json>}
lib/authlogic_openid/authlogic_openid/acts_as_authentic.rb:74:in save'
test/solr/searches_controller_test.rb:13:inteardown'
Failure:
expected but was

test_running_TypeaheadService.notes(TypeaheadServiceTest)
test/solr/typeahead_service_test.rb:18:in `block in
class:TypeaheadServiceTest' F Failure:
expected but was

test_running_TypeaheadService.search_all(TypeaheadServiceTest)
test/solr/typeahead_service_test.rb:8:in `block in
class:TypeaheadServiceTest' Finished in 0.844775 seconds. 7 tests, 2
assertions, 2 failures, 8 errors, 0 pendings, 0 omissions, 0 notifications
0% passed

8.29 tests/s, 2.37 assertions/s
rake aborted!
Command failed with status (1): [ruby -I"lib:test"
-I"/Users/bentonwong/.rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib"
"/Users/bentonwong/.rvm/gems/ruby-2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb"
"test/solr/*_test.rb" ]
/Users/bentonwong/Development/open-source/plots2/lib/tasks/test.rake:39:in
block
(2 levels) in <top (required)>' /Users/bentonwong/Development/
open-source/plots2/lib/tasks/test.rake:14:inblock (2 levels) in <top
(required)>'
/Users/bentonwong/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in eval'
/Users/bentonwong/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in
'
Tasks: TOP => test:solr_tests
(See full trace by running task with --trace)

Many of the errors appear unrelated to the code I just implemented.

Do you have any thoughts on addressing these issues or should I just ignore
them and continue with a pull request?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/1779#issuecomment-345884579>,
or mute the thread
