### ISSUE TITLE
Links in mailers are not active 

### ISSUE THREAD

**Issue by Gauravano** [publiclab/plots2#1780]
Hey, @jywarren @ebarry  while I was working on notify_author_question #1763. I found out that many links in different mailers are not active.For example : 

Notify Answer Likers
![notify_likers](https://user-images.githubusercontent.com/20878070/32907617-a31de6dc-cb26-11e7-9e46-1c130ea0f75b.png)
 
Notify Answer Accept 
![issue3](https://user-images.githubusercontent.com/20878070/32907679-e4944c1e-cb26-11e7-90ae-8bb6a1de22e5.png)

And there are few more views where links are not working.In some of them its also written to click on the link to see the answer or comment but functionality is not there.I can fix all these easily .Should I continue @jywarren sir?

**Comment by jywarren** [comment]
I believe that most email clients will actually render those links
actively, and that we had hesitated to make <a href=''> style links for any
email clients that don't render HTML.

Thanks! The other fixes would be great!

**Comment by Gauravano** [comment]
@jywarren actually all fixes are just to add <a href=""> tag addition only. So what you say should we add <a> tags to all present links or leave them as it is.

**Comment by jywarren** [comment]
Hi, I guess I think we may not have to -- have you signed up for emails on PublicLab.org and checked if any of these are not made into URLs? If that is an issue, I'd be happy to accept a PR -- but it may be worth checking first!

**Comment by Gauravano** [comment]
As for now I have checked only in development by sending SMTP emails but haven't checked closely on PublicLab.org emails so I will check some emails there too and then update you on this issue, sir.

**Comment by Gauravano** [comment]
Hi @jywarren sir, you are right regarding this issue that most email clients do render those links and after observing some emails from PublicLab.org it's confirmed.So, I am closing this issue.

**Comment by jywarren** [comment]
OK, thanks for looking into it and for your attention to these important
details!
