### ISSUE TITLE
Feature request: Spam author banned, but their comment was not removed

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1785]
### Please describe the problem (or idea)

I noticed comment spam on this post: https://publiclab.org/questions/plam/03-31-2017/infragrammer-webgl-hsv-vs-standard-equations#a561

<img width="721" alt="screen shot 2017-11-17 at 1 04 08 pm" src="https://user-images.githubusercontent.com/161439/32961799-f899ff62-cb97-11e7-9d2b-b1a355e499e1.png">

And so, as a site moderator, i went to that profile https://publiclab.org/profile/maisieacton10 and banned it. 

> What did you expect to see that you didn't?

The alert text when i clicked "ban" on the profile said that banning the author would remove all their content from the site -- but it did not. This is a bug. 

Thanks for looking into this!

**Comment by Diksha2008** [comment]
I would like to resolve this!

**Comment by jywarren** [comment]
This is a feature request - we haven't yet designed a system to moderate
comments or answers, because we don't yet have a "status" field for these.
Right now, comment deletion is manual.

This is important because banning a user should not delete their comments
-- that would be irrevocable.

We could model a "status" system on the node.status system in
/app/models/node.rb so that banning a user changes all their comments to
"status = 0" instead of deleting them.

But we will have to ensure that anywhere comments are displayed (dashboard
activity feed, questions pages, notes pages, wiki pages, anywhere else) we
filter comments for "status == 1"

And we'll have to add the comment status column with a default of 1, so
that all current comments are "published"

Later, we could design an additional system so that new posters' comments
are moderated as initially status = 2 (maybe?), and require approval as
with nodes.

Thanks, Liz! Hope these steps help break down this request!

**Comment by ankitbhardwaj78** [comment]
@jywarren can i work on this issue??

**Comment by jywarren** [comment]
Hi, I think this is a big set of features which we should break into smaller parts. Perhaps we could start by highlighting the poster's comments when you do ban them -- opening the profile page to the comments section? See https://publiclab.org/profile/warren

Currently there's not a way to open directly to the comments section. That's a good self-contained issue. Then a follow-up one could be, perhaps, to create a controller method to delete all comments by a user, accessible only to moderators? This would have to be used very very carefully... with an "are you sure" prompt for sure.

**Comment by jywarren** [comment]
Via #428 -- steps for creating a comment moderation system might include:
 
- [ ] add `comment.status` column
- [ ] mark all banned users' comments as `status = 0` to unpublish (in a migration [like this one](https://github.com/publiclab/plots2/blob/master/db/migrate/20170726174757_recover_bios_tokens_statuses.rb))
- [ ] add buttons to comments, visible to mods and admins, for spamming and unspamming comments, like these: https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_node_moderate.html.erb#L3-L9
- [ ] add `where(status: 1)` to all comment displays, especially this line:

https://github.com/publiclab/plots2/blob/3702e83c8f50c86ab6d6a197579990d334a12d90/app/views/notes/_comments.html.erb#L8

**Comment by Diksha2008** [comment]
@jywarren I would like to work on this!

**Comment by jywarren** [comment]
Hi, @Diksha2008 that'd be great -- i think we need to start by planning this one out -- it's a big system. let me check with @ebarry and @steviepubliclab about whether we want to prioritize this project now or to ask folks to hold off for a bit. Thanks!!

**Comment by jywarren** [comment]
i'd like to start with a subset here -- let's:

* [ ] make a "status" column for comments, default `1`, spam = `2`
* [ ] make a "spam" method like this, that only moderators or admins can use (`user.role == admin`): https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L158
* [ ] a "publish" method which sets `status` back to 1
* [ ] unit test the above 2 methods
* [ ] display comments (on dashboard, /research, in answers, wiki pages and notes) only if they have `status == 1`
* [ ] display spammed comments to admins and moderators (`user.role == admin || user.role...`) but with text hidden, with a notice "A comment by @______ was put in moderation. _Read the full comment_" which displays the text, and a "republish" button

This is a lot already! And we wouldn't even have gotten to preventing first-time posters from commenting unless approved. So let's start here and then we can build this out further once we have some of these basic systems in place!

Thanks, all!

**Comment by Gauravano** [comment]
Hi @Diksha2008 @jywarren , I want to help in resolving this issue

**Comment by Diksha2008** [comment]
@Gauravano sure! Lets work on this together!

**Comment by Gauravano** [comment]
So @Diksha2008, How about I can work on first 2 parts and then you next 2 and so on something like this? So you wanna start with first 2 or should I?

**Comment by Gauravano** [comment]
Opened in #2304

**Comment by Diksha2008** [comment]
@Gauravano sorry for the late reply
Sure we can work that way!

**Comment by Gauravano** [comment]
Great
