### ISSUE TITLE
Emails received even if not answered to node 

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#1788]
### Please describe the problem (or idea)

I have got around 6 emails from PublicLab  .

<img width="1223" alt="screen shot 2017-11-18 at 11 27 06 am" src="https://user-images.githubusercontent.com/14952645/32977472-e79bf0dc-cc53-11e7-933d-7a2b107f0b33.png">

However i have no subscriptions from my account and also not given any answers to any node .
The emails states that i have given answer as shown : 

<img width="1231" alt="screen shot 2017-11-18 at 11 27 20 am" src="https://user-images.githubusercontent.com/14952645/32977482-3566404c-cc54-11e7-8814-b4a7d532b7fc.png">

### What's your PublicLab.org username?

sagarpreet 

Registered email : sagarpreet_bt2k15@dtu.ac.in

**Comment by sagarpreet-chadha** [comment]
And again .
<img width="1234" alt="screen shot 2017-11-20 at 10 22 02 am" src="https://user-images.githubusercontent.com/14952645/33002850-bf748904-cddc-11e7-9496-0b7d40bbd143.png">

**Comment by sagarpreet-chadha** [comment]
I think it is due to the fact that in this model function **self.follower()** , we should be checking that **following = true** . 
https://github.com/publiclab/plots2/blob/7d4c04a788fff9340a87d8109eec2f2a2d343ad0/app/models/tag.rb#L134
I think i was following 'everything' tag earlier and the database still contains my **user-id** with following = false . What do you think @jywarren sir ?
Thank You .

**Comment by jywarren** [comment]
yes! so, you had subscribed but then later unsubscribed? Indeed we should check `following == true`! Good catch.

**Comment by jywarren** [comment]
@steviepubliclab this may also be related to your issue! @sagarpreet-chadha found another aspect of this we may have overlooked!

**Comment by sagarpreet-chadha** [comment]
Yes @jywarren sir...i had earlier subscribed and then unsubscribed .
Thanks so much !
