### ISSUE TITLE
Create admin tag page

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#179]
display tags by post frequency, with search by alphabetical order (like "show all tags that begin with A"). Have a sort function button up top. Because there are so many tags to display, begin by listing only the top 25-50 tags, and have a link to "see more".

**Comment by ebarry** [comment]
* /tags page should mention subscribing to tags via RSS at the top of the page
* There should also be a place to view a list of all powertags, not necessarily restricted to admins

**Comment by ebarry** [comment]
sorting of tags by name and by use count -- and for admins, bulk editing of tags (especially to delete offensive spam) -- is still needed.

**Comment by ebarry** [comment]
Also see:
https://github.com/publiclab/plots2/issues/480

**Comment by ebarry** [comment]
Also see: https://github.com/publiclab/plots2/issues/480 which calls for a new page /topics because this page is so poor.

**Comment by ebarry** [comment]
I'm also interested in seeing who is subscribed to tags, for instance, there's an icon indicating that 79 people are subscribed to "everything" generated on publiclab.org, and as part of the community development team, i would like to be able to reach out to these folks. Can this icon be activated?

![screen shot 2017-05-31 at 11 37 23 am](https://cloud.githubusercontent.com/assets/161439/26640506/e9e08202-45f5-11e7-954a-d27cdacac1c7.png)

**Comment by jywarren** [comment]
Hi, Liz, can you break this out into a separate issue? We'd be happy to
help you find the relevant lines of code and mark it a `help-wanted` or
figure out if it could be a FTO issue.

**Comment by ebarry** [comment]
ok awesome progress! I'd like to use this issue to keep planning out how to improve /tags, and then we can break out separate issues from this. 

Generally, i guess it's worth saying that continued improvement on /tags is important because as Google Groups becomes less and less viable as a platform for hosting discussions, we will be directing people to subscribe to tags/topics on the website they're interested in. 



Some ideas, what do you think?

* Consider removing powertags from the main list on /tags OR providing a way to navigate directly to a powertag only view, perhaps at publiclab.org/powertags which could both explain what they are and let people browse them. 
  * One thing ComDev requested almost 3 years ago was that power tags would be shown in the tag list. I repent from having ever asked that because over the intervening years powertags are handling large portions of the website, for instance all activities are `activity:XXXX` and all questions are `question:XXXX`. Having all the power tags in the main list of tags reduces the utility of that list!
* choose a set of tags that's the same as our googlegroups and put them as "suggested subscriptions" at the top of /tags
* add clickable letters like `a` `b` `c` to the top of /tags so that people can navigate to the letter they want to find the tag they want
* create a search just for tags that autocompletes only with tags to help people subscribe
* show tag clusters to help people see how people describe topics in order to help more people subscribe (these tag clusters would only have to be occasionally generated, like once a week). 
* others?

Let's use the note to

**Comment by jywarren** [comment]
FWIW, the explanation page for power tags is at https://publiclab.org/w/power-tags -- so we could excerpt or link there from a potential /powertags page.

Which tag list are you referring to that ComDev requested -- the one for each page? Or the overall list at /tags?

Manually choosing a subset of "featured tags" seems like something we could/should do in content, not code. If you have the list of tags, we can make a Feature out of it and display that -- like how we do banners. (this helps us keep the code generalizable so it may be used by non-Public Lab groups in the future, it also makes it easier to change the list of chosen tags without rebooting the server)

the a,b,c,d letters could be done with a block like `"abcdefghijklmnopqrstuvwxyz".split('').each do |letter|` -- would we do numbers too? 

Search just for tags could be done via the API -- https://github.com/publiclab/plots2/blob/master/doc/API.md - like https://publiclab.org/api/srch/tags?srchString=balloon

**Show tag clusters** is still kind of an issue with performance. Even if they're generated once per week, we'd have to think about how long it might take down the server. For example we run big backups on Sunday mornings ET and this impacts site performance and load time, but we schedule it at a relatively convenient time. If we could develop a plan to calculate out this list and have it auto-post from a script running off-site, maybe is one way forward. 

I think we need to do some deep planning on this last one. 

Actually i think it could be great to close out this issue and start a new one with the new break-me-up list!

**Comment by biswesh456** [comment]
Can I do any contribution regarding this issue? Or is it being done by others?

**Comment by ebarry** [comment]
hi @biswesh456 ! Thank you for writing in! I just spent some time cleaning up in this issue to figure out what's left. 

The only outstanding part of this issue is that powertags are listed in the main tag view. That's mostly fine except when you get to `activity:____` or `question:____` which is essentially a relisting of all tags are big enough topics that people are writing activities and questions on the topic. 

Topics i see this as a problem for (will be expanded, i'm sure): 
`activity:____`
`question:____`
`lat:____`
`lng:____`

I don't know exactly how to approach this so @biswesh456 it might be more pleasant of an experience if perhaps in the meantime while we go back and forth here, you go and find another interesting issue to loop into?

**Comment by biswesh456** [comment]
Thank you for your reply @ebarry. I would do as you have suggested.

**Comment by jywarren** [comment]
Would we be okay with not listing powertags on the tag index page at all? Would we lose some key information if we did that? 

If not, i.e. if that sounds ok, we can just exclude any tag that includes ":" from the tag index page query. Very easy change we can make a first timers issue for! Thanks!

**Comment by gauravano** [comment]
Hey @ebarry @jywarren, so should we exclude power tags or not? Thanks!

**Comment by ebarry** [comment]
Hi Guarav, I would say that yes we can exclude power tags from the tag index page. Could we also create an admin view that includes power tags (basically equal to what exists currently)?

**Comment by gauravano** [comment]
yes, we can do this. Thanks for updating on this one @ebarry.   Also, you mean power tags should be visible to admins and moderators both?

**Comment by gauravano** [comment]
I reopened this issue at https://github.com/publiclab/plots2/issues/5258. Closing this now. Thanks!
