### ISSUE TITLE
Refactoring coauthored notes query into a method in User.rb 

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#1793]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/). This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

📋 Step by Step

- [ ]  🙋 Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
- [ ]  📝 Update the file [https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_node_meta.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_node_meta.html.erb) in the plots2 repository (press the little pen Icon) and edit the line as shown below. [See this page](https://github.com/publiclab/plots2/projects/2) for some help in taking your first steps!
- [ ]   💾 Commit your changes
- [ ]  🔀 Start a Pull Request. There are two ways how you can start a pull request:

### PROBLEM :

We need to Refactor the Coauthored notes query (soon to be used on profile pages [like this](https://publiclab.org/profile/warren) to display posts an author has assisted with) into a method in the `User.rb` model (`/app/models/user.rb`) and to write a Unit test for it (in `/test/unit/user_test.rb`).

### SOLUTION :

The query is given here :
https://github.com/publiclab/plots2/blob/de29744270e6ea518e6c69bb47827b51125e6fc7/app/controllers/users_controller.rb#L111

The above query should be moved into the `user.rb` model as :  

```ruby
def coauthored_notes
    # the query goes here 
end
```

And the test for the above query goes here -- you can see other examples of tests in this file too: 
[test/unit/user_test.rb](https://github.com/publiclab/plots2/blob/master/test/unit/user_test.rb)

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hi, awesome! I made some small tweaks to formatting and added some links directly to the code in places.

**Comment by zhirschtritt** [comment]
I'd like to take this on!

**Comment by jywarren** [comment]
:-) yes please!!!! Is that Zach!??! Hello!

**Comment by zhirschtritt** [comment]
This is he!
