### ISSUE TITLE
Unanswered questions listing is sorted incorrectly

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1795]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

> What happened just before the problem occurred? Or what problem could this idea solve?

Unanswered questions are sorted weirdly -- roughly reverse chronological! 

https://publiclab.org/questions/unanswered/

I think we could change the `order` in this clause:

https://github.com/publiclab/plots2/blob/master/app/controllers/questions_controller.rb#L82

Let's sort by question posting date, descending! (`DESC`)

**Comment by SidharthBansal** [comment]
May I take this issue?

**Comment by jywarren** [comment]
That'd be super. Thank you!!

**Comment by SidharthBansal** [comment]
I have added pull request #1800 
Thanks
