### ISSUE TITLE
Add "Want to get updates for new blog posts? Click here to subscribe" notice to publiclab.org/blog

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1797]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem
The "subscribe" button is a bit under-emphasized on https://publiclab.org/blog -- 

![image](https://user-images.githubusercontent.com/24359/33143903-527d35b8-cf89-11e7-99fd-993f1988e31f.png)

Let's use a Bootstrap "alert" -- in green -- to welcome people who:

1. aren't subscribed
2. are logged in

If they aren't logged in, let's prompt them to log in (linking to `/login?return_to=/blog`), then to subscribe.

## Solution

There's similar code here for the existing button, checking if you're logged in and then if you're subscribed. Let's copy it (leaving the existing button) and have 3 scenarios -- not logged in, logged in but not subscribed, or subscribed (in which case we show nothing).

https://github.com/publiclab/plots2/blob/8e6ec5a29a7ebb4c873cf5b953468addc1df6547/app/views/tag/blog.html.erb#L21-L25

Bootstrap alerts are formatted like this: https://getbootstrap.com/docs/3.3/components/#alerts

This text would be great:

> `Want to get updates for new blog posts? <a href="">Click here to subscribe</a>`

We can copy and modify the button code so the "Click here..." appears as a button. 

The whole thing could go just below this line:

https://github.com/publiclab/plots2/blob/8e6ec5a29a7ebb4c873cf5b953468addc1df6547/app/views/tag/blog.html.erb#L14

Thanks! Happy to help with these steps!

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by acioffi21** [comment]
Hello! I would like to claim this. Thank you!

**Comment by jywarren** [comment]
Yes please! We'd love to have your help.

**Comment by acioffi21** [comment]
Hi,
So I'm having a little trouble, kind of a dumb mistake. I accidentally cloned the actual repository instead of my fork to my Cloud9 Workspace, so I'm not really sure how to execute the pull request that way

**Comment by jywarren** [comment]
Hmm, well you should be able to push to your own fork with `git push
https://github.com/_your_username_/plots2 branch_name` -- hope that helps!

**Comment by Xavier-J-Ortiz** [comment]
@jywarren Hello! I'd like to work on this if there's any work left to be done!

Thanks!

**Comment by jywarren** [comment]
Oh, sorry for the slow reply on this. It looks like @acioffi21 has some work on this here: https://github.com/publiclab/plots2/pull/1810 and we were just waiting to see a final screenshot before merging. If you can download their code and upload a screenshot on that PR, that'd be really helpful so we can just do a final check before merging this in!

Thank you!

**Comment by jywarren** [comment]
Solved in #1810, thanks!!!
