### ISSUE TITLE
Planning issue to improve automated tweets sent by publiclab.org

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1802]
### Please describe the problem (or idea)

Currently, our website sends automated tweets for each new note that someone "stars". 
This is good, but could be better. Let's discuss here. 

For example, a research note such as, https://publiclab.org/notes/joaquinx/11-25-2017/solar-ballon-flight-trajectory-visualization ...

<img width="865" alt="screen shot 2017-11-27 at 10 37 54 am" src="https://user-images.githubusercontent.com/161439/33274765-0c1edf5c-d35f-11e7-9908-cce6958dc959.png">

...once it is "starred," the automated tweet our site (plus IFTTT, i think) sends looks like:
<img width="596" alt="screen shot 2017-11-27 at 10 38 29 am" src="https://user-images.githubusercontent.com/161439/33274807-22d42086-d35f-11e7-8e15-4af5b2e67143.png">

**Problem**: the photo is not included in the tweet, and the username is the publiclab.org username that's unconnected to any possibly existing twitter username for that person. 

> Here are the features that would make our automated tweets better: 

* Add twitter handle to your publiclab.org profile via a powertag, `twitter:@xxxxxxxx`
* Take photo from the note and add it to the tweet

Also needed is a profile page redesign to make space for -- and sense of -- all these new features.

### What's your PublicLab.org username?

Liz

**Comment by jywarren** [comment]
Adding a few items here; 

* [ ] modify RSS feed that IFTTT.com uses to switch to Twitter handles `IF they exist AND there's a ?twitter=true` in the URL (that way we can use the same template for different platforms if needed) -- I think that code is here: https://github.com/publiclab/plots2/blob/master/app/views/notes/rss.rss.builder
* [ ] some better-designed input form for entering twitter handles and the like on your profile
* [ ] a way to display twitter (and other) social media platforms on your profile IF the profile power tags exist

The photo thing may actually not be possible via IFTTT right now -- they seem to have changed things and Twitter disallowed something...? but maybe fixed -- clue here: https://ifttt.com/applets/103249p-tweet-your-instagrams-as-native-photos-on-twitter

**Comment by sagarpreet-chadha** [comment]
@jywarren sir...can i work on it .

For images i think our rss format is not right .
<img width="916" alt="screen shot 2017-11-29 at 4 40 36 pm" src="https://user-images.githubusercontent.com/14952645/33372487-3beabc08-d524-11e7-9b16-516bbdf07e29.png">
source: http://www.landofcode.com/rss-reference/image-tag.php

Our xml structure is currently : 
We may have to add link , title and url sub tags .

<img width="1026" alt="screen shot 2017-11-29 at 4 41 14 pm" src="https://user-images.githubusercontent.com/14952645/33372540-65f5f76a-d524-11e7-8538-246b7f773280.png">

What do you think ?

**Comment by sagarpreet-chadha** [comment]
I was thinking of displaying the twitter (and other) social media platforms links if the power tag twitter:______ exists like this  :  

<img width="1440" alt="screen shot 2017-11-29 at 5 36 08 pm" src="https://user-images.githubusercontent.com/14952645/33374445-3ec90c7e-d52c-11e7-9e37-e15d46684376.png">

OR like this :  

<img width="1234" alt="screen shot 2017-11-29 at 6 04 32 pm" src="https://user-images.githubusercontent.com/14952645/33375418-d9faeeda-d52f-11e7-81cc-b492164885c4.png">

What do you think ?

**Comment by jywarren** [comment]
Looks good!

**Comment by sagarpreet-chadha** [comment]
Thank you @jywarren sir ! 
So i should continue with which design ?

**Comment by jywarren** [comment]
Sorry, was trying to get input from other team members but I think if you could move ahead with the second design, using Fontawesome icons (which we have installed) that'll be great! Thank you!

http://fontawesome.io/

**Comment by jywarren** [comment]
Solved adding to profile pages in #1816!

**Comment by jywarren** [comment]
Ah - let's also add Instagram -- based on the changes here, it should be pretty straightforward -- even a first-timers-only issue?

https://github.com/publiclab/plots2/pull/1816

**Comment by ebarry** [comment]
Is this issue still the right place to be working on other aspects of this, such as grabbing the lead image (if exists) and using that as an image in twitter? thanks for any advice!

**Comment by jywarren** [comment]
Yes, i think we can indicate which we've checked off the list (profile tagging, instagram) and note the remaining broken-out issues, such as getting lead image fixed and creating a UI for inputting social media handles (which i broke out into https://github.com/publiclab/plots2/issues/1933) -- if we can get the lead description of the issue a bit more organized into a list like this then I can keep helping break out the sub-parts and get them in the queue. Thanks!

**Comment by jywarren** [comment]
Also, @sagarpreet-chadha -- i wonder if we could test this out by pointing an IFTTT.com RSS recipe at a Github Gist of a static RSS feed with the correct `<image>` node properties as you suggest [above](https://github.com/publiclab/plots2/issues/1802#issuecomment-347830345). Then see if it can pick out the image from that -- in a test tweet! Then we could create a FTO for the rss builder template changes once we know that'll fix it.

**Comment by sagarpreet-chadha** [comment]
Okay @jywarren ...working on it .

**Comment by sagarpreet-chadha** [comment]
@jywarren , the above proposed solution did not worked . However changing various tags in rss i was able to produce images in tweets .

I used the **IFTTT recipe**  : [https://ifttt.com/applets/66362400d-rss-feed-to-post-a-tweet-with-image-and-url](https://ifttt.com/applets/66362400d-rss-feed-to-post-a-tweet-with-image-and-url)
and 
link to changed xml format is : [https://github.com/sagarpreet-chadha/sagarpreet-chadha.github.io/blob/master/feed.rss](https://github.com/sagarpreet-chadha/sagarpreet-chadha.github.io/blob/master/feed.rss)
and RSS Validator : [https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fsagarpreet-chadha.github.io%2Ffeed.rss](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fsagarpreet-chadha.github.io%2Ffeed.rss)

<img width="594" alt="screen shot 2018-01-11 at 2 32 01 am" src="https://user-images.githubusercontent.com/14952645/34795905-dc37dbde-f679-11e7-9295-782b46c33718.png">

should i open a FTO for same ?

**Comment by sagarpreet-chadha** [comment]
Moreover , the **email id** and **description/content** are also shown in tweets now (in above pic) . Also instead of email-id we can give link to twitter profile of user (not tried though :P) .

**Comment by jywarren** [comment]
That'd be great! Thank you so much!

On Jan 10, 2018 4:27 PM, "Sagarpreet Chadha" <notifications@github.com>
wrote:

Moreover , the *email id* and *description/content* are also shown in
tweets now (in above pic) . Also instead of email-id we can give link to
twitter profile of user (not tried though :P) .

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/1802#issuecomment-356742153>,
or mute the thread

**Comment by sagarpreet-chadha** [comment]
I have created FTO issue #1958 , although i think it is a little complicated for first timers .

**Comment by jywarren** [comment]
Great. I'll take a look and add tags!

On Thu, Jan 11, 2018 at 8:26 AM, Sagarpreet Chadha <notifications@github.com

**Comment by jywarren** [comment]
Closing this as #1958 is solved... pending final tests but all looks in order! Thanks all!
