### ISSUE TITLE
Dropdown menu not working in /post 

### ISSUE THREAD

**Issue by rishabhptr** [publiclab/plots2#1804]
**Please describe the problem (or idea)**

After clicking the share button from dashboard(after login) it redirects to https://publiclab.org/post where the dropdowns in navbar does'nt seem to work.
It is also not working in development.

![screenshot from 2017-11-28 21-18-12](https://user-images.githubusercontent.com/26951824/33329511-ba9a187a-d482-11e7-80b6-cebf46394d71.png)

**Please show us where to look**

https://publiclab.org/post

**What's your PublicLab.org username?**
rishabhptr

**Browser, version, and operating system**
Tried on Chrome/Mozilla

****

**Comment by jywarren** [comment]
Hi, this is waiting on this PR to be resolved, any help appreciated over
there: https://github.com/publiclab/plots2/pull/1663

It's actually related to an upstream library change, which is still
unresolved. Any help with that much appreciated!
https://github.com/publiclab/PublicLab.Editor/pull/110

**Comment by rishabhptr** [comment]
Alright! :+1:
