### ISSUE TITLE
Edits not shown on questions until after a page refresh

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#1807]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

### Please describe the problem (or idea)
I was editing an answer to a question I had posted yesterday (editing the answer itself), but noticed that when I hit publish, my edit was not captured. I tried it a few times and still couldn't get it to register my changes. However, when I:
- hit "edit" 
- then made my changes 
- pressed "preview"
- then pressed "publish" 
my edits on the answer were captured.

I think the edit function that does not publishing the fix is a bug. Can someone help me sort that out? (non coder here) 

Here's the question I was working on: https://publiclab.org/questions/stevie/11-28-2017/how-do-you-build-a-rain-barrel

**Comment by jywarren** [comment]
Hm, sorry, but do you think you could try the first process one more time,
but refresh the entire page first, then again after pressing publish? I
think this is related to the ability to edit and save without refreshing
the whole page, which is nice feature, but this test can help tell us if
that's the case. Thank you!

**Comment by steviepubliclab** [comment]
Hi there,
Sure. I was able to see the changes when I refreshed the page itself. Then I tried to edit it again (just put "test"at the end and hit publish). That time the page refreshed itself when I hit "accept" and I could see the edit. I hit edit one more time and deleted the word test but that time the page did not show that it accepted my edit when it refreshed itself, but when I hit refresh, it did appear changed.  I've done this a couple times with the same result.

**Comment by jywarren** [comment]
OK, awesome, this is super helpful. I think we're either:

1. seeing the browser cache the page and not refresh it until the whole
page is refreshed (browsers are getting more aggressive about caching these
days)
2. seeing a failure in the script that's supposed to update the page
/without/ needing a full-page refresh. That's here:

https://github.com/publiclab/plots2/blob/master/app/views/questions/_answer.html.erb#L75

Using the `data-remote=true` feature of Rails.js, I believe. More detail
needed here to make it easier to fix, but:
http://guides.rubyonrails.org/working_with_javascript_in_rails.html#remote-elements

**Comment by jywarren** [comment]
Actually, I'm having trouble finding anywhere that the new answer text is supposed to update the page. The code for this for comments (on answers) is here:

https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/question.js#L32-L37

I don't think there's any corresponding "on success" triggering when you save an edit... 

An easy fix could just be to remove `data-remote:true` and let the whole page refresh. Editing answers isn't extremely common, so a page refresh isn't the end of the world --- in fact it's much better than the current lack of updating at all!

**Comment by cesswairimu** [comment]
So currently the refresh is happening. Maybe it was fixed on another issue. Closing this. Thanks all
