### ISSUE TITLE
Move translation helper from sidebar to an "alert" box at top of page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1808]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

### Please describe the problem (or idea)

This page is now tagged with `lang:zh` which triggers a Translation widget to appear at the top of the sidebar. But it's not easy to notice.

The code is here: https://github.com/publiclab/plots2/blob/f40642c7b8e64484cebeb0b35ca34b2c48841f76/app/views/sidebar/_related.html.erb#L24

## Solution

Let's move it to the top of the page, into an `alert` box, using Bootstrap, as in these lines of code:

https://github.com/publiclab/plots2/blob/master/app/views/notes/show.html.erb#L6-L11

**Comment by kkavita92** [comment]
I can claim this!

**Comment by jywarren** [comment]
Yes please! That would be great. Thank you!

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by tungla** [comment]
@jywarren could you show me which screen does the side appear? I'd like to claim this issue

**Comment by jywarren** [comment]
Here's one example with the translation sidebar widget:

https://publiclab.org/notes/juncheng09/12-09-2017/instruction-for-sensors

Awesome, thanks!

**Comment by tungla** [comment]
is this the correct position you're aiming to @jywarren?
![image](https://user-images.githubusercontent.com/8103307/33820071-0c53ce0c-de80-11e7-9fdd-6179be75c456.png)

**Comment by jywarren** [comment]
This looks good, but do you think we could put it in the main (right)
column? And I think we don't need the full header for Translation. It could
just be in a <p> -- "Translate this post" -- how does that sound?

Thanks so much, this is looking great!

**Comment by tungla** [comment]
Updated @jywarren. Is that ok?
One problem is i have to use javasciprt to edit HTML of google translate element (to add a <span> to its div). Is it fine to use this approach?
![image](https://user-images.githubusercontent.com/8103307/33929027-95730e64-e01a-11e7-853b-6142a7ff18ef.png)

`<% if @node && (@node.has_power_tag('iso') || @node.has_power_tag('lang')) %>
    <div id="google_translate_element" class="alert alert-info">
      <script type="text/javascript">
      function googleTranslateElementInit() {
        new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE, autoDisplay: false, multilanguagePage: true}, 'google_translate_element');
        addLabelTranslateElement();
      }
      function addLabelTranslateElement() {
        var paragraph = document.createElement('span');
        paragraph.innerHTML = "Translation: ";
        paragraph.style.fontSize = '125%';
        document.getElementsByClassName("skiptranslate goog-te-gadget")[0].prepend(paragraph);
      }
    </script><script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
  </div>
  <% end %>`

**Comment by jywarren** [comment]
Hmm, interesting! This looks cool -- what does the span add? I also was hoping to get it to display in the main column above the title and main image, but this is looking good! Can you open a pull request with your solution? Thank you!

**Comment by jywarren** [comment]
Hi, @tungla -- just checking if you're able to open a pull request with this code. Thanks!

**Comment by tungla** [comment]
Yes @jywarren, gonna open a PR soon, sorry for being late

**Comment by jywarren** [comment]
no problem! Thanks!

**Comment by raunaks13** [comment]
@jywarren - This is my first time contributing. Since this issue has been inactive for a while can I try to submit a PR?

**Comment by jywarren** [comment]
yes please! We'd appreciate that!
