### ISSUE TITLE
Make user profile bios searchable in new search system

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1824]
#1823 suggests this -- we'll have to wait until Solr search is enabled, but we could make the changes here:

https://github.com/publiclab/plots2/blob/master/app/models/user.rb#L16

They'd be similar to the lines in `node.rb`:

```ruby

  searchable if: :shouldIndexSolr do
    text :title
    text :body do
      body.to_s.gsub!(/[[:cntrl:]]/,'').to_s.slice!(0..32500)
    end
```

but for the field `bio`, not `body`. 

Let's hold on this until the new Solr search system is running!

**Comment by ekeast** [comment]
Can I claim this? Or are you still waiting until the new Solr search system is running?

**Comment by jywarren** [comment]
Hi, the new Solr code is merged into our published code branch, but we are
still troubleshooting performance issues before enabling it on production.
However, I think this change can go forward and does not have to be coupled
to the performance issues! Thank you!

**Comment by jywarren** [comment]
This is complete! Thank you and if you're looking for a place to get involved, please see:

https://publiclab.github.io/community-toolbox/#r=all

Thanks!!!
