### ISSUE TITLE
Get numerical hashes like #123 to link to notes, not generate tag links

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1825]
### Please describe the problem (or idea)

Right now, when you use a hashtag like `#sampling` on PublicLab.org, you get a link to the corresponding tag page, https://publiclab.org/tag/sampling. 

If you use a number like `#123`, you likewise get linked to `../tag/123`. 

But this would be a good opportunity to link that to the node with matching ID -- like, for example, https://publiclab.org/n/99 for `#99`

## Solution

The regular expression code to find numbers is here: 

https://github.com/publiclab/plots2/blob/master/config/initializers/constants.rb#L3

We should exclude just numbers -- so while this should work:

`#hello-2`

This should not match:

`#99`

This last `#99` should instead be matched by a new one that does /not/ match any letters. 

To try these out, you can use http://Rubular.com, using the test string:

```
#99
#hello-2
#hello
```

Then, each place we do the substitution should be added to so we replace the numerical ones too: 

https://github.com/publiclab/plots2/search?utf8=%E2%9C%93&q=Callouts.const_get(:HASHTAG)

**Comment by sagarpreet-chadha** [comment]
@jywarren sir...can i take this ?

**Comment by jywarren** [comment]
yes please! this has been a goal for a long time and it'd be fantastic to
see it built out! :-)
