### ISSUE TITLE
Create new inline grid for wiki pages, with format [wikis:_tagname_]

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1828]
## New feature

Our inline power tags let us make grids for activities, like in https://publiclab.org/wiki/activities

Let's make a new one to display lists of wiki pages! It could have the syntax `[wikis:_tagname_]` where `_tagname_` is something like "balloon-mapping" -- so it would show wiki pages tagged with "balloon-mapping", as currently shown on these pages:

* https://publiclab.org/wiki/tag/balloon-mapping
* https://publiclab.org/wiki/tag/hydrogen-sulfide

## Changes

For how we currently set up a grid using notes, see `def notes_grid`: 

https://github.com/publiclab/plots2/blob/master/app/models/concerns/node_shared.rb#L31-L52

For the template we'll have to copy into `_wikis.html.erb`, see:

https://github.com/publiclab/plots2/blob/master/app/views/grids/_notes.html.erb

I believe this is it -- but there may be one more step to get this working. Let's start with this and we can ensure it works by adding a test to this file, similarly to how we test notes grids;

https://github.com/publiclab/plots2/blob/master/test/unit/node_shared_test.rb#L4-L12

The end result is that we should be able to put `[wikis:test]` onto a wiki page, and it should show all wiki pages that have been tagged with the word `test`. 

Make sense? This is a big one, with several moving parts, but it should be easy to write a test for and make progress on. And I'm happy to help! Thanks!

**Comment by zhirschtritt** [comment]
I'd like to do this one, but does seem quite big! @jywarren If you think this would be okay for me to take on I'll go at it.

**Comment by jywarren** [comment]
I'd say have a go at it! It has a lot of moving parts but if you're OK with
some back-and-forth as we figure it out, I'd love your help. Tnx!

**Comment by Diksha2008** [comment]
@jywarren I would like to work on this if @zhirschtritt hasn't!

**Comment by jywarren** [comment]
Yes I think so! But also consider this one which is similar and very useful!

https://github.com/publiclab/plots2/issues/1340

**Comment by zhirschtritt** [comment]
Sorry I dropped off the map on this!

**Comment by jywarren** [comment]
no problem! Hope you're well -- and any time you want to work on an issue,
ping me!

**Comment by jywarren** [comment]
also -- i bought a grain mill. rad.
