### ISSUE TITLE
Expand Tag.tagged_nodes_by_author() method to accept "*" tagname wildcards

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1833]
This line shows the new method added by @SidharthBansal -- 

```ruby
Tag.tagged_nodes_by_author(tagname, user_id)
```
https://github.com/publiclab/plots2/blob/e72cb97ce12f81f68b5195c00e5fb6a22ee08f83/app/models/tag.rb#L227-L232

We want to be able to match "wildcard" tagnames like any tag starting with `activity:` -- often denoted with an asterisk (`*`) -- like in this query: https://publiclab.org/tag/activity:*

This isn't such a tough query -- there's an example here:

https://github.com/publiclab/plots2/blob/e72cb97ce12f81f68b5195c00e5fb6a22ee08f83/app/controllers/tag_controller.rb#L60-L77

See how we detect a wildcard and then switch to an alternative query? This could potentially be more compact, but it works.

Any help with this would be much appreciated!

Once we do this, we can move on to listing all activities a user has done on their profile, by using the query:

```ruby
Tag.tagged_nodes_by_author('replication:*', @profile_user.id)
```

But not yet! Let's do this first and then we'll have a good basis to work from. Thanks!!!

**Comment by SidharthBansal** [comment]
I will like to work on this

**Comment by jywarren** [comment]
Please! That'd be great and you understand the code already!
