### ISSUE TITLE
Adapt TagSelection to UserTag in profile social media features

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1839]
@sagarpreet-chadha -- sorry, I think these lines should be using UserTag, not TagSelection: 

https://github.com/publiclab/plots2/blob/b46b40c6a68f40f1a883dcf506c1a41fb3096131/app/models/user.rb#L157-L164

My fault!

**Comment by sagarpreet-chadha** [comment]
Oh right...so sorry ! Working on it !
Thank You 👍

**Comment by jywarren** [comment]
No problem at all, it was my fault too for not seeing this connection!
Thank you!!

**Comment by jywarren** [comment]
Solved in 03f068f !
