### ISSUE TITLE
Adding Instagram social media link to profile page 

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#1840]
This has been marked as a good candidate for becoming a first-timers-only issue like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors) it as a first-timers-only issue, and then ping @jywarren to get it labelled. Or, if this is not your first time, try to solve it yourself!
### Please describe the problem (or idea)
The issue is part of issue #1802 .
Currently in profile page we can give links to users social media accounts : **facebook , github and twitter** .
Lets add link to **Instagram** also .
<img width="1436" alt="fto" src="https://user-images.githubusercontent.com/14952645/33779269-28ad4da4-dc72-11e7-92c0-4a8fe1f541cb.png">

### Solution 

The code for solving this can be found in PR #1816 . 

1.) Lets add the Instagram logo picture using font-awesome library here :  
       [http://fontawesome.io/](http://fontawesome.io/)
https://github.com/publiclab/plots2/blob/b46b40c6a68f40f1a883dcf506c1a41fb3096131/app/views/users/profile.html.erb#L15

2.) And the code to calculate the link to users instagram account here :  
https://github.com/publiclab/plots2/blob/b46b40c6a68f40f1a883dcf506c1a41fb3096131/app/controllers/users_controller.rb#L126

**Comment by tungla** [comment]
I'd like to claim this issue

**Comment by sagarpreet-chadha** [comment]
Yes please ! Sure !
