### ISSUE TITLE
Develop integration tests for all routes based on provided sitemap list

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1846]
We recently  had some serious issues in the Rails 4 upgrade when our `config/routes.rb` file changed. I had forgotten, but although we have very thorough functional tests, these don't test our routes, because they bypass the URL routing. 

So while all our controller methods worked, the URL routes to access them were messed up. Let's not do that again!

Integration tests test the routes. They're slow for other purposes, but we can use them to stabilize our routing system against things like this. 

How do we work from a list of external URLs to generate an integration test for all the URL routes we want to preserve?

## Sitemap

I used https://www.xml-sitemaps.com to make a partial sitemap (of course not including things you can only see when logged in) --

https://gist.github.com/jywarren/4a1bbc5f02f8b7e28d75c08f52ebc512

This is a good one to start with. Let's use this as a reference to develop some URL route testing in the integration tests, roughly like these:

https://github.com/publiclab/plots2/blob/master/test/integration/public_pages_test.rb

There are also some more obscure ones we should test, while logged in and logged out; these include:

* like buttons, which are via javascript, but at a predictable URL

This issue needs more info, but is a pretty worthwhile project!

**Comment by sagarpreet-chadha** [comment]
@jywarren...can i work on it ?

**Comment by jywarren** [comment]
Sure, it's a bit of a big one... Go for it! One piece at a time!

**Comment by Manasa2850** [comment]
@jywarren I would like to take this up and add tests for the rest of the routes. Thanks!
