### ISSUE TITLE
Make questions posting page visible when not logged-in, with friendly message

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1848]
### Please describe the problem (or idea)

When you click on "ask a question" on the site, but you're not logged in, you see an error page:

https://publiclab.org/questions/new?title=lalalala

We should show the page with a nice prompt to log in or create an account first. The template for this page is here:

https://github.com/publiclab/plots2/tree/master/app/views/editor/questionRich.html.erb

Right now it's erroring because it depends on logged-in data; run it in development mode to see the exact errors!

Would love help with this one -- thank you!

**Comment by Gauravano** [comment]
I have tried to "ask a question"  but after clicking it's redirecting me to https://publiclab.org/questions and if I further enter question and press ask button then I am redirected to the login page (All this while I am logged out).Kindly give some more details.Thank you.

**Comment by jywarren** [comment]
Hi, is this while logged in and is it on your local machine or on
publiclab.org?

Thank you!

**Comment by Gauravano** [comment]
I have tried this on my localhost as well as on [publiclab.org](publiclab.org)  at both places no error message is coming up and I was just redirected to login page


![peek 2017-12-10 21-43](https://user-images.githubusercontent.com/20878070/33806842-cb53e3f6-ddf3-11e7-9e15-d7a243064798.gif)

**Comment by jywarren** [comment]
Ah but did you go to /questions/new ? Some buttons on the site lead there.

**Comment by Gauravano** [comment]
yes, questions/new is giving the error.Can I work on this?

**Comment by jywarren** [comment]
Yes please, that'd be great!
