### ISSUE TITLE
Highlight posting Activities from the dashboard, with guidance

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1850]
### Please describe the problem (or idea)

On the site, there are a lot of "Research note" posting buttons. And now Question buttons. 

For example on https://publiclab.org/dashboard

Let's help encourage people to post step-by-step, how-to activities, as described on http://publiclab.org/w/activities

The `Share your work` button on the dash should at least feature `Share a step-by-step activity` as the first option, leading to the template featured on http://publiclab.org/w/activities (use the URL from the button there).

**Comment by SheepD** [comment]
submitted pr #1898 for review. hopefully i got the context of this issue correctly on the PR
