### ISSUE TITLE
Inconsistencies in tag deletion (investigating)

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#1859]
### Please describe the problem (or idea)
On the https://publiclab.org/wiki/getting-started I observed some issues
1.Any user can add tags to this page. Like I added "balloon". 
2. It automatically tagged with "balloon" and "balloon mapping".
3.There are some tag names with 'X' and some without 'X' for deletion. The tag named "balloon" and "balloon mapping" is not having 'X' to click which I made.
4.On pressing the 'X' next to the tag name by Warren, a javascript dialog box appears, which should not. I tried to delete one but not able to. 
I think a person who has written the tag has the capability to it but here it is not happening.
![image](https://user-images.githubusercontent.com/20972099/33805962-b12d58f2-dde6-11e7-8947-3b1d333ee552.png)

### What's your PublicLab.org username?
bansal_sidharth2996
### Which operating system and browser are you using?
I am using Ubuntu 14.04 with Firefox 57.0.1 (64-bit)

**Comment by SidharthBansal** [comment]
Also as a user, I am just able to add tags to the questions but I am not able to delete tags which I created in the questions.

**Comment by SidharthBansal** [comment]
@jwarren can you explain to me whether this is a feature?

**Comment by jywarren** [comment]
Hi, you should be able to delete a tag if:

* it's your note or question
* it's your tag

I forget the exact rules for a wiki page, but there are two places to look if it's wrong -- first in the tag controller and second in the markup in /app/views/tags/ for displaying a tag. Actually, a third place is where new tags are just created, they're done in pure javascript without a template. So there could be a third place to confirm it's correctly working there.

I guess let's try to narrow this down to a specific bug if you can identify one -- one URL, a single tag, and a reproducible behavior that seems wrong. Then we can look at the above referenced code areas to see if we're missing something. Sound good?

Thanks!!!

**Comment by SidharthBansal** [comment]
So, I was thinking right. It is a bug, not a feature.
And yeah it is only in one URL, two tags balloon and balloon-mapping.
One thing more, I am getting 'X' for other users' tag that is not an expected behaviour and that is happening for many wiki pages. That I think is js issue. Will link into both

**Comment by jywarren** [comment]
Great!

**Comment by jywarren** [comment]
I just adjusted the title accordingly. Thanks!

**Comment by SidharthBansal** [comment]
The implementation is ---if the node and the tag belongs to the same user then the javascript will show the alert box and will pass in the controller the node and tag ids, then delete the tag which has some author.
https://github.com/publiclab/plots2/blob/3db7e63c37d10516576a4cf585e1d05584c06682/app/views/tag/_tags.html.erb#L8-L14
https://github.com/publiclab/plots2/blob/3db7e63c37d10516576a4cf585e1d05584c06682/app/controllers/tag_controller.rb#L229 
It does not handle the case that if SidharthBansal creates a tag on @jywarren  's post, he should be able to delete it. I guess it needs to be changed. I have changed in the view in the pull request. Trying to change in the controller.

**Comment by jywarren** [comment]
Awesome good work!

**Comment by SidharthBansal** [comment]
Can you please review the pull request
Thanks
