### ISSUE TITLE
Link To deletion of UserTag on profile page broken .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#1860]
### Problem

The link to deletion of UserTag on profile page is broken .
I was not able to find any code for deleting the user-tags on profile page .

<img width="911" alt="screen shot 2017-12-10 at 11 15 50 pm" src="https://user-images.githubusercontent.com/14952645/33807654-1d1bd2c8-de00-11e7-880c-4b3fc61214a7.png">

### Thank You

**Comment by sagarpreet-chadha** [comment]
@jywarren sir...also i am not able to **unsubscribe** from my subscriptions .
Should i open another issue for that ? is it related to upgradation to rails 4 ?

**Comment by jywarren** [comment]
:-/ good catch, yes. Probably. Most of these may be mistakes in the
routes.rb file, some due to put/get method. Thanks!

**Comment by jywarren** [comment]
I think we need integration tests to ensure routes changes don't break things. I have an initial issue up here:

https://github.com/publiclab/plots2/issues/1846

**Comment by jywarren** [comment]
Solved in #1865
