### ISSUE TITLE
Error posting comment on answer

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1864]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I received an email with an exciting answer posted. 
<img width="725" alt="screen shot 2017-12-11 at 10 31 30 am" src="https://user-images.githubusercontent.com/161439/33838767-7e9e8d02-de5e-11e7-98bd-cfbd7a8a91de.png">

I clicked the link to comment on the answer, and was brought to the correct comment box. I typed a short reply, and clicked submit and got an error: 

<img width="751" alt="screen shot 2017-12-11 at 10 29 20 am" src="https://user-images.githubusercontent.com/161439/33838686-35cb1e42-de5e-11e7-8cce-1c1f77db1572.png">

Next, i went to the URL, deleted everything after the `?` and reloaded the page. Manually, i scrolled down to the same comment box, put the same one-liner, and clicked submit. The same error occurred. 

FYI I have never seen this error before and that's saying a lot considering what a heavy site user i am. 

> What did you expect to see that you didn't?

I expected to be able to be able to hit submit and have it submit properly. 

### Please show us where to look

https://publiclab.org/questions/warren/09-19-2017/how-do-i-stabilize-smaller-balloons-and-prevent-them-from-being-blown-down-in-the-wind

https://publiclab.org/questions/warren/09-19-2017/how-do-i-stabilize-smaller-balloons-and-prevent-them-from-being-blown-down-in-the-wind#answer-644-comment

### What's your PublicLab.org username?

> This can help us diagnose the issue: liz

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

Chrome on mac.

**Comment by jywarren** [comment]
Gaurav - sure -- i think this relates to changes to the routes file from
the Rails 4.1 upgrade. It's possible the route to make a comment on an
answer has been changed to POST only, not GET, and that we need to either
change it to GET or to modify the commenting code to use POST. Make sense?

Thank you!

**Comment by Gauravano** [comment]
Yes @jywarren this is also due to upgrade, it seems some code is missing from routes so I have fixed this by doing little changes in the comment_controller for now. Thank you.

**Comment by Gauravano** [comment]
Hi @ebarry, Can I close this issue if the problem doesn't exist anymore?

**Comment by jywarren** [comment]
Done, thanks!
