### ISSUE TITLE
Not able to Unsubscribe from subscriptions 

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#1866]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

Not able to Unsubscribe from my subscriptions . 
On clicking unsubscribe button links to `/tag/______`   .
The issue is most probably part of #1846 .

****

**Comment by rishabhptr** [comment]
@sagarpreet-chadha @jywarren  Similar issue persist if user click subscribe to everything from /subscriptions and tries to click the same button.(on hover it says click to unfollow).

Same is the case for /subcriptions/(tags) page clicking the "following (tag)"  button leads to the same page.Could it be a first-timer-issue?

**Comment by sagarpreet-chadha** [comment]
@rishabhptr great catch !! It would be a good FTO issue ✌️ 👏

**Comment by jywarren** [comment]
Agreed!!!

**Comment by jywarren** [comment]
Solved in #1867!
