### ISSUE TITLE
Unlike feature not working 

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#1870]
### Please describe the problem (or idea)

Unlike feature not working for any node .

**Comment by jywarren** [comment]
I'm actually seeing the like button feature not working when logged in, on pages like


https://publiclab.org/questions/stevie/12-15-2017/what-are-good-ways-to-capture-outputs-and-notes-at-events

**Comment by jywarren** [comment]
Fixed!
