### ISSUE TITLE
Sort tags by what you are subscribed to

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1873]
### Please describe the idea

> What problem could this idea solve?

This idea relates to improving the experience of finding topics that you are interested in on publiclab.org and subscribing to the conversation. 

The foundation is already in place thanks to this incredible community. When a signed-on person browsing publiclab.org/tags, the `following` button is highlighted right there in line which is awesome! 

![screen shot 2017-12-11 at 3 48 51 pm](https://user-images.githubusercontent.com/161439/33853228-41c0c4c2-de8b-11e7-9f0d-f6dd1949dab7.png)

### First idea

For someone to see all their subscriptions at once, which i suggest is logically the next thought that someone has when looking at all the tags, the column header `Your Subscriptions` could be a **link to sort all of the tags you are following to the top of the list** -- see righthandmost column heading in screenshot below: 

<img width="879" alt="screen shot 2017-12-11 at 3 41 05 pm" src="https://user-images.githubusercontent.com/161439/33852884-143d2744-de8a-11e7-9aad-a9d6e37de0de.png">

### Second idea

We could add a link to publiclab.org/subscriptions somewhere near the top of this page. Not sure. 

### Please show us where to look

https://publiclab.org/tags
https://publiclab.org/subscriptions

This relates to the giant tag page planning issue https://github.com/publiclab/plots2/issues/179

### What's your PublicLab.org username?
liz

**Comment by Ronaq13** [comment]
I would like to work on it.

**Comment by Ronaq13** [comment]
@ebarry : I would like to work on this.

**Comment by ebarry** [comment]
The short story is that this issue requests another way to sort the order that tags are displayed on /tags. Specifically, that the column header "Your Subscriptions" would be clickable with the result that all tags that you are subscribed to go to the top of the list.

**Comment by jywarren** [comment]
Great, could you narrow the title description to note this refined issue definition? I think this is nice and discrete and if well-described, we can get it solved -- @Ronaq13 we'd love your help if you're still interested!

**Comment by jywarren** [comment]
So:

1. Make a link where it says "Your Subscriptions"
2. Develop a new sorting view, using a new URL perhaps like `/tags/warren` (your username) ? or `/tags/mine`? (preference?)

I can then add links to relevant lines of code so this'll be easier to tackle. Thanks!

**Comment by jywarren** [comment]
The wiki page sorting shows a good example of this kind of sorting link: https://publiclab.org/wiki

**Comment by Gauravano** [comment]
Hi @ebarry @jywarren can I take this issue

**Comment by Gauravano** [comment]
Also, presently '/tags' page has Sort button on top-right of the page for sorting, we can make table heading i.e., name, #uses, and subscriptions as links like in '/wiki' pages.What's your view on this @ebarry I guess it implements your first idea totally.

![new](https://user-images.githubusercontent.com/20878070/34944757-d2d06bf0-fa26-11e7-9871-4f37f81b908f.png)

**Comment by jywarren** [comment]
I like this solution -- it's more compact and consistent. Let's do it!

**Comment by jywarren** [comment]
So this issue has 2 parts -- 

1. the "Your Subscriptions" link to /subscriptions
2. the reorganization of the sorting links from the dropdown menu to just being links on the header items of the table

Maybe @Ronaq13 if you're interested in 1, @Gauravano could take 2? Thanks, all!
