### ISSUE TITLE
Auto-locate me not working

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#1874]
A person is not able to locate his location through auto locate me feature listed
![image](https://user-images.githubusercontent.com/20972099/33855579-570c866c-deeb-11e7-910d-46ac30a6dc59.png)

**Comment by jywarren** [comment]
:-/ this is done via IP-based geocoding if you don't have a GPS (mostly just phones have a GPS). So I think it's just not great -- the geocoding is implemented in https://github.com/publiclab/leaflet-blurred-location/ actually so if we wanted to come up with either a way to improve it or a way to warn people when the location won't be accurate, we could open an issue over there. Would you mind? 

Thanks!

**Comment by SidharthBansal** [comment]
ok

**Comment by SidharthBansal** [comment]
No problem, there was problem in my gps. Thanks for telling. On mobile phone, working fine.

**Comment by jywarren** [comment]
awesome!

**Comment by SidharthBansal** [comment]
Sorry for not checking properly

**Comment by jywarren** [comment]
no problem at all! Glad it was resolved.
