### ISSUE TITLE
initial wiki creation does not associate uploaded main image

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#188]
### Summary

Jeff sez: copy functionality from notes_controller; see [my comment below](https://github.com/publiclab/plots2/issues/188#issuecomment-88627252)

In summary, we've solved this already in research note posting (https://publiclab.org/post) and need to reproduce it by copying the `params[:main_image]` line from https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb#L80 to https://github.com/publiclab/plots2/blob/master/app/controllers/wiki_controller.rb#L105-L109 and test.

****

I just copied @ebarry 's wiki format to create the food wiki.
http://publiclab.org/wiki/food

It wanted a main image (like research notes). So I went around looking for a nice creative commons image of lots of food.

Now I've got a meta section in the wiki which references the CC license and cites the image source (as desired for the license) ... but I see no trace of the image. Makes that section a bit awkward.

Does the main image do anything or show up anywhere for a wiki page? If not, should we remove that feature from the editor for wikis?

**Comment by jywarren** [comment]
Confirmed; the lead image upload does not associate image to page on initial wiki page creation. In the notes controller, we associate using `params[:main_image]` which is set by the image uploader in a hidden field in the note form. Should be easy to port this over to the wiki form too and add to wiki_controller#create
