### ISSUE TITLE
Inconsistent tag deletion buttons

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1884]
This may be due to the Rails 4.1 upgrade, but when I create and then try to delete a tag with the `x` button, it doesn't work. However when I refresh the page, I can then delete the tag successfully --

Try it: https://publiclab.org/w/raspberry-pi-spectrometer

The erroring case is the one where the tag button is generated in JavaScript, on the client side, and inserted, probably using code in `/app/assets/javascripts/tagging.js`. Something must be wrong with this -- maybe it needs to use method `DELETE`?

**Comment by ViditChitkara** [comment]
Can I try and fix this??@jywarren

**Comment by jywarren** [comment]
sure, give it a try! Thanks!!
