### ISSUE TITLE
fix chat button and 404 page to only load chat frame when explicitly clicked on

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#189]
Presently, the chat software is loaded when viewing any page as part of the menu and it is loaded for any 404 page and all the other error pages.
- https://github.com/jywarren/plots2/blob/96f3a6b1e1dc26601aad4716d1d51ed533c4cd46/public/404.html#L178-L182
- https://github.com/jywarren/plots2/blob/96f3a6b1e1dc26601aad4716d1d51ed533c4cd46/public/422.html#L178-L182
- https://github.com/jywarren/plots2/blob/96f3a6b1e1dc26601aad4716d1d51ed533c4cd46/public/500.html#L178-L182
- https://github.com/jywarren/plots2/blob/96f3a6b1e1dc26601aad4716d1d51ed533c4cd46/public/502.html#L178-L182
- https://github.com/jywarren/plots2/blob/a98763dbe3b996b3c21068a84feddaa5211603ee/app/views/layouts/application.html.erb#L184-L188

Instead, it would be better to lazy-load the chat iframe only when a link is clicked (such as the chat bubble itself on the header, or some kind of new button on the error pages).

It might be good to reduce copypasta while this is being fixed. I'm not sure why the error pages don't use the application ERB or why the application ERB and the error pages don't share some stripped down common ancestor. Perhaps error responses don't support ERB templates for some reason?

**Comment by jywarren** [comment]
> responds with dynamic content instead of forwarding to the static page.

I'm not sure, but do you think that this would be a significant additional load on our server to assemble/parse the dynamic content vs. serve a static page for 50x/40x errors? 

I'd like to propose breaking this in two -- 

1. replace all instances of chat with a 'click to open' version to avoid loading the `iframe`, as outlined in [Bryan's comment above](https://github.com/publiclab/plots2/issues/189#issuecomment-67396274)
2. (separately) discussing ways forward on static vs. dynamic error pages, and reducing duplicated code there

Thanks!

**Comment by gauravano** [comment]
Hey @jywarren,  now that we have chat window available at https://publiclab.org/chat only. Can we close this issue? Thanks!

**Comment by gauravano** [comment]
Actually, closing this one. Please reopen if you think, we need some enhancement. Thanks!
