### ISSUE TITLE
make a time-bounded version of tag.contributorcount ?

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1891]
Hi everyone!
### Please describe the problem (or idea)

In order to show how many unique contributors have been active in a certain period of time, perhaps we could make add a time-bounded version of the tag.contributorcount function

### Please show us where to look

Contributor counts are already looking great on tag pages! Check out how the number count is shown right on the tag page https://publiclab.org/tag/spectrometer and it's clickable leading to a page that shows individuals: https://publiclab.org/contributors/spectrometer 

### Next steps after this

Adding contributor count by time period to publiclab.org/stats (in discussion over at ) https://github.com/publiclab/plots2/pull/1672

**Comment by ViditChitkara** [comment]
@ebarry can I give it a go?

**Comment by ebarry** [comment]
Wow Vidit, that would be amazing!!! Please give it a go and let us know how
it goes. :D

--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net

**Comment by jywarren** [comment]
It'd be great if it could accept a time start and end as parameters! Like `contributor_count_for(Time.now, Time.now - 1.week)` -- isn't ruby cool?

**Comment by ebarry** [comment]
this is awesome! I can see how many unique contributors we have in a given timeperiod, for example  this one: https://publiclab.org/stats/range/10-05-2015/10-05-2016/
thank you so much everyone for working on this!!!

**Comment by ViditChitkara** [comment]
It was a fascinating task, indeed!
