### ISSUE TITLE
cache not expiring in rails 4.1

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1892]
This line clears the cache for website features but doesn't seem to be working in rails 4. Maybe the convention has changed?

https://github.com/publiclab/plots2/blob/563371059ac7d33f350d691f3f9182e8bd6f9132/app/controllers/features_controller.rb#L81

**Comment by namangupta01** [comment]
Hey @jywarren, can i work on it ?

**Comment by jywarren** [comment]
That'd be great, thanks a lot!

**Comment by jywarren** [comment]
Hi, any progress on this? I'd be happy to help, we need to get this one resolved. Happy new year!

**Comment by 500swapnil** [comment]
Could I look into this if it's not resolved yet?

**Comment by jywarren** [comment]
Ah, it looks like there's an issue with Rails 4+ adding a "digest" string to the cache key: https://stackoverflow.com/questions/17445994/rails-4-0-expire-fragment-cache-expiration-not-working#17619414

The workaround is to specify `skip_digest` in each use of cache in the views -- we'll have to search through the views to find these. The format for the change would be:

```ruby
<% cache "all_available_releases", skip_digest: true do %>
```

Hope that helps!

**Comment by 500swapnil** [comment]
Yeah that would work. Another shorter solution I found was using regular expressions.
So it would simply be replaced with this
---ActionController::Base.new.expire_fragment("feature_#{params[:title]}")---

**Comment by 500swapnil** [comment]
@jywarren I'll create a pull request. Which method do I use? (Regular exp. or adding cache digest)

**Comment by 500swapnil** [comment]
Opened a PR #1911

**Comment by jywarren** [comment]
Hmm, does this work for sure? Have you tested it out? Cool, thank you!

**Comment by 500swapnil** [comment]
I found it here. It passes all the tests and works fine.
https://stackoverflow.com/questions/33499384/expire-fragment-caching-in-rails-4

**Comment by jywarren** [comment]
I don't think we have a test that tests out cache expiry, and I'm not sure we were seeing the error `"undefined method `expire_fragment' for #<ItinerarySweeper:0xb5a3510 @controller=nil>"` -- actually we don't see an error when this controller method is run. So I'm just not sure. 

I think it's worth a try to merge your PR and see if it works, but if it doesn't then we try the other way?

**Comment by jywarren** [comment]
Leaving this open until we confirm that #1911 fixed it.

**Comment by 500swapnil** [comment]
Okay that makes sense. I ran all the tests. Didn't know they didnt see cache expiry. Let's see if this fixes it and if not, We'll try the other way.

**Comment by jywarren** [comment]
OK, it looks like we need `, skip_digest: true do` -- i just published a new version and don't see the cache expiring!

**Comment by jywarren** [comment]
This got a bit more urgent as we noticed the activity feed isn't updating -- so i'm going to push through an update. Thanks!

**Comment by 500swapnil** [comment]
Do you need me to create a PR? I'll do it now.

**Comment by jywarren** [comment]
i think i got it, but thanks a lot!

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/pull/1923

**Comment by 500swapnil** [comment]
Okay great!

**Comment by jywarren** [comment]
publishing!

**Comment by jywarren** [comment]
That worked! Great!
