### ISSUE TITLE
Remove the Menu

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#1896]
### Please describe the problem (or idea)
If a person who is not logged in clicks on the login button and then on language then nothing happens.
> What did you expect to see that you didn't?
The person should be either able to change language or there should be no language button in the login menu in the header. As we already have a language button in the footer.

**Comment by SidharthBansal** [comment]
I think this is due to removal of drop-down submenus from bootstraps v3 onwards
See https://stackoverflow.com/questions/18023493/bootstrap-3-dropdown-sub-menu-missing
We already have a language change option in the footer. For me, it does not make sense to have a button under login for language.

**Comment by jywarren** [comment]
@ebarry what do you think? Could we simply remove this from the menu? Or should we look into a menu fix?

**Comment by ebarry** [comment]
Let's remove it from now. Do we have an issue open for improving our translation process and how we keep the translation up-to-date with the current site?

**Comment by jywarren** [comment]
OK, that sounds good -- Sidharth, do you think you could update the issue
title to just remove the menu? Then we could make a first-timers issue from
it if you'd like.

Liz, I don't think we do, but we could talk about that on OpenCall if you
want?

**Comment by ebarry** [comment]
we'll have to deal with translation sometime. Sooner than later if that
international grant goes through.

--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net

**Comment by jywarren** [comment]
Sure, it's not too complicated. If we do it once per month, it'd be about 3
hours of work, i think. Who'd be doing it? These are the sorts of things we
should discuss.

**Comment by SidharthBansal** [comment]
I have changed the title to Remove the Menu @jywarren.
May I create a first timer issue?

**Comment by jywarren** [comment]
please do! I forget, have you before? Either way there's some good guidance
here: https://publiclab.github.io/community-toolbox/ -- awesome!

**Comment by SidharthBansal** [comment]
I have not opened any first timer before. Would like to do it today :-)
