### ISSUE TITLE
Move comments to answers in questions 

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#1897]
### Please describe the problem (or idea)

Sometimes on the Q&A feature (www.publiclab.org/questions), people post answers to questions in the comments section. I think it would be good if there was an option to move a comment to an answer, (and maybe vice versa? but I don't think that's as important). I think it will help us curate the information and hopefully make the answers more visible.

**Comment by jywarren** [comment]
This is a good one -- I think we could make a method in the `comment_controller` called `make_answer` which:

1. creates a new answer
2. copies the text, author, and node ID from the comment
3. saves the answer
4. deletes the comment (but only after checking that the answer is saved)

Then we could add a test for this to be sure -- in https://github.com/publiclab/plots2/tree/master/test/functional/comment_controller_test.rb

If someone wants to give this a try, it'd be much appreciated!

**Comment by Gauravano** [comment]
hey @jywarren @steviepubliclab, first of all, happy new year, this functionality seems really cool.Can I work on this?

**Comment by steviepubliclab** [comment]
Happy New Year, and yeah that would be awesome!
-Stevie

**Comment by steviepubliclab** [comment]
Ohh closed? did it get finished? that would be so awesome!

-Stevie

**Comment by Gauravano** [comment]
yes @steviepubliclab its implemented successfully

**Comment by steviepubliclab** [comment]
Awesome!!! thanks so much. going to test it out now.

-Stevie

**Comment by steviepubliclab** [comment]
Hm I don't see how to do it. I'm looking at this one:
https://publiclab.org/questions/stevie/12-19-2017/what-resources-are-available-to-help-people-monitor-noise-pollution


and hoping to move the comment from Primack into the answers section. Any
ideas?

-Stevie

**Comment by jywarren** [comment]
Sorry, it's not published to the site yet! Late tonight!!!

**Comment by steviepubliclab** [comment]
I love this feature - This is so great. :)
