### ISSUE TITLE
database instructions seem to be wrong

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#191]
Following the README, `rake db:migrate` worked fine. The next step broke:
```
$ rake db:setup
plots2 already exists
Access denied for user 'root'@'localhost' (using password: NO). 
Please provide the root password for your mysql installation
>
```

It seems like `rake db:setup` should be run before or instead of `rake db:migrate`?

Also, it shouldn't be using the root user at any rate, as that isn't part of my `database.yml`. I think there are some extraneous assumptions being made with setup.

**Comment by jywarren** [comment]
Wait, which docs, Bryan? the plots2 docs? Let's change that then; it should be an either-or. 

As for root, perhaps it's just a local db yaml config, but may be a good idea to scrub that from any default files we have lying in the codebase to discourage it.

**Comment by btbonval** [comment]
It's in the README, as noted in the ticket. I'll highlight the relevant place in the docs.

It wasn't clear to me that either/or was correct, or if so, what the steps _should_ be. It sounds like either/or ... plus some amount of other stuff (e.g. the YAML stuff) that is not presently documented.

https://github.com/publiclab/plots2/blame/98b3e2d48346f1ee7aecf4a45fa5e915d179b632/README.md#L40-L41

**Comment by btbonval** [comment]
I guess the YAML stuff is documented, but then both of the other steps are documented. I'm getting very confused about which to do when and what steps go together for which use cases.

**Comment by btbonval** [comment]
Oh the YAML stuff is not related to my problem, it was just something @sirMackk brought up. That's part of my confusion ;)

**Comment by jywarren** [comment]
Oh, WRT which docs, i just thought for some reason you might've been looking at the Rails docs but i've just been off this thread for a while, sorry. 

Bryan, i don't want to suck you into more web dev, so please beg off if you'd like, but could you try running `rake db:migrate` then `rake db:seed` and if that works, let's change it from setup to seed? If it runs w/out error I'll make the change. But it's no big deal for me to test it myself.

**Comment by btbonval** [comment]
Ah, okay so the change is from `db:setup` to `db:seed`. That's pretty clear
and I can give that a try.

**Comment by btbonval** [comment]
what specifies whether production or development database is used in these commands?

**Comment by btbonval** [comment]
alright got my rvm environment back up and running.

* `bundle install`
* deleted old databases, created new blank ones with names identified in `database.yml`
* `rake db:migrate`
* `rake db:seed` (not `rake db:setup`)

no apparent errors!

* `passenger start`

woopwoop it's running.

Okay so it looks like the correct fix to the documentation is to replace `db:setup` with `db:seed`.

Now here's a question I have from some of the previous comments: is there ever a utility for `db:setup` and should be document that use case?

**Comment by btbonval** [comment]
created a user, posted a research note on my local run. I'm convinced this worked.

I'll change the docs to reflect the needed change and if there's ever a need for `db:setup` we can add that documentation in when it comes due.

**Comment by jywarren** [comment]
`db:setup` does the same thing as `db:migrate`, but instead of walking through each migration sequentially, it skips to the final and most up to date db state and just builds that. It's faster. you can learn more with `rake -D` to describe all rake tasks, or `rake -D db` for the db namespace options. `db:migrate` lets you step through migrations, and `db:rollback` and other variants let you move forward and back through migrations one by one. 

`passenger start -e production` gets you production mode; development is default. 

yay!!!!

**Comment by btbonval** [comment]
oh, then we should replace `db:migrate` with `db:setup` in the README instructions as well?

**Comment by jywarren** [comment]
I've always done db:migrate myself, but i guess that may just be habit. Now
that we're git tracking schema.rb, I don't see why not!

**Comment by btbonval** [comment]
hm. Alright before I update the documentation, I'll nuke the database and ensure it works as expected. Reopening ticket for this small modification.

**Comment by btbonval** [comment]
interesting. `db:setup` creates the databases for you, while `db:migrate` expects them to already exist. That's an important distinction for the documentation.

**Comment by btbonval** [comment]
Alright, `db:setup` fails if any of the databases already exist. It creates the databases otherwise and it does run faster than `db:migrate`.

Registered new user, posted note, all looks good.

Okay so I'll update the documentation to no longer mention creating the databases (although the user needs permission to make databases), use `db:setup` instead of `db:migrate`, and either drop the databases or fall back to `db:migrate` if any problems occur.

**Comment by jywarren** [comment]
Hooray Bryan!!!
