### ISSUE TITLE
Tweak navbar search autocomplete to not auto-select the first result

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1912]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

Just now, i was trying to search for "tufts" (as in tufts university to find those DIY aerostats and talk to those awesome folks). I typed `tufts` into the search box, and the autosuggest suggested a bunch of stuff with the profile `middtuftxbs` at the top of the list. i hit the Enter key intending to search for tufts but instead that autoselected the first result and landed me on https://publiclab.org/profile/middtuftxbs which is spam, so i banned it. A good outcome but not what i was trying to do. 

> What did you expect to see that you didn't?

I expected that typing Tufts and clicking enter would search for what i typed and not anything from autosuggest. If i wanted something from the autosuggest list (which is very nice, thank you!), it should be assumed that i would mouse-down & click or arrow-down & hit Enter to choose from the list. 

### Please show us where to look

https://publiclab.org/search

### What's your PublicLab.org username?

Liz

Thank you!!!!

**Comment by rishabhptr** [comment]
Hey , Can I try this?

**Comment by jywarren** [comment]
Yes please! I believe it'll be a configuration of
https://github.com/bassjobsen/Bootstrap-3-Typeahead

which we set up here:

https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/restful_typeahead.js

**Comment by jywarren** [comment]
Currently it auto-selects the top result. The docs should allow us to disable that behavior!

**Comment by jywarren** [comment]
Hi, @rishabhptr - looks like you opened a branch for this but not yet a PR? Is it ready? Can you open a PR or do you needs some help with that? Thank you!!

**Comment by rishabhptr** [comment]
@jywarren Yes, as you suggested there is a flag for autoselect which is true by default and setting it to false does fix the problem.But that caused multiple solr-dependent tests to fail on my local environment.
Not really sure how this change have caused them to fail, should I make a pr to see how these tests go?

**Comment by jywarren** [comment]
Yes please -- we're actually removing solr soon, so I don't think it'll be
an issue either way! Thank you!

**Comment by jywarren** [comment]
Fixed! Thanks!
