### ISSUE TITLE
Remove the Menu

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#1914]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you :gift_heart:

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!
:thinking: What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.
### Please describe the problem

While a person is logged out, a person cannot change the language from the header.

### Please show us where to look

Look at the header of the web page. While a person is logged out, click on the login. A submenu with 'Languages' option comes.

### Solution
Remove the languages from the header.

:clipboard: Step by Step

 :raising_hand_woman: Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

 :memo:  Remove the Languages submenu from the plots2/app/views/layouts/_header.html.erb

 :floppy_disk: Commit your changes

:twisted_rightwards_arrows: Start a Pull Request. 

 :checkered_flag: Done Ask in comments for a review :)

:thinking::question: Questions?

Leave a comment below!

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seem stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

**Comment by jywarren** [comment]
This is looking good - perhaps link directly to the segment of code that must be removed? Awesome!

**Comment by SidharthBansal** [comment]
This is the link directly to the code snippet that needs to be removed. https://github.com/publiclab/plots2/blob/91b0a1bdb73aaa4a158fc37641bcf0ede0e4fec0/app/views/layouts/_header.html.erb#L184-L194

**Comment by georgepampalis** [comment]
Hello there! I just started learning how to use GitHub.

Could I try having a go at it ? 😮

**Comment by SidharthBansal** [comment]
Yes, go ahead

**Comment by jywarren** [comment]
We'd love your help!

**Comment by ver-kat** [comment]
Very well written issue! I'm looking for my first contribution and you've made it very appealing.

**Comment by jywarren** [comment]
Hi, @georgepampalis -- looks like you have some code pushed here: https://github.com/publiclab/plots2/pull/1915

@ver-kat -- we have additional issues here, too! https://publiclab.github.io/community-toolbox/#r=all

If none are as well formatted as this we can go in and find one and tidy it up! Thanks!

**Comment by jywarren** [comment]
And resolved in #1915 -- thanks to everybody!
