### ISSUE TITLE
Urls ending with * not working properly

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#1917]
### Please describe the problem (or idea)
If a person writes a research note with any link with an ending * say https://publiclab.org/tag/activity:*. Then it is not taking * into account

> What did you expect to see that you didn't?
I think, the person should be able to post the url with the ending * so that it can be clickable to the right destination. Selecting tags like this is an important feature in public labs.

### Please show us where to look
https://publiclab.org/wiki/activities first paragraph under the first image.

**Comment by SidharthBansal** [comment]
@jywarren I think we are using rdiscount for the markdowns. I am trying to find if there exists any method by which we can handle these types of custom urls. It will great for users to post links like this in their research notes or other places.

**Comment by jywarren** [comment]
Did this end up not being a problem? Thanks!

**Comment by SidharthBansal** [comment]
Yeah
