### ISSUE TITLE
Deleted activities still come on home page

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#1919]
### Please describe the problem (or idea)
If a person creates a research note and deletes it for some reason, then it still comes on www.publiclab.org/home .
Example
I have by mistake made a research note on public labs instead of localhost:3000 and then I deleted the note. See it appears on home page
![image](https://user-images.githubusercontent.com/20972099/34642524-5d72caf8-f33a-11e7-8679-ab0edb9ace89.png)
Testing Urls with *. 

> What did you expect to see that you didn't?
I expect not to see the deleted activities as a user.

### Please show us where to look

https://publiclab.org/ home

### What's your PublicLab.org username?
bansal_sidharth2996

**Comment by SidharthBansal** [comment]
Sorry, actually it is taking few minutes to change the home page. After that it is not showing. Sorry

**Comment by jywarren** [comment]
I believe this is due to cache expiry, which we're working on, but this makes it more urgent. Thanks!

**Comment by SidharthBansal** [comment]
Yeah, I saw swapnil is handling cache expiry in one PR. So,  there was not a need of this issue so I closed this issue. Shall I reopen it?

**Comment by jywarren** [comment]
I think we can leave closed; i'm publishing cache changes now and if it
doesn't work we can do a follow-up fix and publish today.

**Comment by SidharthBansal** [comment]
Ok
