### ISSUE TITLE
Navbar not working on the /post

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#1920]
### Please describe the problem (or idea)
The navbar links to drop down menus are not working on https://publiclab.org/post if a user is logged in. Example About, Get Involved and the menu containing the links to log out, log out from all devices etc.
I have tested this on localhost:3000/post and publiclab.org/post. I also tried on the private window.
> What did you expect to see that you didn't?
I expect to see these menus functional on the navbar

### Please show us where to look

https://publiclab.org/post

### Other information
I am using Mozilla Firefox on Ubuntu 14

**Comment by jywarren** [comment]
Hmm, that's weird -- I believe it may be due to jQuery being included
twice, but I thought we were on PublicLab.Editor v1.0.0 which isn't
supposed to suffer from that issue. Let me check again.

**Comment by jywarren** [comment]
Ah, this is fixed in master but hasn't been published to the site. Doing
that now.

**Comment by jywarren** [comment]
OK, this is fixed in stable; pushing to production site and closing: http://stable.publiclab.org/post

Thanks for catching this!
