### ISSUE TITLE
Stale pages listing at /wiki/stale

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1929]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

### Please describe the problem (or idea)

Let's display a list of wiki pages based on which have been untouched the longest. We currently list pages here: https://publiclab.org/wiki

You can see some stale pages here: https://publiclab.org/wiki?page=39

But we can write a new wiki page controller to be displayed at https://publiclab.org/wiki/stale

See this segment of code for the current wiki controller code for the "index" page at /wiki -- https://github.com/publiclab/plots2/blob/c20f81e35ec73c284d1b893fcd71eeba60e547dd/app/controllers/wiki_controller.rb#L290-L307

Great suggestion from @pdhixenbaugh!!

**Comment by Mujadded** [comment]
Hi, @jywarren by  `a list of wiki pages based on which have been untouched the longest` did you mean to sort all pages from oldest to news (the exact opposite of index page) in `https://publiclab.org/wiki/stale` . ( I am sorry if it's a stupid question  :disappointed: )

**Comment by jywarren** [comment]
I believe so, yes! So I think it could use the same template and possibly
same code, but ordered in reverse. Could that work?

**Comment by Mujadded** [comment]
Yes 😃  I am taking it then !

**Comment by Mujadded** [comment]
#1957

**Comment by Mujadded** [comment]
@jywarren I have open a pr for this in #1957

**Comment by jywarren** [comment]
Fixed by @Mujadded -- thank you!!!
