### ISSUE TITLE
Add ability to sort wiki pages alphabetically

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#193]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled.

This would need to be broken into smaller parts before becoming a `first-timers-only` issue. 

****

This is a new feature request for https://publiclab.org/wiki. This is similar to what has been requested for /tags in https://github.com/publiclab/plots2/issues/179. 

The wiki index page is here: 

https://github.com/publiclab/plots2/blob/master/app/controllers/wiki_controller.rb#L261-L271

We'll be adding a new conditional to the Rails controller code to look for a `?order=alphabetic` parameter in the URL, and sorting accordingly if it exists.

Making it a GET parameter, like https://publiclab.org/wiki?order=alphabetic

The current ordering is done here: https://github.com/publiclab/plots2/blob/master/app/controllers/wiki_controller.rb#L266

We can detect this via `params[:order]` in the controller, but first we should remove the `.order()` that already exists, and add it to an `if/else` conditional. So if our GET param equals `alphabetic`, we sort alphabetically. If it doesn't, we sort by the existing method:

```ruby
                       .order("node_revisions.timestamp DESC")
```

Sorting alphabetically should be:

```ruby
                       .order("node_revisions.title DESC")
```

We could then test this with a similar test to this one, but where we specify `order: 'alphabetic'` in the GET request: https://github.com/publiclab/plots2/blob/master/test/functional/wiki_controller_test.rb#L30-L35

**Comment by ananyo2012** [comment]
Closed by #1049
