### ISSUE TITLE
Not able to add subscriptions

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#1931]
### Please describe the problem (or idea)
On https://publiclab.org/subscriptions by entering the tags and clicking on the add it doesn't add the subscriptions but shows error

**Comment by SidharthBansal** [comment]
I think this is a part of #1846 issue

**Comment by jywarren** [comment]
Oof, good catch, thank you. We'll need to debug the route for this.

**Comment by jywarren** [comment]
Also, if you're interested in preparing this or some of your other recent issues for others to take up, there's some guidance on preparing first-timer issues here: https://publiclab.github.io/community-toolbox/#r=all

Thanks so much!

**Comment by jywarren** [comment]
(and just ping me if you feel you want to label one of these for first timers, etc)

**Comment by SidharthBansal** [comment]
yeah thanks

**Comment by Diksha2008** [comment]
@jywarren Can I resolve this?

**Comment by jywarren** [comment]
Please - that would be great -- Sidharth, does that sound good? Thanks!

**Comment by SidharthBansal** [comment]
@Diksha2008 go for it
