### ISSUE TITLE
View All link on wiki pages

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#1932]
### Please describe the problem (or idea)
When clicking on the View all link on the left sidebar to know all the contributor, it shows wrong or no contributors even though there exist many contributors on the wiki page.
For example, https://publiclab.org/wiki/plots-staff on the left sidebar shows that atleast there are 3 contributors with their name but on the https://publiclab.org/contributors/plots-staff it shows no contributors.
See
![image](https://user-images.githubusercontent.com/20972099/34692000-8e18c33c-f4e4-11e7-823b-e52d08fd0f99.png)
and 
![image](https://user-images.githubusercontent.com/20972099/34692015-9840def8-f4e4-11e7-87f2-161de4bce36e.png)

Also, I checked one other page https://publiclab.org/wiki/lego-spectrometer it shows different names on both the pages. I expect that the recent contributors must be present inside the contributors page at https://publiclab.org/contributors/lego-spectrometer

![image](https://user-images.githubusercontent.com/20972099/34691970-6fd602a4-f4e4-11e7-8b04-5e4dc353de57.png)
and 
![image](https://user-images.githubusercontent.com/20972099/34691983-7befeca8-f4e4-11e7-9dc5-2f75fdbff0bd.png)

One more thing, we can use pluralise method on this page for correct grammar
![image](https://user-images.githubusercontent.com/20972099/34692338-dd4643ac-f4e5-11e7-8436-94dae020ec2d.png)
![image](https://user-images.githubusercontent.com/20972099/34692399-05601a66-f4e6-11e7-9231-6e56f20b384f.png)
I have not checked the files yet. Just was trying to understand the publiclab.org

**Comment by jywarren** [comment]
I believe this should say "Contributors for the topic" somehow more
clearly. Because it's contributors on the tagname, not the wiki page.
You're right, it's ambiguous! Can we rename it for clarity?

**Comment by SidharthBansal** [comment]
Yeah... Actually, I thought for a moment that it is the tag name but I got a little confused, what exactly it is. As the just next link named "View all" points to /contributors/name_of_wiki_page it makes more ambiguous to find that this is a bug. I think it should be "View all contributors for this wiki page" or something like this.

**Comment by SidharthBansal** [comment]
Yeah for sure. I will make a first-timer-issue for it soon

**Comment by jywarren** [comment]
I think it was based on the idea that a wiki page is likely to have a URL
path that matches a tag name, which is not a strong assumption however. The
hope is also just that we show some people who've posted related work
recently!

**Comment by SidharthBansal** [comment]
@jwarren also there are grammar issues here
![image](https://user-images.githubusercontent.com/20972099/34695822-4e7ceea2-f4f2-11e7-9ae5-8ee318bee1f9.png)
See 1 view"s" instead of 1 view

**Comment by SidharthBansal** [comment]
@jywarren can you please put tags to #1936.
Thanks

**Comment by jywarren** [comment]
Done, shall we close this one then? Thanks! Great work!

**Comment by SidharthBansal** [comment]
@jywarren What about the not having condition for pluralisation in the locales? Does it needs to be tackled later on??

**Comment by jywarren** [comment]
I'm not that familiar with it, but I'd be inclined to let pluralization be as it is. There is some guidance here, though: https://robots.thoughtbot.com/pluralizing-rails-i18n-translations

**Comment by jywarren** [comment]
Can we close this issue if we've broken it up into sub-parts, then? Thank you!
