### ISSUE TITLE
a UI for inputting social media usernames into your profile

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1933]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

We can now profile-tag social media handles, with tags like `twitter:jywarren` -- but there's no good UI for doing so; you just have to know to do it. Let's make a nice UI!

Perhaps based on a JavaScript `prompt()`. But could we add a button like `Link social media` and ask people to input `twitter:jywarren` or `instagram:unterbahn` in the prompt text? 

https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt

**Comment by jywarren** [comment]
@ebarry - broke this out of one of yours re: social media and profiles. Nice and discrete!

**Comment by ankitbhardwaj78** [comment]
@jywarren can i take this issue??

**Comment by jywarren** [comment]
Yes please!!
