### ISSUE TITLE
Change text on left sidebar

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#1936]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you :gift_heart:

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!
:thinking: What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.
#### Please describe the problem

Change the "View all" to "Contributors for the topic" on the left sidebar on the wiki pages.

:clipboard: Step by Step

:raising_hand_woman: Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

:memo: Change the text in the following lines
https://github.com/publiclab/plots2/blob/9e0f5e6ba58b72390cb7772c9ebbb088d672d4a5/app/views/sidebar/_related.html.erb#L51-L51
and
https://github.com/publiclab/plots2/blob/9e0f5e6ba58b72390cb7772c9ebbb088d672d4a5/app/views/sidebar/_related.html.erb#L62

:floppy_disk: Commit your changes

:twisted_rightwards_arrows: Start a Pull Request.

:checkered_flag: Done Ask in comments for a review :)

:thinking::question: Questions?

Leave a comment below!

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seem stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!
Thank you!

Your help makes Public Lab better! We deeply appreciate your helping refine and improve this site.

**Comment by ankitbhardwaj78** [comment]
can i take this issue..

**Comment by Mujadded** [comment]
@ankitbhardwaj78 have you started working on it ? or do you have any pull request? if not can I start it?

**Comment by jywarren** [comment]
Hi, all! Thanks please do take this up and post a PR -- I think @ankitbhardwaj78 has first take on it if they're interested. But there are PLENTY of issues to go around! Please check out https://publiclab.github.io/community-toolbox/#r=all for more -- much appreciated, thanks everybody!

**Comment by jywarren** [comment]
Also, perhaps we should have it say "Contributors on this topic" instead of "Contributors for the topic" -- just a small change but much appreciated!

**Comment by ankitbhardwaj78** [comment]
@Mujadded  i have created the PR ..

**Comment by Paarmita** [comment]
@SidharthBansal Is this issue still open?

**Comment by SidharthBansal** [comment]
@ankitbhardwaj78 is already working on it. . But there are PLENTY of issues to go around! Please check out https://publiclab.github.io/community-toolbox/#r=all for more -- much appreciated, thanks @Paarmita !
