### ISSUE TITLE
Chapter pages: Move powertagged information from leftsidebar into tabs

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#194]
The left sidebar events listing on chapter pages is too far down below other leftsidebar items like mailing lists to be effective. Proposal: the event powertag (e.g. "events:gulf-coast") should create a new tab that is centrally located on the page (e.g. on http://publiclab.org/wiki/gulf-coast next to Overview, Research, Wiki pages).

This is part of the Customer2Community initiative because we need the local events links to be really clear as we welcome new customers to participate in existing chapters. 

CC @steviepubliclab

**Comment by jywarren** [comment]
That sounds good, but unfortunately those tabs are not present on every
page. We could do it:

* *if* those tabs are present, and/or
* we could have adding the events powertag auto-add the extra tabs?

**Comment by ebarry** [comment]
Either of these ways sounds good to me. I think it might be easier to have the events powertag auto-add the extra tabs.

**Comment by steviepubliclab** [comment]
I like this as a function chapters can add on to their page to make them more "robust." both options sound good Jeff.

**Comment by jywarren** [comment]
I'd like to close this as something we've achieved (with even greater flexibility) using inline tags: https://publiclab.org/wiki/power-tags#Inline+power+tags -- but open to re-evaluating, please re-open if you want to refine this!
