### ISSUE TITLE
 Change text of tag subscription email to something friendlier

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1952]
https://github.com/publiclab/plots2/blob/master/app/mailers/subscription_mailer.rb#L44

Says "New tag added on #{node.title}" -- but maybe something like: 

`@person added ______ to the [spectrometry] topic`

@ebarry ideas on the wording here?

**Comment by membrq** [comment]
Can I claim when the wording is finalized?

**Comment by jywarren** [comment]
That'd be great, thanks!!!

**Comment by jywarren** [comment]
This is solved in https://github.com/publiclab/plots2/pull/2407 !

**Comment by jywarren** [comment]
@membrq we have a range of other issues you're welcome to at http://publiclab.github.io/community-toolbox#r=all !
