### ISSUE TITLE
Adding images and decription to tweets

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#1958]
Hi, this is a [first-timers-only](https://github.com/publiclab/plots2/projects/2) issue. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

# The Problem

Currently the **tweets** on [PublicLab account ](https://twitter.com/PublicLab)  have format  : 
<img width="588" alt="screen shot 2018-01-11 at 6 25 28 pm" src="https://user-images.githubusercontent.com/14952645/34826552-fde0b91c-f6fc-11e7-8569-f7da50890440.png">

The problem is that the **image is not shown** on tweets and the **description of the shared article** is not shown . 

Example :  For research note ,   [https://publiclab.org/notes/cutlan/01-09-2018/kilimanjaro-citizen-science-1](https://publiclab.org/notes/cutlan/01-09-2018/kilimanjaro-citizen-science-1) ,  the tweet is [this](https://twitter.com/PublicLab/status/950784615513493507) . 

# Solution 

We need to change the tweets to this **format** : 

<img width="594" alt="screen shot 2018-01-11 at 2 32 01 am" src="https://user-images.githubusercontent.com/14952645/34826725-bfec845a-f6fd-11e7-8510-e92f00d5d818.png">

The tweets are generated from the **recipe** (Learn more about recipes from [here](https://ifttt.com/discover))  [https://ifttt.com/applets/66362400d-rss-feed-to-post-a-tweet-with-image-and-url](https://ifttt.com/applets/66362400d-rss-feed-to-post-a-tweet-with-image-and-url) , which tweets whenever there is **change in the RSS feed of Publiclab.com site** [https://publiclab.org/feed.rss](https://publiclab.org/feed.rss) .

We need to change the **format of our RSS Builder** , [https://github.com/publiclab/plots2/blob/master/app/views/notes/rss.rss.builder](https://github.com/publiclab/plots2/blob/master/app/views/notes/rss.rss.builder) to produce correct RSS Feeds .

The **correct RSS feed** has format similar to this  , [https://sagarpreet-chadha.github.io/feed.rss](https://sagarpreet-chadha.github.io/feed.rss)  (this is a static feed only for testing).

Also , you can verify that the generated xml is of correct format from this site , [https://validator.w3.org/feed/check.cgi](https://validator.w3.org/feed/check.cgi) .

1.) Basically to add **images** and **description** , we need to add this : 
`<![CDATA[
  <img src="http://img02.mini.abroad.imgcdc.com/english/photos/fun/90/20170711/1017495_339353.jpg.680x425.jpg" alt="Smiley face">         
]]>`
inside the `<description>`  tag , https://github.com/publiclab/plots2/blob/76da53269e42da218178d3697e11b50bfacf42dc/app/views/notes/rss.rss.builder#L20 

2.)We need to remove the image tag inside `<item>` tag as `<image>` tag is not valid inside `<item>` tag .
**Remove** :  https://github.com/publiclab/plots2/blob/76da53269e42da218178d3697e11b50bfacf42dc/app/views/notes/rss.rss.builder#L19

3.) Format of `<author>` tag is incorrect currently . The correct format is 
`<author> email-id (User-name) </author>` .
https://github.com/publiclab/plots2/blob/76da53269e42da218178d3697e11b50bfacf42dc/app/views/notes/rss.rss.builder#L15

### Feel free to ask any doubt regarding the issue ! Thank you !

# Steps to Fix 

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ]  set up a repository locally following the README instructions, and make sure that all tests pass
 - [ ] try to fix the issue following the steps above, but even before you're done, you can:
 commit your changes and start a pull request (see contributing to Public Lab software) but mark it as "in progress" if you have questions or if you haven't finished
- [ ]  alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see [https://publiclab.org/wiki/developers](https://publiclab.org/wiki/developers)) or go to the [chatroom](http://publiclab.org/chat) if you have questions, and take a look at our [first-timers landing page for more information!](https://github.com/publiclab/plots2/projects/2)

**Comment by jywarren** [comment]
This is a multi-step issue, but we're here to help! Please open a pull request with your initial code and feel free to ask for help - we can look it over and provide support.

**Comment by Mujadded** [comment]
Can i claim it 😀 ?

**Comment by sagarpreet-chadha** [comment]
@jywarren , is it live ?

**Comment by jywarren** [comment]
Not yet - it didn't quite make it by the Friday night update. I'll probably
run an update today too, though! Let's check back in!

**Comment by jywarren** [comment]
OK, it's live now!

**Comment by sagarpreet-chadha** [comment]
*https://publiclab.org/feed.rss* seems to be not working . Looking into it .

**Comment by jywarren** [comment]
server log:

```
Completed 500 Internal Server Error in 58ms (ActiveRecord: 10.5ms)

ActionView::Template::Error (undefined method `main_images' for #<Node:0x007f6eb3869240>
Did you mean?  main_image
               main_image_id):
     8:    @notes.each do |node|
     9: 
    10:      body = node.latest.render_body
    11:      body = "<p><![CDATA[ <img src='"+node.main_images.path(:default)+"' alt='"+node.main_image.title+"' > ]]></p> " + node.body if node.main_image
    12: 
    13:      xml.item do
    14:        xml.title       node.title
  app/views/notes/rss.rss.builder:11:in `block (3 levels) in _app_views_notes_rss_rss_builder__1936050186063288318_50813960'
  app/views/notes/rss.rss.builder:8:in `block (2 levels) in _app_views_notes_rss_rss_builder__1936050186063288318_50813960'
  app/views/notes/rss.rss.builder:3:in `block in _app_views_notes_rss_rss_builder__1936050186063288318_50813960'
  app/views/notes/rss.rss.builder:2:in `_app_views_notes_rss_rss_builder__1936050186063288318_50813960'
  app/controllers/notes_controller.rb:309:in `block (2 levels) in rss'
  app/controllers/notes_controller.rb:307:in `rss'
```

**Comment by jywarren** [comment]
easy fix! and we should make a functional test for this :-)

**Comment by jywarren** [comment]
Sorry, TravisCI is stalled for some hours ... waiting for that to come back before publishing!

**Comment by jywarren** [comment]
The feed is now working: https://publiclab.org/feed/liked.rss

I just enabled the IFTTT recipe too. Fingers X!

**Comment by jywarren** [comment]
And i posted a photo and liked it -- this should trigger the script! https://publiclab.org/notes/warren/01-18-2018/pre-order-the-community-written-pocket-guide-to-grassroots-mapping

**Comment by jywarren** [comment]
It didn't work! Not sure why:

![screenshot 2018-01-17 at 8 14 58 pm](https://user-images.githubusercontent.com/24359/35075806-2dfbb690-fbc3-11e7-9457-676894ae4b76.png)

**Comment by jywarren** [comment]
Error: 

```
EntryAuthor
warren
EntryContent
<p><![CDATA[ <img src='https://publiclab.org/system/images/photos/000/023/198/medium/26068242_2000536900161090_8104197322948214784_n.jpg' alt='' > ]]></p>This 3.5 x 5.5 inch illustrated booklet was printed at the AS220 community print shop by Jacque Bidon, and includes 64 pages of illustrated community-developed guidance and tips on balloon and kite mapping. It was [collaboratively written](<a href="https://publiclab.org/notes/warren/07-01-2017/collaboratively-write-the-new-pocket-guide-to-grassroots-mapping">https://publiclab.org/notes/warren/07-01-2017/collaboratively-write-the-new-pocket-guide-to-grassroots-mapping</a>) by dozens of Public Lab community members. Shown is the final mockup -- the final print will be in red ink. Available for pre-order now at $10 each! We expect to ship in February 2018: <a href="https://store.publiclab.org/products/pocket-guide-to-grassroots-mapping">https://store.publiclab.org/products/pocket-guide-to-grassroots-mapping</a> ![image description](<a href="https://publiclab.org/system/images/photos/000/023/199/large/download.jpg">https://publiclab.org/system/images/photos/000/023/199/large/download.jpg</a> "download.jpg")
EntryImageUrl
http://ifttt.com/images/no_image_card.png
EntryPublished
January 17, 2018 at 08:13PM
EntryTitle
Pre-order the community-written Pocket Guide to Grassroots Mapping
EntryUrl
https://publiclab.org/notes/warren/01-18-2018/pre-order-the-community-written-pocket-guide-to-grassroots-mapping
FeedTitle
Recent research notes on PublicLab.org
FeedUrl
https://publiclab.org/feed.rss
```

**Comment by jywarren** [comment]
I've turned the IFTTT script off for now! I wonder what happened?

**Comment by jywarren** [comment]
Ooh, do we need an "enclosure" line? As per https://sagarpreet-chadha.github.io/feed.rss

`<enclosure url="http://www.publiclab.org/system/images/photos/000/023/122/medium/PIC2.jpg" length="78645" type="image/jpeg" />`

**Comment by jywarren** [comment]
This looks right, but I'm not sure how to add an `<enclosure>` tag to `rss.builder`

**Comment by jywarren** [comment]
OK i got `url=` but not sure if we need type or length -- ? Can we test in your test setup, @sagarpreet-chadha ?

**Comment by jywarren** [comment]
I'll be able to re-activate using this: https://ifttt.com/applets/70744657d-rss-feed-to-post-a-tweet-with-image-and-url

**Comment by sagarpreet-chadha** [comment]
The image is shown due to `<![CDATA[ <img src='`  and not `<enclosure>`  tag ! 
We may remove that enclosure tag .

Tested this here : https://github.com/sagarpreet-chadha/sagarpreet-chadha.github.io/blob/d044a8c9a7124909dba78e0e2570b65a35f6d96a/feed.rss#L154

**Comment by sagarpreet-chadha** [comment]
@jywarren , you were right it gets auto-truncated 😄 !!

**Comment by jywarren** [comment]
Reopening -- one more thing, it tries to post an image even if there isn't an enclosure tag... Not sure how to stop this! 

We may need to use a default image? But that's not a great solution. 

@ebarry @steviepubliclab could we use someone's profile picture?

**Comment by jywarren** [comment]
Are you totally sure about enclosure? I think we have to do more testing. And to figure out how to not post an image if there isn't one.

**Comment by jywarren** [comment]
This is a tough one! I disabled the ifttt script for now. Thanks for working on it!

**Comment by sagarpreet-chadha** [comment]
I agree this is indeed a tricky one , learned a lot though . Thank you !

**Comment by jywarren** [comment]
OK, i've hooked it up to https://twitter.com/pl_testing and
https://gist.github.com/jywarren/055bf4471dbdfff6a1ebd21bf15c3c8f; will add
a new item soon and see if it works.

**Comment by jywarren** [comment]
Hmm, i can't seem to get this working effectively. Can you double check that `enclosure` is definitely not it?

**Comment by sagarpreet-chadha** [comment]
Also ,  [https://gist.github.com/jywarren/055bf4471dbdfff6a1ebd21bf15c3c8f](https://gist.github.com/jywarren/055bf4471dbdfff6a1ebd21bf15c3c8f) file shows following errors according to [https://validator.w3.org/feed/check.cgi](https://validator.w3.org/feed/check.cgi) .

<img width="1396" alt="screen shot 2018-01-25 at 11 08 35 pm" src="https://user-images.githubusercontent.com/14952645/35403233-1fc9d06c-0225-11e8-9e2f-598d87137235.png">

I think resolving these and removing `enclosure tag` may do the job .

**Comment by sagarpreet-chadha** [comment]
Also @jywarren , i was thinking of not using the IFTTT recipes as these are not very flexible . I was thinking of using [twitter gem](https://github.com/sferik/twitter) , it has a very easy function `client.update()` to post on twitter . And we can post on twitter almost instantly (at the same time when the author post on publiclab.org site) and hence not waiting for IFTTT recipe to to run . However it might be a big project .
What do you think ?  😄

**Comment by jywarren** [comment]
Hi, you know, I think that the twitter gem may be a way forward. But it does sound like a big project, and after all we have an API and RSS feeds specifically for integration -- i don't (architecturally) much like the idea of baking additional channels of publication into the core code. 

I'd like to give this another attempt. Let's, for now, assume we can fall back to a profile picture if that exists, and the Public Lab logo (publiclab.org/logo) if /that/ doesn't exist. 

So the remaining problem is how to get the image to appear in Twitter. 

Actually while I see your test looks good, it only demonstrates that the image makes it into the RSS feed and is RSS compliant. We also need to know that the IFTTT feed is reading either the image from the item content, OR from the `<enclosure>` tag. 

One clue, however, is that your original demonstration that got all the way to Twitter, included `<enclosure>` WITH a `length` attribute, which my test lacked. We could [think about attaching file size](https://stackoverflow.com/questions/14803185/paperclip-attachment-file-size) but it's complicated. 

Let's see if we can narrow down the problem using your original demo. Can you do your original test (https://sagarpreet-chadha.github.io/feed.rss) using `<enclosure>` without `length`, and if that breaks the system, we know that's the problem?

Thanks -- this is complex and I appreciate your time on it!

**Comment by jywarren** [comment]
It could also be the `type="image/jpeg"` part of `<enclosure>` -- testing this idea here: https://publiclab.org/feed-tmp.rss + https://twitter.com/pl_testing

**Comment by sagarpreet-chadha** [comment]
Hi , working on it .

Also @jywarren  , i was thinking of an alternative and thought of this : 

1.) Use [this recipe](https://ifttt.com/applets/XE8XJmSq-post-rss-feed-items-to-facebook) to post on FB page , to get posts in the format (facebook page): 
<img width="766" alt="screen shot 2018-01-28 at 2 29 54 am" src="https://user-images.githubusercontent.com/14952645/35476284-409bbd3c-03d3-11e8-8c69-ed86020ab86a.png">

2.)And then using [this recipe](https://ifttt.com/applets/263954p-autopost-from-facebook-page-to-twitter) , to post on Twitter (this is my profile , image is handled automatically and also description comes automatically) : 
<img width="593" alt="screen shot 2018-01-28 at 2 30 06 am" src="https://user-images.githubusercontent.com/14952645/35476299-6b62aad0-03d3-11e8-85fb-52198fc12123.png">


What do you think ?

**Comment by jywarren** [comment]
hmm, it's not `type` -- i checked that using the `feed-tmp.rss` feed and `pl_testing` account. Testing `length` now.

**Comment by jywarren** [comment]
Oh, cool -- maybe that can work! Does the Facebook/Twitter hybrid handle when only some posts have images?

**Comment by jywarren** [comment]
yeah, nope -- `length` didn't help. I'm going to try both at once, but yeah... https://twitter.com/pl_testing

**Comment by sagarpreet-chadha** [comment]
Yes @jywarren , Unfortunately when the FB post **does not** has image then this recipe is working [https://ifttt.com/applets/10891p-share-facebook-page-updates-on-twitter](https://ifttt.com/applets/10891p-share-facebook-page-updates-on-twitter)  and when FB post **has an image** then this [https://ifttt.com/applets/263954p-autopost-from-facebook-page-to-twitter](https://ifttt.com/applets/263954p-autopost-from-facebook-page-to-twitter) is working fine . 

Also in FB post , if we give only the **link of node** in the RSS , then the FB automatically fetches the image (if any) .

**Comment by sagarpreet-chadha** [comment]
I think this combination of recipes may work ! What do you think ?

Also mine **RSS Feed to Twitter** is not working , so i am not able to test the RSS feed . Trying to resolve this ! Thanks 👍
