### ISSUE TITLE
Move display of tags to more prominent location on content pages

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#1960]
### Please describe the problem (or idea)

The idea is to move tags up higher on the page. Some reasons: 

* tags are the main way we organize related content on the site
* to help people realize that tags are actually clickable (recently some long time Public Labbers related to me that they had never known tags even existed)
* to encourage people to add tags, and by doing so organize related content on PublicLab.org
* last but not least, our pro bono consultant from Autodesk recommended doing so https://publiclab.org/wiki/ui

Some options for where to move them: 

* under the line with tabs for view, edit, comment,  
<img width="500" alt="screen shot 2018-01-11 at 2 33 28 pm" src="https://user-images.githubusercontent.com/161439/34843412-6ffa7bd0-f6dc-11e7-913a-3cb7378b0cbe.png">

* in the sidebar, replacing where currently we show "Related and Recent content"
<img width="200" alt="screen shot 2018-01-11 at 2 36 16 pm" src="https://user-images.githubusercontent.com/161439/34843578-d3d9a41e-f6dc-11e7-86d9-374847dab8f4.png">

**Comment by SidharthBansal** [comment]
@ebarry May I take this?
I think it will be better to have tag listing below the tabs. That will not compromise with the features of the sidebar.

**Comment by SidharthBansal** [comment]
@jywarren what do you suggest?

**Comment by jywarren** [comment]
I think that for the time being we have to hold off on this until we git a bit more design input -- would you be willing to try another issue further down? Thank you!

**Comment by ebarry** [comment]
Could we try a version where the line of tags is shown "under the line with tabs for view, edit, comment" ? Can we identify some contemporary UX/UI patterns to base our design on?

**Comment by jywarren** [comment]
Let's post some screenshots of layouts we like, either examples from other
sites we like, or mockups.

Here's a working space with some cut-up interface pieces if you want to
make a mockup:
https://docs.google.com/presentation/d/1TCZoTfuhamRVrUak8aDgqJAwSgyhRtZg2Pgacl2_4zc/edit?usp=slides_home&ths=true

**Comment by jywarren** [comment]
I kind of like the sidebar option, and we are thinking of revising the sidebar to be much more minimal in #1706. Here are some mockups from that template:

![screenshot 2018-01-24 at 11 42 59 am](https://user-images.githubusercontent.com/24359/35344693-bef3612e-00fb-11e8-978a-f110e9268e78.png)

![screenshot 2018-01-24 at 11 39 05 am](https://user-images.githubusercontent.com/24359/35344698-c2c01eaa-00fb-11e8-87d0-eb7fd2c9bf4a.png)

**Comment by ebarry** [comment]
(HI @jywarren in the three column layout above it seems like you are proposing to use a righthand column for the tags -- is this the same thing you call a sidebar? Just trying to figure it out, thanks!)

**Comment by jywarren** [comment]
I was thinking a 2-column layout with the "sidebar" on the right, closer to Siyuan's mockup in this post: 

https://publiclab.org/notes/siyuan/06-12-2017/a-questions-page-to-encourage-discussions-through-better-ux#c17461

But just trying out some ideas!

**Comment by SidharthBansal** [comment]
One thing I would like to suggest is, on the whole website we should have sidebars either on right or on left. When a user will navigate from one page to other and finds some sidebars are on the right while other on the left it really looks ugly to me. Even though the pages individually looks great.
Thanks

**Comment by jywarren** [comment]
After https://github.com/publiclab/plots2/issues/3091 we can re-start work on this, using this mockup:

![image](https://user-images.githubusercontent.com/24359/37424326-8ff2290c-2796-11e8-9620-54c6d5667d62.png)

I think this should go into a file in `app/views/sidebar/_tagging.html.erb` to largely replace `app/views/sidebar/_related.html.erb`

Any help appreciated!

**Comment by jywarren** [comment]
This is now complete in #3127 ! Thank you!
