### ISSUE TITLE
Broken link in API.md

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#1963]
https://publiclab.org/feed/authorname.rss is broken in the API.md file

**Comment by SidharthBansal** [comment]
@jwarren I found that it related to users#rss 
Can you help me  with this? I don't know rss.
Thanks

**Comment by Mujadded** [comment]
@SidharthBansal and @jywarren I have kinda saw the cause of that error and fixed it in #2009 . I tested it in my local setup it was working fine. Maybe you guys can check if it logically correct 😄 ?

**Comment by SidharthBansal** [comment]
@Mujadded yeah it was just an if-else error. Thanks for the catch.

**Comment by jywarren** [comment]
Awesome great teamwork!
