### ISSUE TITLE
Moderation(ban) links shown to a normal user are not required

### ISSUE THREAD

**Issue by ViditChitkara** [publiclab/plots2#1972]
### Please describe the problem (or idea)

When a normal user views contributors' list (/people), there are moderation links which actually have no use to a normal user.
![plots-people-1](https://user-images.githubusercontent.com/22616017/34885818-2935cc84-f7e7-11e7-867e-b59673e76177.jpg)

### Expected Behavior

The column named moderation (consisting links to ban a user) should be visible only to admin or moderator and not to a normal user.
![plots-people-3](https://user-images.githubusercontent.com/22616017/34886385-d56d071e-f7e8-11e7-8de7-8a31572c49ba.jpg)
However, the links are not shown when a user is not signed in as shown above.

### Please show us where to look

https://publiclab.org/people

### What's your PublicLab.org username?

vidit

**Comment by Diksha2008** [comment]
I think this is same as the issue #1918

**Comment by ankitbhardwaj78** [comment]
@ViditChitkara can i take this issue??

**Comment by ViditChitkara** [comment]
Go ahead @ankitbhardwaj78!!! We are happy to help!

**Comment by Diksha2008** [comment]
@ViditChitkara I totally agree with you!
Maybe @jywarren would have more thoughts on it!

**Comment by jywarren** [comment]
Fixed in #1990! Thanks, all!
