### ISSUE TITLE
Unnecessary Code in Routes.rb

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#1975]
The following line needs to be removed, a delete action does not have a get HTTP verb
https://github.com/publiclab/plots2/blob/46c129e6f0f2b4f99c3a982e3d9b58f1b5fc7573/config/routes.rb#L102

**Comment by jywarren** [comment]
Shall we replace it with a `put` so this button still works? And i think we can set the method on that button somehow, can't we? https://github.com/publiclab/plots2/blob/01fac7cda6ab3df0ee9ba492f489edeef741ece9/app/views/wiki/_header.html.erb#L73

**Comment by Mujadded** [comment]
@jywarren and @SidharthBansal This issue was already addressed #1967  and fixed in a pull request #1968  by me a day before, but this was again reported. Please check

**Comment by SidharthBansal** [comment]
@Mujadded no, I have carefully read your issue before submitting this one. This is not a duplicate issue.
Your issue removes wiki#stale but here it is wiki #delete

**Comment by Mujadded** [comment]
@SidharthBansal oh sorry, I read it wrong, the naming confused me . Sorry again and thank you for the correction.

**Comment by SidharthBansal** [comment]
@jywarren I managed to delete the line from the routes without compromising the functionality of the button by changing the link_to helper.
It is working fine.I dont think we need put. Do we??
@Mujadded No problem.

**Comment by jywarren** [comment]
Sounds great!!!
