### ISSUE TITLE
Add comments to search

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1977]
Our new search system is real nice! We have basics of comment search built:

https://github.com/publiclab/plots2/blob/01fac7cda6ab3df0ee9ba492f489edeef741ece9/app/services/typeahead_service.rb#L35-L46

But it needs to be integrated. 

We'll need a `search_comments` function similar to this one:

https://github.com/publiclab/plots2/blob/01fac7cda6ab3df0ee9ba492f489edeef741ece9/app/services/typeahead_service.rb#L130-L143

which uses the above `comments` method instead of `notes`...

Then we can add a line after this one to include comments into search results!

https://github.com/publiclab/plots2/blob/01fac7cda6ab3df0ee9ba492f489edeef741ece9/app/services/typeahead_service.rb#L90-L92

I think that should work... let's try it out!

**Comment by ViditChitkara** [comment]
Shall I try?

**Comment by jywarren** [comment]
Sure, that'd be great! Thanks!
