### ISSUE TITLE
An amazing week -- thank you all!

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1981]
Hi, everybody - i'm just opening an issue to say THANK YOU to everyone who's been coding here recently. ([cross-post on the Public Lab site](https://publiclab.org/notes/warren/01-12-2018/an-amazing-week-of-software-contributing-at-public-lab))

This is one of the most remarkable weeks we've ever had in this project. I had a pretty busy week and was not able to help with every detail over the past few days, but many recent newcomers to the project have really stepped up into leadership roles -- going well beyond just solving problems, to identifying new issues, cleaning up code, tackling bigger and much more complex projects, and even creating new issues to welcome newcomers into the project. What an amazing group!

Just a few highlights this week:

* #1810 Blog page subscribe notification and button by @acioffi21
* #1913 - Full text search in navbar -- of user bios, wiki and note full body text, high speed, by @icarito and me
* #1872 per-author tag page listings like http://publiclab.org/tag/replication:*/author/warren by @SidharthBansal
* #1953 Inline people maps `[map:people:41,-91]`
* #1957 Stale pages listing by @Mujadded at http://publiclab.org/wiki/stale
* #1935 Comments into answers by @Gauravano
* #1959 Inline wiki page grids with `[wiki:_____]` by @Diksha2008
* #1916 major integration tests of routes by @sagarpreet-chadha 
* more by @rishabhptr (#1815), @membrq (#1955), and @georgepampalis (#1915)

Take a look in GitHub Pulse: https://github.com/publiclab/plots2/pulse/weekly

> Excluding merges, 11 authors have pushed 30 commits to master and 37 commits to all branches. On master, 83 files have changed and there have been 996 additions and 2,251 deletions.

Finally, thanks to everyone who opened and commented on issues and PRs -- this is just as critical! @ViditChitkara @guolivar @ebarry @steviepubliclab 

What a week! This is bigger than many months of work, and it's just the beginning. 

We'll probably publish this tonight or over the weekend, and you'll all be able to see your new features on the live site. Thanks and keep up the great work!

-- Jeff

**Comment by jywarren** [comment]
I wanted also to ask if anyone's interested in joining our reviewers group -- we'd like to start using this more a bit as there are lots of PRs and we could use the help in troubleshooting and kindly welcoming new people in and helping their PRs get ready -- @publiclab/reviewers 

If you'd like to join this group of "kind welcoming helpers" -- ping me here and I'll add you!

**Comment by SidharthBansal** [comment]
@jywarren I want to

**Comment by Gauravano** [comment]
Jeff I also want to join

**Comment by jywarren** [comment]
Invited you both to the group!

**Comment by jywarren** [comment]
Ah, @seafr you too! I tried to comb through recent comments but I don't know a good view for that actually. 

There is a list of everyone who's committed code at the bottom of this page, but it's not including issue creators, reviewers, other folks who make this community work: 

https://publiclab.github.io/community-toolbox/

But we're trying to solve that too! https://github.com/publiclab/community-toolbox/issues/14 :-)

**Comment by Mujadded** [comment]
@jywarren Can I join join too :) ?

**Comment by ViditChitkara** [comment]
@jywarren I want to join too!

**Comment by sagarpreet-chadha** [comment]
@jywarren I also want to join 👍

**Comment by Diksha2008** [comment]
@jywarrenI would like to thank you as well for always helping out! Contributing to this project has been truly worthwhile for me! 
Also, I would like to join the reviewers group too! :)

**Comment by seafr** [comment]
@jywarren Don't worry about that "issue", I'm learning a lot anyway . Just add me to the reviewers group please.

**Comment by sagarpreet-chadha** [comment]
I agree with @Diksha2008 and @seafr , the learning rate has been exponential for me as well . Thank you !!

**Comment by SidharthBansal** [comment]
I also agree with you three. It is a great experience learning a lot here. Thanks a lot !!!

**Comment by Gauravano** [comment]
Well said by all of you guys, Also, I want to give credit to the amazing Publiclab team for their support which is the reason we love to work on each issue with more enthusiasm.

**Comment by jywarren** [comment]
Also notice @siaw23 and @StlMaris123 plugging in again -- welcome back, you two! Great to see you!

OK, folks, thanks and I'm sending invites. I'm going to work a bit on guidance for how to be a helpful reviewer, but the basics are:

* always be kind and respectful! (remember our [Code of Conduct!](https://publiclab.org/conduct)
* help people to become better coders and don't make them feel bad
* encourage people to open a PR with their work even if it's not finished
* go through recent PRs to help people who are stuck
* use emojis 🎉 

Some specific things you can do:

* add links to relevant lines of code to help people see where to start, or for an example of a similar feature
* suggest writing a test to *protect your work* from future issues
* tag things as `break-me-up` if it's possible to do a project in separate simpler parts

I'm sure there's lots more, but these are a few things I'm sure you've seen me do around the project. I'd love some help, and thank you for your enthusiasm!

**Comment by jywarren** [comment]
Oh, and if you've completed a PR or two, do consider creating a new `first-timers-only` issue to welcome someone else into our community! There's guidance on this further down on community toolbox:

https://publiclab.github.io/community-toolbox/#r=all

👍 💯 🎉 🎈

**Comment by namangupta01** [comment]
@jywarren I also want to join!

**Comment by rishabhptr** [comment]
@jywarren I would love to join too :smile:

**Comment by jywarren** [comment]
Adding you both too. I'm starting to compile more guidance on being a reviewer -- Some resources now at:

* https://publiclab.org/notes/warren/11-08-2016/help-public-lab-s-software-grow-by-joining-a-supportive-team
* https://publiclab.org/developers

**Comment by membrq** [comment]
I’d love to join too! Have never been a reviewer before but looking forward to learning. Thanks for the resources @jywarren!

**Comment by jywarren** [comment]
Fantastic!!!
