### ISSUE TITLE
Lead Wiki pages on Power tag search

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#1982]
Urls like www.publiclab.org/tag/balloon-mapping* end up in showing it leads to no wiki pages but balloon-mapping may be a wiki page.
![image](https://user-images.githubusercontent.com/20972099/34898168-a1a2383a-f817-11e7-8c2f-851228d423f6.png)
![image](https://user-images.githubusercontent.com/20972099/34898187-b0a26562-f817-11e7-9e9c-9e569b1a187a.png)
Refer #1872

**Comment by SidharthBansal** [comment]
@jywarren Would I truncate the power tag like replication from replication:* or shall I not display the wikis on power tag searches?
Just thinking that these power tags, are not just power tags they are in fact powerful regex expressions so, a user who knows a little code can type in replica* for gettling all replication related stuff. So, truncating replica* will give replica which will again show no wiki pages at the top.
So, I think we should have a condition if-else one in the wiki pages section at the top
What do you think??  Any other idea?

**Comment by jywarren** [comment]
Ah, i see -- you're totally right. We might be in a strange state if someone saw `/wiki/rep` for `/tag/rep*` -- ok, so let's just not show the lead wiki page for wildcard tags. 

We could hard-link to http://publiclab.org/power-tags (or relative, `/power-tags`) -- what do you think of that?

**Comment by jywarren** [comment]
Actually this is not relevant just to power tags, but all tags. How about instead of a wiki page, a short description like:

> **This is a wildcard tag search. The results will show anything starting with `activity`.**

> *Wildcard tag searches use the `*` asterisk in their URLs*

**Comment by SidharthBansal** [comment]
The main problem arises with a word, say app*, which has two root words -apple and application... So that will again give us trouble in finding. 
One way is to have related tags there. But again, here one problem will arise and that is people have written replication:* and that mean user want all related tags to replication and our tag system is showing all replicaion:* one.  So, there is no point for the user to search for the wildcard
I will like to go for the description part. What do you say?
