### ISSUE TITLE
Cancel button required for ease

### ISSUE THREAD

**Issue by Gauravano** [publiclab/plots2#1983]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem
Addition of cancel button in edit mode of wiki page so that user need not visit header for going back and he can cancel editing easily.

What actually does happen (screenshot if helpful!): 

## Solution
Addition of hyperlink a tag named as "Cancel" here
![can1](https://user-images.githubusercontent.com/20878070/34960179-cdcb7030-fa5f-11e7-9100-64e3eb59d365.png)
 
Where to find the relevant lines of code: https://github.com/publiclab/plots2/blob/master/app/views/wiki/edit.html.erb#L22

You just need to figure out href link,try finding that out yourself first.You can always ask for help.

## Steps to Fix

- [x] claim this issue with a comment here, below, and ask any clarifying questions you need
- [x] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by cesswairimu** [comment]
I would like to contribute to this issue if that is okay

**Comment by Gauravano** [comment]
Hi @cesswairimu I am waiting to get input on this issue from @jywarren , once it gets approved its all yours

**Comment by jywarren** [comment]
Hi! Would the cancel button go back to the wiki page? If so, that sounds
great.

**Comment by Gauravano** [comment]
Yes, Cancel button would redirect to the previous page.

**Comment by Gauravano** [comment]
So @cesswairimu you can take that issue.If you got stuck anywhere we are here to help.

**Comment by jywarren** [comment]
Great!

**Comment by jywarren** [comment]
Hi, i'm just going to hold back on the first-timers-only label for now, do you think you could look over the guide at https://publiclab.github.io/community-toolbox/#r=all and https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors for a bit more on how to format these? Thank you so much!

**Comment by Gauravano** [comment]
Will definitely take care of format of FTO issues from now on.Thanks

**Comment by jywarren** [comment]
Thanks. Once done we can relabel and delete these comments to keep it simple.

**Comment by Gauravano** [comment]
Hi, @cesswairimu have you started working on this issue? If you want I can highlight the relevant files which need to be modified for solving this issue.

**Comment by cesswairimu** [comment]
@Gauravano  yeah that would be great please. I am still having issues installing the project i shared in gitter my errors

**Comment by Gauravano** [comment]
Hey, @cesswairimu I have updated the issue, you can follow up with the link. And, we are working on fixing those errors in #1997.It would be corrected soon.

**Comment by Gauravano** [comment]
Hi @cesswairimu ,the issue about migration is resolved now , you can start working on it again and if you  face any error , you can post it here too.

**Comment by cesswairimu** [comment]
@Gauravano  Thanks a lot it works. I am working on the issue now
