### ISSUE TITLE
Can't sign in to Public Lab account on website

### ISSUE THREAD

**Issue by gretchengehrke** [publiclab/plots2#199]
Hi, 
I have a Public Lab account and have successfully logged in before, but when I try to log in today, the website tells me "It looks like you're new here..." and prompts me to create a profile to join the Public Lab community. 
Do I need to make a new account? 
Thanks, 
Gretchen

**Comment by btbonval** [comment]
Hi @gretchengehrke . Thanks for submitting a github issue. Unfortunately github issues are open and transparent. Anyone can read the conversation here.

That transparency isn't a good thing when discussing usernames, email addresses, and account recovery.

Could you email web@publiclab.org and close this ticket? Make sure to include the username you are trying to log in with and any email addresses you might have signed up with so we can quickly search the database for your previous user.

**Comment by gretchengehrke** [comment]
Sure thing.  Thanks!
