### ISSUE TITLE
Email validations missing

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#1992]
### Please describe the problem (or idea)
A user is able to sign in and use publiclab with email wrong email addresses say bansal@gmail
![image](https://user-images.githubusercontent.com/20972099/34905983-bcee2a1e-f889-11e7-9a6f-7de5683839bb.png)
I have created the account with wrong email
> What did you expect to see that you didn't?
I expect user should get an error message when submitting the wrong email

**Comment by SidharthBansal** [comment]
I think we should write REGEX for email validation in the model
Somewhat similar to
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true,
                    length: { maximum: 255 },
format: {with: VALID_EMAIL_REGEX }

**Comment by SidharthBansal** [comment]
Yeah I was also thinking to create it a first timer issue

**Comment by jywarren** [comment]
👍🎈

**Comment by SidharthBansal** [comment]
I am adding an fto issue and closing this one. So that it would be beginner friendly.
