### ISSUE TITLE
Add Email Validation 

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#1996]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you :gift_heart:

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!
:thinking: What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.
## Please describe the problem

A user is able to sign in and use publiclab with email wrong email addresses say bansal@gmail

:clipboard: Step by Step

:raising_hand_woman: Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

:memo: Add VALID_EMAIL_REGEX = /\A[\w+-.]+@[a-z\d-.]+.[a-z]+\z/i to the 
https://github.com/publiclab/plots2/blob/3b09a3515bbfecb48194bd86f2d467b2710103be/app/models/user.rb#L16
:floppy_disk: Commit your changes

:twisted_rightwards_arrows: Start a Pull Request.

:checkered_flag: Done Ask in comments for a review :)

:thinking::question: Questions?

Leave a comment below!

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seem stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!
Thank you!

Your help makes Public Lab better! We deeply appreciate your helping refine and improve this site.

**Comment by Paarmita** [comment]
@SidharthBansal I would like to do this :)

**Comment by SidharthBansal** [comment]
Awesome!!! Go ahead!

**Comment by jywarren** [comment]
Solving in #1999 -- thank you! (just linking over there)

**Comment by Ankit-Singla** [comment]
@SidharthBansal I see that the issue is still open and hasn't been resolved yet. I would like to give it a try if I may.

**Comment by SidharthBansal** [comment]
I think that @Paarmita left out. You can for sure try to resolve the issue

**Comment by Ankit-Singla** [comment]
I think I have done the right changes. I don't understand how I can generate a pull request. Can I please get any help in this regard?

**Comment by balaaagi** [comment]
@SidharthBansal  Is someone working on the issue. I could see it is still open. Can I take this?

**Comment by SidharthBansal** [comment]
@balaaagi I am really sorry for such a late reply. 
I think none is working on it. You can go for it.

**Comment by namanjain1812** [comment]
Claiming the issue as i dont see anyone working on it

**Comment by SidharthBansal** [comment]
Great

**Comment by namanjain1812** [comment]
@SidharthBansal i have done the changes as said but the checks does not pass.I further read about it 
https://stackoverflow.com/questions/22993545/ruby-email-validation-with-regex
and it also says the same.I you please tell where am i going wrong
