### ISSUE TITLE
show password reset link on profile pages

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#200]
For admins (and not moderators), it might be useful to display the password reset link for a user on his or her profile page.

Two users in a short number of days have said they received no email for the password reset link (and it was not in the junk folder either), but I found there was a password reset code in the database digging with my special tools (`mysql` CLI).

There is a larger problem to address here with the emails, but it is not an obvious problem. I received an email when I requested a password reset.

This will make it easier for admins to find the link and send it to users when requested.

**Comment by jywarren** [comment]
I like this. +1 and pretty easy to do.

**Comment by btbonval** [comment]
This would be a good stopgap for #242 until the email system works 100% again.

I'll see if I can get my local plots2 instance running and try to get this in the code.

**Comment by btbonval** [comment]
The profile code which contains various admin/moderator information is here:
https://github.com/publiclab/plots2/blob/fe2ba03bc05e937b0b10851824732bc2e791c525/app/views/users/profile.html.erb#L6-L23

We'd want to dump the reset key, if any, there.

The reset key is set here (serves as an example of how to access it):
https://github.com/publiclab/plots2/blob/1c2075dc84c51f59c3c9f115bbdbfade3cf890be/app/models/user.rb#L74-L82

A few more examples of how to access/use the reset key:
https://github.com/publiclab/plots2/blob/fe2ba03bc05e937b0b10851824732bc2e791c525/app/controllers/users_controller.rb#L144-L149

So, in the profile template, we'd probably want something like this:
``` erb
<% if @user.user && !@user.reset_key.nil? && current_user && current_user.role == "admin" %>
  <a href="/reset/key/<%= @user.user.reset_key %>"><i class="icon-certificate"></i> Reset Key: <%= @user.user.reset_key %></a>
<% end %>
```

**Comment by btbonval** [comment]
wierd, the closes message in the commit didn't close the ticket. Anyway, above commit closes ticket.

**Comment by jywarren** [comment]
bryan, your commit has no PR yet? Want to pull it in?

**Comment by btbonval** [comment]
Oh sorry it's in master. The ticket will show the commit link. I thought
about doing a PR but I wasn't sure if that would add more work to your
plate. Seemed nicer for your time if I just commit directly, but maybe not
a great habit.

**Comment by btbonval** [comment]
Omg I didn't know i forked the repo. I guess I do need to make a PR.

When did I start working out of my own fork? Ugh I probably haven't updated
against your repo then either

**Comment by jywarren** [comment]
Hm, i think you've committed to publiclab/master in the last week, so it's probably only this change. It'll rebase or merge cleanly, i expect. Cool.
