### ISSUE TITLE
Broken revision table headings

### ISSUE THREAD

**Issue by ViditChitkara** [publiclab/plots2#2004]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem
    The wiki revision page have a distorted table headings as shown below:-
    
![rev-1](https://user-images.githubusercontent.com/22616017/34919849-32ee5328-f98f-11e7-9358-0c7b5dcda9e2.jpg)
(This could be directly viewed on https://publiclab.org/wiki/revisions/hydrogen-sulfide)
    We could have another table heading (like "action") for the revert links column. It should look something like:-
![rev-3](https://user-images.githubusercontent.com/22616017/34919892-0682a270-f990-11e7-971e-07e8d8de60c2.jpg)

## Solution

Where to find the relevant lines of code: 
https://github.com/publiclab/plots2/blob/master/config/locales/views/wiki/revisions/en.yml
https://github.com/publiclab/plots2/blob/master/config/locales/views/wiki/revisions/de.yml
What to change them to:
There are 2 empty table headings in the following code snippets which maybe the reason for this problem. 
We could probably remove one of the 'th' tags and utilise other to show 'Action' heading.
https://github.com/publiclab/plots2/blob/ac0f56fff35d9a62d7bcc1d0726260b8d7187a31/config/locales/views/wiki/revisions/en.yml#L10-L16
https://github.com/publiclab/plots2/blob/ac0f56fff35d9a62d7bcc1d0726260b8d7187a31/config/locales/views/wiki/revisions/de.yml#L10-L16

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by ankitbhardwaj78** [comment]
Can i work on this?

**Comment by ViditChitkara** [comment]
That would be great!!
