### ISSUE TITLE
Redundant dashboard2 route 

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2006]
I found there is a route /dashboard2 
  get 'dashboard2' => 'home#dashboard2'
I checked the controller's action it is redirecting to the dashboard.
Does it needs to be removed @jywarren ? Or is there any place we are using it at?

**Comment by seafr** [comment]
I think if we point both routes to 'home#dashboard' the redirection will be redundant and we can then remove 'home#dashboard2'.

**Comment by SidharthBansal** [comment]
Thanks @seafr

**Comment by jywarren** [comment]
Agreed!
