### ISSUE TITLE
Basic/Normal User not able to delete own wiki page

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#2013]
Hi, this is a [first-timers-only](https://github.com/publiclab/plots2/projects/2) issue. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

# The Problem

When normal/basic user deletes the wiki page created by him/her , the login screen is shown .

# Solution

The delete button on wiki page   links to `/notes/delete/` .
https://github.com/publiclab/plots2/blob/ac0f56fff35d9a62d7bcc1d0726260b8d7187a31/app/views/like/_like.html.erb#L52
However the if condition in **notes#delete method** is incorrect here . 
We need to change **if** condition in line :  
https://github.com/publiclab/plots2/blob/ac0f56fff35d9a62d7bcc1d0726260b8d7187a31/app/controllers/notes_controller.rb#L237

to : 
`if current_user && (current_user.uid == @node.uid || current_user.role == "moderator" || current_user.role == "admin")`

### Feel free to ask any doubt regarding the issue ! Thank you !

# Steps to Fix 

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ]  set up a repository locally following the README instructions, and make sure that all tests pass
 - [ ] try to fix the issue following the steps above, but even before you're done, you can:
 commit your changes and start a pull request (see contributing to Public Lab software) but mark it as "in progress" if you have questions or if you haven't finished
- [ ]  alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see [https://publiclab.org/wiki/developers](https://publiclab.org/wiki/developers)) or go to the [chatroom](http://publiclab.org/chat) if you have questions, and take a look at our [first-timers landing page for more information!](https://github.com/publiclab/plots2/projects/2)

**Comment by ankitbhardwaj78** [comment]
Can i take this issue??

**Comment by sagarpreet-chadha** [comment]
Yes @jywarren , i would love to help ! Thanks 😄 .

**Comment by ankitbhardwaj78** [comment]
I will do this.. @jywarren

**Comment by ankitbhardwaj78** [comment]
@jywarren  and @sagarpreet-chadha  please take a review i have made changes #2030
