### ISSUE TITLE
Undesired recaptcha message in production enviroment.

### ISSUE THREAD

**Issue by namangupta01** [publiclab/plots2#2015]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

When user is signing up there is a recaptcha message as shown in the image:

![screen shot 2018-01-16 at 7 23 38 pm](https://user-images.githubusercontent.com/20709985/34992389-152dfbd0-faf3-11e7-93b4-d2707043a482.png)

I think this is undesired

> What did you expect to see that you didn't?

This message should not be there.
It should look like this:
![screen shot 2018-01-16 at 7 32 01 pm](https://user-images.githubusercontent.com/20709985/34992711-051013e0-faf4-11e7-99ff-294ac4b3aafa.png)

### Please show us where to look

https://publiclab.org/register

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hi, @icarito i think we've seen this before -- related to a non-final Recaptcha API key in production. Can you check this out? Thanks!

**Comment by icarito** [comment]
I'll try to issue a new key, it was not preserved when we upgraded, it seems.

**Comment by icarito** [comment]
Thanks for the heads up, much appreciated!
I issued a new API key and was able to eliminate the error.
