### ISSUE TITLE
Error when using emojis on wiki pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2020]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I tried to save a wiki page edit using an emoji -- 🎉 

But i got an error! The logs show:

"Mysql2::Error: Incorrect string value: `\xF0\x9F\x8E\x89 \x0D... for column 'body' at row 1` on this line:

https://github.com/publiclab/plots2/blob/3df85679c34489ab4bd9a1bf4b0c0deda1ae8654/app/controllers/wiki_controller.rb#L170

Any help appreciated! Emoji are important for showing appreciation to contributors 🥇 🎈 🎉

**Comment by ryzokuken** [comment]
@jywarren take a look at https://stackoverflow.com/a/22464749/5156578. This *should* solve our problem.

**Comment by namangupta01** [comment]
Does this problem also occur in development mode?

**Comment by jywarren** [comment]
I'm not sure, but i bet we could add a functional test for the wiki controller to see if we can reproduce this. It'll work in Travis since that uses mysql!

**Comment by jywarren** [comment]
I also wonder if this prior suggestion of a different encoding might help? #2209

**Comment by namangupta01** [comment]
Yes i also remember i commented on the issue to change the encoding but not able to find that issue.

**Comment by namangupta01** [comment]
got the issue...here it is https://github.com/publiclab/plots2/issues/2665

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/pull/3007

**Comment by jywarren** [comment]
Solved in unicode db!
