### ISSUE TITLE
Multiple Leaflet maps' initializations collide in JavaScript

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2022]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

On pages like this one:

https://publiclab.org/wiki/inline-maps

Where there are multiple maps, the JavaScript console is showing an error, i think because we don't uniquely name the maps. We should! 

I believe we can modify this code:

https://github.com/publiclab/plots2/blob/master/app/views/map/_leaflet.html.erb

For comparison, the last map on that page, when displayed alone, works fine!

https://publiclab.org/wiki/sandbox-3

**Comment by perfidiousscript** [comment]
Hi, I'm a first timer and am interested in taking this on.

**Comment by jywarren** [comment]
That'd be great, thanks so much! Please tell us if you need any help.

**Comment by jywarren** [comment]
Doesn't seem to be an issue anymore maybe? https://publiclab.org/wiki/inline-maps seems OK now, not sure why it was acting up earlier. I'm actually going to close this -- thanks for your offer, @perfidiousscript and if you're interested in taking on an issue, i just posted a few new ones:

https://publiclab.github.io/community-toolbox/#r=all 

Thanks!!!
