### ISSUE TITLE
Contributors for power tag inconsistent

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2023]
### Please describe the problem (or idea)
If a person is searching for contributors for a power tag, eg at https://publiclab.org/contributors/replication:* then the user gets no contributors
> What did you expect to see that you didn't?
Either contributors cannot be shown with power tags on this page with a message somewhat like "Please enter a normal tag instead of power tag to get Contributors list" as we have done for the button on the /tag/replication* or we can list all contributors related to that tag or we can truncate the '*' as suggested by @jywarren 

### Please show us where to look
https://publiclab.org/contributors/replication:*

@jywarren , @ebarry what can we implement?

**Comment by SidharthBansal** [comment]
@jywarren May I make this as a first timer with the desciption part? As we have discussed

**Comment by jywarren** [comment]
Please!
