### ISSUE TITLE
Display "activity from past day" in a list at /subscriptions/digest

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2027]
We have a new feature in the User model called `user.content_followed_in_past_period(time_period)`

https://github.com/publiclab/plots2/blob/c6b2d3460d1fb9da28ce5e1cc0944daf690f9415/app/models/user.rb#L313-L315

Let's adjust this to be `user.content_followed_in_period(start, end)` so we can use it like:

`user.content_followed_in_period(Time.now - 1.day, Time.now)`

And make it not use `self.node.where()` but `Node.where()` so it returns /all/ content, not just the user's own content -- adjusting both the test and the model function, and the test description on this line:

https://github.com/publiclab/plots2/blob/3db7e63c37d10516576a4cf585e1d05584c06682/test/unit/user_test.rb#L92-L96

****

### Follow-up task

Then, let's make a new controller method in https://github.com/publiclab/plots2/blob/master/app/controllers/subscription_controller.rb to display this content. It can just be in a table, like this template:

https://github.com/publiclab/plots2/blob/master/app/views/wiki/_wikis.html.erb

I'm not sure, but it may be possible to simply render that template with a collection, so the overall `/app/views/subscriptions/digest.html.erb` file could be just:

```ruby
<h2>Content you've subscribed to in the past week</h2>

<%= render partial: "wiki/wikis" %>
```

And the controller method could be:

```ruby
# display the past day's followed nodes on one page
def digest
  # note these won't be wikis but we'll use the wiki partial template to display a list of nodes
  @wiki = current_user.content_followed_in_period(Time.now - 1.week, Time.now)
end
```

This may not work on the first try, but I'm happy to help troubleshoot!

****

### Follow-up task

Then, let's make a method to send the digest in an email!

**Comment by Gauravano** [comment]
Hi @jywarren I want to try this

**Comment by jywarren** [comment]
That'd be great! Thanks!

On Jan 16, 2018 10:26 PM, "Gaurav Sachdeva" <notifications@github.com>
wrote:

Hi @jywarren <https://github.com/jywarren> I want to try this

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/2027#issuecomment-358185213>,
or mute the thread

**Comment by Gauravano** [comment]
We want to display the nodes to which user is subscribed to on the digest page or all the nodes created and changed between the start and end time? As changes suggested by you @jywarren in user.content_followed_in_past_period are not sufficient to display nodes subscribed/followed by the user, so I was little confused about the aim of the page.Its ready and working for showing all the nodes in the previous week, once you clarify above point, I will change the query in content_followed function accordingly. Also, Thank you, Jeff, your suggested changes have made this task easier.
