### ISSUE TITLE
send email to newly added coauthors explaining what it means

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2028]
This could actually be relatively simply achieved via a comment -- by automatically leaving a comment as we do for the barnstar feature:

https://github.com/publiclab/plots2/blob/dccf61b4cf0aa816a3a906495ea6a0b2d5d847b0/app/controllers/tag_controller.rb#L178-L180

The comment could say `@_author_ has marked @_recipient_ as a co-author.` and everybody on the thread would get email notified.

This code would go just before the last line of this block:

https://github.com/publiclab/plots2/blob/033676b8abd28cd56a999e60934ff9f01bd0a9ac/app/models/node.rb#L660-L667

and the message could look like:

```ruby
"_@#{user.username} has marked @#{node.author.username} as a co-author._"
```

This should work but could take some troubleshooting -- happy to help, and any assistance in taking this task on is appreciated!

**Comment by Gauravano** [comment]
Can I take this issue ?

**Comment by jywarren** [comment]
that'd be super. Thank you!

**Comment by Gauravano** [comment]
Hey @jywarren, the method in the tag_controller for solving this issue would work similar to method barnstar.The barnstar method is called by the form which is there in 'views/like/_like' but for making co-author there is no form present, we make co-author as for now by adding tags only, so should I add if statement in create method of tag_controller and redirect to separate method for handling creation of with:user tag or should I make a new form to trigger the method for this issue which would then perform comment creation part ?

**Comment by Gauravano** [comment]
Also, presently automatic comment creation for barnstar take place if the barnstar is generated via Award barnstar form and not by just adding power tag [barnstar: type], so we can also make changes so that comment creation could take place if someone has added barnstar tag.What do you think @jywarren?

**Comment by jywarren** [comment]
ah, i see. Yes, i think perhaps we should refactor these to trigger on the tag creation, not on the form submission, for both barnstars and co-authorship. 

Do you want to take a crack at this? Thank you!

**Comment by jywarren** [comment]
Just watch out because you can't access `current_user` in the models -- they don't "know" about the user session. But we should be able to use the tag creator's uid, right?

**Comment by Gauravano** [comment]
I will take care of this.Thanks, Jeff.

**Comment by jywarren** [comment]
awesome!!!

**Comment by Gauravano** [comment]
> The comment could say @_author_ has marked @_recipient_ as a co-author. and everybody on the thread would get email notified.

I want to confirm @jywarren that whether we need to send email to all the people present on that thread or only to the user who has been added as a co-author ?

**Comment by jywarren** [comment]
Only to the co-author -- good question! Thanks!

**Comment by Gauravano** [comment]
Thanks for clarifying Jeff
