### ISSUE TITLE
links in notification emails have are relative or incorrect

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#203]
> Hi! There's been a response to your research note "Planning for Spectral Workbench 2.0". Do NOT reply to this email; click this link to respond:

leads to simply `http://notes/warren/02-10-2015/planning-for-spectral-workbench-2-0`

**Comment by jywarren** [comment]
via Mathew's merged-in issue: 

![image](https://cloud.githubusercontent.com/assets/24359/10293218/55b3a42e-6b81-11e5-9983-c3670fcff976.png)

**Comment by icarito** [comment]
It is important that if there is an explicit address in the text, the anchor link points to the same address in the text, otherwise spam filters will definitively take notice. I would prioritize this.

**Comment by icarito** [comment]
Note this is part of the problem in issue https://github.com/jywarren/web/issues/5 (Publiclab.org mail issues)

**Comment by jywarren** [comment]
Also using this as a catchall issue for the problems in callouts -- where we say things like `@icarito` in comments and notes. @icarito has been testing this in jywarren/web#5.

**Comment by jywarren** [comment]
I believe this is confirmed; I sent a callout at: http://publiclab.org/notes/warren/12-12-2010/front-illumination-ccds-used-digital-cameras-dont-perform-well-uv#c12653

And the log shows:

````
Completed 200 OK in 1.2ms (Views: 0.1ms | ActiveRecord: 0.3ms)
  Rendered comment_mailer/notify_callout.html.erb (3.9ms)
Sent mail to xxxxxx@xxxxxx.com (66.8ms)
Sent mail to xxxxxxx@xxxxxx.org (77.7ms)
````
