### ISSUE TITLE
How are the questions sorted on the 'Unanswered' tab? (autoposted via PublicLab.org)

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2037]
(This issue was auto-generated from http://ift.tt/2B8W2Ma -- please help to flesh it out and explore the issue, and respond to the original author!) by http://ift.tt/2BcbKGm Read more and ask the original author for details at: http://ift.tt/2DmabeX ****
<h3>Please describe the problem (or idea)</h3>
<blockquote>
<p>What happened just before the problem occurred? Or what problem could this idea solve? I went to search for unanswered questions on Public Lab here: <a href="http://ift.tt/2BbRWTf">http://ift.tt/2BbRWTf</a> but I was confused by the way these questions were sorted. Is there a way to make that more clear? Maybe these should be sorted by most recent unanswered questions first?</p>
</blockquote>
<h3>What's your PublicLab.org username?</h3>
<p>Stevie</p>
**** (via **Research tagged 'question:website'** at http://ift.tt/2B9Mfpe at January 17, 2018 at 04:42PM)

**Comment by jywarren** [comment]
It seems to be sorted by "node id" (nid), descending:

https://github.com/publiclab/plots2/blob/1230a735e4882ab476d96816c2b87b818327ab01/app/controllers/users_controller.rb#L116-L118

We could try modifying this to sort answered ones to the top... we'd have to think through how to do that sorting. Do you like sorting by:

1. whether its been answered, and THEN
2. recency

?

**Comment by SidharthBansal** [comment]
I will like to try this.

**Comment by ebarry** [comment]
This would be really helpful. I am trying to sort by **recently asked but unanswered** questions, and the unanswered tab gives me results from 4 years ago.

**Comment by jywarren** [comment]
This was resolved, thank you!!!
