### ISSUE TITLE
unify research notes, comments, and wikis as much as possible

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#204]
Comments support most of the features of research notes, but the interface is slightly different.

Since they are already so similar, it'd be great to unify as much code that handles research notes and research note comments as is possible. Both to streamline the code for devvers and to streamline the interface for users.

**Comment by btbonval** [comment]
Turns out research notes might not support versioning the way wikis do.

There is no reason _not_ to supporting versioning in notes and comments. Edits are less likely to occur on single-author notes/comments (as opposed to multi-author wikis).

We don't necessarily need an interface to revert edits for comments or notes, but having the database version them could be beneficial in some cases. Also: unifying the code would make it easier to read, understand, and maintain.

**Comment by btbonval** [comment]
Primarily the difference between research notes/comments and wikis are the number of authors: one for the former, many for the latter. This is a problem of access controls which should be performed at the controller level (or higher); it is not worth distinguishing at the level of the model except for parent/child relationship. By supporting that comments can be children of other comments, we could also allow for more precise thread flows in the form of reddit (or we could leave it internal and not change the display at all).

Primarily the difference between research notes and comments are presentation: where are they placed and what kind of field are they input using. I'm not sure that we need to make the comment input field smaller than the usual research note edit form; in fact, cramming that research note form in the bottom would be reusing code in a nice way. It's just whether the form is on a blank page or under an existing research note.

**Comment by jywarren** [comment]
@ananyo2012 used the Concerns feature in recent Rails to consolidate some common methods among comments, nodes, and answers. This seems like a powerful way to begin slimming down some of our models.

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/commit/60abae5655a91ba300524ad049f1e080ea68741f

**Comment by jywarren** [comment]
This is looking good in the Concerns code! I think we could break out a "versioning for research notes" and recommend an implementation that uses the `node_shared.rb` concern at https://github.com/publiclab/plots2/blob/master/app/models/concerns/node_shared.rb

**Comment by jywarren** [comment]
Moving to a new issue to add version history (revisions) for notes, server-side - #3109
