### ISSUE TITLE
List wiki revision authors as contributors on /contributors/tagname pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2042]
### Please describe the problem (or idea)

I noticed that "Nova" just contributed a revision to the water sensors wiki page: https://publiclab.org/water-sensors

However, they don't appear on the contributors page for that tag: https://publiclab.org/contributors/water-sensors

How hard would it be to add all revision authors to that query? 

https://github.com/publiclab/plots2/blob/5bd6efacc416dc2a1b1235b386c44babe8602b72/app/controllers/tag_controller.rb#L315-L325

Could we make an implementation closer to how `contributor_count` works, in the Tag model?

https://github.com/publiclab/plots2/blob/5bd6efacc416dc2a1b1235b386c44babe8602b72/app/models/tag.rb#L55-L66

Could this implementation also live in the Tag model, and even use the same code as `contributor_count`?

Any help appreciated!

**Comment by ViditChitkara** [comment]
Also we had written the contributor_count method in tag model and did not use it as shown in the comments:-
https://github.com/publiclab/plots2/blob/c12b0fc5e0b88f5219614ca98d031abfc91979ca/app/controllers/tag_controller.rb#L108-L113 
We need to replace that too. What do you say? Shall I submit a patch for this?

**Comment by jywarren** [comment]
That'd be great. Just catching up on PRs now!
