### ISSUE TITLE
404 url  :https://publiclab.org/notes/khufkens/04-24-2015/www.khufkens.com

### ISSUE THREAD

**Issue by ArunNairID** [publiclab/plots2#2049]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hi, thanks -- i think this may be a typo on the original author's part -- perhaps `http://` was not entered? If you agree, perhaps you can leave a comment on that post. I'm going to close this for now but thanks for reporting! If you're interested in getting involved, please check out:

https://publiclab.github.io/community-toolbox/#r=all
