### ISSUE TITLE
devopsify plots

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#205]
I'm mostly doing this as an exercise in first-hand experience to complement my theoretical conceptions and second-hand experience. Figured I'd write a ticket.

The plan is to automate the deployment of Plots2 using an Ansible playbook. For now, I'm assuming debian and apt. The playbook can be extended for other systems as needed or desired later.

For development, I'm planning to use Vagrant to create a virtual machine and run the Ansible playbook against the VM to get it up and running.

For VPSs out in the world (staging/deployment), accessing them should be no different than accessing any other system via SSH. The Ansible playbook should run against the given SSH host no matter where it lives. This should be tested against the publiclab sandbox (I think we have one).

If someone wants a local environment instead of a VM, they should be able to run the Ansible playbook against the local system via SSH. I should ensure this can be done and document it. (This might not be a great solution because the system itself is reconfigured for running the plots software)

For production, Ansible supports Rackspace. I currently don't have access to the Rackspace account and I'm not sure we want Ansible to be provisioning any Rackspace VMs for now.

It sounds like, for now, provisioning a VM will be handled by Vagrant and not Ansible, and we'll ignore provisioning Rackspace VMs. Ansible will be used for configuration.

It will be good to add a hook so that Ansible can update the code running on a system without necessarily starting from bootstrap.

- [ ] Vagrant deploys Debian-based VM
- [ ] Ansible bootstraps VM completely and runs plots system
- [ ] Vagrant calls Ansible bootstrap against VM
- [ ] Ansible updates remote code base and resets appropriate services

Extra credit:

- [ ] Vagrant deploys LXC for systems that can't or shouldn't run a full VM
- [ ] Provision Rackspace system

**Comment by btbonval** [comment]
There is some redundant information in the config so far. For example, the version of Ruby to install is defined in Gemfile (which is sort of wierd, because it is not like Bundler can do anything useful with this information), but it needs to be known by Ansible for installing the correct Ruby version onto the system.

**Comment by btbonval** [comment]
As clarification, the focus of this is on a single-serving system. Thus, I'm focusing on installing everything system-wide.

RVM is not used, as it is for a per-user sandbox. ruby-installer is used to find and install the specified version of Ruby onto the system. Bundler will be run as usual, except it will be given the `--system` flag to install all gems system-wide.

I need to find a good way to run Rails as a startup service while I'm at it.

**Comment by btbonval** [comment]
Look into Vagrant container support. LXC should be a good enough solution for anyone running Linux on netbooks without messing up the entire system.

**Comment by jywarren** [comment]
Note: specifying ruby version in Gemfile is read by RVM, but it's mostly a convenience and a way to ensure devs use the same version.

**Comment by btbonval** [comment]
Ah! That makes sense for RVM. Since I'm not using RVM for deployment, I
have to specify the version another way.

I'll see if there is some way to share that version in two places without
duplication. Possibly a preprocessor that populates config files, but
hopefully not.

**Comment by jywarren** [comment]
I believe this is now being done in Docker by @icarito -- we may be able to close?

**Comment by icarito** [comment]
Yes, I'm doing it with Docker. Worked well for Mapknitter. I'll make a ticket in the systems tracker ;-)

**Comment by icarito** [comment]
We have currently a Dockerfile and docker-compose.yml that setup a Debian 8 container, and we currently use if for continuous integration.

Have a look at .travis.yml for a comand-by-command instruction on how to setup a container with mysql database.

Closing, feel free to reopen if there's something missing!
