### ISSUE TITLE
Looking for mentors for 2018 Summer of Code programs

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2053]
Hi, folks! We're now applying for both Rails Girls Summer of Code and Google Summer of Code -- and we need some folks to offer to be mentors for GSoC in particular. (RGSoC has a different system!) Is anyone interested in joining in as a mentor this coming summer? (we would love to have you apply as a participant of course -- either way!) 

Here's some info I've collected on mentoring... there's a good bit, but if you've been coding with us, or participated in a summer of code with us already, a lot should be very familiar.

If you're interested, please leave a comment on this post:

https://publiclab.org/questions/warren/01-08-2018/software-project-ideas-for-upcoming-2018-summer-of-code-fellowships

Then leave your name next to one of the project ideas we've listed over here: https://publiclab.org/wiki/gsoc-ideas#Ideas

Thanks so much!

****

### What does it mean to be a mentor? 

(from https://publiclab.org/wiki/gsoc#Mentoring)

Mentors **check in with a student at least once per week** roughly from May-August, and offer some project management guidance and encouragement... while relying on the [plots-dev list](/wiki/developers) and the `@publiclab/reviewers` group on GitHub to provide code-specific input, so that we share the burden of specific technical support. 

This means that **to be a mentor you don't necessarily need to know how to code** -- we need mentors who know Public Lab's community and practices well, and who can encourage students to speak up when they get stuck, and to ask the community for input and testing of their work. Students often get stuck when they don't know how something should look, or how a feature might be used by the community -- contextual info!

If you're interested in being a mentor, email the developers list or jeff@publiclab.org -- and read over our [software outreach resources](/software-outreach) to get an idea of how we work!

Some key resources on mentoring:

* our [Summer of Code workflow](https://opensource.googleblog.com/2016/12/google-summer-of-code-2016-wrap-up_21.html)
* read [different ways to mentor in this post](/notes/warren/11-08-2016/help-public-lab-s-software-grow-by-joining-a-supportive-team) -- we need various types!
* read about [what reviewers do day-to-day on Public Lab code projects](/wiki/developers#Reviewers)
* read about [our commitment to modularity](/notes/warren/01-18-2018/software-outreach-modularity-is-great-for-collaboration), very important in how we ask contributors to work
* check out our growing list of [software outreach strategies](/software-outreach)

@publiclab/reviewers @publiclab/soc @icarito @ebarry @steviepubliclab  @MayankKashyap @siaw23

**Comment by MayankKashyap** [comment]
Yeah Jeff , I read about it and I can manage easily

**Comment by jywarren** [comment]
@siaw23 - were you interested as well? Thanks!

**Comment by siaw23** [comment]
yes @jywarren

**Comment by Supun94** [comment]
@jywarren I also would like to apply as a mentor. Thanks!

**Comment by namangupta01** [comment]
@jywarren If possible i would also like to apply as a mentor.

**Comment by jywarren** [comment]
Super, have you all read through the materials I posted above? Thanks very much!

**Comment by jywarren** [comment]
If you're interested, please leave your name in the "potential mentors" list on this page next to projects that interest you! Thanks!

https://publiclab.org/wiki/gsoc-ideas

**Comment by manishkd** [comment]
@jywarren  how we can add our name in potential mentors list, I can't find out.

**Comment by MayankKashyap** [comment]
@jywarren how we can add our name in potential mentors list. I can't find out.

**Comment by jywarren** [comment]
Sorry, to clarify, you can click the Edit tab on that page and add your name -- you'll need a PublicLab.org login! Thanks!

**Comment by jywarren** [comment]
Hello to folks who've asked to be mentors -- I'm assuming you've read through the above materials and I'm adding you all to the @publiclab/reviewers group as well as @publiclab/soc -- we expect mentors to participate in the usual welcoming/reviewing/supporting role that everyone in the reviewers group does. Ask if you're not sure what this means!

Thank you very much! As we [get proposals](https://publiclab.org/notes/warren/02-15-2018/call-for-summer-of-code-2018-proposals), please reply to folks with tips, encouragement, and try to help them format and break down their work into task lists as the above resources indicate. We'll post a "good example" of one soon, but this will also be a chance to figure out who you'd like to be a mentor for when the summer comes. 

Awesome!

**Comment by jywarren** [comment]
Hello all - just posted a call for mentors for Summer of Code 2019 at #4585. Thank you!!!

**Comment by SidharthBansal** [comment]
Hi all!
Anyone interested in GCI at PL then please read https://github.com/publiclab/plots2/issues/6238

**Comment by namangupta01** [comment]
Hey Guys! I am up for GCI mentor

**Comment by pydevsg** [comment]
Hello @SidharthBansal , I have gone through the guidelines and I am willing to a part of the GCI program as a mentor of PL.

**Comment by vinitshahdeo** [comment]
Hello @jywarren @SidharthBansal 

I am highly interested in being a part of Public Lab. I'd like to apply for mentor of GCI program.

**Comment by SidharthBansal** [comment]
Please refer #6238
We will really appreciate your help.

**Comment by jywarren** [comment]
Hi, all! New call for SoC mentors for 2020 is up here! https://github.com/publiclab/plots2/issues/7360
