### ISSUE TITLE
Need a more graceful "denial of access" when not logged in and trying to click buttons

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2056]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

i was watching a faculty member click the "i did this" button on an activity, and they instantly hit the "not logged in" screen. It is preferable that not-logged-in people be able to see at least some kind of preview of what the response template looked like. Without being able to see what screen the button led to, there wasn't enough of the experience that was visible to the potential activity writer so that they could understand the experience they were choosing to provide to their students. This makes it hard for someone (like an educator, in this case) to make the choice to use Public Lab if they didn't already have the commitment / behavior of automatically signing up for a new site/service. 

> What did you expect to see that you didn't?

i would expect that someone not logged in could click a "post" or "i did this" button and see a preview of the next screen to see our nice editing interface, perhaps with a pop-up login screen that was just in the middle that you can see around. 

Also looking forward to OAuth to create a hiccup-less flow of clicking a "log me in with google" button and continuing on seamlessly to do what you are trying to do. 

### Please show us where to look

https://publiclab.org/kombucha-leather, click the activity link, then click the "i did this" button

Thank you!

**Comment by jywarren** [comment]
one way to do this a little smoother is to, instead of simply linking to
/login, have a modal pop up -- like on https://spectralworkbench.org/ --
although with both login and signup forms in the modal. +1 that OAuth will
make this even better!

**Comment by oorjitchowdhary** [comment]
@SidharthBansal Can I take this? 

> one way to do this a little smoother is to, instead of simply linking to /login, have a modal pop up -- like on https://spectralworkbench.org/ -- although with both login and signup forms in the modal. +1 that OAuth will make this even better!

**Comment by SidharthBansal** [comment]
@oorjitchowdhary this issue is being tackled in https://github.com/publiclab/plots2/issues/4132.
So it will be better than you will take a part of issue of it on which no one else is working

**Comment by ebarry** [comment]
Hi @SidharthBansal , i remember how epic #4132 was! wow! The new modals are really lovely, i continue to appreciate them!

Is there a currently open issue for being returned to the particular content page you were on when you logged in? Right now, after attempting to interact on a page, then logging in, i get dropped back to the front page: 

![login](https://user-images.githubusercontent.com/161439/67523444-b08e3c80-f67c-11e9-84fe-c3e7405c88de.gif)

**Comment by SidharthBansal** [comment]
This issue was resolved last year. But it came back 4 months ago again.
I opened one issue to fix it but couldn't get time to complete it due to my research journal work.
Sorry for delay. Will complete it asap 
As this is duplicate issue, i m closing it up
