### ISSUE TITLE
add sorting to /profiles and alias /people

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#206]
Similar to sorting functions on wiki pages, add ability to sort by # contributions, recently joined, # likes earned on their research

http://publiclab.org/profiles

**Comment by jywarren** [comment]
wow there seem to be some spam users on that page.

**Comment by steviepubliclab** [comment]
Just writing in to +1 this idea. another way to follow community trends

**Comment by jywarren** [comment]
@btbonval -- I'm having an SQL issue here and I know you're the wizard. I am crafting a query to sort users by their most recent node update, i.e. `drupal_node.changed DESC` -- although even that won't work properly, as wikis can be changed by non-original-authors. But it's a first step. But I can't seem to both GROUP and ORDER my query:

````ruby  
DrupalUsers.where(status: 1).joins(:drupal_node).group(:uid).order("node.changed DESC").limit(10).collect(&:name)
DrupalUsers Load (0.4ms)  SELECT `users`.* FROM `users` INNER JOIN `node` ON `node`.`uid` = `users`.`uid` WHERE `users`.`status` = 1 GROUP BY uid ORDER BY node.changed DESC LIMIT 10
=> ["bear977", "tupi977", "gclout01", "donna245", "sam245", "cscantiagingclinic", "maclipsticks", "fleurheathtuer", "geminimelttuer", "funciahorttuer"]
````

whereas:

````ruby
DrupalUsers.where(status: 1).joins(:drupal_node).order("node.changed DESC").limit(10).collect(&:name)
DrupalUsers Load (1.0ms)  SELECT `users`.* FROM `users` INNER JOIN `node` ON `node`.`uid` = `users`.`uid` WHERE `users`.`status` = 1 ORDER BY node.changed DESC LIMIT 10
 => ["warren", "warren", "warren", "warren", "sam245", "donna245", "PeterDavidowicz", "warren", "warren", "warren"] 
````

I must be misunderstanding how GROUP BY works?

Apart from that, we'll want to do this for node_revisions, not nodes, and also join comments. That way we can sort by last created/edited wiki edits, research notes, or comments, then paginate. IS IT POSSIBLE?

**Comment by btbonval** [comment]
I'm not sure what you are demonstrating in your examples. In one example, you use `GROUP BY`, and in another, you don't. The results are very different, which is what happens when you use `GROUP BY`.

It is not obvious to me that `GROUP BY` is _not working_. Rather than showing me the difference of using or not using `GROUP BY`, could you demonstrate what is wrong about the returned result when using `GROUP BY` by showing me what you would expect as a result?

Since `node_revisions` is tied to `uid`, there should be no problem joining the tables the same way you joined against `drupal_node`.

Pagination is just a combination of `LIMIT` and `OFFSET`, so that can be built into the query (by hand or using the ORM). You definitely want to paginate inside the database when dealing with hundreds of thousands of results (which will happen with users), rather than returning results and paginating by the server code or the browser client. If you're using a pagination gem, check how it paginates.

I don't think I answered your question, but if you provide me with a little more clarity on what you think is wrong, hopefully I can help.

**Comment by btbonval** [comment]
It might help to include the field you are sorting by in your returned results for debugging. Remove the collect to see the full result, it might help your understanding.

**Comment by btbonval** [comment]
I figured out the problem whilst showering. All answers come whilst showering.

When you `GROUP BY`, you generally mean to aggregate some kind of operator over what you are aggregating.

In this case, you want the `MAX()` operator over the timestamp.

If I were to write it in SQL, it'd look a little like this:
``` SQL
SELECT uid FROM
    (SELECT `users`.`uid`, MAX(`node`.`changed`) as most_recent FROM `users` INNER JOIN `node` ON `node`.`uid` = `users`.`uid` WHERE `users`.`status` = 1) AS sq
GROUP BY uid
ORDER BY most_recent
DESC LIMIT 10
```

The "AS sq" subquery is copy/pasted from the SQL the ORM generated in your example. Honestly, it could probably be done without a subquery, but it generally gets very complex without a subquery so I have to think about it a lot harder.

No idea how to ORM all that.

**Comment by btbonval** [comment]
As a quick explanation of the above, the subquery finds the most recent timestamp for each uid and labels it `most_recent`. The subquery itself is then labeled `sq`, and can be treated as a table named `sq` with columns `uid` and `most_recent` (due to the `SELECT` parameters).

Now that we have a subquery with the tuple (user, most recent timestamp), simply order it by the most recent timestamp and return the user. I added limit/offset for pagination.

**Comment by btbonval** [comment]
probably want to add `AND node.status = 1` to the `WHERE` clause so banned nodes are not included.

node_revisions might be trickier for that aspect.

**Comment by jywarren** [comment]
Ok that's very helpful, I think I can take it from there. Thanks Bryan! I
had assumed group by would only aggregate and the order by would still
stand. But group by max makes some sense. I had been thrown by all the SQL
jargon in the manual entries for group by. Thanks!!

**Comment by btbonval** [comment]
PS read the github page, I sort of edited the snot out of my query after posting. your email will be out of date.

**Comment by jywarren** [comment]
Hmm, ok -  what I said still stands -- the GROUP BY with MAX() -- but to generate it in ActiveRecord, I'll probably need to do it without a subquery. I tried:

````ruby
 @users = DrupalUsers.group('MAX(node.changed) AS last_updated')
                     .where(status: 1)
                     .joins(:drupal_node)
                     .order("last_updated DESC")
                     # .paginate(:page => params[:page])
````
which generates:
````SQL
SELECT  `users`.* FROM `users` INNER JOIN `node` ON `node`.`uid` = `users`.`uid` WHERE `users`.`status` = 1 GROUP BY MAX(node.changed) AS last_updated ORDER BY last_updated DESC
````

but it says: `Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS last_updated ORDER BY last_updated DESC LIMIT 30 OFFSET 0'`

Trying ORDER BY `users.last_updated` ...?

**Comment by btbonval** [comment]
You cannot `GROUP BY` using an aggregator function, that's where the error comes from. `GROUP BY` identifies which variable to use as the independent variable while applying aggregation functions.

So if you `GROUP BY uid`, it means any aggregation functions in your `SELECT` will apply across all rows returned for a common `uid`.

For example, if warren shows up in 15 different rows, `MAX(node.changed)` will find the maximum `node.changed` value for warren across those 15 rows. It does this for each uid where node.changed shows up in multiple rows.

**Comment by jywarren** [comment]
Ack, i misread... reworking

**Comment by jywarren** [comment]
Oh, you are responding very quickly. Hang on a sec

**Comment by btbonval** [comment]
No I will never hang on! Ninja strike!

**Comment by jywarren** [comment]
Done!

````ruby
@users = DrupalUsers.select('*, MAX(node.changed) AS last_updated')
                           .group('users.uid')
                           .where(:status => 1)
                           .joins(:drupal_node)
                           .order("last_updated DESC")
                           .paginate(:page => params[:page])
````
Generates:
````SQL
SELECT *, MAX(node.changed) AS last_updated 
                           FROM `users` 
                           INNER JOIN `node` ON `node`.`uid` = `users`.`uid` 
                           WHERE `users`.`status` = 1
                           GROUP BY users.uid 
                           ORDER BY last_updated DESC 
                           LIMIT 30 OFFSET 0
````

**Comment by jywarren** [comment]
Thanks Bryan!

**Comment by btbonval** [comment]
Sure. That's better without the subquery.

You still might want `.where(node:status => 1)` or whatever in Ruby to make sure the node isn't banned.

**Comment by jywarren** [comment]
adding tests, running them, rebasing, and closign

**Comment by jywarren** [comment]
http://publiclab.org/people -- opening new issue for changing it to be node_revisions and incorporating comments

**Comment by ebarry** [comment]
Hey this issue got closed, when it seems to me that only https://github.com/publiclab/plots2/issues/263 actually got completed. There is still a need to change how /people gets sorted, including potentially by whether people have a filled out bio (See https://github.com/publiclab/plots2/issues/308)

**Comment by jywarren** [comment]
Does #308 fulfill this, or do you want to open a new issue referring to this, but with further request for sorting?

**Comment by ebarry** [comment]
Well, 308 adds on to my original issue that started this thread: "Similar to sorting functions on wiki pages, add ability to sort by # contributions, recently joined, # likes earned on their research to http://publiclab.org/profiles"

So, i can make a new issue with exactly the same text i started this one with ;) is that advisable?

**Comment by jywarren** [comment]
Yes, please open a new issue. This is a really long issue now, mostly dealing with the need to create an optimized query to be able to sort by `drupal_node.changed`, which is now complete. We should start a new one for additional sort types -- each may be somewhat complex to do:

* join date - this is easy, and used to be the default
* # contributions - this will be a bit tough -- it involves a count query, or a caching of a node count
* # of likes earned on their research - this will be even harder, as it involves nested references -- a list of Users whose Nodes have earned Likes
