### ISSUE TITLE
Add profile pictures to /people page

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2063]
### Please describe the idea

> what problem could this idea solve?

Our existing top level page about Public Lab members is a little bland

<img width="1022" alt="screen shot 2018-01-22 at 12 46 19 pm" src="https://user-images.githubusercontent.com/161439/35235483-43643306-ff72-11e7-8e5e-b5fe49fd9206.png">

The Halt The Harm leader directory is on point for having profile pictures. 
<img width="832" alt="screen shot 2018-01-22 at 12 44 00 pm" src="https://user-images.githubusercontent.com/161439/35235427-0f6f2a38-ff72-11e7-81b5-b8ea5629209e.png">

### Suggested steps

* Add profile pictures to /people
* Consider how to show profile tags on /people

**Comment by jywarren** [comment]
That'd be super. Thank you!!
