### ISSUE TITLE
Open port 25 in container to docker host (for SMTP)

### ISSUE THREAD

**Issue by icarito** [publiclab/plots2#2065]
### Please describe the problem (or idea)

Staging container should try to use localhost email facility. Currently it errors (see https://github.com/publiclab/plots2/issues/1570 )

**Comment by namangupta01** [comment]
@icarito As you said we are using SMTP server on production and its running on port 25. I think to open that port there would also be the need for the Docker container's address running on port 25 and address of docker container can be specify by name of the Docker Container. So i think name of docker container is also required to open the port?

**Comment by namangupta01** [comment]
Never mind i got it.
It is `address: "smtp"`

**Comment by jywarren** [comment]
Hi, i see your PR but wouldn't this affect production while we are only interested in doing this for staging? Perhaps we need a bit more input from @icarito before moving forward on this. But thank you!

**Comment by icarito** [comment]
Thanks for your initiative.
The issue is staging is run in a container so we need a way for this container to access the mail service on port 25 at the docker host. So this issue is about configuring docker to allow access to the docker host (usually at IP 172.17.42.1 but need some checking).
Your idea of naming a host as smtp by default is good, although localhost is a more conventional choice for a hosted platform.

**Comment by icarito** [comment]
https://stackoverflow.com/questions/17770902/forward-host-port-to-docker-container documents a way to do this modifying the docker-compose.yml file.
