### ISSUE TITLE
Planning issue: Improve various graphs across site

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2068]
### Please describe the idea

**Stats graphs appear in many places around the site, so improving these graphs will have a big impact on how people understand activity in Public Lab**

### Background on graphs

The graphs haven't been improved since they were first created some years ago. Stats and graphs of all kinds are important for how the community can see itself, and for the non-profit to do evaluation with. 

### Ideas for graphs on `/tag/____ pages`

like http://publiclab.org/tag/kite-making

* [x] Each graph on pages like `/tag/____ pages` should be a link to http://publiclab.org/stats
* [x] Each graph should have a labeled X and Y axis
* [x] Each graph should have a tooltip showing the data that is graphed
* [x] Each graph should _potentially_ have a label like "Activity", but perhaps this won't be needed with well-labeled axes or by using the tooltip (although that won't work on mobile)
* [ ] Determine how graphs should appear on mobile

### Related graphing issues across the site

* [x] Heat maps on profile pages #2361
* [x] http://publiclab.org/stats page graph styling and features (incorporating above ideas): #2068

### Examples of graphs on publiclab.org

* The home of graphs on publiclab.org: https://publiclab.org/stats
* all contributors https://publiclab.org/contributors
* views for contributors by tag such as https://publiclab.org/contributors/wetlands
* https://publiclab.org/tag/kite-mapping
* individual profile pages: https://publiclab.org/people/liz

There are a lot of graphs on https://publiclab.org/stats:
<img width="873" alt="screen shot 2018-01-22 at 1 51 12 pm" src="https://user-images.githubusercontent.com/161439/35238407-568b36ba-ff7b-11e7-8622-ed1ab7d5000c.png">

There are a lot of graphs on https://publiclab.org/contributors:
<img width="1037" alt="screen shot 2018-01-22 at 1 55 46 pm" src="https://user-images.githubusercontent.com/161439/35238620-02310350-ff7c-11e7-9fd9-d0b8b23c7bf8.png">

....and views for contributors by tag such as https://publiclab.org/contributors/wetlands
<img width="1031" alt="screen shot 2018-01-22 at 1 57 02 pm" src="https://user-images.githubusercontent.com/161439/35238656-278b3b98-ff7c-11e7-902b-0395e2ddebc3.png">

You might arrive at the page above by beginning at a tag page, each of which has a graph, such as https://publiclab.org/tag/kite-mapping: 
<img width="1014" alt="screen shot 2018-01-22 at 1 53 02 pm" src="https://user-images.githubusercontent.com/161439/35238497-9c0ad718-ff7b-11e7-9cce-4d9cb4baa4eb.png">

Each profile page has a graph, such as https://publiclab.org/people/liz: 
<img width="1088" alt="screen shot 2018-01-22 at 1 33 45 pm" src="https://user-images.githubusercontent.com/161439/35238423-6337de68-ff7b-11e7-9283-ba98daf3bd1b.png">

There are probably other places where graphs appear. :D

**Comment by namangupta01** [comment]
@ebarry See https://www.chartkick.com/ They have nice graphs.

**Comment by Gauravano** [comment]
https://plot.ly/javascript/line-charts/ they also have a nice interface and their graphs satisfy many ideas which you want @ebarry.

**Comment by steviepubliclab** [comment]
Just pining in that this one seems related to issue #529 https://github.com/publiclab/plots2/issues/529

**Comment by jywarren** [comment]
https://frappe.github.io/charts/ is really nice and has several github type charts!

**Comment by Souravirus** [comment]
@jywarren I want to work on this

**Comment by jywarren** [comment]
Yes, let's start with profile pages, what do you think?

**Comment by Souravirus** [comment]
Yeah I have started working on it

**Comment by ViditChitkara** [comment]
@jywarren I'd be interested in this one!

**Comment by jywarren** [comment]
that'd be great!

**Comment by cesswairimu** [comment]
Hello @ebarry , did you get a chance to look at the new graphs? If so kindly update on changes you would like to be made. Also I was testing the new graphs on mobile earlier today this is how they look.
![screenshot_2019-03-05-19-28-31-898_com android chrome](https://user-images.githubusercontent.com/17081074/53822099-2162d600-3f80-11e9-8d40-15e049b12521.png)

Thanks

**Comment by jywarren** [comment]
Closing this!!!!
