### ISSUE TITLE
[DRAFT] Navigate by first letter for /wiki and /tags

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2069]
### Please describe the problem (or idea)

There has been so much great improvement made on sorting /wiki and /tags lately -- thank you all so much!!!

I would like to explore more fine grained navigation. 
Here's an idea originally proposed in https://github.com/publiclab/plots2/issues/179:

* Add individual letters as well as the number zero to the top of /wiki and /tags like this `0 a b c d e f ...` across the top of the list so people can get right to the letter they are interested in

The scenario is that i am interested in air, and i want to see all types of tags about air, like air-quality, air-monitoring, air-sensors etc. 

Perhaps there are better user interface patterns for this. What do you think?

### Please show us where to look

https://publiclab.org/tags
https://publiclab.org/wiki
https://publiclab.org/people

**Comment by namangupta01** [comment]
This seems to be a great idea!

**Comment by SidharthBansal** [comment]
Superb idea!!!

**Comment by namangupta01** [comment]
@ebarry Can i work on it?

**Comment by jywarren** [comment]
That would be great @namangupta01 -- maybe we could use this: https://github.com/lingz/alphabetical_paginate

**Comment by ebarry** [comment]
Yay, glad people are excited!

**Comment by jywarren** [comment]
Hi, @namangupta01 are you still interested in working on this? It's from a while ago but seems pretty interesting and useful!

**Comment by jywarren** [comment]
Done!

https://publiclab.org/wiki/?sort=title
https://publiclab.org/tags?sort=name&order=asc

Both could use tests, but closing for now!
