### ISSUE TITLE
set node.icon based on tagging, rather than node.type, for display in search results

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#207]
@steviepubliclab noticed this because not all place pages have "flag" icons in search results. We think the various icons are helpful in search results for users just getting acquainted with the Public Lab community. 

so perhaps, have the icons made “all same” or rejigger them to be based on tagging rather than intrinsic/Drupal node type.

**Comment by jywarren** [comment]
To clarify, this is in autocomplete results, right, not on http://publiclab.org/search ? 
If so, I think the relevant code section is here: https://github.com/publiclab/plots2/blob/master/app/controllers/search_controller.rb#L26-L41

**Comment by ebarry** [comment]
it's on /search too. Shown here searching for "gulf coast", the Gulf Coast place page correctly has a flag icon. @steviepubliclab noticed that not all place pages have that. This is something that lowers the functionality of our search. 
![screen shot 2015-02-17 at 5 19 43 pm](https://cloud.githubusercontent.com/assets/161439/6238484/57c6dd66-b6c9-11e4-92ad-e41b1c9ef29f.png)

**Comment by jywarren** [comment]
by /search i meant the full page results, like when you press enter for a
search term without selecting an autocomplete result; this is autocomplete
search only.

I believe the other place these show up is in sidebar results. There may be
code in /app/models/drupal_node.rb that specifies icons; we should
centralize that code.

**Comment by jywarren** [comment]
Note: this should use `node.has_tag()` as in https://github.com/publiclab/plots2/blob/master/app/models/drupal_node.rb#L298

Also a good chance to refactor `node.is_place()` to use `has_tag`: https://github.com/publiclab/plots2/blob/master/app/models/drupal_node.rb#L221

**Comment by ananyo2012** [comment]
@jywarren Please review the fix for this Issue.

**Comment by ananyo2012** [comment]
@jywarren One thing I couldn't figure out--How is the node type for certain places set to "place" for certain places? and how is the path set to `/place/xyz` since I don't see anything for setting the path for a "place" type in the `generate_path` method.

**Comment by jywarren** [comment]
"place" used to be a type of node, but we've deprecated those as much as possible in favor of simply using wiki pages. It'd be good to go through and thoroughly clean out that older system, and migrate any "place" nodes to "page" nodes. 

`generate_path` is only run on new nodes, so since "place" type nodes a no longer created, they only have that path because path is saved in the record itself... so it's for legacy reasons. 

Thanks for fixing this issue!
