### ISSUE TITLE
List people by profile tag at /people/TAGNAME

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2071]
We have a great list of people over at http://publiclab.org/people

But now we have profile tags -- see the bottom of: https://publiclab.org/profile/warren

We should be able to view people by what profile tags they've added. So, for example:

`https://publiclab.org/people/air-quality` - for people who've added the tag `air-quality` to their profile.

This could be achieved through a variation of this method, in the Users controller:

https://github.com/publiclab/plots2/blob/41fe0807cf39f05f2a75183313c67c946859510d/app/controllers/users_controller.rb#L83-L100

To collect such users, we'd want to add to routes.rb: https://github.com/publiclab/plots2/blob/master/config/routes.rb

And in the Users controller, we'd collect users by their profile tag using:

```ruby
User.find(UserTag.where(value: params[:tagname]).collect(&:uid))
```

Does this make sense? 

Any help appreciated!

This will support https://github.com/publiclab/plots2/issues/317 completion too.

**Comment by rishabhptr** [comment]
@jywarren Can I try this?

**Comment by jywarren** [comment]
Yes please!

**Comment by ryzokuken** [comment]
@jywarren strangely, tags don't show up for me. Anything wrong?

<img width="1680" alt="screen shot 2018-01-26 at 8 01 30 pm" src="https://user-images.githubusercontent.com/13121330/35444222-d0001f96-02d3-11e8-9ec6-c1d8853674d4.png">

**Comment by jywarren** [comment]
It looks like tags are invisible except to admins and the person themselves. Can we change that on these lines:

https://github.com/publiclab/plots2/blob/130d6f8e1c177a062f5a0cc568cd85e348a2d3b4/app/views/users/profile.html.erb#L237-L239

The tag input form should be invisible, but the tags themselves shouldn't be. I think that may take some tweaking of this partial template as well, which unfortunately contains both the tags and the tag input form:

https://github.com/publiclab/plots2/blob/master/app/views/tag/_tagging.html.erb

**Comment by jywarren** [comment]
Maybe that should be its own issue!

**Comment by ryzokuken** [comment]
It should be! Let me make one really quick.
