### ISSUE TITLE
Errors on running in Ruby 2.4

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2075]
We currently support up to Rails 2.3, and you may see errors if you run in Rails 2.4:

https://github.com/publiclab/plots2/issues/1392#issuecomment-359566024

```
/Users/bisweshmohapatra/.rvm/gems/ruby-2.4.1/gems/activesupport-4.1.16/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Fixnum is deprecated
/Users/bisweshmohapatra/.rvm/gems/ruby-2.4.1/gems/activesupport-4.1.16/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Bignum is deprecated
rake aborted!
SystemStackError: stack level too deep
```

We should resolve these to become compatible with Rails 2.4!

Thanks @StlMaris123 @biswesh456 for identifying this issue.

**Comment by namangupta01** [comment]
@jywarren Is this rails 2.3 or ruby 2.4?

**Comment by jywarren** [comment]
Oops, haha -- you're right! Fixed.
