### ISSUE TITLE
bug in "read more" link in question posting form

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2077]
### Please describe the problem (or idea)

> What happened just before the problem occurred? 

I was writing a question, and the hover text suggested i should write a better title and offered a `read more` link. Clicking the `read more` link loaded a very complicated URL and i lost the paragraphs i had already written. 

> What did you expect to see that you didn't?

If we are offering a `read more` link in an editing-interface, it should absolutely load a NEW page and not disturb the page people are on. Especially important because in our editors, we are not using an editing platform that continually saves like GoogleDocs or etherpad. 

### Please show us where to look

https://publiclab.org/questions/new?tags=question:question&template=question&redirect=question

### What's your PublicLab.org username?

> This can help us diagnose the issue: liz

**Comment by jywarren** [comment]
Hi, just for quick recovery, there is a history module, go to https://publiclab.org/post click this button:

![screen shot 2018-01-23 at 11 51 00 am](https://user-images.githubusercontent.com/24359/35288873-e48fd656-0033-11e8-92fd-6da1e6f42ed7.png)

This can recover drafts from the post or question posting pages. 

The button was removed from the Rich Questions form during a design revision to simplify the page, but we can try to find a new place for it, as a break-out issue. 

For this issue, the line of code is actually in this project: https://github.com/publiclab/PublicLab.Editor/

https://github.com/publiclab/PublicLab.Editor/blob/83434d52ef64ca3ad076cc2ff7d43ee284c1c6b3/src/modules/PublicLab.TitleModule.js#L25

we need to add `target="_blank"` to that line!

Thanks for reporting, Liz!

**Comment by Rishabh04-02** [comment]
@jywarren I want to fix this. (first timer)

**Comment by jywarren** [comment]
Solved in https://github.com/publiclab/PublicLab.Editor/pull/121#merged-event !!

**Comment by ebarry** [comment]
awesome!

--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net
