### ISSUE TITLE
Add "people" tab to /spam page for moderators

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2079]
We should add new user profiles to the moderate spam page:

https://publiclab.org/spam

![image](https://user-images.githubusercontent.com/24359/35295339-e4f97350-0046-11e8-9f6b-e37ce1c9513a.png)

We can add a new tab, but the tab would actually lead to http://publiclab.org/people (for now) since moderators can see recently active users and ban them from that page. 

This could be added as a new tab among these lines:

https://github.com/publiclab/plots2/blob/ceb7d05404b4619c7fa8cd8cae5e8215798cb02c/app/views/admin/spam.html.erb#L15-L19

This replaces #42. Any help welcomed, thanks!!!

**Comment by biswesh456** [comment]
Can I claim this?

**Comment by jywarren** [comment]
That would be super! Thank you!!!

On Tue, Jan 23, 2018 at 4:04 PM, Biswesh Mohapatra <notifications@github.com

**Comment by ebarry** [comment]
Oh -- does this exist?

**Comment by jywarren** [comment]
This added a tab that links to /people -- not quite the full spam interface you're looking for, i think!

https://github.com/publiclab/plots2/pull/2109/files#diff-1115f5a5481c6bb3b12ab92d382954ffR19
