### ISSUE TITLE
add https://publiclab.org/spam to moderation emails

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2081]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

We have a nice spam page at http://publiclab.org/spam, but we should highlight that page to the moderators group more. 

## Solution

The emails they get  are a great place to add a link:

https://github.com/publiclab/plots2/blob/ceb7d05404b4619c7fa8cd8cae5e8215798cb02c/app/views/admin_mailer/notify_moderators_of_spam.html.erb#L14

Let's add a link to the moderation page for faster moderation to the emails that get sent to moderators. The above line is a great place to put it -- it'll have to be in HTML, like:

```html
<p>Visit the spam page here: <a href="http://publiclab.org/spam">http://publiclab.org/spam</a></p>
```

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page](https://publiclab.github.io/community-toolbox/#r=all)!

**Comment by JoseGre1** [comment]
Hi @jywarren! I'll be working on this one.

**Comment by jywarren** [comment]
Awesome, thanks!!

**Comment by krishnakode** [comment]
Is this being worked on?

**Comment by jywarren** [comment]
Hi, @JoseGre1 solved it just recently! But there are a lot of issues open at https://publiclab.github.io/community-toolbox/#r=all and we'd love to have your help!
