### ISSUE TITLE
Add rich editor to New Wiki form

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2083]
This is a multi-step issue to add the rich text editor to the new wikis page.

The form for making new wiki pages (for example if you're logged in, at https://publiclab.org/wiki/new) is the old editor -- we should replace it (for new pages only!) with the rich editor, as you see at http://publiclab.org/post (again, if logged in)

The rich editor uses this template:

https://github.com/publiclab/plots2/blob/master/app/views/editor/rich.html.erb

We could copy that to one called `wikiRich.html.erb` in the same directory. 

Then we'd need to adapt the wiki controller to use the new template:

https://github.com/publiclab/plots2/blob/master/app/controllers/wiki_controller.rb#L151

Here's the corresponding section for the main rich editor, where the template is used: https://github.com/publiclab/plots2/blob/ceb7d05404b4619c7fa8cd8cae5e8215798cb02c/app/controllers/editor_controller.rb#L39-L49 (this could be copied or adapted for our use).

This is a few steps but I'm happy to help guide someone through! Thanks!

(solves #1475)

**Comment by SidharthBansal** [comment]
@jywarren May I take this?
I was having fever so was not able to do much last week

**Comment by jywarren** [comment]
Oh, I'm sorry to hear that! Hope you're better! Yes of course you're
welcome to take this one !!

**Comment by jywarren** [comment]
Hi @SidharthBansal -- this looks good, but I think we need a follow-up to add this to the `new` method, now. Would you mind opening a similar one? This was my fault, I should've noted we need both `create` and `new`. 

https://github.com/publiclab/plots2/blob/f524608ac1c65adc6ac91c2c72d76152d870b6a4/app/controllers/wiki_controller.rb#L152

I also think the above line may not work because it'll load an empty page -- it's the correct usage for the `new` template but not `create` -- since `new` is what you see at `/wiki/new`, while you only see `create` once you submit the form. Make sense?

**Comment by SidharthBansal** [comment]
I will create a new issue for create in a while. 
Do you mean that I need to remove the line flash in create? Yeah, create does a HTTP post request so flash would not work. We need that in a new action.

**Comment by jywarren** [comment]
I wonder if as long as we show the `create` action in the same view (legacy vs. rich) as the POST was made in, we don't need the flash? 

Like we could move the flash to the `new` method (although it'd be ideal to still use JS to save the title and body and tags) but when submitting the `create` POST, we just rely on whether there was a `legacy` parameter set to know what to show?

**Comment by jywarren** [comment]
Thanks -- even if we just move this into another issue, and break it into a checklist, that's a good first step. I can unless you're interested?

**Comment by SidharthBansal** [comment]
Yeah I am interested.

**Comment by jywarren** [comment]
Awesome, thanks!! 😄
