### ISSUE TITLE
Implement Various Routes with tagname and authorname

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2084]
### Please describe the problem (or idea)
Currently, the tabs on the /tag/tagname/author/authorname like wiki, maps, contributors are dead links. They needs to be modified
## Idea 
We need to define routes for them like
* /wiki/tag/tagname/author/authorname
* /maps/tag/tagname/author/authorname
* /question/tag/tagname/author/authorname
This will help in soving #928

**Comment by jywarren** [comment]
Great idea!!!
