### ISSUE TITLE
PublicBot error

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2086]
### Please describe the problem (or idea)
I was doing a pull request at plots. I wrote "Fixes #issue_number" but still it is showing me "You must enter like "fixes ..."
![image](https://user-images.githubusercontent.com/20972099/35309227-57f143ee-00d1-11e8-927b-cb53c3463d1a.png)
See the first and the last line of the image

**Comment by seafr** [comment]
I've noticed that too. It does not always happen though. See PR #2078, which is not linked to any open issue. Have you looked at `Dangerfile` in the root folder?

**Comment by SidharthBansal** [comment]
Thanks @seafr It helped a lot in solving the issue.

I found that the dangerfile says that if any commit has message containing #some_number than that will create no message. But if the person has written the issue number in the pr_body then that does not work.
So, @jwarren shall I change 
https://github.com/publiclab/plots2/blob/6051774af117bd32c2af944a23df097d0b2ebaf5/Dangerfile#L5-L7
to
```
unless git.commits.any? { |c| c.message =~ /#[\d]+/ } || github.pr_body.any?{ |c| c.message =~ /#[\d]+/ }
  message "This pull request doesn't link to a issue number. Please refer to the issue it fixes (if any) in the body of your PR, in the format: `Fixes #123`."
```

**Comment by jywarren** [comment]
Awesome! Great catch.

**Comment by seafr** [comment]
You're welcome @SidharthBansal
