### ISSUE TITLE
Author subscription system

### ISSUE THREAD

**Issue by rishabhptr** [publiclab/plots2#2088]
### Please describe the problem (or idea)
We cant follow a node author even though it states that we can follow by tag or author.

> What did you expect to see that you didn't?

Clicking on author name did not do anything , it should either redirect to user's profile or directly make the current user follower of the author.

### Please show us where to look

https://publiclab.org/ ...
![screenshot from 2018-01-24 19-45-22](https://user-images.githubusercontent.com/26951824/35336866-b5ef48ce-013f-11e8-883c-e0d00a93f8b6.png)

### What's your PublicLab.org username?

> This can help us diagnose the issue: rish

**Comment by jywarren** [comment]
This is true, and is a big feature... we may want to think through this a bit before tackling it. We'd want to use `user_selection` in this model:

https://github.com/publiclab/plots2/blob/master/app/models/user_selection.rb

similarly to how we use `tag_selection` in this one, to link users to tags as a "following" type behavior:

https://github.com/publiclab/plots2/blob/master/app/models/tag_selection.rb

Then we'd want to add a method to the subscription controller to create these records when someone goes to a given URL (for following a person):

https://github.com/publiclab/plots2/blob/master/app/controllers/subscription_controller.rb#L33

Finally, we'd want to expand `node.notify` to notify people following a person of new posts by that author:

https://github.com/publiclab/plots2/blob/74b91a5cb65b367ba2f6bfaf7ae3445c474a2da1/app/mailers/subscription_mailer.rb#L6-L16

As you can see this is pretty complex, and we'd want to write tests for it too! But thank you for opening this issue!

**Comment by Gauravano** [comment]
Working on this one!
