### ISSUE TITLE
search function overhaul

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#209]
Our search function is a bit slow (needs optimization) and should perhaps be built on top of an existing search library instead of being a crufted together series of weird SQL queries (https://github.com/publiclab/plots2/blob/master/app/controllers/search_controller.rb#L17-L20)

it'd be great if searching covered:
- [ ] tags
- [ ] user profiles
- [ ] comments
- [ ] mailing lists (from #228)
- [ ] anything else

Searching should more clearly present sortable results by type (map, note, wiki), date, popularity etc. 

Will probably want to use a search engine like one of these: http://stackoverflow.com/questions/737275/comparison-of-full-text-search-engine-lucene-sphinx-postgresql-mysql

Also good notes on autocompletion: http://railscasts.com/episodes/399-autocomplete-search-terms

**Comment by ebarry** [comment]
Our web search could also include mailing list results, as described in [228](https://github.com/publiclab/plots2/issues/228)

**Comment by btbonval** [comment]
As noted by @ebarry , I think we can roll #228 into this ticket as part of the overhaul and then we can close out the other ticket.

**Comment by jywarren** [comment]
+1

**Comment by btbonval** [comment]
@jywarren sez:

        Note: this'd probably involve 2 new tables for topics and messages so we could cache/search
        archive all mailing list activity. topics might have a column called "list" with the name of the 
        corresponding google group, so we wouldn't need a 3rd table. 

regarding mailing list caching. I feel like Google should cache everything and have a searchable API. We simply need to union Google's API results into our database results. I don't think caching the mailing lists is our responsibility.

**Comment by btbonval** [comment]
we would want a table of mailing lists to parse, though.

**Comment by btbonval** [comment]
hrm, it looks like Google Groups might not have any APIs for accessing group data. Only group administration API and an API to push messages into a group.

* https://developers.google.com/admin-sdk/directory/v1/guides/manage-groups
* https://developers.google.com/admin-sdk/groups-migration/v1/guides/manage-email-migrations

Why would the search king not make it easy to search groups?

There is this "API", but you must be signed into Google with a cookie if the list is closed, and you must scrape the incoming HTML to extract relevant data:

* `https://groups.google.com/forum/#!searchin/{MAILINGLIST}/{QUERY}`
  * e.g. https://groups.google.com/forum/#!searchin/publiclaboratory/italian

**Comment by btbonval** [comment]
@ebarry I don't see any good way to integrate google groups messages. We could send a query against each mailing list, parse it for number of results, and if the results are non zero, each result could be presented somewhere.

It might be easier to simply add an iframe with each mailing list search query. Let google completely handle the situation, and we just have a little window into it. I don't know how to visually set that up

**Comment by jywarren** [comment]
GG has been neglected for a while, and I recall not finding much of an API.
I think it'd be a good idea for archival reasons to cache GG history on our
site -- it'd make searching easier but also mean we could eventually have
more flexibility in the option to leave GG. But it is a doozy, as mentioned
before :-P

**Comment by btbonval** [comment]
Yeah it's like super annoying to have to do that. I was just inspecting the network traffic to see if GG uses any JSON calls to interrogate the backend. As far as I can tell, the whole search page is one request which generates one HTML response. ugh.

**Comment by btbonval** [comment]
You know, I think iframes are still a better solution for this ticket.

What you're talking about should be done as a separate project on the path to leaving GG, and requires a lot more forethought and planning than the usual hackery done just to get this job or that job done.

**Comment by jywarren** [comment]
Short term, i agree re: better solution -- or just a button that says
"search for this across PL discussion lists"

Long term I think we need to plan for the doozy; maybe reopening the issue
that was merged into this one makes sense for that.

**Comment by btbonval** [comment]
It is as much plots as it is mapknitter, infragram, and all others.

It would be its own project: the PL mailing list project.

**Comment by btbonval** [comment]
Having it as its own project also gives us a more logical framework for creating our own solution later, as that's where the solution's web service code would lie.

**Comment by jywarren** [comment]
Making it a searchable table(s) in plots2 would make sense though.

**Comment by btbonval** [comment]
I disagree. Plots2 != mailing lists. Plot2 == research notes and wikis. MapKnitter != mailing lists. Infragram != mailing lists.

It doesn't belong to any one project.

**Comment by btbonval** [comment]
Having a viewport into the mailing lists from other projects is fine and recommended, but I don't think plots2 should be conflated to the purpose of maintaining all contents of all mailing lists.

**Comment by jywarren** [comment]
I could be persuaded. Do other folks have thoughts?

**Comment by btbonval** [comment]
Just to clarify proposals:

* @jywarren wants to build a few tables into the database of plots2's research notes, wiki pages, and user accounts which tracks all mailing list activity, and then write search code for the mailing lists into plots2's web code
* @btbonval wants to build a fresh database with a fresh code base to track and store the mailing list activity, and then run it as a web service like `lists.publiclab.org` which can be searched by plots2, mapknitter, infragram, etc. it's a longer term goal, but cleaner in the long run
