### ISSUE TITLE
Sorting wiki pages on /wiki by Last Edited is not working

### ISSUE THREAD

**Issue by namangupta01** [publiclab/plots2#2092]
### Please describe the problem (or idea)
In https://publiclab.org/wiki/
Last Edited is not working properly --not sorting the topics by last edited
![screen shot 2018-01-24 at 9 35 50 pm](https://user-images.githubusercontent.com/20709985/35342770-e5ab5efe-014e-11e8-8b25-7f944029e9f9.png)

**Comment by jywarren** [comment]
Hi, @namangupta01 can you link to where this ought to be written in the code? I think... the wiki controller?

Great catch, thank you!

**Comment by namangupta01** [comment]
@jywarren i tried for this bug in development environment and everything seems to be working fine but why it is not working on production.
There are many things that are working in development environment but not working in production.

**Comment by jywarren** [comment]
that is odd. Can you think of some test data we could add which would bring
this error to life in the tests? Good tests are based on good test fixtures
data... i hope we could reproduce this!

**Comment by SidharthBansal** [comment]
I have encountered the same behavior while solving the #1930 
They are getting sorted correctly in the development environment according to the name but in the production it is not working @jywarren 
I will also try to have tests that can solve these similar issues
