### ISSUE TITLE
Deep links load content hidden underneath our menu bar and ribbon

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2093]
### Please describe the problem (or idea)

> What happened just before the problem occurred?

I clicked the timestamp to a particular comment i needed to link to, and it created this URL that loaded the content so high that it was completely hidden under the menu bar or the ribbon. Luckily, I knew what i was expecting to see , so i knew to scroll up to find it, but someone who doesn't know what to expect when clicking the link could get completely confused because of this. 

> What did you expect to see that you didn't?

I expected to see the top of the content i linked to. 

### Please show us where to look

https://publiclab.org/questions/warren/11-14-2017/what-s-one-thing-that-could-be-better-for-newcomers-about-the-public-lab-website#answer-0-comment-17687

Here's an example matching the screenshot below: https://publiclab.org/wiki/public-comment#What+is+Public+Comment?

![screenshot 2018-01-24 at 1 16 13 pm](https://user-images.githubusercontent.com/24359/35349398-cb2e2f02-0108-11e8-857f-7303b0ff909c.png)

**Comment by jywarren** [comment]
Fixed for wiki headings here: #2512 by @patcon -- thanks! 👍 👍 🎉 

please test this out!

Related work by @namangupta01 here for Answers: https://github.com/publiclab/plots2/pull/2146
