### ISSUE TITLE
Adjust date of comments that are changed to answers on /questions

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#2099]
A new feature was added that allows people to move comments on /questions to answers. However, when comments are now adjusted, a new email goes out and the date of the original post is not maintained. 

Here's a link to the code: https://github.com/publiclab/plots2/blob/ceb7d05404b4619c7fa8cd8cae5e8215798cb02c/app/controllers/comment_controller.rb#L154-L157

**Comment by jywarren** [comment]
Let's work on ensuring the dates are set to the original comment date first. 

Then, we can suppress the emails by removing this line: https://github.com/publiclab/plots2/blob/ceb7d05404b4619c7fa8cd8cae5e8215798cb02c/app/controllers/comment_controller.rb#L161

Thanks, @steviepubliclab !!

**Comment by Gauravano** [comment]
Hi @steviepubliclab, I have implemented this feature so I am well familiar with the code.Can I help to resolve this? Thanks.

**Comment by jywarren** [comment]
@Gauravano yes please, that would be fantastic!!

**Comment by Gauravano** [comment]
Thanks, @jywarren .Actually @jywarren @steviepubliclab I have a suggestion regarding email like we have an email for a new answer, comment.etc. Can we make notification mail for this feature too?

**Comment by jywarren** [comment]
Hi, i think we already notify for new answers and comments, but we have
been interested in a "welcome email" feature for when people sign up for
the site initially. Would you wan to make a new issue for that and we can
try to draft what such an email should include?

Thanks, Gaurav!

**Comment by Gauravano** [comment]
I am definitely interested in taking this one.Thanks, Jeff.

**Comment by jywarren** [comment]
awesome!!!
