### ISSUE TITLE
Remove link to /lists from sidebars

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2100]
### Please describe the idea

> What problem could this idea solve?

We are in a year long transition off Google Groups. Let's begin de-emphasizing how much we direct people at the Google Groups by taking out this section of the sidebar that directs people at the GoogleGroups on https://publiclab.org/lists: 

<img width="338" alt="screen shot 2018-01-24 at 4 40 47 pm" src="https://user-images.githubusercontent.com/161439/35358685-7962dd68-0125-11e8-9f51-110dafa3497a.png">

### Please show us where to look

https://publiclab.org/questions/

### What's your PublicLab.org username?

> This can help us diagnose the issue: 
Liz

**Comment by jywarren** [comment]
The template for this section is here!

https://github.com/publiclab/plots2/blob/ceb7d05404b4619c7fa8cd8cae5e8215798cb02c/app/views/sidebar/_related.html.erb#L16

**Comment by ryzokuken** [comment]
@publiclab/reviewers can anyone volunteer to make this an FTO? It's pretty simple:

1. Delete the template partial.
2. Remove this line of code.

@jywarren did I miss anything?

**Comment by jywarren** [comment]
+1!!!

**Comment by SidharthBansal** [comment]
@ryzokuken, @jywarren I will make it soon

**Comment by ryzokuken** [comment]
@SidharthBansal Awesome! As soon as you do, link back to it in here and we will close it.

**Comment by SidharthBansal** [comment]
Issue #2117 created
