### ISSUE TITLE
Stop showing discussion lists messages on the dashboard

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2101]
### Please describe the problem 

We've made some choices to route website notifications into the GoogleGroups so people get used to interacting directly with content on the website by tag, however, that also has a downside: **the Discussion Lists tab on the /dashboard is currently showing entirely website notifications.**  I suggest this has adverse effects on the human mind. 

> What happened just before the problem occurred? Or what problem could this idea solve?

I clicked the discussion list tab on the dashboard

> What did you expect to see that you didn't?

i expected to see humans talking, but it was only bots. 

### Please show us where to look

https://publiclab.org/dashboard

<img width="387" alt="screen shot 2018-01-24 at 5 08 11 pm" src="https://user-images.githubusercontent.com/161439/35360015-3c8d5f08-012a-11e8-91da-41be186422fd.png">

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

Oh, it's Liz, again.

**Comment by ebarry** [comment]
One option is to stop displaying the GoogleGroups on the dashboard. (It was a great try at integration which was nice for a long while until we started sending website notifications into the googlegroups, which we then re-print on the dashboard next to the actual content)
What do you think?

**Comment by jywarren** [comment]
👍 stop showing it. I'd prefer to spend time on that than to try to filter the list! Can you change the name of the issue accordingly if you agree? Thanks!

**Comment by jywarren** [comment]
And then tag this `help-wanted` ? The code for this is here:

https://github.com/publiclab/plots2/blob/74b91a5cb65b367ba2f6bfaf7ae3445c474a2da1/app/views/dashboard/_sidebar.html.erb#L26-L47

We could remove the entire tab, and get rid of the tabs, leaving just wiki edits, for now.

**Comment by ebarry** [comment]
Over in https://github.com/publiclab/plots2/issues/2076 i wrote: 
> I have an idea to help make room for this: remove the righthand column with two tabs for "wiki" and "discussion lists". Instead, add these into the checkbox where you can choose to see research notes, questions, events, and comments

Could we remove the entire tab of `wiki / discussion lists` and plan to add the wiki pages into the content selection dropdown as part of addressing #2076 ?

**Comment by jywarren** [comment]
I think we could, but perhaps as a follow-up. The wiki listings are complicatedly entangled, because we move them into the main list on smaller screens. It's done in JS, here: https://github.com/publiclab/plots2/blob/7f018e64ba2cffa2f1c53826fc09015b6864ba83/app/assets/javascripts/dashboard.js#L77

So maybe we can start with the simpler item, or if you'd like we can try untangling that code more. Like, i think we'd have to remove this style to show wikis in the main feed:

https://github.com/publiclab/plots2/blob/7f018e64ba2cffa2f1c53826fc09015b6864ba83/app/assets/stylesheets/dashboard.css#L275-L279

**Comment by ryzokuken** [comment]
@ebarry @jywarren Should I proceed and just remove the entire section, or is there some catch here?

**Comment by ebarry** [comment]
Reading through @jywarren's comments, i think just removing the tab for "Discussions" would be great for now. We'll deal with the wikis later.

**Comment by jywarren** [comment]
...omnious... :-P
