### ISSUE TITLE
[DRAFT] Reduce "above the fold" space on dashboard given to the /Blog

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2102]
### Please describe the problem (or idea)

> What problem could this idea solve?

The dashboard is precious, and arguably spends too much precious "above the fold" space saying its own name. The rest of the above the fold space is given to the blog: 
<img width="1233" alt="screen shot 2018-01-24 at 5 23 41 pm" src="https://user-images.githubusercontent.com/161439/35360456-c67ca7ea-012b-11e8-97c2-30071e2e732f.png">

> What did you expect to see that you didn't?

Less room given to the blog. 

We could also consider streamlining the very top of the page, although the white space is nice I think it could be better somehow: 

<img width="1206" alt="screen shot 2018-01-24 at 5 28 31 pm" src="https://user-images.githubusercontent.com/161439/35360536-0b3ff760-012c-11e8-990d-628fd372c5b7.png">

### Please show us where to look

https://publiclab.org/dashboard

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hi, Liz, i'm going to tag this with `more-detail-please` and `design` because i think this may need discussion -- it's not ready for someone to take on just yet (i.e. we don't want someone to start removing these just yet!)

**Comment by ryzokuken** [comment]
I agree that we should probably remove the text "Dashboard", it's kinda repetitive/redundant. I mean, the user knows:

1. The URL of the current page is `publiclab.org/dashboard`
2. They clicked on a link that most probably said "dashboard" to get here. (Okay, they were probably redirected here from the site root)

Also, we have a huge banner occupying vertical screen space which conveys an important message but which *should* be, IMO, dismissable (@ebarry @jywarren wdyt?)

<img width="1680" alt="screen shot 2018-01-25 at 8 16 21 pm" src="https://user-images.githubusercontent.com/13121330/35394121-db9d0bba-020c-11e8-9d80-e70c76f2806f.png">

**Comment by oorjitchowdhary** [comment]
Can we close this as the `dashboard` redesign discussion is open at https://publiclab.org/notes/edie_blues/12-13-2018/public-lab-dashboard-new-design-ideas ..
@publiclab/reviewers

**Comment by gauravano** [comment]
Hi @oorjitchowdhary let's keep it open till @jywarren @ebarry reply. Maybe this can be used as an idea for the new design. Thanks!

**Comment by ebarry** [comment]
I am totally fine with closing this now that @edieblu has this great work going on: https://publiclab.org/notes/edie_blues/12-13-2018/public-lab-dashboard-new-design-ideas
