### ISSUE TITLE
Questions are not listed on /questions

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2107]
### Please describe the problem (or idea)
I am not able to see the questions listed on https://publiclab.org/tag/tagname
![image](https://user-images.githubusercontent.com/20972099/35373192-7838000a-01c3-11e8-9fcd-41d4f7b42aef.png)
Also, see https://publiclab.org/questions/
None of the tabs is working --Recently asked, Recently answered, Popular ,Unanswered, Liked
![image](https://user-images.githubusercontent.com/20972099/35373278-e300abf8-01c3-11e8-8238-0467d3ef2ae2.png)
![image](https://user-images.githubusercontent.com/20972099/35373297-ee6b9ebc-01c3-11e8-9166-02fdb9f4360f.png)
![image](https://user-images.githubusercontent.com/20972099/35373310-f70b2056-01c3-11e8-9bf4-b61b9d85c079.png)
Similarly for other tabs

**Comment by ebarry** [comment]
I have this same bug, but only sometimes!!!!!  Like, i couldn't see them yesterday, but this morning even without a restart of my computer, i can see them again! We have tried to squash this bug before as well, don't remember where....

**Comment by ryzokuken** [comment]
@publiclab/reviewers any idea why this must be happening? Local cache corruption?

@SidharthBansal could you confirm this by verifying that a certain question doesn't show up and try again after clearing your system cache? If the question shows up later, that could help us narrow down the possibilities.

**Comment by SidharthBansal** [comment]
@ryzokuken  yeah now it is working fine after clearing the browser's cache

**Comment by ryzokuken** [comment]
Then it probably has something to do with the browser cache

@publiclab/reviewers let's see if we can figure out how to manage our cache in a better way?

**Comment by jywarren** [comment]
wow, do we have any code that puts things in cache? This page used to use
cookies, but I believe we removed that code.

https://github.com/publiclab/plots2/tree/master/app/views/questions/index.html.erb

https://github.com/publiclab/plots2/tree/master/app/controllers/questions_controller.rb

Thanks for looking into this!

**Comment by jywarren** [comment]
Could you both try clearing cookies, and then report back if it ever happens after that? We really need to figure out what actions lead up to this occurring if we want to try to reproduce it! Nobody's hitting the back button, i assume?

**Comment by SidharthBansal** [comment]
After clearing cookies, I am not facing any problems

**Comment by jywarren** [comment]
FOUND THE PROBLEM!!! After like, years.

The issue is that if you disable questions on your dashboard, they are disabled on https://publiclab.org/questions:

![questions1](https://user-images.githubusercontent.com/24359/43555382-d6c05706-95c7-11e8-8ec5-9c5210a29aa2.gif)

We will need to adjust the `dashboard.js` file so it doesn't affect the questions page!

https://github.com/publiclab/plots2/blob/05636a66132d1fbfdc1f321025a24fd5d3d55020/app/views/questions/index.html.erb#L62
