### ISSUE TITLE
[DRAFT TO CONSIDER] create feature at top of /tags

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2110]
### Please describe the problem (or idea)

> What problem could this idea solve?

Over in https://github.com/publiclab/plots2/issues/179, I raised the issue of how do we help people subscribe to the right content when there are so many tags compared to the limited number of googlegroups that was easier to choose from. @jywarren suggested that we could create a feature: 

>Manually choosing a subset of "featured tags" seems like something we could/should do in content, not code. If you have the list of tags, we can make a Feature out of it and display that -- like how we do banners. (this helps us keep the code generalizable so it may be used by non-Public Lab groups in the future, it also makes it easier to change the list of chosen tags without rebooting the server)

This is going to be part of https://github.com/publiclab/plots2/issues/2104

**Comment by ryzokuken** [comment]
Hi Liz!
Had been wondering: 
Does "just keeping a list of **featured tags** that show up at the top of the `/tags` page" suffice?

**Comment by jywarren** [comment]
We could follow a similar approach to https://github.com/publiclab/plots2/issues/208 but inserting the feature code at the top of this template:

https://github.com/publiclab/plots2/blob/master/app/views/tag/index.html.erb

with the feature name `featured-tags` -- and then we can manage that via the features system!

**Comment by ryzokuken** [comment]
@jywarren I'll take a look at both of these. I am new to features and everything, so I'd have to do a little research. Is there some documentation you could point me to?

**Comment by jywarren** [comment]
we need better docs, unfortunately. But that linked issue shows how to set
one up, and then admins can edit them at the route /features -- they cache
and the cache is flushed each time you save the feature. They are nodes!

**Comment by ryzokuken** [comment]
That's helpful! I would try to make sense of both of these issues as soon as possible and submit a patch.

**Comment by jywarren** [comment]
awesome.

**Comment by jywarren** [comment]
Just realized there's some documentation here! https://github.com/publiclab/plots2/blob/master/doc/DATA_MODEL.md#nodes

**Comment by jywarren** [comment]
Made into a first-timers issue in #2260 !
