### ISSUE TITLE
Update "read more" link on tag pages to "learn more on the wiki page"

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2112]
### Please describe the problem

Our "read more" link on the tag pages uses language that Facebook uses as "expand post on same page" but we use it to load an entirely new page which confuses the user, as articulated by our pro-bono UI consultant in https://docs.google.com/document/d/1796lMEwSjUawamKIYebbsSikFBBboVK5lZ6jZFKJLXI/edit

> What did you expect to see that you didn't?

With the "read more" text, people who are more familiar with Facebook than with PublicLab.org (AKA everyone on the planet except for ~25 people) may expect to see that more text or a paragraph unfurls right there on the tag page. 

### Please show us where to look

https://publiclab.org/tag/kite-mapping
<img width="434" alt="screen shot 2018-01-25 at 10 09 36 am" src="https://user-images.githubusercontent.com/161439/35395262-e28605ee-01b7-11e8-8285-f4c6c0434116.png">

**Comment by ryzokuken** [comment]
Did I add that link? 😛 

Anyway, I think I could change the name of the link to something that better describes the action and add a *real* "Read More" link if that's all what is needed.

**Comment by ryzokuken** [comment]
Indeed it was I who added the deceptive link, hindsight is 20/20. Will make the required changes.

<img width="1666" alt="screen shot 2018-01-25 at 8 45 49 pm" src="https://user-images.githubusercontent.com/13121330/35395603-d8336e2a-0210-11e8-8ff0-e64d0bf96009.png">

**Comment by namangupta01** [comment]
@ebarry we can use js request to implement this instead of html request easily! I would create a pr soon.

**Comment by jywarren** [comment]
Hi, I want to be cautious here -- @ebarry are you suggesting we load the whole wiki page inline here? Could we consider simpler approaches to the problem you describe, such as:

* styling the link as a button
* using a `on external link` icon from FontAwesome
* changing the text from `Read more` to something else?

https://github.com/publiclab/plots2/blob/c58808bfbde107d7cbde157100d0bf864544b950/app/views/tag/show.html.erb#L14

**Comment by ryzokuken** [comment]
@jywarren I'd rather believe that she intends us to:

1. Change the text of the link that currently says "Read More" to perhaps something like "Visit Wiki Page" as it seems kinda deceptive. (Principle of least surprise, remember?)

2. If the text is too long, clip it to remain short and expand it upon the user clicking a *real* "Read More" button.

**Comment by jywarren** [comment]
I'm ok with either, just suggesting that an easier fix could be 1), in case
that's preferred, but I defer to @ebarrry!

**Comment by ebarry** [comment]
Yes, #1 as @ryzokuken details is what i meant, just change the text on the link! 

Thank you @namangupta01 ! let's use js somewhere cool elsewhere!

**Comment by ryzokuken** [comment]
I'll hop on to this one in a jiffy.

**Comment by ebarry** [comment]
AWESOME!!!
Building on the success of fixing this, is there something we can do to the "Show more" link at the bottom of grids (of questions, of activities) that opens but does not close?

For instance, see https://publiclab.org/wiki/timelapse

![show-more-link](https://user-images.githubusercontent.com/161439/35645288-5e451e5a-0699-11e8-82d2-d01fa7528457.gif)

**Comment by ryzokuken** [comment]
@ebarry Sure! Do you have the time to make another issue for this, or should I? If you do, assign it to me and I will take care of it as soon as possible.
