### ISSUE TITLE
Login through Oauth

### ISSUE THREAD

**Issue by biswesh456** [publiclab/plots2#2113]
Please describe the problem (or idea):

It is always better to use a google or facebook oauth to log in instead of having a separate account for various sites. So I propose to add google, facebook oauth to publiclabs. I would also like to work on it on my own.

Can I have any suggestions or advice?

**Comment by ryzokuken** [comment]
I guess a lot of people have shown interest in working on OAuth lately. You need to coordinate with the rest of the community in order to make sure that others aren't working on the exact same thing.

**Comment by jywarren** [comment]
We'd love your help, possibly with one of the subsequent integrations --
Twitter, or something? You can catch the latest here -- thanks for pitching
in!

https://github.com/publiclab/plots2/issues/683

**Comment by biswesh456** [comment]
Ya sure would add that also.

**Comment by jywarren** [comment]
Super :-)))))
