### ISSUE TITLE
Add tooltips to all wiki bar icons

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2115]
### Please describe the problem

> What problem could this idea solve?

Not all icons at the top of wiki pages have the nice tooltips that that the "use in-line editor" and the "read comments" icons have. Let's add tooltip text to all icons on the wiki bar. 

![wiki-bar](https://user-images.githubusercontent.com/161439/35397792-5ff6e664-01be-11e8-83cc-5b33c30217e8.gif)

* `Edit this wiki page` for the regular edit pencil
* `Delete this wiki page` (only admins will see this one but still)
* `practice in a realtime doc` or something for the two conversation bubble icon that links to etherpad (more on the icon below)
* `View previous versions of this page` for revisions

Related: **can we find a different icon for the link to etherpad**? the two bubble conversation chat icon is a little misleading because we use nearly that same icon to link to the actual chatroom where there are people to talk to.

### Please show us where to look

and wiki page, for instance https://publiclab.org/wiki/partners

**Comment by ViditChitkara** [comment]
The tooltips need to be added for:-
https://github.com/publiclab/plots2/blob/c58808bfbde107d7cbde157100d0bf864544b950/app/views/wiki/_header.html.erb#L59
https://github.com/publiclab/plots2/blob/c58808bfbde107d7cbde157100d0bf864544b950/app/views/wiki/_header.html.erb#L73
https://github.com/publiclab/plots2/blob/c58808bfbde107d7cbde157100d0bf864544b950/app/views/wiki/_header.html.erb#L81
https://github.com/publiclab/plots2/blob/c58808bfbde107d7cbde157100d0bf864544b950/app/views/wiki/_header.html.erb#L88
Just like we have tooltip fo rich editorr:-
 https://github.com/publiclab/plots2/blob/c58808bfbde107d7cbde157100d0bf864544b950/app/views/wiki/_header.html.erb#L65

**Comment by Apoorva-13** [comment]
Hey! Can I take up this issue?

**Comment by namangupta01** [comment]
@Apoorva-13 Yes, go ahead! Feel free to ask if you need some help!

**Comment by SidharthBansal** [comment]
@Apoorva-13 Do you need any help?
I am happy to help

**Comment by Apoorva-13** [comment]
Thanks! Would surely get back to u with my queries.
