### ISSUE TITLE
Replace the bower+rails asset pipeline with yarn+webpack

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plots2#2118]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

Bower has been officially deprecated for almost a year now, and people in the frontend world have slowly drifted away from the world of bower, gulp-based asset management and `<script>` tags to yarn, webpack and ES6 `import`s respectively. It would be only prudential for us to upgrade our frontend asset management.

## List of Resources:

* https://github.com/rails/webpacker
* http://nithinbekal.com/posts/yarn-rails/
* https://sheerdevelopment.com/posts/using-yarn-with-rails
* http://samuelmullen.com/articles/replacing-the-rails-asset-pipeline-with-webpack-and-yarn/

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hi, this would be great -- could you merge this with #1215 and outline some potential next steps? Thanks!

**Comment by ryzokuken** [comment]
@jywarren Closing this and adding relevant information to #1215
