### ISSUE TITLE
Error page when trying to reset my password

### ISSUE THREAD

**Issue by weatherpattern** [publiclab/plots2#2122]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I am trying to reset my password. I entered my email address and got the reset password email. When I click on the link, I get this message: 

```
Password reset failed. Please contact the web team if you are having trouble.  (Error: no user with that key)
```

> What did you expect to see that you didn't?

I am expecting to see the reset password page.

### Please show us where to look

https://publiclab.org/reset/

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

weatherpattern

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

Chrome Version 63.0.3239.132 (Official Build) (64-bit)
MacOS 10.10.4

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Thank you for reporting! We'll take a look and see what we can do!

Folks -- the code is here: https://github.com/publiclab/plots2/blob/master/app/controllers/users_controller.rb#L192-L230

Not sure exactly what's going on, but I do notice we have tests for this, so not sure what's going on:

https://github.com/publiclab/plots2/blob/09c9241b8e304e8e60f2264503173d312114e51f/test/functional/users_controller_test.rb#L97-L117

Note that @weatherpattern originally had a `DrupalUser` record only, and was upgraded using this function:

https://github.com/publiclab/plots2/blob/09c9241b8e304e8e60f2264503173d312114e51f/app/models/drupal_user.rb#L170-L183

**Comment by rachaelkiteme** [comment]
Hi @jywarren , am still a beginner and I would love to contribute on publiclab, but with a little help will be able to work on this.

**Comment by ryzokuken** [comment]
Hi, @rachaelkiteme! Sure, you may feel free to start working on this. If you face any trouble, you can ask here or on our chatroom.

**Comment by rachaelkiteme** [comment]
Hi,

Thank you so much Ujjwal Sharma. Will let you know case of anything.

Regards
Rachael

Regards
Rachael

**Comment by ebarry** [comment]
Exciting! This is still an outstanding bug, it would be great to have this fixed!

**Comment by rachaelkiteme** [comment]
Thank you Liz, am also thankful to have such a great bug. Am working on it,
case of any difficulties will let you know for assistance.

Thank you.

Regards
Rachael

**Comment by jywarren** [comment]
Hello, i worry this may be a difficult one to reproduce; have you been able to duplicate what @weatherpattern saw? If not, we may need to dig into logs a bit more to try to find the issue there.

**Comment by jywarren** [comment]
Hi, @weatherpattern -- can you email me the notification email you just received? 

@rachaelkiteme we'd love to have your help but without this extra information i think i'll be tough to solve it -- we won't know what's going wrong! 

@ebarry if you could reach out to Ray to get the email forwarded we can take the next step here. Thanks!

Thanks all!

**Comment by jywarren** [comment]
actually @rachaelkiteme if you'd like to check if we have a test for these lines of code -- a post to the `/email` action of `/app/controllers/users_controller.rb` in our functional tests (`/test/functional/users_controller_test`):

https://github.com/publiclab/plots2/blob/df33dfec5f7a3d26e17fec36218d99861059ad88/app/controllers/users_controller.rb#L221-L229

If we pass in the parameter `email` it should assign a `user.reset_key` -- i'm not sure that's happening here!

**Comment by weatherpattern** [comment]
This is the email I received. Removed the code at the end of the URL. The link still goes to the home age with this error message: Password reset failed. Please contact the web team if you are having trouble. (Error: no user with that key)


EMAIL:
Dear weatherpattern,

Someone (probably you) has requested a reset of your password. To reset your password, click here:

http://publiclab.org/reset/key/[removed]

=========================

This link may only be used once. If you believe you have received this in error, please ignore this email. Please contact web@publiclab.org if you believe your account is at risk.

Check out the blog at https://publiclab.org/blog | Love our work? Become a Public Lab Sustaining Member today at https://publiclab.org/donate

**Comment by jywarren** [comment]
great, thank you! OK, so I think the code is not being generated or maybe
just not saved... i don't see the reset_key in the database -- it's nil. We
should write the functional test and follow up that way.

@weatherpattern i'll email you a key that should work.

**Comment by jywarren** [comment]
OK - this line needs to changed to `u.update_attribute(reset_key: key)` -- to correctly save the `reset_key`!

https://github.com/publiclab/plots2/blob/1dfccf7098714d090b2fd19e628f80ad58a1a07b/app/models/user.rb#L111

But we should still write the test!

**Comment by jywarren** [comment]
... actually we'll be deprecating the whole migration system pretty soon. Maybe we don't need a test... this is pretty good documentation of this issue. It won't be around for long. 

We would want to remove this line too though:

https://github.com/publiclab/plots2/blob/master/app/controllers/users_controller.rb#L224

**Comment by weatherpattern** [comment]
So it's working for me now. But look like there is some coding to be done. So, when that's complete feel free to close the issue.

Thanks to all for your help!

**Comment by jywarren** [comment]
thank you too!

**Comment by rachaelkiteme** [comment]
Hello,

@jeffreywarren I followed the conversation and got confused on what am
supposed to do, please help me know my next take on this issue.

Thanks in advance.

Regards
Rachael

**Comment by jywarren** [comment]
No problem! 

See, this line needs to changed to `u.update_attribute(reset_key: key)` -- to correctly save the `reset_key`!

https://github.com/publiclab/plots2/blob/1dfccf7098714d090b2fd19e628f80ad58a1a07b/app/models/user.rb#L111

Do you think you could make that change? Thanks!

**Comment by rachaelkiteme** [comment]
Hello,

Let me check on it, will let you know if I cant't make it.

Regards
Rachael

**Comment by rachaelkiteme** [comment]
Hello, I managed to make changes to the user.rb file and made a pull
request. Thank you so much for your assistance have learnt something.

Case of any pending issue on the commit let me know.


Regards
Rachael

**Comment by jywarren** [comment]
Thanks @weatherpattern this is solved now by @rachaelkiteme -- thanks to everyone for getting this done!!!
