### ISSUE TITLE
configurable email notification preferences

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#213]
We are having settings at /settings as we might wanna add more settings in future. Below are the settings which would be added to settings page: 

Asking: Do you want to be notified by email for (with toggles):

- [x] comments on your posts
- [x] comments on all posts you've commented on
- [x] likes on your posts
- [x] notes on a topic (we have this already!)
- [ ] notifications for wiki page edits: https://github.com/publiclab/plots2/issues/396 (after all the rest!)
- [ ] The monthly blog would be everything tagged `blog` once per
month? What user tag would that be? (by @jywarren )
- [x] Digest- weekly
- [x] Digest - daily

**Comment by ebarry** [comment]
This seems to relate to how the button "subscribe to everything" on publiclab.org/subscriptions in fact only subscribes you to research notes, a fact which we have to explain in help text below the button

**Comment by jywarren** [comment]
that's a great issue to break off as a stand-alone -- maybe good for
first-timers!

**Comment by Gauravano** [comment]
hi @jywarren @ebarry , I have included this issue as a part of my proposal https://publiclab.org/notes/gauravano/02-18-2018/gsoc-proposal-email-integration-project 

![notification_screenshot](https://user-images.githubusercontent.com/20878070/37738062-ca4947c6-2d7b-11e8-9ebc-9afe7d7c632a.png)

![notification_settings](https://user-images.githubusercontent.com/20878070/37738082-dc2aeea4-2d7b-11e8-936f-d6e9fe7f5cad.gif)

What do you think about design ?

**Comment by jywarren** [comment]
Oh cool! I wonder about mobile display, but if it's an issue we can
probably put it in a regular page instead of a modal - either way is
awesome!

**Comment by Gauravano** [comment]
Sure @jywarren , we can put it in the page, right now there are only a few setting options so I thought modal would look nice.

**Comment by jywarren** [comment]
i do think it looks nice! Just thinking ahead in case it doesn't render
well on mobile. :-)

**Comment by Gauravano** [comment]
Hey @jywarren , can you review my proposal https://publiclab.org/notes/gauravano/02-18-2018/gsoc-proposal-email-integration-project now if it's possible. Thanks.

**Comment by Gauravano** [comment]
hi @jywarren @ebarry , I have rendered the design on a separate page and also tested on mobile. Here's preview:-

![ui_setting_screen2](https://user-images.githubusercontent.com/20878070/37788074-8a3e8d98-2e26-11e8-84b1-48d03c1ebe7c.png)

![ui_settings2](https://user-images.githubusercontent.com/20878070/37788075-8a74a4fa-2e26-11e8-97a4-3644ca2f9cf4.gif)

**Mobile view:-**

![screenshot_20180322-230522](https://user-images.githubusercontent.com/20878070/37788167-c125a6a2-2e26-11e8-92b3-19939b976211.png)

![screenshot_20180322-230541](https://user-images.githubusercontent.com/20878070/37788166-c0e5ee90-2e26-11e8-8b3d-491c5de301a1.png)

**Comment by Gauravano** [comment]
hi @jywarren, I can include all the above-mentioned items of the checklist on the Settings page, could you please suggest relevant tag names for each. Thanks.

**Comment by jywarren** [comment]
This sounds great. Can you suggest a first draft list and I can provide some edits or suggestions?

**Comment by Gauravano** [comment]
Tag Names: 
1. For direct comments on author's own post -  `comment_direct:true`
2. For indirect comments i.e., on posts where the current user has commented - `comment_indirect: true`
3. Likes on your post - `post_like:true`

How about these @jywarren?

**Comment by jywarren** [comment]
we could also do `notifications:comment-direct` and
`notifications:comment-direct` and just have non-existence be "off" -- what
do you think? so each one would start with a common prefix of
`notifications:_____`?

**Comment by Gauravano** [comment]
Sounds good to me!

**Comment by Gauravano** [comment]
hi @jywarren in reference to our last tag approval, I have some idea about it. Normally, users change settings once a while, so instead of generating 5 to 6 tags for each profile, we can generate tag if a user doesn't want to receive notification related to a particular setting. What do you think?

**Comment by jywarren** [comment]
So we'd have a set of defaults that don't require a tag to be set, right -- that does make sense. So what would be the defaults? We'd want to document those clearly somewhere. 

Good thinking! 👍

**Comment by Gauravano** [comment]
Yes, we should definitely document them - let's think of some names related to these tags only-
`notifications:comment-direct` like `no-notifications:comment-direct` or `no-notify:comment-direct`. What do you think @jywarren ?

**Comment by jywarren** [comment]
How about:

`notify-comment-direct:false` -- this goes back to your earlier way, but given the default "on", it makes sense. 👍

**Comment by Gauravano** [comment]
Great! I will complete PR shortly. Thanks!

**Comment by Gauravano** [comment]
Hi @jywarren the PR at #2985 is done with comment-indirect notification setting and settings page. I would handle other settings in a separate PR for modularity. I hope that's fine. Thanks!
