### ISSUE TITLE
reply by email to comments

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#214]
For starters, here's the resource we're working from: 

http://railscasts.com/episodes/313-receiving-email-with-mailman?view=asciicast

https://github.com/blog/811-reply-to-comments-from-email has some great conventions. I like how reliable and simple github email replies are.

Recommend first step could be a simple method in the Comment model, like this:

```ruby
  def self.receive_mail(message)
    node_id = message.subject[/^\# (\d+)$/, 1] # this grabs the node ID from the subject line
    user_id = User.find_by(email: message.from.first)
    if node_id.present? && user_id.present?
      Comment.create! nid: node_id, body: message.body.decoded, uid: user_id
    end
  end
```

Then we need a mail script in the `/script/` folder for something like the following:

```ruby
#!/usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require "mailman"

Mailman.config.pop3 = {
  server: 'pop.gmail.com', port: 995, ssl: true,
  username: ENV['GMAIL_USERNAME'],
  password: ENV['GMAIL_PASSWORD']
}

Mailman::Application.run do
  default do
    begin
      Comment.receive_mail(message)
    rescue
      Mailman.logger.error "Exception occurred while receiving message:\n#{message}"
      Mailman.logger.error [e, *e.backtrace].join("\n")
    end
  end
end
```

Then we'll need to contact Sebastian to try to hook this up and we won't tell anyone about the feature just yet, but can try emailing a message with subject line: `Replying to #6` from an email with a corresponding registered user on PublicLab.org, and see if it appends the new comment as we've laid out, on this post, which is `nid=6`: https://publiclab.org/notes/warren/12-7-2010/toy-spectrometers-arrived

I might have missed something, but let's see!

**Comment by ebarry** [comment]
Seems like this is an important functionality to have in place before we announce to the lists that we have the capability to support conversation entirely through our website.

**Comment by jywarren** [comment]
a pretty big one, though -- would need lots of testing. I hesitate to say
this far out, but maybe GSoC 2017...?

**Comment by aspriya** [comment]
@jywarren So as you have stated above, GSoC 2017 has arrived and I could be working on this. I already created a feature branch for this and doing some experiments with mailman gem. And i'm checking for other solutions that could be used also. 
thanks.

**Comment by jywarren** [comment]
Oh, excellent! Please checkout
https://publiclab.org/notes/warren/02-28-2017/call-for-proposals as well.

**Comment by ViditChitkara** [comment]
Hi @jywarren @ebarry working on it!!

**Comment by Gauravano** [comment]
hi @ViditChitkara I guess its part of Email Integration project for this GSoC

**Comment by ViditChitkara** [comment]
Yes, it is!! I have some plans about this for the soc 2018 program!!!

**Comment by Gauravano** [comment]
Nice !!!.Actually, I have also planned to have my GSoC proposal on Email Integration Project.

**Comment by ViditChitkara** [comment]
Cool!

**Comment by jywarren** [comment]
Sounds great -- there's plenty to do, so anything we can accomplish now we
can build on, refine further for SoC for sure! Thanks!

**Comment by jywarren** [comment]
This is now working! Checklist for remaining parts might be:

* [ ] change sending email from `do-not-reply@` to `notifications@`
* [ ] ensure it doesn't include the reply email content (there can be a lot) below the `...`

Anything else to break out here @namangupta01 ?

**Comment by namangupta01** [comment]
yes we can also figure out if we can somehow write a test for it without using email services like mail file and we can also make function test for `receive_mail`.

**Comment by namangupta01** [comment]
Parsing email content depends upon the mail service we are using to do
emails.

**Comment by railsprojects2018** [comment]
This is github's testing reply parsing


________________________________

**Comment by namangupta01** [comment]
@jywarren Above message is send using outlook email id. This message was not parsed correctly. Maybe github is also parsing gmail messages?

**Comment by namangupta01** [comment]
This is send by outlook.

**Comment by railsprojects2018y** [comment]
This is send via yahooo
    On Wednesday, June 27, 2018, 7:28:02 PM GMT+5:30, Naman Gupta <notifications@github.com> wrote:  
 
 This is send by outlook.

**Comment by namangupta01** [comment]
Above message is sent via yahoo. So the conclusion is that github only able to parse mails from gmail not other mails this may be because they are not able to trim emails from other services using any sphefic class or something like we were able to do in gmail using `gmail_quote` class. 
I think we can also able to do parsing from yahoo by using somewhat class like `yahoo_quoted` but other email services provide no such points to differentiate.

**Comment by jywarren** [comment]
Perhaps there are examples of email quoting from various services that people have collected as a set of test strings? Or we could do the same?

**Comment by jywarren** [comment]
Also I like how the excess is hidden behind `...`!

**Comment by namangupta01** [comment]
Yes @jywarren i didn't find any collection but i am already collecting.

**Comment by namangupta01** [comment]
@jywarren Which of the email services should i collect? gmail, yahoo, hotmail, outlook any more?

**Comment by jywarren** [comment]
That's probably a good start, and we can expand with peoples' requests
later?

**Comment by railsprojects2018y** [comment]
yes that would be awesome!!!

**Comment by namangupta01** [comment]
yeah!!!

**Comment by namangupta01** [comment]
for google and yahoo done in pr #2933

**Comment by namangupta01** [comment]
gist for outlook mail:
https://gist.github.com/namangupta01/be81b339c7eb71f3046033556e54c8a7
https://gist.github.com/namangupta01/c5c386f15752b9cc168a4b74b21ecb29
not able to generalize the parser for outlook, researching over it....if we find any solution then we can add it...for now we can merge google and yahoo mail parser?

**Comment by jywarren** [comment]
sounds great!

**Comment by jywarren** [comment]
So I'm not sure this is processing incoming mails right now... i checked mailman.log after publishing today and didn't see one i'd responded to arriving. 

Do we have an issue open for replying to questions, and replying to answers? Questions should be pretty easy, but answers maybe need the subject line suffix `(#a12345)`?

**Comment by namangupta01** [comment]
Can you share the logs here? I just tested here: https://publiclab.org/notes/namangupta/02-17-2018/gsoc-proposal Its working for comment. Let me look for answer.

**Comment by jywarren** [comment]
OK - do we have reply to question working now too? Just checking!

**Comment by jywarren** [comment]
sorry, i mean reply to question leading to a comment on the question?

**Comment by namangupta01** [comment]
Yeah we do have

**Comment by jywarren** [comment]
hmm, i didn't find that that worked yesterday. Can you give it a try to
confirm?

**Comment by namangupta01** [comment]
Sure!

**Comment by namangupta01** [comment]
@jywarren Both question and notes use same node model right? And reply by email is specific to node and answer so i think it should work. But i tried to comment via email to normal post even that is not comment is not added. Is the mailman server stop working after sometime or server connection get timeout after some time because when you redeploy the app it adds all the comments.

**Comment by jywarren** [comment]
Hmm, let's ping @icarito and ask if there's more we need to do to keep the mailman server running?

**Comment by namangupta01** [comment]
Can you share the mailman ending logs so that we can be fully sure about what the bug is?

**Comment by icarito** [comment]
sure!
```
icarito@rs-plots2:/srv/plots_container/plots2$ docker-compose logs mailman                                                                     │···············
Attaching to containers_mailman_1                                                                                                              │···············
mailman_1  | /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/builder/collection_association.rb:27: warning: already in│···············
itialized constant TagNodeAssociationExtension                                                                                                 │···············
mailman_1  | /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/builder/collection_association.rb:27: warning: previous d│···············
efinition of TagNodeAssociationExtension was here                                                                                              │···············
mailman_1  | script/mailman_server: end of file reached (EOFError) 
```

**Comment by icarito** [comment]
I've restarted the service manually (with `docker-compose up`).
The logs added the following lines:
```
mailman_1  | /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/builder/collection_association.rb:27: warning: already in│···············
itialized constant TagNodeAssociationExtension                                                                                                 │···············
mailman_1  | /usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/associations/builder/collection_association.rb:27: warning: previous d│···············
efinition of TagNodeAssociationExtension was here
```
It appears to be running now!

**Comment by jywarren** [comment]
@namangupta01 have you noticed any more outages of this feature? 

What about having some place, like... publiclab.org/status, only visible to admins, where we can monitor how many emails were received and processed in the past day, past week? This could help us monitor uptime.

**Comment by namangupta01** [comment]
Yeah, i will work on it after #3112

**Comment by jywarren** [comment]
Thanks!!!

**Comment by jywarren** [comment]
Hmm, @icarito @namangupta01 it seems like it's not running currently, I tried replying to this question:

https://publiclab.org/questions/Cindy_ExCites/08-03-2018/air-quality-balloons-an-updated-version#answer-0-comment-20293

Any chance mailman is offline again?

**Comment by namangupta01** [comment]
Even i tried to reply, it was not woking :(
It is going timeout i guess.

**Comment by icarito** [comment]
I made an issue about it:
    https://github.com/publiclab/plots2/issues/3208

Maybe it should try to relaunch when it fails? I think docker-compose has a means to restart on failure - or maybe mailman can be configured to not stop in case of error.

The trick is that it's not possible to reproduce manually because it seems to happen when GMail responds "try later".

**Comment by jywarren** [comment]
Could we have it do something else, like leave a log file for failed
attempts? And if it fails, won't it get the emails later once it is able to
connect?

**Comment by jywarren** [comment]
I think this is reliable enough to close up! Thanks all!
