### ISSUE TITLE
RSS feed on tagged-content-for-author pages needs to be built

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2149]
Profile pages like https://publiclab.org/profile/cfastie now show some great links to, for example, all content tagged as an activity for a given user --

https://publiclab.org/tag/activity:*/author/cfastie

However, the RSS feed on that page is a generic feed for activities, not just `cfastie`'s:

https://publiclab.org/feed/tag/activity:*.rss

We need an RSS feed for this. It can be based on this one, which is the generic "all content for this tag" feed:

https://github.com/publiclab/plots2/blob/34935fb011a2982968c6a2e0b049eeb2aa791c78/app/controllers/tag_controller.rb#L324-L347

Any help with this would be appreciated! The new feed should probably be at: 

`https://publiclab.org/feed/tag/activity:*/author/_AUTHORNAME_.rss`

Thanks!

**Comment by SidharthBansal** [comment]
@jywarren May I take this?? I want to implement and learn about how rss works, I think this issue will help me with it
