### ISSUE TITLE
mark organizers, mods, admins with a special icon?

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#215]
## Proposed feature

In comments, users' profile pictures (if they exist) are shown in a small circle; see example: https://publiclab.org/notes/cbreuer/02-06-2016/oil-testing-kit-initial-electronics#comments

![screenshot 2016-03-16 at 4 19 09 pm](https://cloud.githubusercontent.com/assets/24359/13827434/d7e49fd4-eb92-11e5-9ca1-8aafa70eb25d.png)

It'd be nice to see if people are admins or moderators, perhaps with a small marker next to the image, or based on the border of the image, perhaps. We could use the "roles" system for this -- to find whether a user is `user.role == 'admin'` or `== 'moderator'` to decide how to display it. Similarly to #319, it'd be great to use [a Bootstrap tooltip](http://getbootstrap.com/javascript/#tooltips) to explain what it means, and potentially link to a page explaining it (although the image link might still go to the user's profile page, and the link to the roles explanation could be on the profile page, where their role is listed).

The code for the image on comments is currently at https://github.com/publiclab/plots2/blob/master/app/views/notes/_comment.html.erb#L10-L12

(Eventually, this could be connected to the profile tagging system (#104) instead of being based on the role field.)

### Steps to fix

* [ ] claim this issue with a comment
* [ ] discuss here and decide on a visual style and design to indicate role
* [ ] set up a repository locally and make sure that all tests pass
* [ ] start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress"
* [ ] fix the issue following the steps above
* [ ] make sure all tests pass
* [ ] alert someone via either the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by ebarry** [comment]
When you say "roles" system, do you mean what is being conceptualized in [104](https://github.com/publiclab/plots2/issues/104)?

**Comment by jywarren** [comment]
no, the "roles" system is related to Role-based Access Control (RBAC) which we have a primitive implementation of, referred to in https://github.com/jywarren/plots2/issues/160

I'd prefer to implement this in user tagging, but it doesn't make a big difference to me.

**Comment by ebarry** [comment]
user tagging should be able to take care of the organizer status part of this issue, no? That's proposed in 104. but moderator and admin of the website is actually a technical role...seems different.

**Comment by jywarren** [comment]
it's partially related to database optimization; it results in fewer and
simpler db queries if we store that data in the same table, and since we
already have a field for admin/mod roles, we could do that, and reference
'organizer' roles all over the site at near-zero cost. But it's not that
big a deal either way. I imagine @btbonval would prefer we keep (security
related) RBAC roles separate from a more generic tagging system for all
sorts of profile features, but don't know.

**Comment by btbonval** [comment]
@jywarren I'm not sure a see a functional difference in terms of database mangement or security, it'd just be however you choose to program it in the controllers. Perhaps I'm misunderstanding the comparison of tags for security.

In some sense, groups in RBAC are tags applied to users. Users do not get direct privileges, they inherit the privileges of all groups they are assigned to. In that sense, tagging a user with their roles would be just fine.

Right now you have a heirarchical role system. RBAC is meant to be logically separated into domains of concern.

**Comment by jywarren** [comment]
Agreed, architecturally i'd like to have a separate table for roles instead
of the shoehorned implementation we have now. Just wanted to check with you
if you think it'd be a bad idea to simply use the proposed profile tagging
system *as the role storage* -- say, if you thought it was bad practice to
mix its uses with a key security function. agreed that we can manage this
effectively in controllers.

**Comment by btbonval** [comment]
Its only bad form if the controller is not well programmed to prevent users from adding security power tags that they ought not to, or changing existing power tags into security power tags.

Having it separated at the database level causes the database to maintain some of that logic, which is probably better for a number of reasons. However, there is no requirement that it be done as such.

Ultimately security is handled by the controller, no matter what the implementation, which is why it doesn't matter as much how you store it, so long as the controller is in charge of ensuring people can't mess with security ;)

**Comment by btbonval** [comment]
Again, we might want to go back to the RBAC ticket to discuss implementation details.

**Comment by ananyo2012** [comment]
Here is a design suggestion. I am using gear image for a admin with a tooltip "Admin" and a star image for a moderator with a "Moderator" tooltip.We can link the corresponding images with the corresponding wiki pages.
![admin_tooltip](https://cloud.githubusercontent.com/assets/10486343/15268989/7a9c89c2-1a0e-11e6-9abd-139beb609d7a.png)
![moderator_tooltip](https://cloud.githubusercontent.com/assets/10486343/15268991/89acf564-1a0e-11e6-9a82-efd428b54545.png)
If it looks good I can raise a PR ready with me.

**Comment by jywarren** [comment]
Do we ever show stuff on the right edge of that window? Maybe we can put a
grey text there. If we do, we should put it in `<span
class="hidden-xs"></span>` so its hidden on smartphones, or only shows an
icon, no text.

**Comment by ananyo2012** [comment]
@jywarren Didn'T get your last point. Can you explain it further? The text is shown in a tooltip as asked.

**Comment by ananyo2012** [comment]
@jywarren Is there any way to recognize organizers? Is there any `organizer` role present for organizers?

**Comment by jywarren** [comment]
I think we should use `class="pull-right"` to put the icon on the right side of that bar, rather than crowd the profile picture. I don't believe there is an "organizers" role, but I think this is a very good candidate for @lalithr95's project on profile tagging. We could simply create a role, but unfortunately then organizers couldn't *also* be admins or moderators. I think we need profile tagging to complete the part of this that is marking organizers -- if you solve the other parts, can you break that out as an independent issue? Thanks!

**Comment by jywarren** [comment]
We're holding on this a bit pending some design decisions; latest via @steviepubliclab:

> I'm a little conflicted on separating people out by their activity and roles on PL. I think this is coming from some of the readings that have been passed around about activity in online communities. > However, I also see the benefit for people to personally identify and share out about who they are, and what they've been up to. This can also be a positive reinforcer of activity. I think some of they points to keep in mind in building these functions that we don't create
> 1. an intimidating space for newcomers or first time contributors, and
> 2. an internal hierarchy, or become exclusionary by parsing out groups or contributors.
> I'm conflicted as well because in my mind I also go strait to:: What would people think of adding one for organizers?
> Love to hear other people's thoughts on this.

**Comment by jywarren** [comment]
I'm going to close this since we're not sure about implementing it. If it comes back up we can re-open. Thanks!
