### ISSUE TITLE
Show more should change to Show less on clicking

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2150]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**
### Please describe the problem (or idea)
When clicking on the Show More button it does not change to Show less
![image](https://user-images.githubusercontent.com/20972099/35480166-a8881b56-042e-11e8-9af6-a0126c1948f1.png)
![image](https://user-images.githubusercontent.com/20972099/35480169-b06eaa56-042e-11e8-9b22-98fba8c5092f.png)
> What happened just before the problem occurred? Or what problem could this idea solve?
The text should change on clicking the button

### Please show us where to look
https://publiclab.org/wiki/timelapse

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by ebarry** [comment]
Wow, great catch!

**Comment by Ankit-Singla** [comment]
I have understood the problem and would like to resolve the issue.

**Comment by Ankit-Singla** [comment]
@SidharthBansal Hey, can I get a little help in getting started, as its just the second issue I have started working on.
I cloned the repository, installed necessary gems, set up the database, but when I start the server and go to 'localhost:3000/wiki/timelapse', it says 'This page does not exist yet, but you can create it now:'.
Why might this be happening? Is there any other place where I can test my the changes I have made before sending a pull request?

**Comment by SidharthBansal** [comment]
@Ankit-Singla you can definitely try to resolve this one if it seems difficult, try out the other issues labeled with fto on the repository.
Actually, the database of the website publiclab.org is different from the database of your cloned repo. The database of your clone does not contain this page so you are not able to get this issue. You need to reproduce this in the development environment to resolve it.
Does this make sense?
We are here to help.

**Comment by Ankit-Singla** [comment]
@SidharthBansal So that means I should manually insert relevant data to reproduce the bug in the development environment?
Yes, it is making sense and I would like to continue to resolve the issue.
Thanks, I'll ask for help if I am stuck somewhere.

**Comment by SidharthBansal** [comment]
yeah you need to insert relevant data

**Comment by Ankit-Singla** [comment]
@SidharthBansal I created a 'timelapse' wiki page, and tried adding questions by clicking on "Add a related question", but the question does not appear on the same page. 
I have tried to do so by logging in as a user, as well as an admin.
Can you please guide me in the right direction?

**Comment by Ankit-Singla** [comment]
@namangupta01 can you please help me out here?

**Comment by namangupta01** [comment]
sure @Ankit-Singla where are you getting problem?

**Comment by Ankit-Singla** [comment]
@namangupta01 ek baar ye comment streak padho, samajh jaoge aap.

**Comment by namangupta01** [comment]
@Ankit-Singla i'll have a look at it! :)

**Comment by SidharthBansal** [comment]
@Ankit-Singla See https://publiclab.org/questions/tag/timelapse these are the questions which are tagged with 'timelapse'

**Comment by SidharthBansal** [comment]
At public labs we use tags. There are some special tags known as powertags. These tags have special meaning for eg in this case we have ```[questions:timelapse]``` you can learn more about it on https://publiclab.org/wiki/power-tags#Inline+tags.
You need to create multiple questions with this tag or anyother tagname say 'map' then you need to use this [question:map] tag to list those activities.
Hope this helps
I was a little busy so was not able to reply. Also, please use English here because there are many fellows who do not know your native language, so in case they are free they can also help you.

**Comment by Ankit-Singla** [comment]
Thanks a lot @SidharthBansal 
And I'll make sure to use only English here onwards.
@namangupta01 I got the necessary help, will try on my own now.

**Comment by ViditChitkara** [comment]
@Ankit-Singla, to show questions on the wiki page a power tag is used,e.g: [questions:test]. This would show all the questions on the page which contain 'test' as a tag. The 'Ask a related' question button appears only if you use a power tag (The question form would automatically add 'test' tag to it,  making it a related question). The reason why the question is not visible on the page might be due to missing tag ('test' in this case) on that particular question.
Hope this helps!!

**Comment by Ankit-Singla** [comment]
@SidharthBansal @ViditChitkara I tried to post several questions using the required powertags, and still the questions do not appear on the wiki page. But when I post a new question with the tags, on the left there is a related questions section, which shows the previous question I posted. Please help.

![screen shot 2018-01-31 at 10 14 57 am](https://user-images.githubusercontent.com/22820781/35606690-736e55ee-0676-11e8-9ee4-fea550cb28a3.png)

![screen shot 2018-01-31 at 11 02 47 am](https://user-images.githubusercontent.com/22820781/35606730-a9250444-0676-11e8-8927-461a44071541.png)

**Comment by SidharthBansal** [comment]
Have you used [question:test] in your wiki? For listing the question grid

**Comment by Ankit-Singla** [comment]
@SidharthBansal I've figured it out now. Thanks for helping me at every step.

**Comment by Ankit-Singla** [comment]
@SidharthBansal I have resolved the issue and "Show <some_count> more" now changes to "Show less" when clicked.
Don't you that the feature to hide these rows again when the "Show less" button is clicked should also be added? Should I do it in this Pull Request or open another issue for this?

**Comment by Ankit-Singla** [comment]
@SidharthBansal Also, in reference to issue #2151 , we will face the same issue here also. So, should I take care of that as well in this PR. Or should another similar issue be opened for that?

**Comment by Ankit-Singla** [comment]
![screen shot 2018-01-31 at 2 35 29 pm](https://user-images.githubusercontent.com/22820781/35614139-142a85b2-0694-11e8-89c3-874a034ae0c7.png)

@SidharthBansal  I noticed a warning on the console. Should I also update the CDN for MathJax?

**Comment by SidharthBansal** [comment]
You need to enter the capability to show less on clicking show less in this pr. It is a part of this pr

**Comment by SidharthBansal** [comment]
If show 0 is occurring in this also then please update it,no need to open a new issue. Do it in a single PR.
Thanks for the catch.

**Comment by SidharthBansal** [comment]
@Ankit-Singla I mean to say for this issue you need to put all stuff in a single PR. Please remove the changes from the email validation pr. That is different issue. Open a different pr for it

**Comment by Ankit-Singla** [comment]
@SidharthBansal Sorry, it wasn't intentional.
Its just I am not yet comfortable in using github, thats why I am making these mistakes. I'll try to correct it right away.

**Comment by jywarren** [comment]
@Ankit-Singla just to say again, no worries having issues - git and github are not easy to work with! We're happy to help you out here. Thanks to @SidharthBansal for offering some guidance!

And thanks @Ankit-Singla for working on this! We really appreciate it :-) 👍

**Comment by jywarren** [comment]
Hi, @Ankit-Singla if you'd like to take this back up, we're more able to support now -- just re-open https://github.com/publiclab/plots2/pull/2184

If someone else is interested, https://github.com/publiclab/plots2/pull/2184 is a great place to get started solving this!

Thanks, everybody!

**Comment by oorjitchowdhary** [comment]
Hi, I'd like to work on this issue. I'm a GCI candidate. Where can I find the code which is to be edited?

**Comment by oorjitchowdhary** [comment]
Is this issue still open?

**Comment by SidharthBansal** [comment]
Yes it is still open. If you want to give it a try then give it a shot

**Comment by oorjitchowdhary** [comment]
I can't file the code file which is to be corrected..

**Comment by jywarren** [comment]
Could it be in this file and the others in the same folder? 

https://github.com/publiclab/plots2/blob/master/app/views/grids/_notes.html.erb

**Comment by oorjitchowdhary** [comment]
I can't find this task on the GCI dash anymore.. Is it already done by someone else?

**Comment by gauravano** [comment]
Hi @oorjitchowdhary, currently it's claimed by @kevinzluo. Thanks!
