### ISSUE TITLE
Fix "Show 0 more" on inline people lists

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2151]
### Please describe the problem (or idea)
Show 0 more is present in the people's list
> What happened just before the problem occurred? Or what problem could this idea solve?
If there is no more stuff, the text should not appear

> What did you expect to see that you didn't?

![image](https://user-images.githubusercontent.com/20972099/35480203-45361b42-042f-11e8-9d11-a2a491654ffa.png)

### How to Solve:
You can check out @kevinzluo's work in https://github.com/publiclab/plots2/pull/3980 for solving this. 

The file which would require changes will be https://github.com/publiclab/plots2/blob/master/app/views/grids/_people.html.erb

### Please show us where to look
https://publiclab.org/w/power-tags#Inline+power+tags

**Comment by Ankit-Singla** [comment]
Hey, I would like to work on this.

**Comment by SidharthBansal** [comment]
I am working on it, sorry. Please try the other ones out. Can you see that there are issues labelled with 'in progress' or 'assigned' like this one. Folks are already working on these. You may try the other issues labelled with help wanted

**Comment by Ankit-Singla** [comment]
okay, got it

**Comment by SidharthBansal** [comment]
As the codes are overlapping in #2150 and #2151 as @Ankit-Singla is working on it

**Comment by JonathanXu1** [comment]
Hi, has this issue been fixed? I would like to work on it if it hasn't yet.

**Comment by kevinzluo** [comment]
@JonathanXu1 I was testing out this issue for #2150 and it looks to be already fixed.

**Comment by gauravano** [comment]
Hi @kevinzluo could you add a screenshot here showing the show more/less grid in action for people and add your PR number too(for reference). Thanks!

**Comment by JonathanXu1** [comment]
@kevinzluo I think you aren't experiencing the error because section does not include the **<%= users.length - 10 %>** attribute in the show more tag

**Comment by kevinzluo** [comment]
Thanks for the heads up. I didn't realize there were multiple partials for grids :smiley:. The ones i was using were the notes grids and never checked the people grids.

**Comment by SidharthBansal** [comment]
If anyone knows the solution and wants to send a patch then it will be great

**Comment by JonathanXu1** [comment]
@SidharthBansal I've sent a patch on #4253

**Comment by gauravano** [comment]
@jazdao you wanna try this?

**Comment by vansjyo** [comment]
@SidharthBansal Can I try this if not yet solved?

**Comment by SidharthBansal** [comment]
Yeah sure Vanshika

**Comment by siaw23** [comment]
got for it! @vansjyo 😊🎉

**Comment by vansjyo** [comment]
We can replace the 9 with a 10 and I suppose the problem in this issue should be solved. What do you think?

https://github.com/publiclab/plots2/blob/7a0660a3fcbb40250394b68405299c41f894f7f9/app/views/grids/_people.html.erb#L21-L23

**Comment by vansjyo** [comment]
@SidharthBansal Is there anything more that you are expecting from this fix? If not, I'll open a PR, else please let me know. Thanks.

**Comment by gauravano** [comment]
Yes @vansjyo, feel free to open a PR. Thanks!
