### ISSUE TITLE
Hyperlinks drag the pages more than required

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2152]
### Please describe the problem (or idea)
When clicking on the hyperlink buttons next to the headings inside a wiki page they go under the header of the public lab.
> What happened just before the problem occurred? Or what problem could this idea solve?
The heading must appear below the header of the public lab

### Please show us where to look
Initially 
![image](https://user-images.githubusercontent.com/20972099/35480261-505aa456-0430-11e8-902e-d828fe47ac3b.png)
After clicking on the hyperlink button next to the highlighted text
![image](https://user-images.githubusercontent.com/20972099/35480268-64f42dba-0430-11e8-891a-d45c175f3b68.png)
But it should be 
![image](https://user-images.githubusercontent.com/20972099/35480276-7143f5c8-0430-11e8-9dd0-b1184c53160d.png)

**Comment by namangupta01** [comment]
HI @SidharthBansal Which hyperlink are you talking about?

**Comment by SidharthBansal** [comment]
I am talking of these buttons
![image](https://user-images.githubusercontent.com/20972099/35480305-3485a9f0-0431-11e8-82c1-066c94d89373.png)
Functionality is working properly. It is copying the right area of the wiki page in the url section but it shows a little up and it creates ambiguity to the user.

**Comment by namangupta01** [comment]
It's already taken care in issue #2093 and done in pr #2145 
Thanks!

**Comment by SidharthBansal** [comment]
Thanks @namangupta01
