### ISSUE TITLE
display activity graph colored by contributor on /tag/foo page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#216]
https://github.com/publiclab/plots2/blob/master/app/views/tag/show.html.erb#L6

Has the relevant code.

**Comment by gauravano** [comment]
@jywarren I think we can close this one considering we have stats button on tag/topic page which leads to https://publiclab.org/tag/topic/stats. What do you think? Thanks!

**Comment by jywarren** [comment]
Yep!
