### ISSUE TITLE
tag spam moderation

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#217]

**Comment by ebarry** [comment]
Considering our whole site is held together via tagging, this is actually quite significant when spam tags show up in autosuggest.

**Comment by ebarry** [comment]
I've seen MUCH less spam in the last 6 months -- has some other improvement had an effect on this?

**Comment by jywarren** [comment]
I don't know what might've changed but we can add a "delete tag" entry to the tag index if we want. Visible only to admins. It would have to delete boh the tag and any records linking the tag to specific pages. I can help with this if it sounds interesting or we could close this out!

**Comment by gauravano** [comment]
Hey @jywarren @ebarry, do you think we still need this one? Thanks!

**Comment by ebarry** [comment]
I haven't seen any pervasive tag spam lately, seems like Jeff might have
addressed this somehow a couple years ago?
