### ISSUE TITLE
Profile page UI/UX inconsistencies

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2173]
### Please describe the problem (or idea)
The tabs on /profile/author have different treatment in terms of
- [x]  Some have count while others dont have
- [x] Some have icons while other 
- [x] Some have text while other does not
- [x] Like tab should render liked pages on the same page but is rendering on the different page
- [x] Two horizontal lines on the bottom of profile page
![image](https://user-images.githubusercontent.com/20972099/36019014-cd8bb060-0da3-11e8-9c40-6260d3b9877f.png)

- [ ] Broken Ajax ---> See carefully ....The pagination is in accordance with the maximum number of elements present in any of one tab
- [ ] Go to comments nav bar. Then go on second page of comments. You will notice a new page to be opened instead of ajax.
- [x] A non logged in user can click on the tags to delete them 
![image](https://user-images.githubusercontent.com/20972099/35871401-2cdc0360-0b8a-11e8-8633-1fa9b6763013.png)

> What happened just before the problem occurred? Or what problem could this idea solve?
1)Either all should have count or none should
2)Same as 1
3)All should have text
4)Like should render the liked pages there also
5)One horizontal line
6)Pagination should be separately involved with each of the tabs
7)Only the creater should get the js prompt

**Comment by SidharthBansal** [comment]
@ViditChitkara thanks for solving 3rd issue in this via #2166

**Comment by ViditChitkara** [comment]
:+1:

**Comment by SidharthBansal** [comment]
@ebarry, @jywarren what do you suggest?

**Comment by SidharthBansal** [comment]
@ViditChitkara thanks for opening #2262 and doing  #2263.
@ViditChitkara Please notify me if you are working on some part of the issue. I was done with the counts on profile page but you pushed the changes so that others will not work on it.

**Comment by SidharthBansal** [comment]
@jywarren is anyone else working on remaining parts of these sub issues?

**Comment by ViditChitkara** [comment]
@SidharthBansal I didn't really had an idea that you were working on it. I just saw an untidy navbar while browsing on the mobile site and sent a patch for the same. Had I known someone was working on it, I would have been more than happy. Will take care about this in the future

**Comment by SidharthBansal** [comment]
No problem, btw great catch.

**Comment by SidharthBansal** [comment]
#2294 is also a part of profile pages

**Comment by jywarren** [comment]
Is this one perhaps complete? Or anything remaining could be broken out as a narrower issue? Thanks!!!

**Comment by SidharthBansal** [comment]
One issue is left. Broken ajax.

**Comment by jywarren** [comment]
ah, ok - can you elaborate a bit on that? sorry, i didn't quite follow what
was going wrong?

**Comment by SidharthBansal** [comment]
When a user tries to change page number on profile page, the user will observe broken ajax. You need to look very carefully. The pagination is according to max pages of the research comment etc. But it should be different for different nav bars.

**Comment by SidharthBansal** [comment]
Follow the following sequence
1. Go to profile page
2. Click the Like nav bar
3. Click on 19 page from paginations given at bottom
4. You will be redirected to the Research nav bar and 19th page.
This error is in whole website. At all the nav bars. On the main welcome page also. When you switch over events from all events, etc.
Does this makes sense?
I tried to debug this error. But the solution did not work.
Solution is https://coderwall.com/p/viyn-w/will_paginate-and-ajax or similar post. I remember very well that I tried almost 9-10 solutions similar to this post. But they did not work out. So this subissue was not resolved. Sorry for lingering for this error.
One more issue has arisen on profile page --> Once you will go on comments. Then go on second page of comments. You will notice a new page to be opened instead of ajax.
I have added this into the checklist.

**Comment by jywarren** [comment]
No problem, and thanks for carefully documenting this!

**Comment by SidharthBansal** [comment]
Are you willing to send a quick fix to it?
On chrome on my laptop everything is working fine.

**Comment by jywarren** [comment]
Profile pages are fully rebooted!!! Thanks all!
