### ISSUE TITLE
character escaping in searches would be doubleplus good

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#218]
@btbonval sez:

> a search for "dc/baltimore" results in a URL like this: http://www.publiclab.org/search/dc/baltimore
> The URL is being dispatched incorrectly due to the slash, resulting in a page not found error.

This is a routing issue; see `config/routes.rb`

**Comment by Mujadded** [comment]
@jywarren Can I try this ?

**Comment by jywarren** [comment]
Hi, i'm not sure if it's an issue anymore -- could you test it out on
publiclab.org to confirm? But of course we'd love your contribution!

**Comment by Mujadded** [comment]
@jywarren I just tested it out, in search, I typed `dc/baltimore` it redirected to `https://publiclab.org/search/dc/baltimore` which resulted in page does not exist. I will try to fix and close this issue if its ok :smile:

**Comment by jywarren** [comment]
Super, thanks!!

**Comment by jywarren** [comment]
Being fixed in #2003 !!

**Comment by ebarry** [comment]
We have changed our approach to search so i am going to close this issue with a `wontfix` but it's here if we ever need to return to it!
