### ISSUE TITLE
Add link to questions below intro paragraph on front page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2188]
@ebarry @steviepubliclab if this sounds good, I'd like to propose a simple link to the Questions page on the front page (http://publiclab.org when not logged in, or http://publiclab.org/home when you are), like this:

![screenshot 2018-01-31 at 4 52 54 pm](https://user-images.githubusercontent.com/24359/35655579-844e48ac-06c0-11e8-8102-9dacf982204c.png)

What do you think? (from [this mockup](https://docs.google.com/presentation/d/1TCZoTfuhamRVrUak8aDgqJAwSgyhRtZg2Pgacl2_4zc/edit#slide=id.g2e47a5f7b9_0_0))

This could go just below our banners.

**Comment by ViditChitkara** [comment]
I Would like to try it!

**Comment by jywarren** [comment]
awesome, thank you!
