### ISSUE TITLE
Same button treatment

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2194]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!
🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process
### Please describe the problem
On public lab we usually have buttons like this:
![image](https://user-images.githubusercontent.com/20972099/35692153-9327a248-07a0-11e8-8014-e65d94087b06.png)
By mistake someone has made button like this
![image](https://user-images.githubusercontent.com/20972099/35692078-59eda0f4-07a0-11e8-8165-53c53bd83f46.png)
See on the https://publiclab.org/notes/warren/06-22-2017/balloon-mapping-stories-part-1
It lacks >> at the end which is not in analogy with the rest of buttons

### Solution
Add the  &raquo; symbol

:clipboard: Step by Step

:raising_hand_woman: Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

Add ` &raquo;` to https://github.com/publiclab/plots2/blob/00cc80b0bd7c7d6b3e02a9f6d81e039b3efef3d9/app/views/sidebar/_related.html.erb#L7 as done in
 https://github.com/publiclab/plots2/blob/00cc80b0bd7c7d6b3e02a9f6d81e039b3efef3d9/app/views/sidebar/_related.html.erb#L8

:floppy_disk: Commit your changes

:twisted_rightwards_arrows: Start a Pull Request.

:checkered_flag: Done Ask in comments for a review :)

:thinking::question: Questions?

Leave a comment below!

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seem stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!
Thank you!

Your help makes Public Lab better! We deeply appreciate your helping refine and improve this site.

**Comment by shannonnolan17** [comment]
I would love to give this a shot! Thanks for the great step-by-step guide! 😀

**Comment by shannonnolan17** [comment]
Aaand done! I would love a review!

**Comment by SidharthBansal** [comment]
Awesome
