### ISSUE TITLE
consolidate wiki#root and wiki#show controller actions

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#220]
@btbonval sez:

> `wiki#root` can be used to retrieve any wiki page at all, but it is only used in the case of `/:id`

> `wiki#show` is also used to retrieve wiki pages, but it is used for `/wiki/:id`.

> there's not any good reason to have two such functions. `routes.rb` can point both at the same wiki function. Might as well pick one or the other function and stick to it.

**Comment by ananyo2012** [comment]
@jywarren This is not yet implemented. Should we keep this open as it is quite a valid point!

**Comment by jywarren** [comment]
Sure, although the new friendly id stuff may change things?

**Comment by ananyo2012** [comment]
Well yes if we implement that again it may cause certain problems but we can solve that by some thinking!
