### ISSUE TITLE
tag page wiki links go to https://publiclab.org/wiki/#{params[:id]}

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2203]
Oops! I might be responsible for this, but the new buttons on tag pages unfortunately go to `https://publiclab.org/wiki/#{params[:id]}` instead of, for example, `https://publiclab.org/wiki/spectral-workbench`

See this at https://publiclab.org/tag/spectral-workbench

This should be an easy fix -- any help appreciated!

**Comment by jywarren** [comment]
Aha - indeed this should be:

https://github.com/publiclab/plots2/blob/b6fab99912bf06d890eb81be0ab844c6104ad44d/app/views/tag/show.html.erb#L15

`<% if @wiki.latest.render_body.split('</p>').length > 2 %><a class="btn btn-lg btn-default" href="/wiki/<%= params[:id] %>">Learn more on the wiki page</a><% end %>`

**Comment by Gauravano** [comment]
Can I open first-timer for this @jywarren?

**Comment by jywarren** [comment]
sure! Thank you!

**Comment by Gauravano** [comment]
Opened this issue as FTO in #2204

**Comment by jywarren** [comment]
Awesome!!!
