### ISSUE TITLE
Tag Page wiki links point to wrong address

### ISSUE THREAD

**Issue by Gauravano** [publiclab/plots2#2204]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!
🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process
### Please describe the problem
The new buttons on tag pages go to https://publiclab.org/wiki/#{params[:id]} instead of, for example, https://publiclab.org/wiki/spectral-workbench

See this at https://publiclab.org/tag/spectral-workbench

### Solution
Replace this statement
https://github.com/publiclab/plots2/blob/b6fab99912bf06d890eb81be0ab844c6104ad44d/app/views/tag/show.html.erb#L15
with

`<% if @wiki.latest.render_body.split('</p>').length > 2 %><a class="btn btn-lg btn-default" href="/wiki/<%= params[:id] %>">Learn more on the wiki page</a><% end %>`

:clipboard: Step by Step

:raising_hand_woman: Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

:floppy_disk: Commit your changes

:twisted_rightwards_arrows: Start a Pull Request.

:checkered_flag: Done Ask in comments for a review :)

:thinking::question: Questions?

Leave a comment below!

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seems stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!
Thank you!

Your help makes Public Lab better! We deeply appreciate your helping refine and improve this site.

**Comment by Souravirus** [comment]
@Gauravano I want to fix this. Please assign this to me.

**Comment by Gauravano** [comment]
Hey @Souravirus, that's great

**Comment by Souravirus** [comment]
#2211 I have fixed the issue in this pr. Please review it.

**Comment by Souravirus** [comment]
#2211 Please review this pr @Gauravano

**Comment by Gauravano** [comment]
Closed #2204 via #2211
