### ISSUE TITLE
Encoding issues with migrating old DrupalUser accounts to User records

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2209]
We're seeing an issue with a recent migration https://github.com/publiclab/plots2/pull/2157 which tries to mitigate User vs DrupalUser status records. I tried to fix it here: https://github.com/publiclab/plots2/pull/2208 but we have a new problem. 

I believe it's due to this error from the [Jenkins build log](https://jenkins.laboratoriopublico.org/job/Plots-Stable/lastFailedBuild/console):

```
ActiveRecord::StatementInvalid: Mysql2::Error: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=': SELECT  `rusers`.* FROM `rusers`  WHERE `rusers`.`username` = 'トリーバーチ クラッチ'  ORDER BY `rusers`.`id` ASC LIMIT 1
```

The username in question is: `トリーバーチ クラッチ`

Can we convert the string or otherwise mitigate when a username is ... not utf-8?

**Comment by jywarren** [comment]
I think i can get past this by not matching `User` and `DrupalUser` by `name/username`, but instead by `id/uid` (did this in https://github.com/publiclab/plots2/pull/2210). But we will have to solve this if we ever want to convert /all/ `DrupalUsers` into `Users`, with the `drupal_user.migrate` command:

https://github.com/publiclab/plots2/blob/b73d598262f2132a57d4cd3f49f5331edafc8265/app/models/drupal_user.rb#L180-L193

`migrate` will break due to the above encoding problem. Once we fix that issue, we could ensure there are no "orphaned" `DrupalUsers` left with:

```ruby
DrupalUser.all.each do |du|
  du.migrate
end
```

https://stackoverflow.com/questions/17022394/how-to-convert-a-string-to-utf8-in-ruby

**Comment by jywarren** [comment]
That'll get us one step closer to deprecating `DrupalUser`! #956

**Comment by ViditChitkara** [comment]
Hmm, didn't anticipate this problem. will submit a patch for this!

**Comment by jywarren** [comment]
I went ahead and fixed the issue for the purposes of your migration -- no
problem! i should've seen this too. But I do think the future desire to
stop using DrupalUsers entirely, for which we'll need this "migrate"
method. Interested in working on that a bit? Thanks!!

**Comment by ViditChitkara** [comment]
Yes, interested! Finally now the following needs to be done:-
[ ] Modify the `migrate` method to accept `トリーバーチ クラッチ` this type of a string
[ ] Write a migration to ensure we have a user for every drupal user.
If this is good, I'll be happy to give it a go.

**Comment by jywarren** [comment]
yes, fantastic!!! :-)

**Comment by icarito** [comment]
Here's some info on the utf8 situation in MariaDB / MySQL - we should actually switch to `utf8mb4`

**Comment by jywarren** [comment]
Let's make a unique issue for that - this fix should work for now!

**Comment by jywarren** [comment]
OK - we ended up with an error as documented here: https://github.com/publiclab/plots2/issues/2846

So, should give this another try! Thanks though Vidit! We'll get it i'm sure.

**Comment by jywarren** [comment]
OK, given that we had trouble, let's go forward with @icarito's suggestion of `migrate character sets to utf8mb4` -- we'll have to do that in a migration too!

**Comment by jywarren** [comment]
This was solved!
