### ISSUE TITLE
design UI for "responding" to research notes

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#221]
@nathanathan sez:

> Some research notes have a "This is a response to..." item in the side bar. I would like to edit [one of my notes](http://publiclab.org/notes/nathanathan/12-04-2013/glow-in-the-dark-paint-photos) to have one, but I can't seem to find a way to do it.
> Also, I don't see anything that indicates whether a note has response notes and where the responses are. I think that could be very useful for following lines of research conducted by multiple people.

More info/discussion here: https://github.com/jywarren/plots2/issues/211

**Comment by ebarry** [comment]
This is a great idea.

**Comment by jywarren** [comment]
Complete as of Activity Grids and Response prompts!
