### ISSUE TITLE
Profile Map is not shown on small screens .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#2214]
Profile map hides on small screens . 
Changes are to be made in this file : 
[https://github.com/publiclab/plots2/blob/master/app/views/users/profile.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/users/profile.html.erb) .

<img width="411" alt="screen shot 2018-02-03 at 10 15 27 pm" src="https://user-images.githubusercontent.com/14952645/35769409-501ccf5a-0930-11e8-9b95-d2635099d2f9.png">

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by Souravirus** [comment]
@sagarpreet-chadha Please assign this bug to me

**Comment by sagarpreet-chadha** [comment]
Hi @Souravirus , you may go ahead 😄 ! Thanks !

**Comment by Souravirus** [comment]
@sagarpreet-chadha Please review the pr

**Comment by sagarpreet-chadha** [comment]
Solved in  #2269 .
