### ISSUE TITLE
Changing coordinates of people map to show more continents .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#2215]
Hi, this is a [first-timers-only](https://github.com/publiclab/plots2/projects/2) issue. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

# The Problem

Currently the people map shown here :  [https://publiclab.org/people/](https://publiclab.org/people/) , 
<img width="912" alt="screen shot 2018-02-03 at 10 49 33 pm" src="https://user-images.githubusercontent.com/14952645/35769741-9a1f1c34-0935-11e8-963e-7b73ea37ddee.png">

This map is not at center , hence less number of users are shown .
Lets change the center coordinates of the map to show more continents when the page loads .
Like this : 

<img width="901" alt="screen shot 2018-02-03 at 10 50 03 pm" src="https://user-images.githubusercontent.com/14952645/35769762-e8979e0e-0935-11e8-936c-4f741dfb198f.png">

# Solution

Lets change the coordinates here , 
https://github.com/publiclab/plots2/blob/b978d2bd8912a3c4cbffd3a320f44f05deb8764d/app/views/users/list.html.erb#L15
to `lat:23` and `lon:4 ` .

### Feel free to ask any doubt regarding the issue ! Thank you !

# Steps to Fix 

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ]  set up a repository locally following the README instructions, and make sure that all tests pass
 - [ ] try to fix the issue following the steps above, but even before you're done, you can:
 commit your changes and start a pull request (see contributing to Public Lab software) but mark it as "in progress" if you have questions or if you haven't finished
- [ ]  alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see [https://publiclab.org/wiki/developers](https://publiclab.org/wiki/developers)) or go to the [chatroom](http://publiclab.org/chat) if you have questions, and take a look at our [first-timers landing page for more information!](https://github.com/publiclab/plots2/projects/2)

**Comment by VarshaNairM** [comment]
I am a beginner to open source.I want to take up this and work on

**Comment by ViditChitkara** [comment]
Go ahead :+1
