### ISSUE TITLE
Add tweet button to subscription share

### ISSUE THREAD

**Issue by namangupta01** [publiclab/plots2#2216]
### Please describe the problem (or idea)

Currently, when we click on the subscription share button it actually not sharing, it is just showing us the link. 
See here: https://publiclab.org/subscriptions
![screen shot 2018-02-04 at 12 44 30 am](https://user-images.githubusercontent.com/20709985/35770614-9e8222ee-0944-11e8-99bf-6efbf55ee1fc.png)
We can add tweet button there :
![screen shot 2018-02-04 at 12 45 41 am](https://user-images.githubusercontent.com/20709985/35770623-bf23f48c-0944-11e8-8a45-0257ffed0b32.png)

**Comment by ryzokuken** [comment]
Tests passed, danger encountered some error, I guess. Let me restart the build.
