### ISSUE TITLE
Improve element selectors in i18n tests

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plots2#2220]
The class attribute is checked by the selectors in the exact same way other attributes are selected (eg: `p[class=facebook-summary]`) we could preserve line-length and make things simpler by using the canonical class notation (`p.facebook-summary`).

**Comment by James-N-M** [comment]
Hey @ryzokuken Id like to take on this issue, Im a first timer so Ill need additional links and information on how to tackle this. @Gauravano what do you think about this one for me ?

**Comment by Gauravano** [comment]
Hi @James-N-M , you can start with #2289.Thanks.

**Comment by ryzokuken** [comment]
@James-N-M this is a pretty simple one as well, all you need to do it perform a full-codebase search for the undesirable pattern and replace it with the desirable one. Wouldn't take a lot of time or effort, this I tagged this as a good FTO candidate. (Hint: All the of the cases lie inside the `i18n` test file, so you can also just do a single file search-and-replace).

**Comment by James-N-M** [comment]
Awesome ! Thanks guys I’m on it

**Comment by James-N-M** [comment]
@ryzokuken Hey man so the error that the travis tests is getting back to me is There was an error with Danger bot’s Junit parsing: undefined method `[]’ for nil:NilClass. Also im having some trouble installing and running the application on my machine. can you point me in the direction to some different or new instructions to do this ?? I must be missing something on my computer, i have rails ruby etc etc

**Comment by James-N-M** [comment]
@ryzokuken https://github.com/James-N-M/plots2/commits/master to see my commits that I tried, maybe its cause I couldn't get the app running but yes, maybe you or @Gauravano can help me with that.

**Comment by Gauravano** [comment]
Hi @James-N-M make sure to follow the steps mentioned in https://github.com/Gauravano/plots2#installation .Thanks.

**Comment by amarachi-nwokocha** [comment]
Hey @ryzokuken Id like to take on this issue, Im a first timer so Ill need additional links and information on how to tackle this and

**Comment by gauravano** [comment]
Hi @amarachi-nwokocha, please go through the above discussion specifically https://github.com/publiclab/plots2/issues/2220#issue-294140740 and https://github.com/publiclab/plots2/issues/2220#issuecomment-364591640

I believe all information is covered in them. You can ask your doubts if you want more clarity on specific point. Thanks!

**Comment by amarachi-nwokocha** [comment]
done @gauravano please check my pull request https://github.com/amarachi-nwokocha/plots2/pull/1 and merge if its ok your feedback is highly appreciated .. i'm always open to correction

**Comment by gauravano** [comment]
Hi @amarachi-nwokocha, you need to open PR against https://github.com/publiclab/plots2. Your current PR is against forked repo.

**Comment by amarachi-nwokocha** [comment]
hi @gauravano i dont really get the meaning of your comment but i changed the link on my pull request please take a look if im right a feedback would be great here is the link to the pull request : https://github.com/amarachi-nwokocha/plots2/pull/1
Thanks.

**Comment by gauravano** [comment]
Hi @amarachi-nwokocha, you raised the PR against your own repository. If you look at this PR -https://github.com/publiclab/plots2/pull/8651 which is also opened by you, you'll notice that you've raised it against Publiclab main branch, whereas https://github.com/amarachi-nwokocha/plots2/pull/1 is against your own repository which will change code of your repository and not Public Lab project. 

**Correct repo and base branch 👇** 

<img width="1680" alt="Screenshot 2020-10-24 at 11 45 28 PM" src="https://user-images.githubusercontent.com/20878070/97089095-1415c600-1653-11eb-8654-dee98806169d.png">

**Comment by amarachi-nwokocha** [comment]
hi  Gaurav  i'm new to using git hub and ive been trying to delete one of
the pull request i made but its not working i'll check again and get back
to you please i am truly  ill work on it again thank you

**Comment by amarachi-nwokocha** [comment]
![Capture 1](https://user-images.githubusercontent.com/63500921/97136351-30009100-1753-11eb-8a51-87663c8091f5.PNG)
hi this is what i am getting when i try to change it i am confused please help me out

**Comment by amarachi-nwokocha** [comment]
the pull request https://github.com/amarachi-nwokocha/plots2/pull/1

**Comment by gauravano** [comment]
Hi @amarachi-nwokocha, you'll get it, don't worry. We're all learners. here :)

Once a PR is open, you can only change the base branch which I see in the above screenshot you tried to do. 

There are 2 ways to solve it:
1. You can create PR by visiting your branches and starting PR from there. In your case, as you already have this PR open so you'd see View PR instead of Create Pull request. So, you can close the PR present in your repository and create new one with `publiclab/plots2:main` as base. Like this - https://drive.google.com/drive/folders/1mK8hRWuBYzHvRRtDZbF5zjbuGqy8ot2T

2. You can start PR by visiting https://github.com/publiclab/plots2/pulls and clicking the **New Pull Request** button. There you'll see the base repository as publiclab/plots2 already and you can just select the branch with which you want to open PR.

Give them a try. If you still didn't get it to work then you can just click on this - https://github.com/publiclab/plots2/compare/main...amarachi-nwokocha:amarachi-nwokocha-patch-1

Thanks!!

**Comment by amarachi-nwokocha** [comment]
Hi @gauravano  I have done it here Is the link to the new PR https://github.com/publiclab/plots2/pull/8694  Thank you

**Comment by cesswairimu** [comment]
Hey all, I  believe the file that was to be changed on this issue is https://github.com/publiclab/plots2/blob/main/test/integration/I18n_test.rb.. however it looks like we do not have any code currently maintained with that format stated above... Closing this, thanks all
