### ISSUE TITLE
User cant subscribe to tags.

### ISSUE THREAD

**Issue by rishabhptr** [publiclab/plots2#2224]
### Please describe the problem (or idea)
subscribe/tag/'anything' leads to an error page. 

![screenshot from 2018-02-04 16-47-49](https://user-images.githubusercontent.com/26951824/35776919-2a7f8512-09cb-11e8-9dbe-55233f56e750.png)

**Comment by jywarren** [comment]
uh oh! I think that's supposed to be `.length.positive?` -- to make sure
it's more than zero!

Can you open a PR for this? This is pretty urgent!

Great catch!

**Comment by rishabhptr** [comment]
@jywarren I have #2225  open for this where I was using .any? to check if any relation exists but 'length.positive?' works too , so I have updated the pr :smile: .

**Comment by jywarren** [comment]
awesome, thank you!

**Comment by jywarren** [comment]
Actually shall we create a test for this method, so we don't miss this again?

**Comment by rishabhptr** [comment]
@jywarren Yes , I'd love to help! :)

**Comment by jywarren** [comment]
That'd be great -- here's the file where it ought to go -- we don't have a lot of tests in there! https://github.com/publiclab/plots2/blob/master/test/functional/subscription_controller_test.rb

If you want to open a new issue for this that'd be great, or just go for a PR -- either way! Thank you so much! 👍
