### ISSUE TITLE
Link for 'adding descriptive tags' not working .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#2228]
Hi, this is a [first-timers-only](https://github.com/publiclab/plots2/projects/2) issue. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

# The Problem

In the following image , the link **adding descriptive tags below.** is not working , 

<img width="1265" alt="screen shot 2018-02-04 at 11 52 26 pm" src="https://user-images.githubusercontent.com/14952645/35780808-4257a17e-0a07-11e8-8bf3-180c1b796213.png">

Lets **move to the bottom of the page** when we click this link .

# Solution

The line of code to change is : 
https://github.com/publiclab/plots2/blob/8f60c60d68aa60867f4edbef49f03f91e63875cd/config/locales/views/wiki/show/en.yml#L6

Lets add this to move to bottom of the page : 
`<a href='javascript: document.body.scrollIntoView(false);'>adding descriptive tags below</a>.`

### Feel free to ask any doubt regarding the issue ! Thank you !

# Steps to Fix 

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ]  set up a repository locally following the README instructions, and make sure that all tests pass
 - [ ] try to fix the issue following the steps above, but even before you're done, you can:
 commit your changes and start a pull request (see contributing to Public Lab software) but mark it as "in progress" if you have questions or if you haven't finished
- [ ]  alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see [https://publiclab.org/wiki/developers](https://publiclab.org/wiki/developers)) or go to the [chatroom](http://publiclab.org/chat) if you have questions, and take a look at our [first-timers landing page for more information!](https://github.com/publiclab/plots2/projects/2)

**Comment by us241098** [comment]
Hi i am a firs timer and interested in fixing this :)

**Comment by g33kyshivam** [comment]
Hey! Can I take up this issue? I'm a first timer!

**Comment by g33kyshivam** [comment]
Instead of scrolling down, I think direct focus on the input field is much better.
`<a href='javascript: document.querySelector('.tag-input').focus();'>adding descriptive tags below</a>`

**Comment by sagarpreet-chadha** [comment]
Hi , either one of you can go ahead 👍 . Thank you !

If you are looking for more first-timer issues [https://github.com/publiclab/plots2/labels/fto-candidate](https://github.com/publiclab/plots2/labels/fto-candidate)  😄  .

**Comment by MittalS211** [comment]
Hi! 
I am going to try this out. I am a first timer!

**Comment by Gauravano** [comment]
Hi @MittalS211 I guess this issue is solved in #2284.You can find first-timer issues at https://publiclab.github.io/community-toolbox/#r=all . Thanks.

**Comment by jywarren** [comment]
and welcome, @MittalS211 !! Very happy to have your help and if you don't find a first-timers-only issue open, ping me here and we can get one prepared for you.

**Comment by MittalS211** [comment]
Gaurav,
that would be really great! I am trying to make my way into open source,
and that would really help me. I work on html,css, javascript.
