### ISSUE TITLE
Not to show marker on profile page map if tag blurred:true exists .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#2230]
## Please describe the problem (or idea) 

- [ ]  As suggested by @jywarren in issue #1940  , lets not show marker on profile page map if the tag `blurred:true` exists . 

- [ ]  Writing a wiki page on Location-privacy (follow up of issue #1940 and [ publiclab/leaflet-blurred-location#98]( publiclab/leaflet-blurred-location#98) )

**Comment by sagarpreet-chadha** [comment]
@jywarren , kindly assign this to me 👍 😄  .

**Comment by jywarren** [comment]
Done, thank you!!!

**Comment by sagarpreet-chadha** [comment]
Opened PR #2245  and attempted to write a  wiki here : [https://publiclab.org/wiki/location-privacy](https://publiclab.org/wiki/location-privacy) 🎈 😄 .
