### ISSUE TITLE
skytruth alerts feeds on place pages and/or dashboard

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#224]
http://alerts.skytruth.org/rss?l=29.8779,-90.0037,29.9746,-89.8836#rss

with explanation and/or case study of someone responding to a report or creating one

...using powertags

**Comment by gauravano** [comment]
Hey @jywarren, can you explain this issue a bit? Thanks!

**Comment by jywarren** [comment]
This should be solved via Leaflet Environmental Layers!

**Comment by gauravano** [comment]
@sagarpreet-chadha just putting it on your radar, if you get a chance. Thanks!
