### ISSUE TITLE
Email for welcoming newcomer at time of Sign up

### ISSUE THREAD

**Issue by Gauravano** [publiclab/plots2#2241]
Welcome Email should be sent to a newcomer at time of Sign up.The content of Email can include a brief about the PublicLabs, about exploring website features, etc.We can also include in mail links which are shown on Dashboard of the newcomer.Current mail sent at sign up prompts user to join Gooogle group looks like this:- 
![join_mail](https://user-images.githubusercontent.com/20878070/35831727-c1226036-0af0-11e8-812f-ea403407e1ce.png)

We can add more content in above Mailer or can form new mailer.

@jywarren @ebarry please provide your input.Thanks.

**Comment by visheshruparelia** [comment]
I'd like to help out in this

**Comment by Gauravano** [comment]
hi @visheshruparelia most welcome, once final template of mail is decided we'll divide this in parts.

**Comment by ebarry** [comment]
This is an excellent project!!!!! @steviepubliclab check this out --

**Comment by jywarren** [comment]
@publiclab/community-reps maybe some text like:

> Welcome to Public Lab! Let's get you started. 
> 
> Your username is _____. 
> If you forget your password, enter the email address you received this message at into the prompt at https://publiclab.org/reset to reset it. 

What else would we want to send?

**Comment by Gauravano** [comment]
How about sending getting started links which we display at the dashboard of newcomers for a week?

**Comment by jywarren** [comment]
That's a great thing to start with -- super! We can modify the text later :-)

We can even base it on a Feature -- https://github.com/publiclab/plots2/blob/master/doc/DATA_MODEL.md#nodes

that way we can easily update the welcome message text (the part that doesn't include the current user's username, though, since we can't use variables in a feature)

How does that sound?

**Comment by Gauravano** [comment]
hi @publiclab/community-reps I am working on this one. Thanks.

**Comment by jywarren** [comment]
awesome!!!

**Comment by Gauravano** [comment]
What do you think, should we use inline CSS for formatting or use gems? Thanks

**Comment by Gauravano** [comment]
hi @publiclab/community-reps sorry to bother you again, but as welcome email to a user is a crucial and can be helpful to the user in getting familiar with the website. So, if you all can point to some important points to include that would be really helpful. 

Current considerations-

1.  ![first_mail_1](https://user-images.githubusercontent.com/20878070/41636669-79bc4cca-746d-11e8-8df8-3af9280fc676.png)

Thanks .

**Comment by steviepubliclab** [comment]
Hi! Can you clarify if this is showing up in an email or as a pop up?

**Comment by steviepubliclab** [comment]
I think you mean email.

Let me sync up with @ebarry when she gets back. First week in July ok? Is there some holder text you can use in the meantime as you're working on this? I'm looking for some text we recently put together that might be useful for this. (Liz where is that script? I can't find it!).

**Comment by Gauravano** [comment]
Hi @steviepubliclab, I will work on this issue at the start of July then, after @ebarry join us if you have any other ideas regarding design and content about the welcome emails, you can always drop here. Thanks.

**Comment by Gauravano** [comment]
Hi @publiclab/community-reps can we start working on this now? Sorry, I am just a little excited to design new mailer for newcomers :smile:

**Comment by jywarren** [comment]
Hi @Gauravano -- i just checked with Stevie and we have this draft, although we'll want to make final changes before merging it: 

https://gist.github.com/jywarren/893de8c52d7d977c16289eea98bb2035

However, if it's implemented as part of a feature at /features, we can tweak this any time, so it doesn't have to block.

How's that sound?

**Comment by steviepubliclab** [comment]
Here's an edit! 

Welcome to Public Lab! 

Public Lab is an open community dedicated to making environmental monitoring more accessible to all. In Public Lab, our public questions, ideas and exploration help to build the resources available for everyone to use. 

_UN INFO HERE_

There’s a lot you can do in Public Lab: learn how to do environmental investigation in your community, help to build and develop research tools, and work with others to advocate to for change.

Ready to jump in? 

- Join an open call (https://publiclab.org/open-call)
- Find an upcoming event (www.publiclab.org/events)
- Ask a question (www.publiclab.org/questions)
- Follow Public Lab on social media (https://www.facebook.com/PublicLab/)
- Help support our work (www.publiclab.org/donate)

Looking forward to hearing from you soon,

The Public Lab Community

**Comment by Gauravano** [comment]
We can also add PublicLab logo at top-center position of email.  

Any other image you guys wanna suggest @jywarren @steviepubliclab ? Also, any design or should we keep it simple text email?
Thanks!

**Comment by jywarren** [comment]
Let's keep it pretty simple text for now, but if this is implemented as a
Feature, we can add images later, right?

Thanks, Gaurav!!!

**Comment by Gauravano** [comment]
Making a feature is fine. But, I doubt images can be added via feature. Are we displaying images via feature anywhere @jywarren ?

**Comment by Gauravano** [comment]
I found this 
![without_image](https://user-images.githubusercontent.com/20878070/42407735-a7e017fc-81de-11e8-9d10-41cdc0ebe183.png)

we pass feature body as a string, so we can make a new helper function which would return us the node and then we can render node content just like we do for normal node in Email. How does that sound @jywarren ?

**Comment by jywarren** [comment]
That sounds great!

**Comment by Gauravano** [comment]
Hi @jywarren @steviepubliclab I have raised PR at #3025 for this issue. Please create a new feature by name **welcome-email-body** . Thanks!

**Comment by jywarren** [comment]
awesome!!!
