### ISSUE TITLE
bug: upon re-checking the "blur my location" box, the red square malfunctions

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2243]
### Please describe the problem

> What happened just before the problem occurred? 

This is a bug related to Geographic Features https://github.com/publiclab/plots2/issues/1416

I used the "Link with location" feature:
- I navigated to the location i was interested in
- i browsed with the default of "blur my location"
- i unchecked "blue my location"
- i re-checked the default "blur my location -- and that's when the problem occurred: the red square got stuck on the spot where i had "unblurred" my location, and did not reset despite panning it off the screen or zooming in or out. See here: 

![location-bug](https://user-images.githubusercontent.com/161439/35831998-3b6d78a4-0a91-11e8-824e-25785e7a8d02.gif)

> What did you expect to see that you didn't?

I expected to have the "link to location" interface return to its default "blur my location" functionality during which the red square updates depending on how the map was panned underneath it. The red square is always pinned in the center of the map, even as the map is panned underneath. 

### Please show us where to look

https://publiclab.org/notes/gwirth/07-01-2014/preliminary-stitch-of-dredge-island-planting-day-in-jamaica-bay

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

liz

**Comment by jywarren** [comment]
Hi, this is an issue with https://github.com/publiclab/leaflet-blurred-location/ -- a library used on this site. It could be helpful to post over there!

**Comment by jywarren** [comment]
Moving over to https://github.com/publiclab/leaflet-blurred-location/issues/112 -- thanks!!!
