### ISSUE TITLE
inline-map , [map:tag:_tagname_:_latitude_:_longitude] showing incorrect nodes . 

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#2254]
### Please describe the problem (or idea)

Tested this here , [https://publiclab.org/wiki/test-wiki-page](https://publiclab.org/wiki/test-wiki-page) , [map:tag:_tagname_:_latitude_:_longitude] is showing incorrect nodes . 

 It is because we are calling our API in `/_leaflet.html.erb` which gives all the nearby_nodes using `_latitude_` and `_longitude` and does not consider `tagname` .

### Possible Solutions : 

1.) Using the same partial `/_leaflet.html.erb` and making a query on database and hence showing markers .  
2.) Making a new partial and making an API and a model search-helper function and loading blank map and calling API and hence showing markers .

**Comment by sagarpreet-chadha** [comment]
@jywarren , how should i approach this issue ? Thanks 😄  !

**Comment by Gauravano** [comment]
Hi @sagarpreet-chadha, actually while making this API, I highlighted this issue to @jywarren as mentioned in #1934, as this API has been successful I think we should make a new API which incorporates tag.I would be happy to make API for this if you want help :sweat_smile:.Thanks

**Comment by jywarren** [comment]
That would be great, @Gauravano!!! :+1:

**Comment by jywarren** [comment]
Shall we rename this to focus on the API tagging implementation and add some code links to that? Thanks, all!

**Comment by jywarren** [comment]
Hi @sagarpreet-chadha -- just wanted to know if this is completed now... as it's old. WE may have moved way past it!

**Comment by jywarren** [comment]
@sagarpreet-chadha just bumping this up! Thank you!!!

**Comment by sagarpreet-chadha** [comment]
On it 👍 !

**Comment by jywarren** [comment]
lets also hear from @milaarauja to be sure we're on track here! thanks!!!

**Comment by jywarren** [comment]
Is this still open?

**Comment by sagarpreet-chadha** [comment]
Hi @jywarren ,
Yes this is solved : you can check here : https://publiclab.org/notes/sagarpreet/01-30-2019/inline-map-testing . 
Okay currently inline maps are not showing on `/wiki` pages but it related to LEL (https://github.com/publiclab/plots2/issues/5678) . Closing this 😄 !!!

**Comment by jywarren** [comment]
awesome!!!
