### ISSUE TITLE
500 error on posting an answer

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2256]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I pressed Publish on an answer here:

https://publiclab.org/questions/warren/01-17-2018/what-are-materials-we-could-include-in-a-kite-making-materials-pack

The text I posted was:

```
Via our friends at NASA AREN:

spruce sticks -- https://www.aircraftspruce.com/categories/building_materials/bm/menus/wp/spruce.html 

⅛ foam core -- https://www.amazon.com/24X36-White-Foam-Core-Backings/dp/B0073YEE8A 

```

I wonder if the 1/8 caused this? Weird character?

**Comment by namangupta01** [comment]
Yes 1/8 caused the problem because i tied to post without 1/8 and it was posted.

**Comment by jywarren** [comment]
Indeed! Changing the 1/8 to just `1/8` instead of the fraction format didn't cause an error! Maybe we need some kind of encoding protection to filter posts for this kind of thing?
