### ISSUE TITLE
profile tagging; possibly map of users

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#226]
`skill:area`
`gear:balloon`
`gear:spectrometer`
`resources:type`
`willtravel:circumference`
`email:addy@addy`
`phone:555...`

Addendum: 
all projects - contact person
- active projects
- past projects
- possible projects / issues that need attention

Addendum 2:
local mailing list overlays

**Comment by ebarry** [comment]
Can this be combined with https://github.com/publiclab/plots2/issues/104

**Comment by jywarren** [comment]
yes, please do so. Issues in this tracker haven't been gone through for redundancy or out-of-date-ness; on Friday I focused solely on closing down the old tracker.

**Comment by ebarry** [comment]
Moving to [104](https://github.com/publiclab/plots2/issues/104)
