### ISSUE TITLE
Count of research notes and comments missing on profile page

### ISSUE THREAD

**Issue by ViditChitkara** [publiclab/plots2#2262]
![pp-1](https://user-images.githubusercontent.com/22616017/35877355-149149b2-0b9b-11e8-807a-28d2fca9f7f7.jpg)
We should add the count of research notes and comments in the tab panel

**Comment by jywarren** [comment]
Agreed! Although this is getting quite crowded -- could we hide the text
names and just show the counts, when the screen is too narrow? Using
`hidden-xs hidden-md` and such from Bootstrap styles?

**Comment by ViditChitkara** [comment]
> Agreed! Although this is getting quite crowded -- could we hide the text
> names and just show the counts, when the screen is too narrow? Using
> `hidden-xs hidden-md` and such from Bootstrap styles?

Yes, that needs to be taken care of. I noticed that the icons are not properly aligned on small screen.
![mobile-profile-1](https://user-images.githubusercontent.com/22616017/35879220-a9499352-0ba0-11e8-8c7e-7e7c72216d48.jpg)
We also need to find icons for Research and co-authored tabs since it is looking a bit untidy on mobile site. Does this make sense?
