### ISSUE TITLE
sync user.id and drupal_user.uid

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#227]
Notes:

@btbonval: Looks like the out of sync is only effecting the first 50 or so users (only 46 are effected and all have rusers.id under 50.

@jywarren: I think the 50 in question were those who signed up for the beta plots2 site before we had syncing set up. This may indeed be messy, but basically I think we have to do something where we "make space" for them to get the correct ruser.id, and if we can't figure it out, just use one high enough to have an acceptable uid and id.

@btbonval: Assigning new uids sounds like a good compromise, but unfortunately the
id/uid is an extremely integral number in the database. Changing it can be
very difficult to keep straight. At any rate, I think only drupal_user.uid is used across the board. We
could probably replace user.id without any far reaching consequences.

@btbonval: We'll have to very carefully, and by hand, reassign those ids not only in the User table but across all tables the user could have potentially touched. Since there are no foreign keys in the database, the only way to know all places a user'd id can appear is to review all the models and find which ones reference DrupalUser, I think.

@btbonval: primary keys aren't meant to be changed in a relational database, ever :(

@btbonval: You know what, it might be worth deleting the User entries for misaligned users in Rails console. The console supports cascade, so we should see if we can delete only when there is nothing to cascade. As long as there is nothing to cascade, we can delete the User entry and then generate a new User via a migration. Since DrupalUser.uid is authoritative, we would want to remove any User where User.id does not correspond to the DrupalUser.uid. For those cases where a cascade is needed ... well let's just hope that never comes up :(

@jywarren: We can probably list which tables depend on uid:

* DrupalNode
* DrupalNodeRevision
* DrupalNodeCommunityTag
* TagSelection
* DrupalComment
* DrupalFile
* Image
* DrupalProfileValue

**Comment by btbonval** [comment]
So if we pick `User.id` to be de facto standard, we could change _foreign keys_ to start pointing at `User.id` instead of `DrupalUser.uid`. That isn't changing primary key values at all.

Once `DrupalUser.uid` is no longer used by any other table, we could fully deprecate it. We'd migrate any unique information `DrupalUser` still maintains into `User` and update any controller code to make full use of `User`.

This is a fairly large project. The data migration would require a lot of care and a number of steps. The list of tables currently using `uid` is a good start, but we'll also want to review the code to see where it has hard coded calls to `uid`.

**Comment by jiteshjha** [comment]
How about adding offset to the primary keys of either of the tables?
' UPDATE parent_tbl SET primary_key_col = primary_key_col + 5000;
UPDATE child_tbl SET foreign_key_col = foreign_key_col + 5000; '

Is this probably going to break anything?

**Comment by jywarren** [comment]
Bryan is right that this is a big project that has to be done carefully, but I believe we can do it by not ever changing `DrupalUsers.uid` -- instead changing `User.id` which is not depended on for anything currently. 

Only the first ~50 entries in `User` have `User.id` not matching `DrupalUsers.uid`. I'm running a query on production now to find out how many, and exactly what they are:

````ruby
mismatches = []
DrupalUsers.all.each do |user|
  mismatches << [user.name,  user.uid, user.user.id] if user.user && user.uid != user.user.id
end
````

It's taking a while to run.

**Comment by jywarren** [comment]
OK, too long; it was using individual queries to get the matching User records. I need to use `joins` to just get them together. Sorry, please hold.

**Comment by jywarren** [comment]
We'll start with non-spam users. But this is not recording users who have not been 'migrated' to the new site. Some are experiencing migration errors due to the id mismatch, like in #424. But for starters:

````ruby
mismatches = []
DrupalUsers.joins("INNER JOIN rusers ON rusers.username = users.name").where(status: 1).each do |user|
  mismatches << [user.name,  user.uid, user.user.id] if user.user && user.uid != user.user.id
end
````

**Comment by jywarren** [comment]
OMG, so many spam users makes this sooooo slow. I think we could also swap for this to make it even faster:

      mismatches << [user.name,  user.uid, user.user.id] if user.username && user.uid != user.id

**Comment by jywarren** [comment]
OK, it's now just a single query, but it returns 300,753 records. :-(

We should run it on the entire thing (so maybe we can select just a few columns, not the whole record) but when we actually run this we shouldn't have to run it on more than the first 50 or so `Users`

**Comment by jywarren** [comment]
Even better:

    DrupalUsers.joins("INNER JOIN rusers ON rusers.username = users.name").where(status: 1).order('id').each do |user|

I'll consolidate all these comments in a bit. Sorry!

**Comment by jywarren** [comment]
This is all the `DrupalUser.uids`:

    [4, 12, 7, 9, 3, 46673, 554, 403, 704, 152, 77, 43229, 49682, 151, 379, 43651, 46964, 8, 51998, 54025, 1225, 57263, 43047, 1057, 45309, 58354, 51, 409, 46795, 57430, 44551, 46929, 1205, 164, 56693, 44836, 57052, 45662, 163, 59609, 60478, 1083, 60509, 48275, 60514]

And this is all the `User.ids`:

    [3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 37, 38, 39, 40, 41, 42, 43, 45, 46, 47, 48, 49, 50]

It's spaghetti. But I think that we could manually fix it with a list so short. If we can find who can have their `User.id` synced without colliding with someone else, we can go one by one.

**Comment by jywarren** [comment]
I like Jitesh's idea of adding a large number. My plan now:

1. add 400,000 to each `User.id` in the 45 in question
2. go through each one and re-assign each a `User.id` to match their `DrupalUsers.nid`. 

This'll work because the low-numbered `User.id`s will now be free.

**Comment by jywarren** [comment]
I'd like to test this with a few users, and manually confirm that all is well before attempting for all 45. I'm thinking:

    ["cfastie", 554, 9], ["hagitkeysar", 152, 13], ["patcoyle", 77, 14], ["btbonval", 43229, 15],

That is, just increasing the `User.id` by 400,000, and seeing if that breaks anything.

**Comment by jywarren** [comment]
OK, @btbonval - i changed your `User.id` record to `900015` instead of `15` (ended up having to use more than 400,000). I also had to change your `User.openid_identifier` to `http://old.publiclab.org/user/900015/identity`. It saved OK; can you try it out? 

I think the only code used is in `/app/models/user_selection.rb`, which I'm not sure is used at all?

**Comment by jywarren** [comment]
Hi, @Fastie - would you be willing to let me change your user id as I did for Bryan and you could tell me if anything goes wrong? We're hoping to resolve a major issue in the database leftover from the Drupal days. Any issues would be recoverable.

**Comment by Fastie** [comment]
Sure, good luck.

**Comment by jywarren** [comment]
OK, done. One thing that may not work immediately is a fresh SpectralWorkbench/MapKnitter login. I'd say don't log out, and try logging in in an incognito window to check. Thanks, Chris! I can revert tomorrow morning if it doesn't work out.

**Comment by Fastie** [comment]
I was able to log into publiclab, mapknitter and, spectralworkbench from Chrome incognito windows without incident.

**Comment by jywarren** [comment]
Great. Any other weirdnesses on the publiclab.org site? If not, that's great and we can probably resolve this issue pretty easily.

**Comment by Fastie** [comment]
I didn't notice any unusual behavior at publiclab. I didn't do much except navigate around, start to edit a comment, and change my password.

**Comment by jywarren** [comment]
OK, I'm going to ask a few other people. @ebarry @patcoyle @shaief - could we do the same test on your accounts? 

Would you be willing to let me change your user id as I did for Bryan and Chris and you could tell me if anything goes wrong? We're hoping to resolve a major issue in the database leftover from the Drupal days. Any issues would be recoverable, and we haven't had issues so far.

**Comment by shaief** [comment]
@jywarren - you are more than welcome to test things using my account. Good luck and thanks!

**Comment by patcoyle** [comment]
Sure Jeff,

Test as needed with my account.

Thanks,
Pat

**Comment by jywarren** [comment]
Thanks! @shaief and @patcoyle, I just changed yours. So please keep an eye
out for issues.

**Comment by jywarren** [comment]
Unless @shaief, @patcoyle, @btbonval or @cfastie have noticed any errors on the site that could be related to this, I think we can go ahead and do this process for all 45 users, and close this issue up at last!

**Comment by patcoyle** [comment]
Thank Jeff,

I haven't been doing much, but didn't notice any issues.

Pat

**Comment by Fastie** [comment]
The only issue I have noticed recently is [this one](https://github.com/publiclab/plots2/issues/481) about  the preview button not working on new comments on research notes.

**Comment by jywarren** [comment]
OK, apologies, but the id change wasn't saving properly, but i was just able to update @shaief, @patcoyle, @btbonval and @cfastie's user accounts -- now please watch for any ill effects, thanks! (chris, the one you saw is unrelated, thanks for reporting)

**Comment by jywarren** [comment]
I've just made this change for all affected users and emailed them. If this goes well we can re-assign proper uids in the next few days and close this issue FINALLY.

Fingers X!

**Comment by jywarren** [comment]
I've manually confirmed that this is now resolved. All users now have synced `id` and `uid` -- we'll wait to hear if there are issues, but it's looking good. This will not come up again if the fix was correct.
