### ISSUE TITLE
Duplicate errors in questions

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2272]
### Please describe the problem (or idea)
When a person asks question which have an existing title
![image](https://user-images.githubusercontent.com/20972099/35933144-bfc615aa-0c5f-11e8-9fce-817a9aa88b3f.png)

**Comment by SidharthBansal** [comment]
@jywarren thanks for assigning it to me

**Comment by jywarren** [comment]
Hmm, did I assign this to you? was that me? I think i have a rogue bot or something doing some assigning and such!!!

**Comment by SidharthBansal** [comment]
I am not sure whether you assigned this to me or not.But I am pretty sure there is some problem with the bot assign feature. I saw some issues assigned to me as soon as I posted them. Whenever I will encounter this behaviours again I will bring into your notice

**Comment by jywarren** [comment]
OK! Thanks.
