### ISSUE TITLE
Rich text editor adds "/" in front of headers (ie '/##header text')

### ISSUE THREAD

**Issue by shapironick** [publiclab/plots2#2274]
This makes the "##" header markdown not work. 

Other issues with the note editor are:

- formatting bar stays at the bottom making it very tedious to do formatting in a long research note
-no way to center text or photos
-often in long notes the editor frame will snap to a section that I am not editing (particularly when I hit enter or add an image) which can be frustrating on top of the other editor issues. 

### What's your PublicLab.org username?
nshapiro

### Browser, version, and operating system
Chrome on a PC
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hi, thank you! I'm merging this into one I moved for @ebarry -- https://github.com/publiclab/PublicLab.Editor/issues/125

Being on the Editor repository should increase chances we can solve this. Thank you!

**Comment by shapironick** [comment]
great thanks! I moved two sub-points into the editor's repository and +1'd the other one that was already in there.
