### ISSUE TITLE
Add notifications via Ajax Calls with Noty

### ISSUE THREAD

**Issue by namangupta01** [publiclab/plots2#2277]
### Please describe the problem (or idea)
Currently, when we make ajax calls we don't receive any notification.
For example : When user like anything the notification can pop up saying `Liked!`
Or when we post an answer notification can be `Answer Posted!`.
There are variety of library that we can use for this. But i personally like Noty JS.
Noty JS is also present in ruby gem form.

**Comment by jywarren** [comment]
This is a good idea! What might it look like?

**Comment by namangupta01** [comment]
Sorry i miss this comment.
This will e look like 
https://www.google.co.in/search?q=noty+js+demo+gif&tbm=isch&source=iu&ictx=1&fir=40c5C6hCkQ3iAM%253A%252Cwx71zIwC3dVmBM%252C_&usg=__ojtibMLfvQeR-9Fz613wzgbaQQM%3D&sa=X&ved=0ahUKEwjxqOWZnszbAhXWeX0KHYMPDggQ9QEIMjAE#imgrc=40c5C6hCkQ3iAM:
