### ISSUE TITLE
archive and make searchable Google Group history

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#228]
:-P big doozy, but with the RSS feeds, maybe not so terrible... see how we currently already read them: https://github.com/jywarren/plots2/blob/master/app/models/drupal_node.rb#L270

**Comment by ebarry** [comment]
It would be great if mailing list discussions showed up in search results on our website.

**Comment by jywarren** [comment]
Note: this'd probably involve 2 new tables for topics and messages so we could cache/search/archive all mailing list activity. topics might have a column called "list" with the name of the corresponding google group, so we wouldn't need a 3rd table.

**Comment by btbonval** [comment]
Closing this as a duplicate of #209 (not technically duplicate, but being subsumed)
