### ISSUE TITLE
No initial check for valid email on password reset

### ISSUE THREAD

**Issue by taibayard** [publiclab/plots2#2281]
### Please describe the problem (or idea)

Adding a check on password reset to test invalid email 

> What happened just before the problem occurred? Or what problem could this idea solve?

Will prevent the form from submitting invalid email types.

> What did you expect to see that you didn't?
"Error invalid email"

### Please show us where to look

https://publiclab.org/reset/

**Comment by Souravirus** [comment]
I want to work on this @taibayard

**Comment by jywarren** [comment]
Complete in #2315! Thanks, all!
