### ISSUE TITLE
Search bar not properly working

### ISSUE THREAD

**Issue by ViditChitkara** [publiclab/plots2#2287]
![search-error-1](https://user-images.githubusercontent.com/22616017/36031984-85ae17c2-0dd2-11e8-98e9-3f2bed7ce1af.jpg)
Steps to reproduce:-
1) Type something in the searchbar
2) Click on the search icon just right to the search input (should actually redirect to /search/ with the search results)
3) Shows a validation message saying "Please! Type something to search"

**Comment by bronwen9** [comment]
Hey! I've been finding that one will pop up following a successful search: say, I'll use the search box to look for "pumpkin", which will let me see a dropdown of usernames and research note headings, but if I try to use the search field a second time (even on another page) I get the error. I can refresh the page to let me access the search field again.

**Comment by ViditChitkara** [comment]
Hey @bronwen9 , so do you get an error or the search bar doesn't show up anything in the pop up??  The pop-up is working fine on my pc. However,  another problem occurs when we click the search button just right to the text-field, it says "Please enter something" (even when the search bar is not empty).

**Comment by bronwen9** [comment]
I can type into the search bar, but after the first search I get the "please enter something" pop up on ALL following searches, even if I navigate to other pages on the website. The only way I can resume use of the search bar is by refreshing the whole page. 

Thanks!

**Comment by bronwen9** [comment]
Here's a gif of that issue if that helps: first search is successful, but I'm not able to perform a second search. 

![pumpkins](https://user-images.githubusercontent.com/8331717/36278518-1df9ff3a-1262-11e8-9b14-cb45a3af5895.gif)

**Comment by bronwen9** [comment]
Here's another hinky search.. it seems like the magnifying glass doesn't actually serve a function, the only available option is to select either a tag or a research note. 

![water](https://user-images.githubusercontent.com/8331717/36278911-4d28fca6-1263-11e8-8b69-90b00d39f036.gif)

**Comment by ViditChitkara** [comment]
That's exactly what I found out!! This is actually happening due to some faulty script.The magnifying glass should actually redirect to a page where are the search results are rendered! I've worked on a fix for it in #2288 . Hope this would work well once #2288 is merged!! Thanks for reporting it though!!!!

**Comment by bronwen9** [comment]
Thanks for untangling this!
