### ISSUE TITLE
Share buttons not aligned

### ISSUE THREAD

**Issue by Gauravano** [publiclab/plots2#2289]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you :gift_heart:

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!
:thinking: What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.
### Please describe the problem
Notes page shows un-aligned Twitter and Fb buttons.Example: https://publiclab.org/notes/programmer1200/02-03-2018/photometer-kit-idea
![uneven](https://user-images.githubusercontent.com/20878070/36049950-a93f9d68-0e0a-11e8-8e3e-7f31e28679b9.png)

### Solution

Change CSS of the buttons so as to align them.Relevant view file that need change is  https://github.com/publiclab/plots2/app/views/home/_social.html.erb

:clipboard: Step by Step

:raising_hand_woman: Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

:floppy_disk: Commit your changes

:twisted_rightwards_arrows: Start a Pull Request.

:checkered_flag: Done Ask in comments for a review :)

:thinking::question: Questions?

Leave a comment below!

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seems stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!
Thank you!

Your help makes Public Lab better! We deeply appreciate your helping refine and improve this site.

**Comment by BigFun76** [comment]
Has this been resolved?

**Comment by James-N-M** [comment]
I’ll claim this as well ! Since you tagged in it earlier

**Comment by ViditChitkara** [comment]
@BigFun76 , no this isn't resolved yet
Either one of you could resolve it!!

**Comment by BigFun76** [comment]
OK. First-timer here. Still trying to figure out how it all works. Thanks.

**Comment by ViditChitkara** [comment]
Cool, you could look into the file mentioned by @Gauravano for fixing the bug.

**Comment by Shadlimitless** [comment]
Has this issue been closed? First timer here

**Comment by BigFun76** [comment]
Sorry everyone, I figured out how to clone this to my laptop and edit the file. However, I do not know how to run it to see if the changes work. I don't have any experience with Ruby, so maybe someone else should take this one on and I can find something else.

**Comment by Gauravano** [comment]
Hi @BigFun76, you can follow installation steps https://github.com/publiclab/plots2#installation and still face any issue regarding running, we would surely help you.

**Comment by BigFun76** [comment]
Thanks

**Comment by BigFun76** [comment]
OK, I have submitted a PR. Not sure if it is exactly what you were wanting. At least I now understand the process a little better. Next step is being better with the actual code.

Thanks again everyone!

**Comment by Shadlimitless** [comment]
@ViditChitkara thanks ! Let me look for another open issue :-)

**Comment by BigFun76** [comment]
I will need to let someone else handle this issue. I am in over my head on some of the logistics for Ruby, etc. and don’t know when I’ll have time to sort through them. Sorry everyone.

**Comment by Shadlimitless** [comment]
Id like to pick this up, following the instructions on cloning from @Gauravano

**Comment by ViditChitkara** [comment]
@Shadlimitless cool, go ahead! 
No worries @BigFun76 you could ping us if you need any kind of help!

**Comment by Gauravano** [comment]
hi @Shadlimitless , this issue is resolved in #2329 , you can find new issues at https://publiclab.github.io/community-toolbox/#r=all .Thanks.
