### ISSUE TITLE
Alignment of Read more button

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2294]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you :gift_heart:

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!
:thinking: What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.
### Please describe the problem
Unaligned Read more button
On the admins view it is ok
![image](https://user-images.githubusercontent.com/20972099/36072769-9528eb4e-0f4b-11e8-9199-b60b3024757a.png)
but on the ordinary users 
![image](https://user-images.githubusercontent.com/20972099/36072776-c07c7e32-0f4b-11e8-9882-467f6f6a1da5.png)
the read more button is on the right but should be in center

### Solution

Change CSS of the buttons so as to align them.Relevant view file that need change is  
https://github.com/publiclab/plots2/blob/d3225bc5148eab5e5db5d8be38653dab5fc2409e/app/views/notes/_notes.html.erb#L50-L51

:clipboard: Step by Step

:raising_hand_woman: Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

:floppy_disk: Commit your changes

:twisted_rightwards_arrows: Start a Pull Request.

:checkered_flag: Done Ask in comments for a review :)

:thinking::question: Questions?

Leave a comment below!

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seems stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!
Thank you!

Your help makes Public Lab better! We deeply appreciate your helping refine and improve this site.

**Comment by noordean** [comment]
I would love to work on this task but I've not been able to replicate this error locally. This is what I have for ordinary user on my machine.
<img width="1280" alt="screen shot 2018-02-13 at 2 05 48 pm" src="https://user-images.githubusercontent.com/14357823/36151427-7253c274-10c7-11e8-86aa-6c4175d0a435.png">

**Comment by ViditChitkara** [comment]
Hey @noordean !! Actually the problem is not about research button but the "Read more" Button. Currently there isn't any research note of "user". All you need to do is create a research note (logged in as user)  and then view the profile.

**Comment by SidharthBansal** [comment]
I am sorry, @ViditChitkara thanks for correcting me. It is actually read more.
@noordean you need to make research notes to see the listing

**Comment by ViditChitkara** [comment]
👍

**Comment by noordean** [comment]
Thanks @ViditChitkara and @SidharthBansal. I will get a PR up for this.
