### ISSUE TITLE
Unexpected behaviour of "notes" link on the dashboard welcome line

### ISSUE THREAD

**Issue by ViditChitkara** [publiclab/plots2#2295]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

![home-page-1](https://user-images.githubusercontent.com/22616017/36074249-8cc5c0a4-0f63-11e8-9241-7441d8bb2d1c.jpg)
The link associated with "1 notes" in the above screenshot redirects to the dashboard page which is quite unexpected.

> What did you expect to see that you didn't?

There should be a separate recent notes page just like popular notes as shown in the following screenshot:-
![popular-1](https://user-images.githubusercontent.com/22616017/36074301-22f7155a-0f64-11e8-8282-cf2667c1ad35.jpg)

### Please show us where to look

https://publiclab.org/dashboard

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

vidit

**Comment by ViditChitkara** [comment]
Working in #2296

**Comment by SidharthBansal** [comment]
Great catch
