### ISSUE TITLE
Like count error on profile page

### ISSUE THREAD

**Issue by ViditChitkara** [publiclab/plots2#2298]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you :gift_heart:

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!
:thinking: What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.
### Please describe the problem
The like count on the profile page does not correspond to the number of liked notes shown on /profile/user/likes' page
![like-count-1](https://user-images.githubusercontent.com/22616017/36075588-0ec9bf70-0f77-11e8-8d5d-0b5042a7c1cc.jpg)
![like-page-1](https://user-images.githubusercontent.com/22616017/36075589-14d8f7a0-0f77-11e8-98d9-26356c584810.jpg)

### Solution

https://github.com/publiclab/plots2/blob/57f0d6f97844b9ba070f7a048fc9a942c1ecf0c8/app/models/drupal_user.rb#L97-L106

Like_count method could be similar to liked_notes method. We could replace 
https://github.com/publiclab/plots2/blob/57f0d6f97844b9ba070f7a048fc9a942c1ecf0c8/app/models/drupal_user.rb#L98 with something like:-
`
Node.includes(:node_selections).references(:node_selections).where("type = 'note' AND node_selections.liking = ? AND node_selections.user_id = ? AND 
node.status = 1", true, uid).count
`

:clipboard: Step by Step

:raising_hand_woman: Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

:floppy_disk: Commit your changes

:twisted_rightwards_arrows: Start a Pull Request.

:checkered_flag: Done Ask in comments for a review :)

:thinking::question: Questions?

Leave a comment below!

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seems stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!
Thank you!

Your help makes Public Lab better! We deeply appreciate your helping refine and improve this site.

**Comment by claudiaaw** [comment]
Hi! I'm a first timer and I would love to try this out please! Apologies if I might take some time on this one as I understand there is an installation process to run the code.

**Comment by visheshruparelia** [comment]
I want to take this up

**Comment by ViditChitkara** [comment]
Go ahead!!

**Comment by visheshruparelia** [comment]
I have one doubt tho, what does the 'likes' function above the function 'like_count' do in drupal_user modal? I mean if gets the list of all liked notes why won't the current code of 'like_count' work?

**Comment by ViditChitkara** [comment]
Actually like_count counts the number of NodeSelections. Whenever a Node is deleted the associated NodeSelection is not deleted which is the reason why like_count and liked_notes give different counts.

**Comment by ViditChitkara** [comment]
The tab uses liked_count method while the page showing liked notes uses the liked_notes method.

**Comment by visheshruparelia** [comment]
Yeah true, but then the 'likes' function should look like the liked_notes and like_count no?

**Comment by ViditChitkara** [comment]
It should. We need to write a migration which destroys all the NodeSelections whose associated nodes do not exist. 
Then adding a dependent_destroy against :- 
https://github.com/publiclab/plots2/blob/57f0d6f97844b9ba070f7a048fc9a942c1ecf0c8/app/models/node.rb#L46
could solve our problem. Does that make sense?

**Comment by visheshruparelia** [comment]
Yeah this makes more sense, then I guess the previous commit I made isn't required(If we make the required migration and adding a dependent_destroy), correct?

**Comment by ViditChitkara** [comment]
Yeah either one of them would do. The later would be a better option rather than changing the methods.

**Comment by visheshruparelia** [comment]
Agreed the later method is more proper than updating methods, I'll update the code acordingly and create a new PR then

**Comment by ViditChitkara** [comment]
Cool!

**Comment by visheshruparelia** [comment]
I've made the necessary changes and created a PR [here](https://github.com/publiclab/plots2/pull/2330), please review it

**Comment by MargaretAN9** [comment]
I am a first timer - Can I take this up ?

**Comment by aamarill** [comment]
hello @ViditChitkara and @jywarren!

It looks like @visheshruparelia has not worked on this for a while. From looking at the latest PR, it looks like it didn't pass Travis tests. Can I try to fix this? Thanks! 😄

**Comment by jywarren** [comment]
Yes please! And if you want to start from the existing PR, that'd be great.
Thank you!

**Comment by ViditChitkara** [comment]
That would be awesome @aamarill . Feel free to ask, if you get stuck anywhere!

**Comment by aamarill** [comment]
Thanks guys, I thought I replied to this earlier. But I am on it! 💪

**Comment by aamarill** [comment]
Hey guys in the "installation" section of the [README.md](https://github.com/publiclab/plots2/blob/master/README.md) you have the following:


><img width="813" alt="screen shot 2018-05-24 at 5 26 26 am" src="https://user-images.githubusercontent.com/29871004/40485537-a1326362-5f13-11e8-88cc-a9ecf8d8994a.png">

Is that correct? The normal workflow I have seen and read in GitHub documentation is to:
1. Fork the original repo
2. Clone from your fork ->`git clone https://github.com/your_username/plots2.git`, not from the original repo. The original repo is synced via the upstream branch. 

I would be glad to fix the README if needed 😄

**Comment by aamarill** [comment]
I added `, dependent: :destroy` to `has_many :node_selections, foreign_key: :nid` in [app/models/node.rb](https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L71).
Can you give me some hints on how to create a migration to destroy all the `NodeSelections` whose associated nodes do not exist? 
Thanks! 😄

**Comment by jywarren** [comment]
Hi, @aamarill that's a really good point. We'd love to have a README fix!!!

**Comment by shouri007** [comment]
Hi, I see this issue is still open but the PR seems to be merged on the master branch. Can you please let me know if I can claim this bug if it is still open? Thanks :)

**Comment by aamarill** [comment]
@shouri007  I believe this issue can be closed now. @ViditChitkara can you confirm?
Thanks!

**Comment by jywarren** [comment]
I believe that's right -- thank you both!

If you're interested, we have another issue that, although it's not quite a first-timers-only issue, is pretty straightforward. We'd be happy to support you on this:

https://github.com/publiclab/plots2/issues/2493

Thanks! 👍 🎉

**Comment by madeofhuman** [comment]
@jywarren this is still not working. I'd love to pick up this issue?

<img width="707" alt="Screenshot 2019-03-14 at 10 09 52 AM" src="https://user-images.githubusercontent.com/7345686/54344519-5686bc80-4641-11e9-9b4d-5e6c228a7a65.png">

**Comment by madeofhuman** [comment]
@jywarren could you please re-open this issue? I just raised a PR for it. Thanks.

**Comment by jywarren** [comment]
Oh but then i just merged it! Closing again!
