### ISSUE TITLE
Add glyphicons to notes page

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2299]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you :gift_heart:

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!
:thinking: What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.
### Please describe the problem
Some of the tabs on /notes/popular are not having glyphicons. Add the required glyphicons
![image](https://user-images.githubusercontent.com/20972099/36077847-b01596d8-0f95-11e8-91fd-7b6996facfa2.png)

### Solution
Relevant view file that need change is  
https://github.com/publiclab/plots2/blob/57f0d6f97844b9ba070f7a048fc9a942c1ecf0c8/app/views/notes/index.html.erb#L29-L33
Refer https://www.w3schools.com/icons/bootstrap_icons_glyphicons.asp or similar sites
:clipboard: Step by Step

:raising_hand_woman: Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

:floppy_disk: Commit your changes

:twisted_rightwards_arrows: Start a Pull Request.

:checkered_flag: Done Ask in comments for a review :)

:thinking::question: Questions?

Leave a comment below!

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seems stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!
Thank you!

Your help makes Public Lab better! We deeply appreciate your helping refine and improve this site.

**Comment by AndyCodez** [comment]
I'd like to work on this.

**Comment by Gauravano** [comment]
That's great @AndyCodez, you can start.
