### ISSUE TITLE
research popup menu too long for netbook screens and won't scroll

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#230]
@btbonval: On my netbook, the Research popup menu goes to the bottom of my browser screen, ending at "Providence." Maybe there is nothing past that, maybe there is, but I cannot tell either way. If I scroll down, the page in back scrolls, but the white popup menu remains fixed. I can't access the whole thing.

@jywarren: Huh - the navbar-pinned-to-top behavior is eliminated for screens small enough to trigger "tablet" or "phone" styles in Bootstrap. But it is possible to have a window wide enough to remain in desktop styles while not being tall enough to see the whole menu. This seems to be approx 575px tall by about 1024px wide. We could use a @media (max-height:500px) CSS command to either hide some menu items on smaller screens, or potentially disable the pinned-to-top style for those screens. Those changes would go in: https://github.com/jywarren/plots2/blob/master/app/assets/stylesheets/application.css and be compiled into the minified stylesheet with the command rake assets:precompile

We could use css: `max-height:` and `overflow:scroll` even if it looks a bit ugly :-(

**Comment by btbonval** [comment]
There are a number of easy-to-use responsive UIs that will handle different sizes with relative ease.

Changing to someone like that would require a bit of a UI overhaul, but it would not demand that we manage finicky `@media` details or other strange CSS pieces.

Foundation is an example I have used in the past. There are good things about it, and there are bad things about it. If I recall correctly, there are some really nice ways to mark differences between mobile, small format, and desktop formats so you have better control of the responsive design.
http://foundation.zurb.com/learn/features.html

Bootstrap is supposed to be responsive and easy to design across devices, but I'm not sure if it really does much. It's supposed to be automatic, so if it isn't already working for you across devices, it probably won't.
http://getbootstrap.com/getting-started/#disable-responsive

I feel like there was one other that I had used, but I don't recall it.

Here's a roundup from 2013. I've only heard of and used two of them.
http://designinstruct.com/roundups/html5-frameworks/

**Comment by jywarren** [comment]
We are using bootstrap 2, actually, it just needs some tweaking in this one
edge case. Upgrading to Bootstrap 3 also would work as it triggers mobile
styles at 768px or narrower. Not sure if bootstrap 2 supports a custom
mobile width definition.

**Comment by jywarren** [comment]
Fixed in upgrade to Bootstrap 3! Tnx!
