### ISSUE TITLE
Remove link to /lists from sidebars

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2300]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you :gift_heart:

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!
:thinking: What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.
### Please describe the problem
/lists from sidebars are no longer used
![image](https://user-images.githubusercontent.com/20972099/36078178-6c2c728a-0f99-11e8-8df6-2cd7038eed57.png)

### Solution
Remove link to /lists from sidebars
:clipboard: Step by Step

:raising_hand_woman: Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
1. Remove  plots2/app/views/sidebar/_list.html.erb
2. Remove the lines
https://github.com/publiclab/plots2/blob/57f0d6f97844b9ba070f7a048fc9a942c1ecf0c8/app/views/sidebar/_user.html.erb#L9-L15

:floppy_disk: Commit your changes

:twisted_rightwards_arrows: Start a Pull Request.

:checkered_flag: Done Ask in comments for a review :)

:thinking::question: Questions?

Leave a comment below!

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seem stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!
Thank you!

Your help makes Public Lab better! We deeply appreciate your helping refine and improve this site.
This will help in completing the remaining parts of #2117

**Comment by f3mshep** [comment]
I am working on a pull request for this issue. This will be my first contribution to open source!

**Comment by Gauravano** [comment]
That's great @f3mshep.You can ask here if you want any help.

**Comment by f3mshep** [comment]
I removed the specified lines of code and the partial file itself, do I also need to alter the test to reflect the changes?

**Comment by Gauravano** [comment]
no @f3mshep that's not required as it's First timer issue so all steps are mentioned

**Comment by f3mshep** [comment]
@Gauravano I just submitted a PR from a uniquely named feature branch. It is #2311. I mentioned in the PR that 8 tests fail since the partial has been removed.

**Comment by f3mshep** [comment]
@Gauravano I added the partial back in, but removed all references from the _user partial to the _list partial.
