### ISSUE TITLE
PLANNING ISSUE : Unpublished draft of research note for review by participants

### ISSUE THREAD

**Issue by Gauravano** [publiclab/plots2#2307]
Steps for implementation of the draft feature as suggested by @jywarren in #129 are :

* [x] making a `draft` status (maybe status = 3?) for nodes (not wiki pages), which makes it not visible to anyone but the author. 
* [x] a POST parameter like `draft=true` to bypass most of [the "create" method in the notes_controller](https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb#L92) and which adds the `status = 3` when you publish
* [x] a button to post the form with the `draft` parameter set to `true` [in the Rich Editor](https://github.com/publiclab/plots2/blob/master/app/views/editor/rich.html.erb) template
* [x] a modification of the `with:____` coauthor tag (see [this post](https://publiclab.org/notes/partsandcrafts/12-02-2017/quick-build-raspberry-pi-microscope) which allows co-authors to see the post
* [ ] an alert at the top of a draft page that offers a shareable link to the post for sending around
* [ ] maybe a secret URL token that allows access to the post even if someone doesn't have an account?

**Comment by jywarren** [comment]
:-) this looks rad, thanks!!

**Comment by Gauravano** [comment]
Hi, @jywarren @ebarry @steviepubliclab due to adjacency in @ViditChitkara 's proposal and mine, we have decided to divide things as per @jywarren 's suggestions.So, starting with the 3rd part, UI for managing digest settings. Vidit would be doing this part. So, I am thinking to propose this issue i.e., Draft Creation but with some advanced features:- 

1. UI for link sharing:-  
	In this, modal would popup containing options to copy the secret link, there would be a column for entering Email Id or usernames to which that secret link would be mailed, inviting them to edit or give suggestions on the draft.

![modalpart2](https://user-images.githubusercontent.com/20878070/36992292-75079216-20d0-11e8-9c2f-9b45212fa97b.png)

2. The comment section in the draft state would serve as discussion area so if any coauthor wants to give feedback they can write there.The discussion messages wouldn’t be visible publicly once the draft is published.

3. PDF creation of the research note 

Please let me know if you find above parts interesting otherwise @ViditChitkara and I can divide the UI settings part. @publiclab/community-reps your ideas and feedback are welcome.Thanks.

**Comment by ViditChitkara** [comment]
@jywarren any thoughts on this?? I am happy to give the UI part a go. Could you please provide your feedback so that we could adjust our timelines accordingly?

**Comment by jywarren** [comment]
Yes, i'll write back today, sorry!!! 👍

**Comment by Gauravano** [comment]
@jywarren please provide your views on these ideas https://github.com/publiclab/plots2/issues/2307#issuecomment-370518643 . Thanks.

**Comment by jywarren** [comment]
Sorry i said i'd write back but never did! 

Let's try to make this simpler for starters -- we can offer the link to share without offering to mail it for you -- that'll simplify the initial implementation. It could even say `I've shared a draft post from PublicLab.org with you -- click here to view and comment or edit: ________` -- you know? 

> The comment section in the draft state would serve as discussion area so if any coauthor wants to give feedback they can write there.

> The discussion messages wouldn’t be visible publicly once the draft is published.

I'm not sure about this -- perhaps we can offer the author the ability to delete the comments one by one, in case -- but I worry that the "collaboration" ought to be public by default. If they don't want it to be, they can delete comments. Make sense? This simplifies our workflow here, and we can build it out more deeply in separate steps. 

Thanks!!!

**Comment by Gauravano** [comment]
thanks, @jywarren .I will break the issue into smaller steps, and open a new Planning issue with some implementation details very soon.

**Comment by jywarren** [comment]
great!

**Comment by jywarren** [comment]
Hi! It looks like there may be a draft related bug here?

https://publiclab.org/notes/gauravano/03-13-2018/test-question

It fails on this line, with `@node` evaluating to `nil` -- 

https://github.com/publiclab/plots2/blob/8e9dec8787158cd504b68ba340557599c61434e4/app/controllers/notes_controller.rb#L55

```
Processing by NotesController#show as HTML
  Parameters: {"author"=>"gauravano", "date"=>"03-13-2018", "id"=>"test-question"}
Completed 500 Internal Server Error in 33ms (ActiveRecord: 28.2ms)

NoMethodError (undefined method `status' for nil:NilClass):
  app/controllers/notes_controller.rb:55:in `show'
```

Thanks!!!

**Comment by Gauravano** [comment]
actually @jywarren I deleted the node after a minute of its creation

**Comment by Gauravano** [comment]
And, after deleting the node I tried the link too I guess that's how this log is generated

**Comment by jywarren** [comment]
OK! sounds great.

**Comment by jywarren** [comment]
Ooh, some of these are done now, huh?

**Comment by Gauravano** [comment]
yup :smiley: ! List updated.

**Comment by jywarren** [comment]
Awesome!
