### ISSUE TITLE
Profile pages need count of comments

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2309]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

Profile pages do not show a count of comments, not even a (0), just no count at all. 

<img width="1173" alt="screen shot 2018-02-12 at 11 33 13 am" src="https://user-images.githubusercontent.com/161439/36107610-9bd9ca56-0fe8-11e8-975f-5c3aad225329.png">

> What did you expect to see that you didn't?

I expected to see a number inside of parentheses after Comments, in this case `Comments (2)`

### Please show us where to look

https://publiclab.org/profile/mistercoffee -- click on Comments, and you will see that in fact this person has commented twice. 

### What's your PublicLab.org username?
liz

**Comment by ViditChitkara** [comment]
Hi Liz, this would be done once #2263 is merged!! . 😃😃

**Comment by ViditChitkara** [comment]
I have also added count of research notes along with minor UI tweaks for this navbar!!😄😄

**Comment by ebarry** [comment]
awesome!!!!

--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net

**Comment by jywarren** [comment]
Merging this with #2262 and closing as it'll be solved shortly in #2263! Thanks!
