### ISSUE TITLE
Wiki pages with 0 likes not shown on '/wiki/liked' page (sorted by no. of likes)

### ISSUE THREAD

**Issue by ViditChitkara** [publiclab/plots2#2310]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you :gift_heart:

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!
:thinking: What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.
### Please describe the problem

Wiki page when sorted according to likes does not show pages with 0 likes:-
![liked-2](https://user-images.githubusercontent.com/22616017/36112098-8788ac46-104e-11e8-8f20-6f9995cecb29.jpg)
![liked-3](https://user-images.githubusercontent.com/22616017/36112106-8e3dad98-104e-11e8-9ba2-6d1d702f1b78.jpg)

### Solution

We need to refactor the query given below to select pages with 0 likes too :- 
https://github.com/publiclab/plots2/blob/57f0d6f97844b9ba070f7a048fc9a942c1ecf0c8/app/controllers/wiki_controller.rb#L337-L339
The above could be replaced by:-
`
    @wikis = Node.limit(40)
      .order('node.cached_likes DESC')
      .where("status = 1 AND nid != 259 AND (type = 'page' OR type = 'tool' OR type = 'place') AND 
                   cached_likes >= 0")
`

:clipboard: Step by Step

:raising_hand_woman: Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

:floppy_disk: Commit your changes

:twisted_rightwards_arrows: Start a Pull Request.

:checkered_flag: Done Ask in comments for a review :)

:thinking::question: Questions?

Leave a comment below!

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seems stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!
Thank you!

Your help makes Public Lab better! We deeply appreciate your helping refine and improve this site.

**Comment by jsmayo** [comment]
Hmm, I'll give it a go :]

**Comment by ViditChitkara** [comment]
Cool! Go ahead!!

**Comment by jsmayo** [comment]
I think I did it.. still kinda fuzzy on the whole process :S

**Comment by ViditChitkara** [comment]
No problems!! I'm happy to help wherever you feel you are stuck!

**Comment by ViditChitkara** [comment]
@jsmayo could you please create a pull request of your changes here??

**Comment by balaaagi** [comment]
@jsmayo  Can i Take it and complete along with pull request ?

**Comment by jsmayo** [comment]
I thought I did

**Comment by danielleshwed** [comment]
is this issue still available to fix?

**Comment by Gauravano** [comment]
hi @danielleshwed, this issue is already solved in #2362.You can find new first-timer issues at https://publiclab.github.io/community-toolbox/#r=all .Thank you.
