### ISSUE TITLE
version history for everything

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#233]
@btbonval: 

>Comments may be edited in place, but no history is stored with comment edits.
> When a spammer takes an account and edits comments, those comments are overwritten and lost forever. Ignoring spammers, there might be other good reasons to maintain a comment version history internally.
> I see no reason to show the version history to users.
> Spammer situation has been resolved, but this still might be handy. I'm not sure how much work it took Jeff to recover the old comments from database backups, but a versioning system should streamline the process.

**Comment by btbonval** [comment]
I think this would be adequately covered in #204
