### ISSUE TITLE
Social Media icons on profile page not at center (Firefox)

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#2332]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 🤔 PROBLEM : 

The **social media icons** are not at **center** for some browsers (example Mozilla Firefox), see image : 

<img width="872" alt="screen shot 2018-02-15 at 10 12 05 pm" src="https://user-images.githubusercontent.com/14952645/36268757-626612ae-129d-11e8-9499-8a8ffcaf82d2.png">

Lets **change the CSS** to center these icons for all **browsers** .

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the line https://github.com/publiclab/plots2/blob/27d37c9101cfc82188fd991f6be4151428b56307/app/views/users/profile.html.erb#L9 
Lets change the CSS alignment to just **center** instead of **-webkit-center** . 

[See this page](https://github.com/publiclab/plots2/projects/2) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://github.com/publiclab/plots2/projects/2). Thanks!

**Comment by jmphilips** [comment]
I'd like to take this one.

**Comment by sagarpreet-chadha** [comment]
Hi @jmphilips , that would be great ! Thanks !

**Comment by jmphilips** [comment]
@sagarpreet-chadha 

```
ERROR: Permission to publiclab/plots2.git denied to jmphilips.
fatal: Could not read from remote repository.
```
I apologize.  I am receiving this error when I try and push my branch up to GitHub.
