### ISSUE TITLE
Move "search by topic" to top of page and remove sidebar on /questions

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2333]
(via @ebarry) This is a two-part issue -- on http://publiclab.org/questions, we have a sidebar area called `Filter questions by topic` which we'd like to move to a 2-column area in the main column, next to the "Ask a question" area.

The code for the form to be moved is here:

https://github.com/publiclab/plots2/blob/d078466a6dc1c1c4ae3b39e45a8ccb861b7d5860/app/views/sidebar/_user.html.erb#L9-L11

We can move the form into a `col-md-6` div using Bootstrap's grid system: https://getbootstrap.com/docs/3.3/css/#grid-options -- so, 

****

Then we'd like to delete the sidebar entirely, by deleting this line: 

https://github.com/publiclab/plots2/blob/d078466a6dc1c1c4ae3b39e45a8ccb861b7d5860/app/views/questions/index.html.erb#L1

We should then change the main area to be full-with, so `9` becomes `12` on this line:

https://github.com/publiclab/plots2/blob/d078466a6dc1c1c4ae3b39e45a8ccb861b7d5860/app/views/questions/index.html.erb#L3

The new side-by-side forms could use some text tweaking too: 

* The "filter" one we're moving could be titled: `View questions by topic`, with placeholder input text `type your topic` and button text `Search`
* The original area could become `Ask a question here` with placeholder text `type your question` and button text `Continue`

The new two-column area may need some design tweaking to get it right, so if you're able to take on this issue, please post a screenshot with your pull request! Thank you!

**Comment by stefannibrasil** [comment]
I am taking this one too @jywarren

**Comment by jywarren** [comment]
awesome, that's great!
