### ISSUE TITLE
Reposition the bar of editing icons at top of composition box

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2334]
### Please describe the problem (or idea)

> What problem could this idea solve?

I would like to consider moving the "kitchen sink" bar of editing icons above the text box, currently it is below the text box. 

<img width="699" alt="screen shot 2018-02-15 at 12 03 39 pm" src="https://user-images.githubusercontent.com/161439/36269851-49c8289a-1248-11e8-8899-be537f47586c.png">

I feel there are downsides to having the editing icons below the textbox, namely, that doesn't handle well while scrolling up and down the page, and in cases where the note is long, it's hard to scroll all the way down instead of having it pinned at the top. 

The scrolling issue may also be a related but separate issue, in that the /post and /question page should not be "below the fold" on the average desktop display. These pages should not scroll unless someone drags the composition box to be longer. Let me know if i should break this issue out.  

> What did you expect to see that you didn't?

I would expect to see the editing icons positioned at the top of the text box.

### Please show us where to look

https://publiclab.org/questions
https://publiclab.org/post

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

liz

**Comment by sukhbir-singh** [comment]
@ebarry I would like to work on this issue.

**Comment by jywarren** [comment]
Looks great -- actually, both these issues would be great to see moved over to https://github.com/publiclab/PublicLab.Editor if that's possible, which is where our Editor project lives. Thanks!!!

> The scrolling issue may also be a related but separate issue, in that the /post and /question page should not be "below the fold" on the average desktop display. These pages should not scroll unless someone drags the composition box to be longer. Let me know if i should break this issue out.

I think this does need to be its own issue, and I don't quite follow yet! We can unpack this more over at the other repository, though. Thanks!

**Comment by jywarren** [comment]
Moving over to https://github.com/publiclab/PublicLab.Editor/issues/124, thanks!
