### ISSUE TITLE
Insert hyphens into tag search input query

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2335]
(via @ebarry) On this page: https://publiclab.org/questions/ in the sidebar, we let people filter by tag, but when you type `water quality`, it doesn't offer the tag name `water-quality` (because all tagnames are hyphenated). 

The logic for the query is here:

https://github.com/publiclab/plots2/blob/d078466a6dc1c1c4ae3b39e45a8ccb861b7d5860/app/views/tag/_sorting.html.erb#L15

Let's insert a filter to replace spaces with hyphens as people type. So we should be able to replace `query` with:

```js
query.replace(' ', '-')
```

This'll improve matching overall and make it default that it selects a good related tag for many more possible inputs.

Any help appreciated on this!!! 👍

**Comment by sukhbir-singh** [comment]
I am working on this

**Comment by utsha1510** [comment]
working on this

**Comment by Gauravano** [comment]
That's great @utsha1510 .If you have any query please feel free to ask.Thanks.

**Comment by jywarren** [comment]
@utsha1510 how are you doing? Can we help out at all?

**Comment by utsha1510** [comment]
I'm a beginner to open source so I'm working on it and will let you know if
help needed.

**Comment by stefannibrasil** [comment]
Hey, everyone! It looks like only changing `query` on line 15 does not work. Check here: https://stackoverflow.com/questions/14262770/javascript-replace-dash-hyphen-with-a-space 

So maybe assign the replace method to a new variable like: 

`var replaced_query = query.replace(' ', '-');
`
and replacing `query` on line 15 with the one above should work. Let me know if you have any questions!

**Comment by jywarren** [comment]
Thanks @stefannibrasil -- awesome suggestion!

**Comment by milaaraujo** [comment]
Hi everybody! I am a beginner in this open source world and I would like to contribute for the project. I was working on this issue just to get familiar with the code and @stefannibrasil's solution is correct. I know @utsha1510 is working on the issue, but if the problem remains open after all I would like to open the PR. ;)

**Comment by jywarren** [comment]
Hi, @utsha1510 -- we'd love to find you another issue to work on if you're interested and this one ends up being taken. 

Here, I just made this one: https://github.com/publiclab/plots2/issues/2379

Feel free to claim it! And welcome!!!

**Comment by milaaraujo** [comment]
Hi @jywarren! I created the PR, can you check if I did everything right?
