### ISSUE TITLE
Add support for people writing markdown

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2336]
### Please describe the problem (or idea)

> What happened just before the problem occurred? 

I am reporting in from a conversation with @shapironick that reveals a lack of support for people writing markdown in the new Editor (in /questions and /post). The current workflow for someone who wishes to write markdown -- in fact, if they are a long time contributor they probably learned markdown in order to contribute to publiclab.org -- is that they have to click the button ambiguously marked "Rich" at the bottom right of the composition box: 

<img width="699" alt="screen shot 2018-02-15 at 12 03 39 pm" src="https://user-images.githubusercontent.com/161439/36270474-c9e491a2-1249-11e8-8210-fc8f91406db5.png">

I suggest that no one accustomed to writing markdown on publiclab.org would have the faintest idea that -- since updates to our editor -- clicking a button marked "Rich" would be required for their careful formatting to work. As a result, the final published post has had all the markdown formatting "escaped" out with `/`

Trying to fix the formatting without understanding the role of the "Rich/Markdown" button leads to many frustrating cycles of publishing and editing. 

> What did you expect to see that you didn't?

Here are a couple ideas: 
* someone writing markdown in the composition box would automatically trigger help text directing the writer to click the button to change the mode to markdown
* change the button text to say "click here to compose in markdown /  click here to compose in Rich Text"

### Please show us where to look

https://publiclab.org/questions
https://publiclab.org/post

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

liz

**Comment by jywarren** [comment]
We could scan the input for multiple `##` or `**`, or `](` (commonly part of a Markdown link) and display an alert below the box? This should be an issue over at https://github.com/publiclab/PublicLab.Editor, however. Can you move this over there, Liz?

**Comment by jywarren** [comment]
Moving over to https://github.com/publiclab/PublicLab.Editor/issues/125, thanks!
