### ISSUE TITLE
Remove /tags page sidebar

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2337]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

The Tags page is a bit cluttered! https://publiclab.org/tags

## Solution

This is a pretty easy one -- let's remove the sidebar on the first line here:

https://github.com/publiclab/plots2/blob/9cf54a1189f1dfa16abc0ae705463b12dc799e64/app/views/tag/index.html.erb#L1-L3

from the http://publiclab.org/tags page

Then, let's change `col-md-9` to `col-md-12` on the line below so that the tags page becomes full-width. Thanks!!

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page](https://publiclab.github.io/community-toolbox/#r=all)!

**Comment by stefannibrasil** [comment]
Hi, @jywarren I am taking this one. Thanks!

**Comment by jywarren** [comment]
oh, awesome. thank you!!!
