### ISSUE TITLE
Tag pages should have unanswered and answered buttons for questions

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2339]
### Please describe the problem (or idea)
The urls like /tag/balloon have a tab questions.
![image](https://user-images.githubusercontent.com/20972099/36272750-701f0de6-12a8-11e8-86e1-5fa58336614d.png)
The tab is missing the ability to sort the questions based on answered and unanswered questions as we do have on the profile page.
![image](https://user-images.githubusercontent.com/20972099/36272812-99fcf5c4-12a8-11e8-8ec6-2fa81c6e21be.png)

> What happened just before the problem occurred? Or what problem could this idea solve?
The questions page should also have such ability to sort the tagged questions into two parts-answered and not answered.

**Comment by SidharthBansal** [comment]
May I assign it as I am doing the prs related to tags and profile pages @jywarren ?

**Comment by jywarren** [comment]
Sure!

**Comment by noordean** [comment]
This issue and #2340 seems to be the same.

**Comment by SidharthBansal** [comment]
They are not same but they are similar. The codes are overlapping. As you are doing #2340, so it would be great if you will work on it instead of me. 
The difference is here you need to change the show action of the tag controller and there you have changed the show-for-author action

**Comment by SidharthBansal** [comment]
D
