### ISSUE TITLE
Tag_for_author questions should be divided into answered and unanswered

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2340]
### Please describe the problem (or idea)
The urls like /tag/balloon*/author/warren have a tab questions.

![image](https://user-images.githubusercontent.com/20972099/36272976-101349d4-12a9-11e8-9f91-7b5f0520f893.png)

The tab is missing the ability to sort the questions based on answered and unanswered questions as we do have on the profile page.
![image](https://user-images.githubusercontent.com/20972099/36272812-99fcf5c4-12a8-11e8-8ec6-2fa81c6e21be.png)

> What happened just before the problem occurred? Or what problem could this idea solve?
The questions page should also have such ability to sort the tagged questions into two parts-answered and not answered.

**Comment by noordean** [comment]
Can I work on this ?
If yes, a quick question: I can't see the green label `Answered` on my own questions after they've been answered, just as we have in your first screenshot above. This is mine:
<img width="1280" alt="screen shot 2018-02-16 at 8 59 34 am" src="https://user-images.githubusercontent.com/14357823/36298406-42fb7462-12f8-11e8-9ccd-95f513a5d359.png">

**Comment by SidharthBansal** [comment]
Yeah sure you can work on this issue. 
You need to accept the answer to show green accepted button there.
