### ISSUE TITLE
Spam in wiki page revisions is wrongly returned in search results

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2343]
### Please describe the problem

> What happened just before the problem occurred? Or what problem could this idea solve?

I am trying to remove spam from publiclab. The following gif shows that I searched "escort" in an "incognito" window, and was autosuggested several profiles and wiki pages. When i clicked one of the wiki pages, in fact it is one of our major pages "non-profit initiatives". Why was this page returned in search results? To find out, i went to another tab where i was logged in. As a Site Admin, i can see all the spammed revisions where the term "escort" is contained. 

![spam-in-wiki-revisions](https://user-images.githubusercontent.com/161439/36278014-7ef8a202-1260-11e8-96b3-51affbec0363.gif)

> What did you expect to see that you didn't?

Content that we have already marked as spam -- in this case, revisions of wiki pages -- should not be returned in search results. 

### Please show us where to look

https://publiclab.org/wiki/revisions/nonprofit-initiatives
https://publiclab.org/wiki/revisions/join
and several other of our major pages that have been spammed over the years. 

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

liz.
Issue brought to my attention by @bronwen9

**Comment by jywarren** [comment]
Hi, I think this query needs to include `.where(status: 1)` :

https://github.com/publiclab/plots2/blob/fa16a69f8f475c101bc23325f4df7411c2172872/app/models/node.rb#L23-L25

**Comment by jywarren** [comment]
Or maybe `.where('node_revisions.status = 1')`

**Comment by ebarry** [comment]
Potentially, we would want to be able to search through prior revisions, but not through revisions that have been marked spam.

**Comment by jywarren** [comment]
This was solved!
