### ISSUE TITLE
Summer of Code call for proposals -- RGSoC and GSoC

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2345]
We're part of two different summer fellowship programs this year, Rails Girls Summer of Code (#RGSoC) and Google Summer of Code (#GSoC) -- both recruit software contributors to work on open source projects. Read more and post a proposal for comment here: 

https://publiclab.org/notes/warren/02-15-2018/call-for-summer-of-code-2018-proposals

We especially welcome proposals from people from groups under-represented in free and open source software!

As always, our community aspires to be a respectful place. Please read and abide by our [Code of Conduct](https://publiclab.org/conduct).

You can also ask questions on that post, at the bottom. Thanks everybody and eager to see your proposals!

**Comment by jywarren** [comment]
@publiclab/reviewers 🎉  🎈

**Comment by stefannibrasil** [comment]
Congrats, everyone! I've been looking for a while for projects to contribute and it took me a long time to find first-time friendly projects like this. Thank you for this, you are really welcoming =)

**Comment by jywarren** [comment]
:-) welcome one more time!

Also @publiclab/soc folks who've participated before, we'd love to hear from you again, even just to say hi!

**Comment by StlMaris123** [comment]
Hi @jywarren :smile:

**Comment by jywarren** [comment]
@StlMaris123 absolutely! Sorry I missed your comment! 🎉

**Comment by jywarren** [comment]
Hi all, just another request to review and leave comments on proposals if you can, whether you're proposing yourself or you're reviewer or potential mentor. I know a lot of you have exams now and I hope they're going well! 

 https://publiclab.org/notes/warren/02-15-2018/call-for-summer-of-code-2018-proposals

**Comment by jywarren** [comment]
We have [17 proposals](https://publiclab.org/notes/warren/02-15-2018/call-for-summer-of-code-2018-proposals)!! Thanks @publiclab/reviewers @publiclab/soc for your help reviewing even during a busy time of year! 

Excitingly, you may see people proposing ideas that build on your work from last summer so please help them get oriented and be friendly! 👍 😄
