### ISSUE TITLE
Start linking from appropriate places to new location privacy help page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2346]
We have a new page (still being worked on) here: https://publiclab.org/wiki/location-privacy

this explains our new location privacy features, and we should put helpful links to it from anywhere we prompt location-- so, from:

* the profile page http://publiclab.org/profile
* add `Learn about privacy` to `Share your own location on your profile.` on http://publiclab.org/people below the map
* on the Leaflet Blurred Location dialogs at https://github.com/publiclab/plots2/blob/master/app/views/map/_peopleLeaflet.html.erb and https://github.com/publiclab/plots2/blob/master/app/views/map/_userLeaflet.html.erb

Anywhere else?

**Comment by visheshruparelia** [comment]
I'd like to take this up

**Comment by jywarren** [comment]
That'd be great -- does it make sense to you? Need help finding lines of code to work on? 👍

**Comment by James-N-M** [comment]
Ill take this if @visheshruparelia has not.

**Comment by visheshruparelia** [comment]
Going through the code rn

**Comment by visheshruparelia** [comment]
Sorry, was busy for the past 2 days so couldn't look into it. @jywarren can you check my [PR](https://github.com/publiclab/plots2/pull/2368) and let me know if anything more is required?

**Comment by jywarren** [comment]
Ah, i think I just merged the PR by @James-N-M in https://github.com/publiclab/plots2/pull/2360 -- sorry, I didn't realize there were 2 open! Checking now...

**Comment by jywarren** [comment]
Responded in https://github.com/publiclab/plots2/pull/2368 and closing now. Sorry for the mixup! 👍
