### ISSUE TITLE
UI updation: Sortable headers of table with up/down arrow icon

### ISSUE THREAD

**Issue by sukhbir-singh** [publiclab/plots2#2352]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Please describe the problem (or idea)
The aim of this issue is to track the implementation of same sorting UI across all tables on public lab site with sorted headers.

- [x] List of wiki pages (sortable headers implementation pending), https://publiclab.org/wiki
- [x] Sorting implementation needed in people page, https://publiclab.org/people
- [x] Sorting implementation in Tags page (not all headers sort BOTH ascending and descending)
- [ ] All tables in wiki page, Example: https://publiclab.org/wiki/spectrometry

Suggestions are welcome on this issue.

**Comment by sukhbir-singh** [comment]
I am currently working on this issue as suggested by @jywarren in issue #2331

**Comment by Paarmita** [comment]
@jywarren Can I work on this issue or @sukhbir-singh has taken up?

**Comment by namangupta01** [comment]
@sukhbir-singh Are you still working on this issue? or do you need some help? Let us know if you need some help.
@Paarmita He already made a pr for this issue. You can choose other issues. There are plenty of them.
Thanks :)

**Comment by sukhbir-singh** [comment]
Hi @namangupta01 , for this issue I have made pull request for first and second part. PR for first part is still open and PR for second part is already got merged. So part 3 and 4 are still open for contributors. 
Currently I am working on my proposal so I might get back to making new PRs after 2-3 days. Meanwhile, if someone else is interested can work on 3rd and 4th part of this issue.

**Comment by ebarry** [comment]
EXCITING!!!!!

**Comment by jywarren** [comment]
`/tags` is now sortable by # of uses (as of 29 days ago, whoops!)  -- thanks all!

![image](https://user-images.githubusercontent.com/24359/42884745-20b02b22-8a6d-11e8-8c3e-3dd07ce25b83.png)

**Comment by jywarren** [comment]
Added a new one, see above!

**Comment by cesswairimu** [comment]
The remaining task is the same as https://github.com/publiclab/plots2/issues/9338, Closing this and we can track there. Thanks all
