### ISSUE TITLE
Bug in wiki page: "see more" text gets shuffled on clicking of sortable headers

### ISSUE THREAD

**Issue by sukhbir-singh** [publiclab/plots2#2356]
### Please describe the problem (or idea)
I came across a bug in wiki page of https://www.publiclab.org/wiki/advanced-grids. In exclusive grids section table on clicking of the title header, "Show 6 more button" also getting suffled. but the expected thing is "Show more" button must always remains at bottom of table as last row independent of any type of sorting.

See screenshot below:-

![screenshot from 2018-02-17 00-38-50 copy](https://user-images.githubusercontent.com/13816752/36325529-153e7a98-137e-11e8-9abf-e0a4c44d41fc.png)

**Comment by jywarren** [comment]
Great catch! Thank you for filing!

**Comment by adrian-lara** [comment]
Hi @jywarren ! I’m a first-time contributor to this project and was hoping to help out with this issue. Has anybody picked up this issue? If not, could I give it a shot?

**Comment by jywarren** [comment]
Yes please! That would be great. The code for this is here:

https://github.com/publiclab/plots2/blob/b98790631fe22edf34750de5bff5c641ff6ea7b7/app/views/grids/_notes.html.erb#L55-L62

See when it's more than 9, it inserts this `Show X more` row. 

Thank you!

**Comment by Gauravano** [comment]
Solved in #2416
