### ISSUE TITLE
create powertag to list child pages

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#236]
tagging a page like /wiki/spectrometer with something like "childpage" should create a special box on the page to list pages that are tagged parent:spectrometer

**Comment by jywarren** [comment]
This will now be possible with the `[notes:tagname]` inline powertag, in #703. Closing.

**Comment by ananyo2012** [comment]
Uh I think the wrong PR is linked.

**Comment by jywarren** [comment]
You're right! Sorry, #702. :-) good catch!
