### ISSUE TITLE
Improve the current state of testing

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plots2#2364]
- [ ] Watch "How to stop hating your tests" (https://vimeo.com/145917204)
- [ ] Read "TestProf - A Good Doctor for slow Ruby Tests" (https://evilmartians.com/chronicles/testprof-a-good-doctor-for-slow-ruby-tests)
- [ ] Check out their RubyProf Guide (https://github.com/palkan/test-prof/blob/master/guides/ruby_prof.md)
- [ ] Read required docs
- [ ] Improve tests
- [ ] Profit

**Comment by ryzokuken** [comment]
@jywarren please take a look.

**Comment by James-N-M** [comment]
I figure I should actually learn some ruby/rails before trying to take this on haha, if not truly knowing the ins and outs of ruby/rails I dont mind doing some reading 💃

**Comment by ryzokuken** [comment]
@James-N-M Good idea! You could check out the resources I have listed in the PR body itself.

**Comment by jywarren** [comment]
We are doing so much better on this now! Closing!!!
