### ISSUE TITLE
Check current validity of README.rdoc

### ISSUE THREAD

**Issue by ruan-brandao** [publiclab/plots2#2367]
### Please describe the problem (or idea)

I have noticed that the [README.rdoc](https://github.com/publiclab/plots2/blob/master/README.rdoc) file is not updated in a long time, and seems to be a default version without instructions to run the application.

I was wondering if it is okay to remove `README.rdoc`. If it is, I can do it.

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

ruanbrandao

**Comment by jywarren** [comment]
sure, that sounds good! Thank you!
