### ISSUE TITLE
Showing message at the top of upgrade page

### ISSUE THREAD

**Issue by Gauravano** [publiclab/plots2#2369]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labeled.

****

Pages like this:

https://publiclab.org/notes/stoft/09-16-2016/stability-upgrade-mockup-for-plab-spectrometer-3-0

...are proposed upgrades for a specific project (they have the tag `upgrade:dssk` where "dssk" is the tag name for the project they're upgrading, so we should show a message similar to the one shown on this page:

https://publiclab.org/notes/warren/09-20-2016/building-the-stoft-stability-upgrade-for-desktop-spectrometry-starter-kit-3-0

The notification could be shown on this line, triggering on the power tag `upgrade` instead of `replication`:

https://github.com/publiclab/plots2/blob/3702e83c8f50c86ab6d6a197579990d334a12d90/app/views/notes/show.html.erb#L8

`This is an upgrade for ___________. Try building it and _report back how it goes_.`

"report back..." should link to `#Upgrades` which appears lower on the page. 

[ ] Addition of notice to top of page by adding following condition

`<% if @node.has_power_tag('upgrade') %><div class="alert alert-info"><%= raw t('notes.show.upgrade') %> <a href="/n/<%= @node.power_tag('upgrade') %>"><%= raw t('notes.show.replication_link') %></a>.</div><% end %> `

[ ] Replace `t('notes.show.upgrade')` and `t('notes.show.replication_link')` to match the following text `This is an upgrade for ___________. Try building it and _report back how it goes_.`

[ ] Adding link to upgrades in report back

Feel free to ask for any help...

**Comment by James-N-M** [comment]
Hi @Gauravano I'd like to claim this issue. If this post could get some formatting etc, what ever you think that will explain this more clearly and some hints on what I need to modify exactly

**Comment by Gauravano** [comment]
Thanks, @James-N-M .Ok, I am further dividing this into steps.

**Comment by Gauravano** [comment]
hi, @James-N-M I have divided the issue into steps, start with the first one and raise a PR soon, you may ask for help at any point.Thanks.

**Comment by James-N-M** [comment]
@Gauravano I couldnt seem to figure this out properly, my plots 2 also wont run, can you give me more detailed steps on how to accomplish this issue

**Comment by nagano564** [comment]
Is someone still working on this?

**Comment by Gauravano** [comment]
hi @nagano564 , there is PR open at #2375 for this issue, but you can take this one if @James-N-M isn't working on it anymore

**Comment by Gauravano** [comment]
hi @James-N-M , you wanna give this issue a try again?

**Comment by nagano564** [comment]
K.. lemme see if I can help.. Thanks @Gauravano. if @James-N-M wants to keep working it that's cool also. I will take a stab in the next day or two and if he wants to keep working on it back off. Thanks

**Comment by James-N-M** [comment]
@nagano564 @Gauravano  All yours m'dude ! Final projects and other school things right now thanks boys ! 💯

**Comment by Gauravano** [comment]
Thanks @James-N-M !!! We would love to have your help during summer if you are  free. @nagano564 you can start working on this one.Thanks !!!

**Comment by nagano564** [comment]
@Gauravano when trying to run `rake db:setup` 
I am getting this error message

```SyntaxError: /Users/Julie713/bloc/open/plots2/app/models/user.rb:16: empty range in char class: /\A[-[:alnum:]+.]+@[[:alnum:]-.]+[.][[:alpha:]]+
\z/
```

**Comment by seafr** [comment]
User unit tests are passing for me. Try to change the following:
- `[[:alnum:]-.]` to `[-[:alnum:].]`

Awaiting your feedback.

**Comment by nagano564** [comment]
fixed. Thanks

**Comment by seafr** [comment]
It's quite simple @nagano564 . Just make a new branch and make the changes on it, then open a PR. You won't have to touch `master`. Go ahead and give it a try, there's a lot of people here who would be very happy to help out.
Note: When doing `git add`, make sure you add only the modified file.
Note 2: Do **NOT** merge to `master` on your fork.

**Comment by nagano564** [comment]
But the master right now is dirty because we changed the regex. Should I
add and commit but not push?

**Comment by Gauravano** [comment]
Actually, you can't commit to master otherwise all the branches you extend from there will have that commit along. Can you try running `rails s` with old regex only and tell us the output? Thanks.

**Comment by seafr** [comment]
Ah, I see. You can "clean" master and revert it back to what it was before by using `git checkout -- <filename>`. Then from there, you create a new branch and follow the instructions I wrote above. Finally, make the commit on the new branch itself and push it to your fork.
Note: In this case, the change is small enough to wipe it out and start from scratch.

**Comment by nagano564** [comment]
Gotcha that makes sense. Thanks

**Comment by seafr** [comment]
You are welcome @nagano564

**Comment by nagano564** [comment]
Sorry I have been mia. When trying to complete these two step

Make a copy of db/schema.rb.example and place it at db/schema.rb.
Make a copy of config/database.yml.sqlite.example and place it at config/database.yml

it states that these files already exists. They don't exist without the `.example` after them. Should I just delete the `.example` portion?

**Comment by nagano564** [comment]
got it up and running local:3000 but i think the regex was an issue again. I changed it to [-[:alnum:].] again and that fixed the warning
