### ISSUE TITLE
Top menu bar: "participate" 

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#237]
Participate is not the standard term we use to describe Getting Involved. We use language like collaborate, contribute, etc. Let's update this.

**Comment by jywarren** [comment]
Prefer "Collaborate" to avoid $-ambiguity?

**Comment by ebarry** [comment]
personally i do like "Collaborate", but it's potentially more direct to
just say "Get Involved"
Cut to the chase, so to speak.

@steviepubliclab what do you think?

--

txt only: +1 336-269-1539
@lizbarry <http://twitter.com/lizbarry>

**Comment by steviepubliclab** [comment]
I prefer "get involved"

**Comment by ebarry** [comment]
ok, Get Involved is the leading choice -- does anyone have any objections
before we move on this tomorrow?

--

txt only: +1 336-269-1539
@lizbarry <http://twitter.com/lizbarry>

**Comment by btbonval** [comment]
what if I'm afraid of commitment? I'd never click "Get involved": it's scary!
/peanutgallery
/pun
/nothelpful

**Comment by ebarry** [comment]
;) any actual suggestions from the /peanutgallery ?

--

txt only: +1 336-269-1539
@lizbarry <http://twitter.com/lizbarry>

**Comment by btbonval** [comment]
I'm a little concerned about screen space, and "Get Involved" is a little longer than "Participate". However, I like it as a concept.

Being involved is a lot more generic than participate. Like, "being involved" could be wearing the colors and cheering on the team, while "participating" means putting on the colors and getting all muddy with some sportsball.

**Comment by ebarry** [comment]
Ok, there's general agreement on the term Get Involved. Can someone put it onto a test version of our site to see if it fits?

**Comment by ebarry** [comment]
This issue could be viewed as time-sensitive if we want to take advantage of the opportunity to have our printed and web materials align. If this is not so important, then it's not so time sensitive.

**Comment by jywarren** [comment]
I checked and "Get Involved" fits - want me to make that change now?

**Comment by ebarry** [comment]
yes please.

--

txt only: +1 336-269-1539
@lizbarry <http://twitter.com/lizbarry>
