### ISSUE TITLE
menubar search "prompt" popover does not disappear

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2372]
### Please describe the problem (or idea)

The menubar search "prompt" popover sometimes doesn't go away when you type in Chrome desktop:

<img width="305" alt="screen shot 2018-02-20 at 4 17 56 pm" src="https://user-images.githubusercontent.com/24359/36432359-06d00d62-1628-11e8-9da9-0d5b2d1ed67a.png">

### Please show us where to look

https://publiclab.org/ (any page, top menubar)

That line of code is here: https://github.com/publiclab/plots2/blob/313848ae70baf221ce092870090f94088040b4a6/app/views/layouts/_header.html.erb#L74

@namangupta01 i think this was a change you made? Would you mind taking a look? I also found this to be the case on Firefox iOS (although that's harder to test out)

**Comment by ViditChitkara** [comment]
Hi @jywarren! I have provided a fix in #2288. Please have a look!
