### ISSUE TITLE
PLANNING ISSUE:Facebook Authentication

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2388]
Planning issues for #683 
* [x] Add omniauth gem
* [x] Add omniauth-facebook gem
* [x] Add fiagro gem
* [x] Define routes
* [x] Add OmniAuth Configuration to initializer
* [x] Install Openssl
* [x] Add OmniAuth Capability to User Model
* [x] User_session_controller update
* [ ] Views update for login
* [ ] Views update for sign in
* [ ] Write tests for the login through fb
* [x] Write Documentation for the fiagro gem
* [x] Write Documentation for omniauth 
* [x] Write Documentaion for the omniauth-facebook
* [x] Write Documentaion for openssl

**Comment by jywarren** [comment]
This is awesome!!! 👍 👍 👍 @ebarry 

What is the minimum chunk of this we could do in a single PR? Perhaps the gems, plus OmniAuth in initializer and user model, and routes, but not changing the existing login sequence or views YET. What do you think? All the back-end stuff.

**Comment by jywarren** [comment]
Sorry, i don't mean put it all back into one big PR. Just that we can do some things that don't affect current workflows (like login, signup) and merge them in with tests, and know that they work well. Then in a followup PR we can start "Turning it on" for people logging into the site for real -- exposing the back-end work. Does this make sense?

**Comment by jywarren** [comment]
Like, we could potentially enable this for login first, but not for signup. That would let us test this progressively in chunks.

One question is -- will existing users be able to log in with Facebook to their pre-existing accounts? Just wondering. 

Thanks so much!

**Comment by SidharthBansal** [comment]
Sorry I could not do much last two weeks due to my mid sems.
Yeah, we will be doing this into chunks of separate prs so that it will be a quick, easy and a small merge.

**Comment by SidharthBansal** [comment]
Regarding the tests. I think we will be able to write them at the end of the full functioning of login and signup

**Comment by SidharthBansal** [comment]
First of all, I will make a simple facebook login compatible with the current publiclab.org
Then I shall add functionality so that the users who have the facebook account or the login on public labs directly can fetch their same profile in either way around.
I hope this makes sense.

**Comment by SidharthBansal** [comment]
``` Then in a followup PR we can start "Turning it on" for people logging into the site for real -- exposing the back-end work ```
Yeah first of all we will test all the functionality on the local then on production, then we will make the frontend so that new users will be able to start logging in from there.

**Comment by jywarren** [comment]
fantastic, and welcome back! Hope your exams went well and very glad to see
you!

**Comment by SidharthBansal** [comment]
Yeah

**Comment by jywarren** [comment]
Just noting I think we could add some unit tests possibly after ` Add OmniAuth Capability to User Model` -- what do you think? 

Love this!

**Comment by SidharthBansal** [comment]
@jywarren one important thing I like to discuss which is written in my proposal. If we have a direct sign up page we will run into many errors. I have updated my proposal a lot. Please reveiw it. There are many reasons why a simple sign up directly through the provider can lead to unfavourable situations. I have listed all of them at https://www.publiclab.org/notes/bansal_sidharth2996/02-20-2018/gsoc-proposal-oauth-authentication

**Comment by SidharthBansal** [comment]
If a user is able to directly sign up through a provider and then he deletes his provider account then he will not be able to access his public lab account. Also, twitter is not providing us the email addresses, so we can't directly write all stuff into the user model. Other reason is if two providers give you same uid then there would be a conflict hard to resolve. There are many other issues which I have encountered. If the public lab would not have any login in the past then it would be much simpler. But that is not the case. We already have a lot of usernames flushed into the production database so there are potential chances of conflicts of the usernames given by the provider and already present in the data base. 
So, I came up at only one solution that is to make identities which are associated with the user model. A user has many identities. An identity belongs to a user. An identity holds information of the provider. So, no need to worry about all the erroreneous situations. Main problem comes with sign in through provider. We can have that for linking the user account with identities after the person is logged in. Then the person can log in directly to the public labs via provider. This implementation lacks the direct sign up through the providers just to minimise the fallout. Although, if you wish sign up we can make that too but then we need to think how to resolve all the problems.

**Comment by SidharthBansal** [comment]
Also, I will like to mention that there is not a fixed solution to multi party login system . we can have multi party login (that does not have any problem ) but multi party sign up have many issues. Just we can discuss and adopt the strategy which is best over the rest.

I have gone through many websites which already have sign up through multiple providers. Yes, they do suffer from the anomalies which I have list above/ proposal. So, I don't want that those will happen here. Eg. At codechef.com you can login through fb and then unlink your fb account. That will result in an account present in the database but not accessible by anyone. Because the user has destroyed the identity through which he signs up to his account.

**Comment by SidharthBansal** [comment]
Also, I will like to tell that the integration part needs to be implemented simultaneously through out the project. We could not have integration at the last stage for multi party authentication

**Comment by SidharthBansal** [comment]
The user will have to first sign up through our legacy sign up form(which I have called as registration form at many places) (available at pl.org/signup) and then link the different providers(aka identities) to his user account(aka user model).

**Comment by jywarren** [comment]
Hi, all - in relation to @SidharthBansal 's [proposal and discussion](https://publiclab.org/notes/bansal_sidharth2996/02-20-2018/gsoc-proposal-oauth-authentication) of "without a password" state, check out these two lines in the login sequence, which redirect to ask someone to create a password!

https://github.com/publiclab/plots2/blob/77e0c16d623c53980eb691bff2eee34103d87854/app/controllers/user_sessions_controller.rb#L34

**Comment by SidharthBansal** [comment]
Moved to #2676 as code is highly interdependent and interlinked for different providers.
