### ISSUE TITLE
Cache impressions for optimizing SQL query

### ISSUE THREAD

**Issue by icarito** [publiclab/plots2#2389]
### Please describe the problem (or idea)

We are noticing that there's a query taking a lot of time and it could be causing small outages by consuming available threads.
The query is `publiclab@172.18.0.1: SELECT COUNT(*) FROM impressions WHERE impressions.impressionable_id = :int AND impressions.impressionable_type = :string` 

The suggestion by @jywarren is to **Optimize impressionist counts with a cache**:

- wrap this line in cache block: 
https://github.com/publiclab/plots2/blob/58bb6010e28d91106556b2cf07c9a100e3324c46/app/models/node.rb#L133

- example cache block that'll need a new "name":
https://github.com/publiclab/plots2/blob/245d6bc11383d220101f098d25b3843ce59e4c7d/app/views/home/home.html.erb#L133-L135

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by James-N-M** [comment]
@icarito Hi I'd like to try taking on this issue, seeing is its an fto-canditate may you provideo more information and code links so i can accomplish this first timer task.

**Comment by icarito** [comment]
I've updated http://tycho.media.mit.edu/logs/mysql-slow.html to reflect the last 4 days. We just had a several-minutes-long downtime, so we may have to prioritize this.

**Comment by James-N-M** [comment]
@icarito I also don't know to much about cacheing and might not have the time to do the research with midterms, might have to pass this issue off seeing its a priority @icarito Thanks though !!

**Comment by icarito** [comment]
Your help is welcome anytime!

**Comment by jywarren** [comment]
I'm going to take a crack at this one in #2459 -- hope it works!
