### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by arungoel123456** [publiclab/plots2#2392]
### Please describe the problem (or idea)
for the first timers.... when we are following the steps as mensioned on your github ... some steps are not working fine like rake db:setup , bower install etc.   .... after skipping the optional steps , when wwe started the local host ,  a sql error is coming . 
> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?
arun
![screenshot from 2018-02-23 19-03-20](https://user-images.githubusercontent.com/31837154/36631130-51beb378-1998-11e8-9b4a-cf936429566f.png)

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by namangupta01** [comment]
Hey @arungoel123456 Have you ran the command `rake db:migrate` because the error is clearly saying that no such table exist.

**Comment by James-N-M** [comment]
hey @arungoel123456 ive had to reinstall a couple times in the past couple weeks lol so I can help you out over a google hangout or something step by step, Im in detroit michigans time zone , but click my github and send me an email

**Comment by Gauravano** [comment]
hi, @arungoel123456 . Is this installation issue resolved? Please ask if the issue still persists, we would be happy to help.Thanks !!!

**Comment by jywarren** [comment]
Hi, I'm going to close this but please reopen if it happens again!!! Thanks!
