### ISSUE TITLE
Tags lead to Error Page

### ISSUE THREAD

**Issue by bronwen9** [publiclab/plots2#2393]
When I clicked on the tag for "gowanus", I am directed to an error page (also true for "gowanus-canal" "newtown-creek" tags, but not others)

![gowanuserror](https://user-images.githubusercontent.com/8331717/36632670-0efc6378-1957-11e8-9729-a3a445a2317d.gif)

**Comment by jywarren** [comment]
Ah, this is bad! A new-ish bug. Not all tag pages error:

https://publiclab.org/tag/spectrometry works

https://publiclab.org/tag/gowanus does not. 

Anyone in @publiclab/reviewers interested in taking this up? Else I can -- thanks @bronwen9 for finding this!

If we can also file a test to reproduce this, that'd be great too.

**Comment by jywarren** [comment]
It looks like the error is here:

```
Completed 500 Internal Server Error in 291ms (ActiveRecord: 62.5ms)

ActionView::Template::Error (undefined method `length' for nil:NilClass):
    18:       <% else %>
    19:         <h1><%= @wiki.latest.title %></h1>
    20:         <p><%= @wiki.latest.render_body.html_safe.match(/<p>(.+)<\/p>/).to_a.try(:first).to_s.html_safe %></p>
    21:         <p><%= link_to("Learn more on the wiki page", "/wiki/#{params[:id]}") if @wiki.latest.render_body.html_safe.match(/<p>(.+)<\/p>/).length > 1 %></p>
    22:       <% end %>
    23:     </div>
    24:   <% elsif @wildcard %>
  app/views/tag/show.html.erb:21:in `_app_views_tag_show_html_erb__3599211229297965767_53189260'
  app/controllers/tag_controller.rb:124:in `block (2 levels) in show'
  app/controllers/tag_controller.rb:123:in `show'
```

So specifically: `@wiki.latest.render_body.html_safe.match(/<p>(.+)<\/p>/).length` in this page:

https://github.com/publiclab/plots2/blob/14d9f92c06fe1b26ae7b3292b751c3d263a204e1/app/views/tag/show.html.erb#L20

I'm posting a first-timers issue to resolve this!

**Comment by jywarren** [comment]
See #2402 to fix this!

**Comment by jywarren** [comment]
Thanks, Bronwen!
