### ISSUE TITLE
Views of a post cannot be seen on small screens

### ISSUE THREAD

**Issue by Souravirus** [publiclab/plots2#2397]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### What did you expect to see that you didn't?
Views of a post and number of comments cannot be seen on small screens

![croppenscreen](https://user-images.githubusercontent.com/17192149/36661212-bd57f536-1b00-11e8-9c28-7dc9a2b6a5d6.png)

![croppedscreen2](https://user-images.githubusercontent.com/17192149/36661321-f4b44f66-1b00-11e8-8ba3-3d5b32d5a796.png)

Whereas in big screens in the same page views can be seen

Same pages can be seen as:

![croppedscreen5](https://user-images.githubusercontent.com/17192149/36662437-6d1ea41c-1b04-11e8-8fc8-0b4da99440ad.png)

![croppedscreen4](https://user-images.githubusercontent.com/17192149/36662080-46047b1e-1b03-11e8-9e87-b6fa76fb2125.png)

### Please show us where to look
https://publiclab.org/dashboard
https://publiclab.org/notes/programmer1200/02-24-2018/atomic-emission-spectrum-website-to-pdf

### What's your PublicLab.org username?
souravirus

### Browser, version, and operating system
Browser: Google chrome
Operating System: Android Lollipop

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
A lot of things are hidden on smaller screens. Do you think we could
re-show them using a `...` button but keep them hidden by default? Good
thinking!

**Comment by Souravirus** [comment]
Yeah we can do that @jywarren

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.
