### ISSUE TITLE
barnstar giver should get comment email notifications

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#240]
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted issues](https://github.com/publiclab/plots2/labels/help-wanted). Thanks!

## The problem

[Barnstars](https://publiclab.org/wiki/barnstars), which may be given using the "like" dropdown as shown below, are awards given by one logged-in community member to another on [PublicLab.org research notes](https://publiclab.org/research) (login required to see barnstar interface):

![screenshot 2016-03-16 at 3 37 48 pm](https://cloud.githubusercontent.com/assets/24359/13826294/1118d870-eb8d-11e5-8e11-056d4372606f.png)

But sometimes you give a barnstar but you don't get subscribed to updates on that post, as commenters do.

## Possible solution

This is a bit harder to test because email notifications happen behind the scenes , but the easiest way to do it would be for the RSVP action in notes_controller.rb to actually create a comment with text like "Awards a barnstar to X", which would subscribe the awarder to notifications because all commenters get notifications. For this, you could use code similar to the RSVP code here:

https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb#L253-L262

Then you can just rely on the comment emailer to take care of it. The barnstar awarding code is here:

https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L63

### Steps to fix

* [x] claim this issue with a comment
* [ ] set up a repository locally and make sure that all tests pass
* [ ] start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress"
* [ ] fix the issue following the steps above
* [ ] make sure all tests pass
* [ ] alert someone via either the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by Goldtean** [comment]
Going to be taking a look at this today with @matrharr

**Comment by jywarren** [comment]
Fantastic! Thank you and please ask if you have questions or need tips on existing code organization!

**Comment by Goldtean** [comment]
Got this issue: An error occurred while installing libv8 (3.16.14.13), and Bundler cannot
continue. Tried installing v8, uninstalled and installed again, tried installing python, uninstalled and installed again and libv8 still won't bundle install.

**Comment by jywarren** [comment]
Hi, Jeremy - can you post the entire error as a [Gist](
https://gist.github.com) and share the link so we can see some more
contextual info? Thanks!

**Comment by chongr** [comment]
going to start this today, it looks like it is still unresolved

**Comment by jywarren** [comment]
Ah, completed in #601! Forgot to close it here -- thanks @chongr !

**Comment by ebarry** [comment]
Hi @chongr! Thank you again for your valuable contribution to Public Lab. I would like to invite you to join us in a video conference to say a few words about what you contributed and how your experience was. The event is https://publiclab.org/openhour, and it’s coming right up on November 7th, at 1pm EDT which is UTC/GMT -4. 

Please feel free to respond here, or else email liz@publiclab.org, stevie@publiclab.org, jeff@publiclab.org.
