### ISSUE TITLE
Display Questions prompt on dashboard

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2401]
Our dashboard is really nice:

http://publiclab.org/dashboard

But it doesn't feature our Questions system!

See the front page for how this can be highlighted:

https://publiclab.org/home

![image](https://user-images.githubusercontent.com/24359/36683810-9373083c-1aec-11e8-87f0-8a7de882ca97.png)

Let's put that code, which is here:

https://github.com/publiclab/plots2/blob/14d9f92c06fe1b26ae7b3292b751c3d263a204e1/app/views/home/home.html.erb#L44-L48

Onto the dashboard sidebar, here on line 2:

https://github.com/publiclab/plots2/blob/14d9f92c06fe1b26ae7b3292b751c3d263a204e1/app/views/dashboard/_sidebar.html.erb#L1-L5

We can use a Bootstrap "panel" there:

https://getbootstrap.com/docs/3.3/components/#panels

![image](https://user-images.githubusercontent.com/24359/36683907-dc689f0c-1aec-11e8-81bc-8bb73b530784.png)

**Comment by amitsin6h** [comment]
@jywarren want to take this

**Comment by jywarren** [comment]
That'd be great, thanks @amitsin6h ! We'd love it if you'd help out here.

**Comment by MittalS211** [comment]
@amitsin6h  if you need any help solving this, please let me know!

**Comment by amitsin6h** [comment]
@jywarren Please look at the PR #2431 , but I don't understand why my PR has conflict.
