### ISSUE TITLE
Email recieved of an Unpublished node . 

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#2408]
### Please describe the problem (or idea)

When a first time contributor on `publiclab.org` publishes a note , it has to be approved by the PublicLab moderators before it can appear to everyone . However an email is send to people who are subscribed to the TAGS that the note contain . 
On opening the link of note , we are redirected to the Dashboard .

### Solution

The email should be send to people after it gets approved by the maintainers .  

### What's your PublicLab.org username?

sagarpreet

**Comment by Gauravano** [comment]
I have faced this too, @sagarpreet-chadha are you solving this or Can I?

**Comment by sagarpreet-chadha** [comment]
Hi ! Go Ahead 😄  !
I am a little busy with my Exams right now :)
Thanks 👍 !

**Comment by Gauravano** [comment]
Best of luck with your exams !!!

**Comment by ebarry** [comment]
Oh wow, thanks for documenting this, i actually hadn't noticed this was happening. Anyone have any ideas about this?

**Comment by Gauravano** [comment]
Yes, this issue came to attention when new users are submitting their first research note(GSoC proposal). I also have to fix this for draft feature, so I am working on it now.
