### ISSUE TITLE
Prevent auto-tagging of numerical inline tags like #1234

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2426]
Needs more info! Soon, thanks!

https://github.com/publiclab/plots2/blob/2d43c7d908dd8b65d3ca7681cc35a107770e0f20/app/models/revision.rb#L43-L48

https://github.com/publiclab/plots2/blob/2d43c7d908dd8b65d3ca7681cc35a107770e0f20/config/initializers/constants.rb#L1-L11

**Comment by jywarren** [comment]
@Gauravano maybe you could help flesh this out -- do you know what I'm talking about here? :-)

**Comment by Gauravano** [comment]
I guess here we want to stop tagging string like # 12322, like in many proposals, issues and PR's are mentioned and due to which tags have been created, we have to prevent that.Am I right?

**Comment by jywarren** [comment]
yep, that's right! It's pretty annoying, but should be a simple fix. We can
use Rubular.com to prototype!

**Comment by Gauravano** [comment]
hi @jywarren , I just dig into this a little and found that we have tests set up to ensure the creation of these tags so if we don't need this tag creation feature anymore I would do the cleanup. What do you say?

**Comment by jywarren** [comment]
ah, well we want to keep tagging, just not for purely numerical strings,
right?

**Comment by Gauravano** [comment]
ok I will optimize it accordingly

**Comment by jywarren** [comment]
awesome!!! Thanks!!
