### ISSUE TITLE
Feature SkyTruth Alerts map as a layer in Leaflet profile map

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2427]
We have a small map that appears on some profile pages like: http://publiclab.org/profile/nshapiro

We should create a Leaflet map layer that can be disabled, showing nearby SkyTruth Alerts; see:

* [x] create a new layer that can be enabled/disabled with http://leafletjs.com/examples/layers-control/
* [x] add a custom icon with http://leafletjs.com/examples/custom-icons/
* [x] make new markers with `L.marker([51.5, -0.09], {icon: greenIcon}).addTo(map).bindPopup("I am a green leaf.");`

Example JSON file for a longitude/latitude box: http://alerts.skytruth.org/json?&d=30&channel=local&l=41.545%2C-71.8331%2C41.8782%2C-71.3524

Here's a broader area: http://alerts.skytruth.org/json?&d=30&channel=local&l=41.042%2C-72.554%2C42.3747%2C-70.6314

Each alert has a good description that could be shown in a popup, with a link to more information:

```json
{ "feed":[
{
    "id": "4cb6a3cf-7db5-314a-9340-ebe44628fdc1",
    "source": "1",
    "title": "NRC Report: Caustic Gas near Cranston, RI",
    "link": "http://alerts.skytruth.org/report/4cb6a3cf-7db5-314a-9340-ebe44628fdc1",
    "description": "<b>Report Details<\/b><br\/>NRC Report ID: <a href=\"http:\/\/nrc.uscg.mil\/\">1203212<\/a><br\/>Incident Time: 2018-01-29 04:30:00<br\/>Nearest City: Cranston, RI<br\/>Location: 1420 ELMWOOD AVE<br\/>Incident Type: FIXED<br\/>Material: CAUSTIC GAS<br\/>Medium Affected: LAND<br\/>Suspected Responsible Party: <br\/><b>SkyTruth Analysis<\/b><br\/>Lat\/Long: 41.770898, -71.422979 (Approximated from premise)<br\/><b>Report Description<\/b><br\/>CALLER STATED THERE WAS A RELEASE OF CAUSTIC GAS FROM A BUILDING DUE TO A SMALL FIRE. CALLER ALSO STATED THERE WERE ADDITIONAL UNKNOWN CHEMICALS THAT WERE RELEASED. CALLER STATED THE REASON FOR THE RELEASE IS UNKNOWN AT THIS TIME. CALLER STATED THIS IS A PLATING COMPANY.<p><a href=\"http:\/\/alerts.skytruth.org\/report\/4cb6a3cf-7db5-314a-9340-ebe44628fdc1\" target=\"_top\">View Full Report<\/a><\/p>",
    "lat": "41.7708981",
    "lng": "-71.4229789",
    "published": "2018-02-14 05:50:22.009",
    "updated": "2018-02-14 05:50:22.009",
    "incident_datetime": "2018-01-29 04:30:00"    
}

]
}
```

The code for the user profile map is here: 

https://github.com/publiclab/plots2/blob/2d43c7d908dd8b65d3ca7681cc35a107770e0f20/app/views/map/_userLeaflet.html.erb#L8-L12

Let's be sure to highlight SkyTruth Alerts in the map key! http://alerts.skytruth.org

**Comment by sagarpreet-chadha** [comment]
Hi @jywarren , this is pretty amazing idea . Can i work on this ?
However , i can send a PR only after Thursday . 

One doubt : do we have to add any UserTag to enable/disable the layer ? Thanks

**Comment by jywarren** [comment]
I think we could have the layer just be enabled/disabled each time in
JavaScript, for starters. We can build this out later with more features!

I'm also thinking that we'll want people to have the ability to expand the
profile map to make it more useful, to access more features. But that can
also be a follow-up.

Thanks! This'd be great!

On Fri, Mar 2, 2018 at 12:50 PM, Sagarpreet Chadha <notifications@github.com

**Comment by sagarpreet-chadha** [comment]
Hi @jywarren ...should we **remove** the Layer button and/or full-screen button if we visit someone's else profile ? What do you think ?
