### ISSUE TITLE
Minor changes for Social media icons on profile page

### ISSUE THREAD

**Issue by Gauravano** [publiclab/plots2#2428]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

![removalicon](https://user-images.githubusercontent.com/20878070/36934190-d3ee603c-1f0b-11e8-8852-ae5f1fe88505.png)

Our Profile page needs some minor CSS fixes. Remove hover effects so that on hovering over social media icons, the black line doesn't generate.Instead, add the hover effect to enlarge social media icon on hover.And add the margin between each icon.   

File that needs changes - https://github.com/publiclab/plots2/blob/master/app/views/users/profile.html.erb

Thank you!!

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/users/profile.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/users/profile.html.erb) in the `plots2` repository so as to do the required changes.

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by son-vyas** [comment]
I would like to give this a try. Thanks @Gauravano

**Comment by Gauravano** [comment]
That would be great !!!

**Comment by Paarmita** [comment]
@Gauravano Can I take up this issue?

**Comment by namangupta01** [comment]
@Paarmita Sure, Go ahead!

**Comment by Paarmita** [comment]
@Gauravano Do I have to add social icons and then css? As icons are not shown 
![screenshot from 2018-03-12 19-08-08](https://user-images.githubusercontent.com/26546816/37286746-d8eabb16-2628-11e8-9bda-5221af0caaf0.png)

**Comment by Gauravano** [comment]
hi @Paarmita , you have to enter your facebook, twitter, etc username using Link social media button, and then icons would appear.

**Comment by Paarmita** [comment]
@Gauravano on clicking the Link social media button, it's not taking the username and accounts are not linking.
![screenshot from 2018-03-13 21-37-20](https://user-images.githubusercontent.com/26546816/37354062-c12a5084-2706-11e8-96a5-409a7cd79d73.png)

**Comment by Gauravano** [comment]
@Paarmita you have to follow the syntax as shown in the alert like if you want to add your facebook username on PublicLab then you need to add facebook:paarmita287 and similar syntax for twitter, instagram, and github.

**Comment by namanjain1812** [comment]
Can i take this issue?

**Comment by Gauravano** [comment]
### Update in the issue:

First, add class to the div at line https://github.com/publiclab/plots2/blob/master/app/views/users/profile.html.erb#L9 like this 

```diff
-     <div style="text-align: center;">
+    <div class="profile_icons" style="text-align: center;">
```

and then append following CSS 
```ruby

  .profile_icons a{
    text-decoration: none;
  }

  i{
    margin-left: 8px;
  }

  i:hover{
    transition-duration: .2s;
    transform: scale(1.2);
  }

```
here https://github.com/publiclab/plots2/blob/master/app/views/users/profile.html.erb#L283-L287

**Comment by chanjess** [comment]
@Gauravano Hi Gauravano, open source newbie here. There aren't many first timer requests. Are there any upcoming ones I can help out on? Thanks!

**Comment by CoderJolly** [comment]
anybody working on dis?

**Comment by Gauravano** [comment]
Hi @CoderJolly, this issue is solved. Sorry for inconvenience.
