### ISSUE TITLE
Social media icons should link to latest entered username

### ISSUE THREAD

**Issue by Gauravano** [publiclab/plots2#2429]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

Currently, when a user adds new username for existing facebook or any social media account, both tags are stored but icons link to the old one instead of linking to the new one as the user may intend to update it.

Add a function in https://github.com/publiclab/plots2/blob/master/app/models/user.rb something like this - 
`def get_value_of_power_tag_for_social_profile(key)
    tname = self.user_tags.where('value LIKE ?' , key + ':%')
    tvalue = tname.last.name.partition(':').last
    tvalue
  end
`
And, change this line https://github.com/publiclab/plots2/blob/2d43c7d908dd8b65d3ca7681cc35a107770e0f20/app/models/user.rb#L330 
to   ` user_name = get_value_of_power_tag_for_social_profile(site)`

Thank you!!

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/models/user.rb](https://github.com/publiclab/plots2/blob/2d43c7d908dd8b65d3ca7681cc35a107770e0f20/app/models/user.rb) in the `plots2` repository so as to do the required changes.

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by Gauravano** [comment]
Awesome !!!

**Comment by BornToWin** [comment]
Can I still try this one if there is already someone working on it? Thanks.

**Comment by nyattisaias** [comment]
Is it too late to give this a try @Gauravano?

**Comment by Gauravano** [comment]
hi @nyattisaias we would love to have your help but for this one PR is opened in #2430 . But, you can new first-timer issues at https://publiclab.github.io/community-toolbox/#r=all .If you were not able to find any, feel free to ping here I'll open a new one for you.Thanks !!!

**Comment by namanjain1812** [comment]
Is someone working on it.If not I would like to work on it

**Comment by namanjain1812** [comment]
@Gauravano Since i saw no pull requests i have made the changes.Please merge it now
Thanks.

**Comment by poppashingles** [comment]
Hi @Gauravano, I was just wondering if there would be any new first-timers issues set up soon? I'd really like to have a go at one. Thanks for this site though, it's awesome. Definitely the best resource I've seen for newcomers like myself to open source contributions

**Comment by Gauravano** [comment]
Will open a new one in some hours, thanks.

Gaurav Sachdeva

**Comment by Gauravano** [comment]
hi @poppashingles , I am just waiting for @jywarren 's input on some issues and then open them as FTO ,till then please try the link. Thanks.

**Comment by poppashingles** [comment]
Hi @Gauravano, that's great thank you. I'll have another look through the candidates section and see if I can get anywhere there

**Comment by Gauravano** [comment]
Awesome !!!
