### ISSUE TITLE
Page for Barnraising Session Proposals shows error. 

### ISSUE THREAD

**Issue by bronwen9** [publiclab/plots2#2436]
I was navigating to this page to moderate a spam comment after getting an email alert:

https://publiclab.org/questions/warren/10-27-2017/what-sessions-would-people-like-to-have-at-the-2017-barnraising

but when I clicked on the link I found the error page instead.

**Comment by ebarry** [comment]
I believe i just encountered this same bug -- the URL to a question that received a spam comment broke

LINK: https://publiclab.org/questions/warren/11-14-2017/what-s-one-thing-that-could-be-better-for-newcomers-about-the-public-lab-website

I made a gif out of clicking the link, finding the error page, and checking that i took the "answer suffix" off of the URL -- even so, the original content seems to have a broken URL:

![url-bug](https://user-images.githubusercontent.com/161439/37046584-b54b5e78-2136-11e8-8139-2ca347488421.gif)

**Comment by Gauravano** [comment]
hi, @ebarry @bronwen9 I guess this issue is related to #2449 . What do you think?

**Comment by ebarry** [comment]
Oh my gosh, yes it is!!!! thank you for sleuthing!!! This would be a very serious bug if so! 😳

**Comment by Gauravano** [comment]
Could you write a random answer for https://publiclab.org/notes/gauravano/03-08-2018/this-is-for-testing-purpose for testing purpose?

**Comment by Gauravano** [comment]
I have replicated this with https://publiclab.org/questions/gauravano/03-08-2018/testing-purpose and got the same result, node is deleted.So, yes its serious bug as if any user deletes any answer now, that question would be deleted.

**Comment by bronwen9** [comment]
Wow, yes! That's the trigger. We've been deleting a lot of spam comments lately (we're trying to tamp down on the amount of them in issue #974 ), so this likely affects quite a few pages right now.

**Comment by jywarren** [comment]
OK -- we're going to do a data recovery for these by digging into database backups. Thanks for identifying the issue! Merging into #2449.
