### ISSUE TITLE
Missing comment icon in blog page

### ISSUE THREAD

**Issue by amitsin6h** [publiclab/plots2#2437]
Hi, this is a [first-timers-only](https://publiclab.github.io/community-toolbox/#r=all) issue. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you :gift_heart:

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### :thinking: What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

This will added comment icon in blog page which is not present. For reference I have provided the URL where the issue is and screen-shot below.

**URL** https://publiclab.org/blog

![screenshot from 2018-03-07 19-29-41](https://user-images.githubusercontent.com/12906090/37096206-ed69df5c-223d-11e8-919a-fb545f39f297.png)

### How to solve for new contributors

`<i style="color:#888;" class="fa fa-comment-alt"></i>`

Just replace `alt` with `o` from [app/views/tag/blog.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/tag/blog.html.erb) file in the codebase and this will fix the issue.
 

:clipboard: Step by Step

- [ ] :raising_hand_woman: **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ]     :memo: **Update** the file [app/views/tag/blog.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/tag/blog.html.erb) in the plots2 repository so as to do the required changes.

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

- [ ]  :floppy_disk: **Commit** your changes

- [ ]  :twisted_rightwards_arrows: **Start a Pull Request**. There are two ways how you can start a pull request:

   

1.  If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ]  :checkered_flag: Done Ask in comments for a review :)

### :thinking: :question: Questions?

Leave a comment below!

### Is someone else already working on this?

We **encourage you to link to this issue by mentioning the issue** # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [@amitsin6h](https://publiclab.org/profile/amitsin6h ))

**Comment by Gauravano** [comment]
hi @amitsin6h please see the first-timer-issue template we follow and edit accordingly.For reference see issues #2429 .

**Comment by amitsin6h** [comment]
@Gauravano done. Thanks  :+1:

**Comment by Gauravano** [comment]
Awesome !!!

**Comment by oulongwen** [comment]
I would like to work this issue. Thanks.

**Comment by ViditChitkara** [comment]
That would be great

On Mar 7, 2018 10:04 PM, "oulongwen" <notifications@github.com> wrote:

I would like to work this issue. Thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/2437#issuecomment-371198010>,
or mute the thread

**Comment by amitsin6h** [comment]
@oulongwen great, let me know if you need any help

**Comment by jywarren** [comment]
Hi this is great everyone! @amitsin6h i'll add you to reviewers group if you'd like! :-) 👍

**Comment by amitsin6h** [comment]
@jywarren sure :+1:

**Comment by oulongwen** [comment]
Hi @amitsin6h I submitted my PR and it failed the required tests. Could you please take a look and let me know where I did wrong? Thanks.

**Comment by RajuKalidindi** [comment]
hello @amitsin6h ! I'd like to work on this issue

**Comment by amitsin6h** [comment]
@oulongwen are you working on it or I assign it to @RajuKalidindi

**Comment by oulongwen** [comment]
@amitsin6h I have already submitted a PR #2442 for this issue. Somehow the test would not pass. I am waiting for further guidance on how to fix it. Thanks.

**Comment by amitsin6h** [comment]
Just close the PR that you and try to resubmit you wont face any test
failed.
Go for it

**Comment by oulongwen** [comment]
@amitsin6h The problem has already been solved and all the tests are passed. Thanks for your help.:thumbsup:
