### ISSUE TITLE
Leading dashboard blog post is an old one for some reason

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2443]
### Please describe the problem (or idea)

Our dashboard at http://publiclab.org/dashboard shows a single blog post

It's supposed to be the most recent one from http://publiclab.org/blog

> What did you expect to see that you didn't?

Instead, it's an older post -- https://publiclab.org/notes/Shannon/07-06-2016/public-lab-code-of-conduct

Not sure why! The code to grab this post (that's apparently going wrong) is here:

https://github.com/publiclab/plots2/blob/5ac99163ee3a3ce47a52b3a9ccff0e0bf89aa6a2/app/controllers/home_controller.rb#L91

That goes to these lines, which haven't been touched in months -- so it seems unlikely to be the culprit! 

https://github.com/publiclab/plots2/blame/master/app/models/tag.rb#L85-L104

I'm actually a bit mystified at this. The dashboard ought to show the very first post from https://publiclab.org/blog

****

Aha! That page was recently updated. It looks like we use updating as the ordering. We should switch it to creation for this particular instance:

```
2.3.4 :003 > n.updated_at
 => 2018-03-06 15:24:47 +0000 
```

**Comment by 500swapnil** [comment]
I would like to help with this. Any other background on this bug?

**Comment by jywarren** [comment]
Hi, I think we just occasionally update an old blog post, and that bumps it to the dashboard, which is unintended. If we change the ordering on the lines marked above, this should resolve -- thank you, @500swapnil !!!
