### ISSUE TITLE
Need to add "Ascending" sort for `#of uses` on publiclab.org/tags 

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2445]
Hi! This *might* be a first timers only issue, i'm going to tag it `FTO-candidate`

### Please describe the problem (or idea)

> What problem could this idea solve?

I love the new tag sorting, but i noticed that even though we have the "up-down" arrow icon next to `# of uses`, the sort function only works in one direction. Watch the gif below to see how the `# of uses` is only able to sort the tags in Descending order, demonstrated by attempting to change the sort order after sorting alphabetically by the `tag` column: 

![tag-sorting](https://user-images.githubusercontent.com/161439/37112777-73ddd980-2211-11e8-83c9-eaf2b468a9ee.gif)

> What did you expect to see that you didn't?

I expect to be able to sort in ascending and descending order by `# of uses` and in fact by all columns. 

### Please show us where to look

https://publiclab.org/tags
https://publiclab.org/tags?sort=uses

### What's your PublicLab.org username?

> This can help us diagnose the issue: liz

Thank you!!!!!!

**Comment by jywarren** [comment]
Hi! This will involve changes to the controller on lines like this:

https://github.com/publiclab/plots2/blob/ca820a87e083ed7aff95e6c903732d2d4fca7949/app/controllers/tag_controller.rb#L22

Where we'll want to determine order via a URL parameter, like: 

`https://publiclab.org/tags?sort=uses&order=desc`

We can access the order with the variable `params[:order]` within the controller. So let's indicate order with `params[:order] == "desc"` and then update the template to enable this toggling in the table header code here:

https://github.com/publiclab/plots2/blob/ca820a87e083ed7aff95e6c903732d2d4fca7949/app/views/tag/index.html.erb#L26-L33

We'll want to be able to toggle sorting ascending/descending for each of the columns! Any help appreciated, thanks!!!

**Comment by Gauravano** [comment]
hi @jywarren @ebarry , I guess this issue relates to #2352 .

**Comment by ebarry** [comment]
wow yes, @Gauravano -- thank you for directing my attention at this GREAT PR in progress by @sukhbir-singh !!! It's very exciting. Feel free to close this issue in favor of  #2352 .

**Comment by Gauravano** [comment]
Actually, I have gone through the parts of #2352 and noticed it lacks some things.I would open few FTO issues covering those parts. Also, how about adding sort icon i.e., sorting ASC/DESC to every possible page like wiki, tags, people, etc. so that all pages have the same UI? 
![sorticon](https://user-images.githubusercontent.com/20878070/37299456-5f31d91e-2649-11e8-8c35-9b022edb2fc4.png)

**Comment by sukhbir-singh** [comment]
Hi @ebarry , I think there is a minor typo in description of this issue. The url should look like:-
https://publiclab.org/tags?sort=users instead of https://publiclab.org/tags?sort=uses

**Comment by ebarry** [comment]
oh good catch! But i think the count is of how many times a tag is used, rather than of "users" as in people. What do you think?

**Comment by sukhbir-singh** [comment]
sorry my bad, its "number of uses" not users

**Comment by jywarren** [comment]
Gaurav, agreed. Shaun, please go ahead, that would be great! Thanks!!

>

**Comment by jywarren** [comment]
Completed a while back, thanks!
