### ISSUE TITLE
BUG: adding a tag while drafting a note didn't actually get added to the published note

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2446]
### Please describe the problem

> What happened just before the problem occurred?

I wrote content at publiclab.org/post and used the tag interface to add tags before i clicked publish. I just experienced this three times, but NOT when clicking the "I did this" button -- those replication tags did endure through publishing. 

> What did you expect to see that you didn't?

I expected to see the tags that i added make it into the published note. 

### Please show us where to look

https://publiclab.org/post

### What's your PublicLab.org username?

> This can help us diagnose the issue: liz

**Comment by jywarren** [comment]
Hi, Liz - to clarify, the tags added when you click "I did this" on a post like this: https://publiclab.org/notes/cedarlodge/03-07-2018/raspberry-pi-spectrometer-gui

that button would go to: 

https://publiclab.org/post?tags=replication:15880,spectrometry,raspberry-pi,lego-spectrometer

I wasn't able to reproduce this -- using the link above, i added the additional tag `test` and hit publish:

![screenshot 2018-03-13 at 1 46 41 pm](https://user-images.githubusercontent.com/24359/37359853-09dfcea4-26c5-11e8-80dd-6b052bb944de.png)

Then I saw the post go up with all the "preset" tags plus `test`:

![screenshot 2018-03-13 at 1 46 20 pm](https://user-images.githubusercontent.com/24359/37359880-16954ebc-26c5-11e8-8f30-9fbdff9cccf5.png)

Maybe i'm not following your steps exactly? Is it ONLY when you go to 

http://publiclab.org/post ?

Thanks!

**Comment by jywarren** [comment]
If we can reproduce this, we should be sure to add a test for it -- at:

https://github.com/publiclab/plots2/blob/8e9dec8787158cd504b68ba340557599c61434e4/test/functional/notes_controller_test.rb#L195-L213

**Comment by ebarry** [comment]
Hi Jeff, that's correct -- the "I Did This" button tagging was (and is) working perfectly. :D 
I haven't experienced the bug on https://publiclab.org/post lately and am going to close this issue.
