### ISSUE TITLE
re-license under AGPL and/or adopt a CLA

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#245]
We have +1s from folks in #235 for GPLv3, and are going to now re-license under AGPLv3 as this is a web service. 

https://www.gnu.org/licenses/agpl-3.0.txt

**Comment by jywarren** [comment]
@btbonval - We were waiting for input from brian takata (i think?) but can also rewrite his section (it was a fairly small contribution) if we need to in order to move forward. Shall we do this?

**Comment by btbonval** [comment]
@jywarren Even if you rewrite that section, an argument could be made that the contribution influenced later code that was rewritten. Additionally, any contributor to the git repository will forever be branded as a contributor regardless of the effective result of that contribution.

To say that one person's contributions have been entirely overwritten and thus no longer qualifies that person as an author is a very murky prospect.

Again, I think copyright should be held by Public Lab organization; the license is defined by the copyright holder; contributions are accepted and utilized as per the license. Keeping track of authors is good. Trying to create a rag-tag legal entity cooperative of copyright owners is not.

**Comment by jywarren** [comment]
So you're proposing a CLA, then? We'd have to get everyone to sign and send that, then. Shall we raise this on the organizers list? It seems like a bigger topic that'd need some community buy-in. Are there good non-jargony intros to CLAs that we could share?

**Comment by btbonval** [comment]
I brought this idea up previously when you first brought up having a shared copyright amongst the authors in order to change to GPL. I believe my original sentiment was along the lines of "noble but implausible".

Not really sure what CLA means in this context though.

**Comment by ebarry** [comment]
What does CLA mean?

It's super awesome that this AGPL relicensing is slowly happening.

**Comment by Nataliegurl** [comment]
https://en.wikipedia.org/wiki/Contributor_License_Agreement

**Comment by btbonval** [comment]
Yeah we want that and not a hegemony of copyright holders under a psuedo-democratic decision making process, unless we want to build a constitution that defines quorum such that not all authors need reply, in which case that sounds just like a CLA anyway.

**Comment by jywarren** [comment]
> https://en.wikipedia.org/wiki/Contributor_License_Agreement

Sorry, I left that last comment by replying to email, but replied to the one fwded to our kits@ address, so it used the wrong reply address and mislabeled the author. 

Well, I agree that it'd be easier to manage, but we'd still have to get everyone to sign the CLA. I just don't have much experience with CLAs and don't know enough yet to choose or draft one. I think some bind the copyright-owning entity to a specific license, which would work. Gotta do some research... some resources:

* https://www.apache.org/licenses/icla.txt
* https://fossbazaar.org/content/open-source-contributor-agreements-some-examples/
* https://www.gnu.org/licenses/why-assign.html

Did you want to propose this on the organizers list, or would you like me to?

**Comment by btbonval** [comment]
I remember we had this conversation over some email list previously. Was it not the organizer list? Wouldn't we just bring it up again wherever that was?

Another thing we might want, which I think is hinted at by some of the CLA stuff, is an eligibility waiver. Effectively most software programmers sign work product clauses which are far reaching, and suggest any and all work performed in the domain by the employee (regardless of "personal time") is owned by the company.

I've seen open source software incorporate waivers that must be signed, or something like "By submitting a pull request, you verify that blah blah blah." I recall us having this discussion before, and that contributors must abide by what is written in `CONTRIBUTING.md`, but I don't see anywhere that presently says, "As a developer of sound mind and body, I can contribute freely to this project without burden of a work product clause by my employer." or something.

**Comment by jywarren** [comment]
https://opensource.com/article/19/2/cla-problems

Interesting piece on CLAs.

And, I think the moment has passed for this, for better or worse!
