### ISSUE TITLE
Replace blog link with stories from Read Stories button

### ISSUE THREAD

**Issue by amitsin6h** [publiclab/plots2#2454]
Hi, this is a [first-timers-only](https://publiclab.github.io/community-toolbox/#r=all) issue. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you :gift_heart:

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### :thinking: What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

This will add _stories link_ to the **Read Stories Button**, currently the **Read Stories Button** is taking user to the blog page rather then the stories page. For reference I have provided the URL where the issue is and screen-shot below.

**URL** https://publiclab.org/home

![screenshot from 2018-03-09 19-16-51](https://user-images.githubusercontent.com/12906090/37210412-a441b560-23ce-11e8-8dfa-234d2a0b5b98.png)

### How to solve for new contributors

`<p><a href="/blog" class="btn btn-primary btn-lg">Read stories &raquo;</a></p>`

Just replace `/blog` with `/wiki/stories` from [app/views/home/home.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/home/home.html.erb) file in the codebase and this will fix the issue.
 

:clipboard: Step by Step

- [ ] :raising_hand_woman: **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ]     :memo: **Update** the file [app/views/home/home.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/home/home.html.erb) in the plots2 repository so as to do the required changes.

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

- [ ]  :floppy_disk: **Commit** your changes

- [ ]  :twisted_rightwards_arrows: **Start a Pull Request**. There are two ways how you can start a pull request:

   

1.  If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ]  :checkered_flag: Done Ask in comments for a review :)

### :thinking: :question: Questions?

Leave a comment below!

### Is someone else already working on this?

We **encourage you to link to this issue by mentioning the issue** # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [@amitsin6h](https://publiclab.org/profile/amitsin6h ))

**Comment by chitra591** [comment]
Hey @amitsin6h , Can I work on this?

**Comment by amitsin6h** [comment]
@mirzabob do you want to work ?? or I will assign it to @chitra591

**Comment by mirzabob** [comment]
yeah i want to work on it.

**Comment by mirzabob** [comment]
Hello @amitsin6h I worked it but it's giving a wrong tick again.

**Comment by amitsin6h** [comment]
@mirzabob didn't get you

**Comment by amitsin6h** [comment]
@chitra591 I will create an another issue for you to work on, also visit https://publiclab.github.io/community-toolbox/#r=all

**Comment by mirzabob** [comment]
![screenshot from 2018-03-09 21-27-34](https://user-images.githubusercontent.com/35152568/37216585-224c2cc6-23e1-11e8-8e02-becb0a37a32b.png)
@amitsin6h  This is the problem i am facing.

**Comment by amitsin6h** [comment]
@mirzabob first close your PR which you made for the comment icon because your changes for this issue is reflecting in the first PR that you made. 

I suggest you remake PR for this issue.  and also go through the git basics https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github also see the git work flow https://guides.github.com/introduction/flow/index.html.

and when you write you commit message also mention which issue the PR fixes. 
For eg. Updated Read Stories button link (Fixes #issue-number)

**Comment by jywarren** [comment]
I just added a new one at #2458 !! @chitra591

**Comment by chitra591** [comment]
I think that is issue is also fixed! Anyways, Thanks @jywarren !

**Comment by seafr** [comment]
@amitsin6h Please see [my comment](https://github.com/publiclab/plots2/pull/2484#discussion_r174107176). A test may be needed here.

I also suggest you create FTO issues using the [first-timers-bot](https://github.com/hoodiehq/first-timers-bot) as it also displays a helpful "diff" showing which line to add/remove.

**Comment by amitsin6h** [comment]
@seafr I was not aware about first-timers-bot thanks for your help. I have seen your comment , I have asked @mirzabob to make the changes.

**Comment by amitsin6h** [comment]
Fixed and Merged #2484
