### ISSUE TITLE
Offer templates in sidebar of new wiki page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2469]
We have great templates available for wiki pages: https://publiclab.org/wiki/wiki-templates

They can be used using URLs like: `http://publiclab.org/wiki/new?n=1234` where 1234 is the template node id.

Node id at which particular template exist can be found at https://publiclab.org/wiki/wiki-templates by clicking on the button which creates those template. 

We should offer the main ones on the new wiki page form -- for example, if you're logged in:

https://publiclab.org/wiki/nonexistent-page

![image](https://user-images.githubusercontent.com/24359/37231416-24fc2da4-23b9-11e8-85fa-5348249fd110.png)

the template for that is here: 

https://github.com/publiclab/plots2/blob/75db6c9d9b1c02b9ea7e30191ee886b672f966db/app/views/wiki/edit.html.erb#L3-L12

The excerpted section (showing "related") is already only shown when it's being displayed for new wiki pages. So it's a perfect place to put a few links. Maybe something like:

****

### Templates

Use these to start a page from [one of these templates](https://publiclab.org/wiki/wiki-templates):

* [Method template lite]()
* [Method template]()

****

Clicking the link would go to the same URL as you're currently on, but with `?n=_____` appended!

**Comment by Ronaq13** [comment]
I want to take this up.

**Comment by Gauravano** [comment]
That's Great !!!. You can ask here if you want any help.Thanks.

**Comment by jywarren** [comment]
Hi @Ronaq13 - if you do, please link back here from your pull request so we know you've gotten started. Thanks!!!

**Comment by Ronaq13** [comment]
I am working on it. Will send a pull request in a while

**Comment by jywarren** [comment]
:-) awesome!

**Comment by Ronaq13** [comment]
I was working on this. And after i gave a command to pull the latest changes form publiclab/plot2 , now I am facing an error:

`NoMethodError: undefined method `<' for nil:NilClass
  /home/raounak/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/definition.rb:333:in `lock'`

Can anyone help in this?

**Comment by ViditChitkara** [comment]
This happened with me before too! I'm not sure if it will work,but if you could remove the gemfile.lock file. After that run 'bundle install'. Seems to be some dependency related issue.

**Comment by Ronaq13** [comment]
rake db:setup giving an error:

`ActiveRecord::StatementInvalid: SQLite3::SQLException: near "fulltext": syntax error: CREATE fulltext INDEX "index_comments_on_comment" ON "comments" ("comment")
/home/raounak/Desktop/openSource/publiclab/plots2/db/schema.rb:54:in `block in <top (required)>'`

**Comment by Gauravano** [comment]
hey @Ronaq13 ,I guess this issue is related to #1392

**Comment by jywarren** [comment]
OK, I've merged in #2505 -- so this should be resolved now. Can you give it another try? You may have to pull the latest master branch again and then rebase this on top of it. See here for some help with that!

https://publiclab.org/wiki/developers#Resources

**Comment by Ronaq13** [comment]
@jywarren Done. Please check now

**Comment by Gauravano** [comment]
hi @jywarren , I have updated the issue as I think our goal is to change wiki template so URL should be "/wiki/new?n=......" . Am I right ?

**Comment by jywarren** [comment]
Hi all, i'm closing this in favor of #4932 -- thank you all!
