### ISSUE TITLE
hide spam tags on tag listing page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#247]
### The problem

Tags on moderated posts appear at https://publiclab.org/tags -- including advertising related and inappropriate tags.

### Suggested fix

We may not want to delete them all, but can hide them by modifying the query to be something like this:

````ruby
DrupalTag.joins(:drupal_node_community_tag,:drupal_node)
         .where('node.status = ?', 1)
````

On this line: https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L9

### Steps to fix

* [ ] claim this issue with a comment
* [ ] set up a repository locally and make sure that all tests pass
* [ ] start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress"
* [ ] fix the issue following the steps above
* [ ] make sure all tests pass
* [ ] alert someone via either the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by ebarry** [comment]
this would be great!

--

txt only: +1 336-269-1539
@lizbarry <http://twitter.com/lizbarry>

**Comment by jywarren** [comment]
I dont think you'll see spam tags anymore though as I filtered tag auto
complete results. But this is still a good idea.

**Comment by sudheesh001** [comment]
@jywarren @ebarry I'd want to work on this. I've set up the repository and tested it to ensure that the tests pass. I've fixed the issue following the steps above and have re run the tests to ensure all of them are passing.

**Comment by jywarren** [comment]
Great, thanks! I left some comments on your pull request at #450.

**Comment by ebarry** [comment]
Hi @sudheesh001! Thank you again for your valuable contribution to Public Lab. I would like to invite you to join us in a video conference to say a few words about what you contributed and how your experience was. The event is https://publiclab.org/openhour, and it’s coming right up on November 7th, at 1pm EDT which is UTC/GMT -4. 

Please feel free to respond here, or else email liz@publiclab.org, stevie@publiclab.org, jeff@publiclab.org.
