### ISSUE TITLE
Map shows on Notes if only lat:XXXX exists .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#2478]
### Please describe the problem (or idea)

Map shows on Notes if power tag lat:XXXX (or lon:XXXX) exists . 

<img width="426" alt="screen shot 2018-03-12 at 7 38 36 pm" src="https://user-images.githubusercontent.com/14952645/37288458-5796783e-262d-11e8-83c3-1f09e673c3d7.png">

**Comment by Hiroki-Mori360** [comment]
Hello! This is my first comment on github.

I think the problem is that the code inputs 'Not A Number'(NaN) value into args. Use 'parseFloat' and check with 'isNaN'.

**Comment by sagarpreet-chadha** [comment]
Welcome @Hiroki-Mori360 to Github and to PublicLab 😄  !

Do you want to send a Pull Request of your solution ? I can help you with it .
Thanks !

**Comment by Hiroki-Mori360** [comment]
@sagarpreet-chadha
I'd love to !

**Comment by sagarpreet-chadha** [comment]
Great 👍   ! 

I think the lines of code to change/modify are here : 
https://github.com/publiclab/plots2/blob/29ddda47d7872ca6854c2a60124f4a165ef52087/app/views/sidebar/_related.html.erb#L82

Ping me here if you may need any help :)

**Comment by sagarpreet-chadha** [comment]
Closing this . Solved 👍 !
