### ISSUE TITLE
wiki page form is off, can easily be missed

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#248]
I just went to create a new wiki page and thought the form wasn't there. I had to scroll down to find it. I'm running 1050 horizontal pixels on my desktop.

![screenshot from 2015-03-09 12 51 44](https://cloud.githubusercontent.com/assets/880439/6559783/a402501a-c65b-11e4-99f5-a32d39843c5f.png)

This isn't a problem for a new research note.

![screenshot from 2015-03-09 12 52 29](https://cloud.githubusercontent.com/assets/880439/6559786/a86f1f0c-c65b-11e4-8867-40894d53cd70.png)

**Comment by btbonval** [comment]
also useful to know: FF 36.0 on Linux

**Comment by jywarren** [comment]
Ah, this can be caused by a script element appearing inside the
container-fluid div alongside the column divs. If its moved inside the
column div or to the page bottom this won't occur. Good catch!

**Comment by btbonval** [comment]
yay!
