### ISSUE TITLE
Sorting by username on publiclab.org/people

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2483]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

https://publiclab.org/people offers the ability to sort by username or last activity. But when you click sorting by username, it errors:

https://publiclab.org/people?sort=username

The lines where we're doing this are:

https://github.com/publiclab/plots2/blob/29ddda47d7872ca6854c2a60124f4a165ef52087/app/controllers/users_controller.rb#L94

https://github.com/publiclab/plots2/blob/29ddda47d7872ca6854c2a60124f4a165ef52087/app/controllers/users_controller.rb#L104

I'm not sure what's going wrong, but we should try to write a functional test for each option, and we could figure this out by creating a PR with such a test and seeing how it fails!

https://github.com/publiclab/plots2/blob/29ddda47d7872ca6854c2a60124f4a165ef52087/test/functional/users_controller_test.rb#L46-L51

Here, we could do something like:

```ruby
assert_equal assigns(:users).collect(&:id), _________
```

...where ______ is an array of `uids` in the order we expect. I /think/ that will work! We could also test it against its sorted self, so:

```ruby
assert_equal assigns(:users), assigns(:users).sort_by {|user| user.username }
```

**Comment by BornToWin** [comment]
@jywarren I don't understand the problem with the sorting in https://publiclab.org/people?sort=username
Could you be more specific?

**Comment by ViditChitkara** [comment]
@jywarren I'm actually not getting any error. However, the username are being sorted in an unusual way. Probably the usernames starting with a number are being sorted first and then the ones starting with alphabets. Correct me if I am wrong.
