### ISSUE TITLE
question page showing error

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2488]
This page is broken! 

https://publiclab.org/questions/bronwen/03-09-2018/help-the-kits-initiative-launch-the-basic-microscope-kit-by-3d-printing-lens-adaptors

I'll check the logs... :-(

**Comment by ViditChitkara** [comment]
I'd like to help. If you could post the logs over here?

**Comment by ViditChitkara** [comment]
Hmm maybe we need to have a null check for name, will soon create a PR for this😃

**Comment by jywarren** [comment]
We could use a `try` -- but why is there something in there with a nil author?

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/edit/master/app/views/sidebar/_notes.html.erb

**Comment by jywarren** [comment]
someone recently insisted their user account be deleted, so I did so in the db. Perhaps that's an issue.

**Comment by jywarren** [comment]
https://publiclab.org/questions/ is also down. so this seems likely related.

**Comment by jywarren** [comment]
Got it. There was a question with a deleted author. I think we're OK here -- maybe we need to add a `dependent: destroy` between authors and nodes? 

In any case, we're good now -- thanks!

**Comment by ViditChitkara** [comment]
Cool :+1:

**Comment by jywarren** [comment]
thanks, everybody!
