### ISSUE TITLE
New User Post Shows Error

### ISSUE THREAD

**Issue by bronwen9** [publiclab/plots2#2489]
Hello! Clicking the link in a moderators email about a new user's post leads me to an error page. This error appeared both when clicking the "approve" button and when clicking on the link to the post itself to see more.  ¯\_(ツ)_/¯ 

![moderation bug](https://user-images.githubusercontent.com/8331717/37354116-46b2838e-26b7-11e8-9424-9d103bb7d161.gif)

**Comment by bronwen9** [comment]
Ahh, my email wasn't refreshed, it seemed like this post had been approved by the time I clicked through, however the link on the dashboard for the active post seems to lead to error as well. 

![moderation bug2](https://user-images.githubusercontent.com/8331717/37354352-d5a92908-26b7-11e8-8291-2ebe372d2d7c.gif)

**Comment by Gauravano** [comment]
I have checked the Approve link in the mail its working fine. Answer deletion problem which was deleting the node was also resolved, just checked. Also, the thing to note is node (question ) is not deleted as it's still appearing on the dashboard. @jywarren may be Node record from database will help us .

**Comment by jywarren** [comment]
I believe this is the same as #2488, reported this morning -- thanks!

**Comment by jywarren** [comment]
Although I also saw an error on clicking the `Approve` link in the email. I think we should fix #2488 and then circle back to see if there's an additional error or it was just an error on redirecting to the question page. I'll close this but re-open if we find it's a second bug. Thank you!
