### ISSUE TITLE
rendered markdown does not allow nested lists

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#249]
I wrote a nested ordered list like so:

```
1. foo
1. blah
  1. underneath blah
  1. also underneath blah
1. bar
  1. under bar
```

The preview mode rendered it properly, like this:
1. foo
2. blah
   1. underneath blah
   2. also underneath blah
3. bar
   1. under bar

Once rendered, however, it became a straight list that looks like this:
1. foo
2. blah
3. underneath blah
4. also underneath blah
5. bar
6. under bar

**Comment by btbonval** [comment]
Ah, subitems need 4 spaces to render but only 2 spaces to preview.

This might be a nonissue if we move to a different rendering system for WYSIWYG.

**Comment by jywarren** [comment]
This'll be partially addressed in the new Rich Editor, but we may also want to switch to a more compatible Markdown renderer as in https://github.com/publiclab/plots2/issues/139

**Comment by gauravano** [comment]
@jywarren can we close this one as you mentioned https://github.com/publiclab/plots2/issues/139#issuecomment-472221982? Thanks!

**Comment by jywarren** [comment]
yes, let's do!
