### ISSUE TITLE
moderating a spam post shows an error

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2492]
After clicking "spam" in a moderators email, I saw:

![screenshot_20180313-231412](https://user-images.githubusercontent.com/24359/37381591-6635a256-2714-11e8-8ca4-e1a3065663a0.png)

**Comment by jywarren** [comment]
Lol giant image

**Comment by Gauravano** [comment]
hmm, one possibility of error page is node deletion,  as even if another moderator has marked it as Spam then node should be visible to you being admin or moderator. How about adding a check in the controller before displaying the node for its presence as it would reduce uncertainty, so if the node is not there then we can redirect to dashboard displaying a notice. How about this @jywarren ?

**Comment by jywarren** [comment]
So do you think the node was deleted before I could moderate it?

**Comment by Gauravano** [comment]
I think so
