### ISSUE TITLE
Make sidebar content into collapsible sections

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2493]
There's interest (https://github.com/publiclab/plots2/issues/1706) in making the sidebar (see pages like [this one](https://publiclab.org/wiki/community-toolbox)) less "noisy" but not yet a clear plan for how to enable horizontal navigation on the site. As a step in the right direction, let's simplify the sidebar with collapsible sections, as in Bootstrap:

![image](https://user-images.githubusercontent.com/24359/37419274-76a9c2cc-278a-11e8-8a47-880f3c269561.png)

https://getbootstrap.com/docs/3.3/components/#nav-pills

****

Let's have the sidebar's current sections:

* Recent topic contributors
* Recent wiki pages
* Related research notes

become collapsed, but expandable, sections. Each could be a "pill", and maybe they could say:

* Recent contributors
* Related posts
* Related pages

Each with a caret character `v`. When you click it, it runs `$('.related-contributors').toggle()` which opens or closes the list below.

**Comment by chitra591** [comment]
Hi @jywarren, shall I work on this?

**Comment by jywarren** [comment]
Sure, that'd be great! Thanks!

**Comment by ritika98** [comment]
Hi @jywarren , if this issue is not yet solved , i would like to contribute here . Thanks !

**Comment by Gauravano** [comment]
hey @ritika98 , we would love to have your help, but I guess @chitra591 has already claimed this one. You can find more First-timer or FTO candidate issues here https://publiclab.github.io/community-toolbox/#r=all , if you can't find one please let me know I will search one for you. Thanks.

Also, @chitra591 if you need any help please ping. Thanks.

**Comment by marzann** [comment]
@jywarren Is this issue available to work on? You referenced it in our correspondence on another project. Wanted to confirm seeing there was recent conversation. Thank you.

**Comment by jywarren** [comment]
I believe so -- it's been a while and if others come back we can find a new
project for them too! Go ahead and thanks!

**Comment by SidharthBansal** [comment]
@marzann  are you having any trouble with this one?
We can help if you are trapped somewhere.
Thanks

**Comment by nataliyah123** [comment]
@jywarren .hi should i try to make the stacked nav-pills in sidebar of the following file

> app/views/sidebar/_related.html.erb

>

**Comment by jywarren** [comment]
Hi, I think there's someone else working on this right now, so maybe we
should hold off! I created a bunch of new issues recently though, want to
have a look?

**Comment by marzann** [comment]
@jywarren @SidharthBansal: sorry about the delay! I have been quite busy lately. Please open this issue to other collaborators. I will check for new contribution opportunities down the road. Tysm!

**Comment by jywarren** [comment]
ah, no problem! I actually meant there's another project to replace this
content in the sidebar completely, so the collapsible sections are not
needed now, i think!

**Comment by jywarren** [comment]
Oh, sorry! We actually do need this! 

https://stable.publiclab.org/notes/bkleist/04-04-2017/uwec-air-quality-monitoring

See how the tags section is pushed down? 

I'd love to have all the "related" content be removed. Would you be willing to do this? 

Thank you!

**Comment by jywarren** [comment]
@nataliyah123 in particular, i understand @marzann isn't available, though thank you!

**Comment by jywarren** [comment]
So in summary i think we could simply remove these sections:

https://github.com/publiclab/plots2/blob/master/app/views/sidebar/_related.html.erb#L49-L86

and perhaps this? 

https://github.com/publiclab/plots2/blob/master/app/views/sidebar/_related.html.erb#L101-L103

**Comment by derek-allen** [comment]
I'm making some changes to sidebar functionality that can cover this too. Just checking to make sure no one like @nataliyah123 is on this?

**Comment by nataliyah123** [comment]
@derek-allen .ok if your pr is covering the above issue too . and you already have done that . than you can take the issue.

**Comment by jywarren** [comment]
Thanks, both of you!

**Comment by jywarren** [comment]
Please check out https://publiclab.github.io/community-toolbox/#r=all for more issues we'd love help with! 

Maybe this one? https://github.com/publiclab/plots2/issues/2544

**Comment by jywarren** [comment]
Closing this now! Thanks!
