### ISSUE TITLE
popover on tags display

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2494]
We have a tags area on most pages at PublicLab.org, like this one: https://publiclab.org/n/15948

Screenshot:

![image](https://user-images.githubusercontent.com/24359/37421104-d74498e2-278e-11e8-9216-83c5af73efbd.png)

What about using a Bootstrap popover to make this a bit less mysterious? Something like this mockup:

https://getbootstrap.com/docs/3.3/javascript/#popovers

![image](https://user-images.githubusercontent.com/24359/37420992-9b8c272a-278e-11e8-9a76-4873fc652be0.png)

The delete "x" could be switched for a [FontAwesome](https://fontawesome.com/icons) trash can icon in a white "default" button. 

What do people think of this? @publiclab/community-reps

**Comment by ebarry** [comment]
+1

**Comment by sukhbir-singh** [comment]
I would like to work on this !! :smile:

**Comment by jywarren** [comment]
That'd be awesome! This is a really exciting feature. Thanks!

**Comment by jywarren** [comment]
This is complete - a while back! Thanks!
