### ISSUE TITLE
Prototype idea: Notifications API for comments

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2497]
This isn't a priority or anything, just an idea we could explore pretty minimally. Other projects have higher priority!

We could, using just JavaScript, set up notifications for new comments (for example) or notes. Read abou them here: https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API

Here's how it works:

```js
function notifyMe() {
  // Let's check if the browser supports notifications
  if (!("Notification" in window)) {
    alert("This browser does not support system notifications");
  }

  // Let's check whether notification permissions have already been granted
  else if (Notification.permission === "granted") {
    // If it's okay let's create a notification
    var notification = new Notification("Hi there!");
  }

  // Otherwise, we need to ask the user for permission
  else if (Notification.permission !== 'denied') {
    Notification.requestPermission(function (permission) {
      // If the user accepts, let's create a notification
      if (permission === "granted") {
        var notification = new Notification("Hi there!");
      }
    });
  }

  // Finally, if the user has denied notifications and you 
  // want to be respectful there is no need to bother them any more.
}
```

We'd want to add this to the profile page under the buttons on the sidebar. 

And we could trigger it by periodically polling the Comments API, which is not currently working:

https://publiclab.org/api/docs#!/typeahead/typeaheadGetComments

1. It can't be run without a `srchString`, while we'd want to just look for any recent one: https://publiclab.org/api/typeahead/comments?srchString=hydrogen (we can remove that requirement here: https://github.com/publiclab/plots2/blob/1c3882d518ea55aee1191700ed94b9800db9e411/app/api/srch/typeahead.rb#L112)
2. it doesn't seem to return anything! Here's the code that runs the query: https://github.com/publiclab/plots2/blob/1c3882d518ea55aee1191700ed94b9800db9e411/app/services/typeahead_service.rb#L37-L46 

If there's no `srchString` we should just return the last X comments. 

We could:

1. poll this every minute
1. check if notifications are allowed (see above)
2. if they are, then after caching the comment IDs the first time (in JS locally) we could
3. send a notification if there are any new IDs

We'd want to have this running on each page, but what would happen if 2 pages were open at the same time?

**Comment by namangupta01** [comment]
Hey! I am digging into this.

**Comment by namangupta01** [comment]
For multiple tab issue, we can have a table having information of comment and the user which have received the notification and don't send that comment notification on another tab because that comment is already sent to the user through the notification. We can check this while polling for the comment.

**Comment by jywarren** [comment]
This sounds interesting. How do other people solve the multi tab issue? I
would guess it happens a lot.

**Comment by jywarren** [comment]
Also a good potential resource!!! https://dev.to/evilmartians/crafting-user-notifications-in-rails-with-active-delivery-5cn6

**Comment by jywarren** [comment]
Ah and link to mentions of Action Cable here!  https://github.com/publiclab/plots2/issues/3283

**Comment by jywarren** [comment]
https://davidwalsh.name/notifications-api

**Comment by jywarren** [comment]
oh cool! can you share a bit about your approach? i want to be sure the
backend is fairly universal as some people may want to use the API for a
React client...

**Comment by namangupta01** [comment]
Yeah! We will use ActionCable to create different rooms or channels where the client will subscribe based on their authenticity and requirement. And whenever something new is created we will broadcast in those rooms or channels which will lead to sending the data to its subscribers. For solving multiple tab issue we can assign one room to each tab and while broadcasting we will be checking the number of active rooms for that user using Redis as we will use the namespacing for differentiating  between different user which will give us the exact details of number of tabs open by the user and we can also select the which tab in which we want to broadcast the notification in.
This is the best way to implement the real-time notification system.

**Comment by namangupta01** [comment]
As we are going to use sockets for implementing Notification in the project. We can also use this socket technology to provide real-time comment or real-time answer to provide more functionality.

For example, A page on a public lab is opened by me and I am reading comments and answers on that page and in the meanwhile, someone is typing a comment or answer or someone writes a comment or answer then we can let the user know that so and so user is commenting or someone is commenting and also we can add the newly added comment to that page without reloading the page.

The problem with the notification of comment for the same page that the user has opened is that when the user is reading a particular page and the user got the notification for the comment and that comment is done on the same page that the user is reading then to get the comment to appear on the page, user either have to reload the page or click on the notification to open the page in new tab.
Using real-time commenting will help by letting the user know that there is a new comment on the page via the notification and add the comment to that page automatically.

What do you think @jywarren @publiclab/reviewers ?

**Comment by Harshithpabbati** [comment]
I agree with it.

**Comment by SidharthBansal** [comment]
Yeah, sockets are  an essential part which we are lacking at pl. As contributors will increase on the pl, the need of sockets increases.
So, how will you be managing the notifications? Will you be creating Notification system too? Like fb has ??

Thanks Naman for suggesting us great idea.

**Comment by Harshithpabbati** [comment]
Checkout this I made this using the sockets.A simple chat app.
https://afternoon-lake-15004.herokuapp.com/

**Comment by namangupta01** [comment]
Nice app @Harshithpabbati !!
@SidharthBansal We will not create exactly like FB because it also shows the list of notifications but this also sounds like a good idea. @jywarren what do you think of Sidharth's idea?

**Comment by jywarren** [comment]
Just chiming in on a few items here:

1. `different rooms or channels` - these could be either topics http://publiclab.org/tags or maybe first we start with individual notes? If you follow a topic/tag, would you get notifications for all notes/questions in that topic, and if you follow (or participate in) comments on a note/question, you'd get notifications on that node... make sense?
2. It seems that Action Cable uses sockets by design - you can't do one without the other, is that right? Yeah ok -- `Action Cable seamlessly integrates WebSockets with the rest of your Rails application.`  (looking at [this guide](https://edgeguides.rubyonrails.org/action_cable_overview.html) and [tutorials like these](https://duckduckgo.com/?q=action+cable+sockets&atb=v121-6&ia=web))
3. `also we can add the newly added comment to that page without reloading the page` - this seems cool, although we could treat this as a follow-up distinct issue to the main JavaScript Notifications API interface - sound good? Just to do this in sequential chunks - so reloading the page could be a reasonable short-term solution until then.

**Comment by jywarren** [comment]
awesome, great to hear on all this!

**Comment by divyabaid16** [comment]
Hello!
I just came to know that *Public Lab Notifications system* is also one of the proposed projects for GSoC. I was studying it and I found it quite interesting. I have thought of some ideas for it. I was actually not sure that this project is there for Gsoc or not since it's priority was less.
So I wonder should I start with the draft proposal for this?

**Comment by namangupta01** [comment]
Hi Divya!
I have already made a proposal on this
Project. Here's the link
https://publiclab.org/notes/namangupta/03-02-2019/soc-proposal
Thanks

**Comment by gauravano** [comment]
Hi @divyabaid16, we would love to see your ideas and thoughts so feel free to make a proposal. Thanks!

**Comment by jywarren** [comment]
This is completed, though being debugged in https://github.com/publiclab/plots2/issues/6138!
