### ISSUE TITLE
add ability to like a comment

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2498]
Just like on GitHub!

**Comment by ViditChitkara** [comment]
Fantastic idea! Shall I do?

**Comment by jywarren** [comment]
:-) that'd be great!!

**Comment by sukhbir-singh** [comment]
Can I try to solve this issue? if no one is still working on this!!

**Comment by ViditChitkara** [comment]
Hi, I have started working on this, would soon create a PR for the same. 😅😅

**Comment by sukhbir-singh** [comment]
Okay! No problem... Thank you for replying @ViditChitkara
