### ISSUE TITLE
Fresh install throws error on sign in(i did no changes)

### ISSUE THREAD

**Issue by alator21** [publiclab/plots2#2499]
Hello.Just created a fresh install of the project.I had some issues installing it before but i solved them through your older issues.Now i installed everything correctly(i think) and i rushed to localhost:3000.When i tried to sign in i got an error in the users session controller.I mean i cloned the master so something that basic shouldnt throw an error right?Thats the error i got:

undefined method `status' for nil:NilClass

 if params[:user_session].nil? || @user&.drupal_user.status == 1 || @user.nil?
...
...
(users session controller line 19).Any clues?

**Comment by Gauravano** [comment]
hi @alator21 , can you try localhost:3000/signup and let us know the status? Thanks.

**Comment by Gauravano** [comment]
Also, please make sure that `rake db:setup` completes without any error

**Comment by alator21** [comment]
I think I found my issue.I will send a PR later.Thanks for the help anyways.Consider this closed.

**Comment by Gauravano** [comment]
hey @alator21 glad you got the problem fixed !!!. Also, if you share the solution that might help someone else in the future, that would be great.Thanks !!!

**Comment by alator21** [comment]
See #2505.
