### ISSUE TITLE
talk page doesn't work for long titles

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#250]
Reproduce:

1. go to http://publiclab.org/wiki/video-tutorials-for-using-public-lab-tools-and-accessories
2. click Talk
3. Get directed to http://pad.publiclab.org/p/video-tutorials-for-using-public-lab-tools-and-accessories
4. get error "Such a padname is forbidden"

**Comment by jywarren** [comment]
I think it's the length of the title, not the hyphens, after testing. Could
you try for a shorter wiki title? We can/could also create a shortener in
the URL generation (which could in theory make 2 wiki pages share a talk
page if one title is a subset of another, but that doesn't seem like a big
problem) if we know the limit in etherpad.

**Comment by btbonval** [comment]
I think we should make a URL shortener. Etherpad should be a tool that conforms to our needs, we should not need to conform to the tool.

I'll play with the length and see what happens.

**Comment by btbonval** [comment]
If I'm reading upstream code correctly, the URL length is restricted to about 50 characters.
https://github.com/ether/etherpad-lite/blob/9d1eca42b385373bcd6a05d77cfcebbdd9596e91/src/node/db/PadManager.js#L235-L238

**Comment by btbonval** [comment]
Ah I totally see how I was misreading this. I was viewing `[^?]` in the context of start line / end line. Actually, `[^$]` means not dollar sign.

So start the line, optionally capture literal 'g' followed by any character followed by precisely 16 alphanumerics followed by a literal $, then match between 1 and 50 characters that are not a literal $.

Our URLs do not have this optional g pattern, which means the URLs are indeed restricted to 50 characters (which may not include a dollar sign).

What we might want to do is simply truncate the talk URL to 50 characters.

**Comment by btbonval** [comment]
wrong button. closed on accident.

**Comment by btbonval** [comment]
https://github.com/publiclab/plots2/blob/dd3053d56eef424452dd75ed5ea7606753cc380a/app/views/wiki/show.html.erb#L48

Can't figure out what can and cannot be done in embedded Ruby. Surprisingly poorly documented for something so integral to Ruby and also Rails. Anyway, here's my guess at what might work: `<%= @note.slug[0,50] %>`. It wouldn't work in other template languages, and I don't see any documentation saying it'd work here, but ... I don't see anything like filters in erb and a lot of raw Ruby code getting crammed into the tags.

**Comment by jywarren** [comment]
All core ruby works in embedded ruby, no? I guess I've never encountered a case where it doesn't, and simply assumed erb just wraps standard Ruby. I know ActionView provides extra functions on top of base Ruby but don't think anything is disabled or sub-setted. 

I think your solution looks fine!

**Comment by btbonval** [comment]
@jywarren great! can you look at this issue? It is preventing me from testing.
#266

**Comment by btbonval** [comment]
Alright this looks good. Truncates the wiki title at the 50th character, and etherpad works. I added one extra char to the etherpad URL and got the dreaded forbidden padname.
