### ISSUE TITLE
Inline wiki edit not saving

### ISSUE THREAD

**Issue by sctv** [publiclab/plots2#2509]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
Using new inline edit on [this](https://publiclab.org/wiki/chlorophyll-fluorometer?raw=true). 
Added text and link, when I hit save. It returned to the page with no changes. 

on Chrome Version 65.0.3325.162 (Official Build) (64-bit) ? Windows 10

> What did you expect to see that you didn't?
It did not save. 

Work around is to use the old wiki system.

### Please show us where to look

https://publiclab.org/wiki/chlorophyll-fluorometer?raw=true

### What's your PublicLab.org username?
BrianDegger

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by Gauravano** [comment]
hi @sctv , this issue is already open at #2206 but thanks so much for bringing our attention to this one. We would try to resolve this issue as soon as possible. Sorry for the inconvenience.

**Comment by sctv** [comment]
Sorry for the duplicate.
A search didn't bring it up.
Thanks.

**Comment by jywarren** [comment]
Again apologies, some of this has now been fixed and I'm going to merge into #2206 for the remaining. Many thanks! 👍
