### ISSUE TITLE
Update mapping mailing list to include poles

### ISSUE THREAD

**Issue by Nataliegurl** [publiclab/plots2#251]
Currently the language for the description of the aerial mapping and photography list just say balloons and kites. Could we add poles to that of should it have it's own forum?

**Comment by jywarren** [comment]
I think same forum, but where do you see that language? Which URL?

**Comment by Nataliegurl** [comment]
on the grassrootsmapping forum
http://publiclab.org/wiki/mailing-lists
http://groups.google.com/group/grassrootsmapping

-- 
Natalie Mayorga





*Kits Initiative ManagerPublic Lab412 NW Couch, Ste. 307Portland, OR 97209*

*T: 010.722.2291*

*F: 504.324.0401*

*Natalie@publiclab.org <Natalie@publiclab.org>*

*www.publiclab.org <http://www.publiclab.org>*


*FB: www.facebook.com/PublicLab <http://www.facebook.com/PublicLab>*

*Twitter: @PublicLab, @natcat5050*
*Instagram: public_lab*

**Comment by jywarren** [comment]
Ok, go ahead and change it there, and well add a link to the list from
mapknotter.org based on this issue. Thanks!

**Comment by jywarren** [comment]
Erg, sorry, the last based on
https://github.com/publiclab/mapknitter/issues/139

**Comment by Nataliegurl** [comment]
Okay changed

-- 
Natalie Mayorga





*Kits Initiative ManagerPublic Lab412 NW Couch, Ste. 307Portland, OR 97209*

*T: 010.722.2291*

*F: 504.324.0401*

*Natalie@publiclab.org <Natalie@publiclab.org>*

*www.publiclab.org <http://www.publiclab.org>*


*FB: www.facebook.com/PublicLab <http://www.facebook.com/PublicLab>*

*Twitter: @PublicLab, @natcat5050*
*Instagram: public_lab*
