### ISSUE TITLE
Translation mistake

### ISSUE THREAD

**Issue by Gauravano** [publiclab/plots2#2513]
hi @publiclab/community-reps , a user from our PublicLab gitter channel has reported that Welcome line at "/research" - "Willkommen!!Dies könnte Ihr Armaturenbrett wenn Sie das Public Lab verbunden" doesn't form a correct sentence. As I don't know Deutsch so I can't verify, so your input is required. Also, please provide the correct translation of sentence so that FTO can be opened.Thanks.

**Comment by jywarren** [comment]
Via zybell in chat: 

> Fun idea: Replace dashboard(the word) with a combobox where the 10 most popular translations are selectable and the most popular is default. And add a Selection: 'Add translation'"Übersetzung hinzufügen"!-)

**Comment by jywarren** [comment]
I think the German translation across the site is potentially auto-translated and should perhaps be replaced or removed for now. Thanks!

**Comment by Gauravano** [comment]
> I think the German translation across the site is potentially auto-translated and should perhaps be replaced or removed for now. Thanks!

So, I guess translation at "/research should be removed" , what do you think @jywarren ?

**Comment by Gauravano** [comment]
> Fun idea: Replace dashboard(the word) with a combobox where the 10 most popular translations are selectable and the most popular is default. And add a Selection: 'Add translation'"Übersetzung hinzufügen"!-)

What are your views on this @jywarren ?

**Comment by jywarren** [comment]
Take a look at this big proposal: #2530 -- we have a lot of issues with translation so perhaps we should merge this into that?

**Comment by Gauravano** [comment]
hi @jywarren , just gone through #2530 , ideas mentioned there are really great, this issue can surely be merged with #2530 . Thanks.
