### ISSUE TITLE
Change research tab categories

### ISSUE THREAD

**Issue by sdosemagen** [publiclab/plots2#252]
Note-- the formatting is wacky when I post this as a GitHub issue. Jeff-- please see the Google Doc version for formatting. Timeline: March 25th.

* [x] Change tab heading from "research" to "projects"
* [x] add Open Land
* [x] add Fellows
* [x] add divider below "Open"s

**Comment by jywarren** [comment]
@ebarry @steviepubliclab - what would the "People" tab be ordered by? Would it show all people? If it shows recent users (admins can see this list: http://publiclab.org/users/list) you'll see a lot of spam users. 

I'll move ahead with the redesign skipping /people/ for now.

**Comment by jywarren** [comment]
Also, do we want to find a new home for the "popular tags" link to http://publiclab.org/tags? It's a nice page.

**Comment by jywarren** [comment]
also http://publiclab.org/contributors, which is nice.

**Comment by jywarren** [comment]
OK, (heads up @ebarry @steviepubliclab), this is ready except for my questions. It looks like this:

![image](https://cloud.githubusercontent.com/assets/24359/6765965/83a951f6-cfca-11e4-8a55-4eb423a6a1e0.png)

**Comment by ebarry** [comment]
Looking good!
regarding /profiles, we've started talking about sorting methods here: https://github.com/publiclab/plots2/issues/206
I could get behind the idea that in the drop down, People links to /contributors, and at the top of contributors, there's a link to /profiles 
Maybe /profiles needs to be /people instead?

The top of /wiki itself would be a great place to link to /tags. Maybe /tags appears at the top of both /research and /wiki to assist people with navigation?
Here is the issue where we are talking about what admins would need to properly moderate the tags, but maybe we could add some of the alphabetical sorting to everyone's view? https://github.com/publiclab/plots2/issues/179

I don't have a strong suggestion to offer, but want to note that the title "Public Lab Wiki" might not need to have Public Lab in the name, and that Wiki could be replaced with something more descriptive like (and ideally catchier than) "Knowledge Base"

**Comment by sdosemagen** [comment]
Here's a link to the fellows wiki. I'll post content on Monday once others have a chance to take a look: http://publiclab.org/wiki/fellows

Also, I was thinking something more like this as top categories and subcategories. If it's not possible, that's fine:

RESEARCH
Public Lab Wiki
Research Notes
---
TOOLS
PLACES
PEOPLE
---
INITIATIVES
...

**Comment by sdosemagen** [comment]
It did that same thing again, I'll send an email.

**Comment by jywarren** [comment]
What about /kits -- just wondering if we forgot that or if it'll show somewhere else?

**Comment by jywarren** [comment]
I'm happy to just publish these changes for now and add Kits later?

**Comment by jywarren** [comment]
@sdosemagen  sez: 

> Yay, new tab! Are you holding on adding Fellows/Lending Library/People for some reason or was that just missed? Also, changing the name "research" to "projects"

Reopening, tnx.

**Comment by sdosemagen** [comment]
Ahh, I see... when I put the formatted categories in the GH box, it cuts things out. See the email I sent you with the list of categories if this is still a confusion.
