### ISSUE TITLE
Change the text on top of profile search pages

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#2520]
I'm interested in adding to that text that appears on top of the profile pages that shows up when you click: "Questions Asked," "Activities Posted," and "Activities Attempted" 

(example profile page: https://publiclab.org/profile/stevie) 

It currently says: 
<img width="1068" alt="screen shot 2018-03-21 at 9 47 59 am" src="https://user-images.githubusercontent.com/7490478/37718001-ba10f44e-2cef-11e8-98b6-5b9508d3905a.png">

I'm interested in adding: "Here are all the questions you've asked. _This is a wildcard tag search. Please enter a tag without wildcards to display lead wiki pages._ Wildcard tag searches use the * asterisk in their URLs"

**Comment by ebarry** [comment]
love this! 

I notice that this part "_Please enter a tag without wildcards to display lead wiki pages_" is pretty deep in the weeds -- is there another way we could explain this and help people find their way to what they are looking for?

**Comment by jywarren** [comment]
Agreed on both! We actually show something similar on https://publiclab.org/contributors/pm

https://github.com/publiclab/plots2/blob/f3e94060aa60c92f80821b8216b83d93d07b7e3c/app/views/tag/_contributors.html.erb#L9-L13

Or we could adapt the code from the profile page, which is a little complex but not bad:

https://github.com/publiclab/plots2/blob/f3e94060aa60c92f80821b8216b83d93d07b7e3c/app/views/users/profile.html.erb#L160-L168

**Comment by rtrunkhill** [comment]
Hey i'm looking into this.

Would it be better to put the "Here are all the questions you've asked" next to the asked/answered toggle button? 

![image](https://user-images.githubusercontent.com/28711410/41176395-0c0a94ae-6b15-11e8-84f9-15ff7e1532c0.png)

Ive been trying to figure out how to change the message to ```"These are the answers provided by<%= link_to(@user.name,"/profile/#{@user.name}") %>"``` but im having trouble attaching it to the toggle button.

**Comment by Gauravano** [comment]
Hi @rtrunkhill, Can't say much about the placement of text, @publiclab/community-reps will update you shortly on that. About the code: You can use JavaScript for updating the text on button click. Like each time button is clicked, f

**Comment by Gauravano** [comment]
oops, sorry

**Comment by rtrunkhill** [comment]
so I added this code: ```  <% elsif @wildcard %>
    _<% if @node_type == "questions"%>
      <p>Here are all the questions asked by <%= link_to(@user.name,"/profile/#{@user.name}") %>.</p>
    <% end %>_
    <p><i>This is a wildcard tag search. Please enter a tag without wildcards to display lead wiki pages.</i></p>
    <p>Wildcard tag searches use the * asterisk in their URLs</p>
  <% else %>
    <p>This topic has no lead wiki page.</p>
    <p><a class="btn btn-primary" href="/wiki/<%= params[:id] %>?n=14552"><span class="fa fa-plus fa-white"></span> Add one now</a></p>
  <% end %>```
 But i haven't been able to find the node_types for act ivies nor replications because something like this: 
```    <% if @node_type == "questions"%>
      <p>Here are all the questions asked by <%= link_to(@user.name,"/profile/#{@user.name}") %>.</p>
    <% elsif @note_type == "activity"%>
      <p>Here are all of <%= link_to(@user.name,"/profile/#{@user.name}") %> activities.</p>
    <% end %>```

doesn't bring up the message on the /tag/activity:* route

**Comment by jywarren** [comment]
Unfortunately we don't have a convenient method for separating out activities or replications -- perhaps we need a convenience method like `node.is_type('activity')`?

But for now, you can check by looking if `node.has_power_tag('activity')` or `node.has_power_tag('replication')`

**Comment by rtrunkhill** [comment]
i just figured it out, I wrote the code like this ```<% elsif @node_type == "note" && params[:id].match("activity:") %>``` and ```<% elsif @node_type == "note" && params[:id].match("replication:") %>```  

it works great.  going to submit the pr

**Comment by jywarren** [comment]
oh cool!

**Comment by rtrunkhill** [comment]
rake test gives me this error ```Error:
TagControllerTest#test_wildcard_tag_should_have_a_active_asked_and_an_inactive_answered_tab_for_question:
ActionView::Template::Error: undefined method `name' for nil:NilClass
    app/views/tag/show.html.erb:25:in `_app_views_tag_show_html_erb__3511267637889032259_72613600'
    app/controllers/tag_controller.rb:134:in `block (2 levels) in show'
    app/controllers/tag_controller.rb:133:in `show'
    test/functional/tag_controller_test.rb:211:in `block in <class:TagControllerTest>'```

which is referencing this line ```<p>Here are all the questions asked by <%= link_to(@user.name,"/profile/#{@user.name}") %>.</p>````

that's the exact same line used later on the page here 
![image](https://user-images.githubusercontent.com/28711410/41431504-f89b1dd2-6fc7-11e8-8f5f-9e70239227cb.png)

im not sure why it's kicking it back.

**Comment by rtrunkhill** [comment]
disregard.  i just made the messages more generic and it passed all tests, re submitting the pr now
