### ISSUE TITLE
Followers count on tag page inconsistent with followers list

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2527]
### Please describe the problem (or idea)
The count on the followers on /tag/balloon etc is not consistent with the followers list
![image](https://user-images.githubusercontent.com/20972099/37785175-7b8740da-2e1f-11e8-89f5-8151f9a7f460.png)

See that the number of followers is 1 but followers list shows none

**Comment by jywarren** [comment]
hmm, do you think it's possible it's a banned user? Good catch!
