### ISSUE TITLE
can't enter new tags that are a subset of existing tagname

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#253]
since autocomplete auto-selects the first entry

i.e. `monkey` if it's a new tag and there is an existing tag starting with `monkey*`, like `monkey-business`

We may want to migrate to Bootstrap 3 first, as the typeahead feature may need some rewriting anyways.

**Comment by btbonval** [comment]
I noticed this problem myself, although the work around is to add a single tag at a time. I think the workaround I used was: write the full name, click off the autocomplete, make sure you include a comma, push enter.

It'd be better if we didn't need workarounds, of course ;)
