### ISSUE TITLE
Make listing of nodes with multiple tags

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2535]
We're interested in displaying, for example, all wiki pages that are tagged with both `method`:

https://publiclab.org/wiki/tag/method

And another tag, like `balloon-mapping`:

https://publiclab.org/wiki/tag/balloon-mapping

Maybe the syntax could be: 

https://publiclab.org/wiki/tag/method+balloon-mapping

I think this could be a relatively easy change to this query:

https://github.com/publiclab/plots2/blob/9cfe510b71746469fe4ca5fbcf6ae997f496246b/app/controllers/tag_controller.rb#L92-L98

But I'm not sure how to fetch nodes have one tag, AND also another tag, because of how the query is structured. Anyone have an idea?

**Comment by shauncarland** [comment]
I'm interested in exploring this

**Comment by shauncarland** [comment]
I also would be interested in doing some refactoring.  These controllers feel awfully bloated and I think a lot of the logic would be better suit in a separate class or in the Tags model.  If people would be receptive to that...?

**Comment by jywarren** [comment]
That would be great! We'd particularly appreciate unit tested model methods
that could reduce controller complexity. Thanks for offering!!

**Comment by shauncarland** [comment]
w00t!

I have a question though.  For both of those tags (`method` and `baloon-mapping`), it looks like they have unique "headers" (I'm attaching images of what I'm describing below).  But they both also have the graph and the `Notes tagged with X`.  Do we want to just keep that bottom part if we're listing nodes with multiple tags?

**Comment by shauncarland** [comment]
<img width="1258" alt="screen shot 2018-03-31 at 12 13 56 pm" src="https://user-images.githubusercontent.com/10911456/38165163-2cf77a92-34dd-11e8-8cb2-c312d2536b5c.png">
<img width="1278" alt="screen shot 2018-03-31 at 12 13 48 pm" src="https://user-images.githubusercontent.com/10911456/38165164-2d06012a-34dd-11e8-9850-191bbaa6ba3a.png">

**Comment by shauncarland** [comment]
<img width="1183" alt="screen shot 2018-03-31 at 12 15 27 pm" src="https://user-images.githubusercontent.com/10911456/38165168-3d6ee068-34dd-11e8-90fe-a08bc2bb69da.png">


And just like, keep this part?

**Comment by jywarren** [comment]
Yes, I think that's the best way forward. We can even skip the graph for
the time being, although it seems possible we could implement that as a
follow-up! Thanks!

**Comment by thestarsareprojectors** [comment]
this is shaun (using a different account).  i want to take this on again

**Comment by jywarren** [comment]
Oh, awesome, thank you!

**Comment by thestarsareprojectors** [comment]
👍 

Just to clarify.  For this ticket, we want to only show a node if it has all of the tags the user is searching for?  Yes?

**Comment by jywarren** [comment]
Yep, that's right!!!

**Comment by jywarren** [comment]
Hi! I know it's been a while, but curious if you're still interested in taking this one up? Thanks!

**Comment by jywarren** [comment]
We're going to close this up, actually, and I'll post a follow-up to #3064 with our next-steps! Thanks!
