### ISSUE TITLE
Layer icon missing on profile map .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#2537]
### Please describe the problem (or idea)

<img width="312" alt="screen shot 2018-03-25 at 12 54 19 am" src="https://user-images.githubusercontent.com/14952645/37868077-13ed760c-2fc7-11e8-922c-83fce7221480.png">

The top- right corner has missing icon .
Should be like this : 

<img width="318" alt="screen shot 2018-03-25 at 12 55 12 am" src="https://user-images.githubusercontent.com/14952645/37868084-31f0dfcc-2fc7-11e8-9423-b90293b4d7ac.png">

### Please show us where to look

https://publiclab.org/profile/sagarpreet

### Solutions : 

1.) Overwrite the CSS .
2.) Add leaflet css cdn links 

https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.1/images/layers.png
https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.1/images/layers-2x.png

****

**Comment by jywarren** [comment]
I'm interested in maybe doing this in an inline `<script>` tag so that it's easier to break out into its own library. OR -- if we plan to use Leaflet all over the site, which i guess we do already, finding a good place in a top-level stylesheet for this. Maybe `/app/assets/stylesheets/leaflet.css` and then including it into `application.css` ?

**Comment by sagarpreet-chadha** [comment]
Okay 😄 , will submit the PR in a day or two . 
Thanks !

**Comment by sagarpreet-chadha** [comment]
@jywarren ...I think this icon is not shown because we have installed **leaflet library** via **bower.json** and **required** in `application.js`  , hence the icon will look for url `/assets/leaflet/dist/images/marker-icon-2x.png`  which does not exists , see this :

<img width="448" alt="screen shot 2018-04-07 at 5 48 27 pm" src="https://user-images.githubusercontent.com/14952645/38454817-f25a978e-3a8b-11e8-9f2b-d588301b6606.png">

And we are able to see the Full-Screen icon because we are using **cdn link**  and do not have a local-copy as we have for **leaflet** .

So if we pre-compile the images by adding this to `environment/production.rb` : 
`config.assets.precompile += %w[*.png *.jpg *.jpeg *.gif] ` .

What do you think ?

**Comment by sagarpreet-chadha** [comment]
This is solved 🎉  !
Closing this issue .
