### ISSUE TITLE
Add :smiley: style emoji to node and comment display

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2540]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://publiclab.github.io/community-toolbox/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

We often use friendly emoji 😄  🐱 👍 🎈 

And it's an important part of our [software outreach](https://publiclab.org/software-outreach) -- really important!

https://github.com/janlelis/unicode-emoji can convert `:smiley:` style written-out emoji into visual emoji "pictures" -- let's install it and add a filter to both node display and comment display. 

These are the relevant code areas to add the filters. For comments:

https://github.com/publiclab/plots2/blob/f524608ac1c65adc6ac91c2c72d76152d870b6a4/app/models/comment.rb#L44-L48

For nodes: 

https://github.com/publiclab/plots2/blob/f524608ac1c65adc6ac91c2c72d76152d870b6a4/app/models/revision.rb#L94-L101

****

The docs for `unicode-emoji` say this is how you convert a string:

`string.scan(Unicode::Emoji::REGEX) # => ["😴", "▶️", "🛌🏽", "🇵🇹", "🏴󠁧󠁢󠁳󠁣󠁴󠁿", "2️⃣", "🤾🏽‍♀️"]`

This should be a fun one 😄 -- any help appreciated!

**Comment by meghana-07** [comment]
Hi @jywarren , shall I claim this issue ?

**Comment by MayankKashyap** [comment]
@meghana-07 yeah sure..

**Comment by sagarpreet-chadha** [comment]
Solved in #2566 .
