### ISSUE TITLE
Remove German auto-translations until we can do true translation

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2549]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://publiclab.github.io/community-toolbox/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

The German translations, for example:

https://github.com/publiclab/plots2/blob/master/config/locales/views/notes/_responses/de.yml

Are auto-translated, and we've received feedback from 

These were added originally to demonstrate our i18n system, which is great! However, I think we should remove them until we can develop a system for true translation, perhaps as part of #2530 

For now, if someone could remove the various `de.yml` files in `/config/locales/`, that would be great!

This could be made into a lot of first-timers issues with https://github.com/hoodiehq/first-timers-bot, potentially? Although I don't know how it handles file deletion. Could be worth a try!

**Comment by bld456** [comment]
Hello @jywarren 
I'd like to claim this issue. This will be my first contribution to your project and I'm looking forwards to it.

**Comment by jywarren** [comment]
thank you!!!
