### ISSUE TITLE
Create tour of publiclab.org 

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#256]
similar to cute popups that walk you through WWB and SW

**Comment by jywarren** [comment]
Can you list the steps in the tour, with at least sample text?

**Comment by btbonval** [comment]
This is complete deja vu, I thought we already had a ticket for this where I said the following:

We have something like this for FinalsClub using javascript. You can see the tour popup here:
https://www.karmanotes.org/note/harvard/the-human-mind-an-introduction-to-mind-brain-and-behavior/lecture-4-21208-evolution

That was done using JoyRide.
http://zurb.com/playground/jquery-joyride-feature-tour-plugin

**Comment by jywarren** [comment]
Nice example via Rackspace:

![rackspace-tour](https://cloud.githubusercontent.com/assets/24359/7462758/01a59464-f282-11e4-9a60-f65df5882b66.png)

**Comment by jywarren** [comment]
Merging this into #441 which has more examples.
