### ISSUE TITLE
not all tags showing up on /tags page

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#2563]
### Please describe the problem (or idea)
I was searching for the tag mapping on www.publiclab.org/tags and nothing came up. However we have a lot of things tagged mapping. You can see them here:

www.publiclab.org/tag/mapping. 

Anyone know how to fix this or why it wouldn't be showing?

**Comment by Gauravano** [comment]
hi @steviepubliclab , I tried 'mapping' and got the same result, I have also tried some other keyword searches like event, quality and observed that those tags are not shown in which keyword is present after the '-'. For instance, I have searched quality but only one tag came on search 'quality' but I have seen air-quality on tags page too.

I think REGEX needs to be updated for solving this issue.

**Comment by Gauravano** [comment]
I have raised a PR in #2575 , the query needs to be updated, there is no role of REGEX. It will solve this issue.

![issue_solved](https://user-images.githubusercontent.com/20878070/38192245-a91aa448-3689-11e8-9471-990185b58568.gif)

**Comment by steviepubliclab** [comment]
Hi there, noticed this issue is closed, but I'm still having this problem. For example, when I search new-orleans on tag page nothing shows up, but there is a lot of material with that tag:

https://publiclab.org/tag/new-orleans

**Comment by jywarren** [comment]
Thanks, can you re-open this? For clarity, when you enter a search on
https://publiclab.org/tags/ with the search phrase "new-orleans", you go to
a page like https://publiclab.org/tags/new-orleans -- this should be in the
`index` action of the tags_controller.

**Comment by ebarry** [comment]
This is working now!
