### ISSUE TITLE
space separated callouts break middle callouts

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#257]
followup from @jywarren 's report here https://github.com/publiclab/plots2/issues/116#issuecomment-85113646

Can be exemplified here:
http://rubular.com/r/Vevai8HVFi

In this case, ` @mathew @natalie @becki` sees `@mathew` grabbing the space after the callout, which prevents `@natalie` from being seen for some reason.

**Comment by btbonval** [comment]
Changing the list to comma separated works fine. Not that we should require it, just saying.

**Comment by btbonval** [comment]
Yeah the pattern requires either start of line or a non-alphanumeric prior to \@, this ensures we aren't looking at an email.

Because ` @mathew ` steals the non-alphanumeric prior to `@natalie`, it cannot be matched. Unfortunately, `@natalie`, while having nothing in the front and seemingly a match for `^`, does not actually match because it is not the beginning of a line.

I wonder if there's a way to say "nothing" rather than `^`.

**Comment by btbonval** [comment]
PS I honeslty have no clue why the space is not shared.

**Comment by btbonval** [comment]
Removing that last `(\W)` group (be it combined with `$` or `\z`) seems to fix the problem. However I'd like to know how that ended up there in the first place. Was it just overthinking the problem or is there a reason for it?

**Comment by btbonval** [comment]
I reviewed when the current regex was written. The final non-alphanumeric group was added by me using the example in the first paragraph of the above rubular link. Removing that final non-alphanumeric group still works just fine on that first paragraph, so it was probably excessive.

I think we can remove that final group and solve the problem. @jywarren If you're willing to gamble on my being correct, I'll just remove that final group from the regex directly in the file on github. The regex has been tested in rubular, so I probably don't need to fire up the whole website to test it, right?

**Comment by btbonval** [comment]
Remove the final group from this line:
https://github.com/publiclab/plots2/blob/master/config/initializers/constants.rb#L2

Remove references to the final group in both these lines. These were used to inject a trailing period, space, or whatever was matched back into the output, but now that we don't match it, it shouldn't need to be inserted back in.
https://github.com/publiclab/plots2/blob/master/config/initializers/constants.rb#L3-L4

**Comment by jywarren** [comment]
I've written a test for this case, and can try the fix against it.

**Comment by jywarren** [comment]
tested and merged!
