### ISSUE TITLE
people prompted to log in upon asking a question on /questions

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2592]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I tried going to http://publiclab.org/questions and typing in a question.

> What did you expect to see that you didn't?

On submitting, I saw  prompt to log in, which I worry does not preserve my question and is a barrier;

Maybe we should ask people to sign up within the question form if they aren't logged in? It's a bit disruptive to just be prompted when you are trying to ask. Just needs some better UI flow here. 

Anyone want to try thinking through this? Thanks!!

**Comment by pdurbin** [comment]
Check out https://ux.stackexchange.com/questions/ask and how you don't have to log in to ask a question if you use the "post as a guest" option. Here's a screenshot:

<img width="1231" alt="screen shot 2018-04-07 at 1 58 37 pm" src="https://user-images.githubusercontent.com/21006/38458384-d1619bf6-3a6b-11e8-8870-cff73d09baf3.png">

Note that not all Stack Exchange sites allow posting as a guest: https://meta.stackoverflow.com/questions/260906/why-is-it-not-possible-to-post-as-a-guest-on-some-stack-exchange-websites

**Comment by waqargithub** [comment]
Here are two options:

1. Display a sign-in or guest option, as suggested by @pdurbin, but only _if the user is not already signed in_, I joined that community and confirmed that ux.stackexchange displays the sign-in box only if the user is not signed in.

2. Preserve the question by using a modal for sign-in or registration if the user is not already signed in and submits a question.

The second option preserves the question but is still disruptive. The first option avoids the disruption and preserves the question. So I like the first option better.

**Comment by SidharthBansal** [comment]
Yeah, you can work on it. I will be busy till 3rd October due to mid semester exams. Please contact @jywarren or @publiclab/reviewers for queries
Best of luck

**Comment by jywarren** [comment]
I love the solution:

> Display a sign-in or guest option, as suggested by @pdurbin, but only if the user is not already signed in, I joined that community and confirmed that ux.stackexchange displays the sign-in box only if the user is not signed in.

I think, if you're not logged in, instead of submitting the text and going to a new page, it could reveal a compact "log in" area similar to https://publiclab.org/signup -- but preserve the content of the question you asked with a `return_to` parameter, which could lead to a prefilled question form like this:

https://publiclab.org/signup?return_to=/questions/new?title=My%20Title

That would lead you here once you signed up: https://publiclab.org/questions/new?title=My%20Title

This could even work more simply without an inline signup form, but just preserving the title via the `return_to` URL parameter. Does this make sense?

**Comment by jywarren** [comment]
We actually should pick this up and solve it - I think we should address the "as guest" option in a follow-up and fix the smaller initial issue of a log in prompt when you submit the question, triggered by the signup URL above. @aSquare14 are you still interested in trying that? 

Screenshot of the question form which definitely does not preserve the question asked:

![image](https://user-images.githubusercontent.com/24359/47444553-b826b700-d784-11e8-8509-3377451e616a.png)


In fact, it directs to /login but **without** preserving the `return_to` value!

**Comment by jywarren** [comment]
So I think perhaps we should try having the form go to:

https://publiclab.org/signup?return_to=/questions/new?title=My%20Question...

And testing it locally. If that doesn't work, we could do a simpler thing - just grey out the question form and show beneath it a login form like #3756 so people know they must log in before asking a question.

**Comment by SidharthBansal** [comment]
@kevinzluo please submit a patch for this too
#4227
This is linked with your work.

**Comment by kevinzluo** [comment]
Currently this the continue button is disabled while the text above, which also prompts for login, is kept. I will enable the continue button so that the modal opens and the user can log in. We can discuss whether to keep the text above it or not in the PR.

**Comment by SidharthBansal** [comment]
@kevinzluo well done you deserve reward
https://codein.withgoogle.com/dashboard/tasks/5753130928046080/
