### ISSUE TITLE
Read more link in tags module is empty

### ISSUE THREAD

**Issue by Gauravano** [publiclab/plots2#2595]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.
Read more link under Tags field doesn't point to any page due to empty href attribute.

![empty_link](https://user-images.githubusercontent.com/20878070/38472009-0789038c-3b97-11e8-9653-ded57e49847b.png)

 So, link https://publiclab.org/wiki/power-tags needs to be added in href attribute. As the design of https://publiclab.org/post is rendered from https://github.com/publiclab/PublicLab.Editor so Pull request need to be opened against [PublicLabEditor](https://github.com/publiclab/PublicLab.Editor) repository after taking the fork and then the clone of the forked repository. 

File that needs changes - 

Link (https://publiclab.org/wiki/power-tags) need to be added on the following lines in href attribute:- 

https://github.com/publiclab/PublicLab.Editor/blob/master/dist/PublicLab.Editor.js#L23074

https://github.com/publiclab/PublicLab.Editor/blob/master/dist/PublicLab.Editor.js#L23083

Thank you!!

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the above stated files in the `PublicLabEditor` repository so as to do the required changes.

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by cindychangy** [comment]
I can help with this :)

**Comment by Gauravano** [comment]
Awesome ! @cindychangy you can start solving this one, if you need any help feel free to mention me or any @publiclab/reviewers, we would be happy to help. Thanks.

**Comment by Gauravano** [comment]
hi @cindychangy , just checking if you need any help with this. Thanks.

**Comment by Gauravano** [comment]
In progress in https://github.com/publiclab/PublicLab.Editor/pull/132 by @cindychangy

**Comment by jywarren** [comment]
I think this is complete now? Thank you!!!

**Comment by Gauravano** [comment]
oh yes, closing now : )
