### ISSUE TITLE
not obvious that PublicLab has software projects

### ISSUE THREAD

**Issue by Be-ing** [publiclab/plots2#2596]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I watched a [recording of a presentation at LibrePlanet 2018](https://media.libreplanet.org/u/libreplanet/m/sharing-strategies-for-welcoming-newcomers-into-floss-projects-first-timers-only-list-moderation-and-more/) discussing PublicLab's efforts to bring in more software developers and wanted to find out more about the software.

> What did you expect to see that you didn't?

I expected to see the software featured prominently on the [PublicLab homepage](https://publiclab.org/). I did not see anything about software at first glance. I looked around more and expected to see a link to a page about contributing code or a link to the GitHub repository in the Get Involved menu and something about the software in the About menu. Instead I found nothing about software until I scrolled way down to the footer. If I hadn't come to the PublicLab website knowing that PublicLab makes software, I probably would not have figured that out.

### Please show us where to look

https://publiclab.org/

### What's your PublicLab.org username?

none

### Browser, version, and operating system

any

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by pdurbin** [comment]
I was in the audience and I thought it would be easier to find the resources too.

It seems like https://publiclab.org/software-outreach is the main resource for all the software they were talking about.

The slides themselves can be found at https://publiclab.org/notes/warren/03-22-2018/libreplanet-talk-sharing-strategies-for-welcoming-newcomers-into-floss-projects-first-timers-only-list-moderation-and-more

It was an absolutely fantastic talk. Great job @jywarren and @ebarry !!! 🎉 👍 🎈 🦁

**Comment by jywarren** [comment]
Hi! That's a good point -- our software work is younger than the "mothership" (so to speak) of open hardware and environmental monitoring methods, and we're still figuring out how to create a space for it on PublicLab.org. A lot of things compete for attention on the front page. Do you think this could be in a menu, or have other ideas of where we could highlight it? 

Thanks a lot! @pdurbin too!

**Comment by Be-ing** [comment]
I think it could fit somewhere under "II. The Collaboration" or "III. The Solution". I'll leave it to someone more involved in Public Lab to figure out exactly how to say that. There should definitely be an entry in the Get Involved menu that links to a page for getting involved in coding.

**Comment by ebarry** [comment]
ah, great idea! Here's the exact code for the dropdown menu, want to open a PR?
https://github.com/publiclab/plots2/blob/ceb7d05404b4619c7fa8cd8cae5e8215798cb02c/app/views/layouts/_header.html.erb#L45-L65

**Comment by pdurbin** [comment]
Nowadays there's a prominent "Software Projects" item under "Get Involved" (screenshot below) so perhaps this issue can be closed? What do you think @Be-ing and others?

![Screenshot from 2019-06-01 16-08-22](https://user-images.githubusercontent.com/21006/58753072-a9755080-8487-11e9-9b8a-f8766e40e41e.png)

**Comment by gauravano** [comment]
Oh, that's an old issue. Thanks, @pdurbin for updating. If further outreach is required, we can create a feature on /home and list our GitHub org there with some text?

**Comment by Be-ing** [comment]
Looks good to me :+1:
