### ISSUE TITLE
Changing Zoom level of /people map on searching .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#2598]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

We have a **/people map** on this link https://publiclab.org/people/ . 

<img width="876" alt="screen shot 2018-04-09 at 3 38 31 pm" src="https://user-images.githubusercontent.com/14952645/38492840-d41fde90-3c0d-11e8-8fb3-a48a0d09b13e.png">

On searching a user 👤  from the **searchbar** 🔍  the map 🗺  zooms-in to that **user's marker**  too much ! 

Let's change this level of zoom-in  !

Currently the map zoom-in level is 11 , let's change this to level 7  .

Corresponding line of code :
https://github.com/publiclab/plots2/blob/2f35d8734139a35b524af0c29305122b19bcbffb/app/views/map/_peopleLeaflet.html.erb#L25

Thank you!!

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the above stated files in the `PublicLabEditor` repository so as to do the required changes.

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by rajdhandus** [comment]
Can I please work on this issue.. ?

**Comment by sagarpreet-chadha** [comment]
Yes @rajdhandus ! We would love your help 😄 🎈 !
Feel free to ask me here or @publiclab/reviewers team in case of any doubt . 
Thanks !
