### ISSUE TITLE
Group page maps show everybody, not just group members (API changes needed)

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2602]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

We have this fantastic new feature of group people listings: https://publiclab.org/people/group:partsandcrafts

But the lead people map still shows everybody, not just the group members. 

The list is generated here:

https://github.com/publiclab/plots2/blob/2f35d8734139a35b524af0c29305122b19bcbffb/app/controllers/users_controller.rb#L102-L104

But the map is generated from an API query, here: 

https://github.com/publiclab/plots2/blob/2f35d8734139a35b524af0c29305122b19bcbffb/app/views/map/_peopleLeaflet.html.erb#L36

That's hitting this API method: 

https://github.com/publiclab/plots2/blob/2f35d8734139a35b524af0c29305122b19bcbffb/app/api/srch/search.rb#L158

We should add a "people by tag" option to the API, and adjust this query in the leaflet template to show the right people! 

## Help wanted!

Any help on this is appreciated -- it's a bit complex. I think we could start by defining a new test for people location search, based on the existing test here:

https://github.com/publiclab/plots2/blob/2f35d8734139a35b524af0c29305122b19bcbffb/test/functional/search_api_test.rb#L148-L150

Then, we could expand the API method or create a new one to accommodate this new usage, and finally, change the view to make the right call (only when used in this controller action). Make sense?

**Comment by sukhbir-singh** [comment]
Can I try this?? 
I will take help of mentors and will ask questions if needed as this task might be a bit complex :sweat_smile:

**Comment by sagarpreet-chadha** [comment]
Hi @sukhbir-singh ! This sounds awsome 😄  !
Would be happy to help you 🎈 👍  !

**Comment by jywarren** [comment]
that would be great, thank you!!!

**Comment by sukhbir-singh** [comment]
Thank you @jywarren and @sagarpreet-chadha for assigning this task. Solving this really helped me in getting more familiar with the codebase specially testing and API part. :blush: :v: :bulb: thanks..!
