### ISSUE TITLE
Errors while running tests locally . 

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#2611]
**All tests error-ed when running `bundle exec rake test:all` .**

Example error :  

<img width="1250" alt="screen shot 2018-04-11 at 7 48 04 pm" src="https://user-images.githubusercontent.com/14952645/38622703-69a3e380-3dc1-11e8-883d-a10ebaafd251.png">

Anyone getting same error ?
`ActiveRecord::StatementInvalid:         ActiveRecord::StatementInvalid: SQLite3::ConstraintException: NOT NULL constraint failed: rusers.created_at: INSERT INTO "rusers" ........`

**Comment by sagarpreet-chadha** [comment]
I fixed this by adding : 
**`created_at: <%= Time.now %> `
`updated_at: <%= Time.now %>`**

this to **`rusers.yml`** . 

Is anyone else facing this problem ?

Thanks !

**Comment by jywarren** [comment]
hmm, want to open up a PR with this, and I can try it out locally? Thank
you!!

On Wed, Apr 11, 2018 at 9:31 AM, Sagarpreet Chadha <notifications@github.com

**Comment by sagarpreet-chadha** [comment]
Closing this . Solved 👍 .
