### ISSUE TITLE
Make Installation Instructions More Clear

### ISSUE THREAD

**Issue by waqargithub** [publiclab/plots2#2616]
### Please describe the problem (or idea)

I find the information given across readme.md and readme.environment to be confusing and, at times, conflicting.

1. I am not sure if information in readme.environment is still current and whether this file is still to be used. 

2. I think having one consolidated file with all installation related instructions would provide a clearer path to install and set up the environment.

> What happened just before the problem occurred? Or what problem could this idea solve?

This idea could make installation instructions clearer for people trying to join this project.

> What did you expect to see that you didn't?

I expected to see one file that would have installation instructions, and required revision numbers.

### Please show us where to look

https://github.com/publiclab/plots2/blob/master/README.environment

https://github.com/publiclab/plots2/blob/master/README.md

### What's your PublicLab.org username?

waqargithub

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by waqargithub** [comment]
I am happy to work on this issue with someone from the project team.

**Comment by jywarren** [comment]
Hi, @waqargithub thank you! We'd love to come up with a list of things that could be improved. @publiclab/reviewers this kind of input is really valuable as we've seen the site and docs for long enough that we forget what it's like to see them with fresh eyes. 

We used to have a very long README.md, but we heard from people that it was bewildering. So now we have most of our docs in `/doc/`. 

https://github.com/publiclab/plots2/blob/master/README.environment is indeed VERY old. I think we should perhaps just point it to the main README.md and the /docs/ files?

**Comment by siaw23** [comment]
i very much agree with @waqargithub, file organisation and instruction are a bit discouraging. i also feel we should remove unused README's, keep a current, brief one at the top level. i have seen this in the main README for example:


> (optional, not recommended) Install solr engine rails generate sunspot_rails:install
> (optional, not recommended) Start the solr server in foreground by using bundle exec rake sunspot:solr:start
> (optional, not recommended) Index your search database in solr server using bundle exec rake sunspot:reindex

well, if it's optional and *not recommended* why do we need it? @jywarren

**Comment by jywarren** [comment]
Let's make a checklist! Many of these could be completed as part of
first-timers-only issues. Removing Solr from the readme is a great example.
Same with unused readmes! This will be a continuing process but thanks so
much for listing these out -- let's start to chip away at them!

**Comment by jywarren** [comment]
And apologies for returning to this a bit late! @souravirus if you'd like
to use one of these as an opportunity to try making a first-timers-only
issue, I'd be happy to help review it. Thanks everyone!

**Comment by Souravirus** [comment]
I would be happy to make my first first-timers-only issue. So, what should I start with? Is that making issue for removing Solr from the readme?

**Comment by Souravirus** [comment]
Hey @jywarren, I made the first-timers-only on removing of the obsolete code on #2729. Please check it out once.

**Comment by gauravano** [comment]
Hi everyone, thanks for great suggestions. I think in a year, we have improved a lot and so closing this issue. But, you are always welcome to open a new issue, if you want to add on a new suggestion/ highlight an issue/bug.
