### ISSUE TITLE
Update Leaflet Blurred Location to v1.1.12

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2625]
@mridulnagpal and I noticed PublicLab.org is running on v1.1.5 of Leaflet Blurred Location (https://github.com/publiclab/leaflet-blurred-location/):

https://publiclab.org/lib/leaflet-blurred-location/package.json

Although there's `v1.1.12` now available: https://github.com/publiclab/leaflet-blurred-location/releases

We're not pegged to a version, but to the master branch:

https://github.com/publiclab/plots2/blob/c763373a4004c8c346dbc344b18217bd3003722d/bower.json#L27

@icarito can you see if we need to run `bower update` to get the latest? Or do we need to peg to a version like `#~1.1.12` where it says `#master`?

Thanks all!

**Comment by icarito** [comment]
I'll figure out how bower works. I'd be surprised if "#master" is a valid tag anywhere outside git.

**Comment by icarito** [comment]
Oh I see bower defaults to github urls! Now I get it.
I think the problem is we're not doing `bower update` when we build the container.

**Comment by jywarren** [comment]
Resolved, thank you!!!
