### ISSUE TITLE
Banned users with location tags appear on the /people map

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2628]
### Please describe the problem (or idea)

> What happened just before the problem occurred?

The map of /people shows markers for banned users, for instance https://publiclab.org/profile/Evataylor. I have already deleted the location tags off of two other banned users that were showing up on our map before reporting this as a bug. 

> What did you expect to see that you didn't?

I expected to see all real people on our map at publiclab.org/people

### Please show us where to look

https://publiclab.org/profile/Evataylor 
https://publiclab.org/people (that profile is near 0,0 off the west coast of africa)

### What's your PublicLab.org username?

> This can help us diagnose the issue: 
Liz

**Comment by sagarpreet-chadha** [comment]
I would like to solve this one  :world_map:  :balloon: .

**Comment by jywarren** [comment]
Always with the good emojis, Sagarpreet! :-)
