### ISSUE TITLE
Embedded document missing?

### ISSUE THREAD

**Issue by gretchengehrke** [publiclab/plots2#2631]
### Please describe the problem (or idea)

I went to this page: https://publiclab.org/wiki/gardening-toolkit-case-study. On it, I expected to see an embedded file, but instead saw saw the message "That Page Does Not Exist" embedded in the wiki page. It's not an issue with the wiki page itself, since it loads fine and has other content around where that embedded file was. 

### Please show us where to look

https://publiclab.org/wiki/gardening-toolkit-case-study

### What's your PublicLab.org username?

gretchengehrke

### Browser, version, and operating system

Chrome, macOS High Sierra
<img width="1082" alt="screen shot 2018-04-18 at 12 50 17 pm" src="https://user-images.githubusercontent.com/10854595/38948415-8b0ab0d4-430d-11e8-93ec-79c4969be87f.png">

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by gretchengehrke** [comment]
@icarito Jeff suggested that I ping you about this issue. Thanks!

**Comment by icarito** [comment]
Thanks I'm checking it out - the pdf itself is there, but the pdf viewer isn't found - will fix.

**Comment by icarito** [comment]
Some other files were missing in /public directory. I copied the pdf.js file and also the *.html files. Not sure the others are needed? @jywarren is `editor/` used?

```
$ diff . /srv/plots/production/public
Common subdirectories: ./assets and /srv/plots/production/public/assets
Only in /srv/plots/production/public: BFE754E9F28D0D96840680D5BA3E68BD.txt
Only in /srv/plots/production/public: downloads
Only in /srv/plots/production/public: economist.html
Only in /srv/plots/production/public: editor
Only in /srv/plots/production/public: giving.html
Only in /srv/plots/production/public: google6f6b5070e97473ee.html
Only in /srv/plots/production/public: googlef62adec67ea562e9.html
Common subdirectories: ./images and /srv/plots/production/public/images
Only in /srv/plots/production/public: invalid_mx_domains.txt
Only in /srv/plots/production/public: ks.html
Common subdirectories: ./lib and /srv/plots/production/public/lib
Only in /srv/plots/production/public: maintenance.html
Only in /srv/plots/production/public: pdf.js
Only in /srv/plots/production/public: prototype
```

The page in question has been fixed, thanks for the heads up @gretchengehrke !

**Comment by gretchengehrke** [comment]
Thanks @icarito!
