### ISSUE TITLE
Button style doesn't match  

### ISSUE THREAD

**Issue by Gauravano** [publiclab/plots2#2632]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/notes/_coauthored_notes.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/notes/_coauthored_notes.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Currently, in co-authored tab, buttons have different style as shown 

![style_diff](https://user-images.githubusercontent.com/20878070/38950111-1f670530-4362-11e8-98ea-daa73ee976c7.png)
 
Update lines https://github.com/publiclab/plots2/blob/master/app/views/notes/_coauthored_notes.html.erb#L50-L51
 
so that both buttons attain the same style i.e., Spam button should be of same size as Read more button.  

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by trqkkr** [comment]
I'll take a crack at it!

**Comment by flash00** [comment]
Hi, looks like all the first-time-only issues are covered. Would love to work on one when available. 😃

**Comment by Gauravano** [comment]
hi @flash00, thanks for showing great enthusiasm, I let you know if I came across any unclaimed first-timer issue. Thanks :smile:.

**Comment by Gauravano** [comment]
Solved in #2636

**Comment by flash00** [comment]
Great. I'll look forward to hearing from you.

**Comment by jywarren** [comment]
@flash00 -- I've opened one up at https://github.com/publiclab/plots2/issues/2651 if you'd like to take it?
