### ISSUE TITLE
Make link clickable on dashboard

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2638]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

The username on the dashboard is not redirecting to the user's profile. 
![image](https://user-images.githubusercontent.com/20972099/38966129-387fc142-439e-11e8-98b8-17a6966b1a29.png)

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file app/views/dashboard/_header.html.erb
Replace the line
https://github.com/publiclab/plots2/blob/8e71008f243b5592711ee4fb70ee219368f07237/app/views/dashboard/_header.html.erb#L34
with
    ``  <span class="hidden-xs hidden-sm"><%= t('dashboard._header.welcome') %><span class="hidden-md">,<b><a href="/profile/"> <%= current_user.username %></a></b></span>!</span> 
``

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by renatavmaraj** [comment]
I can help with this!

**Comment by RandomNingen** [comment]
Hello I am new to open source. I was looking around for something I could work on. Could I please give this issue a try?

**Comment by chiranjev** [comment]
I would like to resolve this issue if someone has not made any pull request.

**Comment by SidharthBansal** [comment]
Hi @chiranjev there is already a PR on this issue. You can try other first timer issues
@RandomNingen thanks for the pr
