### ISSUE TITLE
Issue with Cloud9 Set-up Instruction or with Script

### ISSUE THREAD

**Issue by waqargithub** [publiclab/plots2#2646]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I used [these instructions](https://github.com/publiclab/plots2/wiki/Simple-Installation-for-Cloud9) to try to set up an environment on Cloud9. My attempt was unsuccessful.

> What did you expect to see that you didn't?

1. I expected to see a field for "Clone from Git or Mercurial URL" before clicking on Create Workspace. In practice, I first clicked on Create Workspace and then saw that field.

2. I expected to be prompted for my user name but did not see that happen. Looking elsewhere in instructions shows a script install_cloud9.sh in Step 5. I typed ./install_cloudnine.sh at the command prompt, which did then ask me for my user name and run the script.

3. The script printed Done! and asked me to run rails s -b $IP -p $PORT. When I ran this command, it told me that my Ruby version is different from what is in the Gem file (see screenshot attached). Since the set up is being done automatically, I wonder if something needs to be updated in the script. In the screenshot, I switched back to Ruby 2.3.4 to show the message I initially got before changing the ruby version.

4. I used comand rvm 2.3.7 to change my Ruby version. When I entered rails s -b $IP -p $PORT I got an error message saying that command was not found. I also noticed that there are errors that occurred (see screenshot attached).

### Please show us where to look

https://github.com/publiclab/plots2/wiki/Simple-Installation-for-Cloud9

### What's your PublicLab.org username?

waqargithub

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

![image](https://user-images.githubusercontent.com/5306998/39067181-6cb7a6d2-449d-11e8-827a-a99a9d57cdb9.png)

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hmm, this is not good, thanks for so carefully documenting it! I believe the Ruby version may be one of the big issues. After running `rvm 2.3.7`, perhaps you need to run `bundle install` to get the gems in that environment?

**Comment by jywarren** [comment]
We could modify these two lines to improve that and perhaps add a `bundle install` step if needed?

https://github.com/publiclab/plots2/blob/65b289c131be6ad7186be2b35952900c62a45f37/install_cloudnine.sh#L5-L6

**Comment by rtrunkhill** [comment]
how does this look?
```
read -p "Enter your cloud9 username: " un
rvm install ruby-2.3.7
source $(rvm 2.3.7 do rvm env --path)
rvm use 2.3.7
bundle install
sudo apt-get update
sudo apt-get -y install imagemagick ruby-rmagick
npm install -g bower
bower install
bundle install --without production mysql
cp db/schema.rb.example db/schema.rb
cp config/database.yml.sqlite.example config/database.yml
rake db:setup
rake cloud9 username=$un
echo "Done! Run the application with 'rails s -b \$IP -p \$PORT'"
```

**Comment by jywarren** [comment]
oh awesome, does this work for you in cloud9?

**Comment by rtrunkhill** [comment]
alright, it's all tested.  we dont need to add the extra `bundle install` we just need to change `rvm 2.3.7` to `rvm use 2.3.7` and add a `gem install bundler` before `bundle install --without production mysql`  I'll put the PR through now.  I got to this to work from scratch on my machine

**Comment by gauravano** [comment]
Closing this as we don't use Cloud9 service anymore. Thank you!
