### ISSUE TITLE
[ENHANCEMENT] Need for making moving forward button on stats page

### ISSUE THREAD

**Issue by Souravirus** [publiclab/plots2#2650]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**
### Please describe the problem (or idea)
We already have a looking back button by week, month and year. 
![screenshot from 2018-04-22 14-21-04](https://user-images.githubusercontent.com/17192149/39093158-7e46c24c-4638-11e8-80c2-d7697b82a234.png)
But to move again forward by years, months and weeks, we have to click the back button of the browser which is not the optimum way for a website. So we should introduce a moving forward button in this page.

### Please show us where to look

https://publiclab.org/stats

### What's your PublicLab.org username?

souravirus

### Browser, version, and operating system

Firefox 59.0.2 , Ubuntu operating system

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.
