### ISSUE TITLE
Skylight Performance Tracking

### ISSUE THREAD

**Issue by siaw23** [publiclab/plots2#2660]
Hi @publiclab/reviewers, [Skylight](https://www.skylight.io/) is providing free performance tracking for open source projects. We have nothing to lose but a lot to gain by joining it. I found that out at RailsConf last week and thought of Plots2. What do you say to adding Skylight to this growing project to track and fix performance issues as they come in?

**Comment by jywarren** [comment]
This looks great. Let me see if we can get signed up quick.

**Comment by siaw23** [comment]
that'd be awesome. as a follow up. i wanted to add that in fact if you search for `rails performance testing` the first link points to a Rails `v3.2.13` guide. I bet you can't find the same guide for a Rails 4 app let alone for a Rails 5 app! @jywarren

**Comment by jywarren** [comment]
I think the performance testing project may have started when we were on Rails 3! It was our oldest PR :-)

**Comment by siaw23** [comment]
that explains it ;)
