### ISSUE TITLE
Marking wiki with one revision as spam

### ISSUE THREAD

**Issue by Gauravano** [publiclab/plots2#2662]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
 I just saw a spam wiki with one revision, and moderators can't mark it spam.

hi @jywarren , here is the wiki [link](https://publiclab.org/wiki/escorts-services-in-hyderabad-sexy-housewife-call-girls-in-hyderabad-busty-and-hot-married-girl-photos), please delete it for now. Thanks.

**Comment by jywarren** [comment]
Ah - so moderators can mark one revision as spam, i believe - shall i make you a moderator to test? (ok, done).

Should we make this more clear?

**Comment by Gauravano** [comment]
@jywarren no one can mark wiki with one revision as spam but moderators can delete the wiki having one revision. I guess that would solve this issue. What do you think?

**Comment by jywarren** [comment]
Ah, i see. sorry, that seems like a long time ago that we implemented that 😄 

Well, I'm just wary about wiki deletion privileges, it's not undoable. What about putting a "flag" button as we now have on the dashboard, for reporting it to `moderators@publiclab.org`?

**Comment by rtrunkhill** [comment]
so i added this to view/like/_like.html.erb : 
```        
<% if current_user.role == "moderator" || current_user.role == "admin" %>
          <li rel="tooltip" title="Flag as spam." class="btn btn-sm btn-default btn-flag-spam-<%= node.id %>" href="mailto:moderators@publiclab.org?subject=Reporting+spam+on+Public+Lab&body=Hi,+I+found+this+item+that+looks+like+spam+or+needs+to+be+moderated:+<%= node.title.gsub(/ /,'+') %>+https://publiclab.org/n/<%= node.id %>+by+https://publiclab.org/profile/<%= node.author.username %>+Thanks!">
          <i class="fa fa-flag"></i>
          </li>
        <% end %>
```
but it trips this error: 
```
ERROR["test_disallow_marking_a_wiki_revision_as_spam_when_its_the_only_revision", Minitest::Result, 5.9919795002788305]
 test_disallow_marking_a_wiki_revision_as_spam_when_its_the_only_revision#Minitest::Result (5.99s)
```

do you want the spam button to work for everyone? or it's just for mods and admins modify the test to not include those user roles?

**Comment by Gauravano** [comment]
hi @jywarren sorry for responding late on this one. yes, flagging a wiki seems fine to me! @rtrunkhill Thanks for taking this, actually marking a wiki with single revision was giving us an error, so we decided to not let anyone mark it as spam. Instead, we now show an alert to contact "admin" for its deletion. As the message is well conveyed via that alert to moderators. 

You can make this flag available to all, as this flag is nothing but triggering an email so, no harm. The test shouldn't fail due to just link addition, that's strange. If you can open a PR for the above changes, we might be able to help you better. Thanks :smiley:

**Comment by rtrunkhill** [comment]
alright i made some minor syntax changes it's passing all the tests and opens up an email properly:
```
    <a rel="tooltip" title="Flag as spam" class="btn btn-sm btn-default btn-flag-spam-<%= node.id %>" href="mailto:moderators@publiclab.org?subject=Reporting+spam+on+Public+Lab&body=Hi,+I+found+this+item+that+looks+like+spam+or+needs+to+be+moderated:+<%= node.title.gsub(/ /,'+') %>+https://publiclab.org/n/<%= node.id %>+by+https://publiclab.org/profile/<%= node.author.username %>+Thanks!">
      <i class="fa fa-flag"></i>
    </a>
```
![image](https://user-images.githubusercontent.com/28711410/41510360-0dbdd89c-7218-11e8-8690-a17d155c2510.png)

putting in the PR now

**Comment by rtrunkhill** [comment]
i got a dangerbot error even though rake tests passes locally

```There was an error with Danger bot’s Junit parsing: undefined method `value’ for nil:NilClass```

I updated the master (man that thing moves fast) and created a new branch and added the changes.  all tests still pass so i'll give it another sho with a different PR
