### ISSUE TITLE
Username in wiki/revisions pointing to /people/ instead of /profile/

### ISSUE THREAD

**Issue by Gauravano** [publiclab/plots2#2664]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/wiki/revisions.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/wiki/revisions.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

Change the link at line https://github.com/publiclab/plots2/blob/master/app/views/wiki/revisions.html.erb#L26 to 
href="/profile/<%= revision.author.name %>"

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by jolivadese** [comment]
Can i take this one?

**Comment by sagarpreet-chadha** [comment]
That would be great @jolivadese 😄 ! Feel free to ask here in case of any doubt .
Thanks 🎈 !

**Comment by jolivadese** [comment]
The line 26 already has the value href="/profile/<%= revision.author.name %>". What should i do?

**Comment by Gauravano** [comment]
hi @jolivadese, I just checked again it's currently  `href="/people/<%= revision.author.name %>"` as you can see 

![line26](https://user-images.githubusercontent.com/20878070/39399415-da6365b0-4b3a-11e8-8432-25e042e7e31e.png)
 and required one is ` href="/profile/<%= revision.author.name %>"`. I hope it's clear now : )

**Comment by jolivadese** [comment]
I've finished!
