### ISSUE TITLE
PLANNING ISSUES: Email Integration 

### ISSUE THREAD

**Issue by namangupta01** [publiclab/plots2#2672]
### Please describe the problem (or idea)
> Planning various issues related to Email Integration

- [ ] Reply to comment by email using mailman gem
- [ ] Adding whenever gem for cron job for Weekly/Daily/Monthly Digest
- [ ] Designing Mailers for Email Digest
More to come......

**Comment by namangupta01** [comment]
@ViditChitkara @Gauravano Kindly add more issues in the list by breaking them.

**Comment by jywarren** [comment]
Awesome :-))))

**Comment by ViditChitkara** [comment]
related issues:- #2681 , #2668

**Comment by ViditChitkara** [comment]
We also need to discuss the UI/UX for "reply by email to  comments" feature.

**Comment by jywarren** [comment]
agreed and there's a good github article on this. GitHub emails are a good
design reference.
https://blog.github.com/2011-03-10-reply-to-comments-from-email/

**Comment by Gauravano** [comment]
Related issue #2667 

hi @jywarren, let us know when you would be free to discuss Email Integration with all of us. Thanks.

**Comment by jywarren** [comment]
sometime later this week, perhaps! Thursday? Can you check
inyourowntime.info to propose a time? Thank you!

**Comment by Gauravano** [comment]
@jywarren Are you free at http://www.inyourowntime.info/2018-05-03_22.00_Asia.Kolkata ?

**Comment by jywarren** [comment]
Yes, i am! I'll see you then!

**Comment by jywarren** [comment]
Merging into #2104!
