### ISSUE TITLE
Role based code cleanup

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#268]
Until #264 is pursued, it might be a good idea to compress as much of the role based logic as possible into one place.

For example, we could make partial templates which render the following: https://github.com/publiclab/plots2/blob/fe2ba03bc05e937b0b10851824732bc2e791c525/app/views/users/profile.html.erb#L6-L17

All of the if/then logic would move into the partial, and that highlighted section would include the partial. That allows us to change how the template logic works later in one place. If we have a few partials, they can all go in the same directory under maybe `templates/roles/`.

Another copy/paste logic can be seen here: https://github.com/publiclab/plots2/blob/ad7fa8d4970a4a831d7eea626be4e27cd295dbf7/app/controllers/admin_controller.rb#L6-L13

If this were Python, I'd write a decorator which checks user credentials and returns an error if they are not met. Since this is Ruby, I don't know a good way. Here's what I'd do in my naivety: write a function which takes the user and required role in; if there is a failed match, it would set the flash error and return False. Then you could copy paste `if not has_permission(user, 'admin') return` or something more Ruby-like.

The above is a little ugly, but such a function could probably be rewritten for RBAC later without needing to make wide sweeping code changes (though this change itself would be such a wide-sweeping code change).

**Comment by btbonval** [comment]
I just noticed that the highlighted section of the partial has two different ways to check if a user is defined. `if @user.user.nil? && current_user` and `if @user.user && current_user`. This already shows one of the problems with not being DRY.

If we write a `has_permission` function, it should contain the check to see if `@user` is a proper user, however that is decided. Then we can call the `has_permission` function directly from the partial template. That'd make the code a little more sane as well.

**Comment by btbonval** [comment]
Alright it turns out the differences are intentional. Misread that one is looking for no, the user does not exist and one is looking for yes, the user does exist. At any rate, same logic still applies for DRY to prevent the possibility of copy/paste mistakes :)

**Comment by jywarren** [comment]
We should consolidate using this code: https://github.com/publiclab/plots2/blob/69ff57056de33e6388e40490bb7bfe8be72a7946/app/helpers/application_helper.rb#L3

**Comment by gauravano** [comment]
@jywarren please update the issue. Thanks!

**Comment by jywarren** [comment]
I'll open a new issue! I think we can build out our model code to make this simpler, without yet planning out a full multi-role system. If we go there, then we might merge this into profile tags!
