### ISSUE TITLE
Contemplate how interesting Xose's website front page is!!

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2692]
### Please describe the idea

I wanted to share https://imvec.tech/ by https://publiclab.org/profile/imvec because i find it visually interesting! Enjoy :)

I couldn't find Xosé's github account, if anyone knows if it exists, please add, thank you!

**Comment by chanjess** [comment]
Hi @ebarry 
I'm new here. I wanted to understand what this is. Is Xose a regular contributor who created all this?

**Comment by ebarry** [comment]
Hi @chanjess , yes that's it! Xose is a great person in Spain, part of many initiatives that are linked from his public lab profile above. Did you have any thoughts or opinions about the video-rich website design he has?
