### ISSUE TITLE
Design and UI discussion of subscription/follow features, nomenclature

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2693]
Copying in from #2104 -- 

### Patterns

* Let's standardize our use of the term "subscribe" and "follow". 
  * We also use subscribe when we suggest that people "subscribe to the Community Science Forum".  However, this page is terribly out of date: https://publiclab.org/subscribe
  * Just for reference, we use "sign up" in relation to the newsletter and the website itself. 
  * "Follow" isn't really used anywhere else and I suggest we change all instances of "Follow" to "subscribe"
  * What do you think?
* There are an emerging set of ideas about pinning main research areas to the top of the dashboard https://github.com/publiclab/plots2/issues/2076, and about showing clusters of related tags to help people see the dimensions of a research area https://github.com/publiclab/plots2/issues/1502
* what are other patterns we could aspire to?

### Overview of how people are presented with information about and control over their subscriptions

The places on our site where one can control subscriptions vary widely: 

**Primarily:** 

* in the unlabelled-except-for-person-emoji "account" dropdown menu, there is a link to https://publiclab.org/subscriptions

<img width="294" alt="screen shot 2018-01-24 at 5 05 07 pm" src="https://user-images.githubusercontent.com/161439/35361733-77055766-0130-11e8-8fc8-73ae3976dc61.png">

* That link takes you to the dedicated page that is personalized to your user account https://publiclab.org/subscriptions

<img width="748" alt="screen shot 2018-01-24 at 4 34 45 pm" src="https://user-images.githubusercontent.com/161439/35358407-8dc7daa2-0124-11e8-8a5b-b9acb3f6a34e.png">

* on the tag page where all tags are listed https://publiclab.org/tags, you have the option to "follow" AKA `subscribe` and to see how many people are already following that tag. You can also sort by "subscription to bring all the tags you already follow to the top. 

<img width="714" alt="screen shot 2018-01-24 at 4 34 01 pm" src="https://user-images.githubusercontent.com/161439/35358363-6dd24926-0124-11e8-8080-b7c57794f1d2.png">

* on tag pages such as https://publiclab.org/tag/kite-mapping, you are offered the option to "Follow" the tag, and are also offered the unique opportunity of getting the RSS feed (is this shown anywhere else? should it be?)

<img width="1158" alt="screen shot 2018-01-24 at 5 51 35 pm" src="https://user-images.githubusercontent.com/161439/35361414-491b86a0-012f-11e8-839f-b5298fa5eb2b.png">

**Comment by chanjess** [comment]
This is very cool and interesting to read. What are the updates on this? I think that the consolidation of "follow" and "subscribe" makes sense and is intuitive.

**Comment by ebarry** [comment]
Here's an update that makes great progress toward this, a new listing of the largest research areas on publiclab.org in the sidebar: 
<img width="1080" alt="screen shot 2018-10-05 at 6 17 03 pm" src="https://user-images.githubusercontent.com/161439/46562636-115ca280-c8cb-11e8-92f5-17b7c2440524.png">
Clicking on a blue topic offers the ability to "Follow" right from the dashboard.

**Comment by jywarren** [comment]
Closing, as we've made tons of progress and are now using "follow" everywhere!
