### ISSUE TITLE
UI, design and testing for publiclab digest feature

### ISSUE THREAD

**Issue by ViditChitkara** [publiclab/plots2#2694]
Part of #2104 

## Design
A possible design for the digest could be:-
![digest-1](https://user-images.githubusercontent.com/22616017/39665881-8899da7e-50b8-11e8-9bc8-f3f53de76f3b.png)

## Testing
* As the digest feature comes online, we could test it with the help of UserTag `digest:weekly` and `digest:daily` . 
* In the initial stages, these tags will be assigned to a few reviewers and maintainers.
* Only those people having such tags would receive digest emails. Subsequently, we could expand this to a larger lot of people.

**Comment by ViditChitkara** [comment]
@jywarren if we could add more details to it. (Please edit this, if there is anything missing)
Once we finalize the design I could create a pr for this.

**Comment by jywarren** [comment]
Hi, is this in the email or on the digests page at https://publiclab.org/subscriptions/digest ?

I think probably the initial design we need to come up with is for email, and I think we ought to start with the simplest -- just a bulleted list. Then we could think about how to organize things by, say, tag?

What if we also thought about a method for organizing a set of posts by tag, generically -- so like `Tag.group_by_tag(@nodes)` which returns an array of arrays... this could be used to generate separate lists in HTML or in the email itself? What do you think?

**Comment by ViditChitkara** [comment]
Hi, this is the email design. I have some code ready for this. Sure, we could start with something basic, figure out the functionality at the backend and then finally reach at this design.
Talking about the tag thing, may be we could add some sort of material chips or tooltips or something to show the tagnames for each of the nodes?
What do you say?

**Comment by jywarren** [comment]
I think a basic bullet list of updates sounds great -- maybe loosely
modeled on the GitHub pulse or activity dashboard?

Although sorting by tag sounds interesting, perhaps showing some images
from the posts is a good initial step that'd make a difference in getting a
nice-looking digest. So after the basic functionality we could try showing
an image from the most-liked post that week, or something? Let's see how
that does, and then think through next steps.

Thanks!!
