### ISSUE TITLE
PLANNING ISSUE: Upgrade to Rails 5.0

### ISSUE THREAD

**Issue by Souravirus** [publiclab/plots2#2714]
This is only an initial planning writeup. 

**Things to be done before the upgrade**
- [x] Making a new branch for the upgrade.
- [x] Working on tests

**Things to be done during the transitions**
- [x] Changing the Gemfile
- [x] Working for the Gems which are not available
- [x] Adding tests where there is no availability of a good test coverage 
- [x] using http://railsdiff.org/4.2.10/5.0.7
- [x] fixing all errors, failures and depreciation warnings
- [x] following the steps of http://guides.rubyonrails.org/upgrading_ruby_on_rails.html
- [x] 4.1 Ruby 2.2.2+ required
- [x] 4.2 Active Record Models Now Inherit from ApplicationRecord by Default

**Things to be done after the transitions**
- [ ] Upgrading documentation and readme etc., about the changes done
- [x] Fixing operational problems if any
- [x] Removing obsolete code if any

@jywarren  @siaw23 @publiclab/reviewers Please verify these steps and please comment any other steps that you want to add.  
Excited to start coding.
It would be nice if any @publiclab/reviewers could add some labels to this issue like gsoc, planning, help wanted, etc.

**Comment by siaw23** [comment]
Looks good to me except there's no mention of system tests. Might be out of the scope of this project but it'll mean we have to tread carefully. Also it'll be nice to get a test coverage for this otherwise it'll look like we don't know what we're doing. This could break or make things, tests coverage will help us gauge our confidence for refactoring. I'd like to remind you to do incremental upgrades instead of big jump between upgrades. RailsDiff will help with that.

**Comment by Souravirus** [comment]
Yeah I will surely go for an incremental upgrade. I think I should give some days for test coverage first. I should see if there are places which are out of tests and add tests to them. What say?

**Comment by jywarren** [comment]
This is looking great. Maybe make 2 categories for things that can be done
in advance of the switch vs. things which can only happen after? (and/or
things that can happen in transition if any exist?)

Looking great!

**Comment by Souravirus** [comment]
Hey @jywarren modified the issue as you wanted. Please check it once and comment any other things you want to add in the issue. Thanks!!

**Comment by jywarren** [comment]
Great! And @Souravirus you should be a reviewer! Have you made a `first-timers-only` issue before (forgive me if I forgot...). I'll invite you now, and I'm sure you've seen this page but please give it a look-over again as we encourage reviewers to be welcoming and helpful to newcomers!

http://publiclab.org/software-outreach

I'll invite you to be a reviewer :-) and happy to review a FTO issue if you want to try making one!

**Comment by Souravirus** [comment]
thanks @jywarren for making me a reviewer. No, I have still not made a `first-timers-only `, but would love to make one. when I find any  first-timers issue in my project.

**Comment by jywarren** [comment]
Great! I'm happy to help. It's often the case that you have to break down
your work to find some good ones, and it's really worth it to expand our
team!

**Comment by jywarren** [comment]
Are we done with this issue now? Any of these follow-ups you want to try? Perhaps some could be good first-timers-only issues. 👍 👍 👍

**Comment by Souravirus** [comment]
Yeah this issue is done. I had sent a PR related to a follow up fix on #2794. I had a update in README.md where I thought to update the testing command to 'rails test -d'. I will also serve as a first timer issue. What do you think @jywarren

**Comment by jywarren** [comment]
Sure! And you can close this once you're ready. What are you thinking of as
next steps? 5.x? :-)

**Comment by Souravirus** [comment]
I will be working on upgrade of rails 5.1 upgrade

**Comment by Souravirus** [comment]
ok I am opening a new first timers issue related to the testing command.

**Comment by jywarren** [comment]
Want to close this then? Maybe you should open a new milestone to track your progress for the summer now that you've completed this planning issue? That way it can be a collection of loosely related issues.

**Comment by Souravirus** [comment]
Yeah closing
