### ISSUE TITLE
Search API error after installation

### ISSUE THREAD

**Issue by E-L-T** [publiclab/plots2#2716]
### Please describe the problem (or idea)

After installation we ran the tests, and we got this error : 
"701 tests, 2061 assertions, 0 failures, 9 errors, 0 skips"

> What did you expect to see that you didn't?
no errors

### Browser, version, and operating system
Firefox 59.0.2 (64 bits), mac os 10.13.3

**Comment by E-L-T** [comment]
After running the tests, we got 9 errors. Here is the first one. The 8 others concern the same file, app/models/node.rb
![capture d ecran 2018-05-11 a 21 40 46](https://user-images.githubusercontent.com/29131404/39943806-7dae8140-5564-11e8-82ac-1d28aa0ac5f9.png)

**Comment by jywarren** [comment]
Hi, sorry it took me a little while but I left a comment on your PR with a proposed fix. I hope this gets us closer, THANKS SO MUCH!!! 👍 👍 👍

**Comment by jywarren** [comment]
Glad to hear in #2717 that this isn't a problem anymore!
