### ISSUE TITLE
Tag pages have non-standard headers on each tab

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2718]
### Please describe the problem (or idea)

> What happened just before the problem occurred?

It's really great to have a direct link to all the Contributors to a tag, but the contributor tab on Tag Pages is missing the standard header that is present on other tabs of the tag page. See below GIF: 

Notice that all tabs on the Tag Page have the same header EXCEPT for the Contributors tab. Here's what's different: 
- sidebar is present on the Contributors tab (the other tabs don't have it)
- there is no Wiki Preview and "Read More" link at the top of the page, instead the graph is the topmost item on the page
- the tab structure itself is missing, thwarting attempts to navigate back to the main Tag Page from Contributors Tab, ESPECIALLY when arriving at the Contributors Tab via a direct link. 

![tag-page-headers](https://user-images.githubusercontent.com/161439/39925995-cffdbf06-54fb-11e8-9b6a-240fb724f6bf.gif)
-

> What did you expect to see that you didn't?

- no sidebar
- standard header with other tabs on Tag Page
- presence of Tabs for navigation through the entire Tag Page

### Please show us where to look

https://publiclab.org/contributors/pm

### What's your PublicLab.org username?

> This can help us diagnose the issue: liz

**Comment by ebarry** [comment]
Oh! i believe @Gauravano fixed this back in January! Scroll down to the bottom of https://github.com/publiclab/plots2/commits/master/app/views/tag/_contributors.html.erb -- can we bring this back?

**Comment by ebarry** [comment]
OMG @jywarren just found out what was up with this: 

There are two pages:
* https://publiclab.org/contributors/tag/balloon-mapping -- already working perfectly!!!!
* https://publiclab.org/contributors/balloon-mapping -- the old style that every tag page links to in the tab, that i filed this issue about!

@jywarren please advise on this :)

**Comment by jywarren** [comment]
Let's merge the best parts of each, and have /contributors/tag/_____
redirect to /contributors/_______ in config/routes.rb --

Things to preserve:

* tabs
* nice 3-panel "stats"
* nice new graph
* no sidebar
* preview of wiki page and 'Read more' at top

Anything else?

**Comment by oorjitchowdhary** [comment]
Can I take this up?

**Comment by jywarren** [comment]
sure, yes please!

**Comment by jywarren** [comment]
Closing and merging into https://github.com/publiclab/plots2/issues/6307 after the major tag page overhaul!
