### ISSUE TITLE
Remove extra link at top of /Questions

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2719]
### Please describe the problem (or idea)

> what problem could this idea solve?

There are redundant links at the top of /question: 

<img width="922" alt="screen shot 2018-05-11 at 9 24 31 am" src="https://user-images.githubusercontent.com/161439/39926421-2c60cbb6-54fd-11e8-9d0a-a89cc73bbfa2.png">

> What did you expect to see that you didn't?

I would expect to see the line "New to Public Lab? Learn how this works »" only once. 

Please remove one line. 

### Please show us where to look

https://publiclab.org/questions

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hi! I think this is already solved but not deployed. Good catch! Should be published this afternoon. Thanks!
