### ISSUE TITLE
Add "Search by tag" text entry to the top of https://publiclab.org/contributors

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2720]
### Please describe the idea

> What problem could this idea solve?

https://publiclab.org/contributors makes sense as the home for contributors on publiclab.org. But right now, it only has 5 hard coded topic areas. 

> What did you expect to see that you didn't?

I would like to see a "Search by tag" text box such as what is already at the top of https://publiclab.org/tags (or the tag search on https://publiclab.org/questions that actually seems to have an autosuggest that preforms better than the version on /tags -- does this need to be broken out as another issue?) that would result in seeing the very nice contributor page for a tag, for example: https://publiclab.org/contributors/pm. 

A second thing i expect to see is that contributor pages have the same header across all tabs, described in https://github.com/publiclab/plots2/issues/2718

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

liz

**Comment by rtrunkhill** [comment]
I resolved this issue:
![image](https://user-images.githubusercontent.com/28711410/41674802-d5e81288-7475-11e8-8b4b-a29507379952.png)


but im having issues passing any [tests](https://github.com/publiclab/plots2/issues/2870) right now.  as soon as i get that resolved i'll submit the pr here

**Comment by jywarren** [comment]
wow, this is awesome! great, i see you opened an issue at
https://github.com/publiclab/plots2/issues/2870

**Comment by rtrunkhill** [comment]
I'm getting the same issue as [here](https://github.com/publiclab/plots2/issues/2542#issuecomment-398495437) with this test:
```
  test "should use existing node body as template in post form based on param 'n'" do
    UserSession.create(users(:bob))

    get :new,
        params: { 
        tags: 'one,two',
        n: nodes(:blog).id
        }

    assert_response :success
    assert_select '#taginput[value=?]', 'one,two'
    assert_select 'textarea#text-input', nodes(:blog).body
  end
```

if i take that test out, it passes all the tests.  so i'll submit and see what you guys want to do with it.  also see the syntax error in the bottom right %[count} ? 

![image](https://user-images.githubusercontent.com/28711410/41682260-1c4043d4-748c-11e8-93bf-67d8d121ab65.png)

I tried to make the change to `config/locales/views/tag/contributors/en.yml` on line 12 `
people_watching_tag: "%{count} people are watching this tag" 
` but for a reason i havn't figured out yet, i'm can't seem to make changes to that file.  that syntax error is live in production

**Comment by ebarry** [comment]
hi all! Excited to see this progress. I do see the syntax error is still happening. Also, the "Search by tag" box has not yet been added at the top. Anything i can do to help?

**Comment by jywarren** [comment]
A lot of this functionality has been moved into the /stats system and the graphs are no longer available. I'm going to close this but can discuss further if needed! Thanks!
