### ISSUE TITLE
Note people as "first-time poster" to encourage ppl to be friendly to them?

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2722]
GitHub now shows this little notice for first-time PR openers, see: https://github.com/publiclab/plots2/pull/2713

![screen shot 2018-05-11 at 2 06 19 pm](https://user-images.githubusercontent.com/24359/39939536-97db55e2-5524-11e8-8dbf-5c86b7e2b08c.png)

@publiclab/community-reps @publiclab/designers do you think we ought to show something similar in a not-too-loud place on posts by newcomers on PublicLab.org? 

For example this newcomer hasn't added much info -- would a reminder that it's their first post be helpful? 

We could show a small link next to their username, maybe? And we can tell because they'd have `@user.notes.length == 1`

https://publiclab.org/notes/saraortiz1/05-04-2018/sunlight

![screen shot 2018-05-11 at 2 10 09 pm](https://user-images.githubusercontent.com/24359/39939681-09ec96e6-5525-11e8-9c80-2a370f9e0566.png)

**Comment by robotscissors** [comment]
I am a newbie, and I would like to claim this issue.

What about placing something next to their username like: 
by [username](url) _[New Contributor]_

**Comment by ebarry** [comment]
this is a lovely idea

--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net



On Sat, May 19, 2018 at 2:17 PM, Christopher Bazin <notifications@github.com

**Comment by robotscissors** [comment]
@ebarry, Just for clarity - anytime a new member creates any type of Node (note, activity, asks a question, or posts an event), **that first contribution** will warrant the _[New Contributor]_ notation, correct?

Does the Node need to be moderated before the status is given? Or just the fact that the user made the effort to post some material and contribute?

**Comment by ebarry** [comment]
Hi! Great questions! I'm wondering if we can keep the moderation as is
(which already requires moderation for any note, comment, or "any kind of
node").

Is it possible to add the tag of "new contributor" independent of what's
going on with moderation status?

Relatedly, I think you should be able to see what unpublished stuff look
like on publiclab.org/spam.  Is this page visible to you?

Thank you for your thoughts on this!!!!

**Comment by jywarren** [comment]
To @ebarry 's question -- this shouldn't affect anything about out current moderation system, @robotscissors was just asking if the "New contributor" message should be shown before or after. I think before is fine, and that simplifies things!

**Comment by Gauravano** [comment]
I guess this issue is resolved. Closing it. Thanks!
