### ISSUE TITLE
🙌 Community Check-in #1: Summer of Code Week 2

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2739]
Hello everybody! Welcome to Community Check-in number 1! If you're new here, welcome, and please checkout our [welcome page](https://publiclab.github.io/community-toolbox/#r=all)!! 👍 🎉 😄 

I'm just back from a big trip to California to help run a Community Science space at Maker Faire -- we helped over 1700 people make microscope, spectrometry, and water quality kits - https://twitter.com/PublicLab/status/999019548849434624

![image](https://user-images.githubusercontent.com/24359/40389449-7abd8b0a-5de0-11e8-8930-7e3f5ccb3cc2.png)

## Check-ins

How are you all doing? What are you working on this week? Having trouble, have questions or stuck? Let's share!

## CodeClimate

As we're getting started, you may see CodeClimate suggesting some changes -- please do your best to tidy up code as you go -- even if it's not yours! The checks look like this:

![image](https://user-images.githubusercontent.com/24359/40389252-de9be6cc-5ddf-11e8-9ae8-53883a5a16c3.png)

And it'll suggest areas where you could make some small improvements to the code. If you're waiting on a review or another response, these are a great place to just pitch in on the overall tidiness and maintainability of our project, OR to make a `first-timers-only` issue ([read more here](https://publiclab.org/n/13667)!) to help a newcomer take on one of these!

****

## Rotating community check-ins

I'd like to invite others to take turns doing the weekly community check-in -- preferably on Monday, although I was so busy I missed it! Say hey in the comments if you'd like to take next week's!

* [x] @jywarren
* [ ] @ryzokuken 
* [ ] @stefannibrasil (maybe after start of RGSoC?)
* [ ] @sagarpreet-chadha
* [ ] someone else?

****

## 'Til next week!

As always, if you're waiting for a review, or if you're stuck,  please request help
here OR leave a comment with @publiclab/soc and @publiclab/reviewers for
some input. We're stronger as a community!

Thanks everyone!

**Comment by jywarren** [comment]
Hello @stefannibrasil @milaaraujo @MargaretAN9 @Gauravano @namangupta01 @ViditChitkara @tech4GT @mridulnagpal @SidharthBansal @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @ccpandhare @icarito @abTest-123 @steviepubliclab @ebarry @publiclab/soc @publiclab/reviewers -- trying a new weekly check-in! 😄 👋 📣

**Comment by tech4GT** [comment]
Hi @jywarren 😀

**Comment by abTest-123** [comment]
Expecting to start soon!

**Comment by MayankKashyap** [comment]
Hi @jywarren @all

**Comment by MayankKashyap** [comment]
Hi @jywarren @all

**Comment by Souravirus** [comment]
Hi @jywarren, @publiclab/soc, I am currently working on correcting the tests of the rails 5.0 upgrade

**Comment by ryzokuken** [comment]
@jywarren I would be a little blocked next week due to an important conference (Node's collab summit in Berlin), but would love to help out on the next week's check-in. 😄

**Comment by jywarren** [comment]
Also, i know i've been asking everyone a lot for relatively tight formatting and structural changes -- being a little more picky now that we're tackling much bigger projects -- but i'm hoping the requests make sense and you see how more rigorous syntax and even stylistic changes can help make the code easier to review, test, and maintain! Thanks for your patience!

**Comment by jywarren** [comment]
i think @mridulnagpal had a question about how to test some new changes -- Mridul, want to link us to your question?

**Comment by jywarren** [comment]
@ryzokuken just added you to the list! You can copy some of this week's template and expand/modify/refine as you like!

**Comment by jywarren** [comment]
Hi, Naman - can you link us to that and we can review? Thanks!

**Comment by MayankKashyap** [comment]
@namangupta can you paste the link here , so we can review...

**Comment by namangupta01** [comment]
Here's the link!

**Comment by stefannibrasil** [comment]
Awesome! I am so excited for the summer to start :tada: 

I can help with the check -in's too. Are there any docs for this?

**Comment by jywarren** [comment]
Thanks, Steffani -- shall I add you further down so after you begin? And there's no docs or template right now because we just made this process up 😛 but you can start with this as a template, i guess -- open to ideas for what we should be asking each week!

**Comment by jywarren** [comment]
@MargaretAN9 @Gauravano @ViditChitkara @mridulnagpal @SidharthBansal @sagarpreet-chadha when you have a chance, can you check in with us? I'd like to hear from all SoC folks each week to stay in good touch! Thank you!

**Comment by sagarpreet-chadha** [comment]
Hi @publiclab/soc team ! 
I have completed 1 layer module and currently working on next . 
@jywarren ...would love to do a community check-in 😄  !

**Comment by SidharthBansal** [comment]
Can anyone please review https://github.com/publiclab/plots2/pull/2737?

**Comment by jywarren** [comment]
Hi all! Just sharing a nice short overview of rails tests --
https://mixandgo.com/blog/feature-tests-vs-integration-tests-vs-unit-tests-in-ruby-and-rails

**Comment by jywarren** [comment]
Thanks @sagarpreet-chadha -- added you to the list. @ryzokuken did you want to do this coming Monday, then, and @stefannibrasil the next or did you want to hold off until RGSoC begins? Either way!

**Comment by SidharthBansal** [comment]
@jywarren I will also love to do the check-in. Can you explain a little what will be there in checkin? Any fixed time?

I am currently working on the main logic of the authentication system. Facebook api has changed so it is giving me some trouble. Google api is working properly.Trying to correct fb api. I have made usertags as needed. Is there any other patch needed to be done with user tag? I am currently working on the user_sessions_controller.

**Comment by jywarren** [comment]
OK, i wanted to say - we seem to have resolved the travis build issue now, so please go ahead and restart your builds. 

@Gauravano and @icarito can you chime in here with some notes on how to use `unstable` to test things out? No rush.

And since @ryzokuken will be in a conference next week, so @sagarpreet-chadha did you want to do a Monday check-in just like this one? @SidharthBansal there is no template as this is a new idea -- but you could start with the sections I posted, and add anything you like. I'm sure it will evolve!

I would like to ask folks two things --

First, if all @publiclab/soc fellows (not required for mentors, although you're welcome of course!) to check in each week, and

Second, we have a pretty deep back-log of pull requests right now. If folks are stuck on something, or just have a bit of extra time, let's really try to get some of those completed and merged, so we have fewer to go through -- i think an ideal is fewer than 20! I know i've created a few... but let's everyone pitch in! If newcomers need help, let's support them!!! 😄 👍 

Have a great weekend, folks! 🎉

**Comment by Gauravano** [comment]
Weekly check-in is an awesome idea @jywarren. Maybe we can have monthly call too..I will try to help as much I can with PR's and unresolved issues.

### Something about Unstable:
1. Use `git push -f https://github.com/publiclab/plots2.git <branch-name-you want-to-push>:unstable` for pushing your commits on `unstable`. Don't push your commits using SHA as it may delete top of `unstable` branch commits done by others (experienced this :wink:).
2. One can check information about their commit builds at http://jenkins.laboratoriopublico.org/ 
3. Experience your commits in action after pushing at https://unstable.publiclab.org/
4. Notify in Gitter channel (preferred as the majority of us use) before pushing so that no conflict arises with other's work.

@icarito please add more to this list. Thanks.

**Comment by Gauravano** [comment]
@jywarren @icarito please specify which commands to use while pushing on stable. As @namangupta01 and I, both are using above command and overrides each other's work. Thanks.

**Comment by sagarpreet-chadha** [comment]
Ok i will do the next check-in :+1:  !

**Comment by SidharthBansal** [comment]
Ok, thank @gauravano

**Comment by icarito** [comment]
Yes thanks everyone, I think we've had a great start!
With regard to using `unstable` :

Please note we've recently made some changes to Makefile and have started to deploy using this file.

So if your branch fails to build in unstable, you may need to rebase to latest master.

Second, you can always check https://jenkins.laboratoriopublico.org/job/Plots-Unstable/ to see if it's been recently used and by whom. You'll notice somebody using it from the timestamps of previous builds. Do coordinate on #publiclab when using the unstable staging server.

For pushing to unstable, from my working branch I usually to `git push origin HEAD:unstable`.

As @Gauravano pointed out, it will deploy to https://unstable.publiclab.org/.
