### ISSUE TITLE
Returning to a note comment some text does not appear.

### ISSUE THREAD

**Issue by dbeavers** [publiclab/plots2#274]
I opened a Github issue from the same browser tab after editing an existing and published note comment.  When finished, I did a couple of backs to get back to editing the note comment that had not been published.  The original text was still there but the second text that was added was missing.  I selected edit again and the second set of edits were present. This is unexpected behavior that is a bit disturbing at first.

**Comment by jywarren** [comment]
I believe this is a browser behavior that I'm not sure we can easily fix -- that browsers "keep" only the initial state of a page, not the final state before you left. I've noticed this on many sites, so I think we should close this (and potentially re-open on a browser's issues feed). Thanks!
