### ISSUE TITLE
🙌 Community Check-in #2: Summer of Code Week 3

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#2750]
Hi everybody 👷  ! 
If you're new here, welcome, and please checkout our [welcome page](https://publiclab.github.io/community-toolbox/#r=all)!! 👍 🎉 😄 

@stefannibrasil @milaaraujo @MargaretAN9 @Gauravano @namangupta01 @ViditChitkara @tech4GT @mridulnagpal @SidharthBansal @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @ccpandhare @icarito @abTest-123 @steviepubliclab @ebarry @publiclab/soc @publiclab/reviewers 

_How are you guys doing ? How was your weekend 🔆 ?_

**Leave a comment here describing what are your plans for this week ❓ or simply leave a  Hi if not planned yet 😄  !**

I have been working on some layers and i plan to optimize the code this week 🔨 👨‍💻  .
https://publiclab.github.io/leaflet-environmental-layers/example/mapSimple.html
<img width="191" alt="screen shot 2018-05-27 at 11 30 27 pm" src="https://user-images.githubusercontent.com/14952645/40589151-099dbc36-6206-11e8-95e7-87dfcd71b893.png">

****

## 'Til next week!

As always, if you're waiting for a review, or if you're stuck,  please request help
here OR leave a comment with @publiclab/soc and @publiclab/reviewers for
some input.

Happy coding 🎉  !

**Comment by Gauravano** [comment]
hi @sagarpreet-chadha @publiclab/soc , the weekend went really well. 
I have completed the basic Draft feature and now planning to add some more tests this week, adding node.path changer method, and can further proceed to Secret URL sharing for non-PublicLab users after discussing with mentors. Also, you guys can try Draft feature at https://unstable.publiclab.org/ and your suggestions and comments are most welcome for discussion at https://github.com/publiclab/plots2/issues/2667 .Thanks :smiley: !

**Comment by jywarren** [comment]
Hi!! Great check-in, @sagarpreet-chadha !! 

Love how that map is coming ❤️ 🌏 

I realized some folks are still having exams -- good luck! 📝 

I'm going to be showing some Image Sequencer work to NASA folks this coming weekend. It's going well! Lots done there.

I also see lots of updates across the site. Trying to respond to people where needed! @publiclab/soc  if you are stuck on something, please ping in here where you need help or review from others.

Also, I saw 🎥 Solo -- it was fun! 👍 👍 👍

**Comment by Souravirus** [comment]
Hi @sagarpreet-chadha @jywarren @publiclab/soc 
I am currently working on clearing out the deprecation warnings of rails 5.0 upgrade. I have corrected all the errors. Now some failures and a long list of deprecation warnings is remaining. So, hopefully, I will clear these out this week. Thanks!!

**Comment by mridulnagpal** [comment]
Hi @publiclab/soc 
I am currently working on creating lat/lng tags on the basic of places tag on a research note. Currently I am detecting any place tags and then geocode the location to find lat/lng and finally ask the user if he/she wants to add location tags. 
I am having some troubles testing though, any help would be much appreciated. Thanks!!

**Comment by ViditChitkara** [comment]
Hello all, @sagarpreet-chadha , @jywarren  -- Have completed the basic digest email feature! Hopefully we'll see it working after the octokit issue is resolved. Would be needing help for testing out the recurring mails and related functionality.
Up next, I would be working to improve the UI/UX and content of Email and further testing it.
Thanks everyone for helping out!!

**Comment by jywarren** [comment]
HI, all! Great work this week. 💪 🎉 ⚡️ ⚡️ ⚡️ 😄 

We're still stuck in the `octokit` bug, so please try to team up to solve this since many people are affected by it -- https://github.com/publiclab/plots2/pull/2738#issuecomment-393226759 @publiclab/soc @publiclab/reviewers

## Rotating community check-ins

@ryzokuken did you want to do this Monday's check-in, or are you still at a conference? (hope you're having fun!) If not, I see @SidharthBansal has offered? Just coordinate so you don't both do it 😄 

I have this list -- if anyone else wants to volunteer I can add you to the bottom? Thanks all!

* [x] @jywarren
* [x] @sagarpreet-chadha
* [ ] @ryzokuken 
* [ ] @SidharthBansal 
* [ ] @stefannibrasil (maybe after start of RGSoC?)
* [ ] someone else?

**Comment by SidharthBansal** [comment]
I am happy to do the next community check-in on upcoming Monday if @ryzokuken is busy with the conference. Else if he is free, he is most welcomed.

**Comment by ViditChitkara** [comment]
I am interested too!!😄😄

**Comment by namangupta01** [comment]
Yeah! Great progress. Once `octokit` bug is removed we will going see a lot of new features coming to life.

**Comment by Souravirus** [comment]
I am also interested to do the community check-in @jywarren

**Comment by abTest-123** [comment]
Hi @jywarren @icarito @MargaretAN9 I set up a Calendar / Hangouts link which I hope will work: https://hangouts.google.com/hangouts/_/calendar/YW1pcmJlckBnbWFpbC5jb20.05tlkdhcj52lbgb36jl1r3jbju

**Comment by jywarren** [comment]
Moving over to #2764 !! Thanks!

**Comment by MargaretAN9** [comment]
Thanks for the link, talk to you at 13:00. :)
