### ISSUE TITLE
Edit documentation

### ISSUE THREAD

**Issue by ljl7123** [publiclab/plots2#2752]
My university technical writing course has an assignment which involves editing documentation on GitHub repositories as practice in real world settings. Edits may involve aspects like style, structure, and concision. Existing style guidelines would be taken into account. The following is one of the resources I would be using:

https://jacobian.org/writing/technical-style/ 

Would anyone mind if I propose edits to documentation in this repository? It would really help me out!

**Comment by Gauravano** [comment]
Hi @ljl7123 that would be awesome! You can ask for help anytime if you require any details about any feature, method, etc. Regarding the writing style, i don't think there would be any issue, let's just confirm with @publiclab/community-reps once. Thanks!

**Comment by ljl7123** [comment]
Awesome, thanks so much @Gauravano!

**Comment by ljl7123** [comment]
Are there any methods/features off the top of your head that need clearer documentation,  @Gauravano ?

**Comment by jywarren** [comment]
Hi, thanks so much! I wonder if perhaps it would be interesting to build out or refine either:

https://github.com/publiclab/plots2/blob/master/doc/DATA_MODEL.md

or

https://publiclab.org/wiki/power-tags

What do you think?

**Comment by jywarren** [comment]
OR, if anyone in @publiclab/soc is interested in help with documenting their new features, perhaps they could chime in with a request! Like the email notifications system is not very well documented.

**Comment by SidharthBansal** [comment]
Yeah, it will be great to get your help @ljl7123

**Comment by SidharthBansal** [comment]
Yeah, it will be great to get your help @ljl7123

**Comment by ljl7123** [comment]
Hi @jywarren , thanks for the suggestion! I'm not quite sure what refining or building out these documents entail, could you elaborate or provide resources? Is it regarding style or the actual content? Thanks!

**Comment by jywarren** [comment]
I think some depends on what exactly you're looking to contribute. We could
write a rough version and you could help style/edit it for readability. Or
if you want, we can try writing bullet points out for the structure and you
can try writing the actual text. What does your assignment need?

**Comment by ljl7123** [comment]
Ideally, I would make edits for readability for a rough version.  Would that work?

**Comment by Gauravano** [comment]
Hi @ljl7123 that would surely work. To start with here are some files which you can see for improvement:-
1. https://github.com/publiclab/plots2/blob/master/README.md
2. https://github.com/publiclab/plots2/blob/master/CONTRIBUTING.md
3. https://github.com/publiclab/plots2/blob/master/doc/DATA_MODEL.md

Also, we have a status system in our codebase for `comment`, `node` and `user`. we haven't documented it, if you can help out with this too, that would be awesome. But, let's start with the existing files. Thanks ! 

(@jywarren please add if I miss any file. Thanks)

**Comment by SidharthBansal** [comment]
Hi, @lkl7123 it will be great if you will be able to create a page for the different labels which we often use at repositories of the public lab. Newcomers may face problem while reading the labels. Or we can have a section in the https://github.com/publiclab/plots2/blob/master/CONTRIBUTING.md? What do you say @jywarren ?

**Comment by jywarren** [comment]
that's also a great idea. I don't know how much work @lkl7123 is looking to
take on, but maybe we could have a list of documentation issues compiled
that others can take on as well?

**Comment by jywarren** [comment]
Closing for now, thank you!
