### ISSUE TITLE
Move recaptcha configurations to environment variables

### ISSUE THREAD

**Issue by icarito** [publiclab/plots2#2756]
We are finishing to  move our deployment to a container. Containers require to be able to be setup by environment variables.

But we are hard-coding a development API key in `config/initializers/recaptcha.rb`. It is expected to be changed by the admin at setup time. We would like to use an environment variable like we do for other configuration settings.

We should keep the development API key in case there is not environment variable defined.

**Comment by jywarren** [comment]
Made a FTO from this! #2762 -- can you watch out there? Thanks!
