### ISSUE TITLE
`config/database.yml` with environment variables

### ISSUE THREAD

**Issue by icarito** [publiclab/plots2#2757]
For the purpose of building a reusable container it would be ideal if we could setup a few configuration variables to put inside an example `config/database.yml.containers` that would configure, to begin:

`DB_HOST`
`DB_PORT`
`DB_NAME`
`DB_USER`
`DB_PASSWORD`

This would be a first step into building containers in staging and using them directly in production (saving a build step and avoiding heavy build process in production).

This task involves tweaking `Dockerfile` to use a new `config/database.yml.containers` instead of `database.yml.example` and then `docker-compose.yml` would need to be setup to pass these environment variables in the `environment` field of the `web` container.

**Comment by jywarren** [comment]
Would we use `ENV['DB_HOST']` and such? like environment variables?

**Comment by jywarren** [comment]
I think my formatting suggestion above should work in a new file called `config/database.yml.containers` -- this should be pretty good for a first timer to try out!

**Comment by icarito** [comment]
I'm reviewing what remains hardcoded still:

- Listening port
- Database configuration
- Forking options  (production: `--max-pool-size 9 --min-instances 9`)
