### ISSUE TITLE
Main header image fails to upload in edit mode

### ISSUE THREAD

**Issue by khufkens** [publiclab/plots2#276]
If I edit the post, an image can be uploaded (this used to be slow if not impossible, but has since a few days been stable / resolved)
![post_with_picture](https://cloud.githubusercontent.com/assets/1354258/7420495/e8c6d7bc-ef4a-11e4-8691-bc3469d761f3.png)
However, after hitting publish (when the image is uploaded) the website does not process the changes and reports an error.
![error_after_submit](https://cloud.githubusercontent.com/assets/1354258/7420506/0e3d52aa-ef4b-11e4-97a6-431690c898b6.png)

This is the case on Linux / FF or Chromium or Mac OSX / FF, OS / browser configurations respectively. So it seems to be fairly browser or OS independent.

No clues on how to resolve this however.

**Comment by jywarren** [comment]
Thank you for reporting so thoroughly. I don't have much time before the
end of the day but this is at the top of my list tomorrow.

**Comment by khufkens** [comment]
No rush,

Just a minor problem. I also think it is an updating issue as my previous
posts where I assigned a picture before submitting the original post were
ok.

K

On Thu, Apr 30, 2015 at 4:31 PM, Jeffrey Warren <notifications@github.com>
wrote:

> Thank you for reporting so thoroughly. I don't have much time before the
> end of the day but this is at the top of my list tomorrow.
>
> On Thu, Apr 30, 2015 at 3:11 PM, Koen Hufkens <notifications@github.com>
> wrote:
>
> > If I edit the post, an image can be uploaded (this used to be slow if not
> > impossible, but has since a few days been stable / resolved)
> > [image: post_with_picture]
> > <
> https://cloud.githubusercontent.com/assets/1354258/7420495/e8c6d7bc-ef4a-11e4-8691-bc3469d761f3.png
> >
> > However, after hitting publish (when the image is uploaded) the website
> > does not process the changes and reports an error.
> > [image: error_after_submit]
> > <
> https://cloud.githubusercontent.com/assets/1354258/7420506/0e3d52aa-ef4b-11e4-97a6-431690c898b6.png
> >
> >
> > This is the case on Linux / FF or Chromium or Mac OSX / FF, OS / browser
> > configurations respectively. So it seems to be fairly browser or OS
> > independent.
> >
> > No clues on how to resolve this however.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/publiclab/plots2/issues/276>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/publiclab/plots2/issues/276#issuecomment-97956858>.
>



-- 
Dr. Koen Hufkens

Harvard University
Department of Organismic & Evolutionary Biology
Richardson Lab <http://www.oeb.harvard.edu/faculty/richardson/>
~
Ghent University
Faculty of Bioscience Engineering
Isotope Bioscience Laboratory <http://www.isofys.be>

**Comment by jywarren** [comment]
OK, thanks for the clarification.

**Comment by jywarren** [comment]
Hello - I believe this is fixed; can you test it out please? Thank you!

**Comment by khufkens** [comment]
Have tested it, works perfectly!

Thanks!!

K

On Fri, May 1, 2015 at 5:01 PM, Jeffrey Warren <notifications@github.com>
wrote:

> Hello - I believe this is fixed; can you test it out please? Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/publiclab/plots2/issues/276#issuecomment-98237520>.
>



-- 
Dr. Koen Hufkens

Harvard University
Department of Organismic & Evolutionary Biology
Richardson Lab <http://www.oeb.harvard.edu/faculty/richardson/>
~
Ghent University
Faculty of Bioscience Engineering
Isotope Bioscience Laboratory <http://www.isofys.be>

**Comment by jywarren** [comment]
thanks to you!
