### ISSUE TITLE
Community Check-in #3 Summer Of Code Week 4

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2764]
Hi everybody :construction_worker_man: !
If you're new here, welcome, and please try some of the ftos. This is a checklist for publiclab/soc.

@stefannibrasil @milaaraujo @MargaretAN9 @Gauravano @namangupta01 @ViditChitkara @tech4GT @mridulnagpal   @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @ccpandhare @icarito @abTest-123 @steviepubliclab @ebarry @publiclab/soc @publiclab/reviewers

How was your weekend? How are you doing? What is your plan for this week?
If you have not planned yet. Just leave a Hi! so that we could know that you are well.
Are you facing some trouble? We are here to collaborate and help each other. The public lab has strength as a community :small_airplane: 

As the openssl gem is installed. I will make major changes this week. Finally, the build test cases passed. 
I am planning to complete the whole login first this week of one provider. I will open the pr shortly. Only the user_tag_controller and session_controller changes are left. The same functions will be used for the providers. I will be also working on the tests this week.
This week will be very interesting and full of code. :smile:

**Comment by sagarpreet-chadha** [comment]
Hi @SidharthBansal , @publiclab/soc team !
I plan to write a note on publiclab.org about the *leaflet-environmental-layers* and try to complete 1 more layer module also .
Thanks :octocat: :hammer: !

**Comment by jywarren** [comment]
Hi, all! I'm at a NASA meeting this weekend presenting our work --including on ImageSequencer work that @tech4GT (and @ccpandhare last year) have done! Work there is going quickly!

I'm so glad we've solved the `octokit` error and we went from 44 pull requests to 32 really quickly!

I wanted to share that you can use Waffle.io to visualize progress of any milestone, such as:

https://waffle.io/publiclab/plots2/metrics/burndown?milestone=Email%20notifications%20overhaul

This is pretty cool! If you organize your summer's work into a milestone, that can be an interesting way to look at how much you've gotten done!

![image](https://user-images.githubusercontent.com/24359/40891651-de09ffe4-6746-11e8-835a-a140cd705c9e.png)

**Comment by jywarren** [comment]
Also just a note - got through all but 26 of those 44 pull requests! Thanks everyone! Great week! For this month:

> Excluding merges, 19 authors have pushed 35 commits to master and 114 commits to all branches. On master, 84 files have changed and there have been 981 additions and 211 deletions.

https://github.com/publiclab/plots2/pulse/monthly

🎉🎉🎉🎉🎉🎉🎉🎉🎉

**Comment by Gauravano** [comment]
Hi @publiclab/soc ,
I am done with the Draft feature yesterday, so this week I would be starting implementation of Subscription settings for Email digest. 

Thanks, 
Gaurav

**Comment by jywarren** [comment]
I think @Souravirus and @siaw23 have something to present folks with too! #2726

**Comment by namangupta01** [comment]
Hello Team! Hopefully, reply to comment feature would get merge soon then i will start working on reply by tweet feature. 

Thanks!

**Comment by ViditChitkara** [comment]
Hello all, I am done with basic digest feature and redis installation with a queuing backend (sidekiq). Would be working on testing and scheduling of mailers this week.

Thank you all for helping out!!

**Comment by ryzokuken** [comment]
Awesome!

Nice initiative, @jywarren. This makes is super easy to get up to speed. Should I do the next week's check-in? (If someone else isn't already enqueued).

**Comment by jywarren** [comment]
Sure, i think you're up next in the list, actually -- that'd be great!!!

**Comment by jywarren** [comment]
I also posted a summary of the past month or two's work here!

https://publiclab.org/notes/warren/06-08-2018/web-working-group-update-22-june-2018

**Comment by ebarry** [comment]
Hi all! i just got back from Family Time and am excited to see all this activity. I would love to hear from @mridulnagpal about Location. Thanks!

**Comment by jywarren** [comment]
Hi everyone - can folks update their milestones and paste them in here so we can start tracking progress?

We will be doing our first GSoC evaluations next week so now is a great time to get your planning issues updated and be sure you have your completed work shown and your next steps outlines. You're all doing great!! 👍 👍 👍 

@stefannibrasil @milaaraujo @MargaretAN9 @Gauravano @namangupta01 @ViditChitkara @tech4GT @mridulnagpal @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @ccpandhare @icarito @abTest-123 @steviepubliclab @ebarry @publiclab/soc @publiclab/reviewers

**Comment by Gauravano** [comment]
Hi @ebarry welcome back :smiley: ! Hope you enjoyed your trip. Many new features added to the website last week, do check them. We would love to have your review on them. Thanks.

**Comment by Gauravano** [comment]
Hi @publiclab/soc 

### Work Progress 
First Implementation of the draft feature is done 
Plannig issue -  #2667 
Last PR - #2747 

#### Remaining Part of Draft feature (open at #2667 ) -- 
1. Secret Link Sharing
2. Writing wiki about the draft feature

#### Currently working on-
Subscription settings for Email: https://github.com/publiclab/plots2/issues/2796 

**Also, I will not be able to do much this week due to some change in my exam schedule http://ipu.ac.in/pubinfo/ntbtech4220518.pdf . Sorry for the inconvenience!**

**Comment by Souravirus** [comment]
Hi @publiclab/soc 
**Work Progress**
Upgrade to rails 5.0.6 is done:
Planning issue: #2714 
Related PRs: #2726 #2783

**Comment by ebarry** [comment]
hi @sagarpreet-chadha  and @mridulnagpal , i was wondering if the map at the top of https://publiclab.org/people pulls in additional results as you pan or zoom? I can't seem to get the map to show any additional results....ideas?

**Comment by sagarpreet-chadha** [comment]
Hi @ebarry ! Welcome back 😄 🎈 !

Additional results as in more **people-markers** ? Like third part of issue https://github.com/publiclab/plots2/issues/1934 . 

Or do we wish to show more information of a person on marker ❓  

Thanks !

**Comment by sagarpreet-chadha** [comment]
Hi folks !

# Progess till now : 

* Many layers are completed , see the  list of layers here : https://github.com/publiclab/leaflet-environmental-layers/issues/1
* Layers Demo : https://publiclab.github.io/leaflet-environmental-layers/example/mapSimple.html

# Currently working on : 

* Planning issue : https://github.com/publiclab/leaflet-environmental-layers/issues/1
*  https://github.com/publiclab/leaflet-environmental-layers/issues/3

# Next : 
* https://github.com/publiclab/leaflet-environmental-layers/issues/10
* https://github.com/publiclab/leaflet-environmental-layers/issues/6  (will need help on what exactly do we require (data) in the API )
* after this only 2 layers will be left !

Thanks !

**Comment by ryzokuken** [comment]
Closing this, making a new issue for this week.

**Comment by ViditChitkara** [comment]
Hello all!! 
****Work Progress****
- The like for comment feature is now working. #2591 
- Added Sidekiq queuing backend #2738 
- Added basic template for digest emails (yet to test, once redis works on production) #2711 

****Currently working on****
- Integration of sidekiq dashboard - Would be required to view various job status. #2772 
- Making cronjob for recurring digest job #2772
- Making redis work on production (stuck on it) #2782 

****Next****
- Improve Digest email content and design.
- After the digest feature I would like to work on suggestion comment feature. More details on #741. Will soon make a planning issue for this. This seems to be pretty interesting for me!

Thanks everyone for helping @jywarren , @icarito , @publiclab/community-reps , @publiclab/soc

**Comment by jywarren** [comment]
Just to mention, i love the new like comment feature!!!

**Comment by jywarren** [comment]
Moved to #2814!
