### ISSUE TITLE
Parent tags no longer showing up

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#277]
The power tag that allows one page to be nested under another is no longer showing up.

**Comment by steviepubliclab** [comment]
Hi there, 
This old issue seems to be happening again. 
Here are a couple examples of where it was in the past but is no longer working. 
- https://publiclab.org/wiki/pm
- https://publiclab.org/wiki/people-of-the-new-orleans-urban-waters-project

Thanks!

**Comment by jywarren** [comment]
Thank you, solved in https://github.com/publiclab/plots2/pull/1238 -- should publish today!
