### ISSUE TITLE
Add autocomplete to comment fields (starting with emoji) using the Horsey library

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2775]
### Please describe the problem (or idea)

We have nice emoji now possible by using `\:smiley:` syntax. Let's make this autocomplete like it does in GitHub -- this will be a fun little project! 👍 😃 🐱 🐴 🌴 

![image](https://user-images.githubusercontent.com/24359/41061332-3d5348ba-69a0-11e8-942b-2ca992f8b86e.png)

https://bevacqua.github.io/horsey/

It should be pretty easy to implement! 

Follow-up ideas: 

1. autocompletion of names when you begin typing `@`
2. maybe even research notes when you start typing `#`

We'll probably need a string list of emoji names from somewhere to do this. Let's implement it in `app/assets/javascripts/comment-autocomplete.js` file!

**Comment by ViditChitkara** [comment]
Looks interesting, I would be happy to help!!

**Comment by jywarren** [comment]
Awesome, please go for it! Thanks!

**Comment by cheneyshreve** [comment]
@jywarren Hi, I'm a first-timer and new to open source. I've looked over the "open" first-timer issues, but they all seem to be taken. Is there anything you could recommend? Thanks :)

**Comment by jywarren** [comment]
Hi! Did you maybe want to try taking a crack at this one? It's not 100%
simple but we can help you out;

https://github.com/publiclab/plots2/issues/2452

**Comment by cheneyshreve** [comment]
Hi @jywarren sure, I'll give it a go!
