### ISSUE TITLE
Error connecting to redis

### ISSUE THREAD

**Issue by ViditChitkara** [publiclab/plots2#2779]
By default redis is trying to connect to localhost (127.0.0.1)
```
Started GET "/users/test_digest_email" for 172.56.22.214 at 2018-06-06 22:12:08 +0000
Processing by UsersController#test_digest_email as HTML
Completed 500 Internal Server Error in 7ms (ActiveRecord: 1.2ms)
  
Redis::CannotConnectError (Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)):
  app/controllers/users_controller.rb:301:in `test_digest_email`
```
 Discussed at:- #2711

**Comment by ViditChitkara** [comment]
https://github.com/publiclab/plots2/blob/fad88fd72c9d08f5591bf4c0cab402160eb9ea54/docker-compose.yml#L32-L41
@icarito there is an environment var named JOB_WORKER_URL in sidekiq container, won't it work? Should I add it in web container?? @jywarren any recommendations, on this? I am a bit in-experienced with docker-compose. Any help is appreciated!!

**Comment by icarito** [comment]
@jywarren I think this was working in unstable but we still need to put it in stable and production. I'll tweak the docker-compose-production.yml now to get this running.

**Comment by ViditChitkara** [comment]
Hi @icarito, I had made the changes for production and stable in #2772, however we saw a circular dependency error, so I made some changes in #2978. Can you have a look at both??
Thanks!
