### ISSUE TITLE
Discussion regarding the deployment of reply-by-email to comment

### ISSUE THREAD

**Issue by namangupta01** [publiclab/plots2#2781]
As discussed with @jywarren on gitter, opening this issue to discuss the things to be done regarding to start our new `reply-by-email` feature.

**Comment by jywarren** [comment]
Great! Can you link back to the conversation PR and copy in some of the notes from there?

**Comment by namangupta01** [comment]
sure.

**Comment by namangupta01** [comment]
Previous discussion regarding this is in #2669.
In the discussion, @icarito gave information about the service being used by stable, unstable.
>What mailman server do you mean? We do not offer our own SMTP service but use an external service (GMail). Currently localhost SMTP is redirected to this GMail account and in the case of `unstable` and `stable` SMTP mail goes all to "testing@tycho.media.mit.edu" mailbox inside the staging server. The server is not setup to collect mail or accept mail from other servers.

See #2669 for detail discussion.

**Comment by namangupta01** [comment]
As in stable and unstable all the mail goes to mailbox inside the staging server we can setup pop3 protocol to receive mail from testing@tycho.media.mit.edu.
And in case of localhost SMTP is redirected to any gmail account we can use the configuration of that gmail account.

**Comment by jywarren** [comment]
OK -- we'll wait for @icarito to chime in on the next step, but if you want to organize a checklist here that'd be helpful too!

**Comment by jywarren** [comment]
So i think we're wanting to make a mailbox for this, using Google Apps? I can do that and send info to @icarito

**Comment by jywarren** [comment]
What should its address be? `website@publiclab.org`? Something friendlier? `notifications@publiclab.org`?

**Comment by namangupta01** [comment]
`notifications@publiclab.org` looks awesome.

**Comment by icarito** [comment]
Hi,
Jeff gave me information on one mailbox. 
notifications@ is for production.
Could we make one mailbox for staging and we can point stable and unstable to pick up fro there? maybe notifications-staging@publiclab.org ?
Then, we need to add email variables to environment at staging. @jywarren this is done in Jenkins configuration at the web interface, for each task configuration. For the case of production we have an `environment.sh` file which is not git-tracked.

**Comment by jywarren** [comment]
Also linking to #2823

**Comment by jywarren** [comment]
OK, created `notifications-staging@` and `notifications-unstable@`

**Comment by jywarren** [comment]
OK, confirmed emails are being received in notifications-staging@ and notifications@. I did not set up the unstable branch one but could in the future if we want. Also noting Naman has opened https://github.com/publiclab/plots2/pull/2823/ for the docker-compose part -- great!
