### ISSUE TITLE
Rails 5 follow-up fixes

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2787]
Just compiling some things from the #2726 #278 Rails 5 upgrades now that it's in stable!

* [x] `POST https://stable.publiclab.org/tag/suggested/tag 404 (Not Found)` - did route change? A GET route exists: https://github.com/publiclab/plots2/blob/9172df4efdcb67995f88ad770fc6c71a22684c2e/config/routes.rb#L173
* [x] ~top navbar search autocomplete doesn't work (doesn't seem to trigger a request at all?)~ (existing bug!)

@Souravirus any help appreciated but I imagine it's late there!

**Comment by Souravirus** [comment]
Yeah lets check what has happened

**Comment by jywarren** [comment]
Oh wait! The top bar nav search does work on a note page! But not on a `/post` page. Let's test more!

**Comment by Souravirus** [comment]
I was checking on the dashboard and it was working fine there. That's why I said in gitter

**Comment by jywarren** [comment]
Ha, and yes, https://publiclab.org/post also doesn't autocomplete. so that's an existing bug! Removing it from above.

**Comment by Souravirus** [comment]
yeah its not auto completing but the search is working fine here

**Comment by jywarren** [comment]
Also Travis seems to have trouble with this... the post-merge run failed with some kind of timeout very early in the process: https://travis-ci.org/publiclab/plots2/builds/389444495 -- adding to list, but @icarito any idea why it would get stuck on:

```
Step 1/16 : FROM ruby:2.4.1-jessie
2.4.1-jessie: Pulling from library/ruby
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by Souravirus** [comment]
yeah there was timeout sometimes but restarting the build worked

**Comment by jywarren** [comment]
OK - can you change the GET to a POST and open a PR? That's the only thing I've found now!

**Comment by Souravirus** [comment]
Also the autocomplete feature is not working in original https://publiclab.org/post. So, I guess this problem is earlier than rails 5.0

**Comment by Souravirus** [comment]
Ok I will change 'get' to 'post'

**Comment by jywarren** [comment]
Just going to re-open this for a question -- locally, I'm seeing:

```
ActiveRecord::StatementInvalid (Mysql2::Error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'plots.node_revisions.vid' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by: SELECT  `node_revisions`.* FROM `node_revisions` INNER JOIN `node` ON `node`.`nid` = `node_revisions`.`nid` WHERE (type = ('page')) AND (node.status = 1) AND (node_revisions.status = 1) AND (timestamp - node.created > 300) GROUP BY node.title ORDER BY timestamp DESC LIMIT 10):
  
app/controllers/home_controller.rb:127:in `activity'
app/controllers/home_controller.rb:163:in `block in set_activity'
app/controllers/home_controller.rb:162:in `set_activity'
app/controllers/home_controller.rb:15:in `home'
```

Did you ever see this error? Thanks!

**Comment by Souravirus** [comment]
No I haven't seen this error.

**Comment by Souravirus** [comment]
behind this error

**Comment by Souravirus** [comment]
Hi @jywarren according to this stackoverflow post https://stackoverflow.com/questions/34115174/error-related-to-only-full-group-by-when-executing-a-query-in-mysql since we are doing `group by` by a node.title, that's why it is giving that error. We should try adding group by node.id then it would be perfect.

**Comment by jywarren** [comment]
oh cool! Want to try opening a PR?

**Comment by Souravirus** [comment]
Yeah I will open a PR
