### ISSUE TITLE
Bad links in e-mails titled "New comment..."

### ISSUE THREAD

**Issue by dbeavers** [publiclab/plots2#279]
When I get an e-mail notification that someone has added a comment to a note I have commented on ALL of the links point to the the author's profile page.  That includes the text of the comment, the "Reply at: __" link, and the "Report abuse to: __" link.  I will forward an e-mail example to the dev list.

**Comment by ebarry** [comment]
I just noticed this is still happening.

**Comment by jywarren** [comment]
Yes, we haven't had time to work on it! :-(

**Comment by jywarren** [comment]
Merging into #203 after prioritization related to email spam concerns via @icarito
