### ISSUE TITLE
PLANNING ISSUE: Subscription Settings

### ISSUE THREAD

**Issue by Gauravano** [publiclab/plots2#2796]
Subscription Settings would be a part of **Settings** page. I would be creating a settings page where Subscription settings will be a section but I think after this we would like to add more things to the settings page for giving users more power. 

Checklist for start:
* [ ] Migration for generating `digest:weekly` or any other to all profiles
* [x] Method in `user_controller.rb`  for accepting the response from settings page
* [x] Creating a view for the settings page
* [x] Procedure for getting settings page using tags

I would be adding more points shortly.
  
@jywarren @steviepubliclab @ebarry

**Comment by jywarren** [comment]
Cool! Also consider building some out
in app/controllers/subscription_controller.rb -- great start here!

**Comment by Gauravano** [comment]
Actually, we would be having this settings page for all user-specific settings so `user_controller.rb` maybe the good place to put logic. But, I'll see if something specific to subscription comes in, I would add that to `subscription_controller.rb`. Thanks.

**Comment by jywarren** [comment]
Ok!!!

**Comment by Gauravano** [comment]
hi @jywarren for starter which options we want to add in our settings. I have added these for now 

![options](https://user-images.githubusercontent.com/20878070/41434325-fb0c110e-7038-11e8-8659-489cc0a3a2c0.png)

Also, please let me know the tag names of each associated setting. Currently, I am considering `digest:daily`, `digest:weekly`. Thanks

**Comment by jywarren** [comment]
I like this! The monthly blog would be everything tagged `blog` once per
month? What user tag would that be?

Cool!

I think this is a good start to try out first. Then we can consider more
complex types -- like what about comments vs posts, questions...

Also, maybe we should have `customized` be linked to a page explaining how
it's generated?

**Comment by Gauravano** [comment]
Sorry for responding late on this! yes, we can do this once we are done with current settings as mentioned in #2985.

**Comment by Gauravano** [comment]
hey @jywarren should I add **monthly blog** as a setting to the checklist at #2985?

**Comment by jywarren** [comment]
sure!

**Comment by Gauravano** [comment]
Merging with #2985
