### ISSUE TITLE
Open ID flash notice appears on wrong page

### ISSUE THREAD

**Issue by icarito** [publiclab/plots2#2799]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://publiclab.github.io/community-toolbox/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

### Please describe the problem (or idea)

![image](https://user-images.githubusercontent.com/199755/41179337-ff684442-6b2f-11e8-9d9a-8015e2055691.png)

This notice is confusing.

**Comment by jywarren** [comment]
i think there's an error with flash[:notice] usage - it is held over in
the session from a recent page load. behavior may have changed in recent
versions, so perhaps these are getting "saved up" somehow and inserted into
the wrong page. One thought is `flash[:notice]` vs. `flash.now[:notice]` --
but perhaps we should read up on how this has changed in Rails?

**Comment by jywarren** [comment]
It's this line:

https://github.com/publiclab/plots2/blob/b4728ff50e981a766dbbcee8c18511aac5241f69/app/controllers/openid_controller.rb#L117-L121

You should get this message when logging into MapKnitter or SpectralWorkbench and getting redirected through PublicLab.org. And typically `flash[:notice]` is saved for the next page -- it's a way to have something appear on the subsequent page load, and (at least in older versions of Rails) to show things on the current page it was `flash.now[:notice]`. 

But maybe things are different in Rails 5?

**Comment by jywarren** [comment]
http://api.rubyonrails.org/classes/ActionDispatch/Flash.html

I think the solution may be to just display this message on the template in `/app/views/openid/decide.html.erb` directly, and not in a flash, since we are not redirecting.

**Comment by rtrunkhill** [comment]
Just so im clear you want to remove the message and flash[:notice] from  this:
``` 
def show_decision_page(oidreq, message = 'The site shown below is asking to use your PublicLab.org account to log you in. Do you trust this site?')
    session[:last_oidreq] = oidreq
    @oidreq = oidreq

    flash[:notice] = message if message

    render template: 'openid/decide'
  end
```

and add it directly to the ```/app/views/openid/decide.html.erb``` with something like ```<h3>The site shown below is asking to use your PublicLab.org account to log you in. Do you trust this site?</h3>``` ?

I'll make those changes but i can't seem to reproduce locally (although it's easy enough to do on the site itself)

**Comment by jywarren** [comment]
Hi, I think we don't want to remove the message, but to figure out how and why it is appearing on the wrong page. I believe it is supposed to be stored for the next page refresh. So maybe it needs to be displayed with `flash.now` instead of `flash` because on the line I highlighted above, it doesn't actually redirect, so the message is "left over". 

But we may also need to be sure that there isn't an alternative scenario where there is actually a redirect, and be sure the message appears properly in that (if it exists).

Thanks for your help on this! We really appreciate it!

**Comment by rtrunkhill** [comment]
alright i changed it to ```flash.now[:notice] = message if message``` but I'm not sure how to test it locally.  My app doesn't have mapknitter to redirect to, so i'm not sure how to replicate/test if this resolves the issue.  Do you want me to submit the pr?  it rake test passes

**Comment by jywarren** [comment]
Hmm, I think yes, we can test that on my local setup where I've gotten both
apps running, if you submit a PR. Thank you!
