### ISSUE TITLE
Instant rice

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#28]
Ideally, it should take fewer than 3 steps from start to finish and less than 10 minutes to cook.

I'm thinking we'll need to add water at some point.

Possibly heat.

**Comment by ananyo2012** [comment]
@btbonval Now what do you want to mean by this?

**Comment by jywarren** [comment]
I think Bryan was keeping a sense of humor in our GitHub issue tracker. Maybe we can keep this one for humorous posterity?

**Comment by ananyo2012** [comment]
:smile: Sure!

**Comment by ryzokuken** [comment]
As a matter of experience, I feel that Instant Noodles not only cook faster but are way more fulfilling.

**Comment by yukiisbored** [comment]
Since I'm Asian, Instant rice are made for lazy people. Real people cook raw rice with a pot and a stove. Death to the lazy people generating rice cookers!

**Comment by jywarren** [comment]
I love it when people find this issue. Means you're /really/ deep into the
repository! :-)

**Comment by ryzokuken** [comment]
> Death to the lazy people generating rice cookers!

@yukiisbored Wew, dude. Calm down :P

**Comment by ryzokuken** [comment]
@siaw23 aww.

**Comment by gauravano** [comment]
Should we reopen this @jywarren :see_no_evil: :laughing:

**Comment by btbonval** [comment]
I don't remember opening this. It looks like I missed about 4 years of notifications. I'm only seeing these comments after getting a notification it was closed.

Fascinating.

**Comment by jywarren** [comment]
:-) hi Bryan!!!
