### ISSUE TITLE
implement MapKnitter maps list, disable until implemented

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#280]
Firstly, disable the mapknitter tab view until something is implemented. This could be as easy as wrapping an if clause around the line which generates the tab and only displays it if there are indeed maps to show:
https://github.com/publiclab/plots2/blob/b8cb16e7706a47302c799294a2f48702cb2f410b/app/views/users/profile.html.erb#L86

If the maps tab is only showed when there are maps, then the current always-blank tab problem is resolved, and when it is fixed, users who have maps will have the tab displayed properly on their profile. So it's a decent long term fix to a short term problem.

Once the following ticket is completed, we want to use the MK RESTful API to parse map information from MK.
https://github.com/publiclab/mapknitter/issues/175

**Comment by jywarren** [comment]
I think this could be implemented via Ajax, using the MapKnitter RSS feed:

https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/dashboard.js

RSS feed for user "warren" (usernames are synced between MapKnitter and PublicLab.org: https://mapknitter.org/feeds/author/warren

**Comment by phillip-hogan** [comment]
Hi @jywarren does this need to be worked on still? I'd like to help.

**Comment by jywarren** [comment]
For sure! That'd be awesome. Tell me if you need a starting point or more
context for the fix!

I may be adding a proxy soon that could allow us to pull in the RSS feed in
Ajax, too.

**Comment by phillip-hogan** [comment]
Cool. So just to check I have this right:

Hide the map knitter tab unless there is something returned for that user on the MapKnitter RSS feed? Implement the feed with something similar to this: https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/dashboard.js ?

**Comment by jywarren** [comment]
Yep! And i believe we'll be able to make it work in IE by proxying the
feeds through our own server, since IE doesn't support cross origin
requests (CORS). This is why we're not quite done with the dashboard feeds
yet either.

Thanks!

**Comment by phillip-hogan** [comment]
How far back in IE do you want to support? I think we could get CORS working for IE 8 and above (it is supported in IE 10 by default I believe).

**Comment by jywarren** [comment]
Really? In the Spectral WOrkbench dashboard, users reported cross origin issues on IE 11, maybe it's how we implemented it? https://spectralworkbench.org/dashboard (requires login)

Screenshot, missing feed:

![swb](https://cloud.githubusercontent.com/assets/24359/14211838/35d7ac0e-f7fe-11e5-8584-139814b6ec47.png)


with feed, in chrome:

![unnamed](https://cloud.githubusercontent.com/assets/24359/14211867/523b86d6-f7fe-11e5-94d3-ae3d2d7f9a5e.png)

**Comment by phillip-hogan** [comment]
It looks like the XMLHttpRequest for https://publiclab.org/feed/tag/spectrometer.rss doesn't have 'Access-Control-Allow-Origin' set to anything in the response header - IE 10 and later will allow CORS as long as this is set I believe. For IE8-9 it requires some extra coding to get it to work. I only had a quick look but I believe it is possible.

**Comment by jywarren** [comment]
Oh, excellent. @icarito, is  'Access-Control-Allow-Origin' something we
should set in the application code or in the nginx conf? I can do it in the
code for sure.

Thanks, Phillip, that's very helpful. I believe Mapknitter has the correct
 'Access-Control-Allow-Origin' headers but tell me if it doesn't.

Let's aim for IE 10+ for starters.

**Comment by phillip-hogan** [comment]
Cool. I'll get into this on the weekend. Installed everything locally but my tests all fail for some reason.

**Comment by jywarren** [comment]
Hi, Phillip - we just realized a couple days ago that the tests pass in mysql but not in sqlite, which we refactored to support out of the box recently. I just merged in a fix which both gets all tests passing in mysql/sqlite, as well as adds/refines many of the tests. I think this should solve your issue, but if it does not, please post the errors and we'll take a look. Thanks!

You can get the new changes with `git pull https://github.com/publiclab/plots2.git master`

Incidentally, may I ask how you came across the codebase? We're looking to better understand how our developer outreach works. Feel free to email me directly at jeff@publiclab.org if you like, thanks!

**Comment by ananyo2012** [comment]
@jywarren Solved in #537. Please review.
