### ISSUE TITLE
404 error for embeddable features

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2817]
We have some content on other sites that are run through the Features system -- using urls like this one:

https://publiclab.org/features/embed/spectral-workbench-sidebar

I'm getting a 404 on that -- looks like a routing issue related to #2726  ?

**Comment by Souravirus** [comment]
yeah checking it locally

**Comment by Souravirus** [comment]
I am getting this when I tried to run this link locally @jywarren 
![screenshot from 2018-06-11 01-18-35](https://user-images.githubusercontent.com/17192149/41205681-818f0ea6-6d15-11e8-8004-8337c297a53f.png)
Check this out
