### ISSUE TITLE
Re-design of the Blog page

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#282]
Working to re-open the Public Lab Blog page. Below is the previous issue on this topic: 

sdosemagen commented on May 13, 2013
Design of blog page for new Public Lab website-- page breaks, etc.
@jywarren
Owner
 jywarren commented on May 13, 2013
perfect -- yeah just copy over whatever relevant info to this page

On Mon, May 13, 2013 at 12:22 PM, Shannon Dosemagen < notifications@github.com> wrote:
…
@sdosemagen
sdosemagen commented on May 13, 2013
http://publiclab.org/blog/idealab

From old thread w/ Jeff: It's actually for any tag -- you can view any tag at http://publiclab.org/blog/thermal-flashlight for example
@ebarry
ebarry commented on May 20, 2013
Also, let's decide where/how the link to the blog will be placed on front page of publiclab.org

in header?
in the sidebar like a featured widget?
TBD
@sdosemagen
sdosemagen commented on May 20, 2013
Jeff and I talked about this the other day. I was hoping that it would go in the header, but Jeff said that there wasn't room. Other possibilities include to break out the "About" tab into sections and include that as one of the sections or put it under the tools/place page, but my opinion is that it might get a bit hidden then. Would it make sense to have it as a bar under the "post research" or "create a wiki note" buttons?
@jywarren
Owner
 jywarren commented on May 20, 2013
Well, I meant that we *could* put it in the header, but we'd have to take
something else out -- or to expand into sub-menus, like the "tools/places"
menu item.
…
@jywarren
Owner
jywarren commented on Feb 20
Closing this for now as part of migration to new issue tracker, but feel free to open a new issue at https://github.com/publiclab/plots2/issues/ if you'd like; perhaps named "blog link in header" and with a suggestion of where to put it.

**Comment by jywarren** [comment]
Just correcting the issue name; the blog is already operating, it just needs more refinement

**Comment by jywarren** [comment]
Also linking to previous issue: https://github.com/jywarren/plots2/issues/126

**Comment by jywarren** [comment]
Need to:

* [ ] adjust line spacing of header
* [ ] reduce title side padding on mobile
* [ ] link to "about the blog"
