### ISSUE TITLE
Make username accept email prefixes

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2821]
### Please describe the problem (or idea)
Currently the username does not allow dot and some symbols which are present in the emails. As discussed in #2771, we will be using email_prefix appended with 2 digit string from the email as username for the OAuth login

**Comment by SidharthBansal** [comment]
@jywarren, 
>Worth exploring, for sure! Great to break it out. One quick way to use the
email prefixes without that blocking is to have a formatter that replaces
`.` with `_` -- then we can revert to allowing dots later if we pursue
that. Just to de-couple things and solve them one by one!

The current regex is 
``/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i`` for email 
and 
``/\A[A-Za-z\d_\-]+\z/`` for username.
So, email prefix is ``/\A[\w+\-.]+\z/i``

So, if we will add dot in username regex we will be done. 
Also, then we can have "email_prefix.g" for google , "email_prefix.f" for fb etc.

**Comment by jywarren** [comment]
Also the `@username` replacements in comments, nodes --

https://github.com/publiclab/plots2/blob/75c75533162ac202ae99c9e29d747e3065ef3096/config/initializers/constants.rb#L2-L5

**Comment by SidharthBansal** [comment]
Yeah, I was going to pin point that. But you are quicker than me :tada:

**Comment by jywarren** [comment]
lol i should stop replying i know you're super thorough... sometimes i just
can't stop!!! :-)

**Comment by SidharthBansal** [comment]
I am sure that ``email_prefix.g`` is best approach. Are you ok with it @jywarren? Shall I start with that?

**Comment by jywarren** [comment]
I think we can solve the broader issue first without implementing this. If
the initial version of oauth a) generates a unique name with numbers at the
end, and b) allows users to edit their name and "try out" usernames until
they find a unique one they like, with AJAX, then we can move that project
forward.

Later, if we want to try to add periods, we can. Sound good? One thing at a
time!

**Comment by SidharthBansal** [comment]
As we discussed 
a) You asked to create ``email_prefix`` +random_stuff, right? So, that email_prefix contains period so for sure we need to first change the username then we can carry on with #2771.
Emails do contain dots.

**Comment by jywarren** [comment]
But instead of doing both at once here, can we filter `bansal.sidharth2996` to `bansal_sidharth2996` so that we don't have to modify the constants and the Regex in the same PR? That's what I'd like to do - then circle back and make it more flexible. I'm just worried about periods in usernames because it will require so many changes and checks, it'll overcomplicate the main function we're going for (oauth) if we do it all together. 

Another I thought of is that `/profile/bansal.sidharth2996` would cause a routing issue - anything after the `.` is sometimes considered a `params[:format]` 

Although we can easily make a new route, I want to do these as separate steps and just be careful.

Thanks for thinking through this so deeply, Sidharth! Much appreciated 👍 👍 👍

**Comment by SidharthBansal** [comment]
OK so going for formatting now. Thanks a lot

**Comment by SidharthBansal** [comment]
![image](https://user-images.githubusercontent.com/20972099/41255168-4571d862-6de3-11e8-9c78-bc35a96dd168.png)

**Comment by jywarren** [comment]
awesome!

**Comment by SidharthBansal** [comment]
Done with formatting function.
![image](https://user-images.githubusercontent.com/20972099/41256295-c97503fc-6de6-11e8-96ef-1ab6200765a3.png)

I created a user with username bansal_sidharth2996 via basic sign up process.
Then tried to create a username from "bansal.sidharth2996@gmail.com"
This approach will have 0.01% failure scenario which we will happen only if 100 users have same username.

**Comment by SidharthBansal** [comment]
However, we can make this even less error prone if we append 2 digit character from following
>def generate_code(number) 
 charset = Array('A'..'Z') + Array('a'..'z')  + Array(0..9)
Array.new(number) { charset.sample }.join
end 
puts generate_code(2)


This will append 2 alphanumeric characters at the end of the string. The chances would be thus (1/62)*(1/62) *1%.

**Comment by SidharthBansal** [comment]
@jywarren made the following commit 
https://github.com/publiclab/plots2/pull/2771/commits/528bae53578a5cffc57240d25d45aa956f7612fc
I think now we can close this issue?
