### ISSUE TITLE
Ability to "like" comments with an emoji

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2822]
https://github.com/publiclab/plots2/issues/2498 and the solution https://github.com/publiclab/plots2/pull/2591 allowd for comment likes that have a "type". 

Let's imagine how to use that field to represent an emoji response -- like "smile" :smile: or "tada" 🎉  or "+1" 👍 

Then people could choose one (we might just offer a few common ones like GitHub does in comments) and people could provide feedback the same way as here in GitHub! Very friendly!

![screen shot 2018-06-11 at 12 28 10 pm](https://user-images.githubusercontent.com/24359/41244398-eda0e6e8-6d72-11e8-90f7-15633afc9177.png)

**Comment by ViditChitkara** [comment]
Hmm, actually I used the likeable type to identify if the like is on comment or answer or any other likeable type.
However, we can use the same terminology for this feature by keeping an emoji_type or something.
I would like to solve this!! Find this very interesting!!!!
Thanks

**Comment by ViditChitkara** [comment]
I love these kind of features!!! :wink:

**Comment by jywarren** [comment]
me too!!!

**Comment by namangupta01** [comment]
Hey i would like to work on it.

**Comment by ViditChitkara** [comment]
Hi @namangupta01 , I have already started with this! Will soon send a pr for this!! Sorry for delaying this..

**Comment by namangupta01** [comment]
Sure! Go on. I thought no one is working on this.

**Comment by ViditChitkara** [comment]
cool :+1:
