### ISSUE TITLE
Add WelcomeBot to our chatroom

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#283]
We could add a WelcomeBot to our chatroom. Here's an awesome one that Shauna of OpenHatch wrote: https://github.com/shaunagm/welcomebot

This is how it works in the openhatch chatroom: 
welcomebot: 
Welcome lizbarry!  The channel is pretty quiet right now, so I thought I'd say hello, and ping some people (like shauna, paulproteus, and marktraceur) that you're here.  If no one responds for a while, try emailing us at hello@openhatch.org or just try coming back later.  FYI, you're now on my list of known nicknames, so I won't bother you again.

**Comment by btbonval** [comment]
Looks like the welcome bot is in Python, so we won't be able to run it alongside any of our current web stacks. At least I don't think there are any Pythonic web stacks.

There is probably little to no developer work required here, it is more of an admin / IT task of finding the right system to put it on and ensuring it runs.

**Comment by jywarren** [comment]
@ryzokuken do you think we're ready for this old one?

**Comment by SidharthBansal** [comment]
@jywarren i think we can close this issue
