### ISSUE TITLE
Deprecate remaining old DrupalUser code for plain User model

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2838]
This used to be a Drupal site, so users are managed across two models, but we're gradually and carefully getting rid of all old `DrupalUser` code. (this is a break-out issue from #956)

Currently we're almost done migrating all functions of `DrupalUser` to `User`, but we'd have to complete this, with `DrupalUser` code appearing throughout the site.

A good place to start would be to begin refactoring all instances of `DrupalUser` to `User` - and removing the ones that simply alias the two together (except for anything in `/migrations/`):

https://github.com/publiclab/plots2/search?utf8=%E2%9C%93&q=drupaluser&type=

Any instance of `user.user` or `user.drupal_user` is likewise an effort to alias, so those can also be substituted with just `user`

https://github.com/publiclab/plots2/search?utf8=%E2%9C%93&q=drupal_user&type=

Lots will probably break when this is done! But it should be reparable and I'm happy to help folks get through this to get our tests passing once again. We're ready for this! 👍 Any help appreciated!

**Comment by Neidley** [comment]
I'd be willing to help. Not familiar with Drupal but I'm intermediate in ruby.

**Comment by jywarren** [comment]
Oh awesome! Yes please, and if you open a PR we'll be happy to help out!

**Comment by Neidley** [comment]
Do most people open a PR and then work on the branch or open the PR at the end?

**Comment by jywarren** [comment]
We prefer a PR early so we can coordinate and help out!

On Jun 19, 2018 11:44 AM, "Andrew Neidley" <notifications@github.com> wrote:

Do most people open a PR and then work on the branch or open the PR at the
end?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/2838#issuecomment-398446712>,
or mute the thread

**Comment by Neidley** [comment]
https://github.com/publiclab/plots2/pull/2857

**Comment by Neidley** [comment]
should have our `drupal_user`s and `DrupalUser`s refractored to `user` and `User` respectively! 👍

**Comment by Neidley** [comment]
I've done my best to update `DrupalUser` to `User` and `drupal_user` to `user`.

Now on to getting tests to pass

**Comment by jywarren** [comment]
😄 awesome!
