### ISSUE TITLE
Rearrange "about" drop down

### ISSUE THREAD

**Issue by sdosemagen** [publiclab/plots2#284]
About Public Lab 
Blog (this needs to be readded)
Stories

**Comment by jywarren** [comment]
Is this ready to go, now? @steviepubliclab was going to do a launch post, I think.

**Comment by steviepubliclab** [comment]
I'd like to work on the wiki page as well for posting. I'll work on this
this week.
-Stevie

**Comment by jywarren** [comment]
http://publiclab.org/wiki/blog now active; I think we're ready for the navbar changes as soon as there's new content? http://publiclab.org/blog
