### ISSUE TITLE
Community Check-in #5 Summer Of Code Week 6

### ISSUE THREAD

**Issue by ViditChitkara** [publiclab/plots2#2840]
Hi everybody :construction_worker_man: !
If you're new here, welcome, and please try some of the ftos. This is a checklist for publiclab/soc.

@stefannibrasil @milaaraujo @MargaretAN9 @Gauravano @namangupta01 @ViditChitkara @tech4GT  @mridulnagpal @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @ccpandhare @icarito @abTest-123 @steviepubliclab @ebarry @publiclab/soc @publiclab/reviewers

How was your weekend? How are you doing? What is your plan for this week?
**If you have not planned yet. Just leave a Hi! so that we could know that you are well.** :small_airplane: 

As of now, I am done with some of the small features like emoji auto-complete in comments. :smile:  The daily/weekly digest is complete but still facing some redis connection issues. Once the redis issue is solved, it would be good to test. :mailbox:  This week I would be working on like comment via multiple reactions(just like github) and starting with the suggestion via comments feature.
It has been a fascinating and enjoyable summer working with publiclab!! :tada: :tada: 
Also, I want to thank @jywarren for his lovely feedback during my first evaluation.

## 'Til next week!

As always, if you're waiting for a review, or if you're stuck,  please request help
here OR leave a comment with @publiclab/soc and @publiclab/reviewers for
some input.

Happy coding 🎉  !

**Comment by SidharthBansal** [comment]
Hi @publiclab/soc,
we have successfully passed the first evaluation :tada:  :tada: :tada: :100: 
I am feeling awesome working at public labs in this summer. Thanks @jywarren for the nice feedback provided on my GSOC evaluation.
I have completed 90% of the first project (OAuth) in the enormous PR #2771. The google provider is working on localhost. Let's hope that it works on production. As work in my project is sequential, once the pr #2771 gets merged, I will start working on github provider. I will write the views and the tests for the provider in 2 different prs. My github app is working.
@jywarren there is good news --> now twitter gives email through advance settings. So, we will be using the existing code as present in #2771 for twitter too. :tada:

**Comment by Souravirus** [comment]
Hi @publiclab/soc,
First of all thanks to the mentors for the nice feedback provided on my GSoC evaluation. Currently, I am working on rails 5.1 upgrade in this PR #2798 by clearing out the errors in the tests.
Thanks!!

**Comment by ryzokuken** [comment]
Thanks to all students for such awesome work and congratulations. You all deserved every single bit of the appreciation. Looking forward to the rest of the summer.

**Comment by Gauravano** [comment]
Hi @publiclab/soc ing 
This week, I would be completing the second part of Draft Feature, finalizing welcome mailer for our website. With this, I would be solving small issues too.
Thanks.

**Comment by sagarpreet-chadha** [comment]
Hi all :octocat:  !
I have been closely following everyone's work and everyone is doing amazing work 🎉 ❣️ 

So this week i will be tackling new layers and hopefully try to conclude with @namangupta01  the best way to use twitter API so that we implement the Reply via Twitter 🐦  feature .

Earlier today ...i had a video conference 🎥 with John Dawes from http://waterreporter.org/ . 
So for using their API i had contacted Water Reporter organization as their API is not open . So the meeting was regarding the discussion of how we can use their API and about the _Leaflet-Environmental-layer_ project and he also told about the aim of their organization . John was really helpful and he will soon give us the access to the API endpoints .  
He may also help with pop-up styling of the markers as well 🗺  ! Thanks waterreporter.org/  !
A glimpse of the discussion : 
<img width="1439" alt="screen shot 2018-06-20 at 9 35 27 pm" src="https://user-images.githubusercontent.com/14952645/41680130-173c1400-74ee-11e8-96e1-2795a6fcbd26.png">

**Comment by jywarren** [comment]
Hi all! We just published a LOT of your code to PublicLab.org -- with help from @icarito.

That includes Rails 5.1! And...

![vidit is amazing](https://user-images.githubusercontent.com/24359/41736595-00986862-755b-11e8-8004-2c7f3d878c95.png)

**Comment by jywarren** [comment]
AND - a special request from @SidharthBansal -- in an Incognito window, if you could please test this:

https://publiclab.org/auth/google_oauth2

😄 👍

**Comment by jywarren** [comment]
... did it work???

**Comment by SidharthBansal** [comment]
I tried it is working fine. I am able to log in, log out, delink the provider, link up the provider, sign in properly.
How is it with @publiclab/soc ?

**Comment by stefannibrasil** [comment]
Yeah, me too, amazing! :tada:

**Comment by Gauravano** [comment]
Its working @SidharthBansal. Awesome work!

**Comment by namangupta01** [comment]
Hello everyone! This week we have deployed mailman reply-by-email work on stable to test out the features. We are receiving emails but there are coming some error while connecting mailman service to db. But we will figure it out soon. And hope we will going to see this feature live soooon. 😄

**Comment by Gauravano** [comment]
That's great @namangupta01 !

**Comment by SidharthBansal** [comment]
That's awesome @namangupta01

**Comment by namangupta01** [comment]
Hi all, I will do this week check-in. Will open in a while. Thanks!!!!!

**Comment by namangupta01** [comment]
Moved to #2911
