### ISSUE TITLE
some parent:XXXX tags aren't working

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2845]
Via @ebarry --

> does anyone have any ideas why some parent:XXXX tags aren't working at the moment? I'm having trouble organizing the /barnraising pages and would love to be able to use parent:barnraising to help. Thanks!

**Comment by jywarren** [comment]
I believe this is because it's looking for a page like `/wiki/barnraising` -- and `/barnraising` is a special root-level page. I made a tweak in #2844 that I think will fix this!

**Comment by ebarry** [comment]
You guys are awesome!!!!! I look forward to "parenting" exuberantly! Thank
you!!!!
