### ISSUE TITLE
Profile page upon not signed in should redirect to root url

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2853]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

When a user is logged in /profile redirect to /profile/user_who_is_logged_in. But when the user is not logged in, it shows the following error
![image](https://user-images.githubusercontent.com/20972099/41595468-82584b38-73e4-11e8-8a1f-fc57849e6ea4.png)
However, it should redirect to publiclab.org

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Insert** into the https://github.com/publiclab/plots2/blob/7a329b36fb8e588bb76f06343782ca698a3af499/app/controllers/users_controller.rb#L122
>    elsif !current_user && params[:id].nil?
      redirect_to "/"

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by imacubsfan23** [comment]
I'll gladly take this issue @SidharthBansal . This will be my first pr that wasn't documentation.

**Comment by SidharthBansal** [comment]
Great..go for it

**Comment by imacubsfan23** [comment]
How can I get this to run locally (with rails s)? More specifically, which database.yml do I use when running rake db:migrate?

**Comment by SidharthBansal** [comment]
#2863 closes this
