### ISSUE TITLE
Create Github OAuth App 

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2856]
Github settings as given on https://www.natashatherobot.com/rails-omniauth-github-tutorial/ are functional as tested in test app.
![image](https://user-images.githubusercontent.com/20972099/41200890-901a4e40-6cca-11e8-88d0-556c56c2a059.png)
![image](https://user-images.githubusercontent.com/20972099/41201250-c7fc3d62-6cd1-11e8-9824-842dba15eaa4.png)
![image](https://user-images.githubusercontent.com/20972099/41201253-ce91793a-6cd1-11e8-86ed-bdf8ebf7c57d.png)
We need to verify that the following will work properly for all users:
* [ ] localhost:3000/auth/github
* [ ] localhost:3001/auth/github
* [x] unstable.publiclab.org/auth/github
* [x] stable.publiclab.org/auth/github
* [x] publiclab.org/auth/github

**Comment by SidharthBansal** [comment]
@jywarren this needs to be done after #2771 is merged and google works perfectly in production.

**Comment by SidharthBansal** [comment]
Part of #2676

**Comment by jywarren** [comment]
Hi, this looks great. Can you create an "Oauth Login" milestone and add and prioritize things in there? I think it'll be helpful to keep track. Thanks!!!

**Comment by SidharthBansal** [comment]
I have created #2676 as main issue for the milestone OAUTH LOGIN. I have written each and every needy greedy detail of all the linked issues. I hope this will reduce the ambiguity which we are facing nowadays.

**Comment by jywarren** [comment]
:-) awesome!!!

**Comment by SidharthBansal** [comment]
I am done with github provider. Whenever you get time you can make github app.
Thanks

**Comment by jywarren** [comment]
OK, so i should make multiple apps, one for each environment, like localhost:3000, stable, unstable...?

**Comment by jywarren** [comment]
And what env variable name should I use? `OAUTH_GITHUB_APP_KEY` and `OAUTH_GITHUB_APP_SECRET`?

**Comment by SidharthBansal** [comment]
Yeah.

**Comment by jywarren** [comment]
Are the localhost ones really necessary? Could people build those themselves?

**Comment by jywarren** [comment]
The others are done and installed on Jenkins and production though!

**Comment by SidharthBansal** [comment]
localhost ones can be made by developers.

**Comment by SidharthBansal** [comment]
>The others are done and installed on Jenkins and production though!

Have you completed the github developer apps settings?

**Comment by SidharthBansal** [comment]
But the feature will not be present in localhost. Developers will not be able to login and logout via providers

**Comment by jywarren** [comment]
Yes i think so!

**Comment by SidharthBansal** [comment]
No they are not. 
@jywarren this is Github issue. I think you are talking about #2892.

The link stable.publiclab.org/auth/`github` is not functional

**Comment by SidharthBansal** [comment]
Can we first finish up #2892 and then jump into this.

**Comment by jywarren** [comment]
No, i just set it all up for GitHub going through the steps above. But I haven't pushed to stable since this morning; i can now.

**Comment by SidharthBansal** [comment]
Ok. Let's push there and see.

**Comment by SidharthBansal** [comment]
Hurray
![image](https://user-images.githubusercontent.com/20972099/41942415-0766a080-79bd-11e8-8924-262ea81dccac.png)
It is working fine on stable

**Comment by SidharthBansal** [comment]
@jywarren I guess you wrote your name instead of Public lab.
Github asks to sign in ``jywarren`` instead of ``public lab``.
Can you please change that?
Thanks

**Comment by jywarren** [comment]
it works!

**Comment by jywarren** [comment]
Ah oops!

**Comment by jywarren** [comment]
how about now?

**Comment by SidharthBansal** [comment]
stable working fine
unstable bad gateway error
pl.org not functional

**Comment by jywarren** [comment]
It's not published to production yet -- and not to unstable, but you can push it there!

**Comment by jywarren** [comment]
publishing to production now

**Comment by SidharthBansal** [comment]
All the changes are in now in master branch as all of them are merged. So, for the unstable shall I force push the master branch?

**Comment by SidharthBansal** [comment]
Pushing to unstable

**Comment by SidharthBansal** [comment]
Unstable shows 502 Bad Gateway

**Comment by SidharthBansal** [comment]
We are done with unstable 
![image](https://user-images.githubusercontent.com/20972099/41943541-6e22a95a-79c1-11e8-9df8-789c2667263e.png)
Thanks @jywarren

**Comment by SidharthBansal** [comment]
![image](https://user-images.githubusercontent.com/20972099/41943822-b10bf978-79c2-11e8-8d4b-38cf566dcb75.png)
We are done with PL.org
Thanks a lot @jywarren

**Comment by SidharthBansal** [comment]
Now we are back to localhost:3000 and localhost:3001.
What do we need to do for them?
I will suggest that the developer should create their account themselves OR we can make an app for the developer. Here we don't have to do any ``domain verification ``as we did in case of Google. So, this will be pretty simple.

**Comment by jywarren** [comment]
But we can also provide documentation for how to set it up.

**Comment by jywarren** [comment]
Let's for the time being ask the developer to do it for themselves. I think
that's reasonable -- if we find we need to do a lot more work on them,
maybe we can change our minds. What do you think?

**Comment by jywarren** [comment]
yep that's how `unstable` works. Super!

**Comment by SidharthBansal** [comment]
And
THANKS A LOT for making 3 apps for GitHub provider.

**Comment by jywarren** [comment]
I like this idea! OK -- so, should we openly share the app id then?

**Comment by jywarren** [comment]
and the secret? I have a localhost:3000 one ready

**Comment by SidharthBansal** [comment]
Can you check if jenkins development environment variables can work?
If they can work then it would be best.

**Comment by SidharthBansal** [comment]
I mean set up the environment variables for development too as you set up for production. Then we can test.

**Comment by jywarren** [comment]
Oh, but we run Jenkins builds in production environment. Ah, you mean temporarily replace them and test it out? Sure, i can do that tomorrow morning. But how would we help people use them locally?

**Comment by SidharthBansal** [comment]
>and the secret?

Sorry you cannot send your app_secret to anyone. I sent you because I can trust you. And I will delete the app in a week or two when we will finish up with Google completely. But you cannot trust on the new developers

**Comment by SidharthBansal** [comment]
I was refering to the way you wrote in https://github.com/publiclab/plots2/pull/2855#issuecomment-398864238

**Comment by jywarren** [comment]
That's fine, i just am not sure for whom we are setting up the developer app... are we just testing that it works at all? If we're not distributing a secret key, folks won't be able to try it locally. Sorry if I'm missing something really obvious here!

**Comment by SidharthBansal** [comment]
> for whom we are setting up the developer app... are we just testing that it works at all?

For the future developers maybe after 3-4 years who will need to change the authentication system for its improvement. I am concerned about future.

Secondly, the developers will be able to log in and log out via localhost:3000 via providers. Otherwise when new developers will try to login via provider they will get errors and they will report them as issues on public lab.

**Comment by SidharthBansal** [comment]
> If we're not distributing a secret key, folks won't be able to try it locally.

They can try it on localhost only if they make their own developer's app. Else they will get errors. I am concerned about those errors.

**Comment by SidharthBansal** [comment]
Errors like ``missing client_id`` etc. when they will try to log in via provider.

The existing login system will work on the localhost too for them.

**Comment by jywarren** [comment]
Ah, so you would just like to debug the errors one gets when doing this
from localhost?

**Comment by SidharthBansal** [comment]
Yes.

**Comment by SidharthBansal** [comment]
One way is to use  ``<% if Rails.env == "production"%>`` for the views. This will not let the developers sign in via provider until they go to localhost:xxxx/auth/:provider. And write documentation for setting up app.
What do you say?
