### ISSUE TITLE
the death of research note templates?

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/plots2#286]
I noticed recently that I no longer get a template when I write a research note. Is that deliberate?

![screen shot 2015-05-27 at 10 24 55 pm](https://cloud.githubusercontent.com/assets/1203280/7853172/70baaaac-04bf-11e5-8543-fbf3c8d25d48.png)

**Comment by jywarren** [comment]
Oh, that's a bug! Thanks for reporting.
