### ISSUE TITLE
OAuth user interface design on login screen

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2866]
@SidharthBansal - i wanted to share how Oauth looks on some other sites, so once we confirm it's perfectly working, we have a good workflow for login. See this example:

![screen shot 2018-06-20 at 9 42 43 am](https://user-images.githubusercontent.com/24359/41662200-91b3a82c-746e-11e8-90ec-78fa81ea77ac.png)

Note a couple things. First, since OAuth is easier, it's presented first. Then, I wonder if we can have the remainder of the non-OAuth screen be hidden until you interact with the first input... so as to keep things simple. Once you click or type in it, then the rest is shown. That way also it's clear that you can ignore it if you're using OAuth. 

What do you think?

**Comment by SidharthBansal** [comment]
You mean to replace 
![image](https://user-images.githubusercontent.com/20972099/41663466-22aa83e4-74c1-11e8-85d1-93691d93901e.png) 
with the image which you have given.
Great idea. I love it.
This closes #2849 and #2859. 
>First, since OAuth is easier, it's presented first. Then, I wonder if we can have the remainder of the non-OAuth screen be hidden until you interact with the first input... so as to keep things simple. Once you click or type in it, then the rest is shown. That way also it's clear that you can ignore it if you're using OAuth.

Great idea. I will love to implement.

**Comment by jywarren** [comment]
Actually so i guess this is 2 issues - we could adopt this design for the
/signup page, and ALSO for the /login page and the login dropdowns. So
maybe even 3! We can wait until it's all working smoothly though!

**Comment by SidharthBansal** [comment]
I have created #2676 as one issue for the milestone OAUTH LOGIN. I have written each and every needy greedy detail of all the linked issues. I hope this will reduce the ambiguity which we are facing nowadays.

**Comment by SidharthBansal** [comment]
>Actually so i guess this is 2 issues - we could adopt this design for the /signup page, and ALSO for the /login page and the login dropdowns. So maybe even 3! We can wait until it's all working smoothly though!

But for the signup and login page we don't need a pop up which we will need for the header. They will be similar but not same.

**Comment by jywarren** [comment]
agreed!

**Comment by jywarren** [comment]
Oh, but we can work from #2859 - that's a great start! 

![](https://user-images.githubusercontent.com/20972099/41615129-0f4ce2c8-7418-11e8-971b-e976d97aeb95.png)

**Comment by SidharthBansal** [comment]
How would it be that first we will do as #2859 and then we modify it to pop window?
I do agree with you. Reopening the pr. And linking it to this issue

**Comment by SidharthBansal** [comment]
This issue needs to be tackled once we are completed with backend for all 4 providers

**Comment by SidharthBansal** [comment]
@jywarren can you please see all the 4 pages on main website. I was successful in breaking the front end into ftos as per your suggestions and PL guidelines of increasing PL community. What else is left in the following pages?
* [ ] /login
* [ ] /signup
* [ ] /profile/edit
* [ ] header
Things which seems complete to you please check them.

**Comment by SidharthBansal** [comment]
![screen shot 2018-06-20 at 9 42 43 am](https://user-images.githubusercontent.com/24359/41662200-91b3a82c-746e-11e8-90ec-78fa81ea77ac.png)
will require the Login button to be replaced by a modal. All stuff is complete in the header. So, I will be creating a fto for this issue after fixing the errors which has arisen in this week

**Comment by SidharthBansal** [comment]
You can try https://github.com/publiclab/plots2/issues?q=is%3Aopen+is%3Aissue+label%3Abug
OR https://github.com/publiclab/plots2/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Ahelp-wanted+ also

**Comment by SidharthBansal** [comment]
We can ask students to give designs for login modal in gci. Then we can break this into code segments.
This issue has instance count of 10

**Comment by dinaelhanan** [comment]
@SidharthBansal Hi! I'm looking into this as I am doing gci. For that task, do we design a similar login screen or actually create on? Thanks!

**Comment by SidharthBansal** [comment]
We need to do both.

**Comment by dinaelhanan** [comment]
Oh ok, thanks for clarifying

**Comment by jywarren** [comment]
We can start with sharing designs - esp. for the login dropdown on any https://publiclab.org page, and/or specifically in a modal for when you want to log in from a prompt lower down on a page. Say, if you are not logged in but want to log in from a `Log in` button at the bottom of the comments on a page like this:

https://publiclab.org/notes/warren/10-23-2018/call-for-outreachy-2018-19-proposals

Thanks, we'd love your help!

**Comment by dinaelhanan** [comment]
@jywarren I'm new to web dev, so bare with me, as this one seems like a challenge, but one I want to take on. I'm just wondering, how would I integrate this (what files/pages would need to be changed?) I've only every done this on a blank site, and doing it on something pre-existing is new to me.

**Comment by SidharthBansal** [comment]
Yeah.

**Comment by jywarren** [comment]
awesome, thanks!

**Comment by SidharthBansal** [comment]
You can tell us your design.
:-)

**Comment by oorjitchowdhary** [comment]
![fda0bffe-9acc-4724-a817-b8c076f9a2eb](https://user-images.githubusercontent.com/39333058/49332210-ddea7b80-f5ce-11e8-9708-1a26ec8ef8cd.jpeg)
Just as a suggestion though.. I feel minimalistic would look better.. But we can choose any one as per everyone's views

**Comment by jywarren** [comment]
This is cool. I think we can incorporate elements of this. In general, I'm
interested in seeing the arrangement of buttons, windows, messages, links,
forms, titles, etc... whereas the graphic style may be best drawn from
Bootstrap, which is the UI library we use, so best to stay consistent with
that. However, there are a million ways to organize buttons, forms, etc
etc! So I like seeing this Oorjit, thank you!

**Comment by oorjitchowdhary** [comment]
Can anyone pls tell help me with the code files to be edited in this issue...

**Comment by SidharthBansal** [comment]
We need to create a modal for the login which will be displayed on the
screen once anyone will click on any login button.

**Comment by dinaelhanan** [comment]
@JonathanXu1 I think it's safe to say... feel free to take it up 👍

**Comment by JonathanXu1** [comment]
Great, I've gone ahead and claimed it. :)

**Comment by JonathanXu1** [comment]
Given that we already have the login buttons redirect to a login page, do we simply show a modal instead? 

Also if we want to show/hide conventional login styles, should that be done through a button like "log in with email and password" to avoid the chance of the user thinking there is no conventional way to log in?

**Comment by dinaelhanan** [comment]
@JonathanXu1 I would start with a button on the original login page that hides entering the email password etc and only shows OAuth until you click the button. Then, you could try moving that whole page as a modal. I wonder if it's OK to have it as a pop-up, I've seen some sites do that. Google included. Let me know what you think

**Comment by JonathanXu1** [comment]
That's a very good idea. I'm just not sure how to find the source code for the login.

**Comment by dinaelhanan** [comment]
@JonathanXu1 What code editor are you using? Maybe you could look for the id/class of the login page? I'm done for today, But I'll write more tomorrow and help you out :)

**Comment by JonathanXu1** [comment]
Yep, my first step is to search for the the corresponding divs in the project, but I'm wondering if there's a better way to do it within the ruby environment. Thanks for your help, I appreciate it :)

**Comment by oorjitchowdhary** [comment]
@JonathanXu1 are you working on this?

**Comment by JonathanXu1** [comment]
Yes, I am

**Comment by oorjitchowdhary** [comment]
Okay.. Feel free to mention me if you need any help..

**Comment by jywarren** [comment]
Just noting that log in code in the header is within 

https://github.com/publiclab/plots2/tree/master/app/views/layouts/_header.html.erb but in the partial

https://github.com/publiclab/plots2/blob/master/app/views/layouts/_social_icons.html.erb

while on the /login or /signup pages, it's at:

https://github.com/publiclab/plots2/blob/master/app/views/user_sessions/new.html.erb

https://github.com/publiclab/plots2/blob/master/app/views/users/_form.html.erb#L13 (note here it's referencing the partial template from above)

I like the idea of tackling this in separate smaller parts!

**Comment by JonathanXu1** [comment]
Hey, I've managed to hide the traditional login and have allowed for it to be shown when a button is pressed. Here is the demo on the login pane:
![login](https://user-images.githubusercontent.com/22998430/49548903-319de300-f8b5-11e8-8ef0-691224aa7c26.gif)

And on the signup pane:
![signup](https://user-images.githubusercontent.com/22998430/49548908-36629700-f8b5-11e8-9db0-a094b23c2f10.gif)

Now to make the modal..

**Comment by dinaelhanan** [comment]
@JonathanXu1 that's so cool! Keep going it looks amazing!

**Comment by jywarren** [comment]
This is great. A couple thoughts -- perhaps, for people running things
locally where the OAuth versions aren't available, we could have it show by
default in cases where that's the only way to log in? Second, I was
thinking we could ditch the "OR" and just show an icon matching the other
OAuth icons (facebook, twitter) but with an envelope... as the last option
in the same row. What do you think?

Thanks so much!!!

**Comment by JonathanXu1** [comment]
Sounds good. I'm unable to view the icons because I'm getting the error: 
![image](https://user-images.githubusercontent.com/22998430/49550309-25b42000-f8b9-11e8-9648-f68342ac5619.png)

**Comment by JonathanXu1** [comment]
Also I was wondering about the syntax for including new.html.erb as a component in the modal.

**Comment by JonathanXu1** [comment]
@jywarren could I get an extension? I have 15 hours left.

**Comment by jywarren** [comment]
of course - i'll extend now. For the errors, I don't think those should be
stopping you from viewing HTML/CSS -- they're warnings from the Facebook
widgets. What do you see on your screen?

Keep up the good work!

**Comment by JonathanXu1** [comment]
Thanks for the extension :)

This is what I currently see: 
![image](https://user-images.githubusercontent.com/22998430/49552362-2a7cd200-f8c1-11e8-9888-8eecd51b5c9b.png)
^ So no icons display whatsoever

Also I'm having issues when I try to include the following in my modal:
**<%= render partial: 'user_sessions/new' %>**

**Comment by SidharthBansal** [comment]
>>for people running things
locally where the OAuth versions aren't available, we could have it show by
default in cases where that's the only way to log in? 

Oauth works well on the localhost, just you need to configure the keys.

**Comment by oorjitchowdhary** [comment]
Even I wasn't able to see the social icons on running localhost when I was doing my PR #4116 
@SidharthBansal How can I configure the keys?

**Comment by SidharthBansal** [comment]
@JonathanXu1 we can delete Rails.production line from all the places for social link icons.
This will avoid the further confusions happening.

**Comment by SidharthBansal** [comment]
https://github.com/publiclab/plots2/pull/4148 created this. I hope now we can create the modal easily.

**Comment by JonathanXu1** [comment]
Hi, I've gotten the icons to appear and moved the login within a modal. The email login is also toggle-able with the email button.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/22998430/49605947-f60c2300-f95f-11e8-9dbf-72212fa11c36.gif)

**Comment by SidharthBansal** [comment]
I think it will be better to show the text instead of icon. Icon seems confusing to me.

Well done!!!
Can you tell the PR number?

**Comment by JonathanXu1** [comment]
It's #4113 . I believe @jywarren requested for an icon, so I changed my original button to that.

**Comment by SidharthBansal** [comment]
I think you misspelled the pr number. OK. Changes looks awesome to me.

**Comment by JonathanXu1** [comment]
It's #4113 . I believe @jywarren requested for an icon, so I changed my original button to that.

**Comment by jywarren** [comment]
I think the icon looks good as "one mode of logging in" but perhaps some
extra explanatory text would help -- something like this -- and maybe we
should still say OR but it could be between the buttons?
Click to log in with one of these methods:

[1] [2] [3] or [email]

What do you think? It's really helpful to see the gif, thank you!

**Comment by SidharthBansal** [comment]
Yeah, we can write email below the icon and have ``OR`` between them.
Great idea Jeff.

**Comment by JonathanXu1** [comment]
How's this?
![image](https://user-images.githubusercontent.com/22998430/49609312-1b515f00-f969-11e8-8ce4-ac4c111e8cd5.png)

**Comment by SidharthBansal** [comment]
Place ``OR`` between social media icons and Login with email

**Comment by jywarren** [comment]
This looks great. I have a slight preference for the bootstrap
"btn-default" style, which is black text on a white button with grey
outline, but i'm not super intense about it! :-)

**Comment by SidharthBansal** [comment]
@JonathanXu1 please continue the conversation in the PR, instead of issue.

**Comment by JonathanXu1** [comment]
![image](https://user-images.githubusercontent.com/22998430/49611766-95391680-f970-11e8-835d-8615f2e99587.png)

**Comment by jywarren** [comment]
Ah super - but sorry, i had meant to leave the text inputs visible as you'd
originally done -- thank you! And could you add 20px padding on the bottom
of the modal? It's a bit squished. Is it just me, or is the modal not quite
centered, too?

This is looking tremendous!!! Thanks for your excellent work!

**Comment by SidharthBansal** [comment]
I agree the modal needs to be centered on the screen.

**Comment by JonathanXu1** [comment]
I believe the slight off-center horizontally is because of the styling of the internal login partial. There's an offset and some padding I believe. I'll look into it.

**Comment by SidharthBansal** [comment]
ok great!
I was referring to centring the modal on the screen. Modal is aligned to
the top. We need it to be centered.

**Comment by SidharthBansal** [comment]
Moved to #4173
