### ISSUE TITLE
Facebook OAuth Settings

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2867]
These are the Facebook OAuth settings for future reference. 
Part of #2676 
Facebook oauth settings 
The Facebook settings need to be as follows
![image](https://user-images.githubusercontent.com/20972099/40996771-4b4ff9f2-6920-11e8-98df-8976d52bc5ad.png)
![image](https://user-images.githubusercontent.com/20972099/40996803-620b79b4-6920-11e8-976b-20956e0b0b88.png)
![image](https://user-images.githubusercontent.com/20972099/40996819-71473d5a-6920-11e8-9631-9e38a4e69273.png)
![image](https://user-images.githubusercontent.com/20972099/40996830-7883f96e-6920-11e8-9e87-2a393eda0a7a.png)
![image](https://user-images.githubusercontent.com/20972099/40996840-844a4ab4-6920-11e8-9f61-99e6bb60d258.png)
We need to verify that the following will work properly for all users:
* [x] https://localhost:3001/auth/facebook
* [x] unstable.publiclab.org/auth/facebook
* [x] stable.publiclab.org/auth/facebook
* [x] publiclab.org/auth/facebook

**Comment by SidharthBansal** [comment]
``OAUTH2 Error`` is produced if we have any old gem out of following
* gem `omniauth`
* gem `facebook-omniauth`

**Comment by SidharthBansal** [comment]
Facebook works only on `3001`(https) in development

**Comment by jywarren** [comment]
Hi, where is the link to start this process on facebook.com? I'd like to do this today or tomorrow in preparation. Thanks!

**Comment by SidharthBansal** [comment]
``developers.facebook.com`` should work

**Comment by SidharthBansal** [comment]
@jywarren please merge the #2959 and #2960 before setting up app for facebook.
On my localhost it is working absolutely fine. I hope it will work well in production too.

**Comment by jywarren** [comment]
This is now set up!

**Comment by SidharthBansal** [comment]
Have you pushed it to stable and production?

**Comment by jywarren** [comment]
I did to stable but i'm seeing some build issues... pinged sebastian in the
chatroom so let's see. I don't want to publish to production until we see
it running smoothly in stable.

Thanks!

**Comment by jywarren** [comment]
Yes, unstable is installed.

**Comment by jywarren** [comment]
hmm... 

```
Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.
```

but stable.publiclab.org is actually included...?

**Comment by jywarren** [comment]
weird

**Comment by jywarren** [comment]
https://www.facebook.com/v2.6/dialog/oauth?client_id=644692375883090&redirect_uri=https%3A%2F%2Fstable.publiclab.org%2Fauth%2Ffacebook%2Fcallback&response_type=code&scope=email&state=aedc1ea11d9ef3f8463a7e6bb0b06106a4042befd33de8d0

**Comment by SidharthBansal** [comment]
It means that you need to add domains and subdomains somewhere in the app.

**Comment by jywarren** [comment]
But I did that... maybe i'm missing something?

![image](https://user-images.githubusercontent.com/24359/42237394-a692015a-7ecb-11e8-80b3-c3d33a9d9c1a.png)

**Comment by jywarren** [comment]
I set namespace to `publiclab` - is that wrong?

**Comment by SidharthBansal** [comment]
I think it is right

**Comment by jywarren** [comment]
Hmm, what else should we try?

**Comment by jywarren** [comment]
It's late there! Let's think about this tomorrow!

**Comment by SidharthBansal** [comment]
Yeah sure. Sleeping now.

**Comment by jywarren** [comment]
Hey, figured it out! 

![screen shot 2018-07-03 at 6 43 37 pm](https://user-images.githubusercontent.com/24359/42247928-18414fd4-7ef1-11e8-8ec7-9bd570cdea1b.png)

It was the callback that had to be set!

**Comment by jywarren** [comment]
It works now! https://publiclab.org/auth/facebook/

**Comment by jywarren** [comment]
Just as you'd shown above. I missed that somehow! Too tired out!

**Comment by SidharthBansal** [comment]
Btw I was not able to sleep. I was searching the net.

**Comment by SidharthBansal** [comment]
It is working fine in production 
![image](https://user-images.githubusercontent.com/20972099/42248004-1c86b5a2-7f41-11e8-9db0-a3c119d636c0.png)

**Comment by jywarren** [comment]
hooray!!!

**Comment by SidharthBansal** [comment]
Working fine on unstable
![image](https://user-images.githubusercontent.com/20972099/42248038-4d6e696c-7f41-11e8-9206-22c8b5101cbd.png)

**Comment by SidharthBansal** [comment]
Now we are completed with this.
Thanks a lot @jywarren for bearing with me for so many app and so many providers.
Thanks a ton.
Now we are completed with the Oauth project. I guess. Do we need any other provider?

**Comment by SidharthBansal** [comment]
I mean the backend stuff.

**Comment by SidharthBansal** [comment]
Can we create first timer issues for the font-awesome icons? OR shall I complete them?

**Comment by jywarren** [comment]
Just the UI for the buttons on the signup forms and such!

We could brainstorm also what other things we can do with these
integrations now. Better integrated Post to Twitter or Post to FB buttons
maybe?

But get some sleep and we can brainstorm in the morning. Good idea to ask
folks for ideas on the Check-In!

And yeah, i think the icons would make nice FTOs!

**Comment by SidharthBansal** [comment]
>We could brainstorm also what other things we can do with these integrations now. Better integrated Post to Twitter or Post to FB buttons maybe?

We can create an issue and discuss this there.

>And yeah, I think the icons would make nice FTOs!

Sure.

**Comment by SidharthBansal** [comment]
This issue is completed
