### ISSUE TITLE
contributors page shows error if tag unused

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#287]
the contributors page does not return results if there are no contributors for that tag

Should show "no results" msg. Kinda related to #275

**Comment by lalithr95** [comment]
@jywarren you can close this issue

**Comment by jywarren** [comment]
Thanks!!! You can also get it to auto-close by including `fixes #287` in your commit messages. But great!

**Comment by lalithr95** [comment]
Sure :+1:
