### ISSUE TITLE
Master suddenly not passing rake test

### ISSUE THREAD

**Issue by rtrunkhill** [publiclab/plots2#2870]
### Please describe the problem (or idea)
I was resolved an issue and failed a rake test regarding code unrelated to the changes I made.

> What happened just before the problem occurred? Or what problem could this idea solve?

I switched to master and did ```git pull upstream master``` then ran a ```rake test``` and got a failure.  I've never failed a rake test from master before.  Here is the error:
```
ERROR["test_should_choose_i18n_for_home/home", Minitest::Result, 18.02589502930641]
 test_should_choose_i18n_for_home/home#Minitest::Result (18.03s)
ActionView::Template::Error:         ActionView::Template::Error: undefined method `author' for nil:NilClass
            app/views/dashboard/_node_wiki.html.erb:6:in `_app_views_dashboard__node_wiki_html_erb___1784082924968517272_73890680'
            app/views/dashboard/_activity.html.erb:67:in `block in _app_views_dashboard__activity_html_erb___3028487914910972440_77176940'
            app/views/dashboard/_activity.html.erb:65:in `each'
            app/views/dashboard/_activity.html.erb:65:in `each_with_index'
            app/views/dashboard/_activity.html.erb:65:in `_app_views_dashboard__activity_html_erb___3028487914910972440_77176940'
            app/views/home/home.html.erb:118:in `block in _app_views_home_home_html_erb__2963426744847793986_77318700'
            app/views/home/home.html.erb:117:in `_app_views_home_home_html_erb__2963426744847793986_77318700'
            app/controllers/home_controller.rb:18:in `home'
            test/functional/home_controller_test.rb:107:in `block (2 levels) in <class:HomeControllerTest>'
            test/functional/home_controller_test.rb:99:in `each'
            test/functional/home_controller_test.rb:99:in `block in <class:HomeControllerTest>'
```

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by Gauravano** [comment]
Hi @rtrunkhill , I also face this error sometimes when I run `rake test` with running rails server. Also, you can always raise a PR and then correct the failing tests if you face any such issue. In this case too, please raise the PR and let's see how it goes. Thanks for reporting!

**Comment by rtrunkhill** [comment]
alright.  when i close my server it passes that test (i've noticed the test acting differently when the server was running before, i learned somethign new).although if i make any changes i still get the same error i was getting [here](https://github.com/publiclab/plots2/issues/2542#issuecomment-398495437).  I'll close this one for now
