### ISSUE TITLE
Make comment editor more user friendly

### ISSUE THREAD

**Issue by namangupta01** [publiclab/plots2#2871]
Currently comment editors are using markdown. It gets very difficult for the people who don't know markdown format. To make writing less difficult for them, there can be several options in comment editor just like github so that user can easily comment.

**Comment by namangupta01** [comment]
@jywarren any input?

**Comment by namangupta01** [comment]
Checkout this demo: https://simplemde.com/

**Comment by jywarren** [comment]
I love the demo but we should keep in mind the new stuff we've been adding like Horsey -- see #2832 and let's connect with @ViditChitkara ?

**Comment by jywarren** [comment]
Generally i love this direction!

**Comment by namangupta01** [comment]
Yes! I am also considering Vidit's pr while working on this.

**Comment by jywarren** [comment]
I'd also love to see the new emoji autocomplete added to with autocompleting usernames with @ and tags with # -- one PR for each. 

could be interesting for @cheneyshreve with @ViditChitkara's help perhaps...

It'd mirror the implementation here: https://github.com/publiclab/plots2/pull/2832

The requests it sends would also be great to pull from the API -- maybe @stefannibrasil and @milaaraujo would be able to advise!

**Comment by jywarren** [comment]
![](https://user-images.githubusercontent.com/22616017/41511087-f06cc192-728d-11e8-9757-d3dce44aed04.jpg)

**Comment by cheneyshreve** [comment]
Thanks @jywarren I'd love to work on this!

**Comment by cheneyshreve** [comment]
Per your comment yesterday @jywarren about wanting  new emoji autocomplete added to with autocompleting usernames with @ and tags with # -- one PR for each.

@ViditChitkara,@namangupta01, @jywarren let me know if you want me to open a new issue or how to proceed. Just let me know where I can be most helpful and I'll get to work, thanks :)

**Comment by ViditChitkara** [comment]
@cheneyshreve sure, you may create a new issue for either one of them and start working on them, we would be happy to help. As suggested by @jywarren , it would have a similar implementation as emoji Auto complete #2832 . Currently it's implemented for comments only, which could be expanded to answers as well as notes.

**Comment by cheneyshreve** [comment]
Thank you, @ViditChitkara I will create a new issue.

**Comment by jywarren** [comment]
Hi, should we merge this into https://github.com/publiclab/plots2/issues/2896 since @cheneyshreve is working on the autocomplete part? Or perhaps we could break out more specific other ways to make it friendlier?

**Comment by jywarren** [comment]
Closing this for now, thanks!
