### ISSUE TITLE
break-me-up GitHub issue label

### ISSUE THREAD

**Issue by pdurbin** [publiclab/plots2#2876]
I noticed there's a GitHub issue label called "break-me-up" that looks great and that I'm thinking of adopting in my own projects:

<img width="1026" alt="screen shot 2018-06-20 at 9 27 10 pm" src="https://user-images.githubusercontent.com/21006/41692939-eeca513e-74d0-11e8-8e9f-7014ffb5c663.png">

I was telling someone about the break-me-up label and I almost said that it's probably a play on "Wake Me Up Before You Go-Go" by Wham! ( https://www.youtube.com/watch?v=pIgZ7gMze7A ):

<img width="663" alt="screen shot 2018-06-20 at 10 05 00 pm" src="https://user-images.githubusercontent.com/21006/41693990-0b9444c8-74d6-11e8-82fa-2cd3fbf73f78.png">

And then I thought, wait a minute, maybe it's a play on "Wake Me Up" by Avicii ( https://www.youtube.com/watch?v=IcrbM1l_BoI ):

<img width="664" alt="screen shot 2018-06-20 at 9 26 09 pm" src="https://user-images.githubusercontent.com/21006/41693026-68795e44-74d1-11e8-9bc4-81e7f20dcbf0.png">

Or maybe it's neither? Just curious. Maybe I'm the only one with these songs in head. 😄

**Comment by jywarren** [comment]
Ooohhh oo-ooooooh why do you
Break me up! Buttercup baby just to let me down... 
And mess me around?

😆 🎵

**Comment by jywarren** [comment]
@ebarry @steviepubliclab do we need a karaoke opencall!??!!

**Comment by pdurbin** [comment]
@jywarren I forgot about Build Me Up! 😄
