### ISSUE TITLE
display comments from SpectralWorkbench.org and MapKnitter.org in dashboard comment feed

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#288]
https://github.com/publiclab/plots2/issues/280 shows how this was done using JavaScript for the RSS feed of MapKnitter maps; it could be reproduced for comments as well -- code here: https://github.com/publiclab/plots2/blob/1f1e8ec7313875b42c0f14019d4645278519f0cf/app/views/users/profile.html.erb#L215-L250

Or we could expose a comments API and consume it via ActiveResource. 

One oddity is that we'd have to use the timestamps to "interleave" the comments by date, and perhaps make requests for the date range of the shown content... deal with pagination, etc... Hmm.

**Comment by jywarren** [comment]
Could perhaps be achieved by combining a comment RSS feed with the Mailing Lists feed...

**Comment by gauravano** [comment]
I think we can close this one as we would be integrating mapknitter with plots2 soon and we can take this up at that time or make new goals? Thanks!

**Comment by gauravano** [comment]
@jywarren
