### ISSUE TITLE
Tests failing  due to rails 5.1 upgrade and oauth commits

### ISSUE THREAD

**Issue by Souravirus** [publiclab/plots2#2880]
Hi @jywarren @SidharthBansal due to the PRs related to rails 5.1 and two of the oauth commits tests are failing. We have to correct these. One of the error is:
`test_login_user_with_an_email_and_then_connect_google_provider#Minitest::Result (124.51s)
ArgumentError:         ArgumentError: unknown keyword: user_session
            test/functional/user_sessions_controller_test.rb:78:in 'block in <class:UserSessionsControllerTest>'
.#<OmniAuth::AuthHash info=#<OmniAuth::AuthHash::InfoHash email="bansal.sidharth309@gmail.com" name="sidharth bansal"> provider="google_oauth2" uid="1357908642">`

**Comment by SidharthBansal** [comment]
Is there anything else failing apart from this test @Souravirus ?

**Comment by Souravirus** [comment]
No, only this test as of now.

**Comment by SidharthBansal** [comment]
You are trying to pass { } for the hash for rails 5 upgrade and hence they are failing. Am I right?

**Comment by Souravirus** [comment]
The passing of parameters from test to controller has changed. So, when I change the way of passing parameters on the line 78 of  `test/functional/user_sessions_controller_test` to 
`post :create, 
     params: {
     user_session: {
     username: users(:jeff).email,
     password: 'secretive'
      }
 }`,
the test passes. So are we ok with it. Should I send a PR related to this change?

**Comment by SidharthBansal** [comment]
Yeah for sure

**Comment by Souravirus** [comment]
ok then I am sending a PR

**Comment by SidharthBansal** [comment]
Great

**Comment by jywarren** [comment]
Oh wow, great work!
