### ISSUE TITLE
Don't allow newcomers to make/edit wiki pages until they've 1 question/post/note/activity approved

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2889]
This still needs some more specific design thoughts -- something like:

* [x] a lock icon where the wiki edit tab is, for newcomers, and
* [x] have it popup a tooltip saying `Please post a question or other content before editing the wiki. Click to learn why.` or something. 
* [ ] a rerouting of /wiki/new or the new wiki form to the dashboard with a similar friendly message alert for newcomers.

This is a temporary solution while we make a plan for a more robust wiki moderation system.

Any help on this appreciated!

**Comment by Gauravano** [comment]
I would love to solve this

**Comment by SidharthBansal** [comment]
Great idea.

**Comment by jywarren** [comment]
Please go for it! I don't think it's too complex a project. Maybe good for some newcomers, in parts, ironically?

**Comment by Gauravano** [comment]
Breaking this issue in FTO's. Thanks.

**Comment by Gauravano** [comment]
First FTO at #2921

**Comment by Gauravano** [comment]
The second one requires some test modification too, so I will do the other minor. @jywarren I have given this link https://publiclab.org/notes/tester/04-23-2016/new-moderation-system-for-first-time-posters in the FTO, please verify if the link is appropriate in this case or not. Thanks.

**Comment by jywarren** [comment]
yes, that sounds great!

**Comment by jywarren** [comment]
Awesome! I updated the checklist above. Great work!
