### ISSUE TITLE
design proposal: 3 column dashboard

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#289]
This is partially complete, and being coded; to-do list here:

* [x] pagination styles on narrow screens
* [x] mailing list ajax testing & styling
* [x] styling notes by type:
  * [x] questions
  * [x] events
* [x] disinclude `hidden:response` notes
* [x] mix in wiki updates alongside new pages
* [x] batch updates if in same display "5 edits by 6 users" (did this using group by DATE in query; doesn't show count or authors, but won't show more than 1 update per day. Could later maybe adapt by using combination of date and username?)
* [x] mix in comments - enumerate comments per group? (http://stackoverflow.com/questions/35927288/how-to-count-how-many-rows-inside-a-group-by-group-meets-a-certain-criteria)
* [x] 'new page' vs. 'edit' in sidebar
* [x] recent edits not showing, due to grouping/sorting in home_controller
* [ ] make `blog-submission` button, hook up remaining buttons
* [ ] enable proxy and switch on mailing lists
* [ ] tell people their "blog post is posted, and will be reviewed for publication on the blog by the editors", in a notice on publication
* [ ] prompt people to tag by topic in "ask a Q" and maybe switch to `question:general`
* [ ] prompt people to choose a region for their event, and link to "about events"
* [ ] refresh button or "pull to refresh" dashboard, or just ajax refresh if it's been a while
* [ ] revision edits issue

****

This is following up on #284 for adding a "Stories" section and #84 (closed) disambiguating Research Notes and Stories. 

This rough proposal (input please!) would organize the dash into three columns (or fewer?) which would be 

* Activity (notes and comments)
* Stories (blog at least)
* Wiki (by recent activity)

Each could have a button at the top to post content of that type.  This would also in theory make space for three banners (as used on the front page currently) which could rotate content, for example for events or Kits announcements. 

![img_20150608_133006](https://cloud.githubusercontent.com/assets/24359/8041197/780722c6-0de4-11e5-8294-bddbc41e35e2.jpg)

I know @ebarry and @steviepubliclab are very busy at the moment, but would love to circle back once things calm down a bit.

**Comment by jywarren** [comment]
Shannon also pasted in our notes from staff retreat on the prompts we'd want; these may fit into the proposed columns above: 

`Share/Learn` `Post an event` `Share a story` `Ask a question` `Post your research`

**Comment by steviepubliclab** [comment]
Would this take the place of what we proposed at the staff meeting (what
you looped in from Shannon)?

**Comment by jywarren** [comment]
It's a design proposal to implement what we discussed at staff meeting.

**Comment by steviepubliclab** [comment]
Ah so the categories on the top would be:
Share/Learn:

 Post an event, Share a story, Ask a question, Post your research

 Or whatever on those we decide?

**Comment by jywarren** [comment]
I think Share/Learn was the text for the button, and the orig. suggestion was for it to then open a list of options including the others. I'm proposing a variation where we have 3 columns with a button at the top of each, something like this:

Activity | Stories | Wiki
---------|--------------|-----------
`Ask a question` | `Share a story` | 
 `Post your research` | | |
_content, content, content, content, content, content, content_ | _content, content, content, content, content, content, content_ | _content, content, content, content, content, content, content_
_content, content, content, content, content, content, content_ | _content, content, content, content, content, content, content_ | _content, content, content, content, content, content, content_
_content, content, content, content, content, content, content_ | _content, content, content, content, content, content, content_ | _content, content, content, content, content, content, content_

Not sure where `Post an event` would fit, yet. But the idea is to make fewer clicks, and less confusion because each column would offer insight into what kind of content you'd be posting, instead of the 4-up popup menu presenting you with four differently-named buttons without extra explanation.

**Comment by steviepubliclab** [comment]
I like this idea. I do think it's important to separate out questions from
research. That way neither gets buried, they are distinct.

**Comment by jywarren** [comment]
I agree, but there just isn't space for four columns; 3 is already making the page pretty busy. Do you have another suggestion for how it could be organized?

**Comment by jywarren** [comment]
I named that column "activity" but we could have an option to show "only research" or "only questions" -- but again, that adds complexity.

**Comment by steviepubliclab** [comment]
what if the activity tab included research notes and wiki updates?

**Comment by jywarren** [comment]
We've already identified a confusion between the two, so I'm reluctant to do that. We could try to go nuts on using design to differentiate them in the same column, but the same is true for Questions, and Questions and Notes have more in common than Notes and Wikis: 

type | time | authorship | discussion
------|--------|------|---
questions & notes | occur at a specific time | single author | have comments
wiki pages | "timeless" | multiple author | no comments

**Comment by jywarren** [comment]
Starting to think about how this could work without being overwhelming, and avoiding a text-heavy layout. This is just an experiment, and would accommodate future features like nearby users/content and a question form:

![screenshot 2016-02-16 at 12 04 38 pm](https://cloud.githubusercontent.com/assets/24359/13084366/301cd318-d4a7-11e5-8ed9-b6cac6bc8659.png)

**Comment by jywarren** [comment]
@ebarry @steviepubliclab - starting to think about how this could work without being overwhelming, and avoiding a text-heavy layout. This layout highlights the blog and wiki more, and provides a bit more context instead of the current dashboard's simply dumping you into a dense feed of research notes. This is just an experiment, and would accommodate future features like nearby users/content and a question form:

![screenshot 2016-02-16 at 12 04 38 pm](https://cloud.githubusercontent.com/assets/24359/13084366/301cd318-d4a7-11e5-8ed9-b6cac6bc8659.png)

**Comment by jywarren** [comment]
I realize we could also potentially switch the wiki and activity feed here...

**Comment by jywarren** [comment]
I'd also like to consider tackling some "design for newcomers" in a large "welcome pane" for folks who haven't posted anything -- similar to the publiclab/spectral-workbench#119 wizard we're working on for Spectral Workbench -- and bigger than the very small notice we already display:

![screenshot 2016-02-16 at 12 30 46 pm](https://cloud.githubusercontent.com/assets/24359/13084846/4c34ba8c-d4a9-11e5-96e8-56b6e4e9a092.png)

**Comment by steviepubliclab** [comment]
I like the look of the layout here. I think it's probably a little
difficult to parse out what each thing is if you don't already know, so
some descriptors might be necessary.

Questions:
- Is "activity" notes and events?
- What is the top right hand square?
- Where would people go if they wanted to search the wiki instead of post a
new one?

**Comment by jywarren** [comment]
Thanks for feedback; the upper right hand square is a dropdown menu from the button, kind of like in Spectral Workbench (i didn't spend time to make it look just right in the mockup):

![screenshot 2016-02-16 at 4 00 13 pm](https://cloud.githubusercontent.com/assets/24359/13090899/74fa5b3a-d4c6-11e5-8829-f8fa4cf0657a.png)

Activity would be notes, events, and questions, but as the example question shows, we'd style them quite differently so they're easy to tell apart.

I like the idea of a search interface here; we could put a search form right next to `Add a new page +` under the Wiki section?

We can also put `?` links next to many things as we've done in Spectral Workbench 2, with or without hover-over explanations:

![screenshot 2016-02-16 at 4 02 43 pm](https://cloud.githubusercontent.com/assets/24359/13090950/ca6aa994-d4c6-11e5-8d94-df678a334ed3.png)
![screenshot 2016-02-16 at 4 03 31 pm](https://cloud.githubusercontent.com/assets/24359/13090966/dfd30e0c-d4c6-11e5-9323-1b76ce96d909.png)

**Comment by steviepubliclab** [comment]
Ah I meant the upper right hand where Matej's post is right now. What
rotates through there?

Are you saying the left hand column is a feed of these things with
different images that distinguish the types of posts? So would someone only
see 2 at once?

**Comment by jywarren** [comment]
That's the latest blog post -- this rev below may clarify that.

No, the activity feed would show questions, events, and research notes, distinguished by color and icon:

![screenshot 2016-02-16 at 4 26 11 pm](https://cloud.githubusercontent.com/assets/24359/13091629/16136c66-d4ca-11e5-807d-53d25cccc410.png)

We could even put `Answer` and `RSVP` buttons on the Q and event types?

**Comment by jywarren** [comment]
And all columns would continue down below the fold, i'm just only mocking what'd display in the first screenful. 

We could put a "post a research note" or "share a project update" button right under Activity -- or even multiple buttons like `Share project update` `Ask a question` and `Post an event` -- but too many buttons may discourage folks from posting at all. I'd do max 2 buttons.

**Comment by jywarren** [comment]
Something like this:
![screenshot 2016-02-16 at 5 24 10 pm](https://cloud.githubusercontent.com/assets/24359/13093229/260f0ef6-d4d2-11e5-846d-0bee6d66e1e5.png)

**Comment by jywarren** [comment]
@steviepubliclab @ebarry - what do you think of this version? It's starting to be a bit busy again; maybe the version with a narrower left column and wider right column was better?

If you're all right with it, I'd like to push this out to the rest of staff, then possibly organizers. This isn't meant to be a drawn-out process, just an approx. week-long design process, and we can continue to improve it later.

**Comment by jywarren** [comment]
Also, what about comments; should we show "ongoing conversations" or something?

**Comment by annhchen** [comment]
Jeff! Great job, it looks a lot cleaner. 

I like the new placement of the "Share your work" formerly "Write a research note" in the right corner. It feels like it's more a part of the research notes "section".

Another great thing about this is that the separate options (share a project, post an event, etc.) can now replace the "template" button in the post research note form. Clicking on a each note type will take you to a different template.

**Comment by tonypubliclab** [comment]
A couple of thoughts after a first quick look through "users' eyes" (I'm not reading the whole thread here, just reacting to what I see in the mockup)

the items in the share your work dropdown surprise me a bit

"Share your work" prepares me to post research notes. I'm not sure what the "project updates" is, if that's a new feature.

Ask a question feels like a different impulse. I guess I mean that if I wanted to ask a question: share your work would be the last button I'd push.

But I really like Share your work and Ask A question as they two buttons or impulses to satisfy. You tend to come to the site either wanting to learn something or show something, you know?

Posting blog posts or new events could logically just be buttons on the blog and events pages. Go to the page to see all the current ones or add your own.

I also like the idea of using Share Your Work as a non-jargon button, even if where it takes you explains that we use something called "research notes" as a basic format to do that.
cool stuff. good work y'all

**Comment by jywarren** [comment]
This is super useful feedback; thank you, folks! Some things like "Project updates" was just putting some ideas out there to get input, so your thoughts are very helpful. The idea in this case was to try to provide more context for what a "research note" is -- that it need not be a huge piece like a peer-reviewed paper or something, but can be a brief update on an ongoing project. But perhaps it's too confusing and it's enough that it says "updates" under "Activity". 

+1s or -1s on the terminology "Share project update" leading to research note form? And/or even renaming research notes "project updates"? Just putting this out there. 

The multiple options in `Share your work` are mostly requests from the staff retreat a year ago. I think it makes more sense to put buttons next to each type of content, and clicking `Share your work` wouldn't open the dropdown -- just the caret next to the button would give you more options. Clicking the button itself would just go to the standard research note form. 

One idea I wanted to possibly add is that we could have a section of the page which is just an "Ask a question" form. But that's too much content for this page. 

We could in theory put three buttons under Activity: `Post research note`, `Post an event` and `Ask a question` - but that'd be starting to overwhelm the user with choices.

**Comment by jywarren** [comment]
One more slightly odd idea - what if "post an event" were dimmed, and it says "You must be an [organizer](https://publiclab.org/wiki/organizers) to post an event. [Apply now]()" or something? 

Not to make more barriers, but so that there are fewer options for new users, reducing confusion, and more reasons to become an organizer? Not sure this is a good idea but putting it out there for discussion.

**Comment by sdosemagen** [comment]
I like the idea of switching the activity feed for where the wiki feed is right now. In general wiki edits can be repetitive (someone editing the same page 20 times in a row), will that be a compelling dashboard item? I also like the first version you posted of this three days ago with a wider right hand column, it's visually more compelling than the next version. The share your work dropdown is great.

**Comment by ebarry** [comment]
Great progress. Some of these questions exceed with this small dashboard project can resolve (mostly because it is not paired with user testing), specifically an improved search interface, and how exactly to support people to ask questions. I feel the same way about the terminology questions -- we are all in this too deep to be making terminology decisions without consultation to at least a small focus group of community members. So we need to keep this dashboard project small. 

the good features i want to support here: 
- moving the "share your work / post a research note" button to the right hand corner. 
- using color-coded backgrounds to differentiate content types.

**Comment by jywarren** [comment]
Thanks, Liz - 

Absolutely - **search overhaul** is a separate topic (#209). The Dash will accommodate that project, though.

A **question form** is also a separate topic (just made #368), but again, I can see it taking the Blog place here, either with tabs, or just above it in a pane. 

+1 on no new terminology in this project, but I think we keep tabling that discussion, so we ought to open a new issue specifically for terminology beyond "Share your work".

I do worry a bit about right hand corner not being in "good" real estate re: [the F-shaped pattern](https://www.nngroup.com/articles/f-shaped-pattern-reading-web-content/), but I think we're still in pretty good real estate. 

Just to be clear: the dropdown **IS templates**. We're just consolidating where these template-generating buttons are displayed. 

And extra note: color coding must be accompanied by icons for accessibility/colorblindness reasons. 

Am also thinking about how this rearranges in mobile, and it might not be simply the standard right-column-below-left-column fluid layout. We'll see, but we might need to tab it in mobile or something. 

Finally, re: shannon's wiki edits comment, I **believe** we can get it to display "5 recent edits to page" instead of showing five separate edit entries. This would be ideal.

**Comment by jywarren** [comment]
One more question for Stevie, but she's on vacay, so maybe for @ebarry in her stead -- do we really want a button that goes directly to the blog, or should it be curated? We could have it auto-tag "blog-submission" and notify blog editors, but not go onto the blog unless it's tagged by editors? Either way, just tell me what you prefer.

**Comment by gretchengehrke** [comment]
Great progress, Jeff! 

I definitely like the color-and-icon-coding for wiki v research note v blog. 

I echo Tony's concern with having "Ask a question" imbedded anywhere instead of as a button for itself. I like Jeff's idea about having a "share your work" button on each type of activity feed, and also in the right-hand corner. 

If we still have room, in the top left where is appears to have two items "try the desktop spectrometer" and "become a member", could we make those "Most popular Store item this week" "become a member" and also add "donate" if it doesn't make it too busy?

**Comment by jywarren** [comment]
Thanks gretchen -- that top left section is actually a rotating banners zone, so we'd be able to put anything there, and I'm trying to indicate in the mockup that it might fade between different banners, as well as show them randomly.

**Comment by jywarren** [comment]
Summing up some comments, starting with @kanarinka:

* My recent wiki edits and research notes, including alerts/notifications if there are comments/likes/etc on them
* dashboard personalization, perhaps by tag (later scope, probably)

@Fastie: 

* like to keep easy access to all recent research notes, comments, wiki edits
* design for tab-based sortability of the Activity feed (related to above)

@mathewlippincott:

* mailing list integration
* several suggestions for future improvements of callout listings #371, subscriptions, and wiki updates #332 

Will try to integrate these into a new mockup. Thanks!

**Comment by jywarren** [comment]
Whew, ok, here's a new version attempting to incorporate some of the suggestions:

![screenshot 2016-02-23 at 5 59 17 pm](https://cloud.githubusercontent.com/assets/24359/13269710/2fd84814-da57-11e5-8ac2-c9e678efa087.png)

**Comment by Fastie** [comment]
That looks really good. 
Now that you are emphasizing the blog, are you really going to let anyone add the tag "blog" to any research note? If you "Post related work" to a blog post, your new note also gets the tag "blog." Is some curation called for?

**Comment by annhchen** [comment]
I agree, this looks really good. Great job Jeff! I really like the addition
of icons & colors to show what type of research note it is (if it's an
event, research note, question, etc.).

On Wed, Feb 24, 2016 at 10:37 AM, Fastie <notifications@github.com> wrote:

> That looks really good.
> Now that you are emphasizing the blog, are you really going to let anyone
> add the tag "blog" to any research note? If you "Post related work" to a
> blog post, your new note also gets the tag "blog." Is some curation called
> for?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/publiclab/plots2/issues/289#issuecomment-188308393>.
>



-- 
Ann Chen <http://annhchen.com>
UnionDocs Collaborative Productions Fellow

+1 973 727 4675 [US]
+1 778 872 9765 [Canada]

Twitter <https://twitter.com/annhchen>  |  Facebook
<https://www.facebook.com/annchenworks>  |  Nat Geo Voices Blog
<http://voices.nationalgeographic.com/author/achen/>  |  Pipeline Mapping
<http://pipelinemapping.tumblr.com>

**Comment by mathewlippincott** [comment]
oh yeah! that is getting all those feeds of info in!

**Comment by steviepubliclab** [comment]
This mock up looks GREAT! Are the blog posts not going to live on the dash now? or is it that they are lumped in with research notes?

**Comment by steviepubliclab** [comment]
Oh I see it now :) silly.

**Comment by steviepubliclab** [comment]
This looks awesome :)

**Comment by jywarren** [comment]
Question -- where should comments go? in the activity feed? Thanks!

**Comment by jywarren** [comment]
also, Chris -- good point. Blog curation is a question for @steviepubliclab -- stevie, at a minimum we could have the "share your story" button tag things as "blog-draft" or "blog-submission" which you could be subscribed to with email notifications. At most, we could actually make a powertag that only moderators can user, that posts things to the blog. But that'd take some more work.

**Comment by steviepubliclab** [comment]
Might be a good idea to put some thought around it since we're having the spam conversation as well. At this point, anyone can tag blog to any post and it would go there. Are you recommending we take that feature away and make it so only moderators can push things to the blog? Is there any chance the moderators could get an email notification and approve blog posts?

**Comment by jywarren** [comment]
So I'm suggesting that we make a new tag called blog-submission, which you
would subscribe to for email notifications. The blog post form would auto
tag with that, and not yet show up on the blog until you added "blog". This
would still be easy to get around by self-tagging "blog" as it is today,
but the default would not bump a submission to the front without your or
someone's input.

**Comment by steviepubliclab** [comment]
That works for me. I think it would be good if we could subscribe
moderators to it, just incase I'm not around or someone else could just get
to it faster.

**Comment by jywarren** [comment]
Super; if you could take lead on getting a few people to be the blog "editors" that'd be great.
