### ISSUE TITLE
Wrong number of likes on wiki pages

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2891]
### Please describe the problem (or idea)
![image](https://user-images.githubusercontent.com/20972099/41746640-b7de1310-75c8-11e8-9b99-c59988ec6d59.png)
![image](https://user-images.githubusercontent.com/20972099/41746655-c5dad78c-75c8-11e8-8ff6-0a908f2ecd38.png)
The list shows there are 7 people who like open call wiki page but the number shows 12.

> What did you expect to see that you didn't?
Number of likes should be same as number of users we are seeing in the list

**Comment by SidharthBansal** [comment]
Most probably this issue is related to banned users. Count should decrease if the user is banned.
Right now I am too busy with the OAuth project so I will love if anyone else can solve this one out.

**Comment by namangupta01** [comment]
@imacubsfan23 Go ahead!

**Comment by imacubsfan23** [comment]
Where can I check if the user is banned? Can't seem to find it anywhere

**Comment by imacubsfan23** [comment]
Warning: long explanation. Overall I'm just curious if I should comment this code or delete it. Please leave your thoughts

Here's what I found:

When I found that the like-count was changing from the correct value to twice the amount every time, I knew that it must have been counting twice (or at least getting replaced incorrectly in another place)

In the like/_like.html.erb:
The ruby code that works (already implemented)
Line 26: ```<span id="like-count-<%= node.id %>"><%= node.likers.length %> </span>```

The jQuery code that does the same thing, but for a second time.
I either want to delete or comment this out, what do you guys think?
Starting on Line 99:
```
// grab the like count for this node; "/likes/node/11278/count"
      jQuery.getJSON("<%= like_count_path(node) %>", function (json) {
        // push like count into the Like button placeholder
        $('#like-count-<%= node.id %>').html(json);
      });
```

**Comment by SidharthBansal** [comment]
When you comment out these lines, are the number of lines right? Try for 5-6 users.

In the page where I found this bug shows 7 in the list but count as 12 that means we still have any other error.

Thanks for the catch.

**Comment by SidharthBansal** [comment]
> if I should comment this code or delete it. 

No need to be scared before posting here. We all are here to help and learn. Feel free to ask help from any member of @publiclab/soc or @publiclab/reviewers

**Comment by jywarren** [comment]
Hi! Does the JavaScript code that seems redundant get used at any later time, such as, upon clicking the like button? If not, then I think we can delete it. Good catch!

**Comment by imacubsfan23** [comment]
I tested for 12 users, and banned 5 of them. Without the jQuery code, it works perfectly. 
Also to respond to jywarren, it does not get used for any purpose other than this.
Next step is to send a pr.
Also, thanks for all of the responses guys! This community is awesome.

**Comment by SidharthBansal** [comment]
Great go ahead
Thanks

**Comment by jywarren** [comment]
Awesome, just ping us when you'd like a review!
