### ISSUE TITLE
Google Provider OAuth settings for development

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2892]
We have completed Google OAuth provider settings on
* unstable.publiclab.org
* stable.publiclab.org
* publiclab.org
The following are left so that the developers can use it in development
* [ ] localhost:3000(http connection)
* [ ] localhost:3001(https connection)
We are moving from the conversation of #2771 to here.
 @jywarren Can you please make the changes to the Google developers app as you indicated in #2855 (comment)?

**Comment by jywarren** [comment]
Just did it, i believe!

**Comment by jywarren** [comment]
Can u check and close this if it works? Thanks @SidharthBansal !!!

**Comment by SidharthBansal** [comment]
Sorry, it is not working
``Missing Required Parameter: client_id``

**Comment by SidharthBansal** [comment]
Is it working in your browser @jywarren for both ports ``3000`` and ``3001``

**Comment by jywarren** [comment]
I think it's the domain verification -- but we can't verify localhost...
maybe look around for how this ought to work? Were you able to add these
for your own API account?

**Comment by SidharthBansal** [comment]
I don't require any ``privacy policy`` nor ``domain verification`` for the ``3000`` and ``3001`` port.
I just need the ``People connect`` api which is for sure enabled in the app created by you.

**Comment by SidharthBansal** [comment]
Can you please verify them 
![image](https://user-images.githubusercontent.com/20972099/41749918-d232d350-75d6-11e8-8df3-8d1ed3dd3350.png)

**Comment by jywarren** [comment]
![screen shot 2018-06-21 at 7 17 28 pm](https://user-images.githubusercontent.com/24359/41750049-c847bc4c-7587-11e8-92c4-f0eff599b9bc.png)

**Comment by SidharthBansal** [comment]
Is it working on your localhost?
Can we change this app_id and app_secret to my app_id and app_secret to check it in development first?

**Comment by SidharthBansal** [comment]
Yeah I saw that there is testing key for ReCaptcha working with localhost

**Comment by SidharthBansal** [comment]
>are there "trial" ids available for working in development?

No there are not.
I was thinking that first we can change the app_id and app_secret in the jenkins to my app_id and app_secret and see whether we are able to configure google login on localhost or not on both my laptop and yours.

If we will not be able to configure it ,that will mean that we can't have same id for all developers

 if we both will be able to log in via google provider that means, we need to change the app_id and app_secret in the jenkins back to the app_id and app_secret which you have created for production and need to modify the app settings OR may be we need to create one more app for developers access. Possible reason for this could be ``localhost is not having domain verification`` and we have done domain verifaction for that app. Make sense?

**Comment by SidharthBansal** [comment]
I have sent you app_id and app_Secret on jeff@publiclab.org.

**Comment by SidharthBansal** [comment]
> Maybe my brain needs a break!

Ok. You take rest. We can continue it later.
>Be sure not to forget to sleep!

Yeah sure. Thanks

**Comment by SidharthBansal** [comment]
Also the form which is rendered inside the signup form says that ReCaptcha is not used in development
https://github.com/publiclab/plots2/blob/608ee10f708eba524581db62cd211fbfd5d60cb7/app/views/users/_form.html.erb#L60-L88

**Comment by jywarren** [comment]
Well, I guess I'm not sure what we can do here. The settings are created but localhost is not working - possibly due to domain verification which we cannot do for `localhost`. See the settings in this comment: https://github.com/publiclab/plots2/issues/2892#issuecomment-399272713 -- what else is left that we could try?

As to the environment variables, you can insert them at run time locally by doing:

```
OAUTH_GOOGLE_APP_KEY=xxxxxxxx passenger start
```

Or, you can put it in a file like `environment.sh` which is like:

```
OAUTH_GOOGLE_APP_KEY=xxxxxxxx
```

and do:

```
source environment.sh && passenger start
```

**Comment by SidharthBansal** [comment]
Is the app_id and app_secret for #2892 (comment) is working on your localhost? 
If not can you please check it with the app_id and app_secret which I have sent you on jeff@publiclab.org
My app_id and app_secret is working on localhost which I have sent you.

I think this can help to troubleshoot a little bit

**Comment by SidharthBansal** [comment]
>The settings are created but localhost is not working - possibly due to domain verification which we cannot do for localhost

Localhost does not require any domain verification but the websites does. So, in the app_id and app_secret which I have sent you. I have not done any domain verification.

**Comment by SidharthBansal** [comment]
>The settings are created but localhost is not working - possibly due to domain verification which we cannot do for localhost

Localhost does not require any domain verification but the websites does. So, in the app_id and app_secret which I have sent you. I have not done any domain verification.

**Comment by jywarren** [comment]
It's a bit late here, but I will try tomorrow, thanks!

**Comment by SidharthBansal** [comment]
As discussed in #2856, we will either create one developers app for github provider OR we will write documentation for developer to set up their app locally.

So, @jywarren we are completed with GOOGLE, so no need to try this.
Thanks @jywarren
