### ISSUE TITLE
Twitter Provider App Settings

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2893]
This is for future reference for Twitter Provider in OAuth Login Project.
This is part of checklist #2676 's Twitter Provider.
A few points:
* Twitter app is not functional in the insecure version of development mode. That is, Twitter works only on https(http+ssl by openssl gem) in development. We use port no ``3001`` for https connection
* We can't use https://localhost:3001 in case of Twitter. Instead, we need to use https://127.0.0.1:3001
* We need to give privacy url for development mode in addition to production. Make the privacy url as needed @jywarren
* We need to give Terms of service for development mode in addition to production. Make it as needed @jywarren
* We need to enable email address otherwise email is not accessible by going to advance settings
* We need to add ``sign-in capability``
* There is only one origin url, hence there is a need to create different apps for the following:
* [x] https://unstable.publiclab.org
* [x] https://stable.publiclab.org
* [x] https://publiclab.org
* [x] https://127.0.0.1:3001
These are the screenshots of the settings made which are functional dated 22.6.18
![image](https://user-images.githubusercontent.com/20972099/41752327-88c1fd78-75e4-11e8-8395-32b583cb56cc.png)
![image](https://user-images.githubusercontent.com/20972099/41752337-9cabb676-75e4-11e8-8e74-6fc9c35727e7.png)
![image](https://user-images.githubusercontent.com/20972099/41752434-0ce63a6a-75e5-11e8-97d5-0c3a3aa7481e.png)

**Comment by SidharthBansal** [comment]
Please don't get dishearted if you log in via twitter from https://127.0.0.1:3001/auth/twitter and you see you are not logged in at public labs. Check the url. It will be https://localhost:3001/
You are actually logged in on https://127.0.0.1:3001 but not on https://localhost:3001.
So check it on https://127.0.0.1:3001

**Comment by jywarren** [comment]
OK, is this ready to go now and I should set up the app? Thanks!!

**Comment by SidharthBansal** [comment]
I have sent the patches in #2948 and #2947 which are required before the twitter app setup. After merging them you can set up the app in your free time.

**Comment by SidharthBansal** [comment]
Once you will make the app_id and app_secret and place it in jenkins. Please ping me. I will start the tests for Twitter.

**Comment by jywarren** [comment]
OK - those are both merged, great!

**Comment by SidharthBansal** [comment]
Now you can set up the twitter apps.

**Comment by SidharthBansal** [comment]
Thanks for the merge

**Comment by jywarren** [comment]
Do you need just the Consumer API Key and Secret, or also an access token and secret? 

I've added the Consumer Key and Secret to unstable, staging, and production!

**Comment by jywarren** [comment]
I set it to read only for now. Want to test this out on unstable?

**Comment by SidharthBansal** [comment]
>Do you need just the Consumer API Key and Secret, or also an access token and secret?

 Only Consumer Key (API Key) and Consumer Secret (API Secret) are needed.

**Comment by SidharthBansal** [comment]
I have pushed the changed to unstable.

**Comment by SidharthBansal** [comment]
![image](https://user-images.githubusercontent.com/20972099/42116807-ad46a828-7c16-11e8-8392-4ea0a83658ac.png)
Working fine

**Comment by SidharthBansal** [comment]
![image](https://user-images.githubusercontent.com/20972099/42116834-d98d3514-7c16-11e8-88b4-8dbc315e7494.png)

**Comment by SidharthBansal** [comment]
@jywarren can you please push the changes to the production and stable.publiclab.org.
Thanks for setting up the apps.

**Comment by jywarren** [comment]
OK, we'll schedule this probably for tomorrow!

**Comment by SidharthBansal** [comment]
Great.

**Comment by SidharthBansal** [comment]
Working fine in production.
Thanks @jywarren
