### ISSUE TITLE
maps not showing up in profile

### ISSUE THREAD

**Issue by skilfullycurled** [publiclab/plots2#290]
I created a map here:

http://mapknitter.org/maps/southeast-chicago-petcoke-piles-6-4-15

But it is not showing up in my profile here:

http://publiclab.org/profile/bsugar#maps

I was working with someone the other day who was having the same issue when we were trying to find eachother's maps.

**Comment by jywarren** [comment]
This is unfortunately a known issue which nobody's had a chance to fix. It's documented in #280 but the workaround at the moment is to go to http://mapknitter.org/profile/bsugar instead of http://publiclab.org/profile/bsugar

**Comment by skilfullycurled** [comment]
perfect.

thanks!
