### ISSUE TITLE
Editing of research note giving 500

### ISSUE THREAD

**Issue by Gauravano** [publiclab/plots2#2905]
Saving an edit to the research note is throwing error 500. Logs for the same are 

![logs](https://user-images.githubusercontent.com/20878070/41810248-1a6b5b72-7719-11e8-9cf5-1905f3e652e7.png)

**Comment by jywarren** [comment]
Hmm, looks like we need to fix the reference to the template for updating
in the notes controller. Thanks for reporting!!

**Comment by Gauravano** [comment]
@jywarren , I submitted the fix at #2906
