### ISSUE TITLE
Community Check-in #6 Summer Of Code Week 7

### ISSUE THREAD

**Issue by namangupta01** [publiclab/plots2#2911]
Hi everybody 👷 !
If you're new here, welcome, and please [try some of our first-timers-only issues](https://publiclab.github.io/community-toolbox/#r=all). This is a checklist for publiclab/soc.

@stefannibrasil @milaaraujo @MargaretAN9 @Gauravano @ViditChitkara @tech4GT @mridulnagpal @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @ccpandhare @icarito @abTest-123 @steviepubliclab @ebarry @publiclab/soc @publiclab/reviewers

How was your weekend? How are you doing? What is your plan for this week?
If you have not planned yet. Just leave a Hi! so that we could know that you are well. 🛩

Hope all of you are doing awesome. This week we deployed reply-by-email work on stable, we got some errors but the error that took most of the effort to resolve is connecting the mailman service to database service in containers but finally we resolved it.  🎉 🎉 It is currently live on unstable. You all can test it out by sending mail to `notifications-unstable@publiclab.org`. Subject should be `some text (#node_id)` which will add the comment to node with node_id given in subject --if that node_id exist obviously. Hoping this will be in production soooon. In current week, i will be discussing with the mentors about how we can overcome spamming in reply-by-tweet feature so that we can further implement it . 

## 'Til next week!
As always, if you're waiting for a review, or if you're stuck, please request help
here OR leave a comment with @publiclab/soc and @publiclab/reviewers for
some input.

Happy coding 🎉 !
Have a wonderful week ahead. 
Thanks

**Comment by namangupta01** [comment]
In case if you want to test, here is a mail template that you can use.
Note: We are sending mail here manually adding node_id in subjects because `unstable` don't have mail sending facility. 
So the steps are:
mailto: `notifications-unstable@publiclab.org`
subject: `some text (#213)` 
content: anything you want

This will add the comment to node_id 213 which you can check at : https://unstable.publiclab.org/wiki/staff-call-notes-5-3-2011/comments

**Comment by SidharthBansal** [comment]
Hi all, the Google Provider is completed. I have completed the configuration settings of Github. Whenever @jywarren will be free he will create the github app(#2856) and /auth/github will be functional from then.
I have completed the tests for Github provider. I will send the patch this week.
Once @jywarren and I are done with #2856 I will send the prs for Twitter provider.
Thanks

**Comment by Souravirus** [comment]
Hi everyone, we are currently at rails 5.1.15. Though the routing problems and some other rendering problems persisted this week but we are trying to get rid of these problems as soon as possible. Sorry for the inconvenience. Also thanks for giving information about these issues.

**Comment by jywarren** [comment]
Hi all! I'm hoping to deploy new code today and get the Google login button and the reply-by-email code live! :-)

**Comment by SidharthBansal** [comment]
Hi all, you can now log in via github to public labs by publiclab.org/auth/github
Thanks

**Comment by jywarren** [comment]
Code is live now, I just published once more!

Great work this week, folks! And many thanks for the help with PRs. We are back down under 30.

**Comment by jywarren** [comment]
Hi, all! @icarito and I are meeting today to work on various issues, and we'll see if we can help with some of the sidekiq issues. 

I wanted to ask if someone wants to do next week's community check-in on Monday? @stefannibrasil -- since Monday will be your and @milaaraujo's first day of RGSoC (BIG WELCOME!!! 👍 👍 🎉 ) maybe you'd like to?

And finally, we've been talking a bit about doing another live video call since we're getting to the middle of the summer and RGSoC is starting. Let's think of a time -- would the same as last time work? @ebarry  had suggested:

> Tomorrow, May 8, 2018 at 8:30am Vancouver, 10:30am New Orleans and Peru, 11:30am NYC and Providence, 5:30pm Israel and Poland, 9:00pm Delhi, 11:30pm mainland China, we will be convening on https://meet.jit.si/publiclab -- For some other timezones, see http://everytimezone.com/#2018-7-2,1650,b8jj

Not on Monday but sometime the coming week? What days work for people -- Tuesday is best for me!

@publiclab/soc

**Comment by stefannibrasil** [comment]
Thanks, @jywarren I am really happy to be officially joining you next Monday!

I can do the Community Check-in next Monday, yes! Already added to my calendar =)

About the call, you can count on me. Cheers!

**Comment by jywarren** [comment]
Fantastic!!!

**Comment by tech4GT** [comment]
I have been working on making image sequencer modules available through nom. We are currently using the invert module via npm. Will be adding meta modules soon.

**Comment by milaaraujo** [comment]
Moved to #2971
