### ISSUE TITLE
Sidebar should properly show Recent Wiki Pages

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2917]
### Please describe the problem (or idea)
The sidebar doesn't show Recent Wiki Pages on publiclab.org/wiki/requests but shows an option ''More''
![image](https://user-images.githubusercontent.com/20972099/41880214-8656efc6-78fa-11e8-96c1-7ee441ec8cc9.png)

> What happened just before the problem occurred? Or what problem could this idea solve?
It should show recent wiki pages

**Comment by jywarren** [comment]
Hi, I think we may be able to remove it in line with https://github.com/publiclab/plots2/issues/1706

or make it collapsible in line with https://github.com/publiclab/plots2/issues/2493

Thanks!

**Comment by SidharthBansal** [comment]
OK great. Then we shall close this one once either #1706 or @2493 is completed

**Comment by oorjitchowdhary** [comment]
Hi all, do we still need this issue..
I think we've removed that type of sidebar on wikis

This is the current layout
![image](https://user-images.githubusercontent.com/39333058/50487103-ea71c080-0a22-11e9-8d51-6c7a78181744.png)

**Comment by jywarren** [comment]
Agreed! Closing!
