### ISSUE TITLE
Section for Drafts OR Inclusion in current tabs

### ISSUE THREAD

**Issue by Gauravano** [publiclab/plots2#2920]
Hi @publiclab/community-reps,
 
Based on the question raised by a Public Lab user here https://publiclab.org/questions/Delaney/06-25-2018/how-to-retrieve-a-draft-of-a-research-note-on-pl-org

I guess we need to make drafts more accessible to users, currently, drafts can only be accessed by the user only through their dashboard.

We can opt one of the two options:-

1. Adding a new tab for Draft notes

![option_1](https://user-images.githubusercontent.com/20878070/41888994-d01f19c8-7925-11e8-976e-73a8262aa800.png)

2. Including Draft notes in the present research, co-authored sections

Please provide your thoughts on this. Thanks!

**Comment by jywarren** [comment]
There are a /lot/ of tabs there. Could we maybe figure out a way to build "coauthored" and "drafts" under "research"? Maybe looking at how it's done with the two subsections of Questions?

But this is really looking good!
