### ISSUE TITLE
db:seed error: Data too long for column 'field_capture_date_value' .

### ISSUE THREAD

**Issue by charleshuang80** [publiclab/plots2#293]
Error in trying to seed with rake db:seed. Getting the following error: ActiveRecord::StatementInvalid: Mysql2::Error: Data too long for column 'field_capture_date_value'. `field_capture_date_value` is being set to '2015-05-28 16:10:54 -0400', which is too long of a string for the field.

Problem is here https://github.com/publiclab/plots2/blob/ad7fa8d4970a4a831d7eea626be4e27cd295dbf7/db/seeds.rb#L66, and needs to change to Time.now.to_s(:short), and changing on line 67 would probably help as well.

**Comment by jywarren** [comment]
Hi, Charles - I believe this is fixed here: https://github.com/publiclab/plots2/pull/295

can you confirm by attempting an install from https://github.com/jywarren/plots2 ? Then I'll merge that PR. Thanks so much for helping us identify this issue!

**Comment by charleshuang80** [comment]
Hi Jeffrey,

The clean install worked fine. I ended up using the mysql databases I had already created previously, so the rake db:setup didn't quite work. Instead I ran
rake db:drop
rake db:create
rake db:migrate
then rake db:seed

All of that and the bower install worked. I'm not sure, for troubleshooting purposes, if it might help to add that as an alternative for people to try when setting up (it's what I did with the other version as well when I had issues with the database, and what finally worked after making the changes for these two issues).

**Comment by btbonval** [comment]
If you run into problems with `db:setup`, there are some notes in the README which should have worked for you.

`db:drop` is noted. Instead of `db:create` and `db:migrate`, you should be able to use `db:setup` again. And of course `db:seed` as the final step.

https://github.com/publiclab/plots2/blame/master/README.md#L78-L83
```
Initialize database with bundle exec rake db:setup

    if there are any errors, try one of these two fixes:
        run rake db:migrate
        OR
        in MySQL, drop database XXX; for each database in config/database.yml and then try rake db:setup again

rake db:seed to populate it with initial dummy data
```
