### ISSUE TITLE
answer deletion not working

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2939]
I wonder if this is a routing issue... I tried to delete this answer and was unable to!

https://publiclab.org/questions/marlokeno/09-20-2017/can-nasa-viirs-data-used-for-disaster-maps#a1056

**Comment by jywarren** [comment]
@Souravirus did we get this one too? Thanks for all your debugging this week!

**Comment by Souravirus** [comment]
Yeah see this. It would be helpful if you can post the full error log. Thank you!!

**Comment by Souravirus** [comment]
Yeah a routing error found. Sending a PR soon. Thanks!!

**Comment by jywarren** [comment]
oh, awesome!
