### ISSUE TITLE
bower install problem ENORESTARGET  No tag found that was able to satisfy ~7.4 (for jquery-file-upload)

### ISSUE THREAD

**Issue by charleshuang80** [publiclab/plots2#294]
Getting the following error when installing with bower: ENORESTARGET  No tag found that was able to satisfy ~7.4. Problem is here https://github.com/publiclab/plots2/blob/916fc51359fb3c4b4e23576e5aa08b63e5e9cf3b/bower.json#L10, where jquery-file-upload specified as 7.4. Changing to ~8.1.0 should work as that is the oldest available version.

**Comment by jywarren** [comment]
Hi, Charles - I believe this is fixed here: https://github.com/publiclab/plots2/pull/295

can you confirm by attempting an install from https://github.com/jywarren/plots2 ? Then I'll merge that PR. Thanks so much for helping us identify this issue!

**Comment by jywarren** [comment]
Thanks, Charles!
