### ISSUE TITLE
Skylight performance monitoring

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2941]
Trying to use Skylight.io, we're seeing an error:

```
E, [2018-06-08T22:14:35.131794 #176] ERROR -- Skylight: trace=2a619260-ed86-45c8-a072-c752080ccba8; failed to instrument span; msg=[E0003] Skylight::MaximumTraceSpansError [Trace#native_start_span]; endpoint=UsersController#profile
```

https://www.skylight.io/support/troubleshooting#e0003 says there's a limit of:

> Skylight limits the maximum number of spans (event sequent items) in a request to 2,048 to prevent a data overload. If your request is very complex, you may hit this limit and data will no longer be tracked for that request. 

But if it's only on UsersController, I'm not sure why it'd stop all data collection...

**Comment by jywarren** [comment]
@siaw23 - any ideas with this?

**Comment by siaw23** [comment]
@jywarren i haven't seen this one before, I reached out to them.

**Comment by jywarren** [comment]
thanks!

**Comment by siaw23** [comment]
just forwarded to you an email containing details in debugging this and some extra stuff... @jywarren

**Comment by jywarren** [comment]
Were you able to connect with them about the Open Source program as well, or should we try to get in touch again? Thanks!

**Comment by siaw23** [comment]
got sick, then forgot, but sent out a message a few seconds ago! any progresson skylight setup? @jywarren

**Comment by jywarren** [comment]
thanks! got their message and we're in the OS program now. Hope you're
feeling better! Still no data though, i'll write back.

**Comment by siaw23** [comment]
Great! OK. I can also follow up if you want me to.

**Comment by jywarren** [comment]
that would be super. I'm not sure what to try next...

**Comment by siaw23** [comment]
Hi Jeff, I'd like to look into this myself. Can you please share the link showing our data endpoints with me? @jywarren

**Comment by jywarren** [comment]
for sure --
https://oss.skylight.io/app/applications/GZDPChmcfm1Q/recent/5m/endpoints

I also shared the acct with you!

**Comment by jywarren** [comment]
I don't know if it's related, but we must've accidentally removed the gem in one of our recent major Rails version updates. readding it in https://github.com/publiclab/plots2/pull/3169

Let's see what that does!

**Comment by jywarren** [comment]
AHHHH ok we're back online in Skylight! @icarito @siaw23 

https://www.skylight.io/app/applications/GZDPChmcfm1Q/recent/6h/endpoints

awesome, it was the gem!

let's see data come in over the next day or two...

**Comment by jywarren** [comment]
![screen shot 2018-08-01 at 6 48 59 pm](https://user-images.githubusercontent.com/24359/43553164-a5ec6d42-95bb-11e8-9087-b2e5b772bc3f.png)

Public dashboard: https://oss.skylight.io/app/applications/GZDPChmcfm1Q/recent/30m/endpoints

**Comment by jywarren** [comment]
Added badge to our readme! https://github.com/publiclab/plots2/commit/05636a66132d1fbfdc1f321025a24fd5d3d55020

**Comment by jywarren** [comment]
[![View performance data on Skylight](https://badges.skylight.io/typical/GZDPChmcfm1Q.svg)](https://oss.skylight.io/app/applications/GZDPChmcfm1Q)
