### ISSUE TITLE
Some research note pages showing 500 errors

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2944]
https://publiclab.org/notes/MaggPi/05-11-2018/raspberry-pi-noir-close-up-imaging

https://publiclab.org/notes/MaggPi/05-21-2018/community-microscope-resolution-test

https://publiclab.org/notes/partsandcrafts/11-26-2017/building-a-raspberry-pi-microscope and it's corresponding post on stable: https://stable.publiclab.org/notes/partsandcrafts/11-26-2017/building-a-raspberry-pi-microscope

https://publiclab.org/notes/MaggPi/06-05-2018/usb-webcam-vs-raspberry-pi-v2-field-of-view-fov-comparison-community-microscope-initial-evaluation-2

What's causing this?

Oddly i wasn't able to find the errors in the logs - these pages are listed as rendering with 200 success... maybe i'm doing something obviously wrong, but I was confused by this...

**Comment by Souravirus** [comment]
Yeah right checking this

**Comment by jywarren** [comment]
oh thanks! I didn't think it's necessarily Rails 5 related... but was quite
mystified!

**Comment by Souravirus** [comment]
Yeah the links submitted in the issue are working. So, closing this for now.
