### ISSUE TITLE
Tests are failing due to recent merges

### ISSUE THREAD

**Issue by Souravirus** [publiclab/plots2#2952]
These are two errors in the two  PRs that were merged recently. 
1. `ERROR["test_create_a_user_with_omniauth_if_email_prefix_does_not_exist_in_db", Minitest::Result, 81.54402136499999]
 test_create_a_user_with_omniauth_if_email_prefix_does_not_exist_in_db#Minitest::Result (81.54s)
NoMethodError:         NoMethodError: undefined method 'using_open_id?' for nil:NilClass
            lib/authlogic_openid/authlogic_openid/session.rb:78:in 'authenticating_with_openid?'
            app/models/user.rb:431:in 'block in create_with_omniauth'
            app/models/user.rb:426:in 'create_with_omniauth'
            test/unit/user_test.rb:207:in 'block in <class:UserTest>'`
2. `ERROR["test_user_creation", Minitest::Result, 82.458089304]
 test_user_creation#Minitest::Result (82.46s)
NoMethodError:         NoMethodError: undefined method 'using_open_id?' for nil:NilClass
            lib/authlogic_openid/authlogic_openid/session.rb:78:in 'authenticating_with_openid?'
            lib/authlogic_openid/authlogic_openid/acts_as_authentic.rb:74:in 'save'
            test/unit/user_test.rb:10:in 'block in <class:UserTest>'`

@SidharthBansal, @jywarren Have a look here.

**Comment by jywarren** [comment]
Oh, oops -- how did that happen? Maybe an issue with failing to rebase?

**Comment by SidharthBansal** [comment]
I am looking at it. Just wondering why hasn't Travis failed? 
Thanks for informing.

**Comment by SidharthBansal** [comment]
The errors which you posted above appeared in the pr because by mistake I pushed some wrong code.
 Later on, when I changed the content. Ran travis again. They passed. But the footprints of the previous error message was not erased. Are they those messages?

**Comment by Souravirus** [comment]
The errors are now cleared @SidharthBansal

**Comment by SidharthBansal** [comment]
Great!
Can we close this issue?

**Comment by Souravirus** [comment]
yeah
