### ISSUE TITLE
"choose file" button on Research Note edit not working

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#2969]
### Please describe the problem (or idea)
I was updating a research note with a new image, clicked edit and used the "choose file" button to the right of the lead image spot. The pop up walked me through selecting the image from my computer, but the image didn't upload when I clicked "open." I was able to get the image uploaded from the drag and drop feature, but this button might not be working? 

This is the RN I was updating https://publiclab.org/notes/stevie/08-11-2017/interview-ramsey-sprague (the lead image on it was previously broken)

**Comment by jywarren** [comment]
Thanks Stevie! 
Anyone looking at this, note that the drag and drop interface next to the button does still work. 

Just adding some debug logs from reproducing this (on Chrome browser):

Line 1032 of `jquery.fileupload.js` -- `            files = $.makeArray(fileInput.prop('files'));`

Error was "Uncaught RangeError: Maximum call stack size exceeded"

This can be reproduced at https://publiclab.org/post (if logged in)

Note that Jquery File Upload's tracker is here, so it's probably worth looking at! https://github.com/blueimp/jQuery-File-Upload

Any help appreciated!

**Comment by jywarren** [comment]
Stevie mentioned:

```
for some reason i can't get images up upload for the main image of a research note. any ideas?

i tried both drag and drop and the button and every time i pick one the scroll bar shows up below to show it's loading, but it just says "no file chosen"

oh weird but my photo came through when i hit publish
```

**Comment by jywarren** [comment]
I've tracked this error a bit more. It's on line 926 of this file:

https://publiclab.org/lib/jquery-file-upload/js/jquery.fileupload.js

```js
            this.options.fileInput = this.options.fileInput.map(function (i, el) {
```

That's part of this library we use: https://github.com/blueimp/jQuery-File-Upload

**Comment by jywarren** [comment]
Interestingly this doesn't happen at https://publiclab.github.io/PublicLab.Editor/examples/ -- the progress bar is shown properly. They should be running at the same version... maybe there's some problem with the interaction between the editor and the main PublicLab.org site code?

**Comment by jywarren** [comment]
I believe I've figured this out and created a first-timers-only issue to fix it! 👍 🎉 

https://github.com/publiclab/plots2/issues/3441
