### ISSUE TITLE
Create a tutorial video for running plots2

### ISSUE THREAD

**Issue by danabauer** [publiclab/plots2#297]
Similar to this for MapKnitter: http://publiclab.org/notes/warren/02-19-2015/tutorial-video-installing-mapknitter-2

I'm happy to take this task!

**Comment by jywarren** [comment]
OMG that would be the awesomest EVER, Dana!

**Comment by ebarry** [comment]
wow that would be so awesome Dana! what do you need from us?

--

txt only: +1 336-269-1539
@lizbarry <http://twitter.com/lizbarry>

**Comment by jywarren** [comment]
Was thinking this could be done as an ASCII cast, using asciicinema, from a standard Cloudnine instance, as outlined in the README.

**Comment by ananyo2012** [comment]
@jywarren Can be given as Google Code-in task?

**Comment by jywarren** [comment]
Sure!

**Comment by jywarren** [comment]
Hi, @ananyo2012 -- was this made into a GCI task or shall I try that?

**Comment by ananyo2012** [comment]
Just catching up with things Jeff. Well respond to this soon.

**Comment by SidharthBansal** [comment]
@jywarren I think we can close this
