### ISSUE TITLE
Community Check-in #7 Summer Of Code Week 8 

### ISSUE THREAD

**Issue by milaaraujo** [publiclab/plots2#2971]
Hi everybody 👩‍💻 👨‍💻!
If you're new here, welcome, and please try some of our [first-timers-only issues](https://publiclab.github.io/community-toolbox/#r=all). This is a checklist for publiclab/soc.

@stefannibrasil @milaaraujo @MargaretAN9 @Gauravano @ViditChitkara @tech4GT @mridulnagpal @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @ccpandhare @icarito @abTest-123 @steviepubliclab @ebarry @publiclab/soc @publiclab/reviewers

Hi guys! How was your weekend? And what is the plan for this week?
If you have not planned yet. Just leave a Hi! so that we could know that you are well. 🛩

Rail Girls Summer of Code is starting today! So this is officially our first week! 🎉  Stefanni and I are very happy to be part of the program.

Today, with the help of our coaches, we are organizing the tasks to be done during the week. Our plan is - at least try 😄 - to follow the schedule posted by Stefanni [here](https://github.com/publiclab/plots2/issues/2755). Stefanni is also working with the issue #2847, I'll work with her on that.

We also would like to know if there is a specific API function that any of you need or want to be implemented!

As always, if you're waiting for a review, or if you're stuck, please request help
here OR leave a comment with @publiclab/soc and @publiclab/reviewers for
some input.

Have a nice week!
Thank you!

**Comment by jywarren** [comment]
Hi, @milaaraujo!!! Fantastic and welcome to WEEK 1!!!

**Comment by Gauravano** [comment]
Hi @publiclab/soc, 
Welcome @milaaraujo and @stefannibrasil :tada: :smile: 

This week I would be completing the Comment moderation system #2304 and 
Configurable email notification preferences #213 .
 Thanks!

**Comment by ebarry** [comment]
Hi everyone, i'm back from some time with my family and happy to rejoin the energy here. Excited that the RailsGirls Summer of Code is beginning!

**Comment by Souravirus** [comment]
Hi everyone, I have completed the rails 5.2 update. Let's hope it works fine. For now I am working on some fixes regarding rails update and failure of jasmine tests. Thank you!!

**Comment by SidharthBansal** [comment]
Hi everyone. This week we will complete all the backend stuff of the Authentication System.

**Comment by sagarpreet-chadha** [comment]
Hi all !

I will work on mapknitter project and try to integrate leaflet-environmental-library to it .

AND @jywarren just added the library to npm : https://www.npmjs.com/package/leaflet-environmental-layers  🎉

**Comment by namangupta01** [comment]
Hey Everyone, i just completed working on the parsing of email feature from gmail and yahoo. It is just similar to github. And in case of emails coming from yahoo, parsing of email is even better then github's parsing. :smile: . This week i will working on some more test and if possible will start some basic work on reply by twitter.

**Comment by SidharthBansal** [comment]
@publiclab/soc publiclab.org/auth/twitter is functional. You all can check it out.
Thanks

**Comment by SidharthBansal** [comment]
Also, please check out publiclab.org/auth/facebook

**Comment by jywarren** [comment]
For folks looking for a small project to do a little work on, consider:

* Display of notes in a thumbnail grid: https://github.com/publiclab/plots2/issues/1097
* A small image upload bug here: https://github.com/publiclab/plots2/issues/2969

We'd really love to get these solved! Thanks, all!

**Comment by stefannibrasil** [comment]
Thanks, everyone! Glad to be officially joining you =)

Just a note, we are planning our work here at the [Projects](https://github.com/publiclab/plots2/projects/5) feature, if you want to check it out :) 

Maybe we can even use that to add the community API requests to have it all at the same place, what do you think? Sometimes it's easy to let some issues pass when someone mention us on Issues/Pull Requests comments. I believe you can all add new Issues there. Let me know what do you think.

**Comment by jywarren** [comment]
I love the Projects feature you all have set up! Looks great, and they've added a lot of new features. 

I know @cheneyshreve has been working on a very exciting new feature to auto-complete tagnames, and is using the URL `https://publiclab.org/tags/suggested/______`-- which we also use for the tag form autocompletion. I wonder if that's a good one to try to refactor into a more standard API method. Just an idea!

**Comment by jywarren** [comment]
Is anyone up for sending out next week's Community Check-in? Thanks @milaaraujo for adding in some helpful links this week!

**Comment by jywarren** [comment]
awesome, thanks Sourav!

**Comment by stefannibrasil** [comment]
yes, sure, @jywarren I've added the #2925 PR to our To-do, we can work on that in the next few weeks, possibly the next one!

**Comment by jywarren** [comment]
I just published latest code to production!!!! http://publiclab.org

![screen shot 2018-07-06 at 7 59 08 pm](https://user-images.githubusercontent.com/24359/42404444-240dfa20-8157-11e8-9b73-79337d893760.png)

**Comment by stefannibrasil** [comment]
looks amazing, good work! :)

**Comment by Souravirus** [comment]
opened in #3010
