### ISSUE TITLE
Comment update route error

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2972]
Hi, @Souravirus -- hopefully the last one! This just showed a 404:

https://publiclab.org/comment/update/19965?body=lalalala

`https://publiclab.org/comment/update/19965?body=Adding+a+reference+here+-+this+looked+pretty+cool%21+%0D%0A%0D%0Ahttps%3A%2F%2Fwww.reddit.com%2Fr%2Fmicroscopy%2Fcomments%2F8giinz%2Fplm_red1_polarized_light_to_dso_chrysotile%2F%0D%0A%0D%0A%3Cblockquote+class%3D%22reddit-card%22+data-card-created%3D%221530631281%22%3E%3Ca+href%3D%22https%3A%2F%2Fwww.reddit.com%2Fr%2Fmicroscopy%2Fcomments%2F8giinz%2Fplm_red1_polarized_light_to_dso_chrysotile%2F%22%3EPLM%28+Red-1%2C+Polarized+Light%2C+to+DSO%29+chrysotile+asbestos+found+in+CA+oil+field+pipeline+ducting%3C%2Fa%3E+from+%3Ca+href%3D%22http%3A%2F%2Fwww.reddit.com%2Fr%2Fmicroscopy%22%3Er%2Fmicroscopy%3C%2Fa%3E%3C%2Fblockquote%3E%0D%0A%3Cscript+async+src%3D%22%2F%2Fembed.redditmedia.com%2Fwidgets%2Fplatform.js%22+charset%3D%22UTF-8%22%3E%3C%2Fscript%3E%0D%0A%0D%0A%5B%21%5BScreen_Shot_2018-07-03_at_11.22.22_AM.png%5D%28%2Fi%2F25392%29%5D%28%2Fi%2F25392%29%0D%0A%0D%0A%5B%21%5BScreen_Shot_2018-07-03_at_11.22.13_AM.png%5D%28%2Fi%2F25393%29%5D%28%2Fi%2F25393%29%0D%0A%0D%0A&image%5Bphoto%5D=`

It looks like probably a routing issue to me. Mind taking a look? Thanks for your hard work on routing in the past week!

**Comment by Souravirus** [comment]
Ok seeing this. Thank you for reporting!!

**Comment by Souravirus** [comment]
Hi @jywarren, can I know how to get to this link. I mean the updating the comment to question as well as answer are working fine.

**Comment by jywarren** [comment]
Hmm, i wonder if it was somehow related to the specific content i tried to
update? It was for a research note, not a question, however.

**Comment by Souravirus** [comment]
Yeah ok I am getting a routing error while trying some similar comment to this link https://publiclab.org/comment/update/19965?body=lalalala So, I am sending a PR related to this.
