### ISSUE TITLE
Github button for OAuth login

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#2975]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

**Introduce font awesome icons for github provider to multiple pages.** 

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Insert**  font-awesome icons into following four files and link them to https://publiclab.org/auth/github. Please add the icons horizontally. They should appear after google icons, in the format:

`<a href="/auth/github" id="connect-github"><span class="btn btn-default"><i class="fa fa-github" style="font-size:20px;color:green;"></i></span></div></a>`

1)https://github.com/publiclab/plots2/blob/57533a44739d85c33f16d3253aea29399f5aed7f/app/views/users/edit.html.erb#L8-L12
2)https://github.com/publiclab/plots2/blob/57533a44739d85c33f16d3253aea29399f5aed7f/app/views/layouts/_header.html.erb#L187-L190
3)https://github.com/publiclab/plots2/blob/57533a44739d85c33f16d3253aea29399f5aed7f/app/views/users/new.html.erb#L27-L31
4)https://github.com/publiclab/plots2/blob/57533a44739d85c33f16d3253aea29399f5aed7f/app/views/user_sessions/new.html.erb#L41-L44
Please make sure that all the four icons are same.
- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)
Part of #2676.

**Comment by jywarren** [comment]
🎉

**Comment by Sensational-Code** [comment]
I'd like to be assigned to this issue.

**Comment by SidharthBansal** [comment]
Sure go ahead
