### ISSUE TITLE
clean up print stylesheet

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#298]
* [x] browsers add a header with the source URL on the print, which overlap page content
* [x] titles take up too much space on first page, esp. with vertical images
* [ ] licensing info in footer is blocky and too big
* [x] use `a, a:after { content: normal !important; }` to disable inline links (offer a button for this)
* [ ] we could [go nuts](http://stackoverflow.com/questions/1960939/disabling-browser-print-options-headers-footers-margins-from-page?rq=1) and prevent Firefox etc from including page numbers, urls in headers

**Comment by ebarry** [comment]
In the PDF print i made of http://publiclab.org/wiki/oil-testing-kit there is no page URL listed anywhere

**Comment by jywarren** [comment]
That's a print dialog box option in some browsers, so unless you want it to
show up, it's not a problem.

**Comment by jywarren** [comment]
I think i got most of this, but couldn't reproduce the blocky footer attribution text issue -- perhaps it only happens in Safari, or perhaps it was resolved by the margin spacing tweaks?

**Comment by jywarren** [comment]
![image](https://cloud.githubusercontent.com/assets/24359/8488652/47c4f848-20e2-11e5-9cdb-a4d816bac8f8.png)

![print](https://cloud.githubusercontent.com/assets/24359/8488654/4b895c08-20e2-11e5-9a6d-9ab7376e63ad.png)

**Comment by jywarren** [comment]
![tmp_24934-img_20150702_180235 21976938560](https://cloud.githubusercontent.com/assets/24359/8488909/c2e3b08a-20e4-11e5-9675-65d75ae4cbc6.jpg)
