### ISSUE TITLE
Codifying a callout codifies the callout link

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#299]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem
I was writing a research note comment trying to refer to `@publiclab` on twitter. I used the code ticks to prevent `@publiclab` from turning into a link:

```
`@publiclab`
```

What happened instead was that the link for publiclab's profile in Markdown (`[@publiclab](/profile/publiclab)`) got codified. It wasn't a clickable link, but rather displayed just as shown here.

The callout replacement should not execute inside of any code or quote areas.

## Solution
The simplest way of fixing this is changing the regexp of the `FINDER` we are using for the callout. Here is the regexp for the finder https://github.com/publiclab/plots2/blob/master/config/initializers/constants.rb#L2

We should change the regexp to
```
/(^|\s)\@([\w-]+)/
``` 
i.e. use a `\s` instead of `\W` so that mentions like `@publiclab` are only recognized when there is a space before the `@` symbol. This also solves a issue that was occurring due to the wrong use of regexp where even if you used a non-word symbol before `@` it was recognized as a mention which shouldn't happen.

## Steps to Fix

- [x] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by btbonval** [comment]
We could update the regex but I think that is not an appropriate course of action. Rather there should be some way to parse the comment text and only apply the callout filter to plain text parts.

Here's the code where the regex is applied indiscriminantly to all text in the comment:
https://github.com/publiclab/plots2/blob/dc88bdcf7a99ce47ebccd23e2443dbaf349328b6/app/models/drupal_comment.rb#L62-L65

**Comment by jywarren** [comment]
I agree - this also affects the new 'foldaways' feature:
http://publiclab.org/wiki/authoring-help#Foldaways

**Comment by btbonval** [comment]
Callouts in foldaways, or how foldaways are used inside / outside of code demarcation?

**Comment by jywarren** [comment]
ah, sorry, the latter. I tried to indicate how foldaways should be coded,
using code delimiters, and it just made an active foldaway.

**Comment by jywarren** [comment]
This has a clear path forward, and I'm marking it as `help-wanted` -- we can write a test for this similar to this: https://github.com/publiclab/plots2/blob/master/test/unit/drupal_node_revision_test.rb#L70-L73

Which would check that a `drupal_node_revision` with the following `revision.body`:

```
`@jywarren`
```

does not include a link, or something like:

```ruby
assert !revision.include?('href')
```

**Comment by 500swapnil** [comment]
I would like to take this up

**Comment by ananyo2012** [comment]
Here is the regexp for the `FINDER` : https://github.com/publiclab/plots2/blob/master/config/initializers/constants.rb#L2
Changing the regexp to `/(^|\s)\@([\w-]+)/` solves this issue. Also the change in regexp won't affect the normal functioning of the finder. We can confirm it by writing a functional test. Should I follow this approach and make it a `first-timers-only` issue?

**Comment by jywarren** [comment]
Yes, that sounds good -- although it seems it may already be claimed?

**Comment by ananyo2012** [comment]
Made this a `first-timer-only` issue. @jywarren If anyone isn't working on this perhaps I can make this as a Goggle Code-in Task?

**Comment by ananyo2012** [comment]
Added this as a Google Code-in task.

**Comment by jywarren** [comment]
+1!

**Comment by StlMaris123** [comment]
Hello, i would like to work on the issue

**Comment by jywarren** [comment]
That would be great, and we'd love to have your help! Happy to answer questions and help you get started. Thanks!

**Comment by StlMaris123** [comment]
I have updated the constants.rb file, i just needed some help on how i will do the tests. Thanks

**Comment by jywarren** [comment]
Found your PR in #1297 -- will comment over there, thanks!
