### ISSUE TITLE
Copying from research notes to wiki pages

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/plots2#300]
This is an improvement to move research more easily from research notes to wiki pages. Currently, only the author of a research note can access the markdown of a research note (unless you have admin privileges).  If there was a "copy markdown" button in research notes and possible comments as well, then the research note could be replicated into a wiki page by someone who wasn't an author. 

It would be nice to link between source and destination for tracking purposes, but I think we can rely on manual linking for now.

**Comment by jywarren** [comment]
Great idea. This wouldn't be hard, either.
