### ISSUE TITLE
add subscribe and unsubscribe links to email notifications based on tags

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3008]
@namangupta01 this could be cool - a section in the email notifications to subscribe to tags (or unsubscribe) - like "follow discussions on 'spectrometry'"

Starts to look more like a mailing list!

**Comment by namangupta01** [comment]
Thats sounds cool.

**Comment by jywarren** [comment]
Let's also add a "subscribe" to the emails for when new tags are added, something like:

`Follow questions posted related to this topic`

https://github.com/publiclab/plots2/blob/master/app/views/subscription_mailer/notify_tag_added.html.erb

**Comment by jywarren** [comment]
@SidharthBansal maybe this is of interest?

**Comment by SidharthBansal** [comment]
I think this is what we are have already built. Just we need to add the link in the email body and everything is complete. 
It can be converted in fto after #4555 is merged.

**Comment by SidharthBansal** [comment]
I was just going to write this comment. lol. You are quicker than me. Let's do it like you said.
So we can build 2 ftos from this. Great.
@geekychaser you asked in #4131 to create some `first timers only`. Can you please create 2 issues for this?
Thanks all.

**Comment by jywarren** [comment]
😁🙌

**Comment by geekychaser** [comment]
@SidharthBansal Yes i would love to create these ftos.
thank you

**Comment by SidharthBansal** [comment]
Awesome. Then let's complete it. 
This will be a BIG Project for you. You have to monitor activity of all the collaborators working on the ftos created by you. Will you be able to do it? I saw you did large number of tasks. So, next task is to help others at PL. 
This is the workflow for this project. 
Step 1: Understand the functionality of the project
Step 2: Identify all the emails where we need to prompt the users for getting subscription to tags on PL.
Step 3: Creating a single fto for`Managing Subscription` on each email as per step 2
Step 4: Creating a single fto for` Subscription to all tags related to topic_name` on each email as per step 2
Make sure everything works before creating ftos in step 3-4. We can't expect first timers will be knowing rails. We teach them only git and open source in ftos. So testing will be down by you.
Step 5: Encourage people to do them
Step 6: Review their PRs and suggest changes
Step 7: Ping me or Jeff or Gaurav to ping them when they are complete.

Does this makes sense Rishabh?

**Comment by geekychaser** [comment]
Thank you very much, I am ready for the work as mentioned.
can you please guide me more of step2
thank you

**Comment by SidharthBansal** [comment]
Right now I built a route /subscribe/multiple/tag/taglist. Taglist is the list of tags separated with commas.
We need to pass the list of tags for the topic for which the email is.
For example the email is from liked page https://publiclab.org/notes/cess/10-24-2018/outreachy-proposal then on clicking on the link1 user will be subscribed to all the tags of that page. Makes sense now?

**Comment by SidharthBansal** [comment]
I have added the required labels.
Thanks @geekychaser
Is anything left in this issue?

**Comment by geekychaser** [comment]
No I don't think. You can check this out if you want.

**Comment by SidharthBansal** [comment]
Yeah sure. Checking this.

**Comment by SidharthBansal** [comment]
Looks good to me.
I think we have completed this issue.
