### ISSUE TITLE
Community Check-in #8 Summer Of Code Week 9 

### ISSUE THREAD

**Issue by Souravirus** [publiclab/plots2#3010]
Hi everybody :woman_technologist: :man_technologist:!
If you're new here, welcome, and please try some of our [first-timers-only issues](https://publiclab.github.io/community-toolbox/#r=all). This is a checklist for publiclab/soc.

@stefannibrasil @milaaraujo @MargaretAN9 @Gauravano @ViditChitkara @tech4GT @mridulnagpal @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @ccpandhare @icarito @abTest-123 @steviepubliclab @ebarry @publiclab/soc @publiclab/reviewers

Hi guys! How was your weekend? And what is the plan for this week?
If you have not planned yet. Just leave a Hi! so that we could know that you are well. :small_airplane:

Last week I did some of the follow up fixes of rails 5.2 upgrade and currently I am working on changing the jasmine tests as it is not working on phantomjs command line. So, I am modifying it to teaspoon mocha. :smile: :smile: 

We also would like to know if there is a specific API function that any of you need or want to be implemented!

As always, if you're waiting for a review, or if you're stuck, please request help
here OR leave a comment with @publiclab/soc and @publiclab/reviewers for
some input.

Have a nice week!
Thank you!

**Comment by SidharthBansal** [comment]
Hi everyone,
I will complete #2676 issue this week. We are just left with some front-end issues listed there. Then I will start with my second project of Bootstrap Upgradation.
All the four providers are working properly. 
I have created the branch for Bootstrap Upgradation too.
Thanks

**Comment by jywarren** [comment]
Hi all! A lot of code finally made it into production this past week. Please be testing it out and identifying follow-ups!

@publiclab/soc mentors will also be writing 2nd midterm evals this week. Please be sure to check in on this thread with your latest updates -- and it's very helpful if you can present your work in a milestone, as well! Adding all your new and old issues to a single milestone is great. 

Thanks!

**Comment by SidharthBansal** [comment]
Hi @publiclab/soc,
# OAuth Login Project(Almost Completed)
MAIN ISSUE https://github.com/publiclab/plots2/issues/2676
MILESTONE https://github.com/publiclab/plots2/milestone/18
We have completed OAuth project. Backend stuff is completed along with tests for all the providers.
You can check out the feature on 
* publiclab.org/auth/facebook
* publiclab.org/auth/google_oauth2
* publiclab.org/auth/twitter 
* publiclab.org/auth/github.
You can see the checklist on https://github.com/publiclab/plots2/issues/2676. In the checklist the front end portion is broken down in ftos. The new feature commented by @jywarren in #2676 is under progress.
# Bootstrap Upgrade(In progress)
I am moving towards my second project that is Bootstrap upgrade.
We have set up the bootstrap branch. Also, all the glyphicons are changed to font awesome icons. I am currently installing newer bootstrap version.

**Comment by sagarpreet-chadha** [comment]
Hi everybody ! 

### Work done :

 * List of layers completed can be found here :  https://github.com/publiclab/leaflet-environmental-layers/issues/1
*  Also added Leaflet-hash for easy sharing of map links . 
*  And @jywarren added the library to npm and bower as well : https://www.npmjs.com/package/leaflet-environmental-layers

### Work to be done : 

For now only 2 layers are left : 
* watershed mapper layer -> EPA website maintainers are not helpful .
* WaterReporter.org -> I had a meeting with them and they were very eager to help , i have mailed them last week but got no response ---will try to contact them again !

Currently working on integrating leaflet-environmental-layers library to Mapknitter website in PR https://github.com/publiclab/mapknitter/pull/269#issuecomment-403526315 .


@publiclab/soc ...if anyone can help me in https://github.com/publiclab/mapknitter/pull/269#issuecomment-403526315 ...it would be great .

Thanks !

**Comment by Souravirus** [comment]
Hi everybody,
### **Rails 5 upgrade**
Rails 5 upgrade is done completely and we are currently running on rails 5.2.0. So, I worked on two upgrades after first evaluation, one for rails 5.1 and other for rails 5.2. 

### **changing javascript tests**
I am currently working on this and the issue for it is #2967 and the PR for this is #2997. So, I am changing the tests to teaspoon-mocha. And any help would be appreciated. 

Thanks!!

**Comment by stefannibrasil** [comment]
Hello, everyone!

@milaaraujo and I this week are planning to start refactoring the Search endpoints. We are beginning by removing all the duplications there and then see how we can improve this part. Will be opening a PR for this soon, we will also check with our coaches before that.

So far, it's working and we also added a few more tests to make sure we didn't break anything ;)

**Comment by Gauravano** [comment]
Hi @publiclab/soc , 

### Work done past week: 
1. Spam Moderation System (part - I) done https://github.com/publiclab/plots2/pull/2957
2. Welcome Email at Signup https://github.com/publiclab/plots2/pull/3025

### This week's goal:
1. Welcome Email with OAuth and Fallback email  - https://github.com/publiclab/plots2/pull/3052
2. Spam comment moderation on profile page and /spam
3. Configurable email settings - https://github.com/publiclab/plots2/pull/2985

Also, as many newcomers are contribute, I will try my best in reviewing and opening FTO's. 
Thanks!

**Comment by jywarren** [comment]
Hi @sagarpreet-chadha -- I left some more potential layers on this note: https://publiclab.org/questions/sagarpreet/07-01-2018/what-more-data-layers-can-we-show-on-map

🎉

**Comment by jywarren** [comment]
Hi all! Is anyone able to do a check in today? Otherwise I can tomorrow morning. Thanks! @publiclab/soc

**Comment by Gauravano** [comment]
Hi @jywarren I would like to do check-in . Thanks!

**Comment by SidharthBansal** [comment]
So lets close this one
