### ISSUE TITLE
Shift the providers up on sign up page

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#3012]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Please describe the problem (or idea)
It is easy to sign up with the providers like facebook etc. than with email and password. So, we need to shift them up
![image](https://user-images.githubusercontent.com/20972099/42425697-2e12adb6-833e-11e8-8864-d1cd731d4dc4.png)
![image](https://user-images.githubusercontent.com/20972099/42425700-3562b372-833e-11e8-8b81-9894ae4d411c.png)
Also, centre align the buttons

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 Swap the providers and email-password sign in
app/views/users/new.html.erb
- [ ] Centre align the provider icons
- [ ] Make the text on the page looks good

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)
Part of #2676.

**Comment by dewanhimanshu** [comment]
can i try this?

**Comment by SidharthBansal** [comment]
Yes

**Comment by chrisbridges** [comment]
So you would essentially like to swap the "Sign up with" option and the form? Putting the "Sign up with" buttons on top?

**Comment by SidharthBansal** [comment]
Right

**Comment by bhargavn** [comment]
Can I try this?

**Comment by SidharthBansal** [comment]
@dewanhimanshu is working on this. So, other guys can take other issues
