### ISSUE TITLE
Shift Link to on edit page

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#3014]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Please describe the problem (or idea)
Make the ``Link to`` OAuth providers appear before the Save on the edit page button. Also make the text "Link to" appears similar to "Email" etc.
![image](https://user-images.githubusercontent.com/20972099/42425754-ccfb912c-833e-11e8-891f-43e5aed1bf07.png)

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 Swap the providers and save button
app/views/users/edit.html.erb
- [ ] Make the text on the page looks good
- [ ] Make the text appear the same for "Link to" as it appears for "Email" etc.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)
Part of #2676.

**Comment by CoderJolly** [comment]
for local testing, der are problems with config,yml file........pls suggest he changes to be done for local testing

**Comment by SidharthBansal** [comment]
What type of errors?

**Comment by CoderJolly** [comment]
Dis comes wen i do rake db:migrate

<img width="620" alt="screen shot 2018-07-10 at 1 37 11 am" src="https://user-images.githubusercontent.com/25739036/42473299-dd04f16e-83e1-11e8-8ed2-d4b80b8658e4.png">

**Comment by namangupta01** [comment]
Just copy `database.yml.sqlite.example` to `database.yml` if you want to use sqlite db.

**Comment by CoderJolly** [comment]
not working still

**Comment by CoderJolly** [comment]
ok thnks

**Comment by nataliyah123** [comment]
can I work on this issue?.

**Comment by juknaCodes** [comment]
I was able to run the code. But I am not getting the Link To functionality in the Profile Edit. 
![image](https://user-images.githubusercontent.com/30264032/42504128-5b4e715a-8458-11e8-8fa6-ea7c85426c10.png)

**Comment by SidharthBansal** [comment]
You need to remove the line rails.environment=production then it would work

**Comment by CoderJolly** [comment]
okay

**Comment by CoderJolly** [comment]
is dis still open?
