### ISSUE TITLE
ical files are broken

### ISSUE THREAD

**Issue by dbeavers** [publiclab/plots2#302]
For example, if you download the ical on http://www.publiclab.org/notes/stevie/07-08-2015/new-orleans-map-viewing-party and then view the file contents you will find it is useless.
BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VEVENT
CLASS:PUBLIC
DESCRIPTION:false
DTSTART;VALUE=DATE:0NaNaNaNTaNaNaN
DTEND;VALUE=DATE:0NaNaNaNTaNaNaN
LOCATION:false
SUMMARY;LANGUAGE=en-us:New Orleans Map Viewing Party
TRANSP:TRANSPARENT
END:VEVENT
END:VCALENDAR

**Comment by ebarry** [comment]
hi @dbeavers is this still an issue?

**Comment by dbeavers** [comment]
I can't find any way to check it now.  Where can I find a page that
generates a .ical file?

**Comment by ebarry** [comment]
hmm i'm not sure. We might not be doing iCal at all anymore, in which case we could also close https://github.com/publiclab/plots2/issues/354

**Comment by jywarren** [comment]
https://publiclab.org/feed/tag/event:rsvp.ics -- see #354 -- although we could add a new one to make this link more visible.

**Comment by jywarren** [comment]
I believe this is a duplicate of #354, which was an experimental and unfinished feature -- head over there for next steps!
