### ISSUE TITLE
Redirect user to /tag/[search-param] if wiki page doesn't exist

### ISSUE THREAD

**Issue by Gauravano** [publiclab/plots2#3027]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Please describe the problem (or idea)

Whenever someone searches for a wiki page that doesn't exist, the user is either redirected to make a new page or to the login page.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

The user should be redirected to /tag page instead of forming new wiki

- [ ] 📝 Change the app/controllers/wiki_controller.rb such that user is redirected to /tag/[search] 

Replace these lines of code 
https://github.com/publiclab/plots2/blob/master/app/controllers/wiki_controller.rb#L67-L73

with   

```ruby   
  flash[:notice] = "The wiki page does not exist, but here are notes tagged with #{params[:id]}."
  redirect_to '/tag/' + params[:id]
  return
````

- [ ] Fixing tests -- mention (@gauravano) after above step for fixing tests 

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

For solving #3026.

**Comment by nataliyah123** [comment]
Is this issue claimed by anyone .if not can i try

**Comment by CoderJolly** [comment]
pls assign me this issue

**Comment by Gauravano** [comment]
Either of you could start with this. Make sure to mention here. Thanks!

**Comment by CoderJolly** [comment]
PR sent @Gauravano

**Comment by nataliyah123** [comment]
@Gauravano .

- The following code is creating the security warning by brakeman(possible unprotected redirect) ,Should 
   this be excluded from the check
`redirect_to '/tag/' + params[:id]`

- The second test it is failing is "Avoid too many return statements within this method" 

- PR sent

please help
Thanks

**Comment by Gauravano** [comment]
1. Replace https://github.com/publiclab/plots2/blob/master/test/functional/wiki_controller_test.rb#L578-L588 

with

```
  test "Invalid date tags aren't added" do
    @user = UserSession.create(users(:jeff))
    @node = nodes(:wiki_page)
    slug = @node.path.gsub('/wiki/', '')
    @node.add_tag('date:bad', @user)

    assert_equal false, @node.has_power_tag('date')
    # assert_equal "anything goes", DateTime.strptime(@node.power_tag('date'),'%m- %d-%Y').to_date.to_s(:long)

    get :show, params: { id: slug }
    assert_response :success
  end
```

2. Replace https://github.com/publiclab/plots2/blob/master/test/functional/wiki_controller_test.rb#L435-L440

with 

```ruby
  test "should redirect to tag page if wiki page doesn't exist" do
    get :show, params: { id: 'A-new-wiki-page' }
    assert_response :redirect
    assert_redirected_to '/tag/A-new-wiki-page'
  end
```
This would remove the travis errors.

**Comment by CoderJolly** [comment]
I m doing it now and den raising PR @Gauravano

**Comment by Gauravano** [comment]
Actually @CoderJolly as @nataliyah123 has also raised PR, it would be great if you can add the above steps to his PR only. What do you say?

**Comment by Gauravano** [comment]
hi @CoderJolly any progress regarding the addition of tests to #3037?

**Comment by Gauravano** [comment]
Hi @CoderJolly you are required to commit these https://github.com/publiclab/plots2/issues/3027#issuecomment-404321676 changes to #3037. Should I add steps for fetching and committing to an existing PR?

**Comment by CoderJolly** [comment]
Yes sir, pls do so. I tried to figure it myself but was unable to do so

**Comment by CoderJolly** [comment]
Done.....

**Comment by Gauravano** [comment]
I guess you pushed the branch to your own repo, please push using `git push https://github.com/nataliyah123/plots2 wikipgissue` Thanks!

**Comment by Gauravano** [comment]
@CoderJolly any update on this. Sorry, just excited to see it in work :sweat_smile:

**Comment by CoderJolly** [comment]
Actually this error came when i did it, and i forgot to upload...apologies

<img width="849" alt="screen shot 2018-07-21 at 1 15 29 am" src="https://user-images.githubusercontent.com/25739036/43022107-b9e25fdc-8c83-11e8-810b-12f5b24647e3.png">

**Comment by Gauravano** [comment]
hmm, let me try!

**Comment by Gauravano** [comment]
Ok, I pushed your commit. I guess its due to permission issue. As I am a member of PL so I can push to other's PR. Thanks, @CoderJolly  for completing PR. 
Also, we would love to have your help on other issues, so if you are looking for new tasks, you can check here https://publiclab.github.io/community-toolbox/#r=all . Thanks!

**Comment by CoderJolly** [comment]
no problem

**Comment by jywarren** [comment]
Complete, thank you everyone! (#3037)
