### ISSUE TITLE
Not getting email notifications for comments on research notes

### ISSUE THREAD

**Issue by gretchengehrke** [publiclab/plots2#303]
I'm using Google Chrome on OSX Yosemite, and I am not receiving email notifications when people comment on my research notes, though I have heard this is supposed to be a feature.  Thanks!

**Comment by ebarry** [comment]
can you search your spam folder for "do-not-reply@publiclab.org"

--

txt only: +1 336-269-1539
@lizbarry <http://twitter.com/lizbarry>

**Comment by gretchengehrke** [comment]
Ohhhh!  Yes -- they are in there.  Thanks!!
