### ISSUE TITLE
Password checker field in OAuth Login

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#3032]
### Please describe the problem (or idea)
A user creates an account by the legacy authentication system. The field password_checker is set as zero. Now he tries to login. The username will be taken. We will check if the user having this username has password_checker field as zero. Yes the user has it set as zero we will check if the password matches and logs him in.

Let us define the fields for provider
Facebook 1
Github 2
Google 3
Twitter 4
A new user creates his account using provider. Password checker will be initialised as mentioned above. Then an email is sent to his account to change the password. If the user resets his password then password checker field is set to zero.
Suppose he forgets to change his password. So it will be a non zero field until he resets his password.
Without resetting the password user tries to login with the username and password. He enters wrong password. Then the backend flow will be like follows. We will fetch the user from the username Then we will fetch the password checker field. We see that this is 1 that means the user has created his account via Facebook. So we will notify the user that he has to change his password by going to forget password.

We will set the field of all the existing users in our database as zero.
If the field is zero and a user links his account then the password checker field need not to be changed.

We don't have to do anything with the user tag model here. Just we need to migrate the user model.
Part of #2676

**Comment by SidharthBansal** [comment]
The first step is migration. 
1) What will I name the field? @jywarren is password_checker ok?
2) What is the difference between ruser and user in the schema?
3) Do I need to migrate user or ruser?

**Comment by SidharthBansal** [comment]
@jywarren can please tell me what is the difference between the ruser and user? Which one do I need to migrate. The schema is as follows
![image](https://user-images.githubusercontent.com/20972099/42718090-8912b3e4-8723-11e8-8cc4-1e9b9264c701.png)

![image](https://user-images.githubusercontent.com/20972099/42718096-986293c8-8723-11e8-9d54-93e2a899ac3e.png)
I will be naming the new field as password checker.

**Comment by SidharthBansal** [comment]
I think I need to migrate ruser. But I am not sure.

**Comment by jywarren** [comment]
That's right, we're trying to get rid of `users` -- `rusers` = User, and `users` = DrupalUser. Thanks!

**Comment by jywarren** [comment]
no problem!
