### ISSUE TITLE
Change Color Of Github Icons

### ISSUE THREAD

**Issue by dewanhimanshu** [publiclab/plots2#3034]
![screenshot from 2018-07-10 23-26-34](https://user-images.githubusercontent.com/32437794/42529898-51de1824-849d-11e8-8a88-90138a5bfde0.png)
the github icon is green every where . We should change its color to black son that it is more relevant.
@jywarren @SidharthBansal

**Comment by SidharthBansal** [comment]
Four pages are to be considered
Login page
Header
Sign up page
Edit profile page
@jywarren what will you suggest?
I prefer black

**Comment by jywarren** [comment]
black sounds nice! Could we also factor these into a template partial so
there's less repetition?

**Comment by SidharthBansal** [comment]
@dewanhimanshu take care that all the four pages looks great after you have set them in a partial.
At some places we place the icons in the center while at other places we keep it on the left.

**Comment by SidharthBansal** [comment]
Completed.
