### ISSUE TITLE
Lamp

### ISSUE THREAD

**Issue by Guillaume123** [publiclab/plots2#304]
![image](https://cloud.githubusercontent.com/assets/11196831/9192910/27c1b204-4007-11e5-95f0-1b23f9f367dc.png)

I get the above error message when I try to open http://publiclab.org/notes/vacdaica123/08-10-2015/lamp

Guillaume123

**Comment by jywarren** [comment]
Was this resolved then?

**Comment by Guillaume123** [comment]
Hi Jeff,

The error is still there. See attachment. Why one capture is a different
size to the other one, I have no idea.

**Comment by Guillaume123** [comment]
Hi Jeff,

The error is still there. See attachment. Why one capture is a different
size to the other one, I have no idea.

**Comment by jywarren** [comment]
Hi, I can't find the note at all - was it deleted?

**Comment by Guillaume123** [comment]
Hi Jeff,

I have attached a clip of the original email in which the link:

http://publiclab.org/notes/vacdaica123/08-10-2015/lamp

appears.

**Comment by jywarren** [comment]
Hi, Gwill - I believe the author deleted their post after the issue was resolved, which is why you now see an error at that address.

**Comment by Guillaume123** [comment]
PublicLab,

This email is to get the [PublicLab] name into my Contacts.

Gwill
