### ISSUE TITLE
SMTP testing system - planning

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3040]
Logs show this error when I try to approve a new post:

```
[372b6dd2-719b-4dd1-8d3a-7146e2196e67] Sent mail to xxxxx@xxxxx.com (29.0ms)
[372b6dd2-719b-4dd1-8d3a-7146e2196e67] Completed 500 Internal Server Error in 743ms (ActiveRecord: 12.0ms)
[372b6dd2-719b-4dd1-8d3a-7146e2196e67]   
[372b6dd2-719b-4dd1-8d3a-7146e2196e67] Net::SMTPFatalError (550 relay not permitted
```

**Comment by icarito** [comment]
Hi,
The issue is we had hardcoded / whitelisted the app container IP address in our mail gateway configuration. But Docker may change this IP address. The solution was to relay for the IP address range of docker containers. This should have fixed this issue!

**Comment by jywarren** [comment]
Is this something we can develop monitoring for? i worry it failed silently...

**Comment by icarito** [comment]
It would be tricky to monitor this. Not sure how to go about it. If we could setup a route in the application that tests this functionality we can setup an HTTP monitor for it by using our current monitoring solution.
This test would have to be coded as a rails app route.

**Comment by jywarren** [comment]
Would the application trigger an email sent to a known address? Could we
monitor an inbox, maybe?

**Comment by icarito** [comment]
We don't need to send an email. I've just manually [tested the SMTP protocol](https://community.spiceworks.com/how_to/11-test-email-flow-using-smtp-commands) and found that in case the relay isn't responding, it will fail immediately upon giving the sender and recipient:
![image](https://user-images.githubusercontent.com/199755/42858455-54124f3a-8a14-11e8-846c-54f12d659cc4.png) so it could be tested continually every few minutes or so (via sidekiq I guess) *without* actually emailing.

The tricky thing is, what should the system do in case it finds it is unable to send mail? Tweet? Notify `#publiclab`? We could start with a `/api/status` route that tests the email relay and gives a 500 error if it fails. Then we could monitor this route with the Rackspace monitoring tools, which emit alerts if it fails.

**Comment by jywarren** [comment]
I like this last way - do you think you can open an issue for that?
Maybe @ViditChitkara could help code that up?

**Comment by jywarren** [comment]
i think in ruby you can execute commandline things by wrapping a command in ` characters, OR

by running `system('ls')`

**Comment by icarito** [comment]
Hi,
I just wrote a naive test in Ruby for the first time:
```
require 'socket'

s = TCPSocket.new 'localhost', 25

while line = s.gets # Read lines from socket
    puts line
    if line.include? '220'
        s.print "MAIL FROM: <icarito@publiclab.org>\n"
    end
    if line.include? '250 OK'
        s.print "RCPT TO: <icarito@publiclab.org>\n"
    end
    if line.include? '250 Accepted'
        puts 'PASS'
        s.close_write
    elsif line.include? '550'
        puts 'FAIL'
        s.close_write
    end
end

s.close
```
The idea would be to put this or something close to it into a rails route.
Then we can use our current (Rackspace) monitoring tools to check that the route always returns PASS.
I just need to figure out where to put this!
:-D

**Comment by jywarren** [comment]
If it's executable, we could put it in a public folder and bypass Rails,
just running it in Ruby... would that help at all?

**Comment by jywarren** [comment]
Done!
