### ISSUE TITLE
clean up old question commenting javascript and templates

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3049]
Now that we have a consistent interface for commenting (thanks to @ViditChitkara in #2896), we should tidy up and clean out the old files that are no longer used. Some are mentioned here;

https://github.com/publiclab/plots2/search?q=previous+comments&unscoped_q=previous+comments

I also don't believe we use this any more? 

https://github.com/publiclab/plots2/blob/master/app/views/questions/_comment.html.erb

@ViditChitkara - interested in a little clean up? It's quite satisfying!!! 😄

**Comment by jywarren** [comment]
Ah, actually there is still one place where old-style commenting persists! 

![screen shot 2018-07-11 at 10 57 20 am](https://user-images.githubusercontent.com/24359/42580755-3f041f8a-84f9-11e8-82b2-0747a8c1298e.png)

And actually these were collapsed; if someone would like to try:

1. removing the 'default collapsed comments' for answers code and
2. integrating the standard comment form at [this template](https://github.com/publiclab/plots2/blob/master/app/views/notes/_comment.html.erb) into ANSWER comments as well, that would be excellent!

Thanks, and I'm happy to help with this!

**Comment by jywarren** [comment]
Here's the collapsed comment area we'd like to make always-uncollapsed:

![screen shot 2018-07-11 at 11 02 14 am](https://user-images.githubusercontent.com/24359/42581068-ee38d5c2-84f9-11e8-89ac-0aa0f593374d.png)

**Comment by ViditChitkara** [comment]
Cool! I'll be happy doing this!

**Comment by jywarren** [comment]
oh great, thanks so much.
