### ISSUE TITLE
Blog template and design improvements

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#305]
Looking for some tips or functions in helping people publish to the blog with consistent layout. (ie picture/text placement)

http://publiclab.org/blog

**Comment by jywarren** [comment]
Do you mean a style guide of some sort? Or maybe a template?

**Comment by steviepubliclab** [comment]
Maybe a template.

**Comment by jywarren** [comment]
Would you like input on the design itself, or just on how it might be
implemented? I think very broadly speaking, paragraphs with single images
between them is a good pattern. Maybe 5 paragraphs? This post has good
overall text/image rhythm:
http://publiclab.org/notes/nicholas/07-08-2015/measuring-particulate-matter-with-the-girl-scouts

**Comment by steviepubliclab** [comment]
I think something like a outline for people to use in terms of text and
photo placement could be helpful.

**Comment by jywarren** [comment]
Maybe we could post an example layout at
http://publiclab.org/wiki/blog#Authoring

**Comment by steviepubliclab** [comment]
with a template?

**Comment by jywarren** [comment]
Yep, did you have some headings you'd like to include? We can make the
template include hints like `<!-- consider inserting a nice photo here -->`
which won't show up when it's published.

**Comment by steviepubliclab** [comment]
That's a good idea. Is there also something that can help center the photos
people upload as well so it looks consistent with the blog layout?

What do you think of this draft template:


###Where my story starts:

Text here


_Insert photo caption here_

Text here

###Why this is important to me:

Text here


_Insert photo caption here_

Text here

###This has made me reflect on:

Text here


_Insert photo caption here_

Text here

**Comment by jywarren** [comment]
I think that template can work, but maybe we could put hidden prompts for
content as well as images, and have the section headings be something
shorter -- since many folks may not write in their own titles, so we should
be prepared for the ones we supply to actually be published.

We could force centering on images... i'm a bit worried it'll take some
trickery and not work 100% of the time, but can give it a try.

**Comment by jywarren** [comment]
I **think** that this will work, but it won't in all circumstances:

````css

.blog > p > a {
  text-align: center;
  width: 100%;
  display: block;
}
````

**Comment by steviepubliclab** [comment]
Does that plug into the template somewhere? And do you have other heading
suggestions?

**Comment by jywarren** [comment]
The best way to do it will be to set this in the site's code (stylesheet). For heading suggestions:

````
###The beginning OR The story begins

###What we did

###Why it matters

###How you can help


````

Also, here's an improved stylesheet with help from @zenhack (on an unrelated project):

````css
section > p img {
  display: block;
  margin: 0 auto
} 
````

**Comment by jywarren** [comment]
Did these headings look good to you?

**Comment by steviepubliclab** [comment]
Would this just be another template or would it help with the look of the
posts?

**Comment by jywarren** [comment]
This issue covers both, but we can start with the template. I think we can
pretty easily add both!

**Comment by jywarren** [comment]
image centering fixed in b5f759690d69ce8cf54bcaa7576d1b0e6f6f9cd0 and bcf5383f2ddd63895233e265a89ce5629287711f

**Comment by steviepubliclab** [comment]
Thanks Jeff! Looks much better with them all centered.
-Stevie

**Comment by sudheesh001** [comment]
Does this need more work or can this be closed ? It looks the fixes are already in place in b5f7596 and bcf5383

**Comment by jywarren** [comment]
I am leaving this open a bit longer as I think we need a few more
improvements, mostly design work. But one thing we badly need is pagination
-- there's none right now -- so if you'd like to tackle that, it'd be much
appreciated. You can borrow pagination view code here:


https://github.com/publiclab/plots2/blob/master/app/views/notes/_notes.html.erb#L50


And in the controller, it just needs: `.paginate(page: params[:page])` as
is shown in several other controller actions. The blog code is in the Tag
controller.

**Comment by jywarren** [comment]
At some point, I'm thinking of adapting some of the styles from the new dashboard at https://publiclab.org/dashboard -- it'd be pretty fast and easy. Stevie, are you interested in seeing research notes in a sidebar or something? Or a link from the blog to all research notes -- thinking that folks might start reading the blog, and be drawn into the rest of the site?

**Comment by steviepubliclab** [comment]
Hi there,
I don't want to crowd the blog, but a link to research notes or the
dashboard might be nice.
-Stevie

**Comment by jywarren** [comment]
Closing this issue and opening a new one for the template! #988

**Comment by jywarren** [comment]
And I'll make a new one at #989 for the "link to research notes or the dashboard".
