### ISSUE TITLE
Link to notes tagged not working (autoposted via PublicLab.org)

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3053]
(This issue was auto-generated from https://ift.tt/2B8W2Ma -- please help to flesh it out and explore the issue, and respond to the original author!) by https://ift.tt/2JdrcWL<br>
<br>
Read more and ask the original author for details at: https://ift.tt/2L5dWIy<br>
<br>
****<br>
<br>
<h3>Please describe the problem (or idea)</h3>
<blockquote>
<p>If you click the tag 'community-microscope' on this page, and then '6 notes' the page does not exist</p>
<p><a href="https://publiclab.org/notes/jiteovien/07-09-2018/integrating-user-instructions-into-the-community-microscope-build-materials">https://publiclab.org/notes/jiteovien/07-09-2018/integrating-user-instructions-into-the-community-microscope-build-materials</a></p>
</blockquote>
<h3>Please show us where to look</h3>
<p><a href="https://publiclab.org/tag/community-microscope">https://publiclab.org/tag/community-microscope</a></p>
<h3>What's your <a href="http://PublicLab.org">PublicLab.org</a> username?</h3>
<blockquote>
<p>This can help us diagnose the issue: asnow</p>
</blockquote>
<h3>Browser, version, and operating system</h3>
<blockquote>
<p>Many bugs are related to these -- please help us track it down and reproduce what you're seeing!</p>
</blockquote>
<hr>
<h2>Thank you!</h2>
<p>Your help makes Public Lab better! We <em>deeply</em> appreciate your helping refine and improve this site.</p>
<p>To learn how to write really great issues, which increases the chances they'll be resolved, see:</p>
<p><a href="https://publiclab.org/wiki/developers#Contributing+for+non-coders">https://publiclab.org/wiki/developers#Contributing+for+non-coders</a></p>
<br>
<br>
****<br>
<br>
(via **Research tagged 'question:website'** at https://ift.tt/2B9Mfpe at July 11, 2018 at 12:51PM)

**Comment by imacubsfan23** [comment]
What's the expected functionality of https://publiclab.org/tag/community-microscope?

**Comment by jywarren** [comment]
Thanks, it's supposed to be like: https://publiclab.org/tag/balloon-mapping

I think we need to pull the logs to see what's happening!

**Comment by jywarren** [comment]
That's weird - it's a 404 not found error. But https://publiclab.org/tag/balloon-mapping works... how can that be?

**Comment by ebarry** [comment]
Confirming that this bug is still happening. :)

**Comment by jywarren** [comment]
All working now!
