### ISSUE TITLE
TESTING.md  is quite outdated

### ISSUE THREAD

**Issue by Souravirus** [publiclab/plots2#3055]
https://github.com/publiclab/plots2/blob/master/doc/TESTING.md is quite oudated and many of the commands might not be working after the change to rails 5 upgrade. So, we should change it.

**Comment by jywarren** [comment]
yes! Awesome!

**Comment by siaw23** [comment]
what specific parts are now deprecated? @souravirus

**Comment by Souravirus** [comment]
First of all `rake test:all` doesn't run all the tests, it only runs the jasmine tests and coverage tests. I don't know if running specific types of test is working or not in rails 5. We have to check that. Also running a single file test and single test has much better commands in rails 5 than to run them with ruby command.

**Comment by siaw23** [comment]
Ah I remember these now. Can you please update those parts of the README so we can have this issue closed? @Souravirus

**Comment by Souravirus** [comment]
Yeah I will surely do these tomorrow as I am travelling back to my college today. Thanks!!

**Comment by Souravirus** [comment]
Hi @jywarren @siaw23 I have posted a first-timers-issue related to this. Please see this https://github.com/publiclab/plots2/issues/3112

**Comment by jywarren** [comment]
awesome!
