### ISSUE TITLE
Rails error being shown

### ISSUE THREAD

**Issue by Souravirus** [publiclab/plots2#3059]
As is reported #3058, some of  the errors are sometimes being shown in travis and also in the local machine. Please see to this @publiclab/soc @publiclab/reviewers 
Here are the errors:
`ERROR["test_create_a_user_with_omniauth_if_email_prefix_does_not_exist_in_db", Minitest::Result, 57.168834722999975]
 test_create_a_user_with_omniauth_if_email_prefix_does_not_exist_in_db#Minitest::Result (57.17s)
NoMethodError:         NoMethodError: undefined method 'using_open_id?' for nil:NilClass
            lib/authlogic_openid/authlogic_openid/session.rb:78:in  'authenticating_with_openid?'
            app/models/user.rb:441:in 'block in create_with_omniauth'
            app/models/user.rb:435:in 'create_with_omniauth'
            test/unit/user_test.rb:207:in 'block in <class:UserTest>'`

`ERROR["test_user_creation", Minitest::Result, 58.106504889000064]
 test_user_creation#Minitest::Result (58.11s)
NoMethodError:         NoMethodError: undefined method 'using_open_id?' for nil:NilClass
            lib/authlogic_openid/authlogic_openid/session.rb:78 'authenticating_with_openid?'
            lib/authlogic_openid/authlogic_openid/acts_as_authentic.rb:74:in 'save'
            test/unit/user_test.rb:10:in 'block in <class:UserTest>'`

**Comment by SidharthBansal** [comment]
Both of these tests are saying that 
`` NoMethodError: NoMethodError: undefined method 'using_open_id?' for nil:NilClass`` 
that meaning somewhere using_open_id? is used. Neither of these tests uses such method
```
  test 'user creation' do
    user = User.new(username: 'chris',
                    password: 'godzillas',
                    password_confirmation: 'godzillas',
                    email: 'test@publiclab.org')

    assert user.save({})

    assert user.first_time_poster
    assert_not_nil user.id
    assert_not_nil user.drupal_user
    assert_not_nil user.uid
    assert_not_nil user.email
    assert_not_nil user.bio
    assert_not_nil user.token
    assert_not_nil user.path
    assert_not_nil user.title
  end
```
and 
```

  test 'create a user with omniauth if email prefix does not exist in db' do
    auth = {"uid" => "98746858591", "info" => { "email" => "bansal.sidharth2990@gmail.com"}}
    sidharth = User.create_with_omniauth(auth)
    assert_not_nil sidharth
    assert_equal sidharth.email, "bansal.sidharth2990@gmail.com"
    #as username "bansal_sidharth2990" does not exist in the db, user with username = "bansal_sidharth2990" will be created
    assert_equal sidharth.username, "bansal_sidharth2990"
  end```

**Comment by SidharthBansal** [comment]
@Souravirus have you updated the Authlogic gem?

**Comment by SidharthBansal** [comment]
Yeah I think the error is trying to say that the method to create a user is changed.

**Comment by Souravirus** [comment]
ok!!

**Comment by Souravirus** [comment]
The error has disappeared but still I have given a PR regarding the upgrading of the auth-logic gem

**Comment by SidharthBansal** [comment]
Can you please review #3072. I made some changes because of this issue.

**Comment by SidharthBansal** [comment]
Is code OK with newer rails version?

**Comment by Souravirus** [comment]
ok let me see

**Comment by Souravirus** [comment]
Yeah it looks good to me

**Comment by siaw23** [comment]
is this issue solved? @souravirus

**Comment by Souravirus** [comment]
Yeah I have submitted a PR #3074 regarding upgradating of the authlogic gem. But for now I can't see the error.

**Comment by Souravirus** [comment]
This error still persists and I have seen it in #2659.

**Comment by jywarren** [comment]
Saw this more recently -- intermittently! 

This is an example: https://travis-ci.org/publiclab/plots2/builds/451172024 although i've restarted it and perhaps it will pass now...

**Comment by jywarren** [comment]
Going to close now! Thanks!
