### ISSUE TITLE
Error on edit page

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#3060]
### Please describe the problem (or idea)
![image](https://user-images.githubusercontent.com/20972099/42659592-5e829816-8646-11e8-952d-b33fc4b8510e.png)

**Comment by SidharthBansal** [comment]
@dewanhimanshu  can you please address this one. It happened due to some error in #3050

**Comment by SidharthBansal** [comment]
I am trying to figure this one

**Comment by dewanhimanshu** [comment]
@SidharthBansal  will solve this issue

**Comment by SidharthBansal** [comment]
Thanks. You need to put the icons in form

**Comment by dewanhimanshu** [comment]
fixed error on edit page #3060 #3067
