### ISSUE TITLE
Improve digest email template

### ISSUE THREAD

**Issue by ViditChitkara** [publiclab/plots2#3061]
The digest emails have some inconsistent links and broken css.

**Comment by ViditChitkara** [comment]
On it!!!

**Comment by ViditChitkara** [comment]
would be soon posting an email template here.

**Comment by ViditChitkara** [comment]
Hi @jywarren , now that the digest mailer is working, can we use the following:-
![gsoc-2](https://user-images.githubusercontent.com/22616017/42891509-2dbbf746-8acd-11e8-8987-cc7e26df717b.png)

**Comment by ViditChitkara** [comment]
![gsoc-3](https://user-images.githubusercontent.com/22616017/42891513-2fa394ec-8acd-11e8-9036-4af3b7a24774.png)
Here is the remaining part of the mail above. This could handle a note with or without an image. This is much similar to quora digest.

**Comment by jywarren** [comment]
this is really great. Let's do it!

**Comment by ViditChitkara** [comment]
Cool!!
