### ISSUE TITLE
Multiple tags to show up in one place

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#3064]
I was wondering if there was a way to compile multiple tag results into one page. For example, I was interested in compiling the questions related to topics that environmental lawyers might be able to help with on Public Lab, but there are different tags people have used that could go under this for example:

https://publiclab.org/tag/question:regulations
https://publiclab.org/tag/question:evidence
https://publiclab.org/tag/question:legal
https://publiclab.org/tag/question:permits

Anyone have ideas on this?

**Comment by Gauravano** [comment]
Hi @steviepubliclab, no we don't have any such method for this task. But, we can add such functionality if required. What do you think? Thanks!

**Comment by steviepubliclab** [comment]
Seems like some of the word cloud conversation we were having on Open Call yesterday could help address some of this, depending on how it played out.

**Comment by jywarren** [comment]
Ah, ok - so what about moving forward on the "related tags" part of that. The first step might be to try to **show related tags on each `/tag/_____` page, based on what other tags are most often used alongside. ** @steviepubliclab does that make sense?

This could, in code, be something like:

A `tag.related` method in https://github.com/publiclab/plots2/blob/master/app/models/tag.rb :

* scan through and collect all `node_tag` records 
* collect the `nid` values
* collect all `node_tag` records which contain these `nid`s
* sort (using group by count) `tid`s according to how often they occur in this set of `node_tag`s
* return the top 5

Then, on our tag page template:

* fetch the `Tag` `name` values of the returned related tags
* display these under the main tag "Related topics"

However, if we find this is too slow to do for every page load, we could cache the result weekly... or start to restrict it to only the past year, or limit to a maximum of 100 or 500 `node_tag`s

**Comment by jywarren** [comment]
Also connecting this much more narrow concept for tag relatedness back to optimization discussions in the much larger and more ambitious discussion in https://github.com/publiclab/plots2/issues/1502#issuecomment-360573133 -- which is about recalculating ALL tag relationships at once, potentially every week. This narrower issue is just for calculating related tags for ONE specific tag at a time, so I think we can write the query to run even hourly...

**Comment by jywarren** [comment]
Hi @steviepubliclab, did you want to go in one of the above directions? We have a pretty good "related tags" system now, highly visible, with a mini tag cloud on search and tag pages. We could bump up the remaining part:

> Hi, would you need an auto-generated page so you could enter a URL like:

> https://publiclab.org/tag/question:regulations+question:evidence+question:legal+question:permits
?

> Or could it  be a wiki page where you list multiple tags in a custom inline
grid, like:

> [notes:
question:regulations,question:evidence,question:legal,question:permits]

**Comment by steviepubliclab** [comment]
Hi,
Thanks for working on this I had forgotten about it, but it seems weirdly similar to the question I was asking as well about tagging related things this morning. I might need to talk about this in person rather than online to better understand the limitations and options. Can we add this to a topic on Open Call?

**Comment by jywarren** [comment]
For sure, thanks!

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/issues/2535  may be this issue!? If so, we can close this?

**Comment by jywarren** [comment]
Reworking this into a plan to do some auto-tagging! https://github.com/publiclab/plots2/issues/6367
