### ISSUE TITLE
Show most recently updated people on Search API

### ISSUE THREAD

**Issue by stefannibrasil** [publiclab/plots2#3069]
Part of #2755

Change the sorting of the results in the API to most recently updated people as discussed in #2925

**Comment by milaaraujo** [comment]
@jywarren's comment: 
>[...]change the sorting of the results in the API to most recently updated people... so [changing this line](https://github.com/publiclab/plots2/blob/master/app/api/srch/search.rb#L45) from [this](https://github.com/publiclab/plots2/blob/73a16d10a7e1bc03c8921f593a98a639687d91a2/app/services/search_service.rb#L236) instead of [this](https://github.com/publiclab/plots2/blob/73a16d10a7e1bc03c8921f593a98a639687d91a2/app/services/search_service.rb#L122) --- a good break-out issue!
