### ISSUE TITLE
update front page link to /wiki/nonprofit-initiatives instead of /initiatives

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#307]
the front page of publiclab.org under II Collaboration links to http://publiclab.org/wiki/initiatives but it should link to http://publiclab.org/wiki/nonprofit-initiatives. Thanks! After this, i might delete the /initiatives page.

**Comment by jywarren** [comment]
Hi, Liz - is this something you could try to fix? If you fork this repository (button upper right) then find the file in your own fork, it'll be on a page (this won't exist until you fork) at the URL:

https://github.com/ebarry/plots2/blob/master/app/views/layouts/_header.html.erb

Which you could navigate to through Github's file browsing interface as well. There's a pencil button in the upper right:

![screenshot 2015-08-24 at 12 35 42 pm](https://cloud.githubusercontent.com/assets/24359/9445953/dcb535fa-4a5c-11e5-8f24-7937010bac53.png)

...where you can find the menu item in the HTML, change it, then below, create a pull request with your new change (give it a name like 'ebarry-header-tweaks'):

![screenshot 2015-08-24 at 12 37 53 pm](https://cloud.githubusercontent.com/assets/24359/9445973/04023928-4a5d-11e5-972e-b0cf7d4850bc.png)

**Comment by ebarry** [comment]
Yes, I will try to do this and report back. Thanks!

**Comment by ebarry** [comment]
Hey Jeff, 
I forked the repository. See https://github.com/ebarry/plots2/tree/master/app/views/layouts where i have only two files in that folder, neither of which is *_header.html.erb*: 
![screen shot 2015-11-14 at 5 13 39 pm](https://cloud.githubusercontent.com/assets/161439/11166082/167867c2-8af3-11e5-856f-d83f38d98e3d.png)

One of the two files is https://github.com/ebarry/plots2/blob/master/app/views/layouts/application.html.erb. I saw that there was footer information in there that needed changing, so i edited the file to change a link in the footer and submitted it as a pull request according to these instructions. 

I see that the main repo has four files in that folder: 
![screen shot 2015-11-14 at 5 13 02 pm](https://cloud.githubusercontent.com/assets/161439/11166083/2241ae88-8af3-11e5-8f4b-26d4ec1b1cd9.png)

...where now i see an actual footer file which is maybe where i should have made the change? https://github.com/publiclab/plots2/blob/master/app/views/layouts/_footer.html.erb
...also, i can't find the actual front page text on https://github.com/publiclab/plots2/blob/master/app/views/layouts/_header.html.erb that you screenshotted above. 

Why did my fork only get 2 of the 4 files in this folder?

**Comment by jywarren** [comment]
Hi, Liz - your fork is very old -- new modifications have been made to the codebase 823 times since your fork's latest version. I've created a pull request that will bring your fork up to date: https://github.com/ebarry/plots2/pull/2

If you accept it, you'll get the latest version.

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/blob/master/app/views/home/home.html.erb

**Comment by ananyo2012** [comment]
This can be closed with #345 being merged
