### ISSUE TITLE
Community Check-in #9 Summer Of Code Week 10 

### ISSUE THREAD

**Issue by Gauravano** [publiclab/plots2#3078]
Hi everybody :smiley: !

If you're new here, welcome, and please try some of our [first-timers-only issues](https://publiclab.github.io/community-toolbox/#r=all). This is a checklist for publiclab/soc.

@stefannibrasil @milaaraujo @MargaretAN9 @Gauravano @ViditChitkara @tech4GT @mridulnagpal @namangupta01 @sagarpreet-chadha @Souravirus @jywarren @MayankKashyap @siaw23 @ryzokuken @ccpandhare @icarito @abTest-123 @steviepubliclab @ebarry @publiclab/soc @publiclab/reviewers

**Hi guys! How was your weekend? And what is the plan for this week?**
If you have not planned yet. Just leave a Hi! so that we could know that you are in sync with us :arrows_clockwise: 

**Here's my progress report**
Last week, I completed the following parts:-
1.Welcome Email with OAuth and Fallback email 
2. Spam comment moderation on /spam (ready to merge at https://github.com/publiclab/plots2/pull/3065) 

And, this week I will complete Configurable email settings part in which I will add remaining settings (https://github.com/publiclab/plots2/pull/2985).  

As always, if you're waiting for a review, or if you're stuck, please request help
here OR leave a comment with @publiclab/soc and @publiclab/reviewers for
some input.

Have a nice week :tada: !
Thank you !

**Comment by sagarpreet-chadha** [comment]
Hi @all !

I have written a new blog on publiclab.org --- https://publiclab.org/notes/sagarpreet/07-16-2018/leaflet-environmental-layer-library-part-2 🎈 
Do take a look at the new layers implemented !

###### Currently working on updating the markers in mapknitter layer !

**Comment by SidharthBansal** [comment]
Hi @publiclab/soc,

I am nowadays working on the tests for the usertags available on the profile page. I am trying to debug the errors which we are facing in OAuth. Also, creating ftos and helping them to get involved in bigger project.
Once I will complete the usertags prs. I will do the password checker and notification work so that we will get a much secure version of OAuth 2.0
Thanks

**Comment by stefannibrasil** [comment]
Hi, everyone!
still working on the same thing from last week, but we are making progress. We have a PR for a Search API refactor proposal #3045 and will open a new one for Typeahead.
We decided to first remove the duplications from both services and later work on improving the queries and remove the hard to read sections. This has been a great way to learn more the API so far!

**Comment by stefannibrasil** [comment]
@sagarpreet-chadha great work, btw! I couldn't access the link to see it working, though! :tada:

**Comment by SidharthBansal** [comment]
I want that PL will apply as a separate organisation as we do in Rails Soc And Google Soc rather than under fossasia.
What is your opinion?

**Comment by Gauravano** [comment]
keeping in view expansion of our PL team, we should participate as a separate organization :grinning:.

**Comment by namangupta01** [comment]
This is going to be awesome if PL participate in Google Code-In

**Comment by tech4GT** [comment]
Awesome!!! Let's apply separately!!😃

**Comment by jywarren** [comment]
Hi, all! I've just published to production about an hour ago! https://github.com/publiclab/plots2/pulse/weekly

**Comment by jywarren** [comment]
Where are the requirements to sign up for Code-in?

**Comment by jywarren** [comment]
also, how many of you have participated in Code-In before?

**Comment by jywarren** [comment]
... i guess everybody went to sleep 😂

**Comment by SidharthBansal** [comment]
The form for 2018 will be out after GSoC ends. Just after that.
I have not participated in Code in before.
Working at Public Lab is my first awesome intern.

**Comment by SidharthBansal** [comment]
Yeah was preparing for sleep, here it is midnight.

**Comment by Souravirus** [comment]
Hi everyone, 
Sorry being late for this check-in. Last week I have worked with changing the jasmine tests to teaspoon-mocha. The changing of tests is actually done but I am currently working with the reporting the test reports to the PR somehow. I was basically trying to report through Dangerbot but it looks like junit in Dangerfile is not detecting any failures of the xml file generated by teaspoon mocha. I will work now on finding some alternate method to make this work. Any help would be appreciated in #2997. 
Also, I will be working on modifying some commands in TESTING.md. Some commands are deprecated after the rails 5 upgrade.

**Comment by jywarren** [comment]
Hi, Sourav - if you'd like to merge the basic fix and think about the
report-back of tests in a separate PR, that's totally OK!

Thanks for checking in!

Who'd like to do next week's check-in? Thanks all for a great week!

**Comment by Souravirus** [comment]
yeah I was also thinking of it lets merge that without the changes in Dangerfile and I will try the report back fix in other PR

**Comment by stefannibrasil** [comment]
I can do the check-in next week.

**Comment by SidharthBansal** [comment]
Great

**Comment by jywarren** [comment]
Awesome, thanks!!!

**Comment by stefannibrasil** [comment]
Moved to #3133

**Comment by Gauravano** [comment]
Closing this one then. Thanks!
