### ISSUE TITLE
filter for users who have profile bio content

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#308]
There should probably be a more comprehensive brainstorm on how to make http://publiclab.org/people something useful for community development. But for now, can admins get a datadump for all usernames where anyone has filled out anything in their profile?

just two columns, username, and text from profile. no images.

**Comment by jywarren** [comment]
Thanks -- urgency?

**Comment by ebarry** [comment]
not urgent.

--

txt only: +1 336-269-1539
@lizbarry <http://twitter.com/lizbarry>

**Comment by btbonval** [comment]
This will be fantastic for moderators to find spammers we haven't gotten to yet!

I bet there are thousands of such users with spam profiles that aren't yet banned.

**Comment by ebarry** [comment]
If this is to be built into the site as a filter for users who have profile bio content, i will also need to be able to search within profile content to be possible in the site. That's what i was planning to do with the datadump.

**Comment by ebarry** [comment]
Gently bumping this up. Stevie and I are working on geography this fall (Q4) and as part of that we will be doing targeted geographic outreach to potential organizers. Having this filter will enable us to search for people who mention geographies in their bio, letting us make progress on this in the lagtime before RichProfiles happens.

**Comment by btbonval** [comment]
What format do you want this in? CSV will probably not work because profiles can have commas (there are ways around this).

You just want username and profile. Would it suffice to do something like this:
```
# username

profileprofile

profile

profile

# username

profile profile profile

# username

profile
```

**Comment by ebarry** [comment]
Could you get username, if they've ever posted or commented (or not), and
the full text of what they typed in as their bio?

**Comment by btbonval** [comment]
Oh, it looks like I don't have access to the system anymore. I thought I did.

**Comment by btbonval** [comment]
woops I have access. Some of my connection configurations are out of date.

**Comment by btbonval** [comment]
I think this query should work. I started running it but it appears to take time. Works fine if I restrict it to one or two users specifically.
``` SQL
SELECT users.name, count(node.nid) AS notes, count(comments.cid) AS comments, profile_values.value AS profile
FROM users
INNER JOIN profile_values ON (users.uid = profile_values.uid AND profile_values.fid = 1 AND length(profile_values.value) > 0)
LEFT OUTER JOIN node ON (users.uid = node.uid)
LEFT OUTER JOIN comments ON (users.uid = comments.uid);
```

That'll get the first profile though, but not later updates. I can't seem to figure out how to get MySQL to get the max fid per user. `SELECT uid, max(fid) FROM profile_values GROUP BY uid` ignores `GROUP BY` and simply returns the same `max(fid)` for every row.

**Comment by btbonval** [comment]
neat trick using self outer join to find largest value (newest profile_value in this case)
```
SELECT pv1.value
FROM profile_values AS pv1
LEFT OUTER JOIN profile_values AS pv2
  ON (pv1.uid = pv2.uid AND pv1.fid < pv2.fid) WHERE pv2.fid IS NULL
ORDER BY pv1.uid;
```

I forgot to make sure user is not banned, and I screwed up the counts for comments and notes. This looks better, and it seemingly runs faster too.
```
SELECT users.name, node.notes, comments.comments, profile_values.value AS profile
FROM users
INNER JOIN (
  SELECT pv1.uid, pv1.value
  FROM profile_values AS pv1
  LEFT OUTER JOIN profile_values AS pv2
    ON (pv1.uid = pv2.uid AND pv1.fid < pv2.fid)
  WHERE pv2.fid IS NULL AND length(pv1.value) > 0
) AS profile_values ON (users.uid = profile_values.uid AND users.status > 0)
LEFT OUTER JOIN (
  SELECT uid, count(nid) AS notes
  FROM node
  GROUP BY uid
) AS node ON (users.uid = node.uid)
LEFT OUTER JOIN (
  SELECT uid, count(cid) AS comments
  FROM comments
  GROUP BY uid
) AS comments ON (users.uid = comments.uid);
```

**Comment by btbonval** [comment]
@ebarry okay I ran this and exported. It was too big to share via email so I uploaded to drive and shared on that.

**Comment by btbonval** [comment]
To reiterate my comment earlier:

>  btbonval commented on Aug 25
> This will be fantastic for moderators to find spammers we haven't gotten to yet!

This turns out to be very true.

**Comment by ebarry** [comment]
Brian, thank you. This is a treasure trove for place-based organizing.

--

+1 336-269-1539
@lizbarry <http://twitter.com/lizbarry>

**Comment by btbonval** [comment]
do the thing again, but with more thing!

1. newer. not the old one, but a new one. like from now. and not the before times.
2. include user email addresses
3. possibly include signup date
4. (possibly include last login. not asked for, but heck)
5. workaround the spaces.

**Comment by btbonval** [comment]
Adds new fields requested but no workarounds for spacing issues.
```
SELECT users.name, users.mail AS email, users.created AS signup_date, users.access AS last_browse_date, node.notes, comments.comments, profile_values.value AS profile
FROM users
INNER JOIN (
  SELECT pv1.uid, pv1.value
  FROM profile_values AS pv1
  LEFT OUTER JOIN profile_values AS pv2
    ON (pv1.uid = pv2.uid AND pv1.fid < pv2.fid)
  WHERE pv2.fid IS NULL AND length(pv1.value) > 0
) AS profile_values ON (users.uid = profile_values.uid AND users.status > 0)
LEFT OUTER JOIN (
  SELECT uid, count(nid) AS notes
  FROM node
  GROUP BY uid
) AS node ON (users.uid = node.uid)
LEFT OUTER JOIN (
  SELECT uid, count(cid) AS comments
  FROM comments
  GROUP BY uid
) AS comments ON (users.uid = comments.uid);
```

**Comment by btbonval** [comment]
It looks like dates are stored in time since epoch, which is not very useful. In the profie, line feeds and carriage returns need to be replaced with spaces and commas should be replaced with semi-colons or something. This can probably be done as part of the MySQL query.

**Comment by btbonval** [comment]
I'm going to skip login times after all. looks like those times are not being updated, so it is probably not worth including. #360

I'll keep signup date though.

**Comment by btbonval** [comment]
```
SELECT users.name, users.mail AS email, FROM_UNIXTIME(users.created) AS signup_date, node.notes, comments.comments,
REPLACE(REPLACE(REPLACE(TRIM(profile_values.value), ",", ";"), "\r", " "), "\n", " ") AS profile
FROM users
INNER JOIN (
  SELECT pv1.uid, pv1.value
  FROM profile_values AS pv1
  LEFT OUTER JOIN profile_values AS pv2
    ON (pv1.uid = pv2.uid AND pv1.fid < pv2.fid)
  WHERE pv2.fid IS NULL AND length(pv1.value) > 0
) AS profile_values ON (users.uid = profile_values.uid AND users.status > 0)
LEFT OUTER JOIN (
  SELECT uid, count(nid) AS notes
  FROM node
  GROUP BY uid
) AS node ON (users.uid = node.uid)
LEFT OUTER JOIN (
  SELECT uid, count(cid) AS comments
  FROM comments
  GROUP BY uid
) AS comments ON (users.uid = comments.uid);
```

**Comment by btbonval** [comment]
oh I guess last time I supplied a tab-separated value sheet so the commas shouldn't have been a problem. There might have been rogue tabs in profiles, but tabs in html editors are far less likely than commas as tab usually changes focus rather than entering a character.

Good thing to keep in mind for next time: TSVs work fine, change the replace above comma-to-semicolon conversion to convert tabs into four spaces and then almost the entire sense is maintained.

**Comment by btbonval** [comment]
@ebarry has requested to include wiki edits and comments. I'll have to read the code on how plots2 does this, but I don't think it is something straightforward to do directly in the database.

**Comment by gauravano** [comment]
Hey @ebarry, what goals/issues we can make from here, keeping in view the latest /people page? Thanks!

**Comment by ebarry** [comment]
The essence of this issue is to have profile bio *text* and *tags* show up
in Search results.
If this is happening already (?), then we can just close this issue.

**Comment by ebarry** [comment]
I suppose there is a second part which is that a Stats function can show
how many people have made which types of contributions. It's a community
awareness / eval function, as well as perhaps a support for spam
moderation. Perhaps we could move over to a Stats issue to describe how
that could work.

**Comment by gauravano** [comment]
> The essence of this issue is to have profile bio *text* and *tags* show up
in Search results.
If this is happening already (?), then we can just close this issue.

We currently show user bio only on /profile page but let's think where else we can add bio field. Here's the search result for warren below :point_down: 

![Screenshot from 2019-03-25 23-12-58](https://user-images.githubusercontent.com/20878070/54941803-ba6b8800-4f53-11e9-975c-218a6b4019a3.png)

If we decide on adding another column for bio in the table, that can make the page a little crowded? What do you think about displaying a popup on hovering over the user image or name? Or, any other idea? That popup can also contain the user profile tags.

**Comment by gauravano** [comment]
> I suppose there is a second part which is that a Stats function can show
how many people have made which types of contributions. It's a community
awareness / eval function, as well as perhaps a support for spam
moderation. Perhaps we could move over to a Stats issue to describe how
that could work.

Yes @ebarry, that'll be good for the stats page. Should I append  this part to stats issue (planning)? 

Thanks!

**Comment by ebarry** [comment]
Great plan re: stats planning issue!

For the bio, it's not important that the full text of the bio be printed on
the search results page . The important part is that the searched-for term
yields profiles where the term appears in bio text or even bio link text as
results on the search page. Does this make sense? It's hard to explain
precisely.

**Comment by gauravano** [comment]
Hmm, that's interesting!

Currently, we don't search over profile bio, but yes, it would be awesome to see search related profiles. @jywarren should we make improvement in the current API for this or new API?

Great idea Liz!

**Comment by jywarren** [comment]
Oh actually yes we do search bio content:
https://github.com/publiclab/plots2/blob/master/app/models/user.rb#L360-L362

We don't search profile tags, so that could be broken out into a new issue
and this one closed. For the stats stuff, let's also open a new issue -- we
do list types of contributions by tag already so let's be sure to add
something very specific. Thanks!

**Comment by gauravano** [comment]
> Oh actually yes we do search bio content:
https://github.com/publiclab/plots2/blob/master/app/models/user.rb#L360-L362

:open_mouth:

**Comment by jywarren** [comment]
lol gaurav :-))))))

**Comment by gauravano** [comment]
@jywarren regarding searching user tag. I found this suggestion from GitHub - https://github.com/publiclab/plots2/issues/3506.

**Comment by gauravano** [comment]
I have dropped @ebarry's thought as a comment in Stats planning issue, let take it there  https://github.com/publiclab/plots2/issues/3498#issuecomment-476327849  

And, regarding usertag @jywarren is this - https://github.com/publiclab/plots2/issues/3506 related?

Thanks and closing this one!
