### ISSUE TITLE
upgrade comments to answers

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#3081]
Hi! 
we previously had a feature to upgrade comments to answers on the question/answer system. Seems like we don't have that right now. Can we get it back :)? 

Best,
Stevie!

**Comment by jywarren** [comment]
Yes, i believe we have combined the comment forms in #2896 #2983 -- but as long as we can detect that it is a question node, we can re-insert this button:

https://github.com/publiclab/plots2/blob/40a207b397cbf762c5d7a41d9a60f36672736785/app/views/questions/_comment.html.erb#L43

**Comment by jywarren** [comment]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://publiclab.github.io/community-toolbox/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by Gauravano** [comment]
Hi @chitra591 , we would love to have your help. Thanks!

**Comment by steviepubliclab** [comment]
Hi! any update on this one? 
The answers that keep coming in as "comments" on questions like this one https://publiclab.org/questions/stevie/07-13-2018/what-is-a-good-way-to-track-vehicular-traffic#answer-comment-20272 are making my fingers twitch! ;)

**Comment by gauravano** [comment]
Hi @chitra591 as stevie said, this one is urgent so I am solving this, sorry for the inconvenience. I am sure you'll find more issues and in case you can't, ping here I will help you in finding one. Thanks! 

@steviepubliclab I am on it. Thanks!

**Comment by jywarren** [comment]
Hi @chitra591 - here's one if you're interested! We're getting an error on
this page - would love some help investigating it!
https://github.com/publiclab/plots2/issues/2703

**Comment by gauravano** [comment]
Hi guys,
Button for promoting a comment to answer was at wrong place i.e., the button was appearing at the answer's comment and so if anyone clicks it, then that comment gets deleted. 

https://drive.google.com/file/d/1hDVyMfgyARiKQLrsK1G_ZyWEimCbYKnd/view?usp=sharing

@jywarren this functionality was made for comments on the node and not for comments on the answer, so that's why they were not working with answer's comment. If you want, I can extend that functionality to answer's comment too in the same PR #3195. What do you think? Thanks!

**Comment by jywarren** [comment]
oh gosh, that would be fantastic. Thanks!
