### ISSUE TITLE
Counts on profiles incorrect. 

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#3083]
Hi,
The counts on the number of research notes/questions on profile pages is a bit misleading. I think that's because it's counting the number of times people edit pages as well? Here are some examples:

- https://publiclab.org/profile/cheneyshreve (says 2 research notes/edits, but only one post shows up)
- https://publiclab.org/profile/pojij_85  (says 2 research notes/edits, but only one post shows up)
- https://publiclab.org/profile/amenzel8  (says 2 research notes/edits, but only one post shows up)

I'm wondering if we could differentiate between posts and edits. Maybe it could show up like this: "4 posts and 2 edits". If this is too complicated for the system, could we change the text on the profile pages so it says "posts" instead of "research notes" since posts now include questions and comments?

Thanks!
-Stevie

**Comment by Gauravano** [comment]
Hi @steviepubliclab , we can differentiate between posts and edits. 
So, showing something like `2 research notes and 3 wiki edits` would work? Thanks!

**Comment by steviepubliclab** [comment]
That sounds nice!
