### ISSUE TITLE
Banned user accounts still show as having liked things

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#309]
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted issues](https://github.com/publiclab/plots2/labels/help-wanted). Thanks!

### The problem

We ban spam users by marking their user record and their posted notes with `status: 0`. But users can "like" things using the star button on most content, as in this screenshot:

![screenshot 2016-03-16 at 11 46 30 am](https://cloud.githubusercontent.com/assets/24359/13818579/c56349da-eb6c-11e5-8ada-d4813a71ab76.png)

For an example, see [FlorentTecumsah](http://publiclab.org/profile/FlorentTecumseh), who is banned (so only mods and admins will be able to navigate to their profile page), on http://publiclab.org/wiki/nonprofit-initiatives:

![screenshot 2016-03-16 at 11 47 57 am](https://cloud.githubusercontent.com/assets/24359/13818620/fb9fad18-eb6c-11e5-870f-465c123eef37.png)

We don't want banned users showing up there. 

### Solution

The query for "likers" of a given node is here: https://github.com/publiclab/plots2/blob/master/app/models/drupal_node.rb#L107-L118

We want to filter with `.where(status: 1)`, but probably will need to `joins` the user model, so we can check the `status` field. That'll probably look like this:

````rails
self.node_selections.where(:liking => true)
    .joins(:drupal_users)
    .where('users.status = 1')
    .collect(&:user)
````

To try this out, try:

* logging in as a user
* liking something
* logging in as admin (using the [seed data's password](https://github.com/publiclab/plots2/blob/master/db/seeds.rb#L13))
* banning the user using the "spam" button (see it in the popover pictured above)
* checking the "likers" list as shown above, to see if the now-banned user

Know about automated testing? There is a spam user (uid #3) in the fixtures, so this can be tested for, too! See https://github.com/publiclab/plots2/blob/master/test/fixtures/users.yml

### Steps to fix

* [ ] claim this issue with a comment
* [ ] set up a repository locally and make sure that all tests pass
* [ ] start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress"
* [ ] fix the issue following the steps above
* [ ] try the manual test listed above
* [ ] make sure all tests pass with `rake test`
* [ ] alert someone via either the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by jywarren** [comment]
LOTS (up to ~50) of examples here of "like spam" -- however I didn't check how many of these users are banned. If we implemented this system, this would be a good test page:

https://publiclab.org/wiki/waterchestnuts

**Comment by jywarren** [comment]
The query for "likers" of a given node is here: https://github.com/publiclab/plots2/blob/master/app/models/drupal_node.rb#L107-L118

We want to filter for `where(status: 1)`. There is a spam user (uid #3) in the fixtures, so this can be tested for, too!

**Comment by franktank** [comment]
So currently I am having an error of undefined local variable or method `users' for #<DrupalNode:0x00000004f02b80> in my  /app/views/like/_like.html.erb.

In drupal_node.rb line 113 I have 
`self.node_selections.where(:liking => true).joins(:drupal_users).where(users.status = 1).collect(&:user)`

In the notes_controller.rb line 43  I added
` @users = DrupalUsers.all`

In the notes/show.html.erb line 16 I modified it to
`<%= render :partial => "like/like", :locals => {:node => @node, :tagnames => @tagnames, :users => @users } %>`

Thanks,
Franky

**Comment by jywarren** [comment]
Hi, Franky - the syntax for `where()` is:

`.where('users.status = 1')` 

with quotation marks, because you're using raw (filtered) SQL there. If you were using Ruby/Rails, you could say:

`.where(status: 1)` 

but since you're using a join, there may be ambiguity about what status belongs to, and I'm not familiar with the Rails/ActiveRecord convention for addressing fields on a joined record. But the SQL version is easy enough.

**Comment by franktank** [comment]
Oh perfect. That fixes it. 

Thanks

**Comment by ananyo2012** [comment]
Closing this as this has been solved. Though curious on whether tests are completed on this.  #498 will be a reminder for this as it contains some useful code related to this.

**Comment by ebarry** [comment]
Hi @franktank! Thank you again for your valuable contribution to Public Lab. I would like to invite you to join us in a video conference to say a few words about what you contributed and how your experience was. The event is https://publiclab.org/openhour, and it’s coming right up on November 7th, at 1pm EDT which is UTC/GMT -4. 

Please feel free to respond here, or else email liz@publiclab.org, stevie@publiclab.org, jeff@publiclab.org.
