### ISSUE TITLE
Put an "Add your location" button on the dashboard

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3092]
**Update:** https://publiclab.org/people has this button; let's add one to the dashboard too!

**Comment by ebarry** [comment]
I very much agree with the first bullet point suggestion to change the wording from "Now get the word out on mailing lists" to something about tagging. I hope people will be able to understand tagging.

**Comment by jywarren** [comment]
We've narrowed in on two key places to show a button prompt:

* [ ] on the dashboard (although that's in design process here: #6229 )
* [ ] on the https://publiclab.org/people page (as in mockup below)
* [ ] in the sidebar of notes and wiki pages

Here are a couple mockups of those spots; we should start with the sidebar!

![image](https://user-images.githubusercontent.com/24359/68955656-75bb8800-0794-11ea-94dd-8fa46989bae6.png)

![image](https://user-images.githubusercontent.com/24359/68955885-f4182a00-0794-11ea-9bbf-6c8abf5f40dd.png)

Sidebar of wiki/note:

![image](https://user-images.githubusercontent.com/24359/68955937-0e520800-0795-11ea-9a33-c33c3370fa45.png)

**Comment by jywarren** [comment]
Although noting that the last one should say "Add A location" not "Add YOUR location"

**Comment by jywarren** [comment]
And here's a mockup of how it can appear in the "your post was published" alert! 

![image](https://user-images.githubusercontent.com/24359/68956202-96d0a880-0795-11ea-9ab1-8016e7595a2d.png)

**Comment by jywarren** [comment]
The red marker can be achieved with: `<i class="fa fa-map-marker" style="color:#d00;"></i>` ! It looks cute:

![image](https://user-images.githubusercontent.com/24359/68956391-f8911280-0795-11ea-909f-9265a9f7806c.png)

**Comment by jywarren** [comment]
Also noting #5882 is an example of the prompt, but it is not currently working, so we should debug that, and then perhaps standardize the code for it so that it can be easily inserted in other places!

**Comment by Tlazypanda** [comment]
@jywarren I would like to work on this if its still available.Thanks :v:

**Comment by jywarren** [comment]
Hi, actually i believe this is completed - thank you though!
