### ISSUE TITLE
Make shortlinks consistent across site

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3093]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://publiclab.github.io/community-toolbox/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

We display "short links" in the format `https://publiclab.org/n/00000` using the node id or `nid` as `00000`, in a few places:

* Questions page (example https://publiclab.org/questions/warren/04-30-2018/what-are-your-thoughts-on-this-initial-sketch-for-a-tag-page-on-publiclab-org)
* wiki pages (example https://publiclab.org/ui)
* notes page (https://publiclab.org/notes/sagarpreet/06-06-2018/leaflet-environmental-layer-library)

These also have different displays at narrow width (for phones) as well as medium and wide. 

Let's consolidate them so they all look nice like this:

![image](https://user-images.githubusercontent.com/24359/42899415-f30c07aa-8a93-11e8-843a-7eed444dd573.png)

The code for this is here: 

https://github.com/publiclab/plots2/blob/5c94fe54e1a3fed19fb0de2c910d5478f03d2391/app/views/notes/show.html.erb#L48

****

Then as a follow-up, let's also add a button to the list view as on the dashboard:

![image](https://user-images.githubusercontent.com/24359/42899402-ea7ef93a-8a93-11e8-8310-4be390aa5740.png)

**Comment by k-sau** [comment]
Hey, i'm first timer and I want to contribute on it but I have few doubts.

1. ``These also have different displays at narrow width (for phones) as well as medium and wide.``
Using the chrome developer tools, opening the site as mobile , I was able to check that there's no shortlink option for mobile but I didn't get the ``as well as medium and wide`` :(

2. ``Then as a follow-up, let's also add a button to the list view as on the dashboard:``
Do we have to add ``New contributor`` green button?

**Comment by jywarren** [comment]
what you can do is make your browser window wider and narrower to view
different styles!

Are you thinking of where to put it? Maybe on the dashboard, it could be
shown as just the "link" icon, next to the comment icon?

**Comment by jywarren** [comment]
Yes! Similarly to how the `#0000` link works on the full page view, the link icon would itself just be linked to the same short URL. Thanks!

**Comment by k-sau** [comment]
Hi, 
+ I have added shortlink icons to the question page. The other two pages already have that icon.
+ I also added to the dashboard: https://imgur.com/a/DpQAZAO

Doubts:
+ Do i also have to add shortlink icon to the question activity also? Like: currently it only have `?` icon
+ I have almost no experience with styling, so im stuck at styling part for phone (and medium & wide size window). Do i need to remove class like:  `hidden-xs hidden-sm hidden-print` for fixing the styling part?

**Comment by jywarren** [comment]
Looks nice! On the dashboard, could we put it to the left of the button that's at the bottom right of each box? In a similar looking button but with the `#` symbol?

I think that'll allow you to do the same for question entries on the dashboard too - thanks!

Can you name what line of what file you're looking at for the styling part? Thanks for your help, we'll do our best to support as this moves along -- you're doing great! 👍

**Comment by k-sau** [comment]
Tysm :)

``Maybe we can even leave out the number in the most compact view``

By this you mean, I should remove the link no. and `#` on compact view?

**Comment by jywarren** [comment]
This is looking great. Still a few more to go. Note how on this view, we might just show the link icon and not the actual ID number, since space is limited:

![image](https://user-images.githubusercontent.com/24359/44923299-d9839d80-ad15-11e8-8c65-fcb47d3938f2.png)


That also shows a regular (non question) note, where we could also show a link icon similarly! @k-sau are you interested maybe? Or anyone else?

**Comment by jywarren** [comment]
Some of those templates are here: 

https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_node_default.html.erb

https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_node_comment.html.erb

https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_node_question.html.erb

Note how the comment template also shows the number, where we could keep it more minimal and just show the icon: 

![image](https://user-images.githubusercontent.com/24359/44923448-426b1580-ad16-11e8-8344-b9ac8baa0582.png)

**Comment by jywarren** [comment]
I'm also not sure why it's not appearing on the https://publiclab.org/questions page?

![image](https://user-images.githubusercontent.com/24359/44923480-5878d600-ad16-11e8-8361-5b14f26ad989.png)

**Comment by k-sau** [comment]
@jywarren Yes i will happily work on this. Will work on this tomorrow and will keep you updated with my progress :)

**Comment by jywarren** [comment]
oh super! Thanks so much!!!

**Comment by k-sau** [comment]
Hey @jywarren,
![screenshot from 2018-09-02 02-33-56](https://user-images.githubusercontent.com/7109945/44949971-19ec3400-ae5a-11e8-8b7c-08a6357617ed.png)

+ I actually removed all my past changes and added the `link icon` to this meta file:    https://github.com/publiclab/plots2/blob/4015e70ca5270e8312b6b340e81c7cd1155880e8/app/views/dashboard/_node_meta.html.erb#L19
is that looks good?
+ And for the `/questions`.  I added the icon in this file:
https://github.com/publiclab/plots2/blob/4015e70ca5270e8312b6b340e81c7cd1155880e8/app/views/questions/_questions.html.erb#L7
![screenshot from 2018-09-02 02-41-35](https://user-images.githubusercontent.com/7109945/44949968-0b9e1800-ae5a-11e8-8c8d-336bef8b4eb1.png)

**Comment by jywarren** [comment]
Ah, i love consolidating it in the meta file. But could we have it
displayed at the bottom in the same way on questions? I like your top icon
a lot but it also makes a difference for it to be in the same place
regardless of the post type, you know?

**Comment by k-sau** [comment]
![screenshot from 2018-09-06 02-29-19](https://user-images.githubusercontent.com/7109945/45120767-bb39f980-b17c-11e8-9533-25066805e72c.png)
hey @jywarren , Is this look better now ? 
https://github.com/publiclab/plots2/blob/4015e70ca5270e8312b6b340e81c7cd1155880e8/app/views/questions/_questions.html.erb#L17
I just cut and pasted this above line to line 26. I hope doesn't broke anything.


>  but it also makes a difference for it to be in the same place
regardless of the post type, you know?
I'm not able to understand this :(

**Comment by jywarren** [comment]
Yes, this looks super. This then is in the same place so it's not
unexpected when people look at questions.

**Comment by k-sau** [comment]
I just did but my Gemfile.lock also got updated. Is that an issue?
