### ISSUE TITLE
Integrate leaflet-environmental-layers into PublicLab.org

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#3094]
We have to integrate leaflet-environmental-layers using npm : https://www.npmjs.com/package/leaflet-environmental-layers

Things to brainstorm : 
1.) Correct place to show ? A new page maybe ? 
2.) Which combinations of layers to show  ?

Follow ups : 

- [x]  Remove skytruth map layer from profile page .

**Comment by jywarren** [comment]
Let's build it into people maps and note maps, at /app/views/grids/ -- and
into /maps main display!

**Comment by sagarpreet-chadha** [comment]
Screen-shots : 
1.) Changed recent contributors marker to black . Does this look okay ?
<img width="857" alt="screen shot 2018-07-30 at 12 10 37 pm" src="https://user-images.githubusercontent.com/14952645/43381259-bba85ba8-93f1-11e8-9a84-ac714c950729.png">

**Comment by jywarren** [comment]
Yeah, i think so -- @publiclab/community-reps what do you think?

**Comment by steviepubliclab** [comment]
looks good to me. Wondering if it will start to look like a lot of black with the base layer lines being in grey scale? Not sure, might be better!
