### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by knoconnor** [publiclab/plots2#3099]
Login failed after (presumed) account creation.

> What happened just before the problem occurred? Or what problem could this idea solve?

Several careful & deliberate attempts to login after creating account failed.  This happened whether I used my email address or username.

> What did you expect to see that you didn't?

An error msg stating that "There is no one in our system by that name . . "  

### Please show us where to look

https://publiclab.org/login

### What's your PublicLab.org username?

knoconnor

> This can help us diagnose the issue: 

Have no idea

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

Windows 10; Google Chrome vers. 67.0.3396.99, 64 bit

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hi, did you receive a "welcome" email that you could check your username
on? Did you sign up using your Google/Facebook/Twitter/GitHub account, or
did you fill out the username yourself? Thanks for reporting!

**Comment by jywarren** [comment]
Hi, we're still happy to help you out, so please re-open if you are still having trouble!
