### ISSUE TITLE
install_cloudnine.sh needs upgrades.

### ISSUE THREAD

**Issue by imacubsfan23** [publiclab/plots2#3100]
When setting up a fork of this repo using install_cloudnine.sh, I have to install rails to run the rest of the commands in install_cloudnine.sh, so I personally think it should be added so I do not have to run it twice, or even 3 times sometimes.

**Comment by jywarren** [comment]
that sounds great, and we'd be happy to merge such additions, thank you!

**Comment by imacubsfan23** [comment]
@jywarren Ready to merge at https://github.com/publiclab/plots2/pull/3095

**Comment by jywarren** [comment]
thanks!
