### ISSUE TITLE
Simplified Tag listing in sidebar:related

### ISSUE THREAD

**Issue by derek-allen** [publiclab/plots2#3121]
Per #3091, the tagging should be moved into the related sidebar, much like this.

![image](https://user-images.githubusercontent.com/40677825/43038871-45279464-8ce7-11e8-91c7-77c177a9f5cc.png)

The tagging template lives here
https://github.com/publiclab/plots2/blob/master/app/views/tag/_tagging.html.erb

**Comment by jywarren** [comment]
⚡⚡👍🏼

**Comment by derek-allen** [comment]
@jywarren to clarify, is the intention to have that tagging system live in the sidebar site-wide? Or only in the cases where "Ask a Related Question" appears?

**Comment by jywarren** [comment]
Let's do it for all wiki pages and notes and question pages - that's pretty
much site-wide!
