### ISSUE TITLE
Send @mentioned people notifications on note publication

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3122]
People are increasingly used to mentioning people like @jywarren and triggering an email notification to that person when commenting on PublicLab.org. But when you do this in the body of a note, it doesn't send a notification like it does in a comment. 

The comment "mentions" are done in this code:

https://github.com/publiclab/plots2/blob/e95d89351e9d352ffa5dafe2209c4713b1f7453d/app/models/comment.rb#L100-L115

We have a list of mentioned users here: 

https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L745

But we don't use it to trigger a notification.

This issue may need multiple parts:

* [ ] a `notify_callout_users` method in node.rb, like the one in comment.rb
* [ ] a `NodeMailer.notify_callout` or a re-use of the `CommentMailer` from the comment code above (to reduce redundancy -- although the mailer template may have to be changed not to say "mentioned in a comment" but just simply "mentioned"
* [ ] a test to show that on node `creation` (not update! because it might send twice?) that the appropriate emails are sent - like this test: https://github.com/publiclab/plots2/blob/master/test/unit/comment_mailer_test.rb#L34

Any help appreciated!

**Comment by jywarren** [comment]
Hi @namangupta01 i'm sure you are busy, but this could be a nice one to try to wrap up in your last week, do you think you have time? If not, no big deal!

**Comment by namangupta01** [comment]
Yeah sure i will create a pr for this soon. 👍

**Comment by jywarren** [comment]
great!!
