### ISSUE TITLE
Image not adjusting size with sidebar 

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#3130]
I just published a new research note and noticed my lead image did not adjust to fit the shape of the rt. justified sidebar. This is what happened: 

![screen shot 2018-07-23 at 3 38 27 pm](https://user-images.githubusercontent.com/7490478/43099067-eec328e6-8e8e-11e8-8b30-ec403eebecff.png)

I changed the image to make it less narrow and didn't have the same problem: 
![screen shot 2018-07-23 at 3 40 32 pm](https://user-images.githubusercontent.com/7490478/43099027-cf5a2ebe-8e8e-11e8-8f15-8d5cdb487185.png)

**Comment by jywarren** [comment]
Solved this one!
