### ISSUE TITLE
Community Check-in #10 Summer Of Code Week 11 

### ISSUE THREAD

**Issue by stefannibrasil** [publiclab/plots2#3133]
Hi everybody :smiley:  !

If you're new here, welcome, and please try some of our first-timers-only issues. This is a checklist for publiclab/soc.

@stefannibrasil @milaaraujo @MargaretAN9 @Gauravano @ViditChitkara @tech4GT @mridulnagpal @namangupta01 @sagarpreet-chadha @Souravirus @jywarren @MayankKashyap @siaw23 @ryzokuken @ccpandhare @icarito @abTest-123 @steviepubliclab @ebarry @publiclab/soc @publiclab/reviewers

sorry for being a little late, but today was a little busy and technically it's still Monday here in Canada :laughing: 

How was your weekend? And what is the plan for this week?
If you have not planned yet, just leave a Hi! so that we could know that you are in sync with us arrows_clockwise

Last week @milaaraujo and I did some API refactoring #3070. Besides that, we started working on a new API endpoint to show the profiles with the most recent activity #3069 and added some docs notes #3115.

This week we have some changes to do on the #3069 and maybe start importing the remaining endpoints from the controllers to the Search API.

As always, if you're waiting for a review, or if you're stuck, please request help
here OR leave a comment with @publiclab/soc and @publiclab/reviewers for
some input.

Have a nice week :tada:  !
Thank you !

**Comment by SidharthBansal** [comment]
Hi all,
I will write test for the user tag controller this week.
I will send patches for notifications of OAuth when no password set. 
Thanks

**Comment by tech4GT** [comment]
Hello Everyone!! Last week we put in a lot of work!! This week I am working a finishing up all core work in image sequencer. This week we also saw some new contributors on the project. Thank you😁

**Comment by jywarren** [comment]
Nice work @tech4GT on welcoming a newcomer into your project! https://github.com/publiclab/image-sequencer/pull/310#issuecomment-407427467

Felt good? 🎉

**Comment by jywarren** [comment]
Hi all - i just published the latest code to the production site! Check it out! https://publiclab.org 👍

**Comment by jywarren** [comment]
Hi, everyone - I was thinking... many of you have successfully welcomed a newcomer into the community recently with a first-timers-only issue. Have some of them gone on to tackle a harder issue, or more than one? 

If you feel like anyone is ready, they might want to take on a more complex project, or even post a draft first-timers-only issue of their own. What do folks think? We might take some time this week to encourage newcomers to get more involved in one of these ways!

**Comment by SidharthBansal** [comment]
Great idea. @jywarren I will suggest that we can create a page for newcomers contributions as you do every month to encourage them so that they will do bigger projects.

**Comment by Souravirus** [comment]
Great idea @jywarren. This is happening with the first-timers that they only contribute to the first-timers-issue and then never come back. 
So, last week I was working with few fixes and some modification of TESTING.md. Also, I will be working on transformation to yarn transition this week. Thank you

**Comment by jywarren** [comment]
yeah, i often try to set them up with a second issue that's somehow similar
to the first. We can coordinate in this issue or in the chatroom to help
each other match-make people with new issues... i often skim
https://publiclab.github.io/community-toolbox/#r=all

it's nice when people can re-apply their newfound skills to a related
problem, and become experts! Feels great too!

**Comment by ebarry** [comment]
Hi folks!
Looking ahead to our next video call, how would August 6 work? It's a Monday. We could use this timing to span from Vancouver to Delhi: https://everytimezone.com/#2018-8-6,300,b8jj

This event would be an all-hands video call, as well as serve as August's Public Lab OpenHour -- https://publiclab.org/openhour. This means other people may also attend. 

We'd love for each Summer of Code team to prepare a couple of slides (or -- if you insist -- a live demo!) to share about the projects they've been working on this summer. 

How does this sound?
Thanks!

**Comment by Gauravano** [comment]
Great @ebarry !

**Comment by Gauravano** [comment]
Hi @publiclab/soc ,
Last week, I have completed the Settings page https://publiclab.org/settings .Now, one can change Email settings from there.
I am working this week on https://github.com/publiclab/plots2/issues/3137 and completing documentation tasks.I would also be working on adding some more settings to the /settings.
Thanks!

**Comment by steviepubliclab** [comment]
Hey all! posted an update to the OpenHour page for our call on the 6th! [Check it out] (https://publiclab.org/openhour).   Available to join!?

**Comment by SidharthBansal** [comment]
Yeah I have written it in my schedule

**Comment by sagarpreet-chadha** [comment]
Count me in also 👍 👍 👍 !

**Comment by stefannibrasil** [comment]
Hi, everyone, I will do my best to attend, but I also have a part-time job and some weeks are busier than others... Also, @milaaraujo and I already have a weekly call with our supervisor, so we already discount that hour from our other work.

But we will talk with our supervisor if it's possible to make some changes on that week, okay? :)

**Comment by SidharthBansal** [comment]
Hi @jywarren when does the intern start? In which month?

**Comment by SidharthBansal** [comment]
Hi @jwarren I have notified all my friends on whatsapp and facebook. Let's see who all jumps into PL group.

**Comment by jywarren** [comment]
Thank you!!! It will start in August.

**Comment by sagarpreet-chadha** [comment]
Hi all !
I was busy with college stuff the previous week , and will try to catch up this week .
Starting with integration of leaflet-environmental-library to plots2 . 
Thanks !

**Comment by jywarren** [comment]
Thanks, Sagarpreet! 

OK, I'm going to do this week's check-in!

**Comment by jywarren** [comment]
Closing!!!
