### ISSUE TITLE
Add link to approve/spam comments in comment email notifications to moderators

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3137]
When I see a new comment in my email inbox, it'd be great to be able to spam + ban directly from there, if possible! 

But only moderators should receive this type of email. In any case, it could be at the bottom of the message, and if, in replying, the link gets posted to the site, it should be OK since others won't be able to use the function. @Gauravano -- any interest in this one? Should be pretty simple!

**Comment by Gauravano** [comment]
yes, I would like to take this one! Thanks!

**Comment by Gauravano** [comment]
Hi @jywarren, we don't have any separate system for first-time-comment like first-time-notes has status = 4.
 So, I guess we should make such system for comments
 OR
 We can make a new mailer which would notify moderators of first-time comments, in this case, the comment would be published on site and an email would be sent to moderators to moderate that comment.  What do you think?

**Comment by jywarren** [comment]
Oh, hi! Sorry, so I think it's enough that if you see a comment because you're otherwise subscribed, you can spam it. 

The issue is that we currently BCC everyone onto one email, so we don't send a separate one to moderators. So maybe it could say:

`Look like spam? _Flag this for moderators_. (Are you a _moderator_? Mark this as _spam_.)` 

what do you think?

**Comment by jywarren** [comment]
yeah, that sounds great, thank you!
