### ISSUE TITLE
flash[:warning] appearing on subsequent pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3141]
Hi, @Gauravano - this isn't exclusively related to drafts, but it did come up there. I've noticed flash messages get "delayed" and shown on the wrong page, say, on subsequent page loads on unrelated pages. Can you try to reproduce this? It did happen when viewing a draft page. I think it may happen for other interactions as well. 

I'd love some help trying to track this down and solving it! Thanks!

**Comment by Gauravano** [comment]
Hi @jywarren I am able to find one such occurrence while visiting the draft page if we visit any other page, then alert remains there. I am resolving it in #3140 . Any more instances which needs to resolve? Thanks!

**Comment by Gauravano** [comment]
Tracked one more instance of this issue 

![second_instance](https://user-images.githubusercontent.com/20878070/43161039-7e4ce5b8-8fa4-11e8-9481-c6d7fb42f3e6.gif)

**Comment by Gauravano** [comment]
One more instance 
![another_instance](https://user-images.githubusercontent.com/20878070/43161222-1cdc5128-8fa5-11e8-9cca-1c6df81cfcd7.gif)

All the flash alerts at application.rb are showing this behaviour, changing them to flash.now has resolved the issue.

**Comment by jywarren** [comment]
awesome! I think there was one related to OpenId authentication... not sure
if you can find it?
