### ISSUE TITLE
Optimization needed for /api/srch/profiles API query

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3147]
Probably due to very high number of users in the system (300k+?) this query needs some optimization as I believe it's responsible for some outages, and is running very slow!

https://publiclab.org/api/srch/profiles?srchString=aya

@icarito - and be aware of this @milaaraujo @stefannibrasil 👍

**Comment by jywarren** [comment]
I believe this is a double-ended string match that's running against the whole table - inefficient...

https://github.com/publiclab/plots2/blob/de4d09faf10d16ab2f15291373ca954ebaba60ee/app/services/srch_scope.rb#L5-L8

This is especially apparent when trying to autocomplete usernames after typing `@...`

https://github.com/publiclab/plots2/blob/de4d09faf10d16ab2f15291373ca954ebaba60ee/app/models/user.rb#L44-L46

Can we use this new full-text search function instead of the above code?

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/pull/3148 - one attempt at this... any suggestions?

**Comment by jywarren** [comment]
Optimizing front end w @ryzokuken too:

https://github.com/ichord/At.js

https://github.com/publiclab/plots2/blob/de4d09faf10d16ab2f15291373ca954ebaba60ee/app/views/comments/_form.html.erb#L76-L88

**Comment by jywarren** [comment]
caching example here: https://github.com/ichord/At.js/wiki/How-to-use-remoteFilter#caching-example

**Comment by jywarren** [comment]
i also limited to 10 results in the reply, in 
https://github.com/publiclab/plots2/commit/d4f16246b901a10956fe04c4c61b1d22536e55e7

**Comment by jywarren** [comment]
Opened a caching issue at #3149!

**Comment by jywarren** [comment]
We could further optimize the `User` query above by selecting only `username`, `status`, `id`... but the full text search also searches `bio` so we'd need to make an alternate form of `User.search` that does not search bios... i'll open another PR for that.

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/pull/3150 - searching only usernames!

**Comment by jywarren** [comment]
ok awesome, previously this had ~600 results, now only 10: https://publiclab.org/api/srch/profiles?srchString=aya

**Comment by stefannibrasil** [comment]
yeah, we were planning to set aside some weeks to work only on improving the search service, but we can start this week, beginning with the #3069.

**Comment by jywarren** [comment]
Also implementing @ryzokuken's optimization here: https://www.irccloud.com/pastebin/yTikGnHV/

**Comment by jywarren** [comment]
Ok, and working on this in #3172 but unable to get the debounce to work yet...

**Comment by Radhikadua123** [comment]
As I can see, #3134 was merged. Is this issue still valid ? If yes, then I can have a deep look inside it.

**Comment by jywarren** [comment]
#3172 and #3149 are still unresolved, and we'd love help with them!! Thank you!

**Comment by Radhikadua123** [comment]
I see. I would love to give it a try later on.

**Comment by jywarren** [comment]
@milaaraujo is this potentially of interest for the API work you're doing?

**Comment by milaaraujo** [comment]
Not directly... I think! What exactly needs to be done here? We are already using the full-text search function.

**Comment by milaaraujo** [comment]
Can we close this one, @jywarren?

**Comment by jywarren** [comment]
Yes, esp since it's being worked on in https://github.com/publiclab/plots2/issues/4670. Thanks!
