### ISSUE TITLE
Research note main image crops unpredictably

### ISSUE THREAD

**Issue by Fastie** [publiclab/plots2#315]
What's with the new main image on research notes? Most images get cropped so they don't present what the author intended until you click the tiny arrow and then most images extend off the bottom of the page so they never present what the author intended. The tiny arrow does not appear if that particular area of the image is white. The old way was better. Change is bad.

**Comment by jywarren** [comment]
Lead images are often way too tall, and were pushing content far down the
page, or getting minified so much that they were unreadable. This display
mode is a test, to see how it works with existing content. Some work better
than others, but it is predictable -- the image is displayed full width,
and cuts off at I think 500 pixels if the image is larger than that.

We have different options:

1. many sites deal with this problem by restricting authors to certain
aspect ratios. We don't, but could.
2. we could better indicate the expanding by making the image expand "a
little" when you hover
3. and/or give the white arrow a black stroke or shadow and make it less
tiny
4. or make a dark bar appear at the bottom of the image with the tools in
white over that bar (this'd allow us to display "download" as well)
5. make the image appear full-screen on click, with a "full screen"
indicator appearing on hover
6. we could keep this new display as default, but allow it to be overridden
with a tag or checkbox

We can also revert -- but I'd like to get to a new design that works better
than the previous version. The new design works really well on lots of
notes, such as:

*
http://publiclab.org/notes/donblair/08-28-2015/riffle-sensor-board-approach
* http://publiclab.org/notes/lperovich/08-30-2015/more-dock-data
*
http://publiclab.org/notes/lperovich/08-25-2015/threshold-single-thermal-fishing-bob
*
http://publiclab.org/notes/claudsmm/08-23-2015/lessons-from-mapping-bourj-al-shamali-refugee-camp

The biggest issue is the resolution of images; I'm thinking about bumping
it up closer to the original, maybe 1024x768.

**Comment by Fastie** [comment]
If the lead image is too tall, or unreadable, the author can chose to change it (it would be good to make it much less obscure how you replace a lead image). The author should chose a lead image that presents itself well and conveys the wanted message, and the author's decision should be respected. That image should never be cropped by the system. The image can be re-sized by the system to fit better, but never cropped. 

Three of the examples you cite as working well with the new system just happen to have unusually wide aspect ratios and fit well in the wide space. The other one gets cropped but doesn't happen to have essential content in the cropped part. Generally, the cropping process fails to present an image that has the same impact as the original.

Maybe the image can be re-sized based on its aspect ratio. Maybe the lead image should open in a floating box when clicked (instead of a new tab replacing the note) with an obvious route to return to the note.

It might be that for well selected images, the original system is about as good as you can do. If the author selects an inappropriate image, that's not anything you should worry about. Just make it obvious to authors how to replace that image.

**Comment by jywarren** [comment]
Hi, Chris - well, the current live code doesn't crop, it just hides the
lower part of the image by default if it's too tall. And I think it's not
as clear a separation of content vs. style as you lay out -- the basic
design of the site bears some responsibility to help authors present their
work well, and the old lead system isn't working that well on that count.

Also, I disagree that "Generally, the cropping process fails to present an
image that has the same impact as the original." -- from a design and
impact standpoint, I think full-width presentation of image is often
stronger, and would also like to encourage people to use images that work
well on the page, which generally means a horizontally oriented image. The
lead image has unique constraints as it is used as a thumbnail in list and
grid views, where I would actually like to crop them to 4:3 for consistent
display in a future revision.

Perhaps we can have a "full width" checkbox under the image, which can be
un-checked?

Re: _instead of replacing the note_, I'd like to move to a "download"
hover-visible button which would leave the default click behavior open to
simply open in a "lightbox modal" mode.  But we just made the "click to see
full-size" default as it was faster.

If you think there should be more clarity about replacing an image, please
do file an issue about that, or bump one up if it already exists.

At the moment I'm pretty slammed with work, so I think we should try to
find the simplest thing that'll meet our needs; would a checkbox work for
now, or should we simply revert and shelve this whole discussion until we
can circle back with more time, or find someone who's interested in coding
up a new attempt?

**Comment by jywarren** [comment]
Bumping up again -- want to revert this for now, Chris, or is it not bothering you that much?

**Comment by Fastie** [comment]
Thanks for pointing out the issues (helping authors, making useful thumbnails, etc). Reverting is probably a good idea for now, and the options for fixing it properly can be discussed. The research note creation (editing) form could have guidance about good image characteristics, and the research note display could have a button for viewing the image larger. 

Maybe the note creation form could display what the thumbnail and the lead image will look like to encourage certain types of image shapes.

**Comment by jywarren** [comment]
I def. want to improve how the main image preview works. This change was
rushed and probably should've waited, since I don't really have time to do
it properly. Perhaps I could just increase the default image display size
moderately (say, to 600x800) without messing with the ratio for now, and
roll this bigger revision into the planned editor revamp project, which is
a pretty big one.

**Comment by jywarren** [comment]
Closing; fixed in new PR #318 - will merge in soon and publish.

**Comment by jywarren** [comment]
revert went live!
