### ISSUE TITLE
Addition is wrong on total number of unique contributors

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#3152]
Hi Everyone!
Perhaps this might be a quick, math-related bug to squash? Thanks in advance!

### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I was checking https://publiclab.org/stats to see how many total contributors there were for all time, and the page displays 1234. I now believe this is incorrect because when i requested total contributors between Jan 1 2017 and today's date July 25 2018 by loading this page: https://publiclab.org/stats/range/1-1-2017/25-7-2018/ it displays 1552. 

> What did you expect to see that you didn't?

I expected to see a total number of unique contributors from all time greater than the number for total number of unique contributors for the past ~18 months. 

### Please show us where to look

https://publiclab.org/stats

### What's your PublicLab.org username?

> This can help us diagnose the issue: 
liz

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by saxe405** [comment]
Hi, sorry for a stupid question. How do i see the repository name where these stats are computed ?

**Comment by ebarry** [comment]
Hi @saxe405 , that's not at all a dumb question! In fact, I have no idea where that information lives! Thanks for writing in, i thought i was losing my mind looking at numbers which didn't seem right. I'm going to copy in @publiclab/connectors to add in any documentation that could help.
Thank you again so much for writing in!

**Comment by Gauravano** [comment]
Hi @saxe405, the stats page takes logic from  https://github.com/publiclab/plots2/blob/master/app/controllers/stats_controller.rb . Please feel free to ask for any doubt or help.
Thanks!

**Comment by ebarry** [comment]
Hi @kryptc , great to meet you!
I see what you are saying, that the main /stats page does not actually display Total Contributors over the lifespan of the website. I think you are completely right about that. 

Perhaps we could add the display of Total Contributors to the main stats page?

**Comment by ebarry** [comment]
Re-stated issue here: https://github.com/publiclab/plots2/issues/3499
