### ISSUE TITLE
Sidekiq resource consumption

### ISSUE THREAD

**Issue by icarito** [publiclab/plots2#3154]
I noticed Sidekiq uses a lot of RAM.
It could have a memory leak. This morning, recently started, it was using 1GB now, 2.7GB:

`2766M  133M  7644 S  0.5  1.7  2:24.62 sidekiq 5.1.3 app [0 of 25 busy]`

Perhaps we could decrease the number of threads somehow?

**Comment by jywarren** [comment]
How is this going?

**Comment by icarito** [comment]
I believe we've contained this. We have 10 threads for Sidekiq now (not sure where it was tweaked) and also reduced the number of passenger working threads to accomodate this (from docker-compose-production.yml file).
