### ISSUE TITLE
initial posts by newcomers (pre-moderation) not being sent to moderators@publiclab.org?

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3159]
I'm no longer seeing emails going to the moderators list for review. It seemed to stop on April 8th... if you're in the group, you can see the last one here: 

https://groups.google.com/forum/#!topic/publiclab-moderators/ArUtyP1ubuI

Since that date, emails are sent when a post is approved or spammed, but not when it's first posted. 

This line is supposed to send the initial email:

https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L196

leading to this mailer:

https://github.com/publiclab/plots2/blob/fbadc4dc65069e806a62a611099319d0b0ba74c8/app/mailers/admin_mailer.rb#L6-L17

Any help appreciated! And looks like we ought to test this...

**Comment by Gauravano** [comment]
Hi @jywarren, this is due to missing call i.e., `.deliver_now` is missing on this https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L196 line

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/pull/3160 submitted a fix, thank you!!!!
