### ISSUE TITLE
Community Check-in #11 Summer Of Code Week 12

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3167]
Hi everybody :smiley:  !

If you're new here, welcome, and please try some of our [first-timers-only issues](https://publiclab.github.io/community-toolbox/#r=all). This is a checklist for @publiclab/soc.

@stefannibrasil @milaaraujo @MargaretAN9 @Gauravano @ViditChitkara @tech4GT @mridulnagpal @namangupta01 @sagarpreet-chadha @Souravirus @jywarren @MayankKashyap @siaw23 @ryzokuken @ccpandhare @icarito @abTest-123 @steviepubliclab @ebarry @publiclab/soc @publiclab/reviewers

How was your weekend? And what is the plan for this week? 

If you have not planned yet, just leave a Hi! so that we could know that you are in sync with us :arrows_clockwise:

****

## Google Summer of Code timeline

Hi, everyone! I wanted to write in because... **I'm going on vacation in a couple weeks!** 🏖🌞  (not the best timing, but when is, really?)

So, planning ahead for **Aug 12-24**, I want to review the GSoC timeline, which is a little earlier than I remember from last year (although maybe my memory is bad):

📆 https://summerofcode.withgoogle.com/how-it-works/#timeline

⌨️ **Coding May 14, 2018 - August 6, 2018**

📥 **Students Submit Code and Final Evaluations August 6 - 14, 2018** - Students submit their code, project summaries, and final evaluations of their mentors.

📝 **Mentors Submit Final Evaluations August 14 - 21, 2018** - Mentors review student code samples and determine if the students have successfully completed their Google Summer of Code 2018 project.

🎉 **Results Announced August 22, 2018** - Students are notified of the pass/fail status of their Google Summer of Code 2018 projects.

So, this means of course, that technically we'll be wrapping up code next week. You'll hand in `code, project summaries, and final evaluations of their mentors` by Aug 14th, when I'll have just left, and then I'll be coordinating final reviews with mentors until the 21st (which I can do while away). 

During the last few daysof coding, while I'm away, I'll be checking in on urgent things every couple days, but not replying to most everyday things. I'm asking @publiclab/mentors to please be extra alert during this time to help fill in. 

But I'm also excited that this can be a chance for you all to take an even stronger leadership role -- every week, this is the kind of thing I do to help keep things running, so I'd like to ask everyone to pitch in a bit:

* 👍 request `ready` labels from people for PRs ready to merge
* 🔧 restart stalled builds (related to our #2824 issue still being worked on)
* 📋 check in on new PRs and offer help, ask for tests and other things to fill out a good PR
* ✅ check stale/stuck [first-timers-only issues](https://publiclab.github.io/community-toolbox/#r=all) to see if people need help, or someone else can take over
* 👥 check on non-plots2 projects like these to see if people need help or input:
    * https://github.com/publiclab/leaflet-blurred-location-display
    * https://github.com/publiclab/image-sequencer
    * https://github.com/publiclab/leaflet-environmental-layers

While I'm gone, I'd like to ask for volunteers ahead of time to post weekly Check-ins -- who's interested? Aug 13th and Aug 20th? 

OK, that was a lot! I hope this is helpful and sorry I can't be online through the last few days, but I'll be back soon! 🏃 And i'll be extra available right up until August 10th, my last day of work before leaving. 

****

As always, if you're waiting for a review, or if you're stuck, please request help
here OR leave a comment with @publiclab/soc and @publiclab/reviewers for
some input.

Have a nice week :tada:  !
Thank you !

(closing #3133)

**Comment by jywarren** [comment]
And a reminder about next Monday -- via @ebarry 

> Looking ahead to our next video call, how would August 6 work? It's a Monday. We could use this timing to span from Vancouver to Delhi: https://everytimezone.com/#2018-8-6,300,b8jj

> This event would be an all-hands video call, as well as serve as August's Public Lab OpenHour -- https://publiclab.org/openhour. This means other people may also attend.

> We'd love for each Summer of Code team to prepare a couple of slides (or -- if you insist -- a live demo!) to share about the projects they've been working on this summer.

**Comment by ebarry** [comment]
Yes thanks for adding this -- 
Dear EVERYONE: This coming Monday, August 6, we have the Share Your Awesome Projects! OpenHour presentation. All call information here: https://publiclab.org/openhour#OpenHour+Schedule: We are expecting everyone to have a couple slides, gifs, or a brief live screenshare demo (!) to share of your new features. Please ask if you have any questions. I am looking for your emoji reaction to this comment or another comment from *each Summer of Coder* to know that you have seen this so i can confirm your attendance.  

Here are the time schedule we're planning, worried that our standard 1pm time is really rather late in India, please comment if so (but i'm not sure we can move it :sad: )
10AM Vancouver
12PM New Orleans
1PM New York  / Miami / Providence
5PM London
8PM Israel
10:30PM India (all cities)

**Comment by namangupta01** [comment]
Hey! I guess timing is okay for india.
This week i will try to complete the the `reply-by-tweet` feature.
@jywarren Please have at #3118 after `octokit`error is removed so that i can complete my project before 6 and will also be able to include reply-by-tweet in demo on 6.  🎉
Thanks!!!!

**Comment by stefannibrasil** [comment]
hey, everyone, @milaaraujo and I won't be able to attend the call next week, so sorry!

about our progress, last week we tried several things to improve the `profiles` endpoint #3134, so it can be used for the @ autocomplete feature! Our coaches gave us some good advice and now we believe it is returning a better list of results. It accepts an `order_by` param, currently `recent`  and a `sort_direction`, DESC by default. Any other suggestion would be great!

While we don't have it finished, we are going to work on adding the Author endpoint and on improving the `people locations` query.

**Comment by Souravirus** [comment]
hi everyone,
@ebarry 10:30 is ok for us.

Regarding my work, I am currently working towards yarn transition in #2659. 
Thanks!!

**Comment by SidharthBansal** [comment]
Hi I am ok with 10:30 pm

**Comment by SidharthBansal** [comment]
Regarding my work, I am right now working on notifications and testing features. I will wrap up all code and close all the related issue of my project this week. I will also share slides by this week or the next week.
Thanks

**Comment by jywarren** [comment]
Hi, all - I think I've resolved the `octokit` bug if any of you were seeing that -- the other #2824 travis bug remains (😭) but if you restart your builds you should be able to get it to pass!

**Comment by gauravano** [comment]
Hi @publiclab/soc, I am working on adding a new setting which is silencing all the notifications related to the node. Thanks!

**Comment by ebarry** [comment]
Hi @milaaraujo and @stefannibrasil -- just saw your message that you won't be able to attend the call! So sorry to hear this. This call is *very important*, important enough for us to attempt to re-arrange around your availability. Can you please advise ASAP on what times would work for you? Perhaps earlier than 10am? Thank you!

**Comment by ebarry** [comment]
Hi @MargaretAN9 ("MaggPi"), thanks for confirming yesterday that you will be able to attend.

**Comment by milaaraujo** [comment]
Hey @ebarry! Initially this time would not work for me because I work from 9 am to 5 pm... However, Monday will be a holiday in British Columbia - we didn’t know that - so I can attend the meeting at the scheduled time!

**Comment by stefannibrasil** [comment]
yeah, I will attend as well, thanks!

**Comment by SidharthBansal** [comment]
Hi @ebarry @jywarren is these slides ok https://docs.google.com/presentation/d/10cpV5ysdAB1EOuggYI_YWoMMI6X23krj4K1waLPnnI8/edit?usp=sharing ?
I have created the slides from user point of view. Shall I add slides for developers point of view also?
I have just given an abstract view of my project without going into implementation details.

**Comment by jywarren** [comment]
I wanted also to welcome some recent contributors to this weekly check-in who've been doing a lot of great work -- @cheneyshreve ([comment tag, username, and emoji autocompletion](https://github.com/publiclab/plots2/issues?q=is%3Aclosed+mentions%3Acheneyshreve)) @imacubsfan23 ([wiki likes, follower count fixes](https://github.com/publiclab/plots2/issues?q=is%3Aclosed+mentions%3Aimacubsfan23)) @dewanhimanshu ([spam buttons](https://github.com/publiclab/plots2/issues?q=is%3Aclosed+mentions%3Adewanhimanshu)), and @derek-allen ([related tags and more!](https://github.com/publiclab/plots2/issues?q=is%3Aclosed+mentions%3Aderek-allen))

You can see their work featured in the [monthly pulse](https://github.com/publiclab/plots2/pulse/monthly), which as of right now shows **100 merged PRs** in 30 days!!!

![image](https://user-images.githubusercontent.com/24359/43599314-3044d4b8-9655-11e8-944e-9d33b1e9e3d5.png)


Hi, all - thanks for your amazing work over the past few weeks. We're really lucky to have your help and we'd love to see your contributions grow! 

If any of you are interested, now that you've had the experience of making several contributions as a newcomer, we'd be happy to help you create your own first-timers-only issue to welcome someone else into the community!

You can read about [first-timers-only issues here](http://www.firsttimersonly.com), view them [for our own project here](https://publiclab.github.io/community-toolbox/#r=all)

And [here's a guide on how to make your own!](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors)

If you want to give it a try, we can support you in getting one ready and labelling it when it's good to go -- it's a really exciting experience to help someone else take their first steps 👍 🎉 🎈

**Comment by jywarren** [comment]
@SidharthBansal that looks perfect!

**Comment by SidharthBansal** [comment]
Thanks

**Comment by dewanhimanshu** [comment]
@jywarren  Thanks

**Comment by cheneyshreve** [comment]
Thank you @jywarren <https://github.com/jywarren> ! So great to be able to
work on this will all of you and see all the new contributions everyone is
making 😃!

**Comment by SidharthBansal** [comment]
@jywarren https://gist.github.com/SidharthBansal/4968cf15675cfc700bc2a8d952489ae0 can you please suggest changes to this link?
We need to provide link to work product in the GSOC final evaluation form
Thanks

**Comment by jywarren** [comment]
Hi, @SidharthBansal - did you also post this to PublicLab.org? I think that may be the ideal place. Thank you, it looks great!

**Comment by jywarren** [comment]
And for folks who joined the Open Hour, you could re-use a lot of your presentations in the final report if you want!

**Comment by SidharthBansal** [comment]
https://publiclab.org/notes/bansal_sidharth2996/08-07-2018/gsoc-multi-party-auth-system?_=1533661182 here is the link.

**Comment by SidharthBansal** [comment]
Thanks @jywarren

**Comment by jywarren** [comment]
Hi, all - I realize I didn't post a check-in this week! Did anyone want to do this? @publiclab/soc Even if it's the final weeks of GSoC, i'd love to hear from people!

**Comment by gauravano** [comment]
Hi @jywarren I am opening one. Thanks!

**Comment by gauravano** [comment]
Opened  at #3222
