### ISSUE TITLE
Google Code-In --- Call for mentors !

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#3168]
Hi, folks! Is anyone interested in becoming a mentor for Google code-in program this year ? 
**DEADLINE 15 OCTOBER 2018, 11:59:59PM IST**
If you're interested, please leave a comment here. Thanks so much!

****

### Update via @Souravirus and others:

Those who want to be invited for GCI Mentor, thank you! Please follow these steps:

1. Solve a [first-timers issue](https://code.publiclab.org). Provide the link to the first timer issue's pull request (PR) once it's merged. In case, you are not able to find any first-timer issue, solve issue marked as `fto-candidate` or `support`, these issues may require little more work, but we'll try to help.
2. Solve a [help-wanted issue](https://github.com/publiclab/plots2/labels/help-wanted). Help wanted issues are issues which are not labelled as `gci-candidate` neither as `fto-candidate` nor as `first-timer-only`. Provide link to such issues' merged PR.
**(Make sure you claim the issue first by commenting on issue you are planning to solve)**
3. make a **first-timers issue**. [Use the extra friendly template](https://publiclab.org/n/13667) which we generally use for creating our first timer issues. Provide the link to the first timer issue which is created by you.
4. fill this form
https://docs.google.com/forms/d/e/1FAIpQLScSBS-ddZN2H-lviUJbKlbV2VwP21fdIutXOCBzigRhmXJybw/viewform?usp=sf_link

****
Those who made any gci-candidate task, please update it in #3276 as well as google code-in dashboard. Also update the gci-candate task with this message:
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

If you make any reusable task then update it [here](https://github.com/publiclab/plots2/wiki/Google-Code-In-Tasks)

****
@jywarren has curated a great list of things on mentoring, here : https://github.com/publiclab/plots2/issues/2053

****

### Help copy in issues to Tasks on the GCI dashboard

Now we need to start copying tasks over to [the GCI site](https://codein.withgoogle.com/dashboard/tasks/)!

* individual tasks can be added to the list here before they're quite ready to be made into a whole new issue: https://github.com/publiclab/plots2/issues/3276
* Many tasks that repeat (for multiple students) are being made and collected here: https://github.com/publiclab/plots2/wiki/Google-Code-In-Tasks and each could have 25 instances
* https://github.com/publiclab/plots2/labels/gci-candidate has many tasks that may need to be copied in

Also be sure to sign up as a mentor for various tasks!

**Comment by sagarpreet-chadha** [comment]
I am interested ❣️

**Comment by namangupta01** [comment]
I am interested too. :)

**Comment by Souravirus** [comment]
I am also interested :smiley:

**Comment by Gauravano** [comment]
I am interested too!

**Comment by SidharthBansal** [comment]
I am interested too

**Comment by jywarren** [comment]
Amazing, everybody! I've made a note to bring this up on the coming Monday staff call for review.

**Comment by jywarren** [comment]
And just noting https://codein.withgoogle.com/ - doesn't seem active yet, but did someone say the application is due in October?

**Comment by MayankKashyap** [comment]
Oh very nycc, it's look good.

**Comment by StlMaris123** [comment]
I am interested too

**Comment by shivani-kapania** [comment]
I’m interested!

**Comment by sachingoyal2910** [comment]
I'm interested.

**Comment by mridulnagpal** [comment]
I am interested too.

**Comment by ViditChitkara** [comment]
Interested!!!

**Comment by jywarren** [comment]
This is awesome. I checked and we are all good to apply this year. Let's
keep coordinating in this issue and touch base when the deadlines approach.
Thanks, all!

**Comment by ankitbhardwaj78** [comment]
I am Interested...

**Comment by SarthakSam** [comment]
I am also interested!!

**Comment by sanchittanwar7** [comment]
Interested!

**Comment by jywarren** [comment]
Oh wow, thanks folks -- how did you end up finding our project?

**Comment by SarthakSam** [comment]
A friend of mine told me about it.

**Comment by namangupta01** [comment]
Hey @jywarren, @shivani-kapania and @sachingoyal2910 are my classmates. They are interested in contributing to the project.

**Comment by MayankKashyap** [comment]
@sachittanwar which project you would like to mentor. And btw welcome in public lab.

**Comment by sanchittanwar7** [comment]
Thanks @MayankKashyap. I'm looking for mentoring in Google Code-In

**Comment by jywarren** [comment]
Hi, all - this was just announced, and it's early this year! 

http://g.co/gci

> Organization applications open on September 6, 2018 at 12:00 (Eastern Daylight Time)
 
> The contest begins for students on October 23, 2018 at 12:00 (Eastern Daylight Time)!

> Organizations -- If you would like to apply for the 2018 program please start thinking about the tasks you would like students to work on and reach out to your community members to ask if they would like to be mentors for the program. Organization applications open for GCI orgs next week on Thursday, September 6th, and close less than 2 weeks later on Monday, September 17th. We will announce organizations on Tuesday, September 18th giving orgs 5 weeks to create their tasks before the contest begins on October 23rd.

Announcement blog post: https://opensource.googleblog.com/2018/08/announcing-google-code-in-2018.html

Shall we start making a list of tasks or types of tasks that people want to create? As we mentioned before, we don't want to post them all at once, but to have a big list which we gradually post, so that we don't overwhelm ourselves with the response. We need to be sure we can support enough participants at the same time.

Where should we make our big list of tasks?

**Comment by jywarren** [comment]
Note the category `Design: graphic design or user interface design` -- could we ask for sketches/mockups, and design ideas for different parts of the site? 

Potentially bite-sized design mockups that help to solve specific issues we identify... not even a page, but some small ambiguities or ugly spots? Something as small as this for example:

![png](https://publiclab.org/system/images/photos/000/024/809/large/Screenshot_2018-05-02_at_9.49.02_AM.png)

The nice part is that we might ask multiple students to submit mockups as design proposals, and we could compare their design solutions to the same problem. 

@ebarry @steviepubliclab

**Comment by namangupta01** [comment]
@jywarren do we need to make list which is visible to all or visible to sphefic people if this is the case we can go make list in reviewers group?

**Comment by jywarren** [comment]
I think we can make it visible to all -- but just not post them tagged as
GCI tasks just yet. No?

**Comment by SidharthBansal** [comment]
We can make list visible to all without tags on that issue.
We can have a milestone to group together all such tasks
We can open a issue which will contain a checklist if all the issues. The checklist can be repeatedly edited by the mentors of GCI and they can refer the issue no in that checklist if issue is created. Tick the point in checklist if it is solved. The discussion can go beyond the main body of checklist in the issue.

**Comment by SidharthBansal** [comment]
@jywarren can you please modify the reviewers team. There are many people who left pl and many new contributors. This will help us at GCI period.
Can I open an issue at plots2 with different categories? Then folks can edit that and can add new issues name there.

**Comment by SidharthBansal** [comment]
We can also include the tasks not solved yet in GCI

**Comment by SidharthBansal** [comment]
Can we add points to issues for GCI?? I will really like to compete and have max points :smile:

**Comment by sagarpreet-chadha** [comment]
Cool idea @SidharthBansal !
Lets make a list on PL --- we can choose from these categories : 

<img width="708" alt="screen shot 2018-08-30 at 11 52 02 am" src="https://user-images.githubusercontent.com/14952645/44833311-55fd7a00-ac4b-11e8-9b0f-97be27c02a1a.png">

**Lets start from here ?** https://publiclab.org/wiki/gci-possible-tasks

**Comment by SidharthBansal** [comment]
OK I am opening a issue. Everyone can edit it.

**Comment by ccpandhare** [comment]
This might be very late; sorry.
But I'd like to be a mentor too, if possible. 😁

**Comment by SidharthBansal** [comment]
You all can add issues under headings in #3276

**Comment by tech4GT** [comment]
Hello everyone, I'm in too!!😊

**Comment by SidharthBansal** [comment]
Hi all. Is there any mentoring form which mentors need to fill?

**Comment by jywarren** [comment]
I'm not sure -- i think probably when we apply and are accepted, we can
invite mentors. That's how it works for GSoC.

**Comment by SidharthBansal** [comment]
@jywarren do we participate in outreachy?? I saw your posts about outreachy once

**Comment by jywarren** [comment]
We'd like to but haven't yet done so. Maybe this year...?

**Comment by SidharthBansal** [comment]
Let me search and post the timeline....I want public lab will participate in every program held in yr

**Comment by SidharthBansal** [comment]
GCI applications are open now. Gentle ping to apply there @jywarren
Thanks

**Comment by SidharthBansal** [comment]
This is outreachy page. Applications are open soon. May I create a new
issue for this @jywarren?
https://www.outreachy.org/apply/project-selection/

**Comment by SidharthBansal** [comment]
I think we need to apply before 12 sep in outreachy
www.outreachy.org/communities/cfp/

See the timeline

**Comment by jywarren** [comment]
Ah, thanks, i'll note this but it may require fundraising!

For Code-In, i'm registering, but it asks:

**Is your organization prepared to provide between 150 and 500 tasks for students to complete?**

Are we??? 😄 🚀

**Comment by gauravano** [comment]
We are prepared for sure :smile: :+1: :100: 

![typing_image](https://user-images.githubusercontent.com/20878070/45327825-c921bd00-b576-11e8-8731-e53392005c36.gif)

(Image source - [liz's profile](https://publiclab.org/profile/liz))

**Comment by sagarpreet-chadha** [comment]
Yes we can easily achieve the lower limit 😄 !

**Comment by jywarren** [comment]
Haha, ok you folks. We'll do it. But remember!!

Requirements:

1. provide a pool of tasks for contestants to choose from, which are publicly published by the Organization;
2. make available five (5) or more individuals responsible for helping contestants integrate with the Organization’s community ("mentors");
3. assign mentors (and alternates in case such mentor becomes unavailable) to monitor the progress of contestants working on the Organization’s tasks and mentoring them as the Contest proceeds;
4. evaluate contestants’ entries for tasks within thirty-six (36) hours of submission and decide whether or not the task has been completed successfully;
assign at least two (2) administrators to act as a main point of contact for Google; and
5. evaluate the work of the twenty (20) highest scoring contestants and select six (6) contestants as Finalists and two (2) of those Finalists as Grand Prize Winners for the Organization.

**Comment by Souravirus** [comment]
Ok we can do it.

**Comment by jywarren** [comment]
Great -- the application is also asking to see: 25 example tasks. Are we organizing them at this issue? https://github.com/publiclab/plots2/issues/3276#issuecomment-418078725

Can we make a list of 25 that are not posted as FTOs yet?

**Comment by jywarren** [comment]
They say: `Be sure to include tasks from all 5 categories.`

and linked to https://developers.google.com/open-source/gci/help/org-sample-tasks

**Comment by jywarren** [comment]
I believe this is the last thing to prepare for the application. 6 days to go before it's due!

**Comment by gauravano** [comment]
@jywarren should we make a list of 25 tasks in a document or should we create 25 issues?

**Comment by jywarren** [comment]
does this page explain their preference?
https://developers.google.com/open-source/gci/help/org-sample-tasks

**Comment by Souravirus** [comment]
So, that means they just want to see the 25 tasks somehow. So, I think making 25 issues with GCI tag on them will do with a description that "reserved for GCI only".

**Comment by gauravano** [comment]
The examples given at the page (linked above ) list small challenges so if we are going to keep that level of tasks then creating a separate issue is not required. 

> Whoever would be creating the task should also add relevant tags and categories.

I meant that whoever would be adding the task at #3276 should also add relevant tags too.

**Comment by SidharthBansal** [comment]
We can create list in #3276 and open respective issues when gci starts with
gci label.

And yeah we will meet the requirements for sure

**Comment by jywarren** [comment]
OK well lets start in #3276 and if we find it gets out of control then we can start breaking them into their own issues. How about that as a path? OK -- 5 days to go! Also note that @ebarry is starting to mark some that could be included in the list. I'll make a `gci-candidate` tag so we can track those too.

**Comment by jywarren** [comment]
OK folks, so I added a bunch of tasks to #3276 with links to code. I think we're getting close to 25, but please check out https://github.com/publiclab/plots2/labels/break-me-up for some good candidates to add. 

Then we'll have to start adding code links, and other information so they aren't too bare or too complex. For now we can do it in comments so you know who has added them. At the end we can do some cleanup and consolidation. 

They'll be due monday!!!

**Comment by bajajerk** [comment]
I am interested to become mentor

**Comment by geekychaser** [comment]
I want to become GCI mentor

**Comment by jywarren** [comment]
Hi, all! Thanks for your interest! Our task list is coming together here: https://github.com/publiclab/plots2/issues/3276

Please add lines of code if you can! And, we'd like to ask all prospective mentors to complete a first-timers-only issue before GCI begins, so you know how our workflow goes. Can mentors who have done one before work with mentors who are new to ensure this? 

I think it will make a big difference for when we are in the middle of Code-In and will be able to have more people familiar with first-timers-only issues, and will be able to make more of them quickly when needed. Thanks!

**Comment by gauravano** [comment]
Congratulations, everyone :tada: :smile: ! Public Lab is officially announced as a Google Code-in participating organization. https://codein.withgoogle.com/organizations/public-lab/.

To all the new contributors, we hang out most of the time in Gitter chatroom - https://gitter.im/publiclab/publiclab. Feel free to join in there.

Thanks!

**Comment by SidharthBansal** [comment]
Awesome news

**Comment by namangupta01** [comment]
Congratulations everyone!

**Comment by sagarpreet-chadha** [comment]
Great news...so exciting ❣️

**Comment by jywarren** [comment]
Folks who'd like to be invited as mentors: please complete a [first-timers-only](https://publiclab.github.io/community-toolbox/#r=all) issue -- and note which you've completed here and I'll add you to the mentors group!

**Comment by jywarren** [comment]
Also, if I don't already have your email please send it to jeff@publiclab.org so I can send the invite. Thanks!

**Comment by vchrombie** [comment]
Hey, I am interested in GCI mentoring. Can someone help me with this?

**Comment by geekychaser** [comment]
>>Folks who'd like to be invited as mentors: please complete a first-timers-only issue -- and note which you've completed here and I'll add you to the mentors group!

@SidharthBansal , @jywarren sir I have created a fto (#3363) and also solved a fto(#3335) with your help @SidharthBansal . My email is geekychaser@gmail.com. Can you please add me to the mentors group and send me an invite link for GCI mentor

**Comment by Souravirus** [comment]
Those who want to be invited for GCI Mentor, please follow these steps:

- solve a first-timers issue

- solve a help-wanted issue

- make a first-timers issue

- fill this form 
https://docs.google.com/forms/d/e/1FAIpQLScSBS-ddZN2H-lviUJbKlbV2VwP21fdIutXOCBzigRhmXJybw/viewform?usp=sf_link

Thank you

**Comment by aSquare14** [comment]
@Souravirus In the google form email address is being asked for twice :smile:

**Comment by Souravirus** [comment]
Yeah right, just fill it for now. @SidharthBansal can you correct the Google form ?

**Comment by SidharthBansal** [comment]
Hi @all first timer issues are those which are specifically labelled as first timers. While the others are help wanted. So @aSquare14 you need to edit your form after making a help-wanted pr.
I have edited the form thanks

**Comment by jywarren** [comment]
@geekychaser fantastic job creating a FTO and welcoming a new person into the community! Great work! I'm sending you a mentor invite. Will check the form as soon as I get into the responses -- @SidharthBansal if you could share again that'd be great. Thanks!

**Comment by jywarren** [comment]
I've also added all current mentors to @publiclab/mentors -- and will continue doing so as we add people. Thanks! 👍 🐶 🎈 😄

**Comment by SidharthBansal** [comment]
I have shared the link. Have you got the emails of people who have filled the form

**Comment by jywarren** [comment]
Echoing an idea from [the chatroom](https://publiclab.org/chat):

> Idea I just had! We should make a recurring task for gci that is reviewing others' pull requests!!!
> I.e. look at a Travis error, or help resolve a merge conflict... We can have a guide for reviewing

💥 

> for example we could say 'see this list of fto-candidates and choose one, and help format it to be a full first-timers-only issue' or 'see this list of pull requests, choose one and read through it (using this list of recommendations) and help troubleshoot and prepare it to be merged'

> so then reviewing a PR from another newcomer can become a task we only have to write once, but is usable multiple iterations

**Comment by SidharthBansal** [comment]
@jywarren #3358

**Comment by Paarmita** [comment]
I'm interested to become GCI mentor

**Comment by SidharthBansal** [comment]
@Paarmita https://github.com/publiclab/plots2/issues/3168#issuecomment-423219024

**Comment by sukhbir-singh** [comment]
I am interested in becoming Google Code-In mentor. :smiley:

**Comment by rishabhptr** [comment]
@jywarren Is the call for mentor still open? Would love to be a mentor 😄

**Comment by igniteeng000** [comment]
I am interested in becoming gci mentor.

**Comment by jywarren** [comment]
Yes, it still is, thank you! Please use the form to apply and we're happy
to answer questions!

**Comment by jywarren** [comment]
I've made a "reusable" issue for adding code links to issues, to help prepare them. It's a good (small) one for newcomers, but also one which really helps to prepare issues for first-timers! 

https://github.com/publiclab/plots2/issues/3424

Someone want to add a recurring task for this?

**Comment by jywarren** [comment]
We can do the same for "Help someone troubleshoot their pull request" and "Draw a mockup for a design problem" linking to https://github.com/publiclab/plots2/pulls and https://github.com/publiclab/plots2/labels/design, respectively!

**Comment by Souravirus** [comment]
Hi @ebarry can you tell when is the date of the open hour as it is not specified. Is it on the first Monday of October as usual or some other day?

**Comment by jywarren** [comment]
I think yes, it should be this coming Monday!

**Comment by rbhatia46** [comment]
@jywarren, I have completed the form and all the prerequisites and would like to be a mentor. Please check. Thanks!

**Comment by avsingh999** [comment]
I am interested in becoming Google Code-In mentor.

**Comment by SidharthBansal** [comment]
Please fill up the form given in above comments.
Thanks

**Comment by avsingh999** [comment]
@SidharthBansal I have already filled that form

**Comment by jywarren** [comment]
Many tasks that repeat are being made and collected here: https://github.com/publiclab/plots2/wiki/Google-Code-In-Tasks

This is looking great!

**Comment by Mridul97** [comment]
I am interested in becoming Google Code-In mentor. :-)

**Comment by jywarren** [comment]
Great @Mridul97 ! Take a look at the top of the page for more info.

Mentors who've gotten their invites, I just created a "reusable" tasks for translations as we've discussed, in #3515, and copied it into a GCI task. It's a good first-timers issue. Please sign up on that task as mentors so we have plenty of people able to help with that! Thank you!

**Comment by jywarren** [comment]
Hi, @avsingh999 i've added you, thanks! However please do go in and add extra info and responses to the issues you've opened already. You could tag them with `needs-code-links` or otherwise provide extra info to help make them solvable tasks for GCI. Thank you!

**Comment by VaaibhaviSingh** [comment]
I am interested in becoming a Google Code-In mentor : )

**Comment by geekychaser** [comment]
@ebarry I want to be a part of live session. I am in 3rd year and pursuing Computer Science Engineering from GGSIPU

**Comment by shivani-kapania** [comment]
> Great @Mridul97 ! Take a look at the top of the page for more info.
> 
> Mentors who've gotten their invites, I just created a "reusable" tasks for translations as we've discussed, in #3515, and copied it into a GCI task. It's a good first-timers issue. Please sign up on that task as mentors so we have plenty of people able to help with that! Thank you!

Done! @jywarren

**Comment by vikul1234** [comment]
I am interested in becoming a google code-in mentor.

**Comment by rockstar777** [comment]
I am interested

**Comment by vsk4** [comment]
I am interested in becoming a Google Code-In mentor.

**Comment by YashishDua** [comment]
I am interested to be a GCI Mentor here at PublicLab.

**Comment by vishalka98** [comment]
I am interested in becoming a Google Code-In mentor.

**Comment by SidharthBansal** [comment]
Please see details given in issue body

**Comment by jywarren** [comment]
and thank you, everyone!!!

**Comment by samagragupta** [comment]
I am interested in becoming a Google Code-In mentor.

**Comment by Dhiraj240** [comment]
Hi, i want to be a GCI mentor for this year.I was gazing towards an opportunity and finally found it.Am i late ? are you still accepting the forms? if yes then i will immediately start working on issues.

**Comment by DakshGondaliya** [comment]
Hello everyone, I am Daksh Gondaliya a third year student pursuing B.Tech. in Computer Science and Engineering at Indian Institute of Information Technology Vadodara. I want to become a mentor in GCI 2018 with Publiclab. I am very eager to work with open source organization Publiclab. I have experience in C, C++, Java, Python, HTML, CSS, Javascript, Bootstrap, React, Postgresql and also experience about embedded related things like Arduno Project. I did my summer design project based on this. I want to explore and experience more about open source with Publiclab.

GitHub profile:
https://github.com/DakshGondaliya
LinkedIn profile: https://www.linkedin.com/in/daksh-gondaliya-64625615b/

Thank you...

**Comment by rohan2599** [comment]
Hey everyone , I am intersted in becoming the google code-in mentor 2018 for public lab.I have been contributing open source in various orgs for about 1 year. And I am looking for an opportunity to work with this organisation.Please can somebody guide me

**Comment by SidharthBansal** [comment]
Please see the details given in issue body

**Comment by DakshGondaliya** [comment]
I am interested in becoming a Google Code-In mentor. @jywarren @SidharthBansal I have filled the form, please review it.

**Comment by jywarren** [comment]
Hi, all - I see a few people asking to join as mentors. I do want to emphasize that we really need to see a link to at least one `first-timers-only` issue you've created according to the template: https://publiclab.org/n/13667

This way we can see you're comfortable publishing a full "FTO" issue -- welcoming a newcomer into the community. Thank you! 

If you've already submitted your form but did not include a fully-formatted `first-timers-only` issue, you can reply here with an updated link and I'll review it. If you've applied and haven't seen any invites or acceptances, this is likely to be the reason why (otherwise I may simply not have gotten to your application yet if it was in the past few days!).

Thank you!

**Comment by jywarren** [comment]
Another request to people -- we have ~20 mentors now and ~28 applications (so a few applications to go through still) -- but we have over 50 pull requests waiting to be supported and prepared for merging!

https://github.com/publiclab/plots2/pulls

**Comment by Dhiraj240** [comment]
@jywarren i have not received any acceptance for GCI mentor.Although i have given you private message on gitter also.[This](https://github.com/publiclab/plots2/issues/3611) is my link to first-timer-issue and i have submitted an issue where i want to work on is [this](https://github.com/publiclab/plots2/issues/3646). Should i start creating first-timer-issues because i thought that till now i haven't received any acceptance so i focused on sending PRs.

**Comment by vishalka98** [comment]
When I again check my  GCI mentor form I found  some problem in form, Now I corrected it.
Please again review my GCI mentor form.
My GCI mentor form link.
https://docs.google.com/forms/d/e/1FAIpQLScSBS-ddZN2H-lviUJbKlbV2VwP21fdIutXOCBzigRhmXJybw/viewform?edit2=2_ABaOnufAE9hhWvq0EB9y576EuNrKBDYVC4x9ZhhWmSgCPRiXv_soNU1IFg

Sent from Mail for Windows 10

**Comment by rohan2599** [comment]
I want to become gci mentor for public lab in gci 2018. @jywarren @SidharthBansal I have already filled the form .You can review the form.

**Comment by vikul1234** [comment]
@jywarren  I have submitted the form already , sharing my FTO issue #3592

**Comment by SidharthBansal** [comment]
Dhiraj go forward and create issues. Jeff is busy now a days. So he will
send invites whenever he gets free.

**Comment by SidharthBansal** [comment]
Vikul you need to create a first timer issue and mentor another guy so as
to demonstrate your mentoring skills. You have created a fto and solved it
yourself. That is why we have not accepted your form till yet.

Dhiraj you need to assist some individuals in first timer issues and help
wanted issues from starting point till they get familiar with public lab

**Comment by SidharthBansal** [comment]
Vishal katiyar you have not made any first timer issue nor helped folks in
solving issues. You have reported an issue. But not created fto.
Also, you have not completed any help wanted issue
@all help wanted issues are issues which doesn't contain ' gci candidate' ,
'first timers only' , nor 'fto' label.
They may or may not have help wanted label.
Please read the guidelines carefully before filling the forms

**Comment by SidharthBansal** [comment]
NOTICE:
This is to inform all the aspiring collaborators who want to become GCI Mentors at Public Lab 2018. They have to complete the required tasks for becoming a mentor and fill the [Google Form shared](
https://docs.google.com/forms/d/e/1FAIpQLScSBS-ddZN2H-lviUJbKlbV2VwP21fdIutXOCBzigRhmXJybw/viewform?usp=sf_link) before **15 October 2018 11:59:59pm IST** if they want their applications to be considered.

**Comment by SidharthBansal** [comment]
Required tasks are clearly listed in this issue body.

**Comment by jywarren** [comment]
Thanks Sidharth! Agreed, we would love to consider more mentors but need to start focusing on getting tasks prepared. Thanks, everyone!!!

**Comment by sk9331657** [comment]
@jywarren  @SidharthBansal  I have already completed my tasks and I am currently guiding newcomers in solving fto's issues. Please review my GCI Mentor application. Eagerly waiting to help the awesome community as a GCI Mentor. :smile:  . Thank you for timely guidance and support.

**Comment by jywarren** [comment]
Have people seen the csv uploader and could it be helpful for copying in issues?

https://code.googlesource.com/codein/api

**Comment by SidharthBansal** [comment]
There are some updates on https://developers.google.com/open-source/gci/help/oa-tips
Please check that out.
This is plots2 gci labelled issue list https://github.com/publiclab/plots2/issues?q=is%3Aopen+is%3Aissue+label%3Agci-candidate
We have 74 issues now.
Many issues have multiple instance count.
We are in a good situation to start welcoming GCI Students
All the @publiclab/mentors are requested to make some ``gci-candidate`` labelled issues, mark some small issues with ``gci-candidate`` tag, convert ``fto-candidate`` issues to ``first timers only`` issues so that we can start giving them to gci students.
Few guidelines https://github.com/publiclab/plots2/blob/master/doc/GCI_MENTOR_GUIDELINES.md
Thanks everyone for help. Hope we will welcome a big crowd soon.

**Comment by SidharthBansal** [comment]
Also open up some ``first timer only`` issues

**Comment by jywarren** [comment]
Collecting multiple-use issues under a label now! https://github.com/publiclab/plots2/labels/multiple-use

**Comment by Souravirus** [comment]
Nice one @jywarren, I was thinking of having a multiple-use issue sometime before.

**Comment by jywarren** [comment]
Also, sagarpreet is doing some great work making design sketch multi-use
issues like this:

https://github.com/publiclab/leaflet-environmental-layers/issues/61

We could use this template to get input on other design issues too at
plots2 or other projects! Great work @sagarpreet-chadha!

**Comment by SidharthBansal** [comment]
@publiclab/mentors are advised to add more information to welcome new aspiring students by editing the issue #3698.
Also, I will be closing this issue day after tomorrow. We will be moving to a new issue to discuss things to be planned out for gci. 
So all the aspiring mentors hurry up and fill the form before the deadline.
Thanks everyone for making Public lab a wonderful community

**Comment by aashna27** [comment]
I am interested in being a gci-mentor. 
I have been through all the steps please review.

**Comment by Rishabh570** [comment]
I have submitted my form already.
Its been an awesome experience contributing to this community, would love to keep contributing :)

**Comment by SidharthBansal** [comment]
All the forms are being reviewed. All the mentors who will be selected will get an invite on their email address. Best of luck.

Now we are focusing on students.

**Comment by SidharthBansal** [comment]
All potential mentors who have not got an invite are requested to wait till 22nd october for their results

**Comment by jywarren** [comment]
Hi everyone - I just went through and accepted 10 new mentors who'd applied before the deadline. There were a few people who still hadn't posted a first-timers-only issue following our template, and if they follow up to do so (i left comments on your issues) I can circle back in a few days and approve anyone else. Thanks for your interest and support!

Since many of you are new, I want to re-iterate -- please check out our Code of Conduct which helps us keep this a respectful and welcoming community! https://publiclab.org/conduct

We take a lot of pride in our friendliness, as well, so we would as always LOVE to see people welcoming newcomers with some extra nice messages 🎉 👍 🎈 

We now have THIRTY EIGHT mentors in the Google Code-In program. You are all amazing! ⚡️ 🙌 🔥

**Comment by SidharthBansal** [comment]
Welcome back jeff. Hope you have an awesome time in China 🎉 👍 🎈

**Comment by Dhiraj240** [comment]
@jywarren Thanks for selecting me, i have just got an invitation.Hope to start my journey with the organisation till my Gsoc 2019 or even after that too.
Thank You so much.

**Comment by SidharthBansal** [comment]
All selected mentors please visit to https://github.com/orgs/publiclab/teams/mentors/discussions/12

Congratulations all of you!!! :1st_place_medal:  Will have a great time this winter with great people.

**Comment by SidharthBansal** [comment]
## Looking for GSoC
**Reviewing PRs and collaboration efforts will be judged in your upcoming GSoC proposals**
If you are a GSoC'19 aspirant, then we need to tell you a good news. All the reviewing tasks will be judged in the upcoming GSoC'19 proposals. If you can review the PRs, help each other across issues, prs, create ftos and much more. Just commenting on the issues to help other folks is okay.
We will be having a special REVIEW/TEAMWORK section in the GSOC'19 proposal this summer.
All the best upcoming GSoCers!!!

**Comment by shreyateeza** [comment]
Hi, @SidharthBansal ! I have been contributing to open source since a year. I have contributed to coala, systers to name some. Sorry for being late but can I apply for a mentor at Publiclab? Rest I am trying to find an issue for me to work on to prove. You can also check my GitHub profile. I have been quite active in reviewing PRs and guiding the contributors.

**Comment by SidharthBansal** [comment]
We are no longer accepting new mentors. Sorry.

**Comment by jywarren** [comment]
Hello all - just posted a call for mentors for Summer of Code 2019 at #4585. Thank you!!!

**Comment by SidharthBansal** [comment]
Hi all !!!
After wonderful GSoC 2019 and awesome GCI 2018 let's plan for GCI 2019. Who all are interested and free this year?
I am opening a new issue for GCI 2019.

**Comment by SidharthBansal** [comment]
Refer #6238

**Comment by jywarren** [comment]
Hi, all! New call for SoC mentors for 2020 is up here! https://github.com/publiclab/plots2/issues/7360
