### ISSUE TITLE
add more types of sorting to /people

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#317]
To add to the improvement of https://github.com/publiclab/plots2/issues/206 which re-organized /people by most recent node update, here are additional sort types that are needed -- each may be somewhat complex to do:

- [x] **join date** - this is easy, and used to be the default
- [ ] **number of contributions** - this will be a bit tough -- it involves a count query, or a caching of a node count
- [ ] **number of likes** earned on their research - this will be even harder, as it involves nested references -- a list of Users whose Nodes have earned Likes
- [ ] by **who has filled out information** (which will include adding a picture) on their profile page (https://github.com/publiclab/plots2/issues/308) (this'll be much harder)

Any other sorting would be accomplished by tagging (see https://github.com/publiclab/plots2/issues/104)

![screen shot 2018-01-22 at 11 33 09 am](https://user-images.githubusercontent.com/24359/35231929-213d2cce-ff68-11e7-93bf-e222ddd66f32.png)

**Comment by gauravano** [comment]
Hi @ebarry @jywarren, we now provide these sorting options - username, join date, last activity. If we still want to add other sort options, we can add small links above the table? 

What do you think about this?

Thanks!

**Comment by jywarren** [comment]
I think we're all good here! Thanks!!!!

**Comment by jywarren** [comment]
We can re-address what we'd like to show in the new card display on the new People page: https://publiclab.org/notes/edie_blues/01-16-2019/what-do-you-think-about-this-design-for-the-people-page
