### ISSUE TITLE
Trending tags showing duplicates

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3188]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

I think we're missing a `group()` or something on the https://publiclab.org/dashboard's trending tags area - i'm seeing 5 of the same:

![screen shot 2018-08-02 at 12 29 19 pm](https://user-images.githubusercontent.com/24359/43597330-c6d11cee-964f-11e8-943d-dcbbcf8e62b6.png)

Here's the code - 

https://github.com/publiclab/plots2/blob/0663ac5f7ad7d047fc47e2b5b9ae59c943f354bc/app/models/tag.rb#L268-L277

And here's the test, where i'm not sure but maybe we should test to be sure they're unique? 

https://github.com/publiclab/plots2/blob/ceb7d05404b4619c7fa8cd8cae5e8215798cb02c/test/unit/tag_test.rb#L131-L137

Any help appreciated!

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by ValentinaTironi** [comment]
I just have one question, How I send you the task ready? Do I have to do a pull request in repository or what? thanks!

**Comment by gauravano** [comment]
Hi @ValentinaTironi , this task is reserved for Google Code-In students, have you claimed this from GCI website?

**Comment by gauravano** [comment]
Awesome! You have to open the Pull request with your changes. Thanks!

**Comment by ValentinaTironi** [comment]
Hi! I'm trying to do a `git push` to do a pull request here but it says that I don't have permission. What I have to do?

**Comment by geekychaser** [comment]
@ValentinaTironi You need to do `git push` to your forked repository and then create a pull request.
Good luck!

**Comment by jywarren** [comment]
so that would be something like `git push git@github.com:ValentinaTironi/plots2
feature-branch-name` or possibly `git push
https://github.com/ValentinaTironi/plots2 feature-branch-name`

ask if you need help, we're happy to support!

**Comment by geekychaser** [comment]
@ValentinaTironi It seems like you have not forked the repository. So to get started follow these installation process `https://github.com/publiclab/plots2#installation`

**Comment by ValentinaTironi** [comment]
@geekychaser Yes, I tried to do following these steps, but I can't do `git clone https://github.com/ValentinaTironi/plots2.git` like that said

**Comment by jywarren** [comment]
This didn't end up solving the issue, unfortunately! Reopening to see if we can develop another solution.

**Comment by ValentinaTironi** [comment]
Oh, sorry. Tell me if I can help in something :/

**Comment by milaaraujo** [comment]
I'll work on this one.
