### ISSUE TITLE
Filter additional quoted text or signatures in email replies to comments

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3218]
Many people use a signature in their emails, for example:

```

Hi there!

--

Auto-signed, 
Jeff
```

Let's try to add a new filter to hide signatures in reply-by-email. @namangupta01 just a heads up, I know you're wrapping up SoC but noting this so we don't forget!

Existing filters for Yahoo and Gmail are here: 

https://github.com/publiclab/plots2/blob/04d5bbca4f47066e9628c1dc78e9961ef32c20f7/app/models/comment.rb#L299

**Comment by shubhscoder** [comment]
I am a beginner , and would like to take up this issue. Would be very helpful if you guide me @jywarren

**Comment by jywarren** [comment]
Attempted fix in https://github.com/publiclab/plots2/pull/3830

But using quote delimiter `On Tuesday, 3 July 2018, 11:20:57 PM IST, RP <rp@email.com> wrote:` using regex. 

@shubhscoder this was a pretty tough one, maybe not helpful for a beginner! If you're still interested, please check out https://code.publiclab.org!

**Comment by jywarren** [comment]
If anyone wants to build on this to complete the issue, we could use the help!

An example of quoted text we'd like to hide is here: https://publiclab.org/questions/warren/10-26-2018/how-can-we-connect-a-pms5003-dust-sensor-to-an-arduino#a1252

![image](https://user-images.githubusercontent.com/24359/47660429-58a61e00-db6d-11e8-907b-7bcb005a42ee.png)

**Comment by shubhscoder** [comment]
Yes I am very interested. I was detected with dengue about a month back, so
had to go to the hospital and everything just stopped. But I am perfectly
fine now , and look forward to contribute as much as I can to public labs.

**Comment by jywarren** [comment]
I'm so sorry to hear that! I believe we've solve this now, in fact. But
there are plenty more issues to work on!

**Comment by jywarren** [comment]
Looks like this didn't work??

**Comment by jywarren** [comment]
Indeed, this alternative mode of catching and filtering out replies does not seem to have worked, as you can still see the quotation text in this comment:

https://publiclab.org/questions/warren/10-26-2018/how-can-we-connect-a-pms5003-dust-sensor-to-an-arduino#a1252

We'd love help catching this type of reply!

**Comment by jywarren** [comment]
Moving to #5842 !
