### ISSUE TITLE
Ability to enable daily/weekly digests when subscribing to a tag (in alert link)

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3219]
Reporting in input from @ebarry -- When subscribing, people may often want to get only one email per day or per week, rather than the "firehose" of everything as it comes. So let's come up with a way to easily switch digests on at the moment of subscribing. Two ideas:

1. when you are redirected to htttps://publiclab.org/subscriptions, show a notice saying `you'll get approximately X emails per week. Click here to get only one per day, per week, or per month.`
2. have a checkbox when you click `Subscribe [ ]` so people can say "weekly digest" (or some other period -- see screenshot below)

![screen shot 2018-08-08 at 10 46 49 am](https://user-images.githubusercontent.com/24359/43844824-8fb0dbf2-9af8-11e8-8b4c-1a8b210c8512.png)

Other ideas welcome!

**Comment by jywarren** [comment]
A little ugly, but just trying this out! 

![screen shot 2018-08-08 at 10 50 55 am](https://user-images.githubusercontent.com/24359/43845010-fbe77704-9af8-11e8-8ca2-f6d18376e76c.png)

Also tracking this over here: https://publiclab.org/questions/warren/07-24-2018/looking-for-input-on-a-simplified-subscribe-design-for-publiclab-org-posts

**Comment by jywarren** [comment]
maybe @ViditChitkara would be interested in this one too? At least, i wonder what you think of how the design might work...

**Comment by ViditChitkara** [comment]
Sure, and yes we need to figure out the design.

**Comment by jywarren** [comment]
I think I'm going to close this as the UI seems a bit too complex...! Thanks!
