### ISSUE TITLE
Community Check-in #12 Summer Of Code Week 13

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#3222]
Hi everybody :smiley:  !

If you're new here, welcome, and please try some of our [first-timers-only issues](https://publiclab.github.io/community-toolbox/#r=all). This is a checklist for @publiclab/soc.

@stefannibrasil @milaaraujo @MargaretAN9 @Gauravano @ViditChitkara @tech4GT @mridulnagpal @namangupta01 @sagarpreet-chadha @Souravirus @jywarren @MayankKashyap @siaw23 @ryzokuken @ccpandhare @icarito @abTest-123 @steviepubliclab @ebarry @publiclab/soc @publiclab/reviewers

What is the plan for this week? 

If you have not planned yet, just leave a Hi! so that we could know that you are in sync with us :arrows_clockwise:

****

## Google Summer of Code timeline

As end to this awesome journey is near, let's review important dates so that we don't miss anything - 
 
📆 https://summerofcode.withgoogle.com/how-it-works/#timeline

⌨️ **Coding May 14, 2018 - August 6, 2018**

📥 **Students Submit Code and Final Evaluations August 6 - 14, 2018** - Students submit their code, project summaries, and final evaluations of their mentors.
(Here are Work Submission Instructions -  https://developers.google.com/open-source/gsoc/help/work-product )

📝 **Mentors Submit Final Evaluations August 14 - 21, 2018** - Mentors review student code samples and determine if the students have successfully completed their Google Summer of Code 2018 project.

🎉 **Results Announced August 22, 2018** - Students are notified of the pass/fail status of their Google Summer of Code 2018 projects.

As @jywarren mentioned in last check-in that he's going on vacation so @publiclab/soc, we all are required to pitch in:

* 👍 request `ready` labels from people for PRs ready to merge
* 🔧 restart stalled builds (related to our #2824 issue still being worked on)
* 📋 check in on new PRs and offer help, ask for tests and other things to fill out a good PR
* ✅ check stale/stuck [first-timers-only issues](https://publiclab.github.io/community-toolbox/#r=all) to see if people need help, or someone else can take over
* 👥 check on non-plots2 projects like these to see if people need help or input:
    * https://github.com/publiclab/leaflet-blurred-location-display
    * https://github.com/publiclab/image-sequencer
    * https://github.com/publiclab/leaflet-environmental-layers

****

This journey was absolutely full of Code :computer: , tasks :spiral_notepad:, fun :tada: and excitement :smiley:. And, now it's time to have a new experience with **Google Code-In**, so if you are excited to be a mentor. Acknowledge here #3168.

**OpenHour: Summer of Code Presentations** are available at YouTube  - https://youtu.be/aak8-z0njQY

![openhour_soc](https://user-images.githubusercontent.com/20878070/43868500-86a42242-9b8b-11e8-8637-c73669306714.png)

As always, if you're waiting for a review, or if you're stuck, please request help
here OR leave a comment with @publiclab/soc and @publiclab/reviewers for
some input.

Have a nice week :tada:  !
Thank you !

(closing #3167)

**Comment by jywarren** [comment]
❤️❤️❤️ this picture!!!! It was AMAZING to talk with everyone in real-time. THANK YOU and great check-in, @gauravano.

@cheneyshreve @imacubsfan23 @dewanhimanshu, @derek-allen, and others who've been pitching in recently - please do be aware that I'll be mostly offline next week and the following week, and that you can ask in the weekly check-ins for help from the `soc` team and `reviewers`. I'm going to invite you all to be collaborators on the project so you'll be able to mention `@publiclab/reviewers` and it'll send a notification. Thanks!

**Comment by SidharthBansal** [comment]
Hi everyone
Thanks Gaurav for amazing picture
I have written the documentation and filled my final evaluation. Sadly, my Ubuntu has crashed and I need to reinstall it and ror, plots2 and related stuff. So, the PR remaining of the usertag will take time. Sorry for delays.
Thanks mentors and other students for giving a wonderful journey of Gsoc. It is a great experince working with you all.

**Comment by milaaraujo** [comment]
Hey everybody!

It was great talking to you guys this week! Seeing everything you accomplished during those GSoC weeks was very motivating.

This week, @stefannibrasil and I expect to finish #3134 and #3217. And we will be working on improving JSON tests.

**Comment by Souravirus** [comment]
Hello everyone!!
It was nice talking to you this week. So, since GSoC is going to over, I wanted to say it was a very overwhelming journey. Full of codes, excitement and everything. :tada: :tada: 
So, related to my progress, I am working on yarn transition and its almost complete. Also, did a fix on route this week. I am also working on my GSoC work product and hopefully release it by today or tomorrow. 
Thanks!!
