### ISSUE TITLE
Community Check-in #13 Summer Of Code Week 14

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#3225]
Hi everybody :smiley:  !

If you're new here, welcome, and please try some of our [first-timers-only issues](https://publiclab.github.io/community-toolbox/#r=all). This is a checklist for @publiclab/soc.

@stefannibrasil @milaaraujo @MargaretAN9 @Gauravano @ViditChitkara @tech4GT @mridulnagpal @namangupta01 @sagarpreet-chadha @Souravirus @jywarren @MayankKashyap @siaw23 @ryzokuken @ccpandhare @icarito @abTest-123 @steviepubliclab @ebarry @publiclab/soc @publiclab/reviewers

What is the plan for this week? 

If you have not planned yet, just leave a Hi! so that we could know that you are in sync with us :arrows_clockwise:

****

## Google Summer of Code timeline

As end to this awesome journey is near, let's review important dates so that we don't miss anything - 
 
📆 https://summerofcode.withgoogle.com/how-it-works/#timeline

⌨️ **Coding May 14, 2018 - August 6, 2018**

📥 **Students Submit Code and Final Evaluations August 6 - 14, 2018** - Students submit their code, project summaries, and final evaluations of their mentors.
(Here are Work Submission Instructions -  https://developers.google.com/open-source/gsoc/help/work-product )

📝 **Mentors Submit Final Evaluations August 14 - 21, 2018** - Mentors review student code samples and determine if the students have successfully completed their Google Summer of Code 2018 project.

🎉 **Results Announced August 22, 2018** - Students are notified of the pass/fail status of their Google Summer of Code 2018 projects.

As @jywarren mentioned in last check-in that he's going on vacation so @publiclab/soc, we all are required to pitch in:

* 👍 request `ready` labels from people for PRs ready to merge
* 🔧 restart stalled builds (related to our #2824 issue still being worked on)
* 📋 check in on new PRs and offer help, ask for tests and other things to fill out a good PR
* ✅ check stale/stuck [first-timers-only issues](https://publiclab.github.io/community-toolbox/#r=all) to see if people need help, or someone else can take over
* 👥 check on non-plots2 projects like these to see if people need help or input:
    * https://github.com/publiclab/leaflet-blurred-location-display
    * https://github.com/publiclab/image-sequencer
    * https://github.com/publiclab/leaflet-environmental-layers

****

This journey was absolutely full of Code :computer: , tasks :spiral_notepad:, fun :tada: and excitement :smiley:. And, now it's time to have a new experience with **Google Code-In**, so if you are excited to be a mentor. Acknowledge here #3168.

As always, if you're waiting for a review, or if you're stuck, please request help
here OR leave a comment with @publiclab/soc and @publiclab/reviewers for
some input.

I will be writing the remaining tests this week. And looking at which issues needs to be addressed in Google Code In(GCI)

Have a nice week :tada:  !
Thank you !

(closing #3222)

**Comment by gauravano** [comment]
Hi @publiclab/soc,
I am done with my work product submission and here's note - https://publiclab.org/notes/gauravano/08-12-2018/gsoc-2018-final-work-product-of-draft-feature-and-email-integration-project . Please provide your valuable feedback.

**Weekly Update:** 
I am working on the last setting of the Email Subscribtion settings project which is Unsubscribe from 
  Q & A  
Issue #1610 
PR raised at #3220 .
I would also be resolving issues in Email notification milestone, after completing above PR.
Thanks!

**Comment by stefannibrasil** [comment]
Hi, everyone! This week @milaaraujo and I are going to wrap our work with our two big PR's #3134 and #3217. We plan to call them on the feed RSS methods, so we decrease the amount of duplicated code around the codebase.

After that, we are going to move on to write unit tests for the search API.

**Comment by jywarren** [comment]
Hi, all! Brief check in from vacation -- for API code, just a note that you
can monitor performance of different parts of the app using Skylight:
https://oss.skylight.io/app/applications/GZDPChmcfm1Q/recent/5m/endpoints

(recently installed thanks to @siaw23!)

**Comment by Souravirus** [comment]
Hi everyone! I have submitted my final evaluation. So, currently I am working with the yarn transition and it is still not complete. There were some errors while pushing it to unstable. Any help is appreciated at #2659. Also, I think I will be starting with the work with graph possibly by today. 
So, thanks for such a wonderful summer everyone.

**Comment by ebarry** [comment]
These check-ins are great, and i think Sidharth has a real knack for
community management!
Happy Tuesday everyone :D

--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net

**Comment by stefannibrasil** [comment]
@siaw23 can we add the API endpoint here as well? https://oss.skylight.io/app/applications/GZDPChmcfm1Q/recent/5m/endpoints

**Comment by siaw23** [comment]
you mean those Grape endpoints right? @stefannibrasil well they should be showing once those endpoints are hit. i see those are the only endpoints not registering, i've just sent an email to Skylight for support.

**Comment by jywarren** [comment]
Hi, all! Since we have a priority fix on the answer formatting now merged in https://github.com/publiclab/plots2/issues/3232, i'd like to push this to production. I've just pushed to https://stable.publiclab.org and since we've had some API changes and I'm not as available, I'd like to ask folks to try the site out (especially focusing on new code you've had merged) before we push it to production. Thanks! @publiclab/soc

**Comment by jywarren** [comment]
(should take a few minutes to build!)

**Comment by jywarren** [comment]
Hmm, looks like it failed! I'm seeing: `An HTTP request took too long to complete. Retry with --verbose to obtain debug information.` 

https://jenkins.laboratoriopublico.org/job/Plots-Stable/lastFailedBuild/console

I wasn't able to figure out where it got this response, but it had gotten past building containers and was in the `+ make deploy-container` segment. @icarito any ideas? I've started it again.

**Comment by jywarren** [comment]
Hmm, failed again... 

```

ERROR: for containers_redis_1  Cannot start service redis: transport is closing
[1A[2K
Creating containers_db_1 ... [31merror[0m
[1B
ERROR: for containers_db_1  Cannot start service db: grpc: the connection is unavailable

ERROR: for db  Cannot start service db: grpc: the connection is unavailable

ERROR: for redis  Cannot start service redis: transport is closing
Encountered errors while bringing up the project.
Makefile:24: recipe for target 'deploy-container' failed
```

I wonder if something is up with the network connections between the containers?

**Comment by jywarren** [comment]
Also, heads up everyone! Tomorrow is Rails Girls Summer of Code Burnout Awareness Day! Even if you're not in RGSoC perhaps it's a thing to think about. I wasn't able to find this year's announcement, but here's a great one from a few years ago, with a list of 10 things to to do instead of code:

https://railsgirlssummerofcode.org/blog/rgsoc-day-off

@publiclab/SoC

Please always take good care of yourselves, it's far more important than the projects we do together even if we're passionate about them.

**Comment by jywarren** [comment]
@publiclab/soc just being sure the notification got sent for the above note!

**Comment by Souravirus** [comment]
Yeah that's a nice note about chilling a day out :smile: :smile:

**Comment by namangupta01** [comment]
Hey all, Sorry for not being active this week...i was busy in my college placements. I will test reply-by-tweet feature in this and coming week on unstable so that we can merge this and make it live soon. 🎉 🎉

**Comment by sagarpreet-chadha** [comment]
Hi all !!!
I was too busy with college placements...hopefully i will be more active next week . Thanks !

**Comment by SidharthBansal** [comment]
Hi, who is going to open the next week's Community Check - in?
@publiclab/soc

**Comment by milaaraujo** [comment]
I can do it, @SidharthBansal!

**Comment by SidharthBansal** [comment]
Go for it

**Comment by milaaraujo** [comment]
Moved to #3241

**Comment by icarito** [comment]
Hi @jywarren (hope you are having a pleasant vacation!) and everyone, the issue with Jenkins was that `unstable` and `stable` (and now `testing`) were sharing the container namespace so they interfered with each other. Once I separated them in Jenkins by tagging the containers with the DOCKER_COMPOSE_PROJECT environment variable, I had to fix a couple of issues but it is working now (https://github.com/publiclab/plots2/pull/3253 - please merge).

In any case Jenkins should work now.

Also, it looks like #2824 should be fixed once #3253 is merged!

**Comment by SidharthBansal** [comment]
This is great news sebastian

**Comment by stefannibrasil** [comment]
good work, @icarito !
