### ISSUE TITLE
Adding Link to mark comment as spam to Dashboard Comment display

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#3226]
Add the comment moderation link  `<a href="/admin/mark_comment_spam/<%= @comment.id %>">Spam</a>` with icon to comment view on dashboard.
 
![demo](https://user-images.githubusercontent.com/20878070/44006376-497e1972-9ea1-11e8-95c3-599d0a2258ce.png)

Like above comment notification on the dashboard is showing `3 comments as a link`, we like to have a link (may be adjacent to it ) to mark the notified comment as spam. 

Here's the file where change is required https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_node_comment.html.erb

This would close https://github.com/publiclab/plots2/issues/3183 completing it. Thanks!

**Comment by gauravano** [comment]
Hey, @qm3 you might be interested in solving this. Thanks!

**Comment by qm3** [comment]
@gauravano I will take a look at it. Thanks for giving me this issue!

**Comment by qm3** [comment]
Hi @gauravano, in the last issue you suggested that I read the checklist of PR body and reflect the changes in raising PR process. Did you mean that I should comment under the PR checklist body and comment about those changes? Thanks!

**Comment by gauravano** [comment]
Just to be clear it was just a friendly suggestion and not much of big concern, I advise people to follow because it eases the whole process for future PRs and all. Let's walk through the checklist and see how following it is beneficial: 

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test` ------ > This step lets one know that whether change done by him/her is giving any error or not. But, one can skip this step as running test locally most of the time gives error

* [x] code is in a uniquely-named feature branch and has no merge conflicts ----- > Your last PR was on the master, and that can irritate you in future so creating a new branch and then raising PR can ease the task
* [x] PR is descriptively titled ---> This one is just for clarity 
* [x] PR body includes `fixes #0000`-style reference to original issue # ----- > This automatically closes the issue number mentioned 
* [x] ask `@publiclab/reviewers` for help, in a comment below   ---- >  For asking for the review 

These are just suggestions (from my little experience) and you are free to avoid them too. Your last PR was awesome :100: and you really helped a lot! Thanks @qm3 !

**Comment by gauravano** [comment]
I have also added the link to the file where change is required, feel free to ask if there is any doubt. Thanks!
