### ISSUE TITLE
line breaks in answers broken. 

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#3229]
Hi, I believe Jeff mentioned this might already be reported, but I can't find it. The line breaks in the /questions section of Public Lab don't appear to be working. They are in the written text, but aren't showing up when it's published. Here are a couple examples::

- Answers here: https://publiclab.org/questions/stevie/08-01-2018/where-can-we-share-well-water-data
- Answers here: https://publiclab.org/questions/belkinsa/08-11-2018/d-o-monitoring-on-public-lab

It appears that not all of the question/answers are affected by this, here's one that appears fine: 
- https://publiclab.org/questions/belkinsa/07-18-2018/are-there-any-diy-equipment-that-measure-dissolved-oxygen-levels-in-water

**Comment by gauravano** [comment]
Hi @steviepubliclab, please check out this https://drive.google.com/open?id=1WJtBopv0Y7dPEtR99SkUr2-iW-DAHAc1 . Is time after the code is changed correct behaviour ?? Thanks!
