### ISSUE TITLE
"+Add one now" button to create a lead wiki page from Tag Pages does not work

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#3236]
Hi folks! tiny thing i just ran into -- 

### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I visited publiclab.org/tag/lead and clicked the "Add one now" button and nothing happened. 
<img width="304" alt="screen shot 2018-08-16 at 10 57 50 am" src="https://user-images.githubusercontent.com/161439/44216735-9fc26c80-a143-11e8-87ee-a9bc24f337f0.png">

> What did you expect to see that you didn't?

I expected to load an editor with the prefilled URL publiclab.org/wiki/lead and be able to start creating content. 

### Please show us where to look

https://publiclab.org/tag/lead

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

liz

**Comment by ebarry** [comment]
UPDATE: i've actually gone ahead and created the main wiki page for lead, so this example might not work anymore. See https://publiclab.org/tag/water instead. thanks!

**Comment by Souravirus** [comment]
Yeah same here I  also got this some time ago when I was adding a lead wiki page (while working with #3234) in localhost @ebarry. Have to see the problem behind it.

**Comment by shubhscoder** [comment]
@ebarry do you wish to be redirected to the page shown in the screenshot below after clicking on "+Add one now" ? 
![wikinewpage](https://user-images.githubusercontent.com/18489285/45098234-329e6780-b142-11e8-8feb-536dd1cb51a2.png)

If yes then I think I can fix this!

**Comment by jywarren** [comment]
Hi! I think the idea is that when going to a page like
/wiki/some-page-name, and that wiki page doesn't exist, that it shows the
form and prompts you to make that page. This is how it used to work --
non-existent pages showed a form to create that specific page. We must've
unintentionally changed this in our tag redirects -- i attempted a fix here
but it didn't work: https://github.com/publiclab/plots2/pull/3189

I'd LOVE some help with this!

**Comment by jywarren** [comment]
Does this make sense @shubhscoder -- that we'd display the template for `/wiki/new` but on the URL for `/wiki/________` (where `______` is a non-existent wiki page)?

**Comment by shubhscoder** [comment]
In file app/views/tag/show.html line number 36 where href points to something weird. I think it should link to wiki/new/

**Comment by shubhscoder** [comment]
Yeah I think that should work @jywarren .

**Comment by jywarren** [comment]
So, i think it should link to /wiki/<%= params[:id] %> so that it prompts
you to create a new page at that address. But it's what happens at that
address that's broken, and that should be worked out at the lines of code
in my pull request -- take a look!

**Comment by jywarren** [comment]
super -- thank you!

**Comment by shubhscoder** [comment]
No problem. Are there any more such issues that can be worked out ?

**Comment by jywarren** [comment]
Ah, sorry, i mean to say that my PR /attempts/ to solve the problem in this way, but I encountered some errors and test failures and think I did it wrong. I'd LOVE some help resolving those if you want to take my PR as a starting point?

**Comment by shubhscoder** [comment]
Yeah sure I can try that!
If you simply link it to wiki/new then it would open up the post edit window without any default information and that is not desired right?

We want it to autofill the create page textbox with params[:id] i.e the name of wiki page that was requested and not found ?

Please correct me if I haven't misunderstood the issue. Thanking you. :)

**Comment by jywarren** [comment]
That's right. I think we /could/ redirect to /wiki/new?title=_____ to offer
default info... so /wiki/newpagename would redirect to
/wiki/new?title=newpagename if that page doesn't already exist.

**Comment by ebarry** [comment]
Would this be a good issue for Google Code In? Or maybe we're already on the way to wrangling it ourselves......

**Comment by jywarren** [comment]
@shubhscoder I think that's up to you -- have you begun work on this one? We'd love your help!
