### ISSUE TITLE
Community Check-in #14 Summer Of Code Week 15

### ISSUE THREAD

**Issue by milaaraujo** [publiclab/plots2#3241]
Hi everybody :smiley:  !

If you're new here, welcome, and please try some of our [first-timers-only issues](https://publiclab.github.io/community-toolbox/#r=all). This is a checklist for @publiclab/soc.

@stefannibrasil @milaaraujo @MargaretAN9 @Gauravano @ViditChitkara @tech4GT @mridulnagpal @namangupta01 @sagarpreet-chadha @Souravirus @jywarren @MayankKashyap @siaw23 @ryzokuken @ccpandhare @icarito @abTest-123 @steviepubliclab @ebarry @publiclab/soc @publiclab/reviewers

What is the plan for this week? 

If you have not planned yet, just leave a Hi! so that we could know that you are in sync with us :arrows_clockwise:

****
Last week, @stefannibrasil and I, finished the profile endpoint in the Search API. Now it is possible to search only by username. We are waiting someone to review our PR #3235.

This week we will finish the unit tests for SearchService class methods. And we are also going to work on refactoring the author rss feed to receive data directly from search profile endpoint.

****
As always, if you're waiting for a review, or if you're stuck, please request help
here OR leave a comment with @publiclab/soc and @publiclab/reviewers for
some input.

Have a nice week :tada:  !
Thank you !

(closing #3225)

**Comment by jywarren** [comment]
Congratulations to the GSoC folks who just finished up! I posted a longer thank you and congrats here: https://publiclab.org/notes/warren/08-21-2018/congratulations-on-a-great-2018-summer-of-code

🙌 ⚡️ 🎉  @publiclab/soc

**Comment by SidharthBansal** [comment]
Thanks everyone for giving me this opportunity and helping me to fulfil it.

**Comment by SidharthBansal** [comment]
Hi @publiclab/soc,
Sagar and I are hosting an event at DTU, India on Monday. You all are welcomed to attend the event.
https://www.facebook.com/events/1061331190699995/?notif_t=plan_user_joined&notif_id=1536071494915419
Thanks
