### ISSUE TITLE
Remove "hasn't been edited in a while" blue banner from automatically appearing on wikis

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#3244]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I have been noticing the blue header at the top of wiki pages that haven't been edited in a while, perhaps longer than 6 months: 
`This wiki page hasn't been edited for a while. If you see anything that needs updating, please help out!`

Since all wiki pages already display the last edit date in the "toolbar" area, i suggest we remove this alert. 

> What did you expect to see that you didn't?

I expected to read the page without this distracting alert

### Please show us where to look

https://publiclab.org/wiki/h2s

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

liz

**Comment by shubhscoder** [comment]
I would like to take up this issue. Would you please guide me through @ebarry ? Thanking you in advance!

**Comment by shubhscoder** [comment]
I have made changes to the code,installed required gems on my local machine. Can someone please guide me on how should I test the made changes locally,because I haven't setup my Database yet. If someone could guide me on setting up my database,it would be very helpful. Thanking you in advance!

**Comment by pdurbin** [comment]
I just took a look at pull request #3260 and it looks good to me. Thanks, @shubhscoder 🎉 👍

**Comment by jywarren** [comment]
This looks great. @ebarry it'd be great if you could think about other ways we might encourage people to keep stale pages up to date, which was the original intent of the notice -- thanks!

**Comment by jywarren** [comment]
Thanks, all, and thanks to @pdurbin for reviewing!
