### ISSUE TITLE
redirect /question to /questions

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#3247]
I'm worried people are ending up on the www.publiclab.org/question which redirects you to www.publiclab.org/tag/questions. I think people who go to this page are probably trying to get to www.publiclab.org/questions. Can we get a redirect set up for that page?

**Comment by shubhscoder** [comment]
I am a newbie to open source and would like to take up this issue. Please guide me throught @steviepubliclab . Thanking you in advance!

**Comment by steviepubliclab** [comment]
Hi Shubham- Thanks for pinging in here!
I'm actually not a coder, so can't help you with any of that, but I can
explain more about what I'm hoping for if that's helpful? If you'd like
support on coding/getting started, check out
https://publiclab.github.io/community-toolbox/

**Comment by jywarren** [comment]
Hi, @shubhscoder -- welcome, we'd love your help with this and would be happy to support you if you could take up this issue. This could be solved either by modifying the wiki controller's `root` method:

https://github.com/publiclab/plots2/blob/39cfd13cb2ba6cba81ddc0abd2ce56d8ceefd3b7/app/controllers/wiki_controller.rb#L249-L264

Or by making https://publiclab.org/question actually display the same thing as /questions, by creating a new route in this file: 

https://github.com/publiclab/plots2/blob/39cfd13cb2ba6cba81ddc0abd2ce56d8ceefd3b7/config/routes.rb#L279

Either way is fine. Have you been able to install this project locally and get it running yet? 

Thanks all!

**Comment by shubhscoder** [comment]
Yes Jeff the system is running on my system , thanks to steffani . I ll
surely try that👍👍

**Comment by jywarren** [comment]
This was solved, thanks!!!
