### ISSUE TITLE
page not showing up even though it's tagged. 

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#3248]
I was looking at this page https://publiclab.org/wiki/tag/community-organizing and noticed that one of the related wiki pages (https://publiclab.org/wiki/creating-a-media-campaign) wasn't showing up, even though it has the same "community-organizing" tag.

**Comment by ebarry** [comment]
We tried removing and re-adding the tag, no effect. 
We also tried untagging another page that was showing up in case the display was limited to four results, no effect.

**Comment by jywarren** [comment]
ok, weird - my brain's too tired right now, but using `[wikis:community-organizing]` does work on this page:

https://publiclab.org/wiki/sandbox#Barnraising

The code driving https://publiclab.org/wiki/tag/community-organizing should be here:

https://github.com/publiclab/plots2/blob/a9a762f6901e073b947dcc9a9e62f7757b6e6dee/app/controllers/tag_controller.rb#L120-L125

versus this for the test I made using the `[wikis:____]` tag:

https://github.com/publiclab/plots2/blob/a9a762f6901e073b947dcc9a9e62f7757b6e6dee/app/models/concerns/node_shared.rb#L287-L291

**Comment by jywarren** [comment]
Believe i found it and opened a PR. We'll see!

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/pull/3269

**Comment by jywarren** [comment]
Hmm this fix did not work! must test more.

**Comment by jywarren** [comment]
This is an iteration of https://github.com/publiclab/plots2/issues/7334 which is now solved!

**Comment by jywarren** [comment]
Hmm, not looking right on live site, reopening... could it be we need to update `tag.run_count` as in https://github.com/publiclab/plots2/issues/8244#issuecomment-668856800?

**Comment by jywarren** [comment]
Oh wait, the live site didn't pull the latest changes. Need to recheck the current commit on the live site and this could indeed be solved...

**Comment by jywarren** [comment]
All good now it's properly published!
