### ISSUE TITLE
system for listing things "this page needs" such as citations or dejargoning

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#326]
this'd be tags, but maybe a menu of standard tags and a standard set of alert styles at top of page

We could use tags to do this -- so, add a tag like `needs:___` for the different types of needs, which would then show a notice at the top of the page, in an alert. 

We need to make a list of these types of messages!

**Comment by aspriya** [comment]
@jywarren, I would like work in this one. But Could you explain little bit more.

**Comment by gauravano** [comment]
@jywarren please add more details to this issue. Thanks!

**Comment by jywarren** [comment]
What if we made it possible to add alerts that display the content of a
Feature, using `alert:featurename` syntax, and so we could add as many
types as we wanted, by adding new features with those names?

**Comment by gauravano** [comment]
Surely, we can try this. Should I make a new issue for this? Also, with which page you want to try this out first? Thanks!

**Comment by jywarren** [comment]
This'd be great! I think we'd add to the view a conditional checking for
`node.has_power_tag('alert')` (i think) and then inside the conditional,
the alert HTML and the features lookup!

**Comment by gauravano** [comment]
Yes, that makes sense. As we would be showing this feature alert only when `alert` tag and alert body exists as feature. So, by which name should we check in the features list for such alerts? Something like `alert-[nodeid]`?

**Comment by jywarren** [comment]
Well we could make it be the name of the feature, no? Then it'd be more
readable. Thanks!

**Comment by gauravano** [comment]
Oh, I thought, we want different alert for each node but yeah, using the name is better as we would be using same alert for multiple nodes.

I have created new issue at https://github.com/publiclab/plots2/issues/5327. Closing this now. Thanks!
