### ISSUE TITLE
Typeahead search api returning 404?

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3264]
@stefannibrasil @milaaraujo no rush as I haven't pushed this to production, but it looks like in the midst of all the search changes maybe something went wrong? 

`Failed to load resource: the server responded with a status of 404 (Not Found)` for https://stable.publiclab.org/api/search/all?srchString=balloon

Do we need to update a route in the autocomplete javascript to match a new route in the API?

Thanks!

**Comment by jywarren** [comment]
btw go this while using the navbar typeahead search in https://stable.publiclab.org

**Comment by stefannibrasil** [comment]
ohhh, I updated the route but it's `/api/srch/all?` instead of `api/search/all`. I already fixed it #3266

If you try https://stable.publiclab.org/api/srch/all?srchString=balloon you get the results. Thanks, @jywarren 

I was able to see the icons locally as well after modifying this.

**Comment by jywarren** [comment]
super, thanks!
