### ISSUE TITLE
Inline tags don't work unless there is text before them (regular expression issue)

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#3267]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I created https://publiclab.org/community with only a body tag in the text field `[wikis:community]`

> What did you expect to see that you didn't?

I expected to see the grid of wikis appear in the page (as it does currently), but instead all that appeared was the plain text of the body tag [wikis:community]

### Please show us where to look

https://publiclab.org/community

**Comment by jywarren** [comment]
Thanks for documenting!

This is driven by this code:

https://github.com/publiclab/plots2/blob/d9bbfad620baa7306d4eb9d7c5f03a06a23cf7bb/app/models/concerns/node_shared.rb#L279

And here is an example in Rubular of how this regular expression (regex) does not properly match the string when it's the first thing in a body of text:

http://rubular.com/r/zr0jpBnkiI

To get it to match, type anything before `[wikis:TESTING]` and it'll start finding the string.

**Comment by jywarren** [comment]
So the next step here might be to try to read Regular Expressions documentation and experiment with Rubular to try to get the expression to match the string even if it's the beginning of the sample text!

**Comment by KauNair** [comment]
There is another fault with this regex
It will also replace any character before `[wikis:community]` except for the \` and > characters. You can check an example [here](http://rubular.com/r/zr0jpBnkiI)
However I do not understand the purpose of replacing the <p> tag here. 
@jywarren can you help me out here?

**Comment by jywarren** [comment]
Hmm, we can check the blame view to see if it was in response to a specific bug. In theory we should have a test demonstrating and annotating the reasoning :-/ 


There is a bit of documentation on the purpose of power tags here: https://publiclab.org/power-tags

Let me check the blame file!

**Comment by jywarren** [comment]
I believe this was intended to ensure that this inline power tag only works when not preceded by HTML tags of any kind - it should be the first thing on a given new line. But it needn't replace the characters, it can ideally just not perform the replacement of the `[...]` portion if it encounters them. I think we ought to adjust the unit tests in `test/unit/node_share_test.rb` (i believe) to reflect this.

**Comment by jywarren** [comment]
You can see here: 

https://github.com/publiclab/plots2/blame/d9bbfad620baa7306d4eb9d7c5f03a06a23cf7bb/app/models/concerns/node_shared.rb#L279 

and trace it back to this PR: https://github.com/publiclab/plots2/pull/1959

But it doesn't offer details about this. I bet this was originally developed for a different regex in the same file and we could likely trace the discussion back using the blame view in a similar way...
