### ISSUE TITLE
Inline maps need url hash feature disabled from LEL

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3272]
@sagarpreet-chadha would you mind submitting a fix for this? I think the URL hash feature is great but i think we need to make it be default-off, and re-enable it for pages where we want it (publiclab.org/maps, publiclab.org/people, mapknitter.org, etc) and not for inline maps. It looks like it causes some trouble esp. when there are multiple maps!

https://publiclab.org/wiki/inline-maps

**Comment by sagarpreet-chadha** [comment]
Okay...working on this :+1:  .
