### ISSUE TITLE
Comment posting error

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3273]
i tried to post this comment:

`This was fixed by @gauravano and is now live!`

On this page: https://publiclab.org/questions/stevie/08-14-2018/what-are-ways-to-monitor-algae-blooms#c20404

And got a 500 error. Not sure why -- need to pull the logs! If anyone can reproduce this locally we could probably fix quickly. Thanks for any help!

```
GET https://publiclab.org/comment/answer_create/1129?body=This+was+fixed+by+%40gauravano+and+is+now+live!&_=1535553099274 500 (Internal Server Error)
```

**Comment by jywarren** [comment]
aha, so you think it's the email service being down that causes this? Yes,
that moment tagging you all sounds very similar. I did see a problem at
that time too.

**Comment by gauravano** [comment]
yes, email service being down seems to be one of the reason.

Do you think we can use Redis to solve this, we can enqueue our emails using redis, this will also decrease the page loading time after signup or after every operation where response waits for email to be sent. We should only use this solution if Redis is working stable at all times.

**Comment by jywarren** [comment]
Has Redis been quite stable, or at least more stable than mailman? @icarito
?

**Comment by jywarren** [comment]
I haven't seen this happen recently...

**Comment by jywarren** [comment]
OK noting that this `mailman` monitoring project is ongoing here: https://github.com/publiclab/plots2/issues/3208

**Comment by jywarren** [comment]
Closing in favor of that issue!
