### ISSUE TITLE
Design Notification System for PL

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#3283]
### Please describe the problem (or idea)
We can have a notification system at Public Labs in the header.  We currently don't have such notification system. We usually notify people via email. We can notify them like facebook, linkedin etc does.
![image](https://user-images.githubusercontent.com/20972099/44945257-c69ac700-ae02-11e8-8dd6-635b48f61c06.png)

**Comment by SidharthBansal** [comment]
@publiclab/reviewers @publiclab/soc any ideas about this is much appreciated.

**Comment by siaw23** [comment]
would be a pretty cool feature. i'm for it. this will be done with action cable i believe?

**Comment by SidharthBansal** [comment]
@souvaris can we use rails 5 stuff? I think we need to use action cable. I
was guessing if we can try to implement this whole project by google code
in students
Can you assist them in doing so?
As we are planing for gci. It will be Great if they will build something.

**Comment by SidharthBansal** [comment]
We will definitely create a large list of issue, but if we will break one or two bigger projects to them it will also help the pl community. What do you say @siaw23 @jywarren. Yeah @siaw23 you can go for it. Let's also hear from other community members what they are looking for.

Btw this will be a big project. We also need to have a web page for showing all the notifications.

**Comment by siaw23** [comment]
uuum won't this be too big for GCI students? well sure i can help with overseeing this if we can have a clear plan what to set notifications for.

**Comment by jywarren** [comment]
Wow, very cool! Actually i wonder if it could be implemented via the Notifications API - that way it can work on phones too:

https://github.com/publiclab/plots2/issues/2497

Or is this what action cable does? I'm not familiar with it!

**Comment by SidharthBansal** [comment]
Helpful links
https://gorails.com/episodes/in-app-navbar-notifications
https://www.youtube.com/watch?v=87fBAWc25Sk
I am trying to learn this stuff first. @siaw23 if you know the notification stuff we can move according to your strategy.
Thanks all

**Comment by siaw23** [comment]
I think the first link is using AJAX. There's a better way. We should use web sockets with Action Cable instead, comes with Rails 5. The second link is something completely different, just plain flash messages. That's not what we want. Are you going to build this or a GCI student again? One important thing worth defining is for WHICH events do we want the notifications? I think that needs to be spelled out, do we want notifications for mentions? new posts? new replies? Then based on that we can design this from scratch.

**Comment by SidharthBansal** [comment]
@jywarren can you please tell whether we need this feature or not? And what
all will we need to include in notifications?
Also do we make it into smaller subtasks for gci or take this project
entirely differently?

OK we can implement it with action cables.
Thanks folks

**Comment by jywarren** [comment]
Hi, please check out the link I shared to the Notification API - it uses
neither AJAX nor web sockets, and is built into the UI of many smartphones
and OSs now. I believe it /may/ use AJAX or web sockets to fetch, but I
think it makes the most sense as the UI of this system.

Can you look at how this might integrate with a back-end? Is the interest
in Action Cable to avoid polling the server to "check for new
notifications"?

Thanks!

**Comment by jywarren** [comment]
I'm going to merge this into #2497! Thanks!
