### ISSUE TITLE
"Weighting" system for Google Code-In

### ISSUE THREAD

**Issue by tech4GT** [publiclab/plots2#3284]
I suggest after a discussion with @SidharthBansal to have a Bounty system on issues throughout GCI to track the student performance.
We can have these bounties as labels on the github issues we will raise during GCI and the bounty shall vary on how big or complex the issue is.
I think these slabs should be enough to cover issues of all complexities.
50
100
150
200
250
300
350
400
450
500

So we can create labels like `bounty:50` and so on
This will help us keep it fair so that someone working on a very complex issue is compensated properly. @publiclab/reviewers please give your suggestions on this.
This is in concert with #3168 and #3276

**Comment by SidharthBansal** [comment]
Varun the bot has errors. You are not a newbie. lol. 
Thanks for opening the issue.

**Comment by tech4GT** [comment]
Oh it's fine this is my first issue on plots😄

**Comment by SidharthBansal** [comment]
@tech4GT can you please divide these bounties in some categories. So that it will be easy for GCI mentors to tag them up

**Comment by SidharthBansal** [comment]
Like writing a page of documentation will have x bounties, making a button ui will have y bounties, implementing that button will have higher bounties and all that. So that we will have a fair system

**Comment by tech4GT** [comment]
Oh sure we can do that once @jywarren and others approve of this system. Is that fine?

**Comment by SidharthBansal** [comment]
Also, I will say that instead of ten we can have fewer levels say 3/4 levels of bounty. It will be quite easy to pick from 3/4 bounty levels then from 10 bounty levels.
Like we can have 100 250 and 500

**Comment by SidharthBansal** [comment]
yeah other reviews are really important

**Comment by tech4GT** [comment]
Yeah we can work out the details once everyone on the team is OK with this.

**Comment by ebarry** [comment]
Wow interesting. Can someone explain what bounties mean? 

I would like to relate this concept to the concept that is currently in my head, which is --- Broadly in Public Lab (as in the environmental research part), we try to reward all contributions equally, to overturn some of the exclusivity that builds up in domains of expertise. 

Thank you for any explanations you can add!!!! <3!

**Comment by jywarren** [comment]
Yes, I've been thinking hard on this one for a few days, and my main worry would be that some people might consider certain types of work to be "worth more" in a way that might not be fair, even by mistake or oversight. It's a tough thing to figure out what is worth more or less or what's easier or harder for people. 

Definitely there are some tasks that just involve lots and lots of lines of code to write. But just because these are easier to quantify as "harder" doesn't mean that we can ignore the kinds of tasks that might take a lot of invisible work. So while I love the goal of this (fairness), I'm cautious!

**Comment by tech4GT** [comment]
Hi @ebarry
Actually bounties are like points that you get on completion of a task. So the bigger the task the more the points(bounty). The idea is to create labels on GitHub issues which will clearly tell the contributors how much points they will get on solving that issue. We can then take our descision based on the points earned rather than number of issues solved. This should be more fair to people who would be solving relatively complex tasks.

**Comment by tech4GT** [comment]
@jywarren you are right, we would have to be very careful while setting the bounties. This should not be a problem if bounties are set on a project by mentors who are very well versed with it, what say?

**Comment by SidharthBansal** [comment]
@jywarren your concern is right. I thought about this thing. For me may be
technology t1 is tough and technology t2 is easy but for other guy it may
be opposite. So, I agree that hard and easy are relative terms.
Just trying to make the competition transparent to students

**Comment by SidharthBansal** [comment]
I will say that we can have 2 categories or three. Like very basic category
in which 50 points (/bounties/score) is given to candidate. 250 who does a
fairly big task.
Usually people make many small one liner edits at many places and the no of
commits for them is higher than those who did a big patch of 500 lines. So,
the judging criterion should be fair.

Like front end images can be 50, implementing a feature with test is 250.
There will be a significant difference in the points which will help us to
decide the winner

**Comment by SidharthBansal** [comment]
My main focus is how will we decide the winner. This decision should be
transparent and fair as per the spirit of competition. We can do this
either by bounty system or by simply lines of code or by number of PRS
merged+ number of issues opened.

**Comment by jywarren** [comment]
> I will say that we can have 2 categories or three. 

I like this to keep the labels more minimal -- and to think about the kinds of work that makes it a "big" one -- imagine they do one of this list, two of the list, or three of:

1. code change (<10 lines)
2. code change (10+ lines)
3. back-and-forth discussion with community for input
4. install and take a screenshot of the feature
5. write a test
6. write documentation

This not as a formal rule but as a rough guide... what do you think? Any others?

If they do 1, it's "small" -- if they do 3, it's "medium" and if they do more than five, it's "large"?

if students help each other out, or are extra friendly, maybe we can assign extra points using a label like `teamwork`?

**Comment by SidharthBansal** [comment]
So this means we will have an excel list type of spreadsheet where we will assign points to folks?

**Comment by SidharthBansal** [comment]
We also need to think of a feasible way to evaluate. If we will assign points for community bonding then this would be really tough for us to keep a check.

**Comment by jywarren** [comment]
Sure, i think this is reasonable. Just trying to come up with a quick way to evaluate "task size"

**Comment by jywarren** [comment]
I am going to make `small` `medium` `large` tags to help us if we need. This can be a hybrid - consider both lines of code, but also when needed, use these tags to help recognize kinds of work that aren't reflected in the lines of code. Maybe the student did a lot of research outside, or talked a lot with community to investigate a problem. Maybe they are making FTOs or something else which doesn't result in new lines. In these cases, we can use the "weighting" tags to help guide evaluation. 👍

**Comment by jywarren** [comment]
Closing as I've updated the main description on the task list issue!
