### ISSUE TITLE
Project Oriented Flow in GCI

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#3285]
@jwarren I have a cool idea. I don't know it's feasibility level. Please help @publiclab/soc.

We have pending projects/new projects at PL. We will have mentors for GCI. We all want to do projects as many as we can to learn. So, I want to map these things together.

Like in GSOC and RGSOC, we can assign a project to a team of mentors(team of mentors can include even one mentor) and the project is completed by the students. We can apply the same approach here at GCI. But with one twist. Many students will be contributing to the same project instead of one. Any student can do any amount of work in any project. The project will be completed within the period of GCI by the students of GCI under the assistance of mentors. The mentors can break that project into smaller issues and subissues. These issues will be solved by the students. Students will get scores. Which will ultimately decide the top 6 winners of the GCI.
This will have many benefits:
1.Mentors can enhance managerial skills and can build more projects on production
2.GCI
3.Most importantly the public lab will grow its contributor population and its code will be enhanced.

**Comment by SidharthBansal** [comment]
Got idea while thinking of #3283

**Comment by jywarren** [comment]
Hmm, interesting! What would be one example of a project -- maybe one like
a number of the sub-issues of this?
https://github.com/publiclab/plots2/issues/2439

**Comment by SidharthBansal** [comment]
Yeah we will break the project into smaller issues and sub issues like you did in #2439.
If you are OK with this approach we can try to break #3283.

**Comment by SidharthBansal** [comment]
@jywarren we are creating the Login/Sign Up frontend this year for this issue.
My idea worked. It was a nice idea

**Comment by SidharthBansal** [comment]
We have successfully completed Login and Subscription project in the GCI.
Closing this issue.
