### ISSUE TITLE
increase default image embedding size to "large"

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#329]
### The problem

Images in research notes, comments, and wiki pages on PublicLab.org are inserted into content at the `:medium` size, by default. This is a bit narrow these days -- 500px wide. To test this, go to https://publiclab.org/post (after logging in) and drag an image into the main text body field. Wait for the markup to appear; it should say something like: 

````markdown
[![7462024074_69ff835908_o.jpg](//i.publiclab.org/system/images/photos/000/014/301/medium/7462024074_69ff835908_o.jpg)](//i.publiclab.org/system/images/photos/000/014/301/original/7462024074_69ff835908_o.jpg)
````

See how this is the Markdown for displaying the `medium` image, surrounded by the link for the `original` image, so you see that when you click on the image? We want the `medium` one to be `large`. 

### Solution

800px is more appropriate. Screens are bigger now! And we have responsive styles so they'll scale down if the window is not big enough.

The code to change this is in two places; first, on this line in the server-side Ruby code by using `.path(:large)`, I believe, instead of just `.path`:

https://github.com/publiclab/plots2/blob/master/app/controllers/images_controller.rb#L28

Then the `:medium` in JavaScript on this line must be changed to `:large` too: https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/dragdrop.js#L64

### Steps to fix

* [ ] claim this issue with a comment
* [ ] set up a repository locally and make sure that all tests pass
* [ ] start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress"
* [ ] fix the issue following the steps above
* [ ] make sure all tests pass
* [ ] alert someone via either the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by jiteshjha** [comment]
Hey @jywarren , is this related to the images under recent activity on the dashboard?

**Comment by jywarren** [comment]
No, it's when you upload an image into the posting form. It's probably in
/app/assets/javascripts/editor.js

Tnx!

**Comment by jywarren** [comment]
Actually it can be solved in JavaScript around this line: https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/dragdrop.js#L64

Or on this line in the server-side Ruby code by using `.path(:large)`, I believe: 

https://github.com/publiclab/plots2/blob/master/app/controllers/images_controller.rb#L28

**Comment by gr2m** [comment]
As you add the `first-timers-only` label, can you add a few more instructions to make it more approachable to people contributing to open source for the first time? I found my way here through https://twitter.com/first_tmrs_only/status/710115818131079168

We recently wrote about how we do that at Hoodie, maybe that’ll help? http://hood.ie/blog/starter-issues.html

**Comment by jywarren** [comment]
Of course, and thanks, that's a great example to work from. I'll post something in the next 15min or so.

**Comment by jywarren** [comment]
How's this, @gr2m ?

**Comment by gr2m** [comment]
amazing, thanks a lot Jeffrey, from own experience I can tell this means a lot to people new your project and to Open Source in general :) With that you could also ping [@YourFirstPR](https://twitter.com/yourfirstPR) to give a shout out.

**Comment by gr2m** [comment]
By the way I’m co-hosting a "Welcome to Open Source" workshop in Atlanta on April 2nd, would you prepare an issue like this for the participants to work on during the workshop? We have a GitHub repository where you could link the issues you prepared for the event:
https://github.com/welcome-to-open-source/Atlanta

I’ll reach out to more projects soon, so timing is perfect :) Let me know if you have any questions. And sorry for the noise in your issue comments here, feel free to ping me on Twitter [@gr2m](http://twitter.com/gr2m/)

**Comment by jywarren** [comment]
For sure. I went ahead and made a list of such issues (and built out similar guidance docs): https://github.com/publiclab/plots2/labels/first-timers-only and some more with a little less support but still a lot of context here: https://github.com/publiclab/plots2/labels/help-wanted

Haha, i actually don't use twitter (except for my github issue bot), but we could open an issue called "preparing issues for newcomers" and talk there, or my email is jeff@publiclab.org. :-)

BTW, how do you typically deal with converting submitted issues, posted by someone else, into a nice issue like this?

**Comment by gr2m** [comment]
> BTW, how do you typically deal with converting submitted issues, posted by someone else, into a nice issue like this?

I usually create a follow up issue with more instructions, and then close the issue posted by someone else with something like "closing in favor of #1234"

**Comment by ykl7** [comment]
@jywarren Hi Jeffrey. This is Yash. I'd like to work on this issue and get it fixed.

**Comment by jywarren** [comment]
Oh, awesome. Please tell me if there's anything you need to get started!

**Comment by ykl7** [comment]
I'll let you know if anything comes up.

**Comment by jywarren** [comment]
@ykl7, a new contributor to our codebase, fixed this in #467, and the change has been merged. Thank you so much! And thanks to @gr2m as well!

**Comment by jywarren** [comment]
Hi, @ykl7, just a heads up that we've tweaked the database configuration a bit -- read up here on how to get running if you have trouble!

https://groups.google.com/forum/#!topic/plots-dev/bFN2TX85h3g

**Comment by ykl7** [comment]
@jywarren Thanks for the tip Jeffrey. I was following one of the issues where this topic was broached. I'll implement the necessary changes in my local repository and proceed accordingly.

**Comment by jywarren** [comment]
Great! I'm also going to make some time to better document some more
issues... If any catch your eye I'm happy to try to flesh them out a bit.

Thanks!

**Comment by ebarry** [comment]
Hi @ykl7! Thank you again for your valuable contribution to Public Lab. I would like to invite you to join us in a video conference to say a few words about what you contributed and how your experience was. The event is https://publiclab.org/openhour, and it’s coming right up on November 7th, at 1pm EDT which is UTC/GMT -4. 

Please feel free to respond here, or else email liz@publiclab.org, stevie@publiclab.org, jeff@publiclab.org.
