### ISSUE TITLE
Wiki Page Creation button not working

### ISSUE THREAD

**Issue by bronwen9** [publiclab/plots2#3296]
The wiki creation button fails to trigger new page-- when pressed, no action is taken. Tried in Chrome and Firefox, checked to make sure nothing posted by navigating back to publiclab.org/wiki/pagename and publiclab.org/tag/pagename.

![wikicreation](https://user-images.githubusercontent.com/8331717/45097055-f04c3a80-b0ef-11e8-8243-345efb6b505a.gif)

**Comment by jywarren** [comment]
Thanks, we're working on this one! https://github.com/publiclab/plots2/issues/3236

**Comment by jywarren** [comment]
With in-progress fix here: https://github.com/publiclab/plots2/pull/3189
