### ISSUE TITLE
Progress spinners on Leaflet Blurred Location

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3297]
Hi, @mridulnagpal - i've been trying to get the spinner to appear when clicking "Locate me" -- as in the latest demo: https://publiclab.github.io/leaflet-blurred-location/examples/

but haven't been able to get it working. Also, the geolocation itself seems not to be working? Maybe there's an issue overall with the button now? Would you mind taking a look?

**Comment by ebarry** [comment]
I just confirmed this bug by clicking that button on https://publiclab.org/wiki/new-town-creek. 
There is no visible response when the button is clicked. 

![no-spinner](https://user-images.githubusercontent.com/161439/46110925-36f2f900-c1b3-11e8-9723-5b79e73d5197.gif)

**Comment by jywarren** [comment]
hi Liz - could you highlight this one to Google Code-In mentors at
https://github.com/publiclab/plots2/issues/3168 and we'll see if we can get
it chopped up and in front of someone? Please do link to
https://github.com/publiclab/leaflet-blurred-location which is where the
docs and demo are running, which are working properly!

**Comment by sagarpreet-chadha** [comment]
Solved in https://github.com/publiclab/plots2/pull/4633 🎉 !
