### ISSUE TITLE
[notes:question:_____] inline grids break by encoding emojis from :question:

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3308]
We have a great system which recognizes short codes for emojis, turning `:question:` into ❓ just like on GitHub!

But when we try to use inline power tags like:

`[notes:question:website]`

...which is supposed to show a list of notes tagged with `question:website` -- it turns that into:

`[notes❓website]`

We need to change the emoji substitution code to not run within `[ ]` square brackets!

I put a test here: https://publiclab.org/wiki/sandbox-2

But you should be able to test in a comment, and on your local copy of the site. 

I believe the substitution code is here!

https://github.com/publiclab/plots2/blob/2fd9e45f198a84b351a3ae562ae826e9998fde94/app/helpers/application_helper.rb#L17

**Comment by KauNair** [comment]
Sounds interesting! 
I'll try this out.
