### ISSUE TITLE
Search page: Comparing search modes (boolean and natural)

### ISSUE THREAD

**Issue by milaaraujo** [publiclab/plots2#3312]
Hey everybody! After working on the API, Stéfanni and I are now trying to improve the Search page (results and design). Recently I opened a PR (#3309 ) to add the boolean mode option to the search view. Now I need your help to compare the different search options in the page (https://publiclab.org/search):
![desenho sem titulo 3](https://user-images.githubusercontent.com/4355017/45398614-c6b47700-b5f9-11e8-8279-c075aea0a7ba.png)
'Natural mode' was previously 'best match'. We changed the name, for now, to make clear that it's the natural mode search. After this period of tests, we can choose better names.

Besides saying which one is better, it would be great if you guys could document your search process:
```
a) what you're looking for, 
b) what search terms you use, 
c) what url you see, 
d) what you see there and how it differs from what you expect, and 
e) what pieces of content (urls) you were expecting to come up in your search
```
And it might also be good if you could compile a list of keywords you want "good" results for, so we can do additional tuning!

Thank you! 
;)

**Comment by stefannibrasil** [comment]
@publiclab/maintainers @publiclab/support @publiclab/reviewers we would love to know what you think of this, we are working on the /search page and we think you are gonna like it, but we need your help with this first, if possible :))))

it will only take like 10min, max, we promise :cake:
