### ISSUE TITLE
Use of common JS functions on /maps page .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#3316]
https://publiclab.org/maps/  --page uses the LEL library . 

https://github.com/publiclab/plots2/blob/master/app/views/map/index.html.erb

Common functions to use/setup this library are written here : 

https://github.com/publiclab/plots2/tree/master/app/assets/javascripts

#### Lets use these common functions !

Example use of these functions are done here : 

https://github.com/publiclab/plots2/blob/master/app/views/map/_leaflet.html.erb

``
We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.
``

**Comment by sashadev-sky** [comment]
this issue has been solved via #4544! Thank you!
