### ISSUE TITLE
wiki page daily changes summary subscriptions

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#332]
get a digest of the day's changes to a wiki page you watch (have starred, in current model)

we could compile changes to **all wiki pages** you've subscribed to in a single email, like:

**Today's wiki edits**
- [Spectrometer](http://publiclab.org/wiki/spectrometer) ([4 changes by 2 users]())
- [Open Air](http://publiclab.org/wiki/open-air) ([1 change by 1 user]())
- [Barnraising](http://publiclab.org/wiki/barnraising) ([9 changes by 4 users]())

[See all recent wiki edits](http://publiclab.org/wiki/)

And ability to subscribe to them from the /wiki list view.

Adding via @mathewlippincott:

We can probably extract diffs of wiki pages, similar to how you can see such diffs on a wiki revisions page. But filtering it by subscription fits into issue #370.

To propose a lighter-weight version of this, what do you think about a way to see new parts of a wiki page highlighted in green, if, perhaps, you click on a "View with changes" link in the feed? That'd be more immediately doable and I'd be happy to open an issue for either or both versions of this. 

Another thing we could think about in wiki social space is seeing not just that a page was edited, but trying to display what _section_ was edited, and offering to deep-link to it. But this is also a longer term project. 

Also see mention of digests here: https://github.com/publiclab/plots2/issues/64

**Comment by gretchengehrke** [comment]
Excellent!

**Comment by jywarren** [comment]
Connect to #289

**Comment by jywarren** [comment]
Merging into https://github.com/publiclab/plots2/issues/1119
