### ISSUE TITLE
Bounce non-user email replies and errors so they don't "disappear silently"

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3322]
We should bounce back a reply email with either: 

`Your reply did not get posted because we couldn't find an account on PL.org` (phrased more friendly and with a prompt to sign up?)

or if some other error occurred, just:

`There was an error and your comment couldn't be posted`

This could be broken into 2 emails -- and two issues.

Currently, the logic for processing the email is here:

https://github.com/publiclab/plots2/blob/60c95f0764036de8a6cac9732fb24896260e517b/script/mailman_server#L26-L31

That already has a `rescue` block, where we could send the "there was an error" message!

For where there is no user found (for example if the sending email doesn't match the one on file for this user), we have a conditional loop here:

https://github.com/publiclab/plots2/blob/60c95f0764036de8a6cac9732fb24896260e517b/app/models/comment.rb#L209-L212

That could have an `else` clause which returns an email. 

We could develop 2 email templates with mailer files here: https://github.com/publiclab/plots2/tree/master/app/mailers

Or we could try to send a shorter plain text response without a template, following some docs here (they're old so please test this out or double-check!):

* https://stackoverflow.com/questions/4916557/how-can-i-send-mail-with-rails-without-a-template#12974849
* `ActionMailer::Base.mail(from: "me@example.com", to: "you@example.com", subject: "test", body: "test").deliver`
* Up to date docs here: https://api.rubyonrails.org/classes/ActionMailer/Base.html#method-i-mail

**Comment by jywarren** [comment]
It does seem possible that we could use the syntax `ActionMailer::Base.mail(from: "me@example.com", to: "you@example.com", subject: "test", body: "test").deliver` to just reply directly in the `mailman_server` file!

**Comment by Anjalizi** [comment]
has this issue been solved yet? if not, please help me get started with this.

**Comment by gauravano** [comment]
Hey @Anjalizi, users can reply to the email they receive from us and there comments are added to our website in case their email account exist in the database. But, in case email account doesn't exist, then we need to send a email back to the user replying the above-given line.

We receive/poll for emails using mailman. the emails are processed at self.receive_mail method. You have to add check at appropriate place to check user existance and send a email by creating a new mailer for that.

Thanks
