### ISSUE TITLE
Add "Reply to this email to post a response" to various email templates

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3323]
Now that we have the fabulous new reply by email system and it's running pretty reliably, we should actually tell people that they can respond by email!

A message like in the title could fit in multiple places. 

![image](https://user-images.githubusercontent.com/24359/45554427-62b1ce80-b804-11e8-8cde-33a7bd5404b2.png)

The various comment templates where we need to add this message (which could be broken into separate issues, so several people can solve this one!) can be found here:

https://github.com/publiclab/plots2/tree/master/app/views/comment_mailer

For each, the current message that says `Do NOT reply...` should be changed to show that `You can reply by email OR visit this link ______`:

https://github.com/publiclab/plots2/blob/60c95f0764036de8a6cac9732fb24896260e517b/app/views/comment_mailer/notify.html.erb#L1-L7

**Comment by geekychaser** [comment]
@jywarren may i do this?

**Comment by jywarren** [comment]
Please! that would be great!
