### ISSUE TITLE
Add dropdown icon adjacent to the navbar items where required

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#3324]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

We used to have buttons in the Navbar some time back which clearly guide people to explore options but with links in the Navbar, a site visitor may think of them as a direct link. So, dropdown icon needs to be added adjacent to the dropdown Navbar link.

Hint: You need to make changes in this https://github.com/publiclab/plots2/blob/master/app/views/layouts/_header.html.erb file.

![dropdown_gci](https://user-images.githubusercontent.com/20878070/45557329-f7dfb200-b85a-11e8-9d00-3fca32d4cdb5.png)

**Comment by jywarren** [comment]
There were also some additional changes removing icons which we may want to
re-add, for example to replace "Dashboard" with a house icon and "Profile"
with a person icon. This keeps things more compact, and we had buttons for
Store and Donate too...

The commit that changed this was here:
https://github.com/publiclab/plots2/commit/8252c2164feaed620e4fcd9a7d0f4df8ff87f1b6#diff-faf6482c7d306c24c4e64dcdf191f7f4

This could be dealt with in a separate issue (or by a second person)
however! The original issue looks like a great first-timers issue :-)

**Comment by gauravano** [comment]
Opened separate issue at #3328 for icons @jywarren. I just added 2 points and 3rd point would be innovation from a GCI student. Also, do you think we should clean these comments?

**Comment by jywarren** [comment]
sure, go ahead!

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.
