### ISSUE TITLE
Redundant "Share Your Work" on dashboard page

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#3325]
```We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.```

### Please describe the problem (or idea)
There are 3 Share your work links to the same page on the dashboard. One inside the navbar's menu. Other on sidebar and one in the Activity Section
![image](https://user-images.githubusercontent.com/20972099/45563094-ebaf2100-b869-11e8-9737-5ef99c1bbcfd.png)

> What did you expect to see that you didn't?
I don't know whether it is a feature or redundancy that needs to be removed.
### Please show us where to look
https://publiclab.org/dashboard

We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.

**Comment by jywarren** [comment]
I think we can remove the white button but leave the remaining 2. The
navbar appears on every page, for example, so is for a slightly different
purpose. Thanks!

**Comment by avsingh999** [comment]
@SidharthBansal  can I work on this issue?

**Comment by SidharthBansal** [comment]
Sorry, you cannot work on this. The issue which are labelled with gci candidate can only be worked by Google Code In Students in the period of GCI.
You can try other issues.
Thanks

**Comment by jywarren** [comment]
Thank you!!!

**Comment by JonathanXu1** [comment]
Hey there, I would like to work on this. Is anyone working on this task?

**Comment by SidharthBansal** [comment]
Go ahead!!!

**Comment by JonathanXu1** [comment]
I've removed the white button in the pull request.

**Comment by SidharthBansal** [comment]
Please link the PR so that we can review.
Thanks

**Comment by oorjitchowdhary** [comment]
@jonathanxu1 perhaps it was a beginner task on gci as it's labeled a fto-candidate issue here.. That's why you may have not found it

**Comment by JonathanXu1** [comment]
@oorjitchowdhary that's what I thought except the label was removed by @SidharthBansal earlier on. I'd definitely like to know since many non- beginner issues on GitHub aren't available as tasks at all.

By the way here's my pull request 
https://github.com/publiclab/plots2/pull/4102

**Comment by JonathanXu1** [comment]
Hey just checking back, my PR has been merged and I was wondering I could get credit for this task. Thanks!

**Comment by SidharthBansal** [comment]
Please claim the task on the GCI dashboard so that I can approve

**Comment by JonathanXu1** [comment]
![image](https://user-images.githubusercontent.com/22998430/49688674-832bb500-fae3-11e8-8d50-e92e30d7d1a2.png)
I can't seem to find it on gci...

**Comment by oorjitchowdhary** [comment]
![image](https://user-images.githubusercontent.com/39333058/49688682-bef26900-fb3b-11e8-879e-4d5def459c37.png)

Yes it is a beginner task on gci

**Comment by JonathanXu1** [comment]
I understand. I'm very sorry for not being aware of that. It won't happen again.

**Comment by SidharthBansal** [comment]
No problem. Be careful from the next time
