### ISSUE TITLE
Make table of contents consistent with contents

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#3326]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Please describe the problem (or idea)
The table of content shows links which appear nowhere in serial order.
![image](https://user-images.githubusercontent.com/20972099/45563398-d71f5880-b86a-11e8-9caa-7a4b4bb2c564.png)

We have either two options:
1. Make front page of plots2 repo as only table of contents and have direct links to the other documents.
2. Write important documents on the front page and have linking for them. Other documents can be present in the doc folder.

We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.

**Comment by jywarren** [comment]
I prefer to have critical information still on the README, and additional
info linked out to. Thanks!

**Comment by SidharthBansal** [comment]
@jywarren I agree with you. I just want to say that we can make table of content somewhat similar to the listing which we provide. Like we can modify the table of contents to have direct links on the page first and then the indirect links so that the document is more readable.
Thanks
