### ISSUE TITLE
Remove Dashboard from the dropdown menu

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#3327]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Please describe the problem (or idea)
We have redundant Dashboard link under profile nav bar. We need to remove it.
![image](https://user-images.githubusercontent.com/20972099/45563588-6fb5d880-b86b-11e8-9b94-d7d93a4a0940.png)
Remove the following line
Code link: https://github.com/publiclab/plots2/blob/60c95f0764036de8a6cac9732fb24896260e517b/app/views/layouts/_header.html.erb#L105

**Comment by maciejmyslinski** [comment]
I'd love to take over this one.
Today I speak about Open Source at meet.js Kraków meetup to encourage peeps to engage.
I'd like to show them live how to contribute using this ticket as an example.
Thank you for creating this opportunity! ❤️

**Comment by SidharthBansal** [comment]
Hi this issue is specially designed for google code in students. So it will be best if you could try any other first timer issue where gci candidate label is not present.
Thanks

**Comment by maciejmyslinski** [comment]
There are no other opportunities in this repo. But no problem, OS world is huge. I'll find something.

**Comment by jywarren** [comment]
Here you go! https://github.com/publiclab/plots2/issues/3341

**Comment by vsk4** [comment]
Hello @SidharthBansal  @jywarren, I would like to work on it. Thank you

**Comment by gauravano** [comment]
This issue is already solved in #3327 ,so closing it. Thanks!
