### ISSUE TITLE
Change navbar links to icons

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#3328]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

To make the Navbar more compact replace the following navbar links:
1. `profile` link with the icon of the person
2. `Dashboard` link with the house icon
3. We want to hear about this point from you. Suggest which other navbar links can be changed :thinking: 

Hint: You need to make changes in this https://github.com/publiclab/plots2/blob/master/app/views/layouts/_header.html.erb file 

Mention @publiclab/community-reps after solving as getting their consent is essential for choosing icon and for finalizing the view too. Feel free to ask for help, if required. Thanks!

**Comment by SidharthBansal** [comment]
Hi @gauravano can you please break this into 2 different issues. So that two people can work on it.
Thanks

**Comment by gauravano** [comment]
Hi @SidharthBansal, I think it's fine as it is, as the issue just need replacing links with icons at some places, its already an easy task :sweat_smile: . What do you say?

**Comment by SidharthBansal** [comment]
Ok

**Comment by SidharthBansal** [comment]
Published on GCI dashboard

**Comment by SidharthBansal** [comment]
An icon in addition to text will be awesome. What do you say?

**Comment by jywarren** [comment]
Yes and we can make this a multi-use issue to go to https://fontawesome.com/v4.7.0/ and find an icon, and paste it in here with a link and a screenshot to suggest one for each item. +1!

**Comment by jywarren** [comment]
Yes and we can make this a multi-use issue to go to
https://fontawesome.com/v4.7.0/ and find an icon, and paste it in here with
a link and a screenshot to suggest one for each item. +1!

**Comment by JonathanXu1** [comment]
Hi, I'm working on solving this issue for codein!

How is this for the user icon: 
![image](https://user-images.githubusercontent.com/22998430/47620705-9ea6a780-dac3-11e8-89b9-03fc7873a1b2.png)
And for the dashboard icon:
![image](https://user-images.githubusercontent.com/22998430/47620709-b2520e00-dac3-11e8-9087-55a440dba73f.png)

Respective links:
https://fontawesome.com/v4.7.0/icon/user
https://fontawesome.com/v4.7.0/icon/home

I think I've made the neccessary changes in the file but can't view it as I'm having trouble running Phusion Passenger. I've followed the standard installation for plots2 until step 9, when I get the following error:
https://pastebin.com/AaeeizLL

**Comment by jywarren** [comment]
Cool! these look great. Can you check out
https://github.com/publiclab/plots2/issues/3840 and post your install
issues there so we can help folks on those in one place? thank you!

However, I believe just the icons completes a GCI task. Adding them to the
code might be a further task!

**Comment by SidharthBansal** [comment]
@JonathanXu1 have you worked on this? Where is the pr?

**Comment by JonathanXu1** [comment]
Yeah I worked on it a long time ago but the task expired before I could claim it

**Comment by SidharthBansal** [comment]
OK, so did you submitted any PR?
Was there any review issue or were you late?

**Comment by JonathanXu1** [comment]
By the time @jywarren commented , my task had expired, but I found the icons and was adding them to the codebase. Should I still make a PR if the changes have already been solved by #4199 ?

**Comment by SidharthBansal** [comment]
I will give you reward for your work.

**Comment by SidharthBansal** [comment]
https://codein.withgoogle.com/dashboard/tasks/5446379464818688/
please claim it, I will approve it

**Comment by JonathanXu1** [comment]
Thank you :)
