### ISSUE TITLE
Issue Initiating Plots2 Ruby Instance on Cloud9

### ISSUE THREAD

**Issue by artsandideas** [publiclab/plots2#333]
Hi, PublicLab
We've forked plots2 to our artsandideas/plots2 github instance and loaded up a named/ruby cloud9 workspace.
Cloud9 creates a working workspace, tells us "ruby-2.1.2 is not installed. To install do: 'rvm install ruby-2.1.2'". So, we do a rvm install ruby-2.1.2. Ruby installs.
Then (at artsandideas:~/workspace (master) $ ) we try to run "./install_cloud9.sh" and bash says: "bash: ./install_cloud9.sh: No such file or directory". We ls into that directory and there is a "install_cloud9.sh" file.
Can you tell us what steps we're missing or have messed up?

Thanks,
Patrick
HereLab

**Comment by jywarren** [comment]
Hi, what directory are you in when you run the install_cloud9 script? Can
you type "pwd" to find out?

You should see folders like app, config, etc, like in the plots2 git repo.

Im traveling at the moment but will try to answer questions as I can. You
might also ask on the publiclab developers list at
http://publiclab.org/wiki/developers if you don't hear back fast enough.

**Comment by artsandideas** [comment]
Hey Jeffrey,

Here’s a screen grab.
I’m patient. This project is ahead of schedule.
Thanks for your note. 
Safe travels,
Patrick






Executive Director
Arts & Ideas
www.aandi.org <http://www.aandi.org/>
patrick@aandi.org
t: @artsandideas <https://twitter.com/artsandideas>
508 560 2762 <tel:508%20560%202762>

**Comment by jywarren** [comment]
Ack! so simple. Sorry for the slow response and the typo which caused this. The correct command is:

`./install_cloudnine.sh`

I'll change this in the docs. My bad!
