### ISSUE TITLE
LEL library not working on plots2 !

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#3337]
Console showing following error : 

<img width="1438" alt="screen shot 2018-09-16 at 8 14 42 pm" src="https://user-images.githubusercontent.com/14952645/45597661-34dbae00-b9ed-11e8-9f39-c0b8c319ee5c.png">

**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

**Comment by JonathanXu1** [comment]
Hey @sagarpreet-chadha could you give us more info on this issue? Such as:

- where to find where LEL is used in frontend
- where to find error in codebase
- any updates on the issue (if it's been resolved, etc)

**Comment by sagarpreet-chadha** [comment]
Resolved 👍 .
