### ISSUE TITLE
Remove redundant code

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#3339]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Move files from https://github.com/publiclab/plots2/tree/master/app/views/comment/ to https://github.com/publiclab/plots2/tree/master/app/views/comments/ to consolidate these very similar folders, and find any references to `/comment/` to change to `/comments/`.

**Comment by gauravano** [comment]
Hi, this issue has been opened as a task on GCI dashboard. If you are Google Code-In participant and want to solve this issue, please claim it from Google Code-In [website](https://codein.withgoogle.com/organizations/public-lab/) . Thanks!

**Comment by gauravano** [comment]
@SidharthBansal I have opened this one on dash, please publish. Thanks!

**Comment by SidharthBansal** [comment]
Published...great!!!

**Comment by SidharthBansal** [comment]
Now I am learning for sessional exam. Will be available after my exam.
Hope you will understand.

**Comment by gauravano** [comment]
Hey, @okonek have you claimed this issue on GCI dashboard?

**Comment by gauravano** [comment]
As I can see from the GCI dashboard, that you have not claimed this task. **According to Google Code-In rules, a participant can work only at that task which is claimed by them. So, I will ask you to close your PR ASAP and please remember this for future. Thanks!**
