### ISSUE TITLE
"About us" confusing in Public Lab Store

### ISSUE THREAD

**Issue by aSquare14** [publiclab/plots2#3350]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

"About us" in header redirects us to https://publiclab.org/wiki/kits which is basically about public lab.
"About us" in footer redirects to https://store.publiclab.org/pages/about-us which is about public lab store.

> What did you expect to see that you didn't?

Confusing behaviour. Naming the header link as "About Public Lab" and the footer link as " About us"(since we are on store page) would be better.

### Please show us where to look

https://store.publiclab.org/

### What's your PublicLab.org username?

asquare14
> This can help us diagnose the issue: 

### Browser, version, and operating system
Chrome. Ubuntu 16.04
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.

**Comment by gauravano** [comment]
Hi, @aSquare14 nice catch! Let's confirm about this from @jywarren @publiclab/community-reps before proceeding further. Thanks!

**Comment by SidharthBansal** [comment]
@jywarren If you agree with this then we can open up 2 first timer gci candidate issues for these links.
Thanks

**Comment by jywarren** [comment]
Hmm, I think maybe we need input from the Kits initiative lead @bronwen9 to make this decision.

**Comment by jywarren** [comment]
Closing this one up, thank you!!!
