### ISSUE TITLE
Typo "Twittern" at end of each post. It should be "Twitter"

### ISSUE THREAD

**Issue by aSquare14** [publiclab/plots2#3351]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

At the end of every article/blog post. There are options of like or tweet. Twitter is written as Twittern.

> What did you expect to see that you didn't?

![selection_006](https://user-images.githubusercontent.com/22938709/45761216-6ea8f080-bc49-11e8-9170-09f3a6686533.png)

### Please show us where to look

https://publiclab.org/notes/warren/07-06-2018/new-accessibility-features-for-making-aerial-maps-in-mapknitter

### What's your PublicLab.org username?
asquare14
> This can help us diagnose the issue: 

### Browser, version, and operating system

Chrome. Ubuntu 16.04
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by gauravano** [comment]
Hmm, this one is strange. 

Ok. I got it. If I am not wrong, you were trying Deutsch language from the footer as mentioned by you in #3348. You noticed no changes in the website but actually minor changes were there, like `tweet --- > Twittern`. So, if you select English again, you will notice that there is no typo. Thanks!

**Comment by aSquare14** [comment]
Yes ! I guess Internationalization needs to be improved !

**Comment by gauravano** [comment]
Agreed! I think this issue can be closed now. What do you think?
