### ISSUE TITLE
Typo. "uing" should be "using"

### ISSUE THREAD

**Issue by aSquare14** [publiclab/plots2#3353]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

_You can aslo share the link to your answer **_uing_** the Share button present below the answer._
This line has a typo.

> What did you expect to see that you didn't?

Change uing to using.

### Please show us where to look

https://publiclab.org/wiki/public-lab-q-and-a
Last line

### What's your PublicLab.org username?
asquare14
> This can help us diagnose the issue: 

### Browser, version, and operating system
Chrome. Ubuntu 16.04
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by Souravirus** [comment]
Nice catch @aSquare14. Do you want to solve it or mark it as a gci-candidate issue?

**Comment by gauravano** [comment]
Hi, @aSquare14 @Souravirus actually that typo was in the wiki page and not in the code. Thanks!

**Comment by Souravirus** [comment]
Hmm right @gauravano.

**Comment by aSquare14** [comment]
@Souravirus  GCI-candidate task if updating wiki counts as one :P

**Comment by Souravirus** [comment]
Yeah we have many easy tasks but this is more than easy. So, it can be done now in my opinion.

**Comment by gauravano** [comment]
Agreed @Souravirus :sweat_smile: . Feel free to close this issue after editing it. Thanks!

**Comment by Souravirus** [comment]
Done.  Closing this !!
