### ISSUE TITLE
Typo. "Monate" should be "Months" on licenses,wiki/board page.

### ISSUE THREAD

**Issue by aSquare14** [publiclab/plots2#3354]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

![selection_007](https://user-images.githubusercontent.com/22938709/45769827-5db6aa00-bc5e-11e8-90eb-08b64dee3221.png)

> What did you expect to see that you didn't?

Months expected, showing Monate

### Please show us where to look

https://publiclab.org/wiki/licenses
https://publiclab.org/wiki/board

### What's your PublicLab.org username?
asquare14
> This can help us diagnose the issue: 

### Browser, version, and operating system
Chrome, Ubuntu 16.04
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by gauravano** [comment]
Hi @aSquare14, I guess this issue is relevant to https://github.com/publiclab/plots2/issues/3351#issuecomment-422895982 . Sorry for the inconvenience.

**Comment by jywarren** [comment]
could this also have been a German localization issue? Thank you!

**Comment by jywarren** [comment]
Ah, i see it's already resolved. Great!
