### ISSUE TITLE
Exploring layouts for the dashboard

### ISSUE THREAD

**Issue by aSquare14** [publiclab/plots2#3355]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Please describe the problem (or idea)

The dashboard lists out all the questions. I noticed that there are lots of gaps (empty white boxes) between a few questions. This behaviour is seen mostly when an image is added.

I think the dashboard UI can be improved by filling these white empty spaces/ using a better template.

![whatsapp image 2018-09-19 at 23 07 06](https://user-images.githubusercontent.com/22938709/45770731-d159b680-bc60-11e8-8ab4-f8fb360b4e2e.jpeg)

### Please show us where to look

https://publiclab.org/dashboard

### What's your PublicLab.org username?
asquare14
> This can help us diagnose the issue: 

### Browser, version, and operating system
Chrome. Ubuntu 16.04
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

This issue has an instance count of 50.
We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.
>> What you need to do as a GCI student?

Can you point to another
site layout as an example of how to solve this? Maybe paste in a screenshot
from another site? 

Give different templates which could be replaced with the current templates.
Each student can give atmost 2 templates which he/she finds best.

**Comment by SidharthBansal** [comment]
We need to properly think what will be the gci issue. @aSquare14 
There are multiple options:
1) We can ask folks to give their UI designs for the issue. Have instance count on the issue as say 10. Then choose the best one.
2) Give a template/ design and ask the students to implement it.

**Comment by aSquare14** [comment]
Giving them a template sounds better. That will be according to the maintainers of the site and will cause less confusion I believe.

**Comment by SidharthBansal** [comment]
Let's take views form jeff first.

**Comment by jywarren** [comment]
I'm interested in this! Thanks for the suggestion! Can you point to another
site layout as an example of how to solve this? Maybe paste in a screenshot
from another site? Thank you!

**Comment by oorjitchowdhary** [comment]
![screenshot 85](https://user-images.githubusercontent.com/39333058/49703288-42d64f00-fc29-11e8-8491-af27c1a881e2.png)

We could use this maybe.. Use the list view below for comments.. 
Use the `top countries` view for maybe tags..
Use the overview grids for perhaps the welcome line on our dash currently.. 
*Welcome, oorjit_chowdhary! 14 notes and 74 wiki edits posted in the past week. You've shared 3 research notes.* 
where we can make notes hyperlink and wiki hyperlink into grid boxes..
And much more of improvisation but this'd require a lot of efforts..

What say @publiclab/reviewers ?

**Comment by JonathanXu1** [comment]
You can also do something similar to Devpost:
![image](https://user-images.githubusercontent.com/22998430/49705519-c4f45280-fbec-11e8-9547-04106d2308fa.png)
They have pre-sized cards that fit together very well in a grid layout. If there is no image available, a placeholder wallpaper will be used. I've made a mock-up with Public Lab's dashboard on photoshop:
![dashboard placeholder](https://user-images.githubusercontent.com/22998430/49705641-d5f19380-fbed-11e8-9f44-9b1867afa69a.png)

**Comment by dinaelhanan** [comment]
I think a good quick fix for this would be finding a way to put a filler image like @JonathanXu1 suggested with the pre-filled cards. Great idea! Maybe what we can create a issue for first is having a default image that all posts without an image will have (probably like the first card in @JonathanXu1 's comment, the publiclab logo) that would be a good place to start

**Comment by SidharthBansal** [comment]
All three of them will get credits. Thanks. This issues is to give rewards
for sharing ui design mock ups as you all have shared, so please claim the
respective issue and get task approved by @Gaurav Sachdeva
<sachdeva.gaurav1997@gmail.com> or @Jeffrey Warren <jywarren@gmail.com>
 or @sidharthbansal

**Comment by oorjitchowdhary** [comment]
Hi.. I don't think the task is available on gci..
Also, Can we shortlist one design so I could work on implementing it.. 
Thanks

**Comment by SidharthBansal** [comment]
Shortlisting will be done by @jywarren so in the meantime you can work on
any other task.

**Comment by SidharthBansal** [comment]
https://codein.withgoogle.com/dashboard/tasks/5329109677768704/

**Comment by oorjitchowdhary** [comment]
@SidharthBansal Please approve the task..

**Comment by gauravano** [comment]
Hi everyone, we are planning dashboard designs here - https://publiclab.org/notes/edie_blues/12-13-2018/public-lab-dashboard-new-design-ideas . You are most welcome to add your ideas there. Thanks!

**Comment by gauravano** [comment]
Closing this one and further discussion is open at above link. Thanks!
