### ISSUE TITLE
Continue to add to Wiki page for repeatable "Community Support Tasks" usable in Google Code-In

### ISSUE THREAD

**Issue by aSquare14** [publiclab/plots2#3358]
### Please describe the problem (or idea)

Wiki was last updated in 2016. We should update it with tasks for 2018 or write TBA. (To Be Announced)

### Please show us where to look

https://github.com/publiclab/plots2/wiki/Google-Code-in-Tasks

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

asquare14
****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment]
@jywarren @aSquare14 was insisting to be a gci-mentor. I told her to solve some ``first-timer-only`` issues at public labs. Then try to solve some ``help-wanted`` issues at public labs. This way she will be know about the workflow at Public labs. Then she could start opening ``fto`` issues and help new comers.
Is there any other thing she needs to do for being mentor??

@aSquare14 can you please send a pull request to this?

**Comment by aSquare14** [comment]
I can send a PR but what should the content be. I think, I'll let @jywarren review the issue once and then send a PR !

**Comment by SidharthBansal** [comment]
yeah great.

**Comment by SidharthBansal** [comment]
Hi We had a discussion, we need to include that if a candidate makes a first timer issues OR help others in first timer issues like helps in travis tests, provide code links OR bug reporting OR suggestions
If a person does similar kind of helping tasks then the candidate will be rewarded.

**Comment by SidharthBansal** [comment]
@jywarren will you mind updating the document, this document  is the most crucial element. All @aSquare14 and I am having exams so cant do it till 1st october. She told on gitter that her exams are till 30th. My are till 1st. This issue is of atmost priority for GCI.

**Comment by SidharthBansal** [comment]
This page is for new comers on how to start contributing at pl. We will list how shall new comer proceed. They need to do two ftos and then other gci tasks. Gci list is in 3276 etc. We need to tell them. 
If we will prepare a nice document and give them link to it then this will reduce significant work of mentors.

**Comment by jywarren** [comment]
Perhaps this is a page to nicely organize things like this?
https://github.com/publiclab/plots2/issues/3424

**Comment by SidharthBansal** [comment]
Yeah this page will contain links to these kind of documents.
As soon as gci candidate comes and asks for help we can give this wiki page link.
This wiki page will guide students 90%. Rest 10% students can be guided on gitter chat. This action will reduce the work of mentors telling students about things.

This wiki page will have link to installation, then to first timers, then to help wanted including multiple instance count design, code links etc tasks. Am I clear?

**Comment by Souravirus** [comment]
Yeah I understand you. So, instead of listing out tasks in that wiki page. We can tell people how to start, how to contribute and things like that. Nice idea @SidharthBansal

**Comment by geekychaser** [comment]
@SidharthBansal @aSquare14 can i prepare documentation for "how to start contributing" , as your exams are going on?

**Comment by SidharthBansal** [comment]
Yeah go ahead. Documentations require many updates so @aSquare14 can also add changes to it when she gets free.
As you are new to pl, please read the above comments and #3276, #3424 and other similar issues.
Don't forget to add them into the PR.
Thanks @geekychaser

**Comment by SidharthBansal** [comment]
Also, there is a possibility that gci students will contribute before the event. So this doc is really important. So go ahead.
