### ISSUE TITLE
Display message in collections in Public Lab Store

### ISSUE THREAD

**Issue by aSquare14** [publiclab/plots2#3359]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**
### Please describe the problem (or idea)

In the collections, collections that do not have any product (eg. photography) should have a message displayed below the heading _"Sorry, there are no products in this collection"_

Currently, it displays _"See more Photography "_

### Please show us where to look

https://store.publiclab.org/collections
Photography section

### What's your PublicLab.org username?
asquare14
> This can help us diagnose the issue: 

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.

**Comment by SidharthBansal** [comment]
@aSquare14 I am having difficulty in reproducing the error.
I tried following and got this
![image](https://user-images.githubusercontent.com/20972099/45796521-91c1b780-bcbe-11e8-938f-baf1188e2830.png)
can you please help in explaining about the error?

**Comment by aSquare14** [comment]
It is not related to search.  Just a UI enhancement. 
1. Go to Photography section in collections. 
2. You will notice it has no products listed.
3. Instead of displaying a hyperlink saying "See more Photography", we should display "Sorry, there are no products in this collection."

In the picture below, we need to update the message.
![screenshot from 2018-09-20 10-45-13](https://user-images.githubusercontent.com/22938709/45797206-1b26b900-bcc2-11e8-8fae-26147774fd87.png)

**Comment by aSquare14** [comment]
I think it would be better suited for GCI candidate :+1: Thanks.

**Comment by SidharthBansal** [comment]
Can you please make  issue like https://github.com/publiclab/plots2/issues/3342? and close this one. Also link this conversation there.
We need to be much more friendly to the newcomers. Follow a similar template. Provide the necessary code links.
Also, I want to tell that we have 2 kind of ``gci-candidate`` issues
1) Issues labelled with ``gci-candidate`` these are little advanced to be solved
2) Issues labelled with ``gci-candidate`` and ``first-timers-only`` -->these are for first timer gci candidates. They have detailed steps and hints. May be we can provide them whole solution.

There is one more category `` first timers only`` these issues are first timers and can be handled by any one except gci candidates. (for elderly fellows). They also have detailed hints and steps.

I think this could be labelled with ``first-timers`` and ``gci-candidate``.

**Comment by aSquare14** [comment]
Okay. Will do !

**Comment by jywarren** [comment]
Hi! I'm going to close as we don't have access to do much on store pages, as it's not an open source codebase. :-(

Thanks though!
