### ISSUE TITLE
Pagination Component needs to be removed from home page if user is not logged in.

### ISSUE THREAD

**Issue by aSquare14** [publiclab/plots2#3360]
### Please describe the problem (or idea)

In references to issues #3301, #2173.

- Pagination is NOT broken in the home page. It redirects to the home page (correct behaviour) if a user is not logged in. This is because to view the other pages, you need to be logged in.
- It works perfectly if the user is logged in. Because after logging in,URL changes to  /dashboard. 
- We should just remove the pagination component from home page if the user is not logged in. 

### Please show us where to look

https://publiclab.org/?page=3

### What's your PublicLab.org username?
asquare14
> This can help us diagnose the issue: 

### Browser, version, and operating system
Chrome. Ubuntu 16.04
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!
 

****
```We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.```
## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment]
Can you please turn this to a first timer issue?

**Comment by jywarren** [comment]
Hi! A few extra bits of into and formatting would be very helpful to make this a proper first timers only issue. Would you mind using this as a model?

https://github.com/publiclab/plots2/issues/3363

There's more guidance on writing first timers only issues at code.publiclab.org as well. 

Thank you so much!!!!!

**Comment by aSquare14** [comment]
Sure ! I'll format all the issues opened by me over the weekend ! :)

**Comment by jywarren** [comment]
I wonder if we could direct to http://publiclab.org/research?page=2 if
you're not logged in?

**Comment by aSquare14** [comment]
So, for now I am just adding code snippet for removing line. Maybe we could open another issue where we can say redirect to page 2 @jywarren ?

**Comment by jywarren** [comment]
Hmm, are you sure the snippet is not used in another view?

**Comment by aSquare14** [comment]
Thanks for poiting it out. I'll look into it

**Comment by abizerlokhandwala** [comment]
Hey @aSquare14 
When the user is logged in, it automatically redirects to /dashboard, but you can reproduce the same pagination problem if you go to the /home URL. The pagination issue persists when logged in. Can we just remove the pagination from the homepage if this is the case, regardless of the user being logged in or not?

**Comment by aSquare14** [comment]
That sounds good to me ! @SidharthBansal  views?

**Comment by abizerlokhandwala** [comment]
It would be safe to remove it from the blog function in home_controller.rb, also it's only used with the /home URL. Can I take it up?

**Comment by jywarren** [comment]
The new home page no longer has pagination, so I'm going to close this up! Thanks!
