### ISSUE TITLE
Change senders name for emails

### ISSUE THREAD

**Issue by geekychaser** [publiclab/plots2#3361]
### Please describe the problem (or idea)
![image](https://user-images.githubusercontent.com/24489162/45821275-65318e00-bd06-11e8-960c-f90ff7571d0c.png)
I got the mail from notifications sounds ambiguous to me
> What happened just before the problem occurred? Or what problem could this idea solve?
Instead of notifications, ``Public Lab`` should be present.

> What did you expect to see that you didn't?
Instead of notifications, ``Public Lab`` should be present.

### What's your PublicLab.org username?
geekychaser

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

mozilla firefox
****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by igniteeng000** [comment]
Please assign #3361 to me

**Comment by SidharthBansal** [comment]
@igniteeng000 go ahead

**Comment by SidharthBansal** [comment]
There are two issues
1) [Public Lab] should not be present in the message title
2) Instead of notifications, text should be ``Public Lab``

**Comment by bajajerk** [comment]
@SidharthBansal 
I want to work on this issue

**Comment by SidharthBansal** [comment]
There are two sub issues in this issue. So you both can work on it.

1.[Public Lab] should not be present in the message subject @igniteeng000 you do this part
2.Instead of ''notifications'', text should be ''Public Lab'' @bajajerk you do this part

**Comment by SidharthBansal** [comment]
Thanks Rishabh for making this issue.
Thanks venu for asking to do this issue at gitter chat.

**Comment by SidharthBansal** [comment]
@bajajerk if you help just ping us

**Comment by bajajerk** [comment]
@SidharthBansal  I have figured out that 'notifications' is rendered from comment_mailer.rb , line 4

 default from: "notifications@#{ActionMailer::Base.default_url_options[:host]}"
Should i change this or think of some other way.

**Comment by jywarren** [comment]
Thanks all! @bajajerk I believe there are more available at https://code.publiclab.org and we'd love your help!
