### ISSUE TITLE
Typo at welcome message

### ISSUE THREAD

**Issue by geekychaser** [publiclab/plots2#3362]
### Please describe the problem (or idea)
The welcome note is a lengthy sentence. Also, there is an extra comma before and.
See
![image](https://user-images.githubusercontent.com/24489162/45821692-775ffc00-bd07-11e8-8ac8-42a0822bed15.png)

> What did you expect to see that you didn't?

We can have nice formated text like
```
This is your dashboard, where recent updates from other community members show up. It'll keep you updated with recent progress, news and developments.
To get started at Public Lab, try: 
```

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

geekychaser

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

mozilla firefox, ubuntu
****

## Thank you!

**Comment by SidharthBansal** [comment]
Like we have #3341.

**Comment by geekychaser** [comment]
Yeah sir. I contacted you at gitter chat. Ok I will try my level best to open up the issue.
Thanks @SidharthBansal sir.

**Comment by SidharthBansal** [comment]
@geekychaser no need to call me sir. Sidharth is ok.
Thanks

**Comment by geekychaser** [comment]
I have opened a new issue #3363. Is it ok?

**Comment by SidharthBansal** [comment]
Yeah it looks good to me.
Let @jywarren review it.
We have moved to #3363 so closing this issue now.

**Comment by geekychaser** [comment]
Thanks @SidharthBansal
