### ISSUE TITLE
Add feature to unable adding a blank tag in subscriptions

### ISSUE THREAD

**Issue by igniteeng000** [publiclab/plots2#3371]
### Please describe the problem (or idea)
In subscriptions, one can also add a blank tag which a user cannot unsubscribe.
> What happened just before the problem occurred? Or what problem could this idea solve?
Unable to remove blank tag
![subs](https://user-images.githubusercontent.com/25272573/45864308-39aab400-bd97-11e8-851d-5b4357ed1024.PNG)

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/subscriptions

### What's your PublicLab.org username?
igniteeng000
> This can help us diagnose the issue: 

### Browser, version, and operating system
chrome, windows 10
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by avsingh999** [comment]
@igniteeng000  I want to work on this  issue please assign me

**Comment by igniteeng000** [comment]
Sure

**Comment by SidharthBansal** [comment]
@avsingh999 also write a test with your patch.
Thanks both of you

**Comment by avsingh999** [comment]
@SidharthBansal  @igniteeng000  This issue can not see on local machine but on publiclab.org we can see this issue ? Now

**Comment by divyabaid16** [comment]
Can I work on this issue?
I found out a solution!

**Comment by SidharthBansal** [comment]
Sure
