### ISSUE TITLE
Welcome Dialog appearing on every refresh for first sign in users

### ISSUE THREAD

**Issue by YashishDua** [publiclab/plots2#3373]
The welcome message has appeared when a user first time enters the dashboard after sign up.
However, even if you cancel the dialog and refresh again, the message comes back again!
![screen shot 2018-09-21 at 1 01 07 am](https://user-images.githubusercontent.com/20666950/45869199-77aed480-bda5-11e8-8e3b-f934b375303a.png)

What should happen?
When a user explicitly cancels the welcome message dialog, it should not come even on multiple refreshes at that instance.

https://publiclab.org/ ...

****
This is an issue for first-timers.

**Comment by vchrombie** [comment]
Can I work on this issue?

**Comment by namangupta01** [comment]
Yeah go ahead!

**Comment by jywarren** [comment]
Ah - this is because the message is tied to the signup date - if you've signed up recently. Perhaps we could set a javascript localstorage value to recognize if you've turned it off? 

https://github.com/publiclab/plots2/blob/cdef0bd7978836212c112f2295b4561d3f6a57f0/app/views/dashboard/dashboard.html.erb#L1-L17

https://developer.mozilla.org/en-US/docs/Web/API/Storage/LocalStorage could help flag it to not appear (or to immediately hide it on page refresh) if the close X button has been pressed. What do you think?

**Comment by YashishDua** [comment]
If the user closes explicitly then it should not be shown afterward.
Apart from this, we can show the dialog for certain days when the user signs up.

**Comment by jywarren** [comment]
That sounds great!

**Comment by vchrombie** [comment]
I have tried using ruby but again I am stuck with this error. 
"Your Ruby version is 2.3.1, but your Gemfile specified 2.4.4"

**Comment by gauravano** [comment]
Hi, @vchrombie you have to install ruby version `2.4.4` and then switch current version to it. I hope you are using rvm. If you have any doubts, feel free to ask. Thanks!

**Comment by shivani-kapania** [comment]
Hi @vchrombie are you still working on this?

**Comment by vchrombie** [comment]
Hey @shivani-kapania, I am actually busy with my exams. if you are interested in fixing, you can do it. :)

**Comment by shivani-kapania** [comment]
Alright, I'd like to take this issue. Thanks! 👍

**Comment by YashishDua** [comment]
@shivani-kapania What's the status on this issue?

**Comment by shivani-kapania** [comment]
Hi @YashishDua I was busy with some work for a few days. I'm working on this. 
Any issues?

**Comment by YashishDua** [comment]
Just keeping a check, since you are working that's great! Otherwise, I was thinking to take up.

**Comment by jywarren** [comment]
Hi, i wonder if this one is OK, as we want to be sure first-time users see
it for a little while?

**Comment by jywarren** [comment]
I think for now, it is OK. Thank you!!!

**Comment by gautamig54** [comment]
This issue seems like not being fixed. @gauravano Can I try resolving this?

**Comment by gauravano** [comment]
Actually, going through @jywarren's comments, it looks like we don't need this one, that's why it's closed. Would you like me to suggest issues to you?

**Comment by gauravano** [comment]
And thanks @gautamig54 for checking here.
