### ISSUE TITLE
UI :: Add css to reply by email thread button 

### ISSUE THREAD

**Issue by namangupta01** [publiclab/plots2#3374]
#### With the merge of https://github.com/publiclab/plots2/pull/2669 we have a reply by email feature. And reply by email is stable and working, so now we can start working on some ui improvement for it.
Starting with the basic improvement:
Email thread button on any comment page is a link on clicking which whole conversation thread open-up but the way link looks can be improved with a tooltip saying [click here to view the conversation thread] with some improvement of link button from :
![screen shot 2018-09-21 at 2 08 35 pm](https://user-images.githubusercontent.com/20709985/45870185-eee56800-bda7-11e8-9f4e-2c8385de5489.png)
to:
![screen shot 2018-09-21 at 2 08 57 pm](https://user-images.githubusercontent.com/20709985/45870190-f3aa1c00-bda7-11e8-8896-b774678a3cdc.png)

and also while hovering we can change the default link behaviour to not show underline on link while hovering and also we can show hand-pointer on hovering the link.
This is basic ui improvement so labeling it to `first-timers-issue`

Comment can be found at: https://publiclab.org/notes/namangupta/02-17-2018/gsoc-proposal#c20071

**Comment by shivani-kapania** [comment]
Hi, I'm Shivani Kapania and I'm a final year student at BVCOE, New Delhi. May I try this issue?

**Comment by namangupta01** [comment]
Yes! Go Ahead. Fell free to ask if you need some help.

**Comment by shivani-kapania** [comment]
Definitely.

**Comment by jywarren** [comment]
Great! I think it could use styles like a padding of 3-4 px, maybe a
border-radius to give it a rounded look, and a very light grey background
color... what do you think? See how it looks in Gmail!

**Comment by jywarren** [comment]
![image](https://user-images.githubusercontent.com/24359/45908881-d63b7900-bdcc-11e8-9d39-61d1c5970943.png)

**Comment by namangupta01** [comment]
Yup gmail button looks good

**Comment by Paarmita** [comment]
@namangupta01 Can I work on this?

**Comment by namangupta01** [comment]
Hey @Paarmita, @shivani-kapania is already working on this issue. 
So you look for other issues to work on. And as far as i remembered you have already contributed to this project so please look for others issue then instead of doing `first-timers-issue`. If you need help in finding the issue then let me know.
Thanks !

**Comment by Paarmita** [comment]
@namangupta01 Yes, plz help in finding one?

**Comment by namangupta01** [comment]
Have you worked with `sidekiq`?

**Comment by namangupta01** [comment]
Okay then let me find some first-timers-issue.

**Comment by namangupta01** [comment]
@Paarmita you can try #3407

**Comment by shivani-kapania** [comment]
@namangupta01 can you assign me a help-wanted issue next?

**Comment by shivani-kapania** [comment]
@namangupta01 hi, can you pls assign me a help-wanted issue next?

**Comment by namangupta01** [comment]
It seems that all the issues are assigned but I will create some. You can
try from them.

**Comment by shivani-kapania** [comment]
Okay, thanks! 👍

**Comment by namangupta01** [comment]
See https://github.com/publiclab/plots2/issues/3425, if you want to try that.

**Comment by shivani-kapania** [comment]
> See #3425, if you want to try that.

Okay, let me take a look at it.
