### ISSUE TITLE
Improve in questions page when search  questions by topic

### ISSUE THREAD

**Issue by avsingh999** [publiclab/plots2#3375]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem

In Questions page when i search  nothing means when search input box is blank and then click search button It's giving this error page  and and when I type space in search input box it's also search for '  ' (space) tag 
![public](https://user-images.githubusercontent.com/25536022/45872219-1a1e8600-bdad-11e8-8661-d40304a0c8be.png)

### 📋Solution

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**Improve tags and search .Here should be messege when we didn't type anything and then message show ' required filed '

![re](https://user-images.githubusercontent.com/25536022/45913797-a4232900-be57-11e8-8d49-577831490f4a.png)

Code links….
https://github.com/publiclab/plots2/blob/5c0d96274bd0be15feba69d8f30093082402ace5/app/views/tag/_sorting.html.erb#L4
- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by jywarren** [comment]
Ah - interesting! We just published some big search changes. Can you try again?

**Comment by avsingh999** [comment]
@jywarren  No it's showing same error

**Comment by jywarren** [comment]
Ah, I see -- can you reformat this issue to be like this one? https://github.com/publiclab/plots2/issues/3409

The title especially can help! Thanks!

**Comment by SidharthBansal** [comment]
@avsingh999 please do the changes according to jeff so that we can publish it.

**Comment by avsingh999** [comment]
@SidharthBansal  @jywarren  please check, If need more changes 
thank you :)

**Comment by SidharthBansal** [comment]
Looks good to me now

**Comment by oorjitchowdhary** [comment]
So we basically want to show that **this is required field error** when we press the search button with a blank search bar.. right?

**Comment by JonathanXu1** [comment]
Hi can I claim this issue for CodeIn?

**Comment by oorjitchowdhary** [comment]
@JonathanXu1 This is a first timers only issue... so if you haven't contributed to public lab, you can go ahead

**Comment by JonathanXu1** [comment]
Alright thanks. I've found the line of code to be changed, but I've never used plots2 before and don't know how to navigate to that element in the UI.
![image](https://user-images.githubusercontent.com/22998430/48675762-2ca60900-eb2b-11e8-9207-3b7a113cf154.png)
Could I get a pointer?

**Comment by oorjitchowdhary** [comment]
So you're a first timer.. No need to worry.. I can assume that you're running public lab from localhost... you just have to go to localhost:3000/questions

**Comment by JonathanXu1** [comment]
Thanks, I figured it out. Is it too late to do a pull request?

**Comment by SidharthBansal** [comment]
Absolutely not. You can push your changes to all the issues which are not worked upon.

**Comment by SidharthBansal** [comment]
You can send a PR.

**Comment by JonathanXu1** [comment]
Hi, I've made pull request #4015

**Comment by JonathanXu1** [comment]
@avsingh999 @SidharthBansal Is it satisfactory? For some reason I'm unable to locate the task in gci anymore.

**Comment by kevinzluo** [comment]
I believe the issue was first resolved in #4006. The task was likely completed too.

**Comment by oorjitchowdhary** [comment]
Also @jonathanxu1 **keep in mind that you can claim and work on only one task at a time according to GCI rules**.

**Comment by JonathanXu1** [comment]
Hi, sorry about that. I abandoned my previous task and claimed this one so I could work on it. Also I believe #4006 does not include links to boolean searches, which was why this task was reopened again

**Comment by kevinzluo** [comment]
I thought #3490 had to deal with adding links to boolean searches, not this one? I might be wrong.

**Comment by JonathanXu1** [comment]
Just completed this issue. Could I get a link to the task? Thanks 🙂

**Comment by JonathanXu1** [comment]
Since my solution to this has been merged, can I get a credit for this task? I can't seem to find it anywhere on GCI..

**Comment by kevinzluo** [comment]
I believe (@)thesparks already claimed and completed the task before in #4006 , even though for some reason that PR was not merged. Also, @gauravano told me to claim a task before working on it as per GCI policy and not to do more than one at once, though all is up to all the mentors to decide.

**Comment by gauravano** [comment]
Hi @JonathanXu1, we really appreciate your work but credit for this task was already given to @thesparks as she claimed and performed it earlier. 

Whenever you do the task without claiming, you do it at your own risk. That's why we advice to follow the rule of "One task at a time which you have claimed". Thanks!

**Comment by JonathanXu1** [comment]
Hi, thanks for letting me know. I'll be aware of this for the future. :)
