### ISSUE TITLE
Liking a question must be allowed from the list item only

### ISSUE THREAD

**Issue by YashishDua** [publiclab/plots2#3379]
The user can mark the question inappropriate or spam from the list while not even entering into that question. If a user can flag from outside then there should be a feature to like that question also from outside.
![screen shot 2018-09-22 at 2 01 13 am](https://user-images.githubusercontent.com/20666950/45904821-d018bd00-be0b-11e8-9fa3-198e52bcde36.png)

Either flagging as spam should not be allowed from outside or liking must be allowed from outside.
Find the issue here:
https://publiclab.org/questions

We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.

**Comment by jywarren** [comment]
Liking is usually done in javascript -- https://github.com/publiclab/plots2/blob/master/app/views/like/_like.html.erb

**Comment by YashishDua** [comment]
@jywarren Thanks for sharing the resource. I will take up this issue.

**Comment by vikul1234** [comment]
@YashishDua @SidharthBansal @jywarren  can I work on this issue

**Comment by SidharthBansal** [comment]
Yeah go ahead

**Comment by jywarren** [comment]
We will be renewing the dashboard as part of Outreachy this winter, and this feature will no longer be needed - but thank you for the idea!!!
