### ISSUE TITLE
Turn off ip_address records in impressionist gem, switch to request_hash

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3382]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://publiclab.github.io/community-toolbox/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

> What happened just before the problem occurred? Or what problem could this idea solve?

We use `impressionist` to track unique pageviews across the site: 

https://github.com/charlotte-ruby/impressionist

> What did you expect to see that you didn't?

The code is currently set up to filter by unique ip addresses. But we can just as easily use `request_hash`, according to the documentation!

https://github.com/publiclab/plots2/blob/cdef0bd7978836212c112f2295b4561d3f6a57f0/app/models/node.rb#L170

This would be much better for privacy reasons and if we can change this and confirm it works, we could remove the `ip_address` table (and switch it's [matching indices](https://github.com/publiclab/plots2/blob/master/db/schema.rb.example#L183) to `request_hash` ones) entirely from the database. 

This is probably a pretty easy change! We'd love some help, and it could be a first-timers issue if the database schema and index changes are done as a follow-up step!

**Comment by SidharthBansal** [comment]
Can we make this entry level gci candidate too?

**Comment by sashadev-sky** [comment]
Going through #3276 task list for potential candidates and I think we can close this one - apologies if disagree feel free to reopen! 

It has since been refactored into 
https://github.com/publiclab/plots2/blob/b6d5089c5ac3b80ef48481a6753f39b8dc0812ca/app/models/node.rb#L180

which seems like the cleanest way to write it 

 And there is no `ip_address` table anymore. So we have really cleaned up shop here.

**Comment by gauravano** [comment]
Thanks for updating!
