### ISSUE TITLE
Improving the back-to-top button

### ISSUE THREAD

**Issue by rbhatia46** [publiclab/plots2#3387]
### Please describe the problem (or idea)
The Back-to-top button is present at the end of the webpage and is static there. Instead it can be present at the bottom-right corner of the screen all the time whenever someone scrolls down the page to make the user expirience better.
> What happened just before the problem occurred? Or what problem could this idea solve?

![](https://image.ibb.co/cXR92U/Capture.png)

> What did you expect to see that you didn't?

There should have been a back-to-top button all the time at the bottom right corner whenever someone scrolls down the page.

### Please show us where to look

https://publiclab.org/dashboard

### What's your PublicLab.org username?
rbhatia46
> This can help us diagnose the issue: 

### Browser, version, and operating system
Chrome Version 69.0.3497.100, Windows 10
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment]
Will you like sending a fix to this?

**Comment by rbhatia46** [comment]
Sure I will give it a shot!

**Comment by SidharthBansal** [comment]
Are you looking forward to be a Google Code in mentor @rbhatia46 ?
If so please fill the form https://docs.google.com/forms/d/e/1FAIpQLScSBS-ddZN2H-lviUJbKlbV2VwP21fdIutXOCBzigRhmXJybw/viewform
If you have not completed the things listed in the form. Do them and be a mentor.
Help people to contribute to OSS. If you want to do so.

**Comment by rbhatia46** [comment]
Yes, @SidharthBansal I am interested in being one! I had a look at the form. I cannot get any unassigned first-timer issue at the moment. For the help-wanted issue, I am onto this one and sure I will look into it and create a first-timer issue soon. And yeah I would love to help people contribute to Open Source as much as I can, thanks! 😁

**Comment by SidharthBansal** [comment]
OK...THANKS

**Comment by jywarren** [comment]
Hi! I just made a new one for you here! Check it out:
https://github.com/publiclab/plots2/issues/3391

On Sep 22, 2018 1:02 PM, "Rahul Bhatia" <notifications@github.com> wrote:

Yes, @SidharthBansal <https://github.com/SidharthBansal> I am interested in
being one! I had a look at the form. I cannot get any unassigned
first-timer issue at the moment. For the help-wanted issue, I am onto this
one and sure I will look into it and create a first-timer issue soon. And
yeah I would love to help people contribute to Open Source as much as I
can, thanks! 😁

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/3387#issuecomment-423758210>,
or mute the thread

**Comment by rbhatia46** [comment]
Thank you so much @jywarren ! I will have a look and solve it soon!

**Comment by SidharthBansal** [comment]
Please claim the task at the #3391.
Thanks

**Comment by bajajerk** [comment]
@SidharthBansal  Can you assign a first timer issue to me too

**Comment by SidharthBansal** [comment]
@bajajerk #3393 thanks

**Comment by rbhatia46** [comment]
@SidharthBansal Need a small help here, can you help me locate the HTML for that button. I tried to look at several ERBs in the views but could not find it. 
Thanks

**Comment by ckairen** [comment]
Hi, I'm currently a student and would like to contribute to this issue as part of my class project. Can I claim this issue? 
It's my first time contributing to open source so there might be some small errors in trying to do pull requests and forking and all that, but I'll definitely try me best to not make dumb mistakes. (you may or may not already noticed my partner isssabel claiming some other issues)

**Comment by gauravano** [comment]
Hi @ckairen, go ahead with the issue! And, don't worry about making mistakes, we all learn and grow from them. Feel free to ask your doubts by commenting below.
(And, yes, I noticed Isssabel, they've claimed other issue. Great to see both of you and would be awesome if more people wanna  start and contribute with us :)

 Thanks!

**Comment by ckairen** [comment]
Hi @gauravano I'll start on #3387 first then before I attempt the HTML injection prevention. Thank you for the fast response!

**Comment by gauravano** [comment]
Great!

**Comment by ckairen** [comment]
Hi @gauravano I've submitted my PR, please let me know if I'm doing it correctly or not. : )

**Comment by gauravano** [comment]
Hi @ckairen, reviewing your PR. Thanks! (And, apologies for the delay!)
