### ISSUE TITLE
redundant trending topics

### ISSUE THREAD

**Issue by avsingh999** [publiclab/plots2#3388]
### Please describe the problem (or idea)
In dashboard page there is a  trending topics But here is one trending topics  iterate 4 times
![taring](https://user-images.githubusercontent.com/25536022/45918335-15d49480-bea3-11e8-9fa2-b2d0c3769099.png)

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/dashboard

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.

**Comment by SidharthBansal** [comment]
Can you turn this into a first timer issue?
Add code links as we do in ftos eg #3386.
This will be really helpful to us.


Also mark the issue as ``Only for google code in`` students.
This issue is already reserved for GCI students as per list in #3276.
Please have a look on the list. The issues in the list are for only GCI folks

Thanks

**Comment by SidharthBansal** [comment]
Are you looking forward to be a Google Code in mentor @avsingh999 ?
If so please fill the form https://docs.google.com/forms/d/e/1FAIpQLScSBS-ddZN2H-lviUJbKlbV2VwP21fdIutXOCBzigRhmXJybw/viewform

**Comment by avsingh999** [comment]
@SidharthBansal  Thank you

**Comment by SidharthBansal** [comment]
jeff has already made it in #3188

**Comment by jywarren** [comment]
But we could really use help with solving #3188! Thanks!
