### ISSUE TITLE
External sites cannot display publiclab.org content in iframes

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#339]
Sorry, moving this to our internal tracker for security/server issues, as it's not related to code. https://github.com/jywarren/web/issues/17

**Comment by icarito** [comment]
So which should it be, DENY or SAMEORIGIN ? I've disabled both, they
were recommended by the SSL configuration documentation.

On 10/11/15 14:58, Jeffrey Warren wrote:
>
> @icarito <https://github.com/icarito>, I get these two errors at
> http://spectralworkbench.org/dashboard:
>
>     Multiple 'X-Frame-Options' headers with conflicting values ('DENY,
>     SAMEORIGIN') encountered when loading
>     'https://publiclab.org/widget/spectrometer'. Falling back to 'DENY'.
>
>     Refused to display 'https://publiclab.org/widget/spectrometer' in
>     a frame because it set 'X-Frame-Options' to 'DENY, SAMEORIGIN'.
>
> I checked, and https://publiclab.org/widget/spectrometer does indeed
> have X-Frame-Options header set to 'DENY, SAMEORIGIN'. Was this not
> previously the case? Can we change it in the nginx configuration?
>
> Both Spectral Workbench and MapKnitter now have missing content on
> their dashboard pages with this error. It's more urgent for
> SpectralWorkbench:
>
> screenshot 2015-11-10 at 2 57 40 pm
> <https://cloud.githubusercontent.com/assets/24359/11074024/6c891c46-87bb-11e5-984a-58da991b2c02.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/publiclab/plots2/issues/339>.
>

-- 
I+D SomosAzucar.Org
"icarito" #somosazucar en Freenode IRC
"Nadie libera a nadie, nadie se libera solo. Los seres humanos se liberan en comunión" - P. Freire

**Comment by icarito** [comment]
Removing both headers seems to have fixed it.

On 10/11/15 15:00, Sebastian Silva wrote:
> So which should it be, DENY or SAMEORIGIN ? I've disabled both, they
> were recommended by the SSL configuration documentation.
>
> On 10/11/15 14:58, Jeffrey Warren wrote:
>>
>> @icarito <https://github.com/icarito>, I get these two errors at
>> http://spectralworkbench.org/dashboard:
>>
>>     Multiple 'X-Frame-Options' headers with conflicting values
>>     ('DENY, SAMEORIGIN') encountered when loading
>>     'https://publiclab.org/widget/spectrometer'. Falling back to 'DENY'.
>>
>>     Refused to display 'https://publiclab.org/widget/spectrometer' in
>>     a frame because it set 'X-Frame-Options' to 'DENY, SAMEORIGIN'.
>>
>> I checked, and https://publiclab.org/widget/spectrometer does indeed
>> have X-Frame-Options header set to 'DENY, SAMEORIGIN'. Was this not
>> previously the case? Can we change it in the nginx configuration?
>>
>> Both Spectral Workbench and MapKnitter now have missing content on
>> their dashboard pages with this error. It's more urgent for
>> SpectralWorkbench:
>>
>> screenshot 2015-11-10 at 2 57 40 pm
>> <https://cloud.githubusercontent.com/assets/24359/11074024/6c891c46-87bb-11e5-984a-58da991b2c02.png>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/publiclab/plots2/issues/339>.
>>
>
> -- 
> I+D SomosAzucar.Org
> "icarito" #somosazucar en Freenode IRC
> "Nadie libera a nadie, nadie se libera solo. Los seres humanos se liberan en comunión" - P. Freire

-- 
I+D SomosAzucar.Org
"icarito" #somosazucar en Freenode IRC
"Nadie libera a nadie, nadie se libera solo. Los seres humanos se liberan en comunión" - P. Freire
