### ISSUE TITLE
[Facebook Like] allowed on question while logged in from Google Auth

### ISSUE THREAD

**Issue by YashishDua** [publiclab/plots2#3390]
The user is allowed to Facebook Like the question when logged in from Google Auth and even count of likes updates.

![screen shot 2018-09-22 at 9 49 23 pm](https://user-images.githubusercontent.com/20666950/45919381-10327b00-beb2-11e8-93d4-0379132f3f67.png)

![screen shot 2018-09-22 at 9 49 37 pm](https://user-images.githubusercontent.com/20666950/45919390-1b85a680-beb2-11e8-87c5-6657c569ab73.png)

Two cases:
1. If this like button counts itself irrespective of auth:
    No point of having it since we already have a start button on the top right for liking
2. If this like button uses facebook Auth:
    It actually is not using the auth service.

Example Scenario: https://publiclab.org/questions/TK_Siddharth/09-20-2018/what-would-be-the-day-to-day-use-of-spectroscopy

**Comment by SidharthBansal** [comment]
Are you looking forward to be a Google Code in mentor @avsingh999 ?
If so please fill the form https://docs.google.com/forms/d/e/1FAIpQLScSBS-ddZN2H-lviUJbKlbV2VwP21fdIutXOCBzigRhmXJybw/viewform

**Comment by YashishDua** [comment]
Alright, and I am taking up this issue @SidharthBansal

**Comment by YashishDua** [comment]
Things we can do:
1. Allow facebook like only if logged in with Facebook Auth
2. Replace Facebook like with Facebook Share
3. Remove this button, since we already have a feature to like the question.
@gauravano @SidharthBansal 
How should we take this further?

**Comment by SidharthBansal** [comment]
Hi, you can work on it but please wait for jeff input.
We already have the facebook and twitter like buttons long before OAuth was introduced. I am seeing these buttons since last 3 years. Oauth is introduced since last 2 months.
When you click on like button then the PL post is posted on fb. This is the current functionality, I guess.

Now @YashishDua wants to connect it to OAuth. Tell me if I am wrong @YashishDua. It will be great if you will connect both of them and allow users to post to their facebook accounts

**Comment by SidharthBansal** [comment]
@jywarren I want your input here before he starts working.
Whenever you are free please tell what you think we should do here.

**Comment by YashishDua** [comment]
Clicking the facebook like just increments the counter, there is no posting.
Preferably, Either we should make this a share button or remove.

**Comment by YashishDua** [comment]
That social tab contains another button which lets you tweet the question, and I think the facebook button should follow the similar functionality i.e to share not to like since we already have star feature for that.

If the PL and Fb accounts are linked, let's allow the user to share and in case it's not, will prompt him to sign up first.

**Comment by SidharthBansal** [comment]
Yeah we both want similar behaviour. Let's wait for Jeff input then you can start working on it.
Thanks

**Comment by jywarren** [comment]
Ah, sorry, catching up! I see what you're saying about sharing on facebook
vs liking. I'd be happy to accept a changed action. We may also want to
adjust the display for fontawesome icons if that's possible... but it could
be done in a separate issue if you like:

https://fontawesome.com/v4.7.0/

**Comment by YashishDua** [comment]
@jywarren In this issue, let's convert the facebook like to share?
And I will open up a new issue for fonts.

**Comment by SidharthBansal** [comment]
Great go ahead for the first step

**Comment by jywarren** [comment]
Ah, this was completed long ago, thanks!!!
