### ISSUE TITLE
Remove dynamic_serch

### ISSUE THREAD

**Issue by milaaraujo** [publiclab/plots2#3396]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Remove** this file [app/assets/javascripts/dynamic_search.js](https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/dynamic_search.js)

- [ ] 📝 **Remove** line 9 on this file [config/initializers/assets.rb](https://github.com/publiclab/plots2/blob/cda8e40bf9edcc58e0beb3c2b5ead872a3e7f327/config/initializers/assets.rb#L9)

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in green (and a +) with the line to change, just change "search" with "profile":

```diff
  'dragdrop.js',
  - 'dynamic_search.js',
  'editor.js',
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :slightly_smiling_face:

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by SidharthBansal** [comment]
Will you mind labelling this as gci candidate for google code in?
Thanks

**Comment by neel1998** [comment]
I would like to work on this one.

**Comment by SidharthBansal** [comment]
Go ahead

**Comment by neel1998** [comment]
I am new to open source ..So can you give me a head start..

**Comment by gauravano** [comment]
Hi @neel1998, welcome to the awesome world of Open Source and Public lab, please see these https://github.com/publiclab/plots2#installation instructions and then start with this issue by making a separate branch. Feel free to ask if you have any doubt. Thanks!
