### ISSUE TITLE
Open Store in Navbar in a new tab

### ISSUE THREAD

**Issue by rbhatia46** [publiclab/plots2#3403]
```We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.```

Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source 
before.**

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step
- [ ] 🙋 **Claim this issue:** Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** line 73 on this file [app/views/layouts/_header.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/layouts/_header.html.erb) and add the target attribute to open this link in a new tab. 
Just change ```<a href="//store.publiclab.org"><%= t('layout._header.store') %></a>``` with
 ```<a target="_blank" href="//store.publiclab.org"><%= t('layout._header.store') %></a>```

- [ ]  💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request.** There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository) and open a pull request from there.

- [ ]  🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?
Leave a comment below!

### Is someone else already working on this?
We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by SidharthBansal** [comment]
This issue needs input from @bronwen9
As discussed in #3350. This issue can't be claimed before their input.

**Comment by jywarren** [comment]
I think this one is ok! Bronwen is at a workshop all today so I can give
👍🏽 for her!

**Comment by Rohit280297** [comment]
heyy...is this issue still open ?  If yes, I would like to work on this. Or else, I would highly appreciate anyone suggesting me any issue to work upon. Thanks ;-)

**Comment by jywarren** [comment]
It is, but we are holding it for Google Code-In! However, you can look at https://code.publiclab.org#r=all for more available issues. 👍 😄

**Comment by SidharthBansal** [comment]
Hi this issue is meant for gci students, not for mentors. You can checkout other issues which does not have ''gci candidate " tag.
You cannot work on this. Sorry
