### ISSUE TITLE
Digest email bug

### ISSUE THREAD

**Issue by ViditChitkara** [publiclab/plots2#3404]
The digest emails are currently not being sent. 
`ArgumentError: wrong number of arguments (given 0, expected 1)` is shown on Sidekiq dashboard (https://publiclab.org/sidekiq/retries).

**Comment by jywarren** [comment]
I dug up the log for this on the server too!

```
2018-09-23T17:01:50.908Z 1 TID-gogckya6x DigestMailJob JID-09573ed86ee039fe4c77e804 INFO: fail: 0.017 sec  
2018-09-23T17:01:50.909Z 1 TID-gogckya6x WARN: {"context":"Job raised exception","job":{"class":"DigestMailJob","args":[],"retry":true,"queue":"default","jid":"09573ed86ee039fe4c77e804","created_at":1537644781.5130486,"enqueued_at":1537722110.8390274,"error_message":"wrong number of arguments (given 0, expected 1)","error_class":"ArgumentError","failed_at":1537644781.8256888,"retry_count":12,"retried_at":1537707061.948535},"jobstr":"{\"class\":\"DigestMailJob\",\"args\":[],\"retry\":true,\"queue\":\"default\",\"jid\":\"09573ed86ee039fe4c77e804\",\"created_at\":1537644781.5130486,\"enqueued_at\":1537722110.8390274,\"error_message\":\"wrong number of arguments (given 0, expected 1)\",\"error_class\":\"ArgumentError\",\"failed_at\":1537644781.8256888,\"retry_count\":12,\"retried_at\":1537707061.948535}"}  
2018-09-23T17:01:50.910Z 1 TID-gogckya6x WARN: ArgumentError: wrong number of arguments (given 0, expected 1)  
2018-09-23T17:01:50.910Z 1 TID-gogckya6x WARN: /app/app/jobs/digest_mail_job.rb:4:in `perform' 
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:185:in `execute_job'  
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:167:in `block (2 levels) in process'  
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'  
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/middleware/chain.rb:133:in `invoke'  
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:166:in `block in process'  
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'  
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/job_retry.rb:98:in `local'  
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'  
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/rails.rb:42:in `block in call'  
/usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'
/usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/reloader.rb:73:in `block in wrap'
/usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'
/usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/reloader.rb:72:in `wrap'  
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/rails.rb:41:in `call'  
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'  
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:217:in `stats'  
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'  
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/job_logger.rb:8:in `call'  
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'  
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/job_retry.rb:73:in `global'  
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:125:in `block in dispatch'  
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/logging.rb:48:in `with_context'  
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/logging.rb:42:in `with_job_hash_context'  
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:124:in `dispatch'  
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:165:in `process'  
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:83:in `process_one'  
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/processor.rb:71:in `run'  
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/util.rb:16:in `watchdog'  
/usr/local/bundle/gems/sidekiq-5.2.1/lib/sidekiq/util.rb:25:in `block in safe_thread' 
```

Key section:

```
2018-09-23T17:01:50.910Z 1 TID-gogckya6x WARN: ArgumentError: wrong number of arguments (given 0, expected 1)  
2018-09-23T17:01:50.910Z 1 TID-gogckya6x WARN: /app/app/jobs/digest_mail_job.rb:4:in `perform' 
```

It looks like we are asking for a parameter in `peform(frequency)` but when it's called it's not getting the parameter

https://github.com/publiclab/plots2/blob/cda8e40bf9edcc58e0beb3c2b5ead872a3e7f327/app/jobs/digest_mail_job.rb#L4

Vidit, do you know where `perform()` is called from and why it doesn't have a `frequency` param set?

**Comment by jywarren** [comment]
If you can identify the change we should make to fix it, and it's only a
few lines, then yeah, I think it'd make a great FTO!

**Comment by ViditChitkara** [comment]
I guess, there isn't any syntactical error. But the cronjobs are not updating according to schedule.rb.
@icarito do we need to specify environment in makefile when we deploy the latest code?

I did `whenever --update-crontab --set environment=development` to make the it work. I believe the same command needs to be done in the makefile with production instead.

https://github.com/publiclab/plots2/blob/2522459bfdc21068df2e0e808a8addc6726808e0/Makefile#L28

**Comment by jywarren** [comment]
Hmm, were you able to get past the "0 parameters where expected 1" error?

**Comment by ViditChitkara** [comment]
yeah I tested locally with 
`
every 1.minutes do
	runner "DigestMailJob.perform_async"
end
`
and
`
every 1.minutes do
	runner "DigestMailJob.perform_async(0)"
end
`

The same error occurred for the first one and worked perfectly for the latter one.

**Comment by ViditChitkara** [comment]
Its actually there in the code, right here:-
https://github.com/publiclab/plots2/blob/2522459bfdc21068df2e0e808a8addc6726808e0/config/schedule.rb#L31-L37
but the problem I guess is that, the crontab isn't updated after this code was deployed. It still assumes that no argument is passed with the function. Does this make sense?

**Comment by jywarren** [comment]
Ah, ok! Cool, do we track the crontab settings in git or is there a
reference to compare the production settings against?

Super it looks like you've got this going. Thanks!

**Comment by ViditChitkara** [comment]
I guess we can't directly view the cronjobs which are scheduled. It can be viewed by logging on the server only. All we need to do is make the update-crontab command run on production. Needs some more digging though. Will look into it.

**Comment by jywarren** [comment]
I can log in and look - but what should i be looking for? @icarito would
you mind trying to coordinate with Vidit on this one? Thanks!

**Comment by icarito** [comment]
```
$ RAILS_ENV=production docker-compose -f containers/docker-compose-production.yml exec web crontab -l


# Begin Whenever generated tasks for: /app/config/schedule.rb at: 2018-10-04 21:39:15 +0000
* * * * * /bin/bash -l -c 'date -u >> /app/public/cron_log.log 2>&1'

0 0 * * * /bin/bash -l -c 'cd /app && bundle exec bin/rails runner -e production '\''DigestMailJob.perform_async(0)'\'' >> /app/public/cron_log.log 2>&1'

0 0 1,8,15,22 * * /bin/bash -l -c 'cd /app && bundle exec bin/rails runner -e production '\''DigestMailJob.perform_async(1)'\'' >> /app/public/cron_log.log 2>&1'

# End Whenever generated tasks for: /app/config/schedule.rb at: 2018-10-04 21:39:15 +0000
```

**Comment by icarito** [comment]
```
$ RAILS_ENV=production docker-compose -f containers/docker-compose-production.yml exec web service cron status
[ ok ] cron is running.
```

**Comment by jywarren** [comment]
Ah ok so can we figure out how the crontab was originally set and then
update it to include the new parameter format?

**Comment by jywarren** [comment]
OK, i changed the test digest code to:

`DigestMailJob.perform_async(0)` where it had lacked the parameter. Now we have to figure out why the daily/weekly ones aren't running, which should be a different issue. 

I tried running `DigestMailJob.perform_async(0)` on the rails console on the production machine, in production mode. But didn't get an email. Looking at logs now.

**Comment by jywarren** [comment]
OK, i ran `user.send_digest_email`

```
  Rendered subscription_mailer/send_digest.html.erb (508.9ms)
SubscriptionMailer#send_digest: processed outbound mail in 557.7ms
ActionView::Template::Error: undefined local variable or method `node' for #<#<Class:0x000055b3ad5f1598>:0x000055b3ad5af238>
        from app/views/subscription_mailer/send_digest.html.erb:33:in `block in _app_views_subscription_mailer_send_digest_html_erb___3263606767765639606_47115098102720'
        from app/views/subscription_mailer/send_digest.html.erb:10:in `_app_views_subscription_mailer_send_digest_html_erb___3263606767765639606_47115098102720'
        from app/mailers/subscription_mailer.rb:61:in `send_digest'
        from app/models/user.rb:404:in `send_digest_email'
        from (irb):5
```

We should be testing `send_digest_email`!

**Comment by jywarren** [comment]
Also I wonder if there's a version mismatch on the ActiveJob we're working with... it says there is no method `perform_later` although the latest Rails Guides say that should work... i likewise don't see docs for `perform_async` in the current rails guids: https://guides.rubyonrails.org/active_job_basics.html

**Comment by jywarren** [comment]
Made a test for `user.send_digest_email` in https://github.com/publiclab/plots2/pull/4305 !

**Comment by jywarren** [comment]
Digest emails now send when we press the test button on profile pages! 

Later: fix formatting/images/bio profile pics of the digest!

Scheduled sends don't work - for some reason, the setting at https://publiclab.org/settings keeps getting switched off! It stays on for a little while but then gets disabled the next day... not sure how this happens!

![image](https://user-images.githubusercontent.com/24359/50652635-1fb36c80-0f55-11e9-97be-5f3f09ad6cf0.png)

**Comment by jywarren** [comment]
OK, attempted fix in https://github.com/publiclab/plots2/pull/4523 -- it looks like the code was deleting ALL digest user tags for all users, rather than just for one user! Eek!

Hopefully this fixes it!

**Comment by icarito** [comment]
It looks like the `whenever` runner is not finding the gems, because cron gives it a clean environment ( without some environment variables we need ). I've attempted a fix with https://github.com/publiclab/plots2/pull/4619/commits . How do you test it?

**Comment by jywarren** [comment]
Maybe some clues here?
https://github.com/javan/whenever/search?utf8=%E2%9C%93&q=environment&type=

Seems there are some ways to set it...

**Comment by jywarren** [comment]
ah! what about:
https://github.com/javan/whenever/issues/732#issuecomment-404576122

**Comment by icarito** [comment]
I tried a couple of alternatives https://github.com/publiclab/plots2/pull/4619/commits/4288bf797b3b249d97a51e0ca4135f2fab1e11a7 adding to `config/schedule.rb` but didn't succeed yet. Looking for ideas!

**Comment by icarito** [comment]
Hi!,
I've pinpointed the issue, child jobs don't inherit the app environment so we have to pass variables like this:
https://github.com/publiclab/plots2/pull/4619/files

With these variables (PATH, GEM_HOME, SECRET_KEY_BASE, and REDIS_URL), I don't get a trace in `unstable`, but no email attempt either. Perhaps more environment variables are needed?

We're so close! Please merge #4619 and let's see!

**Comment by jywarren** [comment]
Yes!!!!!!
