### ISSUE TITLE
Generalise the different routes on profile page.

### ISSUE THREAD

**Issue by bajajerk** [publiclab/plots2#3406]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

![screen shot 2018-09-23 at 11 10 29 pm](https://user-images.githubusercontent.com/29681232/45931119-adf77a00-bf86-11e8-987d-aeddaed205ab.png)

This is from https://publiclab.org/profile/YOUR_USERNAME .
Observed it Chrome , MAC.

> What did you expect to see that you didn't?
``` 
0 answers posted
 ```
 should be of same color and type like others , also others are clickable besides the fact that they are zero too.

**Comment by bajajerk** [comment]
@jywarren  @SidharthBansal  
Please check if its needed

**Comment by avsingh999** [comment]
@bajajerk  @jywarren  @SidharthBansal  If it's needed I would like to work on it

**Comment by jywarren** [comment]
I think we'll have to make a new display of `Answers by an author` - a list page, perhaps. I think we don't have that page yet, and are generally planning to merge answers with comments, so perhaps we should hold off on this for now! 

@bajajerk if you want to make a new issue, please check out this template to learn how to craft one for newcomers! Thank you! 

https://publiclab.org/n/13667
