### ISSUE TITLE
CERN Open Hardware License 1.1.  page not found

### ISSUE THREAD

**Issue by avsingh999** [publiclab/plots2#3408]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Please describe the problem (or idea)
when click on this CERN Open Hardware License 1.1 then It's goes to no page found  and there is back button not work
![licence](https://user-images.githubusercontent.com/25536022/45932112-5b718a00-bf95-11e8-9d97-6298a03d8c8b.png)

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look
this link is in footer but u can go by also this llink
https://www.ohwr.org/cernohl
https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Good find! Can you find an up to date link to the OHL 1.1 ? We can make a first-timers-only issue for this!

**Comment by avsingh999** [comment]
@jywarren I think  that link is https://publiclab.org/wiki/cern-ohl-11

**Comment by avsingh999** [comment]
@jywarren  please assign me if this is right because I don't have  any pr

**Comment by jywarren** [comment]
Actually this is stored in the database, not the code, so I've gone ahead and fixed it with the link you've supplied. Great work! If you're interested, please check out https://code.publiclab.org for another issue! Thanks!

**Comment by vikul1234** [comment]
@jywarren  I want to work on this

**Comment by SidharthBansal** [comment]
@vikul1234 on this issue only jeff can work. You can try other issues.
@jywarren can we close this issue as I assume that you have already changed the required link as you are very quick :smile:

**Comment by igniteeng000** [comment]
It's working so closing this issue.

**Comment by jywarren** [comment]
:-) thank you!
