### ISSUE TITLE
Don't search for " " (spacebar character) in navbar typeahead search

### ISSUE THREAD

**Issue by avsingh999** [publiclab/plots2#3409]
### Please describe the problem (or idea)
In header there is search, It's searching also space which is not good.
![search](https://user-images.githubusercontent.com/25536022/45932253-3d0c8e00-bf97-11e8-99b1-f54c5d9a2bc8.png)

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?
first char in search cann't be space

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?
999_avsingh999
> This can help us diagnose the issue: 

### Browser, version, and operating system
chrome ubuntu 16
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by avsingh999** [comment]
@jywarren I want to work on this If it's required

**Comment by avsingh999** [comment]
@jywarren please review about this issue

**Comment by stefannibrasil** [comment]
If you are willing to help, go ahead, that would be amazing! :)

this is something that we began here, so it may help take a look at [this commit](https://github.com/publiclab/plots2/pull/3357/commits/d57183f6869bad4289a6ca7c4061218e0701907f) first

**Comment by jywarren** [comment]
I believe this is fixed due to https://github.com/publiclab/plots2/pull/4904 ! Thank you!
