### ISSUE TITLE
Improve methods page button placement

### ISSUE THREAD

**Issue by avsingh999** [publiclab/plots2#3410]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Instance count 1
Field: Training

Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**  https://publiclab.org/methods in this page there is shown posts are not in perfect view, Read more buttons collapse to other posts

![methods](https://user-images.githubusercontent.com/25536022/45932403-44cd3200-bf99-11e8-8ae1-52691148e069.png)

(https://github.com/publiclab/plots2/blob/c9f5a33a0eeecbbd7e49cfde8acea78fccd73aef/app/views/notes/_notes.html.erb)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by jywarren** [comment]
Great catch! This could be a great issue for a newcomer to solve!

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://publiclab.github.io/community-toolbox/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by SidharthBansal** [comment]
You can create a new one with first timer only template as Jeff asked you. Then we will close this one.

**Comment by SidharthBansal** [comment]
#3457

**Comment by SidharthBansal** [comment]
Do this issue after you have created issue for #3421. Don't hurry up. We all are there to help you.

**Comment by avsingh999** [comment]
@SidharthBansal @jywarren  I have edited this issue for GCI please check it

**Comment by SidharthBansal** [comment]
Well done.
3 suggestions
1. You missed to write problem statement before proposing a soln
2. Add permanent link of lines of code
3. Open a new issue for this and close this one. Link this to it as here new comer will face difficulty to understand what was going on in the comments.

Thanks great job

**Comment by avsingh999** [comment]
@SidharthBansal  @jywarren   there is another problem in this page here number of like  u can see here are not good should I create another issue for this or  include in this
![star](https://user-images.githubusercontent.com/25536022/46222463-086d4d80-c36e-11e8-85ee-420496b5bca2.png)

![another](https://user-images.githubusercontent.com/25536022/46222340-97c63100-c36d-11e8-9222-698b74314a83.png)

**Comment by jywarren** [comment]
ah, interesting. is there a CSS rule to prevent breaking a line in a
situation like this?

**Comment by avsingh999** [comment]
@jywarren @SidharthBansal  I have created another issue with formating
