### ISSUE TITLE
 Searched people profile not link proficiently

### ISSUE THREAD

**Issue by avsingh999** [publiclab/plots2#3422]
### Please describe the problem (or idea)
when searching people it's search perfect but

![search1](https://user-images.githubusercontent.com/25536022/45967076-82d65e80-c04a-11e8-87d0-dfaaeee732cb.png)

when I click on that people It's going to this page

![search2](https://user-images.githubusercontent.com/25536022/45967033-64706300-c04a-11e8-8315-4e23c9f5e9a3.png)

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

when I click on searched people name It's should be go to that people profile

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system
chrome ubuntu 16
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by avsingh999** [comment]
@jywarren  It's looking for newcommer

**Comment by stefannibrasil** [comment]
hi, thank you, I already created an issue and someone already fixed it, here #3420, just waiting for it to be merged!

sorry for the inconvenience, it will be live soon :)

**Comment by avsingh999** [comment]
@stefannibrasil  thanks
