### ISSUE TITLE
Simple UI improvement for blockquote responses in reply by email comment

### ISSUE THREAD

**Issue by namangupta01** [publiclab/plots2#3425]
For conversation threads, when we click on the toggle button, the reply comments show up in a larger font size than the original comments.

So we can have some basic improvement in this such as: 
 Border padded blockquotes with a light background colour and a smaller font size to differentiate with the original comments.

![whatsapp image 2018-09-24 at 11 45 23 pm](https://user-images.githubusercontent.com/20709985/45972052-4f023580-c058-11e8-8e8e-9f7ff4bb0bd8.jpeg)

**Comment by shivani-kapania** [comment]
Hello, yes I'd like to try this issue. Thanks a lot! 👍

**Comment by namangupta01** [comment]
Go ahead!
