### ISSUE TITLE
Expand reply-by-email feature For outlook

### ISSUE THREAD

**Issue by namangupta01** [publiclab/plots2#3426]
```We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.```

Currently in `reply-by-email` feature we support parsing of email for google, yahoo and the domains that are using google service.
And as this feature is working stable, we can add the feature of parsing outlook mail so that `reply-by-email` support one more domain.
To implement this feature, starting point is https://github.com/publiclab/plots2/blob/master/app/models/comment.rb#L261

**Comment by nonas-hunter** [comment]
Hi, I am a GCI Participant and I want to add this feature. I have written some code but have no idea how to test it. Could anyone help?

**Comment by oorjitchowdhary** [comment]
@publiclab/mentors pls add this task to gci dashboard.. It isn't there right now

**Comment by SidharthBansal** [comment]
Thanks @oorjitchowdhary for pointing it out.
I will create it now.
https://codein.withgoogle.com/dashboard/tasks/6068848605265920/
is the task

**Comment by kevinzluo** [comment]
@SidharthBansal Since GCI is coming to an end soon, would you mind if I worked on this task now even though my previous one ([here](https://github.com/publiclab/leaflet-environmental-layers/pull/104)) has not yet been approved?

If not, that is perfectly fine.

Thank you,
Kevin Luo

**Comment by SidharthBansal** [comment]
All GCI students can work on around 3 tasks at a time. I will not mind
