### ISSUE TITLE
Add remaining unit tests for reply-by-email feature functions in comment model

### ISSUE THREAD

**Issue by namangupta01** [publiclab/plots2#3435]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

There are some functions in `reply-by-email` feature in comment model for which there are no unit tests.
We can add them in test/unit/comment_test.rb

https://github.com/publiclab/plots2/blob/faa03523b35ccaddd26f4bfc00a2c0bcce591b5b/app/models/comment.rb#L224

https://github.com/publiclab/plots2/blob/faa03523b35ccaddd26f4bfc00a2c0bcce591b5b/app/models/comment.rb#L261

https://github.com/publiclab/plots2/blob/faa03523b35ccaddd26f4bfc00a2c0bcce591b5b/app/models/comment.rb#L291

https://github.com/publiclab/plots2/blob/faa03523b35ccaddd26f4bfc00a2c0bcce591b5b/app/models/comment.rb#L299

https://github.com/publiclab/plots2/blob/faa03523b35ccaddd26f4bfc00a2c0bcce591b5b/app/models/comment.rb#L315

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by dinaelhanan** [comment]
Hi! I'm thinking of taking this task, and since I'm new to this, I'm just wondering, what is it that we testing for? thanks!

**Comment by dinaelhanan** [comment]
Is the above a correct way to do this? @SidharthBansal  cc @jywarren

**Comment by gauravano** [comment]
Hi @dinaelhanan, how about opening the PR so that other people and checks can be run? Thanks!

**Comment by dinaelhanan** [comment]
@namangupta01 I will work on the other functions to be tested, but the one I just fixed should be removed :)

**Comment by namangupta01** [comment]
Okay, I will add them tomorrow. You can start working on them.

**Comment by dinaelhanan** [comment]
Thanks!
