### ISSUE TITLE
Add unit tests for Outlook reply-by-email feature

### ISSUE THREAD

**Issue by namangupta01** [publiclab/plots2#3436]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

This is dependent on https://github.com/publiclab/plots2/issues/3426
After the completion of https://github.com/publiclab/plots2/issues/3426, we can add unit tests for this feature as well

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by oorjitchowdhary** [comment]
I have completed #3426 and want to add unit tests for it.. Are there any instructions for running unit tests?
