### ISSUE TITLE
Add integration tests for outlook in reply-by-email feature

### ISSUE THREAD

**Issue by namangupta01** [publiclab/plots2#3437]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

This is dependent on #3426
After the completion of #3426, we can add integrations tests for this feature as well

**Comment by jywarren** [comment]
This is related to filtering all signature types, here! https://github.com/publiclab/plots2/issues/3218

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by CodeSarthak** [comment]
Hi, this task is redundant on GCI as this is dependent on #3426 . Either #3426 should also be added on GCI or this should be removed from GCI. @publiclab/reviewers @jywarren @SidharthBansal

**Comment by oorjitchowdhary** [comment]
> Hi, this task is redundant on GCI as this is dependent on #3426 . Either #3426 should also be added on GCI or this should be removed from GCI. @publiclab/reviewers @jywarren @SidharthBansal

Right, @CodeSarthak .. I think we should add #3426 to the GCI platform.. as we're already very low on non-beginner tasks

**Comment by oorjitchowdhary** [comment]
@namangupta01 @jywarren @publiclab/reviewers I have solved #3426 in #4045 ... Now I'm looking forward to adding the unit tests first #3436 and then add integration tests #3437 ..So how will get the credits on the gci dash.. as there is only one task on GCI which is #3437

**Comment by jywarren** [comment]
Is this completed? Thank you!
