### ISSUE TITLE
Make "Test Digest Email" button on profile page viewable to admins only

### ISSUE THREAD

**Issue by avsingh999** [publiclab/plots2#3440]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Please describe the problem (or idea)
In user profile page there is a Button Test Digest Email. It's not looking good .
add some style 

![button](https://user-images.githubusercontent.com/25536022/45980082-b2975d80-c06e-11e8-978c-656aff305d38.png)

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ profile/user_name

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
this'd be great. It could use the class names `class="btn btn-default"`
like the others there. Can you help point at the lines of code that need to
be changed as in https://github.com/publiclab/plots2/issues/3424 ?

**Comment by SidharthBansal** [comment]
I think this button needs to be removed. @viditchitkara used to test the features in Gsoc. So may be we don't need it now?

**Comment by ViditChitkara** [comment]
It has got some bugs too. Shouldn't it be available for admins or some smaller grp of users only??

**Comment by avsingh999** [comment]
@jywarren in this file   line 221
https://github.com/publiclab/plots2/blob/1b3cd0802d5a16436602afc373f56e1ae2ade2f1/app/views/users/profile.html.erb

**Comment by SidharthBansal** [comment]
So instead of changing the style of the button we can display the button only to admins and moderators. We can create nice gci issues for them and their respective tests. Let's see what Jeff says

**Comment by SidharthBansal** [comment]
Nice catch @avsingh999

**Comment by avsingh999** [comment]
@SidharthBansal  thank you

**Comment by avsingh999** [comment]
@SidharthBansal @jywarren should i add access group to the button.

**Comment by SidharthBansal** [comment]
No you don't need to add access button to it. 
Instead we need to 
1. Write code in the view files that this button is only visible to admins or moderators.
We don't want this button to be shown to general public. 
2. We need to write test that this button is seen by admin
3. We need to write test that this button is seen by moderators
4. We need to write test that this button is not seen by normal users.

**Comment by SidharthBansal** [comment]
Will you want to work on this?

**Comment by avsingh999** [comment]
yes I want to work on it

**Comment by SidharthBansal** [comment]
OK go ahead. This issue is broken into sub issues as listed above. So do things part by part. We highly focus on modularity.
Thanks

**Comment by noi5e** [comment]
@jywarren I'm an Outreachy applicant. Can you assign me to this issue please? :)

**Comment by jywarren** [comment]
awesome! Please go ahead! Thanks!

**Comment by noi5e** [comment]
Okay, I got the site up and running locally, and it looks like this issue has been taken care of already:

<img width="1440" alt="Screen Shot 2020-10-12 at 1 17 04 PM" src="https://user-images.githubusercontent.com/4361605/95787187-d9dd1980-0c8d-11eb-8307-2b391d299d83.png">

Maybe close this issue? However I did notice that the "More User Info" modal on the Profile page doesn't work in Firefox, so I think I'll make a new issue for that.

**Comment by cesswairimu** [comment]
Thanks @noi5e, closing this
