### ISSUE TITLE
Optimize users query in Srch API

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3443]
Looks like we're seeing some site slowdowns due to a search query:

```
Srch::Search [GET] srch/all
Response Time | 35,831ms
```

```SELECT  DISTINCT `rusers`.* FROM `rusers` INNER JOIN `node` ON `node`.`uid` = `rusers`.`id` INNER JOIN `node_revisions` ON `node_revisions`.`nid` = `node`.`nid` WHERE (MATCH(bio, username) AGAINST(? IN BOOLEAN MODE)) AND (rusers.status = ?) ORDER BY node_revisions.timestamp DESC LIMIT ?```

You can see it appearing in Skylight: https://oss.skylight.io/app/applications/GZDPChmcfm1Q/1536553680/12h/endpoints

Can we optimize this more? Could an index like this: https://github.com/publiclab/plots2/pull/3380/files

or is there something else we can do here? I'm seeing worst-case load times of 70-90 seconds... pretty bad! But I'm sure we can figure something out 😄 

@milaaraujo @stefannibrasil what do you think?

**Comment by jywarren** [comment]
Maybe the match against bio and username together is a heavy query... but we are narrowing by status... what if we also said `node.status = 1` so we exclude users who have only unapproved posts (mostly spammers)? That could make a difference. 

I think we could make a first-timers issue of that if we can get a link to the line of code where this query is made!

**Comment by milaaraujo** [comment]
> what if we also said node.status = 1 so we exclude users who have only unapproved posts (mostly spammers)? 

Well, I really don't know... Do you have an estimate of how many users are spammers? But the lines of code are: https://github.com/publiclab/plots2/blob/136b448931f49d8c0baa8bbf79936bcf00e94ad7/app/services/search_service.rb#L37-L40

But maybe we could try to search only by username in the search/all endpoint? I can open a PR with this modification now, so we can see if this helps.

**Comment by jywarren** [comment]
We've had some strong requests to retain searching by bio, so i'd like to
try to keep that in. There are roughly 300k spammers so I think this could
make a difference, although not all of them have nodes... I think it's
worth a try!

Thanks for the code links. If the node.status filter doesn't work we can
consider other options.

**Comment by milaaraujo** [comment]
Yep, we have a lot of spammers. Well, I opened two PR with the different suggestions. I was hoping to compare the two and see which one really works. But you can just ignore my PRs and use  #3445 to open a first-timer issue if you want. :)

search/all/(profile): search only by username as default #3444
Profiles method only join nodes where(node_revisions.status = 1) #3445

**Comment by jywarren** [comment]
if you'd like to push your PRs to unstable to test them out, that could
work -- leave the network monitor pane open and see how long they take on a
full database? But i could also start by merging #3445 -- your call!

**Comment by milaaraujo** [comment]
Well, if `node.status = 1` excludes users who have only unapproved posts (mostly spammers), I think merging #3445 will not hurt!

**Comment by jywarren** [comment]
OK awesome -- let's try it and see what happens. Thanks!
