### ISSUE TITLE
Enhance readability of text in small screens

### ISSUE THREAD

**Issue by geekychaser** [publiclab/plots2#3450]
```We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.```

Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the text color of **username**,**password**,**remember me** to white so that it is visible in mobile browser
![color_problem](https://user-images.githubusercontent.com/24489162/46003987-6defde80-c0cf-11e8-8f97-c556527c24b8.jpeg)

The above text is displayed on the dashboard whenever a person signs up at Public Labs for teh first time
- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by SidharthBansal** [comment]
Great work @geekychaser 
Thanks for making ftos.

**Comment by jywarren** [comment]
Hi this looks great! However, to be a `first-timers-only` issue it does need a link to the code -- see https://github.com/publiclab/plots2/issues/3424

Then we can relabel it with `first-timers-only` -- thanks!!!

**Comment by oorjitchowdhary** [comment]
Hi, I think we can close this down as the login is no longer a dropdown... 
Here's how the current login looks on mobiles
1. on unstable (login modal)

![login modal](https://user-images.githubusercontent.com/39333058/49694628-a7ef5d80-fbb3-11e8-9f8a-fc83e3956494.gif)

**Comment by oorjitchowdhary** [comment]
2. on normal (login page)

![login page](https://user-images.githubusercontent.com/39333058/49694645-f56bca80-fbb3-11e8-9e50-76abbe6d5922.gif)

**Comment by SidharthBansal** [comment]
@oorjitchowdhary thanks
