### ISSUE TITLE
Remove extra horizontal line

### ISSUE THREAD

**Issue by geekychaser** [publiclab/plots2#3451]
```We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.```

Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** Remove that extra horizontal line at bottom
![issue](https://user-images.githubusercontent.com/24489162/46004942-c1632c00-c0d1-11e8-91f3-8fdd5a93ca5f.jpeg)

The above text is displayed on the dashboard whenever a person signs up at Public Labs for teh first time
- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by jywarren** [comment]
Can you add some code links please? https://github.com/publiclab/plots2/issues/3424 Thank you!!! 👍 👍 👍

**Comment by mcblake** [comment]
Hi! I am looking to add links to this issue. What page did you find this problem on? @geekychaser

**Comment by geekychaser** [comment]
@mcblake this is on home page i.e "https://publiclab.org/" .  You need to open this on your mobile phone

**Comment by romanrodriguez** [comment]
Hi @geekychaser, I like to claim this issue.

**Comment by romanrodriguez** [comment]
I'm sorry, I just realized that the first-timers-only had been removed. Could I use this contribution for Outreachy @geekychaser @jywarren?

**Comment by jywarren** [comment]
Hi, yes we removed the label because it doesn't quite lay out the exact steps to fix it, and lacks links to the right lines of code. But I will paste in a code link and I don't think itll be too complicated!

**Comment by jywarren** [comment]
I think the overall page is here:

https://github.com/publiclab/plots2/blob/master/app/views/home/home.html.erb

But it uses a partial template that is reused on many pages; we'll have to be sure the removed line doesn't break other pages like at /tag/test or /research or /dashboard...

https://github.com/publiclab/plots2/blob/master/app/views/notes/_notes.html.erb

This'd be fine to use for Outreachy! Thank you!!

**Comment by romanrodriguez** [comment]
Thank you!! I really like the code base! 

I was looking for potential breaks due to removing the grid part of it. I thought maybe I could include it in the first `<% unless @widget %><hr class="visible-xs visible-sm" /><% end %>`, but after looking at all the assets (stylesheets, etc.) I couldn't find the grid referenced anywhere else. It mostly seems to restraint the line's margins. It also wouldn't go well with the other line styles across the document that resemble this one. Thus, I left grid out.

Please let me know if I am missing something.
