### ISSUE TITLE
Redundant Search on Public Lab in Header dropdown

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#3457]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Instance count 1
Field: Training

Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem

Presence of redundant Search button in dropdown of the header of Public Labs. We need to remove the button from the dropdown

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** Remove that extra horizontal line at bottom``search on public lab`` from header

![image](https://user-images.githubusercontent.com/20972099/46018420-70fec500-c0f7-11e8-9142-76ee2e3a89b4.png)

Remove the following line
https://github.com/publiclab/plots2/blob/136b448931f49d8c0baa8bbf79936bcf00e94ad7/app/views/layouts/_header.html.erb#L38

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by AMI1995** [comment]
@SidharthBansal  I would like to claim this!

**Comment by SidharthBansal** [comment]
We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.
You can try other issues.
Thanks

**Comment by avsingh999** [comment]
Can you @SidharthBansal  provide markup for this template?

**Comment by SidharthBansal** [comment]
NO @oorjitchowdhary all the issue which are labelled with the `fto-candidate` or `first-timers-only`  label are specially designed for beginners. 
You can take on other tasks to help us.

**Comment by SidharthBansal** [comment]
Published https://codein.withgoogle.com/dashboard/tasks/5749268141834240/ on GCI dashboard
