### ISSUE TITLE
Fix the image size

### ISSUE THREAD

**Issue by geekychaser** [publiclab/plots2#3459]
### Please describe the problem (or idea)
Instagram images are not of equal size at Public Lab store.
![issue](https://user-images.githubusercontent.com/24489162/46022389-1e75d680-c100-11e8-922d-a17f6880749c.jpeg)

> What did you expect to see that you didn't?

All the images should be of equal sizes.

### Please show us where to look

https://store.publiclab.org/

### What's your PublicLab.org username?
geekychaser
> This can help us diagnose the issue: 

### Browser, version, and operating system

Chrome Browser on linux operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hi, unfortunately the store is not part of our codebase, but is run from
another application where we don't have as much control. There's plenty to
do however in https://github.com/publiclab/plots2/labels/break-me-up,
https://github.com/publiclab/plots2/labels/fto-candidate, and
https://github.com/publiclab/plots2/labels/planning, so perhaps you could
close this one and try to break out some small issues from those sources?
Thank you!

**Comment by SidharthBansal** [comment]
Btw great catch. You are doing a good job in creating fto issues and reporting bugs @geekychaser

**Comment by geekychaser** [comment]
okay sir
