### ISSUE TITLE
Option of selecting Deutsch language not working 

### ISSUE THREAD

**Issue by shivani-kapania** [publiclab/plots2#3463]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I selected Deutsch language from the footer of my dashboard.

> What did you expect to see that you didn't?

I expected to get the page translated into Deutsch language whereas that didn't happen. 
<img width="1268" alt="screen shot 2018-09-25 at 9 35 09 pm" src="https://user-images.githubusercontent.com/29448581/46027269-11aab000-c10b-11e8-8101-961f217d175f.png">

<img width="1267" alt="screen shot 2018-09-25 at 9 35 56 pm" src="https://user-images.githubusercontent.com/29448581/46027293-1e2f0880-c10b-11e8-89d4-0e918a803659.png">

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

shivanikapania

> This can help us diagnose the issue: 

I'll look for code links and add the same if I find it. 

### Browser, version, and operating system

Google Chrome, MacOS. 

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment]
Please see #3348 Thanks

**Comment by SidharthBansal** [comment]
Thanks for reporting bug
