### ISSUE TITLE
Header navbar runs out of space and covers content

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3464]
Our new header is very nice, but it needs to collapse a bit earlier; we use Bootstrap: https://getbootstrap.com/docs/3.3/

![screen shot 2018-09-25 at 12 07 09 pm](https://user-images.githubusercontent.com/24359/46027518-0a0fea80-c0bc-11e8-8009-c15002d78f41.png)

We should have it collapse into the "minimal" look earlier:

![screen shot 2018-09-25 at 12 11 13 pm](https://user-images.githubusercontent.com/24359/46027559-23189b80-c0bc-11e8-8457-5a7b9aafca4a.png)

The code is here: https://github.com/publiclab/plots2/blob/master/app/views/layouts/_header.html.erb

This will take some testing with expanding and contracting the browser window. Please upload some screenshots of various states so we know it collapses smoothly! An animated GIF would be extra nice!

Thanks!

**Comment by shivani-kapania** [comment]
Hey! Could you please elaborate on the issue? All the header tabs need to be combined into one drop-down menu? 

Thanks!

**Comment by jywarren** [comment]
Hi, if you check out how headers work in Bootstrap docs, they're pretty
clever, and can auto-collapse. But setting when this happens seems a little
more complex. See what the docs say and I'm open to proposals for
solutions! Thank you!

**Comment by DamonClark** [comment]
@jywarren I think you may need to add a css` @media `rule in order to get this resolved. Although there is a chance you can make a smaller change to the `_header.html.erb `file and get it working. I am happy to work on this issue, but I have a feeling its going to need some css to fix it.

**Comment by quinn-codes-synthesis** [comment]
Hi! I'd like to claim this issue.

**Comment by jywarren** [comment]
We'd love your help, thank you!

**Comment by DamonClark** [comment]
I submitted a pull request to fix this here https://github.com/publiclab/plots2/pull/3491 with gif included. I don't know if my fix was the best way to do it. But it definitely solves the problem.

**Comment by quinn-codes-synthesis** [comment]
Oh. That's helpful! I'm going to take a look at it ASAP and see if it needs any tweaking.

**Comment by quinn-codes-synthesis** [comment]
Thanks Damon! I think I'm in over my head, so I'm glad you were able to find a solution.

**Comment by DamonClark** [comment]
No worries Quinn! I'm still just learning too so I'm right there with you.

**Comment by quinn-codes-synthesis** [comment]
@jywarren -- That would be awesome. Thank you! Look for an email from me sometime early next week; I'm preparing to move this weekend and will have a lot more time to contribute once that's over with. 

:house_with_garden: :truck: :derelict_house:

**Comment by jywarren** [comment]
Good luck with the move! 📦 📦 📦
