### ISSUE TITLE
Link 'balloon-mapping' to a new tab in PL Editor

### ISSUE THREAD

**Issue by geekychaser** [publiclab/plots2#3465]
```We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.```

Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** onclick balloon-mapping in recent tag section should take you to /tag/balloon-mapping in new tab

![issue](https://user-images.githubusercontent.com/24489162/46027945-d9a46c80-c10c-11e8-84db-ff00b7394ed9.png)

https://github.com/publiclab/plots2/blob/136b448931f49d8c0baa8bbf79936bcf00e94ad7/app/views/editor/wikiRich.html.erb#L95

After click on balloon-mapping it should take you to (https://publiclab.org/tag/balloon-mapping) in **new tab** :- 
![ballon](https://user-images.githubusercontent.com/24489162/46028178-854dbc80-c10d-11e8-8d21-bd8364b69564.png)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by SidharthBansal** [comment]
Nice catch and nice fto.

A few suggestions 

This is quick guide for adding code links https://github.com/publiclab/plots2/wiki/Google-Code-In-Tasks#help-add-code-links-to-existing-issues

I guess you copied 
>>The above text is displayed on the dashboard whenever a person signs up at Public Labs for teh first time

from previous issue

Also, make sure to write that it should redirect to new page. Write this in fto.

Please add descriptive title to your issue

**Comment by geekychaser** [comment]
okay @SidharthBansal , i have updated the issue.
thanks for guidance

**Comment by jywarren** [comment]
Ah, sorry! I think this may need to be closed in favor of:

"Clicking suggested tag names should enter them into the tag input" -- and
on this repository: https://github.com/publiclab/PublicLab.Editor/

Would you mind closing and opening one over there?

However, I agree also with Sidharth's comments. Thanks for your help!

**Comment by geekychaser** [comment]
okay sir , closing the issue and opening the same over there.

**Comment by SidharthBansal** [comment]
I think that @geekychaser is right. We want to open a specific tag as
listed on the editor. We don't want to open a page to search tags. We are
giving people an example on how tags pages are listed.
jeff you are also right in alternative sense.
Can you please rethink once @jwarren?
Thanks

**Comment by jywarren** [comment]
Maybe we could also have it say "Click to add a recent tag" to make it less ambiguous? But first we'll have to make it work properly! :-)
