### ISSUE TITLE
Link 'water-quality' to a new tab in PL editor

### ISSUE THREAD

**Issue by geekychaser** [publiclab/plots2#3466]
```We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.```

Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** on click water-quality in recent tag section should take you to /tag/water-quality in new tab

![issue](https://user-images.githubusercontent.com/24489162/46027945-d9a46c80-c10c-11e8-84db-ff00b7394ed9.png)

[Code link to update](https://github.com/publiclab/plots2/blob/136b448931f49d8c0baa8bbf79936bcf00e94ad7/app/views/editor/wikiRich.html.erb#L95)

After click on water-quality it should take you to(https://publiclab.org/tag/water-quality) in **new tab** :- 
![water](https://user-images.githubusercontent.com/24489162/46028468-49672700-c10e-11e8-82d0-c040455299b6.png)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by jywarren** [comment]
Ah, sorry! I think this may need to be closed in favor of:

"Clicking suggested tag names should enter them into the tag input" -- and
on this repository: https://github.com/publiclab/PublicLab.Editor/

Would you mind closing and opening one over there?

**Comment by geekychaser** [comment]
okay sir , closing it and opening one over there.

**Comment by jywarren** [comment]
great! Thank you!!!
