### ISSUE TITLE
Usefulness of "Figaro" Gem (update to Issue)

### ISSUE THREAD

**Issue by msarit** [publiclab/plots2#3469]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Usefulness of Figaro Gem

This issue is being updated to reflect the conversation below. Initially, the issue called for the removal of the Figaro gem (used to conceal sensitive information like API keys from public view by disallowing this info to be pushed to online Git repositories). Since PublicLab.org API keys are hardcoded into the app's container, the gem seemed unnecessary.

However, some members are utilizing the Figaro gem in evaluating gsoc - specifically, to test OAuth providers in development mode.

So the Figaro gem stays 👏 But the app needs a comment explaining its use.

### 🤔 What you will need to know

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step By Step

(coming soon; awaiting additional information)

1. If you are familiar with the terminal or would like to learn it, <a href="https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github">here is a great tutorial</a> on how to send a pull request using the terminal.
2. You can also <a href="https://help.github.com/articles/editing-files-in-your-repository/">edit files directly in your browser</a> and open a pull request from there.

*  🏁 Done Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, <a href="https://publiclab.github.io/community-toolbox/#r=all">take a look at some other issues you can help with</a>. Thanks!

**Comment by jywarren** [comment]
Amazing! I'm going to hold off on marking it as a `first-timers-only` issue for a few days because we are having a bit more interest than we're able to respond to quickly! That way we can space these out a little bit. Thank you so much!

In the meantime we would /love/ a little help reviewing and refining others' pull requests - https://github.com/publiclab/plots2/issues/3458

Thanks again!

**Comment by msarit** [comment]
Perfect! I shall do so. You have no idea the rush I'm experiencing contributing to this project lol! You have designed a contribution system that is **so warm and inviting** to first-timers. Thank you Jeffrey 🙏

**Comment by jywarren** [comment]
😅 🙌   I'm SO GLAD to hear it! We're really trying to help people step into leadership roles too, partly because it's the right thing to do but partly because it takes a lot of energy to keep the welcoming going strong. So it's really nice to hear good feedback! THANKS!

**Comment by jywarren** [comment]
But also -- pace yourself! don't burn out! 👍

**Comment by msarit** [comment]
Absolutely - thanks for the advice and support 🙏

**Comment by SidharthBansal** [comment]
Hi @msarit I did the work relating to figaro in my gsoc evaluation. We need an easy way to test OAuth providers in the development mode.
So, figaro gives us an easy way to do so. If we will keep it It will be great.
Thanks

**Comment by msarit** [comment]
@SidharthBansal Ahh alright then. I opened the issue on advice from @jywarren but your explanation makes sense - sorry about that 👍

**Comment by jywarren** [comment]
Ah, interesting @SidharthBansal -- Hmm, so could we adapt this to add a comment explaining what it's used for -- potentially with a link to where related code lives?

**Comment by jywarren** [comment]
@msarit so, if you want to adapt this one to add that extra comment for clarity, it could still make a good FTO!

**Comment by SidharthBansal** [comment]
Ok then we will add the gem again if there will be trouble.
Figaro is used in development. So, I can work by installing figaro at plots
2 local server.
So, as jeff insists, we can reopen the issue

**Comment by jywarren** [comment]
@msarit if you can retitle and adjust this issue to be about putting in a comment to explain, that'd be great! Thanks all!

**Comment by msarit** [comment]
@jywarren Ok Jeffrey I'll get on this tonight. Sorry Ive been home with my family the last few hours 😅

**Comment by jywarren** [comment]
no rush! Thanks a lot!

**Comment by msarit** [comment]
@SidharthBansal would you please send me a link to the code that's relevant to this issue? Thanks!

**Comment by SidharthBansal** [comment]
I will open another issue for the documentation part once this gets merged.

**Comment by Manasa2850** [comment]
@jywarren I would like to open a FTO issue for this. Thank you!

**Comment by Manasa2850** [comment]
This has been solved via issue #9009 and PR #9058
