### ISSUE TITLE
List of trending topics features only one topic

### ISSUE THREAD

**Issue by shivani-kapania** [publiclab/plots2#3470]
**All the trending topics in the user's dashboard are the same. Even if one topic, "spectrometer" here is top trending, still the remaining list should feature other topics (as is the case with most websites).** 

<img width="768" alt="screen shot 2018-09-25 at 10 43 58 pm" src="https://user-images.githubusercontent.com/29448581/46033580-30657280-c11c-11e8-983e-2ec6ac483098.png">

Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general @[help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

📋 **Step by Step**
  🙋 Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

  📝 Update the file plots2/app/views/dashboard/_activity.html.erb in the plots2 repository and edit the line shown below. 

https://github.com/publiclab/plots2/blob/4610d1f646ef328e0c336ee0bf7aee7fe9102016/app/views/dashboard/_activity.html.erb#L54

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

💾 Commit your changes

🔀 Start a Pull Request. There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

  🏁 Done Ask in comments for a review :)

🤔❓ **Questions?**
Leave a comment below!

Is someone else already working on this?
We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seem stuck, offer them some help! Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by jywarren** [comment]
Hi, unfortunately, I wonder if this may take a little more experimentation
than may be appropriate for a first-timers issue?

I've tried to document the issue here:
https://github.com/publiclab/plots2/issues/3188

But I believe it may require some deeper digging that could be a good match
for someone a little more advanced!

**Comment by shivani-kapania** [comment]
Oh, I hadn't seen #3188 earlier. 

I agree, this issue might require some deep digging. I'll close this issue, thanks for informing! 👍

**Comment by jywarren** [comment]
thank you!!!
