### ISSUE TITLE
Create Mentorship Guidelines document

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#3471]
[Help wanted in editting the issue]

### Please describe the problem (or idea)
Create Mentorship Guidelines document at docs/Programs/Mentorship. We will give link to this document to all the potential NEW mentors so that they will be able to understand our system in 5-10 minutes.

> What happened just before the problem occurred? Or what problem could this idea solve?

The crowd at public lab is increasing. The number of mentors this year is quite large than we had previous years. There is a need to properly document the things which mentors needs to do while working at Public lab group.

> What did you expect to see ?

Documentation should clearly list the flow of events at public labs. That is people need to do single first timer only issues. Then they need to do help wanted issues. Mentors have to assist them in these fields. Explain what first timer and help wanted issues means. Then mentors need to guide students to create first timer issues and help in reviewing prs. We are moving towards a self suistaining system approach where people makes pr and people review the pr amongst themselves

Documentation should clearly list about mentorship programs currenlty pl takes part in. With their links

 if you are creating a gci candidate issue format it properly with
lines like
We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.
If it is a first timer issue than use first timer template
also provide code links
What people are doing from a week at PL is they create issues without proper formatting
In issues for gci we need to list the potential solutions also.
If you are creating an issue for gci you need to put them in the staging list for gci also
#3276
For gci issue you need to create the same task on the gci dashboard
You need to write the instance count
ie how many people can take that
You need to tell the category of the issue in the issue description
and things like that

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment]
@rbhatia46 showed interest to write this piece of literature.
Thanks

**Comment by rbhatia46** [comment]
Okay I am working on it.

**Comment by radheyshyamjangid** [comment]
I would like to work on it. Can I?

**Comment by gauravano** [comment]
Hi @radheyshyamjangid , @rbhatia46 has already opened a PR for this issue. You can find more issues at https://code.publiclab.org/ . Thanks!

**Comment by radheyshyamjangid** [comment]
ohk @gauravano

**Comment by jywarren** [comment]
We're looking to incorporate additional content suggested by @SidharthBansal and others in follow-up pull requests which may be completed by others. Please note:



Also we can incorporate some content from here: https://publiclab.org/wiki/gsoc#Mentoring

**Comment by jywarren** [comment]
sorry, adding via @SidharthBansal in #3525:

> Can you please add link to the wiki page that is https://github.com/publiclab/plots2/wiki/Google-Code-In-Tasks. And tell that these are recurring tasks.
> Also tell about labels which we can use at public lab after creating issues

> Also add PR review guidelines

> PR should use 'Fixes #issue_no" in PR body
> Code should be modular.
> Tests must be written if needed. All tests must pass before approval.
> Suggest code changes if any. Else approve the PR by commentting in the PR.
> Also have link to more resources ie publiclab.org/gsoc

**Comment by jywarren** [comment]
Reopening because we have more material we'd like to add in, as mentioned above!

**Comment by starkblaze01** [comment]
I would like to work on this.

**Comment by SidharthBansal** [comment]
Go ahead

**Comment by SidharthBansal** [comment]
Please add missing guidelines from https://docs.google.com/document/d/1-BesjjJnQGAi5A9sS8bJoepmxRSmGZvZ9-uffcbhG_k/ and https://github.com/publiclab/plots2/issues/3563

**Comment by SidharthBansal** [comment]
Also give link to https://github.com/publiclab/plots2/issues/3563

**Comment by SidharthBansal** [comment]
Some great ideas in #3609. Thanks to @ebarry
