### ISSUE TITLE
Related tags is accessing some spam records

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3479]
We have a great new feature where you can call `Tag.related(tag_name)` and you get a list of tags that've been used on a page alongside the tag you pass in. 

https://github.com/publiclab/plots2/blob/4610d1f646ef328e0c336ee0bf7aee7fe9102016/app/models/tag.rb#L305-L318

However, as you can see on this page: https://publiclab.org/tag/country

Some tags shown are actually from spam content. So we need to come up with a way to form that query to be sure the tags used are only those being used on nodes that are `status == 1` -- non-spam nodes. 

This query will be a little tough! I think the best way forward may be to write a test using this "spam" tag:

https://github.com/publiclab/plots2/blob/4610d1f646ef328e0c336ee0bf7aee7fe9102016/test/fixtures/node_tags.yml#L19

We don't currently have a test for related tags but we should! I'll add that as a new issue as well. 

https://github.com/publiclab/plots2/blob/master/test/unit/tag_test.rb

**Comment by erickcsh** [comment]
I want to work on this one. Is it still open?
