### ISSUE TITLE
Add a unit test for the Tag.related method

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3480]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

We're looking to improve our testing to catch errors before they affect our live site! One type is "unit tests" which test models. You can read [all about Rails testing here](https://guides.rubyonrails.org/testing.html). 

https://github.com/publiclab/plots2/blob/master/test/unit/tag_test.rb shows lots of great unit tests, but nothing for the `Tag.related()` function which is here:

https://github.com/publiclab/plots2/blob/4610d1f646ef328e0c336ee0bf7aee7fe9102016/app/models/tag.rb#L305-L318

Let's add one to test this out! An initial test could just run it and confirm that it passes anything back. But then as a follow-up we could expand the test to be more comprehensive. 

But for starters, we can add a simple test just like this one:

https://github.com/publiclab/plots2/blob/98d2a28028ab3b805aceb4bdd194aaed7f330b57/test/unit/tag_test.rb#L14-L18

## Solution

We could add just below the above-mentioned test, something like:

```ruby
  test 'related tags' do
    related = Tag.related(tags(:awesome).name)
    assert !related.empty?
    # assert related.include?(tags(:test)) # if we want to get ambitious, we could check whether an actual related tag is returned, but we would have to probably adjust this if the "test" tag is not actually related.   
  end
```

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org//developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page](https://code.publiclab.org/#r=all)!

**Comment by yasmindias** [comment]
I would like to work on this if no one is working on it already.

**Comment by gauravano** [comment]
Hi @yasmindias, unfortunately, this issue is reserved for Google Code-In as mentioned in the issue body, so you have to look for another issue. Thanks!

**Comment by jywarren** [comment]
Hi @yasmindias we'd love to work with you on another issue and are posting more at https://code.publiclab.org soon. Thank you!

**Comment by jywarren** [comment]
This is reserved for @Nirvikalpa108! Thank you!

**Comment by Nirvikalpa108** [comment]
Hi @jywarren, thank you so much for reserving this issue for me! This is perfect as I really want to learn about testing! 

I am still at the very beginning of my coding journey so I'm finding the syntax quite intimidating. 

I appreciate the link from the general rails testing docs, is there a particular section or another article or two that could help me get to grips with this issue? 

Alternatively, is there anyone that would have an hour to pair with me on this remotely? If not, I would really appreciate receiving some tips on what to google or particular articles so I can teach myself. Thank you 😃

**Comment by jywarren** [comment]
Hi! so glad. 🎉 

For starters, yeah, i think this railscast could be helpful -- i learned rails via Railscasts: http://railscasts.com/episodes/327-minitest-with-rails (although it's a bit old, mostly it is still legit)

I looked around a bit and found this which is kind of nice: https://guides.railsgirls.com/test-driven-development

We use `minitest` and not `rspec` so be aware a lot of tutorials are for `rspec`. Basically, though, unit tests are the simplest and best type of test - they test core functions, not overall systems. They test the lowest-level functions one at a time, out of context. By contrast, functional tests test whole URL endpoints of the app, like posting a blog post or logging in. So they basically require running the whole app automatically through some paces. Unit tests just test some minimal step of the process and confirm that the basic behavior acts as it should. Unit tests are fast and "cheap" - and they confirm basic expected behaviors we might use over and over, but they don't guarantee the whole system works together in concert, if you know what i mean. I hope this is helpful!

Also, if you have the codebase up and running already (#3840), you can try pasting the sample test i cited above into `test/unit/tag_test.rb` and running `rake test:units` (i believe) to see it run. Specifics on testing in our app can be found here: https://github.com/publiclab/plots2/blob/master/doc/TESTING.md

Testing is kind of satisfying in a funny way. I hope you enjoy this issue! There could be some more test-driven-development steps you could take on next if you're interested! Perhaps, #4232 could be a next challenge?

**Comment by jywarren** [comment]
And here, i'll annotate this a bit:

```ruby
  test 'related tags' do # <== declare the test and what it's supposed to test for
    related = Tag.related(tags(:awesome).name) # <== run the `Tag.related()` function and pass it a tag name, which is what it expects to get; store the output in a variable called "related" 
    assert !related.empty? # <== we assert that whatever it returned is not (!) empty
    assert related.include?(tags(:test)) # <== if we want to get ambitious, we could check whether an actual related tag is returned, but we would have to probably adjust this if the "test" tag is not actually related. 
  end
```

To find a related tag, you could add this line before the last line of the test: 

```ruby
puts related.to_json # <== here, we output the returned values in JSON and we'll be able to see in the test output what is actually returned. Then we can add that to the test. 
```

This will protect the functionality of `Tag.related()` against future breaking changes!

**Comment by Nirvikalpa108** [comment]
Hi @jywarren I just want to say a HUGE thank you for taking the time to set this all out for me, that's incredibly kind of you! I'm looking forward to going through all of the recommended links over the coming days and will let you know once I come across further questions. Thank you!

**Comment by jywarren** [comment]
thank you too! And good luck - i can help out if you get stuck!!!
