### ISSUE TITLE
Remove  useless code

### ISSUE THREAD

**Issue by avsingh999** [publiclab/plots2#3481]
### Please describe the problem (or idea)
In this file, there is a useless code "Related topics " which is not showing this page  https://publiclab.org/methods this is good for First-time-only

https://github.com/publiclab/plots2/blob/5c0d96274bd0be15feba69d8f30093082402ace5/app/views/wiki/methods.html.erb

![remove1](https://user-images.githubusercontent.com/25536022/46039688-0156fd00-c12c-11e8-9da5-941ea3c599a2.PNG)

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/methods

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system
chrome ubuntu16
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by avsingh999** [comment]
Good for First-time-only

**Comment by jywarren** [comment]
I agree -- would you like to try formatting it as one? Thank you!!!

**Comment by SidharthBansal** [comment]
He will do #3421 first. I am suggesting him changes there. We need to teach people about our system. 
Each newcomer can take 2 issues at a time atmost. Later on after 4-5 months they can take multiple issues.
Moving slowly with all the newcomers. Hoping this will help them to teach about our workflow.
Thanks

**Comment by SidharthBansal** [comment]
@avsingh999 you can surely work on this issue after completion of #3421.

**Comment by vikul1234** [comment]
@avsingh999  @SidharthBansal I want to work on this issue

**Comment by SidharthBansal** [comment]
Go ahead @vikul1234

**Comment by gauravano** [comment]
Hi @jywarren @SidharthBansal don't you guys think, the code we are talking about is in use? 

![usee](https://user-images.githubusercontent.com/20878070/46262450-0a2a4300-c51f-11e8-896b-7c70b6566ed8.png)

**Comment by avsingh999** [comment]
@jywarren @SidharthBansal, he is right, sorry It was my mistake

**Comment by avsingh999** [comment]
@jywarren @SidharthBansal  I think this page needs to the improvement

**Comment by jywarren** [comment]
OK, i'll close this, but I agree, this page does need improvement!
