### ISSUE TITLE
Remove '=' from header

### ISSUE THREAD

**Issue by geekychaser** [publiclab/plots2#3487]
### Please describe the problem (or idea)

![issues](https://user-images.githubusercontent.com/24489162/46045870-9c57d300-c13c-11e8-98f5-94b4d6ddbe8f.png)

> What happened just before the problem occurred? Or what problem could this idea solve?

It shows "= view previous version of this page".
this = needs to remove

### Please show us where to look

https://publiclab.org/wiki/gsoc

### What's your PublicLab.org username?
geekychaser

> This can help us diagnose the issue: 

### Browser, version, and operating system
Chrome browser

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by geekychaser** [comment]
@SidharthBansal can i solve this?

**Comment by SidharthBansal** [comment]
Go ahead
Thanks for bugs reporting
