### ISSUE TITLE
mail notifications getting lost in spam filters?

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/plots2#349]
not really sure what to do with this one, but I'm de-spamming notifications right now.  It seems to be recent.

![screen shot 2015-11-24 at 1 37 22 pm](https://cloud.githubusercontent.com/assets/1203280/11381391/b2ade58a-92b0-11e5-96c4-ccfd72b81734.png)

**Comment by jywarren** [comment]
I think it should have been resolved during the Barnraising, can you
confirm that none since then have been spammed?
