### ISSUE TITLE
Boolean Full-Text Searches - add a link to more info on boolean searches

### ISSUE THREAD

**Issue by milaaraujo** [publiclab/plots2#3490]
The boolean full-text search has the capability to support operators such as **+**, **-** and **\***. We are using the boolean full-text search [here](https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L39-L44), but with an auto-added asterisk:
```
        if type == :boolean
          query = connection.quote(query.to_s + "*")
          nids = Revision.select("node_revisions.nid, node_revisions.body, node_revisions.title, MATCH(node_revisions.body, node_revisions.title) AGAINST(#{query} IN BOOLEAN MODE) AS score")
            .where("MATCH(node_revisions.body, node_revisions.title) AGAINST(#{query} IN BOOLEAN MODE)")
            .limit(limit)
            .distinct
            .collect(&:nid)
```
So we need help to:
* [x] remove the auto-added asterisk on this line, and treat "boolean search" as an 
expert search type. - Done (#4022)
* [ ] **add a link to more info on boolean searches: https://dev.mysql.com/doc/refman/5.5/en/fulltext-boolean.html - TODO**

----------------------------

We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.

**Comment by milaaraujo** [comment]
Hey @jywarren, can we keep this as a single issue and maybe use it as a help wanted issue for GCI?

**Comment by jywarren** [comment]
Sure!!

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by rohancl** [comment]
@SidharthBansal  @jywarren can you elaborate a bit about adding a link to the more info part of this task, Thanks !

**Comment by milaaraujo** [comment]
Hey @rohancl, this issue has two parts. First, the auto-added asterisk on this part of the code (https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L39-L44) should be removed. Then we need to add a link add to give more info on boolean searches and help users to understand how to use the boolean search. This link is a good one to use: https://dev.mysql.com/doc/refman/5.5/en/fulltext-boolean.html

**Comment by rohancl** [comment]
@milaaraujo  Hey thanks for replying,One more doubt,  I wanted to know whether I can make my own tutorial of Boolean searches  in MySQL to complete the second objective of this task. Thanks !

**Comment by jywarren** [comment]
you could do that, although it's quite ambitious! Perhaps we could start by
linking to an existing one, but then changing the link to yours if you
complete one!

**Comment by rohancl** [comment]
@jywarren Yeah sure, don't get me wrong, by tutorial I meant How I did the steps to solve the this task and all.

**Comment by JonathanXu1** [comment]
Hi, I'd like to work on this issue. Is anyone still working on this issue?

**Comment by milaaraujo** [comment]
@rohancl is working on this one!

**Comment by rohancl** [comment]
Actually, I've encountered my exams, they're like a bunch of storms coming to my face. I am really sorry, I cannot proceed any further contributing in this organisation. @JonathanXu1 feel free to continue with this task. I am really sorry @milaaraujo

**Comment by JonathanXu1** [comment]
Best of luck on your exams @rohancl . Here's my pull request: https://github.com/publiclab/plots2/pull/4019

**Comment by oorjitchowdhary** [comment]
This task is completed right?
I can still see it on the gci platform..

**Comment by JonathanXu1** [comment]
I'm waiting for my submission to be accepted. Thanks!

**Comment by milaaraujo** [comment]
Reopening this because we still need to  add a link add to give more info on boolean searches and help users to understand how to use the boolean search. This link is a good one to use: https://dev.mysql.com/doc/refman/5.5/en/fulltext-boolean.html

**Comment by JonathanXu1** [comment]
I added the link as a comment in line 40, is that sufficient?

**Comment by milaaraujo** [comment]
@JonathanXu1, no... We need to add the link for the publiclab users on the website! ;)

**Comment by milaaraujo** [comment]
Sure!
- https://github.com/publiclab/plots2/blob/master/app/views/search/notes.html.erb
- https://github.com/publiclab/plots2/blob/master/app/views/search/wikis.html.erb

**Comment by CodeSarthak** [comment]
Hi @milaaraujo Where is boolean search being implemented on the webpage, in the front end?

**Comment by JonathanXu1** [comment]
I'd like to continue working on it but the task was not available when I tried to claim it.

**Comment by milaaraujo** [comment]
Hey @CodeSarthak, @JonathanXu1 is already working on it. But we have a lot of available tasks!

@JonathanXu1, I will review it tomorrow. Thanks!

**Comment by CodeSarthak** [comment]
Ok @milaaraujo, but I think we are not so high on tasks right now. We have about 6-7 open tasks on GCI right now.

**Comment by JonathanXu1** [comment]
Yeah if we could work on more tasks that would be great!

**Comment by milaaraujo** [comment]
We are working on open new tasks/issues! :)

**Comment by jywarren** [comment]
Hi, Jonathan - a bunch recently opened on Image Sequencer -- not sure if
they have corresponding tasks in GCI yet, but we're def interested in help
over there too! Thanks!!

**Comment by JonathanXu1** [comment]
@jywarren I'd be glad to help! Perhaps we can open gci issues as we work on them haha
