### ISSUE TITLE
Add an editable Feature for publiclab.org/methods

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#3497]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

The topics at the top of https://publiclab.org/methods occasionally become out of date. Sometimes certain environmental issues suddenly get a lot of media attention, and we want to be able to update the topics quickly to help people connect to information they are seeking. 

This idea is to create an Admin-editable feature for which topics are listed at the top of https://publiclab.org/methods. This exists for other pages like https://publiclab.org/questions and https://publiclab.org/tags. 

The relevant segment of code is right here: https://github.com/publiclab/plots2/blob/7896dfa2fab442088022400fb676aae289a120f4/app/views/wiki/methods.html.erb#L17-L22

Here is an example where we made such a change before on another page: https://github.com/publiclab/plots2/pull/2698/files

> What did you expect to see that you didn't?

I hope that in the future that on https://publiclab.org/features there will be a listing for `methods` and that i can click `edit` and be able to update the HTML, and then see the corresponding change in https://publiclab.org/methods.

### Please show us where to look

https://publiclab.org/methods
https://publiclab.org/features

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

liz
THank you!

**Comment by narnt** [comment]
If I made one PR, I can't work on fto-candidate issue?

**Comment by narnt** [comment]
@ebarry  Topics list on the methods pages have to be like list of features on the features page?

**Comment by jywarren** [comment]
Yes you can, thanks!

This would involve putting this kind of block in the top of the methods page:

https://github.com/publiclab/plots2/blob/ec0b0f9df325097eb30504b686f27632021ae28c/app/views/questions/index.html.erb#L13-L15

Essentially to replace this content:

https://github.com/publiclab/plots2/blob/ec0b0f9df325097eb30504b686f27632021ae28c/app/views/wiki/methods.html.erb#L17-L33

That way it could be set dynamically!

![image](https://user-images.githubusercontent.com/24359/47876981-2278d080-ddf1-11e8-8a96-d882214212ed.png)


```
Methods
developed by Public Lab contributors
Public Lab's community collaboratively develops many different DIY environmental monitoring and advocacy methods.

Browse them here and learn how to get involved.

agriculture
drinking-water
fracking
indoor-air
chemicals
industry
land-use
land-change
mining
oil-and-gas
transportation
urban-planning
sensors
community-organizing
```

**Comment by jywarren** [comment]
Instead of `feature_questions-header` you would likely put something like `feature_methods-header`. 

I'll paste in the current content into our Features system so once it's changed, it'll begin appearing!

**Comment by jywarren** [comment]
Hi, @narnt -- did this make sense? Did you want to give it a try? Thank you!

**Comment by narnt** [comment]
@jywarren yes, sure, I just have had a little break. and thank you!

**Comment by jywarren** [comment]
Hi @narnt just checking if you're interested in picking this back up; if not we're happy to help someone else take it on!

**Comment by jywarren** [comment]
This is complete! Thanks all!
