### ISSUE TITLE
Edit list style of Search profiles results

### ISSUE THREAD

**Issue by milaaraujo** [publiclab/plots2#3502]
Edit table-styling on https://publiclab.org/search/profiles/balloons/ to match https://publiclab.org/people (https://getbootstrap.com/docs/3.3/).

We would like the list of users in /search/profiles/search string/ to be formatted in the same way of /people list.

Code links:
- /search/profiles/: https://github.com/publiclab/plots2/blob/master/app/views/search/profiles.html.erb
- /people: https://github.com/publiclab/plots2/blob/master/app/views/users/list.html.erb

**Comment by simeydk** [comment]
Hi

I would like to try addressing this issue, but will need some help.

(1) My understanding is you want the list of people in /profiles/balloons to match the style of the list of people in /people?
(2) Could you point me to where in the codebase (more or less) the change should happen and where in the code base I can go look to find the styling for /people (or help me get oriented to find these places myself?)

**Comment by milaaraujo** [comment]
Hey @simeydk, 

I'm sorry for the late reply, I took the last week off! Your help would be very welcome, answering your questions:

(1) Yes! We would like the list of users in /search/profiles/_<search string>_/ to be formatted in the same way of /people list.
(2) **/search/profiles/:** https://github.com/publiclab/plots2/blob/master/app/views/search/profiles.html.erb
**/people:** https://github.com/publiclab/plots2/blob/master/app/views/users/list.html.erb

**Comment by milaaraujo** [comment]
Hey @simeydk , are you working on this? Need help?

**Comment by simeydk** [comment]
Thanks for following up. I haven't started on this, yet, but would like to.
I'll give it a shot this weekend

**Comment by milaaraujo** [comment]
No problem! :smile: I understand... This is not a trivial issue! Maybe it is not a good one for FTO, I'm removing that label.

We can do the following when you can get the project  running on your machine I can find a first time issue for you! What do you think?

**Comment by oorjitchowdhary** [comment]
Can I take this? I'm a GCI candidate..

**Comment by jywarren** [comment]
yes please!

**Comment by oorjitchowdhary** [comment]
Okay, I'll work on it

**Comment by oorjitchowdhary** [comment]
I'll submit a PR in about 30 mins or so

**Comment by oorjitchowdhary** [comment]
PR #4130 Pls review

**Comment by SidharthBansal** [comment]
@oorjitchowdhary I could not see any GCI task on the dashboard claimed by you.
Can you please claim it and provide me the link so that I can approve and you can work on a newer task?

**Comment by oorjitchowdhary** [comment]
@sidharthbansal I don't this task is put up on gci.. I saw the non beginners list too.. Couldn't see it.. I think you'll have to create one 😁

**Comment by SidharthBansal** [comment]
https://codein.withgoogle.com/dashboard/tasks/4528622330183680/
please claim it now
I am online now I will approve it now.
Thanks

**Comment by oorjitchowdhary** [comment]
I've claimed it

On Dec 6, 2018, at 8:24 PM, Sidharth Bansal <notifications@github.com<mailto:notifications@github.com>> wrote:


https://codein.withgoogle.com/dashboard/tasks/4528622330183680/
please claim it now
I am online now I will approve it now.
Thanks
