### ISSUE TITLE
Add explanatory text for 'Tags' option on the search

### ISSUE THREAD

**Issue by milaaraujo** [publiclab/plots2#3504]
Add more explanatory text for what the `Tags` option on the search page is actually searching/displaying: https://publiclab.org/search/tags/balloons/

**Comment by kryptc** [comment]
Can I work on this issue? -  with a bit more elaboration, please

**Comment by milaaraujo** [comment]
Sure, @kryptc!

So, right now `/search/tag/<search_query>` is [searching](https://github.com/publiclab/plots2/blob/master/app/services/search_service.rb#L63-L73) nodes that are tagged with the typed search query. We just need to add a general-public simple text explaning that! Something similar to what was done in #3614 to solve #3505.

**Comment by milaaraujo** [comment]
Hey @kryptc, are you working on this? Need help?

**Comment by kryptc** [comment]
Yeah, I'm working on it, sorry for the delay!

**Comment by SidharthBansal** [comment]
No problem
