### ISSUE TITLE
Add explanatory text for 'Profiles' option on the search

### ISSUE THREAD

**Issue by milaaraujo** [publiclab/plots2#3505]
Add more explanatory text for what the Profiles option on the search page is actually searching/displaying: https://publiclab.org/search/profiles/balloons/. Right now it is searching by username and bio.

**Comment by cesswairimu** [comment]
@milaaraujo  what kind of explanatory text  do you mean? Is it like a table or a list with bio and username column? Thanks

**Comment by jywarren** [comment]
I think perhaps more of a general-public simple text explanation -- like
"Searching people's profiles" -- and note that it is searching only these
fields. How does that sound?

**Comment by cesswairimu** [comment]
Sounds good, Thanks @jywarren  will be working on this too

**Comment by jywarren** [comment]
awesome!

**Comment by jywarren** [comment]
Solved by @cesswairimu in https://github.com/publiclab/plots2/pull/3614#issuecomment-427927372

Thanks!!!!!
