### ISSUE TITLE
Explore how to organize search results ( Notes, Wikis, and Questions )

### ISSUE THREAD

**Issue by milaaraujo** [publiclab/plots2#3507]
Explore a combined display of Notes, Wikis, and Questions since they are all Node types: https://publiclab.org/search/balloon.

**Comment by stefannibrasil** [comment]
This would prevent some duplicated results because sometimes the user searches for a query that is a Note AND a question. I think we could unify them all by calling a single method `find_nodes`.

**Comment by cesswairimu** [comment]
Hi @milaaraujo am interested on working on this. Could this involve adding an `All` button that displays all the matched nodes?  Thanks

**Comment by milaaraujo** [comment]
Hey @cesswairimu,  

Yes, I think adding an `All` button would be a good idea! 

Then depending on the quality of the returned results, we can think about removing Notes, Wikis, and Questions individual searches and use just `All` - as @stefannibrasil suggested. What do you think, @jywarren and @stefannibrasil?

**Comment by stefannibrasil** [comment]
That was the first idea, yeah!

My only concern is that we would have an 'All' button for notes, but we also have other results that aren't nodes, like Profiles and Tags:

![screenshot_2018-10-15 public lab notes](https://user-images.githubusercontent.com/10670581/46975569-cfc2b900-d07b-11e8-8b23-d05a339d783e.png)

Maybe use Notes, Profiles, Tags? Like this:

![screenshot_2018-10-15 public lab notes 1](https://user-images.githubusercontent.com/10670581/46978965-15d04a80-d085-11e8-9138-bf38641d47db.png)

Then we would need to update the categories as well, but that's a second part. What do you all think? Like
