### ISSUE TITLE
Method to check if user has commented for first-time or not

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#3509]
(This issue is a part of issue #3331 )

There is a method in https://github.com/publiclab/plots2/blob/master/app/models/user.rb#L343 to check if a user is a first-time poster or not. But, this method checks only for nodes(question, research note, etc). 

You have to make a method by the name `first_time_commenter` and write it's definition as to check if user has commented before or not. Note - You have to check this based on the number of published comments i.e., comment with `status = 1`. Place this method beneath the first_time_poster method only. 

Feel free to ask, if you have any queries. Thanks :smiley: !

**Comment by saloni-garg** [comment]
Hi @gauravano, just wanted to confirm if the following code would do what we are aiming at-
`def first_time_commenter
    comments.where(status: 1).count == 0
  end`

**Comment by champagnepappi** [comment]
hi can I work on this one...
