### ISSUE TITLE
Remove 'D' from USD$ in footer

### ISSUE THREAD

**Issue by shivani-kapania** [publiclab/plots2#3511]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I scrolled to the footer. 

> What did you expect to see that you didn't?

USD$ instead of US$

<img width="1280" alt="screen shot 2018-09-27 at 7 48 45 pm" src="https://user-images.githubusercontent.com/29448581/46153254-61ff4a80-c290-11e8-8d00-6391048b0d63.png">

### Please show us where to look

[https://publiclab.org/](https://publiclab.org/)

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

shivanikapania

### Browser, version, and operating system

Google Chrome, MacOS

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by gauravano** [comment]
Hi @shivani-kapania, as footer is a feature and only admins can edit the feature from PL website directly, let's ask @jywarren for proceeding with this issue. Thanks!

**Comment by shivani-kapania** [comment]
@gauravano yes, I read your comment on #3348 which is why I didn't use the first timers template for this. 👍

**Comment by jywarren** [comment]
Yes, I think we may want to close this and just notify @ebarry of the
change. Thanks!

**Comment by gauravano** [comment]
Closing it then. Thanks!
