### ISSUE TITLE
[multiple-use issue!] Move a translation text into a centralized file

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3515]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

We're starting a big project to (#3262) revamp and refresh our internationalization systems, and one basic task we'd LOVE help with is to start moving translations around the site into a more centralized location t help make them easier to manage. 

It's pretty easy! Try this:

## Find a single translation

First, look through files in this set of folders: https://github.com/publiclab/plots2/blob/master/config/locales/

Dig into the subfolders and find an `en.yml` - full of English text

We want to move all the lines in these files into the main `en.yml` file at the root of these folders; this file:

https://github.com/publiclab/plots2/blob/master/config/locales/en.yml

So take one translation, like this line:

https://github.com/publiclab/plots2/blob/35449fd5da4975aa235a49beae9f7b248d674c8c/config/locales/controllers/application_controller/en.yml#L3

How do we move it?

## Move the single line of text

Cut it from the original file and paste it into the top of the base file just below `en:` -- so between lines 3 and 4 in this example:

https://github.com/publiclab/plots2/blob/35449fd5da4975aa235a49beae9f7b248d674c8c/config/locales/en.yml#L2-L5

Keep the indentation the same! 👀 

See how it was indented under `application_controller:`? Copy that line in too, above your first one, but don't delete it from the original file. 

https://github.com/publiclab/plots2/blob/35449fd5da4975aa235a49beae9f7b248d674c8c/config/locales/controllers/application_controller/en.yml#L1-L4

In this case, you should end up with your root `en.yml` looking like:

```yml
...
en:
  application_controller:
    must_be_logged_in: "You must be logged in to do that."
  language: English
...
```

## Be sure to get all the "nested" lines

Many translations are nested a few levels deep, which means we have to copy each "level". Take this for example:

https://github.com/publiclab/plots2/blob/5c0d96274bd0be15feba69d8f30093082402ace5/config/locales/views/dashboard/_activity/en.yml#L3-L7

In this case, we want to copy those over when we move the translation, so it's still accessible by the string (in this example) `t('dashboard._activity.share_work')`. See this for an example of how these translations are used in code:

https://github.com/publiclab/plots2/blob/5c0d96274bd0be15feba69d8f30093082402ace5/app/views/dashboard/_activity.html.erb#L1

Don't worry, if you get this step wrong we can help you troubleshoot once you open a pull request! 🙌 

## See an example

The changes we've done in this guide have been compiled into a pull request so you can see them all together. Read through this for guidance!

https://github.com/publiclab/plots2/pull/3514/files

Good luck, and we're here to help! 👍 

Many thanks! ⚡️ ⚡️

**Comment by jywarren** [comment]
Please give it a try! I'd love to know if the issue makes sense or I missed
something. Note that multiple people may complete this one! Tell me how it
goes!

**Comment by SidharthBansal** [comment]
Yeah go ahead

**Comment by samyuravikumar** [comment]
Hi may I have this task? I'm also from GCI

**Comment by SidharthBansal** [comment]
Yeah sure. Go ahead

**Comment by gauravano** [comment]
Closing this as we have achieved this a little back and the centralized file is at https://github.com/publiclab/plots2/blob/master/config/locales/en.yml

Thanks all!
