### ISSUE TITLE
Typeahead inconsistencies

### ISSUE THREAD

**Issue by stefannibrasil** [publiclab/plots2#3517]
We use this [dependency](https://github.com/bassjobsen/Bootstrap-3-Typeahead) to for our navbar and search typeahead results. But we have some problems that we need to investigate:

- [ ] Depending on the query, the results are not grouped by category (Notes, Profiles, Questions, etc.). That leads to some duplicated categories being returned. When we get the JSON from the call, we see that the results are grouped by their doc_type, but the typeahead library breaks that somehow.

![screenshot from 2018-09-27 12-03-30](https://user-images.githubusercontent.com/10670581/46168800-512de500-c24e-11e8-84fb-b9b9cf7c9865.png)

- [ ] Sometimes it does not show the button 'View all' that redirects to `search/` page:

Not showing the button:

![screenshot](https://user-images.githubusercontent.com/10670581/46168815-59862000-c24e-11e8-8474-ac08522dffd7.png)

Showing the button:

![screenshot from 2018-09-27 12-11-58](https://user-images.githubusercontent.com/10670581/46168968-b71a6c80-c24e-11e8-9bdf-b98ca62b69f8.png)

**Comment by sunilsj99** [comment]
Can you please describe the issue in more details. I am interested in working on this @stefannibrasil

**Comment by stefannibrasil** [comment]
sure, @sunilsj99.
The typeahead script is [here](https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/restful_typeahead.js). It gest data from the [API](https://github.com/publiclab/plots2/blob/master/app/api/srch/search.rb). The API has the info about the item category, i.e., Note, Profile, Tag, etc. But somehow, the categories aren't grouped, sometimes Notes is returned twice, for example. When we get the JSON on the console, we see that the items are grouped by category, so we don't know exactly how the typeahead organize them.

**Comment by stefannibrasil** [comment]
The other thing is that the 'View all' button doesn't appear always, only for certain queries. We would appreciate any help/insights on those bugs, we don't have much JavaScript experience, so an extra help would be great!

**Comment by roshniRam** [comment]
@stefannibrasil can I work on this issue?

**Comment by stefannibrasil** [comment]
hi, @roshniRam yes, please! Sorry for the delay, I was on vacations. If you have any questions, feel free to ask.

**Comment by jywarren** [comment]
Hi @roshniRam are you by chance still interested in working on this at all? We'd love to have your help!

**Comment by jywarren** [comment]
We are now narrowing this to display only tags, and resolving it in https://github.com/publiclab/plots2/pull/5824!
