### ISSUE TITLE
Continuous like button press shows unexpected behavior

### ISSUE THREAD

**Issue by igniteeng000** [publiclab/plots2#3524]
### Please describe the problem (or idea)
When like button is pressed continuously it shows unexpected behaviour. Like may go to negative values also. On refreshing page problem is solved.

> What happened just before the problem occurred? Or what problem could this idea solve?

![like](https://user-images.githubusercontent.com/25272573/46205140-3e460e00-c33d-11e8-93a5-3abbd0a0e771.gif)

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors

### What's your PublicLab.org username?
igniteeng000
> This can help us diagnose the issue: 

### Browser, version, and operating system
Windows 10, chrome
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by avsingh999** [comment]
@igniteeng000  great catch

**Comment by igniteeng000** [comment]
Add gci-candidate to this also

**Comment by gauravano** [comment]
Hi @igniteeng000 , as this bug is most probably related to controller, so you have to provide the hint or partial solution so as to simplify this issue for GCI participants. Thanks!

**Comment by igniteeng000** [comment]
Ok, no problem

**Comment by avsingh999** [comment]
@jywarren @SidharthBansal can I work on this issue?
thanks :smile:

**Comment by SidharthBansal** [comment]
yes

**Comment by avsingh999** [comment]
@SidharthBansal  @jywarren  @gauravano  when I want to see data in likes table in a console but no data in this table. Can you please help me? If I am wrong then correct me please .
Thanks : )
