### ISSUE TITLE
Highlight selected tab 

### ISSUE THREAD

**Issue by igniteeng000** [publiclab/plots2#3526]
```We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.```

### Please describe the problem (or idea)
It will be good if the selected tab is highlighted.
> What happened just before the problem occurred? Or what problem could this idea solve?

![tab](https://user-images.githubusercontent.com/25272573/46206110-9f231580-c340-11e8-9b8c-da0c870a5744.PNG)

> What did you expect to see that you didn't?
I expect to highlight selected tab as above 

### Please show us where to look

https://publiclab.org/search/science%20community?order=default

### What's your PublicLab.org username?
igniteeng000
> This can help us diagnose the issue: 

https://github.com/publiclab/plots2/blob/a128622eb132eef4733c0067e2c6b2c1669d3042/app/views/search/notes.html.erb
https://github.com/publiclab/plots2/blob/a128622eb132eef4733c0067e2c6b2c1669d3042/app/views/search/wikis.html.erb

### Browser, version, and operating system
windows 10, chrome
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by avsingh999** [comment]
@igniteeng000  can u please explain more about this issue

**Comment by igniteeng000** [comment]
Highlight that tab that is selected just like Notes

**Comment by gauravano** [comment]
Hi @igniteeng000, nice catch,  would you like to solve this issue by yourself or a FTO ? Thanks!

**Comment by igniteeng000** [comment]
I want to add this issue for gci-candidate.

**Comment by gauravano** [comment]
ok, cool!

**Comment by gauravano** [comment]
Please add link to file also in issue body. Thanks!

**Comment by SidharthBansal** [comment]
@igniteeng000 if you are creating a gci candidate issue, please add following lines in the issue body so that other people will not start solving it:
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

**Comment by Souravirus** [comment]
@igniteeng000 Please add this and other gci-candidate issue you make to #3276 as well as to gci dashboard. Nice Work!!

**Comment by jywarren** [comment]
yes this is great!

**Comment by vanguard07** [comment]
I would like to work on this, if this issue is still open.

**Comment by SidharthBansal** [comment]
Sorry, you can't commit changes for this issue.
We are participating in Google Code In. This issue is reserved for Google Code In Students only. 
we'd love help with another issue -- especially looking at helping others make their first contributions!

Maybe take a look at one of these?

https://github.com/publiclab/plots2/labels/support

**Comment by vanguard07** [comment]
No problem. Thanks for informing @SidharthBansal 👍

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by SidharthBansal** [comment]
Yes

**Comment by igniteeng000** [comment]
@Deltrix Now you can find this issue in gci dashboard. Go ahead fix this issue.

**Comment by oorjitchowdhary** [comment]
I'd like to work on this.. I'm a GCI candidate.

**Comment by oorjitchowdhary** [comment]
@SidharthBansal Where is the code file? and how would I submit the work? Should I create a pull request?

**Comment by SidharthBansal** [comment]
Yes.
Thanks for looking at this carefully.

**Comment by oorjitchowdhary** [comment]
@SidharthBansal pls review my task....
https://github.com/oorjitchowdhary/plots2/pull/1
https://github.com/oorjitchowdhary/plots2/pull/2

**Comment by SidharthBansal** [comment]
You need to push it to publiclab/master.

You created PR to your own fork.

**Comment by oorjitchowdhary** [comment]
Oh ok my bad
