### ISSUE TITLE
Edit window for answers to questions does not allow preview (or editing)

### ISSUE THREAD

**Issue by Fastie** [publiclab/plots2#3527]
The edit window for posting an answer to a question does not allow preview. Subsequent attempts did allow preview.

When the answer is posted, opening the edit window does not display the answer for editing. Subsequent attempts to edit did display the answer for editing.

Chrome and Edge on Windows.

**Comment by Fastie** [comment]
I encountered this problem again today while posting a comment on an Answer here: https://publiclab.org/questions/mrodriguezorejuela/09-28-2018/mapir-survey3-rgn-image-processing-pipeline

Clicking "Preview" did not display my post.

When I used the link icon to insert a link, the text in the edit window was not changed, so it seemed that the link function was not working. I entered the markdown for embedding links manually and those links were displayed properly when I posted the comment.

When my comment was posted, I was not able to edit it by clicking the edit (pencil) icon. When that icon was clicked, the edit window opened with no text, which was not reassuring.

**Comment by jywarren** [comment]
Hi, Chris - i believe this has been documented and converted into a task
for the upcoming Google Code-In program. If it is very urgent, we can try
to prioritize it as something to fix before then, but we're anticipating
several hundred new contributors arriving by the end of October to fix
issues like this. If it can wait, we appreciate your patience as we grow
the community!

**Comment by Fastie** [comment]
No need to worry about my patience. The work-around doesn't bother me. I am more worried about the patience of other community members who try to interact using the Answer feature. Waiting a month to fix a feature that is well-used by new community members seems risky. Don't you have sandbox where you could preserve the buggy Answer feature?

**Comment by narnt** [comment]
Can I work on this?

**Comment by narnt** [comment]
It seems like nobody works on it, so I take it

**Comment by narnt** [comment]
On my local machine, when I try to edit a question, all goes fine.

**Comment by jywarren** [comment]
I believe this is now resolved due to #4094 and recent work on the commenting system, thank you!!!
