### ISSUE TITLE
Improve methods page button placement

### ISSUE THREAD

**Issue by avsingh999** [publiclab/plots2#3532]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Instance count 1
Field: Training

Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem
  https://publiclab.org/methods in this page there is shown posts are not in perfect view, Read more buttons collapse to other posts
![methods](https://user-images.githubusercontent.com/25536022/45932403-44cd3200-bf99-11e8-8ae1-52691148e069.png)

### 📋Solution

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** 

https://github.com/publiclab/plots2/blob/c9f5a33a0eeecbbd7e49cfde8acea78fccd73aef/app/views/notes/_notes.html.erb#L51

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by jywarren** [comment]
This is fantastic. Thanks!

**Comment by neel1998** [comment]
Can I work on this one?

**Comment by SidharthBansal** [comment]
@neel this issue is reserved for google code in program which is for high school students.
So you can't work on it if you are not a gci candidate.
You can check out other ftos.
Thanks

**Comment by neel** [comment]
@SidharthBansal sorry. I think you have dialed a wrong number.

**Comment by SidharthBansal** [comment]
Oh sorry its @neel1998 auto complete did not complete while writing. Really sorry to disturb you.

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by CodeSarthak** [comment]
The code reference given in the issue mentions only one button. Do I need to correct only one button or change the entire css class - "btn btn-default"?

**Comment by CodeSarthak** [comment]
Does this look fine? 
![methodsreadmore](https://user-images.githubusercontent.com/24937677/47631412-f0a30800-db6b-11e8-9530-caa05699fc03.PNG)
![methodsreadmoremobile](https://user-images.githubusercontent.com/24937677/47631445-17613e80-db6c-11e8-9147-6c7ab6ccb186.PNG)

**Comment by SidharthBansal** [comment]
Looks good to me.
@jywarren kindly review it

**Comment by CodeSarthak** [comment]
Here is the PR : https://github.com/publiclab/plots2/pull/3772

Please review.

Thanks and Regards.

**Comment by jywarren** [comment]
OK! merged this in #3772 and it is now solved, thank you!

**Comment by oorjitchowdhary** [comment]
This task is already done right? Coz I can still view it on the GCI platform.. So can I still solve it?

**Comment by thesparks** [comment]
> This task is already done right? Coz I can still view it on the GCI platform.. So can I still solve it?


I also asked about it. Gaurav Sachdeva said
"I will see into the issue 3439 and for 3532, yes it's closed, so I guess it wouldn't be available at GCI dashboard too."

**Comment by oorjitchowdhary** [comment]
@thesparks yeah ok no probs.. Our org is running low on tasks.. How many have you done?

**Comment by JonathanXu1** [comment]
Hi, the task is still available but appears to be solved. Am I supposed to be able to claim it?

**Comment by thesparks** [comment]
@gauravano, please respond here

**Comment by oorjitchowdhary** [comment]
Yeah.. @publiclab/reviewers 😟
