### ISSUE TITLE
Answer Preview is not working

### ISSUE THREAD

**Issue by avsingh999** [publiclab/plots2#3534]
### Please describe the problem (or idea)
If I want to Comment/answer of the question, In question page there is two option I can comment or I can give answer  and comment Preview working fine  but Answer preview is not working, if click on preview then it's showing comments preview not an answer's preview 

![issue](https://user-images.githubusercontent.com/25536022/46245050-9d6f5580-c405-11e8-91b1-276190da4ebe.gif)

Link to the comment/answer form - https://github.com/publiclab/plots2/blob/master/app/views/comments/_form.html.erb

Both new comment and new answer uses the same form. In research notes, there is only a single empty form so preview button works fine. But, when we come to questions, preview button doesn't work for answer's comment form and answer's form. When we press preview for any form, it shows/toggle preview for the first empty form of the page.

Link to toggle_preview function - https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/editor.js#L103-L134

Thanks!

**Comment by YashishDua** [comment]
Can I take this issue?

**Comment by Souravirus** [comment]
Nice catch @avsingh999. Can you please add this and other gci-candidate issue you have made to #3276 and the google code-in dashboard. Thanks!!

**Comment by SidharthBansal** [comment]
This has been marked as a good candidate for becoming a first-timers-only issue like these, meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider reformatting or reposting it as a first-timers-only issue, and then ping @SidharthBansal  to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by oorjitchowdhary** [comment]
Hi, I'd like to work on this .. I'm a Gci candidate... @publiclab/mentors

**Comment by oorjitchowdhary** [comment]
Can i get links to the code files....

**Comment by SidharthBansal** [comment]
@oorjitchowdhary this is fto issue, so you are ineligible for this.
You can try other issues.

**Comment by oorjitchowdhary** [comment]
Okay no problem.. I tried working on this as this wasn't a beginner task on gci

**Comment by SidharthBansal** [comment]
Sorry for the late reply.

**Comment by oorjitchowdhary** [comment]
No worries.. You guys are already working so hard... 👏

**Comment by Ivilili** [comment]
Hi, my name is Ivana and I'm Outreachy participant. Can I work on this issue?

**Comment by gauravano** [comment]
Hi @Ivilili, welcome to Public Lab. Go ahead with the issue :+1:

**Comment by Ivilili** [comment]
Hi @publiclab/reviewers, I have few questions about this issue. I've noticed that preview and other  features in Answer are attached to Comment area.
How should I approach this? Should I create new form for answer, because now comment and answer are together in `comments/form`?
Or maybe even integrate answers with comments?

**Comment by gauravano** [comment]
Hi @Ivilili, I went through the issue myself and it's a bit complex. The preview button calls the function toggle_preview which is located here- https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/editor.js#L103-L134 

And, if one observes carefully then will observe that pressing preview button opens the preview of first available empty form. So, something wrong here - https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/editor.js#L103-L134 only. It may take time to fix this one. So, do you like to have another issue?

**Comment by gauravano** [comment]
I have created https://github.com/publiclab/plots2/issues/5056 for you. You can claim that.

**Comment by Ivilili** [comment]
Thank you @gauravano, I will start with new one immediately. It's hard to give up on this one...

**Comment by gauravano** [comment]
You can come back to this one anytime after recording your first contribution. Thanks!

**Comment by sashadev-sky** [comment]
Hi, I am closing this because we have gotten rid of the `answers` editor and just have `comments` now, which was working fine. We can open specific issues for the other surrounding issues with the buttons
