### ISSUE TITLE
images not uploading in Answer

### ISSUE THREAD

**Issue by avsingh999** [publiclab/plots2#3535]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Please describe the problem (or idea)
when I want to upload an image in an answer  and select image file/ drag-drop in answers but it's uploading in comments

![issue3](https://user-images.githubusercontent.com/25536022/46245422-fc839900-c40a-11e8-8ea4-4e71457bb6e5.gif)

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/question/ choose_an_question_and_go_to_that_page

### What's your PublicLab.org username?
999_avsingh999
> This can help us diagnose the issue: 

### Browser, version, and operating system
chrome ubuntu 16.04
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by avsingh999** [comment]
@jywarren  
![issucommit](https://user-images.githubusercontent.com/25536022/46246383-2db79580-c41a-11e8-881b-e358efadcbb1.png)

**Comment by jywarren** [comment]
Ah but that's when it succeeded, no? Thanks!

**Comment by avsingh999** [comment]
@jywarren images can only be uploaded as comments.

**Comment by avsingh999** [comment]
@jywarren  same problem when we want to comment of any answer then preview and image uploading not working

**Comment by jywarren** [comment]
Can you paste in the JavaScript errors you see when trying to upload?

**Comment by jywarren** [comment]
We've deprecated Answers and converted them into Comments, but have a new similar bug -- moving to #5229 now! Thanks!
