### ISSUE TITLE
ical feed of all "event" tagged notes

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#354]
(related to #57) I've attempted a quick version of this, but it's brittle; it's also weird because events don't have times attached. 

See it at: https://publiclab.org/feed/tag/event:rsvp.ics

The end of the feed generates some weirdness; also, I think the incrementer which makes events last "all day" may fail on the last day of the month, because I'm just adding +1 to the day slot. 

Google Calendar can read simple ones of these, but it says it can't read the full generated one the site now makes. See https://github.com/publiclab/plots2/pull/353 also.

```
BEGIN:VEVENT
UID:do-not-reply@publiclab.org
DTSTAMP:20151110T000000
DTSTART;VALUE=DATE:20151110
DTEND;VALUE=DATE:20151111
SUMMARY:Oil Testing Kit Workshop at Art in Odd Places Festival
END:VEVENT
BEGIN:VEVENT
UID:do-not-reply@publiclab.org
DTSTAMP:BEGIN:VEVENT
UID:do-not-reply@publiclab.org
DTSTAMP:BEGIN:VEVENT
UID:do-not-reply@publiclab.org
DTSTAMP:20150909T000000
DTSTART;VALUE=DATE:20150909
DTEND;VALUE=DATE:201509010
SUMMARY:Public Lab Boston/Somerville coding meetup @ Parts &amp; Crafts
END:VEVENT
BEGIN:VEVENT
UID:do-not-reply@publiclab.org
DTSTAMP:BEGIN:VEVENT
UID:do-not-reply@publiclab.org
DTSTAMP:20150608T000000
DTSTART;VALUE=DATE:20150608
DTEND;VALUE=DATE:20150609
SUMMARY:NYC Climate Justice Youth Summit
END:VEVENT
```

**Comment by gauravano** [comment]
Any update on this one @jywarren?

**Comment by jywarren** [comment]
Let's close because we have working integration between events and Google Calendar already now. We can re-open if someone wants!
