### ISSUE TITLE
Inconsistent alert for same page

### ISSUE THREAD

**Issue by vikul1234** [publiclab/plots2#3540]
### Please describe the problem (or idea)
When we delete any comment the alert looks nice but while deleting any answer alert is the default alert.
## Deleting Answer
> What happened just before the problem occurred? Or what problem could this idea solve?
![answer](https://user-images.githubusercontent.com/22452641/46253858-5b94ec80-c4a3-11e8-9bec-a11d859ababa.PNG)

## Deleting Comment
> What did you expect to see that you didn't?
![comment](https://user-images.githubusercontent.com/22452641/46253860-5f287380-c4a3-11e8-8c78-e9dedb224ac5.PNG)

### Please show us where to look
https://publiclab.org/questions/jradheshyam96/09-28-2018/may-i-know-more-about-how-exactly-this-will-this-work

### What's your PublicLab.org username?
vikul1234
> This can help us diagnose the issue: 

### Browser, version, and operating system
chrome, windows 10
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment]
Do you want to work on this?

**Comment by vikul1234** [comment]
yes, i want to work

**Comment by SidharthBansal** [comment]
Go ahead

**Comment by vikul1234** [comment]
@roshniRam  I am working on it.

**Comment by vanguard07** [comment]
@vikul1234 Are you still working on this. If not, can I work on this?

**Comment by vikul1234** [comment]
Go ahead

**Comment by SidharthBansal** [comment]
Hi Is someone working on this?
If no then I can publish this for GCI.

**Comment by vanguard07** [comment]
Okay @SidharthBansal. Please do so. 😄

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by generationXcode** [comment]
hi @SidharthBansal I want to claim this task but am not sure whether I'll be able to do it because I don't know the code...I can't work on ruby files because I don't know the language. Can someone please send the link of the file on github . thanks!

**Comment by generationXcode** [comment]
can I work on it?

**Comment by generationXcode** [comment]
hi, can I try?

**Comment by vikul1234** [comment]
This task is assigned for gci students. If you are gci students then you can work. Thanks

**Comment by generationXcode** [comment]
yeah sure! (:

**Comment by oorjitchowdhary** [comment]
@SidharthBansal Where is the code file which is to be corrected here? Pls help me with it.. Thanks

**Comment by oorjitchowdhary** [comment]
> ### Please describe the problem (or idea)
> When we delete any comment the alert looks nice but while deleting any answer alert is the default alert.
> 
> ## Deleting Answer
> > What happened just before the problem occurred? Or what problem could this idea solve?
> > ![answer](https://user-images.githubusercontent.com/22452641/46253858-5b94ec80-c4a3-11e8-9bec-a11d859ababa.PNG)
> 
> ## Deleting Comment
> > What did you expect to see that you didn't?
> > ![comment](https://user-images.githubusercontent.com/22452641/46253860-5f287380-c4a3-11e8-8c78-e9dedb224ac5.PNG)
> 
> ### Please show us where to look
> https://publiclab.org/questions/jradheshyam96/09-28-2018/may-i-know-more-about-how-exactly-this-will-this-work
> 
> ### What's your PublicLab.org username?
> vikul1234
> 
> > This can help us diagnose the issue:
> 
> ### Browser, version, and operating system
> chrome, windows 10
> 
> > Many bugs are related to these -- please help us track it down and reproduce what you're seeing!
> 
> ## Thank you!
> Your help makes Public Lab better! We _deeply_ appreciate your helping refine and improve this site.
> 
> To learn how to write really great issues, which increases the chances they'll be resolved, see:
> 
> https://publiclab.org/wiki/developers#Contributing+for+non-coders

Also.. I'm unable to view the issue on the public lab site mentioned here

**Comment by thesparks** [comment]
@oorjitchowdhary,
For comment alert (you can take the code from here)

        plots2/app/views/notes/_comment.html.erb
For answer alert (that you need to fix)

        plots2/app/views/questions/_answer.html.erb

**Comment by oorjitchowdhary** [comment]
https://publiclab.org/questions/jradheshyam96/09-28-2018/may-i-know-more-about-how-exactly-this-will-this-work 
When opening this link, it says ** the author of this note has been banned** and then it redirects to the public lab homepage

**Comment by ValentinaTironi** [comment]
HI! I have a question. I can't see where are the answers. Someone can help me? Thanks!

**Comment by oorjitchowdhary** [comment]
@publiclab/reviewers I had done this task two days ago.. But now I can't find it on the GCi dashboard now.. So is it not for gci students now?

**Comment by thesparks** [comment]
@oorjitchowdhary , looks like this task already solved in #4010 and submitted in gci dashboard

**Comment by oorjitchowdhary** [comment]
@thesparks yeah sure but I submitted it before @valentinatironi

**Comment by gauravano** [comment]
Hi @oorjitchowdhary, according to GCI rules, you can perform only that tasks which you have claimed from GCI dashboard. That's why you were asked for closing PR #4001. Also, do remember this rule and open PR for only that task which you have claimed from GCI dashboard. Thanks!
