### ISSUE TITLE
Preview Button Text to be changed in 'Post Comments'

### ISSUE THREAD

**Issue by YashishDua** [publiclab/plots2#3543]
![screen shot 2018-09-30 at 2 51 18 pm](https://user-images.githubusercontent.com/20666950/46255882-82ade700-c4c0-11e8-833f-9af6591ce333.png)
![screen shot 2018-09-30 at 2 51 35 pm](https://user-images.githubusercontent.com/20666950/46255885-85104100-c4c0-11e8-9a56-5bf7dc2781ec.png)

When preview button is clicked, it's text must be changed to 'Hide Preview'.

**Comment by SidharthBansal** [comment]
Are you willing to work on it?

**Comment by YashishDua** [comment]
Yes!
