### ISSUE TITLE
There is no favicon for the web page

### ISSUE THREAD

**Issue by radheyshyamjangid** [publiclab/plots2#3545]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

There is no any favicon for the web page.

> What did you expect to see that you didn't?
![image](https://user-images.githubusercontent.com/20898860/46258706-d6362a00-c4ec-11e8-8fca-0b51c3850ce9.png)

### Please show us where to look

https://code.publiclab.org/

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

jradheshyam96

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!
window 10, chrome

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by pdurbin** [comment]
I see a "PL" favicon on Firefox on Linux. It looks like this:

![pl-255](https://user-images.githubusercontent.com/21006/46258978-67cb7a80-c4a0-11e8-8ff2-0fb111f72475.png)

It's served from https://publiclab.org/images/pl-255.png

**Comment by vishalka98** [comment]
I want to work on this issue. Please assign this issue to me.

**Comment by vishalka98** [comment]
@jywarren Can i add this image https://avatars-05.gitter.im/group/iv/3/57542d83c43b8c601977d790?s=48
