### ISSUE TITLE
Move comment_render_body helper into Comment model

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3552]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

https://github.com/publiclab/plots2/blob/6595ef39f25ca4f2d377cacfd92e86a7460214d6/app/helpers/application_helper.rb#L100-L107

Let's make this a method of Comment - in https://github.com/publiclab/plots2/blob/master/app/models/comment.rb - like:

```
def render_body

end
```

And remove it from `application_helper.rb`!

We'll also need to change this line:

https://github.com/publiclab/plots2/blob/6595ef39f25ca4f2d377cacfd92e86a7460214d6/app/views/notes/_comment.html.erb#L120

To `comment.render_body`

Finally, the `sanitize comment body` test in https://github.com/publiclab/plots2/blob/master/test/unit/comment_test.rb could be updated to test `comment.render_body` instead of reproducing the code from the helper.

Glad to help with this one! Could be a first-timers issue!

**Comment by mauricetmeyer** [comment]
I would like to take on this issue, it would be one of my first open source contributions. Also is there anything I would need to know before opening a pull request, like a special schema for commit messages?

**Comment by jywarren** [comment]
Nope, there's a template in the pull request form, but it's always editable later, so we can help you out as you go! Welcome! 👍 🎉

**Comment by mauricetmeyer** [comment]
@jywarren Thank you! Also those first timer issues are great to get to know the codebase, as I often don't have much time to read into large codebases. 👍

**Comment by jywarren** [comment]
so glad you like them!!!
