### ISSUE TITLE
Page Translation from English to Deutsch is not working.

### ISSUE THREAD

**Issue by harsha-iiiv** [publiclab/plots2#3565]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

 
![screenshot 28](https://user-images.githubusercontent.com/31560965/46356545-94d68380-c680-11e8-8992-afeafcdff2af.png)

### Please show us where to look

 [https://publiclab.org/dashboard](https://publiclab.org/dashboard)

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system
   Google chrome 
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment]
This issue is being addressed in another issue. Thanks for bug
