### ISSUE TITLE
List number of "sub-pages" with link in sidebar

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3566]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

Pages like https://publiclab.org/wiki/contributing-to-public-lab-software have a power tag that says `parent:developers` (https://publiclab.org/wiki/power-tags) which gives them a nice breadcrumb link leading them back to the `developers` page at https://publiclab.org/developers:

![image](https://user-images.githubusercontent.com/24359/46357169-413d4900-c632-11e8-9bf5-a31495c35c3a.png)

We should have a link leading to child pages. You can view child pages like this:

https://publiclab.org/wiki/tag/parent:developers

So, the link should just be, in ruby:

```ruby
<% subpage_count = Tag.find_pages("parent:#{@node.slug}", 100).count %>
<% if subpage_count > 0 %>
  <a href="/wiki/tag/parent:<%= @node.slug %>"><%= subpage_count %> sub-pages</a>
<% end %>
```

Note that we're setting `limit` to 100... we can think about this later because there are definitely no pages with anywhere near 100 sub-pages. 

This could go right above these lines: 

https://github.com/publiclab/plots2/blob/2898e6380677386c62c3e673cd381d4d2319d33e/app/views/sidebar/_related.html.erb#L53-L58

**Comment by RuthBrand** [comment]
hey! is anyone on this?

**Comment by jywarren** [comment]
Hi!!! I think I remember a pull request open but is it linked to here so we
can see it? Could be helpful to check the pull request list. Thank you!!!!
