### ISSUE TITLE
First-timers-issue

### ISSUE THREAD

**Issue by singhalkirtika** [publiclab/plots2#3567]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [index.html](https://github.com/publiclab/community-toolbox/blob/master/index.html) in the `community-toolbox` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Add the following tag:
```
<div class="row">
      <div class="col-md-12">
            <p> If you want to apply for Google Code-In mentor with publiclab and are willing to guide the new open source contributors, go to <a href="https://github.com/publiclab/plots2/issues/3168#issue-345824903">Call for Mentors</p>
	</div>
```
![suggestions](https://user-images.githubusercontent.com/25261181/46363332-521ca780-c690-11e8-9ab3-343e5fa49c00.PNG)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by jywarren** [comment]
this is great! Perhaps we need to mention "for Google Code-In or another
outreach program" -- but thanks!

Note that this change will go into index.html as well.

Great issue!

**Comment by MittalS211** [comment]
I would like to claim this issue!

**Comment by singhalkirtika** [comment]
Thanks @jywarren.
 I will modify the text.

**Comment by singhalkirtika** [comment]
@MittalS211 go for it!

**Comment by singhalkirtika** [comment]
Thanks for that @gauravano. I have updated the link.

**Comment by DakshGondaliya** [comment]
Is this issue open? I would like to claim this issue.

**Comment by jywarren** [comment]
It looks like @singhalkirtika has opened a pull request for this! Please see https://code.publiclab.org#r=all for more issues. Thank you!!

**Comment by jywarren** [comment]
Ah, i see that @singhalkirtika has revised this and posted a new replacement issue instead! 

@MittalS211 please see the revised issue over at https://github.com/publiclab/community-toolbox/issues/50

Thank you!!!
