### ISSUE TITLE
Suggestion / request: use Dependabot to keep dependencies up-to-date (reopening for Yarn)

### ISSUE THREAD

**Issue by greysteil** [publiclab/plots2#3571]
First of all, thanks for PublicLab!

I've got a suggestion / request: would you be up for using [Dependabot](https://dependabot.com) to automatically create dependency update PRs for this repo? I ran it against my fork and it generated [these PRs](https://github.com/greysteil/plots2/pulls). I'll port the `uglifier` one across to this repo so it's easier for you to check it out.

I built Dependabot, but I'm honestly only suggesting it because I hope it can save you some time. I'd love any feedback, and obviously having open source repos using Dependabot helps boost its profile, but if it's not helpful to you then it's not really worth anything.

You can install it from [here](https://github.com/apps/dependabot) or [here](https://github.com/marketplace/dependabot) if you decide to give it a try. It's been through GitHub's security testing (to be allowed in the GitHub Marketplace) and is used by a few thousand organisations, and the source code is [here](https://github.com/dependabot/dependabot-core).

:octocat:

**Comment by jywarren** [comment]
Wow, cool! @publiclab/reviewers what do you think? 

Is there a way to have it do the PRs one at a time? Our PR queue is overflowing a bit. 

Also, will to be able to deal with any conflicts if it opens multiple at once and we start merging? 

Thanks!

**Comment by greysteil** [comment]
> Is there a way to have it do the PRs one at a time? Our PR queue is overflowing a bit.

I could set it to only have one PR open at a time, but maybe it would be better for me to help out getting the initial PRs merged? I can review (Dependabot itself is written in Ruby) and get each PR to a point where a maintainer just needs to hit merge. Then, once you're up-to-date you should expect 1-2 PRs a week.

> Also, will to be able to deal with any conflicts if it opens multiple at once and we start merging?

Yep! Automatically detects conflicts and fixes them. I've been working on it full time for 18 months, so it's pretty good at what it does. 😎

**Comment by jywarren** [comment]
Thank you! How many PRs will Dependabot open, do you think? Can we do them in batches? Sorry, we're just a bit cautious about opening more than 5 at a time, but even if it's 10, we can just get ready for it so we're not overwhelmed 😅

Another thing we can do is run this on a less active Public Lab project for starters -- like MapKnitter. Although we would have to warn you that some of our less active projects are far less tested and up to date, so maybe that is not a great idea...

Actually we could do it on a JavaScript library - ours are pretty well maintained, unlike our secondary Ruby libraries. We could try https://github.com/publiclab/image-sequencer/ or https://github.com/publiclab/leaflet-environmental-layers/, perhaps, or https://github.com/publiclab/PublicLab.Editor

Or I'm OK trying it on this repository too!

**Comment by greysteil** [comment]
All of those options sound good!

The maximum number of PRs that Dependabot will create in a single update run is 5, and the maximum is will ever have open for a single repo (for a single language) is 10. Hopefully that's enough not to overwhelm!

**Comment by jywarren** [comment]
Oh that is great. Then let's go ahead with this repo. Shall I install it
then? I'm finishing for the day, but hopefully tomorrow or Friday.

**Comment by greysteil** [comment]
Yes - thanks would be perfect! The easiest way to do so is from [here](https://github.com/apps/dependabot) - let me know if you have any trouble. I'll also look out for the initial PRs and try to help out with the review 🙂

**Comment by jywarren** [comment]
OK - installed and merged a couple smaller ones! A few questions on the remaining 2... upcoming! Thank you!

**Comment by jywarren** [comment]
Hi @greysteil -- we've installed it on a few more projects, and the NPM based ones really have a lot of updates to run. Cool!

https://github.com/publiclab/spectral-workbench.js/pulls

https://github.com/publiclab/PublicLab.Editor/pulls

One question I had was, is it possible to get dependabot to run a build script? We've considered trying to set up an autobuild bot or something to run `grunt build` after any changes to /src/, but for now we do it manually. All our tests run against `/src/` and not `/dist/` so the testing is still all fine, but it would mean we wouldn't have to periodically do a build manually. Just wondering, I know dependabot does a lot already, but I imagine this comes up.

Also, is it OK to be running it on an untested codebase like this one?

https://github.com/publiclab/infragram/pulls

I'll manually test things, but this is not a production project anyways. Just wondering if we're muddying the waters here or something.

**Comment by greysteil** [comment]
Hey @jywarren, that's awesome!

On running a build script: there's no way for Dependabot to do that at the moment :-( Perhaps a use case for the new GitHub Actions?

On running on an untested codebase: that should be totally fine - won't mess anything up on the Dependabot side, and *hopefully* the compatibility scores will make knowing what's non-breaking a little easier :-)

**Comment by jywarren** [comment]
thanks!

**Comment by jywarren** [comment]
We're doing this across all our major repositories now! Thanks so much!

**Comment by jywarren** [comment]
Hi, @dependabot @greysteil - is there a way to set up dependabot to update our yarn.lock file as well, or an example `config.yml` we could look at to achieve this? Thank you!

**Comment by greysteil** [comment]
@jywarren for sure.

```
# .dependabot/config.yml
version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
```

**Comment by jywarren** [comment]
Amazing and so fast. Are you a bot? 😄 Thanks!

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/commit/e3cf2112469c8be284e541579d2bc02b62d39e7a
