### ISSUE TITLE
Inline leaflet maps show URL hash collisions when more than one are on a page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3574]
https://publiclab.org/wiki/inline-maps shows this @sagarpreet-chadha - is there a version update we need to resolve this?

They are generated in this file:

https://github.com/publiclab/plots2/blob/master/app/views/map/_leaflet.html.erb

Do we have to disable the hashes, or just update our version number in package.json?

https://github.com/publiclab/plots2/tree/master/package.json

Thanks!

**Comment by sagarpreet-chadha** [comment]
@jywarren 

https://github.com/publiclab/plots2/blob/885dd06e8f84de1d5b91038e9ff742bd3d0934e1/app/assets/javascripts/leaflet_helper.js#L26

This line is causing the error .

**Comment by jywarren** [comment]
aha. Maybe we should be careful not to re-use the `map` local variable? Could we make an issue of this?

**Comment by jywarren** [comment]
And thanks!!!
