### ISSUE TITLE
Asking a question button link should be generalized .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#3578]
For new users , when we try to post a wiki page - we get following notice : 

<img width="1238" alt="screenshot 2018-10-03 at 12 12 48 pm" src="https://user-images.githubusercontent.com/14952645/46394160-dc532300-c705-11e8-868b-1916134b810e.png">

On clicking the **Asking a question** button it takes us to **_publiclab.org/questions/...._** .
Change this url so that on localhost we go to **localhost:3000/questions/...._**  .

Thanks !

**Comment by TheOllieB** [comment]
Hey, can I complete this please?

**Comment by gauravano** [comment]
Oops, @jywarren merged the PR. Please close the task if you opened it on GCI dashboard. Thanks!

**Comment by jywarren** [comment]
sorry, it checked out and I didn't follow up to see your discussion -- my
bad!

**Comment by gauravano** [comment]
No issue @jywarren , this issue is not present in the staging area and GCI dashboard. I have cross-checked.
