### ISSUE TITLE
Read more button is collapse on the image

### ISSUE THREAD

**Issue by DakshGondaliya** [publiclab/plots2#3581]
### Please describe the problem (or idea)
Read more button of the highlighted blog is collapse on the image of another highlighted blog.
> What happened just before the problem occurred? Or what problem could this idea solve?

![screenshot 206](https://user-images.githubusercontent.com/25260367/46402558-aae65180-c71d-11e8-856a-35d58b6f2cc9.png)

> What did you expect to see that you didn't?
![looklike](https://user-images.githubusercontent.com/25260367/46402622-e41ec180-c71d-11e8-8853-07591425643b.PNG)

### Please show us where to look
https://publiclab.org/?_=1538558612

### What's your PublicLab.org username?
dynamic_daksh
> This can help us diagnose the issue: 

### Browser, version, and operating system
Google Chrome, Version 69.0.3497.100 (Official Build) (64-bit), Windows 10
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment]
Thanks for reporting a bug.
This bug is being addressed in different issue.

**Comment by DakshGondaliya** [comment]
Can u just mention the issue no. so that I can try to solve that issue and make PR of it.

**Comment by SidharthBansal** [comment]
You are going to make a pr? Great. Then go ahead. The issue has not been solved.

**Comment by SidharthBansal** [comment]
Trying to dig out the issue number if I can. 
You can work on it.

**Comment by SidharthBansal** [comment]
There are two errors
1. No space between read and the next image
2. Read button should be center aligned below the images

**Comment by DakshGondaliya** [comment]
Thank you @SidharthBansal

**Comment by SidharthBansal** [comment]
Please solve both the errors. Also please check that this error is not
reproducing on other pages of the website.

**Comment by SidharthBansal** [comment]
Like the profile page, home page, dashboard page, tag page etc.
Thanks

**Comment by vanguard07** [comment]
@publiclab/mentors I have found out what is causing this issue but I'm unable to find the source page in the repository, so that I can fix it. Can anyone help?

**Comment by jywarren** [comment]
I'm not positive, but I believe it may be here!

https://github.com/publiclab/plots2/tree/master/app/views/notes/_notes.html.erb

**Comment by vanguard07** [comment]
@jywarren Thanks. If this is the file then the issue will will be solved. 
Sorry for the late reply, was busy with exams. 😅

**Comment by jywarren** [comment]
Oh no problem. Do you mean it has been solved already then, or that you will be able to later? 

Good luck with your exams, no worries!

**Comment by vanguard07** [comment]
@jywarren The required changes was done in the above mentioned file, but I can't verify the changes as I'm unable to run plots2 locally. 
Initially, the Read More button collapsed on the image.
![Earlier](https://user-images.githubusercontent.com/23207859/47314825-6dac1a00-d660-11e8-8597-a220a7fe4791.png)

After removing the "float: right", the button no longer collapsed.
![After making the necessary CSS changes](https://user-images.githubusercontent.com/23207859/47314914-a2b86c80-d660-11e8-829e-7ca97deed92a.png)

Could you help as to how I can proceed?

**Comment by jywarren** [comment]
This sounds good - if you want, you can make edits in the browser: https://help.github.com/articles/editing-files-in-your-repository/

Or if you like we can invite you to use Cloud9 to make your changes remotely! https://console.aws.amazon.com/cloud9/home

**Comment by vanguard07** [comment]
@jywarren @SidharthBansal Please review the PR. 😅

**Comment by gauravano** [comment]
Thank you all for working on this. This issue seems resolved :point_down: 

![updated_view](https://user-images.githubusercontent.com/20878070/54276699-f85fc800-45b3-11e9-9003-e19d0cec0393.png)


so closing this.
