### ISSUE TITLE
Login popover in not responsive in smartphone view

### ISSUE THREAD

**Issue by DakshGondaliya** [publiclab/plots2#3583]
### Please describe the problem (or idea)
Login popover is not responsive in the smartphone ie. in the laptop if you shrink the screen.
> What happened just before the problem occurred? Or what problem could this idea solve?

![-public-lab_-a-diy-environmental-science-community-goo](https://user-images.githubusercontent.com/25260367/46405277-6363c380-c725-11e8-91e5-8c2c2e990fe1.gif)

### Screenshot of Login in smartphone view
![mobileloginview](https://user-images.githubusercontent.com/25260367/46405370-b89fd500-c725-11e8-9165-d6b9eebede21.PNG)

> What did you expect to see that you didn't?
### It can be more responsive if we create a popover separately like laptop view.

![loginpopover](https://user-images.githubusercontent.com/25260367/46406245-8479e380-c728-11e8-8f58-eb2095ad3034.PNG)

### Please show us where to look
https://publiclab.org

### What's your PublicLab.org username?
dynamic_daksh
> This can help us diagnose the issue: 

### Browser, version, and operating system
Google Chrome, Version 69.0.3497.100 (Official Build) (64-bit), Windows 10
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by avsingh999** [comment]
@DakshGondaliya  thank you for contribution But  this issue is already  created #3528
