### ISSUE TITLE
Make pop-up for link social media button

### ISSUE THREAD

**Issue by avsingh999** [publiclab/plots2#3584]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### 🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem
In user profile page here is link social media button if we click on this button it' show alert and user type input in this alert form it would be better if there is any pop-up and user type input this form. It will make page very attractive

![sociallink](https://user-images.githubusercontent.com/25536022/46406427-27326200-c729-11e8-984a-d0174c039ea7.png)

### 📋Solution

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**   
some thing like this.
https://www.w3schools.com/bootstrap/bootstrap_modal.asp

Code links….
https://github.com/publiclab/plots2/blob/232907d9677ca6d5409bdd2834cfc41d4a97d1b4/app/views/users/profile.html.erb#L217

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by SidharthBansal** [comment]
This has been marked as a good candidate for becoming a first-timers-only issue like these, meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider reformatting or reposting it as a first-timers-only issue, and then ping @SidharthBansal to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.
