### ISSUE TITLE
Make pop-up for My access Token Button

### ISSUE THREAD

**Issue by avsingh999** [publiclab/plots2#3586]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### 🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem
In user profile page here is link My access token if we click on this button it' show alert it would be better if there will be any pop-up. It will make the page very attractive

![token](https://user-images.githubusercontent.com/25536022/46406943-d6236d80-c72a-11e8-93af-1cf041161f65.png)

### 📋Solution

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**   
some thing like this.
https://www.w3schools.com/bootstrap/bootstrap_modal.asp

Code links….
https://github.com/publiclab/plots2/blob/232907d9677ca6d5409bdd2834cfc41d4a97d1b4/app/views/users/profile.html.erb#L213

https://github.com/publiclab/plots2/blob/232907d9677ca6d5409bdd2834cfc41d4a97d1b4/app/views/users/profile.html.erb#L273

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by SidharthBansal** [comment]
@avsingh999 can you please add some code links so that gci students will be able to send a patch quickly to your issues?
Thanks

**Comment by HarshKhandeparkar** [comment]
Is this related ro ruby or is it pure javascript/html/css?

**Comment by HarshKhandeparkar** [comment]
I'm actually working on this issue.

**Comment by HarshKhandeparkar** [comment]
I have claimed the GCI task. Just wanted to ask if I should add a copy button to the alert?

**Comment by SidharthBansal** [comment]
Yeah you can add it. Please open a PR we will discuss there

**Comment by HarshKhandeparkar** [comment]
Ok, will do so.
