### ISSUE TITLE
Add Publiclab organization link to community-toolbox website

### ISSUE THREAD

**Issue by DakshGondaliya** [publiclab/plots2#3589]
### Please describe the problem (or idea)
A link is required to visit Publiclab organization.
> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look
https://code.publiclab.org/

### What's your PublicLab.org username?
dynamic_daksh
> This can help us diagnose the issue: 

### Browser, version, and operating system
Google Chrome, Version 69.0.3497.100 (Official Build) (64-bit), Windows 10
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by DakshGondaliya** [comment]
I am working on this issue.

**Comment by igniteeng000** [comment]
Also add link to the publiclab website.

**Comment by jywarren** [comment]
Cool! Please link back from any PR you open :-)

And a screenshot would be great!

Thanks!
