### ISSUE TITLE
Add social media links and icons to the footer of the store page

### ISSUE THREAD

**Issue by rohan2599** [publiclab/plots2#3590]
### Please describe the problem (or idea)
The footer needs to be filled with the social media links of the organisation and the icons of each social media i.e facebook , twitter and instagram needs to be added as it is not giving a professional look.
It is also occupying a large space of the footer without nothing being rendered except a follow us button.
![screenshot 50](https://user-images.githubusercontent.com/31514059/46429878-1e5f8180-c765-11e8-8cca-853ff14c4030.png)

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?
The footer page is looking empty which doesn't gives a good impression

### Please show us where to look

https://store.publiclab.org/

### What's your PublicLab.org username?
Rohan2599
> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by rohan2599** [comment]
I am working on this issue

**Comment by jywarren** [comment]
Hi, unfortunately this may need to be closed, as we cannot edit the store
code -- it's a separate site. We very much appreciate your help however!

See more at https://code.publiclab.org#r=all

Thanks!

**Comment by rohan2599** [comment]
ok , no problem
