### ISSUE TITLE
Add a Share button on questions page

### ISSUE THREAD

**Issue by vikul1234** [publiclab/plots2#3591]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem
There is no sharing feature to share questions.

### 📋Solution
Add a share button on questions page

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** https://github.com/publiclab/plots2/blob/master/app/views/questions/_answer.html.erb

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by Rohit280297** [comment]
Can I work on this @vikul1234 ?

**Comment by jywarren** [comment]
Ah, i think this may be just a link to:

https://publiclab.org/questions/TK_Siddharth/09-20-2018/what-would-be-the-day-to-day-use-of-spectroscopy#a1207

 instead of:

https://publiclab.org/questions/TK_Siddharth/09-20-2018/what-would-be-the-day-to-day-use-of-spectroscopy

so it links directly to this answer. But we should make the icon "fa
fa-link" instead of "fa fa-share" -- on this line:

https://github.com/publiclab/plots2/blob/a74987812aec5435717044f76206892399c71ae6/app/views/questions/_answer.html.erb#L60

**Comment by vikul1234** [comment]
So sharing button is not required on that page.

**Comment by vikul1234** [comment]
I think sharing button instead of link will be better, if we can share to other platforms

**Comment by jywarren** [comment]
That sounds good, but we should solve this ambiguity first and open a
separate issue for that. One thing at a time :-)

But very grateful for your help!

**Comment by vikul1234** [comment]
Ok, working on that.

**Comment by vikul1234** [comment]
@jywarren please assign fto, gci candidate label

**Comment by jywarren** [comment]
Hi, I think this may not be simple enough for a newcomer, but could be broken up into multiple parts... have a read of this to learn more:

https://publiclab.org/notes/warren/01-18-2018/software-outreach-modularity-is-great-for-collaboration

What do you think?

**Comment by vikul1234** [comment]
Then convert this issue to help wanted.

**Comment by vikul1234** [comment]
Task1: add a share button.
Task2: Provide different mediums to share that question.

**Comment by vikul1234** [comment]
What do you think?

**Comment by vikul1234** [comment]
we can also extend it further by
One will work to share on facebook, other on twitter and so on.

**Comment by vikul1234** [comment]
on clicking share button ,popover will show fb, twitter , etc icons which users can select to share the question

**Comment by jywarren** [comment]
:-)

Also some nice styling examples on pages like this: https://store.publiclab.org/products/raspberry-pi-camera

**Comment by dave-light** [comment]
@vikul1234 @jywarren As this issue is still open and no PR is linked may I assume nobody is working on it? I notice fto in the initial comment but no fto tag. Since GCI has finished, unsure if this will be completed if not already?

**Comment by gauravano** [comment]
Hi @dave-light you can take this issue. Thanks!

**Comment by gauravano** [comment]
Hi @dave-light, @jywarren is referring to these buttons:
![share_buttons](https://user-images.githubusercontent.com/20878070/50922220-f83a3380-146f-11e9-80ab-c868c141299b.png)

Twitter share button is already present, can you add Facebook share button? 
And, as the share link issue is still unclear we can let it go for now. @jywarren please throw some light on link/favicon part whenever you get time.

Thanks!

**Comment by dave-light** [comment]
@gauravano great, i'll add the fb button.

**Comment by dave-light** [comment]
Just checking facebook's site here https://developers.facebook.com/docs/plugins/share-button and in addition to the standard 'share' button there's the option for 'share [number of shares] '  

![image](https://user-images.githubusercontent.com/25173051/51040421-5a4d8280-15af-11e9-8591-eb7ea6a20244.png)

It's a matter of preference I suppose, so better I ask, what would you suggest @gauravano?

**Comment by gauravano** [comment]
I think we don't need count. What do you say @jywarren?
