### ISSUE TITLE
Inline map API calls a bit broken?

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3597]
@milaaraujo @stefannibrasil I think you can probably offer some quick input here -- it looks like some of the calls going from different types of inline maps are malformed... could you help us untangle what they should be and we can slot in some fixes?

Thanks! Probably similar to, or related to, #3573 

https://publiclab.org/wiki/inline-maps

![image](https://user-images.githubusercontent.com/24359/46441346-3b2f9100-c734-11e8-915c-dc60db9c93db.png)

**Comment by jywarren** [comment]
For example, the first call was to https://publiclab.org/api/srch/taglocations?query=43,-71 which shows a 500 error, but it's probably missing a parameter?

**Comment by rohan2599** [comment]
I want to work on it

**Comment by sagarpreet-chadha** [comment]
Hi @rohan2599 .
Yes that would be great :)
This issue may require some investigative work , so feel free to ask for help if you get stuck anywhere .
Thank you !

**Comment by sagarpreet-chadha** [comment]
Hi @rohan2599 
Just checking if you are stuck or need help somewhere 😄 !

**Comment by sk9331657** [comment]
@rohan Are u still working on it ?? Shall I take up this issue??

**Comment by milaaraujo** [comment]
@stefannibrasil, maybe you can help with this one!

**Comment by stefannibrasil** [comment]
I'll take a look :+1:

**Comment by stefannibrasil** [comment]
hi @jywarren did you used to call the API always like this? I believe it requires two zero digits after the point the way it was implemented, for example:

https://publiclab.org/api/srch/taglocations?query=29.00,-90.00 - 200
https://publiclab.org/api/srch/taglocations?query=43.00,-71.00 - 200

anything else besides that breaks, for example:

https://publiclab.org/api/srch/taglocations?query=29,-90 - 500
https://publiclab.org/api/srch/taglocations?query=40.70,-73.90 - 500

Could you send me more details about the error? For what I can see, I believe we need to require the 2 0's after the point?

**Comment by stefannibrasil** [comment]
hi @jywarren, I added some changes here #3700. Could you please take a look? Thanks!
