### ISSUE TITLE
login and access dates are probably not being updated

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#360]
According to my profile, my last login and access to publiclab.org was 2013-07-23. I know time flies but I am 85% certain I logged in and accessed the site sometime in 2014 and sometime in 2015.

**Comment by ebarry** [comment]
It would be great to get this working.

**Comment by ananyo2012** [comment]
@ebarry Can you tag this with a help wanted tag so that it will be easier to filter? I can probably look into this soon.

**Comment by jywarren** [comment]
I believe this is actually working -- checked my own login time recently. Thanks!
