### ISSUE TITLE
[Multiple-use] Add explanation to all node-based email notifications to reply-by-email

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3606]
We have a new reply-by-email system! It's great, and means you can reply to many emails you get from PublicLab.org and expect your email to be added as a comment. 💬 💥 ✉️ 

However, not all our email notifications make this clear yet -- since this is new, most warn people NOT to reply by email. Let's change that! 🎉 

Changing it will take 3 steps per email template:

## 1. Change email subject lines to include node ids in format `(#0000)`

The new feature works by looking for a node ID in the subject line, looking up that node and attaching response emails to that node as comments. So we need each email notification to have a specially formatted node id in the subject line. Here's how they should change:

```diff
    mail(to: user.email, subject: 'You were mentioned in a comment.')
    mail(to: user.email, subject: "You were mentioned in a comment. (##{comment.node.id}) ")
```

The variable may be `node.id` instead of `comment.node.id` -- it depends on the context. You can find all the mailer functions in this folder, so look through to see which one you want to take on:

https://github.com/publiclab/plots2/tree/master/app/mailers

## 2. Change instructions in email body

Many email addresses warn you not to reply by email with the phrase `Do NOT reply to this email`. You can find them in this search (until we get them all!):

https://github.com/publiclab/plots2/search?q=%22Do+NOT+reply+to+this+email%22&unscoped_q=%22Do+NOT+reply+to+this+email%22

Once the email subject line is changed for a given template (and not before!) we can change this instruction from the top line to the bottom line:

```diff
- Hi! There's been a response to a discussion you're involved in. Do NOT reply to this email; click this link to respond:
+ Hi! There's been a response to a discussion you're involved in. You can reply to this email or visit this link:
```

See how someone did this for an existing template here: https://github.com/publiclab/plots2/commit/990c965aea47da7613c2825949a42f1ca7c29ec1

## 3. Update test

We'll help you with this step. Basically we have tests to confirm the subject line of each message sent. We'll need to update the tests to reflect the new subject lines, like this!

```diff
-    assert_equal "[PublicLab] #{user.username} liked your research note", email.subject
+   assert_equal "[PublicLab] #{user.username} liked your research note (##{node.id})", email.subject
```

That's it! Please take on only one email notification at a time in a pull request, and we can help and double-check your work. 

Also, some email notifications are not linked to just a single node -- so those won't be helpful to convert. If in doubt, link to the one you want to try (in the comments below) and we'll explain! 👍

**Comment by rohan2599** [comment]
I want to work on this

**Comment by jywarren** [comment]
that'd be great!

**Comment by rohan2599** [comment]
@jywarren can you please tell me that which files are need to be changed in test/unit  folder  because in the subscription_mailer_test.rb all the changes are done , so what are the changes that are needed to be done in the files? I'm a little bit confused .Thank you.

**Comment by jywarren** [comment]
Ah, you are right, i think all of the mailer files are converted. So step 1 is complete! I think we can move to steps 2 and 3 for any templates and tests that are not converted. Thanks!

**Comment by rohan2599** [comment]
@jywarren I have completed step1 and step 2 ,Actually I was talking about step 3 i.e which files are needed to be changed in step 3 ,because the test/unit/subscription_mailer_test.rb is fully changed ,so do I need to change all the mailer test files ?
.Thank you.

**Comment by jywarren** [comment]
Ah, well if you open a PR, and no tests fail, you are ALL GOOD :-)
