### ISSUE TITLE
Add a newline code for auto reply of bot after successfully merging a PR

### ISSUE THREAD

**Issue by Dhiraj240** [publiclab/plots2#3611]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [.github/config.yml](https://github.com/publiclab/plots2/blob/master/.github/config.yml#L24) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
- Now that you've completed this, you can help someone else take their first step! See: https://code.publiclab.org
+Now that you've completed this, you can help someone else take their first step! 
+See: [Public Lab's coding community!](https://code.publiclab.org)
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [Dhiraj240](https://github.com/Dhiraj240).)

**Comment by Dhiraj240** [comment]
@jywarren is this the right way to create a first timer issue for newcomers.I will submit other issues after it which i can solve on my own.
I created this as per the requirement to become GCI mentor.

**Comment by Dhiraj240** [comment]
Also please label it as ```first-timer-issue```

**Comment by gowrimanoharir** [comment]
Hi, I would like to take this issue, thanks.

**Comment by bhavukkalra** [comment]
is someone already working on this issue? if not, can i take it?

**Comment by agam-kashyap** [comment]
HI, I would like to take this issue if no one has claimed it yet.
Thanks.

**Comment by Dhiraj240** [comment]
@publiclab/reviewers will you assign them? mainly who commented first.

**Comment by SidharthBansal** [comment]
Yes its first come first service. @gowrimanoharir you can take the issue. Rest can do other issues

**Comment by Dhiraj240** [comment]
@gowrimanoharir Just send your PR for the issue and tag me i will review it, if i am allowed to do so.But otherwise i will comment on it to assist you.

**Comment by gowrimanoharir** [comment]
@dhiraj240 thank you, will let you know once I complete the pr.

**Comment by gowrimanoharir** [comment]
@Dhiraj240 created the pr https://github.com/publiclab/plots2/pull/3668 the CI build still seems to be in progress as I type this, unsure how long that will take. Please let me know if anything is amiss.

**Comment by SidharthBansal** [comment]
If Travis takes longer than usual time, close the PR and open the same
closed PR again. Sometimes Travis gets paused. Don't know why.
So closing and opening the same PR helps
