### ISSUE TITLE
Improve wiki page for mobile view / short width screen

### ISSUE THREAD

**Issue by avsingh999** [publiclab/plots2#3617]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem
https://publiclab.org/wiki in this page here is wiki's pages link where we click and render that particular page, this data are shown in html table but if we decrease the screen size or view this page in mobile 

 then like column in this table  will disappear.
- full screen size
![wiki2](https://user-images.githubusercontent.com/25536022/46533938-0e11e880-c8c4-11e8-99dc-4813d830b59f.png)

- short screen size / mobile view

![wiki3](https://user-images.githubusercontent.com/25536022/46534441-b8d6d680-c8c5-11e8-91b9-fcacc0c71c20.png)

### 📋Solution

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**  remove class="hidden-xs"

Code links….
https://github.com/publiclab/plots2/blob/738d54d13c805a59c4d05c9717f81af24d830dc2/app/views/wiki/_wikis.html.erb#L15

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by SidharthBansal** [comment]
@avsingh999 can we make this gci issue?? We are really near gci and need more than 100 issues for them.
Can you please add the message and add labels?

**Comment by jywarren** [comment]
Also, i believe it's possible some table columns are hidden on smaller
screens to make space. Could you check if that's the case? Thanks!

**Comment by agam-kashyap** [comment]
Hi, I would like to work on this if no one else has claimed it. Also I might need some guidance as it is my first time doing such a thing.

Thank you.

**Comment by SidharthBansal** [comment]
Sorry, you can't commit changes for this issue.
We are participating in Google Code In. This issue is reserved for Google Code In Students only. 
we'd love help with another issue -- especially looking at helping others make their first contributions!

Maybe take a look at one of these?

https://github.com/publiclab/plots2/labels/support
