### ISSUE TITLE
Describing a way for people to turn on Layers .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#3626]
We are using maps all over the side and recently we have integrated Leaflet-Environmental-library in all the maps . 
We need to add a descriptive text on the map so that people can know how to turn on layers . 

@ebarry mentioned great ideas for solving this issue : 

> Proposal: when the in-line map tag is used, it would not only add the map on the page as shown, but also above it, include a line of text saying, "to turn on environmental layers, click the icon in the top right!"

> Maybe we could try a version which also said, "To learn about this project and give feedback, visit [link-to-this-post]"

# Solution : [Open to better solutions as well]
We can use the `attribution` attribute : 

```
 L.tileLayer('http://tiles.mapc.org/basemap/{z}/{x}/{y}.png',
    {
      attribution: 'to turn on environmental layers, click the icon in the top right!',
      maxZoom: 17,
      minZoom: 9
    }).addTo(map);
```

Thanks !

**Comment by gauravano** [comment]
Hi @sagarpreet-chadha, can you add the link to the files and maybe open a new issue using all these details? Thanks!

**Comment by jywarren** [comment]
Let's merge back into this:

https://github.com/publiclab/leaflet-environmental-layers/issues/60#issuecomment-460462757

and ref this too: https://github.com/publiclab/leaflet-environmental-layers/issues/123

Thanks!
