### ISSUE TITLE
List of answers answered by the user is not displayed on clicking the answered button

### ISSUE THREAD

**Issue by rohan2599** [publiclab/plots2#3627]
### Please describe the problem (or idea)
The user profile section page is not displaying the list of answer answered by the users.However, it is showing the no of answers answered by the user.

> What happened just before the problem occurred? Or what problem could this idea solve?TH
It is showing the number of answers answered by the user:
![capture4](https://user-images.githubusercontent.com/31514059/46557159-a29d3a80-c906-11e8-942f-321b3c306185.PNG)

But on clicking the questions answered by the user , it is not displayed:
![capture2](https://user-images.githubusercontent.com/31514059/46557194-bb0d5500-c906-11e8-82b5-0066082a8949.PNG)

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/questions/tag/question:*/author/username
https://publiclab.org/profile/username

### What's your PublicLab.org username?
201651044
> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by rohan2599** [comment]
@publiclab/mentors please review

**Comment by sk9331657** [comment]
@publiclab/mentors I am claiming it.

**Comment by rohan2599** [comment]
@sk9331657 go ahead

**Comment by jywarren** [comment]
I believe this is no longer needed as the profile page has changed! Thanks all!
