### ISSUE TITLE
Can't post/preview an answer to a question without first subscribing to the topic

### ISSUE THREAD

**Issue by joyofsoy** [publiclab/plots2#3629]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
I was trying to post an answer to a question, but was clicking on Post and Preview and nothing happened. I thought it was a bug but then finally found the note at the topic saying that you have to first subscribe to a topic before you can answer a question related to it.
![screen shot 2018-10-05 at 4 59 30 pm](https://user-images.githubusercontent.com/43895356/46562184-8aa2c800-c8c0-11e8-9f5e-1a72a0e5e5bf.png)

> What did you expect to see that you didn't?
Since I was typing in my answer at the bottom, I didn't catch the note at the top that you have to first subscribe to a topic before posting an answer. I subscribed to the topic, reloaded, and was able to post the answer. Was this just the server being slow or is this a newer feature where you are required to subscribe before answering?

### Please show us where to look

https://publiclab.org/q/17225

### What's your PublicLab.org username?
joyofsoy
> This can help us diagnose the issue: 

### Browser, version, and operating system
Chrome Version 69.0.3497.100
macOS High Sierra 10.13.6

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
I think this was a bug in posting, and the notice was actually unrelated -- I'm going to close it for now since posting answers should work normally and then there won't be the ambiguity of the above message!
