### ISSUE TITLE
Logout alert notification doesn't fade away automatically

### ISSUE THREAD

**Issue by Rishabh570** [publiclab/plots2#3632]
### Please describe the problem (or idea)
After logging out from `publiclab.org`, an alert box appears telling that you're successfully logged out, but it stays there unless you manually remove it(by clicking on the cross in alert box) or the page gets reloaded. This seems a bit odd.

> What happened just before the problem occurred? Or what problem could this idea solve?
![screenshot from 2018-10-06 09-51-16](https://user-images.githubusercontent.com/25483260/46567306-72798a00-c94e-11e8-9d82-81827410e77f.png)

> What did you expect to see that you didn't?
The alert box should fade away after 1-2 seconds.

### Please show us where to look

https://publiclab.org/

### What's your PublicLab.org username?
icode365

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by champagnepappi** [comment]
Hi, Leme work on this one

**Comment by Rishabh570** [comment]
@champagnepappi Sure, go ahead!! :+1:
