### ISSUE TITLE
Improve the look of Infragram

### ISSUE THREAD

**Issue by DakshGondaliya** [publiclab/plots2#3636]
### Please describe the problem (or idea)
Change the look of the block of images and pagination.
> What happened just before the problem occurred? Or what problem could this idea solve?
### Screenshot 1
![currentview1](https://user-images.githubusercontent.com/25260367/46571253-44686a00-c98f-11e8-88c7-303196ca2db4.PNG)

### Screenshot 2
![currentview2](https://user-images.githubusercontent.com/25260367/46571255-492d1e00-c98f-11e8-9011-c7c1d8803101.PNG)

### Screenshot 3
![currentview3](https://user-images.githubusercontent.com/25260367/46571257-4df1d200-c98f-11e8-84d1-3abaed16ef84.PNG)

> What did you expect to see that you didn't?
### Video of the Improved look
[ImprovedLook.zip](https://github.com/publiclab/plots2/files/2453006/ImprovedLook.zip)

### Screenshot 1
![newview3](https://user-images.githubusercontent.com/25260367/46571187-39f9a080-c98e-11e8-88d8-537c52449b5b.PNG)

### Screenshot 2
![newview1](https://user-images.githubusercontent.com/25260367/46571183-336b2900-c98e-11e8-8f24-f871cd190da3.PNG)

### Screenshot 3
![newview2](https://user-images.githubusercontent.com/25260367/46571185-36661980-c98e-11e8-84f3-8421018c7d63.PNG)

### Please show us where to look
http://infragram.org

### What's your PublicLab.org username?
dynamic_daksh
> This can help us diagnose the issue: 

### Browser, version, and operating system
Google Chrome, Version 69.0.3497.100 (Official Build) (64-bit), Windows 10
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by DakshGondaliya** [comment]
I am working on this issue.

**Comment by DakshGondaliya** [comment]
@jywarren please review it.

**Comment by gauravano** [comment]
@jywarren do you think, we can transfer this issue to infragram-js repo? Thanks!
