### ISSUE TITLE
Subscription button collapsing in the mobile view

### ISSUE THREAD

**Issue by roshniRam** [publiclab/plots2#3643]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

In this page, in the mobile view the subscription button collapses just below the email text field.
https://publiclab.org/wiki/barnraising-texas-2019

![screenshot 53](https://user-images.githubusercontent.com/30633549/46592860-2ceec580-cae4-11e8-85f9-9fda8f819c99.png)

![screenshot 54](https://user-images.githubusercontent.com/30633549/46592865-3710c400-cae4-11e8-8eb6-31b030c9d8b2.png)

> What did you expect to see that you didn't?

There should be some spacing between email field and subsription button.

### Please show us where to look

https://publiclab.org/wiki/barnraising-texas-2019

### What's your PublicLab.org username?
roshni_ram001

> This can help us diagnose the issue: 

### Browser, version, and operating system
Chrome, windows 10

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment]
This has been marked as a good candidate for becoming a first-timers-only issue like these, meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider reformatting or reposting it as a first-timers-only issue, and then ping @SidharthBansal to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by yasmindias** [comment]
I would like to work on this issue.

**Comment by gauravano** [comment]
Hi @roshniRam the page you tagged https://publiclab.org/wiki/barnraising-texas-2019 is a wiki page and the form is part of node body. It's not related to our code base, so I have to close this issue. Also, wiki page is open for edit, in case you like to fix the mobile view. Thanks!

Hi @yasmindias, we would love to have your help, please check at https://code.publiclab.org/#r=all for more issues. Thanks!
