### ISSUE TITLE
Add button colliding with the enter tag in the mobile view 

### ISSUE THREAD

**Issue by rohan2599** [publiclab/plots2#3644]
### Please describe the problem (or idea)
In the subscription page , when opening the mobile view , the add button is colliding with the enter tag which shows that the page is needed to be improved and made responsive.
Desktop view:
![capture6](https://user-images.githubusercontent.com/31514059/46592941-f5cce400-cae4-11e8-83b2-e8b5957934bb.PNG)
Mobile view:
![capture7](https://user-images.githubusercontent.com/31514059/46592950-01b8a600-cae5-11e8-819f-f87643816e56.PNG)

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/subscriptions

### What's your PublicLab.org username?
201651044
> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment]
This has been marked as a good candidate for becoming a first-timers-only issue like these, meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider reformatting or reposting it as a first-timers-only issue, and then ping @SidharthBansal to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by sk9331657** [comment]
@SidharthBansal  I am claiming it.

**Comment by rohan2599** [comment]
@sk9331657 go ahead

**Comment by sk9331657** [comment]
@rohan2599  Thanks You

**Comment by sk9331657** [comment]
@rohan Is organization still accepting GCI Mentor applications??

**Comment by rohan2599** [comment]
Please ask to@SidharthBansal for this.

**Comment by SidharthBansal** [comment]
Forms arent closed yet.

**Comment by jywarren** [comment]
Yes, you can find out more here!
https://github.com/publiclab/plots2/issues/3168
