### ISSUE TITLE
Display message to enter login details.

### ISSUE THREAD

**Issue by Dhiraj240** [publiclab/plots2#3646]
### Please describe the problem (or idea)
If a user do not enter any information in the email and password fields then it should, display a message to enter it.Instead of following.

> What happened just before the problem occurred? Or what problem could this idea solve?
![screenshot 173](https://user-images.githubusercontent.com/29758643/46611691-18362000-cb2c-11e8-9d51-cbd35d161f29.png)

> What did you expect to see that you didn't?
A simple form message to ask for details.

### Please show us where to look

I need to investigate

### What's your PublicLab.org username?
Dhiraj24

> This can help us diagnose the issue: 

### Browser, version, and operating system
Google Chrome, latest and OS is Windows 8.1

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by Dhiraj240** [comment]
@publiclab/reviewers @jywarren  i would like to work on it.

**Comment by agam-kashyap** [comment]
Hello, I would like to work on this issue as my first time. 
Thank you

**Comment by SidharthBansal** [comment]
@dhiraj240 go ahead

**Comment by SidharthBansal** [comment]
@agam-kashyap you can try other issues

**Comment by gauravano** [comment]
Hi @Dhiraj240, have you started working on this one? Thanks!

**Comment by gauravano** [comment]
@agam-kashyap you can see more issues at https://code.publiclab.org/#r=all and feel free to comment here in case you can't find any unclaimed issue, we'll try to open one for you. Thanks!

**Comment by Dhiraj240** [comment]
@gauravano  no, i have been more inclined towards ```mapknitter``` @agam-kashyap  you should start.

**Comment by agam-kashyap** [comment]
@Dhiraj240 I will get working on it then. Thanks.

**Comment by ananyaarun** [comment]
Hey i would like to take this up. A message like this " There is nobody in our system by that name, are you sure you have the right username?" as seen in other cases would be more suitable in this case.
Also @Dhiraj240 were u able to reproduce this error in ur local installation ?

**Comment by ananyaarun** [comment]
@jywarren @gauravano , I notice that the error msg of banned user comes only in the case of not entering both username and password. Should we have separate error msgs for the case of 
1) entering only username
2) entering only password 
3) username not in DB
4) password doesn't match username but username in DB
Also though i see this error in the public labs page i don't seem to be able to reproduce it in my local installation.

**Comment by gauravano** [comment]
We can perform proper form validation so the form will be submitted only when all the required fields are provided by the user.
