### ISSUE TITLE
Add "control-enter" hotkey to post a comment, like on GitHub/Gmail

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3648]
I write a lot of comments, and sometimes it's nice to be able to hit `control-enter` (or `command-enter` on a Mac) to post the comment. This is a nice convention on GitHub and also for sending an email on Gmail. I think it should be relatively easy to code up using a standard mini library from NPM (https://www.npmjs.com/search?q=keywords:keybinding maybe?) or perhaps some jQuery. 

This will involve a bit of problem solving and creativity -- any help appreciated!

**Comment by sk9331657** [comment]
I am claiming it @jywarren  .

**Comment by sk9331657** [comment]
@jywarren  Can I work on it ??

**Comment by sagarpreet-chadha** [comment]
@sk9331657 ...go for it  ! 
Feel free to discuss the approach 😄 . Thank you !

**Comment by agam-kashyap** [comment]
Can i work on it. Haven't been able to find any issue to work on. 
Thank you.

**Comment by sk9331657** [comment]
@sagarpreet-chadha  @SidharthBansal  @jywarren  Solved this help needed issue.
