### ISSUE TITLE
Removing "schedule" statement from pull_request_template

### ISSUE THREAD

**Issue by geekychaser** [publiclab/plots2#3649]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

![image](https://user-images.githubusercontent.com/24489162/46623467-5989f800-cb4b-11e8-8bd9-24a4028e8fc9.png)

this statement should not be there in PR body

> What did you expect to see that you didn't?

 schedule for reviewing and pulling a pull request should be removed

### What's your PublicLab.org username?

geekychaser

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by geekychaser** [comment]
@SidharthBansal can i work on this?

**Comment by SidharthBansal** [comment]
Great catch @geekychaser
