### ISSUE TITLE
Improve the button group at the bottom of infragram page

### ISSUE THREAD

**Issue by Rishabh570** [publiclab/plots2#3652]
### Please describe the problem (or idea)
The forward and fast-forward buttons in the button group at the bottom of `infragram.org` page are not very nice from the UI standpoint. They can be either made like the ones in `publiclab.org` or we can add an svg/png for them.

> What happened just before the problem occurred? Or what problem could this idea solve?

Currently, the button group at `infragram.org` looks like,

![screenshot from 2018-10-09 11-44-15](https://user-images.githubusercontent.com/25483260/46650307-a60c1c80-cbb9-11e8-87f5-f0bb5c1cc8c3.png)

We can either make it like the one at `publiclab.org`, which looks like

![screenshot from 2018-10-09 11-51-37](https://user-images.githubusercontent.com/25483260/46650363-d5228e00-cbb9-11e8-95b2-8b9e676d6b72.png)

or we add an SVG/PNG, (flaticon.com has many options)

### Please show us where to look

https://infragram.org

### What's your PublicLab.org username?

icode365

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by faithngetich** [comment]
I'd like to work on this issue

**Comment by Rishabh570** [comment]
@champagnepappi Code related to infragram is [here](https://github.com/publiclab/infragram-js)
@faithngetich Go ahead!

**Comment by faithngetich** [comment]
Thanks @Rishabh570 I have been able to access the http://localhost:8000/sandbox/ but I have not been able to navigate to the local version of the site below in the screenshot.  Could you please help. 
<img width="1171" alt="screen shot 2018-10-14 at 11 48 17" src="https://user-images.githubusercontent.com/23743836/46914514-a0427c80-cfa7-11e8-8e6a-6061dcaac912.png">

**Comment by Rishabh570** [comment]
@faithngetich Okay, so you want to see that button group on localhost...do this,

- Go to [index.js](https://github.com/publiclab/infragram-js/blob/master/routes/index.js) of routes and in `export.index` function, remove everything(or comment them out) such that it should contain only this:

```
res.render('index', {
          title: 'Infragram: online infrared image analysis',
          images: "",
          pageNumber: 1,
          pageCount: 1
        });
```

I think searching for an image in local db is causing the template to not get rendered...Try this and then go to `localhost:8001/`

**Comment by Rishabh570** [comment]
@faithngetich Were you able to open that page up on localhost?

**Comment by faithngetich** [comment]
Hey @Rishabh570 yes I have thanks.

**Comment by faithngetich** [comment]
`localhost:8001/`  is not working though so I have just had to access it through `localhost`

**Comment by Rishabh570** [comment]
No worries, you can change the port in `app.js` if it's not working anyways (only for development obviously)

**Comment by faithngetich** [comment]
@Rishabh570 could you please my PR. Here's the link to the[ PR](https://github.com/publiclab/infragram-js/pull/9)

**Comment by jywarren** [comment]
This was solved by @faithngetich ! Thank you! 

Actually if you put the exact text `closes #____` where `____` is the issue number, in the PR description, then when the PR is merged, the corresponding issue is closed automatically! Just a tip!
