### ISSUE TITLE
Add share option for questions page

### ISSUE THREAD

**Issue by vikul1234** [publiclab/plots2#3653]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$_answer.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/questions/_answer.html.erb) in the `$REPO` repository (press the little pen Icon) and edit after the line 60 as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
+ <a href="#a<%= answer.id %>" class="btn btn-default btn-sm "><i class="fa fa-share"></i></a> &nbsp;
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by agam-kashyap** [comment]
Hey, can i take it? Thanks.

**Comment by vikul1234** [comment]
go ahead.

**Comment by agam-kashyap** [comment]
Thank you. 😁😁

**Comment by sk9331657** [comment]
@agam-kashyap  You can go for this https://github.com/publiclab/plots2/issues/3655 . This is a first time issue .

**Comment by agam-kashyap** [comment]
Thankyou @sk9331657.

**Comment by sk9331657** [comment]
> Thankyou @sk9331657.

Issue has been changed to #3658. It is an easy one go for it. :smile:

**Comment by agam-kashyap** [comment]
In this issue, where exactly am I supposed to add that line of code?

**Comment by agam-kashyap** [comment]
> In this issue, where exactly am I supposed to add that line of code?

There no line of code mentioned which I must remove. Some help, please?

**Comment by vikul1234** [comment]
after line 60

**Comment by SidharthBansal** [comment]
@vikul1234 please use permalink instead of temporary line numbers

**Comment by hafsasam** [comment]
Hello! If nobody is working of this issue can I claim it ?

**Comment by gauravano** [comment]
Hi @hafsasam, this issue is not required anymore, so closing this one. We would love to have hellp from you on other issues, you can see more issues at https://code.publiclab.org/#r=all. If you can't find any unclaimed issue there, feel free to comment below or in Gitter channel https://gitter.im/publiclab/publiclab. Thanks!

**Comment by gauravano** [comment]
Reason for closing this issue - https://github.com/publiclab/plots2/pull/3697#issuecomment-470455171. Thanks all for working on this.
