### ISSUE TITLE
The show more button on learn more page of infragram needs some fixes

### ISSUE THREAD

**Issue by Rishabh570** [publiclab/plots2#3654]
### Please describe the problem (or idea)
The *Show more* button below [activities table](https://publiclab.org/wiki/multispectral-imaging#Activities) has some issues,
- When you hover over it, the pointer doesn't change to the cursor
- That button is saying **show 18 more** but it still says the same thing after you've clicked over it, giving the impression that there are still 18 more things to show but when you click again it doesn't do anything.

> What did you expect to see that you didn't?

When the user hovers over it, the pointer should change to `cursor`, and *show 18 more* should change to **show less** or should disappear once *show 18 more* is clicked once.

### Please show us where to look

https://publiclab.org/wiki/multispectral-imaging#Activities

### What's your PublicLab.org username?

icode365

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment]
Are you willing to solve this issue?

**Comment by faithngetich** [comment]
@Rishabh570 can I work on this issue?

**Comment by faithngetich** [comment]
Hey, @Rishabh570 could you please advice on how I could get the page populated to see the Activities part of the page.

**Comment by Rishabh570** [comment]
@faithngetich It is related to `plots2` I guess, I not the right person to help you in that...never worked on Ruby/Rails. You can ask this in the chat, you're surely land somewhere :)

**Comment by SidharthBansal** [comment]
Hi you need to create a wiki page and then activities section in the
development environment. Hope this will help you

**Comment by jywarren** [comment]
@faithngetich if you go to https://publiclab.org/wiki/multispectral-imaging and then create a matching page on your local copy of the database, and copy in the content from the published live version, you'll be able to see it locally. I hope this helps!
