### ISSUE TITLE
A successful login redirects a user to `pulbliclab.org/dashboard` in every situation

### ISSUE THREAD

**Issue by Rishabh570** [publiclab/plots2#3656]
### Please describe the problem (or idea)

After a successful login, the user gets redirected to `https://publiclab.org/dashboard` always even when he is not supposed to...

> What happened just before the problem occurred? Or what problem could this idea solve?

I was here: https://publiclab.org/wiki/multispectral-imaging#Hardware+Mods and clicked *Add your hardware modification here* without logging in, so it said me to log-in which is fine but after I got logged-in it redirected me to *dashboard* instead of the editor page...and I had to manually head over to that page again to add hardware modification.
This can prove to be a pain for the user...

> What did you expect to see that you didn't?

After the user logs in, he/she should get redirected to the page he was trying to access just before logging in so that the user doesn't have to do the extra labour :)

### Please show us where to look

https://publiclab.org/wiki/multispectral-imaging#Hardware+Mods

### What's your PublicLab.org username?

icode365

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by sk9331657** [comment]
@Rishabh570  This is because callback from Github can return to a particular url which is authorized in Github app console.

**Comment by champagnepappi** [comment]
@Rishabh570  Can this be implemented by using friendly forwarding

**Comment by Rishabh570** [comment]
@champagnepappi I actually never worked on Ruby/Rails, so can't tell...but if you're sure about that, please go ahead :+1:

**Comment by champagnepappi** [comment]
@Rishabh570  I'm sure friendly forwarding can do the fix. Leme try it out

**Comment by Rishabh570** [comment]
sure, go ahead :+1:

**Comment by shubhscoder** [comment]
I would like to work on this issue, but I am having trouble locating this on my local machine. Is there a way I can imitate this issue on my local machine? Thanking you in advance! @gauravano

**Comment by shubhscoder** [comment]
Yeah sure ! I ll do that .

**Comment by Radhikadua123** [comment]
I found that this issue might be related to https://github.com/publiclab/plots2/issues/3384
There's already been work going on for this. If you want to help in this one, please have a look at the PR and feel free to share your views. Just wanted to make sure, we don't end up with multiple fixes for the same problem.

**Comment by jywarren** [comment]
Can you clarify if your login was using Google/Facebook/Twitter/GitHub, or
using a username/password? If the former, i think you're right that it's
the same as #3384! Thank you!

**Comment by SidharthBansal** [comment]
I think this issue is solved and we can close it.

**Comment by SidharthBansal** [comment]
Yeah, it has not resolved. I will be submitting a patch if anyone else is not working on this

**Comment by SidharthBansal** [comment]
We are having multiple links across the website where the return_to parameter is missing. 
If we will add return_to to various places, wherever the behaviour is inappropriate this will solve our problem

**Comment by SidharthBansal** [comment]
Creating the new modal and linking return_to actions in the modal might help.
Trying this approach right now.
Hope it helps

**Comment by SidharthBansal** [comment]
#4227 @kevinzluo you can work on this also.
This is highly related to the last PR you did.
These two tasks linked are apart from 10 task I was talking before.

**Comment by SidharthBansal** [comment]
@kevinzluo may I know the pr number for this issue.

**Comment by SidharthBansal** [comment]
https://codein.withgoogle.com/dashboard/tasks/5545998546894848/
@kevinzluo this is the task number. Please claim it after telling me the pr number in which the potential fix lies.

**Comment by kevinzluo** [comment]
Looks fixed on stable.publiclab.org.
