### ISSUE TITLE
Adding Space between Asking a Question And Exploring Projects Button  - FTO 

### ISSUE THREAD

**Issue by sk9331657** [publiclab/plots2#3658]
### Please describe the problem (or idea)

Adding Spaces between button Ask a Question And Exporing a Project
##Ready for New Contributor

![screenshot from 2018-10-09 12-19-22](https://user-images.githubusercontent.com/17084322/46651443-a7d7df00-cbbd-11e8-80e7-2b72ae845851.png)

### Please show us where to look

https://publiclab.org/dashboard

### What's your PublicLab.org username?

sk9331657

### Browser, version, and operating system
Chrome - 69 , Ubuntu 18

### Resources

Using Media Queries : https://www.w3schools.com/css/css_rwd_mediaqueries.asp the spacing can be adjusted dynamically by setting the margin-property of buttons.

### Steps
 
 :raising_hand_man: [x]  Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

  memo Update the file $_answer.html.erb in the $REPO repository (press the little pen Icon) and edit the line as shown below.

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by sk9331657** [comment]
@SidharthBansal   @avsingh999  Please mark this one as a fto.

**Comment by SidharthBansal** [comment]
This has been marked as a good candidate for becoming a first-timers-only issue like these, meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider reformatting or reposting it as a first-timers-only issue, and then ping @SidharthBansal to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by SidharthBansal** [comment]
Please add code links and a potential solution

**Comment by SidharthBansal** [comment]
@Agam-kashyap go ahead. You claimed this issue first.

**Comment by agam-kashyap** [comment]
thank you @SidharthBansal

**Comment by agam-kashyap** [comment]
Could someone tell me which file to look at for making the changes? 
I am new to this.
Thank you.

**Comment by SidharthBansal** [comment]
#3653 @agam-kashyap as you are working on #3653 and only a single first timer issue needs to be done by a single person. You can longer work on this issue.
After completion of that you can do ''help wanted '' issues.

**Comment by sk9331657** [comment]
@agam-kashyap  https://www.w3schools.com/css/css_rwd_mediaqueries.asp
Using Media query you can fix the margin property of buttons to add a space between them. 
Ping me in case you have any other doubts

**Comment by SidharthBansal** [comment]
@sk9331657 we can't mark it as fto until it is properly formatted with code links like #3653 is.
Please turn this into a first timer then ping us to label it.

**Comment by sk9331657** [comment]
@SidharthBansal   Can I provide starter code to @agam-kashyap ??

**Comment by SidharthBansal** [comment]
@sk9331657 a single first timer issue can be done by a single person. A person can't send multiple pull requests to different first timer issues. So @agam-kashyap can't do this issue as he is doing #3653 . 
@sk9331657  you need to implement the ftos using fto templates like we created #3653. After creation of the issue with code links you need to assist the folks to solve the issue.
Am I understandable?

**Comment by sk9331657** [comment]
@SidharthBansal  Where Can I find Fto templates ??

**Comment by agam-kashyap** [comment]
@sk9331657 @SidharthBansal I will then stick to the issue #3653. Thank you.

**Comment by sk9331657** [comment]
@agam-kashyap  Go to #3660 incase you are not able to solve other tasks. I have updated the issue with all needed resource.
