### ISSUE TITLE
Adding Space between Asking a Question And Exploring Projects Button 

### ISSUE THREAD

**Issue by sk9331657** [publiclab/plots2#3660]
Hi , this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋Solution

- [x] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

Steps to be done:

### Create a new branch and checkout using this
```sh
git branch SolvesSpacing
git checkout SolvesSpacing
```
- [x] 📝 **Update**
### Code up this
```sh
@media (max-width:269px) {
  .btn.btn-sm.btn-default
  {
    margin-top:10px;
  }
}
```
- [x] 💾 **Commit** using given syntax

### Finally Commit  and push code
```sh
git commit -am SolvesSpacing
```

- [x] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [x] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by sk9331657** [comment]
@SidharthBansal  Please add up label.

**Comment by sk9331657** [comment]
@SidharthBansal I have made this issue using fto templates. Please label it.

**Comment by sk9331657** [comment]
Thanks @avsingh999

**Comment by sal2701** [comment]
Hey, May I do this?

**Comment by SidharthBansal** [comment]
@sal2701 go ahead

**Comment by sk9331657** [comment]
@sal2701 In case you face any issues , ping @sk9331657 .

**Comment by sal2701** [comment]
@sk9331657  Hey, Does it matter where I insert the code in the file?

**Comment by sk9331657** [comment]
> @sk9331657 Hey, Does it matter where I insert the code in the file?

Yes it will because that corresponding css works for dashboard url.

**Comment by sk9331657** [comment]
@sal2701  Try to fix it by today night.

**Comment by sk9331657** [comment]
@sal2701  What is the status??

**Comment by sal2701** [comment]
@sk9331657  Some checks are happening

**Comment by sal2701** [comment]
@sk9331657  Will it be merged?

**Comment by RuthBrand** [comment]
hey! I would like to tackle this issue, may I do so?

**Comment by sk9331657** [comment]
@RuthBrand This task been already done and currently we are at last stage to merge PR for this issue. You can try another issue.
