### ISSUE TITLE
Step 4: Installation: issue with libv8

### ISSUE THREAD

**Issue by Codeama** [publiclab/plots2#3665]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

When I run this command:
` bundle install --without production mysql`

I get this error message:

> An error occurred while installing libv8 (3.16.14.19), and Bundler cannot
> continue.
> Make sure that `gem install libv8 -v '3.16.14.19' --source
> 'https://rubygems.org/'` succeeds before bundling.

> What did you expect to see that you didn't?

### Please show us where to look

The installation guide on README

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

I use Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by quinn-codes-synthesis** [comment]
Hi Codeama,

I'm unsure of the solution, but I did a search for your issue and found the following StackOverflow page: https://stackoverflow.com/questions/19673714/error-installing-libv8-error-failed-to-build-gem-native-extension/19674065

Someone's github issue with a similar problem and what they did to solve it: https://github.com/huginn/huginn/issues/1597

Or you can view the RubyGems page for libv8 here: https://rubygems.org/gems/libv8/versions/4.5.95.5

Perhaps there is something in one of those places that will help you solve your problem?

**Comment by Codeama** [comment]
Thanks for your reply, quinn-codes-synthesis. 

I've tried 1 and 3 but I'll give 2 a go and see if it works.

**Comment by quinn-codes-synthesis** [comment]
Did you have any luck? Just wanted to follow up since I saw no one else had yet. :) I had several errors while in the process of getting everything set up (soooo many errors, augh), but this wasn't one of them so I'm super curious to learn what we may have done differently!

@publiclab/solvers will probably have some suggestions if you're still stuck!

**Comment by jywarren** [comment]
Hmm, I have seen this happen more often recently but don't totally understand the cause (and perhaps there are multiple)

Here are some previous people who seem to have gotten past it:

 https://github.com/publiclab/plots2/search?q=libv8&type=Issues

May be worth asking them or looking through whether they noted how they got past it. 

Thanks for opening an issue! I hope we can provide some more guidance on this sort of thing if we can figure it out. I'm sorry youre having trouble!!

**Comment by Codeama** [comment]
> Did you have any luck? Just wanted to follow up since I saw no one else had yet. :) I had several errors while in the process of getting everything set up (soooo many errors, augh), but this wasn't one of them so I'm super curious to learn what we may have done differently!
> 
> @publiclab/solvers will probably have some suggestions if you're still stuck!

**Comment by Codeama** [comment]
Oh not! Didn't mean to close this issue. My fingers were too  fast :D

**Comment by quinn-codes-synthesis** [comment]
Yeah, try that. I was having issues with Windows as well -- it wouldn't play nice with Ruby. I was reading somewhere that Windows is, historically, not as dev-friendly as other OSes so maybe that has something to do with it?

Have you worked with Linux before? I'm brand new to it -- but that means the information is still fresh in my brain. Let me know if you hit another roadblock! I followed instructions located [at The Odin Project](https://www.theodinproject.com/courses/web-development-101/lessons/prerequisites?ref=lnav) to get Xubuntu running on a virtual machine, and it was (relatively) straightforward from there.

**Comment by Codeama** [comment]
No I'm new to Linux too and only installed it on an old PC yesterday. Glad to know there's help when I need it.

**Comment by Codeama** [comment]
Yayy! Success! It worked on a Linux system. So my conclusion is that the problem is Windows related. Thank you all for your input. Closing this now.

**Comment by jywarren** [comment]
Great, and excellent to see you checked in with the solution. I hope this
helps other folks too! Thanks!!!
