### ISSUE TITLE
Search: "query expansion" or "thesauruses" or "stemming" in full-text search

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#3666]
### Please describe the problem (or idea)

> What problem could this idea solve?

@bronwen9 and I were observing that searching for `trawl`, `trawls`, and `trawling` all yield different search results. This is actually a similar pattern seen in words like `sample`, `samples`, `sampling`.

Because we're not using a controlled vocabulary, or defining how people can tag, it's currently possible for a newcomer to search for a term, find nothing, and never know they were just a single `s` away from finding an entire research area. 

> What did you expect to see that you didn't?

We should have a way to group common variations on the term so that several closely related or common misspellings would yield the same high quality search results. 

Alternatively, we could have a way to show people what similar term to what they are currently searching for might yield more results. Perhaps at the autosuggest moment where we show "similar" terms along with a "count" of how many times they are used. 

We are willing to work on this manually to create lists of associated words or phrases that could assist the search on our site. 

### Please show us where to look

https://publiclab.org/search

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

liz, bronwen

**Comment by jywarren** [comment]
Hi! I *think* this is called "query expansion" in database terms, and there
is a feature for it here:

https://dev.mysql.com/doc/refman/5.7/en/fulltext-query-expansion.html

https://en.m.wikipedia.org/wiki/Query_expansion

And word variations can be captured via "stemming" I think?
https://en.m.wikipedia.org/wiki/Stemming

It looks like true stemming is not built in but maybe could be achieved
through blind query expansion or another technique?
https://stackoverflow.com/questions/48144890/stemming-words-in-mysql

Hmm, thesauruses were a 2010 proposal for MySQL;
https://stackoverflow.com/questions/3265396/how-to-add-synonym-dictionary-to-mysql-fulltext-search
.
https://stackoverflow.com/questions/15777420/how-to-create-a-synonym-in-mysql#15777438

**Comment by shubhscoder** [comment]
@ebarry we can use the lemmatizer  gem (https://rubygems.org/gems/lemmatizer/versions/0.1.1) to reduce a word to its lemma or dictionary form and then perform the search. This would I guess definitely solve the problem.

**Comment by jywarren** [comment]
Whoa... Lemmatizing is like stemming? Does it work in non English text? Wow!

**Comment by jywarren** [comment]
This sounds super - would you want to open a PR implementing this on our
search API methods? Perhaps if we find additional lemmatizers for other
languages we could insert them. In fact, perhaps if we are going to insert
this code in more than one place, we should make a common method called
`lemmatize()` and then in the future we could switch based on the user set
language. Amazing resource here, thank you!

**Comment by shubhscoder** [comment]
Yes sure I would like to work on this. This is super interesting . Thank
you !
