### ISSUE TITLE
Signed In notification doesn't fade away automatically

### ISSUE THREAD

**Issue by Rishabh570** [publiclab/plots2#3673]
### Please describe the problem (or idea)
After signing in to `publiclab.org`, an alert box appears telling that you're successfully Signed in, but it stays there unless you manually remove it (by clicking on the cross in alert box) or the page gets reloaded. That's not the kind of information that should be persistent in UI.

> What happened just before the problem occurred? Or what problem could this idea solve?

![screenshot from 2018-10-11 15-58-57](https://user-images.githubusercontent.com/25483260/46798310-2f188480-cd6f-11e8-8f21-98f2f917f4c1.png)

### Please show us where to look

https://publiclab.org/

### What's your PublicLab.org username?

icode365

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by Rishabh570** [comment]
[This PR](https://github.com/publiclab/plots2/pull/3662) might help :)

**Comment by champagnepappi** [comment]
Hi @Rishabh570, in #3662 I only focused on the logout but I can adjust it to automatically fade away the signed in notification/or any other notification.
Can the automatic fade be applied to that notification below the signed in notification. The one starting with "Hello welcome to public lab"

**Comment by Rishabh570** [comment]
@champagnepappi Go ahead with it if you want to, but work only on *Signed In* notification... another one contains useful information :)

**Comment by champagnepappi** [comment]
okay @Rishabh570 , on it

**Comment by cesswairimu** [comment]
This is not appearing anymore must have been fixed with another patch. Thanks all and closing this
