### ISSUE TITLE
Change "New Contributor" tag 

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#3675]
A green "New Contributor" tag shows up on some profiles. I'm not sure what makes this happen, but it doesn't seem to go away easily. For example, this profile has been active for over a year and still has that tag
https://publiclab.org/profile/dswenson

Can we update this so that the "new contributor" tag goes away after someone's first post or after a month of the profile being active? 

@publiclab/mentors want to help turn this into a well written issue?

**Comment by gauravano** [comment]
Hi @steviepubliclab, the `New Contributor` tag is added to those profiles which have one note published. But, I see dswenson's profile shows 1 research note and 3 co-authored and the tag is still there, which I agree is little misleading. Thanks!

So, what do you think would be appropriate criteria for labeling a user profile as a new contributor ?

**Comment by steviepubliclab** [comment]
Can we do this:
 "new contributor" shows up on someone's first post, but once they've posted, it's taken off their profile and doesn't end up on any subsequent posts.

**Comment by sashadev-sky** [comment]
@gauravano I am looking through issues tagged as candidates to create my first FTO issue and I saw this one has been fixed and merged already. 

Is there anything you think can be added here for a first time contributor to solve? If not, do you think I can try to format an issue out of centering the text under previews for research notes?

<img width="848" alt="screen shot 2018-11-30 at 7 08 57 am" src="https://user-images.githubusercontent.com/41092741/49290993-9f41ad80-f476-11e8-95ea-a844c71e7b6e.png">

**Comment by jywarren** [comment]
Sure! But also, are you sure this one is solved, and could you link to the PR where it was resolved? Otherwise it might still need some work; thank you!

**Comment by sashadev-sky** [comment]
@jywarren PR #3928 looks like its adding an appropriate condition onto this and related PR #3903 is still pending but not the same issue.

**Comment by gauravano** [comment]
> I just saw the issue I mention above was posted 9 hours ago #4079 but would like to claim it as an fto-candidate to rewrite if possible

@sashadev-sky please go on and try to open first-timer using the linked issue. Thanks!

**Comment by SidharthBansal** [comment]
You just need to use # symbol before the issue number and write the #issue in the comments. It will automatically get referred.

**Comment by SidharthBansal** [comment]
Thanks for creating the issue. It looks Perfect to me.

**Comment by SidharthBansal** [comment]
@jywarren @gauravano as both the prs listed in https://github.com/publiclab/plots2/issues/3675#issuecomment-443337750 are merged, can we close this issue?

**Comment by jywarren** [comment]
Yes and I made a follow-up for refining the 'new_contributor' model code,
too!

**Comment by SidharthBansal** [comment]
Great! 
Closing this now
