### ISSUE TITLE
[multiple-use] Copy ISSUE_TEMPLATE and PULL_REQUEST templates into other projects

### ISSUE THREAD

**Issue by igniteeng000** [publiclab/plots2#3685]
This issue can be used multiple times, since there are a lot of Public Lab projects that need it! Please solve it for only one repository so that others can have a chance as well.

We have a very nice default template for new issues and pull requests, with helpful information.

For example, look like this:

![issue](https://user-images.githubusercontent.com/25272573/46865509-72402980-ce3b-11e8-9961-b416cefe6b39.PNG)

We've refined the templates shown in the `plots2` project (this one!) a lot, and the customized template would be great to copy over into other Public Lab repositories. 

### Copy the files

The files live in the following locations:

* ISSUE_TEMPLATE: https://github.com/publiclab/plots2/blob/master/.github/ISSUE_TEMPLATE.md
* PULL_REQUEST_TEMPLATE: https://github.com/publiclab/plots2/blob/master/.github/PULL_REQUEST_TEMPLATE.md

### Find a place to copy to

There are several Public Lab projects that either don't have these templates (in which case you will need to make a new `.github` folder and place the files inside!) or have them, but they don't have the latest texts. See these projects:

* [ ] https://github.com/publiclab/community-toolbox/
* [ ] https://github.com/publiclab/PublicLab.Editor/
* [ ] https://github.com/publiclab/leaflet-environmental-layers/
* [ ] https://github.com/publiclab/inline-markdown-editor/
* [ ] https://github.com/publiclab/leaflet-blurred-location/
* [ ] https://github.com/publiclab/leaflet-blurred-location-display/
* [ ] https://github.com/publiclab/Leaflet.DistortableImage/
* [ ] https://github.com/publiclab/image-sequencer/
* [ ] https://github.com/publiclab/spectral-workbench/
* [ ] https://github.com/publiclab/spectral-workbench.js/
* [ ] https://github.com/publiclab/mapknitter/
* [ ] https://github.com/publiclab/webjack/
* [ ] https://github.com/publiclab/infragram/
* [ ] https://github.com/publiclab/image-builder-rpi/

Once you've done one, help us remember to check it off the list. But be aware - even it it's checked off, if the files have changed, we may need to copy over the updates!

### Make tweaks to the text

Some lines are specific to the project, and will have to be modified slightly to work in the other projects. For example, the line says `Please show us where to look` but for the [Community Toolbox project](https://github.com/publiclab/community-toolbox), it should say `https://code.publiclab.org`. Each project has a URL on its main repository page, which could be linked to.

**Comment by RuthBrand** [comment]
Hi! I'm a newbie, can I try my hand at this?

**Comment by starkblaze01** [comment]
I would like to work on this.

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.
