### ISSUE TITLE
Adding Installation Video or Screencast on Youtube for All projects - GCI Task

### ISSUE THREAD

**Issue by sk9331657** [publiclab/plots2#3686]
### Please describe the problem (or idea)

- [x] Feature Request 
 It will be quite helpful for future developer to setup the projects if installation video is provided to setup the projects . It is a multi-task issue.

@jywarren  @SidharthBansal  What are your reviews ??

**Comment by SidharthBansal** [comment]
I think this could be single user task. How can we check multiple people videos?
If we enable multiple people to work on same installation process and choose one. This would mean giving higher priority to one fellow over the rest who delivered, not very good video.

If we will choose from a set of videos to be published this will help our community.
Let's think whether it should be multiple use or single use gci issue.

**Comment by sk9331657** [comment]
@SidharthBansal  I mean to say for every project different user can form screencast.

**Comment by SidharthBansal** [comment]
So we need to have single use issue in all repos

**Comment by sk9331657** [comment]
@SidharthBansal Ok I will make for all repo.
