### ISSUE TITLE
Add link to view issues of entire organization

### ISSUE THREAD

**Issue by vishalka98** [publiclab/plots2#3688]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 *Update* the file [$index.html](https://github.com/publiclab/community-toolbox/blob/main/index.html) in the `$community-toolbox` repository (press the little pen Icon) and edit the line **45** as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
+ <p>To explore issues of entire organization. Check out <a href="https://code.publiclab.org/#r=all">Public Lab</a></p>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by vishalka98** [comment]
@jywarren @SidharthBansal  I created this fto issue please add fto label in it.

**Comment by SidharthBansal** [comment]
This issue is reserved for Google Code In Students. So, other contributors please see other issues.

**Comment by vishalka98** [comment]
can i consider this issue as my first-timer-issue? For filling the gci mentor form

**Comment by SidharthBansal** [comment]
All issues labelled with gci candidate are reserved for gci students. Please look other tasks. Sorry. You can't work on this

**Comment by jywarren** [comment]
Hi @vishalka98 - can you add a little extra information about where this line should go? 

I see you've completed one here: https://github.com/publiclab/plots2/pull/3521 -- great, and many thanks!

**Comment by vishalka98** [comment]
I have mentioned the line in the description (45).

**Comment by jywarren** [comment]
Aha! Sorry, i missed that -- `edit the line 45 as shown below.` -- Great! Thank you. 

I believe I have invited you -- did you receive it? Thanks!

**Comment by vishalka98** [comment]
I didn't get any invite yet. Please check or invite me again. Thanks in advance.

**Comment by vishalka98** [comment]
> Aha! Sorry, i missed that -- `edit the line 45 as shown below.` -- Great! Thank you.
> 
> I believe I have invited you -- did you receive it? Thanks!

I think you missed to invite also.

**Comment by vishalka98** [comment]
Thanks for inviting me for gci mentor

**Comment by meinou** [comment]
Want to compete for Outreach!

**Comment by meinou** [comment]
https://github.com/publiclab/community-toolbox/pull/88

**Comment by meinou** [comment]
#88

**Comment by meinou** [comment]
#88 request. 
I see that it was already solved, but may be I can do it as well!
Not sure if it supposed to be in master all the time, but I think it was implied in step-by-step?
Also made changes in my fork, not sure how to make pull request from there

**Comment by shriyakaneriya** [comment]
I intend to apply as an outreachy candidate. Can I contribute to the issue as well?
@meinou Have you already taken this issue? Can I help with something?
