### ISSUE TITLE
"Preview" for new posts not opening in Firefox and Chrome

### ISSUE THREAD

**Issue by bronwen9** [publiclab/plots2#3691]
I've noticed that the "preview" option hasn't been working for new wikis and research notes for at least the past few days. 

The editor seems to be working properly otherwise, but pressing the button doesn't open up a new view. 

![preview](https://user-images.githubusercontent.com/8331717/46879890-31351e80-ce15-11e8-9e17-7daf36aeb59b.gif)

**Comment by amychan331** [comment]
New to this project and testing out different pages. While trying to add new features, I also had this problem on my Firefox. For both wiki and features, the console log have the same error message: 

> TypeError: $(...)[0] is undefined, can't access property "textContent" of it

Thought I did something wrong with my installation, but I guess it is not?

**Comment by jywarren** [comment]
I think it's looking for an HTML element and not finding it! We should look
at the code that's running the preview button, possibly in the
app/assets/javascripts/ folder... Thanks! Sorry, on the run at the moment.

**Comment by amychan331** [comment]
Once I look at the HTML, it became clear. There was an inline onclick for toggle_preview(), but the click event was never passed. It seems like a simple fix. I know it is not mark as a fto-candidate, but can I do it as my first?

**Comment by jywarren** [comment]
Sure that'd be great! Good sleuthing too!
