### ISSUE TITLE
Creating Installation Screencast  of  plot2 and upload on youtube

### ISSUE THREAD

**Issue by sk9331657** [publiclab/plots2#3696]
### Create a screencast showing installation of plot2 and share the link in pr.

@SidharthBansal  @jywarren  Please mark this as gci issue.

**Comment by gauravano** [comment]
Hi @sk9331657, I really liked the idea. Please add the link to the installation steps too in the issue body so that candidate don't have to struggle much. Also, feel free to open this type of issue in other active repos of Public Lab. Thanks!

**Comment by sk9331657** [comment]
@gauravano  Thanks .

**Comment by JonathanXu1** [comment]
Hi, I'd like to work on this but it isn't available on gci. Is someone working on this task?

**Comment by gauravano** [comment]
We haven't created the instance for plots2. I would advice you to take some other task, as you have already done one such task. 

Thanks!

**Comment by JonathanXu1** [comment]
Sounds good. Thanks.

**Comment by oorjitchowdhary** [comment]
@publiclab/reviewers Can I take this up?

**Comment by jywarren** [comment]
Yes, Oorjit but you've already claimed a few, so perhaps choose just one at
a time? Thanks for your enthusiasm!!!

**Comment by jywarren** [comment]
OK! Closing this up now. Thanks!
