### ISSUE TITLE
Welcome Google Code In Students

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#3698]
Hello folks from Google Code In - I realised we don't have a main place for you all to ask questions and get support, so I wanted to say WELCOME and create this issue as a discussion zone. Please leave a comment to say hello, in part so we know who's interested in the program! @publiclab/mentors please keep an eye open for opportunities to welcome and support our Google Code In students! 👍 🎉 

## First contribution

It's so great to see that several of you have made your first contribution. 🙌 This should really help as all our contributions follow this workflow. If you haven't yet, please see this page to get started:

https://code.publiclab.org#r=all

Students are advised to do 2 ``first-timer-only`` or ``fto-candidate`` issues as their primary task at Public Labs. They are considered as ``beginner`` task on Public Lab.
 
## What next?

If you're looking for a next project, I might recommend one which starts to involve multiple files in the application code, so you can start to get a better understanding of the application's workings. Are you familiar with how a Rails application works, in terms of how the model accesses the database, the controller performs the logic, and the views display the actual web pages? If not, we can help you start to pick apart how our system works one piece at a time. 

You can find a lot of relatively small but not completely documented issues here:

https://github.com/publiclab/plots2/labels/fto-candidate

If you choose one, please leave a comment and we can do our best to help find any missing information or help guide you through the next steps. Don't hesitate to ask questions!

Larger collections of tasks can often be found under the `break-me-up` label, which you can go through to find smaller projects to "break off" and solve:

https://github.com/publiclab/plots2/labels/break-me-up

We also have many other projects on Node js and Javascript. You can see the complete collection on https://github.com/publiclab . They are also part of Google Code In Program.

## Supporting tasks

Another area you might be interested in contributing is in supporting other new people to the project. This is an often unrecognized part of a healthy collaborative project, so we've made these issues to encourage people to take part in this crucial activity. We'd love your help, and as a newcomer yourself, you know exactly what it feels like to be new, so you know how important it is to be welcoming and supportive!

https://github.com/publiclab/plots2/wiki/Google-Code-In-Tasks
These tasks are multiple use tasks

## Help wanted tasks

These are a little tougher tasks than the beginner level tasks. But don't worry @publiclab/mentors are there to help you out whenever you get stuck. All the tasks which have ``gci-candidate`` label on them but don't have ``fto-candidate`` nor ``first-timers-only`` tag are considered as ``help-wanted`` tasks.
These tasks include design, documentation, support, testing, coding, adaptability, code enhancements etc.

There are many tasks which are present on github but due to lack of time we are not able to publish them on GCI dashboard. They are a part of GCI and will be considered under evaluation. So, please search the tasks from github rather than from GCI task list for Public Labs.

Thanks and we're happy to answer questions!!

**Comment by Dayitva** [comment]
Hello from Indonesia. Hoping to have great fun participating in GCI this year.

**Comment by ho-dor** [comment]
Hello. I am a first-time contributor. Help me to get started with rails and open-source.

**Comment by avsingh999** [comment]
@ho-dor  great, welcome to you  in publiclab 
here https://code.publiclab.org/ find the issue and solve it
thanks :)

**Comment by kevinzluo** [comment]
Unfortunately the first 2 tasks are marked as beginner (GCI students are only allowed to complete 2 beginner tasks), so I and many others are currently unable to complete them. I will try to do the rest 👍 .

**Comment by SidharthBansal** [comment]
@kevinzluo thanks for reporting.
@jywarren I have created two tasks so that non beginners can also help us. They are INTENTIONALLY duplicate tasks
https://codein.withgoogle.com/dashboard/tasks/5464186466336768/
https://codein.withgoogle.com/dashboard/tasks/6406765190053888/

**Comment by SidharthBansal** [comment]
Whenever any GCI student does any of the following task the student will get credit
https://github.com/publiclab/plots2/wiki/Google-Code-In-Tasks
So, if you can't find these support tasks on GCI we will be happy to create an issue for you.

Also, there is a nice list of `fto-candidate` issues on the plots2. You can earn credits by converting it to the `first-timers-only` issue by using first timers template.
Thanks

**Comment by SidharthBansal** [comment]
``All the students are requested to get all the rewards for all the tasks which they have completed before the deadline.``
Please ``make sure to push all the changes which you are working upon to the respective repository before the deadline``. Once it will be reviewed you will get credits. If it will not be possible to give you guys credit on the GCI dashboard then also we will give you guys credit in some other way. 
Some of you are working on multiple issues and some issues are not solved completely. So, please push those changes too. ``You cannot claim the tasks after the deadline(today) but you can work on the existing prs till December 12 (17:00 UTC) ``
After December 12 (17:00 UTC) no work will be counted towards GCI.
We are doing this because you all have worked on many things. We were not able to support you guys for many of your tasks.
If doubts please ask

**Comment by SidharthBansal** [comment]
I think deadline has passed.
Well done guys.
You are all awesome.
No more tasks can be claimed. Students are requested to work on their pending tasks

**Comment by oorjitchowdhary** [comment]
Thanks a lot for the extension and initiative.. 
GCI is almost over...
So I request all the students @ValentinaTironi @JonathanXu1 @kevinzluo @dinaelhanan @CodeSarthak @thesparks @okonek to please give a good round for applause for all our mentors who have helped us in every task, every little thing and have taught extraordinary new things.. 
So this one's for the mentors, @publiclab/mentors @publiclab/reviewers !!!

🎉 🎉 💯

**Comment by SidharthBansal** [comment]
Thanks all of you

**Comment by ValentinaTironi** [comment]
Thank you too much! I was so scared when it started, I thought I couldn't do this but now we are here!! That's really amazing 💯 This is my last opportunity to participate on GCI, my 18th year is near but It was a fantastic experience! Thank you thank you all! 🎉 🎉

**Comment by dinaelhanan** [comment]
I loved it too! It was my first time writing _and_ ruby code and the help from the community was fantastic, but what was even more fantastic was working on a project that makes an impact on the environment, loved every minute!

**Comment by jywarren** [comment]
This was really epic. Hard to believe how much work and how much activity
went into it. Both mentors and students were incredible and we had some
great teamwork.

THANK YOU to everyone!!!

Look at this activity!!! https://github.com/publiclab/plots2/pulse/monthly

**Comment by JonathanXu1** [comment]
Thank you so much for this wonderful experience. This was my first time contributing to open-source and it was absolutely eye-opening. I really appreciate the mentors' swift and helpful support, as well as the friendliness of all the other collaborators.

You guys have made this an event to remember :)

**Comment by jywarren** [comment]
We'd love to thank people via the Public Lab Twitter account (https://twitter.com/publiclab) as well, or any other social media you have if you'd like to paste it in here 👍  We always want to celebrate our great community members 🎉

**Comment by gauravano** [comment]
Awesome work everyone :tada: ! We really enjoyed working with all of you and would love to continue working. I guess all of you have got the real taste of Open Source by collaborating with each other for creating something big. 

GCI might get over soon, but we would love to have you as a part of Public Lab :heart:.

**Comment by thesparks** [comment]
Thank you! This is a wonderful experience for me. I really enjoyed solving tasks and writing issue, I will never forget these days

**Comment by SidharthBansal** [comment]
*It will be great if you guys will complete your pending stuff, pending
prs before the today's deadline, so that we can consider those too. We want
all your hardwork to be considered. We don't want it to get wasted. I hope
you all will send the remaining patches at the earliest.*

**Comment by kevinzluo** [comment]
@SidharthBansal Sorry to bother, but are you referring to the deadline posted on gitter (`You all are informed that me, gaurav, sagarpreet will not be available from 9:30 IST today. Get your stuff done before it.`), or the deadline of December 12 on the GCI website?

Thank you,
Kevin Luo

**Comment by kevinzluo** [comment]
Alright, thank you for the clarification!

**Comment by SidharthBansal** [comment]
''Follow timeline on GCI dashboard strictly. We can't change the it. ''

**Comment by SidharthBansal** [comment]
Thanks for asking. You should not have doubts.

**Comment by SidharthBansal** [comment]
@jywarren as GCI deadline to claim task is over, I have removed ``gci-candidate`` labels from plots2.

``All GCI students who are working on the issues taken up``(by a comment on GitHub or claimed at GCI website, etc) ``can continue to work on them until the deadlines.``
If you have done some work, then it will be judged for sure. Each and every work will be judged. 

Many of the students will be stressed about the results. Somebody wrote yesterday, that he is stressed a lot. I will like to suggest that you should be happy instead of being stressful. You all did a very nice job this year. As we have a limited number of slots for prizes, so we cannot give you all prizes. 
For those who will win the prizes it means they are currently having great capabilities :tada: :+1: :100: Winners are suggested to keep bringing changes in themselves so that they will become better day by day. 
Those who will not win the prizes: They did a great job. They were opened to open source. They contributed to real time software. Isn't this big? You can learn from your mistakes. You learnt what git is. Git is a tough subject. You learnt rails, html, css, and a lot of stuff. You came to know how to interact with people globally. You came to know how to collaborate on a large scale. You came across the different phases of Life Cycle Model for the Software through following
Requirements: You all learnt how to raise issues and brainstorm them. Find different ways to elaborate on different ideas and notions. You to create checklists. How to break down stuff into smaller pieces.
Design and Implementation: You learnt how to apply changes to get the code work what we discussed in the requirement phase.
Testing: Many students worked at different types of test unit tests, controller tests, integration tests, etc.
Maintenance phase: You learnt how to enhance the existing code. We enhanced the existing login system to have better UI. It can't be achieved without you all. Bug fixing comes into play here. We came across so many bug fixes. Great to see your work.
Be leaders for the organisation: You created First timer issues. They were meant to teach you lessons of mentoring, collaborating etc. At Public Lab, we teach collaborators from beginner level.
I think the above plan for the GCI was completed. You all did all types of tasks. So, why are you stressed up? Learning is a continuous curve and will never reach an end. It is a starting. You will fall, then you have to rise up again. If you will never fall then how can you rise?
I hope that you all enjoyed learning all above things.
In case even if you will feel dishearted about the result, then you can try again next year. We are there to help you always. We want no one to be stressed. Be cool. Have fun. You are children and stress word should not appear within you ever.
In case you are ineligible for GCI next year, then you can think to participate into Open Source through other means, like GSoC, Outreachy, RGSoC etc. We run all the three programs. Don't ever lose hope. Continue coding and be happy.

**Comment by ValentinaTironi** [comment]
OH, It was so beautiful @SidharthBansal, Thank you for support us! I'm so stressed, nervous, and scared too. Also, I'm sick now and I can't be looking for a long time the computer because I've a headache and It hurst a lot. 
I think all of us did an awesome work here, everyone is really great :) Continue like this and you're going to get very far! It was a pleasure ❤️

**Comment by SidharthBansal** [comment]
Take a lot of rest please.

**Comment by ValentinaTironi** [comment]
Yes, I'll do that when I finish some pending here :) I almost finish, don't worry. Thank you ❤️

**Comment by jywarren** [comment]
Valentina please take care of yourself! Get well, code will wait!

Thanks Sidharth for your heartfelt sentiments. Everyone should be very
proud of themselves and of each other! 🙌🏽⚡👏🏽👏🏽👏🏽👍🏽🎉🎉🎉
