### ISSUE TITLE
Fix typos in readme of infragram

### ISSUE THREAD

**Issue by Rishabh570** [publiclab/plots2#3699]
### Please describe the problem (or idea)
*readme* file has the file extension of `.mkd` instead of `.md` and **###Developers** should be changed to **### Developers** in the [readme](https://github.com/publiclab/infragram-js/blob/master/README.mkd)

> What happened just before the problem occurred? Or what problem could this idea solve?

![screenshot from 2018-10-14 22-53-56](https://user-images.githubusercontent.com/25483260/46919923-255b7f00-d004-11e8-8c3d-9ecb16ddd294.png)

Top and bottom part of image above shows the typos to be fixed...

### Please show us where to look

https://github.com/publiclab/infragram-js

### What's your PublicLab.org username?

icode365

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by Rishabh570** [comment]
This can be a *first-timer-only* issue.

**Comment by VictorSanborn** [comment]
Added PR to fix this issue: https://github.com/publiclab/infragram-js/pull/11

**Comment by mardelvalle** [comment]
Hi @VictorSanborn by chance can I help out?

**Comment by jywarren** [comment]
Hi, it looks like @victorsanborn has fixed it! @mardelvalle please check if there's another issue available at http://code.publiclab.org. If there isn't we can make you one!

**Comment by jywarren** [comment]
Thanks @victorsanborn!!!
