### ISSUE TITLE
Subscribe button collapsing in mobile view in mailing list.

### ISSUE THREAD

**Issue by vikul1234** [publiclab/plots2#3712]
### Please describe the problem (or idea)
Subscribe button collapsing in mobile view in mailing list.
> What happened just before the problem occurred? Or what problem could this idea solve?

![subscribe](https://user-images.githubusercontent.com/22452641/47179290-56f18480-d33b-11e8-89ca-e44a4c326a92.PNG)

> What did you expect to see that you didn't?

Add some margin to the subscribe button

### Please show us where to look

https://publiclab.org/lists

### What's your PublicLab.org username?
vikul1234
> This can help us diagnose the issue: 

### Browser, version, and operating system
chrome, win10
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by vikul1234** [comment]
Please add fto-candidate

**Comment by SidharthBansal** [comment]
This issue is marked as a beginner task for GCI students

**Comment by SidharthBansal** [comment]
This has been marked as a good candidate for becoming a first-timers-only issue like these, meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider reformatting or reposting it as a first-timers-only issue, and then ping @SidharthBansal to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by SidharthBansal** [comment]
Can you please add these tasks to the gci dashboard as well?
Thanks for creating issues

**Comment by narnt** [comment]
Hi, I want to work on this issue.

**Comment by narnt** [comment]
I didn't see a problem with those buttons, but I see this:
![image](https://user-images.githubusercontent.com/32932910/47592807-23cf7680-d975-11e8-9c22-1d3ccfb8b874.png)
It must be fixed too?

**Comment by avsingh999** [comment]
@narnt  great catch 
thanks :)

**Comment by avsingh999** [comment]
@narnt  This is for gci-candidate,

**Comment by lakshyabatman** [comment]
Is this issue resolved yet? If not, can I please work on it.

**Comment by SidharthBansal** [comment]
No it has not been fixed.
Go ahead

**Comment by akoopraba4** [comment]
Could you explain what we should do?

**Comment by yash98gupta** [comment]
Hi, can i work on this issue?

**Comment by SidharthBansal** [comment]
Yeah sure

**Comment by jywarren** [comment]
Closing this up as this no longer occurs in the latest version!
