### ISSUE TITLE
Empty comment error

### ISSUE THREAD

**Issue by KauNair** [publiclab/plots2#3725]
Trying to submit an empty comment on a post just prints 'failure' above the comment box in plain text.
I believe an error alert would look better.

**Comment by jywarren** [comment]
I agree, this would be really nice! Can you post a screenshot of the exact
place, and we can help find the right lines of code to change? Thank you!

**Comment by shubhangi-chauhan** [comment]
In file : `plots2/app/controllers/comment_controller.rb` ,
change all instances of :
```
rescue CommentError
  flash[:error] = 'The comment could not be saved.'
  render plain: 'faliure'
end
```
with :
```
rescue CommentError
  flash[:error] = 'The comment could not be saved.'
  render(
    html: "<script>alert('Faliure! The comment could not be saved.')</script>".html_safe,
    layout: 'application'
  )
end
```

This should give you an error alert. :smile: 
 @KauNair @jywarren 

[ Related : #3657 ]

**Comment by KauNair** [comment]
Ah looks like a duplicate issue. @shubhangi-chauhan I guess you can help out on the original thread. I'll close this one.
