### ISSUE TITLE
a preloading page before every page loads

### ISSUE THREAD

**Issue by rockstar777** [publiclab/plots2#3734]
We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more

### Problem
Building a preloading page to enhance the behaviour of loading of html pages such that whenever a page loads a preloading page shows and on complete loading main html body shows.

## Solution
You may find solution here
http://www.marketingformavens.com/blog/create-a-page-loading-animation-with-ruby-on-rails-and-ajax

or here

https://stackoverflow.com/questions/31505506/how-to-show-page-loading-between-pages 
## Code here
https://github.com/publiclab/plots2/blob/cc2df02a63b72cca7b1129aa3044933abf614a50/app/views/layouts/application.html.erb#L57

## Thank you!

 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment]
Can you please elaborate the issue?
Sorry, I am facing difficulty in understanding. It will be very kind of you if you will walk through the issue step by step

**Comment by rockstar777** [comment]
yes in a moment
thanks

**Comment by gauravano** [comment]
@jywarren do you think we should implement this?

**Comment by jywarren** [comment]
I thought about this for some time and while I appreciate the idea, I think we should focus on other optimizations! Thank you!
