### ISSUE TITLE
Improve pagination in the blog page

### ISSUE THREAD

**Issue by avsingh999** [publiclab/plots2#3736]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem
https://publiclab.org/blog in this page pagination is not center to the body

![pagin1](https://user-images.githubusercontent.com/25536022/47317474-4573e980-d667-11e8-89b5-2c64b149b7ca.png)

### 📋Solution

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**    add  ` <div class="text-center"> </div> `
Code links….
https://github.com/publiclab/plots2/blob/a128622eb132eef4733c0067e2c6b2c1669d3042/app/views/tag/blog.html.erb#L77

for help you can see this file
https://github.com/publiclab/plots2/blob/0c0408ea8741e55af7cc96238a915bc343e70f31/app/views/questions/_questions.html.erb#L39

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by avsingh999** [comment]
@SidharthBansal  please help me to add code links because I didn't find that file
thank you :)

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by gilletted** [comment]
I'd like to claim this issue :raising_hand:

**Comment by SidharthBansal** [comment]
Go ahead

**Comment by gilletted** [comment]
Actually this issue is reserved for GCI Participants so I will leave this one for them

**Comment by codesterlife** [comment]
I would like to claim this task

**Comment by codesterlife** [comment]
I am a GCI canditate

**Comment by sagarpreet-chadha** [comment]
Yes @codesterlife ! Go head 😄 !

**Comment by codesterlife** [comment]
how can i get the webpage that needs to edited??

**Comment by avsingh999** [comment]
@codesterlife that webpage  is https://publiclab.org/blog

**Comment by vanguard07** [comment]
@codesterlife This might help - [Page where change is to be made](https://github.com/publiclab/plots2/blob/a128622eb132eef4733c0067e2c6b2c1669d3042/app/views/tag/blog.html.erb#L77)

**Comment by avsingh999** [comment]
@codesterlife  yes you have to make a pull request after editing the file

There are two ways how you can start a pull request:
1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

**Comment by vanguard07** [comment]
@codesterlife You have to create a fork of this repository, make changes in locally, push it, and then send a pull request, i.e.

- Navigate to the [repo](https://github.com/publiclab/plots2) on GitHub.
- Click on the 'Fork' button in the top right corner. GitHub will take some time to fork the repo.
- Navigate to the forked repo. Should be like `https://github.com/<your_github_username>/plots2`
- Click on the green color 'Clone or download' button
- Copy the command given in the text box. Should be like `https://github.com/<your_github_username>/plot2.git`
- Clone it on your local machine using the command `git clone https://github.com/<your_github_username>/plots2.git`
- Navigate to the cloned directory `cd plot2`
- Create a new branch using `git checkout -b <your_branch_name>`
- Change the required file locally.
- Commit your changes using `git add .` and  `git commit -m "<your_message>"`
- Push your local branch to your GitHub repo `git push --set-upstream origin <your_branch_name>`
- Go to your GitHub repo on a browser, you will see a notification asking to create a PR.
- Click on the Create Pull Request button, Give a meaningful title to the PR.
And you're done. 😄

**Comment by AyeshaSherAli** [comment]
@codesterlife have you done it? i would like to do it.

**Comment by codesterlife** [comment]
I've complete it.

**Comment by meinou** [comment]
So, this one is closed, @codesterlife ?

**Comment by shriyakaneriya** [comment]
Has this issue been closed? For I would like to work on it too. @codesterlife ?

**Comment by arungoel123456** [comment]
I would like to work on this issue

**Comment by SidharthBansal** [comment]
The issue is resolved
