### ISSUE TITLE
Remove the typo

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#3737]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

On clicking on '?' page should be opened in new tab.  Currently, it is opening on the same page. So, using `target="_blank"` on the `<a>` tag will solve the problem.

![image](https://user-images.githubusercontent.com/20972099/45542912-d79afd80-b830-11e8-95d9-4bbfb533c1cd.png)- [ ] 💾 **Commit** your changes

Correct the spelling of target in this file - https://github.com/publiclab/plots2/blob/master/app/views/editor/rich.html.erb#L172

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by gauravano** [comment]
Hi, this issue has been opened as a task on GCI dashboard. If you are Google Code-In participant and want to solve this issue, please claim it from Google Code-In [website](https://codein.withgoogle.com/organizations/public-lab/) . Thanks!

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by goonar** [comment]
Claiming to try my first non-wiki-like pull request

**Comment by HarrisonLKatz** [comment]
I would like to claim this issue, please - I would like to practice using git in the terminal for this.

**Comment by SidharthBansal** [comment]
Hi are you a GCI student? Have you claimed this task on the GCI dashboard?

**Comment by HarrisonLKatz** [comment]
I have claimed this task on GCI

**Comment by SidharthBansal** [comment]
Yeah I can see that you are a GCI candidate
We publiclabians invite to the world of open source
Yeah you can go ahead and send us a Pull Request(that is PR in short)
Best of luck

**Comment by HarrisonLKatz** [comment]
Done! Although I did ironically make a type on the commit description (type instead of typo), the actual typo is now fixed. I believe I did the PR format right - please tell me if I made a mistake there. Thank you!

**Comment by gauravano** [comment]
Hi @HarrisonLKatz, the typo on commit name is fine. Thanks for solving the issue! Also, if you want to contribute more, you can look for tasks on GCI dashboard or you can find issues at https://code.publiclab.org/#r=all . Thanks!
