### ISSUE TITLE
Title of the page should be stats rather than index

### ISSUE THREAD

**Issue by geekychaser** [publiclab/plots2#3742]
### Please describe the problem (or idea)

Title of the Contributor statistics should be stats rather than index

> What happened just before the problem occurred? Or what problem could this idea solve?

![image](https://user-images.githubusercontent.com/24489162/47340390-b34a0080-d6bb-11e8-9dce-a7577985f6ec.png)

here title should be changed to stats

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/stats

### What's your PublicLab.org username?

geekychaser

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by geekychaser** [comment]
@SidharthBansal please add gci-candidate and help-wanted labels

**Comment by SidharthBansal** [comment]
Great catch!!!

**Comment by geekychaser** [comment]
Thanks for publishing the task onto GCI website

**Comment by K-zhao** [comment]
Hello! I'm doing the task as part of GCI. I am struggling to find the HTML file name on the repository. Can you tell me where it is? Many thanks!

**Comment by itsshailesh47** [comment]
to correct this issue we need to change the entry between title tags to "stats" instead of "Index"

**Comment by kara27x** [comment]
Well, just have to change HTML's code in HEAD from `<title>&#127880; Public Lab: Index</title>` to `<title>&#127880; Public Lab: Stats</title>` then the issue's gonna be solved.

**Comment by narnt** [comment]
I'm sorry, I saw this Issue too late and already done it. My PR won't be merge? 
@K-zhao do you still work on it and still need help? [This](https://guides.rubyonrails.org/layouts_and_rendering.html) helps me to understand how it works.

**Comment by K-zhao** [comment]
@narnt I have abandoned the task.
