### ISSUE TITLE
"Assignment" posting system which contain listing of their responses

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#375]
also, responses would be hidden from the main research note feed. This is for educators. 

* Teacher would post a note tagged "assignment:sometagname" (we could make this easy with a button for teachers on some wiki page, saying "Post an assignment"
* Their note would have text normally, but end in a big button saying "Post your assignment" or something, which would go to a note post form, auto-tagging ast "assigned:sometagname" where it'd match the assignment post.
* Notes with "assigned:sometagname" would not appear in the main feeds, but only as a listing on the teacher's post.

**Comment by gretchengehrke** [comment]
I generally like this idea, but I think it would be nice to have one post show up in the main dashboard. I'm interested in how educators are using our platform and our tools, and I personally really appreciate how the dashboard consistently shows me the diversity of interests in our community, so I'd like to somehow include a single assignment post in that dashboard snapshot of diversity.

**Comment by jywarren** [comment]
Yes, sorry if that was unclear -- the original "teacher" post would show up.

**Comment by jywarren** [comment]
OK, I have this working in development, but I used a a `NOT IN` operator instead of `EXCEPT`:

````sql
  DrupalNode Load (7.8ms)  SELECT `node`.* FROM `node` INNER JOIN `node_revisions` ON `node_revisions`.`nid` = `node`.`nid` WHERE `node`.`type` = 'note' AND `node`.`sta
tus` = 1 AND (node.nid NOT IN (46,48)) ORDER BY node.nid DESC LIMIT 30 OFFSET 0
````

Which is not very efficient, but since there are not too many research notes, I think we'll be OK for now. I left inline code suggesting a switch to SQL's EXCEPT.
