### ISSUE TITLE
Expanded login pane below comments

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3756]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

When viewing a post while not logged in, you see a simple "log in to comment" message:

![image](https://user-images.githubusercontent.com/24359/47443882-4601a280-d783-11e8-8cc3-8eba3c80f5de.png)

But we have a much friendlier log in pane in the navbar:

![screenshot 2018-10-24 at 11 49 05 am](https://user-images.githubusercontent.com/24359/47443943-66316180-d783-11e8-832b-96dd55668b9b.png)

Let's use some of the same code from the navbar pane to make a friendlier area to log in (and especially quickly log in using Google/Facebook Oauth) below the comment area. 

The code for the navbar pane is here: 

https://github.com/publiclab/plots2/blob/b6e1647b929082bc54bbfa63fe4317d4ae3cf2c3/app/views/layouts/_header.html.erb#L124-L166

But in https://github.com/publiclab/plots2/issues/3755 it will be broken into a partial template, that could potentially be re-used. So this could be done after that issue!

**Comment by love-opensource** [comment]
Hi! I'm new from Outreachy.
Can I work on this?
Thanks.

**Comment by SidharthBansal** [comment]
Published on GCI dashboard

**Comment by oorjitchowdhary** [comment]
> Published on GCI dashboard

I can't find it on GCi.. Is it already solved? 
Sorry, it is getting harder to find open gci issues..

**Comment by oorjitchowdhary** [comment]
@publiclab/reviewers ??

> > Published on GCI dashboard
> 
> I can't find it on GCi.. Is it already solved?
> Sorry, it is getting harder to find open gci issues..

**Comment by jywarren** [comment]
This is not yet solved, thanks! Please keep in mind coordination with #2866 but we're mainly looking for a clearer way to log in on the same page, without needing an extra page refresh. It can use the same partial template as the top login!

Try visiting this page while not logged in (or in incognito): https://publiclab.org/notes/warren/08-30-2018/web-working-group-update-23-august-2018

![screen shot 2018-11-30 at 2 37 56 pm](https://user-images.githubusercontent.com/24359/49310916-b223a480-f4ad-11e8-8347-9ad654d79c88.png)

**Comment by jywarren** [comment]
Once you've solved this one, we can make a new task to coordinate input from #2866 to implement one of the designs from there into code!

**Comment by JonathanXu1** [comment]
@jywarren would you like something similar to this on the bottom of the page?

![login](https://user-images.githubusercontent.com/22998430/49312837-6673f980-f4b3-11e8-9f0d-bd8dfeeeac4f.png)

**Comment by jywarren** [comment]
yes! Although perhaps we could make the email one (and the login/signup
buttons that go with just that one) hidden and show an envelope icon button
in the row with the other login methods. What do you think?

**Comment by JonathanXu1** [comment]
Great, I'll work on that now. I'll make an email icon which could expand to show those stuff.

**Comment by jywarren** [comment]
Awesome! You should be able to find one in FontAwesome, which we use:
https://fontawesome.com/v4.7.0/

**Comment by JonathanXu1** [comment]
How are any of the icons from here:
![image](https://user-images.githubusercontent.com/22998430/49329504-0ed69c00-f54e-11e8-9530-b63660ba86eb.png)

**Comment by oorjitchowdhary** [comment]
Is this a beginner task on GCI? I can't find it in the non-beginners

**Comment by oorjitchowdhary** [comment]
I want to work on this.. but I can't find it in the non-beginner task list on gci.. What should I do

**Comment by jywarren** [comment]
Sorry, looks like you figure this out however -- yes, the envelope-o (the second one) looks like it would work!

**Comment by SidharthBansal** [comment]
@oorjitchowdhary please take any other issue. Someone else is working on this.

**Comment by SidharthBansal** [comment]
See the PR for conversation 
Login modal is now implemented instead of this
