### ISSUE TITLE
Inline wiki table formatting broken

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3757]
We have nice inline tables of wiki pages, like on this page: https://publiclab.org/wiki/air-sensors

![image](https://user-images.githubusercontent.com/24359/47457604-8a059f00-d7a5-11e8-9444-df1e0878453a.png)

However as you can see the table headers are a bit broken -- they don't properly label the columns. 

The file for this is here:

https://github.com/publiclab/plots2/blob/master/app/views/grids/_wikis.html.erb

It'd be great for someone to try fixing this!

**Comment by jywarren** [comment]
@mardelvalle maybe this one would be good for you?

**Comment by mardelvalle** [comment]
@jywarren Yes this looks like a good one. I will work on it then. Thanks for the help.

**Comment by jywarren** [comment]
Awesome! Thanks!!

**Comment by mardelvalle** [comment]
@jywarren This is a picture of the change I did. One thing I was thinking about doing (though it may not be in the scope of this issue) is removing the star icon. It doesn't seem to match the rest of the page's content. Thoughts? 
![screen shot 2018-10-27 at 8 39 29 am](https://user-images.githubusercontent.com/32019417/47604216-4fc61880-d9c4-11e8-8b94-abce0056d0ca.png)

**Comment by jywarren** [comment]
Hi! I think you could also just have the star and no other text for that
column; we are thinking ahead for translation issues and that'd probably
make our lives easier.

This looks great. What is the "table content" text at the top, could we
remove that too?

Thanks!!!

**Comment by mardelvalle** [comment]
Alright. Sure I can remove the "like" text.

The "table content" phrase I believe is being generated from another file as it's not part of the table. I can look into it more where it is coming from but thus far I haven't been able to locate it.

**Comment by mardelvalle** [comment]
@jywarren Hi Again! I tried telling more into the code (specifically the show.html.erb and am not able to still locate the area where the text "Table Content" is being created.

**Comment by jywarren** [comment]
Hmm, perhaps looking at a page where this is being used, we could view
source and try to find it that way?

**Comment by mardelvalle** [comment]
I was trying to do that. However, I had no luck... I was trying it on the page that you gave me but it seems the text is outside of the table. The show.html.erb is connected to the larger div that is associated with the code but doesn't seem to have any specific reference to title generation such as table content. I also tried to recreate the senario on localhost however, I did not see how to generate a similar table.

**Comment by jywarren** [comment]
Ah! look - i used the Google dev console, and found something about translation missing:

![image](https://user-images.githubusercontent.com/24359/47757639-aad66480-dc7d-11e8-9e48-6cfe6ddc804b.png)

Perhaps it's looking for a translation using the `t(...)` syntax? Could you find the text in `/config/locales/en.yml` ?

**Comment by jywarren** [comment]
And to generate a table like that, you can insert, on its own line, `[wikis:_____]` where _____ is a tag name that has been used for some wiki pages.

**Comment by jywarren** [comment]
Hope that helps!!! 👍

**Comment by mardelvalle** [comment]
The en.yml file appears to be generating date information. I don't see any references which would relate it to the table.

**Comment by mardelvalle** [comment]
Hmmm. So your thought then would be that  <%= raw t('wiki._wikis.table_content') %> is searching for content in the yml file that doesn't exist and is generating the words "table content" as a result. I don't think that  <%= raw t('wiki._wikis.table_content') %> is currently doing anything so I could just remove it from the code I think. Let me me if that  sounds about right.

**Comment by jywarren** [comment]
Yes, sorry for my slow reply here! That sounds exactly right. You may want to look in `/config/locales/...` to see if there is any translation matching `table_content` and that could be deleted too!

**Comment by mardelvalle** [comment]
Awesome! Thanks Jeffrey I will take a look there :)

**Comment by oorjitchowdhary** [comment]
@mardelvalle are you working on this issue? I was thinking of picking it up as a GCI task. If you are not; then please let me know soon!

**Comment by mardelvalle** [comment]
@oorjitchowdary thanks for asking! I have some code that I think may work but with the dev environment as is I haven't been able to test if it actually works so I have been hesitant about pushing the changes. Maybe if I  push it you could take a look to see if things check out?

**Comment by oorjitchowdhary** [comment]
@mardelvalle yeah sure.. I will checkout the code and troubleshoot it for you..

**Comment by oorjitchowdhary** [comment]
@mardelvalle Are you still working on it? As a GCi participant, I'd really like to solve this issue...
@jywarren Can I open a PR for this?

**Comment by mardelvalle** [comment]
NM I had some time this morning to do the pull. You can find it here https://github.com/publiclab/plots2/pull/4081.

**Comment by oorjitchowdhary** [comment]
@publiclab/mentors I think we can close this through #4081

**Comment by gauravano** [comment]
Closing this as resolved via #4081. If any idea in issue needs attention, please comment here or open new issue. Thanks!

**Comment by gauravano** [comment]
Closing this as resolved via #4081. If any idea in issue needs attention, please comment here or open new issue. Thanks!
