### ISSUE TITLE
Combined wiki/note grids using [node:_____] syntax, for inline grids

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3758]
This may be a bit more complex, but we'd love some help. 

We have inline grids on pages like this: https://publiclab.org/wiki/air-sensors

This means we have different ways to include inline tables of other pages, using syntax like:

`[notes:______]` or `[wikis:________]`

The templates for these are here:

https://github.com/publiclab/plots2/tree/master/app/views/grids

But sometimes you want to have both wikis and notes displayed. It'd be great to have a combined grid type for any node (see our /docs/ folder and the DATA MODEL) - with format:

`[node:_____]`

See how I've kind of done a broken version of this by just using one grid tag after the other -- showing 2 tables one after the other (a hack! Not very nice but... kind of works):

![image](https://user-images.githubusercontent.com/24359/47458076-ba9a0880-d7a6-11e8-84e5-1b0e4bebe576.png)

One issue is that notes and wikis have different columns - like the timestamp or author column. Let's try to find what overlaps and display those columns so it makes some sense -- but we can tweak this later.

**Comment by KauNair** [comment]
I'll look into this issue. :+1:

**Comment by jywarren** [comment]
Awesome, thanks!!!

**Comment by SidharthBansal** [comment]
Published on GCI dashboard

**Comment by SidharthBansal** [comment]
Yes

**Comment by jywarren** [comment]
That's OK @KauNair we would still love help refining the grid to use Bootstrap styles as per https://github.com/publiclab/plots2/pull/3970#issuecomment-439167488 -- thanks!

**Comment by ValentinaTironi** [comment]
@jywarren @SidharthBansal Hi! I have a question. Where I can see the notes and wikis grids? I looked of them but I couldn't find them. Can you give the route where the notes and wikis are displayed in grids? Thank you!

**Comment by ValentinaTironi** [comment]
Another question: Where I have to show the grids with notes and wikis? And how many I should show? All of them? Sorry, I'm trying to understand the task to resolve it

**Comment by ValentinaTironi** [comment]
In https://publiclab.org/wiki I see that: 
<img width="1280" alt="screen shot 2018-11-23 at 8 57 05 pm" src="https://user-images.githubusercontent.com/20969831/48962706-64b1af80-ef62-11e8-9334-9d3d14b8d847.png">

It's a grid. Everything is right here. But in https://publiclab.org/notes 
<img width="1280" alt="screen shot 2018-11-23 at 8 58 17 pm" src="https://user-images.githubusercontent.com/20969831/48962714-8a3eb900-ef62-11e8-83b1-553c6ba75949.png"> 
And obviously it isn't a grid so... Please can you clear this for me?

**Comment by ValentinaTironi** [comment]
@jywarren @gauravano Hi again! Sorry for be inpatient but I can't work on this task without you help! I really sorry but would be great if you can clear my doubts. Thank you so much!

**Comment by kevinzluo** [comment]
Hi @ValentinaTironi
I believe @jywarren is referring to the feature used in writing wikipages, such as [this one]( https://publiclab.org/wiki/air-sensors), where inserting `[notes:____]` expands into a table when published, as so:

![inlinegrids](https://user-images.githubusercontent.com/44309027/48990493-509db780-f0f4-11e8-9d50-908a9fb93a02.gif)


I believe the task is to create a similar feature where using `[node:_____]` will display all nodes, including notes, wikis, (and maybe questions?) in 1 grid, or to create a standard way to display all grids so the columns fit together nicely.

**Comment by ValentinaTironi** [comment]
@kevinzluo Hello! Thank you so mucho for help me! I'm gonna try this issue.

**Comment by gauravano** [comment]
Hi @ValentinaTironi sorry I am a little busy with exams :sweat_smile: , but try to answer more quickly from next time. Thanks @kevinzluo for explaining :100: .

Do you have any more doubts?

**Comment by jywarren** [comment]
Yes, thank you for stepping in @kevinzluo -- we have a holiday which was
last week and I am just catching up now. I think a combined table is
perfect, but just keep in mind how we will be able to tell notes and wikis
apart in the table. Thanks!
