### ISSUE TITLE
Improve pagination in the tags page

### ISSUE THREAD

**Issue by avsingh999** [publiclab/plots2#3760]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem
https://publiclab.org/tags in this page pagination is not center to the body

![pagi2](https://user-images.githubusercontent.com/25536022/47458732-f27d6c00-d7f7-11e8-942a-852d0b671b41.png)

### 📋Solution

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**    add  ` <div class="text-center"> </div> `
Code links….
https://github.com/publiclab/plots2/blob/cfb8b01acce023c19f5476e8b9f6743cb098e7a8/app/views/tag/index.html.erb#L54

for help you can see this file
https://github.com/publiclab/plots2/blob/0c0408ea8741e55af7cc96238a915bc343e70f31/app/views/questions/_questions.html.erb#L39

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by TheOllieB** [comment]
Can I take this one please?

**Comment by jywarren** [comment]
if you are in GCI, please go ahead!

**Comment by avsingh999** [comment]
@jywarren  this task is not published on GCI
thanks :)

**Comment by jywarren** [comment]
Ah, then ok, please go ahead!

**Comment by sashadev-sky** [comment]
@JonathanXu1 I just commented on the PR (#3863) referencing this issue to remind the user to take a look at it! I would wait a bit and then comment here again if you're still interested and they don't reclaim it

@publiclab/reviewers just wondering for myself, what is the threshold for considering a PR 'abandoned'

**Comment by SidharthBansal** [comment]
@sashadev-sky if you want you can try this one.
Please leave a comment so that we can know that you have started working on the issues

**Comment by sashadev-sky** [comment]
@SidharthBansal sorry for the delay in my reply! This is meant to be a FTO issue, but I think we might want to close and re-open it as a new issue if a GCI candidate doesn't take it by tomorrow? Not sure if that's protocol, but it got buried a bit, so let me know

**Comment by SidharthBansal** [comment]
@sashadev-sky no need to open up a separate issue. We can remove labels.
If you wish you can work on this.

**Comment by SidharthBansal** [comment]
Makes sense.
This is not ideal fto according to me too.
