### ISSUE TITLE
generate confirmation email (done) and require confirmation (not yet done)

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#378]
**Updated:** notification complete, extra confirmation remaining

Registered a new user account "liztester" to see what happens. 
## Relevant URLs

/https://publiclab.org/signup
## PublicLab.org username

liztester
## Browser, version, and operating system

Chrome Version 48.0.2564.116 (64-bit) Mac OSX 10.11.3

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by jywarren** [comment]
Hi, Liz - I don't think we have a confirmation email feature. If you'd like to request we create one, change the name of this issue and perhaps outline what a confirmation email could say. This might also help folks remember their usernames.

**Comment by ebarry** [comment]
The confirmation email should include the username that the person just created. 
Exact wording TBD, but should take into account or possible influence the messages shown to people upon their first and second log-ins to the site: 

![1st visit to site](https://cloud.githubusercontent.com/assets/161439/13405260/90293942-deeb-11e5-8e09-86733ac3cdaa.png)

![2nd visit to site](https://cloud.githubusercontent.com/assets/161439/13405263/961b1cda-deeb-11e5-89fc-b83f70310567.png)

**Comment by jywarren** [comment]
Let's start with just a welcome email! Then move on to a confirmation email.

**Comment by jywarren** [comment]
Solving in https://github.com/publiclab/plots2/issues/2241 ! This would then follow and connect with spam solutions.

**Comment by Gauravano** [comment]
Any help required here @jywarren @ebarry ? Thanks!

**Comment by jywarren** [comment]
OK, so the next thought was to require people signing up to click a "this is really me" link in the email to confirm they really own that email. I think this is probably a good idea but defer to @ebarry

**Comment by jywarren** [comment]
If they logged in using OAuth, they'd be excepted from this requirement, i guess? @SidharthBansal ?

**Comment by SidharthBansal** [comment]
@jywarren yeah we don't send any welcome emails to new users.
Can you please elaborate?
This is new issue to me.

**Comment by SidharthBansal** [comment]
You mean Email verification. Great

**Comment by jywarren** [comment]
yeah exactly!

**Comment by gauravano** [comment]
We now have welcome email and also confirmation email is in WIP. The updated checklist at https://github.com/publiclab/plots2/issues/3798. Closing this one. Thanks!

cc/ @ebarry @jywarren
