### ISSUE TITLE
Title of the page should be stats rather than index

### ISSUE THREAD

**Issue by itsshailesh47** [publiclab/plots2#3799]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
<title>Index</title> is used instead of <title>stats</title>

> What did you expect to see that you didn't?

title should be stats but it is index

### Please show us where to look
look for the entry between <title> tags in the html code of the respective page

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by narnt** [comment]
Hi, where exactly locate the problem? Maybe you can provide a screenshot to help find it? I see that title of this page is "🎈 Public Lab: a DIY environmental science community"

**Comment by quinn-codes-synthesis** [comment]
@publiclab/support -- Looks like this issue is ready to be closed. Someone's pull request was accepted and merged. (And please let me know if there is a different/additional team I should be tagging!)

**Comment by jywarren** [comment]
Aha, good catch and thanks! 👍 🙌

**Comment by jywarren** [comment]
@narnt so you know, if you add the text `closes #0000` to your pull request description (but with the issue number), it will auto-close the issue when the PR is merged. Magic! 🔮 🎉

**Comment by narnt** [comment]
@jywarren thank you, I didn't know that.
