### ISSUE TITLE
Upgrade to Bootstrap 3, FontAwesome 4

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#380]
* [x] header
* [x] icons
* [x] columns
* [x] dashboard
* [x] tag form style
* [x] tag ajax
* [x] search form
  * [x] search form autocomplete
* [x] date picker in /post
* [x] fileupload dropzones
* [x] comment form
* [x] wiki post form
* [x] /archive
* [x] profile
* [x] pagination styling (see map list page)
* [x] search
* [x] post/wiki/comment previewing markdown
* [x] tag autocomplete
* [x] list: sidebar styling
* [x] map page
* [x] error pages
* [x] front page carousel
* [x] map edit form
* [x] spam mgmt form

**Comment by jywarren** [comment]
This seems to be ready to go

**Comment by jywarren** [comment]
Errors on pages:

* [ ] autocomplete search
* [ ] https://publiclab.org/research/

**Comment by Fastie** [comment]
The comments tab on the dashboard is showing only the "working" animation. Chrome in Windows

**Comment by mathewlippincott** [comment]
Seeing some images displaying huge:
https://publiclab.org/wiki/SEM-stub-pm
![screen shot 2016-03-04 at 3 09 25 pm](https://cloud.githubusercontent.com/assets/1203280/13542902/38b48ce2-e21b-11e5-91d7-4207316276aa.png)

**Comment by Fastie** [comment]
Yes, it seems lots of research notes have images that are not scaling down appropriately when the browser window is smallerized. Chrome in Windows. e.g., images are getting cropped on the right here: https://publiclab.org/notes/cfastie/02-25-2016/kapvolution

**Comment by jywarren** [comment]
Merging in a big batch of followup fixes, including some for the newly submitted image-width and comments listing bugs. Thanks!

**Comment by Fastie** [comment]
The comments tab on the dashboard is working now, but the comments tab on profile pages is not working.

**Comment by jywarren** [comment]
Thanks, adding that to the list!

**Comment by jywarren** [comment]
* [ ] Comment header wrapping
* [x] header house icon and brand top padding fixes
* [ ] author name for maps list
* [x] wiki lead image max-width
* [ ] follow buttons on tag page
* [ ] navbars on wiki pages: https://publiclab.org/wiki/new-york-city
* [x] iframes at max-width:100%

**Comment by jywarren** [comment]
* [ ] tag wrapping

**Comment by Fastie** [comment]
The main image on these research notes is way misbehaving (overlapping the text of the note).
https://publiclab.org/notes/cfastie/11-17-2015/harry-collins-and-his-sociologist-stones
https://publiclab.org/notes/cfastie/11-08-2015/converging-on-an-1886-viewpoint
https://publiclab.org/notes/cfastie/01-16-2016/single-vs-dual-cameras

**Comment by jywarren** [comment]
Still couldn't get main images on notes working for extra tall, extra wide, mobile and desktop display... trying again though.

**Comment by mathewlippincott** [comment]
Still seeing some giant images. in comments here: 
 https://publiclab.org/notes/donblair/09-08-2015/rubba-stoppaz#c12515

![screen shot 2016-03-16 at 9 53 28 am](https://cloud.githubusercontent.com/assets/1203280/13821196/d556164c-eb5d-11e5-9278-eba42ea8eb54.png)
