### ISSUE TITLE
Title of the page should be stats rather than index 

### ISSUE THREAD

**Issue by itsshailesh47** [publiclab/plots2#3811]
Title of the page should be stats rather than index 

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?
Title of the page should be stats rather than index 

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?
itsshailesh47

> This can help us diagnose the issue: 

change entry between <title> </title> to 'stats' from 'Index'.

### Browser, version, and operating system
Google Chrome 69.0.3497.100 (Official Build) (64-bit) (cohort: Stable)
Windows 10 Pro, 64 bit

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!
title of the corresponding page needs to be stats as it contains statistical data and its not the homepage.

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders
![gci21](https://user-images.githubusercontent.com/44501762/47604302-5df05500-da15-11e8-90dc-141440836cce.JPG)
#3742 
#3168

**Comment by narnt** [comment]
Thank you for screenshot and link. I will work on this.

**Comment by gauravano** [comment]
This issue has been solved in #3820. Closing this. Thanks @itsshailesh47  and @narnt !
