### ISSUE TITLE
Error on non-existent tag page: fix and test needed

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3817]
when we go to a tag page for which there is no content tagged, we now see an error:

https://publiclab.org/tag/pi-cam

![image](https://user-images.githubusercontent.com/24359/47619871-c4c74a00-dab9-11e8-8faf-a939739bbfb5.png)

Versus https://publiclab.org/tag/pi-camera, where there is content. 

This used to show a page that said "no tagged content" or something, but now is an error. 

We should: 

1. run this locally to find the error
2. write a test for non-existent tag pages to ensure they `assert_response :success` -- a functional test! 

This is up for grabs if anyone wants it! Thanks!!!

**Comment by shubhangi-chauhan** [comment]
Is the following the expected behavior? Seems to be working fine for me.

![pi-cam](https://user-images.githubusercontent.com/36580419/47623917-7c9d3b80-db3c-11e8-98ff-969d9137da62.png)

**Comment by jywarren** [comment]
Oh, that is so strange! But maybe it's a clue -- could it affect only some users, or only admins? 

![image](https://user-images.githubusercontent.com/24359/47757511-179d2f00-dc7d-11e8-8003-4b690e97cef8.png)

Definitely still see the same thing!

**Comment by shriyakaneriya** [comment]
![image](https://user-images.githubusercontent.com/22420442/47926719-44547f00-dee7-11e8-870f-d6a590f98843.png)
For a second opinion, I am getting the same screen as @shubhangi-chauhan.

**Comment by oorjitchowdhary** [comment]
I too get the same screen as @shubhangi-chauhan and @shriyakaneriya

**Comment by dinaelhanan** [comment]
getting the same as everyone above ^^ must be an admin issue....

**Comment by jywarren** [comment]
Or maybe just solved! Anyhow, fixed!
