### ISSUE TITLE
Remove spambots from showing up as "Liking" notes

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#382]
from @Fastie 
Some spammers just "Like" notes which can then take any user to the spammer's profile where inappropriate or risky links persist. When these spam accounts are banned, the profiles should not continue to have links, which as above, could be one goal of the attack.

Spambots are distorting our ability to use statistics on "Liked" notes, we should remove this record of them. 

Also see these screenshots of just *some* of the spam profiles who have liked the most highly liked wiki page of the entire publiclab.org website: https://publiclab.org/wiki/waterchestnuts: 

![screen shot 2016-03-02 at 3 07 44 pm](https://cloud.githubusercontent.com/assets/161439/13474133/ba5c2652-e08a-11e5-908a-afc8d86278c3.png)
![screen shot 2016-03-02 at 3 09 36 pm](https://cloud.githubusercontent.com/assets/161439/13474132/ba5ab218-e08a-11e5-85f9-49f1322b8034.png)
![screen shot 2016-03-02 at 3 10 20 pm](https://cloud.githubusercontent.com/assets/161439/13474129/ba56e28c-e08a-11e5-8a4c-74011664edde.png)
![screen shot 2016-03-02 at 3 10 40 pm](https://cloud.githubusercontent.com/assets/161439/13474130/ba5706e0-e08a-11e5-9d5f-21539efe767f.png)
![screen shot 2016-03-02 at 3 11 12 pm](https://cloud.githubusercontent.com/assets/161439/13474131/ba575afa-e08a-11e5-8da3-abc59a7f8d8e.png)
![screen shot 2016-03-02 at 3 11 32 pm](https://cloud.githubusercontent.com/assets/161439/13474128/ba56ff42-e08a-11e5-8730-c023d3644984.png)
![screen shot 2016-03-02 at 3 11 50 pm](https://cloud.githubusercontent.com/assets/161439/13474134/ba5c1dc4-e08a-11e5-837f-7a00b8afb624.png)
![screen shot 2016-03-02 at 3 12 11 pm](https://cloud.githubusercontent.com/assets/161439/13474137/ba5df482-e08a-11e5-9cfa-1af3f0b722de.png)
![screen shot 2016-03-02 at 3 12 33 pm](https://cloud.githubusercontent.com/assets/161439/13474135/ba5cd61a-e08a-11e5-8dd7-330ee9d625e1.png)
![screen shot 2016-03-02 at 3 12 55 pm](https://cloud.githubusercontent.com/assets/161439/13474136/ba5defbe-e08a-11e5-909c-7ba3eb62ea02.png)
![screen shot 2016-03-02 at 3 13 32 pm](https://cloud.githubusercontent.com/assets/161439/13474138/ba604494-e08a-11e5-902b-282cbd1f42de.png)
![screen shot 2016-03-02 at 3 13 58 pm](https://cloud.githubusercontent.com/assets/161439/13474139/ba60b69a-e08a-11e5-8bd3-15b6deb0de65.png)
![screen shot 2016-03-02 at 3 14 20 pm](https://cloud.githubusercontent.com/assets/161439/13474140/ba61353e-e08a-11e5-97e8-b18a1c3e1fd7.png)
![screen shot 2016-03-02 at 3 14 40 pm](https://cloud.githubusercontent.com/assets/161439/13474142/ba659d18-e08a-11e5-9afd-e4c9c07c8572.png)
![screen shot 2016-03-02 at 3 15 01 pm](https://cloud.githubusercontent.com/assets/161439/13474144/ba668e3a-e08a-11e5-92c2-52111b6f1b44.png)
![screen shot 2016-03-02 at 3 15 22 pm](https://cloud.githubusercontent.com/assets/161439/13474143/ba65a0ba-e08a-11e5-9a90-ce55b2762d90.png)
![screen shot 2016-03-02 at 3 15 41 pm](https://cloud.githubusercontent.com/assets/161439/13474141/ba6553bc-e08a-11e5-982a-b393d84b0019.png)
![screen shot 2016-03-02 at 3 15 58 pm](https://cloud.githubusercontent.com/assets/161439/13474146/ba67e474-e08a-11e5-84b3-a26327ce976f.png)
![screen shot 2016-03-02 at 3 16 21 pm](https://cloud.githubusercontent.com/assets/161439/13474145/ba678df8-e08a-11e5-95c3-e55eb17bda4b.png)
![screen shot 2016-03-02 at 3 17 14 pm](https://cloud.githubusercontent.com/assets/161439/13474147/ba6a612c-e08a-11e5-84f6-9b8ff7b67133.png)
![screen shot 2016-03-02 at 3 17 31 pm](https://cloud.githubusercontent.com/assets/161439/13474148/ba6b8282-e08a-11e5-9e5f-5c6b84ea8c06.png)

**Comment by Fastie** [comment]
There is a lot to like about those fellows who like waterchestnuts.

Another loophole: If a spammer edits a wiki, and then hawk eyed admins revert the wiki and ban the spammer, the spammer's inappropriate edits stay in the revision history of the wiki and show up in search.
Example: https://publiclab.org/search/%20blue%20lollipop%20head

**Comment by jywarren** [comment]
This needs a `.where(status: 1)` in `def likers` here: https://github.com/publiclab/plots2/blob/master/app/models/drupal_node.rb#L111-L118

**Comment by jywarren** [comment]
This is already an issue opened by @ebarry 7 months ago; merging back into #309.
