### ISSUE TITLE
"Like" popover display issues

### ISSUE THREAD

**Issue by ujithaperera** [publiclab/plots2#383]
##What happened just before the problem occurred
When move to subscribe page and when try to follow a subscription tag by clicking follow button, top most tags are not reachable. 

##Relevant URLs
https://https://publiclab.org/subscribe

##PublicLab.org username
ujitha
(to help reproduce the issue)

##Browser, version, and operating system
safari version 9.0.3
OS X El Capitan

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by ujithaperera** [comment]
![screen shot 2016-03-03 at 12 51 02 pm](https://cloud.githubusercontent.com/assets/12997101/13488192/b41395e4-e145-11e5-8630-4d3f9d2fc83b.png)

**Comment by jywarren** [comment]
Good catch. I think this ought to be a pop-down, not a pop-left.

**Comment by ujithaperera** [comment]
Yes.Then this is not going to be a matter anymore

**Comment by jywarren** [comment]
@ebarry - thanks - what browser are you seeing this, where it's starting from too far to the right side? 

![cb52c31e-e52e-11e5-9ee7-9521b33ab086](https://cloud.githubusercontent.com/assets/24359/13611244/801f0ef6-e52f-11e5-84ae-fbeb01d94d7f.png)

**Comment by ebarry** [comment]
I'm seeing this on Chrome Version 48.0.2564.116 (64-bit). my screen resolution is 1280 and the browser window is using the whole desktop, so it doesn't seem like this is from having a small screen. 

example URL: https://publiclab.org/notes/Abhay7417/02-17-2016/question-micro-volume-spectrometer-using-arduino-and-light-detecting-resistor

![screen shot 2016-03-09 at 9 42 13 am](https://cloud.githubusercontent.com/assets/161439/13638659/49fee33a-e5db-11e5-98f1-d45e4a639654.png)

**Comment by jywarren** [comment]
I believe this is resolved! please reopen if not.
