### ISSUE TITLE
Move commenting UI code into an independent .js file

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3831]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

Our commenting code is quite long and is placed inline into the comments page. We should include it using a `<script>` tag, and move it into this folder with other JavaScript code:

https://github.com/publiclab/plots2/blob/f423719cc77948f0e2ceb27e1e0685115841a9a5/app/assets/javascripts/

Here's the segment that should be moved:

https://github.com/publiclab/plots2/blob/f423719cc77948f0e2ceb27e1e0685115841a9a5/app/views/comments/_form.html.erb#L80-L118

Once it's moved into `/app/assets/javascripts/comment.js`, we can re-include it with this line in the `_form.html.erb` template:

```ruby
  <%= javascript_include_tag "comment.js" %>
```

We'd love help with this one!

**Comment by junhouse** [comment]
@jywarren I will claim this and work on it - let me know if someone has already claimed it!

**Comment by junhouse** [comment]
@jywarren I will claim this and work on it - let me know if someone has already claimed it!

**Comment by jywarren** [comment]
Please go ahead, thanks!!!

**Comment by junhouse** [comment]
@jywarren Thanks! I just passed all the tests and updated the code. Do I need to do anything at this point? I already did the pull-request. Please let me know what to do to move forward.
