### ISSUE TITLE
consolidate views/comments and views/comment folders

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3832]
These two folders are redundant, and we should combine their content into a single folder called `comments`:

https://github.com/publiclab/plots2/tree/master/app/views/comments

https://github.com/publiclab/plots2/tree/master/app/views/comment

We will have to go through and find all references to just 'comment' and convert them to 'comments' - some will be detected by tests, and we can fix them, but with others, we will have to:

1. test out the related functionality these template files (in `/comment/`) provide, locally, and re-connect them
2. trace the commits back in [the history view](https://github.com/publiclab/plots2/commits/master/app/views/comment) to see when they were first added, and where the matching references came from

This will take some careful work to complete. I'd love to help support it!

**Comment by narnt** [comment]
I want to work on this, can I?

**Comment by jywarren** [comment]
This was completed, thank you!
