### ISSUE TITLE
Comment mention notification while note is in moderation

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#3845]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I got a notification regarding the creation of a research note and that it's waiting in a queue(I am a moderator). After some hours, I got a notification that someone mentioned me in a comment and guess what from a research note which was held for moderation.  

Here's the note - https://publiclab.org/notes/radhikadua/10-30-2018/outreachy-proposal-improve-statistics-system-for-publiclab#c21043

> What did you expect to see that you didn't?

I didn't expect to receive mention notification from a research note which is still not posted on the website. A moderator can already see the posts in moderation but for normal users, the mention is just misleading/redundant as they can't see the research note or the spam user might play with the system this way.

### Solution

Adding a check before sending email notification such that emails are not sent if note is in moderation/draft. 
Also, add test for the after applying the check.

Bonus: We can implement a system that comment mentions/notifications are sent after research note get posted.

cc @jywarren

**Comment by ebarry** [comment]
Will the author of a note or question held in moderation receive a notification if a moderator comments on their post? As a moderator, i do occasionally comment on a post while it is held in moderation in cases where i have a question about the content. I hope the author would get notification that I commented. I hope that no one mentioned in the note would get a notification. How does this sound?

**Comment by jywarren** [comment]
Yes they do get a notification!
