### ISSUE TITLE
Send verification email to the user on signup

### ISSUE THREAD

**Issue by Radhikadua123** [publiclab/plots2#3850]
Subpart of #3798

We send the welcome email to the user. That email should contain the link by which user can confirm her account.

**Comment by shubhscoder** [comment]
I would like to take this up. With whatever I have researched I think we can use the devise gem for the same. This is the link : https://rubygems.org/gems/devise/versions/4.2.0. Also it has a good number of downloads, hence can be quite reliable.

**Comment by Radhikadua123** [comment]
I'm not sure about the devise gem, but we already send welcome email to the user. So, you might want to take a look at that. But anyway, if devise can make things easier, feel free to use it.

**Comment by shubhscoder** [comment]
I need some more light on this. Should the email confirmation link be included in the welcome email itself ? Or we can send an another email for confirmation? Also do we need some other features like locking ?

**Comment by jywarren** [comment]
I think sending just one email makes sense, so it could go in the welcome
email!

**Comment by SidharthBansal** [comment]
> I think we can use the devise gem for the same.

@shubhscoder sorry, we don't use devise gem in plots2 repo. We are using a similar gem AuthLogic.

**Comment by shubhscoder** [comment]
Yeah, i realized it. Thank you 👍
