### ISSUE TITLE
Weekly Check-in for Code-In, #1

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3858]
Hi everybody :smiley: !

If you're new here, welcome, and please try some of our [first-timers-only issues](https://code.publiclab.org/#r=all). This is a check-in for recent new contributors and mentors, and across the Code-In and Outreachy groups! @publiclab/mentors 

We had some great new contributions this past week from a lot of new faces, including:

@thesparks, @faithngetich, @holykol, @mohitRJranjan, @kopecs, @Radhikadua123, @milaaraujo, @Kanikashrivastav, @LonghornRach, @kevinzluo (including some familiar faces too!)

We're SO EXCITED to have your help!

I know a lot of you have been around for these Check-ins, but they're a tradition we started this past summer, with @stefannibrasil @Gauravano @ViditChitkara @tech4GT @mridulnagpal @namangupta01 @sagarpreet-chadha @Souravirus @jywarren @MayankKashyap @siaw23 @ryzokuken @ccpandhare @icarito @steviepubliclab @ebarry @publiclab/reviewers

What is your plan for this week? 

If you have not planned yet, just leave a Hello! so that we know that you are in sync with us :arrows_clockwise: and doing well!

## Google Code-In

We're in our second week (?) of Code-In and it's been a huge amount of energy. What went well or poorly? 

One that was highlighted by @milaaraujo was that people have had trouble installing, and we need more mentors to help out there. @milaaraujo made this excellent issue to try to get GCI students to provide mutual support, and have a public conversation rather than get stuck in the GCI task in a one-on-one discussion. We can all learn from each others's mistakes! 

https://github.com/publiclab/plots2/issues/3840

## Bottlenecks

In this spirit, where can we direct more mentor energy? What's stuck? 

Also, what is going well? Let's celebrate! 

I for one have truly enjoyed seeing so much mutual support in all the issues. And great friendliness 😄 🎉 

The coming weeks will be absolutely full of code :computer: , tasks :spiral_notepad:, fun :tada: and excitement :smiley:!!

As always, if you're waiting for a review, or if you're stuck, please request help here OR leave a comment with @publiclab/mentors for some input. 🙌 

Have a GREAT week :tada:  !

Thank you !

PS - who among mentors would like to volunteer to post this next week? Please leave a comment below!

**Comment by SidharthBansal** [comment]
Hello everyone.

**Comment by SidharthBansal** [comment]
Hello everyone.
This year we are working really well in both GCI and Outreachy.

Every week we will elect one person for weekly checkins. The person has to
close the issue and open a new one for the next week.
I will like to do this job so that new mentors and students will know about
its workflow.
All gci students are requested to ask doubts if they face any difficulty on
the gitter chat.

**Comment by gauravano** [comment]
Hi everyone :smiley:,

**Improvement Scope:**  Some of the issues posted on GCI dashboard are abandoned frequently, so mentors can go an extra mile and try to simplify that task further if they observe this behaviour. 

Thank you all the @publiclab/community-reps and @publiclab/mentors for working hard for Google Code-In. Have a happy :computer: :tada:  week ahead!

**Comment by Radhikadua123** [comment]
Hi everyone,

This week I plan to finish up https://github.com/publiclab/plots2/pull/3763 and start work on https://github.com/publiclab/plots2/pull/3762 PR. Other than that, I'll be working on improving my outreachy proposal based on community reviews. 

Thanks!

**Comment by Souravirus** [comment]
Hi eceryone, nice work by everyone in this week of GCI. I am currently reviewing various tasks of GCI students. I will also be creating some easy tasks for GCI.

**Comment by avsingh999** [comment]
Hi everyone,
This week I will add issues for GCI candidate and for other users. I am currently reviewing some GCI task
thanks :)

**Comment by shivani-kapania** [comment]
Hey everyone! 
This week, I plan to assign some more issues to myself and create some more beginner tasks! 
Thanks!

**Comment by shivani-kapania** [comment]
Hey everyone!
This week I plan on reviewing some GCI tasks, assign more tasks to myself and create a few beginner tasks. 

Thanks!!

**Comment by rbhatia46** [comment]
Hi everyone!
This week I look forward to reviewing more GCI tasks, assign myself more issues and work on adding a bit more beginner issues to the GCI dashboard.

Thanks!

**Comment by jywarren** [comment]
Hi everyone! I've seen some great supportive mentoring this week. Thanks!

I think there are some issues and PRs where people have still asked a
question and haven't heard back from a mentor yet. So perhaps if you aren't
sure how to help out, you can browse through `gci-candidate` issues and see
if there people who are stuck awaiting input -- and the same with pull
requests!

Thanks again for your help!!!

**Comment by jywarren** [comment]
Hi, all! As more people need support while installing, i changed the task description to this:

```
Install and successfully setup plots2 on your local machine. Submit a screenshot of publiclab running on localhost.

Share the issues you encounter along the way and help others solve theirs.

See this issue for guidance, and to cooperate with others who are also 
working on this task: https://github.com/publiclab/plots2/issues/3840

Report back at the above issue once you succeed, to encourage others and share what worked for you!
```

and i expanded the installation issue a lot to provide more cooperation and mutual support: https://github.com/publiclab/plots2/issues/3840

Is someone interested in doing this week's Check-In? You can follow (copy! modify!) the template I created above (which i borrowed from others myself! 🙌 )

**Comment by SidharthBansal** [comment]
Let's give us this chance to new GCI mentors this time.
@publiclab/mentors just close this issue and open up a new one for the Week 2.

**Comment by geekychaser** [comment]
Hi @SidharthBansal sir, may I do it?

**Comment by SidharthBansal** [comment]
yeah sure

**Comment by geekychaser** [comment]
Moved to #3906

**Comment by geekychaser** [comment]
Can @jywarren sir or @SidharthBansal sir you please close this issue.

**Comment by SidharthBansal** [comment]
yeah sure.
You did a well job in the weekly checkouts.
Thanks @geekychaser
