### ISSUE TITLE
Change conditions for being indicated "new contributor"

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3865]
https://github.com/publiclab/plots2/blob/c7f2ce8a7ac9428bd32dc978213f3cbe08ad317e/app/models/node_tag.rb#L24

Here, `if Node.where(:uid => @uid).length === 1` determines if you're a new contributor, which is not quite right -- someone may have contributed only one node, but they might've done it two years ago, and so `new contributor` perhaps needs an additional condition.

What about **if it's their first post, AND the post is less than 1 month old**? @publiclab/community-reps ?

This code appears in 2 places (and in #3864 we may be trying to consolidate these):

https://github.com/publiclab/plots2/blob/af295d7637420c65990c7ae7ce2eca17a5f569dc/app/models/node_tag.rb#L22-L25

https://github.com/publiclab/plots2/blob/4f028aad99913a8e995246d890228cc6478497f1/app/models/user.rb#L53-L56

**Comment by narnt** [comment]
I want to work on this

**Comment by quinn-codes-synthesis** [comment]
Hi @narnt -- have you had any luck with this so far? If you want a partner or have moved on, I'd love to step in and assist you/take the reins, as appropriate. Or if the issue is solved and ready to be closed, that's helpful information, too!

Thanks!

**Comment by CoderJolly** [comment]
Surely would want to work, if any problems are faced, I would love to help @narnt...Thanks!

**Comment by narnt** [comment]
hi @quinn-codes-synthesis and @CoderJolly ! thank you for your offers of assistance! I just have had a break, but I have struggle with anoter issue: https://github.com/publiclab/plots2/issues/3707 
Can you check it out and share your ideas? Thank you!

**Comment by narnt** [comment]
Hi @jywarren , I need help with my PR!

**Comment by CoderJolly** [comment]
Pls tell @narnt, I will try to help u out

**Comment by narnt** [comment]
@CoderJolly thank you! Link to my PR is above. There are some issues: https://codeclimate.com/github/publiclab/plots2/pull/3928 How can I resolve it?
