### ISSUE TITLE
Help with Project proposal for Outreachy internship

### ISSUE THREAD

**Issue by love-opensource** [publiclab/plots2#3896]
### Please describe the problem (or idea)

As an Outreachy intern, one is required to submit a timeline of the work an intern plans to accomplish during the internship. In that regard and as a new contributor, I need some guids and help from the mentors.

> What happened just before the problem occurred? Or what problem could this idea solve?

This is a call to help for the accomplishment of the last phase of the application process.

@gauravano 

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by gauravano** [comment]
Let's start with https://github.com/publiclab/plots2/issues/3498 , as you can see on this issue that the project is already somewhat divided into parts. Now, what you have to do is design your timeline by considering these:-
1. you could further subdivide a part as per your convenience
2. At public lab we follow modularity, so we prefer the method of solving a part of project per week and then its testing and then proceeding to other part 
3. Considering buffet time so that if your strategy goes wrong you would have time to correct it

Its upto you which points you like to consider.

@jywarren @sagarpreet-chadha @SidharthBansal please add more points. Thanks!

**Comment by gauravano** [comment]
For starting, you can copy the project  parts here as given and then assign a week to each part.

**Comment by SidharthBansal** [comment]
Hi Outreachy Applicants, we will really appreciate if you can get involve the general contributors to your project by creating ``first-timers-only`` issues. You can create first timers through out the project. This will help new contributors to join the community and get involved with your project.

**Comment by love-opensource** [comment]
> Let's start with #3498 , as you can see on this issue that the project is already somewhat divided into parts. Now, what you have to do is design your timeline by considering these:-
> 
> 1. you could further subdivide a part as per your convenience
> 2. At public lab we follow modularity, so we prefer the method of solving a part of project per week and then its testing and then proceeding to other part
> 3. Considering buffet time so that if your strategy goes wrong you would have time to correct it
> 
> Its upto you which points you like to consider.
> 
> @jywarren @sagarpreet-chadha @SidharthBansal please add more points. Thanks!

Hi @gauravano thanks again for this detailed guide. Can I claim #3498 and work on it throughout or do I have to add more to it?
Thanks.

**Comment by gauravano** [comment]
Actually, the issue #3498 is the outreachy project which would be solved by
the selected intern. But, you can add the steps on solving the issue in
your application if you have given thought about implementation.

Gaurav Sachdeva

**Comment by love-opensource** [comment]
Hello, please while writing my proposals, I mistakenly submitted it while it was incomplete. Right now I can't edit it as it's under review.
Thanks.

**Comment by gauravano** [comment]
I have approved your proposal on https://publiclab.org , so you can
continue to edit it. Thanks!

**Comment by SidharthBansal** [comment]
I think we can close this issue as we have met outreachy proposal submission deadline.
