### ISSUE TITLE
header slightly covers .popover-content

### ISSUE THREAD

**Issue by narnt** [publiclab/plots2#3898]
### Please describe the problem (or idea)
I read notes, and when I clicked to an arrow, I saw that header slightly covers appeared block. It happens when a note haven't image on top. Maybe this is not urgent, but this can be improved.

![image](https://user-images.githubusercontent.com/32932910/48004078-473ab400-e121-11e8-9612-91e12eed85a9.png)

Maybe this block should be a little lower?

### Please show us where to look

Any note/question/... without main image, in example this https://publiclab.org/notes/amychan331/11-02-2018/outreachy-proposal-on-expanded-community-stats-system-by-amy-chan

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
This is a great observation! I think we might add a z-index in css to
resolve this... let's mark it as needing the code links added here!

**Comment by sashadev-sky** [comment]
I would like to work on this one.

**Comment by jywarren** [comment]
We'd love your help!

**Comment by sashadev-sky** [comment]
@jywarren changing the drop-down's z-index makes it overlap the entire nav bar (there is an additional header that says "Tools" at the top of it that is currently obscured). When you scroll, the drop down appears to scroll off the top of the window. Should I continue with this or try applying other tweaks? 

<img width="1184" alt="screen shot 2018-11-07 at 11 30 39 pm" src="https://user-images.githubusercontent.com/41092741/48178557-430cc300-e2e8-11e8-9424-d4a6a0392664.png">

**Comment by jywarren** [comment]
![image](https://user-images.githubusercontent.com/24359/48232580-10aea480-e380-11e8-9aab-b843f16281a0.png)

**Comment by jywarren** [comment]
Hmm, interesting. I think it's OK if it scrolls off the edge... or do you
think we should make it open downward? Can you upload some screenshots of
this in a few scenarios, and also double check the "mobile" view -- see how
you can use Chrome to test this?

**Comment by sashadev-sky** [comment]
Below screenshots in a pdf - please disregard page 4

[scenarios.pdf](https://github.com/publiclab/plots2/files/2567985/scenarios.pdf)

It looks the best opening sideways to me. I don't think it's a big issue it scrolls off the top. 

A fix for this might be to make the drop-down open on a hover instead of click. Then the person can't scroll or resize the window with it open. This could be a potential separate issue to open.
