### ISSUE TITLE
Refactor wikis and questions partials to use local variable

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#3915]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?  

From this https://github.com/publiclab/plots2/pull/3711 PR conversation we found that some partials are using instance variables which makes it hard for them to be rendered anywhere. 
*Its a good first-timer issue*

> What did you expect to see that you didn't?  

We would like them to use a local variable if present and default to an instance variable if not.
They should be defined as https://github.com/publiclab/plots2/blob/master/app/views/notes/_notes.html.erb#L1  and replace the instance variable with a local variable everywhere else in the file.

### Please show us where to look
The partials to be refactored are 
https://github.com/publiclab/plots2/blob/master/app/views/wiki/_wikis.html.erb 
https://github.com/publiclab/plots2/blob/master/app/views/questions/_questions.html.erb
add ` <% wikis = wikis || @wikis %> ` and replace `@wiki`  with `wiki` everywhere else in the file.

### What's your PublicLab.org username?
@cess

**Comment by gyi2521** [comment]
Can I work on this?

**Comment by gyi2521** [comment]
Thanks!

**Comment by jywarren** [comment]
@gyi2521 submitted a fix in #3847!

**Comment by SidharthBansal** [comment]
@cesswairimu can you please review #3918 and resolve the conflict. So that we can merge it?

**Comment by cesswairimu** [comment]
@SidharthBansal cool, on it.

**Comment by SidharthBansal** [comment]
Closing the issue as per your request in #3918.
Feel free to close the issues which are completed.
