### ISSUE TITLE
Explore idea for map results in search interface

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3919]
This is part of the ongoing UI work on search! @stefannibrasil @milaaraujo i thought of this while using Duckduckgo.com -- what if we did something like this? When might a map show? Could it show search results near you, or would it only show a map if it could geocode the search term?

![image](https://user-images.githubusercontent.com/24359/48164395-5ef47280-e2b0-11e8-9238-8fd3263a6a5d.png)

**Comment by milaaraujo** [comment]
Initially, I would say it only makes sense to show a map if it could geocode the search term... 🤔

**Comment by jywarren** [comment]
cool, thanks for the input! This would be pretty cool.
