### ISSUE TITLE
Combined Subscribe and login flow 

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#3931]
Combined “Subscribe and login” flow - get people subscribed to some tags as they sign up, based on tags from the pages they've been looking at
    * a route or parameters or session modification to pass some tag names in upon logging in, which then are auto-subscribed to with a notification and link to /subscriptions
Refer #3924

**Comment by SidharthBansal** [comment]
The subscription will be of some tags. So, we need to fetch some tags and get the user subscribed with those tags.
** Fetch some tags **
We need to decide on the number of tags a new user has to be subscribed upon the signup process.
I prefer less than 10. 
We have different approaches to fetch some tags. Some of them are:
1) Static behaviour: We think of some tags which everyone wants to get subscribed. It will be predecided that tag 'X' will always be subscribed to all the users. This is beneficial only if there are certain kind of tags. This will require knowledge of some domain expert who can tell which tag is a must for all the users. May be @jywarren you can tell or you know someone who can tell us.
2) Dynamic Behaviour: # of views, # of likes, # of comments, # of research notes are some of the features which decide which tag is better than other.
 Build some mathematical function which will tell us the most frequently used tags. This mathematical function will involve # of likes, views, comments, research notes etc.
By dynamic nature, I mean a lot of things. People's choice changes over time. Today all the people are interested in tag T1 related topics. But after an year tag T2 related tags are more frequently typed in. So, we need a system that will automatically change to such dynamic behaviour. We cannot hardcode it.
To address this we need to think of some numerical estimate of the time till which we need to see in past to fetch related tags.

** Subscribe to the tags **

This will require 4 OAuth & legacy forms sign up and login flow amendments. I will edit this soon.

**Comment by SidharthBansal** [comment]
@jywarren I think we will be able to subscribe tags to all the previous users also. Will create an issue for this.

**Comment by jywarren** [comment]
OK 2 things -- let's think about retroactive subscribing in a separate issue -- it's complex as we discuss in this comment (https://github.com/publiclab/plots2/issues/3932#issuecomment-437478783).

second, let's start with the most simple case here:

### Simple case 1

someone clicks `Subscribe` on a single tag when not logged in. 

They can be directed to something like `https://publiclab.org/login?subscribe=balloon-mapping`

Once login succeeds via OAuth or basic login, they are then auto-subscribed to that tag. 


### Simple case 2

We could expand Case 1 for multiple tags, like: `https://publiclab.org/login?subscribe=balloon-mapping,kite-mapping`

### Step 3

We expand on Case 2 by making buttons around the site that offer subscription to non-logged-in people like `Subscribe to these tags` meaning all tags on a given research note or wiki page...?

### Step 4

We collect up tags in javascript `localStorage` (only in the browser, so minimal privacy risk) people are browsing, rank them by how many pages tagged `balloon-mapping` someone has looked at, OR how popular those tags are overall to everyone. We then prompt people to sign up for those once they've created an account, on their dashboard. 

OR we auto-subscribe them to 3-5 and inform them of this on their dashboard, but link to Subscriptions page so they can change it immediately. 

How does all this sound?

**Comment by SidharthBansal** [comment]
This sounds great to me. I was thinking something else about this issue. Sorry, I thought that we want some tags to be subscribed as soon as anyone logs into public lab for the first time. I thought of default subscriptions as listed https://github.com/publiclab/plots2/issues/3931#issuecomment-437481861

**Comment by SidharthBansal** [comment]
So, let's start with your suggestions in https://github.com/publiclab/plots2/issues/3931#issuecomment-438876819. From step 1 to step 4.

**Comment by jywarren** [comment]
Super. Thanks, Sidharth!

**Comment by SidharthBansal** [comment]
@jywarren in reference to https://github.com/publiclab/plots2/issues/3931#issuecomment-438876819.
I guess the simple case 1 is not needed. We will prompt the login modal, then the user gets subscribed to that tag. In some prs, this work is going on. What do you say?
Regarding the second case, according to me, it is a little weird to actually have that case at the front end.
I mean a user is not logged in and is selecting tags for subscriptions. This will be very difficult for a newcomer to the public lab to deduce what these subscriptions actually mean I will rather like to show subscription prompts for multiple tags after the user logs in. I want to hide multi tag subscription(aka simple case 2 feature) from newcomers to reduce ambiguity for them. If you don't mind then please have a second thought on this case from newcomer's point of view (not from developer).

**Comment by SidharthBansal** [comment]
#4296 in progress. Right now focusing on the login project. So, can't focus much in subscriptions. Sorry. Will catch up here in a while @jywarren

**Comment by jywarren** [comment]
Great!!!

**Comment by SidharthBansal** [comment]
Any changes here in the approach @jywarren??

**Comment by jywarren** [comment]
One small addition maybe -- we could have a simple text link at the bottom of all tag lists, like:

`balloon-mapping` `kite-mapping` `water-quality` [Follow all topics]()

that would prompt subscription but with the `return_to` of the multiple tag subscription URL; that would be perhaps the simplest UI for the above, and a good basic example, before making all the check-boxes. Then we can move on to more complex UIs like the popover, or the one driven from local tracking. How does that sound, to start with possibly the most basic case? 

This all sounds fantastic. You're doing a tremendous job and also coordinating a big group to do it collaboratively! You and all the others involved should feel very proud of this 👍 🤝 🙌

**Comment by SidharthBansal** [comment]
I am trying my level best giving 8-9 hours daily. We will need an extension for sure. I don't want I will do things in a hurry. I want to make the system such that maintenance will be least as in case of OAuth and Modals.
I will try to again increase to 12-14 hrs a day if possible.

**Comment by SidharthBansal** [comment]
>>One small addition maybe -- we could have a simple text link at the bottom of all tag lists, like:
`balloon-mapping` `kite-mapping` `water-quality` `Follow all topics`
that would prompt subscription but with the return_to of the multiple tag subscription URL; that would be perhaps the simplest UI for the above, and a good basic example, before making all the check-boxes. Then we can move on to more complex UIs like the popover, or the one driven from local tracking. How does that sound, to start with possibly the most basic case?

Currently doing this!

**Comment by SidharthBansal** [comment]
Is there any similar route implemented in the repo so that I can look upon? I am doing these query parameters in the routes for the first time.

**Comment by SidharthBansal** [comment]
`Follow Post` route implemented in #4340. I used strings instead of queries. This solution also gives same output. Please review it. Thanks
