### ISSUE TITLE
Errors Countered "Command 'Yarn' not found" & "Cannot connect to http://localhost:3000/"

### ISSUE THREAD

**Issue by Error-No404** [publiclab/plots2#3946]
I tried all the steps and encountered 2 problems but I fixed them up.
The 2 problems were-
1) Command 'Yarn' not found (while doing yarn install) -
- To fix install the Yarn application from official website. 
- Close Bash and open again.
- The issue is fixed.
2)  Cannot connect to http://localhost:3000/
- I found 2 errors in this.
- A command helped me solve this problem `rails server -b127.0.0.1`
- The website can now be accessed

![screenshot_4](https://user-images.githubusercontent.com/44896455/48314344-49ec4c00-e5ee-11e8-8722-1675d90fd0cd.png)

**Comment by gauravano** [comment]
Hi @Error-No404 thanks for letting us know and as you have submitted your GCI task successfully, I guess your issue is resolved. How about closing this issue now?

**Comment by Error-No404** [comment]
> Hi, sorry you had issues -- please see #3840 to connect with others working on installation issues. Was `npm install -g yarn` missing from the instructions you were following, and where might we have forgotten to put that? Thanks for your help!

https://github.com/publiclab/plots2#installation

**Comment by Error-No404** [comment]
> Hi, sorry you had issues -- please see #3840 to connect with others working on installation issues. Was `npm install -g yarn` missing from the instructions you were following, and where might we have forgotten to put that? Thanks for your help!

https://github.com/publiclab/plots2#installation
