### ISSUE TITLE
Choose a platform for organizing translation efforts

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#395]
As i write this, we have individuals who are ready to translate publiclab.org into Spanish, French, and Chinese, perhaps other languages as well. Although these efforts are waiting on internationalization https://github.com/publiclab/plots2/issues/393, we can still begin to organize our strategy and choose a platform. We could use github, or a dedicated localization platform like https://crowdin.com/.

**Comment by ebarry** [comment]
Hi @jiteshjha as your work has progressed, do you have any input on ways to organize translation efforts?

**Comment by jiteshjha** [comment]
Hello!

I have two ideas for organizing translation efforts. First -- we can
utilize Github Pull Request system to allow anyone to submit translations.
This method has a downside -- The interested community member must be
familiar with Github. Second -- We can create a series of spreadsheet with
the website content on it, with each website text against various columns
for different languages. This way, community members can submit their
translations and correct the existing ones, and I think almost everyone
will be familiar with spreadsheets, as they're not arduous to work with.

Any suggestions?

-- Thanks!

**Comment by jiteshjha** [comment]
Hello!

Transifex is a web-based translation platform, which offers free license to
open source organizations -- and it's easy to use and automate! I have
created a publiclab website translation project and sent invitations for
admin role. Please let me know if you haven't received any invite mail. I
have added only header translation file to check the workflow on the
website, I'll add more files in a couple of day.

Looks interesting!

Best,
Jitesh

**Comment by jywarren** [comment]
Completed! See https://publiclab.org/wiki/translation
