### ISSUE TITLE
New idea Suggestion [Google Code-In]

### ISSUE THREAD

**Issue by Noorbano15** [publiclab/plots2#3954]
Suggesting new idea for solving https://github.com/publiclab/plots2/issues/3460

Web-based tools for collecting, analyzing, and sharing data from a DIY spectrometer. These tools should be there to make our work easier. We can add nice pictures for children. These type of things will attract the teenagers and these days there's a lot of power in the hands of teenagers. And I pray that one day it will be so famous that everyone in the world will be using it. 

@jywarren @publiclab/community-reps

**Comment by jywarren** [comment]
Hi! We have web-based software available, please take a look at https://spectralworkbench.org -- would this work?

Also, we are porting it to be usable with the Raspberry Pi! https://github.com/publiclab/spectral-workbench.js/issues/56

I hope this is helpful!

**Comment by jywarren** [comment]
And great idea!

**Comment by gauravano** [comment]
@jywarren this issue was opened for GCI task - https://github.com/publiclab/plots2/issues/3460 . Should I approve the task?

**Comment by Noorbano15** [comment]
Plz approve this task😃

**Comment by jywarren** [comment]
Yes please! Thanks both of you :-)
