### ISSUE TITLE
Web-based tools for collecting, analyzing, and sharing data from a DIY spectrometer. These tools should be there to make our work easier. We can add nice pictures for children. These type of things will attract the teenagers and these days there's a lot of power in the hands of teenagers. And I pray that one day it will be so famous that everyone in the world will be using it.

### ISSUE THREAD

**Issue by Noorbano15** [publiclab/plots2#3975]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by shubhscoder** [comment]
@Noorbano15 I would suggest that you keep the title short. You can add the description you want , in the section provided to describe the problem. Thanking in you in advance!

**Comment by gauravano** [comment]
Closing this issue as opened again. Thanks!
