### ISSUE TITLE
Two pagination at the botton of the  search page

### ISSUE THREAD

**Issue by gptshubham595** [publiclab/plots2#3976]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## Problem: It can be found here i have just searched anything random
https://publiclab.org/search/hello

Here is a screenshot showing this:
![search_error](https://user-images.githubusercontent.com/24877361/48564821-28a49c00-e91d-11e8-8dfc-0961759ea876.jpg)

##Solution
remove this line once
https://github.com/publiclab/plots2/blob/9a2e82eba9352e074d1527407b08f22c4920350e/app/views/search/tags.html.erb#L26

<%= will_paginate @tags, :renderer => BootstrapPagination::Rails unless @unpaginated %>

as this is repeated 

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by ibrahimelbanna** [comment]
Can I work on this?

**Comment by gauravano** [comment]
Sure @ibrahimelbanna!

**Comment by ICEBERG98** [comment]
I want to work on this any too. Anything I can do?

**Comment by akoopraba4** [comment]
I would like to work on this issue.

**Comment by akoopraba4** [comment]
On opening it,I can find no repetition.Is this issue solved?

**Comment by imsankalp** [comment]
If this issue is not taken by anyone, I would like to solve it.

**Comment by SidharthBansal** [comment]
Are you @ibrahimelbanna working on this? if not please tell. If yes please open up a pull request.

**Comment by Akankshabhasin** [comment]
Are there more issues to solve for complete beginners?

**Comment by sashadev-sky** [comment]
@publiclab/reviewers I believe this issue was resolved 4 days ago by PR #4089 and can be closed

**Comment by SidharthBansal** [comment]
@sashadev-sky I could not see the error reported in the issue on the main production website. So I think we can close this.
