### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by Noorbano15** [publiclab/plots2#3977]
Web-based tools for collecting, analyzing, and sharing data from a DIY spectrometer. These tools should be there to make our work easier. We can add nice pictures for children. These type of things will attract the teenagers and these days there's a lot of power in the hands of teenagers. And I pray that one day it will be so famous that everyone in the world will be using it.

**Comment by oorjitchowdhary** [comment]
@SidharthBansal @jywarren Can we close this issue? Isn't this redundant

**Comment by gauravano** [comment]
Thanks @oorjitchowdhary! @jywarren feel free to reopen if you see any discussion point. Thanks!
