### ISSUE TITLE
very small bug: can't close the popup-context menu on research notes

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#398]
The arrow that pops-up to award a barnstar or see who else liked the note is hidden under the popup menu itself, such that it cannot be closed again once opened. Unless reloading the page. 

![screen shot 2016-03-08 at 1 06 55 pm](https://cloud.githubusercontent.com/assets/161439/13611093/c86a56f8-e52e-11e5-992c-383e5ebe2777.png)

![screen shot 2016-03-08 at 1 07 02 pm](https://cloud.githubusercontent.com/assets/161439/13611095/cb52c31e-e52e-11e5-9ee7-9521b33ab086.png)

Example URL, but this is happening on all research notes: https://publiclab.org/notes/warren/03-04-2016/bostonjs-talks-focused-on-welcoming-new-coding-contributors

**Comment by jywarren** [comment]
Ah, this is related to #383 -- merging, thanks!
