### ISSUE TITLE
Account creation failing in several ways

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#3982]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

For what may be several reasons, I cannot register a new account on the website. 

I am currently located in China, but I'm using an international hotspot that is not behind the Great Firewall (instead is registered in UK) and currently has 4G speed. I attempted to create a new account from two browsers, Chrome Incognito and Firefox. 

<img width="900" alt="screen shot 2018-11-16 at 11 50 28 am" src="https://user-images.githubusercontent.com/161439/48597042-a658be00-e996-11e8-8193-a00861455b8f.png">

<img width="709" alt="screen shot 2018-11-16 at 11 50 48 am" src="https://user-images.githubusercontent.com/161439/48596987-6265b900-e996-11e8-9270-5f25daed85f4.png">

This bug is also being experienced by @shanlter using a VPN registered in the United States in Chrome browser. 

<img width="1280" alt="2018-11-16 11 44 40" src="https://user-images.githubusercontent.com/161439/48596933-16b30f80-e996-11e8-8bf2-64bd5b34ff2e.png">

<img width="784" alt="2018-11-16 11 49 06" src="https://user-images.githubusercontent.com/161439/48596969-4bbf6200-e996-11e8-9b37-731135a73b64.png">

### Related Issue
I have a related report to make: When *not* using a VPN, just using regular Chinese internet, the Google RECAPTCHA API cannot load, and this prevents people from completing account creation 

### Other information
I checked publiclab.org/stats to see if new account creation was totally blocked, and it seems like it is not: 189 new registrations in the past day. 

<img width="521" alt="screen shot 2018-11-16 at 11 41 46 am" src="https://user-images.githubusercontent.com/161439/48597150-4282c500-e997-11e8-88ee-9611eb7d4033.png">

> What did you expect to see that you didn't?

I expected to be able to create a new account on the website, and to be able to recommend this workflow to the 40 new people i will be workshopping with tomorrow. 

### Please show us where to look

https://publiclab.org/signup
https://publiclab.org/stats/range/14-11-2018/15-11-2018/
https://github.com/publiclab/plots2/issues/1570 -- github showed this issue to me as "related"

### What's your PublicLab.org username? 
liz

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

Chrome Incognito and Firefox (updated today) on MacOS

**Comment by jywarren** [comment]
tried in the US i got same, error log: 

```
[5ad9631f-74d8-49df-aea7-5cce91a55e59] Processing by UsersController#create as HTML
[5ad9631f-74d8-49df-aea7-5cce91a55e59]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"6IMvlrmjj0UzqOy4Z6Jl54fkZyXFdd7gtyZmAUJppng9pXlKnDxLA/r5dpPBA
GBVaWdYzkwLR9zui2QrGdjUFw==", "user"=>{"username"=>"jywarren-22", "email"=>"j.y.warren@gmail.com", "password"=>"[FILTERED]", "password_confirmation"=>"
[FILTERED]", "bio"=>""}, "id"=>"jywarren-22", "g-recaptcha-response"=>"03ADlfD1_HOld71sJtFwQziOx6ndud_o0JYn2iiEas2Z15mjW7BeJQovABGZmMQ-FyMsxNGSzfClE-nd
n11c91E-QNzOY1HkpXj8NnUNvOGZS5yGu7dTE3BwBnkbToyAKyA1Sh43rsquZ4-yMhQKuzjP_z4tOiDeploxP4T0gkgbylTX4PLnWP2BuDiqqKxiRhPtIMCPz6HxirySWaUP5kTM7p9vMrIWvohSolL
XTfH8qI9F8dWD4bkAoIOzWInUniU7kVqWdpg7sl_DEX7bDfMCioLG294qQRQA"}
[5ad9631f-74d8-49df-aea7-5cce91a55e59]   Rendering welcome_mailer/notify_newcomer.html.erb
[5ad9631f-74d8-49df-aea7-5cce91a55e59]   Rendered welcome_mailer/notify_newcomer.html.erb (4.8ms)
[5ad9631f-74d8-49df-aea7-5cce91a55e59] Sent mail to j.y.warren@gmail.com (101.9ms)
[5ad9631f-74d8-49df-aea7-5cce91a55e59] Completed 500 Internal Server Error in 439ms (ActiveRecord: 213.9ms)
[5ad9631f-74d8-49df-aea7-5cce91a55e59]   
[5ad9631f-74d8-49df-aea7-5cce91a55e59] Net::SMTPFatalError (550 relay not permitted
):
[5ad9631f-74d8-49df-aea7-5cce91a55e59]   
[5ad9631f-74d8-49df-aea7-5cce91a55e59] app/controllers/users_controller.rb:23:in `create'
```

**Comment by icarito** [comment]
Hi Liz!
Thanks for your detailed report!
Looking at the configuration and logs we discovered our mail gateway was not recognizing our web container to relay email for because an upgrade seems to have changed its IP address.
I missed finishing https://github.com/publiclab/plots2/pull/3330 which should give us warning if this ever happens again. Sorry for the inconvenience and have a great workshop tomorrow!

**Comment by jywarren** [comment]
ohhhhh i had missed this additional issue from the middle of this one, thank you @icarito --

> Related Issue: I have a related report to make: When not using a VPN, just using regular Chinese internet, the Google RECAPTCHA API cannot load, and this prevents people from completing account creation

Making a separate issue for this so we don't forget it:

**Comment by jywarren** [comment]
oops its above you see it
