### ISSUE TITLE
spam tracker 3000

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#4]
In order to determine how much spam is being received at any time, and how much is being handled by the community (admin/moderators), we should have some way to track historical spam even after it is deleted.

This might be as simple as something like a table that has a date that a node id and revision id were deleted, and possibly cache some information such as when the spam was created, who created it, and the last IP address of the creator. Usually this would be done relationally, but since the user, node, and revision might be deleted, this table should store copies of information and not pointers.

**Comment by ryzokuken** [comment]
@yukiisbored What's the status on this?

**Comment by yukiisbored** [comment]
@ryzokuken ah, I think I added that by mistake.

**Comment by yukiisbored** [comment]
We can ban known spammer/scammer/proxy IPs, I think there's an API for those.

**Comment by ryzokuken** [comment]
@jywarren Are we planning on working on this?

**Comment by jywarren** [comment]
I think that with the new OAuth work https://github.com/publiclab/plots2/milestone/18 , there are lots of new spam accounts being made, but none of them are successfully getting spam posts through...

**Comment by btbonval** [comment]
Hi everyone. I had not seen any of the questions or updates to this ticket until recently. My email seems to be 50/50 spam or archived folder. I see a bunch of questions from over a year ago. For those:

The original intent of this ticket was to have shared notes on the process and queries used to find and eliminate spam user accounts. There was never an end goal for this ticket.

I think it should be fine to close this out. The process and queries will still be available in the ticket after it is closed.

**Comment by jywarren** [comment]
Hi, @btbonval -- good to hear from you! Miss you!

Thanks, and we have a good overall spam issue now at #974 for what it's worth. I guess I'll close this since there's not a specific to-do or end goal, and we can trace back to it from #974. Cool!

**Comment by ebarry** [comment]
I will never forget Issue #4
We had a good run over these years <3

Spam Tracker 3000 will live on in our collective meme-ories, and hopefully
meme-orialized on publiclab.org/spam

--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net
