### ISSUE TITLE
Weekly Check-in for Google Code-In #3

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#4009]
Hi everybody :smiley: !

If you're new here, welcome, and please try some of our [first-timers-only issues](https://code.publiclab.org/#r=all). This is a check-in for recent new contributors and mentors, and across the Code-In and Outreachy groups! @publiclab/mentors 

We're SO EXCITED to have you as part of Public Lab and Google Code-In!

**What is your plan for this week?** 
I will be reviewing PRs, GCI tasks and opening new issues on GCI dashboard.

If you have not planned yet, just leave a Hello! so that we know that you are in sync with us :arrows_clockwise: and doing well!

## Google Code-In

We're in our fifth week (?) of Code-In and it's been a huge amount of energy. What went well or poorly? 

## Bottlenecks
It is noticed that some of the GCI participants are attempting multiple tasks at a time, by opening a PR for a task without claiming it from GCI dashboard, which is wrong. As per rules, a participant can work on a single task at a time which they have claimed. So, keep your eyes open so that we could make this journey fair for all. 
 
**In this spirit, where can we direct more mentor energy? What's stuck?** 
We are running low on non-beginner GCI tasks, so try to open as many tasks as possible. 

**Also, what is going well? Let's celebrate!**
Tasks are completing quickly that shows that we are able to help students better and not only that many long stuck issues are solved by GCI participants, which is really awesome.

The coming weeks will be absolutely full of code :computer: , tasks :spiral_notepad:, fun :tada: and excitement :smiley: and exams :books: :sweat_smile: . All the best for your exams !!

## Outreachy 
We received 15 amazing proposals for Winter round of Outreachy and we are glad to annonce that **Ceciliah Wairimu**(@cesswairimu) has been selected as an Outreachy intern for the Public Lab. :tada: :star2: :sparkles:.

We really appreciate efforts of all the people( @Radhikadua123 @faithngetich @quinn-codes-synthesis @amychan331 @mardelvalle @narnt @hydro-m @love-opensource @romanrodriguez @shubhangi-chauhan) who considered PublicLab's project for the Outreachy application. The contribution and support you have given to our project is really valuable and we are really thankful. All the proposals were really awesome,  but unfortunately we could select only a single intern. Wish there were space for every applicant but hopefully those of you who weren't able to be selected have gotten a good taste of work in open source. You are most welcome to apply for the upcoming rounds of Outreachy, Google Summer of Code and RGSoC. 
 

As always, if you're waiting for a review, or if you're stuck, please request help here OR leave a comment with @publiclab/mentors for some input. 🙌 

Have a GREAT week :tada:  !

Thank you !

PS - who among mentors would like to volunteer to post this next week? Please leave a comment below!

**Comment by SidharthBansal** [comment]
Hi everyone,
I observed that we need some resolution techniques to gain speed and quickly start with Outreachy and start preparing results for GCI after reviewing the PRS.
It will be great if you all can provide feedback on this.
Like I have added time for all beginner level GCI tasks as 5 days and other GCI tasks as 7 days. This will give us some time for PR backlog reviews.

**Comment by jywarren** [comment]
Yes, perhaps our GCI tasks pointing at support issues to help review and resolve PRs could be improved, expanded, or made into more GCI tasks in themselves? 

https://github.com/publiclab/plots2/labels/support

**Comment by okonek** [comment]
Hi there, I am a CGI contributor. I just wanted to say what i think. I took part in this competition a year ago but I couldn't find any organization fitting me. This year I found Public Lab and the tasks and how much the mentors help is great. I am looking forward to choose your organization in the next year and maybe stay with the community even after the contest ends. 
Thanks, John.

**Comment by jywarren** [comment]
i'm so glad to hear it! We've done GSoC for several years and it's our
first GCI of this size -- so we're looking to get better at managing how
much activity there is! But it's great to hear good feedback, thank you!

**Comment by CoderJolly** [comment]
> I made a big list of small issues that would make good stand-alone issues and tasks for GCI:
> 
> [publiclab/image-sequencer#487](https://github.com/publiclab/image-sequencer/issues/487)
> 
> I would love some help from other mentors turning these into GCI tasks, even as drafts!

Can only mentors offer help ?

**Comment by CodeSarthak** [comment]
Waiting for more tasks to be added on GCI. @publiclab/guides @jywarren

**Comment by jywarren** [comment]
Just wanted to note @aashna27 and @oorjitchowdhary for their great mentoring, along with lots of others who are pitching in to help others get their tasks done!

**Comment by jywarren** [comment]
Hi, just a couple updates - the task i created for breaking out new tasks got solved very quickly, generating a range of new tasks at Image Sequencer: https://codein.withgoogle.com/dashboard/task-instances/5686896156999680/, https://github.com/publiclab/image-sequencer/issues

based out of https://github.com/publiclab/image-sequencer/issues/487

that worked super well for generating new issues! Let's do more of that! There are still a few instances left of that "break out new issues" task :-) 👍
