### ISSUE TITLE
Root url for wiki pages fails to load

### ISSUE THREAD

**Issue by ananyo2012** [publiclab/plots2#401]
##What happened just before the problem occurred
When trying to go to the /about page or any root wiki page from localhost:3000 the page fails to load
![screenshot from 2016-03-09 12 04 42](https://cloud.githubusercontent.com/assets/10486343/13627263/3f78eb72-e5ef-11e5-9a74-e14e190995db.png)

##Relevant URLs

localhost:3000/about

##PublicLab.org username
ananyo2012
(to help reproduce the issue)

##Browser, version, and operating system
Google Chrome 47.0.2526.106 (64 bit)
OS: Ubuntu 14.04 LTS

A simple change in root method in wiki_controller is solving this problem. Should i add a commit for it?

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by jywarren** [comment]
Hi, I believe this is not a bug - on closer look, the correct address for the about page in the seed data is http://localhost:3000/wiki/about -- I'm aware that the header shows http://localhost:3000/about, but unless you want to correct the seed data at https://github.com/publiclab/plots2/blob/master/db/seeds.rb#L30, this is just a mismatch between seed data and production data which does not result in a bug for a user of the live site. Thanks!
