### ISSUE TITLE
Add "follow us on facebook" and "follow us on twitter" buttons to user dashboard

### ISSUE THREAD

**Issue by shubhscoder** [publiclab/plots2#4011]
### Please describe the problem (or idea)

I think it would be good idea to add "follow us on facebook" and "follow us on twitter" buttons on the dashboard page. So if a person follows public lab on facebook then all his contacts would get to know about public labs and probably that would increase participation for public labs.

**Comment by shubhscoder** [comment]
So the image would look something like shown below. Ignore the sizes as of now, that would be fixed. So the icons would come in right partial of the dashboard page, just below the tags 
![image 1](https://user-images.githubusercontent.com/18489285/48855765-c2b38b00-edda-11e8-91d6-6f0e91c49bef.png)

**Comment by conkytom** [comment]
I'd like to create a working example of this.

**Comment by conkytom** [comment]
Added buttons to the sidebar, these buttons should show up under the topics in the side like in the sample image.  Don't know if there's a more ideal placement for them. I was thinking maybe in the footer, but that might make them less visible.
