### ISSUE TITLE
"Wiki" filter is displayed only in mobile view at /research

### ISSUE THREAD

**Issue by tsparksh** [publiclab/plots2#4026]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

"Wiki" filter is displayed only in mobile view

![deepin-screen-recorder_select area_20181122184239](https://user-images.githubusercontent.com/17945250/48901062-cf8db880-ee86-11e8-8ebe-bca01a6fb11c.gif)

### Proposed additions

Add filter in non-mobile mode too

### Please show us where to look

https://publiclab.org/research

### What's your PublicLab.org username?

catimail123

### Browser, version, and operating system

Chrome, Deepin

****

**Comment by CodeSarthak** [comment]
@thesparks That's a good catch! 👍 We need to look into this.

**Comment by jywarren** [comment]
Thanks so much! Actually this was originally a feature -- we do this because in wider view it is supposed to be displayed in the sidebar. But now perhaps we can remove that code. But please be careful -- this is quiet complex code -- see #4042!
