### ISSUE TITLE
Questions page Comment and Answer numbers not changing correctly

### ISSUE THREAD

**Issue by kevinzluo** [publiclab/plots2#4034]
### Please describe the problem (or idea)

What did you expect to see that you didn't?

Deleting a comment to an answer decreases the answer count:
![errordeletingcommenttoanswer](https://user-images.githubusercontent.com/44309027/48961749-cb23d700-ef3c-11e8-8f16-8cb9228dbf4c.gif)

---

Posting a new comment increases answer count.
![errorinpostingcomments](https://user-images.githubusercontent.com/44309027/48961776-06bea100-ef3d-11e8-8866-ba9f18eecfef.gif)

---

Adding an answer doesn't increase answer count, but deleting one does.
![errorinpostingdeletinganswers](https://user-images.githubusercontent.com/44309027/48961806-31a8f500-ef3d-11e8-805d-16145d8ead1b.gif)

### Please show us where to look

https://publiclab.org/questions

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

kevinz_qu

### Browser, version, and operating system
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

Chrome, Ubuntu

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

The problems I mentioned all go away when the page is refreshed.

I would like to try working on this issue.

**Comment by conkytom** [comment]
I'd like to take a look at this.

**Comment by kevinzluo** [comment]
Hi @conkytom 
I actually started working on this already. Maybe we can assist each other 😄.

**Comment by conkytom** [comment]
Hey @kevinzluo, I haven't pinned down the source of the problem.  I only just started comparing the code from comments in Notes to comments in questions.  I was going to look at it more closely and try different approaches tomorrow.  If you've got any insights or want another set of eyes on it let me know.

**Comment by kevinzluo** [comment]
I think we should try moving everything to use notes/comments. It seems like questions/comments has become deprecated and lacks the "Promote comment to answer" button after https://github.com/publiclab/plots2/pull/3195. I'll let you know if I can find anything else. 
Thanks!

**Comment by jywarren** [comment]
I think Kevin is right, here! Perhaps it could be removed if deprecated :-)

**Comment by kevinzluo** [comment]
Hi sorry for the delay, I've been busy studying for my exam which is tomorrow. After, I take it I will return to working. 

Sorry!

**Comment by jywarren** [comment]
Closing as we've merged comments and answers now! Thanks!
