### ISSUE TITLE
Reworking UI sequence of posting notes and questions from a page that has been geo-tagged

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#4035]
@jywarren @ebarry  .

What do you have in mind to solve this issue ? Thanks !

🤔 🗺 ❓

**Comment by jywarren** [comment]
Thinking about how, when you're on a page that has been geo-tagged, doing
some sketches of how posting from that page could look:

1. where are the buttons and what are they labeled?
2. does it go to /post or /questions/new, and does it "retain" the lat/lon
tags?
3. does it show an inset map in the editor, and ask if you want to remove
the location, change it?

things like this, or that we haven't even thought of yet -- also good
content for the upcoming UI Open Hour!

**Comment by jywarren** [comment]
Complete!!! 🎉
