### ISSUE TITLE
Update the first_time_commenter function

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#4047]
In `app/models/user.rb` , a function by name **first_time_commenter** is present, which is added as a part of #3331. 

Update the function such that, if a user has created any node or comment in past whose status = 1,  then the user shouldn't be considered as first_time_commenter and false would be returned by function.

Make changes in function accordingly.

**This issue is for Google Code-In only, other contributors please find other issues from code.publiclab.org. Thanks!**

**Comment by ValentinaTironi** [comment]
Hi! I wanna work on this but I don't find the task in GCI. Can someone give the link or some reference to search it? Thank you!

**Comment by JonathanXu1** [comment]
![image](https://user-images.githubusercontent.com/22998430/49344736-58f07800-f649-11e8-9cd9-663e10aa8df3.png)

Currently, the function seems to do that already. I'm not familiar with ruby, so if I'm wrong, please let me know!

**Comment by gauravano** [comment]
Current code just checks for comment not for the node. But, anyway this task is not needed anymore, we would be using combination of first_time_poster and first_time_commenter as that makes more sense then updating this function so I have removed it from GCI dashboard. 

Thanks all!
