### ISSUE TITLE
Create a moderated view for the comment

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#4048]
**This issue is a part of Planning issue #3331**

Currently, we only moderate nodes before publishing, now we are planning for the comment moderation system. 

Show the comment on dashboard to moderators and admins in moderated view if the comment has status = 4. The design of the moderated comment can resemble that of moderated node.

The views which would require changes like in `app/views/dashboard`. the moderated node view lies in the same folder. 

**Hi, this issue has been opened as a task on GCI dashboard. If you are Google Code-In participant and want to solve this issue, please claim it from Google Code-In [website](https://codein.withgoogle.com/organizations/public-lab/) . Thanks!**

**Comment by oorjitchowdhary** [comment]
Hi @gauravano .. Could you pls explain more about this issue...
> Show the comment on dashboard to moderators and admins in moderated view if the comment has status = 4. The design of the moderated comment can resemble that of moderated node.

What is meant by comment status = 4?

**Comment by gauravano** [comment]
If in an array of comments, a comment has a status = 4 then that comment is
under moderation. So, that comment would be shown with the different view
from normal comment just like moderated node.

**Comment by ValentinaTironi** [comment]
Hello! I have a question: Would do you like add a section in dashboard where only show comment with status = 4 or just show them with nodes in Activity section?

**Comment by jywarren** [comment]
Hmm, i think alongside the other content, as they are on the dashboard
activity feed, for now. I think soon we may want to start thinking about a
specific spam "tab" or something, but for now let's just show as they are.
Thanks!

>

**Comment by oorjitchowdhary** [comment]
I get the issue.. 
How can I test the different views for questions and moderated questions.. I'd like to view it first and then add the same for the comments.. Can i get a pointer on that.. @publiclab/mentors

**Comment by gauravano** [comment]
@oorjitchowdhary as mentioned in the issue-
The views which would require changes like in `app/views/dashboard`. The moderated node view lies in the same folder.

**Comment by oorjitchowdhary** [comment]
Ok

**Comment by gauravano** [comment]
Comments with status = 4 are moderated comments visible to only moderators and admin.

**Comment by oorjitchowdhary** [comment]
So I just have to the moderate `comment status = 4` comments in comments `views/dashboard`?

**Comment by gauravano** [comment]
You have to create view for comment with status =4. you can take inspiration from the view of moderated node.

**Comment by oorjitchowdhary** [comment]
Ohk I see.. I think I'll take this up
