### ISSUE TITLE
Questions Page asks user to login when already logged in

### ISSUE THREAD

**Issue by conkytom** [publiclab/plots2#4058]
When a user goes to the the "Ask a question" page they are prompted to log in or register before asking a question.  This message appears even if they the user is already logged in.

Even if the user in logged in and writes something in the "type your question" form, the continue button is never able to to clocked on.  The only way around this is if the user enters something in the form presses tab and then enter they will be sent to questions/new path to create a new question.

This is an issue I see on my local host and stable.publiclab.org/questions version of the site, I do not see this publiclab.org/questions.  I am not sure how much the local host from the repository of the stable host reflect what will appear on the main site.

If I can confirm someone else is seeing this issue I would like to work on it.

### Please show us where to look

https://stable.publiclab.org/questions

### What's your PublicLab.org username?

tmconkwright 

### Browser, version, and operating system

Chrome, Version 70.0.3538.102, MacOS Sierra

![question_login](https://user-images.githubusercontent.com/26209735/49056530-071f9c00-f1ca-11e8-9ff4-a4a7503f4721.gif)

**Comment by oorjitchowdhary** [comment]
![screenshot 38](https://user-images.githubusercontent.com/39333058/49073269-0cc3c300-f258-11e8-94b3-982e0d25da53.png)
I find it working properly

**Comment by conkytom** [comment]
Created a pull request for this.

**Comment by oorjitchowdhary** [comment]
> Thanks @oorjitchowdhary, can you see if it is working properly for you [here on the stable beta site?](https://stable.publiclab.org/questions)

You're right.. I tried it out there.. It asks to log in again.. Nice catch..

**Comment by jywarren** [comment]
Oh interesting! Thanks for catching that!!!
