### ISSUE TITLE
Profile edit form is not submittable.

### ISSUE THREAD

**Issue by ujithaperera** [publiclab/plots2#407]
In profile edit, when I upload a image, image get uploaded. But after the upload 
confirm password field,
description field,
save button is not working. when I click on these elements, it triggers the file field for image upload and ask for the image path. 

### Relevant URLs
https://publiclab.org/profile/edit

### PublicLab.org username
Ujitha

### Browser, version, and operating system
Google chrome Version 48.0.2564.116 (64-bit)
Safari Version 9.0.3 (11601.4.4)

OS : OS X 10.11.3

**Comment by jiteshjha** [comment]
While this is being fixed, use tab key to work your way through the form.

**Comment by ujithaperera** [comment]
@jiteshjha yes we can use tab to change the focus of text fields. but we can't use tab key to submit the form

currently there is no issue in image, because when image get uploaded it replaces the current image without having users save command. It's some kind of a fix to this issue. But I suggest, its good to apply all the changes after the user hit on the save button for better user experience.
