### ISSUE TITLE
Problems with the /search/notes

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4079]
### Please describe the problem (or idea)
The `Read More` buttons aren't aligned uniformly.

![screenshot 40](https://user-images.githubusercontent.com/39333058/49268681-df109100-f486-11e8-85ed-1785fcb7d023.png)
and
There are two `pagination bars` on the same page.

![screenshot 41](https://user-images.githubusercontent.com/39333058/49268694-f18aca80-f486-11e8-97af-c655df80e4f9.png)

I remember similar issues being open on the panel but I think they were opened for editing of different pages. @publiclab/mentors 

### Please show us where to look
https://publiclab.org/search/notes/balloon

### What's your PublicLab.org username?
oorjit_chowdhary
### Browser, version, and operating system
Chrome, Windows 10
****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
great catch! Can you show where the code is to fix this? Thank you!

**Comment by sashadev-sky** [comment]
**Problem 1: Read more buttons** 

@jywarren I will create a FTO issue for this one. Should I leave the 2nd one for someone else to try? 

in app/views/notes/_notes.html, the `div` that holds the paragraph content as well as the read more button has styling defined on it that pushes its content to the right:

There is a `style` tag for the div class:
https://github.com/publiclab/plots2/blob/c204b268cd8dc1a713aeae15cc4222f0099d4d73/app/views/notes/_notes.html.erb#L66-L72

There is also inline styling on the `a` tag inside the button:
https://github.com/publiclab/plots2/blob/c204b268cd8dc1a713aeae15cc4222f0099d4d73/app/views/notes/_notes.html.erb#L51

@gauravano @oorjitchowdhary

**Comment by conkytom** [comment]
I think I've got an answer for the pagination issue and submitted a pull request.  The bottom of each search view had the `will_paginate` function, but the partials that the views rendered also contained the `will_paginate` function so there were duplicates.  I left the `will_paginate` in the partials and removed them from the various search views of notes, questions, and wikis.  Hope this does the trick.
