### ISSUE TITLE
Images distorted in thumbnail grids

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4082]
We have some great new thumbnail grids as shown on this page: https://publiclab.org/wiki/micro#Assembly

![image](https://user-images.githubusercontent.com/24359/49305137-6d434200-f49c-11e8-9b69-9cc187ba3526.png)

But as you can see, some images are distorted. This is solved in the dashboard templates -- https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_node_default.html.erb#L7 and the dashboard css:

https://github.com/publiclab/plots2/blob/e6608c89b3a7d1862d1e329e377ef8aea1e2ce90/app/assets/stylesheets/dashboard.css#L199-L204

Let's apply this to the new thumbnail grids too!

@ValentinaTironi would you mind linking to the thumbnail grid code? And would you be interested in making this into a first-timers-only issue to welcome someone else into the community? I'll paste in some guidance below:

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by oorjitchowdhary** [comment]
Can I take this up?

**Comment by jywarren** [comment]
Yes please!

**Comment by jywarren** [comment]
Would you like to make it into a first-timers-only issue and welcome someone else into the community?

**Comment by dinaelhanan** [comment]
@jywarren ^^ I think that's a good idea

**Comment by dinaelhanan** [comment]
@oorjitchowdhary good question, I don't see any distorted images either ;/

**Comment by jywarren** [comment]
The images are slightly squished -- they have not their original aspect
ratio. The CSS used on the dashboard is a little more complex, but allows
images to be shown in a fixed aspect ratio, with extra image hidden. Or, we
could just allow them to be different heights!

**Comment by dinaelhanan** [comment]
Oh I see.. Might take this up when I've finished the  [unit test task](https://github.com/publiclab/plots2/issues/3435). Would appreciate any help there! @jywarren

**Comment by JonathanXu1** [comment]
Would you guys need any help here?

**Comment by dinaelhanan** [comment]
Tried to fixed this using the above PR, I know it's a first-timer only issue, but I haven't really touched anything that had to do with the site's design, so I hope it's OK that I took it up..! @jywarren I'll try to find  way to make the issue for repetitive code really beginner friendly so we can welcome more first-timers! 
I remember seeing an issue that had to do with repetitive code, but I can't find it any where. Should I open an issue? Can't wait to help people contribute!

**Comment by jywarren** [comment]
Was it perhaps #3706 ? Thank you!

**Comment by ValentinaTironi** [comment]
Hey guys! Someone needs help here?

**Comment by oorjitchowdhary** [comment]
@publiclab/mentors So is this already solved then?

**Comment by dinaelhanan** [comment]
I have already solved it just waiting for a PR to be reviewed :) @oorjitchowdhary

**Comment by oorjitchowdhary** [comment]
Oh okay.. Thanks for the contribution @dinaelhanan
