### ISSUE TITLE
Activity prompt buttons on Thumbnail grids

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4092]
We have some great new features by @ValentinaTironi -- a thumbnail grid -- see the Activities section of https://publiclab.org/micro 👍 

One thing that would be great is to have the built-in buttons below that we see on non-thumbnail Activity grids, such as at https://publiclab.org/coqui

![image](https://user-images.githubusercontent.com/24359/49331305-d3959680-f568-11e8-988c-ecfdf66cecc2.png)

Here is the code that auto-generates the button and notice:

https://github.com/publiclab/plots2/blob/e400bf711b6f432051d61be2d912476d55de7ca3/app/views/grids/_notes.html.erb#L66-L73

I think we could break it into a partial template and also include it into the new thumbnail template, so we don't have redundant code:

https://github.com/publiclab/plots2/blob/master/app/views/grids/_thumbnail.html.erb

We'd love help with this and it could become a GCI task too!

**Comment by ValentinaTironi** [comment]
If I can help something, don't hesitate to ask me!

**Comment by oorjitchowdhary** [comment]
> One thing that would be great is to have the built-in buttons below that we see on non-thumbnail Activity grids, such as at https://publiclab.org/coqui

@jywarren I'm unable to understand this...

**Comment by ValentinaTironi** [comment]
I think he is trying to say that now doesn't exist a button to create notes in thumbnail grid like in others grids.
For example, here, in the questions grids there is an `ask a question` button

<img width="872" alt="screen shot 2018-12-01 at 3 49 32 pm 1" src="https://user-images.githubusercontent.com/20969831/49331732-c389b100-f580-11e8-9ff2-287f4c04384c.png">

**Comment by jywarren** [comment]
yes, exactly! thanks!!!

**Comment by oorjitchowdhary** [comment]
![screenshot 42](https://user-images.githubusercontent.com/39333058/49342168-9a027f80-f67d-11e8-8be3-8cb1a775380f.png)

I can see `add an activity` button in the thumbnail grid too.. Just the same as in the other non-thumbnail grids.. 
So do we want to add `ask a question` too?

**Comment by oorjitchowdhary** [comment]
@publiclab/reviewers ?

**Comment by ValentinaTironi** [comment]
Sorry for the delay! About your question: I don't see it locally

<img width="1280" alt="screen shot 2018-12-06 at 7 20 27 pm" src="https://user-images.githubusercontent.com/20969831/49615774-549bc600-f98d-11e8-89ce-731ecbf70b76.png">

Try create one in your project and let me know if the button appears!
@oorjitchowdhary

**Comment by jywarren** [comment]
Yes, i added that button manually! Sorry to confuse you, but we want it
added automatically as in prior types of grids. Thanks!

**Comment by ValentinaTironi** [comment]
@oorjitchowdhary are you still working on this?

**Comment by oorjitchowdhary** [comment]
Okay.. I'll open a PR in a while..

**Comment by jywarren** [comment]
You can make a new wiki page, and add the text "[notes:grid:test]" to a new
line in there, and save. That should work!

**Comment by oorjitchowdhary** [comment]
Okay thanks

**Comment by oorjitchowdhary** [comment]
That doesn't work @jywarren

**Comment by jywarren** [comment]
what do you see? You can see examples of thumbnail grids at
https://publiclab.org/micro for reference!

**Comment by oorjitchowdhary** [comment]
When I use `[notes:grid:test]`, nothing comes up.. it simply prints this on the page

**Comment by jywarren** [comment]
Perhaps you don't have any notes tagged with `test`?

**Comment by oorjitchowdhary** [comment]
Nope, i have it.. 2 of them actually

**Comment by jywarren** [comment]
what is the exact plaintext content on your wiki page?

**Comment by oorjitchowdhary** [comment]
This is happening when I try to create a new partial template..

**Comment by jywarren** [comment]
Hmm, can you point at your latest code in a commit? Even if you need to
open a new PR to share it? Thanks!

**Comment by oorjitchowdhary** [comment]
Ok i will do that

**Comment by oorjitchowdhary** [comment]
@jywarren pls check out #4175

**Comment by oorjitchowdhary** [comment]
And if you've got time pls take a look at #4129 too.. Thanks
