### ISSUE TITLE
Make "I did this" button open a comment form for faster posting

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4093]
We have an "i did this" button which appears at the end of activity posts (learn more at https://publiclab.org/activities)

![image](https://user-images.githubusercontent.com/24359/49333946-b5df2600-f596-11e8-964a-76c7904c4b9e.png)

But it prompts you to make a whole new post. Let's make this easier by starting with a comment prepopulated with `I did this!` and asking people to post a photo if they like. If they want to follow up with more detail, notes, ideas, etc, we can follow up later -- in fact we already do at the bottom of each comment on an activity: 

![image](https://user-images.githubusercontent.com/24359/49333952-ef179600-f596-11e8-8abd-3679ab3505d6.png)

Maybe it could pop open a comment window right there, like this:

![image](https://user-images.githubusercontent.com/24359/49334007-11f67a00-f598-11e8-9227-5834e0a5bdf9.png)

The comment form could go right on this line:

https://github.com/publiclab/plots2/blob/master/app/views/notes/_responses.html.erb#L29

It could be included with this code:

```ruby
      <%= render :partial => "comments/form", :locals => { title: 'Add feedback, suggestions, or photos
', body: 'I did this!', comment: false } %>
``` 

This line will also have to be changed to preserve the "i did this" text: 

https://github.com/publiclab/plots2/blob/master/app/views/comments/_form.html.erb#L18

It should be `body = body || params[:body]`

The newly inserted form should be in a `<div class="activity-comment">` with style `display:none;` and the `I did this` button should now run `$('.activity-comment').show();` when clicked. That'll make the new comment area show only when you click the button.

Finally, we could run `$('.activity-comment textarea').focus()` to activate the text area so you can start typing. 

This may require some testing to ensure the Preview button still works, but we can help you out with that when the time comes. We'd love help with this one!

**Comment by jywarren** [comment]
Added to GCI dashboard!

**Comment by okonek** [comment]
Couldn't it be done just by auto-scrolling down, focusing and entering 'I did this' in the default comment form?

**Comment by okonek** [comment]
Hi, I have resolved this issue in the PR https://github.com/publiclab/plots2/pull/4101 Take a look, when you'll have time.
