### ISSUE TITLE
Implement new UI format for top of tag pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4111]
This is part of a set of issues to take the design work produced by Kelvin at https://publiclab.org/notes/kelv/11-21-2018/tag-page, break it into design "pieces", and implement a number of them, while preserving our default Bootstrap styles: https://getbootstrap.com/docs/3.3/

Let's start with the top of the page. In Kelvin's design, we use a circular image with centered title and description below:

![image](https://user-images.githubusercontent.com/24359/49400473-63c30f80-f712-11e8-99da-969b0193a459.png)

The tag page template actually has 3 different layouts, depending on:

1. https://publiclab.org/tag/air-quality if there is a wiki page with the same name
2. https://publiclab.org/tag/coqui - if there is a lead image on that wiki page 
3. https://publiclab.org/tag/none if there is no matching wiki page at all

![image](https://user-images.githubusercontent.com/24359/49400855-8144a900-f713-11e8-8c05-35e220628534.png)

All three could follow the same new centered layout, where the circle could be grey if there's no image. The template for this page can be found here:

https://github.com/publiclab/plots2/blob/master/app/views/tag/show.html.erb

We'd love help with this!

**Comment by jywarren** [comment]
And a note - let's just start with the centered image in a circle, title, and description. We'll do other changes in a follow-up issue!

**Comment by oorjitchowdhary** [comment]
Can I take this up?

**Comment by oorjitchowdhary** [comment]
@publiclab/reviewers Is the Kelvin design not based on Bootstrap..?

**Comment by SidharthBansal** [comment]
yeah go ahead

**Comment by lohitha02** [comment]
@SidharthBansal  Can you please explain me what exactly I should do?
