### ISSUE TITLE
Move .yahoo_quoted class checking to new function

### ISSUE THREAD

**Issue by namangupta01** [publiclab/plots2#4112]
Here, we are checking for the presence of `.yahoo_quoted` https://github.com/publiclab/plots2/blob/ff870dea11781ab5ed50a806a55f362210f3a638/app/models/comment.rb#L300
We can improve this by moving this checking into the new function just like we have for gmail.
https://github.com/publiclab/plots2/blob/ff870dea11781ab5ed50a806a55f362210f3a638/app/models/comment.rb#L291

**Comment by dinaelhanan** [comment]
I will take this!
Please add to GCI dashboard!

**Comment by SidharthBansal** [comment]
Published on the GCI dashboard.
Please claim it before anyone else claims it.
Thanks

**Comment by namangupta01** [comment]
@SidharthBansal where is the pull request for this?

**Comment by SidharthBansal** [comment]
Sorry. Put label in wrong issue.

**Comment by SidharthBansal** [comment]
No one is currently working on this issue

**Comment by dinaelhanan** [comment]
I took above up another issue, and I have two more I would like to take. If by tuesday it is still not claimed and I'm finished the other two, I will take it. Otherwise, feel free everyone else to take it! :)

**Comment by dinaelhanan** [comment]
@SidharthBansal I will take this once I get this GCI task approved: https://codein.withgoogle.com/dashboard/task-instances/4824240835526656/

**Comment by dinaelhanan** [comment]
@namangupta01 what do you mean by moving it to a new function? I see that it is inside a function just like the gmail one here :
https://github.com/publiclab/plots2/blob/ff870dea11781ab5ed50a806a55f362210f3a638/app/models/comment.rb#L299

**Comment by gauravano** [comment]
Hi @dinaelhanan, what @namangupta01 meant is creating a new function named  `yahoo_quote_present? `  which would be similar in working to Gmail's function mentioned here- https://github.com/publiclab/plots2/issues/4112#issue-387058086

The goal is to replace the line https://github.com/publiclab/plots2/blob/ff870dea11781ab5ed50a806a55f362210f3a638/app/models/comment.rb#L300 with the function. 

Let us know if you want further details. Thanks!

**Comment by kimcheung** [comment]
Looks like this is still open, can I take it?

**Comment by kimcheung** [comment]
PR posted https://github.com/publiclab/plots2/pull/8640
