### ISSUE TITLE
Recenter 'Read more' button for note previews

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/plots2#4113]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem
The 'notes' previews across the site are aligned right instead of centered! 
[https://publiclab.org/search/notes/balloon](https://publiclab.org/search/notes/balloon)

<img width="573" alt="screen shot 2018-12-03 at 10 47 06 pm" src="https://user-images.githubusercontent.com/41092741/49417835-6ee76100-f74d-11e8-9e9d-640249fed7e8.png">

## Solution
This is a pretty easy one -- let's remove the CSS declarations from the notes HTML file that are overwriting the button's previously centered alignment:

1) 
Delete line 69 (and line 70, which is overwritten by the declaration directly under it anyway):
https://github.com/publiclab/plots2/blob/c204b268cd8dc1a713aeae15cc4222f0099d4d73/app/views/notes/_notes.html.erb#L66-L72

2) 
Delete the entire inline `style` attribute.
https://github.com/publiclab/plots2/blob/c204b268cd8dc1a713aeae15cc4222f0099d4d73/app/views/notes/_notes.html.erb#L51

Thanks!!

## Steps to Fix
 
- [x] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [x] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/plots2](https://github.com/publiclab/plots2)
 - [x] Create a new feature branch with a unique name descriptive to the issue
- [x] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [x] Reference this issue in the pull request body
- [x] Once you submit your pull request, an additional checklist will be provided for getting it merged

##  💬  Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by sashadev-sky** [comment]
@publiclab/reviewers can I have labels please 👍

**Comment by dinaelhanan** [comment]
@sashadev-sky that OK?

**Comment by sashadev-sky** [comment]
@dinaelhanan Thank you! I wrote it to be a first-timers-only issue should it have that label instead? Also should we delete these comments afterwards? People tend to think issues that are commented on are taken

**Comment by dinaelhanan** [comment]
@sashadev-sky OK deleting all comments now :+1:

**Comment by rachelkam5** [comment]
Hi!  I would love to contribute to this issue.  This would be my very first open source contribution.

**Comment by rachelkam5** [comment]
I just read over your README file, and I have a question about #4 under Standard Installation.  I've never worked with Rails before, so I'm not sure about the rails root directory.  Do I need to install Rails or something else before setting up the fork locally?  Thank you!

**Comment by rachelkam5** [comment]
@sashadev-sky Thank you!  I will get to work and let you know if I have any more questions!

**Comment by sashadev-sky** [comment]
@rachaelkiteme Sounds good 👍

**Comment by rachelkam5** [comment]
Hi @sashadev-sky I'm so sorry, but I don't think I'm cut out for this one.  I've spent a really long time trying to install Ubuntu, Bash, RVM, etc. and I'm getting error after error.  I'm so sorry!

**Comment by sashadev-sky** [comment]
@rachelkam5 Don't worry!! Ask as many questions as you'd like, thats what this issue is for :) 

I received a lot of errors my first time setting up the repo as well. Maybe I can take a look at yours? Feel free to message me in the [Gitter chatroom](https://gitter.im/publiclab/publiclab) if you prefer.

**Comment by jywarren** [comment]
Yes, and there are some discussions on common install issues over at #3840 -- maybe that can help too!

**Comment by wanzulfikri** [comment]
@rachelkam5  Can I take a stab at this? If you are still working on this, do continue.

**Comment by rachelkam5** [comment]
@wanzulfikri Yes, please take over!  Thank you!

**Comment by wanzulfikri** [comment]
@rachelkam5 Thanks! I’ll try to do it.

I’m a bit slow, so if anyone wants to do it and can complete it earlier than I, feel free to do it and submit the pull request.

**Comment by uzorjchibuzor** [comment]
@wanzulfikri 

How far along are you? I also want to take a stab at this.

**Comment by wanzulfikri** [comment]
@uzorjchibuzor 

Honestly - zero progress.

You can try if you want. 

I don’t own it haha.

**Comment by naveenanilabs** [comment]
can i work on this issue.

**Comment by navkumar2245** [comment]
can i work on this issue if not fixed.

**Comment by SidharthBansal** [comment]
@sashadev-sky
please use permalinks instead of line numbers. They are adjusted as the other changes are merged by other users..

**Comment by SidharthBansal** [comment]
Solved in #4146

**Comment by sashadev-sky** [comment]
@SidharthBansal thank you for taking over here :) noted about the line numbers
