### ISSUE TITLE
Help People Report Errors!

### ISSUE THREAD

**Issue by dinaelhanan** [publiclab/plots2#4117]
# The Problem:

Currently, if a user get a non-existing page, they get a message saying "Report a bug or issue" in the footer, which isn't welcoming for non-developer users and is hard to notice. Instead, we should have something that says "Please feel free to Send Us Feedback!" when a user is first accessing the dashboard. We can have this show up in the banner, in here!

![screenshot from 2018-12-05 11-11-54](https://user-images.githubusercontent.com/19677511/49526818-a43f9c00-f87e-11e8-9d67-5b5db9d48571.png)

We want to welcome people to give feedback!

# How to Solve?
Add a message to the banner on the landing page for new users. You can do that by adding to the text here to include "PublicLab is a platform is built by people collaboratively and that is always improving. We welcome any Feedback you have!". You can even add a button that links to [the issues portion of this repo](https://publiclab.org/issues)

https://github.com/publiclab/plots2/blob/dd18e979e619005c28254fd129852602e0279dd7/app/views/dashboard/dashboard.html.erb#L6

Here's the code for an existing buttons:
https://github.com/publiclab/plots2/blob/dd18e979e619005c28254fd129852602e0279dd7/app/views/dashboard/dashboard.html.erb#L11

You can copy-paste it to a line below that, and change the link to this --> https://github.com/publiclab/plots2/issues/new
 If you have any issues, please feel free to reach out in the comments below!

**Comment by Rishabh570** [comment]
@dinaelhanan Great! Having the banner (as suggested #3631 ) on the landing page will make it clear to new people at the first place I believe...what do you think?

**Comment by dinaelhanan** [comment]
@Rishabh570  oh ok I'll add that

**Comment by dinaelhanan** [comment]
@Rishabh570 done! Please check out my task for this :) 
https://codein.withgoogle.com/dashboard/task-instances/5643246135934976/

**Comment by jywarren** [comment]
love this!!!

**Comment by dinaelhanan** [comment]
@jywarren thank you!

**Comment by CodeSarthak** [comment]
Hi @jywarren @dinaelhanan Can I work on this one?

**Comment by CodeSarthak** [comment]
Hey @dinaelhanan @jywarren @publiclab/mentors , I have an another idea. We can break this issue down into two. One for the message on the banner(this one) and other for making a new button to redirect to issues page of the repo.

**Comment by CodeSarthak** [comment]
This will help us make two fto issues.

**Comment by oorjitchowdhary** [comment]
Hi, what are we trying to do here.. I'm unable to understand

**Comment by SidharthBansal** [comment]
These are supportive tasks. This tasks says newcomer that if you find any
bug then feel free to open up an issue. You are already doing this task.

**Comment by jywarren** [comment]
Hi, I've looked at this and I think we now have a better error reporting page when things go wrong! See this screenshot for non-existent or error pages like https://publiclab.org/nothing/asdfas

![image](https://user-images.githubusercontent.com/24359/54062233-d987bd00-41d2-11e9-8411-1458c32bf8cc.png)


So I'm going to close this one, but thank you!!!!!

But I've opened a new issue for Nirvikalpa108 here: https://github.com/publiclab/plots2/issues/3480
