### ISSUE TITLE
Posting a research note awarded me a barnstar from myself again

### ISSUE THREAD

**Issue by dhaffnersr** [publiclab/plots2#412]
### What happened just before the problem occurred

I was posting a new research note today 3-12-2016, and it awarded me from myself a barnstar again automatically, I did what you advised the last time and deleted it from my tags, but apparently it did it again.

### Relevant URLs

https://publiclab.org/notes/dhaffnersr/03-12-2016/final-data-analysis-for-10w40-motor-oil-using-400nm-uv-led-mar12

### PublicLab.org username
dhaffnersr

(to help reproduce the issue)

### Browser, version, and operating system
google chrome

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by dhaffnersr** [comment]
I forgot to put in there that my operating system is Windows 7

**Comment by ebarry** [comment]
Hi David,
impressive use of tags, 50+ per post.

It occurred to me that tagging a spectrometry post with google-maps,
google-earth, city-point, purelab, science, weird-science,
museum-of-science, cool-stuff, very-cool-stuff and five versions of your
name is a rather unusual use of tags. I'm wondering if that thought has
occurred to you?

--

+1 336-269-1539
@lizbarry <http://twitter.com/lizbarry>

**Comment by dhaffnersr** [comment]
Hey Liz! Well, yeah it may seem unusual but there is a method to it. I
learned about meta tagging when I use to be on Youtube, tags work in an
order of heiarchy through the internet, the goal is to bring more attention
to Plab. Certain tags and their arrangement start to build up hits and then
it starts to grown geometrically. have a good one!

Dave H

**Comment by jywarren** [comment]
Hi, Dave - we just haven't been able to find a moment to fix this bug yet, so for the time being, please just delete the barnstar tag yourself. I'm going to close this issue and point back to #404. Thanks!

**Comment by dhaffnersr** [comment]
Ok Jeff, no problem
