### ISSUE TITLE
Search results should include words mentioned in Title

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#4121]
Dear everyone, 
When i type in the built-in search box in our menu bar for `barnraising` and `texas`, i get this page of results: https://publiclab.org/search/barnraising%20texas  ...which doesn't list the actual wiki that has "barnraising" and "texas" in the *title* and as *tags*: https://publiclab.org/wiki/barnraising-texas-2019. 

Similarly, this wiki with "barnraising" and "texas" in the title and tags _doesn't_ show at https://publiclab.org/search/wikis/barnraising+texas

But if you click "Most recent" sorting on https://publiclab.org/search/wikis/barnraising+texas?order=default -- it does show up. 

Thanks for reading!

(**Updated:** we've written a test to demonstrate this bug at https://github.com/publiclab/plots2/pull/4149 - now we should be able to confirm that any solution resolves this test @dinaelhanan wrote. Still looking for help actually resolving it!)

**Comment by dinaelhanan** [comment]
this looks like a good issue for gci... I would even consider taking it up myself. Thanks for sharing!

**Comment by jywarren** [comment]
Awesome! Just adding some possibly helpful code links; this is mostly driven by the Service API:

https://github.com/publiclab/plots2/blob/26079dbbc10e13ce1e1874b50faac3de1e47f8ea/app/services/search_service.rb#L53-L56

And the MySQL full text search:

https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L27-L68

Maybe most specifically this section?

https://github.com/publiclab/plots2/blob/26079dbbc10e13ce1e1874b50faac3de1e47f8ea/app/models/node.rb#L55-L60

**Comment by jywarren** [comment]
Here's where the search is initiated in the controller: 

https://github.com/publiclab/plots2/blob/26079dbbc10e13ce1e1874b50faac3de1e47f8ea/app/controllers/search_controller.rb#L11-L14

I wonder if it's doing a default boolean search? We can check that in the logs when running it locally. 

It'll be doing one of these three types of search query, in any case: 

https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L39-L60

One of them seems to work much better than the others!

**Comment by jywarren** [comment]
This could be broken up to see if we could debug both the observation that it should match the TAGS, and separately that it should match the TITLE. Just a note that here's a test demonstrating matching ONE tag, but not two:

https://github.com/publiclab/plots2/blob/26079dbbc10e13ce1e1874b50faac3de1e47f8ea/test/unit/node_test.rb#L52-L60

So maybe we need to make a new test to test two-tag matches?

There are also a number of search service based tests in this file which we could add to to try to capture these observed bugs within our tests, and then solve the issues by getting the tests to pass: 

https://github.com/publiclab/plots2/blob/master/test/unit/api/search_service_full_text_search_test.rb

**Comment by dinaelhanan** [comment]
@jywarren ok so this looks like an issue that needs breaking up. Since I've now gotten familiar with writing tests, I'll be happy to write a test for two-tag matches, like you've mentioned above. I'll open an issue on that. Please add this to the GCI tasks, I'd be more than happy to take it up! (just waiting for approval on this one task:https://codein.withgoogle.com/dashboard/task-instances/5643246135934976/)

**Comment by dinaelhanan** [comment]
@jywarren is this not similar to this issue? https://github.com/publiclab/plots2/issues/3480

**Comment by jywarren** [comment]
It's similar in that it tests tag-related functions, but it's testing a distinct function. Thanks! 👍

**Comment by JonathanXu1** [comment]
Hey could I help out as well? This task seems to be available on GCI

**Comment by jywarren** [comment]
Completed in #5978
