### ISSUE TITLE
Drag/drop of image upload into Answer input inserts into wrong textarea

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4122]
I dragged an image into this Answer texarea:

![image](https://user-images.githubusercontent.com/24359/49524393-abb07680-f879-11e8-8227-a24ee9bfa539.png)

on this page:

https://publiclab.org/questions/warren/10-29-2018/help-us-refine-the-search-interface-at-publiclab-org

and the image was inserted at the top comment box. I think we need to fix where the `dragdrop.js` is sending the uploaded image within the page:

https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/dragdrop.js

We'd LOVE help fixing this!

**Comment by oorjitchowdhary** [comment]
@jywarren I think there's too much of similar code between `Answers` and `Comments`.. 
There's an issue with the preview too.. #3534

**Comment by oorjitchowdhary** [comment]
I think I'll work on this

**Comment by jywarren** [comment]
we have that plan, yes! Actually it will hopefully be worked on soon!

**Comment by vaarigupta** [comment]
hello @jywarren    I am an **outreachy applicant** and excited  to work on this issue. How can I start contributing ?

**Comment by jywarren** [comment]
Hi! We have actually just finished #4537 which eliminates the Answers system. So I'm going to close this, but we'd love your help on another issue. Since it's your first one, we are happy to make you a first-timers issue -- i've added you to the list here, and we'll make one for you as soon as we can! Thank you!!!

https://github.com/publiclab/plots2/issues/4963

**Comment by gauravano** [comment]
Closing this @jywarren as you mentioned, it's not needed anymore. Thanks!
