### ISSUE TITLE
Preserve editable search term in search results page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4123]
Working from a set of issues identified here: https://publiclab.org/questions/warren/10-29-2018/help-us-refine-the-search-interface-at-publiclab-org

This is an issue on pages like this, when you complete a search: https://publiclab.org/search/wikis/barnraising+texas

I noticed that when you get to a search results page, there is nowhere on the page where you still see the search phrase in an editable input box, which would make it much easier to refine the search phrase:

[![Screenshot_2018-12-05_at_10.33.49_AM.png](https://publiclab.org/i/28099)](https://publiclab.org/i/28099)

Most search engines will keep the text you originally typed in a search box so editing your search to tweak results is easier: 

[![Screenshot_2018-12-05_at_10.38.00_AM.png](https://publiclab.org/i/28127)](https://publiclab.org/i/28127)

![image](https://user-images.githubusercontent.com/24359/49524568-03e77880-f87a-11e8-9398-a12d36f5cb9f.png)

### Code

The templates for these search results views are in this folder:

https://github.com/publiclab/plots2/tree/master/app/views/search/

And the search box at the top of the page is here, although perhaps we should make a new box? That's a good UI question - keep displaying text in the existing box or make an in-page box lower down?

https://github.com/publiclab/plots2/blob/26079dbbc10e13ce1e1874b50faac3de1e47f8ea/app/views/layouts/_header.html.erb#L23

**Comment by jywarren** [comment]
@stefannibrasil @milaaraujo thought this could be a fun one for someone in GCI! 🐱

**Comment by kevinzluo** [comment]
Hi there!

I believe this may be solved by setting the input's value to `params[:query]`. We can maybe do this with some javascript.

**Comment by jywarren** [comment]
oh that would be amazing -- you could even set it in the template in ruby
no?

**Comment by kevinzluo** [comment]
Could I open a FTO issue for this?

**Comment by SidharthBansal** [comment]
Yeah great work. Can you please claim the task on the gci dashboard so that I can give you rewards.
@jywarren can we know close this issue as @kevinzluo has created first timer for this issue

**Comment by jywarren** [comment]
Oh fantastic! Great work, @kevinzluo -- and looks like someone may already be wanting to work on it? 😄
