### ISSUE TITLE
combine comment buttons into a button group

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4124]
Let's combine comment buttons into a button group using Bootstrap styles: 

![image](https://user-images.githubusercontent.com/24359/49525099-026a8000-f87b-11e8-8fe6-9f2bb6dce5df.png)

Button groups docs: https://getbootstrap.com/docs/3.3/components/#btn-groups

![image](https://user-images.githubusercontent.com/24359/49525243-51181a00-f87b-11e8-90b0-1adb07c40c9d.png)

Code for this view can be found at:

https://github.com/publiclab/plots2/blob/master/app/views/notes/_comment.html.erb

**Comment by jywarren** [comment]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by oorjitchowdhary** [comment]
https://github.com/publiclab/plots2/blob/master/app/views/notes/_comment.html.erb#L37-L80
We intend to put these into a new `div class`.. am I right?
Can I take this up?

**Comment by jywarren** [comment]
yes, that's just right. thank you!

**Comment by SidharthBansal** [comment]
@oorjitchowdhary please claim https://codein.withgoogle.com/dashboard/tasks/6542704897949696/ so that I can approve it.
Thanks
