### ISSUE TITLE
Make a new Test to test for two-tag matches for search

### ISSUE THREAD

**Issue by dinaelhanan** [publiclab/plots2#4125]
This is a broken up part of this issue (#4121)
We are trying to test if the search gets matches that have two tags that equal the search.

https://github.com/publiclab/plots2/blob/26079dbbc10e13ce1e1874b50faac3de1e47f8ea/test/unit/node_test.rb#L52-L60

**Comment by jywarren** [comment]
Closing this although this is only the test -- we need the solution to finally merge #4149 - thank you!!! 🎉
