### ISSUE TITLE
More compact design for comment display on dashboard

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4126]
https://publiclab.org/dashboard shows comments, but they aren't very compact in design:

![image](https://user-images.githubusercontent.com/24359/49528218-8aec1f00-f881-11e8-8429-b43b6e932c8c.png)

In [the UI OpenHour](https://publiclab.org/notes/warren/12-03-2018/openhour-usability-feedback-for-publiclab-org) Bronwen noted that they could be more compact. Let's do some design sketches!

You can use this Google Presentation to do some mockups and upload screenshots:

https://docs.google.com/presentation/d/1TCZoTfuhamRVrUak8aDgqJAwSgyhRtZg2Pgacl2_4zc/edit#slide=id.g3924eb58a4_0_0

**Comment by oorjitchowdhary** [comment]
How about changing it to list view.. like publiclab.org/comments

**Comment by oorjitchowdhary** [comment]
![screenshot 52](https://user-images.githubusercontent.com/39333058/49682906-32678c80-fae2-11e8-8949-3ca71c79aeaa.png)

**Comment by oorjitchowdhary** [comment]
@publiclab/reviewers ?

**Comment by SidharthBansal** [comment]
I will suggest that we want both views.
We need to change the grid view to something better. If you could provide us a better template to work upon, you can got GCI rewards.
Thanks

**Comment by SidharthBansal** [comment]
Nice suggestion btw

**Comment by oorjitchowdhary** [comment]
> I will suggest that we want both views.
> We need to change the grid view to something better. If you could provide us a better template to work upon, you can get GCI rewards.
> Thanks

Okay let me find something more interesting then..

**Comment by oorjitchowdhary** [comment]
> Nice suggestion btw

Thanks 😄

**Comment by oorjitchowdhary** [comment]
I just realized if we do the list view, it won't look good with moderated views as `moderated views` are in grid view.. So we'd have to do something either with moderated view conversion to list moderated or enhance the current grid view for comments..

**Comment by SidharthBansal** [comment]
We want either a new grid view or need to modify the existing one

**Comment by oorjitchowdhary** [comment]
@jywarren Your views here please

**Comment by oorjitchowdhary** [comment]
@publiclab/reviewers I'd like to complete either this or https://github.com/publiclab/plots2/issues/4115#issuecomment-445020693 as my last task on gci..
If I can go for these, I'll claim it .. Also, #4126 isn't available on gci dashboard..

**Comment by jywarren** [comment]
I think we could preserve the same basic style, but think about:

a) how it might not need all the info shown, so as to save space
b) how we might be able to group comments by the post they're attached to,
to save space
c) how we might make the styling of each comment box a bit more minimal or
simpler/smaller

**Comment by oorjitchowdhary** [comment]
@SidharthBansal Can you add this to gci.. I'll complete this one as my last task

**Comment by SidharthBansal** [comment]
https://codein.withgoogle.com/dashboard/tasks/5957069766131712/

**Comment by oorjitchowdhary** [comment]
Thanks

**Comment by ValentinaTironi** [comment]
@oorjitchowdhary Are you still working on this?

**Comment by oorjitchowdhary** [comment]
Yes... This is my last task..

**Comment by oorjitchowdhary** [comment]
> I think we could preserve the same basic style, but think about: 
* [ ]  how it might not need all the info shown, so as to save space 
* [ ] how we might be able to group comments by the post they're attached to, to save space 
* [ ] how we might make the styling of each comment box a bit more minimal or simpler/smaller

Could I get guidance regarding the group comment.. I've done the rest two
Here is how the comment looks now on the dashboard on my localhost..

![screenshot 98](https://user-images.githubusercontent.com/39333058/49800896-b635a900-fd6e-11e8-8c5e-58eefadd35a8.png)

**Comment by oorjitchowdhary** [comment]
@SidharthBansal @jywarren

**Comment by oorjitchowdhary** [comment]
I'm sending a patch for the changes done by me.. Is it okay?

**Comment by SidharthBansal** [comment]
Let's seek guidance from Jeff which design we need to implement.
I really like your work. Beautiful. He knows much better than I do.

**Comment by SidharthBansal** [comment]
Great to see your PR.
