### ISSUE TITLE
Add "spam" button to https://publiclab.org/comments

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4127]
To make spam comment moderation easier, let's add a "spam" link to the table on this page:

https://publiclab.org/comments

The link could take the format:

```ruby

      <% if current_user &. can_moderate? %>
          <a rel="tooltip" title="Mark as spam" class="btn btn-sm btn-default btn-flag-spam-<%= comment.id %>" data-confirm="Are you sure? The user will no longer be able to log in or publish, and their content will be hidden except comments." href="/admin/mark_comment_spam/<%= comment.id %>">
            <i class="fa fa-ban"></i>
          </a>
    <% else %>
          <a rel="tooltip" title="Flag as spam" class="btn btn-sm btn-default btn-flag-spam-<%= comment.id %>" href="mailto:moderators@publiclab.org?subject=Reporting+spam+on+Public+Lab&body=Hi,+I+found+this+comment+that+looks+like+spam+or+needs+to+be+moderated:+https://publiclab.org/<%= comment.parent.path %>#c<%= comment.cid %>+by+https://publiclab.org/profile/<% if comment.author %><%= comment.author.name %><% end %>+Thanks!">
            <i class="fa fa-flag"></i>
          </a>
      <% end %>
```

The page template is here:

https://github.com/publiclab/plots2/blob/master/app/views/comments/_comments.html.erb

**Comment by oorjitchowdhary** [comment]
@publiclab/reviewers I've got an idea.. I think we can implement the list style as I did in my PR #4130 ..
We can make this a tabular site and I'll add a `moderated` row for this where only admins/moderators can view the option to `Ban/Spam` the author of the comment... What say?

**Comment by oorjitchowdhary** [comment]
![screenshot 48](https://user-images.githubusercontent.com/39333058/49538042-814dd000-f8f0-11e8-8d40-526e863cdf6a.png)
Somewhat like this but replacing the `last activity`, `joined`, and `history` tabs with the comments and the `moderation` bar...

**Comment by jywarren** [comment]
that sounds great!

**Comment by SidharthBansal** [comment]
@oorjitchowdhary please claim https://codein.withgoogle.com/dashboard/tasks/5692922734313472/
so that I can approve it.
Thanks for awesome work

**Comment by oorjitchowdhary** [comment]
Done.. 
Thanks a lot.. I'm really enjoying working with Public Lab 😄

**Comment by SidharthBansal** [comment]
You will enjoy it more!!! :smile:
