### ISSUE TITLE
Drag and drop image while editing research note comments fails

### ISSUE THREAD

**Issue by Fastie** [publiclab/plots2#413]
Drag and drop works when writing a comment but not when editing that comment after it has been published.
chrome in windows

**Comment by Fastie** [comment]
Drag and dropping images into comments on research notes (when first creating the comment) now produces three instances of the image code.

**Comment by jywarren** [comment]
Thanks for reporting, chris. All of this is only when dragging but not when
using the select image link?

**Comment by Fastie** [comment]
I recall that I tried the select image link last night and that also failed. This was when editing an existing comment.

**Comment by jywarren** [comment]
Thanks for the added info.

**Comment by Fastie** [comment]
Dragging a photo into a comment (on a research note) produced 15 (I think) instances of the image embedding code. It was the 14th comment on the note. On the ninth comment on a note, I think I got nine instances of the code. Very exciting.

**Comment by ujithaperera** [comment]
Yeah this is an odd experience to the user. i caught the bug. @jywarren Give me few mintues to send my fix.

**Comment by jywarren** [comment]
Commented on your pull request at #421 with some additional debugging input; I think we're close but not quite there. Thanks!

**Comment by jywarren** [comment]
This should be fixed; can you confirm and re-open if it is not? Thanks, esp. to @ujithaperera!

**Comment by Fastie** [comment]
Dragging photos into new or old comments now seems to work fine. 

Thanks.
