### ISSUE TITLE
Planning Issue: Subscription Prompts Across the Website

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4131]
We have a great subscription system now. Let's come up with some better, smarter, and smoother ways to encourage people to subscribe (without just making BIG SIGNS EVERYWHERE). Ideas:
* [x] [Priority] Make general purpose route /subscription_tag=tagname.... like return_to for the following features.
* [x] combined “Subscribe and login” flow - get people subscribed to some tags as they sign up, based on tags from the pages they've been looking at
    * a route or parameters or session modification to pass some tag names in upon logging in, which then are auto-subscribed to with a notification and link to /subscriptions #3931
- [x] Notes
- [x] Wikis
- [x] Maps
- [x] Questions
* [x] Like + Subscribe flow:
Case A1. User likes the page
A2. We will show buttons under each tag "Liked! Follow more content like this by clicking one of these topics: ....".
Case B. A user has not liked the page. Then no need to show subscribe buttons under each tag.
Talking about the subscription button made.
* [x] combined “Comment + subscribe” flow - get people subscribed to some tags as they leave a comment, maybe based on the tags of the post they're commenting on, perhaps using parameters to the comment post action #3932 
- [x] "Suggested subscriptions" on email notification footers #3008
- [x] Topics on dashboard 
![image](https://user-images.githubusercontent.com/20972099/51137232-66159f00-1864-11e9-803d-cf9a38f9e212.png)
- [x] trending tags on dashboard
- [ ] Tags page  popular tags
- [x] Individual tag page related tags 
![image](https://user-images.githubusercontent.com/20972099/51137170-43838600-1864-11e9-913c-a8bc74c75fe2.png)
- [x] Blog

Refer https://github.com/publiclab/plots2/issues/3924

**Comment by SidharthBansal** [comment]
@IshaGupta18 are you familiar with creation of `first timer only` issues. Have you created any so far?
We will creating first timers issues for the following:
![image](https://user-images.githubusercontent.com/20972099/51112175-727a0780-1824-11e9-80ad-193e8642a856.png)

This means this whole project is going to be done by first timers. Isn't this amazing @jywarren?
I will try my level best to increase our community as much as I can. :tada: :100:

**Comment by geekychaser** [comment]
@jywarren @SidharthBansal i would love to work on this. please guide me
thank you

**Comment by IshaGupta18** [comment]
Yes, you can guide me too on how to make ftos once we are done with the main PR, then we can work on this and make ftos, will that be okay? @SidharthBansal

**Comment by SidharthBansal** [comment]
Here is template to ftos.
https://docs.google.com/document/d/1dO-CAgModEGM5cOaMmcnBh2pEON0hv_rH3P2ou2r1eE/edit

You can use this template to write `first timer only` issues. Conversation will be here if you face problem in creating them. 

@IshaGupta18 you can add subscribe button next to tags shown on the blog page. Can you create fto for this once we complete #4626.

@geekychaser once @IshaGupta18 completes her fto creation. You can add button next to topics on the dashboard. Let's do this much first

**Comment by IshaGupta18** [comment]
Absolutely!

**Comment by SidharthBansal** [comment]
@IshaGupta18 please read it once more. I need to edit it due to some reasons. Sorry

**Comment by SidharthBansal** [comment]
@IshaGupta18 let's have a quick pr merge for the Subscription button next to Topics on the dashboard as per https://github.com/publiclab/plots2/issues/4131#issuecomment-454542075

**Comment by SidharthBansal** [comment]
Please merge the latest master(#4626) into your master and make a new branch for these changes.

**Comment by SidharthBansal** [comment]
Please use emoticons(:+1: ) from next time. We want shorter conversations.

**Comment by IshaGupta18** [comment]
Actually I am facing some problem here. The "Topics" panel is being fetched through a helper using caching in the code and I am unable to get how to access that view, so that I can render my button partial there. Could you please guide me with that?

![image](https://user-images.githubusercontent.com/40794215/51320415-b750a900-1a85-11e9-864f-278c8d193e43.png)

**Comment by SidharthBansal** [comment]
It is always better to tell the permalink than sending screenshots. Please
provide it so that mentor can help you.
You have to display the button next to the `Topic` text. So, search for
topic text.

**Comment by IshaGupta18** [comment]
Yes actually, this isn't like a normal view here, the view is being rendered through cache, from an entry in the database, here are the links:
https://github.com/publiclab/plots2/blob/9f7cfc47ded41ed3a7370c66a9c4f7af9704af59/app/views/sidebar/_dashboard.html.erb#L38-L41

https://github.com/publiclab/plots2/blob/9f7cfc47ded41ed3a7370c66a9c4f7af9704af59/app/helpers/application_helper.rb#L57-L64

So the view is rendered from the database's entry. Does this make sense?

**Comment by SidharthBansal** [comment]
I think we can add the button next to line 41 in plots2/app/views/sidebar/_dashboard.html.erb.

**Comment by IshaGupta18** [comment]
What should I pass as tags variable here then? Like @node.node_tags, what will come here?

**Comment by SidharthBansal** [comment]
Please leave this issue until Jeff replies on it.
You can send a PR for the blog page.

**Comment by IshaGupta18** [comment]
So I am inserting the button here, is this right? Should I make a PR for it?

![image](https://user-images.githubusercontent.com/40794215/51347552-6ad98d80-1ac6-11e9-82e6-6e31a1974707.png)

![image](https://user-images.githubusercontent.com/40794215/51347534-5e553500-1ac6-11e9-8d46-9eb3e4bd3368.png)

**Comment by SidharthBansal** [comment]
Make it next to read more text.
Yes make a PR.

**Comment by SidharthBansal** [comment]
Once you complete your PR. Then please try "trending tags on dashboard". Don't commit changes. Use the fto template given above to create a fto. You can see other ftos for reference.

**Comment by SidharthBansal** [comment]
#4666 created by @geekychaser

**Comment by geekychaser** [comment]
created #4667 for `/tags`

**Comment by geekychaser** [comment]
@SidharthBansal I guess we have covered all the related issue ?
Please correct me if i am wrong.
Thank you

**Comment by SidharthBansal** [comment]
I think one issue is left. Trending tags.

**Comment by geekychaser** [comment]
@SidharthBansal So we need to have this subscribe button on our dashboard ?

**Comment by SidharthBansal** [comment]
Yes

**Comment by IshaGupta18** [comment]
Can I do this please since it was assigned to me? @SidharthBansal

**Comment by IshaGupta18** [comment]
@geekychaser we'll assign you more ftos but kindly let me create this one because it was assigned to me initially

**Comment by SidharthBansal** [comment]
Yeah you can do it. @geekychaser is just helping you here, I guess. Isha
can create the fto and in case she will require help then Rishabh can do so.
Once Isha you post the fto, please close this issue.
Thanks all.

**Comment by geekychaser** [comment]
@IshaGupta18 I know, that you are creating ftos but this is your first fto so i was trying to help you in fto creation.
thank you

**Comment by SidharthBansal** [comment]
Great folks. We really appreciate Rishabh your kind gesture to help Isha

**Comment by IshaGupta18** [comment]
I have created #4671 for trending tags. I think this issue can be closed now. Where all should we add this button now? Any suggestions apart from the ones for which ftos have been created?

**Comment by SidharthBansal** [comment]
Have you checked it before creating the fto that it works perfectly fine?
I checked each page. There are no more places where we can add the buttons. In case, you will find it please create a fto for it. 
We can close this issue.

**Comment by SidharthBansal** [comment]
@jywarren we have successfully completed this Multiple Tag Subscription Project with help of @IshaGupta18 and @geekychaser :tada: :100: :1st_place_medal: 
If anything is left in the project please feel free to reopen the issue and comment some suggestions.

**Comment by jywarren** [comment]
Fantastic work, everyone!!!!
