### ISSUE TITLE
UI fixes for range pages and stats page

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#4139]
* [x] Style `stats/range` page calendar section to be mobile responsive
* [x] Transform ` year, one month, or one week further back`  to fa arrow buttons
* [x]  Add cleaner links to range and subscriptions  pages on stats page
* [x] Re evaluate the choice of words used on the range page
* [x] Implement the new stats page design

**Comment by cesswairimu** [comment]
![screencapture-app-moqups-cessmbuguar-gmail-com-wzagurbx4h-view-page-a526cc314-2019-01-04-18_29_39](https://user-images.githubusercontent.com/17081074/50695838-e7905480-104e-11e9-842f-d723257e55c3.png)

**Comment by cesswairimu** [comment]
@gauravano @sagarpreet-chadha @jywarren @SidharthBansal this a redesign for the  https://publiclab.org/stats page. I need some criticism and input/ideas about the same. Kindly take a look and leave some comments :smiley: Thanks.

**Comment by cesswairimu** [comment]
![screencapture-app-moqups-cessmbuguar-gmail-com-wzagurbx4h-view-page-a526cc314-2019-01-04-18_29_39](https://user-images.githubusercontent.com/17081074/50860944-5ac7fc80-13a8-11e9-8493-4188ff3efbf8.png)

**Comment by jywarren** [comment]
So as these are merged into the range pages, the periods displayed on the
visualizations would match the ranges, i think. How does that sound? Some
may need to be reworked to be for a generic period!
