### ISSUE TITLE
Clicking Publish on research note comments gives no feedback

### ISSUE THREAD

**Issue by Fastie** [publiclab/plots2#414]
Clicking publish on a comment to a research note publishes the comment (or edits) but gives no indication that anything happened. 
Chrome in windows

**Comment by jywarren** [comment]
Do you mean like a notice or green indicator or alert that says "your
comment was published"?

Is this helpful because you almost don't notice when the comment is added?
What about if we used a "blind open" animation to add the comment?

**Comment by Fastie** [comment]
I just posted a comment on a note and the display immediately showed the published note and an empty comment box for a new comment. But when I was editing an existing comment and clicked publish, nothing happened. My editing window persisted with my edits in it, and there was no display of my newly edited comment. When I opened a new tab and navigated to the note, my newly edited comment was published.

**Comment by jywarren** [comment]
I see, thanks, I think I understand now.

**Comment by ujithaperera** [comment]
Yes without refreshing the page for 3 rd comment creation it creates 4 comments from the same comment. and for the 4th try it gives 8 comments. 
issue #413 is also occurred due to the same reason.

**Comment by ujithaperera** [comment]
according to my observation there are not handled form creations in notes#comment.html.erb with ajax calls

**Comment by jywarren** [comment]
Here it's important to distinguish between an error that happens while editing a comment (we'll call it an _AJAX comment_) that was just posted -- as it was created/inserted with AJAX -- and an error while editing a comment that was there on initial pageload (we'll call that a _non-AJAX comment). Let's be sure both work.

**Comment by jywarren** [comment]
This should be fixed; can you confirm and re-open if it is not? Thanks, esp. to @ujithaperera!
