### ISSUE TITLE
 Stats on a per-tag basis

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#4140]
Implement display of stats on a per-tag basis, via standard model functions with unit tests
* [ ] Move tag graphs to an individual page(this page) #4646 
* [ ] Display stats for each tag

**Comment by jywarren** [comment]
Noting that the tag graph we're looking to move off of individual tag pages (#4593) could be the very first feature of this page!

**Comment by jywarren** [comment]
![image](https://user-images.githubusercontent.com/24359/51339691-1220db00-1a5b-11e9-92d7-d17c68595d95.png)
