### ISSUE TITLE
First-timer poster tag script

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#4141]
Script to go back through posts and tag first-timer posts with first-time-poster tag

**Comment by cesswairimu** [comment]
@jywarren I see on the site we already have this tag `new contributor`.  Is this the same and we need to change the implementation or is it something else? Thanks

**Comment by jywarren** [comment]
oh, actually that's calculated differently i believe - here we want to know
if a given Node is the first post by a given author. Thanks!

https://github.com/publiclab/plots2/blob/d7e9fe8978c8e4a3cf42515c02f13a09aeace01a/app/models/user.rb#L64-L66
