### ISSUE TITLE
Link Login Modal to Research Note

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4151]
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to write a research note.
link- https://publiclab.org/post
plots2/app/views/sidebar/_related.html.erb

**Comment by SidharthBansal** [comment]
Published on GCI dashboard

**Comment by SidharthBansal** [comment]
@oorjitchowdhary are you willing to take this. I am just asking because you posted on large number of issues to taken up. No one is working on this. I guess you reported this. So, you can work on this.

**Comment by oorjitchowdhary** [comment]
Yes I can do it.. Actually I wasn't able to find issues which could be solved by me.. so I commented on a few

**Comment by oorjitchowdhary** [comment]
Found a good number of issues now.. So working towards them

**Comment by SidharthBansal** [comment]
We are here to help. Please be careful from next time. Long conversations makes difficulty on long run. I hope you will understand

**Comment by oorjitchowdhary** [comment]
@SidharthBansal The template mentioned to edit is wrong..
I think this template is for the `Share you work` button which has a dropdown of `write a note` and `ask a question` .. I'm unable to find the template which is for the notes page sidebar.. which looks like this..
![image](https://user-images.githubusercontent.com/39333058/49736360-e702d900-fcaf-11e8-9bcf-0e0f4e18e6b6.png)
Which has just `write a research note`

**Comment by SidharthBansal** [comment]
Take your time. Use grep command to search. This is a hint.

**Comment by SidharthBansal** [comment]
Yeah

**Comment by SidharthBansal** [comment]
@oorjitchowdhary this is one of the issues you claimed but have not sent a pr.
Commenting under an issue means you are working on it, in other words it means you have claimed it. I really appreciate your help. But as a mentor, my guidance would be to stay focussed to 3 issues at most. Please don't take more than 3 issues for atleast 3-4 months. It will make your initial journey very tough to Open Source if you will take on more than 3 issue. Generally, most of the organisations stick to 1 issue at a time because when we create multiple branches and do multiple PRs across different branches there are many risks of failures, bugs, etc. We will for sure give you an opportunity to tackle more PRs/issues together. But once GitHub will be habitual to you.
I hope you will not feel disheartened. Sorry in case you feel so.
We want your graph to open source will be linear with a positive slope. So, please complete those issues first which you have claimed(including this one)
Thanks for the amazing work which you are doing.

**Comment by oorjitchowdhary** [comment]
@SidharthBansal I'm really very sorry and promise this won't happen again. 
Here's my PR. #4414
