### ISSUE TITLE
Link Login Modal to follow a post

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4152]
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to follow a post
link - https://publiclab.org/notes/joyofsoy/11-09-2018/fighting-the-flood-community-activism-and-education-in-pensacola
        `app/views/users/_follow.html.erb`

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by SidharthBansal** [comment]
@dinaelhanan here is a screenshot
![image](https://user-images.githubusercontent.com/20972099/50399127-34e50a00-07a3-11e9-824e-977e6d687c60.png)

Can you see this font awesome icon?
![image](https://user-images.githubusercontent.com/20972099/50399135-45958000-07a3-11e9-90eb-847f053f50dd.png)

We need to link it to the correct place. Please do so. You worked at /blog instead of this.

**Comment by dinaelhanan** [comment]
@SidharthBansal I'm not sure I did it correctly, please checkout the PR I opened. Thanks for all the help!

**Comment by SidharthBansal** [comment]
OK thanks.
