### ISSUE TITLE
Login Modal to like wiki page

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4154]
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to like wiki page
link https://publiclab.org/wiki/lego-spectrometer

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by okonek** [comment]
@SidharthBansal I don't understand. What do we have to do there? COuld you explain a bit more?

**Comment by SidharthBansal** [comment]
We are currently building modal for login/signup. Check out the unstable.publiclab.org header
Try to do login. A modal will come. We need to integrate that modal to various pages.

**Comment by okonek** [comment]
Ok, now I understand. Thanks for the quick response. I'll take this task.

**Comment by SidharthBansal** [comment]
Thanks for claiming the task

**Comment by okonek** [comment]
@SidharthBansal Resolved in here: https://github.com/publiclab/plots2/pull/4186
Hope you'll have time to check it out.

**Comment by SidharthBansal** [comment]
@okonek like these you can do more 5 tasks. They are similar so, you will be able to do them quickly.
Also, you can create 5 more first timer issues from these tasks.
So total 10 more these link login modal to ______ can be done.

**Comment by SidharthBansal** [comment]
@okonek please submit both these issues for review. I will approve your changes.

**Comment by SidharthBansal** [comment]
May have conflicts due to #4209. We need to resolve them once it gets merged.

Unlike upon logging in a user does not work @okonek please see to it once #4209 is merged.

**Comment by SidharthBansal** [comment]
@kevinzluo can you please check this up and also make a pr in case it is needed. It is similar to the PRs you are submitting nowadays.

**Comment by SidharthBansal** [comment]
Thanks all.

**Comment by SidharthBansal** [comment]
Can you check what happens to the already liked wiki page when it is clicked while the user is not logged in?
In the PR merged there was code which is redundant now. We should delete them and use requireLogin class.

**Comment by oorjitchowdhary** [comment]
> Hey... The current behaviour on PL.org is
> 
> 1. click the like btn
> 2. login modal
> 3. successful login redirects to dashboard

Same behaviour if the user has already liked it and still clicks the like button when logged out

**Comment by SidharthBansal** [comment]
We need to see the state of liked.
If user has not liked it and clicks and then logs in this implies like count will increase.
If user has liked it already and clicks on like button then logs in through modal, it implies like count should decrease.
Does this makes sense?

**Comment by oorjitchowdhary** [comment]
I get it.. But I can't really test it.. I'm redirected to /dashboard everytime after a modal log in

**Comment by SidharthBansal** [comment]
Please check at localhost. PL.org has is much behind master.

**Comment by oorjitchowdhary** [comment]
Oh okay

**Comment by SidharthBansal** [comment]
OK great. So this is solved.
Let's close this.
Thanks Oorjit for your help.
