### ISSUE TITLE
Link Login Modal to power tag wiki page

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4155]
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to ``login ``text on https://publiclab.org/w/power-tags#Inline+power+tags
![image](https://user-images.githubusercontent.com/20972099/49620099-82acf480-f9e5-11e8-8d95-ff6c8957a159.png)

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by JonathanXu1** [comment]
Hi, is this accessible via localhost? I'm getting this:
![image](https://user-images.githubusercontent.com/22998430/49717872-6fd53280-fc26-11e8-84c8-897b92cef3ae.png)

If it's not I'd be happy to contribute to the code in the database!

**Comment by oorjitchowdhary** [comment]
Hi.. @SidharthBansal I've solved this one.. I'm submitting a patch

**Comment by oorjitchowdhary** [comment]
Just a little bit of help.. How can I add a tag to users on localhost

**Comment by oorjitchowdhary** [comment]
Okay.. I worked it out.. Patch coming up
