### ISSUE TITLE
Link Login Modal to Compose new answer on Answers on /questions

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4158]
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to Compose new answer on Answers on /questions
[publiclab.org/questions/](url)
`app/views/questions/_answer.html.erb`

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by oorjitchowdhary** [comment]
@SidharthBansal I think we can close this.. I think it was my mistake to point this out.. When you click `Post an answer`, you're taken to that particular question's page and there you get an option to write an answer which also has login/signup... and I fixed that one in #4213 

Here's the gif to show that

![post an answer](https://user-images.githubusercontent.com/39333058/49700802-8d47d380-fc09-11e8-9e28-deed526b5110.gif)

**Comment by SidharthBansal** [comment]
Oh got it.
Sorry
