### ISSUE TITLE
Link Login Modal to Flag button

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4159]
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to Questions page
publiclab.org/questions/
app/views/questions/show.html.erb
![image](https://user-images.githubusercontent.com/20972099/49638664-da238280-fa2e-11e8-9d78-6891ec926d60.png)

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by SidharthBansal** [comment]
On `post an answer button` and `flag as spam button` both

**Comment by SidharthBansal** [comment]
@okonek I think you are working on this in your prs. It is linked with #4220 what do you say?

**Comment by okonek** [comment]
But where exactly should we link the login modal in this asset? Could you explain a bit more? I'd like to take this task.

**Comment by SidharthBansal** [comment]
You need to do what @jywarren says.

**Comment by okonek** [comment]
Ok

**Comment by SidharthBansal** [comment]
Lets wait for @jywarren to comment

**Comment by okonek** [comment]
Ok, I understand everything now.

**Comment by okonek** [comment]
Resolved in here: https://github.com/publiclab/plots2/pull/4255

**Comment by SidharthBansal** [comment]
@IshaGupta18 I think this is solved in #4413 by your PR. If I am correct please feel free to close this issue.
Thanks
