### ISSUE TITLE
Link Login Modal to Subscribe Tags

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4160]
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to Subscribe/Follow Tags
[publiclab.org/tags/](url)
`app/views/tag/index.html.erb`

![screenshot 56](https://user-images.githubusercontent.com/39333058/49605767-6db96c80-f9b7-11e8-9ad2-643fb3b10ff3.png)

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by SidharthBansal** [comment]
I guess @okonek you are working on this issue. Am I right?

**Comment by kevinzluo** [comment]
I am not sure. It did not work with the other link that subscribed to a tag, so I have doubts :(. I will let you know after I am able to test it.

Thank you,
Kevin Luo

**Comment by SidharthBansal** [comment]
@kevinzluo have you tested it?
