### ISSUE TITLE
Link Login Modal to add an activity

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4161]
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to add an activity 
![image](https://user-images.githubusercontent.com/20972099/49620605-aa04c100-f9e7-11e8-9514-03868626a659.png)

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by kevinzluo** [comment]
Hello! I have claimed this task on the GCI dashboard. 

Just to confirm, once the user clicks this button -> login modal opens -> user logs in -> redirected to add activity page ?

**Comment by SidharthBansal** [comment]
>>button -> login modal opens -> user logs in -> redirected to add activity page

this is known as the basic flow.
You also need to check the alternative flow as follows
button -> login modal opens -> user doesn't log in -> redirected to login page with errors-> users logs in successfully -> redirected to add activity page

**Comment by kevinzluo** [comment]
I have been attempting this task and have come into a problem: How should I attempt to check if the user is logged in? `<% if current_user %>` returns an error saying `undefined local variable or method `current_user' `. 

Sorry, I'm a bit unfamiliar with rails but wanted to give this a shot.

**Comment by SidharthBansal** [comment]
See @oorjitchowdhary @okonek @dinaelhanan 's @JonathanXu1 's pr they will help you.
You don't need what you are thinking here.
I am going for a sleep. You guys can help each other and review each others pr. I will collective see all the work after 5-6 hours.

**Comment by kevinzluo** [comment]
You deserve some rest!

I am not sure what you mean by not needing to check if the user is logged in. All of their PRs already have the `<% if current_user %>` check in place, but mine does not. I am not sure how else to differentiate whether it should open the login modal (for non logged in user) or not (for logged in).

**Comment by SidharthBansal** [comment]
@kevinzluo please claim the task on the GCI dashboard so that I can give you rewards
