### ISSUE TITLE
Navbars should be on the same horizontal line

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4163]
Navbars should be on the same horizontal line
Check out https://publiclab.org/profile/warren
![image](https://user-images.githubusercontent.com/20972099/49621049-95c1c380-f9e9-11e8-90c7-2b4643cec808.png)

Mapknitter is on the next line

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by jywarren** [comment]
This could be solved by using Bootstrap classes to hide the text (leaving
only the icon) for narrower width screens!

**Comment by oorjitchowdhary** [comment]
@publiclab/mentors Can I make this a `first-timers-only` issue?

**Comment by SidharthBansal** [comment]
Yeah sure. Once you create a first timer, please claim the task so that I can reward you.

**Comment by JonathanXu1** [comment]
Hey there, this task is still available on GCI. Can you guys add the "beginner" tag to it to reduce confusion?

**Comment by SidharthBansal** [comment]
Link for the GCI issue please

**Comment by kevinzluo** [comment]
I believe it is this one: https://codein.withgoogle.com/tasks/5066725092491264/?sp-organization=6519545549291520&sp-is_beginner=False

**Comment by oorjitchowdhary** [comment]
@SidharthBansal I think we can close this down.. I opened #4189

**Comment by SidharthBansal** [comment]
@JonathanXu1 I have added beginner label.
Thanks
