### ISSUE TITLE
Suggestion: Follow people on Public Lab

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4164]
Many websites allow users to follow each other and form web. By this people will be able to know what their friends are doing. @ebarry @jywarren @publiclab/mentors what do you suggest?

**Comment by SidharthBansal** [comment]
@jywarren I have created a new label ``brainstorm`` for requirement elicitation issues.

**Comment by oorjitchowdhary** [comment]
Yes, I think that's a great idea.. We've `follow` for tags and that is used widely... I think we should implement `follow` for people too..

**Comment by SidharthBansal** [comment]
@oorjitchowdhary This issue need not be implemented until @jywarren @ebarry agrees upon it.

**Comment by SidharthBansal** [comment]
@gauravano @jywarren is this functionality already made?
I could not find it.

**Comment by SidharthBansal** [comment]
Hi @shubhscoder we need to first take input from @jywarren whether this issue needs to be further explored or not. He is right now busy, you can work on other issues if you want.
Thanks @shubhscoder

**Comment by jywarren** [comment]
Much of the following code is named `----Selection` - like `NodeSelection` for liking nodes, `TagSelection` for following tags. We have a `UserSelection` area but I don't know if it's hooked up to work! 

https://github.com/publiclab/plots2/search?q=UserSelection

Looks like not! Most of the code is here:

https://github.com/publiclab/plots2/blob/5c0d96274bd0be15feba69d8f30093082402ace5/app/models/user_selection.rb

It doesn't really look like it was ever built out: https://github.com/publiclab/plots2/commits/5c0d96274bd0be15feba69d8f30093082402ace5/app/models/user_selection.rb

But if you search for the TagSelection and NodeSelection code, you can see how they are set up. I hope that helps! We'd have to modify the `notify` methods to ensure we are notifying everyone, but not more than once. That code is pretty thoroughly tested so we should be able to monitor carefully what new code does to change the behavior.

**Comment by jywarren** [comment]
Much of the following code is named `----Selection` - like `NodeSelection` for liking nodes, `TagSelection` for following tags. We have a `UserSelection` area but I don't know if it's hooked up to work! 

https://github.com/publiclab/plots2/search?q=UserSelection

Looks like not! Most of the code is here:

https://github.com/publiclab/plots2/blob/5c0d96274bd0be15feba69d8f30093082402ace5/app/models/user_selection.rb

It doesn't really look like it was ever built out: https://github.com/publiclab/plots2/commits/5c0d96274bd0be15feba69d8f30093082402ace5/app/models/user_selection.rb

But if you search for the TagSelection and NodeSelection code, you can see how they are set up. I hope that helps! We'd have to modify the `notify` methods to ensure we are notifying everyone, but not more than once. That code is pretty thoroughly tested so we should be able to monitor carefully what new code does to change the behavior.

**Comment by SidharthBansal** [comment]
Oh this is really cool. We have another project to work upon. Let's start this up.
@shubhscoder as per https://github.com/publiclab/plots2/issues/4164#issuecomment-449560828 please go ahead.
Thanks everyone!!!

**Comment by shubhscoder** [comment]
@SidharthBansal 
I think this feature is already implemented. I have attached some screenshots regarding the same! 
![people_who_follow_user](https://user-images.githubusercontent.com/18489285/50382397-37bcfd80-06c4-11e9-9690-c9b28b717861.png)
![unfollow_feature](https://user-images.githubusercontent.com/18489285/50382398-37bcfd80-06c4-11e9-9fc5-b5d0c65a599a.png)
![people_i_follow](https://user-images.githubusercontent.com/18489285/50382401-43a8bf80-06c4-11e9-881c-daf7da413c48.png)
![follow_feature](https://user-images.githubusercontent.com/18489285/50382402-44415600-06c4-11e9-99e0-bbd648ae086c.png)

**Comment by SidharthBansal** [comment]
So, users can follow each other. Are they getting any notifications regarding their followers?
If a person is following someone then they must get the notifications. Can you please check this?
We are currently having email notification system at PL.

**Comment by shubhscoder** [comment]
Ok I will check that out !

**Comment by shubhscoder** [comment]
@SidharthBansal The notification system has not been implemented. I will start working on that now. Thank you!

**Comment by SidharthBansal** [comment]
Great!!!

**Comment by gauravano** [comment]
This one is interesting. @shubhscoder let me know if you need any help. Thanks!

**Comment by shubhscoder** [comment]
@gauravano I have made a PR for this. Can you please check if everything is good or we need some more additions? Thank you so much!

**Comment by jywarren** [comment]
I believe this is now implemented, and am closing, but if folks could test it out that would be great! #6190
