### ISSUE TITLE
Link Login Modal to Spam on wiki pages

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4165]
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to Spam on wiki pages
![image](https://user-images.githubusercontent.com/20972099/49621189-1aacdd00-f9ea-11e8-98bf-ba627459e8a1.png)
On clicking on the spam icon, modal should be shown

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by JonathanXu1** [comment]
Hi there, I'd like to work on this. I've found 7 instances of the spam button:
![image](https://user-images.githubusercontent.com/22998430/49710012-0133ad00-fc05-11e8-9d58-20a9ba87fc1c.png)
Which one would you like me to work on?

**Comment by SidharthBansal** [comment]
Hi Jonathan @okonek is working on this. Please take another issue.

**Comment by gauravano** [comment]
Agree with @jywarren . The flag button prepares a prewritten email to moderators and nothing else so need of login is required. Thanks!

**Comment by gauravano** [comment]
So, closing this issue and related PR #4252. Thanks!
