### ISSUE TITLE
Link SignUp Modal to Sidebar on wiki pages

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4168]
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to Sidebar on wiki pages
![image](https://user-images.githubusercontent.com/20972099/49637543-a6932900-fa2b-11e8-9e3c-1ef53241f121.png)

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by JonathanXu1** [comment]
Hi there, could I get a pointer to the location of the sidebar layout?

**Comment by SidharthBansal** [comment]
@jonathanXu1 I will request you to focus on atmost 2-3 issues at a time. You have already so many at this time. Can we do this after you complete your pending work

**Comment by SidharthBansal** [comment]
No problem. We discourage more than 3 tasks because it becomes hectic for a student.
>>Hi there, could I get a pointer to the location of the sidebar layout?

I hope it will be in 
https://github.com/publiclab/plots2/tree/master/app/views/sidebar

**Comment by oorjitchowdhary** [comment]
So can I take this up?

**Comment by oorjitchowdhary** [comment]
Though I can't find any login button in the sidebar.. Do we want to add one?

**Comment by SidharthBansal** [comment]
We will be integrating the Sign up module once it is ready.

**Comment by SidharthBansal** [comment]
@oorjitchowdhary no you can't @JonathanXu1 is working on this.
@JonathanXu1 now you can try submitting these login modal linking issues. Atmost 5 per candidate as these are similar.
Also, you can create 5 ftos for these types of tasks. Please provide the gifs for these tasks in the ftos created. So total you can carry around 10 these kind of tasks.(5first timers only and 5 prs). They are not small as they require testing on the unstable, localhost both with the identification of correct file for the pr.
Please use first timers only template for these kind for them. https://docs.google.com/document/d/1dO-CAgModEGM5cOaMmcnBh2pEON0hv_rH3P2ou2r1eE/edit.
@dinaelhanan @okonek and all other GCI students are also informed for them.

**Comment by SidharthBansal** [comment]
@oorjitchowdhary you can work on other similar tasks

**Comment by geekychaser** [comment]
@jywarren @SidharthBansal do i need to create a signup/log in button in sidebar for wiki pages ?

**Comment by geekychaser** [comment]
@SidharthBansal I think signup button is working perfectly do we need to add a log in button?

**Comment by geekychaser** [comment]
@SidharthBansal i am not able to get this on my local server 
![image](https://user-images.githubusercontent.com/24489162/50682629-7ee8ae00-1035-11e9-9850-7552dfb9ad72.png)

**Comment by oorjitchowdhary** [comment]
@geekychaser You need to create a research note and add some tags... This sidebar should appear on the notes page then

**Comment by geekychaser** [comment]
![image](https://user-images.githubusercontent.com/24489162/50683470-3088de80-1038-11e9-923f-a2a0c8c52b7d.png)


please correct me if i am wrong.
thank you

**Comment by geekychaser** [comment]
@jywarren @SidharthBansal i am not able to locate this button on my local server.
thank you

**Comment by jywarren** [comment]
Aha - so, this is run from Features, in the database (see the DATA_MODEL.md docs file). I've now changed it from the interface at /features.

Thank you!!!

**Comment by SidharthBansal** [comment]
Thanks Jeff
