### ISSUE TITLE
Link Login Modal to dashboard Ask a question

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4169]
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to dashboard Ask a question
![image](https://user-images.githubusercontent.com/20972099/49637721-36d16e00-fa2c-11e8-95ce-3f679eef19e8.png)

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by SidharthBansal** [comment]
We are looking for the sign up modal first then these linking issues. Once @JonathanXu1 you complete it we can work on these issues
These linking issues are short if we see the number of lines of code to be changed but lenghty if we see the amount of time, testing etc each requires. Hence I have not made them beginner tasks @jywarren. I hope you will agree on this.

**Comment by SidharthBansal** [comment]
>>I'm wondering how the UI for that would work, since that button would redirect the user to https://publiclab.org/questions

1. Click on the /questions button
2. Login/Sign up integrated modal
3. User signs up or logs in through form or OAuth
4. User redirected to the questions page.

**Comment by oorjitchowdhary** [comment]
This dashboard isn't available on localhost..

![image](https://user-images.githubusercontent.com/39333058/49702437-094c1680-fc1e-11e8-941d-b79c58403048.png)

This is the dashboard which is available on `plots2` local dev

**Comment by jywarren** [comment]
The front page content is stored in a database Feature (see our data model)
which is a special type of node. So it's not present in the codebase. We
have a proposal for a javascript means of triggering a modal login, which
would make it possible to insert such prompts into db-driven text, such as
nodes!

**Comment by SidharthBansal** [comment]
If anyone wants to take on this. Then please tell. I will assign him/her the task

**Comment by mittalprince** [comment]
@SidharthBansal  but the dashboard is not available on my local.

**Comment by oorjitchowdhary** [comment]
Hi all, I just took a look at this one.. I don't think we need to add the login modal here as when we click the `ask a question` button, we're redirected to /questions and we do not require a login
So should I close this?

**Comment by SidharthBansal** [comment]
Thanks Oorjit
