### ISSUE TITLE
 Imagemagick installation on a cloud9

### ISSUE THREAD

**Issue by jiteshjha** [publiclab/plots2#417]
### What happened just before the problem occurred
During the installation process on Cloud9, 
after ``` sudo apt-get install imagemagick ruby-rmagic ```
I get this in the bash terminal -

``` 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package imagemagick is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'imagemagick' has no installation candidate
E: Unable to locate package ruby-rmagick 
```

### Relevant URLs

https://

### PublicLab.org username
jiteshxyz
(to help reproduce the issue)

### Browser, version, and operating system
Firefox - 44
Ubuntu 15.04

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by jywarren** [comment]
Hi, can you post a link to your issue on the plots-dev discussion list?
Other students were able to get it running so I am guessing they can help
troubleshoot. Then we can add to or update the docs.

Thanks!

**Comment by jywarren** [comment]
Ah i see your fix, please hang on a sec.
