### ISSUE TITLE
Link Login Modal to Join Now on dashboard

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4170]
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to Join Now on dashboard
![image](https://user-images.githubusercontent.com/20972099/49637912-b3644c80-fa2c-11e8-8935-f8db5377b7bd.png)

**Comment by SidharthBansal** [comment]
Published on the gci dashboard

**Comment by JonathanXu1** [comment]
Just wondering, is the codebase for this available on plots2 or another repository? On plots2 localhost all I can see is this: 
![image](https://user-images.githubusercontent.com/22998430/49689041-11ef0080-fae9-11e8-97bf-a74cbcb681ba.png)

**Comment by JonathanXu1** [comment]
Sure, I'd like to work on this 👍 
Just wondering, is the codebase for this available on plots2 or another repository? There's no welcome prompt on localhost

**Comment by SidharthBansal** [comment]
Sure you can work on this but this needs to be linked with integrated signup login modal. So you need to stuff there first.

**Comment by SidharthBansal** [comment]
On investigating it, I found that Join Now links to a static page pl.org/join.
We don't need to fix this.
