### ISSUE TITLE
Styling missing on 2nd page of comments on profile

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4174]
This looks like the layout is being suppressed in the `user_controller`!

https://publiclab.org/profile/comments/423961?page=4

![image](https://user-images.githubusercontent.com/24359/49668809-4c936300-fa2d-11e8-9891-c389a9587519.png)

**Comment by oorjitchowdhary** [comment]
I think the first comments page loads on the normal /profile page so it has the styles but rest all are empty.. 
I think we can use the same styles here as I did in my PR #4143 ..

**Comment by SidharthBansal** [comment]
I agree with @oorjitchowdhary we should use same styles.
@oorjitchowdhary are you willing to take this?

**Comment by oorjitchowdhary** [comment]
Yes.. I'll do this.. Could I just get a pointer on the code file of this.. Thanks

**Comment by jywarren** [comment]
Oh, i think the styles already exist, this page is just getting rendered
without a layout, so it misses the CSS links and beginning and end of the
page HTML.  Maybe check in the `profile` action in the user_controller to
see if you can find it saying `layout: false` for anything?

**Comment by oorjitchowdhary** [comment]
@SidharthBansal @jywarren

**Comment by jywarren** [comment]
That's the kind of "no format" that causes this, but that one is for the
RSS feeds. Maybe could be good to use the Google Dev console to see exactly
what request is sent when this page is loaded, locally. Then we could try
to figure out why it's not rendering a layout. Thanks!

**Comment by oorjitchowdhary** [comment]
Can anyone else take this.. 
Sorry, I'm unable to find a fix for this..

**Comment by madeofhuman** [comment]
I can look at this.

**Comment by gauravano** [comment]
@madeofhuman that would'be great. Thanks!

**Comment by madeofhuman** [comment]
@jywarren I've raised a PR for this. Could you please go through it and tell me if it's how it's supposed to work? Thanks.
