### ISSUE TITLE
Quoted email body text ignoring `_(underscore)` in email

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4178]
![image](https://user-images.githubusercontent.com/20972099/49676571-3ecaf580-faa0-11e8-8b33-fdc6fba9a617.png)

See that @bansal_sidharth2996 is broken at underscore(_). We need to fix it.

**Comment by gauravano** [comment]
Hi @SidharthBansal, actually your name is tagged in the comment as you can see - https://publiclab.org/notes/cess/10-24-2018/outreachy-proposal#c20953 . But, yes it is not shown tagged in the quoted mail text, but I think we can ignore that. What do you think?

 cc @SidharthBansal @namangupta01 @jywarren

**Comment by gauravano** [comment]
Feel free to close this issue, if any of you thinks, the issue doesn't need that attention. thanks!

**Comment by SidharthBansal** [comment]
The issue needs attention. I reported this in mailer issue.

**Comment by SidharthBansal** [comment]
codelink must be inside config/initializer

**Comment by jperk224** [comment]
Hi, I'm looking for a decent `fto-candidate` issue to work on.  Is this one available for grabbing?

**Comment by cesswairimu** [comment]
I create a username with an underscore locally and  triggered a few emails tagging the name and subscriptions, It works well locally on the email template -- this may be have been fixed at some point. Closing this for now, anyone feel free to reopen if you experience the issue. Thanks all.
