### ISSUE TITLE
Integrate Sign Up and Login Modals

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4184]
There are two options
1. We will have two separate buttons throughout the website. One for signup and one for login. With the login, we will attach the login modal and with the signup we will attach the signup modal.
As the user needs to open up the sign up modal once in their lifetime, the modal will usually be short as it will be login modal. Once the modal will be lengthy at the time of sign up.
2. We will integrate the login and the signup modal into one modal. Next, we will change login and signup option both with single option `login/signup` which links to the modal.
This will result in users to see large modals each time due to signup.
Most websites have integrated signup/login modal, what do you say @oorjitchowdhary @JonathanXu1 @jywarren ?

**Comment by oorjitchowdhary** [comment]
>    As the user needs to open up the sign up modal once in their lifetime, the modal will usually be short as it will be login modal. Once the modal will be lengthy at the time of sign up.

I didn't understand this.. 

> 2. We will integrate the login and the signup modal into one modal. Next, we will change login and signup option both with single option `login/signup` which links to the modal.
>    This will result in users to see large modals each time due to signup.

Yes that sounds great

**Comment by SidharthBansal** [comment]
>I didn't understand this..

We can have two different modals for sign up and login

**Comment by CoderJolly** [comment]
@SidharthBansal Can someone else also take this, other than GCI ?

**Comment by SidharthBansal** [comment]
@CoderJolly this task needs to be done after Sign Up and @JonathanXu1 is working on this task.
@CoderJolly only GCI students can take GCI tasks.

**Comment by SidharthBansal** [comment]
@JonathanXu1 can you please share the gifs which you are planning for this issue.
We can enhance it here side by side until that pr isn't merged

**Comment by JonathanXu1** [comment]
Here's the gif of the current version of login and signup modals that I'm working on:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22998430/49691997-06b5c800-fb1d-11e8-9762-ce35ec3b2c61.gif)

Keep in mind that the signup modal only works on the /signup page.

**Comment by SidharthBansal** [comment]
I am asking you what are you planning for integrated view.
I know the current state. Sorry, for the misunderstanding

**Comment by JonathanXu1** [comment]
I'm thinking we have the current login modal pop up when the button is clicked. Then, when the user clicks "or sign up", the contents change to the signup modal. What do you think?

**Comment by oorjitchowdhary** [comment]
@JonathanXu1 That seems great

**Comment by SidharthBansal** [comment]
Sounds perfect

**Comment by SidharthBansal** [comment]
You need to do two things
sign up should redirect back to the login modal 
Login modal linked to the sign up modal.

**Comment by SidharthBansal** [comment]
@JonathanXu1 for wide variety of issues which we have created, in those then login modal can be linked.
What do you say?

**Comment by JonathanXu1** [comment]
> sign up should redirect back to the login modal

> in those then login modal can be linked

Sorry could you clarify this?

**Comment by SidharthBansal** [comment]
We have a login button on the signup modal, we need to link it to the login modal. On clicking on that button it should close the signup modal and open up the login modal.
And other action is completely opposite of it.

**Comment by oorjitchowdhary** [comment]
> We have a login button on the signup modal, we need to link it to the login modal. On clicking on that button it should close the signup modal and open up the login modal.
> And other action is completely opposite of it.

Yess

**Comment by oorjitchowdhary** [comment]
Also, @SidharthBansal Can I start working on the link login modal issues?

**Comment by SidharthBansal** [comment]
Yeah sure.

**Comment by JonathanXu1** [comment]
Oh I see. Can I implement this issue in the signup modal branch we're working on since we have both signup and login modals appearing there?

**Comment by SidharthBansal** [comment]
It will be great if you will be pushing changes in the same pr.

**Comment by SidharthBansal** [comment]
Or create a new pr with those changes and close my pr.

**Comment by JonathanXu1** [comment]
I can push the changes to my existing pr if you'd like. It's closed though.

**Comment by SidharthBansal** [comment]
Then you create a new pr. Link it to my pr. Close my pr.
Paste in the whole checkboxes list of @oorjitchowdhary and yours combined there.
We need to check all of them before the pr is ready to be merged.

**Comment by SidharthBansal** [comment]
In the new pr created please first rebase it to the master
and have same identical changes of my pr first. Then I will review it. Once you get the :+1: you can start working on the integration part.
Does it makes sense?

**Comment by JonathanXu1** [comment]
I've added it here: https://github.com/publiclab/plots2/pull/4209. Also I don't think I have permission to close #4203 
Can I start on the integration work?

**Comment by SidharthBansal** [comment]
Yeah sure.
