### ISSUE TITLE
Navbars should be on the same horizontal line

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4189]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all) made from #4163. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [profile.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/users/profile.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

## Issue
The navbar tabs are currently spread out in 2 lines, whereas it should be on the one same horizontal line.

![image](https://user-images.githubusercontent.com/39333058/49688486-075c5780-fb39-11e8-8732-992924c03094.png)

## Code link
https://github.com/publiclab/plots2/blob/master/app/views/users/profile.html.erb#L43-L119

## Solution
This can be solved by using Bootstrap classes to hide the text (leaving
only the icon) for narrower width screens!

You can visit [https://getbootstrap.com/docs/3.3/](url) for reference. 

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by professionalzack** [comment]
I would like to work on this issue thanks

**Comment by arungoel123456** [comment]
@professionalzack  are u working on it ??

**Comment by oorjitchowdhary** [comment]
@arungoel123456 @professionalzack If you guys are willing to collaborate this one.. you're most welcome.. 😃 
Otherwise, @arungoel123456 you can check out https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3Afirst-timers-only for issues which are meant to be solved by `first-timers`..

Welcome to Public Lab! 🎉

**Comment by arungoel123456** [comment]
@professionalzack  would u like to collaborate

**Comment by oorjitchowdhary** [comment]
> i am not exactly sure how to share the PR in here, but i've made one. here is the link (i think):
> [professionalzack#1](https://github.com/professionalzack/plots2/pull/1)

@professionalzack I just took a look here.. You actually created a pull request in your own fork of the repository..

You've to commit changes in the `publiclab/plots2` repository.. To do that here are the steps you can follow.. And ping me on the pull request if you've any doubts.. Thanks a lot.. 

> * [ ]  💾 **Commit** your changes
> * [ ]  🔀 **Start a Pull Request**. There are two ways how you can start a pull request:
> 
> 1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
> 2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

**Comment by SidharthBansal** [comment]
@arungoel123456 as this is a small task, you should take another issue and let @professionalzack work on this one alone

**Comment by professionalzack** [comment]
Hi sorry, I have been out of the house. I had a couple confusions here but seemed to have squared it away. Just waiting to see if the PR is accepted.
Thanks !

**Comment by rexagod** [comment]
Hey I'd like to claim this issue please!

**Comment by oorjitchowdhary** [comment]
@rexagod I think @professionalzack may have already solved this one.. 
You can take a look at #4270 if you want.. Else go to https://github.com/publiclab/plots2/labels/first-timers-only for all the first timers only issue..
Thanks

**Comment by rexagod** [comment]
@oorjitchowdhary I've submitted a claim request at #4270 as well.

**Comment by Harshithpabbati** [comment]
Can i work on this???

**Comment by gauravano** [comment]
Hi @Harshithpabbati, as the PR raised against this issue is abandoned, you can work on this one. Thanks!

**Comment by Harshithpabbati** [comment]
I sent the pr

**Comment by NidhiKJha** [comment]
Hi, I'm an outreachy aspirant, can I work on this issue?

**Comment by Harshithpabbati** [comment]
Yeah continue with it :)

**Comment by uimarshall** [comment]
Hi, i am in the current outreachy program, can i work on this issue, if it is not claimed yet?

**Comment by jywarren** [comment]
Hi, all - actually we try to have one person solve an issue at a time, and we'll be posting more first-timers-only issues soon! Thank you and sorry we don't have quite enough yet! However, if you find one that hasn't been worked on for some time, ask there if you could pitch in to complete it!

**Comment by gauravano** [comment]
Hi everyone!

This issue seems to be resolved :point_down: 

![solved_issue](https://user-images.githubusercontent.com/20878070/54278274-f0098c00-45b7-11e9-95b7-71aae088f495.png)

This is view from @jywarren's PL profile - https://publiclab.org/profile/warren

So, closing this issue for now. Thanks!
