### ISSUE TITLE
Disable login modal in embedded grids

### ISSUE THREAD

**Issue by JonathanXu1** [publiclab/plots2#4191]
This issue is a continuation of #4132 

On each individual listing on the public lab store, there is an option to ask a question.
![image](https://user-images.githubusercontent.com/22998430/49688788-55477000-fae5-11e8-941e-97ff6fe2a9a2.png)

We want to make a login modal pop up when that button is clicked, instead of opening up a dialog of an entire site in that pane, which is highly inefficient.

Example listing: https://store.publiclab.org/collections/featured-kits/products/papercraft-spectrometer-intro-kit?variant=6100877213724

**Comment by SidharthBansal** [comment]
@jywarren do we need this issue OR not because it's part of store?

**Comment by SidharthBansal** [comment]
You have already got points for this task

**Comment by jywarren** [comment]
Ah, this is interesting. Actually because the store uses an iFrame, maybe we need to disable the modal code when in the "embedded" view, which uses this route:

http://publiclab.org/embed/grid/nodes:purpleair

**Comment by jywarren** [comment]
Because the modal would appear in the iframe which would be pretty squished... but worth trying to test it out!

**Comment by SidharthBansal** [comment]
Is anyone on it? Or willing to do after some time?

**Comment by SidharthBansal** [comment]
If @jonathanxu1 you want to do after your integrating modal task, then we can reserve this for you.
Please comment if you wish to.
Thanks Jeff for your input

**Comment by JonathanXu1** [comment]
I'd love to work on it after I finish integrating the modal. Thanks for bringing this up!

**Comment by SidharthBansal** [comment]
Great

**Comment by SidharthBansal** [comment]
@oorjitchowdhary I think this is solved. You did some changes related to this.
Is it solved? Can you please check thanks.

**Comment by oorjitchowdhary** [comment]
I want to check the behaviour but I'm unable to replicate the grid on localhost. How can I add the grid to my notes on localhost?

**Comment by SidharthBansal** [comment]
I have shared a post. Please check it up.

**Comment by oorjitchowdhary** [comment]
On the questions grid on PL.org, the login modal is showing up...
but on the store, it is still redirected to login page

**Comment by SidharthBansal** [comment]
So let's complete this.

**Comment by SidharthBansal** [comment]
> but on the store, it is still redirected to login page

Store is not part of plots2 codebase. So I think we can close this.
