### ISSUE TITLE
Add login modal to subscribe to emails button

### ISSUE THREAD

**Issue by JonathanXu1** [publiclab/plots2#4192]
This issue is a continuation of #4132 

On the requests page, there is a button to subscribe to emails:
![image](https://user-images.githubusercontent.com/22998430/49688805-b8d19d80-fae5-11e8-9534-98dd0d7ad6f7.png)

However that cannot be done unless a user is logged in, so a warning popup is shown. What we want to do is make a login modal appear when the button is clicked and the user is not logged in.

Link: https://publiclab.org/wiki/requests

**Comment by JonathanXu1** [comment]
@SidharthBansal where can one find the partial for the subscribe button?

**Comment by SidharthBansal** [comment]
Patiala are present in the app/views folder check them there

**Comment by SidharthBansal** [comment]
Partials I mean

**Comment by JonathanXu1** [comment]
Ok.
I'm using 
```
<% if current_user %> 
   a
<% else %>
   b
<% end %>
```
to check if a user is logged in. However, a runs even if the user is logged out. Also is there a way to route the page back to the current one when the login is successful?

**Comment by SidharthBansal** [comment]
Integrated modal testing
Please submit this task for review I should approve it now.

**Comment by SidharthBansal** [comment]
>to check if a user is logged in. However, a runs even if the user is logged out. Also is there a way to route the page back to the current one when the login is successful?

Please look at @okonek's PR of linking like buttons it will help you

**Comment by SidharthBansal** [comment]
#4186

**Comment by SidharthBansal** [comment]
Please submit a PR for the rewards. I have already rewarded for the identification of this task in #4132

**Comment by SidharthBansal** [comment]
@JonathanXu1 you have received points for these suggestions. It is part of identication issue #4132

**Comment by JonathanXu1** [comment]
https://github.com/publiclab/plots2/pull/4209#issuecomment-445678224
Sorry I believe I misunderstood your statement. I thought it was one task per fto issue created.

**Comment by SidharthBansal** [comment]
If you create a first timer issue with full fledged solution and the first timer template then you will get rewards.
Is it now clear?

**Comment by JonathanXu1** [comment]
Oh I see. So all I have to do is provide an example solution for my fto issues regarding the modal?

**Comment by SidharthBansal** [comment]
You can provide it if you want.
If you want to send us a pr. Then you can also do that.

**Comment by jywarren** [comment]
Just a note that this button is stored in the node body, not in the
codebase. Still a great idea! Just may require either some clever filtering
of body content or some kind of shortcode to show a subscription button?

**Comment by JonathanXu1** [comment]
@jywarren I think this might be similar to https://github.com/publiclab/plots2/issues/4170
Is it possible for us to get a copy of the node body and submit that to complete the task?

**Comment by jywarren** [comment]
if you click the edit button you'll be able to see the raw body -- try it!

**Comment by SidharthBansal** [comment]
@JonathanXu1 how is it going?
Do you need any help?

**Comment by SidharthBansal** [comment]
@Dsxv you were asking for issues to be assigned to you.
Do you want to do this?

**Comment by Dsxv** [comment]
@SidharthBansal Yes I'd love to take this up ! sorry for late reply .
 Thanks !

**Comment by SidharthBansal** [comment]
@Dsxv how is it going here?

**Comment by SidharthBansal** [comment]
https://github.com/publiclab/plots2/blob/master/doc/LOGIN_SYSTEMS.md will help you.
See requireLogin class.

**Comment by Dsxv** [comment]
Yes, I'm sorry for the delay , I'll create a PR asap

**Comment by SidharthBansal** [comment]
No problem. It is similar to the last PR which you did.

**Comment by SidharthBansal** [comment]
You have to create a similar page on the local host by going to /wiki/new.

**Comment by Dsxv** [comment]
Yes , but how should I add the `subscribe to email` button ? 
Thanks!

**Comment by SidharthBansal** [comment]
Hi, I am really Sorry Pawan for not telling you that this issue is fixed.
Oorjit fixed it. There are many PRs/issues related. His solution aimed to fix grids which fixed this also.
Once the changes will be published everything will work fine on the production branch.
Thanks Pawan for help.
