### ISSUE TITLE
Login modal on join public lab link

### ISSUE THREAD

**Issue by JonathanXu1** [publiclab/plots2#4193]
This issue is a continuation of #4132 

On the https://publiclab.org/research page, there is a link that says "Welcome! This could be your dashboard if you joined Public Lab"
![image](https://user-images.githubusercontent.com/22998430/49688809-d3a41200-fae5-11e8-9b45-c2122f996219.png)

What we want to do is to make a login modal appear when that link has been clicked.

**Comment by dinaelhanan** [comment]
I will take this! @SidharthBansal is this on GCI? and @JonathanXu1 where would I link/add an event to the link to the modal? Never worked on the login modals so any help if appreciated :)

**Comment by SidharthBansal** [comment]
This issue is to be done after we complete the integration of models. So,
please wait.

**Comment by SidharthBansal** [comment]
@dinaelhanan you can now start working on these issues.

**Comment by SidharthBansal** [comment]
@JonathanXu1 same applies to you and @okonek and @oorjitchowdhary and other contributors

**Comment by SidharthBansal** [comment]
We have @okonek pr. Please review it. I am sure you will find what is supposed work.

**Comment by dinaelhanan** [comment]
ok @SidharthBansal thanks!

**Comment by dinaelhanan** [comment]
@SidharthBansal I am running the site and it is not working (I cannot click the button I wrote) is this because this PR is not merged? #4186

**Comment by SidharthBansal** [comment]
@JonathanXu1 you have received points for these suggestions. It is part of identication issue #4132
