### ISSUE TITLE
Link login modal to 'post your work' under 'Get Involved' tab

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4194]
Link the newly added login modal here at `Post your work` under the `Get Involved` tab.

![publiclab_adiyenvironme](https://user-images.githubusercontent.com/39333058/49689090-21e6fe80-fb42-11e8-9f0e-497fe0b5476c.gif)

**Comment by JonathanXu1** [comment]
I think I've fixed this in #4240. Please let me know if it's good.

**Comment by SidharthBansal** [comment]
Issue fixed.

**Comment by oorjitchowdhary** [comment]
@SidharthBansal I just saw the conversation at #4209 .. I think I haven't credits for creating the issues.. I got rewards for identification which was #4132 .. but I also created #4194 and #4218 and #4120 a while back.. So am I eligible for credits on these issues?

**Comment by SidharthBansal** [comment]
Creation of the issues and identification both are included in the same task. You have got credits equally as others have got.
Actually I approved the pr before I asked you to create issues.
I am checking it again. In case I will find any task upon which you were not credited for sure I will link the dashboard task link so that you can review.

**Comment by oorjitchowdhary** [comment]
Okay thanks a lot 👍 😄

**Comment by SidharthBansal** [comment]
Other people have identified tasks other than the login modal. 
Basically the scheme is
1 point for identification of login related taskS with the issue list.
1 point for each task you solve for the login modal
1 point for any other suggestion apart from login modal or any bug
1 point for bug fix 
So, if you want more points in these linking tasks, please identify more buttons across the website and sent the pr. I hope you are not angry and it is fair. I paid special attention while giving all of you rewards.

**Comment by oorjitchowdhary** [comment]
> Other people have identified tasks other than the login modal.
> Basically the scheme is
> 1 point for identification of login related taskS with the issue list.
> 1 point for each task you solve for the login modal
> 1 point for any other suggestion apart from login modal or any bug
> 1 point for bug fix

Okay .. I understand
> So, if you want more points in these linking tasks, please identify more buttons across the website and sent the pr. I hope you are not angry and it is fair. I paid special attention while giving all of you rewards.

Yes.. I'm not at all angry.. I'm just amazed working with Public Lab 👏

**Comment by SidharthBansal** [comment]
https://codein.withgoogle.com/dashboard/tasks/6663508033798144/ here is the task for which you will get rewarded.

**Comment by oorjitchowdhary** [comment]
Yes .. Just approve my previous so I can claim this

**Comment by SidharthBansal** [comment]
Already approved

**Comment by oorjitchowdhary** [comment]
Oh thank you .. 😄

**Comment by oorjitchowdhary** [comment]
@SidharthBansal Can I work on this? Or do I have any more pending issues

**Comment by SidharthBansal** [comment]
Please check your github linked gmail. If you have completed all other tasks claimed then go for it.
Just I want you to be focussed. Its better to learn a topic then to have overview of all the headings present in the book. Please solve things piece by piece. It will create your job very easy.
**You can work on this one!!!**
Thanks

**Comment by oorjitchowdhary** [comment]
Is this getting solved in #4240 ?

**Comment by JonathanXu1** [comment]
Yeah, I'm just trying to install public lab on my local machine to verify if the routing works. Everything else works.
