### ISSUE TITLE
Merge SignUp and LogIn buttons

### ISSUE THREAD

**Issue by JonathanXu1** [publiclab/plots2#4195]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem
On https://publiclab.org/ , you can see that there are separate LogIn and SignUp buttons in the navbar:
![image](https://user-images.githubusercontent.com/22998430/49689182-82971c80-faeb-11e8-9d21-56e0abbf8887.png)

What we're trying to do is to merge these two buttons into a singular one, persay "LogIn/SignUp". Upon clicking that, we'll display the login modal for now. When the SignUp modal and LogIn modal are integrated into one, we can update the modal in another pull request.

The file to modify:
app/views/layouts/_header.html.erb

### 📋Solution

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by oorjitchowdhary** [comment]
@sidharthbansal can I merge the buttons for now? I can then help out @jonathanxu1 for integrating the sign up modal with the login modal

**Comment by oorjitchowdhary** [comment]
So I've made the changes.. but will release the patch if I have your consent @SidharthBansal ...

**Comment by SidharthBansal** [comment]
@oorjitchowdhary please relax for some time. You know that this is a first timers only issue and you cannot work on the first timers issue. You can help first timers but not solve first timers. You are now senior in our organisation. Please look for non first timers

**Comment by oorjitchowdhary** [comment]
Yes.. Okay, I just put my hands on here as @JonathanXu1 had used the first-timers template for non first-timers issues too..

**Comment by SidharthBansal** [comment]
I asked him to make a first timer issue. I forget to label it `first timers only`.
Sorry.

**Comment by JonathanXu1** [comment]
@oorjitchowdhary for the other ones they're just 2-3 lines of code so I thought they would be best suited for first timers

**Comment by SidharthBansal** [comment]
NO there are many issues which are more than 3-4 lines of code.
For the issues which are 3-4 lines of code. For them you can surely create first timer issues.

**Comment by JonathanXu1** [comment]
Oh I was referring to the other fto-formatted issues I made

**Comment by JonathanXu1** [comment]
https://github.com/publiclab/plots2/issues/4242

**Comment by SidharthBansal** [comment]
Please claim it urgently

**Comment by JonathanXu1** [comment]
Alright, claimed it. Thanks for your time.

**Comment by IshaGupta18** [comment]
Hey, this is my first time in contributing to open source, can someone please set me up with a first-timer issue? I will be very grateful!

**Comment by SidharthBansal** [comment]
We will be happy to help you. But this issue is not available now. We will
be looking for it after integration of login sign up modal is complete.
In the meantime you can try to contribute on other issues.
Thanks
Sidharth

**Comment by IshaGupta18** [comment]
Thank you very much. I was hoping if you could recommend me any issue which is suitable for a first timer, because many of them are already taken up, like this one. Thank you.

**Comment by oorjitchowdhary** [comment]
Hi @ishagupta18, welcome to Public Lab!
Thanks for your enthusiasm for this issue.. 
You can take a look at https://github.com/publiclab/plots2/labels/first-timers-only to see the issues which are currently available and are meant to be solved by first timers.. 
Thank you for your interest..

**Comment by IshaGupta18** [comment]
Thank you sir, I will surely have a look at them once again. I am grateful for your time.

**Comment by SidharthBansal** [comment]
I think we don't need a merged button on the header. Two buttons are better. People will be able to handle whichever they are willing to.
