### ISSUE TITLE
add user profiles to the spam moderation page

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#42]
Recently we only had the 15 newest user profiles in the database, so I was able to read all of them. Of the 15, 3 were spam profiles.

Since we're now down to a manageable number of newly created users, we should add new user profiles to the moderate spam page. Instead of "title", it'll contain the profile contents.

https://publiclab.org/spam

![image](https://user-images.githubusercontent.com/24359/35295339-e4f97350-0046-11e8-9f6b-e37ce1c9513a.png)

Users could be removed from the list automatically after a few days to keep clutter down.

The ban button would be useful if the profile is obvious spam.

The Publish button would presently do nothing, since the profiles are published by default. But maybe it could expedite the usual timeout before a user is removed from the list.

We'll need a place in the database to indicate new users that are not yet vetted. This corresponds to the user status of ticket #11.

**Comment by ryzokuken** [comment]
@jywarren Another one dealing with spam. Maybe we should actually make a big issue inviting discussion regarding dealing with spam. Ever since I became a mod on the website, I realized just how much spam you people have to comb through. Kudos.

**Comment by jywarren** [comment]
Hi, @ryzokuken i agree -- i've started collecting spam-related issues in this milestone:

https://github.com/publiclab/plots2/milestone/14

...and will repost this since we now have a page for people at http://publiclab.org/people !

**Comment by jywarren** [comment]
Adapting into the new #2079!
