### ISSUE TITLE
Unable to use login modal password field

### ISSUE THREAD

**Issue by kevinzluo** [publiclab/plots2#4200]
### Please describe the problem (or idea)

Currently unable to use the password field of the login modal and signup modal. Issue only occurs on firefox.

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

Cannot type into the password field.
![loginnotworking](https://user-images.githubusercontent.com/44309027/49691763-d8c98700-fb0e-11e8-878e-2a5689dff5bd.gif)

### Please show us where to look

https://stable.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

Ubuntu, Firefox
****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by oorjitchowdhary** [comment]
@kevinzluo Even I encountered this error.. seems like a browser issue on Ubuntu.. but it worked for me when I used chrome for ubuntu.. I'd suggest please try that out..

**Comment by kevinzluo** [comment]
Yep! I ended up using chrome too.
Kevin Luo

**Comment by SidharthBansal** [comment]
It is working for ubuntu on chrome at my PC.
Can anyone @JonathanXu1 @oorjitchowdhary @Kevin-Kawai or any other contributor look into it and provide us a quick fix?

**Comment by oorjitchowdhary** [comment]
Yes.. it works on chrome but doesn't work on firefox for ubuntu

**Comment by SidharthBansal** [comment]
Please try in incognito window on firefox. Does it work?
Check its behaviour on both localhost and unstable.

**Comment by oorjitchowdhary** [comment]
let me see

**Comment by oorjitchowdhary** [comment]
The password field doesn't work on firefox.. tried all the possible outcomes

**Comment by oorjitchowdhary** [comment]
tried localhost and unstable both

**Comment by JonathanXu1** [comment]
Have you also tried clearing cache and hard refreshing?

It works on all the browsers on windows including firefox for me.

**Comment by dinaelhanan** [comment]
@oorjitchowdhary maybe try it on cloud9? It ended up working better for me. See [here](https://github.com/publiclab/plots2/wiki/Simple-Installation-for-Cloud9)

**Comment by kevinzluo** [comment]
Hi! Thanks for all of your suggestions. 

I tried clearing cache and it did not work. Neither did hard refreshing. The issue only occurs in the modal. On the login page it is fine, so I'll stick to using that for now.

**Comment by SidharthBansal** [comment]
Oh no.

**Comment by dinaelhanan** [comment]
@SidharthBansal I wouldn't really worry about since when I'm using firefox I get that a lot for many sites including Facebook when using modals, so it's not an issue with the modal on public lab it's a firefox issue

**Comment by SidharthBansal** [comment]
As a developer we need to fix it urgently.

**Comment by JonathanXu1** [comment]
Also one thing to note, the return to parameter reroutes to the https://publiclab.org/ url instead of the https://stable.publiclab.org/ url.

**Comment by SidharthBansal** [comment]
Yeah, on localhost it is working fine. I hope it will work on the
production server. So, no need to worry.

**Comment by dinaelhanan** [comment]
@JonathanXu1 what is the return to parameter? I might be able to fix that while I work on #4193

**Comment by oorjitchowdhary** [comment]
> Also one thing to note, the return to parameter reroutes to the https://publiclab.org/ url instead of the https://stable.publiclab.org/ url.

Yes it's okay..
Check https://github.com/publiclab/plots2/pull/4203#issuecomment-445537482

**Comment by SidharthBansal** [comment]
>>@JonathanXu1 what is the return to parameter? I might be able to fix that while I work on #4193

return_to means that after sign up or login we will redirect to the same page.
Eg /questions ->login/signup->success->/questions

**Comment by dinaelhanan** [comment]
@SidharthBansal oh that means sense! Thanks for explaining

**Comment by kevinzluo** [comment]
Issue is also occurring with the signup modal.

**Comment by SidharthBansal** [comment]
Sign up modal is not pushed to stable.
I don't have right to push it to the stable.
You must be referring to the unstable branch. Am I right?

**Comment by kevinzluo** [comment]
Yes

**Comment by dinaelhanan** [comment]
@kevinzluo That maybe true, but then you can see your password in plaintext. We have the field as password so that it is automatically those dots that conceal your password (which are most likely what are causing the problem) I don't think changing it to text is a option :/

**Comment by kevinzluo** [comment]
Yep! I was just mentioning it somehow allowed the field to be focused.

**Comment by dinaelhanan** [comment]
@kevinzluo good observation tho, might help :D

**Comment by JonathanXu1** [comment]
What I was referring to before was that the return to parameter directs to the right sub directory but the "stable" at the front of the url is lost

**Comment by dinaelhanan** [comment]
@JonathanXu1 oh ok, but that's not on the actual website right you're talking about the one we run on localhost?

**Comment by kevinzluo** [comment]
I think I have confirmed it is not an event listener that is doing unfocusing. Perhaps this issue is of relevance? https://support.mozilla.org/en-US/questions/1214123?page=2

**Comment by dinaelhanan** [comment]
@kevinzluo ya that's what I meant! I get that issue all the time on ubuntu

**Comment by SidharthBansal** [comment]
@kevinzluo so we don't need to fix it? 
Am I right?

**Comment by SidharthBansal** [comment]
You 4 are superb.
Can we close this issue?

**Comment by SidharthBansal** [comment]
@kevinzluo have you received your reward for suggestions/bug fixes category?

**Comment by SidharthBansal** [comment]
Let's ask @kevinzluo and @dinaelhanan also.

**Comment by dinaelhanan** [comment]
@SidharthBansal no.. I haven't been able to claim tasks since I am waiting for jeff's approval on the two tag unit test task. But I will claim it as soon as I can

**Comment by SidharthBansal** [comment]
One way is to abandon that task and claim those tasks on which you are sure
that you will get reward. Once @jywarren is online you can take that task
again. He must be highly busy. He is very responsible and very quick in
replying if he is free.
I hope this will not cause any harm to you guys because many mentors are
out of reach currently. They are busy with their exams. I also have viva
tomorrow. Last exam for the semester. So, will be less available tomorrow.
I hope you all will understand

**Comment by kevinzluo** [comment]
@SidharthBansal I have already received an approval for my suggestions on the leaflet environmental layers repository.

I completely understand if you are unavailable tomorrow. You have helped all of us a lot over the past two months, and especially over the last two days. Everytime I look at the Gitter activity chat it has been filled with your username :smile: .

**Comment by SidharthBansal** [comment]
Thanks.
https://codein.withgoogle.com/dashboard/tasks/5353598239113216/
Please claim it. You all should inform if by some problem you are not
getting rewarded. I may forget you to give points somewhere. So please be
careful

**Comment by JonathanXu1** [comment]
Just clarifying, to whom is this task intended for? I don't want to infringe upon anyone's work

**Comment by kevinzluo** [comment]
@SidharthBansal I have claimed and submitted it :smile: . Thank you!

**Comment by SidharthBansal** [comment]
@kevinzluo we need to close it right?

**Comment by kevinzluo** [comment]
Yes. I believe this issue is inherent to Ubuntu Firefox and is not an issue with us.

**Comment by kevinzluo** [comment]
Actually, could we include a link to publiclab.org/login on the login modal and say that if the user is having trouble logging in there to use the link? Because the password issue does not occur on the login page, only in the modal.

**Comment by SidharthBansal** [comment]
I don't think that it is good option. It makes the front end not good.
Also, it creates confusion.
I believe mozilla will fix this error soon. It is a huge organisation. We can hope a fix for this problem in the next version.

**Comment by kevinzluo** [comment]
Ok! That sounds good.
