### ISSUE TITLE
More than 1 reactions on a comment

### ISSUE THREAD

**Issue by arungoel123456** [publiclab/plots2#4202]
If we have reacted once on a comment , then we can add another reaction on a comment .... For eg 
![pic1](https://user-images.githubusercontent.com/31837154/49694269-5348e400-fbad-11e8-8854-8c3eff1b44a2.png)

![image](https://user-images.githubusercontent.com/31837154/49694276-76739380-fbad-11e8-92e9-2a2c24e6fa95.png)

![pic3](https://user-images.githubusercontent.com/31837154/49694282-8be8bd80-fbad-11e8-8dee-3b61701f849c.png)

![pic4](https://user-images.githubusercontent.com/31837154/49694284-9440f880-fbad-11e8-94f8-9493e066bc1d.png)

In this we can see that we can thumbs up as well as we can thumbs down at the same moment .. And at the same time we can react with heart as well ..... How .... This needs to be resolved .... And I would like to work on it

**Comment by oorjitchowdhary** [comment]
@arungoel123456 That's a great catch.. but I think we should edit the code in a manner that a particular user can use only one reaction once.. for eg.. a thumbs up can be used only once by a user.. but he may also add other reactions.. but all reactions can be put up only once.. sort of how it's like on github.. I'll make a gif to demonstrate it well...

**Comment by oorjitchowdhary** [comment]
![morethan1rectionsonacommen](https://user-images.githubusercontent.com/39333058/49694708-fb15e000-fbb4-11e8-8649-1a5ed5718195.gif)

See how it works on github.. 
@publiclab/mentors Can help us out here maybe

**Comment by SidharthBansal** [comment]
@arungoel123456 are you a gci student, if yes please claim the ``give suggestions task``.
Nice catch.
Thank @arungoel123456 
Are you willing to submit a fix for it?

**Comment by arungoel123456** [comment]
@SidharthBansal   who is a gci student ... please explain . 
Secondly I am ready to fix this

**Comment by arungoel123456** [comment]
@oorjitchowdhary   if we give a thumbs up , it means we liked it   but if we are also able to give thumbs down at the same time with thumbs up , what do we actually mean by doing that .... are we liking it or disliking it .... I hope u will get it what I am trying to say .

**Comment by oorjitchowdhary** [comment]
> @SidharthBansal who is a gci student ... please explain .
> Secondly I am ready to fix this

GCI is short for Google Code-in - an annual competition organized by Google for 13-17 year olds

**Comment by SidharthBansal** [comment]
Arun go ahead!
Best of luck

**Comment by jywarren** [comment]
Hi, Arun - i think there could be more reasons for someone to use multiple
reactions than there are problems with +1 and -1 at the same time. Maybe
someone is saying that there are both good and bad things about a comment?

However, one thing I'd like to suggest is that once there is one reaction,
could we have a second button to add reactions appear next to the row of
reactions, as it does on GitHub? That way there's a faster spot to access
them?

Would you mind taking on that project instead of the "only one reaction per
person" one -- that way we can stay more consistent with GitHub UI? Thanks!

**Comment by arungoel123456** [comment]
@jywarren  I got what u want to say in the first para , but i didnt get what u wanna say in second para and which project do u want me to take up ....

I think we should make it like facebook where each person can react only once . Giving a ThumbsUp and ThumbsDown at the same time would not give us the clarity wether the comment is worth reading or not . So I think we should make it one reaction per comment

**Comment by ValentinaTironi** [comment]
What are we going to do with this? I think that is fine that you can add more than one reaction

**Comment by dinaelhanan** [comment]
@ValentinaTironi @jywarren I agree. I like being able to use multiple ones to show how I feel about a comment ; )

**Comment by jywarren** [comment]
OK, I"m going to go ahead and close this as I think enough people want to be able to respond multiple times. Thank you!!!
