### ISSUE TITLE
Change frontend for Comments

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4204]
Currently, the post action of comments looks as
![image](https://user-images.githubusercontent.com/20972099/49695884-7da79b00-fbc7-11e8-8cce-c0db76aab959.png)
we want it to change it to the following
![image](https://user-images.githubusercontent.com/20972099/49695875-5c46af00-fbc7-11e8-834d-d5e3914d7c9d.png)
In this issue we just want a grey div in background.
radio buttons are linked to all the tags of the note.
Refer #3932.

**Comment by SidharthBansal** [comment]
We are also looking for the placeholder text.

**Comment by oorjitchowdhary** [comment]
I'll take this up..

**Comment by oorjitchowdhary** [comment]
Can you tell if the `grey div` comment has been implemented anywhere yet?

**Comment by SidharthBansal** [comment]
>>I'll take this up..

Great!!!

>>Can you tell if the grey div comment has been implemented anywhere yet?

I don't think it is implemented yet.

**Comment by oorjitchowdhary** [comment]
Ok

**Comment by oorjitchowdhary** [comment]
@SidharthBansal could you help me with the code file.. I'm unable to find the template

**Comment by SidharthBansal** [comment]
https://github.com/publiclab/plots2/blob/master/app/views/comments/_form.html.erb?fbclid=IwAR37Nyungallfv1jsAtvrNuVIlBT9Uxf3TGZONNkWXMCkvjPzS24qLc0fRs#L56

**Comment by SidharthBansal** [comment]
@oorjitchowdhary I can't see claim on the task. Please send the patch and claim it.

**Comment by dinaelhanan** [comment]
@oorjitchowdhary I see that you are focused on working on other tasks and have not claim this one. I hope it's OK that I did :)

**Comment by ValentinaTironi** [comment]
@SidharthBansal are you free? I have some pulls to review and would be great if you check out them :) ((Sorry for asking you here :p))

**Comment by SidharthBansal** [comment]
Please tag my name in your PRS. In case I will be able to help on those
tasks I will for sure.
