### ISSUE TITLE
Return_to not rendering in sign up modal

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4207]
Sign up modal should redirect back to the same page after sign up.
Example, on sign up from /questions it should link back to the questions.

**Comment by SidharthBansal** [comment]
#4203 has commit for this issue.

**Comment by SidharthBansal** [comment]
@oorjitchowdhary can we close this one as it working on the localhost?

**Comment by oorjitchowdhary** [comment]
Yes we can close this

**Comment by oorjitchowdhary** [comment]
No.. return_to for sign up isn't working

**Comment by oorjitchowdhary** [comment]
https://github.com/publiclab/plots2/pull/4203#issuecomment-445540649

**Comment by SidharthBansal** [comment]
https://github.com/publiclab/plots2/pull/4203#discussion_r240039775 have you checked it after it?

**Comment by oorjitchowdhary** [comment]
Yes.. checked it now.. Still not working.. I'm redirected to /dashboard

**Comment by SidharthBansal** [comment]
ok

**Comment by SidharthBansal** [comment]
@gauravano I think we can check this and close this.
I did the changes in the PR. Please check them so that we can close this up.
Thanks

**Comment by SidharthBansal** [comment]
@oorjitchowdhary can you please check this behaviour and tell me. I think we should close this. I have solved this @jywarren.
Thanks everyone.

**Comment by SidharthBansal** [comment]
It is merged. Some folks checked it that time before merging.
Just want to cross check as this is very important issue in Login Sequence
project.

**Comment by gauravano** [comment]
It's merged but haven't been pushed to production till now. So, we can check functionality at stable.publiclab.org but issue is captcha doesn't work there and when we switch to spamaway = true (alternate captcha approach), the link get reset on redirect. So, I guess we can check this one once it is pushed to production. Thanks!

**Comment by SidharthBansal** [comment]
OK great thanks

**Comment by SidharthBansal** [comment]
Fixed and checked this @jywarren.
Thanks
