### ISSUE TITLE
Unable to use signup modal password field

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4208]
Unable to use signup modal password field at firefox browser

**Comment by SidharthBansal** [comment]
Can we close this issue now @oorjitchowdhary @dinaelhanan @JonathanXu1 @kevinzluo ?
thanks for your help.

**Comment by oorjitchowdhary** [comment]
Sure.. Close it .. Thanks all 👍

**Comment by SidharthBansal** [comment]
@jywarren we really have so nice students this year. They are doing collaborative things.

**Comment by jywarren** [comment]
:-)
