### ISSUE TITLE
Inconsistencies for the login modal

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4210]
As a collaborative effort of @SidharthBansal @oorjitchowdhary @JonathanXu1 we came to set up the modal on the master branch for the login sequence.
Current Progress.
### Localhost
* [x] **WORKING** Login form validations are working fine for incorrect input fields(testing)

* [x] **WORKING** Login modal validations are working fine for incorrect input fields(testing)

* [x] **WORKING** Login form signs a user in successfully(testing)

* [x] **WORKING** Login modal signs in a user successfully(testing)

* [x] **WORKING** Login works well on all the webpages(testing)

* [x] **WORKING** Login is redirected to the same page after user signs up(return_to)(testing)

### Unstable
* [ ] Login form validations are working fine for incorrect input fields(testing)
Unable to test, redirected to PL stable

* [ ] Login modal validations are working fine for incorrect input fields(testing)
Unable to test, redirected to PL stable

* [x] **WORKING** Login form signs a user in successfully(testing)

* [x] **WORKING** Login modal signs in a user successfully(testing)

* [x] Login works well on all the webpages(testing)

* [x] Login is redirected to the same page after user signs up(return_to)(testing)

Refer #4203 for this conversation

**Comment by oorjitchowdhary** [comment]
Yeah.. Feels good to have contributed by collaborating 🎉

**Comment by SidharthBansal** [comment]
@oorjitchowdhary what is the behaviour of these two remaining on the localhost:3000?

**Comment by oorjitchowdhary** [comment]
> * [x]  **WORKING** Login form validations are working fine for incorrect input fields(testing)
> * [x]  **WORKING** Login modal validations are working fine for incorrect input fields(testing)

They're working.. I mentioned

**Comment by JonathanXu1** [comment]
Wow good job guys! Honored to be part of this

**Comment by SidharthBansal** [comment]
Where are they working @oorjitchowdhary?
On the localhost or on the unstable?
Or both?

**Comment by SidharthBansal** [comment]
@oorjitchowdhary is it redirecting back to the modal or to the login page?

**Comment by SidharthBansal** [comment]
If it works on both and redirects back to the same page. then please provide the gif for the following
/questions -> login -> unsuccessful login ->must be on the /questions and modal should appear with the errors -> filled modal correctly -> logged in successfully -> at the /questions page and we are signed in.

**Comment by oorjitchowdhary** [comment]
Okay.. I'll make a GIF

**Comment by oorjitchowdhary** [comment]
Not for login but for signup..

**Comment by SidharthBansal** [comment]
Let me check your tasks on the dashboard.

**Comment by oorjitchowdhary** [comment]
Okay ..

**Comment by SidharthBansal** [comment]
https://codein.withgoogle.com/dashboard/tasks/5075926623715328/

**Comment by oorjitchowdhary** [comment]
And for localhost...

* [ ] Login modal validations are working fine for incorrect input fields(testing)
You're redirected to login page with an error `"Password is not valid"`
* [ ] Login form validations are working fine for incorrect input fields(testing)
You're redirected to login page with an error `"Password is not valid"`

**Comment by oorjitchowdhary** [comment]
> https://codein.withgoogle.com/dashboard/tasks/5075926623715328/

Claimed it

**Comment by SidharthBansal** [comment]
OK, so I am right that we need a fix here.
Can you try this
/questions -> login -> unsuccessful login ->errors on the login page-> filled login form correctly -> logged in successfully -> at the /questions page and we are signed in.

**Comment by oorjitchowdhary** [comment]
@SidharthBansal This for localhost right?

**Comment by SidharthBansal** [comment]
right

**Comment by oorjitchowdhary** [comment]
ok

**Comment by oorjitchowdhary** [comment]
> /questions -> login -> unsuccessful login ->errors on the login page-> filled login form correctly -> logged in successfully -> at the /questions page and we are signed in.

Yes this works...

**Comment by SidharthBansal** [comment]
gif please. Once you give me the gif please claim it so that I can approve
it

**Comment by oorjitchowdhary** [comment]
Okay sure

**Comment by oorjitchowdhary** [comment]
![login modal 2](https://user-images.githubusercontent.com/39333058/49700717-84a2cd80-fc08-11e8-9ddd-97ae5abcae6e.gif)

**Comment by SidharthBansal** [comment]
Hurray!!!

**Comment by SidharthBansal** [comment]
Please claim it and get rewards

**Comment by oorjitchowdhary** [comment]
https://codein.withgoogle.com/dashboard/task-instances/4793116046393344/
This is the one right?

**Comment by SidharthBansal** [comment]
yes

**Comment by oorjitchowdhary** [comment]
I've claimed it

**Comment by SidharthBansal** [comment]
Please sent it for review also. You missed it.

**Comment by SidharthBansal** [comment]
I know you are careful, but please be a little more.

**Comment by oorjitchowdhary** [comment]
Oh I think @jywarren approved it.. 😄 
That's why you may not be able to see it

**Comment by oorjitchowdhary** [comment]
![image](https://user-images.githubusercontent.com/39333058/49700915-22979780-fc0b-11e8-89cd-dfd49f038959.png)

**Comment by SidharthBansal** [comment]
Oh great @jywarren is back happy to see him.

**Comment by kevinzluo** [comment]
I was recently opened the console, causing the window width to shrink and an error like this occured:
![issueswithwidth](https://user-images.githubusercontent.com/44309027/49717466-c9386400-fc1c-11e8-8603-a25cf04f85cf.gif)

When the window gets even smaller it is fixed, but in a certain interval the input fields are too long.

**Comment by JonathanXu1** [comment]
@kevinzluo do you think it's similar to this?
https://github.com/publiclab/plots2/issues/3454#issuecomment-445715574

**Comment by SidharthBansal** [comment]
@kevinzluo please claim the task
https://codein.withgoogle.com/dashboard/tasks/5255181143900160/
As you have find a bug.
Jonathan you are working on that issue and the bug you referred in the
above comments is part of that issue so, you will get credits after
completion of that task.

**Comment by SidharthBansal** [comment]
Both of you are requested to open up a new issue for reported bugs and then submit the issue links in the GCI platform so that you can get points.
Please hide these comments from both of these issues to make the conversation nice.
When ever you encounter bug not related to Amy issue please open up a new issue.

**Comment by JonathanXu1** [comment]
@SidharthBansal how's this? #4245

**Comment by SidharthBansal** [comment]
Reviewing it there.

**Comment by SidharthBansal** [comment]
@JonathanXu1 please take https://codein.withgoogle.com/dashboard/tasks/5255181143900160/. Your reward is pending.

**Comment by SidharthBansal** [comment]
Shifted to #4250
