### ISSUE TITLE
Login on alert bar doesn't work

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4218]
Part of #4132
## Problem
The login button on the alert bar doesn't work.. On the browser console, it shows a SyntaxError.

![image](https://user-images.githubusercontent.com/39333058/49702390-8b880b00-fc1d-11e8-9cad-d514d0a3fdbd.png)

@publiclab/mentors 
This issue should be resolved ASAP..

Thanks

**Comment by SidharthBansal** [comment]
What do you mean by alert bar?

**Comment by oorjitchowdhary** [comment]
The bar which is saying `You must be logged in to subscribe for email updates, please login or create an account`.

**Comment by SidharthBansal** [comment]
You can send a pr for this too.
Thanks for telling us the issue.

**Comment by SidharthBansal** [comment]
Linking of the modal is the solution.

**Comment by oorjitchowdhary** [comment]
Yes... I'm just not able to find the code for the alert bar..

**Comment by oorjitchowdhary** [comment]
Also, @SidharthBansal You seriously deserve some good rest.. It's 2.20 💤 
Thank you for all the hard work

**Comment by SidharthBansal** [comment]
You guys are also not sleeping. I know that you are indian by timings. You
are awaken from much more time than I am. Just trying to help you all.

**Comment by oorjitchowdhary** [comment]
Yes.. That's really great of you.. Thanks a lot

**Comment by oorjitchowdhary** [comment]
https://github.com/publiclab/plots2/blob/5c0d96274bd0be15feba69d8f30093082402ace5/doc/app/SubscriptionController.html
Is this the file?

**Comment by SidharthBansal** [comment]
@oorjitchowdhary just telling you that the expected behaviour after completion of the pr is 
## Basic Flow
1. User clicks on the subscribe button.
2. User is shown login modal instead of the flash messsage.
3. Modal should display that flash message
4. User successfully signs up 
5. User is subscribed to that tag
6. The subscription button is changed to unfollow.
7. Display of the flash message successfully subscribed to the tag.
## Alternative Flow
1. User clicks on the subscribe button.
2. User is shown login modal instead of the flash messsage.
3. Modal should display that flash message
4. successful login
5. User is unsubscribed to that tag
6. The subscription button is changed to follow.
7. Display of the flash message successfully subscribed to the tag.
As you have reported this error. You can claim https://codein.withgoogle.com/dashboard/tasks/6315697018765312/.
Please submit a pr soon as the deadline is approaching

**Comment by SidharthBansal** [comment]
Sorry you cannot claim this as https://codein.withgoogle.com/dashboard/tasks/5321303037837312/ is the task already identified for this. Please link both the issues.
This is a big task so you can do it with other 10 linking issues. This will not be counted in linking modal issues tally.

**Comment by oorjitchowdhary** [comment]
Oh I see.
@SidharthBansal I'd like to solve this one for sure as the alert bar span is very important for our website..
Let me put my best here.. I'll tag you if I need help... Thanks a lot..

**Comment by oorjitchowdhary** [comment]
> Please link both the issues.

I didn't understand this .. Sorry

**Comment by oorjitchowdhary** [comment]
@SidharthBansal I'm unable to change the subscriptions_controller.rb .. it is showing syntaxerror..

**Comment by oorjitchowdhary** [comment]
> As you have reported the issue you will get rewards.
> https://codein.withgoogle.com/dashboard/tasks/6640870972456960/

Thanks a lot
> Sorry I missed.

No problem..
> Once your pr gets approved you will get reward for that too.

Sure.. I'm trying to fix it but I'm stuck at a syntaxerror in the controller.. I'm unable to use the <a> tag in the controller for a modal .. but the <a> tag for href works ..

**Comment by SidharthBansal** [comment]
Take your time

**Comment by SidharthBansal** [comment]
@kevinzluo do you think that this will also work after your current pr?
If yes then @oorjitchowdhary will have to just set up the 2 lines of code which he was thinking of initially. I personally believe that your code will minimize Oorjit's work.

**Comment by oorjitchowdhary** [comment]
Okay... sure.. Can I work on any new issue now?

**Comment by oorjitchowdhary** [comment]
Hi @SidharthBansal .. Just looked through this again. The alert bar works by the controller code. So I can change the `href='/login'` but i don't know how can I toggle a modal from ruby controller. If I do `data-target=#loginModal`, it becomes a comment due to `#`

https://github.com/publiclab/plots2/blob/c57cbe65ca29f9dd761b6a4dcbd63ef96c84a27a/app/controllers/subscription_controller.rb#L79-L83

**Comment by oorjitchowdhary** [comment]
Here's the current status..

The subscribe button when clicked
![subscribe button login modal](https://user-images.githubusercontent.com/39333058/50469627-4876b780-09d3-11e9-8381-98c19471c45e.gif)

1. user clicks subscribe
2. login modal shows up
3. successful login redirects to same page
4. click subscribe and you're following that tag
The validation messages in the login modal is a separate issue and I think @kevinzluo told he'll work on it when he has time.

The alertbar modal fixed
![alert bar login modal](https://user-images.githubusercontent.com/39333058/50469658-62b09580-09d3-11e9-8754-e1420bb8e12f.gif)

I also fixed the login modal in the alert bar

**Comment by oorjitchowdhary** [comment]
As #4218 and #4231 are related .. I'll send a patch for both .. 
But @SidharthBansal please review this first and tell me what are the changes required here

**Comment by oorjitchowdhary** [comment]
@publiclab/reviewers

**Comment by SidharthBansal** [comment]
Linking of modals is under me.
Wait I will review after dinner.
Thanks

**Comment by oorjitchowdhary** [comment]
Oh okay sure.. Sorry to disturb you
Thanks
