### ISSUE TITLE
Insert placeholder for uploading images instead of inserting at current insertion point

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#422]
## The problem

When uploading images to a post or image form (https://publiclab.org/post, login required), you currently have to wait until the upload completes before continuing to type, because the image will insert wherever the insertion point currently is placed, interrupting your typing.
## How we'd like to fix it

Just like on Github, we'd like to insert the image markdown immediately upon selecting or drag-dropping an image, using the image filename as a placeholder like this:

`![image.png]()`

Then, once it's uploaded, the final URL is placed in the `()` parentheses rather than at the insertion point, so you can just keep writing while uploads progress.

See this happening in this screenshot:

![screenshot 2016-03-16 at 2 55 19 pm](https://cloud.githubusercontent.com/assets/24359/13825099/67e952f2-eb87-11e5-9330-9cf4e507fa67.png)

The relevant code for images is at https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/dragdrop.js#L65 and for other file uploads at https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/dragdrop.js#L67

**Comment by wly731** [comment]
Me and my friend @thinktankshark are interested in looking at this, we will update you once we have a resolution. Thanks.

**Comment by jywarren** [comment]
Oh, that's super. Thank you and please ask if you have questions or need
tips on existing code organization!

**Comment by wly731** [comment]
Thank you @jywarren 

Will keep you updated if we have any progress or question. If there are other folks who are interested to work on this issue please feel free to do so.

**Comment by djmgit** [comment]
@jywarren I would like to work on this issue. How should I proceed?

**Comment by jywarren** [comment]
Hi! See how on this line, we're putting in the markdown for the image: https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/dragdrop.js#L68

But that's only run on completion of upload, not on initial upload. It's in the "done" function.

If we could instead move that line into the `start` function, that'd insert the markdown immediately: https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/dragdrop.js#L43

But since we don't have the `image_url` yet, we'd insert just a unique placeholder, probably the filename. Then, in the `done` function, we'd search the textarea for the unique placeholder, and replace it with the real filename. Does that make sense? Then it'd insert immediately, and just update that text once the final filename is known.

**Comment by jywarren** [comment]
Closing due to new rich editor!
