### ISSUE TITLE
Link Login Modal to Join a Group

### ISSUE THREAD

**Issue by dinaelhanan** [publiclab/plots2#4221]
This is a continuation of #4132. Currently, when someone wants to join a group and is prompted to signup/login, they are sent to the /login page. We want them to use the modal!
https://github.com/publiclab/plots2/blob/5c0d96274bd0be15feba69d8f30093082402ace5/app/views/grids/_people.html.erb#L35

**Comment by dinaelhanan** [comment]
@SidharthBansal hope you had a good rest :D I completed this and am waiting for approval :
https://codein.withgoogle.com/dashboard/task-instances/5943340534071296/
Please also check out the PR, thanks!

**Comment by dinaelhanan** [comment]
was solved in #4246

**Comment by SidharthBansal** [comment]
Thanks
