### ISSUE TITLE
Link Login Modal to Request an Activity

### ISSUE THREAD

**Issue by kevinzluo** [publiclab/plots2#4229]
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to request an activity (The secondary link here).
![image](https://user-images.githubusercontent.com/44309027/49712412-dbf56d80-fc09-11e8-896a-28cd3762c412.png)

**Comment by SidharthBansal** [comment]
@kevinzluo please claim https://codein.withgoogle.com/dashboard/tasks/5794255877439488/ and submit for review. I need to give you rewards.
