### ISSUE TITLE
Link Login Modal to Ask a Question on Wikis

### ISSUE THREAD

**Issue by kevinzluo** [publiclab/plots2#4230]
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to request an activity (The primary button here). For modularity, this is separate from linking the "help answer questions" link.
![image](https://user-images.githubusercontent.com/44309027/49712758-891cb580-fc0b-11e8-8dc9-0e78952a8d71.png)

**Comment by oorjitchowdhary** [comment]
@SidharthBansal Can I solve this?

**Comment by SidharthBansal** [comment]
https://codein.withgoogle.com/dashboard/tasks/5321391554428928/
No, @kevinzluo is pushing this now.

**Comment by SidharthBansal** [comment]
Sorry

**Comment by oorjitchowdhary** [comment]
Okay

**Comment by SidharthBansal** [comment]
May have conflicts due to #4209. We need to resolve them once it gets merged.
--
