### ISSUE TITLE
Negative likes bug on research notes

### ISSUE THREAD

**Issue by JonathanXu1** [publiclab/plots2#4237]
I was browsing through https://publiclab.org/notes/recent, and noticed that a note has a negative number of likes:
![image](https://user-images.githubusercontent.com/22998430/49713581-58db1400-fc17-11e8-90ed-5d4f839a2eb4.png)
You can also see it at https://publiclab.org/notes/liked/ :
![image](https://user-images.githubusercontent.com/22998430/49713688-cbe48a80-fc17-11e8-8d56-f89351f9fd33.png)

As far as I'm aware, this has only occurred on the listing for this specific note. Moreover, this doesn't appear on it's own page:
https://publiclab.org/notes/warren/12-03-2018/openhour-usability-feedback-for-publiclab-org
This happens when I am logged in or out.

Please refrain from liking this note as it may hamper our ability to debug the issue! 

Browser/system: Firefox Quantum Windows 10

**Comment by SidharthBansal** [comment]
I don't think it is a bug. It is a feature. Like people dislike youtube videos.
@jywarren may we close this?

**Comment by JonathanXu1** [comment]
I can't find the option to dislike these posts. Could you show how one can dislike a post?

**Comment by SidharthBansal** [comment]
Oh sorry. https://codein.withgoogle.com/dashboard/tasks/5167726348730368/
Please claim and submit it urgently

**Comment by gauravano** [comment]
@JonathanXu1 would you like to solve this one? Thanks!

**Comment by gauravano** [comment]
Hi everyone, this issue is undertaken by @geekychaser in #4589 so closing this one. Thanks!
