### ISSUE TITLE
Link Modal to Empty Notes Grid Message

### ISSUE THREAD

**Issue by kevinzluo** [publiclab/plots2#4241]
We are creating a login/signup modal, next step is to link to various pages. In this issue we will be linking it to "be the first to post something"
![image](https://user-images.githubusercontent.com/44309027/49714808-fdf3ed80-fc13-11e8-9011-890aa948a61a.png)

**Comment by SidharthBansal** [comment]
Hi @kevinzluo is not working on this. He has already many pending PRs and issues. He is working on them. Currently his exams are going on. Let's give this issue to someone else.

**Comment by kevinzluo** [comment]
I have reposted this as an FTO in #4405

**Comment by SidharthBansal** [comment]
Thanks a lot.
