### ISSUE TITLE
Link login modal to edit wiki button

### ISSUE THREAD

**Issue by JonathanXu1** [publiclab/plots2#4242]
### Problem
On wiki posts such as this https://publiclab.org/wiki/environmental-estrogen-testing there is an option to edit the page:

![image](https://user-images.githubusercontent.com/22998430/49717450-1d474680-fc25-11e8-8969-4aa0e4a3b8be.png)

### 📋Solution
Currently when clicked, the user is directed to a login page. We want the button to open a login modal if the user is not logged in.
/app/views/wiki/_header.html.erb

**Comment by okonek** [comment]
Claimed and resolved in here: https://github.com/publiclab/plots2/pull/4258

**Comment by JonathanXu1** [comment]
@okonek does it open the edit prompt once the user is logged in?

**Comment by okonek** [comment]
No, it doesn't, but I couldn't find a way that I could without editing the controller's code.

**Comment by JonathanXu1** [comment]
Check #4239, I'm trying to do something similar too

**Comment by okonek** [comment]
Ok, I'll check it out in a minute.

**Comment by okonek** [comment]
Well, after looking at the @kevinzluo code in this PR, I still have no idea how he managed to do that. Maybe he could help us himself?

**Comment by kevinzluo** [comment]
Hi @okonek . Please take a look at my comment here:https://github.com/publiclab/plots2/pull/4228#issuecomment-446430051

**Comment by oorjitchowdhary** [comment]
Hi @SidharthBansal, is this issue solved?

**Comment by SidharthBansal** [comment]
All the issues which are open of ``OAuth`` milestone are not solved that is why they are open. I am core mentor for ``OAuth`` milestone. So, I will be closing all the issues whenever they will be needed. 
Thanks.

**Comment by oorjitchowdhary** [comment]
I think for this issue's PR #4258 .. we just need the `requireLogin` class I think

**Comment by SidharthBansal** [comment]
Yeah, @okonek is working on it.
Please read the conversation fully to avoid confusions.

**Comment by SidharthBansal** [comment]
You are contributing very much to Public Lab but on the other hand you are in a hurry. Please don't be in a hurry. Haste makes waste. Please stay focused and give time to all the issues and prs appropriately on which you are commenting. It will help you a lot.
Thanks

**Comment by oorjitchowdhary** [comment]
Yes, I understand. Thank you for the guidance and sorry for the haste approach

**Comment by SidharthBansal** [comment]
No problem, mentors are there to help you.

**Comment by SidharthBansal** [comment]
@Dsxv you can do this too if you want. You were having trouble in finding issues so just telling you some issues.

**Comment by Dsxv** [comment]
@SidharthBansal Thankyou So much for help ! But isn't @okonek working on it?

**Comment by SidharthBansal** [comment]
He is not online since many days so you can work on it.

**Comment by SidharthBansal** [comment]
@Dsxv how is it going here?
