### ISSUE TITLE
Inconsistency in tab display on mobile view

### ISSUE THREAD

**Issue by JonathanXu1** [publiclab/plots2#4245]
While testing out mobile dropdown, it seems like after a certain point, the buttons on /notes and /questions but not /tags stop displaying text, most likely for better ui on mobile view. Also it happens when the navbar takes up extra vertical space.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22998430/49717108-efadcd80-fc23-11e8-9c40-99921766b015.gif)

Perhaps the bug with tabs is a result of another bug of text reappearing at that aspect ratio?

The best resolution for this bug would probably be:

- [ ] prevent navbar from increasing in height
- [x] allow tabs on /tags to turn to just icons too
- [ ] prevent tabs on all three pages from adding back text when the window continues to shrink

Some files to look into:
/app/views/notes/index.html.erb
/app/views/questions/index.html.erb

**Comment by JonathanXu1** [comment]
EDIT:
Figured it out!
https://v4-alpha.getbootstrap.com/layout/responsive-utilities/
There was a <span> with class .hidden-sm which did not account for .hidden-xs

**Comment by SidharthBansal** [comment]
So what please provided the updated screenshots and claim the tasks so that we can give you rewards.
