### ISSUE TITLE
Non-unique page views

### ISSUE THREAD

**Issue by jiteshjha** [publiclab/plots2#425]
### What happened just before the problem occurred

The page view counter doesn't track unique views for any page. Take any sample research note like [this](https://publiclab.org/notes/clauds/12-17-2016/how-useful-is-a-map). Simply doing a page refresh increases the view count. Any spam bot or a simple browser macro could be employed to easily increase the view counter.

Possible solution is using the [impressionist](https://github.com/charlotte-ruby/impressionist) ruby gem. Read the documentation in the Readme and think of a way to use it in plots2.

### PublicLab.org username
jiteshxyz
(to help reproduce the issue)

### Browser, version, and operating system
Firefox 44, Ubuntu 15.04

**Comment by jywarren** [comment]
This is true, but we don't record unique identifiers for pageviews, just
increment a count. I don't see this as a big problem at the moment, but if
you have a simple fix you'd like to propose, go for it! Thanks!

**Comment by jiteshjha** [comment]
I cannot think of a simple fix for this, rather than using [impressionist](https://github.com/charlotte-ruby/impressionist) gem, which includes a long procedure. What do you think?

**Comment by jywarren** [comment]
I think we should focus on other higher priority issues for now, but thanks
for looking into it! Anything from
https://github.com/publiclab/plots2/labels/help-wanted if you're looking
for something to work on!
