### ISSUE TITLE
Help People Report Errors! (Part 2)  

### ISSUE THREAD

**Issue by CodeSarthak** [publiclab/plots2#4251]
This is part 2 of the issue #4117 

# The Problem

Currently, if a user get a non-existing page, they get a message saying "Report a bug or issue" in the footer, which isn't welcoming for non-developer users and is hard to notice. 

# Solution 

We need to add a button which says " Report the Issue" instead of the link which may seem too toned down. Make an attractive button linking to this page https://github.com/publiclab/plots2/issues/new

Here is the template : https://github.com/publiclab/plots2/blob/dd18e979e619005c28254fd129852602e0279dd7/app/views/dashboard/dashboard.html.erb#L6

https://publiclab.org/wiki/issues

![link](https://user-images.githubusercontent.com/24937677/49729395-6508b500-fc9b-11e8-99b3-d221e7642c09.PNG)

**Comment by CodeSarthak** [comment]
@jywarren @publiclab/reviewers Please add label "fto only" and "gci-candidate".

**Comment by dave-light** [comment]
A little confused, description says 'fto' but label says 'fto-candidate'. Does more work need to be done to make it fto friendly? Or is the 'fto-candidate' label incorrect?

**Comment by dave-light** [comment]
If it's not an FTO I'd love to work on this? I've made one contribution to publiclab so far but if you'd rather it was left for someone else I'll understand. I currently have one other issue I'm working on.

**Comment by sashadev-sky** [comment]
@gauravano @dave-light @CodeSarthak I will make an FTO out of this

**Comment by SidharthBansal** [comment]
This issue needs not to be converted into fto.

**Comment by SidharthBansal** [comment]
OK thanks

**Comment by sashadev-sky** [comment]
@SidharthBansal please help answer my comment above yours

**Comment by gauravano** [comment]
Hi @dave-light, sorry for missing your comment earlier. Just trying to get the goal of this issue. Our current page looks this 
![404_page](https://user-images.githubusercontent.com/20878070/51313237-19ec7980-1a73-11e9-8250-ecce5087ac87.png)

Do we just want to change the button text? @dave-light @CodeSarthak @sashadev-sky

**Comment by gauravano** [comment]
OK, I got here - https://publiclab.org/wiki/issues from the footer link. I saw 2 methods listed for reporting issue one via GitHub and another posting a question at publiclab.org 
![issue_page](https://user-images.githubusercontent.com/20878070/51313657-19a0ae00-1a74-11e9-859a-7f1e2cdc0756.png)

I guess, we want to change the GitHub one a button. Am I right?

**Comment by sashadev-sky** [comment]
@dave-light @gauravano I managed to change it to a button in Chrome Dev Tools and I can transfer the code to the DB I just am confused how I would see this change outside of Chrome Dev Tools if this is not a page available in the testing environment.

How do people usually make changes in a scenario like this? Do they just try to recreate that part of the page locally? Sorry I think I am fundamentally confused about something here.

**Comment by gauravano** [comment]
The page we are talking about is a wiki page, which is just a post saved in
production database. Just like our accounts on GitHub, or our comments
here. The wiki is made by different people working together, so anyone who
have conyributed some posts to PublicLab can edit the wiki. You can check
whether you are allowed to edit or not. Or, I can edit the wiki to convert
that link to a button?

Give it a try and let me know, what response you get. Thanks!

**Comment by sashadev-sky** [comment]
@gauravano Thank you! I didn't know that wikis worked that way. I think I have had tunnel vision with the Github side of things. I can't edit yet because I have not contributed to any posts on the site, so you may have to edit it or @dave-light. Are code contributors encouraged to just create pages about anything they feel is relevant?

**Comment by gauravano** [comment]
@sashadev-sky code contributors create research notes and wikis regarding new features, integrations, their work and relevant exciting things there. Questions regarding interesting ideas, GSoC proposals and many things are posted at publiclab.org. As wiki is a page which is created by collaboration of multiple users and not all contributors come to website with legitimate purpose so for preventing spam these guidelines are set. 

I will convert it to button. What text you all think would be nice for the button(keeping style same as Report an issue button)?  Thanks!

**Comment by gauravano** [comment]
![new_temp](https://user-images.githubusercontent.com/20878070/51392965-8abb9080-1b5c-11e9-9df3-841bd6c2fca2.png)

Changes done! Looks good?

**Comment by sashadev-sky** [comment]
Closing this issue as @gauravano has fixed it
