### ISSUE TITLE
Logout always redirects to / (Home Page)

### ISSUE THREAD

**Issue by okonek** [publiclab/plots2#4259]
### Problem
The log out button in the dropdown redirects to the home page. It's a very annoying issue, which can cause users to dislike the whole webpage.
![logout](https://user-images.githubusercontent.com/24360027/49745793-aeef9c00-fc97-11e8-8a41-051ae139e27c.gif)

### Solution
Pressing the log out button should log you out and then redirect to the same page you were on before the action. The solution to this problem would probably be very easy. You should start looking at the [_header.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/layouts/_header.html.erb) and [user_sessions_controller.rb](https://github.com/publiclab/plots2/blob/master/app/controllers/user_sessions_controller.rb) especially the functions `destroy` and `logout_remotely`. The `return_to` statement could be useful.

Thanks for all your help!

**Comment by okonek** [comment]
@SidharthBansal What do you think about it? It's for this task: https://codein.withgoogle.com/dashboard/task-instances/5879456854966272/

**Comment by SidharthBansal** [comment]
Great catch. Can you submit a patch for this?

**Comment by SidharthBansal** [comment]
I have approved it.

**Comment by okonek** [comment]
I can try but I don't know if I would finish before the end of the competition.

**Comment by okonek** [comment]
I can solve it after the competition because I am surely going to help and solve the issues for you even after the contest because your engagement and support are just great.

**Comment by SidharthBansal** [comment]
Great.

**Comment by jywarren** [comment]
you're awesome!!!

**Comment by IshaGupta18** [comment]
Is this issue still open? If yes, could I please try to work on this?

**Comment by SidharthBansal** [comment]
I think @okonek is trying to implement his proposed solution, if no then @IshaGupta18 you can try to fix it.
Thanks all of you.

**Comment by IshaGupta18** [comment]
@okonek please let me know whether you are working on this or not? Thank you all!

**Comment by IshaGupta18** [comment]
I have a solution in mind for this issue, has this issue been resolved or closed yet? Please let me know if I can be of any help! Thank you all very much!

**Comment by okonek** [comment]
@IshaGupta18 Sorry for that I respond so late. You can take it. I had whole lot of exams and other contests at school that I'm too tired to do it.

**Comment by IshaGupta18** [comment]
Okay @okonek I'll start working on it then @SidharthBansal

**Comment by IshaGupta18** [comment]
I have made a pull request for this issue, #4312 is the link to the PR. I am waiting for approval. I hope everything works out. Thank you all very much!

**Comment by IshaGupta18** [comment]
I have closed this pull request. I will make a fresh one, once I have it all resolved. I sincerely apologise for all the trouble I may have caused. Thank you all!

**Comment by SidharthBansal** [comment]
No problem
You can work on this pull request.
Just push in the changes which resolves the travis cases.

**Comment by IshaGupta18** [comment]
@SidharthBansal @gauravano #4331 is my pull request for this issue. I hope everything works out, please do check the file user_sessions_controller.rb for being completely sure that it's up to date and please let me know if there is anything else I can do. Thank you all so much for the help!
