### ISSUE TITLE
Validation error messages for the signup modal

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4268]
We expect the errors will be shown on the modal instead of redirecting to sign up page.
Please ensure the following:
- [ ] Sign Up form validations are working fine for incorrect input fields(testing)
- [ ] Sign Up modal validations are working fine for incorrect input fields(testing)

**Comment by SidharthBansal** [comment]
It needs to be done after #4209

**Comment by SidharthBansal** [comment]
@kevinzluo may be you will be willing to work on this?
As it is related to your pr #3984

**Comment by vishvanatarajan** [comment]
Hey @SidharthBansal can i work on this issue?

**Comment by SidharthBansal** [comment]
Yes

**Comment by SidharthBansal** [comment]
@vishvanatarajan in case of any help needed, please free to ping me.

**Comment by vishvanatarajan** [comment]
@SidharthBansal okay no problem. I will create a PR and link it as soon as possible. Thank you for the support :+1:

**Comment by SidharthBansal** [comment]
How is it going @vishaldeepak ?

**Comment by divyabaid16** [comment]
@SidharthBansal  Can I work on this issue?

**Comment by SidharthBansal** [comment]
Sure

**Comment by divyabaid16** [comment]
So do I need to use the alert to show the error message or just show it below the field?

**Comment by SidharthBansal** [comment]
You can do it anyways.

**Comment by SidharthBansal** [comment]
Published on GCI dashboard

**Comment by VladimirMikulic** [comment]
@SidharthBansal isn't this issue same as #3439? In both of these issues, we need to validate sign up form/modal. Right?

**Comment by VladimirMikulic** [comment]
I am working on this by the way.

**Comment by SidharthBansal** [comment]
Point 1: Please check whether it is solved or not. If they are solved then ping me for adequate action
Point 2: They are different
Point 3: Create modular PR for different functionality.
Thanks

**Comment by VladimirMikulic** [comment]
> Point 1: Please check whether it is solved or not. If they are solved then ping me for adequate action

It's not solved that's why I am working on it.

> Point 2: They are different

Could you please explain the difference between this issue and issue #3439?

> Point 3: Create modular PR for different functionality.

For this issue, it won't be necessary.

**Comment by SidharthBansal** [comment]
Form is different from modal
Also password confirmation is through js
While validation errors are through rails
So they are different but related I guess

**Comment by VladimirMikulic** [comment]
Whoops, I didn't know that. I picked the wrong task then 😅
I am working on client-side validation(JS).

Thanks for the clarification!

**Comment by SidharthBansal** [comment]
May be modal require J's
Not sure

**Comment by SidharthBansal** [comment]
You can search and take this task again if Js is required
