### ISSUE TITLE
SpinachCon new developer feedback on install process

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#427]
Working on #426, here is feedback collected from SpinachCon, relevant to new contributor outreach:
- [x] mac `brew` install instructions (@gr2m)
- [x] prerequisites!! mysql is hard. sqlite not compatible with spatial_adapter (needed?) and community_tags indices break rake db:setup Moving in part to #433, rsolving in #438 w/ sqlite
- [x] someone got [this error](http://stackoverflow.com/questions/13828889/rails-3-heroku-cannot-load-such-file-test-unit-testcase-loaderror/13837694), solution, add `gem 'test-unit'` in Gemfile
- [x] move warning in test entry in database.yml.example to after development to avoid confusion about the warning there (@vzhz)
- [x] reword copy and configure: "To rename the example file for editing, do ..."
- [x] provide prepopulated development.db & test.db for newcomers
- [ ] link to basic mysql setup guide (database.yml, mysql setup, user, etc) in readme (wontfix, preferring sqlite, #438)
- [ ] still need to transcribe SpinachCon feedback and add here

Remainder moved back to #426, 

Cool: https://github.com/espy/ubersicht/

**Comment by jywarren** [comment]
* [ ] move warning in test entry in database.yml.example to after development to avoid confusion about the warning there (@vzhz)

**Comment by jywarren** [comment]
* [ ] maybe provide container w all

**Comment by jywarren** [comment]
* reword copy and configure: "To rename the example file for editing, do ..."

**Comment by vzhz** [comment]
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:458:in `method_missing'
/Users/Admin/Desktop/git/plots2/db/migrate/20120101000000_drupal_schema.rb:4:in `up'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:410:in `block (2 levels) in migrate'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:410:in `block in migrate'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:389:in `migrate'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:528:in `migrate'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:720:in `block (2 levels) in migrate'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:777:in `call'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:777:in `ddl_transaction'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:719:in `block in migrate'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:700:in `each'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:700:in `migrate'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:570:in `up'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/migration.rb:551:in `migrate'
/Users/Admin/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.20/lib/active_record/railties/databases.rake:193:in `block (2 levels) in <top (required)>'
/Users/Admin/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/Admin/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
Mysql2::Error: All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead

**Comment by jywarren** [comment]
Provide prepopulated development.db & test.db for newcomers.

**Comment by vzhz** [comment]
Hey Jeffrey,
I'm about to close tabs and terminal windows from SpinachCon, and I'm
wondering if it would benefit you at all to have a copy of my terminal
output as I was doing the install?
Let me know, happy to send it over!
Veronica

**Comment by jywarren** [comment]
thanks! I think the error you posted is probably enough. Thanks, though!

**Comment by jywarren** [comment]
Closing, as we've thoroughly revised our install process! Thanks!
