### ISSUE TITLE
Searching error at /search bar

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4270]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file https://github.com/publiclab/plots2/blob/7e8ba8e144f54d8d3ea4f4f8157afd9b8275ce56/app/views/search/new.html.erb#L8-L13 in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

### Problem
When you don't write anything in the search bar and still press the search button.. it searches for `/search/ ` therefore comes back to `/search` once again..

![search error](https://user-images.githubusercontent.com/39333058/49831181-47317200-fdb9-11e8-9165-6f278d8ee963.gif)

### Solution
I think we could change the search box code and mark that field as `required`

```DIFF
- <input tabindex="1" style="min-width: 350px;" id="inline_searchform_input" type="text" class="search-query typeahead form-control" data-provide="typeahead" value="<%= params[:id] %>">
+ <input tabindex="1" style="min-width: 350px;" id="inline_searchform_input" type="text" class="search-query typeahead form-control" data-provide="typeahead" value="<%= params[:id] %>" required>
```

![search bar fixed](https://user-images.githubusercontent.com/39333058/49848680-4ec63a80-fdfc-11e8-9531-790aa62aa1fc.gif)

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by jywarren** [comment]
Super! 

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by jywarren** [comment]
This is looking good! However i think for it to be a full first-timers-only issue we'd have to suggest a concrete specific code change -- what it should be changed to. Could you offer the final solution in code for it to be changed to? 

`I think we could change the search box code and mark that field as required`

Remember a FTO is often more to help people learn the collaboration process than to solve the specific code problem. Thanks!

**Comment by jywarren** [comment]
And great work!

**Comment by rexagod** [comment]
Hey I'd like to claim this issue please!
