### ISSUE TITLE
Sorting of '# of people subscribed' on /tags doesn't work

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4271]
### Please describe the problem (or idea)
Sorting of `# of people subscribed` doesn't work.. 
The `ascending` and `descending` is broken and doesn't show up correctly..

![sorting people error](https://user-images.githubusercontent.com/39333058/49832066-a0020a00-fdbb-11e8-84e2-74b1e269fa8d.gif)

> What did you expect to see that you didn't?

By clicking on it, the sorting should have shown proper sequence of `ascending` and `descending`.

### Please show us where to look

https://publiclab.org/tags?sort=followers&order=desc

### What's your PublicLab.org username?

oorjit_chowdhary

### Browser, version, and operating system
Chrome, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by oorjitchowdhary** [comment]
@publiclab/reviewers

**Comment by ValentinaTironi** [comment]
Maybe you can add where is the code for fix this and explain how do you think it can be resolved. What  do you think?

**Comment by SidharthBansal** [comment]
Create PR for the one which works. Think about the second issue in second
pr.
Keeping modularity into mind.

**Comment by oorjitchowdhary** [comment]
No.. actually I meant.. on the live PL site.. sorting of `# of uses` works well but `# of subscriptions` shows an error...

**Comment by shubhscoder** [comment]
@oorjitchowdhary, The problem was in the order_string function. It was ordering the tags array depending on "name" but it was supposed to order it according to number of followers of a particular tag, which is given by Tag.followers_count. I have made a PR to fix these. See if that looks good ! Thank you so much!
