### ISSUE TITLE
Improve UI at 'Contributors' tab at /tags

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4272]
### Please describe the problem (or idea)
The `contributors` tab page shows up in a very unorganized way....

The `number of contributors`, `research notes` and `wiki pages` could be shown in a proper sentence format (which could be styled using Markdown) instead of showing up as a whole row which could be confused with the table.

Moreover, I think the `table` shown below is not well-formatted and therefore gets all its headers on the left side and a whole lot of area left blank towards the right.

> What happened just before the problem occurred? Or what problem could this idea solve?

![screenshot 102](https://user-images.githubusercontent.com/39333058/49832633-41d62680-fdbd-11e8-8b97-5b995068f595.png)

![screenshot 103](https://user-images.githubusercontent.com/39333058/49832649-4c90bb80-fdbd-11e8-8b77-df4d5dd8ef61.png)

### Please show us where to look

https://publiclab.org/contributors/workshop

### What's your PublicLab.org username?

oorjit_chowdhary

### Browser, version, and operating system
Chrome, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by oorjitchowdhary** [comment]
@publiclab/reviewers

**Comment by jywarren** [comment]
this is really cool. Oorjit - do you think you could find some examples
from other places on the web which we could use as a design inspiration for
this page?

**Comment by oorjitchowdhary** [comment]
@dinaelhanan @jywarren I had implemented the /people page layout in the `people` tab /search. Here in #4130. We could implement the same at /tags too..

**Comment by oorjitchowdhary** [comment]
![table-ui-kit-s11](https://user-images.githubusercontent.com/39333058/49848372-de6ae980-fdfa-11e8-8fc9-cf26cafa52bd.jpg)

Found this one.. Really liked it.. Probably we can remove the `Company` tab in here.. and add `Usernames` there.. 

And I also have a great idea.. For the status tab, if we want, we can either use the `@user.status ==` here or perhaps we could add a new feature depending upon the activity of the user which could be like if a user posts 1 research note/wiki page or comments on questions/answers frequently (say every day or every 2 days) -- he could be marked as an `active` user.. And rest tags of `idle` and `inactive` may follow the descend of frequency..

**Comment by dinaelhanan** [comment]
@oorjitchowdhary good idea! like @jywarren said, we could probably use that for the people page too!

**Comment by ebarry** [comment]
Just updating with a current screenshot of the Contributors view of a tag page: 
![contributors](https://user-images.githubusercontent.com/161439/69074706-e74a3f00-09fd-11ea-95ae-552f5c1abced.gif)

**Comment by jywarren** [comment]
I'm going to merge this into https://github.com/publiclab/plots2/issues/6304, thanks!
