### ISSUE TITLE
'Map' tab stays blank if no map is available

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4273]
### Please describe the problem (or idea)
The `map` tab page at /tags stays blank if no map is available. 

> What happened just before the problem occurred? Or what problem could this idea solve?

![screenshot 104](https://user-images.githubusercontent.com/39333058/49832976-2f102180-fdbe-11e8-921b-c482c87d6db4.png)

> What did you expect to see that you didn't?

I think we can add a line which says 
`Sorry, no maps tagged with x and y tags are available. You can view other maps at publiclab.org/maps or you may help us add a map for these tags. Thanks`

### Please show us where to look

https://publiclab.org/maps/tag/workshop

### What's your PublicLab.org username?

oorjit_chowdhary

### Browser, version, and operating system
Chrome, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
this is great!
