### ISSUE TITLE
Enhance the /research page

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4274]
### Please describe the problem (or idea)
The current research page is the exact replica of dashboard also accessible to users who aren't logged in.

I think we enhance this page to just show our recent activity ranging from questions, notes and wiki pages.

Through this, we aren't exactly replicating the dashboard, giving logged in users a special page (`/dashboard`) and are also showing non logged users some activity of PL. I think this issue can be broken down further and could be used for planning.

Research page
![screenshot 105](https://user-images.githubusercontent.com/39333058/49834071-7f3cb300-fdc1-11e8-8ef3-f4c442c3ba1f.png)

Dashboard
![screenshot 106](https://user-images.githubusercontent.com/39333058/49834076-8663c100-fdc1-11e8-9845-edc7c2a2c9cd.png)

### Please show us where to look

https://publiclab.org/research

### What's your PublicLab.org username?
oorjit_chowdhary

### Browser, version, and operating system
Chrome, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
I think this is an interesting idea for @edieblu to consider in the redesign of the dashboard! Please note that the main purpose of the /research page was to ensure that people who haven't made an account or haven't logged in, could still participate in and read through PL content -- it's basically OK if some people just want to follow along, even if we do want them to make accounts. Does this make sense? But yeah, i love the idea of further emphasizing the breadth of activity across the Public Lab community!

**Comment by oorjitchowdhary** [comment]
Actually I'm thinking of something like 'subscriber-only content'. Right now, everything is accessible for members and non members.. Let's create something which is only for members.. And we can add prompts for that feature on the normal site 'sign up to get all the updates on this!'

**Comment by jywarren** [comment]
I'm going to merge this back into the new dashboard design and we'll try to focus on the /tags page as the "public alternative" for non-logged-in users! Thank you!!! #6072
