### ISSUE TITLE
'Follow' icon is the same as 'number of views' icon

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4278]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the files in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 
https://github.com/publiclab/plots2/blob/eeed6645474a356cdd62fdd9e7c8467935faef1f/app/views/like/_like.html.erb#L14
https://github.com/publiclab/plots2/blob/e6fbd99aa47083be93fd1fa10236f743e5bc4900/app/views/tag/blog.html.erb#L18
https://github.com/publiclab/plots2/blob/6f353b2937af8b523708a9991813bbdbac21987d/app/views/home/subscriptions.html.erb#L9
https://github.com/publiclab/plots2/blob/cfb8b01acce023c19f5476e8b9f6743cb098e7a8/app/views/tag/index.html.erb#L44-L48
https://github.com/publiclab/plots2/blob/5c0d96274bd0be15feba69d8f30093082402ace5/app/views/tag/_contributors.html.erb#L25-L29
https://github.com/publiclab/plots2/blob/3f76b90c3273292e9ab2f96654b9790d265afd99/app/views/tag/contributors-index.html.erb#L47-L51
https://github.com/publiclab/plots2/blob/d5aa3de4459da087aa4d7dca06b515fa39910c53/app/views/tag/show/_user_controls.html.erb#L6-L10

```DIFF
- <i class="fa fa-eye"></i>
+ <i class="fa fa-user-plus" aria-hidden="true"></i>
```

### Problem
While browsing through the PL site, I got confused with this.
The `follow` icon is the same as the `number of views` icon. We should change one icon in order to avoid any confusion.

`Follow` icon
![screenshot 110](https://user-images.githubusercontent.com/39333058/49858299-8cd25700-fe1a-11e8-8a22-21e5621efa31.png)

`Views` icon
![screenshot 111](https://user-images.githubusercontent.com/39333058/49858306-91970b00-fe1a-11e8-8286-98600848600d.png)

### Solution
I think we can change one logo. 
I've a suggestion for changing the `follow icon`. 
I think we can use this icon for the `follow` buttons on the site.

![screenshot 112](https://user-images.githubusercontent.com/39333058/49858442-ecc8fd80-fe1a-11e8-8047-ba1a6d7a6af7.png)
https://fontawesome.com/v4.7.0/icon/user-plus

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

*** 
- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by oorjitchowdhary** [comment]
@publiclab/reviewers I created this as a fto issue but I have realized this will require changes at multiple locations, should it still be a fto issue?

**Comment by oorjitchowdhary** [comment]
@SidharthBansal What say?

**Comment by SidharthBansal** [comment]
It will be better to close this issue and create a single issue where you
can list all the places where we need to change the icons. Right now we are
having 500+ issues so we are looking forward to solving them first. If you
will create issue for each then it will create issue tracker to be
overwhelmed for the mentors. Let's teamwork to resolve the existing issues
first. What do you think?
I really appreciate your hardwork. Thanks for the catch.

**Comment by oorjitchowdhary** [comment]
> It will be better to close this issue and create a single issue where you can list all the places where we need to change the icons. 

That's a great idea.
> Right now we are having 500+ issues so we are looking forward to solving them first. If you will create issue for each then it will create issue tracker to be overwhelmed for the mentors. Let's teamwork to resolve the existing issues first. What do you think? I really appreciate your hardwork. Thanks for the catch.

Okay, sounds good. Let's do this!

**Comment by SidharthBansal** [comment]
Oorjit we have :+1: symbols at each comment. If you agree upon the
statement then you can use them instead of commenting. This enables the
conversation to be precise and accurate.

**Comment by SidharthBansal** [comment]
Please link it to the new issue which I suggested you to create.

**Comment by oorjitchowdhary** [comment]
I browsed through the website.. I don't think we require any other changes from the icons perspective...
I think this is the only one... So should I reopen this and all the code links??

**Comment by SidharthBansal** [comment]
Yeah please do so.

**Comment by IshaGupta18** [comment]
Can I claim this issue?

**Comment by uzorjchibuzor** [comment]
@IshaGupta18 I would suggest that you leave this one for someone new. It is targeted at first-timers

**Comment by IshaGupta18** [comment]
Alright, thank you. I have actually made just one contribution, that too yesterday, so I thought I might still come under first-timers category. My apologies. Thank you again!

**Comment by oorjitchowdhary** [comment]
@publiclab/reviewers I think we can let @ishagupta18 solve this one too...?
I think we allow two 'first timers only' issues per person

**Comment by IshaGupta18** [comment]
So should I start working on this one @oorjitchowdhary ?

**Comment by SidharthBansal** [comment]
Right now you can fix the issue in the frontend is you want(the quick fix
one)
I have to tackle the backend as I have written the OAuth code.

**Comment by IshaGupta18** [comment]
Okay @SidharthBansal I'll just do what the task states in the description. Thank you all very much!

**Comment by IshaGupta18** [comment]
I have made a pull request for #4278 issue. I believe #4294 is the link to the request. I am waiting for approval and I hope everything works out. I thank you all very much!
