### ISSUE TITLE
RSS feed page is broken

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4279]
### Please describe the problem (or idea)
I am not so familiar with RSS but I still clicked the button and went to that site.
It comes up with an error at top and then shows up the `document tree`.

![rss error](https://user-images.githubusercontent.com/39333058/49859027-8644df00-fe1c-11e8-82bb-06bc74e8bbde.gif)

### Please show us where to look

https://publiclab.org/feed/oorjit_chowdhary.rss

### What's your PublicLab.org username?

oorjit_chowdhary

### Browser, version, and operating system
Chrome, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by gauravano** [comment]
Hi @oorjitchowdhary are you talking about this message - 

![error_rss](https://user-images.githubusercontent.com/20878070/50046711-bbc42380-00cd-11e9-8b6d-c939be838990.png)
 
If yes, then that's fine. Google Chrome doesn't support RSS, so if you view the same link in Firefox, you'll observe the change. Let me know if I am wrong. 

Thanks!

**Comment by dinaelhanan** [comment]
@jywarren is this it? https://github.com/publiclab/plots2/blob/a2c1723bcdeab32757a4e384c76ae4581845f630/test/functional/notes_controller_test.rb#L713

**Comment by sagarpreet-chadha** [comment]
Hi 😄 !

The above is the test for notes_controller : https://github.com/publiclab/plots2/blob/a2c1723bcdeab32757a4e384c76ae4581845f630/app/controllers/notes_controller.rb#L347

I guess you are looking for users feed (https://publiclab.org/feed/oorjit_chowdhary.rss) , which is tested here : 

https://github.com/publiclab/plots2/blob/a2c1723bcdeab32757a4e384c76ae4581845f630/test/functional/users_controller_test.rb#L242

Hope it helps ! Thanks !

**Comment by sagarpreet-chadha** [comment]
Also i see our feed is not valid . We have to do minor changes . 
We can see the changes we have to do using this validator : https://validator.w3.org/feed/check.cgi

If you paste the feed URL which is (https://publiclab.org/feed/oorjit_chowdhary.rss) , you will see 2 minor changes that we have to do while generating RSS feed . 

The code that generates the RSS is here : https://github.com/publiclab/plots2/blob/master/app/views/tag/rss.rss.builder

If anyone wants to solve this , i would be happy to help . Thank you 😄 !

**Comment by dinaelhanan** [comment]
I'd be glad to take this on!

**Comment by gauravano** [comment]
Great!


Gaurav Sachdeva

**Comment by dinaelhanan** [comment]
@gauravano @sagarpreet-chadha hey! I'm still looking to solve this, but I was hoping for some direction. Please see my above message. Thanks!

**Comment by sagarpreet-chadha** [comment]
Hi @dinaelhanan !

The 2 recommendations are these : 
<img width="1074" alt="screenshot 2018-12-21 at 12 31 16 pm" src="https://user-images.githubusercontent.com/14952645/50329258-639d7f00-051c-11e9-9957-fc160e150171.png">

First one says that we have to convert this field to following form/syntax : 

`joesmith@example.com (Joe Smith)`

The second recommedation i belief is saying that we have to add this tag : 

`<atom:link href="https://publiclab.org/feed/oorjit_chowdhary.rss" rel="self" type="application/rss+xml" />`

within the `<channel>` tag , which we already have . See this line : 
https://github.com/publiclab/plots2/blob/7d8249ca65885adbf75184701a420785c63661a9/app/views/tag/rss.rss.builder#L5

I think it is saying to add **rel="self"** attribute to the above **link** tag . What do you think ?

**Comment by sagarpreet-chadha** [comment]
Awesome 😄 !
