### ISSUE TITLE
'Link social media' button doesn't work

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4281]
### Please describe the problem (or idea)
The `link social media` button doesn't work. 
It displays a dimmed screen. I'm guessing that's for a modal to appear but nothing happens.

![social media link error](https://user-images.githubusercontent.com/39333058/49860550-091b6900-fe20-11e8-8e6d-af5748551ad0.gif)

https://github.com/publiclab/plots2/blob/bb48d317502e73f6e236c7870e74da174e021050/app/views/users/profile.html.erb#L216-L235

There seems to be a modal, which isn't appearing for me.

### Please show us where to look

https://publiclab.org/profile/oorjit_chowdhary

### What's your PublicLab.org username?

oorjit_chowdhary

### Browser, version, and operating system

Chrome, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by oorjitchowdhary** [comment]
@publiclab/reviewers What could be done here

**Comment by gauravano** [comment]
I think there is a bug in action. Looks screen color fades but modal content was unable to show. @oorjitchowdhary would you like to open FTO from this issue. Thanks!

As Oauth would take time, quick fix would be to fix the existing. @SidharthBansal thoughts?

**Comment by SidharthBansal** [comment]
Quick fix is fixing the modal

**Comment by SidharthBansal** [comment]
We should aim at quick fix here first

**Comment by oorjitchowdhary** [comment]
> We can try to fix it. Current fix is display of the modal. I know the further steps, but let's fix the frontend first.
> Please check this out at publiclab.org and unstable and tell me the behaviour.

The same behaviour is there with unstable

**Comment by thesparks** [comment]
I changed 834 (at rendered view) and it works!
What is this code for? When I was working on this popup, this code did not exist.
`  .modal-content{
       opacity: 0;
  }`
![image](https://user-images.githubusercontent.com/17945250/50385231-ccdfe680-0704-11e9-863d-e315c0092d43.png)
![image](https://user-images.githubusercontent.com/17945250/50385250-2a743300-0705-11e9-9d91-9c7185b73f6e.png)

**Comment by sagarpreet-chadha** [comment]
Hi...this is great !

I think you can open a PR for this .
Before opening the PR can you test if this works fine in different window size ?
Also can you check whether this code was changed recently because it used to work fine before .

Thank you :)

**Comment by thesparks** [comment]
@gauravano Hi. I am busy studying now, I need a lot of things to pass. Maybe someone else wants to work on this?

**Comment by IshaGupta18** [comment]
@gauravano can I create a PR for this then? Would it be okay?

**Comment by gauravano** [comment]
No issue @thesparks and all the best! Yes @IshaGupta18 please go ahead. Thanks both of you :smiley: !

**Comment by IshaGupta18** [comment]
#4425 is the link to my PR for this issue. I am waiting for approval @gauravano and hope everything works out! Thanks a lot. A special thanks to @thesparks for helping out on this issue!
