### ISSUE TITLE
Multiple Tag Subscriptions

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4283]
We need to offer users to subscribe to multiple tags simultaneously on clicking a single button.
We will be prompting users the following at multiple web pages
![image](https://user-images.githubusercontent.com/20972099/49863922-5d761700-fe27-11e8-8342-c84fc875d9b8.png)
so that user is able to select tags and get subscribed to the website.
In this issue, we are focussing on the backend. When the user is logged in and tries to subscribe to multiple tags.
One application of this is #3932. Other applications are being discussed in #3924 and are summarized in #4131.

**Comment by jywarren** [comment]
These are controller methods, right? Awesome!

**Comment by SidharthBansal** [comment]
Yeah, a little functionality of controller and some of model.
We will be integrating model functionality in multiple controllers. I hope so. Let's build this one first.

**Comment by SidharthBansal** [comment]
I think we need to modify the comments controller action to follow/unfollow tags.
https://github.com/publiclab/plots2/blob/4adee51f1ee92fc7e50bd236b6836f3e84c9d911/app/controllers/comment_controller.rb#L18
We can have the function for the radio button functionality in the https://github.com/publiclab/plots2/blob/4adee51f1ee92fc7e50bd236b6836f3e84c9d911/app/models/tag_selection.rb#L1.
We can use the function created in the model at the nodes(wiki/research notes/comments etc. )
I think the model is correct.

**Comment by SidharthBansal** [comment]
I am making some changes in the PR #4296. These will be generic changes so that we will be able to use it throughout the website.
Initial steps will be slow but later on we will catch up them in short period of time.

**Comment by SidharthBansal** [comment]
Fixed in #4340.
