### ISSUE TITLE
Hide 'Test Digest Mail' from production

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4286]
Made from #4280 
### Problem
The `Test Digest Mail` button should not appear in the production server.

![screenshot 113](https://user-images.githubusercontent.com/39333058/49859371-68c44500-fe1d-11e8-9edc-0afcb649e569.png)

### Code link
https://github.com/publiclab/plots2/blob/58d5ea84462f6117ce55830aeb8657eca3e5ac7a/app/views/users/profile.html.erb#L237-L241

**Comment by gauravano** [comment]
Hi @oorjitchowdhary @uzorjchibuzor this button was added by @ViditChitkara for testing his GSoC project. I think, it should appear in front of moderators and admin only. So, please add condition accordingly. Thanks!

**Comment by gauravano** [comment]
I know it's for testing but you can change the button style to match other buttons.

**Comment by uzorjchibuzor** [comment]
>Hi @oorjitchowdhary @uzorjchibuzor this button was added by @ViditChitkara for testing his GSoC project. I think, it should appear in front of moderators and admin only. So, please add condition accordingly. Thanks!

@gauravano so it should appear in production if the user is an admin or moderator?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by uzorjchibuzor** [comment]
The way it currently is the button only appear when not in production, it doesn’t take the user status into account. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gauravano** [comment]
Yes @uzorjchibuzor it's fine to show button in production to moderators and admins.

**Comment by uzorjchibuzor** [comment]
>@uzorjchibuzor Would you like to work on this issue? ...

@oorjitchowdhary Thanks, I had a PR pending that removed the button from production I am going to push a commit that takes the status of the user into account instead of the environment. I will change the style to match other buttons too while at it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by oorjitchowdhary** [comment]
Oh great..
