### ISSUE TITLE
Subscription controller redundant code

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4290]
@jywarren can you please look 
https://github.com/publiclab/plots2/blob/9101cc118ba1c882738882948a451903837770ea/app/controllers/subscription_controller.rb#L75-L78
I guess this comment means that we need to make a feature for the user(#4164) and node(ie note + wiki + map + question) subscription.
If we are looking for these then we should leave it as it is.
Else we should trim the controller's action.
How shall we proceed here?

**Comment by jywarren** [comment]
I think perhaps we should focus on proximity-based following in #4551 and leave aside following individual users for the time being. We do have a way to follow nodes -- using `node_selection` and likes. How does that sound?

**Comment by SidharthBansal** [comment]
Someone is working on this in some PR now. Community is increasing so its hard to keep an eye on duplicate issues.
Closing this one.

**Comment by SidharthBansal** [comment]
Jeff you gave permission to follow users in some issue. So, someone has started working in some issues. Can't find it right now. When I will find. I will link issues together.
Thanks
