### ISSUE TITLE
Email sent for Comment to Answer has Wrong ID

### ISSUE THREAD

**Issue by kevinzluo** [publiclab/plots2#4291]
Hello,
I have been testing out the reply to email service and happened upon this error.

The ID for this question is 45, and the ID for this answer is 2. The email sent should have ID (#a2), but it sends as (#a45). 
![emailiderror](https://user-images.githubusercontent.com/44309027/49916077-bd3be480-fe5e-11e8-8514-f1b65282f1b6.gif)

**Comment by kevinzluo** [comment]
I believe the issue is a combination of these lines: https://github.com/publiclab/plots2/blob/9a4e753b551055ba78f8ace397f01ad1c9766aeb/app/mailers/comment_mailer.rb#L47
https://github.com/publiclab/plots2/blob/9a4e753b551055ba78f8ace397f01ad1c9766aeb/app/models/comment.rb#L155-L157

The fix will depend on whether we want to send it with the answer id or question id. I think this is associated with #4094.

**Comment by jywarren** [comment]
Ah this is a great catch. If you want to decide which makes more sense I
support your call on this! Thanks!!!

**Comment by kevinzluo** [comment]
I feel we should use the answer ID so the reply to email service will work. Otherwise the comments will be posted to the parent question.

**Comment by gauravano** [comment]
Hi @kevinzluo would you like to solve this issue? here's the entry point where mail is directed after pulling via mailman - https://github.com/publiclab/plots2/blob/master/app/models/comment.rb#L213-L226

let me know if you need any help. Also, @namangupta01 has implemented reply by mail feature, so you expect help from him. 
Thanks!

**Comment by kevinzluo** [comment]
Yeah I would love to solve this one. I am a bit busy right now so I won't be able to do it immediately. On the subject of reply by mail, could you check out my PR #4212 ? It is ready and implements reply by email for outlook.

**Comment by gauravano** [comment]
Hi @kevinzluo please take your time. Thanks!

Seeing PR #4212

**Comment by jywarren** [comment]
I bet this is now complete due to fixes by @noi5e !! Closing, but re-open if I'm wrong! Thanks!
