### ISSUE TITLE
Planning for holistic improvements

### ISSUE THREAD

**Issue by esylvan** [publiclab/plots2#4301]
PROBLEM: Public Lab has many amazing projects that are all available on the PL website. But PL has not been able to do a holistic review of the user experience and users, especially new or lightly engaged ones, might be confused by what they can do.

GOAL: We want people to find it easy to come to the site, find a sub-community they want to engage with, and then know what they can do with the community. Our approach can be guided by two key main takeaways we want people to get from the site:

- what is Public Lab and what does Public Lab do
- what can I/a given user do with Public Lab

In particular we want to provide this clarity for topical and regional communities of practice.

APPROACH: Public Lab's user interface would benefit from a holistic review of what could be improved. Here is one potential approach we can discuss. 
* create very brief user stories for key user goals on the site. Examples:
  * new user who wants to know what happens at Public
  * new user who wants to engage in a particular location or project
  * existing user who wants to to engage in a particular location or project
  *  existing user receives a notification about something they followed and follows a call to action based on it
  *  better examples?
* Based on these stories, develop guidelines for specific sets of pages or interactions, such as what to do with different notifications.
* Create issues that define the implementation of these guidelines.
* when PL code contributors work on areas that have been reviewed, ask them to link to/review the stories and link to/follow the guidelines developed.

**Comment by esylvan** [comment]
@jywarren @steviepubliclab Hey there! Here's my sketch of what we might do, for conversational purposes. Feel free to put this issue or label it as I cannot do it myself.

**Comment by jywarren** [comment]
Thanks! Will get into this more soon but just to note @ebarry has led a lot of work on understanding roles, motivations, and inputs/outputs of our community, documented in part here, which she may be able to chime in with starting Monday. Thanks!

https://docs.google.com/presentation/d/12NU6V9UFeOWKJrql8AIQZI3mKUWTuakF8zrGpOlgrNg/edit#slide=id.g20a7a15029_0_0

**Comment by jywarren** [comment]
Also chiming in with @edieblu @SidharthBansal who's also working on some more specific UI projects. @esylvan was on our OpenHour and is interested in doing a big overall, holistic UI analysis with us. Just connecting everyone together!

**Comment by jywarren** [comment]
@publiclab/reviewers -- and also, please checkout out @edieblu's work up here: https://publiclab.org/notes/edie_blues/12-13-2018/public-lab-dashboard-new-design-ideas

**Comment by esylvan** [comment]
Thanks, @jywarren. I've checked out @ebarry 's doc and @edieblu  and look forward to talking more about it.

**Comment by SidharthBansal** [comment]
Hi all,
We are building login and signup modal for the better user interface. You
can check you the work going on in OAuth milestone.
Thanks everyone.

**Comment by oorjitchowdhary** [comment]
I think #4274 could also be related here..

**Comment by jywarren** [comment]
Redirecting this to the great process over here! https://publiclab.org/notes/warren/05-07-2019/introducing-a-draft-style-guide-for-public-lab
