### ISSUE TITLE
Link comments under question to login modal

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4303]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all) made from #4132. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [show.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/questions/show.html.erb#L62) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

## Issue

Linking of the Login link to the login modal under the comments
![image](https://user-images.githubusercontent.com/20972099/50025409-7d663000-000b-11e9-8fd0-e368ee63f916.png)

## Solution
Change the 

https://github.com/publiclab/plots2/blob/master/app/views/questions/show.html.erb#L62

to 

```ruby
<p><a data-toggle="modal" data-target="#loginModal">Log in</a> to comment</p> 
```

and please attach a GIF showing the opening of modal on clicking the Login link.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by gauravano** [comment]
Hi @SidharthBansal I converted it to FTO, I hope this issue isn't a priority. Thanks!

**Comment by SidharthBansal** [comment]
Please link the fto number here.
Thanks

**Comment by eli6** [comment]
Hi, I am new to open source and I'd like to try this out! Is it available?

**Comment by gauravano** [comment]
Hi @eli6, Welcome to Open Source and Public Lab :smiley:. Yes, it's available to claim. Thanks!

**Comment by eli6** [comment]
@gauravano Thanks! One question: is the " and a GIF showing the opening of modalon clicking the Login link" really part of the line to be added?

**Comment by gauravano** [comment]
No, that's not a part of the code. Actually, for minor frontend modifications, we ask contributors to attach a GIF of the modified part with their PR so that PR reviewing can be done fastly.

Clear now?

**Comment by eli6** [comment]
Ok thanks 👍 Yes it's clear now! I just wanted to double check since it was code-formatted

**Comment by gauravano** [comment]
Oops, that's me. Edited!

**Comment by oorjitchowdhary** [comment]
Hi, I think I had added login modal for comments on /notes and I believe the /questions page uses the same comments file.. You can check at #4215..
Apologies if I'm wrong

**Comment by SidharthBansal** [comment]
Hi, I checked your changes at my localhost. We use same partial but here also we need to link it to the modal. This button was redirecting to the /login hence @gauravano and I made an issue collaboratively.
