### ISSUE TITLE
Improper css formatting of 'Ask a question' suggestions

### ISSUE THREAD

**Issue by rexagod** [publiclab/plots2#4304]
**Problem:** The suggestions appear to be out of the parent element. I think this is a responsiveness issue, because on adjusting the width of the viewport, the issue ceases to exist.

![screenshot from 2018-12-15 03-56-12](https://user-images.githubusercontent.com/33557095/50033185-70523c80-001d-11e9-9604-170a5bec9f90.png)

![screenshot from 2018-12-15 03-29-58](https://user-images.githubusercontent.com/33557095/50032954-97f4d500-001c-11e9-9586-1cb200a5cb11.png)

**Fix:** I think removing the 'width' attribute entirely from the #questions_searchform .dropdown-menu would fix this.

![screenshot from 2018-12-15 03-32-13](https://user-images.githubusercontent.com/33557095/50032956-988d6b80-001c-11e9-8595-8f09b8aa1474.png)

**Also, I think maybe we should mark this as a `first-timers-only` issue.**

**Comment by sashadev-sky** [comment]
@rexagod good find! That idea does fix the issue of the text going outside of the dropdown, but it creates a new one where the dropdown stretches as far as the text goes:
<img width="1205" alt="screen shot 2018-12-14 at 8 48 35 pm" src="https://user-images.githubusercontent.com/41092741/50037692-2a2bb780-ffe2-11e8-820c-e8545ea969ec.png">

Maybe we could impose a maximum number of characters on the question preview and add a "..." at the end? Let me know what you think!

**Comment by rexagod** [comment]
Hey I think I can fix this. Can I work on it?

**Comment by SidharthBansal** [comment]
Yeah sure

**Comment by gauravano** [comment]
@rexagod you can proceed and yes, you can use the suggestion given by @sashadev-sky about limiting the char length. Thanks @sashadev-sky !

**Comment by rexagod** [comment]
@publiclab/reviewers Check out #4316.
