### ISSUE TITLE
Profiles search results layout issue

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4310]
Hi @cesswairimu and @milaaraujo - just noting a small layout issue on this page which should be a quick fix if you're available to help on this? 

![image](https://user-images.githubusercontent.com/24359/50037396-aa501e00-ffde-11e8-8b32-889df3b6180a.png)

If anyone else has time to work on this, we'd really appreciate it too!

**Comment by oorjitchowdhary** [comment]
I had added the new list design with the profile pictures here in the search in #4130 .. I think the previous layout got overlapped on it and the code for it wasn't deleted.. But that is weird

**Comment by gauravano** [comment]
Hi @oorjitchowdhary thanks for the tip. I am checking the master. Thanks!

**Comment by jywarren** [comment]
We should be able to solve it with some changes to the bootstrap column classes, i think?

**Comment by cesswairimu** [comment]
Oh, I think @oorjitchowdhary and I did changes to the profile search results simultaneously. I added the user-tag search results #3911  and he altered how the `search by username and  bio` were being displayed. I still cannot get results to display for search by username and bio locally so I can replicate the bug. Any idea how I can get the profiles to return results? I would love to fix this.
