### ISSUE TITLE
Optional Image while SignUp

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4311]
@jywarren we have sidebar to add image at /profile/edit but we don't have any image upload option at the /signup.
Can we have an optional image upload in the signup?

**Comment by jywarren** [comment]
Hmm maybe there's an issue with not having a uid to assign yet? We could
have it be a prompt immediately after creating an account, maybe?

**Comment by SidharthBansal** [comment]
@IshaGupta18 may be you will be willing to work on this.

**Comment by IshaGupta18** [comment]
In the sign up modal or sign up page, I think we can add an optional button with a popover. On clicking on that button, they can add a profile picture is the wish to which can be shown in a circular layout in the popover. What do you think?

**Comment by SidharthBansal** [comment]
That would be best I think.

**Comment by IshaGupta18** [comment]
Hey I think a collapse would look better because it would be cleaner and won't overlap with other fields. What do you think?

**Comment by SidharthBansal** [comment]
Can you provide the screenshots for it before working on pr for it?

**Comment by IshaGupta18** [comment]
@SidharthBansal will it be okay if I take some time for this issue, because image uploading and stuff is new to me, so I'll have to figure that out first?

**Comment by SidharthBansal** [comment]
Sure

**Comment by IshaGupta18** [comment]
Thanks a ton!

**Comment by SidharthBansal** [comment]
Hi image upload is already present at the sidebar of profile. We want it
similar for the signup modal. It should be transfered to top. Then it will
be much appreciated.
Thanks Isha.

**Comment by IshaGupta18** [comment]
Where exactly at top would you like it?

**Comment by SidharthBansal** [comment]
At left hand side, I guess

**Comment by IshaGupta18** [comment]
But there is no left side in the modal

**Comment by IshaGupta18** [comment]
And the same form is being rendered on the sign up page and in the modal

**Comment by IshaGupta18** [comment]
Also, if we look at this way, int his layout, after uploading the image, only that robot captcha is left.. so probably it would be suitable. What do you think?

**Comment by SidharthBansal** [comment]
I am saying like
Profile_image Providers
Sign_up_form

**Comment by IshaGupta18** [comment]
Okay, so just below "Sign up to join public lab community" and on the left side of oAuth providers, right?

**Comment by SidharthBansal** [comment]
Yeah I think that will be the best option. What do you think?

**Comment by IshaGupta18** [comment]
Okay, let me try it and show you a screenshot!

**Comment by IshaGupta18** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/40794215/50722606-85d7f500-10f7-11e9-941b-24a9d14a40f1.png)

**Comment by SidharthBansal** [comment]
Let's create the form at 1 column instead of 2 column then the image will
be adjusted accurately.
Thanks Isha

**Comment by IshaGupta18** [comment]
Okay let me see, probably I can adjust this image here too properly, I will try it out okay?
Thanks a lot!

**Comment by IshaGupta18** [comment]
How's this?
![image](https://user-images.githubusercontent.com/40794215/50723068-a35c8d00-10fe-11e9-85f4-b4d97707f65b.png)

**Comment by SidharthBansal** [comment]
Providers
-------------------
image(1st half)   Username
Image(2nd half) Email
Password   Password Confirmation
Bio Text Area.....
Submit
I was trying to suggest this. Sorry for the misunderstanding. Apologies.

**Comment by IshaGupta18** [comment]
Oh that's okay, not a problem. How does this look?

![image](https://user-images.githubusercontent.com/40794215/50723417-647d0600-1103-11e9-8552-ea835e1de9dd.png)

![image](https://user-images.githubusercontent.com/40794215/50723420-7068c800-1103-11e9-9b44-30e54ffea0ec.png)

**Comment by SidharthBansal** [comment]
You missed the circular shape image. Let's add a default image there if no
image is uploaded by the user.

**Comment by IshaGupta18** [comment]
Is this okay?

![image](https://user-images.githubusercontent.com/40794215/50723903-35b65e00-110a-11e9-80ac-3f39061e10fa.png)

**Comment by IshaGupta18** [comment]
Sir that is not a problem, this image is just in a form tag and is submitted along with the rest of the information and is displayed at the profile page of the user. Also, this preview is just through js.

**Comment by IshaGupta18** [comment]
About it being responsive, I am unable to make a gif and show it to you, but it's working just fine on different screen sizes!

**Comment by IshaGupta18** [comment]
![image](https://user-images.githubusercontent.com/40794215/50727020-f2c0ae80-113a-11e9-9403-d1f3cd11c7ee.png)

![image](https://user-images.githubusercontent.com/40794215/50727023-ffdd9d80-113a-11e9-9cfe-4f9879317500.png)

See, is this okay? I hope that your concern was resolved!

**Comment by jywarren** [comment]
Ah awesome! Thanks and great work! Also no need to say sir! :-)

>

**Comment by IshaGupta18** [comment]
Thank you :smile: so I am creating a PR now.

**Comment by SidharthBansal** [comment]
Great

**Comment by SidharthBansal** [comment]
Can you please confirm that the image is present after successful sign up
on the profile page?
Thanks, I will review tomorrow. Its 1-35 am here. Good night.

**Comment by IshaGupta18** [comment]
> ![image](https://user-images.githubusercontent.com/40794215/50727020-f2c0ae80-113a-11e9-9403-d1f3cd11c7ee.png)
> 
> ![image](https://user-images.githubusercontent.com/40794215/50727023-ffdd9d80-113a-11e9-9cfe-4f9879317500.png)
> 
> See, is this okay? I hope that your concern was resolved!

See this... I hope this is okay? 

Its 1:35 am here too, Good Night! Thanks a lot!

**Comment by SidharthBansal** [comment]
I thought that was default image. Sorry for the misunderstanding

It looks great. I will review the code after getting up in the morning.
Sleeping now. Its midnight. You should also sleep.

**Comment by gauravano** [comment]
Hi @jywarren @SidharthBansal @IshaGupta18, I want to make a suggestion regarding the design.  
I guess this image present below is finalized design, but I think, it's looking unorganized a bit as image field is not looking that good with 2 input fields.
![image](https://user-images.githubusercontent.com/40794215/50727020-f2c0ae80-113a-11e9-9403-d1f3cd11c7ee.png)

I would suggest this design :
![profile_image](https://user-images.githubusercontent.com/20878070/50729766-5069f080-1165-11e9-85d2-e449589bc79a.png)

Here, we would be keeping the start of form organized and also bio doesn't need that much space 30% of bio field space can be shared with profile image and yes, placing that field left or right can be decided by comparing only. Not critising the current design just making a suggestion.

Thanks!

**Comment by gauravano** [comment]
I just noticed that PR #4538 is ready so we can keep the above design as a suggestion for the future optimization. Thanks and nice work @IshaGupta18 !

**Comment by IshaGupta18** [comment]
Absolutely! This is how it looks in mobile view
![image](https://user-images.githubusercontent.com/40794215/50739073-b9527680-1200-11e9-9ba0-a0ea8ab55baf.png)

**Comment by SidharthBansal** [comment]
Great

**Comment by jywarren** [comment]
Yes let's open a new issue for @gauravano's suggestion! This is looking good; but perhaps we should make the image a bit smaller (even half the size?) -- so it doesn't push content down too much, especially in mobile view? Can you also add an underline to "Choose image" ? 

Thank you!

**Comment by SidharthBansal** [comment]
I agree with Jeff.
Moved to #4538.

**Comment by IshaGupta18** [comment]
Okay @jywarren ! Should I reduce the size of the image in this one only? Or should I implement the deisgn by @gauravano and do that there?

**Comment by jywarren** [comment]
let's just make the small change in this one, and we'll
address @gauravano's design in a follow-up. Thank you!

**Comment by IshaGupta18** [comment]
Is this better?
![image](https://user-images.githubusercontent.com/40794215/50849243-69a8b200-139c-11e9-8921-d8c6ef872f37.png)

**Comment by jywarren** [comment]
I still think it's a little close to "Choose a Password" - could you add
10px more margin under it? Thanks!

**Comment by jywarren** [comment]
Hi! Thanks! Do you think you could add just 10px more vertical margin where I've highlighted here?

![image](https://user-images.githubusercontent.com/24359/50932150-ba6aea00-1432-11e9-9fd3-5ac76b78a11f.png)

It'll look a little less cramped. Thanks!

**Comment by jywarren** [comment]
Could you share one more screenshot, thank you!!!

**Comment by IshaGupta18** [comment]
Absolutely sit, I should have done that along the way

![image](https://user-images.githubusercontent.com/40794215/51011742-af71a000-157f-11e9-87f2-d47486b1ece1.png)
