### ISSUE TITLE
improve pagination of dashboard page for mobile view

### ISSUE THREAD

**Issue by avsingh999** [publiclab/plots2#4314]
when open https://publiclab.org/dashboard this page in mobile view then it's pagination not looking good.I think this page need to improve.
It look like this.
![pub2](https://user-images.githubusercontent.com/25536022/50045083-30d62f80-00b3-11e9-953a-52b0ecaa7b47.png)

Thank you : )

**Comment by jywarren** [comment]
Good idea! We use the will_paginate gem to do this; maybe there's a
configuration that could be changed?

**Comment by oorjitchowdhary** [comment]
Could you explain me this issue?.. What is to be changed regarding the pagination bar?

**Comment by avsingh999** [comment]
I think it must be look like this

![pub4](https://user-images.githubusercontent.com/25536022/50321948-3390b480-04f9-11e9-8417-4642dcab9eac.png)
