### ISSUE TITLE
Move statistics methods out of user.rb into a model/concern file, add unit tests

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4317]
Hi @cesswairimu this is just a suggestion but we have a range of different statistics related methods in user.rb like `weekly_note_tally` which really make the file super long. I was wondering if we might try to move them to a separate file somehow - maybe a concern, or some other type of sub-file, to help make the user.rb file more readable and short. What do you think of this idea?

**Comment by cesswairimu** [comment]
I love the idea will add it to the milestone. Thanks.

**Comment by jywarren** [comment]
🎉
