### ISSUE TITLE
Integration Tests for Spam Away

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4321]
>>I think we should have a test for this sequence with realistic parameters for spamaway, as it made me uncomfortable that it errored but the tests passed. 

see https://github.com/publiclab/plots2/pull/4209#issuecomment-447652453 and https://github.com/publiclab/plots2/pull/4209#issuecomment-447645413 for reference.

We need some tests to ensure that the spam away works fine on the localhost.
Let's build it @jywarren.
Refer #4209.

**Comment by SidharthBansal** [comment]
Refer #3990 for the implemented work.
Spam away is only for the development mode as the reCatcha does not work on the locahost.

**Comment by gauravano** [comment]
User has option to switch to spamaway in production too?

**Comment by SidharthBansal** [comment]
No, just for the production, Jeff created Spam Away I guess.
ReCatcha does not work at the development mode.

**Comment by gauravano** [comment]
Yes, I am aware that recaptcha doesn't work in development and also not on `unstable`.

**Comment by SidharthBansal** [comment]
I was not aware of the fact that it does not work on unstable. Thanks @Gaurav
Sachdeva <sachdeva.gaurav1997@gmail.com> .It solved #4209's some subissue.

**Comment by gauravano** [comment]
Hey @SidharthBansal it wasn't working before on `unstable` but I just tested signup via modal on `unstable` and identify the items check is coming. So working!

**Comment by SidharthBansal** [comment]
Yeah, Jeff made some changes and now it is working. Thanks for your help.

**Comment by SidharthBansal** [comment]
@VladimirMikulic @Uzay-G any of you guys want to add tests quickly here?

**Comment by SidharthBansal** [comment]
Although it is integration test, we can mark them under system test task as integration tests also have similar complexity as the system tests. Who is aiming to solve this? May be someone else apart from you two

**Comment by sssash18** [comment]
@SidharthBansal I would like to add the test for the case when spamaway text area is not blank.Could I proceed with this?

**Comment by VladimirMikulic** [comment]
@sssash18 go on :)

**Comment by sssash18** [comment]
@SidharthBansal @VladimirMikulic @Uzay-G  Kindly review the added test

**Comment by sssash18** [comment]
@SidharthBansal @VladimirMikulic @Uzay-G Are thier any other tests that I can help in adding?

**Comment by VladimirMikulic** [comment]
@sssash18 thank you for the interest, right now we are focusing on system tests. We could use some help :)

**Comment by sssash18** [comment]
@VladimirMikulic Let me know how I can help

**Comment by VladimirMikulic** [comment]
Let's first resolve the Travis, shall we? :smile:

**Comment by SidharthBansal** [comment]
Sure
