### ISSUE TITLE
Feature code under Sign Up Modal

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4322]
As per the gitter chat,
@jywarren asked
>>But I think we need to show the info text and the notice about open source and code of conduct. Maybe we need a Feature just below the sign up form to be able to add customized content.
 It'd be a pretty easy addition, the feature code is one line.

Let's turn this into a first timers only issue @gauravano @jywarren !!!

**Comment by gauravano** [comment]
This issue will be proceeded once the feature is created by one of the admins. @jywarren whenever you would be done with the feature please add the name of feature below and we will turn it into FTO. Thanks!

**Comment by oorjitchowdhary** [comment]
Can you point out the exact line that needs to be added.. I'll make it into a `first-timers-only` issue

**Comment by SidharthBansal** [comment]
@jywarren it will be great if you can tell us on this. As you asked for this feature. It is little ambiguous to me.

**Comment by SidharthBansal** [comment]
You can tell the text we will turn it into fto.

**Comment by jywarren** [comment]
Oh, i'm sorry - it looks like it was done here: 

https://github.com/publiclab/plots2/commit/2a1f98dcc84e598d27fbd124845e7613fcb7c008

But it looks like it got mistakenly removed here, maybe during a rebase: 

https://github.com/publiclab/plots2/commit/4fa3343c7e87528f7ab8ffecf661efe4c93ead74#diff-476e45acd5b545a090eb0f774aff07dbL78

I'm going to re-add it and close this issue, thanks!! But we could definitely use help with #4634 if you're interested!

**Comment by jywarren** [comment]
Submitted fix in https://github.com/publiclab/plots2/pull/4635 !
