### ISSUE TITLE
Weekly Community Check-In #1

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#4327]
Hi everybody :smiley: !

We all at Public Lab :balloon: - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. Let's start a Community Check-In from this week onwards, where every community member would share something about their work from the past week and about their current week's goal :dart:. You are also welcome to share fun-fact :smile: , new ideas :bulb: , your learning goals :ballot_box_with_check: . 

If you're new here, welcome, and please comment a _Hello message_ below, we would love to work with you. If you're looking for new issues, please try some of our [first-timers-only issues](https://code.publiclab.org/#r=all). 
 
We're SO EXCITED to have your help!

**Is there anything, you would like to share with us from past week's work? What is your plan for this week?** 

If you have not planned yet, just leave a Hello! so that we know that you are in sync with us :arrows_clockwise: and doing well!

The coming weeks will be absolutely full of code :computer: , tasks :spiral_notepad:, fun :tada: and excitement :smiley:!!

As always, if you're waiting for a review, or if you're stuck, please request help here OR leave a comment with @publiclab/mentors @publiclab/reviewers for some input. 🙌 

Have a GREAT week :tada:  !

Thank you !

/cc 
@thesparks @faithngetich @DakshGondaliya  @mohitRJranjan @milaaraujo @kevinzluo 
@stefannibrasil @gauravano @ViditChitkara @tech4GT @mridulnagpal @namangupta01 @sagarpreet-chadha @Souravirus @jywarren @MayankKashyap @siaw23 @ryzokuken @ccpandhare @icarito @steviepubliclab @ebarry @jywarren, @sagarpreet-chadha, @icarito, @JonathanXu1, @uzorjchibuzor, @eli6, @kevinzluo, @ValentinaTironi, @rexagod, @sashadev-sky, @IshaGupta18, @milaaraujo, @dinaelhanan, @cesswairimu, @dependabot[bot], @oorjitchowdhary, @okonek, @wanzulfikri, @mohitRJranjan @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @vishalka98 @publiclab/reviewers @Divy123 @pomyo @bhavayAnand9 @ovipa017-xamk @Mridul97 @avsingh999 @Rishabh570 @subhahu123 @aSquare14  @Radhikadua123 @faithngetich @quinn-codes-synthesis @amychan331 @mardelvalle @narnt @hydro-m @love-opensource @romanrodriguez @shubhangi-chauhan

Feel free to mention names of those contributors in comment below who have been missed.

**Comment by SidharthBansal** [comment]
Hi everyone,
I am tackling two projects this winter. They are login flow and
subscriptions flow project.

Regarding the December Project Progress
*Regarding Login flow Project*

   - Return_to anamoly solved
   - Modal integration to all the web pages across the web page is a much
   more immense challenge then we thought earlier.
   - It has opened a lot of issues(84 issues and PRs).
   - You can find the milestone here ->
   https://github.com/publiclab/plots2/milestone/18.
   - We completed 38 out of 84 till yet till now. Still, a lot more issues
   are needed to be identified and tackled.
   - More than 1/2 as login/signup modal is almost complete as


   1. Login Modal merged into master. Localhost/unstable testing of the
   login modal done.
   2. Sign Up Modal completed. Tested on localhost and unstable
   3. Integration of the modals (WIP).


   - Issues identified present at #4132
   <https://github.com/publiclab/plots2/issues/4132>.
   - Many pages integrated with Login/SignUp modals and are working
   properly on unstable like liking wiki, liking notes, posting comments,
   posting answers, etc.
   - Linking of login modal (WIP)

*Regarding the Subscription Project*

   - Listed under milestone https://github.com/publiclab/plots2/milestone/13
   - 7 Major issues have been identified
   - Different places for subscription project has been identified
   successfully and listed in #4131
   <https://github.com/publiclab/plots2/issues/4131>.
   - Creation of the Subscription button is under progress.
   - Linking subscription buttons to the login modal(WIP)

#4296 <https://github.com/publiclab/plots2/pull/4296> in progress. Right
now focusing on the login project. So, can't focus much in subscriptions.
Sorry. Will catch up here in a while @jywarren <https://github.com/jywarren>

**Comment by sagarpreet-chadha** [comment]
Hi everyone 😄 ! 

So i will be working on these issues in the coming weeks 🎈 : 

* Writing perfect documentation for integration of LEL .
* Integrating new LEL features with plots2 and mapknitter .
* Refreshing maps from API calls when panning/zooming/geolocating
* Fixing nearby tag maps (I just opened an issue... These keep breaking so I think we need a test for them)
* Getting leaflet blurred location to geocode properly and also show spinner icon on starting geocode


### Thank you 🌲 🎅 🤶 !

**Comment by Rishabh570** [comment]
Hi everyone :grinning: 

I'm currently working on `community-toolbox` project, it includes
 
- Shifting and structuring the whole project to have MVC pattern (done almost for all contributors and repo contributors list, recent contributors part is remaining)
- Switching from localStorage to indexedDB ( halfway through it).
- Adding tests (teaspoon-mocha/jasmine needs to be decided)

I'll try to produce some `fto` issues along the way :smile: 
Thanks!

**Comment by SidharthBansal** [comment]
Great Rishabh and Sagar

**Comment by cesswairimu** [comment]
Hey guys :hand:,

Last week I implemented statistics on questions vs answered and date-picker for selecting ranges on the stats page.
 I will doing some refactoring this week #4317 and #4147. 
Also I will be investigating and implementing caching of data content on various pages on the website #4138 . 
Thanks

**Comment by dinaelhanan** [comment]
Hi everyone!
Last week, I was quiet busy with final assessments. I'm currently planning on tying up some loose ends from GCI which is just 2 issues that have to do with linking login modals. I will be on break next week, and will have plenty of time to contribute to other issues. So for now, I haven't got anything planned. If there's any urgent issues that need testing or issues for the image-sequencer, I can really help out there (I don't know much ruby that well, so I'll stick to quick tasks for plots2 until I get comfortable with it.) I'm thinking of taking #4299 and any relevant issues. 
Looking forward to it!

**Comment by jywarren** [comment]
Hi, everyone! Love to see our Check-ins coming back. I'm traveling a lot this week but got to meet @icarito in person for the first time (amazing)!

I have been totally amazed at the cooperation we're seeing this past week. I know people have been putting a lot of energy into GCI and it's really great to see how this experience has given us new insights and strengths as we build cooperation in our community. 

Also a lot of big projects going on! Thank you to Sidharth and Gaurav and everyone else for helping to coordinate lots of different projects. It's great to see we continue to welcome newcomers.

I love the new "pinned issues" -- i added a couple more besides the check-in, so that we can encourage people to be mutually supportive (in addition to the "install plots2 for the first time" one!). Love to hear input or suggestions on this. 

Keep up the great work everyone and please to speak up here or in the chatroom if you get stuck on something! 

One neat thing I've seen recently is some increased participation in the PublicLab.Editor project, which has been a little neglected, but is getting some problems solved now!

* https://github.com/publiclab/PublicLab.Editor/pull/178 by @okonek
* and https://github.com/publiclab/PublicLab.Editor/issues/182 building on @okonek's work by @rexagod

👍 🎉 🎈 🙌

**Comment by sashadev-sky** [comment]
Hi all! 

This week I will be working on collaborating with other members of the community to open up issues on refactoring current code to make it less verbose. 

Thank you!

**Comment by ebarry** [comment]
Hi all! This week in code-related tasks i'm working on identifying a UI coordinator to run about 10 user research interviews in January, and working with @steviepubliclab to edit the call for interviewees: "are you dealing with environmental problems and have never used the Public Lab website? Please let us watch and listen as you navigate through Public Lab!"

Thanks Guarav for the help on the `redirect` tag yesterday, now https://publiclab.org/oil shows off our "Oil and Gas Accountability Toolkit"

@cesswairimu , i'm so excited that you are working on the Stats project. I'm the major user of the system, and am completely available to you if you ever want to connect. The Milestone looks super: https://github.com/publiclab/plots2/milestone/20 , perhaps we could create a planning issue where we can get into detailed planning of steps? Such a planning issue would also be a great place for us to have dialogue, and also feel free anytime to email me at liz@publiclab.org. Thank you!

**Comment by cesswairimu** [comment]
Thanks @ebarry, the idea of a planning issue sounds great I will create a planning issue for it later today.

**Comment by SidharthBansal** [comment]
You can create check boxes in the planning issue.
Please tick the checkboxes which you have achieved.
Nice idea Liz.

**Comment by gauravano** [comment]
How about using #3498 as planning issue, it already has checklist of tasks?

**Comment by ebarry** [comment]
yes, this is a great idea. We can reorganize the initial issue posting which Jeff created (It looks like you can edit that, right?). Let's try not to delete the "stretch goals" even if they will not be part of your work plan <3

**Comment by sagarpreet-chadha** [comment]
Posted a note explaining new features in LEL 😄 : 

https://publiclab.org/notes/sagarpreet/12-20-2018/new-features-in-leaflet-environmental-layers?_=1545288995

Kindly take a look 🙈  ! Thank you 🎄 ☃️ !

**Comment by jywarren** [comment]
Hi, all, love to see the activity here. 

@sashadev-sky what a great idea! We have some very long models, for one. CodeClimate makes some recommendations for refactoring and simplification, as well as reducing redundancy in it's "smells" system (funny name!): #3706 -- 

Also, the Outreachy program has made this week the week of "everybody struggles" -- we may adopt this for next week's Check-In, but just to share my own struggles:

This past week I have been continuing to try to remove the old DrupalUsers code in https://github.com/publiclab/plots2/pull/2857, and no matter how many errors I solve, another dozen or more appear -- it can be pretty frustrating! Never-ending, even. I'm getting closer though! Each time I open the Travis logs and hunt through for clues. We'll get there eventually, and hopefully this will dramatically simplify a lot of our users code by finally getting rid of the duplicated code of having 2 user models.

**Comment by SidharthBansal** [comment]
Moved to #4369
