### ISSUE TITLE
Editing a page as moderator not successful

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#4329]
I tried to "Edit" a page and after clicking Yes on the alert. I was redirected to home with /return_to=login and  alert generated

![return_to_wrong](https://user-images.githubusercontent.com/20878070/50105899-17b8b480-0254-11e9-8a08-a0107d469ba3.png)

Looks like there is something wrong with the conditions.

**Comment by gauravano** [comment]
@SidharthBansal return_to is conflicting in this case.

**Comment by SidharthBansal** [comment]
Please tell the steps which you have followed so that we can work upon this.

**Comment by gauravano** [comment]
Go to any research page and try to edit it as moderator. You will get redirected to "login" page. And,  when a user try to access login page with session then alert is shown like "You have to logout to access this page". That alert is shown.

**Comment by SidharthBansal** [comment]
This error is not related to any login or sign up modals first of all.

Can you please hard refresh and try this again?

**Comment by gauravano** [comment]
![edit_bug](https://user-images.githubusercontent.com/20878070/50218476-19988a00-03b2-11e9-8fc0-3b74848f5838.gif)

I will see the code.

**Comment by pdurbin** [comment]
This bug hit my radar today because I asked if anyone could fix that bad link (404) to https://publiclab/chat at https://publiclab.org/notes/warren/02-28-2019/call-for-summer-of-code-2019-proposals

**Comment by gauravano** [comment]
Actually, the alert shows that only admins, moderators, and co-authors can edit the page as a privilege but after going through Git blame- https://github.com/publiclab/plots2/blame/770b661d1c9b740693ff1e118cfcd56416cffa9b/app/controllers/notes_controller.rb, it looks like moderators were never given the privilege to edit the research note. 

So, it's a question for @jywarren @publiclab/community-reps that whether editing rights to a research note/question should be extended to moderators or not? If not, then, we should edit the alert. 

Thanks!

**Comment by jywarren** [comment]
I think we had better keep it to admins only; thank you @gaurav! So yes,
let's change the message.

**Comment by pdurbin** [comment]
@jywarren sounds good. Do what a separate issue to fix the 404 (the link to https://publiclab/chat )?

**Comment by gauravano** [comment]
Ok, then making a FTO for fixing the alert. @jywarren actually, many pages show  - https://publiclab/chat :see_no_evil:

**Comment by gauravano** [comment]
I just created 2 FTO issues for fixing this - one for alert https://github.com/publiclab/plots2/issues/5046 and one for hiding edit button to moderator - https://github.com/publiclab/plots2/issues/5047.

So, closing this one. Thanks @jywarren @pdurbin!
