### ISSUE TITLE
stop using spatial_adapter, debug sqlite setup to simplify installation

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#433]
and to enable use with sqlite databases

Read up: https://github.com/pdeffendol/spatial_adapter

But we only use it on the `geometry` column on this line of our schema: 

https://github.com/publiclab/plots2/tree/master/db/schema.rb#L52

 ````ruby
create_table "content_field_bbox", :id => false, :force => true do |t|                                                                                                        
    t.integer  "vid",                           :default => 0, :null => false                                                                                                   
    t.integer  "nid",                           :default => 0, :null => false                                                                                                   
   t.integer  "delta",                         :default => 0, :null => false                                                                                                   
   t.geometry "field_bbox_geo", :limit => nil                                                                                                                                  
 end
````

Looking at whether we can just change that to another column type. 

We should do this as a new migration instead of changing an old one; checking about removing `rake db:migrate` from the README.md as a result: https://github.com/publiclab/plots2/commit/bc4bb1d6ac984c3266972805a2d64870fe83063d

****

* [x] Looks like sqlite requires unique index names; `nid` is used twice by line 43 of the schema.rb. We should rename the indices uniquely and see if that works.
* [x] `SQLite3::ConstraintException: NOT NULL constraint failed: node_revisions.teaser` - remove not null?
* [ ] `ActiveRecord::StatementInvalid (SQLite3::BusyException: database is locked: INSERT INTO "rsessions" ("created_at", "data", "session_id", "updated_at") VALUES (?, ?, ?, ?)):` hmmm
* [x] figure out if sqlite is pre-installed on mac os
* [x] update README.md re: sqlite/mac
* [x] figure out sqlite group in Gemfile stuff: http://bundler.io/groups.html says `bundle install --without production` will actually persist in a `.bundle` file or something...
* [x] `ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: true: SELECT "tag_selections".* FROM "tag_selections"  WHERE (tid IN (2,3) AND following = true)` (maybe a true vs "true" issue)

****

Also: remember to squash the commits!

**Comment by jywarren** [comment]
OK, this seems ready to go, pending testing by other devs, or on Cloud9: #438. Closing and addressing any followup in that PR.

**Comment by ananyo2012** [comment]
@jywarren Shouldn't we keep spatial_adapter for the time being ? As you mentioned the geometry column in **content_field_bbox** table uses it. So migrations won't continue. It gives error with `rake db:migrate`

**Comment by jywarren** [comment]
Were you running rake db:migrate from a blank database? It should only be
necessary when adding new migrations -- to set up a complete database from
scratch, use rake db:setup.

Note that I dropped the geometry containing table in the sqlite merge. So
you shouldn't get one if you're starting a database from scratch.

@jywarren <https://github.com/jywarren> Shouldn't we keep spatial_adapter
for the time being ? As you mentioned the geometry column in
*content_field_bbox* table uses it. So migrations won't continue. It gives
error with rake db:migrate

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/publiclab/plots2/issues/433#issuecomment-201236097>

**Comment by ananyo2012** [comment]
@jywarren I did start a new database from scratch in mysql. What I did was
1. Ran `rake db:create`
2. Then I ran rake `db:migrate`
It is when I got the error saying undefined method geometry.

**Comment by jywarren** [comment]
Instead of those two steps, you should run "rake db:setup". It's not usual
to run migrate all the way from scratch when there are lots of migrations.

This makes sense because we did not remove the geometry column from the
migration history, just from the most recent migration. This allows older
databases to manage their state, adding and removing new tables, while
fresh databases just use db:setup to instantiate directly from the final
schema.rb.
