### ISSUE TITLE
Link Login modal to blog tag page

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4335]
We have a button to follow and unfollow on the tag/blog. We need to link it to the login modal if the person is not logged in.

**Comment by SidharthBansal** [comment]
![image](https://user-images.githubusercontent.com/20972099/50274234-bb77af80-0462-11e9-856c-0bb90031ce1d.png)
This is the Login button which @dinaelhanan you have fixed in your pr.

**Comment by SidharthBansal** [comment]
Thanks

**Comment by SidharthBansal** [comment]
I think it is not working.
Let us check it.

**Comment by dinaelhanan** [comment]
@SidharthBansal I don't think my PR fixed the blog one, I think it only fixes following tags.

**Comment by SidharthBansal** [comment]
I am trying to explain you that you did PR for this issue instead of the tag one. You have changed the wrong files. I merged it because we also need this blog change. Still the tag issue is not solved.
You targetted wrong file in the PR.

**Comment by dinaelhanan** [comment]
@SidharthBansal ok so if I understand correctly, the tag still doesn't have link to login modal. I understand that. I'm just wondering if the blog one that I accidently worked on is fixed? Because you re-opened this issue?

**Comment by SidharthBansal** [comment]
Neither of the two issues are fixed.

**Comment by dinaelhanan** [comment]
@SidharthBansal :/ ok I'll check it out :+1:
