### ISSUE TITLE
Enhance Wiki Section of plots2 repo

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4337]
@jywarren @gauravano I read through the wiki section. I think we should also enhance that.
I changed the name of ``Google Code In Tasks`` to supportive tasks so that it can be generic and can be used at multiple places like GSoC, RGSoC, Outreachy and GCI.
What other ideas you guys have?

**Comment by gauravano** [comment]
Discussion at #5848. Thanks you!
