### ISSUE TITLE
Refactoring profile.html.erb code pt.2

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/plots2#4342]
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

Our code in `app/views/users/profile.html.erb` is very verbose... we could use some refactoring

We can start by refactoring out a re-occuring line from the code. For now, the 1st line of:

https://github.com/publiclab/plots2/blob/1931439c0c799b3e3420a9dcaace7a54cf895bd4/app/views/users/profile.html.erb#L216-L223

## Solution

What to change it to: 

Refactor the line in the code block found in the "The Problem" section to use your new helper method instead. 

That line can be updated to `<% if current_profile_user %>`

Thanks!!

## Steps to Fix
 
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/plots2](https://github.com/publiclab/plots2)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by dave-light** [comment]
I'm yet to make an opensource contribution so this'd warm me up. May I claim this?

**Comment by gauravano** [comment]
Hi @dave-light, please go ahead. And, Welcome to Public Lab and Open Source World :globe_with_meridians: :earth_americas: .

**Comment by mzmmlds** [comment]
@dave-light : are you on it? or may claim this?

**Comment by dave-light** [comment]
Hey @mzmmlds, I'm on it.
