### ISSUE TITLE
UI Change for Edit Profile 

### ISSUE THREAD

**Issue by dinaelhanan** [publiclab/plots2#4347]
I went to go edit my profile, when I noticed that the prompt to add an image is below editing your bio and all that, which isn't very intuitive for users. Also, the header "bio" should be above the box where you edit your bio. I'm using the latest version of Firefox if that helps. We might even be able to make this a first-timers-only issue! (if the issue ends up being a quick fix) Lastly, when I didn't enter into the "confirm your password" field, I got an error which is good. However, once I entered the password, I couldn't save my changes again (save button disappeared).
Profile image field below bio:
![screenshot from 2018-12-20 21-21-25](https://user-images.githubusercontent.com/19677511/50321173-905e8180-049d-11e9-9fd2-9e174b5ff0e4.png)
header bio is misplaced:
![screenshot from 2018-12-20 21-23-13](https://user-images.githubusercontent.com/19677511/50321172-905e8180-049d-11e9-9eb5-db35e9c747f3.png)
save button disappeared: 
![screenshot from 2018-12-20 21-27-32](https://user-images.githubusercontent.com/19677511/50321291-33af9680-049e-11e9-9127-a66c05d0fbf8.png)

**Comment by SidharthBansal** [comment]
Hi localhost appears good to me on the Chrome browser.
![image](https://user-images.githubusercontent.com/20972099/50346556-beed6280-0558-11e9-9ef0-615182ac6718.png)
I will request @publiclab/mentors to please check the beviour at their end also.

**Comment by SidharthBansal** [comment]
Actually the recent changes has not been merged to the master.
As soon as they will get merge into the production branch. This error will be fixed.
Sorry for temporary distortion of the edit view.
Great Catch Dina!!! :balloon:

**Comment by dinaelhanan** [comment]
No problem! Glad I was able to help : )

**Comment by gauravano** [comment]
Hi @SidharthBansal @dinaelhanan closing this one as it's solved. Thanks!
