### ISSUE TITLE
Pagination is broken in 'Answered' tab at /questions

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4349]
### Please describe the problem (or idea)
The pagination is broken in the `answered` tab of questions.
Also, when clicked on a page number on the pagination bar, we come back at the `asked` tab on the next page.
> What happened just before the problem occurred? Or what problem could this idea solve?

![ask answer question error](https://user-images.githubusercontent.com/39333058/50340032-4928cd00-053f-11e9-9cd9-0be70e0600c1.gif)

### Please show us where to look

https://publiclab.org/questions/tag/question:general?page=2

### What's your PublicLab.org username?

oorjit_chowdhary

### Browser, version, and operating system
Chrome, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by oorjitchowdhary** [comment]
@publiclab/mentors

**Comment by SidharthBansal** [comment]
Hi thanks for catching the bug. We have many similar pagination bugs. Check them out too.

**Comment by kryptc** [comment]
Hi, could I work on this bug?

**Comment by SidharthBansal** [comment]
Yes go ahead.

**Comment by jywarren** [comment]
Fixed in #8689 ! Thank you!!!!
