### ISSUE TITLE
Image upload progress bar duplicating in create comment box.

### ISSUE THREAD

**Issue by ujithaperera** [publiclab/plots2#435]
### What happened just before the problem occurred
when a user is trying to edit a comment with a image. image upload progress bar appear in create comment box also.

### Browser, version, and operating system
safari , chrome
OSX

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by jywarren** [comment]
I think we need to create `comment.cid`-specific classnames for these
progress bars and ensure that we're activating the right ones. This'll be
in:

https://github.com/publiclab/plots2/tree/master/app/assets/javascripts/dragdrop.js

and/or

https://github.com/publiclab/plots2/tree/master/app/assets/javascripts/editor.js

**Comment by jywarren** [comment]
Oh i see you have a proposed fix; checking... thanks!

**Comment by ujithaperera** [comment]
yeah. I did use this kind of solution on #421. please have a look. thanks
