### ISSUE TITLE
Improve UI at 'Research notes' tab at /tags

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4350]
### Please describe the problem (or idea)
We can fix the aspect ratio of thumbnails of the `research notes` and fix them to a standard size for uniformity. 
Also, we can re-align and center the `Read more` buttons.

This one is related to #4198 and #4113.

> What happened just before the problem occurred? Or what problem could this idea solve?

![screenshot 126](https://user-images.githubusercontent.com/39333058/50340752-454a7a00-0542-11e9-8ae3-a73ba8a7ce3c.png)
![screenshot 127](https://user-images.githubusercontent.com/39333058/50340761-4f6c7880-0542-11e9-8791-df175d6517ff.png)

### Please show us where to look

https://publiclab.org/tag/spectrometer

### What's your PublicLab.org username?

oorjit_chowdhary

### Browser, version, and operating system

Chrome, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by oorjitchowdhary** [comment]
@publiclab/mentors

**Comment by kunalvaswani123** [comment]
Could I take this issue ?

**Comment by oorjitchowdhary** [comment]
I'd like @jywarren or @SidharthBansal to take a look at this first and then guide us through..
You could then take up the issue @kunalvaswani123

**Comment by avsingh999** [comment]
great @oorjitchowdhary , I am also agree with you

**Comment by gauravano** [comment]
Hi everyone, this issue can be divided in two parts-  Read more button centering and fixing image size. 
1. Anyone of you can solve the "Read more button" part, please tell here to avoid any confusion
2. Regarding Image issue, please coordinate with @dinaelhanan as she's working on it for quite sometime and know the issue well

Thanks!

**Comment by oorjitchowdhary** [comment]
@kunalvaswani123 Would you like to take this up?

**Comment by kunalvaswani123** [comment]
@oorjitchowdhary I could start with the read more button part ..

**Comment by oorjitchowdhary** [comment]
Ok cool!


On Dec 27, 2018, at 4:22 PM, Kunal Vaswani <notifications@github.com<mailto:notifications@github.com>> wrote:


@oorjitchowdhary<https://github.com/oorjitchowdhary> I could start with the read more button part ..

**Comment by kunalvaswani123** [comment]
@oorjitchowdhary I am traveling tomorrow .. I'll do as much as I can today and I'll resume work on 29 ..

**Comment by SidharthBansal** [comment]
Ok great. No problem.

**Comment by oorjitchowdhary** [comment]
You can create notes and add tags simply from the sidebar of that notes page..

**Comment by kunalvaswani123** [comment]
I added a note using write a research note button but it does not show that note in localhost:3000/notes

**Comment by kunalvaswani123** [comment]
it shows pending approval by community moderators in my dashboard ..

**Comment by oorjitchowdhary** [comment]
If you've used a non-admin account, you'll have to get it approved by either 'admin' or 'moderator' accounts.. 

If you use 'admin' or 'moderator' to write a new note, it gets published straightaway..

**Comment by kunalvaswani123** [comment]
It shows admin is banned when I try to login with admin..

**Comment by sashadev-sky** [comment]
@kunalvaswani123 I have not been following along closely enough with the banned admin issue to know why this is the case, but I have found a temporary workaround for using the admin account if you need it:

1) log on to moderator account (user: moderator pw: password) 
2) go to admin profile page
3) near the middle of the page on the right you should see a button 'unban user'. 
4) unban them then you can log onto the admin

**Comment by kunalvaswani123** [comment]
@sashadev-sky I tried it now .. I didn't get any moderator banned error .. is this issue solved ?

**Comment by kunalvaswani123** [comment]
I added a research note using share your work in dashboard using admin account and added a tag say balloon-mapping in it .. but when I see tag/balloon-mapping there are no research notes..

**Comment by sashadev-sky** [comment]
@kunalvaswani123 You're right. I reset my DB just in case and checked in rails dbconsole, admin not banned anymore. 

I did the same as you to check. Are you sure there are no notes being displayed? I overlooked this so many times but I think this chart is actually a chart showing 1 note has been created and the title is just below it:

<img width="1166" alt="screen shot 2019-01-18 at 5 31 21 am" src="https://user-images.githubusercontent.com/41092741/51381677-d29dd180-1ae2-11e9-95d9-d3670289465d.png">
and the section below it is saying no research notes for related tags.

**Comment by kunalvaswani123** [comment]
Yeah .. it shows no research notes .. why ? I added a research note .. shouldn't it show one ?

**Comment by sashadev-sky** [comment]
@kunalvaswani123 It is probably then either an issue with the tag or the note. Try checking /notes/author/admin does it have the note and tag?

**Comment by kunalvaswani123** [comment]
it does show the notes I added there
![screenshot from 2019-01-18 18-40-56](https://user-images.githubusercontent.com/30972133/51388842-a0c35400-1b50-11e9-9a27-d5330e5aa066.png)

**Comment by sashadev-sky** [comment]
@kunalvaswani123 the button rendered for the notes all comes from the same partial so I think you're good to open a PR regarding this
