### ISSUE TITLE
Need ability to revert/select main image for wiki pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#436]
### The problem

Main image selection is updated using the "Save" button when editing wikis -- which adds a new image with the appropriate `nid` or `vid` (not sure which). The old image is not deleted, but there's no way to find a listing, so it's impossible to revert to an older image. 

We should make it possible to switch back to an older image, and potentially to delete main images, since they can be spammy. This could be a dropdown of all images (if there are more than one) associated with this post.

### Relevant URLs

A page that's had multiple main images is here: https://publiclab.org/wiki/spectral-workbench-usage but you can also reproduce this on your local copy by just uploading a main image on a wiki page, then uploading a new one over it.

The code fetching the current main image is here: 

https://github.com/publiclab/plots2/blob/master/app/models/drupal_node.rb#L189-L205

Perhaps we could change it to use an `updated_at` timestamp for `node.images` sorting, instead of `created_at`, then make a menu to choose an image and simply change the `updated_at` of that image to the current timestamp. Then it would become the current image, without losing its creation date.

The code for updating which is the main image is here, in `def update` in wiki controller:

https://github.com/publiclab/plots2/blob/master/app/controllers/wiki_controller.rb#L135-L153

**Comment by franktank** [comment]
Going into the Rails console, I found that images are associated with the nid of the post. I think a basic implementation would be in the /notes/edit to have a list of the previous images with a checkbox for user to choose. The list would be under "Main image". So each image associated with the nid of the post will be displayed with a checkbox and option for users to choose one if desired, else they can upload a new image.

**Comment by ananyo2012** [comment]
@jywarren Please review the PR i made. I have added a option dropdown for choosing the main image.

**Comment by ananyo2012** [comment]
I have introduced a `:vid `field for images by making a new migration. The `:vid` stores the current `:vid` of the wiki and the `main_image` method sorts the images according to the `:vid`

**Comment by jywarren** [comment]
Ah, great. I left a comment on it -- thanks, and please check it out!

**Comment by jywarren** [comment]
Solved in #452 - thanks!
