### ISSUE TITLE
Add placeholder text for password in login modal

### ISSUE THREAD

**Issue by geekychaser** [publiclab/plots2#4364]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the placdeholder of **password** in login modal

**Code link** https://github.com/publiclab/plots2/blob/master/app/views/user_sessions/_new.html.erb#L20

![image](https://user-images.githubusercontent.com/24489162/50377356-e66c2a00-0641-11e9-9de0-a57a2b158169.png)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by geekychaser** [comment]
@SidharthBansal @jywarren sorry for being inactive for so long due to my semester exams.
can i post a PR for this?

**Comment by SidharthBansal** [comment]
Yeah sure!!!
How about creating two ftos for this?

**Comment by SidharthBansal** [comment]
Hi sorry. But I think it is looking good.
You can create a `first timer only` issue for placeholder text in the signup
![image](https://user-images.githubusercontent.com/20972099/50377247-d6ebe180-063f-11e9-90c1-89a2d555fc9a.png)
For the username.

**Comment by geekychaser** [comment]
@SidharthBansal Okay , i will create the same for signup

**Comment by SidharthBansal** [comment]
So, please create a single first timer only issue. Not two.

**Comment by SidharthBansal** [comment]
I hope your exams went awesome like you are.

**Comment by geekychaser** [comment]
@SidharthBansal exams were great !
now the issue looks fine?

**Comment by SidharthBansal** [comment]
Please add code links also.
Thanks

**Comment by SidharthBansal** [comment]
I have deleted the comments to avoid confusion to the newcomer.
Thanks @geekychaser for creating a fto.

**Comment by gurpreet9001** [comment]
i am making a pull request

**Comment by SidharthBansal** [comment]
great

**Comment by gurpreet9001** [comment]
it say i don't have access rights

**Comment by SidharthBansal** [comment]
Can you explain what you are trying to do?
Have you installed plots2 on your laptop?

**Comment by gurpreet9001** [comment]
i am putting command in git bash to clone after forking the repo

**Comment by SidharthBansal** [comment]
Please clone the forked repository. You may be cloning publiclab/plots2.
Please try your_username/plots2

**Comment by gurpreet9001** [comment]
yes it worked

**Comment by geekychaser** [comment]
@gurpreet9001 Great then submit a PR

**Comment by SidharthBansal** [comment]
#4556 is the PR for this issue
