### ISSUE TITLE
Username should be non editable

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4367]
@jywarren currently the usernames can be edited at /profile/edit. Username is used in many comments and other functionality throughout the website. In case a user changes their username then this can result in a lot of trouble in our tagging system. So, making it readonly field in the profile section.

**Comment by jywarren** [comment]
Oops, great, thanks!!! And is it blocked in the controller too?

**Comment by SidharthBansal** [comment]
Right now just in the view.

**Comment by SidharthBansal** [comment]
We should make it non editable at database level too. @kunalvaswani123 are you willing to send patch for this too?

**Comment by SidharthBansal** [comment]
Thanks @jywarren for input. I hope you are enjoying at the mountains. We are taking care of reviewing tasks in your absence.
Have a great wonderful journey

**Comment by kunalvaswani123** [comment]
> We should make it non editable at database level too. @kunalvaswani123 are you willing to send patch for this too?

I am not sure about keeping database columns readonly but I'll try.

**Comment by SidharthBansal** [comment]
We are there to help. You try your level best. If you need help. Ping us

**Comment by jywarren** [comment]
@SidharthBansal thank you! I believe we can just look at the users_controller.rb file and ensure that we are not accepting the username as modifiable. We could potentially add a functional test to ensure this. 

Aside from directly assigning it, the only place this could happen is in mass assignment of parameters, which I'm not even sure Rails allows anymore. Thanks!

**Comment by kunalvaswani123** [comment]
@jywarren I agree a simple check in user_params that current username is equal to previous .. I'll send a patch for this after my https://github.com/publiclab/plots2/pull/4386 is merged since I have made some changes for update action in that thus to avoid conflicts

**Comment by SidharthBansal** [comment]
This issue is assigned to @kunalvaswani123.

**Comment by SidharthBansal** [comment]
@kunalvaswani123 you can work on atmost 3 issues at a time. Obviously there are lot of conflicts. We will resolve it before the merges. Don't get afraid of the conflicts. We are here to help you with the conflicts.

**Comment by kunalvaswani123** [comment]
Sorry @SidharthBansal I didn't know about it .. I'll start working on this issue..

**Comment by SidharthBansal** [comment]
@kunalvaswani123 how is it going here? Can you please link the PR.

**Comment by kunalvaswani123** [comment]
I was busy with https://github.com/publiclab/plots2/pull/4568 and my college assignments  so didn't start here .. 
I have to do this right?

> @jywarren I agree a simple check in user_params that current username is equal to previous .. I'll send a patch for this after my #4386 is merged since I have made some changes for update action in that thus to avoid conflicts

I could quickly create a PR for this .. Sorry for the delays..

**Comment by kunalvaswani123** [comment]
@SidharthBansal I have linked the PR..
