### ISSUE TITLE
Password Verification on the edit profile page

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4368]
Suppose a user has opened the laptop and was scrolling through articles on PL while was logged in. Suddenly they went away from the laptop. Some hacker came and went to the /profile/username/edit page and changes their profile content. Potentially the password. This will result in the user inaccessibility to their account.
We should incorporate Password Field on the edit profile page. Only if the password matches the current password, the user should be able to edit the profile details.
@jywarren what do you think?

**Comment by SidharthBansal** [comment]
@kunalvaswani123 this is related to the issue upon which you are working since many days. Are you willing to take this issue?
Thanks.

**Comment by kunalvaswani123** [comment]
Yeah I looked at it we should keep a password confirmation of current password to change the details on the edit page. I will like to work on it.

**Comment by SidharthBansal** [comment]
We can have three fields. 
1. Compulsory field Current Password which everyone needs to fill correctly for the update action to work. If current password is empty or wrong then no form submission
2. New password: Can be empty if user doesn't want to change the password. Else should be same as confirm password and should obey password validations written in the db.
3. Password Confirmation: Similar to the new password.

**Comment by kunalvaswani123** [comment]
Should I start working on it ?

**Comment by SidharthBansal** [comment]
Yeah sure!!!
Best of luck

**Comment by oorjitchowdhary** [comment]
> 1. Compulsory field Current Password which everyone needs to fill correctly for the update action to work. If current password is empty or wrong then no form submission

I think we should focus on this first as this is important...

> 2. New password: Can be empty if user doesn't want to change the password. Else should be same as confirm password and should obey password validations written in the db.
> 3. Password Confirmation: Similar to the new password.

For the password confirmation thing, I think it was introduced in #3984 and the same could be implemented here

**Comment by SidharthBansal** [comment]
2 & 3 is already present on the edit profile page. Just we need to change
the labels.

**Comment by SidharthBansal** [comment]
Right now we are not focussing on #3948 type of things.
We will do these things once we complete this.
Thanks Oorjit.

**Comment by jywarren** [comment]
This sounds great. Thanks!!!

**Comment by kunalvaswani123** [comment]
@SidharthBansal could you direct me to the code that handles password verification for login so that I can use it here.

**Comment by kunalvaswani123** [comment]
I am using .valid_password? to validate the password the user enters
