### ISSUE TITLE
Progress bar appears on multiple comment textareas when uploading into "new comment" textarea

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#437]
### What happened just before the problem occurred

I began editing a comment, then, with two comment edit areas open, I dragged an image into the "new comment" textarea at the bottom. A progress bar appeared on both comment edit areas, but it should only appear on the bottom one. 

This is closely related to #414 and #413, but I believe that the `.progress-bar` selector is not specific enough in the main "new comment" uploading code. 

### Relevant URLs

Try it out [on this page](https://publiclab.org/notes/dhaffnersr/03-12-2016/final-data-analysis-for-10w40-motor-oil-using-400nm-uv-led-mar12#comments) (perhaps don't actually publish anything since there's a real discussion going on there) and see this screenshot:
![screenshot 2016-03-21 at 2 35 56 pm](https://cloud.githubusercontent.com/assets/24359/13929883/caf4c3d8-ef72-11e5-8e5c-1b8693334f3d.png)

Relevant code is in these files; search for `.progress-bar`:

https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/dragdrop.js
https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/editor.js

**Comment by ujithaperera** [comment]
Yeah. Lets  fix this. I will take care of this.

**Comment by jywarren** [comment]
Just checking -- I merged a lot of PRs in the past few days but I'm not sure if this was fixed... i just tested on the latest stable and the problem remains. No rush, just keeping up to date on progress. Thanks!
