### ISSUE TITLE
improve 'input fields' and 'button' in questions page

### ISSUE THREAD

**Issue by avsingh999** [publiclab/plots2#4378]
In mobile view The input fields and button(continue, Search) not align.
![pub7](https://user-images.githubusercontent.com/25536022/50389892-f37a3d80-0755-11e9-8410-a9b90daeaedd.png)

**Comment by geekychaser** [comment]
@avsingh999 i guess this is due to extra margin can i solve this?

**Comment by SidharthBansal** [comment]
Yeah go ahead.
