### ISSUE TITLE
Planning/discussing React port + material design UI

### ISSUE THREAD

**Issue by shubhamkakkar** [publiclab/plots2#4385]
Javascript frameworks like react are way more better to develop a website, small chunks of code increases code readability, re-usable components etc make the website fast

There are various UI flows in the website, for say pagination isn't centered etc.

//issue taken

**Comment by gauravano** [comment]
@publiclab/community-reps

**Comment by gauravano** [comment]
No issue @jywarren :sweat_smile:. And, thanks for letting me know.

**Comment by jywarren** [comment]
I wanted to point at this fantastic ongoing project as a model for a React component living within the plots2 project -- we should, once it's complete, use it to plan future React projects!

https://github.com/publiclab/plots2/issues/9365

Thank you!
