### ISSUE TITLE
Add a button for 'Digest' page

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4399]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

📋 Step by Step
* [ ] 🙋 Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

![screenshot 131](https://user-images.githubusercontent.com/39333058/50423976-b3fd3f80-0882-11e9-8650-b211f85a3ded.png)

Add a `Your Digest` button here.

* [ ] 📝 Update the file `app/views/layouts/_header.html.erb` in the `plots2` repository (press the little pen Icon).
https://github.com/publiclab/plots2/blob/fefa4aa7ed91776a7b1b25902e804089de2f9d89/app/views/layouts/_header.html.erb#L110-L112

Add this line after L110

`<li><a href="/subscriptions/digest">Your Digest</a></li>`

* [ ] 💾 Commit your changes

* [ ] 🔀 Start a Pull Request. There are two ways how you can start a pull request:

* If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

* You can also edit files directly in your browser and open a pull request from there.

* [ ] 🏁 Done Ask in comments for a review :)

🤔❓ Questions?
Leave a comment below!

Is someone else already working on this?
We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seem stuck, offer them some help! Otherwise, take a look at some other issues you can help with. 
Thanks!

**Comment by oorjitchowdhary** [comment]
@publiclab/reviewers pls add the labels...

**Comment by oorjitchowdhary** [comment]
@kevinzluo can you pls add the first-timers-only label. Thanks

**Comment by cesswairimu** [comment]
Awesome @supasheva, go for it
