### ISSUE TITLE
Strange behaviour after logging out 

### ISSUE THREAD

**Issue by Souravirus** [publiclab/plots2#4401]
After logging out of the website, and then clicking sign up button. I get logged in automatically.

I discovered this while working on bootstrap upgrade on sign up and login page. 

![error](https://user-images.githubusercontent.com/17192149/50425999-e752c500-08a8-11e9-9c96-53a4357a37e9.gif)

@jywarren Please see this.

**Comment by geekychaser** [comment]
I also encountered same behaviour , on many pages we need to refresh again to be logged in

**Comment by jywarren** [comment]
Hmm, can we trace what's happening using the logs? Perhaps it's not actually logging you out?

**Comment by geekychaser** [comment]
![login](https://user-images.githubusercontent.com/24489162/50618978-4c975d80-0f1c-11e9-9b24-0715aab1a3cb.gif)

here is one more issue that i am facing, after log out if i go back then it again shows me as i am logged in and need to refresh again

**Comment by geekychaser** [comment]
@jywarren it seems that we are actually logged out but this is not reflected on user. so user needs to refresh again.
thank you

**Comment by jywarren** [comment]
so, as you can see in some of the admin controller, you can append `?_= +
Time.now` to the end of the URL to flush the browser cache. Maybe this is
needed in some actions now?

**Comment by Souravirus** [comment]
Yeah @jywarren, @geekychaser is right. We are actually logged out but not shown. @geekychaser you can work on this if you can and send a pull request.
Thank you!!

**Comment by SidharthBansal** [comment]
Yeah Rishabh is right

**Comment by geekychaser** [comment]
@Souravirus i think its alreday there https://github.com/publiclab/plots2/blob/master/app/controllers/user_sessions_controller.rb#L22

or we need to add this somewhere else please correct me if i am wrong.
thank you

**Comment by geekychaser** [comment]
@jywarren please help me locate file and some other change is required ?
thank you

**Comment by jywarren** [comment]
I think this may need a change from the last notes in this issue -- https://github.com/publiclab/plots2/issues/4522#issuecomment-454438378

Would you be interested in reworking the error messages mentioned there? There may be a few inter-related issues... i'm not 100% sure this is it but I think it may be related.

**Comment by jywarren** [comment]
Ah, wait. I think this is not actually related (although we could still use help in #4522). I think this is due to the back button being used. Does it still show you logged in once you refresh? I think this is just the browser showing the cached page, and it's OK. I'm going to close this but please reopen if I misunderstood! Thanks!
