### ISSUE TITLE
'Follow' button redirect to "/subscriptions" from "/tags"

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4402]
### Please describe the problem (or idea)
When you click on the `follow` button of a tag at `/tags`, you're subscribed to that tag but you're also redirected to your `subscriptions` page. I think the redirect is redundant, just the subscription would be good enough.

#### Another issue
When you go back to `/tags` after subscribing to a particular tag, the `follow` button isn't updated to `following`. It updates only when you refresh the page once again.
 
> What happened just before the problem occurred? Or what problem could this idea solve?

![follow_tags_error](https://user-images.githubusercontent.com/39333058/50426084-6ea13800-08ab-11e9-9081-22504a301154.gif)

### Please show us where to look

https://publiclab.org/tags

### What's your PublicLab.org username?

oorjit_chowdhary

### Browser, version, and operating system
Chrome, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by geekychaser** [comment]
@oorjitchowdhary I think after follow is clicked than it should be redirect to same page and doing so will resolve both the problems ?

**Comment by geekychaser** [comment]
I tried rendering on same page after click but the tag is not subscribed then.

**Comment by geekychaser** [comment]
@gauravano some guidance required to proceed as i tried to convert the following button to unfollow after click but if i tried to render it to same page then the tag is not subcribed

**Comment by shubhscoder** [comment]
@gauravano I think we can make it asynchronous. We could update the follow to following or unfollow without reloading and I think that would be very efficient. Any suggesions?

**Comment by shubhscoder** [comment]
Also, upon clicking unfollow, the user is redirected to unsubscribe/tag/tagname where he is supposed to click the folllowing button again to unfollow. But for a new user this can be quite hard and painful. What if we change the follow button to unfollow  button then and there without any redirection when his request for subscription gets completed?

**Comment by oorjitchowdhary** [comment]
Moved to #4565
