### ISSUE TITLE
Signup link broken on login page

### ISSUE THREAD

**Issue by kevinzluo** [publiclab/plots2#4412]
### Please describe the problem (or idea)

Signup link doesn't work on stable.publiclab.org/login

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

![signupnotworking](https://user-images.githubusercontent.com/44309027/50451154-eeed8a80-08f7-11e9-9632-7ec766da102d.gif)

### Please show us where to look

https://stable.publiclab.org/login

### What's your PublicLab.org username?
kevinz_qu
> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by gauravano** [comment]
@kevinzluo would you like to make this FTO or should I? Thanks!

**Comment by kevinzluo** [comment]
@gauravano Please go ahead! I am preoccupied with something else currently.

**Comment by gauravano** [comment]
No issue @kevinzluo. Thanks!

**Comment by kevinzluo** [comment]
Haha @gauravano it was not as hard as I thought it was. We can go back to passing 1 url parameter into the  user_sessions.new.log_in_or_sign_up translation and then just use `javascript:void(0)` or `#` as the url. Would you like me to make an fto?

**Comment by gauravano** [comment]
Sure, go ahead and make FTO. Thanks!

**Comment by SidharthBansal** [comment]
Awesome folks :heart:
