### ISSUE TITLE
Simplify the questions page

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4413]
As per @jywarren's suggestion, we want to change the design to
![image](https://user-images.githubusercontent.com/20972099/50455916-fe5fe880-0976-11e9-86be-137434509c7d.png)
See publiclab.org/questions/
app/views/questions/show.html.erb
Refer https://github.com/publiclab/plots2/pull/4255#issuecomment-446419979
Related to #4159.

**Comment by SidharthBansal** [comment]
Refer https://github.com/publiclab/plots2/pull/4255 for discussion.

**Comment by IshaGupta18** [comment]
Hey, I could help in this one!

**Comment by SidharthBansal** [comment]
Great

**Comment by IshaGupta18** [comment]
Could you please elaborate more on this? I have read the discussion at #4255 but could you tell me exactly what is to be linked with what? Thank you very much and I am so sorry if I bother you too much

**Comment by SidharthBansal** [comment]
You can check the current design at pl. We have different buttons. Now we want to club them together as shown in the design given above.
Flag post to moderator will be linked to opening of Mozilla Thunderbird etc... For email purpose
Spam post will be linked as the current spam button is linked. 
Become a moderator and other button, I need to search them in the codebase and tell you

**Comment by SidharthBansal** [comment]
Also please see that some buttons will be only viewed to the admin or moderator while other buttons will be viewed by non admins and non moderators only. 
So,we will be looking for if-else condition for this.
Thanks

**Comment by SidharthBansal** [comment]
For the other two buttons let's ask @jywarren. I think become a moderator should open up email to moderation@publiclab.org .

**Comment by IshaGupta18** [comment]
Absolutely, so if I have got this right, this is what needs to be done:
1)  On clicking the flag button now, a popover will be displayed, that popover will contain:
Flag post to moderators, Spam post, Spam post and ban user for admins/moderators
Flag post to moderators, become a moderator for non admin/non moderators

2) Flag post to moderators will be linked to Mozilla Thunderbird etc. for email purposes
Spam post will be linked to the link which is accessible to admin/moderator currently

We'll be waiting for @jywarren for the remaining 2 buttons.

Have I got it right?

**Comment by IshaGupta18** [comment]
Yes I agree, it would be wise to wait for @jywarren to get the correct idea about the functionality. I hope he is having an amazing time :D 
When a user, be it moderator or normal, asks a question for the first time, moderator has to mark it approved or spam.
For the next time onwards, the question is posted. On clicking th flag button, the setup for mail account is shown for now. I think once its set up, the original functionality will be displayed.

**Comment by SidharthBansal** [comment]
Yes it is the expected behaviour.
Thanks

**Comment by IshaGupta18** [comment]
Any updates here @SidharthBansal ?

**Comment by IshaGupta18** [comment]
Yes, I thought so too. Thank you so much for your help, I'll see what all I can help on in the meanwhile. I hope our mentors have an amazing vacation!

**Comment by oorjitchowdhary** [comment]
What if we add an if-else for the icons only..
So we could do 'if user' -> fa fa-flag and open email
'if moderator' -> fa fa-spam and the spam function

This working is right now on /comments

**Comment by SidharthBansal** [comment]
Yes we expect the similar behaviour.

**Comment by SidharthBansal** [comment]
Let's hold on this issue until Jeff comes.

**Comment by IshaGupta18** [comment]
yes @oorjitchowdhary we expect it only, thanks a lot!

**Comment by jywarren** [comment]
This is correct! The extra buttons - we can do in a follow-up. The idea is
that we put 2 functions into one button to save space. But the added
advantage later is that now that we don't need to worry about space, we can
have more finer-grained options for banning. For example, we might have
separate means to ban a user, vs. to ban and also ban all their individual
comments. Or just ban the comment but not all other comments by that user.
Moderators can then take some finer grained control over how they work. But
it could be done in follow-up as some more admin_controller routes may be
necessary!

Thanks!

**Comment by IshaGupta18** [comment]
> Absolutely, so if I have got this right, this is what needs to be done:
> 
> 1. On clicking the flag button now, a popover will be displayed, that popover will contain:
>    Flag post to moderators, Spam post, Spam post and ban user for admins/moderators
>    Flag post to moderators, become a moderator for non admin/non moderators
> 2. Flag post to moderators will be linked to Mozilla Thunderbird etc. for email purposes
>    Spam post will be linked to the link which is accessible to admin/moderator currently
> 
> We'll be waiting for @jywarren for the remaining 2 buttons.
> 
> Have I got it right?

 Okay so @jywarren @SidharthBansal should I start with this for now?

**Comment by SidharthBansal** [comment]
Yes, thanks

**Comment by IshaGupta18** [comment]
Should I leave 'Spam post and ban user' for a follow-up like @jywarren said? Also, I am thinking of linking 'become a moderator' to /moderators as said in #4255 . Is this all fine? Thanks a lot!

**Comment by IshaGupta18** [comment]
Hey @SidharthBansal I think I have completed most of this issue, but the part where I am getting stuck is, I am not able to render the partial I have created for the buttons as data-content of a bootstrap popover. I have tried several different ways, even from our codebase, but there seems to be some bug in rendering it, could you help me out here with this? Thanks a lot!

**Comment by IshaGupta18** [comment]
Also, I am not able to find the route for this page https://publiclab.org/wiki/moderation in routes.rb, what should I link "become a moderator" to in the meanwhile?

**Comment by ebarry** [comment]
Possibly, the link "become a moderator" should go to "mailto:moderators@publiclab.org"?

**Comment by IshaGupta18** [comment]
Isn't "flag post to moderators" linked to the same?

**Comment by jywarren** [comment]
ah, /wiki/moderation exists on production so we can leave it like that -
it's a great idea! Then 'flag' is the email. Thanks!

**Comment by IshaGupta18** [comment]
#4511 is the link to my PR. I am waiting for approval, do let me know what else I can do! Thanks a ton!

**Comment by SidharthBansal** [comment]
@IshaGupta18 just checking, have you linked the login modals to all the new buttons created in the pr. I commented here because I don't want to diverge the nice conversation going on between you and Jeff.
Thanks

**Comment by SidharthBansal** [comment]
@IshaGupta18 ?

**Comment by IshaGupta18** [comment]
I am so so sorry, I don't know how I didn't receive this mail and it's been five days.

**Comment by IshaGupta18** [comment]
Yes I have linked the login modal to the flag button when the user is not signed in, I think that was what I was supposed to do. The modal will be shown to the user if he's not logged in and clicks on the flag button and consequently the popover won't be displayed. Once again I am very sorry for missing out on the mail.

**Comment by SidharthBansal** [comment]
Great!
