### ISSUE TITLE
Link Sign Up modal to the Question page

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4415]
![image](https://user-images.githubusercontent.com/20972099/50456254-3bc57580-0979-11e9-82e5-35cd4f956fed.png)
See last line's keyword: ``Sign up`` . Please link it to the sign up modal
Refer http://localhost:3000/questions/qwerty/12-15-2018/uihjn-m#post-answer

**Comment by SidharthBansal** [comment]
@kevinzluo can you check and tell whether we have created the common function for Sign Up as we created for the login.
I think we have not created one till now. Will you be willing to step forward and create one function for it?
Thanks

**Comment by SidharthBansal** [comment]
Don't forget to link it here. Thanks

**Comment by kevinzluo** [comment]
Hi @SidharthBansal . There were some issues with redirecting on the signup modal. I have sent a patch for them in #4438 . We will need to merge that before attempting anything else.

**Comment by SidharthBansal** [comment]
Thanks

**Comment by SidharthBansal** [comment]
>>@kevinzluo can you check and tell whether we have created the common function for Sign Up as we created for the login.
I think we have not created one till now. Will you be willing to step forward and create one function for it?
Thanks

i think you forget to answer this question.

**Comment by kevinzluo** [comment]
We haven't created a function for linking the signup modal. I would love to do it, but we have to fix the redirect for the signup modal first :smile: . I will make it after #4438 is finished.
