### ISSUE TITLE
Login modal not working at /profile

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4422]
### Please describe the problem (or idea)
The login modal is not working when clicked through the header on /profile.
> What happened just before the problem occurred? Or what problem could this idea solve?

![profile login modal](https://user-images.githubusercontent.com/39333058/50476636-db711b00-09ee-11e9-8102-ec8e2541566b.gif)

### Please show us where to look

https://publiclab.org/profile

### What's your PublicLab.org username?

oorjit_chowdhary

### Browser, version, and operating system
Chrome, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by IshaGupta18** [comment]
Hey @oorjitchowdhary I think I migh have a fix for this, can I take it up and create a PR?

**Comment by gauravano** [comment]
It's related to profile page. At profile page, no modal is displaying, so something wrong with CSS, JS may be. thanks!

**Comment by IshaGupta18** [comment]
I was able to display the login modal, it was a CSS thing, however I don't know about the other modals at profile page. So sorry. Thanks

**Comment by IshaGupta18** [comment]
I think the sign up modal is showing up just fine. I think the "link social media" modal will show up when #4281 is merged. If it's the case just for the login modal, let me know if I can help. I am so sorry to bother you. Thanks a lot!

**Comment by gauravano** [comment]
Hey, no need to be sorry :)
#4281 is an issue, are you interested in solving that or should I? Thanks!

**Comment by IshaGupta18** [comment]
Thank you! I think someone has proposed a solution for #4281 already and someone has asked for their PR.

**Comment by SidharthBansal** [comment]
Is this issue now solved?

**Comment by IshaGupta18** [comment]
No this one isn't but I do have a solution in mind for this, do you me to make a PR for it? Will it be okay @gauravano ?

**Comment by SidharthBansal** [comment]
If you have a solution in your mind then please submit a PR.
Thanks

**Comment by IshaGupta18** [comment]
#4434 is my PR for this issue, I am waiting for approval @SidharthBansal @gauravano . I hope everything works out! Thanks a lot everyone!
