### ISSUE TITLE
add logo of Public Lab along with heading

### ISSUE THREAD

**Issue by geekychaser** [publiclab/plots2#4424]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 add logo of Public Lab along with heading

**code link** - https://github.com/publiclab/plots2/blob/master/app/views/layouts/_header.html.erb#L14

![image](https://user-images.githubusercontent.com/24489162/50479168-390b6480-09fb-11e9-9e07-005f989b7c05.png)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by geekychaser** [comment]
@SidharthBansal please add fto label

**Comment by oorjitchowdhary** [comment]
@geekychaser please mention the code links and also the solution...
FTO issues are meant to introduce new people to our codebase

**Comment by gauravano** [comment]
yes, @geekychaser please add relevant code links, issue description and then get it labeled. Thanks!

**Comment by gauravano** [comment]
Let's ask @jywarren @publiclab/community-reps before starting with this issue. Thanks!

**Comment by geekychaser** [comment]
@gauravano yes, i have added the code link also lets wait for the confirmation

**Comment by geekychaser** [comment]
@SidharthBansal can i make seperate ftos for fa icons ?

**Comment by SidharthBansal** [comment]
Yeah sure

**Comment by BodeSpezial** [comment]
I want to try it. @geekychaser

**Comment by BodeSpezial** [comment]
I'll want to try it @geekychaser

**Comment by geekychaser** [comment]
@BodeSpezial Yeah, you can do it but let us wait for confirmation from @publiclab/community-reps

**Comment by steviepubliclab** [comment]
Hi all, 
Just seeing this. Can you clarify where you're hoping to put the logos? (maybe a screenshot with arrows? 

Thanks!
-Stevie

**Comment by gauravano** [comment]
Hey @steviepubliclab, just adjacent to Public Lab heading 

![nav_logo](https://user-images.githubusercontent.com/20878070/51843420-eba34f80-2338-11e9-980c-5013396c39be.png)

Thanks!

**Comment by rohanpalhappy** [comment]
I am taking up this issue

**Comment by gauravano** [comment]
Hi @rohanpalhappy, this issue is currently in the discussion stage and we are waiting for @publiclab/community-reps approval for the design. Thanks!

**Comment by rohanpalhappy** [comment]
I've PRed #4794 https://github.com/publiclab/plots2/pull/4794 Please check it out

**Comment by rohanpalhappy** [comment]
okay @gauravano

**Comment by jywarren** [comment]
Hi @rohan2599 - apologies for not continuing the community design discussion here a bit. I really appreciate your PR! We do need to think through a few things first, however. 

![](https://user-images.githubusercontent.com/39710215/52666085-4640cc00-2f33-11e9-97c5-fc4e8d5101bf.png)

Your code and screenshot look really nice. The big questions are, 

1. how does it read at different screen widths? We have a set of issues with the navbar folding onto 2 lines, see #4163 #4189 #4189

**Comment by jywarren** [comment]
Ack, sorry! I clicked the button when i didn't mean to! Let me continue writing...

**Comment by jywarren** [comment]
#4690 has the most documentation about header wrapping.

In general, my other concern design-wise is just that the logo may not render well at such a small size. This is not a criticism of the idea of putting it in the header, really, more a shortcoming of the logo design itself (which i helped design, so i can be extra critical 😄 ). 

What if we thought about placing the logo in the footer, centered, like this? This would avoid the complication of the folding header issue:

![image](https://user-images.githubusercontent.com/24359/52729092-81201f80-2f86-11e9-8d4a-da0576df49cf.png)

This would have to be implemented in a db feature, however, and wouldn't need a PR. 

Apologies for the slow decisionmaking on this; the header is a difficult to design and maintain section that has broken a lot recently, so we're just taking extra care in making changes. Thanks for your patience and for your help!!!!

**Comment by gauravano** [comment]
Ah, to be honest, the above design is not looking that good. It's disturbing the alignment of paragraphs in footer. Let's keep thinking about other places. Also, if the header issue is solved, we can try the logo there too. Thanks!

**Comment by vladdypwnz** [comment]
Hey @gauravano , where do you stand with is issue ?
Is this still open ? Do you finally want to place the logo on the header ?

**Comment by gauravano** [comment]
Hey @vladdypwnz, @rohanpalhappy opened a PR for this issue, but we are still in discussing whether we want to add logo in navbar or not. You can see - https://github.com/publiclab/plots2/issues/4424#issuecomment-463275239 for reason about this discussion. You can help us with navbar fix, if you're interested. Thanks!

**Comment by ChinwenduSilvia** [comment]
Hello, I'm a first-timer here, who has claimed this issue?

**Comment by jywarren** [comment]
Hi, I'm sorry this is already taken. Please check out #4963 if you'd like to get a first-timer issue made for you if none are left!

**Comment by jywarren** [comment]
I'm really sorry but after some discussion I think we will have to close this issue because we are going to be starting a new navbar design process in the next few weeks and in the meantime are interested in keeping it as simple as possible. Thank you and I'm sorry this didn't work out, we still deeply appreciate your help!
