### ISSUE TITLE
Login modal unresponsive on iOS devices

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4426]
### Please describe the problem (or idea)
The login modal is not working on mobiles (iOS).

In the GIFs attached, I kept on clicking the login buttons wherever we've implemented a modal. It didn't open up.
> What happened just before the problem occurred? Or what problem could this idea solve?

![screenrecording_122720182347 1](https://user-images.githubusercontent.com/39333058/50490434-0ed59900-0a33-11e9-9237-e5aa7f5e5e1a.gif)
![screenrecording_122720182347](https://user-images.githubusercontent.com/39333058/50490435-0f6e2f80-0a33-11e9-8ee1-73a8b699aa06.gif)

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?
oorjit_chowdhary

### Browser, version, and operating system
Chrome for iOS

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by gauravano** [comment]
We have to think about alternative to modal or make our modal responsive. Thanks!

**Comment by HarshKhandeparkar** [comment]
Does the access token modal work? It's animations are written in pure js and only the styling is done using bootstrap. Maybe this way it may work on ios because safari is not as advanced as other browsers. Another thing is that this should be tested on other browsers as well

**Comment by jywarren** [comment]
Hmm, i would imagine a bootstrap modal should work on iOS -  can you test a
plain one in their demos? https://getbootstrap.com/docs/3.3/ If that works
then maybe we need to tweak ours?

**Comment by oorjitchowdhary** [comment]
Yes, bootstrap modals show up
![modal 2](https://user-images.githubusercontent.com/39333058/50656468-56bb6980-0fb9-11e9-89da-1048b052f529.gif)

The access token modal is also working
![modal 1](https://user-images.githubusercontent.com/39333058/50656482-62a72b80-0fb9-11e9-9cdd-d9df84fe4c83.gif)

**Comment by jywarren** [comment]
Ah, ok. So perhaps this is to be looked at in a chrome dev console
carefully to see what has gone wrong? Could the modals be conflicting?

**Comment by oorjitchowdhary** [comment]
**UPDATE: The modal is now working...
After new code has been published to production.. I don't know how.. But it's working pretty well**

**Comment by SidharthBansal** [comment]
Awesome

**Comment by SidharthBansal** [comment]
I am sleeping now. I will be back after some time. I will review pending
work.
