### ISSUE TITLE
login modal should be prompted while clicking on follow icon

### ISSUE THREAD

**Issue by geekychaser** [publiclab/plots2#4437]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
![image](https://user-images.githubusercontent.com/24489162/50521554-3f2d3e00-0aec-11e9-83fc-114adc4a453a.png)

Login should be prompted if user click on follow icon , if he/she is not logged in

### Please show us where to look

https://publiclab.org/wiki/sandbox-sitemap

### What's your PublicLab.org username?

geekychaser

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by geekychaser** [comment]
@jywarren @gauravano can i give it a try?

**Comment by gauravano** [comment]
Sure @geekychaser go ahead!

**Comment by oorjitchowdhary** [comment]
@geekychaser please mention this issue in #4132 in the form of check lists.. Thanks

**Comment by geekychaser** [comment]
@gauravano @oorjitchowdhary i guess there is a bug the follow button is not working?

**Comment by geekychaser** [comment]
@SidharthBansal `requireLogin` is not working with this. don't know why and button is also not working ,
can you guide a bit?

**Comment by SidharthBansal** [comment]
@geekychaser I think @dinaelhanan is working on https://github.com/publiclab/plots2/issues/4152 and by mistake you found out this bug and are trying to solve it.
I am closing this issue as @dinaelhanan is working on it. 
A new suggestion : Please update your master. Your master is much behind the current plots2 master. I can detect it as the follow icon is different from what is in the current plots2 master branch.
Thanks for reporting the bug.

**Comment by geekychaser** [comment]
@SidharthBansal okay , but icon seems to be different because screen shot is of publiclab.org rather than that of local server.
Thank you

**Comment by SidharthBansal** [comment]
The plots2 branch is not updated since a month. So all developers are
requested to use the development mode until @jywarren gets some time to
push changes to the production server.
Thanks for your patience. I know him very well. As soon as he will get even
5 minutes he will push it.
Thanks everyone.
