### ISSUE TITLE
Add fa-icon for store in nav

### ISSUE THREAD

**Issue by geekychaser** [publiclab/plots2#4440]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Add**  fa fa-icon for store

**code link** - https://github.com/publiclab/plots2/blob/master/app/views/layouts/_header.html.erb#L70

now add this line of code `<i class="fa fa-shopping-cart" style="color: white" aria-hidden="true"></i>` 
inside `<a>` tag

![image](https://user-images.githubusercontent.com/24489162/50535836-09cc3300-0b74-11e9-81e3-823ac026937d.png)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by geekychaser** [comment]
@SidharthBansal please add `first-timer` labels

**Comment by twisted-sres** [comment]
Hey, I would like to work on this issue as my first issue

**Comment by geekychaser** [comment]
Go ahead if you are first timer

**Comment by geekychaser** [comment]
@twisted-sres i guess you have closed your pull request.
 Reopen that and wait for review. thank you!

**Comment by tvibhu12** [comment]
hey @plotsbot  please review my pull request
#4530

**Comment by geekychaser** [comment]
@arungoel123456 I guess there is already a PR for this, but you may check out some other `first timer issue`

**Comment by megha070** [comment]
@geekychaser @gauravano I would like to work on this issue as an outreachy applicant.

**Comment by Manvi07** [comment]
@geekychaser I am an outreachy applicant. I am new to open source and would like to work on this issue. Kindly assign it to me if it's not resolved yet.

**Comment by gauravano** [comment]
Hi @megha070 and @Manvi07, we have removed the icons from the navbar due to resolve UI disruptions - https://github.com/publiclab/plots2/pull/4713 so I think it's better to close this issue for now. Thanks!
