### ISSUE TITLE
Add fa-icon for 'Donate' in nav

### ISSUE THREAD

**Issue by geekychaser** [publiclab/plots2#4441]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Add**  fa fa-icon for donation

**code link** - https://github.com/publiclab/plots2/blob/master/app/views/layouts/_header.html.erb#L73

![image](https://user-images.githubusercontent.com/24489162/50536134-46e5f480-0b77-11e9-9211-51531d4179ff.png)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by geekychaser** [comment]
@jywarren @gauravano please add `first-timers-only` tag

**Comment by mittalprince** [comment]
@geekychaser may I try ?

**Comment by geekychaser** [comment]
@mittalprince yeah sure , go ahead

**Comment by mittalprince** [comment]
@geekychaser sir, if i made some changes in my code then to see results i need to restart the server not ?

**Comment by geekychaser** [comment]
@mittalprince after `passenger start` it will automatically be updated you just need to refresh your page.
thank you

**Comment by mittalprince** [comment]
@geekychaser sir please review my pr.
thanks

**Comment by mittalprince** [comment]
#4461 add icon for donate #4461

**Comment by geekychaser** [comment]
@gauravano okay lets wait for the response but i guess it will not create any issue in header.
Thank you!

**Comment by gauravano** [comment]
Closing all navbar icon related issues and we'll add icons in a single PR whenever ready. Thanks!

cc/ @jywarren
