### ISSUE TITLE
follow icon is not working in wiki section

### ISSUE THREAD

**Issue by geekychaser** [publiclab/plots2#4443]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
![image](https://user-images.githubusercontent.com/24489162/50539659-e1f7c200-0ba9-11e9-8369-2f79eb65ee57.png)

Follow icon is not working/responding 

### Please show us where to look

https://publiclab.org/wiki/comment-templates

### What's your PublicLab.org username?

geekychaser

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by geekychaser** [comment]
@jywarren @gauravano follow button is not working but it looks all fine in code ?

**Comment by oorjitchowdhary** [comment]
Hi @geekychaser, there's an error in the code.. 
Looks like in the latest commit, someone has misplaced the `<li>` and `<a>` tags.
https://github.com/publiclab/plots2/blob/699108b54624cf0554c6bb87d4f05724f79901ad/app/views/like/_like.html.erb#L13-L15

**Comment by geekychaser** [comment]
@oorjitchowdhary no there is no issue with `<li>` tag
