### ISSUE TITLE
Removal of Authors name in comment section from profile page

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4446]
![image](https://user-images.githubusercontent.com/20972099/50541011-f3999380-0bc2-11e9-8bc4-596291ee8959.png)
On the profile page of user U under the comment navbar, all the comments of user U will be listed. So it is redundant to display U.

**Comment by geekychaser** [comment]
@SidharthBansal can i give it a try?

**Comment by SidharthBansal** [comment]
Yeah sure!!!

**Comment by gauravano** [comment]
Let's replace the username column with Note/Question link so that under Comment col only comment body will appear and not "commented on ....". What do you think @SidharthBansal @jywarren?

**Comment by gauravano** [comment]
You got it right!

**Comment by geekychaser** [comment]
@gauravano should i create another task for it or try to make changes in my previous PR ?

**Comment by gauravano** [comment]
Same PR preferred.

**Comment by geekychaser** [comment]
@gauravano does it look fine, suggest if some changes are required

![image](https://user-images.githubusercontent.com/24489162/50589095-41f0b000-0eab-11e9-8001-8cf90b6faea6.png)
