### ISSUE TITLE
A 'pending for approval' comment shows up on the website

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4447]
### Please describe the problem (or idea)
A comment which is pending for approval shouldn't be shown right?
The comment still comes up with the `moderated view` but is visible on the website.
It can be viewed on /research as well as /dashboard.

> What happened just before the problem occurred? Or what problem could this idea solve?

![image1](https://user-images.githubusercontent.com/39333058/50541071-ea5cf680-0bc3-11e9-8577-6b8a90b5d2b5.png)

![image2](https://user-images.githubusercontent.com/39333058/50541072-eb8e2380-0bc3-11e9-908e-3820a092d173.png)

### Please show us where to look

https://publiclab.org/research
https://publiclab.org/dashboard

### What's your PublicLab.org username?
oorjit_chowdhary

### Browser, version, and operating system
Chrome, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by gauravano** [comment]
Hi @oorjitchowdhary thanks for reporting. The comment under moderation should only be visible to moderators and admin, so yeah something is wrong. I will fix it right away. Thanks!

**Comment by gauravano** [comment]
**Current status:**
Commenter - comment visible at note and on dashboard with message
No user session - comment visible at note and on dashboard with message
Moderator - comment visible at note and on dashboard with moderation options
Normal user - comment visible at note and on dashboard with message
