### ISSUE TITLE
Improve the Comments tab on /profile in mobile view

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4448]
### Please describe the problem (or idea)
The comments tab on /profile in mobile view looks really bad.
It gets distorted, doesn't fit the screen properly and also the table is broken.
The `moderation buttons` are in the `last activity` column and the `comments` are in the `username` column.
> What happened just before the problem occurred? Or what problem could this idea solve?

![video](https://user-images.githubusercontent.com/39333058/50541112-825ae000-0bc4-11e9-9af8-1a61ec2a4ba5.gif)

### Please show us where to look

https://publiclab.org/profile

### What's your PublicLab.org username?
oorjit_chowdhary

### Browser, version, and operating system
Chrome for iOS

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by mittalprince** [comment]
@oorjitchowdhary  may i try to solve this?
thanks

**Comment by oorjitchowdhary** [comment]
Let @publiclab/reviewers take a look at this first 
Then @mittalprince you can solve this one
Thanks

**Comment by gauravano** [comment]
Hi @oorjitchowdhary @mittalprince, currently there are some optimizations in-progress at #4458. so let's continue the discussion on this issue after that.  Thanks!
