### ISSUE TITLE
Login return_to not working when username not found

### ISSUE THREAD

**Issue by kevinzluo** [publiclab/plots2#4454]
![loginnotworking](https://user-images.githubusercontent.com/44309027/50542077-d344e700-0b78-11e9-9470-2db317a3fc3e.gif)

The return_to parameter is not working when the username is not found.

**Comment by SidharthBansal** [comment]
Please add `Oauth` milestone.
Thanks

**Comment by kevinzluo** [comment]
#4456 , #4457 , and this issue are all related.

**Comment by SidharthBansal** [comment]
Yeah they are related. But they are different issues. They are being executed on the same files.

**Comment by jywarren** [comment]
Perhaps if username is not found, it could flash an alert like "we couldn't
find that" and land you on the /login page - or even "we couldn't find that
username; check for mis-spellings or <a href="">create a new account</a>" ?

**Comment by codeIriss** [comment]
hey @kevinzluo @jywarren @SidharthBansal @gauravano someone is working on this or i can take this up?

**Comment by jywarren** [comment]
great!

**Comment by SidharthBansal** [comment]
@codeIriss are you able to find cause of this bug?

**Comment by SidharthBansal** [comment]
If a person is on the login page then redirect to login page is correct
else login modal. I hope this makes sense.

**Comment by codeIriss** [comment]
Okay so we should move to login modal then and can u please help where to
look for this?

**Comment by SidharthBansal** [comment]
Views/user_sessions.html.erb

**Comment by SidharthBansal** [comment]
Moving to #4250 as this will enable the login modal to never be redirected to login page. So this error will vanish.
Closing this one.
Thanks everyone
