### ISSUE TITLE
Combine app/views/user_sessions/_new.html.erb and new.html.erb

### ISSUE THREAD

**Issue by kevinzluo** [publiclab/plots2#4456]
These two files are very similar except for the form url. Please keep new.html.erb but have it render _new.html.erb as a partial. 

We can figure out which url to use possibly by passing a local into the partial.

**Comment by kevinzluo** [comment]
Also #4412 will introduce another difference between the two, so need to watch out for that too

**Comment by gauravano** [comment]
@kevinzluo would you like to solve it yourself? Thanks!

**Comment by kevinzluo** [comment]
@gauravano I can work on this. However, could I go ahead and fix #4457 even though it is an fto since that is related to this?

**Comment by SidharthBansal** [comment]
@Dsxv will be willing to work on this issue as your next issue?
You were asking for some help. In case you need more help feel free to ping me, @jywarren or gaurav.
Thanks

**Comment by Dsxv** [comment]
Yes I'd love to work on this ! Thanks for asking :D

**Comment by SidharthBansal** [comment]
You have to make a partial for the common code so that the readability can be increased

**Comment by Dsxv** [comment]
Hi! I wanted to ask after reducing the code , which one of the files should I keep ,file :  new.html.erb or 
partial : _new.html.erb 
thanks!

**Comment by SidharthBansal** [comment]
_new.html.erb i guess.
Please see all the places where we are using this file. If we are removing
it then we need to check that all other places correctly work

**Comment by SidharthBansal** [comment]
Please check following
Edit profile page
Profile page
Login modal
Signup modal
Login page
Signup modal
Each of above should work perfectly then we are good. I also think you are
missing something.

**Comment by Dsxv** [comment]
I'm going to post a gif while working on the localhost , will that do ? 
thanks!

**Comment by SidharthBansal** [comment]
No need to check oauth. I know they will work.
Yeah check on the local host. Some thing will break for sure. We use new at
many places I suppose.

**Comment by SidharthBansal** [comment]
Can you please use grep command for it?
Also, please open up a PR so that I can help you in code.

**Comment by Dsxv** [comment]
I've searched for new in the app directory and still didn't find anything that breaks , I'm uploading the gif for and the creating PR ! Thanks for reviewing ! 

gif for sign up : 
![user_session](https://user-images.githubusercontent.com/36789080/50890792-e67d6f80-1420-11e9-94c9-32f9b4fd26d6.gif) 

gif for login :
![user_session1](https://user-images.githubusercontent.com/36789080/50890826-f5fcb880-1420-11e9-81ce-57f270d76942.gif)

**Comment by gauravano** [comment]
Try routes "/login" and "/signup", I think they use `new.html.erb`. Thanks!

**Comment by SidharthBansal** [comment]
What about the edit profile page, login page, signup page?

**Comment by Dsxv** [comment]
@SidharthBansal  its in the gifs

**Comment by Dsxv** [comment]
The titles were actually mentioning how I created that user session

**Comment by SidharthBansal** [comment]
There needs to be 5 gifs
1. Login modal with back group anything apart from login,signup page and
research page
2. Signup modal with back group anything apart from login,signup page and
research page
3. Login page
4. Signup page
5. Edit profile page.

**Comment by SidharthBansal** [comment]
But you provided 2 gifs. 3 gifs are missing.

**Comment by Dsxv** [comment]
Oh sorry , my bad ! I 'll do it now !

**Comment by Dsxv** [comment]
3. login page : 
![login_user-session](https://user-images.githubusercontent.com/36789080/50892675-162e7680-1425-11e9-8843-ca1ce0364937.gif)

4.sign in page: 
![sign_in_usersession](https://user-images.githubusercontent.com/36789080/50892697-221a3880-1425-11e9-98c3-fad78ba153a6.gif)

5.Edit prof: 
![edit_prof_user-session](https://user-images.githubusercontent.com/36789080/50892715-27778300-1425-11e9-870e-b4ada0c0ab85.gif)
Thanks!

**Comment by SidharthBansal** [comment]
Please link the PR. I will check the code.
Thanks for your work.

**Comment by Dsxv** [comment]
https://github.com/publiclab/plots2/pull/4580 
Thanks for reviewing !
