### ISSUE TITLE
ambiguous behaviour of 'Add one now' on local server

### ISSUE THREAD

**Issue by geekychaser** [publiclab/plots2#4465]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

![add-one](https://user-images.githubusercontent.com/24489162/50549655-a7b02280-0c86-11e9-876f-505fb5d490d4.gif)

> What did you expect to see that you didn't?

### What's your PublicLab.org username?

geekychaser

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by geekychaser** [comment]
@jywarren @kevinzluo can i give it a try?

**Comment by SidharthBansal** [comment]
This is related to #4459 so adding it in OAuth Milestone.
Thanks @geekychaser for reporting the error. I really like the amazing work which you are doing since couple of days.

**Comment by geekychaser** [comment]
@SidharthBansal thank you , this is only possible because of consistent support from all you mentors and other community members
