### ISSUE TITLE
Link login modal to 'Share your work' at '/research'

### ISSUE THREAD

**Issue by geekychaser** [publiclab/plots2#4468]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

![share-your-work](https://user-images.githubusercontent.com/24489162/50550777-498e3a00-0c9c-11e9-85cd-fe216318033d.gif)

> What did you expect to see that you didn't?

'Share your work' redirects to login page  

### What's your PublicLab.org username?

geekychaser

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment]
Please capitalise the first letter of the title.
Thanks for reporting a suggestion for enhancement. We will love to have it implemented.
