### ISSUE TITLE
requireLogin doesn't work on some url's

### ISSUE THREAD

**Issue by kevinzluo** [publiclab/plots2#4471]
Some urls, such as the one detailed in #4231 do not work with requireLogin. They require the user to click the link again (see #4430, I have copied the gif below ). 
![help answer future questions login](https://user-images.githubusercontent.com/39333058/50492532-2fefb700-0a3e-11e9-9848-a90e52c784b8.gif)

**Comment by SidharthBansal** [comment]
Thanks Kevin for reporting the issue.

**Comment by SidharthBansal** [comment]
I think this is not a big problem. We can close this issue. thanks Kevin
