### ISSUE TITLE
 Weekly Community Check-In #3 - "Achievements"

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#4476]
Hi everyone :wave: !

We all at Public Lab :balloon: - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. Let's start a Community Check-In from this week onwards, where every community member would share something about their work from the past week and about their current week's goal :dart:. You are also welcome to share fun-fact :smile: , new ideas :bulb: , your learning goals :ballot_box_with_check: .

If you're new here, welcome :balloon: , and please comment a Hello message below, we  love to work with you. If you're looking for new issues, please try some of our first-timers-only issues.

We're SO EXCITED to have your help!

Is there anything, you would like to share with us from past week's work? What is your plan for this week?

If you have not planned yet, just leave a Hello! so that we know that you are in sync with us :arrows_clockwise: and doing well!

As always, if you're waiting for a review, or if you're stuck, please request help here OR leave a comment with @publiclab/mentors @publiclab/reviewers for some input. :raised_hands:

## This week's theme.
This being the last week of this year/first week of 2019, I thought we can share some good moments and achievements we have had on project and the community at large in addition to our weekly updates on what we will be working on. It does not necessarily have to be something that you did but it can also be a feature that was added on the project that made you happy :smile_cat: 

### Happy new year everyone!!!  :zap: :fireworks: :tada: :balloon: :tada:

cc 
@thesparks @faithngetich @DakshGondaliya @mohitRJranjan @milaaraujo @kevinzluo
@stefannibrasil @gauravano @ViditChitkara @tech4GT @mridulnagpal @namangupta01 @sagarpreet-chadha @Souravirus @jywarren @MayankKashyap @siaw23 @ryzokuken @ccpandhare @icarito @steviepubliclab @ebarry @jywarren, @sagarpreet-chadha, @icarito, @JonathanXu1, @uzorjchibuzor, @eli6, @kevinzluo, @ValentinaTironi, @rexagod, @sashadev-sky, @IshaGupta18, @milaaraujo, @dinaelhanan, @cesswairimu, @dependabot[bot], @oorjitchowdhary, @okonek, @wanzulfikri, @mohitRJranjan @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @vishalka98 @publiclab/reviewers @Divy123 @pomyo @bhavayAnand9 @ovipa017-xamk @Mridul97 @avsingh999 @Rishabh570 @subhahu123 @aSquare14 @Radhikadua123  @quinn-codes-synthesis @amychan331 @mardelvalle @narnt  @hydro-m  @love-opensource  @romanrodriguez  @shubhangi-chauhan @Dhiraj240 @geekychaser  @codeIriss @CoderJolly .

Thanks :smile:

**Comment by cesswairimu** [comment]
This week I will be redesigning the `/stats` page and also finishing up on #4317. 

The UI open-hour made me happy, meeting all the amazing people and having a peep at how people use the website.
I love the new design that @edieblu is working on. 
Every pull request that I make that gets merged makes me happy too :smiley: 
Thanks

**Comment by SidharthBansal** [comment]
Hi everyone.
This week I will be working on the remaining issues of OAuth with Oorjit,
Isha, Kunal, Kevin, Dina, Rishabh, and many more.
We have achieved login and signup through modals and their linking
theoughout the website this December.
Cess thanks for the theme of this week.
Thanks everyone.

**Comment by SidharthBansal** [comment]
Please checkout https://publiclab.org/notes/warren/01-02-2019/public-lab-code-community-report-jan-2019#c21606

**Comment by gauravano** [comment]
Hi everyone, 

I would be completing the Comment moderation system this week #3331. Thanks to Valentina for her work during GCI on this project, only some parts are remaining now :smile: . 

Thank you!

**Comment by jywarren** [comment]
I wanted to share that I managed to get a VERY long-running issue to pass all tests last night! It may not be 100% ready but we're testing it on the unstable server now:

https://github.com/publiclab/plots2/pull/2857

This would complete the deprecation of our very old `DrupalUsers` table and unify it completely with the newer `Users` table -- one more step towards a cleaner and more maintainable and readable codebase! 🎉 

Thanks Cess for a great theme!!!

**Comment by ebarry** [comment]
Happy New Year! Today i used my refreshed brain to revisit the Tagging and Topics Milestone: https://github.com/publiclab/plots2/milestone/13

In a comment on an existing issue, and in one new issue, i suggest we begin getting more use out of the great "Search By Tag" interface that is currently only on the Questions page :)

**Comment by jywarren** [comment]
Hi, all, round 2! I've kicked off a brainstorming post for the ideas page for Summer of Code 2019 - it's early but I thought we'd best get some ideas into discussion ahead of time. People have been brainstorming already - let's do it together!

https://publiclab.org/notes/warren/01-02-2019/brainstorming-for-summer-of-code-2019

Not every project would be chosen, nor attract a student to work on it, but this will let us discuss, compare, critique ideas and then develop a smaller final list. 

Thanks everyone!

**Comment by ebarry** [comment]
hi all, I'm wondering if i could hear some thoughts from you (if you are reading this, this means you!) about *when during 2019 will be a good time to run a Software Contributors Survey?* We did this the year before last, and would like to do it again. 

Here is where we first discussed the idea in October 2017: https://publiclab.org/questions/warren/10-25-2017/help-with-a-standard-mini-evaluation-for-assessing-software-outreach-efforts

Here's the survey as sent out on December 14, 2017: https://github.com/publiclab/plots2/issues/1890

**Comment by gauravano** [comment]
Hi @ebarry I would say right now(in a week) because contributors are very active now-a-days. Also, we could get feedback of GCI students. Thanks!

**Comment by jywarren** [comment]
We'd really love to do this survey in part because I believe we have a very
diverse community, and we work hard to welcome people in. But we can't
clearly measure that we are succeeding in either (welcoming or diversity)
without a strong response to a survey (last time was great but only 17 ppl
i think responded, so not very comprehensive). Thanks Liz!

**Comment by jywarren** [comment]
during the survey open period, we could also include it in the Welcomebot's
"congratulations" message when a PR is merged, and in other places for high
visibility. We didn't have these systems last time!

**Comment by gauravano** [comment]
Nice idea @jywarren :100:

**Comment by ebarry** [comment]
Ok, so far i hear @gauravano 's idea to do it next week. Any other ideas for timing? I guess "a good time" would mean "a time when we could get a lot of respondents". We will also have to set the duration of when the survey is available, for instance two weeks. (Could be shorter or longer). 

Once the survey period is completed, we will describe the results as 
`[survey respondents]/[all possible respondents]`

**Comment by jywarren** [comment]
Would we want to update the demographic sections (which remain old
US-centric categories) with the latest from
https://github.com/drnikki/open-demographics ?

I'd also set a longer period esp to get maximum impact from our welcomebot
reminders. We could aim for the period of SoC 2019 organizing? That is
coming up real fast. Or we could do a 2 month period maybe to start sooner
and let it overlap that period? Is that too long?

**Comment by gauravano** [comment]
If we want to get lot of responses, then another suitable time is after GSoC orgs are announced :sweat_smile:

**Comment by ebarry** [comment]
haha but maybe the people arriving after GSoC orgs are announced have not had enough experience with Public Lab to have meaningful feedback? or maybe they will?

**For demographics: race, Currently in our in-person surveys we have:** 

* Multiracial or multiethnic
* Native Hawaiian or other Pacific Islander
* American Indian or Alaska Native
* Asian
* Hispanic or Latino
* Black, African, or African American
* White or Caucasian
* Prefer not to say

**Open-demographics has two questions. Note the categories on the second one** 

Do you identify as a person of color?
() Yes
() No

With which racial background(s) do you identify? (check all that apply)
[] Asian
[] Black
[] Latino
[] Native American
[] Pacific Islander
[] White
[] Self Identify: _________________
[] Prefer not to answer

**Comment by jywarren** [comment]
Also a lot more discussion at https://github.com/drnikki/open-demographics/issues/14

And this addition (the above you link to is pretty old but hasn't been updated with input from https://github.com/drnikki/open-demographics/issues/14, unfortunately):

> Do you identify yourself as a member of a minority group in the area you live?

@emmairwin suggesting:

> Do you identify yourself as a member of a minority racial, ethnicity or tribal group in the area you live?

**Comment by SidharthBansal** [comment]
Nice Idea. I am in favour of 2 month surveys as Jeff told instead of 2 weeks time period.

**Comment by gauravano** [comment]
Hi @CoderJolly you showed interest in opening check-in last week. Just reminding you to open the check-in on Sunday evening or Monday morning. Also, please copy the @jywarren's comment -  https://github.com/publiclab/plots2/issues/4476#issuecomment-450953816 and ebarry's comment - https://github.com/publiclab/plots2/issues/4476#issuecomment-451268846. 

Don't forget to acknowledge this message to avoid any confusion. Thanks!

**Comment by SidharthBansal** [comment]
Dont forget to make a checklist of the people you did community check ins
(Gaurav, me, Cess and you) so that each person can get a chance to do it it.

**Comment by gauravano** [comment]
You can copy this issue's body and make changes like - changing theme, adding name of new contributors, adding above comments which I have pointed and any other additions you feel relevant and important.

You can keep the theme for next week - "Think About Your Audience". (Copying Outreachy's theme :smile: )
In this case, an "audience" means the people who are reading your blog posts. They may not have all the skills or knowledge that you do. You might share some skills, but they may not be familar with your community. They could be free software contributors or they could be newcomers.

**Comment by gauravano** [comment]
@CoderJolly open the check-in and I would update it, if required. Thanks!

**Comment by SidharthBansal** [comment]
Moved to #4548

**Comment by SidharthBansal** [comment]
Thanks @CoderJolly

**Comment by CoderJolly** [comment]
I am going to add these things too in a few minutes @SidharthBansal  @gauravano
Thanks for giving the opportunity

> Hi @CoderJolly you showed interest in opening check-in last week. Just reminding you to open the check-in on Sunday evening or Monday morning. Also, please copy the @jywarren's comment - [#4476 (comment)](https://github.com/publiclab/plots2/issues/4476#issuecomment-450953816) and ebarry's comment - [#4476 (comment)](https://github.com/publiclab/plots2/issues/4476#issuecomment-451268846).
> 
> Don't forget to acknowledge this message to avoid any confusion. Thanks!
