### ISSUE TITLE
Adding indexes to appropriate columns of the database

### ISSUE THREAD

**Issue by shubhscoder** [publiclab/plots2#4478]
Subpart of #4362 

So basically, the aim of this issue is to identify potential columns of the database tables that can be indexed. This is an attempt to somehow speedup the loading of public labs website. I think we can make a list of all possible places where tables can be indexed and open multiple related sub issues of this. 
Thank you!

**Comment by shubhscoder** [comment]
I have identified these tables where we could index some columns : 
1. Images table (uid and nid together)
2. Likes tables (likeable_id and user_id) (Maybe currently we dont query this table much, but in future we may when we implement some kind of analysis)
3. The node access table. (I havent seen this table being used anywhere, So I am trying to understand what is this used for.)

Rest of tables have already been indexed properly. @jywarren @gauravano do you think there is something that can be done here?

**Comment by jywarren** [comment]
That sounds good! Would you open a pull request with a migration to add
these? There are a few examples of index migrations in /db/migrate you can
look at for an example. Thanks!

**Comment by shubhscoder** [comment]
Yes sure I will open a PR. Thank you!
