### ISSUE TITLE
Spam in email digests?

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4480]
### Please describe the problem (or idea)
As per @gauravano in #2104, email digests are not active.
But I'm receiving weekly digests. Moreover, these are STRANGE weekly digests.

The digest uses the template we have made and comes `from: notifications@publiclab.org` but it is full of **ADVERTISEMENTS**.

It shows the ads in the form of research notes and even takes up a link on PL. 
When clicked on the link, it takes us to publiclab.org and then the website returns a flash message saying `the author of this note is banned`.

![spam in email digest](https://user-images.githubusercontent.com/39333058/50561505-6e80bc80-0d31-11e9-9cf1-35107f78a20e.gif)

> What happened just before the problem occurred? Or what problem could this idea solve?

![screenshot 136](https://user-images.githubusercontent.com/39333058/50561500-60cb3700-0d31-11e9-8bb4-a534af9b498c.png)

![screenshot 137](https://user-images.githubusercontent.com/39333058/50561501-60cb3700-0d31-11e9-8a6a-fc1f290f6627.png)

![screenshot 139](https://user-images.githubusercontent.com/39333058/50561502-60cb3700-0d31-11e9-9e3e-1e471143b191.png)

![screenshot 140](https://user-images.githubusercontent.com/39333058/50561503-6163cd80-0d31-11e9-9208-1885ffb07c7c.png)

### Please show us where to look

Weekly digests 

### What's your PublicLab.org username?
oorjit_chowdhary

### Browser, version, and operating system
Chrome, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by oorjitchowdhary** [comment]
@publiclab/reviewers @publiclab/community-reps What's to be done here??

**Comment by gauravano** [comment]
Have you pressed that "Digest button" present in your profile? hmm, email content is really shocking.

**Comment by oorjitchowdhary** [comment]
> Have you pressed that "Digest button" present in your profile?

I don't remember, but I think yes

**Comment by jywarren** [comment]
Oh whoa! does this mean somehow that the digest function (which had been broken) is now working? 

Perhaps some change we made recently has resolve the blocking issue on that. Let's do 2 things - further test to see why Oorjit is receiving them but nobody else (?) 

I just turned on my digest again, daily, so I'll watch for it.

In the meantime, let's track where digest content is collected and exclude nodes with `status != 1`!

**Comment by gauravano** [comment]
I just enabled the digest for myself  again by going in "Settings" and then pressing test digest button and received a mail with nice content in it, although date and formatting requires work.

![digest_mail](https://user-images.githubusercontent.com/20878070/50615009-d2a9a900-0f08-11e9-9f84-7ad677b201d6.png)

Let's see if it's just due to button press or we get the digest daily such that cron is also doing it's job or not.

**Comment by jywarren** [comment]
OK - i enabled it daily now. Let's see. https://publiclab.org/settings

**Comment by jywarren** [comment]
For the status, i just changed it: 806248916b9fe7e6d3640252b9da3b03fcd637bb

@SidharthBansal @gauravano are we pretty ready to publish `stable` to production? I know a LOT has changed and wanted to check with you first. Thanks!

**Comment by jywarren** [comment]
Continuing to track digest issues here: https://github.com/publiclab/plots2/issues/3404

I think we can close this, but we should open some new ones for the formatting/images/bio profile pics of the digest!

**Comment by oorjitchowdhary** [comment]
@jywarren Can I request one thing... Can you please give me the permissions for adding labels, closing issues etc.. 
Thank you!

**Comment by jywarren** [comment]
Absolutely!
