### ISSUE TITLE
Link login modal to 'Write a research note' at '/wiki/comment-templates'

### ISSUE THREAD

**Issue by mittalprince** [publiclab/plots2#4481]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
![login](https://user-images.githubusercontent.com/26388073/50562591-12bb3100-0d3b-11e9-8db6-8aaeca00382a.gif)

> What did you expect to see that you didn't?

'Write a research' redirects to login page

### Please show us where to look

https://publiclab.org/wiki/comment-templates

### What's your PublicLab.org username?
princemittal766
> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by mittalprince** [comment]
@SidharthBansal please check it and correct me if i wrong
Thanks

**Comment by mittalprince** [comment]
the same problem with 'Ask a related Question' too.

**Comment by SidharthBansal** [comment]
We need to link it to the login modal through the requireLogin Class as done in many of other prs.
Please go for it
Thanks for reporting it up.

**Comment by oorjitchowdhary** [comment]
This is solved in #4414 .. We can close this

**Comment by SidharthBansal** [comment]
Is write a research note and ask a question both solved?
If yes then @oorjitchowdhary please close this issue. Thanks all.

**Comment by oorjitchowdhary** [comment]
Yes both are solved.. We can close this

I don't have the permissions to close the issue..

**Comment by mittalprince** [comment]
@oorjitchowdhary I will close it
Thanks
