### ISSUE TITLE
Redirect removal from login/signup modal

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4483]
As per Kevin's suggestion

> I have another suggestion for requireLogin. We can check if there is an href attribute before sending a getJSON request. This will allow this class to be used on elements that don't require redirect.

I am in favour of the suggestion. @gauravano @jywarren are you also in favour of this suggestion so that we can continue to work on it.

@kevinzluo i think we should do it for both signup and login modal.

**Comment by jywarren** [comment]
this sounds good!

**Comment by SidharthBansal** [comment]
@Dsxv will you like to take this issue? @kevinzluo can help you here.

**Comment by Dsxv** [comment]
@SidharthBansal Yes I want to take on this issue ! however I am not certain , can you please provide me with some reference material , Thank you so much for your time !

**Comment by Dsxv** [comment]
Or should I ping @kevinzluo for it ? 
Thanks!

**Comment by SidharthBansal** [comment]
Hi Pawan, we have a requireLogin class. We are trying to modify that so that it will be faster. You can read the issue body to know what we have to do.

**Comment by jywarren** [comment]
I think we are done here, actually? after https://github.com/publiclab/plots2/pull/4739 -- reopen if i'm wrong, though!
