### ISSUE TITLE
'Pagination of comment page is failing'

### ISSUE THREAD

**Issue by codeIriss** [publiclab/plots2#4485]
### Please describe the problem (or idea)
The pagination of comments page is not correct .
![pagination_comment_page](https://user-images.githubusercontent.com/35463484/50571765-a7c03780-0dd8-11e9-9cff-40cc0f8f0249.gif)

### Please show us where to look
https://publiclab.org/profile/comments

### Browser, version, and operating system
Chrome, Ubuntu 18.04

### Thank you!
Your help makes Public Lab better! We deeply appreciate your helping refine and improve this site.
To learn how to write really great issues, which increases the chances they'll be resolved, see:
https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by codeIriss** [comment]
@gauravano  @SidharthBansal  please check i have opened the issue correctly as this is my first time of opening an issue. 
And also i would like to solve it

**Comment by oorjitchowdhary** [comment]
Hi @codelriss, the pagination isn't failing but the next page is getting loaded without styles.. And #4174 is the issue for that..

I think you can close this one.. 
Thanks

**Comment by codeIriss** [comment]
sure .thankyou @oorjitchowdhary  for letting me know about the issue #4174
