### ISSUE TITLE
'About the blog' takes us to 'wiki/blog' which does not exist

### ISSUE THREAD

**Issue by codeIriss** [publiclab/plots2#4486]
### Please describe the problem (or idea)
'wiki/blog' doesn't exist
![ezgif com-optimize](https://user-images.githubusercontent.com/35463484/50571933-c70c9400-0ddb-11e9-9199-ab0ba65bc9d5.gif)
### Please show us where to look
https://publiclab.org/blog
### Browser, version, and operating system
Chrome, Ubuntu 18.04
### Thank you!
Your help makes Public Lab better! We deeply appreciate your helping refine and improve this site.
To learn how to write really great issues, which increases the chances they'll be resolved, see:
https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by gauravano** [comment]
@jywarren @ebarry any wiki which contains such information? Or, we need to create the page or remove the link?

Thanks!

**Comment by gauravano** [comment]
Thanks for trying Jeff. Eventually, we will find it and convert it in the FTO :smile:. Thanks!

**Comment by ephemeralwaves** [comment]
May I work on this? I can't find the wiki on the site but I did find a snapshot of the page in the waybackmachine from 2015 (https://web.archive.org/web/20150611120745/http://publiclab.org/wiki/blog). Another snapshot was taken in 2017 but by that point it was throwing a 404. Should this page be recreated and then linked properly to https://publiclab.org/blog?

**Comment by gauravano** [comment]
Great :mag: work @ephemeralwaves! @jywarren do you agree on page recreation? If we agree on recreation of page at wiki/blog then we don't need to do any linking as "about the blog" link present on the /blog is already pointing to wiki/blog 

![screenshot from 2019-03-08 00-41-22](https://user-images.githubusercontent.com/20878070/53982512-1ef8ab80-413b-11e9-8bfc-86c94ee039b0.png)

Thanks!

**Comment by jywarren** [comment]
Yeah i think that sounds great! Good work here!!!!

**Comment by gauravano** [comment]
@ephemeralwaves please create the wiki at wiki/blog and paste the link here. If you need any help, feel free to ping me. Thanks!

**Comment by ephemeralwaves** [comment]
Ok I created the [wiki/blog](https://publiclab.org/wiki/blog) but don't know what the markdown for adding a button is. I looked at this [reference page](https://publiclab.org/wiki/authoring-help#Buttons+and+other+HTML) but it links to another page for examples which is locked.

**Comment by jywarren** [comment]
Ah! Actually we use raw HTML for that. But maybe we should come up with a
simple shortcode for buttons, in a separate issue! Something like

[button:Post a question:https://publiclab.org/questions/new]

...could work?

**Comment by gauravano** [comment]
Thank you @ephemeralwaves for solving this :100: . I think with the page being created, we can close this issue. 
@jywarren creating separate issue with your idea.

**Comment by gauravano** [comment]
@ephemeralwaves let us know, if you face any difficulty in adding button. Thanks!

**Comment by steviepubliclab** [comment]
Great! Thank you!
-Stevie

**Comment by ephemeralwaves** [comment]
Done!

**Comment by gauravano** [comment]
:100:
