### ISSUE TITLE
Disabling paste in /login form

### ISSUE THREAD

**Issue by kunalvaswani123** [publiclab/plots2#4487]
A user is able to paste password from any normal text-field to the password field in all forms PublicLab uses for user authentication. This should be resolved since user should not be able to paste the password in the password field.
![peek 2019-01-01 16-15](https://user-images.githubusercontent.com/30972133/50572197-7d727800-0de0-11e9-86a9-65cd170f958b.gif)

**Comment by SidharthBansal** [comment]
@kunalvaswani123 please continue to work on other similar pages. We will resolve the travis error soon and merge things all at once.

**Comment by kunalvaswani123** [comment]
yeah I'll create a pr for edit form and ftos for rest

**Comment by geekychaser** [comment]
@kunalvaswani123 @SidharthBansal rather than adding this seperately can we combine this feature with `requireLogin`.. ?

**Comment by tahnok** [comment]
Sorry to jump in here randomly, but as someone who uses a password manager (specifically, LastPass) this feature is very inconvenient. Any chance this issue could be opened up for discussion again and possibly reverted? I believe a fair number of people use password managers

**Comment by gauravano** [comment]
Hi @tahnok, for sure, we can't deny this fact that many people use password managers, so let's ask @publiclab/community-reps @publiclab/plots2-reviewers about their views. Thanks!

**Comment by SidharthBansal** [comment]
@jywarren

**Comment by jywarren** [comment]
Agreed, I think that's a good justification to keep this field paste-able!

**Comment by SidharthBansal** [comment]
Thanks
