### ISSUE TITLE
'wiki' doesn't exist for using etherpad-lite in /talk/donate

### ISSUE THREAD

**Issue by codeIriss** [publiclab/plots2#4494]
### Please describe the problem (or idea)
wiki page doesn't exist for 'learn more' part in  /talk/donate
![wiki_learn_more](https://user-images.githubusercontent.com/35463484/50575652-1b3d6580-0e28-11e9-823b-9e4a8dca08f3.gif)
### Please show us where to look
https://publiclab.org/talk/donate
### Browser, version, and operating system
Chrome, Ubuntu 18.04

### Thank you!
Your help makes Public Lab better! We deeply appreciate your helping refine and improve this site.
To learn how to write really great issues, which increases the chances they'll be resolved, see:
https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Agreed! Maybe some basic tips on what the talk page is, what Etherpad Lite
is, how to use it and noting that others can use it live for collaboration?

**Comment by gauravano** [comment]
@codeIriss you can make a wiki using @jywarren's suggestions and also mention @ebarry @steviepubliclab @jywarren  there for reviewing the wiki. Thanks!

**Comment by codeIriss** [comment]
@gauravano I would love to create a wiki page for it . @jywarren your views please.

**Comment by jywarren** [comment]
That would be great; perhaps give it a try and I can review the text when
you're ready? Imagine yourself as a first-time visitor and explain briefly
what the talk pages are good for!

**Comment by gauravano** [comment]
From first-time visitor I remember that website will not allow you to make a wiki if you have not contributed before so let me know if you need help. Thanks!

**Comment by jywarren** [comment]
Closing this, as I think it works well enough for now, but if you'd like to re-open, please do! Thanks!
