### ISSUE TITLE
Refactor dashboard sidebar code

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4499]
### Please describe the problem (or idea)
Currently, the `share your work` button (which is in the sidebar) code of the /dashboard or /research lies in `app/views/dashboard/_header.html.erb` https://github.com/publiclab/plots2/blob/491c6d3a07eed89bc9cadc1a70540af245ae8c2f/app/views/dashboard/_header.html.erb#L5-L19

And the code for the sidebar on dashboard is `app/views/dashboard/_sidebar.html.erb`.
Let's add the above portion in this file.

Also, after adding the above code, let's move `app/views/dashboard/_sidebar.html.erb` to `app/views/sidebar` as `_dashboard.html.erb`.

Some refactoring that'll help us in keeping our repo organized. Also, the code will be easy to be found.

> What happened just before the problem occurred? Or what problem could this idea solve?

![image](https://user-images.githubusercontent.com/39333058/50588166-dc022980-0ea6-11e9-9102-ff21787811f5.png)

### What's your PublicLab.org username?
oorjit_chowdhary

### Browser, version, and operating system
Chrome, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by geekychaser** [comment]
@jywarren @SidharthBansal can i do it ?

**Comment by oorjitchowdhary** [comment]
Hi, this isn't an extension of any issue. I just found out this in our repo through @geekychaser's PR. So I opened up an issue. Hope that's okay.
Thanks


@oorjitchowdhary<https://github.com/oorjitchowdhary> can you please tell us the proposed issue is extension of which issue?
Thanks

**Comment by SidharthBansal** [comment]
You want to refactor two files because both contains the same button. Am
I missing something?

**Comment by oorjitchowdhary** [comment]
No, the 'share your work' button on dashboard exists on the sidebar when viewed on the website.
But the code for the button is in app/views/dashboard/header.html.erb.

There exists a particular code file for the sidebar of dashboard (app/views/dashboard/_sidebar.html.erb) but in this file, the button code isn't there. So we can add the 'share your work' button code in the sidebar file of dashboard.
Also, the current sidebar file of dashboard exists in app/views/dashboard whereas it should be in app/views/sidebar..

So, we can actually move the whole sidebar dashboard file (app/views/dashboard/sidebar.html.erb)to app/views/sidebar under the name app/views/sidebar/_dashboard.html.erb.

**Comment by gauravano** [comment]
Nice idea @oorjitchowdhary to organize code! You wanna work on this one yourself or make it a `fto-candidate`? Thanks!

**Comment by oorjitchowdhary** [comment]
I can work on this but @geekychaser wanted to work on it.. 
Can I work on it @geekychaser?

**Comment by oorjitchowdhary** [comment]
After refactoring, this is where the `share your work` button is coming up..
Can anyone help me align it to its original position

![image](https://user-images.githubusercontent.com/39333058/50638054-55227f00-0f82-11e9-817f-3c4dda228b60.png)
