### ISSUE TITLE
Menu width issues due to new icons

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4502]
I think we need to hide the icon in full width views, so it shows /either/ text or icon - as we're seeing some wrapping issues at certain page widths. Related to #4199 -- thanks! Any help appreciated!

![screen shot 2019-01-02 at 1 20 26 pm](https://user-images.githubusercontent.com/24359/50605760-4dcf7880-0e91-11e9-964a-54d4d3cb5a69.png)

**Comment by Chrisyee22** [comment]
Hi, could I work on this issue??

**Comment by gauravano** [comment]
Hi @Chrisyee22, please go ahead!

**Comment by Chrisyee22** [comment]
Here's a link to a gif. Does this work?
https://media.giphy.com/media/2dcW4fQOKFn3JMDKcy/source.mp4

**Comment by IshaGupta18** [comment]
@Chrisyee22 we can resolve this together, you can refer to #4690 for some more information. I would love to work with you. Thanks a lot!

**Comment by d5nguyen** [comment]
hello there! I'm unsure if this issue has been resolved yet or not. Please let me know as I'd love to work on this if it has become available :)

**Comment by jywarren** [comment]
I believe it's been resolved as we have minimized the changes to the header, and frozen the design until the Bootstrap 4 upgrade -- we'd love your help on other design upgrades though! #4922 #5090 ! Thank you!
