### ISSUE TITLE
Add comment text to moderator email

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4503]
I am now receiving comment moderation emails - awesome work @ValentinaTironi @gauravano and others!

![image](https://user-images.githubusercontent.com/24359/50616941-ae25e080-0eb8-11e9-91e1-0651e86306fa.png)

I think we need to add the comment text itself into the template so that people can skim the comment before approving it:

https://github.com/publiclab/plots2/blob/322b7561e81fd207fcb75a7c0e48940ecf891dad/app/views/admin_mailer/notify_comment_moderators.html.erb

What do you think? Thanks!

Also, i noted that when i clicked "Approve" the comment didn't seem to appear until I reloaded the page. I think we may (separately) need to add `"?_" + Time.now.to_s` to the end of the route to clear the cache in the browser.

**Comment by Dsxv** [comment]
Hi @jywarren ! Can I take this up ?  `add the comment text itself into the template`

**Comment by gauravano** [comment]
Hi @Dsxv sure go ahead!

**Comment by ValentinaTironi** [comment]
If somebody needs some help here, don't doubt to ask!

**Comment by Dsxv** [comment]
Yes , I wanted to make sure that is there a reason for the mail being plane ( without style ) , or I can add some styles

**Comment by ValentinaTironi** [comment]
mmm I think there isn't any problem with adding styles. What do you think @gauravano @jywarren ?

**Comment by gauravano** [comment]
For now, we shouldn't add style because if we are thinking of designing emails then it should be uniform for all email templates. We can form a project around designing of emails, but for now, let's keep it simple comment body addition. @jywarren any thoughts? 

Thanks!

**Comment by Dsxv** [comment]
Okay I'll keep that in mind !  
For now , I have just added basic style  for comment ( close to nothing :p ) which can be removed easily .

**Comment by gauravano** [comment]
`master` branch

**Comment by Dsxv** [comment]
Okay Done ! Thanks !
