### ISSUE TITLE
Show different alert at wiki creation if work is in moderation

### ISSUE THREAD

**Issue by grvsachdeva** [publiclab/plots2#4504]
Currently, new users are not allowed to create a wiki page and shown this alert - https://github.com/publiclab/plots2/issues/4463#issuecomment-450570884

If the user's work is in moderation we can show them different alert may be saying "You can create the wiki once your research note/question is approved by moderators."

**Comment by Dsxv** [comment]
Hi gauravano ! I wanted to take on this one , but I am not sure how one can know if the user's work is under moderation or not ?

**Comment by Chrisyee22** [comment]
Hello. Could I work on this issue?

**Comment by gauravano** [comment]
Hi @Chrisyee22, go ahead! Thanks!

**Comment by The-lady-developer** [comment]
Hi @gauravano! Can I work on this issue?

**Comment by gauravano** [comment]
Hi @The-lady-developer, let's just confirm once from @Chrisyee22 as they have closed their PR- https://github.com/publiclab/plots2/pull/4636 just a week ago.

Thanks!

**Comment by gauravano** [comment]
Hey @The-lady-developer, you can work on this, if interested. Thanks!

**Comment by PritiShaw** [comment]
@gauravano  can I work on this ??

**Comment by gauravano** [comment]
Go ahead @PritiShaw!

**Comment by Hassanelashram** [comment]
@gauravano Seems like this is still open, i'll make a PR now with the alert changes if that's fine?

**Comment by Hassanelashram** [comment]
@gauravano -> https://github.com/publiclab/plots2/pull/8452

**Comment by mishra2019** [comment]
@gauravano Seems like this is still open, can  i make a Pull Request now with the alert changes if that's fine?
