### ISSUE TITLE
Fix login at /signup

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4507]
### Please describe the problem (or idea)
Login at /signup is broken.

> What happened just before the problem occurred? Or what problem could this idea solve?

![screenshot 143](https://user-images.githubusercontent.com/39333058/50651107-641c2800-0fa8-11e9-8ff5-1142cadf4390.png)

### Please show us where to look

https://publiclab.org/signup

### What's your PublicLab.org username?
oorjit_chowdhary

### Browser, version, and operating system
Chrome, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment]
I think you were assigned to this task. You can complete it whenever you get free. You told me in the previous conversations that you are busy till 9 Jan.
Thanks Oorjit.

**Comment by oorjitchowdhary** [comment]
I've solved it. I got some time. PR coming up

**Comment by SidharthBansal** [comment]
Great!!!
