### ISSUE TITLE
Documentation for requireLogin Class

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4509]
Part of #4132.
Add documentation for the new requireLogin class so that we can add that to the new buttons etc in future as per Jeff's suggestion https://github.com/publiclab/plots2/issues/4132#issuecomment-451003321.

**Comment by SidharthBansal** [comment]
@oorjitchowdhary are you willing to write this piece of documentation. This will be your first part to write the documentation. Documentation helps in using the function in future.

**Comment by SidharthBansal** [comment]
This is really close to the work which you did in last couple of weeks.

**Comment by oorjitchowdhary** [comment]
Hi @SidharthBansal .. Yes I'll do this one.. 
Where should I add the documentation and how long should it be... 2-3 lines or more?

**Comment by SidharthBansal** [comment]
2-3 lines. We need to search where it would be the best. We have to add it
where this function is implemented for sure. In addition to it ay be we can
add to the readme or anything else. I don't think readme will be
appropriate place. Any suggestions?

**Comment by oorjitchowdhary** [comment]
> I don't think readme will be appropriate place. Any suggestions?

Yes, I don't think we should put it in the README.. I think it'll be best to create a new file for `Login` and `Signup` functionalities just like there is `EMAIL.md` in /doc

This doc could focus on the login and signup modals we created.. and the use of login and signup pages even after the modals.. and also the requireLogin class

**Comment by SidharthBansal** [comment]
Let's take input from @jywarren whether we require to create a separate
file for this or not.
One way is to change omniauth to login sequences doc and add the
documentation there.

**Comment by jywarren** [comment]
I like this last suggestion on maybe a LOGIN_SYSTEMS.md file?

**Comment by SidharthBansal** [comment]
OK Oorjit go ahead with Jeff's suggestion.
Thanks Jeff

**Comment by oorjitchowdhary** [comment]
So should I make a new file as `LOGIN_SYSTEMS.md` or change `OMNIAUTH.md` to `LOGIN_SYSTEMS.md`??

**Comment by jywarren** [comment]
Change it, please -- thank you!
