### ISSUE TITLE
No cursor : pointer on the Login / Sign up Nav

### ISSUE THREAD

**Issue by Dsxv** [publiclab/plots2#4518]
![cursor_pointer](https://user-images.githubusercontent.com/36789080/50686810-d7737780-1044-11e9-9afc-44adba36f495.gif)
Just pointing out for a very minor issue that on Login / Sign Up the cursor is not showing up as a pointer . 
PS : can I take on this issue ? :)

**Comment by jywarren** [comment]
Sure! Maybe because they don't have an href attr?

**Comment by Dsxv** [comment]
@jywarren Yes!
