### ISSUE TITLE
OAuth Login fail and Form Login fail for some users

### ISSUE THREAD

**Issue by kevinzluo** [publiclab/plots2#4522]
![loginfail](https://user-images.githubusercontent.com/44309027/50713904-48faf800-103c-11e9-90af-b0e9a61bd84e.gif)

I already had an account created through Github with username kevinz_qu.

Chrome, Windows 10

**Comment by jonathanzhang53** [comment]
i Tried logging in with GitHub / google and it gave me a success message but it still showed login/signup at the top right

**Comment by geekychaser** [comment]
@kevinzluo i am facing same issue and i am also not able to login on my local server.
![image](https://user-images.githubusercontent.com/24489162/50721936-6b991980-10ed-11e9-90e9-acd50f1cad96.png)

thank you

**Comment by SidharthBansal** [comment]
This is caused in DrupalUser PR most probably. We need to check that and fix it urgently.

**Comment by SidharthBansal** [comment]
Google oauth working on Ubuntu + Chrome

**Comment by SidharthBansal** [comment]
Github OAuth working on Ubuntu + Chrome on pl.org

**Comment by SidharthBansal** [comment]
Is it working on the pl.org?

**Comment by geekychaser** [comment]
no it is not working this side

**Comment by geekychaser** [comment]
so the issue has arised with this commit id `258bf087753c78b239c796c9fd5b02d007e4264c` if you try to point head before this commit everything would work smoothly.
please correct me if i am wrong
thank you

**Comment by gauravano** [comment]
@geekychaser the issue faced by you as described here - https://github.com/publiclab/plots2/issues/4522#issuecomment-451636135 is not an unexpected error. The alert shown in screenshot is rendered in case a moderator bans a user(in your case admin is banned). So, do you remember banning the admin or something like that? Thanks!

**Comment by SidharthBansal** [comment]
It is also appearing on my localhost. It is appearing for user, moderator
and admin all.

**Comment by gauravano** [comment]
> It is also appearing on my localhost. It is appearing for user, moderator
and admin all.

You mean user banned alert?

**Comment by SidharthBansal** [comment]
Yeah

**Comment by gauravano** [comment]
I am inspecting.

**Comment by geekychaser** [comment]
> @geekychaser the issue faced by you as described here - [#4522 (comment)](https://github.com/publiclab/plots2/issues/4522#issuecomment-451636135) is not an unexpected error. The alert shown in screenshot is rendered in case a moderator bans a user(in your case admin is banned). So, do you remember banning the admin or something like that? Thanks!

no i haven't banned admin or something like that, i faced this after updating my fork so this must be arrived due to last few commits and ion getting Head pointing few commits behind it again started working. thank you

**Comment by gauravano** [comment]
Ok, run `rake db:migrate` and let me know the status. Thanks!

**Comment by SidharthBansal** [comment]
We tried rake db:reset and it doesn't work.

**Comment by SidharthBansal** [comment]
Gaurav is it also happening on your side?

**Comment by gauravano** [comment]
No, i am not facing any issue. I remember running `rake db:migrate` when the pull from master was large.

**Comment by geekychaser** [comment]
@gauravano facing same after `rake db:migrate`

**Comment by jywarren** [comment]
Is it possible we did not synchronize user status before the DrupalUsers
deprecation? I thought we were already running status from rusers.status
but maybe we weren't?

If so we could still manually copy them all over as we haven't dropped the
table.

**Comment by jywarren** [comment]
Oh, so it seems to me that we are only seeing the banned error on localhost installs, not on pl.org. I'm changing the title to match. I confirmed also i can log in with GitHub OAuth on pl.org without trouble.

Checking `user.rb` we set `status = 1` in the `create` method, so it should be OK. 

Previously status was stored in `DrupalUsers` table but now in `User` - so could the `User` records have been `status != 1` for some reason?

In addition i wonder if a lot of previously banned users have now been unbanned if we didn't copy over the `drupal_user.status`. Hmm.

**Comment by jywarren** [comment]
No, for a long time we've been synchronizing status: 

https://github.com/publiclab/plots2/blob/d55049cf4953998b85a9a78722379f07fd42bef8/app/models/drupal_user.rb#L84-L88

**Comment by jywarren** [comment]
And everything was synchronized here: https://github.com/publiclab/plots2/pull/2157/files

**Comment by oorjitchowdhary** [comment]
> @kevinzluo i am facing same issue and i am also not able to login on my local server.
> ![image](https://user-images.githubusercontent.com/24489162/50721936-6b991980-10ed-11e9-90e9-acd50f1cad96.png)
> 
> thank you

I too am getting this error.. Unable to login

**Comment by jywarren** [comment]
Should we push a migration where on development it resets user status for
seed users? Lots are being affected by this :-(

**Comment by geekychaser** [comment]
@jywarren yes sir it will be great if you will push these changes. We are having trouble at our laptops.
Thanks you

**Comment by jywarren** [comment]
Hi @gauravano i want to reserve this issue for this also-important problem in development:

![image](https://user-images.githubusercontent.com/24359/51148626-f33d0180-182c-11e9-8af5-845c53f0645f.png)

But I don't think it's exactly the same (although it may be related to it) as #4569.

**Comment by gauravano** [comment]
how about trying to logging in as banned user via OAuth, if it shows the "signed in" message without actually being logged in then it means it is same banned user problem and we are showing wrong alert in OAuth case.

**Comment by gauravano** [comment]
Actually, i have an extra gmail accound, trying now.

**Comment by jywarren** [comment]
Hi, @gauravano that sounds promising, but how do you know this? Can you walk us through the code to demonstrate this?

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/blame/master/app/models/user.rb#L401-L417

**Comment by jywarren** [comment]
We need to fix the notice delay too, how is notice passed on this line?  see https://github.com/publiclab/plots2/blob/master/app/controllers/user_sessions_controller.rb#L58

**Comment by jywarren** [comment]
Checklist:

* [x] test status on oauth creation
* [ ] confirm fix on oauth creation status
* [ ] address delayed notice with `flash.now[...]` but see above link to how notice is passed...?
* [ ] figure out if and how already-existing users got banned?
* [ ] figure out how to unban lots of people? most since the `drupal_users` merge who do not have otherwise spammed content like comments or posts.

**Comment by jywarren** [comment]
Aha - the synchronization code did not apply on initial creation, esp via `create_with_omniauth`! https://github.com/publiclab/plots2/pull/2157/files

OK, so perhaps: people had accounts but they'd created them via OAuth, and actually had `status = 0` (banned) from the start. But we only checked their matching `DrupalUsers.status`, which was 1 (not banned). But once we deprecated DrupalUsers code, their original `User.status` started being used, rejecting them. Possible?

**Comment by jywarren** [comment]
i bet login check was wired in https://github.com/publiclab/plots2/blame/master/app/controllers/application_controller.rb#L77
AHA! yes! https://github.com/publiclab/plots2/blame/2e33bcb229e77cf4994487a8d9439ce784dc09f8/app/controllers/application_controller.rb#L77
ok great

**Comment by jywarren** [comment]
so we can filter by the user.password_checkerfield to see who is OAuth-created, because of https://github.com/publiclab/plots2/blob/master/app/models/user.rb#L407

**Comment by jywarren** [comment]
OK, we've run:

```ruby
User.where.not(password_checker: 0).where(status: 0).each do |user|
  if user.notes.count == 0 || user.notes.collect(&:status).include?(1) || user.comments.collect(&:status).include?(1)
    user.status = 1
    user.save
  end
end
```

**Comment by jywarren** [comment]
Please check if you're able to log in now!

**Comment by jywarren** [comment]
Reopening for a few follow-up steps:

* 4151819 should not have passed if it's really testing what we were hoping for, so I'd like to re-examine
* I forgot that the solution above doesn't exempt people with no comments... probably doesn't make a difference but i want to think through it carefully to be sure

Thanks @gauravano ! Pushing to stable too.

**Comment by jywarren** [comment]
Confirmed this works on stable -- though i had to manually redirect myself back to stable.publiclab.org!

**Comment by jywarren** [comment]
OK and reattempting the test failure worked!

**Comment by jywarren** [comment]
Only 6 ppl got through my filter due to the comments mistake; `["rinkithakur19923", "abusaud23", "rbhatia46", "vladlenariston", "serafimrostiw", "rahamath_prizm"]` - one is for sure a real person. All are status = 1 now. Removing the others as I checked their comments and they are spam.

**Comment by jywarren** [comment]
Now we just need to be sure we address:  `address delayed notice with flash.now[...] but see above link to how notice is passed...?`

**Comment by jywarren** [comment]
@gauravano would you mind taking a look at this last piece?

**Comment by gauravano** [comment]
@jywarren I will take a look at the alert part. Thanks!

**Comment by jywarren** [comment]
Maybe we could write tests here to look for appropriate alert messages for different outcomes like banned status:

https://github.com/publiclab/plots2/blob/f1e8e497c4bc01cf0cb9151578fbfa1bce875c37/test/functional/user_sessions_controller_test.rb#L60-L74

**Comment by jywarren** [comment]
Hi @gauravano perhaps we should open a more specific follow up issue for this section and highlight where the alerts are being generated both in the oauth flow and in the basic login where the messages are correct (as a model for how to refactor the oauth versions). What do you think?

**Comment by gauravano** [comment]
Hey @jywarren I opened a issue at #4691. Thanks!

**Comment by jywarren** [comment]
Awesome. Thanks a lot!

On Jan 22, 2019 10:19 AM, "Gaurav Sachdeva" <notifications@github.com>
wrote:

Hey @jywarren <https://github.com/jywarren> I opened a issue at #4691
<https://github.com/publiclab/plots2/issues/4691>. Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/4522#issuecomment-456396103>,
or mute the thread
