### ISSUE TITLE
Fix Aspect Ratio for thumbnail grid Images

### ISSUE THREAD

**Issue by dinaelhanan** [publiclab/plots2#4524]
Builds on #4198. There are a few things that PR missed. (The grid on /micro still has the aspect ratio issue) The grid on /micro is generated with this template:
https://github.com/publiclab/plots2/blob/master/app/views/grids/_thumbnail.html.erb
(Thanks to @jywarren, who located it :D) 

If there are any other places on the site were you find the images look a bit squashed or cut off, please link to that here. Thanks!

**Comment by jywarren** [comment]
For an example of how we manage to make all images have the same aspect ratio, see this page: https://publiclab.org/research

And the code that drives it here: 

https://github.com/publiclab/plots2/blob/03812548111b0831e82052cd559aeea9a380098a/app/views/dashboard/_node_default.html.erb#L6-L10

See how the images are all the same ratio:

![image](https://user-images.githubusercontent.com/24359/50863416-92b14e80-136c-11e9-8739-2ff7d182fc1f.png)



Compare this to the grid at https://publiclab.org/micro, which uses the above thumbnail grids code:

![image](https://user-images.githubusercontent.com/24359/50863360-639add00-136c-11e9-9be2-752d4e99e924.png)

**Comment by jywarren** [comment]
Thanks @dinaelhanan !!!

**Comment by oorjitchowdhary** [comment]
#4350 is related too

**Comment by harsh1599** [comment]
Hey! I would like to work on this!

**Comment by gauravano** [comment]
Hey @harsh1599, please go ahead! Thanks!
