### ISSUE TITLE
Subtle login button 

### ISSUE THREAD

**Issue by Dsxv** [publiclab/plots2#4529]
![login_prob](https://user-images.githubusercontent.com/36789080/50722799-9f2e7080-10fa-11e9-9dcf-0bf82266f0b7.gif)
When  (viewport width < 990 px) , There are two Login buttons of which one on the Dropdown Nav doesn't work .

**Comment by gauravano** [comment]
Hi @Dsxv thanks for reporting it. Would you like to solve it? thanks!

**Comment by Dsxv** [comment]
@gauravano I'd love to ! Thanks for Asking!  :D
