### ISSUE TITLE
Closer mirroring between stats pages and tag pages

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#4540]
Closer mirroring between stats pages and tag pages

--have them looking similar or something
* [x] Add link to stats page #5001 
* [ ] Change `contribution graph making` method to use the new method used in stats page that accepts range

**Comment by cesswairimu** [comment]
@jywarren kindly elaborate on what I need to do on this. Thanks

**Comment by cesswairimu** [comment]
@jywarren please take  look at this :point_up: when you get a minute. Thanks

**Comment by jywarren** [comment]
I think you've done a great deal of it already - perhaps we might think about showing a link on the tag stats pages that says `< see statistics for all content` leading back to the main stats page?

**Comment by jywarren** [comment]
And that should do it!

**Comment by vaarigupta** [comment]
hello @cesswairimu   I am an outreachy applicant and excited  to work on this issue. How can I start contributing ?

**Comment by cesswairimu** [comment]
Hello @vaarigupta I am currently working on this and it has a pull request that I am finishing up on. Thanks

**Comment by vaarigupta** [comment]
> Hello @vaarigupta I am currently working on this and it has a pull request that I am finishing up on. Thanks

Ok that's cool. I will look for some other issue
