### ISSUE TITLE
Subscribers for each tag

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#4541]
### Subscribers for each tag
Right now the page https://publiclab.org/stats/subscriptions shows key-value pairs of tags and the number of subscribers. Have them appear according to the ones that have a lot of subscribers in a list form and links to the tags or something easier to visualize.

_Breaking this issue to sub-issues to allow people to allow ideas from the community Thanks @gauravano for this awesome idea._

#### Tasks
* [x] Add a subscriptions stats page #4602
* [x] Explore a way to display the subscriptions statistics #4603

**Comment by shreyateeza** [comment]
@cesswairimu Is this issue open to working on? If yes, please assign me and help me get started.

**Comment by cesswairimu** [comment]
@shreyateeza checkout #4603 and maybe we can find a mini pr for you to contribute on...​Thanks for the interest

**Comment by vaarigupta** [comment]
Hello @cesswairimu , I am  an outreachy applicant and excited  to work on it. How can I start contributing ?

**Comment by cesswairimu** [comment]
Closing this discussion continues on #4603
