### ISSUE TITLE
Allow disabling moderator email notifications

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4543]
Moderators get a lot of email. We should let them continue to moderate on the site, but disable the emails at https://publiclab.org/settings

In a separate follow-up, we could add a note to to moderators emails linking to that setting. We could offer an alternative method - an RSS feed, or a chat channel to review on, rather than by email.

**Comment by Anjalizi** [comment]
hi @jywarren. can you help me get started on this issue if this is still open?

**Comment by jywarren** [comment]
Thank you!!!!

Let's add a toggle when sending moderator emails, to look for `user.has_tag('block-node-moderation-emails')` -- then we can add a UI to add that tag!

The moderators to notify are identified in these sections here: 

https://github.com/publiclab/plots2/blob/master/app/mailers/admin_mailer.rb#L6-L30

Would you be interested in trying to add some logic to check for the blocking tag, in the appropriate sections of code there?

**Comment by Anjalizi** [comment]
I'll start working on this.

**Comment by jywarren** [comment]
Merging into #6282
