### ISSUE TITLE
Extend comment moderation system to answer's comments

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#4550]
Currently, the comment moderation system worked upon in #3331 works only for comments on research notes and questions, but not on wiki comments and comments on answers. So, extend that feature to them. 

Thanks!

**Comment by gauravano** [comment]
Awesome! @dldisha I would break the issue soon(expect 1-2 days) so that it can be solved in parts. Also, till then, you can attempt some FTO or fto-candidate issues to get yourself familiar with the codebase. 

Thanks!

**Comment by dldisha** [comment]
Okay, not a problem
Thanks :)

**Comment by jywarren** [comment]
Hi, Gaurav! Please note the update to merge answers and comments in Vidit's
project... just to be aware that there may be some upcoming changes
relevant here!

**Comment by gauravano** [comment]
Actually, that's what I am thinking Jeff. I would take the status update regarding Merge answer and comment project from Vidit and then decide accordingly when to start with this one. 

Thanks!

**Comment by gauravano** [comment]
Hi @dldisha @jywarren, we can work on this issue after the completion of the answer to comment conversion ie., #4094 

Thanks!

**Comment by jywarren** [comment]
awesome!

**Comment by jywarren** [comment]
I think we can resolve this now because all answers are now comments themselves, because of #4094 !
