### ISSUE TITLE
Prototype ways to subscribe to new node posts based on proximity

### ISSUE THREAD

**Issue by milaaraujo** [publiclab/plots2#4551]
### Proximity subscriptions

>Basically this would adapt the existing subscription code but expand it so that you could subscribe to a location -- like your profile location (not sure how to select a location otherwise... could start with this but later generalize to anything with .lat and .lon methods?). When content gets posted, tagged within X distance of the subscribed location, you get a notification.
In theory we could poll "nearby content" via the API periodically and issue notifications. That could be easier. But we need some way to record that you are following a place. Hope that makes sense!
-@jywarren

The most basic idea is that:

1. someone -- person 1 -- could "watch" a location by subscribing to it;
we'll call it "location A"
2. if any content is posted near that location, say at "location B",
notifications would be sent to person 1
3. we may need to think of the "distance" or "radius" which would be
covered by the subscription
-------------------------------------------
Tasks:
* [ ] - [#4655] Implement `User.watchingLocation(nwlat, selat, nwlng, selng)` which should return a collection of User records

**Comment by milaaraujo** [comment]
Hey @jywarren! Now that we are almost done with #4183, I opened this new issue to discuss the proximity subscriptions.

In my contract, we have "prototype ways to subscribe to new node posts based on proximity" but it's not very clear for me what you expect me to do. I

'm not aware of how the subscription code works now, so would it be possible for you to first show me where that code is? It would also be very useful if you could explain exactly what needs to be done from the API's point of view ... Or at least help me figure it out. For example, what endpoint needs to be implemented?

**Comment by milaaraujo** [comment]
In general, your idea sounds good. But I do not know much how the subscription system works, so maybe @SidharthBansal can give us a better feedback?

**Comment by milaaraujo** [comment]
The idea is that every time someone posts some content next to a person who is registered in that region s/he gets an email notification about it?

**Comment by SidharthBansal** [comment]
@milaaraujo I am currently working on the Subscription prompts across the website so that people can subscribe to the tags at multiple places.
The changes requested in this issue are completely separate from what we are building in my contract.
But for sure I can help you.
Jeff wants PL to be global website. So different people at different locations will have different background/culture/interests etc. We want to have a function written in the app/controllers/subscription_controller.rb which will take user_tags (lon and lat) and try to find the most popular tags near that area. Say in India `pollution` is popular tag but in Rhode Island `oil` is popular tag. So, I should be shown `pollution` and Jeff should be `oil`.
Once we have the function we can use it further.

Sorry for the late reply. The community has increased so much in the past 2 months after GCI that mails are getting burried deep underhood even though I try my level best to answer to each mail. Apologies for late reply.

**Comment by SidharthBansal** [comment]
@jywarren @milaaraujo  I am having trouble in understanding the functionality. When do we have to ping the users and for what? Do we need to send them emails? I can't understand what kind of emails we need to send. Sorry.
Can you please explain this again?

**Comment by SidharthBansal** [comment]
@milaaraujo for the tests we have functional/subscriptions file. You can review the node_tag and user_tag tables in the fixtures folder for reference.

**Comment by milaaraujo** [comment]
No worries, SidharthBansal! 
>I am having trouble in understanding the functionality. When do we have to ping the users and for what? Do we need to send them emails? I can't understand what kind of emails we need to send. Sorry.

So, I was talking about email notification because @jywarren mentioned 'plots2/app/mailers/subscription_mailer.rb'. But to be honesty I don't know exactly what we are trying to accomplish here! :dizzy_face: 

I understood your explanation! In that case, what I need to do is implement the function `in the app/controllers/subscription_controller.rb which will take user_tags (lon and lat) and try to find the most popular tags near that area`. I'm just not sure if that is what Jeff has in his mind!

Hey @jywarren, could you help us here? :smiley:

**Comment by jywarren** [comment]
The most basic idea is that:

1. someone -- person 1 -- could "watch" a location by subscribing to it;
we'll call it "location A"
2. if any content is posted near that location, say at "location B",
notifications would be sent to person 1
3. we may need to think of the "distance" or "radius" which would be
covered by the subscription

Does this make sense? We would still need to figure out how to implement
it. But this "prototype" task is a brainstorming. Let's think through some
possibilities and discuss the pros and cons. Thanks!

**Comment by milaaraujo** [comment]
Now I (just) understood what you meant by "Proximity subscriptions"... :sweat_smile: But it makes sense!

So, I think it is easy to use a user tag to control the user subscription to its own location. We could use the tags: `subscribed:yes` and `subscribed:no`. But I don't know how to handle the other location's subscriptions...

**Comment by jywarren** [comment]
Can we mentally puzzle through what we'd have to do to use a usertag like
`subscribed:lat:lon`? I think this could work but just to think it through
thoroughly...

**Comment by milaaraujo** [comment]
Creating the tag would be easy, right? Just add a new entry in the usertags table. It is also important to think where we would implement the "subscription system". The plan is to create a map where the user selects the areas that he would like to subscribe to? Where would this option be inserted?

I think we should also think about it is how we use these tags... I think we should also think about how we will use these tags... Every time content is posted we will have to go through the user tags table, use those truncated coordinates to determine if the post is within the area that the user is subscribed to.

**Comment by milaaraujo** [comment]
And if, instead of using only latitude and longitude, subscriptions were made from a pair of coordinate, for example: `nwlat=71.01&selat=4.39&nwlng=-172.79&selng=80.33`. We could use the inverse logic we use here: #4037.

**Comment by jywarren** [comment]
Interesting -- the pair of coordinates makes the tagname long, but perhaps
not too much more than if we had `subscribe:lat:lon:radius`, and easier to
work in a database with.

What if we prompted people to watch an area in a small [+] button on each
map, defaulting to the current view?

**Comment by milaaraujo** [comment]
Sounds like a good idea to me! :) I just do not know how difficult it would be to implement this though.
