### ISSUE TITLE
nearby Content endpoint (Search API)

### ISSUE THREAD

**Issue by milaaraujo** [publiclab/plots2#4552]
Development of API endpoint for in-dashboard map showing nearby work, for use by geo UI team:
- https://publiclab.org/api/srch/nearbyContent?query=18,-66

**Comment by milaaraujo** [comment]
Hey @jywarren and @sagarpreet-chadha, what would be the difference between this endpoint and the endpoint we already have (nearby nodes)?

**Comment by jywarren** [comment]
Hmm, unless I'm mistaken, i think it's the same thing?

**Comment by jywarren** [comment]
I believe `nearbyNodes` was not complete at the time and so we added it in to be sure it got completed. It looks like it's done now; would you be willing to try to install a map on the dashboard to display from it? Or if not, perhaps we can create an issue for this which someone else can take up. Thank you!

**Comment by milaaraujo** [comment]
>I believe `nearbyNodes` was not complete at the time and so we added it in to be sure it got completed. It looks like it's done now

Great! 

For now I will open the issue, if I have time I can work on it later, meanwhile we can find someone interested in doing it! :)

**Comment by milaaraujo** [comment]
Done! #4557

**Comment by jywarren** [comment]
👍🏽
