### ISSUE TITLE
Nearby nodes and people

### ISSUE THREAD

**Issue by milaaraujo** [publiclab/plots2#4558]
Nearby nodes: `/api/srch/taglocations` (`tagNearbyNodes()` method)
Nearby people: `/api/srch/nearbyPeople` (`tagNearbyPeople()` method)

>- "Brainstorm necessary & useful default and settable sorting for content and people with an “order” parameter"
> - "Explore time bounding parameters for display over “past week” or “past month” or given period consider ways to group people by topic focus" @jywarren

Tasks:
* [x] (#4597) Add "order" parameter to `taglocations`: sort the nodes by date of creation, updates and oldest. / Add more options to "order"  parameter to `nearbyPeople`: Most nodes posted and signup date.
* [ ] (#4604) Add "period" parameter to `taglocations`: add 'start' and 'end' parameters and the search would return results only for that specific period. End default should be now. / Add "period" parameter to `nearbyPeople`: add 'start' and 'end' parameters and the search would return only users with some activity in that specific period. It would be useful for #4560.

**Comment by jywarren** [comment]
1. I like these!
2. maybe by most nodes posted? by date of signup?
3. that sounds great. Maybe `end` could default to now?
4. same! Great! and agreed.
5. ok great! must've been an older one

**Comment by milaaraujo** [comment]
Thank you! Now we have a task list for this issue!
