### ISSUE TITLE
Debug “last active” column on /people

### ISSUE THREAD

**Issue by milaaraujo** [publiclab/plots2#4559]
@jywarren, what is wrong with this column?

**Comment by jywarren** [comment]
I believe the ordering was by something odd, causing long inactive people
to be listed recently. Maybe it's a conflict between revision timestamps
and node timestamps?

**Comment by jywarren** [comment]
This is odd - on this page: https://publiclab.org/people?sort=last_activity

I still see them out of order... what could be the reason? 

![image](https://user-images.githubusercontent.com/24359/51350349-f1b24a00-1a75-11e9-8b1f-376b2c3ba59e.png)

Ah!!!! 

https://github.com/publiclab/plots2/blob/1979c21fe184b3fded22ebca79510932ce01666e/app/views/users/list.html.erb#L40

Fixing this, should be easy!
