### ISSUE TITLE
Email auto-responses posting as comments on research notes. 

### ISSUE THREAD

**Issue by bronwen9** [publiclab/plots2#4562]
A recent post, https://publiclab.org/notes/edie_blues/01-07-2019/the-new-questions-page-design-is-ready-to-be-reviewed had a comment (now deleted) that was clearly someone's out-of-office / vacation auto response. 

I'm uncomfortable broadcasting contents of people's email without their active consent-- is there an additional layer of permission we can add so that responses by email require some kind of "are you human" confirmation from the sender before posting?

**Comment by gauravano** [comment]
Hi @bronwen9 thanks for reporting. 

We can filter the auto-replied emails and can neglect them instead of converting them to comment. I hope that would solve the problem? 

Thanks!

**Comment by bronwen9** [comment]
I think that would be great, thanks!

**Comment by shubhscoder** [comment]
@gauravano I would like to help on this. My other issues are under review, so I would like to work on this. Thank you !

**Comment by shubhscoder** [comment]
Sure @gauravano ! Thank you so much !

**Comment by bronwen9** [comment]
Hey, I noticed we're still getting vacation auto-responses on the site. The most recent one was at the link below (though I'm deleting it now). Is this fixable?

https://publiclab.org/notes/edie_blues/01-29-2019/do-you-like-this-design-for-keeping-track-of-events-and-projects

<img width="838" alt="screen shot 2019-01-29 at 7 58 28 am" src="https://user-images.githubusercontent.com/8331717/51910159-60f43c00-239c-11e9-9c0c-809f25122edd.png">

**Comment by shubhscoder** [comment]
Yeah. I am going to work on it soon. Sorry for the delay.

**Comment by jywarren** [comment]
Maybe these might be useful?

https://stackoverflow.com/questions/1027395/detecting-outlook-autoreply-out-of-office-emails

https://stackoverflow.com/questions/9426801/detect-auto-reply-emails-programmatically

https://github.com/geerlingguy/Imap/issues/6

https://github.com/jpmckinney/multi_mail/wiki/Detecting-autoresponders

**Comment by jywarren** [comment]
Moving to #5842 !
