### ISSUE TITLE
Follow tags without redirecting and reloading

### ISSUE THREAD

**Issue by shubhscoder** [publiclab/plots2#4565]
Currently following or unfollowing tags (https://publiclab.org/tag) redirects to a different link (https://publiclab.org/subscription) which is I assume not necessary, because a user wishing to follow multiple tags might be annoyed to these redirections. So, we can make follow, unfollow of tags asynchronous without any sort of reloading or redirection. That would I guess enrich the user experience!

Thank you!

**Comment by shubhscoder** [comment]
Should I make a PR for this?

**Comment by gauravano** [comment]
Nice idea @shubhscoder! Do you want to implement this one yourself? Thanks!

**Comment by shubhscoder** [comment]
Yeah @gauravano I would like to work on this!

**Comment by oorjitchowdhary** [comment]
We already had a same issue #4402 
But I'll close that one then

**Comment by jywarren** [comment]
Maybe it could say "Subscribed to tag ____. [Click here] to manage
subscriptions." so that people can get to that page if they want, but by
default it stays on the same page?

**Comment by shubhscoder** [comment]
Yeah, sounds good @jywarren. We could show a flash message with link to manage subscriptions?
