### ISSUE TITLE
Finalizing the 2019 Public Lab Software Contributors Survey

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#4567]
Hi all! 
I'm setting up the survey for our community here, and updating some categories from the Fall 2017 edition. First question: Are these the best set of current projects to list for people to indicate they are contributing to?

* Plots2 / PublicLab.org
* ImageSequencer
* MapKnitter
* Spectral Workbench
* leaflet-blurred-location
* Leaflet.DistortableImage
* infragram-js
* inline-markdown-editor
* PublicLab.Editor
* WebJack
* Community Toolbox
* plotsbot

**Comment by ebarry** [comment]
Are we happy with the below categories? Also, right now it's "check all that apply" -- do we want to ask people to choose one main reason?
<img width="429" alt="screen shot 2019-01-08 at 10 42 28 am" src="https://user-images.githubusercontent.com/161439/50841231-38939780-1332-11e9-8d67-d14df9339cc6.png">

**Comment by ebarry** [comment]
Any updates to the projects, or to the set of possible motivations we are asking people about? Wrapping this up today!

**Comment by gauravano** [comment]
Plots2 is listed by many platforms as a good start point to enter open source world or to first PR in ruby/rails like https://github.com/MunGell/awesome-for-beginners#ruby

So, one of the reason can be "I was exploring beginner-friendly projects and found your project"

**Comment by gauravano** [comment]
I just identified that the above link is connecting to an old URL. I will make a PR for the correction.
And Liz, to the list of projects, you need to add: 
* Leaflet-environment-layers

Thanks!

**Comment by ebarry** [comment]
oh thanks @gauravano , just retroactively fixed it! 0_0
