### ISSUE TITLE
Need to re-order installation steps in README.md 

### ISSUE THREAD

**Issue by ujithaperera** [publiclab/plots2#457]
`rake db:setup` won't work without `schema.rb`.

Under "Prerequisites" in "Installation steps: " there are 9 points to follow for new contributors. In point number 4 has the instructions to run `rake db:setup` and in point number 5 says about the `schema.rb`. Since there is no schema.rb in the remote repository, for the better installation guide

**Comment by jywarren** [comment]
Merged the fix; thanks!
