### ISSUE TITLE
Google+ integration should be removed before April 2019

### ISSUE THREAD

**Issue by esylvan** [publiclab/plots2#4573]
Google Plus is scheduled to go away and its closing has been accelerated due to the discover of a bug that  exposed the data of million users. It is scheduled to go away in April 2019.

**Comment by gauravano** [comment]
Hi @esylvan, thanks for creating the issue. I also read an article some time back, regarding this. As I remember we don't use Google+ integration on plots2, but let's confirm with @jywarren.

Thanks!

**Comment by esylvan** [comment]
Thanks @gauravano. You are right. I put this in the wrong area. My issue is related to user profiles. Do you here should I move this concern to?

**Comment by gauravano** [comment]
No @esylvan, this is a very right place, as plots2 is one of the most active projects of PublicLab. We have to ask Jeff as he handles all the PublicLab projects.

**Comment by jywarren** [comment]
I think @SidharthBansal was looking into the minimal switch from Google+ to Google for the OAuth providers. Just looping him in. Thank you!

**Comment by SidharthBansal** [comment]
I think we can ignore this now and do in April. Most probably the original
settings will work. Just we will change the API. Right now the previous API
is available so we cannot do it. We need to wait for this issue.

**Comment by gauravano** [comment]
hey @SidharthBansal, would you like to check this issue as it's April and we should make sure that deprecation doesn't break anything? Thanks!

**Comment by SidharthBansal** [comment]
I have already checked this. We should close this issue now.
Everything working great

**Comment by gauravano** [comment]
ok, thanks for update @SidharthBansal.  Also, thank you @esylvan for opening the issue.
