### ISSUE TITLE
Consolidation existing "range pages" like with the main stats page

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#4577]
Consolidation/standardization of "range pages" like https://publiclab.org/stats/range/10-05-2015/10-05-2016/ with main stats page at https://publiclab.org/stats?time=September%2026,%202017%2022:43

**Comment by cesswairimu** [comment]
Opening another issue because  the previous one diverted to be ui design will copy @jywarren comments about this below.

**Comment by cesswairimu** [comment]
> Also in terms of consolidating, can we progressively move features from the basic stats pages to their "range" equivalents, then merge them?
 > So as these are merged into the range pages, the periods displayed on the visualizations would match the ranges, i think. How does that sound? Some may need to be reworked to be for a generic period!
> Well, basically all the stats /could/ be presented for an arbitrary range of dates. The 52 week stats, etc etc. could all be fit into a framework of "pick a time period", you know? So if we increasingly move everything into the range pages, we can start to think of /all/ the stats functions as being part of the range pages. We may need to be careful if people select really big ranges! But we could cache, or have some "turn off" if the range is too large (and show a notice like "pick a range shorter than X to see this graph" maybe?") The most fundamental stats like "for all time" could be shown at the top, above the range-specific region. Does that make sense?

**Comment by cesswairimu** [comment]
@jywarren just confirming I got this right. We want to move this to range page.

![range](https://user-images.githubusercontent.com/17081074/53094022-0b89f580-352a-11e9-8ad1-22ade1956ce9.png)
Then have the stats page display just the graphs that matches the period selected in the range page?

**Comment by jywarren** [comment]
Right, essentially we don't want to keep maintaining 2 types of pages, and
should just consolidate everything into one page type. Thanks!!

**Comment by cesswairimu** [comment]
Could it make sense if I made the range page a partial and just render it on the `/stats` page?  Thanks

**Comment by jywarren** [comment]
yes that would be fine! And your date selector work could be used for both?

**Comment by cesswairimu** [comment]
yeah
