### ISSUE TITLE
Language dropdown in footer doesn't change language to "zh-CN"

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#4582]
There are currently 3 languages present in the language dropdown - 
1. :en
2. :de
3. :zh-cn

We are able to change language using this dropdown to only English and Deutsch and not to Chinese because wrong language code is passed for Chinese. 

Here's demo that we are not able to swich to Chinese language - https://drive.google.com/open?id=1VcQJ9-L-1tM9uTvOsODgwhdHPnwH_8lE

As the dropdown is a part of footer feature, so only admins can edit it. So, @jywarren please change the language code of chinese from "zh-cn" to "zh-CN", so that it can be used. 

Thanks!

**Comment by jywarren** [comment]
Ok I think I did it!

**Comment by gauravano** [comment]
Yes, its working now. 
![working_lang](https://user-images.githubusercontent.com/20878070/50953939-e772d780-14da-11e9-9659-ab08d0a67a8b.png)

Closing this. Thanks!
