### ISSUE TITLE
Update link on front page

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#4591]
Dear First Timer, 
On https://publiclab.org/home, the text: "monitoring air, water and land." which links to https://publiclab.org/initiatives should instead link to https://publiclab.org/methods. 
Thank you!

**Comment by gauravano** [comment]
Hi Liz, 

Actually this task is for you. As the part where that link lies is a part of a feature and only admins can edit a feature. So, you have to edit this feature - https://publiclab.org/features/16602 for replacing the link. 

Thanks!

**Comment by ebarry** [comment]
thank you! i'm on it :)

**Comment by gauravano** [comment]
Great :+1:
