### ISSUE TITLE
Move graphs from tag pages (like /tag/soc) to tag stats pages

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#4593]
Dear @cesswairimu and other interested people, 

I've been sitting in on some of the user interviews, and the purple graphs are confusing people mostly because: 
1) the axes are not labelled
2) that they are "above the fold" taking up a lot of room and pushing the actual content that people are looking for farther down. 

While clearly many aspects of stats on publiclab.org are being revisited simultaneously probably including graphing, I'm creating this small issue hoping that we can: 
a) make tag-specific stats pages (could be at /tag/stats/<tagname>)
b) move the graph there 
c) add a "stats" link from one to the other

Thank you!

**Comment by cesswairimu** [comment]
@ebarry quick question just to be sure. Are you talking about the graphs on this page https://publiclab.org/stats ?

**Comment by ebarry** [comment]
Hi @cesswairimu  :)! 
Actually i'm not, thanks for asking! I'm talking about the purple graphs on pages `https://publiclab.org/tag/_____`, for instance https://publiclab.org/tag/oil

**Comment by ebarry** [comment]
Could someone share a link to the tag page code here?

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/tree/master/app/views/tag/show.html.erb
here you go!

**Comment by ebarry** [comment]
Thank you for providing the link to the code! I'm wondering if, for the time being, we can stop rendering the graphs on the tag pages? Here's a screenshot of what i would like to remove from the tag pages: 
<img width="1280" alt="screen shot 2019-01-17 at 10 47 30 am" src="https://user-images.githubusercontent.com/161439/51330422-7b95ef00-1a45-11e9-84ed-83d82cf3e86e.png">

Seems to be perhaps partially related to https://github.com/publiclab/plots2/blob/master/app/views/tag/_graph.html.erb which the wonderful @Souravirus worked on last year. Please forgive me for any offense I unintentionally cause for asking this.

**Comment by jywarren** [comment]
Opened an FTO candidate here: https://github.com/publiclab/plots2/issues/4646

**Comment by jywarren** [comment]
@cesswairimu if you want to finish formatting it, feel free to edit mine!
