### ISSUE TITLE
Deprecation warning: Dangerous query method "COUNT(term_data.tid) DESC"

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4594]
Seeing this in the Travis logs - we should change it! 

`DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "COUNT(term_data.tid) DESC". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from block in related at /app/app/models/tag.rb:328)`

https://github.com/publiclab/plots2/blob/9d1992d4cd9f95900e2e0ed43ba526513b6b9d42/app/models/tag.rb#L328

**Comment by debck** [comment]
@jywarren  Can I work on this issue?

**Comment by jywarren** [comment]
We'd love your help!

**Comment by debck** [comment]
@jywarren  I think this issue is resolved. 
Please look into the thread of this issue #4624 
Also, this line  `.order('COUNT(term_data.tid) DESC') ` has been replaced by `.order(count: :desc) `

**Comment by cesswairimu** [comment]
correct Debasish, closing this
