### ISSUE TITLE
Stats Subscriptions page

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#4602]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

**code link** - https://github.com/publiclab/plots2/blob/master/app/views/stats

now add a file namely `subscriptions.html.erb` in this folder.

Inside the file add this code
```
<div class="col-md-3">
    <h4> About this page </h4>
    <p> People subscribe to tags so that they can be updated when a research is posted with the tag they are subscribed to. This page shows the number of subscriptions and subscription rates on different tags. </p>
    <%= render 'stats_nav' %>
</div>
<div class="col-md-8 col-md-offset-1">
    <h2>Subscriptions</h2>
</div>
```
- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

_Feel free to ping me  if you are stuck_

**Comment by gauravano** [comment]
Hi @cesswairimu thanks for opening this issue. You need to further break this issue to make it a `FTO`, as an FTO is considered introduction to the project and Git, so we provide detailed steps. You can refer this issue for template - https://github.com/publiclab/plots2/issues/4440 

And, let me know. if you need any help in breaking this. Thanks!

**Comment by cesswairimu** [comment]
Thanks @gauravano will do

**Comment by ishan909** [comment]
I would like to claim this issue.

**Comment by cesswairimu** [comment]
Awesome @ishan909 go ahead.

**Comment by ishan909** [comment]
Done, ready for review.
