### ISSUE TITLE
Remove the extra space after `share`

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4611]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file `app/views/editor/rich.html.erb` in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 
https://github.com/publiclab/plots2/blob/87db5642c4f434e9eaaa3478f79d2584916c6d09/app/views/editor/rich.html.erb#L30-L37

Remove the extra space which is below the `share` button text.

![screenshot 152](https://user-images.githubusercontent.com/39333058/51100506-6e39f400-17fc-11e9-96c7-c6c3ead1676d.png)

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
- <div class="ple-module container"> 
-
-  <div class="col-md-3"></div> 
-  <div class="ple-errors col-md-9"></div> 

+  <div class="ple-errors"></div> 
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by JAIDEV123** [comment]
On it!

**Comment by Gonnuru** [comment]
Im claiming this issue. Has anyone else claimed it ? If you have have you created a pull request already ? If your stuck I guess I can help you.

**Comment by gauravano** [comment]
Hi @Gonnuru, a PR by @JAIDEV123 is already in progress at #4612 so please find another issue and seems like @JAIDEV123 is stuck with ruby version problem so you can surely help by coordinating with them in the PR. Thanks!

**Comment by rohanpalhappy** [comment]
I am taking up this issue.

**Comment by gauravano** [comment]
The issue already has PR, so please look for another issues to solve. You can explore FTO issues at https://code.publiclab.org/#r=all and if you can't find one there, feel free to comment here, we'll try to open one for you. Thanks!
