### ISSUE TITLE
RESULTS POSTED: Community-wide survey! This is for YOU 🎉🎈

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#4614]
## Community Survey
I've been putting together a community survey with @jywarren, @gauravano, @SidharthBansal and more on behalf of the Public Lab non-profit, and I'd like to ask everyone to take a few minutes to fill it out.

We put a lot into making our community a welcoming place, but we need to better understand what works and what doesn't.

So please, give us your thoughts in this anonymous form -- we'll post the results at the end and we can all learn about ourselves!

**https://goo.gl/forms/4VVMO8dOijRj6BUA3**

cc
@thesparks @faithngetich @DakshGondaliya @mohitRJranjan @milaaraujo @kevinzluo
@stefannibrasil @gauravano @ViditChitkara @tech4GT @mridulnagpal @namangupta01 @sagarpreet-chadha @Souravirus @jywarren @MayankKashyap @siaw23 @ryzokuken @ccpandhare @icarito @steviepubliclab @ebarry @jywarren, @sagarpreet-chadha, @icarito, @JonathanXu1, @uzorjchibuzor, @eli6, @kevinzluo, @ValentinaTironi, @rexagod, @sashadev-sky, @IshaGupta18, @milaaraujo, @dinaelhanan, @cesswairimu, @dependabot[bot], @oorjitchowdhary, @okonek, @wanzulfikri, @mohitRJranjan @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @vishalka98 @publiclab/reviewers @Divy123 @pomyo @bhavayAnand9 @ovipa017-xamk @Mridul97 @avsingh999 @Rishabh570 @subhahu123 @aSquare14 @Radhikadua123 @quinn-codes-synthesis @amychan331 @mardelvalle @narnt @hydro-m @love-opensource @romanrodriguez @shubhangi-chauhan @Dhiraj240 @geekychaser @codeIriss @CoderJolly

**Comment by jywarren** [comment]
Just pinging @mardelvalle @narnt @hydro-m @love-opensource @romanrodriguez @shubhangi-chauhan @Dhiraj240 @geekychaser @codeIriss @CoderJolly on this survey as GitHub has a limit of mentions!

@HarshKhandeparkar, @Mridul97, @aashna27, @jywarren, @dependabot-bot, @lakshyabatman, @slasher17, @IshaGupta18, @kunalvaswani123, @SidharthBansal, @milaaraujo, @oorjitchowdhary, @gauravano, @geekychaser, @trompj, @sagarpreet-chadha, @shubhscoder 

If someone wants to go to https://rishabh570.github.io/community-toolbox#r=all (which includes a bugfix not on code.publiclab.org) and mention other folks who haven't been mentioned yet, that'd be awesome!

**Comment by jywarren** [comment]
This is so important. Thank you all and please help get the word out to our community to get a good representative portrait -- we will learn so much about whether we have been successful in welcoming people and building an inclusive community.

**Comment by SidharthBansal** [comment]
Filled it. Thanks

**Comment by oorjitchowdhary** [comment]
Filled it up.. Thanks 😃

**Comment by CoderJolly** [comment]
Sure, Filled it ....Thanks 👍

**Comment by kunalvaswani123** [comment]
Filled it .. Thanks :+1:

**Comment by uzorjchibuzor** [comment]
Filled it! 👍

**Comment by codeIriss** [comment]
Filled it! 😊

**Comment by lakshyabatman** [comment]
Thanks! Filled it :)

**Comment by tech4GT** [comment]
Done :)

**Comment by sagarpreet-chadha** [comment]
Filled :+1:

**Comment by IshaGupta18** [comment]
Done :+1:

**Comment by rexagod** [comment]
Done.

**Comment by aSquare14** [comment]
Done!

**Comment by shubhscoder** [comment]
Done !

**Comment by dinaelhanan** [comment]
Done 👍

**Comment by Rishabh570** [comment]
Done.

**Comment by ebarry** [comment]
Thank you all so much and please keep the responses coming!

**Comment by Mridul97** [comment]
Filled! :+1:

**Comment by gauravano** [comment]
Done!

**Comment by bhavayAnand9** [comment]
Done! :)

**Comment by Divy123** [comment]
Done!

**Comment by geekychaser** [comment]
Done! :smile:

**Comment by cesswairimu** [comment]
Just filled it. Thanks

**Comment by rbhatia46** [comment]
Completed! :)

**Comment by rockstar777** [comment]
Filled it. Thanks

**Comment by jywarren** [comment]
@shivani-kapania @aashna27 @StlMaris123 @cheneyshreve @roshniRam @tsparksh @Codeama @Kanikashrivastav @seafr @petersowah @rafael-acerqueira @codeIriss @BrainBuzzer @shelbyfirebaugh @sandyvern @carolineh101 @edieblu @lilliankorinek @pyluftig @toyblox @chanjess @msarit @blancasnz @emctackett @haleymnatz @embh @krys2fa @supasheva @gyi2521 @rachaelkiteme @noordean @kryptc @ruan-brandao @chitra591 @geekiam23 @zenara @sofiaclara93 @saakuffo @PiumiHR @sandy8111112004 @Gayathrir1666 we would love your input on this survey as well! Thank you all!!!

Also - https://code.publiclab.org#r=all is now working again thanks to @Rishabh570's fantastic work... we can mention more people from there as well!

**Comment by sashadev-sky** [comment]
@jywarren Completed :) thank you

**Comment by Souravirus** [comment]
I have completed the survey. Thank you!!

**Comment by trompj** [comment]
Finished it! Thank you.

**Comment by edieblu** [comment]
Done! 👍

**Comment by Dhiraj240** [comment]
Sorry for delay done :+1:

**Comment by shivani-kapania** [comment]
Done! 👍😄

**Comment by Rishabh570** [comment]
Hi all, how about showing the survey on `code.publiclab.org` for some time? Something like this,

![screenshot from 2019-01-16 21-14-39](https://user-images.githubusercontent.com/25483260/51260268-f2929f80-19d3-11e9-8142-bbbcd84bbf5b.png)

**Comment by Rishabh570** [comment]
If it looks fine I can open a PR for it...

**Comment by ebarry** [comment]
Sure! you could add something like, "The form will remain open until early March, but don't wait to respond!"

**Comment by Rishabh570** [comment]
I've merged my [PR](https://github.com/publiclab/community-toolbox/pull/130) regarding this...@jywarren can you put it on gh-pages? Thanks!

**Comment by jywarren** [comment]
![image](https://user-images.githubusercontent.com/24359/51264605-e9c6ad00-1984-11e9-8ab6-361e8f228aea.png)

Done! (addded button style) Thanks, great work!

**Comment by ebarry** [comment]
thank you @Rishabh570 and @jywarren ! Looks great.

**Comment by ebarry** [comment]
Hi everyone, we are halfway through the survey period yay!
Time for my friendly reminder that if you have not responded to this survey, please do take a few minutes -- it's anonymous and the future analysis and sharing of our combined responses will help our community become more self-aware, welcoming, and functional. :)

**Comment by Nirvikalpa108** [comment]
Hi @ebarry thank you so much, I just completed the survey! I am completely new to this community and I absolutely love it's welcoming feel for newcomers. You really have created a gold standard for first time contributors! Can I ask for your advice please? I have a problem in that all of the issues for first timers seem to be taken (if I'm correct?) and I'm not sure which issues tagged "help wanted" are appropriate for complete beginners. I would really appreciate your advice, thank you!

**Comment by namangupta01** [comment]
Hi @Nirvikalpa108, Welcome to PublicLab. There is a first timers issue https://github.com/publiclab/plots2/issues/4820 and I guess no one is actively working on this. You can ask if anybody is still working on the issue or not. In case if no one is working on the issue then you are good to go.
Thanks!!

**Comment by Nirvikalpa108** [comment]
Thank you @namangupta01! I've done this. I'll let you know how I get on! Thank you again!

**Comment by shreyateeza** [comment]
Filled it :+1:

**Comment by ebarry** [comment]
Hi all, we'll be closing this survey this week, so please add your feedback in the next day or so to help us improve together!

**Comment by CleverFool77** [comment]
Filled it <3

**Comment by kryptc** [comment]
Done!

**Comment by madeofhuman** [comment]
✅ Done

**Comment by ebarry** [comment]
Great, thanks all! Encouraging to hear these responses so I'll keep the survey open another day or so. Thank you everyone!

**Comment by ebarry** [comment]
Thanks a bunch everyone -- we got 63 responses! @jywarren and I will put together a report and share it in a couple weeks.

**Comment by gauravano** [comment]
Will be waiting to see the report :see_no_evil:

**Comment by ebarry** [comment]
Final Report is live! Thanks everyone! Please add your comments here to this thread for what we are inspired to do/change as a result of reading: https://publiclab.org/notes/liz/04-15-2019/report-2019-software-contributors-survey

**Comment by HarshKhandeparkar** [comment]
Yaay! I have been waiting for this forever.

**Comment by HarshKhandeparkar** [comment]
@ebarry can we add countrywise demographic survey? Like we can list some of the big countries in radio buttons and if the country of the person is not listed, they can enter it in a separate input? How does that sound?

**Comment by ebarry** [comment]
Yes @HarshKhandeparkar, we could do that. Probably would help standardize the answers!

**Comment by ebarry** [comment]
Dear everyone, 
Upon the well-considered advice of @gauravano , let's host a meeting to discuss the contents of the Report (link above in comments):

The following poll offers dates for the next two weekends (as recommended by @gauravano) as well as for Thursday May 2. Note: there are no weekdays offered in the coming week because the staff have an in-person week-long meeting where we cannot have any other meetings:

https://www.when2meet.com/?7773453-c7gAs

Thanks and looking forward to seeing everyone!

**Comment by ebarry** [comment]
We've got a clear choice: Sunday 10:30-11:30 PM India time, 1-2 PM East Coast US time. 

Topic: Public Lab Software Contributors 2019 Survey Report: Discussion
Time: Apr 21, 2019 10:30 PM India Time / 1:00 PM Eastern Time US and Canada
Place: https://zoom.us/j/346913422
Notes: https://pad.publiclab.org/p/developers

### Ahead of time:

* Please enter the discussion topics you wish to discuss on the pad. Please attempt to organize questions and comments under the appropriate headings which correspond to each section of the report: https://pad.publiclab.org/p/developers  Thanks!

cc @gauravano @cesswairimu @skilfullycurled @CleverFool77 @rexagod @sashadev-sky @jywarren @SidharthBansal @HarshKhandeparkar and everyone on this thread :)
