### ISSUE TITLE
Display comment status on https://publiclab.org/comments if comment is not approved

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4616]
As a moderator, i see lots of spam comments on /comments, but they're not marked as such so I thought I had to moderate them. Let's have them appear moderated (labeled, greyed out?) if they are not currently published!

Follow-up: we could have a `https://publiclab.org/comments?status=1` route available to moderators so you don't have to see them, linked to from the top of the page. Regular users wouldn't need to see this link, but it's useful for mods!

**Comment by gauravano** [comment]
I will work on this. Also, /comments link is currently visible to everyone. Do you like it to be seen only by mods or it's fine @jywarren?

Thanks!

**Comment by jywarren** [comment]
I believe it doesn't show unmoderated comments to non-mods... isn't that
right? I always forget this. :-P

**Comment by gauravano** [comment]
@jywarren I just checked 

```ruby 
    status = 1 # status of comments to display
    status = 0 if current_user && (current_user.role == 'admin' || current_user.role == 'moderator')
```

Currently, it shows all spammed comments to moderators and normal comments to users. So, comments which are in moderation are not shown to anyone. I would add the links on page so that moderators can view categorically. Thanks!
