### ISSUE TITLE
Refactor old `error_messages` usage in form helpers

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4622]
I found some very old code in #4575 which I removed, but realized that we still use the `f.error_messages` code in our form error templates; you can see it in all these search results:

https://github.com/publiclab/plots2/search?q=error_messages&unscoped_q=error_messages

Errors should instead be in format:

```ruby
  <% if @model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
      <% @model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
```

I believe this will resolve https://github.com/publiclab/plots2/issues/4521 as well because the duplicate "email already taken" error will be better handled with a modern Rails error reporting approach, as in the docs here: 

https://guides.rubyonrails.org/active_record_validations.html#displaying-validation-errors-in-views

If it helps, see when the old plugin code was originally added here:

https://github.com/publiclab/plots2/commit/4f13238a4837356d3bbf4cfffd7d14a24e7e42dc

**Comment by jywarren** [comment]
If you'd like to take this up, please use the plugin removal in #4575 as a starting point for your changes! Thank you!!!

**Comment by Chrisyee22** [comment]
I would like to work on this issue if that's alright.

**Comment by jywarren** [comment]
we would love your help, thank you!

**Comment by cesswairimu** [comment]
Doing a breakdown here
--------------------------------------
 Features template - https://github.com/publiclab/plots2/issues/8937

**Comment by Manasa2850** [comment]
@cesswairimu I'm reopening this issue since we have 2 more instances where `error_messages` needs to be removed.
Thanks!
