### ISSUE TITLE
Recaptcha overlapping Sign up buttons

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4634]
![screen shot 2019-01-16 at 5 43 39 pm](https://user-images.githubusercontent.com/24359/51283483-53ab7a80-19b6-11e9-9250-32dbcb9cd938.png)

Just noting this! I may not be able to fix it tonight but if someone wants to give it a try, please do! Thanks!

**Comment by dewanhimanshu** [comment]
I want to give it a try

**Comment by oorjitchowdhary** [comment]
Hi, how can we test this... The recaptcha is available only for production
https://github.com/publiclab/plots2/blob/9f7cfc47ded41ed3a7370c66a9c4f7af9704af59/app/views/users/_create_form.html.erb#L74-L79

**Comment by SidharthBansal** [comment]
Moved to #4643
