### ISSUE TITLE
Message Consistency on the Subscriptions Page

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/plots2#4639]
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

On the [subscriptions](https://publiclab.org/subscriptions) page, we need to pluralize the word 'email' in the description around the 'Email Settings' button. While we're at, we can go ahead and standardize the styling to match that of the description above it. 

<img width="302" alt="screen shot 2019-01-17 at 1 24 38 am" src="https://user-images.githubusercontent.com/41092741/51299623-1c10f280-19f7-11e9-872f-9cf895e502ce.png">

## Solution

Where to find the relevant lines of code: 

in `app/views/home/subscriptions.html.erb`, the code the description and link is all written on one line:
https://github.com/publiclab/plots2/blob/9f7cfc47ded41ed3a7370c66a9c4f7af9704af59/app/views/home/subscriptions.html.erb#L20

1) The link (`a` tag) is currently nested in the paragraph (`p` tag), lets move the paragraph below it instead of around it. 

2) Lets change the text to "Control which emails you want to receive." to make it more succinct. 

3) Add italics to the text with a `style` attribute and the declaration `font-style:italic;`

It should look something like this afterwards: 
`<p style="font-style:italic;">Control which emails you want to receive.</p>`

4) One last change. The 'Email Settings' button needs a margin under it. Add a `style` attribute onto the `a` tag with the declaration `margin-bottom:10px;`

The goal is for it to look just like the one above in the end: 
<img width="296" alt="screen shot 2019-01-17 at 1 41 08 am" src="https://user-images.githubusercontent.com/41092741/51300205-14524d80-19f9-11e9-8dd5-9ca050a2dc62.png">

Thanks!!

## Steps to Fix
 
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/plots2](https://github.com/publiclab/plots2)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by gauravano** [comment]
Hi @sashadev-sky, issue is looking nice :100: .

Some points regarding FTO: There are 2 types of beginner issues - 
1. `first-timers-only`: This issue contains detailed instructions and template like you used in this one.  
2. `fto-candidate`: This type issue require some effort from contributor's side. It contains relevant links and goal but not the exact code to be changed/added.

Thanks!

**Comment by gauravano** [comment]
I added some more labels. I hope it's fine!

**Comment by sashadev-sky** [comment]
@gauravano of course thank you!

**Comment by SashwatAnagolum** [comment]
Hi!
First timer on your codebase, can I start with this issue?

**Comment by gauravano** [comment]
Hi @SashwatAnagolum, welcome to Public Lab and please go ahead with the issue. Thanks!

**Comment by SashwatAnagolum** [comment]
Thanks @gauravano, I submitted a PR: https://github.com/publiclab/plots2/pull/4642#issue-245487726
