### ISSUE TITLE
Images are not uploading when editing a comment in research notes. 

### ISSUE THREAD

**Issue by ujithaperera** [publiclab/plots2#464]
### What happened just before the problem occurred
when I try to edit a comment and upload a image progress bar appear and it struck in 100% mark. And image is not get uploaded. In create comment box it's working. But not in edit. 

### Relevant URLs
https://publiclab.org/notes/Ujitha/03-25-2016/for-testing-comment-edit-image-upload

### PublicLab.org username
Ujitha

### Browser, version, and operating system
chrome OSX

**Comment by ujithaperera** [comment]
This issue is not happening in my local. Same OS and Browser. Need help from other users to clarify the bug. Thanks !

**Comment by jywarren** [comment]
On the live site, this worked for me both when posting a comment and immediately editing it without a page refresh, and also when editing it after a page refresh. With both choosing a file and with drag-dropping it. Maybe you have some kind of caching issue?

**Comment by ujithaperera** [comment]
Yes. Its perfectly working when I use different device. My bad. Sorry for the inconvenience.

**Comment by jywarren** [comment]
No problem and thanks for checking!
