### ISSUE TITLE
Navbar gets distorted at 740px 

### ISSUE THREAD

**Issue by dewanhimanshu** [publiclab/plots2#4641]
![screenshot from 2019-01-17 13-44-45](https://user-images.githubusercontent.com/32437794/51304474-4944bb80-1a5e-11e9-9925-29a248c49237.png)

**Comment by geekychaser** [comment]
@dewanhimanshu i guess this is same as #4502.
thank you

**Comment by gauravano** [comment]
Hi @geekychaser thanks for pointing to the issue. Thanks @dewanhimanshu for reporting, closing this one as it is already reported.
