### ISSUE TITLE
Sign Up button conflicts with "I'm not a robot" checkbox in the Sign-up modal

### ISSUE THREAD

**Issue by dhruvgupta167** [publiclab/plots2#4643]
![screenshot 2019-01-17 at 10 30 33 pm](https://user-images.githubusercontent.com/32172694/51335595-7b7b0b00-1aa8-11e9-9048-2a998a508333.png)
The " I'm not robot " checkbox overlaps with the sign-up button in the Sign up modal in the desktop view.

**Comment by SidharthBansal** [comment]
@IshaGupta18 can you please look at this. You did the last PR for these files after which this error has pop up.

**Comment by SidharthBansal** [comment]
It was working fine before your pr. I think you forget to see the layout of the modal while doing the pr.
Create a pr to fix this too.

**Comment by IshaGupta18** [comment]
Let me have a look at this, this wasn't coming in development probably because we were using spamaway there

**Comment by jywarren** [comment]
Yeah - maybe we can wrap the recaptcha code in a div and give it a fixed
height? I think perhaps it's partially because the recaptcha is being
pregenerated while the modal is collapsed, so it positions and sizes itself
during the hidden state.

**Comment by IshaGupta18** [comment]
Yes it could be the reason, let me have a look at it. Thanks @jywarren !

**Comment by IshaGupta18** [comment]
What do you suggest the fixed height should be @jywarren ? Since it can only be tested in production?

**Comment by jywarren** [comment]
well, can you count the pixel height of the production version and we'll
just fix it at that, maybe +10px?

**Comment by IshaGupta18** [comment]
Oh yes, my bad, should have thought about it

**Comment by IshaGupta18** [comment]
So I was thinking of give the wrapping div a height of about 120px or something, because the div in which the recaptcha occurs is about a 100px high. How does it sound?

**Comment by jywarren** [comment]
sounds great! Thanks, Isha!

**Comment by SidharthBansal** [comment]
@dhruvgupta167 thanks for reporting the bug. Sorry I missed to thank you.

**Comment by dhruvgupta167** [comment]
> @dhruvgupta167 thanks for reporting the bug. Sorry I missed to thank you.

@SidharthBansal No need! Just trying to contribute to the organisation.

**Comment by SidharthBansal** [comment]
@IshaGupta18 please link the pr number here.
Thanks all

**Comment by IshaGupta18** [comment]
#4672 is the PR for this issue. Thanks a lot everyone! Also, I am sorry for the terrible delay.
