### ISSUE TITLE
Notes Controller Test failing due to different time zone

### ISSUE THREAD

**Issue by ananyo2012** [publiclab/plots2#465]
### What happened just before the problem occurred
Ok I have these tests failing from the first day I deployed the code in my local machine.
![screenshot from 2016-03-26 16 32 23](https://cloud.githubusercontent.com/assets/10486343/14059698/92bf0cc4-f370-11e5-8f84-8c2aed635c1d.png)
I have figured out the problem is probably because of different time zones in different machines. The problem is due to using pre determined time in node fixture.
https://github.com/publiclab/plots2/blob/master/test/fixtures/node.yml#L3-L4

The **test_show_note** sends the date in converting the integer time in date format in using the `Time.at()` method as you can see here.This is where the problem occurs
https://github.com/publiclab/plots2/blob/master/test/functional/notes_controller_test.rb#L47-L47

The show action in notes_controller finds the node using the date fetched in `params[:date]` which doesn't match with the date used in the path of fixtures.
https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb#L44-L44

Should I change the fixture so that it would use the current time of creation and as well as in the node path?

**Comment by jywarren** [comment]
Oh wow, great find! Yes please,  I'd be happy to accept a fix.

**Comment by jywarren** [comment]
Ah, this is fixed in #456 -- can you confirm and re-open if it's not? Thanks! Again, great find. I wouldn't have caught this one.

**Comment by ananyo2012** [comment]
@jywarren I have confirmed and verified that all tests pass. Thanks for reviewing.

**Comment by ananyo2012** [comment]
@jywarren Hey Jeff it is quite off topic here. I am also a GSoC aspirant for this year. I have posted a proposal on **Expanded Q & A system for publiclab.org** in the publiclab website and also on the GSoC site. Would you mind giving your reviews on it? Here is the [link](https://publiclab.org/notes/ananyo2012/03-25-2016/expanded-q-a-system-for-publiclab-org).

**Comment by jywarren** [comment]
Thanks, definitely I'll take a look in the next few days. The next deadline
is April 11, so we do have a little time. Thanks!
