### ISSUE TITLE
Consider ways to group people by topic focus

### ISSUE THREAD

**Issue by milaaraujo** [publiclab/plots2#4659]
>Is there an API endpoint for people who follow a tag, and are in a bounding box? Would we be able to address the above through that? @jywarren 

* [x] - Adding `field` option to `/api/srch/nearbyPeople` (#4703)
* [x] - Add tests and clarification

**Comment by milaaraujo** [comment]
Hey @jywarren,

Answering your question: We do not have an endpoint that returns people who follow the tag and are in a bounding box. However, nearby people endpoint can filter users with a specific user tag (and inside a bounding box). So we could:
1 - Change `/api/srch/nearbyPeople` and instead of filter by user tag we could filter by subscribed tag.
2 - Or modify `/api/srch/nearbyPeople` to receive another parameter, I don't think it is a good idea because it will be very confusing (user tag/tag).
3 - Or add a new endpoint (#4687).

**Comment by milaaraujo** [comment]
I'm not sure... I opened a new PR with suggestion number 2 (#4703). Here added `field` parameter and when `field=node_tag` it search users following the node topic (`tag=query`). 

Actually, I think this solution is more elegant than creating a new endpoint (#4687). What do you think? #4687 or #4703?

**Comment by jywarren** [comment]
Ok, so field switches the tag field between user and node tags? Cool...

**Comment by milaaraujo** [comment]
Exactly!

**Comment by jywarren** [comment]
Ok this sounds great.

**Comment by milaaraujo** [comment]
I just closed  #4687, since it looks like we will be using #4703 approach. 

Can you review #4703 again? I've already fixed what you asked.
