### ISSUE TITLE
Adding multitag-subscribe button to `/tags/:tagname` 

### ISSUE THREAD

**Issue by geekychaser** [publiclab/plots2#4666]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem
Add multiple tag Subscription on email footers 

### 📋Solution

Add line 

`  <p> <%= render partial: 'tag/subscribe_button', locals:{tags: @related_tags } %></p>`

above https://github.com/publiclab/plots2/blob/master/app/views/tag/show.html.erb#L36
(between line 35 and line 36)
after  ` <%= render partial: "tag/show/related_tags" %>`

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by geekychaser** [comment]
@jywarren @SidharthBansal please add `first-timer-issue` label.
Thank you

**Comment by geekychaser** [comment]
![image](https://user-images.githubusercontent.com/24489162/51424601-264d0f80-1bf6-11e9-9f9f-6a974b61bafb.png)

Is it looking fine or do we need some changes ?

**Comment by SidharthBansal** [comment]
Great

**Comment by jshreyans551** [comment]
Hi! Thanks a lot for the opportunity. Can I work on this issue?

**Comment by geekychaser** [comment]
Yeah, go ahead

**Comment by jshreyans551** [comment]
Thanks a lot!

**Comment by Gonnuru** [comment]
Hello, Can I work on this issue as I'm new to publicLab and to opensource contribution too.

**Comment by geekychaser** [comment]
@Gonnuru This issue has been claimed and @jshreyans551 has posted a PR.
you can look up for some other issue.
Thank you

**Comment by Gonnuru** [comment]
@geekychaser Sure, thank you.
