### ISSUE TITLE
Unable to login without clearing cache

### ISSUE THREAD

**Issue by rahul2240** [publiclab/plots2#4669]
Not able to login on publiclab.org
Steps to reproduce:
1. Login using github
2. Logout of all the devices
3. Try to login again using github
Expected Output: User logged in
Actual Output:  Nothing happened

Repeating step 3 multiple times. I observe
  1. Nothing appear at all
  2. flash message with logout successful
  3. Github reauthorize permission

**Comment by gauravano** [comment]
Please provide your PublicLab username? This might be connected to #4522 so if you turn out to be banned due to the bug. I will un-ban your account. Thanks!

**Comment by rahul2240** [comment]
@gauravano I am able to login after clearning out the cache. I have to do it everytime. I tried the same in incognito and same occur after logging out I was not able to login again but on reloading the page, I got my logged in dashboard.

**Comment by gauravano** [comment]
Hey @rahul2240, we did some fixes in OAuth flow sometime ago so can you try to login again?

Thanks!
