### ISSUE TITLE
Weekly Community Check-In #6 - "Expand Your Horizons"

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/plots2#4676]
Hi everyone :wave: !

We all at Public Lab :balloon: - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. The goal of our Community Check-In is for every community member to share something about their work from the past week and about their current week's goal :dart:. You are also welcome to share fun-fact :smile: , new ideas :bulb: , your learning goals :ballot_box_with_check: .

If you're new here, welcome :balloon:, and please comment a Hello message below, we love to work with you. If you're looking for new issues, please try some of our first-timers-only issues.

We're SO EXCITED to have your help!

Is there anything, you would like to share with us from past week's work? What is your plan for this week?

If you have not planned yet, just leave a Hello! so that we know that you are in sync with us :arrows_clockwise: and doing well!

As always, if you're waiting for a review, or if you're stuck, you can request help here, leave a comment on your issue with @publiclab/reviewers mentioned, or ask the community in our [Gitter](https://gitter.im/publiclab/publiclab) chatroom :raised_hands:.

### Gitter
Gitter is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up there for these updates or just to join the conversation :pager:.

### This Week's Theme

I thought of making this week's theme around the idea of `Expanding Your Horizons`. As code contributors to Public Lab software, it's easy to get focused in on one specific project. While this is great, there is so much more to see and learn! This weekly check-in can be a great place to **write about which code base you have been contributing to and something that interests you about it specifically, code related or greater picture**, so that everyone can learn a little bit about all of the projects circulating. 

I was inspired to make this the theme when I learned that there is a wealth of new information to be found in the **Public Lab index of Wiki's, where code contributors are also welcome to share** their knowledge and create research notes and wikis regarding new features, integrations, their work and relevant exciting things. [Take a look! ](https://publiclab.org/wiki/).

### Summer of Code
@jywarren has started a brainstorming post for the ideas page for Summer of Code 2019 -It would be best get some ideas into discussion from the fellow community member before time. People have been brainstorming already - let's do it together!
https://publiclab.org/notes/warren/01-02-2019/brainstorming-for-summer-of-code-2019

### Software Contributors Survey
[This survey](https://docs.google.com/forms/d/e/1FAIpQLSdGoRWXD79h1qMthwA41R1Kf76iajhqwYIC4A05gH2XvCflLQ/viewform) is conducted on a yearly basis to improve our experience. 

The form will remain open until early March, but don't wait to respond!

### People who did the check-ins

- [x] Gaurav Sachdeva (@gauravano )
- [x] Sidharth Bansal (@SidharthBansal )
- [x] Cess (@cesswairimu )
- [x] Harman Jolly (@CoderJolly )
- [x] Rishabh Rawat (@Rishabh570 )
- [x] Sasha Boginsky (@sashadev-sky)

Have a great week everyone :tada: :fireworks: :balloon:

**Comment by SidharthBansal** [comment]
Who will be doing the next checkin?

**Comment by geekychaser** [comment]
@SidharthBansal I would love to do check-in for next week.
Thank you

**Comment by SidharthBansal** [comment]
Great

**Comment by rexagod** [comment]
Greetings everyone! It's always amazing to see all the efforts and hard work everyone is putting around here, even in other repositories as well. I would however, like to take this opportunity to promote an idea that sparked over at the [Image Sequencer](https://github.com/publiclab/image-sequencer/pull/691#discussion_r249277940). The idea basically focuses on creating a pinned issue that advises the newcomers to look the codebase, find any refactor opportunity, and submit their first PublicLab PR for the same! This way they don't have to wait for new `fto`s and the codebase gets refactored too. I'd like you all to give your inputs on this, and whether we can implement it across **all** the repositories? 

Also, I made some `fto`s for the first-timers reading this :wink: 

**PLOTS2:** https://github.com/publiclab/plots2/issues/4681  https://github.com/publiclab/plots2/issues/4680
**Editor:** [#2460](https://github.com/publiclab/PublicLab.Editor/issues/2460)
**Leaflet Blurred-Location:** [#168](https://github.com/publiclab/leaflet-blurred-location/issues/168)

Cheers PL. Let's do this! :100:

**Comment by sashadev-sky** [comment]
@rexagod I think that would be a good idea for a 2nd or so on issue, like @jywarren has that checklist of the workflow 1) finish an FTO 2) Solve a help-wanted 3) Write your own FTO... we could put somewhere in there to find any problems, open an issue regarding them and challenge yourself to solve it.

For the idea of it being instead of an FTO, though, you would have to consider some factors like the new contributor could choose a very unfriendly 1st issue, they wouldn't get the opportunity to be guided one on one by the issue creator, they wouldn't get familiarized with the PL workflow. That small bit of structure really helped me get acclimated when I first started. I think the size of the code base makes a big difference too. For smaller ones like image-sequencer it could work much better than in  plots2. 

what are your thoughts?

**Comment by cesswairimu** [comment]
Hello everyone :wave:,
I have been working on expanding the statistics project. What excites me about this project is the amount of data on the website and how it is can be used to track trends so I am just trying to make it easier to track the trends and the people doing data analysis easy for them to retrieve the data.
Nice theme @sashadev-sky,

**Comment by oorjitchowdhary** [comment]
Hello all 👋 
I haven't been online lately -- sorry for that.

Hope I'm just in time to ask this...
As per GCI rules, a Grand Prize Winner can ask for a Letter of Recommendation. I had asked the GCI Program Manager but she insisted to ask the mentors to write it out as they've worked with me.

So, @publiclab/reviewers can I ask for a Letter of Recommendation for me for my work and contributions to the organization.

This will be great help..
Thanks. 😄

**Comment by SidharthBansal** [comment]
Whom did you ask?
There are multiple program manager at different locations. Can you please
name her?
Yeah sure we can help you with LORs. You can ask us whenever you have to
submit it anywhere. We will help you with it

**Comment by oorjitchowdhary** [comment]
I asked GCI support and Stephanie Taylor replied to that thread.

I don't really have to submit it anywhere yet but I'd like to have it.

**Comment by shubhscoder** [comment]
I would like to do the community check in the next to next week after @geekychaser has done it. Thank you!

**Comment by gauravano** [comment]
Reminder for @geekychaser: Please open the community check-In on Monday (or Sunday evening). Also, please drop a message in Gitter channel (tagging @all) after opening a check-In. As using Gitter channel we can try to reach max people. You can take more ideas from here - https://github.com/publiclab/plots2/issues/4692#issuecomment-457413684

Also, we are discussing more ideas here - https://github.com/publiclab/plots2/issues/4692. Thanks @sashadev-sky for thinking about community outreach.

**Comment by gauravano** [comment]
New weekly check-in opened at #4711. Thanks all of you!

**Comment by jywarren** [comment]
I missed chiming in this past week, so I just wanted to say I really loved the theme and all the ideas shared here. Lots of growth in our community and this is how we achieve it! @rexagod we have a few pinned issues in this repo along with those at the "support" label. Maybe these could be generalized for other repos or copied?
