### ISSUE TITLE
Replace "&amp;" HTML Entity

### ISSUE THREAD

**Issue by rexagod** [publiclab/plots2#4681]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: There are many instances of code containing "`&amp;`" to implement the "&" character in the website, but instead it renders the "`&amp;`" string itself.

![screenshot from 2019-01-22 01-30-28](https://user-images.githubusercontent.com/33557095/51496495-03814d80-1de6-11e9-8532-b292623d00db.png)

In order to resolve this, we can replace the following "`&amp;`" instances by "and".

````
./app/views/editor/_editor.html.erb:
   17:           Drag &amp; drop to add an image or file, or 

./app/views/editor/_main_image.html.erb:
   17:         Drag &amp; drop to add an image, or 

./config/locales/views/comments/_edit/en.yml:
    7:       drag_and_drop: "Drag &amp; drop to add an image or file, or"

./config/locales/views/comments/_form/en.yml:
    7:       drag_and_drop: "Drag &amp; drop to add an image or file, or"

./config/locales/views/users/_photo/en.yml:
    7:       drag_and_drop_image: "Drag &amp; drop to add an image, or"
````

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by Chrisyee22** [comment]
Can I work on this?

**Comment by rexagod** [comment]
Hey @Chrisyee22! Sure, go ahead!

**Comment by prashant0598** [comment]
@rexagod Can I work on this issue if it is not claimed.

**Comment by rexagod** [comment]
Sure, go ahead @prashant0598!!

**Comment by arungoel123456** [comment]
Can i work on this issue?

**Comment by rexagod** [comment]
Sorry @arungoel123456, it looks like @Chrisyee22 has already submitted a PR. But you can go ahead and checkout [other first timer issues](https://github.com/publiclab/plots2/issues?q=is%3Aopen+is%3Aissue+label%3Afirst-timers-only) in the meantime. Thanks!

**Comment by RizwanSyed357** [comment]
Hi, Is anyone still working on this? If not, I'd be keen. First timer here :)

**Comment by gauravano** [comment]
Hi @RizwanSyed357, this one has a PR in #4700 and I think you have already started work on another FTO issue, so let's complete that for now. Thanks!

**Comment by RizwanSyed357** [comment]
@gauravano Thanks for that

**Comment by ShazZaman** [comment]
Hello Guys, is anybody currently working on this issue?

**Comment by gauravano** [comment]
Hi @ShazZaman, this issue has a PR in progress at #4700. You can find more FTO issues at https://code.publiclab.org/#r=all and if you don't see any unclaimed there, then feel free to comment here, we'll try to open an issue for you. Thanks!

**Comment by ananyaarun** [comment]
@rexagod @gauravano Can i work on this ? I am a newcomer and looks like the previous two PR's are closed for this issue at the moment :)

**Comment by gauravano** [comment]
Hey @ananyaarun, you can work on it. Let's just confirm with @Chrisyee22 once, as their PR https://github.com/publiclab/plots2/pull/4700 is closed just a week ago. Thanks!

**Comment by Chrisyee22** [comment]
I didn’t even see my PR was closed. Were there any issues with my initial PR?

**Comment by gauravano** [comment]
@Chrisyee22 can't say anything as I haven't reviewed your PR. I guess, you have already worked on FTO @Chrisyee22 and I also saw your PR https://github.com/publiclab/plots2/pull/4906 merged, so do you mind if we consider @ananyaarun's PR #4930 instead of your's? 

Thanks!
