### ISSUE TITLE
Remove `/api/srch/peoplelocations` endpoint

### ISSUE THREAD

**Issue by milaaraujo** [publiclab/plots2#4685]
Hey @jywarren,

Since we have the option `sort_by=recent` in the `/api/srch/nearbyPeople`, do you think we can remove `/api/srch/peoplelocations` endpoint (search the the users with most recent activity that have coordinates - lat and lon values - on their user tags)? `nearbyPeople` search users within the rectangle boundary which is better than use the two points logic.

It looks like `/api/srch/peoplelocations` is not used anywhere.

**Comment by jywarren** [comment]
Sure, and great!
