### ISSUE TITLE
Add some css transitions effect

### ISSUE THREAD

**Issue by avsingh999** [publiclab/plots2#4688]
I think if there will be some CSS transitions such that to make delay the animation. It will be good.
![pub1](https://user-images.githubusercontent.com/25536022/51529603-0b310880-1e5f-11e9-9aee-584b13b01849.gif)

**Comment by jywarren** [comment]
That'd be nice! Maybe a blind-down?

**Comment by avsingh999** [comment]
yes @jywarren 
: )

**Comment by arungoel123456** [comment]
@jywarren  can I please work on this issue

**Comment by gauravano** [comment]
Hey @avsingh999, nice idea! 

Note: `first-timers-only` issues need to have this template https://github.com/publiclab/plots2/blob/master/.github/ISSUE_TEMPLATE/first-timers-issue-template.md for being eligible to be a FTO issue, so please take care to follow the template from next time. 

@avsingh999 you want to work on this issue yourself or @arungoel123456 can take on this one? Also, @avsingh999 you can help @arungoel123456 in solving this issue either by making it a FTO or by guiding steps in comments(in case you don't want to solve this one). Thanks!

**Comment by avsingh999** [comment]
@gauravano  Sorry for that. I will use that template for next time.
thank you : )

**Comment by avsingh999** [comment]
@arungoel123456  go ahead.
:smile:

**Comment by suhailsinghbains** [comment]
Hey, can I please work on this, I am new here.
Thanks

**Comment by gauravano** [comment]
Hey @suhailsinghbains, let's just confirm from @arungoel123456 whether he has raised any PR for this issue or not and after that you can collaborate with him for solving this or solve it individually if he's not interested anymore. Thanks!

**Comment by arungoel123456** [comment]
I am working on this issue ....please don't give it to anyone else

**Comment by yash98gupta** [comment]
i would like to solve this issue. @arungoel123456 , would you like to collaborate ?

**Comment by sagarpreet-chadha** [comment]
That would be great @yash98gupta  😄 !

**Comment by siddhishree** [comment]
Can I work on this issue if no one is currently working on this? @suhailsinghbains @avsingh999

**Comment by gauravano** [comment]
hey @siddhishree, go ahead :+1:

**Comment by yash98gupta** [comment]
i have solved this issue ! . Need some help while making a pull request.

**Comment by avsingh999** [comment]
@yash98gupta which type of help you want?
thanks : )

**Comment by yash98gupta** [comment]
@avsingh999 I have made a pull request , also attached a gif along with it .
![new](https://user-images.githubusercontent.com/30808897/54032846-bf50dd80-41d8-11e9-96a4-12ece060249e.gif)

**Comment by avsingh999** [comment]
@yash98gupta  I think It would be better if we can also add transitions when clicking for hiding.
sorry for late reply.
 thanks : )

**Comment by tirlochanarora16** [comment]
Hey, can I work on this issue?

**Comment by mishra2019** [comment]
@avsingh999 it  seems like this is still open, can i work on this issues

**Comment by PremMuddu** [comment]
Hello, Is this issue still open? May I work on it if its still active?

**Comment by KarishmaVanwari** [comment]
Can I take up this issue, if it is still available? @avsingh999

**Comment by nawed2611** [comment]
Hey! Is this issue still open? I wanted to work on it.

**Comment by mohdabbas955** [comment]
hello,is this issue still open ? I want to work on it @avsingh999

**Comment by TildaDares** [comment]
Hi @mohdabbas955, yes you can work on this.

**Comment by KarishmaVanwari** [comment]
@mohdabbas955 Are you still working on this issue? If not, I'd like to take it up @TildaDares .

**Comment by TildaDares** [comment]
Unassigning @mohdabbas955 since there have been no updates.

**Comment by TildaDares** [comment]
@KarishmaVanwari The JS code is in https://github.com/publiclab/plots2/blob/c1280156f6ecbfe5dc27b5c2f516f3eb7243d878/app/assets/javascripts/sidebar.js#L1-L13

HTML Code:
https://github.com/publiclab/plots2/blob/c1280156f6ecbfe5dc27b5c2f516f3eb7243d878/app/views/sidebar/_question.html.erb#L5

**Comment by TildaDares** [comment]
This is what it looks like presently: https://publiclab.org/questions/Softconcept_Africa/09-29-2016/question-put-some-dustduino-in-africa

You have to view it in small screen mode to see the dropdown.

**Comment by KarishmaVanwari** [comment]
Okay, thank you so much @TildaDares!

**Comment by KarishmaVanwari** [comment]
Hey @TildaDares , I've raised a PR #10735 . Please do have a look. Thanks!
