### ISSUE TITLE
build error on stable branch, minitest gem

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4689]
I'm seeing an error on the stable build server:

```
Bundler::GemNotFound: Could not find minitest-reporters-1.3.6 in any of the sources /app/config/boot.rb:6:in `<top (required)>' /app/config/application.rb:1:in `<top (required)>' /app/Rakefile:5:in `<top (required)>'
```

Any idea why this is happening or how to resolve it? Is this a very recent release maybe and dependabot got ahead of the gem sources? @publiclab/plots2-reviewers

**Comment by jywarren** [comment]
Error here in full https://jenkins.laboratoriopublico.org/job/Plots-Stable/lastBuild/console

**Comment by gauravano** [comment]
Hi @jywarren, I opened the link you pasted above but I am seeing this error-

```ruby
 Bundler::GemNotFound: Could not find i18n-1.5.3 in any of the sources
/app/config/boot.rb:6:in `<top (required)>'
/app/config/application.rb:1:in `<top (required)>'
/app/Rakefile:5:in `<top (required)>'
```

**Comment by gauravano** [comment]
I ran `bundle install` locally at up-to-date master and  got this message:

![build_message](https://user-images.githubusercontent.com/20878070/51537206-e7c48880-1e73-11e9-88ae-fe9090d85a13.png)

**Comment by gauravano** [comment]
The error you got @jywarren was encountered in https://jenkins.laboratoriopublico.org/job/Plots-Stable/816/console and last build https://jenkins.laboratoriopublico.org/job/Plots-Stable/818/console is showing the above error - https://github.com/publiclab/plots2/issues/4689#issuecomment-456390410

**Comment by jywarren** [comment]
Hmm @icarito any ideas here? Also see the referenced PR...

**Comment by icarito** [comment]
Hi, I did a few tests and finally tried this in our staging server:

```
$ wget https://raw.githubusercontent.com/eligrey/FileSaver.js/be09a02e8cd3fe7046a692b19f6aa9631d0146c7/package.json--2019-01-23 23:45:42--  https://raw.githubusercontent.com/eligrey/FileSaver.js/be09a02e8cd3fe7046a692b19f6aa9631d0146c7/package.json
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... failed: Connection timed out.
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.64.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1255 (1.2K) [text/plain]
Saving to: ‘package.json’

package.json                     100%[========================================================>]   1.23K  --.-KB/s    in 0s      

2019-01-23 23:47:57 (27.3 MB/s) - ‘package.json’ saved [1255/1255]
```

Note the timeouts when downloading. This is a problem with the network connection at the MIT site, I believe.

**Comment by jywarren** [comment]
Is this something we might report to them to be helpful?

I'm now also watching stable for the latest build to see if it worked.
Thanks!

**Comment by icarito** [comment]
I think this blocker has been solved by tweaking the server's DNS configuration. Let me know if it resurfaces!

**Comment by jywarren** [comment]
Thanks!!!!! Let's follow up later, good ideas.
