### ISSUE TITLE
rename development.db to development.db.example

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#469]
## Problem

People are accidentally committing changes to their development.db - we should fix this if we ship it.

@lalithr95 has suggested renaming to development.sqlite, but I don't think the extension is the problem. We can keep using development.db, and add development.db to the .gitignore file, I believe. Since development.db is already in a lot of peoples' repositories now, I'm inclined not to change it. This indicates that there's not a standard: http://stackoverflow.com/questions/808499/what-is-the-best-extension-name-sqlite-database-files . And if people choose to add .sqlite to their database.yml, then it won't be tracked, so we don't have to worry about it. 

So I think we just need to confirm that:

* [ ] Does .gitignore ignore new copies of the file when pulling from remote? 
* [ ] Does .gitignore prevent a copy of the file from being created locally on initial git clone?
* [ ] Does a .gitignore ignored file cause conflicts when pulling down a new version over a locally changed file? 

****

**Update:** Apparently, .gitignore will only stop files from becoming git-tracked. It does not, [according to this post](http://stackoverflow.com/questions/1274057/making-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore?rq=1), stop tracking updates to files which are already in git. So it seems the above plan won't work. [More info here](http://stackoverflow.com/questions/1139762/ignore-files-that-have-already-been-committed-to-a-git-repository?rq=1)

****

The alternative is to add one more step to the setup instructions, and ship a development.db.example (at which point we might as well rename it development.sqlite.example) and tell people to copy it over if they intend to use the ready-to-go sqlite database.

**Comment by lalithr95** [comment]
I just saw your PR on local db setup which adds sqlite3 extension rather db ext. Sqlite3 works fine in local setup. Will this PR be merged today or as per schedule ? May be we can add an exception for this one.

**Comment by jywarren** [comment]
I'm going to wait, and tomorrow's schedule may get delayed as well (though
I will try) because we're in a staff meeting this week. But I was planning
to wait until tomorrow and to merge it then. Any help you can offer in
making sure people are aware of the change will be appreciated. They may
need to `git checkout development.db` before pulling, and will lose their
local development database changes as a result. We should warn and ensure
people back it up it they wish to keep it.

Thanks!
