### ISSUE TITLE
Refactor alerts for Login flow

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#4691]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

At time of login via OAuth the notices are wrongly shown and sometimes delayed too. See this for reference - https://drive.google.com/open?id=1w9tc4kIkoLJ5tvceoyQ1-kO_yug2pMDR

The link to file which requires help with notice - https://github.com/publiclab/plots2/blob/master/app/controllers/user_sessions_controller.rb#L58 

Also, this issue - #4522 can be referenced where details/progress about resolving the Login issue is recorded.

Thanks!

**Comment by jywarren** [comment]
We'll need to replicate the types of alerts shown in non-oauth login,
including the "your account was banned" type message and others. Thanks!

**Comment by keshav234156** [comment]
@SidharthBansal **UPLOADED ON GCI DASHBOARD**

**Comment by SidharthBansal** [comment]
Published

**Comment by Uzay-G** [comment]
Hey, I submitted a pr for this task #7056. I cannot claim it yet, but @SidharthBansal has allowed me to work on other tasks. Happy new year!

**Comment by SidharthBansal** [comment]
Yeah, your previous task is under review so technically you are doing only
one task at a time.
I will review it soon.

**Comment by SidharthBansal** [comment]
Due to multiple PRs, changing score from 5points (hard) to 15 points (hoF) Jeff.
Thanks all

**Comment by SidharthBansal** [comment]
@Uzay-G is this issue completed?
Can we close this?

**Comment by Uzay-G** [comment]
Yeah everything all these issues will be solved once we merge #7072.

**Comment by SidharthBansal** [comment]
https://codein.withgoogle.com/dashboard/task-instances/5150671058239488/

**Comment by SidharthBansal** [comment]
You have already received points for this issue
Thanks
