### ISSUE TITLE
Ideas for handling weekly check-in mentions

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/plots2#4692]
I mentioned yesterday I wanted to look into the contributor data made available by Github to see if I could come up with a way to use it to handle check-in mentions. (Currently need to manually tag, with a limit of 25 mentions, and no system in place for swapping out inactive users or swapping in new ones)

I pulled the data from plots2 commits from the past 2 months and mapped it out on tableau. Apparently the platform I made it on is made for security, not sharing your work, so here is a PDF reference instead: https://drive.google.com/open?id=12xQtmFVOCFwEm1GtP_vGsNO1Pz-FDRjt (Thank you @gauravano)

I was initially planning to add the rest of the repos and the teams, but I didn't see much more to the data besides # of commits and I felt like that doesn't align with public lab's workflow. I thought this is a good place to stop and get others' opinions about it. Please see my comments at the bottom of the page!

Also the table is for 2 months but the actual data goes back to 2012. If anyone wants the (mostly) nicely formatted excel data feel free to ask for a link below.

**Comment by geekychaser** [comment]
@sashadev-sky It is giving incorrect password or email.
Please correct me if I am wrong

**Comment by gauravano** [comment]
Same here :sweat_smile:!

**Comment by gauravano** [comment]
I think you can add more users to your project by visiting Users option and then adding user from there. Like I am able to see that option at https://eu-west-1a.online.tableau.com/#/site/gauravs/users for my default project.

**Comment by sashadev-sky** [comment]
@geekychaser @gauravano I deleted myself as a 'connected client' maybe you will be able to log in now? If not I can add both of you with your emails if that is okay?

**Comment by gauravano** [comment]
I tried logging in but same error. You can send me invite at sachdeva.gaurav1997@gmail.com Thanks!

**Comment by geekychaser** [comment]
Still facing the same error.
email: geekychaser@gmail.com

**Comment by sashadev-sky** [comment]
@gauravano @geekychaser added! Thank you for being patient with me

**Comment by gauravano** [comment]
Awesome work @sashadev-sky! I think we can do some innovation with Community-Toolbox for listing new contributors. Also, many a times other repo's contributors get ignored due to all the light just on Public Lab. 

We can also announce in Gitter channel about check-In so that it gain some more attention. And, as there's some limit over the number of users which can be mentioned at a time. We can break some numbers in comments. As it's understandable that GitHub doesn' allow it because for every mention email needs to sent. More ideas are welcome!

Thanks!

**Comment by gauravano** [comment]
And, here's the work done by @sashadev-sky in PDF form - https://drive.google.com/open?id=12xQtmFVOCFwEm1GtP_vGsNO1Pz-FDRjt . So, no one need to be invited anymore. Thanks!

**Comment by sashadev-sky** [comment]
@gauravano Thank you for sending it out to everyone in a non-complicated format! 

Sorry, what do you mean by do some innovation with Community-Toolbox? 

Also for check-in, I felt like copy-pasting and manually updating a list of mentions can get confusing - today I noticed every issue has had many duplicate mentions and that can snowball over time. 

At the bottom of the file I mentioned just creating a team and mentioning it instead of individuals. This way its easy to add new people and no need to keep track closely. Gitter is also a good solution! Then maybe we could skip teams and mentions altogether and each week a quick Gitter message could just serve as a reminder (/ introduction) linking the check-in.

**Comment by gauravano** [comment]
> Sorry, what do you mean by do some innovation with Community-Toolbox?

The https://code.publiclab.org page whose codebase is Community -toolbox uses GitHub data for showing contributors too. May be, we can use it to generate a list of new unique users?

> At the bottom of the file I mentioned just creating a team and mentioning it instead of individuals. This way its easy to add new people and no need to keep track closely.

This one will require moderators to update the team regularly - adding new contributors and then removing too old and inactive users. Also, we have to take person's consent before adding them to team. 

So, announcing in Gitter seems nice option as that way all the interested and active people would be updated. 

Thanks!

**Comment by sashadev-sky** [comment]
@gauravano so I guess for innovation with generating and showing statistics about user contributions publiclab/community-toolbox#131 is now the place to discuss. I will write there shortly :)

As for the check-ins, I like the idea of going forward with Gitter. I can write up a plan for switching to that solution and other details if you want to go ahead with it, let me know!

**Comment by gauravano** [comment]
> As for the check-ins, I like the idea of going forward with Gitter. I can write up a plan for switching to that solution and other details if you want to go ahead with it, let me know!

Currently, each week we offer someone new (who haven't opened Check-In before) to do open the check-In. I think we can include this step - "Sharing of Check-In issue in Gitter channel" to the process? What do you think?

Thanks

**Comment by sashadev-sky** [comment]
@gauravano Yes do you think it should be the same message every time? Something like "hi all, please see our weekly check-in here. Everyone is welcome to contribute and we encourage new users to get involved" and in the check-in itself add something like "we share this weekly check-in on gitter consider signing up so you can receive weekly reminders when its posted"

Just wanted to make it clear that the check-in is not exclusive because I got some messages from people asking how they could join.

**Comment by sashadev-sky** [comment]
@gauravano I think it mentions new users already but we can make it even more explicit

**Comment by gauravano** [comment]
> @gauravano Yes do you think it should be the same message every time? Something like "hi all, please see our weekly check-in here. Everyone is welcome to contribute and we encourage new users to get involved" 

Although, from a perspective of newcomer, I would like to see new messages every week, that's the reason I and most of people would agree that doing check-in in rotations is good and everyone get to express their theme ideas/expressions. 


> "we share this weekly check-in on gitter consider signing up so you can receive weekly reminders when its posted"

That's nice idea! 

> Just wanted to make it clear that the check-in is not exclusive because I got some messages from people asking how they could join.

That's great! We can also point them to publiclab.org, like this time you did it well.

Thanks!

**Comment by sashadev-sky** [comment]
@gauravano I saw your message in the check-in! Should I close this issue?

**Comment by gauravano** [comment]
yes, it can be closed now, also could you please add [lines](https://github.com/publiclab/plots2/issues/4692#issuecomment-457413684) to currently open check-in, so they are not missed by contributor whoever opens new check-in. And, thanks for brainstorming over the ideas for community outreach.

cc @jywarren

**Comment by sashadev-sky** [comment]
@sashadev-sky Ok I changed it! Feel free to make any edits to it. I also was thinking to add the new reviewers group, where it says who to ask for help, but I wasn't sure if they are fully integrated yet.

**Comment by gauravano** [comment]
Hmm, as check-in is common for all the Public lab repos so we need to add something like: "Ask @publiclab/plots2-reviewers for help with plots2 project, @publiclab/is-reviewers for ImgSeq" and so on. Thanks!

**Comment by rexagod** [comment]
Just a thought, possible `fto` would be making a "Check-in" template with all the necessary info like the one above.

**Comment by gauravano** [comment]
But, then everyone will just copy the template and will not try to play with the words, ideas, etc, in short, will not try anything new. Like, this time Sasha added about publiclab.org and how useful it is and theme, so we want everyone to be excited to get involved and know something new.

**Comment by gauravano** [comment]
But, we can document steps for check-in opening, which will tell people what we expect from the check-in and what they have to do(like, making it an official part). What do you all think?

**Comment by sashadev-sky** [comment]
@gauravano Great idea. I can write that up if you would like, or we can put it on a Google doc so we can easily collaborate on it because it's pretty subjective. @rexagod @geekychaser

**Comment by sashadev-sky** [comment]
@gauravano On it! and for the new check-in (I will check-in there shortly :) @geekychaser ) did we decide to do Gitter and keep the tags on the post? I think the tags could be removed, and perhaps just keep a few for community organizers (maybe like ebarry jywarren gauravano SidharthBansal whoever else I may have missed)

**Comment by gauravano** [comment]
> did we decide to do Gitter and keep the tags on the post?

yes, current check-in contains the Gitter link and I announced in Gitter channel about the check-in too.

>  I think the tags could be removed, and perhaps just keep a few for community organizers (maybe like ebarry jywarren gauravano SidharthBansal whoever else I may have missed)

Let's keep tags for a while but yeah, we can cross some names as per best of our knowledge of active contributors.

Thanks!

**Comment by jywarren** [comment]
🌱 🍃 🌴 🌲 🌳 ⚡️

**Comment by sashadev-sky** [comment]
closing via #4718
