### ISSUE TITLE
Misplaced "I'm not a robot" image over signup button

### ISSUE THREAD

**Issue by Dhiraj240** [publiclab/plots2#4698]
![screenshot 191](https://user-images.githubusercontent.com/29758643/51603693-88787e00-1f30-11e9-93ca-b9a0334b46fb.png)

**Comment by gauravano** [comment]
Hi @Dhiraj240, thanks for reporting the issue. This issue is already reported at https://github.com/publiclab/plots2/issues/4643 and solved too. The changes would be soon pushed on the production. Thanks!

**Comment by Dhiraj240** [comment]
Oh !! great
