### ISSUE TITLE
Number of languages required at Public Lab

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#4701]
Hi everyone!

Currently, the drop-down in the footer of the website offers 2 addition languages German and Chinese. But, at Transifex, we have availability of 8 languages and there are many translations available(Hurray :tada: ). 

At planning issue #3262 @jywarren took a call for single locale file per language. So, now the question is how many languages we want to consider for the integration with our website?

@jywarren @ebarry @steviepubliclab thoughts?

**Comment by jywarren** [comment]
Shall we use the 8 mentioned? Perhaps let's especially aim to have
Portuguese, Spanish, and a few others from areas that have done public lab
work?

**Comment by gauravano** [comment]
@jywarren we can surely have all the languages one by one. Some points I am brainstorming are:
1. At Transifex all these languages are also present in different files, so we will be merging them
2. There are 2 states - Translated and Reviewed, https://docs.transifex.com/projects/downloading-translations 

So, we need to merge all those files in a single file for each language. I need to download these files but while downloading should I retrieve all strings which are translated or only those ones which are reviewed.
 
Choosing only the reviewed string will lead to losing the strings which haven't been reviewed when we delete those files. I am also thinking of an idea to tackle this situation, I will make one additional folder where I will be keeping the translated only strings and after making lan-specific single files and syncing and all, I will manually propose those strings and then reviewers can take up from there. I know this one sounds a little more work but is considerable. What do you think @jywarren ?

**Comment by jywarren** [comment]
Oh I see.  Yes that sounds like a great solution!!

**Comment by gauravano** [comment]
@jywarren  I have posted in Transifex community - https://community.transifex.com/t/transitioning-from-directory-structure-to-single-file-structure-rails/152?u=gauravano about our issue asking for advice for any alternate approach.

**Comment by PritiShaw** [comment]
Hi @gauravano @jywarren 
I am an outreachy aspirant and new to open source. I would like to work on this issue. Kindly assign it to me if no one else is working on it.

**Comment by gauravano** [comment]
Hey @PritiShaw, actually this issue is not required anymore so closing now. Sorry for inconvenience.
