### ISSUE TITLE
Combine all the YAML files present in config/locales in a single file

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#4702]
At https://github.com/publiclab/plots2/tree/master/config/locales we have all the YAML files in the directories. We want to combine all the files present in those directories with one file for each language. Let's start with English. 

Either we can do this task manually or can use some help from existing resources. I have found https://gist.github.com/branch14/1010381 to be useful and have tested it too. Yes, it works. 

@jywarren I think we can use above code first to combine and then run https://gist.github.com/branch14/5746d4f117f00490fea5 to count for conflicts. As a precaution, I will look at the combined file closely too for ensuring integrity. Sounds good?

**Comment by akshaygupta533** [comment]
Can I collaborate with you on working on this?

**Comment by gauravano** [comment]
Hi @akshaygupta533, you can help for sure, I will try to divide the tasks from this one soon. Thanks!

**Comment by gauravano** [comment]
Hi @jywarren @ebarry @steviepubliclab, 

Here's the progress at Transifex 
![overview_translations](https://user-images.githubusercontent.com/20878070/51834508-90656300-2320-11e9-82b5-dac959649651.png)

As you can see the number of strings reviewed are very less. I have exported the report - https://docs.google.com/spreadsheets/d/1SznxOoZXHnh6gxMyd2lAshSYXSHfHg46JoblBzr__qA/edit?usp=sharing
and you'll find that total number of reviewed strings are 5 (https://docs.google.com/spreadsheets/d/1SznxOoZXHnh6gxMyd2lAshSYXSHfHg46JoblBzr__qA/edit#gid=242146977&range=Q73).

 Earlier, I was thinking of exporting all the reviewed strings only but after going through records in detail - I am working to combine Translated strings, of all languages, as just 5 strings are reviewed so I will review those myself after combining. I hope you all agree on this one. 

**Translated strings:** Strings which are translated by someone but not reviewed by any moderator/expert so trust level is less

**Reviewed strings:** Strings which are translated by someone and reviewed by a moderator/admin/expert so we can trust that translation and use it in our website

**Comment by gauravano** [comment]
Completed in #4751. Thanks!
