### ISSUE TITLE
Weekly Community Check-In #7 - "Commitment" 

### ISSUE THREAD

**Issue by geekychaser** [publiclab/plots2#4711]
Hi everyone :wave: !

We all at Public Lab :balloon: - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. The goal of our Community Check-In is for every community member to share something about their work from the past week and about their current week's goal :dart:. You are also welcome to share fun-fact :smile: , new ideas :bulb: , your learning goals :ballot_box_with_check: .

If you're new here, welcome :balloon:, and please comment a Hello message below, we love to work with you. If you're looking for new issues, please try some of our first-timers-only issues.

We're SO EXCITED to have your help!

Is there anything, you would like to share with us from past week's work? What is your plan for this week?

If you have not planned yet, just leave a Hello! so that we know that you are in sync with us :arrows_clockwise: and doing well!

As always, if you're waiting for a review, or if you're stuck, please request help here OR leave a comment with @publiclab/mentors @publiclab/reviewers for some input or ask the community in our [Gitter](https://gitter.im/publiclab/publiclab) chatroom :raised_hands:

### Gitter
[Gitter](https://gitter.im/publiclab/publiclab) is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up there for these updates or just to join the conversation :pager:.

### This Week's Theme

I thought of making this week's theme around the idea of `Commitment`. The idea behind this theme is that there are lots of pending issues which are being claimed. So, this week we will try to complete a maximum of our pending issues before claiming new ones. Approach mentors if you face any difficulty while solving them.

This week I am working on creating mockups for a tour of Publiclab.org and some previously claimed issues.

cc
@mohitRJranjan @milaaraujo @kevinzluo
@stefannibrasil @gauravano @ViditChitkara @tech4GT @mridulnagpal @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab @ebarry @jywarren, @sagarpreet-chadha, @JonathanXu1, @uzorjchibuzor, @eli6, @ValentinaTironi, @rexagod, @sashadev-sky, @IshaGupta18, @dinaelhanan, @cesswairimu, @dependabot[bot], @oorjitchowdhary, @okonek, @wanzulfikri, @mohitRJranjan @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Rishabh570 @aSquare14 @Radhikadua123 @quinn-codes-synthesis @amychan331 @mardelvalle @narnt @hydro-m @love-opensource @romanrodriguez @shubhangi-chauhan @Dhiraj240 @geekychaser @codeIriss @CoderJolly @rishabhc32 @chirag-singhal @Saurabh19126848_twitter @IgorWilbert @dhruvgupta167 @vrk99 @pdurbin @dave-light 

### Summer of Code
@jywarren has started a brainstorming post for the ideas page for Summer of Code 2019 -It would be best get some ideas into discussion from the fellow community member before time. People have been brainstorming already - let's do it together!
https://publiclab.org/notes/warren/01-02-2019/brainstorming-for-summer-of-code-2019

### Software Contributors Survey
[This survey](https://docs.google.com/forms/d/e/1FAIpQLSdGoRWXD79h1qMthwA41R1Kf76iajhqwYIC4A05gH2XvCflLQ/viewform) is conducted on a yearly basis to improve our experience.

The form will remain open until early March, but don't wait to respond!

### People who did the check-ins

- [x] Gaurav Sachdeva (@gauravano )
- [x] Sidharth Bansal (@SidharthBansal )
- [x] Cess (@cesswairimu )
- [x] Harman Jolly (@CoderJolly )
- [x] Rishabh Rawat (@Rishabh570 )
- [x] Sasha Boginsky (@sashadev-sky)
- [x] Rishabh Kr Bothra (@geekychaser)

Have a great week everyone :tada: :fireworks: :balloon:

**Comment by gauravano** [comment]
Thanks for awesome check-in @geekychaser! 

Upcoming week's goal :
1. I would try to do maximum issues I have assigned myself in past
2. Getting more familiar with Mapknitter codebase, reviewing issues, documentation updates, integration, etc.
3. Working on the Translation project, specifically, transferring directory system to file specific system for each language. 

Wish you all happy week ahead, keep coding, contributing and be happy !

**Comment by sagarpreet-chadha** [comment]
Hi all :smile:  !

I will be working on adding latitude and longitude support to PL.editor's map module - which will pan location on map instead of showing default location , to given input location . 
Also reminding myself here to update Readme as well to update API documentation :P .

Thank you all and have a great week ahead :dancer: :tada: !

**Comment by IgorWilbert** [comment]
Hello everyone 😄! I'm very happy for being part of this project!

Upcoming week's goals:
1- Final touches on the PRs I opened for the Editor, so that they can be meged;
2- Investigate old open issues and if possible turn them into FTO-issues;
3- Continue planning on plots2 mobile version for GSoC, pointing out the most important functionalities and how to implement them;
4 - Get familiar with Image Sequencer codebase;

Hope you all have a great week! Let's do this 🚀 !

**Comment by SidharthBansal** [comment]
Hello everyone!!!
I am trying to explore MapKnitter this week. Let's see what I can do and
find interesting.

**Comment by Dhiraj240** [comment]
Hello everyone,
I am going to work on ```Mapknitter``` and ```SpectralWorkbench``` projects.
Initially i will do their setup on my local machine.
For this week my end result should be to understand the codebase of ```Mapknitter``` and solve the issues, if i unable to solve it then i will report at least two code specific ```fto``` issues.

**Comment by ebarry** [comment]
Hi Everyone, 
This week I am interestedly following @cesswairimu's work on https://github.com/publiclab/plots2/pull/4693 (if you have ideas on the readability of graphs, let us know!), also the tag visualization going on here with @skilfullycurled https://github.com/publiclab/plots2/issues/1502, and the conversations on Community-Reps channel: https://github.com/orgs/publiclab/teams/community-reps

**Comment by skilfullycurled** [comment]
Liz can you resend the community-reps link?

Or maybe it’s restricted.

I’m getting a 404.

**Comment by ebarry** [comment]
Hmmm, can you see if you are in the "public lab organization"? https://github.com/orgs/publiclab/people

**Comment by jywarren** [comment]
@skilfullycurled - maybe they're not publicly readable? but i think they are, i just don't know the link. 2 things to think about - first, we'd love to have you join that group, as it's purpose is: `Be the voice of the Public Lab community in feature/bugfix discussions!` -- but also, let's all remember that the "teams" feature is useful for some coordinating but is always to be balanced with the more public/inclusive option of simply posting an issue. In this case, I believe it was a place to have a discussion about an important design change without having to do it all right in front of a new contributor... very much appreciate the sensitivity! Thanks, all!

**Comment by jywarren** [comment]
I'd also like to request some help with breaking this issue down and getting it resolved. I don't think it'll be too hard and it'll make a big difference for oauth users. 

Thanks all!!!

https://github.com/publiclab/plots2/issues/4691

**Comment by cesswairimu** [comment]
Hi all,
This week am committed to get my open three PRs finished and merged.

**Comment by Yugandhartripathi** [comment]
Hello everyone, 
This week I plan to dive into <code>PL.editor</code> codebase and participate in brainstorming for soc 2019.

**Comment by IshaGupta18** [comment]
Hey Everyone, this week I plan to get my PRs for #4632 and #4413 merged. I will have to work on #4632 more to get it in place. Apart from this, I would love to solve more issues, here and and at mapknitter, and brainstorm on SOC ideas for 2019. Thanks for your constant efforts with my PRs @SidharthBansal and @jywarren . I would also like to pitch some ideas to you regarding SOC. Thanks a lot everyone!

**Comment by sashadev-sky** [comment]
Hi all, 

This week I have been working on standardizing the community check-in process #4718 #4692. It's moving along pretty well, comment on the first linked issue if you want to see any other changes :)
As per this weeks theme, I have also been going through open issues to review and offer help.

Thank you!

**Comment by Rishabh570** [comment]
Hello everyone,
My main goal for this week is to analyse and plan out the enhancements for `code.publiclab.org` (looking for the possibilities of different ideas). Also, as I'm currently working on MVC structure of community-toolbox, I'm getting lots of conflicts because of the recent changes in the code, just making my way through them :sweat_smile: 

Hope everyone is having an awesome week :raised_hands: 
Thanks!!!

**Comment by jywarren** [comment]
Hi, everyone! Chiming in again to say that I added a new section to the `gsoc` page here:

https://publiclab.org/wiki/gsoc#How+to+apply

This just outlines the steps a bit and offers a bit more guidance. But don't worry, the big call for proposals as in previous years will be almost the same, and is not yet open. 

Also noting that I helped @IshaGupta18 on #4413 but we weren't able to figure out why it's not matching in the test we've written! We're close to giving up and leaving the test out, but that's not so nice. If anyone would like a nice puzzle, any help appreciated!!!

**Comment by SidharthBansal** [comment]
We generally give the idea list before call for proposals so that you can
think on which topic you can write your proposals. We are always there to
assist in the proposals so there is no need to worry. :smile:

**Comment by jywarren** [comment]
Hi, all! I'm also starting to put together a new Code Community Report, like this one from the start of the month, but summing up the whole year of 2018. If folks have statistics, big picture observations, other things like that which you'd like to suggest for the report, please chime in! 

https://publiclab.org/notes/warren/01-02-2019/public-lab-code-community-report-jan-2019

**Comment by gauravano** [comment]
Hi @shubhscoder, you expressed interest in opening the check-in last week. So, would you be opening check-in for next week? 

Thanks!

**Comment by shubhscoder** [comment]
Yes sure! I ll open the check in by tomorrow 👍

**Comment by gauravano** [comment]
Great! You can open check-in on Monday too, there is no hurry. Also, @sashadev-sky @rexagod and I have prepared some guidelines for opening Check-in, please try to follow them - https://github.com/publiclab/plots2/pull/4718/files?short_path=5d68667#diff-5d686670ad182a95f3af0779f9940834

Thanks!

**Comment by sashadev-sky** [comment]
@geekychaser I made a mistake in my last check-in about the date the survey closes and I think you had already opened this issue by the time I updated it. I updated it here so that the correct date carries over from this week. Hope thats ok! 

@shubhscoder please note the small change for your check-in :)

**Comment by gauravano** [comment]
New Check-In at https://github.com/publiclab/plots2/issues/4757 . Thank you everyone!
