### ISSUE TITLE
clean up deployment and legacy files

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#472]
This is just a stub to keep track of this task; @icarito and I will be dealing with it. 

* [x] @icarito, do you still use the startup/restart/stop scripts in the home directory?
* [x] I also want to clean up db/empty.sql
* [x] @icarito, were there important reasons to remove `log/.gitkeep`? Or maybe I did that? do we need it?

Thanks!

**Comment by icarito** [comment]
On 27/03/16 12:17, Jeffrey Warren wrote:
>
> This is just a stub to keep track of this task; @icarito
> <https://github.com/icarito> and I will be dealing with it.
>
>   * @icarito <https://github.com/icarito>, do you still use the
>     startup/restart/stop scripts in the home directory?
>
Nope, all starting and stopping is now done as part of the NGINX
initialization as described in our deployment docs:
https://github.com/jywarren/web/wiki/Deployment
>
>   * I also want to clean up db/empty.sql
>
That's not used as far as I can tell.
>
>   * @icarito <https://github.com/icarito>, were there important
>     reasons to remove |log/.gitkeep|? Or maybe I did that? do we need it?
>
It's only needed when cloning initially. I may have removed it when
deploying. I restored it with `git checkout log/.gitkeep` to keep git
happy.
