### ISSUE TITLE
Taglocation API shows spam notes also ?

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#4723]
I guess we need to remove spammed notes ?  
This author is banned on PL .

<img width="1087" alt="screenshot 2019-01-29 at 7 45 05 pm" src="https://user-images.githubusercontent.com/14952645/51914338-a3e6fb80-23fe-11e9-835c-6e34fc080802.png">

Using these coordinates : 

<img width="974" alt="screenshot 2019-01-29 at 7 45 13 pm" src="https://user-images.githubusercontent.com/14952645/51914354-ac3f3680-23fe-11e9-866f-73df56a2ceca.png">

**Comment by jywarren** [comment]
Good catch .We should be able to filter with `Node.where(status: 1)`
