### ISSUE TITLE
Putting single/double quotes around values in locale files

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#4729]
Hi! we are working on combining all the YAML files into language specific files at #4702. After combining the locales using the ruby script, a issue has came to our attention. The issue is the string values of the keys doesn't have double quotes around them. 

Although, some of the translations has been tested locally and they are working fine but for removing any unexpected issue in future, it's best to put the quotes around those string values which contained them originally. So, what needs to be done(in short, but lengthy work :package:)

Put quotes around the string values of this file - https://github.com/publiclab/plots2/pull/4716/files#diff-37c9b835927e3c363588f172de9bb6fa . You have to refer this folder to refer strings original form. Also, if during the process, if you find any key-val pair absent please make a list and comment below. Thanks!

**Comment by akshaygupta533** [comment]
I'll work on this

**Comment by gauravano** [comment]
Hi @akshaygupta533, you have to put quotes for all the strings given in above link - https://github.com/publiclab/plots2/pull/4716/files#diff-37c9b835927e3c363588f172de9bb6fa

using files present in config/locales as the reference.

**Comment by akshaygupta533** [comment]
@gauravano your link redirects to config/locales/en.yml
Could you provide me the path of the file to be changed?

**Comment by gauravano** [comment]
Hi @akshaygupta533, what I did in #4716 is - I merged all the en locales in a single en.yml as you can see in the PR. In that merge process, the quotes are removed from some of the string values so we need to put quotes wherever they were originally present.

You can see the new merged file here - https://github.com/publiclab/plots2/pull/4716/files#diff-37c9b835927e3c363588f172de9bb6fa. You can fetch that file by - 

`git fetch https://github.com/publiclab/plots2 pull/4716/head:pr-4716 && git checkout pr-4716`. This will fetch that branch to you. After that you can put quotes by matching string from https://github.com/publiclab/plots2/tree/master/config/locales and put quotes whereever they are required.

Any question?

**Comment by akshaygupta533** [comment]
So basically I have to add double quotes to the string values in your merged file by comparing with the original unmerged ones?

**Comment by gauravano** [comment]
Yes!
