### ISSUE TITLE
Update Code of Conduct using https://publiclab.org/conduct

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#4730]
In recent days, we have opened FTO's in all our repositories for adding Code of Conduct and all this time we were copying the plots2/code_of_conduct file for updating other repos. So, let's update our Code_of_conduct here at plots2 first and after that copy that single copy at all other repos. 

Also, please make a list of changes which would be required to make by contributors after the document update to copy it to other repositories. 

Here's the Code of conduct at plots2 - https://github.com/publiclab/plots2/blob/master/CODE_OF_CONDUCT.md and it needs update as per https://publiclab.org/conduct .

Thanks!

**Comment by gauravano** [comment]
hey @publiclab/community-reps, please confirm if the https://publiclab.org/conduct is up-to-date and requires no change so that changes at GitHub copy can be initiated. Thanks!

**Comment by AdiyogiV** [comment]
Hey, can I take up this issue if it's still available?

**Comment by gauravano** [comment]
Hi @AdiyogiV, go ahead. Thanks!

**Comment by AdiyogiV** [comment]
List of changes made here (to be copied to other repos) :
1. Under section 'How it Works?' sub-section 'Two helpful groups' sub-section 'ConductCom' : 
  a) Update Conduct committee member names. 
  b) Update method to report violation of Code of Conduct.
2. Change date of updation.

**Comment by jywarren** [comment]
Thanks, @gauravano -- My main concern here is that any time /conduct changes, we'd have to update many different CODE_OF_CONDUCT.md files. Could we reduce the text of CODE_OF_CONDUCT.md to provide basic information but largely point at https://publiclab.org/conduct, so as to prevent them from going out of date? @ebarry your thoughts?

**Comment by gauravano** [comment]
That's a nice idea @jywarren! So, if any of @publiclab/community-reps can list those sections which they believe doesn't change frequently and are good to be included here in the file, that'll solve our problem.

Sections to be included in CODE_OF_CONDUCT.md:
- [ ] Section 1


@ebarry @jywarren @steviepubliclab please list the sections in above list or you can also make changes in #4795 directly or point to a collaborated doc. Thanks!

**Comment by jywarren** [comment]
Hi! Updating here -- i think we could have quite a short file, like 

```
# Public Lab Code of Conduct 

We are coming together with an intent to care for ourselves and one another. We want to nurture a compassionate democratic culture where responsibility is shared. We -- visitors, community members, community moderators, staff, organizers, sponsors, and all others -- hold ourselves accountable to the same values regardless of position or experience. For this to work for everybody, individual decisions will not be allowed to run counter to the welfare of other people. This community aspires to be a respectful place both during online and in-person interactions so that all people are able to fully participate with their dignity intact. This document is a piece of the culture we're creating.

This code of conduct applies to all spaces managed by the Public Lab community and non-profit, both online and in person. It was written by the Conduct Committee (formed in 2015 during Public Lab’s annual conference "The Barnraising") and facilitated by staff to provide a clear set of practical guidelines for multi-day events such as Barnraisings, events led by organizers and community members, and online venues such as the website, comment threads on software platforms, chatrooms, our mailing lists, the issue tracker, and any other forums created by Public Lab which the community uses for communication.

To read the full Code of Conduct and learn how to contact the Conduct Committee or the Moderators group, see:

https://publiclab.org/conduct
```

This way it wouldn't have to be updated as the people change, and wouldn't directly link to the reporting form URL in case that changes. 

@AdiyogiV what do you think; could you update your PR accordingly? 

Thanks, all!

**Comment by CleverFool77** [comment]
Is this issue available :thinking: ? @gauravano @jywarren

**Comment by gauravano** [comment]
hey @CleverFool77, there is a PR open to fix this. I asked the contributor - https://github.com/publiclab/plots2/pull/4795#issuecomment-474364475 , if they don't confirm/complete the PR in 7 days, then you can take it. Thanks!

**Comment by CleverFool77** [comment]
Thanks @gauravano for the info. :)

**Comment by gauravano** [comment]
@CleverFool77 you can work on this one, as the contributor hasn't responded yet. Thanks!

**Comment by CleverFool77** [comment]
Sorry, I missed out the mention in this issue. I'll start working soon. 
Thankss @gauravano

**Comment by CleverFool77** [comment]
Hi @gauravano 
As Mentioned by warren in above comment. 
So I need to put a short info and provide the link to code of conduct ?

**Comment by gauravano** [comment]
Yes @CleverFool77. Thanks!

**Comment by CleverFool77** [comment]
Hi @gauravano I made a PR with the changes suggested in comments.
