### ISSUE TITLE
Add "geocode me" button to editor map interface

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4737]
@sagarpreet-chadha do you think we could add the geolocation button to the map module in the editor?

**Comment by jywarren** [comment]
And the "blur my location" checkbox?

**Comment by jywarren** [comment]
Will it work normally like this? Or do you think we need to integrate the full Leaflet Blurred Location modal, and just have it be consistent?

**Comment by sagarpreet-chadha** [comment]
On it 😄 👍 !

**Comment by jywarren** [comment]
Yes, that's right!
