### ISSUE TITLE
[urgent] Login page link to signup form does not work

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4747]
At https://publiclab.org/login, if you click the `sign up to join` link, nothing happens -- i think it's supposed to work in the modal but is not working on this page.

i'm tracking another login issue, related to OpenID, but will circle back to this.

**Comment by dinaelhanan** [comment]
@jywarren is it here? Want to look into this but don't know how url1 is linking to login modal/ what I could do to help:
https://github.com/publiclab/plots2/blob/2e33bcb229e77cf4994487a8d9439ce784dc09f8/config/locales/views/user_sessions/new/en.yml#L6

**Comment by jywarren** [comment]
thanks for chiming in here! I think i've found a set of interrelated issues and am fixing here: https://github.com/publiclab/plots2/pull/4739

I think i've managed to figure it out... let's see!
