### ISSUE TITLE
Possible changes in README.md

### ISSUE THREAD

**Issue by sidntrivedi012** [publiclab/plots2#4749]
Here, I am adding some possible changes that first timers can make to README in order to get started with contributing.

**Comment by sidntrivedi012** [comment]
Change `We at public labs` to `We, at Public Lab` here - https://github.com/publiclab/plots2#ssl-in-development.

**Comment by sidntrivedi012** [comment]
@jywarren Will this thread be fine. I'll keep adding any changes I feel will help the newcomers.

**Comment by gauravano** [comment]
Yup, the first suggestion is good candidate for FTO issue. I changed your comment @sidntrivedi012 to checklist to track better, hope it's fine. Thanks!

**Comment by sidntrivedi012** [comment]
@gauravano Yeah. Absolutely. Will keep on adding possible changes here as I get more.

**Comment by gauravano** [comment]
Great!
