### ISSUE TITLE
Broken Optional Image tag in sign-up modal/ sign-up page

### ISSUE THREAD

**Issue by IshaGupta18** [publiclab/plots2#4752]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem

Optional Image tag is broken in the sign-up modal/ sign-up page

![image](https://user-images.githubusercontent.com/40794215/52180003-d7fb5b80-2806-11e9-9555-53f860882234.png)

### 📋Solution

To fix the broken image link, change `line 20` in the mentioned file:

https://github.com/publiclab/plots2/blob/08d0f7d4e9b7c1e0d4d9d2e30c4b68c40162751e/app/views/users/_create_form.html.erb#L20

TO:

`<img src="" class="something_something img-circle" style="width: 120px; height: 115px; margin-top: 10px; margin-bottom: 25px; margin-left: 55px; background:#ccc;" onerror="this.src='https://www.gravatar.com/avatar/1aedb8d9dc4751e229a335e371db8058'">`

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by punndcoder28** [comment]
Can I make the change?

**Comment by IshaGupta18** [comment]
Sure go ahead @punndcoder28 ! Feel free to drop a message in case you need any help!

**Comment by jywarren** [comment]
Hi, yes please! @IshaGupta18, I wonder if removing the src parameter entirely would work?

**Comment by IshaGupta18** [comment]
No @jywarren I am afraid it wouldn't. See, this would result in something like this when the image isn't uploaded:
![image](https://user-images.githubusercontent.com/40794215/52180763-6a542d00-2810-11e9-9a9f-62bbc7622351.png)

I think this is because we need to set the value of src parameter to the link provided, so it should be present there.

**Comment by IshaGupta18** [comment]
Chimdiya1 thank you for the pull request, however did you claim this issue before solving it? @punndcoder28 are you going to solve this one or would like to work on some other First Timer Issue?

**Comment by punndcoder28** [comment]
I made the pull request. I haven't recieved any mail further regarding is the my change has been accepted.

**Comment by IshaGupta18** [comment]
Could you please highlight the PR number?

**Comment by punndcoder28** [comment]
I did and I've checked all the boxes.
