### ISSUE TITLE
Weekly Community Check-In #8 - 'Brainstorming for ideas and guiding new comers'

### ISSUE THREAD

**Issue by shubhscoder** [publiclab/plots2#4757]
Hi everyone :wave: !

We all at Public Lab :balloon: - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. The goal of our Community Check-In is for every community member to share something about their work from the past week and about their current week's goal dart. You are also welcome to share fun-fact :smile: , new ideas :bulb: , your learning goals :ballot_box_with_check: .

If you're new here, welcome :balloon:, and please comment a Hello message below, we love to work with you. If you're looking for new issues, please try some of our first-timers-only issues.

We're SO EXCITED to have your help!

Is there anything, you would like to share with us from past week's work? What is your plan for this week?

If you have not planned yet, just leave a Hello! so that we know that you are in sync with us :arrows_clockwise: and doing well!

As always, if you're waiting for a review, or if you're stuck, please request help here OR leave a comment with @publiclab/mentors @publiclab/reviewers for some input or ask the community in our Gitter chatroom :raised_hands:

**Gitter**
Gitter is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up there for these updates or just to join the conversation :pager:.

**This Week's Theme**
As we all know this is the last week before the application deadline for mentoring organizations. After 6th of February we would have a clear idea of what ideas are submitted for this years GSOC. So, I think it would be good idea to start brainstorming about implementation of those ideas. Also, the number of new contributors coming to public labs is expected to increase, so we need to think about how can they contribute effectively and also how do they get the right guidance they would need to get started. 

cc
@mohitRJranjan @milaaraujo @kevinzluo
@stefannibrasil @gauravano @ViditChitkara @tech4GT @mridulnagpal @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab @ebarry @jywarren, @sagarpreet-chadha, @JonathanXu1, @uzorjchibuzor, @eli6, @ValentinaTironi, @rexagod, @sashadev-sky, @IshaGupta18, @dinaelhanan, @cesswairimu, @dependabot[bot], @oorjitchowdhary, @okonek, @wanzulfikri, @mohitRJranjan @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Rishabh570 @aSquare14 @Radhikadua123 @quinn-codes-synthesis @amychan331 @mardelvalle @narnt @hydro-m @love-opensource @romanrodriguez @shubhangi-chauhan @Dhiraj240 @geekychaser @codeIriss @CoderJolly @rishabhc32 @chirag-singhal @Saurabh19126848_twitter @IgorWilbert @dhruvgupta167 @vrk99 @pdurbin @dave-light @shubhscoder 

**Summer of Code**
@jywarren has started a brainstorming post for the ideas page for Summer of Code 2019 -It would be best get some ideas into discussion from the fellow community member before time. People have been brainstorming already - let's do it together!
https://publiclab.org/notes/warren/01-02-2019/brainstorming-for-summer-of-code-2019
Also this week the 6th Feb is the mentoring applications deadline to submit their ideas.  

**Software Contributors Survey**
This survey is conducted on a yearly basis to improve our experience.
https://goo.gl/forms/4VVMO8dOijRj6BUA3
The form will remain open until early March, but don't wait to respond!

**MapKnitter**
MapKnitter provides an interface to upload aerial images positioning them in the web over existing map data. Mapknitter is also maintained by the public lab community, So if you haven't taken a look at that repository then it's a good idea to check that out as well. We are looking for active contributors for Mapknitter as well!

Big projects planning in progress :construction_worker_man:  at Mapknitter, checkout - https://github.com/publiclab/mapknitter/issues/300 

**Leaflet.DistortableImage**
A Leaflet extension to distort images -- "rubbersheeting" -- for the MapKnitter.org (src) image georectification service by Public Lab. Leaflet.DistortableImage allows for perspectival distortions of images, client-side, using CSS3 transformations in the DOM.

>  @jywarren(via Gitter ):  Hi, all - i've opened a planning issue for Leaflet.DistortableImage, the Leaflet library that is the user interface for MapKnitter: publiclab/Leaflet.DistortableImage#126.
We're looking to get folks more involved over there, and there are a lot of interesting projects :-) it'll also likely be a big focus area for Summer of Code.

So, if you are looking to test your JavaScript skills or want to learn while solving issues, check out - https://github.com/publiclab/Leaflet.DistortableImage. Thanks!

People who did the check-ins
  Gaurav Sachdeva (@gauravano )
  Sidharth Bansal (@SidharthBansal )
  Cess (@cesswairimu )
  Harman Jolly (@CoderJolly )
  Rishabh Rawat (@Rishabh570 )
  Sasha Boginsky (@sashadev-sky)
  Rishabh Kr Bothra (@geekychaser)
  Shubham Sangamnerkar (@shubhscoder )
Have a great week everyone :tada: :fireworks: :balloon:

**Comment by shubhscoder** [comment]
I have not been active off late, but from this week I have no other priorities and thus would mainly focus on resolving previously claimed issues. Thank you so much!

**Comment by gauravano** [comment]
Nice check-in @shubhscoder! Thanks!

@shubhscoder please add link to the survey to make it easy for newcomers for finding it.

Whoever want to volunteer for next week's check-in, feel free to raise your :hand:. For next check-In, I have a fun theme in mind, so please contact me for theme if you haven't thought for one yet. 

**Checklist for this week**
- [ ] I have opened the [PR](https://github.com/publiclab/plots2/pull/4740) against my pending issue -  last week, this week, I will get it merged after testing.
- [ ] We would be integrating 8 new languages to publiclab.org under Translation project, preparation of single language file for each language has been done and we would be soon updating the language-menu in the footer with some changes
- [ ] Resolving installation issues with mapknitter by updating essential dependencies. 
- [ ] Going through Leaflet.DistortableImage

Thanks!

**Comment by sidntrivedi012** [comment]
Hi everyone, it feels great to contribute to such an awesome project with such noble goal. Last week, I created some issues one of which was to try to to improve the slider of Image Sequencer and as suggested by @jywarren and @gauravano , am currently working on [#142](https://github.com/publiclab/PublicLab.Editor/issues/142) of PublicLab.Editor and some old issues of Plotsbot. Will fully try to push code that will solve these issues.

**Comment by sashadev-sky** [comment]
Hi guys,

This week I would like to 
- learn the ins and outs of mapknitter and start contributing there
- look further into the logistics for switching to webpack (publiclab/PublicLab.Editor#227)
- contribute in the usual workflow

Thank you! Happy Monday!

**Comment by ViditChitkara** [comment]
Hello everyone, I am currently working on #4094 which is "merging answer and commenting interfaces" and eventually deprecating answers. This will make our system more unified and consistent with only a comments model. If anyone is interested in helping me out with it, is most welcome!
Thanks!

**Comment by jywarren** [comment]
Wow, so much going on!!! Hooray @gauravano on the news about 8 new languages!!! 🌏 🌍 🌎 🎉 

I love the idea of the diff view, @niravasher ! Perhaps it can also be useful in the https://github.com/publiclab/inline-markdown-editor project, where we hope people will be able to edit wiki documents inline, and view the changes they're proposing!

I tried helping out on the Ruby 2.4.4 MapKnitter issue here: https://github.com/publiclab/mapknitter/pull/320 and made progress but didn't finish. I think it needs to be run locally to further trace the bugs. 

For my part, I'm trying to coordinate some optimizations (with MUCH help from @milaaraujo and @spelgubbe - https://github.com/publiclab/plots2/issues/3472 and https://github.com/publiclab/plots2/issues/4670. There are a few different approaches -- we should try several -- but I'm especially interested in reducing the # of queries the typeahead autocompletion and search interfaces send -- limiting them to only after 3 characters or more are entered. I think this will do a lot to improve the responsiveness of the typeaheads. 

Typeahead optimization is a subtle and complex issue! If anyone is interested in learning a bit more about how JavaScript AJAX requests work, and how to work with them to create a smooth UI experience for people, we'd love some help!

Thanks, everyone! It's so great to hear from you all!

...and of course, great job opening this Check-in, @shubhscoder !!!

**Comment by jywarren** [comment]
Hi all, i'll try to put together a blog post on this soon, but i was able to build a Leaflet library around multispectral image processing as part of the [NASA AREN project](https://publiclab.org/aren): https://github.com/publiclab/multispectral that processes NDVI imagery in JavaScript, and another https://github.com/publiclab/leaflet-tile-filter which processes NDVI of image tiles in realtime. The demos are pretty cool. Just sharing this as it was a neat output of the Image Sequencer library!

![image](https://user-images.githubusercontent.com/24359/52306947-41927b80-2967-11e9-86e5-3b5c832d4d4b.png)

This is part of the push to expand the list of examples of real-world uses for Image Sequencer - a kind of gallery of examples: https://github.com/publiclab/image-sequencer/issues/707

GREAT WORK to everyone in the image sequencer community for pushing this library forward! It's so powerful! @publiclab/is-reviewers 🎉 👍 👍 😄

**Comment by SidharthBansal** [comment]
Awesome work Jeff

**Comment by jywarren** [comment]
I also wanted to alert @publiclab/is-reviewers that I just rebased and merged quite a few new features and fixes: https://github.com/publiclab/image-sequencer/pulse/weekly

I noticed we have a lot of pull requests open in both plots2 and image-sequencer. And we have a lot of first-timers-only issues still open (in progress) at our welcome page: https://code.publiclab.org#r=all

Let's make a resolution to try to prepare a lot more of these to be completed and merged! This will help clear our backlog, and get us prepared for new and bigger projects! We're a big community now... we're up to this! 🙌 🎉 🚀

**Comment by gauravano** [comment]
Anyone want to volunteer for opening next check-in?

**Comment by sidntrivedi012** [comment]
@gauravano Yes, I would like to.

**Comment by gauravano** [comment]
Great! Please open the check-in by Monday evening and you can refer this
link - https://github.com/publiclab/plots2/blob/master/doc/CHECKINS.md for
help. Also, do let me know if you have any questions or concerns about
choosing theme or anything. Thanks!

**Comment by gauravano** [comment]
New check-in open at #4784.
