### ISSUE TITLE
cannot post research note

### ISSUE THREAD

**Issue by dhaffnersr** [publiclab/plots2#476]
### What happened just before the problem occurred

When I clicked on the button for writing a research note it brings me to an error page stating if I have the right address, I made sure I was logged in so that wasn't a problem.
### Relevant URLs

https://publiclab.org/tag/spectrometer

### PublicLab.org/dhaffnersr

(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hi, Dave, thank you for reporting. Fix coming momentarily.

**Comment by jywarren** [comment]
Hi, Dave -  I believe it's resolved now. Thank you very much for reporting.

**Comment by dhaffnersr** [comment]
Thanks jeff
