### ISSUE TITLE
ability to go directly to `/subscribe/multiple/tag/tag1,tag2` and correctly enter and login

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4760]
Follow-up to #4739, we should make sure you can go directly to `/subscribe/multiple/tag/tag1,tag2` and correctly enter and login, and get subscribed to those two tags. 

It should be working:

https://github.com/publiclab/plots2/blob/5cde763bbdc3bfb9b91c26d68389285050b5ba8c/app/controllers/subscription_controller.rb#L178-L179

https://github.com/publiclab/plots2/blob/5cde763bbdc3bfb9b91c26d68389285050b5ba8c/app/controllers/user_sessions_controller.rb#L142

but it isn't on unstable. Let's debug this, potentially with an integration test?

**Comment by jywarren** [comment]
Confirming that when i go to `https://stable.publiclab.org/subscribe/multiple/tag/tag1,tag2` and log in with my username and password, I am redirected to:

https://stable.publiclab.org/home?return_to=/login

And see an error message: `You must be logged out to access this page`

**Comment by SidharthBansal** [comment]
You are referring to ONLY the stable branch?

**Comment by jywarren** [comment]
No, production too, but I linked there as a place to test it out. Thanks!

**Comment by SidharthBansal** [comment]
Thanks for the quick response. I am looking into it.

**Comment by SidharthBansal** [comment]
The login flow works well for the OAuth providers. There is some problem with the 
1. Login Form
2. SignUp form
3. Shifting between logging and signup should have retention of return_to params.

**Comment by jywarren** [comment]
If it helps to make a system test for this, perhaps we can narrow down the
issue one step at a time?

**Comment by SidharthBansal** [comment]
Sure, resolving (1) right now. Thanks

**Comment by SidharthBansal** [comment]
Solving #5521 first.

**Comment by SidharthBansal** [comment]
Ability to go directly to `/subscribe/multiple/tag/tag1,tag2` and correctly enter and login has 2 parts
1. Login based on Oauth - rectified in #5560 
2. Login based on login form - debugging it right now. Trying to open up a PR soon.
