### ISSUE TITLE
Expandable graphs

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#4765]
The new graph on stats page is quite awesome
![ref1](https://user-images.githubusercontent.com/17081074/52294208-b676ad00-2989-11e9-85b9-7ca0f7ab54e3.png)
But it only covers 52 weeks from the start date and we now have zoom buttons. If you zoom out of the 52 weeks the graph does not expand 
![ref2](https://user-images.githubusercontent.com/17081074/52294261-e45bf180-2989-11e9-8193-bdbe1c11a471.png)
It should be able to have a expand beyond the 52 weeks

https://github.com/publiclab/plots2/blob/75f2b453935476d24194c05c4dc55db0c27508cf/app/controllers/stats_controller.rb#L54-L56

Or restructure the `graph_making` method on models e.g
 https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L190-#L210

**Comment by jywarren** [comment]
Yes, let's try to refactor graph_making to accept begin and end date
parameters, then it'll be easier to merge the /stats/range pages with
/stats pages!

**Comment by cesswairimu** [comment]
Implemented the new contribution graph method on #4887
