### ISSUE TITLE
Display comments in per-tag stats graphs

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4770]
Related to https://github.com/publiclab/plots2/issues/4541, I think it would be great to be able to see how many comments have been made on all posts which bear a given tag, sort of to see how much "chatter" there's been in a topic area. We could stack this over the existing graphs in #4693, which is where this would be especially useful!

@cesswairimu what do you think?

**Comment by cesswairimu** [comment]
Sounds awesome @jywarren. Working on it thanks
