### ISSUE TITLE
Failure in sending welcome email

### ISSUE THREAD

**Issue by shubhscoder** [publiclab/plots2#4777]
I tried signing up with my emails and the welcome email fails in every case. Probably this is happening after merging #3992. But the tests run well and also it works perfectly well on the local machine. @jywarren  I think we will have to check the logs I guess to  figure out what is wrong. I think this should be fixed as soon as possible.

**Comment by gauravano** [comment]
Hey @shubhscoder, please provide more details, may be screenshots with steps. Thanks!

**Comment by shubhscoder** [comment]
Ok so in a normal scenario, this is supposed to happen :
1. You signup with a email id.
2. You get a flash message saying "We have sent you a welcome email".
3. You get a welcome email on the email id with which you signed up.

But the following is happening:
1. You signup with a email id.
2. You get a flash message saying "We tried sending you the email but failed. Anyways your account has been created".
3. You don't get any welcome email.
So this is a bug, which I am not sure why this is happening

**Comment by gauravano** [comment]
This happened in production?

Gaurav Sachdeva

**Comment by shubhscoder** [comment]
Yeah, this is happening in production! If I try sign up on the local
machine, it works perfectly fine.

**Comment by jywarren** [comment]
Oh, thank you for reporting. If you could send the emails you signed up
with to jeff@publiclab.org, i can check the logs for them and see if there
was a mailing error?

**Comment by jywarren** [comment]
Is it possible this overlapped with the mail issue in
https://github.com/publiclab/plots2/issues/4774#issuecomment-461646291 ?

**Comment by shubhscoder** [comment]
Yeah that is possible. I will try again if it is working after @icarito's
fix

**Comment by shubhscoder** [comment]
@jywarren it is working as of now. I think it was overlapping with #4774

**Comment by jywarren** [comment]
Great, thanks.

**Comment by gauravano** [comment]
@shubhscoder do you think we can close this issue? Also, your PR is merged in master and production builds from the `stable` branch (If I remember correctly). 

@jywarren left a note here for you - https://github.com/publiclab/plots2/pull/3992/files#r255240112. Thanks!

**Comment by shubhscoder** [comment]
Yeah we can close this @gauravano . I will surely check the note. Thank you so much !

**Comment by gauravano** [comment]
Great!
