### ISSUE TITLE
Weekly Community Check-In #9 - 'Debug to Develop'

### ISSUE THREAD

**Issue by sidntrivedi012** [publiclab/plots2#4784]
Hello everyone :wave: !

We all at Public Lab :balloon: - learn, grow, work, brainstorm ideas and contribute together. So why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so that we can support and collaborate with each other better. 

**The goal of our Community Check-In is for every community member to share something about their work from the past week and about their current week's goal** :dart: . 

* You are also welcome to share fun-fact :smile:, new ideas :bulb:, your learning goals :ballot_box_with_check:, your expectations from the community :blush: etc. 

* If you're new here, welcome :balloon: , and please comment a Hello message below, we love to work with you. If you're looking for new issues, please try some of our [first-timers-only issues](https://github.com/publiclab/plots2/issues?utf8=%E2%9C%93&q=first-timers-only).

We're SO EXCITED to have your help!

* Is there anything, you would like to share with us from past week's work? What is your plan for this week?

* If you have not planned yet, just leave a Hello! so that we know that you are in sync with us :arrows_clockwise: and doing well!

* As always, if you're waiting for a review, or if you're stuck, please request help here OR leave a comment with @publiclab/mentors @publiclab/reviewers for some input or ask the community in our Gitter chatroom raised_hands

**Communication Platform - Gitter**
Gitter is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up there for these updates or just to join the conversation pager.

**This Week's Theme**

It has been said - `If debugging is the process of removing software bugs, then programming must be the process of putting them in.` Thus, it is very hard for a single person to write bugless code and thus, develop a perfect software. To solve bugs, the software needs to be tested by a variety of users. That's where the community steps in. Thus, this week help the community grow towards perfection by solving various bugs that have been remained unsolved since a long time. Even solving a first-timer bug will make you learn a lot about the project and our vision.

**What Can I Do for Public Lab**

* If you are a beginner, try starting with -

1. Reading Documentation of the project you want to contribute to.
2. Talking on the chat platform about the project, it's tech- stack,it's goal etc. 
3. Setting up the project on your local machine.
4. Contributing to the community by making Pull Request of any bug you find in the Documentation.

* If you have got some idea about our project and searching which project matches your tech skills, we have got some really awesome projects -

| Skill           | Project |
|------------------------|------|
| HTML/ CSS          | Plots2, Community Toolbox, Image-Sequencer |
| Javascript             | Plots2, Image-Sequencer, PublicLab Editor, Community Toolbox, Leaflet.Distortable Image |
| Ruby on Rails       | Plots2, Mapknitter |
| Node.js                 | Plotsbot, Image-Sequencer|
| MATLAB/ Arduino | Webjack |

**An awesome article on the advent of Free Software Movement**

Some days ago, I came around with an [awesome article](https://kushaldas.in/pages/hacker-ethic-and-free-software-movement.html) on how and why the `FREE SOFTWARE MOVEMENT` actually started. Being in an open source community, we should know our roots and how this philosophy of Open Source Development and Contribution actually started. Thus, do give it a read.

**Software Contributors Survey**
This survey is conducted on a yearly basis to improve our experience.
https://goo.gl/forms/4VVMO8dOijRj6BUA3
The form will remain open until early March, but don't wait to respond!

**Leaflet.DistortableImage**
A Leaflet extension to distort images -- "rubbersheeting" -- for the MapKnitter.org (src) image georectification service by Public Lab. Leaflet.DistortableImage allows for perspectival distortions of images, client-side, using CSS3 transformations in the DOM.

> @jywarren(via Gitter ):  Hi, all - i've opened a planning issue for Leaflet.DistortableImage, the Leaflet library that is the user interface for MapKnitter: [publiclab/Leaflet.DistortableImage#126](https://github.com/publiclab/Leaflet.DistortableImage/issues/126).
> We're looking to get folks more involved over there, and there are a lot of interesting projects :-) it'll also likely be a big focus area for Summer of Code.

So, if you are looking to test your JavaScript skills or want to learn while solving issues, do check out - https://github.com/publiclab/Leaflet.DistortableImage. 
cc
@mohitRJranjan @milaaraujo @kevinzluo
@stefannibrasil @gauravano @ViditChitkara @tech4GT @mridulnagpal @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab @ebarry @jywarren, @sagarpreet-chadha, @JonathanXu1, @uzorjchibuzor, @eli6, @ValentinaTironi, @rexagod, @sashadev-sky, @IshaGupta18, @dinaelhanan, @cesswairimu, @dependabot[bot], @oorjitchowdhary, @okonek, @wanzulfikri, @mohitRJranjan @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Rishabh570 @aSquare14  @hydro-m @love-opensource @romanrodriguez  @Dhiraj240 @geekychaser @codeIriss @CoderJolly @rishabhc32 @chirag-singhal @Saurabh19126848_twitter @IgorWilbert @dhruvgupta167 @vrk99 @pdurbin @dave-light @shubhscoder @HarshKhandeparkar @aashna27 

Thanks and keep contributing! Contributing to Public Lab means contributing to the Environment . :palm_tree: :sun_with_face: :droplet: :balloon: 

People who did the check-ins-
  Gaurav Sachdeva (@gauravano )
  Sidharth Bansal (@SidharthBansal )
  Cess (@cesswairimu )
  Harman Jolly (@CoderJolly )
  Rishabh Rawat (@Rishabh570 )
  Sasha Boginsky (@sashadev-sky)
  Rishabh Kr Bothra (@geekychaser)
  Shubham Sangamnerkar (@shubhscoder)
  Siddhant N Trivedi(@sidntrivedi012) 
Have a great week everyone :tada: :fireworks: :balloon:

**Comment by gauravano** [comment]
Great check-in @sidntrivedi012 and nice theme :100:!

We have lots of bugs to handle at https://github.com/publiclab/mapknitter and https://github.com/publiclab/Leaflet.DistortableImage so jump-in if you want to help.

Our mapknitter project is showing some activity and now ready for your commits, thanks to @Dhiraj240 @sashadev-sky @SidharthBansal  @IshaGupta18 @rexagod who are contributing actively via PR, issues, discussions, etc. 

Thanks!

**Comment by ebarry** [comment]
What a great theme @sidntrivedi012 !
The week i'm supporting our Search User Interface contractor with whatever she might need, and will be available for discussing any features that need input from a Community Rep. Thanks!

**Comment by Souravirus** [comment]
Hey everyone, hope everyone is fine.
I am still working on the upgrade to bootstrap 4. It came to out to be a lot bigger project than I thought.  So, this week I will be working on it. 

Thank you!!

**Comment by CoderJolly** [comment]
> Hey everyone, hope everyone is fine.
> I am still working on the upgrade to bootstrap 4. It came to out to be a lot bigger project than I thought. So, this week I will be working on it.
> 
> Thank you!!

Which issue would dat be cause I would also like to help

**Comment by Souravirus** [comment]
Oh I am working on the pull request #3937.

**Comment by sashadev-sky** [comment]
@sidntrivedi012 awesome check in, thank you! I love what you did breaking up the projects by skills and sharing an article. 

This week I will be 
1) Mapping out my involvement in mapknitter
2) Forking all the repos connected to mapknitter and trying to solve at least one issue in them to learn the code. So far I have made a PR for leaflet.distortableImage 

I wanted to share what really helped me to start contributing to the distortableImage repo:
 I added to Gruntfile.js a **source maps** option, and then in Chrome I paused the code in different places and I identified what the different variables are and how they interacted with each other.  I'm sure a lot of people do this already but if you need help adding source maps to your Gruntfile let me know! Just make sure to remove it after you're done. 

Thanks everyone :)

**Comment by sashadev-sky** [comment]
Oh one more thing!! I am making setup instructions in mapknitter for macOS users. Is there anyone available who can help test run what I have so far and go through it with me and make changes???
I will probably open a specific issue about this tonight but please let me know here if you can help!

**Comment by niravasher** [comment]
I have been adding preview function in the Editor. That is done, just waiting for discussion with community-reps for accepting the frontend. Currently having some problems installing mapknitter on windows, and after installation will be working on adding a progress bar to an image upload

**Comment by ebarry** [comment]
Writing in to add that we are at the halfway mark of the Software Contributors Survey for 2019 -- We have 37 responses so far, and there are clearly many more people than that involved here! To all newcomers as well as those more familiar, please take a moment to fill it out, thanks all! https://github.com/publiclab/plots2/issues/4614

**Comment by ebarry** [comment]
Hi @sashadev-sky , i just noticed that you are in New York City. So are Bronwen and I, we work out of Brooklyn's Navy Yards. Please let me know if you'd like to come in and co-work nearby any day. 🎉 🌮

**Comment by CoderJolly** [comment]
> Oh one more thing!! I am making setup instructions in mapknitter for macOS users. Is there anyone available who can help test run what I have so far and go through it with me and make changes???
> I will probably open a specific issue about this tonight but please let me know here if you can help!

Sure, I hv MacOS

**Comment by cesswairimu** [comment]
Hello everyone :wave: 
This week I am finishing up on the follow up issues on the new graphs.
Next I will do tag-stats related tickets on milestone 20.
Great theme @sidntrivedi012 

Have a nice week ahead.

**Comment by Divy123** [comment]
Hello everyone !
This week I will be working on restructuring issue in image sequencer and try to help others in the community.
Sorry @tech4GT @jywarren I have not been able to do some good amount of work since two days as my laptop is under servicing due to some hardware issues.
It will get fixed by tomorrow and I will start the work as soon as possible.
Thanks!

**Comment by sashadev-sky** [comment]
@ebarry that would be great! I just sent the both of you an email about it :)

**Comment by sashadev-sky** [comment]
@CoderJolly thank you! I never opened the issue because I am waiting to find it out if we will update the mySQL version (most likely I think we will). Having multiple versions of mySQL on your system can create complications during setup so would you want to wait until after the update?

Unless you were already planning to start contributing this week then please let me know!

**Comment by jywarren** [comment]
Thanks, everyone! I agree, i love the breakdown by type in the table, @sidntrivedi012 -- great work!

Lots of exciting stuff going on. A neat one - we've demonstrated running a Sequencer inside a sequencer module, here: https://github.com/publiclab/image-sequencer/pull/764 which lets us create more complex image processing steps made up of combinations of others -- like, generating a colorbar, resizing it, and overlaying it on the previous image.

Now we're moving forward on making it easier to create these with a generator function - so that making these "meta modules" could be as simple as listing the sub-steps in a function. See: https://github.com/publiclab/image-sequencer/pull/765

As we move towards a demo of exporting MapKnitter maps using Image Sequencer (a fun cross-over between our projects!) this kind of refactoring will play an important role!

**Comment by CoderJolly** [comment]
> @CoderJolly thank you! I never opened the issue because I am waiting to find it out if we will update the mySQL version (most likely I think we will). Having multiple versions of mySQL on your system can create complications during setup so would you want to wait until after the update?
> 
> Unless you were already planning to start contributing this week then please let me know!

Sure, I am ready to wait. I will work on Bootstrap issue

**Comment by jywarren** [comment]
Hi, all - just chiming in to note that I've been going through @edieblu's UI design work bit by bit, and responding in more depth with some additional ideas on the Dashboard design and the People page design. You can chime in here if you have input!

https://publiclab.org/notes/edie_blues/12-13-2018/public-lab-dashboard-new-design-ideas#c21883

https://publiclab.org/notes/edie_blues/01-16-2019/what-do-you-think-about-this-design-for-the-people-page#c21875

**Comment by jywarren** [comment]
Hi @sashadev-sky -- yes, i think we should upgrade MySQL, and would be happy to accept a PR!

**Comment by sagarpreet-chadha** [comment]
Hey everyone,

I was traveling the previous week (first vacation in a long time 🏖 😄 ) , hence was not able to do much contributions . 
I plan to start my week by debugging : https://github.com/publiclab/plots2/issues/4722 
And then i will focus mainly on LBLD  🔍 🗺   !

Thank you !

**Comment by gauravano** [comment]
Anyone want to open next week's check-in?

**Comment by IshaGupta18** [comment]
Yes, I would love to!

**Comment by sidntrivedi012** [comment]
Thanks everyone for liking the theme. Cheers to debugging. :tada: :tada:

**Comment by gauravano** [comment]
Great @IshaGupta18! 
Please open the check-in by tomorrow evening and you can refer to https://github.com/publiclab/plots2/blob/master/doc/CHECKINS.md for help. Thanks!

**Comment by IshaGupta18** [comment]
Absolutely! Thanks a ton!

**Comment by IshaGupta18** [comment]
New Check-in #4844 :tada: !
