### ISSUE TITLE
New "active topics" page based on /tags

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#480]
### Problem

It's hard to see what the most active recent topics are on the site, overall. The https://publiclab.org/tags page is not well linked to and is only the tag count for all time, not just the past month or so. It's also not well optimized, and is slow. 
### Proposed solution

Let's make a page at https://publiclab.org/topics which is a little like a Github Pulse page: https://github.com/publiclab/plots2/pulse

It'd by default show the past month, but you could also select the past year, or a past year of activity, by tag count. This would have similar calls to the page currently at https://publiclab.org/tags ([controller code here](https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L6-L14)), but would be more optimized because it'd only be the past month at first page load. It should show overall activity for the past month in a graph, similarly to how it's shown in https://publiclab.org/tag/spectrometer. 

It'd also be great to show the most-used tags in a format like: 

> **7 users** posted **6 notes** and **23 wiki edits** about **spectrometer** in the past week

We could also switch to using [d3.js](http://d3js.org) for the graphs, which might be a nice way to put hover-over data into the graphs, perhaps using the [nvd3](http://nvd3.org/examples/) library to ease the d3 usage. 

Selection of timeframe could be in a right-aligned Bootstrap `btn-dropdown`, similarly to the Github Pulse example above.

**Comment by ebarry** [comment]
can this also be driven by which topical lists are active in the same timeframe?

**Comment by jywarren** [comment]
That's harder as the lists are a separate system from our site, and we
don't have tag data on the lists. But potentially we could pull the monthly
RSS feed and somehow use that, as we're doing on the new Dashboard.

**Comment by ebarry** [comment]
Bumping this up as it connects to the current discussion on how to see community activity

**Comment by jywarren** [comment]
This is a pretty big project. Can we think about how to come up with some capacity and a timeline to tackle it?

**Comment by ebarry** [comment]
I don't necessarily want to do this project, but just wanted to bring past ideas like this together when talking about creating something new like a board for "requests for help" of presenting what "supporting tasks" need doing to people looking to contribute. 

In fact, if our other systems for helping route people into and through Public Lab have superseded this particular idea, let's close it.

**Comment by jywarren** [comment]
I think we've put a lot of time into https://publiclab.org/methods which is now looking pretty good! 

![screen shot 2017-07-05 at 4 34 08 pm](https://user-images.githubusercontent.com/24359/27883787-cbbaa166-619f-11e7-909f-1083b4115e3e.png)

This is sorted due to most recent update, so our immediate needs are somewhat met there. 

Also https://publiclab.org/stats is far more powerful now than when this issue was written. That's also good to take into account. 

But I think we could keep this open in particular if people are ever interested in doing data viz work on PL data (something I've seen come up before) -- this would be an **excellent** place for that to live.

**Comment by ebarry** [comment]
i believe that the original issue about active topics has been addressed by https://github.com/publiclab/plots2/issues/1677 in the dashboard.
