### ISSUE TITLE
Make moderate buttons to appear on the same line

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#4820]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: 

The moderate buttons **Approve** and **Spam** appear on comments and notes listing on the dashboard only visible to the moderators and admin. 

![moderation_view](https://user-images.githubusercontent.com/20878070/52784623-bd817780-307b-11e9-9037-37f3eb7d76f8.png)

These butttons appear on same line as **Moderate first time comment** for comment but for note, the buttons are shown in next line. Let's shift them on the same line by updating file https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_node_moderate.html.erb

Also, attach the screenshot of the updated view by creating a post as a user and then login as a moderator on localhost for clicking the screenshot. 

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by gauravano** [comment]
This issue is created for @ctam853. Thanks!

**Comment by ctam853** [comment]
Thank you for your help @gauravano. I'll claim this issue.

**Comment by gauravano** [comment]
Great @ctam853!

**Comment by Nirvikalpa108** [comment]
Hi @ctam853 are you working on this? If so, shall we attempt it together?

**Comment by sweezy793** [comment]
Is this issue still open ?

**Comment by gauravano** [comment]
Yes, it's available to claim.

**Comment by manansingh96** [comment]
I want to claim it. I have the fix. Can create PR instantly.

**Comment by jywarren** [comment]
Please go ahead!

**Comment by manansingh96** [comment]
@jywarren Created the PR. #4912

**Comment by jywarren** [comment]
Hi @Nirvikalpa108 I noticed you didn't get a response back and if you'd still like at first-timers-only issue, i'm happy to make a new one for you and reserve it. Thank you!

**Comment by Nirvikalpa108** [comment]
Hi @jywarren that would be amazing, thank you!

**Comment by rexagod** [comment]
Hi @Nirvikalpa108! Sorry for any delay, please have a look over this `fto-candidate` [here](https://github.com/publiclab/plots2/issues/4117) and let us know if we can be of any help!

Thanks!!

**Comment by CoderJolly** [comment]
@Nirvikalpa108 Jst ping when you are able to select a first-timer issue and ready to contribute to it!!

**Comment by jywarren** [comment]
Thank you everyone!!! I actually checked out #4117 and i think maybe we need a new one, sorry! So I went ahead and turned an fto-candidate into a new first-timers-only issue here: https://github.com/publiclab/plots2/issues/3480
