### ISSUE TITLE
Refactoring daily vs weekly subject title in Email Digests

### ISSUE THREAD

**Issue by IshaGupta18** [publiclab/plots2#4822]
Okay so I am trying to do this, but I think that it is probably hard coded somewhere, and a variable for checking which type of digest is not being sent to the actions:

Like here, in the mailer code:
https://github.com/publiclab/plots2/blob/d3b122efaa42a9d6b06a70f53626334ad2cf085b/app/mailers/subscription_mailer.rb#L58

Here in the send_digest_email function, top picks are being selected for a week only:
https://github.com/publiclab/plots2/blob/d3b122efaa42a9d6b06a70f53626334ad2cf085b/app/models/user.rb#L325-L330

I think here, when send_digest_email function is being called, the frequency parameter should be passed somehow, and received everywhere, then we can correct the code in the send_digest.html.erb:

https://github.com/publiclab/plots2/blob/d3b122efaa42a9d6b06a70f53626334ad2cf085b/app/jobs/digest_mail_job.rb#L4-L14

**Comment by jywarren** [comment]
I think you're' right that ` def send_digest_email ` in user.rb is only set up for weekly! 

I think we could add a line to it which looks up whether that user should get a week's worth or a day's worth of content. It could be based on the code in https://github.com/publiclab/plots2/blob/7e20e413e94925a4f021f14e61a36b7ebb270e25/app/jobs/digest_mail_job.rb

You could simply use:

```ruby
if self.has_tag('digest:daily') # self is an instance of user
  # set time period to 1.day
elsif self.has_tag('digest:weekly') # self is an instance of user
  # set time period to 1.day
end
```

**Comment by jywarren** [comment]
And you're right - we could change the parameters of this function to be able to pass in the type "weekly" or "daily" as a string, and use that to set the subject appropriately!

https://github.com/publiclab/plots2/blob/d3b122efaa42a9d6b06a70f53626334ad2cf085b/app/mailers/subscription_mailer.rb#L57-L58

**Comment by IshaGupta18** [comment]
Absolutely, I think with this we'll be good to go, I'll start with it ASAP!

**Comment by IshaGupta18** [comment]
#4955 is my PR for this. @jywarren kindly review and let me know what else can be done! Thanks a lot!
