### ISSUE TITLE
Not redirecting to profile when clicking

### ISSUE THREAD

**Issue by arungoel123456** [publiclab/plots2#4825]
In the mobile view ,  even after clicking the profile button , we are not redirected to the profile .
here are some ss.
![1](https://user-images.githubusercontent.com/31837154/52811097-47503580-30ba-11e9-8a16-b20ae5f08d0b.png)
![2](https://user-images.githubusercontent.com/31837154/52811104-49b28f80-30ba-11e9-9854-82d18c320305.png)
![3](https://user-images.githubusercontent.com/31837154/52811106-4b7c5300-30ba-11e9-9a4a-d68ebff88846.png)

**Comment by arungoel123456** [comment]
Third picture shows what happens when we click on the profile button

**Comment by gauravano** [comment]
Hi @arungoel123456, the clicking on **Profile** item expands the nav further and from there if you click on the Profile option, you'll be redirected to your profile page. Try Profile button both at full-screen and mobile-view and you'll get to know, what I mean. Thanks!

**Comment by IshaGupta18** [comment]
Yes @arungoel123456 ! You will have to scroll down into the navbar dropdown to see the remaining options when you click on the `Profile` button, have a look at this:

![image](https://user-images.githubusercontent.com/40794215/52911875-de420b00-32cf-11e9-85a7-622751bc2fab.png)

**Comment by gauravano** [comment]
I think this issue can be closed for now. thanks!
