### ISSUE TITLE
some pages need a clear cache or /?t=random to load properly

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#487]
### What happened just before the problem occurred

I went to https://publiclab.org/profile/Bronwen and (as an admin) clicked "Make moderator" -- which triggers https://github.com/publiclab/plots2/blob/master/app/controllers/admin_controller.rb#L17

But I didn't initially see the green `flash[:notice]` message at the top of the page confirming that Bronwen was made a moderator. I refreshed the page and then saw the notice.

The page is being cached in the browser cache. We should append a `?t=111` to the URL redirect in that action (and for admin role too) where 111 is a random number or timestamp, so that the page refreshes and doesn't rely on browser cache.

The same issue is true of re-publishing moderated revisions at https://publiclab.org/wiki/revisions/moderation (moderator or admin status required to see) -- the revision is republished, but it takes an extra pageload to display. 

There may also be a way to send a clear cache header?

**Comment by ananyo2012** [comment]
@jywarren Hope this can be closed now?

**Comment by jywarren** [comment]
Yes. Let's re-open if we see this recur on other pages we missed. Thanks!
