### ISSUE TITLE
CSS breaking in multiple subscription button

### ISSUE THREAD

**Issue by IshaGupta18** [publiclab/plots2#4874]
Content is not being displayed in the popover and the button styling of the Subscribe+ button has disappeared as well, however, the code is fine I believe because it's the same code that was working perfectly some time ago. I feel that this could be happening because of the changes in the Bootstrap version.
![image](https://user-images.githubusercontent.com/40794215/53281697-1d021600-3753-11e9-849a-7b9e9e708d48.png)

Please look into it if it's because of the Bootstrap version. Thanks a lot!

**Comment by Chrisyee22** [comment]
Hello. Could I work on this issue?

**Comment by IshaGupta18** [comment]
Sure, could you please look into what's actually creating this problem, I would suggest you look into Bootstrap 4's documentation and the updates going on in our repo. Thanks a lot!

**Comment by gauravano** [comment]
We are still riding on Bootstrap3 as the upgrade PR https://github.com/publiclab/plots2/pull/3937 hasn't been merged yet. So, some other problem maybe.

**Comment by swiatek7** [comment]
Hi @Chrisyee22 
Are you working on this issue? Any update?

**Comment by Chrisyee22** [comment]
Hi @swiatek7. Yeah I’m working on it at the moment.

**Comment by IshaGupta18** [comment]
Yes, @Chrisyee22 please keep us posted!

**Comment by Chrisyee22** [comment]
It looks like the button is missing the popover syntax. Has there been a change to it since you mentioned it worked before but no longer does?

**Comment by Chrisyee22** [comment]
Hi @IshaGupta18. The subscribe + button doesn't show up when running the project locally. Am I missing something or doing something incorrectly?

**Comment by IshaGupta18** [comment]
It should come up, is your fork synced? 
here is the button:
![image](https://user-images.githubusercontent.com/40794215/53466086-6fef0c80-3a76-11e9-830c-24a67bdfdea1.png)

**Comment by Chrisyee22** [comment]
I checked my version and it is up to date. I'm not sure why I'm not getting that button. Here's what my screen looks like. 
<img width="1181" alt="screen shot public lab" src="https://user-images.githubusercontent.com/24218722/53477230-18767f80-3a29-11e9-8548-d291a8482097.png">

**Comment by Chrisyee22** [comment]
Ignore that last post. I have the button showing up.

**Comment by jywarren** [comment]
awesome!
