### ISSUE TITLE
Moderate first time posters for spam

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#488]
### The problem

Spam users get their notes sent out to a few dozen people subscribed to "all research notes" -- even if they're caught in the first hour or so. 

### Proposed fix

* [x] user.first_time_poster
* [x] post form notice of moderation with link to moderators
* [x] first time poster posts set to status = 4
* [ ] consider new category of "banned" or something that's not displayed, but not advertising spam
* [x] displayed only to author & moderators in red in list view
* [x] displayed only to author & moderators in red in full view
* [x] notice shown on publish to first time posters, with link to moderators
* [x] emails sent to moderators
* [x] approval switches status to 1
* [x] prompt to encourage
* [x] email sent to author "approved"
* [x] email sent to moderators "approved" in same thread (#490)
* [x] spam emails spammed as usual
* [x] OR notifications sent to all-notes-followers as usual

Notices appearance:

![screenshot 2016-04-18 at 11 38 16 am](https://cloud.githubusercontent.com/assets/24359/14610181/cf625892-055a-11e6-9f01-35a51ec5aaa3.png)

**Comment by franktank** [comment]
Will the post be created before the 30 minutes are over? We could check to see number of posts from the user and if it is 0, we can use [http://apidock.com/ruby/Kernel/sleep](url) to delay it from posting until the 30 minutes are up.

**Comment by jywarren** [comment]
I think that leaves the thread hanging open, but I have some resources on
scheduling with rails, and am going to try this today. My main concern is
how we test this, so I'm thinking of how we might set the timing to zero
for test mode, or other ways to remove asynchronicity during testing.
On Apr 7, 2016 8:39 PM, "Franky Liang" <notifications@github.com> wrote:

Will the post be created before the 30 minutes are over? We could check to
see number of posts from the user and if it is 0, we can use
http://apidock.com/ruby/Kernel/sleep <http://url> to delay it from posting
until the 30 minutes are up.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/publiclab/plots2/issues/488#issuecomment-207149651>

**Comment by jywarren** [comment]
Hi, @icarito - I think this is going to require the `whenever` gem for cron jobs. There's a note for RVM users: https://github.com/javan/whenever#rvm-integration Can you look into this on our setup? Thanks!

**Comment by icarito** [comment]
I've just added the proposed variable `rvm_trust_rvmrcs_flag=1`  to `~plots/.rvmrc` hopefully it will work at once ping me in any case I can help to check that it is working.

**Comment by jywarren** [comment]
Thanks!

**Comment by jywarren** [comment]
We're moving ahead on moderation without a 30 minute delay, for the time being. Changing title accordingly -- posts will be held indefinitely and we'll re-assess in a few weeks to make sure this works.

**Comment by jywarren** [comment]
Looking good though a bit ugly:

![screenshot 2016-04-22 at 6 59 51 pm](https://cloud.githubusercontent.com/assets/24359/14756913/6f0b379c-08bc-11e6-9ff7-00da0597a21b.png)
![screenshot 2016-04-22 at 6 58 54 pm](https://cloud.githubusercontent.com/assets/24359/14756914/6f14d108-08bc-11e6-8f21-d7dd1b3283bc.png)

**Comment by icarito** [comment]
Nice!

**Comment by jywarren** [comment]
made much prettier/more compact/mobile-friendly, last few bugfixes and merged!
