### ISSUE TITLE
Summer of Code Call for proposals - Outreachy and GSoC

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4892]
We're part of two different summer fellowship programs this year, Outreachy Summer and Google Summer of Code (#GSoC) -- which recruit software contributors to work on open source projects. Read more and post a proposal for comment here:

https://publiclab.org/notes/warren/01-02-2019/brainstorming-for-summer-of-code-2019

A few tips for making awesome proposals:
* Please [submit the proposals at publiclab.org](https://publiclab.org/notes/warren/10-23-2018/call-for-outreachy-2018-19-proposals) first. After all the reviews you can submit it on the official website.
* Your information so that we can know you better (not mandatory !).
* Include weekly timeline: Explain what you will be doing in which week. Divide the period into months in bigger tasks. Then into weeks into smaller tasks.
* Include demos/images/gifs to demonstrate your idea
* Include Mock-Ups, Flow Charts, Data Flow Diagrams, etc to explain the workflow in simple language. So that people in the logistics department can review your work and suggest changes.
* PRs merged & Issues reported: This is the most crucial aspect of any application. We want people to be well versed with our system. Please mention all the issues reported, PR merged, suggestions etc in the proposal.
* Start early and have many revisions of the proposal to increase your chances.

These tips are general tips.
Are you tensed? No need to worry!!! :smile: We all are there to help you at each stage of proposing the proposal to the manufacturing of the end product. So just be happy and code.

Best of luck folks. :tada: Hope we will have a great time this year with you all. :+1: 
Here's the one for this last year's program! :1st_place_medal: :1234: :100: 
https://publiclab.org/notes/warren/02-15-2018/call-for-summer-of-code-2018-proposals

 Thanks and more soon! :smile: :tada: 

We are participating in Summer Outreachy for the first time. Hoping you all will have awesome experience!!! We included Summer Outreachy so that we can have better gender equality at PL. We respect all color, creed, race, age group and gender equality. :1st_place_medal: 

### Outreachy Projects

**1. PublicLab.org UI improvements**: https://www.outreachy.org/may-2019-august-2019-outreachy-internships/communities/public-lab/#publiclaborg-ui-improvements

GitHub issue: https://github.com/publiclab/plots2/issues/4922

**2. Extend Leaflet Environmental Layers with new layer menu and layer addition workflow**: 
 https://www.outreachy.org/may-2019-august-2019-outreachy-internships/communities/public-lab/#extend-leaflet-environmental-layers-with-new-layer

GitHub issue: https://github.com/publiclab/leaflet-environmental-layers/issues/134

### CALL FOR OUTREACHY PROPOSALS

We've posted a call for proposals here, where we'd like to ask each of you to open a draft proposal and get some comments on it! Thank you!!

https://publiclab.org/notes/gauravano/03-12-2019/call-for-outreachy-2019-proposals

We especially welcome proposals from people from groups under-represented in free and open source software!

As always, our community aspires to be a respectful place. Please read and abide by our [Code of Conduct](https://publiclab.org/conduct).

You can also ask questions on that post, at the bottom. Thanks, everybody and eager to see your proposals!

**Comment by SidharthBansal** [comment]
:-) welcome one more time!

Also @publiclab/soc folks who've participated before, we'd love to hear from you again, even just to say hi!

**Comment by SidharthBansal** [comment]
@publiclab/reviewers @publiclab/is-reviewers @publiclab/plots2-reviewers

**Comment by SidharthBansal** [comment]
We are really looking for interactive folks. So, whenever you create your proposal please mention it here so that folks can comment on your proposal and we can have brainstorming sessions.

**Comment by jywarren** [comment]
Hi, all! Thanks so much for posting this @SidharthBansal !

A couple notes: first, we haven't been accepted for RGSoC but will be applying for sure!

Second, I'll be posting a full guide to submitting proposals soon - probably today or tomorrow -- but until then you can use this link to start off on the template, and it'll be listed in the final posting I do:

https://publiclab.org/post?n=899&title=SoC%20proposal:%20&tags=software,gsoc,gsoc-2018,rgsoc-2018,soc,soc-2018,soc-2018-proposals

Please indicate if you're doing an Outreachy or GSoC proposal!

**Comment by jywarren** [comment]
OK, I've posted the official guide to posting proposals -- here you go! And there's a button for posting a proposal on that page: 

https://publiclab.org/notes/warren/02-28-2019/call-for-summer-of-code-2019-proposals

**Comment by gauravano** [comment]
@SidharthBansal I have removed the RGSoC mention from the issue body too for now, just to ensure no contributor get confused. We can add that after officially hearing about our participation.

**Comment by Rishabh570** [comment]
Hi @SidharthBansal, I've created a [draft](https://publiclab.org/notes/icode365/03-02-2019/soc-proposal?_=1551529669) regarding my GSOC proposal but the things I'll work on are not finalized & approved yet, that's why I've left some sections blank for now. Can you please take a look?
Thanks!!!

**Comment by SidharthBansal** [comment]
@jywarren may i know the project for the outreachy application? Outreachy website does not list the project idea.

**Comment by SidharthBansal** [comment]
There are some people who can apply in both of the programs like @IshaGupta18 
You all can read https://www.outreachy.org/apply/gsoc/ and decide whichever fellowship you are going to get enrolled in.
Thanks

**Comment by alaxalves** [comment]
Hello to the entire PublicLab team, I'm Álax Alves, a student from Brazil, I have just took notice of Public Lab through GSoC 2019 program. I have recently started to contribute with Public Lab's Mapknitter (https://github.com/publiclab/mapknitter/pull/363). I have great interest in working on the Mapknitter Rails upgrade, since I have experience in those types of migrations (https://gitlab.com/noosfero/noosfero/merge_requests/1438/diffs). I think I could be of great value to the Public Lab team. Along with that migration I plan on making improvements to the entire docker environments, CI configuration.

**Comment by jywarren** [comment]
Welcome, Álax! And welcome everyone!

****

Hi, all - just posting an update here; we've posted the Outreachy project for this summer here: https://www.outreachy.org/may-2019-august-2019-outreachy-internships/communities/public-lab/#publiclaborg-ui-improvements -- you'll need to log in to see the whole proposal.

**Comment by SidharthBansal** [comment]
Three more optional suggestions:
If you were a GCI mentor please mention it in your proposal. We will give extra credit to these long term collaborators.
Second, it will be great to have a conference or seminar at your university about Public Lab and the programs which are held here. It is optional. No compulsion at all.
Thirdly, help each other in writing their proposals by giving suggestions under the proposals

**Comment by Julius26** [comment]
Hello..If I publish a draft on public lab I should do the same on Gsoc website as well?

**Comment by jywarren** [comment]
you can, sure! Or you can wait until the deadline -- just don't miss it!

**Comment by SidharthBansal** [comment]
Best of luck all of you for the results. Closing this issue now.
