### ISSUE TITLE
Preserve `return_to` param when switching from /login to /signup

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4893]
Related to #4759: Note that when going to: 

`https://stable.publiclab.org/subscribe/multiple/tag/arduino,games`, you then get redirected to: 

`https://stable.publiclab.org/login?return_to=/subscribe/multiple/tag/arduino,games`

However, if you then click "Sign up" you then just see `https://stable.publiclab.org/signup`. Let's do a follow-up issue to ensure that if you click Sign up, it preserves the `return_to` parameter!

We'd love help with this!

**Comment by SidharthBansal** [comment]
Hi, I am willing to do it. Just noting whether this behaviour is present for all the routes or specific to the /subscribe/multiple/tag/tag_list?
Whether this error is only present on the stable branch or on all branches?

**Comment by jywarren** [comment]
Hi! All branches and I'm not sure but I would imagine all routes? Thanks!!

**Comment by SidharthBansal** [comment]
It is present for all the routes.

**Comment by SidharthBansal** [comment]
Also present on all the branches as we have observed this error for the first time and code is missing.
