### ISSUE TITLE
Return_to anomaly

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4898]
![image](https://user-images.githubusercontent.com/20972099/53639538-84d2c800-3c4f-11e9-8242-ff59860045f4.png)
Can you see the url and the link to join to even though the user is logged in?
Rails is working as it should but from users point of view there is an error.

**Comment by gauravano** [comment]
Hey @SidharthBansal, isn't this issue same as #4893?

**Comment by SidharthBansal** [comment]
No. I don't think so.

**Comment by gauravano** [comment]
Oops, I got confused.

**Comment by Anjalizi** [comment]
Hi @SidharthBansal ,
I would like to help with this, so that I can get started with this project. I would like to be assigned to this issue and would love to solve it.
I am new to this project, so can you please point me to the file that I need to change or look for. 😅 
Thanks a lot 😃

**Comment by gauravano** [comment]
hey @Anjalizi, we would love to have your help.

So, what's happening is:
If we login via modal then all goes fine but if we login via /login page then we are shown this alert - 
![Screenshot from 2019-03-09 19-49-54](https://user-images.githubusercontent.com/20878070/54072710-91d16600-42a4-11e9-9578-c9573be88c57.png) as return_to tries to take us to /login page again after logging in. 

So, we can solve this by redirecting to dashboard if return_to is "/login". Here's the code you need to work with https://github.com/publiclab/plots2/blob/master/app/controllers/user_sessions_controller.rb#L132-L144

Let us know, if you need any help. Thanks!

**Comment by Anjalizi** [comment]
thank you. i shall look into this.
