### ISSUE TITLE
Mailers for login project at MK

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4899]
Copying from https://github.com/publiclab/mapknitter/issues/366
I think we need to notify the user through email about access grant of MK from plots2. This all companies do. Whenever I first authorize any application through facebook, then facebook messages me about the authorization.
@jywarren should we make them?
Feel free to close this issue if you think we don't need it.

**Comment by jywarren** [comment]
Let's hold off for a moment -- if we decide to automate approval of OpenID
from MapKnitter to PL.org, we could skip it.

**Comment by SidharthBansal** [comment]
I think we should give one email to the user. Consider someones logs in MK through someone else account. This should be notified.
Hence there should also be capability to delink applications from plots2.

**Comment by jywarren** [comment]
If we whitelist only MK, SpectralWorkbench, and MapMill, the risk is very
low. let's think on this a bit before making a decision!

**Comment by SidharthBansal** [comment]
Yeah risks are too low for the corner cases which pop up in my mind. Haha

**Comment by SidharthBansal** [comment]
As per Jeff's suggestion in mk 301 issue, we will be automating the process. Hence we will not require mails.
