### ISSUE TITLE
Tracking errors in production

### ISSUE THREAD

**Issue by siaw23** [publiclab/plots2#4903]
As far as I can see we don't have any means to track errors on production. Some users will report errors here, most won't but we can automate these reports. I think error tracking is necessary. What do you guys think?

I'd like to suggest [Rollbar](https://rollbar.com/). They have a free plan that we can use.

So from time to time we'd look in Rollbar and fix any error that occurs in production.

**Comment by siaw23** [comment]
@publiclab/reviewers @jywarren I think this is a good idea what do you think?

**Comment by shubhscoder** [comment]
@siaw23 , how about sentry?

**Comment by shubhscoder** [comment]
We can actually apply for a free account on sentry!

**Comment by siaw23** [comment]
Sentry is actually a better option IMO. I checked and didn't find anything free or how many reports they'll give for free so if we can apply for a free account then great! I like Sentry. Good choice @shubhscoder

**Comment by shubhscoder** [comment]
Thank you @siaw23. We can apply for a free account here https://sentry.io/for/open-source/ . I think @jywarren will have to signup on the behalf of public labs. Thank you!

**Comment by icarito** [comment]
I've been looking for a solution like this for a while.
I'm happy to go with whichever you find more useful, my preference being something we could conceivably self host in the future (with a libre license). Once we've signed up I can look at deploying it!

**Comment by jywarren** [comment]
Oh this is cool, i wasn't aware of services like this! ❤️ 

Any pros/cons between Sentry and Rollbar?

**Comment by siaw23** [comment]
Pros for Sentry is better UI and more accurate error reporting, Rollbar has worse UI, error reporting, line number are off often as far as I know...

**Comment by jywarren** [comment]
Opened https://github.com/publiclab/plots2/pull/4944

**Comment by jywarren** [comment]
Searching for open source program opt-in... https://sentry.io/settings/public-lab/

**Comment by jywarren** [comment]
And applied to their program!

**Comment by jywarren** [comment]
OK, i think this will start running when a) we're approved and b) we push #4944 to production.

**Comment by siaw23** [comment]
Not sure about the free option. You got any idea when they'll approve?
