### ISSUE TITLE
Automate OpenId Request by whitelisting PL apps

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4914]
As per @jywarren s suggestion in 301 of MK issue we need to automate the process of authentication at MK by eliminating the gateway page. As MK is white listed users can always give permission to the app.
I was inspecting code of MK, and found that https://github.com/publiclab/mapknitter/issues/368 needs to be solved at plots2 repo instead of MK repository.

**Comment by SidharthBansal** [comment]
I am starting with this issue. As soon the gateway page is removed, we will have much simpler flow to think about.
Trying to install the plots2, SWB and MK and checking the flow on localhost:3000 how it goes.

**Comment by jywarren** [comment]
this is great. Yes, you can repoint a local copy of MK towards
localhost:3001 and replicate the forwarding and such.

**Comment by SidharthBansal** [comment]
At the time when you created mk and linked it to plots2 have you checked the authentication system at local host somehow? Or was it done on the production branch directly?

**Comment by SidharthBansal** [comment]
SWB installed. Installing plots2 and MK. Hope MK errors will be solved soon.
