### ISSUE TITLE
Improve the alert message

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#4915]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: 

Change the alert text to 
`You have successfully signed in. Please change your password using the link sent to you via e-mail.`

here - https://github.com/publiclab/plots2/blob/master/app/controllers/user_sessions_controller.rb#L70
Also, attach the screenshot of the updated view, if possible. 

You are also required to fix the errors by modifying the alert text in the tests. Please refer https://github.com/publiclab/plots2/pull/3489/files for that or feel free to ask.  

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by deepesh-ludhyani** [comment]
Hello, I'd like to work on this issue.

**Comment by gauravano** [comment]
Hey @deepesh-ludhyani, go ahead :+1:

**Comment by uimarshall** [comment]
Hi. i will like to work on this issue

**Comment by karunagoyalk** [comment]
Hey @gauravano!
Can I work on this issue?

**Comment by gauravano** [comment]
Hi @uimarshall and @karunagoyalk, @deepesh-ludhyani has already claimed the issue so let's give them some time to complete it. We would love to have help from both of you, you can find more issues at https://code.publiclab.org/#r=all. If you don't find any issue there, feel free to comment here or in Gitter channel- https://gitter.im/publiclab/publiclab, me or someone else will open the new FTO for you. Thanks!

@deepesh-ludhyani have you opened any PR, also in case, you need help feel free to ask.

**Comment by deepesh-ludhyani** [comment]
@gauravano Yes, I will soon open a PR for it, thankyou!

**Comment by shreyateeza** [comment]
@deepesh-ludhyani If not done, can I work on this issue?

**Comment by deepesh-ludhyani** [comment]
Yes, sure! Actually I am facing some problems solving it, you can go ahead.

**Comment by shreyateeza** [comment]
@gauravano Please assign this issue to me.

**Comment by gauravano** [comment]
@shreyateeza you can work on this as @deepesh-ludhyani isn't interested anymore.  

@deepesh-ludhyani we're happy to find you a new issue for you if you're interested.

@karunagoyalk we can create an FTO for you if you are still finding one? Feel free to ask. 

Thanks all!

**Comment by karunagoyalk** [comment]
@gauravano please help me! Because as I checked all issues, somebody is working on everything

**Comment by gauravano** [comment]
@karunagoyalk will ping you shortly with an FTO. Thanks!
