### ISSUE TITLE
Refining /stats preset ranges  routes

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#4916]
### Where to look

https://github.com/publiclab/plots2/blob/master/app/views/stats/index.html.erb#L16-L19
Right now on selecting an option the url is `/stats?options=` which is defined in this line https://github.com/publiclab/plots2/blob/master/app/controllers/stats_controller.rb#L12

### Change to be made
On post the url should be `/stats?start=&end=`

**Comment by thefifthisa** [comment]
Hi, I'm new here and would like to work on this!

**Comment by cesswairimu** [comment]
Hi @thefifthisa, awesome go ahead. Feel free to ask for help here if you are stuck.

**Comment by thefifthisa** [comment]
Thanks @cesswairimu! To clarify, will I need to create the `post` method? I only see `get` here.

**Comment by cesswairimu** [comment]
@thefifthisa oh yeah I see..I guess it has always been a `get`. I believe adding a `post` is not necessary. We want the `filter period` dropdown to be using the same params as we used in the date selector. That is start and end..
![stats](https://user-images.githubusercontent.com/17081074/54014052-580d3c00-418c-11e9-9e62-6c83b116a82d.gif)
This will mean explicitly defining start and end...`end` will be `Time.now` for all the options and `start` will be `Time.now -1.month` for month and so on..also another way would be to make the select options urls go for example `past week` will have the the link `/stats?start=<%= Time.now - 1.week %> &end=<%=Time.now%>` not sure if making the the options url is possible yet

**Comment by ananyaarun** [comment]
@thefifthisa R u still working on this ? Else I'd love to take this up. Thanks :)

**Comment by StlMaris123** [comment]
![Screenshot from 2019-09-16 17-59-42](https://user-images.githubusercontent.com/13062617/64969188-1c2a0080-d8ac-11e9-8858-c2ee3e6d425b.png)

**Comment by cesswairimu** [comment]
This was fix. closing it. Thanks all
