### ISSUE TITLE
Weekly Community Check-In #12 - "Be a reviewer!"

### ISSUE THREAD

**Issue by Harshithpabbati** [publiclab/plots2#4917]
Hi everyone!!!

We all at Public Lab  :balloon:  - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. The goal of our Community Check-In is for every community member to share something about their work from the past week and about their current week's goal :dart: . You are also welcome to share fun-fact :smile: , new ideas  :bulb: , your learning goals :ballot_box_with_check: .

If you're new here, welcome :balloon:, and please comment a Hello message below, we love to work with you. If you're looking for new issues, please try some of our first-timers-only issues.

We're SO EXCITED to have your help!

Is there anything, you would like to share with us from last week's work? What is your plan for this week?

If you have not planned yet, just leave a Hello! so that we know that you are in sync with us :arrows_clockwise: and doing well!

As always, if you're waiting for a review, or if you're stuck, you can request help here, leave a comment on your issue with @publiclab/reviewers mentioned, or ask the community in our Gitter chatroom :open_hands: .

### Poll this week

Public Lab is having a quick poll this week for its open source contributors to see what database systems all of you use! Please respond here: [https://github.com/publiclab/plots2/issues/4919](https://github.com/publiclab/plots2/issues/4919)

### Gitter
Gitter is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up there for these updates or just to join the conversation pager .

### This Week's Theme
**Be a Reviewer!** This week, make sure to review 1 PR of any PL project, irrespective of the fact that you are part of any reviewer team or not as anyone can review. In the reviewing process, make sure to be involved as it's only then, you will learn the most. So, you can take hint about reviewer's job from the below list:

- Run the PR on your device to ensure the changes are working. You can do this by using:

`git fetch repo pull/pr-number/head:new-branch-name`

where:
repo: https://github.com/publiclab/mapknitter
pr-number: Pull Request num like 7314 
new-branch-name: name by which you want to create the new branch

Example: `git fetch https://github.com/publiclab/mapknitter pull/3233/head:pr-3233`

After that, checkout the branch using `git checkout new-branch-name`  

- See if there are any indentation errors
- If tests are failing, copy the error snippets in the PR for helping and also point to the solution or give hints for proceeding further
- Helping with codeclimate issues
- suggest new/better approach for solving the issue
- Ask for screenshot if design issue 
And, many more    

Since open source is all about community and helping others, let's find some issues which might be good for someone else who is contributing or just beginning and help them solve it. Let’s expand our community as much as we can! :tada:

### Summer of Code
@jywarren has started a brainstorming post for the ideas page for Summer of Code 2019 -It would be best to get some ideas into the discussion from the fellow community member before time. People have been brainstorming already - let's do it together!
https://publiclab.org/notes/warren/01-02-2019/brainstorming-for-summer-of-code-2019
And this is the official idea’s page:
https://publiclab.org/wiki/gsoc-ideas

### Software Contributors Survey
This survey is conducted on a yearly basis to improve our experience.
https://goo.gl/forms/4VVMO8dOijRj6BUA3
The form will remain open until early March, but don't wait to respond! This one’s for us!

### MapKnitter
Some great planning and discussions are going on in our MapKnitter repo, do check them out! We are welcoming new contributors there as well, so anyone is welcome to chime in!

cc
@mohitRJranjan @milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @geekychaser @shubhscoder
@sidntrivedi012 @SidharthBansal @cesswairimu @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1, @uzorjchibuzor, @eli6, @rexagod, @dinaelhanan, @dependabot[bot], @oorjitchowdhary, @wanzulfikri, @mohitRJranjan @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @romanrodriguez @Dhiraj240 @codeIriss @rishabhc32 @chirag-singhal @Saurabh19126848_twitter @IgorWilbert @dhruvgupta167 @vrk99 @pdurbin @dave-light @HarshKhandeparkar @aashna27 @Harshithpabbati @marieram @swiatek7 @kaunair

Thanks and keep contributing! Contributing to Public Lab means contributing to the Environment.

People who did the check-ins-
Gaurav Sachdeva (@gauravano )
Sidharth Bansal (@SidharthBansal)
Cess (@cesswairimu )
Harman Jolly (@CoderJolly )
Rishabh Rawat (@Rishabh570 )
Sasha Boginsky (@sashadev-sky)
Rishabh Kr Bothra (@geekychaser)
Shubham Sangamnerkar (@shubhscoder)
Siddhant N Trivedi(@sidntrivedi012)
Isha Gupta (@IshaGupta18)
Gaurav Sachdeva (@gauravano)
Harshith Pabbati (@Harshithpabbati )
Have a great week everyone :balloon: :tada: :sparkler:

**Comment by ebarry** [comment]
Last week on the survey ! (it's been open since Jan 14 and we designed it to be open for two months)

**Comment by Harshithpabbati** [comment]
There was a discussion and they said me open it. in #4879

**Comment by gauravano** [comment]
Nice theme @Harshithpabbati :sweat_smile: .Everyone, please make sure that your meme is not hurtful to anyone https://publiclab.org/conduct. 

Hmm, my name is not tagged because the limit is reached before that, so yes, removing duplicate names isn't helpful. Let's continue with mentioning names in comments only. 
@sashadev-sky

**Comment by gauravano** [comment]
@dhruvgupta167 @aashna27 @Harshithpabbati @marieram @swiatek7 @kaunair @alaxalves @manansingh96 @Chrisyee22 @Aneal-Sharma 


(mention limit exceeded in the above comment so mentioning separately)

**Comment by HarshKhandeparkar** [comment]
I found some Linux vs Mac vs Windows memes I thought the devs might like. Hope these don't hurt anybody.




![windows_vs_mac_vs_linux_2](https://user-images.githubusercontent.com/34770591/53829396-0d31cf80-3fa6-11e9-9e91-ef4614c1f819.jpeg)



![windows_vs_mac_vs_linux_3](https://user-images.githubusercontent.com/34770591/53829408-158a0a80-3fa6-11e9-9c7d-7be34114b444.jpg)

**Comment by alaxalves** [comment]
Hello PublicLab team. Let's work!! :muscle: :muscle: :muscle:

**Comment by cesswairimu** [comment]
Hello all :wave:,
### Week goals
* Do follow-ups on the tag graphs with @ebarry  and implement any requests
* Implement weekly caching of data on the site
* Do a close mirroring between stats pages and tag pages
* Look into gci-pending issues sort them/ rebase ones which are ready

Great week ahead.

**Comment by jywarren** [comment]
Hi all - we're doing a small poll -- we're curious what database do you use with `plots2`? We're discussing in #4896 whether to continue supporting `sqlite` or not -- and want to know how many people currently use different database types!

Please check it out and vote by clicking on the bar graphs: https://github.com/publiclab/plots2/issues/4919

**Comment by sashadev-sky** [comment]
@Harshithpabbati great check-in topic! @gauravano just taught me how to pull someone else's PR locally a few weeks ago. So useful!! 

This week I am continuing to work on mapknitter updates. I would love some help from a **macOS user** with PR [https://github.com/publiclab/mapknitter/pull/355](https://github.com/publiclab/mapknitter/pull/355). I wrote some instructions to install mysql (`MYSQL.md` file) and I just need a user to attempt to install mysql and run the repo using the provided instructions. Please comment either here or there if you are available to help out.

Thanks guys!

**Comment by alaxalves** [comment]
@all I'm currently working on https://github.com/publiclab/mapknitter/pull/363, just got stuck trying to PreCompile mapknitter assets. If anyone can help would be gr8. :crying_cat_face:

**Comment by sashadev-sky** [comment]
@alaxalves what are you stuck on specifically?

**Comment by HarshKhandeparkar** [comment]
@gauravano @publiclab/reviewers I have never done a community check-in before so I want to try doing this once. I will be busy this month(I might do it sometime next month). Where can I find the guidelines and list of contributors to mention? Thanks!

**Comment by alaxalves** [comment]
> @alaxalves what are you stuck on specifically?

@sashadev-sky Basically, I'm trying to make `rake assets:precompile` to work. I feel like there has been a lot of dependencies version mismatch that is causing this.

**Comment by gauravano** [comment]
Hey @HarshKhandeparkar, you are absolutely eligible and welcome to open the check-In. Just raise your :raising_hand_man: when you're free. 

You can find guidelines here https://github.com/publiclab/plots2/blob/master/doc/CHECKINS.md and regarding list of contributors, I myself take names from https://code.publiclab.org and new names I come across from issues/PRs/chatroom.

Thanks!

**Comment by HarshKhandeparkar** [comment]
Thanks a lot! One question I wanted to ask is why do we mention only some
people? Can't we just mention `@publiclab` to mention all people?

**Comment by gauravano** [comment]
Are you sure that @publiclab will notify all the members? @HarshKhandeparkar

**Comment by HarshKhandeparkar** [comment]
I'm not sure. That is why I asked.

**Comment by jywarren** [comment]
I wonder if it only notifies members of the organization, and we don't
always add everyone to the org. We could start doing that if it helps, but
not everyone would accept, but maybe that's OK? It might especially miss
new contributors though. But good questions!!!

**Comment by Harshithpabbati** [comment]
@gauravano  It will mention everyone who are the member's of the Public Lab. New contributers will not be mentioned in it (I mean who don't have any merge).
Thanks

**Comment by gauravano** [comment]
@Harshithpabbati any link or reference you can point to?

@HarshKhandeparkar I just mentioned with @ @publiclab in a random leaflet distortable issue. You got any notification?

**Comment by Harshithpabbati** [comment]
Nope I didnt get any notification.

**Comment by gauravano** [comment]
Then, it's not working

**Comment by HarshKhandeparkar** [comment]
Smartform?

**Comment by gauravano** [comment]
I tried here - https://github.com/publiclab/Leaflet.DistortableImage/issues/53#issuecomment-470150425

**Comment by HarshKhandeparkar** [comment]
I didn't get a notification

**Comment by HarshKhandeparkar** [comment]
If anybody(just about anybody) got a notification from Leaflet.DistortableImage please add a thumbs up :+1: to this comment otherwise add a :-1: . Maybe only some members got a notification?? This is just an experiment. Thanks.

**Comment by Harshithpabbati** [comment]
It's not working Harsh.

**Comment by IgorWilbert** [comment]
Hi all! Sorry for arriving late. Nice theme for a weekly check-in! It would be awesome if I could review some PRs, but I don't have the authorization to merge PRs in the Editor neither Image Sequencer... Should I somehow mark them as approved then? Thanks!

**Comment by Harshithpabbati** [comment]
Yeah mark it as approved!!

**Comment by gauravano** [comment]
@IgorWilbert reviewing is totally different from merging. Only some people have merge rights to repos. You can request changes, comment, approve the PRs, without being a maintainer. Even new contributors can review the PR. 

Thanks!

**Comment by gauravano** [comment]
Anyone interested in opening the upcoming week's check-in?

**Comment by Danielshow** [comment]
I will love to contribute to this project as well as review some PR's. A Junior Ruby on Rails developer here.

**Comment by gauravano** [comment]
Welcome @Danielshow! We would also love to have your help with issues - https://github.com/publiclab/plots2/issues (We just crossed 500 :open_mouth: ) and there are many [PRs](https://github.com/publiclab/plots2/pulls) to review too. 

Let us know if you need any help. Thanks!

**Comment by CleverFool77** [comment]
@gauravano I would like to be part of this.
I'm more of into frontend so I can review the frontend part and code quality.

**Comment by Harshithpabbati** [comment]
@CleverFool77 sure you can review pr's.
Thanks for the help :)

**Comment by CleverFool77** [comment]
Sure @Harshithpabbati  :). I just need to test the PRs locally and comment down the suggestions/changes or give my review right.

**Comment by Harshithpabbati** [comment]
Yeah or else for frontend part you can ask them the screenshot.
Thanks.

**Comment by gauravano** [comment]
@CleverFool77 

1. You can suggest new methods/clean-up ideas
2. If you think the change is big and requires some more testing, we have unstable.publiclab.org for that, so you can ask @publiclab/reviewers for pushing PR to unstable.
3. Collaborate on PR(if required). And, there's a lot which can be done..

**Comment by gauravano** [comment]
New check-in open at https://github.com/publiclab/plots2/issues/5034. Thanks everyone!
