### ISSUE TITLE
DB Migration chokes deployment

### ISSUE THREAD

**Issue by icarito** [publiclab/plots2#4924]
This migration appears stuck in production deployment process:
```
class AddFirstTagPoster < ActiveRecord::Migration[5.1]
  def find_and_update
    User.joins(:node).where('node.status = ?', 1).each do |user|
      if user.nodes.present?
        node = user.nodes.first
        node.add_tag('first-time-post', user)
      end
    end
  end

  def up
    find_and_update
  end
end
```

**Comment by icarito** [comment]
My impression is that joining Users and Node is heavy...

**Comment by jywarren** [comment]
ahhhhhhh i should've caught that. Sorry! Should we refactor that and try
running again?

**Comment by namangupta01** [comment]
What exactly we want to do here?

**Comment by jywarren** [comment]
I think we need to add additional conditions to the `User...()` call so that we aren't trying to fetch all user records. But according to previous tests, this should only be calling 7k records, which isn't all that much:

```ruby
> User.joins(:node).where('node.status = ?', 1).count
=> 7278
> User.joins(:comments).count
=> 15201
```

@icarito do you think even 7k records would be too many and could be causing this?

**Comment by jywarren** [comment]
Testing the above on live db console to benchmark...

**Comment by jywarren** [comment]
I wonder if it's just taking a really long time to go through and make all the tags, but that potentially it's not actually hanging but just taking a really long time to iterate through 7k records and do this for each one?

**Comment by jywarren** [comment]
OK, compare:

`> User.joins(:node).where('node.status = ?', 1).count => 7278`

`User.joins(:node).where('node.status = ?', 1).distinct.count => 1407`

`User.includes(:node).where(node: { status: 1 }).count => 1407`

Gah, ok well that helps a bit...

**Comment by jywarren** [comment]
https://guides.rubyonrails.org/active_record_querying.html#specifying-conditions-on-eager-loaded-associations

**Comment by jywarren** [comment]
Attempted fix here: https://github.com/publiclab/plots2/commit/17378761cdd9f89028342138321bc3f6e9746868

**Comment by jywarren** [comment]
Deploying this now... hoping!

**Comment by jywarren** [comment]
Done! It worked!
