### ISSUE TITLE
Subscribers over time 

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#4925]
Display the # of subscribers over time on tag stats pages like this: https://publiclab.org/tag/ui/stats

**Comment by cesswairimu** [comment]
@gauravano @jywarren @sagarpreet-chadha @SidharthBansal 

This is what I have in mind for this graph.
![sy59iglx](https://user-images.githubusercontent.com/17081074/54767485-486f0800-4c0e-11e9-9ed0-d88c2d4b531c.png)

The bar graphs showing the number of subscribers subscribed during a period and the area graph showing the growth number of subscribers with time for each tag.

However I am blocked on how to fetch this data. The `node_selection` model does not have a timestamp so I cannot use it to get the number of subscribers at a particular time or the number of subscribers who subscribed within a given range. Maybe I am missing something...any ideas on how I can query the number of subscribers against time.
 Also how does the graph look? Thanks.

**Comment by jywarren** [comment]
ahhhhhhh node_selection has no timestamp? wait, what about tag_selection?

If tag_selection has none, we may be stuck! I mean, we could start tracking
now, but we'd have no data from the past...

**Comment by cesswairimu** [comment]
Oh sorry I meant `tag_selection'

**Comment by cesswairimu** [comment]
Okay I think I will add the timestamp and we can start tracking from now. Thanks @jywarren

**Comment by jywarren** [comment]
OK, thank you Cess!

**Comment by jywarren** [comment]
> Active Record automatically timestamps create and update operations if the table has fields named created_at/created_on or updated_at/updated_on.

I think this'll be a very quick fix!
