### ISSUE TITLE
Call for related search terms

### ISSUE THREAD

**Issue by shubhscoder** [publiclab/plots2#4928]
So recently, we implemented a feature wherein the search for a particular term at publiclab.org/search also returns results for the terms that are related to it. #4823 is the relevant issue and #4848 is the solution for the same. 

However for the solution to work we have used a [dictionary file here](https://github.com/publiclab/plots2/blob/master/lib/related_and_hyphenated_terms.dict.txt) - just a simple text file. This dictionary would  use a variety of domain specific words and thus we need everyone's help in setting this dictionary properly.

Following types of words are expected to go into the dictionary : 

1.  Hyphenated terms when for corresponding non-hyphenated ones. For example, we could have the following pair : 

```
purpleair: purple-air
```

2. Related terms, we often use short forms or abbreviations for commonly used terms. But the search engine most of the time misses out on this abbreviations. So we should construct a dictionary of such abbreviations along with the actual corresponding word. For example, this could be one of the pairs:

```
h2s: Hydrogen Sulphide
```

Thank you so much!

**Comment by shubhscoder** [comment]
So @jywarren, do we want people to submit their words by making Pull requests ? Or is there some  other way?

**Comment by gauravano** [comment]
Nice issue @shubhscoder! How about asking contributors to comment the related terms in issue's comments and we can add them weekly/monthly?

**Comment by shubhscoder** [comment]
Yes we could do that @gauravano. Also I have one more idea, how about posting a new wiki on public labs and ask people to comment the related terms there?

**Comment by gauravano** [comment]
We can also ask people to edit the wiki?

**Comment by shubhscoder** [comment]
Yeah that sounds good. We can do that!

**Comment by jywarren** [comment]
I think possibly @ebarry suggested this?

> voc: volatile-organic-compund

Others I can think of are:

```
discussion-list: mailing-list
mailing-list: discussion-list
listserv: mailing-list
dust: pm
pm: dust
particulates: dust
tds: total-dissolved-solids
datalogger: data-logging
```

**Comment by ebarry** [comment]
event: meetup
formaldehyde: HCHO
formaldehyde: CH2O
ag: agriculture
agriculture: farming

are these pairs not reversable, as in, do i have to write the pairs in the other direction as well?

**Comment by shubhscoder** [comment]
I think even the reverse is required.

**Comment by ebarry** [comment]
alright, well let's use this issue to grab quick thoughts, and then maybe we set up a spreadsheet somewhere with a formula to generate all the reverse forms of the pairs?

cafo: factory-farm
cafo: feedlot
sewage: wastewater
salinity: conductivity

**Comment by shubhscoder** [comment]
Yeah that sounds good👍

**Comment by jywarren** [comment]
We may want to do reverse in some cases but not others, so let's keep doing it manually. Some terms might be related to broader terms but we wouldn't want the reverse. 

`valverde: val-verde`

**Comment by jywarren** [comment]
```
data-logging: datalogging
data-logging: data logging
```

**Comment by jywarren** [comment]
Added all these in a batch: #5503

Noting that we're not sure about how to do multiple word additions; for example:

```
h2s "Hydrogen Sulphide"
data-logging "data logging"
cafo "factory farm"
```

So I'm asking over here: https://github.com/yohasebe/lemmatizer/issues/7

**Comment by ebarry** [comment]
urban-planning: urban-design 
urban-design: urban-planning (happy to discuss as once upon a time this was my field, but pragmatically think these should be joined for Public Lab)

soil: dirt
dirt: soil
community-engagement: communityengagement
communityengagement: community-engagement
marine: water 
water: marine

**Comment by ebarry** [comment]
ewb: engineers-without-borders
engineers-without-borders: ewb

pole-aerial-photography: pap
pap: pole-aerial-photography

global-climate-change: climate-change
climate-change: global-climate-change

urbanwater: urbanwaters
urbanwaters: urbanwater

**Comment by jywarren** [comment]
Noting that as of the latest https://github.com/yohasebe/lemmatizer we can now have spaces in the right-hand terms:

https://github.com/yohasebe/lemmatizer#resolving-abbreviations

Thanks to @yohasebe!!!!! ❤️

**Comment by ebarry** [comment]
colorimetry: colorimetric
colorimetric: colorimetry

colorimeter: colorimeters
colorimeters: colorimeter

**Comment by ebarry** [comment]
hot-spot: hot-spots
hot-spots: hot-spot

microscope: microscopes
microscopes: microscope

PS Is there a way to automatically relate a word with the same word that just has an "s" on the end? Asking for a friend!

**Comment by ebarry** [comment]
plastic: plastics
plastics: plastic

radiation: radioactive
radioactive: radiation

superfund-site: superfund
superfund: superfund-sites

spectra: spectrum
spectrum: spectra

**Comment by ebarry** [comment]
diagram | diagrams | diagramming <-- how to associate a cluster?

noise: sound
sound: noise

**Comment by ebarry** [comment]
booklet: publication
publication: booklet

**Comment by ebarry** [comment]
filter: filtering
filtering: filter

filter: filtration
filtration: filter

filtration: filtering
filtering: filtration

**Comment by jywarren** [comment]
Hi Liz, i believe all of these will be covered by lemmatization, thanks!

**Comment by ebarry** [comment]
fossil-fuel: oil-and-gas
oil-and-gas: fossil-fuel

**Comment by jywarren** [comment]
Closing this as we are mainly running on google search now! Thank you!

**Comment by ebarry** [comment]
eu: europe

**Comment by jywarren** [comment]
And, for purposes of migrating tags, I suggest NOT doing all of these, but
choosing only those which we know there is content for and which we want to
take this big action on. But this is a good source to skim to ID such tags!
