### ISSUE TITLE
Improve Pagination in Tags Search

### ISSUE THREAD

**Issue by avsingh999** [publiclab/plots2#4931]
When We Search Tags in Search then pagination nombers  looking not perfect because last pages not showing anything so I think we should Improve this

![ff](https://user-images.githubusercontent.com/25536022/53911216-d201d000-407b-11e9-992a-429018a0c0d6.gif)

**Comment by jywarren** [comment]
We'd love some help with formatting that page!!! Can you share a mockup
based on Bootstrap https://getbootstrap.com/docs/3.3/ for how it might be
improved? Thank you!

**Comment by jywarren** [comment]
Closing as we've revamped search entirely! Thank you!!
