### ISSUE TITLE
Pop up a modal menu with templates when starting a new wiki page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4932]
Going to https://publiclab.org/wiki/new opens a new blank wiki page, but it's a bit bare, and hard for people to know where to begin. Let's offer a Bootstrap modal with some template options:

![screen shot 2019-03-06 at 3 51 27 pm](https://user-images.githubusercontent.com/24359/53912828-cb496d80-4027-11e9-974c-b408c57a0a49.png)

The actual content of the modal we could set in a Feature ([learn about this system here](https://github.com/publiclab/plots2/blob/master/doc/DATA_MODEL.md#features)) which means we don't have to put the HTML for this into the codebase - we'll store it in the database, and I can help with that. For now, we can put that code into a Gist: https://gist.github.com

But the code for the modal which will contain the templates will have to go in our codebase. 

Here's the template for the "new wiki page" page; but note that we use this for editing the wiki page too:

https://github.com/publiclab/plots2/blob/master/app/views/wiki/edit.html.erb

To distinguish, we might need to set a variable in the controller that we can use to turn the modal on: 

https://github.com/publiclab/plots2/blob/master/app/controllers/wiki_controller.rb#L121

**Comment by Chrisyee22** [comment]
Hi @jywarren. Could I work on this?

**Comment by jywarren** [comment]
Oh yes, that'd be super! Thank you!

**Comment by yash98gupta** [comment]
Hello @jywarren. may i work on this issue ?

**Comment by Chrisyee22** [comment]
Hi @yash98gupta. I’m actually working on this at the moment.

**Comment by gauravano** [comment]
Hi @yash98gupta , as this issue is already claimed. But, you can see we have many issues to tackle - https://github.com/publiclab/plots2/issues/ so if you dig a little, you'll find a good issue. If you are looking for your first-issue then, you can find it at https://code.publiclab.org/#r=all, if you can't find any unclaimed issue there, feel free to comment below or in Gitter channel - https://gitter.im/publiclab/publiclab, we'll try to create one for you. Thanks!

**Comment by divyabaid16** [comment]
Is this issue still open?
I would like to work on this.

**Comment by Chrisyee22** [comment]
I am currently working on this.

**Comment by jywarren** [comment]
Hi Divya, perhaps you could look over Chrisyee22's code to offer input or
suggestions until I or another reviewer has a chance? Thanks!

**Comment by Manasa2850** [comment]
@jywarren I would like to work on this!

**Comment by Manasa2850** [comment]
@jywarren I would like to try this!
