### ISSUE TITLE
Improve view of  /notes page

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#4937]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: 
At https://publiclab.org/notes the Spam and Read more buttons are rendering on the different lines as visible in the screen shot
![notes_view](https://user-images.githubusercontent.com/20878070/53973220-5f99fa00-4126-11e9-8e7a-af759b5f0eb2.png)

Update https://github.com/publiclab/plots2/blob/master/app/views/notes/_notes.html.erb#L49-L52 so as to show both buttons in a single line enhancing the page design

After changing the view, also attach the screenshot of updated view in the PR.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by gauravano** [comment]
This issue is for @AnthoniaOkafor. Thanks!

**Comment by AnthoniaOkafor** [comment]
Thanks!

**Comment by shreyateeza** [comment]
@gauravano Can I work on this issue?

**Comment by gauravano** [comment]
Hey @shreyateeza, this issue was created for @AnthoniaOkafor as they were searching for their first-issue with us. I can create one for you too if you are looking for a `first-timer-only` issue?  Thanks!

**Comment by shreyateeza** [comment]
@gauravano Thanks! Yes, I want to solve a more `first-timers-only` issue. Please assign one to me!

**Comment by EngrEric** [comment]
@gauravano  please create similar issue to for me.

**Comment by gauravano** [comment]
hey @shreyateeza @EngrEric, added your name to the list -https://github.com/publiclab/plots2/issues/4963. Will ping you shortly with a issue

**Comment by shreyateeza** [comment]
@gauravano You have added my name in it. Please assign me an issue to work on.

**Comment by gauravano** [comment]
hey @shreyateeza sorry for the delay. I have created one for you at https://github.com/publiclab/plots2/issues/4979 . Thanks!

**Comment by Divy123** [comment]
@gauravano please look into gitter chat.
I have messaged you privately and its urgent.

**Comment by EngrEric** [comment]
@gauravano please i am waiting for my own too

**Comment by gauravano** [comment]
@EngrEric here's one for you - https://github.com/publiclab/plots2/issues/4980. Please claim. Thanks!

**Comment by Jenniline** [comment]
@gauravano  Please can i have one to work on too.

**Comment by sashadev-sky** [comment]
@AnthoniaOkafor Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks! We are starting to request that contributors show some sort of activity towards a first-timers-only issue after claiming it within a week because there is high demand for them. (whether that is asking for more time, help, opening a PR, etc.)

**Comment by AnthoniaOkafor** [comment]
Hello @sashadev-sky. I'll open a PR today. Thanks

**Comment by AnthoniaOkafor** [comment]
Hi @sashadev-sky. I have successfully resolved my FTO issue and pushed it to my fork. However I already opened a PR last week. Do I open a new PR or continue with my first PR? https://github.com/publiclab/plots2/pull/4961#issue-259593726 
 If I'm continuing with the first PR are there changes to be made anywhere in it? Thanks

**Comment by EngrEric** [comment]
@AnthoniaOkafor, congrats on opening your PR.
Am still finding it difficult to run the repo locally so that I will start working.
Are you on windows or Linux?
Again am in Lagos, will want to sync with you to put me through.

**Comment by AnthoniaOkafor** [comment]
Hey @EngrEric, thanks. My laptop runs on Windows but I run the app on Cloud9. If you are finding it challenging running it locally, you could try Cloud9.

**Comment by EngrEric** [comment]
@AnthoniaOkafor but cloud9 is now on AWS and it is not free i think.
i will want to sync with you for guidance. this is my mail ericbest960@gmail.com, am expecting mail from you thanks

**Comment by gauravano** [comment]
Hey @EngrEric, we can send you an invite to Cloud9. It would be free to use then. 

cc @jywarren.

**Comment by gauravano** [comment]
Also, I remember you mentioned about the mysql error in gitter error . If you are still having that same issue then you can update your local master branch by 
`git checkout master` - to checkout master branch
`git pull https://github.com/publiclab/plots2 master` - to update your local branch

After that, you can update your feature-branch i.e., branch on which you have worked on using 
`git checkout [feature-branch-name]` - to checkout that branch
`git rebase master` - to update that branch
`rails s` - run server 

If you haven't made any feature-branch till now, you can do that by:(Do this after updating local master branch only otherwise you have to rebase the branch formed in this step)

`git checkout -b [feature-branch-name]`
`rails s`

**Comment by AnthoniaOkafor** [comment]
Ok @gauravano, I'll do just that. Many thanks

**Comment by sashadev-sky** [comment]
@AnthoniaOkafor if the changes you make are still relevant to the first PR you opened then continue pushing them there. All you have to do is add the changes to that branch and push it `git push origin <yourBranchName> and it'll update there! 

Otherwise you create a new branch for a different feature or something addressing a different issue and push that up. Work on one branch will not effect work on the other and your local repo will update to reflect which branch you are on.

**Comment by sashadev-sky** [comment]
@AnthoniaOkafor I think @gauravano has been following your original PR closer so he can confirm but it looks like he wants you to push your changes there

**Comment by gauravano** [comment]
@AnthoniaOkafor check here - https://github.com/publiclab/plots2/pull/4961#issuecomment-473578125

**Comment by EngrEric** [comment]
@gauravano  i have used cloud9 to setup still same problem.
i think am doing something wrong, i need help please. this is really delaying me.

**Comment by EngrEric** [comment]
@gauravano  thanks for bearing my disturbances i got it working now.
thank you
