### ISSUE TITLE
Add links to popular tags graph on /stats page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4938]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

@cesswairimu has made a great new feature to show popular tags in a period of time, at https://publiclab.org/stats 👍 :

![image](https://user-images.githubusercontent.com/24359/53979203-238d7780-40db-11e9-8701-61fcf19ca75f.png)

It'd be awesome if when you click that bar, it would open the tags page for that tag. So the first bar there could open

https://publiclab.org/tag/first-time-poster/

We'd love help with this!

**Comment by ananyaarun** [comment]
@jywarren , I'd like to work on this issue

**Comment by jywarren** [comment]
Oh please, that would be great. Do you know where to find the templates?

**Comment by ananyaarun** [comment]
@jywarren Was just about to ask  :) . 
I see that the main html file is in plots2/app/views/stats/index.html.erb.
But am bit confused about where the other templates are.

**Comment by cesswairimu** [comment]
@ananyaarun this specific graph is at `/views/stats/index.html.erb` here is the script for this graph https://github.com/publiclab/plots2/blob/master/app/views/stats/index.html.erb#L200-L242
Rendered on the html page by this div https://github.com/publiclab/plots2/blob/master/app/views/stats/index.html.erb#L29

**Comment by shreyateeza** [comment]
@jywarren @ananyaarun If not done, can I work on this issue?

**Comment by Harshithpabbati** [comment]
@shreyateeza we had a discussion of assigning a  first timers  issue to one person for a week. So please kindly search for the other one.
Thanks!

**Comment by ananyaarun** [comment]
@shreyateeza , I'm currently working on this issue :)

**Comment by ananyaarun** [comment]
@jywarren I have been trying to find a way to extract the tag names from the script to link it to the graph accordingly based on which bar is clicked. I had a discussion with @cesswairimu  as well regarding this. At the moment i am able to link the graph to the tags page but not the specific tag. Any ideas on how i can proceed with this issue ? Thanks :)

**Comment by jywarren** [comment]
Hi! I wonder if this could help? https://stackoverflow.com/a/52972766

Did you see the full docs here? Thank you! https://apexcharts.com/docs/options/chart/events/#
