### ISSUE TITLE
Change read more link to button at /blog

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#4940]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: 
At https://publiclab.org/blog the Read more link with the subscribe button doesn't look good ![blog_link](https://user-images.githubusercontent.com/20878070/53983878-2a010b00-413e-11e9-94e3-d39116f2d2be.png)

so let's change the link to a button matching the subscribe button style 

Update https://github.com/publiclab/plots2/blob/master/app/views/tag/blog.html.erb#L63 to do so

After changing the view, also attach the screenshot of updated view in the PR.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by gauravano** [comment]
This one is for @uimarshall . Thanks!

**Comment by uimarshall** [comment]
Thanks @gauravano .I really appreciate this opportunity. I will start working right away!!!

**Comment by gauravano** [comment]
Great!

**Comment by TANGL3SIT3S** [comment]
Hello everyone. Is this still open for help. I don't helping someone if you are stuck. Two heads are better than one .

**Comment by nazeem1988** [comment]
I have been waiting for couple of days to find some good first issue. @gauravano could you pls pass one on to me. I have knowledge in HTML and CSS.

**Comment by shreyateeza** [comment]
Hi @gauravano Can I work on this issue?

**Comment by uimarshall** [comment]
Hi @gauravano i have fork the repository and clone it to my local system. I have also navigated to the folder in my text-editor but i cannot see the `read more` link in the code. Though am able to see it when i use google dev tools.
Kindly assist.

**Comment by gauravano** [comment]
Hi @TANGL3SIT3S, you can collaborate with @uimarshall for solving this issue if they don't mind. I will try to open a new FTO for you too. 

Hey @nazeem1988, sorry you have to wait, I will ping you soon with the FTO.

**Comment by gauravano** [comment]
Hey @shreyateeza , this issue is already claimed by @uimarshall. But, we would love to have your help with other issues, you can find more issues at https://code.publiclab.org/#r=all and if you can't find any unclaimed issue there, feel free to comment below or in the Gitter channel - https://gitter.im/publiclab/publiclab, so that we can try to help you in finding a good issue to start with or maybe create a new issue for you. 

Thanks!

**Comment by gauravano** [comment]
@uimarshall I gone through your fork and the code is visible to me - https://github.com/uimarshall/plots2/blob/master/app/views/tag/blog.html.erb#L63 

Are you not able to see the above line on your editor or you are not able to see any blog post on running local server?

**Comment by karunagoyalk** [comment]
@gauravano Please assign me some task to me also

**Comment by gauravano** [comment]
hey @karunagoyalk, you got your FTO - https://github.com/publiclab/plots2/issues/4972 right?

**Comment by gautamig54** [comment]
Hello @gauravano !!
I have been looking at various issues but all of them seem to be assigned. Can you assign me an issue also!

**Comment by gauravano** [comment]
@uimarshall if you need any help, feel free to ask. Thanks!

**Comment by jayshree1602** [comment]
Hey! @gauravano the issues I am finding are mostly claimed, kindly help me out in finding one . Thanks.

**Comment by gauravano** [comment]
Hey @jayshree1602, you can start with this one as @uimarshall hasn't replied. Thanks!

**Comment by Linda-Ikechukwu** [comment]
Hi, is this still open I would love to work on this.. I'm an outreachy intern applicant

**Comment by jywarren** [comment]
Hi, if nobody has replied for a while (which seems right) we'd love your
help! Are there any open PRs for it?

**Comment by daningenthron** [comment]
Hi @jywarren, if this is still open I would be happy to push a PR, I have it set up locally with the button working correctly - let me know!
