### ISSUE TITLE
Wiki editing seems to be broken

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4941]
Hi all -- we seem to have a new bug with the wiki editing system; perhaps related to some recent changes to https://github.com/publiclab/plots2/blob/master/app/controllers/wiki_controller.rb ?

**Comment by siaw23** [comment]
Can you please get this for us? https://github.com/publiclab/plots2/issues/4903 ? That way we don't have to wait for someone to report, it show up automatically what exactly is happening and how it happened then we can all look together and fix it. It's helpful I think.

**Comment by gauravano** [comment]
Hey @jywarren, raising PR for this one. Thanks!

**Comment by siaw23** [comment]
Reason for my post is I can't reproduce locally. Editing works fine locally.

**Comment by gauravano** [comment]
I tried editing the wiki locally and got error.

**Comment by siaw23** [comment]
As which user? normal or admin? @gauravano

**Comment by gauravano** [comment]
As moderator. Actually, here- https://github.com/publiclab/plots2/commit/40b6624af14b10027196b049e3a1ed8e11dd287e#diff-528416b5954756daa0b141666006dbcb during clean up there was a slight change in order of statements, due to which node.vid was getting null but as per schema it can't be null so 500 was thrown

**Comment by siaw23** [comment]
Yeah I missed that. Thanks for catching it. My main concern though is why didn't the test catch it though.

**Comment by gauravano** [comment]
Yes, it's really shocking that Travis wasn't able to catch this

**Comment by jywarren** [comment]
@siaw23 re: #4903 i think it's a great idea. I am scrambling today to keep up so let me do my best to look at it. Thanks!

**Comment by jywarren** [comment]
@gauravano would you mind looking through the logs to see how this somehow mightn't have been caught? Are we really catching the `success` in the test? Are we doing it to an existing wiki page, anything maybe about the context or parameters or db state that could conceivably be different? Could we run the update twice in the test?

**Comment by gauravano** [comment]
@jywarren will go through the logs and try to find the reasons.

**Comment by gauravano** [comment]
Build logs were not showing enough info so I restarted the build - https://travis-ci.org/publiclab/plots2/builds/501925116?utm_source=github_status&utm_medium=notification

**Comment by gauravano** [comment]
It failed as the branch - https://github.com/publiclab/plots2/pull/4902 is deleted

**Comment by gauravano** [comment]
@jywarren I can't see any way we can see detailed build logs for https://github.com/publiclab/plots2/pull/4902 via Travis. Any idea?

**Comment by jywarren** [comment]
All i can think of is going through the builds on the master branch from more than 12 days ago.... https://travis-ci.org/publiclab/plots2/builds

**Comment by gauravano** [comment]
I went through each commit of #4902 and found that the travis build didn't run when the bug introducing commit is made mistakenly :point_down: 

![travis_build_skipped](https://user-images.githubusercontent.com/20878070/54712951-866b1e00-4b73-11e9-9400-2391435f58bf.gif)

**Comment by gauravano** [comment]
As seen in the above Gif the small refactor commit doesn't show any Travis build. But, I think subsequent builds should've found the bug but don't know why no test was able to find it.
