### ISSUE TITLE
Improve the landing page

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#4947]
## Description 
The website looks inconsistent with the page being sectioned into two in the landing page. Instead we can shift down the right side a bit and and have the image on right side to to take the full width of the viewport. From User's view and designer's view, It doesn't provide a proper user interaction with the user. It looks bloated with lots of tags which makes it difficult for a new user to understand the website on first look.And usually first impression is the last. It would be better to for minimal landing page with better user experience design. 
I designed a rough wireframe to depict the same.

## Affected Page 
`/dashboard`

## Current status 
Here is the attached screenshot 
![screenshot from 2019-03-08 12-32-27](https://user-images.githubusercontent.com/26685258/54013193-42a10d80-419e-11e9-8854-da91f06acd4c.png)

## Expected Behaviour 
![screenshot from 2019-03-08 12-30-27 1](https://user-images.githubusercontent.com/26685258/54013180-387f0f00-419e-11e9-99ab-8f661357d8be.png)

**Comment by CleverFool77** [comment]
If approved, then I would like to work on this. Thanks you

**Comment by jywarren** [comment]
Hi! We will soon be working a bit on dashboard redesign: https://publiclab.org/notes/edie_blues/12-13-2018/public-lab-dashboard-new-design-ideas

Ideas are coming together in https://github.com/publiclab/plots2/issues/4922 where you may want to start watching. Thanks!
