### ISSUE TITLE
Improve the Login UI Modal Box.

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#4948]
## Description 
Currently the fields under Oauth section inclined towards left. It would be better to let it be at center. 
This is a first-timer issue.

## Current behaviour 
![screenshot from 2019-03-08 13-18-31](https://user-images.githubusercontent.com/26685258/54015165-ec839880-41a4-11e9-9508-7bd2035bdf06.png)

## Expected Behaviour
The fields should be in center.

**Comment by CleverFool77** [comment]
I would like to work on this.

**Comment by gauravano** [comment]
Hi @avsingh999, please ensure to label only those issues with `first-timers-only` which has FTO template as given here -https://github.com/publiclab/plots2/blob/master/.github/ISSUE_TEMPLATE/first-timers-issue-template.md . 

As being a first-timers-friendly org, we want to ensure that all the FTO issues follow the same template so it wouldn't confuse new contributors. Thanks!
