### ISSUE TITLE
regression in tag pills for admin user.

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#4952]
## Description 
On Admin's side - 
After clicking on the tag pill to view more information, the pill's css get distorted from right side.

## Current Behaviour 
![screenshot from 2019-03-08 15-51-02](https://user-images.githubusercontent.com/26685258/54023281-915ca080-41ba-11e9-9f93-478a1fb78e6e.png)

#### It stays as it is, even after closing the popup.
![screenshot from 2019-03-08 15-51-17](https://user-images.githubusercontent.com/26685258/54023383-d54fa580-41ba-11e9-99b7-b67c1cf1d993.png)

## Expected Behaviour
The Css shouldn't get distorted.

**Comment by CleverFool77** [comment]
If approved, I would like to work on this issue.

**Comment by siaw23** [comment]
Please go for it.

**Comment by CleverFool77** [comment]
I'm bit busy in hackathon 😅, so it might take a day or two in making a PR. Thank you

**Comment by jywarren** [comment]
Thanks!!

**Comment by CleverFool77** [comment]
@jywarren My hackathons were done, So i opened a PR. Thanks.

**Comment by jywarren** [comment]
awesome, and THANK YOU! We'd love your help in supporting some of the
others making their first contribution. Perhaps you'd be interested to skim
some of these and see if people are stuck? https://code.publiclab.org
