### ISSUE TITLE
Change UI of Navbar for Public Lab Store page

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/plots2#4954]
## Description

The UI design (mainly Navbar )of the Public Lab Store page is different from the other Public Lab pages.

## Current Behavior

UI of Public Lab Store Page

![publiclab_store](https://user-images.githubusercontent.com/32260628/54032618-2fab2f00-41d8-11e9-9b90-31a4554ec2aa.png)

UI of Public Lab pages

![publiclab](https://user-images.githubusercontent.com/32260628/54032794-9fb9b500-41d8-11e9-9a81-4fbb3e45bd5f.png)

## Solution
The CSS of the Navbar on Public Lab Store Page needs to be changed to match the other Public Lab pages.

**Comment by ananyaarun** [comment]
Anyone willing can work on this issue , Else i'll take it up after finishing the other issue i'm currently working on :)

**Comment by gauravano** [comment]
@ananyaarun the https://store.publiclab.org/ site's code is not Open sourced and I guess the site is made using Shopify as footer suggests. We only work on publiclab.org but your suggestions for the design change can be conveyed to @publiclab/community-reps @jywarren. Thanks for thinking, I guess, we can close it, now.
