### ISSUE TITLE
Bug: Cannot save profile edits 

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#4957]
Dear all, 
Tiny bug here -- i have been attempting for the past two days to add some great new gifs to my profile. These gifs are really delightful IMHO. 

However, after clicking the "Save" button, it turns into a spinny symbol for upwards of half an hour (haven't tested beyond that)

![spinning-edit-button](https://user-images.githubusercontent.com/161439/54045132-c5c26380-419e-11e9-9259-80484f81f5f3.gif)

Thanks for taking a look!

**Comment by jywarren** [comment]
Link to try this out: https://publiclab.org/profile (login required)

**Comment by jywarren** [comment]
Noting that this is probably not related to a mailing system issue as in https://github.com/publiclab/plots2/issues/4958, https://github.com/publiclab/plots2/issues/4956, because this action doesn't send mail. Will pull the logs on this and see... thanks for reporting!
