### ISSUE TITLE
Bug: error when posting comments

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#4958]
Hello,
I'm getting an error when I try to post comments on posts. A green error bar shows up on the top right hand side of my screen, then pulls away and I see this error on the page: 

<img width="1136" alt="screen shot 2019-03-08 at 12 27 35 pm" src="https://user-images.githubusercontent.com/7490478/54045362-6d3f9600-419f-11e9-812b-b78936c8d0e4.png">

If I refresh the page the comment is there.
I'm using a chrome browser Version 72.0.3626.119 (Official Build) (64-bit)

Best,
Stevie

**Comment by jywarren** [comment]
Link to try this out: https://stable.publiclab.org/research (any note should work!) (login required)

**Comment by jywarren** [comment]
And confirmed, i had an error doing this too!

**Comment by jywarren** [comment]
Noting that this may be related to https://github.com/publiclab/plots2/issues/4957, and https://github.com/publiclab/plots2/issues/4956, due to a mailing system issue we are looking at. Thank you!

**Comment by jywarren** [comment]
I just tested this after we restarted the mailing system and it seems to be working now, sorry for the downtime!
