### ISSUE TITLE
Gem load error after pulling from master

### ISSUE THREAD

**Issue by shubhscoder** [publiclab/plots2#4959]
So, as usual I just pulled from master and as some new gems were added ran <code>bundle install</code>.
After that I ran <code>rails s</code> and got the following error : 
```
Exiting
/home/scube97/.rvm/gems/ruby-2.4.4/gems/bundler-1.16.4/lib/bundler/rubygems_integration.rb:408:in `block (2 levels) in replace_gem': mysql2 is not part of the bundle. Add it to your Gemfile. (Gem::LoadError)
```
All other branches that are not in sync with the master, work completely fine. But don't know why the latest master is failing. Any help is appreciated.
Thank you so much!

**Comment by siaw23** [comment]
Please post the content of your `database.yml`

**Comment by jywarren** [comment]
Hi, thank you for reporting! I believe this could be related to or the same as https://github.com/publiclab/plots2/issues/4936 -- does that seem likely? Thank you!

**Comment by shubhscoder** [comment]
Yes @jywarren I think this issue is duplicate. We can close this. Thank you!

**Comment by gauravano** [comment]
Hey @shubhscoder @siaw2, you can reopen the issue for continuing the discussion here or at https://github.com/publiclab/plots2/issues/4936. Thanks!
