### ISSUE TITLE
Unable to post new note

### ISSUE THREAD

**Issue by joyofsoy** [publiclab/plots2#4964]
I've been trying to post a new note for about half an hour. When I press Publish, it just spins but doesn't make any progress. I also tried posting in the legacy editor, but after hitting Publish, received the message ***There was an error. Are you sure you have the right address?***

**Comment by gauravano** [comment]
I think, there is same error source behind this one, #4956 and #4958. Maybe failure of mailing system? @jywarren

**Comment by jywarren** [comment]
Yes, i think that's likely. I've alerted icarito about that possibility. Thank you!

**Comment by jywarren** [comment]
OK, this should be working again now as we've restarted the mailing system. Sorry for the downtime!
