### ISSUE TITLE
Make spamaway ids unique

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#4966]
Our spamaway system shows these nice emoji to prevent spammers:

https://publiclab.org/signup?spamaway=true (if you're not logged in)

The code is here:

https://github.com/publiclab/plots2/blob/3d74756c6f7a1ef43dd412c06c2aba9923c98026/app/views/users/_spamaway.html.erb#L19-L21

However, we're getting a warning now that since this is loaded multiple times per page, this segment is causing a collision of identical CSS ids:

![image](https://user-images.githubusercontent.com/24359/54062796-66804580-41d6-11e9-8aaa-c4a6be06f3c2.png)

I think we have to replumb it using classnames to get rid of this warning. 

I /think/ we can potentially change these lines:

https://github.com/publiclab/plots2/blob/3d74756c6f7a1ef43dd412c06c2aba9923c98026/app/views/users/_spamaway.html.erb#L19-L21

They're currently rendering like this, and you can see the ` id="spamaway_statement1_"` that's causing the problem. But i think it may not be important to the functioning of the system, because the `name` field is the important part of a form. The 

```
<button type="button" class="col-xs-5 btn btn-default" style="font-size:3em;text-align:left;" id="spamaway-00">
--
  | <input type="radio" value="📻" name="spamaway[statement1]" id="spamaway_statement1_" /> 📻
  | </button>
```

The above `radio_button` line is part of the form helpers in Rails: https://guides.rubyonrails.org/form_helpers.html

Can we maybe pass in something to the `radio_button` method to give a more unique id?

**Comment by divyabaid16** [comment]
Can I please work on this issue?

**Comment by GettyOrawo** [comment]
Hey @divyabaid16 there's[ this](https://github.com/publiclab/plots2/issues/4971)  isuue that's already assigned to you. Mind if i work on this one?

**Comment by gauravano** [comment]
hey @GettyOrawo, you can start working on this as @divyabaid16 has started with #4971 as per their [comment](https://github.com/publiclab/plots2/issues/4971#issuecomment-471161516) . You both can also work on this together, totally up to you. Thanks!

**Comment by IshaGupta18** [comment]
How's the work going in on this one @GettyOrawo ? Checking in to see if you need any help!

**Comment by IshaGupta18** [comment]
Hey @GettyOrawo are you still working on this one?

**Comment by CleverFool77** [comment]
Hi Is this issue available @gauravano ?

**Comment by gauravano** [comment]
yes @CleverFool77!

**Comment by CleverFool77** [comment]
I would like to work on this. @gauravano
thanks !!

**Comment by gauravano** [comment]
Great!

**Comment by CleverFool77** [comment]
Hi @gauravano I opened a PR https://github.com/publiclab/plots2/pull/5465 for this issue.
thanks !!!

**Comment by gauravano** [comment]
Reviewing!!
