### ISSUE TITLE
ActionView::MissingTemplate

### ISSUE THREAD

**Issue by siaw23** [publiclab/plots2#4969]
We not have error reports from Sentry. Anyone can take this issue since I'm guessing there's not everyone can see these errors as they happen.

https://sentry.io/share/issue/179156b2fed24a60b2eb199657ae7d25/

**Comment by jywarren** [comment]
What's the best way to share the sentry issues? Security concerns w just
posting them, I'd guess? But could we get issues to open automatically from
within sentry if we wanted? Thanks!

**Comment by siaw23** [comment]
We have sensitive data censored out (passwords i know of), if there's any sensitive info other than passwords that I don't know them I think we should add them to `Rails.application.config.filter_parameters` otherwise I think we should be OK with sharing these.

**Comment by GettyOrawo** [comment]
If I can find a way to reproduce this error, I can work on this. Is it claimed already? @siaw23

**Comment by siaw23** [comment]
I have looked at this error yet as there are many others but you can take a shot @GettyOrawo

**Comment by jywarren** [comment]
@siaw23 here's an option for public display? 

https://github.com/getsentry/sentry-github

**Comment by gauravano** [comment]
Hey @GettyOrawo, are you working on this one? Thanks!

**Comment by siaw23** [comment]
@jywarren yeah that's perfect!
