### ISSUE TITLE
New accounts should not allow links on profile pages

### ISSUE THREAD

**Issue by Fastie** [publiclab/plots2#497]
To prevent spammers from making profile pages with spam links. This could eliminate spam comments and likes which lure users to the spam profile pages.

**Comment by gauravano** [comment]
Hey @Fastie, do you want us to restrict new users from adding links to their bio? Thanks!

**Comment by ebarry** [comment]
Hi @Fastie , you've been right for so many years on this issue! Slowly we are catching up and we now have a plan to hide ALL content from ANY new profile created until that profile has submitted some content that has been approved by a moderator. I'm closing this issue in favor of the current plan and take this opportunity to say that we appreciate you Chris! 

Current Plan: https://github.com/publiclab/plots2/issues/6584
