### ISSUE TITLE
Make questions bar graph responsive

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#4970]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: 
At https://publiclab.org/stats the `questions asked  vs questions answered` bar graph is not responsive on smaller screens.

Update https://github.com/publiclab/plots2/blob/master/app/views/stats/_range.html.erb#175 defines a specific width. Lets change this to a percentage.
`width: '90%',`

After changing the view, also attach the screenshot of updated view in the PR. (You probably have to go on responsive design mode by pressing Ctrl+shift+M)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by vansjyo** [comment]
Hi, I would like to work on this isssue.

**Comment by cesswairimu** [comment]
Awesome, go ahead @vansjyo

**Comment by divyabaid16** [comment]
Can I work on this issue?

**Comment by karunagoyalk** [comment]
Hey ! I want to work on this issue

**Comment by cesswairimu** [comment]
Sorry @divyabaid16  and  @karunagoyalk  already claimed let me see I can create some issues for you both

**Comment by vansjyo** [comment]
Thanks @cesswairimu

**Comment by divyabaid16** [comment]
Thank you! Please assign me some other issue. @cesswairimu
