### ISSUE TITLE
Make move back and front arrows responsive

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#4971]
Created specifically for @divyabaid16
### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: 
At https://publiclab.org/stats the arrows are not aligned  well on smaller screens.
![arrows](https://user-images.githubusercontent.com/17081074/54068447-e1407380-425d-11e9-8b40-b525b481e0df.png)

Update 
* Remove https://github.com/publiclab/plots2/blob/master/app/views/stats/_range.html.erb#L97-L99 and replace with
```
 <div class="row">
<h5> Move back or forward using the buttons below </h5>
 <div class="col-md-4 col-md-offset-2">
```

* Change https://github.com/publiclab/plots2/blob/master/app/views/stats/_range.html.erb#L130-L132 to 
```
</div>
<div class="col-md-3">
```

* Add two divs on https://github.com/publiclab/plots2/blob/master/app/views/stats/_range.html.erb#L165
```
 </div>
</div>
```

After changing the view, also attach the screenshot of updated view in the PR. (You probably have to go on responsive design mode by pressing Ctrl+shift+M)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

**Comment by Anjalizi** [comment]
hi, i would like to take up this issue.

**Comment by GettyOrawo** [comment]
Has anyone claimed this?

**Comment by cesswairimu** [comment]
Was created for @divyabaid16 unless he wants to give it up to someone else

**Comment by divyabaid16** [comment]
Thank you @cesswairimu 
I'm looking forward to work on this.

**Comment by cesswairimu** [comment]
@gettyorawo @Anjalizi will try get issues for u both later today

**Comment by GettyOrawo** [comment]
Alright will be waiting. Thank you!
