### ISSUE TITLE
Align download as buttons on smaller screens

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#4972]
Created specifically for @karunagoyalk
### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: 
At https://publiclab.org/stats the download as buttons are not well aligned(To see this locally login as admin) are not aligned  well on smaller screens.
![download](https://user-images.githubusercontent.com/17081074/54068806-b0623d80-4261-11e9-8067-72fa3aceba30.png)

https://github.com/publiclab/plots2/blob/master/app/views/stats/_range.html.erb#L32-L94

Update 
* Remove https://github.com/publiclab/plots2/blob/master/app/views/stats/_range.html.erb#L32-L33 and replace with
```
 <div class="row">
 <div class="col-md-4 col-md-offset-2">
```

* Replace https://github.com/publiclab/plots2/blob/master/app/views/stats/_range.html.erb#L64-L66
```
</div>
&emsp;
<div class="col-md-3">
```
* Add two divs after line https://github.com/publiclab/plots2/blob/master/app/views/stats/_range.html.erb#L94
```
 </div>
</div>
```

After changing the view, also attach the screenshot of updated view in the PR. (You probably have to go on responsive design mode by pressing Ctrl+shift+M)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

**Comment by cesswairimu** [comment]
@karunagoyalk here you go

**Comment by GettyOrawo** [comment]
Hello @cesswairimu has is this issue already claimed?

**Comment by gauravano** [comment]
Hey @GettyOrawo, this issue was created for @karunagoyalk as they were searching for an issue to take on. Are you looking for a FTO?

**Comment by karunagoyalk** [comment]
@cesswairimu @gauravano thanks! I will work on it

**Comment by helenatxu** [comment]
Hi I am an Outreachy applicant, could I be assigned to this issue to work on? Or maybe you have another issue you could assign me to start working :) Thanks @gauravano

**Comment by cesswairimu** [comment]
Hi @karunagoyalk how is this coming along?

**Comment by karunagoyalk** [comment]
@cesswairimu hey! Actually i faced some problem while installing and building the project.But I am trying , i will get back to you in some time with PR

**Comment by cesswairimu** [comment]
Okay cool. rem to checkout https://github.com/publiclab/plots2/issues/3840 to see if there is an error you are getting that was solved there or add a comment with your error and we can try and help

**Comment by karunagoyalk** [comment]
Hey! cesswairimu I have mailed for Free invite for cloud9, But I did not get any response yet!

**Comment by cesswairimu** [comment]
Hey @karunagoyalk Not sure who approves this but let me find out. Did you have installations problems? Maybe you can edit it on github and I will help add the screenshot for you?

**Comment by karunagoyalk** [comment]
Hey! @cesswairimu I have done the editing on github! please help me in adding screnshot.

**Comment by cesswairimu** [comment]
cool, on it

**Comment by cesswairimu** [comment]
Hey @karunagoyalk  could you create a new branch.
go here 
![Screenshot from 2019-03-17 21-38-51](https://user-images.githubusercontent.com/17081074/54496164-50246900-48fd-11e9-9432-d8e3e609972a.png)

and type `fix-download-buttons` when the create blue highlight comes click on it..so we can make a pull request from that branch. Thanks

**Comment by karunagoyalk** [comment]
Hey @cesswairimu I have created the branch,as per you suggested me to do!

**Comment by cesswairimu** [comment]
Awesome seen it...one last thing I want you to make the pull request. just go here https://github.com/karunagoyalk/plots2/tree/Fix-download-buttons then click the `Compare` button on the right side. Then just click the `create pull request` green button then we are set

**Comment by karunagoyalk** [comment]
Hey @cesswairimu what is this?
![Screenshot](https://user-images.githubusercontent.com/16883717/54536976-b7065880-49b7-11e9-80d7-248ddb806fee.png)

**Comment by karunagoyalk** [comment]
@cesswairimu Hey! I am new to open source, please help me , what to do here as I have not added any Screenshot
![Screenshot from 2019-03-18 20-09-45](https://user-images.githubusercontent.com/16883717/54538275-fcc42080-49b9-11e9-8414-5073f0d570e7.png)

**Comment by cesswairimu** [comment]
I will add it for you just now...awesome creating a pull request :tada:

**Comment by cesswairimu** [comment]
Hey @karunagoyalk added the screenshot and left a comment. You can edit this by going here https://github.com/publiclab/plots2/pull/5152/files an then hit the edit ![kaykay](https://user-images.githubusercontent.com/17081074/54542659-4a865c00-49ad-11e9-846b-284121e32a06.png)
and change line 33 to `<div class="col-md-4 col-md-offset-1">` after that just commit then we are ready. Thanks

**Comment by karunagoyalk** [comment]
@cesswairimu Hey! thanks alot for helping me in creating my first PR.I have done the final editing, Can you please have a look,Let me know!

**Comment by karunagoyalk** [comment]
@cesswairimu Hey! Can you assign me some other issue to work on?

**Comment by cesswairimu** [comment]
Hey @karunagoyalk you can through these issues https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22 and see if there is an issue you can work on. Feel free to ping  me if you get stuck. Also I would suggest you install the code locally or have it set on C9 for easier testing.
