### ISSUE TITLE
Grammatical mistakes in README.md

### ISSUE THREAD

**Issue by shreyateeza** [publiclab/plots2#4974]
# Description
1. "It features a variety of features" can be replaced with "It showcases a variety of features".
2. "We :heart: Open Source and actively participates in various OSS programs" needs to be replaced with "We :heart: Open Source and actively participate in various OSS programs".

**Comment by shreyateeza** [comment]
@SidharthBansal Please validate this issue and assign it to me as a part of my outreachy contribution.

**Comment by shreyateeza** [comment]
@gauravano @Souravirus please assign this issue to me.

**Comment by SidharthBansal** [comment]
Go ahead!!!

**Comment by shubhscoder** [comment]
Hi @shreyateeza , you can just make a pull request for this one and reference this issue there. Thank you so much!
