### ISSUE TITLE
Update CONTRIBUTING.md to add links to issue templates

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/plots2#4978]
## Description
Currently the issue templates for first timer issues and other issues are present in the .github folder.
It would be nice to have links to these from the CONTRIBUTING.md file.
## Solution
Add links to issue templates in the Bug reports and troubleshooting section in the CONTRIBUTING.md file.

**Comment by ananyaarun** [comment]
I'd like to work on this issue after review.

**Comment by gauravano** [comment]
hey @ananyaarun, go ahead :+1:
