### ISSUE TITLE
Change cursor to pointer on hover over the wiki "changes" link

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#4979]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: 
On /dashboard while viewing wiki changes/updates, you might have hovered over the changes link, the below one 
![Screenshot from 2019-03-10 01-24-32](https://user-images.githubusercontent.com/20878070/54076601-c01a6a00-42d3-11e9-82b7-f86ed425c989.png)

Update this line of code https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_wiki.html.erb#L40 such that cursor changes to pointer on hovering over the link
 
After changing the view, also attach the screenshot of the updated view of the dashboard in the PR.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by gauravano** [comment]
This issue is created for @shreyateeza. Thanks!

**Comment by corbettbw** [comment]
May I give it a try?

**Comment by gauravano** [comment]
hey @corbettbw, this issue is created for @shreyateeza as they were waiting for the right issue to start with. I can also create a FTO for you, if you want? Thanks!

**Comment by corbettbw** [comment]
Oh, no worries! And yes, that would be great! Thanks!

**Comment by madeofhuman** [comment]
I'd love an FTO as well, @gauravano. 😃 Thank you.

**Comment by govindjeevan** [comment]
Hello! Can I have a FTO issue too please?

**Comment by shreyateeza** [comment]
@gauravano Thanks! I am working on this.

**Comment by gauravano** [comment]
hey @corbettbw and @govindjeevan, added your name to https://github.com/publiclab/plots2/issues/4963 list and will open FTO for you soon. Thanks!

**Comment by daddyjab** [comment]
Hi, @guavarano, I'd love to work on a FTO for this project,  too!

**Comment by gauravano** [comment]
Hey @daddyjab, I have added your name to the list  - https://github.com/publiclab/plots2/issues/4963 and will ping you soon with a FTO. Thanks!
