### ISSUE TITLE
The popover does not close down unless clicked specifically again

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#4987]
I found this issue while trying to solve the issue #4985 #4986 
## Description 
The popover opens when tag pill is clicked, but it does not closes down unless clicked specifically again on same pill. If a new tag is added or user clicks on any other thing, it still doesn't close down. 

## Current Behaviour
![Screenshot from 2019-03-10 19-37-59](https://user-images.githubusercontent.com/26685258/54086130-4e422f00-436c-11e9-8082-baf6d85de1b4.png)

![hh](https://user-images.githubusercontent.com/26685258/54085712-efc68200-4366-11e9-9f1f-4dc216c4aea4.gif)

![gg](https://user-images.githubusercontent.com/26685258/54084556-2e087500-4358-11e9-8ff1-4753d6d55968.gif)

## Expected Behaviour 
A popover should close down if the user clicks anywhere on screen. A user should not have need to click on tag pill again to close it.

**Comment by gauravano** [comment]
Hi @CleverFool77, you are doing awesome work with all the bug fixes, issues, etc  :100: . How about opening some FTO to welcome new people, as many people are waiting for getting started - https://github.com/publiclab/plots2/issues/4963?

Thanks!

**Comment by CleverFool77** [comment]
Sure @gauravano :).

**Comment by gauravano** [comment]
Awesome!

**Comment by gauravano** [comment]
closing this. Refer https://github.com/publiclab/plots2/issues/5072#issuecomment-472974341. Thanks!
