### ISSUE TITLE
Improve the UI of readmore blogs button

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#4990]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** . 
* Change the UI of Readmore button so that it can be differentiated from individual notes Readmore button.

![Screenshot from 2019-03-10 20-34-04](https://user-images.githubusercontent.com/26685258/54087215-b6960e00-4376-11e9-9f5c-7fb8d204a415.png)

* Update will be done in plots2/app/views/home/home.html.erb
* Go for a design similar as given image in `ask a question` button but smaller in size.

![Screenshot from 2019-03-10 23-08-48](https://user-images.githubusercontent.com/26685258/54089030-60cb6100-438a-11e9-9119-cbcea8a8765d.png)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by CleverFool77** [comment]
@gauravano Is this issue correct ?

**Comment by gauravano** [comment]
You have to add link to the line of code new contributor has to modify and what should be the new design.

**Comment by CleverFool77** [comment]
Ohk. I'll add it.

**Comment by CleverFool77** [comment]
@gauravano Updated the issue :)

**Comment by gauravano** [comment]
@coderbeetle interested in solving this one? Thanks!

**Comment by kuja24** [comment]
@gauravano Can I work on this one?

**Comment by gauravano** [comment]
hey @kuja24, this issue is assigned to @coderbeetle as they're waiting for their first-issue for some time. I have added your name to https://github.com/publiclab/plots2/issues/4963 and we'll ping you soon with a FTO. Thanks!

**Comment by gauravano** [comment]
You can also start with other `help-wanted` issues, and if face doubts, feel free to ask us. Thanks!

**Comment by Aarabhi2017** [comment]
Hi @gauravano , Could you please  add me as well? I would like to work on a FTO too

**Comment by gauravano** [comment]
Hey @Aarabhi2017, added your name too :+1:

**Comment by coderbeetle** [comment]
> @coderbeetle interested in solving this one? Thanks!
Ah, sorry I haven't been on here for a few days! An emergency with my cat occurred and I've been busy with frequent visits to the vet. I'll look into the issue very soon! Thank you and sorry for the inconvenience :)

**Comment by gauravano** [comment]
No issue!

**Comment by coderbeetle** [comment]
I made a pull request on the issue, could it please get reviewed? :)

**Comment by deboragaleano** [comment]
I believe this issue is still open and I would like to work on this, I'm an Outreachy applicant.

**Comment by jywarren** [comment]
My apologies for the slow response; we would love your help with this. Thank you!

@coderbeetle i'm sorry we didn't get this completed with you. If you circle back we'd be happy to help you find another issue to work on!

**Comment by jcads** [comment]
Can I still work on this issue?

**Comment by Priyaraj17** [comment]
Is this issue still open? May I work on it.

**Comment by cesswairimu** [comment]
I believe with the new dashborad this value is no longer valid. Closing this. Thanks all
