### ISSUE TITLE
Fix comment design 

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#4991]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

The options on the comment are going out of the parent div as shown :point_down: 
![comment_design](https://user-images.githubusercontent.com/20878070/54087409-9c5d2f80-4378-11e9-89e3-057e110e4ae4.png)

- [ ] 📝 **Update**: https://github.com/publiclab/plots2/tree/master/app/views/notes/_comment.html.erb

so that options don't overflow out of parent comment

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by gauravano** [comment]
This issue is created for @nazeem1988. Thanks!

**Comment by Jenniline** [comment]
Hi am Jenniline new to open source and a an outreachy applicant 
 @gauravano please can i work on this task as well or can i be assigned a task to work on here?

**Comment by nazeem1988** [comment]
Hi @gauravano, thanks for the opportunity. I’m currently at work and cannot be home till evening (next 8 hours). If you’ve some more issues come tomorrow then I would appreciate you give this issue to @jenniline. Even I come from same background. Very new to open source. Thanks!

**Comment by Jenniline** [comment]
Thanks @nazeem1988

**Comment by gauravano** [comment]
Thanks @nazeem1988! I will try to open a new one for you soon. And, I hope, both of you have a nice time contributing and starting your Open Source :globe_with_meridians: journey with us. 

Thanks!

**Comment by Manvi07** [comment]
Hi @gauravano I am an outreachy applicant and new to open source. I would like to work on this issue. Kindly assign it to me if no one else is working on it.

**Comment by gauravano** [comment]
Hi @Manvi07, this issue is assigned to @Jenniline and they'll start working on this very soon. You can go through other issues at https://github.com/publiclab/plots2/issues and start working on those you find interesting(which are unassigned).

 If you want we can add your name to the list - https://github.com/publiclab/plots2/issues/4963 and can ping you whenever FTO is ready for you?

Also, do checkout - https://github.com/publiclab/plots2/issues/5022

Thanks!

**Comment by PritiShaw** [comment]
Hi @gauravano 
I am an outreachy aspirant and new to open source. I would like to work on this issue. Kindly assign it to me if no one else is working on it.

**Comment by gauravano** [comment]
Hey @Jenniline, just checking if you need any help here? Also, if you're not interested anymore we can re-assign this task. Thanks!

**Comment by PritiShaw** [comment]
I am unable to replicate the error, Can you please say what browser,os you are using, @gauravano 
I am on Chrome, Ubuntu14

**Comment by gauravano** [comment]
Hi @PritiShaw,  actually this issue seems resolved in https://github.com/publiclab/plots2/pull/5238/ and I guess some part in new comments+answer combining PR. Thanks for checking here and I think we can close this one.
