### ISSUE TITLE
Add tooltip over delete button of comment

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#4992]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

Add the tooltip "Delete comment" for comment delete button just like we have for other options on the comment

![tooltip_add](https://user-images.githubusercontent.com/20878070/54087533-cb27d580-4379-11e9-815b-37b96f33b610.gif)
  

- [ ] 📝 **Update** You need to update these lines for implementing the change - https://github.com/publiclab/plots2/blob/master/app/views/notes/_comment.html.erb#L87-L89

Also, attach the screenshot of the updated view by going over to any research note/question on localhost and taking a screenshot of the comment posted over there

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by gauravano** [comment]
This issue is created for @cassianoblonski. Thanks!

**Comment by cassianoblonski** [comment]
i'm working on this.

**Comment by cassianoblonski** [comment]
its fine if I add the tooltip over edit comment button too, or better leave for another first timer?

**Comment by gauravano** [comment]
> its fine if I add the tooltip over edit comment button too, or better leave for another first timer?

Let's keep it for another first-timer.

> edit: I followed the installation doc on the Readme and got a problem on:
Standard Installation
4. Install gems with bundle install --without production mysql
needed to change to 'mysql2' to work, otherwise I got the error "mysql2 is not part of the bundle. Add it to your Gemfile" (the mysql2 is on the Gemfile under production group)
I can fix the Readme too if needed just open a issue or reply me here and then I create the PR with both fixes or with your instructions.

The fix has been merged recently, so update your branch and then try. Thanks!

**Comment by gauravano** [comment]
@cassianoblonski

**Comment by aggarwal19** [comment]
Hi @gauravano , Is this issue still open to work ?
and may i solve this issue ?

**Comment by gauravano** [comment]
Hi @aggarwal19 , this issue is assigned to @cassianoblonski . But, we would love to have your help with other issues, you can find more issues at https://code.publiclab.org/#r=all and if you can't find any unclaimed issue there, feel free to comment below or in the Gitter channel - https://gitter.im/publiclab/publiclab, so that we can try to help you in finding a good issue to start with or maybe create a new issue for you. 

Thanks!

**Comment by aggarwal19** [comment]
@gauravano  ,  it would great if you could provide me the first timer only issue .
Thank you

**Comment by gauravano** [comment]
Added your name to the list @aggarwal19. Will ping you soon with an FTO. Thanks!

**Comment by Jenniline** [comment]
Hi I am an Outreachy applicant new to open source and willing to learn.  @gauravano can i work on this issue too or be assigned a task to on it?
