### ISSUE TITLE
Add "Pick a reaction" text to reaction dropdown on comment

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#4993]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

Add the text "Pick a reaction" in reaction dropdown just like GitHub have :point_down: 
![reaction_text](https://user-images.githubusercontent.com/20878070/54087684-5f466c80-437b-11e9-8cd2-4fca4531cd0f.png)

Our current reaction dropdown look :point_down: 
![current_pl](https://user-images.githubusercontent.com/20878070/54087698-7f762b80-437b-11e9-9f8a-cfb0fd2c1914.png)

Feel free to optimize UI of dropdown further too.

- [ ] 📝 **Update** You need to update these lines for implementing the change - https://github.com/publiclab/plots2/blob/master/app/views/notes/_comment.html.erb#L96-L106

Also, attach the screenshot of the updated view by going over to any research note/question on localhost and taking a screenshot of the comment posted over there

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by gauravano** [comment]
This issue is created for @TANGL3SIT3S. Thanks!

**Comment by letnewKid** [comment]
Hello, I'm new to this codebase and to contributing to open source. Is this issue already claimed and if so can I assist?

**Comment by Jaya738** [comment]
Is this issue claimed or I can still work on it?

**Comment by gauravano** [comment]
Hi @letnewKid @Jaya738 this issue is assigned to @TANGL3SIT3S as they were waiting for their FTO for some time. But, we would love to have help from both of you too. 

@Jaya738 I think you got FTO to work with, right?

@letnewKid you can work with @@TANGL3SIT3S on this one, if they don't mind. Or, I can create a new FTO for you too. Thanks!

**Comment by letnewKid** [comment]
@gauravano I'm an outreachy applicant and I guess don't know if it counts if I work with someone when I record my contribution. But I will reach out to @TANGL3SIT3S.

**Comment by gauravano** [comment]
Oh! Let's not complicate the case for Outreachy organizers. I will create a separate issue for you.  Added your name to the list - https://github.com/publiclab/plots2/issues/4963 and will ping you soon. Thanks!

**Comment by letnewKid** [comment]
Thank you so much Gauravano.

**Comment by Jenniline** [comment]
Hello @gauravano I am an outreachy applicant new to open source and willing to learn. Please can i have a FTO task as well.

**Comment by metonymic-smokey** [comment]
@gauravano is this issue still open? Would be willing to try and work on it! 

Thanks!

**Comment by jywarren** [comment]
Yes it is! Also, the styling of the display of reactions is a little bit
irregular now, as compared to GitHub's. We'd appreciate any help with the
styling as well!

**Comment by Shreets** [comment]
Hey @jywarren , i am an Outreachy applicant. I would like to work on this issue if it is still open. Could you please assign it to me. 
if not, I am willing to be assigned an open issue that need being resolved.
Thanks!

**Comment by Shreets** [comment]
Hello
i am an Outreachy applicant. I would like to work on this issue if it is still open.
I shall be picking this issue to work on
Thanks!

**Comment by Shreets** [comment]
Hello, I am an Outreachy applicant and I am picking this issue.

**Comment by jywarren** [comment]
Great, thank you so much!
