### ISSUE TITLE
Bootstrap tooltip data placement parameter is wrong

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/plots2#4995]
## Description
The comment pop up on hovering over the navbar in the donate page goes out of screen.

## Current Behavior
![new2old](https://user-images.githubusercontent.com/32260628/54088927-21504500-4389-11e9-9f62-796c41d35754.png)

## Expected Behavior
The pop up comment stays within the screen.
This can be achieved by changing the placement parameter from 'top' to 'bottom'.

**Comment by ananyaarun** [comment]
I'd like to fix this issue :)

**Comment by gautamig54** [comment]
@ananyaarun I am able to solve this issue and have created PR

**Comment by ananyaarun** [comment]
@gautamig54 Hi, I have solved this issue while creating it itself :) was waiting for @gauravano to approve of the issue to open my PR. Thanks! If this is your first time contributing look for some First timers issue. Claim it, get it assigned and then make your PR. Good luck :+1:

**Comment by gautamig54** [comment]
@ananyaarun thanks!

**Comment by gauravano** [comment]
hey @ananyaarun, as tooltips for all the options open at top on wiki so instead of changing the position, do you think we can work to change the width of the tooltip to accommodate the text in minimum lines?

**Comment by gauravano** [comment]
Also, this bug comes when there is no main image on the wiki so we might want to ignore it. Let's ask @jywarren as they spend many hours on the website. 

Thanks!

**Comment by ananyaarun** [comment]
@gauravano Even i thought this problem goes if a main image is present, but that isnt the case as seen here in the public labs site.
![mainpage](https://user-images.githubusercontent.com/32260628/54128036-2963bf80-4431-11e9-809d-7ec7fac933d5.png)

Sure changing the width is indeed a great idea but only the content in the tooltip varies so which would be optimal is a bit of trial and error.

**Comment by CleverFool77** [comment]
But I guess the screenshot you showed is the one popup which is having maximum content length. Others are usually small :thinking: . So it might not matter if you set the width according to it, I guess. I'm not sure, Its an opinion.

**Comment by gauravano** [comment]
1. changing width of tooltip
any other ideas?

**Comment by ananyaarun** [comment]
@gauravano , i'll give that a try.

**Comment by ananyaarun** [comment]
@gauravano , changing width would mean we override the default CSS of bootstrap. Is that preferable ? Cuz making the width bigger/different only for 1 tag is not a good solution , also making all of them bigger isnt either as they have different content length. So do u think its better to change the width of all or change only for the one going out of screen or avoid changing and make all the tooltip pop ups open at the bottom ?

**Comment by jywarren** [comment]
Oh that would be great. You might also make a first-timers-only issue from
it if you're interested! It could be fun to use this to welcome someone
else into the community as well!

**Comment by ananyaarun** [comment]
@jywarren Sure I'll make this a new FTO issue :)
Also @gauravano just confirming before i open an issue , so the fix for this in the newcomers issue would be to change all tooltips on the page to pop up to the bottom right ?

**Comment by ananyaarun** [comment]
@jywarren , @gauravano  an interesting finding in this regard. The tooltips are actually not designed in a consistent manner right now. Just noticed both on my local installation and public labs page that most actually pop upward while some pop downwards like these on the Donate page. It is the same comment content that pops up/down on different pages.

![popup](https://user-images.githubusercontent.com/32260628/54180068-a68a4580-44c0-11e9-863f-26da5208b0c4.png)

![new2old](https://user-images.githubusercontent.com/32260628/54180100-c588d780-44c0-11e9-8463-4d36145b2f4c.png)

I'll open an issue regarding this, we can discuss further there.

**Comment by ananyaarun** [comment]
Closing this issue as 2 FTO's that fix this have been opened.

**Comment by gauravano** [comment]
Great!
