### ISSUE TITLE
Clean up en.yml

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#4997]
Created specifically for @Anjalizi

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

Problem: With the new dynamic stats page there are a few thing we are not using on https://github.com/publiclab/plots2/blob/master/config/locales/en.yml
 Lets clean up this

- [ ] 📝 **Update**: 
Remove this blocks of code
*  https://github.com/publiclab/plots2/blob/master/config/locales/en.yml#L250-L271
*  https://github.com/publiclab/plots2/blob/master/config/locales/en.yml#L276-L281
*  https://github.com/publiclab/plots2/blob/master/config/locales/en.yml#L283-L288

After changing this, attach the screenshot of `/stats` in the PR.  Just to make sure we didn't break anything on this page

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

Thanks!

**Comment by cesswairimu** [comment]
@Anjalizi here you go.

**Comment by Anjalizi** [comment]
thank you. I shall start with this :)

**Comment by Jaya738** [comment]
Is there anyone already done with this

**Comment by Jaya738** [comment]
please review my changes and accept the pull request

**Comment by cesswairimu** [comment]
Sorry @Jaya738 @Anjalizi is working on this one

**Comment by gauravano** [comment]
hey @cesswairimu, thank you for opening FTOs, please also update the list - https://github.com/publiclab/plots2/issues/4963#issue-418960660 whenever you create a FTO for a contributor so all of us can know. Thanks again :100:

**Comment by jywarren** [comment]
Yes, thank you @cesswairimu and @gauravano you're both doing tremendous
work here! And welcome, everyone!
