### ISSUE TITLE
Link to main stats page on tag stats page

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#5001]
Created specifically for @gautamig54
### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: 

- [ ] 📝 **Update**: 
Add link to stats main page on 
https://github.com/publiclab/plots2/blob/master/app/views/tag/stats.html.erb

Update 
After line https://github.com/publiclab/plots2/blob/master/app/views/tag/stats.html.erb#L2, add
```
<h3> Tag statistics for <%= @tags.first.name %> </h3>
<hr>
<%= link_to " See statistics for all contents", stats_path %>
```

After changing the view, also attach the screenshot of updated view in the PR. 

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

**Comment by gautamig54** [comment]
@cesswairimu thanks! I will start working in this issue :)

**Comment by gautamig54** [comment]
I have created a PR solving this issue.
