### ISSUE TITLE
Increase the size of tag

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5004]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** . 
* Increase the size of tag little bit in Featured Topics.

![Screenshot from 2019-03-11 09-39-03](https://user-images.githubusercontent.com/26685258/54099951-e5959980-43e1-11e9-982d-ce2c3f29f104.png)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by Jaya738** [comment]
can I work on this?

**Comment by CleverFool77** [comment]
@Jaya738 I'm not sure whether this issue will get approved. If yes, then you can :).

**Comment by gauravano** [comment]
@jywarren I think we can try a little bigger size. What do you think?  

@CleverFool77 nice work.  please add the link to the file to be changed. Thanks!

**Comment by jywarren** [comment]
Yes we could work on this! Actually that code is stored in the database, not the codebase, but i've made a copy here you can work on. Once it's complete we can copy it back to the admin interface where it's stored, so ping me!

https://publiclab.org/wiki/sandbox-3

**Comment by CleverFool77** [comment]
@gauravano As this is approved, we can assign a first timer looking for issues.

**Comment by gauravano** [comment]
@Jaya738 you want to work on this one?

**Comment by Manvi07** [comment]
Hi @CleverFool77 
I am an outreachy aspirant and new to open source. I would like to work on this issue. Kindly assign it to me if no one else is working on it.

**Comment by CleverFool77** [comment]
@Manvi07 you can go through the issue #4963 and get yourself an issue assigned. :)

**Comment by CleverFool77** [comment]
@Jaya738 Are you still working on this issue. If yes, then you can open a draft PR or you ask for help in group if you came across some problem or If not, then there is no problem. As opensource is always a place where another can start from where you've left and we can assign a different contributor for this.

**Comment by IshaGupta18** [comment]
We're going to open this up to new contributors -- thanks so much for your help, and please speak up if you'd like to continue! New contributors - this is now available to claim. Thanks, all!

**Comment by elshaek** [comment]
Hi, I would like to work on this, but looking at a previous comment, it seems like the code is not in the codebase. How can I get access to the code?

**Comment by UmairJibran** [comment]
can I please claim this issue? it's my first time contributing to this repo (or any community open source repo at all)

**Comment by jywarren** [comment]
Hi all! I think that, since this is a little stale now, I'm going to go ahead and close it up! I appreciate your help and please chime in on the Weekly Check-In if you'd like a new first-timers issue! https://github.com/publiclab/plots2/issues/8113
