### ISSUE TITLE
profile page links not working

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#5008]
Hello, 
I recently used some of the hyperlinks on top of a profile page and found they were not working. Specifically these ones: 

<img width="741" alt="Screen Shot 2019-03-11 at 10 10 03 AM" src="https://user-images.githubusercontent.com/7490478/54130087-1d064500-43e6-11e9-96e7-13afce6b46dc.png">

They bring you to this error page: 

<img width="1034" alt="Screen Shot 2019-03-11 at 10 09 51 AM" src="https://user-images.githubusercontent.com/7490478/54130123-2b546100-43e6-11e9-8c2b-42d4970c7dc0.png">

Best!
-Stevie

**Comment by madeofhuman** [comment]
Can I work on this if nobody is picking it?

**Comment by gauravano** [comment]
@madeofhuman we would love to have your help. Actually, would you be interested in dividing this issue in parts and then opening them as a FTO as there are many new people who are looking to get started -https://github.com/publiclab/plots2/issues/4963 ? thanks!

**Comment by madeofhuman** [comment]
Sure thing, @gauravano. 😄

**Comment by madeofhuman** [comment]
@gauravano it's just one fix that needs to be applied here, from what I can see. As it is, it'd already an FTO issue.

**Comment by madeofhuman** [comment]
Error source:
<img width="1374" alt="Screenshot 2019-03-11 at 9 58 50 PM" src="https://user-images.githubusercontent.com/7345686/54162561-2af3ae80-4456-11e9-8dc1-faf18dd5eee3.png">

Desired outcome:
<img width="1374" alt="Screenshot 2019-03-11 at 10 38 15 PM" src="https://user-images.githubusercontent.com/7345686/54162602-55456c00-4456-11e9-956e-fb42abb7b4bf.png">
<img width="1374" alt="Screenshot 2019-03-11 at 10 38 33 PM" src="https://user-images.githubusercontent.com/7345686/54162579-3e067e80-4456-11e9-99fa-2e2bffce9548.png">

File to edit:
[_tags_popover.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/tag/_tags_popover.html.erb)

**Comment by madeofhuman** [comment]
@gauravano here it is: https://github.com/publiclab/plots2/issues/5021

**Comment by IshaGupta18** [comment]
Since this issue has now been completed through FTO #5021 , I am closing it! Thanks a lot everyone!
