### ISSUE TITLE
Make README.md consistent by capitalizing first letter of all bullet points

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/plots2#5016]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** Capitalize bullet points present in L17-L24 in the file [README.md](https://github.com/publiclab/plots2/blob/master/README.md) in the `Plots2` repository to make it consistent with the other bullet points.

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by ananyaarun** [comment]
@gauravano , A simple change in README.md to make it look more structured. I think this makes a good FTO issue as well !

**Comment by gauravano** [comment]
Hey @corbettbw, interested in working on this one?

**Comment by madelinejones** [comment]
Could I possibly claim this one?

**Comment by gauravano** [comment]
hey @madelinejones, we would love to have your help with other issues. @corbettbw was looking for an issue to start with for some time so let's give them a chance to work on this.

You can have a look at other issues at https://github.com/publiclab/plots2/issues/ and if find any interesting, then start working on that (if that's not assigned). Also, if you think, a particular issue is little complicated and you need some links to start with, then feel free to mention me or @jywarren there. 

Thanks!

**Comment by ananyaarun** [comment]
@corbettbw are you working on this one ? Feel to ask ask for help if you get stuck :) Thanks !

**Comment by corbettbw** [comment]
Yes! I will give it a try, sorry for the delay!
