### ISSUE TITLE
First-timers-bot and welcomebot seem not to be working now? 

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5018]
See how we connected to these bots here: https://github.com/publiclab/plots2/issues/3681

But neither seems to be working at the moment!

I filed an issue here -- https://github.com/hoodiehq/first-timers-bot/issues/212#issuecomment-471336786

and heard back that that logs for first-timers-bot can be found here:

https://zeit.co/deployments/first-timers-bot.now.sh/logs

**Comment by jywarren** [comment]
@publiclab/reviewers @publiclab/plots2-reviewers this is a bit concerning but I can't see anything wrong!

**Comment by jywarren** [comment]
Noting that it works on MapKnitter: https://github.com/publiclab/mapknitter/issues/396

**Comment by jywarren** [comment]
I thought maybe i figured it out when i saw that our template had been trying to label with `help-wanted` instead of `help wanted` and we deleted the hyphenated version a few months ago -- so i changed it. https://github.com/publiclab/plots2/blob/master/.github/first-timers.yml#L5

But I tried making a new branch named `first-timers-tag-toggle-2` and a new issue wasn't made. Maybe we have to push it to trigger? Or maybe this wasn't the issue after all...

**Comment by jywarren** [comment]
Think i figured it out! The template was moved in this PR - https://github.com/publiclab/plots2/pull/3941

 i think we can move it back to `.github` and it'll start working again!

**Comment by jywarren** [comment]
Hmm, that didn't work...

**Comment by jywarren** [comment]
OK logs are showing: https://zeit.co/deployments/first-timers-bot.now.sh/logs

```
2019-03-13T19:04:26.523Z probot:first-timers:publiclab/mapknitter TypeError: state.api.repos.getContent is not a function
```

**Comment by jywarren** [comment]
Fixed with help from the Hoodie team!!!!!!

**Comment by jywarren** [comment]
Reopening to address the Welcomebot issue too.

**Comment by jywarren** [comment]
Noting that welcomebot seems to have been offline since November 2018? But is still running in MapKnitter: https://github.com/publiclab/plots2/search?o=desc&q=share+demonstrating+the+issue&s=created&type=Issues

Last change to the file was end of November: https://github.com/publiclab/plots2/commits/master/.github/config.yml

aha!

**Comment by jywarren** [comment]
OK, testing, but I believe there had been a `+` character added that was causing it to fail. Re-added!

https://github.com/publiclab/plots2/commit/a41bb2f03ea345dffda061af0f24d84cc487aa10

**Comment by jywarren** [comment]
Hmm, i just tried again at https://github.com/publiclab/plots2/tree/first-timers-digest-email and it didn't open...

**Comment by jywarren** [comment]
```
2019-03-21T17:37:05.345Z probot:first-timers:publiclab/plots2 getting commit "e0132925784e48f7126a0d419ca5c47d2acc1f25"
2019-03-21T17:37:09.472Z probot:first-timers:publiclab/plots2 found commit "Add full paths to email digest images". Changed file "app/views/subscription_mailer/send_digest.html.erb" Found branchUrl "https://github.com/publiclab/plots2/blob/master/app/views/subscription_mailer/send_digest.html.erb"
2019-03-21T17:37:09.472Z probot:first-timers:publiclab/plots2 creating issue...
2019-03-21T17:37:14.999Z probot:first-timers:publiclab/plots2 HttpError: Empty value for parameter 'number': undefined
```

**Comment by jywarren** [comment]
Opened https://github.com/hoodiehq/first-timers-bot/issues/213

**Comment by cesswairimu** [comment]
Looks like we forgot to close this. Thanks all
