### ISSUE TITLE
Make the hover drop downs in the navbar instead of click.

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#5019]
The main navbar has dropdowns which open when clicked. I suggest that it will be better if there is hover dropdowns as it is more convenient and user friendly. 
![Screen Shot 2019-03-11 at 11 02 09 PM](https://user-images.githubusercontent.com/35326753/54160510-bfb9d480-4475-11e9-8346-969af38b919f.png)

**Comment by gautamig54** [comment]
@jywarren I would like to work on this issue if it gets added as one. Thanks!

**Comment by jywarren** [comment]
Sure! This'd be great!

**Comment by gautamig54** [comment]
Thanks @jywarren ! I'll resolve this and file a PR.

**Comment by jywarren** [comment]
awesome :-)

**Comment by CleverFool77** [comment]
@jywarren should I do the same for this issue that tag will open on hover not on click. #4987

**Comment by jywarren** [comment]
Hmm, i guess so - can you open a popover on hover? And would it be hard to
move the mouse into the popover without it closing suddenly when you move
the mouse? If it works smoothly, then sure!
