### ISSUE TITLE
Add "toolkits" to "projects" dropdown menu

### ISSUE THREAD

**Issue by sdosemagen** [publiclab/plots2#502]
- Create wiki that links to frac sand, homebrew, urban waters and gardening toolkits
- Toolkits is added to projects dropdown menu (perhaps under places, but open for suggestions) and links to this wiki page.

**Comment by jywarren** [comment]
Great - ping me again (here or by email) when the wiki page is ready, post
the URL, and we can do this. Super.

**Comment by ebarry** [comment]
The page is updated with links. https://publiclab.org/wiki/toolkits 
Design team, want to advise on a lead image? Otherwise gtg.

**Comment by jywarren** [comment]
Cool -- I don't think this page yet has enough information for a top-level
menu item, though; i.e. what's a toolkit? Is it different from a tool? Why
are they made, what are they for? Who made them?
