### ISSUE TITLE
Write unit tests for parts of Reply By Tweet feature

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5020]
There's a new Reply by Tweet feature, but it needs some unit tests! @namangupta01 maybe you could help people get started on this? 

https://github.com/publiclab/plots2/blob/f4d965c94de289ef3244bc7eb3d555ef4edcfbe0/app/models/comment.rb#L347-L441

Any of these methods could use a unit test, in this file: https://github.com/publiclab/plots2/blob/master/test/unit/comment_test.rb

Here's an example of a unit test! https://github.com/publiclab/plots2/pull/4571/files

We'd love help with this!

**Comment by divyabaid16** [comment]
Can I work on this?

**Comment by shreyateeza** [comment]
@namangupta01 @jywarren I would like to work on this issue. How can I proceed?

**Comment by jywarren** [comment]
Hi! I think more than one person could write a unit test since there are
multiple issues here. I've actually just written up about unit tests a bit
in this issue -- perhaps the resources there could help you get started?
https://github.com/publiclab/plots2/issues/3480#issuecomment-471594589

**Comment by namangupta01** [comment]
Hi Shreya, Please go ahead. There are multiple function in comment model.
You can write unit test of each function. And since there are multiple
functions, multiple people can work on it.
Let me know if you have any questions and need help.
Thanks
