### ISSUE TITLE
Fix hyperlinks not working on profile page

### ISSUE THREAD

**Issue by madeofhuman** [publiclab/plots2#5021]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step
* [ ]  🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
* [ ]  📝 **UPDATE**
Change `line 31` of (https://github.com/publiclab/plots2/blob/master/app/views/tag/show.html.erb)  to:
```
<% if !@related_tags.nil? %>
    <p> <%= render partial: 'tag/subscribe_button', locals:{tags: @related_tags } %></p>
  <% end %>
```
to ensure that an iteration does not occur on a nil value (that is, `tags.each` should only run when `tags` has a non-nil value).
**Current Behavior**
Clicking on the hyperlinks to a user's questions and activities on their profile page breaks the app and opens an error page.
<img width="1374" alt="Screenshot 2019-03-11 at 10 38 15 PM" src="https://user-images.githubusercontent.com/7345686/54162602-55456c00-4456-11e9-956e-fb42abb7b4bf.png">
<img width="1374" alt="Screenshot 2019-03-11 at 9 58 50 PM" src="https://user-images.githubusercontent.com/7345686/54162561-2af3ae80-4456-11e9-8dc1-faf18dd5eee3.png">

**Expected Behavior**
Clicking on the hyperlinks on a user's profile page ("questions", for example) should take you to a page that shows the questions or activities the user has made.
<img width="1374" alt="Screenshot 2019-03-11 at 10 38 15 PM" src="https://user-images.githubusercontent.com/7345686/54162602-55456c00-4456-11e9-956e-fb42abb7b4bf.png">
<img width="1374" alt="Screenshot 2019-03-11 at 10 38 33 PM" src="https://user-images.githubusercontent.com/7345686/54162579-3e067e80-4456-11e9-99fa-2e2bffce9548.png">

* [ ]  💾 **Commit** your changes
* [ ]  🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

* [ ]  🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?
Leave a comment below!

**Comment by madeofhuman** [comment]
@gauravano here's the issue.

**Comment by helenatxu** [comment]
Hi I am an Outreachy applicant, could I be assigned to this issue to work on? Or maybe you have another issue you could assign me to start working :) Thanks @gauravano

**Comment by cesswairimu** [comment]
@madeofhuman good catch, but to make it a `first-timer-only` you have to give the the actual code to be written and links to where specifically it should be. Please do that on the description or I can help with that, juts let me know. @helenatxu awesome you can take up this issue once its ready

**Comment by madeofhuman** [comment]
@cesswairimu It's actually just one line of code that needs to be changed to fix everything. If you look at the screenshot of the error page, it's line 4 of [_tags_popover.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/tag/_tags_popover.html.erb)

**Comment by cesswairimu** [comment]
Aha gotcha, thanks @madeofhuman. @helenatxu this is ready you can get started on it...comment below if you get stuck.

**Comment by helenatxu** [comment]
Thank you @cesswairimu!

**Comment by madeofhuman** [comment]
@helenatxu how are you doing with this? If you're running into any problem, don't hesitate to reach out. 😄

**Comment by madeofhuman** [comment]
Hi, @helenatxu. Hope you're all right? How are you getting on with this issue?

**Comment by helenatxu** [comment]
Hello @madeofhuman! Sorry I didn't answer as I didn't see any notification. I think I will /unclaim this issue because I didn't have time yet to start it after a few days. I will come back if I have enough time again. Thank you!

**Comment by jywarren** [comment]
That's ok @helenatxu, maybe @shubhi2000 would like to take this one over for now and we can make one for you when you're ready?  You can always ask and we will make one. 

https://github.com/publiclab/plots2/issues/4963

**Comment by shubhi2000** [comment]
@jywarren sure, I will take this issue and work on it.

**Comment by jywarren** [comment]
great!

**Comment by shubhi2000** [comment]
I added a conditional statement to run tags.each only when tags has a non-null value, and then I created a PR. Out of 3 checks on my PR, 2 checks were successful and 1 check failed. Since, it is my first PR, I didn't know that I need to tick the checkboxes before proposing the PR. So, the check failure is because of not checking the boxes or something else needs to be done with the code? Please help me regarding this.

**Comment by IshaGupta18** [comment]
Okay so I am not sure why this file is being used here in the profile page. This file was just written for multiple tag subscription, and I don't know why it is linked to links in the profile page. Besides, if tags are empty, that is already being checked here:

`<% if @node && !@node.node_tags.empty? && ((current_user && @node.liked_by(current_user.uid)) || !current_user) %>`

Let's try and find out what's happening here

**Comment by IshaGupta18** [comment]
Finally found the bug! The file that needs to be changes here is not `_tags_popover.html.erb`, its `tag/show.html.erb`. The subscribe_button partial is being called there and the nil condition is not being checked there. So I am closing this issue @madeofhuman and will open a new one for this. @shubhi2000 you can go ahead with that one and close your PR for this. Thanks a lot @madeofhuman for pointing this out!

**Comment by shubhi2000** [comment]
@IshaGupta18 okay, thanks.
