### ISSUE TITLE
Pop up messages inconsistent on different sections of the donate page

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/plots2#5027]
## Description
In reference to issue https://github.com/publiclab/plots2/issues/4995
The pop up message on hover along the nav bar on different sections of the Donate page pops up either up or down. The pop ups across sections of donate page even have different height and width of the tooltip.

## Current Behavior

![popup](https://user-images.githubusercontent.com/32260628/54180989-139eda80-44c3-11e9-8476-0aefcb616187.png)

![mainpage](https://user-images.githubusercontent.com/32260628/54181050-51036800-44c3-11e9-91a7-48c78b8df6af.png)

This is a problem noticed in both the local installation and the main page.

## Expected Behavior

The popups must have a fixed width and either always pop upward or always pop downwards on hover.

**Comment by ananyaarun** [comment]
@jywarren , @gauravano  I can either fix this problem with one PR to make tooltips consistent across files or i think it would be better to split it into different new comer issues.

**Comment by gauravano** [comment]
Yes @ananyaarun, breaking in FTO sounds good :+1: Thanks!

Also, please close #4995 after diving in FTO

**Comment by jywarren** [comment]
Great, and i believe you'll find the code for the tooltips in this file!
https://github.com/publiclab/plots2/blob/master/app/views/wiki/_header.html.erb

**Comment by gauravano** [comment]
Closing this as @ananyaarun has broken this as FTOs. Thanks @ananyaaru :100: !
