### ISSUE TITLE
image upload progress bar in/post editor broken

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#503]
When uploading at http://publiclab.org/post, a progress bar no longer appears, though it still does when uploading into comment textareas.

Relevant code here: https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/dragdrop.js

Test at http://publiclab.org/post

**Comment by ananyo2012** [comment]
Fixed in #575

**Comment by jywarren** [comment]
Thanks!
