### ISSUE TITLE
The react button goes out of comment card

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5030]
## Description 
The buttons in the comment card is going out of the card. 

## Current Behaviour 
![Screenshot from 2019-03-12 22-17-00](https://user-images.githubusercontent.com/26685258/54196164-9edd9780-44e6-11e9-90da-b23061957f07.png)
![Screenshot from 2019-03-12 22-18-47](https://user-images.githubusercontent.com/26685258/54196190-ba48a280-44e6-11e9-8839-c9097f4d9212.png)

## Expected Behaviour
It should not go out of comment card.

**Comment by shreyateeza** [comment]
@CleverFool77 I would like to work this issue when validated!

**Comment by gauravano** [comment]
Hi @CleverFool77, this issue is already posted as a FTO - https://github.com/publiclab/plots2/issues/4991. So, closing this one and thanks!

**Comment by CleverFool77** [comment]
Maybe because of different title, I didn't see it in option of similar issues. @gauravano Thanks for pointing it out. :)
