### ISSUE TITLE
Change the social icons border color

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5031]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** . 
* The border and background of buttons in facebook and twitter buttons used is #4267b2 and #1b95e0 which is the main color of palette color followed by facebook and twitter. Let the background color remain same but Change the border hex to #29487d and ##00aced which is also a part of palette too but it shows a difference with background color.

![Screenshot from 2019-03-12 22-55-25](https://user-images.githubusercontent.com/26685258/54198184-d864d180-44eb-11e9-8923-037bd613ed05.png)

*  update will be done in app/views/home/_social.html.erb

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by CleverFool77** [comment]
@gauravano I wasn't able to find the file where update will be done.

**Comment by gauravano** [comment]
Here's the link - https://github.com/publiclab/plots2/tree/master/app/views/home/_social.html.erb. Please complete the issue now. Thanks!

**Comment by CleverFool77** [comment]
Thanks you so much @gauravano . I guess this issue can be assigned to a first timer now :)

**Comment by CleverFool77** [comment]
Another question,
Can we open another first timer issue regarding alignment of Dashboard and  the info written below it.
![Screenshot from 2019-03-12 22-26-37](https://user-images.githubusercontent.com/26685258/54206570-93966600-44fe-11e9-902b-9884aef6ba1a.png)

**Comment by gauravano** [comment]
As we would be doing re-design soon so let's not do this one now. Thanks!

**Comment by gauravano** [comment]
@daddyjab you can work on this one. Thanks!

**Comment by megha070** [comment]
@gauravano This side Megha Varshney. I am new to open Source and found this project really interesting please help me !

**Comment by CleverFool77** [comment]
@megha070 you can go through the issue #4963 and get yourself an issue assigned. :)

**Comment by CleverFool77** [comment]
Oh i didn't see, that you were in the list. Wait a bit and you'll get issue soon. :) Thanks.

**Comment by megha070** [comment]
@CleverFool77 Thanks a ton!

**Comment by daddyjab** [comment]
@CleverFool77 and @gauravano, thank you for creating this issue and assigning it to me.  I will get started working this! - @daddyjab

**Comment by daddyjab** [comment]
@CleverFool77 or @gauravano:
Will one of you formally assign this issue  #5031 to me ( @daddyjab ) in GitHub?  
Its currently still marked as `unassigned`.

Thanks,  @daddyjab

**Comment by gauravano** [comment]
Actually, GitHub doesn't show names of new contributors on assignees feature and that's why we use `assigned` label on issues to mark.

You can start working on this, irrespective of assignment status. Thanks!

**Comment by CleverFool77** [comment]
@daddyjab Are you still working on this issue ? If yes, then you can open a draft PR or you ask for help in group if you came across some problem or If not, then there is no problem. As opensource is always a place where another can start from where you've left and we can assign a different contributor for this.

**Comment by daddyjab** [comment]
Hi @CleverFool77,
I expect to work it early next week - hit a peak in the day job :)

**Comment by CleverFool77** [comment]
Sure @daddyjab. :)

**Comment by sateslayer** [comment]
@daddyjab are you still working on this?

**Comment by daddyjab** [comment]
Hi, @sateslayer ,
Yes, working on this one, and I expect to complete it today. - daddyjab

**Comment by Annysah** [comment]
Hello, I'm Anisat Akinbani an Outreachy Applicant. 
Is this issue still open, I will like to contribute?

**Comment by gauravano** [comment]
Hi @Annysah, I think the PR for this issue was closed mistakenly as the issue seems solved to me at https://github.com/publiclab/plots2/pull/5425

@jywarren @cesswairimu can you please verify? 

@Annysah you can claim some other FTO meanwhile, status of this one is clarified. Thanks!

**Comment by Annysah** [comment]
Okay...Thank you!

**Comment by ebarry** [comment]
I would also like to clarify this issue. Seems like @daddyjab added the borders in their pull request from last year, but i don't see it integrated on the site. If we no longer want different borders, that's fine, we should just clearly stop work on this if so and close this issue. @jywarren thanks :)

**Comment by jywarren** [comment]
Closing, thank you!!!
