### ISSUE TITLE
Adding link to sample git workflow in readme

### ISSUE THREAD

**Issue by shubhscoder** [publiclab/plots2#5032]
We have a lot of newcomers coming now, So I think we should include this link ( https://publiclab.org/notes/warren/11-22-2017/use-git-and-github-to-contribute-and-improve-public-lab-software ) This is a beautiful guide (Thanks @jywarren for this) to learn git workflow. In fact I made my first pull request using this guide. So probably this could be helpful for  someone else as well. Also we can have this as a FTO.

**Comment by gauravano** [comment]
hey @shubhscoder, nice idea. Would you like to open a FTO for this one? Thanks!

**Comment by shubhscoder** [comment]
@gauravano before I could open a FTO for this someone made a PR for this one. Actually number of newcomers are increasingly a lot in number. So there are many people who are looking for FTO's. We ll need a lot of FTO's now ! :)

**Comment by shubhscoder** [comment]
Yes I will do it. Thank you!

**Comment by gauravano** [comment]
@shubhscoder their PR is not on plots2.

**Comment by gauravano** [comment]
Hey @shubhscoder, @SKashyapD solved the issue so need to open FTO. Thanks!
