### ISSUE TITLE
Add delete account feature in user profile section

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/plots2#5033]
## Description
Currently Once a user creates an account he/she can never delete it.
There are options to edit profile or log out from all devices etc but not to completely delete the account created.

## Expected Behavior
There should be an option to delete account in the user profile section.

**Comment by gauravano** [comment]
hey @ananyaarun, we already have issue for this - https://github.com/publiclab/plots2/issues/2819. If you are interested in implementing this, chime-in there. Thanks!

**Comment by CleverFool77** [comment]
This would be great to add, coz there might be many users who made accounts and now are not using anymore.
But what about notes and wiki they added?
They won't be deleted right?

**Comment by gauravano** [comment]
We can delete spam accounts and content associated with it. And, in case a normal user want to delete their account, we can pose option for them whether they want their content to remain on our website or not? We have to discuss this further as there might be some content rights, etc in play.

**Comment by ananyaarun** [comment]
@gauravano Thanks for pointing it out.
@CleverFool77 Yes Exactly ! 
The solution of posing an option seems best in this case for a normal user.
But shouldn't the creation of spam accounts not be allowed in the first place ? At least to some level ?

**Comment by SidharthBansal** [comment]
Hi there is an existing issue in which account deletion is being discussed. It was created by me. For more discussion you can go there. 
Thanks

**Comment by ananyaarun** [comment]
Sure @SidharthBansal , Thanks :)
