### ISSUE TITLE
Weekly Community Check-in #13 - "Welcome new contributors!"

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#5034]
Hi everyone!!!

We all at Public Lab  :balloon:  - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. The goal of our Community Check-In is for every community member to share something about their work from the past week and about their current week's goal :dart: . You are also welcome to share fun-fact :smile: , new ideas  :bulb: , your learning goals :ballot_box_with_check: .

If you're new here, welcome :balloon:, and please comment a Hello message below, we love to work with you. If you're looking for new issues, please try some of our first-timers-only issues.

We're SO EXCITED to have your help!

Is there anything, you would like to share with us from last week's work? What is your plan for this week?

If you have not planned yet, just leave a Hello! so that we know that you are in sync with us :arrows_clockwise: and doing well!

As always, if you're waiting for a review, or if you're stuck, you can request help here, leave a comment on your issue with @publiclab/reviewers mentioned, or ask the community in our Gitter chatroom :open_hands: .

### Poll this week

Public Lab is having a quick poll this week for its open source contributors to see what database systems all of you use! Please respond here: [https://github.com/publiclab/plots2/issues/4919](https://github.com/publiclab/plots2/issues/4919)

### Gitter
Gitter is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up there for these updates or just to join the conversation page .

### This Week's Theme
**Welcome new contributors!** This week, create atleast 1 new `first-timers-only` (FTO) issue for welcoming a new contributor to Public Lab. The ideal FTO issue is one which:
- Follows FTO issue template - https://github.com/publiclab/plots2/blob/master/.github/ISSUE_TEMPLATE/first-timers-issue-template.md
- Have all the relevant information that a beginner needs for understanding and solving the issue
- Have code-snippet required to solve the issue in case the change required is a bit complex

See https://github.com/publiclab/plots2/issues/4963 for more details. You can also help contributors by reviewing their PR, see https://github.com/publiclab/plots2/issues/4917 for more details.

Since open source is all about community and helping others, let's find some issues which might be good for someone else who is contributing or just beginning and help them solve it. Let’s expand our community as much as we can! :tada:

### Summer of Code
@jywarren has started a brainstorming post for the ideas page for Summer of Code 2019 -It would be best to get some ideas into the discussion from the fellow community member before time. People have been brainstorming already - let's do it together!
https://publiclab.org/notes/warren/01-02-2019/brainstorming-for-summer-of-code-2019
And this is the official idea’s page:
https://publiclab.org/wiki/gsoc-ideas

### Software Contributors Survey
This survey is conducted on a yearly basis to improve our experience.
https://goo.gl/forms/4VVMO8dOijRj6BUA3
The form will remain open until early March, but don't wait to respond! This one’s for us!

### Outreachy
If you're a Outreachy aspirant and looking forward to spending your summer with us working on UI improvements of https://publiclab.org, then check out https://github.com/publiclab/plots2/issues/5022 and call for Outreachy proposals is also open -https://publiclab.org/notes/gauravano/03-12-2019/call-for-outreachy-2019-proposals so do start your proposal early! 

cc
@mohitRJranjan @milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @geekychaser @shubhscoder @sidntrivedi012 @SidharthBansal @cesswairimu @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1, @uzorjchibuzor, @eli6, @rexagod, @dinaelhanan, @dependabot[bot], @oorjitchowdhary, @wanzulfikri, @mohitRJranjan @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @romanrodriguez @Dhiraj240 @codeIriss @rishabhc32 @chirag-singhal @Saurabh19126848_twitter @IgorWilbert @dhruvgupta167 @vrk99 @pdurbin @HarshKhandeparkar @aashna27 @Harshithpabbati @marieram @swiatek7 @kaunair

Thanks and keep contributing! Contributing to Public Lab means contributing to the Environment.

People who did the check-ins-
Gaurav Sachdeva (@gauravano )
Sidharth Bansal (@SidharthBansal)
Cess (@cesswairimu )
Harman Jolly (@CoderJolly )
Rishabh Rawat (@Rishabh570 )
Sasha Boginsky (@sashadev-sky)
Rishabh Kr Bothra (@geekychaser)
Shubham Sangamnerkar (@shubhscoder)
Siddhant N Trivedi(@sidntrivedi012)
Isha Gupta (@IshaGupta18)
Gaurav Sachdeva (@gauravano)
Harshith Pabbati (@Harshithpabbati)
Gaurav Sachdeva

Have a great week everyone :balloon: :tada: :sparkler:

**Comment by gauravano** [comment]
@cassianoblonski, @Anjalizi, @divyabaid16, @madeofhuman, @gautamig54, @CleverFool77, @ananyaarun, @shreyateeza @arungoel123456 @saumyag33 @aashna27 @Harshithpabbati @marieram @swiatek7 @kaunair  @shreyateeza @TANGL3SIT3S @nazeem1988 @karunagoyalk @Nirvikalpa108 @EngrEric @Anjalizi @GettyOrawo @coderbeetle @corbettbw @govindjeevan @gautamig54 @daddyjab @emestabillo @letnewKid @srujana121 @jazdao @ChinwenduSilvia @aggarwal19 @Jenniline @madelinejones @helenatxu @richa031 @fabsar @kuja24

(mention limit exceeded in the above comment so mentioning separately. We have many new contributors and I may have missed mentioning some so feel free to mention contributors you think I have missed. Thanks!)

**Comment by gauravano** [comment]
Hi everyone!

**Goals for the week:**
1. Completing my PRs and pending reviews in mapknitter
2. Filtering plots2 issues and reviewing PRs
3. Solving issues of Translation project

have a great week :100: :sparkles: :smiley: !

**Comment by madeofhuman** [comment]
Hi, guys!

**Goals for the week:**
1. Work on two issues
2. Create two first-timer-only issues

Looking forward to everybody being awesome! 👯 🕺

**Comment by jazdao** [comment]
Hi everybody! :)

**Goals for the week:**
1. Work on my FTO issue and create at least one other PR
2. Create an FTO issue or help break one up
3. Post my proposal and leave a comment on someone else's

**Comment by jywarren** [comment]
Trying to keep up with the amazing new folks who are energizing our community! My goal is to encourage others to do as @madeofhuman and others have done, which is to show each other support!!! 

Noting our community has grown to 486+ people - i actually think possibly our welcome page can't even count everyone anymore as it's broken the API limits? @Rishabh570 or was that solved? https://code.publiclab.org/#r=all

Image Sequencer alone has over 60 contributors! https://code.publiclab.org/#r=image-sequencer

Thanks everyone! Great work!

**Comment by richa031** [comment]
Hello everyone!

**My goals for this week are:**

1. Getting at least 2 issues and work on them beginning with an FTO (please tell me where can I find them)
2. Creating a draft proposal of my outreachy application.

Looking forward to get them done.

**Comment by CleverFool77** [comment]
My goals for this week :
* Create some awesome designs 😍
* Write a blog on the new stuff I learned week.
* Create my outreachy proposal.

And most importantly, keep helping other contributors. I'll try to create five fto issues this week, one more than my last week. 🤗

If anyone is interested, I'm huge in for a debate and discussion in the field of design and technology. 😅😅  

And if there are people who like writing blogs then I would like to read their blogs. 🤓🤓. 

Thanks 📖

**Comment by karunagoyalk** [comment]
Hey everybody!

My goals for this week are:

1. Work on  issue assigned to me.
2. Creating a proposal of my outreachy application.
Looking forward to get them done.

**Comment by ananyaarun** [comment]
Hi everyone !!

My goals for this week are:
- Work on some issues and bugs
- Make a few FTO issues
- Design new UI mockups for the dashboard page and navbar.
- Start working on my proposal draft
- Continue to help and learn from the community :smiley:

**Comment by gautamig54** [comment]
Hello all!

My goals for this week are:

- Resolve 3-4 help-wanted issues on plots2.

- Make few FTO issues.

- Learn more about Ruby on Rails.

- Make a draft proposal for Outreachy.

**Comment by jywarren** [comment]
Hi, all, @SidharthBansal suggested some video chats from time to time -- maybe once per month? -- and i thought of the idea of themed code meetups - like discussing javascript testing, Rails unit testing, skylight/sentry error tracking, resolving codeclimate "smells", things like that, for topics people may find useful. I know that @cesswairimu and @StlMaris123 have done lots of in-person meetups on themes like these and wonder what they (and everyone else) thinks of this idea?

Also, welcome all! @CleverFool77 re: blogs, I've been trying to occasionally maintain one on software outreach (the techniques and strategies and values we promote here at Public Lab), here: https://publiclab.org/software-outreach - hope it's interesting!

**Comment by AnthoniaOkafor** [comment]
Hi everyone

My goals for this week are 

- To complete my FTO issue by first identifying and resolving the errors I am having on cloud9, or installing on Windows Operating System which has also been challenging.

- To resolve more FTO isseues

**Comment by Ivilili** [comment]
Hello, 

 My goals for this week are: 

-  complete my fto,

- be more active in the community,

- Start working on my proposal draft.

Have a great week everybody!

**Comment by gauravano** [comment]
> Hi, all, @SidharthBansal suggested some video chats from time to time -- maybe once per month? -- and i thought of the idea of themed code meetups - like discussing javascript testing, Rails unit testing, skylight/sentry error tracking, resolving codeclimate "smells", things like that, for topics people may find useful. I know that @cesswairimu and @StlMaris123 have done lots of in-person meetups on themes like these and wonder what they (and everyone else) thinks of this idea?

Nice ideas @SidharthBansal @jywarren!! When can we start this?

**Comment by cesswairimu** [comment]
Hi everyone :wave: 

Nice to meet all new contributors :balloon: 
@jywarren I love the idea of a themed video chats and I believe it would be great.

This week's goal.
- Make a couple of ftos
- Implement subscribers over time graph
- Finish of weekly data caching


Great week all

**Comment by jywarren** [comment]
:-) well, we are quite busy welcoming all these new people this week.
Perhaps once the pace of outreach drops a little bit, we might start --
say, next week, or in 3 weeks? (2 weeks from now i will be a bit occupied
with another project here in the local office). Any of these topics look
like a good one to start with?

**Comment by fabsar** [comment]
Hi,
my goals for the week are -
1. working on a few FTOs (please help me find them!)
2. Draft my proposal for outreachy

**Comment by gauravano** [comment]
@jywarren we can start from April 10 as we would be done with both Outreachy and GSoC applications by then?  We can poll for the topic or maybe start from Rails testing?

**Comment by SidharthBansal** [comment]
I agree with Jeff, topic of discussion can be milestone related stuff.
If it will be mid of each month or beginning, then it will be easy to
remember. Can we do it on 15 April?
Then we can continue to do on 15 of each month.
Also, we can't stick to beginning of each month as open hours are scheduled
at those times.

**Comment by shubhscoder** [comment]
Finally, I got over with my exam today.
My goals (till Sunday) : 
1. Creating atleast 2 First timer issues.
2. Solving atleast 2 issues in plots2.

Also I want to start contributing to Mapknitter, but need some help in setting up. I have tried everything but kindoff stuck now. I have opened a issue (https://github.com/publiclab/mapknitter/issues/397) @sashadev-sky do you have any idea about this?

Thank you!

**Comment by sashadev-sky** [comment]
Hi all! 

This week I have been:

- Working on making updates to the Leaflet.DistortableImage library that will be eventually merged into Mapknitter
- Contributing to community building efforts by updating guidelines for first-timers-only issues with @gauravano as per this week's theme 🎉

Thanks!

**Comment by siddhishree** [comment]
Hello everyone!
My goals for the coming week are:
1) work on a few FTOs
2) submit my application for outreachy.
Hope this week is a productive one for me and you guys too! Cheers!

**Comment by SidharthBansal** [comment]
Three optional suggestions for all SoC applicants:
If you were a GCI mentor please mention it in your proposal. We will give extra credit to these long term collaborators.
Second, it will be great to have a conference or seminar at your university about Public Lab and the programs which are held here. It is optional. No compulsion at all.
Thirdly, help each other in writing their proposals by giving suggestions under the proposals

**Comment by SidharthBansal** [comment]
Hi @gauravano can we have next checkin at MK or SWB or IS?
Let's do things in rotations. Different checkins in different repos. To will help us to bind the teams across different projects.

**Comment by SidharthBansal** [comment]
My exams got over yesterday so I am back to help you all. Please tag me in case anyone needs some help.
Thanks

**Comment by gauravano** [comment]
@SidharthBansal yes, we can try check-in in another project this time. Let's do it in Image-Sequencer? Anyone interested in opening the next check-in?

**Comment by Harshithpabbati** [comment]
@gauravano I will do  it if anyone is not interested.

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers anyone interested in doing a check-in in image-sequencer?? @subhahu123 is a new contributor, would you like to do this?

**Comment by gauravano** [comment]
Hey @Harshithpabbati, you need to open check-in in Image-sequencer. Thanks!

**Comment by Harshithpabbati** [comment]
Yeah I will do it in few minutes.

**Comment by ebarry** [comment]
This idea to rotate through the various repos is a wonderful idea! 

What would be a good process to follow for repos that aren't scaffolded yet, like https://github.com/publiclab/SmART-Form  , in order to include them in the rotation? A particular sticking point is that Smart Form no longer has a leading code contributor present in the Public Lab community because the grant expired and the academic team is not working on it any longer. I think there might be some interest in pulling out the colorimetry calculations from the Android and IOS apps, and containing it in a simpler (more universal) web app.

**Comment by Harshithpabbati** [comment]
Ok now where do i open the check in???

**Comment by SidharthBansal** [comment]
Great Idea Liz. We will include it to in the rotations.

**Comment by SidharthBansal** [comment]
Thanks Liz

**Comment by Harshithpabbati** [comment]
A new check in is posted please go through that 
https://github.com/publiclab/image-sequencer/issues/883
This time it is in image-sequencer and next time lets change the repo.
Thanks

**Comment by jywarren** [comment]
Thank you @Harshithpabbati ! I've also left a note at the top of here so we can still pin this issue to the `plots2` issues list and people can still find their way to your new check-in. 👍 🎉
