### ISSUE TITLE
Some issues in the tags page 

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/plots2#5035]
**Description**

In [https://publiclab.org/tags](https://publiclab.org/tags) 
* [ ] In Mozilla Firefox, some of the tags are overlapping each other
* [ ] Cursor in  ```show graph``` when hovered doesn't change to pointer
* [ ] The search bar is spread all across the horizontal screen

![Selection_057](https://user-images.githubusercontent.com/32747809/54226384-bdae4f00-4523-11e9-8ec3-19904bf55a7c.png)

**Expected Behavior**
* [ ] In Mozilla Firefox, there must be some space between the tags
* [ ] Cursor changes to pointer in  ```show graph``` when hovered
* [ ] The search bar is inline with page pagination (at the bottom)

**Comment by gauravano** [comment]
Hi @divyabaid16, would you like to solve this issue or can I open FTO from these?

**Comment by divyabaid16** [comment]
You may open FTO and I will try to help those who are solving the issue.

**Comment by gauravano** [comment]
Awesome!

**Comment by gauravano** [comment]
@jywarren is popular tags part of a feature? Also, any suggestion regarding the search bar?

**Comment by gauravano** [comment]
I guess it's part of **tags-header**.
