### ISSUE TITLE
Add more languages to the language dropdown present in the footer

### ISSUE THREAD

**Issue by grvsachdeva** [publiclab/plots2#5036]
Current Language dropdown:

![lang_present](https://user-images.githubusercontent.com/20878070/54226605-32818900-4524-11e9-9106-1b7e33f8d3ac.png)

@jywarren please provide the code of the **footer-notice** feature - https://publiclab.org/features/13824. I will add more languages to the footer and also add a text asking for help, like this

![new_footer_design](https://user-images.githubusercontent.com/20878070/54226922-d66b3480-4524-11e9-8553-169c01db9ec9.png)

Thanks!

**Comment by divyabaid16** [comment]
I think when we click on the other languages already present other than english, the language of the page doesn't change.

**Comment by gauravano** [comment]
Only those sentences change whose translations are available in our codebase.
