### ISSUE TITLE
Remove Postinstall Script

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/plots2#5037]
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

We are moving away from using Bower to manage our application dependencies, as it has been deprecated. We would like to remove a postinstall script in our `package.json` file that is still creating symlinks to bower components. 

## Solution

This one is simple - lets remove the following lines: 

https://github.com/publiclab/plots2/blob/205653b9e10eed21716f3f61281bc9c4574933f2/package.json#L6-L8

What to change them to:

Nothing. We may eventually add a new postinstall script but for now we are just removing it altogether. 

Thanks!!

## Steps to Fix
 
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/plots2](https://github.com/publiclab/plots2)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by gauravano** [comment]
hey @emestabillo, you can start working on this one. Thanks!

**Comment by emestabillo** [comment]
Hi @gauravano ,
Following are screenshots from my dev setup as requested:

`yarn install`

<img width="805" alt="yarn install" src="https://user-images.githubusercontent.com/21008433/54250313-aec29f00-4519-11e9-87e7-46ff9b260107.png">



`passenger start` gives me 502 Bad Gateway nginx/1.15.8

<img width="1145" alt="pstart" src="https://user-images.githubusercontent.com/21008433/54250338-c568f600-4519-11e9-8a7c-5e9fbba99083.png">

<img width="1130" alt="Screen Shot 2019-03-12 at 10 50 57 PM" src="https://user-images.githubusercontent.com/21008433/54250341-cac64080-4519-11e9-901c-63741405514b.png">

The regular `rails s` command seems to load the app. Can I just use this?

<img width="1243" alt="rails s" src="https://user-images.githubusercontent.com/21008433/54250413-0d881880-451a-11e9-8e84-07901feaf202.png">
<img width="1151" alt="Screen Shot 2019-03-12 at 10 56 59 PM" src="https://user-images.githubusercontent.com/21008433/54250482-5a6bef00-451a-11e9-9d01-70db7fdf89b6.png">

**Comment by sashadev-sky** [comment]
@emestabillo I am not sure about resolving that specific error and maybe @gauravano can advice on that but you can definitely just use `rails s` 👍

**Comment by gauravano** [comment]
Hi @emestabillo, I tried `passenger start` on my system and it worked fine. I think it has something to do with your passenger setup but not quite sure as I am not a regular user of passenger myself (I use WEBrick most of the time).

I found some links - https://stackoverflow.com/questions/51889368/rails-nginx-passenger-error-phusion-passenger-doesnt-seem-to-be-running?rq=1

https://github.com/phusion/passenger/issues/1469 

You can try them and maybe @jywarren can help here. 

> Thank you for the response @CleverFool77 ! I did try it with ‘rails s’, it loaded without the assets. I’ve just been assigned my first task and i dont think it will be a conflict for now (it

you said assets weren't loaded when you ran server with `rails s` but as per the above screenshot, the whole setup seems fine. The view seems different because at publiclab.org, the carousel, footer, etc are features i.e., their code is stored in the production database and that's why you are not able to see that in your local app.
   
Thanks!

**Comment by emestabillo** [comment]
Awesome! Thank you for the feedback @gauravano @sashadev-sky !!
