### ISSUE TITLE
Change background color of button

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/plots2#5042]
**Description**

In [https://publiclab.org/lists](https://publiclab.org/lists)
Currently, when we hover the ```Suscribe``` button, it changes its background color to the color of its parent container. It should not happen in this way.
![screenshot](https://user-images.githubusercontent.com/32747809/54257617-ebc47b00-4585-11e9-80c9-b6b43862a327.png)

**Expected Behaviour**
- [ ] The background color of the button should be the same as the parent container.
- [ ] The button must have a border that separates it from the parent container.
- [ ] The background color must change on hover and should be equal to the current background color of the button without hover.
- [ ] There should be some vertical space between the email input box and the button.

**Comment by gauravano** [comment]
I tried the page on Chrome and didn't get this issue but yes Firefox is showing this issue. Thanks @divyabaid16 for reporting this.

**Comment by gauravano** [comment]
As the page is a wiki so you can make the changes by editing the code there only

**Comment by divyabaid16** [comment]
@gauravano I couldn't find the edit option on that page. Can you please help me with this?

**Comment by gauravano** [comment]
Here you go :point_down: 

![Screenshot from 2019-03-13 22-57-04](https://user-images.githubusercontent.com/20878070/54300783-974fe880-45e3-11e9-95fc-e069f1c380c2.png)

**Comment by divyabaid16** [comment]
@gauravano Actually, I don't know why but I'm not getting an option to edit code in this page. 

![Selection_061](https://user-images.githubusercontent.com/32747809/54302538-1bf03600-45e7-11e9-9ac3-6d0754b6ace2.png)

**Comment by divyabaid16** [comment]
@gauravano I'm unable to find the file where I have to edit. Can you please help me with this?

**Comment by gauravano** [comment]
Hey @divyabaid16, sorry you have to face trouble here. Actually, editing privileges are limited to those contributors who have posted some work on publiclab.org. here's the code for the wiki - https://gist.github.com/gauravano/b1bdf4c95f7d781b47d50c06699b7ab5. You can do the changes and try it locally and  after that I will update the page as per your code. Sounds good?

Thanks for working on this!

**Comment by PritiShaw** [comment]
Can I work on this if it is not done yet ?? @gauravano

**Comment by gauravano** [comment]
Hey @PritiShaw, I think @divyabaid16 is working on this one.

**Comment by divyabaid16** [comment]
@gauravano I tried to change according to what is shown in Google Chrome, and here is the result.
![Selection_087](https://user-images.githubusercontent.com/32747809/54897044-d1c35a80-4eec-11e9-8d2c-415386cffed6.png)


![Peek 2019-03-25 10-56](https://user-images.githubusercontent.com/32747809/54897052-da1b9580-4eec-11e9-9b2e-fdb06a98faf7.gif)

**Comment by divyabaid16** [comment]
https://gist.github.com/divyabaid16/f0a4534250bd45d0a28388ac5242994d

**Comment by gauravano** [comment]
Hey @divyabaid16, the new design looks awesome. Also, I was going through the code and was little confused by the styling part https://gist.github.com/divyabaid16/f0a4534250bd45d0a28388ac5242994d/revisions#diff-01a8cb4ceec1c518a96d6e5e3178c637R10

Don't you see repetition?

Thanks!

**Comment by divyabaid16** [comment]
Yes, @gauravano I agree with you. 
Actually, the link that you had shared previously I had downloaded the zip for the code. So all the components were present scattered. 
Basically, I have just changed the following.

``` <form class="form" action="https://groups.google.com/group/grassrootsmapping/boxsubscribe"><div class="form-inline"><input class="input-medium form-control" type="text" name="email" placeholder="you@email.com" style="width: 250px;" /> <input class="btn" type=submit name="sub" value="Subscribe" style="background-color: #f5f5f5; border: 0.1px solid; margin: 2px;" onmouseover="this.style.backgroundColor='#d6d6d6'" onmouseout="this.style.backgroundColor=' #f5f5f5'" /></div></form>```

This is the new form component.
I was actually getting confused regarding how to edit the code there and I just got started somehow.

**Comment by jywarren** [comment]
Hi, Divya - i wonder if we could use a standard Bootstrap style like
`btn-default` instead of `btn-primary`?

**Comment by jywarren** [comment]
Thanks for tackling this!!! https://getbootstrap.com/docs/3.3/

**Comment by divyabaid16** [comment]
Yes @jywarren 
The screenshot for the change:
![Selection_089](https://user-images.githubusercontent.com/32747809/54938953-6c538600-4f4d-11e9-8a26-6b5efedaaf62.png)

Changes in the code:
```<form class="form" action="https://groups.google.com/group/grassrootsmapping/boxsubscribe"><div class="form-inline"><input class="input-medium form-control" type="text" name="email" placeholder="you@email.com" style="width: 250px;" /> <input class="btn btn-default" type=submit name="sub" value="Subscribe" /></div></form>```

Thank you so much @gauravano @jywarren

**Comment by divyabaid16** [comment]
Yes @jywarren 
The screenshot for the change:
![Selection_089](https://user-images.githubusercontent.com/32747809/54938953-6c538600-4f4d-11e9-8a26-6b5efedaaf62.png)

Changes in the code:
```<form class="form" action="https://groups.google.com/group/grassrootsmapping/boxsubscribe"><div class="form-inline"><input class="input-medium form-control" type="text" name="email" placeholder="you@email.com" style="width: 250px;" /> <input class="btn btn-default" type=submit name="sub" value="Subscribe" /></div></form>```

Thank you so much @gauravano @jywarren

**Comment by gauravano** [comment]
@jywarren what do you think about new design? Also, if you like it, please update the feature or let me know, I can do that. Thanks!

**Comment by jywarren** [comment]
I think it looks lovely! I think this one may be in the wiki page content itself, so perhaps a find/replace could work?

**Comment by gauravano** [comment]
Ah, I knew it was wiki  - https://github.com/publiclab/plots2/issues/5042#issuecomment-472525598 but wrote feature mistakenly :see_no_evil: . Making changes in **wiki**

**Comment by gauravano** [comment]
Ok, I changed the page. here's new look https://publiclab.org/lists 

![Screenshot from 2019-03-31 14-09-06](https://user-images.githubusercontent.com/20878070/55286825-91694e00-53be-11e9-893a-97a503e8bd22.png)


Thanks @divyabaid16 :100: for changes! Also, @jywarren @divyabaid16 please check the page once just to be sure that we haven't breaked anything there as its one of the important wiki page. Thanks! 

Closing this now!

**Comment by jywarren** [comment]
Heads up to @publiclab/community-reps ! Thanks all, this looks great!
