### ISSUE TITLE
Add css to set width of tooltip

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/plots2#5045]
Refer #5027 
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [wiki.css](https://github.com/publiclab/plots2/blob/master/app/assets/stylesheets/wiki.css) in the `plots2` repository to add css for the tooltip.
Added css should set the maximun width of the tooltip.
Code of this format can be followed -

`.tooltip-inner {
    max-width: 500px
}`

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by ananyaarun** [comment]
@gauravano , This is the second part of fixing #5027 . I'm not sure where the new css can be added and some experimenting needs to be done on the width. For now i'm adding css in wiki.css let me know if it should be added in another file.

**Comment by gauravano** [comment]
@aggarwal19 you can work on this one. Thanks!

**Comment by aggarwal19** [comment]
Okay ,I'm working on it .
Thanks

**Comment by aggarwal19** [comment]
Okay ,I'm working on it .
Thanks

**Comment by ananyaarun** [comment]
@aggarwal19 , How's this issue going ? Do u need any help :) ?

**Comment by aggarwal19** [comment]
Actually, I already did the installation process in my Linux OS. But by
mistake, I changed the usr and dev folder permissions from 777 to 754 , due
to this I have to boot the system. So, now I'm doing the booting of the
system and the installation process again.Sorry for the delay!

Thank you,
Shridhi

**Comment by ananyaarun** [comment]
No problem Good luck :) !!

**Comment by aggarwal19** [comment]
@gauravano  Hi ,I want to ask that which version of ruby we have to use in this project?
because the documentation provided on public lab repository said that we have to use ruby2.3 but when i was trying to use the plots2 folder on terminal it shows that required ruby version is not installed "ruby 2.4.4" .
so, now what i have to do ?

Thank you,
shridhi

**Comment by gauravano** [comment]
Hi @aggarwal19, thanks for highlighting this issue. You have to install `ruby-2.4.4` which is specified in the Gemfile. Raising issue to fix the docs.

**Comment by gauravano** [comment]
https://github.com/publiclab/plots2/pull/5160#issuecomment-475943448

**Comment by aggarwal19** [comment]
Hi ,
I want to create a new issue in this project and I also want to solve that
issue too. But before that I want to ask that are we able to suggest some
issues on the website ( https://publiclab.org/ )  or not ?

Thanks you
Shridhi

**Comment by gauravano** [comment]
You can surely open new issues at https://github.com/publiclab/plots2/issues/new. Thanks!

**Comment by gauravano** [comment]
Have you completed this issue?

**Comment by aggarwal19** [comment]
yes

**Comment by avinash080** [comment]
hi is this issue still open??

**Comment by shubhangikori** [comment]
Hey! If this issue is still open, can I work on it?
