### ISSUE TITLE
Don't show edit button on research note to moderators

### ISSUE THREAD

**Issue by grvsachdeva** [publiclab/plots2#5047]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** this line https://github.com/publiclab/plots2/blob/master/app/views/like/_like.html.erb#L2

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
-  <% if logged_in_as(['admin', 'moderator']) || (current_user && (current_user.uid == node.uid || node.has_tag("with:#{current_user.username}"))) %>


+  <% if logged_in_as(['admin'']) || (current_user && (current_user.uid == node.uid || node.has_tag("with:#{current_user.username}"))) %>

```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by gauravano** [comment]
This issue is created for @srujana121. Thanks!

**Comment by z119** [comment]
Unsure if this issue is open or not. If not, I'd like to request to claim this issue.

**Comment by gauravano** [comment]
Hi @z119, you can work on this one. Thanks!

**Comment by AdityaShD** [comment]
is this issue open, If not I would like to work on it.

**Comment by Linda-Ikechukwu** [comment]
I'll like to work on this issue seeing as no pull requests has been made. Can I?

**Comment by Tlazypanda** [comment]
@gauravano Is this issue still available?

**Comment by gauravano** [comment]
Hi @Tlazypanda, sorry missed your message. Thanks to Stalebot :). 

Yes, this issue is still valid as per the current state of the codebase. Notes controller allows only admin and co-authors to edit the node and not moderator so showing **Edit** button is inconsistent with backend API.

Thanks!!

**Comment by Priyaraj17** [comment]
Is this issue open? May I work on it?

**Comment by cesswairimu** [comment]
@jywarren @ebarry  kindly confirm if we want to remove moderators from editing others' notes. Thanks

**Comment by jywarren** [comment]
Hi, that's right - moderators can moderate but not actually edit notes by others. I think this is reflected in tests and controllers, but hiding the button makes sense too! Thanks!

**Comment by Manasa2850** [comment]
@kaylawoodbury you can work on this!

**Comment by kaylawoodbury** [comment]
@Manasa2850 Awesome, thanks! I'll get started on this :)

**Comment by jrogers-dev** [comment]
@grvsachdeva Seems like @kaylawoodbury has abandoned the PR. 
Claiming and fixing, if I may.

**Comment by jrogers-dev** [comment]
@grvsachdeva PR Created, waiting on tests and review. Thank you!
#9750

**Comment by ebarry** [comment]
thank you @jrogers-dev !
