### ISSUE TITLE
Broken print links

### ISSUE THREAD

**Issue by rahul2240** [publiclab/plots2#5049]
![chrome-capture (1)](https://user-images.githubusercontent.com/25618739/54277232-4fb26800-45b5-11e9-9206-56dbbb49a002.gif)

Links are not working for "Print without page links" and "Print in 3-column layout"

**Comment by gauravano** [comment]
@rahul2240 thanks for reporting. Would you like to work on solving this or can I create FTO issue from this?

**Comment by rahul2240** [comment]
@gauravano I would love to work on it :smile:

**Comment by gauravano** [comment]
Great!

**Comment by PritiShaw** [comment]
Can I work on this ?? @gauravano

**Comment by rahul2240** [comment]
@PritiShaw Go ahead
