### ISSUE TITLE
Change link to Button

### ISSUE THREAD

**Issue by shreyateeza** [publiclab/plots2#5050]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file in the `plots` repository (press the little pen Icon) and edit the line as shown below. 
Change the link here in blue box to a button
![change-to-button](https://user-images.githubusercontent.com/30488330/54281104-0404bc00-45bf-11e9-8962-957b6772f68f.PNG)

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by ananyaarun** [comment]
Hey @shreyateeza , You can follow this [Template](https://github.com/publiclab/plots2/blob/master/.github/ISSUE_TEMPLATE/first-timers-issue-template.md) for creating FTO issues. Thanks :)

**Comment by ananyaarun** [comment]
Also looks like this is a note added by @gauravano regarding outreachy , So i don't think it can be changed by others.

**Comment by shreyateeza** [comment]
@ananyaarun Yeah I think the same. But this needs to be changed to a button as well.
Also, thanks for sharing the template.

**Comment by siddhishree** [comment]
@shreyateeza  I would like to work on this issue. I am new to the community and haven't made any contribution yet. Can I proceed?

**Comment by jywarren** [comment]
Hi, indeed, i think we can ask Gaurav to change it, or perhaps he's marked
me as a co-author and I can do so. Thanks for your help though! Would you
mind closing this one, then?

**Comment by gauravano** [comment]
Closing this issue as @jywarren changed it to button. Thanks!
