### ISSUE TITLE
Follow button must be aligned in the middle

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/plots2#5051]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

![Selection_060](https://user-images.githubusercontent.com/32747809/54285921-df154680-45c8-11e9-9292-50de1122fb18.png)

**Update**
The follow button must to aligned in the middle

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by gauravano** [comment]
Hi @luanafaustini, go ahead!

**Comment by gauravano** [comment]
@divyabaid16 please add the link to the file which needs to be changed as it's a FTO. Thanks!

**Comment by luanafaustini** [comment]
Thanks @gauravano I will be waiting for the link to start!

**Comment by divyabaid16** [comment]
@luanafaustini I will update the link by today.

**Comment by divyabaid16** [comment]
@luanafaustini 
You need to change [this](https://github.com/publiclab/plots2/blob/7a0660a3fcbb40250394b68405299c41f894f7f9/app/views/tag/_tags.html.erb#L5) line to
```
<li style="width: 100%;"><span id="tag_<%= tag.tid %>" class="label <%= label_name %>" style="cursor:pointer" data-toggle="popover" data-trigger="focus" data-count=0 data-placement="top" data-content="<p style='text-align:center;'><a href='/tag/<%= tag.name %>'><%= Tag.tagged_node_count(tag.name) || 0 %> notes</a> - <a href='/contributors/<%= tag.name %>'><%= Tag.contributors(tag.name).count %> people <br></a></p> <p style='text-align:center;font-size:12px;'><%if tag.description %><%= tag.description %> |<% end %> created by <a href='/profile/<%= tag.try(:author).try(:username) %>'><%= tag.try(:author).try(:username) %></a> <%= time_ago_in_words(Time.at(tag.date)) %> ago </p><div style='text-align:center;' class='text-center'><a href='/subscribe/tag/<%= tag.name %>' class='btn btn-primary'>Follow</a></div>" data-html="true" title="<%= tag.name %>">
```

**Comment by luanafaustini** [comment]
Hello, thank you!

https://github.com/luanafaustini/plots2/pull/1#issue-261137935
is this it?

**Comment by divyabaid16** [comment]
Yes @luanafaustini 
Since this is an issue for first-timers-only to get familiar with the code base and the organization.

**Comment by luanafaustini** [comment]
Hi, @divyabaid16 Thank you! I wasn't sure if I had submitted right. Would to like to assign me another task? Can I count this task as a contribution? How can I proceed with? I appreciate your help.

**Comment by divyabaid16** [comment]
@luanafaustini have you created the pull request?

**Comment by luanafaustini** [comment]
Is the one that I mentioned on the comment above? Should I hit the Merge Pull Request button?

**Comment by divyabaid16** [comment]
Yes @luanafaustini 
And then reference the pull request with this issue.

**Comment by luanafaustini** [comment]
Thanks @divyabaid16 !

**Comment by divyabaid16** [comment]
@luanafaustini I think you have merged in your remote repo, you must send a pull request in this repository. There must be a button to compare and create a pull request. You must click that.

**Comment by luanafaustini** [comment]
I'm sorry @divyabaid16 but I am looking everywhere to see what I am missing. At the link that you've sent, I can't click on the pen icon link the tutorial is saying. It says that I "must be on a branch to make or propose changes to this file". 

Whenever I change a file of mine is through there, this is the first time that I'm doing to another's person file. 

Is it possible that I don't have access to do that?

![Captura de tela de 2019-03-14 22-45-09](https://user-images.githubusercontent.com/43607760/54402487-1288cb80-46c4-11e9-91f4-4076b2be006d.png)
