### ISSUE TITLE
Add a space in cluttered section of sentence

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5054]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** . 
* Update will be in plots2/app/views/dashboard/_activity.html.erb

![imageedit_2_8588314563](https://user-images.githubusercontent.com/26685258/54302228-7a68e480-45e6-11e9-8071-20ef6b90ed7b.gif)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by CleverFool77** [comment]
I'll update the filename in ten minutes after shifting to linux.

**Comment by CleverFool77** [comment]
Update has been done, @gauravano Is this a correct fto issue.

**Comment by gauravano** [comment]
Hey @madelinejones, you can work on this one. Thanks!

**Comment by CleverFool77** [comment]
@madelinejones Are you still working on this issue. If yes, then you can open a draft PR or you ask for help in group if you came across some problem or If not, then there is no problem. As opensource is always a place where another can start from where you've left and we can assign a different contributor for this.

**Comment by gauravano** [comment]
closed as it is similar to https://github.com/publiclab/plots2/issues/5102

**Comment by gauravano** [comment]
and contributor has already give a :+1: there. Thanks @CleverFool77 for creating the issue :100:
