### ISSUE TITLE
Tags are not closing automatically

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/plots2#5062]
**Description**
I'm not sure whether this issue is reported or not, but I found a small bug with the tags.

The tags are actually acting like a toggle button. 
When we click on the tag it remains open and only after clicking on it again, it is closed. 

Please find the GIF for the same.

![Peek 2019-03-14 17-06](https://user-images.githubusercontent.com/32747809/54354325-5821a600-467c-11e9-80b5-78858d319174.gif)

- [ ] It must close automatically be closed.
- [ ] I was also thinking on the idea how would it be if the tags are opened on hover instead of on click?

If this issue is approved, I would like to work on the same.

**Comment by gauravano** [comment]
Hi @divyabaid16, thanks for reporting. The popup on hover is implemented in https://github.com/publiclab/plots2/commit/b24a75e07c2ac0d5e0f629fe17e08d34796547f9.
