### ISSUE TITLE
Username Issue

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/plots2#5071]
Hello, I signed up on publiclab.org using github oAuth thinking that it would save my github username as my username or atleast ask for it but it saved the email address as the username. Can I change my username somehow? Or delete my account to create a new one as another user?

**Comment by HarshKhandeparkar** [comment]
@publiclab/plots2-reviewers

**Comment by gauravano** [comment]
please give your username

**Comment by siaw23** [comment]
Perhaps it's not a good idea to ask for his username publicly? Maybe @HarshKhandeparkar should send it to @gauravano privately. If no one writes a fix for this in the coming weeks I'll do it then. Basically we should find a different way to create new users with Omniauth. Now we're grabbing the first (username) parts of their emails; information which some people may not want to expose.

**Comment by gauravano** [comment]
I haven't used Github OAuth myself and was not aware of this till now, but email as a username sounded like unbelievable so asked the username. But, yes @siaw23's right, please don't copy the username here. Account deletion feature is not there, it's in discussion here- https://github.com/publiclab/plots2/issues/2819

And, there is no means of changing the username from the website as I can remember.

Totally, agree that either we should ask the user for his preference or use GitHub username maybe?

**Comment by HarshKhandeparkar** [comment]
Hello! Thanks for the response. What it actually did was it removed `@site.com` from the email id and used that as a username and the email was the email used in github. I tried to create a new account but it wouldn't let me since the email was used already. What can I do now? The email is actually my father's so I didn't want to share my email publicly. Is there some kind of id I can provide you or can I delete the acc or change my username privately without anyone knowing?

**Comment by HarshKhandeparkar** [comment]
Currently I am really frustrated as I'm in a situation from which I can only recover by waiting for a PR and I cannot open a PR as I've never used ruby in my life or I would have fixed it myself😂. But this is quite serious🤔 as other users might also fall into this pit. This should be a high priority fix I think. What do you think?

**Comment by jywarren** [comment]
Hi all - i agree this is not ideal; I think we can probably change @HarshKhandeparkar 's username manually in the db this once (esp. since @HarshKhandeparkar has not posted anything, so there will be no other traces!) but that the next steps are important too. So:

1. @HarshKhandeparkar can you email me your username at jeff@publiclab.org
2. let's make an issue to default to the GitHub username in OAuth login (code here: https://github.com/publiclab/plots2/blob/9139227ba2391e2bbe9ad7b2cbf4227f69f0c198/app/models/user.rb#L397-L408)

Sound good? Thank you!

**Comment by HarshKhandeparkar** [comment]
Ok I will mail my username. Btw please don't reply to the mail. Delete the mail if you want. Sorry for the trouble and thank you.

**Comment by jywarren** [comment]
that's fine, i promise i will be careful!

**Comment by HarshKhandeparkar** [comment]
@jywarren I have sent the email. Please let me know if you have received it. Thanks a lot!

**Comment by HarshKhandeparkar** [comment]
Hello, I have actually sent a second email. Please read that as well before making any changes. Sorry.

**Comment by jywarren** [comment]
I did it and you should now have the new (second) username. Thank you!

**Comment by HarshKhandeparkar** [comment]
Btw, how do I sign in? By using github?

**Comment by jywarren** [comment]
Let me contact you on Gitter. Sorry!

**Comment by HarshKhandeparkar** [comment]
Uh.. i dont have a gitter account.

**Comment by jywarren** [comment]
Sorry, i wanted to send you some additional information as i reset your
password but it sent a confirmation email to the address associated with
the account. :-(

If you can see it, you can go ahead and reset your password. Otherwise I
can send you the reset URL in a private channel. Sorry this was a bit
complex!

**Comment by HarshKhandeparkar** [comment]
What would the new username be? You can mention it here as it will be public. Sorry though.

**Comment by HarshKhandeparkar** [comment]
I got the reset email. Thank you! This conversation is really big. I think this issue should be closed and a new one should be opened which specifically addresses this issue.

**Comment by HarshKhandeparkar** [comment]
Ok I have changed the password and everything. The username is correct. Thanks a lot. Shall I close this issue?

**Comment by jywarren** [comment]
Yes, please go ahead -- and can you copy in the checklist i'd posted? Thank
you!

**Comment by HarshKhandeparkar** [comment]
What checklist?

**Comment by jywarren** [comment]
Ah i guess just the issue here: https://github.com/publiclab/plots2/issues/5071#issuecomment-473402485
