### ISSUE TITLE
Improve the profile dropdown on navbar

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/plots2#5074]
# Description
Currently to go to users profile , one has to click on the profile option on navbar. This doesn't open up to profiles page though. However leads to another dropdown where user profile can be selected. This is misleading as the drop down has various other options as well one being profile.

# Current Behavior

![presentprofile](https://user-images.githubusercontent.com/32260628/54378735-f417d580-46ad-11e9-810d-fba51cc7d8b1.png)

# Expected Behavior

![profilechange](https://user-images.githubusercontent.com/32260628/54378873-48bb5080-46ae-11e9-89e6-cd0946b6bd19.png)

Maybe something like this where we show just the username on navbar and clicking this opens all the other options like profile, edit profile etc.

**Comment by ananyaarun** [comment]
This is for discussion regarding this. @publiclab/plots2-reviewers any suggestions or comments ?
I feel its misleading to have to see a profile option in the profile dropdown. 
- Either clicking on profile should directly take us to users profile page. Other options like subscriptions and edit etc can be present on the users profile page instead of dropdown.
- Else it would be good to change the dropdown to show username instead of profile and have the option to navigate to user profile in this dropdown.

**Comment by CleverFool77** [comment]
@ananyaarun Now there is a PR on hover already merged. So I guess this is not that necessary in my opinion. But maybe we can go for `Account` instead of `Profile` in Navbar.

**Comment by CleverFool77** [comment]
I'm interested in working on this :)
Thanks.

**Comment by ananyaarun** [comment]
Hey, since i have already made the change in my local , you mind if i continue working on this ? 
Thanks :)

**Comment by CleverFool77** [comment]
I thought you asked for suggestions so haven't worked on it . But yeah if you have already started working on it, then keep working :+1: . If you need any suggestions, you can ask here :wink: .

**Comment by ananyaarun** [comment]
@CleverFool77 Sure !! :raised_hands:

**Comment by gauravano** [comment]
Adding username on navbar sounds good to me. Let's confirm from @jywarren and then you can continue. Thanks @ananyaarun!

**Comment by jywarren** [comment]
Ah, the only issue I could think of is that the username is not of a consistent length, and could affect the folding of the navbar at different widths. 

What if we changed it for a "person" icon from FontAwesome? https://fontawesome.com/v4.7.0/icons/

Then it would more generally refer to "profile/user stuff" without the expectation of a Profile page exactly. And it would make more space on the navbar. Could this work?

**Comment by ananyaarun** [comment]
@jywarren , Thats a valid point regarding length of username. I'll change it to the icon and see how it looks and maybe add a screenshot here ? Thanks for the feedback :)

**Comment by ananyaarun** [comment]
@jywarren  @gauravano  How does this look ?

![profile](https://user-images.githubusercontent.com/32260628/54449432-0c522800-4774-11e9-94b3-4ee5f0f0bc8e.png)

**Comment by jywarren** [comment]
oh cool -- but is that a fontawesome icon? In fontawesome, icons are
actually text characters and so they wouldn't push down the bottom of the
navbar; they'd just appear in-line. I think there might be one like `<i
class="fa fa-user"></i>` -- they're displayed inside `<i>` tags, like this:

https://github.com/publiclab/plots2/blob/bfd8b9b1af1e3a198fa30442c666b7edb49425a6/app/views/users/profile.html.erb#L7

Does that make sense?

Thanks!

**Comment by CleverFool77** [comment]
One icon doesn't match up that well in the navbar of texts. Maybe we can try an icon with text like facebook does? 
And did you change the alignment of navbar. It looks shifted towards top with respect to the icon.

**Comment by CleverFool77** [comment]
This might be a bad suggestion but what if we restrict user to put up username name text to be shown beside fav-icon with 8 characters. It won't be original username rather a username to be shown here on navbar.

**Comment by ananyaarun** [comment]
@jywarren Yes it is a fontawesome icon. I know what the problem is. I gave it a size of 2x as the original one looked too small.
like this -
![profilenew](https://user-images.githubusercontent.com/32260628/54453780-08c39e80-477e-11e9-9e75-0b4685377990.png)
As you can see the alignment of navbar got extended due to the inc in size.
Any thoughts on this size problem ?

**Comment by ananyaarun** [comment]
@CleverFool77 , Do you feel the current profile icon looks odd ? Also i feel adding a username name text and restricting it to 8 would unnecessarily confuse a new user when they are trying to create an account.

**Comment by jywarren** [comment]
Oh, this looks quite nice though, i think it's good! I don't see the
alignment issue, can you offer more detail?

**Comment by ananyaarun** [comment]
Sure, So fontawesome icon has a default size which would look like this 

![profilenew](https://user-images.githubusercontent.com/32260628/54454072-a74fff80-477e-11e9-8d12-8640b007dd6b.png)

To make it a little bigger i used the next available size which is basically 33% inc . (then 2x 3x 4x etc follow but that would be too big!) 

![bestsize](https://user-images.githubusercontent.com/32260628/54454264-13326800-477f-11e9-9e94-2b854b54b7b4.png)

Now while using the 2x size i initially did, the navbar's height inc slightly as in this screen shot

![profile](https://user-images.githubusercontent.com/32260628/54454316-30ffcd00-477f-11e9-9ef8-b2d6c339f213.png)

Personally i feel the 33% inc would do (second pic) This doesent inc height on Navbar as well :)

**Comment by jywarren** [comment]
OK, that sounds good!
