### ISSUE TITLE
Bug in Ordering of research notes

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/plots2#5076]
# Description
On clicking on research notes and applying the recent filter, the notes are not displayed in proper order moreover i noticed the old once show up first.

![order](https://user-images.githubusercontent.com/32260628/54380532-b917a100-46b1-11e9-8ea6-b2cf1cd0b30d.png)

# Expected
The recent research notes should be displayed first.

**Comment by ananyaarun** [comment]
If approved i'd like to work on this. Thanks !

**Comment by CleverFool77** [comment]
@ananyaarun The `/notes` url is showing all the notes in recent order but not `/notes/recent`. Interesting :thinking:

**Comment by ananyaarun** [comment]
Found the code responsible for this. I think changing this to ascending should work.
`def recent
    @title = I18n.t('notes_controller.recent_research_notes')
    @wikis = Node.limit(10)
      .where(type: 'page', status: 1)
      .order('nid DESC')
    @notes = Node.where(type: 'note', status: 1, created: Time.now.to_i - 1.weeks.to_i..Time.now.to_i)
    @unpaginated = true
    render template: 'notes/index'
  end
`

**Comment by ananyaarun** [comment]
So in the controller.rb file the order has been given as `DESC` by mistake. I guess changing this to `ASC` would work.
