### ISSUE TITLE
Use full span 

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5083]
## Description
RIght now, the UI looks inconsistent as the the options are in middle.

## Expected Behaviour 
As there are only two options to choose, so we can either align them to one side maybe left or we can let the `ask a question` and `tags` to take whole span and divide it into half among them.

## Screenshot
![Screenshot from 2019-03-08 15-28-47](https://user-images.githubusercontent.com/26685258/54417991-a3de5900-4729-11e9-8ca9-3523c57e74f6.png)

**Comment by CleverFool77** [comment]
I'm interested in working in this issue.

**Comment by gauravano** [comment]
Let's try both and see which one looks good? Thanks @CleverFool77!

**Comment by CleverFool77** [comment]
Sure, i"ll gif for images for both of them.

**Comment by CleverFool77** [comment]
@gauravano Following are the images -
For the aligned tabs to left 
![Screenshot from 2019-03-15 21-04-16](https://user-images.githubusercontent.com/26685258/54470669-de033580-47d1-11e9-993c-fc1cd183936d.png)
![Screenshot from 2019-03-16 09-56-01](https://user-images.githubusercontent.com/26685258/54470670-e2c7e980-47d1-11e9-9c65-31eb0c4c07a1.png)

For the tabs divided in half
![Screenshot from 2019-03-16 09-52-50](https://user-images.githubusercontent.com/26685258/54470665-d5aafa80-47d1-11e9-95e4-9f654bf1a44f.png)
![Screenshot from 2019-03-16 09-54-07](https://user-images.githubusercontent.com/26685258/54470671-f410f600-47d1-11e9-93e4-af9f13dd659e.png)

**Comment by CleverFool77** [comment]
Which one look better ? :thinking:

**Comment by gauravano** [comment]
I think tabs divided in half. Let's confirm from @jywarren. Thanks @CleverFool77 !

**Comment by jywarren** [comment]
I agree with Gaurav! Thanks!!!
