### ISSUE TITLE
Lack of consistency in calender on events page

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/plots2#5086]
# Description
The pop up on clicking on events listed in the calender on events page open differently for different rows.

# Current Behavior
This is how is opens for a bottom row 

![bottomrow](https://user-images.githubusercontent.com/32260628/54422978-a3e45600-4735-11e9-8df5-8110e8c73087.png)

This is how it opens for a row on top however

![toprow](https://user-images.githubusercontent.com/32260628/54423012-afd01800-4735-11e9-9d02-b2b70a7a83d2.png)

# Expected Behavior
They should be uniform independent of the row user clicks on.

**Comment by ananyaarun** [comment]
@publiclab/plots2-reviewers , The issue is isn't with size of screen or tag opening based on screen width and height but the difference is seen mainly on where the user clicks. I'd like to try fixing this if approved :) Thanks.

**Comment by gauravano** [comment]
Hey @ananyaarun, the Google calendar is framed into the wiki on this events page so I don't think we have any control over the popups, etc. 

Thoughts?

**Comment by ananyaarun** [comment]
@gauravano , Hmm i see. Then perhaps nothing can be done ? We would have control if we implement the calendar component from scratch ourselves but that would be challenging too ! Do you want me to close this issue for now ?

**Comment by gauravano** [comment]
You can see if there are any options we can supply in the iframe tag for changing the popup style, etc but let's close it for now. Thanks!

**Comment by CleverFool77** [comment]
Aren't google calendar usually like this ? :thinking:

**Comment by gauravano** [comment]
:point_right: https://github.com/publiclab/plots2/issues/5086#issuecomment-473280244
