### ISSUE TITLE
Add followers list to Contributors pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5089]
We should show 2 columns on pages like https://publiclab.org/contributors/ui; one for people who have posted ("contributors" -- these are already shown on the page) and one for people who are Following the tag/topic. We currently only show followers here:

![Screen Shot 2019-03-15 at 12 38 19 PM](https://user-images.githubusercontent.com/24359/54447193-3d543d80-471f-11e9-845d-f684755d54f9.png)

Let's also rename the tab "People"! 

I'd love help with this - it could be done by making 2 columns, one labelled `People who've posted` using the current table -- code here:

https://github.com/publiclab/plots2/blob/master/app/views/tag/contributors.html.erb#L66

And adding a 2nd column displaying a similar table but for `Tag.followers(params[:id])` -- that is, followers of the topic. 

The tab text could be changed in this file: https://github.com/publiclab/plots2/blob/master/app/views/tag/show/_nav_tabs.html.erb

**Comment by ananyaarun** [comment]
@jywarren , I'd like to work on this !

**Comment by jywarren** [comment]
that'd be super, thank you!

**Comment by IshaGupta18** [comment]
@ananyaarun are you still working on this one? If not, could I work on it?

**Comment by ananyaarun** [comment]
@IshaGupta18 ,Sorry I got busy with other issues. 
Sure u can go ahead :)

**Comment by IshaGupta18** [comment]
So I am a bit confused here, so basically we have to create another tab like "Contributors" and list the followers there? Is this making sense? Or do we have to change the popover?

**Comment by ananyaarun** [comment]
From my understanding of the issue, we should create a new tab.

**Comment by IshaGupta18** [comment]
Basically a new tab next to "contributors" tab having a list of followers?

**Comment by ananyaarun** [comment]
Yes, after the enhancement there will be two tabs. One to show list of contributors and one to show list of followers.

**Comment by IshaGupta18** [comment]
Okay that would be cool I think, so just one tab has to be added up.

**Comment by IshaGupta18** [comment]
@jywarren could you please clarify my doubt here? I'll start work then. Thanks a lot!

**Comment by jywarren** [comment]
Hi! Actually i'd like to start by listing followers in a 2nd column of the same tab -- does that work? Thank you!!!

**Comment by IshaGupta18** [comment]
Yes, it does! I am sorry I missed out on your comment here. I'll get on with it ASAP. Thanks!

**Comment by IshaGupta18** [comment]
@jywarren #5353 is my PR for this issue. Kindly have a look at it. Thanks a lot!

**Comment by IshaGupta18** [comment]
@gauravano kindly review my revised PR!
