### ISSUE TITLE
Reapeating of templates while editing

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/plots2#5092]
**Description**
While using the template to share the work, on changing the option of the ```Templates```, the option that is selected is appended after the current option.

It must not happen in this way instead it must be overridden while changing the ```Templates``` from the drop-down menu.

In the page [https://publiclab.org/post?&legacy=true](https://publiclab.org/post?&legacy=true)

Please find the attached GIF.

![Peek 2019-03-16 00-54](https://user-images.githubusercontent.com/32747809/54457455-77f1c080-4787-11e9-9eb4-a26c722f00b1.gif)

**Comment by divyabaid16** [comment]
@publiclab/reviewers Is this issue correct?
If yes, then I would like to work on this!

**Comment by sashadev-sky** [comment]
@divyabaid16 hey, good find! Yes please feel work on this and thank you for your help :) I am assigning you now
