### ISSUE TITLE
Mysterious error message "User owmloading not found" shown

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/plots2#5095]
I got this error when I opened my profile
![Screenshot_20190316_012912](https://user-images.githubusercontent.com/34770591/54458837-f56b0000-478a-11e9-9144-738ea5616b24.jpg)

I have used the website for the first time so please correct me if I have asked something wrong. Also my images were not posting on comments and even on profile image. Is this some internet problem or something else?

**Comment by madeofhuman** [comment]
@gauravano @jywarren I want to look into this next.

**Comment by HarshKhandeparkar** [comment]
Can someone explain to me what this bug is?

**Comment by HarshKhandeparkar** [comment]
What does the error mean?

**Comment by gauravano** [comment]
That would be great @madeofhuman!

**Comment by gauravano** [comment]
@HarshKhandeparkar Actually, this alert is shown in some instances, mostly in login flow. The reason for this is still not known.

**Comment by HarshKhandeparkar** [comment]
Uh ok. I was also not able to upload imgs. What could be the reason?

**Comment by gauravano** [comment]
Locally or in prod?

**Comment by HarshKhandeparkar** [comment]
prod!

**Comment by HarshKhandeparkar** [comment]
I have good internet. 8MB/s upload

**Comment by gauravano** [comment]
There's an issue open for upload of the image in the comments. You faced issue there or somewhere else?

**Comment by HarshKhandeparkar** [comment]
Yes, in comments.

**Comment by CleverFool77** [comment]
Hi
I faced similar issue while I was editing my note.

**Comment by HarshKhandeparkar** [comment]
@guaravano I also couldn't upload a profile img.

**Comment by skilfullycurled** [comment]
If it helps diagnose the problem, I've had this recently as well.  For me, it reveals itself after clicking on a link to see a filtered list of my content from my profile.  

For example: `https://publiclab.org/tag/activity:*/author/bsugar`

Doesn't effect any functionality.

Firefox 66.0.3
macOS 10.12.6

**Comment by jywarren** [comment]
I think i got this. `public/lib/leaflet-environmental-layers/dist/LeafletEnvironmentalLayers.js:             imageLoadingUrl: 'owmloading.gif', // URL of loading image rela`

this is an artifact from LEL, for the "loading" gif. it may try to load this at the wrong location here:

https://github.com/publiclab/leaflet-environmental-layers/blob/783409c0c903f3e14780a687bf2692462016f948/src/openWeatherMapLayer.js#L228

It's a relative location so that's why it shows up so many places. And you may get this notice on the next page load if this map gets loaded and it tries to fetch this .gif !

@ananyaarun @sagarpreet-chadha can we address this issue by eliminating that loading spinner and replacing it with a corrected relative path, or something similar? Maybe the ability to pass a root URL parameter on which to base relative URLs to this loading spinner? Or how does the regular spinner work? This is actually starting to cause system tests to fail, as well! Like in #5995. 

Whew, this was a great one to find! Now we just have to solve it :-)

**Comment by skilfullycurled** [comment]
> Whew, this was a great one to find! Now we just have to solve it :-)

I'm glad you like it?  

I mean, the bugs tend to find me not the other way around.

; )

**Comment by gauravano** [comment]
Wow!! this really took time.

**Comment by jywarren** [comment]
I think this is now solved due to changes in upstream https://github.com/publiclab/leaflet-environmental-layers/! Thanks all!

**Comment by jywarren** [comment]
This is now recurring again, noting relation to #7939

**Comment by jywarren** [comment]
Hi @Tlazypanda -- i reopened this and I think this is also in relation to the asset locations being defined relatively... do you think that may be right? Is it something we could monitor by watching the Chrome dev console while loading a map, and seeing how the path matches or doesn't match the location of the Leaflet assets? Thank you!

**Comment by jywarren** [comment]
As you've been working on assets a lot, if you wouldn't mind adding this to your task list that would be super helpful!!

**Comment by skilfullycurled** [comment]
If it would help I’d be happy to change my username to “owmloading” so I will always be found.  LMK.  : P

Actually, in all seriousness that may have enough comedic value to do.

Wait.

Nope.

It won’t be so funny if it ends causing a Little Bobby Tables situation.

https://xkcd.com/327/

**Comment by ebarry** [comment]
Lol @skilfullycurled 
This is somewhere between Little Bobby Tables and Public Lab's own ghost in the machine

**Comment by Tlazypanda** [comment]
@skilfullycurled @ebarry  That cracked me up lol :joy:   @jywarren I found this on the lel live site might be of use: - investigating more to find out this ghost xD  Do we need this gif file? 
![image](https://user-images.githubusercontent.com/33183263/85022999-c2839900-b191-11ea-9a19-a6e6b3fa8cc3.png)

**Comment by skilfullycurled** [comment]
While my Ruby abilities are very limited, I do try to insert attempts (emphasis on attempts) at humor especially when it’s a bug I submitted.  Not as helpful as actually tracking it down and fixing it, but hey, I’ve only got what they gave me.

**Comment by jywarren** [comment]
Hi! Thanks for investigating this!!!

I think we should see if this is referenced from a stylesheet, in which case we could override it with our own styles, or from JavaScript, in which case perhaps we can override it there? Can you look for the exact line of code where it happens and try to debug from there. 

Overriding in JavaScript may be harder; see how Leaflet has allowed people to override image paths here: https://leafletjs.com/reference-1.4.0.html#icon-default-imagepath

So we could try to do something like that, either locally in our instance, or potentially filing an upstream PR to `leaflet-openweathermap`?

What do you think?

**Comment by ebarry** [comment]
I think this is a candidate for our `Hall of Fame` label...

**Comment by Tlazypanda** [comment]
@jywarren Actually on using the git blame feature (thanks for telling me about this simplifies debugging a lot :D) came to know that this line was introduced in https://github.com/publiclab/leaflet-environmental-layers/commit/f38d59419c4e88af855ec2172c1b5b44192a8be3 where we added the Openweather map module code but this code referenced the owmloading.gif too but this wasn't added.  

https://github.com/publiclab/leaflet-environmental-layers/blob/f38d59419c4e88af855ec2172c1b5b44192a8be3/src/openWeatherMapLayer.js#L228  

So following the Openweather map module(https://github.com/buche/leaflet-openweathermap/ - owmloading file was present from the initial commits of this library) so this had to be added in assets/images. Once I did that, and checked the examples/index in browser the error `Failed to load resource: the server responded with a status of 404 ()` vanished. I have opened a pr for the same in LEL which is referenced above. Thanks :v:

**Comment by ebarry** [comment]
Another sighting of the fugitive `owmloading` 🔭
From browsing someone's profile page, i clicked the title of a research note, and when that note loaded, the red alert of owmloading appeared: 

![omw-loading](https://user-images.githubusercontent.com/161439/87682102-722a3780-c74d-11ea-8d55-6ad96b79570c.gif)

**Comment by ebarry** [comment]
👻 This just happened again. 
I was on https://publiclab.org/profile/liz
and clicked "292 research notes"
then arrived at https://publiclab.org/notes/author/liz where the "ghost" appeared:
<img width="925" alt="Screen Shot 2021-02-10 at 3 18 13 PM" src="https://user-images.githubusercontent.com/161439/107566971-728b9380-6bb3-11eb-91c1-3f59de3e3f29.png">

**Comment by jywarren** [comment]
Just an update - reading the above again, i see that "owmloading.gif" means "open weather map loading" and not a mis-spelling of "downloading" - lol!

https://github.com/buche/leaflet-openweathermap/blob/master/example/leaflet/owmloading.gif

https://github.com/publiclab/leaflet-environmental-layers/pull/473/ attempted to add it locally within LEL, which could work. I'll try that again, but we can also configure it here:

https://github.com/publiclab/leaflet-environmental-layers/blob/5c095304d0d5dcfc56950fccd5c5091dde891bef/src/openWeatherMapLayer.js#L226

cc @RuthNjeri

**Comment by jywarren** [comment]
Progress at https://github.com/publiclab/leaflet-environmental-layers/pull/504 once we get tests running again via GitHub actions for that repo! Then we'll bump the version and re-release.

**Comment by jywarren** [comment]
Final fix in https://github.com/publiclab/plots2/pull/9208, whew.

**Comment by cesswairimu** [comment]
Wow finally!!!  this is awesome :tada: :tada:
