### ISSUE TITLE
Not able to update my own post/note

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#5101]
### Problem faced : 

While updating my proposal on publiclab.org , after doing all the changes when i click the submit button - the spinner on button continues to rotate but no request is send to Server **[In rich wiki mode].**

While in legacy wiki mode , i am getting this error : 
<img width="865" alt="Screenshot 2019-03-16 at 1 52 14 PM" src="https://user-images.githubusercontent.com/14952645/54472716-0b141000-47f3-11e9-90fb-ebd167889aaa.png">

### Possible Solutions :

1.) The JS code which works after we click the submit button is not working properly . 
2.) There maybe problem in the routes .

**Comment by sagarpreet-chadha** [comment]
JS Console logs : 
<img width="1437" alt="Screenshot 2019-03-16 at 1 59 59 PM" src="https://user-images.githubusercontent.com/14952645/54472752-e40a0e00-47f3-11e9-8295-bbbeba68ad45.png">

**Comment by sagarpreet-chadha** [comment]
<img width="415" alt="Screenshot 2019-03-16 at 2 10 23 PM" src="https://user-images.githubusercontent.com/14952645/54472835-57604f80-47f5-11e9-9274-bafdb069fe92.png">

**Comment by jywarren** [comment]
Hmm, could it be related to this Sentry bug i've highlighted in https://github.com/publiclab/plots2/issues/2206#issuecomment-474103918? Can we move any 'inline rich wiki editing' portion of this there, and have this issue be for legacy wiki editing with the normal "edit" button? Thank you for reporting!!!

**Comment by jywarren** [comment]
Ah wait, this is unrelated, sorry! @sagarpreet-chadha is editing a note, not a wiki! I think i've seen this somewhere else though as well. Maybe the person did not open an issue? Changing the title here in any case and will try to find it in Sentry for logs....

**Comment by jywarren** [comment]
Aha - is it possible you were pasting emoji in? Linking the Sentry issue now, but potentially we could resolve with either showing a more useful error, OR solving https://github.com/publiclab/plots2/pull/3007

**Comment by jywarren** [comment]
Hi @sagarpreet-chadha just wondering if this ended up being related to emoji -- i copied in a Sentry error too. If so, could we merge this into #3007 and the related db encoding issues? Thank you!
