### ISSUE TITLE
Fix spacing & capitalization in dashboard activity

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/plots2#5102]
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

Our UI under our Dashboard Activity section needs a little improvement.

<img width="820" alt="Screen Shot 2019-03-16 at 1 20 32 AM" src="https://user-images.githubusercontent.com/41092741/54473895-6672dd80-47b4-11e9-97c4-8c23b6e279aa.png">

## Solution

Let's make it look nice and consistent by adding spacing & capitalization, like this:

<img width="761" alt="Screen Shot 2019-03-16 at 6 40 50 AM" src="https://user-images.githubusercontent.com/41092741/54474070-94f1b800-47b6-11e9-9e9e-d2df8e3e68e1.png">

Where to find the relevant lines of code: 
1) The spacing issue. Add a space after the | (pipe symbol)
https://github.com/publiclab/plots2/blob/d083415283dd89e0644e5bfe5ceb8e30b75dbecf/app/views/dashboard/_activity.html.erb#L42

2) The capitalization issue. Capitalize the first word **of the string**. You do not need to change the key. 
https://github.com/publiclab/plots2/blob/d083415283dd89e0644e5bfe5ceb8e30b75dbecf/config/locales/en.yml#L287

Thanks!!

## Bonus
I am not married to the way the text is laid out in general. If you have any additional changes you want to make, add them on to your PR and thank you! 

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/plots2](https://github.com/publiclab/plots2)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by sashadev-sky** [comment]
currently claimed by @meghana-07

**Comment by megha070** [comment]
I would like to take this up.

**Comment by gauravano** [comment]
This issue and https://github.com/publiclab/plots2/issues/5054 looks similar.

**Comment by sashadev-sky** [comment]
@gauravano good find! Ok @meghana-07 never responded here so its all yours @megha!

**Comment by sashadev-sky** [comment]
@megha070 Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Because of high demand for these issues we try to make sure we have some sort of an update within a week of someone claiming it that the contributor is still working or we might need to reassign it. Thanks!

**Comment by sashadev-sky** [comment]
reassigning to @kuja24!

**Comment by kuja24** [comment]
Will be keen to do it. Thanks!

**Comment by kuja24** [comment]
@sashadev-sky I have joined the cloud9 team.How do I contribute from there?I have cloned it there only in my workspace. How do I proceed further?

**Comment by gauravano** [comment]
Hey @kuja, you can commit the changes using `git commit -m "commit message"` and after that push the commits using `git push origin branch-name`. Raise PR after that by visiting the issue branch on the forked repo and clicking on Pull Request link. 

Thanks!

**Comment by kuja24** [comment]
Ohh!!  I was aware of this but I thought it would be somewhat different for the cloud environment.  Got it now
Thanks!

**Comment by sashadev-sky** [comment]
closed via #5421
