### ISSUE TITLE
Clicking on Publish Note shows buffering icon 

### ISSUE THREAD

**Issue by vansjyo** [publiclab/plots2#5103]
When I click on Publish on the link for "Publish", it shows a buffering icon and does not publish the note. I am using Mozilla Firefox browser and this was an issue while publishing my draft Outreachy proposal on this [ link
![Screenshot from 2019-03-16 17-18-55](https://user-images.githubusercontent.com/25532570/54474941-53422b00-4811-11e9-9f58-1f0051e0bf3c.png)
](https://publiclab.org/post?n=17360&title=Outreachy%20proposal:%20&tags=software,soc,soc-2019,soc,outreachy,outreachy-2019,outreachy-2019-proposals,response:17359). 

Inspector console
![Screenshot from 2019-03-16 17-32-21](https://user-images.githubusercontent.com/25532570/54474960-8e445e80-4811-11e9-9013-2145dacd048b.png)

**Comment by jywarren** [comment]
Hi I'm sorry you had trouble! How long did you wait for it to spin? I wonder if it an issue of the server taking far too long to complete the request, we should look up the skylight logs for this action. Apologies again, and please feel free to email your proposal to jeff@publiclab.org for now!

**Comment by gauravano** [comment]
@jywarren here's a similar issue - https://github.com/publiclab/plots2/issues/5101. Seems something wrong with editor?

**Comment by madeofhuman** [comment]
@gauravano I'm experiencing this issue too when trying to submit my proposal. Let me see if I can look into it.

**Comment by jywarren** [comment]
I believe this is linked to #5118 I just opened from sentry.io... let's investigate there!

**Comment by jywarren** [comment]
Thanks for adding information!

**Comment by jywarren** [comment]
Hi, all - i believe I've fixed a database issue documented in #5118, and if I'm right, this may be resolved. I've left some follow-up steps to address how this originally happened but if the immediate issue is fixed, please report back and close this issue. Thanks so much for carefully documenting it and looking into it.

**Comment by vansjyo** [comment]
@jywarren @gauravano It works now. Its just that it doesn't show any kind of message to notify. Thanks @jywarren for looking into it.
