### ISSUE TITLE
Draft text to welcome newcomers to the dashboard

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#511]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled.

****

We need something like (but in HTML):

```
## Hello, welcome to Public Lab!

This is your dashboard, where recent updates from other community members show up. It's helpful to keep up to date with new progress, news, and recent developments.

But to get started at Public Lab, try:

* asking a question (/questions)
* exploring projects (/methods)
```

This would go in the Dashboard template, probably just above the Activity feed, in a box, perhaps with a light grey 1px border and rounded corners:

https://github.com/publiclab/plots2/blob/master/app/views/dashboard/dashboard.html.erb#L26

If you take this on, please share a screenshot of your work so we can see how it looks!

**Comment by mayank-mittal** [comment]
So do i only have to create a container which displays this message and add it to the dashboard.html.erb? if it is can i take this one.

**Comment by jywarren** [comment]
We'd have to also check if the user is new -- i.e. have they signed up in the past week, for example? And put that in a conditional. Something like:

```ruby
<% if Time.now - current_user.created_at > 1.week %>
  <!-- container here -->
<% end %>
```

I *think* that'd work, but you probably need to test it out! 

Thanks a lot!

**Comment by dristybutola** [comment]
Can i work on this issue?
Secondly is the dashboard to be shown to users newer than a week?
thanks.

**Comment by ryzokuken** [comment]
Sure, @dristybutola.

Yes and no. The dashboard is visible to everyone, but the welcome text would only be visible if the user is newer than a week.

For any queries, feel free to ask here or on our Gitter channel.

**Comment by jywarren** [comment]
Hi, are either @mayank-mittal or @dristybutola still interested in trying this one out? We'd love to help if you've gotten stuck.

**Comment by dristybutola** [comment]
Hi @jywarren , I am going to start work on this :), can I?

**Comment by jywarren** [comment]
Yes, please do, if you're able -- much appreciated!

**Comment by dristybutola** [comment]
So, I am working on this issue  :)

**Comment by jywarren** [comment]
Super. Thanks!

**Comment by Gauravano** [comment]
Hi @jywarren, I have tried to solve this issue as per specifications and have also added conditional so that this well would be visible to only new users.I have attached image of the well I have added, please review and comment on the design
![issue511](https://user-images.githubusercontent.com/20878070/30243198-4a7e215c-95c2-11e7-877e-e091e20244e6.png)

**Comment by jywarren** [comment]
Wow, awesome! Have you opened a pull request for this?

It'd be great to see a "close this window" thing like in the alert windows: https://github.com/publiclab/plots2/blob/master/app/views/layouts/_alerts.html.erb#L7

Also, the `###` is supposed to indicate an `<h3></h3>`, does that makes sense? Could you update accordingly? Thanks!

**Comment by Gauravano** [comment]
hi @jywarren, no I haven't opened pull request. yes, <h3></h3> tags would be great ,thanks for clearing . The message to be displayed is a long one, so it should be part of the screen a modal or to be displayed at top of screen.

demo1 - Modal :
![check3](https://user-images.githubusercontent.com/20878070/30393180-e629c152-98dc-11e7-8667-ab9e0eb4a5df.png)

demo2 - Top of screen :
![check2](https://user-images.githubusercontent.com/20878070/30393181-e62f93b6-98dc-11e7-881e-41706aa62b18.png)

demo3 - At the same place you have mentioned but with close button:
![check1](https://user-images.githubusercontent.com/20878070/30393182-e63eb7b0-98dc-11e7-9e00-1f32c42b3d18.png)

Reply which one looks more appropriate then I will open a pull request for that one. Thank You.

**Comment by jywarren** [comment]
Oops, I wanted to say this is completed and published! Thanks so much to those who helped make it happen!
