### ISSUE TITLE
No notification of new first-timer post was sent to moderators group

### ISSUE THREAD

**Issue by Fastie** [publiclab/plots2#512]
I just noticed on the dashboard an unpublished first time post: https://publiclab.org/notes/clownfish/04-24-2016/question-focus-on-mobile-phone. I did not receive an email notification of this first time post, although I don't really know whether I should have (Am I a moderator?). I approved the post.

Also, why was this unpublished post displayed on my dashboard? Maybe because I am a moderator?

**Comment by jywarren** [comment]
> Maybe because I am a moderator?

Yep!

Filling this out a bit more -- expected behavior is that when the author publishes their note, this sequence happens: 

https://pad.publiclab.org/p/moderation

I also did not get an email. Looking into email sequence first.

**Comment by jywarren** [comment]
BTW, Chris, you are an admin, which is like a super-moderator. 

I'm seeing that emails were sent, but not received by the google group. Or, rather, some were, but some weren't:

* no initial "new first-time poster" emails was received (by me or chris)
* no "this post was approved by X" was received (by me or chris)
* the moderators-version of  "[PublicLab] New post title" published email was received, but this was not sent via moderators@.

My current working theory is that our mail gateway (google apps) is not delivering emails sent to and sent from the same address? Checking the logs.

**Comment by jywarren** [comment]
Yes, it seems that changing the from: address to moderators@publiclab.org means it's sending from and to the same address; the test on Saturday was sent from do-not-reply@publiclab.org.

I'm going to change the from: address to quickly resolve this issue for now. I had changed the from: address so that replying to the email automatically went to moderators@, but that apparently breaks receipt of the email.

**Comment by jywarren** [comment]
I believe we're up and running again with this fix. Please re-open if you see this not working again. 

Testing emails is tough -- they were actually being sent, but due to the from/to issue, they weren't being relayed by a mail service.
