### ISSUE TITLE
[Discussion] Include social weblinks

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/plots2#5123]
**Description**

Currently, there are no social weblinks in [https://publiclab.org/dashboard](https://publiclab.org/dashboard). 

I think that there must be social weblinks like facebook, Instagram, Twitter, Youtube etc, on this page too to grow outreach. 

Even after login, these should be the scope for these weblinks.

**Comment by CleverFool77** [comment]
@divyabaid16 Social links to share dashboard ? 
As much I know, The notes and wikis already have social web links to share :thinking: .

**Comment by divyabaid16** [comment]
@CleverFool77 
Actually, I was not talking about the links to share. 
A link to view the social pages. :rocket:

**Comment by CleverFool77** [comment]
I'm unable to understand. :sweat_smile: 
Can you elaborate a bit ?

**Comment by gauravano** [comment]
@divyabaid16 at /home links are present :point_down: 
![Screenshot from 2019-03-17 18-48-03](https://user-images.githubusercontent.com/20878070/54491535-43941680-48e5-11e9-917c-81202ea8c5e0.png)

**Comment by divyabaid16** [comment]
I was thinking that we should include these links on this page since this is the most visited one. 
Or we can even add the links in the footer section.
What are your views on this @gauravano @CleverFool77

**Comment by CleverFool77** [comment]
Main site is most visited I guess, dashboard is for those who login. So even if we'll share the links.. First that person have to login to see it. If a person is logged in then we see research url I guess.

**Comment by divyabaid16** [comment]
You're right @CleverFool77 :smile: 
Actually, this issue came in my mind thinking that most of the pages have small social icons even on the footer which was not present here.

**Comment by gauravano** [comment]
We can think of adding social links to the footer 

![footer](https://user-images.githubusercontent.com/20878070/54551091-54bb5100-49d3-11e9-85ac-79304bde37a0.png)

I guess they would look good on the extreme bottom-right maybe? We can try different positions? 

Let's ask @publiclab/community-reps what they think about it. Thanks!

**Comment by jywarren** [comment]
In the footer sounds good!

**Comment by divyabaid16** [comment]
@jwarrwm can you please tell me which file has to be changed for the footet.

**Comment by gauravano** [comment]
Actually, footer is a feature, so here's the code for it - https://gist.github.com/gauravano/1124fff46ae156537e6fb712bff9e980. Thanks!

**Comment by divyabaid16** [comment]
@gauravano I have made the changes

File where I have made the changes: https://gist.github.com/divyabaid16/fdfbcde7336e89f7447778bcb4c98908

Screenshot
![Selection_095](https://user-images.githubusercontent.com/32747809/55124643-f443b680-512c-11e9-84aa-0d079b7f50b1.png)

GIF
![Peek 2019-03-28 07-44](https://user-images.githubusercontent.com/32747809/55124959-2bff2e00-512e-11e9-82f1-bc6c37c19c69.gif)

**Comment by gauravano** [comment]
Looks great @divyabaid16! @publiclab/community-reps what do you think?

**Comment by jywarren** [comment]
It's very nice! Is it ready to be copied back in? Thank you!!!

**Comment by gauravano** [comment]
yes, it's ready @jywarren for copying in.

**Comment by jywarren** [comment]
Done! Thank you!!!

**Comment by gauravano** [comment]
Icons are looking great on website footer :smile: :100:
