### ISSUE TITLE
Remove Authlogic deprecation warning for email validation

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#5125]
Main issue #4624 
created specifically for @CubikMan47
### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

**Problem**: 
There is this Authlogic deprecation warning currently
```
DEPRECATION WARNING: This Authlogic configuration option (validates_format_of_email_field_options) is deprecated. Use normal
ActiveRecord validation instead. 
```

 📝 **Update**: 
* Remove line https://github.com/publiclab/plots2/blob/master/app/models/user.rb#L33
* Add this  line  `validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }` after https://github.com/publiclab/plots2/blob/master/app/models/user.rb#L35 

After changing run the tests and make sure the deprecation warning is gone.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

**Comment by CubikMan47** [comment]
Alright, thanks!
