### ISSUE TITLE
Remove asset not present deprecation warning

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#5126]
Main issue #4624 
created specifically for @Julius26
### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

**Problem**: 
This asset pipeline deprecation warning
```
DEPRECATION WARNING: The asset "dynamic_search.js" is not present in the asset pipeline.Falling back to an asset that may be in the public folder.                                                     
This behavior is deprecated and will be removed.
```

 📝 **Update**: 
We are including a javascript file that was removed/ was never there. 
Lets remove this line
https://github.com/publiclab/plots2/blob/master/app/views/admin/assets.html.erb#L8

After changing run the tests and make sure the deprecation warning is gone.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

**Comment by An0u** [comment]
Has anyone opened a pull request on this and is working on it already?

**Comment by cesswairimu** [comment]
Hey @An0u this one @Julius26 is working on it.If you are looking for an fto leave a comment here #4963 and we will get an issue for you soon
