### ISSUE TITLE
Remove instruction to install bower from pre-reqs 

### ISSUE THREAD

**Issue by Nirvikalpa108** [publiclab/plots2#5128]
Hi guys 😃 

Should we remove bower from the list of pre-reqs and change this to yarn?
https://github.com/publiclab/plots2/blob/master/doc/PREREQUISITES.md

I noticed this has been mentioned [here](https://github.com/publiclab/plots2/issues/3840#issuecomment-436428141) by @jywarren, but the documentation change has not been implemented yet? 

Let me know and I can raise a PR.

Thank you ❤️

**Comment by gauravano** [comment]
Hi @Nirvikalpa108, sure, go ahead!

**Comment by metonymic-smokey** [comment]
Hi @Nirvikalpa108 @gauravano, there wasn't a PR pertaining to this issue under the 'documentation' label. 
I'd like to work on this issue as my first one since it's still open, with @Nirvikalpa108 if needed.
thanks!

**Comment by gauravano** [comment]
Hi @metonymic-smokey, go ahead.

**Comment by metonymic-smokey** [comment]
@gauravano changed the docs in my PR.
However, the Travis-CI check keeps failing and I am not too sure on how to rectify this. Any thoughts on this would be helpful!

**Comment by gauravano** [comment]
hey @metonymic-smokey, the test failure is not related to your PR. It's related to our test setup, we are trying to fix that. Sorry for the inconvenience.

**Comment by metonymic-smokey** [comment]
Thanks @gauravano !Are the changes in this PR sufficient or do I need to make further changes to the pre-reqs?

**Comment by metonymic-smokey** [comment]
Thanks @gauravano , the PR has passed all checks now.
Would love to work on similar first-timer bugs at publiclab!

**Comment by gauravano** [comment]
You can find more issues at https://code.publiclab.org. And, if you're interested in any specific language/framework/type of task, feel free to let us know. And, we would also love to have your help. Thank you!
