### ISSUE TITLE
Toggling between update types should be easier (new dashboard)

### ISSUE THREAD

**Issue by Fastie** [publiclab/plots2#513]
The default display on the new dashboard includes notes, comments, questions, and events (like it did before, but now wiki edits are also mixed in #514). It would be good if you could switch to just just notes or just comments with one click (it now takes six clicks to get just comments, and wiki edits are still mixed in #514)

**Comment by jywarren** [comment]
I think a solution could be to have an "All" option which (like [on Spectral Workbench sets](https://spectralworkbench.org/sets/3193)) selects or deselects all. 

The code for this is here: https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_activity.html.erb#L6-L19

The JavaScript for it is here: https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/dashboard.js#L3-L57

Chris, would you mind reformatting this issue following [the guidelines here](https://publiclab.org/wiki/developers#Contributing+for+non-coders), to do our best to invite others into our codebase?
