### ISSUE TITLE
Fix broken link in contributing.md

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/plots2#5131]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the link in the [CONTRIBUTING.md](https://github.com/publiclab/plots2/blob/master/CONTRIBUTING.md) file in the `plots2` repository on L30 from 
`https://github.com/publiclab/plots2/blob/master/.github/ISSUE_TEMPLATE/first-timers-issue-template.md` 
to
`https://github.com/publiclab/plots2/blob/master/.github/first-timers-issue-template.md`

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by ananyaarun** [comment]
I noticed this link was broken a few hours ago when the FTO template was updated. This can be fixed by a first timer in CONTRIBUTING.md file. Thanks :)

**Comment by VinneyJ** [comment]
working on it.

**Comment by ananyaarun** [comment]
@VinneyJ , Do you need any help ? How is the issue going ? Feel free to ask any of us if u get stuck :smiley:

**Comment by VinneyJ** [comment]
Hello @ananyaarun  i had finished the issue long ago  and proposed the change. Thank you.

**Comment by ananyaarun** [comment]
@VinneyJ , Thats great !. Have u opened a PR ? If so reference this issue number, I dont seem to find ur PR :)

**Comment by VinneyJ** [comment]
I just forked it, made a branch and edited the link commented then proposed the change. How do i go about the PR please help. Sorry i didn't know about it(PR).

**Comment by ananyaarun** [comment]
@VinneyJ , no problem. So after making changes in ur fork, U will see an option call "Compare and Pull request". Clicking on this u shall be able to open a pull request. Making changes on ur local is different from merging the changes to this repository. I hope this helps. First try opening a pull request and we can help u out from there :) Thanks !

**Comment by VinneyJ** [comment]
Awesome let me try.

**Comment by VinneyJ** [comment]
I did that  and merged it. Have you seen it on you end? i gave it #6060

**Comment by ananyaarun** [comment]
@VinneyJ , Nice work but i see u merged it to ur forked repository. U need to send a Merge request to this plots2 repository ie the main one not ur fork.

**Comment by VinneyJ** [comment]
![Screenshot from 2019-03-21 16-37-20](https://user-images.githubusercontent.com/39193976/54755829-e2778600-4bf7-11e9-9493-73c6eb1e9876.png)

**Comment by VinneyJ** [comment]
Oh okey let me continue trying. Till it works.

**Comment by VinneyJ** [comment]
@ananyaarun seen it?

**Comment by ananyaarun** [comment]
Yes i see it. Next time don't open multiple PR's for the same issue. It can be edited in one PR itself. Thanks :)

**Comment by VinneyJ** [comment]
Thank you that happened while i was trying so many times. But now am good at it. I learnt.
