### ISSUE TITLE
Add few more steps to installation instructions

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/plots2#5132]
**Description**
Many of us while installing the project faced a common problem of 
```Your Ruby version is 2.x.x, but your Gemfile specified 2.4.4```
Can we add instructions to install the ruby version 2.4.4 using `rvm` or `rbenv` etc before `bundle install` ?

For example: 
`rvm install ruby-2.4.4`
`rvm use ruby-2.4.4`

**Comment by divyabaid16** [comment]
@publiclab/reviewers can this be an issue to be worked upon?

**Comment by jywarren** [comment]
Sure, this'd be helpful I think! Want to open a pull request? Thanks!

**Comment by divyabaid16** [comment]
Ya, I will open up the pull request.

**Comment by SidharthBansal** [comment]
Great
