### ISSUE TITLE
Rails tests failing

### ISSUE THREAD

**Issue by CubikMan47** [publiclab/plots2#5133]
Hi. I was trying to setup plots2 on my local machine, in order to complete my first-timer issue (#5125), but ran into a problem. I successfully installed all the [prerequisites](https://github.com/publiclab/plots2/blob/master/doc/PREREQUISITES.md), and followed all the [installation steps](https://github.com/CubikMan47/plots2#standard-installation) until step 11, when the `rails test -d` command failed with the following error: 

`889 tests, 2690 assertions, 2 failures, 11 errors, 0 skips`
`Writing XML reports to /home/samuele/plots2/test/reports`
`[Coveralls] Outside the CI environment, not sending data.`

However, passenger runs just fine, and I can login at localhost:3000 without problems.

The output and the logs can be found [here](https://gist.github.com/CubikMan47/c7b4bc25270bf9472a6828545c0b32f8)

### Environment info: 
OS version: Ubuntu 18.04.2 (in a VirtualBox VM with host Windows 10 1803 64-bit)
Kernel version: 4.18.0-15-generic
Software versions:
- `rvm -v` `rvm 1.29.7 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]`
- `ruby -v` `ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]` 
- `bundle -v` `Bundler version 1.16.2`
- `npm -v` `6.4.1`
- `bower -v` `1.8.8`

**Comment by cesswairimu** [comment]
Hey @CubikMan47 I believe you are using sqlite3. We are experiencing these errors due to multiple databases we are using mysql for production and somehow some tests fail while using sqlite3. You could ignore this for now you can checkout more discussion on this here https://github.com/publiclab/plots2/issues/4896. Thanks.

**Comment by CubikMan47** [comment]
Alright, thanks
