### ISSUE TITLE
Missing questions in dev seeds break tags notes page

### ISSUE THREAD

**Issue by alonpeer** [publiclab/plots2#5140]
The seeds for local development do not contain any nodes which are attached to a "question" tag (`Node.questions == []`).
This has a side-effect of breaking a page such as http://localhost:3000/tag/five, which one would expect to return the "Blog Post" node, but instead nothing is returned.
The reason is that in `tag_controller` [the list of questions is fetched](https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L97), then [used to filter](https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L135) the list of nodes to only fetch notes. Since `qids == []`, this adds `WHERE node.nid NOT IN (NULL)` to the query, resulting in an empty set.

The solution IMO should be either to add at least one question to the local dev seeds, or avoid adding that query condition. I lean towards the latter, as I find it cleaner, since it doesn't assume the existence of specific data in the system.

**Comment by jywarren** [comment]
This is a great catch and much appreciated! Would you be interested in
submitting a pull request with the change? Thank you!

**Comment by alonpeer** [comment]
@jywarren already did! 😄 See: https://github.com/publiclab/plots2/pull/5141
I just need to fix some rubocop stuff there 🤖
