### ISSUE TITLE
Unpublished research note had a comment

### ISSUE THREAD

**Issue by Fastie** [publiclab/plots2#515]
I found a research note (question) on the dashboard that had one comment (from Warren). It was not labelled as being in moderation. When I navigated to the note, it was labelled "Unpublished" and the photo included was dimmed. The banner said it was from a first time poster so I approved the note. Now it displays normally.

https://publiclab.org/notes/litar/04-25-2016/question-why-won-t-the-spectrum-plot-show-once-the-image-has-been-uploaded

Did Warren leave a comment on the note without approving it for publication?

**Comment by jywarren** [comment]
I think there's a bug that admins don't see the banners, as I didn't see
that it was not yet approved.

Thanks for approving it - I'm looking into the email notifications shortly.

**Comment by jywarren** [comment]
I've rewritten this as #516, closing. Thanks!
