### ISSUE TITLE
Issue in search results of two or more words

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/plots2#5156]
We search with the input as two or more words, the first result seems to be fine but when I click the same or another button again such `All content` or `Notes` etc, the search bar and the results seems to include a plus sign `+` between the input words.

**Current behaviour:**
![plissue2](https://user-images.githubusercontent.com/32747809/54544847-6d713a00-49c6-11e9-97d1-c13ece8ee09d.gif)

**Expected behaviour:**

- [ ] The search bar and the `Results for` section should not include the `+` sign between the words on button clicks.

**Comment by jywarren** [comment]
Yeah i noticed this - would love help fixing it! Perhaps we should look at
the searches_controller.rb file?

**Comment by IshaGupta18** [comment]
Okay so I have found a fix to it, right now I have implemented it in `all-content`, for others, we can create FTOs!

**Comment by IshaGupta18** [comment]
Here's my PR for the same, if approved, I will open FTOs for the remaining tabs! Thanks a lot everyone!
