### ISSUE TITLE
Change cursor to pointer in choose an image

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/plots2#5162]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

**Update**
In [https://publiclab.org/profile/edit](https://publiclab.org/profile/edit) currently, if we want to edit our profile and add an image to it while choosing an image, the cursor must change to a pointer.

Make changes in `app/views/users/_photo.html.erb` file

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by msarfrazanwar** [comment]
Hey, I would like to work on this.

**Comment by divyabaid16** [comment]
Yes, you may go ahead. 
If any help is needed do not hesitate to ask.

**Comment by msarfrazanwar** [comment]
How can I see the changed preview?

**Comment by divyabaid16** [comment]
Have you set up your local host?

**Comment by msarfrazanwar** [comment]
No, How do I deploy? I know how to setup localhost.

**Comment by divyabaid16** [comment]
Have you followed the instructions mentioned [here](https://github.com/publiclab/plots2#installation)? 
Fom the last step, you will be able to set up a local host for yourself. 
After opening up the local host enter ```http://localhost:3000/profile/edit``` url. 
Here, you will be able to see the desired changes.

**Comment by msarfrazanwar** [comment]
I am getting warning due to version conflict with the bundle file and its not working.

**Comment by divyabaid16** [comment]
rvm install ruby-2.4.4
Or
rvm use ruby-2.4.4

You may use any of these lines before bundle install to resolve this error.
Thanks!

**Comment by supriya-kotturu** [comment]
Hey,
can I try this out too?

**Comment by divyabaid16** [comment]
@supriya-kotturu, I guess @msarfrazanwar is working on this.
There will be a separate issue created for you :smile: 
Just introduce yourself on #4963

**Comment by supriya-kotturu** [comment]
thank you @divyabaid16

**Comment by msarfrazanwar** [comment]
Has anyone build this project on Windows because after doing some searching I think rvm is not available for windows. @divyabaid16

**Comment by gauravano** [comment]
Hey @msarfrazanwar, you can follow https://gorails.com/setup/windows/10 for setting up rails on your system. Thanks!

**Comment by msarfrazanwar** [comment]
Hi, On the last step of setting up the database it says "mysql2 not found, include it in the gem file". It is not working even after install it separately.  @divyabaid16 @gauravano

**Comment by divyabaid16** [comment]
What is your ruby version?
Is it 2.4.4?

**Comment by gauravano** [comment]
Hey @msarfrazanwar, can you paste the error here? Thanks!

**Comment by SidharthBansal** [comment]
@divyabaid16 can we close this issue now?

**Comment by divyabaid16** [comment]
Yes @SidharthBansal , this is done now.
Thanks!
