### ISSUE TITLE
Ordering of notes by no of likes not working

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/plots2#5170]
# Description
The notes when displayed in sorted order by no of likes, ie in /notes/liked, the notes appear in random order neither asc nor desc wrt likes.

![likes](https://user-images.githubusercontent.com/32260628/54584566-badcbe00-4a3d-11e9-9d51-074d79c6e785.png)

This is a problem i see in my local installation as well.

# Expected 
The notes must be sorted based on desc order of no of likes.

**Comment by ananyaarun** [comment]
@gauravano , This is an issue i found while looking at #5076 . I'd like to fix this too after #5088 is tested and fixed.

**Comment by CleverFool77** [comment]
Will you be working on this if approved ?

**Comment by ananyaarun** [comment]
@CleverFool77 ,yes :)

**Comment by jywarren** [comment]
Oh this is a good issue, thanks!

**Comment by ananyaarun** [comment]
Hey @jywarren I just noticed that this issue still holds !
even sorting by recent is not working,

![recent](https://user-images.githubusercontent.com/32260628/68711903-a21eab00-05c0-11ea-8bd8-40796c9b3a7a.png)

I think we can make this a GCI issue too ? What do you think ?

**Comment by jywarren** [comment]
Sure, that'd be great!

**Comment by ebarry** [comment]
Thank you for identifying this issue!

**Comment by ananyaarun** [comment]
Issue moved to #6850
