### ISSUE TITLE
Align "Dashboard" text with the welcome text on dashboard

### ISSUE THREAD

**Issue by IshaGupta18** [publiclab/plots2#5173]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem

Change this:

![image](https://user-images.githubusercontent.com/40794215/54592828-28471980-4a53-11e9-8aac-f532a4eb0445.png)

To this:

![image](https://user-images.githubusercontent.com/40794215/54592886-43198e00-4a53-11e9-82e3-31ade5d0a982.png)

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by siddhishree** [comment]
Hello @IshaGupta18 , can i work on this issue?

**Comment by IshaGupta18** [comment]
Sure @siddhishree go right ahead! Let me know if you need any help!

**Comment by vaarigupta** [comment]
hello, This is Vaari Gupta. @IshaGupta18  How can I move with this issue to resolve? It seems to be assigned to @siddhishree .

**Comment by IshaGupta18** [comment]
Yes @vaarigupta this is assigned. You can look for other FTOs or I will try to create one for you very soon!

**Comment by vaarigupta** [comment]
Thanks @IshaGupta18  I am excited to work on FTO . Please create one for me.

**Comment by sharmamansi** [comment]
Hi , @IshaGupta18  can i work on this?

**Comment by IshaGupta18** [comment]
Sure!
