### ISSUE TITLE
Implement shortcut key to change focus over searchbar

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5174]
## Description 
Currently, The users need to take the cursor to search bar and then type and enter it. Instead user can directly use shortcut key to change focus over to the search bar. And then type.
Thus, removing the requirement of mouse for while searching.

**Comment by CleverFool77** [comment]
@publiclab/reviewers Is this issue correct ?

**Comment by CleverFool77** [comment]
If approved, then I would like to work on this. 
thanks :).

**Comment by CleverFool77** [comment]
How about ctrl+shift+s @HarshKhandeparkar . It's not used anywhere.

**Comment by CleverFool77** [comment]
alt are reserved by different OS'es in different way and shift isn't used much.
So this could be most preferred one.

**Comment by HarshKhandeparkar** [comment]
Is typing alt+shift+f easy? Can it be done with 3 fingers of the same hand?

**Comment by CleverFool77** [comment]
@HarshKhandeparkar Using `alt` for shortcut keys isn't preferred as different OS reserve `alt` shortcut keys in their own way hence it might be possible some users wont be able to use the `search` shortcut key. Using `ctrl+shift+f` looks good to me and it is well withing comfort of pressing with same hand.
We might have considered using `ctrl+shift+s` but it is the shortcut key to open debugger menu in firefox.
`Ctrl+shift+f` seems an appropriate choice as `ctrl+f` is used for find and to convey search within public lab, we can use `ctrl+shift+f`.

**Comment by HarshKhandeparkar** [comment]
I guess opera uses it for in-built search.
You can check here https://defkey.com/what-means/ctrl-shift-f

**Comment by CleverFool77** [comment]
@HarshKhandeparkar How about overriding the keys ?

**Comment by HarshKhandeparkar** [comment]
I don't think that is possible.

**Comment by HarshKhandeparkar** [comment]
Also how will you implement this? Using JavaScript?

**Comment by CleverFool77** [comment]
@HarshKhandeparkar yes, overriding shortcut keys via javascript is completely possible.

**Comment by HarshKhandeparkar** [comment]
Then it's ok i think. Just ask @publiclab/plots2-reviewers first though.

**Comment by CleverFool77** [comment]
@HarshKhandeparkar The applications like facebook,twitter,gmail, slack, zulip etc. override the in browser keys like `ctrl+s` with their in application shortcut keys to provide a better user experience.
And considering publiclab has notes ,blog ,subscribe and many more features. This would be very helpful in future course.

**Comment by gauravano** [comment]
I think it's a good idea. @publiclab/community-reps what do you think?

**Comment by jywarren** [comment]
Sure -- in Gmail and other apps, the '/' key opens search. We could do
that? Try this code to detect a keystroke:

$(window).on('keypress', function(e){console.log("keyCode is: " +
e.keyCode)})
