### ISSUE TITLE
Brainstorm list of supportive additions to Welcomebot

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5179]
Our new welcomebot "expandable sections" are great for offering support without overwhelming:

https://github.com/publiclab/plots2/blob/master/.github/config.yml

Let's brainstorm more additions!

## Opening first PR

* [ ] ask people to join the weekly check-in
* [ ] put hints on Travis debugging
* [ ] installation help

## Merging first PR

* [x] help someone else

**Comment by CleverFool77** [comment]
@jywarren How about these points - 
* Ask to read code of conduct
* Give a link to gitter or chat channel
* Provide a link to first-timer issues

**Comment by jywarren** [comment]
oh, very nice ideas!

**Comment by IshaGupta18** [comment]
@jywarren a couple of more points:

Solving some issue

1. show related issues when the contributor is stuck (this would be very helpful to the contributor in taking reference)
2. after merging of a PR, show similar issues on which the contributor can work

**Comment by ananya** [comment]
Hey @jywarren @gauravano I have made a pr at #5241 and added gitter chat link, weekly check-in and installation help. I wasn't sure about travis debugging :sweat_smile: , please let me know about a good source to add it from.

**Comment by jywarren** [comment]
thank you!!! We'll check it out.

IshaGupta18, i wonder if there's a related issues bot we can install?

For travis, I'm thinking something like:

```
If you see errors, or a red X by your commits, this means the Travis
service has found some issues. Dangerbot may highlight what these are and
offer some links, but either way, clicking on the red X will let you read
through the log output as our tests run on your new code. Skim through and
look for lines with "ERROR" or "FAIL" to see if they have hints as to what
lines caused the issue. It can be helpful to copy the error text into the
comments so others can see and offer help in debugging.

Although the tests will say "ERROR" and "FAIL", please don't be
discouraged. Failing tests are supposed to be helpful, and to help build
your confidence in the final code. It's perfectly fine to open a PR with
some errors, because then other community members will be able to help you
figure them out! And it'll feel extra good when you solve them and the Xs
turn into green checkmarks.
```

With some nice friendly emoji too! What do you think?

**Comment by IshaGupta18** [comment]
Yes I think this sounds really good. We can do a related issues bot thing,
that could prove to be really useful and will make the contributor more
independent.
