### ISSUE TITLE
Colour missing for button on contribute a kit page [discussion]

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/plots2#5180]
# Description
Here is the present view of the contribute a kit page both on my local and the public labs page.

![addbluecolor](https://user-images.githubusercontent.com/32260628/54625651-b3490380-4a95-11e9-8785-b37f00146b7c.png)

![addcolour](https://user-images.githubusercontent.com/32260628/54625665-b93ee480-4a95-11e9-91ab-1134ee9b0472.png)

The Subscribe to answer questions on this topic button looks odd.

# Expected Behavior

The color of this button should be the same as Ask a question about kits to keep the UI uniform.

**Comment by ananyaarun** [comment]
I'm not sure if color was intentionally not added. If this is not the case then this can be edited to make a good FTO :) @publiclab/plots2-reviewers

**Comment by ananyaarun** [comment]
Also I think adding colour to the subscribe button just above the navbar would help make it better visible to users and stand out on the page. Thoughts ?

**Comment by gauravano** [comment]
I think we can start working on this one :point_down: 

![one](https://user-images.githubusercontent.com/32260628/54625651-b3490380-4a95-11e9-8785-b37f00146b7c.png)

"or" between buttons also look a little weird? 

I think we can remove "or" and can change Subscribe to answer button for starting. @jywarren 

Thanks @ananyaarun for catching and thinking about this!

**Comment by ananyaarun** [comment]
Sure, Removing or sounds good! . I'll start working on this. Thanks :)

**Comment by jywarren** [comment]
What do folks think about brainstorming a bit on this first -- like, does
the Subscribe to answer button even make sense? Should we instead be asking
people to follow the "kits" or equivalent tag itself, and maybe could
simplify the area? I'd love to hear some ideas. Thanks!

**Comment by ananyaarun** [comment]
Sure !! Any suggestions/comments are welcome :)

**Comment by gauravano** [comment]
As "Subscribe to answer questions" button subscribes a user to `question:kits` in above case so we can mention that only as button text **Subscribe to answer questions** seems confusing. 

So, i am suggesting to use "Get notified whenever someone ask questions about the **kits**"

What do you think?

**Comment by ananyaarun** [comment]
Yes @gauravano that would be less misleading to a new user. But will the text "Get notified whenever someone ask question about the kits" not become too long for a button ? Can we make this a clickable link instead ?

**Comment by gauravano** [comment]
Yes, long text on button will also look bad. Any suggestion, how can we shorten the text length as I don't know if link will look good here?

Maybe @jywarren can guide better on design. Thanks!

**Comment by sashadev-sky** [comment]
Hi! I was just looking over this and I have a few questions:

The UI for a page with Notes available looks like this:

<img width="684" alt="Screen Shot 2019-03-25 at 5 39 00 AM" src="https://user-images.githubusercontent.com/41092741/54909822-6912b880-4ec1-11e9-8e3b-6b0ee81f7c56.png">

Initial thoughts are does following a tag currently give you notifications about everything related to the tag, including questions? And is "subscribing" to something different than "following" it? Do you follow "topics" and subscribe to "tags"?

Maybe for the button we just move the RSS, follow, etc. bar to the bottom, right above the "related tags" section. Then when the user clicks it, there is a popup pane or something similar with a checklist of what sections you would like to subscribe to: wikis, notes, Q + A, all?

**Comment by gauravano** [comment]
> Initial thoughts are does following a tag currently give you notifications about everything related to the tag, including questions? And is "subscribing" to something different than "following" it? Do you follow "topics" and subscribe to "tags"?

@sashadev-sky In this case, subscribing and following is the same, both subscribe a user to a tag. **Follow air-quality** button will subscribe a user to `air-quality` tag whereas **Subscribe to answer questions on this topic** subscribes a user to `question:air-quality` tag. So, the former is a general and latter one is for questions regarding that topic(as per my understanding)  

> Then when the user clicks it, there is a popup pane or something similar with a checklist of what sections you would like to subscribe to: wikis, notes, Q + A, all?

Something like - When user hover over the follow air-quality button, they would see options inside that. So, with this, we can remove the Subscribe to answer questions button too?

**Comment by sashadev-sky** [comment]
@gauravano Yeah that was my idea! So maybe then if you're on the tags specific page like here, you get this hover option of what types you want to subscribe to. For the related tags you would still just be subscribing to the whole tag in general (this feature doesn't look like its been implemented yet anyway) and then if you want to select more specifics instead of subscribing to the whole tag you would have to visit the related tags page instead and subscribe there?

Do you think that makes sense?

**Comment by gauravano** [comment]
> @gauravano Yeah that was my idea! So maybe then if you're on the tags specific page like here, you get this hover option of what types you want to subscribe to.

Ah, when we use the term "tag specific page", so the page dedicated to this tag, so shouldn't it be containing all options directly. If we put all options(wiki, question, event) as buttons, I think, there would be like 4-5 buttons maybe. So, wouldn't it be good to just put them as buttons?

Yes, the backend of Subscribing to multiple tags is done. We are facing some difficulty in frontend part, but @IshaGupta18 is working on that. I also think we should show popups above the tags like we show on notes - https://publiclab.org/notes/warren/11-30-2017/build-a-papercraft-spectrometer-for-your-phone-version-2-0. What do you think?

**Comment by gauravano** [comment]
And, yes, I think we should remove the "or" placed between buttons. @ananyaarun @sashadev-sky

**Comment by ananyaarun** [comment]
@gauravano , Yes as a first step the "or" can be removed. Should we make this a newcomer issue ?
Considering the fix is easy ? 
Once this is done we can ponder on other design changes more such as colour of those buttons.

**Comment by sashadev-sky** [comment]
@ananyaarun yes do you want to open this? Maybe to remove the "or" but add some <br> tags or margins or so? I can't take this on now but I would play around with it a little bit and find what looks good before opening an FTO

**Comment by ananyaarun** [comment]
@sashadev-sky sure will do it :)

**Comment by ananyaarun** [comment]
@sashadev-sky , @gauravano  how would this look ?
![newlook](https://user-images.githubusercontent.com/32260628/55975374-7690b680-5ca7-11e9-93c6-29e309b2dd9d.png)

**Comment by ananyaarun** [comment]
@sashadev-sky , @gauravano  how would this look ?
![newlook](https://user-images.githubusercontent.com/32260628/55975374-7690b680-5ca7-11e9-93c6-29e309b2dd9d.png)

**Comment by jywarren** [comment]
Hi, this was thoroughly overhauled recently and looks great now! Thanks all!
