### ISSUE TITLE
Need to update the revision timestamp when publishing drafts

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5181]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

I just published from a draft here: https://publiclab.org/notes/warren/03-19-2019/assembling-the-simple-air-sensor and it correctly updated the timestamp to "now" when i published, as you can see in the URL.

But on the dashboard it shows up as "4 days ago" so I think we are not updating the revision timestamp as well... 

Here's the code:

https://github.com/publiclab/plots2/blob/4fc2e9f0d54485dbfebb0d3ab070d9d2ce9497c7/app/controllers/notes_controller.rb#L381-L394

I think we need to add a line to update the `@node.latest` (i.e. the most recent revision) timestamp to `Time.now` like:

```js
revision = @node.latest
revision.timestamp = Time.now.to_i
revision.save
```

Thank you!!!

**Comment by jainaman224** [comment]
@jywarren I want to work on this.

**Comment by gauravano** [comment]
Go ahead @jainaman224!

**Comment by jainaman224** [comment]
@jywarren
Url is updated due to https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L140 use of `Time.now` but we are using `node.created_at` as publish time. Which can't be changed.
In Node model there is no publish time. So, how should I approach it?

**Comment by jywarren** [comment]
Addressing this in #6913!
