### ISSUE TITLE
Reporting or contributing for the Bootstrap 4 upgradation

### ISSUE THREAD

**Issue by Souravirus** [publiclab/plots2#5182]
Hi everyone,

We are working on the upgrade to Bootstrap 4 of the Public Lab website(publiclab.org) in this [PR](https://github.com/publiclab/plots2/pull/3937). For some days from now, we will be keeping the [unstable](https://unstable.publiclab.org/) branch updated with the Bootstrap 4 commits. So, if anyone sees anything odd at https://unstable.publiclab.org/, please report to https://github.com/publiclab/plots2/pull/3937. 

Also, if anyone wants to correct the error or the existing errors, please push to the  Souravirus:bootstrap4 branch.
 
https://github.com/Souravirus/plots2/tree/bootstrap4

Thank you!!

**Comment by gauravano** [comment]
@publiclab/plots2-reviewers @publiclab/reviewers

**Comment by PritiShaw** [comment]
Can i work on this ??

**Comment by gauravano** [comment]
yes @PritiShaw :+1:

**Comment by jywarren** [comment]
Hi!! Ok, going through a lot of small and big things here, but just want to say 🎉 this is AMAZING @Souravirus !!!

* [ ] If we could get a little more space between the search bar and the next menu, that'd be great:

![image](https://user-images.githubusercontent.com/24359/55689220-f806e280-594f-11e9-9607-15082f48e562.png)

* [ ] I think the "show password" button that @CleverFool77 made is getting wrapped, although it still works!

![image](https://user-images.githubusercontent.com/24359/55689239-208edc80-5950-11e9-94c5-da4616f79983.png)

* [ ] I think the "profile pic" is not floating right in this:

![image](https://user-images.githubusercontent.com/24359/55689242-2d133500-5950-11e9-9134-3f65d1705445.png)

* [ ] space needed between "or" and "log in" here:

![image](https://user-images.githubusercontent.com/24359/55689252-4f0cb780-5950-11e9-9b8f-da6fbae1f366.png)


More soon!!! Great work, again!

**Comment by jywarren** [comment]
* [ ] I see this in a few places where a btn group is kind of not smoothly grouped, like on the dashboard:

![image](https://user-images.githubusercontent.com/24359/55689311-ed991880-5950-11e9-9383-1358e75265be.png)

* [ ] And after pressing the "Wiki" tab, but also the "New page" button:

![image](https://user-images.githubusercontent.com/24359/55689316-01dd1580-5951-11e9-9e53-0feeb1a91824.png)

* [ ] The "subscribe" button doesn't seem to be working? 

![image](https://user-images.githubusercontent.com/24359/55689319-17ead600-5951-11e9-8f09-e33d5c33d589.png)


* [ ] the tags "cog" menu is off the side of the screen:

![image](https://user-images.githubusercontent.com/24359/55689325-289b4c00-5951-11e9-8595-0bfea724a674.png)

* [ ] the geocoding modal is not full-width:

![image](https://user-images.githubusercontent.com/24359/55689331-34870e00-5951-11e9-988e-c044bd1b9efc.png)

* [ ] Adding a new tag doesn't clear the input, and the new tag is not in a colored badge element:

![image](https://user-images.githubusercontent.com/24359/55689343-4d8fbf00-5951-11e9-98c8-a3ab43cc3bc3.png)

* [ ] Some weirdness with the boxes around the new comment box:

![image](https://user-images.githubusercontent.com/24359/55689351-58e2ea80-5951-11e9-9f37-4b92bc9ffb7b.png)


* [ ] the "preview comment" button doesn't seem to work?

![image](https://user-images.githubusercontent.com/24359/55689357-6a2bf700-5951-11e9-8f37-d5bc141a8f62.png)


* [ ] the node tool caret icon is not appearing: 

![image](https://user-images.githubusercontent.com/24359/55689360-74e68c00-5951-11e9-9957-5eaf633a3bb8.png)

* [ ] clicking the "like" button doesn't seem to do anything

* [ ] follow buttons on the /tags page don't work:

![image](https://user-images.githubusercontent.com/24359/55689375-98113b80-5951-11e9-8fd5-580183fe9d0f.png)

That's a lot for now! Thanks so much for your hard work on this project, Sourav!!!!!

**Comment by jywarren** [comment]
Feel free to check/resolve mine as they get solved. Thanks again!!!

**Comment by Souravirus** [comment]
Hi @PritiShaw if you want to contribute to these issues you can just contribute to this PR. Thank you!!

**Comment by Souravirus** [comment]
Hi @jywarren, that show password button is getting wrapped because the `form-control-feedback` class is outdated in Bootstrap 4. So, should just append it to the input box?

**Comment by jywarren** [comment]
Ah, yes, i guess so. Thanks!

**Comment by sashadev-sky** [comment]
This is not specific to any version of Bootstrap, but please note in PR #5372 we found and resolved a bug with Bootstrap that is yet to be fixed even in V.4. It is that checkboxes do not vertically align with their text for certain OS's. There is now a stylesheet in plots2 specifically to explain and override this bug: [https://github.com/publiclab/plots2/blob/master/app/assets/stylesheets/btsp_checkbox_override.css.scss](https://github.com/publiclab/plots2/blob/master/app/assets/stylesheets/btsp_checkbox_override.css.scss)

Those classes are currently not being used anywhere else in the repo besides `rich.html.erb` (the editor), but please take these overrides into consideration if you do use them. Note they are also on a very high level of specificity.

**Comment by sashadev-sky** [comment]
Also another thing: the styling Bootstrap applies to `input[type=file]` does not prevent cross-browser inconsistencies with the alignment of input[type=file] buttons and the text printed next to them. I added another css file to address that (please see PR #5424 and the issue it references)

**Comment by Souravirus** [comment]
Hi @sashadev-sky, can we include these after the upgrade or someone can take up this task and put the classes where they are required and I can merge them? What do you think about this?

**Comment by sashadev-sky** [comment]
@Souravirus they aren't a big deal so can be included at any point. One of them is already merged and i'm building on it in PR #5421 to apply to every checkbox because I realized all of the check boxes on the site are slightly unaligned for certain users

**Comment by Souravirus** [comment]
Hi @jywarren, the New page button is appearing fine in my browser. Here is the screenshot
![image](https://user-images.githubusercontent.com/17192149/55913114-776f0d00-5c01-11e9-93d7-c228c06a6b7e.png)

**Comment by Souravirus** [comment]
@jywarren, just wanted to say the dropdown which is moving out of the screen can be accessed with the slider at the bottom. Also, it is done by default by Bootstrap. Talking about the map modal, it is also the default size of the Bootstrap modal. So, should we leave them as it is?

**Comment by Souravirus** [comment]
I have made the map modal to a larger size. Here is the screenshot.
![Screenshot from 2019-04-14 16-58-23](https://user-images.githubusercontent.com/17192149/56092234-f6509800-5ed6-11e9-8c29-cbe20a656e71.png)

**Comment by Souravirus** [comment]
Hi @jywarren, the subscribe button is even not working in the original public lab website in the tags page. So, there is a problem with it already in the main repository. So, we can open another issue for that. Also, with that, all the issues are solved. Please see to this.
Thank you!!

**Comment by Souravirus** [comment]
Hi @jywarren, now every bug is solved except the one about the follow button on the tag page which was already present and was not due to bootstrap 4. I have also made the dropdown alignment correct. Here is the screenshot of it.
![image](https://user-images.githubusercontent.com/17192149/56357199-a33d5480-61f8-11e9-8966-0d52263de76c.png)

Please see to this.

**Comment by jywarren** [comment]
Oh this is super. Let's do one more pass and then... go for it? @sagarpreet-chadha @gauravano @SidharthBansal @cesswairimu @stefannibrasil @milaaraujo @ViditChitkara can you try this out and highlight any serious issues? 

We will surely have a few days where things get broken a lot, but we can minimize it with one last final check!!! 👀

**Comment by jywarren** [comment]
@Souravirus will you be pretty available next week if we merged and published this, to help with fixes? Thank you SO MUCH for all of this.

**Comment by Souravirus** [comment]
Yeah I will be available the next week. Thanks!!

**Comment by stefannibrasil** [comment]
Is there a PR with the changes? I could take a look, for sure! :v:

**Comment by stefannibrasil** [comment]
This doc was really helpful when  was doing the same on MapKnitter -> https://getbootstrap.com/docs/4.0/migration/

**Comment by jywarren** [comment]
Yes indeed! https://github.com/publiclab/plots2/pull/3937/  Thanks!

**Comment by sashadev-sky** [comment]
This will have no changes on Bootstrap upgrades at all but I wanted to post here that I made a PR to upgrade sass-rails to `sassc-rails` (it really doesn't change anything at all except a few file names so it is safe to merge in my opinion!) . Please see here: #5548

**Comment by Souravirus** [comment]
Hi @stefannibrasil, you can see the changes [in the unstable branch.](https://unstable.publiclab.org/). Thank you !!

**Comment by stefannibrasil** [comment]
HI all, I did a walk-through on the unstable branch and the only difference that I noted was a space missing after the Log in button in the Log in modal. Other than that, looks good to me :shipit:

**Comment by Souravirus** [comment]
Hi @stefannibrasil, I am really sorry that the unstable branch was currently not holding the bootstrap 4 changes as there were other commits pushed to it. So, can you please see the changes again sometime later.
Thank you!!

**Comment by Souravirus** [comment]
Ok I have pushed the changes. Please see it again after some time. Thank you!!

**Comment by stefannibrasil** [comment]
oh, okay :v: 

The front page is looking weird. Maybe someone pushed other commits again?
The carousel is not working and all of the static content (social media icons, questions button, etc.) are not showing.

### Some spaces to be added:
 * between the nodes and the pagination buttons (front page);
 * after node types buttons on /search page;
 * between nodes results ( the read more button is attached to the other node's image);
 

### General notes
* The footer is different when you navigate between the pages. For example, in the Dashboard, I see a different footer than the one being shown at the front page;
* Also in the Dashboard, when I clicked on 'Share your work', the dropdown is floating to the right, not beneath it;
* When adding a question, in the button group, the Markdown is not at the same line as the others;
* In the highlighted note that appears in the Dashboard, the text 'Node title by user1 from Public Lab Blog` is not aligned;
* The 'enter tag' placeholder is not possible to read here, for example, https://unstable.publiclab.org/getting-started (maybe removing the caret solves this, since it's already visible that it's a button?)
* The button group here is not aligned https://unstable.publiclab.org/wiki/plots-staff
* Align the button hat the /subscriptions page;
* I think these buttons for Questions and Research notes are too big https://unstable.publiclab.org/wiki/organizers
* Just the 'logout from all devices' option is showing up, not sure if this is intentional;

I think that was all, good job! :tada:

**Comment by gauravano** [comment]
- [ ] ![Screenshot from 2019-04-24 17-15-54](https://user-images.githubusercontent.com/20878070/56657052-ae8af700-66b4-11e9-8428-337a6ef90b05.png)

@Souravirus can I commit directly on your PR to resolve some bugs? Thanks!

**Comment by gauravano** [comment]
@Souravirus I have opened a PR against your bootstrap-4 branch - https://github.com/Souravirus/plots2/pull/1

**Comment by gauravano** [comment]
Moving to #5612

**Comment by gauravano** [comment]
Thanks everyone!!
