### ISSUE TITLE
Capitalize searchbox placeholder  in subscriptions

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5191]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** . 
* The input form for `enter tags` is  in lowercase

![Screenshot from 2019-03-20 13-33-27](https://user-images.githubusercontent.com/26685258/54668757-aa981200-4b15-11e9-8518-75e05bdd6aa8.png)

1. Change this line https://github.com/publiclab/plots2/blob/master/config/locales/en.yml#L662 to enter_tags: "Enter tags"
- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by IshaGupta18** [comment]
@vaarigupta you can work on this one!

**Comment by vaarigupta** [comment]
> @vaarigupta you can work on this one!
Thanks a lot .I look into it and continue with it

**Comment by techchic** [comment]
Hello can I work on this as well

**Comment by techchic** [comment]
Hey can I work on this as well?

**Comment by IshaGupta18** [comment]
Hey this is actually assigned. You can look for other FTOs to work on!
Thanks a lot!

**Comment by Linda-Ikechukwu** [comment]
Hi, has this issue been resolved, if not can I be assigned to it? . I'm an outreachy intern.

**Comment by CleverFool77** [comment]
Hi @Linda-Ikechukwu Can you check that whether there is change in development in latest fetched changes? If not, then you can move forward or else this issue would close down.

Thanks !!

**Comment by cesswairimu** [comment]
@Linda-Ikechukwu, it seems like this is not  fixed yet..Go ahead and work on it. Thanks

**Comment by SidharthBansal** [comment]
Is this issue solved?

**Comment by redahaq** [comment]
Hi @CleverFool77 , has this issue been resolved? If not I'd love to work on it. Thank you.

**Comment by shubhangikori** [comment]
Hey! Can I work on this issue?

**Comment by cesswairimu** [comment]
Hi @shubhangikori yes you could work on it. But lets leave the alignment as left aligned. I see we are using left alignment for all of our search boxes. This is what you need to do for this issue.


### Update 
**Todo:** Change this line  https://github.com/publiclab/plots2/blob/master/config/locales/en.yml#L662  to enter_tags: "Enter tags"


Thanks
