### ISSUE TITLE
Add shortcut keys for rich legacy editor

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5193]
## Description
I found this issue when I was working with editor and with my continuous habit of using shortcut keys in editors. The rich legacy editor didn't had this feature but it was present in other editor (rich editor and markdown editor).
I realised that we can add shortcut keys for these features in legacy editor.

![Screenshot from 2019-03-20 16-37-46](https://user-images.githubusercontent.com/26685258/54679972-a6c4b980-4b2e-11e9-808c-b5bb36d96c72.png)

Add shortcut keys for the features such as
* **BOLD** using `Ctrl + b`
* *Italics* using `Ctrl + i`

Shortcut keys feature is very usable and helpful as they provide an easier and usually are quicker method of navigating and executing commands.

## How to do this ?
Use keypress methods to trigger keypress events using JavaScript.

**Comment by CleverFool77** [comment]
@publiclab/plots2-reviewers Is this issue correct ?

**Comment by CleverFool77** [comment]
If approved, I would like to work on this 
Thanks :)

**Comment by avsingh999** [comment]
Hi, @CleverFool77  I found there are a feature ctrl+b and ctrl+i. If  I am wrong then correct me, please.
thanks : )

**Comment by CleverFool77** [comment]
Hi @avsingh999 I guess this is available in simple editor but not the rich legacy editor.

**Comment by IshaGupta18** [comment]
Even I think it already exists, in the rich editor. Legacy editor is different, it's not the same as rich.

**Comment by CleverFool77** [comment]
Hi @IshaGupta18 Maybe I got confused with name. Actually I wanted to say that it's not available in legacy editor. And I was considering rich as simple editor and another as markdown editor.

**Comment by CleverFool77** [comment]
Hi @avsingh999 @IshaGupta18 I've updated the the name as legacy instead of rich. Sorry for the misinformation.

**Comment by IshaGupta18** [comment]
No worries, please ask the reviewers if this issue is valid or not. Would you mind if I work with you on this one, if approved?

**Comment by CleverFool77** [comment]
Sure @IshaGupta18 We have two features, Both of us can go for one :wink:

**Comment by IshaGupta18** [comment]
Great! That would be lovely. We should wait for the reviewers to approve this issue because we don't know how useful it might be.

**Comment by avsingh999** [comment]
@CleverFool77 Yes I think you are right.

**Comment by avsingh999** [comment]
@jywarren @gauravano @SidharthBansal  what do you think about it.
thanks : )

**Comment by jywarren** [comment]
Hi! I super-appreciate the ideas, though in this case I think we're slowly
trying to get rid of the legacy editor. What about this -- we used to have
a feature where you could "submit" a comment by pressing control-return --
but it doesn't work anymore. I think the code is here, but it seems broken:

https://github.com/publiclab/plots2/blob/3cc86dd72e4baf887ba4bb38b979876029c3bce4/app/assets/javascripts/comment.js#L36

Would one of you like to, in the spirit of adding key bindings, get this
working again? It's so nice to be able to submit a comment quickly like
that. What do you think?

**Comment by IshaGupta18** [comment]
Even I thought so, that's why I was waiting for the review. Yes, I think this can be done, also, I was thinking that we could implement that when we have typed in the search bar, pressing enter should load the next page, instead of clicking on the search button. What do you think?

**Comment by gauravano** [comment]
> we have typed in the search bar, pressing enter should load the next page, instead of clicking on the search button.

We already have this for nav search bar. Any other search bar, you're talking about?

Also, have anyone started with https://github.com/publiclab/plots2/issues/5193#issuecomment-474905205? 

Thanks!

**Comment by CleverFool77** [comment]
Hi @gauravano 
Oh!! I seem to miss out . Should I add it in similar way like done in shortcut keys for `search` ?

**Comment by gauravano** [comment]
I think it's already implemented like @jywarren mentioned so there might be a bug, which we need to solve. 

Thanks!

**Comment by CleverFool77** [comment]
Hi @gauravano . Just fixed the issue on https://github.com/publiclab/plots2/pull/5473

**Comment by gauravano** [comment]
:+1:
