### ISSUE TITLE
Add on hover effect to profile icon on navbar

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/plots2#5194]
# Description
In #5093 the navbar UI was updated to add a fontawesome icon however this shows no animation on hover

# Expected
The icon shows animation on hover like this.

![iconcss](https://user-images.githubusercontent.com/32260628/54675268-3ca71700-4b24-11e9-96de-ecf153c66b90.gif)

**Comment by ananyaarun** [comment]
Id like to work on this :)

**Comment by CleverFool77** [comment]
Hi @ananyaarun I guess there was already an issue for the hover on navbar right ?

**Comment by ananyaarun** [comment]
@CleverFool77 , Correct me if i am wrong but i think that issue was to change click to on hover right ? This basically highlights the recently added profile icon on the navbar like the other nav bar items get highlighted.
