### ISSUE TITLE
User unable to set pwd upon SIGNING IN with OAUTH

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/plots2#5198]
I have signed up earlier via Github. Now when I try to log in using the username mentioned in my profile, the portal gives an error message saying `This account doesn't have a password set. It may be logged in with Github account, or you can set a new password via Forget password feature`. But when I try to log in using my email as the username, it is successful.
It seems the issue appears when someone `Sign Up` via the third party.

***Current behaviour:***
![peek3](https://user-images.githubusercontent.com/32747809/54693866-514bd500-4b4d-11e9-8825-45b7f6f05eb3.gif)

***Expected behaviour:***

- [ ] User should be able to log in using email as well as username as the input.

**Comment by gauravano** [comment]
Hey @divyabaid16, yes, we are looking for making improvement in our OAuth system. Would you like to help us with that?

You can ask your queries here and @SidharthBansal will also help you as he has the better understanding of our OAuth system. Thanks!

**Comment by divyabaid16** [comment]
@gauravano the password fields in the edit profile section can also be improved to become more user-friendly, should I open a sperate issue for that?

**Comment by gauravano** [comment]
Go ahead!

**Comment by SidharthBansal** [comment]
Hi, is anyone working on it?
If no, I can work on it.

**Comment by gauravano** [comment]
Hey @SidharthBansal, you can work on it. Thank you!!

**Comment by SidharthBansal** [comment]
oh great
on it!

**Comment by SidharthBansal** [comment]
One interesting thing to observe is you are able to login with an email address. We don't allow saving of email addresses in the username column due to some conflicts with urls and existing users etc. Did you set up your password ever at Public Lab? @divyabaid16 

Thanks

**Comment by divyabaid16** [comment]
Hi @SidharthBansal I had setup my password using the reset password link.
![Selection_265](https://user-images.githubusercontent.com/32747809/69867510-03d35a80-12cd-11ea-95c2-2ddfc16615f9.png)
Thanks!

**Comment by SidharthBansal** [comment]
Can you please check the behaviour again?
I hope GitHub will work finely.

**Comment by divyabaid16** [comment]
Ya, login with Github is working.

**Comment by SidharthBansal** [comment]
Great!
Please do following
1. Log out Pl.org
2. Log in with email address and password.
Tell me the output. Thanks

**Comment by SidharthBansal** [comment]
@divyabaid16 can you please check and tell?
Thanks

**Comment by divyabaid16** [comment]
It is showing that my account doesn't have a password set, so I tried with forgot password, then it is showing some error. Do you know why this is happening? Or maybe my account is just registered by Github so it doesn't allow a separate login?
![Selection_271](https://user-images.githubusercontent.com/32747809/71863784-fd35cf80-3123-11ea-9544-3b7c6fc6b91f.png)
![Selection_272](https://user-images.githubusercontent.com/32747809/71863785-fdce6600-3123-11ea-8202-77533017c2b1.png)

**Comment by SidharthBansal** [comment]
Have you checked it again?
It should work now

**Comment by divyabaid16** [comment]
Ya, the screen shot that I posted was today's. I don't know but for me, it
is not working. Can someone else also check who has logged in from Github.?

**Comment by SidharthBansal** [comment]
My GitHub is working

**Comment by SidharthBansal** [comment]
Can anyone else pls check and tell

**Comment by SidharthBansal** [comment]
Are your other providers fb Twitter Google working?

**Comment by SidharthBansal** [comment]
@Uzay-G please check by logging in by all 4 providers. We can add on this too in your GCI task if this is a error

**Comment by SidharthBansal** [comment]
Google working

**Comment by SidharthBansal** [comment]
Github working

**Comment by SidharthBansal** [comment]
Twitter and FB also working.

**Comment by divyabaid16** [comment]
Yes, all others are working for me, if I login with them.

**Comment by SidharthBansal** [comment]
What about login by email and pwd?

**Comment by divyabaid16** [comment]
I have not set up my password, so I clicked on forget password, and from
that link I tried to set my password, but it didn't work out.

**Comment by SidharthBansal** [comment]
What problem are you facing in creating new pwd?

**Comment by SidharthBansal** [comment]
@Uzay-G you also faced similar problems yesterday.(Maybe your today)
Please tell me what you faced. You can work on this too as it is inter
related. If we will require any PR then it will be medium gci task I guess

**Comment by SidharthBansal** [comment]
If we don't require any PR then it will be zero points and no gci task. I
hope it is okay with you

**Comment by SidharthBansal** [comment]
> I have not set up my password, so I clicked on forget password, and from
that link I tried to set my password, but it didn't work out.

What happened?
What error did you face in setting up your password?

**Comment by Uzay-G** [comment]
Oh sorry @SidharthBansal I hadn't seen this. I could try and investigate but I wouldn't know where to start since I am not having the problem anymore.

**Comment by SidharthBansal** [comment]
You have to signup through GitHub at local. Then try to set up password

**Comment by Uzay-G** [comment]
I tried. I am having this problem also when I do the following steps:
- Sign up
- Reset password
- Login **with username**

Logging in with email=> password works. 
I will try to fix this

**Comment by Uzay-G** [comment]
Alright I found the problem.
It's in the website login part of the `user_sessions` controller:
https://github.com/publiclab/plots2/blob/d8c644a5304211ad461374d2bba4c90b25f86100/app/controllers/user_sessions_controller.rb#L120-L127

As you can see, the error message that says the check to see if the user has a password only goes through if the `user` exists. The `user` is found by matching the `username` entered when logging in to the usernames of the db.

So if you login with your email as username, `user` is nil and this part is ignored. The code keeps going and the codebase checks if the user has logged in with his email as username:
https://github.com/publiclab/plots2/blob/d8c644a5304211ad461374d2bba4c90b25f86100/app/controllers/user_sessions_controller.rb#L131-L134

If the info matches, he is logged in.

This explains why logging in with email works. Now we have to understand why the `password_checker` function is saying the password is not set.

**Comment by SidharthBansal** [comment]
Great finding.

**Comment by Uzay-G** [comment]
Thanks! Do you know where the `password_checker` function is defined? I have grepped the codebase but can't find it. It would be useful to debug

**Comment by SidharthBansal** [comment]
It is not a function. It is just a variable I guess
1 for fb. 2 for Twitter and so on.
I don't remember the order.

**Comment by SidharthBansal** [comment]
Check the hash related to it

**Comment by Uzay-G** [comment]
Yeah I will. I think we don't change the variable when the password is set and that is the problem

**Comment by Uzay-G** [comment]
Oh I found it! I love solving bugs :smile:

**Comment by SidharthBansal** [comment]
Oh great

**Comment by Uzay-G** [comment]
I am opening a pr :+1:

**Comment by SidharthBansal** [comment]
Sure.

**Comment by Uzay-G** [comment]
We can close this. It was solved in #7291
