### ISSUE TITLE
Reply-to-comment has a small issue (but is awesome)

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5199]
@ViditChitkara the system is live and it works! It's awesome! 🎉 

I noticed that although the comment posted, i saw an error in the original form:

![image](https://user-images.githubusercontent.com/24359/54699605-ba105e80-4b07-11e9-9108-72cfe40ff438.png)

Would you mind taking a look? Thank you!

https://publiclab.org/notes/warren/01-02-2019/brainstorming-for-summer-of-code-2019#c23332

**Comment by ViditChitkara** [comment]
Sure, will have a look!! Maybe some js related issues!
