### ISSUE TITLE
Allow visibility in password

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5201]
## Description
Currently, the password is hidden and we can't confirm that the password we wrote is correct or not. So Instead we can have a toggle icon to make the password visible.

![Screenshot from 2019-03-20 22-34-24](https://user-images.githubusercontent.com/26685258/54704630-20759b00-4b61-11e9-8ef5-d5d9c07ef8b1.png)

Thanks :)

**Comment by CleverFool77** [comment]
I'm interested in working in this .
Thanks :)

**Comment by CleverFool77** [comment]
Hi @jywarren. I was trying out this issue in my local since a day. And In that time, I found it to be a most suitable solution in JS. And while doing opening the PR, I remembered that I forgot to open the issue for this. That's why this had a commit of change even before the issue was open. :3

**Comment by jywarren** [comment]
:-) thank you!!!
