### ISSUE TITLE
listing answered questions after deprecating Answers

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5203]
Hi @ViditChitkara -- just want to open an issue to tackle how this will work:

https://publiclab.org/questions/answered/

Both on a) how we'd list them on this page, and also b) how answered comments are represented when viewing a list of comments in a question page?

I know you've thought this through, i just want to try to sum it up in one place as we take the next space. 

Thanks!

**Comment by ebarry** [comment]
Excited for your achievements on this @ViditChitkara !!!

**Comment by ViditChitkara** [comment]
Thanks a lot @ebarry , @jywarren has equally helped me with this!! A big thanks to him too!
@jywarren For b), currently they are just like normal comments, should there be a separate indication for them? But then I guess we'll somehow have to figure out which comments were originally answers. For a) Should we rename the answered tab or something? and the questions which have 'answered' tag?
Thanks a lot!! This is really interesting.

**Comment by ViditChitkara** [comment]
@jywarren next I'll be starting with this, any ideas about how this is going to work out?

**Comment by jywarren** [comment]
So first, i think we need to think about how we mark a comment as "accepted" -- 

the simplest, to me would be to "react" to it with a ✅  emoji, and treat that as "accepted"? Or we could think of using 👍 in the sense of "ok, great, thank you" -- maybe we need input from @publiclab/community-reps on which is more appropriate to replace the "accepted comment" status? 

But in the meantime, we could begin implementing a system to add such reactions (whatever the emoji is that we choose) using the old Answer records. Are we able to scan all accepted answer records and add a reaction to their corresponding new comment record?

**Comment by jywarren** [comment]
Then, for the /questions/answered page, we can just show any question that has had a comment (for now) -- later we could try to join whether the comment was "accepted" -- is that ok?

**Comment by ViditChitkara** [comment]
That's a good idea to add a ✅ emoji to it. Yes, we can identify all
accepted answers. However, we'll have to find out a way to find the
corresponding comments which were created.
One could be, comments having the exact same timestamp as answers (if not
comparing the content)? Will this be a good idea??
Then we could add the emoji to it? We can call it "Verified". And this
emoji won't be available in the dropdown. With a comment there will be a
"verify comment" link available to admins, moderators, etc. Which can be
used to add the verify emoji to it.
What do you think?

**Comment by jywarren** [comment]
Oh, very clever! Timestamp was copied exactly, right? yes, that should
work! if you wanted, we could also compare the text content itself. But i'm
not sure we'd get every one... it could be worth a bit of testing.

**Comment by ViditChitkara** [comment]
Yes, timestamp was copied exactly. However, we'll have to figure a way to test it. For the time being will compare the timestamp!! Let's see how things pan out after doing that.

**Comment by ebarry** [comment]
Who would be able to mark a comment accepted via a green check mark? A) Only the original questioner? B) The original questioner + site moderators? C) Anyone logged into the site? 

I find that i am in favor of B but interested in a discussion

**Comment by ViditChitkara** [comment]
@ebarry , Even I'm in favour of B. Let's hear from others though and then I think we can go forward with this.
