### ISSUE TITLE
ActiveRecord::Fixture::FixtureError: table "comments" has no column named "reply_to".

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#5207]
I just rebase my branch with the latest master and now all my tests are failing with this error

```
ActiveRecord::Fixture::FixtureError:         ActiveRecord::Fixture::FixtureError: table "comments" has no column named "reply_to".
```
:confused: Anyone else experiencing this? Any ideas for fixes or causes?

**Comment by gauravano** [comment]
Mentioning @jywarren @ViditChitkara as this issue seems related to https://github.com/publiclab/plots2/pull/4537/ . Thanks!

**Comment by jywarren** [comment]
Ah, there was a new migration added - i think you need to run `rake
db:migrate`!

**Comment by gauravano** [comment]
tried that, no success

**Comment by cesswairimu** [comment]
Seems we do not have `reply_to` column in env test.
model from console in test 
```
Comment
  cid: integer
  pid: integer
  nid: integer
  uid: integer
  subject: string
  comment: text
  hostname: string
  timestamp: integer
  status: integer
  format: integer
  thread: string
  name: string
  mail: string
  homepage: string
  aid: integer
  comment_via: integer
  message_id: string
  belongs_to :answer (foreign_key :aid)
  belongs_to :node (foreign_key :nid)
  belongs_to :user (foreign_key :uid)
  has_many :likes
  has_many :replied_comments (class_name :Comment, foreign_key :reply_to)
```
in development environment
```
Comment
  cid: integer
  pid: integer
  nid: integer
  uid: integer
  subject: string
  comment: text
  hostname: string
  timestamp: integer
  status: integer
  format: integer
  thread: string
  name: string
  mail: string
  homepage: string
  aid: integer
  comment_via: integer
  message_id: string
  tweet_id: string
  reply_to: integer
  belongs_to :answer (foreign_key :aid)
  belongs_to :node (foreign_key :nid)
  belongs_to :user (foreign_key :uid)
  has_many :likes
  has_many :replied_comments (class_name :Comment, foreign_key :reply_to)

``
:thinking:

**Comment by jywarren** [comment]
Hi Cess, the new migration should create the reply_to column, did it not work?

**Comment by cesswairimu** [comment]
It did not create one on the test env just the dev env

**Comment by jywarren** [comment]
Oh, hmm. @ViditChitkara - do you know why the migration may not be running
for @cesswairimu? If the schema.rb file is correct, it should be used to
run tests, right?

**Comment by eRy-sk** [comment]
Hello, I'm Japanese.
I don't understand English well, so I use Google Translate as a reference.
I can't write English well, but please forgive me.

Specify a test environment and try to migrate.
```bash
$ RAILS_ENV=test rake db:migrate
```
Or reset.
```bash
$ RAILS_ENV=test rake db:migrate:reset
```
However, since I'm a beginner, It is just a suggestion.
I hope you will find it useful.

**Comment by cesswairimu** [comment]
This solved it thanks so much @eRy-sk

**Comment by gauravano** [comment]
Hey @eRy-sk we would love to have more help from you if you're interested -https://github.com/publiclab/plots2/issues/ . Thanks!
