### ISSUE TITLE
Refactor nids in tag model

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#5215]
### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

**Problem**:

I extracted tids and nids to methods in the `tag model` https://github.com/publiclab/plots2/blob/master/app/models/tag.rb#L437-L443

📝 **Update**: 

We want to remove wherever else they are defined in the model so that they can use the new methods.

Changes 
1.  Delete this lines https://github.com/publiclab/plots2/blob/master/app/models/tag.rb#L210-L213

After changing run the tests and make sure we didn't break anything
- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

**Comment by cesswairimu** [comment]
@techchic here you go

**Comment by techchic** [comment]
Great! Thanks

**Comment by edwd42** [comment]
Hi cesswairimu. I am new to open source and public lab.  I'm going to attempt this issue.  Looks easy, but not sure what will happen when I click commit.  Also, not sure where or how to run the tests.  Guess I'll find out soon enough :sweat_smile:

**Comment by techchic** [comment]
Hey @edwd42 I am currently working on this.

**Comment by cesswairimu** [comment]
Hi @edwd42 will add your name for to a list of people looking for ftos pretty soon you should get an issue. and don't worry we are here to help. :smile: Thanks

**Comment by edwd42** [comment]
oh hey sorry techchic.  didn't see that.

**Comment by Michaellin250** [comment]
Is this issue still open?

**Comment by gauravano** [comment]
@techchic are you working on this one. If yes, can you please tag this issue in your PR. Thanks!

**Comment by gauravano** [comment]
hey @Michaellin250, we can add your name to the  https://github.com/publiclab/plots2/issues/4963 if you like? Or, you can go through issues https://github.com/publiclab/plots2/issues/ and claim the one you find interesting. Thanks!

**Comment by susanreenesaa** [comment]
I am taking up this issue

**Comment by SidharthBansal** [comment]
Is this issue solved?
