### ISSUE TITLE
Addition of small display picture

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/plots2#5217]
Can we add a small display picture on the top right corner, the same as we have in the Github? It's like a thumbnail. This might also help the user to identify whether he/she's logged in or not.
Currently, when a user uploads a profile picture there's no thumbnail, it might be a good idea if the site display's a thumbnail on the top right.

**Comment by divyabaid16** [comment]
@publiclab/plots2-reviewers can this be an issue to be worked upon?

If yes, I would like to work on this!

**Comment by divyabaid16** [comment]
To explain better, currently there is an icon at top right corner `fa fa-user-circle`. When I upload my profile pic, that must change to the pic that I have uploaded when I save the changes. 
But, even after upload, it is showing the same icon. 
I wish to solve this issue here and resulting which I would get the image of the picture I uploaded instead of that icon.

**Comment by jywarren** [comment]
Oh, this sounds interesting... but the image is so small? I like where
you're going with this but perhaps we should pursue this idea on the design
for the new People page -- see the bottom of
https://publiclab.org/notes/edie_blues/01-16-2019/what-do-you-think-about-this-design-for-the-people-page

https://publiclab.org/people is where we're thinking of adding this kind of
small circular image. Want to try working on that a bit?

Thank you, i love the creativity here!

**Comment by divyabaid16** [comment]
@jywarren I really liked the new design for the People page. I will try out a few new things there and will try to give my input in every possible way. 
Thank you so much!
