### ISSUE TITLE
Make the link to home page more prominent on website [Discussion]

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/plots2#5218]
# Description
The link to home page on the website ie "Public Lab" visible on the top left corner of the navbar is a bit ambiguous to users as it doesnt stand out as a "link" to home page. Hovering over it causes no effect at the moment either.

![publiclab](https://user-images.githubusercontent.com/32260628/54756036-5ec89400-4c0d-11e9-938a-aee76a7629c9.png)

# Expected

- On hover effect can be added to this to make it look/behave more like a link.
- Or text can be changed to "HOME PAGE" or "HOME" instead of public lab.

**Comment by ananyaarun** [comment]
Any thoughts on this change ? I'd like to work on this once finalized :) Thanks.

**Comment by gauravano** [comment]
We have "Dashboard" in navbar. Isn't that sufficient?

**Comment by ananyaarun** [comment]
Yes absolutely, I may be wrong but Consider a user not logged in/unregistered . Just visiting the website to read notes and wikis. To get to the home page they dont have a dashboard option and have to click on Public Lab which doesnt really look like a link to homepage. Without knowing this the user may just keep using back arrow to navigate.
For a logged in user i see both dashboard and Clicking on public lab takes you to user dashboard.

**Comment by gauravano** [comment]
Hmm, so should we add something similar to "dashboard" for users which browse site without logging-in. Something like "research" just to match URL? Also, at same place at "dashboard" link?

@jywarren @ananyaarun

**Comment by ananyaarun** [comment]
Yes ! That wud be nice to have. The URL can match /research.
Regarding position , For an unregistered user, "Login" and "sign up" options are displayed while for a registered user "Dashboard" and the profile icon are.
So adding a link at the dashboard place would involve creating a new item on the navbar. Am i right ?
@jywarren @gauravano

**Comment by ananyaarun** [comment]
@gauravano @jywarren thoughts on this ?
I think we can make this a GCI issue, at least the part to add on hover effect :)

**Comment by jywarren** [comment]
Sure!

**Comment by cesswairimu** [comment]
A tooltip was added  https://github.com/publiclab/plots2/pull/8504 which took care of this issue. Closing this. Thanks
