### ISSUE TITLE
Remove the show graph link on the tags page

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#5222]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

📋 Step by Step
 🙋 Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

 📝 Update the file $FILENAME in the $REPO repository (press the little pen Icon) and edit the line as shown below.

See this page for some help in taking your first steps!

Below is a "diff" showing in red (and a -) which lines to remove, and in green (and a +) which lines to add:

$DIFF
 💾 Commit your changes

 🔀 Start a Pull Request. There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

You can also edit files directly in your browser and open a pull request from there.

 🏁 Done Ask in comments for a review :)
Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update within a week of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

Is someone else already working on this?
🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- If someone seems stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

🤔❓ Questions?
Leave a comment below!

Having the show graph link, duplicates the graph on the page.

![Screen Shot 2019-03-21 at 8 04 50 PM](https://user-images.githubusercontent.com/35326753/54759740-b6b6c900-4c14-11e9-961d-f1ce0ebb40f3.png)

**Comment by gautamig54** [comment]
@gauravano Kindly look into this and if correct, make this as an FTO issue! Thanks!

**Comment by gauravano** [comment]
hey @gautamig54, yes, it will make a good FTO. Would you like to convert it in FTO by following the steps mentioned here https://github.com/publiclab/plots2/issues/4963?

**Comment by gautamig54** [comment]
@gauravano Yea, sure! Thanks!

**Comment by gautamig54** [comment]
@publiclab/reviewers Kindly label this issue as FTO. Thanks!

**Comment by gauravano** [comment]
Please add the link where changes need to be done and what change

**Comment by GettyOrawo** [comment]
Hello @gauravano and @gautamig54 . Is it okay if I take this up?

**Comment by CleverFool77** [comment]
Hi @GettyOrawo You have done first timer before. Would you mind if a new user who haven't contributed yet is given this chance. :thinking:

**Comment by jywarren** [comment]
Just a note, i think this could be in a database-backed feature, not in the
codebase? May be worth checking first!

**Comment by gautamig54** [comment]
@jywarren yes, it is not present in the codebase. How can this issue be resolved?

**Comment by jywarren** [comment]
ah, so this is run from a database record. For better or worse, only admins
can change it - i'm happy to remove it, great catch!

**Comment by gauravano** [comment]
Thank you all!
