### ISSUE TITLE
Add a modal showing the message of deprecation for legacy editor

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5223]
## Description

I noticed few bugs and additional features required in legacy editor and thought of working on it. 
When I opened the issue, one of the mentors mentioned that the legacy editor is slowly being deprecated.
https://github.com/publiclab/plots2/issues/5193#issuecomment-474905205

## Expected
In case a newbie starts working on some bugs or new feature of that editor, we can show in the modal showing the message of deprecation.
And for users, It would be shown to them so that they get accustomed to the new editors and when the legacy editor goes away they don't face problem shifting to the editor
So It's better to prefer rich/markdown editor.

**Comment by CleverFool77** [comment]
@publiclab/plots2-reviewers Is this Issue correct ? 
If approved, I would like to work on this. :)

**Comment by gauravano** [comment]
@publiclab/community-reps is this final call?

**Comment by CleverFool77** [comment]
There is already a notice given with message of `This is the legacy editor. For the new rich editor [link]`
We can add some lines which was mentioned in Issue.

![Screenshot from 2019-03-21 21-50-54](https://user-images.githubusercontent.com/26685258/54767739-d5708c00-4c23-11e9-8bea-2e85cdc4e13c.png)

**Comment by CleverFool77** [comment]
Maybe something like this - 
![red](https://user-images.githubusercontent.com/26685258/54769100-92fc7e80-4c26-11e9-959f-9b08318068d5.gif)
