### ISSUE TITLE
Repeating info on creating user name 

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#5225]
We were creating a new login and found that the user name we wanted was taken, but to figure this out we needed to submit the form, and when we did the data we had put in was deleted and we had to recreate it. It also brought us to a whole new page rather than the popup we were on. 

Is there a way to store this on the page so it doesn't refresh to a blank "create a login" page?

We were using Safari. 

<img width="1080" alt="Screen Shot 2019-03-21 at 11 18 35 AM" src="https://user-images.githubusercontent.com/7490478/54767434-1daf9000-4bcb-11e9-864b-e00a8a688748.png">

**Comment by jywarren** [comment]
Yes i think someone is thinking about client-side validation -- @gauravano
do you remember who this was? Maybe @cleverfool77 would be interested in
trying this out!

There is an API query we could make from JavaScript as you type; we'd want
to be careful using it too much, but maybe a couple seconds after you enter
the username, it could query:

https://publiclab.org/api/srch/profiles?query=jywarren

and see if it gets any results?

**Comment by swiatek7** [comment]
Could I claim this issue?

**Comment by gauravano** [comment]
I tried to reproduce this but doesn't face this issue. In my case, the form was auto-filled again after getting errors.   

Browser: Chrome

@swiatek7 go ahead. Thanks!

**Comment by gauravano** [comment]
And, @jywarren @ananyaarun is working on validation issues, maybe she would be interested in helping here too.

**Comment by ananyaarun** [comment]
Definitely :) Thanks @gauravano 
I tried to reproduce this issue, But even i see my form was auto-filled after getting the error msg and i didn't loose the entered data.

Browser : Firefox

Is this a browser related issue ?

**Comment by gauravano** [comment]
Maybe. You can test via https://www.browserling.com/

**Comment by ananyaarun** [comment]
@gauravano , so i tested with the safari browser and the form after submitting with the same user name did give error but i could see the form auto filled when i tried to sign up again . 
I dont seem to get this issue on Safari, chrome or firefox.
I tried on internet explorer as well but as i reported in #5096 none of the features seem to work right here!

**Comment by CleverFool77** [comment]
Hi everyone,
I seem to miss out the mention in this issue.
Sorry for the delay.
I would like to test this issue out.

**Comment by CleverFool77** [comment]
Hi @jywarren @gauravano ,
I'm working on the issue https://github.com/publiclab/plots2/issues/5361 with PR https://github.com/publiclab/plots2/pull/5368 based on form validation.
That PR adds realtime form-validation and prevents submission of form until each field is valid and hence, prevents losing of data.
I would like to work on realtime username validation check.

**Comment by gauravano** [comment]
@steviepubliclab @jywarren can you try the signup again and update the status? Thanks!

**Comment by gauravano** [comment]
That's great @CleverFool77. Also, if you hit the block while validating captcha, you can refer PR https://github.com/publiclab/plots2/pull/4444/ where @kevinzluo did great work. We were not prepared at that time for that but I think, now we are. Thanks!

**Comment by steviepubliclab** [comment]
Hey!! It works 👍 

Thanks so much!! That's awesome. :)

**Comment by CleverFool77** [comment]
Hi @gauravano , So regarding the username validation check, should I create a new issue, as this issue is based on data being lost. 
Or should  I directly work on the username-validation check while referencing this issue.

**Comment by gauravano** [comment]
> should I directly work on the username-validation check while referencing this issue.

Yes, go ahead! Thanks @CleverFool77! Closing this one now.
