### ISSUE TITLE
Suggestion for a text edit on the signup page

### ISSUE THREAD

**Issue by publiclab-mimi** [publiclab/plots2#5227]
Hey team,

A suggestion for an edit to the signup page to make the Code of Conduct/Privacy Policy more visible. If we could move the following line of text above the sign up button it will be more prominent for new users & (in theory) more widely read. 
Text: "By signing up, you agree to the Code of Conduct, which applies to all online and in-person spaces managed by the Public Lab community and non-profit. You also agree to our Privacy Policy."
See below for current setup and the proposed setup from a different site. 

<img width="877" alt="Screen Shot 2019-03-21 at 11 49 35 AM" src="https://user-images.githubusercontent.com/48802639/54769847-15a61f00-4bd0-11e9-9f54-86a59e64e040.png">

<img width="433" alt="Screen Shot 2019-03-21 at 11 50 11 AM" src="https://user-images.githubusercontent.com/48802639/54769857-18a10f80-4bd0-11e9-93c7-6dd7178da297.png">

**Comment by jywarren** [comment]
Thanks for the suggestion, Mimi! I think we could do this relatively simply
by moving all the below-button text above the button, but do you want
/some/ above and /some/ below, or is all above OK?

We'd move these lines up to line 100 of the file:

https://github.com/publiclab/plots2/blob/3200f4bca5830dc2c5cd49d0147b09cfef84564d/app/views/users/_create_form.html.erb#L122-L124

Thanks!

**Comment by publiclab-mimi** [comment]
I can defer to the group on the some above/some below point, but I think all above would be a simple solution to emphasizing what pressing “sign up” actually means.

**Comment by edwd42** [comment]
I would like to work on this issue.  May I claim it?

**Comment by gauravano** [comment]
Go ahead @edwd42! Thanks!

**Comment by edwd42** [comment]
OK thanks! Will do.

**Comment by edwd42** [comment]
Hi @gauravano can I ask you something?  This is my first time editing in github.  The edit icon says I must be in a branch.  So there are many first-timers-something branches.  Should I pick any particular one, or do I create a new branch, and how to do that?  
Thanks!

**Comment by gauravano** [comment]
You need to fork the repo first and then create a new branch. have you installed plots2 locally?

**Comment by edwd42** [comment]
Yes, that's what I thought.  But was also told by Jeff to edit right in the github editor.  I am cloning  plots2 on cloud9 again from a fork.  So will create my branch there.  
Thanks very much for your help.

**Comment by gauravano** [comment]
Great! Feel free to comment here if you have any doubts.

**Comment by edwd42** [comment]
Hi @gauravano I completed the task and got the green check Able to merge on the PR page.  But the signup form looks nothing like the screenshot above.  How can I be sure I have the right page?  I clicked the link above  and edited plots2/app/views/users/_create_form.html.erb 
Can you take a look at this screenshot for me and verify I'm on the right page?  Before I submit the PR?
Thanks!
![Signup_form_issue_5227](https://user-images.githubusercontent.com/47794771/54855934-a82ce800-4cce-11e9-911d-ec1d58975691.png)

**Comment by edwd42** [comment]
Sorry I just noticed this line on the PR page, so I will ask my question there. Thanks.
* [ ] ask `@publiclab/reviewers` for help, in a comment below

**Comment by edwd42** [comment]
@publiclab/reviewers - I completed the task and got the green check Able to merge  on the PR page. 
![green_check_able_to_merge](https://user-images.githubusercontent.com/47794771/54856293-17570c00-4cd0-11e9-89dc-7254321fc7a7.png)

But the signup form looks nothing like the screenshot above. How can I be sure I have the right page? I clicked the link above and edited plots2/app/views/users/_create_form.html.erb
Can you take a look at this screenshot for me and verify I'm on the right page? Before I submit the PR?
Thanks!
![Signup_form_issue_5227](https://user-images.githubusercontent.com/47794771/54856308-2c339f80-4cd0-11e9-96cd-1037e94f6432.png)

**Comment by gauravano** [comment]
Hi @edwd42, the page looks different because of the different spam detection method in the development environment and in production. In production, we use Google recaptcha.

**Comment by edwd42** [comment]
OK, @gauravano   well thanks for pointing that out.  So is there a way to use recaptcha in dev too so I would see the same view?  For next time it comes up.
Thanks,

**Comment by gauravano** [comment]
You can change if condition in the file and add a key to see recaptcha in dev environment. Refer this how recaptcha works - https://rubyplus.com/articles/3661-Integrating-Google-reCAPTCHA-with-Rails-5-App. Thanks!

**Comment by edwd42** [comment]
Hi @gauravano I tried to register as indicated in that link's Step 1, but I responds with an error that my domain url on cloud9 is invalid.  I guess I need a real domain, but I cloned plots2 onto cloud9.  Do you have any suggestions for  add a key to see recaptcha in dev environment?
Thanks!

**Comment by gauravano** [comment]
You can use `rails server -b 127.0.0.1` to run server on http://127.0.0.1:3000/. And, you can add http://127.0.0.1 in domains list

**Comment by gauravano** [comment]
Actually, there's a easy way to - Go to config/initializers/recaptcha and change production to development there, so you don't need to generate keys for yourself

**Comment by gauravano** [comment]
![Peek 2019-03-25 16-11](https://user-images.githubusercontent.com/20878070/54913525-ec132d80-4f18-11e9-8a8f-4356e48be525.gif)

The view requires improvment with recaptcha too :point_up:

**Comment by edwd42** [comment]
Awesome tip @gauravano Thanks for pointing that out!  But I'm still getting the Are you human? spam filtering message and not the version you show above.  Maybe because I'm running it on cloud9?  idk.  I can clone it locally and see if I get any better results.
BTW, is this issue has-pull-request label finished and closed, or it it still open until I resolve this question of mine?  Thanks!

**Comment by gauravano** [comment]
The `has-pull-request` label is just for notifying others so they'd be aware that a PR is in progress against a task. Have you changes production to dev at signup view too?

**Comment by gauravano** [comment]
Hey, I just noticed you've raised 2 PRs for this issue - https://github.com/publiclab/plots2/pull/5234 and https://github.com/publiclab/plots2/pull/5233. Please close one. Thanks!

**Comment by edwd42** [comment]
Yes, I was confused about that too.  I was put on this first-timers-list https://github.com/publiclab/image-sequencer/issues/842 when I asked to be put on a list, and then was also put on https://github.com/publiclab/plots2/issues/4963

I submitted my PR and plotsbot responded (in https://github.com/publiclab/plots2/pull/5233) with: Your pull request is on the master branch. **Please make a separate feature branch** with a descriptive name like new-blog-design while making PRs in the future.

So I made a new branch, edited and tested my changes, and submitted that for PR.  That's when the second PR showed up(#5234).  So how do I close the first one #5233?

Sorry for the confusion, just learning...

**Comment by edwd42** [comment]
Oh, found it.  I think.  It now says closed.

**Comment by gauravano** [comment]
No issue. making a seprate feature branch is a good practice that's why we suggest it via bot, although, if you open a PR using master we'll consider it too :)

**Comment by edwd42** [comment]
hmmm.  I'm catching on, but PR's learning curve can be a bit messy.  There's so much to figure out here on PL,  quite different than just coding.  
Thanks so much for your help @gauravano!

**Comment by gauravano** [comment]
That's the beauty of Open Source!

**Comment by gauravano** [comment]
We try to make the contributing process easier for everyone, although.

**Comment by Manvi07** [comment]
Hi @gauravano ! Is this issue resolved? If not, I would like to work upon it.

**Comment by gauravano** [comment]
Hi @Manvi07, this issue is somewhat complete. It works great locally but view needs to be checked on `unstable`.
