### ISSUE TITLE
Listing of all comments on /comments

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#524]
Add a `def index` action to comments controller and re-use the original view at `/app/views/home/comments.html.erb` to show all comments; link from dashboard.

This is ready in #525, although I'm not sure where to put the link on the dashboard?

Also, should write a functional test for this.

**Comment by jywarren** [comment]
I'm going to put it in the "Research" menu for now, and close this. Open to other suggestions.

**Comment by ebarry** [comment]
https://publiclab.org/comments Looks great, but it doesn't seem ready to be
in the dropdown menu. The sorting on /comments is unclear -- it isn't
listed by recent, but there's no discernible other way that it is ordered
or option to change how it's ordered. Can we remove it from the dropdown
menu?

Comments do looks great on the dashboard:

* can the icon on the grey comment boxes lead to
https://publiclab.org/comments ?
* Similarly, can the yellow icon on the question boxes lead to
https://publiclab.org/questions/ ?

--

+1 336-269-1539
@lizbarry <http://twitter.com/lizbarry>

**Comment by jywarren** [comment]
Before moving it from the navbar, we need a new place to put the link -- and I don't think the icon link location is intuitive enough. 

Sorting has been fixed, though -- it just hasn't reached the live site yet. It'll be reverse chronological.
