### ISSUE TITLE
Browse and attach image not working in editor

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/plots2#5244]
# Description

The browse and attach image from computer option is not working in the editor (Attachment option in tool bar)
Only the drag and drop image option works.
The following error pops up

![contribution failed](https://user-images.githubusercontent.com/32260628/54881426-df89c900-4e75-11e9-8037-4cba770d429d.png)

**Comment by ananyaarun** [comment]
I saw an issue opened regarding image upload not working in comments, but i am not able to browse and upload images in the editor. I'm not sure why.

**Comment by CleverFool77** [comment]
I tried it yesterday and it was working 🤔🤔

**Comment by ananyaarun** [comment]
@CleverFool77 , is it working now ? it isnt for me :(

**Comment by CleverFool77** [comment]
I'm travelling right now, so I can't try right now. So I'm not sure. 🤔🤔🤔

**Comment by gautamig54** [comment]
I tried it, it is working for me as well.

**Comment by jywarren** [comment]
Hmm, maybe it had to do with the image itself, can you share it here?
Thanks!

**Comment by ananyaarun** [comment]
I was trying to upload this image 

![dashboard new](https://user-images.githubusercontent.com/32260628/54953666-c6b10e80-4f6e-11e9-96e8-1e5a0b618873.png)

Hmm not sure why it isn't working for me :thinking:

**Comment by jywarren** [comment]
Was it potentially in a comment? Because we have recently had a bug in
comment image uploading... just wondering if it's at all related... Thanks
for reporting!

**Comment by ananyaarun** [comment]
Nope , I faced this issue while editing my proposal. Its indeed confusing why image upload is not working in comments too!

**Comment by jywarren** [comment]
Hmm, well i have to go home now but if someone else wants to try uploading
the same image to see if it can be reproduced, that'd be great. Also
sometimes filenames have caused us trouble... so could be worth uploading
with a new filename? It shouldn't be a problem, but... well, sometimes it
has been.

Thanks again for reporting!!!

**Comment by ananyaarun** [comment]
So that image was actually a screenshot. I'll try with different names and other images and check once.

**Comment by jywarren** [comment]
Is this still open, just wondering?

**Comment by ananyaarun** [comment]
@jywarren It works now just tried it !!
Perhaps it was a problem from my side at that time.
I shall close this issue
Thanks!
