### ISSUE TITLE
Multi-Tag Subscription Button 

### ISSUE THREAD

**Issue by IshaGupta18** [publiclab/plots2#5245]
Finally, the multi-tag subscription button will be back, available for use, this issue intends to fix the popover problem
![image](https://user-images.githubusercontent.com/40794215/54883553-942ee500-4e8c-11e9-96dc-133685c9f45c.png)
To:
![image](https://user-images.githubusercontent.com/40794215/54883562-aa3ca580-4e8c-11e9-988e-640a0d38c393.png)

The users can now subscribe to multiple tags in one go again!

I am submitting a PR for the same!

**Comment by IshaGupta18** [comment]
@jywarren @SidharthBansal I am so happy to tell you that the multi-tag subscription button now works and is fully functional. #5246 is my PR for the same, kindly review it and let me know what else can be done! Thanks a lot!

**Comment by gauravano** [comment]
Great work @IshaGupta18 :tada:
