### ISSUE TITLE
Error on "subscribe to answer question on this topic" button

### ISSUE THREAD

**Issue by ananya** [publiclab/plots2#5247]
While looking into the project I found that the button "subscribe to answer question on this topic" on click opens an  error page 
![Screenshot from 2019-03-24 23-47-41](https://user-images.githubusercontent.com/33188930/54883797-934b8280-4e8f-11e9-8902-f8526df374bc.png)

![Screenshot from 2019-03-24 23-47-47](https://user-images.githubusercontent.com/33188930/54883805-a0687180-4e8f-11e9-99a9-05555664e7b3.png)

**Comment by gauravano** [comment]
Can you test the button for another tag @ananya ?

**Comment by ananya** [comment]
Yes i did for a few but it is showing the same error page for all. :disappointed:

**Comment by gauravano** [comment]
Would you like to solve this one?

**Comment by ananya** [comment]
yes :smiley:

**Comment by ananya** [comment]
Hey @gauravano I was trying to reproduce the bug on the localhost but it is working fine :confused: 
https://drive.google.com/file/d/1rkO7OgajqapFTnm8q5G7wSET5Mtzewgl/view

**Comment by divyabaid16** [comment]
@ananya this issue is fixed in the local host.

**Comment by ananya** [comment]
@divyabaid16 oh okay. what can be done to fix it in production?

**Comment by divyabaid16** [comment]
I guess maintainers know that better. @jywarren

**Comment by gauravano** [comment]
Hey @divyabaid16, I remember you made the PR for updating backend. Thanks @ananya for going through :+1: this one. As the @divyabaid16's  PR has been merged we can see the changes at https://stable.publiclab.org and they would be soon pushed to production. Thanks!
