### ISSUE TITLE
https://publiclab.org/stats/users.csv not loading

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5255]
Hi @cesswairimu  -- sorry to bother, but I noticed this wasn't loading, do you think you could take a peek at it? Thanks!!!

https://publiclab.org/stats/users.csv

**Comment by cesswairimu** [comment]
Sure will do.. Thanks

**Comment by jywarren** [comment]
Hmm, I seem to remember someone removed some CSV code recently because I was supposed to be built into Rails? Maybe that wasn't the case?

Let's add a functional test for this! We can probably check the blame view (poorly named! No blame given!) to see how to readd the CSV converter. Thanks! Attached sentry issue too!
