### ISSUE TITLE
Show powertags to admins only on /tags page 

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#5258]
We want to display powertags to only admins and not normal users. So, this can be achieved by filtering out tags which consist `:` in them.

here's the code for the /tags page - https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L5-L67

Refer #179 for more details.

**Comment by ebarry** [comment]
I'm excited for this one! Will be very useful to the navigability of topics on the website

**Comment by simonastefan** [comment]
Hello, I would like to solve this issue.

**Comment by jywarren** [comment]
Awesome! Looking at your PR now!
