### ISSUE TITLE
Switch to logged_in_as(roles) to simplify auth logic!

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5259]
the `User` model could use some simpler helpers, which would dramatically simplify some template code for showing things only to moderators or admins, like this:

https://github.com/publiclab/plots2/blob/aba49c4378fd94ab3f37de1d398243b75cf90365/app/views/users/list.html.erb#L8-L11

Instead, let's make a user model method like:

```ruby
user.is_role(:admin)
```

Then that code could become:

```ruby
if user.is_role(:admin, :moderator)
```

But we need to be able to specify if it's AND or OR -- any ideas?

Maybe:

```ruby
user.is_one_of_roles(:admin, :moderator)
```

We could also simplify by making an application_helper method like:

```ruby
user_has_role(:admin, :moderator)
```

where we also check if there is a `current_user`, further simplifying the code!

We'd love some help with this, and ideally the new methods would be tested as well! Thanks!

**Comment by jywarren** [comment]
Reposting from part of #268

**Comment by jywarren** [comment]
Ack! We actually have this! So this issue could be for switching to this system:

https://github.com/publiclab/plots2/blob/aba49c4378fd94ab3f37de1d398243b75cf90365/app/helpers/application_helper.rb#L3-L13

**Comment by jywarren** [comment]
This could be broken into many `first-timers-only` issues using search results from this:

https://github.com/publiclab/plots2/search?q=%22current_user.role+%3D%3D%22&unscoped_q=%22current_user.role+%3D%3D%22


****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by jywarren** [comment]
Made https://github.com/publiclab/plots2/issues/5306 for `admin_controller.rb`!

**Comment by SrinandanPai** [comment]
@jywarren I am a ROR developer and I am new to open source. I would like to work on this.

**Comment by SidharthBansal** [comment]
We will love to have your help
