### ISSUE TITLE
Changing lead image

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#526]
### What happened just before the problem occurred
I opened the Public Lab Gulf Coast chapter page. 
I noticed the image on there was an old one, or one that isn't relevant. I tried to change it back to a previous version, but when I select the previous one in the edit, it continues to use the image that is up there now. 

### Relevant URLs

https://publiclab.org/wiki/gulf-coast

### PublicLab.org username
stevie

(to help reproduce the issue)

### Browser, version, and operating system
Chrome, Version 49.0.2623.87 (64-bit),  Mac OS X 

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Thanks, Stevie, we'll look into it. This may be a result of @ujithaperera's #491 PR, which dealt with main image selection. Testing now.

**Comment by jywarren** [comment]
Confirmed -- I see this in the log, too:

````ruby
Started POST "/wiki/update/2" for xx.xx.xx.xx at 2016-05-02 18:09:11 +0000
Processing by WikiController#update as HTML
  Parameters: {"utf8"=>"✓", 
    "authenticity_token"=>"NXNf/FeOxliIpq5YZ7stFMGfZSJ32HdWuV7cHDSpf18=", 
    "image"=>{"photo"=>""}, 
    "image_revision"=>"//i.publiclab.org/system/images/photos/000/003/018/me
dium/airboat_kite_Barataria.jpg", 
    "has_main_image"=>"true", 
    "main_image"=>"3018", 
    "images"=>"", 
    "title"=>"Gulf Coast", 
    "body"=>"###Welcome to The Public Lab Gulf Coast Page...", 
    "id"=>"2"
}
````

I see that `def update` in the wiki controller looks for a `main_image`, an image id: https://github.com/publiclab/plots2/blob/master/app/controllers/wiki_controller.rb#L148-L154

But it also looks for an existing `params[:image_revision]` -- which is probably only for recently added images. 

````ruby
            img = Image.find params[:main_image]
            if @node.images.length > 0
              created = @node.images.collect {|i| i.created_at}
              if params[:image_revision] && created.max >= img.created_at
                img = Image.find params[:image_revision]
              end
            end
````

@ujithaperera - can you take a look? The page is supplying a `main_image`, so we should accept that for older images, and produce a test to ensure backwards-compatibility.

**Comment by ananyo2012** [comment]
@jywarren  Fixed the bug in the referenced PR. It was basically caused due to `main_image_id` used in #491.

**Comment by ebarry** [comment]
This is also happening on https://publiclab.org/wiki/amp. I edited the page, chose the other image, saved it, but the image didn't update. I repeated the process, which failed again.

**Comment by jywarren** [comment]
Ananyo's fix was just published to the live site; can folks try it out please and confirm, reopening if it does not work? Thanks all!

**Comment by ebarry** [comment]
it worked for /amp. thanks!
