### ISSUE TITLE
Fix scrollbar visibility on map hover

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5265]
## Description
While working on an issue, I found that
On mouse hover on the map, the scrollbar disappears.
The complete ui of the people page is moving.

![abcdefg](https://user-images.githubusercontent.com/26685258/55002722-1a6a3900-4ffd-11e9-9bbe-22a094b21836.gif)

![hover](https://user-images.githubusercontent.com/26685258/55004800-e09b3180-5000-11e9-9a10-f5f8ce050f0a.gif)

**Comment by CleverFool77** [comment]
If approved, I'm interested in working on this issue .
Thanks !!

**Comment by CleverFool77** [comment]
@publiclab/plots2-reviewers Is this issue correct ?

**Comment by gauravano** [comment]
Go ahead @CleverFool77!
