### ISSUE TITLE
Request for CSV's from term_data and community_tags

### ISSUE THREAD

**Issue by skilfullycurled** [publiclab/plots2#5268]
This might be able to be merged with [tag visualization of all tags](https://github.com/publiclab/plots2/issues/1502) or [planning for expanded community stats system](https://github.com/publiclab/plots2/issues/3498).

I'm looking to update the [tag graph](https://publiclab.org/notes/liz/09-15-2016/first-draft-of-tag-graph) I created a while back.  While we do have an API now for the top 250 tags, for reasons I'll not get into (unless you'd like me to) recreating the graph will require the data as I originally had it which was a csv of the term_data and community_tags tables.

Would it be possible to provide me with a csv of those tables?  Maybe in the future it can also be a part of the new stats downloads.  The nice thing about the full tables is that you can merge them with the node table to find the tags for the different types of content.

Thanks for your help!

**Comment by skilfullycurled** [comment]
Hey all, 

Just checking in.  Would it be possible to have the csv's without it being implemented in the stats download page?  I didn't mean to imply that it'd be an enhancement although I think it will be a good one in the end.  

I promise to [make something cool](http://www.mapequation.org/assets/img/neuroAlluvial2001-2007.svg) out of it that you won't soon forget.  And by "soon" I mean definitely not for at least the next ten minutes after you look at it.

I'll take a look at the code for the stats.  I don't program in Ruby but maybe I can make out the pattern.

Benjamin

**Comment by jywarren** [comment]
Oh sorry @skilfullycurled i didn't see this. A few thoughts that may help move it along:

1. We should link to the outputs of the new stats downloads from https://publiclab.org/api
2. I wonder if this is as simple as making a new route/action in this controller:

https://github.com/publiclab/plots2/blob/4c6ecb2325b326f451b2a5cc90f9feaedb7475a7/app/controllers/stats_controller.rb#L103-L106

But for the tables you're looking for: `term_data` and `community_tags` --

```ruby
  def tag
    data = Tag.select(:tid, :name, :parent, :count).all
    format(data, 'tag')
  end

  def node_tag
    data = NodeTag.select(:tid, :nid, :uid).where(date: start.to_i...fin.to_i).all
    format(data, 'node_tag')
  end
```

Then, adding routes to match:

https://github.com/publiclab/plots2/blob/4c6ecb2325b326f451b2a5cc90f9feaedb7475a7/config/routes.rb#L252-L253

And a link on this page to display it:

https://github.com/publiclab/plots2/blob/4c6ecb2325b326f451b2a5cc90f9feaedb7475a7/app/views/stats/_range.html.erb#L77-L95

(although the Tag model has not timestamps, so we'd just note there that it's ALL tags)

Benjamin, this would be a pretty easy `first-timers-only` issue to add, i think; does this look good to you? If so, we can build an FTO from it. Thanks!

**Comment by skilfullycurled** [comment]
Yes!  May I try to be the first timer...?

**Comment by jywarren** [comment]
And if so, you could chime in on the Weekly Check-In to see if anyone's interested in picking this up!

https://github.com/publiclab/leaflet-environmental-layers/issues/164

Oh, certainly! So, ill make it now.

**Comment by skilfullycurled** [comment]
Was the leaflet part an accident?

**Comment by jywarren** [comment]
no, actually, we have a rotating community check-in that moves from project to project, to build cross-repo cohesion! 😄

**Comment by skilfullycurled** [comment]
Ohhhhhhh...that's the link to the check in.  Sorry, wasn't immediately clear from the URL.  Okay.  Gotcha.  Working on adding some info to a different issue from some things I've learned data wise, so I'll check in on the check in soon.

**Comment by skilfullycurled** [comment]
I mean, right after.

**Comment by jywarren** [comment]
If you want to claim this yourself, you can go ahead -- i've reserved it for you: https://github.com/publiclab/plots2/issues/5412

I opened another PR with the follow-up changes, but that's a nice one to try out as a first-timers-only issue. We can close this then to move over there!
