### ISSUE TITLE
Remove the by default selected "Asked" button in the Question's tab on the profile's page  

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#5272]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

📋 Step by Step
  🙋 Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

  📝 Update the file app/views/users/profile.html.erb in the plots2 repository. The "Asked" button is permanently selected as it is marked as active by default.

In the line 73, change
`<a href="#asked" class="btn btn-default active" data-toggle="tab">Asked</a>`
to
`<a href="#asked" class="btn btn-default" data-toggle="tab">Asked</a>`

![Screen Shot 2019-03-27 at 6 56 49 PM](https://user-images.githubusercontent.com/35326753/55080264-e3128f80-50c3-11e9-8c5b-09c64dd2bf1a.png)

 💾 Commit your changes

  🔀 Start a Pull Request. There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

You can also edit files directly in your browser and open a pull request from there.

  🏁 Done Ask in comments for a review :)
Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update within a week of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

Is someone else already working on this?
🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- If someone seems stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

🤔❓ Questions?
Leave a comment below!

**Comment by ibnjunaid** [comment]
@IshaGupta18 Can i do it?

**Comment by IshaGupta18** [comment]
Go right ahead, please!

**Comment by ibnjunaid** [comment]
![Screenshot 2019-03-28 at 1 15 45 AM](https://user-images.githubusercontent.com/32925504/55107335-11f62900-50f7-11e9-899f-31de43566ec7.png)

Im having issue with installing right version of ruby on my machine, do you have any fix for it.

**Comment by gautamig54** [comment]
@ibnjunaid Try installing RoR using rvm.

**Comment by gauravano** [comment]
Hey @ibnjunaid, also try `rbenv local 2.4.4` just in case it works

**Comment by ibnjunaid** [comment]
@gauravano rvm worked. Thanks @gautamig54 @gaeun

**Comment by gauravano** [comment]
Great!
