### ISSUE TITLE
Add the # of asked and answered questions under the questions tab in the profile's page

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#5273]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

📋 Step by Step
🙋 Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

📝 Update the file app/views/users/profile.html.erb in the plots2 repository. Add the number of asked questions and the number of answered questions under the questions tab in the profile's page.

Replace the lines 73 and 74 : 
`<a href="#asked" class="btn btn-default active" data-toggle="tab">Asked</a>`
 `<a href="#answered" class="btn btn-default" data-toggle="tab">Answered</a>`
by 
`<a href="#asked" class="btn btn-default" data-toggle="tab">Asked<%= "(#{Node.questions.where(status: 1, uid: @profile_user.id).length})" %></a>`
`<a href="#answered" class="btn btn-default" data-toggle="tab">Answered<%= "(#{Answer.where(uid: @profile_user.id).count})" %></a>`

![Screen Shot 2019-03-27 at 7 24 53 PM](https://user-images.githubusercontent.com/35326753/55081473-eb6bca00-50c5-11e9-9281-9ba298100ebb.png)

💾 Commit your changes

🔀 Start a Pull Request. There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

You can also edit files directly in your browser and open a pull request from there.

🏁 Done Ask in comments for a review :)
Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update within a week of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

Is someone else already working on this?
🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- If someone seems stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

🤔❓ Questions?
Leave a comment below!

**Comment by gautamig54** [comment]
@gauravano Kindly review this issue and label it as FTO. Thanks!

**Comment by jtmims** [comment]
Alright, I got this

**Comment by gauravano** [comment]
Hey @gautamig54, can you check if we are passing questions from the controller, as it would be awesome if we don't need to query again. Thanks!

**Comment by gautamig54** [comment]
Yes, @gauravano we can make a separate variable in the questions/answers controller and since the query of counting the number of questions asked or answers posted has been used few times, we can change it to one. I'll do it. Thanks!

**Comment by gauravano** [comment]
Great!

**Comment by gautamig54** [comment]
@gauravano Kindly review my PR for the said issue. Thanks!
