### ISSUE TITLE
Change the path of "# research notes" on the dashboard from profile to notes/author

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#5274]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

📋 Step by Step
🙋 Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

📝 Update the file app/views/dashboard/_header.html.erb in the plots2 repository. The "# research note" link with the welcome user (below Dashboard) directs the user to their profile page, instead it should direct the user to the notes page.

In the line 16, change
`<a href="/profile/<%= current_user.username %>">`
to
`<a href="/notes/author/<%= current_user.username %>">`

![Screen Shot 2019-03-27 at 7 37 12 PM](https://user-images.githubusercontent.com/35326753/55082410-a47ed400-50c7-11e9-9428-fc1ef69dc2d6.png)

💾 Commit your changes

🔀 Start a Pull Request. There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

You can also edit files directly in your browser and open a pull request from there.

🏁 Done Ask in comments for a review :)
Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update within a week of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

Is someone else already working on this?
🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- If someone seems stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

🤔❓ Questions?
Leave a comment below!

**Comment by gautamig54** [comment]
@gauravano Kindly review this issue and label it as FTO. Thanks!

**Comment by gauravano** [comment]
@AnthoniaOkafor you can work on this one. Thanks!

**Comment by AnthoniaOkafor** [comment]
Thank you for assigning it to me

**Comment by mahmodHammad** [comment]
can i work on it ?

**Comment by gautamig54** [comment]
@mahmodHammad This issue has already been claimed. Try looking for other FTOs. 
Look at issue #5289 . If it gets approved then you can work on that 👍
