### ISSUE TITLE
Fix typo in email search

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/plots2#5276]
Specially created for @supriya-kotturu

Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [x] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [x] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

**Update**
When the user is logged in using admin, following typo prevails:

![Selection_092](https://user-images.githubusercontent.com/32747809/55084068-92eafb80-50ca-11e9-9cd7-268524d59d92.png)

In the file: r/app/views/admin/useremail.html.erb
Change https://github.com/publiclab/plots2/blob/6ea587e24f87fce9e1901744b72b15ec0ac48687/app/views/admin/useremail.html.erb#L6
to ```<p>Moderators and admins have the ability to search for usernames associated with a given email address. This ability is meant to assist in answering the requests submitted by email where the user forgets to specify their username; clearly, the email address of the sender is known.</p>```

- [x] 💾 **Commit** your changes

- [x] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [x] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by supriya-kotturu** [comment]
hey @divyabaid16, I made the required changes to the file.  can you please let me know what to refer to get a screenshot of the changes that need to be recorded?

**Comment by divyabaid16** [comment]
@supriya-kotturu actually you have created the PR in your local repository.
While sending the pull request, make sure that you send it to ```publiclab:master```
Thanks!

**Comment by Michaellin250** [comment]
Is this issue closed? I'd love to tackle it!

**Comment by gauravano** [comment]
Hey @Michaellin250, this one is already assigned. You can get yourself issue assigned by commenting https://github.com/publiclab/plots2/issues/4963. Thanks!

**Comment by supriya-kotturu** [comment]
thank you. I didn't notice it. just created a PR to the master branch

**Comment by IshaGupta18** [comment]
@supriya-kotturu how's it going? Let me know if you're stuck!

**Comment by supriya-kotturu** [comment]
I have fixed the typo the very next day and created a pull request

Sai Supriya

**Comment by gauravano** [comment]
@supriya-kotturu please copy the link to your PR here or add `Fixes #5276` in the PR comment so it gets tagged here. Thanks!

**Comment by gauravano** [comment]
Ok, so your PR is closed https://github.com/publiclab/plots2/pull/5292. I reopened it.
