### ISSUE TITLE
Errored comment functionality

### ISSUE THREAD

**Issue by rexagod** [publiclab/plots2#5277]
Hi all! I was editing a comment [here](https://publiclab.org/notes/Getty/03-26-2019/outreachy-proposal-publiclab-org-ui-improvements) when an internal server error started to popup in my console.

The order of steps I initially followed were:
- Post a comment on Getty's proposal. -- successful
- Edit that. -- unsuccessful
- Delete the posted comment. -- successful
- Post a newer one with appropriate changes. -- unsuccessful

My logs indicating the 500 are below. 

![Screenshot from 2019-03-28 00-28-41](https://user-images.githubusercontent.com/33557095/55104719-f25c0200-50f0-11e9-8a03-f59b4531246f.png)

**Comment by gauravano** [comment]
I commented on behalf of @rexagod but missed some part, so I tried to edit my comment - https://publiclab.org/notes/Getty/03-26-2019/outreachy-proposal-publiclab-org-ui-improvements#c23492
 
but got on this page :point_down: 

![Screenshot from 2019-03-28 00-41-13](https://user-images.githubusercontent.com/20878070/55105551-cc376180-50f2-11e9-9484-d2fe45a994c8.png)

**Comment by gauravano** [comment]
@ViditChitkara @jywarren any idea?

**Comment by gauravano** [comment]
Hey everyone, @rexagod and me did some inspection and found out that the issue was due to mixing of rich and markup emojis. So, closing this one. Thanks!

**Comment by jywarren** [comment]
Thanks all for the debugging!!!
