### ISSUE TITLE
[Discussion] Left sidebar : Profile section menu

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/plots2#5285]
In order to ease the navigation of the profile section. Can we introduce a left sidebar by which a user can easily navigate to the various profile section/settings tabs? Please check out the sample design. It's just to give a brief idea about how we can implement this, the design can be improved further once it is approved.

**Proposed idea:**
![Side bar profile](https://user-images.githubusercontent.com/32747809/55146299-4e16a180-516a-11e9-9ed2-ccd39ab87869.png)

**Comment by CleverFool77** [comment]
Hi @divyabaid16
Did you mean, sidebar on every page?

**Comment by divyabaid16** [comment]
No. 
Only on the profile and settings sections.

**Comment by CleverFool77** [comment]
But we already have this in navbar drop down meuu right 🤔🤔
Did You mean something like github?
The options of sidebar coming in settings section?.
But we don't have so many options like github does 🤔🤔🤔
It would great to hear other opinions 🤔

**Comment by divyabaid16** [comment]
Yeah, we have this in the drop-down menu, but if we include this in the left sidebar, I think, it will ease the navigation for the users to switch between tabs in profile section.
Yes, it is somewhat like Github.
It doesn't matter much if we've many options or not as this is just to make the navigation user friendly.

**Comment by divyabaid16** [comment]
@publiclab/designers, please suggest some ideas on this!

**Comment by jywarren** [comment]
Hi, Divya - so, are you also suggesting the use of a vertical nav instead
of tabs for existing sections, in addition to what opens on a new page?

https://getbootstrap.com/docs/4.3/components/navs/#vertical

https://getbootstrap.com/docs/4.3/components/navs/#tabs

Perhaps with the various profile page design processes going (LekhikaDugtal
would you mind linking to some of the various threads?) we should consider
this alongside the other proposed changes to the profile page?

Thank you for your brainstorming!

**Comment by divyabaid16** [comment]
@jywarren I am suggesting to use this in the profile section only as of now. I think we should consider the idea alongside the other proposed changes to the profile page.

**Comment by CleverFool77** [comment]
Hi @divyabaid16 @jywarren I didn't get notification and hence the delay.
But here it is.
These are some of the bunch of threads where some discussions/designs regarding ui of profile section is going on - 
*  https://publiclab.org/notes/lekhidugtal/03-13-2019/ui-wireframe-for-profile-page#comments
* https://github.com/publiclab/plots2/issues/4423
* https://docs.google.com/presentation/d/1TCZoTfuhamRVrUak8aDgqJAwSgyhRtZg2Pgacl2_4zc/edit#slide=id.gfb2aa1b7ddf791c_5

**Comment by jywarren** [comment]
Thanks, all! Our profile pages are refreshed and looking great! I'd love any other input filed in  new issues. Thanks a ton. 🎉
