### ISSUE TITLE
[Discussion] : Translating pages to different language in footer not working.

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#5286]
There is an option of translating the webpages into German and Japanese, which does not seem to be working. 
Since Public Lab is a general platform and open for people all over the world. 
We can discuss about implementing this feature. 
There were issue opened earlier (#3348) regarding this problem, but no action seem to be taken, therefore I thought of opening up this issue and see if we can come up with some solution. 

![Screen Shot 2019-03-28 at 3 44 56 PM](https://user-images.githubusercontent.com/35326753/55149812-ddbf4e80-5170-11e9-89b2-94cb616cf145.png)

**Comment by divyabaid16** [comment]
@gautamig54 please look into https://github.com/publiclab/plots2/issues/5036#issuecomment-472134891

**Comment by gautamig54** [comment]
@divyabaid16 Thanks! I was exactly talking about this, translation is minimal. We can discuss onto how to translate all the webpages.

**Comment by dinaelhanan** [comment]
@guatamig54 maybe this can be a GSoC issue where people who are native to the language can contribute docs/pages in that language?

**Comment by gauravano** [comment]
hey everyone, we have Transifex account - https://www.transifex.com/publiclab/publiclaborg/dashboard/ so you can help there. Thanks!

**Comment by jywarren** [comment]
Let's do some social media outreach around this too! What should we post?

**Comment by gauravano** [comment]
How about writing a research note?

**Comment by jywarren** [comment]
Sounds great!!!

**Comment by gautamig54** [comment]
@gauravano @jywarren I am working on writing a research note suggesting few ideas on how to translate publiclab web pages.

**Comment by gauravano** [comment]
Actually, @jywarren found some old pages - https://publiclab.org/wiki/translation. Lol, I found some more - https://publiclab.org/tag/translation

Maybe we can organize and update them a bit and we will be all good to start a campaign?

@jywarren @ebarry 

Thanks all!

**Comment by jywarren** [comment]
I think this is complete, thank you!!!
