### ISSUE TITLE
Remove duplicated like, share and tweet buttons on wiki pages

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#5289]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

📋 Step by Step
🙋 Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

📝 Update the file app/views/wiki/show.html.erb in the plots2 repository. The like, share and tweet buttons are duplicated at the end of the wiki and on the sidebar. Remove the buttons at the end of wikis. 

![Screen Shot 2019-03-28 at 7 37 44 PM](https://user-images.githubusercontent.com/35326753/55164046-f6d7f780-5190-11e9-83f7-631a3e39194c.png)

💾 Commit your changes

🔀 Start a Pull Request. There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

You can also edit files directly in your browser and open a pull request from there.

🏁 Done Ask in comments for a review :)
Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update within a week of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

Is someone else already working on this?
🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- If someone seems stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

🤔❓ Questions?
Leave a comment below!

**Comment by gautamig54** [comment]
@gauravano Kindly look into this issue and label it as FTO. Thanks!

**Comment by mahmodHammad** [comment]
can  i work on it ?

**Comment by gautamig54** [comment]
@mahmodHammad Sure, Once it gets approved!

**Comment by gautamig54** [comment]
@gauravano Kindly review this issue. Thanks!

**Comment by gauravano** [comment]
Go ahead @mahmodHammad!

**Comment by mahmodHammad** [comment]
i cant find this divs at app/views/wiki/show.html.erb ! any hint?
![fq](https://user-images.githubusercontent.com/41790090/55283840-dc0daa80-536b-11e9-8eac-f2b7cab44621.PNG)

**Comment by mahmodHammad** [comment]
https://github.com/publiclab/plots2/blob/master/app/views/wiki/show.html.erb

is this  the right file?

**Comment by gauravano** [comment]
Hey @mahmodHammad, yes the file you mentioned is the right one and that't the file mentioned in the issue description too.

See around https://github.com/publiclab/plots2/blob/master/app/views/wiki/show.html.erb#L76-L78

**Comment by mahmodHammad** [comment]
is my pull request accepted?

**Comment by gauravano** [comment]
Yes @mahmodHammad!
