### ISSUE TITLE
Brainstorm "timeline" view for a topical collection of research

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#529]
We've long talked about a "timeline" view of research, organized into topical streams, showing research notes, wiki edits, data uploads, comments, etc etc.

Lots of examples to take inspiration from:
- [Github Pulse](https://github.com/publiclab/plots2/network)
- http://timeline.knightlab.com/
- https://technotarek.com/timeliner/

![screenshot 2016-05-02 at 8 54 49 pm](https://cloud.githubusercontent.com/assets/24359/14972283/4e79579a-10a8-11e6-8709-05328efa4f88.png)

Lots here, just jotting down some notes.

**Comment by david-days** [comment]
Visualizations are a problem I've often encountered.  Even if the data remains complex at any level, providing a visualization (or a series of them) can help.

I've used [D3](https://d3js.org/) to create some useful charts, before.  Here are a few graph examples that might give you an idea of what might be useful.

(I'm considering D3 for some of the charts for the search relevancy results, too--it might be a way to display author, tag, topic, and word-salad relevancy to users trying to navigate the relationships of the research notes posted.

[Sankey Diagram](https://bost.ocks.org/mike/sankey/) This one might produce the version mapping you display above.

[Comic Timeline](http://csclub.uwaterloo.ca/~n2iskand/?page_id=13) Another version of the Sankey diagram.  Not as pretty, but note that additional information is available by clicking on the gray nodes.

[Dependency Wheel](http://www.redotheweb.com/DependencyWheel/) Might be good for displaying collaborative relationships, or as a drill-down from the timeline/Sankey charts.

[Word Cloud](https://www.jasondavies.com/wordcloud/) Less relevant to this, but might be used within narrowed searches (authors/profiles, topics, projects)

[Network Diagrams](http://languagenetwork.cotrino.com/)  This one is for language relationships, but shows the same data in two formats--something to keep in mind.  One of the charts is the dependency wheel from above.

**Comment by gauravano** [comment]
Hey @jywarren, can we close this one considering @2068 is dealing with all the graphs across site so this one should be covered?  Thanks!
