### ISSUE TITLE
Fix page redirection problem in comments section of notes

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/plots2#5291]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

# Current Behavior
When a user not logged in tries to comment on a note, an alert message to login appears. After login however, the user is redirected to the dashboard and looses the note he was trying to comment on previously.

# Expected Behavior 
User should be redirected to that particular note page and not the dashboard. Hereby after login is complete he can proceed with commenting on the note.

**Comment by ananyaarun** [comment]
@publiclab/plots2-reviewers Thoughts on this issue ?

**Comment by gauravano** [comment]
Hey @ananyaarun, yes, it would be nice addition. Thanks :+1:

**Comment by ananyaarun** [comment]
Sure Thanks, I'll be working on this :)

**Comment by gauravano** [comment]
Great!

**Comment by ananyaarun** [comment]
This has been added to GCI dashboard, Thanks !

**Comment by SidharthBansal** [comment]
Sorry I could not search the task link for publishing

**Comment by SidharthBansal** [comment]
I increased the marks for this issue. Kindly tell me the link of task so that I can modify at the dashboard.

**Comment by SidharthBansal** [comment]
Upgrading to `hard` from `medium`
Please provide GCI task link so that I can edit there too
