### ISSUE TITLE
Add link to Skylight in our error page

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#5293]
Hi all!

Having a brainstorm with @jywarren, we realized that this link to skylight.io in the publiclab.org website footer... https://oss.skylight.io/app/applications/GZDPChmcfm1Q/recent/6h/endpoints

...could be added to our error pages such as this one: 
https://github.com/publiclab/plots2/blob/master/public/500.html

This would enable people to more easily check on the site's status!

Could this be a First Timers Only issue?

Thanks!

**Comment by gauravano** [comment]
Hey @ebarry, thanks for creating the issue and yes, FTO issue can be created from it.

**Comment by gauravano** [comment]
Ok, I have created a FTO at #5296. So, closing this now. Thanks!
