### ISSUE TITLE
error on "following jobs"

### ISSUE THREAD

**Issue by vcavallo** [publiclab/plots2#5304]
landed on https://publiclab.org/tag/jobs, clicked "follow jobs", got the "There was an error. Are you sure you have the right address?" page.
clicking on "subscribe"  on the same page just pops up a little tooltip, empty except for: "Follow related tags:" 
clicking the RSS button on the same page results in the same error at this URL: https://publiclab.org/feed/tag/jobs.rss

browser: Brave Version 0.60.47 Chromium: 72.0.3626.119 (Official Build) (64-bit)
os: ubuntu 18
publiclab username: vcavallo (connected via GitHub)

**Comment by jywarren** [comment]
Hi! Thanks for reporting this. For the time being, if you log into the
site, you should be able to use this link:
https://publiclab.org/subscribe/tag/jobs

We'll be overhauling that page soon and will be sure to fix this!

**Comment by gauravano** [comment]
Hey @jywarren, 

> https://publiclab.org/tag/jobs, clicked "follow jobs", got the "There was an error. Are you sure you have the right address?" page.

It's fixed and is merged in master some days ago.

> clicking on "subscribe" on the same page just pops up a little tooltip, empty except for: "Follow related tags:"
 
This one is also ready. @jywarren your final review is required on this here - https://github.com/publiclab/plots2/pull/5246. 

Thanks!

**Comment by jywarren** [comment]
Oh fantastic, thank you Gaurav. I'll also be publishing to production
shortly.

**Comment by gauravano** [comment]
Hi @vcavallo, we have fixed the follow tag button and also Subscribe button works now and allow you to subscribe to multiple tags at the same time. 

Closing this issue now. Feel free to reopen it if you find it not working or anything left.

Thanks!
