### ISSUE TITLE
(not working yet) Change deliver_now to deliver_later for all emails

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5311]
We just successfully converted the admin_controller to use `deliver_later` to enqueue email sending, which should really help keep the website running smoother -- it uses Redis automatically to send emails on another thread. 

https://github.com/publiclab/plots2/pull/4967/files shows how we did it -- it did involve wrapping all failing tests with:

```ruby
perform_enqueued_jobs do 
  # all test contents
end
```

Let's do this for each controller, and each time we use `deliver_now` -- you can find all instances using this search:

https://github.com/publiclab/plots2/search?q=deliver_now

We'd love help with this, and it's fine for it to be over a series of pull requests, one at a time!
- [ ] users_controller (@divyabaid16)
- [ ] answer_like_controller(@AnthoniaOkafor)
- [ ] notes_controller
- [ ] user_sessions_controller
- [x] answers_controller
- [x] admin_controller

**Comment by divyabaid16** [comment]
Can I work on this?

**Comment by namangupta01** [comment]
Go ahead

**Comment by divyabaid16** [comment]
Hi! I had a small confusion. I wanted to know whether I should change it for each controller only?
Or do I need to change the test so that the tests do not fail?

**Comment by AnthoniaOkafor** [comment]
@jywarren @namangupta01 please can I have an fto_candidate issue on Ruby. Thanks

**Comment by divyabaid16** [comment]
@AnthoniaOkafor if you want you can solve this issue for any controller.
Thanks!

**Comment by AnthoniaOkafor** [comment]
Ok, I will. Thanks

**Comment by jywarren** [comment]
Just a note that we don't seem to be seeing these emails sent when using
`deliver_later` and are still debugging this... we'd love the PRs but are
probably not going to merge them until we finish debugging it! But thanks
for the help!!!

**Comment by jywarren** [comment]
OK, we are seeing these `deliver_later` pile up in sidekiq!

https://publiclab.org/sidekiq/queues/mailers

![image](https://user-images.githubusercontent.com/24359/57398173-5e279500-719c-11e9-8cf4-fdf521d6971f.png)

**Comment by jywarren** [comment]
So, I think this may actually be all good, but just we're never actually triggering the job. 

https://api.rubyonrails.org/classes/ActionMailer/MessageDelivery.html#method-i-deliver_later

OK, more on this here: https://stackoverflow.com/a/51642031

We need: `config.active_job.queue_adapter = :sidekiq`

https://gist.github.com/maxivak/690e6c353f65a86a4af9#configure-sidekiq

I'm not sure if `config.action_mailer.perform_deliveries = true` is necessary...

Trying the rest, meaning also a `config/sidekiq.yml` in https://github.com/publiclab/plots2/pull/5687

**Comment by jywarren** [comment]
If it passes, i'll merge into stable, and we can publish along with the big Bootstrap upgrade; we'll see how it does in production, since these emails are not critical!

**Comment by jywarren** [comment]
Also good docs: https://blog.morizyun.com/ruby/library-sidekiq-job-queue-active-job.html

**Comment by jywarren** [comment]
Confirmed! With the code publication we did tonight, this `deliver_later` system is now working! We can start the rest of the controller conversions now. 🎉
