### ISSUE TITLE
Confusion between star and like buttons

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#5312]
There are different options to star and like(which requires facebook login) a note or a wiki. On hovering the star button, it shows a message saying "like to get updates". 
Also, on the profile's page there is a tab for "Liked" posts which actually refers to the starred post. 
I would suggest to differentiate both these operations. The like(facebook) button can remain as it is and we can star any post/wiki for getting updates and the message can be changed to "star for getting updates". Also, on the profile's page the "Liked" tab can be changed to "Starred".

**Comment by gautamig54** [comment]
@gauravano Kindly review this issue. Thanks!!

**Comment by gauravano** [comment]
I think we can use "starring" and "liking" interchangeably. But, it would be better to ask who spend the most time on website like @publiclab/community-reps

**Comment by gautamig54** [comment]
Sorry for the late reply.  @gauravano should I start a discussion on @publiclab/community-reps regarding the starring and liking issue?

**Comment by gauravano** [comment]
Let's wait for some more time. @jywarren will reply soon here. Thanks!

**Comment by jywarren** [comment]
I'm sorry, i missed this! I think this is resolved with our new circular buttons!
