### ISSUE TITLE
setup bulma for plots2

### ISSUE THREAD

**Issue by GettyOrawo** [publiclab/plots2#5325]
Bulma is a CSS framework that requires the least CSS code. I work with bulma a lot and most of its styling is done through the multiple classes that are predefined by the framework. I feel it'll be a really good idea to intergrate it. What do you guys think? @jywarren , @gauravano , @IshaGupta18 , @ananyaarun , @cesswairimu and anyone else?

**Comment by GettyOrawo** [comment]
[bulma.io](https://bulma.io/)

**Comment by ananyaarun** [comment]
Wow!! this is the first time i'm coming across this, seems interesting :) 
But i think in the next few months we will be building on the Bootstrap 4 UI library to implement new HTML templates within the Ruby on Rails website. (Under the outreachy UI project)

**Comment by gauravano** [comment]
I checked out the website of bulma framework. Yes, the framework offers many things like easy syntax, cards, etc - https://bulma.io/alternative-to-bootstrap/ but at the same time, I think, it's good for projects which are just starting or are very new. /

We are about to merge Bootstrap 4 upgrade on the production soon - https://github.com/publiclab/plots2/pull/3937, so I don't think we would like to switch to Bulma, unless needed. 

Thanks!
Mentioning @jywarren and @publiclab/plots2-reviewers.

**Comment by cesswairimu** [comment]
closing this. Thanks all
