### ISSUE TITLE
Feature alerts on nodes

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#5327]
We want to display feature alerts on the nodes, such that:

If a admin add a powertag `alert:featurename` then the feature will be shown as alert on that node.

This can be achieved by:
- [ ] Adding a condition here https://github.com/publiclab/plots2/blob/master/app/views/notes/show.html.erb#L3-L10 for powertag `alert:featurename`.
- [ ] Drop a line about this power tag at https://publiclab.org/wiki/power-tags

Thanks!

**Comment by CleverFool77** [comment]
Hi @gauravano ,
I'm interested in working on this issue.

**Comment by CleverFool77** [comment]
And can I know what does it mean by showing the alert on `that` node ?

**Comment by gauravano** [comment]
Sure, go ahead! 

Suppose, I added tag `alert:hello-world` on my research note, so it should show the feature hello-world in the alert when we open that research note. Clear?

Thanks!
