### ISSUE TITLE
Fix the horizontal scrolling

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5333]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** . 
* Fix the horizontal scrolling in `https://publiclab.org/profile/edit` 

![ezgif-2-03aacb4b5335](https://user-images.githubusercontent.com/26685258/55337067-98c25180-54bb-11e9-9d34-8cbb82f5a530.gif)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by CleverFool77** [comment]
@publiclab/plots2-reviewers Is this issue correct ?

**Comment by ibnjunaid** [comment]
@CleverFool77 this issue isn't valid for mobile displays.

**Comment by CleverFool77** [comment]
@ibnjunaid Can I have some insight regarding this. That How it isn't valid for mobile displays ? 
I didn't see to understand. :sweat_smile:

**Comment by ibnjunaid** [comment]
I mean page the issue you are suggesting isn't showing up on my phone. The webpage is smooth there with content not expanding more than the viewport but that your issue is valid on a large screen.

Any idea why this happens ??

**Comment by CleverFool77** [comment]
@ibnjunaid Ahhh Now I get it.
Regarding the cause of this - 
We can fix the css property for his

**Comment by gauravano** [comment]
Hey @CleverFool77 can you also add the code snippet required to solve the issue? Also @ibnjunaid, you can solve this one if interested. Thanks!

**Comment by CleverFool77** [comment]
Sure @gauravano I'll update it :smiley:

**Comment by ibnjunaid** [comment]
@CleverFool77 I m waiting for your directions .

**Comment by CleverFool77** [comment]
Hi @ibnjunaid 
Today, I'm not getting this issue on my localhost.
So before that , can you try this on your localhost and check if the issue persists.

**Comment by gauravano** [comment]
I am getting this issue!

**Comment by CleverFool77** [comment]
Is it because of different screen size?

**Comment by CleverFool77** [comment]
Hi @divyabaid16 @gautamig54 I found this issue earlier but unable to reproduce it now.
Can I know from you guys whether this issue still persist?
Thanks !!

**Comment by divyabaid16** [comment]
I'm not getting this issue now @CleverFool77 and sorry for the late reply.
Thanks!

**Comment by discombobulateme** [comment]
Hey all :) I'm an Outreachy applicant, would like to make a contribution. Is this issue still open?

**Comment by IshaGupta18** [comment]
Hey, could you try checking if the issue still occurs, and if it does, go
ahead!

**Comment by discombobulateme** [comment]
Hi @IshaGupta18 ! I do not have access to this specific page, cannot check if the issue is still going on :/ should I need special permission?

**Comment by discombobulateme** [comment]
Hi @IshaGupta18 and all, I checked the issue in multiple screens and seems totally fixed :) could someone please close the issue? Or is there something else to fix? (I found no bug in this page)

**Comment by IshaGupta18** [comment]
We'll close it then if it's not seen again! Please look for some other
issue to work on. Thank you!

**Comment by CleverFool77** [comment]
Hi @IshaGupta18 If this one is fixed. Then I'll close it.
Thanks !!
