### ISSUE TITLE
Information and links in comment is going out of comment card

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5334]
## Description
The links are going out of comment card.
Maybe we can fix the no of characters in the card ? and put it inside a container 
![Screenshot from 2019-04-01 21-00-06](https://user-images.githubusercontent.com/26685258/55339880-28b6ca00-54c1-11e9-9aa2-e81c8c0070cb.png)

**Comment by jywarren** [comment]
We could do "overflow:hidden" in css perhaps?

**Comment by CleverFool77** [comment]
@jywarren I would like to work upon this issue.
Thankss !!

**Comment by CleverFool77** [comment]
Oh yess.. How come i forgot that . I would like to try this out.

> We could do "overflow:hidden" in css perhaps?

**Comment by gauravano** [comment]
Go ahead!

**Comment by jywarren** [comment]
:-)
