### ISSUE TITLE
fix distortion in social media pill

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5337]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** . 
* Fix the width in social media pill
![Screenshot from 2019-04-01 20-30-39](https://user-images.githubusercontent.com/26685258/55353554-38dea180-54e1-11e9-8640-82cd60fe191a.png)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by gauravano** [comment]
Strange, I am not getting this issue. 
![Screenshot from 2019-04-02 19-30-31](https://user-images.githubusercontent.com/20878070/55408576-e99a7e80-557d-11e9-8041-1e304754f02f.png)

Browser: Chrome

**Comment by CleverFool77** [comment]
I guess it was because of browser zoom issue.
But while going through this, I found this.
This was not present yesterday though.
![Screenshot from 2019-04-02 20-45-53](https://user-images.githubusercontent.com/26685258/55414351-8cf09100-5588-11e9-8268-b34cc2a7ece4.png)

Everything is shifted and aligned to left.

**Comment by CleverFool77** [comment]
Maybe it was because of browser zoom issue. Mine is usually at 110%
but while going through this issue. I found this.
My dashboard seems to load in two way - 
Sometimes it's like this - 
One -  
![Screenshot from 2019-04-02 20-45-53](https://user-images.githubusercontent.com/26685258/55414706-48192a00-5589-11e9-8ec6-360deb125a17.png)

Two - 
![ezgif-2-4deee28dacde](https://user-images.githubusercontent.com/26685258/55414982-d097ca80-5589-11e9-8c96-1c2d58bdab02.gif)

**Comment by gauravano** [comment]
@CleverFool77 social media pills are distorted in any of the above cases?

**Comment by CleverFool77** [comment]
No, I didn't came across the distortion after I fixed the zoom issue.
@gauravano .I guess this issue will be closed.

**Comment by gauravano** [comment]
Ok. Let's close it for now. If we come across this issue again, then we can investigate the code. How does that sound? Thanks!
