### ISSUE TITLE
Pagination missing on tag pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5339]
Unfortunately we must've made a change to the pagination affecting these lines:

https://github.com/publiclab/plots2/blob/cfb50b99f655ed5d991e987b0a0e2f96ea734b41/app/views/notes/_notes.html.erb#L74-L75

There used to be pagination on pages like this:

https://publiclab.org/tag/balloon-mapping/

But it's not showing up! Not sure why -- but we'd really love help solving this one!!!

**Comment by CleverFool77** [comment]
Hi @jywarren ,
According to you, what could be the reason this :thinking:

**Comment by jywarren** [comment]
I'm not totally sure... i think it could involve some experimentation with
the @paginated = false logic to try to figure it out, locally!

**Comment by gautamig54** [comment]
I pulled the recent code and the curly braces for the .content(lines 61-63) was missing due to which the code written after it wasn't working which involves pagination as well.

**Comment by IshaGupta18** [comment]
Hey @gautamig54 could you tell a bit more precise about this, this could probably be the breaking point in the code and could help in fixing this bug? Thanks!

**Comment by gautamig54** [comment]
Is this issue solved?

**Comment by gauravano** [comment]
No @gautamig54!

**Comment by jywarren** [comment]
Hi all! I think I may have solved this over the weekend... Could you check
the latest code? Thank you!!!!

**Comment by gauravano** [comment]
Yes @jywarren, the pagination bar is visible at publiclab.org/tags. So, let's close this one. And, thanks for solving @jywarren!!
