### ISSUE TITLE
Tag popovers don't disappear when tags are deleted

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5342]
Follow up on #5072 -- when you delete a tag, we need to hide the popover first!

![image](https://user-images.githubusercontent.com/24359/55368461-efca2580-54bf-11e9-8c44-8e5dea70f3ff.png)

I'd love some help with this! 

https://github.com/publiclab/plots2/blob/master/app/views/tag/_tagging.html.erb

**Comment by jywarren** [comment]
Hi @CleverFool77 would you be interested in taking a look at this? Thank you so much!

**Comment by CleverFool77** [comment]
Sure Jeff :)
I'll look into this.

**Comment by jywarren** [comment]
thank you!!!
