### ISSUE TITLE
Emoji reactions are no longer showing authors

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5343]
Hi @ViditChitkara -- i noticed this on comments... maybe due to the refactor? 

![image](https://user-images.githubusercontent.com/24359/55369907-813c9600-54c6-11e9-9bca-aabf9bbadf4f.png)

I'd love some help getting this fixed! And please don't be discouraged by the bugs here, this was a really big refactor so they're bound to happen 😄 

One thing we might do now, is to write a system test for some of this, to protect the features! #5316

**Comment by ViditChitkara** [comment]
Hi @jywarren , that's quite odd. I think this might be a specific case where authors are not showing with the emoji. Oh I think I got it, it shows the authors after refreshing. The reason might be, we are dynamically adding the emoji but, associated js.erb doesn't cater for the tooltip which shows the authors. Is that what might be happening?
Also, could you share the link to the comment in the screenshot above? and yeah I'll be starting with the tests next.
Thanks!

**Comment by jywarren** [comment]
ah, ok! yes, so i think we can activate it with `$().tooltip('selector')`
where the selector is something narrow enough to only affect the newly
added HTML? This is in a reply to a comment, i believe on one of the
proposals but perhaps you could find it relatively quickly here?
https://publiclab.org/comments

Thank you!

**Comment by jainaman224** [comment]
@jywarren @ViditChitkara Can I work on this?

**Comment by jainaman224** [comment]
After https://github.com/publiclab/plots2/blob/master/app/controllers/comment_controller.rb#L209 adding

```
@user_reactions_map = comment.user_reactions_map
```

After https://github.com/publiclab/plots2/blob/master/app/views/comments/like_comment.js.erb#L12 adding

```
<% if @user_reactions_map.has_key? capitalized_emoji_name %>
  $("<%= str %>").attr("data-original-title", "<%= @user_reactions_map[capitalized_emoji_name] %>");
<% end %>
```

Fixed the issue.

**Comment by ViditChitkara** [comment]
@jainaman224 that's really cool!! Could you open a PR for this. Thanks!
