### ISSUE TITLE
Add title to the first column

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/plots2#5345]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [x] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [x] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

**Update**
Current there is no heading in the first column at [the search pages](https://publiclab.org/search/chat)
Add ```Title``` to the first column simply how ```Posted by``` and ```Views``` are for second and third column respectively.
Screenshot for the same:
![Selection_109](https://user-images.githubusercontent.com/32747809/55409347-814c9c80-557f-11e9-8b71-76dd67ea632d.png)

Changes need to be done in ```app/views/search/all_content.html.erb``` and ```app/views/search/_wikis_blank.html.erb``` file.

- [x] 💾 **Commit** your changes

- [x] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [x] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by madhavsarpal100** [comment]
Hii @divyabaid16 , I am new to FOSS community and would like to work on this first-timers-only issue. I really like the concept of DIY environmental investigation at publiclab and would like to contibute to this community in the future. May I work on this issue?

**Comment by namangupta01** [comment]
Hi @madhavsarpal100, go ahead! Let us know if you need any help.

**Comment by madhavsarpal100** [comment]
Thanks!!

**Comment by atjustbeinghumaid** [comment]
Hey!
I've made the reqd changes and made a PR!
Anything more to be done?

**Comment by atjustbeinghumaid** [comment]
Better now?

**Comment by gauravano** [comment]
Hey @divyabaid16, thanks for the awesome FTO.

 Just want to suggest that, it's good either to delete this part or to update the file link and Repo link properly.

> -[ ] :memo:  Update the file $FILENAME in the $REPO repository (press the little pen Icon) and edit the line as shown below.

**Comment by divyabaid16** [comment]
Oh!! My bad.
Thanks @gauravano
