### ISSUE TITLE
Blog redesign next steps and discussion

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5352]
We're looking to improve the blog template again with some design inspiration from this WordPress template:

![image](https://user-images.githubusercontent.com/24359/55426342-8cd59e80-5552-11e9-8db9-790e69428668.png)

We'd like to keep it really minimal but want to:

* add a sidebar including recent posts
* show only the first 300px of the post content, with a `Read more` button that toggles the rest to be visible
* include social media links in sidebar
* include a list of recent tweets in sidebar

We'd love help chopping this up into pieces to implement! This is a pretty simple set of changes that would make some good first-timers-only issues!

**Comment by atjustbeinghumaid** [comment]
Hello!
I am interested in contributing
What needs to be done?

**Comment by CleverFool77** [comment]
Let's break this issue into various parts 🤔
And we can have awesome collaboration with all the contributors in this.
😀

**Comment by IshaGupta18** [comment]
yes, I think that would be great!

**Comment by IshaGupta18** [comment]
I could go with the first one if that's okay @jywarren !

**Comment by divyabaid16** [comment]
I can go up with the second one!

**Comment by atjustbeinghumaid** [comment]
I'll go with anything that makes me learn something new and gets your work done 😃

**Comment by gauravano** [comment]
Ok. Let's make a checklist. 
 - [ ] Create HTML layout and set up a temporary route for the page - @CleverFool77 
 - [ ] Listing blogs on the left. Also, design the post similar to the above design. @divyabaid16 and @atjustbeinghumaid 

- [ ] List recent posts in the sidebar. Design as above. - @IshaGupta18 
- [ ] Show recent tweets of Public Lab in the sidebar.   - @CleverFool77 

Add more to the checklist and divide further, as you like. Thanks everyone :100: :heart: !

**Comment by CleverFool77** [comment]
Thanks for breaking up this issue @gauravano .
I'll begin with first part of this issue. :smiley:

**Comment by gauravano** [comment]
Great!

**Comment by jywarren** [comment]
You all are awesome!!!! 🎉 🎉 🎉 🎉 

we could put the new version at /blog2 for now!!!

**Comment by dinaelhanan** [comment]
This is an awesome idea, I had my real look-through public lab last weekend and I was thinking about how slightly overweening it must be for people not familiar with it. This is definitely going to help

**Comment by CleverFool77** [comment]
Hi @jywarren @gauravano 
I'm bit confused regarding the basic html layout for blog2
Do I have to create a dummy layout like this ? or make changes to layout of `blog.html.erb` in `/blog2` route !!

![Screenshot from 2019-04-06 13-52-46](https://user-images.githubusercontent.com/26685258/55666940-42fef800-5873-11e9-8d9a-61aa3e4a2e50.png)

**Comment by gauravano** [comment]
> Hi @jywarren @gauravano
I'm bit confused regarding the basic html layout for blog2
Do I have to create a dummy layout like this in blog2.html.erb?

This one!

**Comment by gautamig54** [comment]
I would love to contribute to this task. 
I'll take up second and the third task. Adding social media links to the sidebar and showing only the first 300px of the post content, with a Read more button that toggles the rest to be visible.

**Comment by atjustbeinghumaid** [comment]
I previously assumed that the changes have to be made to the original blog file
Thank you @CleverFool77 for making things clear

**Comment by gautamig54** [comment]
@jywarren I think, the main post should also have the tags and like/spam/follow buttons displayed as well. 

![Screen Shot 2019-04-07 at 10 07 31 PM](https://user-images.githubusercontent.com/35326753/55686648-6912be00-5981-11e9-8994-ecaf3c437c71.png)

I would like to take up this task. Thanks!

**Comment by divyabaid16** [comment]
> I would love to contribute to this task.
> I'll take up second and the third task. Adding social media links to the sidebar and showing only the first 300px of the post content, with a Read more button that toggles the rest to be visible.

Hi, @gautamig54 actually I and @atjustbeinghumaid are doing the second one and @IshaGupta18 is going up with the third one. So I guess you can take up https://github.com/publiclab/plots2/issues/5352#issuecomment-480608025 if it is approved.
We will surely ask you for your help.
Thanks :smile:

**Comment by gautamig54** [comment]
Oh okay @divyabaid16. Thanks!

**Comment by jywarren** [comment]
#5394 merged! 🎉

**Comment by gautamig54** [comment]
Can we resume this issue and complete our assigned tasks?

**Comment by divyabaid16** [comment]
I think that all are connected. So before the review of #5449, we can't move on with the next one @gautamig54 
Thanks!

**Comment by gautamig54** [comment]
Since #5449 is about adding the read more link, we can still move ahead with the sidebar. What say @divyabaid16 ?

**Comment by IshaGupta18** [comment]
I'll take on my part in just a couple of days!

**Comment by gautamig54** [comment]
@gauravano  Can I work on designing the header for the blogs page as per the above design?

**Comment by gautamig54** [comment]
I have implemented the blog2 header. How about this?

![Screen Shot 2019-04-21 at 6 21 26 PM](https://user-images.githubusercontent.com/35326753/56470277-257c8180-6462-11e9-9974-2c7c578e54f2.png)

![Screen Shot 2019-04-21 at 6 20 42 PM](https://user-images.githubusercontent.com/35326753/56470284-2b726280-6462-11e9-833e-d4aab0fe7817.png)

**Comment by gauravano** [comment]
I don't think, we need to show header as we have navbar. But, we can keep the heading and logo I guess. @jywarren thoughts?

**Comment by gauravano** [comment]
Okay #5449 merged!

**Comment by gautamig54** [comment]
@gauravano I have referred the About, Method, Research and RSS from the current blogs page. The contents are different from what we have in navbar. 

![Screen Shot 2019-04-21 at 9 32 40 PM](https://user-images.githubusercontent.com/35326753/56472504-d0019e00-647c-11e9-8ec8-b1388170d2a7.png)

**Comment by gauravano** [comment]
@divyabaid16 @atjustbeinghumaid currently the blog shown is hard coded. Now, you need to show the research notes in blogs. You can refer to the logic of current blog page. 

Oh, I didn't noticed it :eyes:. Then, it makes sense, thanks @gautamig54!

**Comment by gautamig54** [comment]
@gauravano @jywarren Can you review #5567 so that we can start with the other things on the list. Thanks!

**Comment by chaurasia-namrata** [comment]
Is this project completed or any work is remaining? I would love to contribute to this project.

**Comment by gauravano** [comment]
Hi @chaurasia-namrata, it's still in-progress. you can see the progress at https://publiclab.org/blog2 and you can also help. Next part is claimed by @divyabaid16 and @atjustbeinghumaid but if they're busy you can claim it?

Thanks!

**Comment by chaurasia-namrata** [comment]
> Hi @chaurasia-namrata, it's still in-progress. you can see the progress at https://publiclab.org/blog2 and you can also help. Next part is claimed by @divyabaid16 and @atjustbeinghumaid but if they're busy you can claim it?
> Thanks!

Thanks @gauravano

**Comment by atjustbeinghumaid** [comment]
Anyone else can claim this issue

**Comment by divyabaid16** [comment]
Yes @chaurasia-namrata  you can work on this. Do ask in case you need any help.
Thanks!

**Comment by daningenthron** [comment]
Hi everyone 👋- we refactored the 'Read More' link to a button in response to a separate issue. I now see that was one of the original goals here. I'm happy to tackle another piece of the redesign if any help is needed?

**Comment by jywarren** [comment]
Hi, we'd love help with any part of the list of changes at the top! Thank you @daningenthron !

**Comment by jywarren** [comment]
Sorry about the stalebot message here, it was a mistake! 😅

**Comment by jywarren** [comment]
Hi all, we are still looking to spin out issues from this! https://publiclab.org/blog2 now exists, and so we are now mostly copying in content and functions from https://publiclab.org/blog to the new page -- we'd love help! 

The templates are:

1. https://github.com/publiclab/plots2/blob/main/app/views/tag/blog.html.erb (old)
2. https://github.com/publiclab/plots2/blob/main/app/views/tag/blog2.html.erb (new)

**Comment by Cadreia** [comment]
@jywarren I would like to work on this issue. Can I proceed?

**Comment by damiecode** [comment]
@jywarren I would like to work on this issue too. @Cadreia  can we divide it?

**Comment by RuthNjeri** [comment]
@Cadreia , @damiecode hi 👋🏾 , I'd like to tag in as well.. as a suggestion, maybe we could start with copying in the content, for example, the:

1. This is basic html layout
2. Recent Post
3. Categories

Do not have content, we can each create an issue for it then begin working on it if @jywarren approves.
In addition, just in case anyone else needs to work on something, 

4. The Public Lab Logo at the top is not present
5. The footer at the bottom has text that is not correctly aligned and some links are not visible(@jywarren can confirm if changes are needed)


There could be more needed issues, just in case anyone catches anything else...

**Comment by Cadreia** [comment]
@RuthNjeri that's a great idea. But like you said, we need @jywarren to approve this.
Also, I noticed an issue with mobile responsiveness. The content of the page exceeds the width of the screen on mobile devices.

**Comment by stacytonui** [comment]
I'd also love to take part in this.

**Comment by tawahpeggy** [comment]
I will like to be part of those working on this issue
