### ISSUE TITLE
Fix notes ordering in recent notes

### ISSUE THREAD

**Issue by jainaman224** [publiclab/plots2#5360]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/controllers/notes_controller.rb](https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -307,7 +307,7 @@ class NotesController < ApplicationController
     @wikis = Node.limit(10)
       .where(type: 'page', status: 1)
       .order('nid DESC')
-    @notes = Node.where(type: 'note', status: 1, created: Time.now.to_i - 1.weeks.to_i..Time.now.to_i)
+    @notes = Node.where(type: 'note', status: 1, created: Time.now.to_i - 1.weeks.to_i..Time.now.to_i).order(created: :desc)
     @unpaginated = true
     render template: 'notes/index'
   end
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by jainaman224** [comment]
Order of notes should be descending according to date. It is ascending currently.
![Screenshot 2019-04-03 at 10 02 41 PM](https://user-images.githubusercontent.com/13117482/55496315-613edb00-565c-11e9-9bf5-8f2348ca5251.png)

**Comment by namangupta01** [comment]
Nice catch 🎉 !

**Comment by gauravano** [comment]
@atjustbeinghumaid you can start working on this one. Thanks!

**Comment by atjustbeinghumaid** [comment]
Why are the tests failing?
Can anybody help?

**Comment by jainaman224** [comment]
Hey, Just create a PR. It is failing because PR is not created. Have a look at https://travis-ci.com/atjustbeinghumaid/plots2/builds/107054288#L4217.

**Comment by atjustbeinghumaid** [comment]
I have made a PR
Pls check and tell me if I have done it right
Suggestions are always welcome

**Comment by atjustbeinghumaid** [comment]
Just realized I made the changes in the master branch
Will create a descriptive branch name and do it again

**Comment by gauravano** [comment]
Hey @atjustbeinghumaid, the above mentioned PR is open at your forked repo, not against publiclab/plots2.

Thanks!

**Comment by atjustbeinghumaid** [comment]
I have made a pr pls check it

**Comment by gauravano** [comment]
Hi @atjustbeinghumaid, you are required to attach the screenshot there, after installing the repo - https://github.com/publiclab/plots2/pull/5393#issuecomment-480586942.

Thanks!

**Comment by AnshitaVishwa** [comment]
@gauravano I would like to work on this issue. can i continue with this issue?

**Comment by IshaGupta18** [comment]
We're going to open this up to new contributors -- thanks so much for your help, and please speak up if you'd like to continue! New contributors - this is now available to claim. Thanks, all!

Isha Gupta @IshaGupta18 Oct 05 23:16

**Comment by IvetaHron** [comment]
Hi, I would like to work on this issue. Could you please assign it to me?

**Comment by SidharthBansal** [comment]
Please check if this issue is solved or not. If no one is working on it and it is still unresolved then go for it

**Comment by ebarry** [comment]
I believe this has been fixed along the way when the menu was updated to offer the option to sort "by last updated": 
<img width="205" alt="Screen Shot 2020-10-19 at 10 10 32 AM" src="https://user-images.githubusercontent.com/161439/96462240-5c685a80-11f3-11eb-9cd2-23ffce5212fe.png">

In this gif i show https://publiclab.org/tag/indoor-air-quality, with correctly sorted "last updated" results: 
![sort-by-date](https://user-images.githubusercontent.com/161439/96462578-b6692000-11f3-11eb-9646-0fa0c298f937.gif)
