### ISSUE TITLE
Form field validation and password visibility

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5361]
## Description
While signup and editing the profile, there is need to write the password and confirm it by writing it again.
There is no way to check whether the password written in both of the field is same unless the submit button is pressed.
And while writing in form, we have no way to know that the data we wrote in field is in correct format.

**Instead we can have these two features in password** - 
* Password matching while filling up the form.
* Eye-icon similar to login form available in signup to toggle the visibility. or maybe we can have show password.

**And we can have this feature for form**
* Add Form validation so that the user gets notified about field errors as soon as the user tabs to next field.

![Screenshot from 2019-04-03 22-28-03](https://user-images.githubusercontent.com/26685258/55497814-c5af6980-565f-11e9-95e8-26f55f97714b.png)

I made a similar issue  and PR earlier for one of the part of this issue, which was for password visibility but it was for login form. 
https://github.com/publiclab/plots2/issues/5201

**Comment by CleverFool77** [comment]
@publiclab/plots2-reviewers What's your opinion regarding this issue ? 
Can we implement this ?

**Comment by IshaGupta18** [comment]
Yes even I thought of something similar, like to keep a strength checker for passwords. I think these 2 can be integrated?

**Comment by CleverFool77** [comment]
yeah, password validation for matching and strength checking

**Comment by IshaGupta18** [comment]
If approved, can we work on this together?

**Comment by CleverFool77** [comment]
Sure :smiley:

**Comment by IshaGupta18** [comment]
So I believe you have completed it all by yourself!

**Comment by gauravano** [comment]
Nice ideas @CleverFool77 @IshaGupta18. Go ahead! Thanks!

**Comment by CleverFool77** [comment]
@IshaGupta18 I just completed one part for now.

**Comment by IshaGupta18** [comment]
Could you please mention which one, so that I can work on the other one?
Thanks!

**Comment by CleverFool77** [comment]
> So I believe you have completed it all by yourself!

Hey Isha, the issue itself isn't big enough to divide.
Earlier while creating this issue , I thought that form validation and password matching would be two different parts. But as I explored I realised, they are in the same category using jquery-validation which makes everything easier.
So earlier which was supposed to be two different parts, in end, they become one. :sweat_smile:

**Comment by CleverFool77** [comment]
Hi Isha, the password visibility part is still left. 
If you're interested, you can work on it.
Thanks !!

**Comment by IshaGupta18** [comment]
Sure, would love to take on it!

**Comment by sakshi-2412** [comment]
@TildaDares can I work on this issue?
Also, is there a need to have a show password button in the signup form? as confirm password and show password are alternatives to each other, I am not sure if they should be used together. We can have a show password icon for current password in the edit profile form.

**Comment by sakshi-2412** [comment]
I realised that form field validation is not working in the edit profile form. #6331 has a possible solution. Can I take that up too?

**Comment by TildaDares** [comment]
@sakshi-2412 You're right about not needing a show password icon on the signup page since we have `confirm password` for that.

@sakshi-2412 You can work on form field validation in the edit form page. Thanks!

**Comment by TildaDares** [comment]
@sakshi-2412 Maybe you create a new issue specifically for the problem you're trying to solve to create better documentation of the problem.

**Comment by sakshi-2412** [comment]
Yes, I'll create a new issue! Thanks

**Comment by sakshi-2412** [comment]
@TildaDares I think this issue can be closed now😃 ( solved by #10604 )
