### ISSUE TITLE
Show default profile image in signup form.

### ISSUE THREAD

**Issue by Anupam-dagar** [publiclab/plots2#5373]
Currently a user has a default profile picture if a profile picture is not set but the same default image doesn't show up on signup page, instead a grey circle is shown.
![Screenshot from 2019-04-05 12-51-34](https://user-images.githubusercontent.com/21174572/55611618-ab7ea400-57a3-11e9-866a-936b38453df1.png)

**Comment by jywarren** [comment]
Hi, this is super! Thank you so much! I did want to note to @CleverFool77 that we should get our first-timers-only issues into full format before tagging them as such -- you can read more about the process here! https://publiclab.org/n/13667 Thanks so much to you both! 👍

**Comment by jywarren** [comment]
And if you are not quite ready to make it a full first-timers-only issue, you can always use the `fto-candidate` label!

**Comment by atjustbeinghumaid** [comment]
Hello!
I'm interested in contributing!
Please assign me to this issue

**Comment by gauravano** [comment]
Hey @atjustbeinghumaid, this issue has a PR at #5374. But, we would love to have your help with other issues. Are you done with FTO? Thanks!
