### ISSUE TITLE
traceback of error from server is shown in webpage

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5378]
## Description
While working on the issue https://github.com/publiclab/plots2/issues/5327
I found this. 
It showed the traceback of error from server on the webpage. And after I refreshed it, the tag was added.
The gif shows the steps to reproduce it - 

![ff](https://user-images.githubusercontent.com/26685258/55642796-1dc8a600-57ef-11e9-93f0-33ba3e1b0226.gif)

**Comment by CleverFool77** [comment]
@publiclab/plots2-reviewers What's your opinion regarding this issue ?

**Comment by jywarren** [comment]
Ah, i think this is where it's trying to fetch the result of an AJAX
request to add a tag, and displaying the response inline --

https://github.com/publiclab/plots2/blob/master/app/views/tag/_tagging.html.erb

It's supposed to catch errors here, but it seems it's not doing so...
https://github.com/publiclab/plots2/blob/c97968aa6bce38dbb2d66548ee05cae0dc4cdc23/app/assets/javascripts/tagging.js#L63-L68

So, something is going wrong in the error, and it's getting inserted into
the page here:
https://github.com/publiclab/plots2/blob/c97968aa6bce38dbb2d66548ee05cae0dc4cdc23/app/assets/javascripts/tagging.js#L41-L54

This is a great candidate for a system test!
https://github.com/publiclab/plots2/issues/5316

Thanks for catching this, @CleverFool77!

**Comment by CleverFool77** [comment]
Hi @jywarren I would like to. Fix this issue.

**Comment by gauravano** [comment]
Great!
