### ISSUE TITLE
Tooltip for visibility of bar in wiki pages missing.

### ISSUE THREAD

**Issue by Anupam-dagar** [publiclab/plots2#5382]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [_header.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/wiki/_header.html.erb#L19) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
- <a onClick="$('#wiki-toolbar').toggle()" class="btn btn-link"><b class="caret"></b></a>
+ <a rel="tooltip" title="Show or Hide the toolbar." data-placement="right" onClick="$('#wiki-toolbar').toggle()" class="btn btn-link"><b class="caret"></b></a>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by DGibbons1** [comment]
Hi @gauravano. I would like to claim this issue.

**Comment by gauravano** [comment]
Hi @DGibbons1, sure go ahead!

**Comment by michelelong** [comment]
@DGibbons1, @gauravano is this still being worked on or may I fix this?

**Comment by gauravano** [comment]
Hi @michelelong, there's a PR for this issue at #5414. I have asked the contributor to update on the status of the PR but am not sure whether they want to leave the issue or give the final push. Anyway, you don't have to wait. You can see other FTO issue at https://code.publiclab.org. I will also mention you if I see any. Thanks!

**Comment by idgrp19** [comment]
I would like to contribute to this project, if this issue is still open? This is my first contribution and i would like to do something at beginner level.

**Comment by gauravano** [comment]
Hi @idgrp19, yes, this issue is open and available to claim. Thanks!

**Comment by pydevsg** [comment]
@gauravano  and @Anupam-dagar can you please assign this issue to me.

**Comment by newbazz** [comment]
@pydevsg yes you can start working on this, i dont think this issue has any prs, you can file one and refer to this issue.

**Comment by pydevsg** [comment]
Okay I am taking this issue will come with a PR very soon.

**Comment by pydevsg** [comment]
@newbazz , @Anupam-dagar and @gauravano I have submitted a PR please review and merge it.

**Comment by CoderJolly** [comment]
PR #6356

**Comment by jywarren** [comment]
Unfortunately something went wrong with the PR and this is now open again -- thank you!!!

**Comment by ampaire** [comment]
Hello @jywarren, I have worked on this issue and will be glad if you check it out on this [Pull request](https://github.com/publiclab/plots2/pull/9594). This is my first time contributing to open source. I will be glad for any help rendered.
