### ISSUE TITLE
Close the "Subscribe+" popover  by clicking anywhere on the screen

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#5383]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

🤔 **What you will need to know.**
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

📋 **Step by Step**
🙋 Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

📝 Update the file [app/views/tag/_subscribe_button.html.erb] (https://github.com/publiclab/plots2/tree/master/app/views/tag/_subscribe_button.html.erb) in the plots2 repository. Currently, the subscribe popover closes only by clicking it back on it.

Attach a click event to the document body excluding the "#mypopcontent" which can be found by getElementById(), which closes the popover. 

💾 Commit your changes

🔀 Start a Pull Request. There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

You can also edit files directly in your browser and open a pull request from there.

🏁 **Done** Ask in comments for a review :)
Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update within a week of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

**Is someone else already working on this?**
🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- If someone seems stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

🤔❓ **Questions?**
Leave a comment below!

**Comment by gauravano** [comment]
Hey @gautamig54, although the issue is simple so don't require exact code snippet but could you add hint in the issue body? Thanks!

**Comment by gautamig54** [comment]
@gauravano I have added a hint in the issue body. Thanks!

**Comment by Isssabel** [comment]
Hi! I'm currently doing a project for my class which is to contribute to open source projects, and I would like to try and work on this issue. Can I claim this issue?

**Comment by gauravano** [comment]
Hi @Isssabel, sure, go ahead :+1:

**Comment by gauravano** [comment]
hey @Isssabel, I just saw that you claimed https://github.com/publiclab/plots2/issues/5385 so removing `claimed` label from here as you can work on only one FTO issue for a repo but you can help us with other non-FTO issues for sure after completing the claimed one. Thanks!

**Comment by ckairen** [comment]
Hi @gauravano, is there a way for us to setup the local environment so that it looks just like the publiclab.org? because some js features aren't included and it's kind of hard to test those out when the local environment doesn't have that implemented. thank you!

**Comment by gauravano** [comment]
Hi @ckairen, some parts of publiclab.org like footer, header of tags page, etc are stored in the database. We call them features, like here https://github.com/publiclab/plots2/blob/app/views/sidebar/_user.html.erb#L5 and there are many. So, you can also create a feature by logging in as admin and then going over at /features page and creat a feature with same title as name in the code.

Also, publiclab.org is the production environment so facebook share, etc are extra there.

If you want to test a particular section, feel free to ask, maybe I or @publiclab/plots2-reviewers can help you. Thanks!

**Comment by gauravano** [comment]
Hi @Isssabel, you started working on this issue? Thanks!

**Comment by ckairen** [comment]
Hi @gauravano, the one that we (me and @Isssabel) want to simulate is the subscribe + button. Now on local environment, the supposedly hidden list is not hidden and the button doesn't work.

**Comment by gauravano** [comment]
this is not related to feature or environment. Try running `yarn install`

This is my view 

![Screenshot from 2019-04-23 03-05-23](https://user-images.githubusercontent.com/20878070/56533137-b8a5dc00-6574-11e9-9ad8-fdc18950fd45.png)

**Comment by ckairen** [comment]
@gauravano we did run yarn install, but it still doesn't show. Is there a specific package that we should install?

**Comment by gauravano** [comment]
this is strange. Can you copy the errors from the console?

**Comment by ckairen** [comment]
Here it is
<img width="491" alt="Screen Shot 2019-04-22 at 5 39 08 PM" src="https://user-images.githubusercontent.com/38804567/56533421-9769cf00-6525-11e9-9bd2-15160e8f65da.png">

**Comment by gauravano** [comment]
I think, it's related to jQuery

**Comment by gauravano** [comment]
you master branch is up-to-date with the publiclab/plots2?

**Comment by ckairen** [comment]
yes it is.

**Comment by gauravano** [comment]
![Screenshot from 2019-04-23 03-12-46](https://user-images.githubusercontent.com/20878070/56533673-c60f9600-6575-11e9-9a13-b0b6d01ab2bb.png)

Please reset it to make even with `master` as something might be there

**Comment by ckairen** [comment]
ok I'll try to do that
and just a side note, I've already successfully implemented the html injection https://github.com/publiclab/plots2/issues/3608 , can I claim the issue?

**Comment by gauravano** [comment]
Ah, as you have already solved a issue and this one is a FTO so you might want to try a complex one? @Isssabel and you are working on this collaboratively?

**Comment by ckairen** [comment]
For #3608 it doesn't seem to be a FTO issue? (and yes @Isssabel is working on #5383 but was stuck on trying to recreate the subscribe+ button)

**Comment by gauravano** [comment]
Okay :sweat_smile:, you can work on a FTO. Although, contributors start from FTO and then move on to complex ones but go ahead!

**Comment by gautamig54** [comment]
@ckairen Are you using Safari? Even I used to get certain UI issues on safari, therefore I switched to Chrome.

**Comment by ckairen** [comment]
@gautamig54  I'm using chrome.
@gauravano @Isssabel  would work on this FTO, I'm just trying to solve the setup problem with her. Thank you for your understanding.

**Comment by ckairen** [comment]
@gautamig54 @gauravano  The problem seems to be fixed when I switched to Windows system, as you can see in the gif in my pull request. Not sure why this is the case though.

**Comment by SidharthBansal** [comment]
Is this issue resolved?

**Comment by sashadev-sky** [comment]
I would say yes or definitely stale. going to close it!
