### ISSUE TITLE
Make exception for `/` opening search when in a textbox

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5387]
Hi @CleverFool77 -- the new `/` feature to open the search box is AWESOME!!!

One funny thing though, i did notice it works when typing a / into a comment box. So maybe we should except text inputs and textareas from this binding? What do you think?

**Comment by CleverFool77** [comment]
Ahhhhhh, looks like i missed some cases. 
Damn I should have tested this before.
I would push a fix for it.
Thanks @jywarren :smiley:
