### ISSUE TITLE
Reduce the font-weight of the contents in the tags buttons

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#5388]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

📋 Step by Step
 🙋 Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

📝 Update the file [app/assets/stylesheets/style.css](https://github.com/publiclab/plots2/blob/master/app/assets/stylesheets/style.css) in the plots2 repository.

 Currently the font-weight of the content in the tags button is 700. Reduce the font-weight to increase readability.
In style.css, add font-weight in the label class. 

For testing the changes made, it can be seen in the tags mentioned in the sidebar of any page or in the dashboard where the tags have been mentioned.

![Screen Shot 2019-04-07 at 12 53 02 AM](https://user-images.githubusercontent.com/35326753/55674250-9b63e300-58cf-11e9-8178-f82e6d5cf81c.png)

 
💾 Commit your changes

🔀 Start a Pull Request. There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

You can also edit files directly in your browser and open a pull request from there.

🏁 Done Ask in comments for a review :)
Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update within a week of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

Is someone else already working on this?
🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- If someone seems stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

🤔❓ Questions?
Leave a comment below!

**Comment by gauravano** [comment]
Hey @gautamig54, can you make the issue more readable by using the exact template provided at https://github.com/publiclab/plots2/blob/master/.github/first-timers-issue-template.md .Also, please add link where the newcomer can test the changes. Thanks!

**Comment by gautamig54** [comment]
@gauravano I have updated the issue. Thanks!

**Comment by brjinks** [comment]
Hi can I claim this issue?

**Comment by gauravano** [comment]
Hi @brjinks, sure :+1:

**Comment by gauravano** [comment]
@jywarren any suggestion for font-weight?

**Comment by mnino** [comment]
Hello,

I am new to open source, so thank you for helping people like me take the first step.  I see that Brjinks has claimed this issue, but I was wondering if this issue is still open.  If so, I would like to help.

**Comment by brjinks** [comment]
@gauravano does a font-weight of 400 work?

**Comment by gautamig54** [comment]
Even I tried with font-weight of 400, it seems pretty good!

**Comment by IshaGupta18** [comment]
We're going to open this up to new contributors -- thanks so much for your help, and please speak up if you'd like to continue! New contributors - this is now available to claim. Thanks, all!

**Comment by loranazarenko** [comment]
Hello! Can i work with this issue?

**Comment by jywarren** [comment]
Hi all! I'm going to close this one as I think we are all good here. Thank you!
