### ISSUE TITLE
Disabled form fields on edit profile page in responsive mode

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5396]
## Description
The form fields are disabled in tablet mode. They don't respond to any clicks.
Although it's working fine on mobile and desktop versions.

![edit](https://user-images.githubusercontent.com/26685258/55681081-bd954980-593f-11e9-8fae-7afd07691b32.gif)

**Comment by gauravano** [comment]
@CleverFool77 would you like to solve this one? Thanks!

**Comment by CleverFool77** [comment]
Sure @gauravano 
Thanks !!
