### ISSUE TITLE
Forward slash in comment moves cursor to search box. 

### ISSUE THREAD

**Issue by bronwen9** [publiclab/plots2#5403]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by bronwen9** [comment]
I noticed that when typing the text of a comment, using the forward slash moves the cursor away from the comment field and places it into the search box, so that it is not possible to use a forward slash in the body of a comment.

**Comment by gauravano** [comment]
Hi @bronwen9, this issue is solved in #5395 and will be merged and hit the production soon. Thanks for notifying!

cc/ @jywarren
