### ISSUE TITLE
Bug in `with:` and `with` powertag

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5404]
while working on this issue https://github.com/publiclab/plots2/issues/5378
I found that error if `with` is added then it added @empty as author in comment box.
And if `with:` is added, then it doesnt give warning to add username as `:` is used but instead it gives traceback error

### To-do
* If `with` is added then don't add @empty as author in comment box
* If `with:` is added then give warning to add username.

![Screenshot from 2019-04-08 00-18-04](https://user-images.githubusercontent.com/26685258/55688428-fbbd5800-5995-11e9-8ef4-8332f0e43472.png)
![Screenshot from 2019-04-08 00-22-50](https://user-images.githubusercontent.com/26685258/55688429-fbbd5800-5995-11e9-9240-d5df556224e9.png)

**Comment by CleverFool77** [comment]
I'm interested in working on this issue if approved.
Thanks !!!!

**Comment by CleverFool77** [comment]
@publiclab/plots2-reviewers What's your opinion regarding this issue.
I'm interested in working on this issue.
Thanks !!!

**Comment by gauravano** [comment]
That would be great @CleverFool77. Thanks!

**Comment by gauravano** [comment]
Fixed in #5402. Thanks!
