### ISSUE TITLE
Error page when entering wrong password, then right password

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5405]
When I enter the wrong password from any page's Login modal, i get a 'wrong password' message, which is good. 

![image](https://user-images.githubusercontent.com/24359/55689285-a3179c00-5950-11e9-9485-5523eab68670.png)

But then I enter the right one, and i see an error page!

![image](https://user-images.githubusercontent.com/24359/55689281-9bf08e00-5950-11e9-93c5-2a812325caa2.png)

**Comment by 40404notfound** [comment]
Can I work on this?

**Comment by gautamig54** [comment]
I think this issue arises because there is no index action defined in the user-sessions controller.
It can be solved by creating an index function in user-sessions controller and directing the user to the dashboard from here. 
What do you think about this @jywarren ?

**Comment by gautamig54** [comment]
@40404notfound What are your thoughts on this? It will be great to have your opinion as well!

**Comment by jywarren** [comment]
That sounds like a great solution; where do you see it directing to an
index action? Thanks!!!

**Comment by gautamig54** [comment]
When I do the same procedure of first entering the wrong password and then entering the right one in my local system, it shows an error that index action is not defined in User-sessions controller.
I would like to work on this bug. Thanks!

**Comment by 40404notfound** [comment]
@gautamig54  Hi, I discovered the same issue. I am quite new to this project and I am still learning the project organization. I would love to help in solving this issue.
Can I have a chance to fix this? Thanks!!
![image](https://user-images.githubusercontent.com/32965363/55723688-a73acc80-59d7-11e9-8f21-e5c369721a5e.png)

**Comment by gautamig54** [comment]
Sure! Go ahead with this. Do ask if you are stuck anywhere :)
Welcome to Public Labs and hope to see many contributions from you!

**Comment by 40404notfound** [comment]
@jywarren @gautamig54 
Hi, I followed @gautamig54  's suggestion and makes the pull request. Looks like the issue is gone now! Thanks a lot for @gautamig54's great hint!

**Comment by jywarren** [comment]
oh awesome! Can you link us to your PR from here? Thanks so much for your
help!

**Comment by 40404notfound** [comment]
@jywarren Sure, here you go! https://github.com/publiclab/plots2/pull/5410
