### ISSUE TITLE
Add a tooltip on hover to the refresh dashboard icon

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#5407]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

📋 Step by Step
🙋 Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

📝 Update the file [app/views/dashboard/_activity.html.erb] in the plots2 repository. 
Add a text saying "refresh" when hovered on the refresh button on the dashboard.

![Screen Shot 2019-04-08 at 3 22 19 AM](https://user-images.githubusercontent.com/35326753/55690300-3d0d3200-59ad-11e9-8ce5-0f1d692089af.png)

💾 Commit your changes

🔀 Start a Pull Request. There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

You can also edit files directly in your browser and open a pull request from there.

🏁 Done Ask in comments for a review :)
Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update within a week of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

Is someone else already working on this?
🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- If someone seems stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

🤔❓ Questions?
Leave a comment below!

**Comment by Swati-rachamalla** [comment]
does the issue claim by anyone?

**Comment by gauravano** [comment]
Hi @gautamig54, the issue contains text from your previous issue. Please remove that. thanks! 

@Swati-rachamalla not yet. You can work on this, if interested. Thanks!

**Comment by aragort** [comment]
Hi! @Swati-rachamalla did you completed the request? I' am new and I don't know how to check if you need help

**Comment by zootechdrum** [comment]
Has anyone claimed this request? I would like to jump on this. I am new to contributing to open source projects.

**Comment by gauravano** [comment]
Hi @aragort, as @Swati-rachamalla has not responded from a week, you can work on this one. 

@Swati-rachamalla in case, you need new issue to work on, feel free to ask, there are many open FTOs. Thanks!

**Comment by gauravano** [comment]
Hi @zootechdrum, you can see other FTO issues at https://github.com/publiclab/plots2/issues?q=is%3Aopen+is%3Aissue+label%3Afirst-timers-only. In case, you don't see any unclaimed, feel free to comment at https://github.com/publiclab/plots2/issues/4963

Thanks!

**Comment by AdityaShD** [comment]
hey! @gauravano , can you please add me to #4963 , I am a first timer and would like to start contributing.

**Comment by ManethKulatunge** [comment]
I would like to claim this if no one is working on it. Thankyou!

**Comment by amitkumarpatel** [comment]
this issue is still open, I would like to claim this if no one is working on this ?

**Comment by vaibhavmathur13** [comment]
I would like to contribute to this project.

**Comment by gauravano** [comment]
Hi @vaibhavmathur13, yes, this issue is still open. Thanks!!

@ManethKulatunge @amitkumarpatel apologies for missing out your comments. If you're still interested in solving a FTO issue, then let me know, I'll create one for you. Thanks!

**Comment by vaibhavmathur13** [comment]
Thank you sir
I'll look into the matter.

**Comment by gauravano** [comment]
Hi @vaibhavmathur13, no need to use "Sir" or "Mam". Please address everyone by username like  @vaibhavmathur13 (or First Name in those cases where they have consented you)

**Comment by vaibhavmathur13** [comment]
Hi @gauravano , I have my base system up and running but I cannot locate the refresh button.
Can you help me locate it?

**Comment by skai-ste** [comment]
Hi, I’m an Outreachy applicant, could I work on this issue?

**Comment by CoderJolly** [comment]
> Hi, I’m an Outreachy applicant, could I work on this issue?

Hi @skai-ste, as @vaibhavmathur13 hasn't responded for more than a week, you can work on it.
Please mention the issue number while raising the PR. Thanks 😄 😄

**Comment by vaibhavmathur13** [comment]
Hi @CoderJolly , I have solved the issue, I will raise the PR by today.

**Comment by CoderJolly** [comment]
> Hi @CoderJolly , I have solved the issue, I will raise the PR in a day or two
> .

Ok, thanks for doing it !! 😄 😄

**Comment by skai-ste** [comment]
Hi again, all good. Could you recommend other issue I could look in to?

**Comment by CoderJolly** [comment]
Sure !! @skai-ste , mention your name at #6206 , a First-Timer Issue will be allotted to you soon
