### ISSUE TITLE
improve comment section in notes

### ISSUE THREAD

**Issue by avsingh999** [publiclab/plots2#5418]
when we click on publish button in the comment But the comment is blank and the total comment is count But after refresh page is working fine. more can see in the gif below
![pub7](https://user-images.githubusercontent.com/25536022/55755863-d0a63780-5a6d-11e9-93ad-e9b0377c1226.gif)

thank you : )

**Comment by gauravano** [comment]
Seems like we are updating the count via AJAX without checking its creation. you want to work on this @avsingh999? Also, nice catch!

thanks!

**Comment by avsingh999** [comment]
sure

**Comment by ValeriaCobianISW** [comment]
Hi @avsingh999 , are you still working on this issue? I would like to contribute with this :D @gauravano

**Comment by avsingh999** [comment]
@gauravano Sorry for that I am busy in my institute work(Projects) So I can't take this right now.
thanks : )

**Comment by ValeriaCobianISW** [comment]
Okay, I’m going to work in this issue for now 🙌🏼 Is it okay?

**Comment by ValeriaCobianISW** [comment]
Hi, this issue is done! @gauravano
Asking for feedback :D
