### ISSUE TITLE
Realtime username validation while signup

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5429]
## Description
Continuing on to https://github.com/publiclab/plots2/issues/5225
This issue aims to provide realtime username validation.
As soon as the user tabs on next field or out of focus for the username field. The query will be given to check whether username is available.

**Comment by GettyOrawo** [comment]
Hey @CleverFool77 this seems so interesting to do. I can help you out if you still held up.. :smile_cat:
