### ISSUE TITLE
Not able to write '/' in editor (triggers search bar shortcut)

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#5435]
I am not able to write '/' in an editor as '/' is set as shortcut for the search bar.

**Comment by jywarren** [comment]
I think this was solved in today's update! Thank you!!!

**Comment by gautamig54** [comment]
okay @jywarren. I'll close this issue
Thank you!

**Comment by jywarren** [comment]
Re-opening as this has reappeared in some places!

**Comment by jywarren** [comment]
We should be able to isolate the line of code where the shortcut is set up and exclude typing into `<input>` or `<textarea>` or woofmark-related (editor related) areas!

**Comment by jywarren** [comment]
Noting this was originally implemented in https://github.com/publiclab/plots2/issues/5174

and https://github.com/publiclab/plots2/pull/5190 was the PR. 

We do have exceptions shown here:

https://github.com/publiclab/plots2/blob/611bb67a8398135f83ba23137c834ef41ad82710/app/assets/javascripts/keybindings.js#L1-L11

But notice that the solution only changed the pointer CSS not the actual event! Fixing that now:

https://github.com/publiclab/plots2/blob/611bb67a8398135f83ba23137c834ef41ad82710/app/assets/javascripts/keybindings.js#L1-L3

**Comment by jywarren** [comment]
Solution in https://github.com/publiclab/plots2/pull/7872!!

**Comment by jywarren** [comment]
It'll need testing though. Once this is merged, let's try it out at https://stable.publiclab.org/post  by trying to make a link and typing in a `/`
