### ISSUE TITLE
Change curson to pointer in /signup page

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/plots2#5439]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [x] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [x] 📝 **Update**
Change cursor to a pointer while choosing an image in the signup page

file :app/views/users/_create_form.html.erb

![Peek 2019-04-10 12-41](https://user-images.githubusercontent.com/32747809/55859192-2b838000-5b8f-11e9-8a6e-c5f8ad7ed68a.gif)

Changes need to be done in the file: app/views/users/_create_form.html.erb

- [x] 💾 **Commit** your changes

- [x] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [x] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by divyabaid16** [comment]
Changes need to be done in the file :app/views/users/_create_form.html.erb

**Comment by IshaGupta18** [comment]
Hey @divyabaid16 could you delete this comment so that users don't think that this issue is claimed as it is marking 2 checkboxes? Thanks!

**Comment by divyabaid16** [comment]
@IshaGupta18 done!!!
Deleting this too :smile:

**Comment by MattMski** [comment]
I want to work on this, can i claim it

**Comment by gauravano** [comment]
Hi @MattMski, sure. I saw you already raised a PR :smile:. Reviewing it! Thanks!
