### ISSUE TITLE
Improve share function

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/plots2#5442]
![Selection_132](https://user-images.githubusercontent.com/32747809/55865600-56280580-5b9c-11e9-8e54-93d16b601567.png)

Changes need to be made:
- [ ] The link shared on twitter is not correct, it must share the correct tag link.
- [ ] Implement share by facebook also (In subsequent PRs)

**Comment by IshaGupta18** [comment]
Hey @divyabaid16 I think we may need to discuss this a little more and do the best we can to implement this. Thanks a lot!
