### ISSUE TITLE
README.environment outdated

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/plots2#5456]
This file:
https://github.com/publiclab/plots2/blob/master/README.environment

This is an issue as it's outdated, as well as a personal question:

Issue: 
- Do we want to keep the `README.environment` file? If so, we should update it. If not, we should move the last bit of information on `login credentials` somewhere else. 

Question: 
- Is `README.environment` a current convention for Rails repositories and if so, in what case? - Would it be inappropriate to just write login credentials for a development environment in the `README.md`?

**Comment by sashadev-sky** [comment]
@jywarren I ask a quick question here can you please get back to me about it when you have a moment? Thank you!

**Comment by dinaelhanan** [comment]
@sashadev-sky from what I've looked up/read README.enviroment is usually where environment variables used by the program is listed, no? (see [this](https://afni.nimh.nih.gov/pub/dist/doc/program_help/README.environment.html) link) if that is true, then our README.environment is unnecessary/wrong and we can just add the login credentials [here](https://github.com/publiclab/plots2/blob/Coveralls-test/README.md) under standard installation, right?

**Comment by sashadev-sky** [comment]
@dinaelhanan I'm really not sure! This is the only one I have ever seen before and it's clearly not in use so I don't have a good grasp on their use case. 

But if you think it should be removed I will make a PR for this. I don't want to put file deletion in an FTO, I feel like for a 1st PR conceptually that could be a bit confusing.

**Comment by jywarren** [comment]
Indeed we can remove this. I think it was stashed here long ago. If you'd like to move the login info that'd be great!

**Comment by sashadev-sky** [comment]
@jywarren Ok on it!
