### ISSUE TITLE
Add css to 'Subscribe to answer questions' button

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/plots2#5462]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [_question.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/tag/show/_questions.html.erb) in the `plots2` repository.
Use the css of the 'Ask a question' button for the 'Subscribe to answer' button.
Updated look:

![newlook](https://user-images.githubusercontent.com/32260628/55987948-473a7380-5cc0-11e9-9e64-36f4b632c7a1.png)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by ananyaarun** [comment]
Another issue based on the discussion here https://github.com/publiclab/plots2/issues/5180

**Comment by johnmidavis** [comment]
Forked and branched and fixed. I am having no luck passing the tests in the original or modified.

**Comment by ananyaarun** [comment]
Which test documentation ? Have you been able to install public Labs locally ? feel free to ask any question/help @johnmidavis :)

**Comment by johnmidavis** [comment]
I have successfully installed locally and am able to log in and do ad hoc testing. 

I am working through [TESTING.md:](https://github.com/publiclab/plots2/blob/master/doc/TESTING.md)

There is an issue running 'rails test -d' repeatedly - the database is not reset.  There is a rake task 'test:db' which does clean the database so this is obviously known. I can run db:drop and db:setup every time for now.

Also errors related to SUBSTRING_INDEX which should go away if I follow the instructions about running with MySQL.  I have MySql set up and running in docker locally, so I will follow up after I do that.

I have seen errors about connecting to  Redis on 127.0.0.1 - I am not running Redis on my machine - don't know if I'm missing something or this test is supposed to be skipped when not is staging or Travis or something.

**Comment by johnmidavis** [comment]
rake db:setup dies here

-- create_table("impressions", {:force=>:cascade})
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Specified key was too long; max key length is 3072 bytes: CREATE TABLE `impressions` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `impressionable_type` varchar(255), `impressionable...
[dbsetup.err.txt](https://github.com/publiclab/plots2/files/3075208/dbsetup.err.txt)

**Comment by ananyaarun** [comment]
@gauravano any idea why the above error is happening ?

**Comment by johnmidavis** [comment]
The bug is related to a style applied to one button - defined in erb versus another where the html is in the local yml file, with a different style. 

The database error, which is preventing me from running Test and Dev against MySql rather than SQLite, to hopefully pass test before creating a pull request.

**Comment by johnmidavis** [comment]
![Screenshot-after](https://user-images.githubusercontent.com/1994470/56085953-612f9f80-5e01-11e9-97ff-f5c533d4d6b0.png)
![Screenshot-before](https://user-images.githubusercontent.com/1994470/56085954-612f9f80-5e01-11e9-8165-bdcead55befe.png)

**Comment by johnmidavis** [comment]
**BEFORE**
![Screenshot-before](https://user-images.githubusercontent.com/1994470/56085968-94722e80-5e01-11e9-8440-2668a5349f97.png)

**AFTER**
![Screenshot-after](https://user-images.githubusercontent.com/1994470/56085974-a48a0e00-5e01-11e9-90ff-614621cd7b1f.png)

**Comment by gauravano** [comment]
Hi @johnmidavis, sorry for the inconvenience, we are having discussions to decide on database - https://github.com/publiclab/plots2/issues/4896. We would love to have your thoughts there too.

Regarding the failure of tests, you can ignore them and create a PR. But, if you're facing error in setup too, like in running `rake db:setup`, then we can discuss and try to solve that?

Thanks!
