### ISSUE TITLE
Redesigning the signup form

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5464]
## Description

Conitnuing on with https://github.com/publiclab/plots2/pull/5374#issuecomment-480515954
It was noticed that there is lots of space below the form fields of email.

![gg](https://user-images.githubusercontent.com/26685258/56016465-f6efff80-5d19-11e9-8b24-45a217328b9f.png)

And Many other details.
eg - 
* We are scrolling in modal ?
* The signup form fields are inconsistent

![Screenshot from 2019-04-12 11-58-28](https://user-images.githubusercontent.com/26685258/56016583-5a7a2d00-5d1a-11e9-9b5d-e3042456e66e.png)
 
So How about working on the redesign of signup form ?
It would be great to have discussion and ideas regarding this.
What's your views about this ? @publiclab/plots2-reviewers

**Comment by SidharthBansal** [comment]
Go ahead!! :+1:

**Comment by CleverFool77** [comment]
Sure @SidharthBansal 
I would like to have some great ideas regarding new signup form from you ? 
@divyabaid16 @ananyaarun @gautamig54 

cc : @jywarren @gauravano

**Comment by gautamig54** [comment]
Yes, @CleverFool77  Its a great idea. How about something like this? 

![Screen Shot 2019-04-12 at 3 34 28 PM](https://user-images.githubusercontent.com/35326753/56028933-e8641100-5d36-11e9-8774-8ece571c0411.png)

**Comment by SidharthBansal** [comment]
Let's first of all correct the issues pointed above. We can redesign it
later on.

**Comment by IshaGupta18** [comment]
I think that would be a good idea. We can break it up and divide it!

**Comment by gauravano** [comment]
We can start on other parts here. Thanks!

**Comment by divyabaid16** [comment]
What are other parts to be worked upon?
I would love to contribute here.
Thanks!

**Comment by gautamig54** [comment]
Let us come up with design mockups and then divide the tasks accordingly. What say @CleverFool77 @divyabaid16 @IshaGupta18?

**Comment by IshaGupta18** [comment]
That would be great!

**Comment by jywarren** [comment]
Hi! The modal is looking pretty good now, so I think i'm going to close this, but please feel free to re-open if I've misunderstood! Thank you!!!
