### ISSUE TITLE
Fix the search's submit button on the Tags page. 

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#5470]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

📋 Step by Step
🙋 Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

📝 Update the file app/views/tag/index.html.erb in the plots2 repository.
Currently, the search submit button disappears when clicked on the search text area. 

![Screen Shot 2019-04-13 at 1 17 54 PM](https://user-images.githubusercontent.com/35326753/56076430-84048880-5dee-11e9-891a-46ec0090f7b3.png)

💾 Commit your changes

🔀 Start a Pull Request. There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

You can also edit files directly in your browser and open a pull request from there.

🏁 Done Ask in comments for a review :)
Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update within a week of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

Is someone else already working on this?
🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- If someone seems stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

🤔❓ Questions?
Leave a comment below!

**Comment by gauravano** [comment]
Hi @gautamig54, please drop a hint for the solution or solution code snippet as it's an FTO. Thanks!

**Comment by gautamig54** [comment]
@gauravano Can I solve this issue?

**Comment by IshaGupta18** [comment]
@gautamig54 do you not want to keep this as an FTO and solve it yourself?

**Comment by gautamig54** [comment]
@IshaGupta18 I have solved the issue and pushed a PR for the same. Thanks!

**Comment by IshaGupta18** [comment]
Okay great!
