### ISSUE TITLE
Show something instead of empty table

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5471]
## Description
If a user has not subscribed to a topics then the webpage shows empty table.
Instead we can have webpage show that some sentence showing `No results found` or `you haven't subscribed to any topic` maybe.
I did a similar issue https://github.com/publiclab/plots2/issues/5188 and resolve it in  https://github.com/publiclab/plots2/pull/5189
 
![Screenshot from 2019-04-13 14-11-44 (1)](https://user-images.githubusercontent.com/26685258/56077223-393b3e80-5df7-11e9-8c41-7d0e4f4b9535.png)

**Comment by CleverFool77** [comment]
@publiclab/plots2-reviewers What's your opinion regrading this issue.
I'm interested in working in this.
Thanks !!

**Comment by gauravano** [comment]
Sounds great! Also, `You haven't subscribed to any topic yet` is apter than other one. Maybe, we can also add a link from where a user can subscribe to tags or we can add, `You haven't subscribed to any topic yet. Changes in any subscribed tagged research note/wiki from last week appears in this table.` 

text suggestions welcome! Also, mentioning @jywarren. Thanks!

**Comment by IshaGupta18** [comment]
Sounds lovely, if you will not mind , can I work on this issue? This is
because I have worked a lot with subscriptions here and would really like
to help in making it better. I will surely take guidance from you on how to
go about it but I really want to take a stab at it. Thanks a lot!
