### ISSUE TITLE
Include "coauthored" notes on profile pages (via `with:authorname` powertag)

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#5475]
Hi, I was recently looking on a profile page of someone I've coauthored some work with. (www.publiclab.org/profile/pat). Because she's listed as a coauthor, it's not showing up on the front page of her profile. Can we merge the tabs where people are authors and coauthors so they all show up under the primary tab?

**Comment by gauravano** [comment]
Hi @steviepubliclab,

You mean a tab with name "All", showing all notes(authored and co-authored)?  

Thanks!

**Comment by jywarren** [comment]
I think we should adapt this so that the profile page includes both in the same listing, esp after the new profile page has now launched! Renaming. Thanks!
