### ISSUE TITLE
change key to subscribe_to_answer

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/plots2#5489]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [en.yml](https://github.com/publiclab/plots2/blob/master/config/locales/en.yml#L381) and [_questions.html](https://github.com/publiclab/plots2/blob/master/app/views/tag/show/_questions.html.erb#L8) in the `plots2` repository to change line 380 and line 8 to subscribe_to_answer respectively.

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by ananyaarun** [comment]
@MagdalenaBiernacka., Do you want to work on this ? Thanks !!

**Comment by ar03** [comment]
@ananyaarun  If this isn't claimed by anyone, I am looking to start contributing! This or another FTO! Thanks

**Comment by Devdrod** [comment]
@ananyaarun  I will love to start contributing to this project, first timer with a bit of knowledge on JS,HTML,CSS and REACT.

**Comment by becomingajunior** [comment]
Looks like this is already claimed, but checking in just in case it's not.  Thanks publiclab for making something available for first-timers to work on! Am hunting for a first time contribution to a project.

**Comment by ananyaarun** [comment]
since there has been no response from @MagdalenaBiernacka , @ar03 you can claim this one :)
@Devdrod and @becomingajunior we shall find another fto for u soon!!
U can meanwhile comment on this issue to find an FTO https://github.com/publiclab/plots2/issues/4963
Thanks :)

**Comment by ar03** [comment]
@ananyaarun I did just complete an FTO if you want to pass this one all to someone else.

**Comment by z119** [comment]
I'm interested in claiming this

**Comment by becomingajunior** [comment]
Thanks!

**Comment by ananyaarun** [comment]
@z119 , Pls wait to be assigned an issue before claiming and working on it next time.
But good work with this one :)
Thanks!!
