### ISSUE TITLE
Initial features and tasks of Expanded Q & A system

### ISSUE THREAD

**Issue by ananyo2012** [publiclab/plots2#549]
These are the initial tasks that are needed to be completed for the initial look of the Expanded Q & A project. The Design ideas are motivated from the research note posted on https://publiclab.org/notes/ananyo2012/05-11-2016/design-ideas-for-expanded-q-a-project

- [x] Write basic CRUD actions for Question Controller and corresponding Views
- [x] Write functional tests for Question Controller
- [x] Create Answer Model and migration
- [x] Write create, update, delete action for Answer Controller
- [x] Rendering Answers using ajax requests
- [x] Write unit tests for answer model
- [x] Write functional tests for answer controller 
 
I will keep on updating the task list as I go on implementing the features and the issue can be closed on completion of the tasks.

**Comment by jywarren** [comment]
Ah, excellent -- feel free to merge my additions from #554 into here if it's easier for you.

**Comment by ananyo2012** [comment]
#555 closes covers first two tasks and #566 covers the remaining tasks. Closing this issue. I will open a new one for implementing commenting system for Q & A page.
