### ISSUE TITLE
Tooltip doesn't disappear

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/plots2#5497]
**Description**'
Tooltip doesn't disappear when I click on like button. 
![Peek 2019-04-17 00-50](https://user-images.githubusercontent.com/32747809/56238381-01a8ec80-60ac-11e9-9c89-efd19c7d9b4d.gif)

This is a bug that needs to be fixed. 

Thanks!

**Comment by ar03** [comment]
@divyabaid16 @IshaGupta18 Mind if I work on or alongside for this one?

**Comment by gautamig54** [comment]
There was the same issue in all the wiki pages also. I have solved it for them as the code base for events page is not available.

**Comment by IshaGupta18** [comment]
@arO3 if you can resolve for events page, go ahead!

**Comment by gautamig54** [comment]
@IshaGupta18 I have made changes in the app/views/like/_like.html.erb which solves for all the pages, I guess including events and wiki pages.

**Comment by IshaGupta18** [comment]
Oh okay, please confirm and get the PR reviewed so that this issue can
be resolved! @arO3 we would love your help on other issues!

**Comment by gautamig54** [comment]
@IshaGupta18 maybe @ARO3 can work on adding a timestamp to each tooltip. Should I open an issue for the same?

**Comment by IshaGupta18** [comment]
Yes that would be great! Go right ahead. Thanks a ton!
