### ISSUE TITLE
Add colour to the unfollow button on profile page

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#5502]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

📋 Step by Step
🙋 Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

📝 Update the file [app/views/users/_unfollow.html.erb] in the plots2 repository.
Change the class from `class : "btn"` to `class : "btn btn-primary"`

Current : 
![Screen Shot 2019-04-17 at 11 12 17 PM](https://user-images.githubusercontent.com/35326753/56308664-7db33b00-6165-11e9-9c24-4ca1adc1efe8.png)

Later : 

![Screen Shot 2019-04-17 at 11 12 33 PM](https://user-images.githubusercontent.com/35326753/56308683-860b7600-6165-11e9-8cd9-6c30628e5ba9.png)

💾 Commit your changes

🔀 Start a Pull Request. There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

You can also edit files directly in your browser and open a pull request from there.

🏁 Done Ask in comments for a review :)
Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update within a week of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

Is someone else already working on this?
🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- If someone seems stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

🤔❓ Questions?
Leave a comment below!

**Comment by z119** [comment]
If no one has yet, I'd like to claim this issue

**Comment by ehamamrah** [comment]
@z119 are you working on it? I would love to claim it.

**Comment by SamueleM97** [comment]
I wuold like to claim it.

**Comment by ehamamrah** [comment]
@SamueleM97 it's already claimed and pull request opened 
[](https://github.com/publiclab/plots2/pull/5505)

**Comment by sashadev-sky** [comment]
@ehamamrah Thank you for the PR! It will be reviewed shortly. Please note that typically if you see someone has requested to claim it, they have at least a week to open a PR or even comment some update regarding it until another user can open a PR for it. 

So this one should have been for @z119. Noting this not to scold you or anything but just so that you know the workflow and also so that @z119 knows they followed the workflow correctly. 

@z119 if you claim an issue you don't also have to follow up in the Create-First-Timers issue about it. That issue is for assigning FTOs to people that don't have one

@z119 we will make you another issue dont worry :)

**Comment by gautamig54** [comment]
@sashadev-sky I'll create another one for @z119.

**Comment by sashadev-sky** [comment]
@gautamig54 sounds good! For an FTO I recommend changing this to _logged in as_ - or removing the logged in as part altogether and just having it say "moderator"

<img width="1024" alt="Screen Shot 2019-04-20 at 1 02 39 AM" src="https://user-images.githubusercontent.com/41092741/56452979-197cac80-6308-11e9-94da-da186f2f4a94.png">

Will you make one out of this?? I will if you don't want to!

**Comment by gautamig54** [comment]
@sashadev-sky I'll open the issue. Thanks!

**Comment by gautamig54** [comment]
@sashadev-sky I'll open the issue. Thanks!

**Comment by gautamig54** [comment]
@sashadev-sky I have a doubt here. It is actually like "<username> - logged as moderator/admin" and for users who are not logged in as moderators or admins it just shows the username. 
In the localhost it shows so is because the username is also moderator, whereas the logged as part is the user role. 
What do you think?

**Comment by sashadev-sky** [comment]
Oh!! Ok then lets just make it "logged in as" and keep it. Thank you for looking into this 👍 👍

**Comment by gauravano** [comment]
Hi @z119 @SamueleM97, will mention you shortly after creating issues for you. Thanks!

**Comment by gauravano** [comment]
@z119 you can solve this one #5582 (@sashadev-sky thanks for highlighting the subject)
