### ISSUE TITLE
Decrease margin to css hover

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/plots2#5514]
Hover does not cover the entire thing. Some portion of the book icon is not aligend with css.
![Peek 2019-04-18 14-19](https://user-images.githubusercontent.com/32747809/56348875-058c5a00-61e5-11e9-85d6-c6f7abcbc0c4.gif)

**Comment by gauravano** [comment]
Hey @divyabaid16, please see https://github.com/publiclab/plots2/pull/5166. Also, if you're interested, you can help in completing that PR too. Thanks!

**Comment by divyabaid16** [comment]
@gauravano so this issue doesn't need to be solved as in #5516 we are just removing the background on hover. 
Also, should I create a new PR for solving #5166 as per the suggestions you have asked for ?
Thanks!

**Comment by divyabaid16** [comment]
@gauravano so this issue doesn't need to be solved as in #5516 we are just removing the background on hover. 
Also, should I create a new PR for solving #5166 as per the suggestions you have asked for ?
Thanks!

**Comment by gauravano** [comment]
> @gauravano so this issue doesn't need to be solved as in #5516 

you mean #5166 right?

Actually, you can collaborate on already existing PR. Thanks!

**Comment by divyabaid16** [comment]
Okay @gauravano I will do this within few days.
Thanks :)
