### ISSUE TITLE
Adding timestamp to the tooltip 

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#5517]
Add timestamps to tooltips on hover to the like section on events or wiki pages. Timestamps mean that the tooltip will close after the set time even if the cursor is on the button.

![Screen Shot 2019-04-18 at 3 03 55 PM](https://user-images.githubusercontent.com/35326753/56351570-058f5880-61eb-11e9-990f-daaec5e3861b.png)

**Comment by gautamig54** [comment]
This issue is for @ARO3. Thanks!

**Comment by gauravano** [comment]
Is it required as I don't think there's any issue with normal tooltip? Thanks!

**Comment by gautamig54** [comment]
okay @gauravano. I'll close this issue as it is not required. Thanks!
