### ISSUE TITLE
Comment Editing Seems Broken

### ISSUE THREAD

**Issue by bronwen9** [publiclab/plots2#5520]
It doesn't look like comment editing is working properly-- when I click into a comment to edit, it appears as though all of the original content has been removed-- if I click onto "save" on a blank edit the original content *does* repost to the page. 

![editcomment](https://user-images.githubusercontent.com/8331717/56370903-14194800-61ca-11e9-9bae-a533b3b9a561.gif)

**Comment by ValeriaCobianISW** [comment]
Are you working on this @bronwen9 ? I would like to contribute :smile:

**Comment by jywarren** [comment]
Hi @ValeriaCobianISW we would /love/ your help with this!!!!

**Comment by ValeriaCobianISW** [comment]
Sure, I'm going to work on this issue :D

**Comment by jywarren** [comment]
Please let us know if you need help with anything. Thank you so much!

**Comment by ValeriaCobianISW** [comment]
Hi, @jywarren I resolved this issue, I would like to get feedback :+1:
