### ISSUE TITLE
Match hyphens in node content when scanning for hashtags

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5527]
Since #532, when people post new pages, notes, questions, etc, the site scans the body content using this matcher:

https://github.com/publiclab/plots2/blob/b61ca7d0d9415e23659cf3fd93976349fc3488b4/app/models/revision.rb#L53-L58

It matches using this REGEX:

https://github.com/publiclab/plots2/blob/b61ca7d0d9415e23659cf3fd93976349fc3488b4/config/initializers/constants.rb#L4

And it tags the node with all the tags it finds -- stuff in the format `#tagname`, anywhere in the text.

We don't have tests for this, but we should! We could do a unit test in https://github.com/publiclab/plots2/blob/master/test/unit/revision_test.rb

However, the focus of this issue is to get it to match hyphenated words properly. It currently creates the tag `#purple` from the string `#purple-air`. Let's modify the regex to find hyphens too!

Actually the best way to test this would be to write the unit test first. Using `node.has_tag('purple-air')` to assert that it's done properly. Then to fix the regex and see the tests pass! Test-Driven-Development!!

We'd love help with this!

**Comment by ebarry** [comment]
Would love to see this one tackled! In the meantime, i'm editing out tags generated in error that end in a dangling hyphen like `simple-` `purple-` because they are adding noise to our tag search results, and our autosuggested tags.

**Comment by eplata31** [comment]
Hi, I'd love to help with this one

**Comment by gauravano** [comment]
Hi @eplata31, that's great :tada: . Thanks!

**Comment by eplata31** [comment]
Hello, I have made some advance and now I'm wondering if it should also accept low dash, something like `purple_air`? or just `purple-air`?

**Comment by gauravano** [comment]
Hi @eplata31, as hyphens are commonly used so solving that is the primary goal but if you can make regex for underscore `_` too, that would be great!

Thanks!

**Comment by eplata31** [comment]
l created a PR, asking for a review :D

**Comment by eplata31** [comment]
Hi @gauravano I'm getting fails from these two test `test_first-timer_moderated_note_(status=4)_shown_to_author_in_list_view_with_notice` and `test_first-timer_moderated_note_(status=4)_shown_to_moderator_with_notice_and_approval_prompt_in_list_view`, I don't now why since i didn't modify something that interacts with these test, can you help me?

**Comment by eplata31** [comment]
Hi, I noticed the fixture I created was the problem so I modified it and now all the test are green :+1:

**Comment by jywarren** [comment]
Oh this is awesome!!!
