### ISSUE TITLE
Design process for /questions page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#554]
@ananyo2012 - here's a sketch as promised!

![tmp_24437-img_20160531_215845 2152495967](https://cloud.githubusercontent.com/assets/24359/15696095/5d330ce2-277b-11e6-9478-a44010df25b5.jpg)

What do you think? There's more to do design wise for the display of the list of questions, for example showing only unanswered or answered questions. But this shows how suggested similar answers could be shown using autocomplete, like in the header search input. @ebarry and @steviepubliclab also, what do you think?

**Comment by ananyo2012** [comment]
@jywarren Looks great! Will implement this in the Questions page.

**Comment by ananyo2012** [comment]
Implemented using #555.

**Comment by jywarren** [comment]
We'll continue design refinement in this issue, thanks! Leaving open for now.

**Comment by jywarren** [comment]
A few followups for this -- it looks great, by the way!

* [ ] the "depressed" state of the list/grid toggle on the right side is a bit buggy -- seems like I can easily get both to be pressed-looking (see below)
* [ ] Is it possible to get the search results to use the new question templates, as the list page does? Coordination may eventually be necessary with @ujithaperera on this, but search results across the site should eventually use the new templates, which may need to be moved into a more generalized /views/ subfolder.
* [ ] can the autocomplete results show author name and # of likes, and whether the question is "answered"
* [ ] can the questions below not display tags? I think it's unnecessary but happy to debate
* [ ] the "post an answer" button doesn't seem to be working
* [ ] I think the sidebar may be unnecessary -- shall we see how it looks with that removed?
* [ ] have you developed a `node.answered` method for questions? It could check for whether there's an "answered" tag (at least for now; more advanced functionality could be added later)

Again, this looks really great!

![screenshot 2016-06-04 at 1 45 17 pm](https://cloud.githubusercontent.com/assets/24359/15801168/a20834e6-2a5a-11e6-86e0-888b837721c4.png)

**Comment by ananyo2012** [comment]
- The first issue is fixed with #565 
- I will be working on this besides creating the answering system and will be raising a PR soon
- Ok I will look into this too. It will depend on the answering system.
- To discuss on this, well I think showing tags on the list page directly shows the user what topic the question is about. If we want a good Q & A system we will want users to answer effectively i.e. help them choose what type of questions they would like to answer. Tags give additional information what the question is related to so that users don't have open each question and they can just know it glancing at the list. I think this should be a satisfactory answer.
- Yes the post an answer button doesn't work. It also depends on the answering system so it will be covered as I make the answering system.
- Ok I will give a screenshot on how it looks without the sidebar. Or perhaps we could keep the sidebar for the time being and show any information related to the questions and design some distinctive sidebars for questions controller and can be dealt in a later stage after completing on the answers and commenting system.
- I am presently working on the answering system. I intend of showing the no of answers besides the comment icon instead of the no of comments. A tooltip can be shown for explaining it.
- Yes that is a good idea we can do that on a later stage.

**Comment by jywarren** [comment]
Great, thanks!

> showing tags on the list page directly shows the user what topic the
question is about.

Makes sense; maybe we can use the info from the tags though, to show topics.

Re: sidebar, keeping the space is fine, I just think the content there is
adding noise. Maybe if we want to have a "subscribe to answer questions" or
"share your skills and knowledge" section it could go there?
This looks great. Like the design. Should the ask button also indicate it's
a search function? Might not need to, just wondering.
-Stevie

On Sun, Jun 5, 2016 at 12:30 AM, Ananya Maiti <notifications@github.com>
wrote:

>
> - The first issue is fixed with #565
> <https://github.com/publiclab/plots2/pull/565>
> - I will be working on this besides creating the answering system and
> will be raising a PR soon
> - Ok I will look into this too. It will depend on the answering system.
> - To discuss on this, well I think showing tags on the list page
> directly shows the user what topic the question is about. If we want a
good
> Q & A system we will want users to answer effectively i.e. help them
choose
> what type of questions they would like to answer. Tags give additional
> information what the question is related to so that users don't have open
> each question and they can just know it glancing at the list. I think this
> should be a satisfactory answer.
> - Yes the post an answer button doesn't work. It also depends on the
> answering system so it will be covered as I make the answering system.
> - Ok I will give a screenshot on how it looks without the sidebar. Or
> perhaps we could keep the sidebar for the time being and show any
> information related to the questions and design some distinctive sidebars
> for questions controller and can be dealt in a later stage after
completing
> on the answers and commenting system.
> - I am presently working on the answering system. I intend of showing
> the no of answers besides the comment icon instead of the no of comments.
A
> tooltip can be shown for explaining it.
> - Yes that is a good idea we can do that on a later stage.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/publiclab/plots2/issues/554#issuecomment-223794182>,
> or mute the thread
> <
https://github.com/notifications/unsubscribe/AHJLrqsaWWh-eIxthaRzA9lY0oAGb_y7ks5qIl8BgaJpZM4IrHwy
>
> .
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/554#issuecomment-223967174>,
or mute
the thread
<https://github.com/notifications/unsubscribe/AABfJ7pEHDL_Ye1p_tw0Yn1IT2e9kiR8ks5qJCfFgaJpZM4IrHwy>
.

**Comment by ananyo2012** [comment]
@ujithaperera @david-days The point 2 and point 3 mentioned above require changes in the search controller. Will it be okay if i go on with it? It would be nice if I could co-ordinate with your changes. If you suggest I can just make a pull request in your repository David.

**Comment by ujithaperera** [comment]
i changed the search controller a lot. But I kept remain unchanged your question action and question-typeahead action. After finishing with tests I am implementing solr. Till you can add anything to those actions without conflicts

**Comment by ananyo2012** [comment]
@ujithaperera Ok great! Then I guess I can go on with the changes.

**Comment by david-days** [comment]
This works for me, too, @ujithaperera.  If you make the changes that you require, @ananyo2012 , we can fold in those adjusted requirements as we build out our stuff.

**Comment by david-days** [comment]
We can handle any conflicts that arise on our end.

**Comment by ananyo2012** [comment]
@jywarren Points 2 & 3 are implemented in #581

**Comment by jywarren** [comment]
Great, can you check them off so we can track the remaining issues? (you can check off my checklists, right?) Thanks!

**Comment by ananyo2012** [comment]
Again permission issues Jeff!

**Comment by jywarren** [comment]
Ack, i see! OK, i'll do it. I wonder if I can give you permissions for things like this without push rights to the repository itself. Apologies!

**Comment by jywarren** [comment]
Design discussion also happening here: https://publiclab.org/notes/ananyo2012/07-25-2016/progress-of-the-expanded-q-a-project

**Comment by ananyo2012** [comment]
@jywarren I think this can be closed now with merging of #628. We can perhaps make a new issue with design ideas in future.

**Comment by jywarren** [comment]
Agreed! 👍
