### ISSUE TITLE
unanswered cards in answered tab

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5541]
## Description
I noticed that even if someone comments down on a question, but it's not answered. Then it is still being shown in `recently answered tab` though there is `no answer tag`.
For eg - Image below.
![Screenshot from 2019-04-20 00-29-49](https://user-images.githubusercontent.com/26685258/56439437-a7a26400-6303-11e9-9107-33bf4d26b88b.png)

So I had a question. If we consider all the tags recently commented in this tab then shouldn't we have tab name as `recent activity` on questions or `recently commented`.
And If we are just going by name `recently answered` then shouldn't we have only cards which are answered and have `answer tag` on them.

**Comment by CleverFool77** [comment]
@publiclab/plots2-reviewers What's your opinion about this ?

**Comment by gauravano** [comment]
@ViditChitkara I think you can better guide here. Thanks!

**Comment by ViditChitkara** [comment]
Hi @CleverFool77 and @gauravano . We are actually removing this tab after the recent comments/answer merge. Will be simply naming it as "commented". Thanks!!

**Comment by gauravano** [comment]
Cool!

**Comment by CleverFool77** [comment]
I'll be closing this issue as this will be resolved soon.

> Hi @CleverFool77 and @gauravano . We are actually removing this tab after the recent comments/answer merge. Will be simply naming it as "commented". Thanks!!
