### ISSUE TITLE
Restrict the wiki page edit to only author and admins

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#5546]
Currently, anyone who is logged in can edit a wiki page. I think it should be restricted to author and admins only.

**Comment by gautamig54** [comment]
@publiclab/plots2-reviewers What are your views on this issue?
If approved, I would like to work on this. Thanks!

**Comment by sashadev-sky** [comment]
@gautamig54 the definition of a wiki inherently means that anyone can collaborate or edit it, so I am going to close this issue! The one restrictions we have on wikis is that a user must have posted their own or a research note first before editing other wikis (this is for spam prevention)
