### ISSUE TITLE
Remove duplicate link to wiki pages on notes page

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#5547]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

📋 Step by Step
🙋 Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

📝 Update the file `app/views/notes/index.html.erb` in the plots2 repository.
        
- Currently, on the notes page, we have a wiki page tab alongside the popular/liked tabs and also, we have a link on the side bar which says "Browse the Public Lab wiki". Both of them correspond to the wiki page. Therefore, it's better if we remove the Wiki pages tab by removing lines 33-35 in the above file.

![Screen Shot 2019-04-20 at 11 09 33 AM](https://user-images.githubusercontent.com/35326753/56453208-9fc2de00-635c-11e9-8322-cfb16d40b9b3.png)

💾 Commit your changes

🔀 Start a Pull Request. There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

You can also edit files directly in your browser and open a pull request from there.

🏁 Done Ask in comments for a review :)
Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update within a week of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

Is someone else already working on this?
🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- If someone seems stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

🤔❓ Questions?
Leave a comment below!

**Comment by gautamig54** [comment]
@publiclab/plots2-reviewers Kindly review this issue. 
@z119 I have opened this issue for you. If this gets approved you can carry on with this. 
Drop a comment if stuck. Thanks!

**Comment by sashadev-sky** [comment]
@gautamig54 few things to update to make a better FTO:
-  link the production site notes page showing the UI issue you are trying to change
-  add a permalink after asking to remove the wiki pages tab showing exactly what code should be removed

**Comment by gautamig54** [comment]
@sashadev-sky I'll update the FTO. Thanks!

**Comment by sashadev-sky** [comment]
@gautamig54 cool mention me when to look at it again thank you!

**Comment by ValeriaCobianISW** [comment]
Hi, I´m new in open source contribution, I would like to work in this issue. Is somebody working in it? @gautamig54

**Comment by gautamig54** [comment]
@ValeriaCobianISW This issue was opened for @z119. Thanks!

**Comment by becomingajunior** [comment]
Hi there - I’d like to claim #5547 if I can. Please let me know if ok to start work on this. Thank you!

**Comment by gautamig54** [comment]
Sure! Go ahead @becomingajunior. Good luck!!!
