### ISSUE TITLE
Add tooltip in revision history table buttons

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5552]
## Description
The image below consists of various buttons but these buttons doesn't have tooltips.
For eg - It's difficult to understand the purpose of two sidearrows button which stands for raw version of content. And many more.
In the second column of grid. The comparison of revision history has previous and next arrows but it doesn't have tooltip.
![Screenshot from 2019-04-20 11-08-51](https://user-images.githubusercontent.com/26685258/56453406-d9e1af00-635f-11e9-8081-3a059ffbcdb0.png)

**Comment by siaw23** [comment]
I don't think that's a next/previous button. Doesn't that stand for 'code'?

**Comment by CleverFool77** [comment]
Hi @siaw23 
I guess they are for next and previous code comparison.
