### ISSUE TITLE
Remove the redundant table row

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5565]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

📋 Step by Step
🙋 Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

📝 Update 
Remove the lines in plots2/app/views/wiki/revisions.html.erb in line 14 to line 16
```diff
- <tr>
-       <%= raw t('wiki.revisions.table_content') %>
- </tr>
```
## Earlier 
It looked like this - 
![Screenshot from 2019-04-21 16-50-39](https://user-images.githubusercontent.com/26685258/56469318-1394e180-6456-11e9-8d75-f98f83b621f6.png)

## After changes
It should look like this -
![Screenshot from 2019-04-21 16-50-28](https://user-images.githubusercontent.com/26685258/56469321-1d1e4980-6456-11e9-84a2-4bb652b1e1cd.png)

💾 Commit your changes

🔀 Start a Pull Request. There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

You can also edit files directly in your browser and open a pull request from there.

🏁 Done Ask in comments for a review :)
Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update within a week of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

Is someone else already working on this?
🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- If someone seems stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

🤔❓ Questions?
Leave a comment below!

**Comment by monsij** [comment]
Interested! @CleverFool77

**Comment by CleverFool77** [comment]
Go forward @monsij

**Comment by UNnamed66** [comment]
This is my first time to make a contribution to the open source community. I was wondering if I can also give it a shot.

**Comment by gauravano** [comment]
Hi @UNnamed66, we would love to have your help, but this one is already claimed so please look for other issues at https://code.publiclab.org/#r=all and if you can't see any issue unclaimed, then feel free to comment at https://github.com/publiclab/plots2/issues/4963 and we'll create an issue for you. 

Thanks!

**Comment by CoderJolly** [comment]
Still open, or any PR received ?
