### ISSUE TITLE
Remove the duplicate link to the child wiki pages on the sidebar

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#5576]
Can we remove the link to the sub pages of a wiki page on the sidebar since we already have a list of sub pages on the wiki page?

![Screen Shot 2019-04-22 at 4 01 05 PM](https://user-images.githubusercontent.com/35326753/56496946-2a503c80-6519-11e9-8056-d9ba2b235655.png)

![Screen Shot 2019-04-22 at 3 57 02 PM](https://user-images.githubusercontent.com/35326753/56496955-320fe100-6519-11e9-8d8f-8e6b5c6f551d.png)

**Comment by gauravano** [comment]
Hi @gautamig54, the list is present in the wiki because of shortcode 
```
### Subtopics

[wikis:parent:air-quality]
```
In case, where the shortcode is not used by author, the list wouldn't appear so it's fine to have the link in the sidebar. Thanks!
