### ISSUE TITLE
System test for Preserve `return_to` param when switching from /login to /signup

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#5585]
Write System test for Preserve `return_to` param when switching from /login to /signup

**Comment by SidharthBansal** [comment]
As per @jywarren 's suggestion 
>This looks good. Would you like to try writing a simple system test for it? The system tests can include interactions like clicking, and then confirming things appear, even with JS interactions! See #5525

**Comment by SidharthBansal** [comment]
@jywarren in which file we have to write the new tests?

**Comment by SidharthBansal** [comment]
Also, as per theory, system tests should have non-functional requirements also to be tested like latency and related stuff. But I am unsure whether we are incorporating them here or not.
Actually, I am a student of Software Engineering so I am taught each phase of Software Development Life Cycle as a subject. So, just trying to collaborate the work which we learn at university and work which we implement at PL for better visualization of topics.

**Comment by SidharthBansal** [comment]
Getting the following error
> Selenium::WebDriver::Error::WebDriverError:         Selenium::WebDriver::Error::WebDriverError: Unable to find chromedriver. Please download the server from
        https://chromedriver.storage.googleapis.com/index.html and place it somewhere on your PATH.
        More info at https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver.

@jywarren it will be great if you can tell the link of the post from where you set up the system tests. I think we need to document the prerequisites of system tests(selenium server, chrome browser etc) in the prerequisite section too. What do you think?

**Comment by SidharthBansal** [comment]
Published on GCI dashboard

**Comment by okonek** [comment]
@SidharthBansal Hi, I took on this issue a while ago. Could you explain a bit more what should the test check, because I don't get what you meant by: "Preserve return_to param when switching from /login to /signup"?

**Comment by SidharthBansal** [comment]
Hi, if someone goes from signup to login form then the return to should be
preserved. Eg person on wiki page wants clicks login then signup
