### ISSUE TITLE
Introduce test suite for JavaScript functionalities 

### ISSUE THREAD

**Issue by ananyo2012** [publiclab/plots2#559]
Relating to various JavaScript based functionalities it would be great if we have a test suite for testing out JavaScript functionalities. As Proposed by @jywarren we will be using [Jasmine ](https://github.com/jasmine/jasmine) for running JS tests. Jasmine would be best suited as it is a TDD based framework and the syntax is quite similr to [Rspec](http://rspec.info/) and suited for those familiar with Rails. 

For more information refer to its github Repo : https://github.com/jasmine/jasmine. Here is the getting started documentation: http://jasmine.github.io/2.0/introduction.html

**Comment by jywarren** [comment]
#567 has the basics in place and I'm working on getting `jasmine-ajax` working so we can fake AJAX requests and test that requests are triggered properly.

**Comment by jywarren** [comment]
OK, it's working now, but our code is not very well organized for testing... yet! Closing as #567 creates the framework, we just need to write tests now.
