### ISSUE TITLE
"Like" text is missing from Like button on research notes

### ISSUE THREAD

**Issue by Fastie** [publiclab/plots2#560]
### What happened just before the problem occurred
I was looking for the like button on a research note. I swear there used to be one.

### Relevant URLs

https://publiclab.org/notes/mathew/06-03-2016/diy-mini-kite-kit-first-flight

### PublicLab.org username

cfastie

### Browser, version, and operating system
Chrome Version 50.0.2661.102 m Windows 10

**Comment by Fastie** [comment]
I guess it's called the Follow button now.

**Comment by Fastie** [comment]
Adding the word "Like" to the tooltip is probably a good idea. It's good that liking a note also follows it (notifies you of activity). The "like" part is probably more important because the author gets notified so liking is a way of communicating with the author and to a lesser extent anyone who notices how many likes a note has.

**Comment by jywarren** [comment]
Great, that's a pretty easy fix for this, if that sounds good to stevie as
well.

**Comment by steviepubliclab** [comment]
"Like" ;)
