### ISSUE TITLE
Redirect user to the same page after multi tag subscription

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#5600]
I think we should redirect the user to the same url after multi tag subscription, instead of /subscriptions so that the user will remain on the current research note or wiki page. Implemented the same in the pr.

**Comment by SidharthBansal** [comment]
@gauravano @ebarry @jywarren please tell whether we need this feature or not. I have created a PR for this with modified tests. If you folks like it then please merge it else we can close both issue and the pr.
Thanks

**Comment by SidharthBansal** [comment]
@jywarren

**Comment by jywarren** [comment]
Hi @SidharthBansal i agree with this! Let's wrap it up and merge this!

**Comment by SidharthBansal** [comment]
Things are connected Jeff. Once we are done with the OAuth redirection pr
then things will become clearer.

**Comment by SidharthBansal** [comment]
@Uzay-G is this issue resolved?

**Comment by SidharthBansal** [comment]
@Uzay-G can we do this first?

**Comment by Uzay-G** [comment]
Before the testing? Yeah ok no problem!

**Comment by SidharthBansal** [comment]
Sure. Let's do testing after it. This is simpler issue

**Comment by SidharthBansal** [comment]
Kindly submit https://codein.withgoogle.com/dashboard/tasks/6647913501949952/
