### ISSUE TITLE
Add ellipsis to tag if the tag length exceeds the dropdown.

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5609]
## Description
![Screenshot from 2019-04-24 19-45-37](https://user-images.githubusercontent.com/26685258/56666453-8fe32b00-66c9-11e9-86d7-3db859ffef97.png)

Tha tags with large no of characters might go out of dropdown. So we can limit the size of tags from going out of dropdown by putting ellipsis after some characters ?
Thus making the ui consistent.

Thanks !!!

**Comment by CleverFool77** [comment]
@publiclab/plots2-reviewers What's your opinion regarding this.
I'm interested in working in this.
Thanks !!

**Comment by sashadev-sky** [comment]
@CleverFool77 This makes me think maybe more importantly we should limit the size of usernames? Figure out what conventionally would be the number limit to set and set that, then check if we need the ellipsis or even just add it anyway just in case.

What are your thoughts?
