### ISSUE TITLE
Pop up subscription modal /after/ opening multi-tag subscription modal

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5614]
@SidharthBansal just looking to wrap this up; am I right that we can remove the login modal part of this segment:

https://github.com/publiclab/plots2/blob/7744d91e9bf03544da2f38e7e66056b6f20162e0/app/views/tag/_subscribe_button.html.erb#L12

and add the `requireLogin` class to this line?

https://github.com/publiclab/plots2/blob/7744d91e9bf03544da2f38e7e66056b6f20162e0/app/views/tag/_tags_popover.html.erb#L11

If so, let's do this, and then write a system test to protect it! Thank you!!!

**Comment by jywarren** [comment]
system test could be like:

```ruby
  test 'multi-tag subscribe button ' do
    visit nodes(:blog).path

    click_button 'sub'

    find('subscribe').click

    assert_selector('#loginModal', visible: true)

    fill_in("#username-signup", with: "newUserName")

    ...
  end
```

**Comment by IshaGupta18** [comment]
I'll do this @jywarren since this was assigned to me but I was unable to do it because of the major issue we were facing of rendering the popover of the Subscribe button. I sincerely apologize for all the delay and will wrap this one up ASAP! Thanks a lot for your patience!

**Comment by IshaGupta18** [comment]
@jywarren @SidharthBansal I am not very sure that doing this is working out, I saw this behavior before as well

![image](https://user-images.githubusercontent.com/40794215/56730422-9b8c2b80-6775-11e9-8ee2-f533a950c4c6.png)


When the user is logged out, on clicking on the button, the login modal should pop-up, right? That's not happening here. Please correct me if I am wrong here. Thanks a lot!

**Comment by IshaGupta18** [comment]
Also, I had to use JS to dynamically render the popover to the subscribe button, so that could also clash with the requireLogin class (although that is not the reason why it's not showing up).  What do you think should be done here?

**Comment by IshaGupta18** [comment]
@jywarren @SidharthBansal I think I have found a fix to this, although it might be a little unconventional (because of the dynamic rendering)

Also, to have similar behavior we have right now with the if condition, we need to add the class to the Subscribe+ button so that the modal pops up if the user clicks on the Subscribe+ button. I hope that's cool?

**Comment by IshaGupta18** [comment]
Here's my PR (without the test for now), kindly review and let me know what else can be done here! Thanks a lot!
