### ISSUE TITLE
Paginator on home page not working.

### ISSUE THREAD

**Issue by siaw23** [publiclab/plots2#5615]
When you scroll down on https://publiclab.org/, there's a paginator that's not working. Maybe someone would like to look at this?
![Screenshot 2019-04-25 at 03 09 59](https://user-images.githubusercontent.com/4806407/56703249-49f98780-6708-11e9-9f78-380a05a04d77.jpg)

**Comment by gautamig54** [comment]
I was trying out this issue and in order to check if my solution works, I created certain blog post (notes with blog tag). Those blogs are appearing on the blogs page but not on home. Is it hard-coded? 
If not then how should I generate notes on the home page?

**Comment by jywarren** [comment]
Hmm, Gautami, that should be working... Is it possible it's caching? But
that would only happen in production mode. Hmmmmm. I'm a bit stumped! Can
you try running the query from the controller in the rails console to see
if it returns correctly there?

**Comment by snpd25** [comment]
@jywarren , can I work on this?

**Comment by siaw23** [comment]
Please go for it. I don't see anyone working on this @snpd25 🙂

**Comment by jywarren** [comment]
Hi, all - we are soon to replace the home page, so perhaps best we close this! Thank you both however!!!
