### ISSUE TITLE
Align /stats page content

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#5619]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

### 🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step
- [ ] 🙋 **Claim this issue:** Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update:**
At https://publiclab.org/stats. Align the contents of this page. 

![Screen Shot 2019-04-25 at 4 59 32 PM](https://user-images.githubusercontent.com/35326753/56732520-4c48f980-677b-11e9-8f2d-9a41f6df3d7b.png)

Update apps/views/stats/index.html.erb in the plots2 repository. 
Add style in line 1. `margin-left:25px;`

After changing the view, also attach the screenshot of updated view in the PR.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request.** There are two ways how you can start a pull request:

 1. If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

 2. You can also edit files directly in your browser and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?
Leave a comment below!

### Is someone else already working on this?
We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seem stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

**Comment by maciejduda1** [comment]
Hello, I will gladly help.

**Comment by gautamig54** [comment]
Great @maciejduda1 !!
