### ISSUE TITLE
Test install-script for codenvy 

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#5622]
We updated install-script in mapknitter to support codenvy in https://github.com/publiclab/mapknitter/pull/420 following the shutdown notice of cloud9 by June 30, so we need to create a new wiki guiding users to codenvy just like https://github.com/publiclab/plots2/wiki/Simple-Installation-for-Cloud9 and after that make changes in Readme too.

Any suggestions and help is welcome. Thanks!!

**Comment by gauravano** [comment]
@publiclab/plots2-reviewers @kaustubh-nair @sashadev-sky @alaxalves @cesswairimu

**Comment by AnthoniaOkafor** [comment]
While installing Plots2 on Codenvy, some commands do not run:

$ rvm install ruby-2.4.4 returns bash: rvm: command not found
$ npm install -g yarn returns bash: npm: command not found
$ yarn install returns bash: yarn: command not found.
Rails 5.0.1 and ruby ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux] are pre-installed but rvm is not.
I continued without using the commands above until I got the error "'couldn't find file 'bootstrap/dist/css/bootstrap.min.css' with type 'text/css'". See the attached photos.

![Codenvy](https://user-images.githubusercontent.com/40716023/56960233-0360be80-6b48-11e9-97f1-fca0e498554e.png)
![Codenvy_Screenshot](https://user-images.githubusercontent.com/40716023/56960234-0360be80-6b48-11e9-87cc-878a8b3deb73.png)

**Comment by gauravano** [comment]
Please try running  `yarn install`.

**Comment by jywarren** [comment]
Did this work for you, @AnthoniaOkafor ? Thanks!

**Comment by AnthoniaOkafor** [comment]
> Did this work for you, @AnthoniaOkafor ? Thanks!

Rails 5.1 and above have been integrated with yarn,  I ran `rake yarn:install` because `yarn install` would not be recognised. But I'm still getting same errors as the one in the above photo.

**Comment by cesswairimu** [comment]
Gitpod is working perfctly on plots2. I think we could stick to that for now. I believe the mapknitter setup worked fine though, we could refer to the implementation there if we need it in future.  Closing this. Thanks all
