### ISSUE TITLE
Idea For Keeping a List of Weekly Check-ins

### ISSUE THREAD

**Issue by skilfullycurled** [publiclab/plots2#5624]
I love the idea that we move the weekly check-in around.  While I know it's predicated on giving other repo's exposure, it's also a fun surprise to see where it will be each week.  

Having said that, I do find it difficult to find the previous check-ins.  Also, the [documentation states](https://github.com/publiclab/plots2/blob/master/doc/CHECKINS.md) that the [current](https://github.com/publiclab/plots2/issues?q=is%3Aopen+is%3Aissue+label%3A%22community+check-in%22) and [past check-in's](https://github.com/publiclab/plots2/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22community+check-in%22+) can be found in the plots2 repo issues.

In order to have the best of both (move around every week and have a centralized record) I'd like to propose that we keep references to the check-in in an issue in the plots2 repo. This way, as long as we reference the issue number in the new check in, it will show up in that issue.  Then we can change the wiki page to link to that specific issue.

Any other ideas?

**Comment by gauravano** [comment]
Yeah, creating a central issue sounds great. We will keep that issue pinned to plots2. Would you like to create that issue or should I?

Thanks!

**Comment by skilfullycurled** [comment]
I'll do it.  There's something very satisfying about creating the only issue that will never close.  Or, wait.  It'll still work if I close it, no?  Then there will be something very satisfying about solving my own issue.

**Comment by gauravano** [comment]
haha, it will never close :sweat_smile:

**Comment by gauravano** [comment]
Let me know, if you need help in navigating  checkins.

**Comment by skilfullycurled** [comment]
Seems like the initial info at the top of the check in is pretty standard and customized each week.  Can the issue number be added to the standard part?

**Comment by skilfullycurled** [comment]
I'll work on going through the previous ones later.  Could you add labels to it?  I don't want to pollute it with this thread but you'll find it if you search, is:issue:"community check-in".  I'll also change the link in the wiki at some point.

**Comment by gauravano** [comment]
Done!

**Comment by skilfullycurled** [comment]
Awesome!  Now we don't have to change the links.  Although it would have made a good FTO.  ; )

<img width="560" alt="Screen Shot 2019-04-26 at 12 28 37 PM" src="https://user-images.githubusercontent.com/950291/56822402-f037b100-681e-11e9-90e9-f523b85a16ad.png">

**Comment by gauravano** [comment]
The check-ins would be tagged in the issue 5624 but I was thinking should we make a list of previous check-ins like:

**Previous Check-ins:**
1. 
2. 
...

**Current check-in:** link ..

What do you think?

**Comment by skilfullycurled** [comment]
Works for me!

**Comment by skilfullycurled** [comment]
(closing issue, but happy to re-open!)

**Comment by gauravano** [comment]
Thanks @skilfullycurled. i will add the previous check-in list in some days. Thanks!
