### ISSUE TITLE
Link "Public Lab" on navbar to the home page instead of dashboard

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#5629]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

### 🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step
   - [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

  - [ ] 📝 **Update**:  Currently, "Public Lab" on the navbar links the user to the root_path i.e, dashboard. Instead it should link to the https://publiclab.org/home page as we already have a separate dashboard link on the navbar.
   Update apps/views/layouts/_header.html.erb in the plots2 repository.
Change `href="<%= root_path %>"` to `href="/home"` on line 14

  - [ ] 💾 **Commit** your changes

  - [ ] 🔀 **Start a Pull Request.** There are two ways how you can start a pull request:

   1. If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

   2. You can also edit files directly in your browser and open a pull request from there.

  - [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?
Leave a comment below!

### Is someone else already working on this?
We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seem stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

**Comment by elzatch4219** [comment]
Is somebody else working on this

**Comment by gautamig54** [comment]
@elzatch4219 It is still not claimed. You can go ahead with this one!

**Comment by IshaGupta18** [comment]
Please go ahead @elzatch4219  and do let us know if you're stuck!

**Comment by CoderJolly** [comment]
Generated PR #5686

**Comment by gautamig54** [comment]
@CoderJolly Great work! Welcome to PL.

**Comment by CoderJolly** [comment]
Still taken ?

**Comment by ManethKulatunge** [comment]
Hi! Can I claim this issue?

**Comment by Gagan6730** [comment]
Hi! Is somebody working on it??

**Comment by jywarren** [comment]
Hi, I think actually we may want to close this as we are in the midst of a
navigation bar redesign. Thank you!

**Comment by jywarren** [comment]
I'm sorry, i see that @CoderJolly and @Gagan6730 have both opened PRs for this. My sincere apologies for missing this, and my deep appreciation for everyone helping out! 

I think that people may find it hard to get to the dashboard if we make this change, and that the home page is mostly for people first visiting the site, so we've long been OK with / redirecting to /dashboard if you are logged in. I hope you understand that we want to be pretty careful with this basic behavior and while we're open to discussing and weighing the pros/cons/alternatives, I think we ought to hold off on a change for the time being!

❤️ 👍 

I'm going to close this up for now just so folks don't get confused. But we are very grateful for your help and would love to help you find another issue to work on! Thanks @gautamig54 @Gagan6730 @CoderJolly !!!
