### ISSUE TITLE
/questions/liked/ page shows doubled posts

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#563]
@ananyo2012 -- https://publiclab.org/questions/liked/ page shows a post more than once; maybe the query needs to enforce uniqueness with a `.group(:nid)` addition to the query.

**Comment by ananyo2012** [comment]
@jywarren Ah I also see it on https://publiclab.org/questions?page=3. But isn't nid supposed to be unique?

**Comment by jywarren** [comment]
it may be, but depending on the type of join, you may return multiple
results across a many-to-many relation. But if you group by nid, you will
be fine.

**Comment by ananyo2012** [comment]
@jywarren Included The fixes in #575. Can  you please check?

**Comment by jywarren** [comment]
Thanks!
