### ISSUE TITLE
SimpleCov over Coveralls

### ISSUE THREAD

**Issue by siaw23** [publiclab/plots2#5641]
Coveralls is reporting a test coverage of 91% which is wrong. SimpleCov on the other hand reports a coverage of 79.94% and shows the test coverage results right after the test. It also shows which parts of the codebase is not covered so we can cover it.

![Screenshot 2019-05-01 at 14 24 45](https://user-images.githubusercontent.com/4806407/57016914-eb0ea380-6c1c-11e9-84f3-1d7584727502.jpg)

I think for development, SimpleCov would be more beneficial to us in the mean time. I'm creating a PR for this to help with refactoring.

**Comment by jywarren** [comment]
This looks good! We have started using CodeCov in `image-sequencer`, do you
want to consider that too?
https://github.com/publiclab/image-sequencer/pull/1047#issuecomment-487310279

**Comment by jywarren** [comment]
Moving to CodeCov i think now! Thank you!
