### ISSUE TITLE
Liking/emoji response updates for Bootstrap 4

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5647]
Just noting that in Bootstrap 4, the emoji response systems need a little styling help!

https://stable.publiclab.org/notes/warren/03-04-2019/testing-post#c17743

![image](https://user-images.githubusercontent.com/24359/57033248-6ae73e80-6c1a-11e9-8097-dba48ec169d6.png)

**Comment by scw248** [comment]
Hi @jywarren, could I give this one a try?

**Comment by scw248** [comment]
@jywarren actually, as I've played around with this, I realized this is a bit beyond me.  Thanks for posting, and best of luck!

**Comment by jywarren** [comment]
OK, thanks in any case! We'd be happy to have another contribution from
you, and if you'd like we can help you find one?

**Comment by dinaelhanan** [comment]
I'd be happy to take this one :)

**Comment by jywarren** [comment]
Awesome!!!!!!! Hi!!!!!

**Comment by dinaelhanan** [comment]
@jywarren hi! where would I find the code for this? thanks!

**Comment by jywarren** [comment]
I believe here:
https://github.com/publiclab/plots2/blob/master/app/views/notes/_comment.html.erb

It looks a bit complex! Perhaps @viditchitkara can help on this too?

**Comment by dinaelhanan** [comment]
@jywarren @ViditChitkara  that would be awesome!

**Comment by ViditChitkara** [comment]
I think the container of 'emojis' is at this line [here](https://github.com/publiclab/plots2/blob/f044a99f40baadf96ce9e334a42476ce8db71996/app/views/notes/_comment.html.erb#L79). I think the positioning of this div has to made relative to its parent div. Then you may want to set top and bottom property of this div accordingly.
[Here is a good article](https://css-tricks.com/absolute-relative-fixed-positioining-how-do-they-differ/) about positioning, you may want to have a look at. @dinaelhanan

**Comment by dinaelhanan** [comment]
@ViditChitkara I've made an attempt in the above PR, please check it out when you've got the time. Thanks!

**Comment by gauravano** [comment]
Hi @dinaelhanan, I just saw this issue and realized that I have attempted this issue at https://github.com/Souravirus/plots2/pull/1 and it was merged in big bootstrap PR too, but I guess somehow my changes were overwritten, so I have opened a new PR at https://github.com/publiclab/plots2/pull/5736 solving this. As you can see in the image at #5736, there is still scope for improvement in it like hovering over emoji is not scaling the emoji like it used to and the distance between the + button and emoji menu shouldn't be there. So, you can work on this. Sorry, I wasn't able to check earlier. Thanks!
