### ISSUE TITLE
Sidebar now missing on dashboard

### ISSUE THREAD

**Issue by publiclab-mimi** [publiclab/plots2#5670]
<img width="1192" alt="Screen Shot 2019-05-07 at 8 20 54 AM" src="https://user-images.githubusercontent.com/48802639/57302731-76ff5000-70a1-11e9-8bf8-eb2950ae8efe.png">

Logged on this morning and noticed that the sidebar that's usually there to encourage me to write a post/ask a question/like us on facebook is missing. I've noticed this in both safari and chrome. it doesn't appear whether I am logged into the website or not. I didn't notice this yesterday, so I'm wondering if something new went live last night?

This bar is still there on other pages, you can see it on the spectrometry page.

<img width="1157" alt="Screen Shot 2019-05-07 at 8 25 04 AM" src="https://user-images.githubusercontent.com/48802639/57302826-ac0ba280-70a1-11e9-917e-be38dfbd9fca.png">

**Comment by jywarren** [comment]
Hi, Mimi - i think it somehow got pushed to the bottom:

![image](https://user-images.githubusercontent.com/24359/57306587-1841d280-70b1-11e9-82c9-7fee4310c293.png)


Thanks for catching it, i wonder if it somehow has to do with the lack of image for the blog post? I'll try adding one there to see.

**Comment by jywarren** [comment]
Looks like that did it! Thanks again for helping catch this!!!

![image](https://user-images.githubusercontent.com/24359/57309816-b8e6c100-70b6-11e9-8c0a-3e6d86c48dac.png)
