### ISSUE TITLE
new tags page cards need updating to Bootstrap 4

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5675]
Hi, @divyabaid16 -- in follow-up to https://github.com/publiclab/plots2/pull/5384, i notice the new Bootstrap 4 project broke your work, i'm sorry!

![image](https://user-images.githubusercontent.com/24359/57317546-55648f80-70c6-11e9-80b4-957da1d39704.png)

I think it should be a minor fix. Would you mind giving it a try using the docs at http://getbootstrap.com to see the new card CSS? 

Thank you!

**Comment by jywarren** [comment]
https://stable.publiclab.org/tags

**Comment by jywarren** [comment]
awesome!!!

**Comment by CleverFool77** [comment]
Hi @divyabaid16 
Are you still working on this Issue. If not, I would like to add this to summer tasks as me and gautami are working on design and updates.

**Comment by divyabaid16** [comment]
Okay you may add this :)

**Comment by CleverFool77** [comment]
I'll take this one then.
Thanks !!
cc : @gautmig54

**Comment by gautamig54** [comment]
@CleverFool77 I see you have fixed the cards here. Great work!
Any other help needed here?

**Comment by CleverFool77** [comment]
This one is done. But I need bit of help in one of the PR where I have added `needs help` label on it.

**Comment by gautamig54** [comment]
Oh great! I see that the active map is not been highlighted(the labels under the graph). I'll fix that.
