### ISSUE TITLE
/inline-maps page showing some errors

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5678]
https://publiclab.org/wiki/inline-maps seems to be stalling and erroring a bit, and I know @sagarpreet-chadha has worked on this before, so I feel bad bringing it up again, but there are some 

I see a few things going on which I think is what makes this so complicated.

1. This is inconsistent, but I'm seeing a lot of the maps on that page greyed out, as if they're stalling while loading
2. Oddly, when I changed the width of the page, some more markers showed up
3. The ones further down are really stuck (see screenshots below)

Also, this error is shown on the page:

```
Uncaught TypeError: Cannot read property 'featureLayer' of undefined
    at wisconsinLayer (eval at <anonymous> (application-98ba6c8dece3e3db273f0b0692b8692bfdaa79300cf55d6636e3ed1f2f5aa3b1.js:350), 
```

I think this really may be multiple overlapping issues here! Maybe once we get it totally working, we should write a system test to protect this, since there's so much JS/Ruby integration going on here: #5316 

![image](https://user-images.githubusercontent.com/24359/57333182-4e4f7880-70ea-11e9-81b9-e88f00cb4abd.png)

![image](https://user-images.githubusercontent.com/24359/57333174-48f22e00-70ea-11e9-9f51-e93c485f3e7d.png)

**Comment by sagarpreet-chadha** [comment]
More details here : https://github.com/publiclab/plots2/issues/4722

I made a copy of this page as a `note` of the main `wiki` page here : https://publiclab.org/notes/sagarpreet/01-30-2019/inline-map-testing  and this note is working fine . 

I am investigating on why the same content is not working on the `wiki page` : https://publiclab.org/wiki/inline-maps . Most probably it is due to external JS code exclusively coded in /wiki . Thanks :)

**Comment by jywarren** [comment]
ok, awesome! Thanks so much, Sagarpreet!

**Comment by sagarpreet-chadha** [comment]
@jywarren ...i think i found the solution to this. 
Do look at the PR https://github.com/publiclab/plots2/pull/6699 . It is because of some function in `short-code-forms` lib.

**Comment by jywarren** [comment]
Let's double check in production once this publishes!

**Comment by sagarpreet-chadha** [comment]
Yes, you are depolying now?

**Comment by jywarren** [comment]
I'm trying to fix this first:
https://github.com/publiclab/plots2/pull/6581/ but
either tonight or tomorrow i hope!

**Comment by jywarren** [comment]
OK, so the maps on this page all now load properly! https://publiclab.org/wiki/inline-maps

But, the markers for each type do not. Looks like a nested bug maybe... @sagarpreet-chadha are you able to take a look at why?

**Comment by jywarren** [comment]
Aha! I'm seeing that maybe there is an initial event trigger that needs to be set up, and that possibly this only fetches markers upon interacting with the map? Not 100% sure, but that seems to work here:

https://publiclab.org/wiki/sandbox-3

when you pan or zoom it loads markers!

**Comment by jywarren** [comment]
![image](https://user-images.githubusercontent.com/24359/69077997-ee288000-0a04-11ea-8c44-e63398f02b9e.png)

**Comment by sagarpreet-chadha** [comment]
Hey @jywarren ,

In all the API calls, 

`tag | question:infragram` is getting added in request URL. Sending a patch for this now.

**Comment by jywarren** [comment]
Wow, so fast! Awesome.

**Comment by sagarpreet-chadha** [comment]
Solved in this PR: https://github.com/publiclab/plots2/pull/6802 . The trick is to use unique variable names everywhere, i will remember this 😄 !!! Otherwise hard to find this bug if one has no context!

**Comment by jywarren** [comment]
Awesome!!!

**Comment by jywarren** [comment]
Nice - fixed and live! https://publiclab.org/wiki/inline-maps

**Comment by sagarpreet-chadha** [comment]
Yes just saw, glad we fixed this :)
Should i add the new LEL inline syntax to this page or make a seperate
wiki? Thanks!

**Comment by jywarren** [comment]
Let's add it here! Good idea.
