### ISSUE TITLE
Reduce redundancy in inline grids file

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5679]
This file is very well tested, but has LOTS of redundancy:

https://github.com/publiclab/plots2/blob/master/app/models/concerns/node_shared.rb

CodeClimate gives a great overview of the level of code duplication here:

https://codeclimate.com/github/publiclab/plots2/app/models/concerns/node_shared.rb

Here you can see that we have tests covering all but the `notes_thumbnail_grid` code, which should give us good confidence in it being OK to rearrange things as long as they pass tests. We can hold off on the thumbnail code until we have a test for that, or we can test it manually:

https://coveralls.io/builds/23246122/source?filename=../models/concerns/node_shared.rb

**Comment by emctackett** [comment]
I would like to try working on this if that's alright. :smile:

**Comment by jywarren** [comment]
Oh please! That would be great!!
