### ISSUE TITLE
Integrate a Prompt button into inline maps

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5680]
Some of our inline grids, like `[activities:________]` generate a "prompt" button to add another node with these tags (docs at https://publiclab.org/wiki/power-tags#Inline+power+tags):

![image](https://user-images.githubusercontent.com/24359/57337505-93c67280-70f7-11e9-85ee-1ce1d0f190e7.png)

That's driven from this function: https://github.com/publiclab/plots2/blob/master/app/models/concerns/node_shared.rb#L190-L221

It'd be great to add a "prompt" button to inline maps (https://publiclab.org/inline-maps) as well, because right now you just see the map itself:

![image](https://user-images.githubusercontent.com/24359/57337526-ba84a900-70f7-11e9-82e7-19bc9dbf8e39.png)

But we could imagine a button beneath it using the tags from this map, and the coordinates as well, but letting you adjust a bit:

![image](https://user-images.githubusercontent.com/24359/57337526-ba84a900-70f7-11e9-82e7-19bc9dbf8e39.png)
![image](https://user-images.githubusercontent.com/24359/57337582-fa4b9080-70f7-11e9-8dd5-7ac1b9e2c458.png)

This would be a great addition to our geographic features. Ideally it'd open a prompt like:

https://publiclab.org/post?lat=-80&lon=44

Which would catch and display that location in the posting form (this doesn't currently happen):

![image](https://user-images.githubusercontent.com/24359/57337616-2b2bc580-70f8-11e9-9de5-7fdf053d5afb.png)

@sagarpreet-chadha -- what do you think of this?

**Comment by eplata31** [comment]
Can I start working on this?

**Comment by jywarren** [comment]
oh, that would be great! It's a little complex but I'm happy to help out!

**Comment by eplata31** [comment]
cool! I will contact you if I get stuck. Thanks!

**Comment by eplata31** [comment]
Hi guys! I'm sorry but due to college and some other projects I'm not having as much time as I would like to dedicate to this problem :( so if anyone wants to take on this please go ahead. I will try to provide help later on.

**Comment by jywarren** [comment]
Thanks! This was completed in #6699 i believe!
