### ISSUE TITLE
Change subscribe button in dashboard to hover instead of popover

### ISSUE THREAD

**Issue by aSquare14** [publiclab/plots2#5691]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem

On the [dashboard](https://publiclab.org/dashboard) there is a subscribe button. On clicking on it a menu/modal appears. This modal can only be closed if you click on the subscribe button again. An improvement would be to only show the modal when the mouse in on the subscribe button. 

### 📋Solution

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**
 Go to `_subscribe_button.html.erb`
Add this `  trigger : 'hover',` to change popover property to hover. Add it below `bottom` in the code snippet below.
`  $('#popover_button').popover({
  	content: $('#mypopcontent').clone().removeClass('d-none'),
         placement: 'bottom',
         ADD code HERE
         html: true
  });`

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by jesus-montano** [comment]
can I check this issue?

**Comment by aSquare14** [comment]
Sure. Go ahead.

**Comment by NrujalSharma** [comment]
hey is it still unsolved, I would like to give it a try.

**Comment by jesus-montano** [comment]
I did a pull request weeks ago but nobody answers me

**Comment by aSquare14** [comment]
@jesus-montano sorry. Sometimes PRs get missed due to high number of PRs. Please give me the link your PR !

**Comment by jesus-montano** [comment]
no problem!!!! this is the link 
https://github.com/publiclab/plots2/pull/5696
