### ISSUE TITLE
mapknitter map display should show lead images, not whole maps

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#570]
I know the RSS feed includes iframes of maps, but I think it may be too many to try to display in too small a space:

![screenshot 2016-06-07 at 12 27 53 pm](https://cloud.githubusercontent.com/assets/24359/15866117/5dc5c3ea-2cab-11e6-8678-0e58446e4a03.png)

I think rss feeds may offer a lead image, in the `<image>` tag, as in this feed: https://mapknitter.org/feeds/all

if so, can we show that? 

And/or, could we display a map of maps, as in https://mapknitter.org/archive ?

@ananyo2012 - are you very busy with your own project, or do you think you could try this, at least the main image one? Thanks!

**Comment by ananyo2012** [comment]
@jywarren No problem Jeff I will try to solve this issue asap.

**Comment by jywarren** [comment]
Thanks! Be sure to get a fresh copy of master. Much appreciated!!

**Comment by ananyo2012** [comment]
Solved in #575. Please review. The maps display now shows like this: 
![maps](https://cloud.githubusercontent.com/assets/10486343/15941669/e2529d00-2e9e-11e6-8bcd-28e3a5d52965.png)

**Comment by jywarren** [comment]
Great -- note that if you add `close #570` as part of your commit message, it will auto-close the mentioned issue when the commit is merged. For this one, can you manually close this once I merge tomorrow morning?

**Comment by ananyo2012** [comment]
Oh great info Jeff! Well I guess i don't have permissions to close this issue. Should i ammend the commit message?

**Comment by jywarren** [comment]
Ah, that's right -- but you can add that string to the body of the pull
request: https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by ananyo2012** [comment]
Coincidentally I have those special keywords in my PR. :smile:

**Comment by jywarren** [comment]
indeed! you do have to put "fixed " before each #, however, and i edited
yours to reflect this. Super!

**Comment by jywarren** [comment]
Thanks!
