### ISSUE TITLE
Content for Profile tags

### ISSUE THREAD

**Issue by lalithr95** [publiclab/plots2#571]
@steviepubliclab @ebarry I had completed tag system for basic tags such as role, skills, tools, gears. I'm currently working on Location based tagging system.

I would need a textual description of above tags to let PublicLab community users know the usage and idea behind the feature. 

PR which contains code #545 
Screenshot of the interface
<img src="https://cloud.githubusercontent.com/assets/24359/15865962/d9bff99e-2caa-11e6-827b-a73af5d972b0.png">
<img src="https://cloud.githubusercontent.com/assets/24359/15865961/d9bfe68e-2caa-11e6-858f-a9f7b8f6a6c4.png">

Let me know your feedback and improvements for location tagging system.
Thanks !

**Comment by ebarry** [comment]
Hi Lalithr95!
@steviepubliclab and I really enjoyed testing out your profile power tagging feature! 

@jywarren, @steviepubliclab and i are looking ahead to the design of the profile page, and thinking how to prompt people to fill out the information -- wondering, is there the option to move the powertagging display to the center of the profile, or does it have to stay in the sidebar? 

Generally, Stevie and I are thinking to deemphasize the public display of Roles. 
Perhaps only moderator and organizer get shown publicly. 
We do not want to show Admin publicly -- there's not need as "contact web@publiclab.org" is shown so prominently on very page of the website in the footer. 

We can't find the past correspondence when Gear and Tools became separate things -- we're not sure what the difference is. 

While we're thinking in terms of the prompt text that encourages people to fill this out, can we expect that autocomplete will be working, and/or can we curate a set of values to be suggested?

**Comment by jywarren** [comment]
Merging into new geographic features!
