### ISSUE TITLE
Public lab as an example of a community that uses the Searchable Linkable Open Public Indexed (SLOPI) communication style

### ISSUE THREAD

**Issue by pdurbin** [publiclab/plots2#5722]
Hello! I'm following up on a conversation I just had with @jywarren at https://gitter.im/publiclab/publiclab?at=5cdb3667e7f42160fa8cb9c0

I'll repeat it here for context. :smile: 

pdurbin	If you're waiting, is now a good time for me to explain my crazy idea? :)

jywarren	sure, but i may be pulled away, just warning!

pdurbin	Cool. Just tell me to stop and I can pick up later. Have you heard of FAIR data?

jywarren	no!

pdurbin	From the wikipedia page: "FAIR data are data which meet standards of findability, accessibility, interoperability, and reusability."

pdurbin	FAIR comes up a lot in my world. And it's funny, it's a new term, minted only a couple years ago. It's really taken off. People tweet about it. FAIR is a thing. In my world anyway.

jywarren	hmm

jywarren	haven't heard of it, but interesting!

pdurbin	And I've been thinking about a concept for a while, a communication style used by Public Lab and that I use myself in open source projects I'm involved in. But it doesn't have a name. So I came up with one the other day. :)

pdurbin	Searchable Linkable Open Public Indexed (SLOPI) Communication. Pronounced "sloppy". What do you think? :)

jywarren	whoa, like unpack that for me?

pdurbin	Searchable: Messages can be found using Google or other search engines.

jywarren	like, how we research and document, or more like to do with our friendliness?

pdurbin	Linkable: Messages have a permalink on the web.

pdurbin	Open: Messages are in the open.

jywarren	hmm!

pdurbin	Public: Messages are public.

pdurbin	Indexed: Messages are indexed by search engines.

jywarren	like, letting it all hang out, as a form of transparency?

pdurbin	Yes, exactly.

jywarren	cool!

jywarren	Liz would love this

pdurbin	While open source projects should endeavor to communicate in the SLOPI style whenever possible, this style is inappropriate for security, code of conduct violations, and telling co-workers on your floor that you brought in donuts.

I thought I'd create this issue to now that I have the idea out there. I've already added Public Lab to a spreadsheet I just started that's linked from this issue:

- https://github.com/pdurbin/slopi-communication/issues/2

Here are the SLOPI communication channels listed in the spreadsheet for Public Lab. I am **not** trying to imply that open source projects should have 17 different channels for communication. I'm mostly just trying to recognize that project use different tools. Also, I'm not sure where I'm going with terms like "SLOPI QA" or "SLOPI UI/UX". Maybe you can help me define these a bit. :smile: 

- SLOPI Mailing List: https://groups.google.com/forum/#!forum/publiclaboratory
- SLOPI Forum: https://publiclab.org/questions
- SLOPI Chat: https://gitter.im/publiclab/publiclab
- SLOPI Issue Tracker (one of many): https://github.com/publiclab/plots2/issues
- SLOPI Kanban: https://github.com/publiclab/plots2/projects
- SLOPI Roadmap: ?
- SLOPI QA: ?
- SLOPI UI/UX: ?
- SLOPI Q&A: ?

I'd love to talk more with the Public Lab community about this idea of SLOPI communication for open source projects? Good idea? Terrible idea? Do you like being sloppy? :smile: Please comment below or please feel free to start a discussion at https://github.com/pdurbin/slopi-communication/issues ! Thanks!

**Comment by pdurbin** [comment]
LOL at @ebarry saying, "Wow things are getting SLOPI around here" -- https://gitter.im/publiclab/publiclab?at=5cdb61265d48a24fd0cc66fa :smile: :tada: 

I don't mean to nag anyone but does Public Lab have a roadmap? Does have a public Travis or Jenkins for QA/CI? Is there a list of what's going on with UI/UX this week or this month from designers or people who care about design? I think for Q&A Public Labs uses https://publiclab.org/questions and I'm trying not to double count the same URL for different channels. I see that "questions" area as a forum, primarily. :smile:

**Comment by pdurbin** [comment]
Over at https://gitter.im/publiclab/publiclab/archives/2019/05/15?at=5cdcaba756271260f96b34d4 I learned from @skilfullycurled about Public Lab's use of Sentry. It looks like Sentry was added in pull request #4944 to address this issue: Tracking errors in production #4903

I'm still on the fence about whether my spreadsheet should be about open source projects or communities. Public Lab is both. Also, as far as I know https://publiclab.org is the only production installation of plots2. Without being able to see what Sentry is showing it's hard for me to judge if there's any value in making some of it public. What would probably be more valuable to users of https://publiclab.org is some sort of status page like https://www.githubstatus.com . Users probably don't care about the low level details of how many 500 errors there have been in the last hour. With a status page, they could know if the site is down or degraded. This might be a new communication channel, "SLOPI Status Page" or something. From a quick issue search I don't believe Public Lab is using something like https://github.com/CachetHQ/Cachet and I'm not sure if this is of interest or not. Obviously, if there are multiple installations of plots2, each installation could decide if they want to show their users a status page or not. It's a form of communication.

**Comment by pdurbin** [comment]
> Perhaps I should add a new communication channel to my spreadsheet, a column called "SLOPI Status Page" or something. From a quick issue search I don't believe Public Lab is using something like https://github.com/CachetHQ/Cachet and I'm not sure if this is of interest or not.

I just noticed "check if the site is running slowly" in the Public Lab footer. It looks like this...

<img width="641" alt="Screen Shot 2019-05-19 at 9 41 01 AM" src="https://user-images.githubusercontent.com/21006/57982962-43fe7a00-7a1a-11e9-9683-c9425da58125.png">

... and links to https://oss.skylight.io/app/applications/GZDPChmcfm1Q/recent/6h/endpoints which looks like this:

<img width="1141" alt="Screen Shot 2019-05-19 at 9 42 30 AM" src="https://user-images.githubusercontent.com/21006/57982975-70b29180-7a1a-11e9-945e-599e1f37e5f0.png">

So I did go ahead and add another column to my spreadsheet called "SLOPI Status Page" and added the skylight link for Public Lab. Judging from pull request #2773 and issue #2660 this was thought of more as "performance tracking" than a status page but it certainly works as a status page and communicates a lot.

Public Lab is extremely interesting to me to study but it's very different that Nextcloud, for example, which is also on my list. Public Lab is an open source project and a live running service all at once. Nextcloud is software that you install on your own server. It would be up to each installation of Nextcloud to set up a status page, if they felt like it. I'll keep thinking about if I want to focus more on the software+service combo or just software. Inkscape is also on my spreadsheet and clearly there's no service component to Inkscape since it's a drawing program that runs on your desktop. The only status page that Inkscape might use (I haven't looked) would be for their developers to make sure their build system is up or whatever other cloud resources they use (stuff developers care about, not users).

**Comment by pdurbin** [comment]
Nice! @jywarren just posted a roadmap: https://publiclab.org/notes/warren/05-22-2019/draft-of-a-public-lab-software-roadmap-comments-welcome ! I'm going to go add it to my spreadsheet, the one linked from https://github.com/good-labs/slopi-communication/issues/2

**Comment by pdurbin** [comment]
> I've already added Public Lab to a spreadsheet I just started that's linked from this issue:
>  - https://github.com/pdurbin/slopi-communication/issues/2

Years later, Public Lab is winning with transparency game, though Inkscape and Jupyter are close contenders. 😄 

I'm closing this. Thanks for helping me find all the links for [that spreadsheet](https://docs.google.com/spreadsheets/d/1wvG3XTd5YwA-SliOUCavQgqfK1jLVnlL9tuUsjHR0Ik/edit?usp=sharing), @jywarren and @ebarry!

**Comment by ebarry** [comment]
Thanks Phil! You're a star ✨
