### ISSUE TITLE
Comment stats counting spam comments?

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5726]
I don't believe comment stats count spam, but looking at this line in the range action I'm not sure, @cesswairimu  maybe we should take a look? 

https://github.com/publiclab/plots2/blob/b8011954823c2e76cd53e2113353c5dcd5bd46cc/app/controllers/stats_controller.rb#L28

Also this line?

https://github.com/publiclab/plots2/blob/b8011954823c2e76cd53e2113353c5dcd5bd46cc/app/models/comment.rb#L44-L47

Should we put status=1 in all these lines?

**Comment by jywarren** [comment]
I think the addition would be, in both places, `.where(status: 1)`

We may want to follow-up with notes, wikis too.

**Comment by jywarren** [comment]
Ah, and we'd have to add the "status" field to the select as well, so `.select("timestamp, status")`

**Comment by cesswairimu** [comment]
Yeah would be worth checking, doing that now. Thanks Jeff

**Comment by cesswairimu** [comment]
For notes we have this `published` scope that we use to filter the status of 1 https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L102, https://github.com/publiclab/plots2/blob/master/app/controllers/stats_controller.rb#L18...yeah would be great to add the same for comments and wikis. Adding those nowThanks Jeff

**Comment by skilfullycurled** [comment]
Oh, just read @jywarren's note in the chat.  @cesswairimu, seems like this is taken care of now or do you need someone to work on it?

**Comment by cesswairimu** [comment]
@skilfullycurled yes I opened a PR, not sure if that will reduce all the spam comments, but it might reduce them a bit. Will ping you if something comes up. Thanks
