### ISSUE TITLE
Uploading main image on wiki pages is not working

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5732]
In follow-up to https://github.com/publiclab/plots2/issues/5650, uploading an image to a wiki page as the "main" image is causing a JS error:

```
dragdrop-84e1d3ce154c3ef9f814bf663f9b0533b654e25c0f18834d1d2eb87aa8487688.js:207 Uncaught TypeError: Cannot set property 'src' of undefined
    at HTMLDivElement.done (dragdrop-84e1d3ce154c3ef9f814bf663f9b0533b654e25c0f18834d1d2eb87aa8487688.js:207)
```

In this "drop zone":

![image](https://user-images.githubusercontent.com/24359/57890305-4a67d880-7805-11e9-8c50-a8dd8281ecc8.png)

This seems VERY similar to the fix for #5650; the error is on this line: 

```js
          ($D.selected).find('#leadImage')[0].src = data.result.url;
```

That's odd, though, this fix should've worked for any page with `wiki` in the URL: 

https://github.com/publiclab/plots2/pull/5703/files

**Comment by jywarren** [comment]
Hi @ViditChitkara would you be able to look at this to see if it also relates to the comment upload code change? I think we've fixed this almost everywhere, but this is still causing issues... thank you!

**Comment by ViditChitkara** [comment]
Hi @jywarren , I'll have a look at it.
