### ISSUE TITLE
UI Improvements PLanning Issue : Questions Page

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5733]
cc : @gautamig54 

![PublicLab_mockups](https://user-images.githubusercontent.com/26685258/57947963-f8ef4480-78fd-11e9-9724-a30711ca27ae.jpg)

#### Checklists

- [x] Create shadow questions page @CleverFool77 
- [x] first design block with some relevant information @CleverFool77 
- [x] card of text area for questions with buttons and post options @gautamig54 
- [x] featured questions cards   @CleverFool77 
- [ ] Show recent questions on some topic - use same card as used in tags section @gautamig54 

Viewable at:

http://stable.publiclab.org/shadow_question

http://publiclab.org/shadow_question

**Comment by CleverFool77** [comment]
Hi @jywarren @gautamig54 
Is division of checklists for questions section correct ?

**Comment by CleverFool77** [comment]
Hi @gautamig54 I'll start off with assignment.

**Comment by gauravano** [comment]
Great start here!! I can see some planning issues for your project. Is there any central planning issue where links to all the sub-planning issues can be found or we can discuss general project direction, goal priority, etc? Thanks!

**Comment by gautamig54** [comment]
@CleverFool77 division of work is perfect. Let's get started on with it!

**Comment by gautamig54** [comment]
@gauravano We can refer to #4922 as central planning issue.
Should I reopen it or make a new one?
Thanks!

**Comment by gauravano** [comment]
please open a new one. You can copy the goals from #4922 . Thanks!

**Comment by CleverFool77** [comment]
Hi @jywarren @gauravano 
As most of the portions in Design issues are dependent. So I'm taking two issues sideways. As some parts or portions of some issues are dependent on each other and it might make us to stop for a while as we are unable to move further. 
I just opened one PR for beginning the work for People section #5740 . And till it would get reviewed and merged. I wanted to begin the work in Questions Page.

So mainly, I wanted to ask that What's the purpose of image and info in First section. 
![Screenshot from 2019-05-19 18-47-05](https://user-images.githubusercontent.com/26685258/57982700-83eb4e80-7a66-11e9-88cd-fab6939087bc.png)

So That I can start off with work.
Thanks !!!

**Comment by CleverFool77** [comment]
HI @jywarren @gauravano 
I wanted to ask that Is first section of questions page not available in plots2 code ?

![Screenshot from 2019-05-19 19-17-26](https://user-images.githubusercontent.com/26685258/57983036-c31b9e80-7a6a-11e9-9f5b-4c0192ba363c.png)

**Comment by gauravano** [comment]
> As most of the portions in Design issues are dependent. So I'm taking two issues sideways. As some parts or portions of some issues are dependent on each other and it might make us to stop for a while as we are unable to move further.
I just opened one PR for beginning the work for People section #5740 . And till it would get reviewed and merged. I wanted to begin the work in Questions Page.

Sounds great!

I think the image tagged by you at https://github.com/publiclab/plots2/issues/5733#issuecomment-493756709 is kind of example of what a question looks like or it's more like representing that one can ask questions and collaborate. (Let's wait for @jywarren on this, we don't want to start with some many /like/ :smile: ). Also, I think, we can also add GIF showing typing a question and posting it, instead of an empty textbox?   

> I wanted to ask that Is first section of questions page not available in plots2 code?

@CleverFool77 it's a feature. I can give you code for that but wait, the new design is different. I think we can use the feature for the static part as we have now. In that case, you can create the feature locally and can give us code in a gist. But, again, let's confirm from @jywarren about the content part and whether it would be fine to have feature for that? 

Thanks!!

**Comment by CleverFool77** [comment]
Hi @gauravano According to new design , we can have it to not have as a feature. What do you say. Let's wait @jywarren's view.
Regarding gif feature of showing typing and posting process. You mean in first section ?

**Comment by gautamig54** [comment]
@CleverFool77 I think, the description is the latest question asked by the logged in user and the link to the responds. The image is the profile image of the user. It is a valid feature. If a user hasn't asked any questions, we can show as no question asked in the description.

**Comment by CleverFool77** [comment]
Ohh I thought the description is information based of community building like You Ask a questions here and etc.
First, I did thought it's profile picture but now I'm thinking what would be use putting of profile picture here.
So I wanted to someone to clear doubt.
Thanks !!!

**Comment by gauravano** [comment]
> Ohh I thought the description is information based of community building like You can Ask questions here and etc.

Same thought. Let's wait for @jywarren.

**Comment by jywarren** [comment]
Hi all! Let's do everything above the "What's your question" form as a feature, so it can be tweaked. We'll assume the speech bubble and profile image is a static image for now (can work on this later, and we'd love help making that, but it can be prototyped and saved in a Gist for copying into the Features system).

The form below should actually be a questions form. But we can look to the one at /questions/new, and as a model. However we made this one much simpler, so let's aim for simplicity!

Thanks, all!

**Comment by CleverFool77** [comment]
Hi @jywarren 
Regarding first section, I'll write the code and share it in the link of gist here.
So the first section would have a static image and some information like `Ask the community` in right side of it. What would be there after clicking the Learn more link ? Should it be linked to wiki ?
Thanks !!!!

**Comment by gautamig54** [comment]
@CleverFool77 There is a wiki regarding Q and A (https://publiclab.org/wiki/public-lab-q-and-a). You can link "learn more" to that.
Thanks!

**Comment by gautamig54** [comment]
I am starting with the questions input form and I had a few doubts. 
The "Next" option will link to the questions editor like the "continue" in the present ui?
and what are the other options here?
Thanks!

**Comment by jywarren** [comment]
I think ideally, "next" might just post it? What do you think?

**Comment by CleverFool77** [comment]
Is first section should be something like this ? 
Image attached below
![Screenshot from 2019-05-22 14-18-58](https://user-images.githubusercontent.com/26685258/58160776-bda59a80-7c9c-11e9-96b4-a08f0f12a851.png)
Thanks !!

**Comment by jywarren** [comment]
Ooh! Looks good! Are we going to try developing this at a "shadow" page
while all the pieces come together? Like /questions2 ? Then once it's
complete, copy it over the original? What do you think?

Thanks a lot, this is awesome!!!

**Comment by gauravano** [comment]
Yes, shadow page would be great :smile:. We will surprise users once it's ready :sweat_smile:

**Comment by CleverFool77** [comment]
Hi @jywarren @gauravano @gautamig54 
We'll proceed with shadow page from now onwards.
I want to ask, that as the first section is feature. So sharing it on gist would be enough. Or there is need to do further changes.

**Comment by gauravano** [comment]
You can test whether the feature is compatible with the rest of the page by testing on stable.publiclab.org. As creating a feature requires admin access to the website, so if you're cool with testing on stable, @jywarren can make you admin at stable.publiclab.org? 
Also, just to remind, stable.publiclab.org builds from `master` branch.
Thanks!

**Comment by gautamig54** [comment]
@jywarren Currently, we have a "continue" button which directs the user to the question's editor. It not only takes the questions but also its description and the tags. So how can we use the "next" button directly for posting a question?
One thing we can do is adding columns for question description and tags on the same page itself, without directing to the editor. 
What do you think?

**Comment by gautamig54** [comment]
@CleverFool77 The design looks great. Since we will be working on the shadow page, we can add the code to the shadow page itself, even if its a static feature. What say?

**Comment by jywarren** [comment]
Ah, ok, so for now let's redirect to the full questions form. we may try to
think through another flow later. I think tagging is not central as new
users may need help tagging after publishing anyways, but you're right we
have to think of the "title" vs. "body" of the question. So, either we'll
have to add a title zone to the front /questions page, or perhaps we could
ask people to "sum up your question in a short sentence" which becomes the
title. Let's do the simple redirect for now, but I'd love to hear your
thoughts on the flow of the questions sequence if we did something more
sophisticated?

**Comment by CleverFool77** [comment]
Hi @jywarren Should we do something like this ? Dividing text area ? 
![Screenshot from 2019-05-27 21-57-18](https://user-images.githubusercontent.com/26685258/58431228-79663000-80ca-11e9-8383-a65a2bc4d9f8.png)


This is followed by quora. 
Though I'm not too sure about this. 
Either we can do this, or in else in a simplest way. Redirect looks like good option.

**Comment by gautamig54** [comment]
Let's redirect to the question's form for now. But I think, it will be feasible to have title and description separately on the /questions page and submit the question from here itself, without needing to go to the questions form.

**Comment by gautamig54** [comment]
Great! #5787 is merged. I am getting started with the question's title area.
Great work @CleverFool77!!!

**Comment by CleverFool77** [comment]
> Great! #5787 is merged. I am getting started with the question's title area.
> Great work @CleverFool77!!!

Sure @gautamig54 :smile:

**Comment by gautamig54** [comment]
How is this? Should I add blue margin to the text area?

![Screen Shot 2019-05-30 at 2 58 31 AM](https://user-images.githubusercontent.com/35326753/58592631-80d23880-8286-11e9-974d-4f94ddf88c02.png)

**Comment by jywarren** [comment]
Hm, well, let's go with whatever bootstrap defaults use. Maybe the "What's
your question?" title could be one size larger, so h2 if it was h3, or h3
if it was h4?

Looking really nice!

**Comment by gautamig54** [comment]
Thanks @jywarren!
I'll make the changes.

**Comment by gautamig54** [comment]
I have a doubt for the further implementation of this page. 
In the featured questions section, we are initially displaying just the two of them(mostly top two). But there are a lot of featured questions. How are we going to display the rest of them?
One thing that can be done is directing to a separate page which has all the featured questions which needs to be created and designed as we currently do not have it.
How do we proceed @jywarren @gauravano ??

**Comment by CleverFool77** [comment]
> I have a doubt for the further implementation of this page.
> In the featured questions section, we are initially displaying just the two of them(mostly top two). But there are a lot of featured questions. How are we going to display the rest of them?
> One thing that can be done is directing to a separate page which has all the featured questions which needs to be created and designed as we currently do not have it.
> How do we proceed @jywarren @gauravano ??

Hi @jywarren I have been wondering the same thing that what would be considered main distinction to get these two feature questions ?

**Comment by gauravano** [comment]
Having a separate page for featured questions is a nice idea. Let's ask @publiclab/community-reps about the need of such page? The top two featured questions can be the most recent one's like we do for the blog. Thanks!

**Comment by CleverFool77** [comment]
Hi @jywarren I was working on th features questions section fr questions page. So I wanted to ask that Is **`popular` _questions tab_** in questions page right now is the **`future features questions`** section for **`shadow_question` page** ? Or is it something else ?

**Comment by gautamig54** [comment]
Yes @CleverFool77. For now we can refer featured questions as the present popular questions. Meanwhile, I will start working for the recent questions and the tags section.

**Comment by jywarren** [comment]
I think featured questions could be managed through a tag like `featured` which is added. So then we could show just 2-3 on this page, then have a link to "more featured questions" which goes to, for example, https://publiclab.org/questions/tag/featured

How does this sound? 

We are looking to be able to highlight really good questions that are especially representative of environmental issues, and so far, "popular" hasn't been a perfect metric to bring those kinds forward. So we thought of a manually curated set as a way to improve what is shown. Does this make sense? Thank you!

**Comment by jywarren** [comment]
So, the curators (like @publiclab/community-reps) would look for questions that are clearly phrased, address an environmental issue, and maybe that have been really well answered, so as to model for the community what it looks like also to get good answers. These examples would help to shape participation on the site by modeling our ideal interactions!

**Comment by CleverFool77** [comment]
Hi @jywarren @gautamig54 
I was working on the features question section. I wanted to know that what's the info being shown below the question in the cards ?

**Comment by gautamig54** [comment]
@jywarren Can you share a gist of "featured questions" features? We have to add it next. Thanks!

**Comment by jywarren** [comment]
Ah, can you post a screenshot of just the section you're talking about? I just want to be sure i'm following correctly. Thank you!!!

**Comment by gautamig54** [comment]
Featured tags in the questions page

![Screen Shot 2019-06-17 at 11 31 11 PM](https://user-images.githubusercontent.com/35326753/59625709-9df87980-9157-11e9-8886-eb554ae3e0dc.png)

**Comment by jywarren** [comment]
Looking great! note we have been showing these in badges in other places.
This is really coming together though!

**Comment by gautamig54** [comment]
@jywarren I have raised a PR for the recent questions section #5912 . After this only featured topics sections will be left and then the page will be complete. Hurray!!
