### ISSUE TITLE
Validation Error Email already taken

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#5734]
**Query**
I'm trying on GitHub with the right env keys now, and it did lead me through the GitHub OAuth approval, which was great. But I got this error:

```
App 22225 output: Validation failed: Email has already been taken
```

So, we should display that, i think?

**Query Resolved**
 it was really tough this time. It took 2 days to resolve validation query. 
![image](https://user-images.githubusercontent.com/20972099/57954036-6e174580-790f-11e9-830b-3edc73005b0b.png)

Try the following. 
1. Login with SWB with PL any provider with help of localhost connected in user_session_controller
2. Login with SWB with PL any provider with help of publiclab connected in user_session_controller
You will be logged in atmost one time. Identity url can take either production or dev url which creates the problem and shows 2 Emails can't be taken.

**Comment by SidharthBansal** [comment]
One solution is to change identity_url to array type which is not possible.
Other solution(which will give you pain many times) is to delete all the users from MK and SWB which have identity_urls with `localhost:` instead of `https://publiclab.org`.

**Comment by SidharthBansal** [comment]
For a normal user(who never uses localhost), this issue is trivial. This issue is one of the corner/ edge case where the person is both user and developer. Then only they will have two identity urls for same PL account.(localhost:3000/openid/bansal.. and publiclab.org/openid/bansal...).

Let's assume, I am a developer not playing with the login systems of PL, SWB and MK then this corner case will not arise ever. 
Reason : user_session_controllers have ``https:publiclab.org/people`` so identity url for both production and dev env will always be set to `publiclab.org/openid/bansal..`
![image](https://user-images.githubusercontent.com/20972099/57955421-8b4e1300-7913-11e9-9d12-962a2123640f.png)

**Comment by SidharthBansal** [comment]
The rarest species(you, me and may be 2-3 in future who will play with login systems) let's discuss this in detail Jeff.

Consider production env, MK and SWB will always have 
![image](https://user-images.githubusercontent.com/20972099/57955566-e4b64200-7913-11e9-87fe-510332cf89da.png)
publiclab in the production. So, in the production database we will always store identity_url for the public lab. So it will not be a problem.

In case the production database is same as for unstable and for dev for any user(which I assume is wrong practice and is not present here) then we will be in inconsistent state and raise a new issue.

Similarly we don't need to worry for unstable branches, their dbs will store only identity_urls containing `publiclab`.

For the dev env, the rarest species can set two identity_urls which will ultimately lead to this error.
So, what should we do for them? One way is use rails console to do things manually which is the easiest step.  


I hope things make sense. These are too complicated things which are twisting a lot. In case of any ambiguity please do ping me.

**Comment by SidharthBansal** [comment]
Also, on further thinking, I came to know that 
> Other solution(which will give you pain many times) is to delete all the users from MK and SWB which have identity_urls with localhost: instead of https://publiclab.org.

This will not be needed. Only the rarest species have to do this kind of stuff on their own PC. No production involvement.

But it will be great if @jywarren you can check that we don't have any user with the identity_url containing `localhost:`. 
I bet we will never have such accounts in the production db.

**Comment by SidharthBansal** [comment]
@jywarren can we close this issue?

**Comment by jywarren** [comment]
Yep!
