### ISSUE TITLE
UI implementation project discussion and planning

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#5739]
This issue is regarding the planning and discussion for the UI improvement project for summer 2019. This will contain an overview of the project. 
The pages to focus on are : 
- [ ] Dashboard
- [x] People's page https://github.com/publiclab/plots2/issues/5707

![Screen Shot 2019-05-19 at 2 41 35 AM](https://user-images.githubusercontent.com/35326753/57975640-67113580-79ea-11e9-8831-7eec17144f9d.png)

- [x] Tag page #5675 

![Screen Shot 2019-05-19 at 4 02 32 AM](https://user-images.githubusercontent.com/35326753/57975660-bb1c1a00-79ea-11e9-98e9-c3eef9d0d3ab.png)

- [x] Individual Tags page

![Screen Shot 2019-05-19 at 4 01 34 AM](https://user-images.githubusercontent.com/35326753/57975663-c8390900-79ea-11e9-8514-bcaa74bf4683.png)

- [x] Questions page https://github.com/publiclab/plots2/issues/5733

![Screen Shot 2019-05-19 at 4 06 46 AM](https://user-images.githubusercontent.com/35326753/57975684-3f6e9d00-79eb-11e9-807a-87a958fbd123.png)

- [x] Profile page

![Screen Shot 2019-05-19 at 4 01 10 AM](https://user-images.githubusercontent.com/35326753/57975665-d129da80-79ea-11e9-9854-270edfee814c.png)

- [x] Search result page https://github.com/publiclab/plots2/issues/5708

![Screen Shot 2019-05-19 at 4 06 07 AM](https://user-images.githubusercontent.com/35326753/57975681-28c84600-79eb-11e9-8186-d2a7567a32fd.png)

- [x] tag/tag_name page 

![Screen Shot 2019-05-23 at 5 53 17 PM](https://user-images.githubusercontent.com/35326753/58252300-65959380-7d83-11e9-8f58-fd4050c71346.png)

Together with these pages, we will be working on other bootstrap fixes on the other pages as well.
cc : @CleverFool77

**Comment by gautamig54** [comment]
@jywarren @gauravano It is a general issue related to UI implementations. We will also be creating separate issues for each page and create a checklist there itself. 
@CleverFool77 Kindly add if I missed out something. 
Thanks!

**Comment by CleverFool77** [comment]
Hi @gautmig54
I just updated the people section and added some more checklists. 
I have started off the assignment. 
Could you look at it. 
Thanks.

**Comment by CleverFool77** [comment]
I'll link all the issues here. 
Thanks !

**Comment by gautamig54** [comment]
Also, can we add blogs page and editor in this project as well?
What do you think @CleverFool77 ??

**Comment by aSquare14** [comment]
@gautamig54  Great work with the issue ! Well-detailed. When you have the designs for dashboard ready link it here ! :)

**Comment by CleverFool77** [comment]
Just a bit, I guess there are still some changes going on in design of dashboard. 
But no worries. We'll add it eventually. 
But till then, we can add the latest design of dashboard yet.
How about that ?
Regarding blogs page and editor page. There are still some people working on them. maybe we should wait for while and if there is no progress, we can add it in our todos and complete it. 
Thanks !!!

**Comment by gautamig54** [comment]
@CleverFool77 Sounds great!!! 
@jywarren can add the design of the dashboard once it is ready.
Thanks!

**Comment by jywarren** [comment]
Just noting - more soon here, sorry! but that the tag page is probably going to be much updated based on the style guide! There's a design at page 8 - what do you think?

https://docs.google.com/presentation/d/1-XHlVn3KQxSjS5WzHgc1l1qvFwqUC5f3-7GXugUP9u4/edit?ts=5cab5403#slide=id.g5926e39f86_0_189

![image](https://user-images.githubusercontent.com/24359/58138539-a4510f80-7c04-11e9-85d1-8d0de80ae42e.png)

It's not completely done, but if you'd like to try copying and refining it in the main Mockups page, that'd be awesome! https://docs.google.com/presentation/d/1TCZoTfuhamRVrUak8aDgqJAwSgyhRtZg2Pgacl2_4zc/edit#slide=id.g558b0e2e98_1_0

**Comment by jywarren** [comment]
And, I can't find it right now but I believe there's an issue open for updating the /tags page to Bootstrap 4 as well!

**Comment by CleverFool77** [comment]
> And, I can't find it right now but I believe there's an issue open for updating the /tags page to Bootstrap 4 as well!
 
https://github.com/publiclab/plots2/issues/5675 This one is tags page update issue.
I pinged the assignee, as soon as there is reply. The work will start on bootstrap upgrade.
After that we will work tags page based on above design.
Thanks !!!

**Comment by jywarren** [comment]
So rad, you folks! Thanks for getting organized!

**Comment by gautamig54** [comment]
I have updated this issue with the tag/tag_name page design. Thanks!

**Comment by jywarren** [comment]
Hi all! Your recent changes are live!!! They look great!!! 

https://publiclab.org/tags

https://publiclab.org/people

Stay tuned in the chatroom to hear when publications happen - great work!

**Comment by milaaraujo** [comment]
This looks good! The project is very well organized. 

I have not introduced myself yet, but my name is Camila! I was a participant in Rails Girls Summer of Code in 2018 and since then I have been a contributor to the project. I have worked mostly on the Search API (https://github.com/publiclab/plots2/projects/6 and https://github.com/publiclab/plots2/projects/8). And I will be Lekhika's co-mentor! :)

@CleverFool77, let me know when you need help with anything! And do not hesitate to mention me directly when you need reviews. I'm in Vancouver, so our timezones are very different! But I will do my best to answer as soon as possible.

**Comment by aSquare14** [comment]
I would also like to mentor this project. Any place for an additional
mentor? :)

**Comment by CleverFool77** [comment]
> This looks good! The project is very well organized.
> 
> I have not introduced myself yet, but my name is Camila! I was a participant in Rails Girls Summer of Code in 2018 and since then I have been a contributor to the project. I have worked mostly on the Search API (https://github.com/publiclab/plots2/projects/6 and https://github.com/publiclab/plots2/projects/8). And I will be Lekhika's co-mentor! :)
> 
> @CleverFool77, let me know when you need help with anything! And do not hesitate to mention me directly when you need reviews. I'm in Vancouver, so our timezones are very different! But I will do my best to answer as soon as possible.

Hey, Nice to meet you. 
This is Lekhika @CleverFool77 
I would be glad for your help here.

Here is the link of project . I have added some stuff and tried to make it more organised. 
https://github.com/publiclab/plots2/projects/10
The project feature of GitHub shows the progress of project very well.
Thanks !!!

**Comment by jywarren** [comment]
Hi all! Is there an updated place to list out some refinements and goals for the /tags page? It's looking tremendous. I see a few formatting tweaks perhaps to the way author images are shown: 

![image](https://user-images.githubusercontent.com/24359/58341673-c2915800-7e1c-11e9-9f82-c5b3feb63663.png)

And I know @ebarry has suggested that we hide (by default) topics that include `:` because these are mostly for utility purposes. Maybe we should show them only if we have a parameter set like `params[:all] == true` ? And then at some point we can add a `...` menu to contain more advanced features like this, that would point at `https://publiclab.org/tags?all=true` -- what do you think?

**Comment by jywarren** [comment]
Hi all! Just noting that the individual tag pages are starting to get a bit... extra broken 😂 

https://publiclab.org/tag/pi-camera

![image](https://user-images.githubusercontent.com/24359/58895669-766ad100-86c2-11e9-9535-39085113d3a5.png)

Maybe it's worth bumping up the priority of that project a little bit, or at least implementing a short term fix?

**Comment by CleverFool77** [comment]
Hi @jywarren How about doing the short term fix first for now ?

**Comment by jywarren** [comment]
That sounds great. Thanks Lekhika!

**Comment by gautamig54** [comment]
I am working on this one!

**Comment by CleverFool77** [comment]
In the features question, the picture is the profile picture of the person who asked the question ?

**Comment by CleverFool77** [comment]
> I am working on this one!

Did you mean short term fix ? Sure then.
thanks !!

**Comment by CleverFool77** [comment]
Hi @gautamig54 It would be great if you can add your work which is done or is in progress in project cards. It would help a lot in checking the work progress. And arrange or sort it with time. So that we can the latest one above.
Thanks !!

**Comment by CleverFool77** [comment]
> Hi @gautamig54 It would be great if you can add your work which is done or is in progress in project cards. It would help a lot in checking the work progress. And arrange or sort it with time. So that we can the latest one above.
> Thanks !!

No worries :3 I already added.

**Comment by CleverFool77** [comment]
Just made few arrangements in project for better categorisation of work.
https://github.com/publiclab/plots2/projects/10
Thanks !!

**Comment by gautamig54** [comment]
Hey, I was trying to upload an image to the tag wiki page to check the changes for this issue but wasn't successful. It shows a server error, saying "Could not run the `identify` command. Please install ImageMagick. excluded from capture: Not configured to send/capture in environment 'development' "
Any suggestions how to resolve this?

**Comment by jywarren** [comment]
Yes! If you follow prerequisites installation steps in the readme, you can
get the dependencies required to do thumbnail image generation that image
upload requires. Thanks!

**Comment by gautamig54** [comment]
Thanks @jywarren I got working now. I was some macOS issue.

**Comment by gautamig54** [comment]
@jywarren Do you want the wiki/tag content below the image like this?

![Screen Shot 2019-06-08 at 6 04 26 PM](https://user-images.githubusercontent.com/35326753/59147312-8f9fb480-8a17-11e9-9ba9-3a46507f4ed0.png)

Or like the divided page where half of it belongs to the picture and half for its content. The problem with that is it works fine with smaller images but with larger images as in https://publiclab.org/tag/pi-camera it writes on the image. In that case we can try resizing the image. What say?

**Comment by CleverFool77** [comment]
Hi @gautamig54 Can you just look into this small bug. The `Continue` button is going out of card.

![Screenshot from 2019-06-08 15-31-14](https://user-images.githubusercontent.com/26685258/59147793-b2cd6280-8a1d-11e9-937d-25c7c4564816.png)

**Comment by gautamig54** [comment]
@CleverFool77 I'll solve this one. Thanks!

**Comment by gautamig54** [comment]
I have raised a PR for the above bug #5860 
Thanks for pointing this!

**Comment by jywarren** [comment]
For the quick fix to the /tag/____ page image issue, we originally had the image and text quite small; i think just setting the image to 100% width solves it for now:

![image](https://user-images.githubusercontent.com/24359/59209975-8713bf00-8b7a-11e9-908f-be441366333f.png)

However, for the broader fix to this page, we should look to the style guide! https://publiclab.org/notes/warren/05-07-2019/introducing-a-draft-style-guide-for-public-lab

**Comment by gautamig54** [comment]
@jywarren Is this fine for the smaller images for now?

![Screen Shot 2019-06-11 at 1 02 12 AM](https://user-images.githubusercontent.com/35326753/59221150-3c2e9180-8be4-11e9-9fa4-31b427b873a9.png)

**Comment by CleverFool77** [comment]
Hi @jywarren @gautamig54 
As we can see that as per the progress of project. People and tags section is almost done. Questions page is 3/4th done i guess.  We are working on search section part right now. So should I open a new planning issue for a new section as we can look over the planning and break up parts of the new section while continuing the work on current one. So if yes, which section should be next from dashboard, profile, tags/tag name etc? As there might be priorities regarding sections. And if no, should the section done till now be refined?

**Comment by jywarren** [comment]
Let's start working on the /tag/_____ page! That really needs some work.
And then perhaps the profile page which is also quite a mess? Then we
circle back to the dashboard! How does that sound?

**Comment by gautamig54** [comment]
That sounds great @jywarren. I'll open up issues for the individual tags page and the profile page.
Thanks!

**Comment by CleverFool77** [comment]
Hi 
I published my blog for outreachy this morning regarding the work.
https://medium.com/@lekhikadugtal/my-project-work-for-outreachy-e455974cdb47
Do give it a read <3 
cc : @jywarren @gauravano @milaaraujo @rexagod @gautamig54

**Comment by jywarren** [comment]
Awesome!!!!! Please do post on publiclab.org as well! Thank you!

**Comment by jywarren** [comment]
Closing this as the only things left are the page subheadings, the new dashboard #6072 and the final Questions page #6323 

THANKS AND CONGRATS!!!
