### ISSUE TITLE
Translation prompts interrupting some button HTML

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5749]
![Screen Shot 2019-05-20 at 3 33 49 PM](https://user-images.githubusercontent.com/24359/58046935-bce1fc80-7b14-11e9-8777-131bd2dd6148.png)

#5651 related -- @gauravano this is on the /subscriptions page -- will this be addressed via the "not ones with HTML in them" adjustment? Thanks!

**Comment by gauravano** [comment]
Hi @jywarren, I have raised a PR for Translation prompt improvement - https://github.com/publiclab/plots2/pull/5738 and that will solve this issue. A system test is failing so, I am going through system test and will resolve it ASAP. Thanks!

**Comment by gauravano** [comment]
Solved in #5783
