### ISSUE TITLE
Fix "3 column print format" post Bootstrap

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5758]
in #1622 we did this, and it's worked really well, but post Bootstrap 4 update it needs some work. 

We're catching follow-up issues one by one in #5612, but this is a big enough one that I thought we should open an independent issue. 

![image](https://user-images.githubusercontent.com/24359/58106255-cec7ac00-7bb5-11e9-9e6d-911f681c2c7d.png)

I would guess we need to tweak these files:

https://github.com/publiclab/plots2/blob/master/app/assets/stylesheets/print.css

https://github.com/publiclab/plots2/blob/794df370264a605935483aa8d0e4946bfd14c37c/app/views/like/_like.html.erb#L98-L108

**Comment by jywarren** [comment]
For reference, they used to print in nice 3-column PDFs for making brochures, like this!

![image](https://user-images.githubusercontent.com/24359/58109404-92974a00-7bbb-11e9-95a5-2f6d4e6dab36.png)

**Comment by jcolborn-dropdeadgames** [comment]
Hello. I would like to handle this issue if it is available.

**Comment by ebarry** [comment]
Hey, just writing in to say this is important for accessibility, that people can print off the content from our webpages.

**Comment by ebarry** [comment]
Copying in @publiclab-mimi

**Comment by coder-cracker** [comment]
If this issue is not closed. I want to work with this issue

**Comment by jywarren** [comment]
We'd love help with this. Just a heads up though that it may be pretty
involved! It involves reworking a print stylesheet in detail to ensure
things print nicely, and includes some Javascript as well to hide some
elements, and toggle a 3-column CSS layout. But one thing we can start with
is listing out problems with the current state of this! Thank you!

**Comment by urvashigupta7** [comment]
Hi @jywarren. I would like to work on this. :)

**Comment by urvashigupta7** [comment]
![Screenshot from 2020-10-20 09-41-57](https://user-images.githubusercontent.com/41363633/96539374-8899df00-12b8-11eb-8544-04d52090860f.png)
 I guess this looks perfect. @jywarren :thinking:
