### ISSUE TITLE
Slow cache generation on profile API endpoint

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5761]
Related to #4561!

https://oss.skylight.io/app/applications/GZDPChmcfm1Q/1558392120/1d/endpoints/Srch::Search%20%5BGET%5D%20srch%2Fprofiles

![image](https://user-images.githubusercontent.com/24359/58139871-bcc42880-7c0a-11e9-85cc-cc87c7ec9806.png)

https://stackoverflow.com/questions/27574861/slow-cache-read-on-first-cache-fetch-in-rails

So.. after some research, it seems like maybe... we should remove this caching? Using this on production in the rails console is almost instant. Is all the time being taken generating the cache???

https://github.com/publiclab/plots2/blob/e201b3b8e7b7bb4a56f7e926a7f6e8bd8b5a7dba/app/api/srch/search.rb#L95-L98

**Comment by jywarren** [comment]
If this works, we may want to re-examine this too: https://oss.skylight.io/app/applications/GZDPChmcfm1Q/1558464720/6h/endpoints/Srch::Search%20%5BGET%5D%20srch%2Fcontent

**Comment by jywarren** [comment]
It's down to ~2.6s in stable without caching, versus ~3.5s in production with caching. I think that's promising but let's see how it does in production as well, and monitor Skylight to see if the cache generation line drops, and overall speed improves.

**Comment by jywarren** [comment]
You know, it's really not clear. Cache generation is gone, but overall more requests seem to be running slowly:

https://oss.skylight.io/app/applications/GZDPChmcfm1Q/1558703340/6h41m/endpoints/Srch::Search%20%5BGET%5D%20srch%2Fprofiles

![image](https://user-images.githubusercontent.com/24359/58353480-98e82900-7e3c-11e9-921e-a0baeb113e61.png)

There's still a mysterious `GET srch profiles` line for which I'm not sure what the cause is. When running this query like `SearchService.new.find_users`, it's quite fast - way less than a second. Just as shown in the SELECT statement in Skylight. So, what's taking so long and making 4.5 million assignments?

**Comment by jywarren** [comment]
It's certainly not fast to run this: https://publiclab.org/api/srch/profiles?query=warren

**Comment by icarito** [comment]
maybe the mysql-slow-logs and some log analyzer can give insight...

**Comment by icarito** [comment]
http://tycho.media.mit.edu/log_20190525/mysql-slow.html
http://tycho.media.mit.edu/log_20190525/production.html

Here for reference - need deeper dive, on first look I could not pinpoint it.

**Comment by jywarren** [comment]
We reverted it today -- had been seeing some memory issues and although it's not clearly linked, this was a high load endpoint and it wasn't any faster than it had been.
