### ISSUE TITLE
Text boxes on the Profile Edit page are too small since Bootstrap update

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#5768]
I was originally going to file an issue about gif upload on Profile Pages, but when i went to edit mine, i saw that the recent site update had made the text boxes on the Edit Profile too small for a prolific writer and gif uploader like myself, specifically:

- the Bio Text box cannot be expanded to the right

![profile-editing-since-update](https://user-images.githubusercontent.com/161439/58201689-ae761b00-7ca3-11e9-9da1-f80df67c4de9.gif)

**Comment by jywarren** [comment]
Thanks for reporting - linking to
https://github.com/publiclab/plots2/issues/5612 as well!

**Comment by ebarry** [comment]
Thanks for fixing this!
