### ISSUE TITLE
Version control schema file for using development database

### ISSUE THREAD

**Issue by ananyo2012** [publiclab/plots2#577]
As mentioned in https://github.com/publiclab/plots2/pull/545#issuecomment-223821888 it would be better if we version control the schema file for using the development database as it would be efficient in many ways and reduce the hassle of updating the development.sqlite.example file each time a new migration is introduced.The steps involved in the process would be:
- Deleting the development.sqlite.example files from repository
- Renaming the schema.rb.example file to schema.rb
- Removing the schema.rb from .gitignore so it can be version tracked

For deployment we have to run `rake db:create` and then `rake db:setup`. That's all. I think we won't need any rake tasks as there re just two commands. The process is independent of any database used. The readme instructions will be correspondingly changed.

@jywarren If you approve this I can make a PR with the necessary changes.

**Comment by jywarren** [comment]
The problem with this is that the schema file is changed when running rake
db:migrate, so then we have to force overwrite it on the production server.
I'd like to ask for @icarito's input (he is our sysadmin). The
development.sqlite.example file is really nice for first-time developers,
and I had a preference for your other suggestion, which would be to make a
rake script to automate building a new sqlite.example file when new
migrations are added.

**Comment by ananyo2012** [comment]
@jywarren Well will it be a problem if the production server has a updated schema file? Just being curious. I still think we should version control the schema file. But if its not then we can just version control the schema.rb.example file and remove the development.sqlite.example. So every time a new migration is introduced we can update the schema.rb.example file. Thus for setting up the database the steps would be. 
- Copy the schema.rb.example file to schem.rb 
- run `rake db:create`
- run `rake db:setup`
We can write a rake task for the above steps so that first timers find it easy to setup the database.

**Comment by jywarren** [comment]
@icarito may know best. I just think it's strange to have to run `git checkout db/schema.rb` before updating production code. I believe we used [this as a reference for the current process](http://stackoverflow.com/questions/737854/what-is-the-preferred-way-to-manage-schema-rb-in-git).

**Comment by ananyo2012** [comment]
Actually I tried running `rake db:create` with a fresh database but it showed errors due to the missing gems for a spatial column. Only `rake db:setup` works for a fresh database. Ok can we then use the alternative that I provided above?

**Comment by jywarren** [comment]
I think that's correct -- `db:setup` is described in the readme: https://github.com/publiclab/plots2/#installation but `db:create` is not. So is your final proposal then to make a rake task to run `rake db:setup` and create `.example` copies of the development.sqlite and schema.rb files?  If so, what would we call the rake task, and we should also make a copy of the existing `development.sqlite` file before overwriting it with a "fresh" one, in case a developer has created development data they want to keep.

**Comment by ananyo2012** [comment]
@jywarren What I want to mean that a development.sqlite.example file won't be necessary.If we just maintain a updated schema.rb.example file it would be sufficient. I just found out that just running `rake db:setup` will create and setup the database. Won't need db:create. So It's just two steps to setup a fresh database for a new user.
- Copy schema.rb.example file to schema.rb
- Run `rake db:create`
Since development.sqlite is a binary file where we can't actually see the changes and also it is something like the 'whole database' not only the structure there can be possible errors in future. 

My final proposal is removing the development.sqlite.example file from the repository and only maintaning a updated schema.rb.example file.  A rake task won't be necessary as we just need to rename a schema.rb to schema.rb.example in case of new migrations which is quite a easy-ish task.

**Comment by ananyo2012** [comment]
@jywarren Uh Jeff can you give your final verdict on this so that it can be closed. To make you remember the final proposal is to just to maintain a updated schema.rb.example and remove the development.sqlite.example file. For setting up a new database a user just has to rename the schema.rb.example to schema.rb and run `rake db:setup`. That's all. Explanation can be found above.

**Comment by jywarren** [comment]
Hi Ananyo -- sorry, I'm eager to wrap this up too. 

I hear what you're saying, and I think this could work, but the sqlite.example file was to reduce complexity for first-time contributors. 

To demonstrate that this works, could you create a new Cloud9 script, and confirm that it runs successfully following [exactly the steps in the Readme](https://github.com/publiclab/plots2/#simple-installation-with-cloud9)? 

Script: https://github.com/publiclab/plots2/blob/master/install_cloudnine.sh 

In some ways this is like a test for ease of initial install on a completely "plain" unmodified Ubuntu system. If newcomers can follow this process and see it working on Cloud9, a standard VM, we can be pretty sure that it'll work for them in general. 

Not to mention the Cloud9 script currently depends on the sqlite.example file and we'd have to update that anyways to make this change. 

Thanks, this is a good idea and should reduce the burden of making PRs. Please include a change to the PULL_REQUEST_TEMPLATE too: https://github.com/publiclab/plots2/blob/master/PULL_REQUEST_TEMPLATE.md

**Comment by jywarren** [comment]
@icarito -- possibly related -- if we modify this, might the Cloud9 script I mentioned be a basis for a Dockerfile, or could we use a Dockerfile instead of this in conjunction with Cloud9 or a similar service? (Sandstorm.io or something?)

**Comment by ananyo2012** [comment]
@jywarren Thanks Jeff for considering this!

**Comment by jywarren** [comment]
Thanks for tackling it! I love every step we can do to make contribution easier.
