### ISSUE TITLE
Profile Page Issues

### ISSUE THREAD

**Issue by publiclab-mimi** [publiclab/plots2#5770]
Hey guys, two bugs to report on the Profile Page since the update.

From the Profile Page, I'm not able to use the tabs to get over to things that I've coauthored or to drafts. I encountered this problem first on Safari, switched to Chrome, same issue. Hovering over the button shows the url: https://publiclab.org/profile/mimiss#draft or https://publiclab.org/profile/mimiss#coauthored but going directly to those links doesn't bring up either item. Here's a photo of what the page looks like:

<img width="1322" alt="Screen Shot 2019-05-22 at 3 05 58 PM" src="https://user-images.githubusercontent.com/48802639/58205352-f137f300-7ca3-11e9-8c3a-c55471072378.png">

Second issue is that the buttons on the page are wonky (specifically mark as spam or read more), both in Safari and Chrome. The text and button don't align well. The buttons do work.

**Comment by publiclab-mimi** [comment]
Linking over to #5612

**Comment by jywarren** [comment]
Thanks for reporting, Mimi!

**Comment by AnshitaVishwa** [comment]
@jywarren i would like to work on this issue.

**Comment by jywarren** [comment]
Oh this would be great! Thank you!

**Comment by michelelong** [comment]
I can fix the broken tabs to authored/coauthored/drafts if no one is doing it yet.

**Comment by CleverFool77** [comment]
Sure @michelelong You can go forward. and Do ping if you came across any problem.
Thanks !1
