### ISSUE TITLE
Inclusion of lat and lon on API profile search query

### ISSUE THREAD

**Issue by rarrunategu1** [publiclab/plots2#5774]
The following issue on mapknitter requires this update to be able to return a profile user's location if they have added it on their profile
https://github.com/publiclab/mapknitter/issues/626

**Comment by rarrunategu1** [comment]
With Jeff's help I already have the changes made on a separate branch to submit a pull request for review

**Comment by jywarren** [comment]
Just noting that this code is live! https://publiclab.org/api/srch/profiles?query=Gauravano
