### ISSUE TITLE
Print in 3-Column Layout Buggy

### ISSUE THREAD

**Issue by publiclab-mimi** [publiclab/plots2#5777]
Hello again friends! I've learned that we have a bit of an issue with printing from the website in the 3 column layout format.

<img width="226" alt="Screen Shot 2019-05-23 at 10 24 59 AM" src="https://user-images.githubusercontent.com/48802639/58265591-95be4180-7d45-11e9-8ca0-3aef7b3d3ec6.png">

On Safari, the option to print in 3 column layout doesn't do anything different from a regular print. It looks like this:

<img width="418" alt="Screen Shot 2019-05-23 at 10 27 20 AM" src="https://user-images.githubusercontent.com/48802639/58265638-af5f8900-7d45-11e9-9557-e4c294e0a08f.png">

On Chrome, it does create 3 columns, but there is so much overlap that they're not readable. I've tried for a few different pages (research notes & wikis), here's what it looks like:
<img width="988" alt="Screen Shot 2019-05-23 at 10 27 48 AM" src="https://user-images.githubusercontent.com/48802639/58265742-e6359f00-7d45-11e9-9fc5-2b55bedd85bf.png">

<img width="568" alt="Screen Shot 2019-05-23 at 10 24 26 AM" src="https://user-images.githubusercontent.com/48802639/58265729-e2a21800-7d45-11e9-802a-137db6f877a5.png">

<img width="488" alt="Screen Shot 2019-05-23 at 10 25 07 AM" src="https://user-images.githubusercontent.com/48802639/58265754-eafa5300-7d45-11e9-922a-432bfdeb668e.png">

**Comment by publiclab-mimi** [comment]
Also linking to #5612 because I think it may be related.

**Comment by jywarren** [comment]
Hi! Thanks! I actually opened this already here, i'm going to merge these! https://github.com/publiclab/plots2/issues/5758
