### ISSUE TITLE
Twitter OAuth not working

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#5792]
Hi all,
I am facing logging into Twitter. Is there anyone else facing the same trouble?
It is going in infinite loop.
@gauravano @ebarry @aSquare14 @publiclab/reviewers .
Thanks in advance for helping.

**Comment by gauravano** [comment]
Hi @SidharthBansal, 

I haven't logged in to publiclab.org via Twitter so documenting accordingly --
The page kept loading for nearly a minute or two and then I was redirected to /research so not logged in. I tried logging-in using Twitter again but no success, this time it was something like infinite loop as you mentioned but without any reload time. 

Then, I refreshed the page and tried logging in again and got redirected to :point_down: 

![Screenshot from 2019-05-27 02-58-36](https://user-images.githubusercontent.com/20878070/58387463-0efeb280-802c-11e9-9a38-21b7426fb6a2.png)

And, after authorizing, got redirected to /dashboard. Logged out again and tried to login via Twitter, went smooth. So, there might be a cache in play? Or, anything which maybe preventing the loading of Twitter authorization page, as that page is loaded every time.

Thanks!

**Comment by SidharthBansal** [comment]
I tried to login through Twitter. It is working fine here. 
Twitter pages are not handled by PL. Twitter handles it. So, even if it is working one time AND all the links which comes in the infinite loop are of twitter domain, we are having consistent source code at PL.


@jywarren are you still facing this issue?
I am not facing this issue any longer. I tried it today and yesterday.

**Comment by jywarren** [comment]
Working for me! Closing, thanks!
