### ISSUE TITLE
Fix Rubocop performance deprecation warning

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#5795]
### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

**Problem**:

Performance cops have been removed from RuboCop 0.68 

📝 **Update**: 

Put this in `Gemfile`.

```
gem 'rubocop-performance'
```

Then add this in `.rubocop.yml`.

```yaml
require: rubocop-performance
```

After changing run `bundle install`

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

**Comment by kodyclemens** [comment]
I'd be happy to tackle this issue.

**Comment by Esh08** [comment]
Hey, I'm a first time user of GitHub and would love to know if I can assist you in any way? @kodyclemens

**Comment by kodyclemens** [comment]
@Esh08 Unfortunately I think this issue may have to wait as Codeclimate does not yet support the new gem, which is resulting in failing tests.

**Comment by jywarren** [comment]
Thanks! That's too bad - maybe we can mark the PR with that and then merge it hopefully down the road once it is supported? Thank you for your help!!!

**Comment by alaxalves** [comment]
@kodyclemens @jywarren CodeClimate currently only supports rubocop ~> 0.52.0. We had this same issue with mapknitter at https://github.com/publiclab/mapknitter/pull/547

**Comment by nstjean** [comment]
Is this needed now? This link says that codeclimate should support rubocop-performance:
https://github.com/codeclimate/codeclimate-rubocop/issues/166

Let me know and I'll create a pull request.

**Comment by Lisa-Caton** [comment]
Hi there, I would like to take this issue (as a first-timers-only) :)

**Comment by cesswairimu** [comment]
@Lisa-Caton go ahead its all yours

**Comment by Lisa-Caton** [comment]
great - I'll get started asap! Thanks so much.

**Comment by Lisa-Caton** [comment]
I think I am stuck. When I did the pr it looks like my branch isn't passing checks with my submission. [https://github.com/publiclab/plots2/pull/6437](url) I've only added the 2 lines to the code. And when I ran `rubocop --require rubocop-performance` it ran without errors on my terminal. (`92 files inspected, 126 offenses detected`) Since I am able to run the working command locally, I'm not sure what to do next.

**Comment by cesswairimu** [comment]
Hi @Lisa-Caton I will take a look

**Comment by SidharthBansal** [comment]
Is this issue solved? Can we close this?

**Comment by jywarren** [comment]
Let's close it! Looks OK!
