### ISSUE TITLE
Need for more chatrooms?

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#5819]
Hi, as we were discussing in the Gitter channel about the need of more chatrooms for organising conversations better and at correct place, let's consider all the scenarios.

Convo from Gitter:
---------
> Do we have a seperate room for the Outreachy fellows? I was wondering that would make the process more convenient and efficient for the mentors and mentees. @jywarren @gauravano
Also, just to confirm, the opencall happens on recurring Tuesdays, right?

> Gaurav Sachdeva @gauravano May 30 00:44
We don't have separate room till now, but we are ready to form one if there's requirement

> Jeffrey Warren @jywarren May 30 00:44
I think maybe we need to get organized about Gitter rooms. Some people have made new ones, and I understand the need, but also don't want to get too fragmented -- especially since many SoC and Outreachy people would get a lot of help being able to rely on each other
maybe we need some kind of recommended thing like "try to always start conversations in the main room, and then move them to other rooms" as well as a listing of rooms?
it's easy to get siloed, but also easy to feel like we're flooding the main chat room!
both are legitimate things to watch for

> Pranshu Srivastava @rexagod May 30 00:50
Indeed, we definitely need a plan to manage isolation and flooding.

> Jeffrey Warren @jywarren May 30 00:52
@rexagod if you have some ideas for this (or anyone else) perhaps we could start an issue and give some proposal a try for a week or two, and see if we like it?

> Pranshu Srivastava @rexagod May 30 00:52
I guess @CleverFool77 @ananyaarun can wiegh in on this, let us know if they require something of this sort?
Sure, @jywarren!
Also, regarding the publiclab/soc room, can we move the updates to some other place, maybe publiclab/updates, or something? That can help us deal with some of the flooding here.
The main room would still be used for general conversations.
I'll spin up an issue on this.

> Gaurav Sachdeva @gauravano May 30 00:57
Great!

**Comment by gauravano** [comment]
We can create more Gitter rooms. But. let's think for what cases we need more rooms-- 

1. Project-specific room -- I think, we don't need this type as it's good to have transparent and open discussions about the project. It will also help other contributors to be in-sync with the SoC projects.

2. Repo specific reviewers group -- We can think about this type. But, I think, the current reviewer's group is good and we can add reviewers of all repos there only 

3. Repo specific discussion group -- Sometimes, discussion about a repo's issue keep on getting big. It's not bad, but maybe repo specific group will be good to collect those discussions? Maybe, let's keep plots2 as a major general group and we can create rooms for Mapknitter and Image Sequencer for start?

4. SoC mentor group - We can create them as some things need privacy and maybe mentors will share their thoughts and opinions openly in Gitter room?
   
Thoughts are welcome @rexagod @jywarren @publiclab/community-reps @publiclab/reviewers @publiclab/mentors

**Comment by starkblaze01** [comment]
I think Repo specific discussion group will be great, keeping all the discussions related to Repo at one place will be also easy for others to the gist of what's going on related to that repo if they are left behind and easy to find which is usually hard because of conversation flooding in a single group. We can discuss the general ideas in plots2 itself and Repo specific discussions could be done in the respective channel.

**Comment by CleverFool77** [comment]
Hi @gauravano Can we poll maybe between various way. So everyone can choose maybe ?
Though According to me the project specific group looks like a great idea.
By this, we can continue on the conversation in chatroom in future too. Thus if a new contributor came across any problem. It would be preferred write their issues in chatroom of that specific group where we have only those people who are working and interested in that project instead of one main chatroom where we have all members of community.

**Comment by jywarren** [comment]
Sure a poll sounds nice. Gaurav remember how the poll with responses
worked? :-)

**Comment by gauravano** [comment]
Yeah, we can open a poll for sure. But, I want to mention that if any @publiclab/soc is facing communication issues or they think that having a separate project-specific room or repo-specific room will fasten and would be convenient for them and the work, then we just need to poll between **repo-specific** & **project-specific** room as your convenience is a priority for us. What do you think @jywarren? 

About @rexagod 's suggestion -
> Move updates from 'soc' to 'updates' room. That way the SoC room could be utilized for SoC-specific discussions, while the lobby could be used for sharing all sorts of general ideas. 

Do we really need those updates about the various activities @jywarren? I think we can remove them. 

 > As above, a separate room for all Outreachy discussions.

I think as we are considering dedicating a room for SoC, we can use that room only for Outreachy as both programs share the same aim of OSS uplifting and introduction with little bit different processes?

**Comment by jywarren** [comment]
Yes I guess just repo vs project. I think we should not split outreachy
from gsoc, as there are many benefits to being well connected.

For updates we can suggest it's a best practice but not require it?

**Comment by IshaGupta18** [comment]
I think project specific chatrooms will be a great idea!

**Comment by gauravano** [comment]
React with the corresponding emojis to give your opinion:

1. Repo-specific room (Separate groups for each of the repo, starting from Mapknitter, Image-Sequencer, LDI, LEL -- Long term/permanent groups) :heart: 
2. Project-specific room (Separate groups for each of the Summer of code project -- temporary/archived after the end of SoC) :+1: 
3. SoC group (Group which will consist of all mentors and SoC interns) :rocket:

Only one of the option from 1 and 2 will be implemented. For 3, we will consider it depending on # of votes.

Thanks!!

**Comment by cryptoclidus** [comment]
Another option could be a two chat split: general / projects, but I'm voting for an existing option!

**Comment by skilfullycurled** [comment]
Am I correct in thinking that a gitter room is not the same as a slack channel?  If not, does Riot have an equivalent?  I have some thoughts on this but they might not be relevant given the structure of what is being discussed.

**Comment by rexagod** [comment]
@skilfullycurled [I'd rather not recommend Riot anyway](https://www.reddit.com/r/privacy/comments/bca2k2/matrix_riot_hacked_for_the_second_time_stay_away/), but yes, it does have that functionality (wrt. gitter rooms).

**Comment by skilfullycurled** [comment]
@rexagod, thanks for responding to my question.  My question was poorly worded and not very specific.  I confused Gitter as being synonymous with Riot since that was what I was using (thanks for the tip by the way!).

More directly, I'm wondering what we mean by "chatrooms" in this conversation.  Do chatrooms refer to a specific feature in Gitter which is different than what one thinks of when they use a "channel" in Slack?

**Comment by rexagod** [comment]
No, not a gitter-specific feature, but vaguely similar to channels. I take it that you've used the publiclab lobby in the past, right? That's a "chatroom", and that is (chatroom, not the lobby) what's being referred to here.

**Comment by skilfullycurled** [comment]
I think I see now.  Did a bit more [digging](https://gitter.zendesk.com/hc/en-us/articles/200178951-Gitter-communities-and-rooms) and it sounds like [although a room can be a channel](https://developer.gitter.im/docs/rooms-resource), in general, Channels in Gitter are subsets of rooms.  Thanks, that really helped me to understand what was guiding the choices in the poll.

**Comment by gauravano** [comment]
Hi everyone, we have 3 new chatrooms -

https://gitter.im/publiclab/image-sequencer
https://gitter.im/publiclab/leaflet - For all leaflet based projects
https://gitter.im/publiclab/mapknitter

You are welcome to join these rooms and hold discussions regarding your project there. Thanks!

**Comment by IshaGupta18** [comment]
Could you please open one up for simple-data-grapher?

**Comment by gauravano** [comment]
cc @jywarren

**Comment by gauravano** [comment]
Thank you @jywarren!

Here's one for simple-data-grapher: https://gitter.im/publiclab/simple-data-grapher

**Comment by gauravano** [comment]
Hi, closing this now but feel free to re-open if the discussion around any new Gitter room required. Thanks everyone!
