### ISSUE TITLE
duplicate sqlite example file

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#582]
@ananyo2012 - just noticed this that you mentioned; @lalithr95 I think you misnamed your submitted example sqlite file. Can you submit a pull request to fix this? Thank you, and sorry, I should've caught this!

https://github.com/publiclab/plots2/blob/master/development.sqlite3.example
https://github.com/publiclab/plots2/blob/master/development.sqlite.example

**Comment by ananyo2012** [comment]
@jywarren Fixed in #566

**Comment by lalithr95** [comment]
Thanks @ananyo2012 @jywarren 
I have updated my previous migrations in development.sqlite.example and removed sqlite3 file in #583

**Comment by ananyo2012** [comment]
@jywarren This can be closed now.
