### ISSUE TITLE
Tooltips for interface consistency and clarity on wiki and blog

### ISSUE THREAD

**Issue by michelelong** [publiclab/plots2#5820]
![follow-tools](https://user-images.githubusercontent.com/50340123/58764241-5d2f1c80-852a-11e9-87aa-a02c98403a3f.png)

Similar to closed issue #2115 and open issue #5382.
The follow buttons and tools dropdown don't have tooltips on mouseover.

**Comment by gauravano** [comment]
hey @michelelong, again great catch! Dropping the link to file here - https://github.com/publiclab/plots2/blob/master/app/views/like/_like.html.erb in case you're interested in solving this one :smile:. Also, do you think, it would be good if we open dropdown on hover? 

Thanks!!

**Comment by michelelong** [comment]
Yeah, I can fix this one.
I wouldn't have it dropdown on hover. It's annoying when you move the mouse around in the middle of the screen and stuff you didn't mean to open keeps popping up.

**Comment by gauravano** [comment]
Hmm, makes sense. But, don't you think that dropdown icon is self-explaining that there's a sub-menu present. Do we really need to add a title for that?

**Comment by michelelong** [comment]
Yes, the dropdown caret makes it clear there is a submenu, but there isn't a hint as to what can be found in the submenu like the print options. It should probably have a more descriptive tooltip than just "tools" if it is going to have one or I can remove it if you prefer.
