### ISSUE TITLE
Change absolute link to methods on the dashboard

### ISSUE THREAD

**Issue by michelelong** [publiclab/plots2#5821]
![dashboard-absolute](https://user-images.githubusercontent.com/50340123/58766494-02ef8500-8545-11e9-8c03-9247b7f631c4.png)

**Problem**: When working locally, an absolute link to "Exploring projects" on the dashboard goes to the actual website instead of loading the local methods page.

**Solution**: Change link to relative.
![absolute-link](https://user-images.githubusercontent.com/50340123/58766610-3b439300-8546-11e9-9248-637ac018439c.png)

**File to edit**: app/views/dashboard/dashboard.html.erb

**Comment by gauravano** [comment]
Hi @michelelong, great catch. If you are interested in solving this please make a PR. Thanks!!
