### ISSUE TITLE
[PROPOSAL] Organizing Gitter chatspace

### ISSUE THREAD

**Issue by rexagod** [publiclab/plots2#5822]
> I think maybe we need to get organized about Gitter rooms. Some people have made new ones, and I understand the need, but also don't want to get too fragmented -- especially since many SoC and Outreachy people would get a lot of help being able to rely on each other

> maybe we need some kind of recommended thing like "try to always start conversations in the main room, and then move them to other rooms" as well as a listing of rooms?

> it's easy to get siloed, but also easy to feel like we're flooding the main chat room!

> both are legitimate things to watch for

Hi all! I was recently encouraged to open this issue by @gauravano after sharing my thoughts on opening a separate room for Public Lab's Outreachy community for a better and focused overall engagement among the same. However, agreeing to @jywarren's statement above, I believe that this can actually be a part of a bigger issue we are currently facing in out gitter chatspace, namely, isolation and flooding (eg., occasionally a newer member can't get much engagement in the lobby due to messages of different categories being posted in the same room, difficulty finding a particular message, many discussions on different topics simultaneously, etc.). Therefore, I've opened this issue for any and all ideas that may help us untangle the chatspace for the better.

Feel free to chime in, thanks!

**Comment by rexagod** [comment]
Okay so I'll start. Some changes I'd recommend are:

- Move updates from 'soc' to 'updates' room. That way the SoC room could be utilized for SoC-specific discussions, while the lobby could be used for sharing all sorts of general ideas.
- As above, a separate room for all Outreachy discussions.

Maybe we could formulate a composed plan out of all the ideas that get posted here and try it out for a week or two, like @jywarren recommended?

**Comment by rexagod** [comment]
@gauravano Can we pin this for more views?

**Comment by gauravano** [comment]
Hey @rexagod, I thought you forgot about it and so I opened a issue yesterday - https://github.com/publiclab/plots2/issues/5819 :sweat_smile:

**Comment by rexagod** [comment]
No problem, @gauravano!

Closing this in favor of #5819! 👍

**Comment by gauravano** [comment]
Don't forget to add your comments to #5819 @rexagod. And, sorry for the inconvenience.

**Comment by rexagod** [comment]
Will do, @gauravano, and no problem! 👍
