### ISSUE TITLE
Username with a space in it needs better validation error message

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5829]
This is small but important - someone wrote in saying they got a "username invalid" message when trying to sign up; I tried, and realized that if you enter a space in a username, it says "invalid" but doesn't say why. 

![Screen Shot 2019-06-03 at 6 42 29 PM](https://user-images.githubusercontent.com/24359/58839342-78378480-862f-11e9-8714-43dba7180a4f.png)

We should offer a validation error message specifying the formatting rules for usernames!

I think this should go here: 

https://github.com/publiclab/plots2/blob/faa5a12e86bf7944dca43134f649947f03ca96a6/app/models/user.rb#L60-L61

**Comment by gauravano** [comment]
![Screenshot from 2019-06-04 06-11-02](https://user-images.githubusercontent.com/20878070/58843317-959c3b00-868f-11e9-9d10-e8608d33901e.png)

@jywarren is this message good?

**Comment by jywarren** [comment]
Yeah!!! Thanks!!

**Comment by suretrust** [comment]
@jywarren is anyone working on this? I'd like to work on it.

**Comment by jywarren** [comment]
@suretrust that would be awesome, thank you!!!

**Comment by jywarren** [comment]
@suretrust this is also the kind of thing that would be great to have a test for. Have you written Rails tests in the past? Here's an example of functional testing of validations:

https://github.com/publiclab/plots2/blob/89432eeb3e780cf3953f11fc6971f5574a410d2a/test/functional/users_controller_test.rb#L243-L256

We might also check the actual error message, although that could take some experimentation to get right; maybe it'd be something like this:

```ruby
assert_equal "correct message here", assigns(:user).errors.first
```

Thank you! We can help if you get stuck!!!! 👍

**Comment by suretrust** [comment]
@jywarren thanks, I'll surely ask for help if I get stuck. :)

**Comment by gauravano** [comment]
Hi @jywarren, I spent some time with this one and I think we can incorporate translations here - https://stackoverflow.com/questions/808547/fully-custom-validation-error-message-with-rails We can further divide the messages - https://stackoverflow.com/questions/17935597/ruby-on-rails-i18n-want-to-translate-custom-messages-in-models for simplifying for user. 

I have raised https://github.com/publiclab/plots2/pull/5836 setting up such structure and will incorporate @suretrust change accordingly in Translation flow.

Thanks!

**Comment by Tlazypanda** [comment]
@jywarren is this issue still available?

**Comment by jywarren** [comment]
I suppose it is! @gauravano?

**Comment by Tlazypanda** [comment]
@jywarren I would like to work on this :sweat_smile:

**Comment by jywarren** [comment]
Please go ahead! Thank you!
