### ISSUE TITLE
Fix the new question form

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5839]
## Description
The UI is distorted due to bootstrap4 upgrade.
maybe we can work on this.
For eg - 
* The toolbox regression.
* The field for tags look different from other fields.
* The flash notice width maybe ?

![gg](https://user-images.githubusercontent.com/26685258/58964309-4c9dd100-87cc-11e9-916a-3dae7e9f26b9.gif)

**Comment by jywarren** [comment]
Yes, let's make this as smooth and simple as possible!

Some of these changes we can also port back to the main /post form which
especially looks bad in mobile devices. Thanks!

**Comment by CleverFool77** [comment]
Hi @jywarren I went through the code for question-form. I seem to see a class called `ple-guide` but cant see the usage. I guess its the info which we were showing earlier on first column of grid ?

**Comment by jywarren** [comment]
Yes, I think so, more used in the regular post form.

**Comment by CleverFool77** [comment]
So Should I remove it from question form as it doesn't have any usage here ?

**Comment by jywarren** [comment]
I think so. I thought perhaps it was necessary for some reason but if it
works fine without then all good!

**Comment by CleverFool77** [comment]
Hi @jywarren I went through code, Fixed some widths and other and came with results. The first column of grid which is class of `ple-guide` is empty. I guess it's because same code is used for other forms like `/post`. But in other forms there is info being showed in this first column where as its empty in questions form. 
You can see the gap in the screenshot below.
![Screenshot from 2019-06-06 23-11-09](https://user-images.githubusercontent.com/26685258/59054052-7b8d7300-88b0-11e9-9239-32863a6e369c.png)

So I guess that this class is not necessary in this questions-form. Although it is necessary in other forms but as we different files for both forms and they have different fields. So it wont have effect on others. maybe the work can be done on complete rearrangement of grid section for `question-section`. What do you say ?

**Comment by jywarren** [comment]
If it doesn't break the question form then that's fine to remove. Let's
keep it simple!
