### ISSUE TITLE
Email auto replies are auto-posting to research notes. 

### ISSUE THREAD

**Issue by bronwen9** [publiclab/plots2#5842]
### This has happened before, but email auto replies are showing up as comment responses in threads on the site. 

This particular email posted about 70 times, and contains information about the poster's personal schedule as well as contact information for another person. 

![AutoReplyPost](https://user-images.githubusercontent.com/8331717/58979199-7ab6ed00-879b-11e9-8dea-448238f51796.gif)

Can we disable auto comments in comment by email?

**Comment by bronwen9** [comment]
This is actually an issue on 2 posts-- the 2nd post is here: https://publiclab.org/notes/eustatic/05-24-2019/balloon-map-of-south-bonfouca-cel-usfws-planting-with-pies-and-toes

Worth noting that the email posting to the comments has a pretty clear "do not share" note at the bottom. 
<img width="490" alt="Screen Shot 2019-06-05 at 2 19 28 PM" src="https://user-images.githubusercontent.com/8331717/58979847-f82f2d00-879c-11e9-87bc-730294457ccc.png">

**Comment by jywarren** [comment]
Linking to previously opened issues at #3218 #4562 !

**Comment by jywarren** [comment]
And just to update on the status here, the original fix at #3218 didn't work, or worked for only some autoreplies. I'm closing that in favor of this issue. 

#4562 was not followed up on, but I found some resources for how to identify an auto-reply email here: https://github.com/publiclab/plots2/issues/4562#issuecomment-458547740


https://stackoverflow.com/questions/1027395/detecting-outlook-autoreply-out-of-office-emails

https://stackoverflow.com/questions/9426801/detect-auto-reply-emails-programmatically

geerlingguy/Imap#6

https://github.com/jpmckinney/multi_mail/wiki/Detecting-autoresponders

**Comment by jywarren** [comment]
And copying in the probably helpful notes from one of them:

```
There's no set of checks for auto-responses that produce perfect behavior (detect all auto-replies with no false positives), but the following checks have worked well so far:

header "Auto-Submitted" with value other than "no" (see RFC 3834)
headers "X-Autoreply" or "X-Autorespond" with any value
header "Precedence" with value "auto_reply"
```

**Comment by jywarren** [comment]
Apparently we can read the headers like: `email.headers["Message-ID"]` -- so for the above:

* `email.headers["Auto-Submitted"] != "no"`
* `email.headers["X-Autoreply"]`
* `email.headers["X-Autorespond"]`
* `email.headers["Precedence"] == "auto_reply"`

**Comment by jywarren** [comment]
So we'd modify this line:

https://github.com/publiclab/plots2/blob/04d5bbca4f47066e9628c1dc78e9961ef32c20f7/app/models/comment.rb#L263-L266

**Comment by jywarren** [comment]
This is going to be difficult to test out. We can do it manually. But we should try to collect several full autoreply emails from different sources and put them in our fixtures: https://github.com/publiclab/plots2/tree/master/test/fixtures/incoming_test_emails

**Comment by jywarren** [comment]
@bronwen9 if you can fwd me some that would be very helpful

**Comment by jywarren** [comment]
Tests should be easy to write against real captured email samples. I added `Comment.is_autoreply(mail)` which we can use.

**Comment by jywarren** [comment]
Here is our Outlook test; we could add one more for an Outlook-generated auto-reply:

https://github.com/publiclab/plots2/blob/4a31189ea8cba15ebe166bfbd3ae2367e0d8cebf/test/integration/incoming_mail_parsing_test/outlook_parsing_test.rb#L3-L18

Similarly with Google and Yahoo auto-replies: https://github.com/publiclab/plots2/tree/4a31189ea8cba15ebe166bfbd3ae2367e0d8cebf/test/integration/incoming_mail_parsing_test

**Comment by jywarren** [comment]
OK, so our next steps would be:

* [ ] to capture sample auto-reply emails from Gmail, Outlook, and Yahoo, and add them to our fixtures, as, for example: `test/fixtures/incoming_test_emails/outlook/autoreply_incoming_outlook_email.eml`
* [ ] unit test with `Comment.is_autoreply(Mail.read('test/fixtures/incoming_test_emails/outlook/autoreply_incoming_outlook_email.eml'))` -- let's put this in https://github.com/publiclab/plots2/blob/master/test/unit/comment_test.rb !

**Comment by enviro3** [comment]
Hey all, just letting folks know I am attempting to solve this issue so it's a work "in progress". Thanks!

**Comment by jywarren** [comment]
thank you, much appreciated!!!

**Comment by jywarren** [comment]
OK, i worked a bit on this, and used @enviro3's collected samples of autoreplies from Outlook, Yahoo, and Gmail in addition to @patcon's collected properties to filter for, and wove them together into a `Comment.is_autoreply()` function. 

expanded on @enviro3's tests to create tests to properly identify autoresponses and non-autoresponses; once those properly run, i have filtering code ready to test against the sample emails. Then we can use that filter when processing received emails.

**Comment by jywarren** [comment]
#6289 was just merged, potentially solving this. Just wanted to say thanks to:

* @bronwen9 and @ebarry for clearly identifying and describing the issue, with examples
* @enviro3 for carefully and thoroughly collecting sample emails and building tests around them
* @patcon for finding the filter terms to look for

I hope this is resolved, but we'll have to wait and see -- it's a pretty complex little chunk of code. But all of these contributions were critical in solving this issue, so THANK YOU! 🙌 ❤️

**Comment by jywarren** [comment]
And noting that, since the basic mechanism is built now, we can continue to add more sample emails from other email systems, and more precise mail filters, building on #6289 as we go.

**Comment by ebarry** [comment]
Very cool!!!!!!!!
Thanks all

**Comment by enviro3** [comment]
> #6289 was just merged, potentially solving this. Just wanted to say thanks to:
> 
> * @bronwen9 and @ebarry for clearly identifying and describing the issue, with examples
> * @enviro3 for carefully and thoroughly collecting sample emails and building tests around them
> * @patcon for finding the filter terms to look for
> 
> I hope this is resolved, but we'll have to wait and see -- it's a pretty complex little chunk of code. But all of these contributions were critical in solving this issue, so THANK YOU! 🙌 ❤️

Thank you @jywarren for wrapping this up! much appreciated
