### ISSUE TITLE
Notes from banned author still published

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#5843]
Here's a mystery: 

This author is rightfully banned: https://publiclab.org/profile/c329163204

However, this note from this author still appears on the website: 
https://publiclab.org/notes/c329163204/05-23-2019/the-separation-essence-of-different-chromatography

Let's figure out where this bug is!

**Comment by michelelong** [comment]
When I visit the site, **not logged in**, through those links I don't see the note or author profile. I get the main site and a pink notice at the top that the author/note was banned.

**Comment by ebarry** [comment]
oh! this is great information! It must have been because i was a moderator that i could see that! 
I am surprised that comments can still be submitted to banned posts, but that's not really a problem so i'll close this issue! Thanks @michelelong ! and Welcome.
