### ISSUE TITLE
Long tags in People page are overflowing

### ISSUE THREAD

**Issue by Souravirus** [publiclab/plots2#5857]
@CleverFool77 @gautamig54 The recent changes in the people page has made the tags overflow in the People page. Please see to it. 
![image](https://user-images.githubusercontent.com/17192149/59095002-0e6ff100-8935-11e9-977a-11e96f2bce64.png)

**Comment by CleverFool77** [comment]
Hi @Souravirus Thanks for pointing it out.
This matter is in our notice. We had discussion regarding this and are looking into it and will fix it soon.
Thanks !!
