### ISSUE TITLE
Change colour for the featured tags on /questions page

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#5865]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

### 🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step
  - [ ] 🙋 **Claim this issue:** Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

  - [ ] 📝 **Update:** The featured tags on https://publiclab.org/questions are not showing up.
Update apps/views/questions/index.html.erb in the plots2 repository.
Add color style to the feature imported in L-12 to L-16

![Screen Shot 2019-06-11 at 1 31 17 AM](https://user-images.githubusercontent.com/35326753/59223274-240d4100-8be9-11e9-8f73-870724606249.png)

  - [ ] 💾 **Commit your changes**

 - [ ]  🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

You can also edit files directly in your browser and open a pull request from there.

 - [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?
Leave a comment below!

### Is someone else already working on this?
We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seem stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

**Comment by nhughey** [comment]
Hi,  i'd like to claim this issue and submit a pull request. First time contributer here.

**Comment by AkshayChoulwar** [comment]
Hi I also want to work on this can u assign it to me I am the first timer only :)

**Comment by gautamig54** [comment]
Sure @AkshayChoulwar.  You can go ahead with this one. Thanks and welcome to PL!!

**Comment by nhughey** [comment]
Hi, is there anything I can do to help as well?

**Comment by ramstore07** [comment]
Hey there! is the issue still open? first timer here :)

**Comment by newbazz** [comment]
I would like to work on this issue if no one is working on it.

**Comment by cesswairimu** [comment]
Sure go ahead
