### ISSUE TITLE
Reply-by-email emails sent repeatedly in loop

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5867]
Related to #5817 we noticed that some comments were getting posted over and over; we're not sure why, but we should look closely at this section of code; we've had to turn off `mailman` to stop this from going on forever (100s of repeated emails):

https://github.com/publiclab/plots2/blame/master/app/models/comment.rb#L262-L292

@namangupta01 can you poke around a little to see if you can see if anything has changed? 

We've been messing with this area of the code to try to resolve the memory issues, but it doesn't look like anything we changed would cause an infinite loop of email receiving:

https://github.com/publiclab/plots2/blob/ca1011840ac47940f4295a7a8679280cf74828b9/script/mailman_server#L22-L39

**Comment by jywarren** [comment]
Could be related to https://github.com/publiclab/plots2/issues/5668 as well... just to connect these two...

**Comment by jywarren** [comment]
OK, noting that we have /always/ had the `begin/rescue` loop enabled, since this feature was first implemented in https://github.com/publiclab/plots2/commit/fad88fd72c9d08f5591bf4c0cab402160eb9ea54#diff-331c6244d78f698043a2591c25d75d1e

until recently. @namangupta01 how do we mark mail as 'processed'? Is there some way that mail is not getting removed from the inbox?

**Comment by jywarren** [comment]
Is it possible we had been attempting to fetch the same email, and then it queued up somewhere like a zillion times, and we are still (at ~150 copies) making our way through that queue, and could flush it? Or are we really seeing a loop here?

**Comment by icarito** [comment]
It could be! I tried loggin into notification@publiclab.org mailbox but it didn't let me because it didn't recognize my location - I had the same idea in mind - maybe you have better luck?

**Comment by namangupta01** [comment]
This is very strange. I think I need to figure out in more depth how mailman works internally and what we can do to resolve this.

**Comment by namangupta01** [comment]
So, I have found a resolution here. We are storing `message_id` in comment table which stores the `message_id` of the mail received. `message_id` is unique for every mail so the problem of getting posted the same mail will be resolved after using the condition of `message_id`.

**Comment by jywarren** [comment]
Oh, that's great. Thanks for looking into it! I wonder why it wasn't
happening before but at least this will prevent it from happening again.

**Comment by namangupta01** [comment]
I will be creating a pr for this super soon.

**Comment by jywarren** [comment]
thank you naman!!!
