### ISSUE TITLE
Add your location on /people page doesn't work?

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5882]
Just checking @gautamig54 @CleverFool77 on this page: https://publiclab.org/people

I clicked "Add your location" but perhaps because we're not on the profile page, when i clicked "save" in the modal, it didn't seem that my location was actually saved. Can you check on this and confirm? Thank you, this page is looking better and better!

**Comment by gautamig54** [comment]
Yes @jywarren, I will look into this issue.

**Comment by gautamig54** [comment]
Yes @jywarren Add your location on people's page does not saves the user's location. I am not clear about how to go about this. When a user adds a location on the profile page, they cannot change it unless they explicitly delete the lat: and the lon: tags. Maybe that's why we are not able to update the location.
We have @map_lat and @map_lon variables defined in the profile function of the users controller which saves the user's location. Can we make an helper function for this? 
I need help with this issue. @gauravano @SidharthBansal

**Comment by jywarren** [comment]
One thing you can do is modify the controller for this path:
https://publiclab.org/profile/tags/create/1?name=lat:12.41,lon:13

It's under this controller:
https://github.com/publiclab/plots2/blob/master/app/controllers/user_tags_controller.rb

We can have new ones replace previous ones, maybe? You can submit multiple
tags with it, as above!

**Comment by deboragaleano** [comment]
Hi, I'm an Outreachy applicant and would like to claim this issue if it's not taken. Thanks so much!

**Comment by jywarren** [comment]
Sure, this may take some investigating and trial and error! But you can look at how the location input works on a regular post, and we may need to make some code changes to ensure it works in this context as well! Here's an example of a page where it works:

https://publiclab.org/notes/warren/03-01-2019/build-a-sound-generating-coqui-conductivity-sensor

**Comment by deboragaleano** [comment]
I just realized that it's written in Ruby and I'm not familiar with it yet (just saw that the label said JS). In this case, I should leave this issue to another applicant ;)

**Comment by ebarry** [comment]
Is this the same bug that is why i (logged in as an adminstrator) can't add profile tags on other people's accounts?

**Comment by ebarry** [comment]
I'm going to file this as a new bug, thanks!

**Comment by nstjean** [comment]
My update to fix the profile page tagging doesn't seem to have fixed this issue yet.
- Should "Add your location" button be hidden if the user already has a location entered?
- Or should their location be changed from the new input from the /people/ page?

I'll get this working with the javascript functionality that now exists.

**Comment by jywarren** [comment]
I guess hidden makes sense. Thanks a lot!!!!

**Comment by nstjean** [comment]
Ok! I'll get this working.
