### ISSUE TITLE
Checking on test running in parallel processes

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5886]
Hi @alaxalves after the changes to our tests (https://github.com/publiclab/plots2/pull/5751) which split system tests out, I am trying to find the test output for normal tests. It should be after this line:

https://travis-ci.org/publiclab/plots2/jobs/544942636#L3984

This is the last time we changed this: https://github.com/publiclab/plots2/commit/c9f91d31a8f10e815b54795086197ac5fd00511f

Here's an older test where they failed properly: https://travis-ci.org/publiclab/plots2/builds/518541335#L3926-L3933

I tried breaking a test here: https://github.com/publiclab/plots2/pull/5885 but it did not fail tests. I'm wondering if we've misconfigured something that is causing normal tests not to run.

Do we need to be running `rails test -d` as in https://github.com/publiclab/plots2/blob/master/doc/TESTING.md ? I'm hoping this issue is quite recent, but the timing uncertainties caused by our system tests seem to have obscured this issue.

**Comment by jywarren** [comment]
And sorry to keep tagging you in on this project - i appreciate your expertise on these configurations!

**Comment by alaxalves** [comment]
> And sorry to keep tagging you in on this project - i appreciate your expertise on these configurations!

No problem at all @jywarren I'm just happy to help. Check out https://github.com/publiclab/plots2/pull/5884, I'll investigate this issue there.

**Comment by jywarren** [comment]
OK, it looks like #5885 now has tests enabled, and quite a few are failing. I'm going to revert the original test break I did intentionally, and start to try to address the remainder so we get back to a state where all tests are running and reporting properly, and passing.

**Comment by jywarren** [comment]
We are all good here!
