### ISSUE TITLE
UI Improvements Planning Issue : tag/tagname page 

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5889]
#### Current Design 
![ezgif-4-efcfcf93f14c](https://user-images.githubusercontent.com/26685258/59403385-0e9e3f80-8dc0-11e9-81b2-3189d78f579e.gif)

#### Draft mockup design 
![PublicLab mockups](https://user-images.githubusercontent.com/26685258/59403573-c59abb00-8dc0-11e9-8950-7612725da532.png)

#### New style guide design

![Public Lab Style Guide Draft](https://user-images.githubusercontent.com/26685258/59403269-9a639c00-8dbf-11e9-853a-9c30deeb809c.png)

**Comment by CleverFool77** [comment]
Hi @gautamig54 @jywarren I saw two designs as per earlier draft and new style guide. So may I know which one will be the one that will be implemented ?

**Comment by gautamig54** [comment]
Haha @CleverFool77 We opened the issues at the same time. I have added the checklists according to the new design. Look at #5890

**Comment by gautamig54** [comment]
I think we need to implement the new style guide design.
