### ISSUE TITLE
UI Improvements Planning Issue : Profile Page

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#5891]
<img width="314" alt="Capture" src="https://user-images.githubusercontent.com/35326753/59406255-17484300-8dcb-11e9-8de4-46c4161b370a.PNG">

**Checklist**

- [x] Divide page into two sections @CleverFool77 
- [x] Add location map @CleverFool77 
- [ ] Add the tags 
- [ ] Add edit option, add tags option button to show info @CleverFool77 
- [ ] Add the type dropdown as in the individual tags page sorting the cards as per the questions, wikis, notes, liked, comments and barnstars (not in the design)
- [x] Add cards similar to those on /tags page @CleverFool77 

Sidebar

- [x] Add profile image with the user info @CleverFool77 
- [x] Add "add tags", "add location" and edit profile options. @CleverFool77 
- [x] implement an ellipses which might contain options like "follow", rss feed, link social media etc. @CleverFool77 
- [x] Add the # of research notes, comments, wiki edits, questions asked or answers posted etc. @CleverFool77 
- [ ] Refine sidebar and style it

cc: @CleverFool77

**Comment by CleverFool77** [comment]
Hi @gautmig54
Let's wait a bit for profile page. We still have questions, search and tags page right now. We'll. Move on to this when they are on verge of completion. What do. You say. 
Thanks!!

**Comment by gautamig54** [comment]
Yea you're right. I just opened up this issue. We can  work on this one later.

**Comment by chaurasia-namrata** [comment]
hi, is this project open and can i join?

**Comment by CleverFool77** [comment]
Hi @jywarren @gautamig54 Should we start with profile page now ?

**Comment by CleverFool77** [comment]
hi @jywarren The current design have col-9 and col-3 grid. 
But I wanted to ask some doubts about new design. 
In new design. The second column does look like col-3 but the column one doesn't look like one which is taking col-9 of grid.
So What would be the column spans for it. Any idea @gautamig54

**Comment by jywarren** [comment]
I think in the new design, it seems like a 6/4 split. What do you think of doing that?

**Comment by CleverFool77** [comment]
Oh great !!! Looks like we have much margin from right side in new design. I'll start off with this then.
Thanks !!

**Comment by CleverFool77** [comment]
HI @gautamig54 We have already started off with profile page. You can take whichever checklist you are interested in and start off the work.
Thanks !!

**Comment by CleverFool77** [comment]
Hi @Jeff So I was working on tags part. The design for profile page is not there in draft style guiden ppt. So Can I know the source where we have this design , so I can have closer and clear look into buttons and various parts.

**Comment by gautamig54** [comment]
Hi @CleverFool77 @jywarren. Sorry for not being active in the past week due to major health issues. I am fine now and will resume working now. 
Kindly accept my apologies.

**Comment by gautamig54** [comment]
@CleverFool77 Can we divide it as where you implement the left side and I'll do the right side. Sounds good?

**Comment by CleverFool77** [comment]
Right now, right side is not clear yet like buttons and all. Maybe we should wait a bit for clear design. Till then we can work on cards and @user has parts. Even for tags part, we have to wait a bit. As there is place where tags would be shown but no place to add the tags field.

**Comment by CleverFool77** [comment]
So in that if you wish to take the right side, then sure. Go forward.

**Comment by CleverFool77** [comment]
Hi @gautamig54 @jywarren Can I know the source for the clear image of draft for profile page. The image is blurry and the Public lab style draft doesn't have this design.

**Comment by CleverFool77** [comment]
HI @jywarren The design in Publiclab mockup slides doesn't have details for the buttons and many other stuff. Can We discuss it a bit ?

**Comment by CleverFool77** [comment]
Maybe we can have a discussion about it tomorrow during open call ?

**Comment by jywarren** [comment]
Also @chaurasia-namrata we'd love your help! Maybe this is not quite ready yet but we could use your help on any number of other issues in design: https://github.com/publiclab/plots2/labels/design

**Comment by jywarren** [comment]
Hi all - this page design was developed just before the style guide, so perhaps it needs another draft where we reconfigure it slightly to match the style guide where it's quite different. 

The mockup is in the general Mockups presentation: https://docs.google.com/presentation/d/1TCZoTfuhamRVrUak8aDgqJAwSgyhRtZg2Pgacl2_4zc/edit#slide=id.g5a9109bb88_1_4

It was last published here: https://publiclab.org/notes/warren/04-22-2019/user-interface-projects-update-and-dial-osc-project-recap

Does someone want to make a copy in the Mockups doc and try to re-apply Style Guide recommendations to update this? I think it'll mostly affect the sidebar.

**Comment by jywarren** [comment]
And, +1 open call!

**Comment by CleverFool77** [comment]
Cool!!! Lets discuss it a bit during opencall tomorrow regarding the refinements in sidebar and other stuff which is supposed to be included.

**Comment by gautamig54** [comment]
Sure! We can have a discussion about the page on open call tomorrow!

**Comment by CleverFool77** [comment]
HI @jywarren Regarding long cards, we are classifying on the basis of tags like `water-quality` and etc. Below this, we have active topics and all. So Below this, will we be still having cards for notes, questions and etc like we have right now ?

**Comment by CleverFool77** [comment]
HI I was trying the cards section and got something like this - 
![Screenshot from 2019-07-09 18-52-37](https://user-images.githubusercontent.com/26685258/60891364-cc5f0580-a27a-11e9-8946-d2e0f1978ce8.png)

For now, I'm showing the cards for all the tags but I guess as per style guide, I have to show the topic cards for most active topics ? And Is there any limit on numbers too ?

**Comment by jywarren** [comment]
I think we would only show the topics cards, and no individual posts
(although in each topic card we could show the posts by this author?)

And we might say "5 more posts by @username" below? That could link to
these tag/author specific listings!
https://publiclab.org/tag/gsoc/author/warren

What do you think? That keeps the complexity of this page a bit lower, it's
more of an overview and then you can go to the tag/author listings to see
more.

**Comment by CleverFool77** [comment]
So we would be having lots of cards considering we have lots of topics used by author. Or do you want the topic cards to be made for few topic ? like most active topics ? But then what about those topics notes which doesn't have most active topics ? Then can we never see them considering we don't have individual cards for all the notes ?

**Comment by jywarren** [comment]
Ah, hmm. What do you think about:

1. showing cards for only topics the author is subscribed to
2. having a section at the bottom listing (in badge format) all the tags
the user has used, where each badge leads to the same tag/author URL, but
we don't show the whole topic area?

Would this be confusing or weird? I think you're totally right about so
many topics for most people. So makes sense to highlight what topics
they've subscribed to -- it's kind of like, what forums are they part of?
Versus just what topics have they posted about, which is a much larger
number.

**Comment by CleverFool77** [comment]
Hi @gautamig54 @jywarren Regarding tags ablove the topic cards, How do you wanna decide which tags to be shown there.
1. The tags which users adds to its profile to be shown to others ? its kinds tags of interest for profile.
2. Most used tags based on following count ?

**Comment by jywarren** [comment]
Ah, the "recommended" ones? maybe most used tags as you say, or:

3. most occurring tags based on posts liked, or recently commented on (this
is a tough query but maybe worthwhile?)
4. tags from posts you've published?

in any case maybe we need a `user.recommended_tags` method that we can
adapt so we can draw on multiple sources for what "recommended" means?

**Comment by CleverFool77** [comment]
So out of all these points, which one seems most apt ?

**Comment by CleverFool77** [comment]
We can have tags on the basis of one of these points only right ? 
According to me we should have tags which seems to be of profile user's interest should be shown. What do you think ? 
And below topic cards, we can have another potion of tags, For that we can have most used tags I guess ? 

So we can two rows of tags 
- One above topic cards - which is of user's interest of tags
- Below the topic cards - which is most used tags

**Comment by jywarren** [comment]
Yeah, this sounds right. But note that if we base it on tags from posts
you've made, then for newcomers there won't be any if they haven't posted.
So perhaps we need to pull from multiple sources and take the top 5 or
something, to account for different edge cases?

**Comment by SidharthBansal** [comment]
This is EPIC
The profile revamp is awesome!!!
Well done!!! Checking this project. Thanks @CleverFool77

**Comment by CleverFool77** [comment]
Hi Sidharth.
Thanks !!!
The work is on the way. We are solving some bugs and other stuff. And then soon it would be ready.
cc: gautami

**Comment by SidharthBansal** [comment]
Oh great. Keep it up.
Great work so far
