### ISSUE TITLE
Dropdown checkbox filters on dashboard

### ISSUE THREAD

**Issue by michelelong** [publiclab/plots2#5895]
I noticed on the dashboard the dropdown checkboxes to filter which updates should show doesn't work. I can PR to fix this if you like.
![filter-dropdown](https://user-images.githubusercontent.com/50340123/59464389-e9282a80-8ded-11e9-8208-69b8019f6ca9.png)

**Comment by jywarren** [comment]
Oh that would be great! Thank you!

**Comment by jywarren** [comment]
Closing this up as noted in the PR!
