### ISSUE TITLE
Combine templates for email digest and settings digest

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5908]
We originally made this digest page to test out the display of email digests: 

Using this template: https://github.com/publiclab/plots2/blob/master/app/views/subscriptions/digest.html.erb

But that wasn't well documented, and now email digests are run from a different template:

https://github.com/publiclab/plots2/blob/master/app/views/subscription_mailer/send_digest.html.erb

Now we have somewhat redundant templates. We've done a lot of work to make sure the email digest shows the right information. Let's now make the page at https://publiclab.org/subscriptions/digest show the same information, which will make debugging what the email digests show much easier.

Thanks!

**Comment by jywarren** [comment]
And we'll then be able to style them better too! We should be able to take a screenshot in https://github.com/publiclab/plots2/blob/master/test/system/screenshots_test.rb if we want as well.

**Comment by snpd25** [comment]
@jywarren , I would like to work on it. But will require some help to get started on it. Thanks :)

**Comment by mittal-parth** [comment]
@jywarren So what I understand from this is that we need to make /subscriptions/digest work - by creating a common template for email digest and settings digest? (In my testing /subscriptions/digest never showed my subscribed topics - always asked to subscribe to some more topics)

**Comment by mittal-parth** [comment]
@TildaDares I would like to work on this if my understanding is correct. Thanks!

**Comment by TildaDares** [comment]
@mittal-parth Yeah your understanding is correct. You can work on it!

**Comment by jywarren** [comment]
> * When it needs to be displayed on the normal website, this would have to change since `ActionMailer:...` wont work. How do we ensure that the correct link is used for settings and email digest respectively using the same template?

Great question, @mittal-parth -- we have to do that because links in the emails won't be served at publiclab.org, so we can't use relative links. But for this page, it will be at PublicLab.org, so we can just skip the hostname/root and start with `/` to form URLs, and they'll be interpreted as relative links by the browser. Does that make sense?

Regarding wiki.latest.title, I think that's the best practice vs. wiki.title, because it takes the title of the latest revision. It's not common for the title to change but just in case it does. 

Thank you!!!

**Comment by mittal-parth** [comment]
Yes @jywarren that makes sense. However, I still don't know how we can ensure the links switch for the Web page and the email from the *same template*.

Ok cool. Thank you!

**Comment by mittal-parth** [comment]
Hi @jywarren !
This is how the subscriptions/digest was intended to be (with slight modifications to some redundant stuff)

![image](https://user-images.githubusercontent.com/76661350/151217532-51e0a486-2b5a-493e-89f7-4011c6fb1dee.png)


This is how the current mailer looks like


https://user-images.githubusercontent.com/76661350/151217912-35af5f68-4ea0-4a1b-b612-d2f65bbd821e.mp4


Few questions:
Which look should be kept considering that the web page also indented to sort the nodes based on certain queries?

If we do intend to keep the sorting functionality:
 (a). Should the column headings be mentioned in the mailer as well?
 (b). Should the _Likes_ and/or _Page Views_ column be kept or removed?
 (c). _Last Edited_ be changed to _Published_?

cc @TildaDares 
Thank you!!

**Comment by jywarren** [comment]
I think as long as it's clear how things are sorted, we don't need to implement sorting on the page. I think likes/pageviews can be removed. Last edited... i wasn't sure, sometimes people edit something old, and then it shows up again, so then it wouldn't be quite right to call it "Published" would it? Or could it say "Last published"?

Thank you!
