### ISSUE TITLE
Rebase gone wrong?

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#5911]
![2019-06-17-12-12-publiclab org](https://user-images.githubusercontent.com/17081074/59592808-707ce300-90f9-11e9-9801-20f247eff1fc.png)

I am working on #5904 and I will fix this with that but wanted to note here for people to be  a little more careful when doing a rebase and possibly check afterwards all the conflicting files and pages look good to avoid something like this going to production in future. Thanks all

**Comment by jywarren** [comment]
I'm so sorry @cesswairimu -- i should have caught this with the new screenshots! I'm still getting used to them, but I noticed some CSS features don't work in the screenshot tests, so I wrongly assumed this had been working fine locally and was only broken in the screenshot tests. We're learning more about how they work so I'll trust them a bit more now to tell us when layouts look wrong. 

noting: ca1011840ac47940f4295a7a8679280cf74828b9 https://github.com/publiclab/plots2/pull/5802

Oh you know what? This didn't have screenshots enabled, so I did actually see them generated on subsequent PRs, but thinking back, I am not sure we had a moment to see automated screenshots before the PR was merged. From now forward this will be easier to catch AND we'll know to trust the screenshots more. 

Thanks for the catch @cesswairimu !

**Comment by jywarren** [comment]
Ah no, looks like it was this commit: https://github.com/publiclab/plots2/commit/0a5a061ae98659879a4b71d7634415c53cf15284#diff-e8d970f814aa8ace0c4be3778174c22bR12

I think this was just a somewhat older PR that caused trouble when rebasing. But again, we'll watch out with screenshot tests now. Thanks.

**Comment by cesswairimu** [comment]
No worries, and yeah the screenshots are really awesome and will help avoiding this. Thanks Jeff
