### ISSUE TITLE
Drafts should not trigger email notifications for mentioned @usernames 

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5914]
Link to #3845, but here's the code:

https://github.com/publiclab/plots2/blob/087d1df8968d58cae97d0d30d45847d55c9944d9/app/models/node.rb#L219-L225

I think probably this is the key section:

https://github.com/publiclab/plots2/blob/087d1df8968d58cae97d0d30d45847d55c9944d9/app/models/node.rb#L644-L646

We can probably use `node.draft` as a condition:

https://github.com/publiclab/plots2/blob/087d1df8968d58cae97d0d30d45847d55c9944d9/app/models/node.rb#L624

Love some help with this one!

**Comment by jywarren** [comment]
And as a follow-up, we /should/ send the notifications when it's finally published!

**Comment by StlMaris123** [comment]
Hi @jywarren on modifying the node model, do we have access to the params from the model?

**Comment by jywarren** [comment]
I don't think so, but we can look at where .notify() is run from and make
the modification there?

**Comment by ericlarosa** [comment]
@jywarren is help still needed here?

**Comment by swathi-0901** [comment]
hello, I would like to work on this issue can I?
