### ISSUE TITLE
Comments don't appear on questions, and answers don't appear on notes

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#592]
### What happened just before the problem occurred

I responded to this note: https://publiclab.org/notes/AndrewJamesLaplante/06-12-2016/question-how-to-rename-a-set

Then i found it at the new https://publiclab.org/questions -- as https://publiclab.org/questions/AndrewJamesLaplante/06-12-2016/question-how-to-rename-a-set

And responded to it there too. But comments don't appear on questions, and answers don't appear on notes, so there are kind of two "versions". @ananyo2012 , thoughts on this, or potential solutions? 

Also, are email notifications sent on answer creation?

**Comment by ananyo2012** [comment]
@jywarren Yes currently there are two versions. Please don't use the developing Q & A system for responding to questions. The previous Questioning system isn't scraped off yet and the work on Q & A isn't completed yet. The commenting system is still in progress. After it gets complete I will replace all the links to questions to the new Questions page url.

**Comment by ananyo2012** [comment]
I did it so that user can still use the current Questioning system doesn't gets hampered while the development is in progress.

**Comment by ananyo2012** [comment]
Also email subscriptions aren't working now. I will work on them after the mid term evaluations.

**Comment by jywarren** [comment]
That's fine - maybe an alert notice at the top of these pages is a good
idea until the features are ready to use? Thanks!

**Comment by ananyo2012** [comment]
Well I didn't include any link in the topmost navigation bar for visiting
the questions. So is it necessary? I think regular users won't be bothered.
ᐧ

**Comment by jywarren** [comment]
Yeah, I guess it'll be fine. I just worry about I'll formed data getting
into the database and mucking up your future work... just paranoid I guess.
:-)

Will comments and answers both be possible, in your plan? Or will questions
allow only answers?
On Jun 17, 2016 3:39 PM, "Ananya Maiti" <notifications@github.com> wrote:

Well I didn't include any link in the topmost navigation bar for visiting
the questions. So is it necessary? I think regular users won't be bothered.
ᐧ

On Fri, Jun 17, 2016 at 11:57 PM, Jeffrey Warren <notifications@github.com>
wrote:


> That's fine - maybe an alert notice at the top of these pages is a good
> idea until the features are ready to use? Thanks!
> On Jun 17, 2016 1:56 PM, "Ananya Maiti" <notifications@github.com> wrote:
>
> > Also email subscriptions aren't working now. I will work on them after
> the
> > mid term evaluations.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/publiclab/plots2/issues/592#issuecomment-226837717>,
> > or mute the thread
> > <
>
https://github.com/notifications/unsubscribe/AABfJ4vlupKWzDDBwTtw1cnMz2qkcvGqks5qMt_HgaJpZM4I4exP

> >
> > .
>
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/publiclab/plots2/issues/592#issuecomment-226845402>,
> or mute the thread
> <
https://github.com/notifications/unsubscribe/AKACRywUx9RyY7PyV2VsH_09_v87yXhXks5qMub1gaJpZM4I4exP
>

> .
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/592#issuecomment-226863232>,
or mute
the thread
<https://github.com/notifications/unsubscribe/AABfJ58c7TNe1jp1QxbF0GR70NAWpM0Oks5qMvf7gaJpZM4I4exP>
.

**Comment by ananyo2012** [comment]
Well Thanks anyways Jeff! :smiley: Yeah Questions will have both comments and answers as per the new design. Once I complete my initial work I will post a research note on this.

**Comment by jywarren** [comment]
Super, thanks again and I'll be a bit less in touch next week, then offline
the week after. Great work!

**Comment by ananyo2012** [comment]
@jywarren This can be closed now. I will post a research note on it as soon as you publish the changes on the site.

**Comment by jywarren** [comment]
Great. As the Barnraising event is this weekend, I'm not sure it it'll
happen until Tuesday, but we'll see. Thanks!
