### ISSUE TITLE
Check for logged_in status on /settings

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5923]
It looks like we aren't checking if people are logged in on https://publiclab.org/settings, causing an error when you load the page without logging in. We should catch and redirect; the controller is here:

I don't actually see a method for settings in https://github.com/publiclab/plots2/blob/master/app/controllers/users_controller.rb -- but routes.rb does say there is one. Maybe it's just an HTML file with no controller action? Probably. 

https://github.com/publiclab/plots2/blob/master/app/views/users/settings.html.erb

So maybe a change on this line would just enable a login check even though we don't have an explicit controller action:

https://github.com/publiclab/plots2/blob/master/app/controllers/users_controller.rb#L3

If not, we should just add this to make it explicit:

```ruby
def settings
end
```

**Comment by yprasant0** [comment]
@jywarren @IshaGupta18  is this issue still available, being new here I would like to take up this issue. Thanks

**Comment by jywarren** [comment]
We'd love your help! Sorry for the slow reply!!!

**Comment by Uzay-G** [comment]
Hey! This error is still present so I will reformat this as an fto!

**Comment by jywarren** [comment]
This was solved, thanks all! https://github.com/publiclab/plots2/blob/main/app/controllers/users_controller.rb#L3
