### ISSUE TITLE
Search not working.

### ISSUE THREAD

**Issue by bronwen9** [publiclab/plots2#5927]
Currently, attempts to use the search bar lead to an error page. 
<img width="1187" alt="Screen Shot 2019-06-20 at 1 37 29 PM" src="https://user-images.githubusercontent.com/8331717/59869151-a7086700-9360-11e9-97b3-3e8bc2f18438.png">

**Comment by gauravano** [comment]
Hi @bronwen9, this issue is resolved and fix is pushed to production so you shouldn't face any issue now. Please give a try and let us know. Thanks!
