### ISSUE TITLE
Move "follow author" and "Flag" buttons under dropdown menu

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5932]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

### 🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step
  - [ ] **🙋 Claim this issue:** Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

  - [ ] **📝 Update:** 
On pages like https://publiclab.org/notes/warren/02-28-2019/call-for-summer-of-code-2019-proposals, we have a small tool menu that looks like this:

![image](https://user-images.githubusercontent.com/24359/59881912-c7dfb500-937e-11e9-8b1c-94a38c8dd623.png)

Let's further minimize it by putting the "follow author" and "flag" buttons inside that menu! This should be a pretty easy fix. 

The two buttons in question are here:
https://github.com/publiclab/plots2/blob/21261a5e4c19e0756f14addf908ce34d00c8366f/app/views/like/_like.html.erb#L10-L15

Update apps/views/like/_like.html.erb in the plots2 repository.
Place the above buttons inside the popover section using the above statements. Place it above the delete buttons starting at L#50. 

  - [ ] **💾 Commit your changes**

 - [ ]  **🔀 Start a Pull Request.** There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

You can also edit files directly in your browser and open a pull request from there.

  - [ ] **🏁 Done** Ask in comments for a review :)

### 🤔❓ Questions?
Leave a comment below!

### Is someone else already working on this?
We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seem stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

**Comment by jywarren** [comment]
@gautamig54 @CleverFool77 maybe this would be a pretty easy FTO for someone? Would a recent FTO completer want to open their own FTO using this? 

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by gautamig54** [comment]
@jywarren I have updated the issue. Kindly review @publiclab/reviewers !

**Comment by jywarren** [comment]
Looks great! Want to relabel it? Thank you @gautamig54 !!! This is awesome.

**Comment by mohamed-elalem** [comment]
Can i claim this one?

**Comment by rexagod** [comment]
Go ahead, @mohamed-elalem! Let us know if you face any problems whatsoever. Thanks!

**Comment by mohamed-elalem** [comment]
@rexagod I opened a pull request for this issue, kindly check #5939.
