### ISSUE TITLE
Change colour of social-media icons from black and white to original

### ISSUE THREAD

**Issue by aSquare14** [publiclab/plots2#5936]
<img width="1437" alt="Screenshot 2019-06-22 at 8 35 55 AM" src="https://user-images.githubusercontent.com/22938709/59958742-dd60f600-94c8-11e9-8ae1-6047747a6d6e.png">

Change the colour of social media icons to look like this 

<img width="243" alt="Screenshot 2019-06-22 at 8 37 40 AM" src="https://user-images.githubusercontent.com/22938709/59958757-07b2b380-94c9-11e9-916f-fb3a9e55370c.png">

**Comment by gauravano** [comment]
The icons are part of the feature so their code is stored in DB. But, let's see how the page looks after introducing colors.

**Comment by jywarren** [comment]
Cool -- also, let's try to stay synced with the style guide process! Thank
you for the input!
https://publiclab.org/notes/warren/05-07-2019/introducing-a-draft-style-guide-for-public-lab

**Comment by gauravano** [comment]
![Screenshot from 2019-06-25 01-09-06](https://user-images.githubusercontent.com/20878070/60046788-d7942c00-96e5-11e9-8cb9-5ebe4e9c4bbc.png)

@aSquare14 @jywarren how's it looking?

Also, pasting style guide section for reference:
![Screenshot from 2019-06-25 00-47-59](https://user-images.githubusercontent.com/20878070/60046836-f5619100-96e5-11e9-80ca-f43ff920294a.png)

**Comment by jywarren** [comment]
Hi! I think we'd be OK with the colored icons if you want to adjust them - but please keep in mind that we will be doing a front-page redesign incorporating elements from the style guide pretty soon, so I don't want folks to feel bad if changes made now are overwritten in a few weeks or months. Just a heads up, and thank you so much for your interest in this!

**Comment by gauravano** [comment]
Cool. 

 Here's the gist for the code - https://gist.github.com/gauravano/db813bbdec1b7e680d6b8882092b02e0

So, whoever takes on this issue have to first create a feature by name `home-intro` by logging in as admin and then visit localhost:3000/features and create feature from there using the code from Gist.
Edit and Save the feature if you're not able to see changes at localhost:3000/home.

After that, apply colors to all the social icons including Instagram too. you can use image for instagram. 

Thank you!

**Comment by aSquare14** [comment]
Cool ! Looks good to me and @jywarren your point is valid !

**Comment by enviro3** [comment]
Hi @aSquare14, @gauravano, and @jywarren, would it be okay if I take a crack at this? I don't mind if any changes I make are overwritten later in the new re-design that is coming. Let me know, thanks :)

**Comment by gauravano** [comment]
Hi @enviro3, actually, we'll keep the black and white icons as it goes with the current page design. So, closing this issue. Although, thanks for your interest in this one :+1:
