### ISSUE TITLE
Replace TAGS with TOPICS

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5945]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

### 🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step
  - [ ] **🙋 Claim this issue:** Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

  - [ ] **📝 Update** 

  - [ ] **💾 Commit your changes**

 - [ ]  **🔀 Start a Pull Request.** There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

You can also edit files directly in your browser and open a pull request from there.

  - [ ] **🏁 Done** Ask in comments for a review :)

### 🤔❓ Questions?
Leave a comment below!

### Is someone else already working on this?
We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. If someone seem stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

**Comment by cfinn16** [comment]
Hi! Can I work on this?

**Comment by CleverFool77** [comment]
Hi you can, but I haven't updated the details for this issue yet. Wait for some hours and I'll update this.
Thanks

**Comment by cfinn16** [comment]
Sounds good — I'll wait for your update. Thanks!

**Comment by CleverFool77** [comment]
HI @jywarren I don't seem to find the file for this code.

**Comment by CleverFool77** [comment]
Hi @cfinn16  If you are  interested, you can look into this first timer issue https://github.com/publiclab/plots2/issues/5976
Thanks !!!

**Comment by CleverFool77** [comment]
I'll open a different first timers issue for you next.

**Comment by cfinn16** [comment]
Hi @CleverFool77, sorry for my delayed response here. I've been traveling the past few days and will be until Friday. I'll keep my eyes peeled for a new first timer issue then that I can jump in on. Thanks!

**Comment by CleverFool77** [comment]
Great !!!!

**Comment by newbazz** [comment]
I would like to work on this issue
