### ISSUE TITLE
Topics card display styling refinements

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5949]
@gautamig54 @CleverFool77 just noting that there are some oddities about the topics cards on https://publiclab.org/tags - would you mind taking a look?

![image](https://user-images.githubusercontent.com/24359/60125498-e87e8500-9759-11e9-9352-d90b85528ac5.png)

I think maybe the profile picture should:

1. be a grey circle if there's no profile picture, so the layout is consistent
2. be float:left ?
3. should the other elements be display:block?

I was able to get it looking a little better with:

```html
<div>
  <img class="rounded-circle" id="profile-photo" style="width:20px; height:20px; margin-right:8px; display: block;float:left;" src="/i/33131.jpg">
  <p style="display: block;">
    <a style="color: inherit;" href="/notes/it13/06-22-2019/as-per-my-ndvi-output-like-this-how-can-we-calculate-endvi-or-ndvi-image">As per my ndvi output like this How can we calculate  endvi or ndvi image ?</a>
    <span style="display: inline-block; margin-left: 10px;color: #808080;">by <a style="color: #808080;" href="/profile/it13">@it13</a></span>
  </p>
</div>
```

![image](https://user-images.githubusercontent.com/24359/60125600-2b405d00-975a-11e9-87e6-6f04c6ca874e.png)

**Comment by CleverFool77** [comment]
Hi @jywarren This looks good. I'll solve some of the parts and open `first-timers`-only` for some.
Thanks !!

**Comment by jywarren** [comment]
Complete!!!
