### ISSUE TITLE
Figure out way to embed Leaflet Environmental Layers map in a wiki with specific layers showing

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5950]
@ananyaarun @sagarpreet-chadha - Folks are interested in showing specific layers in an inline or leading map, so, having some layers "default on" -- on pages like:

* https://publiclab.org/wisconsin
* https://publiclab.org/puerto-rico
* https://publiclab.org/one-cranston

Some are "lead maps" at the top of the page, and some are in the sidebar, and some are inline. Let's start with inline maps.

![image](https://user-images.githubusercontent.com/24359/60114093-173c3180-9741-11e9-8c41-c8efba623c6a.png)
![image](https://user-images.githubusercontent.com/24359/60114107-1f946c80-9741-11e9-8af3-15570e325982.png)

Here's an inline map:

![image](https://user-images.githubusercontent.com/24359/60115776-b4e53000-9744-11e9-9282-bc5f42e330d5.png)

Generated with `[map:content:41.8:-71.4]`

So, I note that LEL can generate these links with layers enabled: https://publiclab.github.io/leaflet-environmental-layers/example/#13/41.8173/-71.4147/BL2-Purple-windrose-AQI

This one shows 3 layers:

![image](https://user-images.githubusercontent.com/24359/60134715-22598680-976e-11e9-8894-bf5ed371cefb.png)

Could we make an embed code generator for this, as an easy first step? From the gh-pages demo? 

Then, later, we can come up with a way to have any instance of LEL able to generate some kind of shortcode for within the PL ecosystem. This could be a follow-up, but it might follow a format like, maybe, `[map:https://example.com/LEL-map-path]` or something, which would just be a simple way to display any LEL map... we can discuss later!

**Comment by sagarpreet-chadha** [comment]
This is super cool feature 😄!

**Comment by jywarren** [comment]
Solved in https://github.com/publiclab/plots2/pull/6204#issuecomment-535252025 !!!
