### ISSUE TITLE
Speed difference between navbar tag search and /tags tag search

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5951]
Using these two types of tag search, the navbar search is much slower than the `suggested` route!

![image](https://user-images.githubusercontent.com/24359/60111108-54052a00-973b-11e9-8645-a7ddf5e43e15.png)

The navbar one uses: https://publiclab.org/api/srch/tags?query=coqui

The `suggested` one lower down is faster, and uses (over XHR): https://publiclab.org/tag/suggested/coqui

Here's the navbar code: 

https://github.com/publiclab/plots2/blob/8b691a8e3213b48652f3e256a3a4a33c14526c39/app/api/srch/search.rb#L276-L294

Suggested: https://github.com/publiclab/plots2/blob/8b691a8e3213b48652f3e256a3a4a33c14526c39/app/controllers/tag_controller.rb#L386-L393

Comparison of skylight traces:

Navbar: https://oss.skylight.io/app/applications/GZDPChmcfm1Q/1561487700/6h/endpoints/Srch::Search%20%5BGET%5D%20srch%2Ftags

Suggested: https://oss.skylight.io/app/applications/GZDPChmcfm1Q/1561487520/6h/endpoints/TagController%23suggested?responseType=json

Both go to:

https://github.com/publiclab/plots2/blob/8b691a8e3213b48652f3e256a3a4a33c14526c39/app/services/search_service.rb#L83-L88

So why the difference?

**Comment by jywarren** [comment]
What's going on with our API? It's so inefficient!!! https://oss.skylight.io/app/applications/GZDPChmcfm1Q/1561487700/6h/endpoints/Srch::Search%20%5BGET%5D%20srch%2Ftags

**Comment by jywarren** [comment]
The API call averages 3.5 seconds. The tags controller suggested action averages 150 milliseconds!!!

![image](https://user-images.githubusercontent.com/24359/60142765-47a7be00-9789-11e9-8d71-f53fd5f85139.png)

**Comment by jywarren** [comment]
Maybe something here? https://github.com/ruby-grape/grape/search?q=slow&type=Issues

**Comment by newbazz** [comment]
@jywarren I would like to take this issue up if no one is working on it.

**Comment by jywarren** [comment]
For sure, but this may be a bit of a mystery -- not as easy as an issue
where there's a known solution. Just stay in communication in our chatroom
and we'd love your help! Thank you!

**Comment by jywarren** [comment]
Noting we're switching the URL to the faster endpoint because of https://github.com/publiclab/plots2/issues/6835, in https://github.com/publiclab/plots2/pull/6840
