### ISSUE TITLE
Porting LBL and LBLD to Bootstrap 4

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#5955]
@jywarren , 
Can you put some links to merged PR's or some documentation to help me get started here. Thank You!

**Comment by jywarren** [comment]
Sure! here are some:

https://github.com/publiclab/plots2/issues/5612
<https://github.com/publiclab/plots2/pull/>

https://github.com/publiclab/plots2/issues/1716

I hope these help!

Sagarpreet, do you think you could find some time to prioritize this one -
specifically for the MapKnitter layer?
https://github.com/publiclab/leaflet-environmental-layers/issues/112

We're going to be relaunching MapKnitter pretty soon and I was hoping to
include this in the update!
