### ISSUE TITLE
Make wiki/note page headings more minimal, based on the new style guide

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5956]
@gautamig54 @CleverFool77 I was working in the [style guide draft](https://publiclab.org/notes/warren/05-07-2019/introducing-a-draft-style-guide-for-public-lab), and have been trying to see how we can keep a minimum of extra stuff in the heading, as it's currently so overloaded: 

![Screen Shot 2019-06-27 at 7 34 10 PM](https://user-images.githubusercontent.com/24359/60307425-8ddc5900-9912-11e9-8220-c600083ea946.png)

So I tried putting everything in a `...` menu just under the title. But then i thought, it's bit too hidden maybe? So I tried a row of buttons in the sidebar:

![image](https://user-images.githubusercontent.com/24359/60307344-350cc080-9912-11e9-99d9-0d17469b3356.png)

Any thoughts? Ideas? Preferences?

**Comment by CleverFool77** [comment]
I seem to miss out this.
Thanks for assigning. @jywarren

**Comment by CleverFool77** [comment]
We have been using ellipses in all cards too.Instead of ellipses, row of buttons and menu buttons looks much better. 
How about earlier, letting all the this data remain hidden, then we can trigger the show class with one menu button.
So unless someone want to edit the note or wiki, they need not see these buttons.

**Comment by gautamig54** [comment]
We have been using ellipsis for text over-riding. Like in extra long tags. We ca keep it to ellipsis and display the full text on hover. What do you think @CleverFool77 ?

**Comment by jywarren** [comment]
Hover could be an issue for smartphones, but I like the idea -- maybe on click? So, the first button would be a `...` button, but round, and clicking it shows all the other buttons in that row?

**Comment by jywarren** [comment]
Now we have a very minimal set of sidebar buttons which can contain LOTS of extra stuff, we can get back to making the wiki/note page headings more minimal as in the style guide:

https://publiclab.org/notes/Bronwen/09-20-2019/online-live-builds-make-magazine-in-october is an example page. 

Here's what it looks like now:

![image](https://user-images.githubusercontent.com/24359/65792180-35933e00-e131-11e9-8d99-fa0fbfcac383.png)

The mockup is here:

![](https://user-images.githubusercontent.com/24359/60307344-350cc080-9912-11e9-99d9-0d17469b3356.png)

The `...` menu can now be skipped as that content can go in the new sidebar `...` button, the circular one. For the rest, anything else we are removing to get it minimized can go in the dropdown of the new `...` button as well!

We'd love help with this!

**Comment by jywarren** [comment]
Here's the current wiki page header:

![image](https://user-images.githubusercontent.com/24359/65792419-b4887680-e131-11e9-9942-2014803302dc.png)


So for note pages, it could say:

`by @authorname | Sept 4 2019 | #14142`

For wiki pages, it could say:

`8 authors | 14 revisions | Talk` (each underlined, as a link)

The notes header code is here (it could maybe be broken into a partial template?):

https://github.com/publiclab/plots2/blob/f7683ee7e65f16efab1f6665463f89f2e8bb2882/app/views/notes/show.html.erb#L27-L60

The wiki page header code is here:

https://github.com/publiclab/plots2/blob/f7683ee7e65f16efab1f6665463f89f2e8bb2882/app/views/wiki/_header.html.erb#L30-L108

**Comment by ebarry** [comment]
@joyofsoy, check out this issue which comprehensively redesigns the header on notes and wikis -- that redundant line "read more: publiclab.org/n/######" will definitely be removed.

**Comment by Ugtan** [comment]
I would like to work on the issue @jywarren
