### ISSUE TITLE
The `answered` and `asked` tab doesn't work

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5958]
#### Description

The answered and asked tab seems to have broken and is not working.

![Screenshot from 2019-06-28 17-39-19](https://user-images.githubusercontent.com/26685258/60341376-e6bbf800-99cb-11e9-880a-51b3fb78076e.png)

**Comment by CleverFool77** [comment]
Hi @michelelong  I saw you worked on the one of the tab fix earlier. If you are interested, you can look into this.
Thanks !!

**Comment by michelelong** [comment]
I'll look into it.

**Comment by jywarren** [comment]
Hi! Just noting, I think this is also potentially related to the test issue
in https://github.com/publiclab/plots2/pull/5902, if you're talking about
the tag page! Thanks!

**Comment by michelelong** [comment]
Is there a way to get the count for these two tabs like the others have?

**Comment by gauravano** [comment]
Hi @michelelong, yes, you can do that, here's logic for the profile page https://github.com/publiclab/plots2/blob/master/app/controllers/users_controller.rb#L143-L228 . You'll see in profile.html.erb that we show count for some tabs from the instance variable we use like for Authored, Coauthored, Drafts, etc. Similarly, you can either send the count or if we already have instance variable declared then you can use it to show the count. 

Let me know if you want any help. Thank you!

**Comment by jywarren** [comment]
I believe this is no longer required as per the new profile page design! Thanks!!
