### ISSUE TITLE
error in <blockquote> parsing in Markdown

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5959]
Oddly it looks like markdown blockquotes are getting converted to `<p>` paragraph tags:

![image](https://user-images.githubusercontent.com/24359/60356398-d3466800-999e-11e9-9065-38198c178302.png)

this rendered from the Markdown usage:

```
> Text here
```

We may need to look at whether our markdown parser has changed. Oddly the render method in `comment.rb` hasn't for 4 months, so it seems unlikely to be the issue:

https://github.com/publiclab/plots2/blob/61684ae2fce32b5c53fba23cb7be46dd69867b60/app/models/comment.rb#L413-L425

This needs some further investigation and we might also link to #3889 !

cc @ebarry

**Comment by jywarren** [comment]
Ah, wait! The blockquote code is there, so this is a styling issue!

![image](https://user-images.githubusercontent.com/24359/60356612-68496100-999f-11e9-9d67-905e8065b8d4.png)

Great. So let's check our CSS.

**Comment by jywarren** [comment]
So it'll be in one of these; probably the first! We can check if they've changed, OR we can check if the container for comments has changed and is no longer getting these styles applied:

https://github.com/publiclab/plots2/blob/a3e40c5cb20e94653de20a74e0ac9553c87f0d3a/app/assets/stylesheets/comments.css#L27-L32

https://github.com/publiclab/plots2/blob/63090daa89adcd5124661a6ea41203210575387f/app/assets/stylesheets/style.css#L286-L289

**Comment by jywarren** [comment]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by enviro3** [comment]
Hi @jywarren, I'm a newbie and would love to take a shot at this issue. May I work on this?

**Comment by rexagod** [comment]
Go ahead, @enviro3!
