### ISSUE TITLE
Implement card designs in embedded grids!

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5960]
We have these nice embedded grids that show in iframes, at urls like:

https://publiclab.org/embed/grid/questions:balloon-mapping

They look like this, on an external site like MapKnitter.org : 

![image](https://user-images.githubusercontent.com/24359/60374205-36e98900-99d1-11e9-981a-24fcdfeed291.png)

The "grid" versions don't look as good:

https://publiclab.org/embed/grid/notes:grid:balloon-mapping

Let's have the grid version (with thumbnail) use the new card designs from the style guide! cc @CleverFool77 @gautamig54 what do you think?

**Comment by jywarren** [comment]
cc @cesswairimu this'll look cool and we can feature some balloon mapping blog posts using this, with images!

**Comment by cesswairimu** [comment]
Awesome!!

**Comment by CleverFool77** [comment]
Hi @jywarren This might be a silly question but what is embedded grid. Is it something like grid or nested grid ? :sweat_smile: 
regarding addition of cards, yes we can do this. Is code for this in plots2 code ?

**Comment by jywarren** [comment]
I'm sorry to use jargon! My bad 😄 

Here is some documentation about inline grids; each one can also be embedded on an external site:

https://publiclab.org/wiki/power-tags#Inline+power+tags

the thumbnail grid mode looks like this:

![image](https://user-images.githubusercontent.com/24359/60827738-dbf92400-a17e-11e9-8349-1facd9f7533b.png)

See how the table-style ones have a small "embed" button in the lower right to provide embedding codes, for embedding on other sites like YouTube videos. @cesswairimu did this on the new front page of https://MapKnitter.org!

![Screen Shot 2019-07-08 at 12 50 09 PM](https://user-images.githubusercontent.com/24359/60827778-f7fcc580-a17e-11e9-9bd7-1ae7b7e3fa19.png)

**Comment by Utiwari1999** [comment]
@jywarren and @SidharthBansal I want to work on this issue if it is not closed.

**Comment by coder-cracker** [comment]
@jywarren  and @SidharthBansal I also want to work on this issue..

**Comment by SidharthBansal** [comment]
I think you can work on this

**Comment by jywarren** [comment]
Oh I'm sorry I've already started here! https://github.com/publiclab/plots2/pull/6581

However if you can help me resolve the errors there I'd be super grateful!
