### ISSUE TITLE
Action Cable Testing

### ISSUE THREAD

**Issue by namangupta01** [publiclab/plots2#5969]
Hey, all!
With the merge of #5743 we now have action cable implemented in our system. Next step is to write test so that we are sure that everything is working fine.

There are multiple ways to test action cable. Some of them are:

https://github.com/palkan/action-cable-testing
https://medium.com/@tomekw/unit-testing-actioncable-channels-with-rspec-ca67ca6834af

@jywarren @gauravano what do you think will be a good way to test action cable?

**Comment by jywarren** [comment]
This is a bit outside my expertise, actually! But - if there are indeed
unit tests available, let's start with a few simple ones of those. Then, we
can implement a front-end system test in JavaScript as well. Here's an
example of running JS in a full-stack system test:

https://github.com/publiclab/plots2/blob/a9d4e3048eee72aa3161f8999a6fde5b95443e58/test/system/search_test.rb#L25-L26

**Comment by namangupta01** [comment]
`action-cable-testing` seems to be a good option because it gets merged in Rails 6.0 and it is also used in RSpec 4.

**Comment by jywarren** [comment]
awesome!

**Comment by namangupta01** [comment]
Closing this since this is done in #5985.
