### ISSUE TITLE
Change profile picture as per new style guide design in profile page

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5975]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** /home/lekhika/github/plots2/app/views/users/profile.html.erb

Change L-126

```diff
+<img class="d-none d-lg-inline rounded-circle" id="profile-photo" style="width:100%;margin-bottom:10px;" src="<%= @profile_user.profile_image %>" />
-<img class="d-none d-lg-inline rounded" id="profile-photo" style="width:100%;margin-bottom:10px;" src="<%= @profile_user.profile_image %>" />
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by PoseidonSigmaX** [comment]
Hey, I'd like to work on this issue

**Comment by CleverFool77** [comment]
Sure @PoseidonSigmaX You can go ahead.

**Comment by Saad2714** [comment]
Hi, can I work on this issue? 
 @CleverFool77

**Comment by CleverFool77** [comment]
Hi @PoseidonSigmaX Are you working on this issue ?

**Comment by CleverFool77** [comment]
> Hi, can I work on this issue? First-timer here :)
> @CleverFool77

Lets wait for @PoseidonSigmaX . If he is not working, then you can start off. and And if he is working on this, then I'll open a new first timer issue for you. Cool ?

**Comment by Saad2714** [comment]
yeah... Cool :)

**Comment by CleverFool77** [comment]
It's already been nine days. So I guess we'll assign a different issue to @PosiedonSigmaX.
You can start off with this issue @Saad2714

**Comment by deepanshumaan** [comment]
Hey, a first-timer here. I'd really to work on this issue. How do I?

**Comment by CleverFool77** [comment]
Hi @deepanshumaan Saad had already put PR for this issue. How about you wait a bit for sometime and we'll open a new first timer issue for you.
