### ISSUE TITLE
Add grey circle to make layout consistent in topic-card, when there is no picture for note

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5976]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**  /plots2/app/views/tag/_topicCard.html.erb

Add another condition for this if : 
when there is no profile image then a grey circle should be shown. Add en empty div with circle class.
if condition is at L-13
```diff
-<% if node.main_image %>
-<img class="rounded-circle" id="profile-photo" style="width:20px; height:20px; margin-right:8px; display: inline-block;" src="<%= node.main_image.path(:default) %>" />
-<% elsif node.scraped_image %>
-<img class="rounded-circle" id="profile-photo" style="width:20px; height:20px; margin-right:8px; display: inline-block;" src="<%= node.scraped_image %>" />
+<% if node.main_image %>
+<img class="rounded-circle" id="profile-photo" style="width:20px; height:20px; margin-right:8px; display: inline-block;" src="<%= node.main_image.path(:default) %>" />
+<% elsif node.scraped_image %>
+<img class="rounded-circle" id="profile-photo" style="width:20px; height:20px; margin-right:8px; display: inline-block;" src="<%= node.scraped_image %>" />
+<% else %>
+<div class="circle"></div>
```
Add the css for circle class in last lines of page.
```css
<style>

.circle {
  background-color: gray;
  height: 20px;
  width: 20px;
  border-radius: 100%;
}

</style>

```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by nicobermudez** [comment]
Hey, I'd love to take a go at this issue!

**Comment by CleverFool77** [comment]
Sure. You can go ahead.

**Comment by kryptocodes** [comment]
hey I would like to do this

**Comment by CleverFool77** [comment]
Hi @nicobermudez Are you working on this Issue ?

**Comment by nicobermudez** [comment]
Hi @CleverFool77, yes! I currently have limited wifi but will have a PR in by the end of the week

**Comment by CleverFool77** [comment]
Seems like @nicobermudez will be working on this. So @kryptocodes I'll open a new first-timer issue for soon and ping you. What do you say ?

**Comment by kryptocodes** [comment]
Sure ! :-)

**Comment by enviro3** [comment]
Hi @CleverFool77, I work in the environmental field and am learning software on the side. I would LOVE to contribute to this project as my first contribution ever to open source! Would you be able to create a new "first timer only" issue for me and tag me? If you have time that would be amazing!

**Comment by CleverFool77** [comment]
Sure @enviro3 I'll make a first timer issue for you soon.
Thanks !!!

**Comment by enviro3** [comment]
Thank you @CleverFool77! Much appreciated :)

**Comment by CleverFool77** [comment]
Hey @enviro3 This is not first timer but I do have an issue for you. Are you interested ?

**Comment by enviro3** [comment]
@CleverFool77, absolutely! Please send my way. Thank you!

**Comment by CleverFool77** [comment]
I tagged you in the issue @enviro3 . This is the one https://github.com/publiclab/plots2/issues/6055
