### ISSUE TITLE
Change to 3 cards from four in a row for notes card

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#5987]
**Please describe the desired behavior.**
Recently, notes card were pushed, Right now we have four cards in a row which is making the notes card way too small comapred to questions card. 

![Screenshot from 2019-07-06 13-28-32](https://user-images.githubusercontent.com/26685258/60753572-fb167b00-9ff1-11e9-9fb1-0cb35eb46069.png)

It would be good if we can have 3 cards in a row instead of four.
 
**Update** Updating this file  app/views/notes/_notes.html.erb   with col-4 instead of col-3 would do I guess. And some minor fixes with margins and padding.
Thanks !!!

**Comment by CleverFool77** [comment]
Hi @Anupam-dagar and @cfinn16 If any one of you is interested in this Issue. Then  you can take this up.

**Comment by jywarren** [comment]
Hm, before making this change perhaps we could look at side by side mockups
at a few different screen sizes? Thanks!!

**Comment by CleverFool77** [comment]
Hmm I'll look over it

**Comment by CleverFool77** [comment]
HI Jeff !! I just looked into this and we had three cards in a row as we have side map too which thus take whole width of screen.

![Screenshot from 2019-07-06 17-05-37](https://user-images.githubusercontent.com/26685258/60755670-6ec78080-a010-11e9-8419-68e98e67b9db.png)

And regarding different screens, If you mean mobile then this is what we have right now !!
![Screenshot from 2019-07-06 17-08-57](https://user-images.githubusercontent.com/26685258/60755696-d67dcb80-a010-11e9-9493-1745974af564.png)

**Comment by CleverFool77** [comment]
I saw that the wiki image of main is effecting the others and making it either the page scrollable horizontally of leaving lots of margins in right. :thinking: 
Is it due to container ? But if I'll remove the remove the overridden css of container, then it would margins and padding side by side for image. :thinking: 
Hi !! Is it necesaary for us to use container and row class used in main file where we call cells of all other files. As it might happen that we dont need use container class at all and it may lead to adding further over-ridden css for it. Like we are doing it right now. :thinking: 
Should we refactor whole code for it ? So that container and row class will be written inside cells not mail file ?

**Comment by jywarren** [comment]
Actually we shouldn't really be overriding the .container class -- we
should rely on the original Bootstrap 4 usage:
https://getbootstrap.com/docs/4.3/layout/overview/

I think I was able to set position: absolute and left: 0 and width: 100%
for a lead image and have it work, can you try that for the lead image?

**Comment by CleverFool77** [comment]
Hi @jywarren I'll try the method you spoke of.
Thanks !!!

**Comment by CleverFool77** [comment]
HI @Anupam-dagar If you interested, You can look into this Issue for having three cards in a row instead of four cards . You can also look into this some screenshots and discussions from @jywarren here https://github.com/publiclab/plots2/issues/6002

**Comment by Anupam-dagar** [comment]
@jywarren  @CleverFool77 I would like to take this up.

**Comment by Anupam-dagar** [comment]
opened https://github.com/publiclab/plots2/pull/6015 as a fix for this. @jywarren @CleverFool77 please review.
