### ISSUE TITLE
add admin tools to the Login menu

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#599]
(@jywarren reformatted this on @ebarry's behalf):

Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

An admin-only interface for searching for peoples' email addresses needs to be readily available; the URL is:

https://publiclab.org/useremail (though you won't be able to see it on the live site if you're not an admin!)

But it's hard to find or remember.

## Solution

We could put it in the Login menu in the upper right, in this template:

https://github.com/publiclab/plots2/blob/master/app/views/layouts/_header.html.erb#L175

Perhaps below a divider, and surrounded by `if` tags so it's only shown to admins:

```
<% if current_user.role == 'admin' %>
  <li class="divider"></li>
  <li><a href="/useremail">Email search</a></li> 
<% end %>
```

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by ebarry** [comment]
updated!

--

+1 336-269-1539
@lizbarry <http://twitter.com/lizbarry>

**Comment by jywarren** [comment]
Hm, i don't see any change... did it not save?

This is a pretty easy fix -- could you make this into a "help-wanted" issue ([formatting guidelines](https://publiclab.org/wiki/developers#Contributing+for+non-coders)) and link to the code for the menu content, in this file: https://github.com/publiclab/plots2/blob/master/app/views/sidebar/_post_button.html.erb#L19-L31

**Comment by jywarren** [comment]
Hi @ebarry - could you take a look at reformatting this one? Thanks!

**Comment by 500swapnil** [comment]
I would like to work on this problem

**Comment by jywarren** [comment]
We'd love your help on this and are happy to offer any assistance you might need. Thanks a lot!

Just curious -- we're trying to improve our outreach to new contributors -- how did you happen to hear about us?

**Comment by 500swapnil** [comment]
I was looking for issues on github with label first-timers-only.

**Comment by 500swapnil** [comment]
I am having trouble installing the prerequisites asked. Can I submit PR without those?

**Comment by jywarren** [comment]
Yes, definitely -- the PR will trigger a build on our automated test
server, which will run your code, and we'll both be able to see the output.
However, you won't be able to see if it's correct unless you write a
specific test for it. Still, this is a pretty minimal HTML change, so I
think it'll be fine. Thanks!

**Comment by 500swapnil** [comment]
I have sent a PR. Please have a look #1008

**Comment by jywarren** [comment]
Thanks, sorry I missed that at first -- i left one more request there, it's very close.
