### ISSUE TITLE
Sidebar wrap issue -- new UI changes?

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6002]
cc @gautamig54 @CleverFool77 I noticed this wrapping happening when not logged in, the sidebar can get pushed below:

![image](https://user-images.githubusercontent.com/24359/60979283-6c12a700-a300-11e9-9569-3e1df162b7c4.png)

on stable: https://stable.publiclab.org/notes/warren/09-07-2017/wrapping-up-google-summer-of-code-2017-at-public-lab

Would you mind taking a look? Also, seeing the new card style everywhere, I'm now 100% in support of 3 per row instead of 4. They look great! But yeah, i bit crowded and this will also help the "too tall" issue with longer titles. The profile page on stable:

![image](https://user-images.githubusercontent.com/24359/60979450-c0b62200-a300-11e9-8a7c-7e7c40bc4d6c.png)

By contrast, on full-width pages 4 looks good:

![image](https://user-images.githubusercontent.com/24359/60979375-9b291880-a300-11e9-9c38-1f63ba06d344.png)

**Comment by gautamig54** [comment]
Regarding wrapping up of sidebar below, I was also facing this issue when dividing the individual tags page into bootstrap grids. I solved it. I will look into this one too.

**Comment by jywarren** [comment]
Awesome, folks. Thanks. And looking ahead, the new sidebar design features
a couple "mini topic cards" and a "view all tags" below -- but I'm sure
you've both got a lot on your plate already now!

**Comment by CleverFool77** [comment]
is this new sidebar design included style guide ?

**Comment by jywarren** [comment]
Yes, it is -- take a look at this:

![image](https://user-images.githubusercontent.com/24359/61004582-47d0bd80-a334-11e9-974c-a768f21b9ee8.png)

**Comment by CleverFool77** [comment]
This looks great.  Should we start off with this too @gautamig54 As we can see other profile section and etc are on stop because of some changes in mockup.

**Comment by CleverFool77** [comment]
Hi @jywarren I got the issue with stacking of sidebar. I'll fix it.

**Comment by gautamig54** [comment]
Yes @CleverFool77. Let's start with this.

**Comment by CleverFool77** [comment]
Opening an Issue with breakup checklists or making checklists here would do ?

**Comment by gautamig54** [comment]
I'll make a new issue and the checklist. Give me a minute.

**Comment by CleverFool77** [comment]
> I'll make a new issue and the checklist. Give me a minute.

Sure !!! Go forward !!!

**Comment by gautamig54** [comment]
Hi @jywarren! Regarding wrapping up of sidebar at the bottom, I am not able to generate it. It works fine in my localhost.
Can you check it @CleverFool77 ?

**Comment by CleverFool77** [comment]
Hi @gautamig54 @jywarren I guess this issue has been fixed unintentionally in some PR. The issue is no longer reproducible.
Thanks !!!!

**Comment by jywarren** [comment]
OK! Thanks!

**Comment by jywarren** [comment]
Ah, reopening as I was able to reproduce when not logged in! In Chrome. 

![image](https://user-images.githubusercontent.com/24359/63279706-7b79fe00-c277-11e9-89fe-4d87f8921054.png)

**Comment by jywarren** [comment]
All good now!
