### ISSUE TITLE
New sidebar design implementation for the notes show page

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#6005]
![Screen Shot 2019-07-11 at 12 05 38 PM](https://user-images.githubusercontent.com/35326753/61027687-6be3db80-a3d4-11e9-98cd-2f6d745c80d7.png)

#### Checklist :

- [ ] Toggle icons - Add star and edit option from wikis and notes, And subpages icons @CleverFool77 
- [ ] Tags card and show two of them while hiding others @gautamig54 
- [ ] Add tags option
- [ ] Map and Add location button
- [ ] Add social media icons 

cc : @CleverFool77 @jywarren

**Comment by CleverFool77** [comment]
Link to style guide !!
https://docs.google.com/presentation/d/1-XHlVn3KQxSjS5WzHgc1l1qvFwqUC5f3-7GXugUP9u4/edit?ts=5cab5403#slide=id.g58d9556a0e_1_528

**Comment by CleverFool77** [comment]
Hi @jywarren Can we some explanation regarding the toggle buttons ? Like what does sub pages and other stuff means ? And what about the post option we have in sidebar right now ? Are we going to remove it ?

**Comment by CleverFool77** [comment]
HI @gautamig54 I added another checklist for adding tags in the page which is present we have in sidebar currently, and in a new one, its been done by small icon with plus button inside circle.

**Comment by jywarren** [comment]
Yes, let's remove the post option. People can post from the topic pages
themselves, or from their dashboard.

Some pages have sub-pages, like this --
https://publiclab.org/wiki/data-logging -- and we can just link to the same
listing as that page. Thanks!!!

**Comment by CleverFool77** [comment]
Hi @jywarren Regarding edit and star buttons, They are related to notes/wikis and etc right ?

**Comment by CleverFool77** [comment]
And what about sharing in social media buttons , that we have currently present in sidebar ? Do we have to add this ?

**Comment by jywarren** [comment]
Star and edit are yes, for wikis and notes. Ah, good question! Yes, we'd
better put social in the same space at bottom of sidebar. Thanks!

**Comment by CleverFool77** [comment]
Great !!!!

**Comment by CleverFool77** [comment]
HI @gautamig54, We dont have such icons with circle in font-awesome right ?
Does that mean I have to hardcode or this circle around the icon ?

**Comment by jywarren** [comment]
I think you may be able to use border-radius in css?

**Comment by CleverFool77** [comment]
This idea is great !!!!!
Thanks Jeff.

**Comment by CleverFool77** [comment]
Hi Jeff , could you look into this
https://github.com/publiclab/plots2/issues/6001

**Comment by CleverFool77** [comment]
Hi @gautamig54 Are you working on the tags cards portion ? Coz I can see that right now you have lots of issues in your bag ?

**Comment by CleverFool77** [comment]
> Hi @gautamig54 Are you working on the tags cards portion ? Coz I can see that right now you have lots of issues in your bag ?

Hi Gautami, Are you working on this ?

**Comment by gautamig54** [comment]
Yes. I am working on it!
