### ISSUE TITLE
Rethinking UI flow of /tags page to Subscribe buttons

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6026]
Working from some great feedback from @steviepubliclab here, about the https://publiclab.org/tags page:

> When someone searches on this page, it’s not clear how they would subscribe to tags from the page. The search function brings you to a new page with the tag you search and the subscribe button is hidden there. I'm wondering if we can leave ppl on the /tags page to subscribe to things rather than take them off. I guess I'm interested in something like the `+Add` feature on the Subscriptions page more than a search feature that takes you off the page.

![image](https://user-images.githubusercontent.com/24359/61540200-30b45e80-aa0b-11e9-9a48-76759228395a.png)

OK, cool -- to start off, the new /tag/_ page is different so that may help some, first: https://stable.publiclab.org/tag/balloon-mapping (it's rebuilding now so not online yet) which better highlights the Subscribe function. Here's a not quite perfect screenshot while the site rebuilds:

![image](https://user-images.githubusercontent.com/24359/61540416-9274c880-aa0b-11e9-9242-b38cd3ca8def.png)

When you search on /tags currently, and choose a result item, you go to the individual tag page (as in the screenshot). There are a few options. We could: 

1. show a `Subscribe +` button in the search results
2. have the result of searching be to populate the same page with topics as you type, or after you click <kbd>enter</kbd>, so you see the Subscribe buttons from the list below

(1) could be something like this:

![image](https://user-images.githubusercontent.com/24359/61541062-e207c400-aa0c-11e9-8b90-7b27da2f8279.png)

Maybe there are other ideas too? So we can understand the goal really clearly, can you talk a bit about why you want to have people stay on the /tags listing page rather than get over to the individual tag pages quickly? Thanks!

**Comment by CleverFool77** [comment]
This idea regarding addition of `subscribe` buttons is great tbh. Maybe we can even have a link to know more about tag or something ? Though button looks better.

**Comment by CleverFool77** [comment]
Although Jeff, the inter search results takes time and usually before even we get this dropdown menu, we have usually clicked on search button and have directed towards results already.

**Comment by steviepubliclab** [comment]
Hi! Wondering the status of this idea? It doesn't look like it went through. I'm still interested in the ability for someone to subscribe to tags from this page. I like the dropdown idea you had here, but from our recent conversation, maybe the word needs to be changed to "follow" 

Other note: Are there other open issues related to the /tag page UI I can put an eye on? I'm thinking about user experience for adding and managing subscriptions

**Comment by steviepubliclab** [comment]
Hi all, just adding in with a little more context and material. We're starting to use /tags as a landing page for tag subscriptions. So, I'm trying to work through the process of subscribing to tags as a first time visitor to Public Lab. (For example, say you come in to Public Lab from social media, or any other link and want to get updates on new material on some specific topics, we direct people to www.publiclab.org/tags) :: 

**You currently need a login to follow tags** 

If you don't have a login, currently the process is -- 
1) go to /tags
2) search the tag you'd like to follow
3) click that tag and get redirected to the /tag/_page_ for that topic
4) click follow 
5) login pop up appears, (new user must find sign up button at top)
6) Click "sign up" 
7) Create a login
8) get redirected to the dashboard 


Currently users who don't have a login can't easily subscribe to follow tags, the process of attempting to do so boots you off the page we direct people to.

For this issue I see an ideal change would be to **create a system where people only need to enter their email address to follow tags.** I see following tags as being something different from creating a login to contribute content to the website- so the barriers for doing so could be lowered (unless we're worried about spam followers?) 

If we can't do the above, here are a couple other things that might be helpful changes in this process: 
- allow people to easily follow from the tag page without redirecting them to the individual tag pages. 
- reduce the number of steps from above
- make sure people who create a new login stay on the page they were on before they were required to create a login

Thanks all, looking forward to thinking through this with others!

**Comment by jywarren** [comment]
Hi! There are a lot of ideas here, which is great-- i'll respond to just a few for starters!

First, on the original dropdown containing a `Follow` button, I didn't hear back on this so we didn't pursue it, but I'm glad you like the idea, and we can start implementing it now. 🎉 

Re `a system where people only need to enter their email address to follow tags` - one way to rephrase it could be `can we skip entering a) username, b) password, and c) spam filtering when creating an account` -- because, in order to store the email, we need to create some kind of account record, and those are the only other fields we currently require. So it's like a "minimal account" with only one data entry - the email.

If we did this kind of "minimal account", we would have to think through some possible issues:

1. could we assign them a somewhat random username so they don't have to choose one? We do this for Twitter/FB/Google login (i think we base it on their email or login there?) (see 4 & 5 for why they might need a username)
2. if the person later wanted a full account, might they want to change their username later? 
3. would we say that such an account can receive notifications, but can't post (which would mitigate spam) ... until, maybe, they choose a password and pass the spam filter? 
4. would they show up as part of the count of followers, and/or would they show up in a list of followers?
5. how would they turn off or adjust notifications without an account they could log into? Via email confirmation, maybe? 

So, these aren't insurmountable, but there is some additional thinking that'd have to happen to make this work; i'm sure there are more things we'd need to plan through as well.

Either way, i like the low hanging fruit you're highlighting too, whether or not we take on the "minimal accounts" system above: 

1. allow people to easily follow from the tag page without redirecting them to the individual tag pages.
    * This will now be implemented from the above mockup
2. reduce the number of steps from above (brainstorm follows)
    * once (1) is done, it chould be:
        1. go to /tags
        2. search the tag you'd like to follow
        3. click follow on that tag
        4. **SIGNUP** modal appears (we should be able to set a cookie or something to know if you've been to the site before, and show appropriately)
        5. Create a login
        6. get redirected to ________
3. make sure people who create a new login stay on the page they were on before they were required to create a login
    * this was actually by design, but I'm not invested in it - the reasoning had been that we have the welcome notice that orients people on the dashboard. I think this may need some discussion/input from others, as we could easily skip this, and just send you back where you came from. But, we did reason through this not too long ago. One different factor is that the new dashboard is very much like the /tags page - it'll show a list of topic cards, and have a lot of prompting/support to get you following more tags. So, in that case, would the dashboard be a more appropriate place to end up than it is now? See #6229 #6072 for progress on the new dashboard.

### Takeaways

1. we'll start working on the follow buttons on the tags page search input
2. SIGNUP modal appears if you've never logged in (determined via a cookie)
3. discussion of dashboard (in 3 above)

Thanks, Stevie!

**Comment by jywarren** [comment]
Ah, ok found this which may have some relevant discussion! https://github.com/publiclab/plots2/issues/5600

**Comment by jywarren** [comment]
Closing this as we've broken out all relevant parts into separate issues now, i believe?
