### ISSUE TITLE
Long tag page cards

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6027]
Hi @gautamig54 and @CleverFool77 -- I wanted to see if we can come up with a solution for this issue which is rare but affects the current page design:

![image](https://user-images.githubusercontent.com/24359/61568216-5c0d6c80-aa50-11e9-86a2-a72e05ee1c6b.png)

I think this means we need to use `float` instead of absolute positioning for the tag card; is that right? Once this is resolved, and #5995, we can publish all your recent work to the live site!

Thanks for your help!!!

**Comment by gautamig54** [comment]
Hi @jywarren! I am working on this one! I will look into #6054 as well. Thanks!

**Comment by jywarren** [comment]
Awesome, thank you.

**Comment by jywarren** [comment]
Hi! Any updates on this? Thank you!!!
