### ISSUE TITLE
Add Notification Enabling UI part

### ISSUE THREAD

**Issue by namangupta01** [publiclab/plots2#6039]
Add Notification Enabling UI part same as we have for Email. Let's first discuss what are the possible types which we can add.
- notifications:all
- notification:like
- notification:mentioned
Any more suggesstion @jywarren ?

**Comment by namangupta01** [comment]
What are your thoughts on this @jywarren ?

**Comment by jywarren** [comment]
This sounds great! cc @gauravano as well. Thanks!

**Comment by gauravano** [comment]
Sounds great! But, can we first create a job for the msg broadcast and adding that in queue. And, see how that pattern works? 

This way, we'll be expanding on the optimized approach. 

Thnks Naman and great progress.
