### ISSUE TITLE
Extract javascript from profile page into app/assets/profile.js

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#604]
The user profile page's javascript is all inline -- we should take a crack at moving as much as possible into a new javascript file, and passing any necessary variables into a `profile()` function to simplify the profile page javascript? 

The profile page is here: https://github.com/publiclab/plots2/blob/master/app/views/users/profile.html.erb

We can shorten it by half and separate out the inline javascript into a file at `/app/assets/javascripts/profile.js`

Something like this:

```js
  <script>
    (function(){
      var profile = profile({
        user_id:       <%= @user.id %>
      })();
```

At the end of the profile template.

**Comment by lalithr95** [comment]
Sure, yeah I will move profile inline js to new file.
