### ISSUE TITLE
Tag page heading card not rendering well in mobile screens

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6054]
![image](https://user-images.githubusercontent.com/24359/61722456-5659a480-ad38-11e9-92da-89fcad04a169.png)

cc @gautamig54 @CleverFool77 would you be able to help with this? I think it relates to not using position:absolute for the card... Thanks!

**Comment by jywarren** [comment]
Related to https://github.com/publiclab/plots2/issues/6027 too!

**Comment by jywarren** [comment]
I think it's only https://publiclab.org/tag/coqui doing this ... maybe odd-shaped images? Not sure!

**Comment by CleverFool77** [comment]
Hi Jeff !! I went through the site !! My screenshots are somewhat different :
*attached below*

![Screenshot from 2019-07-23 20-49-41](https://user-images.githubusercontent.com/26685258/61724412-8aaa8080-ad8b-11e9-9d04-6a70c310665e.png)
![Screenshot from 2019-07-23 20-49-50](https://user-images.githubusercontent.com/26685258/61724413-8aaa8080-ad8b-11e9-826b-d6ca4b42b9f4.png)
![Screenshot from 2019-07-23 20-50-12](https://user-images.githubusercontent.com/26685258/61724414-8b431700-ad8b-11e9-9b00-b4118744a456.png)

**Comment by jywarren** [comment]
OK, good to know! Maybe different devices are showing different things here. Let's keep gathering evidence!

**Comment by jywarren** [comment]
My screenshot is 685px wide!

**Comment by CleverFool77** [comment]
Hi @jywarren I specially checked it in 685px wide and yes it's distorting in that width - 
**attached image**
![Screenshot from 2019-07-23 23-21-19](https://user-images.githubusercontent.com/26685258/61735012-aff5b980-ada0-11e9-8cce-b8714a502c00.png)

Me and @gautamig54  will try to look into this and give a fix soon.
Thanks !!

**Comment by CleverFool77** [comment]
So After trying it on many screens, The UI is distorted only in tab version, otherwise its working fine on different screens.

**Comment by gautamig54** [comment]
So @CleverFool77 we can use media screen functionality and make it right for the tab view as well. I did it explicitly for the mobile view, you see it in the code. 
We can do the similar thing for the tab view also. Maybe just by increasing the maximum width in the media screen to 685px which is currently 480px.
What do you say?

**Comment by CleverFool77** [comment]
Sure. Would you like to try it out ? like you did in mobile version as you
said ?

**Comment by gautamig54** [comment]
Sure. I'll try it out!

**Comment by gautamig54** [comment]
@CleverFool77. I notice that in tab view, the page is not displaying the image with the grey background. It is happening for the mobile view. Why do think this is happening?

![Screen Shot 2019-07-27 at 2 37 06 PM](https://user-images.githubusercontent.com/35326753/61992430-0c482a00-b07c-11e9-9788-1e147e7a3805.png)

![Screen Shot 2019-07-27 at 2 37 18 PM](https://user-images.githubusercontent.com/35326753/61992433-12d6a180-b07c-11e9-9786-071366e65757.png)

**Comment by CleverFool77** [comment]
So page is not displaying the image with background . Its because this feature is necessary only in medium and above larger screen as usually width of image goes much smaller compares to width of our screens. 
Besides, In this I have used two different divs, one is for smaller screen like mobile and other is for screens larger than mobile. So I did add the background on them using bootstrap classes and css.
Is this what you wanted me to explain ?

**Comment by gautamig54** [comment]
HI @CleverFool77! I am not able to understand why the image is not rendering in the tab view. Can you look into this? I will take care of the tag card positioning and other objects. 
You can solve the image part and I will take care of the rest :)

**Comment by jywarren** [comment]
I looked in the chrome dev console and found that this 'box' class div is potentially the issue? 

![image](https://user-images.githubusercontent.com/24359/63353744-387c6100-c331-11e9-8126-a18d5e76389f.png)

**Comment by jywarren** [comment]
OK, moving to #6799
