### ISSUE TITLE
Follow-up issues to new tag page design 

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6055]
The new tag page looks super! Especially on this page: https://publiclab.org/tag/water-quality

But there are small things I'd like to resolve. Just organizing here!

* [ ] `# people discussing` - extra space to right @newbazz 
* [x] `# people discussing` - white text color       **Issue :** https://github.com/publiclab/plots2/issues/6057 **PR:** https://github.com/publiclab/plots2/pull/6058
* [ ] move admin button into `...` menu @hedonhermdev 
* [x] tweak page width? i'm getting some left/right scrolling "wiggle" @Anupam-dagar 
* [ ] Alerts get covered up @enviro3
* [ ] if logged out, the login modal on this tag page is distorted. @Anupam-dagar 
* [ ] main image size - should we be loading really gigantic images, which can be slow? (see below)

![image](https://user-images.githubusercontent.com/24359/61726574-d8999700-ad3f-11e9-906b-8081b457fd1e.png)

Needs discussion/design:

* [ ] figure out what to do with questions buttons - merge into general "post" button as in style guide?

**Comment by jywarren** [comment]
cc @gautamig54 @CleverFool77

**Comment by jywarren** [comment]
Any more you want to add?

**Comment by jywarren** [comment]
Could we also consider using a photo wall for the lead image on the tag page, using various image from the wiki page?

https://www.npmjs.com/package/jquery-photowall

**Comment by jywarren** [comment]
Also, wondering if we could move this template (used on this page as thumbnail grid: https://publiclab.org/wiki/micro#Assembly) to the new card design:

https://github.com/publiclab/plots2/blob/master/app/views/grids/_thumbnail.html.erb

This is not directly related, but wanted to hear your thoughts!

**Comment by CleverFool77** [comment]
Hi @jywarren Should I open small first timers only issue for all these different parts ? It would be great to let other people contribute. what do you say ?

**Comment by CleverFool77** [comment]
I'll write down the file and the change required for these parts in first timers only issue. So it would make everything easier.

**Comment by CleverFool77** [comment]
And regarding question button, - the new option of having a single post button with dropdown for various option to choose from `notes` , `wikis`, and `questions`  would be great !!!

**Comment by gautamig54** [comment]
Hi @CleverFool77! Yes, I think making them as FTOs will be a good idea!

**Comment by gautamig54** [comment]
Hi @jywarren! I think if we add question button into the post button, then it will look like a more generalised thing. Like, the user will expect an option for notes or wikis also under the post button. What do you think?

**Comment by jywarren** [comment]
:-) this is great. I'll update more soon, sorry, but if you want to see a range of "scenarios" with this design:

* https://publiclab.org/tag/water-quality (best outcome! So nice!)
* https://publiclab.org/tag/community-microscope
* https://publiclab.org/tag/coqui
* https://publiclab.org/tag/air-quality
* https://publiclab.org/tag/spectrometer

**Comment by CleverFool77** [comment]
@newbazz and @Anupam-dagar Are you guys interested in taking first and fourth part of this issue ?

**Comment by CleverFool77** [comment]
Hi @jywarren I did notice the slow loading of image in community microscope. So How would you want to deal with this ?

**Comment by newbazz** [comment]
@CleverFool77 yes i will take the first one.

**Comment by hedonhermdev** [comment]
Can I try to fix these issues?

**Comment by newbazz** [comment]
@hedonhermdev i am working on it.

**Comment by CleverFool77** [comment]
@hedenohermdev Are you interested in third or fourth one ? As @newbazz is
taking the first one.

**Comment by newbazz** [comment]
I have made a PR, can someone review it https://github.com/publiclab/plots2/pull/6060

**Comment by Anupam-dagar** [comment]
@CleverFool77 I'll take the 4th one if it is available.

**Comment by CleverFool77** [comment]
Sure Anupam, you can do fourth then, and hedeno, would you like to go for third?

**Comment by jywarren** [comment]
Hi, I found one more -- looks like the "alerts" get a bit covered up. Should be pretty simple to fix though! 

![image](https://user-images.githubusercontent.com/24359/61910887-7be2db80-aefb-11e9-897d-66169da686db.png)

**Comment by CleverFool77** [comment]
ohk I'll add this in checklist.

**Comment by hedonhermdev** [comment]
I’ll do the third one

**Comment by CleverFool77** [comment]
Cool. Go forward.

**Comment by CleverFool77** [comment]
Hi @enviro3 As you have already done one of the `fto-candicate` issue and you wanted next one. So Are you interested in the fifth part of this issue which is for the alert which seems to get covered up.

**Comment by enviro3** [comment]
@CleverFool77 - yep, I will attempt to fix the alert so it fully shows. Thank you for letting me work on this!

**Comment by CleverFool77** [comment]
Great !! I'll assign you this part then.
Thanks !!!

**Comment by enviro3** [comment]
Hi @CleverFool77, I'm having some trouble replicating this issue on the browser so I can see what's going on. When I go to https://publiclab.org/tag/one-cranston in incognito mode and click "Subscribe" I get the following: 
![image](https://user-images.githubusercontent.com/22761644/62102167-d312e400-b24c-11e9-88f5-4b3c4507eb3d.png) What should I click instead to get the alert message as noted above?

**Comment by CleverFool77** [comment]
> Hi @CleverFool77, I'm having some trouble replicating this issue on the browser so I can see what's going on. When I go to https://publiclab.org/tag/one-cranston in incognito mode and click "Subscribe" I get the following:
> ![image](https://user-images.githubusercontent.com/22761644/62102167-d312e400-b24c-11e9-88f5-4b3c4507eb3d.png) What should I click instead to get the alert message as noted above?

To be honest I checked what you wanted to say and even I got the same. Hi @jywarren @gauravano Reproducing this issue should be like this only right ? 
- Logout 
- Try subscribing one of the tags
- You'll get a alert to login or create account 
:thinking:

**Comment by enviro3** [comment]
Hi @CleverFool77, I think I may table this issue for now. I have a homework assignment to work on a more difficult issue on github. The assignment requires I do a more difficult contribution such as:
- developing a new feature
- finding and fixing a bug that has been identified as critical
- finishing a task to support a future feature

Is there any issues or assignments I could work on that would fulfill this criteria and also help you all out in plots2? Thank you so much!

**Comment by CleverFool77** [comment]
Hi @enviro3 the bug you are working on is because of new feature that is recently added. So yes indeed, It is one of the critical bug. 
Regarding such issues though, I don't seem to remember. But you can go through the list of issues maybe.
@gauravano might help you.
BTW for bug, you can check the label `bug` and for new feature, go through label `feature`.

**Comment by CleverFool77** [comment]
Hi @enviro3 Are you interested in this issue https://github.com/publiclab/plots2/issues/5741 ?
Explanation is this - https://github.com/publiclab/plots2/pull/5800#pullrequestreview-252776122

**Comment by gauravano** [comment]
Hey @enviro3, you can work on https://github.com/publiclab/plots2/issues/5842. It has PR but a bit older. Also, tests also need to be added. Let me know if you're interested.

**Comment by enviro3** [comment]
Hi @CleverFool77, good to know it's a key bug that needs fixing so I would love to help. I still cannot seem to replicate the issue though. When I launch on localhost:3000 I am going to the blogs page (I am not logged in) and then I go to Subscribe+ and choose a tag and click subscribe I am always greeted with the modal pop-up to log in rather than the "covered up alert bug". I've been clicking around the website trying other ways to trigger the bug but am coming up short. @gauravano, do you have ideas how to reproduce the bug? 

@CleverFool77 - thank you for pointing out issue #5741 ! I will indeed try to take a crack at it :)
@gauravano - thank you for the shout out and pointing out issue #5842! I would like to take a shot at fixing this even though this particular issue may be a bit too advanced for me. I will give it a try anyway though!

Thank you both again! Very much appreciated.

**Comment by gauravano** [comment]
> Hi @CleverFool77, good to know it's a key bug that needs fixing so I would love to help. I still cannot seem to replicate the issue though. When I launch on localhost:3000 I am going to the blogs page (I am not logged in) and then I go to Subscribe+ and choose a tag and click subscribe I am always greeted with the modal pop-up to log in rather than the "covered up alert bug". I've been clicking around the website trying other ways to trigger the bug but am coming up short. @gauravano, do you have ideas how to reproduce the bug?

first of all, make sure, you're on master. Then, go to any tag page like localhost:3000/tag/<tagname?
If no alert is appearing for you, you can add `flash[:notice] = "Some text ..."` in the tag_controller file under show method, and then you'll see the notice at the tag page.

> @gauravano - thank you for the shout out and pointing out issue #5842! I would like to take a shot at fixing this even though this particular issue may be a bit too advanced for me. I will give it a try anyway though!

Just take any one and focus on that. If you try to solve all at a go, you'll not be able to complete any. So, start with one, and after solving that move to another. 

Thanks!

**Comment by CleverFool77** [comment]
Thanks @gauravano for help. 😄

**Comment by Anupam-dagar** [comment]
@CleverFool77 I would like to take up the 6th part.

**Comment by CleverFool77** [comment]
Sure @Anupam-dagar.
You can go forward !!

**Comment by CleverFool77** [comment]
Hi @hedonhermdev Are you working on your assigned part ?

**Comment by jywarren** [comment]
This is complete! Thanks, all!
