### ISSUE TITLE
Banning (spam) users doesn't drop the liked count on wiki pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#607]
https://publiclab.org/barnraising had 14 likes with spammers, but I banned them all, so there should only be ~5 now. But maybe the cached_likes is not properly recalculated?

Like counts are listed in the upper right box -- to the right of the title, marked with a star icon.

`user.ban` is here: https://github.com/publiclab/plots2/blob/master/app/models/drupal_users.rb#L45

Perhaps this belongs in the admin controller? That would be here: https://github.com/publiclab/plots2/blob/master/app/controllers/admin_controller.rb#L87

Any time you ban a user, presumably you'd want to trigger a recalculation of likes on any node they've liked. Recalculating likes happens here: https://github.com/publiclab/plots2/blob/master/app/controllers/like_controller.rb#L35

**Comment by rafael-acerqueira** [comment]
Hi ! I Sent a pull request #864 to this issue. I don't have a lot of experience in contribute, so if I made something wrong, let me know !

**Comment by jywarren** [comment]
Great, thank you - I'll review soon and get back to you!

**Comment by jywarren** [comment]
Apologies for my slowness here - we're currently in a staff retreat and I'm not as able to respond to contributions. I just wanted to say thanks for your PR and we're very grateful for your contribution -- we should be able to review and merge a little later this week.

**Comment by jywarren** [comment]
This works, but there's some other issue at play -- on [the Barnraising page](https://publiclab.org/barnraising) I now see the correct number (6) show for a moment, then change to 17! I think there's some odd caching going on in the count requested by JavaScript:

https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/like.js

And perhaps we should try to rework the liking code here: https://github.com/publiclab/plots2/blob/master/app/controllers/like_controller.rb#L35

Bears more investigation but thanks for your fix so far!

**Comment by jywarren** [comment]
Indeed, here are all the places that `cached_likes` is used, and I think really any time we increment or decrement it, we should just be counting all the `node_selections` instead of adding/subtracting one:

```ruby
app/views/wiki/_wikis.html.erb:      <td><%= number_with_delimiter(wiki.cached_likes) %></td>
app/views/answer_like/likes.js.erb:$("#answer-like-count-<%= @answer.id %>").html('<%= @answer.cached_likes%>')
app/models/answer.rb:  attr_accessible :uid, :nid, :content, :cached_likes, :created_at, :updated_at
app/models/drupal_node.rb:  attr_accessible :title, :uid, :status, :type, :vid, :cached_likes, :comment, :path, :slug
app/models/answer_selection.rb:        answer.cached_likes += 1
app/models/answer_selection.rb:        answer.cached_likes -= 1
app/models/concerns/node_shared.rb:    self.cached_likes
app/models/drupal_users.rb:      node.drupal_node.cached_likes = node.drupal_node.cached_likes - 1
app/models/drupal_users.rb:      node.drupal_node.cached_likes = node.drupal_node.cached_likes + 1
app/helpers/application_helper.rb:        output += '  <td class="likes">' + number_with_delimiter(node.cached_likes) + '</td>'
app/helpers/application_helper.rb:                        .order("node.cached_likes DESC")
app/helpers/application_helper.rb:                        .order("node.cached_likes DESC")
app/controllers/questions_search_controller.rb:      likes = " &nbsp; &nbsp; <i class='fa fa-star'></i> " + match.cached_likes.to_s
app/controllers/subscription_controller.rb:        #  node.cached_likes = node.cached_likes + 1
app/controllers/subscription_controller.rb:        #  node.cached_likes = node.cached_likes - 1
app/controllers/questions_controller.rb:    @questions = @questions.order("cached_likes DESC")
app/controllers/answer_like_controller.rb:    render :json => Answer.find(params[:id]).cached_likes
app/controllers/wiki_controller.rb:                       .order("node.cached_likes DESC")
app/controllers/wiki_controller.rb:                       .where("status = 1 AND nid != 259 AND (type = 'page' OR type = 'tool' OR type = 'place') AND cached_likes > 0")
app/controllers/notes_controller.rb:                       .where('type = ? AND status = 1 AND cached_likes > 0', 'note')
app/controllers/like_controller.rb:    render :json => DrupalNode.find(params[:id]).cached_likes
app/controllers/like_controller.rb:          node.cached_likes = node.cached_likes + 1
app/controllers/like_controller.rb:          node.cached_likes = node.cached_likes - 1
```

The like controller should just call a model method like `node.like(user)` or `node.unlike(user)` -- and we can test those out in the unit tests.

**Comment by jywarren** [comment]
We should break this up into separate issues:

* develop `node.like(user)` and `node.unlike(user)` methods, based on (and replacing) https://github.com/publiclab/plots2/blob/master/app/controllers/like_controller.rb#L35-L71 which:
  1. are unit tested
  2. create a new `NodeSelection` entry: `NodeSelection.where(user_id: user.uid,
nid: self.id).first_or_create` 
  3. count `NodeSelection`s for this node and update cached_likes accordingly
* see if Answers also need these `like/unlike` features, and consider moving them to https://github.com/publiclab/plots2/blob/master/app/models/concerns/node_shared.rb
* refactor https://github.com/publiclab/plots2/blob/master/app/controllers/like_controller.rb#L25 and https://github.com/publiclab/plots2/blob/master/app/controllers/like_controller.rb#L30 to use the `node.like/unlike` methods from above, and delete the `set_liking` method they were pointed at
* scour code (as in the comment above) to be sure we don't manually increment/decrement cached_likes anywhere -- we should be using the new `like/unlike` features proposed here and therefore creating `NodeSelection` records.

**Comment by jywarren** [comment]
Updated with code from an old PR with a partial implementation. This issue needs some clean up and breaking up!
