### ISSUE TITLE
Reporting success on profile picture upload/change.

### ISSUE THREAD

**Issue by Gagan6730** [publiclab/plots2#6074]
Currently when we upload or change our profile picture, there is no message either if the upload was successful or not.
We could add a message to report that to the user.
<img width="379" alt="Screenshot 2019-07-28 at 1 27 02 AM" src="https://user-images.githubusercontent.com/23430169/61999050-d1271480-b0d6-11e9-8fcb-f9a1ec0f771f.png">

**Comment by Gagan6730** [comment]
@jywarren what do you think about this?

**Comment by CleverFool77** [comment]
This looks great according to be. What do you think? @gautamig54 @gauravano

**Comment by gauravano** [comment]
Looks great. How about using Noty for this? Thank you!

**Comment by Gagan6730** [comment]
@gauravano Would I be able to upload a profile pic in development mode? When I am trying to test my changes, it is just showing uploading.

<img width="325" alt="Screenshot 2019-07-28 at 11 12 55 PM" src="https://user-images.githubusercontent.com/23430169/62010838-3fc6a980-b18d-11e9-966f-8643651324aa.png">

**Comment by gauravano** [comment]
I think, there's a bug due to which preview is not showing up. But, you should be able to upload image. After image uploading, the bar will be removed. And, if you refresh the page, you'll see your image uploaded.

**Comment by gauravano** [comment]
If you like, you can also work on the image preview bug

**Comment by Gagan6730** [comment]
I think its working fine on the site, but trying to upload while developing, its not able to upload the profile pic. Its just showing "uploading" even after few minutes.

**Comment by gautamig54** [comment]
Yes, @Gagan6730 you can upload an image in the development mode. Have you installed imagebrick?
