### ISSUE TITLE
wiki print pages modal distortion

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#6078]
![Screenshot from 2019-07-29 15-04-07](https://user-images.githubusercontent.com/26685258/62037819-274ca280-b212-11e9-82e8-14c8c88f19d0.png)

**Comment by newbazz** [comment]
I would like to work on this issue. And btw you are talking about the toolbar that is going outside the box right?

**Comment by CleverFool77** [comment]
Yes I'm talking about that only. Would you like to work on this ? @newbazz

**Comment by newbazz** [comment]
yes, I would like to work on this issue, can you please help me in reproducing the issue.

**Comment by CleverFool77** [comment]
Sure this is great. So just create a wiki page and when you'll go the link, you'll Find this modal distortion after clicking the icon on sidebar.

**Comment by newbazz** [comment]
![image](https://user-images.githubusercontent.com/25884863/62269765-b5629c00-b451-11e9-9937-4b6dc3c4105b.png)

@CleverFool77 i am not getting any icon on the side bar.

**Comment by CleverFool77** [comment]
Maybe you haven't fetched the latest changes pushed to master branch yet.
Just fetch it and rebase it, then you'll get the toggle icon.

Thank you

**Comment by newbazz** [comment]
@CleverFool77 It is uptodate with the upstream.

**Comment by newbazz** [comment]
I am still not geeting the toggle icon.

**Comment by CleverFool77** [comment]
Hi @newbazz Can you show me the link ? 
I made a wiki page named test -
So I got this - 
![Screenshot from 2019-08-01 17-13-13](https://user-images.githubusercontent.com/26685258/62290751-b3173680-b47f-11e9-8813-053b6ae8f028.png)
I created another note page -
So I got this -
![Screenshot from 2019-08-01 17-14-15](https://user-images.githubusercontent.com/26685258/62290816-d5a94f80-b47f-11e9-9313-854564c8e0ab.png)

I guess just follow these steps -
* git checkout master
* git fetch upstream master
* git rebase upstream/master
If direct its done, then its cool, or else 
solve the merge conflicts
* git add -A
* git rebase --continue

**Comment by CleverFool77** [comment]
You can see the second latest commit which has been added -
https://github.com/publiclab/plots2/commits/master
So You need to fetch and rebase.

**Comment by newbazz** [comment]
![image](https://user-images.githubusercontent.com/25884863/62346068-66307000-b512-11e9-9dab-60fd64b3d9c9.png)
It is already up todate

**Comment by newbazz** [comment]
@CleverFool77 you can have a look at this as well https://github.com/newbazz/plots2/commits/master

**Comment by newbazz** [comment]
![image](https://user-images.githubusercontent.com/25884863/62346869-57978800-b515-11e9-8d5d-10538eabce98.png)
I made a new wiki as well, but ma not getting the toggle icon.

**Comment by CleverFool77** [comment]
Hi @newbazz now it would be done. Just click on the second icon above the tags on sidebar on the image you uploaded.

**Comment by newbazz** [comment]
thanks @CleverFool77 will start working on it soon.
