### ISSUE TITLE
Indent `app/views/like/_like.html.erb` properly

### ISSUE THREAD

**Issue by newbazz** [publiclab/plots2#6080]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file https://github.com/publiclab/plots2/blob/master/app/views/like/_like.html.erb (press the little pen Icon) and edit the line as shown below. 

1. Copy the indented code here https://gist.github.com/cesswairimu/fe9c3fd047ac94531f17a461dc9b5895

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by newbazz** [comment]
The file doesn't have a uniform indentation, i.e some lines are separated by 4 spaces and others by 2 spaces, this indentation is what needs to be changed.

**Comment by amitkumarpatel** [comment]
I would like to make the indentation correct

**Comment by metonymic-smokey** [comment]
First timer here, this seems like an issue I could take up if no one else is assigned, working with @amitkumarpatel if needed.

**Comment by CleverFool77** [comment]
Well @jywarren @gauravano Regarding this, we do have many pages without indentation. Should we start refactoring and linting it properly ? Along with doc-strings and other stuff ? We can do it through first timers ?

**Comment by gauravano** [comment]
Sure @CleverFool77.

**Comment by samyak-jn** [comment]
@CleverFool77 I would also like to contribute to the issue, can you please guide me where to start from? 
Thanks

**Comment by ermarie** [comment]
@CleverFool77 Happy to do some indenting if there is more to do!

**Comment by newbazz** [comment]
So i think all the interested candidates can first of all see what are the indentation standards ruby follows, after that looking for files that are not upto those standards, asking creating an issue for the change of indentation and working on it.

**Comment by CleverFool77** [comment]
I guess all of you can look into the pages of file and even without opening an issue. You can open a PR with a title "Refactor: filename". We can start with basic indentation first and removal extra spaces and stuff first. And following a particular linter would be much better.

**Comment by CleverFool77** [comment]
> I guess all of you can look into the pages of file and even without opening an issue. You can open a PR with a title "Refactor: filename". We can start with basic indentation first and removal extra spaces and stuff first. And following a particular linter would be much better.

@ermarie @samyak-jn @metonymic-smokey @newbazz

**Comment by JeffOgah** [comment]
Made changes as requested. PR opened here https://github.com/publiclab/plots2/pull/6439
