### ISSUE TITLE
Fix unequal margins/paddings in the featured questions cards on shadow interface

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#6092]
As one can see, that the padding or margins in left or right of cards is unequal.
It would be great if we can have equal margins on side. SO that both the cards are exactly at center.
The gap from left for first card is lesser than the gap of second card from right. This should be `equal`.

![Screenshot from 2019-08-01 19-52-55](https://user-images.githubusercontent.com/26685258/62301331-0a280600-b496-11e9-8f8b-3b6ecb76e37d.png)

**Comment by CleverFool77** [comment]
Hi, 
We have this bug at the different route https://publiclab.org/questions_shadow
which is for now is the shadow interface of the new questions page.

**Comment by CleverFool77** [comment]
Hi @enviro3 and @newbazz If one of you is interested. You can look into this.
Thanks !!

**Comment by newbazz** [comment]
Yes i would like to work on the issue.

**Comment by gautamig54** [comment]
Hi @newbazz! The issue is that featured cards are not exactly in the centre. Can you make out that?

![Screen Shot 2019-08-02 at 11 40 26 AM](https://user-images.githubusercontent.com/35326753/62348483-6cc2e580-b51a-11e9-9983-a1e9f7d45f57.png)

**Comment by CleverFool77** [comment]
As gautami mentioned. You just need to algn the feature cards in center. You need to inspect element the current design.

**Comment by CleverFool77** [comment]
Its because of uneven column gaps, As much as I remember. 
Its col-md-2 before the cards but its more than col-md-3 after the cards.... So thus leading to gap...

**Comment by newbazz** [comment]
okay, so one of the solutions is using adding extra margin in the style sheet or another thing that can be done is apply styling using bootstrap, which do you think should be approached in this isse?

**Comment by CleverFool77** [comment]
Hi @newbazz It depends on you, how about trying the mock first. Whichever method looks efficient and better.

**Comment by CleverFool77** [comment]
There shouldn't be much of hardcoded code, and do it only when it's absolutely necessary, otherwise try bootstrap classes and other stuff.

**Comment by newbazz** [comment]
@CleverFool77 the bootstrap is not customizable so I am not sure bootstrap can solve our problem. I can have a look if not we have to hardcode the margin. And anyways applying bootstrap classes/ids is also hardcoding in a way.

**Comment by CleverFool77** [comment]
Hi @newbazz then you can try margins and paddings.

**Comment by CleverFool77** [comment]
Tbh you can try whatever method you want, it need to be efficient and solve the bug.

**Comment by CleverFool77** [comment]
Hi @newbazz Are you working on this? Or any updates?

**Comment by newbazz** [comment]
@CleverFool77 sorry but i am going a bit busy lately, yes i can work but it can take a few days, you can carry on with this if it's urgent. Sorry for the delay.

**Comment by CleverFool77** [comment]
Cool. @newbazz You can take your time
Thanks !

**Comment by NitinBhasneria** [comment]
@jywarren There is a problem here as I open in the server there is nothing shown in the place of featured question. Can you tell me why?

**Comment by NitinBhasneria** [comment]
![Screenshot from 2020-01-17 22-45-18](https://user-images.githubusercontent.com/44112080/72631866-112ace00-397b-11ea-8503-0c01e031245d.png)

**Comment by jywarren** [comment]
I believe that is supposed to show questions tagged with the tagname
"featured"? so, to get things to show, you have to tag some questions with
that tag. Does that help?

**Comment by NitinBhasneria** [comment]
But on the original website it is showing without the tag... It's now showing only when opened via server.

**Comment by NitinBhasneria** [comment]
![Screenshot from 2020-01-18 00-04-10](https://user-images.githubusercontent.com/44112080/72636870-117c9680-3986-11ea-8223-8252a3bc60a1.png)

**Comment by NitinBhasneria** [comment]
@jywarren do you mean that this thing comes in features. If yes where we can view its source code and edit it.

**Comment by NitinBhasneria** [comment]
@jywarren Thanks for the help and here I got the solution

**Comment by jywarren** [comment]
Awesome!!!
