### ISSUE TITLE
Limiting the biodata to be be shown ?

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#6121]
## Describe 
In reality, we can't limit the data for bio.
But can we limit the part which is shown 
for eg -

![Screenshot from 2019-08-09 18-57-31](https://user-images.githubusercontent.com/26685258/62782280-901c0080-bad7-11e9-85ae-102505ffa897.png)

This image has lots of line in biodata, So how about limiting the bio data to 3-4 lines to be shown and hide other part. 
If only clicked on `more` button, then only full bio would be shown.
Like we usually for tags part -

![Screenshot from 2019-08-09 18-59-38](https://user-images.githubusercontent.com/26685258/62782436-e25d2180-bad7-11e9-8dfb-b947a04d2e90.png)

**Comment by CleverFool77** [comment]
cc: @gautamig54 @jywarren

**Comment by SidharthBansal** [comment]
Hi @CleverFool77  there are two ideas:
1. We can use ``more`` option as discussed above
2. Create an additional field in the user's profile section to add short biodata.
I am in favour of option 1.

**Comment by SidharthBansal** [comment]
Great idea

**Comment by gauravano** [comment]
Yes, "Show more" option sounds good.

**Comment by gautamig54** [comment]
@CleverFool77 I will add this feature!

**Comment by CleverFool77** [comment]
Great !!

**Comment by AdityaShD** [comment]
is this issue still open? I would like to work on it.

**Comment by jywarren** [comment]
Hi, I think we should close this as we haven't had more input on it from community reps. Thank you though!
