### ISSUE TITLE
Sharing draft requires login 

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#6122]
Hello! I was recently working with @ebarry on a post with a community partner. That community partner doesn't have a Public Lab login yet. We're hoping she will at some point in the future, but in the meantime, we were hoping to be able to share a post with her so she could see it before it was published (in case there were any edits or additions she wanted to make). 

**Please describe the desired behavior.**
I am wondering if we can change the way people interact with drafts so that if I send a link to a draft out to someone without a Public Lab login, they can still see it.

**Comment by gauravano** [comment]
Hey @steviepubliclab, when we created this feature, we incorporated this feature but I found that in https://github.com/publiclab/plots2/pull/5028/ it's removed, I guess mistakenly, so need to be fixed. Will do that. 

if anyone else, want to take a dig, feel free to go and refer PR and look for changes done in notes_controller there. 

Thank you!

**Comment by jywarren** [comment]
Oh goodness, yes, it's this line that needs to be re-added, allowing just
the token (in the unique URL) to be used to share despite not being logged
in:

https://github.com/publiclab/plots2/pull/5028/files#diff-b9551b46e6321bfb977e1f52104c5768L56

We should protect this with a test. Gaurav, are you able to open an issue
for this? I'll ask in the chatroom too to see if anyone is available.
Thanks!

**Comment by gauravano** [comment]
I will take this issue @jywarren.

**Comment by jywarren** [comment]
Thank you, Gaurav!!!

**Comment by gauravano** [comment]
Actually, test is already there but in #5028 test is also changed 😄. Raising PR
