### ISSUE TITLE
Travis build failing 

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#6128]
Travis build is currently exiting with this failure for all the recent pull requests...
With this error 
``
/usr/local/bundle/gems/octokit-4.14.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/publiclab/plots2/pulls/6124: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)
``

![travis](https://user-images.githubusercontent.com/17081074/62840199-26e6e980-bc9f-11e9-82da-38fb444562c6.png)

@publiclab/reviewers any ideas on how to solve this? Thanks

**Comment by sashadev-sky** [comment]
@cesswairimu I googled the error message and got to this page, someone from PL actually  posted this question there. https://github.com/travis-ci/travis-ci/issues/8018
So I would try this suggestion:

"@namangupta01 I got this recently for a repo on travis-ci.com after the move to GitHub Apps. 
Solved it by adding the --pro flag to `travis setup releases`."

**Comment by cesswairimu** [comment]
Great, thanks @sashadev-sky

**Comment by gauravano** [comment]
We faced this issue nearly a year ago too - https://github.com/publiclab/plots2/issues/2758 and it was solved by generating new token for Travis CI

**Comment by cesswairimu** [comment]
Thanks @gauravano, are you have access to generate another token?

**Comment by gauravano** [comment]
No, I don't. @jywarren or @icarito can do that

**Comment by kaustubh-nair** [comment]
Oh I'm facing the same issue here while trying to set up dangerbot https://github.com/publiclab/mapknitter/pull/926

**Comment by kaustubh-nair** [comment]
I think it's an issue with the dangerbot token?
We can try commenting out the danger command temporarily till this is fixed so we can see the builds

**Comment by jywarren** [comment]
Ah, ok, so do we need to generate a new token, or has TravisCI moved to
GitHub apps and there is some other way? Thanks, all!

**Comment by IshaGupta18** [comment]
I think @gauravano said in the call that we need a new token!

**Comment by jywarren** [comment]
OK, working on this now!

**Comment by jywarren** [comment]
OK, just as in https://github.com/publiclab/plots2/issues/2758#issuecomment-409355915, I added a `DANGER_GITHUB_API_TOKEN` set to `display value in build log`-- following instructions at https://danger.systems/guides/getting_started.html#setting-up-an-access-token, and generated the token at https://github.com/settings/tokens

**Comment by jywarren** [comment]
@kaustubh-nair i also repeated this for MapKnitter; can you try restarting some tests to see if it works? Thanks!

**Comment by jywarren** [comment]
Looks like this worked for `plots2`!!!

**Comment by gauravano** [comment]
Thank you @jywarren!!
