### ISSUE TITLE
cursor position on etherpad unreliable

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#613]
### What happened just before the problem occurred

i started working on a new pad, and it was fine until i pasted in a link. 
Then the cursor started losing its position, and typing new letters would insert before the actual insertion point. This effect worsened until i stopped typing completely and without touching the keyboard at all I watched the blinking cursor move itself backwards in a line of text, one letter for every blink. 

### Relevant URLs

https://

### PublicLab.org username

@liz

### Browser, version, and operating system

Chrome on OSX 10.11.3

**Comment by jywarren** [comment]
Hi, can you please file this on the etherpad-lite issue tracker? Thanks!

**Comment by ebarry** [comment]
done: https://github.com/ether/etherpad-lite/issues/2224

**Comment by jywarren** [comment]
Thanks!
