### ISSUE TITLE
Weekly community Check-In #32 - Push Your Limits

### ISSUE THREAD

**Issue by namangupta01** [publiclab/plots2#6130]
Hi everyone 👋 !

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️ .

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. 💯

If you're new here, welcome, and please comment a Hello below, we would love to work with you. If you're looking for new issues, please try some of our first-timers-only issues.

We're SO EXCITED to have your help!

Is there anything, you would like to share with us from past week's work? What is your plan for this week?

If you have not planned yet, just leave a Hello! 👋 so that we know that you are in sync with us 🔃 and doing well!

As always, if you're waiting for a review, or if you're stuck, please request help here OR leave a comment with @publiclab/mentors @publiclab/reviewers for some input. 🙌

Gitter
Gitter is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up there for these updates or just to join the conversation. You can also join us through http://publiclab.org/chat 💬.

So the final evaluation process is not very far now. At this point, everybody's contributions to the projects and the community have grown quantitatively and qualitatively. Some are almost done with their projects also. This makes the next coming weeks the best time to give a final touch to the projects.

You can find our list of previous check-ins here.
https://github.com/publiclab/image-sequencer/issues/1195

📝 Note to Summer of Code interns:
We request all the SoC students to read and include necessary points in their check-in comment

Update on what you worked on last week
Goals in the coming week
What things you did collaboratively last week? This is really important we want team spirit.
It is like a weekly scrum. Be flexible.
Issue/PR you're struggling with (if any)
Join us for Open Code Call/ Weekly scrum on Tuesday - http://publiclab.org/opencall

Thanks 🎈 🎉 🚀

**Comment by namangupta01** [comment]
@newbazz @aSquare14 @vaarigupta @alonpeer @aashna27 @harshithpabbati @jesus-montano @cryptoclidus @mohamed-elalem @konolga @gowtham5699

**Comment by namangupta01** [comment]
@milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @shubhscoder @sidntrivedi012 @SidharthBansal @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77 @ananyaarun @ananya @publiclab-mimi @ananya @hc-barker @starkblaze01 @asquare @pdurbin @HarshKhandeparkar

**Comment by niravasher** [comment]
All the best to all GSoCer's for the last evaluation round and congratulations for passing the first two. Keep up the great work

**Comment by Rishabh570** [comment]
Hi all, 

**Update**

- **Work ready for review**

  - Implement a leaderboard of recent contributors, incorporated as a _sort_ option in the filter. [207](https://github.com/publiclab/community-toolbox/issues/207)
  - Progressive web app support with an offline read-only purpose using application cache. Also, can be added to the home screen as a standalone app. [239](https://github.com/publiclab/community-toolbox/pull/239)
  - Added unit tests for the project's controller layer (`utils/` folder) [246](https://github.com/publiclab/community-toolbox/pull/246)

- **Work in Progress**

  - Writing documentation for the project explaining all the pieces that contribute to community-toolbox. It includes details about the code chunks that are responsible for specific actions and how they add up to make an individual feature in the project. [overview page](https://github.com/Rishabh570/community-toolbox/blob/DOCS/docs/overview.md).
  - User notifications follow-up focused on showing precise information to the user.

- **FTO created**

  - Rename autocomplete.js file. [link](https://github.com/publiclab/community-toolbox/issues/241)
  - Add copy-to-clipboard for recent contributors' list. [link](https://github.com/publiclab/community-toolbox/issues/240).

Hope everyone is doing great. As my remaining work is finishing in a couple of days, I would love to help and study other soc projects. Please feel free to ping.
Thanks!!! :tada:

**Comment by jywarren** [comment]
Hi, everyone! Pushing my limits here to catch up after my time off. I'm so glad to see you all again, and am trying to help resolve critical issues first. I was able to resolve a MapKnitter export bug and am working on Travis tokens today. So eager to see what you've all accomplished. Thank you!

**Comment by SidharthBansal** [comment]
Pushing my limits is to catch up with as many GSoC projects as possible.
There is a lot of pending prs at PLs. Reviewing questions asked on the
issues/prs and help folks new to PL.
Thanks

**Comment by gauravano** [comment]
New check-in at https://github.com/publiclab/plots2/issues/6205. Thank you!!
