### ISSUE TITLE
Featured Topics on publiclab.org/questions page are not visible, but links still work

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#6136]
## Please describe the problem (or idea)

I visited https://publiclab.org/questions and noticed that Featured Topics is blank. When i moused over the area i expected to view tags, i saw that the link are still active because the arrow cursor changed to a hand, and the link previews showed up in the bottom left hand corner of my browser window. Here's a gif: 

![questions](https://user-images.githubusercontent.com/161439/63027865-b47f3080-be7b-11e9-881e-1ebaff26891b.gif)

> What did you expect to see that you didn't?

I expected to see blue buttons with white text displaying the name of each featured tag

### Please show us where to look

https://publiclab.org/questions -- same while logged in and while not logged in. 

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

liz

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

Chrome on Mac 10.13.6

**Comment by ebarry** [comment]
There's a feature to controlling what appears here that has not been editorially changed by staff admins in 11 months. It can be viewed at https://publiclab.org/features --> "Questions Header"
Here's the html that's in that feature: 

<h2>Questions and Answers</h2>
<h4><small>Ask a question of the Public Lab community to help you in your environmental exploration.</small></h4>

<p>New to Public Lab? <a href="/wiki/public-lab-q-and-a">Learn how this works &raquo;</a></p> 

<hr />

<h4>Featured topics</h4>

<p style="font-size:1.1em;">
<span class="label label-primary"><a href="/questions/tag/air-quality">air-quality</a></span>
<span class="label label-primary"><a href="/questions/tag/agriculture">agriculture</a></span>
<span class="label label-primary"><a href="/questions/tag/balloon-mapping">balloon-mapping</a></span>
<span class="label label-primary"><a href="/questions/tag/legal">legal</a></span>
<span class="label label-primary"><a href="/questions/tag/microplastics">microplastics</a></span>
<span class="label label-primary"><a href="/questions/tag/mining">mining</a></span>
<span class="label label-primary"><a href="/questions/tag/noise">noise</a></span>
<span class="label label-primary"><a href="/questions/tag/oil-and-gas">oil-and-gas</a></span>
<span class="label label-primary"><a href="/questions/tag/pm">particulate matter</a></span>
<span class="label label-primary"><a href="/questions/tag/sensors">sensors</a></span>
<span class="label label-primary"><a href="/questions/tag/stormwater">stormwater</a></span>
<span class="label label-primary"><a href="/questions/tag/timelapse">timelapse</a></span>
<span class="label label-primary"><a href="/questions/tag/waste">waste</a></span>
<span class="label label-primary"><a href="/questions/tag/water-quality">water-quality</a></span>

</p>

**Comment by jywarren** [comment]
It looks like this feature was not updated with Bootstrap 4, though other manually curated tags listings were. The format is now `<a class="badge badge-primary" href="/tag/climate">climate</a>` instead of `<span class="label label-primary"><a href="/questions/tag/air-quality">air-quality</a></span>`.

I just adjusted them and they should work now!
