### ISSUE TITLE
Sidebar buttons misplaced in question layout

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6142]
Hi, @CleverFool77 @gautamig54 -- noticed this unexpectedly went a bit odd:

![image](https://user-images.githubusercontent.com/24359/63176520-11adea00-c014-11e9-8a56-fa1e87c866ce.png)

https://publiclab.org/questions/rafabeur/08-16-2019/i-need

Would you mind taking a look? Also, I think it may be worthwhile to consider a cleanup of the questions template to bring it more inline with the note template. I like the "related questions" area but otherwise, it's pretty messy. Do you want to open a new issue to explore what we can do to bring it more in line with the style guide?  Thank you!

**Comment by gautamig54** [comment]
Hi @jywarren! I will look into this misplaced icons. 
We can discuss about the related questions part here only. Can we make a separate page consisting all the related questions and drop a link to the same here on the sidebar. 
Other suggestion is shifting the related questions section below. Like in wiki page : 

![Screen Shot 2019-08-17 at 11 06 15 AM](https://user-images.githubusercontent.com/35326753/63207183-1095bf00-c0df-11e9-8a11-50fcbded0ba0.png)

**Comment by CleverFool77** [comment]
Hi Jeff !!
While considering sidebar in notes and wikis, I guess I forgot considering it Questions page. I'll fix this bug.
Regrading refinement !! Can we have refinement of all pages like `notes` ,`wikis` and `Questions` too ? maybe we can have a draft design and slowly implement it step by step ?
As it can been seen, as now more and more pages are being redesigned. Some of the pages left which are still following old design look oddly different compared to new ones.
Thanks !!!

**Comment by jywarren** [comment]
Yes, i like gradually making these pages more consistent! There may be
reasons to have them not be identical to each other, but we can still clean
them up in the new style guide guidance.

As to separate page for the related questions, I guess I think interlinking
questions is especially important. Let's leave it for now, but maybe we
could brainstorm something - like what about a button that says "13 related
questions" or something like that?

In general the Questions page draws a lot of inspiration from StackOverflow
design. And they show a lot of "similar questions" in the sidebar. Just to
consider! Thanks!
