### ISSUE TITLE
"Share your location" doesn't seem to work on profile page.

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#6150]
The "add location" modal isn't opening when I click on "Share you location" on the profile page. 

![Screen Shot 2019-08-18 at 3 48 32 PM](https://user-images.githubusercontent.com/35326753/63223210-c7716800-c1cf-11e9-9d04-f7af41b72c97.png)

**Comment by gautamig54** [comment]
@CleverFool77 Can you generate this issue?

**Comment by CleverFool77** [comment]
Hi @gautamig54 This one is working. I checked it on latest update !!
It's just bit slow, so you didn't get modal !!!
I'll be closing this.
Thanks !!

![Screenshot from 2019-08-18 17-04-54](https://user-images.githubusercontent.com/26685258/63223926-60a57c00-c1da-11e9-9a56-01436b1b539f.png)
