### ISSUE TITLE
Notification when someone likes your note

### ISSUE THREAD

**Issue by namangupta01** [publiclab/plots2#6152]
Currently, we are showing the notification to the users when they are mentioned in the comments we can extend this feature to receive a notification when any user likes any research note.

**Comment by jywarren** [comment]
This is great, thanks. Did you have an issue open already for notifications
on phones as well as desktop browsers? Thanks!

**Comment by namangupta01** [comment]
Yes, I do have one issue open for notification on phone. I researched it and found out we can't use action cable to make a notification on the phone. Android doesn't allow it. More specifically, someone can create a notification when there is some gesture movement on that app or another way is using FCM or service worker. But I guess this needs some more research. What do you think?

**Comment by jywarren** [comment]
Hm, but https://developer.mozilla.org/en-US/docs/Web/API/notification lists compatibility with phone browsers... is it a push notifications triggering issue? Do we need a PWA to do this fully? Can you collect some info on this in the issue and link to it from here? thank you Naman!!!

**Comment by namangupta01** [comment]
Notification does support in phone. I was saying it's triggering method using socket doesn't work. Why it doesn't work :
In android phone Notification API is only allowed in response to a user gesture. You can see here: https://stackoverflow.com/a/54225858

**Comment by namangupta01** [comment]
But to work this out I found a simple solution using a serviceworker here https://stackoverflow.com/a/31787926. I am trying this solution currently.

**Comment by jywarren** [comment]
aha, ok, makes sense! Thank you!
