### ISSUE TITLE
New front page design!

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6155]
After a LOT of design work, we've settled on a new design for our front page! It incorporates a lot from [our new Style Guide](https://publiclab.org/notes/warren/05-07-2019/introducing-a-draft-style-guide-for-public-lab), but also with a lot of input from @ebarry @steviepubliclab on our communities team at the Public Lab non-profit. 

Here's the mockup (from our [shared mockups doc](https://docs.google.com/presentation/d/1TCZoTfuhamRVrUak8aDgqJAwSgyhRtZg2Pgacl2_4zc/edit#slide=id.g5a6cac5901_4_0)):

![Screen Shot 2019-08-19 at 2 31 40 PM](https://user-images.githubusercontent.com/24359/63289910-3ad9af00-c28e-11e9-99da-dfce32c0d2fe.png)
![Screen Shot 2019-08-19 at 2 32 06 PM](https://user-images.githubusercontent.com/24359/63289914-3ca37280-c28e-11e9-9312-c3d7bba5a747.png)
![Screen Shot 2019-08-19 at 2 32 29 PM](https://user-images.githubusercontent.com/24359/63289920-4200bd00-c28e-11e9-8fc2-cffeabfeec50.png)

OK, so, it breaks into three sections: 

The top is very much like one of our tag pages (see https://publiclab.org/tag/water-quality), plus a 4-column pane. The 4-column area could be [run from a Feature](https://github.com/publiclab/plots2/blob/master/doc/DATA_MODEL.md#features). We're still working on the final text, so let's use placeholder text for everything in this section for now. 

The middle section is a set of 3 bands, each showing content from a wiki page. The title is the wiki page title, the description is the first paragraph of the wiki page, and people are not quite decided yet -- so we can leave them off in the first implementation. We should fetch these as the most recently 3 pages bearing the tag "front-page" (at least for now).

The bottom is a set of columns showing a wide range of topics (tags). This could be a second Feature (https://github.com/publiclab/plots2/blob/master/doc/DATA_MODEL.md#features). 

So this needs breaking up, and we should do it as a shadow page, I think, before we're ready to publish it -- so at, maybe, `/front-shadow`?

@CleverFool77 @gautamig54 what do you think of this? Would you be interested in trying to implement this new design or are you pretty busy at the end of this month?

Thank you!

**Comment by CleverFool77** [comment]
Sure @jywarren This looks great. We can go for it I guess !! Should I break it up in parts ? This design is for home page right ?

**Comment by jywarren** [comment]
That's right! And yes, we can break it up. Actually now that I think about
it, the list of topics was intended to go into the footer, actually! So we
could just add that portion to the footer feature that's already on the
site. What do you think?

**Comment by gautamig54** [comment]
Sure. Should I make a new issue for it adding in the footer?

**Comment by jywarren** [comment]
Sure, and copy in the screenshot? I think it'll be pretty simple HTML and
we can share the HTML in the issue, then paste it into the live site
feature. How does that sound?

**Comment by gautamig54** [comment]
Sounds great!

**Comment by CleverFool77** [comment]
Hi @jywarren How are we supposed to do from third to fifth sections ? Are they default data  to be written in code ?
And If no one took the first section, then I would like to start off with it.
Thanks !!

**Comment by gautamig54** [comment]
> Hi @jywarren How are we supposed to do from third to fifth sections ? Are they default data to be written in code ?

I think it might be added as a feature. Hi @CleverFool77! I am half way there in the first part.

**Comment by CleverFool77** [comment]
Hi @gautamig54 If you are halfway on first part , then should i go for second parts onward ?

**Comment by gautamig54** [comment]
Sure @CleverFool77 !

**Comment by CleverFool77** [comment]
Hi @jywarren I wanted to ask that what do we have add in `feature`, `feature2`  till `feature4` of second section ? For now its just a default icon and default data for template in draft design.

**Comment by gautamig54** [comment]
Hi @jywarren @CleverFool77 Are we making the whole of front page as a feature?

**Comment by CleverFool77** [comment]
It is indeed a feature I guess. 🤔 Right

**Comment by gautamig54** [comment]
We were suppose to make a shadow page right?
Should I add the first portion as a shadow page and open a PR?

**Comment by CleverFool77** [comment]
Hi @gautamig54 This is the feature I guess. So we have to share it in gist
like you did it in footer.
Thanks !!

**Comment by CleverFool77** [comment]
> Yes, actually let's make that whole section into a feature. we are still working on the text for that!

Hi @jywarren Should I just use some default icons then ?

**Comment by gautamig54** [comment]
Cool. I'll do that!!

**Comment by jywarren** [comment]
So sorry! The "Community Projects" section is not a feature. But the rest is! Thank you!!!

**Comment by jywarren** [comment]
For icons, yes, sure! We will find appropriate ones in nounproject.org at a later time. Thank you!

**Comment by CleverFool77** [comment]
Cool. I'll share the gist for this.

**Comment by gautamig54** [comment]
I have implemented the first part. The screenshot is as follows : 

![Screen Shot 2019-09-01 at 2 17 08 AM](https://user-images.githubusercontent.com/35326753/64069048-3aaebb80-cc5f-11e9-8fce-dad840c1f4cd.png)

Link to the gist :https://gist.github.com/gautamig54/fea9094b40c72ab16a805d17a15d50e6

**Comment by gautamig54** [comment]
Hi @jywarren! What projects are to be shown in community projects? Are we not adding it as a feature?

**Comment by jywarren** [comment]
Hi, check out my comment above about this! I think we can code it up pretty easily, not in a feature: https://github.com/publiclab/plots2/issues/6155#issuecomment-524927240

Thank you!

**Comment by discombobulateme** [comment]
Hello all :) I'm a current Outreachy applicant, but also quite fan of PublicLab project. I'm am also currently renewing PyLadies Berlin design and StyleGuide with special attention to accessibility. I took a look at your StyleGuide proposition and found those are super good points to work on design, but missed some accessibility guidelines. Is there something I could do module-contribute in this matter?

**Comment by NitinBhasneria** [comment]
@jywarren Is there some more task left for this issue. If yes please tell and assign them to me.

**Comment by ebarry** [comment]
I think this issue has actually been completely resolved, @jywarren is it safe to close?
