### ISSUE TITLE
Remove geokit-rails gem from the project

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#6165]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Remove the geokit-rails gem from the repository- from Gemfile and Gemfile.lock as it's not used.**

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by Akter8** [comment]
I want to do this. Thank you.

**Comment by Akter8** [comment]
@gauravano could you please tell me why I am getting an error? Thank you.

**Comment by seabl** [comment]
AFAIK there's no need to edit _**Gemfile.lock**_ manually. **_Bundler_** will do that automatically.

**Comment by bendjukastein** [comment]
Let me know if there's anything i can do to help! First timer here :)

**Comment by seabl** [comment]
@bendjukastein please also feel free to look around and claim any of the first-timer-only issues. Thanks!

**Comment by Fsalker** [comment]
> If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

Is there actually a link to the tutorial? I can't see any on my browser. I was actually curious to check it out (:

**Comment by seabl** [comment]
@Fsalker You'll find the full text of the above [here](https://github.com/publiclab/plots2/blob/master/.github/ISSUE_TEMPLATE/--first-timers-only.md) including the link to the tutorial.

**Comment by gauravano** [comment]
Also, I have updated the issue. Apologies for copying wrong markdown earlier for issue creation

**Comment by seabl** [comment]
@gauravano There are 2 templates for FTO issues in the `.github` folder. Which one do we use?

**Comment by Fsalker** [comment]
Thanks!

**Comment by gauravano** [comment]
There's one in .github -- https://github.com/publiclab/plots2/blob/master/.github/first-timers-issue-template.md which we use, another file is .yml file. 

There's a directory by name ISSUE_TEMPLATE which also holds first-timer issue template, that is for GitHub, so that Github can provide option when user hit new issue button

**Comment by seabl** [comment]
Thanks for clarifying this.

**Comment by yprasant0** [comment]
@gauravano is anyone working on this, if not then I would like to go ahead with this. Thanks!!

**Comment by gauravano** [comment]
Hi @yashbth, there's a PR for this already open so please consider claiming other issues. Thank you!!

**Comment by CoderJolly** [comment]
Could someone reference the PR number regarding this issue so that he can be reviewed and this issue be closed. Thanks 😄 😄

**Comment by seabl** [comment]
#6168
