### ISSUE TITLE
Idea: powertag pages for activity (`activity:foo`) can use the "value" of their key:value pair

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#6173]
**Please describe the desired behavior.**

This is a feature idea for convention for powertag pages for `Activity:foo` to 

1. have their lead cards default to the "value" of their key:value pair 
2. have their lead images be pulled from the "value" wiki page of their key:value pair

For instance, view https://publiclab.org/tag/activity:microscope to see that the lead card could have a link back to /microscope, and the lead image be pulled from /microscope. 

<img width="1276" alt="Screen Shot 2019-08-21 at 3 32 48 PM" src="https://user-images.githubusercontent.com/161439/63462449-fafaff00-c428-11e9-8391-5d6bea2a193b.png">

**Additional context (optional)**

Thank you for reading!

**Comment by jywarren** [comment]
We currently have this card pull from a page that's redirected to, which is a similar situation. So, we can look at these lines of code:

https://github.com/publiclab/plots2/blob/8715803d0336c45e854bf0d12375547a3f458624/app/controllers/tag_controller.rb#L76-L82

We can add a condition which detects if it's a `key:value` powertag, like:

```ruby
elsif tagname = params[:id].match(':') && node = Node.where(slug: tagname)&.first
    @wiki = node # skip powertag prefix to find wiki page
```

...I think? This might take some reworking, but it's worth a try!

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by ebarry** [comment]
Thanks to anyone who might be able to reformat this as a first-timers-only issue 💚

**Comment by cesswairimu** [comment]
Hi @ebarry @jywarren, I am trying to reformat this to be a fto need some clarity though...The link we are editing is it `Add a wiki page` button in the screenshot about and from the example should it link to `/tag/microscope`? Thanks

**Comment by Jigyasa-Kumari** [comment]
Hi, I am Jigyasa, and I am an Outreachy 2020 applicant. Is this issue open and can I work on this?

**Comment by Karska-dev** [comment]
Hello! I would like to work with this one.

**Comment by cesswairimu** [comment]
Hi @Karska-dev we would love your help. Go ahead

**Comment by Karska-dev** [comment]
> Hi @ebarry @jywarren, I am trying to reformat this to be a fto need some clarity though...The link we are editing is it `Add a wiki page` button in the screenshot about and from the example should it link to `/tag/microscope`? Thanks

So, if I get it right. This card:

![Screen Shot 2020-10-14 at 6 31 19 PM](https://user-images.githubusercontent.com/4979096/96062948-bb248180-0e4b-11eb-84cb-77934baa7b86.png)

should look exactly like this one:

![Screen Shot 2020-10-14 at 6 31 28 PM](https://user-images.githubusercontent.com/4979096/96063079-fa52d280-0e4b-11eb-8d6d-954e462e80d5.png)

Please, correct me where I am wrong!

**Comment by ebarry** [comment]
HI @Karska-dev , 
Thanks for working on this one! 

This situation is where there's a power tag in the form `key:value` where `value` already has a dedicated wiki page. 

In your example, you are showing the tag page for the powertag `activity:translation`. There is a page publiclab.org/wiki/translation, so the `activity:translation` card should: 

1. pull the preview text from publiclab.org/wiki/translation, same as publiclab.org/tag/translation does. 
2. display a "Learn more" button that links to /wiki/translation instead of "Add a description" button that leads to an editor for creating a new wiki page. 
3. pull the lead image from /wiki/translation same as /tag/translation does
4. Remain labelled on the card as `activity:translation`
