### ISSUE TITLE
Signup modal not showing up

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#6175]
Sign up modal not showing up at any place

@IshaGupta18 confirmed the existence of issue

**Comment by gauravano** [comment]
@jywarren

**Comment by jywarren** [comment]
Is this on the live site? Uh oh... any JS errors?

**Comment by jywarren** [comment]
Confirmed, and no JS errors I can see. Can we check blame views on relevant
templates?

**Comment by gauravano** [comment]
yes, no JS error. yes, checking blame and recent commits

**Comment by jywarren** [comment]
Hmm. `$('#signupContainer').show()` doesn't work. I can't see how it's related to https://github.com/publiclab/plots2/pull/6149/files based on the JS logic but is it really resolved if you go before that?

Can you try reverting just those changes without rolling back commits?

**Comment by gauravano** [comment]
done https://github.com/publiclab/plots2/pull/6177

**Comment by jywarren** [comment]
No wait, $('#signupContainer').show() does work... odd.

**Comment by jywarren** [comment]
And locally it does work?

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/blob/master/app/views/user_sessions/_form.html.erb and https://github.com/publiclab/plots2/blob/master/app/views/users/_create_form.html.erb haven't been touched in months...

**Comment by jywarren** [comment]
Its an id collision:

![image](https://user-images.githubusercontent.com/24359/63465153-9fcc0b00-c42e-11e9-8c6a-9a9529e2dd36.png)

**Comment by jywarren** [comment]
OK, i can change that to a unique ID

**Comment by jywarren** [comment]
Fix in #6178 -- very close to yours Gaurav but preserves the functionality of hte PR in question (#6149).

**Comment by gauravano** [comment]
@jywarren so when we do something like `.container:not(#loginSignupContainer)` --  we are defining CSS for all containers except loginSignupContainer. Right?

**Comment by jywarren** [comment]
yes! 

I added 2 screenshot tests too.

**Comment by gauravano** [comment]
Hmm, don't you think we should avoid such practices and write CSS for each component separately. A new user which will create any new modal will have to write it's own CSS to override this CSS defined in _header

**Comment by jywarren** [comment]
I'm open to other solutions here after the quick fix. I think i agree that
we want to /include/ a specific id for the header page style, instead of
/exclude/. Does your PR do that?

**Comment by gauravano** [comment]
no. that require defining .container in more general css file and checking each modal and changing CSS of those which are distorted so let's tackle that in another issue.
