### ISSUE TITLE
Add condition of no subscriptions and show an info

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#6188]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file /plots2/app/views/home/subscriptions.html.erb

Earlier we just had one table part where subscriptions is being shown, But now we have added an condition that if there is no subscriptions then we should show some info or else show the table.

```html
<table class="table">
  <tr><th><%=raw translation('home.subscriptions.tag') %></th><th><%=raw translation('home.subscriptions.options') %></th></tr>
  <% current_user.subscriptions(:tag).each do |subscription| %>
  <tr>
    <td><a href="/tag/<%= subscription.tagname %>"><%= subscription.tagname %></a> <i style="color:#aaa;"> +<%= Tag.follower_count(subscription.tagname).to_i-1 %> other people</i></td>
    <td><div class="btn-toolbar" style="margin:0;">
      <div class="btn-group">
        <!--
        <a rel="tooltip" title="As it happens" class="btn btn-default btn-xs" href="javascript:void(0)"><i class="fa fa-envelope"></i> Email</a>
        <a rel="tooltip" title="Once per day" class="btn btn-default btn-xs" href="javascript:void(0)"><i class="fa fa-list"></i> Digest</a>
        -->
        <script> input_<%= subscription.tid %> = '#share-<%= subscription.tid %>'</script>
        <a class="btn btn-outline-secondary btn-sm" rel="popover"  data-toggle="popover" data-placement="left" title="<%= t('home.subscriptions.share_subscription_link') %>" data-html="true" data-content="<div style='margin-top:10px;'><a style='padding-left:3px;' href='https://twitter.com/intent/tweet?text=🎈 Public Lab: Subscriptions&url=https://publiclab.org/subscriptions/tag/<%= subscription.tagname %>' class='twitter-share-button'>Tweet</a></div> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='//platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','twitter-wjs');</script>
        <i class="fa fa-share"></i> <%= t('home.subscriptions.share') %></a>
        <a class="btn btn-outline-secondary btn-sm" href="/unsubscribe/tag/<%= subscription.tagname %>" data-method="delete"><i class="fa fa-remove"></i> <%= t('home.subscriptions.unsubscribe') %></a>
      </div>
    </div></td>
  </tr>
  <% end %>
  </table>
```
Replace the lines in above code which are present in lines 43-63 with the lines of code below.
```html
  <% if current_user.subscriptions.length == 0 %>
  <p> You haven't subscribed to any topic yet </p>
  <% else %>
    <table class="table">
    <tr><th><%=raw translation('home.subscriptions.tag') %></th><th><%=raw translation('home.subscriptions.options') %></th></tr>
    <% current_user.subscriptions(:tag).each do |subscription| %>
    <tr>
      <td><a href="/tag/<%= subscription.tagname %>"><%= subscription.tagname %></a> <i style="color:#aaa;"> +<%= Tag.follower_count(subscription.tagname).to_i-1 %> other people</i></td>
      <td><div class="btn-toolbar" style="margin:0;">
        <div class="btn-group">
          <!--
          <a rel="tooltip" title="As it happens" class="btn btn-default btn-xs" href="javascript:void(0)"><i class="fa fa-envelope"></i> Email</a>
          <a rel="tooltip" title="Once per day" class="btn btn-default btn-xs" href="javascript:void(0)"><i class="fa fa-list"></i> Digest</a>
          -->
          <script> input_<%= subscription.tid %> = '#share-<%= subscription.tid %>'</script>
          <a class="btn btn-outline-secondary btn-sm" rel="popover"  data-toggle="popover" data-placement="left" title="<%= t('home.subscriptions.share_subscription_link') %>" data-html="true" data-content="<div style='margin-top:10px;'><a style='padding-left:3px;' href='https://twitter.com/intent/tweet?text=🎈 Public Lab: Subscriptions&url=https://publiclab.org/subscriptions/tag/<%= subscription.tagname %>' class='twitter-share-button'>Tweet</a></div> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='//platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','twitter-wjs');</script>
          <i class="fa fa-share"></i> <%= t('home.subscriptions.share') %></a>
          <a class="btn btn-outline-secondary btn-sm" href="/unsubscribe/tag/<%= subscription.tagname %>" data-method="delete"><i class="fa fa-remove"></i> <%= t('home.subscriptions.unsubscribe') %></a>
        </div>
      </div></td>
    </tr>
    <% end %>
    </table>
  <% end %>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by CleverFool77** [comment]
Do check the `/subscriptions` and put the screenshot in the pr with subscriptions and without any subscriptions(subscriptions count is zero).

**Comment by NitinBhasneia** [comment]
can I do this @CleverFool77 ?

**Comment by CleverFool77** [comment]
Sure nitin. Go forward.

**Comment by NitinBhasneia** [comment]
@CleverFool77  Do we have to run and then take a screenshot or only oof a code??

**Comment by CleverFool77** [comment]
Hi nitin, we need screenshot of the new change or the update you have done.

**Comment by priyanka1204** [comment]
can i work on this issue?

**Comment by CleverFool77** [comment]
Hey @priyanka1204 nitin is working on this currently i guess. Are you @NitinBhasneia ?
If yes, do write it down in comment or else priyanka may start with this.

**Comment by NitinBhasneia** [comment]
Ye, I am working!!

**Comment by CleverFool77** [comment]
Great !!

**Comment by NitinBhasneia** [comment]
@CleverFool77 Here are some errors in starting! Can you guide me to start and to install all dependencies?? Please

**Comment by CleverFool77** [comment]
HI @NitinBhasneia What are the errors ? Did you follow the steps in readme ?

**Comment by CleverFool77** [comment]
Check this part -
### Standard Installation

1. Fork our repo from https://github.com/publiclab/plots2.
2. In the console, download a copy of your forked repo with `git clone https://github.com/your_username/plots2.git` where `your_username` is your GitHub username.
3. Enter the new **plots2** directory with `cd plots2`.
4. Steps to install gems:
    * You may need to first run `bundle install` if you have older gems in your environment from previous Rails work. If you get an error message like `Your Ruby version is 2.x.x, but your Gemfile specified 2.4.4` then you need to install the ruby version 2.4.4 using `rvm` or `rbenv`.
	    * Using **rvm**: `rvm install 2.4.4` followed by `rvm use 2.4.4`
	    * Using **rbenv**:  `rbenv install 2.4.4` followed by `rbenv local 2.4.4`
    * Install gems with `bundle install --without production mysql` from the rails root folder, to install the gems you'll need, excluding those needed only in production.
5. Make a copy of `db/schema.rb.example` and place it at `db/schema.rb`.
6. Make a copy of `config/database.yml.sqlite.example` and place it at `config/database.yml`
7. Run `rake db:setup` to set up the database
8. Install static assets (like external javascript libraries, fonts) with `yarn install`
9. By default, start rails with `passenger start` from the Rails root and open http://localhost:3000 in a web browser.
(for local SSL work, see [SSL](#ssl+in+development) below)
10. Wheeeee! You're up and running! Log in with test usernames "user", "moderator", or "admin", and password "password".
11. Run `rails test` to confirm that your install is working properly. Or `rails test:system` for system tests.

**Comment by NitinBhasneia** [comment]
Your Ruby version is 2.6.3, but your Gemfile specified 2.4.4
this error is coming in the process!!

**Comment by NitinBhasneia** [comment]
@CleverFool77 Ok  I have done all the things but when running localhost it's showing some error.
"@' is not allowed as an instance variable name"

**Comment by CleverFool77** [comment]
Can you show me the screenshot. What's you ruby version ? IS there any mismatch ?

**Comment by NitinBhasneia** [comment]
No, I have corrected version issue?
Just see this 
![Screenshot from 2019-08-24 14-19-29](https://user-images.githubusercontent.com/44112080/63634895-3c361d80-c67a-11e9-9c8e-f0b94a978b1a.png)

**Comment by CleverFool77** [comment]
Hi nitin. Start the server once again. It will be solved after reloading.

**Comment by NitinBhasneia** [comment]
Yeh, I started the server again but the same thing is stuck!!

**Comment by NitinBhasneia** [comment]
sorry, but can you just check this!
![Screenshot from 2019-08-24 15-36-34](https://user-images.githubusercontent.com/44112080/63635866-16fadc80-c685-11e9-8326-67eb9d3f21a2.png)

**Comment by CleverFool77** [comment]
As per the latest update , This thing shouldn't be there :thinking:

**Comment by NitinBhasneia** [comment]
ok I will pull once more than I will try thanks

**Comment by NitinBhasneia** [comment]
Again the
![Screenshot from 2019-08-26 00-27-32](https://user-images.githubusercontent.com/44112080/63654490-7269bf00-c798-11e9-8090-803dca5f4908.png)
 other error is coming

**Comment by Anupam-dagar** [comment]
@NitinBhasneia the error is related to a file not existing. In this case `bootstrap`, I think you forgot to run `yarn install` to install the libraries. Try running `yarn install` and then starting the server. The issue should get fixed.

**Comment by NitinBhasneia** [comment]
Could not start the Nginx engine:
nginx: [emerg] bind() to 0.0.0.0:3000 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:3000 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:3000 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:3000 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:3000 failed (98: Address already in use)
nginx: [emerg] still could not bind()
THIS ERROR IS COMING ON passenger start.
@Anupam-dagar @CleverFool77 pls give solution

**Comment by Anupam-dagar** [comment]
the port is already in use. Kill the process using that port or just do a system restart.

**Comment by CleverFool77** [comment]
Hi @NitinBhasneia Is your bug resolved ?

**Comment by CleverFool77** [comment]
I'll close this issue as the PR for this has been merged.
We can continue the the proble regarding installatioon here or you can solve it with the help of community members in here -.https://gitter.im/publiclab/publiclab
Thanks !!
