### ISSUE TITLE
Create helper to generate tag cards

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6199]
The tag cards on https://publiclab.org/tags can often show the same post multiple times per page. Let's do this:

1. the tag cards could be generated by a view helper called `createTagCard()`
2. the view helper could accept as a parameter an `createTagCard(exclude)` array of `nids` that we should exclude
3. the view helper could return a list of `nids` that it will be displaying, which can be added to a list of `nids` that should be excluded from subsequent tag cards.

So the flow would look like:

```ruby
exclude = []
exclude += createTagCard('balloon-mapping', exclude)
exclude += createTagCard('air-quality', exclude)
```

@CleverFool77 @gautamig54 what do you think of this?

**Comment by jywarren** [comment]
Here's the issue, by the way - duplicate appearance of nodes on my profile page demonstrates it!

![image](https://user-images.githubusercontent.com/24359/63620750-29f7a900-c5c0-11e9-8310-2574240411d1.png)

**Comment by CleverFool77** [comment]
Ohh Yes, It would be better. Besides we are using tag cards everywhere. This would decrease our load somehow.

**Comment by gautamig54** [comment]
Yes, This seems like a good solution. And with the shifting of website structure to being it topic oriented, this will prove to be a great and help reduce redundancy.

**Comment by jywarren** [comment]
Awesome!

**Comment by jywarren** [comment]
Ah, the fix didn't work in profile pages but it did on /tags!
