### ISSUE TITLE
Weekly community Check-In #33 - Summer of Code Wrap-Up 💼

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#6205]
Hi everyone 👋 !

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️ .

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. 💯

If you're new here, welcome, and please comment a Hello below, we would love to work with you. If you're looking for new issues, please try some of our first-timers-only issues.

We're SO EXCITED to have your help!

Is there anything, you would like to share with us from past week's work? What is your plan for this week?

If you have not planned yet, just leave a Hello! 👋 so that we know that you are in sync with us 🔃 and doing well!

As always, if you're waiting for a review, or if you're stuck, please request help here OR leave a comment with @publiclab/mentors @publiclab/reviewers for some input. 🙌

**Gitter**
Gitter is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up there for these updates or just to join the conversation. You can also join us through http://publiclab.org/chat 💬.

You can find our list of previous check-ins [here](https://github.com/publiclab/plots2/issues/5627).

## Note to Summer of Code interns:

All the work you did during the summer is really great and projects/features you made shine on different platforms be it plots2, mapknitter, image-sequencer, simple-data grapher, image-matcher, etc. 

**Now, it's time to wrap the summer right way, so make sure you followed all the below N steps ✅:**

**0...N-3:** https://publiclab.org/notes/warren/08-20-2019/wrapping-up-outreachy-and-gsoc-2019 

Yes, just read the above post as it sums up everything we expect from you.

**N-2:** Post the link to your project's work product below. You can also tweet it, don't forget to mention @publiclab 😄. 

**N-1:** Start preparing a 5-min presentation about your project with live demo/ GIF / Video of your work as we will be having a Summer of Code Wrap-up call very soon, probably September 3, 2019. You can take help/review from mentors regarding the presentation. Don't worry, it will be fun!!

**Join us for Open Code Call/ Weekly scrum on Tuesday** - http://publiclab.org/opencall

Thanks 🎈 🎉 🚀

**Comment by gauravano** [comment]
@milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @shubhscoder @sidntrivedi012 @SidharthBansal @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77 @ananyaarun @ananya @publiclab-mimi @ananya @hc-barker @starkblaze01 @asquare @pdurbin @HarshKhandeparkar

**Comment by gauravano** [comment]
@newbazz @aSquare14 @vaarigupta @alonpeer @aashna27 @harshithpabbati @jesus-montano @cryptoclidus @mohamed-elalem @konolga @gowtham5699

**Comment by gauravano** [comment]
@edwd42 @seabl @simonastefan @Anupam-dagar

**Comment by Anupam-dagar** [comment]
Hi core team at Publiclab. I would like to contribute here to code as well as by reviewing the PR's. I already have couple of PR's merged.
@gauravano I would like to have a small discussion regarding https://github.com/publiclab/plots2/issues/6126

**Comment by gauravano** [comment]
You are very welcome @Anupam-dagar. Sure, let's have a discussion at #6126. If you want to have a call, feel free to ping me. Thanks!

**Comment by CleverFool77** [comment]
Hi @gauravano @jywarren !!

Regarding the project work of me and @gautamig54 , Should both of us write one post ? As we usually divided each and every sections into further parts ? Because the work was for same section but different parts. So description would be similar.

Or should we write different ones mentioning work done ?

Also we do have one project link below showing all the issues and PRs. We had many discussions in issue itself rather chats.
Project link -  https://github.com/publiclab/plots2/projects/10

**Comment by rexagod** [comment]
Hey all! Here's my Final Work Product: https://publiclab.org/notes/rexagod/08-25-2019/google-summer-of-code-2019-public-lab-final-work-product-pranshu-srivastava

***

**Comment by niravasher** [comment]
Congratulations to all GSoC'ers for wrapping up their projects. I am sure all of you have worked very hard for completing their proposals on time. A big shout out to everyone from my side. Also amazing job by all the mentors. Hearty congratulations once again

**Comment by cesswairimu** [comment]
Congrats to the Outreachy and GSoC interns :tada: :tada: :tada: :balloon:  you all did a great job. I was always looking forward to Tuesdays so I can hear all the awesome stuff happening in your different projects :smile:.
Great week ahead all :v:

**Comment by ViditChitkara** [comment]
hi everyone, I've written GSoC wrap-up post [here](https://publiclab.org/notes/vidit/08-26-2019/gsoc-2019-wrapup). And congratulations to all the summer of code and outreachy interns. 😄 🎉 🎉 🎈 🎈

**Comment by divyabaid16** [comment]
Hello everyone!
Congratulations to everyone for being such a great team. 
Please find my final GSoC report: https://publiclab.org/notes/divyabaid16/08-24-2019/gsoc-2019-mapknitter-image-management-divya-baid?_=1566650343
Thank you :tada: :tada:

**Comment by CoderJolly** [comment]
Congratulations to all GSoC'ers and Outreachy interns for wrapping up their projects. 😄 🎉 🎉 🎈 🎈A round of applause to everyone for reaching this far and a big thank you to all the moderators. @jywarren @gauravano @SidharthBansal

**Comment by CleverFool77** [comment]
> Hi @CleverFool77 it's fine if you want to write a joint post, but if you do, some portion of the post should be clearly written by each of you speaking to your personal experience. Does that make sense? Thank you!

We'll write separate posts I guess ? What do you say @gautamig54 . The sections will be similar but the parts mentioned would be different. By this, It would help us in having better explanation and detailed experience that how we tackled that part.

**Comment by gautamig54** [comment]
> > Hi @CleverFool77 it's fine if you want to write a joint post, but if you do, some portion of the post should be clearly written by each of you speaking to your personal experience. Does that make sense? Thank you!
> 
> Hi @jywarren !!
> We'll write separate posts I guess ? What do you say @gautamig54 . The sections will be similar but the parts mentioned would be different. By this, It would help us in having better explanation and detailed experience that how we tackled that part.

Sounds cool! :D

**Comment by Rishabh570** [comment]
Hi all, 
My work product is available [here](https://publiclab.org/notes/icode365/08-25-2019/community-toolbox-work-product). 
Congratulations to everyone :tada: :smile:

**Comment by SidharthBansal** [comment]
Congrats for wrapping up SoC so well this summer. This Gsoc was the Gsoc
ever at PL. Similarly Outreachy.
Best of luck for results.
Don't forget to submit final evals in official websites

**Comment by gauravano** [comment]
**Announcement regarding Summer of Code presentations:**

Hi everyone, we will be having SoC presentation call on September 3, 2019 at 9:15 PM IST(11:45 AM EST, 3:45 PM UTC) 

**Date and Time:** https://everytimezone.com/s/96b47522
**Call Notes:** http://publiclab.org/opencall 
**Call Link:** https://zoom.us/u/4PA9bWsb

All the Public Lab staff, Summer of Code(GSoC and Outreachy) mentors and students are requested to join the call. Other contributors, and interested people are very much welcome to join. Students please prepare a short 5-min presentation regrading your project.

Thanks!!

**Comment by IshaGupta18** [comment]
Hey everyone! I have written my blogpost [here](https://publiclab.org/notes/IshaGupta18/08-26-2019/google-summer-of-code-2019-final-work-product-isha-gupta). Do take a look if you can! Congratulations to everyone for having an amazing summer!

**Comment by SidharthBansal** [comment]
Thanks everyone for writing beautiful docs. You all did an amazing job.
We are having GCI ahead so we all want that you will participate in it as a mentor.
More on GCI soon. Thanks all.

**Comment by SidharthBansal** [comment]
Here is the call for mentors : https://github.com/publiclab/plots2/issues/6238
This is the new task list : https://github.com/publiclab/plots2/issues/6239
A ton of help is required to copy paste the issues to #6239 which can be rolled into gci tasks. 

Thanks all. I hope you all are eager for GCI as I am!!!

**Comment by CoderJolly** [comment]
> **Announcement regarding Summer of Code presentations:**
> 
> Hi everyone, we will be having SoC presentation call on September 3, 2019 at 9:15 PM IST(11:45 AM EST, 3:45 PM UTC)
> 
> **Date and Time:** https://everytimezone.com/s/96b47522
> **Call Notes:** http://publiclab.org/opencall
> **Call Link:** https://zoom.us/u/4PA9bWsb
> 
> All the Public Lab staff, Summer of Code(GSoC and Outreachy) mentors and students are requested to join the call. Other contributors, and interested people are very much welcome to join. Students please prepare a short 5-min presentation regrading your project.
> 
> Thanks!!

Where can we find the Zoom recording for the GSOC wrap-up and student presentations ?

**Comment by SidharthBansal** [comment]
Hi!!
Who is going to open this weeks checkin?
I will like to open it for Google Code In.
if anyone else is free then feel free to comment and open it.

**Comment by gauravano** [comment]
Go ahead @SidharthBansal. Thanks!!

**Comment by IshaGupta18** [comment]
Can I open it?

**Comment by gauravano** [comment]
Here's the recording of **GSoC and Outreachy presentations:** https://youtu.be/MaxNmU8x_pk @CoderJolly

**Comment by gauravano** [comment]
Sure @IshaGupta18 maybe @SidharthBansal can edit it afterward. Just discuss with him before opening. Thanks!!

**Comment by IshaGupta18** [comment]
Sure, absolutely! Thank you!

**Comment by SidharthBansal** [comment]
Moved to #6270
