### ISSUE TITLE
Create "first-timers-only" issues for newcomers 👋

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#6206]
(This issue is in continuation of https://github.com/publiclab/plots2/issues/4963)

Hi everyone!

We, at Public Lab, are known for welcoming new contributors into the Open Source world but a number of times, newcomers were not able to find `first-timers-only` issues to start their journey or face troubles making their first contribution with us. 

Reasons being:
1. Lack of `first-timers-only` issues
2. Struggle in finding the good issue to start and lack of enough support?

We are working on both of the above aspects to support and help the maximum number of people to take their first step in their OSS journey with us, through our various [projects](https://github.com/publiclab/) but we need more support for this. So, this is a call to all the Public Lab members to try and create a first-timers-issue for someone who wants to start their journey and waiting for an FTO being assigned to them.

**If you are interested in creating `first-timers-only` issue, follow these instructions:**
1. Browse through the publiclab.org and see if there's a bug which can be easily solved
2. Solve this issue but don't create a PR this time, instead create a FTO issue
3. Click on this [link](https://github.com/publiclab/plots2/issues/new) to start creating a new issue
4. We follow a specific template for FTO issues, so copy the template from [here](https://github.com/publiclab/plots2/blob/master/.github/first-timers-issue-template.md) 
5. Edit the issue body to add the goal of the issue, code snippet required, file to be updated, add screenshots(if required). Don't add code snippet required to solve in case, the issue just requires minor HTML or CSS change or equivalent.
6. Add a catchy and relevant title to the issue but don't include "FTO" , "first-timers-only" or equivalent in title
7. Get the issue you just created labeled by mentioning @publiclab/reviewers or @publiclab/plots2-reviewers. 
- If you have labeling privileges, feel free to do so yourself but ensure that you have used FTO template. 
- If you are not able to mention the above-mentioned teams, and doesn't have labeling privileges, then drop a line in Gitter channel - https://gitter.im/publiclab/publiclab or mention @jywarren @gauravano @SidharthBansal and any one of us will surely follow-up with you. You can also mention any other member, you can think of with labeling privileges.
8. It's time to invite a new contributor to your issue. If there are unchecked names in the below list, then those people are still looking for FTO issue to start with, so mention them in your FTO by writing - `This issue is created for @[contributor-name]. Thanks!` 
Also, if you see, a new contributor is looking for an issue, feel free to point them to your FTO. 

### Contributors looking for `first-timers-only` (FTO) issues

- [x] @tauhir - #6359
- [x] @augustozanellato - https://github.com/publiclab/leaflet-environmental-layers/issues/238
- [x] @nstjean -https://github.com/publiclab/mapknitter/issues/1050
- [x] @stefanosu - https://github.com/publiclab/mapknitter/issues/1057
- [x] @alexido19 - https://github.com/publiclab/mapknitter/issues/1065
- [x] @Akashutreja - https://github.com/publiclab/mapknitter/issues/1066
- [x] @fadib - https://github.com/publiclab/mapknitter/issues/1067
- [x] @skai-ste - https://github.com/publiclab/plots2/issues/5047
- [x] @mahimahans111 - https://github.com/publiclab/plots2/issues/5215
- [x] @Lisa-Caton - https://github.com/publiclab/plots2/issues/5795
- [x] @pkayres - https://github.com/publiclab/plots2/issues/5137
- [x] @jeffogah - https://github.com/publiclab/plots2/issues/6080
- [x] @IvetaHron - https://github.com/publiclab/plots2/issues/6440
- [x] @Linda-Ikechukwu - https://github.com/publiclab/plots2/issues/5191
- [x] @crisner
- [x] @vishakhanihore - https://github.com/publiclab/plots2/issues/6444
- [x] @shailzaa
- [x] @saivoleti17 - https://github.com/publiclab/mapknitter/issues/1086
- [x] @chrisnorwood - https://github.com/publiclab/plots2/issues/6461
- [ ] @DanielKlys7
- [x] @Diegoafv - https://github.com/publiclab/mapknitter/issues/1094
- [x] @saramace
- [x] @lojosmit 
- [x] @kyebrowning
- [x] @jon-flores - https://github.com/publiclab/mapknitter/issues/1098
- [x] @textuallyactive
- [x] @Lafexlos
- [x] @anushtha1011
- [x] @ChamuMutezva
- [x] @anikerr
- [x] @megha070
- [x] @yagosansz
- [x] @aman-k334
- [x] @saivoleti17
- [x] @Him010
- [x] @aisayo
- [x] @boolean5
- [ ] @reginareynolds
- [x] @ivaibhavkr
- [ ] @satcasm
- [ ]  @preetiy 
- [ ]  @sap143
- [ ] @rojasTob 
- [ ] @giantthinker
- [ ] @AxelleDRouge
- [ ] @RaquelFilipaMendes
- [ ] @avinash080 
- [ ] @aviveller
- [ ] @AudreySchmook
- [ ] @ahrocha96 
- [ ] @jayg98 
- [x] @YuetChan 
- [ ] @infy815
- [ ] @MarieSell 
- [ ] @nyjackson
- [ ] @Thebohemiangeek 
- [ ] @loranazarenko 
- [ ] @mehnazyunus 
- [ ] @starkah 
- [ ] @jaywahr 
- [ ] @govgoel 
- [ ] @Anjalizi 
- [ ] @anuk79
- [ ] @ajitsinghkaler
- [] @puneeth2001

**To first-time contributors:** If you are looking for FTO and want your name to be added to the above list then, feel free to comment below to show your interest. If you are looking for working on a specific language/framework, mention that too in your comment.

**To Public Lab members who have comment edit privileges:** Please add names of newcomers who have shown into for FTO in the below comments. Also, add the names of other newcomers who are looking for FTO and shown their interest by commenting on other issues.

For any query, feel free to ask below or at Public Lab Gitter channel - https://gitter.im/publiclab/publiclab

Thank you and welcome to Public Lab 🎈😄

**Comment by tauhir** [comment]
Hi! I'd like to be given an FTO issue, please.

**Comment by augustozanellato** [comment]
Me too!

**Comment by gauravano** [comment]
Hi @tauhir @augustozanellato, I have added the names of both of you. You will be assigned an FTO issue soon. Thanks!

**Comment by ananyaarun** [comment]
Here is an FTO https://github.com/publiclab/plots2/issues/6359
@tauhir You can take this one !!

**Comment by ananyaarun** [comment]
Here is another one https://github.com/publiclab/leaflet-environmental-layers/issues/238
@augustozanellato You can take this !!

**Comment by nstjean** [comment]
I am looking for one too!

**Comment by IshaGupta18** [comment]
Hey! We'll be creating some FTOs really soon! In the meantime, you can set
up different repos!

**Comment by stefanosu** [comment]
Hi, @gauravano I'm eager to start working on FTO issues as well thanks in advance.

**Comment by alexido19** [comment]
@gauravano I'm looking for a first timer issue too

**Comment by Akashutreja** [comment]
Hey I am looking for FTO issues, thanks

**Comment by gauravano** [comment]
Welcome, @nstjean @stefanosu @alexido19 @Akashutreja added your names and we'll try to assign you issues as soon as possible. Thanks!

**Comment by fadib** [comment]
Hey all, I'm looking for a first-timers-only issue, thanks!

**Comment by skai-ste** [comment]
Hi, I am looking for First-Timer issue too, thank you!

**Comment by cesswairimu** [comment]
@nstjean you can take this one https://github.com/publiclab/mapknitter/issues/1050 . Thanks

**Comment by cesswairimu** [comment]
@stefanosu here is one for you https://github.com/publiclab/mapknitter/issues/1057

**Comment by mahimahans111** [comment]
Hi, I got my initial application of Outreachy approved and I am looking for a first-Timer issue. Please help!

**Comment by cesswairimu** [comment]
@mahimahans111 I have added your name to your to the list.. we will try to get you an issue soon

**Comment by JeffOgah** [comment]
Hello, I'm looking for a FTO too

**Comment by SidharthBansal** [comment]
@JeffOgah I have added your name to your to the list.. we will try to get you an issue soon

**Comment by nstjean** [comment]
I created a FTO for anyone else to use. Hope I did it correctly!
https://github.com/publiclab/plots2/issues/6413

**Comment by cesswairimu** [comment]
@alexido19  here is an issue for you https://github.com/publiclab/mapknitter/issues/1065

**Comment by cesswairimu** [comment]
@Akashutreja here you go https://github.com/publiclab/mapknitter/issues/1066

**Comment by cesswairimu** [comment]
@fadib here is an issue https://github.com/publiclab/mapknitter/issues/1067

**Comment by IvetaHron** [comment]
Hello! I am Outreachy applicant and I am looking for Firts-Timers issue. Thank you for you help.

**Comment by Linda-Ikechukwu** [comment]
Hi, I am an Outreachy applicant and i would love to be assigned a FTO isuue. Thanks

**Comment by crisner** [comment]
Hi I am an Outreachy applicant. I haven't made any contributions to publiclab yet and I am looking for an issue in the frontend to start contributing. Thank you.

**Comment by vishakhanihore** [comment]
Hello, I am an outreachy applicant. I would be glad if I could get a `Good First Issue` or `FTO`

**Comment by shailzaa** [comment]
Hi. I am new to open source and I am looking for a FTO issue.

**Comment by cesswairimu** [comment]
@IvetaHron @Linda-Ikechukwu @crisner @vishakhanihore @shailzaa I have added your names on the list.

**Comment by cesswairimu** [comment]
@skai-ste you can work on this one https://github.com/publiclab/plots2/issues/5047

**Comment by crisner** [comment]
@cesswairimu Thank you for adding me to the list! I got the go ahead on an issue on the leaflet environment layers repo and I am working on it. You can take my name off the list, Thanks.

**Comment by cesswairimu** [comment]
Awesome thanks for letting me know @crisner

**Comment by cesswairimu** [comment]
@Lisa-Caton here is an issue for you https://github.com/publiclab/plots2/issues/5795

**Comment by cesswairimu** [comment]
@pkayres  here is your issue https://github.com/publiclab/plots2/issues/5137

**Comment by saivoleti17** [comment]
Hi I'm new to Open source, looking for an FTO.

**Comment by cesswairimu** [comment]
Hi @saivoleti17 added your name to the list

**Comment by vishakhanihore** [comment]
Any issue for me?

**Comment by cesswairimu** [comment]
@JeffOgah here you go https://github.com/publiclab/plots2/issues/6080

**Comment by chrisnorwood** [comment]
I'd love to start contributing to open source.  Are there any issues I can work on?

**Comment by DanielKlys7** [comment]
I'd love to work on some open source in JavaScript and maybe in React!

**Comment by Diegoafv** [comment]
Looking for one!

**Comment by saramace** [comment]
I also would love to start contributing to open source! Let me know if there is anything I can do as a first issue.

**Comment by cesswairimu** [comment]
@IvetaHron  here is an issue for you https://github.com/publiclab/plots2/issues/6440

**Comment by lojosmit** [comment]
Hi, if possible could I please be granted an issue to resolve. I would like to do this from the CLI to get used to running and commiting locally. Much appreciated.

**Comment by IvetaHron** [comment]
Hi @cesswairimu, thank you for creating a first-timers-only issue for me, but @lojosmit solved it already. Would you possibly have another one, that I can start working on it? Thank you.

**Comment by jywarren** [comment]
Here is one for @vishakhanihore ! https://github.com/publiclab/plots2/issues/6444 Thank you!!!

**Comment by nstjean** [comment]
Here is one @shailzaa https://github.com/publiclab/plots2/issues/6446

**Comment by kyebrowning** [comment]
I'd like to be added to the list. Open to anything but have familiarity with JavaScript, CSS and HTML if that matters.

**Comment by cesswairimu** [comment]
@IvetaHron sorry about that...here is another issue https://github.com/publiclab/plots2/issues/6449

**Comment by jon-flores** [comment]
Hi there, I'm looking into some FTO issues. Would love to help contribute to open source projects. 
Let me know if there's anything I can do! 

Thank you

**Comment by cesswairimu** [comment]
Hello  @chrisnorwood, @DanielKlys7, @Diegoafv, @saramace, @kyebrowning @jon-flores. I have added your names in the list will try and get ypu issues as soon as possible. Welcome

**Comment by cesswairimu** [comment]
@saivoleti17 here https://github.com/publiclab/mapknitter/issues/1086. Thanks

**Comment by textuallyactive** [comment]
Hey! Can you add me too? I'm quite new to OSS, though I've contributed a few times before. Thanks.

**Comment by Lafexlos** [comment]
Hey all! I'd love to be given an FTO issue, please. 
Worked with GitHub but never contributed to open-source projects and created PRs before.

**Comment by anushtha1011** [comment]
hey i am looking for a First time issue and would like my name to be added to the list

**Comment by ChamuMutezva** [comment]
Looking for a First time issue. Preferably anything in the range of html, css, javascript, typescript and angular

**Comment by anikerr** [comment]
I am looking for an FTO, please. JavaScript would be awesome, but also happy to do HTML or CSS fixes. Thank you!

**Comment by cesswairimu** [comment]
@chrisnorwood here is one https://github.com/publiclab/plots2/issues/6461

**Comment by cesswairimu** [comment]
@Diegoafv, here is one in mapknitter https://github.com/publiclab/mapknitter/issues/1094

**Comment by cesswairimu** [comment]
@DanielKlys7 here is one https://github.com/publiclab/Leaflet.DistortableImage/issues/409. Leaflet.Distortable project is pure js and you could find more js issues there...I don't think we have a react project yet but there are a bunch of js ones. Or you can browse on plots2 for issues with the tag `javascript` .Thanks

**Comment by megha070** [comment]
Hey All!
I am looking for some FTO issues, kindly assign me one.

**Comment by yagosansz** [comment]
Hello,
Any FTO issues up for grabs?

Thanks!

**Comment by aman-k334** [comment]
Hey ! I would like to work on FTO issue too.

**Comment by saivoleti17** [comment]
Can i have any FTO issue?

**Comment by Him010** [comment]
Hey I am looking for FTO issues, thanks

**Comment by aisayo** [comment]
Hello, I am a beginner and would like to find FTO issues, Thank you!!

**Comment by boolean5** [comment]
Hi all, I am an Outreachy applicant and I'm very interested in Public Lab's project. I would also like to work on an FTO issue if that's possible. Thanks in advance.

**Comment by nstjean** [comment]
@kyebrowning Here's one for you https://github.com/publiclab/plots2/issues/6484

**Comment by nstjean** [comment]
@saramace Here's an issue for you: https://github.com/publiclab/plots2/issues/6486

**Comment by reginareynolds** [comment]
Hi, I've dabbled in open source before but I haven't contributed to this codebase yet. I would also like to throw my name into the hat of people looking to get a FTO issue! 😄

**Comment by ivaibhavkr** [comment]
Hi!
I'd like to contribute to an FTO issue. 
Kindly add me to the list.

**Comment by cesswairimu** [comment]
Sorry guys, I was not able to use my laptop, out of charge, new country, different sockets, charger not compatible :expressionless: ...Anyway,thanks all for getting the ftos going @nstjean :+1: , will add the new names to the list . Thanks all

**Comment by cesswairimu** [comment]
@jon-flores here is one https://github.com/publiclab/mapknitter/issues/1098

**Comment by preetiy** [comment]
Hello! I would like to contribute to the FTO issues. Please add me to one.

**Comment by boolean5** [comment]
Hi @cesswairimu, you suggested issue #6498 for me but someone got there before me and resolved it. Can you please remove the check next to my name on the list, as I'm still waiting for an FTO? Thanks!

**Comment by rojasTob** [comment]
Hi. I would like to contribute. Is there an FTO issue available? Please, assign me to one.

**Comment by nstjean** [comment]
Here's one for @textuallyactive https://github.com/publiclab/plots2/issues/6516

**Comment by sap143** [comment]
Hi I also want to contribute.Please, assign me to one.

**Comment by nstjean** [comment]
Here is one for @Lafexlos https://github.com/publiclab/plots2/issues/6518

**Comment by giantthinker** [comment]
Hi, I also want to contribute.

**Comment by AxelleDRouge** [comment]
Hi, I also would like to contribute, please

**Comment by RaquelFilipaMendes** [comment]
Hi, I wanted to start my journey in contributing to open source.

**Comment by avinash080** [comment]
Hi, i wanted to start my contribution plz add my name in list

**Comment by avinash080** [comment]
hi , I also want to contribute to open source

**Comment by aviveller** [comment]
Hello

I would love to try my first contributing, 

Thank you

**Comment by AudreySchmook** [comment]
Looking for a FTO, please and thanks!

**Comment by ahrocha96** [comment]
Hi, I'm looking to contribute! Thanks so much!

**Comment by jayg98** [comment]
Hello, I would appreciate the opportunity to contribute! Thanks!

**Comment by YuetChan** [comment]
Hi, I would like to contribute to the project. Thank you!

**Comment by infy815** [comment]
Hi, I would like to contribute. I could help in design, javascript and react

**Comment by MarieSell** [comment]
Hi, I would like to contribute my first time! Thank you, for this exciting opportunity.

**Comment by nstjean** [comment]
Here is one for @anushtha1011 https://github.com/publiclab/plots2/issues/6531

**Comment by nstjean** [comment]
Here is one for @ChamuMutezva https://github.com/publiclab/plots2/issues/6532

**Comment by nyjackson** [comment]
Hi, I'm also ike to participate! Thank you for this opportunity! I am familliar with Python, Java and C++.

**Comment by Thebohemiangeek** [comment]
Hey i would like to participate, im familiar with Js and Python.

**Comment by cesswairimu** [comment]
@anikerr here is one https://github.com/publiclab/plots2/issues/5185 ...the tests may fail after the addition just ping me and I will help. Thanks

**Comment by CodeMeKathy** [comment]
Hi! I am new to this codebase and have not previously contributed.  I would very much like to contribute to an FTO issue. I am most familiar with HTML, CSS, JS, and front-end frameworks.

**Comment by loranazarenko** [comment]
Hello, I'm from Outreachy and I am looking for a FTO issue. Thanks.

**Comment by mehnazyunus** [comment]
Hi, I'm looking for a first-timers issue! I've worked with HTML. CSS, JS, Python. Open to learning Ruby.

**Comment by starkah** [comment]
Hello, 
I would love to be added to this list as I'm a first timer too who is looking for a place to start.

**Comment by nstjean** [comment]
@megha070 One for you! https://github.com/publiclab/plots2/issues/6549

**Comment by nstjean** [comment]
@yagosansz Here's one for you: https://github.com/publiclab/plots2/issues/6550

**Comment by nstjean** [comment]
@aman-k334 Here's one for you: https://github.com/publiclab/plots2/issues/6548

**Comment by nstjean** [comment]
@saivoleti17 And one for you! https://github.com/publiclab/plots2/issues/6551

**Comment by jaywahr** [comment]
@nstjean May you please add me to the wait list 😃 Thank you!

**Comment by govgoel** [comment]
I would love to do my first contribution as I am a first timer too and I am familiar with C++,python,Django Please add me to the waitlist looking for to start soon.

**Comment by Anjalizi** [comment]
Looking for an FTO.

**Comment by anuk79** [comment]
Hi, I would like to contribute to the project and work on FTO issue.
I am familiar with Javascript, React, Typescript, Css, Html
Thank you!

**Comment by crisner** [comment]
@Him010 Here's an issue [#272](https://github.com/publiclab/leaflet-environmental-layers/issues/272) in [publiclab/leaflet-environmental-layers](https://github.com/publiclab/leaflet-environmental-layers).

**Comment by crisner** [comment]
Here's is another issue in the LEL project, [issue #271](https://github.com/publiclab/leaflet-environmental-layers/issues/271). Anyone looking to contribute please comment on the issue if you would like to work on it. Thank you!

**Comment by ajitsinghkaler** [comment]
Hi, I would like to be assigned a FTO.
I am familiar with Javascript, Angular, Typescript, CSS, Html.

Thankyou.

**Comment by cesswairimu** [comment]
@ajitsinghkaler take this one https://github.com/publiclab/leaflet-environmental-layers/issues/271, thanks so much @crisner

**Comment by cesswairimu** [comment]
Hey @RaquelFilipaMendes @avinash080  @aviveller @AudreySchmook @ahrocha96 @jayg98 @YuetChan @infy815 @MarieSell @nyjackson @Thebohemiangeek @loranazarenko @mehnazyunus @starkah @jaywahr @govgoel @Anjalizi @anuk79 @ajitsinghkaler. Welcome to Publiclab :balloon:, I have added your names to the list  please be patient as we find issues for you. In the meantime, you can browse through the issues and if you see something you can work on and is not assigned to someone...leave a comment saying ypua re working on it...feel free to ping us if you need more context on an issue. Thanks

**Comment by cesswairimu** [comment]
@boolean5 you can solve this one https://github.com/publiclab/plots2/issues/6551. Thanks

**Comment by Anand-Theertha** [comment]
Hello! I am looking for making some contributions as well. :D

**Comment by Aj163** [comment]
Hi, I am looking for First-Timer issue!

**Comment by crisner** [comment]
@cesswairimu Please assign another issue for @ajitsinghkaler . @YuetChan seems to have commented on the issue first. Thanks!

**Comment by ajitsinghkaler** [comment]
No problem just remove the tick from my name @cesswairimu and add it to @YuetChan

**Comment by cesswairimu** [comment]
Cool @crisner, done...thanks all

**Comment by adersh-m** [comment]
Hi all, I'm also looking for FTO... Its my first time contributing to Open source projects..

**Comment by cee-elle** [comment]
Hi, I'm also looking for my first contribution, please let me know if anything comes up!

**Comment by ardelapaz** [comment]
I'm looking for my first issue. React preferred, but anything Javascript or Ruby is okay too.

**Comment by nstjean** [comment]
I have two issues that no one responded to. If you want to claim one just leave a comment on it before working on it. Thanks!

https://github.com/publiclab/plots2/issues/6550
 
https://github.com/publiclab/plots2/issues/6548

**Comment by cesswairimu** [comment]
@reginareynolds @ivaibhavkr , could you take the above :point_up: mentioned respectively? Thanks

**Comment by ivaibhavkr** [comment]
I'll like take #6548 
Thanks!

**Comment by cesswairimu** [comment]
cool. thanks

**Comment by nicoleiocana** [comment]
I would enthusiastically like to be added to your FTO list. I am proficient with the ruby language, the Rails 5 framework, Bootstrap 4. I have slight experience with JavaScript (jQuery & React libraries).

**Comment by klaffert** [comment]
Hi, I would like to be added to the FTO list -- I am looking for issues with HTML, CSS, Javascript, Ruby or React. 

Thanks!

**Comment by nstjean** [comment]
I created some more FTOs!
https://github.com/publiclab/plots2/issues/6604
https://github.com/publiclab/plots2/issues/6603
https://github.com/publiclab/plots2/issues/6602
https://github.com/publiclab/plots2/issues/6601
https://github.com/publiclab/plots2/issues/6600
https://github.com/publiclab/plots2/issues/6599
https://github.com/publiclab/plots2/issues/6598
https://github.com/publiclab/plots2/issues/6597
https://github.com/publiclab/plots2/issues/6596

**Comment by jywarren** [comment]
Oh my gosh that's amazing!!!

**Comment by susanreenesaa** [comment]
Sorry about the changes I had made above

**Comment by cesswairimu** [comment]
Here is another fto https://github.com/publiclab/plots2/issues/6688

**Comment by rebecarancan** [comment]
Hello, I'm looking for FTO issues

**Comment by Abhinav1299** [comment]
I would like to be added to the FTO list. I am looking for issues with HTML and  CSS.

**Comment by nstjean** [comment]
This one is still open! https://github.com/publiclab/plots2/issues/6601

**Comment by Devang-25** [comment]
Hey I am looking for FTO issues, thanks

**Comment by cesswairimu** [comment]
These two issues are still open https://github.com/publiclab/mapknitter/issues/1059, https://github.com/publiclab/mapknitter/issues/1065

**Comment by priyajitm** [comment]
Hi! I am looking for FTO issue to contribute, Thanks!!

**Comment by nstjean** [comment]
This are open:
https://github.com/publiclab/plots2/issues/6736
https://github.com/publiclab/plots2/issues/6727

**Comment by DouglasLutz** [comment]
Hello, I'm looking for FTO issues

**Comment by cesswairimu** [comment]
Hi @DouglasLutz @priyajitm , nice to have you here...check the last two comments and see if the issues linked given are some are still available.

**Comment by priyajitm** [comment]
@cesswairimu I already worked on #6736 & #6727 is already assigned to someone.

**Comment by cesswairimu** [comment]
Sorry about that @priyajitm, you can have this https://github.com/publiclab/mapknitter/issues/1059

**Comment by nstjean** [comment]
@priyajitm I see you already have completed a pull request for #6736 . These first-timer-only issues are just for your first one. Now what you can do is look for other small bugs or issues labeled "help wanted". You can see some info here https://code.publiclab.org/ - Scroll down to "What's next?"

**Comment by priyajitm** [comment]
@nstjean @cesswairimu I don't need another FTO issue, I already completed one. I was only letting you know that of the two issues mentioned above, I have completed one and the other is already assigned to someone else.

**Comment by rajdeep2898** [comment]
@gauravano I am looking for a first-timer Issue.

**Comment by kushaggarwal** [comment]
Hi, I am looking for a first timer issue 
please help me find one  thanks

**Comment by puneeth2001** [comment]
Hi, I am looking for a first timer issue, can you please help me find one.

**Comment by harshithpabbati** [comment]
> Hi, I am looking for a first timer issue, can you please help me find one.

@puneeth2001 added your name to the above list. You will be shortly assigned with a first-timer issue. :)_

**Comment by SidharthBansal** [comment]
You can check if there is any unclaimed issue while we are trying to create
a fto issue. Thanks

**Comment by cesswairimu** [comment]
Hi @puneeth2001, have you found a fto yet? You can check this out if not https://github.com/publiclab/plots2/issues/6923. Welocme to PublicLab :balloon:

**Comment by MaheshPawar97** [comment]
Me too

**Comment by smarty1palak** [comment]
Hi, I am looking for a FTO to contribute. Please help!

**Comment by sharmamansi** [comment]
Hi, I am looking for some issues to contribute as i have already contributed in some FTO's

**Comment by cesswairimu** [comment]
Hi @smarty1palak, sorry I didn't see your comment sooner, hope u got an issue to work on...Hi @sharmamansi , I will ping you when I find a good first-timer-issue. Welcome to PublicLab both :)

**Comment by anthony-zhou** [comment]
Hello, I am also looking for a FTO to work on. Thanks!

**Comment by cesswairimu** [comment]
Here are a few ftos thanks to @crisner 
- https://github.com/publiclab/plots2/issues/6978
- https://github.com/publiclab/leaflet-environmental-layers/issues/304
- https://github.com/publiclab/leaflet-environmental-layers/issues/305
Thanks all and happy to have you here

**Comment by cesswairimu** [comment]
This issue is up for grabs https://github.com/publiclab/plots2/issues/5137.

**Comment by nstjean** [comment]
Here are two issues up for grabs:
https://github.com/publiclab/plots2/issues/7050
https://github.com/publiclab/plots2/issues/7051

**Comment by yihenghuang** [comment]
Hi, I am a newcomer. Can I join the list please? thank you!

**Comment by cesswairimu** [comment]
Great @yihenghuang , we will ping you once I find one

**Comment by crisner** [comment]
Here's an issue in the LEL repo: [#322](https://github.com/publiclab/leaflet-environmental-layers/issues/322). Please feel free to tag me for any clarifications.

**Comment by crisner** [comment]
Here's another FTO issue from the LEL repo. [#333](https://github.com/publiclab/leaflet-environmental-layers/issues/333)

**Comment by cesswairimu** [comment]
fto https://github.com/publiclab/mapknitter/issues/1066

**Comment by SidharthBansal** [comment]
There are many ftos which people left in the middle way. So, we need to
allocate those issues too

**Comment by cesswairimu** [comment]
Great idea :+1: ...I will check them close the prs and unassign them within the weekend. Thanks

**Comment by SidharthBansal** [comment]
I will really appreciate that
Thanks

**Comment by robin-natale** [comment]
Hi I would like to become an open contributor. looking for an FTO on #css #js #html #bootstrap  :)

**Comment by crisner** [comment]
@robin-natale Here's an FTO for you. https://github.com/publiclab/leaflet-environmental-layers/issues/369

**Comment by Medlineme4** [comment]
Please add my name to the list as a first timer.

**Comment by Kirti2502** [comment]
Hi I am Kirti Rohira, please add my name to the list.
I would like to work on issues related to Javascript, react and css.

**Comment by Shulammite-Aso** [comment]
hello, please, I'ld like to have a first-time-only issue assigned to me. 
Also i'm an outreachy applicant and looking to start contributing to publiclab.Editor repo. But i'm generally open to working on any public lab FTO issue at all.

**Comment by Alexjake660** [comment]
I am looking for an FTO please.

**Comment by cesswairimu** [comment]
Hi @Kirti2502 , @Shulammite-Aso and @Alexjake660 , Welcome and I will try to get you ftos ASAP. Thanks

**Comment by cesswairimu** [comment]
@Kirti2502  here you go https://github.com/publiclab/plots2/issues/6598

**Comment by cesswairimu** [comment]
@Alexjake660 here https://github.com/publiclab/plots2/issues/6727

**Comment by cesswairimu** [comment]
@Shulammite-Aso here https://github.com/publiclab/plots2/issues/6756

**Comment by Shulammite-Aso** [comment]
Thank you @cesswairimu 

Meanwhile, I remember you from oscafest😊

**Comment by cesswairimu** [comment]
wow cool, nice to meet you @Shulammite-Aso, oscafest was great :raised_hands:

**Comment by Shulammite-Aso** [comment]
> wow cool, nice to meet you @Shulammite-Aso, oscafest was great

Yeahh, thank you!

**Comment by cesswairimu** [comment]
Moving this to https://github.com/publiclab/plots2/issues/7683 since the thread is too long. Thanks everyone

**Comment by saitgulmez** [comment]
Hi, 
I'm looking for an FTO related #css #js #html #bootstrap.  If there is any openned issue related these skills, could you please assign me.
Thanks in advance.
