### ISSUE TITLE
Can't "like"/star a Research Note

### ISSUE THREAD

**Issue by klie1** [publiclab/plots2#621]
### What happened just before the problem occurred

I clicked the star to "like" a note, and there was no response.  I attempted this on two different browsers, and also after logging out and back in again.  I also attempted on Stevie's account and computer, and there was no response for her either.
![screen shot 2016-07-21 at 10 13 55 am](https://cloud.githubusercontent.com/assets/20325934/17028051/d9d75c58-4f2b-11e6-909b-b0cd90726072.png)

### Relevant URLs

https://publiclab.org/notes/ranon/07-18-2016/flight-report

### PublicLab.org username

klie

### Browser, version, and operating system

Google Chrome Version 51.0.2704.103 (64-bit)
Firefox 47.0.1
Mac OS El Capitan, Version 10.11.5

**Comment by jywarren** [comment]
@ananyo2012 - could this relate to the work you were doing on like incrementing? And would this be covered by the test you submitted? If not, let's track and write a test for this interaction too!

**Comment by jywarren** [comment]
Fixed! @ananyo2012 it was unrelated, see #623

**Comment by ananyo2012** [comment]
@jywarren Great work Jeff! Was getting a hard time figuring it out. Yes I will try to add some javascripts tests for it.
