### ISSUE TITLE
Investigate why duplicate topic boxes are appearing on some profile pages

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#6219]
### Please describe the problem 

Hello! I'd like to break out a small issue from https://github.com/publiclab/plots2/issues/6097 for @CleverFool77 to consider. 

I am noticing that some profile pages have the same topic boxes appearing more than once. 

I most frequently see this on new contributor profile pages (that are often in fact spammers but that shouldn't matter), such as this one, where multiple topics are repeated multiple times: 

https://publiclab.org/profile/kolkatanewsnstories

![repeating topic-boxes](https://user-images.githubusercontent.com/161439/63889699-80ddf380-c9af-11e9-8f28-0aee2a4aa646.gif)

> What did you expect to see that you didn't?

I expect to see each topic only once. 

### Please show us where to look

https://publiclab.org/profile/kolkatanewsnstories

### What's your PublicLab.org username?

liz

Thank you!

**Comment by jywarren** [comment]
@cleverfool77 mentioned that this code is being driven here:
https://github.com/publiclab/plots2/blob/d4d69ab4144d1457749ff215c53b63e167cc7142/app/views/tag/_profileCard.html.erb#L3

In theory, any use of `user.tags` shouldn't return duplicates. So we could
try to solve this upstream in user.rb under `def tags` -- adding a
`.distinct` or a `.uniq` to ensure distinct tag results:

Weird, it already has a `.uniq` here, at the bottom:

https://github.com/publiclab/plots2/blob/d4d69ab4144d1457749ff215c53b63e167cc7142/app/models/user.rb#L148-L159

Could it be that we need add another .distinct on line 148?

**Comment by jywarren** [comment]
I believe this is solved! See for example https://publiclab.org/profile/liz
