### ISSUE TITLE
can't edit research notes in chrome or firefox

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/plots2#622]
I edited an already published research note and then hit "publish" and nothing happened (chrome). Attempted again in firefox, same result.  "preview" doesn't work either.

This is the note:
https://publiclab.org/notes/mathew/07-21-2016/openflexure-microscope-high-resolution-assembly

### PublicLab.org username
mathew
(to help reproduce the issue)

### Browser, version, and operating system
Firefox 47 in OSX 10.11.5
Chrome 51.0.2704.103

**Comment by jywarren** [comment]
Fixed, thanks for reporting! See #623 for details.
