### ISSUE TITLE
Popular tags

### ISSUE THREAD

**Issue by Gagan6730** [publiclab/plots2#6222]
## When we click "more" to see more popular tags, the "more" button stays as it is. It should change to "less" and probably appear at the end of all the popular tags.

See: https://publiclab.org/tags#
<img width="598" alt="Screenshot 2019-08-30 at 1 46 45 AM" src="https://user-images.githubusercontent.com/23430169/63973263-09e84e00-cac8-11e9-8735-3a66a865d814.png">

**Comment by lokcito** [comment]
I've tried to review that in repository but that content is recorded in database and is shown by helper: 'feature'. Or how can we modify this, where is that content located in code of project?

![code](https://i.imgur.com/cdzX2MZ.png)

any idea to solve that?

**Comment by Gagan6730** [comment]
> I've tried to review that in repository but that content is recorded in database and is shown by helper: 'feature'. Or how can we modify this, where is that content located in code of project?
> 
> ![code](https://camo.githubusercontent.com/0008cbfd64a007258b06ffda4da912d28e33869c/68747470733a2f2f692e696d6775722e636f6d2f63647a58324d5a2e706e67)
> 
> any idea to solve that?

Can you state the file in which you found this? @lokcito 
Thanks

**Comment by jywarren** [comment]
This is mentioned in the doc/DATA_MODEL.md file, good find! It is based on
static HTML, so if you view the source of the page on the live site, you
can see it. I might recommend that we simply hide the "more" link instead
of change it, which could be less code. I think it might be like
`$(this).hide()` do to so?

If you want to submit new code for this, please send a GIF of it working
and include the code in a Gist, linked in a comment here. Then we would
love to update the live site with your code. Thank you!

**Comment by seabl** [comment]
@Gagan6730 see file `app/helpers/application_helper.rb`, starting line 47

**Comment by Gagan6730** [comment]
> This is mentioned in the doc/DATA_MODEL.md file, good find! It is based on static HTML, so if you view the source of the page on the live site, you can see it. I might recommend that we simply hide the "more" link instead of change it, which could be less code. I think it might be like `$(this).hide()` do to so? If you want to submit new code for this, please send a GIF of it working and include the code in a Gist, linked in a comment here. Then we would love to update the live site with your code. Thank you!
> […](#)

Hey @jywarren 
I am a bit confused. I read about features and know that they are static HTML and could be used as they are. So, can we edit any feature through the code base or it is just something admin could do through the site??
Thanks

**Comment by jywarren** [comment]
Indeed, admins do this through the site. I'm an admin, so if you share some
code that you know works, i can add it as a Feature on the live site!

**Comment by Gagan6730** [comment]
Hi @jywarren
I have attached a gif of working code below. Could you please have a look.
Link to gist: https://gist.github.com/Gagan6730/9727d5c3fc65c081ad5b7a681f82f241

![more_tags](https://user-images.githubusercontent.com/23430169/64407248-83bca080-d0a1-11e9-944a-a76fbeb747c4.gif)

**Comment by jywarren** [comment]
So sorry for the delay! This is perfect. I've updated https://publiclab.org/tags as well. Thanks a ton!
