### ISSUE TITLE
Reduce Travis runtime with caching

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6225]
Let's see if we can reproduce what Alax did here! 

https://github.com/publiclab/mapknitter/pull/794

**Before caching:**
![image](https://user-images.githubusercontent.com/19597045/60455123-05a8cd00-9c0c-11e9-9e9b-4263f541c078.png)

**After caching:**
![image](https://user-images.githubusercontent.com/19597045/60455136-0ccfdb00-9c0c-11e9-9e25-9a961970b783.png)

**Comment by jywarren** [comment]
😄 cc @alaxalves

**Comment by Manasa2850** [comment]
@jywarren I would like to try this!

**Comment by alaxalves** [comment]
Since we do not use Travis anymore, I'm closing this :)

**Comment by alaxalves** [comment]
CC https://github.com/publiclab/plots2/pull/8951#issuecomment-755919080
