### ISSUE TITLE
Browser notifications not working

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6226]
Hi @namangupta01 ! I'm trying to test this out but am seeing an error similar to https://github.com/publiclab/plots2/issues/5980 on production:

```
Error during WebSocket handshake: Unexpected response code: 404

  | ActionCable.Connection.Connection.open | @ | cable-d30277fdde31fe…c5729884ec69.js:241
-- | -- | -- | --
  | (anonymous) | @ | cable-d30277fdde31fe…c5729884ec69.js:205
  | ActionCable.Connection.Connection.reopen | @ | cable-d30277fdde31fe…c5729884ec69.js:275
  | (anonymous)

```

The line is:
```js
            this.webSocket = new ActionCable.WebSocket(this.consumer.url, protocols);
```

Can you see what's up here? Thank you!

**Comment by jywarren** [comment]
Could it be related to https://github.com/publiclab/plots2/pull/6158/ somehow?

**Comment by namangupta01** [comment]
Hi @jywarren, This is not related to #6158. I guess you are trying on production and it is related to https://github.com/publiclab/plots2/issues/6138. This is the Nginx configuration error. We already got this error when we were using `unstable` and `stable` while developing this feature. I guess correcting the Nginx conf should resolve this problem.
Thanks

**Comment by jywarren** [comment]
Ah ok! Thanks!
