### ISSUE TITLE
Mails from same research note should pile up in the inbox under same thread.

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#6230]
I observed that multiple comments/like messages from multiple people on the same research note are shown as different email thread in the inbox. They should be displayed in a single email thread.

**Comment by jywarren** [comment]
Good idea! cc @ebarry and noting that this is typically driven by the exact text of the title matching across emails.

**Comment by SidharthBansal** [comment]
Also the multi tag subscription is present on all emails.
These emails have same header and footer. A better way to have all the
emails one by one stacked in the single email thread without duplicate
header and footer.
We can omit them from second mail onwards. What do you think?

**Comment by jywarren** [comment]
This could be worked by making this email title:

https://github.com/publiclab/plots2/blob/7e2ebf018d021f6f31d5a9d99d242eb5048ba2ba/app/mailers/subscription_mailer.rb#L7

and this one:

https://github.com/publiclab/plots2/blob/7e2ebf018d021f6f31d5a9d99d242eb5048ba2ba/app/mailers/subscription_mailer.rb#L57

Match each other, and making this one: 

https://github.com/publiclab/plots2/blob/7e2ebf018d021f6f31d5a9d99d242eb5048ba2ba/app/mailers/comment_mailer.rb#L11

and this one:

https://github.com/publiclab/plots2/blob/7e2ebf018d021f6f31d5a9d99d242eb5048ba2ba/app/mailers/comment_mailer.rb#L18

also identical... that is, the email subjects should all be the same for this set of emails!

Good FTO, actually!

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by Jigyasa-Kumari** [comment]
Hi, I am Jigyasa and I am an Outreachy 2020 applicant. Is this issue open, and can I work on it?

**Comment by cesswairimu** [comment]
Yeah @Jigyasa-Kumari its open, feel free to get started on it. Thanks

**Comment by ebarry** [comment]
Yes this is a great idea!

**Comment by jcads** [comment]
As there haven't been any updates regarding this issue, I guess I can take this up.

**Comment by jcads** [comment]
Already fixed in https://github.com/publiclab/plots2/pull/6515.

**Comment by jywarren** [comment]
Ah, thank you @jcads for pointing that out!!!
