### ISSUE TITLE
Keyboard shortcut for posting comment not working

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#6231]
Ctrl + Enter should post comments on the research notes.
I think in past someone has made this feature. But this is not working now

**Comment by CleverFool77** [comment]
Hi @SidharthBansal I made this PR https://github.com/publiclab/plots2/pull/5473 four month ago to this bug. This was under review and was somehow left behind.

**Comment by SidharthBansal** [comment]
Duplicate of #5193 
Thanks Gagan for your work
Quick Suggestion : Grab approval of the mentors before sending prs
