### ISSUE TITLE
Redirect to same page after oauth login

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#6233]
I found this code is again broken.
Let's fix this first.

**Comment by SidharthBansal** [comment]
Base work for remaining cdms pr

**Comment by SidharthBansal** [comment]
Debugging https://github.com/publiclab/plots2/blob/master/app/controllers/user_sessions_controller.rb#L21
From some days.
Checking previous issues and prs

**Comment by ebarry** [comment]
This would be a wonderful bug to solve!!!!! thank you!

**Comment by SidharthBansal** [comment]
@jywarren I can't find from where "Signed In" flash notice is triggered.
https://github.com/publiclab/plots2/search?q=Signed+In%21&unscoped_q=Signed+In%21

**Comment by SidharthBansal** [comment]
Here is the error https://github.com/publiclab/plots2/blob/67231f9cb3e88d2b80730cd1f43d9cd19f77ca65/app/controllers/user_sessions_controller.rb#L63

**Comment by jywarren** [comment]
Aha! Do you have a suggested fix?

**Comment by SidharthBansal** [comment]
I am trying. I am not able to reproduce it on my local. So, I asked for
server logs. That might help.
It is present on prod.

**Comment by SidharthBansal** [comment]
Published on GCI dashboard

**Comment by jywarren** [comment]
Hi! I think this needs additional input from @steviepubliclab and @ebarry before being completed, thanks!

**Comment by jywarren** [comment]
Because we have a conflicting feature to direct to the dashboard if it's a first time signup. Or is this different?

**Comment by jywarren** [comment]
In any case I think this needs a bit more documentation before we really know as well. Thanks!

**Comment by SidharthBansal** [comment]
Sorry for the late reply. My inbox had 100+ emails. I expect it will increase when GCI begins :-)

This problem was solved 3 times in the past by Radhika, me and Isha. (maybe in last yr GCI too by Jonathan/Oorjit).
Some folks have added new features which conflict with this code. So, it got broken again.
Do you remember that Cross Domain System PR was working perfectly fine on unstable, and localhost? But there was some error in MK and SWB logins by OAUTH ONLY ON PROD? 

So an integration test is needed to ensure it will not break the next time. (I wrote test for OAuth in GSoC but we did not discuss the need of redirecting to the same page that time). So, we need to break this issue into 2 `hard` issues.

@jywarren ` a conflicting feature to direct to the dashboard ` can you please explain which feature so that I can understand what went wrong here.

**Comment by SidharthBansal** [comment]
See this pr https://github.com/publiclab/plots2/pull/5025/files
This is somehow causing OAuth to be redirected to the dashboard I guess.

**Comment by SidharthBansal** [comment]
@jywarren can  you please help me in recalling why we needed this line
https://github.com/publiclab/plots2/blob/master/app/controllers/user_sessions_controller.rb#L60

**Comment by jywarren** [comment]
Ah, i'm sorry - I think i was mixing things up. My apologies. 

I'm thinking about the discussion of whether on SIGNUP we want to leave people on the dashboard or on the page they came from, so that's unrelated to this issue on LOGIN. 

Signup-related issues have sometimes been opened to suggest that people end up back where they came from but my understanding is that they need to arrive on the dashboard to see the "welcome message". Related issues:

* https://github.com/publiclab/plots2/issues/3367
* https://github.com/publiclab/plots2/issues/5600 (not sure if this is signup or login)

But, possibly related to this issue: https://github.com/publiclab/plots2/issues/3246

Thanks!

**Comment by SidharthBansal** [comment]
>> Signup-related issues have sometimes been opened to suggest that people end up back where they came from but my understanding is that they need to arrive on the dashboard to see the "welcome message"

As requirements are conflicting, it is giving us some pain in thinking. But we can bet we can do it 🚀 
I remember, we discussed these things and came to the conclusion to give the dashboard on SIGN UP and redirect back to the same page for LOGIN. How does this sound now?

**Comment by jywarren** [comment]
I think this sounds great; let's get a final OK
from @publiclab/community-reps and then settle on this permanently!

**Comment by SidharthBansal** [comment]
Yes, we will solve cross domain things before 2020 :-)

**Comment by steviepubliclab** [comment]
Ok just to clarify, you're saying any new signup would direct people to the dashboard, but when someone is coming who already has a username and is just looking to log in, they could do so and remain on the same page? Is that what you're suggesting?

If so, I believe the pathway @ebarry was speaking about was in keeping people who are also creating a new login the ability to stay on the same page.

**Comment by jywarren** [comment]
Ah, one extra parameter, Stevie - in both cases we're talking about if they
click a Follow button - in the first case, even if they follow a topic,
they'd sign up and end up on the dashboard (but would be following the
topics). In the second, they'd log in and get sent to /subscriptions (i
think!).

Is that right, Sidharth?

**Comment by SidharthBansal** [comment]
Yeah!
Thanks

**Comment by steviepubliclab** [comment]
Ah ok, then maybe @ebarry you want to ping in here?  I thought you were interested in having people stay on a page once they follow?

**Comment by Uzay-G** [comment]
Hey @SidharthBansal @jywarren I would like to work on this issue. I have been fiddling around with my dev-tools to manually add the ```return_to``` value that is used in the code to redirect after login:

![redirect](https://user-images.githubusercontent.com/52892257/70532087-90480d80-1b56-11ea-8eaa-81119c39e77a.PNG)

Surprisingly, this worked. So I think the problem is that for some reason, the session return_to value is not being saved correctly. I will try to understand why it's not being saved and will then create a PR.

**Comment by Uzay-G** [comment]
I am trying to pinpoint the bug but the login process is complex

**Comment by SidharthBansal** [comment]
I think we have not decided yet what needs to be done. @jywarren what is
the final objective?

**Comment by Uzay-G** [comment]
Yeah because now I realized that when you log in it actually redirects to the previous page and says "You were successfully logged in."

**Comment by SidharthBansal** [comment]
Did you log in through Oauth OR login form?

**Comment by Uzay-G** [comment]
Oh no yeah you are right. Should I work on trying to make it redirect for the oauth or is that not the goal for this issue?

**Comment by SidharthBansal** [comment]
This issue is under discussion. So, I have asked Jeff, Liz and Ebarry.
Let's wait for their response
You can do other tasks while we decide on what to do.
Thanks

**Comment by SidharthBansal** [comment]
I really appreciate your search in this matter

**Comment by Uzay-G** [comment]
Thanks!

**Comment by Uzay-G** [comment]
Hey! I have found the solution to this problem because it was interfering with the testing for #7072. I am a GCI student but have not claimed the task yet because I am still working on #7072. Can I make a pull request to fix this so that I can do proper testing for my other pr?
Thanks! :+1:

**Comment by Uzay-G** [comment]
The changes I have in mind would, when logging in, redirect users to the page they were initially on.

**Comment by Uzay-G** [comment]
I understand that you want to redirect users to dashboard if it is there first time signing in and these changes will keep that functionality.

**Comment by Uzay-G** [comment]
I will make the pull request so we can discuss about the changes! :+1:

**Comment by SidharthBansal** [comment]
YOu can claim that issue as it is interrelated. We can reformat things. Don't worry

**Comment by SidharthBansal** [comment]
Hi @Uzay-G kindly claim the task on the dashboard. So that we can give you points.
