### ISSUE TITLE
"google" library not loaded; stopping other JS on all pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#624]
### What happened just before the problem occurred

Several JS-driven features stopped working after this; there are three issues to look into. 

1. First, does this code (https://github.com/publiclab/plots2/blob/abf4ba8017f94c5efea52ad7c13d35aa68434e0a/app/assets/javascripts/location_tags.js) need to be loaded on every page? 
2. Why isn't the 'google' library loading for many pages... or is it that we're requiring `location_tags.js` on all pages (incorrectly) but requiring the Google API on only those pages where it's required?
3. Can we create a Jasmine test which loads **all** included JS files and then performs some simple assertion at the end ( @ananyo2012 -- is this something you could look at? ) so that if there are any errors thrown during initialization of all JS code, we catch that on running tests?

See #621 and #622 for bugs resolved with the related fix in 06fb5f72ebc4835f5f90f3c6c0d395c50caf143b

**Comment by ananyo2012** [comment]
@jywarren Yes we need good client side tests for these. Will add some more javascript tests to test all javascript functions work correctly. Keeping a close look at this issue.

**Comment by jywarren** [comment]
Super. I like the idea of loading all libs in one test and then doing an
assertion at the end to confirm that there are no exceptions thrown. But I
don't recall if we can automatically include *all* javascripts referenced
from application.js... can we?

**Comment by ananyo2012** [comment]
Yes Jeff we can just include application.js and that will just include all other js libs included in it. It is same as the asset pipeline. Then we just have to make some simple assertions on it.

**Comment by lalithr95** [comment]
It worked for me locally, probably asset compilation in production lead to the issue. Thanks for the immediate fix. I included library for only pages which required (mostly location tag and people map). I will look into jasmine, test suite for JS action is a good idea. I made a PR for user follow feature in progress. #625

**Comment by ananyo2012** [comment]
@lalithr95 The jasmine tests were failing before the fix. Have to figure it out.

**Comment by jywarren** [comment]
We should look into triggering the Jasmine tests to run alongside `rake
test` -- there's an example here:
https://github.com/websocket-rails/websocket-rails/commit/b903ef14fceaa709ddc1c11073116d73ad088bfd#diff-52c976fc38ed2b4e3b1192f8a8e24cffR31

However, this would require phantomjs on the local machine. I think this is
reasonable, but it's a big extra dependency. What are your thoughts?

**Comment by ananyo2012** [comment]
Yes its a good idea to run both rails tests and jasmine tests with a single command. Well we can add some documentation in the readme for phantomjs installation. That would make it easier to follow.

**Comment by jywarren** [comment]
OK, and once #633 is merged, will any and all JS tests fail if there are any syntax errors in the JS code from `application.js`? I think that's what Ananyo is saying, no?

I'm having some trouble getting phantomjs to be recognized by my local Jasmine setup. Hang on and I'll try to figure it out.

**Comment by jywarren** [comment]
it was because the Phantomjs gem is not for all architectures, and is actually marked as alpha; I changed the default to not use the phantomjs gem, but your own phantomjs binary. 

Now I get this error -- can you try setting `spec/javascripts/support/jasmine.yml` line 52 to `use_phantom_gem: false` and running `rake spec:javsacript` to see if this is just my setup being odd (chromeos/crouton running Ubuntu on ARM)?

**Comment by jywarren** [comment]
````
(trusty)warren@localhost:~/sites/plots2$ rake spec:javascript
Running `"phantomjs" "" "/home/warren/.rvm/gems/ruby-2.1.2/gems/jasmine-rails-0.12.2/lib/jasmine_rails/../assets/javascripts/jasmine-runner.js" "file:///home/warren/sites/plots2/tmp/jasmine/runner.html?spec="`
Running: file:///home/warren/sites/plots2/tmp/jasmine/runner.html?spec=
Starting...
Faked response to: /likes/node/1/create
4

Finished
-----------------
3 specs, 0 failures in 0.181s.

ConsoleReporter finished
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Segmentation fault (core dumped)
````

**Comment by ananyo2012** [comment]
@jywarren Well I am not getting any error like the one you got. Its running perfectly.

**Comment by jywarren** [comment]
I actually think my computer just runs out of memory when running this, but will look into it. I think pending the last few changes in #633 this can be closed -- can you just confirm that all assertions will run *after* all js files are included, as we specify above in # 3?

**Comment by ananyo2012** [comment]
@jywarren Fixed the problem of google library not loading in #633 commit df89edc.

**Comment by ananyo2012** [comment]
The problem was here: https://github.com/publiclab/plots2/blob/master/app/views/users/info.html.erb#L1. This should be included in the `application.html.erb` file before the `location_tag.js` loads. I also removed the `location_tag.js` from the application.js file and included it in the `info.html.erb` file in the user views since I don't think we need to load it in every page.

**Comment by ananyo2012** [comment]
@jywarren What I found out that if any any of the js files included in the application.js fails to load all the tests include in jasmine spec file fails. This is because of asset compilation which includes everything in application.js and treats it as a single file.So basically we don't need to include any initialization tests for those files included in application.js

**Comment by ananyo2012** [comment]
For those js files not included in the application.js simply including them using `require` in the spec file would be enough. If all files load properly all tests should pass otherwise all tests would fail.

**Comment by lalithr95** [comment]
@ananyo2012 Thanks for fix, I'll figure out why location_tag file is causing issue. @jywarren I suspect https://github.com/publiclab/plots2/blob/master/app/views/users/info.html.erb#L1 token in URL is causing the issue. Also it one of my token, can you replace it and set ENV variable under PublicLab token ?

Thanks !

**Comment by jywarren** [comment]
Hi, Lalith - there's a way to create a "config.yml" file to be included, as
here:
https://github.com/publiclab/mapknitter/blob/master/config/config.yml.example

However, that adds an additional requirement to the install process. Is
there no other way around it, or is there a way to fall back to a service
that doesn't require an API key? Will anything fail for new contributors
who have just installed the codebase but have not created an API key?

Perhaps we could add a conditional for the API key before including/using
the location service, then the `/config.yml` addition would be optional for
most users. We would want to document this in the README in any case.

**Comment by jywarren** [comment]
For reference, the config can be accessed using:

APP_CONFIG = YAML.load_file("#{Rails.root}/config/config.yml")[Rails.env]

then, in code, using:

APP_CONFIG["google_maps_api_key"]

**Comment by jywarren** [comment]
I also want to think about how to get the Google API include only on the pages where it's required. Mentioned this here: https://github.com/publiclab/plots2/pull/633#discussion-diff-72827695 with an approach with a `yield` call in the header. Circle back when David Days and Ujitha's code is merged.

**Comment by jywarren** [comment]
Closing this now, as I believe it's complete.
