### ISSUE TITLE
Feature request: add pagination to /spam/revisions

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#6244]
**Desired behavior.**

The Moderators group convened last week to review the features available for moderators reviewing spam.
Based on that conversation, @bronwen9 and I have the following feature request:

- [ ] Add pagination to https://publiclab.org/spam/revisions 
- [ ] Doublecheck why the years are displayed as 47, 48, and 49 years ago.

<img width="1203" alt="Screen Shot 2019-09-05 at 9 45 09 AM" src="https://user-images.githubusercontent.com/161439/64347422-e5a5d900-cfc1-11e9-87cd-22b86e7f3568.png">

**Additional context (optional)**

This page is not often used, but did enable us to catch a very bad spam image on our main page: publiclab.org/chat. For this reason we believe this page is worth attention to make it more functional. Thank you! Any questions?

**Comment by seabl** [comment]
The "49 years ago" thing could mean those spammers were active very long ago... at the very beginning of UNIX time.

**Comment by jywarren** [comment]
The new /spam2 dashboard at #7969 #7961 will resolve this! Thanks!

**Comment by ebarry** [comment]
Great, thanks!
