### ISSUE TITLE
Discussion: observation about how #s of people are referred to on tag pages

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#6247]
I'd appreciate a conversation in this issue, hopefully resulting in a few simple, good ideas that could be implemented. But for now this is merely a discussion. 

**URL**
https://publiclab.org/tag/balloon-mapping

**Context**

1. When i look at the current tags page, i find it confusing that the number of people subscribed are listed in the side right as number of people "discussing." This is far away from the "Subscribe" button on the left side, and my confusion is compounded because I do not directly associate the words "subscribe" and "discuss", which makes it unclear what the number of people discussing is referring to. Does anyone else feel this way? I have drawn an arrow proposing to move the number of "people discussing" into the box with the Subscribe button. 

2. The number of contributors is hidden in the drop-down menu "By Type". I have a feeling like the people on this site could be featured in a different way from the documentation that they create. I am wondering if there's a way to move the Contributor link out of the "By Type" menu. It would be nice to see the # of contributors and # of subscribers related in the layout in some way. 

3. Seen together, the three blue buttons pose too many calls to action. I feel the subscribe button should be given the most prominence. The lower two blue buttons for asking or answering questions are so long that they fight for visual prominence.  Here's one idea: only show the `Ask a question on foo` or `subscribe to answer questions on foo` when the content type "Questions" is selected from the dropdown, meaning on this type of page: https://publiclab.org/questions/tag/balloon-mapping

4. This is so minor because there are so few admins, but could the button and text `"Add Tag Parent" (Admin Only)` be moved into the right sidebar underneath "Related Tags"?

![tag-page-annotation](https://user-images.githubusercontent.com/161439/64365895-14807700-cfe3-11e9-8a00-a61e084b7022.png)

I'd love to hear your thoughts!

**Comment by jywarren** [comment]
Hi Liz, thanks for posting. Quick thoughts:

for 3, they are already removed in https://stable.publiclab.org/tag/balloon-mapping, so no worries. Likewise for 4, all extra stuff is being moved under the `...` menu in the tag card upper right corner, and that'll include the `tag parent` button. 

For 1 and 2, this goes back to the [DIAL UI project designs](https://publiclab.org/notes/warren/04-22-2019/user-interface-projects-update-and-dial-osc-project-recap) and the [Style Guide](https://publiclab.org/notes/warren/05-07-2019/introducing-a-draft-style-guide-for-public-lab), and also gets at the shift towards "forums" as a mental model. Subscribing is how you become part of the forum, so the "forum members" and "joining the forum" became our top priorities. The discussion we had at the time was to address the discrepancy by doing our utmost to convert contributors into subscriber/members -- a project we've recently revived so I hope that'll address a lot of the ambiguity here. 

Another thing is we have this PR open that needs wrap-up, that displays /both/ "follower/subscriber/members" and contributors on the same page: https://github.com/publiclab/plots2/pull/5632 -- both "Contributors" and "X people discussing" link there. 

Two thoughts to carry this forward, apart from that tag-subscribers-outreach project:

1. The nomenclature of a "forum member" is a little unclear. We'd talked about the word "discussing" as emphasizing discourse. Is there a brainstorm we could do to develop a better one? follower, subscriber, member...
2. Some contributors won't want to become `follower/subscriber/members`, no matter what, and that's reasonable. Is "contributor" a good word for them, and how might they be listed without causing confusion WRT the `follower/subscriber/member` role? Could they be termed "former followers" or something? That's not quite right. Or could we show `follower/subscriber/members`, and below that, have text like: `X people have contributed to this topic but are not follower/subscriber/members` ? 

Definitely open to ideas here. Contributors plays an attribution/credit role in addition to a "part of a group" role, so there is definitely a reason to continue tracking it. But to me it seems secondary to the list of people actively engaged in the topic -- i.e. "who will hear you if you post there". Love to hear other thoughts on this though. Thanks for posting!

**Comment by ebarry** [comment]
ok this is great information, thanks for updating me. 

I read in your comment that both "Contributors" and "X people discussing" will link to the same page, perhaps https://publiclab.org/contributors/balloon-mapping ? That is great. So we will be figuring out how to display these two types of counts of people (contributors and followers/discussants) on the main /tag page, and on the /contributors/tag page. 

For me, I want to maintain our highlighting of contributors by displaying a total count of contributors _and_ offering some kind of display with link to their profiles (currently a list, but it could look more like Community Toolbox, eventually, if that's of interest?), in addition to listing the number of "followers, subscribers, members" by tag.

**Comment by jywarren** [comment]
The issue I linked to by Isha is work towards showing two tables side by
side, one for subscribers and one for contributors. But what I'm wondering
is, could we show subscribers as the "main" display, but below it, list
essentially "contributors who aren't subscribed" -- that would also reduce
the # of ppl shown twice? It may also help facilitators to see who to
encourage to subscribe.

**Comment by ebarry** [comment]
Here's an idea -- display these terms and numbers for the different ways that people are engaged in a regular sentence so that the terms have context, for example:

"This Topic has X contributors, and X people following along"

This sentence could appear in the card, and the "Subscribe" button could appear directly after the sentence.

**Comment by jywarren** [comment]
We've tried to keep the cards to an absolute minimum of text/info, so as to make them very readable. That's not to say we can't fit this, but it's a classic "limited real estate" problem, so I want to be careful. 

Would a more compact `12 contributing | 8 following` work? It could include a `(?)` icon linking to to an explanation of what that means. Alternatively `12 contributors | 8 followers (?)`

![image](https://user-images.githubusercontent.com/24359/64555392-3a6f8980-d30b-11e9-9231-86a83cae4c12.png) ![image](https://user-images.githubusercontent.com/24359/64555456-5b37df00-d30b-11e9-865e-f2ae5ec86660.png)

Or do you think it's worth including the full sentence on every card? I'm especially thinking of the limited space on mobile devices but any way we can keep the cards minimal helps the overall design stay focused and non-overwhelming. What do you think?

For reference, here's the intended design on a mobile device:

![image](https://user-images.githubusercontent.com/24359/64555623-b79afe80-d30b-11e9-9492-332ea8e1c57b.png)

**Comment by ebarry** [comment]
i prefer the verbs of contributing, following, etc, but it seems like other experiences around the web, especially social media (twitter, instagram) are making us expect "identities" like contributors and followers. 

If there's no room for a sentence, there's just no room. It's OK. However, then we are still left with the problem we've made for ourselves, which is that upon first read, there's no inherent meaning of what a `contributor` is or what a `follower` is, and how the big blue "Subscribe" button relates to being either of those words. I think we need to give some context. A sentence gives context, but perhaps 

Related to context, elsewhere around the web (aka social media accounts or forums) it's also common to see a number indicating volume of content generated in a forum thread (which is what tags are for us now) or by a social media account. On an instagram account you see how many posts an account has made, or on a twitter account you see "how many tweets and how many likes" an account has. In our case this would be a total # of posts, comments, wiki pages that that tag is applied to. I think this is important for adding a sense of scale, as in -- _how big is this topic?_.

**Comment by jywarren** [comment]
Ah, note that in the updated mockup SUBSCRIBE was changed to FOLLOW.

Also, noting that the topics page tag card design (that'll also be on the
new dashboard and profile page) has a link for "124 people discussing" so
this could also follow a concise pattern we establish here.

I think if you don't feel the (?) help link is enough, we could have a
popup or other help text that displays only for new users, explaining it a
bit. Would you like to explore that idea a bit more?

**Comment by jywarren** [comment]
Just summarizing where we are:

1. we'll show `X contributors | Y followers (?)` in the card, and adopt that vocab across the site

And questions left:

1. now that both contributors and followers are represented on /contributors/____ (by @IshaGupta18 in #5089) we should circle back to how those lists are shown, from [the above comment](https://github.com/publiclab/plots2/issues/6247#issuecomment-529512061). To avoid overlap, we could show Contributors, then Followers, but if Followers have already appeared in the Contributors list, they might not appear twice (our choice). Maybe Contributors then need an icon to show if they are following. Or should we just have 2 lists, one above the other, with redundancies?
2. The "amount of activity" next to the above would be a bit of a long datapoint, like:

`X contributors | Y followers | Z posts (?)` -- and then what, would we show questions, wiki edits? 

![image](https://user-images.githubusercontent.com/24359/64982363-073d7500-d88c-11e9-844b-99bdaedf64e6.png)

What if we compacted the view options above the posts (`By Views` / `By Likes` and the right-side `By Type`) to make room, and put this triple stat on the left in that space? That's a bit less crowded, but still pretty high visibility. 

Could be like (but with icons):

![image](https://user-images.githubusercontent.com/24359/64982861-2be61c80-d88d-11e9-9d40-9ea46d2d23d7.png)

**Comment by ebarry** [comment]
The mockup for your second point looks great @jywarren ! let's do the `# posts by # contributors | # followers`

For your first question, i like you suggestion that "Contributors then need an icon to show if they are  also following", and then have a separate list for those who are only following. 

Thanks!!!!! 💃

**Comment by jywarren** [comment]
Broke up the take-aways from this and opened:

* https://github.com/publiclab/plots2/issues/6304
* https://github.com/publiclab/plots2/issues/6305
* https://github.com/publiclab/plots2/issues/6306

Thank you! Closing here and opening a new issue to get into navigation discussion.

**Comment by jywarren** [comment]
And picking up discussion of navigation on the individual tag page here: https://github.com/publiclab/plots2/issues/6307
