### ISSUE TITLE
Link type text coming out of the card in dashboard

### ISSUE THREAD

**Issue by IshaGupta18** [publiclab/plots2#6248]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Here's a CSS type bug in a card in the dashboard
![image](https://user-images.githubusercontent.com/40794215/64380510-bee1b400-d04e-11e9-9bf5-ab446ef3643a.png)

Please try to wrap text like this to multiple lines, to fix the design flaw.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by kapil-raj** [comment]
Hey, I want to claim this issue. :)

**Comment by IshaGupta18** [comment]
Go right ahead, let me know if you need any help! Thank you!

**Comment by kapil-raj** [comment]
I can't seem to find the $REPO repository, after clicking on the $FILENAME, it takes me directly to the issues. But i am not finding the code file that I have to edit

**Comment by IshaGupta18** [comment]
Yes because I haven't mentioned the filename here, would you like to
explore it on your own a little, that might give you a better idea of the
codebase?

**Comment by CleverFool77** [comment]
Hi @IshaGupta18 As it is `first timer only` issue. It would be great if you could mention the file.

**Comment by IshaGupta18** [comment]
Yes, I wanted to but I just posted this issue as soon as I saw it. Let's
make this simpler. Do you happen to know which file do the cards in the
dashboard belong to? I think you'll be able to correctly point to the right
file! Thank you!

**Comment by kapil-raj** [comment]
I don't know if I am getting this right. The link should be inside the card, right?

**Comment by IshaGupta18** [comment]
Yes

**Comment by kapil-raj** [comment]
so shouldn't be this a html problem rather than css cause if we place the content inside the "card" then the css will also applied to the link text

**Comment by vajjalavikram** [comment]
i want to claim this issue

**Comment by IshaGupta18** [comment]
I think Kapil is already working on it. Could you look for another FTO?
Thanks a lot and let me know if you have any questions.

**Comment by vajjalavikram** [comment]
okay
Thanks!

**Comment by kapil-raj** [comment]
Dude go ahead

**Comment by darksun27** [comment]
![Screenshot from 2019-09-11 01-13-44](https://user-images.githubusercontent.com/31998550/64645219-ffb44100-d431-11e9-9f36-74124b9ba080.png)
This is what I get when login into the app. Is it a database seeding error? or any other issue which i didn't understand at the moment?

**Comment by darksun27** [comment]
If anyone has not claimed this issue, can I claim it? I think i have found the solution.

**Comment by IshaGupta18** [comment]
I think you can go ahead and solve it!

**Comment by bermylle** [comment]
Hello is this claimed? Or solved? Sorry i am a newbie hehe

**Comment by IshaGupta18** [comment]
Hey, I think you can give it a try!
