### ISSUE TITLE
Add a wiki edits link to /wikis/author/_authorname_ from profile pages, and create that new page

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#6253]
I've noticed that only some of the gray links on profile pages link out. I was wondering if we could get them all link? I'm not able to see ~comments or~ wiki edits anymore. Maybe this is a bug? Also not sure if it's reported elsewhere, if so please feel free to delete 
<img width="293" alt="Screen Shot 2019-09-06 at 9 24 13 AM" src="https://user-images.githubusercontent.com/7490478/64431411-5f07ff00-d088-11e9-8281-6edfd69ae73e.png">

**Comment by jywarren** [comment]
Hi Stevie, thanks, there is some ongoing work on that, and also want to connect to https://github.com/publiclab/plots2/issues/6001. 

Right now, the first task is to convert those that /are/ links into underlined links so it's clear they can be clicked. 

Second, we have a goal of two new routes, `/wiki/author/stevie` and `/comments/author/stevie` (or `/comments/stevie` i guess?) 

Actually now I look, we do have that for wikis, but only under a topic:

https://publiclab.org/wiki/tag/water-quality/author/mimiss

Just like https://publiclab.org/tag/water-quality/author/mimiss

It does not exist for comments. 

So, the next tasks would be to develop the new `/wiki/author/_____` and `/comments/author/____` routes, which can use the same templates as `/wiki` and `/comments`, for simplicity. 

If you're interested in a different UI for that section, I think it's worth discussing. I like how it's an at-a glance, human-readable description of the person's posts. But if it would be better as a series of icons or something, that's something we can try to figure out.

**Comment by jywarren** [comment]
@CleverFool77 @gautamig54 I was just wondering if we have another issue for this, as I think it was mentioned before, both in regards to the profile page and to the dashboard, actually!

**Comment by jywarren** [comment]
From #6220, `/notes/authorname` would also be great to be able to link to!

**Comment by CleverFool77** [comment]
Hi @jywarren @steviepubliclab !!
Regarding the grey out links, These were Turning blue and had underline on hover. But as we usually don't hover on it , it seems like grey text to us. I have opened a new PR https://github.com/publiclab/plots2/pull/6255 and converted them to permanent blue with underline. So it shows that they are `<a>` tags links.

**Comment by CleverFool77** [comment]
And Regarding wikis and comments, We don't have routes for them yet.
Should we create something like `comments/authorname` or `wikis/edited or author/authorname`.

**Comment by steviepubliclab** [comment]
Great! Thanks all, for some reason I thought under the prior profile page version I was able to see comments. maybe I'm mistaken!

**Comment by ebarry** [comment]
I also thought that the old profile page offered a # of comments, but maybe not a link to be able to see them?

**Comment by jywarren** [comment]
I think maybe it did offer that, but not at a distinct url, just as a sub
tab. So we will need to break it out into its own page. But shouldn't be
hard! And, we should look to see if the old template files can be reused.

**Comment by steviepubliclab** [comment]
Hi! another one related to this. I noticed when you click 'research notes" on profile pages, it also shows questions people have asked. On the old profile page format these were separated. Can we separate them again?

**Comment by jywarren** [comment]
Regarding @CleverFool77's question, I think we should go with `/wikis/authorname` to list wikis edited by a person. 

And for @steviepubliclab's last comment, we should break that out as its own issue.

**Comment by jywarren** [comment]
The comments link and page are complete, though!

**Comment by SidharthBansal** [comment]
@Uzay-G published on GCI dashboard. Kindly receive points

**Comment by Uzay-G** [comment]
Thanks! I will when this [task](https://github.com/publiclab/plots2/pull/7202) gets approved :+1:

**Comment by SidharthBansal** [comment]
Shouldn't it be https://github.com/publiclab/plots2/pull/7169?

**Comment by SidharthBansal** [comment]
I have awarded points to @uzay for this task after publishing corresponding task to GCI dashboard

**Comment by SidharthBansal** [comment]
@Uzay-G ?

**Comment by Uzay-G** [comment]
Yeah thank you my task was approved :+1:
