### ISSUE TITLE
Weekly Community Check In 34: Welcoming the youth!

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#6270]
Hi everyone 👋 !

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️ .

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. 💯

# Welcoming the Youth - Google Code In Planning 

Google Code-in is a contest to introduce pre-university students (ages 13-17) to open source software development. Since 2010, 8,108 students from 107 countries have completed over 40,100 open source tasks!

Because Google Code-in is often the first experience many students have with open source, the contest is designed to make it easy for students to jump right in.

Refer https://codein.withgoogle.com/archive/ for more details on the program

Call for Mentors : https://github.com/publiclab/plots2/issues/6238

Google Code In Tasklist : https://github.com/publiclab/plots2/issues/6239

Challenge for GSoC and Outreachy Students -> Teach the young generation to code like a pro.
💯 🎉 
Let's see how well our SoC students can manage the immense crowd which we will have from October onwards.  Last year I accepted this challenge. Let's see who will accept this challenge this year?

Mentor guidelines https://developers.google.com/open-source/gci/help/oa-tips#mentors

Other than SoC students, we invite everyone to apply for GCI mentorship. Anyone can help us with molding the young generation into the right orientation.

**Comment by SidharthBansal** [comment]
@gauravano
@milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @shubhscoder @sidntrivedi012 @SidharthBansal @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77 @ananyaarun @ananya @publiclab-mimi @ananya @hc-barker @starkblaze01 @asquare @pdurbin @HarshKhandeparkar
@newbazz @aSquare14 @vaarigupta @alonpeer @aashna27 @harshithpabbati @jesus-montano @cryptoclidus @mohamed-elalem @konolga @gowtham5699

**Comment by SidharthBansal** [comment]
@ananyaarun @ananya @publiclab-mimi @ananya @hc-barker @starkblaze01 @asquare @pdurbin @HarshKhandeparkar
@newbazz @aSquare14 @vaarigupta @alonpeer @aashna27 @harshithpabbati @jesus-montano @cryptoclidus @mohamed-elalem @konolga @gowtham5699
@jywarren @ebarry @steviepubliclab

**Comment by ebarry** [comment]
hi all! last week and this week i've appreciated having time to really explore the new contributions that this summer's work has created on publiclab.org! Everything is looking great.

**Comment by SidharthBansal** [comment]
Loved to see Outreach winter!

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/webjack/issues/119. Thanks all :heart:
