### ISSUE TITLE
Chose a scoring system for gci students

### ISSUE THREAD

**Issue by newbazz** [publiclab/plots2#6278]
Discuss it with other mentors and have a proper method for scoring the gci participants.

**Comment by SidharthBansal** [comment]
Please add a comment in call for mentors that "scoring system is discussed
in #6278".
Thanks for opening it on my suggestion!

**Comment by debck** [comment]
I was thinking of labeling issues as easy-work, medium, or hard and then adding specific points to each task. And then the contributor can be easily evaluated according to the score plus his involvement with the community and other measures.

**Comment by IshaGupta18** [comment]
I think we should have a little more detailed description on the points
system, and discuss it thoroughly, as it will be fixed once decided and we
won't be able to change it once GCI begins.

**Comment by newbazz** [comment]
Okay yes it makes sense to have some sort of labels for the issues. Let us first begin by mentioning all the types of issues that can be there for a gci student like `typo`, `css fixing` etc and rate them accordingly. Firstly make buckets so as to fit all of the issues and keep a scoring system for the individual bucket.

**Comment by SidharthBansal** [comment]
+1 for labels like hard medium and easy.

**Comment by IshaGupta18** [comment]
Yes, but they won't be enough

**Comment by newbazz** [comment]
@IshaGupta18 yes we know that they wont be enough, that is why we have proposed an idea to list down all the types of issues that a gci can get to solve, and according to the same, we can make further categories. 
Someone can volunteer and make a google doc, share the editable link here so that one can add/edit to the list.

**Comment by newbazz** [comment]
@aSquare14 @aashna27 @vaarrigupta @alonpeer @konolga @jesus-montano @CoderJolly @ananyaarun @sashadev-sky @Divy123 @oorjitchowdhary

**Comment by sashadev-sky** [comment]
As far as labels go, google code-in gives some [guidelines](https://developers.google.com/open-source/gci/faq#tasks):
- we should categorize tasks in one of the 5 category labels so people can filter
- it says students are able to do 2 "beginner" tasks max - so I was just thinking `beginner`, `medium`, `hard` is sufficient.

I designed a scoring / label system in this doc that (I think?) fits the model of GCI: https://docs.google.com/document/d/1KW6zIHtrJEl9329Yep5JhTA5CPmA8XV64CMx5Pz_7KU/edit#

From here we can tailor it to fit if it doesn't? @newbazz @jywarren

**Comment by IshaGupta18** [comment]
Hey, can I get the access to the document as well, I would like to view the
scoring scheme and suggest changes if there are any!

**Comment by debck** [comment]
I would also like to have the access. I can suggest something if any. 
debck7019@gmail.com

**Comment by sashadev-sky** [comment]
sorry forgot it was private! I guess its best to leave it private.. I shared with @debck @oorjitchowdhary @jywarren and a few other emails I have already. I will need the rest of your emails to share! Just click on share button on the link to request access @IshaGupta18

**Comment by sashadev-sky** [comment]
Also people I have added have the rights to add anyone else so go ahead if you guys know eachotheres email

**Comment by sashadev-sky** [comment]
Ok the following people still need to be added @newbazz @IshaGupta18 @aashna27 @jesus-montano @CoderJolly @Divy123 @ViditChitkara @CleverFool77

**Comment by newbazz** [comment]
@sashadev-sky really appreciate your efforts. I think the doc seems okay. One more suggestion from my side is, I have noticed that the code whether ruby or js, doesn't confine to the coding standards of the specified language, that is what needs to be added as a beginners issue as well.

**Comment by sashadev-sky** [comment]
@newbazz yes I have always thought that really really neeeds to be fixed add it on

**Comment by sashadev-sky** [comment]
@newbazz I think it can be medium as well. The user should document the standards first, then fix them.

**Comment by sashadev-sky** [comment]
rememeber beginner issues are limited to 2. anyone have any idea how many that means we should make?

**Comment by newbazz** [comment]
The standards are already fixed for programming languages which we use like ruby and javascript. We also have linters, we can add the lint tests in continuous integration as well.

**Comment by newbazz** [comment]
> rememeber beginner issues are limited to 2. anyone have any idea how many that means we should make?

It depends on the students PL gets this year :P

**Comment by pydevsg** [comment]
Can you please share me access to the document @sashadev-sky , so that I too can share my valuable response for the scoring system as well.

**Comment by pydevsg** [comment]
As many of you have already shared the opinions, I think the scoring system could be as follows.
Easy(typo errors, small bug fixes) - 10 points , deadline 2 day within the time interval he or she is assigned the task.
Medium( a minor feature with a small bit lines of code ) - 20 points , deadline 3 days within the time interval he or she is assigned the task.
Hard( a major feature ) - 30 points , deadline 5 days within the time interval he or she is assigned the task.

**Comment by CoderJolly** [comment]
> Ok the following people still need to be added @newbazz @IshaGupta18 @aashna27 @jesus-montano @CoderJolly @Divy123 @ViditChitkara @CleverFool77

Sure @sashadev-sky , pls add me

**Comment by SidharthBansal** [comment]
@Sasha Boginsky <sboginsky17@gmail.com> It will be great if you can give
comment access to all the viewers.
I think we should make hard as 40 points as it takes a lot of time and
effort. Great work Sasha

**Comment by sashadev-sky** [comment]
sorry for the delay! just added you guys to all the docs @pydevsg @CoderJolly 
@SidharthBansal I think we were trying to avoid having it public, but pretty sure anyone can invite anyone else to it. 40 points seems a little unfair, also assuming you are referring to an `impossible` issue I wouldn't go higher than 15pt (hard x 3). I bumped it up to that in the doc!

**Comment by pydevsg** [comment]
Thanks for adding me to the docs.
I think we should atleast provide 10 points for the `hard` issues .
Apart from that I think the naming convention should be changed from `impossible` to other tag.If a GCI student solves some `easy` issues and then check there are some `impossible` issues then surely he would be afraid and would take away himself/herself from trying it. 
Correct me if I am wrong somewhere @sashadev-sky .

**Comment by pydevsg** [comment]
The `impossible` issues can be renamed to `technical_features` issues or some relevant but not `impossible` . Would like to have opinions on this from others as well. @SidharthBansal , @CoderJolly , @newbazz @IshaGupta18

**Comment by SidharthBansal** [comment]
Hi Sudipto. Thanks for your concern about the nobody willing to take the
impossible tasks.
They were proposed to be named as impossible as the existing community
couldn't solve it. They are not necessarily features. So technical features
will be inadequate label.

Regarding points, I think there should be fair difference bw points.
Impossible specially should have 2x hard score as nobody will be able to
provide support on them.

**Comment by newbazz** [comment]
Yes, I also dont think that renaming the issues will help. Renaming will not change the nature of the issue, but yes i think we can partially give them points for the `impossible` issues.

**Comment by CoderJolly** [comment]
> sorry for the delay! just added you guys to all the docs @pydevsg @CoderJolly
> @SidharthBansal I think we were trying to avoid having it public, but pretty sure anyone can invite anyone else to it. 40 points seems a little unfair, also assuming you are referring to an `impossible` issue I wouldn't go higher than 15pt (hard x 3). I bumped it up to that in the doc!

Thanks for the access @sashadev-sky. 😄 👍 🎉

**Comment by ebarry** [comment]
Have we chosen a scoring system for gci students? If so, perhaps should we close this issue?

**Comment by newbazz** [comment]
@ebarry we are there with a scoring system, i think we can close this issue. What say @SidharthBansal

**Comment by StlMaris123** [comment]
@sashadev-sky , would time taken to complete a ticket also be taken into account?

**Comment by SidharthBansal** [comment]
In short,

Scoring System


   -

   Beginner Level Task(1pt): Installation Tasks, FTOs, Typographical
   errors, HTML/CSS etc.
   -

   Medium Level Tasks(2pt): Simple challenging tasks like methods, tests,
   designs, demos, documentation(if small) etc.
   -

   Hard Tasks(5pt): New feature, research, Documentation(long or difficult
   for high school students to understand and write), etc.
   -

   Supportive Tasks(1pt): Bug reporting(1pt/tasks), creating fto(1pt/task),
   screenshots(1pt/task), suggest new changes(if change is accepted-1pt/task),
   adding code linking(1pt/task) and other tasks of helping like pr reviews,
   participating in weekly checkins (1pt/week, however if mentor finds that
   mentee is too helpful than mentor can award 2 points at max).
   -

   Impossible Tasks(15pt): Wontfix issues. Jeff will ONLY make/publish
   these tasks.

Please refer: https://github.com/publiclab/plots2/wiki/Supportive-Tasks
Thanks

**Comment by SidharthBansal** [comment]
I just consolidated the GDoC made by Sasha. Thanks Sasha!
