### ISSUE TITLE
For moderator accounts, add ability to turn off email at /settings

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#6282]
**Please describe the desired behavior.**

This feature request is part of improving the moderators workflow, and was written with @jywarren and @bronwen9. 

This feature request is to add the ability to turn of moderator emails per user at /settings. 

This feature should only be shown to /moderators and /admins. 

**Additional context (optional)**
<img width="646" alt="Screen Shot 2019-09-12 at 4 58 58 PM" src="https://user-images.githubusercontent.com/161439/64820574-b02f5b80-d57e-11e9-8cd1-d7019061c113.png">

Thanks!

**Comment by ebarry** [comment]
Here is a tiny additional goal: update the email address listed in the upper right left sidebar to be `moderators@publiclab.org` instead of `organizers@publiclab.org` on /spam

On **https://publiclab.org/spam**

<img width="333" alt="Screen Shot 2019-09-16 at 10 08 36 AM" src="https://user-images.githubusercontent.com/161439/64965074-5377bd80-d86a-11e9-92b6-eddec534c231.png">

**Comment by jywarren** [comment]
Copying in line numbers and info from previous issue at #4543 !

Also noting link to VERY similar/related issue at https://github.com/publiclab/plots2/issues/6867, especially with regard to UI changes that'd need to happen. 

****

* [ ] Let's add a toggle to https://publiclab.org/settings that:
* [ ] when sending moderator emails, causes the site to check `user.has_tag('block-node-moderation-emails')` before adding that moderator to the list.

The moderators to be notified are collected up in these sections here: 

https://github.com/publiclab/plots2/blob/3267de0b4872c07d2aaa6ab523d33e45e062cb33/app/mailers/admin_mailer.rb#L8-L19

We could add lines like:

```ruby
all_moderators = User.where(role: %w(moderator admin)).collect(&:email)
moderators = []
all_moderators.each do |mod_user|
  moderators << mod_user unless .has_tag('no-moderation-emails')
end
```

This would be a great FTO!

Follow-ups would be:

1. write a test for this by adding such a user tag to a testing user account
2. develop a UI for this at the /settings page, as in #6867

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by anthony-zhou** [comment]
I'd be happy to work on this as part of GCI. I will open a PR addressing this soon.

**Comment by jywarren** [comment]
That would be super!!!!

**Comment by SidharthBansal** [comment]
Published on GCI

**Comment by jywarren** [comment]
Completed by @anthony-zhou ! Thank you!!!
