### ISSUE TITLE
Mysql2::Error::ConnectionError on Travis

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6293]
Travis is showing this error on all PRs now; https://github.com/publiclab/plots2/pull/6283, https://github.com/publiclab/plots2/pull/6289, and https://github.com/publiclab/plots2/pull/6291 are all affected.

`Mysql2::Error::ConnectionError: Can't connect to MySQL server on '127.0.0.1' (111 "Connection refused")`

Noting possible relationship to this Sentry error: https://github.com/publiclab/plots2/issues/6271

Hmm, this is indicating that this can come from a change to docker-compose: https://stackoverflow.com/questions/55427429/rails-app-using-docker-compose-wont-connect-to-the-mysql-container but ours haven't changed in months... 

https://github.com/publiclab/plots2/tree/master/containers

@icarito any idea why this could be happening in Travis?

**Comment by jywarren** [comment]
Example log: https://travis-ci.org/publiclab/plots2/jobs/584610576

**Comment by jywarren** [comment]
* [Travis tracker](https://travis-ci.community/search?q=mysql%20connect) doesn't seem to show an issue. 
* MapKnitter is not showing this either. 
* Dockerfile, docker-compose, Gemfile havent' been changed since early August or earlier

**Comment by icarito** [comment]
Hi all,
This is too bad, I am guessing travis is busier for some reason maybe Mysql is taking longer to start? I tried extending the timeout to 10 and it seemed to go better: https://travis-ci.org/publiclab/plots2/builds/585131767?utm_source=github_status&utm_medium=notification (3 out of 5 test jobs passed, only 1 failed with mysql error). I'll try setting it to 15, we may want to add a "wait_for_open_port" kind of script.

**Comment by icarito** [comment]
I'm trying out a longer delay in https://github.com/publiclab/plots2/pull/6283

**Comment by icarito** [comment]
![imagen](https://user-images.githubusercontent.com/199755/64918066-9187bb00-d75e-11e9-9d06-496f015a915f.png)

Seems to have worked for #6283!
(the failed functional test actually is a failed test, not a testing error).

So a quick solution is setting sleep to 15 in travis, @jywarren !

**Comment by icarito** [comment]
I made a small PR as a starting point with this first solution https://github.com/publiclab/plots2/pull/6295

**Comment by jywarren** [comment]
Great, thank you!
