### ISSUE TITLE
Create new question page (following style guide!)

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6294]
#1994 describes the new design style guide, and we now have new designs for the basic Note and Wiki pages. But the Questions page is still looking a bit old. We should make the questions page use the same template as the notes page, so it is similarly cleaned up. We may need to preserve the "related questions" on the sidebar. But otherwise let's get it looking nice and minimal again! 

We'd love help with this!

**Comment by CleverFool77** [comment]
Hi @jywarren Is there new design draft for this design ?

**Comment by dinaelhanan** [comment]
@jywarren @CleverFool77 sorry for my absense the past few months! It was a busy time with family, friends, work and school so I took some time off of github. I'll be a lot more active the coming months so you'll see me around more often :) This looks like a good issue for me to start on. I think @CleverFool77 tried to update the design for the questions page in #5948 but her changes weren't applied. Should I open a new PR and add your changes to app/views/questions/__questions.html.erb ?

**Comment by jywarren** [comment]
We don't have a new design sheet for this. But it should be almost identical to the notes page design in the style guide, with the addition of the sidebar listing of related questions. Ideally we'd be able to consolidate the templates - perhaps we could just use the notes template instead of the current questions one?

@dinaelhanan we're so happy to see you! Glad to hear it! On the design @CleverFool77 did, it was just for the question card - not the whole page. Here, we're trying to work on the full question page itself - like at this URL:

https://publiclab.org/questions/adam-griffith/08-27-2019/favorite-camera-for-balloon-kite-mapping

![image](https://user-images.githubusercontent.com/24359/65049823-6a82e200-d934-11e9-8784-11de9a708c0b.png)


See how it differs (not a huge amount, but in some key ways) from the basic notes page:

https://publiclab.org/notes/warren/08-27-2019/bringing-public-lab-s-multispectral-image-processing-to-leaflet-maps

![image](https://user-images.githubusercontent.com/24359/65050106-dd8c5880-d934-11e9-8446-8dc3b0b5b35b.png)


The changes are pretty small, actually, just the header, really:

![image](https://user-images.githubusercontent.com/24359/65049912-900feb80-d934-11e9-8995-2a485774bd02.png)

**Comment by jywarren** [comment]
Also noting that there is a "tidying up the header" issue open here which applies equally to Wikis, Notes, and Questions:

https://github.com/publiclab/plots2/issues/5956

That'd be a great follow-up to this on!

**Comment by pydevsg** [comment]
#6239

**Comment by pydevsg** [comment]
#6238

**Comment by pydevsg** [comment]
#6239

**Comment by pydevsg** [comment]
@jywarren , I think we can add this issue for GCI task list, with medium tag.

**Comment by jywarren** [comment]
Awesome! I can tag it if you want to add it? Thanks!

**Comment by pydevsg** [comment]
Yes, do tag it with gci and medium

**Comment by dinaelhanan** [comment]
i'll be finishing this up this weekend. Setting up my local dev environment took longer than expected :/

**Comment by pydevsg** [comment]
Go ahead @dinaelhanan :rocket:

**Comment by pydevsg** [comment]
@dinaelhanan , this task is assigned for the gci candidates.So, if you haven't done any PRs its fine , please don't make one. Thanks :)

**Comment by SidharthBansal** [comment]
Can anyone hide unwanted comments and make it consistent with GCI guidelines?
I will really appreciate this gesture!

**Comment by pydevsg** [comment]
@SidharthBansal I am taking the initiative will do the same and later delete this comment too.
Thanks for the advice.

**Comment by pydevsg** [comment]
**Updated on GCI Dashboard**

**Comment by SidharthBansal** [comment]
Published

**Comment by Uzay-G** [comment]
Hey @jywarren I was trying to look at how I could change the design and noticed that the [question page](https://publiclab.org/questions/adam-griffith/08-27-2019/favorite-camera-for-balloon-kite-mapping) sidebar is not placing itself next to the body of the question but instead it is placed after all the comments at the bottom of the page.

I don't have this problem on my local server so I used my devtools and noticed that this div of the application.html.erb file is somehow not a parent of the sidebar. https://github.com/publiclab/plots2/blob/3bd5522fbedfebdd24fb6062e59ee587df3f2324/app/views/layouts/application.html.erb#L117
I'm not sure if this is an actual problem because the stable version of publiclab and my local server work fine so it's just the publiclab.org website. 

A potential cause for this would be that an ```</div>``` tag was added somewhere that is closing the ```<div class="row">``` too early.

**Comment by jywarren** [comment]
Oof, those are the toughest type of HTML error to find. Can you confirm this is happening on all question pages, or is it possibly related to just that one page? Thanks!

**Comment by Uzay-G** [comment]
The error (at least for me) is present on about half of the questions of the publiclab site I am looking at and is not present at all locally. Example problem pages are:
- https://publiclab.org/questions/stevie/12-04-2019/what-are-the-health-impacts-of-the-aluf-plastics-plant-from-air-pollution
- https://publiclab.org/questions/stevie/12-16-2019/are-there-simple-tests-for-nitrates-in-well-water
-https://publiclab.org/questions/francesco49/11-22-2019/driver-usb-camera-community-microscope
- https://publiclab.org/notes/warren/08-27-2019/bringing-public-lab-s-multispectral-image-processing-to-leaflet-maps
This one seems fine: https://publiclab.org/questions/ThomasTaufan/11-26-2019/how-can-i-process-the-images-taken-from-modified-camera

**Comment by Uzay-G** [comment]
Should I create an issue?
