### ISSUE TITLE
Issues with cross-wired comment preview buttons - break this up

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/plots2#6297]
# Problem

Heres the page used for gif and screenshot: https://publiclab.org/questions/nickyshen0306/09-12-2019/how-to-design-a-camera-for-calculating-endvi

Easier to just show... the preview button on an editor should not be coupled to multiple editors on the page:

![exx](https://user-images.githubusercontent.com/41092741/64926446-8e76e400-d7cb-11e9-9069-75a94e3f645c.gif)

Besides being unusual behavior, it results in a lot of other problems like losing your text, confusing output (Has previously been documented in #3534). 

<br>

The issue continues:  this is a screenshot of my page with 3 editors on it at a time, of two different varieties. The top editor is to comment on the last comment thread on the page, the middle editor is to comment on my own comment, and the bottom editor is to create a new comment: 

<img width="513" alt="Screen Shot 2019-09-15 at 3 05 30 PM" src="https://user-images.githubusercontent.com/41092741/64926458-c5e59080-d7cb-11e9-8441-cd8d1b711782.png">

# Solution 

We may want to take start by removing the functionality to comment on comments and just leave creating new comments with one editor (just remove it front-end, not back-end data). When we're ready, we can start breaking apart tasks to re-implement a more complex interface. It seems like re-implementing will be much easier than debugging through it.

**Comment by jywarren** [comment]
Hi @sashadev-sky - thanks for the great documentation. I wanted to CC @ViditChitkara who worked on this recently as did @gauravano -- the relevant code is here:

https://github.com/publiclab/plots2/blob/f29f90d6690d5a3c6d578221af79c0cd2b7bafee/app/views/comments/_form.html.erb#L92-L100

I believe the `Publish` button works properly - independently, that is. But my initial thought on the `Preview` button is that it is not properly addressing the correct container in toggling the preview.

I actually think this is solvable directly, BUT I think a priority should be to write a system test which protects it from future breakages. The reply-to-comment system has been some long hard work to get working correctly and I'd love to ensure we preserve it -- tests seem like the best way to do that!

**Comment by sashadev-sky** [comment]
@jywarren ok hopefully one of them @gauravano @ViditChitkara can either solve this or open it up as  a GCI task! Then I can close this. I would put this as a "medium" task given that you provided the solution
