### ISSUE TITLE
power tag not working on all pages 

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#6299]
# Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
I was looking to add a power tag on https://publiclab.org/wiki/glossary to make https://publiclab.org/about a parent page for it, however the power tag feature isn't working on this page. Perhaps because this is one of the wikis without the wiki/about?

**Comment by jywarren** [comment]
Hi Stevie, the `/about` page is a special page and it had some old metadata attached to it. I was able to log into the database and delete it, and now it works. I also fixed ~12 other pages similarly affected. Thanks for reporting!
