### ISSUE TITLE
Uploading CSVs in questions 

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#6301]
**Please describe the desired behavior.**
Hi, I've been working with a community member on this question https://publiclab.org/questions/stevie/08-23-2019/what-are-best-practices-and-tools-to-help-clean-up-data-sets#c25454. He has been trying to upload a couple CSV files into the question so people can put some eyes on his data, but we haven't been able to get them to upload.

**Comment by jywarren** [comment]
Thanks for reporting, I tried a very small CSV but have also asked Crispin to email me the ones he had trouble uploading: https://publiclab.org/questions/stevie/08-23-2019/what-are-best-practices-and-tools-to-help-clean-up-data-sets#c25527

**Comment by jywarren** [comment]
OK, I found the error, but still trying to understand it:

`ActiveRecord::RecordInvalid: La validación falló: Photo has contents that are not what they are reported to be`

```
{action: create, controller: images, image: {photo: #<ActionDispatch::Http::UploadedFile:0x00007f04a6aa2880>}, nid: undefined, uid: 1}
--
```

Linked to this maybe: https://github.com/thoughtbot/paperclip/issues/1924

**Comment by jywarren** [comment]
OK, my theory (and i think i have a fix):

1. small CSVs upload with proper `text/plain` content type
2. large CSVs upload with `application/octet-stream`

So, my initial fix made large CSVs work. But small ones stopped working. Now I'm trying to allow both types.

**Comment by jywarren** [comment]
We'll want the graph to look very roughly like this: 
![image](https://user-images.githubusercontent.com/24359/65466041-bdc0cd00-de2b-11e9-9e86-11c9fe52ac0c.png)

**Comment by jywarren** [comment]
Linking this thread back to Isha's work here: https://publiclab.org/notes/IshaGupta18/08-26-2019/google-summer-of-code-2019-final-work-product-isha-gupta#c25570

**Comment by jywarren** [comment]
and confirmed that this worked!
