### ISSUE TITLE
Correct Sign-up Form Validation message 

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#6303]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

# Problem

When a user tries to submit an empty sign up form, and also does not check off the recaptcha box, This output is shown: 

![image](https://user-images.githubusercontent.com/41092741/64667642-7b10f500-d428-11e9-8273-fe91767a290e.png)

# Solution

Instead, we want all the relevant errors ("field cannot be empty" or so) to be listed along with the failed recaptcha verification. 

Each box in this problem is worth some points. We will accept answers that complete one part and not the other, but encourage you to go for all 3. Completion of all three will result in bonus points :)

- [ ] fix the `create` action so that the correct errors show
- [ ] fix the error messages themselves as well. If you see below, there are three different errors for email, but only one of them is correct. 
- [ ] write a test reflecting this fix. Guidelines: the test must fail without your changes, and your changes are what makes it pass.

![image](https://user-images.githubusercontent.com/41092741/64667496-faea8f80-d427-11e9-85b9-725f1c9cb19d.png)

**Comment by SidharthBansal** [comment]
Codelinks 
1. Sign Up form - https://github.com/publiclab/plots2/blob/master/app/views/users/_create_form.html.erb
2. Dynamic form - https://github.com/publiclab/plots2/blob/5c0d96274bd0be15feba69d8f30093082402ace5/lib/dynamic_form/action_view/helpers/dynamic_form.rb
3. Local files - https://github.com/publiclab/plots2/blob/3a96771279cf4fbf31ff6279f99f068a6d7a2a47/config/locales/en.yml

**Comment by ananyaarun** [comment]
This has been added to GCI dashboard, Thanks !

**Comment by SidharthBansal** [comment]
From #3340

**Comment by chen-robert** [comment]
Can I have this task assigned to me?

**Comment by SidharthBansal** [comment]
Are you notdeghost?

**Comment by chen-robert** [comment]
Yes

**Comment by SidharthBansal** [comment]
Go ahead

**Comment by chen-robert** [comment]
Great, thanks!

**Comment by chen-robert** [comment]
@SidharthBansal I've fixed the first two parts but I'm not too sure how to write the tests. Should it be under system, unit, integration, or something else? I would greatly appreciate it if you could point me in the right direction, thanks!

**Comment by SidharthBansal** [comment]
What do you think?
It depends on your thinking.
If you are testing a sequence as follows:
1. Sign up with wrong details
2. Sign up with right details
3. Dashboard with welcoming message
1-3 suggests integration test altogether
If you want to just test 1 then unit test will work.
Functional tests are for controllers.

**Comment by SidharthBansal** [comment]
Please think the intended behavior and write test(s) accordingly

**Comment by SidharthBansal** [comment]
What is the PR numberl?

**Comment by chen-robert** [comment]
@SidharthBansal I have not made the PR yet, I wanted to write the test before proceeding.

**Comment by SidharthBansal** [comment]
ok

**Comment by SidharthBansal** [comment]
Please tell me the code link so that I can make it hard instead of medium

**Comment by SidharthBansal** [comment]
Changed to hard from medium

**Comment by SidharthBansal** [comment]
As this issue may require multiple tests, I will be happy to open a `hard` task for tests for this issue. Chen can claim and get points for both the hard tasks once his pr is merged.
Thanks

**Comment by SidharthBansal** [comment]
@chen-robert I observed that you have not claimed this task on the dashboard. Why?

**Comment by chen-robert** [comment]
@SidharthBansal the task expired for me on the GCI dashboard. Is there any way for me to reclaim it or extend the time limit?

**Comment by chen-robert** [comment]
I had initially claimed it and was working on it but it expired when I was sleeping. I was unable to find it afterward and wasn't sure if you had removed it?

**Comment by chen-robert** [comment]
Also, all three of my other PRs are ready to merge now, I've fixed the corresponding Travis errors :tada:

**Comment by SidharthBansal** [comment]
Please try to reclaim it.

**Comment by SidharthBansal** [comment]
I have not removed it

**Comment by chen-robert** [comment]
@SidharthBansal I have reclaimed it now, thanks!

**Comment by SidharthBansal** [comment]
This issue is resolved

**Comment by SidharthBansal** [comment]
@chen-robert kindly reclaim it on dashboard for points
