### ISSUE TITLE
Reorganize /contributors/___ pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6304]
(follow-up to https://github.com/publiclab/plots2/pull/5632) cc @IshaGupta18 🙌 

We now show 2 types of users on our contributor pages like https://publiclab.org/contributors/water-quality

1. contributors - who have posted using this topic or commented on this topic
2. followers - who are following this topic and will get notified when new content is posted to it

They're a bit messily next to each other:

![image](https://user-images.githubusercontent.com/24359/64988376-55a54080-d899-11e9-8ac3-1cf20b434faa.png)

Let's:

* [ ] show contributors in a table on top, but in each row, mark if that person is ALSO following -- maybe, with an eye icon? In a column called `Following`, maybe?)
* [ ] then let's show people who are NOT in the first list, but ARE subscribed. This can be in a second table with the title `Following`. 

Should we have a short text explanation of the distinction?

**Comment by ebarry** [comment]
great plan!

**Comment by Anupam-dagar** [comment]
@jywarren I would like to take this up.

**Comment by IshaGupta18** [comment]
Go ahead! Let me know if you need some help!

**Comment by Anupam-dagar** [comment]
@jywarren Can we include a badge in front of the user's name in the contributors table to signify following or maybe coloring the row?

**Comment by IshaGupta18** [comment]
I believe a badge would be a better idea. What do you think?

**Comment by jywarren** [comment]
If there is a unique column for the indicator, that'd be great, so it has a header label. But within that column, I think a badge with the `<i class="fa fa-eye"></i>` icon could work! What do you think?

**Comment by jywarren** [comment]
Hi, how is this coming along, did you need any help? Thanks!

**Comment by NitinBhasneria** [comment]
@nstjean I don't know how to check whether the person is following or not. Do you know how to check?

**Comment by nstjean** [comment]
That is a good question. Let me take a look!

**Comment by NitinBhasneria** [comment]
I have made a pr for this just have a look.
@nstjean

**Comment by KarishmaVanwari** [comment]
Is this issue open? @jywarren @ebarry @IshaGupta18

**Comment by TildaDares** [comment]
Hi @KarishmaVanwari, it still is.

**Comment by KarishmaVanwari** [comment]
@TildaDares I've opened a PR #10778. Please have a look!

**Comment by KarishmaVanwari** [comment]
@TildaDares I've created another PR #10778. Please review. Apologies for the inconvenience.
