### ISSUE TITLE
Add `# posts by # contributors | # followers` to tag pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6305]
We have 2 types of users we'd like to show counts for on pages like https://publiclab.org/tag/water-quality

1. `contributors` - who have posted using this topic or commented on this topic
2. `followers` - who are following this topic and will get notified when new content is posted to it

We'd like to list them just below the main image banner of the page, where it has small `by views` and `by likes` buttons:

![](https://user-images.githubusercontent.com/24359/64982363-073d7500-d88c-11e9-844b-99bdaedf64e6.png)

Let's move the `By Views` and `By Likes` buttons to the right to be with the `By Type` dropdown.

They are here: https://github.com/publiclab/plots2/blob/f29f90d6690d5a3c6d578221af79c0cd2b7bafee/app/views/tag/show.html.erb#L53-L56

We can move them over here: https://github.com/publiclab/plots2/blob/master/app/views/tag/show/_nav_tabs.html.erb

Then let's add this text to the left side where they had been:

`# posts by # contributors | # followers (?)`

of course, substituting counts for each. 

* For posts, use `Tag.find_nodes_by_type([tagname], 'note', false).count`: https://github.com/publiclab/plots2/blob/f29f90d6690d5a3c6d578221af79c0cd2b7bafee/app/models/tag.rb#L105
* For contributors, use `Tag.contributors(tagname)`: https://github.com/publiclab/plots2/blob/f29f90d6690d5a3c6d578221af79c0cd2b7bafee/app/models/tag.rb#L74
* For followers, use `Tag.follower_count(tagname)`: https://github.com/publiclab/plots2/blob/master/app/models/tag.rb#L174

Finally, we'd like to use the fontawesome icon `fa-question-circle-o` (https://fontawesome.com/v4.7.0/icon/question-circle-o) at the end of the line, and link that icon to: https://publiclab.org/wiki/contributors (a page which we'll create later!)

We'd love help with this one!

**Comment by ebarry** [comment]
Great! This will add a lot of helpful context at-a-glance to these type of pages

**Comment by CoderJolly** [comment]
Could I take this issue ?

**Comment by jywarren** [comment]
That would be great, thank you!!!

**Comment by anthony-zhou** [comment]
I would like to work on this.

**Comment by jywarren** [comment]
Hi @anthony-zhou -- we'd love help with it. Did you want to open a pull request? Thanks!

**Comment by anthony-zhou** [comment]
Yes

**Comment by anthony-zhou** [comment]
@jywarren How can I test the pages offline to see whether my changes are working? (This is my first time contributing)

**Comment by jywarren** [comment]
You can add a tag to a page by logging in and clicking the + icon in the
sidebar, and then view the tag page for that tag! Like /tag/test for the
tag "test". Does that make sense?

**Comment by anthony-zhou** [comment]
Thanks - that makes sense. I've spent the past few days trying to install and run the project locally and I just got it to work. 
However, when I try to add a tag, an error message is shown: "Incomplete response received from application." The tag is not added. Also, the site runs very, very slowly. Are these common problems and do you know a way I could fix them?

**Comment by anthony-zhou** [comment]
The site looks correct, although I wasn't able to add tags to the posts I made locally. I opened a pull request with my changes. Let me know if anything should be fixed or improved!
