### ISSUE TITLE
Add counts to `by type` dropdown on tag pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6306]
![image](https://user-images.githubusercontent.com/24359/64982363-073d7500-d88c-11e9-844b-99bdaedf64e6.png)

On our new tag pages, let's add counts to each type in the `By Type` dropdown:

![image](https://user-images.githubusercontent.com/24359/64989752-34921f00-d89c-11e9-871e-e389579f6554.png)

Each type can be counted a different way, and should use a 'pill badge' from the Bootstrap UI library: https://getbootstrap.com/docs/4.3/components/badge/#pill-badges

* For posts, use `Tag.find_nodes_by_type([tagname], 'note', false).count`: https://github.com/publiclab/plots2/blob/f29f90d6690d5a3c6d578221af79c0cd2b7bafee/app/models/tag.rb#L105
* For questions, use: `Tag.find_nodes_by_type("question:#{tagname}", 'note', false).count`: https://github.com/publiclab/plots2/blob/f29f90d6690d5a3c6d578221af79c0cd2b7bafee/app/models/tag.rb#L105
* For wikis, use `Tag.find_nodes_by_type([tagname], 'page', false).count`: https://github.com/publiclab/plots2/blob/f29f90d6690d5a3c6d578221af79c0cd2b7bafee/app/models/tag.rb#L105
* Maps: let's not worry about these for now!

The lines where changes can be made are here:

https://github.com/publiclab/plots2/blob/69d751e2723b2d07db88cc95fd28461168f522f0/app/views/tag/show/_nav_tabs.html.erb#L10-L11

We'd love help with this! Thank you!

**Comment by jywarren** [comment]
Related to https://github.com/publiclab/plots2/issues/6305 too!

**Comment by anna-dorigo** [comment]
Hi everyone! this is my very first time helping in an open source project and I would like to help with this feature if thats ok?

**Comment by jywarren** [comment]
We'd love the help! However just noting that this hasn't (yet) been
formatted as a first-timers-only issue so we haven't broken it down step by
step. If it seems like you are comfortable taking it on, please go ahead!
But if you'd like we can go through and add some more information and hints
to help you out. Thanks a bunch for your help!

**Comment by anna-dorigo** [comment]
I did the fork and the clone in my computer, Im trying to get the environment running locally, I will let you guys know if I get stuck somewhere. Thanks so much for the opportunity!

**Comment by jywarren** [comment]
Great! There are some resources here on getting the environment running:
https://github.com/publiclab/plots2/issues/3840

Thank you too!

**Comment by CleverFool77** [comment]
Hi @jywarren @anna-dorigo How about showing the count in `badges` instead of simply displaying ?
https://getbootstrap.com/docs/4.3/components/badge/

**Comment by jywarren** [comment]
agreed! That'd be great!

**Comment by anna-dorigo** [comment]
Perfect! working on it!

**Comment by anna-dorigo** [comment]
UPDATE: Local environment working and started diving into the code

**Comment by anna-dorigo** [comment]
QUESTION: Im adding dummy posts, questions and wikis to my local dababase. Im using the following suggested calls: 

For this I get posts and questions added:
`Tag.find_nodes_by_type([tagname], 'note', false).count `

For this I get 0 even though there are questions
`Tag.find_nodes_by_type("question:#{tagname}", 'note', false).count`

For this I get the right amount of wikis
`Tag.find_nodes_by_type([tagname], 'page', false).count:`

Am I missing something related to the posts and questions?

here is the dump of the ActiveRecord for this call
`Tag.find_nodes_by_type([tagname], 'note', false).count `

`#<Node nid: 50, vid: 50, type: "note", language: "", title: "hola ", uid: 1, status: 1, created: 1569251406, changed: 1569251406, comment: 2, promote: 0, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 0, comments_count: 0, drupal_node_revisions_count: 1, path: "/notes/admin/09-23-2019/hola", main_image_id: nil, slug: "hola", views: 1, latitude: nil, longitude: nil, precision: nil>, 
#<Node nid: 48, vid: 48, type: "note", language: "", title: "hi4?", uid: 1, status: 1, created: 1568985333, changed: 1568985333, comment: 2, promote: 0, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 0, comments_count: 0, drupal_node_revisions_count: 1, path: "/notes/admin/09-20-2019/hi4", main_image_id: nil, slug: "hi4", views: 1, latitude: nil, longitude: nil, precision: nil>, 
#<Node nid: 47, vid: 47, type: "note", language: "", title: "hi3?", uid: 1, status: 1, created: 1568984838, changed: 1568984838, comment: 2, promote: 0, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 0, comments_count: 0, drupal_node_revisions_count: 1, path: "/notes/admin/09-20-2019/hi3", main_image_id: nil, slug: "hi3", views: 1, latitude: nil, longitude: nil, precision: nil>, 
#<Node nid: 45, vid: 45, type: "note", language: "", title: "hi2?", uid: 1, status: 1, created: 1568942870, changed: 1568942870, comment: 2, promote: 0, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 0, comments_count: 0, drupal_node_revisions_count: 1, path: "/notes/admin/09-19-2019/hi2", main_image_id: nil, slug: "hi2", views: 1, latitude: nil, longitude: nil, precision: nil>, 
#<Node nid: 44, vid: 44, type: "note", language: "", title: "hi?", uid: 1, status: 1, created: 1568942643, changed: 1568942643, comment: 2, promote: 0, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 0, comments_count: 0, drupal_node_revisions_count: 1, path: "/notes/admin/09-19-2019/hi", main_image_id: nil, slug: "hi", views: 1, latitude: nil, longitude: nil, precision: nil>]`

the nid 50 is a post and the rest are questions.

**Comment by jywarren** [comment]
Awesome! Uh hmmm. Are the questions tagged with `question:TAGNAME`
appropriately?

One thing you can do is to add your test content to the test fixtures, and
write a unit test in /test/unit/tag_test.rb which shows that `
Tag.find_nodes_by_type("question:#{tagname}", 'note', false).count` should
work -- i believe there are already test "question" posts in the test
fixtures as well, so you may be able to just add that unit test to confirm
that it's working properly?

**Comment by anna-dorigo** [comment]
Hi gain Jeffrey!

You were right I need to specify in the tag for example: "question:water"
that was my mistake. but is it normal that if people just add "water"
without the "question:tagname" it is not considered a question anymore and
is counted with the posts? shouldn't we add it in the code?

**Comment by anna-dorigo** [comment]
Guys do you have any preference on the type of badge? 

<img width="671" alt="Screen Shot 2019-09-24 at 10 52 31 AM" src="https://user-images.githubusercontent.com/1304609/65522905-7a14a480-deb9-11e9-9ca6-33ef2e105027.png">

**Comment by anna-dorigo** [comment]
Looking good people :) 

<img width="965" alt="Screen Shot 2019-09-24 at 10 57 38 AM" src="https://user-images.githubusercontent.com/1304609/65523419-3ff7d280-deba-11e9-8ac2-8a0f287b45a6.png">

Do you guys want me to change the format of the "people" badge too to make it uniform?

**Comment by jywarren** [comment]
Sure! And, this looks epically great!

**Comment by ebarry** [comment]
Fantastic!

**Comment by anna-dorigo** [comment]
Hi Guys! 

Im glad you guys liked it! Sorry I was away for a week, do you guys have a format in mind?

![](https://user-images.githubusercontent.com/1304609/65522905-7a14a480-deb9-11e9-9ca6-33ef2e105027.png)

I hope to make the pull request this weekend.

**Comment by jywarren** [comment]
We could go for red or blue, either works for me! Thanks a lot!

**Comment by anna-dorigo** [comment]
Hi Guys! 

I was finally able to submit the pull request. This is the final view of the UI:

<img width="1079" alt="Screen Shot 2019-10-12 at 11 48 13 AM" src="https://user-images.githubusercontent.com/1304609/66704356-298aad00-ece9-11e9-9065-2c7a5fa09988.png">

Fingers crossed everything will go smoothly!

P.D. my pleasure!! thank you so much for the opportunity!!

**Comment by ebarry** [comment]
This looks so good! Thank you @anna-dorigo !
