### ISSUE TITLE
UI discussion of individual tag page content

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6307]
![image](https://user-images.githubusercontent.com/24359/64987754-df540e80-d897-11e9-8fc8-b1ac8363f97b.png)

Our individual tag pages, such as at https://publiclab.org/tag/water-quality, follow the [style guide draft](https://publiclab.org/notes/warren/05-07-2019/introducing-a-draft-style-guide-for-public-lab) -- let's discuss specifics of how the collection of content below the main top "hero" area can be organized and navigated into. 

### Issues

@ebarry is worried about the amount of context the display of posts provides currently. Some questions to dig into this:

1. can you describe a "flow" -- like narrate someone using this and how you'd hope they navigate, or what they'd find?
2. One issue here is that it's quite hard to keep a manageable amount of information on this page. To some degree, some things need to be de-emphasized (not necessarily removed) in order to create clarity and focus on our priorities. This is one of our densest pages. 

### Goals

What is the overall goal of this page? 

@ebarry suggested it could look more like a Discourse forum, showing a range of different topics (sub-topics?), each showing a sense of recency and participation. In a sense that's the role of /tags, but is there a way that this page should be providing a second "tier" of sub-topics in a similar way?

### Ideas

@ebarry suggested making the # of comments and the date more prominent on the individual post cards. A minimal footer could show comment count in each card with an icon. Dates are a little harder in a limited amount of space. 

![image](https://user-images.githubusercontent.com/24359/64988024-89339b00-d898-11e9-8b6f-29b254d202ac.png)

Input appreciated! Thanks!

**Comment by jywarren** [comment]
Also just noting that the Style Guide guidance for post cards (actually esp the wiki example) shows space for sub-items, which would nicely fit comments:

![image](https://user-images.githubusercontent.com/24359/64991099-33aebc80-d89f-11e9-9326-24f142cbc5cf.png)

I think we could rework that here a bit:

![image](https://user-images.githubusercontent.com/24359/64991529-09a9ca00-d8a0-11e9-9eb4-2572db039872.png)

**Comment by jywarren** [comment]
I'm going to spin out the part about a few extra bits of info on the post card. If there are more follow-ups here, or more discussion, please chime in! Thanks!

**Comment by jywarren** [comment]
So I think the big open questions are:

* [ ] how do we make the different types more prominent without overwhelming too much visually?
* [ ] can we make space in this zone for presenting different types without using a dropdown?

![image](https://user-images.githubusercontent.com/24359/69678011-5107c000-1072-11ea-81a8-a82760099aa7.png)

There are a number of design options we can explore here, and I suggest "Pill Navs" could be a good option: https://getbootstrap.com/docs/4.3/components/navs/#pills

![image](https://user-images.githubusercontent.com/24359/69678300-2a965480-1073-11ea-9de6-f48602590ac6.png)

And that `by views` and `by likes` could be collapsed into a menu labelled `Sort`

**Comment by jywarren** [comment]
So this page has had some refinement since last update, and here's a screenshot from today:

**Comment by ebarry** [comment]
I agree we can delete Related Tags for now, especially if that allows us to make space in this zone for presenting different types without using a dropdown, for instance, using Pill Nav as @jywarren describes above. This is a feature request that i've heard again from @joyofsoy and @kgradowski in the past month, and this would be GREAT.

Once we get the Pill Nav in, and after three more weeks of onboarding the new Research Coordinator, then we can re-assess about Related Tags. In the meanwhile, I'll share my main concern that when on a very detailed tag like "drinking-water", there's no navigation up to the main Topic Area of "water-quality". See examples of these larger Topic Areas on https://publiclab.org/topics. The new Research Coordinator is being supported to learn about our current organization and develop an approach to issues like this.

**Comment by jywarren** [comment]
TODO: figure out what to do with the welcome text. 

(Quick note to comment out the Maps tab) - let's see what it looks like to move to tabs! Thanks, all.

**Comment by jywarren** [comment]
OK, here is a mocked up version (from our [mockups doc](https://docs.google.com/presentation/d/1TCZoTfuhamRVrUak8aDgqJAwSgyhRtZg2Pgacl2_4zc/edit#slide=id.g81e5b443c7_0_207)) with tabs vs. pills, with all the other changes made as well, but there is one ambiguity related to a request from Stevie + Joe as well - the "total count" should still remain, right? So the `133 contributors and 80 followers` count just after it, is this now redundant with the final `People` tab? Any suggestions on this?

![image](https://user-images.githubusercontent.com/24359/84829118-389ec900-aff5-11ea-9bcb-ad2aedaaaeb7.png)

![image](https://user-images.githubusercontent.com/24359/84829466-d2667600-aff5-11ea-98cc-414efc1c94c1.png)

I also want to note that for smartphone display, we could either:

1. revert to dropdown for very compact screens
2. hide other types as they no longer fit on the screen

Note that we would start by hiding the text in favor of just icons, on smaller screens, so the threshold for having to hide any tabs would be pretty low. Here are the icons (remember we are also removing Maps):

![image](https://user-images.githubusercontent.com/24359/84829974-a26ba280-aff6-11ea-9989-cf37bcc761e7.png)

**Comment by jywarren** [comment]
Starting implementation here: https://github.com/publiclab/plots2/pull/8046

**Comment by jywarren** [comment]
OK, #8046 is ready for final review, with screenshots there!

**Comment by ebarry** [comment]
The PR looks great, thanks! No changes from me.

**Comment by jywarren** [comment]
Completed and closing!!!
