### ISSUE TITLE
Refactor the code according to the coding standards

### ISSUE THREAD

**Issue by newbazz** [publiclab/plots2#6314]
Please mention all the files that you find are not according to the defined standards of the programming language.

**Comment by gmakey2k** [comment]
Hello, hi... new user!!!

**Comment by newbazz** [comment]
Hello @gmakey2k, https://github.com/rubocop-hq/ruby-style-guide this is the basic coding standards for ruby coding style. Now what you can do is, find ruby files that do not follow these coding standards, open an issue referencing to this issue and solve it. 
P.S: You can always use a linter to indent/make the file follow proper coding style.

**Comment by bermylle** [comment]
Hello!

**Comment by discombobulateme** [comment]
Hello, I would love to contribute to this issue, is it still available? Just need some guidance on which pages to check, all on Plot2?

**Comment by susanreenesaa** [comment]
the issue was closed @discombobulateme

**Comment by tawahpeggy** [comment]
i will like to work on this issue if it is still open

**Comment by cesswairimu** [comment]
Completed in https://github.com/publiclab/plots2/issues/6340
