### ISSUE TITLE
Mobile width issue in new questions page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6318]
https://publiclab.org/questions_shadow is our new questions page, but the bottom section doesn't flow properly on mobile browsers. We'd love some help sorting this out using the Bootstrap UI library!

![Screenshot_20190923-093633](https://user-images.githubusercontent.com/24359/65430381-d3130880-dde5-11e9-815f-ba6ee4243ecb.png)

**Comment by CleverFool77** [comment]
Hi @jywarren I would like to solve this.
Thanks !!

**Comment by jywarren** [comment]
Please do, I'd appreciate it! Thanks!!! I think some use of col- in
bootstrap responsive should work.

**Comment by CleverFool77** [comment]
Hi @jywarren I found some more issues while working on this. I'll fix them too in one PR.
Thanks !!

**Comment by jywarren** [comment]
Awesome!

**Comment by alexido19** [comment]
Can I contribute to this ?

**Comment by jywarren** [comment]
Hi @alexido19 - it looks like @CleverFool77 has this one, but maybe you'd be interested in helping with another issue? Maybe part of this one? https://github.com/publiclab/plots2/issues/5956
