### ISSUE TITLE
Table misaligned on /projects

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#6320]
Hello!

The table on the bottom of this page is showing up misaligned for me https://publiclab.org/wiki/projects. 
<img width="715" alt="Screen Shot 2019-09-23 at 3 02 21 PM" src="https://user-images.githubusercontent.com/7490478/65454506-3e270400-de13-11e9-9e85-14e74350cfb7.png">

I'm using Chrome.

**Comment by jywarren** [comment]
Not sure why this is happening! But, the template is here:

https://github.com/publiclab/plots2/blob/cba54993c9e42dd10c7ecb58be45f33a6f4335c4/app/views/grids/_wikis.html.erb#L12-L23

Thanks for reporting! 

Maybe it's the `d-none` and `d-md-inline` classes someone added there? We could try removing them. To see how one of these is made, see https://publiclab.org/wiki/power-tags

**Comment by dylmye** [comment]
Hello, would it be alright for me to have a crack at this? :)

**Comment by dylmye** [comment]
I had a quick look anyway, and it looks like the `d-md-inline` class (which adds the CSS prop `display:inline` in the media query `min-width: 768px`) is the cause. Is there any particular reason for using this class / the `d-none` class for screens smaller than 768px?

Reproduced on FFX and Chrome

**Comment by jywarren** [comment]
Not to my knowledge -- if you'd like to file a fix we'd be very grateful!
If you could include screenshots at different widths that would be great.
Thanks!

**Comment by dylmye** [comment]
Sure thing! Is it alright if I submit it tomorrow so it's accepted under Hacktoberfest? 
Thanks

**Comment by jywarren** [comment]
Of course!

**Comment by maniac-tech** [comment]
Is there any update on the PR or the issue here @jywarren ?

**Comment by dylmye** [comment]
@maniac-tech I'm pushing up my fix this lunch, I was busy yesterday, apologies

**Comment by AdityaSatnalika** [comment]
Pushed and Created a pull request for the Fix of the problem . Branch #Bug_Plots2_6320

**Comment by steviepubliclab** [comment]
Thank you!!

**Comment by AdityaSatnalika** [comment]
Hey I am Not Able to push the code as its showing permission denied

**Comment by jywarren** [comment]
Hi @AdityaSatnalika perhaps you need to fork the project and push to your own fork?

Thanks @dylmye !

**Comment by AdityaSatnalika** [comment]
Will Do that . But how will I create a pull request then ?
