### ISSUE TITLE
Add functional tests for sorting alphabetically by title on /tags and /wiki pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6346]
These pages both offer alphabetic ordering!

https://publiclab.org/wiki/?sort=title
https://publiclab.org/tags?sort=name&order=asc

But both could use functional tests. We'd love help with this!

The wiki page actually has a test, but it doesn't check if the results are sorted alphabetically:

https://github.com/publiclab/plots2/blob/5177ea83550fc153efba5faace4dff70414aa512/test/functional/wiki_controller_test.rb#L27-L32

The tags page has no such specific test for alphabetic order. We'd love help with this!

https://github.com/publiclab/plots2/blob/5177ea83550fc153efba5faace4dff70414aa512/test/functional/tag_controller_test.rb#L145-L161

**Comment by jywarren** [comment]
Follow-up to https://github.com/publiclab/plots2/issues/2069 !

**Comment by StlMaris123** [comment]
Hi @jywarren on plots2/test/functional/wiki_controller_test.rb, we are passing the param `alphabetic`, which translates to `/wiki?order=alphabetic`. It does not have any effect on the ordering, can we modify the test to test sort instead.
Also is it okay to add sort in desc?

**Comment by jywarren** [comment]
Oh that's a great idea. Sounds good! Thanks!!!
