### ISSUE TITLE
Fix back to top button for mobile view

### ISSUE THREAD

**Issue by pydevsg** [publiclab/plots2#6352]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file (https://github.com/publiclab/plots2/blob/master/app/assets/stylesheets/style.css) in the `$plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

In the current UI the back to top button is too big and it hides some content

![Previously(current UI) - backtotop](https://user-images.githubusercontent.com/40278255/65840670-6e9dff00-e339-11e9-88c6-9aa5e6628453.jpeg)

After giving the media queries with some css, this can be solved  

## Inside the media query add the given css 
@media (max-width:400px)  { 
 .back-to-top i {
    font-size: 40px;
    position: fixed;
    bottom: 20px;
    right: 20px;
  }
}

Expected UI change after doing the above step will be -
![ExpectedUI backtotop (Updated)](https://user-images.githubusercontent.com/40278255/65841007-b8d4af80-e33c-11e9-86fb-cd43d30f7d07.jpeg)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by shiv-1998** [comment]
Hi can I work on this?

**Comment by shiv-1998** [comment]
I've raised a PR for the same.

**Comment by pydevsg** [comment]
Change your PR a bit and add the Issue Number with it and then your 1st PR will be merged 😄

**Comment by Askat08** [comment]
Hi there, may I take this up?

**Comment by garg3133** [comment]
@pydevsg Sorry! But I'm unable to understand how can the fix given by you solve the problem? The back to top button is causing problems in small screens (360px width as shown in screenshot), right! But the change you have suggested will decrease the size of back to top button for screens bigger than 400px as you have written "min-witdh:400px" in the media query.

> @media (min-width:400px) {

I think it should be "max-width:400px". Please correct me if I'm wrong. 

Thank You!

**Comment by pydevsg** [comment]
@garg3133 Thankyou very much for your valuable correction, actually it will be max-width not min-width, I agree with you. I fixed it but there was a small typo from my side.

**Comment by pydevsg** [comment]
Hi @Askat08, a PR has already been given for this issue you can check for first timers issues and fto from - [code.publiclab.org](https://code.publiclab.org)

**Comment by pydevsg** [comment]
@shiv-1998 please provide a screenshot and complete the issue.

**Comment by pydevsg** [comment]
@SidharthBansal can I make this issue for the gci candidate, if so I will add them in GCI tasklist.

**Comment by SidharthBansal** [comment]
Sure Thanks
