### ISSUE TITLE
Tiny Typo fix!

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#6359]
Hello! 
### Please describe the problem (or idea)

As reported by @joyofsoy, when someone publishes their draft, the text has a typo “Your work is now visible publically”.  "Publically" should be spelled "publicly".

This may be in the general "Publish" popup message also, but we are not sure. Is there a way to search for that typo?

> What did you expect to see that you didn't?

"Publically" should be spelled "publicly"

### Please show us where to look

https://publiclab.org/post -- once a post goes live

### What's your PublicLab.org username?

> This can help us diagnose the issue: 
Liz

Thank you!

**Comment by Redm0nd** [comment]
Hi, 

I have a fix for this on my fork, is it okay if i raise a PR?

**Comment by globefire** [comment]
is it open @ebarry  @seabl ?

**Comment by gauravano** [comment]
Hi @globefire, this issue is reserved for @tauhir as they showed their interest in getting an issue assigned. But, we'd be happy to create a issue for you if you want. Thanks!

**Comment by gauravano** [comment]
Also, @tauhir are you working on this as I can't see your PR tagged here. Thanks!

**Comment by tauhir** [comment]
@gauravano I'm working on this now, thanks.
