### ISSUE TITLE
Small text change on Login/Signup modal

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#6360]
**Please describe the desired behavior.**

This is a request by @joyofsoy to slightly edit the wording on the Login/Signup modal which currently reads:
 
>Forgotten or lost your password? Reset it by clicking here

to 

>Forgot your password? Reset here.

The hyperlink should be on the word "here". 

**Additional context**

The text appears in both of these situations, as shown in screenshots below: 

<img width="643" alt="Screen Shot 2019-09-25 at 4 06 10 PM" src="https://user-images.githubusercontent.com/161439/65987169-4acedc00-e453-11e9-8180-c0276acb0ee8.png">

<img width="899" alt="Screen Shot 2019-09-25 at 4 05 44 PM" src="https://user-images.githubusercontent.com/161439/65987191-56ba9e00-e453-11e9-836a-34f453ead3ac.png">

Thank you for reading!

**Comment by amilaneni99** [comment]
Hi, I would like to give this a shot. Thanks

**Comment by ebarry** [comment]
Thanks! This closed issue may contain helpful code links for the Login/Signup Modal: https://github.com/publiclab/plots2/issues/2866

**Comment by amilaneni99** [comment]
Hey @ebarry I've created a PR. It would be great if you review it. Thanks!

**Comment by ebarry** [comment]
Thank you so much @amilaneni99 !!! I really appreciate it! 
I just read the PR thread and wish to thank you and @seabl both for making this happen!
