### ISSUE TITLE
New "Questions" interface not showing questions

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#638]
Hi @ananyo2012 
Was wondering if you can help me figure out what's going on with my browser and the /questions page.

### What happened just before the problem occurred
I was testing out the new "Questions" interface. I went to the URL and got this screen where none of the questions were visible: 
![screen shot 2016-07-28 at 8 44 46 am](https://cloud.githubusercontent.com/assets/7490478/17214737/f94b83ce-549f-11e6-97fb-a88004b71a0b.png)

When I click between pages, (1/2 or Previous/Next) the questions flash on the screen and disappear. 

### Relevant URLs
https://publiclab.org/questions/

### Browser, version, and operating system
Chrome, Version 51.0.2704.103 (64-bit), OS: X EL Capitan Version 10.11.3

**Comment by ananyo2012** [comment]
@steviepubliclab Does the same happen for the Popular and liked urls?

**Comment by steviepubliclab** [comment]
yes.

**Comment by ananyo2012** [comment]
Ok trying to figure out the problem.

**Comment by steviepubliclab** [comment]
I'm still having a problem with this on chrome, but it seems to be working on my Safari.

**Comment by jywarren** [comment]
wonder if this is related to sessions in
https://github.com/publiclab/plots2/issues/672 ?

stevie can you try looking in chrome in incognito mode?

**Comment by steviepubliclab** [comment]
It does show up in my incognito window. Strange.

**Comment by ananyo2012** [comment]
@steviepubliclab was having this problem before the changes were published. Don't think this is related to #672

**Comment by jywarren** [comment]
I just meant that it could relate to sessions, so I wonder if a broader fix
to sessions could resolve both?

**Comment by jywarren** [comment]
Just checking if you've made progress with this or if I can help out. Thanks!

**Comment by ananyo2012** [comment]
Just hold on a bit Jeff. I haven't figured it out yet. I will respond to
this as soon as I figure out something.
ᐧ

**Comment by ananyo2012** [comment]
@jywarren Can you see this one? I can't figure out what is the problem. As per the image @steviepubliclab  posted at the beginning pagination links are present. But questions don't show up. This shouldn't be related to sessions since the questions are fetched from the database and then listed.

**Comment by ananyo2012** [comment]
@steviepubliclab Can you once more confirm if this is happening still now since a lot of code has been changed in the past few days?

**Comment by steviepubliclab** [comment]
I'm seeing them now when I go to the page. Seems fixed to me.
-Stevie

**Comment by jywarren** [comment]
Super, thanks!!
