### ISSUE TITLE
Add package.json and yarn.lock to git-ignore

### ISSUE THREAD

**Issue by mathyoudawson** [publiclab/plots2#6384]
When installing the application locally the following files were modified.
They shouldn't be checked into git as far as I know

```
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   package.json
        deleted:    test.sqlite-journal
        modified:   yarn.lock

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        package-lock.json
```

> What happened just before the problem occurred? Or what problem could this idea solve?
Setting us the application locally including running redis locally through `bundle exec sidekiq`

> What did you expect to see that you didn't?
The aforementioned files showing in git status

### Please show us where to look
git status

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by gauravano** [comment]
It depends on project to project and community to community. Some prefer to track and some not. I  will say, it should be responsibility of the user to add changes which they wanna make in a commit. And, package.json, package-lock.json and yarn.lock require changes occasionally as we need to update dependencies, so I'll say not to add them to gitignore. 
You can add test.sqlite-journal in there. @jywarren what you think?

**Comment by mathyoudawson** [comment]
@gauravano Sounds reasonable! Happy to just add `test.sqlite-journal` or close the issue/PR

**Comment by gauravano** [comment]
yeah remove the test.sqlite-journal from repo and add it to gitignore. Thanks!
