### ISSUE TITLE
multiple page tab bars 

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#6387]
I was on this page https://publiclab.org/questions/tag/pm?page=2 scrolling through questions, when I saw it has two scroll bar arrows to toggle between pages: 
<img width="1008" alt="Screen Shot 2019-10-03 at 10 34 56 AM" src="https://user-images.githubusercontent.com/7490478/66136860-25b0a980-e5ca-11e9-823d-002b44c0ef4a.png">

**Comment by nstjean** [comment]
I'll take this on. :)

**Comment by CoderJolly** [comment]
> I'll take this on. :)

Sure @nstjean , pls go ahead. Feel free to ask anything. 😄 😄

**Comment by nstjean** [comment]
So I've identified the problem - the `asked-tab` and `answered-tab` are both showing at all times even though only one is marked active. I can easily update the CSS to hide the inactive one, but there are further problems:
1. The tabs at the top of the page don't work to switch the active group.
2. There are no questions in the "answered" section, only in the "asked" section
3. The paginator for the "answered" section is displaying for the number of items in "asked" - this may be fixed when the logic for #2 is fixed.

My question is, do I solve just the initial problem with a pull request and break up the remainder into new issues? Or should I fix all of it together?

**Comment by gauravano** [comment]
If you have a good understanding of related code then go ahead for solving all parts, as you need to increase complexity bit by bit. Thank you!

**Comment by nstjean** [comment]
Ok, I'll go ahead and try it! I am new to Ruby but this will be a good challenge.

**Comment by gauravano** [comment]
Oh, I hope, it's not your first issue, because you might wanna try an easier issue first.

**Comment by nstjean** [comment]
Ok what I'll do is split it up. I'll solve the first part of this, the easy issue, and do a pull request for practice. Then I'll look into what needs to be done for getting the tabs working as a separate issue. :)

**Comment by gauravano** [comment]
Sounds great!

**Comment by CoderJolly** [comment]
> So I've identified the problem - the `asked-tab` and `answered-tab` are both showing at all times even though only one is marked active. I can easily update the CSS to hide the inactive one, but there are further problems:
> 
> 1. The tabs at the top of the page don't work to switch the active group.
> 2. There are no questions in the "answered" section, only in the "asked" section
> 3. The paginator for the "answered" section is displaying for the number of items in "asked" - this may be fixed when the logic for #2 is fixed.
> 
> My question is, do I solve just the initial problem with a pull request and break up the remainder into new issues? Or should I fix all of it together?

Sorry, for replying late but I think @gauravano cleared your doubt.

You can create a PR for the initial problem and the make an issue regarding the remaining !! 😄 😸

**Comment by jywarren** [comment]
Fixed in #8689 ! Thank you!!!!
