### ISSUE TITLE
Turn off redis dependency in development mode

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#6389]
Right now in development mode we get a redis error on certain actions. The one I got today was `Redis::CannotConnectError in AdminController#publish`
It would be great if we could turn off the dependency in development!

![FireShot Capture 001 - Action Controller_ Exception caught - localhost](https://user-images.githubusercontent.com/49460529/66176002-f9c51080-e629-11e9-8d1a-0dd6bea10041.png)

**Comment by mathyoudawson** [comment]
Currently action cable is dependent on Redis. I believe you can use different adaptors but making the application less prod-like in development sounds risky.

You can run this locally after installing redis by running `bundle exec sidekiq`
On mac you can use brew to install redis through `brew install redis`, then run `brew services start redis`.

After Redis is running locally run sidekiq `bundle exec sidekiq`.

People have bought this up before #2779

**Comment by jywarren** [comment]
Thank you for the clarification and the link to #2779!

Is this reflected in the Readme? If not, perhaps we could do that, and then
close this up?

Another option is to research a "mock" redis, which could allow running
locally while not needing to install Redis, but it depends on the balance
of how easy it is to install for newcomers vs. how useful it is in
development. Thanks!!!
