### ISSUE TITLE
Old photo uploaded to publiclab.org missing

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/plots2#639]
I'm editing the [PET Bottle Rig wiki page](https://publiclab.org/wiki/pet-bottle-rubber-band-rig), and noticed that an image wasn't displaying. It appears to be missing on the server.

The listed image URL is:
https://publiclab.org/sites/default/files/P1050339.jpg

**Comment by icarito** [comment]
Possible pointer to tweak configuration:
http://stackoverflow.com/questions/12848549/error-310-too-many-redirects-with-nginx-rails-3
I'll have a look in production. Thanks.

**Comment by jywarren** [comment]
That's odd. It was uploaded in the old Drupal system, but those files
should be preserved statically. A similar photo in the same directory is
loading fine:
https://publiclab.org/sites/default/files/5392220652_9524633600_o.jpg which
suggests that it's not a configuration issue.

Sebastian, can you do a file system search for "P1050339.jpg" to see if
it's just misfiled? Thanks.

**Comment by icarito** [comment]
I searched for P1050339 in the plots2 server filesystem and did not find it. I checked in archive.publiclab.org to, not found.

**Comment by jywarren** [comment]
Seems like it's been missing for a while -- it's not clear if it was there
in 2013 via the Wayback machine, but some of the other images were. We have
some older copies of the entire site I can look through, though. Sebastian,
do you know what the oldest backup you have is?

**Comment by icarito** [comment]
I found a copy in tycho server at /media/hiro/earth/oldbackup/html/sites/default/files/P1050339.jpg dated Jan 1 2013.

**Comment by jywarren** [comment]
Hmm, is there a safe and tidy way to copy over any missing images in
/sites/default/files/*? Rsync?

**Comment by mathewlippincott** [comment]
found another missing image, this one from Pat Coyle's note:
https://publiclab.org/notes/patcoyle/04-07-2014/using-free-sfm-tools-for-automatic-volume-calculation

the image should be here:
https://i.publiclab.org/system/images/photos/000/003/542/original/ss_of_selected_edges_filled_maybe.tiff

**Comment by gauravano** [comment]
Hey @mathewlippincott @jywarren , any update on this issue? Also, the image mentioned here is .tiff file and is loading but not showing up on the website. Thanks!

**Comment by jywarren** [comment]
I believe we should be able to support this by adding `tiff` and `tif` to
each of these lines:
https://github.com/publiclab/plots2/search?q=dxf&unscoped_q=dxf

**Comment by gauravano** [comment]
@jywarren I was able to upload tiff file but it doesn't show up on the website. See this -https://publiclab.org/notes/gauravano/03-27-2019/testing-tiff

Thanks!

**Comment by cesswairimu** [comment]
Just opened the link provided and the images seem to be loading fine...not sure if this issue was fixed or they re-uploaded...anyway, closing this. feel free to reopen if we are still experiencing the issue. Thanks all
