### ISSUE TITLE
Addition of questions and comments in topic cards in profile page

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#6390]
### Description
We have notes added to the topic cards for that particular tag. We need Questions/comments too. So we need to add this. There are two portions -
- [ ] First we need to add questions and comments in cards
- [ ] Second we need to add the no of questions/comments for that topic in the cards
Similar as notes given below.

![Screenshot from 2019-10-04 12-11-18](https://user-images.githubusercontent.com/26685258/66186609-52cf8b80-e6a0-11e9-828c-0f01d613f982.png)

We have to follow the style draft. Here is the screenshot of the change that is need to be done.
The code of the `question`, `comments` part would be similar to that of `notes` part.
The code of the notes part is already present in the codebase in file [app/views/tag/_profileCard.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/tag/_profileCard.html.erb)

![Screenshot from 2019-10-04 12-28-46](https://user-images.githubusercontent.com/26685258/66187526-93c89f80-e6a2-11e9-8471-2fa221132adb.png)

Thanks !!

**Comment by nstjean** [comment]
Hi, I'd like to work on this. :)
