### ISSUE TITLE
Add link to view question page

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#6393]
The page for viewing a question has text at the top says
[user] is asking a question about [tag-name]
The tag name should be a link to the page that lists all questions under that tag name.

For instance, on this page:
[https://publiclab.org/questions/wmacfarl/09-25-2019/how-can-we-relate-water-quality-sensor-measurements-to-oil-gas-pollution](url)
![FireShot Capture 003 - 🎈 Public Lab_ How can we relate water quality sensor measurements to_ - publiclab org](https://user-images.githubusercontent.com/49460529/66232139-29215f00-e6b6-11e9-93e4-a7e6e51de81e.png)

The words "water quality" should link to this page:
[https://publiclab.org/questions/tag/question:water-quality](url)

This could be a good candidate for a First Timers Only issue.

**Comment by eprotagoras** [comment]
Hi, could I try my hand at this? This would be my first contribution here!
