### ISSUE TITLE
drop down overlap in navigation bar

### ISSUE THREAD

**Issue by moki298** [publiclab/plots2#6395]
The dropdowns in the navigation bar overlaps, check the below screenshot 

![Screen Shot 2019-10-04 at 5 37 30 PM](https://user-images.githubusercontent.com/21165330/66241738-b6bc7900-e6cd-11e9-82e0-c9538434348f.png)

### Steps to recreate:

- Navigate to https://publiclab.org/
- Click on 'Get Involved' in the navigation bar, the relevant dropdown should appear
- Now without clicking anything move the cursor on to the 'About us' tab, another dropdown appears but the first one is still being shown

### Ideal Behavior
Ideally, the first dropdown that appears should disappear or get hidden when the cursor moves to another tab

**Comment by MysticNas** [comment]
Hey, id  like to work on this project as a outreachy applicant. Would it count as a contribution? thank you

**Comment by moki298** [comment]
@MysticNas I don't know much about Outreachy, you should talk with your mentors regarding that, but you are always welcome to make contributions to this repo. Please make a PR and refer this issue if you want to work on this. Thanks.

**Comment by discombobulateme** [comment]
I would love to contribute on that :) can I make a PR?

**Comment by discombobulateme** [comment]
Actually I am a bit lost @moki298 can you give me a little help? That's the first time I'm contributing to a big collaborative project. I forked plots2 and cloned it to my local computer. How do I access this file to work on it? I don't understand the process to tell the community I'm working on it.

**Comment by discombobulateme** [comment]
Hum... and I understand that this is not under plots2, at least I couldn't find the file, could you @MysticNas ?

**Comment by cesswairimu** [comment]
Hi @moki298, I am not able to replicate this, could you please tell me which OS and browser you are using...or just give it a try again and let me know if the bug is still there? Thanks

**Comment by moki298** [comment]
I can still see this happening in my browser. My environment details:
- Chrome Version: 77.0.3865.90
- Mac Version: macOS Sierra 10.12.6

You need to do a left mouse click on 'Get Involved' tab first and then hover your mouse on to 'About us' to recreate this.

**Comment by susanreenesaa** [comment]
i can also see that issue in my browser( using Google Chrome)

**Comment by susanreenesaa** [comment]
i would like to try and solve allocate it to me. Send me the route to the files to edit. thank you

**Comment by cesswairimu** [comment]
Thanks @moki298... @susanreenesaa sure go ahead..The file is https://github.com/publiclab/plots2/blob/master/app/views/layouts/_header.html.erb. Thanks all

**Comment by susanreenesaa** [comment]
okay @cesswairimu . let me give it a try. thanks

**Comment by cesswairimu** [comment]
This was fixed recently I can't seem to find the PR but the bug is fixed. Thanks all. closing this
