### ISSUE TITLE
improve tag subscriptions when tags are added late

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#64]
lots of people dont get notified because note tags were added _after_ posting, either by author or by first readers. 
- 5 (or 20) minute delay on sending the emails? 
- or, record who's gotten a notification for a given node?
  - with Notification table, with uid, nid, timestamp, reason (tid/uid/nid)
- we could get better at suggesting tags, perhaps based on content
- option for daily digests: could solve this with hourly digests? Possible steps for solution in #1119

**Comment by ryzokuken** [comment]
@jywarren Let's think this over. I'd like to work on this if possible.

**Comment by jywarren** [comment]
I think we could run a daily ActionJob queue and see if any tags were
created with more than 5-10 second delay after the original node was
created. If so, we could re-run the notifications. There'd be some
duplicates, but it wouldn't be too bad.

If we do set up a subscription to daily digests, there is another issue for
that already open, and I think someone's starting to plan it out. Best
coordinate. Users would have to be able to unsubscribe, I suppose.

**Comment by ryzokuken** [comment]
@jywarren What's the status on the daily digests?

**Comment by jywarren** [comment]
Merging into #1119 and some of this was completed already too!
