### ISSUE TITLE
Welcoming Hack October Fest participants to Public Lab

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#6412]
Public Lab is delighted to organize Hack October Fest 2019 in all the repositories of Public Lab. 
Public Lab is a collaborative organiz.ation. 🤝 We at Public Lab, believe in making relationships with people by creating a friendly and generous atmosphere ❤️  
This is the first time Public Lab is participating in Hack October Fest. So, Public Lab is eagerly searching for contributors 

# Hack October Fest ?? 🤔 

**Hacktoberfest**® is open to everyone in our global community. Whether you’re a developer, student learning to code, event host, or the company of any size, you can help drive the growth of open source and make positive contributions to an ever-growing community. All backgrounds and skill levels are encouraged to complete the challenge.

### Eligibility Criterion
Hacktoberfest is open to everyone in our global community!

### What should participants do?
Pull requests can be made in any GitHub-hosted repositories/projects.

### How to participate?
Sign up anytime between October 1 and October 31.

### Rules
To qualify for the official limited edition Hacktoberfest shirt, you must register and make four pull requests (PRs) between October 1-31 (in any time zone). PRs can be made to any public repo on GitHub, not only the ones with issues labeled Hacktoberfest. If a maintainer reports your pull request as spam or behavior, not in line with the project’s code of conduct, you will be ineligible to participate. This year, the first 50,000 participants who successfully complete the challenge will earn a T-shirt.

Refer here[https://hacktoberfest.digitalocean.com/] for more information

**Comment by nstjean** [comment]
Fun!!

**Comment by Anjalizi** [comment]
@gauravano @SidharthBansal when will applications for google code in mentors be open?

**Comment by SidharthBansal** [comment]
They are open

**Comment by Anjalizi** [comment]
how can I apply to become one?

**Comment by SidharthBansal** [comment]
Just solve any 3 issues.
You can start with FTOs

**Comment by Anjalizi** [comment]
I have solved 2 issues in the past namely #5025 and #5012. will it be acceptable if I just solve a third one?

**Comment by SidharthBansal** [comment]
Just ensure them to be in October month.
Date of raising all prs should be Oct.

**Comment by megha070** [comment]
@SidharthBansal can you please assign me some FTO issue?
