### ISSUE TITLE
Update color on hover of flag button on questions page

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#6413]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [/app/assets/stylesheets/dashboard.css](https://github.com/publiclab/plots2/blob/master/app/assets/stylesheets/dashboard.css) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

This is what the hover button currently looks like on the questions page:
![Question Flag Hover - before](https://user-images.githubusercontent.com/49460529/66334238-9f1c0500-e906-11e9-89d4-6f74409d9c1c.jpg)

This is what it should look like:
![Question Flag Hover - after](https://user-images.githubusercontent.com/49460529/66334250-a511e600-e906-11e9-989c-4f8b7a11bcc3.jpg)

On line 340 where it says this:
`.note .meta a:hover i {
  color: #666;
}'

Replace that with this code:
`.note .meta a i {
  transition: color .15s ease-in-out,
    background-color .15s ease-in-out,
    border-color .15s ease-in-out,
    box-shadow .15s ease-in-out;
}

.note .meta a:hover i {
  color: #FFF2CC;
  background: #666;
}`

![Question Flag Hover - Diff](https://user-images.githubusercontent.com/49460529/66334204-8e6b8f00-e906-11e9-8d5f-f8e6c0ad9adc.jpg)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by susanreenesaa** [comment]
hello, can you assign this to me, please?
I am a first-time outreachy applicant

**Comment by nstjean** [comment]
Go for it @susanreenesaa ! Let me know if you have any trouble.

**Comment by susanreenesaa** [comment]
thank you. although I am still having challenges installing the application dependencies on my computer

**Comment by chidexebere** [comment]
Hello @susanreenesaa are you still having issues? I am available to help

**Comment by susanreenesaa** [comment]
yes @chidexebere I am still having issues.  on completing to install dependencies. I have posted the issue on the public chat. though no feedback yet.  I am trying to set up the db using  (rake db:setup) command but i keep getting this error (Could not find nokogiri-1.10.4 in any of the sources) even after running `bundle install` to install missing gems.

**Comment by susanreenesaa** [comment]
![image](https://user-images.githubusercontent.com/49034794/66383419-a0603700-e9c5-11e9-9136-9ef0d5ead651.png)

**Comment by briannadeg** [comment]
I would like to do this please

**Comment by susanreenesaa** [comment]
I have finished resolving the error. I am now working on the issue. Thanks for the help

**Comment by susanreenesaa** [comment]
I have created a pull request for the issue
