### ISSUE TITLE
Resolve rubocop lint offenses inside /app/controllers

### ISSUE THREAD

**Issue by moki298** [publiclab/plots2#6417]
Referenced from #6340

To do:
- Use rubocop to resolve the linting errors from the ruby files inside the /app/controllers directory
- Check #6340 for more information

**Comment by kryptocodes** [comment]
I would like to work on this

**Comment by moki298** [comment]
> I would like to work on this

Great @kryptocodes , please go ahead. Refer this issue when you create a PR, let me know if you need some help. Thanks.

**Comment by bbborisk** [comment]
Hello! Could i contribute as well?

**Comment by moki298** [comment]
@bbborisk sure go ahead and create a PR.
