### ISSUE TITLE
Tag page needs cleaning up

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#6420]
I would really like to clean up [https://publiclab.org/questions/tag/question:general](url) but I want to make sure I know what the intention is! Once I get some direction I will handle this issue.

First I noticed that the Asked/Answered buttons at the top don't work - are they supposed to function the same as the "Recently Asked" and "Unanswered" tabs on [http://localhost:3000/questions/unanswered/](url) ? Should they be removed? I am unclear what their purpose is.

Second I saw that the entire look of the page is very different from others on the site. Would it make more sense to have it formatted the same as the questions page?

For instance, questions page looks like this:
![FireShot Capture 008 - 🎈 Public Lab_ Questions and Answers - publiclab org](https://user-images.githubusercontent.com/49460529/66400673-ee6a4000-e9af-11e9-9180-0f7e1cc93e04.png)

But when the tag page looks like this:
![FireShot Capture 009 - 🎈 Public Lab_ question_general - publiclab org](https://user-images.githubusercontent.com/49460529/66400713-fde98900-e9af-11e9-9b00-a3b4d40b3e6c.png)

> What happened just before the problem occurred? Or what problem could this idea solve?

This could give the site a more unified feel.

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/questions/tag/question:general

### What's your PublicLab.org username?

> This can help us diagnose the issue: nstjean

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Closing this now as we've made a ton of progress! Thank you!!
