### ISSUE TITLE
Clarify default ordering on /tag/_____ pages in UI

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6421]
We currently show pages like https://publiclab.org/tag/water-quality with content sorted by revision timestamp, descending, as in this code:

https://github.com/publiclab/plots2/blob/cc10a02951110f0fed4ae9c15da13c7817ae5e40/app/controllers/tag_controller.rb#L95

```ruby
'node_revisions.timestamp DESC'
```

![image](https://user-images.githubusercontent.com/24359/66415966-cb00be80-e9ca-11e9-9758-6749e2b83413.png)

Let's turn "by views" and "by likes" into a dropdown that also includes "by last updated", and show that selected when in the default view. We can use the same logic to decide which to highlight:

https://github.com/publiclab/plots2/blob/cc10a02951110f0fed4ae9c15da13c7817ae5e40/app/controllers/tag_controller.rb#L90-L96

The code for the current display is here:

https://github.com/publiclab/plots2/blob/cc10a02951110f0fed4ae9c15da13c7817ae5e40/app/views/tag/show.html.erb#L57-L61

For reference, here is how the dropdown is formatted on the right side:

https://github.com/publiclab/plots2/blob/cc10a02951110f0fed4ae9c15da13c7817ae5e40/app/views/tag/show/_nav_tabs.html.erb#L5-L12

We'd love help with this one!

**Comment by anthony-zhou** [comment]
I'd be interested in working on this issue. To clarify, does this mean there will be two separate dropdown menus next to each other, one showing showing 'by last updated' by default and the other showing 'by type'?

**Comment by Tlazypanda** [comment]
@jywarren Can I take this up?

**Comment by jywarren** [comment]
OH, that would be super. Thank you!!!
