### ISSUE TITLE
Show "x" to unfollow vs. "unfollow" button depending on page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6424]
We recently made it possible to "unfollow" a topic from a topic card, by pressing the `x` in the upper right corner:

![image](https://user-images.githubusercontent.com/24359/66423096-f4c0e200-e9d8-11e9-863b-8723b76805bc.png)

This replaces the former button labelled `unfollow` (here, in an older screenshot, it says `unsubscribe`):

![image](https://user-images.githubusercontent.com/24359/66422208-45cfd680-e9d7-11e9-97d0-5e9a66d7da09.png)

But topic cards appear in different places. We should have it offer an `unfollow` button on the https://publiclab.org/tags page, but an `x` on the dashboard. We can tell what page we're on by comparing the `params[:action]` and `params[:controller]` variables. For the dashboard it should be controller: `home` and action: `dashboard`, whereas for the /tags page, it should be controller: `tag` and action: `index`. 

The `x` button is here:

https://github.com/publiclab/plots2/blob/cc10a02951110f0fed4ae9c15da13c7817ae5e40/app/views/tag/_topicCard.html.erb#L7-L9

We'd love help with this!

**Comment by danielwheeler1987** [comment]
Howdy, i can help with this?

**Comment by jywarren** [comment]
That would be great, thank you!

**Comment by danielwheeler1987** [comment]
@jywarren I have a PR ready locally... can you grant me permission to push it up? Ty.

**Comment by seabl** [comment]
@jywarren please close this issue as the PR has been merged.

**Comment by jywarren** [comment]
Thanks, just did that! Thanks all!
