### ISSUE TITLE
Resolve rubocop lint offenses inside /app/helpers

### ISSUE THREAD

**Issue by moki298** [publiclab/plots2#6436]
Referenced from #6340

To do:

Use rubocop to resolve the linting errors from the ruby files inside the /app/helpers directory
Check #6340 for more information

**Comment by rojasTob** [comment]
Hi. Can I take this one?

**Comment by moki298** [comment]
@rojasTob this is work in progress here #6442, please check #6509 a similar issue or feel free to work on other available issues of your interest.
