### ISSUE TITLE
Make stats page constistent

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#6440]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!
### Description
@skilfullycurled make the last three parts of this page uniform. Thanks Benjamin :). It would be nice to center the first part of the page a little  so that the page can transition smoothly to the rest of the graph parts.
### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file https://github.com/publiclab/plots2/blob/master/app/views/stats/index.html.erb (press the little pen Icon) and edit the line as shown below. 

Todo:  Change this line https://github.com/publiclab/plots2/blob/master/app/views/stats/index.html.erb#L1 to 
`<div class="col-lg-12 offset-lg-1" style="margin-bottom:20px; margin-left:100px;">`

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by cesswairimu** [comment]
Reserved for @IvetaHron

**Comment by lojosmit** [comment]
Good day @cesswairimu. I am not sure I understand how this works? This is an open issue for all to action? Could you please elaborat?
if possible could you please review change and accept?

**Comment by cesswairimu** [comment]
Hello @lojosmit, sorry..we are having folks who are applying for Outreachy  and they have a deadline to beat so they ask here #6206 for a first-timer issue do that they can get started on the repo and have an equal chance. So we are creating issues specifically for them as they ask for one.

**Comment by cesswairimu** [comment]
But since you already worked on it its fine I will try and create another issue for @IvetaHron. No worries. Thanks @lojosmit

**Comment by lojosmit** [comment]
Apologies. I guess I should have asked first. I just got excited to see an issue which was not taken yet. But Thanks for allowing me to contribute.

**Comment by lojosmit** [comment]
@cesswairimu Could you please guide me on how to get the pull request into master branch?

**Comment by guptam123** [comment]
Hey, @cesswairimu can I work on the issue?

**Comment by cesswairimu** [comment]
Hi @guptam123, @lojosmit is working on this

**Comment by cesswairimu** [comment]
@lojosmit, there was a checkbox on opening a PR, I guess you deleted it...I will add it back on your Pull request for you and you can follow the steps as described...fell free to ping me if by any chance you need more clarity. Thanks

**Comment by guptam123** [comment]
@cesswairimu I'm sorry, I have made a PR. Should I close the PR?

**Comment by cesswairimu** [comment]
yes please @guptam123 , there is another PR of the same fix. Please look for another issue u an't find one ping me...Thanks
