### ISSUE TITLE
Add cache-busting string to comment moderation action

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6444]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file shown below as described

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

When you moderate a comment, it redirects you back to where you were -- often the page upon which the comment was made. But, because of browser caching, you often still see the comment there. We need to introduce some random characters at the end of the URL in order to force the browser to actually refresh the page, and show it with the comment removed. 

Here's an example of adding a timestamp to the end of a URL in order to break the cache:

https://github.com/publiclab/plots2/blob/a0861eb62c70e819f7b4804a5608c8e7d13c6530/app/controllers/admin_controller.rb#L32

See how where we currently do the redirect, we don't add such extra characters:

https://github.com/publiclab/plots2/blob/a0861eb62c70e819f7b4804a5608c8e7d13c6530/app/controllers/admin_controller.rb#L154

According to [this blog](https://blog.bigbinary.com/2016/02/29/rails-5-improves-redirect_to_back-with-redirect-back.html), in `redirect_back`, Rails uses `request.env['HTTP_REFERER']` to go back where you were before. We're going to have to do this manually because we can't insert the cache-busting characters using `redirect_back`.

So it'd be like this:

```ruby
back_url = request.env['HTTP_REFERER'] || root_path
redirect_to back_url + '?_=' + Time.now.to_i.to_s
```

We'd love help making this change! Just note that it may require a test change as well, but we can help you with that if any tests fail and modifications are needed. Thanks!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by jywarren** [comment]
This is for @vishakhanihore ! Than you!

**Comment by klaffert** [comment]
@jywarren Is this being worked on? Thanks!

**Comment by jywarren** [comment]
It doesn't look like it - we'd love your help! Thanks!

**Comment by jywarren** [comment]
Oops, closed by accident! 😄

**Comment by Ugtan** [comment]
Looks like @klaffert already submitted a PR for a FTO issues. So, can I work on the issue? Thanks @jywarren

**Comment by SidharthBansal** [comment]
Hello, you have already done a First timer issue. So, you can help us with other issues. Thanks for your help!

**Comment by SidharthBansal** [comment]
Published on GCI dashboard

**Comment by pianeta051** [comment]
Is anyone working on this?
may i take this issue?

**Comment by jywarren** [comment]
We'd love help with it if nobody is actively working on it! Thanks!

**Comment by Srija616** [comment]
@jywarren Can I work on this issue as an Outreachy applicant?

**Comment by Alexjake660** [comment]
@SidharthBansal Can I work on this as my first issue?

**Comment by jywarren** [comment]
Hi, i'm sorry, but @Alexjake660 or @Srija616 yes please go ahead! We definitely would like help with this.

**Comment by Alexjake660** [comment]
@jywarren thanks

**Comment by jaibhavaya** [comment]
What is the status of this?  I'd like to work on it if no one else is. :)

**Comment by Alexjake660** [comment]
I am working on this.

**Comment by Alexjake660** [comment]
@SidharthBansal this has already been done.

**Comment by jywarren** [comment]
Hi all! I believe this is still available -- see how the line here is still as it was before? 

https://github.com/publiclab/plots2/blob/a0861eb62c70e819f7b4804a5608c8e7d13c6530/app/controllers/admin_controller.rb#L154

We can change it following the instructions at top; we'd love some help!

**Comment by carrimaxx** [comment]
Working on this, thanks @avats-dev!

**Comment by carrimaxx** [comment]
@avats-dev I may need a little help. I have successfully forked and cloned the repo. I did the following to make sure my copy of the repo is updated: **git remote add upstream git@github.com:publiclab/plots2.git**, then **git fetch upstream**.   However, while trying to execute the **git fetch upstream** command, I get this error:

```$ git fetch upstream
The authenticity of host 'github.com (140.82.113.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? no
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.```

I have looked it up and tried generating and adding my Github ssh keys before I cloned it. Then tried changing my laptop's windows credentials following instructions from [this post](https://stackoverflow.com/questions/51424051/git-clone-authentication-failed-for-url) to no avail. Is there something I am missing?

**Comment by carrimaxx** [comment]
Hello, @avats-dev and @jywarren!
I was assigned this and tried using Gitpod to try and fix this issue, however when I examined line 154 (it is on line 164 now), it doesn't say `redirect_back(fallback_location: root_path) ` anymore, but instead was changed to `redirect_to @comment.node.path + '?_=' + Time.now.to_i.to_s `.
I admittedly can not tell if this is a good alternative to the `request.env['HTTP_REFERER']` because I have no knowledge of Ruby (I know JavaScript), should I change line 164 still (to `back_url = request.env['HTTP_REFERER'] || root_path
redirect_to back_url + '?_=' + Time.now.to_i.to_s`)?

**Comment by jywarren** [comment]
Hi, @carrimaxx - i'm so sorry for the slow reply; i believe that means this was already completed, and I'm sorry about that. If you're still interested in taking on a first-timers-only issue, there is now one at #8789 which you're welcome to claim! My apologies and thank you for your help!
