### ISSUE TITLE
update dashboard.css by removing the empty rulesets

### ISSUE THREAD

**Issue by susanreenesaa** [publiclab/plots2#6454]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

**Steps to fixe the issue**
navigate to 
plots2/app/assets/stylesheet/dashboard.css in the public lab projects directory.
![image](https://user-images.githubusercontent.com/49034794/66711323-39120080-ed92-11e9-9225-ad00f75b9b63.png)
Remove the CSS code on lines 219,220,2021 (remove lines 2019 to 2021)
**NOTE**
After removing the empty rulesets the error highlighted at the bottom of the page should disappear
**The error is Don't use empty rulesets ...** so it should show **no problems have been detected in the workspace so far**.
![image](https://user-images.githubusercontent.com/49034794/66711608-b68c3f80-ed97-11e9-89be-d321611ddcab.png)
**Expected result** 
![image](https://user-images.githubusercontent.com/49034794/66711584-4da4c780-ed97-11e9-91d4-ed43a77676c2.png)
- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by steric85** [comment]
Hello @susanreenesaa 
I am interested in this issue. Can I claim it?

**Comment by steric85** [comment]
@susanreenesaa Please review https://github.com/publiclab/plots2/pull/6455 :)

**Comment by susanreenesaa** [comment]
@steric85. Sorry for the delay. I don't have the right to merge your pull request. but if you are an outrechy applicant, you can ask your mentor to make a pull request or ask on the public channel.
@ishaGupta already reviewed your pull request so if you can access the merge button, click it to merge your request. if not ask for help as I suggested above. thanks

**Comment by steric85** [comment]
@susanreenesaa Thanks for the response.
I don't have the access to merge. Also, I am not an outrechy applicant.
@IshaGupta18 Can you please help here?

**Comment by IshaGupta18** [comment]
I am so sorry I missed this mail, hope this is resolved now? Feel free to
text me on Gitter for help too!
