### ISSUE TITLE
error on starting new question with punctuation in title

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#647]
### What happened just before the problem occurred

@ananyo2012 - I typed "How do i ..." and pressed enter on /questions
### Relevant URLs

https://publiclab.org/questions_search/How%20do%20I%20...

Can you check that out? Maybe write a test for it, too? Thanks!

**Comment by ananyo2012** [comment]
@jywarren This seems to be a general issue with the search query. The search box in the navbar also shows similar behaviour. Trying to fix this.

**Comment by jywarren** [comment]
Just checking if you've made progress with this or if I can help out. Thanks!

**Comment by ananyo2012** [comment]
This one too. Will be responding to this soon.
ᐧ

**Comment by ananyo2012** [comment]
Well found the problem. Rails by default doesn't allow dots in dynamic segements as mentioned in the blue box here http://guides.rubyonrails.org/routing.html#dynamic-segments. But if we need it in the search  id we can use a regexp like `id: /[^\/]+/` that accepts allcharacters accept slash, referring to the solution given there. @jywarren Do we really need dots in the search term? If we do need it I can proceed with the solution.

**Comment by jywarren** [comment]
Ah, that makes sense. Can the dots be encoded as [HTML codes](http://www.ascii.cl/htmlcodes.htm)? Hmm, that doesn't seem to work-- a period is `&#46;` but that still doesn't get moved over. 

But actually it seems it doesn't copy over even if the title is "Hello world" -- so maybe there are two issues? Once it copies basic text over, then we could try the HTML code to get periods to copy over too...

**Comment by ananyo2012** [comment]
@jywarren I couldn't get your last point. Do you mean punctuation marks in title do not come up to the url?

**Comment by jywarren** [comment]
Sorry, the sequence is:

1. I typed `Hello world` on https://publiclab.org/questions (pls try this on local, not live server)
2. Press enter
3. The title text input only says "Question:"

Shouldn't it include the text "Hello world" -- since that was the text of my question?

Thanks!

**Comment by ananyo2012** [comment]
ok that is fixed in issue #791. This issue is specifically for using punctuation marks
