### ISSUE TITLE
Weekly Community Check In 36: Create a first-timer issue

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#6470]
#### Hi everyone :wave: 

We all at Public Lab :balloon: - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal :dart: . You are also welcome to share fun-fact :smile: , new ideas :bulb: , your learning goals :ballot_box_with_check:.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. :100:

Create a first-timer issue
------------------------------------------------ 
We always have a lot of people coming in to the community. This is because of our friendly nature of welcoming new contributors :smiley: This week, please take a minute and create a fto in your project of choice and match it to a person looking for an fto [here](https://github.com/publiclab/plots2/issues/6206)
 
### Note to Outreachy participants
-----------------------------------------------
Welcome to PublicLab, happy to have you here :smile: 
Please say hi and introduce yourself so that the community and the mentors can get to know you. Ask for help whenever you need it. If you need help finding first-timer issues or guidelines on how to effectively make contributions or basically anything, people are super nice here :wink: 

If you can't find an issue to get started on leave a comment  [here](https://github.com/publiclab/plots2/issues/6206)
  so that we can get an issue for you...please mention you are an outreachy applicant too. 

Great week ahead everyone :balloon: :balloon:

**Comment by cesswairimu** [comment]
@gauravano@milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @shubhscoder @sidntrivedi012@SidharthBansal @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18@CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23@ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors@publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita@publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240@codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers@publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps@subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77
--

**Comment by cesswairimu** [comment]
@ananyaarun @ananya @publiclab-mimi @ananya @hc-barker @starkblaze01 @asquare@pdurbin @HarshKhandeparkar@newbazz @aSquare14 @vaarigupta @alonpeer @aashna27 @harshithpabbati @jesus-montano@cryptoclidus @mohamed-elalem @konolga @gowtham5699@jywarren @ebarry @steviepubliclab @StlMaris123,  @tauhir, @augustozanellato, @nstjean, @stefanosu, @alexido19, @Akashutreja, @fadib, @skai-ste, @mahimahans111, @Lisa-Caton, @pkayres, @JeffOgah, @IvetaHron, @Linda-Ikechukwu, @crisner, @vishakhanihore, @shailzaa, @saivoleti17, @chrisnorwood, @DanielKlys7, @Diegoafv, @saramace, @lojosmit, @kyebrowning, @jon-flores

**Comment by vaibhavmatta** [comment]
Hello all.! 
I am Contributing since 1.5 months at Publiclab Image Sequencer. 
Right now I am working on New modules i.e. 
1. Sharpen Image Module
2. Radial Blur Module
3. Cartoonify Image Module
Simultaneously, I am studying about Plots2 as well and planning to start Contributing in this project as well. 

Goals for this week : 
1. Make PR for atleast two modules I am working on.
2. Find out more bugs in Front End of Image Sequencer and open isses for them.
3. Start Contributing for Plots2.
4. Helping all the new contributors

Please tell if something else is also expected from me.
Thank you 🙂

**Comment by SidharthBansal** [comment]
Vaibhav it's really nice to see your enthu for GCI. I really appreciate the work you are doing as Image Sequencer 
You can fill the form with details. 
It will be really great if you can open up as many ftos as you can for GCI and general public.
We want 150+ unsolved ftos asap. Ftos can be in any pl repo.

**Comment by vaibhavmatta** [comment]
@SidharthBansal 
Alright, I should focus on Making FTO issues now. I've already made a list for all the new ftos I observed while working on Project. 
I am filling the form and I think I should not solve any first timer only issue in order to clear mentor requirements and I should only focus on Completing the target of 150+ new ftos. 
Please add me to Mentor's Group.

email : er.vaibhavmatta@gmail.com

that

**Comment by SidharthBansal** [comment]
Please fill the mentorship form. Will add you soon.

**Comment by vaibhavmatta** [comment]
Alright.! Should I write NULL in the place of 'First time issue solved' and 'Help Wanted Issue solved' because I think it is for the new members applying for Mentorship ryt?

**Comment by SidharthBansal** [comment]
You have to tell the link to the prs.

**Comment by pydevsg** [comment]
> Right now I am working on New modules i.e.
> 
> 1. Sharpen Image Module
> 2. Radial Blur Module
> 3. Cartoonify Image Module
>    Simultaneously, I am studying about Plots2 as well and planning to start Contributing in this project as well.
> 
> Goals for this week :
> 
> 1. Make PR for atleast two modules I am working on.
> 2. Find out more bugs in Front End of Image Sequencer and open isses for them.
> 3. Start Contributing for Plots2.
> 4. Helping all the new contributors
 
Great @vaibhavmatta , I was going through image-sequencer and will soon contribute with you in this project. I will look upon few modules and will create some ftos in  it.

**Comment by vaibhavmatta** [comment]
@pydevsg Sure Mate.! We really need contributors in Image Sequencer. Have a look on its readme.md and Contributing document. Study about image processing algorithms on net. Feel free to DM me on Gitter or Tag me anytime you need help. I will send you some links which can help you alot.

**Comment by nstjean** [comment]
Hi! I'm really happy to be here! So far I've opened two FTO issues. Right now what I'm working on are these two PRs: https://github.com/publiclab/plots2/pull/6422 and https://github.com/publiclab/plots2/pull/6472 . It's been a good challenge for me, and I've learned a lot about Rails, system tests, and ActiveRecord queries. I do need some info before I can move forward with them, however. Hopefully someone can confirm that I'm doing things the right way. :)

**Comment by vaibhavmatta** [comment]
@nstjean it's really nice. You are on the right path. Just a tip for you, Focus on Quality Contributions over Quantity Contributions. 

Please open as many fto issues as you can.

Rest, you can ping me up on gitter or tag me up wherever you feel stuck. 
Happy Coding.!

**Comment by pydevsg** [comment]
Sure @vaibhavmatta :+1:

**Comment by stefanosu** [comment]
Hi, all is it possible to work on more than one issue at a time? If so I would like to work on another issue thank you very much.

**Comment by pydevsg** [comment]
Ask the issue creator and reviewers to review your first issue @stefannibrasil , if its alright then you can work on the second.

**Comment by SidharthBansal** [comment]
If Stefanos is done with the issue and it is not yet reviewed. Then however
you can take second issue.
Thanks

**Comment by IvetaHron** [comment]
Hello everyone! My name is Iveta and I am Outreachy applicant too. I am very happy to be here and I would like to contribute to the project as much as I can. It is my first time ever contributing to the project, so it feels confusing a little bit, but community here is amazing and very supportive. I have made my first PR and I am looking forward to work on this project more.

**Comment by pydevsg** [comment]
> Oh ok, cool thanks can I be assigned a new issue?

I will reference here or comment on some issues to help you till then go through `first-timers-issues` and  `help wanted` issues. @stefanosu :)

**Comment by pydevsg** [comment]
> Hello everyone! My name is Iveta and I am Outreachy applicant too. I am very happy to be here and I would like to contribute to the project as much as I can. It is my first time ever contributing to the project, so it feels confusing a little bit, but community here is amazing and very supportive. I have made my first PR and I am looking forward to work on this project more.

Great @IvetaHron . Feel free to ask questions when you need to me as well as in the gitter channel.

**Comment by cesswairimu** [comment]
Thanks all for the awesome work you are doing :tada: 
#### A note to the Outreachy applicants
Remember to also record your contributions on the Outreachy website too...I know most of you have already worked on a first-timer issue, If you need more explanation on a second issue that you have identified feel free to ping the author or any of the mentors so we can support you as much as possible and get the most out of the contribution phase...You can also start drafting your final application [here](https://publiclab.org/notes/gauravano/03-12-2019/call-for-outreachy-2019-proposals) so that you can get feedback and improve your application it before you post it on the Outreachy website..

#### To everyone
If you are interested on opening the next community check-in feel leave a comment below.

Thanks all :heart:

**Comment by aman-k334** [comment]
Hey,I also wanted to contribute to FTO issues. Can I get assigned to any open FTO Please.

**Comment by vaibhavmatta** [comment]
@aman-k334 We would love to have your Contributions. You can pick up any FTO issue and ask if anyone is already working on it. If no one else claimed that issue, just put a comment that you want to claim it and start working on the issue. 
Thanks 😊

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/image-sequencer/issues/1280. Thanks all
