### ISSUE TITLE
Remove hard redirect from /wiki/games

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#6473]
### Please describe the problem (or idea)

I was attempting to create a lead wiki page for https://publiclab.org/tag/games. The "Learn More" button should lead to https://publiclab.org/wiki/games but instead it goes to the page https://publiclab.org/getting-started . This is strange behavior. 

> The issue:

Please figure out what is causing the hard redirect from https://publiclab.org/wiki/games to https://publiclab.org/getting-started and remove it. I would do this myself as a site admin with control over powertags, except this redirect seems not to be generated from a power tag. 

Thank you!

**Comment by AdityaShD** [comment]
Hello @ebarry , Can i work on this issue?
Thanks

**Comment by AdityaShD** [comment]
Can someone assign me the issue please:)

**Comment by ebarry** [comment]
Yes! please go ahead with this if you do not have another one, thank you! cc @cesswairimu

**Comment by cesswairimu** [comment]
Hey @AdityaShD , would be interested in editing this to become a first-timer-only issue and assign to one of the folks looking for a new issue? just wondering or you can go ahead and solve it, whatever you prefer.Thanks @ebarry and @AdityaShD

**Comment by AdityaShD** [comment]
Hey @cesswairimu , Can I add steps for solving the issue for first timers. Would love to do that. 
Thanks.

**Comment by cesswairimu** [comment]
That would be great..thanks so much @AdityaShD  just hit the edit button on the description or just add a comment below...here is the template format you can copy from  https://github.com/publiclab/plots2/issues/new?assignees=&labels=first-timers-only&template=--first-timers-only.md&title= . Thanks

**Comment by jywarren** [comment]
I believe this may be a really tough one, perhaps related to a database record. I'm going to look into it and try to resolve it in a console to the production server! Sorry @AdityaShD but we'd love to have your help with another issue. Thanks!
