### ISSUE TITLE
Banned user still showing up as a "top answerer"

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#6476]
### Please describe the problem (or idea)

I was on this page: https://publiclab.org/questions/pataxte/11-14-2018/any-pole-photos-of-community-gardens and saw a profile name in the sidebar that turned out to be a banned user: 

<img width="1182" alt="Screen Shot 2019-10-15 at 2 39 27 PM" src="https://user-images.githubusercontent.com/161439/66859702-ceabbc80-ef59-11e9-9c89-6e0b1e7243ba.png">

> What did you expect to see that you didn't?

I expected to not see any banned users featured on our website. 

### Please show us where to look

https://publiclab.org/questions/pataxte/11-14-2018/any-pole-photos-of-community-gardens

Thank you for any ideas!

**Comment by simonastefan** [comment]
The banned user also appears in the comments. Should the user comments be removed as well?

**Comment by ebarry** [comment]
Yes, comments by a banned user should be hidden from the site. Thanks @simonastefan !

**Comment by steviepubliclab** [comment]
Hi, wanted to check in on this. What's the status? I'm about to post a similar issue about when a comment is marked as spam, it should also ban the user.

**Comment by jywarren** [comment]
> when a comment is marked as spam, it should also ban the user.

I believe that is already the case.

As for this issue, shall we just remove that section "Top answerers"?

https://github.com/publiclab/plots2/blob/e09dba207359887bc0ce7e233156a3c621f3abbc/app/views/sidebar/_question.html.erb#L17-L25

If so, this can be marked as an FTO. Thanks!

**Comment by priyanka-choubey** [comment]
@jywarren instead of removing the top answerers, we can try checking if the user is banned or not and then while iterating the list we can choose to display names of non-banned users only.. If this sounds okay I would be interested to take it up :)

**Comment by jywarren** [comment]
Sure, that sounds good! Thank you!

**Comment by keshavsethi** [comment]
Is this Issue still open?? 
@priyanka-choubey @jywarren
