### ISSUE TITLE
Change button text color to white

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6481]
![Screenshot_20191016-134205](https://user-images.githubusercontent.com/24359/66944281-e008cd80-f01a-11e9-891d-bfdf1c7c88a5.png)

Here the Follow button in the drop-down has black text but it should be white. Would someone be willing to make this change or to craft a first timers only issue from it?

****
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****
N/B This happening on Mac, safari browser.

**Comment by jywarren** [comment]
The file for this should be in: 

https://github.com/publiclab/plots2/blob/master/app/views/tag/_dropdown_subscribe.html.erb

And it's viewable on pages like: https://publiclab.org/tag/dust

**Comment by phoenixking25** [comment]
@jywarren I want to work on this!

**Comment by IshaGupta18** [comment]
Go ahead!

**Comment by cesswairimu** [comment]
Yeah the text is already white...also on the the live site. Or maybe its support for a different browser? I tried with firefox and chrome

**Comment by phoenixking25** [comment]
@cesswairimu i used firefox. If you also tried it on chrome then it needs to be tested just only for IE and safari. But i am using ubuntu can't do that.

**Comment by debck** [comment]
Yes, I tried with safari and it was black.

**Comment by cesswairimu** [comment]
@debck, would you be interested in fixing this, since some of us cannot replicate?. Thanks

**Comment by debck** [comment]
sorry @cesswairimu But I am a windows OS user. I just checked the error from one of my friends MacOS.

**Comment by cesswairimu** [comment]
Gotcha...no worries thanks for investigating I will update the issue to  include the OS

**Comment by swathi-0901** [comment]
hey, can I work on this issue?

**Comment by sashadev-sky** [comment]
@swathi-0901 this one has a PR open against it (#6725) so it is taken! Are you having trouble finding an issue to work on?

**Comment by swathi-0901** [comment]
Yes

> @swathi-0901 this one has a PR open against it (#6725) so it is taken! Are you having trouble finding an issue to work on?

**Comment by swathi-0901** [comment]
> Yes
> 
> > @swathi-0901 this one has a PR open against it (#6725) so it is taken! Are you having trouble finding an issue to work on?

can u help out?

**Comment by sashadev-sky** [comment]
@swathi-0901 yes - I will make you one shortly and tag you in it :)

**Comment by sashadev-sky** [comment]
just tagged you in #6797 !

**Comment by Kirti2502** [comment]
Can I take up this issue?

**Comment by sashadev-sky** [comment]
closing this as it has since been updated! @jywarren I think the page you linked might be cached (if possible?) because I saw the error initially when opening it.

![image](https://user-images.githubusercontent.com/41092741/79178780-21184980-7dd4-11ea-9410-0b5d0aa62b8a.png)

**Comment by sashadev-sky** [comment]
sorry nevermind it just only appears when the user is logged out -- ill write up an FTO for it

**Comment by sashadev-sky** [comment]
ok closing this its reopened as an FTO in #7813
