### ISSUE TITLE
Fix users page dropdown alignment

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#6486]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [list.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/users/list.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Here is the code section we're going to be editing:

https://github.com/publiclab/plots2/blob/dbb9eb43300c13ee5d17a6f291670d6d71e4b3db/app/views/users/list.html.erb#L39-L53

On small screen sizes this is what happens:
![FireShot Capture 013 - 🎈 Public Lab_ List - localhost](https://user-images.githubusercontent.com/49460529/67025391-f1fa7700-f0d3-11e9-92eb-8fe82b0ec117.png)

We need to add some divs to wrap it with a bootstrap flexbox for alignment. Change the above code to this:

```
<div class="d-flex justify-content-between">
  <div>
    <a href="/profile/<%= user.username %>"><%= user.username %></a>
  </div>
  <div>
    <a class="ellipsis" data-toggle="dropdown">&nbsp<i class="fa fa-ellipsis-h" style="color: #666; font-size:15px;"></i></a>
    <ul class="dropdown-menu dropdown-menu-right" style="font-size:10px;">
      <li><a style="color: #808080; cursor: no-drop;">Joined <%= distance_of_time_in_words(user.created_at, Time.current, { include_seconds: false, scope: 'datetime.time_ago_in_words' }) %></a></li>
      <li><a href='/notes/author/<%= user.name %>'><%= user.note_count %> Research Notes</a></li>
      <li><a style="color: #808080; cursor: no-drop;"><%= user.nodes.count %> Wiki Edits</a></li>
      <li><a href="/profile/<%= user.username %>">See Full Profile</a></li>
      <% if current_user && (current_user.role == "admin" || current_user.role == "moderator") %>
        <% if user.status == 0 %>
          <i class='fa fa-ban' style="color:#a00;"></i> <%= t('users.list.banned') %>
          <% elsif user.status == 1 %>
            <li><a data-confirm="<%= t('users.list.are_you_sure') %>" href="/ban/<%= user.uid %>" ><i class='fa fa-ban'></i> <%= t('users.list.ban') %></a></li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>
```

This is what it should look like on the screen!
![FireShot Capture 014 - 🎈 Public Lab_ List - localhost](https://user-images.githubusercontent.com/49460529/67025422-ff176600-f0d3-11e9-9a23-273fb0be6453.png)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by nstjean** [comment]
Reserved for @saramace

**Comment by saramace** [comment]
Thanks! I will work on this tomorrow night! I look forward to contributing

**Comment by saramace** [comment]
I think I fixed it and it is ready for review. Let me know if I messed up, and I can try and fix it. 

#6492
