### ISSUE TITLE
block display of barnstars awarded by banned users

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/plots2#649]
I recently banned a spammer, user [zonawin:](https://publiclab.org/profile/zonawin)
![screen shot 2016-08-03 at 4 29 20 pm](https://cloud.githubusercontent.com/assets/1203280/17385457/ab2b07ee-5997-11e6-8f52-75f56ffbc010.png)

I found this spammer because they awarded me a Barnstar for [my research note](https://publiclab.org/notes/mathew/07-11-2016/sample-prep-for-passive-particle-monitors).  I was flattered, until I found out they were pushing online casinos :-( 

the note still has a barnstar and my profile. It seems like awarding barnstars is a way to boost the credibility and profile of spam users, and the barnstars should come down.  I can imagine that removing banned users barnstars may not always be the best course of action.  A user may have been a part of a research process and have made good contributions before being banned for inappropriate behavior.  Their research, and maybe their barnstars, should stand. 

Anyways, some thought may be needed on this.

**Comment by jywarren** [comment]
Yeah, I agree it will take some thought. We also see spam accounts just
liking things to drive traffic/links to their profile pages, but without
showing up anywhere else. Maybe need input from @ebarry on this one.

**Comment by jywarren** [comment]
I'm going to suggest we address this as a moderation issue. Thank you!!!
