### ISSUE TITLE
Add links to Contributors and Followers on tags pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6493]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

These texts which appear at the top left of the content area of each tag page (such as https://publiclab.org/tag/water-quality), are great! 

![image](https://user-images.githubusercontent.com/24359/67140230-dd93b700-f258-11e9-9775-0cc0ccaff22f.png)

However, both "contributors" and "following" should link to the corresponding page listing contributors and followers (both can link to the same page): 

https://publiclab.org/contributors/water-quality

Ideally they'd be underlined to indicate they're links, but not be a different color.

And while we are at it, it would be great to change the color of the (?) icon to match!

## Solution

The lines of code to change are here:

https://github.com/publiclab/plots2/blob/dbb9eb43300c13ee5d17a6f291670d6d71e4b3db/app/views/tag/show.html.erb#L57-L58

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org//developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page](https://code.publiclab.org/#r=all)!

**Comment by luksari** [comment]
Hi, can I claim it to contribute to this issue?

**Comment by teemukaaria** [comment]
Hi @jywarren , could I claim this?

**Comment by lucasnogueira** [comment]
Hi @teemukaaria, did you start to work on it already? I had but I forgot to comment here LOL. If you have already no worries though, I will grab another one :)

**Comment by teemukaaria** [comment]
@lucasnogueira Yeah, I kind of already started working on this, but if you already have the complete solution just go ahead and make a pull request.

**Comment by Sanatan-Shrivastava** [comment]
Hi @jywarren , I am interested in fixing this, please acknowledge me with the links to followers and contributors page.
Is this the correct link to followers page?
Link: https://publiclab.org/contributors/followers
