### ISSUE TITLE
adding dropDown arrow on Nav dropdown links

### ISSUE THREAD

**Issue by susanreenesaa** [publiclab/plots2#6496]
continuation of pull request #6395
**FOCUS AT THE PUBLICLAB NAVBAR **
**mainly at Get Involved** and **About Us  page links** 
currently, the webpage at http://localhost:3000 or https://publiclab.org/  looks like below
![image](https://user-images.githubusercontent.com/49034794/67144241-5d337d00-f27d-11e9-9984-052b4dbeb5f9.png)
But it would be great if the viewer is to be able to know that the navbar links of **Get Involved** and **About Us** are **dropdown menus**. Therefore you are required to add **an arrow pointing down**(dropdown-arrow). The dropdown-arrow must be after each of the words **Get Involved** and **About Us**.  like in the image below 
![image](https://user-images.githubusercontent.com/49034794/67144253-74726a80-f27d-11e9-9c37-114912584367.png)

**file path to edit** app/views/layouts/_header.html.erb
**curent code to edit** on **line 29_31** and **line 49_51** 
 **line 29_31** 
``` <
29. <a class="nav-link " data-toggle="dropdown" href="#" >
30.          Get Involved
31.    </a> 
``` 
**image for line 49_51**
![image](https://user-images.githubusercontent.com/49034794/67144596-acc77800-f280-11e9-8f82-d33cb0dab1a2.png)
 *expected*
``` 
29.<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" >
30.           Get Involved
31.         </a>
```
```       
49       <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">
50           <%= t('layout._header.about.about_title') %>
51         </a>
```

So in the   **<a / >** in the **class**  after **nav-link** add the word  **dropdown-toggle** as shown above in order to add the dropdown-arrow.

**Comment by auralshin** [comment]
I want to take this

**Comment by susanreenesaa** [comment]
@auralshin. this is a first-timer only issue. so if u have solved other first-timer issues before, you may leave it for a first-timer on the publiclab platform. but if you would like to take it, I dont have the right to assign it to you so copy the URL and ask in the group chat for someone to assign it to you. thanks

**Comment by susanreenesaa** [comment]
hello @auralshin. ask anyone in the group chat to help you review the issue so that you can merge it

**Comment by sssash18** [comment]
@publiclab/reviewers  Can I work on this issue?

**Comment by cesswairimu** [comment]
mmh :thinking: I am not so sure about this issue..because we currently have the links appear on hover..would adding a drop down assume a button click?

**Comment by cesswairimu** [comment]
cc @publiclab/designers

**Comment by sssash18** [comment]
But I think to let the users know that it's a drop down, it's necessary

**Comment by sashadev-sky** [comment]
closing this as its stale and the updated version is re-opened in #7632
