### ISSUE TITLE
Inactive fa fa-eye icon on login page and popup screen

### ISSUE THREAD

**Issue by susanreenesaa** [publiclab/plots2#6511]
The fa fa-eye icon on both the login page and popup screen is inactive( it doesn't not show any effect when clicked nor does it show the password)
**url** 
http://localhost:3000/login# and http://localhost:3000/login
or 
https://publiclab.org/login and https://publiclab.org/login#
![image](https://user-images.githubusercontent.com/49034794/67241290-d4266c80-f45b-11e9-8e8c-d40e6574d248.png)
![image](https://user-images.githubusercontent.com/49034794/67241643-76465480-f45c-11e9-8f9c-53aba7dfb35c.png)

**expected**
to show the user password when clicked

**Comment by mehnazyunus** [comment]
Hi, I'd like to claim this issue

**Comment by nstjean** [comment]
@mehnazyunus Great! Let us know if you need help!

**Comment by susanreenesaa** [comment]
@try to follow the links that I put above because there may be different models with the login fa fa-eye but this issue I only checked on those url's 
http://localhost:3000/login# and http://localhost:3000/login
or
https://publiclab.org/login and https://publiclab.org/login#. 
if it's okay, may @nstjean  and @vaibhavgeek  can help me verify that because on my side they are inactive

**Comment by susanreenesaa** [comment]
please the issue is on the stated URl. this url (http://0.0.0.0:3000/) is different so it has no issue

**Comment by nstjean** [comment]
I am using Chrome on Linux and the fa-eye button isn't working on localhost:3000/login
When I click the Login button it seems to depend what page I'm on when I click on it. If I'm on the main page of localhost:3000 it works as intended, but not if I'm on localhost:3000/login when I click on the Login button.

On publiclab.org I have the same results.

**Comment by mehnazyunus** [comment]
What I meant was that since both URLs use the same html file, and one works and not the other, am I right in concluding that the issue is not with the html file?
@nstjean any pointers to where I can start hunting for the bug?

**Comment by susanreenesaa** [comment]
@vaibhavmatta  can you please help out @mehnazyunus  to locate the exact file to edit. thanks

**Comment by vaibhavmatta** [comment]
@susanreenesaa I will search for the file once and tell if I  am able to find it or not. Thanks 🙂

**Comment by jywarren** [comment]
I believe it's here! You can use the `needs code links` label also to mark issues that need code links. Thanks all!

https://github.com/publiclab/plots2/blob/13b2355ded7c25b3fe12f871aba1282137c7cf6d/app/views/user_sessions/_form.html.erb#L41-L45

**Comment by vaibhavmatta** [comment]
ThankYou @jywarren

**Comment by sssash18** [comment]
Both the login path form and login popup reference same user_sessions/_form , then why one is working fine while the other one is not?

**Comment by sakshi-2412** [comment]
Hey all! I would like to work on this issue. I think in the login page, the form is also rendering due to the login popup, so it is creating a conflict. The console shows- 

![show password](https://user-images.githubusercontent.com/85152262/147145431-80cf3c7c-c8c8-40ad-86ff-60d145e863d3.png)

We can add a check in views/layouts/_signupLoginModal.html.erb to render the login modal only if the current page is not the login page.

**Comment by sakshi-2412** [comment]
Can I open a PR for the same?

**Comment by TildaDares** [comment]
Hi @sakshi-2412, you can go ahead and open a PR. Feel free to reach out if you need any assistance.
