### ISSUE TITLE
Fix icon hover color on "like" buttons

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#6516]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [_like.html.erb](https://github.com/publiclab/plots2/tree/master/app/views/like) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Just after these lines of code:
https://github.com/publiclab/plots2/blob/d653be356eafa7f6181fb05e2d1e3ac46a2199e5/app/views/like/_like.html.erb#L103-L105

Add this code in:
```
.like-buttons a .fa, .popover .btn-group a .fa {
  color: inherit;
}
```

This is what the drop down looks like before the change:
![FireShot Capture 019 - 🎈 Public Lab_ Anyone working on low cost plants_ - localhost](https://user-images.githubusercontent.com/49460529/67307256-39af4300-f4c6-11e9-97dd-ac4aca5e57f9.png)

And this is what it will look like after!
![FireShot Capture 020 - 🎈 Public Lab_ Anyone working on low cost plants_ - localhost](https://user-images.githubusercontent.com/49460529/67307273-403dba80-f4c6-11e9-8663-d0718dca0f04.png)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by nstjean** [comment]
This is reserved for @textuallyactive

**Comment by sap143** [comment]
I wanted to start my journey in contributing to open source.

**Comment by nstjean** [comment]
Hi @sap143 ! This issue is reserved for someone, but you can add your name to the list here: https://github.com/publiclab/plots2/issues/6206 :) Welcome!

**Comment by sap143** [comment]
Thanks You
Added my name to the list #6206

**Comment by avinash080** [comment]
is this issue open?

**Comment by textuallyactive** [comment]
Thank you. Would do a PR as soon as I get access to a laptop. Cheers!

**Comment by nstjean** [comment]
@avinash080 Sorry, someone is already working on this issue. If you would like to be assigned an issue you can add your name to the list here: https://github.com/publiclab/plots2/issues/6206

**Comment by avinash080** [comment]
@nstjean  ok so plz tell me if there's any issue open . this is my first time on github.

**Comment by nstjean** [comment]
@avinash080 We will let you know in the other thread. :) Thanks for being here and for being patient!

**Comment by krystelufe** [comment]
I am an outreachy applicant . Pls I need a first timer issue to start working on. thanks

**Comment by textuallyactive** [comment]
Done! 
However, I don't know who to tag for reviewing. Thank you for everything again!

**Comment by SidharthBansal** [comment]
@textuallyactive you have to create a PR in plots2 not in your fork!
Best of Luck!

**Comment by dmahajan980** [comment]
@nstjean Can I work on this issue if it's still open?

**Comment by nstjean** [comment]
It looks like this is open @dmahajan980 , go ahead!

**Comment by dmahajan980** [comment]
Thank you @nstjean !! Will make a PR soon.

**Comment by dmahajan980** [comment]
I have made the PR. Kindly review it and let me know if there's any issue.
Thanks
