### ISSUE TITLE
What color should toolbar buttons be?

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#6519]
Currently the toolbar when you are typing a comment looks inconsistent:
![FireShot Capture 025 - 🎈 Public Lab_ Do stinkbugs actually stink_ - localhost](https://user-images.githubusercontent.com/49460529/67311691-0a043900-f4ce-11e9-817c-23b458362bc4.png)

What do you think the color should be? Grey?
![FireShot Capture 023 - 🎈 Public Lab_ Do stinkbugs actually stink_ - localhost](https://user-images.githubusercontent.com/49460529/67311754-21432680-f4ce-11e9-9da9-2cb70fde0953.png)

Or black?
![FireShot Capture 024 - 🎈 Public Lab_ Do stinkbugs actually stink_ - localhost](https://user-images.githubusercontent.com/49460529/67311745-1e483600-f4ce-11e9-8122-9d04b73f3907.png)

Once I get some feedback I'll turn this into a FTO. :)

**Comment by Resolution-1** [comment]
I want to work on this

**Comment by nstjean** [comment]
@Resolution-1 Sure! First let's find out what everyone thinks the color should be. :) It should be able to be corrected with a couple classes in the style.css file.

**Comment by Oscar-Gallardo** [comment]
I believe it should be black as it would contrast better with the background.

**Comment by nstjean** [comment]
@Resolution-1  So I saw that in the wiki posting screen the buttons were all black, so let's go with that to be consistent.

What you need to do is for `.navbar-text` and `.btn-toolbar` you need to set the text color to `#222` and for the hover it needs to be set to white. You can put the css in [style.css](https://github.com/publiclab/plots2/blob/master/app/assets/stylesheets/style.css)

If you need any help please let me know!

**Comment by smarty1palak** [comment]
Is this issue still open? Can i work on it?

**Comment by nstjean** [comment]
This is not corrected yet!

I am not seeing the toolbar show up on comments, but I do see the inconsistent toolbar at https://publiclab.org/wiki/new - following the steps above will fix it. :)

**Comment by smarty1palak** [comment]
Okay i will work on it. Thanks!

**Comment by smarty1palak** [comment]
Hi, I am having trouble finding the code for this . Csn you point me to it @nstjean ? Thanks!

**Comment by smarty1palak** [comment]
Okay nevermind. I got that. Thanks !

**Comment by smarty1palak** [comment]
Hi, I have completed the issue. Can you guide me on the guidelines to be followed for sending a PR @nstjean ?

**Comment by nstjean** [comment]
@smarty1palak Great! What you need to do is push your changes to your own fork on GitHub. Then when you look at [Pull Requests](https://github.com/publiclab/plots2/pulls) in publiclab it will show you a button for "compare and submit pull request". Make sure the base is master on publiclab, and the one you're comparing it to is the branch you created on your own fork.

Here's a guide that has pictures!
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request
