### ISSUE TITLE
Change function t to translations in dashboard/_comment_moderate

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#6551]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [_comment_moderate.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_comment_moderate.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

In this template we need to change the function named `t(....)` to be named as `translations(...)` on lines 4, 5, 6 and 8.

https://github.com/publiclab/plots2/blob/50164b13d612be00c5f700bb302af103a881e63c/app/views/dashboard/_comment_moderate.html.erb#L4-L8

After the changes it should look like this:
```
      <%= translation('dashboard._comment_moderate.first_time_post') %>
      <a class="btn btn-outline-secondary btn-sm" href="/admin/publish_comment/<%= comment.id %>"><%= translation('dashboard.moderate.approve') %></a>
      <a class="btn btn-outline-secondary btn-sm" href="/admin/mark_comment_spam/<%= comment.id %>"><%= translation('dashboard.moderate.spam') %></a>
    <% else %>
      <%= raw translation('dashboard.moderate.pending_approval', :url => '/wiki/moderation') %>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by nstjean** [comment]
Reserved for @saivoleti17

**Comment by jaywahr** [comment]
@nstjean how can I get on a "wait list" to get a `first-timers-only` issue? Thank you.

**Comment by nstjean** [comment]
Hi @jaywahr - our list is located here: https://github.com/publiclab/plots2/issues/6206 Just post and your name will get added to the list! We'll get new issues up soon!

**Comment by cesswairimu** [comment]
@saivoleti17 already have a fto here https://github.com/publiclab/mapknitter/issues/1086 ... @boolean5 you can solve this. Thanks all

**Comment by boolean5** [comment]
Thank you @cesswairimu. I'm on it.

**Comment by boolean5** [comment]
Now I see that @saivoleti17 has already submitted a PR  (#6555) for this issue. I think it would be fair to let them complete their work. Please, let me know if any help is needed.

**Comment by cesswairimu** [comment]
Cool no worries

**Comment by Anand-Theertha** [comment]
Hello! I saw this issue under "No one assigned". Does this mean I can work on it even though it has been reserved for somebody?

**Comment by nstjean** [comment]
Hi @Anand-Theertha ! There is already a pull request for this issue. We'll be making more first-time-only issues!

**Comment by taysa91** [comment]
Hi, 
I am Outreachy candidate and new to open source. Is this issue still open. Can I take it.

**Comment by nstjean** [comment]
@taysa91 You can work on this.

**Comment by taysa91** [comment]
@nstjean Thank you. I did make a contribution but will also like to work on this one. Hope y'all don't mind.

**Comment by nstjean** [comment]
Hi @taysa91 ! We ask that people only do one FTO issue so that others have something to do to start out. If you have completed one already then next you can take a look at the bugs we have that need a little fix: https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3Abug

**Comment by taysa91** [comment]
@nstjean Sure no problem, and thank you.

**Comment by imanishbarnwal** [comment]
Hello, @nstjean if no one is working on this issue. Can I do it? Thank You!!

**Comment by cesswairimu** [comment]
Hi @imanishbarnwal, sure go ahead..Thanks

**Comment by imanishbarnwal** [comment]
Hello, @cesswairimu I just send a PR kindly check that. Thank You!!

**Comment by Cadreia** [comment]
Hi, @cesswairimu I would love to work on this

**Comment by cesswairimu** [comment]
Go ahead @Cadreia, thanks

**Comment by cesswairimu** [comment]
@Cadreia, I see you have you already contributed to a first-timer issue. Would you mind leaving this one to a new contributor? and you could browse through the issues with the label `help-wanted` or `bug`

**Comment by Cadreia** [comment]
@cesswairimu okay, I'll do that. But I just linked a pull request for it. Do I close it?

**Comment by cesswairimu** [comment]
Yeah you could just close it if you are okay with that... thanks a lot 💯

**Comment by Suiiyush** [comment]
Hey If it is not already assigned to anyone can I work on this issue

**Comment by cesswairimu** [comment]
Hi @Suiiyush,  It looks like this has been solved already https://github.com/publiclab/plots2/blob/50164b13d612be00c5f700bb302af103a881e63c/app/views/dashboard/_comment_moderate.html.erb#L4-L8 . Closing this. Thanks everyone.
