### ISSUE TITLE
Remove "moderators@publiclab.org" from mailers in dev mode

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#656]
https://github.com/publiclab/plots2/blob/9cb76917efcff9c2d91ed2e403dc2417cd7c0bb1/app/mailers/admin_mailer.rb#L9

Otherwise running tests can inadvertently email the actual moderators list :-)

We could use a value set at the top of the page using `Rails.env`.

I think we should send to "test@publiclab.org" instead. 

http://api.rubyonrails.org/classes/ActionMailer/Base.html shows how to set a default, but I'm not sure if we can do this in a conditional loop, or set the default based on environment. It bears some looking into, and we will probably have to adjust the functional and unit tests, too:

https://github.com/publiclab/plots2/blob/master/test/functional/admin_controller_test.rb#L155

https://github.com/publiclab/plots2/blob/master/test/unit/admin_mailer_test.rb#L24

**Comment by ananyo2012** [comment]
@jywarren I think this isn't required. Rails smartly handles tests and doesn't send any mails to the real world. Rather all mails are stored as array objects. See these lines in environments/test.rb https://github.com/publiclab/plots2/blob/master/config/environments/test.rb#L27-L30

**Comment by ananyo2012** [comment]
Ok sorry Jeff I thought you were referring mails sent while running Rails tests. You actually meant tests sent during development environment. Should have seen the title of the Issue more clearly. :-)

**Comment by jywarren** [comment]
No problem -- yes, I think this may come up from time to time. Another way to do it would be to use `Rails.root` as the domain name of the email destination. 

Finally, we may want to include "defaults" and "custom settings" for things like the moderators email, in a config.yml file.

**Comment by ananyo2012** [comment]
@jywarren I think the best thing to do is to set the Action Mailer delivery_method to `:file` in development. This way all the mails in development would go to the `tmp/mails` directory. Even a good way to monitor the mails in development environment. I have included the fixes in #659.

**Comment by jywarren** [comment]
Oh great, thanks!

**Comment by jywarren** [comment]
I'm going to close this as it's essentially complete pending confirmation and final merge in #659. Thanks all!
