### ISSUE TITLE
Write functional test for batch spamming notes/authors

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6569]
Here is the Ruby code that finds the corresponding nodes by `nid` and bans their authors AND spams the nodes:

https://github.com/publiclab/plots2/blob/50164b13d612be00c5f700bb302af103a881e63c/app/controllers/admin_controller.rb#L316-L334

We should write a test to confirm the correct users are getting banned. This could be a functional test for the path: `/spam/batch/1,2,3`

It could be based on this functional test:

https://github.com/publiclab/plots2/blob/50164b13d612be00c5f700bb302af103a881e63c/test/functional/admin_controller_test.rb#L64-L70

The test would just confirm that the correct users are getting banned, and the nodes spammed:

https://github.com/publiclab/plots2/blob/50164b13d612be00c5f700bb302af103a881e63c/app/views/admin/_nodes.html.erb#L19-L23

We'd love help with this!

**Comment by SidharthBansal** [comment]
@jywarren can we create some minor projects from the above list as hall of fame tasks for GCI?

**Comment by SidharthBansal** [comment]
If there are 1-2 tests I think we can change it medium tasks

**Comment by jywarren** [comment]
Sure this would be great...

**Comment by SidharthBansal** [comment]
Published

**Comment by Uzay-G** [comment]
Hey @SidharthBansal and @jywarren! I would love to work on this once my other task gets approved. 

Thanks :+1:!

**Comment by Uzay-G** [comment]
Hey! I have been working on this issue and have claimed the tests. I have made two functional tests for now but plan to make more. They are like this:
```ruby
  test 'batch spamming users should ban correct number of users and correct number of nodes' do
    UserSession.create(users(:admin))
    spam_nodes = [nodes(:spam_targeted_page), nodes(:spam)]
    authors = spam_nodes.collect { |node| node.author }
    get :batch, params: { ids: spam_nodes.collect { |node| node["nid"] }.join(",") }
    assert_equal spam_nodes.length.to_s + ' nodes spammed and ' + authors.uniq.length.to_s + ' users banned.', flash[:notice]
    assert_redirected_to "/spam/wiki"
  end

  test 'normal user should not be allowed to batch spam' do
    UserSession.create(users(:bob))
    spam_nodes = [nodes(:spam_targeted_page), nodes(:spam)]
    get :batch, params: { ids: spam_nodes.collect { |node| node["nid"] }.join(",") }
    assert_equal "Only admins can batch moderate.", flash[:error]
    assert_redirected_to "/dashboard"
  end
```

I am trying to make more but have encountered a very bizarre problem with this test which should work normally:
```ruby
  test 'users that have been batch-spammed are banned' do
    spam_nodes = [nodes(:spam_targeted_page), nodes(:question)]
    get :batch, params: { ids: spam_nodes.collect { |node| node["nid"] }.join(",") }
    authors = spam_nodes.collect { |node| node.author } 
    assert authors.all? { |spammer| spammer.status == 0 }
  end
```
It takes two non-spammed notes and spams them and should ban their authors. Unfortunately, the test fails because the authors' status, which should be 0 if they are banned, is still 1. I think maybe the author data is not updating for some reason.
Do I need to run a command to update the test database or something like that?
Thanks @jywarren and @SidharthBansal.

**Comment by Uzay-G** [comment]
I've been trying to understand why but can't find the root of the problem. 
If I batch spam by going on the local server everything works fine but when I do the same from the console or in the testing environment the users aren't banned :confused:. I will keep looking but let me know if you know why this is going on :+1:

**Comment by Uzay-G** [comment]
Alright I finallly found the problem. :+1:

**Comment by SidharthBansal** [comment]
Oh great!
I just saw your message.

**Comment by Uzay-G** [comment]
Hey @SidharthBansal! I've come up with these three functional tests for now:

https://github.com/Uzay-G/plots2/blob/5df11bfdd411cf4eca1243b87b47e89e19d57ddd/test/functional/admin_controller_test.rb#L72-L96

**Comment by Uzay-G** [comment]
Hey @SidharthBansal, do you think I should create a new integration test file for the batch-spamming or leave it in the admin controller?
