### ISSUE TITLE
Replace instances of "publiclab.org" with Rails.root

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#657]
In an effort to make this system more broadly usable by other communities, we should use `Rails.root` or `Rails.root.to_s` instead of any instance of the string `"publiclab.org"` in this codebase. This should be a fairly straightforward find/replace.

**Comment by blakeyoder** [comment]
Mind if I take this one?

**Comment by jywarren** [comment]
Please do! And I'd be happy to answer any questions or offer input, though
this one is pretty simple. Thanks!

**Comment by blakeyoder** [comment]
Awesome - been in Ruby and RoR for about 2 years now. Looking to get involved with an open source project. This will be my first commit to an open source project :)

**Comment by ebarry** [comment]
awesome to hear from you @blakeyoder !

**Comment by jywarren** [comment]
Hi, Blake - just checking if there's any help we can offer. Note that there've been a lot of new commits merged into the code recently so you may need to watch out when rebasing. Thanks again!

**Comment by blakeyoder** [comment]
Jeffrey, thanks for checking in. I got the app working on my local machine the other day and will go through this over the weekend. Been swamped by life lately. Thanks for the heads-up on all the merges

**Comment by jywarren** [comment]
no problem and good luck!

**Comment by jywarren** [comment]
Hi, this was bumped up in priority by @icarito, who needs it to set up test containers for our deployment process; I'm sorry to do it but I've gone ahead and implemented a first pass, in PR #886. Thanks -- we'd love to have your contribution elsewhere, and there are plenty of important issues still at https://github.com/publiclab/plots2/labels/help-wanted.
