### ISSUE TITLE
Clicking the 'follow' button on a tag does not change it to 'unfollow'

### ISSUE THREAD

**Issue by crisner** [publiclab/plots2#6570]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

On clicking the follow button, the button text does not change. Only after the page is refreshed the button changes from 'follow' to 'unfollow'.
![publiclab org_tags_page=2 (1)](https://user-images.githubusercontent.com/29401459/67688341-b1e2a080-f9bf-11e9-8ef8-168c76614be8.png)

> What did you expect to see that you didn't?

I expected the button to show the text 'unfollow' instead of 'follow' when clicked.
![publiclab org_tags_page=2 (2)](https://user-images.githubusercontent.com/29401459/67688358-b909ae80-f9bf-11e9-8a1b-487ebd46415f.png)

### Please show us where to look

https://publiclab.org/tags?page=2

### What's your PublicLab.org username?
christie_reni
> This can help us diagnose the issue: 

### Browser, version, and operating system
Chrome, version 77.0.3865.120 (Official Build) (64-bit),  windows10
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hi, great catch! I think we need to bust the browser cache by inserting a
random number to the redirected-to URL. THis is done in some other
controllers, so it'd be fantastic to add this (using a timestamp to get a
unique URL) like this:

https://github.com/publiclab/plots2/blob/master/app/controllers/subscription_controller.rb#L121

Would you be interested in helping to solve this?

It should be in this function, i think?

https://github.com/publiclab/plots2/blob/master/app/controllers/subscription_controller.rb#L146

https://github.com/publiclab/plots2/blob/master/app/controllers/subscription_controller.rb#L162

Oddly, in that "add" method, it seems we do actually do this. When you see
the page not updated, does it have something like "?_12231415" at the end
of the URL? Maybe we're not catching one case and forgetting to append it
somehow?

**Comment by crisner** [comment]
@jywarren Thanks! Yes, I would like to give this one a try!

> When you see
the page not updated, does it have something like "?_12231415" at the end
of the URL?

No. The URL remains the same as in https://publiclab.org/tags?page=2. Is it supposed to redirect to something like https://publiclab.org/subscriptions?_=1572282692?

**Comment by jywarren** [comment]
Hm. It should go to https://publiclab.org/tags?page=2&_=1572282692
actually. Does this happen the same if you press "follow" from
https://publiclab.org/tags and not from https://publiclab.org/tags?page=2 ?

**Comment by crisner** [comment]
> Hm. It should go to https://publiclab.org/tags?page=2&_=1572282692 actually. Does this happen the same if you press "follow" from https://publiclab.org/tags and not from https://publiclab.org/tags?page=2 ?

Yes. The same happens even from https://publiclab.org/tags. It does not go to the expected URL.

**Comment by crisner** [comment]
I have been tinkering with the code a bit. Looks like we are not sending back any json information here:
https://github.com/publiclab/plots2/blob/3dad8ad6afe62eb4aec5c89ccf94d4d0c09aac26/app/controllers/subscription_controller.rb#L65-L69

that needs to be read here:
https://github.com/publiclab/plots2/blob/3dad8ad6afe62eb4aec5c89ccf94d4d0c09aac26/app/assets/javascripts/async_tag_subscriptions.js#L27-L33

I set the json information and this is how it looks like now:
![localhost_3000_tags](https://user-images.githubusercontent.com/29401459/67751652-827f7280-fa57-11e9-898e-f5f96a8f4fe0.png)

When I refresh the page it is showing the expected 'unfollow' on the button. Should we leave it this way or would it be better to change the text to unfollow instead?

**Comment by crisner** [comment]
@jywarren I have created a pull request with changes made to the code that fixes the issue and have attached some gifs for review. Thanks!
