### ISSUE TITLE
Make the SignUp popup responsive 

### ISSUE THREAD

**Issue by debck** [publiclab/plots2#6572]
#### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

When you open https://publiclab.org/ in your mobile browser and click on the `Sign Up` button from the menu, a pop up modal appears which is not responsive.

![dek](https://user-images.githubusercontent.com/33368759/67696338-b1043b80-f9cc-11e9-9a4e-63a2e4f3783a.jpeg)

> What did you expect to see that you didn't?

The modal should be responsive like the login modal.

### Please show us where to look

https://publiclab.org/ 

### What's your PublicLab.org username?

       debasish_sahoo1998

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by susanreenesaa** [comment]
@debck. hope you are doing good. 
Using google chrome.
I have tried to see this problem on a very small phone. to see the issue, but the signup page is working very well (very responsive). maybe the only issue that I see is that on clicking the signup button, the popup is not obvious because it's only is seen after scrolling down (popup pops up way below the screen). Therefore one can be mistaken that the phone has frozen because of the smoky popup background that is visible before scrolling down to see the popup.
I also tried it out on the smaller screen of the PC. and it works fine. I am using google chrome on all platforms. 
However, when I opened the same page on the phone using opera mini, even the menu could not open.
could the issue be related to the web browser?
@jywarren  and @nstjean, u can also check this out.

**Comment by nstjean** [comment]
@debck What mobile browser are you using, so we can recreate the issue?

**Comment by debck** [comment]
I was using chrome browser in my phone

**Comment by nstjean** [comment]
@susanreenesaa I see what you mean about the sign up popup being located below the screen! The login popup doesn't have the same problem.

@debck Thanks for responding! I'm checking on chrome and not having an issue. Can you check again and see if you're still seeing the problem?

**Comment by debck** [comment]
Yes, I am still finding it. The login popup is working good. But for the
signup modal, it appears little downwards and scrolling it I still see as
in the screenshot above.

**Comment by susanreenesaa** [comment]
@debck. After scrolling to that signup screen, is it responsive when you type in anything?
Because mine is responsive it even verifies the input data and also submits it.

**Comment by debck** [comment]
It isn't responsive but it verifies the input data and also submits it.

**Comment by NitinBhasneria** [comment]
Hey can I make this popup responsive and work on the issue? @debck

**Comment by debck** [comment]
Yes sure @NitinBhasneria

**Comment by NitinBhasneria** [comment]
@debck It seems that when we open in mobile it is some little problem in responsiveness and also some buttons and borders are overlapping in tablet views. Can you please confirm is these are the only problems??

**Comment by NitinBhasneria** [comment]
/home/nitin/Pictures/Screenshot from 2020-01-15 23-12-03.png
/home/nitin/Pictures/Screenshot from 2020-01-15 23-12-08.png
/home/nitin/Pictures/Screenshot from 2020-01-15 23-12-10.png

**Comment by NitinBhasneria** [comment]
![Screenshot from 2020-01-15 23-12-03](https://user-images.githubusercontent.com/44112080/72457498-be231080-37ec-11ea-8ebc-3e19780618e2.png)
![Screenshot from 2020-01-15 23-12-08](https://user-images.githubusercontent.com/44112080/72457499-be231080-37ec-11ea-9cd4-71d3e2a10afe.png)
![Screenshot from 2020-01-15 23-12-10](https://user-images.githubusercontent.com/44112080/72457502-bebba700-37ec-11ea-865d-37a7d29f0885.png)

**Comment by emilyashley** [comment]
Oh good, glad to see this is already open and being worked on! I was about to make an issue when I noticed it on my phone last night. 💯

**Comment by NitinBhasneria** [comment]
In signup popup the responsiveness is little low as the css width is given in px instead of percentage of looks a little less responsive. @jywarren could you please give your view...?
