### ISSUE TITLE
Undefined keyword in the toast/notification popup.

### ISSUE THREAD

**Issue by phoenixking25** [publiclab/plots2#6573]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
* Open the target link without any previous login and click on follow button, so it will pop up the dialog box to ask for new login and at the same moment the toast/notification popup with the text
UndefinedClick here to manage your subscriptions.

### Please show us where to look

https://publiclab.org/tags?page=2 ( without logging in )

![Screenshot from 2019-10-28 23-07-41](https://user-images.githubusercontent.com/22527880/67704754-b7e67a80-f9db-11e9-88e4-79bf7bb8539f.png)

**Comment by priyanka-choubey** [comment]
@jywarren I think we can close this issue because this bug cannot be found anymore. Please check for the same. thanx :)

**Comment by jywarren** [comment]
OK, thank you!
