### ISSUE TITLE
Drop custom template for question listings in favor of standard notes template

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6575]
We have this custom template:

https://github.com/publiclab/plots2/blob/master/app/views/questions/_new_question.html.erb

For pages like this, displaying questions:

https://publiclab.org/tag/question:water-quality

However, we've really refined the regular listings here, visually:

https://publiclab.org/tag/water-quality

So, let's just use the same template, instead of switching. The template at top can be deleted. Then, we can just use this section:

https://github.com/publiclab/plots2/blob/bfe70900de941a78c4fab0c82a128ad46433795e/app/views/tag/show/_tab_content.html.erb#L4-L13

And remove the condition "if type == note"

And then, remove the section that's set up just for questions:

https://github.com/publiclab/plots2/blob/bfe70900de941a78c4fab0c82a128ad46433795e/app/views/tag/show/_tab_content.html.erb#L15-L36

That will simplify the code and make it more maintainable and consistent! We'd love help with this one!

**Comment by shubhankarsharma00** [comment]
I will like to work on this one.

**Comment by jywarren** [comment]
We'd love your help! Actually we're looking to delete the independent
template and to eliminate the conditional which switches questions onto
it's own template. Does that make sense?

>

**Comment by swathi-0901** [comment]
hello, @jywarren can I work on this issue, please? If you assign it to me I shall start working on it thank you :)

**Comment by swathi-0901** [comment]
@jywarren can u help me out to find where I went wrong?

**Comment by sssash18** [comment]
@publiclab/reviewers @jywarren  Can i work on this issue?

**Comment by cesswairimu** [comment]
sorry @swathi-0901, I didn't see your request for help, let me know if you need help finding another issue... @sssash18 sure,  please go ahead

**Comment by KarishmaVanwari** [comment]
Is this issue open? @jywarren

**Comment by KarishmaVanwari** [comment]
@jywarren @TildaDares Can I take up this issue?

**Comment by TildaDares** [comment]
Hi @KarishmaVanwari, we decided to revert back to the normal question template https://github.com/publiclab/plots2/pull/10359. I think we can close this one now.
