### ISSUE TITLE
Change function t to translation in dashboard/_activity

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#6597]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [_activity.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_activity.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

In this template we need to change the function named t(....) to be named as translation(...) on lines 1, 19, 27, 36, 42, 48, 54, 61, 72, and 74.

https://github.com/publiclab/plots2/blob/9027525dbe504db82276e12ec59dfb00c7a45961/app/views/dashboard/_activity.html.erb#L1
change to
```<h3 id="activity-header"><i><%= translation('dashboard._activity.activity') %></i></h3>```

https://github.com/publiclab/plots2/blob/9027525dbe504db82276e12ec59dfb00c7a45961/app/views/dashboard/_activity.html.erb#L19
change to
```<span class="node-type-filter"><%= translation('dashboard._activity.all_updates') %></span>```

https://github.com/publiclab/plots2/blob/9027525dbe504db82276e12ec59dfb00c7a45961/app/views/dashboard/_activity.html.erb#L27
change to
```<%= translation('dashboard._activity.dropdown.all') %>```

https://github.com/publiclab/plots2/blob/9027525dbe504db82276e12ec59dfb00c7a45961/app/views/dashboard/_activity.html.erb#L36
change to
```<%= t('dashboard._activity.dropdown.research_notes') %>```

https://github.com/publiclab/plots2/blob/9027525dbe504db82276e12ec59dfb00c7a45961/app/views/dashboard/_activity.html.erb#L42
change to
```<%= translation('dashboard._activity.dropdown.question') %>```

https://github.com/publiclab/plots2/blob/9027525dbe504db82276e12ec59dfb00c7a45961/app/views/dashboard/_activity.html.erb#L48
change to
```<%= translation('dashboard._activity.dropdown.events') %>```

https://github.com/publiclab/plots2/blob/9027525dbe504db82276e12ec59dfb00c7a45961/app/views/dashboard/_activity.html.erb#L54
change to
```<%= translation('dashboard._activity.dropdown.comments') %>```

https://github.com/publiclab/plots2/blob/9027525dbe504db82276e12ec59dfb00c7a45961/app/views/dashboard/_activity.html.erb#L61
change to
```<%= translation('dashboard._activity.dropdown.wiki') %>```

https://github.com/publiclab/plots2/blob/9027525dbe504db82276e12ec59dfb00c7a45961/app/views/dashboard/_activity.html.erb#L72-L75
on these lines notice that there are 4 instances to change!
```
  <span class="d-none d-md-inline"><%= translation('dashboard._activity.from_other') %> <a href=""><%= translation('dashboard._activity.community_scientists') %></a></span> <%= translation('dashboard._activity.past_week') %>
  <% if current_user %>
    <span class="d-none">| <a href="/profile/<%= current_user.username %>"><%= translation('dashboard._activity.your_work') %></a></span>
  <% end %>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by pravalikavis** [comment]
Hi, I would like to take up this

**Comment by nstjean** [comment]
@pravalikavis Hi, go ahead!

**Comment by nstjean** [comment]
@pravalikavis Are you still working on this?

**Comment by swathi-0901** [comment]
hey, can I work on this issue?

**Comment by nstjean** [comment]
@swathi-0901 I see you've already completed a First Time Only issue. Now that you've done that you can look at https://code.publiclab.org/ (Scroll down to 'What's Next?'). We encourage people to clone our repository and get it working on your local development system. Information is available here: https://github.com/publiclab/plots2/blob/master/README.md

**Comment by swathi-0901** [comment]
> @swathi-0901 I see you've already completed a First Time Only issue. Now that you've done that you can look at https://code.publiclab.org/ (Scroll down to 'What's Next?'). We encourage people to clone our repository and get it working on your local development system. Information is available here: https://github.com/publiclab/plots2/blob/master/README.md

Okay :)

**Comment by mantinone** [comment]
Hey, it looks like this issue is still open.

Can I claim it?

**Comment by nstjean** [comment]
@mantinone Yes go ahead!

**Comment by mantinone** [comment]
Okay, I believe I'm ready for review.

I noted that the lines mentioned in the description didn't match up with the lines in the file, but I'm guessing that might just be an issue with the browser.  The file looks as expected in Atom.

I realized after submitting that I didn't create a branch for this.  I just used the browser edit function.  Should I redo this pull request with a branch?
