### ISSUE TITLE
Change function t to translation in dashboard/_comment_moderate

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#6598]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [_comment_moderate.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_comment_moderate.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

In this template we need to change the function named t(....) to be named as translation(...) on lines 4, 5, 6, and 8.

https://github.com/publiclab/plots2/blob/9027525dbe504db82276e12ec59dfb00c7a45961/app/views/dashboard/_comment_moderate.html.erb#L4-L8
change to:
```
      <%= translation('dashboard._comment_moderate.first_time_post') %>
      <a class="btn btn-outline-secondary btn-sm" href="/admin/publish_comment/<%= comment.id %>"><%= translation('dashboard.moderate.approve') %></a>
      <a class="btn btn-outline-secondary btn-sm" href="/admin/mark_comment_spam/<%= comment.id %>"><%= translation('dashboard.moderate.spam') %></a>
    <% else %>
      <%= raw translation('dashboard.moderate.pending_approval', :url => '/wiki/moderation') %>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by aviveller** [comment]
can i take it?

**Comment by nstjean** [comment]
Go ahead @aviveller !

**Comment by gptshubham595** [comment]
May I take this issue 
as it around  days and not solved

**Comment by nstjean** [comment]
@aviveller Are you still working on this?

**Comment by Tanish0019** [comment]
@nstjean Can I take this issue?

**Comment by nstjean** [comment]
@Tanish0019 If @aviveller does not respond soon I will re-release this issue. We will also post some new first time only issues to do.

**Comment by aviveller** [comment]
Hello

Sorry for the late answer, you can take it .

בתאריך יום ה׳, 7 בנוב׳ 2019, 16:24, מאת Natalie St Jean ‏<
notifications@github.com>:

**Comment by Tanish0019** [comment]
Okay! I'll work on it :)

**Comment by jywarren** [comment]
This one is still available! Thanks, all!

**Comment by jywarren** [comment]
Especially for Outreachy folks!

**Comment by ana-vela** [comment]
Hello! I'm an Outreachy applicant, and I can take this one on if it is still available. Thanks!

**Comment by jywarren** [comment]
Super, thank you!

**Comment by tejaswini22199** [comment]
Hey @nstjean  can I work on this issue ?

**Comment by ana-vela** [comment]
Hi, @tejaswini22199 ! This issue fix is in progress. I'm adding @jywarren as well in case we need any clarification. Thanks!

**Comment by jywarren** [comment]
I believe this is complete, thank you!!!!
