### ISSUE TITLE
Change function t to translation in dashboard/_header

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#6599]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [_header.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_header.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

In this template we need to change the function named t(....) to be named as translation(...) on lines 4, 6, 14, 15, 16, 18, and 19.

https://github.com/publiclab/plots2/blob/9027525dbe504db82276e12ec59dfb00c7a45961/app/views/dashboard/_header.html.erb#L4-L6
change to:
```
      <h1><%= translation('dashboard._header.dashboard') %></h1>
    <% else %>
      <h1><%= translation('dashboard._header.community_research') %></h1>
```

In the lines below notice there are 12 instances of the function t(...)! Make sure we get all of them.
https://github.com/publiclab/plots2/blob/9027525dbe504db82276e12ec59dfb00c7a45961/app/views/dashboard/_header.html.erb#L13-L20
change to:
```
    <% if current_user %>
      <span class="d-none d-lg-inline"><%= translation('dashboard._header.welcome') %><span class="d-lg-none d-xl-inline">,<b><a href="/profile/"> <%= current_user.username %></a></b></span>! <%= current_user.new_contributor %></span>
      <a href="/notes/recent"><%= @note_count %> <% if @note_count === 1 %> <%= translation('dashboard._header.note') %><% else %> <%= translation('dashboard._header.notes') %><% end %></a> <%= translation('dashboard._header.and') %> <a href="/wiki"><%= @wiki_count %> <%= translation('dashboard._header.wiki_edits') %></a> <%= translation('dashboard._header.posted_past_week') %>
      <%= translation('dashboard._header.you_shared') %> <a href="/notes/author/<%= current_user.username %>"><%= @user_note_count %> <% if @user_note_count === 1 %><%= translation('dashboard._header.research_note') %><% else %><%= translation('dashboard._header.research_notes') %><% end %></a>.
    <% else %>
      <span class="d-none d-lg-inline"><%= translation('dashboard._header.welcome') %>!</span>
      <%= translation('dashboard._header.this_could_be_dashboard') %> <a data-toggle="modal" data-target="#loginModal"><%= translation('dashboard._header.joined_public_lab') %></a>
    <% end %>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by jairus-crabb** [comment]
Hello! Has anyone claimed this issue??

**Comment by nstjean** [comment]
@jairus-crabb No one else has, you are welcome to it!

**Comment by gptshubham595** [comment]
May I take this issue 
as it around  days and not solved

**Comment by nstjean** [comment]
@gptshubham595 This issue was requested by @jairus-crabb just 22 hours ago.

**Comment by jairus-crabb** [comment]
I am still working on this!

**Comment by jairus-crabb** [comment]
Hi, just wanted to give an update. I am still attempting to setup, working with WSL has had a learning curve but I'm getting closer. Had a lot of issues with finding a way to access the localhost in WSL from Windows, as I couldn't get a stable version of firefox to run (I think might be related to hardware on my Surface), so I resorted to trying to access from the host's firefox.exe. 

I was able to get the web server "Address Already in Use" problem solved, but now I'm stuck with this error when trying to open the localhost:3000 in a browser (firefox):
ActiveRecord::StatementInvalid in Home#home
Showing /home/jcrabb/Projects/plots2/app/views/layouts/application.html.erb where line #37 raised:
SQLite3::SQLException: cannot rollback - no transaction is active: rollback transaction

Should i make another issue for this localhost problem? I will actively keep trying to setup, I've already learned a lot in the past week and am excited and tackle this issue.

**Comment by nstjean** [comment]
Hi @jairus-crabb did you have any luck? You can post on #3840 for installation problems.

**Comment by jairus-crabb** [comment]
Yes I believe so! I able to get it running on Friday but then I traveled all weekend. I'll be working on this change as it looks fairly simple. One thing is that I couldn't get passenger to work but puma seemed to launch the application without issues, it's been a bit tricky with WSL and lots of trial and error. I'll update if I run into any more roadblocks.

**Comment by nstjean** [comment]
Yes, it is really hard with WSL. If you get it working reliably we may ask you to document what you did, as others are having struggles!

**Comment by jairus-crabb** [comment]
Reliability is indeed now the question! I'll have to get more familiar with the application itself. Is there any other items or things I can test out specifically to test how reliable it is?

Also I should be finishing up this issue today, sorry for the delay on this!

**Comment by nstjean** [comment]
No worries! Thanks!

I don't think there's anything specific, just getting the server to run is pretty great!

**Comment by nstjean** [comment]
If you are able, could you post on https://github.com/publiclab/plots2/issues/3840 with the steps you took to install it and run the server on Windows?

**Comment by jairus-crabb** [comment]
Submitted PR #6816

I can definitely document what I did! So far I haven't had any crazy issues, I ran some tests and the only errors I got were certain functionalities that had dependencies I just hadn't installed.
