### ISSUE TITLE
Change function t to translation in dashboard/_node_question

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#6603]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [_node_question.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_node_question.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

In this template we need to change the function named t(....) to be named as translation(...) on line 18.

https://github.com/publiclab/plots2/blob/9027525dbe504db82276e12ec59dfb00c7a45961/app/views/dashboard/_node_question.html.erb#L18
Change to:
```
      <p class="meta"><%= translation('dashboard._node_question.question') %> <%= render partial: "dashboard/node_meta", locals: { node: node } %></p>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by klaffert** [comment]
Would love to take this one on!

**Comment by nstjean** [comment]
@klaffert Hi, go ahead!

**Comment by klaffert** [comment]
@nstjean All done. Let me know if there's any feedback and thanks!

**Comment by gptshubham595** [comment]
May I take this issue 
as it around 3 days and not solved

**Comment by Devang-25** [comment]
@nstjean Can I claim this one?
I have already committed and pulled 3 requests.
Let me know.

**Comment by nstjean** [comment]
@gptshubham595  @Devang-25 There is already a pull request submitted for this issue.

@Devang-25 These FTO issues are for people who have never submitted a Pull Request before. You can look at https://code.publiclab.org/ (scroll down to "What's next?") for some suggestions on what your next steps can be!

**Comment by klaffert** [comment]
Hi @nstjean is there anything else that needs to be completed on this one? Thanks!

**Comment by nstjean** [comment]
@klaffert It should be all set! Someone will merge it soon. :)

**Comment by nstjean** [comment]
If you are looking for something more to do you can check this page here https://code.publiclab.org/ and scroll down to "What's next?" It has some ideas and links! We also recommend cloning our repository/ies and getting them working on your development machine.
Installation instructions: https://github.com/publiclab/plots2/blob/master/README.md

**Comment by nstjean** [comment]
Completed in https://github.com/publiclab/plots2/pull/6659
