### ISSUE TITLE
"answer has been accepted" email has a typo

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#667]
> Your answer for the question Does the new Question feature work? has been accepted by the question author.

The word "author" was not replaced by a username or link. @ananyo2012 could you look into this? Not super urgent but let's get a fix in, thanks!

**Comment by ananyo2012** [comment]
@jywarren Well I actually did it on purpose as you can see it clearly mentions "the question author" i.e. whoever is the author of the question. Nevermind I will replace it with the actual author name.

**Comment by jywarren** [comment]
Sorry, Ananyo -- hang on a sec, there's a more urgent bug I'm working on
but I apologize if I misfiled this.

**Comment by jywarren** [comment]
You're correct, apologies again, I was just filing these issues as quickly as I could and misread it. Closing; this is not a bug! Great work, Ananyo!
