### ISSUE TITLE
Scroll to top should be hidden before

### ISSUE THREAD

**Issue by gptshubham595** [publiclab/plots2#6684]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step
     - goto https://publiclab.org/
     - see scroll top arrow

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** 
![gif](https://user-images.githubusercontent.com/24877361/68230585-50ee4480-001f-11ea-8433-10a0755c37ef.gif)

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by gptmanoj** [comment]
@gptshubham595 should i opt for this?

**Comment by gptshubham595** [comment]
@gptmanoj go for it

**Comment by jywarren** [comment]
Hi @gptshubham595 I'd like to suggest we hold off on labeling these as `first-timers-only` just yet, as the full formatting of an FTO should include links to where the code is in the project, like this:

https://github.com/publiclab/plots2/blob/e3f1150402a3a16905281f69e1af484e81841d3e/app/models/node.rb#L644-L646

You can read more about how to create full FTO issues here! 

https://code.publiclab.org and https://code.publiclab.org/#whats-next

Thanks so much!!! 🙌

**Comment by swathi-0901** [comment]
hey, can I work on this issue?... If yes can you please tell in detail what is to be done??

**Comment by susanreenesaa** [comment]
hey, @gptshubham595  this issue was already created/ merged so if you don't mind, you can close it. 
Reference to the closed issue #6435

**Comment by gptshubham595** [comment]
No problem
But one can it here now also : https://publiclab.org/ . Can you please confirm?

**Comment by SidharthBansal** [comment]
Hello Shubham,
We are happy to see that you find a bug at the website.
However, this bug is resolved as indicated above.
Quick suggestion: Please use screenshots of the actual website publiclab.org OR localhost.
Also, kindly write the code links in the fto issues
I checked it. It is solved. It will be released into the production in a few days.
Thanks all for helping Shubham. :-)
Thanks all
Sidharth
