### ISSUE TITLE
Remove redundant text written twice: Read More Blog

### ISSUE THREAD

**Issue by gptshubham595** [publiclab/plots2#6686]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

![Untitled](https://user-images.githubusercontent.com/24877361/68231366-efc77080-0020-11ea-98c2-9a80c75f5d68.png)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by gptshubham595** [comment]
@123abhay  go for it

**Comment by Abhinav1299** [comment]
@123abhay if you are not working on this issue, @gptshubham595 can I work on this?

**Comment by ananyaarun** [comment]
@gptshubham595 , what is the issue here ? Pls be elaborate in ur issue templates.

**Comment by ananyaarun** [comment]
@gptshubham595 , Also an FTO needs to have the link to the files that need to be updated and needs to explain the issue properly.

Next time before you allow any contributor claim an issue please get it checked by a plots2 reviewer.
Thanks a lot !

**Comment by Kirti2502** [comment]
Hi, I am an outreachy applicant and I would like to take up this issue.

**Comment by Kirti2502** [comment]
Please let me know the file where I can find this screenshot.

**Comment by theOpetunde** [comment]
Hi, I'm an outreachy aspirant and would be willing to take on this issue knowing @Kirti2502 already claimed one issue before

**Comment by Kirti2502** [comment]
Sorry but I've not claimed any issue on this project. I've been waiting for either confirmation on some issues and some help on this one.

**Comment by theOpetunde** [comment]
Alright then. Thank you for the clarification

**Comment by keshav234156** [comment]
@Kirti2502  you can take up this issue. Please try to claim 1 issue at a time to avoid ambiguity.

**Comment by Kirti2502** [comment]
Yeah sure. I'll take care from next time.

**Comment by keshav234156** [comment]
@SidharthBansal Is this a valid FTO?

**Comment by keshav234156** [comment]
@theOpetunde As I can see you have already attempted an FTO.So now you can move the help-wanted task.
Thanks!!

**Comment by Jigyasa-Kumari** [comment]
Hi, I am Jigyasa and I am an Outreachy 2020 applicant. Is this issue open and can I work on it?

**Comment by cesswairimu** [comment]
Hi all I didn't see this sooner , @ananyaarun your are right, this is not an issue...Its working as desired. Closing this. Thanks all

**Comment by cesswairimu** [comment]
@Jigyasa-Kumari  please let me know if you need help getting a first timer issue
