### ISSUE TITLE
Success notification upon clicking the follow button when user is not signed in

### ISSUE THREAD

**Issue by crisner** [publiclab/plots2#6688]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [subscription_controller.rb] (https://github.com/publiclab/plots2/blob/master/app/controllers/subscription_controller.rb) and [async_tag_subscriptions.js](https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/async_tag_subscriptions.js) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Issue: A bug on 'https://publiclab.org/tags' where the green notification is shown upon clicking the follow button when user is not signed in.
![bug](https://user-images.githubusercontent.com/29401459/68244017-d979de80-0039-11ea-830d-3368f506e01c.gif)

Expected behavior: The green/success notification should not be shown upon clicking the follow button when a user is not logged in.

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

https://github.com/publiclab/plots2/blob/e3f1150402a3a16905281f69e1af484e81841d3e/app/controllers/subscription_controller.rb#L69
make the following changes in the location shown above:
```diff
-     render json: { status: status, message: message, id: tag.tid, tagname: params[:name], url: "/tags" + "?_=" + Time.now.to_i.to_s }
+     if current_user
+       render json: { status: status, message: message, id: tag.tid, tagname: params[:name], url: "/tags" + "?_=" + Time.now.to_i.to_s }
+     end
```
https://github.com/publiclab/plots2/blob/e3f1150402a3a16905281f69e1af484e81841d3e/app/assets/javascripts/async_tag_subscriptions.js#L30-L33
make the following changes in the location shown above:
```diff
+      if(data_recv.id) {
          notyNotification('relax', 3000, 'success', 'top', data_recv.message + 'Click <a href="../subscriptions"> here </a> to manage your subscriptions. ');
          var html_new = '<a rel="tooltip" title=Following class="btn btn-default btn-sm active" href="/unsubscribe/tag/'+ data_recv.tagname + '"> <i class="fa fa-user-plus" aria-hidden="true"></i>Following</a>';
          $('#follow-unfollow-column-'+data_recv.id).html(html_new);
          window.history.pushState("", "", data_recv.url);
+      }
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by crisner** [comment]
@jywarren @cesswairimu Came upon this bug and figured it would make a good FTO. Please let me know if that is not the case or if there are any changes to be made in the issue description. Thank you.

**Comment by cesswairimu** [comment]
Great catch @crisner thanks...do we need to add `.present?` in the current user check smth like `current_user.present?`... or without present returns a boolean too? Thanks

**Comment by crisner** [comment]
Thanks! I tested the code with just `if current_user` and it works as expected.

**Comment by cesswairimu** [comment]
Awesome.. will match this with one of the folks looking for an fto...Thanks

**Comment by rebecarancan** [comment]
@cesswairimu @crisner, I would like to work on this issue.

**Comment by cesswairimu** [comment]
Great @rebecarancan  :tada: its all yours...Go ahead. Thanks

**Comment by rebecarancan** [comment]
@cesswairimu  Ok!!

**Comment by cesswairimu** [comment]
Hi @rebecarancan, go ahead. Thanks
