### ISSUE TITLE
Profile page erroring when not logged in

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#669]
In an incognito window, open any profile page, like:

https://publiclab.org/profile/liz

I see this error in the logs:

```
Completed 500 Internal Server Error in 102.4ms

ActionView::Template::Error (undefined method `role' for nil:NilClass):
    81: 
    82:     <% end %>
    83:     <br />
    84:     <% if current_user == @profile_user || current_user.role == 'admin' %>
    85:       <a href="/profile/info/<%= @user.name %>" class="btn btn-default btn-sm btn-block"><i class="fa fa-pencil"></i> <%= t('users.profile.edit_information') 
%></a>
    86:     <% end %>
    87:   </p>
  app/views/users/profile.html.erb:84:in `_app_views_users_profile_html_erb__818985285315481481_59989420'
```

**Comment by jywarren** [comment]
I believe this is @lalithr95's addition -- I'm issuing an urgent fix for this, as I think it's actually been deployed for a little bit. @lalithr95 -- can you write a test for this case? Just a simple functional test to ensure profile pages load when not logged in.

**Comment by jywarren** [comment]
Actually line 42 of the public_pages_test (in integration tests) should have caught this. I'm not sure why it didn't?

**Comment by jywarren** [comment]
On closer inspection, this is not urgent, as it largely overlaps with #668. However, once `params[:preview]` check is disabled, it *would* become urgent. I'm issuing this fix now, in any case.

**Comment by jywarren** [comment]
So the integration test would have caught it but there were two overlapping bugs. Closing!

**Comment by lalithr95** [comment]
@jywarren I'm writing fix. You can merge best?

**Comment by jywarren** [comment]
Already good, merging now. Thanks!

**Comment by jywarren** [comment]
And resolved in #670.

**Comment by lalithr95** [comment]
Cool Thanks ! Deployed ?

**Comment by jywarren** [comment]
Not yet -- waiting for ananyo's fix and we'll post both together.

**Comment by lalithr95** [comment]
Okay, We should probably start with any of the exception tracking systems, https://rollbar.com/ is good to start with. They allow free account for 1 project. We get these exception way before (after deploy) than  we discover.

What do you think ?

**Comment by jywarren** [comment]
Hmm, interesting! I'm not familiar with it and will check it out.

We should also have continuous integration testing with TravisCI soon.

**Comment by lalithr95** [comment]
Yeah cool 👍
