### ISSUE TITLE
Profile dropdown menu gets cut off on smaller screens 

### ISSUE THREAD

**Issue by susanreenesaa** [publiclab/plots2#6692]
Referencing Issue #6574 
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open-source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```
*Problem*
Currently, the navigation bar is fixed on top. The issue is that on a smaller screen( ie mobile phone or minimize Pc screen to phone screen size), one is unable to view all the elements in the dropdown menu. as shown below
url https://publiclab.org/ or https://publiclab.org/blog

![image](https://user-images.githubusercontent.com/49034794/68250053-1a212a00-0031-11ea-8581-99c3d2a1dbf4.png)

*Expected*
the menu should be scrollable so as to view all menu elements. (see image below)
![image](https://user-images.githubusercontent.com/49034794/68250915-11c9ee80-0033-11ea-8e4d-11f8e939c382.png)

to make changes, navigate to *plots2/app/views/layouts/_header.html.erb*
at the extreme end of  the file in (<style>..... </style>)and the code below (add lines 188 to 194)
<style>
  @media (max-width: 767px){
    .navbar{ 
    max-height: 100vh; 
     overflow-y: auto; 
    -webkit-overflow-scrolling:touch;
   }
 }
 </style>
code to be added as shown in blue on the right side of the picture
![image](https://user-images.githubusercontent.com/49034794/68249709-6750cc00-0030-11ea-9b1a-a5a0678012de.png)

**Comment by TedTran2019** [comment]
May I please give it a shot?

**Comment by swathi-0901** [comment]
@susanreenesaa can I work on this issue?

**Comment by nitish81299** [comment]
@susanreenesaa **I would like to work on the issue.**

**Comment by nitish81299** [comment]
@susanreenesaa 
I have made a [PR](https://github.com/publiclab/plots2/pull/6698) for the above issue, have a look.

**Comment by susanreenesaa** [comment]
sorry for the delay in reply

**Comment by susanreenesaa** [comment]
@jywarren help me review this. I tried to but I have no clue where to find the file to review. maybe you can give me direction on how to do it. thanks

**Comment by dmahajan980** [comment]
@susanreenesaa  I would like to work on this issue if it isn't fixed.
