### ISSUE TITLE
Remove extra dots appearing in website

### ISSUE THREAD

**Issue by gptshubham595** [publiclab/plots2#6694]
Please Note: We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more

Problem
We just have to increase space and make one dot bigger arrow key also appears when we are at the top of the page.
[here](https://www.publiclab.org/methods)

![dot](https://user-images.githubusercontent.com/24877361/68291606-3c0dc180-00b0-11ea-8764-fd0ea593b816.JPG)

**Comment by SidharthBansal** [comment]
Please write the issue in the GCI tasklist.
Thanks

**Comment by SidharthBansal** [comment]
Please add adequate labels.

**Comment by susanreenesaa** [comment]
@SidharthBansal. should i convert this into FTO issue

**Comment by SidharthBansal** [comment]
Sure

**Comment by gptshubham595** [comment]
@susanreenesaa Sure

**Comment by ananyaarun** [comment]
There are multiple issues open for this one.
Also since this has been listed on the GCI task list, Can we close one ?

**Comment by SidharthBansal** [comment]
Sure!
