### ISSUE TITLE
Selection of the center grid in "Choose your Location" map picker is not working

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#6697]
### Please describe the problem (or idea)

> What happened just before the problem occurred?

Excitedly, i clicked the new "Add Location" button to add latitude and longitude to the London page: 
<img width="287" alt="Screen Shot 2019-11-06 at 10 47 54 AM" src="https://user-images.githubusercontent.com/161439/68313845-42d20f80-0083-11ea-91d7-eb3b1eb021ee.png">

In the map picker, i was unable to choose the square for London. I feel that there is something broken about the selection of the centered grid square that one wishes to choose for location...see my trouble picking London in the gif below: 

![Location-Grid-Bug](https://user-images.githubusercontent.com/161439/68313983-7745cb80-0083-11ea-9acf-27df6351117d.gif)

> What did you expect to see that you didn't?

I expected to be able to slide the map area for London into the center of the picker, and have it highlight in red. 

### Please show us where to look

https://publiclab.org/wiki/london-uk --> "Add Location" button in upper right sidebar

Thank you!

**Comment by susanreenesaa** [comment]
let me try it out

**Comment by ebarry** [comment]
How's it going @susanreenesaa ?

**Comment by susanreenesaa** [comment]
@ebarry. Still stuck but I am working on it.
I started with the search bar, the one (search bar) that I got from the leaflet notes that I have read so far, is fixed or located in the map div so I am trying to see how I can get it out of the map div so that it appears like the one in the page. (search bar above the map).
so if you have any content that is helpful, I will be grateful. thanks

**Comment by susanreenesaa** [comment]
@ebarry. I tried it out today and the **ADD LOCATION** button is no longer a link (it does not render the map anymore. when clicked nothing happens). so do I have to do the whole thing from scratch?

**Comment by ebarry** [comment]
HI @susanreenesaa , i see what you are saying -- the Location button has some odd behavior. I had to click it twice to get the interface to open. That may be an additional bug that you could report in a new issue? 

Once I got the interface open by clicking a second time, i panned around the grid lines and have some new observations to report: the problem with the red highlight "skipping" over certain areas seems to be happening to certain longitudes, namely between 1W and 0 degrees longitude. Is there perhaps a math error involved? 

CC @sagarpreet-chadha to advise as well. Thank you!

**Comment by jywarren** [comment]
Just wondering (we really should document in a separate issue) if the
2-clicks-to-open issue could just be the page finishing loading? If you
wait a good while then click, does it open the first time?

Your observation about London being very near 0 longitude is really key
here! That is almost certainly related as shown in your gif, and we should
maybe move this to https://github.com/publiclab/leaflet-blurred-location for
follow-up. The algorithm to draw the boxes is there and probably is not set
up for the special case of a box where one longitude is ~359 and the other
~0. Thanks!

**Comment by susanreenesaa** [comment]
the add location button does not open the map at all so currently, I am not working on the issue because I have no access to the map(popup map). unless if I have to recreate the code?

**Comment by sagarpreet-chadha** [comment]
Hey the map should open --- yes @jywarren is right it takes time for JS to get load.

**Comment by jywarren** [comment]
Closing this in favor of #213 but if there is another bug that can be disambiguated from that one, please re-open and add info! Thank you!
