### ISSUE TITLE
Incorrect comment count on some of the Public Lab blogs

### ISSUE THREAD

**Issue by Ugtan** [publiclab/plots2#6702]
### Please describe the problem (or idea)
The cards present in the Public Lab blog section, as well as the blogs section on `https://publiclab.org/blog`, show an incorrect number of comments. When you click on the blog to check the comments, the number will be different there. I have seen an irregularity as some blog cards show correct number of comments as well.
![image](https://user-images.githubusercontent.com/32966387/68339942-8a03e300-010b-11ea-9d1c-8055f922d372.png)
![image](https://user-images.githubusercontent.com/32966387/68340019-a99b0b80-010b-11ea-8fb2-698ddb2a11df.png)
![image](https://user-images.githubusercontent.com/32966387/68340049-bae41800-010b-11ea-8608-8a5053263913.png)

### Please show us where to look

`https://publiclab.org/blog`

### What's your PublicLab.org username?

umang.taneja0173

### Browser, version, and operating system

Firfox v69.0.1 OS- Manjaro

**Comment by nstjean** [comment]
Thanks! I will take a look at this.
