### ISSUE TITLE
Change function t to translation in wiki/_wikis

### ISSUE THREAD

**Issue by swathi-0901** [publiclab/plots2#6704]
We need to change the function t to translation in lines 10,12,13,14,15 of wiki/_wikis

**Comment by Abhinav1299** [comment]
I would like to solve this issue

**Comment by swathi-0901** [comment]
Yea this is a first-timer issue If you're so please go ahead :)

**Comment by Tlazypanda** [comment]
@swathi-0901 Is this issue still available?

**Comment by nstjean** [comment]
This issue is open!

**Comment by chirag-wadhwa** [comment]
Heya, can I work on this issue...

**Comment by nstjean** [comment]
@chirag-wadhwa Go ahead!

**Comment by chirag-wadhwa** [comment]
Heya, the function t has already been replaced with translation in the above mentioned lines in the file wiki/_wikis. 
Is there anything else to be done in the file???

**Comment by nstjean** [comment]
Oh sorry! It looks like this issue was posted twice. Let me find another file for you to edit.

**Comment by chirag-wadhwa** [comment]
No worries,
Thanks...

**Comment by chirag-wadhwa** [comment]
Heya, can I work on the issue #6727 ???

**Comment by nstjean** [comment]
I made this one for you :) https://github.com/publiclab/plots2/issues/7484
