### ISSUE TITLE
Descriptive Title Assurance of Pull Requests

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#6716]
![image](https://user-images.githubusercontent.com/20972099/68394078-3341ec00-0193-11ea-8bc6-929ffc71a22c.png)
Mentors are requested to ensure titles of issues and PRs should be descriptive. 
`Update index.html.erb` etc doesn't make any sense. PR titles should be descriptive.
I just opened this issue as I saw this practice followed by many contributors. Let's keep quality over quantity.
@cesswairimu @gauravano @sagarpreet-chadha @jywarren @ebarry

**Comment by susanreenesaa** [comment]
That's a great observation @SidharthBansal. Thanks

**Comment by SidharthBansal** [comment]
@jywarren closing this now
