### ISSUE TITLE
Tag sort needs refresh to work properly

### ISSUE THREAD

**Issue by ananyo2012** [publiclab/plots2#672]
### What happened just before the problem occurred

Well I don't know why this is happening. When I try to add a new tag or remove a tag from the Tag sort in the questions page the results doesn't get sorted and neither the tags are displayed at the beginning. After I do a page refresh then after it starts working correctly. Same goes for the Clear all tags. Though I see it working perfectly in development in my local machine. There is something going on in the session storage which I just can't figure out. This are links to the relevant code that I wrote for the Tag sort functionality.

This is the controller code for adding or removing tags in session: https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L237-L263

This is the `sort_by_tags` method that does the sorting: https://github.com/publiclab/plots2/blob/master/app/controllers/application_controller.rb#L179-L191
### Relevant URLs

https://publiclab.org/questions
### PublicLab.org username

ananyo2012
(to help reproduce the issue)
### Browser, version, and operating system

Google Chrome, Firefox on Ubuntu 14.04 LTS

**Comment by jywarren** [comment]
I'm looking at this now, but a quick note is that I think you can remove the "banners" from the left sidebar, so the sort interface is easier to find.

**Comment by jywarren** [comment]
Hm, when I type in "drone" and press enter, the page refreshes and I see the one question tagged "drone" -- so it seems to work for me? 

I'm curious, though, maybe we should use the URL instead of a session, if we're already going to be refreshing the page? We could do `/questions/drone` or `/questions/tag/drone`?

**Comment by ananyo2012** [comment]
Well there is already a `/tag/drone` page that is managed by the tags controller. We should then append tag parameter in url like `/questions?tag=drone,spectrometer`. Actually using session was much convenient since it can be used over any pages or urls like liked and popular pages too. This is hard to fix since I am not getting any problems in development. Maybe there are any setting for session store that we are missing in production.

**Comment by jywarren** [comment]
Hmm, yes i think session store can be set to 'cookie' or 'file' for
different environments, in `/config/environments/x.rb` ... i haven't much
experience with it though.

**Comment by jywarren** [comment]
Hi, Ananyo -- just tried entering a tag ('spectrometer') on /questions and got redirected to:

https://publiclab.org/tag/add_tag?return_to=%2Fquestions&name=spectrometer

Is this related to the above issue, or is it a distinct one I should file an issue for?

Thanks!

**Comment by ananyo2012** [comment]
@jywarren Ok i see this is a routing problem. See these two line https://github.com/publiclab/plots2/blob/master/config/routes.rb#L152 and https://github.com/publiclab/plots2/blob/master/config/routes.rb#L168. The first one should not be present. This is not related to this is issue but in fact this is the reason why tests were failing for the sort_by_tags integration test during the search api merge. The long rebase might have overlooked this. I am just fixing this and reading the tests as well.
