### ISSUE TITLE
Make tag text and delete "x" icon more visually distinct

### ISSUE THREAD

**Issue by publiclab-mimi** [publiclab/plots2#6720]
**Please describe the desired behavior.**
While working with a new Public Lab user, were confused by the “x” that appeared next to a tag. The person said  “wait i tagged this ‘soil’ not ‘soil x’” and made me realize just how close the "x" to delete and the font for the tag are.

I am hoping that we can change that "x" for delete to one that is more visually distinct from the font, like an X in a circle or a box. 

Below I've included a photo of the way that tags currently look for reference.

<img width="161" alt="Screen Shot 2019-11-07 at 2 44 04 PM" src="https://user-images.githubusercontent.com/48802639/68426126-185c8100-016d-11ea-9d3d-fb2c9bd3f514.png">

**Comment by susanreenesaa** [comment]
@publiclab-mimi, how are you doing?
can you please share with me the URL for that page( where tags with X are located ) so that I can create an FTO for it.
Thank you

**Comment by publiclab-mimi** [comment]
Sorry for the delayed reply. 

The "x" on a tag page comes up on any note that the user has authored when they're logged in. These also come up if you add a tag to an existing page, even if you're not the author, although only for the tag you've added. It's the way that a user can remove tags they've created. So I don't know what a good url to share for that would be.

**Comment by jywarren** [comment]
I think we can look through the FontAwesome icon collection, which we use
already in the codebase, for a more suitable "x" icon to use!

**Comment by susanreenesaa** [comment]
let me do that. @ jywarren.

**Comment by susanreenesaa** [comment]
@publiclab-mimi  any url would have helped as a starting point with the above explanation because i have to open all pages until i find on any page where that occurs.

**Comment by susanreenesaa** [comment]
@publiclab-mimi if you don't mind, you can send me like two URL as i also look try to trace the page on which the  bug is located

**Comment by jywarren** [comment]
I believe it's in the sidebar on posts, so any wiki page for example after
expanding the (+) at the bottom of the sidebar. The template should be in
views/tags/tagging I think? Thank you very much!!

**Comment by jywarren** [comment]
This was refactored by @susanreenesaa into #6791, and solved in #6793 ! Thanks!!!!
