### ISSUE TITLE
Change function t to translation in layouts/_alerts.html.erb

### ISSUE THREAD

**Issue by Abhinav1299** [publiclab/plots2#6727]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [layouts/_alerts.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/layouts/_alerts.html.erb) in the `https://github.com/publiclab/plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is showing where to make changes:

In `plots2/app/views/sidebar/_author.html.erb` file, change occurrences of function t(...) to translation(...) on line number 26.

> ` <div class="alert alert-warning"><button type="button" class="close" data-dismiss="alert">×</button><i class="fa fa-exclamation-mark"></i><%= t('layout._alerts.request_access') %><a href="/openid/resume"><%= t('layout._alerts.approve_or_deny') %> &raquo;</a></div><% end %><% cache('feature_sitewide-alert', skip_digest: true) do %><%= feature('sitewide-alert') %><% end %></div><script> 
 setTimeout("$('.alerts-container .alert-success').fadeOut('slow')", 7000)</script>
`

change this to:

> `<div class="alert alert-warning"><button type="button" class="close" data-dismiss="alert">×</button><i class="fa fa-exclamation-mark"></i><%= translation('layout._alerts.request_access') %><a href="/openid/resume"><%= translation('layout._alerts.approve_or_deny') %> &raquo;</a></div><% end %><% cache('feature_sitewide-alert', skip_digest: true) do %><%= feature('sitewide-alert') %><% end %></div><script> setTimeout("$('.alerts-container .alert-success').fadeOut('slow')", 7000)</script>`

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by nstjean** [comment]
Hi @Abhinav1299 ! Thanks so much for opening a FTO, it is much appreciated! You will just have to edit the post to add the information someone will need, such as a link to the file, the repo name (plots2), and where it says DIFF you will add in the line number(s) and show what the code should be after changes.

**Comment by Abhinav1299** [comment]
@nstjean I have made the required changes. Thanks for the information.

**Comment by nstjean** [comment]
Great thanks!

This issue is open!

**Comment by sap143** [comment]
I want to work on this issue

**Comment by nstjean** [comment]
@sap143 Go ahead!

**Comment by sap143** [comment]
I am not able to find line no 26 in plots2/app/views/sidebar/_author.html.erb . It has only 16 lines

**Comment by nstjean** [comment]
@sap143 I see there was an error with the file name. It was supposed to be _alerts.html.erb
However it looks like someone created a pull request for this issue already.

**Comment by sap143** [comment]
ok should I leave it now or continue to this issue

**Comment by nstjean** [comment]
@sap143 We'll have to find another FTO issue for you! I'll be creating more.

**Comment by nstjean** [comment]
This issue is open!

**Comment by chirag-wadhwa** [comment]
Heya, can I work on this issue...

**Comment by nstjean** [comment]
@chirag-wadhwa I just assigned a different issue to you, so we can leave this open for someone else. :)

**Comment by Alexjake660** [comment]
@nstjean Is this issue still open?

**Comment by cesswairimu** [comment]
@Alexjake660 yes t is please go ahead

**Comment by Alexjake660** [comment]
@cesswairimu check my pull request please.
