### ISSUE TITLE
change function t to translation of views/grids/_thumbnail

### ISSUE THREAD

**Issue by swathi-0901** [publiclab/plots2#6736]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:
change the function t to translation in lines 23 and 26. After changing the lines should look like below:

```diff
<%= translation('notes._notes.last_edit_by') %> <a href="/profile/<%= node.latest.author.name %>"><%= node.latest.author.name %></a>
| <i class="fa fa-eye"></i> <%= number_with_delimiter(node.views) %> <span class="d-none d-md-inline"><%= translation('notes._notes.views') %></span>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by nstjean** [comment]
Hi @swathi-0901 ! Thanks so much for opening a FTO, it is much appreciated! You will just have to edit the post to add the information someone will need, such as a link to the file, the repo name (plots2), and where it says DIFF you will add in the line number(s) and show what the code should be after changes.

**Comment by swathi-0901** [comment]
> Hi @swathi-0901 ! Thanks so much for opening a FTO, it is much appreciated! You will just have to edit the post to add the information someone will need, such as a link to the file, the repo name (plots2), and where it says DIFF you will add in the line number(s) and show what the code should be after changes.

Yea I did it :)

**Comment by nstjean** [comment]
This issue is open!

**Comment by priyajitm** [comment]
I claim this.

**Comment by priyajitm** [comment]
@nstjean @swathi-0901 I am getting error in Travis integration check.

**Comment by taysa91** [comment]
Hi @nstjean 
I am an Outreachy applicant and new to open source. Is this issue still open. I would like to work on it.
Thanks

**Comment by nstjean** [comment]
@taysa91 There is a PR submitted for this that works, they are just waiting to merge it until something else is done. :)

**Comment by jywarren** [comment]
This is available again! Thank you!!!

**Comment by jywarren** [comment]
Actually i believe the code has been reorganized enough that we should close. Thanks everyone!!!
