### ISSUE TITLE
stray flash message "Your preference has been saved" shows on a page after editing location tags

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#674]
### What happened just before the problem occurred

I went to `/editor`, and saw the message `Your preference has been saved` -- but I hadn't been editing the location tags since yesterday. I think this line:

https://github.com/publiclab/plots2/blob/eb2cc80f1c12abb1ebbf701079205c39065e8f55/app/controllers/users_controller.rb#L255

...needs work -- flash messages are displayed only after a redirect, I believe? At least the ordering is not straightforward; can you take a look, @lalithr95 ? Thanks!

**Comment by lalithr95** [comment]
I'll fix this, flash need to be updated in redirect.

**Comment by lalithr95** [comment]
Thanks for the invite to PublicLab 👍  🎉

**Comment by jywarren** [comment]
complete in #688
