### ISSUE TITLE
Show hover text when the cursor points to the social media icons

### ISSUE THREAD

**Issue by preetiy** [publiclab/plots2#6742]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.
Add hover text so that when a cursor points to the social media icon, the name of the social media icon is visible.
![Screenshot (5)](https://user-images.githubusercontent.com/31736843/68488959-2e04a000-026c-11ea-9d58-7af76008f204.png)

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by ameykulkarni25dec** [comment]
I would like to get started with this. Please help me out, I am totally new to Github and Open Source contributions, although I have 8 years of Java dev experience. Please let me know how to start.

**Comment by aayush-05** [comment]
Hey @preetiy !
Can I work on this issue ?
Please assign it to me.

**Comment by susanreenesaa** [comment]
@preetiy  for this to be an FTO, it must have all the code and instructions needed to complete it. so I changed the label. if you want to be an FTO, include all the necessary instructions to complete it. Thanks for contributing to public lab

**Comment by susanreenesaa** [comment]
@ameykulkarni25dec. please join the publiclab community chat ( https://gitter.im/publiclab/publiclab )for faster help because there are many/different people who are available and willing to help at all time. Also, you can look through this list and claim any issue that u can do by commenting on it. https://github.com/publiclab/plots2/labels/first-timers-only.
Here is an guideline on how to use git and github effectively https://publiclab.org/notes/stefannibrasil/04-20-2018/github-guide-for-open-source-contributions.
Hope that helps for now

**Comment by preetiy** [comment]
> @preetiy for this to be an FTO, it must have all the code and instructions needed to complete it. so I changed the label. if you want to be an FTO, include all the necessary instructions to complete it. Thanks for contributing to public lab
@susanreenesaa  Hey! thank you for changing the label, will take care of it for further contributions.

**Comment by preetiy** [comment]
@ameykulkarni25dec  you can work on this issue.

**Comment by preetiy** [comment]
@aayush-05  please go for other FTO as this was already approached by someone else. you can go this link 
 https://github.com/publiclab/plots2/labels/first-timers-only 
and find one for you.

**Comment by Tlazypanda** [comment]
@preetiy Is this issue still available?

**Comment by preetiy** [comment]
> @preetiy Is this issue still available?

Sorry this has been already taken, you can find one at https://github.com/publiclab/plots2/labels/first-timers-only

**Comment by priyanka-choubey** [comment]
@preetiy  @jywarren can i take this up if noone else is working on it?

**Comment by jywarren** [comment]
Sure, it seems so -- thank you!

**Comment by priyanka-choubey** [comment]
@jywarren can you direct me to the file where the changes need to be made. I can't find the icon on local host.

**Comment by jywarren** [comment]
So, this is stored in the database in a "Feature" -- https://github.com/publiclab/plots2/blob/master/doc/DATA_MODEL.md#Features explains a bit more. 

That means, the best may be to "view source" in a browser, and post the change here, and I or another admin can copy it into the database. Unfortunately this means there will not be a code commit in the repository! If you'd prefer to take another issue, I understand! But we could still use the help. Thank you!

**Comment by priyanka-choubey** [comment]
```

		<a href="https://twitter.com/intent/follow?original_referer=http%3A%2F%2Fpubliclab.org%2Fhome&amp;region=follow_link&amp;screen_name=PublicLab&amp;tw_p=followbutton&amp;variant=2.0"><span rel="tooltip" title="twitter" data-placement="top"><i style="text-decoration:none;" class="fa fa-twitter"></i></span>
</a>
		&nbsp;
		<a href="https://www.facebook.com/PublicLab"><span rel="tooltip" title="facebook" data-placement="top"><i style="text-decoration:none;" class="fa fa-facebook"></i></a>
		&nbsp;
		<a href="https://instagram.com/publiclab"><span rel="tooltip" title="instagram" data-placement="top"><i style="text-decoration:none;" class="fa fa-instagram"></i></span></a>
		&nbsp;
		<a href="https://www.youtube.com/c/publiclab"><span rel="tooltip" title="youtube" data-placement="top"><i style="text-decoration:none;" class="fa fa-youtube-play"></i></span></a>
```
	This will give you a tooltip above the icons.
![Screenshot from 2020-01-18 11-57-22](https://user-images.githubusercontent.com/33806116/72659770-f98b2e00-39ea-11ea-91d5-65c7a1498715.png)

**Comment by jywarren** [comment]
Hm, there's a slightly odd underline effect shown... and it's not quite aligned with the twitter icon. Is that something we could refine a bit more before using this? Thank you so much!

![image](https://user-images.githubusercontent.com/24359/72830203-37d45780-3c4e-11ea-9b01-68e953454a49.png)

**Comment by Kirti2502** [comment]
Hi, I am an outreachy applicant and I would like to take up this issue.

**Comment by Srija616** [comment]
Hey! @jywarren Can I claim this task for the Outreachy application?

**Comment by cesswairimu** [comment]
This has to be edited from the live db hence not available for fixing in development mode. Closing this. Thanks all.
