### ISSUE TITLE
Use Gitpod for people wanting an online workspace?

### ISSUE THREAD

**Issue by Tanish0019** [publiclab/plots2#6747]
**Please describe the desired behavior.**
As cloud9 workspaces have been disabled, we can try using Gitpod instead as it makes it easy for beginners to get started with contributing without the hassle of installing all requirements locally.

**Additional context (optional)**
Add a gitpod.yml file and add the instruction section in the README.

**Comment by Tanish0019** [comment]
@jywarren what do you think?

**Comment by nicoleiocana** [comment]
I wouldn't necessarily agree that cloud9 workspaces have been disabled. Even though they have been acquired by AWS, they are now just AWS Cloud9 workspaces. I referenced that I have an updated version of the install_cloud9 shell script file [here](https://github.com/publiclab/plots2/issues/3840#issuecomment-551888732). This way individuals who have an AWS Cloud9 account could still help via the cloud vs. locally. I just haven't heard back from anybody yet; hence, I have not made a PR.

**Comment by jywarren** [comment]
This is a great idea and we've completed it in https://github.com/publiclab/plots2/pull/8145 ! Thank you!
