### ISSUE TITLE
Remove extra dots appearing in website 

### ISSUE THREAD

**Issue by susanreenesaa** [publiclab/plots2#6752]
**Referencing issue** #6694

Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step
**Remove extra dots ** in the web page so that it looks good. below is the **image showing** the  **Error**
![image](https://user-images.githubusercontent.com/49034794/68528847-09123a80-0309-11ea-885a-03ef32def6df.png)
**Expecting **
no more dots on the page.
![image](https://user-images.githubusercontent.com/49034794/68528883-6f975880-0309-11ea-858f-e6d5ce5510e5.png)
**Path of the file to edit:  plots2/app/views/notes/_notes.html.erb**
**code to be added**
**Eclose** `<li>....</li>` on lines 70 to 71 into `<div style="list-style-type:none;>.....</div>` as shown in the image below
![image](https://user-images.githubusercontent.com/49034794/68529393-50032e80-030f-11ea-95d6-c21de8ef282b.png)
- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by rasokan** [comment]
Can I take this one?

**Comment by kamal-kaur04** [comment]
@publiclab/reviewers I have fixed this issue. Please review it. Thank You.

**Comment by ananyaarun** [comment]
Hey @kamal-kaur04 @susanreenesaa  , This issue is reserved for GCI participants.
We would love the have your help with other issues.
Thanks !!

**Comment by susanreenesaa** [comment]
@kamal-kaur04. this issue is for only GCI participants as indicated in the labels.  so please reconsider if you are not one of them.

**Comment by priyajitm** [comment]
what is gci?

**Comment by ananyaarun** [comment]
Hey @priyajitm GCI is google code in , a competition for 13-17 year olds to introduce them to open source.

**Comment by jywarren** [comment]
Hi, all, i believe this got solved in an unrelated issue, actually, so
perhaps we need to close it and the corresponding GCI task? Thanks!

**Comment by jywarren** [comment]
oh! no, it's still there! https://publiclab.org/methods Thanks!
