### ISSUE TITLE
Weekly community Check-In #38 Planning GCI and Prize Guidelines

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#6762]
Hi everyone 👋
We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. 💯

### Guidelines for Mentor Prizes :1st_place_medal: 

**IMPORTANT NOTE:** Please ensure a healthy, friendly and collaborative environment at PL :heart: . Teamwork and community bonding will be judged amongst mentors. We strongly prefer collaboration and mutual support over competitions amongst mentors. Collaboration and kindness are key ingredients for deciding the prizes.

**Metric for deciding prizes for mentors** :1234: 

1. Form filled by GCI students about mentor preferences and mentor work.
2. Form filled by mentors who they think was the best mentors. (They can't fill their names.)
3. Tasks made by the mentor on the GCI dashboard. 
4. Tasks reviewed by the mentor
5. Other supportive and collaborative factors like FTOs opening up, issues opening up, bug reporting.

Quality and number of tasks/ issues/ PRs reviewed by the mentors will be judged by the judging team. Judging Team will involve Cess, Jeff, Gaurav, Liz and Sidharth. Forms will be filled in the last week of GCI.

This year, we are providing some prizes for mentors as well! :100:  :tada:  :tada: :smile: The following three prizes will be made available:
1. Best GCI mentor will be awarded GCI grand prize trip and PL kit.
2. Second prize, best GCI mentor will be awarded trip to GSoC summit*
*Note: Google made an additional 'GCI' slot available this past GSoC summit, and we don't know that this is permanent. But if it is available, this mentor would be selected to attend. In case GSoC will not allow for GCI mentor to attend GSoC summit, then, unfortunately, we will not be able to send anyone there as GCI mentor.
3. Third best GCI mentor will get a PL Kit.
Leading mentors for the following repositories will each get a kit (1 max per mentor): :
LEL
LBL
plots2
PublicLab.Editor
image-sequencer
mapknitter
spectral-workbench
spectral-workbench.js
infragram
  
Minimum 10 tasks should be reviewed and made in the respective repository to be eligible for prizes.
AND 
Fill https://github.com/orgs/publiclab/teams/gci/discussions/4
4. GCI certificate, T-shirt and Stickers will be awarded to each mentor (by Google).  :+1: 

## Planning GCI :seedling: 

There are basically 4 tasks which we need to ensure before GCI starts.
1. 100 FTOs for NON-GCI Public
2. 100 FTOs RESERVED for GCI students
3. 200 general tasks for GCI students
4. Get the tasks published by me or Jeff.

**Guidelines** https://github.com/orgs/publiclab/teams/gci/discussions/5

This year Google became stricter than last year. In GCI, no mentor is allowed to ask any personal information from mentees not even the name nor blog writing etc.
Also, Google wants active mentors this year. Else they asked Org Admins to revoke Mentorship Requests. PL doesn't want to lose any of their mentors. So, all mentors are requested to add at least 5 tasks on their dashboard asap. 5 tasks will help us in demonstrating you as active PL mentor. NO hard and fast rule of 5. Just it is my suggestion to show you as an active contributor.

**Check mentorship**: Last date to get mentor invite is 14 November 11:59:59pm. In case you have not received mentor invite yet for GCI dashboard AND https://github.com/orgs/publiclab/teams/gci/members. Please contact Sidharth or Jeff. 

Mentors are requested to help us in https://github.com/orgs/publiclab/teams/gci/discussions

# Non-GCI Mentors

Non-GCI mentors can also help us by creating issues and reviewing prs. We can add you in the reviewer's team if you work good! :tada:

**Comment by SidharthBansal** [comment]
@gauravano @milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @shubhscoder @sidntrivedi012 @SidharthBansal @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77

**Comment by SidharthBansal** [comment]
@ananyaarun @ananya @publiclab-mimi @ananya @hc-barker @starkblaze01 @asquare@pdurbin @HarshKhandeparkar@newbazz @aSquare14 @vaarigupta @alonpeer @aashna27 @harshithpabbati @jesus-montano@cryptoclidus @mohamed-elalem @konolga @gowtham5699@jywarren @ebarry @steviepubliclab @StlMaris123, @tauhir, @augustozanellato, @nstjean, @stefanosu, @alexido19, @Akashutreja, @fadib, @skai-ste, @mahimahans111, @Lisa-Caton, @pkayres, @JeffOgah, @IvetaHron, @Linda-Ikechukwu, @crisner, @vishakhanihore, @shailzaa, @saivoleti17, @chrisnorwood, @DanielKlys7, @Diegoafv, @saramace, @lojosmit, @kyebrowning, @jon-flores

**Comment by SidharthBansal** [comment]
@jywarren @gauravano @cesswairimu @ebarry

**Comment by nstjean** [comment]
Hi! That all sounds very exciting with the GCI, good luck to all!

I finished my Outreachy proposal!
https://publiclab.org/notes/natalie_stjean/10-29-2019/outreachy-proposal-refine-geographic-ui-and-js-integration-for-publiclab-org
Thanks to all who took a look at it. I'm really excited to get started on my project in December, if selected. :)

I've continued organizing the list of translation FTOs on #6579 . This week we've had some newbies using the list to post FTOs on their own, which is great! I've learned how to post PR reviews, and how to pull PRs down to my local computer to view the code.

For Pull Requests this week I've worked on these:
LEL: https://github.com/publiclab/leaflet-environmental-layers/pull/278
Plots2:
#6718 - bug fix
#6422 - finished the second half, needs a review
#6402 - old fix, rebased and pushed up new version so it can be merged

**Comment by IshaGupta18** [comment]
All this sounds amazing Natalie! I will also review your proposal if you
would like another opinion at it?

**Comment by nstjean** [comment]
Sure! It might be too late to make any changes in the official proposal, but I'm definitely open to suggestions for the project!

**Comment by cesswairimu** [comment]
Great  check-in @SidharthBansal :tada: , thanks for the comprehensive updates.. exciting weeks ahead...hi @IshaGupta18 :wave: great stuff @nstjean and all the best...Have a great week ahead all

**Comment by SidharthBansal** [comment]
Nice to see enthu of all of you folks!

**Comment by SidharthBansal** [comment]
Is anyone willing to open the check-in in the first week of December about `Welcoming Google Code In Students`?
And who is going to open next check-in? Next week check-in could be `Welcoming Outreachy folks`.

Thanks

**Comment by sagarpreet-chadha** [comment]
I will open!

**Comment by SidharthBansal** [comment]
Which one?

**Comment by SidharthBansal** [comment]
Hi GCI mentors, we have moved to https://github.com/orgs/publiclab/teams/gci/discussions for GCI things! All discussions regarding GCI mentorship are PRIVATE! to mentors only now. If you find any GCI mentorship discussions happening in public[except GCI tasklist], please ping me.
Thanks all.

**Comment by SidharthBansal** [comment]
**IMPORTANT**: Till now 13 tasks are published. We have only 15 tasks as Draft.
We need 225 tasks before 1 December. Mentors are kindly requested to make as many tasks as possible. If we will not be able to get 100+ tasks published before 1 Dec, we will not be able to welcome GCI this year :-(
So, please make 5 to 15 tasks each day on the GCI Dashboard. GCI is a big responsibility. I hope you all have the enthusiasm to complete this! :+1: 
Best of luck

**Comment by cesswairimu** [comment]
Anyone interested in opening next weeks check-in?

**Comment by SidharthBansal** [comment]
Sagarpreet commented above!

**Comment by cesswairimu** [comment]
Awesome..thanks @SidharthBansal

**Comment by sagarpreet-chadha** [comment]
Shifted to https://github.com/publiclab/plots2/issues/6792

**Comment by sashadev-sky** [comment]
@SidharthBansal I will do the one the week after to welcome the google code in students :)
