### ISSUE TITLE
Comments on answers don't appear in the main Dashboard comment feed

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#677]
https://publiclab.org/questions/AndrewJamesLaplante/06-12-2016/question-how-to-rename-a-set#answer-comment-15148

@ananyo2012 - not sure how this is set up, but would you mind taking a look? Thanks!

**Comment by ananyo2012** [comment]
@jywarren Actually comments for answers don't show up since they don't have a direct parent. They are related through the answers. I will add answer comments in dashboard as well but will slightly change the view for this.
