### ISSUE TITLE
install_cloud9.sh needs to be updated for AWS Cloud9 with Amazon Linux Platform

### ISSUE THREAD

**Issue by nicoleiocana** [publiclab/plots2#6773]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

The problems occur during the installation of the commands in the script shell all the way up until you have logged in as the user/moderator/admin. To break down each point of occurrence:
1. During installation, the terminal will prompt - 
* `RVM is not a function, selecting rubies with 'rvm use ...' will not work.`
* `sudo: apt-get: command not found`
* The top right-hand corner will display: `On Amazon Linux use yum instead of apt-get`
2. After installation, after runnning `rails s -b $IP -p $PORT`, the terminal will prompt - 
* `Could not find proper version of railties (5.2.3) in any of the sources`
* ``Run `bundle install` to install missing gems.``
3. Once you are using the correct ruby version and correctly start the rails server, the following error will occur after you have logged in as either the user/moderator/admin. Any attempt to view a webpage **after** being directed to your dashboard will shut down your rails server -

![plots2](https://user-images.githubusercontent.com/44947175/68790661-8802be00-05fc-11ea-9bbe-51a40ce63190.gif)

* The server log displays - 
``/home/ec2-user/.rvm/gems/ruby-2.4.4/gems/redis-4.1.0/lib/redis/client.rb:353:in `rescue in establish_connection': Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED) (Redis::CannotConnectError)``

> What did you expect to see that you didn't?

Ideally, no errors during the installation. Practically, I would have liked to see the page regarding the link that I clicked after logging in.

### Please show us where to look

https://github.com/publiclab/plots2/blob/master/install_cloudnine.sh

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

Since this occurs in the development environment, the username is either of these three:
1. user
2. moderator
3. admin

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

![browser](https://user-images.githubusercontent.com/44947175/68787886-3146b580-05f7-11ea-8750-ab8bcf72fef3.PNG)

![windows](https://user-images.githubusercontent.com/44947175/68787895-3441a600-05f7-11ea-9fe3-359d31486246.PNG)

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Now on GitPod!
