### ISSUE TITLE
Change function t to translation in grids/_wikis

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#6775]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [_wikis.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/grids/_wikis.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

On line 18 the function t(...) needs to be changed to translation(...)
https://github.com/publiclab/plots2/blob/50b355aca3a58bdbfe5fffe6c37f0b902ee1bd00/app/views/grids/_wikis.html.erb#L18

Change to:
```<td><%= distance_of_time_in_words(Time.at(wiki.latest.created_at), Time.current, { include_seconds: false, scope: 'datetime.time_ago_in_words' }) %> <%= raw translation('wiki._wikis.by') %>```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by sharanya204** [comment]
Hi @nstjean :) could I try my hand at this one?

**Comment by nstjean** [comment]
@sharanya204 Go ahead! :)

**Comment by sharanya204** [comment]
@nstjean Quick question about who I should tag and where to request a review - is here okay? I also can't seem to tag @publiclab/reviewers, and was wondering if I was on the right track with that,

**Comment by nstjean** [comment]
@sharanya204 It looks like you did a pull request against your own repo instead of the publiclab version. See at the top of the page where it says `sharanya204/plots2` ? It should say `publiclab/plots2`

**Comment by sharanya204** [comment]
@nstjean I think I got it! Do I need to comment over at the pull request for a review?

**Comment by nstjean** [comment]
Great! I'll go take a look.

**Comment by nstjean** [comment]
PR #6780

**Comment by govindgoel** [comment]
This issue is open.

**Comment by Alexjake660** [comment]
@govindgoel Can I claim this issue?

**Comment by nstjean** [comment]
@Alexjake660 Go ahead!

**Comment by Alexjake660** [comment]
@nstjean check out my pull request please.
