### ISSUE TITLE
Change function t to translation in home/subscriptions

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#6776]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [subscriptions.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/home/subscriptions.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

In this file the following lines need to have the function t(...) updated to translation(...). There are 11 instances that need to get changed on the following lines!
https://github.com/publiclab/plots2/blob/50b355aca3a58bdbfe5fffe6c37f0b902ee1bd00/app/views/home/subscriptions.html.erb#L9
So line 9 would be changed to:
```      <a rel="tooltip" title="<%= translation('home.subscriptions.click_unfollow') %>" class="btn btn-outline-secondary active" href="/unsubscribe/tag/everything" data-method="delete"><i class="fa fa-user-plus" aria-hidden="true"></i> <%= translation('home.subscriptions.following') %> <b><%= translation('home.subscriptions.research_notes') %></b></a>```

These lines need to be changed as well:

https://github.com/publiclab/plots2/blob/50b355aca3a58bdbfe5fffe6c37f0b902ee1bd00/app/views/home/subscriptions.html.erb#L11
https://github.com/publiclab/plots2/blob/50b355aca3a58bdbfe5fffe6c37f0b902ee1bd00/app/views/home/subscriptions.html.erb#L34
https://github.com/publiclab/plots2/blob/50b355aca3a58bdbfe5fffe6c37f0b902ee1bd00/app/views/home/subscriptions.html.erb#L37
https://github.com/publiclab/plots2/blob/50b355aca3a58bdbfe5fffe6c37f0b902ee1bd00/app/views/home/subscriptions.html.erb#L58-L60

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by nstjean** [comment]
@sap143 You can do this one!

**Comment by MCElmo** [comment]
Hey, I'd like to do this.

**Comment by sap143** [comment]
Ok I will work on this

**Comment by nstjean** [comment]
Hi @MCElmo ! This one is reserved for someone else, but we will have more first time issues soon!

**Comment by sap143** [comment]
@nstjean I have opened Pull Request but its showing error message "Merging is blocked"

**Comment by nstjean** [comment]
@sap143 That's normal, the moderators do the merge after a review! I'll review your code later today if someone doesn't before then.

**Comment by Tlazypanda** [comment]
@nstjean Is this issue still available?

**Comment by nstjean** [comment]
It looks like this was completed in https://github.com/publiclab/plots2/pull/6778 but that post didn't reference this one so this wasn't closed. Sorry!

**Comment by nstjean** [comment]
Closed via #6778
