### ISSUE TITLE
Answers to Questions are truncated at 255 characters

### ISSUE THREAD

**Issue by Fastie** [publiclab/plots2#678]
### What happened just before the problem occurred
I posted an answer to a question

### Relevant URLs

https://publiclab.org/questions/shubham/08-17-2016/how-to-neutralize-remove-the-source-s-spectra-to-obtain-absorption-spectra
### PublicLab.org username
cfastie
(to help reproduce the issue)

### Browser, version, and operating system
chrome, windows

**Comment by jywarren** [comment]
Maybe the answer body text is being stored in a string column instead of a text column?

**Comment by ananyo2012** [comment]
Yes that might be the case. Just looking at it. Fixing all the issues sequentially.

**Comment by ananyo2012** [comment]
Addressed in #692
