### ISSUE TITLE
DISCUSSION: ways to follow topics on the new dashboard, for newcomers

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#6787]
**FOR DISCUSSION**
We are most of the way through a fabulous transformation into a forum of topic-focused communities. Here are a few scenarios for how new accounts registering on publiclab.org might be given or might acquire subscriptions to topic groups. This issue is an invitation for comment and reflection! Thank you and please read on: 

**1) Default subscriptions, but only to newsletter and blog**
Signup in one screen: 
- username, email, password
- checkbox for newsletter via Campaign Monitor
- checkbox to Follow the `blog`

When first time visitor arrives at publiclab.org/dashboard, they see: 
- the blog box
- the floating subscribe box that offers additional topics and links to see all topics at /tags

PROS: new signups receive PL’s highest quality, most curated content
CONS: people may never end up joining any topic groups

**2) No default subscriptions, beginning dashboard shows cards that one does not receive emails for**
Signup in one screen: 
- username, email, password
- checkbox for newsletter via Campaign Monitor

When first time visitor arrives at publiclab.org/dashboard, they see: 
- topics boxes for all recent activity on the website — but these are not subscriptions
- floating subscribe interface prompts you to subscribe in order to customize your dashboard (maybe this is at the top?)
- small link to “see all recent activity” remains on dashboard

PROS: signing up for Public Lab doesn’t immediately create email burden
CONS: topically grouped—but otherwise uncurated—feed of all activity. (maybe a PRO?)

**3) Choose topics to subscribe to at signup**
Signup moment is extended: create account as described above, and then a second screen to subscribe to topics you are interested in. 

When first time visitor arrives at publiclab.org/dashboard, they see: 
- boxes for topics they subscribed to

PROS: from the very start, topic groups are presented as the way to participate in PL
CONS: longer signup sequence introduces the potential of dropping out before signup is complete

**4) First time logged-in visitors to the site are shown a fullscreen prompt to Follow Topics**
When first time visitor arrives at publiclab.org/dashboard, they see: 
- panel of the ~18 topics with “Follow” or “Join” buttons and link to “See all Topics”
- if they do not subscribe to anything, their feed remains as Scenario 2: dashboard shows all topic boxes for all recent activity on the website — but these are not subscriptions, and the floating subscribe interface prompts you to subscribe in order to customize your dashboard

PROS: Gives more support for the first time logged-in visitor to publiclab.org to have the joining of topic groups clearly presented with an invitation. Retains the agency of choosing your own topic(s). Increased likelihood that you “recognize” an issue you care about. 
CONS: this much choice may overwhelm someone who is generally interested but perhaps not really focused on any environmental concern of personal interest

**5) Signup includes a small set of default subscriptions**
Default subscriptions are chosen to appeal to a generic new user, but how?

PROS: a minimally curated dashboard is created for every new user. 
CONS: assumes that the pre-selected topics will not be overwhelming to a person who actually may have a very specific purpose in coming to PL. Staff may fail at choosing appropriate set of default topics. 

****

**Great starts!**
Already live on the site, is a great function that when a not-logged in user clicks "Follow" on a tag page, that becomes a subscription for them once they've created an account. There's even the opportunity via the "dropdown" carrot on the Follow button to choose to follow multiple topics at a time. Thanks @IshaGupta18 and @SidharthBansal for "multi-tag subscriptions!

**** 

cc @publiclab-mimi @steviepubliclab @jywarren @joyofsoy and anyone who is interested in this workflow.

**Comment by joyofsoy** [comment]
I really like the idea of #4 with a big option for "I'll decide later" or something like that. Thanks for the pros/cons list and brain work!

**Comment by steviepubliclab** [comment]
Hi!! I like 2 to have a dashboard look active right away, but I also like 4.

**Comment by Amith1206** [comment]
Going in a bit of classical way i would recommend 3,you choose what you need at the beginning itself

**Comment by Amith1206** [comment]
5 is the kind thing were you really increase the no. of subscriptions

**Comment by jywarren** [comment]
Just wanted to note here that the question of getting emails or not may be useful to think of separately. Following can notify in different ways (like smartphone alerts vs. emails) and it would be pretty easy to add a "no emails" option in https://publiclab.org/settings!

I like 2 and 4, though my feeling is that in both, 'topics boxes for all recent activity on the website' would be too much, and we'd want to choose just a few topic to feature until people have "customized". 

Emails aside, both are similar to what i had suggested with ~5 default top-level subscriptions, but 1 main distinction: you wouldn't have to "unsubscribe" from a default set - as soon as you started following one topic, the defaults would disappear (though a topics selector could remain)

I think for me the keys are:

a) what the prompt to follow looks like
b) how much is shown on the dashboard of things you aren't actually following (too much/too little)

Finally i think the idea of showing stuff on the dashboard that appears as if it's being followed could be confusing to people, esp. if once you actually follow something, the rest disappear. One way to mitigate this could be to have a different-looking box (not a standard topic box) that shows a "mix" of recent activity in a unique style.

**Comment by ebarry** [comment]
An in-person discussion on this a few days highlighted the need to figure out an option to subscribe without receiving emails. @jywarren @steviepubliclab , has this idea made it to github yet? If so, please link here!

**Comment by ebarry** [comment]
Brainstorming language with @steviepubliclab for #4 "Add these topics to my dashboard" with a secondary box on that screen that says "Email me updates!"

Do we have an issue going anywhere about adding functionality to the subscription panel?

**Comment by jywarren** [comment]
Narrowed for the time being to:

![image](https://user-images.githubusercontent.com/24359/69755154-976a2700-1125-11ea-986c-2d6c0a0c47ba.png)

* [ ] Using a feature to top right of page to advertise events and encourage people to follow content (collapsible)
* [ ] default subscription `blog` for now
* [ ] brainstorming an area below everything which shows off either a) 3 randomly selected topics from our list of 18 feature topics, or b) 3 randomly selected posts from posts bearing special tag `featured:dashboard` (decision to come)

Thanks!

**Comment by SidharthBansal** [comment]
Sorry I missed this in piles of emails due to GCI.
This is really amazing discussion going on :heart: Let me think and tell my suggestion are fully reading it!
Thanks.

**Comment by SidharthBansal** [comment]
I really liked 2 and 4. Inclined towards 4 more than 2.

**Comment by ebarry** [comment]
For the image @jywarren  uploaded on Nov 27, showing the idea of three boxes with a randomly generated rotation from our 18 topics, the boxes currently only show a lead image and the tag name --> could these be Fullsize Topic Boxes?

Separately, where could the "firehose" of all recent content still be accessed by advanced users?

**Comment by jywarren** [comment]
Thanks!

> three boxes with a randomly generated rotation from our 18 topics, the boxes currently only show a lead image and the tag name --> could these be Fullsize Topic Boxes?

Full size topic boxes don't have an image, and these are adapting a style from individual post cards. Can you share a screengrab of what you're suggesting?

> Separately, where could the "firehose" of all recent content still be accessed by advanced users?

That would be at /research, which would remain as it looks now (although we'd probably later transition it to match tag pages like https://publiclab.org/tag/water-quality in follow-up).

**Comment by steviepubliclab** [comment]
> That would be at /research, which would remain as it looks now (although we'd probably later transition it to match tag pages like https://publiclab.org/tag/water-quality in follow-up).
This brings you to the current dashboard no? Is this because you would get all activity in your feed if you're not subscribed to something anyway?

**Comment by jywarren** [comment]
No, sorry - /research used to be a clone of the dashboard, but at some point i guess we just redirected. I meant basically the full firehose feed, and that we could basically keep the current dashboard code for that purpose. 

Alternatively we could just ditch the current dashboard entirely and revert to some modified version of the display at https://publiclab.org/tag/water-quality but showing all content?

**Comment by jywarren** [comment]
Just to finalize this, I'm going to add a feature to the bottom of the new dashboard main column where we can put different designed ideas for advertising topics, with images and everything. It'll get pushed down as people add subscriptions.

Once we decide on a display we like, we can code up something less manual!
