### ISSUE TITLE
Drag and dropping photos fails in comments on questions

### ISSUE THREAD

**Issue by Fastie** [publiclab/plots2#679]
### What happened just before the problem occurred
dragged a photo into a comment (not an answer) to a question

### Relevant URLs

https://publiclab.org/questions/shubham/08-17-2016/how-to-neutralize-remove-the-source-s-spectra-to-obtain-absorption-spectra

### PublicLab.org username
cfastie
(to help reproduce the issue)

### Browser, version, and operating system
chrome, windows

**Comment by ananyo2012** [comment]
@Fastie actually I have designed the comments for asking any clarifications or conversation. It just has limited markdown support. For detailed explanations like using images please choose to answer.

**Comment by Fastie** [comment]
That's a fine solution, except that everywhere else at publiclab.org you can drop an image (and other types of files) into a comment. So this introduces some inconsistency.

**Comment by ananyo2012** [comment]
Yes actually Q & A pages have a slightly different structure than other notes and wiki pages. You can see the answer editor in the Q & A pages supports the toolbar which is unlike to the comment editor in notes pages where the toolbar is absent. I will sum up a complete documentation on the Q & A pages in a wiki soon.

**Comment by ananyo2012** [comment]
@jywarren Should we close this since I intended to use comments for conversations or clarifications in Q & A pages?

**Comment by jywarren** [comment]
I think so -- perhaps if we do a comments overhaul using the new rich editor code, we could revisit, and this could be revised to be a proposal for such a new feature.
