### ISSUE TITLE
Add questions asked vs asked status bar in tag/topic page

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#6790]
Sub task of https://github.com/publiclab/plots2/issues/2120.

### Description
---------------------
Add a questions asked vs answered rate  on https://publiclab.org/tag/community/stats. We should reuse the dat picker there to calculate the rate while calculating the other existing metrics.

We already have a silmilar status bar here ![Screenshot from 2019-11-17 12-22-22](https://user-images.githubusercontent.com/17081074/69005570-10eb6380-0935-11ea-8aa9-236fd2765749.png)  on https://publiclab.org/stats?options=Past+year and you can reuse the idea used there. 

### Where to find Logic and templates 
--------------------------------------------------------
We get the questions vs answers with like this https://github.com/publiclab/plots2/blob/master/app/controllers/stats_controller.rb#L28-L34

The graph code can be found here... https://github.com/publiclab/plots2/blob/master/app/views/stats/index.html.erb#L259%20-L326 .
You could extract this as a partial and reuse for the two views.

The view that we need to add the status bar is https://github.com/publiclab/plots2/blob/master/app/views/tag/stats.html.erb and its action in controller is https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L524-L535

**Comment by nstjean** [comment]
Hi, can I help with this, or is it reserved for something?

**Comment by cesswairimu** [comment]
Hey @nstjean, please go ahead. Feel free to ping me in case of anything. Thanks

**Comment by nstjean** [comment]
When I go to /tag/community/stats in local it's giving me an error. Might have to do with the cache?

![FireShot Capture 064 - Action Controller_ Exception caught - localhost](https://user-images.githubusercontent.com/49460529/69159032-4f0f9100-0ab5-11ea-8d38-8bfe038062d6.png)

**Comment by nstjean** [comment]
I figured it out... in local I have nothing with the tag "community". If I go to a different tag it works. The page should probably display a nicer error for "nothing found with the tag ___" instead!

**Comment by jywarren** [comment]
Good catch and great idea!
