### ISSUE TITLE
Weekly community Check-In #39 - "Ask for help!" 

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#6792]
Hi everyone 👋
We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. 💯

## Ask for help! 🆘 

So GCI will start from next month and there will be amazing amount of energy that the young coders will bring in. 
As a mentor, it is our responsibility to guide them in the right direction so they can proceed in their tasks. There may come a time when as a mentor you have no clue as of what to do in that task (wihch is normal 😄 ), during that point of time - "ASK" other mentors/maintainers to chip in and guide instead of pointing the student in the wrong direction!

**Comment by sagarpreet-chadha** [comment]
@gauravano @milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @shubhscoder @sidntrivedi012 @SidharthBansal @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77

**Comment by sagarpreet-chadha** [comment]
@ananyaarun @ananya @publiclab-mimi @ananya @hc-barker @starkblaze01 @asquare@pdurbin @HarshKhandeparkar@newbazz @aSquare14 @vaarigupta @alonpeer @aashna27 @harshithpabbati @jesus-montano@cryptoclidus @mohamed-elalem @konolga @gowtham5699@jywarren @ebarry @steviepubliclab @StlMaris123, @tauhir, @augustozanellato, @nstjean, @stefanosu, @alexido19, @Akashutreja, @fadib, @skai-ste, @mahimahans111, @Lisa-Caton, @pkayres, @JeffOgah, @IvetaHron, @Linda-Ikechukwu, @crisner, @vishakhanihore, @shailzaa, @saivoleti17, @chrisnorwood, @DanielKlys7, @Diegoafv, @saramace, @lojosmit, @kyebrowning, @jon-flores

**Comment by sagarpreet-chadha** [comment]
@jywarren @gauravano @cesswairimu @ebarry

**Comment by SidharthBansal** [comment]
Hello everyone,
Update: 26 tasks published.
Other 9 draft tasks are having some minor problems, so I can't publish them
Minimum requirement of tasks to be published before 1 Dec is 100 tasks. Please make as many tasks as you can before 1 Dec to participate in GCI and win exciting prizes.

I hope you all understand it is very important to do 100+tasks to get into GCI. 
Thanks
Sidharth

**Comment by ebarry** [comment]
Hi all, i'm committing to organizing issues into Milestones to help us streamline on which fronts we will be making progress at any one time. Thanks to @cesswairimu ' the Metrics Milestone is already 95% done! :D

**Comment by jywarren** [comment]
Hi all! I'm so impressed with the GCI organizing going on. I've been trying to prepare our Geographic Features milestone for the upcoming Outreachy season, here!

https://github.com/publiclab/plots2/milestone/7

And preparing a set of new issues for it here!

https://github.com/publiclab/plots2/issues/6801

Thanks everyone for all your hard work! 🙌

**Comment by SidharthBansal** [comment]
Great

**Comment by SidharthBansal** [comment]
![image](https://user-images.githubusercontent.com/20972099/69496604-ea5f9680-0ef9-11ea-9862-4daa92e27b4a.png)
Hello, we still need 60 more tasks in GCI dashboard. Is there anyone willing to help to mark issues as GCI-reserved and ping me so that I can upload and publish them on GCI website?
Thanks!

**Comment by cesswairimu** [comment]
Hello, anyone interested in opening this week's check-in?

**Comment by pydevsg** [comment]
Hi @cesswairimu I am interested in opening this week's check in

**Comment by cesswairimu** [comment]
Great :tada: :tada:  @pydevsg, please do..and ping me if you need anything to open it

**Comment by pydevsg** [comment]
Okay thanks @cesswairimu I will ping you up when needed :)

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/6845. Thanks all :heart:
