### ISSUE TITLE
Fix pluralization logic

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/plots2#6797]
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

What's supposed to happen:

On a person's profile page the count of research notes at the top are pluralized incorrectly (should be 1 research _note_).

![image](https://user-images.githubusercontent.com/41092741/69061191-aeeb3680-09e6-11ea-8c87-83337b3c6ce3.png)

## Solution

This is a simple one -- lets find the relevant line of code first: 
https://github.com/publiclab/plots2/blob/6aad7435e1efff7eaf2fe3cedc862cb4aed5a791/app/views/users/profile.html.erb#L13

as you can see, this line has no conditional and this person will just always have plural research notes.
 
```kotlin
<%= @profile_user.name %>'><%= @profile_user.note_count %> research notes </a>
```
Lets help him out:

```JS
 <h5><a href='/notes/author/<%= @profile_user.name %>'><%= @profile_user.note_count %><%= @profile_user.note_count == 1 ? ' research note' : ' research notes' %></a>
```

Use the resources I have given you above to fix this bug, and then open a PR

Thanks!!

## Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/plots2](https://github.com/publiclab/plots2)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by sashadev-sky** [comment]
assigned to @swathi-0901!

**Comment by ChamuMutezva** [comment]
has #6797 been taken?

**Comment by swathi-0901** [comment]
> assigned to @swathi-0901!

Yea I claimed it.

**Comment by sashadev-sky** [comment]
@ChamuMutezva would you like me to make you one as well?

**Comment by ChamuMutezva** [comment]
@sashadev-sky, yes please, i need one

**Comment by sashadev-sky** [comment]
Ok I will ping you in a bit! @ChamuMutezva

**Comment by sashadev-sky** [comment]
@ChamuMutezva just assigned you to #6809

**Comment by ChamuMutezva** [comment]
@sashadev-sky, thanks, i will be working on it today.
