### ISSUE TITLE
Make tag header images scale smoothly in mobile/desktop

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6799]
We have these nice image headings for tag pages:

https://publiclab.org/tag/water-quality

They're based on this [Froala design block](https://www.froala.com/design-blocks) pattern:

![image](https://user-images.githubusercontent.com/24359/69076085-b1f32080-0a00-11ea-9f2d-971c6bc6537b.png)

However, ours aren't built the same way and don't smoothly/responsively transition between full-width and mobile sizes. There are some where the image is cut off, or messed up. Let's look back at the original design and code to try to standardize and fix this! 

Code for the original Froala block was:

```html
<section class="fdb-block pb-0" style="background-image: url(imgs/hero/purple.svg);">
  <div class="container">
    <div class="row text-left justify-content-end">
      <div class="col-12 col-md-6 col-xl-5">
        <div class="fdb-box rounded-bottom-0">
          <h2><strong>Design Blocks</strong></h2>
          <p class="lead">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>

          <p class="lead mt-4"><a class="btn btn-outline-primary" href="https://www.froala.com">Read More</a></p>
        </div>
      </div>
    </div>
  </div>
</section>
```

I believe the full code can be found somewhere here:

https://github.com/froala/design-blocks/tree/dev/dist

Our code is here:

* https://github.com/publiclab/plots2/tree/master/app/views/tag/show.html.erb
* https://github.com/publiclab/plots2/tree/master/app/views/tag/show/

We'd love help fixing this!

**Comment by jywarren** [comment]
Example - this looks nice!

![image](https://user-images.githubusercontent.com/24359/69076257-17dfa800-0a01-11ea-8c26-c62f693912cb.png)


But this doesn't! the image disappears!

![image](https://user-images.githubusercontent.com/24359/69076282-229a3d00-0a01-11ea-8d1e-8c2ecf337ffc.png)

**Comment by jywarren** [comment]
See a lot of background work and documentation on this in https://github.com/publiclab/plots2/issues/6054 !

**Comment by jywarren** [comment]
I was able to get that type of header to work using this CSS: `<link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/froala-design-blocks/2.0.1/css/froala_blocks.min.css">`

However, it messes up the fonts! Trying to figure that out now.

**Comment by jywarren** [comment]
OK - I am able to get this work by re-including the main stylesheet like this:

```html
<link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/froala-design-blocks/2.0.1/css/froala_blocks.min.css">
<link rel="stylesheet" media="all" href="/assets/application-08768cdbfbde532afe88f0b458bc1767de7799ff598f2d54f6b0229e2f76e703.css" />
```

Obviously this isn't great. If we can confirm that the froala css doesn't break things all over the site, we could add it to the `<head>` and not have to re-include the main stylesheet... but we'll have to be really thorough to check the screenshots at different sizes and all!

**Comment by NitinBhasneria** [comment]
hey @jywarren I would like to take this issue! Can I?

**Comment by jywarren** [comment]
Oh goodness, we'd LOVE that. This area of code can be much simpler and more
consistent!

**Comment by NitinBhasneria** [comment]
@jywarren I think that the water quality box also needs to be fixed with responsiveness. What are your views? Also, we can cover more screen width as this is not looking nice to only cover the center part. Thank u

**Comment by NitinBhasneria** [comment]
> Example - this looks nice!
> 
> ![image](https://user-images.githubusercontent.com/24359/69076257-17dfa800-0a01-11ea-8c26-c62f693912cb.png)
> 
> But this doesn't! the image disappears!
> 
> ![image](https://user-images.githubusercontent.com/24359/69076282-229a3d00-0a01-11ea-8d1e-8c2ecf337ffc.png)

This is what I mean .... that it is looking nice when image cover whole backgound rather than only center part as this... given below

**Comment by NitinBhasneria** [comment]
![Screenshot from 2020-01-17 22-57-26](https://user-images.githubusercontent.com/44112080/72632664-c0b47000-397c-11ea-8776-e5ba8b71276d.png)

**Comment by jywarren** [comment]
Hi, well, did you see my link to how the front page at https://publiclab.org
works (when you're not logged in)? It uses Froala Design Blocks. Theirs
scales smoothly and super nicely at every size, and our design was based on
it. I would really hope we can just use their standard code instead of
reinventing the wheel, what do you think?

**Comment by jywarren** [comment]
Yes, i wanted to agree also that we want the background image to be edge-to-edge the whole time. The Froala code achieves this, as shown on our front page! 

In the meantime, our pages are degrading a bit, some change must have affected the styling and now they are pretty bad!

https://publiclab.org/tag/annual-report

![image](https://user-images.githubusercontent.com/24359/72906277-f56b5300-3cff-11ea-8b0d-ce9fa964d04a.png)

@NitinBhasneria would you be willing to give this a try? I think the first step is to try to use the code from our front page, which I'll excerpt here:

```html
<link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/froala-design-blocks/2.0.1/css/froala_blocks.min.css">
<link rel="stylesheet" media="all" href="/assets/application-08768cdbfbde532afe88f0b458bc1767de7799ff598f2d54f6b0229e2f76e703.css" />
    
   <section class="fdb-block pb-0" style="background-image: url(/system/images/photos/000/024/688/original/gowanus.jpg);position:absolute;left:0;width:100%;margin-top:-21px;height:360px;padding-top:3rem;">
   <div class="container">
   <div class="row text-left justify-content-start">
   <div class="col-12 col-md-6 col-xl-5">
   <div class="fdb-box rounded-bottom-0" style="padding:2.8rem 2.5rem 1.2rem;">
   <h1>Public Lab</h1>
   <p class="lead" style="font-size: 1rem;">Public Lab is a community and a non-profit, dmocratizing science to address environmental issues that affect people.</p>
   <p class="lead mt-4"><a class="btn btn-lg btn-primary front-page-join-btn" hef="/signup">Join &raquo;</a></p>
   </div>
   </div>
   </div>
   </div>
   </section>
```

**Comment by NitinBhasneria** [comment]
Yea I will give it a try

**Comment by NitinBhasneria** [comment]
@jywarren I have found the solution of the edge-to-edge background image. I first tried the Froala design as on the front page. But using this will disturb many CSS classes and the given Froala design is also little unuseful of these tag pages, as this has extra buttons and all the things and many errors are coming. **Instead of this we can change some little CSS and page can be made like front page.**
So, please tell what to do. Whether the Froala design is necessary or should we do with CSS. As doing with CSS will be better from my side.

**Comment by jywarren** [comment]
Hi, thanks so much! Can you open a PR with this so I can take a look at your changes? I think a non-Froala design is OK, but one reason I also liked Froala is that the HTML code was much simpler too. 

Thank you!

**Comment by NitinBhasneria** [comment]
@jywarren kindly review this, by this the image now edge to edge.
The disappearance of the image will be fixed in other PR.
Thanks
