### ISSUE TITLE
Preserve the /zoom/ of the map in the /post button from an inline map

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#6804]
## SOLUTION STEPS: 

1. Calculate zoom from map using leaflets getZoom API.

2. Pass zoom:X in the URL of button onClick()

3. Parse the URL in the editor controllers corresponding action and save it in @zoom variable.

4. Pass zoom param similar to lat and lon:

https://github.com/publiclab/plots2/blob/6aad7435e1efff7eaf2fe3cedc862cb4aed5a791/app/views/editor/rich.html.erb#L315

5. In PL.EDITOR, in mapModule , use the Leaflet Blurred Object and use its API to set Zoom of the map.

Thanks!

**Comment by nfarve** [comment]
Hi! Can I claim this?

**Comment by jywarren** [comment]
Hi! We'd love help with this! It's a bit convoluted, so if you'd like to take a first-timer issue we def. understand. But @sagarpreet-chadha just did part of this in this pull request:

https://github.com/publiclab/plots2/pull/6591/files#diff-febd74b4f018c188d3912fc496d3a037R30-R32

And, the workflow to add `zoom` to this using the Leaflet API should be not too much different in that same file. 

(ref https://leafletjs.com/reference-1.4.0.html)

Then, I think we'll have to make changes to the editor similar to how Sagarpreet did it for latitude/longitude:

https://github.com/publiclab/plots2/blob/39115b4562b3f462bd04d8f4d5539c507d67177f/app/views/editor/rich.html.erb#L314-L317

Finally, we'll have to modify the editor itself to accept the zoom values and actually use them; we can follow what Sagarpreet did there too - although it's in a separate repository:

https://github.com/publiclab/PublicLab.Editor/pull/349

We're happy to have your help at any one of these spots, or all -- but I think in the order I laid out, we can solve them one at a time without needing to do all 3 in one coordinated change. 

Thanks a ton! 🎉

**Comment by nfarve** [comment]
@jywarren I think I understand what needs to happen. I will let you know if I have questions.

**Comment by sagarpreet-chadha** [comment]
Awesome!

**Comment by jywarren** [comment]
Hi @nfarve it looks like perhaps you've started work on the next section? If so, please open a PR so that folks can see that you have, both so someone else doesn't redundantly start on this, but also in case you need any input as you go! Thanks again for taking this one on! Very exciting.

**Comment by nfarve** [comment]
👋 @jywarren I think I have a working branch, but I a little confused on where this lives on the actual website. Can you walk me through the steps of how to view this feature in a local version on the website?

**Comment by jywarren** [comment]
Sure, you can see the button in action on this page: https://publiclab.org/wiki/sandbox-3

And, if you make a wiki page locally, you can get the same kind of map to appear by using this shortcode:

```
[map:layers:content:41.5:-71.5:odorreport,pfasLayer,Unearthing,toxicReleaseLayer]
```

That opens a map with those layers at that location. Thanks!!!

**Comment by jywarren** [comment]
I believe this is now complete!
