### ISSUE TITLE
Admins/Moderators cannot add profile tags to other people's profiles

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#6805]
### Please describe the problem

As a site Admin, i help organize people, and the primary way that i group people for potential further support is by adding tags to their profile page. The best example of this is that i add an "education" tag to teachers, professors, workshop leaders and similar people who are involved in educational initiatives. 

For the past several months i have not been able to add a tag to someone else's profile page, even though my account is an Admin account. When i try to type into the profile tag box and press "enter", the box turns grey, the tag does not appear, and upon refresh the tag is not there. See gif: 
![profile tagging](https://user-images.githubusercontent.com/161439/69091000-65670f80-0a17-11ea-96f5-910ed6564bf2.gif)

> What did you expect to see that you didn't?

I expect to be able to type a tag into the "Add a Tag" box on someone's profile page and have the tag be added. 

### Please show us where to look

https://publiclab.org/profile/zengirl2

### What's your PublicLab.org username?
liz

**Comment by ebarry** [comment]
Thanks for checking this out @StlMaris123 !!!! Great to see you here, hope you have been well 🙂

**Comment by jywarren** [comment]
This is solved; i just tested it on the live site. I think we should modify this issue or post a follow-up to write a test to protect this functionality; i believe this is now done by @nstjean in 
  https://github.com/publiclab/plots2/pull/6951 as well. Thanks!
