### ISSUE TITLE
"Last Edited" date is inconsistent, as shown on wiki and profile records

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#6806]
### Please describe the problem (or idea)

> What happened just before the problem occurred?

A great contributor from Brasil wrote into the list to highlight their wiki page https://publiclab.org/wiki/tortuga-guardian which displays an edit date at top of "Last edited by GSan 2 months ago." When i clicked through to the author's profile page https://publiclab.org/profile/GSan , the page is listed as having been edited a few hours ago -- see gif: 

![edit-date-bug](https://user-images.githubusercontent.com/161439/69091279-f1793700-0a17-11ea-97e3-646c785af380.gif)

> What did you expect to see that you didn't?

I expected that the dates would be the same between the content editing logs and the profile activity log. 

### Please show us where to look
https://publiclab.org/wiki/tortuga-guardian 
https://publiclab.org/profile/GSan

### What's your PublicLab.org username?
liz
Thank you!

**Comment by SidharthBansal** [comment]
Published on GCI dashboard!
Thanks Liz

**Comment by fluctix** [comment]
Can I work on this issue, even thoughmy task has still not been approved?

**Comment by SidharthBansal** [comment]
One task at a time is allowed. However you can do supportive tasks if you
are free :-)

**Comment by fluctix** [comment]
Ok

**Comment by Tlazypanda** [comment]
@SidharthBansal I think this issue is resolved since the links now display the revision correctly :sweat_smile:

**Comment by SidharthBansal** [comment]
Thanks
