### ISSUE TITLE
Error in transifex translation()

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6807]
Hi @gauravano @cesswairimu @nstjean I wanted to see if the three of you might be able to figure out this 

https://github.com/publiclab/plots2/blob/master/config/locales/en.yml#L205 looks pretty simple.

But it's causing this oddity: 

![image](https://user-images.githubusercontent.com/24359/69096522-9ac52a80-0a22-11ea-9ab9-54ae50d18d19.png)

Here's the line of code; we swapped `t(` for `translation(`

https://github.com/publiclab/plots2/blob/a5d3392c3d6f5f4daaa56d5a4431e1bc0de5c46c/app/views/notes/_comments.html.erb#L4

In this PR: https://github.com/publiclab/plots2/pull/6766/files

Do we need to use `<%=raw %>` so that any HTML that's replaced gets better formatted? Or, what is going on here? 

Thanks all!!!

**Comment by jywarren** [comment]
Uff, here's another related error further down the same page!!!

![image](https://user-images.githubusercontent.com/24359/69097679-0d370a00-0a25-11ea-9faa-bebd1748986e.png)

**Comment by jywarren** [comment]
That's on this page!

**Comment by nstjean** [comment]
Oh dear!! I'm taking a look at that page, I'm not seeing an error on my PC or mobile! So I'm not sure why it would be showing only sometimes?

![FireShot Pro Screen Capture #023 - 'Arrow Down Icon I Font Awesome' - fontawesome_com](https://user-images.githubusercontent.com/49460529/69101032-85ed9480-0a2c-11ea-8bf5-912ef875348f.png)

**Comment by jywarren** [comment]
Oh hm, do you think it only happens when you're using another language? You
can switch in the footer...

**Comment by nstjean** [comment]
For me it looks the same under any language. Hmm. But nothing on the page changes to a translated text, is that normal?

**Comment by cesswairimu** [comment]
Like @nstjean, I also cannot  replicate this....which page is this @jywarren?

**Comment by ebarry** [comment]
It is from this link: https://publiclab.org/notes/Bronwen/11-18-2019/fall-workshops-in-nyc-oil-gas

**Comment by jywarren** [comment]
@ebarry do you see it? I see it when set to Spanish, and saw it on my laptop and phone. But when I switch to English it's fine!

**Comment by jywarren** [comment]
Yes, i can replicate it on that page. It's also happening in a couple other places, mostly where the translation overlaps a button or some other HTML. 

![image](https://user-images.githubusercontent.com/24359/69157853-88df9800-0ab3-11ea-9fd9-bdb6decc6a0a.png)

I wonder if the translation helper itself needs a `<%=raw %>` or `.html_safe` to stop the HTML from getting flattened?

https://github.com/publiclab/plots2/blob/1e0eba7eb917784717cccc19783fee250a1d2d99/app/helpers/application_helper.rb#L140-L151

https://apidock.com/rails/String/html_safe

Actually it recommends using `raw()` on the string, which marks it as safe to not escape. Let's try that.

**Comment by jywarren** [comment]
Noting that to switch languages locally is `/change_locale/es` (for spanish)

**Comment by jywarren** [comment]
hmm, i can't seem to switch locally... strange. can anyone else? As this is a priority, maybe we should go ahed and implement this as it's a pretty small change. I don't like publishing it without being able to check, though.

**Comment by jywarren** [comment]
Unfortunately the staging and unstable servers are down, will fix them thursday with luck. 

https://github.com/publiclab/plots2/pull/6813 - if anyone can try this out that'd be great!

**Comment by jywarren** [comment]
I'm going to give it a try!!!

**Comment by nstjean** [comment]
Fingers crossed!

**Comment by jywarren** [comment]
Solved! Thanks, all!!!

![image](https://user-images.githubusercontent.com/24359/69442077-f0971c80-0d19-11ea-8ac7-866f2c9b8867.png)
