### ISSUE TITLE
Welcoming GCI Students

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#6808]
# Welcome GCI Students 🥇

Hi everybody 😃 !

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯. You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️ .We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. 💯

## About Google Code-In 👨‍💻 
Google Code-in (GCI) is an annual programming competition hosted by Google LLC that allows pre-university students to complete tasks specified by various, partnering open source organisations. A global, online contest introducing teenagers to the world of open source development and an opportunity for beginners to jump in and get started no matter what skills they have. Participants get to work on real software and win prizes from t-shirts to a trip to Google HQ!
PublicLab Welcomes all GCI Students, :tada: :balloon: 

In order to score points, students are required to complete tasks. So, What are tasks ?
**Tasks**- A task is a small project that is expected to take between 3-5 hours of work to complete. Tasks are categorised with the following labels:
 - **Code**: Tasks related to writing or refactoring code 👨‍💻 
 - **Documentation/Training**: Tasks related to creating/editing documents and helping others learn more 📝 
- **Outreach/Research**: Tasks related to community management, outreach/marketing, or studying problems and recommending solutions 👨‍🔬 
- **Quality Assurance**: Tasks related to testing and ensuring code is of high quality 🔨 
- **Design**: Tasks related to user experience research or user interface design and interaction 🎨 

The following scoring system will be used for grading your tasks throughout all the repositories participating in Google Code-In. 💯  
In case you find any task without a score, then immediately inform either me or any mentor to know its score. 👍

## GCI Scoring System
 - **Beginner Level Task(1pt): -** Installation Tasks, First-Time-Issues, Typographical Errors, HTML-CSS, etc.  Try to use `First-Timers-issue` format ONLY if you are creating such tasks. Duration: 3 days.
 - **Medium Level Task(3pt) -** Simple challenging tasks like methods, tests, designs, demos, documentation(if small) etc. Duration: 5 days.
. ⛑ 
 - **Hard Level Task(5pts) -**  New feature, research, Documentation(long or difficult for high school students to understand and write), etc. Duration: 7 days.
🥇 
 - **Supportive Task -** Bug Reporting(1pt/task) 🐞 , Creating "First-Timer-Issues"(1pt/task), Suggesting New Changes(if accepted, 1pt/change) 💡 , Add Code Linking(1pt/task) 🔗 , PR reviews (1pt/week, however if the mentor that mentee is too helpful, 2 pts can be provided at max) ✔️  📜 , adding a screenshot to existing PRs(1pt/task), etc.

- **Hall-of-fame Tasks(15pt)**: Wontfix issues. Jeff/me will ONLY make/publish these tasks. Duration: 10 days.
Please refer: https://github.com/publiclab/plots2/wiki/Supportive-Tasks.
If anyone finds any task exceeding complex, then we can enhance the scores too :-)

We strongly encourage students to participate in the Weekly community check-ins for regular updates 👯‍♂ 

**One Installation Task & "First-Timer Issue" is a compulsion for all students.** 💯 Mentors are requested to guide the students in this direction.
**Supportive tasks** can be done multiple times by each student. You will get points for each of the supportive tasks. 👍 
We will be having a form at the end of GCI where you have to fill all the details of the tasks. You can mention all your extra supportive tasks there.

In case of any doubts, feel free to contact  [@SidharthBansal](https://github.com/SidharthBansal)  or other mentors here or on gitter!  🖌May you have an awesome journey ahead !!! 🎈 ❤️ 🎉

Students can ping the mentors of the respective repos or projects in order to seek help or guidance. 🎉 👍 👨‍💻
ALL: @jywarren
Mapknitter: @gauravano, @SidharthBansal, @sashadev-sky @IshaGupta18, @cesswairimu  @divyabaid16
Plots2: @gauravano, @SidharthBansal, @IshaGupta18, @ananyaarun, @pydevsg, @sashadev-sky, @cesswairimu 
SWB: @gauravano, @SidharthBansal, @cesswairimu  @sidntrivedi012
simple-data-grapher: @IshaGupta18, @pydevsg, @debck, @rexagod @ananyaarun 
LEL: @sagarpreet-chadha @ananyaarun, @rexagod @IshaGupta18 
IS: @keshav234156, @debck, @subhahu123, @rexagod
LDI: @sashadev-sky, @rexagod
LBL: @rexagod
PublicLab.Editor: @ananyaarun  @rexagod @IshaGupta18 @divyabaid16
image-sequencer: @rexagod @lohitha02
spectral-workbench.js: @sidntrivedi012 @ananyaarun 
infragram: @divyabaid16 @rexagod @ananyaarun 

GCI students will be evaluated on the basis of total points, friendliness, and collaboration skills. We will be circulating a form to be filled by all the GCI students. This form will include their tasklist and expected total points. So, all students are requested to note down the issue number, pr number, scores of the task, etc. whichever they would solve in GCI.
**Note:** Students who will miss filling the final form will not be evaluated for prizes. So, please don't forget to fill the form at the end week of GCI.
Student grade sheet self-evaluation forms will be active in last week of GCI. 🚀 

**All GCI Students are requested to say HELLO in this issue as this issue is the place for all the announcements.**
Thanks,
Sidharth

**Comment by CoderJolly** [comment]
Students can ping the mentors of the respective repos or projects in order to seek help or guidance. 
**All Repos/Projects -** @jywarren 
**Mapknitter -** @gauravano , @SidharthBansal , @sashadev-sky , @IshaGupta18 , @cesswairimu , @divyabaid16
**Plots2 -** @gauravano , @SidharthBansal , @IshaGupta18 , @ananyaarun , @pydevsg , @sashadev-sky , @cesswairimu
**Leaflet-Environmental-Layers -** @ananyaarun , @rexagod , @IshaGupta18 
**Simple-Data-Grapher -** @IshaGupta18 , @pydevsg , @debck , @rexagod 
**PublicaLab.Editor -** @rexagod , @IshaGupta18 , @divyabaid16
**Infragram -** @divyabaid16 
**Image-Squencer -** @rexagod , @lohitha02 
**Spectral-Workbench.js -** @sidntrivedi012 
**SWB -** @gauravano, @SidharthBansal, @cess @sidntrivedi012
**IS -** @keshav234156, @debck, @subhahu123, @rexagod
**LDI -** @sashadev-sky, @rexagod
**LBL -** @rexagod

**Comment by CoderJolly** [comment]
@namangupta01 @jywarren @ViditChitkara  @ananyaarun @aSquare14 @cesswairimu @CleverFool77 @debck @Divy123 @divyabaid16 @ebarry @gauravano @harshithpabbati @IshaGupta18 @geekychasser @lohitha02 @keshav234156 @newbazz @rexagod @rishabhptr @sagarpreet-chadha @samagragupta @sashadev-sky @sidntrivedi012 @vaibhavmatta @subhahu123 @StlMaris123 @starkblaze01

**Comment by CoderJolly** [comment]
Students can ping the mentors of the respective repos or projects in order to seek help or guidance. 🎉 👍 
ALL: @jywarren
Mapknitter: @gauravano, @SidharthBansal, @sashadev-sky @IshaGupta18, @cess @divyabaid16
Plots2: @gauravano, @SidharthBansal, @IshaGupta18, @ananyaarun, @pydevsg, @sashadev-sky, @cess
SWB: @gauravano, @SidharthBansal, @cess @sidntrivedi012
simple-data-grapher: @IshaGupta18, @pydevsg, @debck, @rexagod
LEL: @ananyaarun, @rexagod @IshaGupta18
IS: @keshav234156, @debck, @subhahu123, @rexagod
LDI: @sashadev-sky, @rexagod
LBL: @rexagod
PublicLab.Editor: @rexagod @IshaGupta18 @divyabaid16
image-sequencer: @rexagod @lohitha02
spectral-workbench.js: @sidntrivedi012
infragram: @divyabaid16

**Comment by IshaGupta18** [comment]
Hey Everyone! GCI Candidates are welcome to contribute to our repositories! They are requested to read some of the issues pinned here: https://github.com/orgs/publiclab/teams/gci/discussions?pinned=1

**Comment by chen-robert** [comment]
@IshaGupta18 The link https://github.com/orgs/publiclab/teams/gci/discussions?pinned=1 doesn't seem to work for me. It gives a 404 error for some reason

**Comment by keshav234156** [comment]
@chen-robert sorry for the inconvenience caused to you.Actually it's GCI mentor group and all the discussion that are present in that group are only accessible by the mentors

**Comment by SidharthBansal** [comment]
ALL GCI STUDENTS ARE REQUESTED TO GET THEIR PR REVIEW TASK APPROVAL FOR WEEK 1 FROM KESHAV
@keshav234156

**Comment by SidharthBansal** [comment]
PR Review grading will be done after each week.
1st week by @keshav234156 
2nd week by @pydevsg 
3rd week by @IshaGupta18 
4th week by @ananyaarun 
more soon
All GCI students are requested to leave a hello in this issue

**Comment by SidharthBansal** [comment]
We are aiming at a Supportive community at PL. So, we will be giving 1pt/week per repository to the students who will help in reviewing the PRs which are not reviewed yet.
Students are requested to write descriptive comments so that the creator of PR facing any trouble can resolve the problems in their PR. Yes, we want students to behave as mentors and review PR. 🎉 
🚀 
Student can do ALL supportive tasks along with their current task. Students can get points for these tasks after completion of the week.
For week i they will get marks in week i+1.
For the last week, get points in the last week itself.
These supportive tasks are made so that students can be busy while their tasks are under review by the mentors. You can check other supportive tasks too.
All students can do as many as supportive tasks as they want. They will get points for all of them.
Example, X opens 100 FTOS then X will get 100 points. We will circulate a form at the last week where you all have to write about these supportive tasks.


In case of any doubts, please feel free to ask here.

**Comment by SidharthBansal** [comment]
All students are requested to get PR review task in week i+1 for week i. We will `delete week i PR Review task per repo in week i + 2`.
We want all of you to secure a lot of points due to these tasks.
Tip: There are many tasks labelled with `fto-candidate`. If you change them to `first-timers-only` issue using fto templates, then you will get 1pt/fto.

Best of luck :-)

**Comment by Uzay-G** [comment]
Hello I am participating in GCI

**Comment by anthony-zhou** [comment]
Hello! I'm participating in Google Code-in, and I'm excited to help out here. It looks like the task system here is separate from the GCI tasks dashboard, where you have to wait for one task to be approved before moving on to the next. 

Is it alright to work on multiple PRs at the same time here on GitHub (just while waiting for the others to be reviewed)?

**Comment by sashadev-sky** [comment]
@anthony-zhou you're technically allowed to work in multiple on Github, but if another student gets the issue on the dashboard it's theirs. 

It's not a good situation when a participant claims a task that already has a PR up for it by a participant that didn't claim (this has already happened ). So I would say please don't officially open the PR on Github until you get the issue on dashboard (keep your changes local).

**Comment by SidharthBansal** [comment]
Hello, glad to meet you.
You can take multiple supportive task with existing claimed task on the
dashboard. But you can't open prs for two gci non supportive tasks
simultaneously.
Supportive tasks are meant to keep you busy while mentors are reviewing
your prs.

**Comment by SidharthBansal** [comment]
We will be giving points who are actively reviewing prs throughout the week. I observed some students write a single comment and are asking for approvals. We want GCI students to learn about reviewing prs too. Writing a single comment will give you points but you all will not be able to learn. So, I will advise students to review as many prs as possible.
Thanks

cc/ @chen-robert @Uzay-G @VladimirMikulic @Ugtan @anthony-zhou 
Can you guys write GitHub handle of all the GCI students you know in this post? Please don't write handles that are already present in this post.
I want all the Github Handle so that all the announcements done in this post are reached to them.

Mentors, please do it @keshav234156 @ananyaarun @sashadev-sky @pydevsg @IshaGupta18

**Comment by SidharthBansal** [comment]
Sorry I don't know Github handle of all the GCI students. So, I want your help.
Thanks

**Comment by Uzay-G** [comment]
@fluctix @HarshKhandeparkar @genesis331

**Comment by dotangad** [comment]
Hello! I'm Angad - a sophomore participating in Google Code-In. I just finished my first task and I'm about to claim my next. My email is [mail@angad.dev](mailto:mail@angad.dev), I am also on the Gitter channel as @dotangad.

**Comment by CodeSarthak** [comment]
Hey! I am Sarthak. I am participating in GCI for Public Lab. I participated for Public Lab last year too and I finished seventh in the leaderboards. 

Feel free to dm me on Gitter or mail me at getsarthakaggarwal@gmail.com

Looking forward to working with everyone :)

**Comment by HarshKhandeparkar** [comment]
Hi! I am Harsh. I have been participating in gci for the last years. I learnt about publiclab via gci last year and I have been contributing to the ImageSequencer ever since. One of the main reasons why I stayed back and continued contributing is the welcomng attitude and fto issues.

Publiclab introduces me to proper open source and I have learnt exponentially ever since I joined PL.

Thanks all!

**Comment by SidharthBansal** [comment]
Please don't write any information about yourself
Welcome all

**Comment by VladimirMikulic** [comment]
@Mallik813 @Asiedu13

**Comment by SidharthBansal** [comment]
Hello GCI students, 
I hope you all had a great 🎉 experience with Public Lab this winter. We have more surprises for you coming ahead. All the best for week 2. Try to maintain consistency. Even if you are not able to solve the problem stick to it. We are there to guide you so that you can solve it 💯 
So, don't take the stress. Most importantly don't take it as a competition. Take it as a learning challenge!
I observed that students are helping each other. That's really amazing 🙌 
Few tips: PR reviews are marked per WEEK per REPOSITORY.
So, please start reviewing prs of `multiple repositories` so that you can get multiple points. Also, review as many prs as possible as this will help you in understand the code of the repos :-)
I observed students get pr reviews task approval for only one repo. So, start doing for multiple repos.

The second piece of advice is to start making FTOs. Many students are free as their tasks are under review. So, you can utilize your time by doing ftos. Create as many ftos as possible. 
If you find a bug then please report it as an issue on the GitHub, you will get points. Then either we can upload it to GCI dashboard or you will turn it into fto. Either way, you will get points.

Supportive tasks will help you gain a lot of points. Best part is you don't have to claim them nor get approval from mentors after your first supportive task is complete. 2nd, 3rd... supportive tasks will be graded on google forms circulated at the end of GCI. You can fill all the supportive tasks detail there.
If you did 250 supportive tasks then 250 points. Isn't that amazing folks ? 🚀

**Comment by SidharthBansal** [comment]
In case of any doubts, feel free to ask ME or any mentor,

**Comment by CodeSarthak** [comment]
Hi, are any hall-of-fame tasks going to be added soon?

**Comment by SidharthBansal** [comment]
If you find any task that is very difficult like writing docs for whole
repo(15+files), creating a new section of a profile like creating auth
modals, etc. then please let me know. I will mark it as hOF and add it to
the GCI dashboard.
Mentors are busy reviewing the tasks so we are not able to add those types
of tasks till now. Thanks for the reminder.
Please see the break-up labeled task. Maybe we can label them as hOF.
Also, plots2 require system tests for many functions. So, writing 15+
system tests and breaking it into system tests for GCI as medium tasks can
be treated as hOF. It depends on the situation. Please ping wherever you
think we can have hOF label. It should be an EPIC issue. We can discuss it
there.
Thanks

**Comment by SidharthBansal** [comment]
GCI students are requested to take on the tasks labelled with hall of fame
and submit tasks for pr reviews of second week and third week by end of third week (22 Dec 2019)
We will upload week 3 tasks shortly.
Thanks all

**Comment by dnhuan** [comment]
Hi, this is my first time GCI!

**Comment by SidharthBansal** [comment]
Oh great! Welcome to Public Lab
Please read through this welcoming post carefully.
Can you please start with the installation task(s) and 2 beginner
issues/ftos?
Then you can switch to medium/hard or hall-of-fame tasks.
Best of luck all of you :rocket:

**Comment by SidharthBansal** [comment]
Students participated in the program: (students from the dashboard that have completed at least one task)
arnavlol
az @anthony-zhou
cb @chiragbhansali
CHEAH ZIXU  @genesis331 
CodeSarthak @CodeSarthak
EX3x19
fluctix @fluctix
Ghosteroid_naman
HarshK @HarshKhandeparkar
Jonah_zekes
MarxPlank
NotDeGhost @chen-robert
Oleg
pythongiant @pythongiant
ryan10145 @Ryan10145 
symt @symt
takitsuse
UG @Uzay-G
Veer @vgadodia
VladeDev @VladimirMikulic
Dotangad  @dotangad
Ooi Jun Xiang
handlerug
syobon
Prinxe
Sparks @tsparksh
ee9957 @ee9957
md37 @md37

Kindly ping the GCI students not present in the above list OR whose github handle is not present.

**Comment by SidharthBansal** [comment]
Merry Christmas  🎄 🎅 🎁 ☃️ 
I hope all of you are enjoying the holidays.
I just published pr review tasks for the following weeks:
week 4: 23 - 29Dec 
week 5: 30dec - 5 Jan 
Thanks all

**Comment by Uzay-G** [comment]
Thanks @SidharthBansal and merry christmas :santa:! Hey could you please check out my comments on the [codecov issue](https://github.com/publiclab/plots2/issues/6290)? Thank you so much. 

It's a difficult task but I am gonna try my best :+1:!

**Comment by SidharthBansal** [comment]
Please read through its official docs

**Comment by Uzay-G** [comment]
Yeah I checked them out and looked at some examples configurations.

**Comment by Uzay-G** [comment]
Oh great, it's just a start but this change made the codecov bot work on plots2: https://github.com/publiclab/plots2/pull/7042. There are other problems but it's a start!

**Comment by SidharthBansal** [comment]
Ok great

**Comment by SidharthBansal** [comment]
Happy new year!
We are going to upload the following issues after reformatting them
publiclab/plots2#5585
publiclab/plots2#4487
publiclab/plots2#4323
publiclab/plots2#4268
publiclab/plots2#4250
publiclab/plots2#3439
publiclab/plots2#3367
If any candidate wants to pick them before reformatting them, then they can pick it up before reformatting them.
Most of the above will be hard issues.

**Comment by SidharthBansal** [comment]
Stats from present dashboard

**Comment by SidharthBansal** [comment]
![Uploading image.png…]()

**Comment by SidharthBansal** [comment]
Reminder: Ftos carries a lot of points. Please make as many ftos as possible.

**Comment by SidharthBansal** [comment]
In case any GCI student finds that scores are inappropriate and they should get higher score for that task then feel free to ping me. We will evaluate them.
Example: Today I observed one Gigantic PR review, so I have to give points to GCI student who is constantly reviewing another GCI student's pr on an hourly basis. Just I was fair to the reviewer. 
Sometimes reviews are too big and the reviewer should get points too. If this is the case then we can increase the instance count of the issue. I hope all will understand this thing.
Thanks all

**Comment by SidharthBansal** [comment]
When PR reviews are EPIC it becomes PRs done in collaborations.

**Comment by SidharthBansal** [comment]
Few more issues which are going to be published on GCI dashboard soon
Here's possibly a good GCI issue? publiclab/leaflet-environmental-layers#87 medium sized I guess

and a nice one here! publiclab/plots2#6253 large sized!
I'm starting to add this gci-candidate label and they show up as recently updated in this view: https://github.com/publiclab/plots2/issues?q=is%3Aopen+is%3Aissue+label%3Agci-candidate+sort%3Aupdated-desc

**Comment by SidharthBansal** [comment]
Next week's pr review tasks published.

**Comment by SidharthBansal** [comment]
Is any GCI student willing to convert this into FTO ?
https://github.com/publiclab/plots2/issues/6282#issuecomment-571828261

**Comment by SidharthBansal** [comment]
1 point task

**Comment by SidharthBansal** [comment]
This is another task needing reformatting in FTO template.
https://github.com/publiclab/plots2/issues/6176#issuecomment-571777196
1 point task[supportive task]

**Comment by CodeSarthak** [comment]
> This is another task needing reformatting in FTO template.
> [#6176 (comment)](https://github.com/publiclab/plots2/issues/6176#issuecomment-571777196)
> 1 point task[supportive task]

I can work on this one

**Comment by SidharthBansal** [comment]
Sure

**Comment by pydevsg** [comment]
Hello all GCI students here are some of the tasks which you can work upon in the upcoming few days. 
#6828 
#6829 
#6253 
#6282 
#4109 
https://github.com/publiclab/mapknitter/issues/1175

**Comment by SidharthBansal** [comment]
GCI students are requested to get all the tasks published before working on them. All mentors are online now.
Thanks

**Comment by SidharthBansal** [comment]
Many of the students will be stressed about the results. Somebody wrote yesterday, that he is stressed a lot. I will like to suggest that you should be happy instead of being stressful. You all did a very nice job this year. As we have a limited number of slots for prizes, so we cannot give you all prizes. 
For those who will win the prizes it means they are currently having great capabilities :tada: :+1: :100: Winners are suggested to keep bringing changes in themselves so that they will become better day by day. 
Those who will not win the prizes: They did a great job. They were opened to open source. They contributed to real-time software. Isn't this big? You can learn from your mistakes. You learned what git is. Git is a tough subject. You learned rails, HTML, CSS, and a lot of stuff. You came to know how to interact with people globally. You came to know how to collaborate on a large scale. You came across the different phases of the Life Cycle Model for the Software through following
Requirements: You all learned how to raise issues and brainstorm them. Find different ways to elaborate on different ideas and notions. You to create checklists. How to break down stuff into smaller pieces.
Design and Implementation: You learned how to apply changes to get the code work that we discussed in the requirement phase.
Testing: Many students worked at different types of test unit tests, controller tests, integration tests, etc.
Maintenance phase: You learned how to enhance the existing code. We enhanced the existing login system to have a better UI. It can't be achieved without you all. Bug fixing comes into play here. We came across so many bug fixes. Great to see your work.
Be leaders for the organization: You created First timer issues. They were meant to teach you lessons of mentoring, collaborating, etc. At Public Lab, we teach collaborators from beginner level.
I think the above plan for the GCI was completed. You all did all types of tasks. So, why are you stressed up? Learning is a continuous curve and will never reach an end. It is a starting. You will fall, then you have to rise up again. If you will never fall then how can you rise?
I hope that you all enjoyed learning all the above things.
In case even if you will feel disheartened about the result, then you can try again next year. We are there to help you always. We want no one to be stressed. Be cool. Have fun. You are children and stress word should not appear within you ever.
In case you are ineligible for GCI next year, then you can think to participate in Open Source through other means, like GSoC, Outreachy, RGSoC, etc. We run all three programs. Don't ever lose hope. Continue coding and be happy.
Similarly for mentor prize distribution, please don’t think of it as a competition. Think about it as your first global mentoring program. You all did a superb job. You managed to publish 250+ tasks. You managed to review 500+ tasks/issues/prs. Was that not an achievement?
Both mentors and mentees were able to communicate with people all over the world across different time zones. Managing workload across different time zone is an industrial quality you all developed. Qualitative attributes like ownership, reviews, collaborative skills, teamwork, accountability, and responsibility were developed. 
I initially thought of posting mentor related stuff at private mentors only channel. But then I realised that this GCI we achieved much more than we thought. I was really scared this year. You all can ask Jeff. Last year, the crowd was too much and unmanageable. This year we found emerging mentorship within students too. This emerging quality helped us in more number of prs and issues being solved. As mentors behaved like experienced developers, I can’t refrain from this text to private mentors only channel. :rocket:
Was this period too hectic for you all? I took a break myself. So, on vacation, I and Jeff thought of an idea to give you all a break of one week just after the GCI. So, all students will be on NO WORK from 25 January to 30 January. From 31 January to 7 February all GCI mentors can take rest. We want you all to go on vacation OR do anything which you enjoy. Play Guitar or dance or watch NetFlix. Do whatsoever you like. But give it a break. 
I will be available in these periods too. So, we have added a field for fun activities in the grade sheet/evaluation forms. Do anything amazing before GCI ends and post that there. It is completely optional. We will not grade you on the basis of fun event. :smile: Write what you did and which fun event you did just before the end of GCI. Make sure you write about the event you like instead of making us happy. We will not be judging you on fun events. :smile:
However outreachy mentors have to be online and work with their students. 
I will be posting student evaluation forms soon. Kindly fill them asap. These are editable forms, so in case of errors feel free to edit them before ``Thursday, January 23 (18:00 UTC) 
In case of doubts regarding forms fields etc. contact me personally or any other mentors. Thanks all. Have a wonderful career ahead :rocket: :tada:

**Comment by SidharthBansal** [comment]
https://github.com/publiclab/plots2/issues/7219
issue for quick grabs

**Comment by SidharthBansal** [comment]
Hi a good news for you all. We will be opening GSoC mentorship applications for GCI students also if they are eligible according to GSoC mentorship rules. So, stay connected after the GCI :-)
I hope you all like it

**Comment by SidharthBansal** [comment]
We will be adding a much bigger issue to GCI
https://github.com/publiclab/plots2/issues/5316
All folks are invited to come and get as many prs merged as they want. Each area of code say comments system test will be a hard issue of 5 points. So people are encouraged to do them as many as they want. Let's complete this in GCI 2020

**Comment by SidharthBansal** [comment]
All students are invited to write as many system tests as they want. But let's stick to priority system tests first.

**Comment by SidharthBansal** [comment]
Here is the task
https://codein.withgoogle.com/dashboard/tasks/6015285472002048/

**Comment by SidharthBansal** [comment]
GCI ANNOUNCEMENTS: GRADESHEET FOR STUDENTS https://docs.google.com/forms/d/1e60ybBZNaJ_Aai_pJHIzFL4gxMVsVngZBUYw3gK_1dE/edit?ts=5df7b8f8
MENTOR EVALUATION FORMS BY STUDENTS https://docs.google.com/forms/d/1DO5U3APs6nyOorHWIvz5jwFz_Nvw4xhjGredIwprQCg/edit
TOGETHER THEY CONTAIN 10 POINTS
DEADLINE TO FILL THESE FORMS 23 JANUARY 18 UTC
In case of any doubts/queries/problems with the form, contact Sidharth immediately on any communication media

**Comment by tsparksh** [comment]
Hey @SidharthBansal , do we have a mentor list? Is @sashadev-sky a mentor?

**Comment by SidharthBansal** [comment]
Yes she is a mentor

**Comment by SidharthBansal** [comment]
Mentor list is already present in the issue body

**Comment by SidharthBansal** [comment]
Ther forms are editable

**Comment by SidharthBansal** [comment]
One HoF issue:
https://codein.withgoogle.com/dashboard/tasks/6653314876309504/

**Comment by Uzay-G** [comment]
> **GCI ANNOUNCEMENTS: GRADESHEET FOR STUDENTS https://docs.google.com/forms/d/1e60ybBZNaJ_Aai_pJHIzFL4gxMVsVngZBUYw3gK_1dE/edit?ts=5df7b8f8 MENTOR EVALUATION FORMS BY STUDENTS https://docs.google.com/forms/d/1DO5U3APs6nyOorHWIvz5jwFz_Nvw4xhjGredIwprQCg/edit TOGETHER THEY CONTAIN 10 POINTS DEADLINE TO FILL THESE FORMS 23 JANUARY 18 UTC In case of any doubts/queries/problems with the form, contact Sidharth immediately on any communication media**

Should we submit it now or wait a bit longer if we have unfinished tasks?

**Comment by SidharthBansal** [comment]
Forms are editable. So you can add on other tasks too afterwards. :-)

**Comment by Uzay-G** [comment]
Oh sorry I didn't see. Thanks!

**Comment by cesswairimu** [comment]
Hello everyone, I just wanted to thank all of you for the amazing work you are doing :rocket: . Also I would like to know if anyone here would like to open the next weekly check-in? I would be glad to guide if needed. Thanks all and keep up the great work  :+1:

**Comment by daemon1024** [comment]
> Also I would like to know if anyone here would like to open the next weekly check-in? 
I would like to open the next weekly check-in @cesswairimu . I am not a GCI Student but I am new to Public Labs and would like to participate in the organisation more actively.
Thank You :)

**Comment by cesswairimu** [comment]
sure @daemon1024,  please do so in the evening today or early tomorrow morning you can choose any of the many repos to open at. Thanks

**Comment by daemon1024** [comment]
> sure @daemon1024, please do so in the evening today or early tomorrow morning you can choose any of the many repos to open at. Thanks

Thanks @cesswairimu !

> I would be glad to guide if needed. 

Please do so :)

**Comment by daemon1024** [comment]
> please do so in the evening today or early tomorrow morning you can choose any of the many repos to open at. 

@cesswairimu I have opened the check in, https://github.com/publiclab/image-sequencer/issues/1540 here, Kindly review it. 

Also sorry for the spam there-in it was due to some mishandling at my end.

**Comment by SidharthBansal** [comment]
It will be great if you all can get your tasks approved asap if not approved yet. Also please fill the grade sheet and mentor evaluation forms before the deadline.

**Comment by SidharthBansal** [comment]
You can claim one task for some time at the dashboard in the end phase of GCI. So, it will be great if you choose and keep one task for it. Thanks all

**Comment by CoderJolly** [comment]
Hello Everyone !!
Just wanted to remind all GCI Students that you need to fill the forms pertaining to the **Grade sheet** & **Mentor Evaluation** as together they carry **10 points** 💯 

_GRADESHEET_ FOR STUDENTS https://docs.google.com/forms/d/1e60ybBZNaJ_Aai_pJHIzFL4gxMVsVngZBUYw3gK_1dE/edit?ts=5df7b8f8

_MENTOR_ EVALUATION FORMS BY STUDENTS https://docs.google.com/forms/d/1DO5U3APs6nyOorHWIvz5jwFz_Nvw4xhjGredIwprQCg/edit

**The deadline to fill the forms is till 23th January 18 UTC**

In case of any doubts/queries/problems with the form, contact @SidharthBansal immediately on any communication media.

Thank all of you for the amazing work you are doing 🚀.

**Comment by SidharthBansal** [comment]
Is here anyone interested to mentor GSoC or outreachy or rails girl summer of code?

We will be opening the call for mentors shortly

**Comment by Uzay-G** [comment]
I think it could be interesting but I am not sure I have enough experience.

**Comment by SidharthBansal** [comment]
You can give it a try. We are there to help you

**Comment by VladimirMikulic** [comment]
@SidharthBansal we have to be mature (18) to be mentors, right?

**Comment by SidharthBansal** [comment]
Please refer guidelines

**Comment by SidharthBansal** [comment]
Mentors are requested to fill the form
https://docs.google.com/forms/d/1UcmXtNEVjZW6fozpW_9gWduRpnfVNG816JTswx85_VA/edit asap
DEADLINE 27 January 18 IST
Thanks all. We have expedited the process :-)

**Comment by SidharthBansal** [comment]
It was really nice working with you all in GCI.
Let's move to SoC programs now. 
Closing this. 
Thanks

**Comment by SidharthBansal** [comment]
Those candidates who are ineligible for GSoC mentorship can become part of reviewers team. So, no worries :-)

**Comment by SidharthBansal** [comment]
Also, check Outreachy and Rails Girl Summer of Code mentorship eligibility criterion. Maybe you will fit there

**Comment by VladimirMikulic** [comment]
Mark me for reviewers team :+1:

**Comment by SidharthBansal** [comment]
Please send a request. I or @cesswairimu or @jywarren will accept

**Comment by VladimirMikulic** [comment]
Thanks, @SidharthBansal. Where should I send it? Thanks.

**Comment by CodeSarthak** [comment]
Count me in for reviewers team too

**Comment by Uzay-G** [comment]
Yeah I would love to be a part!

**Comment by SidharthBansal** [comment]
Hi, all! New call for SoC mentors for 2020 is up here! #7360
<https://github.com/publiclab/plots2/issues/7360>
Please comment on the reviewers team thread for reviewers team inclusion.
Thanks all

**Comment by SidharthBansal** [comment]
Refer #4707

**Comment by SidharthBansal** [comment]
**Google Code In 2019-20 Mentorship Prize Results**
Hello everyone, this year was EPIC :rocket:. Over 127 students participated and 35 mentors participated this year :tada:. Around 11 repositories participated this year 💯 . We completed the `Login/Sign Up and Oauth` Milestone and `System Tests` 🎖  for entire plots2 repository with the help of @VladimirMikulic and @Uzay-G. Addition to this, please check the pulse monthly
![image](https://user-images.githubusercontent.com/20972099/73378287-61445180-42e6-11ea-844f-585ce40e4f85.png)
This is greater than SoC programs we had earlier. 💯  This is just for plots2. 
Similar progress for other repositories like leaflet, LDI, Editor, MK, SWB, IS and many more.
We are proud to have you all this winter. We have already filled the results for students. Google will be announcing them on 10 February.
Regarding mentors, we will be happy to announce them now 🎉 🎉 🎉 
@keshav234156 GCI GRAND PRIZE SUMMIT + PL KIT
@ananyaarun GSOC SUMMIT(If GCI mentor is invited, in 2019 gci mentor was invited. We hope this year also, GCI mentor is invited) + PL Kit
Following mentors will be awarded a PL Kit for their contribution at Public Lab
Ananya, Keshav, Debashish, Mayank Pathela, Sasha, Isha, Sudipto and Harman Jolly. 🥇 
I have sent an email for the PL kits. Kindly order that using the coupon code I emailed you all.
Thanks and let's start with GSoC and outreachy 🚀 
Let's make it more encouraging and collaborative than past years

**Comment by VladimirMikulic** [comment]
Wow, just wow! I didn't even look at insights. This is crazy :smile: 
Good work everyone.
