### ISSUE TITLE
Make "Answering" HTML Responsive for smartphone use

### ISSUE THREAD

**Issue by ananyo2012** [publiclab/plots2#681]
Hi, this is a `first-timers-only issue`. This means we've worked to make it more legible to folks who either haven't **contributed to our codebase before, or even folks who haven't contributed to open source before**. If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted issues](https://github.com/publiclab/plots2/labels/help-wanted). Thanks!

## The Problem
The css elements at extra small screen width are not properly placed for the Answer view. The design is not fully responsive as you can see in the image below
![small_width_view](https://cloud.githubusercontent.com/assets/10486343/17746116/456c5f26-64cc-11e6-8cca-58f13e965d07.png)
The design looks scattered specially when you are logged in as the comment author since all the buttons are placed out. Relevant url of the image souce: https://publiclab.org/questions/ananyo2012/08-17-2016/is-the-question-interface-working

## Solution
The css gets broken up basically for the comments section in the answer view. These lines include  the answer container: https://github.com/publiclab/plots2/blob/master/app/views/questions/_answer.html.erb#L42-L66
The question form view is here: https://github.com/publiclab/plots2/blob/master/app/views/questions/_form.html.erb
This is the comments view: https://github.com/publiclab/plots2/blob/master/app/views/questions/_comment.html.erb

plots2 uses Bootstrap UI. So try using the bootstrap responsive classes suitably to fix the design at extra small screen width and also maintain the overall Responsive design.

## Steps to Fix
- [ ] claim this issue with a comment
- [ ] set up a repository locally and make sure that all tests pass
- [ ] start a pull request (see contributing to Public Lab software) but mark it as "in progress"
- [ ] fix the issue following the steps above
- [ ] try the manual test listed above
- [ ] make sure all tests pass with rake test
- [ ] alert someone via either the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by carolineh101** [comment]
Hello, I'd like to help out with this issue!

**Comment by jywarren** [comment]
Oh, that'd be great! Please do, and feel free to reach out for any
assistance you need. Thanks!

**Comment by carolineh101** [comment]
I'm having a bit of trouble with the tests after installment – when I run `rake test:all`, I get "0% passed."

**Comment by ananyo2012** [comment]
@carolineh101 Yes you will see see 0% passes. That's fine. Just see you get all green and no errors during test.

**Comment by carolineh101** [comment]
Ok, thanks!

**Comment by jywarren** [comment]
Try just "rake test" -- it's unlikely you've made changes which would
affect JavaScript anyhow.

**Comment by carolineh101** [comment]
How would you like the layout to look?  Currently, I have only changed the design so that the edit and delete buttons are within the container, as seen below.

![screen shot 2016-08-17 at 8 42 38 pm](https://cloud.githubusercontent.com/assets/17236117/17761347/36e609d6-64bb-11e6-8f34-fd81711c1ada.png)

**Comment by ananyo2012** [comment]
Can you somehow adjust the view so that the edit and delete buttons comes just beside the comments as in larger screen widths and the comment body wrap in multiple lines?

**Comment by carolineh101** [comment]
How does this look? I added media queries to resize the comment width depending on screen size (no change to original layout if not a phone, using Bootstrap's "xs" definition of 768 pixels or fewer).

iPhone 6s test
![screen shot 2016-08-17 at 10 58 52 pm](https://cloud.githubusercontent.com/assets/17236117/17763562/4a78595a-64ce-11e6-963b-2aed723c3739.png)

iPhone 4s test
![screen shot 2016-08-17 at 10 59 10 pm](https://cloud.githubusercontent.com/assets/17236117/17763561/4a57ae3a-64ce-11e6-9cb3-f437dbc523ac.png)

**Comment by ananyo2012** [comment]
Oh this looks perfect! Can you now make the comment form responsive too? It should follow the same logic. Make the profile icon the textarea and submit button in the same line. You should also take care that the edit form aligns as well which is basically the same form. You can perhaps use a different Submit icon for smaller screen widths so that it fits well.

**Comment by ananyo2012** [comment]
@jywarren How about using this icon http://fontawesome.io/icon/reply/ for submit button at smaller screen widths?

**Comment by jywarren** [comment]
Sounds great. I'm curious if you were able to put the CSS into a
comments.css file -- if not, no worries and it's fine to do that later. But
it'll help keep the more complex CSS work compartmentalized.

Great work, Caroline! When you're ready, please open a pull request from a
named feature branch and we can look over the code. Happy to offer input on
that process too.

**Comment by jywarren** [comment]
Also, I'm curious how you came across the project? We're doing our best to
make our code welcoming to new contributors and it helps to know what's
working :-)

**Comment by ebarry** [comment]
Hi Caroline @carolineh101 <https://github.com/carolineh101>! Great to meet
you :D

--

+1 336-269-1539
@lizbarry <http://twitter.com/lizbarry>

**Comment by carolineh101** [comment]
I worked on making the comment form responsive.  Here's how it looks at the moment:

iPhone 6s test
![screen shot 2016-08-18 at 11 28 59 am](https://cloud.githubusercontent.com/assets/17236117/17785860/512b25a2-6537-11e6-909a-94214aaa64e4.png)

Mac test
![screen shot 2016-08-18 at 11 29 27 am](https://cloud.githubusercontent.com/assets/17236117/17785861/51343782-6537-11e6-81eb-68e8d546d0fe.png)

@jywarren Yes, I did add the css to a comments.css file.  In regard to how I came across the project, I was just searching through Github for interesting projects with issues marked "help-wanted" and I saw that this bug had really clear documentation!

And @ebarry, hello to you too!

**Comment by ananyo2012** [comment]
Oh this really looks good now! Nice to meet you too @carolineh101 ! We are having more and more contributors in plots2! Just to be sure can you confirm that that the comment box has the expandable feature as you type in for smaller screen width? Probably post a screenshot how it looks now?

I was thinking that perhaps we should remove the profile icon beside the comment textarea as it looks quite odd. It will also give more room for the textarea. Can you give it a try and show how it looks?

**Comment by carolineh101** [comment]
Expanding seems to work:

![screen shot 2016-08-18 at 2 33 17 pm](https://cloud.githubusercontent.com/assets/17236117/17791596/cac92d28-6550-11e6-964d-0afec5d79d3f.png)

Would you like me to remove the profile icon beside both comment text areas, or only from one of them?  And would you like it removed only for phone screen widths or for all widths?

**Comment by jywarren** [comment]
Maybe only for the narrowest widths -- and only beside the inputs, but both
of them... thanks, Caroline! A little left/right padding on the top bar
just below "1 Answers" would also be great. But you know, it's also fine to
just call this one complete and file a PR... we don't want to ask you to
bite off too much in a single issue! Very happy to have your contribution.

**Comment by carolineh101** [comment]
Ok! Does this look good? If so, I'll go ahead and submit a PR.

![screen shot 2016-08-18 at 3 37 56 pm](https://cloud.githubusercontent.com/assets/17236117/17793108/d7d3634a-6559-11e6-91dc-ae84a16ebeb8.png)

**Comment by jywarren** [comment]
Yeah, looks great!

**Comment by carolineh101** [comment]
I've created a pull request!

**Comment by ananyo2012** [comment]
@carolineh101 This looks great now! :+1:

**Comment by jywarren** [comment]
Closed in #696. Thanks again!

**Comment by ebarry** [comment]
Hi @carolineh101! Thank you again for your valuable contribution to Public Lab. I would like to invite you to join us in a video conference to say a few words about what you contributed and how your experience was. The event is https://publiclab.org/openhour, and it’s coming right up on November 7th, at 1pm EDT which is UTC/GMT -4. 

Please feel free to respond here, or else email liz@publiclab.org, stevie@publiclab.org, jeff@publiclab.org.

**Comment by carolineh101** [comment]
Hi @ebarry, thank you for inviting me to participate in the video conference!  Unfortunately, I have class at this time and will not be able to join in.
