### ISSUE TITLE
Fix pluralization logic III

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/plots2#6810]
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

![image](https://user-images.githubusercontent.com/41092741/69100165-8f75fd00-0a2a-11ea-99fb-cb42733cbaa4.png)

The pluralization in the screenshot above is incorrect (ie. should be "1 person" not "1 people")

## Solution

This is a simple one -- lets find the relevant line of code first:

https://github.com/publiclab/plots2/blob/a5d3392c3d6f5f4daaa56d5a4431e1bc0de5c46c/app/views/tag/_profileCard.html.erb#L7

As you can see, this line has no conditional and "people" will always just be plural.

Let's correct this: - Rails gives us a really convenient way to resolve it through the [pluralize method](https://apidock.com/rails/ActionView/Helpers/TextHelper/pluralize).

Update the inner `a` tag to use the method like so:

```ERB
<a href="/tag/<%= tag.name %>"><%= pluralize(Tag.follower_count(tag.name), 'person') %> discussing</a>
```

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/plots2](https://github.com/publiclab/plots2)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by sashadev-sky** [comment]
**Uploaded on GCI Dashboard**

**Comment by SidharthBansal** [comment]
Published

**Comment by 1405043-kd** [comment]
can I claim this?

**Comment by SidharthBansal** [comment]
Hi @1405043-kd This issue is reserved for GCI students. Please do any other issue.
Thanks

**Comment by kamal-kaur04** [comment]
Hii @SidharthBansal Can I take this issue??

**Comment by Alexjake660** [comment]
@sashadev-sky I'd like to claim this issue

**Comment by sashadev-sky** [comment]
@kamal-kaur04 go for it! 

@Alexjake660 if @kamal-kaur04 doesn't respond in the next week you can go for it

**Comment by Alexjake660** [comment]
@sashadev-sky thank you.

**Comment by kamal-kaur04** [comment]
Thanks @sashadev-sky Will do this.

**Comment by Alexjake660** [comment]
Exactly a week.
Lol

**Comment by sashadev-sky** [comment]
@Alexjake660 sorry!! If you want an FTO and like JS there is one available here: https://github.com/publiclab/Leaflet.DistortableImage/issues/429

**Comment by Alexjake660** [comment]
@sashadev-sky Thank you. I already completed an FTO though. If it'll still be okay for me to do this, I can.

**Comment by sashadev-sky** [comment]
You are welcome to do one for each repo! @Alexjake660
