### ISSUE TITLE
Rename fetch_comments method

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#6814]
`fetch_comments` method should be named something more descriptive, like `comments_viewable_by(user)` or `comments_approved_for(user)`!

_Originally posted by @jywarren in https://github.com/publiclab/plots2/pull/6718#issuecomment-555569444_

The method is here 
https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L1063-L1071

And you need to replace on the new method these files and lines

1. https://github.com/publiclab/plots2/blob/master/app/views/questions/show.html.erb#L58
2. https://github.com/publiclab/plots2/blob/master/app/views/questions/_new_question.html.erb#L71

3. https://github.com/publiclab/plots2/blob/master/app/views//notes/_comments.html.erb#L3

4. https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_node_comment.html.erb#L6

5. https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_node_meta.html.erb#L18

**Comment by cato-hga** [comment]
@cesswairimu This looks like something I could do. Can I try working on this one?

**Comment by cesswairimu** [comment]
Hey @cato-hga, yeah sure go ahead. Thanks

**Comment by Amith1206** [comment]
has this issue been solved

**Comment by govindgoel** [comment]
I have submitted a pull request on this but some more files to change.

**Comment by govindgoel** [comment]
Hey @cesswairimu  I would like to work on this issue if it is still available and I ask you to please elaborate what exactly to be done. And I also apologise for the PR's I mentioned without prior advise.
Happy Coding!

**Comment by Tlazypanda** [comment]
@cesswairimu is this issue still available?

**Comment by cesswairimu** [comment]
Hey @Tlazypanda, yeah, no one completed the issue as per the specifications, we would love your help. Thanks
