### ISSUE TITLE
Wiki pages broken where title and path did not match, or where path did not include "wiki"

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#682]
https://publiclab.org/openhour for example, which is now available at https://publiclab.org/wiki/openhour

Other pages like https://publiclab.org/wiki/about are affected because it's title was "About Public Lab" and so its new URL is https://publiclab.org/wiki/about-public-lab

This is high urgency; many, including some of our most important pages. are affected. 

This is related to the `friendly_id` work, @ananyo2012. I'll be in [Gitter](https://gitter.im/ananyo2012/plots-gsoc) to coordinate fixing.

This is not just root level wiki pages; `/wiki/organizers` was changed to `https://publiclab.org/wiki/public-lab-organizers`. I believe the migration mentioned above has made all slugs match titles, which broke many existing URLs. I think this may not even be a root wiki issue, but a batch migration renaming issue. 

The new migration resaved all nodes, here: https://github.com/publiclab/plots2/blob/master/db/migrate/20160816094642_seed_slugs_column.rb#L3 and caused the url to change and follow whatever the title was. See a failed attempt to change a url back, here:

```ruby
2.1.2 :014 > n = DrupalNode.first
  DrupalNode Load (1.9ms)  SELECT "node".* FROM "node" LIMIT 1
 => #<DrupalNode nid: 1, vid: 0, type: "page", language: "", title: "About", uid: 1, status: 1, created: 1467898382, changed: 1471467098, comment: 0, promote: 0, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 0, drupal_comments_count: 0, drupal_node_revisions_count: 1, path: "/wiki/about", main_image_id: nil, slug: "about"> 
2.1.2 :015 > n.path = "/about"
 => "/about" 
2.1.2 :016 > n
 => #<DrupalNode nid: 1, vid: 0, type: "page", language: "", title: "About", uid: 1, status: 1, created: 1467898382, changed: 1471467098, comment: 0, promote: 0, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 0, drupal_comments_count: 0, drupal_node_revisions_count: 1, path: "/about", main_image_id: nil, slug: "about"> 
2.1.2 :017 > n.save!
   (0.3ms)  begin transaction
  DrupalNode Exists (0.7ms)  SELECT 1 AS one FROM "node" WHERE ("node"."path" = '/about' AND "node"."nid" != 1) LIMIT 1
   (0.9ms)  UPDATE "node" SET "changed" = 1471467155 WHERE "node"."nid" = 1
  FriendlyId::Slug Load (0.8ms)  SELECT "friendly_id_slugs".* FROM "friendly_id_slugs" WHERE "friendly_id_slugs"."sluggable_id" = 1 AND "friendly_id_slugs"."sluggable_type" = 'DrupalNode' ORDER BY "friendly_id_slugs".id DESC LIMIT 1                                                                                                    
   (28.7ms)  commit transaction
 => true 
2.1.2 :018 > n = DrupalNode.first
  DrupalNode Load (1.2ms)  SELECT "node".* FROM "node" LIMIT 1
 => #<DrupalNode nid: 1, vid: 0, type: "page", language: "", title: "About", uid: 1, status: 1, created: 1467898382, changed: 1471467155, comment: 0, promote: 0, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 0, drupal_comments_count: 0, drupal_node_revisions_count: 1, path: "/wiki/about", main_image_id: nil, slug: "about"> 
```

**Comment by jywarren** [comment]
I can confirm that [the test here](https://github.com/publiclab/plots2/blob/master/test/functional/wiki_controller_test.rb#L88) did not actually test the format of the root level path. 

And the error on the server log is:

```
ActiveRecord::RecordNotFound (Couldn't find DrupalNode with nid=receipts):
  app/controllers/wiki_controller.rb:23:in `show'
```

**Comment by jywarren** [comment]
OK, I believe it's because due to the new `friendly_id` system, root-level wiki routing never reaches this line, and so is not directed to the `def root` method in the wiki controller: https://github.com/publiclab/plots2/blob/master/config/routes.rb#L278

**Comment by jywarren** [comment]
I'd also like to peg `friendly_id` to a version -- tests were passing on my dev machine at `v4.0.10.1`.

**Comment by jywarren** [comment]
I actually am having trouble recreating this condition on my development machine, because if I set `node.path = '/about'` then save it, it doesn't actually change the path, probably due to some friendly_id filter:

```ruby
2.1.2 :014 > n = DrupalNode.first
  DrupalNode Load (1.9ms)  SELECT "node".* FROM "node" LIMIT 1
 => #<DrupalNode nid: 1, vid: 0, type: "page", language: "", title: "About", uid: 1, status: 1, created: 1467898382, changed: 1471467098, comment: 0, promote: 0, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 0, drupal_comments_count: 0, drupal_node_revisions_count: 1, path: "/wiki/about", main_image_id: nil, slug: "about"> 
2.1.2 :015 > n.path = "/about"
 => "/about" 
2.1.2 :016 > n
 => #<DrupalNode nid: 1, vid: 0, type: "page", language: "", title: "About", uid: 1, status: 1, created: 1467898382, changed: 1471467098, comment: 0, promote: 0, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 0, drupal_comments_count: 0, drupal_node_revisions_count: 1, path: "/about", main_image_id: nil, slug: "about"> 
2.1.2 :017 > n.save!
   (0.3ms)  begin transaction
  DrupalNode Exists (0.7ms)  SELECT 1 AS one FROM "node" WHERE ("node"."path" = '/about' AND "node"."nid" != 1) LIMIT 1
   (0.9ms)  UPDATE "node" SET "changed" = 1471467155 WHERE "node"."nid" = 1
  FriendlyId::Slug Load (0.8ms)  SELECT "friendly_id_slugs".* FROM "friendly_id_slugs" WHERE "friendly_id_slugs"."sluggable_id" = 1 AND "friendly_id_slugs"."sluggable_type" = 'DrupalNode' ORDER BY "friendly_id_slugs".id DESC LIMIT 1                                                                                                    
   (28.7ms)  commit transaction
 => true 
2.1.2 :018 > n = DrupalNode.first
  DrupalNode Load (1.2ms)  SELECT "node".* FROM "node" LIMIT 1
 => #<DrupalNode nid: 1, vid: 0, type: "page", language: "", title: "About", uid: 1, status: 1, created: 1467898382, changed: 1471467155, comment: 0, promote: 0, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 0, drupal_comments_count: 0, drupal_node_revisions_count: 1, path: "/wiki/about", main_image_id: nil, slug: "about"> 
```

I have to go, i have a phone call for 30 mins and will return to this after.

**Comment by jywarren** [comment]
Ack! Mistake -- the above server log was for `/wiki/receipts`. The request for `/receipts` was:

```ruby
Started GET "/receipts" for 72.203.200.206 at 2016-08-17 20:25:08 +0000
Processing by WikiController#root as HTML
  Parameters: {"id"=>"receipts"}
  Rendered public/404.html within layouts/application (0.1ms)
```

I think the new migration here: https://github.com/publiclab/plots2/blob/master/db/migrate/20160816094642_seed_slugs_column.rb#L3 caused the url to change. Checking.

**Comment by jywarren** [comment]
The `/receipts` page is nid 4181. Unfortunately the page slug has been changed to match the title:

```ruby
 => #<DrupalNode nid: 4181, vid: 26687, type: "page", language: "", title: "Receipt submission form 2012-2013", uid: 9, status: 1, created: 1349404976, changed: 1471387990, comment: 0, promote: 0, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 0, drupal_comments_count: 0, drupal_node_revisions_count: 18, path: "/wiki/receipt-submission-form-2012-2013", main_image_id: nil, slug: "receipt-submission-form-2012-2013"> 
```

**Comment by jywarren** [comment]
This is not just root level wiki pages; `/wiki/organizers` was changed to `https://publiclab.org/wiki/public-lab-organizers`. I believe the migration mentioned above has made all slugs match titles, which broke many existing URLs. I think this may not even be a root wiki issue, but a batch migration renaming issue.

**Comment by jywarren** [comment]
I believe all previous paths were lost with the migration. Looking into a script to recover all previous wiki page URLs -- there are 1014 wiki pages. 

Maps also seem to be broken: https://publiclab.org/map/barataria-site-abh2-barataria-bay-louisiana/07-25-2014

**Comment by jywarren** [comment]
I'm considering what it would take to do a full reversion of `friendly_id` code, since there are multiple issues here.

**Comment by david-days** [comment]
Looking at models/drupal_node.rb right now--I had to dig through this url-matching setup to figure out how to make searches work

**Comment by jywarren** [comment]
We have good database backups, so we'll be able to recover any lost data; that's not a big deal. Of 1014 wiki pages, probably only a couple dozen have different titles from their paths.  Structurally though, removing `friendly_id` which was merged about a dozen PRs back, would be challenging.

**Comment by jywarren** [comment]
I'm checking out the maps issue now before taking next steps

**Comment by jywarren** [comment]
All right; my action plan is:

1. find how many wiki pages either lacked the word "wiki" (were root-level) or had titles different from their paths, and store a copy
2. resolve map routes issue
3. find how to change the current URL of a node
4. find how to stop a `save` from changing a path
5. decide whether to excise `friendly_id` code to accomplish 2, 3 and 4
6. code around `friendly_id` or excise it
7. run saved original paths in batch process to recover
8. write down next steps here for tomorrow

**Comment by jywarren** [comment]
Also looking here: http://stackoverflow.com/questions/24454926/unable-to-change-url-path-after-updating-attributes-with-friendly-id#24466172

**Comment by jywarren** [comment]
* I've figured out how to modify the code to manually set `node.path`, and let it remain preserved across `node.save`s. 
* I'm recovering all previous node paths from a database dump from 7/28/16, and have confirmed that no wiki pages were retitled or created with non-matching title/paths since then.

**Comment by jywarren** [comment]
Fixes enabling recovery of wiki paths (in followup script) here: #685

**Comment by jywarren** [comment]
Moving map issue to it's own issue: #686

**Comment by jywarren** [comment]
Next steps will be:

1. run query in rails console on recovery database to find all wiki pages whose title does not match their path
2. generate a nested array of `[[nid, path]]` for copy/paste
3. switch to live db and iterate over, and set path for each nid and save
4. confirm https://publiclab.org/wiki/about, https://publiclab.org/openhour, https://publiclab.org/wiki/organizers

**Comment by ananyo2012** [comment]
I am really very sorry Jeff! It was a very big mistake from my part. I had
missed it out. What I should have have done was to save all the previous
urls in the history module and then only change the slugs! I big mistake
from my part!
ᐧ

**Comment by jywarren** [comment]
That's OK -- don't worry about it. I think only 10-20 pages are affected
and we have a good database backup to work from. I want to think about how
we can improve our tests and even our testing procedure to catch things
like this in the future. But also -- read over my fixes -- is it OK for
`friendly_id` to simply not update on title change? Or will we have to make
more significant changes? All tests passed with the new changes, though I
deleted a few tests. Maybe we're OK, but let's be sure.

Thanks! The database backup is still converting, so I'm going to let it go.
I could manually change the pages we know about now, but I don't think it's
urgent and I prefer to wait until morning to see if the db imports, and to
do it all at once.

**Comment by ananyo2012** [comment]
@jywarren Yes some more changes are needed at the controllers since they too find the nodes using the friendly_id slug. I will be seeing that. But I think the easiest solution would be if possible is to change the title according to the previous url. That would save the slugs in the friendly_id slug table. And then we can change to new title any time and the old urls would redirect to the new ones.

**Comment by jywarren** [comment]
OK, I've reset the wiki paths from a recovered database, thanks to @skillfullycurled. All the ones I mentioned seem to work except /wiki/organizers. I'm not sure what's up with that one.

**Comment by jywarren** [comment]
I'm not sure what's up with the organizers page; it was in the list I generated of wiki pages whose titles did not match their paths in the pattern `/wiki/parameterized-pagename` -- I'm posting that list here: https://gist.github.com/jywarren/11f32f5ea891ad9bfe5807210a3400ef -- `[1805,"Public Lab organizers","/wiki/organizers"]`

**Comment by jywarren** [comment]
Perhaps this is still a `friendly_id` issue. The error is:

```
Started GET "/wiki/organizers" for 117.211.86.108 at 2016-08-18 03:59:35 +0000
Processing by WikiController#show as HTML
  Parameters: {"id"=>"organizers"}
Completed 404 Not Found in 2.2ms

ActiveRecord::RecordNotFound (Couldn't find DrupalNode with nid=organizers):
  app/controllers/wiki_controller.rb:23:in `show'
```
However, I can see the record:
```
2.1.2 :001 > n = DrupalNode.find 1805
  DrupalNode Load (0.1ms)  SELECT `node`.* FROM `node` WHERE `node`.`nid` = 1805 LIMIT 1
 => #<DrupalNode nid: 1805, vid: 27430, type: "page", language: "", title: "Public Lab organizers", uid: 9, status: 1, created: 1335477268, changed: 1471492401, comment: 0, promote: 0, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 14, drupal_comments_count: 0, drupal_node_revisions_count: 217, path: "/wiki/organizers", main_image_id: 17601, slug: "public-lab-organizers"> 
```

**Comment by jywarren** [comment]
Can you take a look, Ananyo? I'm going to sleep! phew

**Comment by ananyo2012** [comment]
Yeah I am on it Jeff! Have some rest. I will figure what the problem is.

**Comment by ananyo2012** [comment]
This is because the finding is still based on slugs. Need to revert to finding nodes by path. Please hang on a bit. I am going to send in a PR soon.

**Comment by jywarren** [comment]
Thanks.

**Comment by jywarren** [comment]
Also, do you think we have to amend the migration that saved all nodes?
It's a slim chance but if someone else ever runs that again, on the live or
another instance, it could cause trouble again. Maybe best to either
comment it out or add the history generating command before it.

**Comment by ananyo2012** [comment]
Actually the migration just resaves all nodes. Now that we have comment out
the update_path method it won't cause any problems
ᐧ

**Comment by jywarren** [comment]
Yes, but if anyone has a previous version of the codebase running (we don't
know of any, but it's possible) they might upgrade through this process.
It's a really rare possibility but I'd like to be thorough.

Also just thinking through all the different follow-ups we should do after
last night. Thanks!

**Comment by ananyo2012** [comment]
Ok then we should probably remove the migration?
ᐧ

**Comment by jywarren** [comment]
I'll do it in merging #687, just to be sure. Checking that now.

**Comment by jywarren** [comment]
Can you work on https://github.com/publiclab/plots2/issues/689 in the meantime?

**Comment by jywarren** [comment]
Also, let's make a checklist for cleaning up commented code after this: #691

**Comment by jywarren** [comment]
As ananyo pointed out this also affects nodes; I'm importing previous node paths and one way that they differ is that month is sometimes presented in `DD-M-YYYY` format instead of the now-standard `DD-MM-YYYY` format. See here the old record as I'm importing it, and the new record after the faulty migration:

```
 => {"created"=>1291706359, "nid"=>6, "path"=>"/notes/warren/12-7-2010/toy-spectrometers-arrived", "status"=>1, "title"=>"Toy spectrometers arrived", "type"=>"note", "uid"=>1} 
2.1.2 :033 > DrupalNode.find 6
  DrupalNode Load (0.4ms)  SELECT `node`.* FROM `node` WHERE `node`.`nid` = 6 LIMIT 1
 => #<DrupalNode nid: 6, vid: 8, type: "note", language: "en", title: "Toy spectrometers arrived", uid: 1, status: 1, created: 1291706359, changed: 1471387969, comment: 2, promote: 1, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 0, drupal_comments_count: 0, drupal_node_revisions_count: 1, path: "/notes/warren/12-07-2010/toy-spectrometers-arrived", main_image_id: nil, slug: "warren-12-07-2010-toy-spectrometers-arrived"> 
```

**Comment by jywarren** [comment]
Old notes paths now imported. This page still doesn't work, but maybe will pending #687: https://publiclab.org/notes/warren/12-7-2010/toy-spectrometers-arrived

**Comment by jywarren** [comment]
OK, with #687, that page and https://publiclab.org/wiki/organizers are back up. Also https://publiclab.org/openhour and https://publiclab.org/about. Great!
