### ISSUE TITLE
Unable to add 'question:question' power tag

### ISSUE THREAD

**Issue by publiclab-mimi** [publiclab/plots2#6822]
### Please describe the problem (or idea)

I'm not able to add power tags to my posts (or others) on the site. When I posted this question (https://publiclab.org/notes/mimiss/11-20-2019/dfrobot-turbidity-sensor-troubleshooting) I included only power tags in the editor. Once posted, it was without tags. When I go to try and add tags (in chrome or safari) I see the following:

First this:
<img width="1037" alt="Screen Shot 2019-11-20 at 9 41 19 AM" src="https://user-images.githubusercontent.com/48802639/69253760-c4916500-0b7a-11ea-9de2-57d35740ab76.png">

Then, after adding a power tag, this: 
<img width="1033" alt="Screen Shot 2019-11-20 at 9 41 39 AM" src="https://user-images.githubusercontent.com/48802639/69253795-d07d2700-0b7a-11ea-8821-ffc3a3efbf36.png">

This is the second time that I've run into this issue. Both times with questions where the tag editor begins with question:question. I've noticed other questions going un-tagged as well. Is this a question:question issue perhaps?

### What's your PublicLab.org username?
@ mimiss

### Browser, version, and operating system

Mac OS Catalina, Google Chrome and Safari

**Comment by publiclab-mimi** [comment]
If I go back to the same post and use any power tag other than question:question they work, so I'm thinking this is a question:question issue.

**Comment by publiclab-mimi** [comment]
For a new user posting a question, the question:question power tag is removed but the first-time-poster tag is still added

<img width="1141" alt="Screen Shot 2019-11-20 at 9 59 03 AM" src="https://user-images.githubusercontent.com/48802639/69254848-78472480-0b7c-11ea-99b0-516a1afb2f44.png">

**Comment by jywarren** [comment]
Hi, Mimi, thanks! Sorry, just to clarify, what page/button did you post
this from, and which tags a) should have appeared and b) shouldn't have
appeared? Thank you!

**Comment by publiclab-mimi** [comment]
Both posts from the dashboard->share your work->ask a question. On the first post where I noticed the issue I had a bunch of additional tags, question:water-sensing, water-quality, question:turbidity, and a few more. None of those tags appeared on the post when it was published. I had a student go through the same dashboard to question and put a BUNCH of tags in (after the question:question tag that is auto-generated) that didn’t show up. On the test post, I did not add any additional tags to the question:question tag that is auto-generated.

A side note, but I’ve noticed that when I add the tag ‘question:water’ the tag ‘water’ is not auto-added

**Comment by jywarren** [comment]
Thanks, can you clarify where you posted the question from, i.e. which page
and which button? That'll help us troubleshoot -- and reproduce -- the
issue!

**Comment by publiclab-mimi** [comment]
Yes, Sorry. For both the errors shown here I was on the dashboard (publiclab.org/dashboard <http://publiclab.org/dashboard>) and opened the “Share Your Work” dropdown and pressed “Ask a Question” which brought me over to the editor.

**Comment by jywarren** [comment]
Ah sorry didn't understand that this was the same issue. 

Just for a possible quick fix; the current dashboard uses this URL for questions:

https://publiclab.org/post?tags=question:question&template=question&redirect=question

What if we switched it for this?

https://publiclab.org/questions/new?tags=question:general

Would that fix this?

**Comment by publiclab-mimi** [comment]
I think this would do it!

**Comment by jywarren** [comment]
OK awesome. The URL is here: 

https://github.com/publiclab/plots2/blob/eaf36b1bcfc7c05562aa7ed594ebd6e92154c8c8/app/views/sidebar/_dashboard.html.erb#L12

I'll make a FTO!

**Comment by jywarren** [comment]
Closing for https://github.com/publiclab/plots2/issues/6823 -- thank you, @publiclab-mimi !!!!
