### ISSUE TITLE
Wiki tag page showing only one entry

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6825]
https://publiclab.org/wiki/tag/project:featured should show ~ 3 wiki pages, but it shows only one. 

An example of one not appearing is: https://publiclab.org/wiki/the-sand-sentinel-program

Not sure why this is happening! The code for this is here;

https://github.com/publiclab/plots2/blob/eaf36b1bcfc7c05562aa7ed594ebd6e92154c8c8/app/controllers/tag_controller.rb#L107-L148

We'd love help debugging this!

**Comment by jywarren** [comment]
Very strange, but this page doesn't suffer the same issue! 

https://publiclab.org/wiki/tag/project

**Comment by jywarren** [comment]
Could it relate to power tags?

**Comment by jywarren** [comment]
Could it be related to this issue? Needs testing on the console! https://github.com/publiclab/plots2/issues/3248

**Comment by jywarren** [comment]
Note this returns 4 items, which is correct:

```
t = Tag.where('term_data.name IN (?)', 'project:featured')
=> #<ActiveRecord::Relation [#<Tag tid: 23372, vid: 3, name: "project:featured", description: "", weight: 0, count: 4, parent: nil>]>
```
However this returns only 1:

```
Tag.find_nodes_by_type('project:featured', 'page')
```

**Comment by NitinBhasneria** [comment]
@jywarren Is this issue closed.

**Comment by jywarren** [comment]
This is an iteration of #7334 which is now solved!

**Comment by jywarren** [comment]
Ah, i'm seeing only 2 now but 3 are listed in the tab; reopening for a closer look - could be a "ghost node" or something... an irregular record of some kind, like in https://github.com/publiclab/plots2/issues/7334#issuecomment-662115491

![Screen Shot 2020-10-06 at 10 45 22 PM](https://user-images.githubusercontent.com/24359/95281619-a29de100-0825-11eb-9f07-104e22741059.png)

**Comment by jywarren** [comment]
Oh wait, the live site didn't pull the latest changes. Need to recheck the current commit on the live site and this could indeed be solved...

**Comment by jywarren** [comment]
OK, it published now and it worked! 4 and 4!
