### ISSUE TITLE
On new Front Page, change "Join" button to "Follow Topics" for logged-in users

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#6826]
**The issue:** On the gorgeous new Front Page https://publiclab.org/home , logged-in users are presented with the Join button, which leads to a signup action which is not allowed while signed in so that an error appears. 

**The Idea:** Logged in users are presented with a button to "Follow Topics"

Current screenshot showing how logged-in users are presented with a Join button: 
<img width="1261" alt="Screen Shot 2019-11-20 at 5 03 50 PM" src="https://user-images.githubusercontent.com/161439/69282228-ca596b80-0bb7-11ea-8872-e2da557c79ff.png">

What is shown when you click the button: 
<img width="1100" alt="Screen Shot 2019-11-20 at 5 04 59 PM" src="https://user-images.githubusercontent.com/161439/69282292-f117a200-0bb7-11ea-9dfe-a61388db0507.png">

**Comment by jywarren** [comment]
Solved!
