### ISSUE TITLE
Fix pluralization logic IV

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/plots2#6827]
**Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

## The problem

On the `/notes/author/admin` page, the pluralization for research notes is incorrect: 

<img width="870" alt="Screen Shot 2019-11-20 at 11 34 09 PM" src="https://user-images.githubusercontent.com/41092741/69304364-58504900-0bee-11ea-97c8-edb10e6a072d.png">

## Solution

When plugging in values that are subject to change, we need to make sure the text it'll generate is appropriate for both the singular and plural case.

 -- lets find the relevant line of code first:

the text is generated here:
https://github.com/publiclab/plots2/blob/a5d3392c3d6f5f4daaa56d5a4431e1bc0de5c46c/app/views/notes/index.html.erb#L14

with additional help from here:
https://github.com/publiclab/plots2/blob/b3dc71222e3a1ce9e5417bc01c8b1e3c0d92f21f/config/locales/en.yml#L158-L159

There are many ways to fix this
-  I like this solution - "you can make use of the pluralization features of the `I18n` library by defining count values to translation keys". http://stackoverflow.com/questions/25064677/ddg#25065514
- But do it however! Just make sure your solution is DRY, as in sticks to using the locale helpers if this variable is used frequently throughout the repo, or a rails/ruby/etc.  method that helps to handle this logic. No `if count == 1 ... else ....` here please as **we have both "note(s)" and "edit(s)" to consider**. 

**Requirements**: 
- [ ] DRY
- [ ] accounts for both "note(s)" and "edit(s)"

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/plots2](https://github.com/publiclab/plots2)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by sashadev-sky** [comment]
**Uploaded to GCI Dashboard**

**Comment by SidharthBansal** [comment]
PUBLISHED

**Comment by Uzay-G** [comment]
Hey @sashadev-sky, I'd like to work on this. Can we use the rails [pluralize](https://apidock.com/rails/ActionView/Helpers/TextHelper/pluralize) method instead. I have a working solution but maybe that's not what you are looking for.

**Comment by Uzay-G** [comment]
@sashadev-sky I'd like to work on this issue but I don't understand why it wouldn't work with the [pluralize](https://apidock.com/rails/ActionView/Helpers/TextHelper/pluralize) method.

**Comment by Uzay-G** [comment]
With something like this it seems to be working:
```<h3><%= raw t('notes.index.research_by', :url1 => "/people/"+@user.name, :user_name => @user.name) %> <small><%= pluralize(@user.note_count, "note") %> and <%= pluralize(@user.revisions.count, "edit") %><% if @user.notes.length > 0 %> <%= raw t('notes.index.starting_time', :time => time_ago_in_words(@user.created_at)) %><% end %></small></h3>```
