### ISSUE TITLE
Fix pluralization in admin page - I

### ISSUE THREAD

**Issue by pydevsg** [publiclab/plots2#6828]
**Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Problem
![comment_section](https://user-images.githubusercontent.com/40278255/69336784-571e2b00-0c85-11ea-908d-c163e0e33256.png)

The pluralization in the screenshot above is incorrect (i.e. it should be "1 comment" not "1 comments" )

### Code Snippet
https://github.com/publiclab/plots2/blob/master/app/views/users/profile.html.erb/#L256

In order to solve this problem we need to write a conditional statement to pluralize when the count>1 . In order to do this we will be using [pluralize method](https://apidock.com/rails/ActionView/Helpers/TextHelper/pluralize).

### Solution

```ERB
<li><h5><a href = "/profile/comments/<%= params[:id] %>"><%= pluralize(Comment.where(uid: @profile_user.id).count, 'comment', plural: 'comments') %></a></h5></li>
```
### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you until a certain duration  if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

##  💬   Get help
If you need any help - here are some options: 

- Comment below.
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by SidharthBansal** [comment]
https://github.com/publiclab/plots2/issues/6828

**Comment by genesis331** [comment]
Can I work on this?

**Comment by genesis331** [comment]
Please check the [PR](https://github.com/publiclab/plots2/pull/6908).

**Comment by SidharthBansal** [comment]
Are you a GCI student?

**Comment by keshav234156** [comment]
@genesis331 Have you claimed this task on the GCI dashboard? Also, do give a thorough read to #6808

**Comment by pydevsg** [comment]
@genesis331 you haven't yet claimed the issue on GCI Dashboard , please do the same and let me know

**Comment by genesis331** [comment]
Ok claiming it on Dashboard.

**Comment by pydevsg** [comment]
Hi, @genesis331 please let me know if you have done so
