### ISSUE TITLE
Fix pluralization in admin page - II

### ISSUE THREAD

**Issue by pydevsg** [publiclab/plots2#6829]
**Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Problem
![admin_research_note](https://user-images.githubusercontent.com/40278255/69339028-79ff0e00-0c8a-11ea-8b97-8d0fa2d60bb1.png)

The pluralization in the screenshot above is incorrect (i.e. it should be "1 research note" not "1 research notes" )

### Code Snippet
https://github.com/publiclab/plots2/blob/master/app/views/users/profile.html.erb#L13
https://github.com/publiclab/plots2/blob/master/app/views/users/profile.html.erb/#L253

### Solution
Use the `pluralize` in **a** tag as given below for the two lines indicated above.
```ERB
<h5><a href='/notes/author/<%= @profile_user.name %>'><%= pluralize(@profile_user.note_count, 'research note', plural: 'research notes') %></a>
```
```ERB

```
### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you until a certain duration  if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

##  💬   Get help
If you need any help - here are some options: 

- Comment below.
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by SidharthBansal** [comment]
PUBLISHED ON GCI DASHBOARD

**Comment by pianeta051** [comment]
Hi, 
Is anyone working on this?
May I take this issue?

**Comment by Uzay-G** [comment]
Hey @pianeta051:smile:. This issue is reserved for participants in the Google CodeIn. If you are indeed a member, you can work on this one. 
Otherwise you can find some issues [here](https://code.publiclab.org)

**Comment by z-arnott** [comment]
Hi, does this still need to be done?
If so, I'd like to work on it! :)

**Comment by SidharthBansal** [comment]
Yes you can work on it
Thanks
