### ISSUE TITLE
Questions index contains count of Answers and Comments

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#6832]
I noticed that the /questions/ page is showing a count for Answers as well as a count for Comments, but Answers is depreciated and needs to be removed.

Currently it looks like this:

![FireShot Capture 072 - 🎈 Public Lab_ Questions and Answers - publiclab org](https://user-images.githubusercontent.com/49460529/69368243-bd945080-0c67-11ea-9157-efe198caf728.png)

What does everyone think about right-aligning the links like this to make it look a bit neater?
![FireShot Capture 071 - 🎈 Public Lab_ Questions and Answers - localhost](https://user-images.githubusercontent.com/49460529/69368182-9e95be80-0c67-11ea-80c3-5b1391823b5f.png)

**Comment by jywarren** [comment]
This sounds good to me. As to styling, however, I wonder if we should, per
the style guide, refactor questions to use the new "card" design?

**Comment by nstjean** [comment]
I'll look at what needs to be done to achieve that!

**Comment by jywarren** [comment]
The /views/notes/_notes.html.erb file may be a good place to start! Awesome!
