### ISSUE TITLE
Give comment upload script unique IDs to properly place images

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6833]
When uploading an image to a comment, esp if it's not the first comment, it looks like we're displaying the progress bar and inserting the image into the wrong textarea, probably due to non-unique html id attributes! See:

![Screenshot_20191121-153429](https://user-images.githubusercontent.com/24359/69374767-cb9c9e00-0c74-11ea-8aac-37f2fdac66cf.png)

Instead of showing the file here, it appeared in the "reply to" textarea of the top comment:

![Screenshot_20191121-153420](https://user-images.githubusercontent.com/24359/69374794-deaf6e00-0c74-11ea-9e18-addbdb4e0002.png)

Let's fix this!

**Comment by jywarren** [comment]
Code for the comment form is here:

https://github.com/publiclab/plots2/blob/master/app/views/comments/_form.html.erb

And it's includes into each note page here:

https://github.com/publiclab/plots2/blob/master/app/views/notes/_comments.html.erb

And the JavaScript for uploading is here:

https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/dragdrop.js

**Comment by SidharthBansal** [comment]
Published on GCI dashboard
