### ISSUE TITLE
Update map.html.erb - replace http with https

### ISSUE THREAD

**Issue by IvetaHron** [publiclab/plots2#6834]
Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.

Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [map.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/users/map.html.erb) in the `
plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

<img width="984" alt="PublicLab 1" src="https://user-images.githubusercontent.com/48660940/69376473-36180300-0ca2-11ea-9a9d-3938824b7905.png">

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by npang4** [comment]
Can i claim this?

**Comment by AbhinavMir** [comment]
Is this claimed? I'd love to work on this.

**Comment by IvetaHron** [comment]
Hi @npang4, @AbhinavMir thank you for your interest to solve this issue, but the task is reserved for Google Code-in (GCI) participants. You can have a look on our page : https://code.publiclab.org for more issues.

**Comment by Uzay-G** [comment]
Hey! I would like to claim this and will apply to the google codein. Can I fix the issue or should I wait until the registration date?

**Comment by IvetaHron** [comment]
Hi @Uzay-G if you are GCI participant, the issue is yours. Thank you.

**Comment by Uzay-G** [comment]
> 
> 
> Hi @Uzay-G if you are GCI participant, the issue is yours. Thank you.

Yeah ok I will take care of it. I will apply to GCI in december when registration is open

**Comment by IvetaHron** [comment]
Hi @Uzay-G, thank you for creating a PR for this issue, but would you please edit it little further. You need to replace both 'http' for 'https' on the line 53, not only one. And look at the line 73, there are more two 'http' that need to be replaced.

**Comment by Uzay-G** [comment]
> 
> 
> Hi @Uzay-G, thank you for creating a PR for this issue, but would you please edit it little further. You need to replace both 'http' for 'https' on the line 53, not only one. And look at the line 73, there are more two 'http' that need to be replaced.

Oh thank you @IvetaHron, I hadn't seen that at all but added it to my pull request. Thanks again.

**Comment by IvetaHron** [comment]
Thank you @Uzay-G for editing you PR. All good now.
