### ISSUE TITLE
full text search of tags slows site down

### ISSUE THREAD

**Issue by icarito** [publiclab/plots2#6835]
![imagen](https://user-images.githubusercontent.com/199755/69397663-248c2680-0cb5-11ea-84b3-09f8b721a846.png)

Here's a closeup of a peak moment, when response times came down a lot. There was a report at the chat from gitter, that the site was unresponsive. From the alerts we've been getting from Rackspace, this happened for about 8 minutes a time about 9 times today.

### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by icarito** [comment]
Another such peak:
![imagen](https://user-images.githubusercontent.com/199755/69398039-7c775d00-0cb6-11ea-9238-0b76a0b1aab6.png)

**Comment by icarito** [comment]
This happened again this morning and was reported by @steviepubliclab on the chat channel.
Should we block this route for now?

**Comment by jywarren** [comment]
Are we hitting the route when searching from the navbar? 

![image](https://user-images.githubusercontent.com/24359/69442007-c8a7b900-0d19-11ea-8091-b9a45ee8ab75.png)

**Comment by jywarren** [comment]
Yes, i think so:

![image](https://user-images.githubusercontent.com/24359/69442706-0ce78900-0d1b-11ea-9431-8cf4bbde958f.png)

Damn, why is that url cache-busting the response? 

https://publiclab.org/api/srch/tags?query=conduc&_=1574439550078

`&_=1574439550078` ???

**Comment by jywarren** [comment]
I'm going to push the front-page caching again but i really am not sure why this particular route is suddenly causing trouble...

**Comment by jywarren** [comment]
Ah, forget the timestamp, i think it was on the URL i sent the search /from/. 

I have an issue open on Grape to ask why this is an inefficient query vs another we use that's very efficient but bypasses Grape: https://github.com/ruby-grape/grape/issues/1890#issuecomment-508805254

They'd suggested we add better instrumentation to diagnose. 

For the short term, we might want to switch from the current API call which averages 3.5 seconds, to the non-API call which returns the same results in average 116 milliseconds. 

That is featured on our `/tags` page, and is run with this script:

https://github.com/publiclab/plots2/blob/158594acacb46a5416c72215716abd6c1b60f52d/app/views/tag/_sorting.html.erb#L19-L38

They both use the same `typeahead()` library, so we could refactor the relevant parts of this section to use the alternative URL:

https://github.com/publiclab/plots2/blob/9909ef0f3aacfee85901818fdf30352367f4a8e6/app/assets/javascripts/restful_typeahead.js#L10-L27

**Comment by jywarren** [comment]
The faster query returns just an array of strings:

```
["conductivity","conduct","code-of-conduct","question:conductivity","parent:conductivity","activity:conductivity","codes-of-conduct","question:conduct","water-conductivity","parent:conduct"]
```

The slower one returns larger objects, but the same basic info:

```
{"items":[{"doc_id":7613,"doc_type":"TAGS","doc_url":"/tag/conductivity","doc_title":"conductivity","doc_score":null,"doc_author":null,"doc_image_url":null,"latitude":null,"longitude":null,"blurred":null,"category":"TAGS"},{"doc_id":12921,"doc_type":"TAGS","doc_url":"/tag/conduct","doc_title":"conduct","doc_score":null,"doc_author":null,"doc_image_url":null,"latitude":null,"longitude":null,"blurred":null,"category":"TAGS"},{"doc_id":14827,"doc_type":"TAGS","doc_url":"/tag/code-of-conduct","doc_title":"code-of-conduct","doc_score":null,"doc_author":null,"doc_image_url":null,"latitude":null,"longitude":null,"blurred":null,"category":"TAGS"},{"doc_id":15636,"doc_type":"TAGS","doc_url":"/tag/question:conductivity","doc_title":"question:conductivity","doc_score":null,"doc_author":null,"doc_image_url":null,"latitude":null,"longitude":null,"blurred":null,"category":"TAGS"},{"doc_id":16120,"doc_type":"TAGS","doc_url":"/tag/activity:conductivity","doc_title":"activity:conductivity","doc_score":null,"doc_author":null,"doc_image_url":null,"latitude":null,"longitude":null,"blurred":null,"category":"TAGS"}],"srchParams":{"query":"conduct","seq":null,"tag":null,"nwlat":null,"nwlng":null,"selat":null,"selng":null}}
```

**Comment by jywarren** [comment]
So this would be the change:

```js
     query = query.replace(' ', /-/g); // replace spaces with hyphens
     var encoded_query = encodeURIComponent(query); 
     var qryType = $(el).attr('qryType'); 
        if (qryType == "tags") {
          var queryUrl = '/tag/suggested/' + encoded_query;
        } else {
          var queryUrl = 'api/srch/' + qryType + '?query=' + encoded_query;
        }
        if (window.hasOwnProperty('ga')) {
          tracker = ga.getAll()[0];
          tracker.send("pageview", queryUrl + '&typeahead=true');
        }
        if (qryType == "tags") {
         return $.post('/tag/suggested/' + encoded_query, {}, function (data) { 
           var objects = data.map(function(a) { return { doc_url: '/tag/' + a } });
           return process(objects);
         });
        } else {
          return $.getJSON('/' + queryUrl, function (data) {
            return process(data.items);
          },'json');
        }
```

**Comment by icarito** [comment]
Thanks for the quick action yesterday. We're still seeing performance degradation today! :-(
![image](https://user-images.githubusercontent.com/199755/69481207-3bc63380-0ddd-11ea-9980-a6837674c3d6.png)
Still it points to the full text search function.
