### ISSUE TITLE
Peg `friendly_id` to a version, as v4 and v5 are not compatible

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#684]
tests were passing on my dev machine at `v4.0.10.1`

**Comment by ananyo2012** [comment]
Yes indeed it is. But friendly_id 5.0 isn't compatible with Rails 3. By default the compatible version is friendly_id 4 and that is what get installed with `bundle install`. I don't think we need to mention the version no.

**Comment by jywarren** [comment]
Maybe we can just leave a comment in the gemfile for future notice, when we
do a rails 4 port.

**Comment by ananyo2012** [comment]
Ok I will do it.

**Comment by ananyo2012** [comment]
Include in #692
