### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by Uzay-G** [publiclab/plots2#6841]
I noticed at 18h00 that the website is down and at this time still is. I entered the url https://publiclab.org/ and tried to connect from my phone and computer on two different networks.
This is the resulting error:
```
Our website is having some trouble.
See our monitoring graphs to see what's going on.
Please help us figure out what happened so we can fix it!
If possible, please describe:
    - what you did just before the problem occurred
    - any web addresses needed to see the problem (such as the URL of this page)
    - your PublicLab.org username (if you have one)

or send an email to web@publiclab.org with the above information.

Thank you for helping to improve open source software!.
Ask for help in the Public Lab chatroom
Community members and staff may be able to help you in real time.
```
Do you know why this is happening? The site was working for me at about 17h50. I hope this helps you solve the problem.

**Comment by jywarren** [comment]
Thanks for reporting! We are rushing in a fix at #6835 and #6840.

**Comment by Uzay-G** [comment]
Website is now back to normal

**Comment by jywarren** [comment]
Thanks!
