### ISSUE TITLE
Weekly community Check-In #40 - "Pre GCI Preparation!"

### ISSUE THREAD

**Issue by pydevsg** [publiclab/plots2#6845]
Hi everyone 👋

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. 💯

## **Pre GCI Preperation!** 💻 
We are 1 week  to this year's Google Code-in program 🎉 . In order to kick start this event we will need to have at least 100 tasks published in GCI Dashboard. We need to have the tasks published in GCI dashboard and linked to github so that they can be updated when these issues are completed by the students 

 ### How well are we prepared 🤔 
We currently have more than 40 published tasks as said by @SidharthBansal in the [channel](https://gitter.im/publiclab/publiclab) previously. 

### How you can help  👨‍💻 👩‍💻
- Format an issue you have an idea on how to solve to have more context and add `gci-candidate` label on it. Mention @SidharthBansal  or @cesswairimu  so that they can have it created on the gci dashboard
- If you are a mentor create some tasks on the dashboard if you have some time to spare within the week, mark the issue with the label `reserved-for-gci`  on github and @SidharthBansal shall review and have it published. 
- If you create an issue that seems like a potential gci task...please add a `gci-canditate` label on it.

 As being part of this community , I think if we all come up together we can achieve 💯  this within the given deadline.👐 

Wishing all the best to the junior coders who will be getting started to the world of open source.
Excited to help them enter this world #open source ❤️ 

### Next Check-in
Sasha shall open the next check-in

**Thanks everyone for making Public Lab so reliable . Hope it remains 🔝 as usual 🎉**

**Comment by pydevsg** [comment]
@jywarren @SidharthBansal @cesswairimu @gauravano @ebarry

**Comment by pydevsg** [comment]
@Rishabh570 @sashadev-sky @IshaGupta18  @vaibhavmatta @shubhscoder @aSquare14 @sidntrivedi012  @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77 @milaaraujo @kevinzluo

**Comment by SidharthBansal** [comment]
Hello, we want at least 60 more tasks to be in GCI. Only 8 days left. So, let's speed up on this folks.

Thanks for all the help towards GCI :-) :+1: :100:

**Comment by skilfullycurled** [comment]
The task I would like to add is for me to say hello to everyone.

I haven't had a chance to connect in a while and I've been thinking a lot about the community lately.  

If my numbers are correct (and they are not), I think that means we only need 59 more tasks now?

Wait.  Shoot.  I completed the task.  Never mind, we're back to 60 again.  

Gah!  How many times do I have to tell myself?!  Think before you act.  Think before you act.  Think!

: P

(Sorry to go off topic but hey, it is a community check in, no?)

**Comment by nstjean** [comment]
Hello all!

Last week I finished up #6821 and worked on #6422 and have started working on restyling the /questions/ index to match the style guide.

This week I'm going to be adding tasks for GCI! I'm also going to be preparing to start the Outreachy project next week, if I get selected. :)

**Comment by jywarren** [comment]
Hi all! with our testing/staging/stable/unstable servers back online, i'm a bit more relaxed this week, and we have some holiday days off this Thursday and Friday, so it's a short week here! So for me, it's time to catch up on the self-care and get rested for the start of Outreachy and GCI! 😴 

I did want to announce we've posted our new front page design at https://publiclab.org, (or https://publiclab.org/home if you're logged in), which has been a LONG time in the making! And we redid our navbar (hopefully for the last time in a while!) so the site is looking sharp!

Thanks for all the hard work in recent weeks!

**Comment by cesswairimu** [comment]
Hello :wave: everyone, 

Congrats @nstjean and @crisner  :tada: :tada:  for being accepted to the Outreachy program . We are extremely grateful to all the other applicants, for your work with us to date and that we welcome you to continue being part of this community. It sucks that we had limited slots and could not accept more. 

The new PL homepage looks great :rocket:  thanks to all who worked to make this possible :1st_place_medal: :1st_place_medal:.
This week I am working finishing up on the new simple template and I also be helping in creating gci tasks

Great rest of week everyone

**Comment by crisner** [comment]
Thanks, @cesswairimu! Congratulations @nstjean!🎉

**Comment by SidharthBansal** [comment]
Congrats @nstjean and @crisner.
New homepage is awesome : 💓

**Comment by nstjean** [comment]
Thank you!! Congrats @crisner I look forward to working with you!

**Comment by crisner** [comment]
Thank you @SidharthBansal and @nstjean! I look forward to working with you as well @nstjean!

**Comment by SidharthBansal** [comment]
Hello everyone!

This is the progress so far!
![image](https://user-images.githubusercontent.com/20972099/69854786-f360b700-12af-11ea-87b6-fa552e627e9c.png)

Superb folks! You did a lot of work :-)

Thanks

**Comment by SidharthBansal** [comment]
Hello Folks,
We ultimately did it :-)
👍 💯 🎖 🚀 
![image](https://user-images.githubusercontent.com/20972099/69913316-41b2b900-145c-11ea-8905-4b73491ed20c.png)
I am so happy to have a pool of really helpful mentors this winter, you all are doing an amazing job. You all must be proud of yourself. We did an initial set of tasks.
This week PR review grading of GCI students is done by @keshav234156 so all the GCI students can catch him to get points for it.
We are all set for GCI folks! Superb! 🎉 🎉 🎉 
This year we are focussing on Quality over Quantity. Make sure that the PRs have screenshots, detailed titles, tests if required and proper documentation. Make sure that the work inside PRs are done in proper commits with commit title and commit details. I know its tough but this is what we as mentors have to teach new students to OS. 🚀 🚀 

Sorry for being stricter this year. Last year's student suggested improving quality of tasks as they were ambiguous. 

This is most probably the first mentoring session for most of you. 🥇 This will be challenging and a bit overwhelming when you will get 100 emails. Just remember that these students will be in future developers. So, it's our responsibility to guide them the best.
Best of luck to all the mentors :-)
(We will say best of luck to the student when GCI starts. This post is for GCI Pre-Planning 😅 )
In case of any doubts feel free to reach to me. 

Btw I detected the person who was writing tasks for me on GCI dashboard. It's a secret. I will not tell you folks about them. I came to know that I am good at investigation this GCI 2019-20. 🔢

**Comment by SidharthBansal** [comment]
All mentors are requested to visit https://github.com/publiclab/plots2/issues/6808 and edit it if needed. 
Also, it is mentor's responsibility to redirect their students to this post so that we can warmly welcome them :-)

**Comment by SidharthBansal** [comment]
Please don't ask personal information like name, age, gender, etc from any student. Students are not allowed to post anything except code and documentaion.
Thanks

**Comment by jywarren** [comment]
@SidharthBansal and everyone who helped make this happen -- tremendous work!!!! 🎉🎉🎉🎉🎉🎉🎉

This is an amazing effort. Great job, everyone!

**Comment by cesswairimu** [comment]
Hey @sashadev-sky, you had expressed interest of opening this week's next check-in...kindly let us know if you are still available to do that..Thanks all for getting gci ready :tada: :tada:

**Comment by SidharthBansal** [comment]
I guess Sasha is busy. Who is willing to open next weekly check in?
I want some adventurous theme this week. Should we write the most stupid
thing I ever done in life OR the most thrilling or adventurous thing ?
It has been many weeks we haven't done fun weekly check-ins
Let's discuss theme first!

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/mapknitter/issues/1150. Thanks everyone
