### ISSUE TITLE
Align password view button

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#6846]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
![image](https://user-images.githubusercontent.com/20972099/69555164-c15a0700-0fc8-11ea-877e-0681703fdda3.png)
Login modal has alignment problems with password

> What did you expect to see that you didn't?

Proper alignment

### Please show us where to look

https://publiclab.org/ 
login modal by clicking on login button in upper right corner

**Comment by qw3eq** [comment]
Can I claim it?
I already know how to fix it.

**Comment by SidharthBansal** [comment]
Hi this issue is reserved for GCI candidates. You can check other issues.
Thanks

**Comment by debck** [comment]
hey, @SidharthBansal This issue is duplicate of  #6847

**Comment by SidharthBansal** [comment]
Thanks
