### ISSUE TITLE
Expand use of x icon for tags

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6849]
**Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**

Follow-up to #6791, we have the new icons working for newly added tags but not for existing ones, as shown below; see 

![image](https://user-images.githubusercontent.com/24359/69564020-37864b80-0f80-11ea-8439-e2e0398a0c50.png)

versus any of the older tags which still use an `x` character instead of an icon. 

![Screenshot_20191123-155359](https://user-images.githubusercontent.com/24359/69563377-fb062000-0f7e-11ea-85ff-bf5fd6a6a7b7.png)
To fix this, we'll need to replace the `x` character on these two lines, with the same icon as in https://github.com/publiclab/plots2/issues/6791 -- 

```html
<i class='fa fa-times-circle fa-white blue pl-1' aria-hidden='true' ></i>
````

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by jywarren** [comment]
To fix this, we'll need to replace the `x` character on these two lines, with the same icon as in https://github.com/publiclab/plots2/issues/6791 -- 

```html
<i class='fa fa-times-circle fa-white blue pl-1' aria-hidden='true' ></i>
````

@susanreenesaa were you interested in adding this follow-up FTO? 

Thanks everyone!

**Comment by jywarren** [comment]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by kubakorniluk** [comment]
Hi, i claimed this issue

**Comment by jywarren** [comment]
Awesome! Thank you!

**Comment by SidharthBansal** [comment]
@kubakorniluk this task is intended for GCI. Only GCI students are requested to solve this task. If you are not a GCI student then please see other tasks which don't have GCI label.
Thanks

**Comment by MariMachaidze** [comment]
hey, I just claimed this task.

**Comment by SidharthBansal** [comment]
Please read the welcoming post for GCi and do 2 ftos before attempting
other issues. Thanks
Best of luck

**Comment by MariMachaidze** [comment]
Where can I see the code to fix?

**Comment by jywarren** [comment]
Hi, I wonder if this has been fixed by @nstjean already? I believe it is already updated on PublicLab.org. I'm sorry if this got mixed up! Thank you!

**Comment by SidharthBansal** [comment]
@nstjean please look into this. If it is fixed already then we can give MariMachaidze approval on the dashboard so that other GCI students will not claim this task.
Thanks

**Comment by nstjean** [comment]
Oh no! I'm sorry! I think I did. :(

**Comment by SidharthBansal** [comment]
Can we close this?
