### ISSUE TITLE
Fix error in ordering of notes by number of likes

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/plots2#6850]
**Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

# Description
The notes when displayed in sorted order by no of likes, ie in /notes/liked, the notes appear in random order neither asc nor desc wrt number of likes.

![likes](https://user-images.githubusercontent.com/32260628/54584566-badcbe00-4a3d-11e9-9d51-074d79c6e785.png)

# Expected 
The notes must be sorted based on desc order of no of likes.

**Comment by SidharthBansal** [comment]
Published

**Comment by Uzay-G** [comment]
Hi @ananya I am going to work on this task. Thanks

**Comment by SidharthBansal** [comment]
Cool

**Comment by ananyaarun** [comment]
Hey @Uzay-G  Awesome :tada: 
Btw you tagged the wrong ananya :laughing: 
my handle is "ananyaarun"

**Comment by SidharthBansal** [comment]
This happened a lot of times. Lol
