### ISSUE TITLE
Add on hover effects to the link "Public Lab" on navbar

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/plots2#6851]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**

The link to home page on the website ie "Public Lab" visible on the top left corner of the navbar is a bit ambiguous to users as it doesn't stand out as a "link" to home page. Hovering over it causes no effect at the moment either.

![publiclab](https://user-images.githubusercontent.com/32260628/54756036-5ec89400-4c0d-11e9-938a-aee76a7629c9.png)

- On hover effect needs to be added to this to make it look/behave more like a link.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by SidharthBansal** [comment]
Published

**Comment by ygaitonde** [comment]
Hi, I claimed this issue!

**Comment by SidharthBansal** [comment]
Are you a GCI student?
THis issue is reserved for GCI students only

**Comment by ygaitonde** [comment]
Yes, I am.

**Comment by SidharthBansal** [comment]
Great!

**Comment by SidharthBansal** [comment]
Go ahead!
Have you installed the repository? If no then please go ahead and install it!

**Comment by ygaitonde** [comment]
Yes, I have forked it and cloned it to my local machine. Is there any better place to chat than on this issue? I will need some help as this is my first time contributing open-source :)

**Comment by SidharthBansal** [comment]
This is open source so this is the best place to discuss things :-)

**Comment by ygaitonde** [comment]
I'm following through the README.md on plots2 to get started, and I'm stuck where I am supposed to enter 'passenger start' at the . I am facing the error passenger: command not found.

**Comment by SidharthBansal** [comment]
Hello Yash,
We are glad to see that you have started working on Installation. :tada:
Don't forget to upload a screenshot after a successful installation and get
points for your installation task :-) :+1:
If you are using Ubuntu then you have to do passengers start at the
terminal. If windows then please do it at a command prompt.
Feel free to see the list of mentors for plots2 repo and ask help from them
anytime.
Thanks
SIdharth

**Comment by NitinBhasneria** [comment]
@ananyaarun @SidharthBansal Is their is need of hover now. If yes please tell so that I can fix it.

**Comment by SidharthBansal** [comment]
I am in favour of hovering effect

**Comment by NitinBhasneria** [comment]
Ok so I will be working on this @SidharthBansal

**Comment by SidharthBansal** [comment]
Great

**Comment by SidharthBansal** [comment]
Sorry this is a first timer issue. You cannot work on it as it is for people new to Public Lab community 
@VladimirMikulic i will require some help. Please edit the GCI issues. Remove the line reserved for GCI and add `first-timer-issue` and other related labels as soon as you get some time.
Thanks

**Comment by SidharthBansal** [comment]
Also, we need to hide the unwanted comments as these issues are now for generic population(including SOC aspirants)
SoC = Outreachy + Google Summer of code

**Comment by VladimirMikulic** [comment]
@SidharthBansal I am on it :+1:

**Comment by SidharthBansal** [comment]
Thanks

**Comment by av-00** [comment]
Is this issue completed?

**Comment by VladimirMikulic** [comment]
@av-00 thank you for your interest in solving this issue. It would be great if you could inspect this :)

**Comment by av-00** [comment]
@VladimirMikulic  Is the necessary file plots2/static/index.html?
I hope I have run the project correctly! Attached is the screenshot. Please tell me if I have errors.
![Screenshot from 2020-03-12 20-25-16](https://user-images.githubusercontent.com/43967251/76534687-d6877280-649f-11ea-8497-90cb5fb16310.png)

**Comment by VladimirMikulic** [comment]
@av-00 the file that you are looking for is `plots2/app/assets/stylesheets/style.css`

**Comment by javila35** [comment]
Hi, has this issue been completed? 

If not, I would like to take it on. New to Public Lab and open source, this would be my first contribution.

**Comment by jywarren** [comment]
Hi all! Sorry for the very slow response here. This issue is still open for anyone to claim -- not just GCI participants. Thanks!!!

**Comment by ishaanmehta4** [comment]
Is this issue open for contribution? 
I am new to open source contributions, and would want to work on it for hacktoberfest.

**Comment by ananyaarun** [comment]
Sure @ishaanmehta4 , Go ahead !

**Comment by Iamhafsah** [comment]
Hi. I see that this issue is still open. can I work on it for the Outreachy internship?

**Comment by jywarren** [comment]
that would be great! Thanks so much for your help, and let us know if you
need anything!

**Comment by bcanty92** [comment]
is Add on hover effects to the link "Public Lab" on navbar #6851 still available ? if so I would like to claim it .

**Comment by shallom-dot** [comment]
Hello @ananyaarun please  assign this issue to me. Thank you!

**Comment by jywarren** [comment]
Hi! Unfortunately it looks like this was completed! I'm going to close it but please see https://code.publiclab.org for more!

![image](https://user-images.githubusercontent.com/24359/96624656-066ee200-12db-11eb-839c-c30f0e08fe91.png)
