### ISSUE TITLE
Add a tooltip on "Public Lab" that says  "Home" on navbar

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/plots2#6852]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**

Let add a tooltip on hover with the words "home" on hover on the PublicLab text,
![publiclab](https://user-images.githubusercontent.com/32260628/54756036-5ec89400-4c0d-11e9-938a-aee76a7629c9.png)

-  A tooltip needs to be added here that says home.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by SidharthBansal** [comment]
Published

**Comment by someshkar** [comment]
Hey! I just claimed this issue.

**Comment by jywarren** [comment]
Hi all, i'm sorry, but this issue makes modifications to the navbar, which is a reserved area -- discussion with @publiclab/community-reps is required before making changes here! 

However, let me suggest that instead of changing the text, we add a tooltip, that says "Home" -- like this:

![image](https://user-images.githubusercontent.com/24359/69989200-1c33b700-1511-11ea-852d-56cc963d6ecd.png)

That way, this issue can remain and @someshkar can complete it without needing design discussion. 

Tooltips like this can be achieved via Bootstrap, and here is some documentation!: https://getbootstrap.com/docs/4.3/components/tooltips/

**Comment by someshkar** [comment]
@jywarren so do I do that instead?

**Comment by jywarren** [comment]
Yes please, that would be great. Thanks!

**Comment by someshkar** [comment]
Hey, I abandoned this task for now.

**Comment by ananyaarun** [comment]
Hi @someshkar ,
I believe you are a GCI student. Sorry for the confusion, Take a look at other issues that interest you with the label 'gci-candidate'

**Comment by someshkar** [comment]
@ananyaarun yeah, I'll do that, thanks!

**Comment by SidharthBansal** [comment]
Ananya can you please modify the task as per Jeff's comments at both GCI
dashboard and here.
Thanks

**Comment by SidharthBansal** [comment]
Don't forget to hide unwanted comments and ping me at gitter pm to save the
changes at the dashboard (if I have to)
Thanks

**Comment by nightlan1015297** [comment]
Hi

**Comment by SidharthBansal** [comment]
Hello

**Comment by jywarren** [comment]
Created an FTO in https://github.com/publiclab/plots2/issues/8501!
