### ISSUE TITLE
Margin on /stats page pushes content off screen

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#6853]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

On the page https://publiclab.org/stats the div block at the top pushes off to the right of the view screen on screens less than 1354px wide. In the file `app/views/stats/index.html.erb` :

https://github.com/publiclab/plots2/blob/833e0b69a7124f61e0f02ea42d549f7871ddd600/app/views/stats/index.html.erb#L1

You will have to try some different CSS to get it to fit properly on the page and have a margin on both sides at large screen sides. The margin should not apply at mobile and small screen sizes.

Here is what it looks like now (div highlighted to show it going off screen):

![FireShot Capture 074 - 🎈 Public Lab_ Stats - localhost](https://user-images.githubusercontent.com/49460529/69648760-e9358300-1039-11ea-8cf8-eeafdbeb64ac.png)

**Comment by nstjean** [comment]
@SidharthBansal Can you add this to the GCI dashboard and whatever else you need to do?

**Comment by SidharthBansal** [comment]
Thanks. I have published the issue on the GCI dashboard!
