### ISSUE TITLE
Error occurs on tag/TAGNAME/stats/ if tagname does not have any posts

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#6854]
**Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

When someone tries to view the stats page for a tag that does not exist we get an error. It would be really nice if we could display a page that says, for example, "Wiggles not found."

Example: https://publiclab.org/tag/wiggles/stats

In the tag_controller there is the function `stats` that control what content is shown on that page:
https://github.com/publiclab/plots2/blob/833e0b69a7124f61e0f02ea42d549f7871ddd600/app/controllers/tag_controller.rb#L533-L551

In https://github.com/publiclab/plots2/blob/master/app/views/tag/stats.html.erb we will also have to use some IF statements to display the message if there's no content.

**Comment by nstjean** [comment]
@SidharthBansal Here's another one!

**Comment by SidharthBansal** [comment]
We still need 70 more issues. Can you please help me in labelling some more issues?
It will be great help!

**Comment by nstjean** [comment]
Yes, I will add more this weekend!

**Comment by SidharthBansal** [comment]
Published on GCI website
