### ISSUE TITLE
Style "add a location" button to match style guide

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6856]
Pages like https://publiclab.org/wiki/london-uk have a prompt to add a location:

![image](https://user-images.githubusercontent.com/24359/69657303-f6f20500-1047-11ea-8fb6-d3ee147117cd.png)

However, the [style guide](https://publiclab.org/notes/warren/05-07-2019/introducing-a-draft-style-guide-for-public-lab) shows we should be showing them in a button like this:

![image](https://user-images.githubusercontent.com/24359/69657369-138e3d00-1048-11ea-9180-de0ac3659d48.png)

The icon should be: `<i class="fa fa-map-marker" style="color:#c40;"></i>`

And the text should be (on this page) "Add a location" and not "Add your location". 

We'd love help fixing this!

The code for it is here: 

https://github.com/publiclab/plots2/blob/1cfd91a87c7333718960a20b560857c88920c0d3/app/views/sidebar/_related.html.erb#L48-L54

**Comment by jywarren** [comment]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by kushaggarwal** [comment]
Hi @jywarren 
As I understood from the above mentioned information about the issue is to change the "add your location" button into the new format as mentioned by you for which the reference code you have given above right

**Comment by jywarren** [comment]
That's right! Thanks!

**Comment by SidharthBansal** [comment]
Hi @kushaggarwal are you working on this?

**Comment by kushaggarwal** [comment]
Hello @SidharthBansal yes I am

**Comment by SidharthBansal** [comment]
Go ahead. Thanks

**Comment by jywarren** [comment]
Just noting this could be related to #6899 and cc'ing @nstjean !

**Comment by jywarren** [comment]
Hi @kushaggarwal are you still working on this? Need any help? Thanks!

**Comment by jywarren** [comment]
If you aren't able to continue, maybe we can open this up for someone else? Thanks, either way works!

**Comment by pianeta051** [comment]
@kushaggarwal are you still working on this....If not please let us know, because I am interested in this.
thanks

**Comment by jywarren** [comment]
Hi @pianeta051 we'd love your help, it seems like this is open!

**Comment by kushaggarwal** [comment]
Hello guys,
Sorry for the answering so late 
Got stuck with my university exams therefore wasn't able to reply
@pianeta051 please go ahead as I am facing some problem with setting up the project 
so, you can go ahead with the issue meanwhile I will try to solve the problems with setup on my end 
Thank you

**Comment by dmahajan980** [comment]
I would like solving this issue as my first contribution to open source. Can I work on this?

**Comment by nstjean** [comment]
@dmahajan980 I just assigned another issue to you: https://github.com/publiclab/plots2/issues/6516

**Comment by jywarren** [comment]
If nobody's taken this up still, it's still available! Please leave a comment and open a pull request if you get started, thanks!

**Comment by sssash18** [comment]
@jywarren I would like  to do this.

**Comment by SidharthBansal** [comment]
Hi @sssash18 only one FTO/ first timers only issue per person is allowed. Please don't do more ftos 
We will merge this one. But don't do more ftos.
You can do as many issues as you want which don't have `fto` tag nor `first-timers-only` tag
Thanks

**Comment by sssash18** [comment]
Ok @SidharthBansal ,I will  take care next time .Sorry for the misdeed.
