### ISSUE TITLE
Remove tag parenting UI from templates

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6864]
**Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**

Let's remove this section from the code, as we are no longer providing this admin feature!

https://github.com/publiclab/plots2/blob/97d0142d9e8b8ceb62513e7f1a3471fdeadfa8da/app/views/tag/show/_user_controls.html.erb#L34-L51

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by SidharthBansal** [comment]
Published

**Comment by myungwoo-Y** [comment]
Can I take this issue?

**Comment by SidharthBansal** [comment]
Hi, this issue is reserved for GCI students. So, you can't work on it if you are not GCI student.
Please see other issues which are not labelled with gci based labels.
Thanks

**Comment by chen-robert** [comment]
Hello @SidharthBansal, can I claim this task?

**Comment by SidharthBansal** [comment]
You can claim it after completing installation task for plots2.
Thanks

**Comment by SidharthBansal** [comment]
And please ping all the mentors of the repo instead of only one mentor. As time zones vary a lot

**Comment by CodeSarthak** [comment]
Hey, this task is still there on GCI but it is closed here. Please take appropriate action @SidharthBansal @jywarren

**Comment by SidharthBansal** [comment]
Can you please check whether this task is completed or not?

**Comment by SidharthBansal** [comment]
@chen-robert did you take points for this task?
