### ISSUE TITLE
Option to not receive email notifications for topics you follow

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6867]
Similarly to #4543, and in relation to #6787, we should make an option in https://publiclab.org/settings to turn off email notifications for topics you follow. You might still get notified via the Notifications API (like, smartphone notifications, etc), and you'd still see topics you follow listed on your dashboard (new dashboard at #6072).

New note email notifications are generated from this segment of code:

https://github.com/publiclab/plots2/blob/97d0142d9e8b8ceb62513e7f1a3471fdeadfa8da/app/mailers/subscription_mailer.rb#L8-L26

We need to modify this line, to make an exception for a) people who have a user tag showing they don't want to get email notifications for things they follow, so `notifications:none` perhaps? (we need to discuss/disambiguate this vs. the existing tags we use on the /settings page...)

https://github.com/publiclab/plots2/blob/97d0142d9e8b8ceb62513e7f1a3471fdeadfa8da/app/mailers/subscription_mailer.rb#L16

You can determine if a user has a tag like this:

```ruby
UserTag.exists?(user.id, 'digest:weekly')
```

https://github.com/publiclab/plots2/blob/master/app/views/users/settings.html.erb

(Possibly useful links: The settings were previously worked on in https://github.com/publiclab/plots2/pull/2985/ and https://github.com/publiclab/plots2/pull/3119 and digests are sent from https://github.com/publiclab/plots2/blob/7e20e413e94925a4f021f14e61a36b7ebb270e25/app/jobs/digest_mail_job.rb)

**Comment by jywarren** [comment]
Existing tags for this kind of thing are formatted like: `notifications:mentioned` so perhaps `notifications:noemail` (just so it specifically means no emails, as opposed to turning off other kinds of notifications)?

Then we'll need a UI on this page, https://publiclab.org/settings :

![image](https://user-images.githubusercontent.com/24359/69747692-e0fe4600-1114-11ea-9ab9-06f1e307a94f.png)

**Comment by steviepubliclab** [comment]
<img width="481" alt="Screen Shot 2019-11-27 at 1 01 13 PM" src="https://user-images.githubusercontent.com/7490478/69748715-f8d6c980-1116-11ea-9a52-6e9a67b6df87.png">

**Comment by jywarren** [comment]
So the switch we'd have to add to the subscription_mailer.rb file would be:

```ruby
recipients += node.author.followers.collect(&:email) 
recipients -= UserTag.where(value: 'digest:weekly').collect(&:user).collect(&:email) # exclude anyone who uses weekly digests
recipients -= UserTag.where(value: 'digest:daily').collect(&:user).collect(&:email) # exclude anyone who uses daily digests
```

Then we'd need to modify the tests to ensure this is working!

**Comment by steviepubliclab** [comment]
Text edit suggestions:

**Email Notifications**
I want to receive an email 
   Whenever there are new posts on topics I follow
   In a daily digest
   In a weekly digest
   Never

I want to be notified by email for:
   Comments on my posts
   Likes on my posts
   Comments on all posts I’ve commented on
 
**Browser Notifications** 
I want to receive browser notifications: 
   When I’m mentioned
   When someone likes my work
   Never

**Comment by jywarren** [comment]
OK awesome; the only thing is that "Never" wouldn't be an option that can have an "on/off" status, so I think for now we'll leave that off? If you'd like we can follow up with something where you click that and it automatically turns off the others, but it's a little more involved. Thanks!

**Comment by ebarry** [comment]
Regarding the "never" option, while the text Stevie suggested may not work for "never" in that way, does the graphic she drew up work?

**Comment by jywarren** [comment]
Yes, but ONLY for the first "All topics" row, so for now we will probably keep the page layout as it is. 

If in the future we set out to do a per-topic notifications settings system, we could adopt the table style view. Thanks!

**Comment by jywarren** [comment]
Is this otherwise ready to go? Thanks!

**Comment by jywarren** [comment]
Noting this is ready pending @publiclab/community-reps 👍 to be taken up; it will be very similar to #6282, which was fixed by #7183 and #7191. Thanks!

**Comment by Srija616** [comment]
@jywarren Hey! I am an Outreachy applicant. I would like to work on this, can you help me get started on this issue?

**Comment by ebarry** [comment]
Yes, speaking as a @publiclab/community-reps, this is ready to go 👍.

**Comment by jywarren** [comment]
I believe this is complete!

![image](https://user-images.githubusercontent.com/24359/114239142-abe24480-9953-11eb-8a18-24efef5d959f.png)

**Comment by jywarren** [comment]
The only thing we could consider re-opening this for is to reorganize this into radio buttons (i.e. choose between them, rather than toggle each one on or off):

![image](https://user-images.githubusercontent.com/24359/114239395-0a0f2780-9954-11eb-8f21-19af1409b87f.png)

And to add an extra option for "NEVER". However that would involve the ability to add the tag `notifications:noemail` which as of https://github.com/publiclab/plots2/pull/9269/ is evolving into a blanket policy of no emails (but is not there yet).

Closing but we can re-open a narrower project!

**Comment by ebarry** [comment]
Thank you! /Settings is looking really great and fresh.
