### ISSUE TITLE
Change texts for "settings" page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6871]
## Problem
We need to make some text adjustments on this page, https://publiclab.org/settings :

![image](https://user-images.githubusercontent.com/24359/69747692-e0fe4600-1114-11ea-9ab9-06f1e307a94f.png)

### To work on :
@steviepubliclab has developed some new text for it! Thanks!

```
Email Notifications

I want to receive an email

- Whenever there are new posts on topics I follow
- In a daily digest
- In a weekly digest

I want to be notified by email for:

- Comments on my posts
- Likes on my posts
- Comments on all posts I’ve commented on

Browser Notifications

I want to receive browser notifications:

- When I’m mentioned
- When someone likes my work
```

Let's make these text changes on this page: https://github.com/publiclab/plots2/commits/main/app/views/users/settings.html.erb

_Originally posted by @jywarren in https://github.com/publiclab/plots2/issues/6867#issuecomment-559195780_

**Comment by kushaggarwal** [comment]
I would like to work on this

**Comment by jywarren** [comment]
Please do, we'd love your help!

**Comment by pydevsg** [comment]
@kushaggarwal this issue is reserved for `gci-candidates` . Please look on other issues , thanks :)

**Comment by SidharthBansal** [comment]
@pydevsg this issue is already taken by @kushaggarwal so we can't keep it in GCI.
First come first serve is followed in OS. 
@kushaggarwal in case you want any help to solve this issue please feel free to ping me or any other mentor.
Best of luck @kushaggarwal 
Regards
Sidharth

**Comment by kushaggarwal** [comment]
Okay Thanks @SidharthBansal  
Will surely contact in case of any problem

**Comment by kushaggarwal** [comment]
Hi I was trying to set up the project inorder to work for the problem above but not able to set it up it says the error as shown image 
Can you please help
![Screenshot 2019-12-02 at 7 37 40 PM](https://user-images.githubusercontent.com/44523552/69965912-4b5f1e00-153b-11ea-9f27-819e14397218.png)

**Comment by SidharthBansal** [comment]
Have you updated your bundle and done bundle install?

**Comment by kushaggarwal** [comment]
Yes I have executed the bundle update command but it throws the below error first and then the one in above image
![Screenshot 2019-12-02 at 10 49 02 PM](https://user-images.githubusercontent.com/44523552/69980406-32b03180-1556-11ea-8993-1ce03af1f5fd.png)

**Comment by chen-robert** [comment]
@kushaggarwal 

I just tried it and the installation worked for me on Ubuntu 18.04.3 LTS. 

It appears you are running Mac OS, which might have some platform-specific problems. I found [this StackOverflow article](https://stackoverflow.com/questions/23536893/therubyracer-gemextbuilderror-error-failed-to-build-gem-native-extension) which might work for you. 

```
gem uninstall libv8
gem install therubyracer -v '0.11.3'
gem install libv8 -v '3.11.8.13' -- --with-system-v8
```

**Comment by cesswairimu** [comment]
Hi all, @kushaggarwal, were u able to fix your issue. Thanks @chen-robert :+1:

**Comment by kushaggarwal** [comment]
Yes I am on it will update you soon about the same

**Comment by kushaggarwal** [comment]
Thanks @chen-robert  for your help 
Will go through the article I hope this will work

**Comment by kushaggarwal** [comment]
Hi @chen-robert 
I went through the stackoverflow article you mentioned in the above message but was not able to resolve the error, the sam error still persists so can you please help 
Also can yo u please help what are the previously installed dependencies that should be installed in the system if any as I might be missing any leading to this error
Thanks

**Comment by cesswairimu** [comment]
Hey @chen-robert ,
You could try this command `gem update --system` if that fails try this `sudo apt-get install ruby-dev zlib1g-dev liblzma-dev`

**Comment by kushaggarwal** [comment]
Hello guys,
Sorry for the delay was caught up with my university exams 
Will soon make a pull request for the above issue
Thank You

**Comment by kushaggarwal** [comment]
Hello 
In above mentioned layout the slider buttons need to be there for each sub option in the heading like I want to be notified by email

**Comment by cesswairimu** [comment]
Hi @kushaggarwal, I believe the slider buttons are already in place...we need to change the text. Thanks

**Comment by kushaggarwal** [comment]
Okay Thank you will do so

**Comment by sssash18** [comment]
@publiclab/reviewers Can I take up this task if it's still not done?

**Comment by kushaggarwal** [comment]
Hello 
I am working on this one and will soon generate a pull request for the same 
Thank you

**Comment by sssash18** [comment]
Fine @kushaggarwal ,take your time to complete the task.Thanks

**Comment by NitinBhasneria** [comment]
@jywarren Can I work on this issue?

**Comment by kushaggarwal** [comment]
Hello 
I have already submitted a pull request regarding the same

**Comment by NitinBhasneria** [comment]
@kushaggarwal then you should edit your pr and write the issue number their in fixes.

**Comment by kushaggarwal** [comment]
Okay will do so 
Thank you

**Comment by SidharthBansal** [comment]
Great

**Comment by jywarren** [comment]
Hi folks, just noting that there was a very good start to this in https://github.com/publiclab/plots2/pull/7259 which could be build upon if someone else would like to take this up!

**Comment by Manasa2850** [comment]
I would like to work on this!
