### ISSUE TITLE
Remove depreciated Answers from QuestionController#unanswered

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#6878]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Right now https://publiclab.org/questions/unanswered/ is calculating whether or not a question has been answered by looking for the depreciated `answers` table. What we need to do is remove references to `:answer` and instead select all questions that have no comments.

**Comment by nstjean** [comment]
@SidharthBansal Here's another.

**Comment by SidharthBansal** [comment]
Published
