### ISSUE TITLE
Add test screenshot for tag stats page

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#6879]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

We need a screenshot for the tag stats page added to the test screenshots! An example on our live site is:
https://publiclab.org/tag/lego-spectrometer/stats

You can find info on running our tests here: https://github.com/publiclab/plots2/blob/master/doc/TESTING.md

**Comment by nstjean** [comment]
@SidharthBansal

**Comment by SidharthBansal** [comment]
Please label it `hard`, `medium` or `beginner`. If beginner than kindly reformat it to FTO template. 
Also, add **We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.** at top of issue body.
Do this for all the GCI issue you pinged me. That will be a great help. Thanks :-)

**Comment by nstjean** [comment]
@SidharthBansal  Ok will do!

**Comment by keshav234156** [comment]
@SidharthBansal **UPLOADED ON GCI DASHBOARD**

**Comment by SidharthBansal** [comment]
Published

**Comment by VladimirMikulic** [comment]
@nstjean @keshav234156  The site is not available in the development. How should I handle this?

![Screenshot_20191222_152755](https://user-images.githubusercontent.com/35997844/71323097-c29b2880-24cf-11ea-91c8-3f333ad1b385.png)

**Comment by nstjean** [comment]
Good question! So the pages that we see on the live site aren't in your local database, and moreover they aren't in the testing database either. The nodes that are created during tests are listed here:
https://github.com/publiclab/plots2/blob/master/test/fixtures/nodes.yml

Does that help?

**Comment by VladimirMikulic** [comment]
Hi @nstjean. Thank you for the fast response.
This nodes.yml if only for fixtures tests, the tag state page test belongs to system tests, right?

**Comment by nstjean** [comment]
You can read about fixtures here: https://api.rubyonrails.org/v3.1/classes/ActiveRecord/Fixtures.html
