### ISSUE TITLE
change the function t to translation of app/views/users/_likes.html.erb

### ISSUE THREAD

**Issue by govindgoel** [publiclab/plots2#6880]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!
You can find the filehere:
"https://github.com/publiclab/plots2/blob/master/app/views/users/likes.html.erb"
Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:
You only have to edit the function t and not the whole line.
change function t to translation in lines 6,11,15 and 23 respectively.After changing the lines should look like below: "
<pre>
 <%= translation('users.likes.wiki_liked_by') %> <%= user.name %>"><%= user.name %></a>
</pre>
<pre>
 <i class="fa fa-book"></i> <%= wiki.title %></a> <small style="color:#888;">(<%= translation('users.likes.updated') %><%= distance_of_time_in_words(wiki.updated_at, Time.current, { include_seconds: false, scope: 'datetime.time_ago_in_words' }) %>)</small>
</pre>
<pre> 
<%= translation('users.likes.more') %></a>
</pre>
<pre> 
<i class="fa fa-star-o"></i> <%= translation('users.likes.liked_by') %> <%= user.name %>"><%= user.name %></a>

</pre>

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by nstjean** [comment]
Hi @govindgoel ! Thanks for helping!! Can you include a link to the file in the post? Are the line numbers 6, 11, 15 and 23 correct? Right now that code looks like it's all one piece to copy and paste, it could be confusing.

**Comment by govindgoel** [comment]
Yeah thanks for suggestion I have updated  the info..
Happy Coding!

**Comment by nstjean** [comment]
Thanks! Looks great! :)

**Comment by kushaggarwal** [comment]
Can I work on this issue

**Comment by govindgoel** [comment]
assigned @kushaggarwal

**Comment by kushaggarwal** [comment]
In which branch should I post the pull request 
Can you help please

**Comment by nstjean** [comment]
@kushaggarwal Sorry for the wait! To post a pull request you will go into your forked branch that has the changes and post the pull request from there against the publiclab/master branch.
Here's some info from GitHub on how to do that: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by kushaggarwal** [comment]
Okay Thank you very much for your help @nstjean 
Will post the pull request for the same

**Comment by nstjean** [comment]
@kushaggarwal Let me know if you get stuck!

**Comment by kushaggarwal** [comment]
Hello I have made the pull request for the above issue 
So, can you please review the changes for the same
