### ISSUE TITLE
Can't create new wiki page by typing in direct URL

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#689]
### What happened just before the problem occurred

attempted to create new wiki page by typing in a direct URL. 
I was able to create a new page by going to https://publiclab.org/wiki/new

### Relevant URLs

https://publiclab.org/wiki/community-development-projects 

### PublicLab.org username

liz

### Browser, version, and operating system

Chrome, OSX 10.11.3

**Comment by jywarren** [comment]
We also don't have a test for this. https://publiclab.org/wiki/community-development-projects now exists, but https://publiclab.org/wiki/community-development-projects2 does not (for testing) -- any non-existing page should display a form for a new page of that name. 

Liz, didn't it used to put the title in the title field? We could do this better than we had, too -- like a "deparameterize" -- `/wiki/this-new-page` would have a placeholder title of `This new page` -- with `.gsub('-', ' ').capitalize`

**Comment by ananyo2012** [comment]
@jywarren Ok trying to fix this one too

**Comment by ebarry** [comment]
yes @jywarren, this method did used to  take what had been typed into the URL bar and use it as the page title. It would be cool to bring that feature back better than ever.

**Comment by ananyo2012** [comment]
@jywarren I think this is solved now. I typed in a wiki page in the url https://publiclab.org/wiki/a new wiki page and it is taking me to the new wiki editor. Obviously it only happens when I am logged in. @ebarry Can you confirm this is solved?

**Comment by jywarren** [comment]
Great, agreed, it works: https://publiclab.org/wiki/foofoo

Sorry, i haven't checked -- is there a test for this now?

**Comment by ananyo2012** [comment]
Uh just checking it.

**Comment by ananyo2012** [comment]
Test included in #695
