### ISSUE TITLE
Add a location modal on notes takes a long time to appear - 6+ seconds

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6897]
I'm wondering what may be slowing this down; let's investigate a bit with the web console!

![image](https://user-images.githubusercontent.com/24359/70066421-b00d8d80-15ba-11ea-860e-70935f7e8cc5.png)

![image](https://user-images.githubusercontent.com/24359/70066441-bbf94f80-15ba-11ea-9959-d3c30b199261.png)

You can try it out here:

https://publiclab.org/wiki/sandbox-3

**Comment by jywarren** [comment]
First, noting that the modal is loaded from a remote source, which is taking a while to load. 10s:

`Request URL: https://publiclab.org/locations/modal`

Checking Skylight...

**Comment by jywarren** [comment]
Not awesome:

![image](https://user-images.githubusercontent.com/24359/70172378-862d9700-169e-11ea-949d-24da60f5a2f0.png)

https://oss.skylight.io/app/applications/GZDPChmcfm1Q/1575464280/6h/endpoints/TagController%23location_modal?responseType=html

**Comment by jywarren** [comment]
Something in this history? https://github.com/publiclab/plots2/commits/master/app/views/locations/_form.html.erb

But it's been a while since the last edit, (june 28) and @nstjean's change wasn't published until ~10 hours /after/ this slowness report. So, maybe an optimization needs to be made on something happening in the form template?

**Comment by jywarren** [comment]
Maybe `current_user.get_all_used_locations` or `current_user.get_latest_used_location`?

https://github.com/publiclab/plots2/blob/e6006ce12f3eb53259d148879c06397c962e08f8/app/models/user.rb#L455

**Comment by nstjean** [comment]
Wow that's slow. I can't even get the modal to come up on that sandbox page you linked to.

**Comment by nstjean** [comment]
Other wiki pages and notes I check the modal pops up quite quickly. But not at all on that page.

**Comment by jywarren** [comment]
Yeah i know! OK, i see how this code in `user.rb` is really in need of optimization. I'm going to try to compose a much faster query.
