### ISSUE TITLE
mutated map coordinate info and map details

### ISSUE THREAD

**Issue by gonzoearth** [publiclab/plots2#69]
while searching through NYC maps to apply tags I found this map was not where it belongs by about 30mi to the SW. I'm seeing ghosts because it was found in an area we've never mapped and I would not have left it broken when I published it originally. The map details about Riverkeeper was empty as well.
http://publiclab.org/map/newtown-creek-north-brooklyn-ny/2011-08-06
When the archive leaflet database was fixed last month I found and fixed 4-5 maps that also wandered away from where they belong. This is the first one I have found since

**Comment by gauravano** [comment]
Hi @jywarren @gonzoearth do you think we can close this issue if there's no another such problem reported after this or if we have improved our system? 
Thanks!
