### ISSUE TITLE
Lost wiki page for foldable-spec

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#690]
### What happened just before the problem occurred

Attempted to follow link to https://publiclab.org/wiki/foldable-spec from where it was linked on /spectrometry

### Relevant URLs

https://publiclab.org/wiki/foldable-spec
https://publiclab.org/wiki/spectrometry

### PublicLab.org username

liz

**Comment by jywarren** [comment]
That's odd, it's represented in the list I re-imported: `[5215,"Foldable
Mini-Spectrometer","/wiki/foldable-spec"]` -- will check the logs. Liz,
when you submit things, can you say exactly what you see, like "not found"
or "error" -- it helps us solve things a bit quicker. Thanks!

**Comment by ananyo2012** [comment]
I think this will also get fixed with #687

**Comment by jywarren** [comment]
Fixed!
