### ISSUE TITLE
Stalebot preventing Jenkins build?

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6905]
Whoa, unexpectedly, Stalebot seems to have prevented Jenkins from building the stable test server:

```

stderr: error: cannot lock ref 'refs/remotes/origin/feature/install-stalebot': 'refs/remotes/origin/feature' exists; cannot create 'refs/remotes/origin/feature/install-stalebot'
From https://github.com/publiclab/plots2
 ! [new branch]        feature/install-stalebot -> origin/feature/install-stalebot  (unable to update local ref)
error: cannot lock ref 'refs/remotes/origin/feature/stalebot-install': 'refs/remotes/origin/feature' exists; cannot create 'refs/remotes/origin/feature/stalebot-install'
 ! [new branch]        feature/stalebot-install -> origin/feature/stalebot-install  (unable to update local ref)
   ee8200e1..c539db78  stable     -> origin/stable

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2372)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1985)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:80)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:563)
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:897)
	... 11 more
ERROR: Error fetching remote repo 'origin'
Finished: FAILURE
```

https://jenkins.laboratoriopublico.org/job/Plots-Stable/lastFailedBuild/console

Even stranger, I haven't yet installed it!? 

https://github.com/publiclab/plots2/pull/6900 has the config file

Let me see if somehow it is installed, even though I didn't press the install button...

**Comment by jywarren** [comment]
@gauravano i'm going to try deleting the branch you created, but saving the stalebot integration itself... let's see...

**Comment by jywarren** [comment]
Restarting jenkins build after deleting!

**Comment by jywarren** [comment]
Uhhh, hm. OK, so i guess Jenkins does `git fetch` and gets all the `publiclab/plots2` branches, and now we need to actually go into the Jenkins-managed filesystem and delete the `feature/install-stalebot` branch -- I'll ping @icarito about this!

**Comment by jywarren** [comment]
`stderr: error: cannot lock ref 'refs/remotes/origin/feature/stalebot-install': 'refs/remotes/origin/feature' exists; cannot create 'refs/remotes/origin/feature/stalebot-install'`

**Comment by jywarren** [comment]
`git remote prune origin` on the jenkins machine's repo didn't work...

**Comment by icarito** [comment]
I followed this thread and found that the only way I got it to work was to remove the `origin` remote and to add it back again. Now it's building!

https://stackoverflow.com/questions/6656619/git-and-nasty-error-cannot-lock-existing-info-refs-fatal#38272660
