### ISSUE TITLE
Clean up commented code from fixes in #687 and #685, other followups

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#691]
* [x] scan through [changed files in 687](https://github.com/publiclab/plots2/pull/687/files) for commented code, and remove
* [x] same for [685](https://github.com/publiclab/plots2/pull/685/files)
* [x] remove "save all nodes" migration just in case
* [x] write tests to prevent this in future (list these here if not already done)

**Comment by ananyo2012** [comment]
Actually I wanted to keep the code commented in case we wanted to revisit it in future.

**Comment by jywarren** [comment]
That's fine, but we should leave informative comments next to it, so people know what it is and where to find discussion on github. Thanks!

**Comment by ananyo2012** [comment]
Ok sure we can do that. You can assign this one to me.

**Comment by jywarren** [comment]
Great. Maybe we can consolidate all `friendly_id` possible followup and a summary of the current state in one issue, including the maps slugs change [referenced here](https://github.com/publiclab/plots2/issues/686#issuecomment-240781745).

**Comment by ananyo2012** [comment]
@jywarren I think tests included in #685, #687, #693 should suffice. What do you think?

**Comment by jywarren** [comment]
It's the end of the day here so I think I'll go through these carefully
tomorrow along with the other PRs, but I'm sure you've been thorough.
Thanks!

**Comment by jywarren** [comment]
I'm going to close this, thanks!
