### ISSUE TITLE
Map markers for nodes only appear after map interaction, not on initial load 

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6910]
Pages like https://publiclab.org/wiki/sandbox-3 show off the great new features of inline maps, but I noticed that the map markers for content (pages on PL) don't appear on initial load; only after interacting with the map a bit:

Initial load (no black map markers):

![image](https://user-images.githubusercontent.com/24359/70154003-c7fa1580-167d-11ea-9bbb-2ce0ff93b30b.png)

After dragging map:

![image](https://user-images.githubusercontent.com/24359/70153969-b9136300-167d-11ea-8700-55c675018f85.png)

I want to guess that the trigger for loading the remote API call for that layer is not triggered on initial page load, only on map move. Or if it is, it's getting missed perhaps due to load order? 

@sagarpreet-chadha would you mind taking a look here to see if we can adjust this? Thank you!

**Comment by sagarpreet-chadha** [comment]
Yes i think i figured why this is happening! I will work on this issue on
weekend. Thanks.

**Comment by jywarren** [comment]
awesome, thank you Sagarpreet!!!!

**Comment by jywarren** [comment]
@sagarpreet-chadha @nstjean if you happen to put an eye on this that would be great! I bet it's a one-liner to trigger the markers and we just forgot to do an initial page-load trigger.

**Comment by nstjean** [comment]
Sure! I bet that's exactly what the issue is. @sagarpreet-chadha you said you had figured it out?

**Comment by jywarren** [comment]
Just noting here - possible additional issue which we believe is solved, but linking:

- markers don't appear at all now; could be linked to the fix -- https://github.com/publiclab/plots2/pull/7299 - this is the LEL bump that was causing testing errors, we talked about default loading
- https://publiclab.org/notes/warren/11-16-2019/mashapaug-pond - example of this in sidebar map

**Comment by jywarren** [comment]
I think i found the event handlers:

https://github.com/publiclab/plots2/blob/23e83cdc51a8496f23db932054cbe25ee329e821/app/assets/javascripts/leaflet_helper.js#L109-L140

**Comment by nstjean** [comment]
I can fix this, I had to do something similar on `/map/`. I'll make a PR
