### ISSUE TITLE
Replace text with icons in wiki headers

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6911]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### What is to be  done.
Our wiki pages have nice new minimal headers like this:

https://publiclab.org/wiki/coqui

![image](https://user-images.githubusercontent.com/24359/70157070-e4e51780-1682-11ea-86a6-f92248ae9930.png)

However, I think we could go even more minimal by using icons instead of text. We can add text "tooltips" if we want, but let's start by replacing the text with nice icons, in a grey color. 

The code is here:

https://github.com/publiclab/plots2/blob/662281d25316e474aa22188679c8d3a0f1f3189e/app/views/wiki/_header.html.erb#L34-L36

See how you can hover over Revisions and see a helpful tooltip:

![image](https://user-images.githubusercontent.com/24359/70157608-dc411100-1683-11ea-8b3d-879f093f87d3.png)

We could replace "Authors" with: `<i style="color:#888;" class="fa fa-user"></i> 6` (notice icon before number) and add a tooltip saying "6 authors"

We could replace "Revisions" with `<i style="color:#888;" class="fa fa-history"></i> 57` and leave the helpful tooltip.

And we could replace "Talk" with just ``<i style="color:#888;" class="fa fa-comment-o"></i>`.

That would result in this:

![image](https://user-images.githubusercontent.com/24359/70157666-f2e76800-1683-11ea-8b89-298a24ed8620.png)

You can see how the tooltips are set up in the 2nd and 3rd item with these attributes: ` rel="tooltip" title="View all revisions for this page." data-placement="top"` -- the same could be repeated for the "Authors" item!

This would be really great, and we'd love help with it! 

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by heikergil** [comment]
hi, unless someone else is already working on this problem  i would like to claim it

**Comment by jywarren** [comment]
that'd be great, thank you!
