### ISSUE TITLE
Add popover to list authors on wiki page headings

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6923]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### What is to be done.
[Wiki pages](https://publiclab.org/wiki/onecranston) now have this great header showing Authors, Revisions, and the talk page:

![image](https://user-images.githubusercontent.com/24359/70264384-4c27c800-1766-11ea-80aa-168dab23f0c0.png)

Let's make it so you can click the Authors item and see a [Bootstrap popover](https://getbootstrap.com/docs/4.3/components/popovers/) listing the authors' usernames.

The code for that is here:

https://github.com/publiclab/plots2/blob/6d417a384801e4c20b77c4d6360788f19a78b41c/app/views/wiki/_header.html.erb#L34-L36

We can get the authors listing using `node.authors`, as shown here:

https://github.com/publiclab/plots2/blob/6d417a384801e4c20b77c4d6360788f19a78b41c/app/models/node.rb#L278-L280

And for each one, we could do the following so that their names are clickable and lead to their profile pages!

```html
<ul>
  <% node.authors.each do |author| %>
  <li><a href="/profile/<%= author.username %>">@<%= author.username %></a></li>
  <% end %>
</ul>
```
That code can go inside the popover!

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by takitsuse** [comment]
If no one is working on this I'd like to claim this.

**Comment by takitsuse** [comment]
Hmm...Could I ask for help? It seems I got stuck.
How can I set the HTML tags for the content of popover?
I edited line 34 to be:
```erb
<span rel="tooltip" data-placement="left"><%= number_with_delimiter(@node.authors.length)  %> Authors</span> |
```
and I was about to set the popover content
```erb
<ul>
          <% @node.authors.each do |author| %>
            <li><a href="/profile/<%= author.username %>">@<%= author.username %></a></li>
          <% end %>
</ul>
``` 
to data-content but I have no idea how to do so.

**Comment by takitsuse** [comment]
I managed to get out of the stuck myself.

**Comment by takitsuse** [comment]
Here's progress: [Screencast](https://imgur.com/a/jtcJito).
As you see in the screencast, the popover vanishes when we move the cursor to the author's link. This is not what we intended but I have no idea how to fix this behavior. Could you help me out?

**Comment by cesswairimu** [comment]
Hey @takitsuse, wow..this is so great :tada: ...could you please open a pull request on plots2?( Here is a link to open a pull request against your branch go https://github.com/publiclab/plots2/compare/master...takitsuse:add-popover-to-list-authors and click on "create a pull request" _just incase its your first time_). Also cold you try adding 2 or three authors just to see how that will look like.Thanks so much for working on this

**Comment by takitsuse** [comment]
Created PR. Thanks for your guidance!

**Comment by pianeta051** [comment]
Is anyone working on this?...Can I take it?

**Comment by SidharthBansal** [comment]
Yes, someone else is working on it. Please try any other issue.

**Comment by Johongirr** [comment]
how can i be notified if some new issue is opened

**Comment by jywarren** [comment]
Hi all - apologies for slow reply here. This is available for anyone to claim!

**Comment by chanukya-y** [comment]
hi @jywarren , i would like to claim this issue

**Comment by gauravano** [comment]
Go ahead @chanukya-y :)

**Comment by jywarren** [comment]
Hi @chanukya-y - just noting that there is a good start in https://github.com/publiclab/plots2/pull/6934 that you could build on!

**Comment by madhhuurrii** [comment]
Hii @jywarren , can I work on this issue as a first timer?

**Comment by Priyaraj17** [comment]
Is this issue open right now? May I work on it?

**Comment by cesswairimu** [comment]
Hi @madhhuurrii are by chance working on this or still interested, sorry I missed your comment..If not, please let @Priyaraj17 know Thanks you both

**Comment by madhhuurrii** [comment]
No @cesswairimu,I am not working on this issue

**Comment by cesswairimu** [comment]
thanks, @Priyaraj17  you can take this one. thanks

**Comment by Priyaraj17** [comment]
Sure I will start with it.

**Comment by Priyaraj17** [comment]
@cesswairimu  Can you please review the PR https://github.com/publiclab/plots2/pull/9372
