### ISSUE TITLE
Filter out powertag topics from profile page listings

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6924]
Our profile pages https://publiclab.org/profile/warren, https://publiclab.org/profile/stevie, etc - look great! They list topics recently posted to by each author. But, we see a lot of "powertags" -- those that have colons `:` in them and are for utility use only. They don't represent real "topics"!

So, let's filter them out of this view. It should be relatively easy, since we use `@profile_user.tags` on this line to generate the list:

https://github.com/publiclab/plots2/blob/6d417a384801e4c20b77c4d6360788f19a78b41c/app/views/tag/_profileCard.html.erb#L2-L6

Let's instead make a new method in `/app/models/user.rb` for `def normal_tags`, modeled on the one in `/app/models/node.rb`:

https://github.com/publiclab/plots2/blob/6d417a384801e4c20b77c4d6360788f19a78b41c/app/models/node.rb#L435-L448

We'd love help with this! 

It'd be extra great if you wanted to write a unit test for `user.normal_tags` - it could be a simple one based on this:

https://github.com/publiclab/plots2/blob/6d417a384801e4c20b77c4d6360788f19a78b41c/test/unit/user_test.rb#L26-L27

(that one also has some redundant repeats that could be removed!)

Anyhow, I'm happy to support if anyone's interested in taking this on!

**Comment by smarty1palak** [comment]
Hi, I am a first timer but would like to try this out. Can i be assigned this one?

**Comment by jywarren** [comment]
Yes please go ahead! Thanks!

**Comment by YuetChan** [comment]
Is anyone working on this issue? If not, can I give it a try?

**Comment by pianeta051** [comment]
I would like to help on this....Let me know if any help is needed

**Comment by jywarren** [comment]
@YuetChan - if you'd like to help out, please open up a PR even with your initial work, so we can see! @pianeta051 it looks like this has been claimed but if @YuetChan does not follow up for a few days, i'm sure we could use the help! Thanks all!
