### ISSUE TITLE
Fix mailto link text

### ISSUE THREAD

**Issue by Uzay-G** [publiclab/plots2#6939]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.
### The Problem
As you can see in the image below, the comment link on the publiclab.org website opens up an email with a body text full of pluses instead of spaces.

![fto-1](https://user-images.githubusercontent.com/52892257/70388084-9ea6f580-19ad-11ea-9206-108322738c7d.PNG)

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [notes/_comment file](https://github.com/publiclab/plots2/blob/master/app/views/notes/_comment.html.erb) in the repository (press the little pen Icon) and edit the line as shown below. 
- Replace this on line 65:
```href="mailto:moderators@publiclab.org?subject=Reporting+spam+on+Public+Lab&body=Hi,+I+found+this+comment+that+looks+like+spam+or+needs+to+be+moderated:+https://publiclab.org/<%= comment.parent.path %>#c<%= comment.cid %>+by+https://publiclab.org/profile/<% if comment.author %><%= comment.author.name %><% end %>+Thanks!">```
with this:
```href="mailto:moderators@publiclab.org?subject=Reporting%20spam%20on%20Public%20Lab&body=Hi,%20I%20found%20this%20comment%20that%20looks%20like%20spam%20or%20needs%20to%20be%20moderated:%20https://publiclab.org/<%= comment.parent.path %>#c<%= comment.cid %>%20by%20https://publiclab.org/profile/<% if comment.author %><%= comment.author.name %><% end %>%20Thanks!">```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### How this works
If we replace the pluses directly with spaces that would have failed because a url can't have any empty spaces. What we did is replace these pluses with an [**escaped character**](https://www.werockyourweb.com/url-escape-characters/). The escaped character for a space is  ```%20```.

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!
### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by myungwoo-Y** [comment]
Hi, can I work on this issue?

**Comment by Uzay-G** [comment]
Sorry @myungwoo-Y but this one is only for those who haven't contributed to our repos before. You can find issues to work on [here](https://github.com/publiclab/plots2/labels/help-wanted). Thank you for wanting to help but we are going to leave this one for someone else.

**Comment by shashwataggarwal** [comment]
Hi, can I work on this?

**Comment by Uzay-G** [comment]
Hey @shashwataggarwal! Welcome to PublicLab! Yeah you can claim the issue and then I'll review your pull request. If you encounter any problems you can message me here.

**Comment by shashwataggarwal** [comment]
Kindly review my pull request
Thank you!
