### ISSUE TITLE
Fix typo in config.yml

### ISSUE THREAD

**Issue by CodeSarthak** [publiclab/plots2#6945]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [config.yml](https://github.com/publiclab/plots2/blob/master/.github/config.yml) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
Line 40:
-It is recommend to include as many gifs and emojis as possible
+It is recommended to include as many gifs and emojis as possible
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by johnaceto** [comment]
Hello. Can I claim this issue?

**Comment by CodeSarthak** [comment]
@johnaceto Yes, go ahead.

**Comment by johnaceto** [comment]
Please review my pull request. Thank you.

**Comment by CodeSarthak** [comment]
Great job @johnaceto 
Go to : https://github.com/publiclab/plots2/issues to find more issues you can work on. 

Welcome to Public Labs :)

**Comment by cesswairimu** [comment]
Hi @CodeSarthak, was this fixed on another PR? I saw there is a pull request from @johnaceto. Kindly let me know why you closed it. Thanks

**Comment by CodeSarthak** [comment]
Yes, #6947 is ready to be merged according to me.

**Comment by cesswairimu** [comment]
@CodeSarthak ooh cool... I am sorry, I did not communicate this before...we do not manually close the issue until after the pull request is merged...it closes automatically when a pull request with the referenced number is merged...No worries though I will reopen this. Thanks a lot for opening this :heart:
