### ISSUE TITLE
Modify card design as displayed on Methods page to match style guide

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6960]
We now have nice new "card" designs for pages around the site, from the [style guide draft](https://publiclab.org/notes/warren/05-07-2019/introducing-a-draft-style-guide-for-public-lab). They look like this:

![image](https://user-images.githubusercontent.com/24359/70752223-23707700-1d00-11ea-9e88-327e568a57a8.png)

But this page isn't quite looking right:

https://publiclab.org/methods

![image](https://user-images.githubusercontent.com/24359/70752229-28352b00-1d00-11ea-9cce-00ea19cd5c49.png)

It used to show these bits of information on the card itself:

![image](https://user-images.githubusercontent.com/24359/70752507-c4f7c880-1d00-11ea-896c-b31af1480579.png)

See how they're in the popover when you click the `...` menu:

![image](https://user-images.githubusercontent.com/24359/70752537-d214b780-1d00-11ea-9ee5-b95da332adfa.png)

So since the data is still there, let's just be sure that it appears in the card's bottom-left corner, kind of like the comment icon and text in the bottom left of the very first screenshot cards!

Here's the section of code where these 2 bits of info (Activities and Questions) are shown in the popup; this should just be moved to a different area of the tag card template (in the same file):

https://github.com/publiclab/plots2/blob/7a6d9316193e1cb5b9318aa49dca665d52c54f27/app/views/notes/_card.html.erb#L50-L55

We'd love help with this!

**Comment by sharmamansi** [comment]
Hey, @jywarren  can i work on this?

**Comment by jywarren** [comment]
That would be great, thank you!!

**Comment by sharmamansi** [comment]
hey @jywarren can you please help me when im running the project on my machine im not able to see these cards.

**Comment by jywarren** [comment]
Hi, I believe you need to create a wiki page at /wiki, and then give it a
tag "method" for it to appear on this listing. Make sense?

**Comment by sharmamansi** [comment]
@jywarren  kindly review this.
