### ISSUE TITLE
Include Emails of Banned Users in Moderator Email Search

### ISSUE THREAD

**Issue by skilfullycurled** [publiclab/plots2#6962]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Moderators have access to a feature that allows them to lookup profiles by email.  During a recent attempt to unban a mistakenly banned user (#6883) it was discovered that this feature does not include the emails of banned users.

In discussion with the moderation team, there are some good use cases for including these emails:

1) if a user created their account a long time ago, they may not remember there username (or remember it correctly).  In those instances, finding a profile by email would be the only recourse.  

2) Including banned users may eliminate a round of back and forth if the person emailing the moderation team is using the email address they signed up with.

The current solution (related #7109)is to create a check box that when toggled will add banned from 2015 onward to the search.  We also need to add some text explaining what the check box does and the impact that using it may have on the site.

**NOTE:** _See the **update** section below for a link to the post in this conversation where the steps are located to complete the FTO._

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** 
The steps needed to complete the FTO can be found in the conversation below at [this post](https://github.com/publiclab/plots2/issues/6962#issuecomment-570727398).

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by skilfullycurled** [comment]
Regarding the number of spam users slowing things down:  

We have at least over 350,000 actual users (see [here](https://github.com/publiclab/plots2/issues/5524#issuecomment-484611290)) but that's from 2013 and things seem pretty good.  Did we not require email back then?

I trust you could do an actual query but as a rough estimate: I've been collecting moderation emails since 5/1/19 and we've only marked ~1800 users as spam (and banned them as a consequence).  So, extrapolating from that (admittedly a flawed idea) let's say conservatively, we have ~4000 spam users a year.

Perhaps we could limit the inclusion dates to some number of years that would keep everything speedy.  Or is there a slow down due to the fact that now you have to add in another query parameter?  

I don't think the feature needs to capture all edge cases, just enough that it's worthwhile to have it.  I haven't been on the moderation list for long enough to know how long that should be.  Do other moderators have any thoughts on that?

**Comment by jywarren** [comment]
Just thinking about how to warn people about this, the checkbox could have a helpful warning like `[ ] include banned accounts (careful: the huge # of accounts can make this slow the whole site down)`

We could have the checkbox add a POST parameter like `banned=true` and then on line 59 of this code segment, switch off that conditional accordingly:

https://github.com/publiclab/plots2/blob/0f94ede6e5cb3eaf244491e14f090b704bfec297/app/controllers/admin_controller.rb#L63-L75

**Comment by jywarren** [comment]
If this sounds reasonable, @skilfullycurled, we can mark it as an FTO candidate and hand it off to folks for implementation? ❤️ Happy new year!

**Comment by skilfullycurled** [comment]
Happy New Year!

For sure, did you need me to change anything on this issue or do you have the power to edit it?

A few suggestions:

1) Would it help to put a time constraint on the search or would that slow the process down even more?  There was a period of time when we got 350,000+ signups in 2013 and the probability that the needle is in that haystack is very close to zero.

2) I'd give the warning a use case or condition to satisfy before doing it, and a reminder to be patient.  This is an edge case since current moderators already know the use case, but it's a small addition that will have two positive effects: 1) it shouldn't be their first option but 2) it's an acceptable option and they shouldn't shy away from using it in particular instances.  When using a "search all" function, I think it's common for people to try it and then realize that the time it's taking isn't worth it so they cancel the request.

As a verbose example:  

_[ ] include banned accounts (careful: Please use only in cases where the user is already banned or you are unable to find the user through the normal search first.  The huge # of accounts can make this slow the whole site down.  Please be patient as it loads.)_

3) I had another idea since I last filed this which would also make a good FTO.  We could also add something using the body parameter in the mailto such as:

"Please make sure to include your username and the email address you used to sign up for the site."

```
<a href="mailto:moderators@publiclab.com?body=Please make sure to include your username and the email address you used to sign up for the site">moderators@publiclab.com</a>
```

The overall goal as I see it is to reduce the back and forth between the moderator and the user while also making the need to search all of the users a very rare instance.  So I think anything we can that's simple and prevents needing to use the search feature in the first place is a worthwhile addition.

**Comment by jywarren** [comment]
if you think the time constraint of >2013 is OK, then we could just add
that to the checkbox and state it, and include less cautionary text. And
assume no searching banned users <2013.

I like the moderators mailto idea; could you break that into its own issue?
It's pretty easy to implement and would make a great FTO. Thanks!

**Comment by skilfullycurled** [comment]
If you think it will make a difference, we can shave off (possibly as much as) another ~36,000, then you can start at 2015.  That's not from actual data, I'm extrapolating but I think it's a reasonable one.  I mean hey, you're a decade old now (and it's a new decade) so you're allowed to do things by 5's now!  I leave that to you, I have no opinion, just offering some info albeit not based entirely on fact.  So I guess that makes it an opinion.  Anyway, you get it.

Will do on the FTO.

**Comment by skilfullycurled** [comment]
Wait!  I didn't mean to close it...clicked on the wrong button.  Unless that's okay that I closed it.  Seems like we've come to an end for the time being

**Comment by jywarren** [comment]
No, let's go ahead on this - I think then the changes would be to change lines 68-9 of this:

https://github.com/publiclab/plots2/blob/0f94ede6e5cb3eaf244491e14f090b704bfec297/app/controllers/admin_controller.rb#L63-L75

to something like:

```ruby
       if params[:include_banned]
         @users = User.where(email: params[:address]) 
           .where('created_at > (?)', DateTime.new(2015)) # since 2015, whether banned or not
       else
         @users = User.where(email: params[:address]) 
           .where(status: [1, 4]) 
       end
```

And a template change to add a checkbox to this:

https://github.com/publiclab/plots2/blob/d251b5ff71036060d2439128496550c022bac80c/app/views/admin/useremail.html.erb#L7-L13

like:

```html
<label>
  <input type="checkbox" id="myCheck" name="include_banned" />
  Include banned accounts after 2015 (careful: can result in server slowness for all users)
</label>
```

I think this is ready to be made into an FTO! 

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by skilfullycurled** [comment]
Ah, you know, I remember now that there's a template for FTO's.  Do we typically convert the original issue by changing the original text and filling it in with the new information we have from the discussion or do we need a new one?

**Comment by jywarren** [comment]
I think you got it right in the one you just posted, thanks!

**Comment by skilfullycurled** [comment]
I'm still not clear: I meant in regards to this one, when you said it's ready to be an FTO, should I make a new one or just fix the formatting on this issue so it matches the FTO template.  The other one that I wrote was a different FTO for the mailto text.

**Comment by skilfullycurled** [comment]
I'm just going to go ahead and do it and we can "fix it in post" as they say.

**Comment by jywarren** [comment]
Sorry - yeah, i don't have a strong opinion on reformatting vs making a new one. If you want to keep people in the notifications thread you can use the same issue. But not a big deal either way! Thank you!!

**Comment by skilfullycurled** [comment]
@jywarren, I reformatted the original post.  Since you already had the steps in the conversation, I simply linked to that post in the "update" section on the checklist.  I think it's officially ready for a label upgrade!

@shipcy, if you're interested in taking it on, go head and claim it!  Please leave a note either way.

Thanks everyone!

**Comment by skilfullycurled** [comment]
@shipcy, can you say a bit more about your experience so I know where to begin to help you?  

What have been your experiences with Github?  Have you worked with Github with your own work?  Have you contributed to another repository before?

**Comment by shipcy** [comment]
@skilfullycurled I'm totally new to open source. I've not that much idea about the contributions. But I'll try my best to apply my skills here and will try to solve issues. And I haven't contributed to any repository yet. Please guide me.

**Comment by skilfullycurled** [comment]
That's actually perfect @shipcy because I've been wanting to update the and see if people can follow it anyway.

BTW: Also, introduce yourself [here](https://github.com/publiclab/plots2/issues/6962#issuecomment-571205632).  This is our weekly community check-in.  Each week there is a new question that is asked.  Often it is centered around what people are working on, but sometimes I just use it to say "hello".  Let everyone know you're working on your first contribution.  You'll get an enthusiastic greeting, and people will generally let you know if they're available for any questions!

Okay, let me take some screenshots, and update the tutorial.  Be right back!

**Comment by skilfullycurled** [comment]
@shipcy, I was looking at your profile, and it seems like you do know how to fork the repository.  If so, then you can go ahead and fork plots2.  If not, then just wait and I'll have an image up in a few minutes.

**Comment by shipcy** [comment]
Hey, everyone! My name is Shipra Choudhary. I'm currently a junior pursuing Computer Science and Engineering from India. My skill set includes HTML, CSS, Bootstrap, Javascript, JQuery, C++, MySQL, etc. And I'm new to open source and I'm working on my first contribution.

**Comment by skilfullycurled** [comment]
@shipcy, I'm so sorry.  I gave you the wrong link.

(sigh)

Follow [this link](https://github.com/publiclab/leaflet-blurred-location/issues/227) and introduce yourself here.

**Comment by shipcy** [comment]
@skilfullycurled I've introduced myself there.

**Comment by shipcy** [comment]
@skilfullycurled I have given my introduction.

**Comment by skilfullycurled** [comment]
Great!  Okay, give me a bit, I need to check on some things with folks.  In the meantime, you can fork the repository.

**Comment by shipcy** [comment]
@skilfullycurled it's done!

**Comment by skilfullycurled** [comment]
Great!  Okay, sadly, I am waiting to hear back on some stuff, and I also need to go for a bit.  You can certainly try using it though, it's located [here](https://publiclab.org/notes/liz/11-02-2016/make-the-most-basic-github-contribution).  I think there is a step missing right before step 7.  What I think you want to do is _**go back**_  to your repository, and find the file and location.  Then you can follow step 7 and the rest.  Normally, the file location and changes to be made are at the top of an FTO.  In this particular case, they are in the conversation, and you can find them by clicking [here](https://github.com/publiclab/plots2/issues/6962#issuecomment-570727398).

You'll see there's a block of code and at the top it says:
```
plots2/app/controllers/admin_controller.rb
Lines 63 to 75 in 0f94ede
```
You need to find that file in your repository and find lines 63-75.  Then follow the steps from 7 on wards.  If you can't or would prefer to wait, that's perfectly fine!  Note: since this is happening on a branch in your repository, you can experiment with the editing as much as you want.

**Comment by shipcy** [comment]
@skilfullycurled I have done it.

**Comment by skilfullycurled** [comment]
You did great!  You went really far without very good directions or instructions.  Well done.

A few things:

1) Don't forget the second part which is changing the template to add the check box (see above).  However, we should get more specific on where that code goes first.  @jywarren, when you have a moment, can you let us know what line the html goes in the template in your [comment above](https://github.com/publiclab/plots2/issues/6962#issuecomment-570727398)?

2. I didn't realize that we hadn't given you any lines for where the new code goes.  The end result should look like the following below, so you can now replace the entire def useremail function instead of figuring out where it gets inserted. 
```
  def useremail
    if logged_in_as(['admin', 'moderator'])
      if params[:address]
        # address was submitted. find the username(s) and return.
        @address = params[:address]
        if params[:include_banned]
          @users = User.where(email: params[:address]) 
          .where('created_at > (?)', DateTime.new(2015)) # since 2015, whether banned or not
        else
          @users = User.where(email: params[:address]) 
          .where(status: [1, 4]) 
        end
      else
        # unauthorized. instead of return ugly 403, just send somewhere else
        redirect_to '/dashboard'
      end
    end
  end
```
You can make the changes to your current branch and I believe the pull request you created should update automatically with the new commits.  However, I'd cancel the pull request and start over because I have two other suggestions.  It's your choice, truly.

3. You've named your branch `shipcy-patch-1`.  I believe "patches" are for fixes, not new features, so give your branch a name that describes the feature such as `scipcy-banned-users`.

4) Make sure to name your commits with more description as well.  Instead of "updated admin_controller.rb", "modified useremail function to include banned users".  Then, when you modify the useremail.html.erb your commit could be "added checkbox to include banned users".  You want to get specific enough that someone else could easily find your commit from the giant list of commits if they had to.

**Comment by skilfullycurled** [comment]
PS: This is really helpful by the way. These errors are really on us and our directions so it's great to be able to see where our directions are failing!

**Comment by jywarren** [comment]
Hi! just noting if it'd be helpful just be sure to ping me @jywarren with any questions. You're doing great!

**Comment by skilfullycurled** [comment]
@jywarren, you might have missed my question in the giant text, but when you have a moment, can you let us know what line the html goes in the template in your comment above?

**Comment by jywarren** [comment]
Oh sorry! Yes, i think it'd go just before line 13, but you may want to wrap it in `<p>` `</p>` tags depending on how it ends up looking!

**Comment by shipcy** [comment]
@skilfullycurled I've done the def useremail function changes and made another pull request.

**Comment by shipcy** [comment]
@skilfullycurled I have also completed the second part which is changing the template to add the checkbox and made a pull request.

**Comment by shipcy** [comment]
@skilfullycurled and @jywarren I wanna know the one thing that why are we using % inside HTML tags like <% if @address %> ?

**Comment by skilfullycurled** [comment]
I forgot to answer your question about my mentioning the questions at the top, I’ll have to reread what I wrote.  Will get back to you!

**Comment by skilfullycurled** [comment]
The <% %> tags are know as “template tags”.  I can explain in more detail when I’m at my computer, but in the meantime, you can look up “Ruby erb template tags” to get a feel for why/how they’re used.  

Short story, they allow you to “program” your HTML.  For example, HTML does not have any if/then statements.  So what do you do if you want your HTML to say one thing if a user is logged in, but another thing if they are not?  You could have two different HTML pages, and the server will send the right one out depending.  But that’s double the work for what is essentially the same HTML but with one different line.  Templates make this and other nice things possible (variables, for loops, and more!) that in the end mean less work for you!

The templates are converted to regular HTML when they go out, and the template tags <% %> tell the compiler that this is a part of the document that is not in HTML so please put your programming glasses on, do what it says, and then compile it to HTML.

There are a number of different templating languages, and they’re not unique to a specific programming language.  People can choose different ones to their liking.  For example there’s one called “mustache” (you’ll see why when you take a look) so this is a great opportunity to learn the concept.

Well, that short story was a bit longer than shorter, ; ) but I’ll be back with some links to clear explanations!  

Another good thing to read up on is MVC websites which stand for model, view, controller.  The ruby documentation is actually pretty good.  It might explain both concepts there.  You just need a feel for these two things, you don’t have to understand them perfectly.

**Comment by skilfullycurled** [comment]
@shipcy, I've got to bring someone else into the conversation because for some reason your pull requests aren't showing up in the plots2 pull requests.  Hold tight!

**Comment by shipcy** [comment]
@skilfullycurled why my pull requests aren't showing? Maybe any fault from my side

**Comment by skilfullycurled** [comment]
@shipcy, yes, I noticed.  In my comment above yours I asked for people to help out.  Are you receiving notifications via email when the thread is updated with new comments?  Because we're all leaving comments at different times (sometimes at the same time!), it's easy for one to get out of sync with the conversation.  If you haven't already, be sure to take a look at what's come in since you last posted.

**Comment by skilfullycurled** [comment]
Pinging @publiclab/connectors.  If anyone has some time to dedicate to helping today, I'd appreciate it, I'll out more than usual.  @shipcy is going quite a good job and I want to make sure they still has the support they need (!) and don't have to wait too long for help.

**Comment by nstjean** [comment]
Hi @shipcy ! I took a look at your pull requests and it looks like they were created on your fork instead of the master branch. So all you need to do is go to https://github.com/publiclab/plots2/pulls and create the pull request there. Then it will show up as not just something in your personal fork, but for the public lab repository master branch!

After you click on the `New Pull Request` button you're going to click on the link `compare between forks`. make sure the left side has the `publiclab/plots2/master` and on the right side you will select your fork `shipcy/plots2` and then select the branch your changes are in.

![FireShot Capture 181 - Comparing publiclab_master nstjean_master · publiclab_plots2 - github com](https://user-images.githubusercontent.com/49460529/71913318-2450c900-3145-11ea-9cf9-214b3b2dbe60.png)

**Comment by shipcy** [comment]
@nstjean I can't see the base repository and head repository.
![Screenshot 2020-01-07 at 10 48 32 PM](https://user-images.githubusercontent.com/51285742/71914587-e3d26900-319f-11ea-88ba-a59697315aca.png)

**Comment by nstjean** [comment]
Click on the blue link "compare across forks" and it should show up!

**Comment by shipcy** [comment]
@nstjean thank you so much. I've done this.

**Comment by nstjean** [comment]
Excellent! I see them now!

**Comment by shipcy** [comment]
@skilfullycurled and @nstjean what to do next? Please guide me.

**Comment by nstjean** [comment]
You now just have to wait for your pull request to be reviewed. :) I will check to make sure the page looks ok and either post suggestions for changes or approval!

**Comment by shipcy** [comment]
@skilfullycurled my pull request is having issues. And I don't know what to do next. Please help me out.

**Comment by skilfullycurled** [comment]
Hey @scipcy!  Sorry to have been gone yesterday, I had a project I needed to give some love to.  

Okay!

First things first.

Once you have a pull request submitted, move the conversation over there, that way we can keep all of the issues that are impeding the request on that that page.

@nstjean is taking a look right now, and I'll join in, too!

**Comment by shipcy** [comment]
Thanks @skilfullycurled

**Comment by skilfullycurled** [comment]
Hi, just wanted to notify everyone that I tried out the interface and it was actually very speedy, in the order of seconds.  The user I was looking up only signed on a few weeks ago, and it's almost midnight EST, but still, it was nice to know the site won't implode for the most frequent use case.
