### ISSUE TITLE
Location form on /post/ has inconsistent styling

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#6968]
This is the mockup from my proposal for publiclab.org/post/

![Post_2_with_text_2_BORDERED](https://user-images.githubusercontent.com/49460529/70821419-093ea380-1da9-11ea-8259-b09b16287a1d.png)

It evens up the spacing of the elements. The code needs cleaning up too.

I'll be doing this in a PR very shortly. :)

**Comment by jywarren** [comment]
Like this! Maybe "remove location" ought to be a trash can instead of a ban icon? And, ought it to be next to "current location"? 

Finally i think i suggested already that "by entering coordinates" could be a toggle with those fields already collapsed by default. 

Thanks! Awesome!
