### ISSUE TITLE
Some legacy wiki URLs not preserved

### ISSUE THREAD

**Issue by BeckiC** [publiclab/plots2#697]
### What happened just before the problem occurred

Tried to click the menu bar link for the "How we're funded" page. There is now no content.

### Relevant URLs

https://publiclab.org/wiki/how-public-lab-funded

### PublicLab.org username

(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by ananyo2012** [comment]
@jywarren Jeff could you see this. I think this one is affected too.

**Comment by jywarren** [comment]
Hi, Becki - I'm not sure exactly why this happened, but I see that https://publiclab.org/wiki/how-we-are-funded exists, and my records show that that was the original URL:

`[657,"How Public Lab is Funded","/wiki/how-we-are-funded"]`

I'm trying to figure out if there were some pages with 2 URLs -- such as happened with the `/lists` vs. `/wiki/mailing-lists` pages. It used to be that some pages redirected to a different URL. I think this was pretty rare, but don't know the mechanism.

In the meantime, I'll add the link correction to the menu bar. Thanks for reporting! I'll modify the name of this issue.

**Comment by jywarren** [comment]
Hi, Becki - we've changed the header link, so I'm going to close this; if there are other links elsewhere pointed at the old URL, please ping me and we can pursue a deeper fix. Thanks for reporting!
