### ISSUE TITLE
New post form goes off-screen at small screen sizes

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#6970]
**Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

At https://publiclab.org/post/ at small screen sizes the elements collapse nicely and are supposed to be fill the width of the screen. But something is pushing the map and form off the screen! Let's look at the CSS and fix it.

![FireShot Capture 110 - 🎈 Public Lab_ Post - localhost](https://user-images.githubusercontent.com/49460529/70822884-a18a5780-1dac-11ea-886c-0a06c4dd68b8.png)

**Comment by nstjean** [comment]
@SidharthBansal This can be added to the GCI dashboard!

**Comment by SidharthBansal** [comment]
Published thanks

**Comment by SidharthBansal** [comment]
Can you write reserved for gci students online at top of the issue body?

**Comment by nstjean** [comment]
Oh yes! Done. :)
