### ISSUE TITLE
Change language not working

### ISSUE THREAD

**Issue by Uzay-G** [publiclab/plots2#6971]
I was on the Publiclab.org website and wanted to check something so I tried changing the language in the section at the footer. After I changed it, the window reloaded and I noticed that the language was still english as you can see here:
![lang-bug](https://user-images.githubusercontent.com/52892257/70825801-969fe900-1de5-11ea-9440-c7edc0a692b6.png)

### Please show us where to look

https://publiclab.org/

### Browser, version, and operating system
I was on Firefox with Ubuntu but I think this isn't related to my device.

Thanks :+1:

**Comment by jywarren** [comment]
Hi! Actually the language change will affect only UI elements, and even then only ones we've entered into the translation system. So I think some caveats and explanation, even briefly, will help set expectations here. What do you think?

**Comment by jywarren** [comment]
For example the dashboard has some translated text, but not in every language. 

Each globe icon represents a string of text that is not yet translated:

![Screenshot_20191213-195903](https://user-images.githubusercontent.com/24359/70840827-1c6e6500-1de3-11ea-994b-aa4db4f02c5c.png)

**Comment by pianeta051** [comment]
Hello,
I would like to help with this issue. Is anyone working on this?.
Thanks
