### ISSUE TITLE
Performance issue: Elements constantly updated

### ISSUE THREAD

**Issue by VladimirMikulic** [publiclab/plots2#6989]
As the title suggests, on https://publiclab.org/post span that contains a message and a link is updated constantly. I suspect we have an infinite loop somewhere. Also, my CPU usage rises while I am on pl.o/post. 

Video: https://streamable.com/vvn65
Browser: Chrome 79
OS: Kubuntu 19.10

**Comment by jywarren** [comment]
I think you may be right -- it could just be the polling from this module
feature? https://github.com/publiclab/PublicLab.Editor#title-integration
looking
for related titles... if you turn that off does it still run the CPU?

**Comment by VladimirMikulic** [comment]
That's what I found out too. I've provided detailed explanation and PR: https://github.com/publiclab/PublicLab.Editor/pull/370
