### ISSUE TITLE
Implementing User Streaks in User Profile Page

### ISSUE THREAD

**Issue by ananyo2012** [publiclab/plots2#699]
A lot of discussion has already been made on User Streaks in #319 and #539. The current status of User streaks is that a a fire icon is shown beside comments for an User on a streak. This is how it looks
![user_streaks](https://i.publiclab.org/system/images/photos/000/016/847/original/streak_v1.png)
The detailed definition of User streaks can be found on https://publiclab.org/wiki/streak.

Relevant discussion has been stated clearly in the Public Lab research note https://publiclab.org/notes/ananyo2012/07-02-2016/definition-for-user-streaks. 

We need to come up with a better definition of User streaks following the Public Lab culture and with a good design idea to implement it in the User profile.

**Comment by jywarren** [comment]
Let's close this one out for now, thanks!
