### ISSUE TITLE
comments page on profiles not loading. 

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#6992]
Hello,
When visiting this profile page: https://publiclab.org/profile/Mark34 I clicked the comments link here: 
<img width="1087" alt="Screen Shot 2019-12-09 at 9 10 10 AM" src="https://user-images.githubusercontent.com/7490478/71004866-95561100-20b0-11ea-8b47-84eb6a35a21e.png">

and am taken to a sort of error page that looks like this: 
<img width="1062" alt="Screen Shot 2019-12-09 at 9 09 59 AM" src="https://user-images.githubusercontent.com/7490478/71004910-aacb3b00-20b0-11ea-86f1-c657df06ccdd.png">

**Comment by jywarren** [comment]
Hi, Stevie, thanks! I think we want it to look more like https://publiclab.org/comments, right? Like this?

![image](https://user-images.githubusercontent.com/24359/71021788-13c0ac00-20cd-11ea-9293-a1966340d6a6.png)

I believe it's the same template -- looks like we just need to do some adjusting -- I believe it's this one:

https://github.com/publiclab/plots2/blob/master/app/views/comments/index.html.erb

I see 2 issues; first, it seems to work better when the user has comments; the one you looked at maybe had none, and maybe that broke the layout? Here, i have some and it looks OK on my profile:

https://publiclab.org/profile/comments/warren/

Maybe that's a clue! But the second issue is that there are just some odd formatting things going wrong, like the tab for "Moderated Comments", and the spacing. We use https://getbootstrap.com/docs/4.3/components/ to style this so it could probably use some tidying up! Thanks!

**Comment by steviepubliclab** [comment]
Yes but for someone's individual profile.
-Stevie

**Comment by SidharthBansal** [comment]
Publishedx

**Comment by steviepubliclab** [comment]
Thank you!!
