### ISSUE TITLE
Make the main navigation bar responsive

### ISSUE THREAD

**Issue by VladimirMikulic** [publiclab/plots2#6995]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 🔥 Problem:

![Screenshot_20191217_175103](https://user-images.githubusercontent.com/35997844/71023601-5ef5b180-2103-11ea-912b-a0361f90430f.png)

![Screenshot_20191217_175206](https://user-images.githubusercontent.com/35997844/71023615-6321cf00-2103-11ea-97d7-afd14c34c614.png)

As you can see from the pictures above, the current navigation bar has some problems :(
Search bar splits up on screens width  990 - 1110 & 768 - 860.
On mobile devices, the hamburger menu is not aligned with the logo. 

### 🚩 Goal:

![nav](https://user-images.githubusercontent.com/35997844/71024209-b34d6100-2104-11ea-8d99-87e2f8a628cd.png)

![Screenshot_20191217_180357](https://user-images.githubusercontent.com/35997844/71024001-39b57300-2104-11ea-84ae-02c7116eb82f.png)

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Work**

**1)** Open plots2/app/views/layouts/_header.html.erb

- Remove inline styles from the input element on line 20 plots2/app/views/layouts/_header.html.erb

- On line 149 change the class `d-xl-none` to `d-lg-none` to make the hamburger menu disappear on the large screens

**2)** Open plots2/app/assets/stylesheets/style.css

- On line 221 - 229, remove `padding-top`, add `margin-top: 0.3125rem;` and set `margin-bottom: 0;` like this:

```css
@media (max-width: 768px) {
  #header #brand,
  #header #brand-compact {
    margin-top: 0.3125rem;
    padding-bottom: 0;
    padding-right: 4px;
  }
}
```

- After line 128, `#pl_pad` selector add this code:

```css
#header .navbar .input-group {
  flex-wrap: nowrap;
}

#header .navbar #searchform_input {
  cursor: text;
  min-width: 190px;
}
```

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by jywarren** [comment]
Hi, this is really great! I believe there is an easier fix documented here, however: https://github.com/publiclab/plots2/issues/6888

Can you integrate that into this FTO? Thank you so much!!!

**Comment by VladimirMikulic** [comment]
@jywarren updated accordingly :)

**Comment by polygonart6777** [comment]
I would like to claim this issue!

**Comment by VladimirMikulic** [comment]
@polygonart6777 of course, please do! Welcome to PublicLab :tada: :tada: :tada: 
If you have any questions, you can ask me.
You should also introduce yourself to the community on [Gitter](https://gitter.im/publiclab/publiclab) :cocktail:
