### ISSUE TITLE
search page returns original wiki page title

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#7]
If a wiki page title has been changed, the search page returns the initial title and not the newest title.

I have to assume this will be a simple fix in the code from reading `node.title` to `node.latest.title`.

**Comment by jywarren** [comment]
That's right -- but which page, exactly? The only place I could find that this happened was on the advanced search page at https://publiclab.org/search/advanced

The code for that is here: https://github.com/publiclab/plots2/blob/master/app/views/search/advanced.html.erb#L43

and indeed, it's using `node.title`. Should be an easy fix! Bryan, would you mind if I reformatted this to follow the basic format of this issue: https://github.com/publiclab/plots2/issues/247 and then tagged it with `first-timers-only`?

**Comment by ananyo2012** [comment]
@jywarren Does this issue needs a fix? Or will it be kept as a `first-timer-only` bug? The autocomplete results also show the old title. So we need a `match.latest.title` in the search controller. Well this indeed is an easy fix.

**Comment by jywarren** [comment]
I think that this might be addressed by the new search interface, and in
the meantime, I'd like to leave the first-timers-only issues open, as they
take some work to prepare. If you're looking for something to do, maybe
give a try making a first-timers-only issue -- it's challenging, but can
really help recruit contributors!

**Comment by ananyo2012** [comment]
Ok I will then try converting this as a first-timer issue by adding more content here.You can then label it as a first timer issue.

**Comment by jywarren** [comment]
great, ping me when you do and I can delete extra comments too -- and/or
you can open a new issue, close this one linking to the new cleaner one if
you like.

**Comment by ananyo2012** [comment]
@jywarren Hey Jeff I solved this issue in #600. I found that this problem was occurring only for wiki pages since the wiki title was not updated with each revision. But I had to update the title so as to update the wiki url. So this issue has to be closed once #600 gets merged. I think I can find other issue that can be labeled as `first-timer-only` issue and probably make one if found.

**Comment by jywarren** [comment]
Super, that would be great. Maybe helping Liz make #599 into a first-timers only, since it's just moving html markup around, with one Ruby conditional inside?
