### ISSUE TITLE
signup offers to auto-subscribe you to tags you were looking at

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#70]
so if users sign up through a page on spectrometry or formaldehyde exposure, their subscriptions might be pre-populated with content tagged as such.

An extra field in the login form might indicate some tags which you could add to or delete, like

**Comment by biswesh456** [comment]
May I take this? Is there any prior work done in it?

**Comment by jywarren** [comment]
We haven't much looked at this!

I think we could start by thinking about ways to think about tags to
follow. What if we made a function of the User model which displayed all
the tags on posts you've posted, liked, commented on or answered.

That would quickly become a big list. So take the most recent 10 and show
them on the /subscriptions page in the sidebar, saying "you've interacted
with these topics recently. Click to subscribe to updates on them." or
something. What do you think?

On Thu, Jan 25, 2018 at 5:16 AM, Biswesh Mohapatra <notifications@github.com

**Comment by biswesh456** [comment]
Well thats a great idea. Can we keep two lists - one with recent ones and one with most frequently visited ones?

**Comment by biswesh456** [comment]
So @jywarren should I start looking at how to implement the idea? Or further discussion is required?

**Comment by biswesh456** [comment]
Hey @jywarren just noticed PR #2058. Doesn't it do what we were discussing about?

**Comment by jywarren** [comment]
Close! Actually that displays topics you have already subscribed to. This
issue tries to list out topics you might WANT to subscribe to. Make sense?

On Fri, Jan 26, 2018 at 3:07 PM, Biswesh Mohapatra <notifications@github.com

**Comment by Gauravano** [comment]
Hi @jywarren can I take this

**Comment by jywarren** [comment]
awesome!

**Comment by biswesh456** [comment]
@jywaren I am busy with some college work hence could not give time to this issue. Hopefully @Gauravano could Do it soon!!! Good luck

**Comment by jywarren** [comment]
ok! no problem, and thank you!

**Comment by gauravano** [comment]
@jywarren I think we can re-post this issue with some more details. Do you think we want to add a suggestion field to the sign-up form where tags would be contained?

Thanks!

**Comment by jywarren** [comment]
I believe we can close this one!

**Comment by gauravano** [comment]
ok, closing this then. Thanks!
