### ISSUE TITLE
PublicLab homepage: Images in projects section squished with text on mobile devices

### ISSUE THREAD

**Issue by VladimirMikulic** [publiclab/plots2#7002]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### :fire: Problem

![Screenshot_20191218_122435](https://user-images.githubusercontent.com/35997844/71082769-f6094a80-2191-11ea-8dd1-41e0c298696f.png)

![Screenshot_20191218_122503](https://user-images.githubusercontent.com/35997844/71082778-f9043b00-2191-11ea-9aae-55f8a551d5c6.png)

As you can see, images on mobile devices are squished with text.
We should add some spacing in between.

### 🚩 Goal

![Screenshot_20191218_123027](https://user-images.githubusercontent.com/35997844/71082925-3ec10380-2192-11ea-8a54-6adc81ed441e.png)

![Screenshot_20191218_122956](https://user-images.githubusercontent.com/35997844/71082935-42ed2100-2192-11ea-850a-7290d041e12b.png)

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Work** Open the file plots2/app/views/home/home.html.erb 
At the bottom of the <style> tag add this code:

```css
@media(max-width: 575px){
  .projects .project-image:nth-of-type(1),
  .projects .project-image:nth-of-type(3) {
    margin-bottom: 1.7rem;
  }
}
```  

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by 0dim** [comment]
Hi! I've never contributed to an open source project before, I'm interested in doing this.

**Comment by VladimirMikulic** [comment]
Hi @0dim! Welcome to PublicLab :balloon: 
PublicLab is a community of hard-working, passionate and creative people.
You can meet all of us on [Gitter](https://gitter.im/publiclab/publiclab)

We welcome first-time contributors and we would appreciate getting this issue fixed.
If you are stuck, don't worry, others and I are here to help! :open_hands: 

If you are a GCI student, don't forget to checkout #6808

**Comment by Priyanka-Bnsl** [comment]
can i work on this issue?
