### ISSUE TITLE
Add test.sqlite-journal file to git ignore

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#7003]
Description
------------

This file is becoming annoying and affecting a couple of pull requests and its easily committed esp if contributors use `-A` flag while committing.

Lets gitignore this file as we do  not need to track the changes done.

Here is a good outline to follow if needed https://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore

**Comment by jywarren** [comment]
Agreed! Thanks!

**Comment by Manvi07** [comment]
I think it's already in gitignore. @cesswairimu

**Comment by cesswairimu** [comment]
oh yeah I see @Manvi07 thanks, could be it wasn't added the right way... we are still tracking changes from it.

**Comment by AnshitaVishwa** [comment]
@cesswairimu I would like to work on it. By the time I'll browse and search for it. Thanks!!

**Comment by cesswairimu** [comment]
Nice just llet me know if u need my help..this is the file https://github.com/publiclab/plots2/blob/master/test.sqlite-journal

**Comment by AnshitaVishwa** [comment]
@cesswairimu I guess the file test.sqlite-journal has already been added in the git ignore. Should I do this once again?

**Comment by cesswairimu** [comment]
Yeah... It is already added but if you look at the repo we are still tracking it... So we need to fix that... The link I provided above :point_up: could help you in fixing that
