### ISSUE TITLE
Projects button on home page should be more relevant

### ISSUE THREAD

**Issue by Uzay-G** [publiclab/plots2#7004]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- Change the text of this button to "Submit your own" or "Learn More":
https://github.com/publiclab/plots2/blob/883c509ae5911e28955e666100be8be2f3872280/app/views/home/home.html.erb#L56
This link redirects to a wiki to help users on building their own projects and not actually more projects. It would make more sense to have a link title that actually references the purpose of the /projects page.

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by jywarren** [comment]
Hi! This may need some input from @publiclab/community-reps or at least
some +1 from them before being ready to complete! Thanks!!!

**Comment by Uzay-G** [comment]
Yeah no I totally get it @jywarren! I was about to ask.

**Comment by jywarren** [comment]
Awesome, thank you so much!

**Comment by Uzay-G** [comment]
Hey! @publiclab/community-reps, do you think this should be done or is it not a good idea?

Thanks :smile:

**Comment by steviepubliclab** [comment]
Hi @Uzay-G! 
Can you post in the page this would edit? i see the text suggestion, but can't tell where it would go. 

Thank you!
-Stevie

**Comment by Uzay-G** [comment]
Oh yeah it would be on this page:
![fto-3](https://user-images.githubusercontent.com/52892257/71291604-6de29b00-2373-11ea-89a3-14a6393d2001.png)

**Comment by steviepubliclab** [comment]
Hi ah ok got it. Thank you!  I do want that page to list out more projects as well as help people walk through making their own pages. So I'd prefer to leave the text as is right now.

**Comment by Uzay-G** [comment]
Yeah ok no problem. Should I close the issue?

**Comment by steviepubliclab** [comment]
Sounds good. Thank you!!
