### ISSUE TITLE
Excerpts of tag pages are cut off

### ISSUE THREAD

**Issue by Uzay-G** [publiclab/plots2#7006]
### Please describe the problem (or idea)

> What did you expect to see that you didn't?
I was trying to go on the topic pages of certain tags like this one:

![excerpt-bug](https://user-images.githubusercontent.com/52892257/71125338-08fa3a00-21e7-11ea-91c0-23f50196701a.png)

I noticed that the excerpts of the wiki descriptions are cut off for several of them as you can see above. I think we should try and fix this so the full paragraph is displayed.

### Please show us where to look

The code that decides this is at this line of the show tag view:
https://github.com/publiclab/plots2/blob/562e17306d0ddafb592bb8ad08a57ed73f8995c1/app/views/tag/show.html.erb#L23.
It takes the body of the wiki description and takes the first paragraph using the ```split()``` function.
I don't know why this isn't working but am going to try and figure it out. I would love your help :smile:.

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by sharmamansi** [comment]
Hey @Uzay-G , I guess the content is still rendering but its hidden as overflow property is set to hidden in class wiki-sub. I guess some adjustment in css font size could help over here.

**Comment by Uzay-G** [comment]
Yeah I checked and you are right that the problem is with the overflow. I'm not sure how exactly we can fix it.

**Comment by sharmamansi** [comment]
I think adding a scroll can fix it.

**Comment by sashadev-sky** [comment]
Assigning myself just a reminder to come back and check in here!

**Comment by sashadev-sky** [comment]
I checked this out.. the issue with adding a scroll is that the scroll box will look really small and have markdown syntax in it which won't render correctly
![2020-01-18 20 53 37](https://user-images.githubusercontent.com/41092741/72673176-af2e9f00-3a34-11ea-9b2d-442d273fe561.gif)

I wanted to make an FTO out of this but I think its a little complicated so just opening a PR with a quick fix!
