### ISSUE TITLE
Login view password field

### ISSUE THREAD

**Issue by EmirVatric** [publiclab/plots2#7008]
In the login view, the password field eye icon is not aligned properly.

![Screenshot 2019-12-19 at 00 01 45](https://user-images.githubusercontent.com/46676569/71132641-5b902200-21f8-11ea-9f16-c1c58635e22e.png)

### What's your PublicLab.org username?
emirvatric

Chrome - Version 79.0.3945.88 (Official Build) (64-bit)

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by EmirVatric** [comment]
I would be happy to do this issue 👍

**Comment by VladimirMikulic** [comment]
@EmirVatric the screenshot that you've provided above, is it the development or the production version? In production, the icon is aligned properly.

![Screenshot_20191219_010424](https://user-images.githubusercontent.com/35997844/71133661-8c258b00-21fb-11ea-8730-b27e777d0beb.png)

**Comment by EmirVatric** [comment]
Hi, @VladimirMikulic in production.
After pointing this out I notice that only from root route the login form has the icon aligned properly, but only if you try to login from the root route.

![Screenshot 2019-12-19 at 01 12 53 (2)](https://user-images.githubusercontent.com/46676569/71134093-48cc1c00-21fd-11ea-8b4c-ee9f27ee290f.png)
![Screenshot 2019-12-19 at 01 18 23](https://user-images.githubusercontent.com/46676569/71134176-7f099b80-21fd-11ea-843d-7df3350170a1.png)

**Comment by VladimirMikulic** [comment]
@EmirVatric good catch :medal_military: I can confirm all these issues. :beetle: 
We would appreciate you getting this fixed :)

You can open another issue for "Sign Up" modal misalignment and do it after this one.

**Comment by EmirVatric** [comment]
@VladimirMikulic 
When looking into this I encountered something that I don't really understand. On root route on element id='visibility' class input-group-text is found before class fa and occurs twice, and property **display: flex (from class input-group-text) overrides property display: inline-block(class fa)**

![Screenshot 2019-12-19 at 02 17 29](https://user-images.githubusercontent.com/46676569/71136663-d449ab00-2205-11ea-8f12-b177bb991049.png)

And in other views, class fs occurs before class input-group-text, and **property display: inline-block(class fa) overrides display: flex (from class input-group-text)**
![Screenshot 2019-12-19 at 02 18 44](https://user-images.githubusercontent.com/46676569/71136878-871a0900-2206-11ea-8957-b074ad50548f.png)

In submitted PR, I used bootstrap classes 'd-flex' wich will use !important to enforse flexbox.

**Comment by VladimirMikulic** [comment]
I've tested it and it works, I've approved the changes :)

**Comment by shipcy** [comment]
Can I take this ?

**Comment by VladimirMikulic** [comment]
Hi @shipcy. We already have a PR that resolves this issue. Please try other FTOs.
Thanks.
