### ISSUE TITLE
Login/Logout Flash messages show in Deutsch even when language is set to English

### ISSUE THREAD

**Issue by ananyo2012** [publiclab/plots2#701]
Hi, this is a `first-timers-only issue`. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The Problem
When you login or logout in publiclab.org the flash messages gets displayed in Deutsch even when the language is set to English. Here is a snap: 
![logout](https://cloud.githubusercontent.com/assets/10486343/17816720/46a4ad70-6658-11e6-85b4-79d8f8e7e3da.png)

## Solution
Look at this line that should contain the locale for Deutsch: https://github.com/publiclab/plots2/blob/master/config/locales/controllers/user_sessions_controller/de.yml#L3. Here `en` must be changed to `de` and that solves it!

## Steps to Fix
- [ ] claim this issue with a comment
- [ ] set up a repository locally and make sure that all tests pass
- [ ] start a pull request (see contributing to Public Lab software) but mark it as "in progress"
- [ ] fix the issue following the steps above
- [ ] try the manual test listed above
- [ ] make sure all tests pass with rake test
- [ ] alert someone via either the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by jiteshjha** [comment]
Nice catch @ananyo2012 ;
In https://github.com/publiclab/plots2/blob/master/config/locales/controllers/user_sessions_controller/de.yml#L3 , 'en' must be changed to 'de' -- I think this can qualify as a first-timer bug? Thanks!

**Comment by jywarren** [comment]
Yes, that would be great. Feel free to edit this one or post a new one and
close this, linking to it. Thanks!

**Comment by ananyo2012** [comment]
Yeah I can edit this one and remove other comments to cleanup.

**Comment by ykl7** [comment]
@jiteshjha you mind if i take this one? minor bug to fix

**Comment by jiteshjha** [comment]
Sure @ykl7. Let me know if you need any assistance. :)

**Comment by ebarry** [comment]
Hi @ykl7! Thank you again for your valuable contribution to Public Lab. I would like to invite you to join us in a video conference to say a few words about what you contributed and how your experience was. The event is https://publiclab.org/openhour, and it’s coming right up on November 7th, at 1pm EDT which is UTC/GMT -4. 

Please feel free to respond here, or else email liz@publiclab.org, stevie@publiclab.org, jeff@publiclab.org.
