### ISSUE TITLE
Make footer topics section responsive

### ISSUE THREAD

**Issue by VladimirMikulic** [publiclab/plots2#7017]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### :fire: Problem

![Screenshot_20191219_195245](https://user-images.githubusercontent.com/35997844/71201320-102e5000-229a-11ea-9557-28afd203efe1.png)

![Screenshot_20191219_195354](https://user-images.githubusercontent.com/35997844/71201326-13294080-229a-11ea-807b-5019af12cec7.png)

![Screenshot_20191219_195422](https://user-images.githubusercontent.com/35997844/71201329-16243100-229a-11ea-94c4-d0512945a508.png)

The footer topics section looks really bad :(
That's why you are here, right?

Make it responsive 😎

### 🚩 Goal

![Screenshot_20191219_195507](https://user-images.githubusercontent.com/35997844/71201360-29cf9780-229a-11ea-97c1-4d5584de1140.png)

![Screenshot_20191219_195553](https://user-images.githubusercontent.com/35997844/71201408-3f44c180-229a-11ea-81f7-7d27d3157337.png)

![Screenshot_20191219_195633](https://user-images.githubusercontent.com/35997844/71201414-44a20c00-229a-11ea-9704-d26c7d1b33c9.png)

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Open** plots2/app/assets/stylesheets/style.css
After the `footer ul` selector(line 278) add this code:

```css
.footer-topics .row {
    justify-content: space-around;
}

.footer-topics .row .col-md-3 {
    flex-basis: 50%;
    max-width: fit-content;
}

@media(max-width: 768px) {
    .footer-topics .row .col-md-3 {
        max-width: none;
        text-align: center;
    }
}
```

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by candesign** [comment]
I'd like to do this. :)

**Comment by VladimirMikulic** [comment]
@candesign go for it :rocket:

**Comment by Priyanka-Bnsl** [comment]
can i work on this issue?

**Comment by VladimirMikulic** [comment]
Hi, @Priyanka-Bnsl. I am glad that you are interested in working with us :rocket: 
We have a PR for this issue, but if you wish you could help us by fixing [this issue](https://github.com/publiclab/image-sequencer/issues/1381)

Thanks.

**Comment by jywarren** [comment]
Hi all, just a warning that some of the code for this may be in a
database-backed feature, and not in the github repository itself! Wed still
love help but if you can't find it we can copy code into the database to
resolve this and can still give credit! Thanks!

**Comment by VladimirMikulic** [comment]
@jywarren could you explain to me what is a database-backed feature?
Where should I find it? Thanks.

**Comment by guptaaman70659** [comment]
I am Interested to resolve this issue

**Comment by guptaaman70659** [comment]
I have added the code in style.css. and made  pull request 
If there something I forget please tell me

**Comment by VladimirMikulic** [comment]
Hi @guptaaman70659. I am glad that you are showing interest in our project.
This issue has already been solved, as you can see we have 2 PRs for it.

You can take a look at other FTOs.

**Comment by guptaaman70659** [comment]
Hi @VladimirMikulic  
First of all thanks for giving response 
I have one doubt why this Issue  is opened yet If it has already been solved ?

**Comment by VladimirMikulic** [comment]
@guptaaman70659 we misunderstood each other. By "solved" I meant that we have 2 PRs that are resolving this issue.

I hope it's clear now :)
Also, Happy New Year :tada:

**Comment by Uzay-G** [comment]
Closed in https://github.com/publiclab/plots2/pull/7018!
