### ISSUE TITLE
Can't find edit button

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#7021]
Hello! I was hoping to do an edit on this wiki page https://publiclab.org/wiki/barnraising but I can't find where the edit button went. Is there any way we could get it back in the toolbar in the header of the wiki? 

Thanks

**Comment by jywarren** [comment]
Hi Stevie, I think someone had used the "sidebar:none" powertag which may
have hidden the edit button. It should be fixed now I deleted it, can you
check? If not there could be another issue and we can check.

**Comment by jywarren** [comment]
I believe this is solved!

![image](https://user-images.githubusercontent.com/24359/71674601-a27a2d80-2d49-11ea-8d79-89e446dcd746.png)
