### ISSUE TITLE
Bug in the Search Controller

### ISSUE THREAD

**Issue by AnshitaVishwa** [publiclab/plots2#7026]
When I tried clicking on the **"Questions"** 

![Screenshot from 2019-12-21 14-26-42](https://user-images.githubusercontent.com/36095454/71305735-10476080-23fe-11ea-9999-5e0fa4870006.png)

It shows...........

![Screenshot from 2019-12-21 14-24-04](https://user-images.githubusercontent.com/36095454/71305742-1f2e1300-23fe-11ea-84bf-6d3ec541c529.png)

similarly when clicked on **"Notes"**

It shows...................

![Screenshot from 2019-12-21 14-24-27](https://user-images.githubusercontent.com/36095454/71305751-44228600-23fe-11ea-83c9-c2f73596bf22.png)

**Comment by AnshitaVishwa** [comment]
I would like to work on it.

**Comment by VladimirMikulic** [comment]
@AnshitaVishwa on which page this issue occurs and under what circumstances?
I would like you to provide more details.

**Comment by AnshitaVishwa** [comment]
@VladimirMikulic It is occuring on the page    **'/search/content/'** 
Whether there is query or not but it will show this error.

**Comment by AnshitaVishwa** [comment]
@VladimirMikulic on the real website this error is not there....but when i m trying this on the local host it persists....I think I should close the issue.

**Comment by VladimirMikulic** [comment]
@AnshitaVishwa I think that you should close the issue. This error occurs probably because you have some problems with the database. Also, the development version differs from the production one.
