### ISSUE TITLE
New design for location popup modal

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#7031]
I'd really like to redesign the popup modal so that it looks and feels like the in-line form at /post/ . Here are two options I came up with. Which do you prefer? Any other suggestions? Open to all ideas!

Also I had a question of whether that Scale slider is needed or not? We already will have zoom buttons and mouse zoom in the map itself.

Option 1: 

![Option 1](https://user-images.githubusercontent.com/49460529/71312613-e0e32480-23fa-11ea-8b51-f7d64f361ee2.png)

Option 2:

![Option 2](https://user-images.githubusercontent.com/49460529/71312617-e476ab80-23fa-11ea-8d43-5d5a794d0e90.png)

And here's how it would look like on an iphone:

![iPhone 6-7-8 – 1](https://user-images.githubusercontent.com/49460529/71312627-efc9d700-23fa-11ea-90b8-29b9ede56e8a.png)

**Comment by sagarpreet-chadha** [comment]
@jywarren , @ebarry need your help here 😄 !

**Comment by jywarren** [comment]
Hi! I like (1) a lot. As to the slider, I think it really helps to emphasize the relationship between zoom and privacy, so I'd like to keep it! Thank you!

**Comment by jywarren** [comment]
Also, what if we removed the extra input for "Place name as it will be saved" and instead displayed that text in grey, in quotation marks, just next to... the save button? Or somewhere else? It's just visually crowded right now and I wonder if we can do something else to indicate a "final check" for what it'll say when you save, you know?

**Comment by nstjean** [comment]
Okay! Yes I like the idea of moving the "place name will be saved as" to a less prominent position. I'll play around and post some ideas.
