### ISSUE TITLE
PublicLab Newsletter title dropdown doesn't work on screeens < 992px

### ISSUE THREAD

**Issue by VladimirMikulic** [publiclab/plots2#7037]
[Demo](https://streamable.com/65wxq)

**Comment by SidharthBansal** [comment]
You will get one point for bug reporting.
If you sent a fix then we will give you 3 more points by classifying this into medium task

**Comment by SidharthBansal** [comment]
Similarly for all gci students for all suggestions and bug reporting tasks
I hope all the students are liking this scheme
