### ISSUE TITLE
Hide honeypot field for spamaway signup

### ISSUE THREAD

**Issue by Uzay-G** [publiclab/plots2#7044]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along.
-  We need **your help** because at the bottom of [spamaway signup page](https://publiclab.org/signup?spamaway=true) there is a form field that says `Don't write anything here if you're a real person.`. This is a spam-blocking technique using a [honeypot field](https://www.thryv.com/blog/honeypot-technique/). Spam bots will fill in every field on the page (even hidden ones) that users are not supposed to fill in. Since they will fill the form anyways, it's better to hide it from the view of the actual users. This is how you can help us do this :smile:.
- This is the `<div>` element that we want to hide:
https://github.com/publiclab/plots2/blob/cd43dfdf8d9b0987aa640ac5a5eb0a9981023eef/app/views/users/_spamaway.html.erb#L29.
As you can see. it has the `hide` class that is actually not defined to hide the element. Instead replace the `hide` with [`d-none`](https://getbootstrap.com/docs/4.0/utilities/display/#hiding-elements) which is already defined to hide the element.
[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by DhyeyLalseta** [comment]
I will try to claim the issue.

**Comment by DhyeyLalseta** [comment]
I created the pull request. Asking for review. :)

**Comment by Uzay-G** [comment]
Thanks for contributing @DhyeyLalseta and welcome to Publiclab! I'll check out your pull request :+1:

**Comment by daemon1024** [comment]
Thanks @Uzay-G for directing me to this issue. I will claim it and start working on it :)

**Comment by developer22-university** [comment]
HI, @Uzay-G  i am claming this.

**Comment by Uzay-G** [comment]
Great @daemon1024! Sorry @developer22-university but @daemon1024 has already claimed this. If you want you can do https://github.com/publiclab/spectral-workbench/issues/472.

**Comment by daemon1024** [comment]
@Uzay-G I request you to review my PR.
