### ISSUE TITLE
Remove incorrect color and extra space from button on Profile

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#7050]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [profile.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/users/profile.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

On this line:
https://github.com/publiclab/plots2/blob/cd43dfdf8d9b0987aa640ac5a5eb0a9981023eef/app/views/users/profile.html.erb#L76

We need to change it to this:
```
    <a class="btn btn-outline-secondary" id="info-ellipsis"><i class="fa fa-ellipsis-h" style="margin:0"></i></a>
```

This is it looks like now:
![FireShot Capture 133 - 🎈 Public Lab_ admin - localhost](https://user-images.githubusercontent.com/49460529/71523992-7d914080-2899-11ea-9551-3bb1409fce87.png)

And this is what it will look like after!
![FireShot Capture 135 - 🎈 Public Lab_ admin - localhost](https://user-images.githubusercontent.com/49460529/71524005-86821200-2899-11ea-98b6-1f35a2618675.png)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by nathanjr94** [comment]
Hello, I'd like to claim this issue.

**Comment by nstjean** [comment]
Excellent! Go for it!

**Comment by skritichauhan** [comment]
I too would like to claim this issue.

**Comment by aptvaibhav** [comment]
hey is this done? Else i would like to fix this issue.

**Comment by nstjean** [comment]
@skritichauhan and @aptvaibhav this issue has been completed. I'll post some more FTOs this week!
