### ISSUE TITLE
Add hover style to all btn-outline-secondary buttons

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#7051]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [style.css](https://github.com/publiclab/plots2/blob/master/app/assets/stylesheets/style.css) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Just after these lines:
https://github.com/publiclab/plots2/blob/cd43dfdf8d9b0987aa640ac5a5eb0a9981023eef/app/assets/stylesheets/style.css#L496-L498

Add in these:
```
    a.btn-outline-secondary:not([href]):not([tabindex]) {
      color: #6c757d;
    }
    
    .container .btn-outline-secondary:hover {
      color: white !important;
    }
    
    .container .btn-outline-secondary:hover .fa {
      color: white !important;
    }
```

This is what one of the buttons look like on hover now:
![FireShot Capture 132 - 🎈 Public Lab_ Dashboard - localhost](https://user-images.githubusercontent.com/49460529/71525669-c13b7880-28a0-11ea-82d9-304c05b4c182.png)

And this is what it will look like after:
![FireShot Capture 136 - 🎈 Public Lab_ Dashboard - localhost](https://user-images.githubusercontent.com/49460529/71525712-065faa80-28a1-11ea-9e28-b7e7bde70553.png)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by nstjean** [comment]
A note about these changes:

This will fix the buttons on the right side of the user profile and the left side of the dashboard - and all btn-outline-secondary that keep having bootstrap override the hover color. I've added `.container` because we want to leave the top nav buttons alone, we only want to target any in the main section.

The `a.btn-outline-secondary:not([href]):not([tabindex])` is to override a color set in bootstrap for any `a` tags that do not have an `href`, such as the ones mentioned on the profile and dashboard, all buttons of `.btn-otuline-secondary` should look the same, regardless of them having an `href` or not.

**Comment by CodeMeKathy** [comment]
Hi! - If I may, I would like to claim this one.

**Comment by DevanshCodes** [comment]
Hey! is it open? if it is I want to claim this one.

**Comment by CodeMeKathy** [comment]
@DevanshCodes, I was waiting for confirmation.  Did you see my claim?  Have you already completed the work?

**Comment by VladimirMikulic** [comment]
@CodeMeKathy @DevanshCodes has already submitted a PR. He made a mistake.
Could you please check out other FTOs?

Thanks.
