### ISSUE TITLE
Map allows scrolling out-of-bounds and saves incorrect longitude

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#7052]
When entering a profile location with the popup modal I've noticed that the lon just keep going even when you scroll past the map bounds of -180/180 longitude. If we allow users to keep scrolling their map then we need to correct the numbers to stay within the bounds when we save the info in plots2.

Saving a number out of bounds is causing an issue on /map/ when loading a user location.

Example:

![FireShot Capture 139 - 🎈 Public Lab_ admin - localhost](https://user-images.githubusercontent.com/49460529/71526297-352b5000-28a4-11ea-9704-5aefe5102060.png)

The incorrect number is saved, this should be corrected to [0, 115], in which -245 + 360 = 115

![FireShot Capture 140 - 🎈 Public Lab_ admin - localhost](https://user-images.githubusercontent.com/49460529/71526302-39f00400-28a4-11ea-9946-2440a25564f8.png)

Instead of showing Indonesia in /map/ this is showing somewhere in the middle of the Pacific ocean:

![FireShot Capture 141 - 🎈 Public Lab_ Map - localhost](https://user-images.githubusercontent.com/49460529/71526307-3f4d4e80-28a4-11ea-86ea-def7c3f2d07f.png)

On the modal it also allows scrolling past the edge of the north and south poles but it does not allow the numbers to go beyond -90/90 latitude, so this appears to be a longitude only problem.

![FireShot Capture 144 - 🎈 Public Lab_ admin - localhost](https://user-images.githubusercontent.com/49460529/71526756-542ae180-28a6-11ea-8dca-3a9f10e3eb7b.png)

I will be looking into this and figuring out if this is plots2, LBL, or LEL?

**Comment by nstjean** [comment]
So this is how Leaflet maps work. We need to check and adjust that number before sending the data as a powertag. I suggest a function in LBL, maybe something like `blurredLocation.getLonWithinBounds()` Then we can call that in instead of `blurredLocation.getLon()` to create the tag. @jywarren @sagarpreet-chadha What do you think?

**Comment by sagarpreet-chadha** [comment]
Is it possible to restrict the map boundaries?
We already do that so that map does not goes to infinite panning, can we use that here? (See how we initialize the map, we pass bounds object)
 Thanks!

**Comment by nstjean** [comment]
Yes I believe that's pretty easy to do!

**Comment by nstjean** [comment]
@sagarpreet-chadha Do we want to limit all LBL maps? Or do we want to create an option?

**Comment by nstjean** [comment]
@sagarpreet-chadha Or we can call blurredLocation.map.setMaxBounds and not have to change LBL.

**Comment by sagarpreet-chadha** [comment]
>  I suggest a function in LBL, maybe something like blurredLocation.getLonWithinBounds()

Yes this looks better approach. Let's do this, Thanks 😄

**Comment by nstjean** [comment]
@sagarpreet-chadha Ok! Should I close my PR to set map bounds?

**Comment by nstjean** [comment]
@jywarren Do you have a preferences? Setting map bounds in plots2 so people can't scroll past the edge? Or create a function in LBL to correct the number?
