### ISSUE TITLE
Horizontal scrolling on homepage

### ISSUE THREAD

**Issue by VladimirMikulic** [publiclab/plots2#7056]
![Screenshot_20191228_184400](https://user-images.githubusercontent.com/35997844/71547619-8f123f80-29a2-11ea-8f2f-a6d6b3f79117.png)

As the title suggests, we have a horizontal scrollbar on the homepage.
It persists on all devices(desktop, tablet & mobile).

The scrollbar is especially annoying on laptops when you scroll via touchpad and the page constantly moves left-right.

Homepage code is not in the repo so I can't submit a PR, but I would be more than happy to provide admins with the code that fixes this.

**Comment by SidharthBansal** [comment]
Great. You will get 1 point for bug reporting. Thanks

**Comment by SidharthBansal** [comment]
There is a pr and an issue related to it. Is it a duplicate issue?

**Comment by VladimirMikulic** [comment]
@SidharthBansal it seems that this is a duplicate of #7064, although I reported the bug first.

**Comment by SidharthBansal** [comment]
Kindly close the one duplicate and add information at one place so that things are unambiguous

**Comment by VladimirMikulic** [comment]
:+1:
