### ISSUE TITLE
"Internal Server Error" when posting research note

### ISSUE THREAD

**Issue by wmacfarl** [publiclab/plots2#7062]
**NOTE: immediate issue solved, and several more changes have been made to prevent this in the future, but one of the several causes is still open pending, see [this comment below](https://github.com/publiclab/plots2/issues/7062#issuecomment-572811285)**

### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I attempted to save a research note as a draft.  I also followed up by attempting to post a new "test" research note and got the same result/error.

> What did you expect to see that you didn't?

When I clicked "Save" the "Save" button was replaced with the spinning progress indication icon as usual but nothing happened.  When I looked in the developer console I saw the following errors:

![image](https://user-images.githubusercontent.com/757598/71604871-daf3ee80-2b32-11ea-9405-f42e17949d6c.png)

### Please show us where to look

I have attached the markdown text of the note I was initially trying to post, but I had the same problem using a different browser with a research note that simply said "test" so I don't think it's a problem with the body of the research note.

### What's your PublicLab.org username?
wmacfarl

### Browser, version, and operating system
Windows 10, using Firefox and Google Chrome

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

[sensor_platform_build_guide_draft.md.txt](https://github.com/publiclab/plots2/files/4011450/sensor_platform_build_guide_draft.md.txt)

**Comment by jywarren** [comment]
Thanks for reporting -- I'm checking this on Sentry now.

**Comment by jywarren** [comment]
Yes, looks like first incident on Dec 20th:

![image](https://user-images.githubusercontent.com/24359/71674737-10265980-2d4a-11ea-86d1-510473fde679.png)


```
ActiveRecord::RecordNotUnique
Mysql2::Error: Duplicate entry '0' for key 'index_node_vid': INSERT INTO `node` (`type`, `title`, `uid`, `status`, `changed`, `comment`, `path`, `slug`) VALUES ('note', 'required certifications for becoming a switch network engineer', 649997, 4, 1577967893, 2, '/notes/switchnetwork/01-02-2020/required-certifications-for-becoming-a-switch-network-engineer', 'required-certifications-for-becoming-a-switch-network-engineer')
```

**Comment by jywarren** [comment]
Previously came up in https://github.com/publiclab/plots2/issues/5118

We should make a hard rule to ensure this can't happen?

**Comment by jywarren** [comment]
Here it seems when creating a draft it's somehow possible to create a node with nid 0, which causes this: https://github.com/publiclab/plots2/issues/5118#issuecomment-473608697

**Comment by jywarren** [comment]
So our follow-ups are:

1. remove the draft w/ `nid=0` to unblock the issue
2. investigate how this happens while making drafts
3. come up with alternative means of creating default records that don't rely on `nid = 0`

**Comment by jywarren** [comment]
Ah, and just noting, it's `vid` not `nid` which is zero

**Comment by jywarren** [comment]
And confirming it was a draft which resulted in this error, same as last time!

**Comment by jywarren** [comment]
Basic posting is back online. Moving to 2) how this happens.

**Comment by jywarren** [comment]
I'm theorizing that we must get in a state where there is a note created, which would have `vid=0` but then the revision is invalid, and the `node.vid` doesn't get updated. It could happen in this section of the code:

https://github.com/publiclab/plots2/blob/3267de0b4872c07d2aaa6ab523d33e45e062cb33/app/models/node.rb#L662-L683

**Comment by jywarren** [comment]
That's all in a transaction so it's supposed to roll back if anything goes wrong... i noticed this happened before in https://github.com/publiclab/plots2/issues/6678

**Comment by jywarren** [comment]
This indicates that to trigger a rollback, we have to use `node.update!(vid: revision.vid)` -- https://medium.com/@kristenrogers.kr75/rails-transactions-the-complete-guide-7b5c00c604fc

**Comment by jywarren** [comment]
Example:

```
def transfer_money(amount)
 
  ActiveRecord::Base.transaction do
    john.update!(money: john.money + amount)
    ted.update!(money: ted.money - amount)
  end
 
rescue ActiveRecord::RecordInvalid
  puts "Oops. We tried to do an invalid operation!"
end
```

**Comment by jywarren** [comment]
So we could do:

```ruby
rescue ActiveRecord::RecordNotUnique
```

**Comment by jywarren** [comment]
Or just explicitly `raise ActiveRecord::Rollback if condition`

**Comment by jywarren** [comment]
Maybe

```ruby
raise ActiveRecord::Rollback if node.vid == 0
```

**Comment by jywarren** [comment]
This is super hard to test for, though. We could write a test to try to introduce a bad revision maybe...

**Comment by jywarren** [comment]
OK, theory - it happens when we have an emoji or unicode character in a revision!

**Comment by jywarren** [comment]
Updated #7173 to test that out. Then #7172 may fix it.

**Comment by jywarren** [comment]
Very funny, but if https://github.com/publiclab/plots2/pull/7173 correctly fails, then we may have a way to test for #3007... a hall-of-fame issue....

**Comment by jywarren** [comment]
So, we have a rollback now and it should work, solving the issue. But the underlying cause is the unicode issue at #3007!

**Comment by jywarren** [comment]
Seeing this open again at https://sentry.io/share/issue/2709eb2c658f48739bf30e2699c95136/, linked to emoji/unicode issue!

**Comment by jywarren** [comment]
Closing as we've solved emoji database issues!
