### ISSUE TITLE
Responsiveness error in home page

### ISSUE THREAD

**Issue by pythongiant** [publiclab/plots2#7064]
![image](https://user-images.githubusercontent.com/13624560/71622195-1efdf680-2bfa-11ea-9b4f-24a736a4481e.png)

### Please describe the problem (or idea)

> What did you expect to see that you didn't?

The Horizontal scroll bar looks ugly and indicates a responsiveness error

### Please show us where to look

https://publiclab.org/ 

### Browser, version, and operating system
Screen res - 1366x768
Browser - Chrome 78

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment]
Thanks. Can you add a fix for this?
We can make it medium gci issue. Thanks

**Comment by SidharthBansal** [comment]
Happy new year

**Comment by pythongiant** [comment]
Sure @SidharthBansal I'll work on this today

**Comment by SidharthBansal** [comment]
Great
