### ISSUE TITLE
Add "Places" (/map) to the navbar

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#7071]
Continued from https://github.com/publiclab/plots2/issues/1621.

@nstjean is doing excellent work in making `/map` route. Let's add `Places` in the plots2 navBar that will be pointing to the new `/map` route. 

Let's add under `community` heading:

<img width="219" alt="Screenshot 2020-01-01 at 2 52 10 PM" src="https://user-images.githubusercontent.com/14952645/71639909-62ae3a00-2ca6-11ea-99b1-c9440d5468be.png">

Thanks!

**Comment by sagarpreet-chadha** [comment]
@jywarren , we have to add this under `Community`, right?

**Comment by jywarren** [comment]
That sounds great. Thanks!!!

**Comment by shipcy** [comment]
I want to take this. Can i?

**Comment by sagarpreet-chadha** [comment]
Yes please go ahead :)

**Comment by sssash18** [comment]
@sagarpreet-chadha  Can I work on it if it's still not done?

**Comment by sagarpreet-chadha** [comment]
Hi @shipcy , are you working on this?

**Comment by shipcy** [comment]
@sagarpreet-chadha Yes, I'm working on this. Actually I'm not ok that's why the work is on hold.
Sorry!

**Comment by sagarpreet-chadha** [comment]
No hurry, take care 😃

**Comment by sssash18** [comment]
@sagarpreet-chadha  Can I do this  if shipcy is not active ?
