### ISSUE TITLE
Rename `answered` to `recently_commented`

### ISSUE THREAD

**Issue by anthony-zhou** [publiclab/plots2#7075]
**Please describe the desired behavior.**
We should consider refactoring the method `answered` to something more accurate, like `recently_commented`, to reflect what the method is actually doing. https://publiclab.org/questions/answered/

**Additional context**

The method named `answered` here is actually getting recently commented questions:
https://github.com/publiclab/plots2/blob/fd5683d47ba235abc38e0e16a0d8675b53a1f289/app/controllers/questions_controller.rb#L94-L107

As seen in this page, with the exception of the index function (showing recently asked questions), the "Recently Commented" tab is the only tab where the url and method name do not match the tab name:
https://github.com/publiclab/plots2/blob/fd5683d47ba235abc38e0e16a0d8675b53a1f289/app/views/questions/index.html.erb#L56-L60

This refactoring may also involve changing the above url from `/questions/answered/` to `/questions/recently-commented`, although I'm not sure how that might affect site navigation or analytics of some kind.

**Comment by priyanka-choubey** [comment]
@anthony-zhou can I work on this?

**Comment by anthony-zhou** [comment]
@priyanka-choubey You're welcome to work on this, but keep in mind that it might not be approved, as this is just a suggested refactoring.
