### ISSUE TITLE
Fix map slider on location modal not updating on zoom

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#7079]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [_form.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/locations/_form.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Just after this code here:

https://github.com/publiclab/plots2/blob/fd5683d47ba235abc38e0e16a0d8675b53a1f289/app/views/locations/_form.html.erb#L108-L110

Right after line 111 add this code:
```
      blurredLocation.map.on('zoomend', function() {
        let zoom = blurredLocation.map.getZoom();
        $('#ex1').slider('setValue', zoom);
      })
```

This will make the slider respond to when the map zooms in and out!

![Peek 2020-01-01 14-48](https://user-images.githubusercontent.com/49460529/71645395-c2581580-2ca5-11ea-8cb8-db60538f0b09.gif)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by DevchamploO** [comment]
Hello. I would like to work on this issue.

**Comment by nstjean** [comment]
@DevchamploO OK go ahead!

**Comment by sssash18** [comment]
Can I take up the issue if it has not been completed ?

**Comment by nstjean** [comment]
@DevchamploO Are you still working on this? Do you need any help?

**Comment by DevchamploO** [comment]
I’m still working on this. I am work at the moment but will shoot for making a pull request this evening.

**Comment by nstjean** [comment]
@DevchamploO Ok, great, thanks! Just wanted to check in! :)

**Comment by DevchamploO** [comment]
I am having trouble running the app on my machine. When I run the passenger start command and navigate to localhost:3000 I receive an error that says ‘home/dev/repos/plots2/app/public/index.html’ is not found (2: no such file or directory) with a 404 error in chrome. It appears that it can not locate the correct path. I’m not sure why this is happening. I am using ubuntu 18.04 (wsl).

**Comment by nstjean** [comment]
I'm not very familiar with install errors, I did a quick search and couldn't find anything that mentions that problem. I'm going to find someone who can help you with that!
In the meantime go through these instructions and make sure you didn't miss a step (because that happened to me when I installed everything!): https://github.com/publiclab/plots2#installation
You can also read through this thread for anything that might help: https://github.com/publiclab/plots2/issues/3840

**Comment by DevchamploO** [comment]
﻿
I have not been able to resolve the issue I have been having. Everytime I try to run the server I get the same or similar error. I don’t think it is an installation error because when I add an index file it works fine. I have tried reinstalling but the issue persists. I think the problem lies somehow with PATH configuration. Since I am not sure when I can get this resolved I think that it is best to reopen the issue for someone else to work on it who is not experiencing these challenges.

**Comment by nstjean** [comment]
@DevchamploO I'm sorry you're having problems! It does sound like a PATH issue. :(

**Comment by nstjean** [comment]
After looking at the code for this page I believe I accidentally already completed this in https://github.com/publiclab/plots2/pull/6957 where I was testing it. Oops!
