### ISSUE TITLE
Remove "Question:" from question editor input title (creates double "Question:" in displayed title in question page)

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#708]
Hi, this is a `first-timers-only issue`. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The Problem
See this question: https://publiclab.org/questions/Anmar/08-19-2016/question-calibration-issues. You see the **Question:**  word shows two times. The first one is present due to as it is explicitly shown in the question page and the next one is in the very title because the user used it in the title. The question editor automatically adds the `Question:` part in the title box and most users just leave it like that and write down the title. So it is better that we drop off that from the editor template and discourage the use of the word in the title as all question pages contain the word at the beginning of the title and specially formatted.

## Solution
The line that auto adds the `Question:` word in the input title is this: https://github.com/publiclab/plots2/blob/master/app/views/editor/post.html.erb#L89. Just remove that word from there.

## Steps to Fix
- [ ] claim this issue with a comment
- [ ] set up a repository locally and make sure that all tests pass
- [ ] start a pull request (see contributing to Public Lab software) but mark it as "in progress"
- [ ] fix the issue following the steps above
- [ ] try the manual test listed above
- [ ] make sure all tests pass with rake test
- [ ] alert someone via either the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by ananyo2012** [comment]
Yeah that can be the case. But probably the reverse. Since the title is upto the user.  User can change it. Better that we don't give the "Question:" word preexisting in the text field.

**Comment by ryzokuken** [comment]
Hey @jywarren! Among other's I'd like to claim this issue as my first one, thus maintaining the sanctity of the `first-timers` tag. (If there's no problem with that)

**Comment by jywarren** [comment]
:-) that would be great, thanks!

**Comment by neeleshn** [comment]
Hey,

I am a first timer too. Can only person claim an issue or many people can claim the same issue at once?

Thanks,
Neel.

**Comment by jywarren** [comment]
Hi! We'd prefer each first timer take a distinct issue -- there ought to be
enough to go around! Thanks!

**Comment by ryzokuken** [comment]
@jywarren I'm having some issues installing the dependencies on cloud9 using `./install_cloud9.sh`.

I'll try setting up the project in my local machine. As this issue just involves removing the block `<%= "Question: " if params[:template] == "question" && @node && @node.title == nil %>` from the file, should I try removing this in the editor and committing the changes? **Warning:** Although I don't think removing this would break the application, I guess we should run the tests anyway. Maybe passing the Travis build tests is enough?

If you're curious, here's the errors it has been throwing:

1. 

```
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/ubuntu/workspace/config/database.yml
/usr/local/rvm/gems/ruby-2.1.2/gems/railties-3.2.22.5/lib/rails/application/configuration.rb:115:in `read'
/usr/local/rvm/gems/ruby-2.1.2/gems/railties-3.2.22.5/lib/rails/application/configuration.rb:115:in `database_configuration'
/usr/local/rvm/gems/ruby-2.1.2/gems/activerecord-3.2.22.5/lib/active_record/railties/databases.rake:25:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create => db:load_config
(See full trace by running task with --trace)
```

This was fixed (to some extent) by re-running `./install_cloud9.sh`, but here's what happened next:

2.

```
Connection refused - {:data=>"<?xml version=\"1.0\" encoding=\"UTF-8\"?><add><doc><field name=\"id\">DrupalUsers 1</field><field name=\"type\">DrupalUsers</field><field name=\"type\">ActiveRecord::Base</field><field name=\"class_name\">DrupalUsers</field><field name=\"name_s\">ryzokuken</field><field name=\"mail_s\">usharma1998@gmail.com</field><field name=\"status_s\">1</field></doc></add>", :headers=>{"Content-Type"=>"text/xml"}, :method=>:post, :params=>{:wt=>:ruby}, :query=>"wt=ruby", :path=>"update", :uri=>#<URI::HTTP:0x007fcec427ec60 URL:http://localhost:8982/solr/development/update?wt=ruby>, :open_timeout=>nil, :read_timeout=>nil, :retry_503=>nil, :retry_after_limit=>nil}
```

**Comment by ryzokuken** [comment]
Apparently, I cannot connect to the Drupal users database. The problem is in `drupal_user.save!` in `/app/models/user.rb`.

**Comment by ananyo2012** [comment]
Ah ok this is a solr related issue since. We haven't still added the steps in the readme for the cloud9 installation. Please follow the [installation steps](https://github.com/publiclab/plots2#installation). Follow the steps 8,9,10 before start the server and that should start the server successfully.

**Comment by jywarren** [comment]
yes -- apologies -- we're working on the Solr install steps for Cloud9 (thanks to Ananyo!) and will have better instructions there soon. 

@neeleshn -- if you'd like to pick up another, there should be a number of issues available at https://github.com/publiclab/plots2/labels/first-timers-only -- I'd be happy to help you choose one! Thanks!

**Comment by jywarren** [comment]
Also -- if you've made the changes you think should work, and you want to try running the tests to see if everything still runs fine, you can submit your changes in a pull request with "IN PROGRESS" in the title -- and our TravisCI service will run all the tests and show you the output. I know this is not /quite/ as good, but if it's a simple change, it's fine with us! 

You can learn more about opening a PR based on your feature branch here: https://publiclab.org/wiki/contributing-to-public-lab-software

Thanks!

**Comment by ryzokuken** [comment]
@jywarren @ananyo2012 `passenger start` runs the server on port 3000 while c9 expects apps to run on port 8080. Is there some way I could specify it to use 8080?

**Comment by jywarren** [comment]
Hmm, well you can say `passenger start -p 8080` -- but I don't remember
that being necessary!

**Comment by ananyo2012** [comment]
@ryzokuken Yes the command for starting server in cloud9 is `rails s -b $IP -p $PORT`

**Comment by ebarry** [comment]
Hi @ryzokuken! Thank you again for your valuable contribution to Public Lab. I would like to invite you to join us in a video conference to say a few words about what you contributed and how your experience was. The event is https://publiclab.org/openhour, and it’s coming right up on November 7th, at 1pm EDT which is UTC/GMT -4. 

Please feel free to respond here, or else email liz@publiclab.org, stevie@publiclab.org, jeff@publiclab.org.

**Comment by ryzokuken** [comment]
Hey @ebarry! Firstly, thanks for the invitation. However, I'd like to mention that I'm just a kid wanting to contribute to the project. Also, 1:00 PM EDT is 10:30 PM in my timezone and I'd most probably be having school the next day, so I don't really know if I'd be able to attend this.

**Comment by ebarry** [comment]
Hi @ryzokuken, there are no age limits on being awesome!
If it works for your schedule considering school the next day, and if it works for your family, you are most welcome to join us. Feel free to have a family member get in touch with me directly with any questions -- liz@publiclab.org

**Comment by ryzokuken** [comment]
Thanks @ebarry, I'll try my best.
