### ISSUE TITLE
Add prompt to Dashboard (/dashboard) to add user location

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#7084]
If a user doesn't have a location they should be prompted on the /dashboard to enter one.

Should it be in the main column, something like this?

![FireShot Capture 161 - 🎈 Public Lab_ Dashboard - localhost](https://user-images.githubusercontent.com/49460529/71678624-9abf8680-2d53-11ea-8aa4-1c5eed2a6924.png)

Or in the sidebar?

![FireShot Capture 162 - 🎈 Public Lab_ Dashboard - localhost](https://user-images.githubusercontent.com/49460529/71678912-4668d680-2d54-11ea-9a4a-2ec9060991f5.png)

If it's in the main column we could add some descriptive text to the box. If it's in the sidebar it matches with the pages and notes, but will be more easily overlooked.

**Comment by jywarren** [comment]
Let's do sidebar! We will also have to be sure this gets reflected in the new dashboard project, which is currently a bit stalled #6229 #6072 

Thanks!

**Comment by nstjean** [comment]
Ahh, perfect! Ok!

**Comment by sagarpreet-chadha** [comment]
🎉

**Comment by sssash18** [comment]
@jywarren @nstjean Can i work on this?

**Comment by sssash18** [comment]
@jywarren @nstjean Can I work on this?

**Comment by nstjean** [comment]
Using the wording from #6072 this is what it looks like:

![FireShot Capture 205 - 🎈 Public Lab_ Dashboard - localhost](https://user-images.githubusercontent.com/49460529/72265461-8c425c00-35ea-11ea-919f-0f8e28cb47c1.png)


Should we add the line break in a different spot?

![FireShot Capture 206 - 🎈 Public Lab_ Dashboard - localhost](https://user-images.githubusercontent.com/49460529/72265471-906e7980-35ea-11ea-83c3-7f752d9ea7a8.png)

**Comment by sagarpreet-chadha** [comment]
Yes "About location privacy" in next line makes sense. Thanks!

**Comment by nstjean** [comment]
Reposted as a FTO! https://github.com/publiclab/plots2/issues/7263
