### ISSUE TITLE
Menu Icon on Medium-sized Screens not Vertically Aligned

### ISSUE THREAD

**Issue by anthony-zhou** [publiclab/plots2#7095]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

As you can see, the menu icon (top right) is not vertically aligned on medium sized screens: 
![image](https://user-images.githubusercontent.com/37421108/71705215-219c4f80-2da4-11ea-9baf-2885eda2d370.png)

On line 103 of app/assets/stylesheets/style.css, https://github.com/publiclab/plots2/blob/f46faa6c8c97bd683cf355f4854fc226ca4b22eb/app/assets/stylesheets/style.css#L103
add a CSS rule as follows:
```
.fa-bars {
  vertical-align: middle;
}
```

Note: this is similar to the vertical-align changes mentioned in issue #7092, but is applied instead to the menu icon. Perhaps there could be a more general solution for vertically aligning all the icons on this site.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by gxite** [comment]
Hi i'd like to claim this issue.

**Comment by mbronek7** [comment]
Hi I would like to start contributing to open source, could you check My PR

**Comment by shipcy** [comment]
I would like to solve this issue.

**Comment by sunguru98** [comment]
May I take this issue please if someone hasnt still completed it yet?

**Comment by sssash18** [comment]
May I take up this issue if it has not been assigned?
Actually, I am new to this community
