### ISSUE TITLE
Profile Pages

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#71]
Is it possible to have a place for on people's profiles to upload their picture? Maybe similar to the drag and drop tool we have on research notes.

**Comment by jywarren** [comment]
Hi, Stevie - Is it reasonable to merge this into #104? I'm trying to consolidate and organize these issues for contributors (esp GSOC students) to get going on, and if this is similar enough could you please add the relevant info to #104 and close this issue? Thanks.

**Comment by ebarry** [comment]
Hey @steviepubliclab , i moved some of what i saw as the key insights from here onto https://github.com/publiclab/plots2/issues/104. Check it out and see if we can close this issue.

**Comment by jywarren** [comment]
Hi, @steviepubliclab - I'm closing this issue as it's been left unresolved for a while and it seems that Liz has merged with #104. But if you'd like to re-open, let's work to refine the name and scope of work and that's fine.
