### ISSUE TITLE
Question & Answer comment box width issue

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#710]
### What happened just before the problem occurred

On https://publiclab.org/questions/Anmar/08-19-2016/question-calibration-issues the comment box is pretty narrow, and I wonder if the `media` CSS selector is working properly? I'm on latest Chrome (on a Chromebook):

![screenshot 2016-08-20 at 10 28 06 am](https://cloud.githubusercontent.com/assets/24359/17831788/f6371d0a-66c0-11e6-9553-5c3b97091fa2.png)

Not super urgent, but if @ananyo2012 and/or @carolineh101 could take a look, that would be great. Thanks!

**Comment by ananyo2012** [comment]
Ok I am not facing this but will have a look.
ᐧ

**Comment by ananyo2012** [comment]
But I am facing it here:
https://publiclab.org/questions/shubham/08-18-2016/question-can-i-upload-csv-files-on-spectralworkbench-for-calibration-and-other-purposes.
Weird!
ᐧ

**Comment by jywarren** [comment]
Maybe worth trying in incognito vs. plain modes?

**Comment by ananyo2012** [comment]
Fixes in #713
