### ISSUE TITLE
Add Text To Body In Contact Moderators "mailto:" Link

### ISSUE THREAD

**Issue by skilfullycurled** [publiclab/plots2#7109]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

This issue stems from #6962 (a related FTO!).  We want to reduce the ammont of back and forth email communication when a user contacts us because they believe they have been mistakenly banned.  Currently, moderators can only find a banned user via their user name.  #6962 adds the ability to find them using their email address.  

However, finding a banned user by email address is taxing on the server for reasons described in #6962.  Therefore, in an effort to avoid having to use that, we are adding text to the mailto link to automatically populate the email with text in the body that requests the username and email address.

You can read more about the mailto link [here](https://www.rapidtables.com/web/html/mailto.html) and play around with the different parameters [here](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_mailto).

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [/app/controllers/application_controller.rb](https://github.com/publiclab/plots2/app/controllers/application_controller.rb) in the [plots2](https://github.com/publiclab/plots2) repository (press the little pen Icon) and edit the line as shown below.

https://github.com/publiclab/plots2/blob/964be1f16ae2546efa47fab5ffcc0eceb679c993/app/controllers/application_controller.rb#L88

Please add the following:

`?body=Please make sure to include your username and the email address you used to sign up for the site.`

Like so:

`...and contact <a href='mailto:moderators@#{request.host}?body=Please make sure to include your username and the email address you used to sign up for the site.'>moderators@#{request.host}</a> if you believe this is in error."`

The final result should look like this:
```
flash[:warning] = "The user '#{@current_user.username}' has been placed in moderation; please see <a href='https://#{request.host}/wiki/moderators'>our moderation policy</a> and contact <a href='mailto:moderators@#{request.host}?body=Please make sure to include your username and the email address you used to sign up for the site.'>moderators@#{request.host}</a> if you believe this is in error." 
```

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by sunguru98** [comment]
I want to take this, please. It seems easy for me and will add experience to my OSC belt :), I don't know the etiquette even for claiming haha.

**Comment by skilfullycurled** [comment]
Thanks @sunguru98, that was quick!

As far as claiming goes, I'd say, if you see a comment thread, then just ask if anyone already has it.  If it's completely empty, I think it's safe to just claim it.  No justification necessary, it's just so people don't double up.

**Comment by shipcy** [comment]
I want to take this issue. Please let me know if I'm allowed to take this issue.

**Comment by skilfullycurled** [comment]
Hi Shipra,

I think someone already completed this (responding from my phone so I can’t see the site right now).

If you look in the narrative up top, there’s a related issue.  It’s slightly more complicated, but not by much.  I haven’t set it up as an FTO yet, it’s still an FTO candidate.  All I need to do is take all of the decisions and group them into a step by step up top. 

But you can go ahead and claim it if you want, and I’ll go work on it.  I can finish it the next hour, probably before.  And if you add a message, you’ll be subscribed and I can let you know when it’s ready...? 

If, after I finish, you decide you don’t want to do it or you find a different one, then just leave a note saying you’ll find/have found a different one.

**Comment by skilfullycurled** [comment]
@sunguru98, now that you've completed the task, don't forget to click all of the check boxes up to.  One of them will be for making a pull request, which you should do if you haven't yet done so.  I think the people who approve them look for all of the boxes to be ticked off.

**Comment by skilfullycurled** [comment]
@shipcy, the related one is #6962.  I'm going to go fix it up right now.

**Comment by skilfullycurled** [comment]
Okay @shipcy, #6962 is all set for the taking (if you want it, that is).  If, for whatever reason, you're uninterested, just leave a note there so someone else knows it's claimable again.

**Comment by shipcy** [comment]
@skilfullycurled Sir, I really don't know how to do this. If you may guide me then I'll take this issue otherwise I'll leave this issue and look for another one.
Thanks!

**Comment by skilfullycurled** [comment]
No "sirs" necessary, Benjamin will be fine.  ; )

We are absolutely here to guide you!  The process is no different than this one.  If you think you can do this one, I'm confident with some help you can do the other one, if you're interested.  Let's move the conversation over to #6962, because everyone on the thread can help out.  I'm going to ask you a question over there.

**Comment by shipcy** [comment]
@skilfullycurled yeah, sure!

**Comment by skilfullycurled** [comment]
Oh, as an aside @shipcy, I didn't know anything about contributing to another repo when I started, so don't worry about that!  Everyone is here to help no matter your experience, and even _after_ you complete an FTO.

**Comment by shipcy** [comment]
@skilfullycurled Thank you so much!

**Comment by shipcy** [comment]
@skilfullycurled and you were talking about some question above. What's the question then?

**Comment by skilfullycurled** [comment]
Yes, click on this [link](https://github.com/publiclab/plots2/issues/6962#issuecomment-571205632).  I moved the conversation to the issue that I'm taking about.

**Comment by sunguru98** [comment]
I completed the solution and even tries to PR it, but it gives me some Codeclimate error, dont know what that is about. I went and changed the tests and then tried again. No use. Please help me @skilfullycurled

**Comment by skilfullycurled** [comment]
First, you’re going a great job figuring everything out!

My code climate didn’t (and still don’t always) pass, it’s super frustrating.  This is very normal.  You’re doing all the right things.

And, you’ll have a chance to learn how to debug with code climate.  Like I said, this won’t be the last time you’ll be in this position.

Another benefit is that code climate tests do not fail for code that is technically correct, but doesn’t do what you want, so it forces you to look it over.

I’ll take a look as soon as I can.  If we can’t figure it out, we’ll call in a few senior members, which will be good so you can get to know them.

Again, you’re doing great without a lot of help, so I hope you’re feeling good about that.

**Comment by jywarren** [comment]
🎉

**Comment by sunguru98** [comment]
Holy mangoesss ... Did I just push in the code amongst a huge community ??????????

**Comment by jywarren** [comment]
You sure did 😂 congrats! It should go live at https://stable.publiclab.org shortly, and to the production site https://publiclab.org during the coming week!

🚀 🎸 🙌

**Comment by jywarren** [comment]
You are also featured now on https://code.publiclab.org/ as a contributor! ❤️ 

![image](https://user-images.githubusercontent.com/24359/71920207-46057c80-3154-11ea-864b-9cc0226960bf.png)

**Comment by sunguru98** [comment]
I am just speech less now ... Thank you sooo much for accepting this.. It literally means the world to me.

**Comment by skilfullycurled** [comment]
Great job @sunguru98, I know the feeling! We’ll have to figure out a way to 

Bringing in at @ebarry and @bronwen9.

Between this and @shipcy’s work (also just merged! 🎉) the back and forth for collecting info from the person contacting the moderators will be reduced, hopefully to none!

@sunguru98, if you want to try out the feature, make an account on publiclab.org (if you haven’t already).  Let me know here, and I’ll ban you so the next time you log in, you can use the feature to email the moderators we’ll unban you.  : )

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by skilfullycurled** [comment]
Oh, @sunguru98, also, let me know your username after you make the account.

**Comment by sunguru98** [comment]
Definitely. Pretty much the same name would be. @sunguru98  lol @skilfullycurled.
