### ISSUE TITLE
Login prompt on Question comment area does not redirect back after login

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#711]
Hi, this is a `first-timers-only issue`. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!
## The Problem

Visit a research note or question like: https://publiclab.org/questions/Anmar/08-19-2016/question-calibration-issues while not logged in, then click "Log in" to comment in the comment section to login. But then you will be redirected to the dashboard, instead of back to the original post. It'd be great to have a `return_to` param as on other login prompts, which is just adding `?return_to=/path` to the end of the link, which is then read here: https://github.com/publiclab/plots2/blob/master/app/views/user_sessions/new.html.erb#L24
## Solution

There are many areas where similar Login links are present like the notes page, question page and the Answers section in questions page. These are all the relevant areas
- https://github.com/publiclab/plots2/blob/master/app/views/notes/show.html.erb#L109
-  https://github.com/publiclab/plots2/blob/master/app/views/notes/_comments.html.erb#L19
- https://github.com/publiclab/plots2/blob/master/app/views/questions/show.html.erb#L61
- https://github.com/publiclab/plots2/blob/master/app/views/questions/_answers.html.erb#L13
- https://github.com/publiclab/plots2/blob/master/app/views/questions/_answer.html.erb#L58

Everywhere a `?return_to=` parameter is needed beside the login url which should be set to `request .path` for redirecting to the current page.
## Steps to Fix
- [x] claim this issue with a comment
- [ ] set up a repository locally and make sure that all tests pass
- [ ] start a pull request (see contributing to Public Lab software) but mark it as "in progress"
- [ ] fix the issue following the steps above
- [ ] try the manual test listed above
- [ ] make sure all tests pass with rake test
- [ ] alert someone via either the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by ananyo2012** [comment]
Yes this is a simple fix. I will make it a first-timer issue.

**Comment by Squawk09** [comment]
Hello, 

I just started working in Ruby and have been looking for an open source project to contribute to.  Could you please mark this issue as in-progress.  I believe I can handle this issue.  Thanks for making a project that seems very open and friendly to new contributors!

**Comment by jywarren** [comment]
Very glad to hear it! Welcome! I've marked it as `in-progress`. 

I'm curious (we're trying to improve on reaching out to first time contributors) -- how did you hear about our project?

**Comment by Squawk09** [comment]
I saw it on up-for-grabs.net.

**Comment by Squawk09** [comment]
When I launch the project in cloud9 and go to create an account after pressing the log in button, it throws an error.  Do you know a way around this? I just want to quickly test my solution.  

Thanks!

**Comment by jywarren** [comment]
Ah - i believe we haven't completed the update of the Cloud9 installation
steps following the recent Solr upgrade -- it's on our priority list,
however: https://github.com/publiclab/plots2/issues/832

In the meantime, you can actually just open a pull request marked with
"(testing)" before the title, and it'll run your changes on our TravisCI
service, and show you the output. That will run the tests.

However, if you want to manually test it out, you'll need to look at the
more complete install instructions, including the Solr installation:
https://github.com/publiclab/plots2/#search

and the remaining steps to start that service up:
https://github.com/publiclab/plots2/#installation

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? I believe we've fixed the cloud9 install process, so hopefully that's no longer a problem.

Thanks!

**Comment by ebarry** [comment]
HI @Squawk09, thank you for reaching out to Public Lab! I would like to invite you to join us in a video conference to say a few words about what you found engaging about the Public Lab community and/or this particular github issue. The event is https://publiclab.org/openhour, and it’s coming right up on November 7th, at 1pm EDT which is UTC/GMT -4. 

Please feel free to respond here, or else email liz@publiclab.org, stevie@publiclab.org, jeff@publiclab.org.

**Comment by dixonscottr** [comment]
Hi, @jdollete, @mr-jungchoi and I will be working on this tonight

**Comment by jywarren** [comment]
Also, just wanted to say we've just fixed/updated our cloud9 install script, so if you were seeing an error, it shouldn't happen now (just tested this myself). Thanks and apologies for the install issue!

**Comment by Squawk09** [comment]
Hi, 

Yes I got distracted with work. I plan on pushing a commit for this bug over the weekend. 

THanks!

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by mridulnagpal** [comment]
I would like to work on this issue

**Comment by jywarren** [comment]
Hi, @mridulnagpal - it sounds like @Squawk09 could be stuck on this, so perhaps you could take it on if they're not ready to submit a fix. But it also looks like you've found some other issues to work on, so @Squawk09, feel free to take a bit longer on this and I'm happy to help.

**Comment by ananyo2012** [comment]
@Squawk09 Just checking were you able to setup the repository locally or in Cloud9?

**Comment by ananyo2012** [comment]
@petersowah Yes go ahead with it. Since @Squawk09 hasn't still replied you can take up this isssue now. You can contact us in our gitter channel if you need any  help.

**Comment by petersowah** [comment]
@ananyo2012 I sent in a PR

**Comment by ananyo2012** [comment]
Yeah just checking it

**Comment by jywarren** [comment]
Solved by @petersowah in #1158! Thank you! 🎉
