### ISSUE TITLE
Logging in through MK AND SWB should not redirect to Publiclab

### ISSUE THREAD

**Issue by Uzay-G** [publiclab/plots2#7121]
The authentication system for Mapknitter, Publiclab and Spectral Workbench are quite intertwined and I noticed that logging it to Mapknitter through oauth (at least Github) redirected to the publiclab dashboard instead of back to Mapknitter. Here's a video with the problem:

![redirection-problem](https://user-images.githubusercontent.com/52892257/71836975-97aafa00-30b5-11ea-9890-c578f45485d6.gif)

Is there a way we could implement a redirect to the website we are currently on instead and do you find this useful? I would love to help! :+1:

**Comment by VladimirMikulic** [comment]
I've thought of this issue too. It's annoying when you get redirected every time when you log in via Google/Github...

**Comment by Uzay-G** [comment]
Yeah I totally agree.

**Comment by jywarren** [comment]
Oh huh... let's cc @SidharthBansal because he created this system. I wonder
does this happen only for Google/GitHub or for Twitter/FB too?

**Comment by SidharthBansal** [comment]
Hi @Uzay-G I was referring to the same thing yesterday in your pr. We need a test to ensure correct behavior for MK and SWB(no redirect back to PL). Can you please add tests demonstrating it also?

**Comment by SidharthBansal** [comment]
@jywarren there were some changes in May-July in plots2 due to which all 4 providers are redirecting back to MK and SWB. We are trying to rectify this on `priority`. I really appreciate your patience.

**Comment by SidharthBansal** [comment]
@Uzay-G and I am solving it. I hope we will finish this milestone this week.

**Comment by jywarren** [comment]
Thank you very much!!!

**Comment by SidharthBansal** [comment]
I think this will be solved after #3367

**Comment by SidharthBansal** [comment]
@Uzay-G please provide tests for MK and SWB

**Comment by SidharthBansal** [comment]
If this issue still requires changes then please provide changes too

**Comment by Uzay-G** [comment]
> @Uzay-G please provide tests for MK and SWB

@SidharthBansal could you help me with this? I don't think it's possible to test logging in through Publiclab from MK or SWB

**Comment by SidharthBansal** [comment]
This will help you

https://github.com/publiclab/plots2/blob/d06f59460edf0424a6edbfc4000ac8444145fc5d/test/integration/openid_test.rb

**Comment by SidharthBansal** [comment]
Let's focus on completing login milestone asap. So, that we can start working on other projects like comments, stats too together

**Comment by SidharthBansal** [comment]
You can take as much time as you want. Don't need to take tension.

**Comment by Uzay-G** [comment]
Hey! I checked out the file and I was wondering what type of tests you wanted me to add. Do you want me to add tests for trying to log in with banned users and things like that?

**Comment by SidharthBansal** [comment]
User at Mk in not logged in state.
User clicks Github Provider.
Github is logged in
Pl is logged in
MK is logged in
User is logged into MK
User is on mk.org

Similarly for all provider, similarly for both signup and login and for
both swb and mk.
Does this make sense?

**Comment by Uzay-G** [comment]
Yeah it does. I am looking at the example you sent and will try and code some tests :+1:

**Comment by SidharthBansal** [comment]
There will be many tests.
Please ensure no duplicate tests

**Comment by Uzay-G** [comment]
Hey! Don't some of these tests: https://github.com/publiclab/plots2/blob/d06f59460edf0424a6edbfc4000ac8444145fc5d/test/integration/openid_test.rb already do authentication requests from MK or SWB?

**Comment by SidharthBansal** [comment]
yes we already have some tests. we need to write remaining tests if any

**Comment by Uzay-G** [comment]
All of the tests in the file are only for SWB, should I replicate them for MK?

**Comment by SidharthBansal** [comment]
There should be tests for mk too

**Comment by Uzay-G** [comment]
The tests are quite confusing... I have done the missing tests for MK based on what already existed for SWB but I am not sure what I can add and how I can test through the open_id. What other tests should I add to the files?

**Comment by SidharthBansal** [comment]
Let's first merge a pr so that equal number of tests are present for mk and
swb. Then we can think forward.

**Comment by Uzay-G** [comment]
Alright I will open the pull request :+1:

**Comment by SidharthBansal** [comment]
Now we can continue with other tests

**Comment by Uzay-G** [comment]
What type of tests would you like me to add?

**Comment by SidharthBansal** [comment]
Login to mk by logging into GitHub at public lab. Redirected back to mk.

**Comment by Uzay-G** [comment]
Doesn't this one solve that:
https://github.com/publiclab/plots2/blob/299a6f47832a42a7f67dcbea5e2c7f8d41883aac/test/integration/openid_test.rb#L338-L391

Maybe I am wrong. What do you think?

**Comment by SidharthBansal** [comment]
Please abandon the current task. I think we can go to the system tests now

**Comment by SidharthBansal** [comment]
Sorry I can't give points for this as it was already solved

**Comment by Uzay-G** [comment]
Yeah no problem :+1:
