### ISSUE TITLE
Wiki "Preview" state does not show a way to go back to editing

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#7122]
I noticed today that when you edit a Wiki page it has the options of "Save" "Preview" and "Cancel." When you click on "Preview" the page displays as a preview just as it should, but there is no button that says "Edit" or shows how you can return back to editing.

![FireShot Capture 171 - 🎈 Public Lab_ Editing 'Power Tags' - publiclab org](https://user-images.githubusercontent.com/49460529/71837511-957c7780-3084-11ea-9c18-f2001df7e5d3.png)

I learned from trial and error that pushing the "Preview" button again brings me back to the Edit mode. The text on the button should change to reflect this change in function. When you press the "Preview" button to show the preview the text should change to "Edit" so you know to push that button to go back.

**Comment by jywarren** [comment]
That'd be great. Thanks!

**Comment by Tlazypanda** [comment]
@jywarren is this issue still available?

**Comment by Tlazypanda** [comment]
@nstjean can I take this up?

**Comment by nstjean** [comment]
@Tlazypanda It looks like we had a working fix submitted for this, we should probably check why it wasn't merged!

**Comment by imajit** [comment]
@jywarren @nstjean can I work on this?
