### ISSUE TITLE
Public Lab Website x-overflow fix

### ISSUE THREAD

**Issue by LeoDog896** [publiclab/plots2#7127]
> What did you expect to see that you didn't?

Well, more as what did I expect to not see, a x-scroll bar

### Please show us where to look

https://publiclab.org/

I'm not signed in and this styling appears automatically

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!
I'm not signed in, and I'm using a Windows 10 with a Chrome browser version 79.0.3945.88

****
![Capture](https://user-images.githubusercontent.com/26509014/71854972-bc02d880-30ad-11ea-8488-4af0f2307142.PNG)

**Comment by NitinBhasneria** [comment]
@LeoDog896  I would like to take this issue

**Comment by keshavsethi** [comment]
Someone Please review this

**Comment by NitinBhasneria** [comment]
@jywarren @SidharthBansal This is not a valid issue need to be closed.

**Comment by SidharthBansal** [comment]
Why this needs to be closed?

**Comment by NitinBhasneria** [comment]
because fixes of this issue has already been merged. @SidharthBansal

**Comment by debck** [comment]
Yes it was fixed here https://github.com/publiclab/plots2/pull/7102

**Comment by SidharthBansal** [comment]
Can we close this now?
Thanks all

**Comment by NitinBhasneria** [comment]
Yes @SidharthBansal
