### ISSUE TITLE
Show author name on /comments listing

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#7134]
The comments page listing is a little bare and could use some design cleanup. First of all, i can't see who wrote each comment! Let's add an author name (should be `comment.author.username` i think?) so this is more legible:

https://publiclab.org/comments

And, we can link the authorname to their profile, like: https://publiclab.org/profile/stevie

We'd love help with this! 

The page template is here:

https://github.com/publiclab/plots2/blob/master/app/views/comments/_comments.html.erb

**Comment by sunguru98** [comment]
I just noticed one thing which was weird, The first photo which I have attached has just the ID named "C", but in code when I saw, you were trying to embed the letter C along with the Comment Id name which is in the second image. So, is it a bug or should that be left alone haha?
<img width="232" alt="Screenshot 2020-01-08 at 12 30 09 AM" src="https://user-images.githubusercontent.com/32637757/71921198-68c47f00-31ae-11ea-9648-0dd61191f6f5.png">
<img width="197" alt="Screenshot 2020-01-08 at 12 31 43 AM" src="https://user-images.githubusercontent.com/32637757/71921200-68c47f00-31ae-11ea-98d0-0f99e316cc62.png">

**Comment by sunguru98** [comment]
And for the solution itself, I am having this idea of creating a basic element dry-run and showing the result to you. The first image is code which I had lab ratted it, and the second is the output shown on screen.
<img width="457" alt="Screenshot 2020-01-08 at 12 37 40 AM" src="https://user-images.githubusercontent.com/32637757/71921660-4aab4e80-31af-11ea-9edf-1df1582f4ca5.png">
<img width="729" alt="Screenshot 2020-01-08 at 12 37 48 AM" src="https://user-images.githubusercontent.com/32637757/71921664-4b43e500-31af-11ea-8324-c73dbe2aa03b.png">

In the place of Hello World, You will be seeing the Author name perfectly linking to his/her profile page.

**Comment by jywarren** [comment]
I think this can work, thanks - but what about a bit more compact, by
making author one column of the table? Thanks a lot for your help!

**Comment by sunguru98** [comment]
You mean the author and the comment should come side by side, like the image pasted below @jywarren?

<img width="754" alt="Screenshot 2020-01-08 at 12 50 34 AM" src="https://user-images.githubusercontent.com/32637757/71922475-facd8700-31b0-11ea-8386-63bcc6e78e12.png">

**Comment by jywarren** [comment]
Yeah, that would be great!!

**Comment by sunguru98** [comment]
Alright I will start working on it. BTW how to run this on my local computer? As I haven't been in the Ruby background before haha.

**Comment by nstjean** [comment]
Hi @sunguru98 ! Here's documentation on how to install `plots2` onto your computer and get it running: https://github.com/publiclab/plots2#installation Let us know if you run into issues!

**Comment by keshavsethi** [comment]
I have made a PR for this issue. Please review this.

**Comment by sunguru98** [comment]
@keshavsethi You could clearly see that there is a conversation going on here .. Moving forward without even asking a permission is not a part of an Open source etiquette. You should have asked permission on taking it first. @jywarren What do you say?

**Comment by keshavsethi** [comment]
Sorry for this, I will remember this in future.

**Comment by sunguru98** [comment]
As you have done this time .. Lets wait for @jywarren to review your code and get it merged. But this is an unpleasant way please do refrain it in further PRs.
