### ISSUE TITLE
Run-on Sentence

### ISSUE THREAD

**Issue by winstoniskandar** [publiclab/plots2#7138]
**Please describe the desired behavior.**
Right now on https://publiclab.org/wiki/projects, there is a run-on sentence underneath "who should post a project page." 
Describe the solution you'd like.
The sentence right now is "If you're posting about a concern for the first time, you can use the Issue Brief template, if you're posting about a specific question you have, you can post it to Public Lab's Q+A." Instead, the sentence should be "If you're posting about a concern for the first time, you can use the Issue Brief template. Or if you're posting about a specific question you have, you can post it to Public Lab's Q+A."

**Additional context (optional)**
Feel free to include any applicable: code, screenshots, or gifs.

**Comment by jywarren** [comment]
Hi @winstoniskandar - sorry for the slow reply -- that's actually a wiki page, so if you'd like you can make the change yourself! Thanks a lot for catching that - would you like to? If so please feel free to re-open this issue. Thanks again! 🎉
