### ISSUE TITLE
New Feature/suggestion for GCI

### ISSUE THREAD

**Issue by rajat-png** [publiclab/plots2#7145]
In this global contest (that is GCI) have not grading system, only get inform to candidate how many task complete which candidate not have idea that they go to winner/runner up/finalist. So I suggest a new feature/idea that Grading system for student cotributing work.
I hope this is helpful for all GCI candidate.

**Comment by SidharthBansal** [comment]
Please check https://github.com/publiclab/plots2/issues/6808
