### ISSUE TITLE
Top map only shows for tag "place" and not power tag "place:xx"

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#7148]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [_related.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/sidebar/_related.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Right now if you input the tag `place` the map shows properly as a map across the top of the page instead of in the sidebar.

![FireShot Capture 187 - 🎈 Public Lab_ This is a post testing location - localhost](https://user-images.githubusercontent.com/49460529/71992805-026a4b80-3204-11ea-8f56-d332cd364fbc.png)

But if you input the power tag `place:xx` then it isn't showing properly.

![FireShot Capture 186 - 🎈 Public Lab_ This is a post testing location - localhost](https://user-images.githubusercontent.com/49460529/71992975-537a3f80-3204-11ea-95ae-cb3d9b1f9dfc.png)

So let's cover our bases by checking both of those options. On this line here:
https://github.com/publiclab/plots2/blob/2365caabd15e4b7fa178e94e25b0bf4dd9b67f84/app/views/sidebar/_related.html.erb#L44

Change it to:
`<% if @node && (@node.has_tag("place") || @node.has_power_tag("place")) && @node.lat && @node.lon %>`

Now it works properly!

![FireShot Capture 188 - 🎈 Public Lab_ This is a post testing location - localhost](https://user-images.githubusercontent.com/49460529/71993146-9a683500-3204-11ea-9244-468485874dc2.png)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by nstjean** [comment]
@jywarren Should this check for the tag `place` at all? Or only the power tag?

**Comment by llabake** [comment]
Hi, I would like to claim this.

**Comment by nstjean** [comment]
@llabake Great, go ahead!

**Comment by nstjean** [comment]
@llabake I see that you also have https://github.com/publiclab/leaflet-environmental-layers/issues/333 so go ahead and do that one in Leaflet Environmental Layers. I'll have someone else do this one. :)

@sunguru98 You can have this one!

**Comment by sssash18** [comment]
Can I take up this issue?

**Comment by nstjean** [comment]
@sssash18 This issue has already been claimed, but I know there is one available in Leaflet Environmental Layers: https://github.com/publiclab/leaflet-environmental-layers/issues/322

**Comment by sunguru98** [comment]
Yayyyyy .. I will do it right away.

**Comment by nstjean** [comment]
Great! Thank you for your patience. :smiley:

**Comment by sunguru98** [comment]
@nstjean Done :)
