### ISSUE TITLE
Wiki page with place:xx tag shows two maps

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#7149]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [wiki/_header.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/wiki/_header.html.erb) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

A wiki with a `place:xx` tag is showing both the top map and a (broken) map in the main column.

![FireShot Capture 193 - 🎈 Public Lab_ Stats - localhost](https://user-images.githubusercontent.com/49460529/71997324-af949200-320b-11ea-88e4-8b7ca312f8f1.png)

That's not what it should be doing! It should show the same as when `place` is entered:

![FireShot Capture 192 - 🎈 Public Lab_ Stats - localhost](https://user-images.githubusercontent.com/49460529/71996549-6b54c200-320a-11ea-8a91-479bc652c382.png)

In this file remove these lines 45-47:
https://github.com/publiclab/plots2/blob/6fa24e3296505cb5d7a72e518ca22bf96899b345/app/views/wiki/_header.html.erb#L45-L47

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by nstjean** [comment]
Forgot to tag you, @jywarren 

I can make this into a FTO once I know what it should do. :)

**Comment by nstjean** [comment]
Oh wait, I see, it's the same problem as the other one... it works for `place` but not for `place:xx`. I'll edit the original post to make the change!

![FireShot Capture 192 - 🎈 Public Lab_ Stats - localhost](https://user-images.githubusercontent.com/49460529/71996324-013c1d00-320a-11ea-882e-e23f803a691f.png)

**Comment by Bhanu-mbvg** [comment]
Can I take this up? @nstjean

**Comment by sunguru98** [comment]
May I take it here? @jywarren

**Comment by nstjean** [comment]
@Bhanu-mbvg Go ahead!

@sunguru98 Here's one for you: https://github.com/publiclab/plots2/issues/7148

**Comment by jywarren** [comment]
Ah! Noting relation to this disambiguation needed in this issue: https://github.com/publiclab/plots2/issues/6953

Thanks!!!

**Comment by 9916103020** [comment]
Hi @nstjean Can I take this issue??

**Comment by nstjean** [comment]
@9916103020 Sorry, someone has already submitted a pull request for this issue.

**Comment by 9916103020** [comment]
@nstjean is there any other firs time issue which I can solve?

**Comment by nstjean** [comment]
@9916103020 It looks like this one is open! https://github.com/publiclab/plots2/issues/7230

**Comment by 9916103020** [comment]
Thanks @nstjean
