### ISSUE TITLE
Put count of tag subscribers in a green alert box in question post page

### ISSUE THREAD

**Issue by ananyo2012** [publiclab/plots2#715]
Hi, this is a `first-timers-only issue`. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The Problem
The question post page shows the number of users who have subscribed to the question tag. You can visit this link to see this: https://publiclab.org/post?tags=question:question&template=question&redirect=question (login required). Here is an image of the same.
![ask_question](https://i.publiclab.org/system/images/photos/000/017/691/original/ask_question.png)
You can see the text in the sidebar mentioning `2 people have signed up to answer questions on this topic.` But it is quite hard noticing it. It is better to have it in a green bootstrap alert box.

## Solution
Here is the line that shows the text: https://github.com/publiclab/plots2/blob/master/app/views/editor/post.html.erb#L18-L20. We can have it in a green bootstrap alert box. You can take help from the bootstrap documentation on this: http://getbootstrap.com/components/#alerts-examples 

## Steps to Fix
- [ ] claim this issue with a comment
- [ ] set up a repository locally and make sure that all tests pass
- [ ] start a pull request (see contributing to Public Lab software) but mark it as "in progress"
- [ ] fix the issue following the steps above
- [ ] try the manual test listed above
- [ ] make sure all tests pass with rake test
- [ ] alert someone via either the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by RodCardenas** [comment]
I'd like to help with this.

**Comment by jywarren** [comment]
This was fixed in #803!

**Comment by ebarry** [comment]
Hi @RodCardenas! Thank you again for your valuable contribution to Public Lab. I would like to invite you to join us in a video conference to say a few words about what you contributed and how your experience was. The event is https://publiclab.org/openhour, and it’s coming right up on November 7th, at 1pm EDT which is UTC/GMT -4. 

Please feel free to respond here, or else email liz@publiclab.org, stevie@publiclab.org, jeff@publiclab.org.
