### ISSUE TITLE
addTag javascript function does not process place powertags correctly

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#7154]
In following the place tag submission from the modal in https://github.com/publiclab/plots2/pull/7125 I've run into a problem with the addition of tags.

https://github.com/publiclab/plots2/blob/b57eb15c4b77c420e08a6f279ee4d8f909cf3674/app/assets/javascripts/tagging.js#L13-L21

When I re-wrote the `addTag` function I left this section from before. However this is giving me a problem in that if a tag is a place power tag submitted not through the form itself the tag is being sent through 
https://github.com/publiclab/plots2/blob/b57eb15c4b77c420e08a6f279ee4d8f909cf3674/app/assets/javascripts/tagging.js#L107-L127
and never actually being sent to the add tag API unless it returns with a valid geolocation and adds lat, lng, place together. (and `lng` isn't the correct tag name, which makes me think this is an outdated function that we don't need anymore)

Now luckily we don't see this issue pop up very often for two reasons: it doesn't come into play when you use the form itself, only when you use `addTag` in javascript, and it also doesn't happen when you use the modal because "place" is not the first tag in the string of tags.

@jywarren Is there any reason we need to have this looking up geolocations when someone types in a `place:xx` power tag? Can we delete this function? and fix addTag so that it will correctly add a `place` tag just as it should?

**Comment by jywarren** [comment]
We had originally imagined that people could quickly bypass the modal (or
this might've predated the modal) to generate location tags simply by
inputting a place:_____ tag (i forget if it was via some JS code?). But
maybe that's really not useful anymore and we should just deprecate it?

**Comment by nstjean** [comment]
Ahhh, ok. That's up to you! If we want to keep that functionality I will need to fix the api error because right now it's not working at all.

**Comment by jywarren** [comment]
Hmm. I guess let's just simplify and cut it. I can't think of a strong use
case for it after all!

**Comment by nstjean** [comment]
Ok, will do!
