### ISSUE TITLE
Build failing after LEL update

### ISSUE THREAD

**Issue by crisner** [publiclab/plots2#7158]
Getting errors such as,
`Rack app error handling request { GET /lib/leaflet-environmental-layers/example/lib/glify.js }`
`#<ActionController::RoutingError: No route matches [GET] "/lib/leaflet-environmental-layers/example/lib/glify.js">`

The route shown in the error does not exist after the LEL update. Getting the error even after updating map dependencies here in plots2.

**Comment by jywarren** [comment]
Huh... Did we remove that lib, and include it via npm? Maybe we forgot to
change a route accordingly?

**Comment by crisner** [comment]
We had missed changing a link to the old path in `_header.html.erb` file in the `views/layouts` dir.

**Comment by jywarren** [comment]
Ah! Good catch! I guess we should start noting these in release notes...

**Comment by nstjean** [comment]
Just in case anyone else finds this in a search, if you get this error message just run `yarn upgrade` and then `yarn install`.
