### ISSUE TITLE
Remove pipe symbols from autocomplete results in /questions pages

### ISSUE THREAD

**Issue by ananyo2012** [publiclab/plots2#716]
Hi, this is a `first-timers-only issue`. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The Problem
The search box in https://publiclab.org/questions shows autocomplete search results as you type in. The search results contain the username, like count and answer count separated by `|` symbol. It would be be good to have them replaced with few spaces `&nbsp;` Here is a image showing it
![search](https://i.publiclab.org/system/images/photos/000/017/690/original/search_typeahead.png)  

## Solution
The search results are constructed in the questions_search controller as you can see here: https://i.publiclab.org/system/images/photos/000/017/690/original/search_typeahead.png. Just remove the instances of `|` symbol with few spaces `&nbsp;`

## Steps to Fix
- [ ] claim this issue with a comment
- [ ] set up a repository locally and make sure that all tests pass
- [ ] start a pull request (see contributing to Public Lab software) but mark it as "in progress"
- [ ] fix the issue following the steps above
- [ ] try the manual test listed above
- [ ] make sure all tests pass with rake test
- [ ] alert someone via either the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by sandyvern** [comment]
Hi! I would like to attempt to fix this issue. This is my first attempt at contributing to a project other than fixing typos...but would like to give it a try.

**Comment by jywarren** [comment]
Hi, Sandy -- we'd be very happy to have your contribution; please feel free
to ask for input or help if you need it. Thanks!

**Comment by jywarren** [comment]
Closed in #845! Thanks, Sandy!

**Comment by ebarry** [comment]
Hi @sandyvern! Thank you again for your valuable contribution to Public Lab. I would like to invite you to join us in a video conference to say a few words about what you contributed and how your experience was. The event is https://publiclab.org/openhour, and it’s coming right up on November 7th, at 1pm EDT which is UTC/GMT -4. 

Please feel free to respond here, or else email liz@publiclab.org, stevie@publiclab.org, jeff@publiclab.org.
