### ISSUE TITLE
Fix minor typo in LABELS.md

### ISSUE THREAD

**Issue by anthony-zhou** [publiclab/plots2#7167]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

### Changes Requested:
In LABELS.md (https://github.com/publiclab/plots2/blob/master/doc/LABELS.md), there is a typo on line 25:
"Issues which need discussion and requirements needs to be elicitated" should be changed to "Issues that need discussion and requirements need to be elucidated"

Please fix this typo.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by shipcy** [comment]
I want to take this.

**Comment by anthony-zhou** [comment]
@shipcy Go for it! Let me know if you need any help.

**Comment by shipcy** [comment]
@anthony-zhou Can you please tell me the name of the repository for this issue?

**Comment by shipcy** [comment]
@anthony-zhou I've made the changes. You can review it now.

**Comment by n-git-gif** [comment]
i would like to contribute

**Comment by taysa91** [comment]
I am an Outreachy participant and new to Github. If this issue is still open, can I try it.
Thanks

**Comment by jywarren** [comment]
Hi all! I see @shipcy's PR and it looks great. CLosing this now. Thanks everyone - there are more available at https://code.publiclab.org and we'd love your help there!!!
