### ISSUE TITLE
Remove banners from sidebar of /questions page

### ISSUE THREAD

**Issue by ananyo2012** [publiclab/plots2#717]
Hi, this is a `first-timers-only issue`. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The Problem
https://publiclab.org/questions has banners present in the sidebar. Banners refer to the images shown in the sidebar. It would be good to have them removed as they are not required in the questions page.

## Solution
This is the line that shows the banner in the sidebar: https://github.com/publiclab/plots2/blob/master/app/views/sidebar/_user.html.erb#L5. You just need to hide it for the question page. Just a note that the template is used in multiple areas. You need to remove it only for the questions page.

## Steps to Fix
- [x] claim this issue with a comment
- [x] set up a repository locally and make sure that all tests pass
- [x] start a pull request (see contributing to Public Lab software) but mark it as "in progress"
- [x] fix the issue following the steps above
- [x] try the manual test listed above
- [x] make sure all tests pass with rake test
- [x] alert someone via either the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by cpdavngr** [comment]
I can take this one. This will be my first bug fix.

**Comment by jywarren** [comment]
Thank you, that would be great! Don't hesitate to ask if you need any help,
of if you get stuck.

**Comment by cpdavngr** [comment]
Okay, I think I figured it out. I added conditional logic to the "sidebar-feature" line:
[https://github.com/cpdavngr/plots2/blob/master/app/views/sidebar/_user.html.erb#L5-L7](url)
Let me know if this is correct and what I need to do next. Thanks!

**Comment by jywarren** [comment]
Hi that looks good -- next up would be to open a pull request, following the sequence outlined here: https://publiclab.org/wiki/contributing-to-public-lab-software

Then we'll be able to see if your new code passes the automated tests (if you accidentally broke something, for example) and I can review all the changes on Tuesday or Friday (our two review/merge days). Thanks a lot!!

**Comment by cpdavngr** [comment]
Okay, I'm a bit new to github. First, I realized that I forgot to make a
branch for my change before I committed it. Since it was a quick, small
change, I deleted the forked repository.forked it again, cloned it to my
Fedora box, created a new branch, made sure I was in the new branch, made
the change, and then switched to the master branch. However, when I tried
executing "git pull publiclab master" (step 5 in the instructions) it said:

"Fatal: 'publiclab' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."

I tried adding the original repo URL as an upstream but the pull request
still failed.

Not quite sure how to fix this. I'm sure I'm missing something very simple
as I'm new.

Let me know if you have any suggestions. Thanks!

-Ralph

**Comment by jywarren** [comment]
Oh, swapping the URL provided on our projects main GitHub page for the word
"publiclab" should work -- what error did you get then?

We should change that line in the guide to the URL instead of "publiclab"
-- which instructions did you see it in? The wiki page on contributing?
Thanks!

**Comment by cpdavngr** [comment]
Ah, ok, I didn't try that.  I ended up just making the change and doing the
pull request via the Github website. I was trying to avoid that, but, it
worked. :) Anyway, after I made the pull request, it gave me the option to
merge it. I wasn't sure if I was supposed to do that or not so I didn't.
Should I merge it?


The instructions I was following are on the URL that you sent me. Step 5 is
what probably needs updated:

https://publiclab.org/wiki/contributing-to-public-lab-software

Thanks again!

-Ralph

**Comment by jywarren** [comment]
Hmm, i wonder -- i didn't see a PR notification -- maybe it's asking you to merge it into your own master branch? See if you can re-make the PR and choose `publiclab/plots2 master` as the base for your PR and you shouldn't be offered the option to merge into the `publiclab` main project repo. Thanks!

Yeah -- i actually like the edit-on-github.com workflow, it's kind of neat that it exists. Though the PR generation steps are a bit more obscure, as you've found.

**Comment by cpdavngr** [comment]
Ah, yep, that's what I did. I made a pull request against my own fork. :P  (Again, Github n00b. ;) )
Anyway, I think it worked this time via the web.  Let me know if there's anything else I need to do.

Thanks!

-Ralph

**Comment by jywarren** [comment]
super! we're working through a merge issue with PR #810 at the moment, so
it might be a few days before we pull this one in. Thanks for your hard
work!

**Comment by jywarren** [comment]
Great, I see it in #822 and it passes tests perfectly. Closing here! 

I'm curious (we're trying to improve on reaching out to first time contributors) -- how did you hear about our project?

**Comment by cpdavngr** [comment]
Thanks!  I found the project via the "first-timers-only" search in Github.
I think I found out about the search term through this article:
https://medium.com/@kentcdodds/first-timers-only-78281ea47455#.fck0tz4sv

Thank you for taking the time to categorize the difficulty of the issues. I
think that really helps first timers like me. :)

-Ralph

**Comment by ebarry** [comment]
Hi @cpdavngr! Thank you again for your valuable contribution to Public Lab. I would like to invite you to join us in a video conference to say a few words about what you contributed and how your experience was. The event is https://publiclab.org/openhour, and it’s coming right up on November 7th, at 1pm EDT which is UTC/GMT -4. 

Please feel free to respond here, or else email liz@publiclab.org, stevie@publiclab.org, jeff@publiclab.org.
