### ISSUE TITLE
Setting Show password for a short time

### ISSUE THREAD

**Issue by sssash18** [publiclab/plots2#7177]
**Please describe the desired behavior.**
Currently the show password goes from text to password again when the user clicks it,but for a greater password security the password must automatically change from text to password in a short interval of time.This would provide greater password security
**Additional context (optional)**
**Current Behaviour**
![current](https://user-images.githubusercontent.com/57896905/72133983-cae8d400-33a8-11ea-99a4-d5da14dac2a2.gif)
**Expected Behaviour**
![expected](https://user-images.githubusercontent.com/57896905/72133997-d50ad280-33a8-11ea-9a4d-8d41fafe4071.gif)

**Comment by sssash18** [comment]
@jywarren @nstjean Can I go ahead with adding this feature?

**Comment by sssash18** [comment]
@publiclab/reviewers Can you share your views about this?

**Comment by nstjean** [comment]
Hmmm I'm not really sure. I will wait for others to give input!

**Comment by jywarren** [comment]
Yes, i think this is a good idea! Let's just be sure the code is relatively
short and compact, and leave a good comment explaining the behavior, so it
doesn't get messed up later. Thanks!

**Comment by sssash18** [comment]
Could you please review the pr #7190 ?

**Comment by SidharthBansal** [comment]
Great @sssash18 
Let me give it a review
