### ISSUE TITLE
moderating a comment from the website

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#7178]
I went onto this research note because a got an email that a spam comment was posted to it: 

https://publiclab.org/notes/imvec/04-06-2018/online-odor-log-v1-0

I found the spam comment, but when the page reloaded (as it did automatically), the spam comment was still there.  I went to the page again in incognito mode (not logged in as a moderator) and the comment wasn't on there. 

It's confusing to still see the moderated comment on the research note with no visible change to it once you mark it as spam. Is there a way we can change this so the comment is deleted with the page reloads, or that it's clearly marked as moderated? 

Here's a screenshot of the page after I moderated the comment (hit the spam button): 
<img width="778" alt="Screen Shot 2020-01-10 at 9 32 48 AM" src="https://user-images.githubusercontent.com/7490478/72160735-d6c69d00-338c-11ea-819a-ec3967c678fe.png">

**Comment by jywarren** [comment]
Can you reload the page one more time, or go to this modified URL, and check then? if so, it's a browser caching issue that we can fix pretty quick! Thanks!

https://publiclab.org/notes/imvec/04-06-2018/online-odor-log-v1-0?clearcache

**Comment by steviepubliclab** [comment]
Hi, the comment is no longer there for me on this link.

**Comment by jywarren** [comment]
OK great, then we can fix this pretty easily, we just need to make the "next" URL unique by adding something to the end of it to trigger the browser cache to clear. Opening an issue!

**Comment by jywarren** [comment]
Great, made an FTO for it. Thanks!
