### ISSUE TITLE
Wider nav bar covers up top of map

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#7188]
Currently the navbar is fixed and the map is within the `container` div in the content. `container has a fixed `padding-top`, which works when the nav bar is standard size but when there is an extra notice at the top it does not work!

![FireShot Capture 202 - 🎈 Public Lab_ Map - publiclab org](https://user-images.githubusercontent.com/49460529/72179440-df31ce80-33b2-11ea-858d-2492df5ed778.png)

I have a fix for this!

**Comment by shipcy** [comment]
I want to take this issue @nstjean. Can I?

**Comment by shipcy** [comment]
@nstjean please reply?

**Comment by nstjean** [comment]
Hi @shipcy ! Thanks for offering! I already submitted a fix for this. :)
