### ISSUE TITLE
Research notes template shows while editing a question

### ISSUE THREAD

**Issue by ananyo2012** [publiclab/plots2#719]
Hi, this is a `first-timers-only issue`. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The Problem
When you edit a question by clicking the Edit button the same Research note template shows in the editor. Here is a image showing it
![edit_template](https://cloud.githubusercontent.com/assets/10486343/17838476/2c966780-67ec-11e6-9243-289a542e031a.png)
You can see there is a `question:question` tag in the tags section (so it is a question) still the editor shows the research note template. We have to use the question template in the edit form too.

## Solution
We just have to use a `?template=question` parameter in the edit link of the question. Here is the line that contains the edit link: https://github.com/publiclab/plots2/blob/master/app/views/like/_like.html.erb#L36

One more thing to note is the question template lists the number of followers to the question topic which is done by subscribing the specific question power tag. Questions are basically notes tagged with a `question:topic` tag where`topic` is the question topic. You can find a power tag using the `power_tag` method for a node. So you have to use something like `@node.power_tag('question')` to find a question tag for a node. What this method does is that it returns the `topic` for that question in form of a string. Once you get the topic of the question you just have to use that to find the followers of that topic. Here are the lines that shows the no of followers: https://github.com/publiclab/plots2/blob/master/app/views/like/_like.html.erb#L36. 

Just replace the occurrences of `params[:tags]` with `question:topic` where topic is found using the method described above in case `params[:tags]` is not present i.e. in case of question edit. So use a basic `if` statement for that.

## Steps to Fix
- [x] claim this issue with a comment
- [x] set up a repository locally and make sure that all tests pass
- [x] start a pull request (see contributing to Public Lab software) but mark it as "in progress"
- [x] fix the issue following the steps above
- [x] try the manual test listed above
- [x] make sure all tests pass with rake test
- [ ] alert someone via either the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by sjones88** [comment]
Hi, I'd like to work on this.

**Comment by jywarren** [comment]
Hi, amazing, thank you so much! I see your PR, perfect.

**Comment by ebarry** [comment]
Hi @sjones88! Thank you again for your valuable contribution to Public Lab. I would like to invite you to join us in a video conference to say a few words about what you contributed and how your experience was. The event is https://publiclab.org/openhour, and it’s coming right up on November 7th, at 1pm EDT which is UTC/GMT -4. 

Please feel free to respond here, or else email liz@publiclab.org, stevie@publiclab.org, jeff@publiclab.org.
