### ISSUE TITLE
Unapproved users should not be able to tag wiki pages

### ISSUE THREAD

**Issue by Uzay-G** [publiclab/plots2#7196]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.
### The Problem
Currently, users who have not been approved can add tags to wiki pages. This creates issues because these users who have not yet shown their worthwhile participation in the platform can spam a wiki page with random tags. We need your help to prevent this and create a test to check that everything works! :+1:

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
 
- **Write a test for the functionality**
We are going to follow the principles of [Test-Driven-Development](https://en.wikipedia.org/wiki/Test-driven_development) and begin my making a test to check whether or not are changes work. For now, the tests will fail because we haven't changed anything.
Add this test to the [`node` unit test](https://github.com/publiclab/plots2/blob/master/test/unit/node_test.rb):
```ruby
test 'non-approved users should not be able to add tags' do
    node = nodes(:one)
    assert_difference 'node.tags.count', 0 do
      node.add_tag('myspamtag', users(:spammer))
    end
    assert_not node.has_tag('myspamtag')
end
```
This way, we test that adding the tag as a non-authorized user fails. If you run the tests now with `rails test` in the project directory, this one should fail because we haven't implemented the changes yet!

- **Make the test pass**
This is the start of the method that adds the tag to the wiki page:
https://github.com/publiclab/plots2/blob/9fe25045e3af6236a55bcbcb04e1db55aab42f19/app/models/node.rb#L758-L763
We want to add a conditional that makes sure the user has been approved. To do this, cut the body of the method lines 759-819 and reformat the method to look like this:
```ruby
def add_tag(tagname, user)
  if user.status == 1
   # paste function body
  end
end
```
That way, if an un-authorized user tries to add a tag, they will be blocked from doing it. Run the tests now, and our test should pass!
# **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by sssash18** [comment]
Can I take it?

**Comment by Uzay-G** [comment]
Yeah go ahead @sssash18 :+1:
