### ISSUE TITLE
Restrict settings page to logged-in users

### ISSUE THREAD

**Issue by Uzay-G** [publiclab/plots2#7201]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!
### The Problem
Currently, if non logged in users try to go to their settings, the page returns an error because it tries to access the current user's settings but there is no current user because the user is not logged in. We want to fix this behavior so that the settings page is restricted to logged-in users.
### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- We need you to edit the following line:
https://github.com/publiclab/plots2/blob/9fe25045e3af6236a55bcbcb04e1db55aab42f19/app/controllers/users_controller.rb#L3
This line configures which pages require a logged-in user, as you can see the `save_settings` route is restricted but not the `settings` one. You need to  restrict the settings route so change it the line to look like this:
`before_action :require_user, only: %i(edit update save_settings settings)`

There we go! Now, non-logged in users will be redirected to login and will not get any errors :smile:

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by sssash18** [comment]
Can I do this?

**Comment by Uzay-G** [comment]
Hey, I noticed you already claimed another fto I made. Could you let someone else work on this issue? Thanks @sssash18 :+1:

**Comment by sssash18** [comment]
@Uzay-G  I completed the previous task .Can i start with this one?

**Comment by sssash18** [comment]
Sure,no problem..

**Comment by sssash18** [comment]
@Uzay-G  Meanwhile reviewers review about the test fails can i carry on with this issue?

**Comment by Uzay-G** [comment]
Yeah go ahead
