### ISSUE TITLE
Introducing divider in tools dropdown

### ISSUE THREAD

**Issue by sssash18** [publiclab/plots2#7204]
**Please describe the desired behavior.**
Currently in the tools dropdown their is no divider before "Kits" and "Software" heading.This makes it tough to understand whether it is a link or a Heading. Introducing a divider before them would make it more understandable

**Additional context (optional)**
**Current Behaviour**
![Screenshot 2020-01-11 at 10 15 57 PM](https://user-images.githubusercontent.com/57896905/72207538-235ec500-34c0-11ea-805c-13bf87293361.png)
**Expected Behaviour**
![Screenshot 2020-01-11 at 10 16 34 PM](https://user-images.githubusercontent.com/57896905/72207550-3d98a300-34c0-11ea-97ab-69b81bd6e517.png)

**Comment by sssash18** [comment]
@publiclab/reviewers  Can I move ahead with this?

**Comment by SidharthBansal** [comment]
Yes

**Comment by SidharthBansal** [comment]
@jywarren please suggest. I am in favor of dividers.
@sssash18 you can do as per @jywarren  request.
Thanks @sssash18

**Comment by sssash18** [comment]
@SidharthBansal Thanks for your positive feedback!!
@jywarren  Can you please share your views?

**Comment by sssash18** [comment]
@SidharthBansal Any update on this? Should I implement it.

**Comment by SidharthBansal** [comment]
Let's wait for Jeff. Meanwhile you can do other issues 
Thanks

**Comment by jywarren** [comment]
Sure, let's do this!
