### ISSUE TITLE
Invalid email error on signup page

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#7212]
@VladimirMikulic please fix this. You missed this.
![image](https://user-images.githubusercontent.com/20972099/72222524-9aad5b00-358b-11ea-8482-eb9f2228a036.png)
I already gave 5 points for signup form and modal validations.

**Comment by SidharthBansal** [comment]
Kindly check this on the localhost. Maybe changes are not deployed to the production yet.
`Email not present` should come instead

**Comment by VladimirMikulic** [comment]
Should I do the same for password and confirm password fields?

**Comment by VladimirMikulic** [comment]
Or maybe instead of showing error, we can just return to the original style.

**Comment by SidharthBansal** [comment]
Yes. They should say similar things. Marks are already given for this task

**Comment by VladimirMikulic** [comment]
I am on it @SidharthBansal. Thanks.
