### ISSUE TITLE
Consolidate testing for `user_sessions` controller

### ISSUE THREAD

**Issue by Uzay-G** [publiclab/plots2#7218]
Hey, our [login controller](https://github.com/publiclab/plots2/blob/master/app/controllers/user_sessions_controller.rb) has some very complex logic and especially for oauth login there are many different outcomes for each login. This is explained in [our documentation](https://github.com/publiclab/plots2/blob/master/doc/LOGIN_SYSTEMS.md)

This complexity is why it's important to have bulletproof testing for this controller. I have begun adding tests in https://github.com/publiclab/plots2/pull/7113 and https://github.com/publiclab/plots2/pull/7072 but I think a few more would be useful.

Here are those that I have already made and are working for the website:
```ruby
  test "logging in through omniauth and then through normal login should display error and redirect" do
    request.env['omniauth.auth'] =  OmniAuth.config.mock_auth[:github1]
    # login through omniauth 
    post :create
    # logout
    post :destroy
    request.env['omniauth.auth'] = nil
    post :create, params: { user_session: { username: "bansal_sidharth309", password: "random"} }
    assert_equal flash[:error], "This account doesn't have a password set. It may be logged in with Github account, or you can set a new password via Forget password feature"
  end

  test "logging in with banned user through normal login should fail" do
    user = users(:bob)
    user.ban
    post :create, params: { user_session: { username: user.username, password: 'secretive' } }
    assert_redirected_to root_url
    assert_equal flash[:error], I18n.t('user_sessions_controller.user_has_been_banned', username: user.username).html_safe
  end
```
I'd love to hear what you think and work on this with you! @publiclab/reviewers @SidharthBansal

**Comment by SidharthBansal** [comment]
Go for these tests. Please open up a pr. I will merge it quickly

**Comment by SidharthBansal** [comment]
3 + 2 points so total 5 points. I don't think we can give more than 5 points in total for both the tests. What do you think?

**Comment by Uzay-G** [comment]
Oh wow! I didn't expect to get points for these. Yeah that's more than
enough. I will work on this in 6hrs when I get home.

**Comment by SidharthBansal** [comment]
You will get 1 extra point for suggestion for this issue opening.

**Comment by SidharthBansal** [comment]
``
test "logging in with banned user through normal login should fail" do
    user = users(:bob)
    user.ban
    post :create, params: { user_session: { username: user.username, password: 'secretive' } }
    assert_redirected_to root_url
    assert_equal flash[:error], I18n.t('user_sessions_controller.user_has_been_banned', username: user.username).html_safe
  end
``
we will also require similar test for moderator

**Comment by Uzay-G** [comment]
Hey @SidharthBansal did we add the points for this pr in another task?
I thought i had solved it on the dashboard but it is nowhere to be found.

**Comment by SidharthBansal** [comment]
I think we can add this in System Test 2 task.

**Comment by Uzay-G** [comment]
Oh! Good idea :+1:
