### ISSUE TITLE
Remove multiple screenshots from PRs

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#7219]
![image](https://user-images.githubusercontent.com/20972099/72238458-c704be00-3603-11ea-91c8-62ba04bad79a.png)
Kindly decrease number of screenshots from the prs

**Comment by Uzay-G** [comment]
Yes I agree with you @SidharthBansal. Also it's a bit of a waste of energy to have these photos sent through Github notifications each time. What do you think @jywarren?

**Comment by SidharthBansal** [comment]
I suggest keeping 2-3 screenshots.

**Comment by jywarren** [comment]
Actually i use these to check features carefully. If there is some other
way to list them or link to them, it's very helpful for double-checking
especially UI changes. I'd like to keep them all, but if you can think of a
way to minimize them or display them on a different page that we link to,
that would be great.

**Comment by jywarren** [comment]
for example could we set it to overflow:hidden in CSS, and would that let
us scroll through them? Then we can show 2-3 at a time only.

**Comment by SidharthBansal** [comment]
agreed

**Comment by NitinBhasneria** [comment]
If this issue is open... Can I work on this @SidharthBansal.

**Comment by jywarren** [comment]
If you can figure out a way to do this, we'd appreciate it! I think maybe
we need to test out how css scroll works when sent via GitHub email
notifications. Bears some testing!
