### ISSUE TITLE
Talk page should display title, instead of path, of the parent page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#722]
Hi, this is a `first-timers-only issue`. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

The Talk pages, for example https://publiclab.org/talk/desktop-spectrometry-kit-3-0 show the url, but not the title, of the parent page. 

## Solution

The string used is stored in a `@slug` variable in the talk controller: https://github.com/publiclab/plots2/blob/1b6074ed951e698b440dc929e42577fe6bfe0633/app/controllers/talk_controller.rb

It's later used in this template: https://github.com/publiclab/plots2/blob/a79dd9591ebc6ecd5f2b9a2de91c224ab5baf4d1/app/views/talk/show.html.erb

We should instead store the whole node object in a variable called `@node` by searching for it by the `slug`, which we receive as `params[:id]`:

```ruby
@node = DrupalNode.find_by_slug params[:id]
```

...and then in the template use `@node.path` and `@node.latest.title` (for the title from the most recent node revision). 

If you're feeling particularly enterprising, the Talk controller, with only one method, could be merged into the wiki controller as a `def talk` method, and the corresponding template moved from `/app/views/talk/show.html.erb` to `/app/views/wiki/talk.html.erb`. Since we don't anticipate more talk methods or tools, we might as well simplify a bit. 

## Steps to Fix

- [x] claim this issue with a comment here, below
- [ ] set up a repository locally and make sure that all tests pass
- [ ] start a pull request (see contributing to Public Lab software) but mark it as "in progress"
- [ ] fix the issue following the steps above
- [ ] make sure all tests pass with `rake test`
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by ap916** [comment]
Hi, I would like to work on this issue. Do you have a deadline in which it should be done ?
I don't have much experience with Ruby so I may need to brush up a bit.

**Comment by jywarren** [comment]
Great! No, no deadline -- and please do ask if you need any help. Thanks!!!

**Comment by ap916** [comment]
Using `@node.latest.title` is giving me this error :
`ActionView::Template::Error: undefined method `title' for nil:NilClass`

**Comment by jywarren** [comment]
Is that in your local environment? Each node should have a "latest" revision, so that's not good. Maybe you could commit what you have so far and open a pull request so I can take a look at your code?

**Comment by ap916** [comment]
I opened a pull request. Please check it out.

**Comment by jywarren** [comment]
Ok, I may not be able to right away but it'll also now run your code in a
virtual machine so we can see how it goes.

**Comment by jywarren** [comment]
This was fixed in #778 thanks to @ap916, thanks a lot for your contribution -- forgot to close it!

**Comment by ebarry** [comment]
Hi @ap916! Thank you again for your valuable contribution to Public Lab. I would like to invite you to join us in a video conference to say a few words about what you contributed and how your experience was. The event is https://publiclab.org/openhour, and it’s coming right up on November 7th, at 1pm EDT which is UTC/GMT -4. 

Please feel free to respond here, or else email liz@publiclab.org, stevie@publiclab.org, jeff@publiclab.org.
