### ISSUE TITLE
Finalizing the 2020 Public Lab Software Contributors Survey

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#7224]
Hi all!
I'm setting up the survey for our community here, and updating some categories from the Fall 2018 edition. First question: Are these the best set of current projects to list for people to indicate they are contributing to? Please read the alphabetized list below and please add a comment with any others i missed!

- Community Toolbox
- ImageSequencer
- infragram-js
- inline-markdown-editor
- leaflet-blurred-location
- Leaflet.DistortableImage
- Leaflet-environment-layers
- MapKnitter
- Plots2 / PublicLab.org
- plotsbot
- PublicLab.Editor
- Spectral Workbench
- WebJack

Based on last year's issue: https://github.com/publiclab/plots2/issues/4567

CC @cesswairimu @sashadev-sky @SidharthBansal @gauravano @emilyashley @jywarren and all who are reading this.

**Comment by ebarry** [comment]
Other requests that came in after last year's survey included: 

- several people suggested we add  "daily" to the "How frequently do you contribute?" question. 
- @HarshKhandeparkar asked "can we add countrywise demographic survey? Like we can list some of the big countries in radio buttons and if the country of the person is not listed, they can enter it in a separate input? How does that sound?"
- @sagarpreet-chadha said "I would like add a question about "how many years development experience do you have?" so we can visualize this in a bar chart

**Comment by SidharthBansal** [comment]
Hello
> several people suggested we add "daily" to the "How frequently do you
contribute?" question.

Yes

>@HarshKhandeparkar <https://github.com/HarshKhandeparkar> asked "can we
add countrywise demographic survey? Like we can list some of the big
countries in radio buttons and if the country of the person is not listed,
they can enter it in a separate input? How does that sound?"

Great

> @sagarpreet-chadha <https://github.com/sagarpreet-chadha> said "I would
like add a question about "how many years development experience do you
have?" so we can visualize this in a bar chart

Awesome idea

Regarding repos, I think there are two Spectra Work Bench(RoR and JS)

Thanks

**Comment by ebarry** [comment]
from @jywarren : 
“How do people make time for this work? In what size chunks?”
- 15 minutes?
- an hour every other day? 
- a block of time once a week? 
- write your own_________

**Comment by sagarpreet-chadha** [comment]
I dont know if we already have this: "What do you expect from contributing to open source?"

**Comment by ebarry** [comment]
do you have a set of answers you'd like to offer people? That would be easier to analyze if we could come up with a list rather than leave it free text

**Comment by sagarpreet-chadha** [comment]
Okay cool,
The options can be multiple select types:

1. Learning and leveraging your skills.
2. This is part of my School assignment.
3. I want to take part in open source programs like Gsoc, GCI, outreachy,
etc.
4. I am curious to know how open-source development works.
5. I want to learn about PublicLab
6. I want to use this library/software in my personal projects.
7. I have some other reason.


Thanks :)

**Comment by SidharthBansal** [comment]
Awesome ideas folks

**Comment by emilyashley** [comment]
Thanks y'all. Adding these great suggestions to the survey shortly :)

**Comment by emilyashley** [comment]
Opened it here: https://github.com/publiclab/plots2/issues/7406 

Closing this planning issue. Thank you!
