### ISSUE TITLE
To move css present in _notes.html.erb

### ISSUE THREAD

**Issue by sssash18** [publiclab/plots2#7234]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
The notes/_notes.html.erb contains a lot of css regarding its style.It's better to move it in a seperate file

> What did you expect to see that you didn't?
it should be moved to a new file('notes.css') for code management.

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by sssash18** [comment]
@publiclab/reviewers Share your views over this?

**Comment by cesswairimu** [comment]
yeah, I believe that is the best practice..we can totally do this. Thanks so much for opening this
