### ISSUE TITLE
Map over laps the publish line

### ISSUE THREAD

**Issue by sssash18** [publiclab/plots2#7235]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
The map in the create note overlaps with the bottom publish line

> What did you expect to see that you didn't?
Publish line should be on top.
**Current Behaviuor**
![Screenshot 2020-01-14 at 7 11 54 PM](https://user-images.githubusercontent.com/57896905/72349086-d66a3100-3701-11ea-8ebd-8d445e6f9787.png)

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by sssash18** [comment]
@publiclab/reviewers  Kindly share your views on this?

**Comment by cesswairimu** [comment]
I think this is the required display...
![Screenshot from 2020-01-14 17-49-43](https://user-images.githubusercontent.com/17081074/72354221-65714c00-36f6-11ea-8888-b3bafd95b63c.png)
:point_up: this sticks to the bottom and you scroll to see the rest of the form inputs

**Comment by sssash18** [comment]
@cesswairimu  I agree with you.

**Comment by nstjean** [comment]
Yes, this is an issue in PublicLab.Editor : https://github.com/publiclab/PublicLab.Editor/issues/367

**Comment by sssash18** [comment]
So should I close this one if it already exists? @nstjean

**Comment by nstjean** [comment]
@sssash18 Yes I think we can close this one!

**Comment by sssash18** [comment]
Already present
