### ISSUE TITLE
[urgent] Broken page

### ISSUE THREAD

**Issue by klie1** [publiclab/plots2#724]
### What happened just before the problem occurred

I clicked on the blog link to "Introducing the Environmental Evidence Project" from the Dashboard, pictured here:
![screen shot 2016-08-22 at 5 28 11 pm](https://cloud.githubusercontent.com/assets/20325934/17873909/e3869a72-688d-11e6-8782-ea72d34f6b3d.png)

And it brought me to this error message:
![screen shot 2016-08-22 at 5 27 33 pm](https://cloud.githubusercontent.com/assets/20325934/17873917/efe9a3a4-688d-11e6-815c-4b7f946c646f.png)

### Relevant URLs
https://publiclab.org/blog

### PublicLab.org username

klie

**Comment by jywarren** [comment]
Thanks, I'm on this one!

**Comment by jywarren** [comment]
Temporary fix issued, but pending a big rebase/merge to do a final fix and test in #726.

**Comment by jywarren** [comment]
Closing this as fixed in #726.
