### ISSUE TITLE
Redirect to the dashboard after OAuth SIGNUP

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#7240]
Moved from #7211 
Right now the user is redirected back to the previous page after OAuth Sign UP and login.
We want the user to go to the Dashboard page on first time of Signing into Public Lab irrespective of type of login(form/fb/twitter/google/GH)
@Uzay-G is working on this

**Comment by SidharthBansal** [comment]
@Uzay-G go for it

**Comment by SidharthBansal** [comment]
Please remember that a user may have a account with no provider linked. User is not signed in. User tries to log in through provider P. This should not result in dashboard. 
Does this makes sense?
We will require a lot of tests here too.

**Comment by Uzay-G** [comment]
Yes I understand. Should I work on this before adding `open_id` tests for MK and SWB?

**Comment by SidharthBansal** [comment]
You can work on both. Your wish which one first or both together

**Comment by Uzay-G** [comment]
Hey, I had a question about this, could you help me?
In this part of the oauth signup logic:
https://github.com/publiclab/plots2/blob/c5e3275d8f3841c2291551abfc8d357904dfddd2/app/controllers/user_sessions_controller.rb#L85-L88

The user is signing up through `open_id` so should we redirect him back to the site he was using before signing up or to the dashboard?

Thanks!

**Comment by SidharthBansal** [comment]
Yes.
I am not able to see your last comment.

**Comment by Uzay-G** [comment]
What do you mean?

**Comment by SidharthBansal** [comment]
Is anything remaining here?

**Comment by SidharthBansal** [comment]
If everything is complete. Then please close this issue

**Comment by Uzay-G** [comment]
No this is done. Could you close it? I don't have the permission. Thanks :+1:
