### ISSUE TITLE
At location button to dashboard sidebar

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#7263]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [sidebar/_dashboard.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/sidebar/_dashboard.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

On line 20 remove this:
https://github.com/publiclab/plots2/blob/46af8030c82fe8346702edbaf917bfeb9e229163/app/views/sidebar/_dashboard.html.erb#L20

And add in this code in its place:
```
<div style="margin: 2.2rem 0;">
  <a class="btn btn-lg btn-outline-secondary blurred-location-input" submit_to="/profile/tags/create/<%= current_user.uid %>"><i class="fa fa-map-marker" style="color:#c40;"></i> Add your location</a>
  <p style="font-size: smaller; margin: 0.3rem 0;">
    Add your location to see work near you<br>
    <a href="https://publiclab.org/location-privacy" target="_blank">About location privacy »</a>
  </p>
</div>
```

It will look like this when you are done!

![FireShot Capture 225 - 🎈 Public Lab_ Dashboard - localhost](https://user-images.githubusercontent.com/49460529/72541476-95ccfd80-3850-11ea-953d-4a66ddea0ae4.png)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by imajit** [comment]
Hey ! I'm working on it

**Comment by pcube99** [comment]
Is this issue still up ?
I want to claim it.

**Comment by nstjean** [comment]
Hi @pcube99 ! @imajit has submitted a pull request for this issue. Take a lot to see if you can find any first-time-only issues that aren't taken.

**Comment by imajit** [comment]
Hey @nstjean I can you review the PR

**Comment by imajit** [comment]
@pcube99 If you are looking FTO issues you can try #7269 if it has not been claimed
