### ISSUE TITLE
FTO: Fix duplication of flashes when moderating users

### ISSUE THREAD

**Issue by Uzay-G** [publiclab/plots2#7269]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### The Problem
Currently, when a moderator or admin moderates a user, there is a duplicate flash to notify them:

![double-mod](https://user-images.githubusercontent.com/52892257/72567107-7caa6800-38b5-11ea-83a7-ad16aba2c9ba.gif)
We need your help with this.
### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

-  These two flash messages are being called in two different areas of the code:
In the Users controller:
https://github.com/publiclab/plots2/blob/79cb1622175c12f1098a251de6957a53cde5d3d8/app/controllers/users_controller.rb#L228-L230

In the Admin controller:
https://github.com/publiclab/plots2/blob/79cb1622175c12f1098a251de6957a53cde5d3d8/app/controllers/admin_controller.rb#L277

The second one is useless whenever a user is moderated the admin is redirected to the profile page of the user. When he reaches that page, the `profile` route will display a message warning that the user of the page is moderated. On the other hand, if we removed the first flash, whenever an admin went to a moderated user's profile, there would be no warning for him to notice the user is banned. 

Please help us by removing line  277 of the `admin_controller` to fix this duplication :+1:

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by pcube99** [comment]
I want to claim the issue.

**Comment by oslewis** [comment]
> I want to claim the issue.

Hey,
Have you submitted a pull request yet?
Anything I can do to help?

**Comment by pcube99** [comment]
What am I supposed to do in this issue?
I mean removing 277 line, that's it ??

**Comment by Uzay-G** [comment]
Yeah removing that line will remove the duplication

**Comment by SangharshSeth** [comment]
Hey i like to claim this issue

**Comment by SangharshSeth** [comment]
Hi  can i submit a pull request to this issue.

**Comment by pcube99** [comment]
> What am I supposed to do in this issue?
> Can you elaborate on the issue !!

I have committed a PR #7080  
Please check it.

**Comment by pcube99** [comment]
@Uzay-G  Please check the latest PR.
