### ISSUE TITLE
duplicate wiki page paths

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/plots2#727]
this page is no longer displaying-- thought I'd report it since you've had trouble with some wiki links recently:
https://publiclab.org/wiki/passive-pm

**Comment by ananyo2012** [comment]
@jywarren Another missing data I guess. Can you have a look at it?

**Comment by jywarren** [comment]
Hi, I'm seeing this error:

```
Completed 500 Internal Server Error in 549.0ms

ActionView::Template::Error (undefined method `[]' for nil:NilClass):
    44:         <li class="active"><a href="#"><span class="hidden-xs"><%= t('wiki.show.view') %></span><span class="visible-xs"><i class="fa fa-file-o"></i></span></a></li>
    45:         <li><a href="<%= @node.edit_path %>?t=<%= Time.now.to_i %>"><i class="fa fa-pencil"></i><span class="hidden-xs hidden-sm"> <%= t('wiki.show.edit') %></span></a></li>
    46:         <% if current_user && current_user.role == "admin" %><li><%= link_to "/wiki/delete/"+@node.id.to_s, :confirm => I18n.t('wiki.show.are_you_sure_delete', :path => @node.path) do %><i class="fa fa-trash"></i><span class="hidden-xs hidden-sm"> <%= t('wiki.show.delete') %></span><% end %></li><% end %>
    47:         <li><a href="/talk/<%= @node.slug[0,50] %>"><i class="fa fa-comments-o"></i><span class="hidden-xs hidden-sm"> <%= t('wiki.show.talk') %></span></a></li>
    48:         <li><a href="/wiki/revisions/<%= @node.slug %>"><span class="hidden-xs"><%= @node.revisions.length %> </span><i class="fa fa-list"></i></a></li>
    49:       </ul>
    50:     </div>
  app/views/wiki/show.html.erb:47:in `_app_views_wiki_show_html_erb___528106901410175680_63438900'
```

I think this is due to the record having a nil `slug` -- perhaps that link should be based on `path` and not `slug`? Ananyo, could you try for a fix?

We're still resolving a major rebase of the new search controller (maybe another day), but if this is very urgent, I can do a hotfix now that'll be overwritten by a later commit. What do you think, @mathewlippincott ?

**Comment by jywarren** [comment]
OK, i did a quick fix -- but no commit yet -- I just turned `slug[0,50]` into `slug.to_s[0,50]`.

**Comment by ananyo2012** [comment]
@jywarren Yes actually it was previously based on path by the `path` method but now it is the value of the slug column. But the slug column should have been generated. Since every time a new record is created or the title is change the slug is regenerated according to this https://github.com/publiclab/plots2/blob/master/app/models/drupal_node.rb#L26-L28

**Comment by jywarren** [comment]
Maybe since the slug column usage has changed, we should scan the codebase
for instances of slug and add to_s? Or add a test that runs a slug = nil
node through various pages? The former sounds better.

**Comment by mathewlippincott** [comment]
I figured it pointed to some larger issue and might effect other pages-- I wouldn't invest in re-posting this page so much as solving whatever brought it down, which seems to be what y'all are doing.

**Comment by jywarren** [comment]
@ananyo2012 - there's extensive use of `slug` on that view, and I think we need to either change calls of `slug` to a new name that returns `path.split('/').last` or run a batch script to restore original slugs to ensure these all work. As this is related to the `friendly_id` work (and I'm currently working on the big search rebase) could you take a look and at least solve this page? Thanks!

**Comment by jywarren** [comment]
Oh and @mathewlippincott - the page is back up, we're just looking at followup fixes for any related issues.

**Comment by ananyo2012** [comment]
Well the slug does keeps the updated title. And every time we change a record it is resaved. So do we really need to change it?

**Comment by jywarren** [comment]
Actually the following pages lack a `slug` -- how did that happen, and how shall we generate them? 

`["Guides", "London UK", "air quality class 6", "air quality class 7", "Air Quality Class 7", "Air Quality Class 6", "water-quality", "hometesting-environmental-estrogens-bibliography|Bibliography", "hometesting-environmental-estrogens-bibliography|Bibliography", "Initiatives", "Initiatives", "Intellectual Property", "Intellectual Property", "Water quality ", "Blog", "Blog", "London, UK", "DOCCOM", "DOCCOM", "Spectral Workbench Snapshots", "Spectral Workbench Snapshots", "passive-pm", "passive-pm", "中国城乡水质问题 - Water Risks in Urban and Rural China", "中国城乡水质问题 - Water Risks in Urban and Rural China"]`

**Comment by jywarren** [comment]
Though many of those pages (testing manually) work fine: https://publiclab.org/wiki/water-quality

**Comment by jywarren** [comment]
I could just run something like:

```ruby
DrupalNode.where(type: 'page', status: 1, slug: nil).each do |n|
  n.slug = n.generate_path.split('/').last
  n.save
end
```

in the console?

**Comment by ananyo2012** [comment]
Ok what i see is there are pages with the same title. Pages with duplicate
title aren't allowed now.That's why the slug didn't get updated for these
pages.
ᐧ

**Comment by jywarren** [comment]
Ah, good observation. I'll go through those and find which is the "real"
node, and/or rename one if both have real content.

**Comment by ananyo2012** [comment]
Previously nodes with same path were allowed that's why some of the records
still exist with the same paths. But you can't resave these records now
since validation check will fail anyways.
ᐧ

**Comment by ananyo2012** [comment]
Yes you can just rename the path and title for the duplicate entries and
resave all entries that will solve this problem.
ᐧ

**Comment by jywarren** [comment]
Ugh, still working on this; had a really ugly revert needed resulting in this page having the wrong updated timestamp: https://publiclab.org/wiki/london-uk

This is really painstaking work, so I should take it very slow. Only 6 records remain that are affected.

**Comment by jywarren** [comment]
I think for the remainder, the process should be:

1. Check the wayback machine for the `nid` of the one that was shown by default before this migration: https://web.archive.org/web/20150316102923/https://publiclab.org/wiki/water-quality
2. Check that the other (presumably duplicate) node has only one revision, which is older than the `node.changed` timestamp for the original node
3. Delete the duplicate node

**Comment by jywarren** [comment]
Fixed `london-uk`, looking at last six now.

**Comment by jywarren** [comment]
OK, all duplicate records of wiki pages resolved. @ananyo2012 - anything else you'd like to tidy up on `friendly_id` work besides the `slug` issues I've outlined? I'm closing this now.

**Comment by ananyo2012** [comment]
Well we can revert the slug column and friendly id slug table too if you
say. But is there any simpler way to do this rather than writing a new
migration to revert the changes?

ᐧ

**Comment by jywarren** [comment]
Hmm, I think that if we want there to be an unbreakable relationship
between slug and path, we should make sure all existing nodes follow that
(some notes still don't, and we could follow up on that). I'm mostly
worried about code cleanliness to future contributors here, and if there's
ambiguity about slug vs. path we should at least provide good documentation
for guidance.
