### ISSUE TITLE
Add welcoming message as a feature

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#7277]
The welcoming text currently is fixed and not editable by the admins.Moving the welcoming text into a feature will allow site admins to edit it according to their needs.

Follow up to #6096 implemented by pull request #7236 

**Please describe the desired behavior.**
Admins can now edit the welcoming message present here.
![Screenshot from 2020-01-16 11-53-22](https://user-images.githubusercontent.com/33183263/72605571-0c4a2800-3943-11ea-901d-36fcdc73581e.png)

**Additional context (optional)**
Check out the discussion here:-
https://github.com/publiclab/plots2/pull/7236#issuecomment-575261143

**Comment by Tlazypanda** [comment]
@jywarren I would like to work on this as discussed.Thanks :)

**Comment by jywarren** [comment]
That would be super!!!!
