### ISSUE TITLE
Re-add sort_by_tags_test tests after major rebase

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#728]
I removed the tests in this file during a major rebase; the issue was with the `session[:tags]` call in both returning `nil`. I apologize, but we really needed to get this merge done, so I was hoping @ananyo2012 could take a look at the changes in [the PR I merged](https://github.com/publiclab/plots2/pull/652#issuecomment-242095143) and double check to see why the session is returning empty. 

Thanks!

**Comment by jywarren** [comment]
@ananyo2012 - if you have a chance to re-add these (or if you already have) I'd love to close this out. Thanks!

**Comment by ananyo2012** [comment]
Yes Jeff I have already added these. You can close this one now.
ᐧ
