### ISSUE TITLE
Very few suggestions show up for subscription 

### ISSUE THREAD

**Issue by imajit** [publiclab/plots2#7289]
On this page [link](https://publiclab.org/subscriptions) when I try to add new tags to subscribe to then very few suggestions show up in the drop down like balloon mapping, spectrometer and thermal flashlight .
![Screenshot from 2020-01-18 16-27-00](https://user-images.githubusercontent.com/38528640/72662657-a5df0b80-3a0f-11ea-9d8f-9c7a68c4f885.png)
In this field 
![bug](https://user-images.githubusercontent.com/38528640/72662658-a677a200-3a0f-11ea-996c-6f4deaf49aff.png)

What I was expecting was to find all tags orders in some manner to appear when I type a letter like if I type 'a' then all the tags with 'a' in it should appear which doesn't seem to happen .

**Comment by nstjean** [comment]
So it looks like that was the idea, eventually, but that it was never coded in so it's just some "example tags" hardcoded in.

I'm looking through https://github.com/publiclab/plots2/blob/master/app/models/tag.rb which is the model for Tag. I don't see any functions that get all tags from the database. What you'd need to do is add a function like all_tags_by_popularity and in it you'd use ActiveQuery to get all unique tagnames from the database, sorted by how frequently it has been used. This could be pretty challenging to accomplish! You'd also have to filter out any powertags.
