### ISSUE TITLE
Wrong message when signing in without password as oauth user

### ISSUE THREAD

**Issue by Uzay-G** [publiclab/plots2#7296]
If a new user signs up through oauth and then later tries to login through the site without having set their password, they can either use their username or email to identify themselves.

If they use their username, a warning flashes telling them that they have not yet set their password. This is the expected behavior. But if they use their email to log in, instead of the same warning message being displayed, they get the error invalid password although they have not set it yet.

The pr #7292 will fix this so that trying to log in in with email displays the correct warning

**Comment by NitinBhasneria** [comment]
@Uzay-G Is this issue available?

**Comment by Uzay-G** [comment]
Sorry, this was fixed in #7292
