### ISSUE TITLE
Fixed table headers

### ISSUE THREAD

**Issue by keshavsethi** [publiclab/plots2#7298]
I feel that tables will be much more interactive if table headers are kind of fixed at the top of table as it sometimes become difficult to see which column defines what
![Screenshot from 2020-01-19 04-34-30](https://user-images.githubusercontent.com/36025262/72671789-9f837a80-3a75-11ea-9e17-07d6a0652d63.png)
here we can't differentiate which 0 is for like and which is for comments 
link [https://publiclab.org/newsletter](url)

**Comment by keshavsethi** [comment]
@SidharthBansal @jywarren should I try this??

**Comment by jywarren** [comment]
Sure, i agree with this! Thank you!
