### ISSUE TITLE
Travis sometimes fails due to redirection fixes

### ISSUE THREAD

**Issue by Uzay-G** [publiclab/plots2#7303]
In #7113, oauth redirection was fixed and now the user is redirected to the page he was on before logging in. But the user is for some reason redirected to the previous page plus a parameter with the current time:
https://github.com/publiclab/plots2/blob/b80f193b60827f90b70bef020648d8b2813468fa/app/controllers/user_sessions_controller.rb#L21-L22

So, at the time I did not question this and left it as is. But, I also made some tests for redirection:
```ruby
  test "redirects to previous page when logging in through oauth" do
    request.env['omniauth.origin'] = "/notes/liked"
    request.env['omniauth.auth'] =  OmniAuth.config.mock_auth[:github1]
    # sign up
    post :create
    assert_redirected_to "/notes/liked?_=#{Time.now.to_i.to_s}"
  end
```

Now I am noticing that the `_` parameter is sometimes causing travis to fail at the `    assert_redirected_to "/notes/liked?_=#{Time.now.to_i.to_s}"` line. This happens because there is a slight variation between the `Time.now` parameter where the test redirects and the `Time.now` that the test compares the url to. Here is an example of the Travis error:
```
FAIL["test_user_that_links_provider_to_existing_account_should_not_be_redirected_to_dashboard_on_oauth_signup_for_Google_provider", #<Minitest::Reporters::Suite:0x00005573a6e48120 @name="UserSessionsControllerTest">, 21.083390820999966]

 test_user_that_links_provider_to_existing_account_should_not_be_redirected_to_dashboard_on_oauth_signup_for_Google_provider#UserSessionsControllerTest (21.08s)

        Expected response to be a redirect to <http://test.host/notes/liked?_=1579461863> but was a redirect to <http://test.host/notes/liked?_=1579461862>.

        test/functional/user_sessions_controller_test.rb:344:in `block in <class:UserSessionsControllerTest>'
```

As you can see, the user is redirected to `http://test.host/notes/liked?_=1579461862` but there is a very small difference between that time (1579461862) and the time when the test is run (1579461862). This is failing certain prs like https://github.com/publiclab/plots2/pull/5666/.

Should I open a pr to fix this or is the `Time.now` parameter useful @publiclab/community-reps?

**Comment by SidharthBansal** [comment]
@jywarren

**Comment by SidharthBansal** [comment]
@cesswairimu what are your views

**Comment by cesswairimu** [comment]
Wow..this is great investigation, makes sense because the redirection time is different to the time we do the assertion. Do we need the timestamp on the assertion?
Could just doing `assert_redirected_to "/notes/liked` still work? because all we need is the redirected url right? or am I missing something?

**Comment by Uzay-G** [comment]
Thanks! No unfortunately that doesn't work. It needs to be exactly the redirected url with parameters. Maybe I could use regex to match the expression?

**Comment by cesswairimu** [comment]
ooh I see..maybe we could try another assertion..
something like `assert_equal request.path, '/notes/liked'` not sure if its request.path or  request.base_url, I need to check that up..not certain it will work though

**Comment by Uzay-G** [comment]
I tried that wasn't working perfectly. This does though:
`assert @response.redirect_url.include? "/notes/liked"`

I will open a pr :+1:

**Comment by SidharthBansal** [comment]
Great

**Comment by cesswairimu** [comment]
Thanks @Uzay-G for the fix :raised_hands: ...in the spirit of solving travis failures I have created a tracking issue where we can track all the tests that fail on travis but pass on some instances/locally, here https://github.com/publiclab/plots2/issues/7315 and hopefully w can get all of them sorted out. Thanks @Uzay-G and @SidharthBansal
