### ISSUE TITLE
Line on header at width 768px

### ISSUE THREAD

**Issue by NitinBhasneria** [publiclab/plots2#7312]
### Please describe the problem (or idea)
1. A line is showing on the header of grey colour which is not looking good in terms of UI and need to be fixed.
2. The menu icon is difficult to see so the border width should be more.
> What did you expect to see that you didn't?
The line should not be there.
Icon menu should be clearly seen.
### Please show us where to look

https://publiclab.org/
On the header at width of the device = 768px.

### What's your PublicLab.org username?
nitin_tech
> This can help us diagnose the issue: 
Need to check the UI at width equals to 768 px and need to fix
## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders
![Screenshot from 2020-01-20 20-57-19](https://user-images.githubusercontent.com/44112080/72747920-f014e800-3bdb-11ea-9542-513a26ea2c4a.png)

**Comment by NitinBhasneria** [comment]
@jywarren  @SidharthBansal  please review this issue

**Comment by SidharthBansal** [comment]
Great catch. Are you willing to fix this?

**Comment by NitinBhasneria** [comment]
Yea, I'll fix this by today.

**Comment by cesswairimu** [comment]
Hey @NitinBhasneria, I am not clear on the issue here..could you please elaborate? thanks

**Comment by NitinBhasneria** [comment]
@cesswairimu Actually there was a slight line on the header due tlh wrong media query limit. As you can see the screenshot.

**Comment by cesswairimu** [comment]
@NitinBhasneria I am sorry I think we fixed this in another PR looks good now. what do you think? 
![Screenshot from 2020-02-29 23-22-45](https://user-images.githubusercontent.com/17081074/75614515-9bee1380-5b4a-11ea-8eb6-e2022c0adc63.png)

**Comment by NitinBhasneria** [comment]
No @cesswairimu It is still there have a look.
![Screenshot from 2020-03-01 12-16-18](https://user-images.githubusercontent.com/44112080/75621109-857da180-5bb6-11ea-8f29-83db49701ace.png)

**Comment by cesswairimu** [comment]
My bad gotcha
