### ISSUE TITLE
Using the Editor's buttons causes issues with parsing Markdown

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#7320]
Recently when I was posting an activity on Public Lab. I used the activity template here:

<img width="1085" alt="Screen Shot 2020-01-21 at 1 38 15 PM" src="https://user-images.githubusercontent.com/7490478/72832700-64d73900-3c53-11ea-9024-c75095ea802b.png">

This template uses the new editor, and I only used the radio buttons for drafting this piece. However, after I hit publish, I noticed there were a few things that didn't come through on the editor -- for example, things I bolded or italicized didn't come through when I hit publish. Some of them instead looked like they had misplaced markdown. Here is part of the post as it came through on email after I first hit publish where you can see some of the markdown: 

<img width="846" alt="Screen Shot 2020-01-21 at 1 47 36 PM" src="https://user-images.githubusercontent.com/7490478/72833438-d794e400-3c54-11ea-8439-418733381af9.png">

This only happened to some of my material it, but when I went back to fix it, the editor alerted me I was using markdown and kept pushing my page to the bottom and asking me if I wanted to change the formatting.  I was able to manually fix most of it by deleting the markdown, retyping the material and using the buttons, but not all of it was fixable, for example the extra lines with link symbols I can't seem to get rid of: https://publiclab.org/notes/stevie/01-17-2020/how-to-collect-a-water-sample.

**Comment by jywarren** [comment]
Hi, i think this could be linked to https://github.com/publiclab/PublicLab.Editor/issues/307, and I think @VladimirMikulic may have filed a fix for it. If so, we may just need to bump the version in the Editor and get the latest version into plots2 here?

**Comment by jywarren** [comment]
I'm sorry i think perhaps it was @IgorWilbert !

**Comment by VladimirMikulic** [comment]
@jywarren I haven't filed a fix for it, yet.

**Comment by SidharthBansal** [comment]
@VladimirMikulic are you willing to fix it?

**Comment by SidharthBansal** [comment]
@VladimirMikulic also kindly update the issue title so that folks can easily detect the issue from the title.
Thanks all

**Comment by VladimirMikulic** [comment]
@SidharthBansal I've tried to reproduce the issue, but the template works fine for me.
@steviepubliclab can you confirm that issue is still present? We had some changes in the editor.

**Comment by SidharthBansal** [comment]
@VladimirMikulic can you please check the production ?
If issue is not present then we can close this

**Comment by VladimirMikulic** [comment]
I've checked in production and locally and wasn't able to reproduce it.
