### ISSUE TITLE
Reply to comment by email not working

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#7321]
Reporting re: @steviepubliclab and possibly related to #5668 - 

> Hi great! I just tried to reply by email to test this out. I was replying to a comment on a research note and it didn't go thorough. Perhaps this is a different issue. This is what it looked like on my email:

![image](https://user-images.githubusercontent.com/24359/72838046-905f2100-3c5d-11ea-985c-ab291ea165e1.png)

> It didn't show up on this research note: https://publiclab.org/notes/nshapiro/09-26-2016/build-a-plant-based-air-purifier#comments

This is a priority issue, and cc'ing @icarito to see if we can check the mail queue in general, or otherwise track this message?

**Comment by tawahpeggy** [comment]
i will like to work on this issue if possible

**Comment by tawahpeggy** [comment]
@cesswairimu please assign this issue to me @tawahpeggy

**Comment by tawahpeggy** [comment]
i will also look at the 2 issues mentioned under this one by @jywarren  and @cesswairimu.

**Comment by cesswairimu** [comment]
Go ahead @tawahpeggy, thanks

**Comment by tawahpeggy** [comment]
Ok @cesswairimu thanks for the go ahead.

**Comment by tawahpeggy** [comment]
@cesswairimu i have studied the issue stated here but i have reasons to
think it has been sorted out already cause reply to comment by email is
working fine. except i havent gotten the point why the issue was written.
please any help will be appreciated.

**Comment by cesswairimu** [comment]
Hey @steviepubliclab @ebarry could you please confirm if this is still happening in production? Thanks

**Comment by jywarren** [comment]
Let's close this up for now, thank you! If it recurs we can re-open. Thank you!!!
