### ISSUE TITLE
Popup doesn't disappears on 'Manage Subscriptions page'

### ISSUE THREAD

**Issue by sssash18** [publiclab/plots2#7355]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
The share popup on manage subscriptions page does not diappears on clicking somewhere else on the screen.This creates inconvenience for the user
![Untitled_ Jan 27, 2020 5_27 PM](https://user-images.githubusercontent.com/57896905/73173140-af145a80-412a-11ea-9e63-4d55dbe971a5.gif)

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by sssash18** [comment]
@publiclab/reviewers Please share your views on this

**Comment by JanviMahajan14** [comment]
Hi @sssash18 i am new in open source . Can I work on this issue?

**Comment by sssash18** [comment]
@JanviMahajan14 If you are new to publiclab ,I would recommend you to first do a "first timers only issue " first and get familiar with the environment. That would help you a lot.Thanks

**Comment by imajit** [comment]
Hey I think the same problem is there when you click topics button 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/38528640/73183810-6e740b80-4141-11ea-9dd2-8abf6fdfa150.gif)

**Comment by Odisseuss** [comment]
Hello @sssash18, has anyone taken up the issue yet?

**Comment by sssash18** [comment]
@Odisseuss It's not taken yet,are you willing to do it?

**Comment by imajit** [comment]
@sssash18 i would like to work on this if no one has claimed it .

**Comment by Odisseuss** [comment]
@sssash18 would be glad to

**Comment by sssash18** [comment]
> @sssash18 i would like to work on this if no one has claimed it .

@Odisseuss has already approached it before.You could try other issues available.Thanks for your interest

**Comment by sssash18** [comment]
> @sssash18 would be glad to

Yeah you can go ahead
