### ISSUE TITLE
View on a map from notes pages results in "NaN" in URL

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#7357]
Hi @nstjean - i think maybe this is an unintended effect, but I see "view on a map" on pages like this:

https://publiclab.org/notes/warren/11-16-2019/mashapaug-pond

But it leads to this URL, probably because we aren't getting a proper slug from it, since it's not a wiki page? 

https://publiclab.org/map#NaN/41.79/-71.43

But, I'm not sure about that. I guess we should be using `node.id` on notes, since they require more than the slug as a unique id. What do you think?

This seems like it'll be a relatively simple fix, would you mind taking a look? 

All the buttons across the site now look AMAZING!!! 🎉

**Comment by nstjean** [comment]
Ohh I think it's because there's no zoom saved for that page! I'll have to hardcode a default zoom level. I'll get a PR for this today!

**Comment by jywarren** [comment]
Oh, awesome. Thank you so much!
