### ISSUE TITLE
Refresh page upon adding location tags

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#7359]
I heard from someone who was confused as to why the map didn't appear upon adding location tags, so I think we should initiate a page refresh when that happens -- what do you think, @nstjean @crisner -- does this makes sense? We could just do this in JS after hearing a success for the tag POST? 

Thanks! Just a thought that this might be a better user experience!

**Comment by nstjean** [comment]
Yes I agree! I think it should refresh after adding any power tag, because things like `place:xx` will change the view of the page as well.

**Comment by jywarren** [comment]
ah, good thought! can you point to the code where we submit these? I think you did a lot of great work to consolidate this code and perhaps it's a one-line change!

**Comment by crisner** [comment]
> I heard from someone who was confused as to why the map didn't appear upon adding location tags, so I think we should initiate a page refresh when that happens

Sounds good to me.

**Comment by nstjean** [comment]
This is the function that is called when tags are successfully added:
https://github.com/publiclab/plots2/blob/f6e37826002aef04843a6f448c3dedef5ae2e35b/app/assets/javascripts/tagging.js#L71-L89

I believe `tag[0]` is the tag name.
We can check for specific power tag names: `if (!!tag[0].split(':')[0].match(/^(lat|lon|place)$/)) { }`

**Comment by NitinBhasneria** [comment]
@jywarren I would like to work on this issue. May I ?

**Comment by nstjean** [comment]
@NitinBhasneria Go ahead! If you need help just let me know.

**Comment by NitinBhasneria** [comment]
ok, I will be working on this.
thanks @nstjean

**Comment by NitinBhasneria** [comment]
by adding the location.reload(true); in the code given by you @nstjean it will work fine.
What do you think?

**Comment by nstjean** [comment]
Yes, that sounds good!
