### ISSUE TITLE
Replace all uses of wiki.slug in favor of wiki.path

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#736]
We no longer use `node.slug` and it's redundant with the `node.path` field, so we should remove all instances from the codebase. Here they are:

```ruby
app/views/wiki/show.html.erb:  <div class="alert alert-warning"><%= raw t('wiki.show.revision_from', :time => @revision.created_at.to_s(:long)) %> <a href="/wiki/revisions/<%= @node.slug %>"><%= t('wiki.show.view_all_revisions') %></a></div>
app/views/wiki/show.html.erb:        <li><a href="/talk/<%= @node.slug %>"><i class="fa fa-comments-o"></i><span class="hidden-xs hidden-sm"> <%= t('wiki.show.talk') %></span></a></li>
app/views/wiki/show.html.erb:        <li><a href="/wiki/revisions/<%= @node.slug %>"><span class="hidden-xs"><%= @node.revisions.length %> </span><i class="fa fa-list"></i></a></li>
app/views/wiki/show.html.erb:    <% slug = @node.power_tag('parent') %>
app/views/wiki/show.html.erb:    <% parent = DrupalNode.find_by_slug(slug) %>
app/views/wiki/show.html.erb:          <p><a href="/tag/<%= @node.slug %>"><%= raw t('wiki.show.more_research', :tag => @node.slug) %> &raquo;</a></p>
app/views/wiki/edit.html.erb:      <li><a href="/wiki/<%= wiki.slug %>"><i class="fa fa-book"></i> <%= wiki.title %></a></li>
app/views/wiki/edit.html.erb:      <% if @node.path %><li><a href="/wiki/revisions/<%= @node.slug %>"><%= t('wiki.edit.revisions_for_this_page') %></a></li><% end %>
app/views/wiki/revisions.html.erb:      <li><a href="/wiki/<%= @node.slug %>"><%= t('wiki.revisions.view') %></a></li>
app/views/wiki/revisions.html.erb:      <li><a href="/wiki/edit/<%= @node.slug %>"><%= t('wiki.revisions.edit') %></a></li>
app/views/wiki/revisions.html.erb:      <li class="active"><a href="/wiki/revisions/<%= @node.slug %>">Revisions (<%= @node.revisions.length %>)</a></li>
app/views/talk/show.html.erb:<div><iframe src="https://pad.publiclab.org/p/<%= @node.slug[0,50] %>" style="width: 100%; height:800px;"><p><%= t('talk.show.try_direct_link', :url1 => 'https://pad.publiclab.org/p/'+@node.slug[0,50]) %></p></iframe></div>
app/models/drupal_node.rb:  attr_accessible :title, :uid, :status, :type, :vid, :cached_likes, :comment, :path, :slug
app/models/drupal_node.rb:  friendly_id :friendly_id_string, use: [:slugged, :history]
app/models/drupal_node.rb:    slug.blank? || title_changed?
app/models/drupal_node.rb:    self.slug[0..5] == 'place/'
app/models/drupal_node.rb:  def self.find_root_by_slug(title)
app/controllers/talk_controller.rb:    @node = DrupalNode.find_by_slug params[:id]
app/controllers/wiki_controller.rb:      @wikis = DrupalTag.find_pages(@node.slug,30) if @node.has_tag('chapter') || @node.has_tag('tabbed:wikis')
app/controllers/wiki_controller.rb:    @node = DrupalNode.find_root_by_slug(params[:id])
app/controllers/admin_controller.rb:        redirect_to "/wiki/revisions/<%= @node.slug %>" + '?_=' + Time.now.to_i.to_s
```

Note that each time, we can't just use `path` -- If a wiki has slug `hello-world`, it's supposed to have a path of `/wiki/hello-world`. So we should make a new method on `DrupalNode` like:

```ruby
def slug_from_path
  self.path.split('/').last
end
```

And then replace all of the above instances of `node.slug` with `node.slug_from_path`.

Also, `find_by_slug` and `find_root_by_slug` will have to be rewritten to search by `path` as well -- adding `/wiki/` back in, or potentially searching with a SQL wildcard like `%` in front of the `slug_from_path` result. I'm happy to offer ideas/help on that too, and it could become a separate issue for simplicity.

**Comment by jywarren** [comment]
We should try running a query in the production console to test how many wiki pages don't have a slug that matches their path.

**Comment by 500swapnil** [comment]
Hey I would like to help with this.

**Comment by jywarren** [comment]
That'd be great -- but perhaps one issue at a time? Thank you!

**Comment by 500swapnil** [comment]
I'm done with the other issue. How do I proceed with this one?

**Comment by jywarren** [comment]
This one is complex, but we should work bit by bit. Some of the above listed instances of `slug` can just be replaced pretty simply -- like:

`app/views/wiki/edit.html.erb:      <li><a href="/wiki/<%= wiki.slug %>"><i class="fa fa-book"></i> <%= wiki.title %></a></li>`

can just become:

`app/views/wiki/edit.html.erb:      <li><a href="<%= wiki.path %>"><i class="fa fa-book"></i> <%= wiki.title %></a></li>`

But there are ideas above for how to convert more complex ones. Typically, a slug would look like:

`some-string`

and a path would look like:

`/wiki/some-string`

Make sense?

**Comment by 500swapnil** [comment]
Yes I understand. I will start by replacing the instances.

**Comment by jywarren** [comment]
Super! Thanks! 👍

**Comment by 500swapnil** [comment]
<% slug = @node.power_tag('parent') %>
slug.blank? || title_changed?
<% parent = DrupalNode.find_by_slug(slug) %>
How will I convert these to path?

**Comment by jywarren** [comment]
Where are they from? `app/views/wiki/show.html.erb`? Can you look at the context of that and see how (and whether) you need to convert from a path to a slug or back?

**Comment by 500swapnil** [comment]
Yes the first 3 are from app/views/wiki/show.html.erb
And I can't understand how we can convert these to path.

**Comment by jywarren** [comment]
Ah, i see -- most instances on that page could use the `node.slug_from_path` method in DrupalNode I proposed above. But this one is different:

```ruby
    <% slug = @node.power_tag('parent') %>
    <% parent = DrupalNode.find_by_slug(slug) %>
```

Here, we're trying to find a parent by its slug, but really we could just assemble a "path" and search by that. So:

```ruby
    <% parent = DrupalNode.find_by_path("/wiki/" + @node.power_tag('parent')) %>
```

does that make sense?

**Comment by jywarren** [comment]
Thanks for your persistence and hard work!

**Comment by 500swapnil** [comment]
Yeah I understand that. Thank you!
And what about the slugs in drupal_node.rb?

**Comment by jywarren** [comment]
I see two that'll need work:

```ruby
app/models/drupal_node.rb:    self.slug[0..5] == 'place/'
```

For this one, you could do `self.path[0..6] == '/wiki/place'` -- make sense?

```ruby
app/models/drupal_node.rb:  def self.find_root_by_slug(title)
```

This one, I think it makes more sense in context:

```ruby
  def self.find_root_by_slug(title)
    DrupalNode.where(path: ["/#{title}"]).first
  end
```

so we're already searching by path, right? I think we could just search the codebase for where `find_root_by_slug` is used, and switch to just `DrupalNode.find_by_path()` -- make sense?

**Comment by 500swapnil** [comment]
Okay I have done as much as I understood! Have a look. #1101

**Comment by jywarren** [comment]
Great, we'll see if it passes tests and there may be more followup once we see what happens there. Thank you! 🎉

**Comment by 500swapnil** [comment]
It didnt pass the tests.
