### ISSUE TITLE
Missing Email & Website info in Author field of package.json

### ISSUE THREAD

**Issue by vinitshahdeo** [publiclab/plots2#7361]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process. 

> **The author field in `package.json` has two optional fields i.e. email and website which is missing. Please check [this](https://docs.npmjs.com/creating-a-package-json-file#author-field).**

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [package.json](https://github.com/publiclab/plots2/blob/master/package.json) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
- "author": "Public Lab",
+ "author": "Public Lab <web@publiclab.org> (https://publiclab.org)"
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by JanviMahajan14** [comment]
Hi @vinitshahdeo . Can I take up this issue?

**Comment by mdjaved1** [comment]
Hi @vinitshahdeo  I would like to take up this issue as well if its possible

**Comment by vinitshahdeo** [comment]
@JanviMahajan14 @mdjaved1 Thanks for showing your interest. I just had a look at your profile. You guys don't seem to be beginners. **Can we please keep this issue for absolute beginners?**

**Comment by JanviMahajan14** [comment]
@vincegando Sure! :+1:

**Comment by Odisseuss** [comment]
Hello @vinitshahdeo. This would be my first ever contribution on an open source project. Can i take up the issue?

**Comment by vinitshahdeo** [comment]
@Odisseuss Thanks for showing your interest. You can take up this issue but if you feel like you can take up other issues, I'd recommend you leave this as you're not new to GitHub. I'm targeting someone who's an absolute beginner. Anyways, you can proceed with this issue if this is going to be your first-ever contribution.

**Comment by Odisseuss** [comment]
@vinitshahdeo Okay, i will search for something more suitable, and leave this for real beginners :).

**Comment by zerozeynep** [comment]
Hi, @vinitshahdeo can i take it up?

**Comment by vinitshahdeo** [comment]
Hello @zerozeynep, Thanks for your interest. I viewed your profile, you're capable of resolving a few better issues. I've opened this for absolute beginners. Mind finding some other issue for you, and leave it for beginners?

**Comment by dragonwarp** [comment]
Can I claim this issue?

**Comment by vinitshahdeo** [comment]
@dragonwarp Yes, please go ahead.

**Comment by dragonwarp** [comment]
It seems I managed to format the pull according to the standards set forward in this project. Are the standards, speaking in a strictly rough way, similar across projects or are they unique for every particular open source project?
