### ISSUE TITLE
Add "status" field to /comments page, viewable by admins/moderators only

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#7362]
https://publiclab.org/comments has tools to spam individual comments, shown to admins, here:

https://github.com/publiclab/plots2/blob/aa3b8644e365080e264e73590529ff03bb63cb08/app/views/comments/_comments.html.erb#L36-L47

Let's add a small indicator of the current status of the comment there too, as it's ambiguous!

Let's have the status shown just above lines 37 and 40 in this code excerpt, with `Status: <%= comment.status %>` so that we cover each possible condition. 

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by keshavsethi** [comment]
@jywarren I have created a PR for this issue, please review

**Comment by guptadiksha307** [comment]
Hi, I'm new to open source and I would like to contribute to this issue. May I?

**Comment by SidharthBansal** [comment]
There is an outstanding PR. Can you please find any other issue?
