### ISSUE TITLE
Weekly community Check-In #46 - "End of GCI , start for SoCs."

### ISSUE THREAD

**Issue by pydevsg** [publiclab/plots2#7364]
Hi everyone 👋

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. 💯

## End of GCI :tada: 
Last week we successfully ended GCI competition for this year , saw numerous contribution from the participants (specially in this repository) during GCI phase. We are happy to have more valuable members in our community :blush: . Thanks to all the participants and also to the mentors for  making this event grand. :smile:

## <ins>SoC</ins>
With approaching **RGSoC** , **Outreachy** and most importantly **Google Summer of Code(GSoC)** , we are in seek of active mentors for these competitions who are well versed with Public lab ecosystem. @jywarren has already posted about the same here - https://github.com/publiclab/plots2/issues/7360 . If you are one of them who is wiiling to mentor ,feel free to mention there.

Keep contributing to Public Lab :rocket: . 
**Thanks everyone for making Public Lab so reliable . Hope it remains on 🔝 as usual 🎉**

**Comment by pydevsg** [comment]
@jywarren , @cesswairimu , @SidharthBansal , @gauravano and @ebarry

**Comment by pydevsg** [comment]
@CodeSarthak , @Uzay-G , @VladimirMikulic , @HarshKhandeparkar , @chen-robert , @LeoDog896, @anthony-zhou and all other GCI students , take a bow :clap:

**Comment by pydevsg** [comment]
Mentors - @ananya , @keshav234156  , @IshaGupta18 , @pydevsg , @debck , @rexagod , @sidntrivedi012 , @divyabaid16 , @subhahu123

**Comment by pydevsg** [comment]
@Tlazypanda, , @pcube99, @nstjean, @imajit, @nicoleiocana, @simonastefan, @dependabot-preview[bot], @giovannyg, @jywarren, @NitinBhasneria, @seabl, @priyanka-choubey, @anthony-zhou, @hknowlton, @Bhanu-mbvg, @pythongiant, @EmirVatric, @KateAnn19, @daemon1024, @abdiclear, @Electrickal, @crisner, @shipcy, @sunguru98, @keshavsethi, @gxite


@Rishabh570 @sashadev-skyl @vaibhavmatta @shubhscoder @aSquare14 @sidntrivedi012 @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77 @milaaraujo @kevinzluo @shipcy @developer22-university @keshavsethi @emilyashley @smarty1palak @daemon1024

**Comment by cesswairimu** [comment]
Great :tada: thanks for opening this @pydevsg

**Comment by VladimirMikulic** [comment]
Thank you very much @pydevsg :+1:

**Comment by Uzay-G** [comment]
> @CodeSarthak , @Uzay-G , @VladimirMikulic , @HarshKhandeparkar , @chen-robert , @LeoDog896, @anthony-zhou and all other GCI students , take a bow clap

Thanks @pydevsg! It's been a fun competition and I'm really glad I participated with PL :+1:

**Comment by pydevsg** [comment]
Thanks evreyone :smile:

**Comment by CodeSarthak** [comment]
Thanks a lot this amazing community which has given me more than I could give it 😄

**Comment by jywarren** [comment]
@CodeSarthak never! everyone gives and gets here! 🙌 

Glad to see you all!

**Comment by nstjean** [comment]
I wish I could have spent more time with the CGI students, what great work was accomplished!!

**Comment by SidharthBansal** [comment]
**Google Code In 2019-20 Mentorship Prize Results**
Hello everyone, this year was EPIC :rocket:. Over 127 students participated and 35 mentors participated this year :tada:. Around 11 repositories participated this year 💯 . We completed the `Login/Sign Up and Oauth` Milestone and `System Tests` 🎖  for entire plots2 repository with the help of @VladimirMikulic and @Uzay-G. Addition to this, please check the pulse monthly
![image](https://user-images.githubusercontent.com/20972099/73378287-61445180-42e6-11ea-844f-585ce40e4f85.png)
This is greater than SoC programs we had earlier. 💯  This is just for plots2. 
Similar progress for other repositories like leaflet, LDI, Editor, MK, SWB, IS and many more.
We are proud to have you all this winter. We have already filled the results for students. Google will be announcing them on 10 February.
Regarding mentors, we will be happy to announce them now 🎉 🎉 🎉 
@keshav234156 GCI GRAND PRIZE SUMMIT + PL KIT
@ananyaarun GSOC SUMMIT(If GCI mentor is invited, in 2019 gci mentor was invited. We hope this year also, GCI mentor is invited) + PL Kit
Following mentors will be awarded a PL Kit for their contribution at Public Lab
Ananya, Keshav, Debashish, Mayank Pathela, Sasha, Isha, Sudipto and Harman Jolly. 🥇 
I have sent an email for the PL kits. Kindly order that using the coupon code I emailed you all.
Thanks and let's start with GSoC and outreachy 🚀 
Let's make it more encouraging and collaborative than past years

**Comment by IshaGupta18** [comment]
This is just amazing! Congratulations to all the mentors!!! :tada:  Let's begin GSoC and Outreachy with a bang and make it an even bigger success this year! :heart:

**Comment by Uzay-G** [comment]
:+1:! It's been awesome working on GCI with you all! :tada:

**Comment by debck** [comment]
Congratulations @keshav234156 and @ananyaarun and all other mentors. It was really an awesome experience 🎉 🎉

**Comment by jywarren** [comment]
Hooray!!!! 💯 thanks so much to everyone who made this GCI wonderful! 🎉 🙌

**Comment by subhahu123** [comment]
@jywarren  Is community-toolbox project in included in this year gsoc ?
i was an applicant for that last year but didn't got chance in it ....

**Comment by CoderJolly** [comment]
Congratulations @keshav234156 and @ananyaarun for being the top performers !!! 🎉🎉
Special thanks to all maintainers @jywarren @cesswairimu @gauravano for being at the judging panel 💯. And lastly @SidharthBansal for being an awesome admin at GCI👍.

**Comment by Dhiraj240** [comment]
Congratulations to the winner @keshav234156  and our mentor @ananyaarun and everyone associated with it.

**Comment by cesswairimu** [comment]
Hats off :tada: :tada: :tada:  to all the gci students and mentors for the amazing work you have done. You all made gci successful and fun. Thanks

**Comment by SidharthBansal** [comment]
Who is going to open next weekly check-in for community reports?

**Comment by SidharthBansal** [comment]
@emilyashley

**Comment by SidharthBansal** [comment]
Moved to #7429
