### ISSUE TITLE
Map control buttons cover up the nav message window

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#7376]
I noticed today that the buttons on maps are peeking out overtop of the message at the top of the screen. Everything slides below the navbar, as it should, but not under the message that's above the navbar:
https://publiclab.org/wiki/inline-maps

![FireShot Capture 245 - 🎈 Public Lab_ Inline maps - publiclab org](https://user-images.githubusercontent.com/49460529/73299959-2c4cd780-41de-11ea-8c58-5023330ab26c.png)

![Peek 2020-01-28 14-55](https://user-images.githubusercontent.com/49460529/73300038-4dadc380-41de-11ea-835b-316a05a09b31.gif)

This can probably be fixed with adding or increasing `z-index` for the div at the very top of the screen, CSS can be added to https://github.com/publiclab/plots2/blob/master/app/assets/stylesheets/style.css

**Comment by alti21** [comment]
Hi, I am a first timer, can I fix this?

**Comment by keshavsethi** [comment]
@nstjean can i try this if it is still open

**Comment by nstjean** [comment]
Hi @alti21 have you completed a first-timers-only issue yet? We highly recommend doing one of those first so you can get familiar with how pull requests work!

**Comment by nstjean** [comment]
@alti21 Ok I just checked, you haven't done a PR yet. So do you feel comfortable jumping in to tackle this? If so you may attempt it, just ask for help if you need it!

**Comment by alti21** [comment]
I would like to attempt it, yes. Thanks!

**Comment by nstjean** [comment]
Ok! Just let me know if you have trouble!

**Comment by alti21** [comment]
i am actually having trouble installing it locally, will I be able to install the prereqs on windows?

**Comment by alti21** [comment]
Actually I will leave this issue, as I do not have experience with Ruby

**Comment by nstjean** [comment]
Okay! This repository doesn't play nice with Windows, I tried but ended up installing Linux to work on. Many of our other repositories are Javascript, you can take a look!

**Comment by nstjean** [comment]
@keshavsethi Do you still want to try this out?

**Comment by keshavsethi** [comment]
@nstjean I have open a PR, Please review it 
Thanks
