### ISSUE TITLE
Copy existing label descriptions from documentation into github label description field. 

### ISSUE THREAD

**Issue by emilyashley** [publiclab/plots2#7377]
Found this [awesome label documentation](https://github.com/publiclab/plots2/blob/master/doc/LABELS.md) when onboarding with @jywarren today.

Making a little issue note for myself as I'm doing some repo onboarding and housekeeping to include some of these descriptions into the description field provided by github [here](https://github.com/publiclab/plots2/labels) so this knowledge & understanding spreads :) Some of these require a little truncation as there is a character limit. 

- [x] `help-wanted`
- [x] `first-timers-only`
- [x] `fto-candidate`
- [x] `bug`
- [x] `enhancement`
- [x] `break-me-up`
- [x] `more-detail-please`
- [x] `design`
- [x] `documentation`
- [x] `testing`
- [x] `outreach`
- [x] `brainstorm`

I'll probably need feedback on what, if anything, to write as description for program & event specific labels.

**Comment by emilyashley** [comment]
Ok copied the existing ones over :+1: Leaving this issue open for a day or two incase additional comments arise.

**Comment by jywarren** [comment]
Thank you! So great!

**Comment by emilyashley** [comment]
Cool, closing :)
