### ISSUE TITLE
Sorting does not work in digest

### ISSUE THREAD

**Issue by sssash18** [publiclab/plots2#7390]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
Sorting doe not work in digest
**Current Behaviour**
![sorting](https://user-images.githubusercontent.com/57896905/73456131-5ac1e280-4397-11ea-8a9d-5fcc23756e92.gif)

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by sssash18** [comment]
@publiclab/reviewers I would like to implement this.Can I proceed?

**Comment by SidharthBansal** [comment]
Great Catch. Please go ahead
