### ISSUE TITLE
Password confirmation box in wrong place

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#7391]
On the Edit Profile page `/profile/edit` I see username, email, Change your password, Current password, and Confirmation.

Confirmation says "Retype your password to confirm". But this is next to "Current password". So what are we confirming, the new password or the old one? We should be confirming the new one, to make sure the user knows what they typed in is correct. The old password is being checked against what is in the database, it does not need to be confirmed.

![FireShot Capture 254 - 🎈 Public Lab_ Edit - localhost](https://user-images.githubusercontent.com/49460529/73460216-1ce89e00-4346-11ea-99fe-fcdc119899f9.png)

"Confirmation" should be next to "Change your password".

**Comment by nstjean** [comment]
I tested it out, the logic is checking the value against the new password. So the box just needs to be moved!

Also I noticed that the tab order is incorrect and needs to be fixed.

**Comment by DouglasLutz** [comment]
@nstjean I can work on this one

**Comment by nstjean** [comment]
@DouglasLutz Go for it! :+1:
