### ISSUE TITLE
2020 Community-wide survey! This is for YOU 🎉🎈

### ISSUE THREAD

**Issue by emilyashley** [publiclab/plots2#7406]
## Community Survey
We've been putting together a community survey with @ebarry, @jywarren, @SidharthBansal, @sagarpreet-chadha  more on behalf of the Public Lab non-profit, and I'd like to ask everyone to take a few minutes to fill it out.

We put a lot into making our community a welcoming place, but we need to better understand what works and what doesn't.

So please, give us your thoughts in this anonymous form -- we'll post the results at the end and we can all learn about ourselves! We'll keep it open until March 27, 2020

https://forms.gle/Z6J3Mrdszm9iFiuv9

**Comment by SidharthBansal** [comment]
@jywarren , @cesswairimu , @SidharthBansal , @gauravano and @ebarry
@CodeSarthak , @Uzay-G , @VladimirMikulic , @HarshKhandeparkar , @chen-robert , @LeoDog896, @anthony-zhou and all other GCI students 
@ananyaarun , @keshav234156 , @IshaGupta18 , @pydevsg , @debck , @rexagod , @sidntrivedi012 , @divyabaid16 , @subhahu123

**Comment by SidharthBansal** [comment]
@Rishabh570 @sashadev-skyl @vaibhavmatta @shubhscoder @aSquare14 @sidntrivedi012 @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77 @milaaraujo @kevinzluo @shipcy @developer22-university @keshavsethi @emilyashley @smarty1palak @daemon1024

**Comment by SidharthBansal** [comment]
@Tlazypanda, , @pcube99, @nstjean, @imajit, @nicoleiocana, @simonastefan, @dependabot-preview[bot], @giovannyg, @jywarren, @NitinBhasneria, @seabl, @priyanka-choubey, @anthony-zhou, @hknowlton, @Bhanu-mbvg, @pythongiant, @EmirVatric, @KateAnn19, @daemon1024, @abdiclear, @Electrickal, @crisner, @shipcy, @sunguru98, @keshavsethi, @gxite

**Comment by Uzay-G** [comment]
Submitted!

**Comment by blurry-x-face** [comment]
Submitted 😄

**Comment by Tlazypanda** [comment]
Submitted! :smile:

**Comment by imajit** [comment]
Submitted !

**Comment by sagarpreet-chadha** [comment]
Done 🎉 😄

**Comment by sssash18** [comment]
Submitted!

**Comment by govindgoel** [comment]
Done!!

**Comment by CoderJolly** [comment]
Done 🎉

**Comment by niravasher** [comment]
Done :smile:

**Comment by keshavsethi** [comment]
Done !!

**Comment by nstjean** [comment]
Done :)

**Comment by HarshKhandeparkar** [comment]
Filled ✍️

**Comment by Rishabh570** [comment]
Done :v:

**Comment by ebarry** [comment]
Hi all, thank you for filling this survey out! So far, we have just **_less than half the number of respondents we had in last year's survey_**, so please, even if you are a very recent member, or shy for any reason, please go ahead and fill out the survey -- there's plenty of questions where you can express that you are new, and it is anonymous. 🌳 🎈 🙏 https://forms.gle/Z6J3Mrdszm9iFiuv9

**Comment by sidntrivedi012** [comment]
Filled already 😃

**Comment by alaxalves** [comment]
Done!

**Comment by gauravano** [comment]
Done!

**Comment by ebarry** [comment]
Thanks all!
