### ISSUE TITLE
Missing Hamburger Menu Icon on Mobile

### ISSUE THREAD

**Issue by z-arnott** [publiclab/plots2#7415]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.
### Problem
The hamburger menu bars icon is missing in the top right corner of the nav-bar on Mobile.
This is because the [font-awesome](https://fontawesome.com/) library has changed its class names.
![image](https://user-images.githubusercontent.com/50159450/73603606-f9467300-4552-11ea-852d-efdf18dddd65.png)

### 📋Solution
Remove this line to remove the old Font-Awesome class name.
![image](https://user-images.githubusercontent.com/50159450/73603542-c354bf00-4551-11ea-9f14-ce48817ee0de.png)

Add this line to add the new Font-Awesome class name.
![image](https://user-images.githubusercontent.com/50159450/73603565-3b22e980-4552-11ea-81a0-0105f99793e6.png)

The Nav-bar should look like this when you're done! :) 
![image](https://user-images.githubusercontent.com/50159450/73603601-e3d14900-4552-11ea-903f-048b6193c473.png)

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by krsudhanshu** [comment]
can I claim this issue?

**Comment by z-arnott** [comment]
@krsudhanshu go ahead!

**Comment by kraken-coder** [comment]
@krsudhanshu have you open a pull request?

**Comment by theOpetunde** [comment]
Have you been able to solve this?

**Comment by krsudhanshu** [comment]
nope!
I haven't open a pull request

**Comment by krsudhanshu** [comment]
Whenever I click on $FILENAME it opens a blank page. Can somebody guide me in this.

**Comment by krsudhanshu** [comment]
Hi there! I did a pull request, but I think it went wrong can someone guide me!
Thanks!!

**Comment by z-arnott** [comment]
Hi @krsudhanshu can you edit your PR with the issue number, #7415 !

And tag publiclab/reviewers in a comment on the PR for them to check it

Thanks :)

**Comment by krsudhanshu** [comment]
hey @z-arnott i am not able to tag them.
Updated the issue number to #7415 .

**Comment by guptadiksha307** [comment]
Hi, Is this issue open?

**Comment by cesswairimu** [comment]
Great catch @z-arnott, Thanks
