### ISSUE TITLE
Translation Missing for Navbar Items

### ISSUE THREAD

**Issue by z-arnott** [publiclab/plots2#7416]
### Please describe the problem (or idea)

What happened just before the problem occurred? Or what problem could this idea solve?
>The problem occurs when you hover over certain items of the NavBar.
All the items in the Community and Tools drop down menus are affected. Newsletter under the About Us menu is also affected.

Why this is happening:
>The path to the translation key within /config/locales/en.yml is referenced incorrectly for some of the menu items. 
The translation keys are missing for other menu items.

### Please show us where to look
>The "translation missing: Community.en" message is visible here
![image](https://user-images.githubusercontent.com/50159450/73604185-775a4800-455a-11ea-90d0-17a64384b686.png)

https://publiclab.org/

###Solution:
>Many of the Items already have keys in the /config/locales/en.yml 
I've added proper path references the items that already have keys.

****

**Comment by z-arnott** [comment]
I'd be happy to add the missing translation keys as well if needed, but I wasn't sure how they should be formatted.

**Comment by jywarren** [comment]
Hi, thank you so much -- i just referenced this when noting there may have been some issues with the string parsing done here. I don't know if you have any availability to help us figure this out? Thanks again for your great work! https://github.com/publiclab/plots2/issues/7798
