### ISSUE TITLE
Removal of edit and new feature button for non admins

### ISSUE THREAD

**Issue by sssash18** [publiclab/plots2#7421]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
Their is no need according to me to display the new features button and edit button and then inform the user that only admins can perform that action.
It would be better if we just remove those buttons.
**Current Behaviour**
![Screenshot 2020-02-03 at 5 41 05 PM](https://user-images.githubusercontent.com/57896905/73652225-63bef680-46ac-11ea-9fcf-4cb5b7965378.png)
**New Behaviour**
![Screenshot 2020-02-03 at 5 38 24 PM](https://user-images.githubusercontent.com/57896905/73652239-6de0f500-46ac-11ea-9ea4-58d332f936c8.png)

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by sssash18** [comment]
@SidharthBansal @nstjean @Uzay-G @VladimirMikulic Please provide your views on this.
I would like to work this out.Thanks

**Comment by VladimirMikulic** [comment]
Displaying a blank page is not a great UI. I would stick with the current layout. @SidharthBansal @Uzay-G?

**Comment by sssash18** [comment]
@VladimirMikulic Actually on my local machine their are no features Only the 'edit' column and 'new issue' button would be removed for nonadmins

**Comment by nstjean** [comment]
@sssash18 You can go to http://localhost:3000/features/new and create a bunch of fake features so it will show up on your computer. I think it would be a great idea to remove the edit and create new button, since non-admins won't get access anyways.

**Comment by sssash18** [comment]
Thanks @nstjean for your help.
Kindly review the changes.
