### ISSUE TITLE
Can't get to page two on spam interface

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#7423]
Hello,
I'm working on moderation, and I can't figure out how to get to the second page of the spam filter dashboard. I think there are more sitting in moderation on the second page. Here's a link:

https://publiclab.org/spam

**Comment by steviepubliclab** [comment]
I was able to get to the second page by adding ?page=2 in the url, but this page will need buttons to do this in the future

**Comment by keshavsethi** [comment]
@steviepubliclab can I try this out ??

**Comment by steviepubliclab** [comment]
yes! thank you

**Comment by keshavsethi** [comment]
@steviepubliclab @SidharthBansal @nstjean  Please review this PR 
Thanks!!
