### ISSUE TITLE
Margin Issue with Sign Up modal

### ISSUE THREAD

**Issue by keshavsethi** [publiclab/plots2#7426]
Sign up modal is not responsive for smartphones
![Screenshot from 2020-02-03 23-16-11](https://user-images.githubusercontent.com/36025262/73677079-87e5fc00-46db-11ea-8b02-cfa2274bc82c.png)

Please Review 
Thanks

**Comment by SidharthBansal** [comment]
Are you willing to help us with this issue?
Similarly for log in modal?

**Comment by keshavsethi** [comment]
yes Sure, i will do this

**Comment by keshavsethi** [comment]
@cesswairimu can we merge this??
