### ISSUE TITLE
Weekly community Check-In #47 - "2020 Contributor Community Survey is Live!"

### ISSUE THREAD

**Issue by emilyashley** [publiclab/plots2#7429]
Hi everyone 👋 I'm Emily Ashley and I wanted to introduce myself -- I'll be working part-time with Public Lab as their staff Full Stack Developer in the New Orleans office  ✨💻 Excited to be here, contribute, and learn more about the community and the awesome folks that make it all that it is! 🙌🙌

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. 💯

## 2020 Software Contributor Community Survey is Live 🎉 
Survey ticket is here: https://github.com/publiclab/plots2/issues/7406
We've been putting together a community survey on behalf of the Public Lab non-profit, and I'd like to ask everyone to take a few minutes to fill it out. We put a lot into making our community a welcoming place, but we need to better understand what works and what doesn't.

So please, give us your thoughts in this anonymous form -- we'll post the results at the end and we can all learn about ourselves! We'll keep it open until March 27, 2020 https://forms.gle/Z6J3Mrdszm9iFiuv9

## **Google Code In 2019-20 Mentorship Prize Results**

Regarding mentors, we will be happy to announce them now 🎉 🎉 🎉 
@keshav234156 GCI GRAND PRIZE SUMMIT + PL KIT
@ananyaarun GSOC SUMMIT(If GCI mentor is invited, in 2019 GCI mentor was invited. We hope this year also, GCI mentor is invited) + PL Kit
Following mentors will be awarded a PL Kit for their contribution at Public Lab
Ananya, Keshav, Debashish, Mayank Pathela, Sasha, Isha, Sudipto and Harman Jolly. 🥇 
I have sent an email for the PL kits. Kindly order that using the coupon code I emailed you all.
Thanks and let's start with GSoC and outreachy 🚀 
GCI Student winners will be announced by Google :rocket: 

## Call for SOC mentorship
We’re looking for mentors for the upcoming SOC projects. Here’s a link to some of the ideas being floated seeking proposals. If you’re interested in mentoring please add your name to this open issue: https://github.com/publiclab/plots2/issues/7360

Keep contributing to Public Lab 🚀 . 
**Thanks everyone for making Public Lab so reliable . Hope it remains on 🔝 as usual 🎉**

**Comment by cesswairimu** [comment]
@rehasantiago, @urvashigupta7, @HashTalmiz, @vinitshahdeo, @nstjean, @dragonwarp, @z-arnott, @VladimirMikulic, @NitinBhasneria, @Tlazypanda, @JanviMahajan14, @sssash18, @mantinone, @DouglasLutz, @seabl, @dependabot-preview[bot], @jywarren, @crisner, @Uzay-G, @shaibrown5, @kostogls, @pcube99, @imajit, @nicoleiocana, @simonastefan, @giovannyg, @priyanka-choubey, @anthony-zhou, @hknowlton, @Bhanu-mbvg, @pythongiant

**Comment by cesswairimu** [comment]
@Rishabh570 @sashadev-skyl @vaibhavmatta @shubhscoder @aSquare14 @sidntrivedi012 @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77 @milaaraujo @kevinzluo @shipcy @developer22-university @keshavsethi @emilyashley @smarty1palak @daemon1024

**Comment by SidharthBansal** [comment]
Hi everyone,
Emily, we are glad to have you onboarded. She will be helping us in many projects for SoC especially, Printability of posts and wiki pages AND Leaflet Environmental Layers (LEL): time slider UI. :rocket:
  
I will be mentoring only plots2, mk and swb related projects 👍

**Comment by alaxalves** [comment]
Hello everyone, I've started working on Spectral Workbench. My goal is to standardize its practices and tool pattern the same as we've done with Plots2 and Mapknitter. Spectral Workbench is an important module for the PL ecosystem and I've realized that it pretty outdated, and present several deprecated modules. I already have some PRs on review at: 
- https://github.com/publiclab/spectral-workbench/pull/480
- https://github.com/publiclab/spectral-workbench/pull/470

PS: @emilyashley and @cesswairimu could you take a look at those

**Comment by nstjean** [comment]
So glad to have you, Emily!!

I'm still working on my Outreachy project with @crisner , getting all the maps working correctly, adding features to LEL, and integrating data from plots2 into our maps!

**Comment by SidharthBansal** [comment]
Great Natalie

**Comment by SidharthBansal** [comment]
and @crisner

**Comment by cesswairimu** [comment]
Thanks everyone for filling the survey and if you haven't yet please do.

Anyone interested in opening next week's check-in?

**Comment by SidharthBansal** [comment]
I think we can include gci student result there?
Any gci student wishing to participate?

**Comment by VladimirMikulic** [comment]
Sorry I didn't understand the "participate" part. Participate in SOC?

**Comment by SidharthBansal** [comment]
You can participate in next community check-in

**Comment by VladimirMikulic** [comment]
I don't think that it would be appropriate that I open this check-in since it will include GCI results and I was a student. Some could say it's a conflict of interest. Maybe some newcomer could do this?

**Comment by nstjean** [comment]
I can do it!

>

**Comment by VladimirMikulic** [comment]
Thanks, @nstjean.

**Comment by SidharthBansal** [comment]
Agreed!

**Comment by cesswairimu** [comment]
Awesome, thanks @nstjean

**Comment by nstjean** [comment]
@cesswairimu @SidharthBansal If there is any information about CGI that I should include can you email it to me? Or should I just post a regular check in?

**Comment by cesswairimu** [comment]
@nstjean nope, gci is over now...you could just mention the survey is still open for the folks that have note filled yet. Thanks

**Comment by nstjean** [comment]
Ok!

**Comment by nstjean** [comment]
New check-in open https://github.com/publiclab/leaflet-environmental-layers/issues/394
