### ISSUE TITLE
Fix the spacing in the read more button

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#7431]
The read more button under the methods url has a spacing issue.
The padding/margin needs to be fixed so that the read more text doesn't overflow out of the button.

> What did you expect to see that you didn't?
![image](https://user-images.githubusercontent.com/33183263/73720405-e1841000-4747-11ea-8828-633c39087f0a.png)

### Please show us where to look

https://publiclab.org/methods

**Comment by Tlazypanda** [comment]
@jywarren can you approve this? Can I take this up?

**Comment by Tlazypanda** [comment]
@VladimirMikulic @cesswairimu @SidharthBansal can I work on this?

**Comment by cesswairimu** [comment]
Hey @Tlazypanda , yeah sure, good catch. thanks
