### ISSUE TITLE
A user able to follow itself

### ISSUE THREAD

**Issue by sssash18** [publiclab/plots2#7434]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
After creating the post the user is able to follow itself. This should not happen.
**Current Behaviour**
![Untitled_ Feb 4, 2020 7_29 PM](https://user-images.githubusercontent.com/57896905/73751417-14002e00-4785-11ea-8966-47c962d13366.gif)

> What did you expect to see that you didn't?
A user must not follow itself

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by sssash18** [comment]
@publiclab/reviewers @SidharthBansal  @VladimirMikulic @Uzay-G  What are your views on it?I would like to solve this.Thanks

**Comment by Uzay-G** [comment]
This is a good idea @sssash18! We should do it

**Comment by VladimirMikulic** [comment]
:+1:
