### ISSUE TITLE
Admin able to ban itself

### ISSUE THREAD

**Issue by sssash18** [publiclab/plots2#7442]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
It is observed that a admin is able to block itself.It could be dangerous in cases when their is just one admin and it is blocked.
**Current Behaviour**
![Untitled_ Feb 6, 2020 12_06 AM](https://user-images.githubusercontent.com/57896905/73872013-ea263480-4874-11ea-8d9c-ff79baa50825.gif)

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by sssash18** [comment]
@SidharthBansal @Uzay-G @VladimirMikulic Please provide your views on it.Can I proceed with it?

**Comment by VladimirMikulic** [comment]
I've just encountered that behaviour. It would be appreciated if you could fix it :)
