### ISSUE TITLE
Displaying of go to top button

### ISSUE THREAD

**Issue by NitinBhasneria** [publiclab/plots2#7454]
At the top of webstie the go to top button should not be displayed which is displaying in this case.

![Screenshot from 2020-02-10 18-53-07](https://user-images.githubusercontent.com/44112080/74153446-a5184e80-4c36-11ea-9664-b00f9326b6d3.png)

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by NitinBhasneria** [comment]
@VladimirMikulic @SidharthBansal please review this.

**Comment by VladimirMikulic** [comment]
That would be a very nice UI improvement :+1: 
@NitinBhasneria you are doing great work!

**Comment by NitinBhasneria** [comment]
Looks like the js file scroll-func.js is not linked so we have to link this file.
@VladimirMikulic do you have some idea where to link this file?

**Comment by VladimirMikulic** [comment]
I see what is the problem. The file `scroll-func.js` is in the root folder.
You should move it to `plots2/app/assets/javascripts`.

After you do that, add an entry in `plots2/app/assets/javascripts/application.js` to make it compile with other scripts.
You could as well format the `scroll-func.js` properly.

Thank you.

**Comment by NitinBhasneria** [comment]
yea, I got it thnx.

**Comment by tawahpeggy** [comment]
i will like to check this issue out and work on it, if possible because i see its still open

**Comment by fiona-byte** [comment]
Hi @NitinBhasneria if this issue is still open, I'd love to work on it

**Comment by shreyaa-sharmaa** [comment]
Hey @tawahpeggy @fiona-byte!
This issue was already solved in #6944 (merged might not be in production yet) and then in #7466. 
You can check out the linked PR for more context. Maybe you can help finding the errors in that PR to get that merged.  

All the best!

**Comment by fiona-byte** [comment]
Thanks a lot @shreyaa-sharmaa

**Comment by cesswairimu** [comment]
@fiona-byte  you can check on https://stable.publiclab.org/  I am checking too

**Comment by cesswairimu** [comment]
Looks like its still displaying, @shreyaa-sharmaa  @fiona-byte  could you please confirm..stable has all the changes on main

**Comment by shreyaa-sharmaa** [comment]
Hey @cesswairimu I can see that too. 

@NitinBhasneria 's PR for the same mentions that it wasn't visible at all then? Strange. :thinking:

**Comment by cesswairimu** [comment]
Yeah that's strange. @NitinBhasneria any ideas what could have gone wrong?

**Comment by fiona-byte** [comment]
Hey @cesswairimu, I can see that too. I'm looking to see what has gone wrong

**Comment by shreyaa-sharmaa** [comment]
Any updates @fiona-byte?

**Comment by TildaDares** [comment]
Resolved in #9588
