### ISSUE TITLE
Need css improvement in https://publiclab.org/methods

### ISSUE THREAD

**Issue by NitinBhasneria** [publiclab/plots2#7458]
PROBLEM
As we can see the padding of the open box not good the read more had been overflow, hence padding needs to be improved.

![free-image-resizer-cropper](https://user-images.githubusercontent.com/44112080/74179087-be36f480-4c62-11ea-96db-8719623cb984.png)

Where to look 
https://publiclab.org/methods
## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by NitinBhasneria** [comment]
@VladimirMikulic @nstjean @SidharthBansal please review?

**Comment by VladimirMikulic** [comment]
This is in progress on #7446.

**Comment by VladimirMikulic** [comment]
Whoops, accidentally reopened it.
