### ISSUE TITLE
Select all button in spam page

### ISSUE THREAD

**Issue by keshavsethi** [publiclab/plots2#7460]
At first Select all button selects all the elements of table but if it is pressed again and again it get disabled as shown
![Screenshot from 2020-02-11 01-06-53](https://user-images.githubusercontent.com/36025262/74183569-3bfefe00-4c6b-11ea-964d-1ba188cb1458.png)

/spam/wiki and /spam 
Thanks

**Comment by NitinBhasneria** [comment]
@keshavsethi can I work on this issue?
