### ISSUE TITLE
Bypass emoji trouble by filtering and converting emoji

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#7469]
For a short-term fix to #3007 and related issues where note and wiki saving fail due to emoji in the title and body, I propose we filter the emoji out and replace them with their `:smiley:` :smiley: text equivalents, which are auto-filtered back into emoji on display. 

This should work for emoji, although not for other unicode which aren't working on the site. 

Code here based on this example: https://github.com/publiclab/plots2/blob/591f59a720c4e173ea4ff07db53f8b64897ffe8e/app/helpers/application_helper.rb#L9-L46

We can use the REGEX provided by `unicode-emoji`, already installed, to replace them, using `gemoji`, also already installed!

* https://github.com/github/gemoji
* https://github.com/janlelis/unicode-emoji

I believe we can do something like this, in the `before_save` filter:

```ruby
require "unicode/emoji"
require "gemoji"

string = "String which contains all kinds of emoji:😴▶️🛌🏽🇵🇹🏴󠁧󠁢󠁳󠁣󠁴󠁿2️⃣🤾🏽‍♀️"

string.match(Unicode::Emoji::REGEX) do |match|
  string.gsub!(match.to_s,  ":" + Emoji.find_by_unicode(match.to_s) + ":")
end
```

We can insert this in an ActiveRecord validation, before we save records ([like we do here](https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L130))

We actually already do this on revisions, here:

https://github.com/publiclab/plots2/blob/b648a8b2cf09d152e99ada65d8d3404ce7cb401b/app/models/revision.rb#L46-L51

Let's add this for node title as well, in node.rb, as well as adding a new `before_save` to `revision.rb` for revision body text. 

We'd love help with this one! cc @cesswairimu @emilyashley @icarito as this should address one major site bug! 🐛 🎉

**Comment by geekychasser** [comment]
@jywarren can i try this ?

**Comment by jywarren** [comment]
Wow that would be super! Please do!

**Comment by geekychasser** [comment]
Following Observations
- Emoji not working in title of research notes
- Emoji not working in title of wiki
- Emoji not working in title of revision
- Emoji not working in body of revision

Although emojis are working in body of wiki and research notes. Can you please share link of the methods used in body of wiki and research notes for emotification ? I will use it for the titles.
After debugging emojis we can move to unicodes. what do you think ? @jywarren @Uzay-G @VladimirMikulic @cesswairimu @ananyaarun @namangupta01 @SidharthBansal

**Comment by jywarren** [comment]
Closing as we've solved emoji database issues now!!!
