### ISSUE TITLE
node revisions in sidebar use node, not revision date

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/plots2#747]
I pulled up [a research note of mine](https://publiclab.org/notes/mathew/06-24-2016/aerial-photography-rigging-needs) and noticed that the "Recent Wiki Pages" sidebar appeared to be displaying older content, and that it had a suspicious number of updates exactly 13 days ago.

![screen_shot_2016-08-29_at_2_27_41_pm](https://cloud.githubusercontent.com/assets/1203280/18068377/e30a64ee-6df5-11e6-8179-19999f7e4bb8.png)

Clicking through, I found that many of these edits were 7-24 months old:

![screen shot 2016-08-29 at 2 37 07 pm](https://cloud.githubusercontent.com/assets/1203280/18068431/1d08f336-6df6-11e6-9ca5-53a8f489b772.png)

![screen shot 2016-08-29 at 2 28 35 pm](https://cloud.githubusercontent.com/assets/1203280/18068436/2465ba06-6df6-11e6-8cc0-8dc61af4eee3.png)

I'm seeing the same issue in Chrome and Firefox, logged in or logged out, so I'm assuming its not browser-specific and is happening on the back end.

**Comment by jywarren** [comment]
oh, good eye -- @ananyo2012's migration updated all records to generate new
slugs 13 days ago, so strictly speaking this is accurate. But perhaps we
could use the latest revision's timestamp instead. For notes, however, we
may need to recover pre-existing updated_at records from the previous db,
but we could check if notes' revisions were affected (maybe not?)

On Mon, Aug 29, 2016 at 5:40 PM, mathew lippincott <notifications@github.com

**Comment by ebarry** [comment]
yeah i see this on the spectrometry pages, and think it would be very
helpful to have the "real" dates.

--

+1 336-269-1539
@lizbarry <http://twitter.com/lizbarry>

**Comment by jywarren** [comment]
Found that node timestamps were changed, but not revision timestamps (I believe). Attempting non-migration fix to display revision timestamps instead of updated node ones. I believe this'll be an easy fix, but fingers X.

**Comment by jywarren** [comment]
Resolved, thankfully!

**Comment by jywarren** [comment]
Reopening -- this reappeared on the FAQ grids -- 15 days: https://publiclab.org/wiki/spectrometry#Frequently+Asked+Questions
