### ISSUE TITLE
Sign up and login popup margin error

### ISSUE THREAD

**Issue by NitinBhasneria** [publiclab/plots2#7482]
PROBLEM
when you open the signup or login in small devices you will see that sign up and login popup ahs unequal and wired top margin although in some devices it is perfect.

To see:
go to the site go to inspect and then responsive select different mobiles devices there you will be the problem

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by NitinBhasneria** [comment]
@VladimirMikulic @cesswairimu @jywarren please approve this I will be working on this then.

**Comment by VladimirMikulic** [comment]
This has been a long time issue. You definitely have my approval.

**Comment by keshavsethi** [comment]
@NitinBhasneria @VladimirMikulic I have made a PR in #7448 
Can you please review this ?
Thanks

**Comment by NitinBhasneria** [comment]
@keshav234156 let the pr be merged then we will check through.
Although the changes you have made are right but this problem has been changed many a times so will check it.

**Comment by keshavsethi** [comment]
@NitinBhasneria Sure!!
Thanks!!
btw its @keshavsethi :)

**Comment by VladimirMikulic** [comment]
@NitinBhasneria it can't be merged before it has been checked :)

**Comment by NitinBhasneria** [comment]
I will check it bt today @keshavsethi @VladimirMikulic

**Comment by cesswairimu** [comment]
solved in https://github.com/publiclab/plots2/pull/7448 . closing this
