### ISSUE TITLE
Sorting in features page

### ISSUE THREAD

**Issue by sssash18** [publiclab/plots2#7485]
**Please describe the desired behavior.**
Describe the solution you'd like.
Currently there is no kind of sorting on features page .It would be benficial if we could sort features based on title or last edited.

**Additional context (optional)**
Feel free to include any applicable: code, screenshots, or gifs.

**Comment by sssash18** [comment]
I would like to implement this @SidharthBansal  @cesswairimu

**Comment by SidharthBansal** [comment]
Great
