### ISSUE TITLE
Change post date on draft to publish date

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#7498]
When someone starts a post on Public Lab it captures the date of the draft was started. Then when it's finally published, it holds the original date. This means it doesn't show up on the top of the feed and new posts end up buried in the history. can we change this so that the data it is published is what is used rather than the date the draft started. here's an example of a post I'm talking about. Was started in August, but posted yesterday. 

https://publiclab.org/notes/WendyBrawer/08-20-2019/how-to-get-street-trees-for-your-community?_=1581707285

@ebarry to follow

**Comment by imajit** [comment]
Hey ! can I work on this ?

**Comment by steviepubliclab** [comment]
Great!   Sounds good.

**Comment by jywarren** [comment]
I think we would need to check if it's a draft becoming a non-draft, and set the timestamp at that moment. I see @imajit made an attempt, let's try to resuscitate this! Thanks, all!

**Comment by Priyaraj17** [comment]
I can take a look in this.

**Comment by TildaDares** [comment]
Resolved in #9989
