### ISSUE TITLE
finalize `status` and `category` names and prompts for guided tagging

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#750]
Just need final tweaks and explanatory links for:

> At what status do you think it is? `request` `proposal` `draft` `in-progress` `review-me` `complete`

We also need "category" and "goal" powertags, then that's it. 

> What [kind of activity]() is it? `build` `verify` `observe` `test-limits` `field-test` `experiment` `monitor`

I'm not so sure about these, but if they have hover popups that explain more, maybe?

**Comment by ebarry** [comment]
@gretchengehrke let's work on this tomorrow once you are back! Friday afternoon HEDWIG session!
