### ISSUE TITLE
Add location button on hover

### ISSUE THREAD

**Issue by keshavsethi** [publiclab/plots2#7503]
Background of Add location button on hover becomes white as shown in the image
/people
![Screenshot from 2020-02-15 21-35-31](https://user-images.githubusercontent.com/36025262/74591136-6ff76c00-503b-11ea-9123-1fde62ff79e0.png)

Thanks!!

**Comment by sssash18** [comment]
@keshavsethi  I would like to do it.

**Comment by sssash18** [comment]
@keshavsethi I would like to convert this issue to a fto. Can I proceed?

**Comment by keshavsethi** [comment]
@sssash18 yeah,make it first timer issue:)
