### ISSUE TITLE
Followers button is not working well

### ISSUE THREAD

**Issue by NitinBhasneria** [publiclab/plots2#7504]
When we click on follower it is expected to show the followers list instead it just reload.

![Screenshot from 2020-02-15 22-02-48](https://user-images.githubusercontent.com/44112080/74591573-f82b4080-503e-11ea-97f7-136ae1fcc73a.png)

We have to make it scroll to the followers list.
here

![Screenshot from 2020-02-15 22-04-22](https://user-images.githubusercontent.com/44112080/74591596-24df5800-503f-11ea-9dc4-d33de29a28a4.png)

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by NitinBhasneria** [comment]
@nstjean @SidharthBansal review it please.

**Comment by keshavsethi** [comment]
Hey @NitinBhasneria please refer to PR #7331 
It is kind of similar to issue mentioned.
@SidharthBansal @nstjean

**Comment by NitinBhasneria** [comment]
@keshavsethi 
yea but webpage should not reload then.
It's ok that after your pr no scroll will be needed but there should also no need of reloading then.

**Comment by NitinBhasneria** [comment]
What are your views @jywarren @nstjean

**Comment by nstjean** [comment]
I see the same problem with both of those links: contributors and followers. We do not need them to be links, since they are right there on the page at the top.

**Comment by cesswairimu** [comment]
This is fixed now. Closing this. Thanks all
