### ISSUE TITLE
list view not working

### ISSUE THREAD

**Issue by keshavsethi** [publiclab/plots2#7505]
List view in https://publiclab.org/questions?page=1 is not working.
It remains in grid view on clicking list view button as shown 
![Screenshot from 2020-02-15 22-07-44](https://user-images.githubusercontent.com/36025262/74591686-0037b000-5040-11ea-9d09-2be5c46c9a91.png)

Thanks !!

**Comment by keshavsethi** [comment]
@VladimirMikulic @SidharthBansal @nstjean Is this a valid issue?? can i try this?

**Comment by nstjean** [comment]
Yes this is an issue I noticed before! You can certainly take a look at it and see if you can fix it!

**Comment by AyanChoudhary** [comment]
@keshav234156 Are you still working on this? If not can I take this?
