### ISSUE TITLE
pop up css not working 

### ISSUE THREAD

**Issue by keshavsethi** [publiclab/plots2#7509]
pop over in subscription styles are not working properly in  https://publiclab.org/subscriptions
1)multiple popups  together
2)z-index wrt header
3)tweet button css
4) overlapping  
![Screenshot from 2020-02-16 01-58-03](https://user-images.githubusercontent.com/36025262/74594829-b14e4280-5060-11ea-8665-7985482c2e7e.png)
@VladimirMikulic @SidharthBansal @nstjean 
Thanks!!

**Comment by sssash18** [comment]
@keshavsethi  issue #7355 already mentions this problem in it regarding this popup

**Comment by keshavsethi** [comment]
@sssash18 , Thanks for mentioning that issue but there are few more things which are not covered in that PR like z index wrt top banner, tweet button css etc

**Comment by sakshi-2412** [comment]
I would like to take up this issue!
