### ISSUE TITLE
display author and time on hover of tags

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#751]
We should use a [Bootstrap tooltip](http://getbootstrap.com/javascript/#tooltips) to display who and when tags were created, for each tag element in the list: 

![screenshot 2016-08-30 at 12 43 39 pm](https://cloud.githubusercontent.com/assets/24359/18098255/6a98237e-6eaf-11e6-8af7-df0f5fde2d34.png)

The tooltip could be attached to this span: https://github.com/publiclab/plots2/blob/master/app/views/tag/_tagging.html.erb#L4

**Comment by carolineh101** [comment]
Hello, I'd like to help out with this!

**Comment by jywarren** [comment]
Super! This is extra important given the recently posted work on Activity
grids (https://publiclab.org/notes/liz/08-30-2016/check-out-
these-activity-grids) -- very glad to have your help on it!

**Comment by carolineh101** [comment]
I've created the tooltips – what are the components I need to retrieve the creator and date created?

![screen shot 2016-08-30 at 10 17 23 pm](https://cloud.githubusercontent.com/assets/17236117/18116822/a45c743e-6eff-11e6-893d-cedd222531c7.png)

**Comment by jywarren** [comment]
There's a long chained method for `author`, which in full is `<%= tag.drupal_node_community_tag.first.author.username %>`

However, you could improve this situation quite a bit by making a method in `app/models/drupal_tag.rb` like:

```ruby
def author
  self.drupal_node_community_tag.first.author
end
```

then, the template would just need: `<%= tag.author.username %>`. 

For the date, you can use `Time.at(t.drupal_node_community_tag.first.date)` -- which converts the timestamp into a Time object. 

But then you'll need to convert it to a readable time; we often use this: `<span><%= time_ago_in_words(time_object) %> ago</span>`

Hope that's helpful! Some of these should be easier than they are, due to some legacy database structures. Adding some helper methods to the models as I suggest above helps improve the situation.

**Comment by carolineh101** [comment]
Thank you, that was very helpful!  How does this look?

![screen shot 2016-08-31 at 10 35 33 am](https://cloud.githubusercontent.com/assets/17236117/18139708/66639f32-6f67-11e6-8bfd-64e76e6c9c2c.png)

**Comment by jywarren** [comment]
Looks great! Maybe make the username bold, so it stands out a bit more?
Then I think it's good!

**Comment by carolineh101** [comment]
Ok! Does this look good? If so, I'll submit a pull request.

![screen shot 2016-08-31 at 4 08 03 pm](https://cloud.githubusercontent.com/assets/17236117/18149495/36324aec-6f95-11e6-8f06-9ddc07afc372.png)

**Comment by jywarren** [comment]
Perfect. Thanks! Please rebase on top of the latest master and I should be
able to merge.

**Comment by carolineh101** [comment]
Ok, I've created a pull request!

**Comment by jywarren** [comment]
Completed!
