### ISSUE TITLE
Useless blank space 

### ISSUE THREAD

**Issue by NitinBhasneria** [publiclab/plots2#7513]
there is a useless blank space that needs to be removed in the user page.

![Screenshot from 2020-02-16 20-22-59](https://user-images.githubusercontent.com/44112080/74607009-0dfe3b80-50fb-11ea-8751-5f9b8179e3ef.png)
after clicking this comes 
Where to look
https://publiclab.org/profile/radimir_cacic09
![Screenshot from 2020-02-16 20-22-58](https://user-images.githubusercontent.com/44112080/74607019-279f8300-50fb-11ea-8835-b2713e614c9f.png)

Although in some users this space is used for twitter and other signs. But space should not be displayed if the user has nothing to show.
## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by NitinBhasneria** [comment]
@nstjean @cesswairimu Review this issue please.

**Comment by cesswairimu** [comment]
@NitinBhasneria, the link provided above does not show any such space...kindly check again

**Comment by NitinBhasneria** [comment]
No, but we have to click on three dots for that kindly click and also check the screenshots @cesswairimu

**Comment by cesswairimu** [comment]
Gotcha..go ahead

**Comment by nstjean** [comment]
@chirag-wadhwa asked me if I could find them an easy issue to try as their first step after a FTO. This looks pretty simple with just HTML and CSS. Do you mind letting them try this one?

**Comment by NitinBhasneria** [comment]
No not a problem but some js will be included in this to check if github or twitter icon is there or not.
If you want to assign this to someone you can.

**Comment by nstjean** [comment]
@NitinBhasneria Thanks! You are doing excellent work!

**Comment by NitinBhasneria** [comment]
@nstjean have you assigned it to someone or should I solve this.
Thanks

**Comment by nstjean** [comment]
@NitinBhasneria I have not heard back so go ahead.

**Comment by jywarren** [comment]
I believe this is completed, thank you!
