### ISSUE TITLE
Lock floating toolbar for formating in public lab posts

### ISSUE THREAD

**Issue by imajit** [publiclab/plots2#7518]
The toolbar that allows user to format the text in 4th step of [post](https://publiclab.org/post) is not useful in other steps. So I feel locking it to 4th step instead of having a floating one would be a good idea.
![ezgif com-video-to-gif(4)](https://user-images.githubusercontent.com/38528640/74613352-a2849000-5133-11ea-9fbe-8ff2c90e4b85.gif)

**Comment by neelesh17** [comment]
Can i claim this issue?

**Comment by imajit** [comment]
@publiclab/designers can you please review this

**Comment by nstjean** [comment]
I do agree that it shouldn't be floating all over the page. I think the reason it was floating was so that it was always visible when the edit box is really long and you're scrolling through things. But perhaps we could hide it when the edit box isn't visible?

**Comment by imajit** [comment]
I agree hiding it when edit box is not visible can solve the issue. Also the last four buttons in the toolbar also do not have a grey background, even that needs to be fixed . @nstjean I would like to work on this issue and  @neelesh17 I have actually started working on the issue but you can help me if I'm stuck :relaxed:

**Comment by nstjean** [comment]
Sounds like a good plan!
