### ISSUE TITLE
Missing css files in assets.rb file

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#7529]
While trying to find a fix for the padding problem in the dropdown menu for `_card.html.erb` file,I noticed that some files are not included in`assets.rb` such as `notes.css` and some other css files.Thus the likely padding and ui issues across the app can just be fixed by importing these.

Am I missing something here ...are these css files imported from any other place? Not really sure can you help me out

For ex in file `_new_question.html.erb` has the following code which renders the dropdown without any padding issue:-

```
.ellipsis{
  cursor: pointer;
}

.dropdown-menu li a{
  display: inline-block;
  padding-bottom: 5px;
  padding-left: 14px;
  font-size: 13px;
}

```

But the same block of code present in `notes.css` is not rendered possible because it is not compiled.  
```
#notes .ellipsis {
  cursor: pointer;
}

#notes .dropdown-menu li a{
  display: inline-block;
  padding-bottom: 5px;
  padding-left: 14px;
  font-size: 13px;
}
```

**Comment by Tlazypanda** [comment]
@jywarren @SidharthBansal @VladimirMikulic can you have a look and point me in the right direction? Not really sure if this inference is right :sweat_smile:

**Comment by VladimirMikulic** [comment]
You are right! `notes.css` is neither compiled nor referenced with `stylesheet_link_tag`.

**Comment by Tlazypanda** [comment]
@VladimirMikulic should I add the missing css files to `assets.rb` then and open a pr for the same?

**Comment by VladimirMikulic** [comment]
You could build upon this PR. No need for separation.

**Comment by Tlazypanda** [comment]
Ohh okay should I add all the missing css files then or are some of them not in use/inactive now? Can you let me know about the same @VladimirMikulic Thanks a ton! :smile:

**Comment by VladimirMikulic** [comment]
All that are required, but not present in `assets.rb` or `application.css` :)

**Comment by cesswairimu** [comment]
Hey @Tlazypanda I don't think we need to include this on application.yml. Rails conventions includes the assets on views by default you have to add if you have other css files on other folders. Am I missing smth here?

**Comment by Tlazypanda** [comment]
@cesswairimu ummm...after adding that file I can see the difference in css in some pages for example pls refer-https://github.com/publiclab/plots2/issues/7565  so I think it is not getting imported, in the application.css file we have to give relative path of the stylesheets and the assets folder is also not in the vendor directory here it is for the app directory

**Comment by jywarren** [comment]
great detective work here! Thanks!!
