### ISSUE TITLE
A note of Eymund's not available

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/plots2#753]
one of [Eymund's notes](https://publiclab.org/notes/eymund-diegel/10-26-2012/hello-kitty-watchdog-patrols-gowanus-canal-skies) on the Hello Kitty rig is unavailable, however it shows up in his [profile](https://publiclab.org/profile/Eymund):

![screen shot 2016-08-30 at 10 51 56 am](https://cloud.githubusercontent.com/assets/1203280/18100460/f5310948-6e9f-11e6-891a-968100908699.png)

I was wondering if it has to do with his username change, as his old notes are under the user "Eymund-diegel" and new ones are under Eymund.  That said, several Eymund-Diegel notes are displaying. This note alone appears to have the issue.

**Comment by jywarren** [comment]
Whoa, odd error:

```ruby
Completed 500 Internal Server Error in 725.7ms

ActionView::Template::Error (incompatible character encodings: ASCII-8BIT and UTF-8):
    74:   <% end %>
    75: 
    76:   <div style="overflow:hidden;" id="content">
    77:   <%= raw auto_link(insert_extras(@node.latest.render_body), :sanitize => false) %>
    78:   </div>
    79: 
    80:   <% if @node.files && @node.files.length > 0 %>
  app/views/notes/show.html.erb:77:in `_app_views_notes_show_html_erb__4359248108729036159_90768340'
```

I think we've seen encoding errors before, I'll check.

**Comment by jywarren** [comment]
Indeed: https://github.com/jywarren/plots2/issues/102 and https://github.com/jywarren/plots2/issues/196, but no clear solution. Reading up.

**Comment by jywarren** [comment]
This is very odd. I can run: 

```ruby
helper.auto_link(helper.insert_extras(@node.latest.render_body), :sanitize => false)
```

in the rails console on the production server, with no error, and its encoding is `#<Encoding:UTF-8>`. I'm not sure why this would be happening?

**Comment by jywarren** [comment]
Very odd, also -- attempted to paste the content of this note back into the note editing form at https://publiclab.org/notes/edit/4649, and save, which failed (same error?), but pasting the content into the bottom of the sandbox wiki works fine: https://publiclab.org/wiki/sandbox

Is the database column itself ascii encoded?

**Comment by jywarren** [comment]
Going to try cloning the record into a new one, preserving all columns, and deleting old one to get a fresh record. Else may have to look at reading the encoding in MYSQL? http://stackoverflow.com/questions/30598514/ruby-on-rails-utf8-encoding-problems-in-mysql-from-activerecord

**Comment by jywarren** [comment]
Wow, this is a real doozy. I can /sometimes/ save a new revision with blank content, but sometimes that doesn't work either, resulting in:

```
ActionView::Template::Error (incompatible character encodings: UTF-8 and ASCII-8BIT):
    56:     <div class="container">
    57:       <div class="row">
    58:
    59:         <%= yield %>
    60:
    61:       </div><!--/row-->
    62:     </div><!--/container-->
  app/views/layouts/application.html.erb:59:in `_app_views_layouts_application_html_erb__2454989576958399069_69005600'
```

There doesn't seem to be a pattern, though, and when I paste in the original content again, it breaks. I tried replacing all the quotation marks to ensure they weren't special characters, but that didn't work either.

**Comment by jywarren** [comment]
On the advice of: 

I inserted these lines in `/config/environment.rb` and restarted:

```ruby
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8
```

The post then showed up (with "hello" as its body), but when I edited and pasted in the original text, it showed the same error. So I removed those lines and restarted again. Now it's shown once again: https://publiclab.org/notes/eymund-diegel/10-26-2012/hello-kitty-watchdog-patrols-gowanus-canal-skies

The original is here: https://gist.github.com/jywarren/8ea019bd39b8703bf8bdec85f091fba8 (with smart quotes removed).

I've worked on this for some hours, and can't for the time being continue. @icarito I know you're in transit, but could you look over the steps I've attempted and see if you can figure out what's going wrong? 

To recreate the revision, i've been using (in rails console):

```ruby
n = DrupalNode.find 4649
r = n.latest
r2 = n.new_revision({uid: 1016, nid:4649, title: 'Hello Kitty Watchdog Patrols the Gowanus Canal', body: 'hello'})
r2.save!
r.delete
```

This deletes the troubled revision and recreates it with the same parameters except the `body`, which is what was creating this issue originally (i believe). I've also tried:

```ruby
r.body = r.body.force_encoding("UTF-8")
r.save!
```

This doesn't seem to work either, and then the post sometimes becomes irrecoverable even if I set `body` to "hello" again.

**Comment by icarito** [comment]
Sure I'll have a look tonight. 

Encodings tend to be a complex issue. I've had good results by staying with utf-8 all the way.

**Comment by jywarren** [comment]
Early in our sites history we weren't all but should be now, and oddly when
I run body.encoding, it reports utf-8!

On Sep 1, 2016 3:17 PM, "Sebastian Silva" <notifications@github.com> wrote:

Sure I'll have a look tonight.

Encodings tend to be a complex issue. I've had good results by staying with
utf-8 all the way.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/753#issuecomment-244181104>,
or mute
the thread

**Comment by icarito** [comment]
Okay I logged into rails console and tried to reproduce the issue but could not trigger the error. I tried the commands you shared and indeed managed to create a new revision but setting the content back to https://gist.github.com/jywarren/8ea019bd39b8703bf8bdec85f091fba8 on the rails console felt awkward (because of escaping).

In order to properly reproduce the issue I need write rights for https://publiclab.org/notes/edit/4649

Meanwhile my own research points to other ways of forcing utf-8 encoding by either:
* [setting an active record schema option] (https://github.com/algolia/algoliasearch-rails#utf-8-encoding) or
* [monkeypatching active record](http://stackoverflow.com/questions/11478316/error-incompatible-character-encodings-utf-8-and-ascii-8bit/16737583#16737583)

Hopefully we can test these outside production ;-)

**Comment by icarito** [comment]
@jywarren If you have simple way to grant me edit rights to https://publiclab.org/notes/edit/4649 I'd appreciate it - I assume I will be able to reproduce it then (on saving?).

I really need to reproduce to propose or try a fix.

**Comment by jywarren** [comment]
Oh, sorry - i made you an admin just now.

**Comment by mathewlippincott** [comment]
Found another note missing, this one from Chris Fastie, and of a similar vintage:
https://publiclab.org/notes/cfastie/6-3-2012/nrg-images-cover-crop-trials

It appears in searches but you can't access the link:

![screen shot 2016-09-27 at 1 36 49 pm](https://cloud.githubusercontent.com/assets/1203280/18890812/a26fb9ce-84b7-11e6-9c73-b17665736add.png)

**Comment by mathewlippincott** [comment]
Another missing note, this one much more recent:
https://publiclab.org/notes/Ecta64/04-24-2016/high-wind-range-tailless-sled-kite-design

This one does not appear in Ecta64's profile.  Its only record is a [link from one of my notes](https://publiclab.org/notes/mathew/05-02-2016/stormy-o-weathers-horned-allison-towards-a-kite-wind-speed-meter).
![screen shot 2016-10-31 at 5 14 55 pm](https://cloud.githubusercontent.com/assets/1203280/19875865/c35386e8-9f8d-11e6-9a41-eb4726481eb6.png)

**Comment by jywarren** [comment]
thanks for reporting -- will look into this first thing tomorrow.

On Mon, Oct 31, 2016 at 5:18 PM, mathew lippincott <notifications@github.com

**Comment by jywarren** [comment]
Updates: the original Hello Kitty post is working now: https://publiclab.org/notes/eymund-diegel/10-26-2012/hello-kitty-watchdog-patrols-gowanus-canal-skies (not actually sure what the solution was unless Sebastian was able to do something with encodings... but happy)

I got an email notification for this one but don't see the comment here anymore; maybe it was a mistake? But in any case, the URL was not quite right, so if the wrong URL was showing somewhere we can try to find that: 

https://publiclab.org/notes/Ecta64/4-24-2016/high-wind-range-tailless-sled-kite-design 

Should be (and works at):

https://publiclab.org/notes/Ecta64/11-01-2016/high-wind-range-tailless-sled-kite-design

The last one, here:

...is an unrelated one based on tag code, which I think I've also found:

```
  Rendered tag/_tagging.html.erb (12.7ms)
  Rendered notes/show.html.erb within layouts/application (1279.6ms)
Completed 500 Internal Server Error in 3350.6ms

ActiveRecord::RecordNotFound (Couldn't find DrupalUsers with uid=6):
  app/models/drupal_node_community_tag.rb:32:in `user'
  app/models/drupal_node_community_tag.rb:28:in `author'
  app/views/tag/_tagging.html.erb:6:in `block in _app_views_tag__tagging_html_erb__752610345364303992_59983440'
  app/views/tag/_tagging.html.erb:5:in `_app_views_tag__tagging_html_erb__752610345364303992_59983440'
  app/views/notes/show.html.erb:123:in `_app_views_notes_show_html_erb__1530052915338889494_61098960'
```

I believe I've created a test and a fix for this situation and submitted it in #948

**Comment by mathewlippincott** [comment]
The Ecta64 notes-- I deleted my comment on this issue because I emailed Ecta64 and he indicated that he'd deleted the earlier notes (so not a bug).  He had concerns about the kite's stability.  I pushed him to re-post and annotate rather than delete, hence the contemporary date on the new URL.

**Comment by jywarren** [comment]
Awesome, thanks!!
