### ISSUE TITLE
remove headers when table is empty

### ISSUE THREAD

**Issue by keshavsethi** [publiclab/plots2#7531]
Here in https://publiclab.org/wiki/tag/question:general?sort=page_views
Header can be removed when table is empty. A message can be displayed that table is empty.
![Screenshot from 2020-02-18 16-47-49](https://user-images.githubusercontent.com/36025262/74731762-b680dc80-526e-11ea-9e14-1582a6bb08db.png)

**Comment by urvashigupta7** [comment]
I would like to work on it.
