### ISSUE TITLE
Including Bootstrap in plots2/editor

### ISSUE THREAD

**Issue by keshav234156** [publiclab/plots2#7532]
Bootstrap files are not included in plots2 Editor leading to various style issue like inconsistency in style of the toolbar , quoted text and code doesn't show the style

**Comment by Bhanu-mbvg** [comment]
I would like to work on this issue

**Comment by VladimirMikulic** [comment]
Hi @Bhanu-mbvg. Thank you for the interest, but we already have the PR that resolves this.
