### ISSUE TITLE
No text appearing in mobile view.

### ISSUE THREAD

**Issue by NitinBhasneria** [publiclab/plots2#7533]
When we click on the button by type or by sort the dropdown appears in which the text is not appearing, there is space where the text can be shown but still, no text appears making it wired in looks.

![text](https://user-images.githubusercontent.com/44112080/74744739-c1486b00-5288-11ea-9039-647dc7d9612e.jpeg)
![text1](https://user-images.githubusercontent.com/44112080/74744746-c3122e80-5288-11ea-8bd1-8d39ad382bf6.jpeg)

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by NitinBhasneria** [comment]
@cesswairimu @nstjean review this please.

**Comment by nstjean** [comment]
I definitely see an issue on http://localhost:3000/questions/tag/question:general
Feel free to fix it!

**Comment by NitinBhasneria** [comment]
Ok thanks @nstjean
