### ISSUE TITLE
Editor toolbox sticking at footer

### ISSUE THREAD

**Issue by keshavsethi** [publiclab/plots2#7544]
In https://publiclab.org/post?tags=newsletter

On Scrolling down toolbox of editor sticks at bottom  of footer as shown 
![Screenshot from 2020-02-20 02-11-05](https://user-images.githubusercontent.com/36025262/74874325-cab7fd00-5386-11ea-82b0-8ff930850e17.png)
@cesswairimu @VladimirMikulic @nstjean Please review 
Thanks!!

**Comment by VladimirMikulic** [comment]
Fixed in https://github.com/publiclab/PublicLab.Editor/pull/395
