### ISSUE TITLE
Questions don't show a sidebar map when they have a location

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#7561]
If you look at a note here you'll see that it has a sidebar map:
https://stable.publiclab.org/notes/warren/07-09-2018/test

![FireShot Capture 311 - 🎈 Public Lab_ Test - stable publiclab org](https://user-images.githubusercontent.com/49460529/75196351-c8102b80-5729-11ea-9629-04dd09ca0c5a.png)

But when a question has a location it doesn't show anything:
https://stable.publiclab.org/questions/gretchengehrke/09-08-2017/what-are-the-reaction-rates-of-hydrogen-sulfide-with-oxygen-versus-copper-or-silver?_=1582582208#

![FireShot Capture 310 - 🎈 Public Lab_ What are the reaction rates of hydrogen sulfide with o_ - stable publiclab org](https://user-images.githubusercontent.com/49460529/75195881-d4e04f80-5728-11ea-8d27-898bf6d2f9a2.png)

Now that we have locations and items on maps we should add that functionality to questions as well! 

Here is the existing code for a sidebar on a note:
https://github.com/publiclab/plots2/blob/4691cb7a01fe1f81d3b9d952435e1058925b8abb/app/views/sidebar/_related.html.erb#L45-L64

And this is the partial for a sidebar for a question:
https://github.com/publiclab/plots2/blob/master/app/views/sidebar/_question.html.erb

We need to copy all that code for displaying a side map and button to add a location, into the question template. But it's not a good idea to have the same code in two different templates! We should pull that code out into a new partial and then call that partial in both sidebars.

**Comment by Tlazypanda** [comment]
@nstjean can I take this up?

**Comment by nstjean** [comment]
@Tlazypanda Sure! Go ahead!
