### ISSUE TITLE
Error in Travis testing: PostTest

### ISSUE THREAD

**Issue by nstjean** [publiclab/plots2#7575]
I'm getting this error on my PRs, and I see that all recent PRs have the same error. It's not a test fail, it's a mysql error:

![FireShot Capture 330 - Job #16810 5 - publiclab_plots2 - Travis CI - travis-ci org](https://user-images.githubusercontent.com/49460529/75554903-3cd4b580-5a09-11ea-9632-13b764d73f11.png)

**Comment by alaxalves** [comment]
We hope that https://github.com/publiclab/plots2/pull/7568 fixes every Travis related issue

**Comment by nstjean** [comment]
Thanks for doing all this work on the tests!!

I am still getting an error. I restarted twice, same error.

![FireShot Capture 331 - Job #16893 4 - publiclab_plots2 - Travis CI - travis-ci org](https://user-images.githubusercontent.com/49460529/75690853-8fb0a600-5c71-11ea-9dca-952babb79482.png)

**Comment by nstjean** [comment]
Here's the PR: https://github.com/publiclab/plots2/pull/7562

**Comment by alaxalves** [comment]
> Thanks for doing all this work on the tests!!
> 
> I am still getting an error. I restarted twice, same error.
> 
> ![FireShot Capture 331 - Job #16893 4 - publiclab_plots2 - Travis CI - travis-ci org](https://user-images.githubusercontent.com/49460529/75690853-8fb0a600-5c71-11ea-9dca-952babb79482.png)

@nstjean I have commented on your PR, lets move the discussion there ;)

**Comment by jywarren** [comment]
I believe this was resolved in https://github.com/publiclab/plots2/pull/7715! Thanks!
