### ISSUE TITLE
Dropdown not spaced properly in Stats page

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#7577]
### Please describe the problem (or idea)
 The elements in the dropdown are not spaced properly in Stats page.This needs to be modified to make the UI more appealing.  
![image8](https://user-images.githubusercontent.com/33183263/75601721-f30ccd80-5ae3-11ea-85aa-bf5c86d67816.png)

### Please show us where to look

https://publiclab.org/stats

**Comment by Tlazypanda** [comment]
@VladimirMikulic @jywarren can you kindly approve? Thanks :v:

**Comment by VladimirMikulic** [comment]
:+1:
