### ISSUE TITLE
Tools popover overflows to the right of the screen

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#7578]
### Please describe the problem (or idea)
Currently the tools popover in the events page overflows to the right of the screen as shown below.It needs to be positioned so that it remains within the screen width.
![image10](https://user-images.githubusercontent.com/33183263/75602002-1dac5580-5ae7-11ea-8e70-66f79bcd76d6.png)

### Please show us where to look
/wiki/events

**Comment by Tlazypanda** [comment]
@VladimirMikulic @jywarren can you kindly approve? Thanks :v:

**Comment by VladimirMikulic** [comment]
Approved!
