### ISSUE TITLE
Add 'Last Edited By' to tools popover of questions and notes 

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#7586]
Currently only the Wiki tools popover has the last edited by field.We can extend this functionality to questions and notes in vorder to achieve uniform functionality across the website.

**Additional context (optional)**
Wiki-  
![image](https://user-images.githubusercontent.com/33183263/75658772-deb90400-5c8e-11ea-9676-8266117c2eb6.png)
Questions and notes-  
![image](https://user-images.githubusercontent.com/33183263/75658672-bcbf8180-5c8e-11ea-9a83-c691ca9cee1c.png)

**Comment by Tlazypanda** [comment]
@VladimirMikulic can you kindly approve? Thanks :v:

**Comment by VladimirMikulic** [comment]
This would definitely be useful. @Tlazypanda you have a sharp eye :)

**Comment by cesswairimu** [comment]
Thanks @Tlazypanda for your suggestion tagging @publiclab/maintainers to gve thoughts  on this before we can move forward. Thanks

**Comment by Tlazypanda** [comment]
@publiclab/maintainers @jywarren @emilyashley can you kindly approve? Thanks :v:
