### ISSUE TITLE
Spacing not proper between sort options and cards 

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#7587]
### Please describe the problem (or idea)

The spacing is not enough between the sort options and the cards in /tag and /contributor routes.So inorder to improve user experience we have to add some spacing for the same.
![image3](https://user-images.githubusercontent.com/33183263/75659141-80405580-5c8f-11ea-806f-f3b6c63af86f.png)  

![image4](https://user-images.githubusercontent.com/33183263/75659259-ad8d0380-5c8f-11ea-9f60-6ca38c8db2a3.png)

### Please show us where to look

https://publiclab.org/tag/oil-and-gas
/contributor/contributors

**Comment by Tlazypanda** [comment]
@VladimirMikulic can you kindly approve? Thanks :v:

**Comment by VladimirMikulic** [comment]
@Tlazypanda :+1:

**Comment by sanjana091001** [comment]
Can I work on this?

**Comment by VladimirMikulic** [comment]
@sanjana091001 if @Tlazypanda is fine with this, it's all yours :)

**Comment by Tlazypanda** [comment]
@sanjana091001 I have started working on this already :sweat_smile: you can take this https://github.com/publiclab/plots2/issues/7574 up if you want
