### ISSUE TITLE
Incorrect count of tags shown

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#7590]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
In the /tags route the cards for individual tags have wrong count of tags marked.
![image](https://user-images.githubusercontent.com/33183263/75749565-146df380-5d48-11ea-8d7b-763a45658ec6.png)
![image](https://user-images.githubusercontent.com/33183263/75749597-2c457780-5d48-11ea-9748-62e6b10ab436.png)

Here there are only 2 posts with this tag but 20 is shown as the count.

### Please show us where to look

https://publiclab.org/tags

**Comment by Tlazypanda** [comment]
@VladimirMikulic can you kindly approve? Thanks :v:

**Comment by VladimirMikulic** [comment]
Could you check if this occurs on the hosted website as well? Thanks.

**Comment by Tlazypanda** [comment]
@VladimirMikulic I think it does occur on the hosted website too.Please check the below links.Thanks :v: 

https://publiclab.org/tags?page=5
https://publiclab.org/tag/climate

**Comment by VladimirMikulic** [comment]
@Tlazypanda it's true! Good catch. This should definitely be fixed.

**Comment by ebarry** [comment]
Interesting! There is a discrepancy between the count of posts shown on the /tags Topic Cards, and the count of posts shown on the Tag Page. Great catch @Tlazypanda !
