### ISSUE TITLE
Issue in navbar

### ISSUE THREAD

**Issue by govindgoel** [publiclab/plots2#7593]
![ ](https://media.giphy.com/media/Xzdg0cVS5YmkrIbBUh/giphy.gif)
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
The topics section pop up but does not close when you click anywhere on the page
After clicking on tools section if you hover over community section it it overlaps and vice-versa.

### Please show us where to look

https://publiclab.org/post

### What's your PublicLab.org username?
>govindgoel
### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!
Brave Browser
Version 1.1.21 Chromium: 79.0.3945.79 (Official Build) (64-bit)

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by govindgoel** [comment]
@VladimirMikulic Please look at this

**Comment by VladimirMikulic** [comment]
@govindgoel this is great! Thank you for reporting this, you have my full approval.

**Comment by urvashigupta7** [comment]
I would like to work on this issue. Kindly assign it to me. 😊

**Comment by shreyaa-s** [comment]
Thanks @govindgoel ! I'll get it done today itself.
