### ISSUE TITLE
expand co-authorship features with right-to-edit, etc

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#761]
This issue is a combination of several smaller, [self-contained issues](https://github.com/publiclab/plots2/labels/break-me-up) which are inter-related. You can help by:

- choosing one and breaking it out into its own issue (leaving a comment here to reference back)
- solving one of these sub-issues
- helping to flesh out sub-issues so that they're easier to solve
- helping to break up the larger issue into more discrete parts so it can be solved one-by-one

****

Co-authorship -- the use of a [power tag](https://publiclab.org/wiki/power-tags) to make multiple authors, as in https://publiclab.org/notes/Shannon/07-06-2016/public-lab-code-of-conduct -- needs more features, for which we could open several new issues, but to collect them here:

- [x] give co-authors (as denoted by `with:<username>`, [see code here](https://github.com/publiclab/plots2/blob/master/app/views/notes/show.html.erb#L35-L38)) right to edit (as in now-closed #606), meaning a `node.has_power_tag('with')`-based check on `edit` and `update` actions on `app/controllers/notes_controller.rb` (broken out into #1640 by @ebarry)
- [x] possible `user.coauthored_notes` model method
- [x] list co-authored posts on all authors' profiles based on above
- [x] create simple interface for adding coauthors, either in [rich editor](https://github.com/publiclab/PublicLab.Editor) or in a guided tags system like #648
- [ ] add email notification sent to newly-added co-authors, explaining what it means, with `___ has made you a co-author. This means that...`

**Comment by jywarren** [comment]
Begun work in #825 with tests

**Comment by ashleypt** [comment]
I'll be happy to break this issue up. Additionally, each piece of it is something I'd like to work on, especially the first two.

**Comment by jywarren** [comment]
Super - yeah, i think the first step is to actually open a new issue for one of these, link to lines of code, and clearly (if briefly) state the distinct problem and proposed solution, with a link back to this "overview" issue. Thank you!

**Comment by jywarren** [comment]
And #825 includes test fixture data which create coauthor tags, as well as a test which will fail until the right-to-edit is added. So it's a great place to start!

**Comment by ananyo2012** [comment]
@jywarren Was looking at this. Shouldn't we remove the `fto-candidate` label since this doesn't seem to be a issue to be approached by first-timers? Also should I open separate issues for each one mentioned above?

**Comment by jywarren** [comment]
Yes, perhaps -- I had been marking some issues where it'd be easy to take a
sub-issue out and reformat as a FTO one, but maybe that's not helpful and
"break-me-up" is enough. If you'd like to break it up, that'd be great!
Thank you, Ananyo, you're doing great work!

**Comment by ananyo2012** [comment]
@jywarren Thanks Jeff! I will break this up into several issues.

**Comment by jywarren** [comment]
We are all done here EXCEPT for:

* [ ] sending an email to added coauthors explaning what it means!

This last item could be broken out and described more narrowly, and could potentially be a good one for a first-timers-only issue!

**Comment by jywarren** [comment]
This last item could also be achieved via a comment -- by automatically leaving a comment as we do for the barnstar feature:

https://github.com/publiclab/plots2/blob/dccf61b4cf0aa816a3a906495ea6a0b2d5d847b0/app/controllers/tag_controller.rb#L178-L180

The comment could say `@_author_ has marked @_recipient_ as a co-author.` and everybody on the thread would get email notified.

**Comment by jywarren** [comment]
Closing this and moving the remainder to a clean issue over at #2028 with next steps! Thanks, all!
