### ISSUE TITLE
Cursor doesn't change into pointer on hover over tag ellipsis in sidebar  

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#7613]
### Please describe the problem (or idea)
The cursor doesn't change into pointer on hovering over ellipsis of tag in sidebar which leads to confusion if it is a button or not.

![Screenshot from 2020-03-08 22-49-47](https://user-images.githubusercontent.com/33183263/76168374-4e4e5800-6195-11ea-8648-4a83510b9c15.png)

### Please show us where to look

https://publiclab.org/questions

**Comment by Tlazypanda** [comment]
@VladimirMikulic can you kindly approve? Thanks :v:

**Comment by VladimirMikulic** [comment]
@Tlazypanda I don't understand the issue. Which ellipsis? I don't see your cursor anywhere on the picture? Thanks.

**Comment by Tlazypanda** [comment]
@VladimirMikulic yeah sorry about that.Can you see it here? 
![IMG20200309171254](https://user-images.githubusercontent.com/33183263/76210137-7f786800-6229-11ea-9509-9c5802c2a0da.jpg)

**Comment by VladimirMikulic** [comment]
@Tlazypanda Oh, there it is! Thank you for a detailed screenshot.
I agree this should be changed to pointer since it is a button.

**Comment by Tlazypanda** [comment]
Moved to #7646.Closing this .
