### ISSUE TITLE
No alert dialog for making a user an admin

### ISSUE THREAD

**Issue by sssash18** [publiclab/plots2#7621]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
Currently their is not shown any kind of alert dialog box when the existing admin makes someone a admin or moderator
**Current Behaviour**
![Untitled_ Mar 10, 2020 4_22 PM](https://user-images.githubusercontent.com/57896905/76305692-a7300480-62eb-11ea-99e7-48170e31f575.gif)

> What did you expect to see that you didn't?
Their must be alert dialog box.

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by sssash18** [comment]
I would like to work on this issue

**Comment by nstjean** [comment]
Do you mean like a confirmation dialog box?

**Comment by sssash18** [comment]
Yes @nstjean

**Comment by nstjean** [comment]
@cesswairimu What do you think?

**Comment by cesswairimu** [comment]
mmmh I don't think we need this.. :thinking: If it was about removal we would have made sense but since its not a destructive action we don't need the dialog...hat do you think @nstjean

**Comment by cesswairimu** [comment]
@ebarry I know you may be using this function a lot. What are your thoughts on adding a dialog box?  Thanks

**Comment by ebarry** [comment]
Interesting find! If someone is made an admin, presumably by an admin going to the user's profile page and clicking "Make Admin" -- does the appearance of the buttons change? If so, is that enough of an alert?

**Comment by jywarren** [comment]
Yes, they do change. They are not displayed by default but anyone doing this will be able to open them to check. I think it's good enough, thanks all!!!
