### ISSUE TITLE
No way to remove any person as admin

### ISSUE THREAD

**Issue by sssash18** [publiclab/plots2#7622]
**Please describe the desired behavior.**
Describe the solution you'd like.
Currently their is no way( apart from banning) to remove a user as admin by another admin.It would be better if we provide with such option.

**Additional context (optional)**
Feel free to include any applicable: code, screenshots, or gifs.

**Comment by sssash18** [comment]
@VladimirMikulic @nstjean What are your views on this ?
I would like to add this option

**Comment by nstjean** [comment]
This does sound like it could be useful. @cesswairimu @jywarren what do you think?

**Comment by cesswairimu** [comment]
I think its a great idea @ebarry @steviepubliclab what do you think

**Comment by SidharthBansal** [comment]
+1

**Comment by ebarry** [comment]
Hi! Sorry i missed seeing this earlier. Thank you for observing this opportunity! 

I'm thinking about "how to think about" this issue. The site does not have that many total admins, and accidentally clicking that button is probably more harmful than the corresponding benefit offered by being able to easily click a button in the few times it would be necessary. 

I see that this is in the style of the button for making someone not a moderator -- currently who has these permissions? All moderators or only Admins? 

Thank you for thinking deeply about the publiclab.org website!!!!!

**Comment by ebarry** [comment]
Still thinking about this. I think i do not see the advantage of this feature. 
I am interested in hearing more from you about your idea 🤝
Could you elaborate on why you feel it would be better to provide an option to remove a user as admin by another admin (apart from banning)? Thank you! 😊

**Comment by sssash18** [comment]
@ebarry Just in case if a person needs to be removed as a admin while still continuing to be a regular user, it's not possible currently. It kind of creates a void in functionality, so I think adding that option will be beneficial in that case. Thanks!

**Comment by jywarren** [comment]
I don't have a strong opinion on this but the system was actually designed so it's not possible to un-admin someone - so that we don't end up without admins or so an admin doesn't like, "go rogue" or something. But really it's just not a common case so we didn't reason through this very thoroughly. I generally default to thinking that we should not add new features that aren't going to be used much, because it's more to maintain, but again, don't have a strong opinion here! Thanks!

**Comment by ebarry** [comment]
Hi @sssash18 , i think we are leaning towards a "do not implement" position on this, but it's not without gratitude for your thoughtfulness and insight into what does seem to be an obvious oversight.

**Comment by cesswairimu** [comment]
Closing this. Thanks all
