### ISSUE TITLE
Welcome GSoC 2020 applicants and  Call for proposals

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#7624]
Hello awesome GSoC applicant :wave: and welcome to PublicLab :balloon: 
--------

We are glad to have you here. This year, we  are participating in Google Summer of Code(GSoc) under DIAL. Here are a few todos 

### Introduce yourself 
Please say hi below and introduce yourself(optional)

### Call for GSoC proposals

We request applicants to post their proposals on the PublicLab website. [Here](https://publiclab.org/notes/cess/03-02-2020/call-for-2020-soc-proposals-gsoc-and-outreachy?_=1583850654) is a link to call of proposals to the PL website, which also has a template for drafting the template, sample proposals for past inters and helpful pointers while drafting the proposals.
 Kindly submit early and post a link on gitter so that contributors and mentors can give feedback and help you improve on your proposal. 

### Contributions :man_technologist: :woman_technologist: 

 To become  more familiar with the codebase, we encourage applicants to start contributing to the codebase during the application process. Find issues with the label `fto` `soc` to get started on the codebase. You can also get first-timer-issues here https://code.publiclab.org/

### Questions :thinking: 

 If you have any questions please leave a comment below and we will get back to you.

These tips are general tips.
Are you tensed? overwhelmed?  No need to worry!!! : We all are there to help you at each stage of the way. Feel free to reach out in case of anything. Folks are super friendly here :smile:

**Comment by saurabhkanswal** [comment]
Hey @emilyashley can you please provide some more information on this (https://publiclab.org/wiki/gsoc-ideas#Leaflet+Environmental+Layers+(LEL):+time+slider+UI ) idea. so i can start with proposal. 
As of now all i can understand is that this idea is about adding control native to LEL library like we have zoom, scale, layers control in leaflet.
your comments are welcomed.😃

**Comment by alaxalves** [comment]
Hello guys I'm Alax, but I think most people already know me here from last year's GSoC program. I intend to work this year again for 2020 GSoC in the DevOps upgrades on Spectral Workbench. My proposal is available [here](https://publiclab.org/notes/alaxallves/03-06-2020/gsoc-proposal-2020-spectral-workbench-rails-and-devops-upgrades?_=1583504846). Everyone feel free to comment and suggest any changes there. I have already started working on some of the Spectral Workbench upgrades. Currently I have a PR opened there I'd like some review on, the PR is at https://github.com/publiclab/spectral-workbench/pull/470. Thanks guys

**Comment by gr455** [comment]
Hi everyone, I am Ruturaj from India. A freshman at International Institute of Information Technology, Bangalore. I have been a part of PL for about 3 months now and it has been great and I have leart a lot of things on my way :smile:

**Comment by Tlazypanda** [comment]
Hey everyone! @cesswairimu @jywarren @emilyashley  Just wanted to know if I can submit my proposal for Outreachy for Gsoc as well. The Outreachy website states that if you are a student its better to apply for both the programs. My only concern is the topic I have chosen is not listed in the gsoc ideas for this year. Would this pose as a problem? Thanks

**Comment by cesswairimu** [comment]
@Tlazypanda yeah you def can

**Comment by cesswairimu** [comment]
Hi all, I have reviewed most of the proposals and left some feedback. I will go through the rest within the week. If you have a PR that has been waiting for review for a while ..feel free to mention it here and ping me...It easier to track it from here than on the PRs I could miss it amidst the hundreds of the emails notifications. Thanks

**Comment by sssash18** [comment]
@SidharthBansal @jywarren @cesswairimu Please provide your views on Accesslint(in Automatic linting of PR) in my proposal as I have to include it in my proposal before the deadline:https://publiclab.org/notes/suyash1814/03-07-2020/gsoc-2020-proposal-site-wide-accessiblity-on-publiclab-org

**Comment by gr455** [comment]
Hi @cesswairimu . Can you please review https://github.com/publiclab/spectral-workbench/pull/483 and https://github.com/publiclab/spectral-workbench/pull/490 . Thanks :)

**Comment by cesswairimu** [comment]
@sssash18 @gr455  I will take a look within the day. Thanks

**Comment by SidharthBansal** [comment]
To all GSoC applicants, Google has changed its timeline for GSoC.please have a look at new timeline at https://summerofcode.withgoogle.com/how-it-works/#timeline

**Comment by SidharthBansal** [comment]
Students are requested to post the proposal on the Google website asap!

**Comment by gr455** [comment]
@SidharthBansal do you mean the draft or the final pdf?

**Comment by neelesh17** [comment]
Hey @SidharthBansal  can you please provide some more information on this (https://publiclab.org/wiki/gsoc-ideas#Leaflet+Environmental+Layers+(LEL):+time+slider+UI ) idea.

**Comment by sagarpreet-chadha** [comment]
Hey @neelesh17 and everyone interested in that project, so the aim of the project is that we have a lot of data for each layers, hence we want a functionality to filter data on the basis of time (range). The most common UI is a TIME SLIDER (on map) which one may have seen on various websites.
Saying that we are open on better UI options with better UX.
I hope this helps! Thanks :)

**Comment by Tlazypanda** [comment]
@cesswairimu Thanks for taking the time out to review all our prs!!  :tada:  Adding a couple more that need to be reviewed 
https://github.com/publiclab/plots2/pull/7687 - ( issue description modified to add full before and after screenshot)
https://github.com/publiclab/plots2/pull/7607 - (approved)
https://github.com/publiclab/plots2/pull/7611 - (issue description changed just to reflect the social icon alignment and pr changes removed)
https://github.com/publiclab/plots2/pull/7605 - (clarification added)

**Comment by neelesh17** [comment]
> Hey @neelesh17 and everyone interested in that project, so the aim of the project is that we have a lot of data for each layers, hence we want a functionality to filter data on the basis of time (range). The most common UI is a TIME SLIDER (on map) which one may have seen on various websites.
> Saying that we are open on better UI options with better UX.
> I hope this helps! Thanks :)

@sagarpreet-chadha but isn't this issue alone is a little small for gsoc, if you could suggest any other issue it would be really helpfull

**Comment by cesswairimu** [comment]
@Tlazypanda I checked out the PRs. Thanks

**Comment by cesswairimu** [comment]
🌳🌟 Hi everyone, here's something very rewarding you can do in 5 minutes to benefit the entire community: you can fill out this survey and make sure YOU are represented in our 2020 Community Snapshot! https://forms.gle/Q9BNduRGzsLrALxi7 📈 

Check out the 2019 report here: https://publiclab.org/notes/liz/04-15-2019/report-2019-software-contributors-survey. We are going to do the same "chart-n-graphs" treatment for 2020 but before we can begin, we need more than 38 people to fill out this survey! That's right, so far only 38 people have filled the 2020 survey even though we have more active contributors than ever. In 2019, 63 people filled out the survey. **Let's exceed last year's response rate! Please click here to improve our data quality: https://forms.gle/Q9BNduRGzsLrALxi7**

Thank you for all you do!
💚

_Originally posted by @ebarry in https://github.com/publiclab/plots2/issues/7711#issuecomment-604460524_

**Comment by cesswairimu** [comment]
Thank you everyone for applying with PublicLab. We had great proposals from all you and with PublicLab participating as a sub org we had few slots but we would have loved to take in more..
Please know that we are extremely grateful for your work with us to date and that we welcome you to continue being part of this community. Thank you for understanding and we hope you’ll apply again :heart:
