### ISSUE TITLE
answer text remains in textarea after submission

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#763]
On a page like https://publiclab.org/questions/PeterDH/05-13-2016/question-how-do-i-get-the-calibration-user-interface, after submitting an answer, the answer textarea still has my answer text. It should be empty after a successful submission.

The answering template code is here: https://github.com/publiclab/plots2/blob/master/app/views/questions/_answer.html.erb

The form itself is here: https://github.com/publiclab/plots2/blob/master/app/views/questions/_form.html.erb

I couldn't find the submit code itself, though... @ananyo2012 ? This could make a good `first-timers-only` issue, too.

**Comment by ananyo2012** [comment]
Yes I see it Jeff. I am on it.

**Comment by ananyo2012** [comment]
Ok this was due to some duplicate ids in css. Fixed in #790

**Comment by ananyo2012** [comment]
And about the answer post code it is here Jeff  https://github.com/publiclab/plots2/blob/master/app/controllers/answers_controller.rb#L4-L18. On successful submission this code gets executed https://github.com/publiclab/plots2/blob/master/app/views/answers/create.js.erb#L1-L2

**Comment by ananyo2012** [comment]
@jywarren Uh I just found that comment section in notes pages are a little shorter now. See here https://github.com/publiclab/plots2/blob/master/app/views/notes/_comments.html.erb#L3. I wonder if it was a deliberate change. It's looking quite odd. Should it make it a full grid using `col-md-12` class. If you approve I can add it in the same fix.

**Comment by jywarren** [comment]
Hmm, they look about normal to me, do you mean they're narrower? Can you show a screenshot of what you mean? You can also use the "blame" feature to see who edited a line of code -- even in Github.com's view: https://github.com/publiclab/plots2/blame/master/app/views/notes/_comments.html.erb#L3

![screenshot 2016-09-06 at 2 13 25 pm](https://cloud.githubusercontent.com/assets/24359/18285411/3e990da0-743c-11e6-81ca-41e390959277.png)

**Comment by ananyo2012** [comment]
@jywarren Yes I mean narrower that the full width. Well I see the `col-md-10` class has been kept over quite a long time. I think it's just a catch of my eye. But it would be great if we use a `col-md-12` class instead to span full-width.

**Comment by jywarren** [comment]
sounds good to me!

**Comment by ananyo2012** [comment]
Ok I can include it in a future change as it's a simple one.
