### ISSUE TITLE
Add a drop-down arrow to the "About Us", "Tools" and "Community" Icon to indicate that there are sub-options under them.

### ISSUE THREAD

**Issue by theOpetunde** [publiclab/plots2#7632]
Continuing from [this issue](https://github.com/publiclab/plots2/issues/6496) #6496

I think it is important to have a 'dropdown' arrow in the "About Us", "Tools" and "Community" icons on the headers. I see that the code has already been implemented here: (https://github.com/publiclab/plots2/blob/master/app/views/layouts/_header.html.erb)

but the changes are not yet seen on the page. 
![Screenshot (2)](https://user-images.githubusercontent.com/60391138/76515429-db293800-6459-11ea-8d74-75640d0ff0ae.png)

There are still yet to be dropdown arrows on the header icons that have sub-icons. I think this can go on to be a FTO-issue. 

Please let me know your thoughts on this @publiclab/reviewers @publiclab/plots2-reviewers

**Comment by VladimirMikulic** [comment]
@theOpetunde I agree, we should add dropdown icons :+1:

**Comment by Kirti2502** [comment]
Is anyone working on this issue? If not I'd like to look into it.

**Comment by theOpetunde** [comment]
@Kirti2502 please go ahead

**Comment by sashadev-sky** [comment]
@theOpetunde @VladimirMikulic  I agree with @cesswairimu that arrows, by convention, indicate that the item should be clicked to see the dropdown. So if we were to switch to arrows, we would want to remove the hover functionality and change it to click. 

I don't think that's a bad idea, and would standardize the nav options you mention above to be the same as topics, which currently works with click. @publiclab/designers

**Comment by cesswairimu** [comment]
Closing this. @publiclab/designers please feel free to reopen this if you feel its a design we could change. Thanks all
