### ISSUE TITLE
Change function t to translation in app/views/tag/_profileCard.html.erb

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#7637]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/tag/_profileCard.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/tag/_profileCard.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

In the respective lines, the function t needs to be changed to translation  

```diff
25<a href="/tag/<%= tag.name %>/author/<%= @profile_user.name %>"><%= t('tag.index.notes', count: Node.find_by_tag_and_author(tag.name, @profile_user.id, 'notes').count) %></a> |
26          <a href="/questions/tag/<%= tag.name %>/author/<%= @profile_user.name %>"><%= t('tag.index.questions', count: Node.find_by_tag_and_author(tag.name, @profile_user.id, 'questions').count) %></a> |
27          <a href="/profile/comments/<%= @profile_user.name %>/tag/<%= tag.name %>"><%= t('tag.index.comments', count: Comment.find_by_tag_and_author(tag.name, @profile_user.id).count) %></a>
33<a style="float: right;  width: 100px;" rel="tooltip" title="<%= t('sidebar._post_button.share_your_work') %>" data-placement="bottom" href="/post?tags=<%= tag.name %>" class="btn btn-primary btn-sm">New post <i class="fa fa-plus fa-white"></i></a>
37<a style="width: 100px;" rel="tooltip" title="<%= t('tag.show.unfollow') %>" class="btn btn-light btn-sm active" href="/unsubscribe/tag/<%= tag.name %>"></i> <%= t('tag.index.unfollow') %></a>
39<a style="width: 100px;" class="btn btn-outline-secondary btn-sm index-follow-buttons follow-btn-remote" href="/subscribe/tag/<%= tag.name %>" data-remote="true"><%= t('tag.index.follow') %></a>
```
This needs to be replaced with the following - 

```diff
25<a href="/tag/<%= tag.name %>/author/<%= @profile_user.name %>"><%= translation('tag.index.notes', count: Node.find_by_tag_and_author(tag.name, @profile_user.id, 'notes').count) %></a> |
26          <a href="/questions/tag/<%= tag.name %>/author/<%= @profile_user.name %>"><%= translation('tag.index.questions', count: Node.find_by_tag_and_author(tag.name, @profile_user.id, 'questions').count) %></a> |
27          <a href="/profile/comments/<%= @profile_user.name %>/tag/<%= tag.name %>"><%= translation('tag.index.comments', count: Comment.find_by_tag_and_author(tag.name, @profile_user.id).count) %></a>
33<a style="float: right;  width: 100px;" rel="tooltip" title="<%= translation('sidebar._post_button.share_your_work') %>" data-placement="bottom" href="/post?tags=<%= tag.name %>" class="btn btn-primary btn-sm">New post <i class="fa fa-plus fa-white"></i></a>
37<a style="width: 100px;" rel="tooltip" title="<%= translation('tag.show.unfollow') %>" class="btn btn-light btn-sm active" href="/unsubscribe/tag/<%= tag.name %>"></i> <%= translation('tag.index.unfollow') %></a>
39<a style="width: 100px;" class="btn btn-outline-secondary btn-sm index-follow-buttons follow-btn-remote" href="/subscribe/tag/<%= tag.name %>" data-remote="true"><%= translation('tag.index.follow') %></a>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by p-vinayak** [comment]
I'd like to take this issue!

**Comment by Tlazypanda** [comment]
@p-vinayak Go ahead !

**Comment by Medlineme4** [comment]
I'm giving it a trial

**Comment by Jigyasa-Kumari** [comment]
I am an Outreachy 2020 applicant. Can I work on this issue?

**Comment by Tlazypanda** [comment]
@p-vinayak are you still working on this issue ? If not this can be assigned to someone else

**Comment by p-vinayak** [comment]
Just created a pull request! Sorry for the delay

**Comment by Tlazypanda** [comment]
@cesswairimu This is solved it seems can we close this? :sweat_smile:

**Comment by cesswairimu** [comment]
Sure..thanks eveyone :+1:
