### ISSUE TITLE
Center the tags open and show more tags button in the sidebar

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#7644]
### Please describe the problem (or idea)
Currently the tags open and show more tags button are not centered on the sidebar.  
![image](https://user-images.githubusercontent.com/33183263/76696029-db6d4180-66ac-11ea-80de-9f30690dafa4.png)

### Please show us where to look

https://publiclab.org/ ...

**Comment by Tlazypanda** [comment]
@VladimirMikulic @SidharthBansal can you kindly approve? Thanks :v:

**Comment by VladimirMikulic** [comment]
I was just about to open this issue when I saw this, @Tlazypanda you are reading my mind :)

**Comment by Tlazypanda** [comment]
@VladimirMikulic Some telepathy is surely on its way :rofl:
