### ISSUE TITLE
Redesign /tools page to incorporate # of activities, contributors

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#765]
The tools page at https://publiclab.org/tools could better integrate data from the new activity grids, which would be relevant to new visitors:

https://publiclab.org/notes/liz/08-30-2016/check-out-these-activity-grids

We could show, for each tool, instead of the text summary:

```
--------------------
|                  |
|                  |
--------------------
    Tool title
===================
    14 activities
  32 contributors
     4 upgrades
```

based on the count of activities using the same logic as in `application_helper.rb`:

https://github.com/publiclab/plots2/blob/master/app/helpers/application_helper.rb#L67-L71

(That method should, in any case, be moved to `/app/models/drupal_node.rb` as a method called `activities` -- and likewise with `upgrades`.)

We could add a `.count` to the end of the query which should optimize it as well, and then the template on the tools page could use `<p><%= node.activities.count %> activities</p>`.

But overall, this is a **design project** to look at how the tools page could be redesigned to include more welcoming language and more interactive info about each tool project.

Current page:

![screenshot 2016-08-31 at 12 27 16 pm](https://cloud.githubusercontent.com/assets/24359/18137454/5f34e96e-6f76-11e6-8352-6162ccd84e19.png)

**Comment by jywarren** [comment]
@carolineh101 - if you're interested in a slightly bigger project, I wonder if this is something you'd like to take a look at? @steviepubliclab and @ebarry are also interested in this and could probably provide some input if so.

**Comment by carolineh101** [comment]
Yes, I'd love to work on this!

**Comment by jywarren** [comment]
Super! I'm so glad. Thanks and tell us where we can be of help.

**Comment by carolineh101** [comment]
I've started working on it!  How do I turn a research note into a tool to test on the page?  (I've tagged my test note as "tool", but it's not showing up.)

**Comment by jywarren** [comment]
Ah, actually you have to make a wiki page and mark it as a tool, not a
note. Super!

**Comment by carolineh101** [comment]
Ah ok, thanks!

**Comment by carolineh101** [comment]
I've created a preliminary layout for /tools:

![screen shot 2016-09-06 at 9 12 33 pm](https://cloud.githubusercontent.com/assets/17236117/18300517/a1833afc-747e-11e6-9251-63a33d3b8014.png)

However, I'm having a bit of trouble with the activities and upgrades counts.  I've created the new methods (```self.activities``` and ```self.upgrades```) in ```/app/models/drupal_node.rb``` and have added ```.count``` to the end of the query, but the website doesn't seem to recognize ```activities``` as a method of DrupalNode when I try to run it.  Here is the error message:

![screen shot 2016-09-06 at 10 15 17 pm](https://cloud.githubusercontent.com/assets/17236117/18300615/7729eb56-747f-11e6-9f6d-61d2a036ec02.png)

Any idea what is going on?  (I'm not super familiar with Ruby, so I'm not sure what's the reason for the error.)

**Comment by jywarren** [comment]
I think I can help out here, but in the meantime maybe @ebarry and
@steviepubliclab can chip in on the design itself. I also was thinking we
could show the icons in colors (blue, red?), so they're easy to pick out.

**Comment by steviepubliclab** [comment]
Hi! Wow really excited for this. I like the design you're suggesting here. Also, I agree that having them different colors could be helpful. Does your layout include the lead image? The lead images caught my attention from the screenshot @jywarren copied in. Seem like right now the size isn't standard, if they were, perhaps they would fit better on the page and be easier to scan through? But this might be a different design question.

**Comment by jywarren** [comment]
Hi, Caroline -- so this is a bit more complex of an issue, but it's not too much more so. See in `application_helper.rb`:

https://github.com/publiclab/plots2/blob/master/app/helpers/application_helper.rb#L73-L77

The "stacked" methods like:

```ruby
      nodes = DrupalNode.where(status: 1, type: 'note')
                        .includes(:drupal_node_revision, :drupal_tag)
                        .where('term_data.name LIKE ?', "activity:#{$1}")
                        .page(params[:page])
                        .order("node_revisions.timestamp DESC")

```

That whole stack could be moved into `/app/models/drupal_node.rb` as a method called `activities` (the missing method) -- creating a paramter called `tagname` instead of using the Rexex replacement code of `$1` -- like:

```ruby
def self.activities(tagname)
   DrupalNode.where(status: 1, type: 'note')
             .includes(:drupal_node_revision, :drupal_tag)
             .where('term_data.name LIKE ?', "activity:#{tagname}")
             .order("node_revisions.timestamp DESC")
end
```

Here, we're not making a method of an individual node, like `node.activities` -- that would start with `def activities` -- the `self.` part means we're adding a method to the DrupalNode class itself, so it's more like when we call `DrupalNode.find()`. Ours will end up being `DrupalNode.activities`. 

Notice I removed the `page()` method, which is actually for pagination - not needed here, and really only supposed to be used in a view, not a model (my fault for leaving those in there). I suppose the `order()` method might also need to be kept in the helper, since when we move the core of that method to a model, we're supposed to be thinking of the most general use case. So the helper would be left with something like:

```ruby
node = DrupalNode.activities($1) # notice we're passing the tagname in here from the regex pattern $1
                 .order("node_revisions.timestamp DESC")
```

Then `DrupalNode.activities(tagname).count` will be the count.

This is kind of a judgement call -- we're saving a little complexity in the helper by moving it to the model. If we moved the `order()` method back into the model too, we'd save a little more complexity in the helper, but it'd make the model method less flexible. In general, I tend to think that things you do more than once should be moved deeper into the stack -- "back" towards the model, so they're more fundamental parts of the system, rather than just a specific usage we happen to be making. Since we don't want to repeat the whole sequence of calls to get our activities, just to count them, this makes sense. 

Sorry, that was long, but hope it gives some context and is helpful re: your specific issue!

**Comment by jywarren** [comment]
And just one more note -- we could, alternatively, decide that the `activities` method really ought to be a method of `DrupalTag` -- as I've made a few methods of that sort in that class, and we are doing tag-related things: https://github.com/publiclab/plots2/blob/master/app/models/drupal_tag.rb#L62-L69

But since we want `.activities()` to return nodes, I think our current plan makes sense. But the method I linked to here is a similar example - though maybe too inflexible since we're not using it!

**Comment by jywarren** [comment]
Standard image sizes could be done using some of the code from the new
dashboard -- see how on the dashboard they're all cropped to the same
height? https://publiclab.org/dashboard (or https://publiclab.org/research
if you're not logged in)

The code for that is here:
https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_node_default.html.erb

And styles here:
https://github.com/publiclab/plots2/blob/master/app/assets/stylesheets/dashboard.css

Those dashboard templates and styles could be repurposed to be more general
use around the site?

**Comment by carolineh101** [comment]
Thanks, the code for the activity and upgrades tables works now!  I've also added images to the tools and colors to the icons (though I haven't worked on image cropping yet).  How does this look so far?

![screen shot 2016-09-07 at 6 22 02 pm](https://cloud.githubusercontent.com/assets/17236117/18333925/27969478-7528-11e6-9fcd-9aece95f5d4c.png)

I just have a couple questions – how are we defining "contributors"?  And how do I get the proper ```tagname``` when calling the ```activities``` and ```upgrades``` methods on the ```/tools``` page?  Currently, I'm using the regex pattern ```$1``` as in the helper (which does work), but it's not registering the activities and upgrades, as you can see in the image above.

**Comment by jywarren** [comment]
Oh, this is so great! I'll answer at greater length tomorrow, but for
starters I wonder if we can align center within each tool and have the
activities link to the /wiki/toolname#Activities section. For tag name, I
think for now we have to assume the tag name matches the tool page name
(slug), although this won't always be true. But we can either work to make
it more true, or come up with a new system later.

**Comment by carolineh101** [comment]
Okay!  I've added links to the activities and upgrades, standardized the image heights to 150px, centered the content, and got the activities/upgrades numbers working.  How does this look so far?

![screen shot 2016-09-08 at 12 07 58 am](https://cloud.githubusercontent.com/assets/17236117/18340176/664fecf2-7558-11e6-98c3-286080b17407.png)

A couple caveats: the activities and upgrades links are to the _grids_ (```#Activity+grid``` and ```#Upgrade+grid```), which not all wikis have yet, and the tag names for the activity and upgrade counts are assumed to match the tool page name (which won't work for pages with spaces in the titles, hence why I changed the titles on my test tool wikis).

**Comment by jywarren** [comment]
This looks great. I'm thinking perhaps we should make the text size of a bit smaller -- match to the views/stars section, and... maybe comment out contributors until we figure that out? I think that's a bigger project for which we may need to open a new issue -- it could include counting:

* authors who've posted work tagged with the topic tagname
* those who've commented on or answered such posts
* even those who've added tags to the page to help get the activity grids running?

and figuring out how to do that efficiently.

Do you think `Read more` should be a `btn-default` button? And I'm thinking maybe some kind of text intro -- maybe something like:

> Public Lab's community develops many different techniques and methods for DIY environmental monitoring. Browse many of them here and learn how to get involved. 

@steviepubliclab -- do you think we could/should list questions about each, in addition to what @carolineh101's added?

This looks great so far!

**Comment by jywarren** [comment]
Oh, and I think we could make the header "Tools and techniques" and center it, with the subtitle in kind of a grey underneath. What do you think?

**Comment by steviepubliclab** [comment]
ohh I love this. The equalized spacing looks really nice too. I don't think the questions on first glance is as important and it might get a little cluttered. I think questions are more important on the tool pages themselves.

**Comment by jywarren** [comment]
Stevie, do you think we could/should remove "last edit by xxx" from this
view? Since in many ways now, the way to contribute is to do/post
activities, more than to edit the wiki page itself?

**Comment by steviepubliclab** [comment]
We could, but it does make it a bit more personable.

**Comment by carolineh101** [comment]
How does this look now?  I changed "read more" to "get involved" because it sounds more welcoming/interactive – what do you think?

![screen shot 2016-09-08 at 12 08 08 pm](https://cloud.githubusercontent.com/assets/17236117/18363000/0d09d026-75bd-11e6-9e86-9396eef6c9e6.png)

**Comment by steviepubliclab** [comment]
Hm, it sounds a bit like a commitment though and some people might not be
ready to commit to just in their exploring stage. Oh, explore, what do
people think of that word instead?

**Comment by carolineh101** [comment]
Hmm, explore does sound better – how does this look now?

![screen shot 2016-09-11 at 7 01 40 pm](https://cloud.githubusercontent.com/assets/17236117/18421212/4e057c14-7852-11e6-8025-c83f219eee67.png)

**Comment by jywarren** [comment]
I think this looks really good and we're ready for a PR -- we can continue to refine it in follow-up posts. Sound good? Thanks!

**Comment by carolineh101** [comment]
Ok, will submit a PR!

**Comment by jywarren** [comment]
This is now live, congrats and thanks again! Please ping us and check out https://github.com/publiclab/plots2/labels/help-wanted if you're looking for a new challenge!
