### ISSUE TITLE
Change function t to translation in app/views/sidebar/_wikis.html.erb

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#7654]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/sidebar/_wikis](https://github.com/publiclab/plots2/blob/master/app/views/sidebar/_wikis.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

The following 't' needs to be replaced with translation

```diff
16 <%= raw t('sidebar._wikis.updated_by', :time => time_ago_in_words(wiki.latest.updated_at), :url1 => "/profile/"+wiki.latest.author.name, :author => wiki.latest.author.name) %>
23 <p><a href="/tag/<%= params[:id] %>"><%= t('sidebar._wikis.more') %></a></p>
25 <p><a href="/wiki/"><%= t('sidebar._wikis.more') %> &raquo;</a></p>
```
Replace it with the following -

```diff
16 <%= raw translation('sidebar._wikis.updated_by', :time => time_ago_in_words(wiki.latest.updated_at), :url1 => "/profile/"+wiki.latest.author.name, :author => wiki.latest.author.name) %>
23 <p><a href="/tag/<%= params[:id] %>"><%= translation('sidebar._wikis.more') %></a></p>
25 <p><a href="/wiki/"><%= translation('sidebar._wikis.more') %> &raquo;</a></p>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by Medlineme4** [comment]
Give me a go ahead to work on this. pr please.

**Comment by Tlazypanda** [comment]
Yeah sure go ahead 👍

**Comment by Medlineme4** [comment]
Thank you

**Comment by Medlineme4** [comment]
How many FTO issues can I work on?🤔

Sent from Yahoo Mail on Android 
 
  On Sun, Mar 15, 2020 at 5:06 PM, Sneha Mishra<notifications@github.com> wrote:   


Yeah sure go ahead 👍

**Comment by Tlazypanda** [comment]
Usually just one since it's meant to be for first timers only 😅 after the fto's you can move to the fto candidates which are a bit more difficult than the ftos. @medlineme4

**Comment by Medlineme4** [comment]
How do I locate or move to the fto candidate? Is any available

Sent from Yahoo Mail on Android 
 
  On Tue, Mar 17, 2020 at 4:39 AM, Sneha Mishra<notifications@github.com> wrote:   


Usually just one since it's meant to be for first timers only 😅 after the fto's you can move to the fto candidates which are a bit more difficult than the ftos. @Medlineme4

**Comment by Tlazypanda** [comment]
@Medlineme4 you can find them at https://code.publiclab.org/. Thanks :v:

**Comment by Medlineme4** [comment]
Have I done it? Is it now okay

**Comment by Medlineme4** [comment]
Travis build up failed

**Comment by cesswairimu** [comment]
Hello, I am sorry but it seems like this was solved in another PR. Closing this...Thanks all
