### ISSUE TITLE
Change function t to translation in app/views/user_tags/index.html.erb

### ISSUE THREAD

**Issue by justinelai** [publiclab/plots2#7662]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/user_tags/index.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/user_tags/index.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

The following 't' needs to be replaced with translation.

```
2 <h1 style="font-family:Junction Light;"><%= t('user_tag.index.popular_user_tags') %></h1>
8 <p><%= t('user_tag.index.browse_popular_user_tags') %></p>
24 <th><a href = "<%= user_tags_path %>?sort=value"><%= t('user_tag.index.user_tag') %></a> <i class="fa fa-arrows-v"></i></th>
25 <th><a href = "<%= user_tags_path %>?sort=uses"><%= t('user_tag.index.number_of_uses') %></a> <i class="fa fa-arrows-v"></i></th>    
```

```
2 <h1 style="font-family:Junction Light;"><%= translation('user_tag.index.popular_user_tags') %></h1>
8 <p><%= translation('user_tag.index.browse_popular_user_tags') %></p>
24 <th><a href = "<%= user_tags_path %>?sort=value"><%= translation('user_tag.index.user_tag') %></a> <i class="fa fa-arrows-v"></i></th>
25 <th><a href = "<%= user_tags_path %>?sort=uses"><%= translation('user_tag.index.number_of_uses') %></a> <i class="fa fa-arrows-v"></i></th>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:
1. If you are not familiar with GitHub or the pull request model, [here is a guide you can follow](https://guides.github.com/activities/hello-world/) on how GitHub works.
2. If you are familiar with the terminal or would like to learn to use it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

3. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by justinelai** [comment]
Hi @publiclab/plots2-reviewers - I'm an Outreachy applicant and noticed we could use more FTOs! I followed the instructions in https://github.com/publiclab/plots2/issues/6206

If this looks good, I'm happy to claim and solve it. Thanks!

Note: will need to update 
https://github.com/publiclab/plots2/issues/6579

**Comment by taysa91** [comment]
Hi @cesswairimu 
I am on Outreachy applicant and new to open source. I see that @justinelai  might be working on this issue. If not, I would like to try it.
Thanks.

**Comment by justinelai** [comment]
@sssash18 Hi! I saw that you opened some new FTOs for the same t function. Could you please label mine and approve me to work on it? Thanks! 

CCing @jywarren @gauravano @SidharthBansal per instructions for getting this labeled.

@taysa91 - By now I think there are new FTOs to choose from. But if I'm doing this correctly, we can coordinate and I'll make you one :)

**Comment by TroydonAnabolic** [comment]
Hi, can I get one more too please :)

**Comment by cesswairimu** [comment]
@justinelai sure, I try to create more ftos within the week. @taysa91 and @TroydonAnabolic I will find to find ftos for you before end of day. Thanks all
