### ISSUE TITLE
Click required for "Topics" but not for other categories on https://publiclab.org/dashboard

### ISSUE THREAD

**Issue by Srija616** [publiclab/plots2#7667]
[

**Please describe the desired behavior.**
This issue is on the [Public Lab dashboard](https://publiclab.org/dashboard)
The "Topics" on the [dashboard](https://publiclab.org/dashboard) needs a left click to show options whereas other tabs like "Community", "Tools", etc require only hovering the mouse on them. 

I suggest we maintain uniformity over here. Please refer the gif below.
Also, @cesswairimu @jywarren please guide how to find codebase for the dashboard.

![ezgif com-video-cutter](https://user-images.githubusercontent.com/33909898/76824584-90366880-683d-11ea-812c-22542718d958.gif)

**Comment by chinmay021** [comment]
i would like to work on this . Can i?

**Comment by cesswairimu** [comment]
There is an issue about this somewhere I will try to look for it and link it here

**Comment by cesswairimu** [comment]
I will close now since its not a bug. Thanks all
