### ISSUE TITLE
talk page text missing 

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#769]
### What happened just before the problem occurred
I went to the organizer's page talk pad, and the text that use to be there is missing.

### Relevant URLs
https://publiclab.org/talk/public-lab-organizers
### PublicLab.org username
stevie
(to help reproduce the issue)

### Browser, version, and operating system
Chrome, os: X El Capitan

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by ebarry** [comment]
This is what the talk page used to be: https://publiclab.org/talk/organizers

Not sure why the link went to /public-lab-organizers

**Comment by jywarren** [comment]
Fixed, in that the tab link now goes to 'organizers' and not 'public-lab-organizers' -- and both pads are still available on the links above. Thanks for reporting!

**Comment by steviepubliclab** [comment]
Awesome! Thanks Jeff
