### ISSUE TITLE
No indication for current sort

### ISSUE THREAD

**Issue by sssash18** [publiclab/plots2#7695]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
Currently , a user can't know the way in which people are sorted. 
**Current Behaviour**
![Screenshot 2020-03-19 at 7 37 03 PM](https://user-images.githubusercontent.com/57896905/77076126-62a61680-6a19-11ea-9677-583ca8b8cd49.png)

> What did you expect to see that you didn't?
There must be some way of indicating like underlining  only the parameter in which the people are currently sorted.

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by sssash18** [comment]
@cesswairimu @SidharthBansal @nstjean @VladimirMikulic Please provide your views on this.
I would like to solve this issue. Thanks!

**Comment by VladimirMikulic** [comment]
You would like to implement users sorting? It's fine by me.

**Comment by sssash18** [comment]
@VladimirMikulic The sorting already works but their is no indication about the way in which users are currently sorted, I would like to underline only the parameter in which users are currently sorted.
