### ISSUE TITLE
move I18N library into bower dependency

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#771]
This library is included directly in the codebase:

https://github.com/publiclab/plots2/blob/master/public/javascripts/i18n.js

...but we should instead include it in our `bower.json` file and include it in our application.js file: https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/application.js

then `bower update` will include it.

**Comment by ryzokuken** [comment]
I could help with this, considering a bower package exists for the library.

**Comment by jywarren** [comment]
oh great -- yes, that would be super. Thanks!

**Comment by ryzokuken** [comment]
i was thinking about solving this problem this way:

1. adding the `angular-i18n` package to `bower.json`
2. removing the library folder
3. changing the part where it looks for the library in `public/javascripts` to `bower_modules/ ...`

@jywarren what do you say?

**Comment by jywarren** [comment]
yes, that sounds right -- though we should check that it gets picked up properly on this line of application.js, which is where it's referenced when its compiled into the final js used on the production site: https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/application.js#L35

Thanks!

**Comment by ryzokuken** [comment]
@jywarren I had started to work on this, when I realized how everyone switched from bower to npm sometime ago, and how recently, everyone's been switching from npm to yarn. 

yarn is a library built by facebook and google (I read this on the internet, don't know how true this is, but it was definitely built by facebook). I request you to read [this article](https://scotch.io/tutorials/yarn-package-manager-an-improvement-over-npm) and please think it over. 

Yarn's homepage: https://yarnpkg.com/

Thanks. If you decide against it, I'd work on bower anyway. Just thought you should know what I'd been thinking about.

**Comment by jywarren** [comment]
Hi - I think we tend to move a little slower than the typical library, in
part because it takes some time to ensure that a new system works given the
complexity of our site. But I'll definitely read it over, and just note
that integrating either npm or bower with the Rails asset pipeline is a
little complex, and took a while to get right. I'm open to discussions of
upgrading to Yarn, but there are a number of other more pressing issues I'd
like to focus on before dedicating too much time to it -- the Solr search,
advanced search API and interface, the new Rich Editor, and lots of the
issues at https://github.com/publiclab/plots2/labels/help-wanted. But
thanks a lot for bringing it up -- maybe there will be a time soon when
we're ready to consider a switch.

**Comment by ryzokuken** [comment]
@jywarren I totally understand. Please look over [http://www.hpcs.cs.tsukuba.ac.jp/~tatebe/lecture/h23/dsys/dsd-tutorial.html](this library). It comes with Rails support. Shall I add this one?

**Comment by jywarren** [comment]
Sorry, is that the right link?

**Comment by ryzokuken** [comment]
@jywarren If you could help me narrow down the bower package we need, I could perhaps fix this.

**Comment by jywarren** [comment]
So I think this would work: https://github.com/fnando/i18n-js which you could reference directly.

**Comment by ryzokuken** [comment]
Okay, so here's what I've been thinking about:
1. add the package to bower dependencies (involves updating `bower.json`
2. remove the file from the codebase
3. update the assets pipeline to use the one located in `bower_modules/` rather than 'public/javascripts/'
Sounds okay?

**Comment by jywarren** [comment]
Yes, that's perfect! I'm not sure we run any tests against the module, but
that could be an additional followup we could post as a new issue if you're
inspired to.

**Comment by ryzokuken** [comment]
@jywarren, The library page (https://github.com/fnando/i18n-js) describes the rails-y way to do it (by adding it to the Gemfile). As the library existed on the bower package index, I'm pretty sure it can be installed using bower too. Which one of the two ways would you like me to add the library to the project?

**Comment by jywarren** [comment]
I slightly prefer bower, as that's what we've done for most of the other
JavaScript assets. Thanks!

**Comment by ryzokuken** [comment]
Sure thing, I'm on it.

**Comment by ryzokuken** [comment]
@jywarren I understand that there aren't any unit tests for this, but is there any way I could test if the module works on my local environment before pushing my changes to the repository?

**Comment by jywarren** [comment]
Yes, using jasmine tests -- I believe the readme has a section on them?

**Comment by ryzokuken** [comment]
They do.

**Comment by ryzokuken** [comment]
`rake spec:javascript` does not work. Also, it does not appear in `rake --tasks`

**Comment by jywarren** [comment]
I believe it's rake spec:javascripts or rake specs:javascript, but I just
took a red eye flight and my brain isn't working that well. We should make
a more standard alias like rake test:javascript or something.

**Comment by ryzokuken** [comment]
@jywarren I believe it is `rake spec:javascript` because:
1. The README says so
2. Neither of the others work anyway
3. `rake test:all` also calls the exactly the same command

This had been working earlier when I ran tests on my local machine. I have no idea what went wrong. Maybe some other contributor can run a quick check and tell me if it is a local issue.

**Comment by jywarren** [comment]
Can you open a pr so we can see it run on the TravisCI test instance?

**Comment by ryzokuken** [comment]
definitely.

**Comment by jywarren** [comment]
oops, this was solved in #936- closing! Thanks again!
