### ISSUE TITLE
Width refinement to map popup display in CSS

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#7714]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

You can now see this mapping library on by default at:

https://stable.publiclab.org/map#7/41.14399650184958/-71.81762695312501

I'd like to suggest we narrow the popups a bit, to maybe 300px? They seem excessively wide. Is there a way to let them auto-size, or use the default?

![image](https://user-images.githubusercontent.com/24359/76344353-cf156d00-62d7-11ea-986e-2285da15b68c.png)

Citing @jessibreen below:

It looks like the width of the popup is set in the css for that page. It has an important flag on it, so it is overriding the leaflet default of 300.

The bug is at lines 20 and 21 in https://github.com/publiclab/plots2/tree/master/app/assets/map.css

Get rid of this:

```css
.leaflet-popup-content {
width: 800px !important;
}
```
...and the popup boxes will default to their usual 300 px width.

**Comment by jywarren** [comment]
I converted this to an FTO candidate and moved it to `plots2` !! Thanks, @jessibreen !!

**Comment by AidenOliver** [comment]
Hey I was wondering if I could try and help fix this issue. I see that jessibreen has made a pull request already, so if it's already resolved then that's fine. But I'd like to help as much as I can.

**Comment by cesswairimu** [comment]
@AidenOliver, let me know if you need help finding another issue
