### ISSUE TITLE
FEATURE: Integrate automatic code style checker

### ISSUE THREAD

**Issue by VladimirMikulic** [publiclab/plots2#7717]
Since I've been an active member of this community I see a lot (to be honest all) of beginners make the same styling mistakes and every time I have to point it out to them to enforce clean codebase.
I believe that other mentors could agree with me as well.

It would be very beneficial to the project and us (mentors) to have an automatic code style checker like [Stickler CI](https://stickler-ci.com/). The checker would save the enormous amount of our time and make sure that the code is properly formatted.

@jywarren @SidharthBansal @nstjean @sashadev-sky @cesswairimu your views on this? Thanks.

**Comment by cesswairimu** [comment]
@VladimirMikulic Wow :rocket: :rocket: that is a great idea... love it :tada: :tada:  I don't know anything about Sticker CI though...Will check it out

**Comment by VladimirMikulic** [comment]
Thanks, @cesswairimu. It's nothing complicated. We just specify formatting configurations for each language that we want to check and that's it. I am not the owner of the repo, so I can not set it up myself. I'll be more than happy to assist admins :)

**Comment by sashadev-sky** [comment]
sounds fine by me! looping in @gauravano

**Comment by Tlazypanda** [comment]
@VladimirMikulic That's an awesome idea :rocket:

**Comment by nstjean** [comment]
I love the idea of having consistent code!!

**Comment by gauravano** [comment]
Hi everyone!

@VladimirMikulic great idea. I think a few things we need to check about the Strickler are - how easy it is to use, how it present errors (this one is a bit important, as contributors will get to learn a lot if it highlights the rule).

Also, Strickler CI internally used rubocop for checking and fixing issues. I think we should check if  codeclimate which we currently use can provide the same service (not in terms of automatic fixing but highlighting the issues in review).

For testing and comparing @VladimirMikulic you can install the app on your cloned repo and after that, it can be installed here.

**Comment by jywarren** [comment]
I'm just noting that i reconfigured CodeClimate to leave in-line suggestions and it is pretty nice! It is limited to 5, i think, so it's not overwhelming. It looks like this:

![image](https://user-images.githubusercontent.com/24359/100785830-38498d00-33df-11eb-8fb1-404448fdfdee.png)


Maybe this is a nice way for this to work as well?

https://github.com/publiclab/plots2/pull/8527#pullrequestreview-506101602
