### ISSUE TITLE
BUG: tag_selection_test fails sometimes unexpectedly

### ISSUE THREAD

**Issue by VladimirMikulic** [publiclab/plots2#7718]
The bug is as far as I know old. Sometimes, the [test](https://github.com/publiclab/plots2/blob/master/test/unit/tag_selection_test.rb) fails for no reason.
I suspect it's because of time 'hacking' that we do in the test.

@Uzay-G do you have any suggestions here?
You did a great job fixing these kinds of tests in the GCI.

**Comment by Uzay-G** [comment]
Thanks! Do you have any logs of a situation where this one failed? That way I can troubleshoot the problem :+1:

**Comment by VladimirMikulic** [comment]
@Uzay-G sorry about that.
Here are a few examples:
https://travis-ci.org/github/publiclab/plots2/jobs/651138974?utm_medium=notification&utm_source=github_status from #7466

https://travis-ci.org/github/publiclab/plots2/jobs/661384805?utm_medium=notification&utm_source=github_status from #7481

**Comment by cesswairimu** [comment]
lets log here and reopen if this happens again...thanks everyone
