### ISSUE TITLE
Change function t to translation in app/views/layouts/_header.html.erb

### ISSUE THREAD

**Issue by nicoleiocana** [publiclab/plots2#7726]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/layouts/_header.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/layouts/_header.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
- 20: <input type="text" id="searchform_input" class="form-control search-query typeahead" role="search" qryType="tags" placeholder="<%= t('layout._header.search') %>"  value="<%= params[:query] %>" required>
+ 20: <input type="text" id="searchform_input" class="form-control search-query typeahead" role="search" qryType="tags" placeholder="<%= translation('layout._header.search') %>"  value="<%= params[:query] %>" required>

- 70: <%= t('layout._header.about.about_title') %>
+ 70: <%= translation('layout._header.about.about_title') %>

- 73: <a class="dropdown-item" href="/about"><%= t('layout._header.about.about_public_lab') %></a>
+ 73: <a class="dropdown-item" href="/about"><%= translation('layout._header.about.about_public_lab') %></a>

- 74: <a class="dropdown-item" href="/blog"><%= t('layout._header.about.blog') %></a>
+ 74: <a class="dropdown-item" href="/blog"><%= translation('layout._header.about.blog') %></a>

- 75: <a class="dropdown-item" href="/newsletter"><%= t('Newsletter') %></a>
+ 75: <a class="dropdown-item" href="/newsletter"><%= translation('Newsletter') %></a>

- 76: <a class="dropdown-item" href="/wiki/contact"><%= t('layout._header.about.contact') %></a>
+ 76: <a class="dropdown-item" href="/wiki/contact"><%= translation('layout._header.about.contact') %></a>

- 81: <a class="nav-link btn btn-outline-secondary" target="_blank" href="//store.publiclab.org"><%= t('layout._header.store') %></a>
+ 81: <a class="nav-link btn btn-outline-secondary" target="_blank" href="//store.publiclab.org"><%= translation('layout._header.store') %></a>

- 84: <a class="nav-link btn btn-outline-secondary" href="/donate"><%= t('layout._header.donate') %></a>
+ 84: <a class="nav-link btn btn-outline-secondary" href="/donate"><%= translation('layout._header.donate') %></a>

- 94: <a rel="tooltip" class="nav-link" title="<%= t('layout._header.your_dashboard') %>" data-placement="bottom" href="/dashboard">Dashboard</a>
+ 94: <a rel="tooltip" class="nav-link" title="<%= translation('layout._header.your_dashboard') %>" data-placement="bottom" href="/dashboard">Dashboard</a>

- 98: <a rel="tooltip" class="nav-link signupToggle" title="<%= t('layout._header.become_part_community') %>" href="#">
+ 98: <a rel="tooltip" class="nav-link signupToggle" title="<%= translation('layout._header.become_part_community') %>" href="#">

- 99: <%= t('layout._header.join') %>
+ 99: <%= translation('layout._header.join') %>

- 124: <a class="dropdown-item" href="/profile/<%= current_user.username %>"><%= t('layout._header.profile') %></a>
+ 124: <a class="dropdown-item" href="/profile/<%= current_user.username %>"><%= translation('layout._header.profile') %></a>

- 125: <a class="dropdown-item" href="/profile/edit"><%= t('layout._header.edit_profile') %></a>
+ 125: <a class="dropdown-item" href="/profile/edit"><%= translation('layout._header.edit_profile') %></a>

- 128: <a class="dropdown-item" href="/subscriptions"><%= t('layout._header.subscriptions') %></a>
+ 128: <a class="dropdown-item" href="/subscriptions"><%= translation('layout._header.subscriptions') %></a>

- 130: <a class="dropdown-item" href="/profile/<%= current_user.username %>/likes"><%= t('layout._header.notes_liked') %></a>
+ 130: <a class="dropdown-item" href="/profile/<%= current_user.username %>/likes"><%= translation('layout._header.notes_liked') %></a>

- 139: <%= link_to t('layout._header.logout'), logout_path, class: "dropdown-item" %>
+ 139: <%= link_to translation('layout._header.logout'), logout_path, class: "dropdown-item" %>

- 146: <%= t('layout._header.login.login_title') %>
+ 146: <%= translation('layout._header.login.login_title') %>

- 155: <a class="dropdown-item d-lg-none" href="//store.publiclab.org"><%= t('layout._header.store') %></a>
+ 155: <a class="dropdown-item d-lg-none" href="//store.publiclab.org"><%= translation('layout._header.store') %></a>

- 156: <a class="dropdown-item d-lg-none"  href="/donate"><%= t('layout._header.donate') %></a>
+ 156: <a class="dropdown-item d-lg-none"  href="/donate"><%= translation('layout._header.donate') %></a>

- 159: <a class="dropdown-item d-xl-none" rel="tooltip" title="<%= t('layout._header.your_dashboard') %>" data-placement="bottom" href="/dashboard">Dashboard</a>
+ 159: <a class="dropdown-item d-xl-none" rel="tooltip" title="<%= translation('layout._header.your_dashboard') %>" data-placement="bottom" href="/dashboard">Dashboard</a>

- 161: <a class="dropdown-item d-xl-none" rel="tooltip" title="<%= t('layout._header.become_part_community') %>" href="/signup"><%= t('layout._header.join') %></a>
+ 161: <a class="dropdown-item d-xl-none" rel="tooltip" title="<%= translation('layout._header.become_part_community') %>" href="/signup"><%= t('layout._header.join') %></a>

- 170: <% if params[:controller] == "notes" %><h1>Public Lab <small><%= t('layout._header.research_note') %></small></h1><% end %>
+ 170: <% if params[:controller] == "notes" %><h1>Public Lab <small><%= translation('layout._header.research_note') %></small></h1><% end %>

- 171: <% if params[:controller] == "wiki" %><h1>Public Lab <small><%= t('layout._header.wiki_doc') %></small></h1><% end %>
+ 171: <% if params[:controller] == "wiki" %><h1>Public Lab <small><%= translation('layout._header.wiki_doc') %></small></h1><% end %>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:
1. If you are not familiar with GitHub or the pull request model, [here is a guide you can follow](https://guides.github.com/activities/hello-world/) on how GitHub works.
2. If you are familiar with the terminal or would like to learn to use it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

3. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by WaldenJosh** [comment]
I would like to claim this issue. Thank you!

**Comment by nicoleiocana** [comment]
@WaldenJosh You got it, it's all yours. You are welcome.

**Comment by WaldenJosh** [comment]
Pull request #7744 created for this issue. Please review/comment.
