### ISSUE TITLE
Change function t to translation in app/views/tag/_contributors.html.erb

### ISSUE THREAD

**Issue by nicoleiocana** [publiclab/plots2#7736]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/tag/_contributors.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/tag/_contributors.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
- 26: <a rel="tooltip" title="<%= t('tag.contributors.unfollow') %>" class="btn btn-outline-secondary btn-sm" href="/unsubscribe/tag/<%= params[:id] %>"><i class="fa fa-user-plus" aria-hidden="true"></i> <%= t('tag.contributors.following') %> <b><%= params[:id] %></b></a>
+ 26: <a rel="tooltip" title="<%= translation('tag.contributors.unfollow') %>" class="btn btn-outline-secondary btn-sm" href="/unsubscribe/tag/<%= params[:id] %>"><i class="fa fa-user-plus" aria-hidden="true"></i> <%= translation('tag.contributors.following') %> <b><%= params[:id] %></b></a>

- 28: <a class="btn btn-outline-secondary btn-sm" href="/subscribe/tag/<%= params[:id] %>"><i class="fa fa-user-plus" aria-hidden="true"></i> <%= t('tag.contributors.follow') %> <b><%= params[:id] %></b></a>
+ 28: <a class="btn btn-outline-secondary btn-sm" href="/subscribe/tag/<%= params[:id] %>"><i class="fa fa-user-plus" aria-hidden="true"></i> <%= translation('tag.contributors.follow') %> <b><%= params[:id] %></b></a>

- 30: <a class="btn btn-outline-secondary btn-sm" rel="popover" data-placement="bottom" data-html="true" data-title="<%= t('tag.show.users_following_tag') %>" data-content="<% Tag.followers(params[:id]).each do |user| %><i class='fa fa-star-o'></i> <a href='/profile/<%= user.username %>'><%= user.username %></a><br /><% end %><% if Tag.follower_count(params[:id]) == 0 %><i><%= t('tag.show.none') %></i><% end %>"><%= Tag.follower_count(params[:id]) %> <i class="fa fa-user"></i> <span class="caret"></span></a>
+ 30: <a class="btn btn-outline-secondary btn-sm" rel="popover" data-placement="bottom" data-html="true" data-title="<%= translation('tag.show.users_following_tag') %>" data-content="<% Tag.followers(params[:id]).each do |user| %><i class='fa fa-star-o'></i> <a href='/profile/<%= user.username %>'><%= user.username %></a><br /><% end %><% if Tag.follower_count(params[:id]) == 0 %><i><%= translation('tag.show.none') %></i><% end %>"><%= Tag.follower_count(params[:id]) %> <i class="fa fa-user"></i> <span class="caret"></span></a>

- 39: <p><%= raw t('tag.contributors.wild_card_search_detected', :tag => params[:id]) %></p>
+ 39: <p><%= raw translation('tag.contributors.wild_card_search_detected', :tag => params[:id]) %></p>

- 41: <p><%= raw t('tag.contributors.no_contributors', :tag => params[:id]) %>:</p>
+ 41: <p><%= raw translation('tag.contributors.no_contributors', :tag => params[:id]) %>:</p>

- 46: <th style="width:75%;"><%= t('tag.contributors.people_who\'ve_posted') %></th>
+ 46: <th style="width:75%;"><%= translation('tag.contributors.people_who\'ve_posted') %></th>

- 47: <th><%= t('tag.contributors.notes') %></th>
+ 47: <th><%= translation('tag.contributors.notes') %></th>

- 53: <td><a href='/tag/<%= params[:id] %>/author/<%= user.name %>'><%= t('tag.contributors.notes') %> &raquo;</a></td>
+ 53: <td><a href='/tag/<%= params[:id] %>/author/<%= user.name %>'><%= translation('tag.contributors.notes') %> &raquo;</a></td>

- 62: <th> <%= t('tag.contributors.people_who_are_following') %> </th>
+ 62: <th> <%= translation('tag.contributors.people_who_are_following') %> </th>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by Angelvicks** [comment]
Hello @nicoleiocana please can i work on this issue?. I am an Outreachy Applicantfor 2020.

**Comment by nicoleiocana** [comment]
@Angelvicks Why yes, it's all yours! I too am a fellow Outreachy Applicant for 2020 🙂

**Comment by Angelvicks** [comment]
ok thanks @nicoleiocana

**Comment by Angelvicks** [comment]
ok thanks @nicoleiocana

**Comment by Angelvicks** [comment]
#7760 that is the pull request. Thanks for letting me do this.

**Comment by nicoleiocana** [comment]
PR (https://github.com/publiclab/plots2/pull/7760) approved and merged into Master.
