### ISSUE TITLE
Change function t to translation in app/views/user_sessions/_form.html.erb

### ISSUE THREAD

**Issue by nicoleiocana** [publiclab/plots2#7737]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/user_sessions/_form.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/user_sessions/_form.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
- 6: <h2><%= raw t('user_sessions.new.log_in') %></h2>
+ 6: <h2><%= raw translation('user_sessions.new.log_in') %></h2>

- 9: <%= raw t('user_sessions.new.sign_up') %></a> <%= raw t('user_sessions.new.to_join') %>
+ 9: <%= raw translation('user_sessions.new.sign_up') %></a> <%= raw translation('user_sessions.new.to_join') %>

- 28: <label for="username"><%= t('user_sessions.new.username') %></label>
+ 28: <label for="username"><%= translation('user_sessions.new.username') %></label>

- 32: <label class="control-label" for="password"><%= t('user_sessions.new.password') %></label>
+ 32: <label class="control-label" for="password"><%= translation('user_sessions.new.password') %></label>

- 47: tabindex="3"><%= t('user_sessions.new.log_in') %></button>
+ 47: tabindex="3"><%= translation('user_sessions.new.log_in') %></button>

- 51: <%= f.check_box :remember_me %> <%= t('user_sessions.new.remember_me') %>
+ 51: <%= f.check_box :remember_me %> <%= translation('user_sessions.new.remember_me') %>

- 57: <p class="form-grey"><%= raw t('user_sessions.new.reset_by_clicking_here', :url1 => "/reset/") %></p>
+ 57: <p class="form-grey"><%= raw translation('user_sessions.new.reset_by_clicking_here', :url1 => "/reset/") %></p>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by stone95** [comment]
Hello,

I would like to claim this issue please.

**Comment by nicoleiocana** [comment]
@stone95 Hi. This isssue is all yours to claim. Good luck!

**Comment by stone95** [comment]
I have made a mistake somehow. Can someone help me figure out where?

After making the changes and being in the branch, I expect "git status" to show me that I have altered _form.html.erb. However, the status is:

On branch Change-function-t
nothing to commit, working tree clean

I have:
- forked in githhub
- executed command git clone https://github.com/stone95/plots2.git
- git branch Change-function-t
- git checkout Change-function-t 
- modified file via nano
- git checkout master
- git add -A 
- it commit -m "Change function t"
- git status

What did I do wrong?

**Comment by nicoleiocana** [comment]
When you `git checkout master` you returned to the master branch, but you didn't make the changes on the master branch, you made them on the Change-function-t branch. If you `git checkout Change-function-t` and then `git status` it should show you there is a change in the file app/views/user_sessions/_form.html.erb . Hope this helps.

If that doesn't work, then the only thing that I can think of is that you never saved the changes (Ctrl + S).

**Comment by stone95** [comment]
> When you `git checkout master` you returned to the master branch, but you didn't make the changes on the master branch, you made them on the Change-function-t branch. If you `git checkout Change-function-t` and then `git status` it should show you there is a change in the file app/views/user_sessions/_form.html.erb . Hope this helps.
> 
> If that doesn't work, then the only thing that I can think of is that you never saved the changes (Ctrl + S).

Thank you! You were correct. I did not git checkout Change-function-t. Is there a written tutorial you suggest for creating a pull request via the command line? I see several and they have differing instructions.

**Comment by nicoleiocana** [comment]
@stone95 Yeah, I do. Not only is this a written tutorial, but you will actually compare and pull request to someone's repo to experience the entire process. This was where I first learned how to complete a PR for Public Lab myself 🎉

[https://github.com/firstcontributions/first-contributions](https://github.com/firstcontributions/first-contributions)

**Comment by stone95** [comment]
Success! (I think.) I got a successful "All checks passed" upon completion of the pull request but the success message was at #7773 (https://github.com/publiclab/plots2/pull/7773)  instead of 7737.

Thank you for all of your patience with a noob. I appreciate it.

**Comment by nicoleiocana** [comment]
Yayy 🎉🎉. Good work. There were minor things to fix, but overall, awesome work! Just to clarify:

#7773 is the Pull Request that fixes the issue #7737 - I can totally see how those numbers might be confusing.

You are very welcome. No prob - we were all at that point once upon a time. Any other questions, you can always reach out to me.

**Comment by sarthak-choudhary** [comment]
Is this issue done ? If not I would like to claim it.

**Comment by nicoleiocana** [comment]
@sarthak-choudhary You got it. The issue is now yours to claim. Good luck! 😀

**Comment by ioampatzidis** [comment]
Hello, could I work on this issue?
Thank you!

**Comment by emilyashley** [comment]
Oh cool, just noting it looks like we now have two PR's open for this issue. Let's check them out for duplicate fixes. 

Thanks for this work!!

https://github.com/publiclab/plots2/pull/7979
https://github.com/publiclab/plots2/pull/7892

**Comment by cesswairimu** [comment]
It seems like this was solved in unliked PR. Closing this.... Thanks everyone
