### ISSUE TITLE
Proposal: Place Limitations on the Number of Tags in a Post

### ISSUE THREAD

**Issue by skilfullycurled** [publiclab/plots2#774]
Hey all,

Doing some data analysis work on tag co-occurrences and ran into the classic folksonomy problem of posts with many many tags. 

Folksonomies are great for eliciting tags that might not otherwise be devised, allowing the community to define it's own categories instead of a top-down approach, and for personal self expression.  That said, they also have the potential drawback of diluting their usefulness in filtering content. (and on a personal level, make tag graphs impossible to read).

Some suggestions:

1) Limit the number of tags to 3.

2) Limit the number of tags to 3 "free tags" plus + 1 location tag + 1 taxonomic tag (a predetermined set).

3) Limit the number of tags to 6.  I'm not a mathematician by any means but it's the magic network science number and not just a saying.  I can't see how any more tags then this could be of any use in finding content.

4) Do not limit any tags but include some text which offers some guidelines about what makes a good tag.

Cross post: https://groups.google.com/forum/#!topic/plots-dev/SLhzB-cq6Qk

**Comment by jywarren** [comment]
Hello @skilfullycurled -- this is an interesting proposal, and perhaps needs more discussion from organizers and/or developers. I think we could easily move forward on 4, but might also make a suggestion about the others -- that limits be per-person, and perhaps lifted if you're a moderator? What do you think?

**Comment by skilfullycurled** [comment]
I think option four definitely makes sense as an initial intervention.  Giving "advice" may encourage enough self imposed refinements to make further changes unnecessary.  

Based upon the initial feedback in the googlegroup, it seems like people are leveraging tags for different purposes.  As such, it's probably worth understanding what those are a bit more before making a formal design change so as not to disrupt anyone's workflow.  Perhaps there is something else happening which is actually calling for a different feature entirely.  My sense right now is that this would be a feature which allows personal tags for bookmarking.

To that point, your "lift for moderator" suggestion is a good one because the cohort of people using the tags for workflows specific to them, are probably of that class of people.

Related side question: Currently, can one use tags to narrow down (tag A AND tag B) or open up (tag A OR tag B) results?

**Comment by jywarren** [comment]
Hi, Ben - thanks -- so how about a new issue like "Display message when
many tags exist"

with message: 'These are a lot of tags! Learn about tagging'

and re: your search question, we don't have a "both tags" or "either tag"
search interface but I believe it'll be possible once we get the new search
system online. Those would both make  good individual issues which could be
broken up as well into a) interface design, b) routing, and c) controller
and search API work, each.

**Comment by jywarren** [comment]
I'm going to close this with the suggestion that we approach over-tagging as a moderation issue. But we could open a new issue with the 'These are a lot of tags! Learn about tagging' message if you like -- chime in, thanks!
