### ISSUE TITLE
Change function t to translation in app/views/users/_likes.html.erb

### ISSUE THREAD

**Issue by nicoleiocana** [publiclab/plots2#7740]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/users/_likes.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/users/_likes.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
- 13: <%= t('notes._notes.moderate_first_time_post') %> <br class="d-none d-lg-inline"/>
+ 13: <%= translation('notes._notes.moderate_first_time_post') %> <br class="d-none d-lg-inline"/>

- 14: <a class="btn btn-outline-secondary btn-sm" href="/moderate/publish/<%= like.id %>"><%= t('notes._notes.approve') %></a>
+ 14: <a class="btn btn-outline-secondary btn-sm" href="/moderate/publish/<%= like.id %>"><%= translation('notes._notes.approve') %></a>

- 15: <a class="btn btn-outline-secondary btn-sm" href="/moderate/spam/<%= like.id %>"><%= t('notes._notes.spam') %></a>
+ 15: <a class="btn btn-outline-secondary btn-sm" href="/moderate/spam/<%= like.id %>"><%= translation('notes._notes.spam') %></a>

- 17: <%= raw t('notes._notes.pending_approval', :url1 => '/wiki/moderation') %>
+ 17: <%= raw translation('notes._notes.pending_approval', :url1 => '/wiki/moderation') %>

- 30: <%= t('notes._notes.last_edit_by') %> <a <% if @widget %>target="_blank"<% end %> href="/profile/<%= like.latest.author.name %>"><%= like.latest.author.name %></a>
+ 30: <%= translation('notes._notes.last_edit_by') %> <a <% if @widget %>target="_blank"<% end %> href="/profile/<%= like.latest.author.name %>"><%= like.latest.author.name %></a>

- 33: | <i class="fa fa-eye"></i> <%= number_with_delimiter(like.views) %> <span class="d-none d-lg-inline"><%= t('notes._notes.views') %></span>
+ 33: | <i class="fa fa-eye"></i> <%= number_with_delimiter(like.views) %> <span class="d-none d-lg-inline"><%= translation('notes._notes.views') %></span>

- 49: <% if logged_in_as(['admin','moderator']) %><a class="btn btn-outline-secondary" href="/moderate/spam/<%= like.id %>"><i class="fa fa-ban"></i> <%= t('notes._notes.spam') %></a><% end %>
+ 49: <% if logged_in_as(['admin','moderator']) %><a class="btn btn-outline-secondary" href="/moderate/spam/<%= like.id %>"><i class="fa fa-ban"></i> <%= translation('notes._notes.spam') %></a><% end %>

- 50: <a class="btn btn-outline-secondary" style="float: right; margin-left: 1px;" href="<%= like.path %>"><%= t('notes._notes.read_more') %></a>
+ 50: <a class="btn btn-outline-secondary" style="float: right; margin-left: 1px;" href="<%= like.path %>"><%= translation('notes._notes.read_more') %></a>

- 54: <a class="btn btn-outline-secondary" href="#"><i class="fa fa-ban-circle"></i> <%= t('notes._notes.spam') %></a>
+ 54: <a class="btn btn-outline-secondary" href="#"><i class="fa fa-ban-circle"></i> <%= translation('notes._notes.spam') %></a>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by SusannaDiV** [comment]
Hi! May I tackle this issue?

**Comment by nicoleiocana** [comment]
@SusannaDiV Hi! Yes you may.

**Comment by SusannaDiV** [comment]
@nicoleiocana thank you so much! Please review my pull request, if you may :)

**Comment by nicoleiocana** [comment]
@SusannaDiV I saw on your PR #7753 that you closed it? Didn't @Tlazypanda approve of your changes? 😕

**Comment by SusannaDiV** [comment]
> @SusannaDiV I saw on your PR #7753 that you closed it? Didn't @Tlazypanda approve of your changes?

@nicoleiocana My mistake, I'm really sorry (got confused for a second reading the report) - I reopened it, thanka for pointing that out :)

**Comment by nicoleiocana** [comment]
@SusannaDiV Susanna Oh hey, no need to apologize. I just wanted you to get the credit that you deserve. Great job!

If you want to know why one of those tests failed, it's because when you cloned the plots2 repo back in Mar 7, there have been 34 updates since then. So, before you made the changes on your branch, you should have updated your forked repo with the updated master from plots2, then submit the changes. Not to worry though, I made the exact same mistake and @Tlazypanda was the one who helped me out. Small world.

**Comment by Tanmayi03** [comment]
Hi, may I work on this issue??

**Comment by nicoleiocana** [comment]
@Tanmayi03 Sorry, SusannaDiV re-opened this issue back up and it has successfully passed all of its tests. It will most likely be merged then closed. I still have issue #7730 open, would you like to be assigned this one?
