### ISSUE TITLE
Weekly community Check-In #53 - Be Productive

### ISSUE THREAD

**Issue by govindgoel** [publiclab/plots2#7749]
<p>We all at Public Lab <g-emoji class="g-emoji" alias="balloon" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f388.png"><img class="emoji" alt="balloon" height="20" width="20" src="https://github.githubassets.com/images/icons/emoji/unicode/1f388.png"></g-emoji> - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal <g-emoji class="g-emoji" alias="dart" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f3af.png"><img class="emoji" alt="dart" height="20" width="20" src="https://github.githubassets.com/images/icons/emoji/unicode/1f3af.png"></g-emoji> . You are also welcome to share fun-fact <g-emoji class="g-emoji" alias="smile" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f604.png"><img class="emoji" alt="smile" height="20" width="20" src="https://github.githubassets.com/images/icons/emoji/unicode/1f604.png"></g-emoji> , new ideas <g-emoji class="g-emoji" alias="bulb" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4a1.png"><img class="emoji" alt="bulb" height="20" width="20" src="https://github.githubassets.com/images/icons/emoji/unicode/1f4a1.png"></g-emoji> , your learning goals <g-emoji class="g-emoji" alias="ballot_box_with_check" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/2611.png"><img class="emoji" alt="ballot_box_with_check" height="20" width="20" src="https://github.githubassets.com/images/icons/emoji/unicode/2611.png"></g-emoji>.</p>
<p>We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. <g-emoji class="g-emoji" alias="100" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4af.png"><img class="emoji" alt="100" height="20" width="20" src="https://github.githubassets.com/images/icons/emoji/unicode/1f4af.png"></g-emoji></p>
<h2>Be productive while doing work from home</h2>
<p>While the pandemic is having an impact globally I would request everyone to be safe and stay healthy.This week please say hi and let us know with what ways you are trying to be more  productive while working from home.</p>
<h2>GSoC and Outreachy applications end soon⌛</h2> 
<strong>To GsoC applicants:</strong>
<ul>
<li>
We hope that everyone has submitted their proposal on the PublicLab website and completed their applications through GSoC portal as well otherwise please do it asap.
</li>
<li>
If facing any kind of difficulties or have doubt feel free to ask <a href="https://github.com/publiclab/plots2/issues/7617" data-hovercard-type="issue" data-hovercard-url="/publiclab/plots2/issues/7617/hovercard">here</a>
</li>
<li>
Deadline: March 31st.
</li>
</ul>
<strong>To Outreachy Applicants</strong>
<ul>
<li>
We hope that everyone has submitted their proposal on the PublicLab website otherwise please do it asap.
</li>
<li>
If facing any kind of difficulties or have doubt feel free to ask <a href="https://github.com/publiclab/plots2/issues/7617" data-hovercard-type="issue" data-hovercard-url="/publiclab/plots2/issues/7617/hovercard">here</a>
</li>
<li>
Deadline: April 7th.
</li>
</ul>
<h2>Next Check-in</h2>
<p>If you would like to open the next weekly check-in please comment below..I am glad to guide you if its your first time or have any questions.</p>
<p>Thanks everyone for making PL awesome and have a great week ahead <g-emoji class="g-emoji" alias="balloon" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f388.png"><img class="emoji" alt="balloon" height="20" width="20" src="https://github.githubassets.com/images/icons/emoji/unicode/1f388.png"></g-emoji></p>

**Comment by govindgoel** [comment]
@sssash18, @Tlazypanda, @chinmay021, @Srija616, @AnnaMinakova, @greenbrown, @taysa91, @TaishiRoy, @yagmurbaydogan, @Shulammite-Aso, @Jigyasa-Kumari, @moliver4, @TroydonAnabolic, @justinelai, @Janetsomehow, @keshav234156, @Snouzy, @dependabot-preview[bot], @stevenalila, @Digiox, @NitinBhasneria, @yandu31, @milosv1, @jamescapps, @Nevenem, @chirag-wadhwa, @yogeshjdeshmukh, @omizrahi99, @cesswairimu, @theOpetunde, @sailahonkanen, @robin-natale, @avidler, @nstjean, @keshavsethi, @ccyccyccy, @JordanTFite, @krsudhanshu, @3ng7n33r, @Odisseuss, @imajit, @VladimirMikulic, @rehasantiago, @urvashigupta7, @HashTalmiz, @vinitshahdeo, @dragonwarp, @z-arnott, @JanviMahajan14, @mantinone, @DouglasLutz, @seabl, @jywarren, @crisner, @Uzay-G, @govindgoel

**Comment by govindgoel** [comment]
@Rishabh570 @sashadev-sky @vaibhavmatta @shubhscoder @aSquare14 @sidntrivedi012 @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77 @milaaraujo @kevinzluo @shipcy @developer22-university @keshavsethi @emilyashley @smarty1palak @daemon1024 @jywarren

**Comment by govindgoel** [comment]
Thanks for the help @cesswairimu 🎉

**Comment by cesswairimu** [comment]
Great check-in...thanks @govindgoel

**Comment by alaxalves** [comment]
@govindgoel Gsoc's application deadline is actually March 31st. ;) via https://summerofcode.withgoogle.com/how-it-works/#timeline

**Comment by alaxalves** [comment]
This week I focused on improving my GSoC proposal after a set of feedbacks from my PL friends  (available [here](https://publiclab.org/notes/alaxallves/03-06-2020/gsoc-proposal-2020-spectral-workbench-rails-and-devops-upgrades?_=1583504846)). I reviewed my scheduling and realised it could be possible upgrading both Spectral Workbench Rails' and the Mapknitter Image Exporting modules. I think it’s possible to accomplish both projects since I am already familiar with Mapknitter's codebase, since I’ve been a heavy contributor for a quite amount of time and also because Spectral Workbench has a small codebase in comparison to Mapknitter’s and Plots2’s, so the Rails upgrade is going to be less painful. And also we could skip and go straight further with some Rails versions without any prejudice. And since improving the Mapknitter's Exporting module is a priority I took the liberty of incorporating this core project to my proposal.

**Comment by Tlazypanda** [comment]
Hey guys,
The past week got some of my pending prs merged and updated my proposal a bit to expand the printability part as suggested by @jywarren . Had been a little busy with assignments and stuff as we are having online classes now so now will be opening some new fto issues and reviewing prs too. How's everyone else doing? :sweat_smile:

**Comment by gr455** [comment]
Hi everyone,
This week, last week I opened a couple PRs to streamline the testing process of spectral. This week, I have a few online classes and a semester project to keep me busy 😅

**Comment by emilyashley** [comment]
Hello everyone. Checking in <3 Hope everyone is well and being kind to themselves. Since it is springtime in New Orleans, while working from home I've been making sure to open the windows or bring in a flower or two from the garden to keep at the table to brighten my mood. And I definitely think mood helps my productivity.

Seeing all these GSOC proposals coming in is definitely inspiring as well! Y'all are so great.

**Comment by Medlineme4** [comment]
Should everybody be part of this or is it for a few people? Seems I am confused

**Comment by Medlineme4** [comment]
Since the stay at home order began, I have been working on a few projects and I have also been doing some write-ups

**Comment by TroydonAnabolic** [comment]
Still trying to find a programming job, studying full stack development, and game development to increase my chances of getting a developer job. Decided to take on a technical support representative job to keep the income flowing while I improve my full stack skills and continue my job hunt.

**Comment by nstjean** [comment]
Hi all! Being productive at home is not easy right now, as I'm used to it being just me here working! Now I have the whole family home. I am working on a freelance project that is currently somewhat urgent. In order to try to be more productive I bought a laptop, I'm setting it up with Ubuntu and getting everything installed so I can hide from the chaos of the family.

**Comment by cesswairimu** [comment]
Hey all, would anyone would like to open this week's check-in?

**Comment by Alexjake660** [comment]
@cesswairimu Thank you. I'd need a little guidance on how to go about it though.

**Comment by cesswairimu** [comment]
> Should everybody be part of this or is it for a few people? Seems I am confused

Yeah @Medlineme4 the check-in is for everyone in the community

**Comment by cesswairimu** [comment]
Sure @Alexjake660, just ping me incase of anything...

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/7793 thanks everyone...Thanks @Alexjake660 :+1:
