### ISSUE TITLE
Separate display of power tags from normal tags

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#775]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled.

****

[Power tags](https://publiclab.org/wiki/power-tags) (in `key:value` format) and regular tags are mixed in display: 

https://publiclab.org/notes/liz/08-30-2016/check-out-these-activity-grids#tags

We should show the power tags separately, perhaps show them in purple or grey, and also link the words "Power tags" in the label to the above explanation of them. 

This may also be where we could show an expanded interface for adding powertags, as in #496 -- and should in any case link to power tags documentation at https://publiclab.org/wiki/power-tags

Tags are displayed in this template: https://github.com/publiclab/plots2/blob/master/app/views/tag/_tagging.html.erb#L5

`@node.community_tags`, used there, is defined here -- it's just an alias to an ActiveRecord relation: https://github.com/publiclab/plots2/blob/master/app/models/drupal_node.rb#L436

We should use the more specific `@node.power_tag_objects` and `@node.normal_tags` to separate these out ([see here for docs](https://github.com/publiclab/plots2/blob/master/app/models/drupal_node.rb#L385-L399)).

If we can think of a more compact way to display these, that'd be great, too!

**Comment by jywarren** [comment]
@ananyo2012 , perhaps this'd be a good GCI candidate?

**Comment by ananyo2012** [comment]
Yes this involves work on CSS and designing as well. A good GCI candidate.

**Comment by ananyo2012** [comment]
Sure :blush: Happy to offer any help!
ᐧ

**Comment by gaeun** [comment]
@ananyo2012 @jywarren I think we can close this via #1174.

**Comment by ananyo2012** [comment]
Ah thanks!
