### ISSUE TITLE
Profile picture can be updated without entering password but bio cant be added 

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#7756]
### Please describe the problem (or idea)
In the current scenario it is possible to update the profile picture in the edit profile without entering current password but bio can't be added without entering the current password.

So either updation should be allowed without entering current password for both profile picture and bio or it should not be allowed for anything without entering current password. Important for consistency across the app.

## Gif  
![img1](https://im.ezgif.com/tmp/ezgif-1-8ebee88a83c5.gif)
![img2](https://im.ezgif.com/tmp/ezgif-1-1fd335b650cd.gif)

### Please show us where to look

https://publiclab.org/ ...

**Comment by Tlazypanda** [comment]
@VladimirMikulic @jywarren can you kindly approve? Thanks :v:

**Comment by VladimirMikulic** [comment]
I would leave it without a password, since it's not something sensitive like confirming an email, 2FA...

**Comment by Tlazypanda** [comment]
@VladimirMikulic so bio updation should be allowed without entering current password right?

**Comment by VladimirMikulic** [comment]
Make sense to me. @nstjean @cesswairimu what do you guys think?

**Comment by nstjean** [comment]
Yes I agree, they should be consistent and it doesn't need a password check.

**Comment by cesswairimu** [comment]
@jywarren @emilyashley what do you think?

**Comment by emilyashley** [comment]
Hmm, yeah, that sounds okay to me. 

I think email, location, and location privacy settings are things I **would** expect password validation for. Are either of those editable from the bio section? (Thanks, still learning how all the pieces interact :) )

**Comment by ebarry** [comment]
Ok so this is ready to approve if we can verify that changing the account's email, changing the location, and changing the location privacy settings are behind password validation.

**Comment by ebarry** [comment]
Checked on my account: 
- changing email address is behind the password.

**Comment by Tlazypanda** [comment]
@ebarry Thanks for the update! Oops my bad :sweat_smile: Maybe I can modify this pr to just allow changing the bio without password but require password for changing the email ...will have to look into this though :sweat_smile:
