### ISSUE TITLE
Toast notification message after following returns the array in the msg

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#7757]
### Please describe the problem (or idea)
On following a tag the toast/ notification pop up returns the array of followed. This can be modified to return a string of followed or some other message which makes sense to the non-coder users of Public Lab.
![image](https://user-images.githubusercontent.com/33183263/77930652-c9a0b680-72c8-11ea-9fdb-92f7c6936147.png)

### Please show us where to look

https://publiclab.org/dashboard

**Comment by Tlazypanda** [comment]
@VladimirMikulic @jywarren can you kindly approve? Thanks :v: Also what do you think the message should be?

**Comment by VladimirMikulic** [comment]
I agree, this should be improved. Showing data structures to the user is not pleasant :)
