### ISSUE TITLE
Follow checkbox doesn't update according to checked boxes

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#7762]
### Please describe the problem (or idea)
> What happened just before the problem occurred? Or what problem could this idea solve?
In the current behaviour unchecking boxes in the follow tab doesn't update the follow tab.

## GIF  
![follow](https://user-images.githubusercontent.com/33183263/78030638-0a0f3b80-7380-11ea-8099-a155675d695a.gif)

### Please show us where to look

https://publiclab.org/dashboard

## Thank you!

**Comment by Tlazypanda** [comment]
@VladimirMikulic @jywarren @cesswairimu can you kindly approve this issue? Thanks :v:

**Comment by VladimirMikulic** [comment]
👍
