### ISSUE TITLE
Layout issues on editor page at /post

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#7763]
Something weird happened to our post page after #7534, and we seem to be having some layout bugs now:

https://stable.publiclab.org/post

![image](https://user-images.githubusercontent.com/24359/78037916-26888500-733a-11ea-8af1-83a67ea7ed52.png)

we may have to do some part of this differently! No worries, we'll figure it out!

_Originally posted by @jywarren in https://github.com/publiclab/plots2/pull/7534#issuecomment-606661240_

**Comment by keshav234156** [comment]
@jywarren Couldn't get what weird in this.Can you  please point out what wrong at https://stable.publiclab.org/post .Thanks!!

**Comment by keshav234156** [comment]
Search Bar ?

**Comment by jywarren** [comment]
I just uploaded a screenshot - there seems to be some folding of the navbar yeah -- and the publish button looks different, i think because our customizations to the bootstrap styles are now overridden by a second Bootstrap include. Very odd!

I wonder if we should revert the 2nd bootstrap include and dig deeper into the editor buttons issue first?

**Comment by jywarren** [comment]
Would you be able to help out with this? Perhaps the fastest initial step would be to revert, merge that, then continue on editor buttons?

**Comment by keshav234156** [comment]
@jywarren ok, Would be happy to help.Reverting Pr now.

**Comment by jywarren** [comment]
I wonder if... we need to trace the CSS for the editor buttons using the chrome dev console. I can do this but we are trying to republish code to the production site today, so reverting first would be great. Thank you so much!! Such a fast response! ❤️

**Comment by keshav234156** [comment]
#7764

**Comment by keshav234156** [comment]
Hmm, So basically there were some unused button classes from bootstrap that were present. Now as bootstrap has been included there styles are visible. Should we remove that unused classes?

**Comment by ebarry** [comment]
I think this issue is fixed and could be closed now?
