### ISSUE TITLE
Weekly community Check-In #53 - Don't Give Up

### ISSUE THREAD

**Issue by Alexjake660** [publiclab/plots2#7793]
We all at Public Lab :balloon: - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal :dart:. You are also welcome to share fun-fact :smile:, new ideas :bulb:, your learning goals :ballot_box_with_check:.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. :100:

### Don't Give Up
Programmers are one(1) of the most resilient bunch of people out there, taking on problems no other people will or can take and keeping at it till it's solved. Getting great results that make the world a better place. Sometimes those problems seem insurmountable and impossible to solve but yet we undertake them, often times having to learn new technologies and skills to do this. As you work this week, remember not to give up, remember why you started in the first place, and be rest assured with the confidence that you can do it.

#### Outreachy applications ends today⌛
To Outreachy Applicants
- We hope that everyone has submitted their proposal on the PublicLab website otherwise please do it asap in the next couple of hours.
- If facing any kind of difficulties or have doubt feel free to ask [here](https://github.com/publiclab/plots2/issues/7617)
- Deadline: April 7th, 4:00pm UTC.

#### Next Check-in
If you would like to open the next weekly check-in please comment below.

Thanks everyone for making PL awesome and have a great week ahead :balloon:

**Comment by cesswairimu** [comment]
Thanks @Alexjake660 :tada:

**Comment by cesswairimu** [comment]
@sssash18, @Tlazypanda, @chinmay021, @Srija616, @AnnaMinakova, @greenbrown, @taysa91, @TaishiRoy, @yagmurbaydogan, @Shulammite-Aso, @Jigyasa-Kumari, @moliver4, @TroydonAnabolic, @justinelai, @Janetsomehow, @keshav234156, @Snouzy, @dependabot-preview[bot], @stevenalila, @Digiox, @NitinBhasneria, @yandu31, @milosv1, @jamescapps, @Nevenem, @chirag-wadhwa, @yogeshjdeshmukh, @omizrahi99, @cesswairimu, @theOpetunde, @sailahonkanen, @robin-natale, @avidler, @nstjean, @keshavsethi, @ccyccyccy, @JordanTFite, @krsudhanshu, @3ng7n33r, @Odisseuss, @imajit, @VladimirMikulic, @rehasantiago, @urvashigupta7, @HashTalmiz, @vinitshahdeo, @dragonwarp, @z-arnott, @JanviMahajan14, @mantinone, @DouglasLutz, @seabl, @jywarren, @crisner, @Uzay-G

**Comment by cesswairimu** [comment]
@govindgoel @Rishabh570 @sashadev-sky @vaibhavmatta @shubhscoder @aSquare14 @sidntrivedi012 @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77 @milaaraujo @kevinzluo @shipcy @developer22-university @keshavsethi @emilyashley @smarty1palak @daemon1024 @jywarren

**Comment by Divy123** [comment]
Hello everyone!!

Nice theme @Alexjake660 . This is something most important right now. While whole world is fighting right now, we need to stay strong. But it's the beauty of open source that it does not really impose any restrictions on our work culture and it has taught many others for the same. And when many people are still struggling finding the right way to utilise their time, I believe contributing to the open source organisations can be one of the most satisfying as well as self-learning exercise all can practice.

And to add to that we have two equal opportunities, GSoC and Outreachy. I believe the motivation is here, the time is here and let's all of us get started with our full responsibility and enthusiasm to tackle this pandemic in the most productive way.

**Comment by gr455** [comment]
Hi everyone! The past week has been an attempt to complete all the piled up work from university 😅 and looks like so will the coming week be. I will continue to contribute once I'm done with that.
Aside from that, totally agree with @Divy123 , open source is a great way to do something productive in these tough times :)

**Comment by alaxalves** [comment]
Last week I have been busy accomplishing some personal projects. Had not much time to contribute with the PL community, but I got to successfully open a PR at the Mapknitter-Exporter repo. This is the the link: https://github.com/publiclab/mapknitter-exporter/pull/27. I'd like someone to please review it @jywarren @cesswairimu @SidharthBansal @icarito

**Comment by Medlineme4** [comment]
The past week was challenging as I had to complete some personal projects. I also had to begin new tasks that will my stay at home and an enjoyable one. I have also read few chapters of some books I have procrastinated about.

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/spectral-workbench/issues/498 thanks everyone

**Comment by Alexjake660** [comment]
@cesswairimu I just noticed this should have been check-in #54 instead of #53. Sorry about this error on my part. Can the numbers be corrected?

**Comment by cesswairimu** [comment]
Oh I missed it too...no worries I will edit it. Thanks
