### ISSUE TITLE
[urgent] Research note posting not appearing; error shown

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#7799]
https://publiclab.org/notes/suyash1814/03-07-2020/gsoc-2020-proposal-site-wide-accessiblity-on-publiclab-org

This shows a 500 error! cc @sssash18 @Shulammite-Aso this may have affected you both? Suyash i found yours listed here: https://publiclab.org/notes/author/suyash1814

@Shulammite-Aso can you share your publiclab.org username here so we can track if yours had a similar issue?

**Comment by jywarren** [comment]
I believe I found this is an issue with the translation system. Linking the Sentry report...

**Comment by jywarren** [comment]
```
ActionView::Template::Error
undefined method `translation' for I18n:Module
Did you mean?  translate
               translate!
NoMethodError
undefined method `translation' for I18n:Module
Did you mean?  translate
               translate!
```

```
    <%= render partial: 'sidebar/notes', locals: { notes: @node.responses, title: I18n.translation('sidebar._related.responses_to_note'), node: @node } %>
```

I've made a VERY fast quick fix here: https://github.com/publiclab/plots2/commit/81114cf5cd2954e029f40f7d43282327b01060f0

I will rush this into production which should take about an hour. Please check back and update here if it works! Thank you!

**Comment by jywarren** [comment]
thanks folks, if you can check your post again once this process completes that would be really helpful. I hope I've found the error and this is the process republishing the live site with the new fix: https://jenkins.laboratoriopublico.org/job/Deploy%20Plots2/53/

**Comment by Shulammite-Aso** [comment]
> https://publiclab.org/notes/suyash1814/03-07-2020/gsoc-2020-proposal-site-wide-accessiblity-on-publiclab-org
> 
> This shows a 500 error! cc @sssash18 @Shulammite-Aso this may have affected you both? Suyash i found yours listed here: https://publiclab.org/notes/author/suyash1814
> 
> @Shulammite-Aso can you share your publiclab.org username here so we can track if yours had a similar issue?

Yeah, the 500 error here is exactly the same I'm getting. 
My publiclab.org username is @asoamarachi

**Comment by Shulammite-Aso** [comment]
I should publish my post again once the process completes☺

**Comment by Shulammite-Aso** [comment]
I just saw on my dashboard now that my post got submitted actually, with pending approval. Only I can't access the content when I click on it. So I may not need to resubmit my post.

**Comment by jywarren** [comment]
Initial issue fixed! I will approve @Shulammite-Aso's post now and i hope the same error will be resolved there too!

**Comment by jywarren** [comment]
Approved. I believe this is all resolved now -- thank you SO MUCH for reporting, and if there are more issues i can take another look!
