### ISSUE TITLE
All updates filter in dashboard

### ISSUE THREAD

**Issue by keshavsethi** [publiclab/plots2#7809]
1.) "All update" filter in the dashboard does not work properly. Even after selecting the filter as shown in the image, the dashboard shows all the updates like wiki, comments, notes, etc.
2.)There is also an issue in its css as All update text color becomes grey instead of white as shown.
3.) select all button is not working properly as shown.
https://publiclab.org/dashboard
![Screenshot from 2020-04-13 00-24-50](https://user-images.githubusercontent.com/36025262/79077352-a4776380-7d1e-11ea-8f21-15b3034066e7.png)

@jywarren @SidharthBansal please review it
Thanks

**Comment by keshavsethi** [comment]
@jywarren @cesswairimu @SidharthBansal can I proceed on this issue??

**Comment by cesswairimu** [comment]
I thought we fixed this on another PR let me try to find it
