### ISSUE TITLE
Table display issue on Tag Contributor pages

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#7817]
### Please describe the problem (or idea)

There are a couple small display issues on Tag Contributor pages* that if fixed would entirely upgrade the user experience of someone searching on Public Lab for people researching topics that are also of interest to you. 

*Tag Contributor pages have the URL structure: https://publiclab.org/contributors/foo  , where `foo` represents a tag. 

> What happened just before the problem occurred? 

I was browsing the `evidence` tag via https://publiclab.org/tag/evidence and wanted to see who contributed this type of content. I clicked on "23 contributors" -- see screenshot below of where this link is on the Tag Page: 
<img width="1157" alt="Screen Shot 2020-04-14 at 2 02 47 PM" src="https://user-images.githubusercontent.com/161439/79258184-c07f2000-7e58-11ea-9754-c5df6ecb8661.png">

> What did you expect to see that you didn't?

The link brought me to https://publiclab.org/contributors/evidence , which is great. However, the layout on this page has a couple issues: 

1. Both columns in the two column table are too narrow for the content they contain and for their header labels. The column headers are labelled "People who've posted" and "Notes". "People who've posted" breaks onto two lines. The content in Notes is forced to break onto two lines even though it contains only 7 characters. 
2. There is a third column which only appears once the user scrolls down to the bottom row of the first two columns. Then this third column appears at right, labelled "People who are following". This column lacks content. 

See gif below: 
![contributors-display](https://user-images.githubusercontent.com/161439/79258681-83fff400-7e59-11ea-9c2b-541050c93793.gif)

### Please show us where to look

Tag Contributor pages such as https://publiclab.org/contributors/evidence

There are some closed issues related to this page which can be seen at #993 (create this type of page), #2444 and #6675 (counting the number of contributors correctly)

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

liz

**Comment by jywarren** [comment]
I believe the lines of code governing this page are here! 

https://github.com/publiclab/plots2/blob/f70e6ea791d78b098c2556ebecf58402c030f6c2/app/views/tag/_contributors.html.erb#L44-L69

**Comment by sanchibansal340** [comment]
Is this issue open?

**Comment by ebarry** [comment]
Yes, thank you, this issue is open!

**Comment by sanchibansal340** [comment]
When I opened the site, it is not appearing as show in the video

**Comment by jywarren** [comment]
Hi, did you try https://publiclab.org/contributors/evidence?

How about https://publiclab.org/contributors/water-quality ?

**Comment by sanchibansal340** [comment]
https://drive.google.com/file/d/1QGaSavgEuES-I-faI7-ozNSaiI4MGIZT/view?usp=drivesdk

It's showing like in both my laptop and phone. Can you please check if you can view the video?
Thanks

**Comment by ebarry** [comment]
Thank you @sanchibansal340 -- i agree with you. I see that your video shows that the display for   https://publiclab.org/contributors/water-quality is working properly for you. 

It is looking even worse for me, at least at the current width our screen is set to. 

<img width="628" alt="Screen Shot 2020-04-28 at 11 44 46 AM" src="https://user-images.githubusercontent.com/161439/80508375-f8509200-8945-11ea-872b-7dc129cdea8e.png">

**Comment by sanchibansal340** [comment]
Okay I will work on it

**Comment by ebarry** [comment]
Hi @sanchibansal340 , thank you for writing back so quickly after it took me 7 days to write back to you! i'm realizing through working with @jywarren and @emilyashley that there are several pieces to this issue. haha 😅

1. The Header Text. I just made this issue to address it https://github.com/publiclab/plots2/issues/7847 

2. The appearance of the table at different widths. I'll write more on this in a couple hours.

**Comment by sanchibansal340** [comment]
Okay @ebarry . It isn't a problem, I realize that you must be busy.

**Comment by ebarry** [comment]
To address _2) the appearance of the table at different widths_, luckily the solution already exists—however, it's only visible at less than ~750 pixels of screenwidth. Perhaps this is referred to as "Media Width", as in for phones?

Here's the table looking great, as @sanchibansal340 also showed in video above: 

<img width="617" alt="Screen Shot 2020-04-28 at 4 44 02 PM" src="https://user-images.githubusercontent.com/161439/80535902-842ae400-896f-11ea-9fa8-6414a49da637.png">

Here's what's great about it: 
- there is no line break in the values of the Notes column. This is good because the height of all rows in the table can remain normal, instead of being exaggerated in height which you can see at greater screenwidths. 
- The table of "People who are following" lines up next to the first table of "People who have posted" and "Notes", with appropriate white space separating the grey horizontal lines of each table, conveying that these are separate tables. At other screen widths, this table's headers are pushed to the bottom, and values are not displayed. 

## Next Steps

- [ ] Find code links for where the width of the screen summons different table layouts
- [ ] Set the display of the table to be shown as it is at less than 750px width **_at all widths._**

**Comment by ebarry** [comment]
Hi SanchiBansal340, i did not mean to "assign myself" to fix the issue yesterday, I have assigned it to you if you would still like it. 🌳

**Comment by sanchibansal340** [comment]
Yes, I want to work on it. Sorry was a little busy due to exams. I will start in 3 days, will that be okay?

**Comment by ebarry** [comment]
Yes, thank you so much! Good luck on exams, and do get plenty of rest too :)

**Comment by ebarry** [comment]
Hi @SanchiBansal340, how did exams go?

**Comment by sanchibansal340** [comment]
Hey @ebarry. The exams went well, I am working on the issue and will be done with it in 2 days.
Sorry for not updating you.

**Comment by sanchibansal340** [comment]
@ebarry Why is that the source code on Chrome Dev tools is different and actual code is completely different? 
Also do I have to setup the code according to the prerequisites in the README.md. I didn't because I thought that I am just working on HTML and CSS thus I won't have to.

**Comment by sanchibansal340** [comment]
@ebarry by removing 'position:absolute',  'People who are following' table is going below the 'People who've posted table'. Do you want this kind of format or do you want the table side by side only?

Attached the screenshots below of how that looks
![Screenshot (35)](https://user-images.githubusercontent.com/51092036/81807801-5e3f3b00-953c-11ea-944a-142ef90e0879.png)
![Screenshot (36)](https://user-images.githubusercontent.com/51092036/81807804-5f706800-953c-11ea-8f56-119b96ffb02f.png)
![Screenshot (37)](https://user-images.githubusercontent.com/51092036/81807807-60a19500-953c-11ea-874d-c449edf9b410.png)
![Screenshot (38)](https://user-images.githubusercontent.com/51092036/81807810-61d2c200-953c-11ea-822a-fbd1adc00035.png)
![Screenshot (39)](https://user-images.githubusercontent.com/51092036/81807812-626b5880-953c-11ea-9d28-bf9c5215d6b7.png)
![Screenshot (40)](https://user-images.githubusercontent.com/51092036/81807813-6303ef00-953c-11ea-9f81-dcfc43bb2e8a.png)

**Comment by ebarry** [comment]
@sanchibansal340 these screenshots are so helpful in describing the issue! 

In mobile view, it would be helpful to move the table for "People who are following" down below the other tables, but this isn't what this issue is about, so let's set this part aside for now. 

We are looking to retain the side-by-side view of both tables with appropriate column widths. Is there a way to see where the CSS changes on screensizes greater than 750px? I tried to look at the page using developer tools myself but i am not familiar enough to find what i'm looking for!

**Comment by patcon** [comment]
Hey all! Don't want to confuse this with another cook, but seems like maybe there's a little bootstrap usage issue at the core of this, that's complicating things from the get-go :)

From [bootstrap docs on Nesting the grid system](https://getbootstrap.com/docs/4.0/layout/grid/#nesting):

> To nest your content with the default grid, **add a new .row and set of .col-sm-\* columns within an existing .col-sm-\* column**. Nested rows should include a set of columns that add up to 12 or fewer (it is not required that you use all 12 available columns).

When I add a new `<div class="row"></div>` _around_ the inner cols (the two `col-md-6` columns) and remove the inline styles for those same `col-md-6`divs, it seems to work out cleaner (and expands to cover the whole parent width, which seems expected):

[![screencap of modified grid](http://g.recordit.co/Eoe0281Uq3.gif)](http://recordit.co/Eoe0281Uq3)

Maybe that's related?

**Comment by ebarry** [comment]
Thanks for spotting these insights @patcon and @sanchibansal340 ! It would really be great to get our contributor tables looking good because Public Lab is made of contributors :) Do the next steps seem clear to anyone?

**Comment by sanchibansal340** [comment]
@ebarry I made 3 changes on Chrome Devtools. I found the 750px thing as well but wasn't able to take screenshot of it. I have attached the screenshots of the changes made and how the table looks with it.
![Screenshot (53)](https://user-images.githubusercontent.com/51092036/82566988-5ade2c00-9b9a-11ea-96d9-729322190d51.png)
![Screenshot (55)](https://user-images.githubusercontent.com/51092036/82566994-5dd91c80-9b9a-11ea-8f8a-bec7e41e5ac6.png)
![Screenshot (56)](https://user-images.githubusercontent.com/51092036/82566996-5f0a4980-9b9a-11ea-9fea-22d59b34f5d8.png)

**Comment by cesswairimu** [comment]
> @ebarry Why is that the source code on Chrome Dev tools is different and actual code is completely different?
> Also do I have to setup the code according to the prerequisites in the README.md. I didn't because I thought that I am just working on HTML and CSS thus I won't have to.

Hey @sanchibansal340 yeah you will need to install the project inorder to work on this...but you could also do it on github but you will have trouble testing the implementation also we normally require screenshots for ui changes. Thanks for the great investigations :tada:

**Comment by cesswairimu** [comment]
@sanchibansal340 these files are rendered as partials at https://github.com/publiclab/plots2/blob/master/app/views/tag/show.html.erb and these partials are in this folder https://github.com/publiclab/plots2/tree/master/app/views/tag/show  let me know if you need more pointers on the code. Thanks

**Comment by cesswairimu** [comment]
@patcon @sanchibansal340 @ebarry great detective work here :rocket: Thanks

**Comment by ebarry** [comment]
Hi @sanchibansal340 , do you feel interested in figuring out how to install the project to take this to the next step? Let us know what support would help!

**Comment by sanchibansal340** [comment]
@ebarry I will update you within a day. I am sorry that I am taking so long to solve such a simple issue.

**Comment by emilyashley** [comment]
Awesome thank you @sanchibansal340! Appreciate you picking this up.

**Comment by sanchibansal340** [comment]
@ebarry Can I setup this project on Windows?

**Comment by ebarry** [comment]
I"m not sure, but i've asked in the chatroom if anyone could help answer this. Thanks for your dedication on this, i'm so grateful and impressed. I also wish to mention that this is not a "first-timers-only" issue, meaning that there is some complexity here that might be great to address through pairing up with a more experienced contributor. Would you be open to that?

**Comment by shreyaa-s** [comment]
Hey @sanchibansal340 ! Sure you can, please refer to this https://help.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository 
If you're using github desktop https://help.github.com/en/desktop/contributing-to-projects/cloning-and-forking-repositories-from-github-desktop

If you're stuck somewhere feel free to reach out.

**Comment by sanchibansal340** [comment]
> I"m not sure, but i've asked in the chatroom if anyone could help answer this. Thanks for your dedication on this, i'm so grateful and impressed. I also wish to mention that this is not a "first-timers-only" issue, meaning that there is some complexity here that might be great to address through pairing up with a more experienced contributor. Would you be open to that?

Yes sure.

**Comment by sanchibansal340** [comment]
> @ebarry Why is that the source code on Chrome Dev tools is different and actual code is completely different?
> Also do I have to setup the code according to the prerequisites in the README.md. I didn't because I thought that I am just working on HTML and CSS thus I won't have to.

I was talking about having sqlite3 and rvm etc. Do I need them or can I work on HTML and CSS part of the project without needing to setup sqlite3 and rvm?

**Comment by Tlazypanda** [comment]
Hey @sanchibansal340 Thanks so much for your dedication towards this issue :heart: 

To answer some of your queries - 
- It is recommended that you setup this on Linux since Ruby on rails and our particular environment works better with Linux. But I believe you have a windows system (am i right not sure :question: ) so here are some ways you can setup Linux in your windows and carry out installation. Please refer [this](https://github.com/publiclab/plots2#windows-installation). 

Now my personal opinion would be to dual boot your system since later on if you want continue to work with Opensource Linux will be your saviour :100: but please do this when you are absolutely clear with how to do it (some wrong steps and your OS vanishes :confused: I will be happy to help :smile: ).
- Setting up the project is the best way to go! Since we need to check if your changes work alright locally, might require screenshots and also if the changes would require us to update tests of any kind. Since this is a bit complex of an issue might require some testing :sweat_smile: 

Hope this answer your queries! Feel free to ping me in case you run into any issues :v:

**Comment by sanchibansal340** [comment]
@Tlazypanda thank you so much for the guidelines. I will dual boot my laptop, though the part about os vanishing is a bit scary but I will ask for your help if needed.

**Comment by jywarren** [comment]
Thank you @Tlazypanda !!! And @sanchibansal340 you're awesome for taking on this challenge. Also see #3840 for group troubleshooting on installation!

**Comment by jywarren** [comment]
Hi, all, I've looked through all the solutions here and wanted to try some of them out, so I opened a pull request here: https://github.com/publiclab/plots2/pull/8021

It pushes the right-hand "followers" table below the left hand "contributors" table in narrower views which I think is appropriate; when the two tables are too narrow, they read as a single table, which is confusing. 

One thing I'd like to suggest is that we get rid of, or move, the "Related tags" text -- @ebarry do you remember where we had thought we could put those? My memory was that we wanted to display them differently because it's not a good use of an entire 25% column to the right. I'll open a new issue for this and if we can develop a plan for those, perhaps @sanchibansal340 would be interested in helping with that? I would be very happy to guide a bit on it once @sanchibansal340!

If the solution in https://github.com/publiclab/plots2/pull/8021 looks like progress, we can merge it and move to further refinements. Thanks, everyone!

**Comment by jywarren** [comment]
Ah, and just to link up regarding "Related tags", @ebarry resurfaced this discussion which i think is an appropriate place to talk about that! https://github.com/publiclab/plots2/issues/6307
