### ISSUE TITLE
open /map page more zoomed in for performance reasons

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#7822]
Really big views are a performance issue for displaying nearby people, so we should try to zoom in a bit on https://publiclab.org/map

Code is here:

https://github.com/publiclab/plots2/blob/ba9470957efeb6789ecc49bec13b270d506a9302/app/controllers/map_controller.rb#L32

And is used here in the template:

https://github.com/publiclab/plots2/blob/ba9470957efeb6789ecc49bec13b270d506a9302/app/views/map/map.html.erb#L43-L45

If there is no zoom profile tag, it seems to default to a global view! 

https://publiclab.org/map#3/40.99999999999999/-52.89453124999999

Let's not do that. Maybe choose like zoom 10 as default?

https://publiclab.org/map#10/41.88165276651511/-71.36132687330247

**Comment by jywarren** [comment]
https://publiclab.org/map#11/40.67759191045513/-73.8769419793971 zoom 10 or 11 seems to be good. here's someone.

**Comment by Shulammite-Aso** [comment]
@jywarren I don't do ruby, but I think I can take a shot at this! 
And perhaps ask a question if I get stuck.

Thanks!!

**Comment by cesswairimu** [comment]
Great :tada:  @Shulammite-Aso go ahead

**Comment by Shulammite-Aso** [comment]
Hi @jywarren @cesswairimu  please do help.😊

I'm trying to get exactly what we need to do here.  Is it to change the global view here 
https://github.com/publiclab/plots2/blob/ba9470957efeb6789ecc49bec13b270d506a9302/app/controllers/map_controller.rb#L26 from 3 to 10 or 11,  or to define another default value of say 11 while still leaving 3 as the global view?
    
Thank you!

**Comment by cesswairimu** [comment]
@Shulammite-Aso you can try different zooms see which one gives the best display and use that as the default...10 was the proposed one

**Comment by Shulammite-Aso** [comment]
> @Shulammite-Aso you could try different zooms see which one gives the best display and use that as the default...10 was the proposed one

Thanks @cesswairimu 
This will mean simply removing 3 and replacing with 10 right?
Just trying to know if there's any other code adjustment I'd need to make before this works.

**Comment by cesswairimu** [comment]
yeah just the zoom I believe. Thanks

**Comment by jywarren** [comment]
Amazing @Shulammite-Aso thank you! Reviewing now!
