### ISSUE TITLE
Titles on navbar dropdown links are all "translation missing..."

### ISSUE THREAD

**Issue by bplmp** [publiclab/plots2#7840]
### Please describe the problem (or idea)

In the dropdown links in the site's navbar, all titles are "translation missing:...", example: "translation missing: en.Tools".

If you keep your mouse hovering for a couple of seconds on the link you'll see the title text.

### Please show us where to look

![image](https://user-images.githubusercontent.com/11858154/80291276-abd93c80-8722-11ea-9b6f-9c02566a1f95.png)

### Browser, version, and operating system

Chrome.

**Comment by gauravano** [comment]
Nice catch @bplmp. Would you like to take a shot at this one?

**Comment by katungi** [comment]
@bplmp maybe i can take a look at it??

**Comment by ebarry** [comment]
Yes please do! Apologies if the invitation was not clear when @gauravano asked "would you like to take a shot at this one" -- we'd be grateful if you would @katungi 🌳🌻

**Comment by katungi** [comment]
Thanks @ebarry, will start on it asap!

**Comment by urvashigupta7** [comment]
Hi, I would like to work on this :)

**Comment by gauravano** [comment]
Hi @urvashigupta7, you can work on it. Also, saw your comment here - https://github.com/publiclab/plots2/issues/7896#issuecomment-703750493.

As you have a good understanding of the project, I would suggest solving #7896 and converting this one into an FTO issue and welcome/help whoever claims the issue. What do you think? Although, you're very welcome to solve both too :)

Thanks!

**Comment by urvashigupta7** [comment]
Sure @gauravano. Will do as you suggested :)
