### ISSUE TITLE
Weekly community Check-In #56 - Be generous, support and spread the word!

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#7844]
We all at Public Lab :balloon:  - learn, grow, work, brainstorm ideas, contribute together so why not share our ideology to help and support in whatever small way we can to whosoever needs our help. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal :dart: . You are also welcome to share fun-fact :smile: , new ideas :bulb: , your learning goals :ballot_box_with_check: 

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. :100: 

# Be generous, support and spread the word!
The world right now seems unpredictable. With people around the world losing jobs, we take it upon us to help in anyway we can to uplift mankind. Our help can be as small as extending our network to those in need, a small donation, helping those people that you see in your daily lives who are in dire need of work or even teaching your awesome skills to the world. The only way we can beat this pandemic is by growing stronger as a community and supporting each other in anyway we can.
So let's stand together and spread the love!

## This week's focus Issues

These are issues that are of high priority and requests from our large community that use the software. 
1. https://github.com/publiclab/plots2/issues/7832https://github.com/publiclab/plots2/issues/7832
2.  https://github.com/publiclab/plots2/issues/7831

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these. Or you can add more context to the ones labeled `gci-candidate` so that they can be taken up by the gci folks.  We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance :smile: 

## Next Check-in
If you would like to open the next weekly check-in please comment below.

Thanks everyone for making PL awesome and have a great week ahead :balloon:

**Comment by Tlazypanda** [comment]
@sssash18, @Tlazypanda, @chinmay021, @Srija616, @AnnaMinakova, @greenbrown, @taysa91, @TaishiRoy, @yagmurbaydogan, @Shulammite-Aso, @Jigyasa-Kumari, @moliver4, @TroydonAnabolic, @justinelai, @Janetsomehow, @keshav234156, @Snouzy, @dependabot-preview[bot], @stevenalila, @Digiox, @NitinBhasneria, @yandu31, @milosv1, @jamescapps, @Nevenem, @chirag-wadhwa, @yogeshjdeshmukh, @omizrahi99, @cesswairimu, @theOpetunde, @sailahonkanen, @robin-natale, @avidler, @nstjean, @keshavsethi, @ccyccyccy, @JordanTFite, @krsudhanshu, @3ng7n33r, @Odisseuss, @imajit, @VladimirMikulic, @rehasantiago, @urvashigupta7, @HashTalmiz, @vinitshahdeo, @dragonwarp, @z-arnott, @JanviMahajan14, @mantinone, @DouglasLutz, @seabl, @jywarren, @crisner, @Uzay-G

**Comment by Tlazypanda** [comment]
@govindgoel @Rishabh570 @sashadev-sky @vaibhavmatta @shubhscoder @aSquare14 @sidntrivedi012 @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77 @milaaraujo @kevinzluo @shipcy @developer22-university @keshavsethi @emilyashley @smarty1palak @daemon1024 @jywarren

**Comment by alaxalves** [comment]
I had been very busy with PL stuff these past weeks. I got to successfully help @icarito on shipping Mapknitter to our Google Cloud env, which involved a lot of rebasing and adjusting the existing code, Yall can get more info here --> https://github.com/publiclab/mapknitter/pull/1273. Also, along with @gr455 I got to finish the Ruby and Rails upgrade on Spectral Workbench, with slightly improved test coverage and several other improvements. 
So it has been a successful week for the PL team. \o/
Special thanks to @gr455 and @icarito that helped me a lot.

**Comment by Janetsomehow** [comment]
I have been offline for a while dealing with family stuff. I hope to start learning something new this week

**Comment by gr455** [comment]
Hi everyone!
I helped @alaxalves with Rails upgrades on SWB this week. Apart from that, I have also been working on a web application of my own for my university folks to be able to exchange notes(since the classes have been online past couple weeks, not many people actually listen to them). Currently it is hosted on <a href = "http://gr455.pythonanywhere.com">gr455.pythonanywhere.com</a>. Has been a great week 👍

**Comment by jywarren** [comment]
Hi, everyone! So glad to see you all and thanks to @Tlazypanda for opening this up!

I'm working on a bunch of different issues this week after taking 3 big ones from MapKnitter last week. I'm struggling a bit with getting https://github.com/publiclab/plots2/pull/7820 - a bump to latest editor version -- to pass, and hoping to check out https://github.com/publiclab/PublicLab.Editor/pull/437 with fixes to image upload UI in the editor. 

I offered some input to @ebarry on taking the next steps on https://github.com/publiclab/plots2/issues/7831, and want to finish rebasing https://github.com/publiclab/leaflet-environmental-layers/pull/422  as well.

I so appreciate the sentiment in this week's theme! ❤️ For my part I'm trying to help where i can, and to pay attention to what's happening in the world that especially affects folks who are already facing tough problems. Hoping everyone is well and sending my wishes for health.

**Comment by Uzay-G** [comment]
Hey everyone! Online school is quite intense right now, with lots of work from our teachers on top of the video meetings. I am building a website right now with a few biologists to provide clear and intuitive  information about the virus and how to stop its spread.
I hope doing this will be able to help in the fight against the virus by teaching people how to act more responsibly :smile:

**Comment by nstjean** [comment]
I'm sorry I haven't been around! My main computer wasn't booting and it was "school break" last weekend for my kids, no schoolwork to keep them occupied. It's such an adjustment to have everyone in the house together all day long!

I would like to clean up the things I was finishing up on on the maps across the different repos. And just in general catch up with what has been happening here!

**Comment by SidharthBansal** [comment]
Hello everyone, I hope you all are curious about the Google Summer of Code results today! :tada: :tada:
For those who has not passed this time, I will say, you all have potential. This year, we had very few slots so we were not able to select all the hardworking candidates. We really :heart: your contributions at Public Lab and will always be there to help you to uplift your career. You all have learned a lot in the GSoC application period. Everyone did the proposal. The proposal is the design phase in any SDLC. So, well done. 

Those who will be selected today. Congratulations!!!! We are now tied for at least 4 months, maybe more :) Happy coding.

**Comment by SidharthBansal** [comment]
Moved to https://github.com/publiclab/plots2/issues/7866

**Comment by TroydonAnabolic** [comment]
Have been away for some time too, just moved houses and had heaps of things to sort, finally back into working on the RPG game tutorial i was following.

**Comment by cesswairimu** [comment]
Great @TroydonAnabolic hope you are settling in fine...we change weekly check-in issues every week you can find the links on #5627 ...current check-in is at #7866
