### ISSUE TITLE
Weekly check-in template

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#7845]
Lets create a template for the the check-in links we been copying text for more than an year now...lets have a template for check-in...we could use the text from  https://github.com/publiclab/community-toolbox/issues/308  that includes the priority issues ...we are however open to improvement of the text

**Comment by daemon1024** [comment]
The template goes here, https://github.com/publiclab/plots2/tree/master/.github/ISSUE_TEMPLATE , right?

**Comment by daemon1024** [comment]
@cesswairimu Can you please review it !

Thanks :)

**Comment by cesswairimu** [comment]
Great I will come within the course of the day :)
