### ISSUE TITLE
Link needs updating or removal

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#7846]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I saved a draft note, which went well. Then i noticed at the top of the draft, there was a link on the words "adding a descriptive tag below" which did not do anything when clicked. Here is what it displays: 

<img width="194" alt="Screen Shot 2020-04-28 at 10 52 51 AM" src="https://user-images.githubusercontent.com/161439/80502354-858fe880-893e-11ea-80b4-4a62f09240d2.png">

![descriptive-tags-broken-link](https://user-images.githubusercontent.com/161439/80502177-4c577880-893e-11ea-85d7-4098626d836e.png)

> What did you expect to see that you didn't?

I expected this link to do somewhere, or else for this text to not be hyperlinked. 

### Please show us where to look

https://publiclab.org/notes/show/23484/rbl4sGfcW8_ef_SWkHWhHg

### What's your PublicLab.org username?

Liz

**Comment by ebarry** [comment]
Hi all, i suspect this might not be too tricky if someone could share code links?

**Comment by Tlazypanda** [comment]
Hey @ebarry  I just created a pull request for this ...didn't remove the link part but replaced it with opening the tags adding button because it seemed a better option :sweat_smile: Can you please check out the GIF in my pull request and let me know if this works. Thanks a lot! :smile:

**Comment by cesswairimu** [comment]
@ebarry @Tlazypanda I feel like the link should redirect to https://publiclab.org/tags what do you think?

**Comment by Tlazypanda** [comment]
Ohh, since the text was 'adding descriptive tags below' I directed them to where they will be able to add tags from for that note :sweat_smile:  

@cesswairimu Should I modify the pull request for the same then? Let me know :smile:
