### ISSUE TITLE
table content is not aligned

### ISSUE THREAD

**Issue by keshavsethi** [publiclab/plots2#7855]
In https://publiclab.org/contributors/air-quality People who are following column is not aligned with other columns as shown
![Screenshot from 2020-04-29 02-44-39](https://user-images.githubusercontent.com/36025262/80772189-83fb3600-8b73-11ea-931f-9ea6e16d5086.png)
Thanks!!

**Comment by jywarren** [comment]
I believe this can be merged as a duplicate! Thanks!
