### ISSUE TITLE
Track successful vs. unsuccessful replications & builds

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#786]
in the new [Activity grids](https://publiclab.org/notes/liz/08-30-2016/check-out-these-activity-grids) -- so that the number shown is of how many succeeded vs. not.

Maybe we want to show `4/12` for four of twelve attempts succeeded?

**Comment by jywarren** [comment]
And Mathew made a good suggestion -- ways to encourage people to post "partway done" work, to ask for help and post their work so far.

**Comment by jywarren** [comment]
how to mark with success/failure: `replication:success` vs. `replication:unsuccessful` tag, who gets to mark it as such, how success condition is described/tested/debated

**Comment by jywarren** [comment]
Gretchen's idea -- mini-quiz, maybe based on original activity author's framing.

**Comment by jywarren** [comment]
Positive discursive interactions to reach consensus on this.

**Comment by jywarren** [comment]
Could we include a few "quick reply" buttons in the new "i did this" comment window to offer alternatives like "I had some trouble" or "I have a suggestion" ? These could be added to the start of the textarea content! @okonek what do you think of this after having solved https://github.com/publiclab/plots2/pull/4101 ?

**Comment by jywarren** [comment]
We could make a GCI task for it if you like?

**Comment by jywarren** [comment]
![screen shot 2018-12-05 at 5 37 30 pm](https://user-images.githubusercontent.com/24359/49548679-82610c00-f8b4-11e8-8e68-8328d007d694.png)

Something like this -- using code like:

```html
<span style="font-family:arial;">
  <a class="btn btn-default btn-xs">'I have a suggestion'</a> 
  <a class="btn btn-default btn-xs">'I had some trouble'</a> 
  <a class="btn btn-default btn-xs">'This worked perfectly!'</a>
</span>
```

**Comment by jywarren** [comment]
Maybe it adds the text to the end if it is currently only "I did this!" -- but to the beginning if it's anything else? Or do the buttons disappear once you start typing? I'm just trying to think how to make it not just insert the text strangely before/after something you've actually already written...

**Comment by dinaelhanan** [comment]
I think that the comment suggestions are a really good idea. This should be a gci-candidate! It looks good for a first-timers since they really would just have to add the mentioned code above and add a link to the suggestion comment template (I think there's a link to that, I've seen issues with that template...) Hope that helps!

**Comment by jywarren** [comment]
Great idea! Would you like to post a first-timers-only issue for this? Usually when they're properly formatted and labelled, someone shows up real fast to solve it, and it's really fun. Little bit like fishing -- but for friends and collaborators! 🎣

**Comment by dinaelhanan** [comment]
@jywarren Ok, I'll finish up the two tag unit tests at saturday latest and have the issue up by sunday. Thanks!

**Comment by jywarren** [comment]
awesome!

**Comment by jywarren** [comment]
Moving into a new issue -- comment suggestions -- with this idea, closing original (though I asked in staff slack if we want to revisit how "replications" are represented). Thanks!

**Comment by jywarren** [comment]
Noting new issue "Suggested comments" at https://github.com/publiclab/plots2/issues/5808
