### ISSUE TITLE
Weekly community Check-In #57 - GSoC & Outreachy Commences

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#7866]
We all at Public Lab :balloon:  - learn, grow, work, brainstorm ideas, contribute together so why not share our ideology to help and support in whatever small way we can to whosoever needs our help. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal :dart: . You are also welcome to share fun-fact :smile: , new ideas :bulb: , your learning goals :ballot_box_with_check: 

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. :100: 

# GSoC and Outreachy Announcements:

We are happy to announce that the following candidates are selected for GSoC and Outreachy 2020. :tada: :tada:
1. Sneha
2. Keshav Sethi
3. Keshav Garg
4. Nitin
5. Alax
6. Shulammite
7. Shreyaa

This year we had lesser slots as we participated in DIAL. But still, this summer will be gigantic as the previous summers :100: 
Few tips: 
1. Please try to break down your projects into small modular PRs with tests(units, functional, system integration etc.)
2. Please don't forget to document your code. Documentation is essential for long term readability and a better understanding of future developers working on the same piece of code.
3. Please try to involve more people in your project. The more the merrier. Create FTOs as we did in past. Be collaborative. :1st_place_medal: 
4. Please arrange your work in the form of milestones so that it is easily evaluated by the mentors. All the issues and prs throughout all the three phases will come under this milestone. :checkered_flag: 
5.  Please open up a planning issue listing the work break down the structure of the GSoC & Outreachy project using checkboxes. :seedling: 
6. Stay active and communicative. Need help then feel free to ping the mentors. We are there to help. Also, ping other GSoC and Outreachy students working in the same stack. PL is more about teamwork :technologist: 
6. Kindly participate in weekly checkins with progress reports
7. Kindly write blog posts each month/evaluation.

## This week's focus Issues

These are issues that are of high priority and requests from our large community that use the software. 
1. https://github.com/publiclab/plots2/issues/7832
----
 A big thanks to @dongskyler for solving last week's focus issue #7831 :tada: :tada: 

## Next Check-in
If you would like to open the next weekly check-in please comment below.

Thanks everyone for making PL awesome and have a great week ahead :balloon:

**Comment by SidharthBansal** [comment]
Hello everyone, I hope you all are curious about the Google Summer of Code results today! tada tada
For those who has not passed this time, I will say, you all have potential. This year, we had very few slots so we were not able to select all the hardworking candidates. We really heart your contributions at Public Lab and will always be there to help you to uplift your career. You all have learned a lot in the GSoC application period. Everyone did the proposal. The proposal is the design phase in any SDLC. So, well done.

Those who will be selected today. Congratulations!!!! We are now tied for at least 4 months, maybe more :) Happy coding:)

**Comment by SidharthBansal** [comment]
@govindgoel @Rishabh570 @sashadev-sky @vaibhavmatta @shubhscoder @aSquare14 @sidntrivedi012 @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77 @milaaraujo @kevinzluo @shipcy @developer22-university @keshavsethi @emilyashley @smarty1palak @daemon1024 @jywarren

**Comment by SidharthBansal** [comment]
@sssash18, @Tlazypanda, @chinmay021, @Srija616, @AnnaMinakova, @greenbrown, @taysa91, @TaishiRoy, @yagmurbaydogan, @Shulammite-Aso, @Jigyasa-Kumari, @moliver4, @TroydonAnabolic, @justinelai, @Janetsomehow, @keshav234156, @Snouzy, @dependabot-preview[bot], @stevenalila, @Digiox, @NitinBhasneria, @yandu31, @milosv1, @jamescapps, @Nevenem, @chirag-wadhwa, @yogeshjdeshmukh, @omizrahi99, @cesswairimu, @theOpetunde, @sailahonkanen, @robin-natale, @avidler, @nstjean, @keshavsethi, @ccyccyccy, @JordanTFite, @krsudhanshu, @3ng7n33r, @Odisseuss, @imajit, @VladimirMikulic, @rehasantiago, @urvashigupta7, @HashTalmiz,

**Comment by SidharthBansal** [comment]
@vinitshahdeo, @dragonwarp, @z-arnott, @JanviMahajan14, @mantinone, @DouglasLutz, @seabl, @jywarren, @crisner, @Uzay-G

**Comment by Dhiraj240** [comment]
All the best everybody, I will not be selected in my last attempt again(gut feeling :P). 

All the best all.

**Comment by SidharthBansal** [comment]
@Dhiraj240 you are really hardworking. We really appreciated your work. Kindly look for more and better opportunities. 

Congrats all! Google announced it https://summerofcode.withgoogle.com/organizations/6496801642774528/?sp-page=2

**Comment by alaxalves** [comment]
Thanks a lot for picking me guys. :partying_face: :partying_face:

**Comment by gr455** [comment]
Congratulations everyone! :tada:

**Comment by sssash18** [comment]
Congrats everyone and have a great experience! 👍

**Comment by CoderJolly** [comment]
Kudos Everyone 🎉🎊

**Comment by blurry-x-face** [comment]
Congratulations everyone!!! :tada: :tada:

**Comment by vinitshahdeo** [comment]
All the best everyone for making it to **GSoC** 2020! 🎉

**Wishing you a great journey ahead!** ❤️

**Comment by dongskyler** [comment]
Thank you very much. I think I have received more credits than I deserve. Thanks to @cesswairimu , @jywarren, and @Tlazypanda on #7831.

**Comment by jywarren** [comment]
Hi, Outreachy and GSoC folks!!! I've build on Sidharth's suggestions above and posted a longer Welcome Packet issue for you all which we've been working on for a little while! https://github.com/publiclab/plots2/issues/7873

Please check it out!!!

**Comment by jywarren** [comment]
Hi all, i wanted to recognize @nicoleiocana for being a spectacular welcomer in our community. This was a helpful, warm, and supportive message for a newcomer:

https://github.com/publiclab/plots2/issues/7703#issuecomment-605349109

Sending thanks and appreciation to @nicoleiocana !!! 🙌 ❤️

**Comment by jywarren** [comment]
@nicoleiocana perhaps you might like to open the next check-in? https://github.com/publiclab/plots2/issues/5627

**Comment by nicoleiocana** [comment]
@jywarren  Yes, I would be proud to open up next week's check in. I just need some direction as to how to format/ structure the thread....and was hoping that you could steer me where I need to go/the individuals who could offer that support.

**Comment by cesswairimu** [comment]
Great, thanks @nicoleiocana :tada: 
You can choose a topic to be the theme of the week and copy the first paragraph of the description on the current issue and have it as part of your description. You can checkout previous themes on #5627  for pointers. As to when to open the check-in either today or tomorrow(Monday morning) Please feel free to ping me if you need any help or clarity .
Thanks again

**Comment by nicoleiocana** [comment]
@cesswairimu Here is this week's check in #7899 . Thanks for the opportunity to share some insight to everybody here at Public Lab.

**Comment by cesswairimu** [comment]
Thanks @nicoleiocana ...Moved to #7899 . Thanks everyone
