### ISSUE TITLE
comments on Q&A slightly wonky

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#787]
### What happened just before the problem occurred

an accepted answer in the new Q&A system shows a count of 1 comments, but there is no comment. 

![screen shot 2016-09-03 at 4 58 55 pm](https://cloud.githubusercontent.com/assets/161439/18227605/f0cef3f0-71f7-11e6-833b-8a4bd1dfb8f0.png)

### Relevant URLs

https://publiclab.org/questions/nshapiro/09-02-2016/question-what-is-the-open-source-community-s-take-the-mit-license#a33

### PublicLab.org username

 liz 

### Browser, version, and operating system

**Comment by ananyo2012** [comment]
Weird this doesn't happen on other questions. I am on it. Thanks for reporting @ebarry

**Comment by ananyo2012** [comment]
I also see 1 comment shown in the question comments though there is none.

**Comment by ananyo2012** [comment]
Well I tried posting a comment for that question both in a answer and a separate question comment. The comment showed up just after I posted, that means it got saved. But after I refreshed the page it was gone. So there is comment present in the database for that question but it isn't showing up.

P.S. This only happens for this particular questions. Others are workinf fine. See this one where I posted the same comment https://publiclab.org/questions/bsugar/08-22-2016/question-is-there-a-simple-and-reliable-way-to-test-the-rigidity-of-the-spectrometer#answer-0-comment-15306

**Comment by jywarren** [comment]
Ananyo, could you try to duplicate this by making a local copy of it with
the same tags/title/body on your local copy? If you get stuck, I can also
log in over ssh and use `rails console` to look more closely at this
question's db record.

**Comment by ebarry** [comment]
ok more information -- i got an email notification that someone DID leave a comment: 

Here's a screenshot:
![screen shot 2016-09-03 at 7 08 51 pm](https://cloud.githubusercontent.com/assets/161439/18228081/fdca8242-7209-11e6-9d6d-bb22abca54ec.png)

**Comment by ananyo2012** [comment]
Ok I figured it out. It is due to these lines https://github.com/publiclab/plots2/blob/master/app/views/questions/_answer.html.erb#L78-L86 that extracts the anchor text and  checks for matches. The link @ebarry posted contains a anchor text for answer and that's why comments weren't being displayed as they were hidden. I will submit a fix for this shortly.

**Comment by ebarry** [comment]
Awesome!!!

**Comment by ananyo2012** [comment]
Fixed in #795
