### ISSUE TITLE
Welcome, Outreachy/GSoC 2020 participants! Let's plan & coordinate! 🎉🙋‍♀️🙋🙋‍♂️

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#7873]
Welcome!!!! 🎉 💯 🙌 ✨✨✨✨ 

Congratulations and thanks to everyone who’s worked so hard in the past few months towards our Outreachy and Google Summer of Code initiatives. Now that we have accepted 7 projects, it’s time to start planning how we’ll work together. We've compiled this issue, and [this Google Doc of the same content](https://docs.google.com/document/d/1NwWrIhumVxVa0i__ZRMY9upLh6LmzNrG-0PtnZo4LZE/edit) as a Welcome Pack for you to get oriented!

At Public Lab, we work cooperatively, meaning that we invite others into our work, we lay the groundwork early for shared successes and mutual support, and we [work in specific ways](http://publiclab.org/software-outreach) that build a broader community. Read on to learn more!

### Chatroom + weekly check-ins

Each week we have a “check in” where we… [check in](https://github.com/publiclab/plots2/issues/5627)! Say hello, share a link to a recent blog post, ask for help, and watch for interesting themes. And sign up to open one of the check-ins yourself! 

And we have a chatroom at https://gitter.im/publiclab/publiclab where you can chime in with questions, offer help, or troubleshoot, or just hang out!

### Kick-off and Celebration video calls

Meeting in real-time is great:

* We’ll host a video call sometime in May, before coding period begins June 1
* Look ahead to a September 14, 2020 [OpenHour](http://publiclab.org/openhour) for another chance to meet online!

Team project planning and communication

Here are some resources on how we encourage you to collaborate and structure your work!

* https://github.com/publiclab/plots2/issues/5667 - a “how we work” document from 2019 
* https://publiclab.org/notes/warren/01-18-2018/software-outreach-modularity-is-great-for-collaboration
* https://github.com/publiclab/plots2/issues/5794 - resources for writing modularly

### Milestones

We have a strong culture of transparency from the planning process through implementation, where sharing your progress step by step helps others to understand where you are in your work. We use a combination of GitHub Milestones and “planning issues” (see description above in the “modularity” blog post) to communicate what you plan to do and how much you’ve gotten do so far!

* Example planning issue: https://github.com/publiclab/plots2/issues/7432

### Style guide

We have a Style Guide draft to help you with design, UI, UX decisions for any Public Lab site. Whenever you are thinking through how something should look, please give this a read and ask questions!

https://publiclab.org/notes/warren/05-07-2019/introducing-a-draft-style-guide-for-public-lab

### Roadmap

The Roadmap is a document to help guide the long-term sustainability, goals, and prioritization of projects. When planning out your project, think of how to balance the complexity of new features with long-term maintainability! Read more here: 

https://publiclab.org/notes/warren/05-22-2019/draft-of-a-public-lab-software-roadmap-comments-welcome

### Supportive tasks

https://github.com/publiclab/plots2/labels/support - These tasks are part of how we develop community through mutual support, and it’s good to set aside some time each week for this kind of thing. They will also help you attract a team of contributors to help build the community and engage newcomers in solving problems with you!

### People to reach out to

Different projects at Public Lab have different groups of leaders; here is a list of folks who’ve recently taken leadership at various projects (we’ll be building this list out in coordination with the Feature Maintainers process: https://github.com/publiclab/plots2/issues/6501!):

* Plots2 - @jywarren @cesswairimu @sidharthbansal @gauravano
* Mapknitter - @jywarren
* Editor - @cesswairimu @jywarren
* Leaflet.DistortableImage - Sasha Boginsky (@sashadev-sky)

### Project teams

This year we’ll have a big team working on the Editor, which will require some significant cooperation and planning. We’ve compiled a bunch of ideas for how the Editor team could split up the project and focus on different features, as well as how we might expand the project so that the larger group will have enough to work on (don’t worry, there’s PLENTY!)

https://docs.google.com/document/d/1LX1VEi_TEplnduXETqwr8mPPt-hshlg03dLeaa74hMI/edit

Please leave comments and we can discuss in this issue!

### More resources

https://github.com/publiclab/plots2/issues/5684 - last year's “convening teams” issue from 2019 SoC

****
And remember -- as I'm sure you know, our community aspires to be a respectful place. Please read and abide by our [Code of Conduct](https://publiclab.org/conduct) as always.

Once again, welcome and we're so glad to have your participation this year! 🎉 💯 😄 💥

**Comment by jywarren** [comment]
cc mentors and coordinators! @emilyashley @cesswairimu @SidharthBansal @sidntrivedi012 @subhahu123 @starkblaze01 @debck @ananyaarun @govindgoel @pydevsg @blurry-x-face 

And participants this year! @Tlazypanda @Shulammite-Aso @shreyaa-s @keshav234156 @keshavsethi @alaxalves @NitinBhasneria 🎉

**Comment by keshav234156** [comment]
@jywarren @cesswairimu I have opened a Planning issue for Editor project at https://github.com/publiclab/PublicLab.Editor/issues/490

**Comment by cesswairimu** [comment]
Fantastic thanks @keshav234156  :tada: :tada:

**Comment by Tlazypanda** [comment]
Hey @cesswairimu @jywarren @SidharthBansal I just opened the planning issue at https://github.com/publiclab/plots2/issues/7883 .Please have a look and provide some feedback on the same :rocket: .Thanks!!

**Comment by emilyashley** [comment]
Hey folks! Welcome! There's a lot happening so fast already and the momentum is AWESOME. 🤩

Hi @Tlazypanda @Shulammite-Aso @shreyaa-s @keshav234156 @keshavsethi @alaxalves @NitinBhasneria !!

Just wanted to call your attention here and make this space for us to meet and schedule a Welcome Call. 

First off, I'm Emily I live in New Orleans, USA and my office hours are typically 10am-2pm Central Time and 9-5pm Tuesday. Tuesdays is also a day that other coordinators  (looking at you, @jywarren) are consistently available.

While we might already be accustomed to living on github, I'd love for each of you to **share your timezone** and also your **preferred time** or days of week (i.e. Office Hours) to have synchronous communication such as a Welcome Call!

**Comment by emilyashley** [comment]
Also YAY we have an Editor Team! I'm interested in having a Kick Off call with y'all and setting up shared project management tools (like, Milestones) that work well for collaboration between a team of 4 :) More on that in the Editor Repo, later!!

**Comment by keshav234156** [comment]
@emily In India we have timezone GMT+5:30. I would like to prefer to have a Call on Tuesday when other coordinators are available as well. I would prefer 9 am - 12 pm Central time. For Editor, we can have it on any day of the week between 9 am to 12 pm Central Time.

**Comment by shreyaa-s** [comment]
For me, anytime between 9 am - 2 pm (Central Time) works fine, any day of the week. Though, like Keshav, I would prefer to have a call on Tuesday as well when all coordinators are available. Thanks!

**Comment by keshavsethi** [comment]
Hey @emilyashley, 10 am to 2 pm works for me and Tuesday is also fine :smile:

**Comment by keshavsethi** [comment]
I have opened a planning issue for the Spam management Dashboard at #7885. Please provide your feedback at the same :sweat_smile: @SidharthBansal @jywarren @ananyaarun @pydevsg @emilyashley @cesswairimu 
Thanks!!

**Comment by NitinBhasneria** [comment]
Hey @emilyashley, 10am - 2am will be best time for me.

**Comment by Shulammite-Aso** [comment]
Hi @emilyashley Tuesday is cool, but 12pm - 2pm central will be a lot convenient for me. 

For any other week day, 9am - 2pm central time is all good. 

Meanwhile, I live in Nigeria, with timezone GTM+1.

**Comment by Tlazypanda** [comment]
Hey @emilyashley !! 10am to 2pm central time works for me too and Tuesday sounds good. Looking forward to this :tada:

**Comment by cesswairimu** [comment]
@emilyashley  https://doodle.com/ might be a great tool to do a poll on the time

**Comment by alaxalves** [comment]
Hello @emilyashley ! I'm in Brazil at GMT -3 timezone. Tuesdays at any time are okay for me, we'd only have to get it scheduled a few days earlier.

**Comment by SidharthBansal** [comment]
Congrats all!

**Comment by jywarren** [comment]
Hi again folks! so glad to see you all in here. Just noting 10-2pm central is fine for me too!

**Comment by emilyashley** [comment]
Awesome, thanks y'all.  Let's plan on a Welcome Call **11am Central UTC-5 Tuesday May 19th**! I think I have everyone's email and can get a google calendar invite out. 

@Tlazypanda @Shulammite-Aso @shreyaa-s @keshav234156 @keshavsethi @alaxalves @NitinBhasneria 

@ebarry @jywarren 

I'm also happy to meet with any of y'all 1:1 during my office hours between now and then (or after) if you've got burning questions or ideas! Honestly excited to get some face-to-face time and to get to know you.

**Comment by emilyashley** [comment]
@Tlazypanda @Shulammite-Aso @shreyaa-s @keshav234156 @keshavsethi @alaxalves @NitinBhasneria @jywarren 

Invite sent! I may update the invite with the appropriate zoom link and agenda tomorrow before the call. 

I used the emails I had on hand from your application, if I got it incorrect or you did not receive a google calendar invitation please let me know :) 

Happy Monday!
