### ISSUE TITLE
Minify JS using Uglifier for performance

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#7887]
Currently the js files are not minified which slows down the first paint of the website. Uglifier gem which is already present in the gem file can be used for minfying js and hence decreasing the first paint time of the website.

**Additional context (optional)**
### Screenshots-
Currently the performance of PublicLab is 2/100 score on Google PageSpeedInsights.
![image](https://user-images.githubusercontent.com/33183263/81388329-c99c9d80-9135-11ea-8864-e061d5c36837.png)

Suggestion points to minifying js-
![image](https://user-images.githubusercontent.com/33183263/81388196-91955a80-9135-11ea-958b-186802240d13.png)

**Comment by ebarry** [comment]
Thank you for working on this! The screenshot shocked me. I look forward to seeing our rating of 2/100 improve after your excellent work! 🌷

**Comment by Tlazypanda** [comment]
@ebarry !! Yeah hopefully after this summer we can see the page load time improve :100: Thanks so much for your kind words :heart:

**Comment by Tlazypanda** [comment]
@jywarren Just chiming in to say  I was just checking this out again the performance improvement after this but it's not working possibly since its fetching from the already existing public/assets folder so maybe we will have delete it and rebuild :sweat_smile: Thanks :v:

**Comment by Tlazypanda** [comment]
@jywarren Just chiming in to say I was just checking this out again the performance improvement after this but it's not working possibly since its fetching from the already existing public/assets folder so maybe we will have delete it and rebuild sweat_smile Thanks v
