### ISSUE TITLE
Check for js files duplication in assets.rb and application.js

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#7889]
Currently many files which are already present in the application.js manifest file are present in assets.rb as well. Also if files mentioned in assets.rb are applicable for use throughout the application it is better to include them in application.js instead of augmenting the asset array in assets.rb.

**Please describe the desired behavior.**
The duplicates can be removed and also further js files used throughout the application can be moved from assets.rb to application.js manifest file. This will improve the performance greatly since the js file will be minified,gzipped and cached allowing loading only when modified.

**Additional context (optional)**
Please refer Best Practices in Rails Precompilation subsection [here](https://launchschool.com/blog/rails-asset-pipeline-best-practices).

**Comment by Tlazypanda** [comment]
@jywarren @cesswairimu While going through this issue noticed a lot of discrepancies in the structure of files. Some assets which are already present in app/assets folder are also present in public/lib folder and are served from different places in application.rb and assets.rb. For example- ics

So what is the rule of thumb to follow here? Should we remove the packages from /lib or /assets. Also some files I believe may not be called as much across the app and should only be present in assets.rb. But would need some help to identify this :sweat_smile: can you help me out with this? 

Thanks :v:

**Comment by cesswairimu** [comment]
checking
