### ISSUE TITLE
Comment Error Message appears on another page

### ISSUE THREAD

**Issue by jscastanos** [publiclab/plots2#7896]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
The error message doesn't behave as it should be.

Steps to produce:
1. Select any topic and submit an empty comment. (error message should appear that it could not be saved)
2. Navigate to other pages.
3. The error message will appear on the page you selected.

![output1](https://user-images.githubusercontent.com/37854603/81487806-ca4b4600-9293-11ea-8abf-52f28e0b582c.gif)

NOTE: the bug mention above will not occur if you are going to refresh the page manually. (but it shouldn't be that way)

![output2](https://user-images.githubusercontent.com/37854603/81487925-37aba680-9295-11ea-8130-1eb3ec0fb185.gif)

> What did you expect to see that you didn't?
The error message should appear on the page it should be and without any manual action.

### Please show us where to look

https://publiclab.org/notes/silentsairam/06-10-2019/an-insight-on-indoor-air-pollutants-factors-sources-pollutants or any related links

### What's your PublicLab.org username?

> This can help us diagnose the issue: 
jec_castanos

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!
Chrome - Version 81.0
Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by PrakharSharma41** [comment]
Hi @ jscastanos  , I would like to work on this issue.

**Comment by jscastanos** [comment]
@PrakharSharma41 Sure, go ahead. Just don't forget to mention @publiclab/reviewers in your PR

**Comment by cesswairimu** [comment]
Thanks for reporting this @jscastanos

**Comment by jscastanos** [comment]
@cesswairimu No problem. I'll try to find some more in my spare time.

**Comment by urvashigupta7** [comment]
Hi, I would like to work on this issue 😊

**Comment by jywarren** [comment]
Hi, we'd love help with this -- but it may be a bit tangled and difficult to figure out. We do have comment error handling for asynchronous comment submissions, but it may require some digging into code at /app/assets/javascript/ to find where that code is and a look at the Rails controller at /app/controllers/comments_controller.rb (i think?) to see why it's not sending back an error that the client-side JavaScript code can receive and display before refreshing the page. Does that make sense?

Thanks!!

**Comment by urvashigupta7** [comment]
Hi, what I can see is when we create a new comment successfully it responds with this javascript [file](https://github.com/publiclab/plots2/blob/main/app/views/comments/create.js.erb) and then notyNotification displays notification that comment has been successfully added. However, when we send empty body it falls inside rescue [portion](https://github.com/publiclab/plots2/blob/main/app/controllers/comment_controller.rb#L53) which generates a flash and since it is ajax request and the flash is not displayed it gets stored in flash hash and it displays on another page. So, what we can do is we can add response status 404 and remove the flash so that  when this ajax request fails [this](https://github.com/publiclab/plots2/blob/main/app/assets/javascripts/comment.js#L25) set of code will add notyNotification

**Comment by gauravano** [comment]
Nice catch @urvashigupta7. I can see @PrakharSharma41 also claimed this issue. Let's check with them if they have started working on this one? Maybe you both can collaborate to solve this issue. Thanks!!

**Comment by urvashigupta7** [comment]
Thanks @gauravano 😊.  @PrakharSharma41 Are you still working on this?

**Comment by urvashigupta7** [comment]
Hi @gauravano , @jywarren. Should I open a pull request as Prakhar hasn't replied yet?

**Comment by cesswairimu** [comment]
@urvashigupta7 go ahead. Thanks

**Comment by jywarren** [comment]
Yay, thanks all! Good to see you @gauravano !!
