### ISSUE TITLE
Weekly Community Check-In #58 - Acceptance

### ISSUE THREAD

**Issue by nicoleiocana** [publiclab/plots2#7899]
We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯. You are also welcome to share fun-fact 😄, new ideas 💡, your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. 💯

## Acceptance
There have been many great themes that involve self-awareness: don't give up #53, everybody struggles #41, asking for help #39, and motivate #21.  Acceptance of who you are occurs when you find closure of identifying the limits of your character. Be appreciative of the pace at which you learn, demonstrate kindness to yourself when you make mistakes, and don't beat yourself up comparing yourself to others. You are a distinguished individual - compare yourself to yourself. We all become who we are supposed to become at different rates by experiencing different life events. Be proud of who you are and how you have progressed to where you are right now. Be your biggest fan! You rock! 💪

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time 😄

Thanks everyone for making Public Lab awesome 🎈
Have a great week ahead all ❤️

**Comment by gr455** [comment]
Hi everyone! Hope everyone is doing well. I have been quite occupied with some collegework for the past few days(since the vacations start in 5 days :tada: ).I also participated in SharkyCTF this weekend which was super cool. This week, I will finish off my university work and try to help with SWB upgrades. I am also searching for an intership of sorts to do over the summer :smile:

**Comment by cesswairimu** [comment]
@jscastanos, @jywarren, @sarthak-choudhary, @dongskyler, @keshavsethi, @Shulammite-Aso, @ckchu8, @keshav234156, @DerekChristy, @Srija616, @priyanka-choubey, @Tlazypanda, @AyanChoudhary, @imajit, @NitinBhasneria, @nstjean, @marientje, @rutger-t, @Janet33, @TroydonAnabolic, @priyanshbalyan, @Medlineme4, @mandysGit, @msanden, @AidenOliver, @Janetsomehow, @AntroMarina, @llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-s, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @WaldenJosh, @B4Lee, @VisnuGanth, @jessibreen, @alaxalves, @kamal-kaur04, @sssash18, @chinmay021, @greenbrown, @taysa91, @TaishiRoy, @yagmurbaydogan, @Jigyasa-Kumari, @moliver4

**Comment by cesswairimu** [comment]
@greenbrown, @taysa91, @TaishiRoy, @yagmurbaydogan, @Jigyasa-Kumari, @moliver4, @govindgoel @Rishabh570 @sashadev-sky @vaibhavmatta @shubhscoder @aSquare14 @sidntrivedi012 @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77 @milaaraujo @kevinzluo @shipcy @developer22-university @keshavsethi @emilyashley @smarty1palak @daemon1024

**Comment by Uzay-G** [comment]
> Hi everyone! Hope everyone is doing well. I have been quite occupied with some collegework for the past few days(since the vacations start in 5 days tada ).I also participated in SharkyCTF this weekend which was super cool. This week, I will finish off my university work and try to help with SWB upgrades. I am also searching for an intership of sorts to do over the summer smile

Same @gr455! We also participated with my team. It was epic :smile:. I really liked the blockchain ones!

**Comment by gr455** [comment]
> > Hi everyone! Hope everyone is doing well. I have been quite occupied with some collegework for the past few days(since the vacations start in 5 days tada ).I also participated in SharkyCTF this weekend which was super cool. This week, I will finish off my university work and try to help with SWB upgrades. I am also searching for an intership of sorts to do over the summer smile
> 
> Same @gr455! We also participated with my team. It was epic :smile:. I really liked the blockchain ones!

My other teammates did the blockchain, but the web ones were also really good 👌

**Comment by Uzay-G** [comment]
Yeah they were nice too :smile:. I liked web fugu and aqua world

**Comment by AyanChoudhary** [comment]
Hello everyone, hope you all are fine! It is a little tough being stuck in a lockdown here, but still I along with some of my friends am reading on how to develop an os.

**Comment by shreyaa-s** [comment]
Hey everyone! Hope you're doing good. I've been busy going through the woofmark library and completing a few college projects. Good luck!

**Comment by ebarry** [comment]
Hi everyone, I'm excited to see all the people and teams pick up speed, and am enjoying reading the planning issues for the Google Summer of Code and Outreachy projects. I'm also following progress on some stray bugs that i've filed lately.

**Comment by Tlazypanda** [comment]
Hey everyone! I still have my exams going on and am just waiting for them to just get over :crying_cat_face: Plan to revisit my proposal and make some changes after that :v: Also gonna start working on my blog :sweat_smile:

**Comment by alaxalves** [comment]
Hello guys, did some GSOC issue planning I intend on keep with on the upcoming week. @gr455 kindly offered to keep helping me on the SWB upgrades, so I'll make use of it :laughing:

**Comment by WaldenJosh** [comment]
Hope everyone is doing great! Just got done with my Web Programming II final yesterday. Looking forward to helping out more! Where can I help?

**Comment by Shulammite-Aso** [comment]
Hi all! So In the past week, I felt a bit unproductive, but I did basically set up my outreachy blog website, cloned Woofmark and have been looking into what each part of the codebase really does. 
Looking to follow up progress on the Editor project planning this week.

**Comment by SidharthBansal** [comment]
Hello all, I will be taking a webinar tomorrow at 6 pm IST regarding GSoC. So, that I can help juniors for GSoC 2021. I will be discussing the common mistakes due to which people were not accepted to GSoC 2020. I will give insights from both mentors and student. So, kindly share with your friends and juniors. Also with your seniors if they are still in college/university :)
I have created a new channel CODING OBSESSIONS on youtube  https://www.youtube.com/channel/UCOBUYbxTnrD7u0myc0wcjSg/featured
I did a lot of things during my college days. Want to share these things with all the juniors so that they are benefitted from it :)
You all are invited to suggest me the topics to cover :)

**Comment by SidharthBansal** [comment]
> Where can I help?

@WaldenJosh please claim any issue on no one else is not working in any repos having stack of your choice

**Comment by SidharthBansal** [comment]
@Tlazypanda same here. I am having viva nowadays. I hope lockdown doesn't delay or ruin our exams :)

**Comment by jywarren** [comment]
Hi everyone! so nice to see you all! I'm trying to go through and leave helpful tips on teamwork and project management for the GSoC and Outreachy teams here especially: https://github.com/publiclab/PublicLab.Editor/issues/490

I love @nicoleiocana's theme and will strive to `demonstrate kindness to yourself when you make mistakes` ! I'm currently struggling to install node v10, and so far haven't had a lot of success but maybe this thought will help me out :-)))

**Comment by jywarren** [comment]
And noting that 🎉 🎉 I just published https://www.npmjs.com/package/leaflet-environmental-layers v2.4.0 and https://www.npmjs.com/package/leaflet.blurred-location-display v1.3.0  thanks to everyone who's worked on those!

They are now publishing to the live site at https://PublicLab.org !

**Comment by alaxalves** [comment]
> Hi everyone! so nice to see you all! I'm trying to go through and leave helpful tips on teamwork and project management for the GSoC and Outreachy teams here especially: [publiclab/PublicLab.Editor#490](https://github.com/publiclab/PublicLab.Editor/issues/490)
> 
> I love @nicoleiocana's theme and will strive to `demonstrate kindness to yourself when you make mistakes` ! I'm currently struggling to install node v10, and so far haven't had a lot of success but maybe this thought will help me out :-)))

I always use NVM to manage my node versions @jywarren. It is as easy as managing Ruby with RVM.

**Comment by Tlazypanda** [comment]
@SidharthBansal Whoaa!!! That's a great initiative :rocket: Count me in :raised_back_of_hand: 

I can totally relate to the fact that students should have these resources free of cost instead of paying and not really getting any benefit out of it :100: 

And August is pretty much the perfect time to start since the new admits join the universities. We can do like bi-monthly sessions with Ask-me-Anything sessions to help students out. :sweat_smile: 

Some of the Topics from the Top of my head are :- 

-  What is Opensource and how to get started with it?
-  Why should you contribute to Opensource? 
-  About Programs like GSoC etc...
-  Busting myths of GSoC etc..(you have to be an expert developer, from iit/nit etc)
-  Interview preparations (leetcode/platform discussion)
-  Building projects that create an impact
-  System design intro
-  Creating the perfect resume
-  Uplift others (being a part of the dev/opensource community)

We can move into more detailed discussions/tutorials as well over git/github, solving specific questions for interviews or proposal writing. 

I have been thinking of the same topics for my blog, Would love to have you on-board as a coauthor :100:

**Comment by emilyashley** [comment]
That's awesome @SidharthBansal, let us know how it went :)

**Comment by cesswairimu** [comment]
Hi all, anyone who would like to open next week's check-in?

**Comment by Shulammite-Aso** [comment]
> Hi all, anyone who would like to open next week's check-in?

Hi @cesswairimu I just noticed this now. I'll be glad to help 🙏

I'm hoping it's late already?

**Comment by cesswairimu** [comment]
Great @Shulammite-Aso :tada: :t-rex:  No its not late...please open it within the day..Thanks

**Comment by cesswairimu** [comment]
@Shulammite-Aso kindly post the link here when its ready. Thanks

**Comment by Shulammite-Aso** [comment]
> @Shulammite-Aso kindly post the link here when its ready. Thanks

Oh, 

It will be ready in few minutes. I had actually  missed your earlier reply asking me to go ahead.😃

**Comment by Shulammite-Aso** [comment]
Hi @cesswairimu , here is the link https://github.com/publiclab/plots2/issues/7926

Thank you for asking me to do this, and sorry that it is coming a bit late.

**Comment by cesswairimu** [comment]
Forgot to close this one which was moved to #7926
Thanks everyone and thanks @Shulammite-Aso  for the new check-in :+1:

**Comment by SidharthBansal** [comment]
thanks @Tlazypanda

**Comment by SidharthBansal** [comment]
You can contact on gitter pm if you want to help more :)

**Comment by Tlazypanda** [comment]
Yeah sure! @SidharthBansal :smile:
