### ISSUE TITLE
"alert-error" which would make a red alert bar is broken.

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#7903]
# Please describe the problem (or idea)

I went to https://publiclab.org/wiki/authoring-help#Alert+Flags and used the documentation to add a red alert to the top of publiclab.org/getting-started. When i saved that page, the alert did not render. I had to try using another color bar, apparently green "alert-success" does work. 

> What did you expect to see that you didn't?

I expected to see a light red bar appear behind the alert text, but the red bar did not appear. 

### Please show us where to look

https://publiclab.org/getting-started

### What's your PublicLab.org username?
liz

Thank you!

**Comment by jywarren** [comment]
Super, i believe `alert-danger` will work instead of `alert-error` due to our upgrade to Bootstrap v4 (the CSS class changed then). Can you give that a try? 

![image](https://user-images.githubusercontent.com/24359/81750846-47391400-947c-11ea-9720-5deae611e6e6.png)

**Comment by ebarry** [comment]
Yup, that works! Check it out: https://publiclab.org/wiki/authoring-help#Alert+Flags and i added a link to bootstrap v4 docs on alert bars to our authoring help page. This can be closed as far as i'm concerned.
