### ISSUE TITLE
Lazy load images using lazyload-rails gem

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#7919]
**Please describe the desired behavior.**
Currently the pages are loaded only after completely loading all the images. We can lazyload images to improve first paint time. For this we can use lazyload-rails [gem](https://github.com/jassa/lazyload-rails).

**Additional context (optional)**
According to Pagespeed insight, lazyloading images is a good suggestion.
![image](https://user-images.githubusercontent.com/33183263/82149038-9368c780-9873-11ea-98eb-5a4adeda0f53.png)

**Comment by jywarren** [comment]
This is really awesome 🤯
