### ISSUE TITLE
Lead image doesn't appear for Questions

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#792]
### What happened just before the problem occurred

I posted a new question and don't see the lead image, although you can see there is one if you edit the note (me, or admins, can do this). Just wondering if it was intentionally omitted or if there's a bug.

### Relevant URLs

https://publiclab.org/questions/warren/09-06-2016/has-anyone-tried-a-dashboard-camera-for-timelapse-or-aerial-mapping

The template is here: https://github.com/publiclab/plots2/blob/master/app/views/questions/show.html.erb

It's based on this template, which does show an image (image code highlighted): 

https://github.com/publiclab/plots2/blob/master/app/views/notes/show.html.erb#L8-L14

Maybe it's as simple as porting that back in?

**Comment by ananyo2012** [comment]
@jywarren Yes actually I have intentionally omitted it and forgot to ask you about it. I thought keeping questions simple is better. In fact I was thinking of removing the lead image upload section in the question editor so that users won't upload a lead image. What do you say?

**Comment by jywarren** [comment]
Hmm, well, until we think through not prompting people for images in the
submission form, I think we should add it back in -- I see the idea of it
being simpler, but as it is, people may add images and then become
confused. Thanks!

**Comment by ananyo2012** [comment]
Ok Jeff I will add the lead image back.
ᐧ

**Comment by jywarren** [comment]
Hi, @ananyo2012 -- hope you're well! Are you still working on this one or is it open for newcomers? I may make it into a `first-timers-only` post.

**Comment by ananyo2012** [comment]
Hi Jeff! Sorry I couldn't be around these days. Just wait a bit. I will be
working on it today.
ᐧ

**Comment by ananyo2012** [comment]
@jywarren My tests are failing due to a problem starting the Solr server. I followed the steps given in the readme. But I installed the v8 of all the java packages i.e. openjdk-8-jre, openjdk-8-jdk, icedtea-8-plugin since I recently updated my Ubuntu system to Ubuntu 16.04 Xenial and the v7 packages for java weren't available. Is this due to the differnt version in my java packages?

**Comment by ananyo2012** [comment]
Ok I installed openjdk-7-jre and openjdk-7-jdk using a ppa. But still unable to install icedtea-8-plugin.

**Comment by ananyo2012** [comment]
Problem solved seeing #832
