### ISSUE TITLE
Weekly Community Check-In #59 - Always communicate.

### ISSUE THREAD

**Issue by Shulammite-Aso** [publiclab/plots2#7926]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. 💯

## Always communicate 

This week, we want to all remind our self of how important communication is. Communication is how we make a great community, and more especially a great team when we have to work together on a project. one thing that will help us to continue to see communicating as very important, is when we remember that nobody lives in our head and we don't live in any body's head, therefore we need to always share our thoughts  and be very clear about it as well as ask for and accept feedback.

To all the interns, GSoC/Outreachy who will be working hard on projects this summer, communication can mean various things from documenting the issues we create well so that other can easily understand them when they read them, to documenting all our works that introduces something new to the overall project, or updating documentation were one already exists. We also want to ask questions when we're stuck of feel lost, don't be ashamed to ask any kind of question as long as you have tried your best to find answers by yourself. Remember, nobody lives in your head, you need to always share your thought, and be as clear as possible.

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** 🎈
Have a great week and year ahead all ❤️

**Comment by Tlazypanda** [comment]
@Shulammite-Aso Great topic!! :heart: There are many times we fear asking questions thinking others would find them stupid but we just really should go for it :100:

**Comment by alaxalves** [comment]
Hey guys,

I have created my GSOC Planning Issue here ~> https://github.com/publiclab/spectral-workbench/issues/506.

Also, I am specially waiting on the review of https://github.com/publiclab/spectral-workbench/pull/499. I might need @icarito to get this merged, maybe I could work on a staging environment for Spectral, since we don't have any for now.

**Comment by jywarren** [comment]
Hi all! @alaxalves i alerted Sebastian so we hope to hear soon, thanks.

Thank you @Shulammite-Aso for a great check-in and theme! SO agreed! 🎉 

I've been working a lot to smooth out the integrations between libraries and "parent" applications, and got some help this week by communicating in a pull request -- VERY grateful to @VladimirMikulic for chiming in with a fix on this, which i had been mystified about! https://github.com/publiclab/plots2/pull/7913

With UI changes, library updates, and more, sometimes it can be hard to trace what others have done, and it's always a great idea to ask for help! 🙌

**Comment by SidharthBansal** [comment]
Here is a piece of good news from my side which I wanted to tell but I was waiting for it to be published. Kindly check out https://twitter.com/matplotlib/status/1263204229478408192
Telling you the twitter link so that I can make friends :)

**Comment by VladimirMikulic** [comment]
Congratulations Sidharth. Thats some good work!

**Comment by Tlazypanda** [comment]
@SidharthBansal Congratulations!! :100: :tada:

**Comment by gr455** [comment]
Great news @SidharthBansal !🎉 🎉

**Comment by cesswairimu** [comment]
Hi all :wave: and great theme @Shulammite-Aso :tada: 
Glad to see the interns getting organized and even start working on some issues :+1: hope the welcome call went well :)
Feel free to ping me for reviews and discussions and will get back to you as soon as I can

Happy coding :man_technologist: :woman_technologist:

**Comment by alaxalves** [comment]
> Hi all! @alaxalves i alerted Sebastian so we hope to hear soon, thanks.
> 
> Thank you @Shulammite-Aso for a great check-in and theme! SO agreed! 
> 
> I've been working a lot to smooth out the integrations between libraries and "parent" applications, and got some help this week by communicating in a pull request -- VERY grateful to @VladimirMikulic for chiming in with a fix on this, which i had been mystified about! #7913
> 
> With UI changes, library updates, and more, sometimes it can be hard to trace what others have done, and it's always a great idea to ask for help!

Thanks a lot Jeff, I'm already looking into that with Sebastian.

**Comment by cesswairimu** [comment]
Hey all, anyone interested in opening next week's check-in?

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/7950 Thanks everyone :heart:
