### ISSUE TITLE
UI and data table for Spam Management Dashboard

### ISSUE THREAD

**Issue by keshavsethi** [publiclab/plots2#7927]
All the functionality of the current Spam Management Dashboard is included in the new UI. Bulk moderation is still left.
Other items in sidenav like flagged posts and Queue are not done. _But filtered posts, wiki, comments, and revision are done._ 
I have attached a few screenshots of UI and a PR with this. Please give your reviews to UI. I will make changes accordingly.
Some of the links are disabled as of now. I will add them when that feature is complete 
![Screenshot from 2020-05-19 05-23-37](https://user-images.githubusercontent.com/36025262/82271141-97d8d180-9994-11ea-87ef-2b6d2930d1b9.png)
{This is for WIkis when data is there}
![Screenshot from 2020-05-19 05-23-44](https://user-images.githubusercontent.com/36025262/82271147-9ad3c200-9994-11ea-937c-50301786defd.png)
{This is when data is not available}
![Screenshot from 2020-05-19 05-24-43](https://user-images.githubusercontent.com/36025262/82271150-9d361c00-9994-11ea-99ec-c5c37ee3d0f5.png)
{This is in full screen without sidenav}

Please give your review and suggests changes. @jywarren @SidharthBansal @ananyaarun @pydevsg @emilyashley @cesswairimu and others 
Thanks!!

**Comment by keshavsethi** [comment]
I have made some more changes and added Bulk spam and bulk publish. I have also attached more screenshots and gifs with PR. Please give your reviews. This PR has all the features of the current Spam Management system. 
Thanks!!

**Comment by emilyashley** [comment]
Awesome, thanks for making these. Taking a look at them today 🙌

**Comment by keshavsethi** [comment]
> Awesome, thanks for making these. Taking a look at them today

@emilyashley  I have updated it a bit. Please refer to #7928
Thank you!!
