### ISSUE TITLE
Activity grid pagination or "see all #" if too long

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#793]
Activity grids and inline notes tables can get quite long, as in https://publiclab.org/wiki/spectrometry#Frequently+Asked+Questions

Perhaps we should limit them to 10-20 posts (length opinions, @ebarry, @gretchengehrke  or @steviepubliclab?) and either paginate (which would be a bit complex to implement) or at least for now, show a link that just says `View all 54`.

This all currently is generated here: https://github.com/publiclab/plots2/blob/master/app/helpers/application_helper.rb#L31

But we could do it in JavaScript in the method which sets up the table heading sorter methods, and is run on each table:

https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/grids.js

If the latter, we should rename the method to `setupGrids()` instead of `setupGridSorters()`.

**Comment by cpdavngr** [comment]
I'd like to try fixing this one.
I'll probably just edit the JavaScript to fix it, but would "will_paginate" be an option?
https://github.com/mislav/will_paginate

**Comment by jywarren** [comment]
Oh cool! My guess is that we won't have enough that we really need to do a
database limit the way will paginate does. And since we have sorting in
JavaScript, we'd then have to refactor sorting to be server side. I agree
it'll be easier to do this in JavaScript and assume we'll have a max of,
say, 40-50 rows to show.

Thanks!

**Comment by jywarren** [comment]
How are things going here -- need any help or tips? Were you able to get the Jasmine javascript tests running? I believe there's a test for the "sorting" function of the activity grids.

**Comment by jywarren** [comment]
Hi - don't want to rush you -- but just want to make sure you're not stuck here; if there's anything I can to to make suggestions, please ping me. Thanks!

**Comment by cpdavngr** [comment]
Hi,

No issues so far. I just had big class load for school over the past few weeks and wasn't able to work on this much. I should be able to revisit it now. Thanks!

-Ralph

**Comment by jywarren** [comment]
Hi, Ralph - just wanted to say we've added some more JavaScript tests to the `rake spec:javascripts` suite, and I don't think that'll affect your work, but just a heads up. And please do reach out if you get stuck, thanks!

**Comment by cpdavngr** [comment]
Hi, just started working on this again (classes finally over). Is there a quick way to put some entries into the sample database to simulate the problem? Right now, I'm just creating a bunch of entries manually.  Let me know, thanks!

**Comment by jywarren** [comment]
Cool! There are a number of examples that could be sourced from the fixtures here:

https://github.com/publiclab/plots2/blob/master/test/fixtures/node.yml

For example in this test: https://github.com/publiclab/plots2/blob/master/test/integration/node_insert_extras_test.rb

You could manually enter that or perhaps add to the seed data in:

https://github.com/publiclab/plots2/blob/master/db/seeds.rb

That could then be instantiated with "rake db:seed", I believe. Like shown here:

http://stackoverflow.com/questions/761123/what-is-the-best-way-to-seed-a-database-in-rails#2070869

**Comment by jywarren** [comment]
I'm resolving this in javascript, in a series of pull requests today. Thanks!!!

#1274, #1271, #1272, #1273

**Comment by cpdavngr** [comment]
Sorry I didn't get this done sooner. The random numbered divs made this a bit tricky and I was working on a way to identify them by type without making adjustments to the rest of the divs on the page.

**Comment by jywarren** [comment]
No problem at all! I suddenly realized that just expanding open if it's too
long would solve a lot of problems for this issue and make implementation
simpler and easier to maintain. If you're looking for another one to
tackle, please see our help-wanted issues!
