### ISSUE TITLE
Subscription Tags Out of Order at https://publiclab.org/stats/subscriptions

### ISSUE THREAD

**Issue by dongskyler** [publiclab/plots2#7934]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

**Currently**, subscription tags are ordered in an odd way at [https://publiclab.org/stats/subscriptions](https://publiclab.org/stats/subscriptions), making it difficult to comprehend the information on the popularity of subscription tags.

Here's a screenshot at the time of writing:

<img width="558" alt="Screen Shot 2020-05-19 at 5 08 57 PM" src="https://user-images.githubusercontent.com/19198708/82393385-cf369500-9a0b-11ea-8b78-a96c8f013910.png">

The current order starts with 160-169 subscriptions, and then moves to 0-9, and then 230-239.

It's not in the order of increasing integers or alphabet, although tags in each cell are in alphabetical order.

> What did you expect to see that you didn't?

**My suggestion** is to order Subscription Tags in a **decreasing integer order**. 

For example, it shows tags with the most subscriptions, 370-379 subscriptions, followed by the next highest number, 280-289, and so forth.

Or you can add a feature to let users choose the order (increasing or decreasing, by integer or by tag name, etc).

See comments as references:
- [Here I first described the issue.](https://github.com/publiclab/plots2/issues/7908#issuecomment-631113189)
- [Here @jywarren responded.](https://github.com/publiclab/plots2/issues/7908#issuecomment-631114682)

### Please show us where to look

[https://publiclab.org/stats/subscriptions](https://publiclab.org/stats/subscriptions)

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

Irrelevant. You don't need to login to see this bug.

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

Irrelevant. This is a server-side issue.

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by ebarry** [comment]
Thank you @dongskyler i agree with your suggestion: 
>to order Subscription Tags in a decreasing integer order.

**Comment by urvashigupta7** [comment]
I would like to work on this issue if it is not taken
