### ISSUE TITLE
Weekly Community Check-In #60 - Soc Community Bonding wrap up

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#7950]
Hi everyone! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. 💯

## Community Bonding wrap up 
Let us know what you will be working on this week and if blocked express it below so that you can get help

 ### To Outreachy and GSoc Interns
Hope the community bonding period has been great and you are ready to start coding the summer away next week :smiley: ..if you have any further questions on the anything on the project or community feel free to leave a comment on the planning issues or here. I would like to hear how the past two weeks have been please leave a comment here on how the experience is so far. Also if you have any blogs leave the links below so that we can check them out :+1:  

### To mentors
If you haven't had a chance to check who you will be mentoring this summer please do so within the week and say hi to them on the various projects planning issues and checkout the amazing conversations that are going on there :tada: :tada:  and maybe start being part of them. :smiley: 

### Reviewers and fellow contributors
We would love your help reviewing the interns PRs as they start coming in and also would appreciate chip-ins on discussions on various issues..Let do what we do best...collaborating :balloon: 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone and have a great week 🎈**

**Comment by cesswairimu** [comment]
@urvashigupta7, @jywarren, @dependabot-preview[bot], @daemon1024, @Tlazypanda, @jscastanos, @sarthak-choudhary, @dongskyler, @keshavsethi, @Shulammite-Aso, @ckchu8, @keshav234156, @DerekChristy, @Srija616, @priyanka-choubey, @AyanChoudhary, @imajit, @NitinBhasneria, @nstjean, @marientje, @rutger-t, @Janet33, @TroydonAnabolic, @priyanshbalyan, @Medlineme4, @mandysGit, @msanden, @AidenOliver, @Janetsomehow, @AntroMarina, @llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-s, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @WaldenJosh, @B4Lee, @VisnuGanth, @jessibreen, @alaxalves, @kamal-kaur04

**Comment by alaxalves** [comment]
Hey guys,
This week I have:
- Published a planning issue --> https://github.com/publiclab/spectral-workbench/issues/506
- Opened a PR including Codecov and Simplecov at Spectral Workbench
- Reviewed PRs throughout PL repositories

My main goal for this week is to start increasing Spectral Workbench test coverage percentage (currently 68%, goal is >90%) with @gr455's help. So I can proceed with the upgrades with more confidence. Regarding the Mapknitter's exporter I intend to work on Sebastian's feedback given at https://github.com/publiclab/mapknitter-exporter-sinatra/pull/47 so we can get that merged too.

**Comment by jywarren** [comment]
That's so awesome @alaxalves -- increased coverage will be so great for then making upgrades. It'll give us enormous confidence. Do you think that system tests which walk through the steps in the tutorials in https://publiclab.org/wiki/spectral-workbench will be possible? 

Fantastic! I merged your SimpleCov/CodeCov PR too. Great work!

**Comment by jywarren** [comment]
Hi folks via Outreachy and GSoC! I wanted to highlight a couple notes I left for @keshavsethi on:

* using our `unstable` server to test changes on plots2 codebase: https://github.com/publiclab/plots2/pull/7928#issuecomment-634119437
* referring to our Style Guide on UI and design questions: https://github.com/publiclab/plots2/pull/7928#discussion_r430526808
* using "shadow pages" to introduce new features while not overwriting the previous version yet, so people can opt into using the 'new' interface vs. the 'legacy one' -- https://github.com/publiclab/plots2/pull/7928#issuecomment-634130224

Finally, it's a good idea to think about what would be a minimal milestone, or set of changes we could refine and get completely right before merging, in each PR you make, leaving further new ideas and projects for later PRs. This ensures we don't have a long-running branch that will be harder to review, catch bugs in, and rebase/sync in order to merge. We want to do these things in bite-sized pieces so we can be really thorough! 

Thanks, all! Hoping these tips help you structure your work as you begin!!! 🎉 💯 🙌 

cc 
@Tlazypanda @Shulammite-Aso @shreyaa-s @keshav234156 @keshavsethi @alaxalves @NitinBhasneria, mentors: @CoderJolly @subhahu123 @ananyaarun @starkblaze01 @govindgoel @sidntrivedi012 @debck @cesswairimu @SidharthBansal @sagarpreet-chadha @emilyashley

**Comment by Tlazypanda** [comment]
Hey @jywarren Thanks so much for the notes :tada: 

So this week I have been researching more on the codebase and how to optimise further. Have certain doubts about how we should organize the packages (yarn vs gem vs cdn) and if where should we keep the files (assets.rb or application.js/css or not a part of the asset pipeline). Need your help with these folks :v: 

Have opened some PRs that require reviews https://github.com/publiclab/plots2/pull/7937 https://github.com/publiclab/plots2/pull/7938 https://github.com/publiclab/plots2/pull/7943 https://github.com/publiclab/plots2/pull/7939 https://github.com/publiclab/plots2/pull/7945 

Also have started working on my blog which I am hosting on my personal blog site (found this great jekyll theme) this is an initial draft: https://tlazypanda.github.io/opensource/2020/05/09/outreachy'20-my-journey-with-publiclab/ rest is under construction :sweat_smile: Looking forward to feedback :v:

**Comment by keshav234156** [comment]
Thanks, @jywarren!!. I am currently working on https://github.com/publiclab/PublicLab.Editor/issues/487 . If anyone has faced Bugs related to code module please list that in the issues or if you can provide suggestions regarding already listed bugs in the issue than that would be even more beneficial. 

Does anyone know how to test Editor post changes locally? Like if we write something on http://localhost:3000/post and then post it . This doesn't show, how the content would look on in the actual website. Is there any way or workaround?

**Comment by shreyaa-s** [comment]
Hey everyone!
Thanks @jywarren !
@Tlazypanda I loved the blog :heart: 
@alaxalves great work :+1: 

I've been working on https://github.com/publiclab/PublicLab.Editor/issues/457. The last week was spent digging through the code, going through the various opened issues, finding the concerned code, rigorous testing to find something relevant for a bug or ways to reproduce it and trying to leave feedback wherever I could. 
I'm still working on my blog. Hope to get it up soon.

**Comment by cesswairimu** [comment]
Hey all, anyone would like to open this week's check-in?

**Comment by cesswairimu** [comment]
Sorry for the delay yesterday was a holiday in Kenya... New check-in here https://github.com/publiclab/PublicLab.Editor/issues/523.. Thanks all

**Comment by jywarren** [comment]
Also noting to folks that I'm finishing up reading through and responding to your comments in this check-in as well, today! Thanks for a great week! 

@Shulammite-Aso @NitinBhasneria @keshavsethi perhaps we'll hear from you (even briefly) next week? I know you've been working hard in various issues and I definitely see you -- but just to get in the habit of chiming in here would be great. Thank you so much!
