### ISSUE TITLE
Update text in alert

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#7959]
https://github.com/publiclab/plots2/blob/3b30fd05bf10fb9b893847b36709682a317ae8f2/app/views/like/_like.html.erb#L87

Please replace the text "Are you sure?" with "All revisions will be lost, and you cannot undo this action. If this is a spam page, be sure that it did not overwrite valid content before deleting the entire page ++and the history++."

**Comment by Tlazypanda** [comment]
Hey @ebarry! I was going to create a fto out of this but not sure about what does the ++ mean in  page ++and the history++." Can you help me out? :sweat_smile: Thanks :v:

**Comment by ebarry** [comment]
Wow thanks!
I think that the writer just meant to add emphasis, like **bold text**, to "and the history"

Even if a First Time Contributor wouldn't know how make that phrase bold, if they could simply edit the alert message, it would be helpful!

**Comment by Tlazypanda** [comment]
@ebarry Thanks for letting me know :tada: I have opened the fto https://github.com/publiclab/plots2/issues/7990 Please Let me know if it works :smile:

**Comment by ebarry** [comment]
looks great! Closing this one in favor of that one.
