### ISSUE TITLE
Clicking "edit" on a question comment doesn't open an edit interface

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#796]
### What happened just before the problem occurred

I was on a question page and clicked the "pencil" edit icon for a comment i'd just made, but wasn't shown an editor or the comment text -- it seemed to show me a new blank box:

![screenshot 2016-09-07 at 9 56 00 am](https://cloud.githubusercontent.com/assets/24359/18314520/5fe6397e-74e1-11e6-809d-0af29d8505e6.png)
### Relevant URLs

https://publiclab.org/questions/stevie/09-06-2016/question-has-anyone-used-a-timelapse-camera-in-stream-monitoring
### Browser, version, and operating system

latest Chrome

**Comment by jywarren** [comment]
@ananyo2012 , would you mind taking a look at this? Perhaps we could add a JS test. Thanks!

**Comment by ananyo2012** [comment]
Just looking at it Jeff
ᐧ

**Comment by ananyo2012** [comment]
@jywarren I don't see this in development as well as in a question in production which I previously posted https://publiclab.org/questions/ananyo2012/08-17-2016/is-the-question-interface-working. Can recheck once if it's happening again?

**Comment by ananyo2012** [comment]
I am trying to add a javascript test for this.

**Comment by ananyo2012** [comment]
Ok I see it now. This is related to #797

**Comment by ananyo2012** [comment]
Comments with a new line character aren't editable now.

**Comment by jywarren** [comment]
Ah, ok -- good catch. Yes, I think a JS test is a good idea. Thanks!!!!! So glad the JS tests will be more reliable now.

**Comment by jywarren** [comment]
This is fixed, closing!
