### ISSUE TITLE
Error on commenting on a question

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#797]
### What happened just before the problem occurred

I left a comment with some markdown in it ( the `> hello world` block quote syntax) and, though I don't know of that was the problem, I saw an error:

![screenshot 2016-09-07 at 9 59 48 am](https://cloud.githubusercontent.com/assets/24359/18314666/054c1c08-74e2-11e6-93be-d63ec8b2a42e.png)

However on page refresh, the comment was saved. @ananyo2012 - sorry, would you mind taking a look here? Perhaps a test in Ruby is needed for this one? Thanks!

### Relevant URLs

https://publiclab.org/questions/stevie/09-06-2016/question-has-anyone-used-a-timelapse-camera-in-stream-monitoring

**Update:** This is likely due to questions not permitting newline characters; see below.

**Comment by ananyo2012** [comment]
Catching this one too Jeff!
ᐧ

**Comment by ananyo2012** [comment]
Uh Ok I see this is not a problem of the blockquote but  something else. Just trying to figure it out

**Comment by ananyo2012** [comment]
I think a new line character is causing the problem.

**Comment by jywarren** [comment]
Hi, Ananyo -- I looked in https://github.com/publiclab/plots2/blob/master/app/models/answer.rb but couldn't find where the newline requirement is in the code -- it's also not apparently in https://github.com/publiclab/plots2/blob/master/app/controllers/answers_controller.rb. Where can we remove this restriction? The only validation I see in the model is that `:content` must exist.

**Comment by jywarren** [comment]
Hi, ananyo -- shall we try writing a unit test for this?

**Comment by Fastie** [comment]
I posted a comment on [this question](https://publiclab.org/questions/liz/09-28-2016/what-are-important-aspects-to-consider-about-replication-on-the-website-and-in-the-community), but the comment did not display in Chrome. Then I posted the same comment again, and it still did not display. The page indicated that there were two comments, but did not let me see them. Then I posted the same comment on Jeff's existing answer to that question and it displayed normally. 

The next day I noticed that my two comments on the question were still not displaying, but later I noticed that the all three copies were displaying normally in Chrome and in Internet Explorer. So I deleted two of the copies including the copy on Jeff's answer. 

Later I noticed that my single comment (on the question) was not displaying, but 30 minutes later it was displaying. I have noticed similar behavior on other questions. It seems that the question page often indicates that there is a comment on the question, but there is no way to display that comment.

**Comment by Fastie** [comment]
This link: https://publiclab.org/questions/liz/09-28-2016/what-are-important-aspects-to-consider-about-replication-on-the-website-and-in-the-community#anwer-0-comment

does not allow the comment to be displayed. This is the link from the dashboard if you click "1 comments."

This link: https://publiclab.org/questions/liz/09-28-2016/what-are-important-aspects-to-consider-about-replication-on-the-website-and-in-the-community

displays the comment normally.

**Comment by ananyo2012** [comment]
Ok this issue occured earlier. This is due to the anchor link after the
link. I will take a look at this.
ᐧ

**Comment by jywarren** [comment]
Solved the original 'multiline comment' issue in #867 - can you rename this issue or open a new one to reflect the new issue Chris has identified? Thanks.

**Comment by jywarren** [comment]
Moving to a new issue in #873 and closing this one.
