### ISSUE TITLE
first-time-only

### ISSUE THREAD

**Issue by AndrewWei-Colosseum** [publiclab/plots2#7970]
Let's start

**Comment by Tlazypanda** [comment]
Hey @AndrewWei-Colosseum :wave: Welcome to Publiclab! Would you be interested in working on a first-timers-only issue? :tada:

**Comment by Yonttee** [comment]
hi im interested in working on a first timer only issue

**Comment by Tlazypanda** [comment]
Hey @Yonttee Welcome to Publiclab :tada: :balloon: Here is a first-timers-only issue that you can work on https://github.com/publiclab/plots2/issues/6756

**Comment by emilyashley** [comment]
Hi! Welcome!

**Comment by swarajpure** [comment]
Hello. Is there anything I can work on?

**Comment by ebarry** [comment]
HI @swarajpure , looks like most of the first-timers-only issues are being worked on. If you let us know which of the "FTO-candidate" issues might be something that your skillsets are applicable to with a little more help, please comment in on one of these and others can help get it all the way to a properly formatted FTO that you can work on: https://github.com/publiclab/plots2/labels/fto-candidate
