### ISSUE TITLE
Recursive "subscribe to question" link!

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#798]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem
I was looking for the best link to give to people to subscribe to question topics. I ended up here:  https://publiclab.org/questions/tag/question:spectrometry and realized the subscription link in it is recursive. It doubles up the "ask a question about `question:spectrometry`" to make a tag `question:question:spectrometry`

This URL is formatted properly for people to subscribe to `question:spectrometry` https://publiclab.org/tag/question:spectrometry

## Solution
This is a special case of `question` power tags as they itself refer to a question. So if we encounter this situation we should simply replace the `question:topic` tag by `topic`. So the best way to do this is replacing the GET parameter `params[:id]` with
```ruby
params[:id].gsub('question:', '')
```
The code for the post question and subscribe button is here https://github.com/publiclab/plots2/blob/master/app/views/tag/show.html.erb#L84
## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by ananyo2012** [comment]
Yeah that's a thing I also noticed previously but forgot to mention. I
think we should extract the question topic for question tags.
ᐧ

**Comment by ananyo2012** [comment]
Well this is a special case of `question` power tags. So we can simply replace the the tagname that we get using the GET parameter like `params[:id].gsub('question:','')`

But I was thinking whether we can ask question for other power tags? If so we should deal with that too. @jywarren Thoughts on this?

**Comment by jywarren** [comment]
Ananyo, I'm not sure honestly... Sometimes I think there's a lot of
interesting unexpected functionality that could result from power tags. I
think catching if it starts with "question:" and treating it as a special
case makes sense.

**Comment by ananyo2012** [comment]
Ok Jeff let's make it simple for now, just treating question power tags as a special case. I am making this a first-timer issue and adding it as a Google Code-in task.

**Comment by abbastailor** [comment]
I am participating in Google Code-in and want to work on this issue.This would also be my first open-source contribution.

**Comment by ananyo2012** [comment]
@abbastailor Please claim this task first. Then you can start working on this issue. I hope you have already found the task.

**Comment by BrainBuzzer** [comment]
I don't know if I am doing this right so just asking. Should that line be looking like this.

    <% unless @wildcard %><p style="clear:both;padding-top:8px;"><a style="margin-bottom:6px;" class="btn btn-primary" href="/post?tags=question:<%= params[:id] %>&template=question&redirect=question"><i class="fa fa-white icon-question-circle"></i> <%= raw t('tag.show.ask_question', :tag => params[:id]) %></a> <%= raw t('tag.show.or_subscribe_to_answer', :url1 => "/subscribe/tag/question:"+params[:id].gsub('question:', '')) %></p><% end %>

Just the final part is edited.

**Comment by ananyo2012** [comment]
@BrainBuzzer You need to do the same for each occurrences of `params[:id]` in that line.
