### ISSUE TITLE
(Link to) advanced search is wack!

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#800]
### What happened just before the problem occurred

i searched for a term for which there were no results. (i recreated this error with a neutral term "noresults" (haha): https://publiclab.org/search/noresults

Screenshot: 
![screen shot 2016-09-07 at 5 22 42 pm](https://cloud.githubusercontent.com/assets/161439/18329045/c042edf6-751f-11e6-9c79-68d0dce45433.png)

On that page of no results, i clicked on the link in "Try an advanced search" -- which went to a broken page of URL https://publiclab.org/searches/advanced/

![screen shot 2016-09-07 at 5 19 35 pm](https://cloud.githubusercontent.com/assets/161439/18328991/91eb0e5c-751f-11e6-912f-2c89f3ff7d2b.png)

### PublicLab.org username

liz

**Comment by jywarren** [comment]
I believe this is pending @ujithaperera's work in https://github.com/publiclab/plots2/pull/781, but there could also be a separate issue in @david-days API code? Would you two mind taking a look?

**Comment by david-days** [comment]
I will take a look.  I am betting on routes.rb, which was reworked a few
times over gsoc.

**Comment by ujithaperera** [comment]
This can be fixed easily by adding correct link to the page. But I also found that several route duplications in the the file.

**Comment by jywarren** [comment]
#810 was just merged in, and we'll be looking at advanced search functionality once it gets published on the site on Thursday; it may take some additional tweaks.

**Comment by jywarren** [comment]
This needs additional work for tests that return no results. I'll see what I can do!

**Comment by jywarren** [comment]
I wasn't able to reproduce this on publicla.org and think perhaps it's been fixed already!
