### ISSUE TITLE
Add aria-label for input field in /subscriptions route 

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#8000]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/home/subscriptions.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/home/subscriptions.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Make changes in line 49

```diff
49 <input type="text" name="name" class="form-control" placeholder="<%= translation('home.subscriptions.enter_tags') %>" data-provide="typeahead" data-source='<%= Tag.all_tags_by_popularity %>' autocomplete="off" required="required">
```

Replace this line with -

```diff
49 <input aria-label="Enter tags" type="text" name="name" class="form-control" placeholder="<%= translation('home.subscriptions.enter_tags') %>" data-provide="typeahead" data-source='<%= Tag.all_tags_by_popularity %>' autocomplete="off" required="required">
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by Tlazypanda** [comment]
@cesswairimu @jywarren can you kindly approve? :sweat_smile: Tested locally - 
Before  
![image](https://user-images.githubusercontent.com/33183263/83976250-81c88c00-a916-11ea-88b5-dd56e7e7d58f.png)
After  
![image](https://user-images.githubusercontent.com/33183263/83976267-97d64c80-a916-11ea-92bc-5c163d2bb38c.png)

**Comment by cesswairimu** [comment]
Looks good...thanks @Tlazypanda  :tada:

**Comment by esiebomaj** [comment]
This issue has been worked on 😥

**Comment by ebarry** [comment]
Hi @esiebomaj , @cesswairimu made this issue just for you, please begin here...and thank you so much!

**Comment by Tlazypanda** [comment]
@esiebomaj This issue is available :sweat_smile: Ignore the tested locally msg above, the pull request still needs to be created :v: Looking forward to your contribution :tada:

**Comment by esiebomaj** [comment]
great!

**Comment by esiebomaj** [comment]
I have created a PR for this issue with number #8008 
This will be my first open source contribution (excited)
@Tlazypanda @cesswairimu @ebarry

**Comment by cesswairimu** [comment]
That was fast :smile: Tjhanks @esiebomaj

**Comment by cesswairimu** [comment]
cool..Thanks everyone :+1:
