### ISSUE TITLE
Add aria-label for empty link in /questions route

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#8001]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/questions/show.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/questions/show.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Make changes in line 38

```diff
38 <a href="/n/<%= @node.id %>"><i class="fa fa-link"></i></a> <span class="d-none d-xl-inline"><a href="/n/<%= @node.id %>">#<%= @node.id %></a>
```
Replace this line with 

```diff
38 <a aria-label="Link to note" href="/n/<%= @node.id %>"><i class="fa fa-link"></i></a> <span class="d-none d-xl-inline"><a href="/n/<%= @node.id %>">#<%= @node.id %></a>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by Tlazypanda** [comment]
@cesswairimu @jywarren can you kindly approve? :sweat_smile: Tested locally -
Before  
![image](https://user-images.githubusercontent.com/33183263/83976560-45962b00-a918-11ea-8b5d-818bc12611e1.png)
After  
![image](https://user-images.githubusercontent.com/33183263/83976569-5181ed00-a918-11ea-8beb-79a97e4e81ac.png)

**Comment by ishika1727** [comment]
@Tlazypanda Can you please assign this to me?

**Comment by cesswairimu** [comment]
Hi @ishika1727, go ahead...Thanks both

**Comment by habeckmatt** [comment]
Hi, is this issue still open?

**Comment by cesswairimu** [comment]
@ishika1727  are you still working on this?

**Comment by Tlazypanda** [comment]
Hey @cesswairimu I think #8013  is open and ready to be merged the codeclimate is stuck there but if you check on it by clicking the details then the tests have passed :sweat_smile: 

@habeckmatt #8092 #8093 #8094 are available to work on :tada: Thanks for your interest in working with Public Lab :100:

**Comment by cesswairimu** [comment]
cool thanks @Tlazypanda

**Comment by cesswairimu** [comment]
@habeckmatt I will add your name here #7683  and we will ping you once we get an fto...Thanks everyone

**Comment by hiteshsubnani0128** [comment]
Hi, is this issue still open?

**Comment by cesswairimu** [comment]
Hi @hiteshsubnani0128, someone is working on this...will add your name #7683  here and will ping you when we get one for you :)
