### ISSUE TITLE
Weekly Community Check-In #62 - Help New Contributors!

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#8002]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. 💯

## Help New Contributors!

This week we have had a good numbers of new contributors  looking for issues to contribute to and help in reviewing their pull requests. Publiclab is a community that welcomes new contributors with :heart: so let's try to make this process of contribution for these new contributors a cake :cake:  walk!

Here's how you can help!

- Create fto issues or fto-candidates
- Review fto pull requests
-  Incase the new contributor feels stuck at any point for example the tests fail, help them out!

## To Outreachy and GSoC students

Thanks for all the amazing work you have done so far :tada: So we would like to know what great tasks you plan to take on this week :100: If for any reason you would be away from keyboard , let us know in advance :v: Also sometimes tasks might get a bit overwhelming and we may find ourselves struggling but these are one of the many challenges we face in our lives - Celebrate these challenges, ask for your mentor's advice and maybe blog about it (p.s Outreachy's next blog topic is **Everybody Struggles** due on June 9th).

Happy Coding :woman_technologist:

## To mentors
Please be on the lookout for concerns/questions and reviews that the interns so that we can keep the programs running smoothly. Thanks :v:

## Reviewers and fellow contributors
We would love your help reviewing the interns PRs as they start coming in and also would appreciate chip-ins on discussions on various issues..Let do what we do best...collaborating :balloon:

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** 🎈
Have a great week and year ahead all ❤️

**Comment by Tlazypanda** [comment]
@keshavsethi, @jywarren, @AyanChoudhary, @imajit,@NitinBhasneria, @nstjean, @marientje, @rutger-t, @Janet33, @TroydonAnabolic, @priyanshbalyan, @Medlineme4, @mandysGit, @msanden, @AidenOliver, @Janetsomehow, @AntroMarina, @llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-s, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @Tlazypanda, @keshav234156, @WaldenJosh, @B4Lee, @VisnuGanth, @jessibreen, @alaxalves, @kamal-kaur04, @sssash18, @chinmay021, @Srija616, @AnnaMinakova, @greenbrown, @taysa91, @TaishiRoy, @yagmurbaydogan, @Shulammite-Aso, @Jigyasa-Kumari,

**Comment by Tlazypanda** [comment]
@moliver4, @justinelai, @Snouzy, @stevenalila, @Digiox, @yandu31, @milosv1, @jamescapps, @Nevenem, @chirag-wadhwa, @yogeshjdeshmukh, @omizrahi99, @theOpetunde, @sailahonkanen, @robin-natale, @avidler, @ccyccyccy
@urvashigupta7, @daemon1024, @Tlazypanda, @jscastanos, @sarthak-choudhary, @dongskyler, @keshavsethi, @Shulammite-Aso, @ckchu8, @keshav234156, @DerekChristy, @Srija616, @priyanka-choubey, @AyanChoudhary, @imajit, @NitinBhasneria, @nstjean, @marientje, @rutger-t, @Janet33, @TroydonAnabolic, @priyanshbalyan, @Medlineme4, @mandysGit, @msanden, @AidenOliver, @Janetsomehow, @AntroMarina, @llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-s, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @WaldenJosh, @B4Lee, @VisnuGanth, @jessibreen, @alaxalves, @kamal-kaur04

**Comment by Tlazypanda** [comment]
Tagging new contributors - @adityakpranav @esiebomaj  @Yonttee @swarajpure @vinuch @ishika1727 . Welcome to Publiclab :wave: :balloon: Please feel free to drop down a message and let us know if you are looking for new issues or need reviews :v:

**Comment by adityakpranav** [comment]
> 
> 
> Tagging new contributors - @adityakpranav @esiebomaj @Yonttee @swarajpure @vinuch @ishika1727 . Welcome to Publiclab 👋 🎈 Please feel free to drop down a message and let us know if you are looking for new issues or need reviews ✌️

 Hi, @Tlazypanda 👋 thanks for such a warm welcome 😊. As a newbie contributor 👶 looking for a new genuine issue as my first contribution to the community.

**Comment by swarajpure** [comment]
> 
> 
> Tagging new contributors - @adityakpranav @esiebomaj @Yonttee @swarajpure @vinuch @ishika1727 . Welcome to Publiclab 👋 🎈 Please feel free to drop down a message and let us know if you are looking for new issues or need reviews ✌️

Thank you for such a warm welcome. Publiclab seems to be a very friendly and beginner-friendly organization. Would love to contribute in whatever way possible.

**Comment by cesswairimu** [comment]
Thanks @Tlazypanda  for opening this also tagging a new contributor @ioampatzidis

**Comment by ebarry** [comment]
Welcome new contributors and hello more experienced contributors 😃 We are a little low on our stock of first-timers-only issues, and as @Tlazypanda requested above, if you are a little more experienced, a high leverage point contribution would be for you to take a look through som FTO-candidate issues https://github.com/publiclab/plots2/labels/fto-candidate and see if you might be able to advance any into being a real first-timers-only :boom: 🏆https://github.com/publiclab/plots2/labels/first-timers-only :yay:

**Comment by Tlazypanda** [comment]
Hey everyone! :wave: This week I worked on some accessibility issues and one performance related major issue (critical css and rest asynchronous loading) that needs to be tested out thoroughly :sweat_smile: 

I also wrote the second blog for Outreachy here - https://tlazypanda.github.io/opensource/2020/06/08/outreachy'20-blog2-everybody-struggles/ Please give it a read :v: Its more on our mental well being rather than a technical one :stuck_out_tongue: 

@adityakpranav @esiebomaj @Yonttee @swarajpure @vinuch @ishika1727 @ioampatzidis Have opened some ftos here :tada:  https://github.com/publiclab/plots2/issues/8004 https://github.com/publiclab/plots2/issues/8005 https://github.com/publiclab/plots2/issues/8006 https://github.com/publiclab/plots2/issues/8007

**Comment by emilyashley** [comment]
Awesome! Happy to see this ✨ Welcome new contributors!

**Comment by alaxalves** [comment]
Hello Guys, 

This past week I have: 
- Increased Spectral Workbench Test Coverage
- Split production and development Dockerfile at Mapknitter project.
- Received review and updated Ruby upgrade PR at Spectral Workbench

For this upcoming week I plan on:
- Finish multijobs builds at Mapknitter-Export-Sinatra
- Refactor codebase at Mapknitter-Export-Sinatra
- Include rubocop at Mapknitter-Export-Sinatra
- Use ruby official image at Mapknitter-Export-Sinatra Dockerfile

Currently I need review/merge of the following PRs:
- https://github.com/publiclab/mapknitter-exporter-sinatra/pull/58
- https://github.com/publiclab/mapknitter/pull/1329
- https://github.com/publiclab/mapknitter-exporter-sinatra/pull/57
- https://github.com/publiclab/spectral-workbench/pull/513
- https://github.com/publiclab/spectral-workbench/pull/499

PS: I have been feeling super fine, I'm glad for the well wishes messages, I'm very happy to realize that everyone cares. Much love from Brazil and take care :heart:

**Comment by keshav234156** [comment]
Hey everyone, last week I worked in implementing a linting tool for PublicLab.Editor (https://github.com/publiclab/PublicLab.Editor/pull/519) .This week I will try to improve code module and Bold module wrapping function based on further reviews

**Comment by NitinBhasneria** [comment]
Hey everyone, hope all are safe.
Last week I have made some changes in image module CSS. Implemented the popup issue and solved it. (https://github.com/jywarren/woofmark/pull/3).
This week I will try to finish the Title B module issues and adding the features of seeing and removing the tagged post.
Currently, I am confused about how the suggestion in the title module works.
Thanks, everyone.

**Comment by Shulammite-Aso** [comment]
Hi all!  So this week i want to start working on the UI for users to document bugs they come across in PublicLab.Editor, I already have the mock-up, what is left is to implement.  I've also been trying to help with debugging Woofmark's  difficulty  with un-selecting tools or modules once they've been selected, I'll try to find some more time to look into it this week too. 

Also I made my second blog post,  here is the link https://shulammiteaso.wordpress.com/2020/06/09/everybody-struggles/

Thank you!!!

**Comment by jywarren** [comment]
Hi all! I'm back after some days offline and it's really wonderful to see everyone here, checking in with each other, helping one another out. Huge thanks to @Tlazypanda for opening this as well as for creating some FTOs for people! 

GSoC/Outreachy folks, if you are stuck on something, please reach out to each other for reviews and input, and I've also connected up all our Editor Team mentors:  @Divy123 @sidntrivedi012 @subhahu123 @starkblaze01 @debck @ananyaarun @govindgoel @pydevsg @blurry-x-face and of course @emilyashley and myself.

Thank you @Shulammite-Aso and @Tlazypanda for the blog posts, I really appreciate them and look forward to reading them!

Catching up on updates across the board -- ping me in the chatroom if you need something urgently! Thanks again!

**Comment by cesswairimu** [comment]
Hi, thanks everyone for sharing and a big welcome to the new folks... is any of the interns willing to open next week check-in? Happy Friday all

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/8040. Thanks everyone
