### ISSUE TITLE
Fix icons issue after migration to font-awesome-rails

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#8023]
### Please describe the problem (or idea)
Some icons available in Font Awesome 5.0 are currently used in the application which aren't getting loaded now since font-awesome-rails makes use of v4.7.0.

The icons are as follows and can be replaced by their counterpart of the FA v4.7.0 library instead:-
- fa-map-marker-alt -> fa-map-marker
- fa-dot-circle -> fa-dot-circle-o

One more thing noticed in file `layouts/_header` the bars icons needs to be called as `fa fa-bars` instead of `fas fa-bars`

> What did you expect to see that you didn't?
Icons not getting loaded

**Comment by Tlazypanda** [comment]
@jywarren Can you point me to the right files for the leaflet map icons? I can't seem to find them in plots2 :sweat_smile:

**Comment by jywarren** [comment]
Hi! @icarito sez:

> Staging's /system/images folder is setup such that any missing images are pulled from production if not found locally (I did this thru nginx). But images in other directories could be missing.
> Let me know if there's another path that should work the same! I see for instance /system/profile/photos could be such an instance...

Hope that helps!!!

**Comment by Tlazypanda** [comment]
Hey @jywarren I am not sure if I understand correctly :sweat_smile: I have to edit the font awesome icons called that is-   

![image](https://user-images.githubusercontent.com/33183263/84558119-fef86480-ad4d-11ea-88d8-3b65352c75dc.png)  

The `fas fa-map-marker-alt` shown here needs to be replaced with `fa fa-map-marker` since this icon is part of FA 5.0 and not available in v4.7 so I am not sure about the system routes since these are not like images but like <i> tags with the FA icons :sweat_smile: I am confused :confused: Am I missing something out here? :sweat_smile:

**Comment by jywarren** [comment]
Ah but you can't find where the HTML is? I wonder if it's actually in the upstream library leaflet-environmental-layers?

**Comment by jywarren** [comment]
If so, could it be somewhere here?

https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/leaflet_helper.js

**Comment by jywarren** [comment]
Maybe they're instantiated here and we need to detect fontawesome version?

https://github.com/publiclab/leaflet-environmental-layers

**Comment by Tlazypanda** [comment]
Ohh @jywarren  so this code wasn't part of plots2 repo at all then :sweat_smile: I was so confused looking for it :laughing:  I found it in the leaflet-environmental-layers repo just gimme some time to setup this repo and will open a pr there then :v:

**Comment by Tlazypanda** [comment]
@jywarren So I went through lel :sweat_smile: and the issue is that lel has v5.0 Font Awesome so we can either bump down it to 4.7 (possible since the icons used in lel are also available on 4.7) or bump up plots2 (not possible since there is a lot of icons used with fa class and some icons names have changed in the newer version).

A temporary fix for now will be to include cdn link for Font Awesome in LEL and then later migrate it to 4.7. So what should I do for now? :sweat_smile:

**Comment by Tlazypanda** [comment]
@jywarren Noticed some more issues arising due to the FA 5 being loaded after FA 4.7 thus overwriting some of the css of the icons, have added one more fix here
