### ISSUE TITLE
Weekly Community Check-In #63 - Stay Updated!

### ISSUE THREAD

**Issue by keshavsethi** [publiclab/plots2#8040]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. 💯

## Stay Updated

This week lets update and document our progress properly which will help fellow interns, mentors, and other members to review our code and give suggestions. Weekly standups and documentation by making weekly research note is a good idea. This can have some list of tasks that are completed and future plans including some major issues which we are currently facing and blocking our progress. This will also help us to be productive and updated in these times
_There are three ways in which can keep our mentors updated:_

-  Making a note in Public lab and make a common tag for this like weekly-update
- Comment here in this check-in :sweat_smile: 
- Update in weekly standups by DIAL

## To Outreachy and GSoc Interns
Thanks for the commendable work last week :tada: :tada: Please update your progress here and let us know about issues and blockers which you are facing. It will be nice if we help each other and newcomers by reviewing and suggesting some changes. Let's work together and make Public Lab _awesome_ :balloon: 
Happy coding :heart: 
 
## To Mentors, Reviewers and fellow contributors
Thanks to all the reviewers and mentors for all the efforts which you are putting in reviewing our code and helping us at every point of time :100:. Let's do our best by collaborating and helping each other :smile: :tada: 

## Next Check-in
If you would like to open the next check-in. Leave a comment below. We are happy to help if it's your first time

**Thanks everyone for making Public Lab awesome** 🎈
Have a great week and year ahead all ❤️
Stay safe! :hugs:

**Comment by keshavsethi** [comment]
@keshavsethi, @jywarren, @AyanChoudhary, @imajit,@NitinBhasneria, @nstjean, @marientje, @rutger-t, @Janet33, @TroydonAnabolic, @priyanshbalyan, @Medlineme4, @mandysGit, @msanden, @AidenOliver, @Janetsomehow, @AntroMarina, @llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-s, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @Tlazypanda, @keshav234156, @WaldenJosh, @B4Lee, @VisnuGanth, @jessibreen, @alaxalves, @kamal-kaur04, @sssash18, @chinmay021, @Srija616, @AnnaMinakova, @greenbrown, @taysa91, @TaishiRoy, @yagmurbaydogan, @Shulammite-Aso, @Jigyasa-Kumari

**Comment by keshavsethi** [comment]
@moliver4, @justinelai, @Snouzy, @stevenalila, @Digiox, @yandu31, @milosv1, @jamescapps, @Nevenem, @chirag-wadhwa, @yogeshjdeshmukh, @omizrahi99, @theOpetunde, @sailahonkanen, @robin-natale, @avidler, @ccyccyccy
@urvashigupta7, @daemon1024, @Tlazypanda, @jscastanos, @sarthak-choudhary, @dongskyler, @keshavsethi, @Shulammite-Aso, @ckchu8, @keshav234156, @DerekChristy, @Srija616, @priyanka-choubey, @AyanChoudhary, @imajit, @NitinBhasneria, @nstjean, @marientje, @rutger-t, @Janet33, @TroydonAnabolic, @priyanshbalyan, @Medlineme4, @mandysGit, @msanden, @AidenOliver, @Janetsomehow, @AntroMarina, @llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-s, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @WaldenJosh, @B4Lee, @VisnuGanth, @jessibreen, @alaxalves, @kamal-kaur04

**Comment by keshavsethi** [comment]
Hey Everyone :wave: Hope you all are fine :heart: This is my update for last week
- Last week I worked on Digest for unmoderated posts and wrote a test for it(https://github.com/publiclab/plots2/pull/7987). There were few errors in stable, I checked its build logs ad made some changes which are in PR(https://github.com/publiclab/plots2/pull/7987). I noticed that /spam also has few issues in stable which were mentioned in https://github.com/publiclab/plots2/pull/8037. I worked on System test for /spam2 and made a PR for this at https://github.com/publiclab/plots2/pull/8038. 
- Next week I am planning to work on some more filters in all the tables and check dashboard in the stable which is having some issues for /spam2 
- Current blockers: I have mentioned those in https://github.com/publiclab/plots2/pull/8037, Please review and give suggestion

Thanks!!

**Comment by Tlazypanda** [comment]
Hey everyone :wave: 

This week I worked on some accessibility issues, issues fixing the icons error migration to FA v4.7, loading critical css and rest asynchronously ( #7996 review required help!! :sweat_smile: ) , opened some ftos for newcomers and started working on lazyloading images #8043 (any feedback appreciated :v:) 

Also need inputs on #7991 before proceeding further :sweat_smile: 

Also welcoming some new contributors to Publiclab :balloon: :tada: :clap:  @Janitham97  @markkulube @JapneetSingh5 @imanishbarnwal Thanks everyone for your contributions to Publiclab!!

**Comment by jywarren** [comment]
@keshavsethi - i see you've linked all your PRs together here, so apologies for asking that in another issue! This is super. If you could also link them together to the Spam milestone that'd be great as well! Great work!

@Tlazypanda you're doing great work too! I did note some oddities with asset loading paths in a few related issues and I think this is something to watch out for, although at least one may not have been related to your work -- but I'd super appreciate your input as you've been dealing with asset loading in any case!

Looking at your linked-to issues as well. Thanks a ton! 

And WELCOME to new contributors! 🎉 🎉 🎉 You're awesome!!!!

**Comment by jywarren** [comment]
@keshavsethi https://github.com/publiclab/plots2/pull/8038 looks really great. I LOVE system tests because they really show reviewers (and future contributors) how the code is supposed to work, and they make merging PRs much easier, as they guarantee functionality! Approved and ready to merge with your final confirmation!

**Comment by jywarren** [comment]
Folks in the Editor project - @Shulammite-Aso @NitinBhasneria @shreyaa-sharmaa @keshav234156 -- i see lots of great work and both you and other @publiclab/soc folks may want to look at the coordination issue @emilyashley opened at https://github.com/publiclab/PublicLab.Editor/issues/532 - covering how to get changes to upstream libraries ready to be released and merged downstream all the way to PublicLab.org. 

One note on that is that we haven't republished PublicLab.org for a couple weeks and pending some changes to the /spam2 page (@keshavsethi) and the map icon assets (@Tlazypanda) we can do that soon and you'll see your work go live! 😅 🎉 

Finally, some of you are starting to see how certain issues/tasks/sub-projects are seen as higher or lower priority by the @publiclab/community-reps team, and that's ok! I suggest making a `low-priority` label in your repositories to indicate that such issues could be put on hold to make time and space for the more high priority issues. This is natural at this point in the summer as you unearth lots of old issues and get things cleaned and sorted out, and refine the order in which you want to take on projects!

Thanks, everyone!

**Comment by jywarren** [comment]
@Tlazypanda - just to clarify, i see one issue with an icon at https://stable.publiclab.org/tag/balloon-mapping -- i think probably a fontawesome version issue? 

![image](https://user-images.githubusercontent.com/24359/84827415-6df5e780-aff2-11ea-9fda-3776c3d15cf2.png)

**Comment by Tlazypanda** [comment]
Hey @jywarren I have resolved the icon errors here publiclab/plots2#8041 I think this should resolve all the errors 😅 can you kindly have a look ? Thanks ✌️ and again sorry for all the inconvenience caused with this issue, the migration caused unwanted changes in separate libraries and features not present in the codebase

**Comment by jywarren** [comment]
Done! No problem at all!!!

**Comment by cesswairimu** [comment]
Hello all, and thanks @keshavsethi  for opening this issue :tada: 
Planning to review most pending soc PRs this week and catching up on any discussions happening on the planning issues. Great job everyone and have a great rest of the week

-------
Also anyone willing to open next week's check-in kindly express your interest here. Thanks

**Comment by shreyaa-sharmaa** [comment]
Hey everyone!
I hope everyone's doing fine. 
I had some trouble with my github account last week and I'll be using this one from now. For this week I'll be working on https://github.com/publiclab/PublicLab.Editor/issues/503.
To be reviewed:
https://github.com/jywarren/woofmark/pull/5
Thanks!

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/8059. Thanks everyone
