### ISSUE TITLE
Weekly Community Check-In #64 - We are here for you.

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#8059]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. 💯

## We are here for you.
This week we would like to focus on the importance of mental health and communication. With tragic incidents happening all over the world, we believe it is of utmost importance to address this issue. Nothing is more important than your life. Things can be overwhelming but remember it's alright to take out time for yourself. No matter how big problems seem right now, they always have one way or the other out .

This community will always look out for you, please don't hesitate in sharing your feelings. Speak your heart :heart:  out and seek help :sos: 

Also for all those out there who have lost someone special, hang in there ... we are always a text away.

## To Outreachy and GSoC students
Thanks for all the amazing work you have done so far :tada:   So we would like to know what great tasks you plan to take on this week :100:   If for any reason you would be away from keyboard , let us know in advance :v:   Also sometimes tasks might get a bit overwhelming and we may find ourselves struggling but these are one of the many challenges we face in our lives - Celebrate these challenges, ask for your mentor's advice and maybe blog about it.

Happy Coding :woman_technologist:

## To mentors
Please be on the lookout for concerns/questions and reviews that the interns so that we can keep the programs running smoothly. Thanks  :v: 
## Reviewers and fellow contributors
We would love your help reviewing the interns PRs as they start coming in and also would appreciate chip-ins on discussions on various issues..Let do what we do best...collaborating :balloon: 
## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time #5627 

Thanks everyone for making Public Lab awesome 🎈
Have a great week and year ahead all ❤️

**Comment by Tlazypanda** [comment]
@keshavsethi, @jywarren, @AyanChoudhary, @imajit,@NitinBhasneria, @nstjean, @marientje, @rutger-t, @Janet33, @TroydonAnabolic, @priyanshbalyan, @Medlineme4, @mandysGit, @msanden, @AidenOliver, @Janetsomehow, @AntroMarina, @llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-s, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @Tlazypanda, @keshav234156, @WaldenJosh, @B4Lee, @VisnuGanth, @jessibreen, @alaxalves, @kamal-kaur04, @sssash18, @chinmay021, @Srija616, @AnnaMinakova, @greenbrown, @taysa91, @TaishiRoy, @yagmurbaydogan, @Shulammite-Aso, @Jigyasa-Kumari

**Comment by Tlazypanda** [comment]
@moliver4, @justinelai, @Snouzy, @stevenalila, @Digiox, @yandu31, @milosv1, @jamescapps, @Nevenem, @chirag-wadhwa, @yogeshjdeshmukh, @omizrahi99, @theOpetunde, @sailahonkanen, @robin-natale, @avidler, @ccyccyccy
@urvashigupta7, @daemon1024, @Tlazypanda, @jscastanos, @sarthak-choudhary, @dongskyler, @keshavsethi, @Shulammite-Aso, @ckchu8, @keshav234156, @DerekChristy, @Srija616, @priyanka-choubey, @AyanChoudhary, @imajit, @NitinBhasneria, @nstjean, @marientje, @rutger-t, @Janet33, @TroydonAnabolic, @priyanshbalyan, @Medlineme4, @mandysGit, @msanden, @AidenOliver, @Janetsomehow, @AntroMarina, @llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-s, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @WaldenJosh, @B4Lee, @VisnuGanth, @jessibreen, @alaxalves, @kamal-kaur04 @adityakpranav @esiebomaj @Yonttee @swarajpure @vinuch @ishika1727

**Comment by ebarry** [comment]
Happy new week all! 🌳
Incredible work last week by so many people -- really impressive! 🌟
A personal thanks from me to all who found time and attention to look into details with tag pages, especially considering that those efforts were in addition to their own projects 🌺

**Comment by jywarren** [comment]
Hi, all! Back from helping my family out and ready to get plugged back in; the tag page design overhaul in #8046, and tracking a posting issue as well. Will be looking in to see how all Outreachy and GSoC folks are doing as well! 🎉

**Comment by jywarren** [comment]
Also - @Tlazypanda would you mind updating https://github.com/publiclab/plots2/issues/5627 to link here? Thank you!!!!!

**Comment by jywarren** [comment]
Congrats btw on a lot of merged PRs this week. And congrats to https://github.com/publiclab/plots2/pull/8034 for getting a big PR merged for spam moderation!

Excited to see the Editor team work together on their first release! https://github.com/publiclab/PublicLab.Editor/issues/532 🎉

**Comment by jywarren** [comment]
And THANK YOU to all the mentors @publiclab/soc who have been helping out!!!!

**Comment by Tlazypanda** [comment]
Hey everyone :wave: So this week, I worked on some changes with lazy-loading images, started drafting the documentation for performance and accessibility guide #8057 and some more accessibility fixes. 

Some of the tasks which have been a blocker for me now :sweat_smile: : - (Help needed!!) https://github.com/publiclab/plots2/pull/7939, https://github.com/publiclab/plots2/pull/7945, https://github.com/publiclab/plots2/issues/5095 (the mysterious ownloading thing) 

Needs review :smile:  : - #7996, #7958, #7989 

@publiclab/Publiclab.Editor can your please give me your inputs on #7991 ? Thanks :v:  

Also noting @jywarren @ebarry @cesswairimu  That the publiclab site has a lot of static images which need to be lazyloaded (the code for this isn't accessible to me) as well so I have documented how to do it here #8057  so maybe we can migrate to this as well :sweat_smile: with your help :tada:

**Comment by SidharthBansal** [comment]
Hi all,
This week we have GSoC First Evaluations so please don't forget to fill out the forms before the deadline. It will just take 5 minutes so fill it asap.
Quick updates from my side: I will be joining a gaming startup `Gameskraft` from Wednesday. Really excited to start the FTE job. :)

**Comment by Tlazypanda** [comment]
Hey @SidharthBansal Congratulations!! :tada: :clap: :100:

**Comment by TroydonAnabolic** [comment]
Updates from my side, joined a free course that will give me an opportunity to gain the AWS Cloud Practicioner and increase my chance to get a dev job in the cloud.

**Comment by cesswairimu** [comment]
Anyone interested in opening this week's check-in?

**Comment by ebarry** [comment]
Congrats @SidharthBansal !!!!!

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/spectral-workbench/issues/520. Thanks all :heart:
