### ISSUE TITLE
Q&A Tab for unanswered questions

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#806]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled.

This will need to be broken up into multiple parts to become `first-timers-only` issues -- we've suggested 4 pieces below:

****

## The problem

I was just going through the Q&A feature and thought it might be a good idea to include a tab for **unanswered questions**. That way we don't lose them as new questions get asked and I think it could be a good place for people to start contributing. 

This is what it currently looks like at https://publiclab.org/questions:

![screen shot 2016-11-18 at 11 34 18 am](https://cloud.githubusercontent.com/assets/24359/20437747/2720cc82-ad83-11e6-85a1-ce9b10aeddda.png)

## Solution

There are four parts to this:

## 1

We'd need to add a new controller method for `def unanswered`, like this one: https://github.com/publiclab/plots2/blob/master/app/controllers/questions_controller.rb#L44-L57

But where that one `.joins(:answers)`, we'd want to only query for questions which **have no answers** -- so that'd be:

```ruby
@questions.includes(:answers)
                .where( answers: { aid: nil } )
```

## 2

We'd also need to make a new title option like this one, but for "Unanswered questions": https://github.com/publiclab/plots2/blob/master/app/views/questions/index.html.erb#L6

And a new tab for "Unanswered questions": https://github.com/publiclab/plots2/blob/master/app/views/questions/index.html.erb#L40

## 3

We'd need a new route in `config/routes.rb` - a copy of this one but for `unanswered`: https://github.com/publiclab/plots2/blob/master/config/routes.rb#L243

## 4

Finally, we'd want to test the controller action, again, a copy of the one for the `answered` action, but where we also test that the first result `assigns(:questions).first` has `.answers.length == 0`:

https://github.com/publiclab/plots2/blob/master/test/functional/questions_controller_test.rb#L107-L113

**Comment by saakuffo** [comment]
I think I have a handle on this. Incoming PR.

**Comment by jywarren** [comment]
Perfect, thank you so much! 🎉 🎈 👍
