### ISSUE TITLE
addLocation is not defined on profile page location adding modal

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#8061]
On profile pages, removing location tags and re-adding a location using the modal fails, with:

`addLocation() is not defined`

OK, so this used to exist:

https://github.com/publiclab/plots2/pull/1965/files#diff-0e96eb89432977c7610f8598db819f24R17-R22

```html
    <script>
      function addLocation() {
        $('.blurred-location-input').click() ;
      }
    </script>
```

Where'd it go? 

Looks like this commit consolidated some Leaflet code but lost this:

https://github.com/publiclab/plots2/commit/0545b0fa306b4326e5242ec7ae6ac737538b5e9a

let's just not use a separate function but apply the click directly?

**Comment by ebarry** [comment]
Thanks for documenting this! I've noticed this unexpected behavior, but did not know how to articulate it.

**Comment by jywarren** [comment]
Unfortunately `$('.blurred-location-input').click()` doesn't open the modal. Checking how we're supposed to do it now...

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/edit/master/app/views/users/profile.html.erb#L9

**Comment by jywarren** [comment]
OK, i tested again and i believe this works: `$('.blurred-location-input:last').click()`

**Comment by jywarren** [comment]
And opened a PR!
