### ISSUE TITLE
Docker-compose fails to start passenger

### ISSUE THREAD

**Issue by icarito** [publiclab/plots2#8108]
### Please describe the problem (or idea)

Unable to deploy. The web container errors out with:
```
web_1      | /bin/bash: /usr/local/bundle/bin/passenger: No such file or directory  
plots_unstable_web_1 exited with code 127                                           
```
> What did you expect to see that you didn't?

Expected to see passenger start.
I've setup Jenkins in plots/unstable to expose the docker logs, e.g. https://jenkins.laboratoriopublico.org/job/Plots-Unstable/1059/console

Also tried a few different things. The problem appears when invoking rake from the Makefile, docker-compose ps lists: `plots_unstable_web_1       /bin/bash -c sleep 5 && /u ...   Exit 127` for the web entry.

### Please show us where to look

Pushing to unstable will result in an error log (but success status) with current main branch.

**Comment by icarito** [comment]
Note that when I invoke `docker-compose` directly I get passenger without problems:
```
jenkins@tycho:/srv/plots_unstable/plots2$ docker-compose run --rm web bundle exec passenger    
Starting plots_unstable_redis_1 ... done                                                       
Starting plots_unstable_db_1    ... done                                                       
Phusion Passenger Standalone, the easiest way to run web apps.                                 
                                                                                               
Available commands:                                                                            
                                                                                               
  passenger start      Start Phusion Passenger Standalone.                                     
  passenger stop       Stop a Phusion Passenger instance.                                      
  passenger status     Show the status of a running Phusion Passenger instance.                
                                                                                               
Run 'passenger <COMMAND> --help' for more information about each command.                      
jenkins@tycho:/srv/plots_unstable/plots2$                                                      
```

**Comment by Tlazypanda** [comment]
Just sharing some links that might be related :sweat_smile: 
https://stackoverflow.com/questions/3958092/problem-with-bundle
https://github.com/capistrano/passenger/issues/26
https://stackoverflow.com/questions/7071582/no-such-file-to-load-bundler-on-passenger-on-ubuntu
