### ISSUE TITLE
Weekly Community Check-In #66 - Outreachy Mid-term feedback

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#8113]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Outreachy Mid-term feedback

This week marks the mid-point of the Outreachy Timeline. The mid-point feedback form is due for mentors and students on July 10. This is the time to discuss and communicate with mentors if the project now has a different set of goals than before or things turned out to be a bit complicated than before. It's alright to be behind schedule as long as you have been working full time on the project. :raised_hands: 

If you are facing any hardships with your project or feel you might need an extension for completion, get in touch with the mentors :sparkles: Modify your project timeline accordingly and make adjustments :v: 

## To Outreachy and GSoC students
Thanks for all the amazing work you have done so far :tada: So we would like to know what great tasks you plan to take on this week :100: If for any reason you would be away from keyboard , let us know in advance :v: Also sometimes tasks might get a bit overwhelming and we may find ourselves struggling but these are one of the many challenges we face in our lives - Celebrate these challenges, ask for your mentor's advice and maybe blog about it.

Happy Coding :woman_technologist:

## To mentors
Please be on the lookout for concerns/questions and reviews that the interns so that we can keep the programs running smoothly. Thanks :v:

## Reviewers and fellow contributors
We would love your help reviewing the interns PRs as they start coming in and also would appreciate chip-ins on discussions on various issues..Let do what we do best...collaborating :balloon:

### Thank you note to focus issues contributors

Special thanks to @icarito and @alaxalves for their amazing work with the jenkins issue :v:

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** 🎈
Have a great week and year ahead all ❤️

**Comment by Tlazypanda** [comment]
@JapneetSingh5, @Neilblaze, @markkulube, @vinuch, @Tlazypanda, @icarito, @dependabot-preview[bot], @jywarren, @keshavsethi, @praaatik, @Janitham97, @imanishbarnwal, @dburugupalli, @adityakpranav, @ioampatzidis, @esiebomaj, @Alexjake660, @cesswairimu, @urvashigupta7, @daemon1024, @jscastanos @keshavsethi, @jywarren, @AyanChoudhary, @imajit,@NitinBhasneria, @nstjean, @marientje, @rutger-t, @Janet33, @TroydonAnabolic, @priyanshbalyan, @Medlineme4, @mandysGit, @msanden, @AidenOliver, @Janetsomehow, @AntroMarina, @llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-s, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @Tlazypanda,

**Comment by Tlazypanda** [comment]
@keshav234156, @WaldenJosh, @B4Lee, @VisnuGanth, @jessibreen, @alaxalves, @kamal-kaur04, @sssash18, @chinmay021, @Srija616, @AnnaMinakova, @greenbrown, @taysa91, @TaishiRoy, @yagmurbaydogan, @Shulammite-Aso, @Jigyasa-Kumari @moliver4, @justinelai, @Snouzy, @stevenalila, @Digiox, @yandu31, @milosv1, @jamescapps, @Nevenem, @chirag-wadhwa, @yogeshjdeshmukh, @omizrahi99, @theOpetunde, @sailahonkanen, @robin-natale, @avidler, @ccyccyccy
@urvashigupta7, @daemon1024, @Tlazypanda, @jscastanos, @sarthak-choudhary, @dongskyler, @keshavsethi, @Shulammite-Aso, @ckchu8, @keshav234156, @DerekChristy, @Srija616, @priyanka-choubey, @AyanChoudhary, @imajit, @NitinBhasneria, @nstjean, @marientje, @rutger-t,

**Comment by Tlazypanda** [comment]
@Janet33, @TroydonAnabolic, @priyanshbalyan, @Medlineme4, @mandysGit, @msanden, @AidenOliver, @Janetsomehow, @AntroMarina, @llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-s, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @WaldenJosh, @B4Lee, @VisnuGanth, @jessibreen, @alaxalves, @kamal-kaur04 @adityakpranav @esiebomaj @Yonttee @swarajpure @vinuch @ishika1727 @nsachin08 @Rohit-786 @daemon1024

**Comment by alaxalves** [comment]
Heyyy guys, 
This upcoming week I intend to finish Rails 5 PR at Spectral Workbench, remove Bower and configure Yarn for Spectral Workbench and start including Rubocop in Travis builds for Spectral, Exporter gem and Exporter-Sinatra.

**Comment by Tlazypanda** [comment]
Hey everyone :wave: 

Last week I have been stuck on adding alternate_text for images :sweat_smile:  Opened #8112 for discussion on introducing lighthouse ci for performance and accessbility monitoring.

Review required #7996 #7945 #7958 #8087 #8104 :v: 
Thanks :raised_hands:

**Comment by keshavsethi** [comment]
:wave: Hey everyone, 
Last week, I worked on Flag nodes and Flag Comments where any users can flag node or comment and those nodes can be moderated at /spam2/flags and comments at /spam2/comments. This week I am planning to work on comment bulk moderation and its system and functional tests. I will also work on the Queue and the active user page.
Please review PR for Flag nodes and comments  https://github.com/publiclab/plots2/pull/8107 and https://github.com/publiclab/plots2/pull/8107#issuecomment-653942167
Thanks! :v:

**Comment by jywarren** [comment]
Hi all! I am going through all active conversations I can see today, so if you have anything I missed or you are stuck on, please chime in here and ping me on Gitter! 

Very appreciative for all your amazing work. 🎉  Things are going very well, you should all be very pleased!

**Comment by cesswairimu** [comment]
Hello everyone :wave: 
I am a little under the weather this week but I am still available and will be catching up on the reviews and discussions today and tomorrow 
Thanks everyone for the amazing work you are doing  :tada: :tada: and thanks @Tlazypanda for opening the check-in :+1: 
Anyone who would like to open next week's check-in please leave a comment.  Thanks and  great rest of the week :balloon:

**Comment by SidharthBansal** [comment]
Hello all,
Today I got the news that I am branch topper for the Software Engineering branch at Delhi Technological University 2016-2020 batch with 9.43/10 GPA. I am really glad  🙂

**Comment by Tlazypanda** [comment]
@SidharthBansal Congratulations!!! That's amazing :tada: :100: :partying_face:

**Comment by ebarry** [comment]
Congratulations @SidharthBansal ! Great work!!!

**Comment by keshavsethi** [comment]
Congratulations @SidharthBansal !! :tada: :tada: :100:

**Comment by cesswairimu** [comment]
Congrats @SidharthBansal  :tada: :tada: 
Would anyone  like to open this week's check-in?

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/8143. Thanks everyone
