### ISSUE TITLE
Remove unused code from profile method in user_controller

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#8114]
**Please describe the desired behavior.**
User controller profile method has some unused code that can be removed to improve upon server response time on this endpoint.

**Additional context (optional)**
https://github.com/publiclab/plots2/blob/ad1a891697bab762511367f444223c563c2054a3/app/controllers/users_controller.rb#L161

Update: I think code from line 160 to 205 can be carefully removed can you please crosscheck and let me know? Thanks :v:

**Comment by Tlazypanda** [comment]
@jywarren @cesswairimu can you confirm that `@notes` is not used for this view? :sweat_smile:

**Comment by cesswairimu** [comment]
@Tlazypanda I can't see it used anywhere

**Comment by Tlazypanda** [comment]
@cesswairimu Thanks for the review :tada:

**Comment by jywarren** [comment]
And hopefully tests will catch it if you open a PR!
