### ISSUE TITLE
Update blog template to show co-authors

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#8118]
**Please describe the desired behavior.**
@joyofsoy would like to see co-authors displayed on https://publiclab.org/blog. This page has some fancy styling which is nice, and needs a little update to include the newer co-authoring feature on Research Notes. 

**Additional context (optional)**
The original note shows the co-author: 
![screen_shot_2020-07-06_at_10 05 15_am_480](https://user-images.githubusercontent.com/161439/86809481-ee37c780-c049-11ea-8991-22c352c24412.png)

However, the blog only shows the first author: 
![screen_shot_2020-07-06_at_10 03 51_am](https://user-images.githubusercontent.com/161439/86809539-f859c600-c049-11ea-9f15-e64f1d9c65a4.png)

### Thank you!

**Comment by Tlazypanda** [comment]
Hey @ebarry we can probably make an fto out of this as well :sweat_smile: if there is no rush :v:

**Comment by ebarry** [comment]
that would be ideal! thanks for reviewing this!

**Comment by mronauli** [comment]
hi @Tlazypanda @ebarry, first timer here! mind if i work on this issue?

**Comment by Tlazypanda** [comment]
Hey @mronauli Sure go ahead :tada: Just adding here that this issue is an fto-candidate and not an fto (first-timers-only issue) so if you are comfortable with working on this go ahead :100: (in case you face any difficulty with this please feel free to ping :v: )

**Comment by Tlazypanda** [comment]
Just adding more information about the files involved here to be edited -  
https://github.com/publiclab/plots2/blob/94841c82bcbb2b08628743cbdb9dbecdf75b946a/app/views/tag/blog.html.erb#L53 

In this line we need to add coauthors like we have in the file lines 30-34
https://github.com/publiclab/plots2/blob/94841c82bcbb2b08628743cbdb9dbecdf75b946a/app/views/notes/show.html.erb#L31

**Comment by mronauli** [comment]
Thank you @Tlazypanda!
