### ISSUE TITLE
Bold "𝐁" button does not create bold text in Reply To Comment editor

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#8119]
📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I was writing a reply to a comment, and highlighted some of my text, then clicked the "B" icon to make it bold; however, there was no effect from clicking the "𝐁" button. See gif: 
![bold-not-working](https://user-images.githubusercontent.com/161439/84318769-f2e98880-ab3c-11ea-906d-4765eaa7362c.gif)

> What did you expect to see that you didn't?

I expected to see the highlighted text turn **bold**

### Please show us where to look

https://publiclab.org/questions/wangmeising97/06-05-2020/why-we-see-red-image-when-using-blue-filter#c26940

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

liz

Thanks!!!!

**Comment by willkunz13** [comment]
After some testing I think it has to do with all the editor toolbars interacting with a single text area.  So pressing the bold button appears to do nothing, when in fact it is adding four (*) to another text area on the page.  Same goes for italics and any other editor interaction.  I'm trying to find a solution, and any recommendations from someone who has worked on the editor.js would be appreciated.

**Comment by ebarry** [comment]
thank you all!
At this time i believe buttons have been removed from both the *Comment Editor* and the * Reply To Comment Editor*, so perhaps this can be closed until the next round of work on those editors?

**Comment by cesswairimu** [comment]
I see it exists on the questions comments and it is working as expected. Thanks all, closing this
