### ISSUE TITLE
replication templates from [prompt:text] power tag?

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#814]
Note to self (also @ebarry)

![tmp_5683-img_20160913_152431 2-1448108704](https://cloud.githubusercontent.com/assets/24359/18488283/b57f9e40-79c6-11e6-9ffb-f1f743e2e7cf.jpg)

**Comment by jywarren** [comment]
Just an idea

**Comment by mathewlippincott** [comment]
This would be very helpful for standardized field reports or data reports.  

I could create a template for a flight report, for instance.  when someone goes to replicate a flight with a piece of equipment, they could be prompted for standard categories such as:

Weather
Date
Location
Kite
other equipment
payload
notes and observations

I imagine this would give us a start towards @gretchengehrke's request for data comparison.  A labeled category in tagged notes could be automatically transcluded into a data table.

**Comment by jywarren** [comment]
Noting input from @ebarry in #2052:

> This is an opportunity to allow people who are writing activities, especially teacher types, to customize the template that appears in the research note after clicking the "I did this" button.

**Comment by ebarry** [comment]
Great, this is exactly what i was getting at in #2052. 
The person writing the activity is in a good position to write a helpful response template. How can we help them do this?

I'm also interested in the "save progress" moments sketched above.

**Comment by jywarren** [comment]
OK, so a minimal version of this is that you can now set a comment template using the tag: `comment-template:______` where `_____` is the name (slug) of a wiki page. We will be expanding this for image upload and other things soon!

**Comment by jywarren** [comment]
Adding a menu option to explain how this works here: https://github.com/publiclab/plots2/issues/3923

**Comment by jywarren** [comment]
This will link to this explanatory page: https://publiclab.org/comment-templates

**Comment by jywarren** [comment]
We now have templates in comments and notes!
