### ISSUE TITLE
Weekly Community Check-In #67 Books/Podcasts/Movies that you draw Inspiration from

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#8143]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Books/Podcasts/Movies that you draw Inspiration from - 
Share your favourite books/podcasts/movies that you draw inspiration from :heart: When the going gets tough remembering these inspirational ideas/moments really dawns on you and motivates you to push the wall further :100: 

Simple concepts of life that we take away from these sources that really change the way we look at life and the world around us. Hopefully we will also get the chance to draw inspiration from this :v: 

## For the Interns
If you are blocked on something, please leave a comment and we will be sure to help. For the interns if you have any blogs please leave a link below and we will check them out.

## For the mentors 
Please be on the lookout for concerns/questions and reviews that the interns so that we can keep the programs running smoothly. Thanks :v: 

## For this topic
Let's invite the community of Publiclab outside of the dev side to share their best books/podcasts/movies!! :raised_hands: 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** 🎈
Have a great week and year ahead all ❤️

**Comment by cesswairimu** [comment]
@JapneetSingh5, @Neilblaze, @markkulube, @vinuch, @Tlazypanda, @icarito, @dependabot-preview[bot], @jywarren, @keshavsethi, @praaatik, @Janitham97, @imanishbarnwal, @dburugupalli, @adityakpranav, @ioampatzidis, @esiebomaj, @Alexjake660, @cesswairimu, @urvashigupta7, @daemon1024, @jscastanos @keshavsethi, @jywarren, @AyanChoudhary, @imajit,@NitinBhasneria, @nstjean, @marientje, @rutger-t, @Janet33, @TroydonAnabolic, @priyanshbalyan, @Medlineme4, @mandysGit, @msanden, @AidenOliver, @Janetsomehow, @AntroMarina, @llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-s, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @Tlazypanda,

**Comment by cesswairimu** [comment]
@keshav234156, @WaldenJosh, @B4Lee, @VisnuGanth, @jessibreen, @alaxalves, @kamal-kaur04, @sssash18, @chinmay021, @Srija616, @AnnaMinakova, @greenbrown, @taysa91, @TaishiRoy, @yagmurbaydogan, @Shulammite-Aso, @Jigyasa-Kumari @moliver4, @justinelai, @Snouzy, @stevenalila, @Digiox, @yandu31, @milosv1, @jamescapps, @Nevenem, @chirag-wadhwa, @yogeshjdeshmukh, @omizrahi99, @theOpetunde, @sailahonkanen, @robin-natale, @avidler, @ccyccyccy
@urvashigupta7, @daemon1024, @Tlazypanda, @jscastanos, @sarthak-choudhary, @dongskyler, @keshavsethi, @Shulammite-Aso, @ckchu8, @keshav234156, @DerekChristy, @Srija616, @priyanka-choubey, @AyanChoudhary, @imajit, @NitinBhasneria, @nstjean, @marientje, @rutger-t,

**Comment by cesswairimu** [comment]
@Janet33, @TroydonAnabolic, @priyanshbalyan, @Medlineme4, @mandysGit, @msanden, @AidenOliver, @Janetsomehow, @AntroMarina, @llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-s, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @WaldenJosh, @B4Lee, @VisnuGanth, @jessibreen, @alaxalves, @kamal-kaur04 @adityakpranav @esiebomaj @Yonttee @swarajpure @vinuch @ishika1727 @nsachin08 @Rohit-786 @daemon1024

**Comment by cesswairimu** [comment]
@NitinBhasneria , @Shulammite-Aso @keshav234156 @shreyaa-s or @shreyaa-sharmaa  how are you doing? Noticed you didn't check-in last week...wanted to check how you are fairing on

**Comment by jywarren** [comment]
Hi all! I wanted to shout out to the Editor team @NitinBhasneria @Shulammite-Aso @keshav234156 @shreyaa-sharmaa about their new release `v2.1.0` at https://github.com/publiclab/PublicLab.Editor/pull/555 - great work! They're now organizing a follow-up bugfix release `v2.1.1` at https://github.com/publiclab/PublicLab.Editor/pull/557. Love to hear some updates on that, folks! ❤️ 🎉 🙌

**Comment by Sagarpreet** [comment]
Hi @all, 
Thanks for the checkin @cesswairimu , i hope everyone is safe and sound here :)
I was watching pursuit of happiness movie the other day, very inspiring! 
Also i can open the checkin next week 👍 
Thanks!

**Comment by jywarren** [comment]
It's not a movie but I just watched Season 2 of the new Twilight Zone by Jordan Peele and it was really great 😱 

Was it inspiring? I guess an inspiring work of filmmaking, so in that sense yes! Inspiring me to work to prevent the dystopias shown in the episodes, maybe. 💯

**Comment by Tlazypanda** [comment]
@sagarpreet-chadha Pursuit of happiness is my fav too!!! :heart: 

Some more favs- 
-  Life is beautiful ( i cried so hard please watch this)
- A beautiful mind
- Into the wild
- Front of the class
- Moneyball

@icarito @ebarry @skilfullycurled would love to hear yours and other publiclab community members answers :sweat_smile: if you don't mind tagging them here :sweat_smile: 

So this week I spent most of the time on working on the printability side of my proposal :v: #8128 Thanks!!

**Comment by keshavsethi** [comment]
Hey Everyone  :wave: Hope you all are safe :heart: 
Forest Gump (best feel-good movie) and Tare Zameen Par are some of my favorites and very inspiring movies 

**Last Week:**
- Finished Flag nodes and comments #8107 
- Worked on system and functional tests for flag feature 
- Updated Dashboard and Digest UI #8130
- Resolved issues in Pagination, alerts and filters.

**Week Ahead:**
- Bulk moderation of comments and its tests 
- Work on active user moderation and its tests
- Work on Queue and its tests
- Documenting features of Dashboard

Thanks!!

**Comment by jywarren** [comment]
Cheering for @mronauli who just solved this issue about co-authors on the blog template: https://github.com/publiclab/plots2/pull/8137

And for @Tlazypanda for finding the lines of code that had to change to make @mronauli's work smoother: https://github.com/publiclab/plots2/issues/8118

And to @ebarry for writing a very clear and well-documented initial issue: https://github.com/publiclab/plots2/issues/8118

Great collab, folks! 🎉 💯 👏 👏 👏 👏 👏

**Comment by ebarry** [comment]
Hello all, checking in with an appreciation for @emilyashley who has been a wonderful part of PublicLab for the last 6 months. As of last week, she's moved on from her role on staff at the organization, but we truly look forward to seeing her around Github and of course, New Orleans ⚜️. Thank you @emilyashley !!!!!! 🌟👩‍💻🦄🐊🌈

**Comment by skilfullycurled** [comment]
@sagarpreet-chadha, thank you!  That's so funny, just yesterday I was writing about Public Lab in a "What are your qualifications box." for a course I'd like to TA in (Social Informatics) and I thought, "You know, I should really bother those folks about embedding #5627 in the boilerplate at the top of the community check in so I'll get reminders about them!"

Anyway...



Two movies that I draw inspiration from in particular: 

1) [I :heart: Huckabees](https://www.youtube.com/watch?v=2eOLOmCjRPY).  The main character is an environmental activist and the movie opens with him [reciting a poem](https://www.youtube.com/watch?v=_i8-t5biK10) in honor of a large rock his organization was able to save from development. 😆 

2) [Contact](https://www.youtube.com/watch?v=Q399v-pMG30)  Based on a book by Carl Sagan and Ann Druyan directed by Robert Zemeckis of Forest Gump fame (I'm looking at you @keshavsethi) about a scientist at SETI (loosely based on [Jill Tarter ](https://en.wikipedia.org/wiki/Jill_Tarter)) who discovers an extraterrestrial message.  

These aren't books or podcasts per se but the audio recordings of lectures delivered by two people who write books and have podcasts dedicated to them:  Ram Dass and Alan Watts.  Trey Parker and Matt Stone of South Park did a [series of six ~2 minute animations](https://www.youtube.com/watch?v=VvrfnE7Q-0w) of talks by Alan Watts which I highly recommend.

PS: @Tlazypanda if you haven't seen the moment that [Roberto Benigni accepted the Oscar for Best Foreign Film](https://www.youtube.com/watch?v=8cTR6fk8frs), it's almost as good as the movie.

**Comment by shreyaa-sharmaa** [comment]
Hey, hope everyone is doing well!
That's a lot of movies to add to my watchlist :smile: 
One of the most inspirational movies for me was: **Dead Poets Society** _`Carpe diem. Seize the day, boys. Make your lives extraordinary`_ :heart: 
After the new release of Editor, most of my time has gone in tracking down the bugs for Editor's integration in plots2 (no success so far), smoothening out tests in Editor and trying to understand why they fail for some PRs as well as defining tests for woofmark.

**Comment by gr455** [comment]
Hi everyone! hope everyone is doing well.
I have been busy for the last couple weeks studying for my finals but we just got a mail yesterday stating that they're cancelled. So now I'm spending my free time learning JavaScript.

I don't really watch too many movies or listen to podcasts but listening to Elon Musk talk is always inspirational :)

**Comment by ebarry** [comment]
Hi everyone, 
Also not a movie but something i was watching recently is an animated series on Netflix called "Kipo and the Age of Wonderbeasts" https://en.wikipedia.org/wiki/Kipo_and_the_Age_of_Wonderbeasts plus it has a great soundtrack
For grappling with the issues of our time, i was truly moved by Bayo Akomolafe on https://podcasts.apple.com/us/podcast/for-the-wild/id942809988?i=1000463389031

**Comment by cesswairimu** [comment]
Hi all :wave: 
I am a huge podcast listener and I will try to just give a few :smile: [Greater than code](https://www.greaterthancode.com/), [My Ruby Story](https://devchat.tv/podcasts/my-ruby-story/), [Legally Clueless](https://linktr.ee/legallyclueless) and [Lets break good](https://www.letsbreakgood.com/) and are my top 4
Thanks @Tlazypanda  for the topic update :heart: 

Great rest of week everyone...

**Comment by cesswairimu** [comment]
Anyone up for opening this week's check-in?

**Comment by Tlazypanda** [comment]
@cesswairimu  🙌 I will take it up tomorrow if that's alright 😅

**Comment by cesswairimu** [comment]
sure its cool..thanks @Tlazypanda for always coming through :heart:

**Comment by jywarren** [comment]
Closing this one up! Thanks!
