### ISSUE TITLE
Center the project images on the Home page

### ISSUE THREAD

**Issue by HashTalmiz** [publiclab/plots2#8155]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

_This is a simple UI fix that could help someone get started with contributing anywhere!_ 
**_Just center the project images on the home page to make it look better!_**

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [home.html.erb](https://github.com/publiclab/plots2/blob/main/app/views/home/home.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" which lines to add **under the styles tag** :

```
.project-image {
        text-align: center;
}
```
_This should center the project **Images**, yes you read it right, **Images**. Try it out for yourself in the browser's inspector if you wish to see it work first!_

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by HashTalmiz** [comment]
![fixneeded](https://user-images.githubusercontent.com/55018280/87773600-045f3800-c841-11ea-915f-95a84b205542.png)
This is the current view of the image. Align the image to the center and share a screenshot of the changes seen on the home page.

**Comment by ARobinson26** [comment]
Hi there,
I've never contributed to open source before and would love to give this a go if it's still available?

**Comment by N0v0cain3** [comment]
Is it still available?

**Comment by HashTalmiz** [comment]
Hey @ARobinson26, You can go ahead with this. 
Sorry @N0v0cain3 this is a `first-timers-only` issue.

**Comment by thejasvi-ks** [comment]
Hi everyone, I have never contributed to anything before too. I would like to give it a try if it's available.

**Comment by galanggg** [comment]
Hey @HashTalmiz can i make pull request to this issues ?

**Comment by HashTalmiz** [comment]
@cesswairimu @jywarren Have a look at #8169.

**Comment by jywarren** [comment]
Thanks, all! @cesswairimu thank you for your caution - this kind of design change is usually something we're pretty cautious about - both because it's a high-visibility page, and because we try to seek some broad consensus on design changes before starting a PR on it. 

But, in this case @HashTalmiz is completely correct and the centering looks great! 🎉 

Thanks to @HashTalmiz @cesswairimu @sagarpreet-chadha and especially @galanggg for identifying, solving, and reviewing this one! 👍  Great teamwork! 💯

**Comment by jywarren** [comment]
And thanks to @ARobinson26 and @N0v0cain3 for your offer to help! We'd love your help on another one. One thing is to look through old first-timers-only issues as there are some where people are stuck and need help, or just aren't available anymore! Feel welcome to be friendly and pitch in! 🎉
