### ISSUE TITLE
some wiki page revisions tab links go to wrong URL

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#816]
### What happened just before the problem occurred

I clicked Revisions on a wiki page: https://publiclab.org/lists

And got this, with a red warning box that says it has no revisions: https://publiclab.org/wiki/revisions/mailing-lists

This also happened on https://publiclab.org/wiki/ndvi

The code for this button is here: https://github.com/publiclab/plots2/blob/master/app/views/wiki/show.html.erb#L29

and here: https://github.com/publiclab/plots2/blob/master/app/views/wiki/show.html.erb#L48

The issue is probably that we're using `slug` -- but should be using a subset of `node.path` -- like `node.path.split('/').last` since the `friendly_id` revamp changed this property.

**Comment by pdhixenbaugh** [comment]
Manually editing the URL sometimes gets you to the revision page, e.g. https://publiclab.org/wiki/revisions/riffle/ however clicking on past revisions shows the current revision instead... e.g. https://publiclab.org/wiki/revisions/riffle/17279 (It should be the very first revision)

**Comment by jywarren** [comment]
I've revised #736 to cover these issues, and also did some migrations in #1003 which may resolve at least the riffle page. Thanks!
