### ISSUE TITLE
Alert boxes push down tag page image headings 

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#8167]
When on pages like https://publiclab.org/tag/water-quality, if there is an alert box such as logging out, it pushes down the lead image. Haven't captured it but it's in this view:

![Screenshot_20200718-075953](https://user-images.githubusercontent.com/24359/87852071-f7882600-c8cc-11ea-828e-a4828141331a.png)

Should be easy to make them float!

**Comment by AntonioFry** [comment]
@jywarren I'd be happy to help anyway I can. Do you know anyway to get the alert boxes to pop up so can try recreating the bug?

**Comment by AntonioFry** [comment]
@jywarren So I found the problem and tried changing the positioning to absolute of the alert as well as the z-index to 1. Here's the result:

![Changes](https://i.imgur.com/Bf24JR2.png)

I'm not exactly sure where to find to HTML code for this in the repo to change it, but tell me what you think of the changes.

**Comment by jywarren** [comment]
I think this would be great. I think it ought to apply to the `.alerts-container` class, but only on this page -- could we do it as inline CSS? Because in other contexts, it seems it ought to display as it had before. 

```css
    position: absolute;
    z-index: 999;
    width: 100%;
    left: 0;
    padding: 0 20px;
```

these seem pretty good!

Would you like to try inserting it in this inline style block?

https://github.com/publiclab/plots2/blob/122e8a73b440bb752f080375aad3f24a02b7c8f9/app/views/tag/show.html.erb#L7-L14

If so, we'd love to see a PR, just be sure to link to it from here! Thank you so much!

**Comment by jywarren** [comment]
And, what I did was, log in from that page, and you get directed back with the alert showing! It then hides itself, but you can use the inspector to delete `display:none` if you want to try working on it more. Thank you!!!

**Comment by avats-dev** [comment]
### Hey @jywarren , this looks stale, can I work on this?
> I think I have to add `.alerts-container` in **style** block and insert the css, right?

**Comment by jywarren** [comment]
Yes, that would be great, thank you @avats-dev -- and if @AntonioFry finds more time I'm happy to help find a new issue for you too!
