### ISSUE TITLE
moderated wiki revisions appear in Wiki dashboard sidebar

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#817]
### What happened just before the problem occurred

Wiki edits by `mariakatosvich` which I spammed still appear in the sidebar of the dashboard at https://publiclab.org/dashboard (https://publiclab.org/research if not logged in). 

These are generated by this query: https://github.com/publiclab/plots2/blob/master/app/controllers/home_controller.rb#L77

Notice on line 80, we specify `node.status = 1` -- but we don't specify `node_revisions.status = 1`, which we need to add as well. 

It would also be great to verify this with a test -- including a test fixture for a moderated spam node revision in this file: https://github.com/publiclab/plots2/blob/master/test/fixtures/node_revisions.yml#L49

which would have `status: 0` -- and a test in this file to check if it appears in the dashboard results: https://github.com/publiclab/plots2/blob/master/test/functional/home_controller_test.rb

**Comment by rafael-acerqueira** [comment]
Hi ! I have a doubt here. Should I test if moderated_spam appear in dashboard results? But if it's moderated it doesn't appear in dashboard, right ? It status is 0.

**Comment by jywarren** [comment]
That's right, thanks! Status 0 should not appear.

**Comment by rafael-acerqueira** [comment]
Ok. I'm new in tests, sorry about this. The ideia here is I have to check if unmoderated_spam_revision appear on the dashboard. But the instance variable that is used in the view contains wikis and revisions:
https://github.com/publiclab/plots2/blob/master/app/controllers/home_controller.rb#L86

So, I'm having difficult in doing this test. I know that I need create a list of revisions with status 1 plus a list of wiki and show it in the dashboard.

Can you give me some tip ?

**Comment by jywarren** [comment]
Could you iterate through the list in the instance variable, and do a two
part conditional on each item that asserts that a) if it's a revision, then
b) it's status is 1?

**Comment by jywarren** [comment]
Hi, just checking if you needed any additional help with this one -- please feel free to submit a PR with "in-progress" as well if you'd like to share your code so far. My thought was something like:

```ruby
@wikis.each do |obj|
  if obj.class == DrupalNodeRevision && obj.status == 1
    assert_select "something here" # match that it's displayed
  elsif obj.class == DrupalNodeRevision && obj.status != 1
    assert_select false, "something here" # match that it's NOT displayed
  end
end
```

**Comment by rafael-acerqueira** [comment]
I have this:
<pre>
    @wikis = DrupalNode.where(type: 'page')
    revisions = DrupalNodeRevision.joins(:drupal_node)                                
                                .where('type = (?)', 'page')                                
                                .where('node_revisions.status = 1')
    @wikis = @wikis + revisions </pre>

If the first conditional is true, I would have assert_select (".wiki"). In the second conditional I didn't understand why use "false" parameter in the first argument. If I do something like this: assert_select( ".wiki", false). It's is true only if I don't have any ".wiki". I'm not sure if It's right.

**Comment by jywarren** [comment]
oh -- i may have just written the false argument in the wrong place. Thanks for fixing it -- this looks good!

**Comment by rafael-acerqueira** [comment]
Please check my pull request #883

**Comment by jywarren** [comment]
Merged, thanks!!
