### ISSUE TITLE
'Follow' pop up menu overlaps with navigation bar

### ISSUE THREAD

**Issue by AntonioFry** [publiclab/plots2#8171]
When clicking on the arrow next to the 'Follow' button a menu appears. When scrolling down while this menu opens, it ends up overlapping with the navigational bar.

Image of bug:

![Pop up menu overlapping with nav bar](https://i.imgur.com/QfLOBon.png)

Link to page with bug: https://publiclab.org/tag/water-quality?_=1595188617

I came across the bug while using Google Chrome. Mentioning just in case the issue is browser specific.

A possible fix is to try changing the element z-index to 0.

**Comment by ebarry** [comment]
wow good catch! Thanks for reporting @AntonioFry !

**Comment by urvashigupta7** [comment]
Hi.. I would like to work on this :)

**Comment by cesswairimu** [comment]
Hi @urvashigupta7, we would love your help. Go ahead. Thanks
