### ISSUE TITLE
Weekly Community Check-In #68 - Share new and exciting technologies/tools 

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#8172]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Share new and exciting technologies/tools 

Hey everyone :wave: This week you are encouraged to share any new and exciting technologies/tools that you are working on that you would recommend to other Public Lab folks to try out. It can be language frameworks or tools or literally any new feature that is fun and has helped boost productivity :raised_hands: 

### Thank you note to focus issues contributors

A huge thank you to @icarito for setting up Google Cloud sql with emoji support :100: @jywarren and @keshavsethi for their work on setting up Gitpod :tada: 

## For the Interns
If you are blocked on something, please leave a comment and we will be sure to help. For the interns if you have any blogs please leave a link below and we will check them out.

## For the mentors
Please be on the lookout for concerns/questions and reviews that the interns so that we can keep the programs running smoothly. Thanks :v: 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** 🎈
Have a great week and year ahead all ❤️

**Comment by Tlazypanda** [comment]
@JapneetSingh5, @Neilblaze, @markkulube, @vinuch, @Tlazypanda, @icarito, @dependabot-preview[bot], @jywarren, @keshavsethi, @praaatik, @Janitham97, @imanishbarnwal, @dburugupalli, @adityakpranav, @ioampatzidis, @esiebomaj, @Alexjake660, @cesswairimu, @urvashigupta7, @daemon1024, @jscastanos @keshavsethi, @jywarren, @AyanChoudhary, @imajit,@NitinBhasneria, @nstjean, @marientje, @rutger-t, @Janet33, @TroydonAnabolic, @priyanshbalyan, @Medlineme4, @mandysGit, @msanden, @AidenOliver, @Janetsomehow, @AntroMarina, @llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-s, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @Tlazypanda,

**Comment by Tlazypanda** [comment]
@keshav234156, @WaldenJosh, @B4Lee, @VisnuGanth, @jessibreen, @alaxalves, @kamal-kaur04, @sssash18, @chinmay021, @Srija616, @AnnaMinakova, @greenbrown, @taysa91, @TaishiRoy, @yagmurbaydogan, @Shulammite-Aso, @Jigyasa-Kumari @moliver4, @justinelai, @Snouzy, @stevenalila, @Digiox, @yandu31, @milosv1, @jamescapps, @Nevenem, @chirag-wadhwa, @yogeshjdeshmukh, @omizrahi99, @theOpetunde, @sailahonkanen, @robin-natale, @avidler, @ccyccyccy
@urvashigupta7, @daemon1024, @Tlazypanda, @jscastanos, @sarthak-choudhary, @dongskyler, @keshavsethi, @Shulammite-Aso, @ckchu8, @keshav234156, @DerekChristy, @Srija616, @priyanka-choubey, @AyanChoudhary, @imajit, @NitinBhasneria, @nstjean, @marientje, @rutger-t,

**Comment by Tlazypanda** [comment]
@Janet33, @TroydonAnabolic, @priyanshbalyan, @Medlineme4, @mandysGit, @msanden, @AidenOliver, @Janetsomehow, @AntroMarina, @llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-s, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @WaldenJosh, @B4Lee, @VisnuGanth, @jessibreen, @alaxalves, @kamal-kaur04 @adityakpranav @esiebomaj @Yonttee @swarajpure @vinuch @ishika1727 @nsachin08 @Rohit-786 @daemon1024

**Comment by sagarpreet-chadha** [comment]
Hi all,
I am working on a personal nodejs project, where i am using Sequelize to connect to mysql DB, also using typescript instead of javascript...a lot of boilerplate to write to support TS but it is fun!!!

Also i will open the check-in next week, if no one volunteers 🎉 
Thanks!

**Comment by jywarren** [comment]
Hi all! I wanted to echo @Tlazypanda  to celebrate @icarito this week because he's worked for a LONG time to re-encode and rebuild our database to ensure that both non-latin Unicode characters (도토리묵 😛 ) and Emoji 🎉 💯  work on our website. They now do -- give it a spin! 

As to new exciting tools, obviously you've seen me get excited about GitPod over the past few weeks. 😄 

I'm excited not only because it eases reviewing PRs, but also because I think it could be a great way for people to start contributing, meaning you can with one click open up a working version of the site, and not need to do all the installation steps! If it works well for folks, I'd like to suggest we adopt it as our "default" installation method for new contributors and highlight it:

1. in the README
2. in our installation issue: https://github.com/publiclab/plots2/issues/3840
3. replacing / sidestepping #6774 and our old Cloud9 install process
4. maybe even in our first-timers-only templates!

What do you all think?

**Comment by Tlazypanda** [comment]
Hey @jywarren I think that's a superb idea :heart: since it can really take away some of the heavy lifting for new contributors and make the process fairly easy for them :tada: 

@sagarpreet-chadha I also want to try typescript :smile: 

While I haven't been able to do much  learning lately I have my eyes set on learning some functional programming (hope i don't procrastinate on this one :p) 

This week I worked on some performance improvements, fixing travis tests and some work on the printing part of my proposal. 
Needs review: -
https://github.com/publiclab/plots2/pull/8159 https://github.com/publiclab/plots2/pull/7996 https://github.com/publiclab/plots2/pull/7958 https://github.com/publiclab/plots2/pull/7945

Also please help me with inputs on https://github.com/publiclab/plots2/issues/8128 @jywarren @ebarry since I am not sure how to proceed further with this :sweat_smile: :disappointed_relieved:

**Comment by cesswairimu** [comment]
Hi everyone :wave: 

I am currently learning elixir for a microservice I am suppose to rewrite in elixir.
Great week ahead  :balloon:

**Comment by cesswairimu** [comment]
Hi everyone,
@keshavsethi and I have been trying to solve the recent travis failures over the weekend on https://github.com/publiclab/plots2/pull/8186...no luck yet..any ideas are welcome...seems like the travis-ci changed the chrome version or smth so the driver install is failing...the error is 
```
Minitest::UnexpectedError:         Selenium::WebDriver::Error::SessionNotCreatedError: session not created: Chrome version must be between 70 and 73
          (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Linux 4.15.0-1077-gcp x86_64)
```

also @sagarpreet-chadha no one claimed this week's check-in so its all yours. Thanks

**Comment by sagarpreet-chadha** [comment]
Hi @cesswairimu , I will try to search for this 😄 
Okay thanks, i will the make the check-in tomorrow morning IST 💯

**Comment by sagarpreet-chadha** [comment]
New check-in opened in PL editor https://github.com/publiclab/PublicLab.Editor/issues/578
