### ISSUE TITLE
Moderating a wiki revision needs cache flush in URL

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#818]
### What happened just before the problem occurred

After marking a wiki revision as spam (on a page [like this](https://publiclab.org/wiki/revisions/london-uk)), the revisions page doesn't show the new content; we should redirect back to the revisions page, not the dashboard, and append `'?_=' + Time.now.to_i.to_s` so the browser cache flushes. 

The code for this redirect is here: https://github.com/publiclab/plots2/blob/master/app/controllers/admin_controller.rb#L143-L146

See an example of cache flushing of this sort here: https://github.com/publiclab/plots2/blob/master/app/controllers/admin_controller.rb#L16

**Comment by sandyvern** [comment]
Hi! I would like to give this a shot, please.

**Comment by jywarren** [comment]
That would be super. Thanks a lot -- and please note -- apologies, but I'm currently in a staff retreat and am a bit slower at responding this week.

**Comment by sandyvern** [comment]
Awesome...I will get to work then! And yay for staff retreats! Enjoy!

**Comment by sandyvern** [comment]
Hi Jeff!  Trying to work on this and running into a little bit of trouble when trying to rebase (following the new directions you sent this morning)...

> To get the latest version of the master branch, so you can build your changes on this newer, easier version, follow these steps:
> 
> git add and git commit your current work in your named feature branch (that's not master)
> git checkout master - switch to your local copy of the master branch
> git pull https://github.com/publiclab/plots2.git master - get the new version into your local master branch
> git checkout feature-branch - switch back to your feature branch, here named feature-branch as an example
> git rebase master - detach your changes from the older master branch history, and replay (or 'rebase') them so they're relative to the new master branch

Inserting error from trying to rebase below:

`sandyvern:~/workspace/plots2 (moderating-a-wiki-revision) $ git rebase master
First, rewinding head to replay your work on top of it...
Applying: changed span to link & changed to answer.id
Using index info to reconstruct a base tree...
M       app/views/questions/_answer.html.erb
Falling back to patching base and 3-way merge...
Auto-merging app/views/questions/_answer.html.erb
CONFLICT (content): Merge conflict in app/views/questions/_answer.html.erb
error: Failed to merge in the changes.
Patch failed at 0001 changed span to link & changed to answer.id
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

sandyvern:~/workspace/plots2 (moderating-a-wiki-revision|REBASE 1/3) $ git rebase --abort
sandyvern:~/workspace/plots2 (moderating-a-wiki-revision) $ git status
On branch moderating-a-wiki-revision
nothing to commit, working tree clean`

**Comment by jywarren** [comment]
Ah, ok - so now it says there's a conflict in:

CONFLICT (content): Merge conflict in app/views/questions/_answer.html.erb

So if you go in that file, you can choose the versions of each conflicting
line you want to keep. I think it'd be helpful to find a quick tutorial on
resolving conflicts in git rebases... once you do that, you can "git rebase
--continue" and it should complete.

On Oct 5, 2016 8:49 AM, "Sandy" <notifications@github.com> wrote:

Hi Jeff! Trying to work on this and running into a little bit of trouble
when trying to rebase (following the new directions you sent this
morning)...

To get the latest version of the master branch, so you can build your
changes on this newer, easier version, follow these steps:

git add and git commit your current work in your named feature branch
(that's not master)
git checkout master - switch to your local copy of the master branch
git pull https://github.com/publiclab/plots2.git master - get the new
version into your local master branch
git checkout feature-branch - switch back to your feature branch, here
named feature-branch as an example
git rebase master - detach your changes from the older master branch
history, and replay (or 'rebase') them so they're relative to the new
master branch

Inserting error from trying to rebase below:

`sandyvern:~/workspace/plots2 (moderating-a-wiki-revision) $ git rebase
master
First, rewinding head to replay your work on top of it...
Applying: changed span to link & changed to answer.id
Using index info to reconstruct a base tree...
M app/views/questions/_answer.html.erb
Falling back to patching base and 3-way merge...
Auto-merging app/views/questions/_answer.html.erb
CONFLICT (content): Merge conflict in app/views/questions/_answer.html.erb
error: Failed to merge in the changes.
Patch failed at 0001 changed span to link & changed to answer.id
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase
--abort".

sandyvern:~/workspace/plots2 (moderating-a-wiki-revision|REBASE 1/3) $ git
rebase --abort
sandyvern:~/workspace/plots2 (moderating-a-wiki-revision) $ git status
On branch moderating-a-wiki-revision
nothing to commit, working tree clean`

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/818#issuecomment-251715312>,
or mute
the thread

**Comment by jywarren** [comment]
Here's a good guide!
https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/

**Comment by jywarren** [comment]
Back from staff retreat and hopefully can chip in more here; please ping me if you get stuck! -- thanks!

**Comment by sandyvern** [comment]
Sorry for the delay....had some technical difficulties just with gh...but just submitted pr.
