### ISSUE TITLE
Eliminate n+1 query for user.tagnames

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#8189]
**Please describe the desired behavior.**
Wherever we are calling the function `user.tagnames`, the users don't include/eager-load the tag model which leads to n+1 queries.
Example: - `list.html.erb` line 70 (user.tags function is called which in turn calls the user.tagnames function)
Triggered from `user.rb` line line 161 method- `tagnames`
Can check this on /people route

**Additional context (optional)**
Feel free to include any applicable: code, screenshots, or gifs.

**Comment by sagarpreet-chadha** [comment]
Hi @Tlazypanda ,
So eager loading this query, we will make 1 huge query instead of n queries, is it?

**Comment by Tlazypanda** [comment]
Yeah :sweat_smile: but I am not sure if the code is right for this because it's not making much of a difference on my local setup so am not able to monitor
