### ISSUE TITLE
Remove Less and less-rails gems, including the-ruby-racer and v8?

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#8199]
Do we use Less? It requires v8 and the-ruby-racer, which are pretty heavy. 

https://github.com/publiclab/plots2/tree/main/app/assets/stylesheets doesn't have any .less files

https://github.com/publiclab/plots2/tree/main/app/assets/less hasn't changed in 6 years and i think we don't use lightbox anymore. Shall we just remove it and get both `the-ruby-racer` and `less` out of our Gemfile?

**Comment by jywarren** [comment]
https://github.com/metaskills/less-rails

**Comment by avats-dev** [comment]
Is this confirmed, or triage is needed yet?

**Comment by avats-dev** [comment]
@jywarren any updates?

**Comment by jywarren** [comment]
Hi @jywarren i'm so sorry! Yes, this is confirmed, we'd love help with it! My apologies for slow reply. If you can't get a hold of me it may be easier in the chatroom https://gitter.im/publiclab/publiclab (due to volume of notifications). Apologies!

**Comment by Manasa2850** [comment]
@jywarren I would like to work on this
