### ISSUE TITLE
Error in accessing `/dashboard`

### ISSUE THREAD

**Issue by shreyaa-sharmaa** [publiclab/plots2#8202]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?  

I can't access the `/dashboard`. 
After running `passenger start`, I landed up on the home page. Logging in leads to this error and refreshing the page doesn't work. I can access other pages by typing the address, they work fine.

> What did you expect to see that you didn't?  

![Screenshot from 2020-07-30 13-47-59](https://user-images.githubusercontent.com/66686803/88899644-eeec0400-d26b-11ea-9794-762542b5c23a.png)

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by keshavsethi** [comment]
@shreyaa-s @jywarren It will be solved in https://github.com/publiclab/plots2/pull/8186
