### ISSUE TITLE
Align body placeholder on /post

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#8225]
We added a placeholder on the body text field on #8180 
The placeholder looks great locally put it a little outside the text-area on stable  https://stable.publiclab.org/post

The file is  https://github.com/publiclab/plots2/blob/main/app/views/editor/rich.html.erb

![Screenshot from 2020-08-01 20-12-56](https://user-images.githubusercontent.com/17081074/89106764-3bcf0680-d435-11ea-8736-d73b4d8ba176.png)

----
We can use unstable to test this since locally everything looks fine

**Comment by galanggg** [comment]
Hello @cesswairimu is it look good to you? let me know thanks
![Screenshot from 2020-08-02 19-42-32](https://user-images.githubusercontent.com/21099312/89122278-941b0c80-d4f8-11ea-8294-25d0d6fc003b.png)

**Comment by cesswairimu** [comment]
@galanggg ,..yeah it looks great...we need to make sure it looks the same here https://stable.publiclab.org/post though

**Comment by arteevraina** [comment]
@galanggg Are you still working on this issue? If not, Can I work on this one?

**Comment by avats-dev** [comment]
@cesswairimu when I was trying to solve #8319 , I saw that in https://github.com/publiclab/plots2/blob/c55e1ff6983041e197c9a4e168f107c78688cbaf/app/views/editor/rich.html.erb#L367-L370
, changing line 368 as 

**`$('.ple-errors .alert').append('<p><b>'  '</b> </p>');`**

gives following layout to the editor, which is quite good.

---
![editor-new](https://user-images.githubusercontent.com/35889327/93720486-edbdc000-fba6-11ea-825c-a88e4614c835.gif)

---

But, **publish** button becomes inactive. 
> I don't know exactly why this happened but editor looks kinda nice here :smile: .

**Comment by cesswairimu** [comment]
Wow that sure does look good...the Publish button is usually deactivated untill you enter the title and body part..is it activated after that?

**Comment by avats-dev** [comment]
@cesswairimu publish is inactive even after I type smth on body with a title.

**Comment by cesswairimu** [comment]
:thinking:

**Comment by jywarren** [comment]
Hi @avats-dev can you open up a PR with your code and we can try it out in GitPod to see what's up? Thanks!!

**Comment by avats-dev** [comment]
sure!

**Comment by gauravahlawat81** [comment]
@jywarren Any updates on this ? The placeholder is aligned but publish button is still disabled. I checked it at [https://stable.publiclab.org/post](url) ,[https://publiclab.org/post](url) and in my development mode too. Any idea how it can be solved ? Thanks.

**Comment by TildaDares** [comment]
I think this issue has been resolved since body content is correctly aligned in both stable and live site.
