### ISSUE TITLE
Add a "related topics" section under tag card header

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#8226]
I accidentally committed this (getting used to GitPod interface, sorry) so we can remove this, because I only meant to test it out. But if we like it, we can keep it:

https://github.com/publiclab/plots2/commit/b7bcbf23d7f2d75bdcfb0117f10f9c5582fd2f4b

You can try it out here: https://stable.publiclab.org/tag/water-quality

Basically it shows a plus icon next to the tagname. When you click it, it displays 5 related topics. 

![Screen Shot 2020-08-01 at 4 17 31 PM](https://user-images.githubusercontent.com/24359/89109812-960aa000-d412-11ea-976b-f307ff719995.png)
![Screen Shot 2020-08-01 at 4 17 37 PM](https://user-images.githubusercontent.com/24359/89109815-973bcd00-d412-11ea-850e-9aa392241067.png)

**Comment by sagarpreet-chadha** [comment]
Looks great 💯 

Just 2 things I noticed:
1. In mobile view, the tags are overflowing.
2. We should add an animation when showing these tags instead of instant rendering, or maybe rendering  each after 0.1 seconds or so maybe

**Comment by jywarren** [comment]
aww good catch Sagarpreet, for mobile. Can you screenshot? 

Also can we do animation using bootstrap classes or with a simple inline css? 

Thanks for the great ideas!

**Comment by jywarren** [comment]
I think the wrapping looks OK now! 

![image](https://user-images.githubusercontent.com/24359/89343019-a53b5900-d671-11ea-99ca-1668ef67c6d7.png)
https://stable.publiclab.org/tag/water-quality

**Comment by jywarren** [comment]
Closing this up unless we want to return to it. Thanks!
