### ISSUE TITLE
add tags input (matching legacy editor of note editor) to new wiki form and wiki editing page.

### ISSUE THREAD

**Issue by Shulammite-Aso** [publiclab/plots2#8229]
**Please describe the desired behavior.**
Describe the solution you'd like.

This is a feature request by the PL staffs, to have the new wiki form and wiki editing page include field for tag input.

will be working on this soon.

**Additional context (optional)**
Feel free to include any applicable: code, screenshots, or gifs.

**Comment by jywarren** [comment]
Just chiming in with some code links!!!

the tags form from the notes legacy editor, which should work: https://github.com/publiclab/plots2/blob/92834ead6c53d6d9431bb99024d4044b282518be/app/views/editor/post.html.erb#L93-L98

Maybe we can excerpt it into a [partial template](https://guides.rubyonrails.org/layouts_and_rendering.html#using-partials), and just include it in the wiki editor too? 

And then we'll have to confirm that the code to actually add the tags is included in the wiki controller for both `create` and `update` -- 

https://github.com/publiclab/plots2/blob/92834ead6c53d6d9431bb99024d4044b282518be/app/controllers/notes_controller.rb#L100-L102

Hope that helps!!!

**Comment by Shulammite-Aso** [comment]
> Hope that helps!!!

This will help. @jywarren  Another thing however is that i'm not able to see `.../wiki/new` with passenger start, so i don't know how else to tell if its working. unless maybe i push what i have, then somebody else confirms if it works. If it will actually work this way.

**Comment by jywarren** [comment]
Oh, is it because of your user account status? I think you should be able to log in locally with the `admin` account, maybe the pwd is `password`? Or it's written in the `/db/seeds.rb` file. IT could be `secret`... not sure. 

If not, is there another error in loading that page? 

Thanks!

**Comment by Shulammite-Aso** [comment]
> Oh, is it because of your user account status? I think you should be able to log in locally with the `admin` account, maybe the pwd is `password`? Or it's written in the `/db/seeds.rb` file. IT could be `secret`... not sure.
> 
> If not, is there another error in loading that page?
> 
> Thanks!

No other error, except taking me to the dashboard page instead.  I'm going to try logging in as admin however
