### ISSUE TITLE
Broken map link in the archive

### ISSUE THREAD

**Issue by numeroteca** [publiclab/plots2#823]
### What happened just before the problem occurred

I searched for a map in the archive. I found it but the link it is not working.
### Relevant URLs

Broken URL: https://publiclab.org/map/real-estate-bubble-ruins-madrid-spain/2013-01-03
### PublicLab.org username

pablo
I get the same problem without login in.
### Browser, version, and operating system

Firefox 47.0 on Ubuntu 14.04.

**Comment by ebarry** [comment]
Hi Pablo, 
The link seems to be working, but i do not see any aerial imagery on top of the basic satellite map -- is that the problem?

**Comment by ebarry** [comment]
It's also worth noting that the JPG and GEOTIFF links go to broken pages in the archive, but that may be because we have a physical drive to replace.
