### ISSUE TITLE
Image upload in Comment Section

### ISSUE THREAD

**Issue by NitinBhasneria** [publiclab/plots2#8239]
Currently, the image cant be uploaded in the comment section.
![sss](https://user-images.githubusercontent.com/44112080/89287991-8a1d1900-d672-11ea-8908-c7dad6972a03.png)

cc: @sagarpreet-chadha @cesswairimu @jywarren 

I will be working on this.

**Comment by NitinBhasneria** [comment]
OK, so drag and drop is working fine. While the choose file button is not at all working.

**Comment by NitinBhasneria** [comment]
The image button is fixed. 
Next: going to repair the reply on the comment.

**Comment by jywarren** [comment]
Looking great! I think the javascript console output has some clues 🕵️

**Comment by NitinBhasneria** [comment]
> Looking great! I think the javascript console output has some clues

completed in #8240 have l look.😁
