### ISSUE TITLE
old "reports" urls not working

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#824]
There are very few "reports" left, but we had tried to migrate them in the past and I think we need to take another look. 

https://publiclab.org/report/diy-spectrometry-workshop-lima-peru

could be converted to a wiki page or research note; there are few enough reports that this could probably be done manually.

**Comment by 500swapnil** [comment]
This is an old issue. Is it resolved now? Otherwise I can take this up

**Comment by jywarren** [comment]
I think we actually need to look through some old URLs based on this and see if we can write a new route for them?

https://github.com/publiclab/plots2/blob/499bb8d4d0c99be412d7fbdf7a9bc7308c7ea3ac/config/routes.rb#L124

aha! here:

https://web.archive.org/web/*/publiclaboratory.org/report/*

https://publiclab.org/report/plots-new-york-summit and many other examples. 

I believe we just need to refactor this method:

https://github.com/publiclab/plots2/blob/499bb8d4d0c99be412d7fbdf7a9bc7308c7ea3ac/app/controllers/legacy_controller.rb#L58-L61

To be exact, i think we need a query sort of like:

```ruby
@node = Node.find_by(slug: params[:id])
```

And then we can do:

```ruby
redirect_to: @node.path, status: :301
```

To redirect it. Make sense?

**Comment by 500swapnil** [comment]
#2654
