### ISSUE TITLE
Add a button for uploading images to the Wiki Editor toolbar that would look similar to the Rich Editor's button

### ISSUE THREAD

**Issue by shreyaa-sharmaa** [publiclab/plots2#8241]
To add images:
![prompt2](https://user-images.githubusercontent.com/66686803/89438215-2d028f80-d766-11ea-8174-3546cf74dc3d.png)

Toolbar iteration 1:
![tool](https://user-images.githubusercontent.com/66686803/89438180-1fe5a080-d766-11ea-80c0-4ae8eb11e89d.png)

**Comment by shreyaa-sharmaa** [comment]
@jywarren what do you think?

**Comment by jywarren** [comment]
Wow! This could definitely work but do you think it could just start the OS-level fileinput instead? It might be easier! 

So it would work the same as clicking "click to upload" in the comment form footer, you know? 

Thanks @shreyaa-sharmaa !!!
