### ISSUE TITLE
Total Tag count on tag stats pages seems incorrect for tag "beach"

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#8244]
Reporting in here from @ebarry and Jeanette, the graph at https://publiclab.org/tag/beach/stats seems correct, but below it the "Total Tag count" of 8 seems wrong, by their count.

![Screen Shot 2020-07-27 at 10 56 45 AM](https://user-images.githubusercontent.com/24359/89336806-f7777c80-d667-11ea-8065-1df1f6ef782a.png)

That code is driven from here:

https://github.com/publiclab/plots2/blob/c60aaabb56c018962c76abf3f5f2d114f8492d15/app/views/tag/_graph.html.erb#L4-L8

Strange -- `@tags.first.count` would seem to be running `Tag.where(name: params[:id]).first.count`, which doesn't make sense to me. 

Looking deeper, cc @cesswairimu as well...

**Comment by jywarren** [comment]
Aha - more sense here: it's not doing a database count, it's accessing an attribute named `count` on the `Tag` model:

```ruby
irb(main):036:0> Tag.where(name: 'beach').first.count
=> 8
irb(main):037:0> Tag.where(name: 'beach').first
=> #<Tag tid: 15452, vid: 3, name: "beach", description: "", weight: 0, count: 8, parent: nil>
```

**Comment by jywarren** [comment]
So, perhaps that's simply not getting updated. Let's see where else we count tag usage, and also where we update the attribute...

**Comment by jywarren** [comment]
Looks like we need to be running this to maintain that attribute:

https://github.com/publiclab/plots2/blob/d9e7f1143424956cc7d61e7de0b06fd5c1e83a19/app/models/tag.rb#L39-L42

We do that each time a tag is added:

https://github.com/publiclab/plots2/blob/122e8a73b440bb752f080375aad3f24a02b7c8f9/app/models/node.rb#L845

OK, so when `run_count` is run, we get 8 for `beach`

However, when we run this, we see there are only 4 notes (and no wikis) for `beach`:

```ruby
Tag.find_nodes_by_type('beach', 'note').count
```

**Comment by jywarren** [comment]
OK wait we have to run run_count on all tags!!! https://stable.publiclab.org/tag/beach/stats

**Comment by jywarren** [comment]
So we'll need to run:

```ruby
Tag.all.each do |tag|
  tag.run_count
end
```

**Comment by cesswairimu** [comment]
Great detective work :tada:

**Comment by jywarren** [comment]
Running this on stable.publiclab.org now to test.

**Comment by ebarry** [comment]
Exciting to see this detective work yield results!

**Comment by jywarren** [comment]
Sorry, this was completed long ago and is live! Closing!
