### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by jibe-b** [publiclab/plots2#8253]
On page [publiclab.org/wiki/open-call](https://publiclab.org/wiki/open-call)

the link on the word `event`

![Screenshot from 2020-08-05 10-13-00](https://user-images.githubusercontent.com/6146483/89388414-48d54980-d704-11ea-8e56-70ae47d757a6.png)

is wrongly buillt: https://publiclab.org/wiki/www.publiclab.org/events

This wiki page is locked, I let you change this ;)

**Comment by avats-dev** [comment]
@jibe-b ,Yeah, the link is broken. I checked it out. 
**I think the correct link should be https://publiclab.org/events**

**Comment by jibe-b** [comment]
Thanks for dealing with this @avats-dev. Somehow the link is still built the wrong way

![Screenshot from 2020-08-07 12-24-20](https://user-images.githubusercontent.com/6146483/89636521-08fb9700-d8a9-11ea-9f1f-014f52fbbedd.png)

**Comment by cesswairimu** [comment]
Great catch @jibe-b and @avats-dev  you are right :100: I will try to get someone to edit that. Thanks you both

**Comment by ebarry** [comment]
Thank you, i've edited it! Really appreciate the good catch 🤝

**Comment by cesswairimu** [comment]
Thanks @ebarry
