### ISSUE TITLE
All Tag Icon not active when clicked in spam2/queue 

### ISSUE THREAD

**Issue by keshavsethi** [publiclab/plots2#8258]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file https://github.com/publiclab/plots2/blob/main/app/views/spam2/_queue.html.erb#L42 , Here Icon is not active(text is not dark when selected) 
![Screenshot from 2020-08-06 12-24-11](https://user-images.githubusercontent.com/36025262/89500955-2a448080-d7e0-11ea-88c5-ff29243f1495.png)

**Change params[:type] to params[:tag]** 

` <% if params[:type] == "everything" %>` to` <% if params[:tag] == "everything" %>`

**To test this** 
Login as moderator or admin
Go to spam2/queue/filter/everything

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by Vortex2wenty** [comment]
Hi, I would like to claim this issue.

**Comment by keshavsethi** [comment]
> Hi, I would like to claim this issue.

@Vortex2wenty, Sure!! 
Thanks :tada:

**Comment by 2Shar18** [comment]
> Hi, I would like to claim this issue.

Hey, are you still working on this issue? 
I also wish to contribute, so if you are stuck, can you tag me? I'd love to help 😄

**Comment by Aastha2891** [comment]
Hi, I would like to claim this issue

**Comment by avats-dev** [comment]
Go on @Aastha2891 :tada: 
> Feel free to ping if you're stuck!

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by nadimakhtar97** [comment]
@keshavsethi  is this issue still open? I want to contribute to it as I have never made a PR.

**Comment by avats-dev** [comment]
@nadimakhtar97 you can go on, thanks for taking up on this!
> Also @Aastha2891 you can try a different one when you're free, as this is stale for almost 21 days.

**Comment by nadimakhtar97** [comment]
@avats-dev  @keshavsethi     **<% if params[:type] == "everything" %> to <% if params[:tag] == "everything" %>**    is already changed in  **spam2/queue/filter/everything**  at line number 46 in https://github.com/publiclab/plots2/blob/main/app/views/spam2/_queue.html.erb#L42

        **<a href="/spam2/queue/filter/everything" class="btn nav-link  <% if params[:tag] == "everything" %> active<% else %> text-secondary<% end %>"><i class="fa fa-arrow-circle-o-up <% if params[:tag] == "everything" %> text-dark<% else %> text-secondary<% end %>" data-toggle="tooltip" data-placement="top" title="All Nodes which you are following"></i> All Tags</a>**

where else do I need to update params[:type] to parmas[:tag] ? please reply soon.

**Comment by avats-dev** [comment]
@nadimakhtar97 looks like this issue is resolved and should be closed. **You can try #8174 , another fto.** Thanks. :rocket: 

Also, @keshavsethi @cesswairimu , this issue is probably resolved so should be closed. :tada:

**Comment by cesswairimu** [comment]
Thanks you both. You are right. closing this
