### ISSUE TITLE
Re-order legacy and comment toolbars so order of tools matches that of Rich Text Editor

### ISSUE THREAD

**Issue by shreyaa-sharmaa** [publiclab/plots2#8259]
Currently:
![current](https://user-images.githubusercontent.com/66686803/89510991-ef961480-d7ee-11ea-805d-637558ad4f7b.png)

Toolbar iterations including the image icon:
1.
![t1](https://user-images.githubusercontent.com/66686803/89505338-12242f80-d7e7-11ea-9c84-762b31d28ccf.png)

2.
![t2](https://user-images.githubusercontent.com/66686803/89505250-f456ca80-d7e6-11ea-882c-d2a03d2291b9.png)

3.
![t3](https://user-images.githubusercontent.com/66686803/89505251-f456ca80-d7e6-11ea-8274-0638e7a60c34.png)

4.
![t4](https://user-images.githubusercontent.com/66686803/89505254-f587f780-d7e6-11ea-976c-039fc8ccb7a1.png)

5.
![t5](https://user-images.githubusercontent.com/66686803/89505256-f6208e00-d7e6-11ea-8ab1-7522ecf1b5a9.png)

6.
![t6](https://user-images.githubusercontent.com/66686803/89505260-f7ea5180-d7e6-11ea-8c6a-2604bc01d113.png)

**Comment by jywarren** [comment]
![image](https://user-images.githubusercontent.com/24359/90682303-c172f480-e232-11ea-8f34-c8268fae160c.png)

For comparison, here's the rich editor toolbar! 

I'm sorry for the slow response here. However, I think i can clarify a bit after checking with staff. We can remove the "Templates" button entirely. I believe that means that for the remainder, option 4 above looks the best for us! Thank you!
