### ISSUE TITLE
top-level /activities listing page!

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#827]
A place to find activities or post them, by topic!

This is a huge one -- open to suggestions but probably needs a lot of design/UI thinking before we start coding, but just to get it started!!!

**Comment by jywarren** [comment]
Hi, @steviepubliclab - shall we just fold this one into the /topics page, and assume that's the primary way people will find activities, rather than trying to develop an independent /activites page? I could just close this one.

**Comment by steviepubliclab** [comment]
sounds good to me.
