### ISSUE TITLE
Implement Design for /followers and /following routes

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#8270]
**Please describe the desired behavior.**
Currently the /followers and /following route doesn't have design consistent with the rest of the website. We need to implement a design with the same table as the "People who are following" table on the /contributors pages. Reference:- the farthest right hand table on https://publiclab.org/contributors/water-quality.

**Additional context (optional)**
https://publiclab.org/people/liz/followers
https://publiclab.org/people/liz/following

Reference for the table can be constructed
https://publiclab.org/contributors/water-quality

Broken into:
- [ ] #8278
- [ ] #8277

**Comment by Tlazypanda** [comment]
Hey @cesswairimu I was thinking we can get new contributors to pick this up who have contributed here already and can take on a more experienced task. 

What do you think? Should we break this issue down into some parts to make it easier? Thanks :v:

**Comment by cesswairimu** [comment]
Hi @Tlazypanda.. that's a great idea..yeah let's do that. Thanks

**Comment by renugasaraswathy** [comment]
Hi @Tlazypanda @cesswairimu I can pick this up. I am one of the new contributors here and having experience in RoR.

**Comment by cesswairimu** [comment]
Sure thing @renugasaraswathy  we would love your help ...let me try to break this down in the next few minutes then I will ping you to choose which of the issues you would like work on. Thanks

**Comment by cesswairimu** [comment]
@renugasaraswathy  the issues are #8277 and #8278

**Comment by cesswairimu** [comment]
@Tlazypanda do you think we should explore other designs for these two? @ebarry would like to hear your thoughts on this too

**Comment by Tlazypanda** [comment]
Hey @cesswairimu definitely open to this :tada: I just picked up from what @ebarry had suggested here https://github.com/publiclab/plots2/issues/8115#issuecomment-654862501 :sweat_smile:

**Comment by cesswairimu** [comment]
Gotcha, thanks for linking me to that 👍

**Comment by Tlazypanda** [comment]
Closing this moved to #8277  and #8278 Thanks @cesswairimu :heart:
