### ISSUE TITLE
Refine /followers page design

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#8277]
Currently the /followers route doesn't have design consistent with the rest of the website. 
It looks like this 
![Screenshot from 2020-08-10 17-06-57](https://user-images.githubusercontent.com/17081074/89791588-3015cb00-db2c-11ea-8c57-b1d2d7f8ab0b.png)

Link: https://publiclab.org/people/cess/followers
We could implement a design with the same table as the "People who are following" table - the farthest right hand table on https://publiclab.org/contributors/water-quality. But other designs are welcome

**Comment by renugasaraswathy** [comment]
@cesswairimu Will work on this. Thank you
