### ISSUE TITLE
Refine /following page design

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#8278]
Currently the /following route doesn't have design consistent with the rest of the website. 
It looks like this 
![Screenshot from 2020-08-10 17-06-57](https://user-images.githubusercontent.com/17081074/89791588-3015cb00-db2c-11ea-8c57-b1d2d7f8ab0b.png)

Link: https://publiclab.org/people/liz/following

We could implement a design with the same table as the "People who are following" table - the farthest right hand table on https://publiclab.org/contributors/water-quality. But other designs are welcome

**Comment by renugasaraswathy** [comment]
@cesswairimu will work on this too. Thank you

**Comment by renugasaraswathy** [comment]
Hi @cesswairimu @Tlazypanda, I am currently working on this. Could you help answering the following queries?

How do users navigate to /followers or /following pages of user?
would like to understand why is the route '/people/:username/following' instead of '/profile/:username/following'?

Thanks

**Comment by cesswairimu** [comment]
Hi @renugasaraswathy , good question. I do have a specific reason why the routes are set up as such, it could be it was just a call of the developer that worked on that. Or maybe could be the profile page was not initially there and we were using `/people/username` as the profile page then...Given  all the users is `/people` with rails convention this would be our `index` page and hence to get a single user(`show`) this because `/people/username` ...

As for the followers If you go on someone's profile say https://publiclab.org/profile/cess and on the far right below the avator and click on the three dots icon you will see a `Follow` button. But where you can get a link that shows your followers I do not know how to locate that on the site.

**Comment by cesswairimu** [comment]
solved in #8372 Thanks again @renugasaraswathy :1st_place_medal:
