### ISSUE TITLE
not all wikis displayed on tag page although count is correct

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#8279]
### Please describe the problem

> What happened just before the problem occurred? Or what problem could this idea solve?

I wanted to see all the wiki pages tagged `project` so i went to https://publiclab.org/wiki/tag/project. 

> What did you expect to see that you didn't?

I see that the count of wikis (11) is correct, but only three were displayed. I believe this is a bug. See screenshot: 
<img width="1034" alt="Screen Shot 2020-08-10 at 11 54 29 AM" src="https://user-images.githubusercontent.com/161439/89803131-71908100-db00-11ea-9887-a67741629ca5.png">

### Please show us where to look

- https://publiclab.org/wiki/tag/project
- https://publiclab.org/wiki/projects#Example+Project+Pages:

### What's your PublicLab.org username?

Liz

Thanks!

**Comment by jywarren** [comment]
Hi, I believe this is a variation of https://github.com/publiclab/plots2/issues/7334, which we're working on currently. I'm going to merge it into that one, but if it is distinct after all, please re-open,thanks!
