### ISSUE TITLE
make a "redirect" type note which auto-redirects normal users but not mods or admins

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#828]
We sometimes want to redirect a page, but it can take manual database changes to do this. We should simply have a [power tag]() like `redirect:<id>` where the `<id>` is the nid of the destination page.

Normal users (`user.role != 'admin' && user.role != 'moderator'`) should just be automatically redirected in the wiki and notes controllers' `show` methods:

https://github.com/publiclab/plots2/blob/master/app/controllers/wiki_controller.rb
https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb

But admins and mods should see the redirect page, so they can remove the redirect if need be. There should be a notice shown that `Only moderators and admins see this page, as it is redirected to _Page title_. To remove the redirect, delete the tag beginning with "redirect:"`.

That could be flashed before displaying the page, using:

``` ruby
flash.now[:warning] = "Message here"
```

This would be much more flexible and we could actually leave content on the page if we wanted, too.

**Comment by sjones88** [comment]
Hi @jywarren, I'd like to take a crack at this.

**Comment by jywarren** [comment]
That would be super -- thanks! Have you written tests in Rails before, or would you be able to try writing a test for this? An example test you could work from is this one, which logs in as an `admin` and tests for a flashed message and redirect: https://github.com/publiclab/plots2/blob/master/test/functional/wiki_controller_test.rb#L201-L212

One test could be similar, adding the tag and checking for the message. A second, counterpart test could /not/ log in, and check that normal viewers are simply redirected. 

If you're more comfortable tackling the issue itself, i'd be happy to take a stab at the tests, so you could then write the code which "succeeds" at the tests. But if you're interested in doing the tests too that'd be great. 

Thanks again!

**Comment by sjones88** [comment]
I was planning on writing the tests first. Should I make a PR once the tests are written so we can review them before I move on to the issue?

**Comment by jywarren** [comment]
Sure, that sounds great. Also the PR will initially fail (as they should),
which it'd be nice to confirm as the Travis service runs them on your PR
when you post. Thanks!

**Comment by jywarren** [comment]
Hi, @sjones88 - just checking in to make sure you aren't stuck; if you just haven't had time there's no rush. Thanks!

**Comment by sjones88** [comment]
Hi @jywarren, I've been busy lately, but I'm going to work on this today. One issue I ran into was creating a fixture for testing the new 'redirect' power tag. Any insight you could provide would be helpful. Thanks!

**Comment by jywarren** [comment]
Hi, Steven - sorry, I was in a staff retreat and just catching up now. Yes
-- can you push a PR so I can see your code? To add a tag, you need to make
a fixture entry on fixtures/tags.yml AND fixtures/community_tag.yml -- not
the most intuitive due to remaining legacy database structure and naming
conventions we should try to get rid of at some point (and this could use a
good, descriptive new issue, really).

Thanks!

**Comment by sjones88** [comment]
Here's the PR: https://github.com/publiclab/plots2/pull/875
