### ISSUE TITLE
Outdated cloud9 installation instructions

### ISSUE THREAD

**Issue by avats-dev** [publiclab/plots2#8282]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

Cloud9 installation instructions are outdated. They need to be updated.

> What did you expect to see that you didn't?

I wanted to install it on cloud9 and saw that instructions do not match with anything similar now.

### Please show us where to look

https://github.com/publiclab/plots2/wiki/Simple-Installation-for-Cloud9

> This can be used as a reference for current instructions which are similar to standard instructions with added cloud9 environment. 
https://docs.aws.amazon.com/cloud9/latest/user-guide/sample-github.html

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

Not needed here.

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

Not needed.

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hello, you're totally right! We've just for the past few weeks been testing GitPod.io, and are pretty confident that it's ready now. Would you like to try opening a pull request changing the cloud9 instructions to suggest using GitPod instead? It is linked from the top of the README!

**Comment by avats-dev** [comment]
@jywarren I will change the instructions and open a PR soon. 

Just making sure if we're removing **cloud9** instructions and support, because then [this script](https://github.com/publiclab/plots2/blob/master/install_cloudnine.sh) would also needed to be removed.

**Comment by cesswairimu** [comment]
@avats-dev let me know if you would like to work on this..or maybe it can be a fto candidate. Let me know what you think. Thanks

**Comment by avats-dev** [comment]
@cesswairimu we can make this an fto but there are some issues:
- while replacing cloud9 instructions, we should replace them with the one with gitpod. Now, people should be able to use gitpod, as if some newcomer clicks on gitpod badge, he will see the master of this repo instead of his fork, which he needed. So, there should be a work around for this. The best way (that I could find) is to have a gitpod extension or add-on and use it wherever you want to build . This part can be a fto candidate.
- Another issue is that we should also add instructions for people to install through docker, and we should enhance its support, as docker is becoming quite popular and accessible and as it would be best for this codebase (as then there won't be any version issues, and much more), specially for people starting in ruby and rails. Fyi we should already have a dockerfile as gitpod uses it, so it won't require much work, just some touches. we can open this as a new issue with hacktoberfest label.

So what do you think?

**Comment by jywarren** [comment]
Hmm, i like the docker idea, but perhaps this should be spun out into its own issue? Thank you!

Regarding the fork issue you highlighted, should we say "fork this first and then go to this Gitpod URL" with something like https://gitpod.io/#https://github.com/YOURUSERNAME/plots2/ ?

**Comment by avats-dev** [comment]
Yeah @jywarren that would be better and we can also add the alternative to just use an add-on in case you want it to be much easier.
Also, we should have another separate issue for the docker one and maybe this [dockerfile](https://github.com/publiclab/plots2/blob/main/Dockerfile) is valid and would help, but I'm not sure.

**Comment by avats-dev** [comment]
Closing this one as `c9` is resolved in #8515 
For docker, follow up on #8524
