### ISSUE TITLE
Sidebar wrap problem for non-logged-in users

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#8287]
I noticed that when not logged in, the sidebar gets shoved below the rest of content on note pages like this: https://publiclab.org/notes/anngneal/12-08-2017/7-ways-to-measure-monitor-and-evaluate-water-quality

![image](https://user-images.githubusercontent.com/24359/89938270-41baa980-dbe4-11ea-8628-baf0082b8d0d.png)

Tracing it, I thought this is the juncture between divs that's relevant:

https://github.com/publiclab/plots2/blob/73193e0cfca8a648cc2f7db2a342db1197a11576/app/views/notes/show.html.erb#L110-L118

However, I think it's this line which has an unclosed div:

https://github.com/publiclab/plots2/blob/69b8a56ce8c170b74151debf36da57ae8dd762be/app/views/notes/_comment.html.erb#L79-L92

That would only be shown to logged-in users. For non-logged in users, we'd be left with an extra `</div>` on the lines below, causing this issue. Let's test in GitPod.

**Comment by gauravahlawat81** [comment]
Hey @jywarren , you were right. Removing the last `div` did solve this problem. As you mentioned, if the user was not logged in, we were left with an extra div which was causing the issue.

**Comment by gauravahlawat81** [comment]
### Sidebar for non logged in users
![Screenshot from 2021-01-04 22-35-46](https://user-images.githubusercontent.com/36696399/103560096-35115780-4edd-11eb-8310-54fdfcc3411e.png)

### Sidebar for logged in users

![Screenshot from 2021-01-04 22-37-37](https://user-images.githubusercontent.com/36696399/103560249-77d32f80-4edd-11eb-86e5-8b7ab5c06601.png)

**Comment by gauravahlawat81** [comment]
Should I create a PR or we will be converting this into FTO ? @cesswairimu what do you think ?

**Comment by cesswairimu** [comment]
@gauravahlawat81  you can go ahead and create a PR for this...thanks

**Comment by gauravahlawat81** [comment]
@cesswairimu I have created the PR. Thanks !
