### ISSUE TITLE
show "This is an upgrade for X" message at the top of upgrade pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#829]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled.

****

Pages like this:

https://publiclab.org/notes/stoft/09-16-2016/stability-upgrade-mockup-for-plab-spectrometer-3-0

...are proposed upgrades for a specific project (they have the tag `upgrade:dssk` where "dssk" is the tag name for the project they're upgrading, so we should show a message similarly to the one shown on this page:

https://publiclab.org/notes/warren/09-20-2016/building-the-stoft-stability-upgrade-for-desktop-spectrometry-starter-kit-3-0

The notification could be shown on this line, triggering on the power tag `upgrade`:

https://github.com/publiclab/plots2/blob/3702e83c8f50c86ab6d6a197579990d334a12d90/app/views/notes/show.html.erb#L8

`This is an upgrade for ___________. Try building it and _report back how it goes_.`

"report back..." should link to `#Upgrades` which appears lower on the page.

**Comment by 500swapnil** [comment]
I would like to help with this!

**Comment by jywarren** [comment]
That'd be great!

**Comment by ananyo2012** [comment]
@jywarren Can you explain this a bit more? For the page https://publiclab.org/notes/warren/09-20-2016/building-the-stoft-stability-upgrade-for-desktop-spectrometry-starter-kit-3-0 the message of the top of the page should be like 
```
This is an upgrade for dssk. Try building it and _report back how it goes_.
```
Where should the "report back" link point to? Is it the parent research note that has the power tag. https://publiclab.org/notes/stoft/09-16-2016/stability-upgrade-mockup-for-plab-spectrometer-3-0 in this case?

**Comment by ananyo2012** [comment]
Btw https://publiclab.org/notes/stoft/09-16-2016/stability-upgrade-mockup-for-plab-spectrometer-3-0 doesn't show up. Recently I saw some pages that weren't showing. Found another few days back which I forgot to report.

**Comment by jywarren** [comment]
Could you look at how this is coded for Activities, which should be almost
identical?

**Comment by jywarren** [comment]
That's exactly right!

**Comment by Gauravano** [comment]
Can I open a new fto-candidate from this ?

**Comment by jywarren** [comment]
yes please! That'd be great :-)

**Comment by Gauravano** [comment]
Opened in #2369
