### ISSUE TITLE
Embeddable activities grids for including on external sites

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#830]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled.

This could be broken up if it's too complex!

****

When showing PL projects on other sites, we could make it easier to display actionable lists of activities using an `<iframe>`. It could lead to:

`/embed/<tagname>` 

This would involve:

* a new route to the URL above in https://github.com/publiclab/plots2/blob/master/config/routes.rb, like `match 'embed/:tagname' => 'notes#embed`
* a new controller action for `def embed` in https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb -- which contains: `render layout: false` 
* a new template at `/app/views/notes/embed.html.erb` with just an inline grid, so: 

```ruby
<%= insert_extras('[' + params[:tagname] + ']') %>
```

on this line: https://github.com/publiclab/plots2/blob/master/app/helpers/application_helper.rb#L31

Once this is all working, we could make a new issue for featuring the embeddable grid, perhaps in a dropdown somewhere like on the tag listing page...

**Comment by ashleypt** [comment]
On this issue I'll be happy to break it up and assist the newcomers with each sub-issue when they get stuck.

**Comment by ma8sa** [comment]
Hi, I m new here and would like to work on this . Can you help me getting started

**Comment by jywarren** [comment]
Hi, that's great to hear. Perhaps you could start by making a new template
for this, following the steps in this pull request, which did those same
initial steps:

https://github.com/publiclab/plots2/pull/1044/files

But you could name it:

"/app/views/tags/gridsEmbed.html.erb"

And the controller action would be:

"/app/controllers/tags_controller.rb"

Does that make sense? Then you could open a pull request with those changes
and we could add some content to that page. It'll be good to take this
step-by-step, right?

**Comment by ma8sa** [comment]
i have defined embed and and the new route , bbut i m supposed to with the gridsEmbed.html.erb part ?

**Comment by jywarren** [comment]
did you create a new file at that location? you can just use a blank file
for the time being -- if you open a PR, we can take the next steps, thanks!

**Comment by ma8sa** [comment]
i made a blank file there and opened a pull request

**Comment by jywarren** [comment]
Super - saw it in #1188 and left some comments, thanks!
