### ISSUE TITLE
Set image css width to 100% for answers to questions

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#831]
Questions pages display answers below ([like this](https://publiclab.org/questions/warren/09-19-2016/how-can-i-reduce-ambient-light-inside-the-desktop-spectrometry-starter-kit#answers)), but images added inline in peoples' answers do not conform to their parent elements' width; on mobile devices or narrow screens, they overflow and look gigantic and silly. 

We need to add something like:

```css
.answer p img {
  max-width:100%;
}
```

below this these styles in the `style.css` file: https://github.com/publiclab/plots2/blob/master/app/assets/stylesheets/style.css#L349

It should affect this element: https://github.com/publiclab/plots2/blob/master/app/views/questions/_answer.html.erb#L26-L28

**Comment by ykl7** [comment]
@jywarren do you mind if i try to work on this?

**Comment by jywarren** [comment]
Please! Sounds great!

**Comment by ykl7** [comment]
@jywarren Hey Jeffrey, I'm facing some problems in testing right now. So, it could take some time. Sorry for the delay.

**Comment by ananyo2012** [comment]
@ykl7 Can you say what problems are you facing? Is it due to a RSolr error? We recently updated our readme. Please have a look at the [Testing](https://github.com/publiclab/plots2#testing) section of the readme once more.

**Comment by ykl7** [comment]
@ananyo2012 actually, I'm having problems with my Cloud9 environment. I'll look at the [Testing](https://github.com/publiclab/plots2#testing) section as well before I push any changes

**Comment by ananyo2012** [comment]
One more thing you need to install the java libraries which is given in the [Search](https://github.com/publiclab/plots2#search) installation instructions. We haven't yet included it in the cloud9 installation script. But we will be doing it soon.

**Comment by ykl7** [comment]
@ananyo2012 thanks for the heads-up. I'll do that as well and ask you guys if there are any more problems.

**Comment by jywarren** [comment]
Thanks, @ykl7 - please ping us if you have continuing trouble -- and perhaps we could look at your cloud9 install if you grant us access and we can help troubleshoot there. Apologies for the added search-based testing process. 

Another option is to open a pull request with your new commits, and let our new TravisCI service run the tests for you. But this will only give you feedback on things we have tests written for.

**Comment by jywarren** [comment]
Although once you open a PR, others (like me) can pull in your changes and test them out ourselves as well, so that's a way forward too. Thanks for your patience!

**Comment by jywarren** [comment]
Hi - thanks, closed in #859
