### ISSUE TITLE
Follow buttons sticks with Add a description button

### ISSUE THREAD

**Issue by arteevraina** [publiclab/plots2#8316]
### Screenshot

![image](https://user-images.githubusercontent.com/43968121/90424199-58c53400-e0db-11ea-9bdb-9b814fff8f9c.png)

### Please show us where to look

https://publiclab.org/tag/four and reduce the window to half of your monitor screen

### Browser, version, and operating system
Firefox, 79.0 and Ubuntu 18.04

### Additional Information

I would like to work on this.

**Comment by Garvitmodi** [comment]
Hi @arteevraina , I would like to work on this issue.

**Comment by arteevraina** [comment]
@Garvitmodi I am waiting for the maintainers to confirm this issue then you can start working on this.

**Comment by sagarpreet-chadha** [comment]
Yes this looks like a valid UX enhancement, @Garvitmodi yes you can start work on this. Make sure that it looks fine in all browsers. Thanks @arteevraina  @Garvitmodi 🎉

**Comment by arteevraina** [comment]
> Yes this looks like a valid UX enhancement, @Garvitmodi yes you can start work on this. Make sure that it looks fine in all browsers. Thanks @arteevraina @Garvitmodi tada

**Comment by arteevraina** [comment]
@Garvitmodi Go can work on this now.

**Comment by ebarry** [comment]
Just mentioning that I am unable to reproduce this bug on my laptop in Chrome or in Firefox, or on my phone in Android Chrome.

**Comment by arteevraina** [comment]
> Just mentioning that I am unable to reproduce this bug on my laptop in Chrome or in Firefox, or on my phone in Android Chrome.

When I previously checked it in my Firefox browser. It showed this UI on reducing the window size to half of the screen.

**Comment by bodhisha** [comment]
Hey, Can I work on this? Or is anyone currently on this? @arteevraina

**Comment by arteevraina** [comment]
Yes, you can work if you are able to reproduce it @bodhisha
