### ISSUE TITLE
Odd wording on unique title validation failure message: "base: You have already used this title."

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#8319]
The wording on the title uniqueness validator for new notes is a little odd:

![image](https://user-images.githubusercontent.com/24359/90537735-ac6f6600-e14b-11ea-81ac-1a5333d3ab13.png)

Aha - ok, we probably don't have to print the "key" line here on line 368 -- let's just remove that!:

https://github.com/publiclab/plots2/blob/c55e1ff6983041e197c9a4e168f107c78688cbaf/app/views/editor/rich.html.erb#L367-L370

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by avats-dev** [comment]
Hey @jywarren , I removed line 368 (one with the `key`) from this https://github.com/publiclab/plots2/blob/c55e1ff6983041e197c9a4e168f107c78688cbaf/app/views/editor/rich.html.erb#L367-L370

and then when I tested on GitPod, I got this:
![Screenshot from 2020-08-24 00-56-47](https://user-images.githubusercontent.com/35889327/90987042-7267ef00-e5a5-11ea-925f-3c0d86c0a334.png)

**Comment by avats-dev** [comment]
Also, the **publish** button behaves strangely in this scenario, I have added a screenshot for reference. 
> And it remained like this even if I changed the name, but it publishes if clicked on. 

![Screenshot from 2020-08-24 00-58-50](https://user-images.githubusercontent.com/35889327/90987095-dee2ee00-e5a5-11ea-8bc5-d43634a71e25.png)

I think this is worth another issue, right?

**Comment by sagarpreet-chadha** [comment]
Yes @avats-dev , kindly make a issue in PL.editor repo telling in detail the steps to reproduce this and what was the expected behaviour?

Also you can make PR for this if you want, removing printing of key line. Thanks 😄

**Comment by avats-dev** [comment]
Well, @sagarpreet-chadha , removing the printing of key line is not working out as there's no error getting thrown. It's just a reddish bar then. 
I replaced https://github.com/publiclab/plots2/blob/c55e1ff6983041e197c9a4e168f107c78688cbaf/app/views/editor/rich.html.erb#L367-L370 with https://github.com/avats-dev/plots2/blob/4e880b9d5cc6da72c56b1581a29c5a96b21c4cf4/app/views/editor/rich.html.erb#L367-L369 , and so I think something else is off.

**Comment by avats-dev** [comment]
@sagarpreet-chadha or @cesswairimu any suggestions on this one?

Also I think this should be transferred to the editor repo to avoid duplicate issues.
