### ISSUE TITLE
Image upload button not working in comment editor

### ISSUE THREAD

**Issue by avats-dev** [publiclab/plots2#8328]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

Well, pressing the `Choose One` button didn't worked in comments editor. Even the cursor also didn't changed to pointer when hovered over it.
![Peek 2020-08-19 04-01](https://user-images.githubusercontent.com/35889327/90572078-cacb7500-e1d0-11ea-8b7e-4c2f5f9afd5c.gif)

> What did you expect to see that you didn't?

Well, after clicking on it, it should open a dialog to browse through files and select file(single or multiple) which meets the condition to be called as an image.

### Please show us where to look

For an example you can follow the link below but it's a problem in editor, not any certain page.
https://publiclab.org/notes/stevie/04-03-2019/event-frac-sand-mining-health-research-public-forum

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

Not needed.

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

I don't think it is relevant here, but even so:
- Browser : Mozilla Firefox
- Version : 79.0
- OS : Ubuntu 20.04 LTS

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by Garvitmodi** [comment]
Hi @avats-dev , I would like to work on this issue.

**Comment by avats-dev** [comment]
Hi @Garvitmodi , Welcome to the publiclab community! :heart: 

- If you understand the issue and know what to do, go on and open a PR. :+1: 

- If you're new to this codebase, and would like to try somewhat relatively more easy, pick one of [these issues](https://github.com/publiclab/plots2/labels/first-timers-only) to get a start. You can also drop a message [here](https://github.com/publiclab/plots2/issues/7683) to get an easy issue to start with.

Feel free to ask anything, would love to help: :smile:

**Comment by Garvitmodi** [comment]
Hey @avats-dev thanks for getting back to me. I  understand the issue and would like to help you resolve it.
Can you please provide me with the acceptance criteria of the pr request so that I can start working on it.

**Comment by avats-dev** [comment]
Well then, @Garvitmodi you're good to go, open a PR and link to this issue when you're done. Thanks :heart:

**Comment by avats-dev** [comment]
@Garvitmodi any updates on this?

**Comment by NitinBhasneria** [comment]
Hey @avats-dev nice catch. Want to inform you that this bug is already mentioned in #8239 and solved in https://github.com/publiclab/plots2/pull/8240.

**Comment by Garvitmodi** [comment]
Hi @avats-dev  I am still working on it. As mentioned by @NitinBhasneria  , I will see PR #8240 . I will report back here as soon as I become familiar with the work done in PR #8240 and report with improvement suggestions if any.

**Comment by avats-dev** [comment]
@NitinBhasneria sorry for reopening this, I didn't checked. Great work on #8240 :+1: .

@Garvitmodi I think this is almost resolved, you can look for some other open issues. I think #8319 is good to go, check it out.

> I'm closing this one, thanks.
