### ISSUE TITLE
Link to comments on a wiki page does not show comments

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#8334]
### Please describe the problem (or idea)

I visited https://publiclab.org/wiki/translation and clicked the `...` icon to open up additional menu items, shown in screenshot: 
<img width="1221" alt="Screen Shot 2020-08-19 at 3 33 32 PM" src="https://user-images.githubusercontent.com/161439/90681509-8c19d700-e231-11ea-954f-f73662435911.png">
)

When i clicked on the link for "2 Comments", this URL loaded: https://publiclab.org/wiki/translation#comments, but no comments were shown on the page. 

> What did you expect to see that you didn't?

I expected to see the 2 Comments that have supposedly been left on this wiki page. 

### Please show us where to look

https://publiclab.org/wiki/translation
https://publiclab.org/wiki/translation#comments

### What's your PublicLab.org username?
liz

**Comment by jywarren** [comment]
Hi @PrakharSharma41 - we'd love your help. I think i've found the issue - the real URL should be:

https://publiclab.org/wiki/translation/comments

Yet we point to `#comments` here: 

https://github.com/publiclab/plots2/blob/639f15e83396fe00c3b06d7ebc17f4c3f5c23247/app/views/like/_like.html.erb#L115-L121

Would you be able to change that `href` value in the `_like.html.erb` template and open a pull request accordingly? I've made a `first-timers-only` issue to help you along the way: https://github.com/publiclab/plots2/issues/8345

**Comment by ebarry** [comment]
hi @PrakharSharma41 , what other questions might you have? 🌳✨

**Comment by ebarry** [comment]
Thanks for fixing this @PrakharSharma41 ! I see the fix is live. 
Closed by https://github.com/publiclab/plots2/pull/8355
