### ISSUE TITLE
Test DrupalNode.activities with activity node fixtures

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#834]
We need to test the new `DrupalNode.activities` and `DrupalNode.upgrades` methods at the bottom of `drupal_node.rb`:

https://github.com/publiclab/plots2/tree/master/app/models/drupal_node.rb

We should create fixtures in:

https://github.com/publiclab/plots2/tree/master/test/fixtures/node.yml
https://github.com/publiclab/plots2/tree/master/test/fixtures/tags.yml
https://github.com/publiclab/plots2/tree/master/test/fixtures/community_tags.yml

to create dummy nodes that have tags `activity:foo` and `upgrade:foo` and then check if `DrupalNode.activities` and such actually return those nodes. This can be a unit test in:

https://github.com/publiclab/plots2/tree/master/test/unit/drupal_node_test.rb

**Comment by prabhagharan** [comment]
Hi,

I am super new to Rails and open source contribution, thought of learning Rails by contributing to some open source project so landed here.
This my first ever pull request. https://github.com/publiclab/plots2/pull/877
Let me know if I am missing something.
