### ISSUE TITLE
ambiguous double pagination UI on /spam2

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#8343]
![image](https://user-images.githubusercontent.com/24359/91185836-4c813e00-e6bc-11ea-9225-449a3ebb05e7.png)

Hi @keshavsethi - i noticed 2 pagination UIs here and wondered if we want to either remove one or clarify the difference? 

Thank you!

**Comment by keshavsethi** [comment]
@jywarren It has been corrected in my PRs. Can you please verify it on stable as it is fine there. This is my old PR!!
Thanks!!

**Comment by keshavsethi** [comment]
@jywarren @ebarry Is this issue still there? 
Thanks!!

**Comment by jywarren** [comment]
Confirmed, thanks! It's corrected - thanks for the speedy reply!! Closing!!! 🎉
