### ISSUE TITLE
error on /spam2/comments/filter/unmoderated

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#8369]
Mimi reports that she is:

> trying to do some bulk moderation of old spam comments, but getting an error when I press the “spam” button. Here’s what it looks like.

![image](https://user-images.githubusercontent.com/24359/91872286-b2823e00-ec45-11ea-8605-cb0c441d7f08.png)

I think i've found the correlated Sentry error and will link!

```
NameError: undefined local variable or method `user' for #<BatchController:0x00007ff140142998>
Did you mean?  user_id
  from app/controllers/batch_controller.rb:135:in `block in batch_comment'
  from app/controllers/batch_controller.rb:127:in `each'
  from app/controllers/batch_controller.rb:127:in `batch_comment'
```

Mimi also sez:

> I get this same error even if i try to do moderation of individual comments via the spam button up top from this page. The spam button within the table under “Action” does work.

**Comment by keshavsethi** [comment]
@jywarren I have already changed this method in a batch controller. I have checked it in https://stable.publiclab.org/spam2/comments/filter/unmoderated/30 and bulk spam worked fine there. I think some of the PRs got merged but not reflected in the PL. Can you please verify??
Thanks :heart:

**Comment by jywarren** [comment]
The last publication to the live site was https://jenkins.laboratoriopublico.org/job/Deploy%20Plots2/71/ - and updated only to https://github.com/publiclab/plots2/commit/639f15e8, from 9 days ago. 

The last commit to the batch controller was - https://github.com/publiclab/plots2/commit/baa7e7cd335b8325c8194f0740a59449448050d9 - Aug 25 - 1:58 EDT
 - 7 days ago. So this should be resolved there. I'll republish and check! Thank you!!! Sorry to keep submitting old issues!!
