### ISSUE TITLE
New "answers" to questions are not showing up in dashboard feed

### ISSUE THREAD

**Issue by gretchengehrke** [publiclab/plots2#837]
### What happened just before the problem occurred

I was the third person to submit an answer to a question, but the question was still buried in the dashboard feed down at the date of the original question-posting. Then, I found new information that was relevant and wanted to submit an additional answer, and again had to scroll all the way down the page to find the question post in my feed. The "comment bubble" on the question in the dashboard indicated that there had been zero responses. However, when I clicked on the question page link, it appropriately showed that there had been three responses.

**Comment by jywarren** [comment]
Thanks, Gretchen -- I think this needs to be broken out into several
distinct issues and will circle back to help flesh them out, though if you
have time, please go for it:

* comment count on dashboard does not reflect "answers"
* new "answers" don't appear on dashboard, or bump original Q back up in
timeline (we could use the template shown on https://publiclab.org/questions
-- which is here:
https://github.com/publiclab/plots2/blob/master/app/views/questions/_questions.html.erb
)

**Comment by jywarren** [comment]
I believe the "comment count on dashboard does not reflect answers" issue is being resolved here: https://github.com/publiclab/plots2/pull/940

This would be a great issue to flesh out with next steps; should questions with new answers be "bumped back up" in the feed, or should we display answers to questions in the dashboard feed (and would this cause clutter?).

**Comment by jywarren** [comment]
Hi, @gretchengehrke - thoughts on this? 

Should questions with new answers be "bumped back up" in the feed, or should we display answers to questions in the dashboard feed (and would this cause excess clutter?).

**Comment by jywarren** [comment]
In the new design, we will be showing topic areas instead of individual posts, so this should be resolved! Thanks!
