### ISSUE TITLE
Weekly Community Check-In #74 - Retrospect of the work done 

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#8374]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## This is not the end :P Just start of open source journey 😄 

Cheers to all the summer interns 🎉 
I would love to know your views/reviews on how did your internship went? What went well? What could had gone better for you? How were the mentors and reviewers?
Did you learn something from the review comments maybe?

💯 

## This week's focus Issues

These are issues that are of high priority and requests from our large community that use the software. 

🥇 
There is one high priority issue this week:
https://github.com/publiclab/PublicLab.Editor/issues/607
Any help appreciated!

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄
 🥇

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** 🎈
Have a great week and year ahead all ❤️

**Comment by sagarpreet-chadha** [comment]
@jywarren, @AgyeyaMishra, @Jolios, @cesswairimu, @samarakoon-ryan, @Samasth, @malaikaaiyar, @keshavsethi, @OmLakshmi, @nsachin08, @dependabot-preview[bot], @Tlazypanda, @galanggg, @ishika1727, @icarito, @RajatSablok, @mronauli, @ijeomaemeruwa, @alaxalves, @Shulammite-Aso, @JapneetSingh5, @Neilblaze, @markkulube, @vinuch @JapneetSingh5, @Neilblaze, @markkulube, @vinuch, @Tlazypanda, @icarito, @dependabot-preview[bot], @jywarren, @keshavsethi, @praaatik, @Janitham97, @imanishbarnwal, @dburugupalli, @adityakpranav, @ioampatzidis, @esiebomaj, @Alexjake660, @cesswairimu, @urvashigupta7, @daemon1024, @jscastanos @keshavsethi, @jywarren, @AyanChoudhary, @imajit,@NitinBhasneria, @nstjean, @marientje, @rutger-t, @Tlazypanda,

**Comment by sagarpreet-chadha** [comment]
@llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-sharmaa, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @Tlazypanda,@keshav234156, @WaldenJosh, @B4Lee, @VisnuGanth, @jessibreen, @alaxalves, @kamal-kaur04, @sssash18, @chinmay021, @Srija616, @AnnaMinakova, @greenbrown, @taysa91, @TaishiRoy, @yagmurbaydogan, @Shulammite-Aso, @Jigyasa-Kumari @moliver4, @justinelai, @Snouzy, @stevenalila, @Digiox, @yandu31, @milosv1, @jamescapps, @Nevenem, @chirag-wadhwa, @yogeshjdeshmukh, @omizrahi99, @theOpetunde, @sailahonkanen, @robin-natale, @avidler, @ccyccyccy

**Comment by sagarpreet-chadha** [comment]
@jscastanos, @sarthak-choudhary, @dongskyler, @keshavsethi, @Shulammite-Aso, @ckchu8, @keshav234156, @DerekChristy, @Srija616, @priyanka-choubey, @AyanChoudhary, @imajit, @NitinBhasneria, @nstjean, @marientje, @rutger-t, @imajit, @NitinBhasneria, @nstjean, @marientje, @rutger-t, @nsachin08 @Rohit-786 @Tristan-Elizabeth @aakanchha01 @habeckmatt @hiteshsubnani0128 @ijeomaemeruwa @OmLakshmi @dmoini @yusufatalay @Samasth @malaikaaiyar @davidgoldcode @Shokescodes @marciojunior88 @avats-dev @NitinBhasneria, @nstjean, @marientje, @rutger-t, @urvashigupta7, @daemon1024

**Comment by cesswairimu** [comment]
Thanks Sagar :tada:

**Comment by pydevsg** [comment]
@keshavsethi , @keshav234156 share your GSoC experience here :smile: 
Great time mentoring you. :heart: 
Kudos @keshavsethi for your work in Spam management Dashboard. :tada:
@keshav234156 for your work in the Public Lab Editor :tada:

**Comment by jywarren** [comment]
Great work, everyone!!! Thanks for all your time and effort!!! 🎉 🎉 🎉 🎉

**Comment by keshavsethi** [comment]
> @keshavsethi , @keshav234156 share your GSoC experience here 
> Great time mentoring you. 
> Kudos @keshavsethi for your work in Spam management Dashboard. 
> @keshav234156 for your work in the Public Lab Editor

Hey Everyone 👋🏻
It's been an amazing time working with everyone in GSoC 2020 🎉   I learned a lot of things from everyone!! 
Thanks to all the _**mentors and community members**_ ❤️  for helping, reviewing, and continuously supporting me throughout the GSoC period
This is link to my **GSoC report**: https://publiclab.org/notes/keshav_sethi0004/08-29-2020/spam-management-dashboard-gsoc-2020-report
Spam Management Dashboard **Documentation**: https://publiclab.org/notes/keshav_sethi0004/08-18-2020/spam-management-dashboard-documentation 
Thanks, everyone!! :rocket: :tada:

**Comment by cesswairimu** [comment]
I suggest we  leave this check-in open for this week too to give everyone a chance to give a retro.
Great job everyone :tada: :tada: and thanks for choosing PL :tada: :tada:  :rocket: ]]


Great week ahead

**Comment by jywarren** [comment]
Agreed. I've just submitted the compiled final evaluations and would love to hear from @publiclab/soc and mentors if you're able! 

Many thanks to our Outreachy and GSoC participants, and to everyone who helped mentor this summer. It was an incredibly good experience, especially given the very difficult situation in the world this summer. I hope you are all safe and healthy and wish the best for your families and friends as well. 

🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by shreyaa-sharmaa** [comment]
Hey everyone! 
I hope you're all safe and healthy :heart:
It's been an amazing experience working with PL community. 

A big thank you to the mentors, maintainers and all the community members for your invaluable input, for being patient while explaining something, and supporting us throughout. 
I learnt a lot form all of you! :heart: :tada:

**Comment by Tlazypanda** [comment]
Hey everyone :wave: 

Hope you are all doing well :heart:  
The last week has been super busy with endless assignments and evaluations :cry: 

Apart from the many technical things that I learnt during this internship, I guess just working here on an actual live project has made me feel much more confident. And I think I owe it all to the community members here who welcomed us with open arms and always supported us throughout :100: I am sure that this experience will shape all of us to go on to spread the same level of warmth that we received onto others and a passion for learning like there's no tomorrow.

Also shout out to @cesswairimu who has been helping me with the Alternate text for Images issue where I was stuck for a long time :100: :heart: Really appreciate when we have mentors like her who go out of the way to help their mentees

**Comment by cesswairimu** [comment]
Thanks everyone,  anyone interested in opening this week's check-in?

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/8394 Thanks everyone
