### ISSUE TITLE
Display alert on "candidate" activity posts with prompt to "adapt" them

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#839]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled.

****

Our new [activities system](https://publiclab.org/tag/activity-grids) sets out a [more structured format](https://publiclab.org/notes/warren/09-17-2016/what-makes-a-good-activity) for activity posts, but we've been seeding it with existing content that's _close to_ an activity, or from which an activity could be adapted. 

For example, many activities listed [on the spectrometry page](https://publiclab.org/wiki/spectrometry#Activities) are not really formatted as activities yet, but we hope folks will adapt their content and post new ones, as [this](https://publiclab.org/notes/warren/09-18-2016/see-the-fraunhofer-absorption-lines-in-sunlight) was adapted from [this earlier post](https://publiclab.org/notes/cfastie/3-2-2013/fraunhofer).

To achieve this, we could use a [power tag](https://publiclab.org/wiki/power-tags) such as `status:candidate` -- that way it'd be listed on an Activities grid, but there'd be an acknowledgement that it's not really an activity yet. The tag could trigger an alert above the text, similarly to this code:

https://github.com/publiclab/plots2/blob/master/app/views/notes/show.html.erb#L4

The note could say something like (input, @steviepubliclab or @ebarry or @gretchengehrke?): 

> This was marked as a candidate activity -- read about how to adapt its content into a fully-fledged, step-by-step activity that can be easily replicated.

**Comment by 500swapnil** [comment]
I would like to help with this issue

**Comment by jywarren** [comment]
I think we could add a similar `if` statement after line 4 of `show.html.erb` -- checking for `status:candidate`, and link people to this URL from the words "read about how to adapt its content":

https://publiclab.org/notes/warren/09-17-2016/what-makes-a-good-activity

**Comment by 500swapnil** [comment]
#1078
