### ISSUE TITLE
Weekly Community Check-In #75 - Thank you GSOC and Outreachy folks

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#8394]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Thank you GSoC and Outreachy folks :heart: 

A big big thank you to the interns,  the mentors, our reviewers team and PL staff for all the hardwork :muscle: :muscle:  
We have a congratulatory  post [here](https://publiclab.org/notes/warren/09-14-2020/congratulations-to-our-outreachy-and-gsoc-2020-fellows). Thanks @sagarpreet-chadha  and @jywarren for drafting this :tada: :tada: 

Thanks everyone who joined the presentation call today, it was great to meet you all :heart: Feel free to leave a link to your presentation if you would like to share with the rest of the community(optional) 

Awesome blogs and documentation of this summer's work :tada: :tada: 
----------------------------------------------------------------------------------
@keshavsethi - https://publiclab.org/notes/keshav_sethi0004/08-29-2020/spam-management-dashboard-gsoc-2020-report
@Tlazypanda  - https://hackmd.io/@itm2017004/BJuqtap6L
@alaxalves - https://publiclab.org/notes/alaxallves/08-29-2020/gsoc-2020-report
@keshavsethi - https://publiclab.org/notes/keshav_sethi0004/08-18-2020/spam-management-dashboard-documentation

(please feel free to edit this and add links to any blogs and docs I might have missed)
      
See you all around :heart: 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** 🎈
Have a great week and year ahead all ❤️

**Comment by cesswairimu** [comment]
@jywarren, @AgyeyaMishra, @Jolios, @cesswairimu, @samarakoon-ryan, @Samasth, @malaikaaiyar, @keshavsethi, @OmLakshmi, @nsachin08, @dependabot-preview[bot], @Tlazypanda, @galanggg, @ishika1727, @icarito, @RajatSablok, @mronauli, @ijeomaemeruwa, @alaxalves, @Shulammite-Aso, @JapneetSingh5, @Neilblaze, @markkulube, @vinuch @JapneetSingh5, @Neilblaze, @markkulube, @vinuch, @Tlazypanda, @icarito, @dependabot-preview[bot], @jywarren, @keshavsethi, @praaatik, @Janitham97, @imanishbarnwal, @dburugupalli, @adityakpranav, @ioampatzidis, @esiebomaj, @Alexjake660, @cesswairimu, @urvashigupta7, @daemon1024, @jscastanos @keshavsethi, @jywarren, @AyanChoudhary, @imajit,@NitinBhasneria, @nstjean, @marientje, @rutger-t, @Tlazypanda,

**Comment by cesswairimu** [comment]
@llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-sharmaa, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @Tlazypanda,@keshav234156, @WaldenJosh, @B4Lee, @VisnuGanth, @jessibreen, @alaxalves, @kamal-kaur04, @sssash18, @chinmay021, @Srija616, @AnnaMinakova, @greenbrown, @taysa91, @TaishiRoy, @yagmurbaydogan, @Shulammite-Aso, @Jigyasa-Kumari @moliver4, @justinelai, @Snouzy, @stevenalila, @Digiox, @yandu31, @milosv1, @jamescapps, @Nevenem, @chirag-wadhwa, @yogeshjdeshmukh, @omizrahi99, @theOpetunde, @sailahonkanen, @robin-natale, @avidler, @ccyccyccy

**Comment by cesswairimu** [comment]
@jscastanos, @sarthak-choudhary, @dongskyler, @keshavsethi, @Shulammite-Aso, @ckchu8, @keshav234156, @DerekChristy, @Srija616, @priyanka-choubey, @AyanChoudhary, @imajit, @NitinBhasneria, @nstjean, @marientje, @rutger-t, @imajit, @NitinBhasneria, @nstjean, @marientje, @rutger-t, @nsachin08 @Rohit-786 @Tristan-Elizabeth @aakanchha01 @habeckmatt @hiteshsubnani0128 @ijeomaemeruwa @OmLakshmi @dmoini @yusufatalay @Samasth @malaikaaiyar @davidgoldcode @Shokescodes @marciojunior88 @avats-dev @NitinBhasneria, @nstjean, @marientje, @rutger-t, @urvashigupta7, @daemon1024

**Comment by HarshKhandeparkar** [comment]
Hi all! I created [this](https://github.com/HarshKhandeparkar/gpujs-hive-compute) tool to use multiple computers on a network for parallel computing. It is using [gpu.js](https://gpu.rocks) which means that it can run in a browser, nodejs or even on a mobile device(using a browser).

I was thinking that this could be used in some of the projects here, such as Image Sequencer. IS already uses gpu.js for gpu accelerating its backend. With this tool, it can use multiple GPUs which dont even need to be on the same part of the planet. And if there is no external GPU, it will always work on its own.

**Comment by jywarren** [comment]
Hi everyone! It was great seeing folks on the call yesterday. Sending 🙌  to everyone!

And sharing this cool graphic of repo activity from the past few months:

![image](https://user-images.githubusercontent.com/24359/93239244-82ac5d80-f750-11ea-9317-55745d1dea24.png)

via http://ghv.artzub.com/#repo=plots2&climit=300&user=publiclab


@HarshKhandeparkar whoa, this is really amazing, Harsh! You should totally open an issue on IS! I'm trying to imagine what it looks like, perhaps an icon like 

![image](https://user-images.githubusercontent.com/24359/93239733-31e93480-f751-11ea-9afa-13b570ac57a2.png)

could be shown in the module, you click it and it shows a URL you can go to from nearby devices in order to add them to the cluster? Let's brainstorm a bit in an IS issue! very impressive!! 😲 🤯

**Comment by cesswairimu** [comment]
Happy monday all, anyone wonna open this week's check-in?

**Comment by KarenEfereyan** [comment]
> Hi everyone! It was great seeing folks on the call yesterday. Sending 🙌 to everyone!
> 
> And sharing this cool graphic of repo activity from the past few months:
> 
> ![image](https://user-images.githubusercontent.com/24359/93239244-82ac5d80-f750-11ea-9317-55745d1dea24.png)
> 
> via http://ghv.artzub.com/#repo=plots2&climit=300&user=publiclab
> 
> @HarshKhandeparkar whoa, this is really amazing, Harsh! You should totally open an issue on IS! I'm trying to imagine what it looks like, perhaps an icon like
> 
> ![image](https://user-images.githubusercontent.com/24359/93239733-31e93480-f751-11ea-9afa-13b570ac57a2.png)
> 
> could be shown in the module, you click it and it shows a URL you can go to from nearby devices in order to add them to the cluster? Let's brainstorm a bit in an IS issue! very impressive!! 😲 🤯

@jywarren this graphic is really cool
