### ISSUE TITLE
Use I18n gem to internationalize application_controller

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#840]
That controller includes lots of "you were logged in/out" type messages which are pretty key for most users. 

https://github.com/publiclab/plots2/blob/master/app/controllers/application_controller.rb

There are instructions in the README and examples in other controllers for how to implement I18n here -- any help appreciated!

**Comment by mzishtiaq** [comment]
Hi, I am a fresh junior developer, hoping to contribute to open source and learn some more by doing so. I suppose I could give it a go and hopefully, contribute something useful to this wonderful project, with your assistance. :)

**Comment by jywarren** [comment]
We would love it if you took a crack at this issue -- thank you so much! I'm happy to help if you run into trouble, and please note that I'm a little less responsive than usual this week as we're having a staff retreat. Also -- if you run into a *lot* of trouble, there are a range of more thoroughly documented issues at https://github.com/publiclab/plots2/labels/first-timers-only

Thanks again!

**Comment by mzishtiaq** [comment]
Thank you for the positive response, this looks achievable and I can give it a shot. I hope you're having a good time at the staff retreat, enjoy. :)

**Comment by mzishtiaq** [comment]
Hi, I have made some progress and used I18n gem for the following:
* "You must be logged in to do that."
* "You must be logged in to access this page"
* "You must be logged out to access this page"
* "The author of that note has been banned."
Just wanted to ask if these were the only ones you wanted? And could you help me out with German translation, please? :)

**Comment by jywarren** [comment]
Thanks! If you want to push a pull request with "in-progress" in the title, with any progress you've made, we're happy to provide input and help you as you work. 

I think we could post a new issue asking for German translation and pointing at your new english file -- it'll fall back to English for those we don't yet have. 

Also, we're hoping to improve our outreach to new contributors -- would you mind sharing how you found us? Thanks again!

**Comment by mzishtiaq** [comment]
No problem, I had already completed the English file and also created the 'de' file for German translations, however, I only have empty strings there at the moment. I'll pull down master and rebase it again to solve any conflicts and then I'll open a pull request.

I found you through [up-for-grabs]:http://up-for-grabs.net/#/tags/rubyonrails, you're pretty much the only open source project under 'rubyonrails' tag there. :)

**Comment by jywarren** [comment]
Oops, sorry forgot to close this! Fixed in https://github.com/publiclab/plots2/commit/43222cd31f306344e0fcfca04c996ba96f160ff0

Thanks again and take a look at this if you're looking for a new challenge! 

https://github.com/publiclab/plots2/labels/help-wanted
