### ISSUE TITLE
cue replications display with `activity:*` in addition to `seeks:replications` tag

### ISSUE THREAD

**Issue by shapironick** [publiclab/plots2#841]
### What happened just before the problem occurred

I was on the https://publiclab.org/wiki/open-air page and wanted to be able to click the replications number in order to see the replications that occurred under this activity. As replications increase it would be great to be able to see all of the different iterations/replications. 

### Relevant URLs

https://

### PublicLab.org username

nshapiro

### Browser, version, and operating system

chrome Version 53.0.2785.116 (64-bit) yosemite osx

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
That's a great idea -- would it link down to the replications section, then?

**Comment by ebarry** [comment]
We're talking in person here so let me add in that it could be any collection, even like how search results show, or like tag results: https://publiclab.org/tag/open-air

**Comment by jywarren** [comment]
hmm, not sure I follow that but i'm sure you'll flesh this out as you go.
Tnx!

**Comment by shapironick** [comment]
It would be great for the "2 replications" number to link to a new page
that aggregates those two replications and all subsequent ones. does that
make sense? you were imagining a link down lower in the page? that could
work! it could also get messy, is my only hesitancy.

**Comment by shapironick** [comment]
ah i see there is something like it on the bottom of the OG note for the
activity
https://publiclab.org/notes/nshapiro/09-26-2016/build-a-plant-based-air-purifier

is that what you were saying could be linked to? makes sense!

**Comment by jywarren** [comment]
I believe we have a fix for this forthcoming, thanks! Changing title.

**Comment by jywarren** [comment]
Done in #890!

**Comment by shapironick** [comment]
Fantastic! thanks!
