### ISSUE TITLE
Weekly Community Check-In #76 - Let's create some Hacktoberfest  issues

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#8419]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Let's create some Hacktoberfest  issues

Since Hacktoberfest is just around the corner :100: :tada: , let's welcome some opensource contributors :heart:  and celebrate the spirit of Opensource. Please check out https://hacktoberfest.digitalocean.com/ for more information. If we have enough contributors, how about creating a virtual Hacktoberfest meetup? :see_no_evil: 

Hacktoberfest welcomes all opensource contributors to contribute to public repositories and the first 75,000 contributors with 4 or more pull requests receive tshirts. 

Our task at hand is to identify issues that can be labelled `hacktoberfest`.

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** 🎈
Have a great week and year ahead all ❤️

**Comment by Tlazypanda** [comment]
@jywarren, @AgyeyaMishra, @Jolios, @cesswairimu, @samarakoon-ryan, @Samasth, @malaikaaiyar, @keshavsethi, @OmLakshmi, @nsachin08, @dependabot-preview[bot], @Tlazypanda, @galanggg, @ishika1727, @icarito, @RajatSablok, @mronauli, @ijeomaemeruwa, @alaxalves, @Shulammite-Aso, @JapneetSingh5, @Neilblaze, @markkulube, @vinuch @JapneetSingh5, @Neilblaze, @markkulube, @vinuch, @Tlazypanda, @icarito, @dependabot-preview[bot], @jywarren, @keshavsethi, @praaatik, @Janitham97, @imanishbarnwal, @dburugupalli, @adityakpranav, @ioampatzidis, @esiebomaj, @Alexjake660, @cesswairimu, @urvashigupta7, @daemon1024, @jscastanos @keshavsethi, @jywarren, @AyanChoudhary, @imajit,@NitinBhasneria, @nstjean, @marientje, @rutger-t, @Tlazypanda,

**Comment by Tlazypanda** [comment]
@llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-sharmaa, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @Tlazypanda,@keshav234156, @WaldenJosh, @B4Lee, @VisnuGanth, @jessibreen, @alaxalves, @kamal-kaur04, @sssash18, @chinmay021, @Srija616, @AnnaMinakova, @greenbrown, @taysa91, @TaishiRoy, @yagmurbaydogan, @Shulammite-Aso, @Jigyasa-Kumari @moliver4, @justinelai, @Snouzy, @stevenalila, @Digiox, @yandu31, @milosv1, @jamescapps, @Nevenem, @chirag-wadhwa, @yogeshjdeshmukh, @omizrahi99, @theOpetunde, @sailahonkanen, @robin-natale, @avidler, @ccyccyccy

**Comment by Tlazypanda** [comment]
@jscastanos, @sarthak-choudhary, @dongskyler, @keshavsethi, @Shulammite-Aso, @ckchu8, @keshav234156, @DerekChristy, @Srija616, @priyanka-choubey, @AyanChoudhary, @imajit, @NitinBhasneria, @nstjean, @marientje, @rutger-t, @imajit, @NitinBhasneria, @nstjean, @marientje, @rutger-t, @nsachin08 @Rohit-786 @Tristan-Elizabeth @aakanchha01 @habeckmatt @hiteshsubnani0128 @ijeomaemeruwa @OmLakshmi @dmoini @yusufatalay @Samasth @malaikaaiyar @davidgoldcode @Shokescodes @marciojunior88 @avats-dev @NitinBhasneria, @nstjean, @marientje, @rutger-t, @urvashigupta7, @daemon1024

**Comment by ebarry** [comment]
Hi happy equinox everyone! ☀️🌍🌏🌎☀️
This week i'm working on report writing 😅

**Comment by cesswairimu** [comment]
@nadimakhtar97

**Comment by cesswairimu** [comment]
Hello everyone,
This week I will continue with the cleanup of issues & PRs across our projects and hackoberfest labelling. Also still working on  #7991 
Great week ahead everyone

**Comment by Tlazypanda** [comment]
Hey everyone :wave: I am planning to open issues with this `Hacktoberfest` label @cesswairimu can you give me an idea of the difficulty level of these issues in plots2 or what we can go for? :sweat_smile: Also shout out to @cesswairimu for her continued support on #7991 :tada: :clap:

**Comment by cesswairimu** [comment]
@Tlazypanda I am mostly looking for "help-wanted" or "bug" labelled issues. One thing we have to make sure that they have enough context for someone to quickly pickup and start working on and also independent in that they are not relying on other issues. The website describes them as issues with "a well-defined scope and are self-contained". Hope this helps and thanks for help :100:

**Comment by Tlazypanda** [comment]
Hey @cesswairimu Thanks for the info on this :v: I was wondering if we can create some hacktoberfest issues for migration to pagy on a route-to-route basis. The pagy docs might be self-contained and if the issue is also structured in a proper manner contributors might be able to follow with ease. What do you think? :sweat_smile: @jywarren

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/8440. Thanks everyone
