### ISSUE TITLE
permalinks to specific answers in Q&A

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#842]
Our new Q&A system is great, and people are starting to post questions and answers:

https://publiclab.org/questions

On research notes, you can click on the "time posted" text to get a deep link (using a `#hash` at the end of the URL) to the comment -- opening that link will auto-scroll down to that comment: 

> https://publiclab.org/notes/warren/09-17-2016/what-makes-a-good-activity#c15466

In this example, "15466" is the comment id. The code for this can be found here:

https://github.com/publiclab/plots2/blob/master/app/views/notes/_comment.html.erb#L17

For Answers, this is not implemented:

https://publiclab.org/questions/gretchengehrke/09-20-2016/question-would-it-be-feasible-to-use-a-stationary-camera-to-conduct-emissions-opacity-evaluation

But it'd be a pretty simple change to this line:

https://github.com/publiclab/plots2/blob/master/app/views/questions/_answer.html.erb#L14

Using the answer id -- which I believe would be `<%= answer.id %>` in the template.

**Comment by sandyvern** [comment]
Hi! I would like to give this a go please.

**Comment by jywarren** [comment]
That would be great! As always, we're happy to offer input if you get stuck!

**Comment by sandyvern** [comment]
Hi again! I have attempted to fix my original correction but not sure if the test rerun?...or if I need to open another pr?...or maybe my code is just still wrong, which a very valid possibility! :-)

**Comment by jywarren** [comment]
OK -- taking a look in the PR at #849 -- thanks!

**Comment by jywarren** [comment]
Completed in #849 -- thanks again!
