### ISSUE TITLE
Migrate to pagy 

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#8426]
**Please describe the desired behavior.**
Currently we are using will_paginate gem for pagination but pagy offers better performance and saves memory.  
Follow up to #8326 

https://ddnexus.github.io/pagy/migration-guide
https://github.com/ddnexus/pagy

Implemented routes

**wiki**
- [x] stale
- [x] index
- [x] revisions
- [x] author

**tag**
- [x] blog
- [x] show

**notes**
- [x] places
- [x] author

**Comment by Tlazypanda** [comment]
Hey @jywarren @cesswairimu using this issue as master issue will be adding pagy for different routes in smaller prs :sweat_smile:

**Comment by cesswairimu** [comment]
cool, haven't used pagy before will check it out. Thanks

**Comment by jywarren** [comment]
Thank you! Yes, `pagy` seems to be massively faster... and lower memory usage. I hope this will be really helpful!

**Comment by avats-dev** [comment]
Also, this could be implemented through a lot of ftos or hacktoberfest issues. I think managing this like #6579 would be good too to keep track of remaining changes.

**Comment by Tlazypanda** [comment]
Yes, I also think we should create some issues out of this :sweat_smile: for hacktoberfest mayve we can maintain the list of functions in which this has been implemented in the issue description
