### ISSUE TITLE
List of who pressed "like" should be shown on each answer in Q&A

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#843]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled.

****
Our new [Q&A system](https://publiclab.org/questions) is great, and people can "like" individual answers -- like one of the answers on this page:

https://publiclab.org/questions/gretchengehrke/09-20-2016/question-would-it-be-feasible-to-use-a-stationary-camera-to-conduct-emissions-opacity-evaluation

![screenshot 2016-09-26 at 4 33 30 pm](https://cloud.githubusercontent.com/assets/24359/18850776/fe6ca806-8406-11e6-9e4f-d00d3e6b1736.png)

However, you can't tell who else liked the answer -- the way you can see who liked a question (or note):

![screenshot 2016-09-26 at 4 34 16 pm](https://cloud.githubusercontent.com/assets/24359/18850799/1ea5021c-8407-11e6-8d34-2ce50eb754d9.png)

This might take some UI design work -- maybe a caret menu like how it's implemented for questions:

https://github.com/publiclab/plots2/blob/master/app/views/like/_like.html.erb#L8-L14

**Comment by ryzokuken** [comment]
I'd love to work on this, as this issue was tagged `help-wanted`. However, I might run into some problems (being new to open source development) and might need help.

**Comment by ryzokuken** [comment]
https://github.com/publiclab/plots2/blob/master/app/views/answer_like/likes.js.erb

Renders the star based on if the `answer` is `liked_by` the `current_user`, I'd look into the `liked_by` function, maybe it has a list of people who have liked it already and all that's required is to display that list.

**Comment by jywarren** [comment]
We'd love your help and are happy to offer any assistance you might need.
Thanks a lot!

Just curious -- we're trying to improve our outreach to new contributors --
how did you happen to hear about us?

Thanks!

I think that's a good place to start!

**Comment by ryzokuken** [comment]
@jywarren I got to you from up-for-grabs.net

It's great that you've been using the help-wanted tag to help newcomers get up to speed with this project.

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by jywarren** [comment]
Hi, just checking if you've gotten stuck on this at all, or if I could help in any way? Thanks!

**Comment by ryzokuken** [comment]
I'd get on this ASAP after the bower issue is closed. Thanks for reminding me :)

**Comment by Pk13055** [comment]
@ryzokuken Are you still tackling this?

**Comment by ryzokuken** [comment]
@Pk13055 No, please feel free to work on it. If you need any help, please feel free to ask here on Github or on our Github channel. Thanks.

**Comment by ananyo2012** [comment]
@Pk13055 Just checking in if you are working  on this?

**Comment by Pk13055** [comment]
Yes, I will submit a PR within the day. I was actually caught up with
something else.

On Dec 19, 2016 11:22 AM, "Ananyo Maiti" <notifications@github.com> wrote:

@Pk13055 <https://github.com/Pk13055> Just checking in if you are working
on this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/plots2/issues/843#issuecomment-267898133>,
or mute
the thread

**Comment by ananyo2012** [comment]
Sure take your time.

**Comment by Pk13055** [comment]
@ryzokuken  Can you link the function for `liked_by_users`? Can you also direct me to the code for the `like` button? I can get started on the pop-up menu for the same.

**Comment by ananyo2012** [comment]
Here is the code for answer like button https://github.com/publiclab/plots2/blob/master/app/views/questions/_answer.html.erb#L46
Here is the `liked_by` method https://github.com/publiclab/plots2/blob/master/app/models/concerns/node_shared.rb#L8-L10

**Comment by ryzokuken** [comment]
Thanks for the help, @ananyo2012

**Comment by Pk13055** [comment]
@ryzokuken I've made the required changes, I think it should be solved. However, my repo has some changes that haven't been pushed which I don't want to include in this PR; how should I proceed such that my feature-branch only contains this latest commit?

**Comment by ananyo2012** [comment]
@Pk13055 I hope you got through your problem?

**Comment by Pk13055** [comment]
Yes, I've submitted a PR regarding the same.

**Comment by Pk13055** [comment]
@ananyo2012 Yes, the problem was a long time ago I hadn't properly created a branch and some commits always carried over to succeeding PRs; I created a new fork and (I hope) it shouldn't be a problem any longer.
