### ISSUE TITLE
Weekly Community Check-In  #77 - Hacktober and Outreachy October 

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#8440]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

##  Hacktober and Outreachy October 

This October we are expecting folks from Hackoberbest and  Outreachy applicants for the winter program. So lets be on the lookout and help where need be.

 ###  :woman_technologist: Hackoberfest :man_technologist: 

If you are a contributor consider registering for Hacktoberfes and contribute to our projects. If you open 4 PRs during the month of October you will receive a  Hacktoberfest tee or tree reward after the month is over. New contributors coming in for Hacktoberfest welcome and its great to have you here :balloon:. We have a number of issues with the 'hackoberfest' label but also feel free to check out our 'help-wanted' issues. We could organize an event within the month if we have a number of people participating. Be sure to checkout any virtual events in your region and see if you would be interested in attending one 

### :tada:  Outreachy :tada: 

We challenge everyone this week to create a fto for  the Outreachy folks you can give it the "outreachy" label to preserve it for them. If you are an Outreachy applicant welcome to PublicLab  :balloon: feel free to say hi below and ask any questions you might have. We have a discussion issue for you here https://github.com/publiclab/plots2/issues/8448 . Here you can ask any questions, say hi and introduce yourself.

## This week's focus Issues

These are issues that are of high priority and requests we have this week
*ftos ftos ftos* This week let us please create fto issues for the Outreachy applicants who we expect to start coming on Monday next week. 

We will very much appreciate any help on these issues. also any help in identifying fto-candidates(_these are issues that can be converted to fto or broken down to multiple ftos_) will be appreciated
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note to focus issues contributors

A big thanks to @Tlazypanda for opening this https://github.com/publiclab/plots2/pull/8411 fixing a travis error :tada: and many thanks to @jywarren and @VladimirMikulic for helping on that  :tada: 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** 🎈
Have a great week and year ahead all ❤️

**Comment by cesswairimu** [comment]
@jywarren, @AgyeyaMishra, @Jolios, @cesswairimu, @samarakoon-ryan, @Samasth, @malaikaaiyar, @keshavsethi, @OmLakshmi, @nsachin08, @dependabot-preview[bot], @Tlazypanda, @galanggg, @ishika1727, @icarito, @RajatSablok, @mronauli, @ijeomaemeruwa, @alaxalves, @Shulammite-Aso, @JapneetSingh5, @Neilblaze, @markkulube, @vinuch @JapneetSingh5, @Neilblaze, @markkulube, @vinuch, @Tlazypanda, @icarito, @dependabot-preview[bot], @jywarren, @keshavsethi, @praaatik, @Janitham97, @imanishbarnwal, @dburugupalli, @adityakpranav, @ioampatzidis, @esiebomaj, @Alexjake660, @cesswairimu, @urvashigupta7, @daemon1024, @jscastanos @keshavsethi, @jywarren, @AyanChoudhary, @imajit,@NitinBhasneria, @nstjean, @marientje, @rutger-t, @Tlazypanda,

**Comment by cesswairimu** [comment]
@llabake, @khushi02, @Alexjake660, @LarrySul, @nicoleiocana, @chrisdrums1, @Angelvicks, @Akanksha1212, @beladinaelfitri, @rid1hady, @shreyaa-sharmaa, @goamoth, @SusannaDiV, @yusofsf, @nanlliu, @Tlazypanda,@keshav234156, @WaldenJosh, @B4Lee, @VisnuGanth, @jessibreen, @alaxalves, @kamal-kaur04, @sssash18, @chinmay021, @Srija616, @AnnaMinakova, @greenbrown, @taysa91, @TaishiRoy, @yagmurbaydogan, @Shulammite-Aso, @Jigyasa-Kumari @moliver4, @justinelai, @Snouzy, @stevenalila, @Digiox, @yandu31, @milosv1, @jamescapps, @Nevenem, @chirag-wadhwa, @yogeshjdeshmukh, @omizrahi99, @theOpetunde, @sailahonkanen, @robin-natale, @avidler, @ccyccyccy

**Comment by cesswairimu** [comment]
@jscastanos, @sarthak-choudhary, @dongskyler, @keshavsethi, @Shulammite-Aso, @ckchu8, @DerekChristy, @Srija616, @priyanka-choubey, @AyanChoudhary, @imajit,   @marientje, @rutger-t, @imajit,  @marientje, @rutger-t, @nsachin08 @Rohit-786 @Tristan-Elizabeth @aakanchha01 @habeckmatt @hiteshsubnani0128 @ijeomaemeruwa @OmLakshmi @dmoini @yusufatalay @Samasth @malaikaaiyar @davidgoldcode @Shokescodes @marciojunior88 @avats-dev, , @marientje, @rutger-t, @urvashigupta7,   @muzzyay, @CyberAngler93, @Kirti2502, @sangu09,  @Hassanelashram, @nadimakhtar97, @joyhumin, @yashkpal1711, @Mohitkumar6122, @lax0248917, @Sethpony, @erickcsh,

**Comment by dmoini** [comment]
@cesswairimu Could you please remove me from future weekly community check-ins?

**Comment by cesswairimu** [comment]
@dmoini sure thing, sorry for any inconvenience caused

**Comment by ebarry** [comment]
Welcome Hacktober participants and Outreachy Winter applicants!

**Comment by urvashigupta7** [comment]
Hi everyone, I will be participating in Outreachy as well as Hacktoberfest this time. Really excited. 🤩❤️🎉

**Comment by sagarpreet-chadha** [comment]
I heard that we can even ask them (hacktoberfest) to plan a tree instead of receiving swags, is that true?

I plan to work on number of issues mostly in PL.editor this week :smile:
Will try to open FTO’s as well labelling hactoberfest 👍

**Comment by cesswairimu** [comment]
@sagarpreet-chadha  that's true :tada:

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/PublicLab.Editor/issues/634. Thanks everyone :tada:
