### ISSUE TITLE
Add pagy for questions route

### ISSUE THREAD

**Issue by avats-dev** [publiclab/plots2#8444]
**Please describe the desired behavior.**

Pagy is a pagination gem used for its peak performance over other pagination tools. As mentioned #8426 we have been trying to migrate our codebase from will_paginate to pagy gem and would love your help with it! tada
 
Here is how you may implement pagy for a single action: -

 * Select action `index` under [`questions_controller`](https://github.com/publiclab/plots2/blob/main/app/controllers/questions_controller.rb)
 
 * Since here pagination is already implemented using `will_paginate` as [`.paginate(page: params[:page], per_page: 24)`](https://github.com/publiclab/plots2/blob/07b03d0aa7612e40db0f723327da48aaf5692013/app/controllers/questions_controller.rb#L24-L27), you can remove this line so that the method now looks like
    ```
      @questions = Node.questions
      .where(status: 1)
      .order('node.nid DESC')
    ```

 * Now add the pagy method in this action as -
     ```
      @pagy, @questions = pagy(Node.questions
      .where(status: 1)
      .order('node.nid DESC'), items: 24)
    ```
    
Here 24 represents the items to be displayed on each page. This is the most basic way we can use pagy over any action: -
 ` @pagy, @records = pagy(Product.some_scope)`

Now, repeat the same workflow for following actions too, all under [`questions_controller`](https://github.com/publiclab/plots2/blob/main/app/controllers/questions_controller.rb)
 - `index_shadow` https://github.com/publiclab/plots2/blob/07b03d0aa7612e40db0f723327da48aaf5692013/app/controllers/questions_controller.rb#L32-L35
 - `answered` https://github.com/publiclab/plots2/blob/07b03d0aa7612e40db0f723327da48aaf5692013/app/controllers/questions_controller.rb#L98-L102
- `unanswered` https://github.com/publiclab/plots2/blob/07b03d0aa7612e40db0f723327da48aaf5692013/app/controllers/questions_controller.rb#L111-L117
 
**Now applying this on html generated in views**
 - Move to the html code which is generated for this controller at [`app/views/questions/_question.html`](https://github.com/publiclab/plots2/blob/main/app/views/questions/_questions.html.erb)
 - Search for the `will_paginate` line and replace it with
   ```
       <% if @pagy %> 
         <%= raw pagy_bootstrap_nav @pagy %>
       <% else %> 
         <%= will_paginate @notes, renderer: willPaginate::ActionView::BootstrapLinkRenderer unless @unpaginated %> 
       <% end %>
   ```
    
 - This will now check if `@pagy` variable is available or not and then if present will generate pagination using pagy.
 
 - Awesome, create a pull request for the same and add screenshots if relevant!

---

 **Additional context (optional)**
 In case of queries please checkout the following links for help: -
 https://ddnexus.github.io/pagy/how-to
 https://ddnexus.github.io/pagy/migration-guide
 #8428
 #8326

**Feel free to ask if you are stuck or need any help. Thanks :rocket:**

**Comment by tyler-wel** [comment]
@avats-dev 
Hey avats! I also commented on the blog routes issue, but I would love to take a shot at implementing this. I've worked with pagy at least once, and just got the repo setup locally 👍  #hacktoberfest

**Comment by avats-dev** [comment]
Hey @tyler-wel , you're welcome to help us migrate to pagy. You are free to open a PR to resolve this or you can open similar issues for routes that still don't have migrated. 

Thanks 👍
