### ISSUE TITLE
Search tags returns improper tag links

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#8459]
### Please describe the problem (or idea)
While working on pagination for search#tags in #8458 noticed that the search query yields improper and weird tags. 

> What did you expect to see that you didn't?
https://publiclab.org/search/tags/one

![image](https://user-images.githubusercontent.com/24359/95669987-36d4b480-0b54-11eb-9e7e-9e21246b6e25.png)

**Comment by ebarry** [comment]
Wow. How did you get this result @Tlazypanda ? What did you type in, and where, and what did you click to arrive at this page?

**Comment by Tlazypanda** [comment]
Hey @ebarry under the /search/tags route for searching tags with a query term so the query I searched for was one :sweat_smile:

**Comment by jywarren** [comment]
Hi @Tlazypanda that's great, i guess that page is not linked to and so was overlooked in later design refinements. I've created an FTO covering this and will make one to add this to the sidebar links for types of search as well. https://github.com/publiclab/plots2/issues/8530

**Comment by jywarren** [comment]
Thanks!
