### ISSUE TITLE
Reverting signup validation PR related to failing test

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#8460]
(update from @jywarren) -- So @cesswairimu noted that this seems related to https://github.com/publiclab/plots2/pull/7768/ and we are looking to revert https://github.com/publiclab/plots2/pull/7768/ now:

> So there is a bug, the signup page if you do not check the captcha or check the animals checkbox it throws the spam detection error but actually the account is already created. That is why the test is failing. I think something broke. I am thinking we revert that commit so that we unblock everyone else as we figure out what's happening. 

****

This test is failing in the last few PRs. did we change this url or what is happening? 
![Screenshot from 2020-10-06 17-38-20](https://user-images.githubusercontent.com/17081074/95216742-1bd40e80-07fb-11eb-8977-e134c53b7075.png)

**Comment by cesswairimu** [comment]
Found that the test was added on https://github.com/publiclab/plots2/pull/7768 checking locally why the url is not working

**Comment by jywarren** [comment]
Wow Cess, one step ahead of me! Just found this in #8383. Amazing!

**Comment by cesswairimu** [comment]
So there is a bug, the signup page if you do not check the captcha or check the animals checkbox it throws the spam detection error but actually the account is already created. That is why the test is failing. I think something broke. I am thinking we revert  that commit so that we unblock everyone else as we figure out what's happening. what do you think @jywarren ?
Looping in @shreyaa-s too
![sign-up](https://user-images.githubusercontent.com/17081074/95241721-d8879900-0816-11eb-91ac-9c93411ed134.gif)

**Comment by jywarren** [comment]
Ah i see. Yes, ok, let's revert https://github.com/publiclab/plots2/pull/7768 and resolve related bugs and circle back to re-examine. Thank you @cesswairimu and ccing @shreyaa-sharmaa (shreya's new handle) in relation -- no worries, this is good to have caught! Note the tests we changed in #8461 as a result, we'd want to revert those back too...

**Comment by jywarren** [comment]
Ah, sorry, i see Cess created #8463 -- moving there now.

**Comment by cesswairimu** [comment]
cool,  creating the PRs for the reverts. thanks
