### ISSUE TITLE
Show notice on accepted Answers prompting them to be adapted into Activities

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#847]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled.

****

Here's where it shows if an answer is accepted: https://github.com/publiclab/plots2/blob/master/app/views/questions/_answer.html.erb#L34-L36

Examples of answered questions can be found here: https://publiclab.org/questions/answered/

The notice (`<p class="alert alert-success">Alert text here</p>`) could say:

> Your answer was accepted! If it would be helpful, consider expanding on this answer by [posting a step-by-step activity](/post?template=activity,tags=response:nid)

where the link led to: `/post?template=activity,tags=response:<question-nid>` and `<question-nid>` was the `nid` of the question -- that way it'd be linked back, once posted.

**Comment by 500swapnil** [comment]
I would like to help with this issue

**Comment by jywarren** [comment]
Super, thanks!

**Comment by 500swapnil** [comment]
#1051

**Comment by jywarren** [comment]
Fixed in https://github.com/publiclab/plots2/pull/1051 thanks!!
