### ISSUE TITLE
Improved styling of posts in map popups on /map pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#8470]
The map popups on https://publiclab.org/map look like this right now:

![image](https://user-images.githubusercontent.com/24359/95267553-8721de80-0803-11eb-957f-aa174fba585a.png)

I think we can refine the popups that are shown on maps. The best thing would be if they appeared as they do on pages like this: https://publiclab.org/tag/water-quality -- these use the `.card` style from Bootstrap -- https://getbootstrap.com/docs/4.4/components/card/

![image](https://user-images.githubusercontent.com/24359/71694212-7b891f00-2d7c-11ea-8d72-77c45000f687.png)

Would someone like to try giving the popup design a go to get them to match?

_Originally posted by @jywarren in https://github.com/publiclab/plots2/issues/6993#issuecomment-570356247_

**Comment by burianovata** [comment]
Hi! I'm Outreachy applicant.  Can you assign this issue to me, please?

**Comment by jywarren** [comment]
Sure, go ahead! Thank you!!!

**Comment by jywarren** [comment]
Did you need help finding the template files?

**Comment by burianovata** [comment]
@jywarren yes please. This is my first time working with Ruby project, so it's a bit confusing to understand file structure.

I need to find `leaflet.css`  that contains popup styles. I found out it is included by this line:
https://github.com/publiclab/plots2/blob/5a2155a8f269ff20e134fd296ddaf35fb748c180/app/views/map/_mapDependencies.html.erb#L1
But there's no `leaflet/dist` folder in the project.

Also I need a file where popup container classes can be added. So I'm looking for parent elements of these:
https://github.com/publiclab/plots2/blob/5a2155a8f269ff20e134fd296ddaf35fb748c180/app/assets/javascripts/leaflet_helper.js#L90-L92

Thanks!

**Comment by Cadreia** [comment]
@jywarren Please can you assign this issue to me? I'm an Outreachy intern applicant and would like to work on it

**Comment by jywarren** [comment]
Hi @Cadreia - @burianovata is currently working on this one. If you'd like, we can make you a new issue? 

@burianovata I believe `/lib/leaflet/dist/leaflet.css` is a dependency from the external `leaflet` library, which gets installed with the `yarn` utility. So it wouldn't show up unless you run `yarn install`. However, being external, we can't edit it in our codebase, but you could override it. 

That said, I think we can work within the existing Leaflet styles, rather than modifying them, for the most part. You're totally right that you could edit line 90 of `plots2/app/assets/javascripts/leaflet_helper.js` and I think i recommend adding to that file to add a wrapper `div` around the content, with its own class -- OR you could add to styles here:

https://github.com/publiclab/plots2/blob/c60aaabb56c018962c76abf3f5f2d114f8492d15/app/assets/stylesheets/map.css#L32

See how it uses `.leaflet-popup` already there? and you can use the Chrome inspector to see the structure of the existing styles and markup; looks like it has a nested `.leaflet-popup-content-wrapper` div as well:

![image](https://user-images.githubusercontent.com/24359/95490972-fe23b800-0966-11eb-9975-dc4383145924.png)

I guess that `map.css` file is where to make your changes! How does that sound?

**Comment by burianovata** [comment]
@jywarren it makes sense! Thank you for such detailed explanation. I keep on with this issue.
