### ISSUE TITLE
Wrong text input gets selected while using toolbar on comments

### ISSUE THREAD

**Issue by urvashigupta7** [publiclab/plots2#8478]
While trying to add new comment  when any of the option is choosen from toolbar the changes are displayed in different text input.

![ezgif com-video-to-gif (6)](https://user-images.githubusercontent.com/41363633/95346113-1c42d700-08d9-11eb-87e9-d018b8cd15bb.gif)

### where to look

https://publiclab.org/questions/Cogreg/09-20-2020/how-do-i-test-home-made-fertilizer

**Comment by Sagarpreet** [comment]
Correct!
Always the first comment editor is changed. This is because if do not have any `id` associated to each comment editor.

**Comment by nibble0101** [comment]
Hi @Sagarpreet . Outreachy applicant here. Can I take a  look at this?

**Comment by sagarpreet-chadha** [comment]
Hey @nibble0101 , yes we would like your help 👍 
So this is a little big issue, you may want to break this down 😄 
Also let’s wait for @jywarren approval before we start because we might want to spin off a separate library for comment editor and solving here may not be useful now.

**Comment by noi5e** [comment]
Starting to work on this one! Just made a PR to add unique IDs to the toolbar buttons. After that, I think it will be a very similar fix to the image upload cross-wiring issues (linked above in this issue)
