### ISSUE TITLE
Replace .count on app/views/search to .size

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#8489]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the files where we have `.count` with `.size` . Using .size increases the speed of the query.

1. https://github.com/publiclab/plots2/blob/main/app/views/search/all_content.html.erb#L49
2. https://github.com/publiclab/plots2/blob/main/app/views/search/_questions_blank.html.erb#L20
3. https://github.com/publiclab/plots2/blob/main/app/views/search/_tags_blank.html.erb#L12
4. https://github.com/publiclab/plots2/blob/main/app/views/search/_wikis_blank.html.erb#L21
5. https://github.com/publiclab/plots2/blob/main/app/views/search/_profiles_blank.html.erb#L15

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by cesswairimu** [comment]
reserved for @Annysah

**Comment by ImagineZero0** [comment]
Hey..
I just wanted to know how does one Claim the issue to start contributing?

**Comment by cesswairimu** [comment]
Hi @ImagineZero0, first you check if anyone has commented saying `working on this issue` or smth like that. If not leave a comment saying you are working on that issue. If they commented a while back and no pull request is linked ask them if they are still working on it. hope that answers your question

**Comment by ImagineZero0** [comment]
> Hi @ImagineZero0, first you check if anyone has commented saying `working on this issue` or smth like that. If not leave a comment saying you are working on that issue. If they commented a while back and no pull request is linked ask them if they are still working on it. hope that answers your question

Thank you for your informative reply....
Seems like someone is already working on this issue currently so I would just for some other issue..
Thanx again for your answer, this seems a little confusing for the first time really..

**Comment by Annysah** [comment]
Hello @cesswairimu,
I'm so excited, I have completed the task you assigned.
Can I get a review?

**Comment by Annysah** [comment]
I will also love to take up more issues please!

**Comment by cesswairimu** [comment]
@Annysah I see you created multiple PRs, we usually create one pull request per issue. Could you please update all the files on one of the pull requests. Do let me know if you need any help with that

**Comment by Annysah** [comment]
Oh, please how do I go about updating all the files in a PR?

**Comment by cesswairimu** [comment]
Sure are you editing on the web or locally?

**Comment by Annysah** [comment]
I am editing on the web

**Comment by cesswairimu** [comment]
cool. Lets use this branch https://github.com/Annysah/plots2/tree/patch-6.

- Click on https://github.com/Annysah/plots2/tree/patch-6/app/views/search
- Click on the file _questions.html.erb. On the top right you will see the pencil icon,  click to the correct line.
- Add a message on the `commit changes` text box then click the commit changes.

The changes should reflect on this pull request https://github.com/publiclab/plots2/pull/8491/files.
 Repeat the same for the other 3 files

**Comment by Annysah** [comment]
![1](https://user-images.githubusercontent.com/52763841/95508568-1fa69300-09ab-11eb-8acb-92db7ce61619.PNG)
@cesswairimu I'm a bit confused what can I edit in this file _questions.html.erb. because it does not have the .count?

**Comment by cesswairimu** [comment]
oh sorrry I meant ` _questions_blank.html.erb`

**Comment by cesswairimu** [comment]
here https://github.com/Annysah/plots2/blob/patch-6/app/views/search/_questions_blank.html.erb

**Comment by Annysah** [comment]
Thank you!

**Comment by Annysah** [comment]
@cesswairimu Thank you so much for the reviews.
Can I get a review? here is the link to the corrections: https://github.com/publiclab/plots2/pull/8491/files

**Comment by cesswairimu** [comment]
Awesome :tada: on it, now you could close all the other pull requests and leave this one https://github.com/publiclab/plots2/pull/8491. Thanks
