### ISSUE TITLE
"# more" link not working in tags sidebar listing on nodes pages

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#8490]
### Please describe the problem

The underlined link text in the sidebar that indicates that there are a certain number of additional tags on a piece of content is clickable, but is not actually a link
<img width="117" alt="Screen Shot 2020-10-08 at 1 13 08 PM" src="https://user-images.githubusercontent.com/161439/95491806-252eb980-0968-11eb-8c9d-db045e593a9f.png">

> What did you expect to see that you didn't?

I expected that this would expand to show existing tags. 
Using the "circle +" does serve to expand and show the tags AND provide the add a tag box, so the functionality is still available, which is good. 

However, the broken link should be fixed. 

### Please show us where to look

https://publiclab.org/questions/jeffkrol/09-29-2020/using-thunderoptics-spectrophotometer

### What's your PublicLab.org username?

> This can help us diagnose the issue: 
liz

**Comment by swarajpure** [comment]
Can I work on this?

**Comment by cesswairimu** [comment]
Go ahead @swarajpure. Thanks.
The file that renders this tag sidebar is https://github.com/publiclab/plots2/blob/main/app/views/tag/_tagging.html.erb

**Comment by ebarry** [comment]
Thanks @swarajpure !
Feel free to ask any questions, i may not have described the issue very well. 
Clicking the underlined text is supposed to show the blue lozenges of the tags. Then clicking the "circle+" is supposed to open the input box to add more tags. This is right, isn't it @jywarren ?

**Comment by swarajpure** [comment]
Thank you @ebarry !
Do I necessarily have to have linux environment for ruby? I use windows.

**Comment by cesswairimu** [comment]
@swarajpure we do have windows installation guidelines here https://github.com/publiclab/plots2#windows-installation  do let us know if you are having any trouble with the installations. Thanks

**Comment by swarajpure** [comment]
I guess I will pass this one. Commenting myself so that somebody else can take it up and fix it instead of you guys waiting up for me. Didn't wish to ghost.

Sorry for the inconvenience caused.

**Comment by cesswairimu** [comment]
no worries, thanks @swarajpure

**Comment by publiclab-mimi** [comment]
Hi all. I wanted to note that this broken link is especially troublesome if you’re not logged in to the website, as I’m only able to see the functional “+” button if I’m logged into Public Lab. So for food who may not have a username, they’re unable to access any tags that are in the collapsed menu.

**Comment by jywarren** [comment]
Hi, just noting this was solved in https://github.com/publiclab/plots2/issues/8571 by @nk183 in a first-timers-only issue created by @Cadreia -- thank you all!!!
