### ISSUE TITLE
Wrong link to revisions page in the wiki

### ISSUE THREAD

**Issue by numeroteca** [publiclab/plots2#850]
### What happened just before the problem occurred
When trying to see the revisions of this wiki page https://publiclab.org/wiki/aerial-photography the link provided in the tab was wrong: https://publiclab.org/wiki/revisions/aerial-photography--2 instead of the correct one https://publiclab.org/wiki/revisions/aerial-photography

**Comment by jywarren** [comment]
Thanks, Pablo! This is a duplicate with #816-- hope to find someone to tackle it soon! I'll mark it as "priority".
