### ISSUE TITLE
Advanced search not working

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#854]
### What happened just before the problem occurred

At https://publiclab.org/searches/new, entering "dustduino" and pressing the search button results in:

> Required parameter missing: search

@ujithaperera and @david-days -- any ideas? all tests pass, so is there an issue in the controller? Does it work in your development environments?
### PublicLab.org username

warren, also @steviepubliclab reported as well
### Browser, version, and operating system

Chrome

**Comment by jywarren** [comment]
Also - do we need to run `rake sunspot:reindex RAILS_ENV=production` -- because that yielded a 404 error for me (note to @icarito):

```
plots@rs-plots2:~/production$ rake sunspot:reindex RAILS_ENV=production
rake aborted!
RSolr::Error::ConnectionRefused: Connection refused - {:data=>"<?xml version=\"
1.0\" encoding=\"UTF-8\"?><delete><query>type:User</query></delete>", :headers=
>{"Content-Type"=>"text/xml"}, :method=>:post, :params=>{:wt=>:ruby}, :query=>"
wt=ruby", :path=>"update", :uri=>#<URI::HTTP:0x00000009478598 URL:http://localh
ost:8983/solr/default/update?wt=ruby>, :open_timeout=>nil, :read_timeout=>nil, 
:retry_503=>nil, :retry_after_limit=>nil}
```

**Comment by david-days** [comment]
I think it's a routes.rb issue.  Pushing the search button without any entered values sends you to:  

https://publiclab.org/search/

But line 137 is commented out, and all the following routes are looking for a match with something after "search/".

I would recommend moving line 137 `match 'search' => 'searches#new'` to the last entry for search.  This would make the default no-param page go to the "new" view on the controller.  If tests fail at that point, we'd just need to check the code for "new" to make sure it handles empty parameters.

**Comment by jywarren** [comment]
But I did enter a value in the input. Let me try this locally and see what's happening.

**Comment by jywarren** [comment]
I see:
```
Started POST "/searches" for 127.0.0.1 at 2016-09-30 13:25:29 -0400
Processing by SearchesController#create as HTML
  Parameters: {"utf8"=>"�", "authenticity_token"=>"KhB183d+stcIMHAdwE66BWPdZgDtPU5emZQ4Scpl/NA=", "search_record"=>{"key_words"=>"post", "main_type"=>"Notes or Wiki updates", "language"=>"", "min_date"=>"", "max_date"=>""}}
Geokit is using the domain: localhost
  Rendered text template (0.1ms)
Completed 400 Bad Request in 35.2ms (Views: 14.4ms | ActiveRecord: 0.0ms | Solr: 0.0ms)
```

**Comment by jywarren** [comment]
I'm going to try to write (failing) tests to reproduce these errors, and open a PR.

**Comment by jywarren** [comment]
OK -- here is the now-failing test in a PR: https://github.com/publiclab/plots2/pull/856

**Comment by jywarren** [comment]
We'll be addressing this in #1176
