### ISSUE TITLE
(multiple issues) Fix UI flow and debug dashboard location input form

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#8566]
We have a feature where you can add your location from the dashboard -- https://publiclab.org/dashboard (while logged in):

![image](https://user-images.githubusercontent.com/24359/95913284-fd799000-0d71-11eb-9477-e84f5b7dd7e0.png)

You click "Add your location" and a modal popup appears, prompting you:

![image](https://user-images.githubusercontent.com/24359/95913323-0cf8d900-0d72-11eb-9236-853e380e0dfd.png)

Unfortunately, as @Tlazypanda noted, this doesn't really work smoothly, both due to possible UI design gaps (no notification to the user when tags are created) and possibly bugs. @Tlazypanda noted:

> * clicking "Save" doesn't apparently do anything, because you're just dropped back on the dashboard
> * On adding location modal, the slider works by zooming in but when we save it and check it out in the profile page it is saved without any zoom.
> * Also after adding your location it still shows add location on dashboard
> * This is invoked by adding location from dashboard but on clicking share location from profile page nothing happens.
> * Also after adding location for first time, it doesn't seem to update for a second time

Even after fixing this, we also ought to add a system test for adding profile tags - like, one of these modified for the dashboard!

https://github.com/publiclab/plots2/blob/86776c2c72a505b0db563f52d1a8165c36c6eb37/test/system/post_test.rb#L188-L211

We could add one of these assertions afterwards that checks that the profile tags are properly created: 

https://github.com/publiclab/plots2/blob/86776c2c72a505b0db563f52d1a8165c36c6eb37/test/system/tag_test.rb#L40-L51

### Intended workflow

The ideal intended workflow is:

1. See "add a location" on dashboard, click it
2. See modal and check content of one or more of the inputs
3. enter lat/lon and zoom, or use the slider
4. press `Save` and see an alert (maybe?) that says "profile location was saved. Learn more about location privacy" - linking to https://publiclab.org/location-privacy
5. confirm dashboard button now says "View nearby content
6. confirm tags were added and appear on profile page

**Comment by khadija-nur** [comment]
Hi can I work on this issue?

**Comment by tawahpeggy** [comment]
@khadija-nur have you started working on this issue already? if yes we  can work on it together since the issue's description is kind of lengthy. why don't we use this issue as a means of starting our pair pogramming journey.

**Comment by aissshah** [comment]
This looks interesting and I would like to team up as well! @khadija-nur @tawahpeggy

**Comment by khadija-nur** [comment]
That'd be great @tawahpeggy I'm available to work on it tomorrow evening. @mhtien will you be available then?

**Comment by khadija-nur** [comment]
Sorry I've already started working on it with others @tawahpeggy Hopefully another issue comes up soon

**Comment by tawahpeggy** [comment]
Ok no problem.
Hopefully I'll find an issue

**Comment by jywarren** [comment]
Hi all! Thank you so much for your help. I think this may best be completed in a few different parts:

* [ ] clicking "Save" doesn't apparently do anything, because you're just dropped back on the dashboard: let's ensure we add a `flash[:notice]` telling the user that the location was saved! Or, it may require the use of the `noty` helper to make an alert appear in pure Javascript: https://github.com/publiclab/plots2/blob/baa7e7cd335b8325c8194f0740a59449448050d9/app/views/spam2/_nodes.html.erb#L118-L122
* [ ] ensuring that a tag such as `zoom:_____` (like, `zoom:8`) is saved on the profile page once this form is submitted - should be done in [this controller](https://github.com/publiclab/plots2/blob/main/app/controllers/user_tags_controller.rb#L35), i believe!
* [ ] after adding your location it still shows add location on dashboard - we should check if `lat:____` and `lon:____` user tags exist and switch to a button saying `Nearby activity`, linking to a page like https://publiclab.org/map/#6/18/-66 (with `zoom/lat/lon` built into the URL (template here: https://github.com/publiclab/plots2/blob/27a3839154e0cec071860448f99697f9c831042c/app/views/sidebar/_dashboard.html.erb#L20-L28)
* [ ] on clicking share location from profile page nothing happens - let's ensure the button on /profile works too, and write a test to protect it
* [ ] after adding location for first time, it doesn't seem to update for a second time - so, let's be sure that in https://github.com/publiclab/plots2/blob/main/app/controllers/user_tags_controller.rb#L35, we /replace/ location tags, perhaps? this is probably a big enough issue to break out by itself.

Each of these may need a test to protect it, so take a look at the example tests and assertions above!

I recommend folks pick one, and we'll coordinate from here!

**Comment by khadija-nur** [comment]
Thanks for the additional info @jywarren, they're super helpful

**Comment by gauravahlawat81** [comment]
I would like to work on this issue if it's not assigned to someone else. CC: @jywarren

**Comment by gauravahlawat81** [comment]
@jywarren When we  click `Add location` on dashboard, the location doesn't get saved, but when we go on the profile page and the location isn't added yet, `Share your Location` will prompt you to add the location first,after adding location, it indeed saves the location. This seems weird and I will be looking into this deeply!

**Comment by Manasa2850** [comment]
@jywarren clicking on the `Share your Location` button in the profile page does not do anything. (4th item in your checklist)
I would like to take this up and try to fix it.

**Comment by coder645** [comment]
@Manasa2850 sure go ahead! Good luck!

**Comment by gauravahlawat81** [comment]
Hey @Manasa2850 , thanks for the help, I have already started working on this and I would love to collaborate! :+1:

**Comment by Manasa2850** [comment]
Awesome @gauravahlawat81! I just saw your PR regarding saving the location.
Could I work on enabling the `Share your Location` button from the profile page?

**Comment by coder645** [comment]
Sure @Manasa2850 please go ahead and take that up!
Cheers!

**Comment by Manasa2850** [comment]
Thanks @coder645. I'll start working on it then!

**Comment by gauravahlawat81** [comment]
> Could I work on enabling the `Share your Location` button from the profile page?

Sure no problem, I am currently working on displaying `Nearby Activity` button if the location exists!

**Comment by gauravahlawat81** [comment]
@Manasa2850 could you please help me with writing tests for the code that I have written till now ? It seems to me that you are very well versed with writing tests! :smile:

**Comment by gauravahlawat81** [comment]
We can work together on this and I will get to learn a lot from you, I believe! :nerd_face:

**Comment by coder645** [comment]
@gauravahlawat81 I can help you with that mate!

**Comment by gauravahlawat81** [comment]
Thanks @coder645 !

**Comment by Manasa2850** [comment]
Sure @gauravahlawat81. I'm not an expert in this too but I'll definitely try to help!

**Comment by gauravahlawat81** [comment]
@Manasa2850 Couldn't find you on gitter, what's your username there ?

**Comment by coder645** [comment]
@gauravahlawat81 please be respectful of others. 
Not everyone who contributes here is there on Gitter.

**Comment by coder645** [comment]
@cesswairimu could we have some sort of mechanism / code of conduct to ensure people (here @gauravahlawat81 and maybe some other time myself) don't make disrespectful comments and then delete it?
Cheers!

**Comment by cesswairimu** [comment]
We do have a code of conduct, you can find it in the documentation... thanks

**Comment by coder645** [comment]
@gauravahlawat81 I suggest that you take a look at that and not make disrespectful comments from next time onwards.
Cheers!

Thanks @cesswairimu :+1:

**Comment by cesswairimu** [comment]
Great collaboration here @Manasa2850 @gauravahlawat81  :tada: :tada:
