### ISSUE TITLE
Rename /tools to /methods, add redirect and change page title

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#857]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled.

This could be 2-3 first timers issues, or just solve it yourself!

****

Our `/tools` page is now being moved to `/methods`, and the title changed to Methods. We need to:

* change `def tools` method to be `def methods`: https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb#L60-L68
* add back a `def tools` which is just a redirect: `redirect_to '/methods'` in  https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb#L60
* change the title of the page. The template itself is at https://github.com/publiclab/plots2/blob/master/app/views/notes/tools_places.html.erb#L25, but it uses a locale file at https://github.com/publiclab/plots2/blob/master/config/locales/views/notes/tools_places/en.yml#L6 and a matching German one at https://github.com/publiclab/plots2/blob/master/config/locales/views/notes/tools_places/de.yml#L6

(See discussion on this question: https://publiclab.org/notes/liz/09-30-2016/should-tools-be-renamed-to-methods-techniques-or-something-else)

**Comment by mridulnagpal** [comment]
I would like to work on this issue

**Comment by mridulnagpal** [comment]
#1020

**Comment by mridulnagpal** [comment]
@jywarren This one is resolved as well

**Comment by jywarren** [comment]
Superb!
