### ISSUE TITLE
Fix "# more" link so that it expands to show more tags

### ISSUE THREAD

**Issue by Cadreia** [publiclab/plots2#8571]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file "plots2/app/views/tag/_tagging.html.erb" in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

The underlined link text in the sidebar that indicates that there are a certain number of additional tags on a piece of content is clickable but is not actually a link. The "# more" link is expected to expand to show existing tags.
Using the "circle +" actually does expand and show the tags AND provide the "add a tag" box, so the functionality is still available, which is good. However, the broken link should be fixed. 

![github](https://user-images.githubusercontent.com/40563356/95952125-77039380-0def-11eb-8456-b84ddecb8944.png)

Below is the code for the link itself

https://github.com/publiclab/plots2/blob/0c199c6e0450a5d20cc11c0774cc867cb6fc9f61/app/views/tag/_tags.html.erb#L10-L12

You can see a sample of this issue at this link
https://publiclab.org/questions/eustatic/06-30-2020/how-do-i-follow-airplanes-dispersing-corexit-9500-w932h-n38wa-n64766-n64767

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -60,7 +60,7 @@ 
<script>
-  $("#tags-open").click(function(){
+  $("#tags-open, .show-more-tags").click(function(){ 
    $("#tagform").show();
    $("#tags-open").hide();
    $('.more-tags').show();
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by nk183** [comment]
Hello, @Cadreia please can I work on this?

**Comment by Cadreia** [comment]
Hi, @jywarren. I've created this "first-timers-only" issue out of #8490. Can you close #8490 now?

**Comment by Cadreia** [comment]
@publiclab/reviewers can you please get this issue labelled?

**Comment by Cadreia** [comment]
Sure, @nk183. Go ahead. Please let me know if you face any difficulties with this!

**Comment by KarenEfereyan** [comment]
@nk183 you were earlier. 🤣🤣🤣 well done

**Comment by nk183** [comment]
how do I iterate over  tags when "circle +" is expanded

**Comment by nk183** [comment]
where is "add a tag"  functionality

**Comment by Cadreia** [comment]
That has already been implemented. All that you have to do is to replace the line of code highlighted in red with that in green, so that the user can click on either the link(# more) or the (+) button to reveal the rest of the tags

**Comment by nk183** [comment]
@Cadreia ,I have made the pull request please review

**Comment by nk183** [comment]
@Cadreia ,I have made the pull request  #8579   please review

**Comment by Aman2632** [comment]
@Cadreia can i work on it please

**Comment by nk183** [comment]
I have made some commits please review, @Cadreia

**Comment by nk183** [comment]
@Cadreia ,  I have created another pull request please review

**Comment by ebarry** [comment]
Thank you for creating this @Cadreia !!!!
