### ISSUE TITLE
Creating email aliases for googlegroups

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#86]
This will enable us to create nested groups. Nested groups will facilitate region / chapter relationships, and also enable us to more securely email our weekly newsletter to all googlegroups at once. 

for nesting regions and chapters: 

nyc@publiclab.org = plots-nyc@googlegroups.com
bos@publiclab.org = plots-boston@googlegroups.com
gulf@publiclab.org = plots-gulfcoast@googlegroups.com
norcal@publiclab.org = plots-norcal@googlegroups.com
dc@publiclab.org = PLOTS-Baltimore-DC@googlegroups.com
prov@publiclab.org = plots-providence@googlegroups.com
phi@publiclab.org = plots-philadelphia@googlegroups.com
amst@publiclab.org = plots-amsterdam@googlegroups.com
skane@publiclab.org = plots-skane@googlegroups.com
la@publiclab.org = publiclab-la@googlegroups.com
jerusalem@publiclab.org = Publiclab-Jerusalem@googlegroups.com
butte@publiclab.org = plots-butte@googlegroups.com
chi@publiclab.org = public-lab-chicago@googlegroups.com

southeast@publiclab.org = plots-southeast@googlegroups.com
northeast@publiclab.org = publiclab-northeast@googlegroups.com
midwest@publiclab.org = publiclab-midwest@googlegroups.com

**Comment by steviepubliclab** [comment]
Should we merge this with your nested gg comment?

**Comment by ananyo2012** [comment]
@ebarry This will be a tough one as you have to set email address alias for each group and for that you have to co-ordinate with all the admins of each group. But it might be easier if admin of each groups are same. Here is how to add a domain alias to a G suite: https://support.google.com/a/answer/53295?hl=en and after that we need to add the email aliases of each group: https://support.google.com/a/answer/2727156?hl=en

**Comment by ananyo2012** [comment]
@ebarry Your thoughts on this?

**Comment by jywarren** [comment]
Liz is traveling in China at the moment, and we're about to have a holiday
this week in the US -- so she probably won't be able to reply until
Monday/Tuesday at the earliest. Thanks!

**Comment by ananyo2012** [comment]
Oh ok its alright. Will wait for her reply.

**Comment by gauravano** [comment]
@ebarry @steviepubliclab @jywarren any updates regarding this issue? Thanks!

**Comment by jywarren** [comment]
I think we can close as we are moving to "forum-like" subscriptions and away from google groups!
