### ISSUE TITLE
Weekly Community Check-In # 79 - Draft Your Outreachy Proposal

### ISSUE THREAD

**Issue by RuthNjeri** [publiclab/plots2#8619]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Begin Drafting Your Outreachy Proposal

We have had a huge number of new contributors having their first-timer issues being merged! 🎉 
The Outreachy application deadline is only 2 weeks away and it is beneficial to start drafting a proposal in order for the mentors to give feedback. 
To begin your proposal, refer to this [link](https://publiclab.org/notes/cess/10-02-2020/call-for-proposals-outreachy-winter-2020).

As always, if you are stuck, overwhelmed, and have questions feel free to reach out [here](https://github.com/publiclab/plots2/issues/8448). We are all happy to help. 

You can also join the discussions happening at [Gitter](https://gitter.im/publiclab/publiclab) to reach out for new first timer issues or even find someone to pair program with. 

### Thank you note to focus issues contributors
A huge thank you to everyone who completed an FTO, reviewed PRs, and provided support to each other. A huge shoutout to those who were able to have their PRs merged in the last week, 🥇 @nk183, 🥇 @KarenEfereyan, 🥇 @stacytonui,
🥇 @mhtien, 🥇 @khadija-nur, 🥇 @fiona-byte, 🥇 @jywarren, 🥇 @dharmelolar, 🥇 @Shreets, 🥇 @noi5e 

And to all those who provided reviews on the PRs as well 🥇 @jywarren, 🥇 @Sagarpreet, 🥇 @Cadreia, 🥇 @Tlazypanda, 
 🥇  @cesswairimu 

To everyone following the conversations, learning, and providing support, we appreciate you too 🥇 

## Next Check-in
If you would like to open the next check-in...Leave a comment below. We are happy to help if it's your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by ebarry** [comment]
Happy October everyone 🎃
I am going back through old first-timers-only issues and closing them when the original issue has already been resolved for some reason such as the design of the page changing and eliminating the issue in that way. It's really encouraging to see so much energy in the repos, and so much energy going to orient and guide newer contributors and reviewing their contributions.

**Comment by Cadreia** [comment]
@cesswairimu, I would love to create next week's check-in, if it's okay.

**Comment by stacytonui** [comment]
Thankyou!! @RuthNjeri 
Also Thankyou @cesswairimu and @jywarren who have made the whole contribution process very easy esp to first time contributors like me

**Comment by Shreets** [comment]
Thank you very much @RuthNjeri for this great check-in! 
It was real awesome to get first crack at open source with Public Lab. 
Thanks to @cesswairimu , @jywarren for being vigilant to our calls for help and for creating ever-so-encouraging environment for us to work and learn in.
Really appreciate it!

@Cadreia - good luck with the check-in next week :)

**Comment by Cadreia** [comment]
@Shreets Thanks!

**Comment by cesswairimu** [comment]
Sure thing @Cadreia thanks :tada:

**Comment by dldisha** [comment]
@RuthNjeri, great work creating this week's check-in :tada:

**Comment by KarenEfereyan** [comment]
Thank you so much to the entire team at Public Lab. Working with you all has been awesome. A big shout out to the mentors for their unending support. Another big shout out to all the contributors on this project. You all are amazing. @RuthNjeri I would like to create the check in for next week, although I am not particularly sure what it'll involve but I'm counting on the support of everyone.

**Comment by fiona-byte** [comment]
Thank you @RuthNjeri for creating this week's check-in.
I really want to appreciate the mentors and the entire Public Lab team for their support.
A big shout out to @cesswairimu and @jywarren for creating a really friendly environment to learn and also for their unending encouragement.

Thank you! 🎉

**Comment by RuthNjeri** [comment]
Thank you @KarenEfereyan, @Cadreia already mentioned she would like to create next week's check-in, maybe you could do it the week after? Also, when drafting one, you can always consult @cesswairimu she is really helpful in giving feedback.

**Comment by kamzzy** [comment]
thank you everyone that made it easier for first timers like me to contribute to open source

**Comment by jywarren** [comment]
It's so wonderful to see you all! SO MUCH appreciation for those who've taken their first step -- and to those who've helped someone else do the same! Thank you @RuthNjeri for opening this and for the excellent 🥇🥇🥇🥇🥇

It's also wonderful to see people volunteering to open check-ins. We often coordinate in https://github.com/publiclab/plots2/issues/5627 (which is usually pinned but we replaced it with the Welcome Outreachy issue!)

**Comment by IjayAbby** [comment]
I really want to appreciate the mentors and the entire Public Lab team for their support.
A big shout-out to @cesswairimu and @jywarren for coordinating together to ensure no one is left behind on the on-boarding process and always replying on-time to any concerns any of us had. They also created friendly first-timer issues which make it easier for anyone to take part regardless of your experience in coding.
Thank you @RuthNjeri for creating this week's check-in.
Thank you to everyone who has taken the time to contribute to the project.

**Comment by bhamster07** [comment]
Thanks so much to everyone for all the fantastic work! As one of the Public Lab staff who uses the website everyday, I greatly appreciate all that you're doing ❤️

**Comment by fiona-byte** [comment]
Hi @jywarren and @cesswairimu,
I noticed a something on the Public Lab website. I think the scroll-to-top button should be hidden when the page is at the top and should be displayed when the page is moved down a little. A little animation could be added to make this look better

**Comment by cesswairimu** [comment]
Hey @fiona-byte, good catch, thanks. We have a issue for this here https://github.com/publiclab/plots2/issues/7454 if you would like to work on it. Thanks

**Comment by fiona-byte** [comment]
I'd love to work on it. Thank you @cesswairimu

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/8676 . Thanks everyone
