### ISSUE TITLE
Remove sudo from `sudo npm install -g bower`

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plots2#862]
In [README.md](https://github.com/publiclab/plots2/blob/master/README.md#L101) sudo should be removed from the command `sudo npm install -g bower` as it is considered a bad practice. 

### References (to name a few): 

* https://docs.npmjs.com/getting-started/fixing-npm-permissions
* https://coderwall.com/p/t2mc9g/don-t-sudo-npm
* https://jesse.sh/sudo-npm-install/
* https://johnpapa.net/how-to-use-npm-global-without-sudo-on-osx/
* http://www.competa.com/blog/2014/12/how-to-run-npm-without-sudo/

If possible, we should also include a link (possibly to the official npm video tutorial) to help contributors facing this problem overcome it.

**Comment by ryzokuken** [comment]
@jywarren could i fix this one myself? :grinning:

**Comment by jywarren** [comment]
yes, please, that would be great!

**Comment by jywarren** [comment]
Addressed in #866 (just linking to the PR)
