### ISSUE TITLE
Change http to https in drupal_content_type_map.rb

### ISSUE THREAD

**Issue by noi5e** [publiclab/plots2#8629]
🔊  **NOTE:** _(This issue is a part of Issue #8587 and has been claimed at the time of writing this issue. However, there are several places in the codebase where this change needs to happen, and issues haven't been made for each instance yet. If you are a first-time contributor, please refer to #8587 for more info on how to find instances of 'http' in the codebase. From there, you can make your own FTO issue and pull request to solve it.)_

---

Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file /app/models/drupal_content_type_map.rb (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
-    l = "<a href='http://creativecommons.org/publicdomain/zero/1.0/'>Public Domain</a>" if field_license_value == 'publicdomain'
-    l = "<a href='http://creativecommons.org/licenses/by/3.0/'>CC-BY</a>" if field_license_value == 'cc-by'
-    l = "<a href='http://creativecommons.org/licenses/by-sa/3.0/'>CC-BY-SA</a>" if field_license_value == 'cc-by-sa'
+    l = "<a href='https://creativecommons.org/publicdomain/zero/1.0/'>Public Domain</a>" if field_license_value == 'publicdomain'
+    l = "<a href='https://creativecommons.org/licenses/by/3.0/'>CC-BY</a>" if field_license_value == 'cc-by'
+    l = "<a href='https://creativecommons.org/licenses/by-sa/3.0/'>CC-BY-SA</a>" if field_license_value == 'cc-by-sa'
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by noi5e** [comment]
@cesswairimu @jywarren, please assign @yashmohan100 to work on this issue, they claimed it in #8587.

**Comment by cesswairimu** [comment]
For some reason I can't see @yashmohan100 when I search on the assignee tab, but its all your @yashmohan100 and I have labelled it as assigned. Thanks so much @noi5e

**Comment by Muskan-Malhotra** [comment]
May I contribute to this issue?

**Comment by yashmohan100** [comment]
> For some reason I can't see @yashmohan100 when I search on the assignee tab, but its all your @yashmohan100 and I have labelled it as assigned. Thanks so much @noi5e

is is still open ?? sorry i was away for a week. will contribute for sure

**Comment by cesswairimu** [comment]
Yes its still, go ahead. Thanks

**Comment by Suiiyush** [comment]
If anyone has not claimed this yet then can I work on this issue? 
I am a first timer this will be my first contribution on Github

**Comment by yashmohan100** [comment]
Hi @Suiiyush , i am working on this. @cesswairimu has told me to do some changes...i am still figuring them out.
Thanks !!

**Comment by cesswairimu** [comment]
Hi @yashmohan100  I didn't realize you were having prob with that.
Here are steps you can follow to easily create a branch on the web

- Navigate to https://github.com/yashmohan100/plots2. 
- Click on the branch dropdown, that brings a search bar. 
- Type the name of the new branch, e.g `change-http-to-https`
- Click on the *create branch* text that appears below 
- Once created, it will bring you a compare and PR on the top, click on it and create the PR.

Here is a gif for the same.

![new-branh](https://user-images.githubusercontent.com/17081074/97571914-0072b280-19f9-11eb-8f9a-b077b19ff79a.gif)

Please ping me if stuck. Thanks

**Comment by yashmohan100** [comment]
> Hi @yashmohan100 I didn't realize you were having prob with that.
> Here are steps you can follow to easily create a branch on the web
> 
>     * Navigate to https://github.com/yashmohan100/plots2.
> 
>     * Click on the branch dropdown, that brings a search bar.
> 
>     * Type the name of the new branch, e.g `change-http-to-https`
> 
>     * Click on the **create branch** text that appears below
> 
>     * Once created, it will bring you a compare and PR dialog on the top, click on it and create the PR.
> 
> 
> Here is a gif for the same.
> 
> ![new-branh](https://user-images.githubusercontent.com/17081074/97571914-0072b280-19f9-11eb-8f9a-b077b19ff79a.gif)
> 
> Please ping me if stuck. Thanks

Actually, I was having issue with rebase and what you meant by it ?

**Comment by cesswairimu** [comment]
Oh I see, I think rebasing will have an issue in your case because you are using the main branch.
Though you could try doing `git rebase -i upstream/main` _assuming your remote for publiclab/plots2 is upstream, save and exit and push your branch

**Comment by yashmohan100** [comment]
thanks. i will do this by today evening.
