### ISSUE TITLE
gem mysql2 throws error while performing `bundle install`

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plots2#863]
**PROBLEM:** The mysql2 gem throws an error during installation. Here's a short log.

```
ERROR:  Error installing mysql2:
    ERROR: Failed to build gem native extension.

    /home/ryzokuken/.rvm/rubies/ruby-2.1.2/bin/ruby -r ./siteconf20161002-9251-jf4wv4.rb extconf.rb
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for rb_thread_blocking_region()... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_hash_dup()... yes
checking for rb_intern3()... yes
checking for mysql_query() in -lmysqlclient... no
-----
libmysqlclient is missing. Trying again with extra runtime libraries...
-----
checking for main() in -lm... yes
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lz... yes
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lsocket... no
checking for main() in -lnsl... yes
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lmygcc... no
-----
libmysqlclient is missing. You may need to 'apt-get install libmysqlclient-dev' or 'yum install mysql-devel', and try again.
-----
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/home/ryzokuken/.rvm/rubies/ruby-2.1.2/bin/ruby
    --with-mysql-dir
    --without-mysql-dir
    --with-mysql-include
    --without-mysql-include=${mysql-dir}/include
    --with-mysql-lib
    --without-mysql-lib=${mysql-dir}/lib
    --with-mysql-config
    --without-mysql-config
    --with-mysql-dir
    --without-mysql-dir
    --with-mysql-include
    --without-mysql-include=${mysql-dir}/include
    --with-mysql-lib
    --without-mysql-lib=${mysql-dir}/lib
    --with-mysqlclientlib
    --without-mysqlclientlib
    --with-mlib
    --without-mlib
    --with-mysqlclientlib
    --without-mysqlclientlib
    --with-zlib
    --without-zlib
    --with-mysqlclientlib
    --without-mysqlclientlib
    --with-socketlib
    --without-socketlib
    --with-nsllib
    --without-nsllib
    --with-mysqlclientlib
    --without-mysqlclientlib
    --with-mygcclib
    --without-mygcclib

extconf failed, exit code 1
```

**SOLUTION:** 

`sudo apt install libmysqlclient-dev` OR `sudo yum install mysql-devel`

**Comment by ryzokuken** [comment]
@jywarren Was setting up the project locally, and this is one of the few issues I found. Maybe I could help improve the documentation a little?

**Comment by jywarren** [comment]
Hi - we've considered creating a second README for prerequisites -- perhaps
this and other platform-specific tips could go there? Thanks!

**Comment by jywarren** [comment]
I also think that this is a pretty common error to run into when using mysql. (BTW, isn't sqlite a simpler viable option?) So if there's simply an up to date guide we could link to on installing it, that might be best, rather than keeping our own docs up to date.

**Comment by ryzokuken** [comment]
The thing is -- the ruby gem requires the library in your system. I'd highly suggest either adding the library to the list of prerequisites or maybe work on making automated shell scripts for installation on different environments. Eg. I'd only need to run `sudo ./install_ubuntu.sh`. I think that'd be a great thing to work on.

**Comment by ananyo2012** [comment]
@ryzokuken Actually the thing is we use sqlite for development. mysql is used in production and the gem has been grouped under production. So while installing gems in development use `bundle install --without production` as mentioned in the [Installation](https://github.com/publiclab/plots2#installation) section. That will work smoothly.

For installing the prerequisites follow the [Prerequisites](https://github.com/publiclab/plots2#prerequisites) section. Well we haven't included the mysql dev package in the prerequisites since it is not required in development.

As per I think it is better to install the prerequisites separately and not using a installation script since the commands vary for different environments and we have o maintain a separate one for each which is not a good idea. Since we do not want to restrict the usage for some environments only. Also it is always good to install them separately in development since it will be easy to detect any installation failures and also get a feel of it for first timers :blush:

**Comment by ryzokuken** [comment]
@ananyo2012 I did use `--without production`. I guess it just skips the production group and as mysql also has its own group, that's why it's being installed. Anyway, its still throwing the Solr error in my local PC as well as Cloud9. I have sent the log on the gitter channel. Please help me fix it so that I can contribute to the real thing rather than make PRs for the README :P

**Comment by ananyo2012** [comment]
Uh ok let me check the gitter channel

**Comment by ananyo2012** [comment]
OK we recently made some PRs #861 and #868 that should fix these issues both in development as well as in cloud9. But for now can you sequentially mention the steps right from the start so that I can catch what should be the issue.

**Comment by ryzokuken** [comment]
I'll give you the exact history when I reach home tonight. But AFAIK I followed the steps on the README sequentially

**Comment by ryzokuken** [comment]
@ananyo2012 Here's my exact `history`:

```
  301  bundle install --without production
  302  cp db/schema.rb.example db/schema.rb
  303  cp config/database.yml.sqlite.example config/database.yml
  304  rake db:setup
  305  rails generate sunspot_rails:install
  306  bundle exec rake sunspot:solr:start
  307  bundle exec rake sunspot:reindex
  308  bundle exec rake sunspot:solr:start
  309  bundle exec rake sunspot:reindex
  310  rake db:setup
  311  passenger start
  312  bower install
  313  passenger start
  314  rails generate sunspot_rails:install
  315  bundle exec rake sunspot:solr:start
  316  bundle exec rake sunspot:reindex
  317  rake db:setup
```

**Comment by ananyo2012** [comment]
Ok I see a lot of repeated steps. According to the error log you gave earlier migrations were running fine. The problem was in seeding the data. So presently you should start the solr server before running db:setup. So these should be the steps for a fresh copy after installing all prerequisites.
```
$ cd plots2
$ bundle install --without production
$ cp db/schema.rb.example db/schema.rb
$ cp config/database.yml.sqlite.example config/database.yml
$ bower install
$ rails generate sunspot_rails:install
$ bundle exec rake sunspot:solr:start
$ rake db:setup
$ bundle exec rake sunspot:reindex
$ passenger start
```

For testing you should stop the solr server in development using `rake sunspot:solr:stop`. Then run
```
$ rake sunspot:solr:start RAILS_ENV=test
$ rake test:all
```

**Comment by ananyo2012** [comment]
@ryzokuken I suggest you too look at our [help-wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. There are a lot of them. Perhaps if you are stuck which one to start with I can help select one.

**Comment by ryzokuken** [comment]
@ananyo2012 I have definitely been thinking of taking the plunge as soon as I successfully setup the project. 

According to my interpretation of your guidelines, I'd `rm -rf plots2/`, re-clone the repo and try these commands in exactly this order. 

Thanks.

**Comment by ananyo2012** [comment]
@ryzokuken No you dont have to remove the repository entirely. Just ensure all solr instances are stopped and just remove the development.sqlite and test.sqlite files. Ad if you have copied the database.yml and schema.rb files just skip those steps.

**Comment by jywarren** [comment]
Apologies for the difficulties with the solr installation -- they're new, and we're doing our best to work through them in the PRs Ananyo linked to above. We definitely hope to have the install process ironed out and simpler within the next week and a half, so thank you for your patience. 

Also, thanks to Ananyo for helping out here -- I'm currently in a week long staff retreat and am a little less able to provide support than usual. 

However, I'd be happy to accept a PR with more guidance on mysql/sqlite on the README.

**Comment by ryzokuken** [comment]
Thanks @ananyo2012! That seemed to have worked like a charm. I will run some more tests and come back here.

**Comment by ryzokuken** [comment]
EDIT: Solr is up and running, but when I try posting a question, another error pops up. Here's the message. 

```
AbstractController::DoubleRenderError (Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".):
  app/controllers/application_controller.rb:143:in `alert_and_redirect_moderated'
  app/controllers/questions_controller.rb:27:in `show'
```

**Comment by ryzokuken** [comment]
I see you guys have a `Dockerfile`. If it's running properly, we won't need to setup dependencies and stuff again and again.

**Comment by jywarren** [comment]
Sorry for the radio silence. I hope to have a look at this thread again
today or tomorrow-- back from our staff retreat now. Thanks!!!

**Comment by jywarren** [comment]
Hi, Ryzokuken - could you rebase on top of the latest master and open a pull request? Then I can see the error and the exact diffs against my version (where tests are passing). I'm not sure there is a test for posting a question, so if we're not catching the double render error you see, we should add one to properly catch that error. I looked around in here and didn't see a question posting test: 

https://github.com/publiclab/plots2/blob/master/test/functional/notes_controller_test.rb

It should be the same as testing `notes_controller.rb`'s "create" method, but should trigger this line: 

https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb#L156

**Comment by ryzokuken** [comment]
@jywarren: merged my local master with upstream/master. 
Here's the error:
```
Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".
```
in
```
app/controllers/application_controller.rb:143:in `alert_and_redirect_moderated'
app/controllers/questions_controller.rb:27:in `show'
```

**Comment by jywarren** [comment]
It's odd since I'm not seeing that test failure -- but the solution is pretty easy:

```ruby
    redirect_to "/"
    return
```

Just after line 143 of `app/controllers/application_controller.rb`

**Comment by ryzokuken** [comment]
@jywarren did yours throw an issue too?

**Comment by jywarren** [comment]
It's odd, no -- but I've merged a good bit of code since, so you might want to rebase on top of the latest master and try again. https://travis-ci.org/publiclab/plots2/builds/ shows tests on all recent PRs and the latest master.

**Comment by ryzokuken** [comment]
@jywarren I will. Also, line 143 was already `redirect_to "/"` ...? I added a `return` after that but to no avail. I also added a return after a `redirect to "/"` higher above the function, but still no. 

This is another reason to use containers. That way, we'd all use the same environment, and the same environment would be used in production so you won't ever have a "doesn't work here" issue. Also, that would cut down the fuss of installing dependencies locally. It'd take care of them.

**Comment by jywarren** [comment]
Hi - can you push up a pull request with your latest code? That way we are
using identical containers, and can look at exactly what code differs
between your branch and master -- and see how tests run on both in
identical environments. Thanks for your hard work on this!

**Comment by ryzokuken** [comment]
@jywarren Github does not allow me to create a PR because my master is identical to your master. Maybe ill try running tests locally?

**Comment by jywarren** [comment]
Huh - are you developing in the master branch? You should be able create a
PR based on a named feature branch, with your additional changes; see
https://publiclab.org/wiki/contributing-to-public-lab-software#A+sample+git+workflow
and use `git status` to check what branch you're currently on.

**Comment by ryzokuken** [comment]
I was just checking if the repo was working properly in master.

Just another check:
I do a `passenger start` to start the server. That's it, right? Maybe I'm missing something... Upto the point I typed this, all tests were passing.

**Comment by jywarren** [comment]
Hmm, well if you push up a PR, I can pull it to my local and see what's
going on. You or I can also add a test to run through that section of code,
to try to trigger the same error in a test -- that'll help us be on the
same page.

**Comment by ryzokuken** [comment]
Okay... I'll do that right now

**Comment by ryzokuken** [comment]
cannot create a PR still... 
![screenshot from 2016-10-10 21-56-08](https://cloud.githubusercontent.com/assets/13121330/19243245/71063b88-8f34-11e6-9aea-389075a76a84.png)

**Comment by jywarren** [comment]
That's so odd -- are you sure you've run `git push origin sample-branch` so
there's a copy of your branch on Github's servers?

**Comment by ryzokuken** [comment]
there is... that's why I could compare it in the first place...

**Comment by jywarren** [comment]
It seems like, viewing
https://github.com/ryzokuken/plots2/tree/sample-branch, there are no new
commits there. Are your changes committed locally before you're pushing up?
No worries, we'll solve this!

**Comment by jywarren** [comment]
Was this figured out then? Sorry, just want to close out old issues, but feel free to open a new one about your specific issue if it's unresolved. Thanks!!
