### ISSUE TITLE
Change http to https in notify_moderators_of_spam.html.erb

### ISSUE THREAD

**Issue by noi5e** [publiclab/plots2#8630]
🔊  **NOTE:** _(This issue is a part of Issue #8587 and has been claimed at the time of writing this issue. However, there are several places in the codebase where this change needs to happen, and issues haven't been made for each instance yet. If you are a first-time contributor, please refer to #8587 for more info on how to find instances of 'http' in the codebase. From there, you can make your own FTO issue and pull request to solve it.)_

Please see #8587 for more context behind this issue.

**Comment by noi5e** [comment]
@cesswairimu @jywarren , @Kennygrace needs to be assigned to this issue, they have an open PR at https://github.com/Kennygrace/plots2/pull/1.

I decided not to type up extensive issue notes if the contributor already has an open PR, I thought it would be overkill since it seems as if they don't need the help.

**Comment by cesswairimu** [comment]
Sounds good, thanks @noi5e

**Comment by Kennygrace** [comment]
@noi5e  This is what I worked on, and I made a  PR already, should I do it again?

**Comment by Muskan-Malhotra** [comment]
May I take up this issue if it is available?

**Comment by noi5e** [comment]
@Kennygrace no definitely don't do it again! I've linked to your PR here, so hopefully @jywarren or someone else will review it and merge it soon.

**Comment by cesswairimu** [comment]
@Kennygrace, it seems you made the pull request on your repo, you can create one on plots2. Thanks

**Comment by cesswairimu** [comment]
You can use this link https://github.com/publiclab/plots2/compare/main...Kennygrace:Kennygrace-patch-1

**Comment by Kennygrace** [comment]
I've done it @cesswairimu
