### ISSUE TITLE
Change http to https in notify_moderators_of_comment_spam.html.erb

### ISSUE THREAD

**Issue by noi5e** [publiclab/plots2#8631]
🔊  **NOTE:** _(This issue is a part of Issue #8587 and has been claimed at the time of writing this issue. However, there are several places in the codebase where this change needs to happen, and issues haven't been made for each instance yet. If you are a first-time contributor, please refer to #8587 for more info on how to find instances of 'http' in the codebase. From there, you can make your own FTO issue and pull request to solve it.)_

Please see #8587 for more context behind this issue.

**Comment by noi5e** [comment]
@cesswairimu @jywarren, please assign @amanda-ariyaratne to this issue. They have an open PR at https://github.com/publiclab/plots2/pull/8593.

I decided not to type up extensive issue notes if the contributor already has an open PR, I thought it would be overkill since it seems as if they don't need the help.

**Comment by amanda-ariyaratne** [comment]
Hello, I have opened a [pull request](https://github.com/publiclab/plots2/pull/8593) to this issue linking the issue [#8587](https://github.com/publiclab/plots2/issues/8587).
It is awaiting review.
