### ISSUE TITLE
Change http to https in _history.html.erb

### ISSUE THREAD

**Issue by noi5e** [publiclab/plots2#8632]
🔊  **NOTE:** _(This issue is a part of Issue #8587 and has been claimed at the time of writing this issue. However, there are several places in the codebase where this change needs to happen, and issues haven't been made for each instance yet. If you are a first-time contributor, please refer to #8587 for more info on how to find instances of 'http' in the codebase. From there, you can make your own FTO issue and pull request to solve it.)_

---

Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file /app/views/notes/_history.html.erb (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
-    <script src="http://d3js.org/d3.v3.min.js"></script>'publicdomain'
+   <script src="https://d3js.org/d3.v3.min.js"></script>'publicdomain'
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by noi5e** [comment]
@cesswairimu @jywarren Please assign @MinervaLong to this issue.

**Comment by sleekyom** [comment]
Can i take the task if it's still available?

**Comment by noi5e** [comment]
@sleekyom, @MinervaLong was the first to claim it in #8587, but I think if it's still open in 48 hours, comment again?

**Comment by sleekyom** [comment]
Sure!
Thanks

**Comment by MinervaLong** [comment]
Hello @noi5e @jywarren @cesswairimu   I'm still interested in this issue, please could you assign it to me? Thank you :)

**Comment by noi5e** [comment]
@MinervaLong okay good to know you're still interested... You already reserved this in the other thread, so please go ahead and work on your pull request! And leave a comment here or in Gitter if you need help.

**Comment by cesswairimu** [comment]
Thanks everyone :tada:
