### ISSUE TITLE
Change http to https in db/seeds.rb

### ISSUE THREAD

**Issue by noi5e** [publiclab/plots2#8633]
🔊  **NOTE:** _(This issue is a part of Issue #8587 and has been claimed at the time of writing this issue. However, there are several places in the codebase where this change needs to happen, and issues haven't been made for each instance yet. If you are a first-time contributor, please refer to #8587 for more info on how to find instances of 'http' in the codebase. From there, you can make your own FTO issue and pull request to solve it.)_

Please see #8587 for more context behind this issue.

**Comment by noi5e** [comment]
@cesswairimu @jywarren please assign @MadhaviG97 to this issue, their open PR is at https://github.com/publiclab/plots2/pull/8597.

I decided not to type up extensive issue notes if the contributor already has an open PR, I thought it would be overkill since it seems as if they don't need the help.

**Comment by bibbudata** [comment]
@noi5e if it is still available can i take it up? #7683

**Comment by noi5e** [comment]
Hi all, @MadhaviG97 claimed this issue in the other thread, and submitted a PR, so I believe their PR should take priority. @jywarren

**Comment by SARVESHKHANDELWAL** [comment]
Can i work on this issue???

**Comment by cesswairimu** [comment]
Hi @SARVESHKHANDELWAL, looks like @MadhaviG97 is already working on this one. Thanks

**Comment by IC1101Virgo** [comment]
Heya! Can I work on this issue? 😸
