### ISSUE TITLE
Questions vs. Answers bar chart not appearing on tag stats pages like /tag/air-quality/stats

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#8641]
https://publiclab.org/tag/air-quality/stats shows the Questions Answered vs. Unanswered heading, but seems to need a tweak to its controller code to match the version at https://publiclab.org/stats

Here is the working code for /stats:

https://github.com/publiclab/plots2/blob/27a3839154e0cec071860448f99697f9c831042c/app/controllers/stats_controller.rb#L44-L45

And it shows up like this:

![Screen Shot 2020-10-20 at 12 42 28 PM](https://user-images.githubusercontent.com/24359/96617531-c0f9e700-12d1-11eb-91c6-bc10d01f68b5.png)

Unfortunately the code for the tag-specific stats page is different:

https://github.com/publiclab/plots2/blob/27a3839154e0cec071860448f99697f9c831042c/app/controllers/tag_controller.rb#L524-L529

And it outputs code which doesn't seem readable by javascript -- it seems like it's dumping a pure Ruby object out:

```
var questions = [{21284=&gt;1, 21662=&gt;5, 21663=&gt;5, 21664=&gt;5, 21717=&gt;4, 22308=&gt;1, 22309=&gt;1, 22310=&gt;1, 22415=&gt;1, 22682=&gt;1, 22751=&gt;5, 22775=&gt;7, 22828=&gt;1, 22967=&gt;3, 23083=&gt;3, 23277=&gt;3, 23504=&gt;7, 23522=&gt;3, 23558=&gt;5, 23575=&gt;6, 23581=&gt;4, 23673=&gt;4, 23732=&gt;1, 23738=&gt;4, 23805=&gt;2, 23867=&gt;3, 23888=&gt;4, 24024=&gt;2, 24025=&gt;3, 24026=&gt;4, 24042=&gt;2, 24591=&gt;6, 24644=&gt;3, 24755=&gt;2}];
--
  | var answers = [{21284=&gt;13, 21662=&gt;15, 21663=&gt;10, 21664=&gt;25, 21717=&gt;24, 22308=&gt;2, 22309=&gt;1, 22310=&gt;5, 22415=&gt;5, 22682=&gt;2, 22751=&gt;15, 22775=&gt;49, 22828=&gt;4, 22967=&gt;24, 23083=&gt;9, 23277=&gt;15, 23504=&gt;35, 23522=&gt;3, 23558=&gt;65, 23575=&gt;24, 23581=&gt;8, 23673=&gt;16, 23732=&gt;3, 23738=&gt;12, 23805=&gt;8, 23867=&gt;3, 23888=&gt;8, 24024=&gt;2, 24025=&gt;9, 24026=&gt;8, 24042=&gt;10, 24591=&gt;24, 24644=&gt;6}];
  | var unanswered = [ questions[0] - answers[0] ];
```

Let's fix this! The template code is the same, so if we fix the controller code we should get the bar chart appearing correctly for both.

**Comment by nstjean** [comment]
I'll take a look at this. :)
