### ISSUE TITLE
Discussion: Update .rubocop_shopify_styleguide.yml

### ISSUE THREAD

**Issue by RuthNjeri** [publiclab/plots2#8646]
When I run `rubocop -a app/controllers/notes_controller.rb` or `rubocop -a <any other file>` I receive a series of errors from that show that the `.rubocop_shopify_styleguide.yml` has obsolete configurations. 

Should it be updated? 

![Screenshot 2020-10-20 at 21 46 14](https://user-images.githubusercontent.com/7622875/96631069-88342f00-131e-11eb-97c9-0cffd3764fa3.png)

Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [rubocop_shopify_styleguide.yml](https://github.com/publiclab/plots2/blob/main/.rubocop_shopify_styleguide.yml) in the `PLOT2` repository (press the little pen Icon) and update any errors that show that `rubocop_shopify_styleguide.yml` contains deprecated lines of configuration. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by RuthNjeri** [comment]
Tagging @jywarren and @cesswairimu in the discussion above.

**Comment by h20190907** [comment]
Please assign this issue to me. I am new to the open-source community and looking forward to opportunities to contribute. Thanks in advance!

**Comment by nk183** [comment]
can I work on this issue ?

**Comment by RuthNjeri** [comment]
Hi @nk183, the issue hasn't been given a "go ahead" yet by @jywarren and @cesswairimu, it's still a discussion.. 
If approved, @h20190907 will be assigned since he reached out first...however, in the meantime, both of you can mention that you are looking for an issue to work on  [here](https://github.com/publiclab/plots2/issues/8448#issuecomment-713519173)

**Comment by cesswairimu** [comment]
Hey thanks @RuthNjeri for opening this. Yeah we can try it out with one file see how travis and codeclimate will behave.

@h20190907 you can go ahead lets start with file Ruth suggested notes_controller.
@nk183  you could keep an eye on how this goes if successful we can move to other files.

Thanks everyone

**Comment by h20190907** [comment]
Thanks a lot, @cesswairimu @RuthNjeri, I will start working on this, and will keep posting the updates here

**Comment by KarenEfereyan** [comment]
@RuthNjeri what exactly is rubocorp?

**Comment by RuthNjeri** [comment]
Hi @KarenEfereyan, Rubocop is usually used to format the code, or ensure that you are using the correct coding standards usually described in a config file within the app files for example `rubocop.yml`

If for instance you want to autocorrect a particular file, maybe the indentation is off or your method names are wrong, you can run Rubocop on that file and it will correct it for you.. you can read more about it [here](https://github.com/rubocop-hq/rubocop) it is usually installed as a gem.

**Comment by KarenEfereyan** [comment]
> Hi @KarenEfereyan, Rubocop is usually used to format the code, or ensure that you are using the correct coding standards usually described in a config file within the app files for example `rubocop.yml`
> 
> If for instance, you want to autocorrect a particular file, maybe the indentation is off or your method names are wrong, you can run Rubocop on that file and it will correct it for you.. you can read more about it [here](https://github.com/rubocop-hq/rubocop) it is usually installed as a gem.

Nice. Similar to lint rules in yarn, right? Thanks for explaining

**Comment by noi5e** [comment]
Thanks so much for opening this @RuthNjeri, I also discovered this a few months back when I was trying to lint files!

Tagging @jywarren and @Tlazypanda as well to put this on their radar as a potential source of FTOs that's very useful to the repo.

**Comment by kunmi02** [comment]
@TildaDares and @jywarren I think this pull request  https://github.com/publiclab/plots2/pull/10877 actually closed this issue. I think it is safe to close this issue

**Comment by TildaDares** [comment]
Resolved in #10877
