### ISSUE TITLE
Double pagination on tags questions

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#8674]
Double pagination here https://publiclab.org/questions/tag/blog, 
we should have a single pagination

![Screenshot from 2020-10-24 15-32-04](https://user-images.githubusercontent.com/17081074/97081932-6d0f3b00-160e-11eb-925c-15151bbc0b3a.png)

**Comment by Cadreia** [comment]
Can I work on this?

**Comment by cesswairimu** [comment]
Go ahead @Cadreia, thanks

**Comment by Cadreia** [comment]
@cesswairimu Alright. I also noticed on large screens, paginated numbers still exist when there's no content to display
