### ISSUE TITLE
question tag doesn't show up while posting a question

### ISSUE THREAD

**Issue by ananyo2012** [publiclab/plots2#869]
### What happened just before the problem occurred

While posting a question by clicking the `Ask Question` link the `question:question` power tag doesn't appear which used to appear earlier. This should be present else the user might forget to add that tag and the note won't be published as a question since for a note to be a question it must have a `question :topic` power tag
### Relevant URLs

https://publiclab.org/post?tags=question:question&template=question&redirect=question (Login required)
### PublicLab.org username

ananyo2012
### Browser, version, and operating system

Google Chrome on Ubuntu 16.04 LTS

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by pdhixenbaugh** [comment]
This affected me as well, and led me to create a few research notes when I thought I was creating questions.

Can we add a sentence somewhere saying something like "Ask a question by tagging this post "question:topic" replacing topic with a tag the question relates to." ?

# PublicLab.org username

pdhixenbaugh

# Browser, version, and operating system

Firefox 49 on Windows 10.

**Comment by jywarren** [comment]
Where did you click the Ask a Question button? Just want to track on what pages this problem is occurring, and the matching code.  Thanks!

**Comment by jywarren** [comment]
Pages like this? https://publiclab.org/notes/imvec/11-15-2016/fresh-air-collector

That seems to lead to: https://publiclab.org/post?template=question&tags=question:generalcalibration,sensors,open-air,response:13706

The `question:generalcalibration` tag is a bug already fixed but not published, but it does seem to be making a question form, no? So you must be seeing this on another page?

**Comment by pdhixenbaugh** [comment]
It was so long ago, I'm not sure which page I created a question from. You
can look at my posts and their tags if that can be a clue. If I notice it
happen again I will note the page

**Comment by jywarren** [comment]
I think we could try to find it with `grep -r Ask app` -- marking as a help-wanted issue!

**Comment by ananyo2012** [comment]
Closing this one as it is no longer occurring.
