### ISSUE TITLE
Rename The Draft Method To Save_Draft For Clarity

### ISSUE THREAD

**Issue by RuthNjeri** [publiclab/plots2#8690]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open-source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

This issue was raised [here](https://github.com/publiclab/plots2/pull/8620#issuecomment-717312490) based on the fact that the draft method also saves a node. Changing it from `draft` to `save_draft` makes it more clear.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:
Rename `.draft` method to `save_draft` on lines `1107` and `684` in the `node.rb file`
https://github.com/publiclab/plots2/blob/5ed9d5d8f9be585fcd6b853dd680a3437feef95e/app/models/node.rb#L1107
```diff
- def draft 
+def save_draft
```

https://github.com/publiclab/plots2/blob/5ed9d5d8f9be585fcd6b853dd680a3437feef95e/app/models/node.rb#L684

```diff
-node.draft if params[:draft] == "true"
+node.save_draft if params[:draft] == "true"
```

These changes should not break any tests, I have confirmed this.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by sagarpreet-chadha** [comment]
Awesome! Thanks for opening this issue 🎉

**Comment by Guambo** [comment]
Hey! I'd like to take this for my first open source contribution if it's available!

**Comment by saitgulmez** [comment]
Hi,
I would like to take this issue. I have not made any contribution  on any open source project yet.

**Comment by melawlah** [comment]
Hello, I will like to contribute to this project. Can I go ahead?

**Comment by saitgulmez** [comment]
Hi, i have  created my first pull request with this issue.

**Comment by RuthNjeri** [comment]
Hi @Guambo, and @melawlah you can reach out [here](https://gitter.im/publiclab/publiclab) or [here](https://gitter.im/publiclab/publiclab) to request for a first-timer issue. 

Hi @saitgulmez thanks for creating the PR to fix it, please add a link of this issue in the PR you have created. @cesswairimu please assign this issue to @saitgulmez, he's already implemented it [here](https://github.com/publiclab/plots2/pull/8693/files)

**Comment by cesswairimu** [comment]
Thanks everyone
