### ISSUE TITLE
RICH MARKDOWN EDITOR SHOULD HAVE A PREVIEW BUTTON

### ISSUE THREAD

**Issue by KarenEfereyan** [publiclab/plots2#8698]
Currently, I am trying to draft my proposal for contributing to this project. I am greeted with the option of using the legacy editor or the rich markdown editor. I automatically opted for the rich markdown editor since the legacy editor is deprecated and would soon fall out of support. But the rich markdown editor has no preview button. I am unable to take a look at the changes I made before publishing the post. This proposal, being what it is requires quite a bit of typing and image upload. It is only right and needed that a preview button exists

**Please describe the desired behavior.**
A great solution would be to implement the preview button for the rich markdown editor and while it is in the works, the legacy editor should keep getting support.

**Additional context (optional)**
1. Legacy Editor soon to be deprecated<br>
![legacy-top](https://user-images.githubusercontent.com/56835876/97563066-d8785480-19e2-11eb-87ef-94daa21306b8.jpg)
2. Rich Markdown Editor without preview button<br>
![markdown editor](https://user-images.githubusercontent.com/56835876/97563120-e4fcad00-19e2-11eb-82ca-c61cd61d7077.jpg)
3. Legacy Editor With Preview <br>
![legacy botton](https://user-images.githubusercontent.com/56835876/97563141-ed54e800-19e2-11eb-83b8-a1eaf2a31038.jpg)

**Comment by jywarren** [comment]
Hi @KarenEfereyan I believe we will have the ability to add this shortly as we finish up https://github.com/publiclab/plots2/pull/8620 -- thank you very much for your suggestions and apologies for any trouble you may have had!

**Comment by jywarren** [comment]
Ah, my mistake! I believe this should now be running on the live site!!! Closing now! Thanks, everyone!
