### ISSUE TITLE
Weekly community Check-In  #82-We Rise By Lifting Others! 

### ISSUE THREAD

**Issue by tawahpeggy** [publiclab/plots2#8719]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

Is there anything, you would like to share with us from last week's work? What is your plan for this week?  If you have not planned yet, just leave a Hello! so that we know you are in sync with us and doing well! 

As always, if you're waiting for a review, or if you're stuck, you can request help here, leave a comment on your issue with @publiclab/reviewers mentioned, or ask the community in our Gitter chatroom: https://gitter.im/publiclab/publiclab. :open_hands:

**Public Lab** is an open community which collaboratively develops accessible, open source, Do-It-Yourself technologies for investigating local environmental problems. at public lab you can get help on the following topic (Air,Water,soil,climate,niose e.t.c).

**Gitter** is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up there for these updates or just to join the conversation and get your issues discussed and solved quicker . here is the link: http://publiclab.org/chat :speech_balloon:.

### This Week's Theme - WE RISE BY LIFTING OTHERS.
when I initially wanted to join open source, I was confused on what organisation to pick,so I moved through the lists of open source projects and choosed projects from familiar organisations and top ranking organisations, but I couldn't continue since when I got into issues there was little or no help from contributors. It made me nearly stop trying to contribute to free and open source, but I decided to go through the list of projects one more time and that is when i got in contact with Publiclab, and just on the first day after introducing my self I had 3 contributors reply me which made me very happy, and each time I ran into an issue I had someone doing their best to help me out. that is how publiclab ended my search for a good open source community.
Lets not stop doing this as it encourages new contributors.
lets always review others code and make comments so some people don't feel left out. Lets try to also make first-timers-only issues as it encourages new contributors and above all lets, continue been the family we are.

**A Note To Outreachy Contributors**
As most of us outreachy contributors have submitted our final application and also submitted our proposals it is not a time to relent our efforts but to keep contributing to this great, free and open source project so we can learn more from it and all its wonderful contributors and users and in turn help it achieve its goal which is bringing solutions to communities environmental scientific problems.
Thank you note to focus issues contributors
The Public Lab Community is saying thank you to everyone who completed an FTO, reviewed PRs, and offered assistance to others in one way or another.
Congratulations to those whose first pull requests were merged in the past week:  :1st_place_medal: @saitgulmez, :1st_place_medal: @alvesitalo, :1st_place_medal: @jubaan, :1st_place_medal :1st_place_medal: @IC1101Virgo, :1st_place_medal: @IC1101Virgo, :1st_place_medal: @nstjean :1st_place_medal:@noi5e

Thanks so much, to you, supermen and women who provided reviews on the PRs and dropped helpful feedback on the proposals submitted by the outreachy contributors. :1st_place_medal: @jywarren, :1st_place_medal:  @cesswairimu, 1st_place_medal @VladimirMikulic, 1st_place_medal @Uzay-G, :1st_place_medal: @Tlazypanda, 1st_place_medal @tawahpeggy, :1st_place_medal: @KarenEfereyan, :1st_place_medal: @RuthNjeri, :1st_place_medal: @urvashigupta7 :1st_place_medal: @Cadreia
We appreciate you all for the efforts you put in this past week.

To everyone following the conversations, learning, and providing support, we appreciate you too. Keep up the great work.

** Next Check-In**
If you would like to open the next check-in...Leave a comment below. We are happy to help if it's your first time.
you can view previous check-Ins done by other contributors so you get inspired and do that for next week. here is the link: #5627.

Discussion: if like me you have goals for the week and would love to see them come to a reality, just comment them below and have someone follow you up. i will like all of us at publiclab to make goals this week to:
-create an issue
-review at least one merge request
-and Encourage someone finish an issue.
why not pick up an even more difficult issue and have other contributors help you crack it.
as for me i plan to do this, this week and also collect my transcript at my previous school,and finish a task am carrying over from last week.
**fun facts**
-did you know :So far, two diseases have successfully been eradicated: smallpox and rinderpest?.
-The original London Bridge is now in Arizona.
-During your lifetime, you will produce enough saliva to fill two swimming pools. :laughing: 
don't forget to drop more fun facts on the comment section below.

Thanks to everyone for making Public Lab awesome :heart: 
You all have a great week ahead :balloon:

**Comment by KarenEfereyan** [comment]
Yay! Way to go girl! This is beautiful! Well done! Personally, this last week has been hectic for me. On average, my area gets not more than 5hours of electricity daily. It has really had a negative impact on my productivity levels and what I've been able to do. But I'm not giving up. I'll keep pushing.

**Comment by tawahpeggy** [comment]
thanks dear, you are right , cause the day we stop pushing we become leaving corpses. its not always easy but we have to always strive to be better.i have a friend in nigeria who always complains about electricity shortage too. don't bother just make and move over to cameroon :laughing:

**Comment by VladimirMikulic** [comment]
@KarenEfereyan @tawahpeggy props to you both for striving and not giving up. I wish you the best and feel free to `@me` for the review :)

**Comment by KarenEfereyan** [comment]
> thanks dear, you are right , cause the day we stop pushing we become leaving corpses. its not always easy but we have to always strive to be better.i have a friend in nigeria who always complains about electricity shortage too. don't bother just make and move over to cameroon :laughing: 

I love the sound of that. I just renewed my passport. Send my ticket fair and ill be on my way😂😂😂

**Comment by KarenEfereyan** [comment]
> @KarenEfereyan @tawahpeggy props to you both for striving and not giving up. I wish you the best and feel free to `@me` for the review :)

Thank you. Ill be sure too. Right now battery low. 😭😭😭😭

**Comment by fiona-byte** [comment]
Yaay, this is beautiful.. Way to go girl!!! 🚀🚀

**Comment by RuthNjeri** [comment]
Thanks for sharing your story @tawahpeggy 😄 
My goal this week is to get a PR that I've been working on for a while get merged, help out with some reviews, and possibly create an issue...

**Comment by tawahpeggy** [comment]
thank you all for your positive remarks. i love the sound of that @RuthNjeri, we've got our eyes on you.

**Comment by cesswairimu** [comment]
Hello all :wave: 
Thanks @tawahpeggy  for opening this :tada:
Hope everyone is doing well, great week ahead everyone

**Comment by IC1101Virgo** [comment]
Hey Everyone! 
I would like to thank you all for giving me the opportunity to grow. I want to further work on more issues and learn new things. I am new but I'll learn and get there soon 😄 
I hope I would get guidance to grow! 
You guys are great 🥰 
Thank you again 🌹

**Comment by KarenEfereyan** [comment]
> Hey Everyone!
> I would like to thank you all for giving me the opportunity to grow. I want to work on more issues and learn new things. I am new but I'll learn and get there soon 😄
> I hope I would get guidance to grow!
> You guys are great 🥰
> Thank you again 🌹

Yay! You're welcome dear. Stay amazing

**Comment by frankiefab100** [comment]
Hi everyone! I'm glad to be part of this community. A PR I made last month just got merged and I look forward to making more contributions and positive impact.

**Comment by KarenEfereyan** [comment]
> Hi everyone! I'm glad to be part of this community. A PR I made last month just got merged and I look forward to making more contributions and positive impact.

Yay. Yippie. Congrats

**Comment by jywarren** [comment]
Hi, everyone! I've been loving the themes of these check-ins. And so glad to have everyone supporting one another here. 

> -During your lifetime, you will produce enough saliva to fill two swimming pools. 😆

O. M. G. this is... an image to imagine, for sure... 💦  🏊  😂 

I was pretty low-key yesterday (tuesday is my usual work day) and mostly chased a few bugs i saw in our Sentry.io monitoring system. Small ones but nice to solve a few!  https://github.com/publiclab/plots2/pull/8729 and https://github.com/publiclab/plots2/pull/8730 and https://github.com/publiclab/plots2/pull/8727

The blog redesign PR was merged, which was a big one and nice to see now at https://stable.publiclab.org/blog2! Great work, @Cadreia !!!

Also a ton of work going on over at #8620 between @RuthNjeri and @Sagarpreet 🙌 

I'm tinkering on https://github.com/publiclab/plots2/pull/8733 and will hopefully finish that up soon... as well as https://github.com/publiclab/plots2/issues/8325 with @tawahpeggy. 

I also finished reviewing the Outreachy applications, and wanted to thank all of you very sincerely for the work you've put in, my fingers are crossed for the Outreachy organization's next steps. It's been an especially wonderful application period and i'm grateful for your time and care.
