### ISSUE TITLE
metadata to display on question cards - design discussion

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#8731]
Just breaking out a discussion from https://github.com/publiclab/plots2/pull/8479#discussion_r518358655 on what to display on each card style. Right now, we show a pretty minimal card (re style guide https://publiclab.org/style-guide) for regular posts/notes:

![image](https://user-images.githubusercontent.com/24359/98708918-b5896100-234f-11eb-9e32-5eddcd4c4e73.png)

This is driven by the following template: https://github.com/publiclab/plots2/blob/main/app/views/notes/_card.html.erb

Question cards look a little different, unfortunately:

![image](https://user-images.githubusercontent.com/24359/98709676-b242a500-2350-11eb-89bf-a45e9085dfb3.png)

Question cards are driven by a separate template, actually - we should try to make them more consistent, which would include:

* [ ] grey meta text
* [ ] smaller meta text size
* [ ] black title and author text
* [ ] more bottom-padding in card

Template here:

https://github.com/publiclab/plots2/blob/5c239014abe3cc46fad82f33ce0382f928f3789a/app/views/questions/_questions.html.erb#L5-L12

## Design questions

Note that questions have tags listed. I think this makes them already quite cluttered and that adding a count of comments might make them even a bit harder to read, but we could do it. Is there anywhere else we could reduce clutter to improve readability? Are we still committed to the topics listing on each card? 

For reference, look at how posts are displayed on the dashboard. Do we like the amount of info on each item here?

![image](https://user-images.githubusercontent.com/24359/98709494-6ee83680-2350-11eb-8264-957ea427d0b8.png)

## Coding

In any case, instead of making the templates match, we should just start using the regular card template, and add a condition to cover questions:

https://github.com/publiclab/plots2/blob/5c239014abe3cc46fad82f33ce0382f928f3789a/app/views/notes/_card.html.erb#L39-L45

**Comment by jywarren** [comment]
OK, so let's just swap in the standard `_card.html.erb` template, having checked on this with @ebarry! We can make an FTO from this by just modifying:

https://github.com/publiclab/plots2/blob/5c239014abe3cc46fad82f33ce0382f928f3789a/app/views/questions/_questions.html.erb#L5-L12

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by KarenEfereyan** [comment]
@jywarren like I observed the cards aren't of the same height which is a lot inconsistent in itself. It would be great to add related tags in case the user searches by tags but if the tags become more than 3 and break into a new line, then it'd be too cluttered so maybe we could reduce the tags to the 3 most related? Then only the number of comments and maybe the link icons really matter. Maybe we could remove the others?

**Comment by KarenEfereyan** [comment]
I could cone up with a quick design of how I think the cards should look while incorporating gray and smaller meta text size and black colored author. I don't think adding more padding would totally solve the issue of inconsistent card heights. The length of the title is always a factor. Instead, it might be good to explicitly set a maximum number of characters for the title and maybe add a read more link to see the whole title? Not sure about that just suggesting

**Comment by KarenEfereyan** [comment]
![card](https://user-images.githubusercontent.com/56835876/98853965-35035700-245a-11eb-9aa4-ffae166c17f8.png)
This is a rough design of how it'd look. Still some things to deliberate on. 
1. The tags compose characters of different lengths, how do we deal with that. I think for questions asked, what's important is the person who asked the question, when it was asked and replies to the question, hopefully suggesting solutions. 
@jywarren what ae your thoughts?

**Comment by KarenEfereyan** [comment]
@jywarren @cesswairimu ??

**Comment by jywarren** [comment]
Hi @KarenEfereyan I'm so sorry i missed this. Sometimes I don't see a comment for a few days as my main work day is Tuesdays. Thank you for your careful work on this! I think in discussion with @ebarry we settled on the default display (the very top screenshot) as suitable for questions as well. So I think that makes it relatively simple to move forward on! 

I do think your idea of trying to get the cards to be standard heights is good. But it's a pretty tough challenge - are there sites which achieve this given variations in title length? 

Thank you!

**Comment by jywarren** [comment]
I think we can break this into a few pieces and hopefully welcome some newcomers in in the process. I suggest:

* [ ] add a `app/models/node.rb` method `node.is_question?` so we can tell if it's a question.
* [ ] add a conditional based on `node.is_question?` so we switch between `Post` and `Question` in this section:
https://github.com/publiclab/plots2/blob/5c239014abe3cc46fad82f33ce0382f928f3789a/app/views/notes/_card.html.erb#L39-L45
* [ ] replace the custom question template at [the comment above](https://github.com/publiclab/plots2/issues/8731#issuecomment-724922984) with the `<%= render partial: 'notes/card', locals: { node: node, i: i, tagname: tagname } %>` template partial, so we start using the same template.

@KarenEfereyan if you are still interested in taking any of these on, that'd be great! Or in creating a `first-timers-only` issue out of them for a newcomer, as i suggested above. Thank you again for your work and patience!

**Comment by jywarren** [comment]
Actually for the above line item 3 -- changing the template -- couldn't we just eliminate this whole block and make line 9 accept `|| @node_type == 'question' ` as well?

https://github.com/publiclab/plots2/blob/903a1623638aab99b2ad9bec3b628416818c6f95/app/views/tag/show/_tab_content.html.erb#L20

@Cadreia maybe this could simplify your work in https://github.com/publiclab/plots2/pull/8689 as well? 

Thanks, all!

**Comment by KarenEfereyan** [comment]
> Hi @KarenEfereyan I'm so sorry i missed this. Sometimes I don't see a comment for a few days as my main work day is Tuesdays. Thank you for your careful work on this! I think in discussion with @ebarry we settled on the default display (the very top screenshot) as suitable for questions as well. So I think that makes it relatively simple to move forward on!
> 
> I do think your idea of trying to get the cards to be standard heights is good. But it's a pretty tough challenge - are there sites which achieve this given variations in title length?
> 
> Thank you!

I thought as much. Its okay. I can understand how busy you must be

**Comment by KarenEfereyan** [comment]
> I think we can break this into a few pieces and hopefully welcome some newcomers in in the process. I suggest:
> 
> * [ ]  add a `app/models/node.rb` method `node.is_question?` so we can tell if it's a question.
> * [ ]  add a conditional based on `node.is_question?` so we switch between `Post` and `Question` in this section:
>   https://github.com/publiclab/plots2/blob/5c239014abe3cc46fad82f33ce0382f928f3789a/app/views/notes/_card.html.erb#L39-L45
> * [ ]  replace the custom question template at [the comment above](https://github.com/publiclab/plots2/issues/8731#issuecomment-724922984) with the `<%= render partial: 'notes/card', locals: { node: node, i: i, tagname: tagname } %>` template partial, so we start using the same template.
> 
> @KarenEfereyan if you are still interested in taking any of these on, that'd be great! Or in creating a `first-timers-only` issue out of them for a newcomer, as i suggested above. Thank you again for your work and patience!

Sure. I can do either. Maybe create an FTO out of it. I'll need help with that though because I've never created one before

**Comment by tawahpeggy** [comment]
@KarenEfereyan Its quite simple to create an FTO issue, just check at the top of any issue already created, click on new issue (the green button at the top right corner of the page ) then select fto and follow the steps as describe on the template.its exactly same as creating a check-in ,just that different templates are used.

**Comment by jywarren** [comment]
I'm eating lunch right now but also happy to help out in the chatroom if you're looking into doing this! https://gitter.im/publiclab/publiclab

**Comment by KarenEfereyan** [comment]
I'll be out of power on my phone soon.I'll look into it tomorrow and contact you @jywarren and @tawahpeggy if I have issues. BTW @jywarren enjoy your lunch

**Comment by jywarren** [comment]
OK @KarenEfereyan and thank you @tawahpeggy -- i've completed the first item, and so now the second can be done as a stand-alone. Then 3. If you need help faster next time, please do reach out in the chatroom as I should get a notification faster then!

Thanks, everybody!

**Comment by tawahpeggy** [comment]
> I'll be out of power on my phone soon.I'll look into it tomorrow and contact you @jywarren and @tawahpeggy if I have issues. BTW @jywarren enjoy your lunch

anytime @KarenEfereyan

**Comment by ebarry** [comment]
Thank you for all your help @KarenEfereyan
<https://github.com/KarenEfereyan> @tawahpeggy
<https://github.com/tawahpeggy> @jywarren <https://github.com/jywarren> !
--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net

**Comment by jywarren** [comment]
Uh oh - actually it looks like our question card formatting in https://publiclab.org/questions was affected by the changes here. I'm reopening just to try to resolve this:

Before:

![image](https://user-images.githubusercontent.com/24359/129810269-6521f5b5-f6fe-41af-90a5-64e769ab4d0e.png)

Now:

![image](https://user-images.githubusercontent.com/24359/129810456-9c0cf716-1c07-45c0-bb48-05e00755a862.png)

I think we need to fix the lazy loading on /questions, probably just by running this:

```js
$(function(){
  $("img").lazyload();
});
```

(see https://github.com/publiclab/plots2/pull/8043/files#diff-10d79f07bd4ae39a54ddd901d05832f6ea45f6ec427932edd966bed0b83e6714R20)

**Comment by ebarry** [comment]
I think the question card formatting is fixed now: 
<img width="1152" alt="Screen Shot 2021-12-08 at 3 17 22 PM" src="https://user-images.githubusercontent.com/161439/145278204-276e7c29-a0d8-4d00-ba2c-e5f90352c428.png">

**Comment by TildaDares** [comment]
@ebarry It was resolved in #10359

**Comment by cesswairimu** [comment]
Seems this one is resolved. Thanks all
