### ISSUE TITLE
Request for joining the organisation

### ISSUE THREAD

**Issue by akshitagupta15june** [publiclab/plots2#8742]
Request for joining the organisation

**Comment by pkdiv** [comment]
Hi @akshitagupta15june , I want to start contributing to open source, so I would like to claim the issue.

**Comment by akshitagupta15june** [comment]
I would like to join the organisation

**Comment by cesswairimu** [comment]
Hi @akshitagupta15june thanks for checking  us out...have you contributed to any PublicLab projects? We usually add folks who are contributors..if not and you would like to contribute check issues here https://code.publiclab.org/

**Comment by cesswairimu** [comment]
Closing this. @akshitagupta15june please feel free to reach out in the [chat room](https://gitter.im/publiclab/publiclab) if you have any further question . Thanks
