### ISSUE TITLE
Not able to create account and sign into the forum.

### ISSUE THREAD

**Issue by ashwinvasudevan** [publiclab/plots2#876]
### What happened just before the problem occurred
Tried to create an account, after filling out the captcha, I received 
"There was an error. Are you sure you have the right address?"

### Relevant URLs

https://publiclab.org/register

### PublicLab.org username
Tried to create an account, that's when the error occurred.

(to help reproduce the issue)

### Browser, version, and operating system
Chrome 53.0.2785.143 OSX El Captain

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Hi, we had a hiccup this morning but it should be resolved now -- can you give another try? Thanks for your patience.

If that doesn't work, please re-open this issue and we can have another look. Thanks for reporting.
