### ISSUE TITLE
Weekly Community Check-In #84 - See Beyond its Flaws 

### ISSUE THREAD

**Issue by tawahpeggy** [publiclab/plots2#8760]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯 Is there anything, you would like to share with us from last week's work? What is your plan for this week? If you have not planned yet, just leave a Hello! so that we know you are in sync with us and doing well!

As always, if you're waiting for a review, or if you're stuck, you can request help here, leave a comment on your issue with @publiclab/reviewers mentioned, or ask the community in our Gitter chatroom: https://gitter.im/publiclab/publiclab. :open_hands:

**Public Lab** is an open community which collaboratively develops accessible, open source, Do-It-Yourself technologies for investigating local environmental problems. at public lab you can get help on the following topic (Air,Water,soil,climate,niose e.t.c).

**Gitter**  is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up there for these updates or just to join the conversation and get your issues discussed and solved quicker . here is the link: http://publiclab.org/chat :speech_balloon:.

### This Week's Theme - See Beyond Its flaws .
we were just busy doing our own stuff and all of a sudden we were asked to stop going out of the house and our siblings had to stop school,mum could no longer go for her business as everything was shut down and Dad needed to come home. In inquiring what was happening, we were told not to speak in public instead we should wear masks and always wash our hands. It was when we started seeing vulnerable people dieing randomly that we understood  things had taken a different turn and we really had to stay home.the government tried as much as they could to reduce death rate but it was seeming impossible.The numbers increased daily as many as 32000 infected and almost 1000 deaths. Presently things are trying to return to normal but we have already lost a lot of time and resources but as @jywarren says we should not worry or think about the things we planned to do that are still undone, but lets take this opportunity to spend time with our love ones, stay away from the virus as much as possible and do the things that are possible and can be done from home. I personally will like to see things differently by looking beyond the shortcomings of the corona virus because though it has greatly destroyed the worlds economy and my plans as a whole, it  gave me the opportunity to spend time with my family especially my Dad who is never home. This virus gave me the opportunity to be with him and the whole family for 2 weeks. it was one of the best times of my life. 

### A Note To Outreachy Contributors
I am sure all of us aspirants outreachy interns are worried sick right now and all sorts of thoughts are running through our minds wondering who is going to be given the great privilege of becoming an intern at this great organisation.
Here is my advice to us all,
Be calm and hope for the Best but don't give up on the organisation because you were not chosen. i advice you to continue  contributing and staying around cause you could apply in next sessions or better still apply to other open source internship opportunities and  competitions like **Hactoberfest, She Codes** etc

### Thank you note to focus issues contributors
The Public Lab Community is saying thank you to everyone who completed an FTO, reviewed PRs, and offered assistance to others in one way or another.
Congratulations to those whose  pull requests were merged in the past week: :1st_place_medal: @RuthNjeri , :1st_place_medal: @Cadreia 

Thanks so much, to you, vibrant men and women who contributed immensely in the past week. :1st_place_medal: @ebarry :1st_place_medal:  @jywarren :1st_place_medal: @cesswairimu  :1st_place_medal: @sagarpreet-chadha  :1st_place_medal: @VladimirMikulic, :1st_place_medal: @Uzay-G, :1st_place_medal: @Tlazypanda,  :1st_place_medal: @urvashigupta7  :1st_place_medal: @icarito  :1st_place_medal:  @KarenEfereyan 

To everyone following the conversations, learning, and providing support, we appreciate you too. Keep up the great work.

###  Next Check-In
If you would like to open the next check-in...Leave a comment below. We are happy to help if it's your first time.
See previous check-Ins done by other contributors to get inspired and do that for next week :hugs: . here is the link: #5627.

**Discussion:**
A big shout out to all our outreachy contributors and mentors for the geat work done. may your God richly Bless you for all your hardwork and sacrifices  towards public Lab. 
We are eager to know how everyone is doing during this  2nd wave of the corona virus. and one good thing  the corona virus helped you aquire or gained, be it a skill, a hobby or any thing. just share with us in the comment section. for me i was able to spend time with my dad for the first time in about 6 years in a roll which was so exiting :heart: . 
 **Facts**
- People with type A blood may be more susceptible to infection.
-People who don’t have symptoms can spread the virus.
-Contrary to popular belief, pets can NOT spread the coronavirus. No cases of human infection from a dog or cat have yet been reported.

**Thanks to everyone for making Public Lab awesome :heart:**
You all have a great week ahead :balloon:

**Comment by KarenEfereyan** [comment]
You did this week too? Super nice Tawah. Thanks

**Comment by tawahpeggy** [comment]
> You did this week too? Super nice Tawah. Thanks

yea i did dear @KarenEfereyan  thanks. hope you are good.
also did you encounter any issues while creating the issues??.

**Comment by fiona-byte** [comment]
This is beautiful

**Comment by fiona-byte** [comment]
@tawahpeggy I'd love to work on next week's check-in

**Comment by KarenEfereyan** [comment]
Congrats to you @RuthNjeri you deserve the internship position. Enjoy the internship. I'll try harder next time

**Comment by cesswairimu** [comment]
Thanks @tawahpeggy :tada: and  thanks @fiona-byte do let me know if you need help next week

**Comment by RuthNjeri** [comment]
Thanks, @KarenEfereyan :)...if you re-apply in the future, I'll be happy to share any feedback...

**Comment by KarenEfereyan** [comment]
> Thanks, @KarenEfereyan :)...if you re-apply in the future, I'll be happy to share any feedback...

I'll be sure to. Enjoy your internship😍😍😍

**Comment by tawahpeggy** [comment]
A big congratulations to you @RuthNjeri i wish you best of luck on your internship.you were actually the best candidate for the position :100: :clap: :partying_face: :partying_face:  :partying_face:

**Comment by RuthNjeri** [comment]
Thank you for the kind words @tawahpeggy :) and thanks for sharing your wonderful stories during the weekly Check-ins, I hope I'll still see you contributing 😃

**Comment by tawahpeggy** [comment]
ofcourse you will public Lab has become home for me within this short time

> Thank you for the kind words @tawahpeggy :) and thanks for sharing your wonderful stories during the weekly Check-ins, I hope I'll still see you contributing

you are very welcome @RuthNjeri, ofcourse you will still see me around, Public Labs has become a home for me within this past few weeks.

**Comment by tawahpeggy** [comment]
> Thank you for the kind words @tawahpeggy :) and thanks for sharing your wonderful stories during the weekly Check-ins, I hope I'll still see you contributing

you are very welcome @RuthNjeri, ofcourse you will still see me around, Public Labs has become a home for me within this past few weeks.

**Comment by stacytonui** [comment]
Nice work @tawahpeggy, your check-ins are an interesting read and Congrats @RuthNjeri You deserve it!!

**Comment by jywarren** [comment]
Hi @tawahpeggy thank you so much for a beautiful check-in. It's deeply appreciated and I'm glad to hear you are finding some positives in this tough time. Your post gave me a chance to take a big deep breath on a busy day!

Many congrats to @RuthNjeri @noi5e and everyone who worked so hard these past weeks. We will be participating in Outreachy every round we can get into the program and we hope to have a chance to work with more of you in the future. Please know your efforts and your contributions are precious to us and you're always welcome here!

**Comment by tawahpeggy** [comment]
> Hi @tawahpeggy thank you so much for a beautiful check-in. It's deeply appreciated and I'm glad to hear you are finding some positives in this tough time. Your post gave me a chance to take a big deep breath on a busy day!
> 
> Many congrats to @RuthNjeri @noi5e and everyone who worked so hard these past weeks. We will be participating in Outreachy every round we can get into the program and we hope to have a chance to work with more of you in the future. Please know your efforts and your contributions are precious to us and you're always welcome here!

Thanks @jywarren, your mentoring skills are top notch, i learnt a lot from you this past weeks and working with you has been awesome so far,  learning more from you is what i can't afford to miss out on.

**Comment by cesswairimu** [comment]
Hi @fiona-byte how is the check-in coming along?  please let me know if you need any help.

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/8791. Thanks all

**Comment by KarenEfereyan** [comment]
> Hi @fiona-byte how is the check-in coming along? please let me know if you need any help.

Hi @cesswairimu . I'll do this week's check in on behalf of @fiona-byte. She has some health related issues but she'll be back soon. She said to tell you

**Comment by cesswairimu** [comment]
Hey @KarenEfereyan, no worries, @Tlazypanda already opened one, thanks.
Quick recovery to @fiona-byte 💜
