### ISSUE TITLE
History graph for wildcard tag display should not be displayed

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#878]
Seen on https://publiclab.org/tag/question:*
The graph at the top of activity over time seems not to be populated: 

![screen shot 2016-10-11 at 3 11 35 pm](https://cloud.githubusercontent.com/assets/161439/19284795/583ece62-8fc5-11e6-8e4b-7dd18417f5bc.png)

****

@jywarren sez: This is because wildcards (`*`) are not real tags, so the graph should not really be shown at all. The following code (on this line: https://github.com/publiclab/plots2/blob/master/app/views/tag/show.html.erb#L25) is suppose to detect that and not show the graph, but is not working properly:

```ruby
  <% if @tags.first %>
```

We could:

1. Modify the conditional above to use the same logic as the controller  (https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L28), making it: `@tags.first && params[:id][-1..-1] != "*"` -- which ensures that the last character is not a wildcard.
2. Add a test that checks this page and ensures a graph is not shown:

The test could be based on this one: https://github.com/publiclab/plots2/blob/master/test/functional/tag_controller_test.rb#L85-L101

```ruby
  test "wildcard tag show" do

    get :show, id: 'question:*'

    assert :success
    assert_not_nil :tags
    assert :wildcard # if this fails, this line may need to be: assert assigns(:wildcard)

    assert_select '#note-graph', 0 # test that the graph is not shown
  end
```

**Comment by mridulnagpal** [comment]
I would like to work on this issue
