### ISSUE TITLE
Display # of answers per question on /questions page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#879]
On https://publiclab.org/questions, the # of comments is shown, but not the # of answers. 

The per-question template is here: https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_node_question.html.erb

If we wanted to show it at the bottom of each box, that's cool. But if we wanted to show it alongside questions, we might use this sub-template: https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_node_meta.html.erb

We should be able to use `node.answers.count` to return the # of proposed answers. 

The key here is that it currently only shows `Answered` if an answer has been accepted, so un-accepted answers aren't shown -- we'd like to fix that.

**Comment by prabhagharan** [comment]
Seems it already displays answers count at https://publiclab.org/questions , please correct me if my interpretation is wrong.

https://github.com/publiclab/plots2/blob/master/app/views/dashboard/_node_meta.html.erb#L8

**Comment by jywarren** [comment]
Oh, indeed -- apologies. Perhaps we need to show both answers and comments, somehow? Because until looking closer, I thought the icon indicated comments, which is why i created this issue.

**Comment by prabhagharan** [comment]
Yeah we can show both, just a minor change. Also I think texts can be used instead icons so it will be more readable. 

Will look like:
In /research screen:
![screen shot 2016-10-14 at 3 53 19 pm](https://cloud.githubusercontent.com/assets/211298/19384525/42c64f92-9227-11e6-92a6-088531bd1a7f.png)

In /questions screen:
![screen shot 2016-10-14 at 3 52 58 pm](https://cloud.githubusercontent.com/assets/211298/19384539/57bcbc7e-9227-11e6-92b7-1d1e4b6c2549.png)

**Comment by jywarren** [comment]
I think text is nice but on a smartphone there's probably not room. Can we
use Bootstrap tooltips to disambiguate instead of text links? Thanks for
thinking through this!

**Comment by jywarren** [comment]
Hi, @prabhagharan - just checking, did you open a PR for this, or were you interested in doing so? Thanks!
