### ISSUE TITLE
Weekly Community Check-In #85 - Outreachy is here!!!

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#8791]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Outreachy is here!!!

This week marks the first week of Outreachy. A very warm welcome to the Outreachy interns and hoping they have an amazing time here at Publiclab 🎈 

### For the interns
Please create a planning issue laying out all the tasks to be completed during this internship 🎉 
This will give the mentors a rough idea of what tasks we are dealing with and provide with any guidance if required. 😄 
Don't worry about what all to include at the moment 😅 This list can be variable as and soon you start developing, feel free to make changes accordingly.

Also don't forget to join the official Outreachy zulip chat and get a chance to network with outreachy fellows from all over the world 🌏 

Some examples : #7885 #7883 #7432 

## For the mentors
Take this time to get acquainted with your mentee and help them with laying tasks down. ✌️ 

Answer their questions and direct them to any documentation that can help them! 💯 

## This week's focus Issues

These are issues that are of high priority and requests from our
large community that use the software. 

https://github.com/publiclab/plots2/labels/high-priority

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by Sagarpreet** [comment]
Happy coding to Outreachy interns 🎉

**Comment by jywarren** [comment]
Thanks @Tlazypanda! this is so great. A big welcome to @RuthNjeri and @noi5e and thanks again to everyone who participated so far.

**Comment by RuthNjeri** [comment]
Thanks for the warm welcome!

**Comment by noi5e** [comment]
Yes, thanks for welcoming us in as interns!

**Comment by cesswairimu** [comment]
moved to https://github.com/publiclab/mapknitter/issues/1474. thanks al ot everyone :tada:
