### ISSUE TITLE
tag aliases and subscriptions interaction

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#880]
We're working on a tag aliasing system, but that doesn't yet touch on email notifications -- but it could and should! 

https://github.com/publiclab/plots2/pull/871

a key use re: `spectrometer` vs. `spectrometry` tags

**Comment by wimpykid26** [comment]
@jywarren . I would love to work on this. Could you give me some more information about what the issue is? :)

**Comment by jywarren** [comment]
Hi, I think we may need to wait on another subscription-related issue for this (#1119), and I see you're interested in #428 -- so maybe let's tackle that first! Thanks!

**Comment by jywarren** [comment]
Closing and moving into https://github.com/publiclab/plots2/issues/6367
