### ISSUE TITLE
Stop using old inefficient `set_sidebar` method

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#8803]
We used to use `set_sidebar` a lot because it was a standard way to show sidebars across the site. But that old style sidebar is essentially completely gone, and we should remove it from any remaining pages. The code is very inefficient and it's causing 25+ second load times. 

The function itself is here, and you can see why it's so inefficient! it's super long and just makes tons of queries for stuff we don't use anymore, like wikis, etc etc:

https://github.com/publiclab/plots2/blob/cbb807ba8e2302f09dafc0060475aa118e34c2c6/app/controllers/application_controller.rb#L25-L67

Here's all the instances we should carefully remove and test:

https://github.com/publiclab/plots2/search?q=set_sidebar

This could be broken out into sub-tasks or sub-issues! We'd love help with it!

**Comment by gauravahlawat81** [comment]
Hey @jywarren , I would like to work on this!
