### ISSUE TITLE
Remove all "answered_questions" code from app/controllers/tag_controller.rb

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#8804]
We no longer use this code, so we'd love some help just removing all of it! I believe, but am not 100% sure, that tests should pass even after we do this. 

https://github.com/publiclab/plots2/blob/92834ead6c53d6d9431bb99024d4044b282518be/app/controllers/tag_controller.rb#L141-L142

Thanks for any help on this!!!!

**Comment by jywarren** [comment]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by jperk224** [comment]
@jywarren I would like to work on this. I've been hunting for `fto-candidate` issues to work on to get more familiar with the repo and been having trouble finding ones that seem to be up for grabs?

**Comment by RuthNjeri** [comment]
Hi, @jperk224 thank you for reaching out. I've assigned the issue to you. Feel free to ask any questions here if you need any clarification

**Comment by jperk224** [comment]
Thanks @RuthNjeri !  Can you please confirm which tests I should verify still pass after removing these `answered_questions` references? I see `tag_selection_test.rb`, `tag_test.rb`, and `user_tag_test.rb`.  Is it all or any of them or am I looking in the wrong place?  Thank you.

**Comment by RuthNjeri** [comment]
Hi @jperk224 I see there's also `tag_controller_test.rb`

**Comment by jperk224** [comment]
I am still planning to look at this/review it.  I haven't had a much time the last few days as I had hoped.  If someone is eager to take this on immediately let me know and it can be reassigned, else I hope to get to it soon!
