### ISSUE TITLE
List related activities/questions in sidebar on activity/questions pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#881]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled.

****

On activity pages like this: https://publiclab.org/notes/ashkaya/09-17-2016/build-a-coqui-a-simple-water-conductivity-sensor

The sidebar shows people, wiki pages, and notes related. We should have an alternate sidebar -- based on the template here: 

https://github.com/publiclab/plots2/blob/master/app/views/sidebar/_related.html.erb

That template is included into the notes page here, line 1: https://github.com/publiclab/plots2/blob/master/app/views/notes/show.html.erb#L1

Perhaps we could show a table of activities, using the table generator here: https://github.com/publiclab/plots2/blob/master/app/helpers/application_helper.rb#L31

This may need some design work -- sketches, mockups -- before it's complete -- but we could either start with design work, or we could start with back-end work to display the data, thinking about design as a followup.

**Comment by mridulnagpal** [comment]
I would like to work on this issue

**Comment by jywarren** [comment]
I think you have a couple issues already in progress, so why don't we hold off on this one until your other pull requests are complete. But after that, we would love to have your help with this! Thanks and we appreciate your hard work and energy!

**Comment by jywarren** [comment]
Let's not do this, since we're rethinking the UI of sidebars!
