### ISSUE TITLE
Tag visualization loading issues, probably related to rate limiting

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#8815]
The visualization at https://publiclab.org/tags usually shows a graph of interconnected topics to the right side, but it's not loading now. The iframe containing it is pointed at https://publiclab.org/tags/stats/graph?limit=50

I looked at routes.rb and found a similar looking route at: https://publiclab.org/stats/graph

However it's blocked by password, i think because of @icarito's work to protect our stats routes from robots which was causing overload. I wonder if we can either make an exception for this route, or change its path, but I'm also not sure if `/stats/graph` is the same as `/tag/stats/graph` - but if it is the same, I hope that it is not a huge load to do this graph (i think it's cached) so it should be OK. Hoping this is a pretty simple fix!

**Comment by icarito** [comment]
I've made an exception for the password protection of the `/stats` route for `/stats/graph` and now the graph is displaying.
