### ISSUE TITLE
Resolution more compact and structurally well-organized for Banning (spam) users drop the liked count on wiki pages

### ISSUE THREAD

**Issue by rafael-acerqueira** [publiclab/plots2#882]
This looks like it'd work -- and I can def. pull it in. But I wonder if we could do even better. Would you be willing to try something a little more compact and structurally well-organized as a followup?

I'm thinking:

A. Write a test that:

1.has a user like a node, and then check that the like count is increased ban the user, and check that the like count is decreased 

B. Replace the like recalculations with more efficient code:
1.Write a new method, perhaps under the DrupalNode model, like node.toggle_like(user) (and maybe directional ones like node.like(user) and node.unlike(user)), based on this code and use it both in the admin controller and in the likes controller.

2.Write a method that checks if a user likes a node (this can be used in the node.toggle_like method above), such as node.liked_by(user) which returns true or false
Write unit tests for node.toggle_like, node.like, node.unlike, and node.liked_by(user)

C. Check that the test in A. still passes

This is a lot of steps, but the functionality is pretty simple and/or already written. I think that, done as outlined above, we could be sure not to break the currently-working system, and then all liking/banning code across the site would be much more effective.

Another idea would be to write a method like node.recalculate_likes because can't we just write a query to count node_selections and save the sum? But this approach could be complimentary to the above.

**Comment by jywarren** [comment]
Great, tagged and thanks!

**Comment by sagarpreet-chadha** [comment]
@jywarren sir...may i try this issue ?

**Comment by jywarren** [comment]
Yes, I think so -- actually perhaps we need to more clearly state the purpose here, i think it's been taken a bit out of context. 

Aha -- it's part of https://github.com/publiclab/plots2/issues/607 --

**Comment by jywarren** [comment]
Hi, @rafael-acerqueira and @sagarpreet-chadha -- looks like this is now wrapped up; i just wanted to say thanks to you both for making this happen!
