### ISSUE TITLE
Implement Mobile Responsiveness on The All Posts Page

### ISSUE THREAD

**Issue by RuthNjeri** [publiclab/plots2#8830]
This is part of the Dashboard implementation #8513

It will:
- [ ] Implement/Ensure mobile responsiveness in the 'All Posts' page
- [ ] Implement/Ensure mobile responsiveness in the Research notes section
- [ ] Implement/Ensure mobile responsiveness in the Questions section
- [ ] Implement/Ensure mobile responsiveness in the Wiki pages section
- [ ] Implement/Ensure mobile responsiveness in the  Comment section

**Comment by RuthNjeri** [comment]
I think, for now, the all posts page `/notes` is responsive..
The other pages(/comments, /questions, /wiki) I suspect will require a redesign, I think responsiveness will be handled in each individual page redesign, what do you think @jywarren ?

**Comment by Sagarpreet** [comment]
I like the idea 💯

**Comment by RuthNjeri** [comment]
Thanks @Sagarpreet! I'll close this issue.
