### ISSUE TITLE
Many revisions fixtures have nid = 1 and are causing intermittent test failures

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#8864]
Follow-up to #8862 --

It looks like MANY of the revisions fixtures have nid = 1 -- that must be the underlying problem. I think we have to given them all unique nids, because notes are not supposed to have more than 1 revision! also... they dont have timestamps set so they are probably getting initialized with almost identical timestamps, which could account for the intermittent failures!

https://github.com/publiclab/plots2/blame/main/test/fixtures/revisions.yml#L91

this may take some untangling of the other tests that use these fixtures... we'll have to see! If we give unique nids we may have to add matching entries to /test/fixtures/nodes.yml to make this work.

_Originally posted by @jywarren in https://github.com/publiclab/plots2/issues/8862#issuecomment-746690241_

**Comment by noi5e** [comment]
Currently working on this, will push changes to the branch in PR #8865
