### ISSUE TITLE
Weekly Community Check-In #87 - Everybody Struggles

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#8877]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Everybody Struggles

I know we have talked about this topic a couple of times, it was last week's theme for Outreachy and we didn't get a time to discuss it. Thought it would be great to discuss here with the community and hear everyone's experiences. Outreachy Organizers  writes 
>If we never acknowledge the effort and struggle we experience, other people may feel bad about getting stuck. They may hesitate to reach out when they need help. However, sometimes even the act of asking for help can solve your problem! Often when we start to write about what we're stuck on, or talk with another person about it, we end up figuring out something new to try or realizing what our issue was. Programmers often call this "rubber duck" debugging:

This week  lets share about a time in the when you were really stuck on an issue and how you got yourself unstuck 

## This week's focus Issues
We are now officially running on git-actions thanks to @jywarren  :rocket: :rocket: 
During the migration there were a couple of editor tests that were weirdly failing _(they were passing on travis before and also passing on local environment)_ we have them commented out for now we would love help fixing or rewriting these

- https://github.com/publiclab/plots2/issues/8858

We will very much appreciate any help with this issue. Any contributor who is looking for issues to work on please consider taking a look at this. Feel free to leave a comment on the issue if you have any ideas 
We will add a thank you message here in next week's check-in if you contribute in any way. Thanks in advance 😄

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by RuthNjeri** [comment]
Hi @cesswairimu 😄 

It's interesting that when I find myself struggling, I easily forget everybody struggles too...a struggle that comes to mind is when I wanted to order the notes on Public Lab according to the most liked and views and couldn't get a working query. I was able to get a lot of help from you (Thank you!) in thinking through it and eventually solving it... It's always a good idea to reach out when stuck or struggling.

Have a great week everyone!

**Comment by noi5e** [comment]
@cesswairimu Thanks for writing this check-in! As an intern, I've struggled a bit (okay a lot) learning some things about Rails, but also web development in general. 😥 I guess it's part of the learning process! It's satisfying when I can find the answer, like figuring out a riddle. It just happened this week for me when I was also writing a query in #8618, so satisfying to figure that out! 

Like Ruth I think it's important to be able to ask for help and be transparent about what you don't know. There's still a lot that I'm learning about the codebase, like I've had a million questions about how comments get made and testing in 8810

**Comment by sagarpreet-chadha** [comment]
Hi everyone, I was not much active last week. I will try to catch up with the status in today's Outreachy meeting 😄

**Comment by cesswairimu** [comment]
Keeping this open for this week too, Ruth has offered to open next week's one :tada: ...Thanks everyone and nice week ahead :heart:

**Comment by RuthNjeri** [comment]
Thanks @cesswairimu. Happy holidays everyone!

**Comment by RuthNjeri** [comment]
This week's check-in https://github.com/publiclab/plots2/issues/8931
