### ISSUE TITLE
Feature Q&A and Activities in many more places

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#888]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled.

**Note:** each of these below would be nice `first-timers-only` issues, not the whole thing!

****

Ideas:

- [ ] SpectralWorkbench.org dashboard (https://github.com/publiclab/spectral-workbench)
- [ ] Blog https://publiclab.org/blog
- [ ] at the end of an activity (list related questions?)
- [x] in sidebar (see #881)
- [ ] on MapKnitter (https://github.com/publiclab/mapknitter/)
- [x] in an embed (see #830)

For Public Lab nonprofit staff:

- [x] Infragram.org (partially done)
- [x] in kits boxes
- [x] on store
- [ ] at the end of printed instructions (as replaced)

**Comment by ananyo2012** [comment]
@jywarren Happy to know the Q&A system that I help develop is going to be featured at other sites as well :blush: I will help breaking up this issue. Before that I have to get acquainted with the code of `feature_controller` and _activity grids_ which are fairly new to me.

**Comment by jywarren** [comment]
:-) Indeed-- i'm largely offline this week, but am happy to help think this through more. And am thinking about better docs for our code structure -- will upload an image soon and would love to add an "Architecture" section to the docs.
