### ISSUE TITLE
README links to API

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#894]
I want to begin using the awesome new APIs @david-days put together -- David, can you link to the Grape API index pages so I can start solving things like #595, and others can begin using them? Also, do those cover the internal APIs we can begin using within the codebase? Thanks!

**Comment by david-days** [comment]
Wll do!  And yes--I still owe you a write-up and how-to on using the Grape and internal APIs.

**Comment by jywarren** [comment]
Added!
