### ISSUE TITLE
"Scroll back to top button" should not be there when we already are on top.

### ISSUE THREAD

**Issue by frappelatte28** [publiclab/plots2#8948]
### Please show us where to look
![PublicLab_issue1](https://user-images.githubusercontent.com/64382399/103751359-2b4b3980-502e-11eb-8354-1eba62fa7a40.png)

### What's your PublicLab.org username?
> This can help us diagnose the issue: 
pjilowa

### Browser, version, and operating system
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!
Google Version 87.0.4280.88 (Official Build) (64-bit)

****

**Comment by frappelatte28** [comment]
Can I raise a PR on this issue? @gauravahlawat81

**Comment by gauravahlawat81** [comment]
Hey @frappelatte28 , thanks for looking into this, great spot! But I am also a newbie like you in PublicLab community, so you will have to ask @cesswairimu for this. He will be able to guide you in a better way. Cheers and welcome to Public Lab.

**Comment by frappelatte28** [comment]
Thanks @gauravahlawat81:-)

**Comment by cesswairimu** [comment]
hey @frappelatte28, yeah this an issue and we would love your help...we already an issue and some discussions going on here https://github.com/publiclab/plots2/issues/7454 also there was an attempt to fix that didn't work [here](https://github.com/publiclab/plots2/pull/6944) that might be helpful..feel free to get started on it

Thanks you both :heart:

**Comment by TildaDares** [comment]
If no one's working on this, I'd like to take it up.

**Comment by cesswairimu** [comment]
Hey @TildaDares , we would lobe your help, feel free to go ahead. thanks
