### ISSUE TITLE
advanced search returns "Required parameter missing: search"

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#895]
When going to https://publiclab.org/searches/new (the advanced search page), and entering a search term, I see:

> Required parameter missing: search

I believe this is because the parameter `search` is required on this line: https://github.com/publiclab/plots2/blob/master/app/controllers/searches_controller.rb#L89

However, the form that generates the request does not supply that parameter: 

https://github.com/publiclab/plots2/blob/master/app/views/searches/_form.html.erb#L4

@ujithaperera and @david-days - is there a missing field there? What should the `search` parameter include? 

By contrast, this does not return any results (reindexing is actually erroring out for some reason), but it doesn't error, either:

https://publiclab.org/searches?search=flame

Finally, why doesn't this test line fail, if we're not supplying a `search` param? https://github.com/publiclab/plots2/blob/master/test/integration/search_flow_test.rb#L18

**Comment by david-days** [comment]
@jywarren 

I'll take a look. I've been playing around with the site's URLs and the form submission, and the behavior is definitely not what is expected.  Part of the issue seems to be that it's automatically redirecting to some of the fallback options in routes.rb (which would explain why the test is not erroring--it's getting an answer, but we're not checking that the response is correct.).

**Comment by david-days** [comment]
@ujithaperera @jywarren 

I also noticed that the ["advanced" form](https://github.com/publiclab/plots2/blob/master/app/views/searches/advanced.html.erb#L9) is putting out a different submission than the ["new" form](https://github.com/publiclab/plots2/blob/master/app/views/searches/_form.html.erb#L1)--this seems to be where the "searches" in your example url is coming from, @jywarren

**Comment by jywarren** [comment]
Are both needed, or is one deprecated? I'm most interested in whichever is
shown when you click "advanced search" from a regular search. I believe
that link redirects to https://publiclab.org/searches/new, no?

**Comment by jywarren** [comment]
I tried to make a change (probably wrong) and attempted to build out a test that'd catch this here: https://github.com/jywarren/plots2/commit/57b3923e3f569ad09f6779d355ec0d9882cc7527 -- feel free to pull in that commit or copy from it.

**Comment by genericlady** [comment]
I'll give this a shot

**Comment by genericlady** [comment]
The problem is with `search` since it's being required as part of the ruby strong params. I don't know if it's missing from the form or missing from the search params hash. I didn't have time to finish debugging it since everyone was leaving the meetup and I got there late. bon chance!

**Comment by jywarren** [comment]
Thank you! 

Looking at this again, I've pulled out that test I wrote in my last comment and created a pull request for it here: #952.

It looks like the code now in the PR should generate a `search` parameter from the form, and that the test matches that expectation as well. The query https://publiclab.org/searches?search=flame also now does not error, but returns no results, which for the time being is OK -- until we get the Solr service online. 

Thanks, @genericlady -- we'd love any additional help you're able to offer, if you're interested! There are a number of other issues up for grabs at https://github.com/publiclab/plots2/labels/help-wanted

**Comment by jywarren** [comment]
The PR still fails, due to:

```

================================================================================
Error: test_advanced_search_basic_test(SearchFlowTest): ActionView::Template::Error: undefined method `search' for #<SearchRecord:0x0055fff023a5a0>
app/views/searches/_form.html.erb:4:in `block in _app_views_searches__form_html_erb___3859669145889764336_47278865203440'
app/views/searches/_form.html.erb:1:in `_app_views_searches__form_html_erb___3859669145889764336_47278865203440'
app/views/searches/new.html.erb:6:in `_app_views_searches_new_html_erb___1398981614837015214_47278865461280'
test/integration/search_flow_test.rb:14:in `block in <class:SearchFlowTest>'
================================================================================
```

Looking at the code again, line 20 of `searches_controller.rb` uses the `search_params` method, here: 

https://github.com/publiclab/plots2/blob/master/app/controllers/searches_controller.rb#L89

```ruby
      params.require(:search).permit(:key_words, :main_type, :note_type,
```

This is odd to me -- we require the `search` parameter, but permit `:key_words` -- what's the difference? It looks to me that `:key_words` is what's actually used elsewhere in the code:

```ruby
(trusty)warren@localhost:~/sites/plots2$ grep -r key_word app/
app/views/searches/show.html.erb:                      <p> Your search - <strong><%= @search.key_words %> </strong> - </p>
app/views/searches/show.html.erb:                      <a href="<%= search_dynamic_url + '/'+ @search.key_words %>">Try Dynamic search</a>
app/views/searches/_form.html.erb:    <%= f.text_field :key_words, class: 'search-query form-control' %>
app/views/searches/index.html.erb:      <td><%= search.key_words %></td>
app/models/search.rb:  attr_accessible :key_words, :title, :main_type, :note_type, :min_date, :created_by,
app/models/search.rb:      fulltext self.key_words
app/models/search.rb:    ['node.title LIKE ?', "%#{key_words}%"] unless key_words.blank?
app/models/search_record.rb:  attr_accessible :key_words, :title, :main_type, :note_type, :min_date, :created_by,
app/models/search_record.rb:      fulltext self.key_words
app/models/search_record.rb:    ['node.title LIKE ?', "%#{key_words}%"] unless key_words.blank?
app/models/search_record.rb:    ['node.title LIKE ?', "%#{key_words}%"] unless key_words.blank?
app/controllers/searches_controller.rb:    set_sidebar :tags, @ssearch.key_words
app/controllers/searches_controller.rb:      params.require(:search).permit(:key_words, :main_type, :note_type,
```

Conversely, I don't see the `:search` parameter used anywhere else, although it was in this file from the very first commit. I'm tempted to just remove it!

**Comment by jywarren** [comment]
I pushed a new commit to #952 to see how that works.

**Comment by jywarren** [comment]
Resolved!!
