### ISSUE TITLE
Remove Already Subscribed Topics in The Trending Section

### ISSUE THREAD

**Issue by RuthNjeri** [publiclab/plots2#8957]
This issue is part of #8513

It will fix:

- [x] Removing already subscribed topics in the trending section

**Comment by mohitdmak** [comment]
Is this issue resolved or available?

**Comment by RuthNjeri** [comment]
Has been merged through https://github.com/publiclab/plots2/pull/9030/commits/bb5545c900b612e28d958eb9e3edb2650f088a63
