### ISSUE TITLE
Solr "exceeded limit of maxWarmingSearchers=2" error

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#896]
### What happened just before the problem occurred

I made a comment, as user 'tester', on a note, and got an "error" in the comment form. 

Then, the dashboard stopped responding -- got a 500 error. The comment sent, though!

The logs show:

```
Completed 500 Internal Server Error in 754.3ms

RSolr::Error::Http (RSolr::Error::Http - 503 Service Unavailable
Error: 'Error opening new searcher. exceeded limit of maxWarmingSearchers=2, try again later.','code'=>503}}

URI: http://localhost:8983/solr/default/update?wt=ruby
Request Headers: {"Content-Type"=>"text/xml"}
Request Data: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><commit softCommit=\"false\"/>"
```

@icarito, @ujithaperera, @david-days - do we need to increase that setting? 

I found that restarting Solr worked, though I still got a 500 on the dashboard for a few more reloads.

**Comment by jywarren** [comment]
Actually, I'm now redirected properly to /dashboard, but see a 500 error there now.

**Comment by jywarren** [comment]
And now looking normal again. Hmm.

**Comment by jywarren** [comment]
OK - is it possible we're making "too many commits at once" and why now, but not earlier? http://wiki.apache.org/solr/FAQ#What_does_.22exceeded_limit_of_maxWarmingSearchers.3DX.22_mean.3F

**Comment by icarito** [comment]
Hi,
I'm seeing extremely slow response when loggin in. Probably related? I'm on IRC.

**Comment by jywarren** [comment]
i have to move -- 10m, but will join you soon. htop didn't show too much resource usage...

**Comment by icarito** [comment]
it's slow but it responded correctly now

**Comment by icarito** [comment]
CPU is back to normal now...

**Comment by david-days** [comment]
It was running slow last night when I was testing out the search capabilities.  No errors (other than expected), but not the normal crisp response I was used to.

**Comment by icarito** [comment]
Any interaction on Solr seems to send the CPU on an intensive task. If I log in or log out, site slow to respond and Solr process consumes 100% CPU.

**Comment by icarito** [comment]
There are currently 37 solr processes running in the server. Is this normal Solr behaviour?

**Comment by icarito** [comment]
Yes it looks so because they are all children of one master Solr java process.

**Comment by jywarren** [comment]
I'm back at a more solid internet connection and joining IRC. I wonder if an index flush would be a good idea, since the biggest thing that happened in the last 12 hours is that I reindexed.

**Comment by jywarren** [comment]
http://daniel.hepper.net/blog/2010/11/howto-clear-solr-index/ says:

`curl http://localhost:8983/solr/update?commit=true -d  '<delete><query>*:*</query></delete>'`

to flush the index.

**Comment by jywarren** [comment]
We set up an ssh tunnel to the Solr admin and deleted the core, which had 300k+ docs, and unrequired Solr in production.

Currently investigating deleting old sessions from mysql -- hoping that will lighten the load on Solr. There are some 300k+ session records.

**Comment by jywarren** [comment]
We will circle back once session records are flushed, and check in after some sysadmin work on this. Thanks for patience.

**Comment by jywarren** [comment]
Going to close this as we're separately containerizing Solr.
