### ISSUE TITLE
Append keywords in questions tag filter as GET URL parameters

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#897]
At https://publiclab.org/questions, when you add a "filter" of a given tag, the URL is not changed -- the added tag filters are stored in the session.

It's important that the keywords should be be appended to the url instead of being stored in the session. The routing should be more like:

`https://publiclab.org/questions/spectrometry`

and for multiple tags, perhaps:

`https://publiclab.org/questions/spectrometry,second-tag,another`

These would be fetched in the questions_controller via `params[:id].split(',')` -- here: https://github.com/publiclab/plots2/blob/master/app/controllers/questions_controller.rb. The `index`, `answered`, `popular`, `liked` action use this functionality presently.

The sorting is done using the `sort_questions_by_tag` method in the application controller, where it sources from the session: https://github.com/publiclab/plots2/blob/master/app/controllers/application_controller.rb#L190-L200. This method is called in all the places mentioned above.

The addition and deletion of tags from the session is done using the methods in tag_controller listed here: https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L239-L267. So you need to modify these methods too.

The tag sorting interface (that generates the sessions, and would generate the URLs in our new plan) shown on the sidebar, is here: https://github.com/publiclab/plots2/blob/master/app/views/tag/_sorting.html.erb

That itself might be moved into this directory for easier management: https://github.com/publiclab/plots2/blob/master/app/views/questions/

## Steps to solve
Summarizing the steps below
- [ ] Modify the tag methods mentioned [here](https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L239-L267) to append the keywords in url instead of session and fetch them accordingly
- [ ] Modify the `sort_questions_by_tag` [method](https://github.com/publiclab/plots2/blob/master/app/controllers/application_controller.rb#L190-L200) according to changes made and deprecate the use of session and use GET url parameters
- [ ] Modify the `index`, `answered`, `popular`, `liked`actions in questions controller accordingly
- [ ] Move the tag sorting template from [views/tag](https://github.com/publiclab/plots2/blob/master/app/views/tag) --> [views/questions](https://github.com/publiclab/plots2/blob/master/app/views/questions/
)

**Comment by jywarren** [comment]
@ananyo2012 -- any chance you could take this one on? I understand if you're busy!!!

**Comment by ananyo2012** [comment]
Sure Jeff I can work on this. In fact I was just onto other issues as well.

Uh sorry to say it here I recently sent you a mail. Do have a look at it.
ᐧ

**Comment by jywarren** [comment]
Thanks and i got your email -- chatting w/ other staff about it today and
we appreciate your interest!

**Comment by jywarren** [comment]
I've created a start to this in #929 -- and key sections are:

Controller logic: https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L238-L268

The form itself is here: https://github.com/publiclab/plots2/blob/master/app/views/tag/_sorting.html.erb#L26-L46

**Comment by jywarren** [comment]
@ryzokuken - if you're looking for new projects, this is also a key one I've been having trouble with. It seems to be related to a recurrence (for me) of bug #638, where no questions are shown:

![screenshot](https://cloud.githubusercontent.com/assets/7490478/17214737/f94b83ce-549f-11e6-97fb-a88004b71a0b.png)

**Comment by ryzokuken** [comment]
@jywarren Sure, I'll look into it.

**Comment by jywarren** [comment]
@ananyo2012, perhaps this'd be a good GCI candidate, esp. if you're familiar with this code?

**Comment by ananyo2012** [comment]
Yes this is a good one. Holds importance for improving the sort feature. I can improve documentation for this issue and then we can add this as a task.

**Comment by jywarren** [comment]
Closed, hooray!
