### ISSUE TITLE
Signup sequence overhaul

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#899]
The signup interface is perhaps our most important design of the entire site -- if people can't get past it, all participation/contribution is limited. Let's take a thorough look at it, esp. the captcha, which we've heard reports of folks getting stuck at.

The captcha of the signup sequence looks like this now:

![screen shot 2016-10-17 at 4 13 09 pm](https://cloud.githubusercontent.com/assets/24359/19453778/a31ffe7e-9484-11e6-9b3c-e102b0c25ac8.png)
### What happened just before the problem occurred

> didn’t like the selecting each question, picked wrong and each time she did it erased what she had already put in

When you get it wrong you get a new set of questions, and it deletes username/pwd fields as well.

@steviepubliclab suggests changing questions, I agree. avoid terms that require a sense of humor, which may not translate. Something more welcoming. 

Look into login via Facebook
### Relevant URLs

https://publiclab.org/signup
### New questions

Let's come up with some more translatable questions! Leave suggestions below.

**Comment by jywarren** [comment]
The questions could also say, for example:

> Are you a real person?
> • Yes | • No

> Are you here to post advertisements on our site?
> • Yes | • No

> Do you promise to follow the Code of Conduct?
> • Yes | • No

**Comment by ebarry** [comment]
Let's also connect this train of thought with the idea of adding a question
at Registration related to evaluation

--

+1 336-269-1539
@lizbarry <http://twitter.com/lizbarry>

**Comment by steviepubliclab** [comment]
Hi there a few questions:

- I like the evaluation question idea but for the spam filter aspect, the
person would have to choose only the one option right?
- I like to COC thing too, do we have a link on the page to it?
- I was just reading that the yes/no questions are easier for spambots to
get past than typed answers. How successful has this system been?
-What about the google system that shows the person numbers or scrambled
words to type?

-Stevie

**Comment by jywarren** [comment]
> I like the evaluation question idea but for the spam filter aspect, the
person would have to choose only the one option right?

Yeah, I'm hesitant to mix a spam filter with evaluation questions... that sounds complicated from a study design perspective. 

> I like to COC thing too, do we have a link on the page to it?

We don't, but can. What would the wording be? Perhaps similar to and/or alongside the "you agree to open source" text at the bottom. I suggest something starting with "A respectful space is essential if we're to work together. ..."

> I was just reading that the yes/no questions are easier for spambots to
get past than typed answers. How successful has this system been?

I don't know of a way to automatically evaluate text answers; the current system just knows that one answer is correct and one is wrong, and sadly computers aren't that great at any other kind of test :-/

> What about the google system that shows the person numbers or scrambled
words to type?

We used to use that and it basically doesn't work anymore -- automated spambots can get past it. There's [a new system](https://www.google.com/recaptcha/intro/index.html) where you just check a box, but I don't know the efficacy statistics on it... and there are [some concerns](http://www.businessinsider.com/google-no-captcha-adtruth-privacy-research-2015-2):

> ...according to research from AdTruth, seen by Business Insider, Google’s No CAPTCHA reCAPTCHA appears to be collecting personally identifiable additional data beyond mere behavioral cues about their users, too.

There's also some on how captchas are not accessible here: https://www.w3.org/TR/turingtest/

But, i do agree:

1. yes, we should put CoC in the signup page
2. we can look at eval, but needs to be distinct from Captcha and not block signup process unduly

**Comment by steviepubliclab** [comment]
Hello,

RE wording on COC. I like the idea of including it on the bottom.  How
about this, most of it is strait from the COC:
"The code of conduct applies to all spaces managed by the Public Lab
community and non-profit, both online and in person."

With a link? Could it come up in a new tab so people don't loose the login
page?

-Stevie

**Comment by ryzokuken** [comment]
or we could use Google's [reCAPTCHA API](https://www.google.com/recaptcha/intro/index.html).

**Comment by jywarren** [comment]
We had trouble with the previous version of their API, in that spammers
were getting through. But perhaps the new version works better -- it's
worth a try, esp. if it makes it easier for people to create accounts.

**Comment by ryzokuken** [comment]
@jywarren Please look into it and tell me if we're okay with giving it a try.

**Comment by jywarren** [comment]
I tried to look for data on success rates over time or at least in comparison between the old and new versions of reCaptcha -- that'd be the greatest mark of success I'd look for. If you can find any data on this, please share!

**Comment by steviepubliclab** [comment]
Had another incident lately with people having trouble creating a UN.
anyone have other thoughts on reCaptcha ? Seems like an easier system than
asking people questions.

**Comment by jywarren** [comment]
I'm mostly worried about the effectiveness of reCaptcha, since if it
doesn't work as well, there'll be increased work for moderators --
potentially a lot of increased work. If anyone has data on the new "just
check the box" reCaptcha system's effectiveness, we'd have more ability to
move forward on this.

**Comment by jywarren** [comment]
I broke out the CoC link into its own issue: #1117.

I'm trying to think how we can move forward on this, and I think we could try the new reCaptcha system out if we were sure we could switch back if it doesn't work to stop spammers. 

But how might we evaluate if it's easier than the questionnaire? I think we can just assume that it is, but I want to be thorough about whether screen readers and other accessibility issues will be an improvement over the current login system.

**Comment by steviepubliclab** [comment]
+1 give reCaptcha a try. In terms of evaluating it on success, I'll have my
ears open as I work with people in setting up profiles, just anecdotal, but
still helpful I think.

-Stevie

**Comment by ryzokuken** [comment]
@jywarren: I'd love to work on this as soon as we finalize the design.

**Comment by steviepubliclab** [comment]
Hi,
Just an anecdote, I just had a call with a new community member who had a
lot of trouble with the current log in. Specifically, she couldn't tell how
the 4 questions were set up (as in choose one from each row).
Alternatively, she signed up for a google group on the phone with me as
well with a reCaptcha. She was confused at first on it, but then it went
really quickly as soon as she clicked it and she could visually see what
was happening and understood.

-Stevie

**Comment by jywarren** [comment]
Looking carefully at the 4-question system, I think there are multiple issues at stake here:

1. It says to "answer questions", but instead of questions there are these "bars" where you choose one of two options -- with no further explanation
2. It's not clear that you need to choose one of each pair, which could be made more clear by breaking them up and numbering them 1-4, prompting with "For each of the four paired statements, choose the one that's more accurate."
3. We could show a stronger **OR** between each pair.
4. As above, we could choose a new set of questions that are easier to understand and answer, such as "The sun is brighter than the moon." and "An elephant is bigger than a mouse." Or: "Which is bigger? [ ] Elephant **OR** [ ] Mouse"

The reason I suggest this is that the process of switching back to reCaptcha is a bit more involved (we'd have to have it be off for development and testing), and would take more time, whereas here, the small design tweaks and new set of questions could be done pretty quickly with some input from @steviepubliclab and @ebarry on formulating new questions, so would be likely to be finished faster. 

I'm still fine going either way, but wanted to put out this suggestion, thanks!

**Comment by jywarren** [comment]
That is to say, I think that we haven't fully explored why the four-question system is difficult for people, and hearing from Stevie and others, and carefully looking at it, suggests to me that it's not just the content of the questions that's at issue, but that there may be more we can easily do to dramatically improve the system without taking on the project of re-integrating reCaptcha -- if we choose to go that way. Open to input, just wanted to put these thoughts out there for consideration!

**Comment by ebarry** [comment]
Updating this issue to report in that I heard from @steviepubliclab that at the last in-person Mapknitter workshop, 50% of the attendees were unable to get through our login screen on their own, and needed to be helped by at their individual computers one by one. Let's discuss the prioritization of this issue? Right now it's not prioritized but perhaps should be.

**Comment by jywarren** [comment]
Hi, thank you -- would you two be able to take a look at my suggestions and offer input on next steps? Thank you, i know it got lost over the holidays.

**Comment by jywarren** [comment]
Fix is submitted at #1210 but has some serious additional changes - users are sometimes asked to "trace" images or choose between them. I don't think this'll happen often! But it may come up from time to time. I left screenshots to review.
