### ISSUE TITLE
Add Number of Wikis to The Topic Card

### ISSUE THREAD

**Issue by RuthNjeri** [publiclab/plots2#8992]
This is Part of #8513

Add the number of wikis to the topic card

Refer To #8935 (comment)

**Comment by RuthNjeri** [comment]
Hi @ebarry and @jywarren I am looking into how I'll add the number on the top card. 
Should the total number of wikis and notes be included in the posts section like below and how it currently is on the site
![Screenshot 2021-01-15 at 15 42 55](https://user-images.githubusercontent.com/7622875/104728700-5b8a8a80-5748-11eb-93ff-cbdb7f8b2da7.png)

Or should it use this other approach of separating the two and including links to either the notes and wiki?

![Screenshot 2021-01-15 at 15 40 38](https://user-images.githubusercontent.com/7622875/104728673-4dd50500-5748-11eb-8417-a09ada5e8e57.png)

I think, either way, they all kind of lead to the same page..but someone might be interested in wikis more...let me know what you think

**Comment by jywarren** [comment]
Hi @RuthNjeri - thank you, why don't we do: `2 notes | 4 wikis` as the format? Removing the >> will trim space, and this keeps it pretty short still. Will the extra text cause us trouble on narrow screens?

Thanks!

**Comment by RuthNjeri** [comment]
Hi @jywarren that looks great! I'll test it out and let you know if it causes any trouble on narrow screens. Thanks!

**Comment by ebarry** [comment]
I"m excited to see this, i think it will be great 🌟
