### ISSUE TITLE
Small style adjustments for new dashboard

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#8999]
@RuthNjeri this looks amazing!

![image](https://user-images.githubusercontent.com/24359/104360174-a903bf00-54de-11eb-9b02-332e4e3b8270.png)

Just noting a few small things to refine --

* [x] some small text is in Junction Light (the font) and i wonder if we can standardize the size and font -- i think it's Arial -- in the same sans-serif where we see `90 Following` in our tag cards. See how on GitHub, all small text is relatively consistent in size and style? 
* [x] An exception is `Follow more topics` which i find myself wishing to be the same size as `Remembering Tonawanda` and `everything` in this screenshot
* [x] I notice the special tag `everything` is displayed, which i think we should hide - i believe it's tag `tid=0` -- it's a special tag for following ALL content. We can ignore it and hide it on this page!

I think that's it! Thanks again and congrats on a terrific job!

**Comment by RuthNjeri** [comment]
Thanks @jywarren, that all makes sense. I remember having a tough time standardizing the font family...
