### ISSUE TITLE
Remove sidebars from templates

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#9014]
We removed the sidebar methods in the controllers here https://github.com/publiclab/plots2/issues/8803. This is a follow up to identify and remove the instances where the sidebar is being rendered...we expect some tests to fail, so this might involve some rewriting of tests

**Comment by Manasa2850** [comment]
@cesswairimu I would like to try this out!

**Comment by cesswairimu** [comment]
Great :tada:  assigned it to you . Thanks
