### ISSUE TITLE
Reverse order of comments display on question pages

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#903]
Just expressing a preference for the comments on the questions page to post the most recent **on the bottom instead of the top** -- so in chronological, instead of reverse-chronological order. 

This would help make it consistent with the rest of the commenting features on Public Lab and is the natural way we read, at least in english :) 

(related to #884, an overall UI design issue for Q&A)

The code for this section can be found here: https://github.com/publiclab/plots2/blob/master/app/views/questions/_comment.html.erb

### Relevant URLs

Example question: https://publiclab.org/questions/stevie/09-06-2016/question-has-anyone-used-a-timelapse-camera-in-stream-monitoring

Screenshot:

![screen shot 2016-10-18 at 1 09 08 pm](https://cloud.githubusercontent.com/assets/24359/19488265/19268908-9534-11e6-94a5-b7f4e9cbd787.png)

**Comment by alexey-klimuk** [comment]
Hi guys, I've just created pull request for this issue https://github.com/publiclab/plots2/pull/926

**Comment by jywarren** [comment]
Great, thanks -- I'll check it out!

**Comment by jywarren** [comment]
Solved today, thanks a lot!
