### ISSUE TITLE
Add Translations To The Questions Index Page

### ISSUE THREAD

**Issue by RuthNjeri** [publiclab/plots2#9033]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the files linked below in the `https://github.com/publiclab/plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:
Add translation lines for the question index page in the `config/locales/en.yml`

https://github.com/publiclab/plots2/blob/2b2bd90290f22d5a5ff709b25b1a40e11094db7e/config/locales/en.yml#L661-L662
Indent the lines below after line 662 above...

```diff
  questions:
    index:
      recently_commented: Recently Commented
      recently_commented_questions: Recently commented questions
      popular_questions: Popular Questions
      most_viewed_questions: Most viewed questions
      unanswered_questions: Unanswered Questions
      liked_questions: Liked Questions
      most_liked_questions: Most liked questions
```

Add the lines below in the file from
https://github.com/publiclab/plots2/blob/2b2bd90290f22d5a5ff709b25b1a40e11094db7e/app/views/questions/index.html.erb#L3-L10

```diff
+<h2><%=translation('questions.index.recently_commented')%> <small class="d-md-none d-lg-inline"><%=translation('questions.index.recently_commented_questions')%></small></h2>
  <% elsif params[:action] == 'popular' %>
+<h2><%=translation('questions.index.popular_questions')%> <small class="d-md-none d-lg-inline"><%=translation('questions.index.most_viewed_questions')%></small></h2>
  <% elsif params[:action] == 'unanswered' %>
+<h2><%=translation('questions.index.unanswered_questions')%> <small class="d-md-none d-lg-inline"><%=translation('questions.index.unanswered_questions')%></small></h2>
  <% elsif params[:action] == 'liked' %>
+<h2><%=translation('questions.index.liked_questions')%> <small class="d-md-none d-lg-inline"><%=translation('questions.index.most_liked_questions')%></small></h2>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by YusufAbdelaziz** [comment]
Can I work on this?

**Comment by RuthNjeri** [comment]
Hi @YusufAbdelaziz yes you can.. I have assigned it to you..

**Comment by YusufAbdelaziz** [comment]
I've made a PR, could you please check it?

**Comment by RuthNjeri** [comment]
Sure..on it..

**Comment by pawan-nirpal-031** [comment]
Hello Folks, I am a complete beginner to open-source and Github contributions, I'd like to start contributing with this beginner-friendly project, `https://github.com/publiclab/plots2/blob/2b2bd90290f22d5a5ff709b25b1a40e11094db7e/config/locales/en.yml`
This file is asking me to indent lines 661 and 662, but I suppose I have to be on a branch to be able to make any changes to the file, I was wondering if anyone here could help me out getting started and tell me how exactly do I complete this particular task. what do I have to do, please be considerate of a newbie. Thanks in advance.

**Comment by RuthNjeri** [comment]
Hi @pawan-nirpal-031 I have shared some links from your original comment here https://github.com/publiclab/plots2/issues/9040#issuecomment-763608031

**Comment by RuthNjeri** [comment]
Closing this issue, it has been fixed through https://github.com/publiclab/plots2/pull/9038
