### ISSUE TITLE
Ensure The Trending Method Does Not Fail If Subscriptions is Empty

### ISSUE THREAD

**Issue by RuthNjeri** [publiclab/plots2#9034]
This is part of #8513

Ensure the @tag_subscriptions doesn't make the trending function fail if it is empty.
Refer to this comment https://github.com/publiclab/plots2/pull/9030#discussion_r559734612

**Comment by RuthNjeri** [comment]
Hi @jywarren...please have a look at a comment I've shared based on this task.. it is in response to your original concern https://github.com/publiclab/plots2/pull/9030#discussion_r561180855

**Comment by RuthNjeri** [comment]
Retagging you on this @jywarren 😄  I think my comment notification was lost in the noise of other notifications....

**Comment by RuthNjeri** [comment]
Here is the implementation just incase you are not able to find it quickly...
[
![Screenshot 2021-01-29 at 16 35 03](https://user-images.githubusercontent.com/7622875/106281240-01adb880-6250-11eb-8f9b-6f8dfd3dc53b.png)
](url)

**Comment by jywarren** [comment]
Ah, how exactly can I help here? Have you tried triggering such an error, maybe in a unit test? if so maybe we can see if we can skip this based on what happens? Thanks Ruth!!

**Comment by jywarren** [comment]
And sorry for missing this!!

**Comment by RuthNjeri** [comment]
That makes sense, I'll add a unit test.
