### ISSUE TITLE
New form design for asking questions

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#904]
Currently we re-use the basic note posting form at https://publiclab.org/post for questions. We should revise this to be more specific to, and helpful for, question asking.

Questions are often asked by people new to Public Lab, who will need extra clarity and context. Here's a design which addresses this:

![screen shot 2016-10-18 at 12 44 10 pm](https://cloud.githubusercontent.com/assets/24359/19487437/d0cd836c-9530-11e6-8672-fe0d2de03aa4.png)

To implement, we'll need a new form at https://github.com/publiclab/plots2/blob/master/app/views/editor/ -- maybe called `https://github.com/publiclab/plots2/blob/master/app/views/editor/question.html.erb`?

That would be accessible (i believe) at `/editor/question`. I've created a separate issue for the routing portion to actually use the form: #910. (This is now complete!)

Now we need to tackle integration of the rich editor, at https://github.com/publiclab/PublicLab.Editor/

This can be done similarly to how it was done here: https://github.com/publiclab/plots2/tree/master/app/views/editor/rich.html.erb -- 

Happy to help with this one -- it's big!

**Comment by jywarren** [comment]
@carolineh101 - I know you're busy, but curious if this issue is of interest to you! @steviepubliclab and I did some design work on it and it'd be a really key improvement to the Q&A system. Thanks!

**Comment by carolineh101** [comment]
I'd love to work on this issue!  However, given that I'm in school, it may take a while before I have updates on it – would that be ok?

**Comment by jywarren** [comment]
Sure -- would it help if we tried to break it into pieces -- say, one for
separating out the question form, another for the actual design work, maybe
a third for testing the template redirect, for example?

**Comment by carolineh101** [comment]
Yes, that would definitely help!

**Comment by jywarren** [comment]
OK -- I broke out the routing tasks with some extra steps into #910!

**Comment by jywarren** [comment]
Note from open call via @ebarry  -- numbered steps are really helpful for guiding others through the new rich editor -- should add them here too.

**Comment by jywarren** [comment]
I would start by coping the rich editor template and then modifying it to more closely match the mockup above.

**Comment by 500swapnil** [comment]
@jywarren Okay I will have a look!

**Comment by jywarren** [comment]
You may want to make a new template file to start with, rather than overwrite this one: https://github.com/publiclab/plots2/blob/master/app/views/editor/question.html.erb

Such as `questionRich.html.erb` -- that way we can test it out before making changes to the current one. Make sense? Thank you!!

**Comment by 500swapnil** [comment]
@jywarren Ok I will start by copying the template and work on the copy!

**Comment by 500swapnil** [comment]
@jywarren We may need to include most of what is there in the  https://github.com/publiclab/plots2/tree/master/app/views/editor/rich.html.erb template. Am I right? And is there any way of viewing individual templates?

**Comment by jywarren** [comment]
Yes, i think including much of that is appropriate, yes (though not
MainImage).

Sorry, how do you mean viewing individual templates?

Thanks!

**Comment by 500swapnil** [comment]
I mean viewing them on a browser. I can get an idea of the design changes while integrating the editor.

**Comment by jywarren** [comment]
ah yes, i believe you should be able to access a template named
"questionRich.html.erb" at "/editor/questionRich" -- though you should test
that locally. If it doesn't work, we'll need to add a temporary
/config/routes.rb entry.

**Comment by 500swapnil** [comment]
@jywarren I've opened a PR #1177 . Please have a look!
