### ISSUE TITLE
Continued: Add Translation To The Questions Index Page

### ISSUE THREAD

**Issue by RuthNjeri** [publiclab/plots2#9040]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the files linked below in the https://github.com/publiclab/plots2 repository (press the little pen Icon) and edit the line as shown below.

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

This is a continuation of this issue https://github.com/publiclab/plots2/issues/9033
Once this PR https://github.com/publiclab/plots2/pull/9038 has been merged you can begin working on this one. If you know how to resolve merge conflicts feel free to comment below and I can assign it to you.

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

Add translation lines for the question index page in the` config/locales/en.yml`
https://github.com/publiclab/plots2/blob/2b2bd90290f22d5a5ff709b25b1a40e11094db7e/config/locales/en.yml#L661-L664
Add the translations from `ask_question` to `liked`

```
  questions:
    index:
      explanation: "Ask a question to the Public Lab community to help you in your
        environmental exploration."
      ask_question: Ask a question here
      to_ask_question: To ask a question, please
      log_in: log in
      or: or
      sign_up: sign up
      first: first.
      recently_asked: Recently Asked
      popular: Popular
      unanswered: Unanswered
      liked: Liked
```

https://github.com/publiclab/plots2/blob/2b2bd90290f22d5a5ff709b25b1a40e11094db7e/app/views/questions/index.html.erb#L23-L25
```diff
-<h4>Ask a question here</h4>
+<h4><%=translation('questions.index.ask_question')%></h4>
<% if !current_user %>
-<p>To ask a question, please <a href="/login?return_to=/questions">log in</a> or <a href="/signup?return_to=/questions">sign up</a> first.</p>
+<p><%=translation('questions.index.to_ask_question')%><a href="/login?return_to=/questions"><%=translation('questions.index.log_in')%></a> <%=translation('questions.index.or')%> <a href="/signup?return_to=/questions"><%=translation('questions.index.sign_up')%></a><%=translation('questions.index.first')%></p>
```
https://github.com/publiclab/plots2/blob/2b2bd90290f22d5a5ff709b25b1a40e11094db7e/app/views/questions/index.html.erb#L53-L73
```diff
- <i class="fa fa-refresh"></i> <span class="d-none d-lg-inline"> Recently Asked</span>
+<i class="fa fa-refresh"></i> <span class="d-none d-lg-inline"> <%=translation('questions.index.recently_asked')%></span>
</a>
</li>
<li class="nav-item">
<a class="nav-link <% if params[:action] == "recently_commented" %> active <% end %>" href="/questions/recently_commented/">
-<i class="fa fa-check"></i> <span class="d-none d-lg-inline"> Recently Commented</span>
+<i class="fa fa-check"></i> <span class="d-none d-lg-inline"> <%=translation('questions.index.recently_commented')%></span>
</a>
</li>
<li class="nav-item">
<a class="nav-link <% if params[:action] == "popular" %> active <% end %>" href="/questions/popular/">
-<i class="fa fa-bolt"></i> <span class="d-none d-lg-inline"> Popular</span>
+<i class="fa fa-bolt"></i> <span class="d-none d-lg-inline"> <%=translation('questions.index.popular')%></span>
</a>
</li>
<li class="nav-item">
<a class="nav-link <% if params[:action] == "unanswered" %> active <% end %>" href="/questions/unanswered/">
-<i class="fa fa-question-circle"></i> <span class="d-none d-lg-inline"> Unanswered</span>
+<i class="fa fa-question-circle"></i> <span class="d-none d-lg-inline"> <%=translation('questions.index.unanswered')%></span>
</a>
</li>
<li class="nav-item">
<a class="nav-link <% if params[:action] == "liked" %> active <%end %>" href="/questions/liked/">
-<i class="fa fa-star-o"></i> <span class="d-none d-lg-inline"> Liked</span>
+<i class="fa fa-star-o"></i> <span class="d-none d-lg-inline"> <%=translation('questions.index.liked')%></span>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by 1liale** [comment]
Hi it's my first time contributing to open source, I would be interested in helping out.

**Comment by pawan-nirpal-031** [comment]
I am making progress, thankful to this project.

**Comment by RuthNjeri** [comment]
Hi, @pawan-nirpal-031 I have just seen your comment on https://github.com/publiclab/plots2/issues/9033#issuecomment-763379793 .... Please have a look at these steps on how to edit files from an editor...also, have a look at the ReadMe file on steps to set up the repository and contributing steps.. https://github.com/publiclab/plots2/blob/main/README.md

Please comment here or share any issues you face on https://gitter.im/publiclab/publiclab... once you are able to set up the up and have an idea on how to contribute, I'll be happy to create another First timer issue for you @pawan-nirpal-031. Thank you.

Hi, @1liale you were first to comment, I'll assign this to you, thanks for reaching out. Let me know via commenting here if you have any questions.

**Comment by 1liale** [comment]
@RuthNjeri  hey sorry if this is a dumb question but just to clarify, you would like me to keep the YAML file as it is but do the same translation done for "ask_a_question" in the html file for items from "ask_a_question" to "liked"?

**Comment by RuthNjeri** [comment]
Hi, @1liale that's a great question!

Yes, keep the file as it is and only add the "ask_a_question" to "liked"...I added the other items because I thought this https://github.com/publiclab/plots2/pull/9038 would be merged first... The yaml file should look this way


```
  questions:
    index:
      explanation: "Ask a question to the Public Lab community to help you in your
        environmental exploration."
      ask_question: Ask a question here
      to_ask_question: To ask a question, please
      log_in: log in
      or: or
      sign_up: sign up
      first: first.
      recently_asked: Recently Asked
      popular: Popular
      unanswered: Unanswered
      liked: Liked
```

I have updated the issue description to reflect this...thanks for asking...let me know if you have other questions...

**Comment by 1liale** [comment]
![image](https://user-images.githubusercontent.com/38883331/105286659-bf67e580-5b84-11eb-96ea-a1e58d9f78fc.png)  @RuthNjeri  Do I also add (recently_commented: "recently commented") to the en.yml file? Otherwise the translation isn't referencing anything

**Comment by RuthNjeri** [comment]
Good catch @1liale, please add it...

**Comment by 1liale** [comment]
Hi @RuthNjeri could you review my PR. I hope that's how you wanted it but let me know if there's any issues that need fixing.
