### ISSUE TITLE
Problem with moderation notifications. 

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#906]
### What happened just before the problem occurred

Notifications are repeating in their email delivery, again and again, as of today around 11AM. 
![screen shot 2016-10-19 at 1 35 43 pm](https://cloud.githubusercontent.com/assets/161439/19530238/0e865d7a-9601-11e6-9801-a18f59c9d2a8.png)

**Comment by ebarry** [comment]
I have not received any further notifications since 1:30pm today, so not sure if this is fixed?

**Comment by icarito** [comment]
I've not investigated still. I received the duplicates as well.

**Comment by jywarren** [comment]
Hi, Liz - do you mean that you get each one twice? This may be because you
are both subscribed to moderators@ AND your'e a moderator on plots2. Can
you check the message details on each to see if that's the case? And can
you make the title a bit more specific -- like "duplicated moderation
emails"

**Comment by ebarry** [comment]
OK, so i think that there were just so many posts (almost 40) with extremely similar titles that i thought i was getting duplicates, but actually i don't think they were. I would close this issue now.
