### ISSUE TITLE
Display Notification for Emoji Reactions on a Comment

### ISSUE THREAD

**Issue by noi5e** [publiclab/plots2#9071]
What do you all think about having a Noty Notification displayed when user reacts to a comment?

### Expected
**For example**, [here is a **video** that shows notification when user DELETEs a comment](https://user-images.githubusercontent.com/4361605/105646033-6339e580-5e52-11eb-9574-e535a9abe792.mov).

An image of **Delete Notification** below:
<img width="1431" alt="Screen Shot 2021-01-24 at 2 44 45 PM" src="https://user-images.githubusercontent.com/4361605/105646111-dba0a680-5e52-11eb-867d-afffb611f138.png">

We could have a similar notification for when user reacts to a comment. The notification could have a string like:
- _Reacted with "Hooray!_
- _Reacted with "Thumbs Down" to Comment_
- _Removed "Thumbs Down" Reaction_

### Actual
This [**video** shows what currently happens when the user emoji-reacts to a comment](https://user-images.githubusercontent.com/4361605/105646133-0559cd80-5e53-11eb-9776-06695455bcb4.mov)

- No notification at all
- Sometimes there can be a delay after the user clicks on the reaction, and before the reaction appears on the comment. This can be a little confusing sometimes. Maybe a notification would help this be less confusing?

On the other hand, I know that for example facebook doesn't flash notifications when a user likes a post. Is this something we even want to do? If so, I'm happy to help guide whoever takes this issue on.

**Comment by noi5e** [comment]
### What to Change
Here's where the comment view sends a request to make a user reaction on a comment:
https://github.com/publiclab/plots2/blob/38e37eb20602d799ab935e4e281f32782e856fda/app/views/notes/_comment.html.erb#L83-L92

Particularly these two lines are making an `<a href>` tag that sends a request to `/comment/like`:
https://github.com/publiclab/plots2/blob/38e37eb20602d799ab935e4e281f32782e856fda/app/views/notes/_comment.html.erb#L87-L88

Which calls this controller here:
https://github.com/publiclab/plots2/blob/38e37eb20602d799ab935e4e281f32782e856fda/app/controllers/comment_controller.rb#L140-L160

The **delete comment** example I mentioned above uses this JS here to flash the notification:
https://github.com/publiclab/plots2/blob/38e37eb20602d799ab935e4e281f32782e856fda/app/views/notes/_comment.html.erb#L107-L117

- Maybe instead of an `<a>` link to send the request to emoji-react, we send a jQuery AJAX request like above.
- Then in the callback for that request, put a `notyNotification` to flash the response
- We would also probably need to think about [debouncing](https://css-tricks.com/debouncing-throttling-explained-examples/) so the user doesn't spam the emoji buttons by clicking over-and-over again.

**Comment by RATED-R-SUNDRAM** [comment]
I would like to work on this issue

**Comment by noi5e** [comment]
@RATED-R-SUNDRAM go for it! comment on this page or in chat if you'd like help with anything!

**Comment by shadowoflight** [comment]
@noi5e  can I work on this issue if @RATED-R-SUNDRAM is not working on this?

**Comment by noi5e** [comment]
@shadowoflight Good question! @RATED-R-SUNDRAM Do you still want to work on this issue? Are you stuck anywhere and need help? If you don't want to work on this anymore, are you okay with @shadowoflight taking it over?

**Comment by shadowoflight** [comment]
Since @RATED-R-SUNDRAM has no response it will be fair enough if I take up the issue and start working @noi5e

**Comment by noi5e** [comment]
@shadowoflight Go ahead!

**Comment by noi5e** [comment]
@shadowoflight How is it going with this issue? Were you able to find a way to get the app set up locally or on GitPod? Please let me know if there's any way I can help 😄

**Comment by govindgoel** [comment]
@shadowoflight are you working on this

**Comment by govindgoel** [comment]
@noi5e Can you assign this to me

**Comment by noi5e** [comment]
@shadowoflight, You mentioned that you hadn't started working on this because of exams. Can you please let us know when you'll be ready to start this?

**Comment by waridrox** [comment]
Hey @noi5e, meanwhile can I try to solve this :)

**Comment by noi5e** [comment]
@govindgoel If you want this issue it's yours. Can you claim it in the next 24 hours? If I don't hear from you, I'll assign it to @waridrox

**Comment by govindgoel** [comment]
@noi5e I can start working on this.

**Comment by waridrox** [comment]
Since there is no further update on this, @noi5e could you please assign it to me, I would like to at least try and see if this can be resolved. Thanks :)

**Comment by noi5e** [comment]
@waridrox Go ahead and start working on it! You can submit a PR linking this issue. Thanks.

**Comment by govindgoel** [comment]
I am working on it the issue I faced @noi5e is with ajax call i am able to put a notyNotification but while remvoing the reacted emoji, it still shows reacted with in the notification ideally it should show removed the particular emoji, there is some issue with the post request i'm currently looking into it. And I should have followed up early :/

**Comment by waridrox** [comment]
> And I should have followed up early :/

No worries 👍 pls continue...

**Comment by noi5e** [comment]
@govindgoel Ah okay! Sorry about that, I wasn't sure if you were working on it. @govindgoel, definitely continue working on it. I'm happy to help you too! Don't hesitate to leave a comment about what you find.

**Comment by KarishmaVanwari** [comment]
Is this issue open? If yes, I would like to work on this. @noi5e

**Comment by Yavnikaa** [comment]
If this issue is open, I would like to take this up. May I?

**Comment by noi5e** [comment]
Apologies for the delay! @Yavnikaa, as you are the most recent interested person, feel free to take up this issue!

**Comment by iem-saad** [comment]
@noi5e Hi, is anyone working on this issue? I would like to work on it if possible. Thanks

**Comment by noi5e** [comment]
@iem-saad Yes, feel free to go ahead and make a PR!

**Comment by iem-saad** [comment]
Thanks for allowing me, will ping you when done or help needed.

**Comment by iem-saad** [comment]
Hi @noi5e, you use rbenv or RVM for managing ruby versions? I use RVM and having following issue while project setup. Do you know any workaround??
https://bugs.ruby-lang.org/issues/18658

**Comment by noi5e** [comment]
@iem-saad I recommend asking for config help in Public Lab's Gitter channel... Or browse our open issues, you might find that someone else has encountered the same setup bug.

**Comment by iem-saad** [comment]
Hi, @noi5e I hope you are well. I've completed the task can you please review it #11356 
Thanks.
