### ISSUE TITLE
Weekly Community Check-In #89  - Create FTOs

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#9077]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Create First-Timer-issues

This week lets take time to create ftos, convert first-timer-candidates into ftos or indetify fto-candidates and label them or leave a comment asking a maintainer to label. Thanks everyone.

## This week's focus Issues

These are issues that are of high priority and requests from our
large community that use the software. 

https://github.com/publiclab/plots2/labels/high-priority

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note to focus issues contributors

Many thanks to our fto creators :1st_place_medal: :1st_place_medal: @Manasa2850 @RuthNjeri @noi5e @gauravahlawat81  🥇:1st_place_medal: 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by cesswairimu** [comment]
New first-timer planning issue is here https://github.com/publiclab/plots2/issues/9083

**Comment by jywarren** [comment]
Thanks Cess for the new first-timer issue!

I'm focused on helping out with Outreachy issues for the rest of the day! https://github.com/publiclab/plots2/labels/outreachy

**Comment by RuthNjeri** [comment]
Thanks for opening this up @cesswairimu 🎉 
If I create an FTO issue, should I link it to #9083?

**Comment by cesswairimu** [comment]
@RuthNjeri yeah, I see you've already got the hang of it and thanks for fto :tada:

**Comment by cesswairimu** [comment]
Hi all, would anyone like to open this week's check-in?

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/9112. Thanks all
