### ISSUE TITLE
Invite to Barnraising! 

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/plots2#909]
Hi there,
New issue alert :). 

Just wanted to invite everyone who has been working on, or following, the Public Lab codebase to the annual event we have coming up November 11-13th. Come and meet the community who's using this code!

![screenshot 2016-08-31 at 12 13 53 pm](https://cloud.githubusercontent.com/assets/7490478/19565365/2df88916-96ac-11e6-808a-8faa8afba4ec.png)

About the event:: 

The "Barnraising" event is the annual event hosted by the Public Lab community. In this event we all come together to:
- test environmental monitoring tools in the field, 
- talk about how we can better share ideas on the Public Lab website,
- develop new research projects, 
- share out about environmental concerns and think about strategies to address them. 

The event is hosted in an “unconference style.” This means that people join to participate and collaborate rather than just present, talk, and listen. The event is takes place in a great location south of New Orleans, Louisiana and draws people from all over the US and the world! 

To learn more and register visit:  http://publiclab.org/barnraising
Comment below for questions or email me at: stevie@publiclab.org

@carolineh101, @nickstaggs, @sandyvern, @ap916, @cpdavngr, @david-days, @ujithaperera, @RodCardenas, @sjones88, @ykl7, @mzishtiaq, @ryzokuken, @neliojrr, @rafael-acerqueira, @ananyo2012, @ujithaperera, @lalithr95, @jiteshjha, @rmeister

**Comment by ananyo2012** [comment]
An issue for Invitation! :blush: This is really something innovative @steviepubliclab Thanks for the invitation Stevie. Hope I could attend but having my University exams around that time and some Visa issues! Hope to attend it some day in future! :blush:
