### ISSUE TITLE
Translation in the Comment Index Section

### ISSUE THREAD

**Issue by RuthNjeri** [publiclab/plots2#9093]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [Index.html.erb](https://github.com/publiclab/plots2/blob/b3009791076b15c9da81d58aec3de2a7a2b0f784/app/views/comments/index.html.erb) and the [en.yml](https://github.com/publiclab/plots2/blob/b3009791076b15c9da81d58aec3de2a7a2b0f784/config/locales/en.yml#L727-751)
 in the `Main` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:
https://github.com/publiclab/plots2/blob/b3009791076b15c9da81d58aec3de2a7a2b0f784/app/views/comments/index.html.erb#L3

```diff
- <span class="d-lg-inline">All comments</span>
+  <span class="d-lg-inline"><%= translation('comments.index.all_comments') %></span>
```

https://github.com/publiclab/plots2/blob/b3009791076b15c9da81d58aec3de2a7a2b0f784/app/views/comments/index.html.erb#L7

```diff
- <span class="d-lg-inline">Moderated Comments</span>
+<span class="d-lg-inline"><%= translation('comments.index.moderated_comments') %></span>
```

https://github.com/publiclab/plots2/blob/b3009791076b15c9da81d58aec3de2a7a2b0f784/config/locales/en.yml#L727-751
Add the following lines positioned at the same level as _edit: after line 751

```diff
    index:
      all_comments: "All Comments"
      moderated_comments: "Moderated Comments"
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by Antonio-Riccelli** [comment]
Hi there,
I'm looking to make my first contribution. If nobody else is working on this, could I have it assigned to me?

Many thanks

**Comment by RuthNjeri** [comment]
Hi @Antonio-Riccelli thanks for reaching out!
I'll assign it to you. Feel free to reach out if you face any problems

**Comment by harshdhonchak** [comment]
Can i also work on this , please !

**Comment by harshdhonchak** [comment]
There is some issue with my PR .Sir can you please help me

**Comment by Antonio-Riccelli** [comment]
Thank you, @RuthNjeri. I think I have done everything right and submitted the pull requests. 

Let me know if my submission is incorrect and there is something I should change.

**Comment by RuthNjeri** [comment]
Hi, @harshdhonchak thanks for reaching out. @Antonio-Riccelli already began working on the issue and has created a PR for it, you can check the issues to see if there is another First Timer Only issue to pick up. Once I create one I can also tag you to pick it up. Just make sure that you don't begin working on an issue if someone else has already begun working on it. 

You can always comment on any issue to confirm that you can pick it up. Maybe you could review the work @Antonio-Riccelli  has done and give feedback? Also, you might need to close the PR you have created since we'll have two PRs for the same issue. Thanks and I hope to see you working on another issue soon :)

**Comment by RuthNjeri** [comment]
Hi @Antonio-Riccelli, that's great! I'll have a look at it
