### ISSUE TITLE
Fix the `New page` alignment issue

### ISSUE THREAD

**Issue by Manasa2850** [publiclab/plots2#9105]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/dashboard/_wiki.html.erb](https://github.com/publiclab/plots2/blob/main/app/views/dashboard/_wiki.html.erb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
<div class="col-xl-4 col-lg-5 col-md-5 col-5">
-   <a href="/wiki/new" class="btn btn-primary btn-sm btn-outline-secondary btn-block" type="button" style="color:white" ><i class="fa fa-plus-circle" style="color:white" ></i> <%= translation('dashboard._wiki.new_page') %></a>
+   <a href="/wiki/new" class="btn btn-primary btn-sm btn-outline-secondary btn-block" type="button" style="color:white" ><i class="fa fa-plus-circle" style="color:white; margin-left:-3px" ></i> <%= translation('dashboard._wiki.new_page') %></a>
</div>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by Manasa2850** [comment]
Before:
![before](https://user-images.githubusercontent.com/43354059/106379092-a571a280-63cf-11eb-840f-83a4224c9893.png)

After:
![after](https://user-images.githubusercontent.com/43354059/106379099-ab678380-63cf-11eb-83a6-81024d0c3597.png)

**Comment by BenUnyolo** [comment]
Hi there. Please could I claim this as my first issue?

**Comment by Manasa2850** [comment]
Hi @BenUnyolo. Sure, please go ahead!

**Comment by shivam-2311** [comment]
hi is the issue is still open?

**Comment by shivam-2311** [comment]
i am not able to understand the issue can you please explain me again.

**Comment by ParseSnip** [comment]
Hi issue still open?

**Comment by larabee7777** [comment]
Hi @Manasa2850,  I'd like to claim this if it is still open thanks :)

**Comment by Manasa2850** [comment]
Hi! We already have a pull request for this. Would you like to take up some other issue?
Thanks!

**Comment by larabee7777** [comment]
Yes you can assign something, else I will just continue looking thanks so much :)

**Comment by Manasa2850** [comment]
@larabee7777 please feel free to comment and start working on any of the [help wanted](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues that someone else is not working on. Thanks!

**Comment by Manasa2850** [comment]
Closing this issue since it's not really a first timer issue (with reference to [this comment](https://github.com/publiclab/plots2/pull/9111#discussion_r568681524)). Sorry about that!
