### ISSUE TITLE
Filter out moderators who've checked "Do you want to be notified by a email for moderation emails?" in /settings

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#9114]
Looks like we missed a couple email notifications in  https://github.com/publiclab/plots2/issues/6282 -- easy fix though!

Any line which collects moderator emails in this file (and elsewhere) we should go through and filter out any one which has a tag opting out of moderator email notifications!

Those are the ones which have a tag like `notifications:noemail` or `no-moderation-emails` (confirmed this toggle works!)

That said, we have a setting in /settings for this:

https://github.com/publiclab/plots2/blob/876d0fc084064aaecc23f8003630d7d1ab858fa1/app/views/users/settings.html.erb#L50-L54

![image](https://user-images.githubusercontent.com/24359/106645025-d7167500-6559-11eb-8d1e-35a3f1447504.png)

So let's filter for at least `no-moderation-emails` and then maybe also  `notifications:noemail` when collecting emails on these lines:

https://github.com/publiclab/plots2/blob/97247e30289dfb27f93446b84d036ad9811e7983/app/mailers/admin_mailer.rb#L74

Here's a code example for how this works:

https://github.com/publiclab/plots2/pull/7183/files

```ruby
    all_moderators = User.where(role: %w(moderator admin))
    moderators = []
    all_moderators.each do |mod_user|
      moderators << mod_user.email unless mod_user.has_tag('no-moderation-emails')
    end
```

****

cc https://github.com/publiclab/plots2/issues/6867 https://github.com/publiclab/plots2/issues/6282

**Comment by 17sushmita** [comment]
Hi @jywarren , Can I work on this issue.

**Comment by cesswairimu** [comment]
Go ahead @17sushmita . Thanks
