### ISSUE TITLE
UI design work on note Edit button

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#913]
To make more space in mobile display, we moved the "Edit" button from research note headers into the "utilities" dropdown next to the `Follow` button on pages like this:

https://publiclab.org/notes/pdhixenbaugh/10-20-2016/blink-an-led-write-a-sketch-and-build-a-breadboard-circuit-for-the-riffle

Though you have to be an admin to edit someone else's post, or see the button, i've screenshotted it here:

![screen shot 2016-10-21 at 1 59 17 pm](https://cloud.githubusercontent.com/assets/24359/19607264/9e317be4-9796-11e6-94e4-412b923e0410.png)

Many authors can't find that button, so we should explore other UI options:
- marking that menu more clearly as a "tools" menu
- (preferred) finding a new, more compact space for the edit button or link
- potentially displaying the edit button prominently on desktop width screens, but more compactly on mobile devices

Happy to help brainstorm, and we can get some feedback from authors if you make a sketch or mockup!

**Comment by Pk13055** [comment]
@jywarren How about moving it inline with the 'follow' button? I would be willing to take this issue up if we reach a close on the position..

**Comment by jywarren** [comment]
I think that's reasonable, do you think you could try it and use chromes device simulator to check how it looks on narrower screens, and upload a screenshot of, say, an iPhone?

**Comment by Pk13055** [comment]
@jywarren Would there be any way to get a hold of the code for the admin tools? I can't view the 'edit','award star', etc options..

**Comment by jywarren** [comment]
yes -- they're in
https://github.com/publiclab/plots2/blob/master/app/views/like/_like.html.erb
-- which should perhaps be renamed, something like `tools`? But that
doesn't have to be part of this issue.

**Comment by Pk13055** [comment]
@jywarren Sorry to keep asking you, I'm pretty new to this; what about the main note-page? Where could I find it's .erb?  (PS - I think it'd work if I just moved the block into the btn-group, while checking `<% if current_user && (current_user.uid == node.uid || current_user.role == "moderator" || current_user.role == "admin") %>` )

**Comment by jywarren** [comment]
The main note page is at:

https://github.com/publiclab/plots2/blob/master/app/views/notes/show.html.erb

No problem! It's a big code base and we're happy to have your contribution. 

If you can keep your code broken up onto multiple lines that'd be great for readability. 

Thanks, and please open a pull request when you're ready so we can take a look!

**Comment by jywarren** [comment]
https://publiclab.org/wiki/contributing-to-public-lab-software#A+sample+git+workflow

**Comment by Pk13055** [comment]
#1076 - Please review and tell me if something needs to be changed.

**Comment by jywarren** [comment]
Solved there! Thanks!!! 🎈
