### ISSUE TITLE
Video media not playing on the site: Continuing issues with Bucket Monitor Toxic Tours page

### ISSUE THREAD

**Issue by kgradow1** [publiclab/plots2#9164]
https://publiclab.org/notes/A_SCH/11-08-2020/draft?_=1604861928#

Hi all, Annie Schillo posted this bug awhile ago and I am checking up on it.

This page is supposed to host four separate “toxic tour videos,” but they are not appearing. When we try to create a new page, we are unable to post or link videos. Can you let me know the status of this fix? It’s been down for probably a month or so and we are eager to start doing promotion of this page. Thank you in advance.

Katie

### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by kgradow1** [comment]
I am @kgradow1 and she is @A_SCH
\

**Comment by kgradow1** [comment]
I am @kgradow1 and she is @A_SCH
\

**Comment by kgradow1** [comment]
I am @kgradow1 and she is @A_SCH
\

**Comment by kgradow1** [comment]
I am @kgradow1 and she is @A_SCH
\

**Comment by cesswairimu** [comment]
Hi @kgradow1  and thanks for opening this..we will look into it. Thanks

**Comment by jywarren** [comment]
Hi, it looks like there is only one video there, can you share links to the other videos you'd like to put there and we can try to help get them embedded? 

Thanks!

**Comment by kgradow1** [comment]
Hi Jeff, please see attached.

https://www.youtube.com/watch?v=5LAJ3_Zvsg4

https://www.youtube.com/watch?v=FxYbXTV5MT4

https://www.youtube.com/watch?v=5z4MXCkV6S0

https://www.youtube.com/watch?v=ICrQHCq89pk

Thank you for looking into this!

**Comment by 17sushmita** [comment]
Hi @kgradow1 , I think there is an issue with the embedding code you're pasting. I tried to copy the code of the video you provided and it is working fine and I saw from the browser debugger that your embedding code of video is this -
```
<iframe width="480" height="252" src="https://www.youtube.com/embed/5LAJ3\_Zvsg4" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen\=""></iframe>
```
and what I copied from youtube was this 
```
<iframe width="480" height="252" src="https://www.youtube.com/embed/5LAJ3_Zvsg4" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
allowfullscreen></iframe>
```
Ignoring the `\=""` after allowfullscreen, you can see the difference in the url you copied, just check `src` attribute which in your case is "https://www.youtube.com/embed/5LAJ3\_Zvsg4" and what I got is "https://www.youtube.com/embed/5LAJ3_Zvsg4", see there is no `\` after 5LAJ3 , so basically the code you pasted is a wrong URL of the video and that's why the video is not playing.

This is what I drafted-
![image](https://user-images.githubusercontent.com/42088159/111816599-07945180-8903-11eb-8b62-90ecbaaa9fba.png)

And here is the preview of it-
![image](https://user-images.githubusercontent.com/42088159/111816706-2692e380-8903-11eb-96b1-e202044c5503.png)

**Comment by waridrox** [comment]
Yeah another workaround if using markdown syntax is to embed the youtube link using this syntax 

`[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/YOUTUBE_VIDEO_ID_HERE/0.jpg)](https://www.youtube.com/watch?v=YOUTUBE_VIDEO_ID_HERE)
`

**Comment by waridrox** [comment]
But I think @17sushmita's solution is better :D

**Comment by kgradow1** [comment]
Hi all, the issue we are having is that after we embed the code, the
editing functions of the page disappear and we are locked out of future
edits.

Here is the page prior to embedding the videos (no video, just text):

[image: image.png]

And here is the page afterwards  (it looks like this is also true in the
example above)

[image: image.png]

This is the code I attempted to embed:

<iframe width="560" height="315" src="
https://www.youtube.com/embed/ICrQHCq89pk" title="YouTube video player"
frameborder="0" allow="accelerometer; autoplay; clipboard-write;
encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by kgradow1** [comment]
In the second example, the video is posted, but the editing functions are
now gone.

I can back out of this page back to the editing window (prior to the video)
but if I post the video and then migrate away from the page, I am now
locked out.

This was the problem we were initially having.

**Comment by kgradow1** [comment]
Additionally, when I try to embed all four videos in sequence, I lose the
editing functions and get the following error:
[image: image.png]
An error occurred. Please try again later. (Playback ID: 59e_zbvWgVkg7S32)

This is the full text of the page, including the code I tried to embed:


<iframe width="560" height="315" src="
https://www.youtube.com/embed/5LAJ3_Zvsg4" title="YouTube video player"
frameborder="0" allow="accelerometer; autoplay; clipboard-write;
encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="
https://www.youtube.com/embed/FxYbXTV5MT4" title="YouTube video player"
frameborder="0" allow="accelerometer; autoplay; clipboard-write;
encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by kgradow1** [comment]
Sorry, sent too soon!

This is the full text of the page, including the code we are trying to
embed:

When it comes to environmental campaigns, the more communities are informed
about what they are being exposed to, the better they are able to then
advocate for reform. As a result, it’s important to learn both how to
identify what you are smelling, as well as what the potential health
effects are. In the following links Public Lab has complied a list of
resources from SDCEA’s Toxic City Booklet that quickly lays out the odors
associated with common refinery chemicals
<https://publiclab.org/notes/kgradow1/10-31-2020/smells-that-kill-how-to-identify-odours>
as
well as a comprehensive list of the chemicals and health effects of each
polluting industry.
<https://publiclab.org/notes/kgradow1/11-06-2020/toxic-city-health-impacts-of-chemicals-emitted-in-the-south-durban-area>

Additionally, when looking at this issue of the serious health impacts
resulting from emitted chemicals, it’s important to keep in mind the
communities surrounding the polluters that are disproportionally effected.
To learn more go on a “Toxic Tour” of South Durban to hear about the major
polluters of South Durban, South Africa and the communities affected.

<iframe width="560" height="315" src="
https://www.youtube.com/embed/5LAJ3_Zvsg4" title="YouTube video player"
frameborder="0" allow="accelerometer; autoplay; clipboard-write;
encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="
https://www.youtube.com/embed/FxYbXTV5MT4" title="YouTube video player"
frameborder="0" allow="accelerometer; autoplay; clipboard-write;
encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="
https://www.youtube.com/embed/5z4MXCkV6S0" title="YouTube video player"
frameborder="0" allow="accelerometer; autoplay; clipboard-write;
encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="
https://www.youtube.com/embed/ICrQHCq89pk" title="YouTube video player"
frameborder="0" allow="accelerometer; autoplay; clipboard-write;
encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by kgradow1** [comment]
The text posts without a problem.

But when we try to embed the four videos, we get an error message on the
videos and are additionally locked out of the editing features.

If it's possible to just create a new page, that might be the best
solution.  Annie tried to do this, though, and ran into the same problem.

**Comment by jcads** [comment]
@kgradow1 I tried embedding the videos you linked in the text above and it's working fine for me.

_draft:_
![image](https://user-images.githubusercontent.com/50954098/111964819-fc723900-8b2f-11eb-81ae-547416e42534.png)

_preview_
![image](https://user-images.githubusercontent.com/50954098/111964955-24619c80-8b30-11eb-8310-914747532a7d.png)

> The text posts without a problem.
>
> But when we try to embed the four videos, we get an error message on the
videos and are additionally locked out of the editing features.


I wonder what caused this issue for you. May I know what browser are you using?

**Comment by kgradow1** [comment]
I'm using Chrome.

It's still broken for me, unfortunately.

It looks like it's posted as a draft, maybe that has something to do with
it?

[image: image.png]

[image: image.png]

**Comment by jywarren** [comment]
Hi @kgradow1 I was able to get the videos to load by going to https://publiclab.org/notes/edit/24955 (i'm an admin) and pasting in (from your email above):

```

<iframe width="560" height="315" src="
https://www.youtube.com/embed/5LAJ3_Zvsg4" title="YouTube video player"
frameborder="0" allow="accelerometer; autoplay; clipboard-write;
encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="
https://www.youtube.com/embed/FxYbXTV5MT4" title="YouTube video player"
frameborder="0" allow="accelerometer; autoplay; clipboard-write;
encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="
https://www.youtube.com/embed/5z4MXCkV6S0" title="YouTube video player"
frameborder="0" allow="accelerometer; autoplay; clipboard-write;
encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="
https://www.youtube.com/embed/ICrQHCq89pk" title="YouTube video player"
frameborder="0" allow="accelerometer; autoplay; clipboard-write;
encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

I did it in "markdown" mode, not "rich text" and i wonder if that made it work where it hadn't for you? I think @17sushmita's note that `allowfullscreen` became `allowfullscreen\=""` seems very likely to be our rich text editor code trying to "fix" that parameter but in fact breaking it. 

In any case, I'll make a new issue in our Editor project with that thought. Thanks!!!

**Comment by ebarry** [comment]
Thanks for finding this bug everyone. So sorry for the work this required to report this from your side Katie -- really appreciate it and owe you one surely!
