### ISSUE TITLE
Trending Issues Not Loaded 

### ISSUE THREAD

**Issue by RuthNjeri** [publiclab/plots2#9168]
This is part of #8513

In some cases, there are not trending tags being loaded...
See point 3 in https://github.com/publiclab/plots2/issues/8513#issuecomment-776072401

**Comment by RuthNjeri** [comment]
Hi @jywarren, About the trending topics not showing up for you, I tested this on the stable site and initially, nothing showed up for me as well..
![Screenshot 2021-02-16 at 23 46 00](https://user-images.githubusercontent.com/7622875/108375984-8a968f00-7213-11eb-9111-c9c2c9e3c51c.png)

Then I noticed, the trending code, only shows topics that have a post within the past month. So I created a post and the next day(Because trending tags are cached and expire after 24hrs) the trending tag appeared.

![Screenshot 2021-02-18 at 17 59 37](https://user-images.githubusercontent.com/7622875/108376133-b3b71f80-7213-11eb-8987-de9270e8547e.png)


Let me know what you think....

**Comment by jywarren** [comment]
OK, i think we can say this is just OK. Thank you!!!
