### ISSUE TITLE
Aria Hidden Attribute For Blog Images

### ISSUE THREAD

**Issue by RuthNjeri** [publiclab/plots2#9170]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [_blog.html.erb](https://github.com/publiclab/plots2/blob/1bee8cc71238a8e88b45360d9313e9b800c3db0a/app/views/dashboard_v2/_blog.html.erb) in the `Plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!
https://github.com/publiclab/plots2/blob/1bee8cc71238a8e88b45360d9313e9b800c3db0a/app/views/dashboard_v2/_blog.html.erb#L5-L7
Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
- <div class="img" style="background-image: url('<%= @blog.main_image.path(:large) %>')">
+ <div aria-hidden="true" class="img" style="background-image: url('<%= @blog.main_image.path(:large) %>')">
<% elsif @blog.scraped_image %>
- <div class="img" style="background-image: url('<%= @blog.scraped_image %>')">
+ <div aria-hidden="true" class="img" style="background-image: url('<%= @blog.scraped_image %>')">
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by Yuta-KTD** [comment]
Hi!
Is anyone else working on this one?
If not, I'd like to.

**Comment by Yuta-KTD** [comment]
Also, I'd like to report an unrelated matter.
The 
>  [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) 

link in the issue body is broken.

Is [this](https://app.egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github) the correct link?

**Comment by RuthNjeri** [comment]
Hi @Yuta-KTD, thanks for reaching out, I've assigned the issue to you...

**Comment by RuthNjeri** [comment]
> Also, I'd like to report an unrelated matter.
> The
> 
> > [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github)
> 
> link in the issue body is broken.
> 
> Is [this](https://app.egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github) the correct link?

Yes the link is broken, but you can have a look at the contribution guidelines on our [README](https://github.com/publiclab/plots2/blob/main/README.md#developers)

**Comment by Yuta-KTD** [comment]
Hi!
I've completed my task! Please confirm.

**Comment by Yuta-KTD** [comment]
> > Also, I'd like to report an unrelated matter.
> > The
> > > [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github)
> > 
> > 
> > link in the issue body is broken.
> > Is [this](https://app.egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github) the correct link?
> 
> Yes the link is broken, but you can have a look at the contribution guidelines on our [README](https://github.com/publiclab/plots2/blob/main/README.md#developers)

Thanks for letting me know.
I checked those guidelines.

**Comment by harshdhonchak** [comment]
Is anyone working on this @RuthNjeri . if not I would like to work on this .

**Comment by RuthNjeri** [comment]
Hi @harshdhonchak, yes, @Yuta-KTD has already raised a PR on it.
