### ISSUE TITLE
Tab Index For Pinned Blog

### ISSUE THREAD

**Issue by RuthNjeri** [publiclab/plots2#9172]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [_blog.html.erb](https://github.com/publiclab/plots2/blob/1bee8cc71238a8e88b45360d9313e9b800c3db0a/app/views/dashboard_v2/_blog.html.erb) in the `Plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!
https://github.com/publiclab/plots2/blob/1bee8cc71238a8e88b45360d9313e9b800c3db0a/app/views/dashboard_v2/_blog.html.erb#L20
Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
- <h4 class="blog-caption">
+ <h4 class="blog-caption" tabindex="1">
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by manchere** [comment]
Hi, I would like to work on this issue.

**Comment by RuthNjeri** [comment]
Hi @manchere, thanks for reaching out, I have assigned it to you.

**Comment by manchere** [comment]
Thank you!

**Comment by shadowoflight** [comment]
Is the issue active , if @manchere is not working on it, can I go ahead and complete this issue @RuthNjeri

**Comment by manchere** [comment]
yes, working on it

**Comment by manchere** [comment]
@RuthNjeri I am facing some issues setting up my environment, so I have unassigned to allow others to work on the issue.

**Comment by shadowoflight** [comment]
Made a pr, requesting review @RuthNjeri

**Comment by nphan03** [comment]
Hi all,
Is this still available for contribution? If so, please let me know
Thanks

**Comment by shadowoflight** [comment]
@nphan03 I have already raised a pr for the same, you might like to work on other issues open, thanks.

**Comment by jywarren** [comment]
Hi @manchere did you need some help with your local setup? You can check out #3840, and folks in the chatroom are often happy to help out too! https://gitter.im/publiclab/publiclab
