### ISSUE TITLE
Get parent tags to display child tag content in graphs

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#918]
We've just created a [tag aliasing system](https://publiclab.org/wiki/power-tags#Tag+aliasing) in #871, so that content tagged with `spectrometer`, which has a tag.parent of `spectrometry`, appears on the `spectrometry` (parent) tag page:

https://publiclab.org/tag/spectrometry

However, the graph shown on that page does not show `spectrometer`-tagged content, just the listing below does. Let's fix it in the graph, so the graph should include all data shown on the graph shown at https://publiclab.org/tag/spectrometer.

I believe the graph draws on data from these two methods: https://github.com/publiclab/plots2/blob/master/app/models/drupal_tag.rb#L143-L169

Yes - the call to `tag.weekly_tallies` is here: https://github.com/publiclab/plots2/blob/master/app/views/tag/show.html.erb#L20

**Comment by manish310794** [comment]
@jywarren What if the hierarchy goes like this `spectometry` <- `spectometer` <- `sub-category`? Will the `spectrometer` tag page show content with tags `spectometer` and `sub-category` as well?

**Comment by jywarren** [comment]
Hi! No, I think only one level... To do more could lead us to circular and
infinite queries, right?

Thanks!

**Comment by manish310794** [comment]
Yes, you are right. It might lead to circular queries since it not a strict category-sub-category system.

**Comment by jywarren** [comment]
Hi, were you interested in taking this issue on? I'd be happy to offer some more input if so.

**Comment by manish310794** [comment]
@jywarren Yes I am interested to take this up.

**Comment by jywarren** [comment]
Super! Tell me if you need anything and thanks!

**Comment by jywarren** [comment]
Reworking this into a plan to do some auto-tagging! #6367
--
