### ISSUE TITLE
UI redesign of tag list page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#920]
https://publiclab.org/tag/riffle doesn't highlight the central https://publiclab.org/wiki/riffle page -- 

@pdhixenbaugh @ebarry

Also suggestion of "pinning" content to the top of the tag page.

**Comment by Pk13055** [comment]
@jywarren I would like to contribute; can you give me some headers (what changes in particular, etc)?

**Comment by jywarren** [comment]
I believe this has improved as of #973, but I'd like to see the graph labelled, and more space added above it (it currently overlaps the "read more" text in some screensizes).

I also wonder if "Research Notes" could be made into "Recent updates" and a new tab could be added for Activities, listing an [activity grid](https://publiclab.org/notes/liz/08-30-2016/check-out-these-activity-grids) automatically using the helper in `app/helpers/application_helper.rb`. 

But any other user interface design suggestions are welcome! These that I've mentioned may need to be broken out into their own issues. And we're looking at how this page could become a kind of "pulse" page for the topic area, giving an overview of activity/community kind of like [how GitHub Pulse does](https://github.com/publiclab/plots2/pulse/monthly) for this repository.

If you're interested in the UI design work, I generally think we could ditch the left sidebar and try to do a cleaner overall layout with the main column content. What do you think? Do you like doing sketches as part of a design process?

**Comment by jywarren** [comment]
Thanks, by the way!!!

**Comment by Pk13055** [comment]
@jywarren I took a look at the page on some mobile devices; the graph seems to render fine even on an iPhone 4 in portrait mode, however, the scaling isn't right in landscape, the y-axis key overlaps the graph data.
Also, by left sidebar, do you mean the extra margin-spacing that's been kept empty? I think pushing all the content to the left and making it more block-type would look cleaner. 

Could you also elaborate more on what you mean by this page becoming a Pulse-esque one? Do you mean that there should be a display of sorts showing the recent comments, new posts, tags, etc?

![screenshot from 2016-12-08 13 36 42](https://cloud.githubusercontent.com/assets/13479308/21004811/af04c806-bd4b-11e6-9223-6c220df505e5.png)
![screenshot from 2016-12-08 13 36 17](https://cloud.githubusercontent.com/assets/13479308/21004812/af0540ec-bd4b-11e6-9430-6570866f9f5f.png)

**Comment by jywarren** [comment]
Yes, see how in the screenshots, "Read more" is kind of pushed up against the graph, and is not as visible? I think it just needs some more margin below it.

> Also, by left sidebar, do you mean the extra margin-spacing that's been kept empty? I think pushing all the content to the left and making it more block-type would look cleaner.

There's a `col-md-3` -width zone, which in wide screens occupies the left 25% of the screen, using https://getbootstrap.com layout styles. If we got rid of it, we'd want to think about whether there's any content that's shown there (i think it's mostly been moved into tabs) that we want to preserve elsewhere on the page. 

> Could you also elaborate more on what you mean by this page becoming a Pulse-esque one? Do you mean that there should be a display of sorts showing the recent comments, new posts, tags, etc?

Yes, just generally thinking about various ways to represent activity for this topic area in creative and informative ways, without overwhelming the layout with too much content all at once.

**Comment by jywarren** [comment]
This is now complete due to the featuring of wiki content at the top of tag pages!
