### ISSUE TITLE
Call for Summer of Code(soc) mentors 2021!!

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#9219]
Hi everyone :wave: 
We are applying to  [GSoC](https://summerofcode.withgoogle.com) and [Outreachy](https://www.outreachy.org/) and we are looking for folks interested in mentoring both of these programs this coming summer. We have participated in both during the past few years.

Read some of last year's proposals for Outreachy  [here](https://publiclab.org/notes/liz/03-09-2020/call-for-outreachy-2020-proposals)  and GSoC  [here](https://publiclab.org/notes/cess/03-02-2020/call-for-2020-soc-proposals-gsoc-and-outreachy)

**We especially welcome people from groups underrepresented in free and open source software!**

It's very important to us to have diverse representation in our mentor group just as in our participant group. And remember -- our community aspires to be a respectful place. Please read and abide by our [Code of Conduct](https://publiclab.org/conduct) 
We are calling for individuals who would like to be mentors for this round. 

**[Here](https://github.com/publiclab/plots2/issues/9257) is the idea list of potential projects for the summer round**

We will update the confirmed projects for each program here once we have that information.

### To participate:

This year, we're asking for mentors that have taken some of the following steps to be part of our community:

1. Solve a [first-timers issue](https://code.publiclab.org#r=all). Provide the link to the first timer issue's pull request (PR) once it's merged. In case, you are not able to find any first-timer issue, solve issue marked as `fto-candidate` or `support`, these issues may require little more work, but we'll try to help.
2. Solve a [help-wanted issue](https://github.com/publiclab/plots2/labels/help-wanted). Help wanted issues are issues which are not labelled as `gci-candidate` neither as `fto-candidate` nor as `first-timer-only`. Provide link to such issues' merged PR.
**(Make sure you claim the issue first by commenting on issue you are planning to solve)**
3. make a **first-timers issue**. [Use the extra friendly template](https://publiclab.org/n/13667) which we generally use for creating our first timer issues. Provide the link to the first timer issue which is created by you.

Mentors check in with a student at least once per week roughly from May-August, and offer some project management guidance and encouragement... while relying on the [chatroom](https://publiclab.org/chat) and the @publiclab/reviewers group to provide code-specific input, so that we share the burden of specific technical support. We have weekly Check-Ins on GitHub (https://github.com/publiclab/plots2/issues/5627) as well, and mentors are expected (along with students!) to be in the rotation to post these occasionally.

Remember that to be a mentor you don't necessarily need to know how to code -- we also need mentors who know Public Lab's community and practices well, and who can encourage students to speak up when they get stuck, and to ask the community for input and testing of their work. Students often get stuck when they don't know how something should look, or how a feature might be used by the community -- contextual info!

****

If you're interested in being a mentor, leave a comment here, fill in [this form](https://docs.google.com/forms/d/e/1FAIpQLSempLUqWxIUDlaTM4V9dHtCPwU6AbHOBLuJpPYwCzqJunkiYg/viewform) and read over our [software outreach resources](https://publiclab.org/software-outreach) to get an idea of how we work!

#### Some key resources on mentoring:

- read over our [Summer of Code workflow here](https://publiclab.org/wiki/gsoc#How+we+work)
- read these [extra notes on our approach here](https://opensource.googleblog.com/2016/12/google-summer-of-code-2016-wrap-up_21.html)
- read [different ways to mentor in this post](https://publiclab.org/notes/warren/11-08-2016/help-public-lab-s-software-grow-by-joining-a-supportive-team) -- we need various types!
- read about [what reviewers do day-to-day on Public Lab code projects](https://publiclab.org/wiki/developers#Reviewers)
- read about [our commitment to modularity](https://publiclab.org/notes/warren/01-18-2018/software-outreach-modularity-is-great-for-collaboration), very important in how we ask contributors to work
- check out our growing list of [software outreach strategies](https://publiclab.org/software-outreach)

Thanks a lot, and we're happy to answer questions, please leave a comment below if any!

**Comment by jywarren** [comment]
Sending appreciation and gratitude to past mentors @CoderJolly @subhahu123 @ananyaarun @starkblaze01 @govindgoel @sidntrivedi012 @debck @SidharthBansal @sagarpreet-chadha @pydevsg @blurry-x-face @Divy123 @emilyashley @sidntrivedi012 @subhahu123! 

And we are happy to answer questions about what mentoring is like. Thanks for posting, @cesswairimu !!

**Comment by jywarren** [comment]
cc @publiclab/is-maintainers @publiclab/comment-maintainers @publiclab/is-ui-maintainers @publiclab/is-cli-maintainers

**Comment by RuthNjeri** [comment]
This is amazing!! I would love to transition into mentoring the next round of applicants! I have learnt a lot through the mentorship provided and would like to do the same for others.

**Comment by noi5e** [comment]
Second that, would be interested in becoming a mentor as well!

**Comment by CoderJolly** [comment]
> Sending appreciation and gratitude to past mentors @CoderJolly @subhahu123 @ananyaarun @starkblaze01 @govindgoel @sidntrivedi012 @debck @SidharthBansal @sagarpreet-chadha @pydevsg @blurry-x-face @Divy123 @emilyashley @sidntrivedi012 @subhahu123!
> 
> And we are happy to answer questions about what mentoring is like. Thanks for posting, @cesswairimu !!

This is amazing @jywarren & @cesswairimu. I appreciate your concern and I offer the same gratitude to @publiclab/mentors @publiclab/maintainers @publiclab/comment-maintainers @publiclab/is-maintainers @publiclab/is-ui-maintainers @publiclab/is-cli-maintainers as well !!

Cheers 🎊 👍🏻

**Comment by cesswairimu** [comment]
**Update:** All interested kindly fill in [this form](https://docs.google.com/forms/d/e/1FAIpQLSempLUqWxIUDlaTM4V9dHtCPwU6AbHOBLuJpPYwCzqJunkiYg/viewform) for better planning. Thanks

**Comment by jywarren** [comment]
Thank you all!!!! 🎉 🎉 🎉 🎉

**Comment by pydevsg** [comment]
Count me in with @SidharthBansal 😃 .
I am willing to mentor this year as well and help folks in their projects. 🎉

**Comment by divyabaid16** [comment]
I am interested in becoming a mentor this year.
Happy to help. Thank you 💯

**Comment by gautamig54** [comment]
Hello all! I am interested in mentoring this year. Would love to help and learn from everyone! 
Thank you 👍

**Comment by gautamig54** [comment]
Hello all! I am interested in mentoring this year. Would love to help and learn from everyone! 
Thank you 👍

**Comment by jywarren** [comment]
Hi @gautamig54 we'd love to have your help too, sorry for the slow reply -- did you fill out the form linked above? Thank you!
