### ISSUE TITLE
Weekly Community Check-In #93 - SoC Preparation

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#9229]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## SoC Preparation 

Outreachy just closed initial application yesterday, in a week or so time we expect to have applicants checking out our projects and  contributing..GSoC applicants should coming in about a week after the Outreachy applicants..in preparation to that, lets do a few things to ensure smooth process for these folks. If you are aspiring to apply to either of these programs, please say hi below :smiley: 

### How you can help

**1. Create an fto for soc applicants**
Create first-timer-only for these folks and add `soc` label to reserve it for soc fellows....lets also add a disclaimer at the  the top of the issue something like `Please note we are preparing to participate in Outreachy and GSoC, and have reserved this issue for soc participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.` 

**2. Break down issues**
soc applicants often move to help-wanted issues after solving ftos lets  try and break out issues such issues if massive, into smaller independent issue and add as much info as possible this may include link to code files, screenshots etc and label them with `soc` label for them to find.

**3. Be a reviewer**
In the next couple of weeks we expect to have a lot of contributions coming in... if you have contributed with us for a while, please consider joining our reviewing team to help in reviewing of PRs and giving feedback

**4. Volunteer to mentor**
Both Outreachy and GSoC require mentors from our community. Mentors check in with a student at least once per week roughly from May-August, and offer some project management guidance and encouragement.....please checkout more information on how you can mentor [here](https://github.com/publiclab/plots2/issues/9219) if you are interested.

:heart: Thanks everyone :heart: 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by RuthNjeri** [comment]
Thanks, @cesswairimu! I'll begin creating a few FTOs from Monday next week...

**Comment by cesswairimu** [comment]
Hi all, lets keep this for another week as we continue the preparations. Thanks

**Comment by jywarren** [comment]
Phew, thanks Cess -- we are almost ready to share our ideas page, hopefully will do so tomorrow!!! Thanks @RuthNjeri as well!!!

**Comment by jywarren** [comment]
OK, and i've posted the full Ideas list for Outreachy/GSoC 2021 at #9257 to make a space for in-depth discussion of these ideas -- please feel free to ask questions or offer ideas there! Thanks all!

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/9274. Thanks everyone
