### ISSUE TITLE
Calendar "datepicker" integration as tagging widget or wizard for notes

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#9232]
We have a calendar widget in the legacy post form at https://publiclab.org/post?legacy=true, which appears when you click `This is an event`:

![Screen Shot 2021-02-23 at 3 46 15 PM](https://user-images.githubusercontent.com/24359/108905935-4c6fe580-75ee-11eb-8258-da9de0b9c4ec.png)

We should be able to, instead of integrating this with the new Editor code, make it appear at the bottom of a post, above the comments, on a page like this: https://stable.publiclab.org/notes/kgradow1/07-01-2020/remembering-tonawanda#comments

![image](https://user-images.githubusercontent.com/24359/108908823-c3f34400-75f1-11eb-8565-ffdc934757fa.png)

### Detect whether to show the widget

It could detect if a page needs this by checking if the `@node.has_tag('event')`, perhaps, and if it's the author viewing, or a moderator or admin... 

### Display the widget

...it could have a message like `This looks like an event. ` and a button like `Add a date`

Clicking the button would show a date input selector like in this partial:

https://github.com/publiclab/plots2/blob/03e9b2717153cbfe8d42c4ee795d2919ef0aa237/app/views/editor/_event.html.erb#L8-L14

I believe this can get the popup datepicker using `$('.datepicker').datepicker()`

Then another button `Save date` would use the `addTag(tagname)` javascript method to add a tag in the format `date:10-04-2019` -- like on this post: https://publiclab.org/notes/warren/09-30-2019/microbrews-meet-up-at-as220-food-providence

This is a really complex issue with many parts. I'd be happy to help someone go through it or I can take it on myself!

**Comment by imajit** [comment]
Can I work on this?

**Comment by RuthNjeri** [comment]
Hi @imajit thanks for reaching out. I have assigned it to you. Let us know if you have any questions.
