### ISSUE TITLE
Date error on post in moderation queue

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#9233]
### Problem Description

A comment that appears in the https://publiclab.org/spam2 queue an hour ago (shown in the screenshot as the top comment), when clicked, says it was posted `51 years ago`.

<img width="1000" alt="screen_shot_2021-02-23_at_4 05 31_pm" src="https://user-images.githubusercontent.com/161439/108912924-4b8f8180-75f7-11eb-9473-826f57754cb4.png">

I expected to see a more recent timestamp, similar to the "1 hour" that appeared in the list. 

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file https://github.com/publiclab/plots2/blob/main/app/views/spam2/_comments.html.erb  (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Replace this line https://github.com/publiclab/plots2/blob/main/app/views/spam2/_comments.html.erb#L141
with 
```
 <%= time_ago_in_words(comment.timestamp) %> ago
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by cesswairimu** [comment]
thanks for reporting this Liz, I will edit the description a bit and convert this to a fto.

**Comment by cesswairimu** [comment]
Reserved for @PavitKaur05
