### ISSUE TITLE
Intermittent failing tests on github actions

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#9247]
We have a few tests that fail on PRs but pass on retry...lets collect them here and try to solve them all.
Feel free to edit this and add a test you encounter behaving this way

```
=========================== FAIL SearchControllerTest#test_search_question_at_/search/questions/question (113.61s)
        Expected: 8
          Actual: 15
        test/functional/search_controller_test.rb:51:in `block in <class:SearchControllerTest>'

============================= FAIL CommentControllerTest#test_should_not_send_notification_email_to_another_commenter_if_notify-comment-indirect:false_usertag_is_present (104.91s)
        Expected false to be truthy.
        test/functional/comment_controller_test.rb:387:in `block in <class:CommentControllerTest>'

 FAIL CommentControllerTest#test_should_send_mail_to_moderator_if_comment_has_status_4 (105.23s)
        Expected false to be truthy.
        test/functional/comment_controller_test.rb:294:in `block in <class:CommentControllerTest>'

= FAIL CommentControllerTest#test_should_send_mail_to_multiple_tag_followers_in_the_comment (105.33s)
        Expected false to be truthy.
        test/functional/comment_controller_test.rb:315:in `block in <class:CommentControllerTest>'

 FAIL CommentControllerTest#test_should_send_mail_to_tag_followers_in_the_comment (105.43s)
        Expected false to be truthy.
        test/functional/comment_controller_test.rb:308:in `block in <class:CommentControllerTest>'

 FAIL CommentControllerTest#test_should_send_notification_email_upon_a_new_wiki_comment (105.52s)
        Expected false to be truthy.
        test/functional/comment_controller_test.rb:323:in `block in <class:CommentControllerTest>'

```

**Comment by jywarren** [comment]
Hmm, some might be https://github.com/publiclab/plots2/pull/8865 

actually a number of these are the same as we're seeing in https://github.com/publiclab/plots2/pull/9314 -- let me check in with that person too...

**Comment by jywarren** [comment]
I think these related to email notifications may have begun with https://github.com/publiclab/plots2/pull/9269, but odd that they're intermittent...

**Comment by jywarren** [comment]
Hmm. No fixtures have these user tags so the logic doesn't seem wrong:

https://github.com/publiclab/plots2/blob/main/test/fixtures/user_tags.yml

https://github.com/publiclab/plots2/blob/c9349cae8af3e8ed2e27c77d9e35173a6cfa9194/app/mailers/admin_mailer.rb#L150

**Comment by jywarren** [comment]
I tried refining those tests to confirm an email is generated at all:

```ruby
assert_difference 'ActionMailer::Base.deliveries.size', 0 do
  ...
end
```

However i think we may need to wrap them in enqueue statements too, if the emails are getting sent later.

**Comment by jywarren** [comment]
Noting that i don't know if the `perform_enqueued_jobs` part makes sense, since we have not yet converted most email sending code to `deliver_later` - that's in this PR:

https://github.com/publiclab/plots2/pull/9314

**Comment by jywarren** [comment]
This section seems like it could relate to `nids`: 

```
=========================== FAIL SearchControllerTest#test_search_question_at_/search/questions/question (113.61s)
        Expected: 8
          Actual: 15
        test/functional/search_controller_test.rb:51:in `block in <class:SearchControllerTest>'
```

#8865

**Comment by jywarren** [comment]
attempted to adjust sort order there... `test "search question at /search/questions/question" do`

**Comment by jywarren** [comment]
I think i got it, fingers X!!!

**Comment by cesswairimu** [comment]
Thanks Jeff! :tada:
