### ISSUE TITLE
Questions: show.html.erb Translations

### ISSUE THREAD

**Issue by RuthNjeri** [publiclab/plots2#9254]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the files below

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

https://github.com/publiclab/plots2/blob/452a75bbbd1bf9cf8f0ab545a8f6a4eee3ec01a8/app/views/questions/show.html.erb#L25
Make this change
```diff
-<h1 style="margin-top: 20px;"><span class="question">Question: </span><a href="<%= @node.path(:question) %>"><%= @node.title %></a></h1>
+<h1 style="margin-top: 20px;"><span class="question"><%=translation('questions.show.question')%>:</span><a href="<%= @node.path(:question) %>"><%= @node.title %></a></h1>
```
https://github.com/publiclab/plots2/blob/452a75bbbd1bf9cf8f0ab545a8f6a4eee3ec01a8/app/views/questions/show.html.erb#L28-L29
Make this change
```diff
-<a href="/profile/<%= @node.author.name %>"> <%= @node.author.name %> </a> is asking a question about <b><a href="/questions/tag/<%= pt %>"><%= pt %></a></b>:
+<a href="/profile/<%= @node.author.name %>"> <%= @node.author.name %> </a<%=translation('questions.show.question_about')%> <b><a href="/questions/tag/<%= pt %>"><%= pt %></a></b>:
```

https://github.com/publiclab/plots2/blob/452a75bbbd1bf9cf8f0ab545a8f6a4eee3ec01a8/app/views/questions/show.html.erb#L36-L42
Make this change
```diff
-<% if @node.status == 0 || @node.status == 4 %><span class="badge badge-danger">UNPUBLISHED</span> | <% end %>
-<% if @node.status == 3 %><span class="badge badge-success">Draft</span> | <% end %>by <a href="/profile/<%= @node.author.name %>"><%= @node.author.name %></a> |
-<% if @node.has_power_tag('with') %>with <% @node.coauthors.each_with_index do |coauthor,i| %>
-<a href="/profile/<%= coauthor.username %>"><%= coauthor.username%></a> <%= coauthor.new_contributor %><%= ',' if i < @node.coauthors.size-1 %><% end %><% end %>

+<% if @node.status == 0 || @node.status == 4 %><span class="badge badge-danger"><%=translation('questions.show.unpublished')%></span> | <% end %>
+<% if @node.status == 3 %><span class="badge badge-success"><%=translation('questions.show.draft')%></span> | <% end %><%=translation('questions.show.by')%> <a href="/profile/<%= @node.author.name %>"><%= @node.author.name %></a> |
+<% if @node.has_power_tag('with') %><%=translation('questions.show.with')%> <% @node.coauthors.each_with_index do |coauthor,i| %>
+<a href="/profile/<%= coauthor.username %>"><%= coauthor.username%></a> <%= coauthor.new_contributor %><%= ',' if i < @node.coauthors.size-1 %><% end %><% end %>
```
In the translations file en.yml, make these changes
https://github.com/publiclab/plots2/blob/452a75bbbd1bf9cf8f0ab545a8f6a4eee3ec01a8/config/locales/en.yml#L664

Inside the `questions:` block, beneath the last indented section, add:
```diff
  show:
     question: "Question"
     question_about:  "is asking a question about"
     unpublished: "UNPUBLISHED"
     by: "by"
     draft: "Draft"
     with: "with"
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by eynglv** [comment]
Hi, Can I take this? This would be my first contribution!

**Comment by cesswairimu** [comment]
Hi @eynglv and thanks for your interest,  are you an Outreachy applicant? this is specifically reserved for Outreachy applicants ...if not, kindly browse through other issues and feel free to ping me if you still can't find anything  and I will help you find one. Thanks

**Comment by Prahitha** [comment]
Hi, I am an Outreachy applicant and am looking for some first-timers-only issues to start with. I'd like to take this if it's not assigned yet. Thanks.

**Comment by cesswairimu** [comment]
Hi @Prahitha, please go ahead. thanks

**Comment by eynglv** [comment]
Hi, @cesswairimu  I actually am also an Outreachy applicant! Are there other first-timers-only issues I could work on?

**Comment by cesswairimu** [comment]
Hi @eynglv, I have reserved one for you here https://github.com/publiclab/plots2/issues/9264 . thanks

**Comment by Anupam-USP** [comment]
Hey @eynglv, I am new to open source and searched about "outreachy" but not able to find its meaning. May I know what it is?

**Comment by cesswairimu** [comment]
Hi @Anupam-USP, Outreachy is remote paid internship for people underrepresented in tech...you can find more details here https://www.outreachy.org/ thanks
