### ISSUE TITLE
Footer overlaps tag note & three dot menu

### ISSUE THREAD

**Issue by manchere** [publiclab/plots2#9271]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
When accessing a tag, the footer overlaps the three dots menu when it is open. 
This hides some of the options on the three dots menu behind the footer.
<img width="1283" alt="Screenshot 2021-03-05 at 2 30 40 PM" src="https://user-images.githubusercontent.com/11008910/110131350-f6572b00-7dc1-11eb-886c-767189ce6d9e.png">

> What did you expect to see that you didn't?
I expected the three dots menu to appear in front of the footer, a margin below the tag could also separate the footer from covering the three dots menu when it is open.

### Please show us where to look

https://publiclab.org/questions/tag/lat:5

### What's your PublicLab.org username?

>manchere

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!
Google chrome Version 88.0.4324 & Safari Version 14.0.2

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by manchere** [comment]
@pydevsg all right thanks, can you assign me to this issue, please?

**Comment by gaurav2699** [comment]
Hello, since there are no pull requests linked with the issue, I would like to work on this issue or help out @manchere  if he is stuck somewhere

**Comment by ebarry** [comment]
Thank you for reporting and working on this! I am also reporting this issue on the three-dot-menu for Tag Pages: 
<img width="663" alt="Screen Shot 2021-05-13 at 2 52 17 PM" src="https://user-images.githubusercontent.com/161439/120387033-66a91600-c2f7-11eb-9519-adc533e160b2.png">

Additionally, i believe i have seen similar behavior on publiclab.org/maps, in the layer palette.

**Comment by KarishmaVanwari** [comment]
Is this issue still open? @manchere @pydevsg @ebarry

**Comment by TildaDares** [comment]
Resolved in #10247
