### ISSUE TITLE
Weekly Community Check-In #94 - Congratulations winter 2020 Outreachy interns

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#9274]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Congratulations winter 2020 Outreachy interns :tada: :tada: 
Congratulations to @noi5e and @RuthNjeri on successfully completing their internship :rocket: :rocket:  The winter program wrapped up  a week ago. This week lets share some good interactions we have had with the Outreachy interns and mention some of their work you have loved and appreciate them. The two are preparing a presentation of their work on an open call next week on Tuesday and all are invited

**date:** 16th March 2021
**time:** https://bit.ly/3kTir8L
**meeting link**: https://us02web.zoom.us/j/86297425690?pwd=ZFAyUnd2UjQ5dkp6ekM1QzYxcjdrdz09

## Volunteer to mentor
We are still looking for mentors from our community for both Outreachy and GSoC . Mentors check in with a student at least once per week roughly from May-August, and offer some project management guidance and encouragement..... more information on how you could mentor is [here](https://github.com/publiclab/plots2/issues/9219) . Thanks in advance :heart: 

### Thank you note to focus issues contributors

🥇🥇Thanks so much @Manasa2850 @RuthNjeri   for opening ftos in the past week🥇🥇

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by pydevsg** [comment]
Awesome 👏 
Congratulations @RuthNjeri and @noi5e 🎉 🚀

**Comment by Manasa2850** [comment]
Congrats @RuthNjeri and @noi5e! :tada: :partying_face:

**Comment by RuthNjeri** [comment]
Thanks, everyone!

**Comment by jywarren** [comment]
Congrats!!!! It's amazing to see everything up at https://publiclab.org/v2/dashboard/ and even more at https://stable.publiclab.org/v2/dashboard/. I'll republish the site now -- it'll take a couple hours -- and we'll see even more updates on the live site!!!

**Comment by SidharthBansal** [comment]
Congrats @RuthNjeri and @noi5e! 🎉 🥳

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/9318 , see you all on the open call later today
