### ISSUE TITLE
Replace/Rename Dashboard V2 References 

### ISSUE THREAD

**Issue by RuthNjeri** [publiclab/plots2#9278]
This is part of the transition tasks needed to replace the old dashboard with the new dashboard https://github.com/publiclab/plots2/issues/9277

After the old dashboard files have been removed, the new dashboard will be updated to the main dashboard by:

1. Renaming all routes from `v2/dashboard` to `dashboard`
2. Rename the folder `views/dashboard_v2` to `dashboard`
3. Rename the `dashboard_v2` action in the `home_controller` to dashboard
4. Rename all references to `dashboard_v2` or `v2/dashboard` in the tests folder files to `dashboard` and `dashboard`

**Comment by waridrox** [comment]
@RuthNjeri can I try as my first contribution to the org 😄 ?

**Comment by RuthNjeri** [comment]
Hi @waridrox thank you for reaching out...
This issue is still pending... but you can begin working on other issues listed in the issues section.

**Comment by waridrox** [comment]
Sure, thanks for the update!

**Comment by govindgoel** [comment]
@RuthNjeri I can start working on this.

**Comment by RuthNjeri** [comment]
Hi @govindgoel, this issue is blocked. Please have a look at today's weekly check-in to see what other issues you can pick https://github.com/publiclab/plots2/issues/9350
