### ISSUE TITLE
Welcome GSoC applicants and call for proposals 🎉🙋‍♀️🙋🙋‍♂️

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#9283]
Hello :wave: and welcome to PublicLab :balloon: 
--------

We are glad to have you here. This year, we  are participating in Google Summer of Code(GSoc) as an independent org. 
This is a discussion issue for all of you. If you would like to checkout our large community you can find us on gitter https://gitter.im/publiclab/publiclab and also we do weekly check-ins where folks say what they are working on and ask for help if blocked. You can find the link to the latest check-in here #5627 

### Projects
Idea list/ potential projects: https://publiclab.org/wiki/gsoc-ideas#2021+Ideas
Github discussion: https://github.com/publiclab/plots2/issues/9257 

Here are a few todos 

### Introduce yourself 
Please say hello in a comment below, so we get to know you(optional).

###  First contribution :man_technologist: :woman_technologist: 
We suggest you make a first contribution. We have issues with the first-timer-only label which are specifically tailored for a first time contributor. You can find them here https://code.publiclab.org/ along with the guidelines on how to start contributing. Please be sure to check if someone is already working on an issue before you take it up. Kindly leave a comment on the issue to let other people know you are working on an issue. If you can't find any issues that are available, please feel free to leave a comment below and we will find you one asap.
After you solve the first issue you can browse through our "help-wanted" issues. Feel free to tag @publiclab/mentors if you need more context for you to solve an issue.

### Call for GSoC proposals

We request applicants to post their proposals on the PublicLab website. 
Here are [2020 proposals](https://publiclab.org/notes/cess/03-02-2020/call-for-2020-soc-proposals-gsoc-and-outreachy) you could look at in the meantime to get an idea
_We shall link a call to this year's call for proposal here, in the few days_

 Kindly submit early and post a link on gitter so that contributors and mentors can give feedback and help you improve on your proposal.  

### Questions :thinking: 

 If you have any questions please leave a comment below and we will get back to you.

#### A few tips for making awesome proposals:
* Please [submit the proposals at publiclab.org]  first. After all the reviews you can submit it on the official website.
* Your information so that we can know you better (not mandatory !).
* Include weekly timeline: Explain what you will be doing in which week. Divide the period into months in bigger tasks. Then into weeks into smaller tasks.
* Include demos/images/gifs to demonstrate your idea
* Include Mock-Ups, Flow Charts, Data Flow Diagrams, etc to explain the workflow in simple language. So that people in the logistics department can review your work and suggest changes.
* PRs merged & Issues reported: This is the most crucial aspect of any application. We want people to be well versed with our system. Please mention all the issues reported, PR merged, suggestions etc in the proposal.
* Start early and have many revisions of the proposal to increase your chances.

These tips are general tips.
Are you tensed? overwhelmed?  No need to worry!!! : We all are there to help you at each stage of the way. Feel free to reach out in case of anything.

**Comment by dhanmoni** [comment]
Hi, myself Dhanmoni Nath, full-stack software developer student with 3+ years of development experience, I'm looking forward to contributing to publicLab and learn new stuff!

**Comment by dhanmoni** [comment]
I have a doubt, only the 6 project ideas that are listed under 2021 ideas will be available for GSoC 2021, right? Will the 2020 ideas available, especially the Editor repair and fortification project?

**Comment by YogeshSharma01** [comment]
Hi, @cesswairimu and @jywarren myself Yogesh Sharma, I have introduced my proposed idea can we consider it for GSoC 2021, and also I'm confused that can we introduced more than one idea?

**Comment by sahilsaha7773** [comment]
Hi! I am a first-year CSE undergrad student with experience in full-stack web dev. I was also one of the winners in GCI 2018. I am really excited to contribute to public lab and be a part of this amazing community!

**Comment by cesswairimu** [comment]
@dhanmoni yeah only the ideas listed under 2021 will be considered.
@YogeshSharma01 the ideas are already present to GSoC and we cannot add any more as of this moment...what applicants normally do is look at the idea list and draft a proposal around any of the projects. Thanks

**Comment by YogeshSharma01** [comment]
@cesswairimu Okay Thanks

**Comment by jywarren** [comment]
Hello all, and welcome! Thanks for introducing yourselves. I work with Cess at Public Lab and have mentored here for some years. I also drafted the ideas list and am happy to answer questions! Thanks all!!!

**Comment by jywarren** [comment]
Also, noting this issue where we've listed our project ideas -- where we can dig into the details and do some Q&A specific to the ideas: https://github.com/publiclab/plots2/issues/9257

Thanks, all!!!!!

**Comment by abhishek-geek** [comment]
Hey @cesswairimu and @jywarren 
I'm Abhishek and i have experience in Javascript, Node, React and HTML/CSS. Most of the project idea for 2021 GSOC needs some Ruby on Rails, and i don't have any experience in that.
Would it be any problem while working on the projects.
I am totally looking to be a part of this community
Thanks.

**Comment by saikeshari** [comment]
Hi @cesswairimu  and @jywarren ,
I am Sai Keshari, a second-year undergrad in Delhi Technological University (DTU).
I am proficient in frontend Web development, particularly in ReactJS. I have also made several projects.
I am fascinated by project ideas in Public Labs and would like to contribute to it as part of my GSoC'21 participation and also would like to continue contributing as I find Public Labs quite interesting application. I explored and found that it requires some Ruby on Rails. I have not learned Ruby on Rails, can I contribute without it. Although, I am open to learning Ruby on Rails for contributing to the project.
Please let me know how I can get started and start contributing.
Cheers

**Comment by cesswairimu** [comment]
Hi @abhishek-geek, hi @saikeshari yeah all the projects we have this round do require some Ruby on Rails, we have had interns before who had no prior Ruby on Rails experience, so that is not a prob..what you could do is start looking at rails during the application period...and start solving some issues on the project so that you can get a hang of it...
@saikeshari  you can checkout https://code.publiclab.org/ on details on how to start contributing feel free to ping me if you are still lost after that or have any further questions..thanks you both

Welcome everyone

**Comment by abhishek-geek** [comment]
Thankyou @cesswairimu 
Looking forward to some good first issue. And meanwhile I'll start learning rails.

**Comment by gaurav2699** [comment]
Hello, I am Gaurav Singh, a 2nd-year Information technology student from the National Institute of Technology Karnataka. I really loved the work you guys are doing. I have experience in Ruby on Rails hence would love to contribute to Public Lab. Thank you.

**Comment by govindgoel** [comment]
Hi everyone, I am Govind Goel an undergraduate student from Amrita Vishwa Vidyapeetham, Amritapuri Campus. I have been working on different projects and contributing to Public Lab and it has been a great journey till now :)
Thank You.

**Comment by manishaag7** [comment]
Hello everyone, I am a 3rd year student . I have basic knowledge of HTML, CSS, Javascript . I know ruby on rails and made a simple website using youtube tutorial. I would like to contribute and I am completely new to open source. Thank you!

**Comment by BondaSaim** [comment]
Hello @cesswairimu and @jywarren ,
I am Bonda Saim, a sophomore at the National Institute of Technology, Warangal
I have been working on Data Science, Machine Learning, Android Application Development, Web Development and Game Development for the past few years.
I am working as a part-time Software Solution Architect at iDataMachine, an Australian AI startup company.
I also have worked on research involving AI and genomic data under the supervision of our college professor.
Now, I want to enter the world of open sourcing and I feel that PublicLab is a great place to start.
I have no prior experience with Ruby, but I believe that I am a fast learner.
If you think that I would be helpful, I would love to contribute on your project.
Thank you and have a good day.

**Comment by cesswairimu** [comment]
Hi all and welcome again, [here](https://publiclab.org/notes/cess/03-24-2021/call-for-2021-gsoc-proposals)  is call for proposals on the PublicLab website...I know the applications open officially for GSoC in 2 days..but feel free to start posting on PublicLab...we  advise applicants to post first on the PublicLab website, get feedback from mentors and then post the refined version on GSoC.

Thanks all and feel free to ask any questions

**Comment by jywarren** [comment]
Welcome @manishaag7 and @BondaSaim!

**Comment by himanshu007-creator** [comment]
Hi everyone!

I am Himanshu from India and I am pursuing B.Tech in electronics and communication with minors in CS. I started coding last year during the lockdown and have come a long way, from missing semicolons to missing closing tags ( pun intended 🙂) .Rest I am looking forward to know the community well.

Here are my socials.
Linkedin:- https://www.linkedin.com/in/himanshu-here

**Comment by anirudhprabhakaran3** [comment]
Hello!

I am Anirudh Prabhakaran, and I'm from India. I have experience with web design, Python and Rails. I'm excited to contribute to Public Lab!

Godspeed

**Comment by 17sushmita** [comment]
Hi @jywarren and @cesswairimu 
Are the first 2 projects strictly reserved for outreachy or GSoC applicants can also make a proposal for it? I had applied for Outreachy but my initial application could not get approved due to not meeting minimum time commitment criteria which is not the case in reality. I'm very eager to work on these projects and would like to participate in GSoC for the same idea. Is it possible to do so?

**Comment by waridrox** [comment]
Hi @jywarren and @cesswairimu, I had a few questions regarding the **spectral workbench integration** project idea under GSoC. Pls have a look. Thanks :)
1 - Does this require the live capture interface code to be re-written in order to integrate with ruby on rails ?
2 - And if so, where do we want to integrate it to, is it supposed to be integrated at https://github.com/publiclab/spectral-workbench or some new domain altogether since the project inline-markdown editor is integrated into the plots2 project I believe…
3 - But then how is the current spectral workbench working then, is it all JS only and is there no RoR integration ?
4 - And do we need a db to store the values for the login users assuming option 1 is correct ?
5 - Are there any enhancements that can be considered if option 1 is correct and the code is to be rewritten altogether ?

**Comment by RuthNjeri** [comment]
Hi everyone! Thank you all for joining us, I am looking forward to contributing with all of you and reviewing your proposals 😃

**Comment by govindgoel** [comment]
@RuthNjeri Thanks, I have posted the draft proposal for translation system refinements here: https://publiclab.org/notes/govindgoel/03-25-2021/gsoc-proposal
I'm working on it to improvise.

**Comment by RuthNjeri** [comment]
Thanks @govindgoel, I'll have a look at it soon and leave some comments.

**Comment by eightballocto** [comment]
Hi all, I'm Michelle—a fairly green developer. I specialize mostly in web design, and I have experience with server-side scripting languages like Python, Ruby, and PHP.

**Comment by RuthNjeri** [comment]
Hi and welcome @eightballocto 🎉

**Comment by omgupta1608** [comment]
Hi, I am Om Gupta, I am a 2nd year student from New Delhi, India. Looking to start my FOSS journey. I am full-stack web developer and work on other technologies like Android, Systems etc.
Hello everyone!! 😊

**Comment by YogeshSharma01** [comment]
Hi, @RuthNjeri 
I have posted the draft proposal for translation system refinements here:
https://publiclab.org/notes/YogeshSharma01/04-04-2021/gsoc-proposal
Please review 
Warm Regards 
Yogesh Sharma
Thanks😊

**Comment by sahilchalia** [comment]
Hello everyone, I am Sahil, a 2nd year BCA student from India. I am new to FOSS and looking to start my journey with you people. I am a front-end web developer and I know flutter as well.

**Comment by gaurav2699** [comment]
Hey @jywarren @cesswairimu @RuthNjeri, I posted my draft proposal for Legacy Code Deprecation Project for GSoC 2021. There are still lot of changes and details to be done. Would appreciate any feedback. Thanks a lot!

**Comment by anirudhprabhakaran3** [comment]
@jywarren @cesswairimu here's my proposal:
https://publiclab.org/notes/anirudhprabhakaran3/04-03-2021/gsoc-2021-proposal-education-related-usability-upgrades

It would be really great to get some feedback. Thanks in advance!

**Comment by YogeshSharma01** [comment]
Hi, @jywarren and @cesswairimu, and @RuthNjeri please review my draft proposal for translation system refinements my proposal  here: 
https://publiclab.org/notes/YogeshSharma01/04-04-2021/gsoc-proposal
There are still a lot of changes and details to be done. Would appreciate any feedback. 
Warm Regards,
Yogesh Sharma
Thanks a lot!

**Comment by jywarren** [comment]
Hi all, I wanted to say welcome to everyone once more -- and to note that we often get DMs from people about reviewing still-not-yet-posted proposals; and I usually respond with something like:

> Hi, thank you so much for your interest! Have you already posted this draft on our call for proposals? That's actually where we make comments and we'd appreciate if you could post there! Feel free to link me to your proposal once you have. Thanks again!!

I totally understand if people aren't sure about posting a draft, but just know that it's totally OK to post a partially complete draft for feedback, in fact it's encouraged! Thanks to those who have already!

Some folks will feel competitive about this and that's understandable, but we really try to encourage people to think cooperatively as much as possible. both because all proposals can improve with peer feedback but also because we are really interested to see how people support one another; this is a big thing we consider in applications - cooperation, teamwork, mutual support. 

Thanks so much for coming and for your time, everyone.

**Comment by NishantJawla** [comment]
Hey @jywarren @cesswairimu @RuthNjeri, I posted my draft proposal for GSoC 2021. There is still a lot of work to be done in terms of changes and details. Any feedback would be greatly appreciated. Thank you very much!

**Comment by SharmaTanish** [comment]
Hi  @jywarren @cesswairimu @RuthNjeri @everyone , I am Tanish BE CSE student at Chitkara University Punjab , India . I have learnt web development from coding ninjas and all my concepts also i have also made many projects using CSS and JS . I am very hardworking and have scored 94.2% in 12th . I had made a pull request of issue#6446 on plot2 repository and also i am looking to work on more issues/projects of public lab ! 
I also have experience of GSSOC (Girlscript summer of code) by GSOC coding time , where i have merged pull requests .
You can also go through my linkedIn profile - https://www.linkedin.com/in/tanish-a54b771b3 .

**Comment by RuthNjeri** [comment]
Hi Everyone, thanks for sharing your proposals, I will have a look at them in the course of the week.

Hi @SharmaTanish thank you for joining us, and welcome!

**Comment by jywarren** [comment]
Hi all - just a reminder to get your proposals posted as soon as possible, to give reviewers time to offer feedback so you can make revisions before the duedate on the 13th! If we don't have time, it's a bit harder to evaluate your proposals as we haven't had a chance to discuss a bit. So we appreciate it! It's totally fine if it's a draft, no problem at all. We just want to get a glimpse and offer some input! Thanks!

**Comment by jywarren** [comment]
Thanks so much everyone for your time! We'll be updating very soon, but proposals closed today at Google's site. Closing this and we are looking forward to the next steps!!!

**Comment by RuthNjeri** [comment]
There were really amazing proposals posted. Thanks, everyone! And all the best.
