### ISSUE TITLE
Form UI Change in different screens

### ISSUE THREAD

**Issue by sahilsaha7773** [publiclab/plots2#9285]
#### What happened just before the problem occurred? Or what problem could this idea solve?
In mobile view, there is no space between the two forms which makes the overall UI look bad.

![Screenshot from 2021-03-11 23-22-30_3](https://user-images.githubusercontent.com/35343652/110832560-75b49500-82c1-11eb-9aaf-3c53e51abb85.png)

When the user is not logged in, the two forms are not perfectly aligned.

![Screenshot from 2021-03-11 23-22-06_2](https://user-images.githubusercontent.com/35343652/110832569-76e5c200-82c1-11eb-81a5-e28473e63e60.png)

#### What did you expect to see that you didn't?

Improve the alignment and overall UI of the forms.

### Please show us where to look

https://publiclab.org/questions

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!
- Browser: Chromium Version 89.0.4389.82 (Official Build)
- OS: Ubuntu 20.04.1 LTS

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by pydevsg** [comment]
Thanks for opening this up @sahilsaha7773 .
Can you please tell me your proposed UI change?

**Comment by sahilsaha7773** [comment]
> Thanks for opening this up @sahilsaha7773 .
> Can you please tell your proposed UI change?

This is how it should look after fixing. These changes will make the UI look better for all devices.

![Screenshot from 2021-03-11 23-54-31](https://user-images.githubusercontent.com/35343652/110835720-2b351780-82c5-11eb-97f9-f78ec30f02fc.png)
![Screenshot from 2021-03-11 23-53-53](https://user-images.githubusercontent.com/35343652/110835725-2cfedb00-82c5-11eb-8bdc-6d18ddc4c5d0.png)

**Comment by pydevsg** [comment]
Go ahead @sahilsaha7773 and fix this issue.

**Comment by cesswairimu** [comment]
This is great :tada: thanks @sahilsaha7773 and @pydevsg  :tada: :tada:
