### ISSUE TITLE
Remove 'place' and 'tool' node types in wiki_controller.rb

### ISSUE THREAD

**Issue by Manasa2850** [publiclab/plots2#9302]
With reference to #714

Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/controllers/wiki_controller.rb](https://github.com/publiclab/plots2/blob/main/app/controllers/wiki_controller.rb) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
  def index
    @title = I18n.t('wiki_controller.wiki')
    sort_param = params[:sort]
    order_string = 'node_revisions.timestamp DESC'

    if sort_param == 'title'
      order_string = 'node_revisions.title ASC'
    elsif sort_param == 'last_edited'
      order_string = 'node_revisions.timestamp DESC'
    elsif sort_param == 'edits'
      order_string = 'drupal_node_revisions_count DESC'
    elsif sort_param == 'page_views'
      order_string = 'views DESC'
    elsif sort_param == 'likes'
      order_string = 'cached_likes DESC'
    end

    @pagy, @wikis = pagy(Node.includes(:revision)
      .references(:node_revisions)
      .group('node_revisions.nid, node_revisions.vid')
      .order(order_string)
-     .where("node_revisions.status = 1 AND node.status = 1 AND (type = 'page' OR type = 'tool' OR type = 'place')"))
+     .where("node_revisions.status = 1 AND node.status = 1 AND type = 'page')

    @paginated = true
  end

  def stale
    @title = I18n.t('wiki_controller.wiki')

    @pagy, @wikis = pagy(Node.includes(:revision)
      .references(:node_revisions)
      .group('node_revisions.nid, node_revisions.vid')
      .order('node_revisions.timestamp ASC')
-     .where("node_revisions.status = 1 AND node.status = 1 AND (type = 'page' OR type = 'tool' OR type = 'place')"))
+     .where("node_revisions.status = 1 AND node.status = 1 AND type = 'page')

    @paginated = true
    render template: 'wiki/index'
  end
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by jcads** [comment]
Can I work on this one?

**Comment by Manasa2850** [comment]
Sure @jcads you can work on it!

**Comment by cesswairimu** [comment]
Hi @Manasa2850 hi @jcads , I am not sure why we had the two types here or its some deprecated types that we do  not use anymore...tagging @jywarren  to confirm its okay to remove these. Thanks you both

**Comment by Manasa2850** [comment]
Hi @cesswairimu. According to #714, we don't use these two types anymore.

**Comment by cesswairimu** [comment]
Gotcha, thanks for that
