### ISSUE TITLE
Remove references to "place" and "tool" node types in tag.rb

### ISSUE THREAD

**Issue by jcads** [publiclab/plots2#9307]
## In reference to #714.

Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [x] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [x] 📝 **Update** L121 and L467 of the files [/app/models/tag.rb](https://github.com/publiclab/plots2/blob/56139e9197769a8e0b7c16bd782f1f1060a99fff/app/models/tag.rb) and [/app/controllers/tag_controller.rb](https://github.com/publiclab/plots2/blob/56139e9197769a8e0b7c16bd782f1f1060a99fff/app/controllers/tag_controller.rb), respectively, in the `https://github.com/publiclab/plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

_/app/models/tag.rb_
```diff
-  # just like find_nodes_by_type, but searches wiki pages, places, and tools
+  # just like find_nodes_by_type, but searches wiki pages
  def self.find_pages(tagnames, limit = 10)
-   find_nodes_by_type(tagnames, %w(page place tool), limit)
+   find_nodes_by_type(tagnames, %w(page), limit)
  end
```

_/app/controllers/tag_controller.rb_
```diff
  def contributors_index
    @tagnames = ['balloon-mapping', 'spectrometer', 'infragram', 'air-quality', 'water-quality']
    @tagdata = {}
    @tags = []

    @tagnames.each do |tagname|
      tag = Tag.find_by(name: tagname)
      @tags << tag if tag
      @tagdata[tagname] = {}
      t = Tag.where(name: tagname)
      nct = NodeTag.where('tid in (?)', t.collect(&:tid))
      @tagdata[tagname][:users] = Node.where('nid IN (?)', nct.collect(&:nid)).collect(&:author).uniq.size
-      @tagdata[tagname][:wikis] = Node.where("nid IN (?) AND (type = 'page' OR type = 'tool' OR type = 'place')", nct.collect(&:nid)).size
+      @tagdata[tagname][:wikis] = Node.where("nid IN (?) AND (type = 'page')", nct.collect(&:nid)).size
      @tagdata[:notes] = Node.where("nid IN (?) AND type = 'note'", nct.collect(&:nid)).size
    end
    render template: 'tag/contributors-index'
  end
```

- [x] 💾 **Commit** your changes

- [x] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [x] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by jcads** [comment]
@17sushmita you can work on this one.

**Comment by 17sushmita** [comment]
> @17sushmita you can work on this one.

Thank You for the response but I already contributed to a fto issue. I reached out to the issue myself and that could be the case my name was still listed in issue #9083. Should I open a PR for this or leave this for other first timers.

**Comment by cesswairimu** [comment]
@17sushmita please lets leave it for a first-timer, I will mark your name on the list thanks...Thanks a lot @jcads  for opening this

**Comment by jywarren** [comment]
Hi @jcads really nice FTO here! Thanks!!

**Comment by manishaag7** [comment]
Can I solve this issue? I am new to open source.

**Comment by jcads** [comment]
@manishaag7 go ahead! Let me know if you have any questions.

**Comment by manishaag7** [comment]
@jcads I have to change one line in each file or look in the whole file and change everywhere wherever applicable?

**Comment by jcads** [comment]
@manishaag7 just 1 line in each file. 

Just follow the diff above and you're good.
