### ISSUE TITLE
Weekly Community Check-In #95

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#9318]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

The Outreachy winter 2020 interns(@RuthNjeri  and @noi5e) are having a  presentation today of their awesome work they have been doing over the last 4 months. All are welcome :tada: :tada:
 
**date:** 16th March 2021
**time:** https://bit.ly/3kTir8L
**meeting link:** https://us02web.zoom.us/j/86297425690?pwd=ZFAyUnd2UjQ5dkp6ekM1QzYxcjdrdz09

## This week's focus Issues

These are issues that are of high priority and requests from our
large community that use the software. 

1. https://github.com/publiclab/plots2/issues/9292
2. https://github.com/publiclab/plots2/issues/9164

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note to focus issues contributors

 A big thanks to the FTO authors of the past week  :1st_place_medal:  :1st_place_medal: @Manasa2850 @jcads @SidharthBansal  @manchere 🥇 :1st_place_medal: 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by RuthNjeri** [comment]
Thanks @cesswairimu 😄 

Here is my presentation for anyone who would like to access it https://docs.google.com/presentation/d/1QD7PFCg3woBqfXVvndP6_Yj38TRwhbFeXNp920sF3pU/edit?usp=sharing
