### ISSUE TITLE
Follower/Following page: hovercard on follower/following user profile

### ISSUE THREAD

**Issue by 17sushmita** [publiclab/plots2#9326]
Enhance the follower/following list at https://publiclab.org/people/liz/followers

-  on hover to a profile, the user's bio or follower/following count shows up

**Comment by Priyaraj17** [comment]
May I please work on this issue?

**Comment by 17sushmita** [comment]
@Priyaraj17 , I've already linked a PR for this issue. You might want to take up any `first-timers issue` labelled issue to start with 😄️

**Comment by Priyaraj17** [comment]
@17sushmita Sure. Thanks
