### ISSUE TITLE
Make "contributors" tab on tag listing pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#933]
Hi, this is a `first-timers-only issue`. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

Our tag pages show a lot of rich info about recent tag-specific content: 

https://publiclab.org/tag/spectrometer

One link that's a bit hidden is the "recent contributors" one, at the bottom of the left-hand column, which leads to:

https://publiclab.org/contributors/spectrometer

But that's an important page for crediting everyone who's posted on that topic.

## Solution

It'd be great to make this into a tab, similarly to the other tabs, as in this template: 

https://github.com/publiclab/plots2/blob/master/app/views/tag/show.html.erb#L61-L66

It could use the `<i class="fa fa-user"></i>` icon, and be called "Contributors", something like this:

```ruby
    <li><a href="/contributors/<%= params[:id] %>"><i class="fa fa-user"></i> <%= raw t('tag.show.contributors') %></a></li>
```

But then we'd have to add a translation in English and German, so the `t('tag.show.contributors')` tab text works; those two translation files are:

* https://github.com/publiclab/plots2/blob/master/config/locales/views/tag/show/en.yml
* https://github.com/publiclab/plots2/blob/master/config/locales/views/tag/show/de.yml

We'd add to the English one:

```ruby
       contributors: "Mitwirkende"
```

And to German: 

```ruby
       contributors: "Contributors"
```

That should do it!

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by gcttong** [comment]
I can do this one!

**Comment by ebarry** [comment]
Hi @gcttong! Thank you again for your valuable contribution to Public Lab. I would like to invite you to join us in a video conference to say a few words about what you contributed and how your experience was. The event is https://publiclab.org/openhour, and it’s coming right up on November 7th, at 1pm EDT which is UTC/GMT -4. 

Please feel free to respond here, or else email liz@publiclab.org, stevie@publiclab.org, jeff@publiclab.org.
