### ISSUE TITLE
Add questions count to profile page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#934]
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

Profile pages on PublicLab.org show a list of questions for each user, under the `Questions` tab:

![screenshot 2016-10-30 at 7 26 29 pm](https://cloud.githubusercontent.com/assets/24359/19842499/e449c04a-9ed6-11e6-90f0-798b41c9df49.png)

As in the screenshot, you can see Answers too, by clicking on the two-part button. Try this yourself on my profile page: https://publiclab.org/profile/warren

It would be great to see how many questions are listed (let's not think about answers for now, but that could be a nice follow-up question!)

## Solution

Where to find the relevant lines of code: https://github.com/publiclab/plots2/blob/master/app/views/users/profile.html.erb#L156

The line displaying the tab is:

```ruby
    <li><a href="#questions" data-toggle="tab"><i class="fa fa-comments"></i><span class="hidden-sm hidden-xs"> <%= t('users.profile.questions') %></span></a></li>
```

You can change that to:

```ruby
    <li><a href="#questions" data-toggle="tab"><i class="fa fa-comments"></i><span class="hidden-sm hidden-xs"> <%= t('users.profile.questions') %> (<%= DrupalNode.questions.where(status: 1, uid: @user.id).count %>)</span></a></li>
```

That should show the # of questions in parentheses in the tab!

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by gcttong** [comment]
working on it!

**Comment by gcttong** [comment]
OK submitted the pull request!

**Comment by ebarry** [comment]
Hi @gcttong! Thank you again for your valuable contribution to Public Lab. I would like to invite you to join us in a video conference to say a few words about what you contributed and how your experience was. The event is https://publiclab.org/openhour, and it’s coming right up on November 7th, at 1pm EDT which is UTC/GMT -4. 

Please feel free to respond here, or else email liz@publiclab.org, stevie@publiclab.org, jeff@publiclab.org.
