### ISSUE TITLE
Weekly Community Check-In #96 - Understanding Your Users and The Product

### ISSUE THREAD

**Issue by RuthNjeri** [publiclab/plots2#9350]
Hi everybody! 👏

 I hope you had a wonderful weekend 🌴 

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Understanding Your Users and The Product

Most times, in a software development environment, it is so easy to get into the routine of just writing code and somehow forgetting about the end-users or the community that the code benefits. Writing code with the end-users in mind as well as the business goals helps in creating a product that you will be proud of as well as loved by the end-users.

What are some of the questions you ask yourself about the end-users or the Public Lab platform when you are contributing code? Have you attended any Public Lab [Open Call](https://publiclab.org/wiki/open-call) meetings? What do you think about the platform?

I'll share my experience in the comment section below.

## This week's focus Issues

These are issues that are of high priority and requests from our large community that use the software. 

1. https://github.com/publiclab/PublicLab.Editor/issues/698
2. https://github.com/publiclab/plots2/issues/9164
3. https://github.com/publiclab/plots2/issues/8864

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

## Thank you note to focus issues contributors

🥇 🥇 🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇
 @Manasa2850, @noi5e, @govindgoel, @waridrox, @jcads, @17sushmita, @DBailie96, @nlao1, @gaurav2699, @adedejisalim, @saikeshari 
🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by RuthNjeri** [comment]
During my Outreachy contribution period with Public Lab, I was interested in hearing from the Public Lab community specifically the end-users, I would read some research notes posted on the site and once joined an air quality open call. 
It was great to see that the code contributions I wrote translated into something that was benefiting the community. I think that once in a while it's important to look at the other side of the software development "curtain" and learn from your users and even test the product you are working on with them.

If you have recently contributed or are planning to contribute to [Public Lab](https://publiclab.org/). Go over to the website, read some research notes,  and even join an [Open call](https://publiclab.org/wiki/open-call) if you can! You'll be guaranteed to learn something!

Have a great week!

**Comment by jywarren** [comment]
Hi all, it's always a pleasure to return on Tuesday morning and see so much collaboration, mutual support, helpfulness and kindness. Keep up the great work!

**Comment by cesswairimu** [comment]
Hi all, 
I agree, it whole different view hearing from end-useurs and some features  end up being used in a very different way than when developing you didn't think of.  Open calls are great 

A call for GSoC proposals is [here](https://publiclab.org/notes/cess/03-24-2021/call-for-2021-gsoc-proposals)

Great theme @RuthNjeri  :tada:  thanks all

**Comment by cesswairimu** [comment]
@RuthNjeri I love many medals emojis on thank you note section...adapting that :smiley: 

Moved to https://github.com/publiclab/plots2/issues/9389
Thanks everyone
