### ISSUE TITLE
Animate Save Icon When User Enters Comment Text

### ISSUE THREAD

**Issue by noi5e** [publiclab/plots2#9362]
## `Description`
From a user interaction standpoint, it would be helpful to have the save icon blink whenever a user enters text into a comment form.

The save icon is the 💾 in the comment toolbar below:

<img width="406" alt="Screen Shot 2021-03-22 at 7 11 24 PM" src="https://user-images.githubusercontent.com/4361605/112082718-0f423900-8b43-11eb-935c-02b46b90c57b.png">

See #9131, particularly [this comment](https://github.com/publiclab/plots2/issues/9131#issuecomment-776245431).

Currently the comment form saves every single time the input is changed. This isn't very useful to the user, so we'll also want to implement some kind of [debouncing](https://www.freecodecamp.org/news/javascript-debounce-example/) or `setTimeout` delay.

## `Summary of Changes to Be Made`
These changes can be done in separate PRs, and by different contributors. But they probably have to be done in sequence:

1. Add debouncing to delay the `save` method in `editor.js`, either wait 1000ms, or only run `save` when user input has stopped for 500ms (you choose the time).
2. Add some animation to the 💾 save icon when the `save` method runs, so that user knows that it's running. Darken the icon background. Replace the 💾 with one of [these FontAwesome spinner icons](https://fontawesome.com/how-to-use/on-the-web/styling/animating-icons).
3. Swap out the `Drag and drop to add an image or file, or choose one` with `Saving...` to absolutely spell it out for the user.

## `Useful Links & Images`
What the end goal looks like:
<img width="555" alt="Screen Shot 2021-03-23 at 12 04 39 PM" src="https://user-images.githubusercontent.com/4361605/112203635-fe8bd480-8bcf-11eb-9c75-05b5c0e2002e.png">

These changes are going to be made in the comment/legacy editor, which lives at `app/assets/javascripts/editor.js`:
https://github.com/publiclab/plots2/blob/62fdcd0dd54b47727a046a0129ba138710082f0b/app/assets/javascripts/editor.js#L116-L119

Leave a comment below if you want to claim this issue, and post here if you need any help getting oriented to the codebase! Good luck! 🍀

**Comment by waridrox** [comment]
Can I give it a shot! This one seems to implement some great functionality :D

**Comment by noi5e** [comment]
@waridrox Definitely, go ahead!

**Comment by waridrox** [comment]
- I'm having a hard time thinking about how we can implement the spinner when the save function is being performed. That's because the whole toolbar is rendered as a partial initially so I'm not sure if we can render that specific save option differently than the rest of the toolbar icons. 

- I've managed to implement a debounce function in the save function though which may same some cpu resources.


https://user-images.githubusercontent.com/58583793/112347402-d5ad3180-8cec-11eb-9984-c0287c32c23c.mp4

- Another thing that we might do is to get away with the save icon completely and prompt the user somewhere that the posts get auto-saved so they don't need to worry about it. But that might not be a great idea from a perspective of user feedback.

@noi5e What are your views on this 🤔 ?

**Comment by noi5e** [comment]
@waridrox This is great work so far, and good questions!

> I'm having a hard time thinking about how we can implement the spinner when the save function is being performed. That's because the whole toolbar is rendered as a partial initially so I'm not sure if we can render that specific save option differently than the rest of the toolbar icons.

The `Editor` class has an attribute `commentFormId`:
https://github.com/publiclab/plots2/blob/a44aff71c69671d2cb7142e1d93d45ff97114c06/app/assets/javascripts/editor.js#L10-L11

Which can be used to refer to the particular save button that needs to be updated:
https://github.com/publiclab/plots2/blob/a44aff71c69671d2cb7142e1d93d45ff97114c06/app/views/editor/_toolbar.html.erb#L81-L90

jQuery seems like the best tool to use in this situation. Perhaps the spinner icon can be a sibling of `<i class="fa fa-save"></i>` set to `display: none;` and jQuery will `toggle()` visibility between one element and the other.

`editorToolbar.js` does a similar thing with jQuery whenever images are uploaded to a comment form, and we need to toggle visibility of the image upload progress bars:
https://github.com/publiclab/plots2/blob/a44aff71c69671d2cb7142e1d93d45ff97114c06/app/assets/javascripts/editorToolbar.js#L26-L32

> I've managed to implement a debounce function in the save function though which may same some cpu resources.

Nice! 🙌 

> Another thing that we might do is to get away with the save icon completely and prompt the user somewhere that the posts get auto-saved so they don't need to worry about it. But that might not be a great idea from a perspective of user feedback.

Hmm... Personally I want users to be able to use a feature we already have, and for them to know about it in an intuitive way... I think this issue is the best way to do it that I can think of. But definitely open to hearing other ideas about how to do that!

**Comment by waridrox** [comment]
> Which can be used to refer to the particular save button that needs to be updated:

Thanks for the info! 😄

**Comment by waridrox** [comment]
_Update_ - @noi5e, here are 2 versions of the implementations, though there is still a small problem to resolve 😅

_Save button with the spinner icon_

https://user-images.githubusercontent.com/58583793/112682150-b30a4c80-8e95-11eb-8e85-926dee85200d.mp4

___
_Save button with no functionality_ 

https://user-images.githubusercontent.com/58583793/112682176-be5d7800-8e95-11eb-8752-82fc1e034633.mp4

But as you might have noticed, there are conflicting CSS styles at the save button which I can't figure it out yet that turn the save icon  💾 to the white color of the background 😅 when the save button is clicked.

Meanwhile would you like to see any further enhancements added like 
> Swap out the Drag and drop to add an image or file, or choose one with Saving... to absolutely spell it out for the user. ?

**Comment by waridrox** [comment]
Here's the final implementation, I'm really not sure how to make the CSS styles work without affecting when the 💾 icon when it is clicked. Maybe someone else can try that 😅. Other than that I've implemented what was required.
