### ISSUE TITLE
Installation Error: rake db:setup

### ISSUE THREAD

**Issue by achhetr** [publiclab/plots2#9366]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
I am trying to install the plot2, while on step 8 when I run `rake db:setup`. It gives me an error

rake db:setup                               
rake aborted!
LoadError: Error loading the 'mysql2' Active Record adapter. Missing a gem it depends on? mysql2 is not part of the bundle. Add it to your Gemfile.
/Users/akash/Documents/projects/opensource/plots2/config/environment.rb:5:in `<top (required)>'

Caused by:
Gem::LoadError: mysql2 is not part of the bundle. Add it to your Gemfile.
/Users/akash/Documents/projects/opensource/plots2/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create => db:load_config => environment
(See full trace by running task with --trace)

> What did you expect to see that you didn't?
I was expecting mysql2 database to setup

### Please show us where to look
https://github.com/publiclab/plots2#standard-installation 
step 8
https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by waridrox** [comment]
@achhetr Please look forward to setting up a redis db and starting it by following the instructions at https://github.com/publiclab/plots2#redis-installation and starting it. There are some problems with setting up a mysql db currently.

**Comment by achhetr** [comment]
When running 
`bundle exec sidekiq` I get the following error

`2021-03-26T07:15:59.431Z pid=93438 tid=ouq0w4a9a WARN: Sprockets::Railtie::ManifestNeededError: Expected to find a manifest file in `app/assets/config/manifest.js`
But did not, please create this file and use it to link any assets that need
to be rendered by your app:

Example:
  //= link_tree ../images
  //= link_directory ../javascripts .js
  //= link_directory ../stylesheets .css
and restart your server

For more information see: https://github.com/rails/sprockets/blob/070fc01947c111d35bb4c836e9bb71962a8e0595/UPGRADING.md#manifestjs
2021-03-26T07:15:59.431Z pid=93438 tid=ouq0w4a9a WARN: /Users/akash/.rvm/gems/ruby-2.6.6/gems/sprockets-rails-3.2.2/lib/sprockets/railtie.rb:106:in `block in <class:Railtie>'`

**Comment by waridrox** [comment]
Maybe this can be useful - https://github.com/mperham/sidekiq/issues/1500

**Comment by gaurav2699** [comment]
Hey @achhetr, I was having the same problem. So, I set up SQLite instead of MySQL and that worked for me. I think setting up with MySQL has some issues. Hope this solves this problem.

**Comment by anirudhprabhakaran3** [comment]
Yes. Instead of doing 
```
cp config/database.yml.example config/database.yml
```
try doing 
```
cp config/database.yml.sqlite.example config/database.yml
```
This clears the issue.

**Comment by waridrox** [comment]
@achhetr, If you are still not able to get it work, after running the command `cp config/database.yml.sqlite.example config/database.yml`, refer [_this_](https://stackoverflow.com/questions/58339607/why-does-rails-fails-to-boot-with-expected-to-find-a-manifest-file-in-app-asse#answer-58370129:~:text=Easy%20Steps%20To%20Solve%20the%20Problem%3A) to resolve the error.

**Comment by achhetr** [comment]
changing database to sqlite worked, thank you guys I am closing this issue
