### ISSUE TITLE
MimeMagic Build Failure

### ISSUE THREAD

**Issue by RuthNjeri** [publiclab/plots2#9377]
There are 3 stable builds that have failed for far because of this [error ](https://jenkins.laboratoriopublico.org/job/Plots-Stable/2590/console)

It would seem that it has been [archived](https://github.com/rails/rails/issues/41750)...

```
[91mYour bundle is locked to mimemagic (0.3.3), but that version could not be found
in any of the sources listed in your Gemfile. If you haven't changed sources,
that means the author of mimemagic (0.3.3) has removed it. You'll need to update
your bundle to a version other than mimemagic (0.3.3) that hasn't been removed
in order to install.
The command '/bin/sh -c gem install --default bundler &&     gem update --system &&     bundle install --jobs=4' returned a non-zero code: 7
[0mService 'web' failed to build
make: *** [Makefile:5: build] Error 1
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by RuthNjeri** [comment]
Maybe upgrading it to 0.3.6 will help? https://github.com/mimemagicrb/mimemagic/issues/98#issuecomment-805766052

**Comment by RuthNjeri** [comment]
Looks like 0.3.6 has some trouble as well...using `0.3.8`
![Screenshot 2021-03-25 at 22 45 59](https://user-images.githubusercontent.com/7622875/112534305-f2646a80-8dbb-11eb-9ceb-dd7cd57c244c.png)

**Comment by cesswairimu** [comment]
Thanks Ruth, There is a conversation about this on the rails repo [here](https://github.com/rails/rails/issues/41750) most people upgraded to 0.3.6 and it seemed to work

**Comment by cesswairimu** [comment]
Also noting rails 5.2.5 have been released addressing the issue more details https://weblog.rubyonrails.org/

**Comment by RuthNjeri** [comment]
Thanks, @cesswairimu, should we look into upgrading our version `5.2.3` to `5.2.5`? Then see what version of mimemagic to use...
