### ISSUE TITLE
Error Command "webpack" Not Found

### ISSUE THREAD

**Issue by RuthNjeri** [publiclab/plots2#9382]
[Builds](https://jenkins.laboratoriopublico.org/job/Plots-Stable/) have been failing in the stable deployment due to the error `error Command "webpack" not found`

This seems to be a common error and there are some solutions as suggested below;

https://github.com/rails/webpacker/issues/522#issuecomment-328985202
https://github.com/rails/webpacker/issues/522#issuecomment-309873612

I am not sure what criteria we should use to pick a fix.

**Comment by RuthNjeri** [comment]
Do you have any thoughts on this @noi5e?

**Comment by anirudhprabhakaran3** [comment]
Running 
```
rails webpacker:install
```
on my local machine seems to solve this issue

**Comment by waridrox** [comment]
As pointed out in the gitter channel by @noi5e - 
```
bundle install
rails webpacker:install
rails webpacker:install:react
rails generate react:install
```

Running these commands solves the issue.

**Comment by waridrox** [comment]
@jywarren I ran into the webpack problem after syncing my fork, and was able to resolve it with these commands - 
```
bundle install
rails webpacker:install
rails webpacker:install:react
rails generate react:install
```

>For now, you have to create a manifest.js file, following the steps shown here: https://stackoverflow.com/questions/58339607/why-does-rails-fails-to-boot-with-expected-to-find-a-manifest-file-in-?app-asse#answer-58370129:~:text=Easy%20Steps%20To%20Solve%20the%20Problem%3A

This I believe is for people trying to setup a new db altogether, with sqlite following the command - `cp config/database.yml.sqlite.example config/database.yml` wherein there is some configuration required after this command. Since I already had redis db setup already I didn't faced the issue of creating a `manifest.js` file.

**Comment by noi5e** [comment]
I just made an FTO at #9392 to update the installation docs for React & webpacker setup!

It's a distinct issue from this one, because as @RuthNjeri mentioned in the original post [builds are failing](https://jenkins.laboratoriopublico.org/job/Plots-Stable/) over at `stable`. For that we'll need to ping @icarito, which I'll do in chat right now.

**Comment by jywarren** [comment]
oh this is awesome.  Thank you @noi5e!!!!!

**Comment by icarito** [comment]
A couple of weeks ago, webpacker was built correctly in our unstable staging instance.
https://jenkins.laboratoriopublico.org/job/Plots-Unstable/1098/console

I pushed `unstable` to a new branch and made a pull request to be able to compare the code:
https://github.com/publiclab/plots2/pull/9393/files

It looks to me like @anirudhprabhakaran3 is correct that the node version needs to be updated.

**Comment by jywarren** [comment]
OK just noting that @icarito and i realized the GitHub diff is wrong - all those changes are already in our `main` branch. Also it seems to be building our `stable` branch fine in Jenkins, so something is odd with our `main` branch not building to `stable.publiclab.org`. Looking deeper...

**Comment by jywarren** [comment]
Just noting that it seems to be written wrong in 3 places in the GitHub Actions config - `webpack` instead of `webpacker`:

https://github.com/publiclab/plots2/blob/999264ebe70d750f1836a4b4dcbdb7118595639b/.github/workflows/tests.yml#L49

**Comment by jywarren** [comment]
I think stable.publiclab.org is building again!!!

**Comment by icarito** [comment]
Yup, I think #9395 did fix it.

**Comment by noi5e** [comment]
Ah, great, I see. I put the commands in the wrong order. Thanks @icarito!

**Comment by noi5e** [comment]
> Just noting that it seems to be written wrong in 3 places in the GitHub Actions config - webpack instead of webpacker:

Oh yeah, I left a note about this in chat (but obviously it's easy to miss with all the activity lately):

> It's meant to be rails webpacker:install:react instead of rails g webpack:install:react. 🤦 @jywarren You might want to take note, because we currently have 2 out of 3 wrong commands in the GitPod & test flows!

**Comment by jywarren** [comment]
OK, i'll make that change in a pr, thanks @noi5e !!!

**Comment by RuthNjeri** [comment]
Thanks, everyone! 🎉 
Closing the issue since PRs referencing it have been merged 🚀
