### ISSUE TITLE
Welcome Outreachy Summer 2021 Aspirants 🎉🙋‍♀️🙋🙋‍♂️

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#9388]
# :tada: Welcome Outreachy applicants Summer 2021  :tada:

Hello :wave: and welcome to PublicLab :balloon: We are so excited to have you here :heart: . This is a discussion issue for all of you. Please say hello in a comment below, so we get to know you. Ask any questions that you might have here and we will be sure to answer them as soon as possible. If you would like to checkout our large community you can find us on gitter https://gitter.im/publiclab/publiclab and also we do weekly check-ins where folks say what they are working on and ask for help if blocked. You can find the link to the latest check-in here #5627 

## First Step :computer: 
We suggest you make a first contribution. We have issues with the `first-timer-only` label which are specifically tailored for a first time contributor. You can find them here https://code.publiclab.org/ along with the guidelines on how to start contributing. Please be sure to check if someone is already working on an issue before you take it up. Kindly leave a comment on the issue to let other people know you are working on an issue. If you can't find any issues that are available, please feel free to leave a comment below or on #9083 and we will find you one asap. 
After you solve the first issue you can browse through our  "help-wanted" issues. Feel free to tag @publiclab/mentors or @cesswairimu if you need more context for you to solve an issue.

## Outreachy summer 2021 Projects :memo: 

We have 2 projects for this round.

1. [Expand and refine Tag/topic system of PublicLab.org](https://www.outreachy.org/outreachy-may-2021-internship-round/communities/public-lab/#expand-and-refine-tagtopic-system-of-publiclaborg)
2. [Improve education-related usability and functionality on PublicLab.org](https://www.outreachy.org/outreachy-may-2021-internship-round/communities/public-lab/#improve-education-related-usability-and-functional)

Github discussion: #9257

## Call for Proposals :page_with_curl: 
We request applicants to post their proposals on the PublicLab website. [Here](https://publiclab.org/notes/cess/04-04-2021/call-for-proposals-outreachy-summer-2021) is a link to a call for proposals on the PL website, which also has a template for drafting the template, sample proposals for past interns and helpful pointers while drafting the proposals. 
[See 2020 winter proposals here](https://publiclab.org/notes/cess/10-02-2020/call-for-proposals-outreachy-winter-2020)
Kindly submit early and post the link here or on gitter so that contributors and mentors can give feedback and help you improve on your proposal before you submit it on the Outreachy website.

### Deadline 
April 30, 2021 4pm UTC is the deadline for applicants to record contributions and create a final application on the Outreachy website

### Questions :thinking: 
 If you have any questions please leave a comment below and we will get back to you

#### These tips are general tips.
Are you tensed? overwhelmed?  No need to worry!!! We all are there to help you at each stage of the way. Feel free to reach out in case of anything people are very friendly and welcoming here :relaxed:

**Comment by jywarren** [comment]
A special welcome to Outreachy applicants, and thank you for your time! We are so honored to have the chance to work with you and want you to know that we're here to help, both in the comments right here, and in our chatroom at https://gitter.im/publiclab/publiclab if you need help in the moment.

I'm Jeff -- he/him -- and I'm one of the code community coordinators here along with @cesswairimu 🙌  and @RuthNjeri ✨ , both of whom joined Public Lab through Outreachy. I like cooking, growing plants, bicycling, and drawing. 

I also want to give a shout out to our former Outreachy fellows from months and years past, many of whom i'm sure will be happy to welcome you as well! @publiclab/soc 🎉 🎉 🎉 🎉 🎉 

Thanks again and don't be a stranger!

**Comment by amiyahfrierson** [comment]
Hi! I'm Amiyah and I'm new to FOSS and making contributions, but I am eager to grow my skills through the Outreachy program. 😄

**Comment by jcads** [comment]
Hi @amiyahfrierson, welcome! Checkout https://code.publiclab.org/ on details on how to start contributing. Feel free to ask any questions here or in the chatroom.

Thank you!! :tada: :tada:

**Comment by jywarren** [comment]
Hi @amiyahfrierson - welcome!!!

**Comment by aliciapaz** [comment]
Hi everyone, I'm Alicia. Hoping to make my first contribution soon 🌱

**Comment by iamananya** [comment]
Hello ! I am ananya .Looking forward to contribute to the projects and get guidance from the awesome community of public labs.😁😁

**Comment by goodluck1455** [comment]
Hello everyone, am Goodluck Stephen by name, always ready to learn and grow at any point in time. I look forward to contributing to the project and as well learn new things.

Thank you.

**Comment by jywarren** [comment]
Hello @aliciapaz @iamananya @goodluck1455 -- a big welcome to you all!

**Comment by omgupta1608** [comment]
Hello, I am Om. I am new to FOSS and would like to start my journey. Looking forward to working with great people on great tech. 😊

**Comment by RuthNjeri** [comment]
Hi everyone! And Welcome @omgupta1608, @aliciapaz, @iamananya, @goodluck1455 and @amiyahfrierson 🎉 
We are happy to have you join us in your Open Source journey. I'll be creating a couple of first-timer issues that you could try out in the next few hours. If you are unable to find an issue please reach out to us here, and we'll help you find one. Thank you!

**Comment by sahilchalia** [comment]
I am a first-timer in FOSS. Looking forward to work with the amazing publiclab community. I am a front-end developer skilled in Web and Mobile Applications development. 
Hello everyone!

**Comment by RuthNjeri** [comment]
Hi and welcome @sahilchalia 😃

**Comment by cesswairimu** [comment]
Hi everyone and welcome!!, 
[Here](https://publiclab.org/notes/cess/04-04-2021/call-for-proposals-outreachy-summer-2021) is a call for proposals on the PL website Please do consider submitting early so that mentors can give feedback and help you improve on your proposal before you submit it on the Outreachy website. Thanks all :heart:

**Comment by roli25** [comment]
Hello everyone, I am Roli Jain , an Outreachy applicant. I wish to contribute in Publiclab organization.
Could you please suggest some issues to get started with?
Thankyou.

**Comment by aliciapaz** [comment]
Hi @cesswairimu! Thank you for your welcoming words.
I opened a pull request on this issue last week: https://github.com/publiclab/plots2/issues/9398 and I had some problems with the tests...I would appreciate some guidance on that, please.
Meanwhile, should I wait until I solve that one before moving to a new issue?
Thanks in advance!

**Comment by cesswairimu** [comment]
Hi @aliciapaz, you can move to another issue as you wait...I will take a look at your pull request later today and leave some comments. Thanks

**Comment by jywarren** [comment]
Hi all, I wanted to say welcome to everyone once more -- and to note that we often get DMs from people about reviewing still-not-yet-posted proposals; and I usually respond with something like:

> Hi, thank you so much for your interest! Have you already posted this draft on our call for proposals? That's actually where we make comments and we'd appreciate if you could post there! Feel free to link me to your proposal once you have. Thanks again!!

I totally understand if people aren't sure about posting a draft, but just know that it's totally OK to post a partially complete draft for feedback, in fact it's encouraged!

Some folks will feel competitive about this and that's understandable, but we really try to encourage people to think cooperatively as much as possible. both because all proposals can improve with peer feedback but also because we are really interested to see how people support one another; this is a big thing we consider in applications - cooperation, teamwork, mutual support. 

Thanks so much for coming and for your time, everyone.

**Comment by Elukoye** [comment]
Hello guys,
 I have a quick question @jywarren, @cesswairimu, @RuthNjeri  and all other mentors. I have scrolled through the list of candidate issues that would be good FTO and some of them are fixed. Do you need any help weeding out those? Also, I have an FTO issue separate from the list, do I create the issue then submit it or does it have to come from this list [Candidates for FTO](https://github.com/publiclab/plots2/labels/fto-candidate)

**Comment by RuthNjeri** [comment]
Hi @Elukoye 

Thanks for reaching out about this, please share the links to the ones that are fixed and @cesswairimu, @jywarren, and I will have a look at them.

We would love more FTO issues posted, you do not need any other requirement apart from choosing the FTO issue template when creating one. If you have any questions, you can tag us and we'll be happy to review it, thank you!

**Comment by jywarren** [comment]
Hi, everyone! Just wanted to note that if you are already applying to Outreachy, and qualify for GSoC, please consider applying to GSoC as well! As it's a shorter/smaller program (in time) I understand it doesn't work for everyone. But given the very small number of slots we typically manage to get in Outreachy, we are always very happy to support some additional folks from the Outreachy cohort via GSoC if we can make it work. You can definitely halve the project work to make this feasible. 

Happy to answer questions on this. And keep in mind the application for GSoC is due on the 13th! https://summerofcode.withgoogle.com/

**Comment by jywarren** [comment]
And one more thing - we're getting close to the GSoC proposal deadline, and it can be quite helpful to read over the proposals we're getting for that program, in terms of the kinds of details, questions, etc we have in mind when looking at a project proposal. The programs are of course not the same but a couple of the project ideas are, and if you are inclined to offer suggestions or ask questions over there too, it's very welcome! Thanks, all!

https://publiclab.org/notes/cess/03-24-2021/call-for-2021-gsoc-proposals

**Comment by Elukoye** [comment]
hello ✋ @RuthNjeri ,
This is the link to the article I used to install RVM in WSL2 in the pre-installation guide.
I think it is useful for those who are using Ubuntu through WSL2 because we can't log in in as a shell. There is no GUI for that.
Is it possible to add it to the pre-installation instructions, especially the RVM and Ruby installation sections?
[Follow this link](https://linuxize.com/post/how-to-install-ruby-on-ubuntu-20-04/)

**Comment by RuthNjeri** [comment]
Hi, @Elukoye thanks for sharing. I think you could create specific instructions for the WSL2 guide similar to the Windows one on the README https://github.com/publiclab/plots2#windows-installation. That's a good FTO issue, do you want to write that up?

**Comment by Elukoye** [comment]
@RuthNjeri yes ,I would love to. Also ,could you link me to the comment you made concerning my proposal in the wiki? I can't see it . Would love to make changes before the final date. Also the project am proposing is under education and user related functionality. You can find it in the Outreachy website.Please let me know if you need further clarification.

**Comment by RuthNjeri** [comment]
Hey @Elukoye, the comment I made for the proposal for the wiki was posted in the Gitter chat room. I copied the same comment on your new proposal. Also, for the Outreachy proposal, you should focus on the entire project `education and user-related functionality` and not a subsection of it since an intern chosen will work on the entire project scope in the duration of the internship.

**Comment by jywarren** [comment]
Hi @Elukoye that is so great and helpful, the WSL2 stuff you shared. Maybe we can include it in #3840?

**Comment by jywarren** [comment]
Hi all, just a reminder (via Outreachy!)

> In order to be eligible to be selected as an Outreachy intern, each applicant must:

> 1. Fill out an initial application at https://www.outreachy.org/eligibility/
> 2. Record a contribution to your project on the Outreachy site.
> 3. Complete a final application for your project.

> The deadline for final applications is April 30, 2021 at 4pm UTC. Applicants will not be able to create a final application after the deadline. Applicants can edit their final application until the deadline.

> Applicants who submit a final application will be able to continue recording and editing their contributions to your project. They can record contributions until the intern announcement on May 17, 2021 at 4pm UTC. Applicants who have not submitted a final application will not be able to record or edit their contributions.


https://www.outreachy.org/outreachy-may-2021-internship-round/communities/public-lab/expand-and-refine-tagtopic-system-of-publiclaborg/contributions/

https://www.outreachy.org/outreachy-may-2021-internship-round/communities/public-lab/improve-education-related-usability-and-functional/contributions/

**Comment by cesswairimu** [comment]
Hi everyone :wave:  please checkout this week's check-in here https://github.com/publiclab/plots2/issues/9566
thanks to everyone who has already posted on the PublicLab website, the mentors will continue providing feedback on the proposals.
If anyone is having trouble posting, please feel free to reach out or ask any other questions you may be having. Thanks everyone

**Comment by Elukoye** [comment]
@cesswairimu,@jywarren, is there a way to retrieve a draft copy? I think I lost mine. I can see my draft history but cannot retrieve it.

**Comment by aliciapaz** [comment]
Hi @Elukoye 
If you click on "x entries" it will display the list of draft entries on that date and then you can click on the "revert" button to retrieve a particular draft. 
![image](https://user-images.githubusercontent.com/67963195/116265013-c0428180-a748-11eb-806c-467c6f8e4dbc.png)
I hope this helps :)

**Comment by jywarren** [comment]
Hi @Elukoye @aliciapaz is right - however if you've already published your draft, it may be this? https://publiclab.org/notes/lukoyedith/04-20-2021/gsoc-proposal-filter-out-spam-from-comment

**Comment by Elukoye** [comment]
@jywarren , the link you put isn't the one I was working on, I had started a new one. @aliciapaz , that brings me an empty form
please reference here https://www.loom.com/share/6071312f7a1341199187edf47917d861

**Comment by jywarren** [comment]
Ah ok @Elukoye i will look for the other

**Comment by Elukoye** [comment]
I clicked on the publish button but it was unresponsive, so I saved it as a draft and refreshed the page, it brought an empty form, When I tried to revert, it was rendering an empty form.

**Comment by jywarren** [comment]
Hm. I'm sorry it caused trouble, maybe we need to debug the draft saving function? Was it this one though? https://publiclab.org/notes/lukoyedith/04-25-2021/sample-draft

**Comment by Elukoye** [comment]
@jywarren, it's not the one 😢 . However, this is what I noticed, when I leave my research note untouched for a few hours in save as draft mode, the moment I refresh the page, my draft disappears. This is the second time am starting over 😄 . Maybe we can include a gem called Sisyphus gem that uses script tags to wrap around the input forms on the app. Actually, I have proposed this in my new research note proposal to tackle this problem.

**Comment by Elukoye** [comment]
@jywarren the title of my latest research note was:
 Improve education-related usability and functionality on PublicLab.org

**Comment by jywarren** [comment]
Hi @Elukoye if it's OK with you can we create a new issue for this and try to document a bit more of how this happened? I'm so sorry you've lost your text, and I want to see if we can recover it but also to make sure this doesn't happen again. Thank you for noting it!

**Comment by jywarren** [comment]
@Elukoye I made a new issue here to investigate more. Thank you again -- https://github.com/publiclab/plots2/issues/9569

**Comment by cesswairimu** [comment]
Hi all, here are some updates from Outreachy:

```
Summary of new deadlines
---

May 3 at 7pm UTC - final application deadline

May 7 at 4pm UTC - deadline for manually submitting final applications
for applicants who are sick with COVID-19, or are impacted by a family
member sick with COVID-19.

May 9 - contribution deadline


Final application deadline
----

The final application deadline is now extended to Monday, May 3 at 4pm
UTC. It is okay if that is a draft final application.
```
Thanks all

**Comment by Elukoye** [comment]
@jywarren, @RuthNjeri, @cesswairimu here is a link to my latest proposal, I would appreciate feedback from you and anyone else, thanks 🙏 .
https://publiclab.org/notes/lukoyedith/04-27-2021/sample-draft

**Comment by Elukoye** [comment]
@jywarren, about signing in with gitter, I don't think I can see recent messages. I posted something in the chat but it doesn't show.

**Comment by jywarren** [comment]
I'm sorry @Elukoye are you using https://gitter.im/publiclab/publiclab ? Can you try again there?

**Comment by RuthNjeri** [comment]
Hi @Elukoye, I have shared some feedback on your proposal, thanks for sharing.

**Comment by cesswairimu** [comment]
unpinning this to pin back weekly communication issue.

**Comment by cesswairimu** [comment]
Thank you everyone for applying with PublicLab. We had great proposals from all you and many great contributions from all of you we would have loved to take in more if we got more slots..For those who did not get selected, please know that we are extremely grateful for your work with us to date and that we welcome you to continue being part of this community. Thank you for understanding and we hope you’ll apply again :heart:

Congratulations @Manasa2850 and @TildaDares :tada: :tada:
