### ISSUE TITLE
Weekly Community Check-In #97 - GSoC and Outreachy applications are open

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#9389]
We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. 💯

##  GSoC and Outreachy applications are :tada: :tada: 

 Google Summer of Code and Outreachy applications officially opened yesterday. If you are an applicant to any of these programs, welcome to PublicLab :balloon: we are glad to have you :heart: .

**To Outreachy applicants:**
- Please say hi here and introduce yourself if you have any questions you can ask [here](https://github.com/publiclab/plots2/issues/9388)
- We encourage applicants to post a proposal on the PublicLab website too so as to can get feedback from fellow contributors and mentors, improve your proposal before you submit on the Outreachy website. [Here](https://publiclab.org/notes/cess/04-04-2021/call-for-proposals-outreachy-summer-2021) is the call for proposals

**To GsoC applicants:** 
- Please say hi and introduce yourself. If you have any questions you can ask [here](https://github.com/publiclab/plots2/issues/9283)
- Kindly submit your proposal on the PublicLab website, more details and a template for drafting the proposal [here](https://publiclab.org/notes/cess/03-24-2021/call-for-2021-gsoc-proposals)

## This week's focus Issues

These are issues that are of high priority and requests from our 
large community that use the software. 
 - https://github.com/publiclab/PublicLab.Editor/issues/701
 - https://github.com/publiclab/PublicLab.Editor/issues/683
 - Opening ftos for soc applicants

 We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these. We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance :smile: 

## Thank you note to focus issues contributors

🥇 🥇 🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇
 @jywarren, @RuthNjeri ,  @waridrox, @jcads, @17sushmita, @SidharthBansal 
🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇

## Next Check-in
If you would like to open the next weekly check-in please comment below..I am glad to guide you if its your first time or have any questions.

Thanks everyone for making PL awesome and have a great week ahead :balloon:

**Comment by anirudhprabhakaran3** [comment]
Hello! I would like to open the next weekly check-in, considering that it's been 5 days since this one.

**Comment by cesswairimu** [comment]
Fantastic @anirudhprabhakaran3 :tada:  There is a template at https://github.com/publiclab/plots2/issues/new?assignees=&labels=community+check-in&template=--weekly-check-in.md&title=Weekly+Community+Check-In+%23+-+Topic that you could use.. you could open the check-in ether today(Sunday) evening or tomorrow. Feel free to reach out if you have any questions. Thanks!

**Comment by anirudhprabhakaran3** [comment]
I see that the template has sections for a title, focus issues, and contributors. How do I get relevant information for those sections?  Also, I'll open the check-in today in the evening (13:30 GMT).

**Comment by cesswairimu** [comment]
You could choose any topic/theme you would like people to discuss..you could check out #9318 for some ideas from past themes.. as for focus issues and contributors you can leave as is on the template I will help update after you post. Thanks

**Comment by anirudhprabhakaran3** [comment]
@cesswairimu https://github.com/publiclab/plots2/issues/9444

**Comment by cesswairimu** [comment]
Thanks a bunch @anirudhprabhakaran3 
Moved to #9444  thanks all
