### ISSUE TITLE
Update comment count only after moderator approval

### ISSUE THREAD

**Issue by daemon1024** [publiclab/plots2#9397]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

The comment count on any note is updated before approvals from moderators.

> What did you expect to see that you didn't?

The comment count should only update when approved by mods.

### Please show us where to look

![image](https://user-images.githubusercontent.com/47106543/113055527-532ee100-91c8-11eb-8bc3-54e58ad80f04.png)
https://publiclab.org/notes/cess/03-24-2021/call-for-2021-gsoc-proposals#Proposals

![image](https://user-images.githubusercontent.com/47106543/113055562-5c1fb280-91c8-11eb-97fa-c0f40e841998.png)
https://publiclab.org/notes/barun1024/03-24-2021/gsoc-2021-proposal-geographic-features-refinement

### What's your PublicLab.org username?

barun1024

**Comment by reginaalyssa** [comment]
Hope it's okay if I take this on!
