### ISSUE TITLE
Display error for non-unique username as soon as it is entered during sign-up 

### ISSUE THREAD

**Issue by GayathriVenkatesh** [publiclab/plots2#9407]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

When a user signs up for the first time, it would be nice to display whether the username is unique or not, as he is typing the username.

> What did you expect to see that you didn't?

![Screenshot (50)](https://user-images.githubusercontent.com/32172764/113096827-919dbd80-9213-11eb-894f-cdeb8f48b9d6.png)

After entering all my details - username, email id and typing the password twice, the page threw an error saying the username has already been taken. So I had to type all my details again multiple times until the entered username was unique.

Since it is cumbersome to keep re-entering the same details, it would be a good idea to flag the error as soon as the username has been entered. This will ensure that the user enters a unique username before proceeding with the other details.

Something like this:

![email_taken png 2017-10-31 1509444735](https://user-images.githubusercontent.com/32172764/113096207-69618f00-9212-11eb-9e62-30a30343eb56.png)

### Please show us where to look

https://publiclab.org/register

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

gayathri_v

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

Chrome, Windows 10
****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by ampaire** [comment]
Can I spend the weekend working on this?

**Comment by ShivamJhaa** [comment]
@TildaDares , @Tlazypanda Is this issue relevant?

**Comment by KarishmaVanwari** [comment]
Can I work on this issue, if it needs to be implemented? @TildaDares

**Comment by TildaDares** [comment]
You can take this up @KarishmaVanwari

**Comment by KarishmaVanwari** [comment]
Hey @TildaDares, it seems that this issue has already been fixed, since I tried to signup with the username that already exists and it shows:
![image](https://user-images.githubusercontent.com/78212650/157615941-14271ae6-2811-4cd4-baae-639ed3c083a3.png)

Please confirm!

**Comment by TildaDares** [comment]
You are right @KarishmaVanwari. I think we can close this now. Thanks!
