### ISSUE TITLE
Sort the order of activities in an Activity Grid by Likes

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#941]
### What happened just before the problem occurred

The activity grid at https://publiclab.org/wiki/translation#Activities+for+people+who+want+to+translate
is not sorting by likes. As i write this issue, one of the three notes has 1 like, the others have 0 likes. Yet, at page load, the grid doesn't list the note with the 1 like above the notes with 0 likes. 

It is already possible to simply click the column header "Purpose" to sort the Activity Grid alphabetically / numerically. This functionality should be preserved while we adjust the default sorting to be based on likes.

### Relevant URLs

https://https://publiclab.org/wiki/translation

### PublicLab.org username

liz

**Comment by jywarren** [comment]
This would make a good help wanted issue; relevant lines of code are:

https://github.com/publiclab/plots2/blob/master/app/models/drupal_node.rb#L770

And especially: https://github.com/publiclab/plots2/blob/master/app/helpers/application_helper.rb#L74

Can you explain more of why it should sort that way, and tag this?

**Comment by ebarry** [comment]
The number of "likes" on activities is a proxy measure of how popular/accessible an activity is. The most "liked" activities would be great places for new people to start, and because of that should be featured close to the top of the grids that they are in. Read all about activities and why we're using these sortable grids to organize them here: https://publiclab.org/notes/liz/08-30-2016/check-out-these-activity-grids

Thanks!

**Comment by ebarry** [comment]
Hi @foggy1! Thank you again for your valuable contribution to Public Lab. I would like to invite you to join us in a video conference to say a few words about what you contributed and how your experience was. The event is https://publiclab.org/openhour, and it’s coming right up on November 7th, at 1pm EDT which is UTC/GMT -4. 

Please feel free to respond here, or else email liz@publiclab.org, stevie@publiclab.org, jeff@publiclab.org.

**Comment by foggy1** [comment]
@ebarry I'd be happy to join!
