### ISSUE TITLE
Retain gallery/list view state when we move from one filter to another in the questions page

### ISSUE THREAD

**Issue by Manasa2850** [publiclab/plots2#9412]
**Please describe the desired behavior.**
Currently, irrespective of whether we're in the gallery view or in the list view in https://publiclab.org/questions/ if we go to `Recently Asked`, `Recently Commented` etc it switches to gallery view. It would be good if the same state is retained when we click on one of the columns i.e if we are in list view in `Recently Asked` and then go to `Recently Commented`, list view should be retained there.

**Additional context (optional)**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43354059/113191959-cd6c6d80-927b-11eb-8a33-2a6ad3177464.gif)

**Comment by TildaDares** [comment]
@Manasa2850 I'd love to work on this.

**Comment by Manasa2850** [comment]
Hi @TildaDares. You can definitely start working on this once @jywarren or @cesswairimu approves this issue!

**Comment by cesswairimu** [comment]
hi, I agree @Manasa2850 that would be great, thanks for catching this. You can go ahead @TildaDares  we would love tour help
Thanks you both :tada:

**Comment by TildaDares** [comment]
@cesswairimu Can I use local storage to persist the button's state?
