### ISSUE TITLE
"Save" not working on /features

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#9416]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
As an Admin, I edited text in a Feature, then clicked Save. The page reloaded with a "This page does not exist" screen, see screenshot. I also tested clicking "Save" without editing, with the same result. 

<img width="998" alt="Screen Shot 2021-04-01 at 10 08 36 AM" src="https://user-images.githubusercontent.com/161439/113306835-7e055c00-92d2-11eb-8845-98919d05ded7.png">

> What did you expect to see that you didn't?
I expected to see my edits successfully saved. 

### Please show us where to look

https://publiclab.org/features/17211
https://publiclab.org/features/11796/
and for Jeff: https://publiclab.slack.com/archives/CV7KG8MFT/p1617198609007000

### What's your PublicLab.org username?

bhamster
liz

Thank you!

**Comment by daemon1024** [comment]
Noting some finding that may assist in solving this.

When we try to edit and save in local development environment, the route seems to throwing off an exception.

```No route matches [POST] "/features/<id>"```

It should be calling `update` features controllers. 
https://github.com/publiclab/plots2/blob/9e66b0f1a7c19733388d233308d2b090111bc627/app/views/features/edit.html.erb#L1
https://github.com/publiclab/plots2/blob/9e66b0f1a7c19733388d233308d2b090111bc627/app/controllers/features_controller.rb#L68 the update controller hasn't been updated for quite a while so not exactly sure what changed that is throwing off this exception now.

**Comment by jywarren** [comment]
Wow very much appreciated! I got drawn into an adjacent bug 😅

**Comment by jywarren** [comment]
I'll check the routes.rb file!

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/blame/main/config/routes.rb

**Comment by jywarren** [comment]
This line is 6 years old, so i doubt it's related! 

https://github.com/publiclab/plots2/blame/9e66b0f1a7c19733388d233308d2b090111bc627/app/views/features/edit.html.erb#L1

**Comment by jywarren** [comment]
I really don't see much in routes.rb...

**Comment by daemon1024** [comment]
I checked the the routes, there's no `POST` method for `features/:id`

**Comment by daemon1024** [comment]
https://stackoverflow.com/questions/19501374/rails-4-routingerror-no-route-matches-post This might be related

**Comment by jywarren** [comment]
indeed. i think it probably uses a more general matcher, or is implicit since it's a resource? 

https://github.com/publiclab/plots2/blob/9e66b0f1a7c19733388d233308d2b090111bc627/config/routes.rb#L23

**Comment by jywarren** [comment]
The broken feature was last edited `2 months ago` so i'm thinking there have only been a couple site republishes since then anyways! So strange!

**Comment by daemon1024** [comment]
I will look into if we had any changes in the `node` model, since the stackoverflow solution seems to be pointing towards there.

**Comment by jywarren** [comment]
Aha, i like your theory on the `form_for` code, i think that's probably it. See this change: https://github.com/publiclab/plots2/pull/8923

**Comment by jywarren** [comment]
I'll try reverting that change in local and checking the generated url of the form in HTML...

**Comment by jywarren** [comment]
OK, current form shows `<form action="/features/11796" accept-charset="UTF-8" method="post">`

let me see after reverting this form_for change...

**Comment by jywarren** [comment]
Hmm. Reverting `:node` to `@node` makes it `<form class="edit_drupal_node" id="edit_drupal_node" action="/features/44" accept-charset="UTF-8" method="post">`

looks pretty similar... let me inspect the whole form, maybe even try submitting it and inspecting the package sent...

**Comment by daemon1024** [comment]
```diff
-<%= form_for :node, :as => :drupal_node, :url => url do |f| %>
+<%= form_for @node, :as => :drupal_node, :url => url do |f| %>
```

This solved it :)

**Comment by daemon1024** [comment]
`@node` was changed to `:node` unknowingly i guess.

**Comment by daemon1024** [comment]
> Hmm. Reverting `:node` to `@node` makes it `<form class="edit_drupal_node" id="edit_drupal_node" action="/features/44" accept-charset="UTF-8" method="post">`
> 
> looks pretty similar... let me inspect the whole form, maybe even try submitting it and inspecting the package sent...

 Ohh I missed this.

**Comment by jywarren** [comment]
Agreed. I'm going to try triggering a validation error to see if the displayed messages still work, as that was the target of the fix.

**Comment by jywarren** [comment]
Looks ok!

![image](https://user-images.githubusercontent.com/24359/113735953-b63ddd80-96ca-11eb-9ff7-0f31d90a8971.png)

I guess maybe it was a mistaken or unrelated change?

I'll rush this into production but we should back it with an integration test. That could be a pretty good FTO!

**Comment by daemon1024** [comment]
🎉

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/commit/99e0157d58497fa17e59c59099e97d39d3965d17 and monitoring the tests before merging to stable and publishing!

**Comment by jywarren** [comment]
Thank you so much, @daemon1024 !!!
