### ISSUE TITLE
Add translations for editor/post.html.erb

### ISSUE THREAD

**Issue by Manasa2850** [publiclab/plots2#9425]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [config/locales/en.yml](https://github.com/publiclab/plots2/blob/main/config/locales/en.yml) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
  talk:
    show:
      welcome: "Talk page for <a href='%{url1}'>%{page}</a> | This page allows for
        synchronized editing by multiple people as you type. <a href='%{url2}'>Learn
        more</a>"
      try_direct_link: "If this page does not load properly, <a href='%{url1}'>try
        here</a>"
+ editor:
+   post:
+     welcome: "Here you can ask a question to the Public Lab community to help you in your environmental exploration. This is a great space to ask whether a method exists for identifying a possible pollutant, or ask about details of a specific technique for identifying a pollutant."
+     add_tags: "You can add more tags in the tags section below to further relate your question. You can also change the main tag of the question by renaming the part after"
+     q_and_a: "New to Public Lab? Take a minute to read the Q &amp; A wiki before posting your question"
+     learn_more: "Learn more &raquo;"
+     research_note: "At Public Lab, we all collaborate to invent and improve open source environmental science tools. <b>Research notes</b> are the primary way we share what we learn, ask questions, pose challenges, and critique one another's work."
+     photo: "photos of what you've made"
+     troubleshooting: "requests for troubleshooting"
+     projects: "proposals for new projects"
+     events: "announcements of events"
+     reports: "reports from a field test or meetup"
+     video: "Watch a 30 second video on posting research notes &raquo;"
  home_controller:
    science_community: "a DIY environmental science community"
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by omgupta1608** [comment]
Can I work on this ? I am a first timer.

**Comment by Manasa2850** [comment]
Sure, you can work on this!

**Comment by omgupta1608** [comment]
#9426 
I did the required changes and I have opened a Pull Request.

**Comment by omgupta1608** [comment]
#9426
