### ISSUE TITLE
Add translations for map/index.html.erb

### ISSUE THREAD

**Issue by Manasa2850** [publiclab/plots2#9428]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [config/locales/en.yml](https://github.com/publiclab/plots2/blob/main/config/locales/en.yml) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
 like:
    index:
      recent_likes: "Recent Likes"
      user: "User"
      liked: "Liked"
      action: "Action"
+ map:
+   index:
+     current_view: "Current view based on your shared location. Click <a href='/profile'>here</a> to adjust."
+     share: "Share your own location on <a href='/profile'>your profile</a>."
+     privacy: "Learn about <a href='https://publiclab.org/wiki/location-privacy'>privacy</a>"
+     archive: |
+       <h3><i style="color:#aaa;" class="fa fa-hdd"></i> A grassroots data archive</h3>
+       <p>This archive represents the collective work of our community to provide an alternative source for aerial imagery, and to highlight issues of environmental and social concern with Do-It-Yourself tools. The archive provides:</p>
+       <ul>
+         <li>A permanent, backed up archive</li>
+         <li>A place to advocate around your data</li>
+         <li>A space to discuss and understand the maps</li>
+       </ul>
+       <hr />
+       <h3><i style="color:#aaa;" class="fa fa-globe"></i> How to contribute</h3>
+       <p>Most of the maps in this archive were made in <a href="//mapknitter.org">MapKnitter</a>, a free and open source tool created by Public Lab contributors to turn aerial photos into maps.</p>
+       <p>To add your open source map to the archive, contact <a href="mailto:staff@<%= request.host %>">staff@<%= request.host %></a> and be prepared to provide some background and to tell the story of your map. Creative Commons and Public Domain maps are <a href="/licenses">both accepted</a>.</p>
  tag:
    blog:
      the_public_lab: "The Public Lab"
      blog: "Blog"
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by amiyahfrierson** [comment]
I'd like to claim this one, if you please.

**Comment by siddhantdixit** [comment]
I have Updated config/locales/en.yml file. Waiting for Review :)

**Comment by amiyahfrierson** [comment]
Oh, thought we had to claim these first. 😅

**Comment by siddhantdixit** [comment]
I am new to GitHub! I wanna contribute :)

**Comment by cesswairimu** [comment]
Thanks a lot @Manasa2850  for the FTOs.. feel free to be mentioning them at #9083 for any folks waiting for first-timer issues,
Thanks again for all the great work you are doing :heart: . Thanks

**Comment by cesswairimu** [comment]
Hi @amiyahfrierson hi @siddhantdixit 
@amanda-ariyaratne yeah you are right,  we encourage one to let others know they are working on an issue, so nobody else picks it up, @siddhantdixit if you read the description of the issue we have the steps explained there...kindly let people know you are working on an issue before and if someone has expressed interest ask them if they are still working on it before you get started. I will review the PR @siddhantdixit and thanks for working on it... @amiyahfrierson do let me know if you are still looking for an issue and I will add your name at #9083 and we will ping you when one comes along.
Thanks you both and welcome to PublicLab

**Comment by cesswairimu** [comment]
@siddhantdixit  I just say you deleted the branch your branch and fork, are you planning to reopen the pull request?  Thanks

**Comment by siddhantdixit** [comment]
@cesswairimu No! :)  Thanks!

**Comment by amiyahfrierson** [comment]
@cesswairimu I'm still looking! I'd love to be added.

**Comment by cesswairimu** [comment]
thanks @siddhantdixit,
@amiyahfrierson you can go ahead and work on this one, assigning this to you . Thanks
