### ISSUE TITLE
Weekly Community Check-In #98 - GSoC and Outreachy applications still open!

### ISSUE THREAD

**Issue by anirudhprabhakaran3** [publiclab/plots2#9444]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform that helps a newcomer to become a leader of tomorrow. 💯

## Working on GSoC and Outreachy applications

This week share an exciting moment you have had on PublicLab. I'll go first.

There have been many new contributors working on various issues on PublicLab. I also worked on an issue and my code has been merged! The feeling is indescribable. Looking forward to seeing and helping many more contributors and many more contributions!

What about you? You can share whatever you want. Could be a feature that you worked on that got you super excited, an interaction you had with another collaborator, an open call that was very exciting for you, an issue that you raised that got you excited, a eureka moment you had when working on an issue, anything really.

## This week's focus Issues

These are issues that are of high priority and requests from our large community that use the software. 

We have had an increment of bugs show up in the past two weeks. This week lets try to fix most of these. You can find them here.
https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3Abug
We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note to focus issues contributors

🥇 🥇 🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇
 @jywarren, @RuthNjeri ,  @noi5e , @17sushmita, @Manasa2850
🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇🥇 🥇

## Next Check-in
If you would like to open the next check-in, leave a comment below. We are happy to help if it's your first time

**Thank you, everyone, for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by cesswairimu** [comment]
Thanks @anirudhprabhakaran3  :tada:

**Comment by Elukoye** [comment]
Hello, I would love to participate in the next  weekly community check-in :)
@cesswairimu, @jywarren , @RuthNjeri

**Comment by RuthNjeri** [comment]
Thanks for opening this up @anirudhprabhakaran3 🎉 

An exciting moment I have had on Public Lab is how the new comers like yourself are taking initiative by creating weekly check-ins, reviewing other PRs, and welcoming new contributors. It builds on the strength of the Public Lab community and our values. ❤️ 

@Elukoye Thanks! 🎉  I have added your name to the Weekly Community Communication https://github.com/publiclab/plots2/issues/5627 list for the next one.

**Comment by jywarren** [comment]
Thanks @anirudhprabhakaran3 - much appreciated! 

For me, it's always exciting to see new people show up and begin to find a place not only in making contributions, but in helping out others -- i love it when someone relatively new can step into the role of a mentor for someone else who's also new! It really makes sense, as the recent experience of learning a ton of new stuff helps one to empathize and understand what a challenge it is for someone who's about to take those steps. 

This includes both @anirudhprabhakaran3 and @Elukoye for volunteering to open our check-ins!!

🎉 🎉 🎉 🎉

**Comment by cesswairimu** [comment]
hI @Elukoye, please open the check-in anytime today, we have a template [here](https://github.com/publiclab/plots2/issues/new?assignees=&labels=community+check-in&template=--weekly-check-in.md&title=Weekly+Community+Check-In+%23+-+Topic) that you could use, also feel free to ping @RuthNjeri or myself if you need  help. Thanks

**Comment by Elukoye** [comment]
Thanks , I will do that.

**Comment by cesswairimu** [comment]
MOved to https://github.com/publiclab/plots2/issues/9496, thanks all
