### ISSUE TITLE
Profile photo preview on dashboard pane not showing up on certain pages

### ISSUE THREAD

**Issue by waridrox** [publiclab/plots2#9450]
### Please describe the problem (or idea)
Profile photo preview on the dashboard menu is not showing up on certain webpages.

### Please show us where to look
https://publiclab.org/

https://user-images.githubusercontent.com/58583793/113550644-07899680-9611-11eb-9ed4-f9e615877d34.mp4

### What's your PublicLab.org username?
waridrox

### Browser, version, and operating system
Chrome v89

**Comment by Elukoye** [comment]
Hi 👋 @waridrox and @cesswairimu ,can I try work on this ?

**Comment by waridrox** [comment]
Sure @Elukoye 😄, go for it! 🚀

**Comment by Elukoye** [comment]
Ok 👌 am on it

**Comment by Elukoye** [comment]
![Uploading Screenshot_20210405-123610.png…]()

**Comment by Elukoye** [comment]
@waridrox ,just to be clear about the issue ,what I noticed is some header images on some posts aren't loading,is that what you meant by profile preview not showing up on certain web pages ?

**Comment by waridrox** [comment]
I am referring to the profile photo image next to the dashboard icon 😅.

<img width="137" alt="Screenshot 2021-04-05 at 3 30 03 PM" src="https://user-images.githubusercontent.com/58583793/113562485-ccdd2980-9623-11eb-8e1f-197f86617fe1.png">

**Comment by Elukoye** [comment]
Oh yea , I have seen it , the video wasn't loading previously :). Thanks for the clarification.

**Comment by Elukoye** [comment]
Hi @waridrox,  @jywarren, @RuthNjeri,
I need a little help here, I was wondering if the navbar component persists through the application.html.erb file. I am trying to locate the profile image in the navbar. And understand the project better

**Comment by daemon1024** [comment]
Hey @Elukoye ,
This might be the component you want to dig in :)
https://github.com/publiclab/plots2/blob/bd0bc112112a1d92f4181fe77deeca7cfdb8d00d/app/views/layouts/_header.html.erb#L112

**Comment by jywarren** [comment]
Wow i also noticed that missing icon. Using the Chrome developer tools we should be able to see if there is a request failing? Thanks for catching this and offering to work on it, both of you!

**Comment by jywarren** [comment]
So strange -- yeah you can right click it too to open the image itself:

![image](https://user-images.githubusercontent.com/24359/115435147-8832c000-a1d7-11eb-8ac8-4f564e656abf.png)

**Comment by jywarren** [comment]
Actually on waiting a moment, mine went from grey to having a picture again. @waridrox are you sure it persists and is not just a very slow loading image?

Thank you!!!

**Comment by Elukoye** [comment]
@daemon1024 thanks ,will look into it .😃

**Comment by Elukoye** [comment]
@jywarren I agree with you ,I did notice that the image load after some time.Could it be a  lag while the page is loading?

**Comment by waridrox** [comment]
Hi all, I believe the profile icon loading problem is still persistent even after the webpage fully loads.


https://user-images.githubusercontent.com/58583793/115789782-4ecea000-a3e3-11eb-9e13-7f7ffb639344.mp4


On further observation, the profile image after clicking on `Share your work button` is not requested to begin with, so I think it defaults to the grey img:

<img width="1277" alt="no-reference" src="https://user-images.githubusercontent.com/58583793/115789480-d667df00-a3e2-11eb-9f86-cc48464a3ef1.png">

On the other hand, the img that gets loaded on the dashboard is requested from the stored google storage:
<img width="1271" alt="pic-reference" src="https://user-images.githubusercontent.com/58583793/115789683-25157900-a3e3-11eb-86af-162f59f49f14.png">

**Comment by Elukoye** [comment]
thanks @waridrox for the analysis, will sure help 😄

**Comment by KarishmaVanwari** [comment]
Can I take up this issue? @waridrox @jywarren

**Comment by jywarren** [comment]
Sure, we'd love the help! Although we aren't quite sure still under what circumstances it's happening. @NARUDESIGNS you saw this happen recently too - do you know how to get it to happen, so we can figure out how to resolve it? Thank you!

**Comment by jywarren** [comment]
Ah, i can see this happen in production on https://publiclab.org/post - so that's a clue!

**Comment by NARUDESIGNS** [comment]
> Sure, we'd love the help! Although we aren't quite sure still under what circumstances it's happening. @NARUDESIGNS you saw this happen recently too - do you know how to get it to happen, so we can figure out how to resolve it? Thank you!

@jywarren yes, when you log in to https://publiclab.org/dashboard and also https://publiclab.org/post
This is a link to where I pointed it out - https://github.com/publiclab/plots2/issues/10481

**Comment by sakshi-2412** [comment]
@jywarren I think the problem is related with <%= image_tag(...)%>, replacing it with <img .../> solves this issue which is strange since both are using the same source url 🤔

**Comment by sakshi-2412** [comment]
@jywarren @TildaDares can I work on this issue if no one else is?

**Comment by TildaDares** [comment]
Hi @sakshi-2412, sure you can take this up.
