### ISSUE TITLE
rake:db setup fails because of missing dependency

### ISSUE THREAD

**Issue by eightballocto** [publiclab/plots2#9455]
As stated in the title, `rake:db` aborts due to a supposed missing dependency, "'mysql2' Active Record adapter".

I've been able to "fix" this by adding the missing dependency, but another error appears where it demands a "manifest" in `app/assets/config/manifest.js`.

I don't know if there's something I'm missing, or if there's a caveat not listed in the README, but I thought it better to raise awareness to this issue—that is, if anyone else is experiencing this.

**Comment by anirudhprabhakaran3** [comment]
Is this on the development or deployment server?

**Comment by eightballocto** [comment]
> Is this on the development or deployment server?

I intended this to be on the development server, but I can't really say for certain (I'm still new to this project, I was following the steps to set up the project)

**Comment by anirudhprabhakaran3** [comment]
Aah. Did you run something like `cp config/database.yml.example config/database.yml` ? I suggest you try running `cp config/database.yml.sqlite.example config/database.yml`

**Comment by eightballocto** [comment]
That *did* work, but I think that's because it applies to SQLite. In this instance, it's regarding the `mysql2` gem. I noticed that in the `Gemfile` it notes the following:
```ruby
# mysql 0.4.3+ causes a version mismatch, apparently, and demands 'activerecord-mysql2-adapater
```
Curiously, the version specified for `mysql2` in the `Gemfile` is `>= 0.4.4`

**Comment by anirudhprabhakaran3** [comment]
That's because when you're running `bundle install`, it is ignoring the `mysql` and `production` gems. That's why the README suggests that we use the sqlite version. 

However, said that one might be interested in running the MySQL version. In that case, I don't know how to un-ignore the gems😅

**Comment by eightballocto** [comment]
Okay, that makes sense. I was able to work around this by invoking `bundle config set --local 'mysql production'`

In this process, I discovered another issue, `ActiveRecord::NoDatabaseError: Unknown database 'publiclab_dev'`

I get the feeling that this might have something to do with the script generating the database. I'll have to investigate more.

**Comment by eightballocto** [comment]
Closing as this is not a bug but rather operator error.
