### ISSUE TITLE
Automated redeployment is interrupted 

### ISSUE THREAD

**Issue by icarito** [publiclab/plots2#9470]
With messages;

```
    conflict  config/webpacker.yml                                                                                            
Overwrite /app/config/webpacker.yml? (enter "h" for help) [Ynaqdhm] Y                                                          
Copying babel.config.js to app root directory                                                                        [273/1999]
    conflict  babel.config.js                                                                                                  
Overwrite /app/babel.config.js? (enter "h" for help) [Ynaqdhm]             
```
This is interrupting deployment to production. We need to figure out how to avoid this prompt.

**Comment by daemon1024** [comment]
The prompt can be bypassed with piping appropriate input beforehand.

```sh
echo "a" | rails webpacker:install && rails webpacker:install:react && rails generate react:install
```

can replace with any other appropriate option `n`/`y` . . .

**Comment by jywarren** [comment]
We're looking at whether this line was required only once on our production container, but we are mistakenly running it every time?

https://github.com/publiclab/plots2/blob/84abd32524da5e478c328e11be93b39ab5686ff3/Makefile#L10

Followup in #9502 

Closing this one!
