### ISSUE TITLE
Set CSS Margins and Paddings to the landing page sections.

### ISSUE THREAD

**Issue by Elukoye** [publiclab/plots2#9474]
When in the mobile view, some of the landing page elements have no padding or alignment.

**Please describe the desired behaviour.**
When in mobile view the UI elements should have equal margin and padding to create alignment, symmetry, order and visual appeal. 
**Describe the solution you'd like.**
Set the CSS margin and padding proper padding of the elements to be equal especially in the Community Projects section. Let the content within align. Let the sections be properly positioned to create symmetry, order and visual appeal for mobile users.

**Additional context (optional)**
 [Link to the landing page](https://publiclab.org/) 
 [Link to video showing the problem](https://www.loom.com/share/9c902463380949d98616583251c2709d)

**Comment by eightballocto** [comment]
Replacing line 72 in `home.html.erb` with either `margin: auto;` or removing the rule altogether seems to remediate this visual issue. It should be noted that this is noticeable even when viewing on a desktop too (white space on the *right* area)

**Comment by Elukoye** [comment]
Is anyone willing to work on this issue ?

**Comment by eightballocto** [comment]
I'll work on it, it should be a pretty simple fix.

**Comment by Elukoye** [comment]
@eightballocto awesome,all yours ,🚀👍

**Comment by eightballocto** [comment]
Will work on it as soon as #9483 is merged
