### ISSUE TITLE
incorrect "question:generalspectrometer" tag gets added to questions from somewhere

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#949]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled.

****

### What happened just before the problem occurred

This person posted a question: https://publiclab.org/questions/chuynh451/11-01-2016/intensity-for-spectra-too-low

But it was originally tagged with `question:generalspectrometer` -- it should've been `question:spectrometer` or `question:general`, so there must be an error in the input form somewhere. 

Indeed this page shows that tag when you click the `Ask a question` button: https://publiclab.org/wiki/spectrometer -- the link ends up being:

https://publiclab.org/post?template=question&tags=question:generalspectrometer

The template code for that is here: https://github.com/publiclab/plots2/blob/master/app/views/sidebar/_related.html.erb#L8

and it's pretty tangled; could use simplification or better formatting, maybe breaking it up onto multiple lines. But the key section is:

`
href="/post<%= '?template=question&tags=question:general'+(@tagnames.uniq.delete_if{|x| x.match(":") }).join(',') if @tagnames %>
`

The simplest fix would be to just add a comma after `general` -- as that's being concatenated to the tag name from `@tagnames.uniq`.

**Comment by ajessee** [comment]
@jnaftali and I would like to take a crack at this. We will open two pull requests, one with the simple solution of adding a comma, and another with a solution that we think might work.

**Comment by jywarren** [comment]
We'd love your help on this and are happy to offer any assistance you might need. Thanks a lot!

Just curious -- we're trying to improve our outreach to new contributors -- how did you happen to hear about us?

**Comment by jywarren** [comment]
Fixed in #969; please see here for another challenge if you're looking for one! 

https://github.com/publiclab/plots2/labels/help-wanted

Thanks!!
