### ISSUE TITLE
Translation string replacement errors

### ISSUE THREAD

**Issue by imajit** [publiclab/plots2#9494]
![Screenshot from 2021-04-10 23-18-15](https://user-images.githubusercontent.com/38528640/114317377-6b3a2500-9b25-11eb-8057-ed92c252b1c3.png)
![Screenshot from 2021-04-10 23-17-59](https://user-images.githubusercontent.com/38528640/114317378-6c6b5200-9b25-11eb-9b15-c3791094876f.png)
This issue is  similar to #7798

**Comment by cesswairimu** [comment]
Closing this, Fixed in https://github.com/publiclab/plots2/issues/9494. thanks
