### ISSUE TITLE
Weekly Community Check-In #99

### ISSUE THREAD

**Issue by Elukoye** [publiclab/plots2#9496]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## This week's focus Issues

These are issues that are of high priority and requests from our
large community that use the software. 
https://github.com/publiclab/plots2/labels/bug

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks to everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by TildaDares** [comment]
Good job @Elukoye 🎉🎉🎉🎉🎉🎉
I'd like to open the next check-in

**Comment by jywarren** [comment]
@TildaDares that would be wonderful! Have you seen the guidance Cess linked to? we can add you to the listing issue too. Thanks!!!

**Comment by ebarry** [comment]
Great check-in! A note about next week's check-in, it's going be #100, which is kind of a nice number, and i think we can celebrate this on Public Lab social media accounts. What are cool things to say on social media about our community having reached its #100th checkin?

**Comment by divyabaid16** [comment]
Hey everyone!

Great check-in @Elukoye 
I am one of the mentors who will be mentoring GSoC students so do reach out to me for any help.
Really excited to work with all of you again. 💯 

Cheers,
Divya

**Comment by Elukoye** [comment]
Thank you @divyabaid16

**Comment by RuthNjeri** [comment]
Hi Everyone!

Thanks for opening this @Elukoye 

@TildaDares, I have added your name to the list(#5627) for the next check-in, please have a look at some Checkin ideas here that you could use #9480

@ebarry that sounds like a great idea...I was thinking since 100  in binary is 4, we could celebrate the top 4 weekly check-in contributors?

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/9526. Thanks everyone :heart:
