### ISSUE TITLE
Inconsistent footer style

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#9497]
### Please describe the problem (or idea)

In https://publiclab.org/ the footer links have a black text color but in other pages like https://publiclab.org/people the footer links have a text color of blue.
> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

[Home page](https://publiclab.org/)

![image](https://user-images.githubusercontent.com/63427719/114422170-f0691c80-9bad-11eb-94f1-fb7f1294d68e.png)

Other pages

![image](https://user-images.githubusercontent.com/63427719/114422224-fbbc4800-9bad-11eb-906b-e2dcaf6772bf.png)

### Please show us where to look

https://publiclab.org/

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by TildaDares** [comment]
@RuthNjeri how do I reproduce this locally since the footer is not displayed in the local env.

**Comment by RuthNjeri** [comment]
@TildaDares that's correct, the footer uses a feature tag. Maybe you could perform an inspect element on the different pages on the live site and see what is different about the tags used? You can have a look at the different feature tags displayed here https://publiclab.org/features

This is the one for the footer https://publiclab.org/features/13824

**Comment by Priyaraj17** [comment]
Is anyone working on it?

**Comment by TildaDares** [comment]
@Priyaraj17 The code for the footer is not in the plots2 repo. You can try it if you want though.

**Comment by Priyaraj17** [comment]
> @Priyaraj17 The code for the footer is not in the plots2 repo. You can try it if you want though.

Sure. I can try it using the dev tools.

**Comment by RuthNjeri** [comment]
Hi, @TildaDares and @Priyaraj17 should we close this issue? Since the code that needs to be updated is on the public lab features list https://publiclab.org/features and not on the repo?

**Comment by TildaDares** [comment]
@RuthNjeri I'll close it.

**Comment by Priyaraj17** [comment]
> Hi, @TildaDares and @Priyaraj17 should we close this issue? Since the code that needs to be updated is on the public lab features list https://publiclab.org/features and not on the repo?

Sure. No problem.
