### ISSUE TITLE
Standardize presentation of "no results" messages on tag page tabs

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#9510]
# Tag pages are great
# Tag pages can benefit from greater standardization 😄 

When a tag is clicked from a piece of content, the person is brought to the tag page. This is good. 

In the gif below, observe the following non-optimized situations: 

- the tag page loads on the Research Notes tab, however, IF there are no Research Notes, then the display is "No results found; try searching for 'effect-based-test': Search for "effect-based-test" .  In this user journey, this is rather confusing because the person was *just* reading `effect-based-test` content immediately before arriving on this page, although it was a Wiki vs a Research Note, which many will not understand upon first glance. In general, a person may not instantly understand the tab layout of the tag page, so the "no result" messages should be edited to instead encourage the person to "look at each tab to see where content might exist or else search" -- this suggested text needs copyediting :)

- Observe that the Questions tab also returns no results, but here we are presented with no text but instead an empty pagination device. Ideally, this would be consistent with how "no results" are shown on other tabs with the encouraging text suggesting people look at all the tabs to see where results might be. 

- The wiki tab presents properly-- hooray!!! 🎉  🎉 🎉

- the Contributors tab has an actual error. Although the count on the tab correctly shows "1", in tab itself displays "no result" text: "No contributors for that tag; try searching for 'effect-based-test':" Secondly, in terms of standardization, the text is almost like the Research Notes Tab "no results" display except after the colon the actual link to go "Search" seems to have been left out, another inconsistency. This tab needs both a bug fix and a standardization. 

![standardize-results-notice](https://user-images.githubusercontent.com/161439/114895934-e3cb0b00-9ddd-11eb-9b83-a7a5f484cb93.gif)

**Comment by TildaDares** [comment]
@ebarry I'd love to work on this.

**Comment by ebarry** [comment]
Thank you @TildaDares ! Would you like to choose just one specific part of this to begin with? Please write back with what you'd like to break off to start with. Are there any questions i can answer?

**Comment by TildaDares** [comment]
@ebarry I'll start with the first one. For the no results text I'm thinking 'No results. Have you checked the other tabs? or try searching:'.

**Comment by ebarry** [comment]
This is exactly the kind of improvement that would really help! Thanks @TildaDares :)
Building on your suggestion, how about adding a greeting, and then inviting them to look at other tabs? For instance:

>Hi! No research notes have this tag, try checking the Questions or Wiki tabs on this page. Or try searching:__(_active search link_)_

I'm sure this can be improved, please write back with more edit ideas! 
CC @bhamster07 to also give wording suggestions.

**Comment by bhamster07** [comment]
Thanks @TildaDares! Also wondering if a small emoji might help make the message friendlier? Building off your and @ebarry's ideas now, maybe something like: 

> Hi! No research notes have this tag 🤷, try checking the Questions or Wiki tabs on this page. Or try searching:__(active search link)_

**Comment by TildaDares** [comment]
@bhamster07 @ebarry Your suggestions definitely add more warmth. I'll start working on it.

**Comment by jywarren** [comment]
Hi all, thanks and love the brainstorming happening here. I'm just marking this with labels to show it can be broken out into multiple issues (or pull requests) and also that discussion on the exact text for each tab is still ongoing. Maybe we should think about presenting the texts like this:

1. **Research notes:** `Hi! No Research Notes have this tag 🤷, try checking the Questions or Wiki tabs on this page. Or try searching:__(active search link)_`
2. **Questions:** `Hi! No Questions have this tag 🤷, try checking the Research Notes or Wiki tabs on this page. Or try searching:__(active search link)_`
3. **Wikis:** `Hi! No Wikis have this tag 🤷, try checking the Research Notes or Questions tabs on this page. Or try searching:__(active search link)_`

is this OK for all three options to be standardized?

I'm also adding the `add-code-links` label so we can work on linking to each code file where such changes would be made. That'll help whoever wants to make the changes. 

Once we agree on the exact texts for each, we can mark this as an `fto-candidate` so multiple issues can be made for newcomers from it. It's a pretty ideal one for that!

**Comment by ebarry** [comment]
These texts look perfect to me, exactly how i was hoping we could standardize, and i see @bhamster07 gave a 👍 as well, so these texts are good to go!

**Comment by TildaDares** [comment]
@jywarren @ebarry I think the issue with the count error in the contributors tab is because of https://github.com/publiclab/plots2/blob/9b60ef6f719c5150e32155475314d51b06c114e7/app/models/tag.rb#L348-L354
That method is used to count the number of notes which excludes wikis https://github.com/publiclab/plots2/blob/9b60ef6f719c5150e32155475314d51b06c114e7/app/controllers/tag_controller.rb#L450
 Is it possible to  replace `@note_count` with `@users` in https://github.com/publiclab/plots2/blob/9b60ef6f719c5150e32155475314d51b06c114e7/app/views/tag/_contributors.html.erb#L30-L37

**Comment by jywarren** [comment]
Just noting that the "no results" message standardization is DONE. Great work everyone!

Last thing is to look into this odd contributor count. But I'm going to close this as the main issue is resolved. 🎉

**Comment by jywarren** [comment]
The two queries are:

https://github.com/publiclab/plots2/blob/3a05ae2d547c71d5a7d173741586397947fcbc00/app/controllers/tag_controller.rb#L150

vs 

https://github.com/publiclab/plots2/blob/3a05ae2d547c71d5a7d173741586397947fcbc00/app/controllers/tag_controller.rb#L155

but this should be the same???

https://github.com/publiclab/plots2/blob/b03d3915b02802e50e353e2b695bd4b945f2d166/app/models/tag.rb#L80-L83

**Comment by jywarren** [comment]
https://publiclab.org/tag/effect-based-test/author/bhamster also nothing!

**Comment by jywarren** [comment]
got it. Fix in https://github.com/publiclab/plots2/pull/9643!!

**Comment by ebarry** [comment]
awesome! can't wait to see this go live
--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net
