### ISSUE TITLE
Add table of contents under an icon for wiki/Markdown pages, like GitHub does now!

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#9512]
![image](https://user-images.githubusercontent.com/24359/114939796-f4e04000-9e0e-11eb-9d03-c2d098c12197.png)

We could put it in the row of icons under the title on wiki pages (like [this one](https://publiclab.org/wiki/software-outreach)):

![image](https://user-images.githubusercontent.com/24359/114939941-1b9e7680-9e0f-11eb-96bd-21b0e82a191f.png)

We could use the "list" icon here:

https://fontawesome.com/v4.7.0/icon/list-ul

To actually generate the table of contents, we could use a library, preferably on the client side in JavaScript, something like:

* https://github.com/jonschlinkert/markdown-toc
* there are lots of options to sort through to find a good match: https://github.com/search?q=table%20of%20contents

**Comment by jcads** [comment]
Hi @jywarren, can I pick this up?

**Comment by RuthNjeri** [comment]
@jcads, thanks for volunteering. I think you can go ahead and begin working on it.

**Comment by DR-FREKE** [comment]
@RuthNjeri @jcads  Is this done or is it still up for grabs?

**Comment by RuthNjeri** [comment]
Hi @DR-FREKE thanks for reaching out, I think you can pick it up, I do not see a PR linked to this issue if @jcads has been working on it...plus it has been 13 days since the issue was assigned. Please go ahead and work on it.
