### ISSUE TITLE
Remove datepicker if a page already has a date tag

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#9517]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file `app/views/notes/show.html.erb` in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -91,7 +91,11 @@
       current_user.id == @node.id || current_user.is_coauthor?(@node) ) && 
       @node.has_tag('event') %>
   <hr/>
-  <p>This looks like an event.     <span><button id="date-toggle" class="btn-outline-secondary btn-sm" data-toggle="tooltip" data-placement="right" title="Add Date"><i class="fa fa-calendar" aria-hidden="true"></i></button></span></p>
+  <p>This looks like an event.  
+    <% unless @node.has_power_tag('date') %>
+      <span><button id="date-toggle" class="btn-outline-secondary btn-sm" data-toggle="tooltip" data-placement="right" title="Add Date"><i class="fa fa-calendar" aria-hidden="true"></i></button></span>
+    <% end %>
+  </p>
   <div id="event-datepicker">
     <input type="text" class="datepicker" aria-describedby="DatePickerGuide"/>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by TildaDares** [comment]
@cesswairimu

**Comment by VarunAroraCode** [comment]
Hi, I'm working on an open source class project and would like to contribute! Can I be assigned this issue?

**Comment by TildaDares** [comment]
@VarunAroraCode A reviewer has to give their okay before you start working on this. @cesswairimu Is this FTO okay?

**Comment by RuthNjeri** [comment]
@TildaDares, can you share an image showing what happens now and what happens after the changes suggested in the issue?

**Comment by TildaDares** [comment]
Before
![image](https://user-images.githubusercontent.com/63427719/115158591-d5534c80-a086-11eb-9cef-32dfc3d04114.png)

After
![image](https://user-images.githubusercontent.com/63427719/115158600-e1d7a500-a086-11eb-9e3e-55b4646396b6.png)

@RuthNjeri

**Comment by VarunAroraCode** [comment]
@TildaDares Any idea when that would be possible? I'd love to finish this up by the end of the day

**Comment by TildaDares** [comment]
@VarunAroraCode Sorry, this isn't up to me.

**Comment by VarunAroraCode** [comment]
@TildaDares I understand. Thanks for tagging who is!

**Comment by jywarren** [comment]
This looks great! Let's go for it!!! (i'm a reviewer ❤️ )

**Comment by DR-FREKE** [comment]
can I also be a contributor on this? @VarunAroraCode @jywarren @TildaDares @cesswairimu . Thank you

**Comment by TildaDares** [comment]
@DR-FREKE Only one person can work an issue but if @VarunAroraCode is no longer working on it then you can take it up.

**Comment by DR-FREKE** [comment]
@TildaDares ok but how do I know that?

**Comment by TildaDares** [comment]
@DR-FREKE When I see a `first-good-issue` I'll let you know.

**Comment by cesswairimu** [comment]
@DR-FREKE also adding your name here #9083 . Thanks everyone

**Comment by Manasa2850** [comment]
@cesswairimu I've updated the issue number in #9530. I think it can be merged.
Thanks everyone!

**Comment by cesswairimu** [comment]
Thanks @Manasa2850 🎉
