### ISSUE TITLE
Weekly Community Check-In #100 - 🎉 100th Check-in 🎉

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#9526]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## 100th weekly community check-in

It’s an honour to be the one to mark Public Lab’s 100th weekly community check-in 🥳🥳🥳. When I first started contributing at Public Lab it felt intimidating. But then seeing how welcoming and understanding everyone here at Public Lab was I felt a lot more confident. So on this 100th weekly check-in I’d like to thank 🏅🏅🏅🏅 @jywarren @cesswairimu @RuthNjeri and so many other contributors🏅🏅🏅🏅 who have made this GSOC and Outreachy contribution period seamless for new contributors like me. I’m happy to be a part of a community filled with inspiring people who dedicate their time and effort to creating a welcoming and inclusive environment. 
So to mark this check-in please tell us why you’re happy to be a part of this amazing community and add the 💯 emoji to your comments. Thank you @ebarry for the wonderful idea of using this emoji 💯.

Here's to more weekly community check-ins 🥂🥂🥂🥂🥂🥂

## This week's focus Issues

These are issues that are of high priority and requests from our
large community that use the software. 

https://github.com/publiclab/plots2/labels/high-priority

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note to focus issues contributors

🏅🏅🏅🏅🏅🏅🏅 @jywarren @cesswairimu @RuthNjeri @noi5e @waridrox @eightballocto @elukoye 🏅🏅🏅🏅🏅🏅🏅

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by cesswairimu** [comment]
This is beautiful, thanks @TildaDares  :tada:

**Comment by ebarry** [comment]
Here's the tweet celebrating our 100th checkin! Thanks to all: https://twitter.com/PublicLab/status/1384157310344331268

**Comment by daemon1024** [comment]
🥳🥳🥳🥳🥳🥳🥳🥳

**Comment by Manasa2850** [comment]
Amazing @TildaDares !! :partying_face::tada:

**Comment by 17sushmita** [comment]
Celebrations 🥳🥳💯💯💯💯💯

**Comment by RuthNjeri** [comment]
Thanks @TildaDares...to 100 more 🏇🏾

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/9566 Thanks everyone :100:
