### ISSUE TITLE
"Getting Started" link on navbar leads to error page for Admin users

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#9527]
☀️🌞🌼🌻🌳
### Please describe the problem

> What happened just before the problem occurred? Or what problem could this idea solve?

When logged in with an account with Admin privileges, clicking the Getting Started link under **Navbar --> Community --> Getting Started** leads to an error page. I reproduced this from an error reported by @publiclab-mimi who was logged into publiclab.org using Admin account "mimiss": 
![getting-started-erro-loggged in](https://user-images.githubusercontent.com/161439/115260769-0b351700-a101-11eb-8e6f-09910b1eebd0.gif)

As people with Admin accounts are often leading tours of the website, this does affect non-admin users. 

NOTE: from brief testing i conducted, this bug does not seem to affect not-logged in users, or users with regular accounts with no special privileges. 

> What did you expect to see that you didn't?

I expected the redirect on that link to work, and point me at /welcome, even when logged in as Admin. 

### Please show us where to look

https://publiclab.org/ navbar, the first link in the **Community** menu

### What's your PublicLab.org username?

> This can help us diagnose the issue: 
liz

Thank you!

**Comment by jcads** [comment]
I'd like to work on this but i wasn't able to replicate the bug in my local development. Any ideas?

**Comment by publiclab-mimi** [comment]
It's something that I only saw when logged in through an admin account. I'm
not sure if that's helpful for reproduction.

**Comment by jywarren** [comment]
Thanks for reporting this! It's the user-facing side of this error: https://github.com/publiclab/plots2/issues/9417 and was fixed in https://github.com/publiclab/plots2/pull/9435 9 days ago by @gaurav2699 with help from @pydevsg @Tlazypanda @cesswairimu @RuthNjeri 

GREAT collaboration everyone!!! ✨ ✨ ✨ ✨
