### ISSUE TITLE
Move comment input box to bottom of comments list on Questions pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#955]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled.

****

### What happened just before the problem occurred

The Questions form had been designed with comments in ascending, instead of descending, time order, and we switched that back (to oldest-at-top) in a recent commit. But now the input itself is still at the top, but comments appear at the bottom when added. 

Let's move the input to the bottom to match! This will also be more consistent across the site. 

### Relevant URLs

https://publiclab.org/questions/marfisistemidroni/11-03-2016/question-infragram-kit

The relevant code can be found on this template:

https://github.com/publiclab/plots2/blob/master/app/views/questions/show.html.erb#L52-L74

With the list of comments on line 73, and the form for it above. 

To solve this, just swap those!

**Comment by jywarren** [comment]
@ryzokuken - if you're looking for a new issue, I wonder if you'd be willing to try converting this to a `first-timers-only` issue? https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors

This helps us broaden our contributor base!

**Comment by ryzokuken** [comment]
@jywarren I could definitely try.

**Comment by ryzokuken** [comment]
@jywarren Correct me if I'm wrong

https://github.com/publiclab/plots2/blob/master/app/views/questions/show.html.erb#L52-L70 is the comment form.

https://github.com/publiclab/plots2/blob/master/app/views/questions/show.html.erb#L72-74 render the comments partial.

All this issue involves is swapping the position of those.

**Comment by jywarren** [comment]
That's right, and this makes it an ideal `first-timers-only` issue -- it's
also not a critical bug, so we can afford to wait a few days (or even
weeks) for it to be fixed. Keeping a good supply of first-timers issues is
a key strategy of ours in continuing to recruit new contributors!

Thanks!

**Comment by ryzokuken** [comment]
@jywarren Yeah, I realized that. I'll write a small markdown file for the issue description and come back to you as it would be my first issue.

**Comment by jywarren** [comment]
you can also tag it with `fto-candidate` so I can take a look over it
before it goes up on the list in front of actual first-timers -- we're
treating that as our "queue" since it does take extra effort to finalize
one of these with full formatting.

Thanks a lot!!

**Comment by jywarren** [comment]
Made into first-timers-only issue in #958

**Comment by ryzokuken** [comment]
Cleaned up that one.
Was the content and everything okay? I added a prerequisites section but rather filled it with places where you could learn stuff so that it doesn't feel intimidating.

**Comment by jywarren** [comment]
Yes it looks great! Thanks!

**Comment by ryzokuken** [comment]
:grinning: Don't mention it. Looking forward to making a few more in the course of the week. I have 2 issues in mind (one of which I already posted as an `fto-candidate`), after which I'll just look up other `fto-candidate`s.
