### ISSUE TITLE
Hide Emoji list after leaving comment reaction

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#9563]
**Please describe the desired behavior.**
After leaving a reaction on a comment, the emoji container should hide/close.

**Additional context (optional)**

https://user-images.githubusercontent.com/63427719/116144197-f396f900-a6d3-11eb-81b5-f7b3532de778.mov

**Comment by govindgoel** [comment]
@TildaDares this is great

**Comment by jywarren** [comment]
Hi @TildaDares i really appreciate this one, but I am also unsure -- i often use multiple reactions and so i kind of like that it stays open? What do other people think? I'm not set either way.

**Comment by CQW-Code** [comment]
I sometimes do use multiple reactions so like that it stays open; I don't know if it's feasible but maybe a time delay on closing the reaction/emoji list? ( that may or may not be a plus for low vision and blind people who may use publiclab's site).

**Comment by jywarren** [comment]
That's such a great idea, thanks @CQW-Code. I think that's a relatively easy change as well, what do you think @TildaDares?

Maybe we need to help the first-timer at https://github.com/publiclab/plots2/issues/9574 add a `setTimeout()` delay?

**Comment by TildaDares** [comment]
@jywarren The issue at #9574 is different from this one. The `setTimeout()` will be added to the PR for this issue.
