### ISSUE TITLE
Emoji list is hidden on mobile devices

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#9574]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file `app/views/notes/_comment.html.erb` in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -1,6 +1,6 @@
 <div id="c<%= comment.cid %>" class="comment" style="margin-top: 20px; margin-bottom: 20px; padding-bottom: 9px; word-wrap: break-word;">
 
-  <div style="margin-bottom: 0;border-bottom-left-radius: 0;border-bottom-right-radius: 0;border-bottom: 0;" class="navbar navbar-light bg-light">
+  <div style="margin-bottom: 0;border-bottom-left-radius: 0;border-bottom-right-radius: 0;border-bottom: 0;overflow-y: visible;" class="navbar navbar-light bg-light">
     <% if comment.status == 4 %>
       <p class="alert alert-warning moderated">
         <% if logged_in_as(['admin','moderator']) %>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by TildaDares** [comment]
## Before

https://user-images.githubusercontent.com/63427719/116328090-21596c00-a7c0-11eb-8a46-28825bad2a7c.mov

## After

https://user-images.githubusercontent.com/63427719/116328164-506fdd80-a7c0-11eb-8396-c038565137c8.mov

**Comment by Khusyasy** [comment]
hey, can I claim this? I'm new to contributing to open source,

**Comment by TildaDares** [comment]
@Khusyasy Go ahead🎉

**Comment by Khusyasy** [comment]
@TildaDares I'm a bit confused but I managed to do the pull request, can you review it please, and did I get it right?

**Comment by jywarren** [comment]
Hi all - thanks so much for your help here. Just noting we've had a little more discussion on this and possibly want to have a delay before it hides in case people want to add multiple reactions. Could we add a `setTimeout()` delay to JavaScript here?

**Comment by 2201monesh** [comment]
I am new to open source , can I work on this issue

**Comment by TildaDares** [comment]
@2201monesh Thank you for the interest but there's an open PR for this already. You can ask for your name to be added to the list of first timers in #1234
