### ISSUE TITLE
Move comment input box to bottom of comments list on Questions pages

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plots2#958]
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## Prerequisites

You don't really need to know anything in advance in order to tackle this issue. However, a little understanding about HTML and/or ERB (Embedded Ruby) would really help you not only crack this issue easily, but understand what's happening behind the scenes.

Get started with HTML:
1. http://www.w3schools.com/html/
2. https://developer.mozilla.org/en-US/docs/Learn/HTML
3. https://www.tutorialspoint.com/html/

Get started with ERB:
1. http://www.stuartellis.name/articles/erb/
2. https://www.tutorialspoint.com/ruby-on-rails/rails-introduction.htm

## The problem

Currently, the comment input box appears at the top of the comments list. (See [this](https://publiclab.org/questions/marfisistemidroni/11-03-2016/question-infragram-kit) question for reference) it needs to be moved to the bottom of the comments list.

## The Motivation

The Questions form had been designed with comments in ascending, instead of descending, time order, and we switched that back (to oldest-at-top) in a recent commit. But now the input itself is still at the top, but comments appear at the bottom when added.

Let's move the input to the bottom to match! This will also be more consistent across the site.

## Solution

https://github.com/publiclab/plots2/blob/master/app/views/questions/show.html.erb#L52-L70 is the comment form.

https://github.com/publiclab/plots2/blob/master/app/views/questions/show.html.erb#L72-74 render the comments partial.

All you need to do is to swap the positions of the two.

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by ryzokuken** [comment]
@jywarren I tried my best. Please tell me if there's anything I could do to improve the quality of this question and any others I make in the future. Also, if you find the issue up to the mark, tag it as required.

**Comment by ashleypt** [comment]
Hi, I'd love to do this as I'm learning rails! :)

**Comment by ryzokuken** [comment]
@ashleypt Sure! You can post any queries you have here.

**Comment by jywarren** [comment]
Hi! I don't think `rake db:migrate` is necessary -- which instructions did you see that in? `rake db:setup` should be enough. But if we out incorrect instructions up, we should fix it!

**Comment by ashleypt** [comment]
@jywarren Ah! Sorry, I'm used to running rails db:migrate or rake db:migrate - didn't catch the db setup. It's working now, should have the issue fixed quickly :)

**Comment by ashleypt** [comment]
All fixed :) https://github.com/publiclab/plots2/pull/960

**Comment by ryzokuken** [comment]
@ashleypt Just curious --- were the installation instructions unclear in any way?

**Comment by ashleypt** [comment]
@ryzokuken no but you put the wrong link to the developers page in your initial comment on the issue - /developers instead of /wiki/developers :)

**Comment by ashleypt** [comment]
@ryzokuken maybe do a better job specifying which steps are optional - like installing jdk for solr. that could be my next pull request!

**Comment by ryzokuken** [comment]
@jywarren I had been thinking about keeping things simple by keeping only the necessary stuff inside the installation section, segregating the optional stuff completely. Will talk about this on OpenHour, perhaps? BTW, its today, right? 1PM ET?

**Comment by ashleypt** [comment]
@ryzokuken here's a pull request to fix the readme. ill take on any additional readme changes you might want as well

https://github.com/publiclab/plots2/pull/961

**Comment by ryzokuken** [comment]
@ashleypt Wonderful! If this is discussed today, I'll let you know anything which gets decided. Another thing I had in mind was to segregate the optional steps involving the configuration of solr which currently reside in the installation section, to perhaps a new section like "Solr Configuration (Optional)".

**Comment by aayushgupta1** [comment]
Hi, I would love to contribute to this. I am learning rails at the moment.

**Comment by aayushgupta1** [comment]
Hey, I made some changes for the comments section. Can someone check it and respond to the pull request?

**Comment by jywarren** [comment]
Merged in #960! Thanks!

**Comment by aayushgupta1** [comment]
Welcome!
