### ISSUE TITLE
Change the bundler install statement in README and the cloud9 installation script to effectively avoid installation of the mysql2 gem

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plots2#959]
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## Prerequisites

You don't really need to know anything in advance in order to tackle this issue. However, a little understanding about Bundler would really help you not only crack this issue easily, but understand what's happening behind the scenes.

Get started with Bundler:
1. http://bundler.io/
2. http://bundler.io/rationale.html

## The problem

In a development environment, one is required to install all gems excluding gems belonging to the `production` group. The gems from the production group (only the `mysql2` gem for now) are also a part of another group named `mysql`. Therefore, in order to avoid it's installation, it is imperative to skip installing **BOTH** the groups.

## The Motivation

If we appropriately mention the command to be used in order to install the gems on a person's local computer in the documentation, newer developers would find it easier to setup the project on their respective environments.

## Solution

In order to fix this, all one needs to do is to find all instances of the command `bundle install --without production` in two files- [README.md](https://github.com/publiclab/plots2/blob/master/README.md) and [install_cloudnine.sh](https://github.com/publiclab/plots2/blob/master/install_cloudnine.sh) and replace them with a slightly improved command- `bundle install --without production mysql`

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by ryzokuken** [comment]
@jywarren Here's another one. Please tag it and close the other issue if you find it up to the mark.

**Comment by wenyichen** [comment]
hey, can I work on this?

**Comment by jywarren** [comment]
Yes, of course, and thanks!
