### ISSUE TITLE
Final listing of barnstars for widget

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#96]
@ebarry - did you have any other barnstars you'd like to add to the widget? And do the links work now?

I want to add one for coding for:

http://publiclab.org/notes/pfoltyn/06-10-2014/webgl-flavored-infragram-org

**Comment by ebarry** [comment]
it's great that people are using the barnstar system on research notes, but we still gotta update this based on the organizers' work from last year http://publiclab.org/wiki/barnstar-brainstorm#which+barnstars+should+be+listed+in+research+note+dropdown?

* Classic (existing)
* Documentation (combo of photo, video, cinematography)
* Watchdog (existing)
* Empiricism (existing)
* Education barnstar - (existing)
* Remixing
* Engagement barnstar (for outreach) - two halves of star flipped inside out so points touch in the center. Similar to an earlier proposal for "teamwork barnstar"
* Affordability: http://publiclab.org/notes/mathew/5-29-2012/solar-hot-air-balloons making technologies more accessible by radically reducing their cost.
* Great question - (new) gold question mark for a well-framed research question

**Comment by jywarren** [comment]
Great, do each of these have an entry on the Barnstars page with a title that is their exact name, but capitalized? If so, we can add these. Each will be slotted into a sentence like:

`<recipient> was awarded the Xxxxxx Barnstar by <awarder> for their work in this research note.`

https://github.com/publiclab/plots2/blob/ad7fa8d4970a4a831d7eea626be4e27cd295dbf7/app/views/like/_like.html.erb#L16-L21

**Comment by jywarren** [comment]
There's a bug in the link code now, but each ought to link then to the following:

`publiclab.org/wiki/barnstars#Xxxxxxx`

We can change how that link is generated/transformed from the barnstar tag name -- this would be from `barnstar:xxxxxx`

**Comment by ananyo2012** [comment]
@jywarren Can this be closed now? Barnstars are now listed in https://publiclab.org/wiki/barnstars with the correct links in the format mentioned above

**Comment by jywarren** [comment]
This is up to @ebarry and @steviepubliclab -- depends if we want to
reconcile the legacy vs. tag-based barnstars. Thanks!

**Comment by jywarren** [comment]
I'm going to close this now as we haven't used the older barnstar system for a while, but we can now add barnstar types if we like, so happy to open issues for that!
