### ISSUE TITLE
Add WSL2 set-up instructions for Redis

### ISSUE THREAD

**Issue by Elukoye** [publiclab/plots2#9608]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open-source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [README.MD](https://github.com/publiclab/plots2/edit/main/README.md) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Add the following after line 150 in the README.md file ⬇️ ⬇️ 
 * Using **Ubuntu WSL2**: 
  -update & upgrade Ubuntu: `sudo apt update && apt upgrade`
  -install redis:`sudo apt install Redis-server`
  -open Redis.config file:`sudo nano /etc/redis/redis.conf`
  -update the file by changing the `supervised no` line to `supervised systemd`(ubuntu uses systemd)
  -start Redis:`sudo service redis-server start`
  -open Redis CLI: `redis-cli`
  -test Redis: type `ping` & response should be `pong`
  -exit cli: type `quit`
   Awesome 👍  All done ✅ 

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming the first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by xdshivani** [comment]
I would like to work on this

**Comment by Elukoye** [comment]
@xdshivani ,all yours 🙂🚀

**Comment by xdshivani** [comment]
I am working on this.

**Comment by bajajvinamr** [comment]
I would like to claim this issue!

**Comment by Elukoye** [comment]
Hi @bajajvinamr,@xdshivani  is already working on this

**Comment by parth-gohil** [comment]
Hi @xdshivani , I'd like to help contribute. Let me know if you need any help with the issue. :)

**Comment by iamkrish-coder** [comment]
Is this still available to grab? First timer looking for a contribution :)

**Comment by jrogers-dev** [comment]
@Elukoye 

Also a first timer, and would like to know how do we know if/when the initial claimant has abandoned the task?
I've noticed a few other issues that were opened up to anyone willing to submit a pull request. 
Is there a timeline for that, or is it just some issues that are opened up in that way?

Either way, I'm open to working on this issue if possible.

Thank you for your time, it's much appreciated!

**Comment by Elukoye** [comment]
@jrogers-dev ,the person who initially claimed the issue hasn't worked on it . The rule is that if the issues hasn't been touched for one week then it can be claimed by another ,so please go ahead and claim it.

**Comment by jrogers-dev** [comment]
Thank you for the response, @Elukoye ! Claiming this, and submitting pull request: #9748
