### ISSUE TITLE
What is the URL to query a date range on the stats page?

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#964]
The /stats page is really great, https://publiclab.org/stats

It offers some ability to customize the date range you are looking for by clicking "Try [one year], [one month], or [one week] further back." Clicking on any of those adds a query to the URL based on the exact current time and date, such as 

https://publiclab.org/stats?time=December%2031,%202015

Helpfully, clicking the button for [one year] a second time modifies this modified URL: 
https://publiclab.org/stats?time=December%2031,%202014%2000:00

I'm wondering, is there a URL to query a bracketed date range, for instance August 1 to October 31?

**Comment by jywarren** [comment]
There is not currently a date range feature.

This could be added by making the `params[:time]` parameter into `params[:end]`, and adding a `params[:start]` which defaults to, for example, timestamp 0, for example. 

The code for this is here:

https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb#L13-L17

But it raises other questions; would the 52-week periods still just be 52 weeks, or would we need to design a flexible graph that could show the whole range? The former is easier and is a good first step, but it'd have to be clearly presented in the display so people don't get confused. 

If we went forward with completely flexible graphing, we might need to set limits or allow only mods to do this, as it could tax the database and slow the site. 

The `start/end` change above would also need to be reflected in `DrupalNode`: https://github.com/publiclab/plots2/blob/master/app/models/drupal_node.rb#L173-L183

And in `DrupalComment`: https://github.com/publiclab/plots2/blob/master/app/models/drupal_comment.rb#L23-L31

What is the prioritization on this? Should I spend some time further breaking this up and adding documentation and suggested paths forward? Thanks!

**Comment by jywarren** [comment]
@ebarry - bumping this up for next steps, thank you!

**Comment by ebarry** [comment]
So, i was hoping not to create new graph or graphic interface features. If i can simply do a URL query, i can get the evaluation work done. Can this be a bare bones thing and go faster?

**Comment by jywarren** [comment]
I think we can't let the graphs go out of sync -- but one step forward is to adapt `weekly_tallies` in the following lines to accept a start date, or document the methods better so we know how many weeks "forward" or "back" we need to specify:

```ruby
    @graph_notes = DrupalNode.weekly_tallies('note', 52, @time).to_a.sort.to_json
    @graph_wikis = DrupalNode.weekly_tallies('page', 52, @time).to_a.sort.to_json
    @graph_comments = Comment.comment_weekly_tallies(52, @time).to_a.sort.to_json
```

That code is here:

https://github.com/publiclab/plots2/blob/master/app/models/drupal_node.rb#L181

and here:

https://github.com/publiclab/plots2/blob/master/app/models/comment.rb#L27

Other than that, every line in the controller has a range already, so we'd have to adapt it to accept both a start and and end date:

```ruby
.where(timestamp: @time.to_i - 1.years.to_i..@time.to_i)
```

**Comment by jywarren** [comment]
I think this is more complex because of the way current data is displayed: see how on https://publiclab.org/stats, it says:

> 9 notes and 70 wiki edits posted in the past week. 711 people joined in the past week.
> 49 notes and 203 wiki edits posted in the past month. 2921 people joined in the past month.

that can't easily be adapted into a range, just grammatically

if I changed it all to follow the range specified, we'd lose the "past week" stat which is quite useful when the specified period ends "present day"

maybe I could change it so that it shows data for:

1. the specified period, which'd be a year by default, 
2. the final week of the period and 
3. the final month of the period?

that way all the current displays would show the same data as they do right now, but the labels would be rewritten to be flexible to a specified period

and i guess we'd want to add one for the entire period, so it'd be like:

> 9 notes and 70 wiki edits posted in the past week. 711 people joined in the final week of the specified period. (if it's longer than 1 week)
> 49 notes and 203 wiki edits posted in the past month. 2921 people joined in the final month of the specified period. (if it's longer than 1 month)
> ## notes and ### wiki edits posted in the past month. #### people joined over the specified period.

Or, we could move the top two up, and just show the last week/month in relation to present time no matter what (showing exact dates to be clear), and have the customizable period below, again clearly marked

Or, maybe best to just not touch this page, and create a new page which outputs, in text, the data you want? Then we sidestep this whole thing and just have as simple a query as we can. What statistics exactly do you need?

**Comment by ebarry** [comment]
For the evaluation project, @sdosemagen and I need to export activity on the website for specific three month periods for multiple years. Example is "September, October, November" for 2011, 2012, 2013, 2014, 2015. We are totally OK with setting up a separate and low-tech way just so we can get this, and leaving the /stats page as is! Thank you for thinking about this and helping.

**Comment by jywarren** [comment]
Sure -- but what activity exactly? Just "notes, wiki edits posted, people joined" ? Questions?

**Comment by jywarren** [comment]
Comments?

**Comment by ebarry** [comment]
Well, this is going to sound ridiculous, but "Everything possible that we
can get from the plots2 database."

--

+1 336-269-1539
@lizbarry <http://twitter.com/lizbarry>

**Comment by jywarren** [comment]
Can you prioritize this list, perhaps starting with `notes, wiki edits posted, people joined`, since we already have queries for that? And what else? Thanks, just looking for a more actionable ranked list.

**Comment by jywarren** [comment]
Thanks, got feedback - 

> notes, wiki edits posted, people joined
