### ISSUE TITLE
Move "More topics" and more on new v2 dashboard into left column

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#9654]
We have some great features [in the new v2 dashboard](https://stable.publiclab.org/v2/dashboard/), which, if someone hasn't yet started following topics, let site admins encourage people to follow by showing featured tags and other content. However, these are displayed full width, so they get pushed down below all other content in the left or right column:

![image](https://user-images.githubusercontent.com/24359/119211857-be878780-ba82-11eb-99da-bf26d0d5cda4.png)

We should move this into the left column so that it is more visible to new users (who are following few topics yet) without having to scroll down the page. 

I believe this will involve moving the following code up onto line 8 of the same template, but it will require some testing to confirm that this works!

https://github.com/publiclab/plots2/blob/0837f34289cacc965138a051f99846c047b18988/app/views/dashboard_v2/dashboard.html.erb#L16-L41

**Comment by jywarren** [comment]
I just tried this in the Chrome dev console and it seems to work:

![image](https://user-images.githubusercontent.com/24359/119211981-93e9fe80-ba83-11eb-97b4-21bf0dded31a.png)

Note that the two "Water Quality" cards shown are added as custom content using the Features system, so don't worry about those, they'll just act the same as the Featured and Trending Topics just above them.

**Comment by jywarren** [comment]
@TildaDares this might be a small but nice refinement to consider as part of your project, or as an FTO for someone else!

**Comment by TildaDares** [comment]
@jywarren Sure, I'll take a look at it.

**Comment by cesswairimu** [comment]
Looks like this was solved in https://github.com/publiclab/plots2/pull/9658 . Closing this, thanks all
