### ISSUE TITLE
Move 'More Topics' on new dashboard into left column

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#9655]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file `app/views/dashboard_v2/dashboard.html.erb` in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

See #9654 for more screenshots

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -5,6 +5,32 @@
       <%= render partial: "dashboard_v2/blog"%>
       <%= render partial: "dashboard_v2/alerts"%>
       <%= render partial: "dashboard_v2/topicCard"%>
+      <%# Additional Topics %>
+      <div class="other-topics">
+        <h4>
+          <i class="form-grey"><%= translation('dashboard_v2.sidebar.interest_topics', :url => '/subscriptions')%></i>
+        </h4>
+        <%# Featured topics %>
+        <small><a href="/tags" class="form-grey"><%= translation('dashboard_v2.sidebar.featured_topics') %>:</a></small>
+        <span>
+          <%= feature('feature-tags') %>
+          <small class="text-format form-grey" style="text-decoration: underline"><%= translation('dashboard_v2.sidebar.more_topics',:url => '/wiki/topics') %> </small>
+        </span>
+        <br/>
+        <%# Trending topics %>
+        <small><a href="/tags" class="form-grey"><%= translation('dashboard_v2.sidebar.trending_topics') %>:</a></small>
+        <span>
+          <% cache('trending-tags', expires_in: 24.hours, skip_digest: true) do %>
+              <% @trending_tags.each do |i| %>
+                  <a href="/tag/<%= i.name %>" class="badge badge-primary"><%= i.name %></a>
+              <% end %>
+            <% end %>
+          <small class="text-format form-grey" style="text-decoration: underline"><%= translation('dashboard_v2.sidebar.more_topics',:url => '/wiki/topics') %> </small>
+        </span>
+      </div>
+      <div class="dashboard-topics-footer">
+        <%= feature('dashboard-topics-footer') %>
+      </div>
     </div>
     <%# Sidebar %>
     <div class="col-lg-4">
@@ -13,32 +39,6 @@
       <%= render partial: "dashboard_v2/sidebar"%>
     </div>
   </div>
-  <%# Additional Topics %>
-  <div class="other-topics">
-    <h4>
-      <i class="form-grey"><%= translation('dashboard_v2.sidebar.interest_topics', :url => '/subscriptions')%></i>
-    </h4>
-    <%# Featured topics %>
-    <small><a href="/tags" class="form-grey"><%= translation('dashboard_v2.sidebar.featured_topics') %>:</a></small>
-    <span>
-      <%= feature('feature-tags') %>
-      <small class="text-format form-grey" style="text-decoration: underline"><%= translation('dashboard_v2.sidebar.more_topics',:url => '/wiki/topics') %> </small>
-    </span>
-    <br/>
-    <%# Trending topics %>
-    <small><a href="/tags" class="form-grey"><%= translation('dashboard_v2.sidebar.trending_topics') %>:</a></small>
-    <span>
-      <% cache('trending-tags', expires_in: 24.hours, skip_digest: true) do %>
-          <% @trending_tags.each do |i| %>
-              <a href="/tag/<%= i.name %>" class="badge badge-primary"><%= i.name %></a>
-          <% end %>
-        <% end %>
-      <small class="text-format form-grey" style="text-decoration: underline"><%= translation('dashboard_v2.sidebar.more_topics',:url => '/wiki/topics') %> </small>
-    </span>
-  </div>
-  <div class="dashboard-topics-footer">
-    <%= feature('dashboard-topics-footer') %>
-  </div>
 </div>
 
 <style>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by TildaDares** [comment]
@Rutwij12 Would you like to work on this?

**Comment by tobiasvpini** [comment]
Hi, i will try to make it.

**Comment by tobiasvpini** [comment]
> @Rutwij12 Would you like to work on this?

Must it only copy and paste the plus diff?

**Comment by tobiasvpini** [comment]
@TildaDares must it only copy and paste the plus diff?

**Comment by TildaDares** [comment]
@tobiasvpini Let's give @Rutwij12 some time to respond.

**Comment by Rutwij12** [comment]
Hi @TildaDares Yeah Sure! I can have a go at this.

**Comment by yuma-fujimoto** [comment]
Hi @TildaDares I want to do it too.

**Comment by TildaDares** [comment]
Hi @yuma-fujimoto there's an open PR for this issue already. You can ask for your name to be added here #1234
