### ISSUE TITLE
[Discussion] Add Listing of Draft Posts to Profile Pages

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#9660]
In my [proposal](https://publiclab.org/notes/mathildaudufo/04-26-2021/outreachy-education-related-usability-upgrades) I suggested adding a link to the draft posts among the user's activity ( research notes, wiki edits e.t.c) and only the profile user would be able to see the page.

![image](https://user-images.githubusercontent.com/63427719/119323939-230b3800-bc77-11eb-9a42-ca4f30bab9d9.png)

The drafts page would be displayed in the author's page like https://publiclab.org/notes/author/cess/ but it would be drafts instead of notes. You can see the discussion here https://publiclab.org/notes/mathildaudufo/04-26-2021/outreachy-education-related-usability-upgrades#c28650

![image](https://user-images.githubusercontent.com/63427719/119324855-2fdc5b80-bc78-11eb-8beb-187fc3e388fe.png)

Currently a publish draft button can only be found in the alert message and if the cancel button is mistakenly clicked/tapped then that functionality is lost (refreshing the page displays the alert message again). So, I suggested including a `Publish Draft` button in the page itself. This makes it a lot easier to find the `Publish` button even when the alert is closed.

![image](https://user-images.githubusercontent.com/63427719/119325676-07a12c80-bc79-11eb-9f45-2a78d12411f2.png)

@jywarren @RuthNjeri @cesswairimu Please let me know your thoughts on this proposal.

**Comment by jywarren** [comment]
I think this sounds great. The only notes i have are:

1. things that are visible only to the user can create confusion if they aren't clearly labeled as such, so maybe on the page with the drafts tab we add a small text below the tabs that says (in a yellow alert box?) `This tab is visible only to the author.` (that actually raises a question - should it be visible to admins? I suppose not! Or let's start with the assumption not, as it's simpler and better privacy. We could later reconsider)
2. the list of items on the profile is a bit messy itself, so while I like this appearing there, i want to keep in our minds the thought that there may be a better design for this list at some point!

Thanks, @TildaDares !!!

**Comment by TildaDares** [comment]
@jywarren I've taken note of everything you've mentioned and I'll work on a better solution.

**Comment by TildaDares** [comment]
@jywarren I think another possible location for the `drafts` button would be the dropdown menu for the profile picture. It would be placed in the section for `subscriptions` and `notes you liked` because they are kind of related. 

![image](https://user-images.githubusercontent.com/63427719/119623870-7f4d9380-be00-11eb-9ef5-d6d561043149.png)

What do you think about this alert box being placed at the centre of the drafts tab?

<img width="728" alt="Screenshot 2021-05-27 at 11 59 30" src="https://user-images.githubusercontent.com/63427719/119815028-03784780-bee3-11eb-918f-52fe992867ef.png">

**Comment by RuthNjeri** [comment]
Thanks for sharing your suggestions @TildaDares, I think adding it in the profile picture drop-down makes sense to me...even without the text `This tab is visible only to the author.` it shows that the drafts are specifically for the user...

Tagging @ebarry, she could have some insights as well...

**Comment by TildaDares** [comment]
@jywarren @RuthNjeri Since I'll be making use of the `notes/author` template for the drafts page, this task kind of relies on #9622.

**Comment by ebarry** [comment]
Thank you so much for working on this very useful feature!
I think the righthand sidebar is a great place to link to Draft content. I would **not** put it in the dropdown menu for the profile picture (it's already confusing that "Notes you've liked" is in that menu, and it might be nice to look ahead to how this link to "likes" could also be moved into the right sidebar on the page as well). 

What is your outlook on the two big links under the map VS the more complete list of links in the right sidebar? Do we have the right content in the right place here? 
<img width="688" alt="Screen Shot 2021-06-07 at 10 40 16 AM" src="https://user-images.githubusercontent.com/161439/121036772-ed894300-c77c-11eb-8dc5-26da20c1408d.png">
<img width="253" alt="Screen Shot 2021-06-07 at 10 41 40 AM" src="https://user-images.githubusercontent.com/161439/121036816-f5e17e00-c77c-11eb-8981-40c4ecbb400a.png">

**Comment by TildaDares** [comment]
@ebarry I think the two links under the map should be removed. The sidebar already has those links so it seems kind of repetitive to still have it under the map. Also, making the sidebar the only place where you can find links to content created by the user makes the page a lot more organised and easier to navigate.

**Comment by ebarry** [comment]
ok, sounds good!
--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net

**Comment by ebarry** [comment]
Hi! responding to Jeff's note above, point 1:
>things that are visible only to the user can create confusion if they aren't clearly labeled as such, so maybe on the page with the drafts tab we add a small text below the tabs that says (in a yellow alert box?) This tab is visible only to the author. 
- on this, Ruth suggested "This tab is visible only to the author and site administrators" as I noted that the current default is that admins are able to see draft posts and reach out through the comments to offer help if it seems needed. 

> (that actually raises a question - should it be visible to admins? I suppose not! Or let's start with the assumption not, as it's simpler and better privacy. We could later reconsider)
- i'm noting that currently admins are able to see draft posts, so this would be a change I do not wish to make at this time without further consideration.

**Comment by jywarren** [comment]
Hi all! I actually thought it sounded like a really nice idea to put it in the menu dropdown -- @ebarry what are your concerns about placing a link there? It seems like a familiar place to find such things, for example "drafts" can be found in such a menu in some sites/apps. Is there a confusing scenario you've observed related to seeing Likes there as well? 

Another place could be in the /post form itself -- see how drafts are listed there in Twitter, and in Instagram this is similar:

![image](https://user-images.githubusercontent.com/24359/121705643-d7dc8c00-caa2-11eb-944d-e84cdfd21944.png)

**Comment by TildaDares** [comment]
> Another place could be in the /post form itself

@jywarren @ebarry 
 We could also use a modal instead of a page.

**Comment by ebarry** [comment]
Have we ever created a clear concept for what goes in the Profile dropdown
menu? I'm interested in us making one. I feel that over the years I've been
a part of creating what—in US slang at least— might be called "a junk
drawer" approach -- lots of important bits that don't fit anywhere else yet
we want them handy. Without a clear concept of that menu, i'm hesitatant to
put yet another item there, especially when there's a clear place for it on
the profile page itself.
--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net

**Comment by jywarren** [comment]
Ah, just to clarify, i wasn't suggesting it go in the menu /instead of/ the profile page. 

Let's move ahead with what we have wide agreement on - a link from the profile page. @TildaDares i like the modal concept but i think it might be easier to use a page so that we can easily link to it from multiple places, and also so that there's a URL we can tell people to go to where drafts are listed. What do you think?

I like the My Drafts button on the post page too. Let's do that in addition to the profile page link!

Thanks, all!

**Comment by TildaDares** [comment]
@ebarry @jywarren @RuthNjeri 
The drafts page looks like the research notes index page without the nav tabs. I'm not too sure about the heading text.

<img width="1280" alt="Screenshot 2021-07-08 at 00 08 02" src="https://user-images.githubusercontent.com/63427719/124839364-93002400-df80-11eb-89e7-36be2902d9a2.png">

I'm also reconsidering adding the drafts tab in the research notes index page. Some elements start to overlap on certain breakpoints because there are too many items.

<img width="769" alt="Screenshot 2021-07-08 at 00 15 41" src="https://user-images.githubusercontent.com/63427719/124839906-a52e9200-df81-11eb-8c66-f7b0ed12b222.png">

**Comment by jywarren** [comment]
Hi! I love both, for different reasons, and I really appreciate your thinking through this. We can adjust the breakpoints but it might be best to put "Drafts" last if we do so we can just adjust visibility for that single one rather than for all? But, I trust your judgement on this. The single page looks great as well, and we could add `Visible to you and those you've shared a private link with` maybe?

**Comment by RuthNjeri** [comment]
It looks great @TildaDares, I agree with Jeff, also the `sort_by` is only available for the research notes. It does not pop up for the other items in the navbar so it's breakpoint should be easy to fix.
