### ISSUE TITLE
Weekly Community Check-In #104 - Outreachy Internship Starts Today🥳

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#9661]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Outreachy Internship Starts Today🥳

Congratulations once again to @imajit @17sushmita @waridrox @Manasa2850 @daemon1024 for being accepted into GSOC and Outreachy.

Today is the first day of the Outreachy internship and I'm both excited and nervous😂. Facing new situations and changes can be scary especially for me. So, when I'm in these kind of situations I try to be as positive as I can and acknowledge that I might make mistakes or not know something. Learning is part of the job and if I do make mistakes I learn how to fix them and avoid such mistakes in the future. 

Please share how you cope with anxiety when you face new situations.

## This week's focus Issues

These are issues that are of high priority and requests from our
large community that use the software. 

https://github.com/publiclab/plots2/labels/high-priority

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note to focus issues contributors

Many thanks to contributors of the past two weeks
🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇
@jywarren @cesswairimu @RuthNjeri @icarito @Rutwij12 @bajajvinamr @aliciapaz @Manasa2850 @krishgon @2201monesh @P0NC1K @Dandu-Rajeev @aws107 @dependabot[bot] @carlos-osorio-developer @Priyaraj17 @waridrox 
🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by cesswairimu** [comment]
Hi all, 

Congratulations @imajit @17sushmita @waridrox @Manasa2850 @daemon1024 @Manasa2850 @TildaDares :tada: :tada: :tada:  :tada: :tada: 

Thanks @TildaDares  for the check-in
Great week ahead everyone :balloon:

**Comment by Manasa2850** [comment]
Nice check-in @TildaDares :partying_face:. Even I'm excited and nervous at the same time and I hope to learn a lot throughout the internship :smiley: 
Thank you @cesswairimu !!

**Comment by 17sushmita** [comment]
> Nice check-in @TildaDares . Even I'm excited and nervous at the same time and I hope to learn a lot throughout the internship 
> Thank you @cesswairimu !!

@Manasa2850 Having the same feeling as you, Excited and nervous. Really looking forward to have a great learning experience this summer😃

**Comment by jywarren** [comment]
Thank you so much, @TildaDares and everyone else! This will be great, and I'm really looking forward to working with you. Please don't hesitate to ask questions! 

One great thing to check out is this great intro to using milestones and planning issues, written by @RuthNjeri --

https://publiclab.org/wiki/gsoc#Using+Milestones+and+Planning+issues

I'll be sending out a bigger welcome packet to everyone tomorrow morning!

✨ ✨ ✨ ✨ ✨

**Comment by aliciapaz** [comment]
A deep-deep-breath, good luck, and a great week ahead to the new interns 🎉

**Comment by carlos-osorio-developer** [comment]
Thanks for the updates @TildaDares, looking forward to keeping contributing. Congratulations and good luck to everybody on this path! Greetings!

**Comment by Elukoye** [comment]
Congrats to all those who were chosen for the internship, looking forward to working with you all.

**Comment by cesswairimu** [comment]
happy new week all...anyone wonna open this week's check-in?

**Comment by waridrox** [comment]
@cesswairimu, done at #9703! 🎈

**Comment by cesswairimu** [comment]
Thanks a bunch @waridrox :tada: :tada: :tada: 


Moved to #9703 . Thanks everyone
