### ISSUE TITLE
Poll for both Summer of Code Students and Mentors 🗳️

### ISSUE THREAD

**Issue by grvsachdeva** [publiclab/plots2#9697]
### Poll for both Summer of Code Students and Mentors (Outreachy and GSoC 2021): 

Hi folks, please complete the below poll and help us understand what are your opinions/preferences when it comes to different activities of the Summer of Code program.

**1. What should be the frequency of the Summer of Code All-Hands call?** 
[![](https://api.gh-polls.com/poll/01F6YRHYJM6TFMDMPYQKFHDX7M/Weekly)](https://api.gh-polls.com/poll/01F6YRHYJM6TFMDMPYQKFHDX7M/Weekly/vote)
[![](https://api.gh-polls.com/poll/01F6YRHYJM6TFMDMPYQKFHDX7M/Biweekly%20%28Every%202%20weeks%29)](https://api.gh-polls.com/poll/01F6YRHYJM6TFMDMPYQKFHDX7M/Biweekly%20%28Every%202%20weeks%29/vote)
[![](https://api.gh-polls.com/poll/01F6YRHYJM6TFMDMPYQKFHDX7M/Monthly)](https://api.gh-polls.com/poll/01F6YRHYJM6TFMDMPYQKFHDX7M/Monthly/vote)

**2. With what frequency are you planning to publish a project update blog?**
[![](https://api.gh-polls.com/poll/01F6YRNC1YXHBS6G4GCFHHPMVT/Weekly)](https://api.gh-polls.com/poll/01F6YRNC1YXHBS6G4GCFHHPMVT/Weekly/vote)
[![](https://api.gh-polls.com/poll/01F6YRNC1YXHBS6G4GCFHHPMVT/Biweekly%20%28Every%202%20weeks%29)](https://api.gh-polls.com/poll/01F6YRNC1YXHBS6G4GCFHHPMVT/Biweekly%20%28Every%202%20weeks%29/vote)
[![](https://api.gh-polls.com/poll/01F6YRNC1YXHBS6G4GCFHHPMVT/Monthly)](https://api.gh-polls.com/poll/01F6YRNC1YXHBS6G4GCFHHPMVT/Monthly/vote)
[![](https://api.gh-polls.com/poll/01F6YRNC1YXHBS6G4GCFHHPMVT/Once%20per%20evaluation)](https://api.gh-polls.com/poll/01F6YRNC1YXHBS6G4GCFHHPMVT/Once%20per%20evaluation/vote)

We are trying to get each student/project assign at least 2 dedicated mentors so the learning process for both students and mentors is qualitative. The Summer of Code programs are virtual internships but with such technological advancements, no one should feel disconnected so we encourage both students and mentors to have weekly calls for 15 mins to 1 hr. It’s up to your mutual convenience, and requirement. 

Students can discuss the blockers, project progress, ideas, plan for next week, etc with mentors, and mentors can give brief feedback to students about their work at regular intervals and not wait until the evaluation cycle to highlight the areas of improvements or appreciate them for their great work :D

**3. Do you think if the above idea of having call on a weekly/biweekly (every 2 weeks) basis would be helpful?**
[![](https://api.gh-polls.com/poll/01F6YS31T1HV61000CA4JX3WBD/Yes)](https://api.gh-polls.com/poll/01F6YS31T1HV61000CA4JX3WBD/Yes/vote)
[![](https://api.gh-polls.com/poll/01F6YS31T1HV61000CA4JX3WBD/No)](https://api.gh-polls.com/poll/01F6YS31T1HV61000CA4JX3WBD/No/vote)
[![](https://api.gh-polls.com/poll/01F6YS31T1HV61000CA4JX3WBD/Not%20Sure)](https://api.gh-polls.com/poll/01F6YS31T1HV61000CA4JX3WBD/Not%20Sure/vote)

----  

Most of the discussion about the project would take place on the Planning issue so that all contributors can refer that, and also it helps in gaining quick context about the topic from the issue body, and past discussion in one place.

But, we understand that there might be things irrelevant to the issue, about the framework, setup, setting-up call, etc so we can decide a channel for that in start so that our communication is clear and no one miss any update. 

**4. By which communication channel you want to interact with your respective project mentors/student, please comment below with Pros/Cons**  [Comment below with the choice, we'll post a poll for this too if required]

- Repository specific channel
- Summer of Code channel
-  General Public Lab channel
-  Project specific channel (Channel dedicated to your SoC project)

Thank you all, please complete this activity as soon as possible so we can have wonderful and seamless collaboration over the summer, and can start instantaneously!

**Comment by daemon1024** [comment]
I would prefer to keep the interaction to General Public Lab channel.
 - Get inputs from the whole community
 - I would love to see various kinds of updates from my colleagues

**Comment by waridrox** [comment]
### Either of _General Public Lab_ channel or _Summer of Code_ channel

- Pros: Open suggestions/discussion of a particular idea, help or implementation.
- Cons: Too many messages may lead to spamming of the General Public Lab channel hence an alternative could be a _Summer of Code_ channel

**Comment by RuthNjeri** [comment]
I agree with @daemon1024, also because if a particular mentor is not available, another mentor who is available can help out or better yet other students can help each other out.

**Comment by jywarren** [comment]
Just quickly noting that we sometimes worry about filling the chat with long in-depth debugging threads or whatever, and perhaps an "in-depth" channel that's still open could be possible to switch to.

**Comment by jywarren** [comment]
Sorry, my last comment was especially because yesterday @icarito and I generated a LOT of chat transcript, flooding the channel. 

**Pro:** 
- there were some people who followed along and helped out
- I think this info being visible was itself a good thing (transparency)

**Con:** 
- it dominates the chat, making other conversations harder to have or to keep up with
- it buries older topics so questions and ideas may get lost
- it may be intimidating to newcomers

This is a tough one to find a balance on!

I wonder if we could encourage a norm of /starting/ all conversations in the main channel, then taking them to one or more secondary channels? Would it feel awkward? Or maybe if we are really transparent and legible about how the channels may be used, people would be able to "follow" a thread into a secondary channel once it moves, and it could be a form of onboarding?

I do think that if deeper/longer conversations started primarily in secondary channels, the main channel might be "left as" a "newcomer welcoming channel" -- that's not a bad thing in itself, but it might not provide invitation and support for newcomers to dig deeper and build knowledge and take more leadership. But, if we regularly divert conversations into secondary channels, maybe it's like a lot of helpful "ladders" extending into them?

**Comment by grvsachdeva** [comment]
**Gist of outcomes from this exercise as of  June 5, 2021, 8:30 pm IST**

> 1. What should be the frequency of the Summer of Code All-Hands call?
Biweekly frequency seems to be the popular choice followed by weekly. The last meeting was very productive, so we may think of keeping it weekly for start and then having a biweekly frequency. Just want to be sure, no one's questions remain unanswered. @jywarren  what do you think?

> With what frequency are you planning to publish a project update blog?
Biweekly frequency looks like a clear winner on this. happy and excited to read project updates from all, and as mentioned it is not a rule, so if you want to publish weekly or take time and post on monthly basis, that's also fine.

> Do you think if the above idea of having call on a weekly/biweekly (every 2 weeks) basis would be helpful?
Great to see that everyone's excited about this one. For this to be successful and a great experience, efforts would be required from both students and mentors, students please reach out to mentors or the general forum whenever you feel stuck. Please decide on the frequency of such calls among yourself and feel free to use Google meets or Jitsi (https://jitsi.org/), which is Open source solution. 

> By which communication channel you want to interact with your respective project mentors/student, please comment below with Pros/Cons
Appreciate all the folks who took time to put their opinion on this one. General Public Lab channel looks like a popular choice as it propagates the true value of Open source, collaboration in the open and everyone is welcome to contribute. But, as some of you suggested, and greatly explained by @jywarren that thread may get lost sometimes due to main channel being open and all contributors coming in, we can have public  Summer of Code channel, where deep discussion can go only after getting started on main Public Lab channel. 

@jywarren what do you think about opening a secondary channel(soc channel) then for extended discussion?

Thanks!!

**Comment by ebarry** [comment]
Noting that @jywarren 's current calendar invite is scheduled for every week

**Comment by jywarren** [comment]
Hi all! Thank you so much @grvsachdeva for running this poll! Much appreciate everyone's input. I'll invite everyone to the `soc` channel for starters. And will assume next week's meeting is OPTIONAL, but I will still be there in case people have questions or want to chat synchronously. Thanks, everyone!

**Comment by jywarren** [comment]
Added everyone! https://gitter.im/publiclab/soc or https://matrix.to/#/#publiclab-software:matrix.org

Thanks!!
