### ISSUE TITLE
hacked code results in -1 likes on front end sometimes

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#97]
The front end is designed with two javascript toggle switches. One will push the like button and one will unpush the like button. Both functions are toggles rather than absolute logic.

Instead of special case handling, I wrote a hack. If you already like the page on page load, it toggles the like button in javascript (as if you didn't like the page and then clicked like), filling in the star and incrementing the like counter artificially. So then the like counter is decremented by 1. If you don't like the page, it acts as though you liked the page but then clicked the unlike button. This action artificially decrements the like counter by 1, so then it increments the like count.
https://github.com/jywarren/plots2/blob/master/app/views/like/_like.html.erb#L81-L89

I just noticed the comments aren't very clear and one is copy/paste without modification. So that's about clear as mud. Yay me.

The two step process seems to pause or get delayed on some systems. Perhaps it'd be better to implement absolute functions for loading the initial setting. I was trying to avoid that with this hack to reduce the places where Like and unLike logic take place.

**Comment by jywarren** [comment]
All good! Haven't seen this in a very long time. Tnx.
