### ISSUE TITLE
Weekly Community Check-In #105 - `>_` Terminal theme configurations 💻

### ISSUE THREAD

**Issue by waridrox** [publiclab/plots2#9703]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## `>_` Terminal theme configurations 

- Customising terminal themes may be one of the coolest things and we would love 💖 to see what all customisations/themes our community is using to possibly draw some inspirations from each other. 💻
- Here's mine for reference :D 
- <img width="480" alt="Screenshot 2021-05-24 at 2 13 00 PM" src="https://user-images.githubusercontent.com/58583793/119321332-27951800-bc9a-11eb-9db1-a67b16ad4bfd.png">
- If you believe in no configuration at all, that's totally fine too! 😄

Cheers ✌️

## This week's focus Issues
These are issues that are of high priority and requests from our
large community that use the software.

https://github.com/publiclab/plots2/labels/high-priority

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note to focus issues contributors
Many thanks to contributors of the past week
🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇
@noi5e, @imajit, @dependabot[bot], @bajajvinamr, @cesswairimu, @dependabot-preview[bot], @Khusyasy
🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** ❤️
Have a great week ahead all 🎈

**Comment by TildaDares** [comment]
@waridox great check-in and your theme choice is really good 🔥. I'm a bit boring 😁 so I don't have any configurations.

**Comment by RuthNjeri** [comment]
Thanks, @waridrox 😃 ....yours looks cool, what theme do you use?

I use the Pi theme and a cool autosuggestion plug in to help in remembering commands for me 😅 

<img width="489" alt="Screenshot 2021-05-31 at 11 28 16" src="https://user-images.githubusercontent.com/7622875/120165084-e2299b00-c203-11eb-8faa-806f22d0478c.png">
<img width="689" alt="Screenshot 2021-05-31 at 11 28 30" src="https://user-images.githubusercontent.com/7622875/120165093-e48bf500-c203-11eb-9232-e42d25aaa7d5.png">
<img width="566" alt="Screenshot 2021-05-31 at 11 31 57" src="https://user-images.githubusercontent.com/7622875/120165096-e5bd2200-c203-11eb-9a4d-7a85cdb37000.png">

**Comment by 17sushmita** [comment]
Thanks @waridrox, very cool check-in!!🥳 Mine is a customized theme. I like this dark and translucent terminal.
and @RuthNjeri  I like your autosuggestion plugin. I will try to install it for mine too😃.

![image](https://user-images.githubusercontent.com/42088159/120169077-30976380-c21d-11eb-9155-d3b1dad497bb.png)

**Comment by Manasa2850** [comment]
Very interesting check-in @waridrox :partying_face: 
I don't have any configuration as of now :sweat_smile:. @RuthNjeri @17sushmita your terminals look really cool. I'll try installing something like that too!

**Comment by waridrox** [comment]
@RuthNjeri, I just use a custom `bash config` to highlight the current branch and folder routes. I might try your auto-completion plugin though ✨:

```
# Git Branch

parse_git_branch() {
   git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

#export PS1="\u@\h \W\[\033[32m\]\$(parse_git_branch)\[\033[00m\] $\n"

# Folder Color

export PS1="\[\033[36m\]\u\[\033[m\] \[\033[33;1m\]\w\[\033[m\]\[\033[32m\]\$(parse_git_branch)\[\033[00m\]\n$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GFh'

```

**Comment by RuthNjeri** [comment]
Thanks @Manasa2850, I use ohmyzsh https://ohmyz.sh/

**Comment by cesswairimu** [comment]
Loving the colorful terminals I will check out some
I user the terminator terminal https://terminator-gtk3.readthedocs.io/en/latest/ that has a range of to customization features 

![Screenshot from 2021-06-05 10-28-06](https://user-images.githubusercontent.com/17081074/120884096-956e0780-c5e9-11eb-8e69-0dbfa52eef4d.png)

great theme @waridox  :tada: :tada:

**Comment by cesswairimu** [comment]
Would anyone like to open next week's check-in?

**Comment by Manasa2850** [comment]
@cesswairimu I would like to!

**Comment by cesswairimu** [comment]
Awesome🎉🎉 thanks @Manasa2850 free to open it on sunday evening or anytime monday. Thanks

**Comment by cesswairimu** [comment]
Hi @Manasa2850 I can't trace the check-in....maybe you created it on another repository, could you please link me to it. thanks

**Comment by cesswairimu** [comment]
no worries, thanks @Manasa2850 ..closing this
