### ISSUE TITLE
Spectral workbench is not working

### ISSUE THREAD

**Issue by samirulkhan** [publiclab/plots2#9707]
Spectral workbench is not working, fix it.

**Comment by jywarren** [comment]
Hi @samirulkhan - thank you for reporting this; we're working on it and will report back in https://github.com/publiclab/spectral-workbench/issues/640 as soon as we know more.

**Comment by jywarren** [comment]
@samirulkhan also just a heads up that things should be working again now on SpectralWorkbench! Thanks for filing the issue.
