### ISSUE TITLE
Add "try the new Rich Editor" message to /post page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#971]
### Relevant URLs

https://publiclab.org/post

Rich editor URL: https://publiclab.org/editor

The /post template is here: https://github.com/publiclab/plots2/blob/master/app/views/editor/post.html.erb

An `<div class="alert alert-success">Text</div>` with the text and link inside would be perfect. 

Perhaps it should say "beta Rich Editor"!

**Comment by sandyvern** [comment]
@jywarren Is anyone working on this one? The fto-candidates need to be written up in first-timer-only format? Creating a new pr or editing this one?

**Comment by jywarren** [comment]
You can make a new one and close this one, or just solve it yourself --
either way! Thanks!

**Comment by jywarren** [comment]
We'll be bypassing this in #1091 -- thank you!!!
