### ISSUE TITLE
Expand our documentation of stable/unstable build servers

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#9718]
We had a great discussion among @publiclab/soc team today about the stable/unstable servers, and realized we could do a lot to better explain them, beyond technically how to use them but to include their purpose, our norms and habits around them, and tips!

Here are some notes we took; it'd be great to have them added to the READMEs: (https://github.com/publiclab/plots2/blob/main/doc/TESTING.md#testing-your-work-with-unstable)

****

```
### Stable server

Purpose of https://stable.publiclab.org

Info:

- `main` branch auto-builds at https://stable.publiclab.org
- "Pre-production"
- Last manual checks before it publishes live
- Last chance to find bugs!
- You can try things out on here - it’s a copy of the database, so you can post “example” or “test” posts and nobody will see on the live site
- No emails are sent
- Build process: merge to main => auto-triggers build of stable.publiclab.org => push to stable branch => publish on live site at publiclab.org
- Passwords are all replaced with "publiclab" for security reasons

### Unstable server

Anyone in the org can push a branch to it - it simulates the live site with the full database
https://github.com/publiclab/plots2/blob/main/doc/TESTING.md#testing-your-work-with-unstable (documentation)

Commands:

Push to unstable branch of publiclab/plots2 to trigger a build:  $ git push -f git@github.com:publiclab/plots2 HEAD:unstable

Monitor all builds at https://jenkins.laboratoriopublico.org/
```

If someone would like to try cleaning these notes up and making them more readable and friendly, I'd super appreciate it!

**Comment by anirudhprabhakaran3** [comment]
@jywarren mind if I take this up? I believe I have to add this information to the TESTING.md file right?

**Comment by RuthNjeri** [comment]
Thanks, @anirudhprabhakaran3, please feel free to take this up and let us know if you have any questions.

**Comment by anirudhprabhakaran3** [comment]
Can anyone push to the unstable branch now? In the previous docs, it's mentioned that only people with write access can do it. Just wanted to confirm once

**Comment by jywarren** [comment]
> Can anyone push to the unstable branch now? In the previous docs, it's mentioned that only people with write access can do it. Just wanted to confirm once

I'm so sorry to have missed this Q! No, only people who have push rights to the publiclab fork can push to unstable.
