### ISSUE TITLE
Feature lead image and first paragraph of text from a wiki page on the corresponding tag index page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#973]
We have great tag-based listing pages, such as:

https://publiclab.org/tag/balloon-mapping
https://publiclab.org/tag/spectrometry

However, they just kind of dump a bunch of recent content from the site onto the page, without much context. But many of these tag names have a corresponding top-level wiki page; for example:

https://publiclab.org/wiki/balloon-mapping
https://publiclab.org/wiki/spectrometry

If, for a given tag listing page, like https://publiclab.org/tag/balloon-mapping, there's a matching wiki page, we should feature the lead image, and the first paragraph of content from that page, at the top of the tags listing, above the graph. 

I think if we showed two columns, with the image to the left and the title and first paragraph to the right, we could do this without sacrificing too much of the page space:

```           
[ image ] [ title          ]
          [ 1st paragraph ]
=====================
[ item ] [ item ] [ item ] [ item ]
[ item ] [ item ] [ item ] [ item ]
```

We could find the wiki page by checking if there's a DrupalNode with the appropriate path: 

```ruby
# controller code:
@wiki = DrupalNode.where(path: "/wiki/#{tagname}"
```

And, though this is just roughly sketched out,  could then use this `@wiki` instance variable to display the relevant content on the tag show page (on this page just before the graph code: https://github.com/publiclab/plots2/blob/master/app/views/tag/show.html.erb#L4).

(as a first step, you could just show the image and title, since the first-paragraph code may be a bit more complex)

```ruby
<!-- view code: -->
<% if @wiki %>
  <!-- some HTML layout code -->
  <%= @wiki.main_image.path if @wiki.main_image %>
  <!-- some HTML layout code -->
  <%= @wiki.latest.title %>
  <!-- some HTML layout code -->
  <%= @wiki.latest.render_body.split('\n').first %>
<% end %>
```

A functional test for this would also be a good independent task; for example, it could copy this test and adapt it to work with a tagname for which we have test fixture data for a matching wiki page: https://github.com/publiclab/plots2/blob/master/test/functional/tag_controller_test.rb#L85-L100

**Comment by ryzokuken** [comment]
@jywarren Would you prefer me breaking this into multiple fto issues or approaching this myself?

**Comment by ryzokuken** [comment]
Also, I suppose you guys are making changes to the `DrupalNode` model. Do I wait for that issue to be solved? (It seems to be far from being merged as it is also a big issue, so maybe I could quickly fix this one first)

**Comment by ryzokuken** [comment]
@jywarren I'm getting a `undefined method `latest' for #<DrupalNode::FriendlyIdActiveRecordRelation:0x007f27488e8890>
`. You sure `@wiki` has a `latest` method?

**Comment by jywarren** [comment]
Don't wait on the DrupalNode changes, we have to work synchronously. 

Oh, add a .first to the end of the `@wiki = ...` line!

Yes it could be broken up or you could do portions yourself... Here's a sketch!!

![tmp_21030-img_20161110_123529127263263](https://cloud.githubusercontent.com/assets/24359/20189532/33c6f33a-a743-11e6-95ab-bf99a10fda20.jpg)

**Comment by jywarren** [comment]
Thanks!

**Comment by ryzokuken** [comment]
@jywarren Exactly what I had in mind. I'd try utilizing bootstrap's responsive grid to make it look better.

Sorry that I hadn't been active for some days, I was busy organizing a Drupal Camp (YAY) but I'm free now and will work on this. Thanks :)

**Comment by jywarren** [comment]
Super and I see and commented on your PR. Sorry I was also unable to help in the past week due to our annual conference (the Barnraising: https://publiclab.org/barnraising). Back now!
