### ISSUE TITLE
[Discussion] Add Bootstrap Tooltips to Location Tags

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#9732]
The [description](https://github.com/publiclab/plots2/issues/9257) for the location tag tooltips task says to add the tooltips to a page like https://publiclab.org/wiki/puerto-rico but I can't find any location tags on that page that need tooltips. The location tags I did find already have tooltips 

<img width="342" alt="Screenshot 2021-06-03 at 12 17 05" src="https://user-images.githubusercontent.com/63427719/120636502-9e35d080-c465-11eb-8413-0825258f9b5b.png">

Should it be in the location tags in the profile page https://publiclab.org/profile/mathildaudufo instead?

@jywarren @cesswairimu @RuthNjeri

**Comment by jywarren** [comment]
Ah, good point. Shall we add an explanatory text to the existing tooltip?

**Comment by TildaDares** [comment]
@jywarren Yeah I think that'll work.

**Comment by TildaDares** [comment]
@jywarren Is this okay?

![image](https://user-images.githubusercontent.com/63427719/120724880-96f5dd80-c4cc-11eb-9d16-ade57d20d5c8.png)

**Comment by Tlazypanda** [comment]
@TildaDares lgtm 🎉
