### ISSUE TITLE
[Enhancement]On home page links in the footer area stand out

### ISSUE THREAD

**Issue by afzal442** [publiclab/plots2#9738]
![c3](https://user-images.githubusercontent.com/11625672/120882479-dcfa9080-c5f5-11eb-9ef9-11fccc33c6c3.JPG)

### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

On the home page, the footer section shows different from other pages' footer which stands out in this sense.
Compare both for more details.

Also, divide the links section into two lists,

![c2](https://user-images.githubusercontent.com/11625672/120882482-dec45400-c5f5-11eb-9278-3fc6fb4fefc7.JPG)

> What did you expect to see that you didn't?

The result should be as below.
![c2](https://user-images.githubusercontent.com/11625672/120882782-82623400-c5f7-11eb-9171-a03ec0bfde75.JPG)

### Please show us where to look

Compare https://publiclab.org/ with https://publiclab.org/wiki/welcome

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by Elukoye** [comment]
@afzal442 can I work on this. ?

**Comment by afzal442** [comment]
Sure you can, let me know if you need any help.

**Comment by afzal442** [comment]
@Elukoye plz draft a PR for this to get some reviews.

**Comment by cgrkzlkn** [comment]
@afzal442 @Elukoye i would like to work on this too, but i am new to this project, it would be great if someone help me with it (which files to change for example). I already installed plots2. As i see now, footer not visible in local development.

**Comment by afzal442** [comment]
Hi @cgrkzlkn, welcome here. 

Could post any screenshot of what you see on your local machine? Thanks.

**Comment by cgrkzlkn** [comment]
Thanks @afzal442 , here is screenshot: 
![plots2_footer](https://user-images.githubusercontent.com/58742393/120917990-cb2ef100-c6ba-11eb-821d-a7c2190421e7.PNG)

**Comment by afzal442** [comment]
Thanks for sharing. Let me work around it!

**Comment by afzal442** [comment]
Hello @cesswairimu! could you help with this?

**Comment by afzal442** [comment]
As I can see footer tag is defined on main page as below:
```css
footer a{
color: #444
}
```

which is not on other pages.

**Comment by afzal442** [comment]
So this makes the difference!

**Comment by cgrkzlkn** [comment]
> As I can see footer tag is defined on main page as below:
> 
> ```css
> footer a{
> color: #444
> }
> ```
> 
> which is not on other pages.

In which file that definition is?

**Comment by Elukoye** [comment]
@cgrkzlkn ,go ahead and work on it ,will look at it and let you know what I think

**Comment by afzal442** [comment]
> As I can see `a` element of footer tag is defined on the main page as below:
> 
> ```css
> footer a{
> color: #444
> }
> ```
> 
> which is not on other pages.

@cesswairimu @Elukoye what do you think?

**Comment by cgrkzlkn** [comment]
@Elukoye Is there any improvement on the subject?

**Comment by afzal442** [comment]
@17sushmita could you help with this?

**Comment by 17sushmita** [comment]
Hi @afzal442, Thank you so much for bringing this out. I just checked out the issue. You are in the right direction about this 

> As I can see footer tag is defined on main page as below:
> 
> ```css
> footer a{
> color: #444
> }
> ```
> 
> which is not on other pages.

But, the issue I can see is that this styling is coming from a CSS library we have imported in `application.css`. So, I'm not sure if we can change/remove these lines. But we can do one thing that we add
```css
footer a {
    color: #007bff !important;
}
```
in our code. This will override the previous styling of `footer a`. Although, this will work if we add this line to application.css, but I'm not sure if it is the most appropriate file to add our code in. You may create a new file and require it in application.css too or you can add it to some other appropriate file. 

See the output below after adding it to our compiled application.css file (on the right)
![image](https://user-images.githubusercontent.com/42088159/121952099-6c800c00-cd79-11eb-937f-973f04394e0d.png)


Hope it helps. Thank you :)

**Comment by afzal442** [comment]
Thanks! That really makes sense. I was also wondering if we can override the CSS property.
Steps to be taken:
Create a file in this folder https://github.com/publiclab/plots2/tree/main/app/assets/stylesheets namely footer.css and include the CSS tag.
And require it in this file https://github.com/publiclab/plots2/blob/main/app/assets/stylesheets/application.css

Or investigate any proper file to add that CSS tag.

**Comment by cgrkzlkn** [comment]
@17sushmita @afzal442  Thanks for help! Now i understand how we'll change the style of the footer.  Is that okay if we add that CSS tag to [style.css](https://github.com/publiclab/plots2/blob/main/app/assets/stylesheets/style.css) ? Other footer elements are in that file too.

**Comment by 17sushmita** [comment]
@cgrkzlkn, Yes, `styles.css` seems good to me. Thank you for investigating!!🎉

**Comment by cesswairimu** [comment]
Great collaboration here :tada: :tada: , thanks so much all and sorry I missed this, This is looking great
