### ISSUE TITLE
Format _tags.html.erb

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#9754]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file `app/views/tag/_tags.html.erb` in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -17,7 +17,18 @@
         <a class="show-more-tags" href="javascript:void(0);"><p style="float:left; color:#666; margin-top:14px; margin-left:5px;"><u><%= tags.length - 2 %> more</u> &nbsp </p></a>
       <% end %>
 
-      <p class="badge <%= badge_name %> pop more-tags" style="display:none;cursor:pointer;margin-bottom:3px;" id="tag_<%= tag.tid %>" data-toggle="popover" data-trigger="focus" data-count=0 data-placement="top" data-content="<p style='text-align:center;'><a href='/tag/<%= tag.name %>'><%= Tag.tagged_node_count(tag.name) || 0 %> notes</a> - <a href='/contributors/<%= tag.name %>'><%= Tag.contributors(tag.name).count %> people <br></a></p><% if tag.location_tag? %><p>This is a geographical tag for placing this content on a map. Please visit our <a href='https://publiclab.org/wiki/location-privacy'>location privacy</a> page. </p><% end %> <p style='text-align:center;font-size:12px;'><%if tag.description %><%= tag.description %> |<% end %> created by <a href='/profile/<%= tag.try(:author).try(:username) %>'><%= tag.try(:author).try(:username) %></a> <%= time_ago_in_words(Time.at(tag.date)) %> ago </p><div class='text-center'><a href='/subscribe/tag/<%= tag.name %>' class='btn btn-primary'>Follow</a></div>" data-html="true" title="<%= tag.name %>">
+      <p 
+        class="badge <%= badge_name %> pop more-tags"
+        style="display:none;cursor:pointer;margin-bottom:3px;"
+        id="tag_<%= tag.tid %>"
+        data-toggle="popover"
+        data-trigger="focus"
+        data-count=0
+        data-placement="top"
+        data-content="<p style='text-align:center;'><a href='/tag/<%= tag.name %>'><%= Tag.tagged_node_count(tag.name) || 0 %> notes</a> - <a href='/contributors/<%= tag.name %>'><%= Tag.contributors(tag.name).count %> people <br></a></p><% if tag.location_tag? %><p>This is a geographical tag for placing this content on a map. Please visit our <a href='https://publiclab.org/wiki/location-privacy'>location privacy</a> page. </p><% end %> <p style='text-align:center;font-size:12px;'><%if tag.description %><%= tag.description %> |<% end %> created by <a href='/profile/<%= tag.try(:author).try(:username) %>'><%= tag.try(:author).try(:username) %></a> <%= time_ago_in_words(Time.at(tag.date)) %> ago </p><div class='text-center'><a href='/subscribe/tag/<%= tag.name %>' class='btn btn-primary'>Follow</a></div>"
+        data-html="true"
+        title="<%= tag.name %>"
+      >
         <a class='tag-name' href='/tag/<%= tag.name %>'><%= tag.name %></a>
         <% if logged_in_as(['admin', 'moderator']) || (current_user && ( current_user.uid ==  @node.uid || current_user.uid == tag.uid)) %>
           <% if tag.name.include? ':' %>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by TildaDares** [comment]
@jdcbautista Would you like to work on this?

**Comment by CYBER-BRIX** [comment]
Hey can you assign this issue to me ,i'm a beginner and would really like to work on this.

**Comment by TildaDares** [comment]
Hi @CYBER-BRIX, this issue has been reserved for @jdcbautista. You can ask for your name to be included in #9083 as a first-timer. Thanks!

**Comment by CYBER-BRIX** [comment]
@TildaDares I have commented ,and please can you assign me some issue related to basic java I'm passionate about coding with java

**Comment by TildaDares** [comment]
@CYBER-BRIX This repo uses Ruby, Html, CSS and JavaScript.

**Comment by CYBER-BRIX** [comment]
i can do Html ,but can you suggest me some other repo i have trying so hard
to find it but i can't please help me finding a maybe a good java repo if
you can or any other first timer reoi is fine with me for html

**Comment by Jgabriel88** [comment]
Hello, I would love to start contributing, I am a new grad from a web development bootcamp and I am looking for opportunities to keep coding!

**Comment by TildaDares** [comment]
You can ask for your name to be included in #9083

**Comment by TildaDares** [comment]
@CYBER-BRIX Are you still interested in working on this?

**Comment by CYBER-BRIX** [comment]
> @CYBER-BRIX Are you still interested in working on this?

YUP

**Comment by TildaDares** [comment]
Great🎉

**Comment by CYBER-BRIX** [comment]
So is this issue assigned to me?

**Comment by TildaDares** [comment]
Yes @CYBER-BRIX
