### ISSUE TITLE
Weekly Community Check-In #106 - Everybody Struggles

### ISSUE THREAD

**Issue by Manasa2850** [publiclab/plots2#9762]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Everybody Struggles

This is theme for this week in Outreachy. As quoted by the Outreachy organizers, "Sometimes the act of writing about what you are struggling with can help you find the answer. When you write about your confusion, you may think of a place you haven't searched for help. When you write about a problem you're stuck on, you may think of a way to fix it. Programmers often call this "rubber duck" debugging".
This week lets share about a time when you were really stuck on an issue and how you got yourself unstuck.

## This week's focus Issues

These are issues that are of high priority and requests from our
large community that use the software. 

https://github.com/publiclab/plots2/labels/high-priority

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note to focus issues contributors
Many thanks to the contributors of last week
:1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: @jywarren @noi5e @TildaDares @cesswairimu @Rutwij12 @KSVSC @imajit @darrylpoh @afzal442 @KarAyushman @anirudhprabhakaran3 @jrogers-dev @Jgabriel88 @icarito :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by jywarren** [comment]
Hi everyone! Thank you so much @Manasa2850 for this check-in! 

@publiclab/soc team - i'd very much like to hear a short (even one-line) update here about what you've been working on, if you're stuck or need input, and also how you're feeling! Please take a short moment to leave a note here each week, i really appreciate it!!! 🌟 

cc @TildaDares @Manasa2850 @17sushmita @daemon1024 @waridrox @imajit

Happy to hear from our mentors as well if you have a moment!! @publiclab/mentors ❤️

**Comment by daemon1024** [comment]
Hey there 👋 I am doing fine 😊, Spent most of the time setting up and digging through old conversation and issues 😅. Currently working on the script to generate layers. Hope to give y'all a demo by the next check-in 🙌

**Comment by TildaDares** [comment]
Hi everyone, I've been working on username autocomplete in comment boxes. It involved a lot of trial and error 😅 but I'm glad everything worked out.

**Comment by imajit** [comment]
Hi! I have been working on improving the UI experience for the translation team. It has lots of tiny changes and some changes require a bit of discussion too.

**Comment by Manasa2850** [comment]
Hi everyone :wave:. I'm doing good :smiley: 
I've finished the tag locking and not displaying tags of banned users tasks (Ref #9694). I'm currently writing tests for them.
Tag locking is not working as expected on the stable website when we use the Chrome browser. Hopefully I'll figure out the issue with this soon!

**Comment by waridrox** [comment]
Hi all! 😃 Recently, I've been working on integrating the new capture interface from `spectral-workbench.js` lib to the `spectral-workbench` app. Thanks to the latest `npm` release by @jywarren 🚀, I can now reliably port the newly updated library.

**Comment by 17sushmita** [comment]
Hi everyone😀,
I'm working on Preventing first-time posters to add tags. I've opened a PR for disabling it from UI (#9770)  and an FTO (#9774) to block requests from backend. Currently, I'm writing tests for them.

**Comment by anirudhprabhakaran3** [comment]
Hello!
I've been trying to make an auto-labeller for PRs, and one PR related to that has also been merged. However, it seems as though there are issues with it and now that's what I'm focussing on.
Other than that, I'm also editing the documentation for the stable and unstable servers. Have to complete that too.

**Comment by Ha-pixel67** [comment]
@anirudhprabhakaran3 the question was asked to the public lab SoC team which includes people selected for gsoc and outreachy. Nobody asked for your comments. Please don't spam here.

**Comment by TildaDares** [comment]
@Ha-pixel67 
@anirudhprabhakaran3 is not a spammer and there's nothing wrong with them sharing how their week is going ❤️

**Comment by Ha-pixel67** [comment]
@TildaDares I appreciate it. But when Jeffrey has so clearly tagged the soc team and the mentors, I really don't think this person @anirudhprabhakaran3 had to come and put a comment and spam here.
I really appreciate the work done by Open Source communities and I'll do my level best to kick out unwanted people like @anirudhprabhakaran3

**Comment by TildaDares** [comment]
@Ha-pixel67 I appreciate your enthusiasm for open source but the kind of language you're using is not acceptable. ❤️ & 💡

**Comment by daemon1024** [comment]
Hi @Ha-pixel67. Appreciate your concern. But this check-in is for the wider community to interact and collaborate.

As stated in the issue description
>  We have a Community Check-In each week, where **every community member** can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️

Looking forward to your check-in as well and would really appreciate if you would help us maintain an inclusive and welcoming environment here.

Here's our [Code of Conduct](https://publiclab.org/conduct#:~:text=Public%20Lab%20is%20dedicated%20to,class%2C%20age%2C%20or%20religion.). It would be great if you can go through it once and maintain the same. 

Thank You.

**Comment by jywarren** [comment]
Thanks everyone. @Ha-pixel67 I understand there's a lot of info in this issue and it may not have caught your eye what our community norms are around the check-in process. @anirudhprabhakaran3 is definitely welcome to offer an update ❤️ ✨  for all the work you've been putting in on troubleshooting our outages, monitoring and such. 

I appreciate everyone's notes on the welcoming tone we aspire to have here and thank you so much for helping @Ha-pixel67 to find and understand our norms. @Ha-pixel67 I'm sure folks will understand as you're getting oriented here and echoing others' comments that we appreciate your enthusiasm too. If you can give a 👍 ,  especially regarding our code of conduct, we will be happy to have your participation. 

All around thank you for the calm and non-judgemental takes from everyone, and I look forward to working together!

**Comment by cesswairimu** [comment]
thanks all  :heart:   :heart:   :heart: 

I would like to thank @KSVSC and @anirudhprabhakaran3 for helping close [some old issues](https://github.com/publiclab/plots2/issues/9637)  :tada: :tada: :tada: :tada: and many thanks to the soc  folks for the ftos you are creating, help with the reviews and the amazing work you are doing :tada: :tada: :tada: :tada:

**Comment by Jgabriel88** [comment]
I would like to stop receiving emails, how can I do it???

**Comment by anirudhprabhakaran3** [comment]
On the right side of the page, under the notifications tab, you'll see an unsubscribe button.

**Comment by cesswairimu** [comment]
Would anyone like to open this coming week's check-in?

**Comment by 17sushmita** [comment]
> Hi all, Would anyone like to open this coming week's check-in?

I would like to open

**Comment by cesswairimu** [comment]
Fantastic  thanks @17sushmita  :tada:  :tada: . Please feel free to open anytime today(monday). thanks

**Comment by 17sushmita** [comment]
@cesswairimu, here it is #9797

**Comment by cesswairimu** [comment]
Thanks @17sushmita 🎉🎉
