### ISSUE TITLE
Differentiate between tags and power tags

### ISSUE THREAD

**Issue by Manasa2850** [publiclab/plots2#9776]
@publiclab/mentors  this is what I've thought of to differentiate between tags and power tags. Please let me know your views on this.

1. Change the location of power tags - currently we add normal tags and power tags in the same place. Instead, we can have another input box for power tags, hovering over which will tell us what a power tag is.
2. Prompt users to enter the type of power tag before adding it - this will help to add the power of the power tag to all the tags on the note and not just the one it is added with. (Ref #6593)

![power_tag_mockup](https://user-images.githubusercontent.com/43354059/121775285-54a35f00-cba4-11eb-84d4-0706aa109492.png)

3. Follow button should appear only on normal tags and not on power tags when not following. (Ref #6593)
4. Different bootstrap style for power tag cards - maybe have a different color and switch over to 'cards' from 'badges'.

**Comment by jywarren** [comment]
Re: item 4, just noting:

powertag display: https://github.com/publiclab/plots2/pull/8684

**Comment by ebarry** [comment]
Great! Nice chatting with you today on the call. 
Regarding: 
1. I see the concept here, but I do not see a need for two input boxes. Perhaps the combination of "+" which expands to the input box could be improved? For instance, this "+" completely disappears once clicked. Might this turn into a "-" after clicking, allowing the user to hide the input box?
<img width="240" alt="Screen Shot 2021-06-15 at 12 28 24 PM" src="https://user-images.githubusercontent.com/161439/122089941-44be9180-cdd5-11eb-9684-b0255a9a9034.png">
The input box 
<img width="261" alt="Screen Shot 2021-06-15 at 12 29 24 PM" src="https://user-images.githubusercontent.com/161439/122090111-6ae43180-cdd5-11eb-9164-2bacc684c259.png">

**Comment by ebarry** [comment]
Ok -- i got more into the history of this project and I more fully appreciate what you've suggested here. Upon reflection, I think my comment from earlier today did not fully meet your question. I think the ideas you're engaging with are a little beyond what we've figured out as of yet. Thank you again for pushing ahead, but i'm wondering if you could give us a couple weeks while some staff / community reps are out of office, and then come back to solve it together in July? Do you have enough on your plate, for example moving on the display issue here https://github.com/publiclab/plots2/pull/8684 ? Please let us know. CC @jywarren

**Comment by jywarren** [comment]
Hi @Manasa2850 and @17sushmita, just let me know if you running low on tasks that can be tackled now, given this one will take a little more brainstorming with community reps!

**Comment by Manasa2850** [comment]
Hi @ebarry and @jywarren. Thanks for the inputs. For this week, I'll work on
1. Display suggestion made by Liz - having a `-` button.
2. Display issues mentioned in #6593 and #8684 
3. Follow button should appear only on normal tags and not on power tags when not following.

For the other sub-issues, we can come back later and work on it when we have some more clarity!

**Comment by jywarren** [comment]
Hi @Manasa2850 thanks! I think that for now the switch between (+) and (-) is not completely necessary. There are some challenges visually to how to make it clear that (-) hides the input box. (and it should really be (x)) So I think we should hold off on that for now. 

One thing you may be able to help with if you're looking for additional tasks related to powertags, is [this complex one](https://github.com/publiclab/plots2/issues/9698#issuecomment-865381336) suggested in @daemon1024's project, where there is a little overlap with yours. There is a need for a button to prompt people to add their location if they haven't already, just like we do [on the new dashboard](https://publiclab.org/v2/dashboard/). 

Also, while I think the changes in #9822 look great, i do want to note that this could mean people wouldn't follow tags like `question:general` so i wanted to get a final confirmation from @publiclab/community-reps on this. I think we should wait until @ebarry is able to get back to us about this before merging that. 

But no worries, there's plenty to do. I'll start digging into things to identify more and of course #8684 is a big one!

**Comment by Manasa2850** [comment]
As discussed in today's call, I'll implement the following things for now

- [ ] Swap the colors of the normal tags and power tags.
- [ ] Hovering over the power tags should display 'Power Tag'.

**Comment by ebarry** [comment]
Hi Manasa, 
The tagging sidebar continues to look better and better with your contributions! thank you!

I'm writing to say i'm still in support of the hover-over tooltip on power tags. 

* Where the power tags show in the grey box, the entire grey box might have a tooltip. Do you think that could work?
* for the small lozenge tags, i am thinking that the way the sentence `This is a power tag.` has the same link target as the number of notes and contributors is a little confusing. If there's going to be link text stating `This is a power tag` perhaps that could link directly to https://publiclab.org/wiki/powertags so that people can learn about what powertags are. Or, perhaps the link text is overdone, and figuring out how a hover tooltip could work might reduce the issue with this information being presented as a link? 

![tag-tooltips](https://user-images.githubusercontent.com/161439/127002611-e6793d41-910e-42e5-90f6-7b1c850ef676.gif)

**Comment by jywarren** [comment]
- small icon (i) explaining power tags?
- `--------- POWER TAGS (i) ---------` divider above this section?
- idea for dropping small "badge" style in favor of larger grey box style for power tags, but also remove "# following" (or move it into menu)

link to a design reference for some of these: #6593
