### ISSUE TITLE
Change caption of Ask a question button in research note 

### ISSUE THREAD

**Issue by ananyo2012** [publiclab/plots2#979]
Hi, this is a `first-timers-only issue`. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!
## The Problem
Take an example research note like https://publiclab.org/notes/liz/10-26-2016/add-reviewers-to-a-language. The caption in the "**Ask a question**" button needs to be changes there since the button links to the question post page with related tags attached to that note. So the Button should show something like "**Ask a related question**" and with a question mark icon beside it instead of an pencil icon. Also the tooltip should show something like "**Ask a question about _topic_**" 

## Solution

See this line https://github.com/publiclab/plots2/blob/master/app/views/sidebar/_related.html.erb#L8. You need to change the title attribute in the `a` tag with the suitable message to change the tooltip. To change the Caption of the button you need to change the locale parameter `ask_a_question` and also change its corresponding Deutsch translation.  You find the locale for the view in https://github.com/publiclab/plots2/tree/master/config/locales/views/sidebar/_related

## Steps to Fix
- [ ] claim this issue with a comment
- [ ] set up a repository locally and make sure that all tests pass
- [ ] Discuss the final caption for the button
- [ ] start a pull request (see contributing to Public Lab software) but mark it as "in progress"
- [ ] fix the issue following the steps above
- [ ] try the manual test listed above
- [ ] make sure all tests pass with rake test
- [ ] alert someone via either the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by DanielGeoffreyHodgkins** [comment]
I found this project through https://twitter.com/yourfirstpr looking to do some open source development, would it be possible to claim this issue?

**Comment by jywarren** [comment]
We'd love your help on this and are happy to offer any assistance you might need. Thanks a lot!

**Comment by mridulnagpal** [comment]
I would like to work on this issue

**Comment by jywarren** [comment]
Hi, @mridulnagpal - it looks like you've found some other issues to work on -- let's let @DanielGeoffreyHodgkins take a bit longer on it. @DanielGeoffreyHodgkins - happy to help if you've gotten stuck or need any pointers. Thanks!

**Comment by DanielGeoffreyHodgkins** [comment]
Hi, @jywarren my workload has ramped up in recent days and I don't think I'll be able to get round to this in reasonable time. Sorry for wasting your time!

**Comment by Pk13055** [comment]
Is this issue still up for grabs?

**Comment by jywarren** [comment]
I believe so -- and @DanielGeoffreyHodgkins, no waste of time at all, good
luck with your work and if you find yourself with more time, we'd love to
see you again sometime. Thanks!

**Comment by kadosa** [comment]
Hi! I'd be happy to pick this one up, if Pk13055 is not working on it already..

**Comment by jywarren** [comment]
Please do -- we haven't heard back yet. And anyone who's still looking for issues, many of these are close to `first-timers-only` type issues, but are either lacking formatting or a few extra bits of info. 

https://github.com/publiclab/plots2/labels/fto-candidate

I'm happy to fill in the blanks if you find one that you like.

**Comment by kadosa** [comment]
Ok, I've forked the repo and got everything set up. Now just need to figure out the right copy. I think 'Ask a related question' and 'Ask about $topic' is fine. Not sure how you go about selecting the correct German translation, I speak the language but I'm not native. My proposition would be 'Stellen Sie eine verbundene Frage' and 'Fragen Sie anderen bezüglich $topic'. 

The current code does not provide translation for the tooltip caption, so I'd suggest adding it to the locale yaml file.

**Comment by Pk13055** [comment]
I'm sorry, I was shifting town. I've changed the caption, but can't seem to find the tooltip text

**Comment by jywarren** [comment]
A pull request was submitted in #1041 and is under review, thanks!
