### ISSUE TITLE
Change limit and cache expiration date on recently active users query

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#9796]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### ❓Problem

Public Lab comment boxes now show you a list of recently active users when you type `@` just like Github does. You can test it out here https://stable.publiclab.org/ 

https://user-images.githubusercontent.com/63427719/121555040-8ed8f900-ca0a-11eb-82fe-e58b37a24c5d.mov

Presently the limit on the query that fetches the recently active users is `5` and the cache expires every 24 hours. These things need to change and that's why I need your help

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file `app/models/user.rb` in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
@@ -505,8 +505,8 @@ class User < ActiveRecord::Base
     recent_locations.last
   end
 
-  def self.recently_active_users(limit = 5, order = 'last_updated DESC')
-    Rails.cache.fetch('users/active', expires_in: 24.hours) do
+  def self.recently_active_users(limit = 15, order = 'last_updated DESC')
+    Rails.cache.fetch('users/active', expires_in: 1.hour) do
       User.select('rusers.username, rusers.status, rusers.id, MAX(node_revisions.timestamp) AS last_updated')
         .joins("INNER JOIN `node_revisions` ON `node_revisions`.`uid` = `rusers`.`id` ")
         .where("node_revisions.status = 1")
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by TildaDares** [comment]
@phyleria Would you like to work on this?

**Comment by virtualpathum** [comment]
Im a first timer. Can I fix this?

**Comment by TildaDares** [comment]
Hi @virtualpathum, thank you for the interest but this issue is reserved. You can ask for your name to be included in the list of first timers here #9083. Thanks :)

**Comment by phyleria** [comment]
Yes I would, thank you

**Comment by cesswairimu** [comment]
Hey @phyleria, please let us you if you are stuck in any way here or there is any way we can help. Thanks

**Comment by phyleria** [comment]
Hi @cesswairimu , yes I would  appreciate some help.

**Comment by cesswairimu** [comment]
cool,  after forking the project navigate to this file `app/models/user.rb`  and update the lines outlined on step 2 of  the [issue description](https://github.com/publiclab/plots2/issues/9796#issue-920288772)  (replace the lines marked in red with the green ones) you could do this locally or refer [to this]( https://help.github.com/articles/editing-files-in-your-repository/) to edit on github  directly ...makes sense?

**Comment by phyleria** [comment]
Yes, that makes sense, and I’ve completed it. Thanks for your help!

**Comment by TildaDares** [comment]
Hi @phyleria Do you need help with this?

**Comment by phyleria** [comment]
Hi, yes. I tried creating a pull request but it didn't pass the tests.

**Comment by TildaDares** [comment]
@phyleria Was it after creating the PR that the tests didn't pass on GitHub or you're talking about the tests you ran locally?

**Comment by phyleria** [comment]
That was before I created the PR

**Comment by TildaDares** [comment]
@phyleria Create the PR and we'll deal with the failing tests together.

**Comment by phyleria** [comment]
I have already created the PR

**Comment by cesswairimu** [comment]
Solved in https://github.com/publiclab/plots2/pull/9857. closing this. Thanks all
