### ISSUE TITLE
Weekly Community Check-In #107 - Cheat Days are Important!!

### ISSUE THREAD

**Issue by 17sushmita** [publiclab/plots2#9797]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Cheat Days are Important!! 

In our generation, it is seen that hustling and burning out yourself is very important to become successful. We, developers often enjoy coding and working day and night on an issue when we struggle. Working like hell may bring compliments, applause and maybe success from all corners of the world but it will exhaust you physically, mentally and most importantly emotionally. That is why having cheat days to break our daily coding routine and get indulged in some fun activities becomes very important to have a peaceful mind. Also, we know 'Everybody Struggles' (last week's check-in), therefore, many times, it becomes very important to think in a different way about the problem and cheat days help us have a peaceful mind to start afresh.

So, this week, let's share what you all do on your cheat days or some new ideas to make our cheat days more meaningful.

**For example-**
I love painting and enjoy my day by indulging in new artwork when I feel like struggling over some issue. It helps me to be creative and think in a different way and most of the times I end up finding some new approaches to start over. Also, I'll be happy to share some of my paintings if you want😉(although I'm still an amateur😅)

Excited to know some interesting ideas for you all🤩
## This week's focus Issues

These are issues that are of high priority and requests from our large community that use the software. 

https://github.com/publiclab/plots2/labels/high-priority

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note to focus issues contributors
🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇
@TildaDares @anirudhprabhakaran3 @icarito @noi5e @eightballocto @waridrox @Manasa2850 @afzal442 @cesswairimu @darrylpoh @afzal442 @KarAyushman @jrogers-dev
🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇

## Next Check-in
If you would like to open the next check-in. Leave a comment below. We are happy to help if it's your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by Ha-pixel67** [comment]
Haramkhor @anirudhprabhakaran3

**Comment by Ha-pixel67** [comment]
@waridrox kyu be?

**Comment by Ha-pixel67** [comment]
@anirudhprabhakaran3 sala

**Comment by Ha-pixel67** [comment]
Abey kya kar rahe ho

**Comment by Ha-pixel67** [comment]
Sala @anirudhprabhakaran3

**Comment by Ha-pixel67** [comment]
Dekh lunga teko

**Comment by Ha-pixel67** [comment]
@17sushmita behen yeh sala @anirudhprabhakaran3 ko kyu special mention??

**Comment by Ha-pixel67** [comment]
Aaja aaja main hoon pyaar tera

**Comment by waridrox** [comment]
@Ha-pixel67, Folks who contribute to the codebase of Public Lab get featured in the weekly check-in...If you do it too, you will also get featured.

**Comment by Ha-pixel67** [comment]
Haan ji bhaiyya main bhi comment kiya. Mujhe bhi dedo na special mention

**Comment by jywarren** [comment]
Hi folks! @17sushmita I really appreciate this topic. It's not even cheating -- how can we do good work if we don't take care of ourselves! It's so cool to know you are a painter! 🎨 🎨 🎨  I'd love to see your paintings!!

I like riding my bike on a day off, having a picnic, reading a book under a tree. 

I think i need to do that -- been a bit too busy recently! 

This week i'll be focused on this switch to Google Storage, to address our outages, in collaboration with @icarito: https://github.com/publiclab/plots2/issues/9760#issuecomment-861701120

(also noting that Ha-pixel67 was banned above for violation of our code of conduct. Thanks to everyone for your understanding and help.)

**Comment by daemon1024** [comment]
Hey Folks,

Cheat Days are definitely important. I mostly spent my cheat days sight seeing, but nowadays it's mostly listening to music or playing games with friend 😃 

I spent my week organizing and prioritizing things. I was a bit overwhelmed by the things I could do and I had put my hands in a lot of directions. A chat with @jywarren helped me figure out a lot of things and I am hopefully in the clear now 🚀

**Comment by 17sushmita** [comment]
Hi everyone,

I worked on the subscription stats query bug this week and writing tests for it now. Also, I'll collaborate with @Manasa2850 to divide further tasks this week and need some community input to move ahead.

> Hi folks! @17sushmita I really appreciate this topic. It's not even cheating -- how can we do good work if we don't take care of ourselves! It's so cool to know you are a painter! 🎨 🎨 🎨  I'd love to see your paintings!!

Thanks, @jywarren, and apologies for checking the comment late. I mostly like to do nature paintings. These are some of my paintings which I do in my free time.
<img src="https://user-images.githubusercontent.com/42088159/122676265-02dd8300-d1fb-11eb-8a4a-e926b7a54cd9.jpg" width=230 ><img src="https://user-images.githubusercontent.com/42088159/122675799-ad07db80-d1f8-11eb-823b-3be3bef67810.jpg" width=340>  <img src="https://user-images.githubusercontent.com/42088159/122676038-bba2c280-d1f9-11eb-9408-b2e31a078408.jpg" width=230>

**Comment by waridrox** [comment]
Woah!!!!! 😧 These paintings are so true to life 💯 You have some great artwork skills @17sushmita!

Hi all, 
So, I've finally managed to make the capture code work on both the old and the new `/v2` URL for Chrome and Firefox and will be pushing it soon on unstable to check for breaking changes if any 🤞. I'm still not able to figure out how to get it work on Safari tho :( Might need some help here...

Talking about the cheat days/moments, I mostly resolve to solving Rubik's cube puzzles 😄 / playing piano 🎹 occasionally / listening to songs.

**Comment by cesswairimu** [comment]
Hi everyone,  Great theme and beautiful paintings @17sushmita  :tada: :tada:  I feel  like the theme was not fully exhausted because of the moderation we had to do last week..thanks everyone for getting on top of it..maybe we could keep this check-in for another week ? What do folks think? 

I mostly take walks or read fiction when I am feeling overwhelmed

**Comment by jywarren** [comment]
@17sushmita i love these paintings!! Especially the reflections and water effects. 

@waridrox what kind of piano do you play? I also play a bit! mostly things i hear, or a little old jazz.

@cesswairimu i wanna know, what do you like reading?

****

Since we're keeping this one open another week, i wanted to share -- i asked folks in today's Outreachy/GSoC call what they hope to learn more about in the coming weeks -- what topic -- and here's what people shared. Feel free to reply with some resources, or @publiclab/soc mentors in particular look out for how to help folks get into these topics!!

### Topics we’d like to learn about

* Manasa: UI/UX (jeff!) (Sudipto)
    * https://publiclab.org/notes/warren/05-07-2019/introducing-a-draft-style-guide-for-public-lab 
    * this is always a tough one -- and doesn't always fit into GitHub well as a process! I personally like to sketch on paper a lot. But I also love drag-and-drop UI builders, and modularity: https://froala.com/design-blocks/, https://www.layoutit.com/, 
* Mohammad: Rails gems (packaging spectral-workbench.js to a rails gem)
    * this was new to me, but I did this a couple years ago with @icarito: https://github.com/publiclab/mapknitter-exporter and it was fun!
* Ruth: congrats! - Finishing up on pending courses (Writing well, and Top performer by Scott Young)
* Tilda: testing – in general, SQL!
  * do you like writing SQL directly, or what parts of SQL are you interested in? 
* Sushmita - testing/mocking, publishing gems (did in python) (Manasa)
    * also yes, check out this gem i built a couple years ago with @icarito: https://github.com/publiclab/mapknitter-exporter 
* Ajit - production - what happens after code gets pushed? (barun)
    * @icarito knows this the best, but we use Jenkins to automate publication in containers. Our Jenkins setup is at https://jenkins.laboratoriopublico.org/ - you can see all our systems building there! And we use a complex set of dockerfiles and docker compose files to systematize publication. 
* Barun - optimization - all kinds (jeff!)
    * i had shared this tutorial and amazing explanation of "debounce" timing: https://css-tricks.com/debouncing-throttling-explained-examples/
* Sudipto - Progressive web application PWA
    * aha! We use these a bit - in https://github.com/publiclab/image-sequencer/, and I think we used to in Spectral Workbench!
* Jeff - React (Sudipto, barun) 
    * i found this recently which was cool: https://utopia.app/ (WYSIWYG React editor???)

Let's all help one another build our skills as we go here! Thanks, all!

**Comment by cesswairimu** [comment]
@jywarren short fiction novels..the last one I read was 'Turtles All the Way Down'

hi all, would anyone like to open next week's check-in?

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/9866. Thanks all
