### ISSUE TITLE
[Discussion] Refine design of co-authored posts on profile pages

### ISSUE THREAD

**Issue by TildaDares** [publiclab/plots2#9798]
Presently coauthored posts are displayed separately from normal posts as seen here https://publiclab.org/profile/warren. I suggested changing the query that gets a user's posts (notes, questions and wikis) to also include co-authored posts.

```
def find_posts_by_type(type = 'note')
  coauthored_tag = "with:" + name.downcase
  
  Node.where(type: type).where('node.uid = ? OR term_data.name = ? OR term_data.parent = ?', uid, coauthored_tag.to_s, 
  coauthored_tag.to_s).order('created DESC')
end

```
What does the community think?

@jywarren @RuthNjeri @cesswairimu

**Comment by RuthNjeri** [comment]
Hi @TildaDares, thanks for sharing your idea. What would be the benefit of this? I guess I am also curious about the initial decision on not including the co-authored posts, maybe @jywarren or @ebarry can shed light on that.

I do see the option of accessing co-authored posts on the sidebar
![Screenshot 2021-06-20 at 13 06 37](https://user-images.githubusercontent.com/7622875/122670028-8f228280-d1c8-11eb-9e95-201ed765686c.png)

**Comment by jywarren** [comment]
Fetching the co-authored posts is a less efficient database query, unfortunately, because we don't have a many-to-many relationship between nodes and users. The `with:USERNAME` powertag serves as our join table, but fetching it is not super efficient. So we've kind of avoided doing this as the default. @TildaDares do you see a way around it or think the performance won't be too bad? Thanks for thinking on this! Maybe we need to leave a comment somewhere to explain this too!

**Comment by TildaDares** [comment]
@jywarren I don't see any workaround that would be more efficient.

**Comment by jywarren** [comment]
Hi Tilda! If you are interested in taking this one up, i think the next steps were:

1. think about/take notes on the potential performance impact of a dual query
2. try some load tests in the Rails console?
3. Try making the change and pushing it to unstable for speed tests in the dev console Network pane
4. think about how best to document this change and make future developers aware of how it works
5. make a final decision

How does that sound?

**Comment by TildaDares** [comment]
Sounds good @jywarren.

**Comment by TildaDares** [comment]
Sounds good @jywarren.

**Comment by TildaDares** [comment]
@jywarren I looked at the [response time](https://www.skylight.io/app/applications/GZDPChmcfm1Q/recent/6h/endpoints/TagController%23show_for_author?responseType=html) on skylight and it has a typical response of `342ms` which I think is manageable considering that we don't have a many-to-many relationship. 

Also, going with my initial plan of including co-authored posts with regular posts would mean fetching all of the user's notes (including co-authored posts) first before being able to get the all of the user's question and that wouldn't improve the efficiency. For now, I think it'd be best to leave the posts as is.

**Comment by jywarren** [comment]
OK, I think that sounds good. Thank you for looking into it, @TildaDares !
