### ISSUE TITLE
cached_likes don't stay in sync with the true state of the likes

### ISSUE THREAD

**Issue by btbonval** [publiclab/plots2#98]
How to check for and fix synchronization issues directly in the database:
https://github.com/jywarren/plots2/issues/129#issuecomment-18475514

``` SQL
CREATE VIEW view_node_like_count AS SELECT node_selections.nid, sum(liking)
AS num_likes, cached_likes, title FROM node_selections, node WHERE node.nid
= node_selections.nid GROUP BY node_selections.nid;

SELECT * FROM view_node_like_count WHERE cached_likes <> num_likes;

UPDATE node,view_node_like_count
SET node.cached_likes = view_node_like_count.num_likes
WHERE
node.nid = view_node_like_count.nid AND
node.cached_likes <> view_node_like_count.num_likes;
```

There are still problems with synchronization. I resynchronized cached_likes earlier today.

Snippet from a relevant comment (https://github.com/jywarren/plots2/issues/129#issuecomment-45666057):
A particular user was associated with 25 like mismatches (in the top 5 mismatches), but that user has almost no association with the site in 2 years and the profile indicates no likes at all. The database suggests the user hasn't logged in since August 2013, but the last synchronization happened after that.

I just checked, the id is the same in users and rusers (checking in case the wrong id was being used to update likes)

**Comment by ananyo2012** [comment]
@jywarren Can you verify that this isn't happening now?

**Comment by jywarren** [comment]
We need a more comprehensive overhaul of comment tallying, and I've written this up here: 

https://github.com/publiclab/plots2/issues/607#issuecomment-257211982

I'll close this here and elaborate there.
