### ISSUE TITLE
Change DB schema from using parsed to native column

### ISSUE THREAD

**Issue by icarito** [publiclab/plots2#980]
Changed the DB schema in Node to point at the native column name instead of alias.

Solr is having issues with the (huge) users database in production and this has been identified as related.

Part of the problem may be that it's not really an alias - it does some extra timestamp parsing:

https://github.com/publiclab/plots2/blob/ceb7d05404b4619c7fa8cd8cae5e8215798cb02c/app/models/node.rb#L270-L272

I.e. this line would become "changed" -- 

https://github.com/publiclab/plots2/blob/ceb7d05404b4619c7fa8cd8cae5e8215798cb02c/app/models/node.rb#L28

@jywarren suggested this might be a `good first-timers-only` task. It's related to general issue of 

https://github.com/publiclab/plots2/issues/956

**Comment by icarito** [comment]
When trying the naive approach of replacing `updated_at` for `changed` in `drupal_node.rb` like this:
```
+++ b/app/models/drupal_node.rb
@@ -25,7 +25,7 @@ class DrupalNode < ActiveRecord::Base                                                                                            text :body do
       body.to_s.gsub!(/[[:cntrl:]]/,'')
     end
-    time :updated_at
+    time :changed
```
I get the following error when reindexing:
```
[################################                                                    ] [322850/845573] [ 38.18%] [02:34] [04:10] [  2085.76/s]rake aborted!
ArgumentError: changed is not a multiple-value field, so it cannot index values []
```

**Comment by morrme** [comment]
The files seem to have been changed since this issue was created.

**Comment by jywarren** [comment]
Closing this -- we no longer use Solr! Thanks!
