### ISSUE TITLE
Map page showing error

### ISSUE THREAD

**Issue by ananyo2012** [publiclab/plots2#981]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled.

### What happened just before the problem occurred
When I try to open the page 2 in maps index page it shows an error

### Relevant URLs
https://publiclab.org/maps?page=2

### PublicLab.org username
ananyo2012
(to help reproduce the issue)

### Browser, version, and operating system
Google Chrome on Ubuntu 16.04 LTS

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment]
Here's the error! (mixed up with some other errors in the logs) -- should be a pretty easy first timers issue by adding a test for `if node.map` before using `node.map.authorship`

```ruby
Started GET "/maps?page=2" for 184.186.1.179 at 2016-11-14 23:37:16 +0000
Processing by MapController#index as HTML
  Parameters: {"page"=>"2"}
Started GET "/notes/eustatic/09-06-2014/reference-bay-denesse-and-plaquemines-bayou-aerial-photo-history-2" for 98.185.50.69 at 2016-11-14 23:37:16 +0000
Processing by NotesController#show as HTML
  Parameters: {"author"=>"eustatic", "date"=>"09-06-2014", "id"=>"reference-bay-denesse-and-plaquemines-bayou-aerial-photo-history-2"}
  Rendered map/_maps.html.erb (1010.9ms)
  Rendered map/index.html.erb within layouts/application (1613.9ms)
Completed 500 Internal Server Error in 1615.3ms

ActionView::Template::Error (undefined method `authorship' for nil:NilClass):
    6:     <% end %>
    7:     <h4><a href="<%= node.path %>"><%= node.title %></a></h4>
    8:     <p style="color:#888;"><small>
    9:       by <a href="/profile/<%= node.map.authorship %>"><%= node.map.authorship %></a> 
    10:       <% unless !node.map || node.map.captured_on == "" %> <%= time_ago_in_words(node.map.captured_on) %> ago<% end %>
    11:       | <a href="<%= node.path %>#comments"><i style="color:#888;" class="fa fa-comment-o"></i> <%= node.comment_count %></a>
    12:       | <i style="color:#888;" class="fa fa-star-o"></i> <%= node.likes %>
  app/views/map/_maps.html.erb:9:in `block in _app_views_map__maps_html_erb__1202309236321258068_48797540'
  app/views/map/_maps.html.erb:2:in `_app_views_map__maps_html_erb__1202309236321258068_48797540'
  app/views/map/index.html.erb:73:in `_app_views_map_index_html_erb__1037644138890094631_1198127
```

**Comment by 500swapnil** [comment]
I

**Comment by 500swapnil** [comment]
I would like to work on this issue

**Comment by jywarren** [comment]
Super, yes please! And happy to help.

**Comment by 500swapnil** [comment]
How do I test locally, the changes I have made?

**Comment by 500swapnil** [comment]
PR #1019

**Comment by jywarren** [comment]
Completed, thanks! 🎉
