### ISSUE TITLE
Standardize tooltips on row of icons

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#9812]
**Please describe the desired behavior.**
Describe the solution you'd like.

I'd like to see consistency in the tooltips on this series of icons: 
![inconsistent-tooltips](https://user-images.githubusercontent.com/161439/122126709-20c47580-ce00-11eb-8637-aa7d2b1db841.gif)

**Additional context (optional)**
Feel free to include any applicable: code, screenshots, or gifs.

This occurs on all notes and all wikis. 

Thank you for reading!

**Comment by TildaDares** [comment]
@ebarry Would you like a tooltip added to the edit button?

**Comment by ebarry** [comment]
Yes, it would be great to have a tooltip added to the edit button, maybe keeping in mind that not all users will have access to that feature as we are discussing in https://github.com/publiclab/plots2/issues/9888. 

Also, can the tooltip on Tools appear **above** the icon like the other tooltips do in relation to their icons?

**Comment by ebarry** [comment]
Thanks @Manasa2850 !!!!!!!
