### ISSUE TITLE
Is there a comprehensive map of all stitched maps?

### ISSUE THREAD

**Issue by shanlter** [publiclab/plots2#984]
### What happened just before the problem occurred

I need to see the multiple maps that i have stitched, and others have stitched, together on a single map. 
I visited publiclab.org/archive. There are two problems with this overview map: The map markers are out of date (don't show more recent maps), and the "map of maps" does not show the actual aerial maps. 

I need to see all the aerial maps together on one map. How can we have this?

### Relevant URLs

https://publiclab.org/archive

### PublicLab.org username

shantler

**Comment by jywarren** [comment]
Would you like to see them as "dots" on a map, as the current /archive page
shows? I think we could do this on MapKnitter.org without too much trouble,
but there'd be lots of maps that are only partially complete, as it's hard
to tell when authors consider them "complete" -- what do you think?

Also, with some hundreds of maps, would we want to show every one, or just
the most recent 100 or so? (for performance reasons?)

**Comment by jywarren** [comment]
I wanted to ask @ebarry if there is additional info on this, or a proposed "first step forward"? Thank you!

**Comment by jywarren** [comment]
There are 2186 completed maps on MapKnitter at the moment (exported), and we list 8,568 total. I don't think this is feasible to display on a single map, but we could zoom in pretty far, and show a smaller set -- and perhaps show the most recent 100 within the current view? 

See how we allow listing of maps by region -- this one has about 125 in the NYC area: https://mapknitter.org/map/region/New-York-New-Jersey?minlon=-74.33&minlat=40.48&maxlon=-73.54&maxlat=41.04

We could use that code:

https://github.com/publiclab/mapknitter/blob/master/app/controllers/maps_controller.rb#L143-L150

To make a new RSS feed for regions:

https://github.com/publiclab/mapknitter/blob/master/app/controllers/feeds_controller.rb

Then limit that to 100, so we get no more than the most recent 100: `.limit(100)`

Then, we could make an inline tag that replaces `[map:https://mapknitter.org/feeds/region?minlon=-74.33&minlat=40.48&maxlon=-73.54&maxlat=41.04]` with a Leaflet webmap of that area, anywhere on PublicLab.org. 

Is that something you'd like us to look at, or that you could help out with? 

Also pinging @ebarry and @steviepubliclab

**Comment by jywarren** [comment]
OK, so I did a test and there are over 4000 maps that have at least one image. You can now browse them here:

https://mapknitter.org/map/map

This can now be embedded, but it is a heavy load on many computers. 

I'd do more screenshots but it's breaking my computer!

![screen shot 2017-01-11 at 3 23 06 pm](https://cloud.githubusercontent.com/assets/24359/21864945/efea8d02-d811-11e6-8f36-5927be3e0f38.png)

**Comment by ebarry** [comment]
Wow this is great! Does anyone know the status on open aerial map (or contemporary version of that project) which was serving out our actual archive of the imagery itself?

**Comment by shanlter** [comment]
I am so terribly sorry that I started the question, but missed all your replies since I didn't login github. This is awesome! I checked the maps in China, something wrong, I report  here:
https://mapknitter.org/maps/testt fake image
https://mapknitter.org/maps/kunlun3 fake image
https://mapknitter.org/maps/test1--11 fake image
https://mapknitter.org/maps/hailongtun--4 fake image
https://mapknitter.org/maps/test-parking-led wrong position or fake image.

https://mapknitter.org/maps/test--108  wrong location showed in Jiangsu in "comprehensive map", but actually in USA when I open it.
https://mapknitter.org/maps/easton-park wrong location showed in Jiangsu in "comprehensive map", but actually in TX, USA when I open it.
https://mapknitter.org/maps/xindu  wrong location showed in Sichuan in "comprehensive map", but actually in Paris when I open it.
https://mapknitter.org/maps/test--77 wrong location showed in Sichuan in "comprehensive map", but actually in LA when I open it.
https://mapknitter.org/maps/28jun2012-aldwell-south-river-right wrong location showed in Shanghai in "comprehensive map", but actually in USA when I open it.
https://mapknitter.org/maps/this-is-just-a-test wrong location showed in Tibet in "comprehensive map", but actually in Nigeria when I open it. the user layer can not correctly display as well


https://mapknitter.org/maps/xiangshan This maybe real!!! who is this warrenwyf guy?

**Comment by jywarren** [comment]
There is indeed a lot of fake stuff, but it's hard to screen that out. We could try showing only maps by non-anonymous users, would that help?

**Comment by jywarren** [comment]
OK, I"m going to try not showing anonymous authors. Let's see if it runs in the change I just submitted in #234, and I can publish it if so. Thanks!

**Comment by jywarren** [comment]
Closing this now, and it'll be addressed in publiclab/mapknitter#234. Thank you!
