### ISSUE TITLE
[Discusssion] Import translated strings from Transifex

### ISSUE THREAD

**Issue by imajit** [publiclab/plots2#9859]
Part of #9686 
**Importing Translations**
Transifex allows project integration with github repository. We need to install Transifex app to Public Lab Github organisation and then authorize it. This would keep resources up-to-date by syncing the content on regular basis. 
After setting up the integration, we can also automate the merging of strings using Transifex bot. It pulls changes in the repos and pushes translations based on preferences. Here is a snap of available options to push translations.
![GitHub_WebHooks_updated](https://user-images.githubusercontent.com/38528640/123513341-614aab80-d6aa-11eb-93bd-e2f8fdae2e46.png)
We can also sync existing files.
More about it here https://docs.transifex.com/transifex-github-integrations/github-tx-ui

**Pre-translation Workflow**
We can active Translation Memory Fill-up, this helps us in having consistent translations and also helps in cases where there is repetition in strings. How it works is, lets say we have "Its hot and humid in India" translated, then if there exists another string similar to this like "Its hot and humid in Africa" Transifex Memory fills in the translation based on some fuzzy matching logic,we can then review the pre-filled translation and add the one that match. 
More about Translation Memory and how it works here https://docs.transifex.com/translation-memory/tm-introduction 
![Screenshot 2021-06-26 19:15:30](https://user-images.githubusercontent.com/38528640/123514922-e934b380-d6b2-11eb-959f-dec7e82c03c4.png)

**Comment by imajit** [comment]
@jywarren @ebarry @grvsachdeva

**Comment by jywarren** [comment]
Hi @imajit i made you an admin in Transifex. Now I'm going to install the app, thanks!

**Comment by jywarren** [comment]
Ah, i think it was already installed!

![image](https://user-images.githubusercontent.com/24359/123848601-e968c500-d8e5-11eb-8ce8-a17bc161fa85.png)

**Comment by jywarren** [comment]
And the project is already linked:

![image](https://user-images.githubusercontent.com/24359/123848776-16b57300-d8e6-11eb-82b2-10935958c963.png)

**Comment by jywarren** [comment]
Just noting also we went through some of these steps in https://github.com/publiclab/plots2/issues/9481

**Comment by jywarren** [comment]
Shall we try updating/syncing Spanish and French as a test-run?

**Comment by imajit** [comment]
Yeah, I think we can get a idea how the bot works from this

**Comment by imajit** [comment]
There is an error in the naming convention , the language files are named as `hi-IN` but when I pull it from the Transifex project it returns `hi_IN` , so I think we need to follow the same naming convention or else create the language resource in the Transifex project and then just pull it into our repository.

**Comment by imajit** [comment]
I was just testing the sync and somehow messed the resource file, i guess the conflict in file names lead to this :worried: , looking into it

**Comment by imajit** [comment]
I have added https://github.com/publiclab/plots2/blob/main/config/locales/en.yml to auto-update en.yml file based on this documentation https://docs.transifex.com/projects/updating-content#automatically-updating-source-files

**Comment by imajit** [comment]
I tried to export strings from the Github repository to the Transifex project, but it says URL not correct. It pointed it to the en.yml file in the main branch and also changed the project slug from master to main.
I changed the slug from `--master` to `--main`
![im3](https://user-images.githubusercontent.com/38528640/124753115-3da72100-df46-11eb-8c82-1f5fa365d079.png)
This is the updated URL 
![im2](https://user-images.githubusercontent.com/38528640/124753120-3ed84e00-df46-11eb-9c02-4454b574e5b5.png)
It shows failed to sync en.yml file in timeline
![im](https://user-images.githubusercontent.com/38528640/124753123-3f70e480-df46-11eb-97a9-6c9fca040d5c.png)

**Comment by imajit** [comment]
I want to try some ways suggested in the documentation to integrate Github Repo to Transifex, so to make sure I don't change the existing project I'm thinking of trying out things on a dummy project, and then once I figure out the right way, I'll do the same from the existing project.

**Comment by imajit** [comment]
I finally figured out what went wrong in importing the strings from Github to Transifex. The URL link to update the file needs to be a `raw` format of the file. This automates the importing strings to the Transifex part, so now Transifex keeps a check of the `en.yml` file and imports new strings as and when they are added.
![w](https://user-images.githubusercontent.com/38528640/124888897-27579e80-dff4-11eb-882b-2ff4f548ea9e.png)
Now, if we want to add new strings, all we need to do is add them to en.yml and Transifex will handle the syncing part.

**Comment by imajit** [comment]
On trying to sync the Transifex project with the Github Repository, some files fail to sync. Here is a snippet of the error log.
```
/config/locales/de.yml
Error while uploading translation: b"Could not import file: expected plurals rules '['other']' instead got '['one', 'other']' for resource string '174391802' and language 'de', expected plurals rules '['other']' instead got '['one', 'other']' for resource string '174391862' and language 'de', expected plurals rules '['other']' instead got '['one', 'other']' for resource string '174391822' and language 'de', expected plurals rules '['other']' instead got '['one', 'other']' for resource string '174391820' and language 'de'"
/config/locales/ru.yml
Error while uploading translation: b"Could not import file: expected plurals rules '['other']' instead got '['one', 'few', 'many', 'other']' for resource string '174391802' and language 'ru', expected plurals rules '['other']' instead got '['one', 'few', 'many', 'other']' for resource string '174391862' and language 'ru', expected plurals rules '['other']' instead got '['one', 'few', 'many', 'other']' for resource string '174391820' and language 'ru', expected plurals rules '['other']' instead got '['one', 'few', 'many', 'other']' for resource string '174391822' and language 'ru', expected plurals rules '['other']' instead got '['one', 'few', 'many', 'other']' for resource string '174391796' and language 'ru'"
/config/locales/pt-BR.yml
Error while uploading translation: b"Could not import file: expected plurals rules '['other']' instead got '['one', 'other']' for resource string '174391802' and language 'pt_BR', expected plurals rules '['other']' instead got '['one', 'other']' for resource string '174391862' and language 'pt_BR', expected plurals rules '['other']' instead got '['one', 'other']' for resource string '174391820' and language 'pt_BR', expected plurals rules '['other']' instead got '['one', 'other']' for resource string '174391822' and language 'pt_BR'"
/config/locales/gr.yml
Error while uploading translation: b"Could not import file: Language 'Italian (it)' specified in the YAML file does not match with the language 'Greek (el)' for which it was uploaded."
/config/locales/hi-IN.yml
Error while uploading translation: b"Could not import file: expected plurals rules '['one', 'other']' instead got '['other']' for resource string '174391829' and language 'hi_IN', expected plurals rules '['one', 'other']' instead got '['other']' for resource string '174391812' and language 'hi_IN', expected plurals rules '['one', 'other']' instead got '['other']' for resource string '174391852' and language 'hi_IN'"
/config/locales/es.yml
Error while uploading translation: b"Could not import file: expected plurals rules '['other']' instead got '['one', 'other']' for resource string '174391820' and language 'es', expected plurals rules '['other']' instead got '['one', 'other']' for resource string '174391822' and language 'es'"
/config/locales/ar.yml
Error while uploading translation: b"Could not import file: expected plurals rules '['other']' instead got '['zero', 'one', 'two', 'few', 'many', 'other']' for resource string '174391850' and language 'ar'"
```
Korean, Italian, French, and Chinese files sync properly. I'm not sure if this is a language-specific issue or something related to integration. Searching for more information about the errors.

**Comment by imajit** [comment]
This error is a language-specific issue and not related to integration, Transifex uses en.yml as the resource file and syncs all other translation files to it. If we compare the `units:` translations we can see that some units have `one:`,`other:` sub-parts in translation but the main en.yml file does not have it. This is the cause of the error.
https://github.com/publiclab/plots2/blob/7af4b026fa2d5d897af76800bda0b853bd6d7f8c/config/locales/en.yml#L1241-L1247
https://github.com/publiclab/plots2/blob/7af4b026fa2d5d897af76800bda0b853bd6d7f8c/config/locales/de.yml#L174-L188
I checked other files too and the reason is the same - inconsistency with the en.yml file. 
Either we can delete the inconsistent subparts or add them to all other YAML files that do not have it. I'm not sure which one would be better. What are your views on this ? @jywarren @grvsachdeva @ebarry

**Comment by jywarren** [comment]
Just circling back here - i think we agreed to file a question with the Transifex community and/or support (maybe both if it's possible?) 

This seems like a common problem that'd come up for many languages, and I'm curious what their preferred/best practice is.

**Comment by jywarren** [comment]
Thanks for your careful working through of this issue, @imajit !! Do i remember you had another possible idea, regarding a different version of the gem maybe?

**Comment by imajit** [comment]
> Thanks for your careful working through of this issue, @imajit !! Do i remember you had another possible idea, regarding a different version of the gem maybe?

I saw a discussion regarding Copycopter gem  https://github.com/publiclab/plots2/issues/3262#issuecomment-452375614

**Comment by jywarren** [comment]
OK - let's try to get a response from Transifex then. If you've opened a support request can you link it from here or otherwise update us here on the status of the conversation? Thank you!

**Comment by imajit** [comment]
Yes,   I opened an issue on the community page  https://community.transifex.com/t/plurals-rules-error-on-uploading-translation-file-to-transifex-project/2370

**Comment by ebarry** [comment]
Oh! Your post got a response yesterday: https://community.transifex.com/t/plurals-rules-error-on-uploading-translation-file-to-transifex-project/2370/2

**Comment by imajit** [comment]
Okay So the files are syncing correctly now. :100: ,but no PR is raised from Transifex, I'll try minimum threshold and see if any PR is generated 
![Screenshot 2021-07-22 at 03-56-52 The Publiclab org translation project on Transifex](https://user-images.githubusercontent.com/38528640/126567939-5a7f0592-5218-4d78-9a9b-c7af93d42642.png)

**Comment by imajit** [comment]
Okay, so it works, this was a manual sync. I think automatic sync would be triggered when the language file is completely reviewed

**Comment by imajit** [comment]
Closing this issue as importing new strings from Github to Transifex as well as from Transifex to Github is working

**Comment by jywarren** [comment]
This looks great. So where will the instructions for how to initiate this manually, or to manage it automatically, go? For example, is it OK that it tried to introduce many empty strings in #9939 -- they'll be detected and replaced with default language (english)?

**Comment by imajit** [comment]
Hey! 
Transifex initiates a [automatic-sync] when the language is 100% reviewed. 
For [manual-sync] we can go to integrations and we have "Send to Github" option which triggers a PR. This will check all the languages that are reviewed above the threshold percentage and make a PR for those languages, so in #9939 as only France has more than 1% reviewed strings it was pushed.
Regarding the empty strings, for now no :sweat_smile:,if you merge them then empty strings will be shown instead of default English translation. To merge the PR we need to change the Translation Function, for now, we check if translated strings are there or not [here](https://github.com/publiclab/plots2/blob/2d92f9e100e5e14d516774fc451ac6acab875266/app/helpers/application_helper.rb#L160), we need to add an additional check if they are empty.
I think we should do this because on every manual sync some new strings will be added, so instead of waiting for the entire language to be reviewed, we can regularly run manual sync and add new strings. What are your thoughts on this ? @jywarren

**Comment by jywarren** [comment]
That sounds great. Yes, so let's make a checklist of these items in your planning issue and go through them? Thanks @imajit this is great!
