### ISSUE TITLE
Weekly Community Check-In #108  - Think About Your Audience

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#9866]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Think About Your Audience

This was week's 5 Outreachy theme. We will twist it a little to fit the all contributors. This week lets discuss ways in which we can make PublicLab better for newcomers, both code contributors and website users. What are some terms, concepts that you are finding/ you found confusing when you first got started contributing or using the website. Feel free to suggest  what we can do to improve this experience for the next person.  Also feel free to share some terms or concepts you have learned while contributing to PublicLab.

If anybody is struggling or stuck on any issue, then feel free to comment down below. 

## Note to soc fellows
Thanks all for all the great work you are doing :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: 
Please update here on what you are working on this week and  if blocked on anything. Thanks

## This week's focus Issues

These are issues that are of high priority and requests from our
large community that use the software. 

https://github.com/publiclab/plots2/labels/high-priority

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note to contributors of the past two weeks

🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇
@gettinDrikkieWithIt, @AmandeepSingh285, @17sushmita, @Jayita10, @phyleria, @sab30-webdev, @Manasa2850, @BajajSmriti, @lonwabo-mnyaiza, @jywarren, @imajit, @Shashwat545, @cgrkzlkn, @anirudhprabhakaran3, @Shreyas220, @divs-2018, @tirthPatel177, @maximuusS, @unnati914, @noi5e, @maheshschand, @CaptainDrewBoy, @iamkrish-coder, @soham4abc, @simranbiswas, @waridrox, @TildaDares,  @jrogers-dev,  @KarAyushman, @afzal442, @darrylpoh,  @Rutwij12, , @yuma-fujimoto
🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇🥇

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by jywarren** [comment]
Really nice theme, @cesswairimu -- thanks! 

I am always still confused about asynchronous JS styles. Like Promises or async/await. I can puzzle through it and even write code in it, but it's not natural to me. 

I also struggle with the constantly changing "proper" way to manage things like dependencies, or "best practices"! They seem to change every year!

**Comment by cesswairimu** [comment]
Thanks Jeff,

I write a couple of ftos almost every week using first-timer bot and still have to look up if the branch prefix should be `first-timer` or `first-timers` I still don't know which one of the two it should be :smile:  
I also struggle with some js concepts despite writing some code every now and then :facepalm: 

Would anyone like to open next week's check-in?

**Comment by cesswairimu** [comment]
Am running out of ideas🤦... keeping this for another week. Thanks all

**Comment by 17sushmita** [comment]
Hi @cesswairimu, we can create a checkin on the topics we all proposed to learn as discussed in the meeting. 
Refer to this comment - https://github.com/publiclab/plots2/issues/9797#issuecomment-866286997

**Comment by unnati914** [comment]
I would be interested for check-in

**Comment by jywarren** [comment]
I'd also love to hear a brief one-line update from our @publiclab/soc team here, and each week! Thank you!!!

**Comment by NH709** [comment]
Hello ! Happy to be part of Public Lab @jywarren

**Comment by cesswairimu** [comment]
Hi all, welcome @NH709 :tada: :tada: 
thanks @17sushmita  :tada: :tada: ...  really great idea thanks :100: :100: 
thanks @unnati914  :tada: :tada:  ...you can open on Sunday evening or Monday..

**Comment by cesswairimu** [comment]
@unnati914  we have this temple https://github.com/publiclab/plots2/issues/new/choose (choose the `Weekly Check-in`) one that you can use... and feel free to ping me then if you need any help. Thanks again

**Comment by unnati914** [comment]
sure

**Comment by unnati914** [comment]
I have an idea.. for more people to take part in publiclab could we give an announcement on social platforms about our call and beginner friendly issues.. if that is allowed..

**Comment by soham4abc** [comment]
> I have an idea.. for more people to take part in publiclab could we give an announcement on social platforms about our call and beginner friendly issues.. if that is allowed..

That would be great!

**Comment by unnati914** [comment]
should i open the weekly check-in sunday evening?

**Comment by Tlazypanda** [comment]
Hey @unnati914 we usually open check-ins on Mondays/Tuesdays but I don't think anyone minds an early check-in 😛

**Comment by jywarren** [comment]
> I have an idea.. for more people to take part in publiclab could we give an announcement on social platforms about our call and beginner friendly issues.. if that is allowed..

I love this idea too! any time someone creates a new first-timers-only issue you're welcome to shout it out on social media. Or just in general to point at https://code.publiclab.org!

**Comment by unnati914** [comment]
sure! @Tlazypanda 💯

**Comment by unnati914** [comment]
moved to #9901 💯

**Comment by cesswairimu** [comment]
Thanks @unnati914  :tada: :tada:
