### ISSUE TITLE
Planning issue for advanced search UI

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#987]
This needs to be broken up into several sub-issues, some of which could be `first-timers-only` candidates:

https://publiclab.org/search/dynamic is a new search system based on the [RESTful API](https://github.com/publiclab/plots2/#api), but it has some rough edges. 

* [ ] some items appear more than once (need a uniqueness parameter somewhere?)
* [ ] limiting # of results and paginating with `.paginate()` as is done on many other parts of the site (will improve speed)
* [ ] shortening descriptions shown if paragraphs are too long
* [ ] possibly displaying author and how recently a piece of content was updated
* [ ] advertise dynamic search as a beta service at `/search`

and more?

![image](https://user-images.githubusercontent.com/24359/43337768-ba4d51ba-91a2-11e8-945c-194a0b065f81.png)

**Comment by Pk13055** [comment]
Have you reached some stand on which issues are to be tackled first? I could get a headstart if you've decided upon something

**Comment by jywarren** [comment]
I think a number of them could be broken out, but need hints to where they appear in lines of code. 

The `.paginate()` one is one which is probably in this controller -- but the dynamic search page action is empty: 

https://github.com/publiclab/plots2/blob/master/app/controllers/searches_controller.rb#L32

So I think it makes calls via JavaScript to other actions, but am not sure which. That needs some exploration (or input from @david-days?) and we could leave some helpful comments in that controller to describe what the actions do. 

I'm also not sure -- can we run `.paginate()` (a feature of `will_paginate_rails` gem) on these search records? 

As to the too-long descriptions, i think thatd be in javascript in this page of code, but am also not sure:

https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/dynamic_search.js#L155

For either of these, we could write tests (and examine existing ones) to confirm this, starting with this page and moving on to JavaScript testing in Jasmine:

https://github.com/publiclab/plots2/blob/master/test/functional/restful_search_test.rb

There is a simple unit test for search result documents here, and perhaps we could test out the pagination by adding a new test there, once we get more info on it: 

https://github.com/publiclab/plots2/blob/master/test/unit/doc_result_test.rb

So, plenty of starting places and investigating and adding comments is actually a good first step.

**Comment by jywarren** [comment]
Hi, this is for dynamic search, not search overall -- see leading link above. All of these are still up for grabs, as dynamic search may eventually replace standard search (i.e. http://publiclab.org/search/wind)

**Comment by stefannibrasil** [comment]
closed via #3357
