### ISSUE TITLE
Add new authoring template for blog posts

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#988]
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

Our blog, at https://publiclab.org/blog, could use a template for people posting; templates are at:

https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/editor.js#L101

This would help people write good blog posts, know how to structure them, etc. 

## Solution

Templates are in Markdown. A new line one be:

```js
    'blog': "###What I want to do or know\n\n###Background story"
```

Don't forget to get the commas right! 

But with a different template -- which could be:

```
### The beginning

<!-- Tell who you are and some background -->

### What we did

### Why it matters

### How you can help

```

You have to replace newlines with `\n` characters in the JavaScript code, but otherwise this should be pretty straightforward. But we're here to help!

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by wimpykid26** [comment]
Hello, since this issue is for newcomers, can I work on this ?

**Comment by jywarren** [comment]
We'd love your help on this and are happy to offer any assistance you might need. Thanks a lot!

Just curious -- we're trying to improve our outreach to new contributors -- how did you happen to hear about us?

**Comment by wimpykid26** [comment]
I was browsing through previous year's GSOC projects and happened to come across this !. Also, a friend of mine (who also contributes to this project) told me about this.

**Comment by jywarren** [comment]
OK, looking at your PR now. Thanks!

**Comment by jywarren** [comment]
Thanks a lot! 🎉 🎈
