### ISSUE TITLE
optimize tag autocompletion 

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#99]
Maybe by selecting fewer fields and/or sorting differently?

**Comment by ananyo2012** [comment]
I think this can be closed now. Here is the code that finds tag suggestions https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L172-L175 Presently tags are queried by matching the tagname and upto a maximum of 10 tag suggestions

**Comment by jywarren** [comment]
Here are the existing indices -- and I think we'll be relying on the solr search system for tag searches in the future, so I think we'll be OK to close this either way -- but curious if the name-based index here does the trick:

https://github.com/publiclab/plots2/blob/master/db/schema.rb.example#L371-L373
