### ISSUE TITLE
Replace "user map" link with "people" link in header menu

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#990]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled.

****
We have a still-unfinished link to "User map" which is not a good naming, nor is the feature complete. Let's comment it out and add a new one, to the https://publiclab.org/people listing. 

The template for the header menu is here:

https://github.com/publiclab/plots2/blob/master/app/views/layouts/_header.html.erb#L58

That line could be commented out with `<!-- ... -->` marks, and a new one could be added below, with a link to `/people` and text "People".

But the text itself will need to be set in the locales, so it can be translated; it'd look like: `<%= t('layout._header.projects.research.people') %>`

and have a matching entry just below this line: https://github.com/publiclab/plots2/blob/master/config/locales/views/layouts/_header/en.yml#L18

```
          users_map: "Users map"
```

**Comment by mridulnagpal** [comment]
I would like to work on this issue

**Comment by mridulnagpal** [comment]
#1018

**Comment by jywarren** [comment]
Closed in #1018!
