### ISSUE TITLE
Weekly Community Check-In #109 - UI/UX and its Importance 💯 

### ISSUE THREAD

**Issue by unnati914** [publiclab/plots2#9901]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Title - UI/UX 

All the mentors are requested to share resources on UI/UX and folks interested to learn about it can go through it 🥇 
If you have any resources for UI/UX, Frontend, designing etc. You are free to share here 💯. UI/UX is a very crucial aspect of your mobile application. In order to make your app successful, you must provide an amazing user interface and user experience through your app. By understanding the need of your target audience and their market preference, you can make your app interactive and more engaging. UI designers focus on user experience by designing easy-to-navigate software for all types of digital products like websites, applications, and other interactive devices. UX refers to the user experience design. It includes the overall experience that a user has as they interact with a website.

## This week's focus Issues

These are issues that are of high priority and requests from our
large community that use the software. 

https://github.com/publiclab/plots2/labels/high-priority

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note for past two weeks contributors 
@jywarren , @17sushmita , @Manasa2850 , @abhiprojectz , @sashadev-sky , @imajit , @pranavaddepalli , @aliciapaz , @icarito 

🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by cesswairimu** [comment]
Great theme Thanks @unnati914  for opening this :tada: :tada:

**Comment by anirudhprabhakaran3** [comment]
Hello! It's been a long time since I've logged in here. (had some issues with the laptop)

This is a great theme. Right now, I'm also trying to improve the UI/UX of one of my college projects, and honestly, it's difficult! No wonder why UI/UX designers get paid so much. One of my favourite resources is the RefactoringUI book, which one of my seniors so kindly sent to me. It's an amazing book, and great for anyone and everyone who is interested in UI/UX.

Would love to hear from the others!

**Comment by unnati914** [comment]
yes @anirudhprabhakaran3 its a great book  I am also exploring UI/UX since two months and trust me its difficult ! So thought of opening the weekly check in with this theme.

**Comment by unnati914** [comment]
thank you @cesswairimu for the opportunity 💯

**Comment by waridrox** [comment]
Hi all 👋, cool theme @unnati914! 🌈 though I prefer blogs/vids rather than reading books cause I'm too lazy :P

- I personally follow UI Design Daily which sends latest UI trends straight to your inbox so you're up in sync what's trending in the market - https://www.uidesigndaily.com
- Other than that I follow Punit Chawla which talks about UI/UX in a really cool manner on YT - https://www.youtube.com/c/PunitChawla/featured
- Even Google is revamping it's design game with the recent announcement of Material You at Google I/O which is going to be the future design language after Material UI in Android 12 for example - https://youtu.be/UHQPdP8qgrk

**Comment by abhiprojectz** [comment]
@waridrox  That's so nice.

And @unnati914  Its a nice theme.

Here is list of something awesome that, i found interesting:

- https://github.com/alexpate/awesome-design-systems
- https://github.com/gztchan/awesome-design
- https://github.com/kevindeasis/awesome-ui
- https://github.com/wasabeef/awesome-android-ui
- https://github.com/netoguimaraes/awesome-ux
- https://github.com/goabstract/Awesome-Design-Tools

**Comment by jywarren** [comment]
Hi all! Love the theme too @unnati914 -- thanks!

We have this style guide which we developed to help people with the particular challenges of UI/UX within Public Lab spaces: https://publiclab.org/notes/warren/05-07-2019/introducing-a-draft-style-guide-for-public-lab

It was a super in-depth process, but the output is pretty useful and not too long!

**Comment by daemon1024** [comment]
Hey all, love the theme @unnati914 🤩. Found a lot of cool resources in the thread 🙌 I personally just scroll through Dribbble or Behance and look at what awesome things folks are working in the UI/UX space.

**Comment by Tlazypanda** [comment]
Hey great theme @unnati914 :tada: I personally am not really great in this space but I follow Pablo Stanley founder of Blush for his great illustrations and sense of humour :D do check him out whenever you can :p

**Comment by Tlazypanda** [comment]
Also folks if any of you are interested to open next week's check-in do let us know :100:  feel free to reach out if you need ideas for the theme too :smile:

**Comment by unnati914** [comment]
moved to #9920 💯
