### ISSUE TITLE
Add First Timers landing page to prominent README position

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#994]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem
First-timer contributors currently often land at:

https://github.com/publiclab/plots2/labels/first-timers-only

or even just generally:

https://github.com/publiclab/plots2/labels/help-wanted

We now have a great new First-Timers landing page at:

https://github.com/publiclab/plots2/projects/2

It's friendly and welcoming -- see this screenshot:

![screen shot 2016-11-18 at 11 18 38 am](https://cloud.githubusercontent.com/assets/24359/20437136/d92a39ac-ad80-11e6-8b89-f4d10f0e23af.png)

## Solution

We should link to it in a prominent and welcoming way in our README, with a friendly note (for example, sourcing text from the landing page itself. 

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/developers) if you have questions!

**Comment by Vehikite-John** [comment]
I would like to claim this issue. This is my first time contributing, so I may have some questions along the way, but I'll at least work on getting the repo set up on my laptop. I'll keep you posted on my status.

**Comment by imsarath** [comment]
Hello,
I'd like to work on this issue.
Could you please mark it as `in-progress` ?

**Comment by jywarren** [comment]
We'd love your help on this and are happy to offer any assistance you might need. Thanks a lot!

Just curious -- we're trying to improve our outreach to new contributors -- how did you happen to hear about us?

**Comment by imsarath** [comment]
I was looking for interesting rails projects on first-time-users-only and stumbled onto public lab when i saw the word "DIY".

**Comment by jywarren** [comment]
Thanks a lot -- we really appreciate your contribution! 👍 🎈
