### ISSUE TITLE
Weekly Community Check-In #111 - Cloud Computing and it's applications

### ISSUE THREAD

**Issue by sakshamlamba109** [publiclab/plots2#9953]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

Title - Cloud Computing and it's Applications
Hi there!! This week we will be talking about how Cloud Computing has revolutionised the technical world by discussing about it's various applications. Please feel free to share any project, resource related to this particular domain :)

Why Cloud ?
Cloud Computing provides resources like compute, storage, network etc. to it's users over the internet, and the users need to pay only for the resources used. Cloud has become an important part in development and nearly every technology uses the resources offered by the Cloud. Not just only the underlying infrastructure, but Cloud also provide developers with a platform and even fully deployed applications.

This week's focus Issues
These are issues that are of high priority and requests from our
large community that use the software.

https://github.com/publiclab/plots2/labels/high-priority

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

Thank you note to focus issues contributors
@jywarren , @ebarry  , @imajit , @Jordan-Rob  , @jayeritz  , @DmitriiOxen  , @Pandademic  , @17sushmita  , @daemon1024

💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯

Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

Thanks everyone for making Public Lab awesome ❤️
Have a great week ahead all 🎈

**Comment by unnati914** [comment]
Thank you @sakshamlamba109 for opening the issue 
Some videos for cloud computing 👍 
https://www.youtube.com/watch?v=RWgW-CgdIk0

**Comment by sakshamlamba109** [comment]
Thankyou!!
Also, I've written some articles on this domain as well. One of which is published by RedHat:
Do give it a read:
https://www.redhat.com/sysadmin/creating-backup-data

Another one:
https://virtandcont.blogspot.com/

**Comment by TildaDares** [comment]
Thank you @sakshamlamba109 and @unnati914 for the cloud computing videos and articles.

**Comment by unnati914** [comment]
Thanks @TildaDares 💯

**Comment by sakshamlamba109** [comment]
Thankyou @TildaDares  :)

**Comment by jywarren** [comment]
Hi all! Sage Sharp of Outreachy passed this along:

> The Linux Foundation is running a survey to measure diversity, equity, and inclusion in open source. Anyone who uses, contributes to, or thinks about open source is welcome to fill it out:

> https://www.research.net/r/PZ9J8QN

> Please share this link widely so the survey results can be representative of the whole open source user base and community members.

Thanks for the check-in, everyone!

**Comment by cesswairimu** [comment]
Hi everyone :wave:, nice check-in

Anyone with some a little time to spare, I would like help testing https://github.com/publiclab/plots2/pull/9897...
*To help :* what you need to do is open it on gitpod(using the link on pull request) and let me know if the browser launches fine on your end or not...you could leave a comment here or on the pull request. thanks in advance :smile:  and happy Sunday all

**Comment by sakshamlamba109** [comment]
Hey @cesswairimu, the browser launched successfully!!

**Comment by cesswairimu** [comment]
Thanks a bunch @sakshamlamba109 🎉🎉

**Comment by sakshamlamba109** [comment]
Your welcome @cesswairimu!!

**Comment by daemon1024** [comment]
Hello 👋🏽 ,

Interesting topic 🙌🏽. Containers and Docker are an important part in the cloud ecosystem. I highly recommend https://devopswithdocker.com/ if you are starting out with docker :)

I like to watch videos from https://www.youtube.com/ibmcloud they are quick, well explained dive into various cloud related technologies and terminologies.
