### ISSUE TITLE
Profile images on profile page aren't lazy loading

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#9957]
https://github.com/publiclab/plots2/blob/e646cfd248e46fe9cf11a2eb7860bbf29f949b7d/config/initializers/lazyload.rb#L2

this line is supposed to show the grey 1x1 px gif until it loads the real image:

https://github.com/publiclab/plots2/blob/ca12d6238415f328d7e734521c30c62249f6a2f2/app/views/users/profile.html.erb#L49

![image](https://user-images.githubusercontent.com/24359/127210502-232c7f14-c8e7-46c0-be14-45f45b08404e.png)

But it's not working! Hmm...

URLs are: https://storage.googleapis.com/publiclab-production/public/system/users/photos/000/000/001/thumb/aseprite_templates.png

**Comment by jywarren** [comment]
After re-uploading that file while editing my profile, it works. 

https://publiclab.org/profile/liz doesn't though --

And now i've uploaded a second image: https://storage.googleapis.com/publiclab-production/public/system/users/photos/000/000/001/thumb/Screen_Shot_2021-07-27_at_2.50.03_PM.png

![image](https://user-images.githubusercontent.com/24359/127211106-53fe72bf-b52f-4a78-a739-c1989f84c440.png)

It looks to me to not be incrementing. Or not generating the path correctly.

**Comment by jywarren** [comment]
Do we need to configure profile images like we did here, somehow?

https://github.com/publiclab/plots2/pull/9807/files#diff-7f9b82fa0c235726052743e6cf2f484d762326c44b93c7b01f24706d8d26e5deR7

**Comment by jywarren** [comment]
Aha - we had set the path differently here: 

https://github.com/publiclab/plots2/blob/ca12d6238415f328d7e734521c30c62249f6a2f2/app/models/user.rb#L41-L42

Let's modify that to match?

**Comment by jywarren** [comment]
Noting then that we may have 2 issues:

* [ ] old profile images don't work site-wide, for example in the navbar when logged in
* [ ] new (and old) profile images don't display on top right side of profiles like https://publiclab.org/profile/liz

#9958 focuses on the first one. After that let's solve the second!

**Comment by jywarren** [comment]
We think profile images weren't copied into Google Storage. We'll copy them in and see what happens. I think it may just start working? Fingers 🤞

**Comment by ebarry** [comment]
🤞 indeed! as of now, my profile picture is still not displaying.

**Comment by jywarren** [comment]
This is still in testing, sorry @ebarry - i meant start working after we push it to our "unstable" testing server. Thanks for your patience!

**Comment by icarito** [comment]
I'm actually finding photos, but not under /public/system/users/photos , rather under /public/system/profile/photos. E.g. https://storage.googleapis.com/publiclab-production/public/system/profile/photos/7/original/384404446-square.png - could we have a routing issue?
