### ISSUE TITLE
Tag input showing incorrect HTML

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#9961]
![Screen Shot 2021-07-28 at 8 53 31 AM](https://user-images.githubusercontent.com/24359/127325358-020e1e2d-6fc9-4a74-80e4-e10b31f5900e.png)

follow up to https://github.com/publiclab/plots2/pull/9938

Hi @imajit @Tlazypanda @noi5e - just noting that after merging 9938 i saw this slight oddness in the tag input. Is it possible there's an improperly nested quotation mark?

Would you mind taking a look? I'd like to publish a fix relatively soon. No big deal but would be good to resolve! Thank you!

**Comment by imajit** [comment]
Yes, sorry I missed it. The quotation mark is misplaced. I'll fix it asap 😬
