### ISSUE TITLE
Commenting some of the lines 

### ISSUE THREAD

**Issue by unnati914** [publiclab/plots2#9967]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [PULL_REQUEST_TEMPLATE.md](https://github.com/publiclab/plots2/blob/main/.github/PULL_REQUEST_TEMPLATE.md) in the `plots2` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
+ <!-- Add a short description about your change here-->

- Fixes #0000 (<=== Add issue number here)
+ Fixes #0000 <!--(<=== Add issue number here)-->

- We're happy to help you get this ready -- don't be afraid to ask for help, and don't be discouraged if your tests fail at first!
+ <!--We're happy to help you get this ready -- don't be afraid to ask for help, and don't be discouraged if your tests fail at first!-->

- If tests do fail, click on the red X to learn why by reading the logs.
+ <!--If tests do fail, click on the red X to learn why by reading the logs.-->

- Please be sure you've reviewed our contribution guidelines at  https://publiclab.org/contributing-to-public-lab-software
+ <!-- Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

- Thanks!
+ <!--Thanks!-->
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by steves14** [comment]
I would like to take this issue. Please assign to me if that's cool

**Comment by DalilaBA** [comment]
@steves14 yu don't wait an assignement, you go to the file and make the changes, and then you pull a request

**Comment by anirudhprabhakaran3** [comment]
Hey @steves14 ! You don't have to wait for it to be assigned to you. If no one else is working on the issue (as is in this case), you can just drop a comment stating that you're working on this, and start working! Thank you!

**Comment by DalilaBA** [comment]
#9969

**Comment by anirudhprabhakaran3** [comment]
> Hey @steves14 ! You don't have to wait for it to be assigned to you. If no one else is working on the issue (as is in this case), you can just drop a comment stating that you're working on this, and start working! Thank you!

Seems like someone else has already made a PR for the issue! Sorry for the confusion. Feel free to try out some other first-timers-only issue! Just check that no one is working on it, mention that you are working on it, and you should be good to go!

**Comment by Ash-KODES** [comment]
How will i get to know,if someone is working on the issue or not?

**Comment by anirudhprabhakaran3** [comment]
Usually someone will have dropped a message, saying that they wanted to work on it. That means someone is working on it. If there has been no progress even after around a week, you can ask the person just to confirm that they still are working on the issue.

**Comment by DalilaBA** [comment]
> How will i get to know,if someone is working on the issue or not?

hi @Ash-KODES I updated and pulled a request yesterday on that file

**Comment by luckych8080** [comment]
I claim this issue.

**Comment by luckych8080** [comment]
Done
please review :)

**Comment by noi5e** [comment]
> I would like to take this issue. Please assign to me if that's cool

@steves14 Sorry for the confusion, yes, definitely go ahead and leave a comment on an issue if you don't see anyone else claiming it. No need to wait for someone to assign to you.

@Ash-KODES @DalilaBA I'm sorry I closed your pull requests, but I saw that you had other PRs that were open/merged so I went ahead and merged @luckych8080's.
