### ISSUE TITLE
Update our supporters

### ISSUE THREAD

**Issue by daemon1024** [publiclab/plots2#9971]
We have listed projects that support us at https://github.com/publiclab/plots2/blob/main/doc/SUPPORTERS.md

We have changed some of our projects, so we should update them in this page like `Coveralls` -> `Codecov`

**Comment by Ash-KODES** [comment]
OK  I AM WORKING ON THIS :)
THANK YOU MENTOR!!

**Comment by Ash-KODES** [comment]
I have made a pull request please review it mentors!!
