### ISSUE TITLE
Add a hover text on the lock button

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#9978]
This is subtask to #9888
Add a popover on hover instead of click?(explore if this is possible) When a contributor sees the `disabled` sign first, they might not bother to click and read why they can't add tags.

It would also be really helpful if contributors could hover over the lock icon on a locked page to see why it has that icon.

<img width="606" alt="Screenshot 2021-07-09 at 10 06 24" src="https://user-images.githubusercontent.com/63427719/125053702-5544ed80-e09d-11eb-9f95-95073098d926.png">

_Originally posted by @TildaDares in https://github.com/publiclab/plots2/issues/9888#issuecomment-877031292_

**Comment by jcads** [comment]
Can I work on this one?

**Comment by cesswairimu** [comment]
Hi @jcads, sure, please go ahead. Thanks

**Comment by jcads** [comment]
Hi @cesswairimu I'm sorry something came up and I think I could not push through with this. If anyone wants to work on this. Feel free to do so

**Comment by cesswairimu** [comment]
No worries @jcads .. thanks

**Comment by noi5e** [comment]
I think we could break this down a little further so a new contributor could understand it. (TBH I'm still not fully there yet 😅)

It looks like the lock icon this is talking about is located here:
https://github.com/publiclab/plots2/blob/aeb6c35f16c1944f1f524becae3c710ed4282822/app/views/notes/show.html.erb#L29-L33

We can add a hover tooltip by copying this example:
https://github.com/publiclab/plots2/blob/aeb6c35f16c1944f1f524becae3c710ed4282822/app/views/notes/show.html.erb#L104

What do we want the hover text to say exactly? `New contributors are not allowed to create drafts` or something like that? @TildaDares

**Comment by TildaDares** [comment]
@Manasa2850 will probably be able to answer this better but I think the text could be `New contributors are not allowed to add tags to a note. See ——- to read more about this`

**Comment by sakshamlamba109** [comment]
Hey!! Can I work on this issue?

**Comment by arushisinha09** [comment]
Hey , Can i work on this?

**Comment by noi5e** [comment]
@sakshamlamba109 Go ahead, since you were first, and maybe if you get stuck @arushisinha09 you can help them out?

**Comment by arushisinha09** [comment]
ya sure

**Comment by sakshamlamba109** [comment]
> @sakshamlamba109 Go ahead, since you were first, and maybe if you get stuck @arushisinha09 you can help them out?

okay thanks!!

**Comment by Manasa2850** [comment]
Hi everyone! It's not just for new contributors, anyone other than admin / moderators cannot add tags on a locked note. We can keep the text on hovering as ` Only admins / moderators can add tags on locked content.` similar to what I've done [here](https://github.com/publiclab/plots2/pull/9733#issuecomment-855599662), to maintain uniformity.

**Comment by DalilaBA** [comment]
Hi guys, I might have a little problem with the PR, and I think that it was an old commit that I forgot, I didn't now how to delete it, and even now I don't now how to fix the error, please help
