### ISSUE TITLE
Image shortlinks aren't redirecting to correct image size

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#9979]
https://publiclab.org/i/44535.png?s=t is supposed to redirect to 

https://storage.googleapis.com/publiclab-production/public/system/images/photos/000/044/535/thumb/Screen_Shot_2021-05-28_at_1.29.16_PM.png

but is instead pointed at:

https://storage.googleapis.com/publiclab-production/public/system/images/photos/000/044/535/original/Screen_Shot_2021-05-28_at_1.29.16_PM.png

Relevant code:

https://github.com/publiclab/plots2/blob/5c8fd13d726d99f43ae87fad873e639bcc5aec79/app/controllers/images_controller.rb#L7-L17

You should be able to set sizes using this syntax - https://publiclab.org/i/44534.png?s=t, https://publiclab.org/i/44534.png?s=m, https://publiclab.org/i/44534.png?s=l (for small, medium, large) but I think the new file storage we published may be routing everything to original size?

We may need (a)icarito's help on this but he may not be available right now.

**Comment by ebarry** [comment]
Thank you for spotting this!

**Comment by anirudhprabhakaran3** [comment]
I think the issue is here
https://github.com/publiclab/plots2/blob/5482fc868ac96a9b0622b50aaaee7b3003033b72/app/models/image.rb#L35-L42

The only two types of images that are being parsed are either original or medium. i think removing the else condition should do the trick

**Comment by ebarry** [comment]
Thank you for investigating this @anirudhprabhakaran3! Would you be interested in trying to make a PR to fix this?

**Comment by anirudhprabhakaran3** [comment]
Yes! I'll make a PR for it
