### ISSUE TITLE
Calculate view count of a page

### ISSUE THREAD

**Issue by ananyo2012** [publiclab/plots2#998]
Presently view counts are calculated by simple page refreshes which is a little wobbly. So page views are non-unique. We need to create view counts that are unique with respect to a specific IP or user. One way to do this is by using the [impressionist](https://github.com/charlotte-ruby/impressionist) ruby gem.

**Comment by jywarren** [comment]
Hi, Ananyo -- I believe there's another issue open for this, but without
the specific gem recommendation you've made here. Would you mind looking
around a little for it (i think it was by jitesh or perhaps another GSoC
student) and merging? Thanks!

**Comment by ananyo2012** [comment]
Ok sure Jeff. Will close this after I find that.

**Comment by ananyo2012** [comment]
No such issue open @jywarren. So we can go on with this.

**Comment by jywarren** [comment]
Ah, i finally found it! Sorry, when I'd mentioned it I wasn't at my computer and couldn't search thoroughly. Here it is -- we can close it and just direct people to this one, if you like? 

https://github.com/publiclab/plots2/issues/425

**Comment by ananyo2012** [comment]
Sure I will close this one and redirect to that one.
