### ISSUE TITLE
Weekly Community Check-In #112 - Machine Learning

### ISSUE THREAD

**Issue by sakshamlamba109** [publiclab/plots2#9981]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Title  - Machine Learning
This week share about Core concepts of Machine Learning, the resources, learning etc. 💯 

## This week's focus Issues

These are issues that are of high priority and requests from our
large community that use the software. 

https://github.com/publiclab/plots2/labels/high-priority

We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these.
We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note to focus issues contributors

Thanks so much on contributing to Public Lab 💯 
@jywarren , @17sushmita , @Manasa2850 , @TildaDares , @noi5e , @anirudhprabhakaran3 , @imajit , @daemon1024 , @saraswathy-krish , @roshni-patel , @atayl16 , @adrnna 

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

*Thanks everyone for making Public Lab awesome* :heart:  
Have a great week ahead all :balloon:

**Comment by anirudhprabhakaran3** [comment]
Hello everyone!

Machine Learning..ooh. The hot word of the moment. ML is nearly everywhere. I am taking a few introductory courses on edX and Coursera on ML/AI, but I personally find that I need to work on my math for me to get a better grasp on what it actually is.

(As a side note, I'd like to open the weekly check-in for next week, if that's okay with everyone!)

**Comment by Tlazypanda** [comment]
Hey @anirudhprabhakaran3 yes please feel free to open the check-in much appreciated :heart: 

As far the topic is considered I recently completed a machine learning internship and did a small writeup of my experience 
https://medium.com/@mishrasneha.bb/notes-smart-autocomplete-my-intuit-internship-experience-b5e3a051110c
 
p.s Andrew Ng is the ML God :100:

**Comment by Tlazypanda** [comment]
Also Inviting other @publiclab/soc folks to share their experiences in this domain :tada:

**Comment by sakshamlamba109** [comment]
> Hello everyone!
> 
> Machine Learning..ooh. The hot word of the moment. ML is nearly everywhere. I am taking a few introductory courses on edX and Coursera on ML/AI, but I personally find that I need to work on my math for me to get a better grasp on what it actually is.
> 
> (As a side note, I'd like to open the weekly check-in for next week, if that's okay with everyone!)

Sure @anirudhprabhakaran3 go for it!!
