### ISSUE TITLE
Speed up GitHub Actions test runs/checks by caching dependencies

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#9983]
I suspect we may not be caching properly and wanted to suggest we try this out:

https://dev.to/github/caching-dependencies-to-speed-up-workflows-in-github-actions-3efl

We have gem caching supposedly installed here, so let's confirm it's working:

https://github.com/publiclab/plots2/blob/a578843b8127c1bf96c5bc023b673a652b0cd074/.github/workflows/tests.yml#L53-L59

Likewise we should be able to cache javascripts from the `yarn install` line. Let's see what we can do to improve our load times!

Currently here is where we stand:

![image](https://user-images.githubusercontent.com/24359/128056426-1559eab2-5fa3-4b1e-a101-1874fb70d0b4.png)

You can read through our logs here:

https://github.com/publiclab/plots2/actions/runs/1090845487

**Comment by noi5e** [comment]
Reading up on this now. Here's what [GitHub Actions's docs](https://github.com/actions/cache/blob/main/examples.md#ruby---bundler) say about caching Ruby gems:

> Caching gems with Bundler correctly is not trivial and just using actions/cache is not enough.

> Instead, it is recommended to use ruby/setup-ruby's bundler-cache: true option whenever possible:

```
- uses: ruby/setup-ruby@v1
  with:
    ruby-version: ...
    bundler-cache: true
```

That seems to be what we're doing here:
https://github.com/publiclab/plots2/blob/5482fc868ac96a9b0622b50aaaee7b3003033b72/.github/workflows/tests.yml#L51-L59

🤔

**Comment by noi5e** [comment]
What are the indications that Ruby gems are NOT being cached correctly?

Here's the [unit test run](https://github.com/publiclab/plots2/runs/3222445809?check_suite_focus=true) from the most recent logs @jywarren posted:
```
bundle install
  /opt/hostedtoolcache/Ruby/2.6.6/x64/bin/bundle config --local path /home/runner/work/plots2/plots2/vendor/bundle
  /opt/hostedtoolcache/Ruby/2.6.6/x64/bin/bundle config --local deployment true
  Cache key: setup-ruby-bundler-cache-v3-ubuntu-20.04-ruby-2.6.6-Gemfile.lock-c3c1488c69b07d2f3f5aff65476c89408928cde98964b01410ba5c94aa79b8fa
  Received 134217728 of 252020325 (53.3%), 128.0 MBs/sec
  Received 252020325 of 252020325 (100.0%), 144.4 MBs/sec
  Cache Size: ~240 MB (252020325 B)
  /usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/0e2d6d88-3fa0-468f-818e-a408927ef433/cache.tzst -P -C /home/runner/work/plots2/plots2
  Cache restored successfully
  Found cache for key: setup-ruby-bundler-cache-v3-ubuntu-20.04-ruby-2.6.6-Gemfile.lock-c3c1488c69b07d2f3f5aff65476c89408928cde98964b01410ba5c94aa79b8fa
  /opt/hostedtoolcache/Ruby/2.6.6/x64/bin/bundle install --jobs 4
```

Later on in the same run:
```
...
  Using whenever 1.0.0
  Using will_paginate 3.3.0
  Using will_paginate-bootstrap4 0.2.2
  Bundle complete! 107 Gemfile dependencies, 266 gems now installed.
  Bundled gems are installed into `./vendor/bundle`
  Took   6.25 seconds
```

🤔

**Comment by noi5e** [comment]
To spell out my thoughts from the last comment, `Cache restored successfully` makes me think that the run **IS** caching Ruby gems. But then later on in the run, `Bundle complete! 107 Gemfile dependencies, 266 gems now installed.` makes me think that it isn't? 🤷

**Comment by noi5e** [comment]
I'm going to give it a shot, and make a PR attempting yarn dependency caching according to [these docs](https://github.com/actions/cache/blob/main/examples.md#node---yarn). 

Let's see how this goes! Working with GitHub Actions in this way is new for me.
