### ISSUE TITLE
Move "Lock note" link into sidebar "advanced tagging" dropdown menu

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#9988]
The new link prompting admins and mods to lock a note is currently in the main column of notes, as shown here:

![image](https://user-images.githubusercontent.com/24359/128076434-60daec58-a339-475a-acd9-1a71935f5b3f.png)

Let's move it into the sidebar "advanced tagging" dropdown menu shown here:

![image](https://user-images.githubusercontent.com/24359/128076393-31febedb-588f-480b-ae57-3bd26792a5a5.png)

This could be a nice FTO! Thanks!

**Comment by Ash-KODES** [comment]
CAN YOU PLEASE EXPLAIN THE ISSUE MORE DISCRIPTIVELY,I AM READY TO HELP:)

**Comment by Manasa2850** [comment]
@Ash-KODES this is a simple one. Currently the `Lock Note` option is there in the main page of the research note. We need to move this to the advanced tagging menu, the code for which is present in `app/views/tag/_advanced_tagging.html.erb`. 
You can work on this one. Let me know if you need any help!

**Comment by Ash-KODES** [comment]
ok i am working on it
thank you mentor

**Comment by Ash-KODES** [comment]
@Manasa2850 can you please guide me 
i am not able to get trace html files in repo of things i am working on!
please leave the link of reaserch note html file?

**Comment by noi5e** [comment]
@Ash-KODES You can search for phrases in GitHub, or in the repository files if you `git clone`d them to your computer.

I just searched for `Lock Note` and I found the partial here:
https://github.com/publiclab/plots2/blob/aeb6c35f16c1944f1f524becae3c710ed4282822/app/views/notes/show.html.erb#L93-L95

Try to take it from here and if you get stuck just leave a comment again! 🤗

**Comment by Ash-KODES** [comment]
> @Ash-KODES You can search for phrases in GitHub, or in the repository files if you `git clone`d them to your computer.
> 
> I just searched for `Lock Note` and I found the partial here:
> https://github.com/publiclab/plots2/blob/aeb6c35f16c1944f1f524becae3c710ed4282822/app/views/notes/show.html.erb#L93-L95
> 
> Try to take it from here and if you get stuck just leave a comment again!

thankyou this was really helpfull
