### ISSUE TITLE
research note dropdown menu not completely visible!

### ISSUE THREAD

**Issue by Ash-KODES** [publiclab/plots2#9999]
![issue_reasearch_note_dropdown_menu](https://user-images.githubusercontent.com/84193017/128638230-b7d35c1a-7ecc-4ee4-a97b-229c62cb6127.png)

**Comment by noi5e** [comment]
I'm reproducing this bug by visiting https://publiclab.org/tag/research-notes and clicking on the three-dot dropdown menu:
<img width="674" alt="Screen Shot 2021-08-08 at 11 59 24 AM" src="https://user-images.githubusercontent.com/4361605/128642847-00195b76-ed73-4438-a0e8-0cdda2495d7c.png">

It looks like there are two distinct `<div id="container">`s on the page, one for the `research-notes` tag card, and one for the rest of the page:
<img width="767" alt="Screen Shot 2021-08-08 at 12 01 08 PM" src="https://user-images.githubusercontent.com/4361605/128642920-2a21d92a-5129-4d10-afa0-8b4a250804ca.png">

The partial for the tag card is at `app/views/tag/show/_user_controls.html.erb`.  I think the other one is at `app/views/tag/show.html.erb`.

Maybe playing with the CSS z-index property on one of the containers will fix this. This seems like a fun one to work on. Any takers? 😄

**Comment by Ash-KODES** [comment]
I would like to contribute for this issue:)

**Comment by noi5e** [comment]
@Ash-KODES Go ahead!

**Comment by ebarry** [comment]
How's it going @Ash-KODES ? Want to check-in re: what you're working on so far?

**Comment by Ash-KODES** [comment]
The concerned element has been given the position property as absolute, but still, even after giving it a z-index of '20000'(inside the chrome's developer tools), it is not coming above the below container. I am not coming up with any other ideas, if anyone is able to provide any solution, please help me out.

**Comment by noi5e** [comment]
@Ash-KODES Thanks for researching this issue! 

I guess my `z-index` idea didn't work out. Looks like the solution will require a lot more experimentation... I think you have the right idea playing with the CSS in Chrome DevTools, that's what I would do too.

Maybe adjust the height of the containing `section` element? Or maybe it's the `section` element that needs the `z-index` property changed? 🤷 If you can play around with it some more, I think you'd learn a lot! And it seems like it's a much-needed change.

**Comment by Ash-KODES** [comment]
ok I will try some more then...
and yaa I got to learn many things which i didnt knew:)
thank you!

**Comment by ebarry** [comment]
This issue is 🎶 partying like it's #9999 🎶 
Thank you, i saw this too and i may have also created an issue about this.

**Comment by Hina-softwareEngineer** [comment]
**I want to contribute to this issue. But I am unable to reproduce the issue. As I don't get dots(dropdown openner) on my webpage.**


![z](https://user-images.githubusercontent.com/56507951/135767316-f4cffb12-318b-4b43-839b-bada0f798847.png)
.

**Comment by TildaDares** [comment]
Hi @Hina-softwareEngineer, you have to be logged in to see the ellipsis menu.

**Comment by Hina-softwareEngineer** [comment]
@TildaDares  @noi5e  I have figure out the issue. Its because of `overflow` : `hidden` property set to parent container in which card and dropdown is present. That's why we are unable to view the full dropdown. by removing that property in chrome Devtools. Now, the bottom box-shadow of card can be seen.  It looks like this:


![z](https://user-images.githubusercontent.com/56507951/135901208-f8529121-d018-45b1-98dc-1234d2ffb976.png)


If this picture is to be okay, Can I make a pull request or Do you want some change? Any feedback is welcome :)
Thanks Tilda for telling me to sign In to view the dots.

**Comment by TildaDares** [comment]
Amazing detective work @Hina-softwareEngineer! Yes you can open a PR.
